### ISSUE TITLE
Wrong Navigator's yAxis title position

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#10007]
#### Actual behaviour
The Navigator's yAxis title has incorrect position. When the `title.rotation` is set to 0, then text is partially goes out of the chart container (is cropped). It's caused by wrong calculation of element `x` value, which has the negative value.

_Note:
This issue is more visible on Windows platform, where the value is even smaller than on OSX._

#### Live demo with steps to reproduce
https://jsfiddle.net/otm3j2q9/

Windows:
![image](https://user-images.githubusercontent.com/15111955/51838621-2096ae80-2307-11e9-8876-70b7e46e04cc.png)

OSX:
<img width="498" alt="screenshot 2019-01-28 at 14 20 06" src="https://user-images.githubusercontent.com/15111955/51838871-dc57de00-2307-11e9-842d-9cefdeb58636.png">

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
We didn't design the navigator for showing axis titles - it is intended as a simple navigation tool for the main axis. So by adding a title to the Y axis we have come across a case that we haven't seen before.

By default it is simply disabled:
https://github.com/highcharts/highcharts/blob/6d6773e2afada06fa0931c4b1a949b02b64bafd3/js/parts/Navigator.js#L534-L536

May I ask what is the use case for adding a title for the navigator Y axis?

**Comment by TorsteinHonsi** [comment]
I think the problem in the demo is that we don't consider the size of the navigator axis title when we do the layout, like we do with regular Y axes. So this can be overcome by manually adjusting things like `chart.marginLeft`, `yAxis.title.x` and `yAxis.title.y`. See https://jsfiddle.net/highcharts/wb25ptzL/4/
