### ISSUE TITLE
Wrong legend value on series mapping

### ISSUE THREAD

**Issue by kai2468** [highcharts/highcharts#10005]
#### Expected behaviour
Would expect the legend to stay the same if the series mapping is changed

#### Actual behaviour
Legend value changes from "Column 1" to "Column 2"

#### Live demo with steps to reproduce
http://jsfiddle.net/h6L7r2vw/
- At start legend is set to Column 1
- Remove label: 0 from series mapping
- Now legend is set to Column 2

#### Product version
Latest

**Comment by kai2468** [comment]
Any chance this can get looked at?

**Comment by PaulDalek** [comment]
Unstale.

**Comment by PaulDalek** [comment]
Hi @kai2468 

Thank you for contacting us. In short, the 0 indexed value shouldn’t be considered as a series name but by setting the `label` option with 0 allows it.

_Internal note_
It comes from the SeriesBuilder’s `read` function, more precisely from the below piece of code that is responsible for removing index of the `x` property. Setting any custom parameter with 0 index makes it still considered when looking for an index of a name.

```
if (typeof this.name === 'undefined' && builder.readers.length >= 2) {
  columnIndexes = builder.getReferencedColumnIndexes();
  if (columnIndexes.length >= 2) {
    // remove the first one (x col)
    columnIndexes.shift();
    // Sort the remaining
    columnIndexes.sort(function(a, b) {
      return a - b;
    });
    // Now use the lowest index as name column
    this.name = columns[columnIndexes.shift()].name;
  }
}
```

**Comment by maciejBL** [comment]
Hi, could we get back to the topic, since this is currently a big blocker in our project.

I've prepared the jsfiddle demo (https://jsfiddle.net/rs4vLu78/58/) to depict what's the problem, I would expect here to have different labels for series, independently from the `seriesMapping` contains.
