### ISSUE TITLE
Path animation is not correct when changing date using input boxes

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#1000]
1. Open http://www.highcharts.com/stock/demo/basic-line
2. Place the cursor in the lower limit edit box 
3. Change the date to be one day less than current value. Hit enter.

Result: The animation wiggles
Expected: The animation to scroll to the right.

Note that when entering a date that is one day more than current, then the animation is correct.

**Comment by pawelfus** [comment]
Works fine in 4.2.5+ version: http://jsfiddle.net/503gjo4s/
