### ISSUE TITLE
Tooltip doesn't appear when hovering StockTools/GUI area when tools are hidden

### ISSUE THREAD

**Issue by colinfoster** [highcharts/highcharts#10001]
#### Expected behaviour
Tooltip should appear when hovering over any part of the chart.

#### Actual behaviour
Tooltip stops appearing when hovering over the area where the StockTools usually appear.

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/stock-tools-gui
1.) Use the tools "<" icon to hide the tools.
2.) Hover over the chart where the tools used to be.

#### Product version
HighStock v7.0.2

#### Affected browser(s)
MacOS Safari, FireFox, Chrome  confirmed. (Likely not browser specific.)

**Comment by KacperMadej** [comment]
Hi @colinfoster 

Thank you for reporting about the bug.

The dead zone for any mouse interactions with chart is caused by main container (with class `highcharts-stocktools-wrapper highcharts-bindings-wrapper`) that is not hidden and overlaps the chart preventing pointer events.
