### ISSUE TITLE
Series.update and dynamically added event handlers

### ISSUE THREAD

**Issue by lpa-mihail-sudenoc** [highcharts/highcharts#10010]
#### Expected behaviour
I dynamically added an event handler to a point of a chart series using Highcharts.addEvent method. After updating of the series options using Series.update method, the point, as well as series by itself should still contain all its event handlers.

#### Actual behaviour
All event handlers of all of the series points and also all events of the series by itself are removed and aren't restored after Series.update.

#### Live demo with steps to reproduce
https://jsfiddle.net/w1jyfLhs/3/
1. Click on the first point of the presented series — alert will appear, indicating that handler is working;
2. Click on the button below the chart to update series options;
3. Click on the first point again — no alert, because handler has been removed.

#### Product version
Highcharts 6.2.0

#### Affected browser(s)
All browsers

Please suggest any solution if there is some or fix the issue.

**Comment by KacperMadej** [comment]
Hi @lpa-mihail-sudenoc 

Thank you for reporting about the problem.

As a workaround you could assign the event again after the update.
Demo: https://jsfiddle.net/BlackLabel/9qy5w7gs/

**Comment by TorsteinHonsi** [comment]
I'll debug this tomorrow and try to come up with a solution. For some reason, it seems like the points themselves are destroyed and replaced in this case, which they shouldn't be.

**Comment by lpa-mihail-sudenoc** [comment]
Thank you very much, Torstein! Could you please also take a look at the events of the series? They're also destroyed after update, therefore the "afterUpdate" event of the series, which is mentioned in [the docs](https://api.highcharts.com/class-reference/Highcharts.Series#update) can never be handled.

**Comment by TorsteinHonsi** [comment]
This change turned into a bigger refactoring, since what we currently do is to destroy all points and build new ones on `Series.update`. But I think it's worthwhile to rewrite the logic to avoid this. Unfortunately this means there's no simple fix that can be ported back to Highcharts v6, so for that case you'll have to rely on workarounds, or upgrade.

Demo with the fix applied: https://jsfiddle.net/highcharts/ohxdju0q/5/

**Comment by lpa-mihail-sudenoc** [comment]
Thank you very much for the fix and help, Torstein. Actually, the biggest problem for us is the series event handlers, because if we will be able to use "Series.afterUpdate", we can at least try to redraw and reassign all event handlers of the points, I think it might work. But how can we get the series fix in 6.2.0? Is it possible?

**Comment by KacperMadej** [comment]
@lpa-mihail-sudenoc 
You could manually change used Highcharts version to include the changes made in the fix. To apply a fix to the code you could check [this dcos](https://github.com/highcharts/highcharts#build-and-debug).
