### ISSUE TITLE
highcharts scatter plot unexpected point demonstrate

### ISSUE THREAD

**Issue by burakkp** [highcharts/highcharts#10018]
#### Expected behaviour

https://imgur.com/vsasDXF

#### Actual behaviour

These marked points, I don't understand where the data comes from. This is not the data from the API.

https://imgur.com/appQ2Hf

**Comment by sebastianbochan** [comment]
Hi @burakkp,
Thank you for contacting us. For general [support](http://www.highcharts.com/support) questions, please use stackoverflow / forum or email.

ps. in the support case, please attach a live demo of your chart which will allow us to debug it. From the image it is really limited and there can be many reasons of the issue.
