### ISSUE TITLE
Highcharts.Chart missing exportChartLocal method signature in types

### ISSUE THREAD

**Issue by attilacsanyi** [highcharts/highcharts#10012]
#### Expected behaviour
`exportChartLocal` **should** exists on type `Highcharts.Chart`

#### Actual behaviour
`exportChartLocal` **is not** exists on type `Highcharts.Chart`

#### Product version
Highcharts 7.0.2 with TypeScript 3.2.2

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @attilacsanyi 

It's defined in the .d.ts file for the offline-exporting module.

https://github.com/highcharts/highcharts-dist/blob/f9b76c26f777a0ada687744b8d4ede31cbe55efe/modules/offline-exporting.src.d.ts#L11-L26

```ts
    interface Chart {
        /**
         * Exporting and offline-exporting modules required. Export a chart to
         * an image locally in the user's browser. Requires the regular
         * exporting module.
         *
         * @param exportingOptions
         *        Exporting options, the same as in
         *        Highcharts.Chart#exportChart.
         *
         * @param chartOptions
         *        Additional chart options for the exported chart. For example a
         *        different background color can be added here, or `dataLabels`
         *        for export only.
         */
        exportChartLocal(exportingOptions: ExportingOptions, chartOptions: Options): void;
```

**Comment by attilacsanyi** [comment]
Dear @kacperadej, thanks for pointing to the right d.ts file, can you help me how to type the chart in TyepScript to have this exporting type capabilites? This is my question in general to any highcharts module which was separatated and extending Chart interface.

Appreciate your guideline. Thanks in advance.
