### ISSUE TITLE
Highcharts Gradients on multiple charts print 

### ISSUE THREAD

**Issue by RZK349** [highcharts/highcharts#10027]
Using highcharts recommendation for printing multiple charts from the reference below:

http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/exporting/multiple-charts/

every thing works fine until i implemented gradient colors into the theme , here is an example:-
 
The charts in the UI
https://ibb.co/nLvkshk
 
The print result:-
https://ibb.co/GcdKXvs
https://ibb.co/2ZydZkp

please not that viewing the SVG output in an external viewer would show the the gradients just fine.

i am using react along side the highcharts official wrapper

Thanks in advance

**Comment by RZK349** [comment]
Hi @sebastianbochan 
Thank you for replaying.

I am collecting SVG data from the charts and constructing a PDF report containing all the charts.

Please not the result in the Fiddles you included when you click on download as SVG from the context menu.

i am using Chrome, and not using the styled mode i have a custom theme and use "setOptions" to fill in the highcharts colors

**Comment by TorsteinHonsi** [comment]
Old, related issue that seems to have been fixed: https://github.com/highcharts/highcharts/issues/1137

**Comment by TorsteinHonsi** [comment]
It works for me in Adobe Reader but not in Preview on the Mac, where all the gradients are replaced by white fill.
