### ISSUE TITLE
There is no ChartSelectionEventObject

### ISSUE THREAD

**Issue by Timppe** [highcharts/highcharts#10032]
#### Expected behaviour
I expect the event parameter of ChartSelectionCallbackFunction to be something like
`Event & { yAxis: { min: number, max: number }[], xAxis: { min: number, max: number }[] }`

#### Actual behaviour
It is only Event, and accessing the parameters yAxis and xAxis and their corresponding min and max values which the official documentation says it has (https://api.highcharts.com/highcharts/chart.events.selection), gives a type error

#### Live demo with steps to reproduce
Just look at the type definitions in highcharts.d.ts

#### Product version
Highcharts 7.0.2

**Comment by sebastianbochan** [comment]
Hi @Timppe,
Thank you for reporting.

FYI @bre1470
