### ISSUE TITLE
TypeScript: RangeSelectorOptions.buttonTheme is not a CSSObject

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#10037]
#### Expected behaviour
`RangeSelectorOptions.buttonTheme` has far more complex structure than `CSSObject`. E.g. see official demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/rangeselector/styling/

An error is thrown when trying to set `style` as an object. `states` will do that too.

#### Actual behaviour
`RangeSelectorOptions.buttonTheme` is defined as of `CSSObject` type.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/rangeselector/styling/

#### Product version
7.0.2

_Internal note:_
fyi: @bre1470

**Comment by TorsteinHonsi** [comment]
Yes, the thing documented at https://api.highcharts.com/class-reference/Highcharts.SVGAttributes.

**Comment by KacperMadej** [comment]
Maybe it should be, but that won't work either. `SVGAttributes` has `style` and `states`? I'm unable to find those in docs and when testing a prop with this type (mapNavigation.buttons.zoomIn.theme) error is being thrown when I try to set `style`. Is `SVGAttributes` defined outside of this code? https://github.com/highcharts/highcharts/blob/c9f93f5acb3b5b16a18ce7098b9e51f6e61e242f/js/parts/Utilities.js#L267-L323

**Comment by aminsmartsense** [comment]
@KacperMadej Hover state and active state also not working. Please help me with this.

`states: {
                hover: {
                },
                select: {
                    fill: '#039',
                    style: {
                        color: 'white'
                    }
                }
                // disabled: { ... }
            }`

**Comment by bre1470** [comment]
The state problem will be solved with the next Highcharts update.
