### ISSUE TITLE
series-labels doesn't fit series area when x-axis type is category

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10038]
#### Actual behaviour
Series labels don't fit the series area when x-axis type is set to 'category'. They are displayed onto plot area, but in some cases their color is the same as background color and because of that they are not visible.

Streamgraph series example: https://jsfiddle.net/BlackLabel/34fy69g7
Area series example: https://jsfiddle.net/BlackLabel/yq1zas9x

Would you classify this as a bug and something that should be improved?
Also, this is how it looks like in Highcharts official demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/streamgraph

#### Workarounds
We can set x-axis min and max: https://jsfiddle.net/BlackLabel/fhw0rk1o
We can set the label's contrasting color: https://jsfiddle.net/BlackLabel/ws3b1cL6

#### Product version
Highcharts 7.0.2

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: https://jsfiddle.net/highcharts/6Lm319x8/

There were two issues, first a regression since 27b3314691391c7042abe17c648c0d511ca67022 causing all labels to align to the right inside their allowed boxes, next they were allowed to display partly outside the area bounds.
