### ISSUE TITLE
Venn diagram - "z is undefined"

### ISSUE THREAD

**Issue by xantore** [highcharts/highcharts#10039]
#### Expected behaviour
No errors.

#### Actual behaviour
Error "z is undefined" in line 9028 
``` 
else h && (f.stateMarkerGraphic = p = v.renderer.symbol(h, z.x, z.y, z.width, z.height).add(f.markerGroup) 
```

#### Live demo with steps to reproduce
It happens when one circle is really big - after mouseover on any of the circles error appears.
It causes also the problem that after mouseOut the circle stays in 'hover' state due to this error.

#### Product version
Highcharts 7.0.2

#### Affected browser(s)
At least Chrome and Firefox

#### Solution
In my opinion its enough to add statement "&& z" in above code so the final condition should be:
```
else h && z && (f.stateMarkerGraphic = p = v.renderer.symbol(h, z.x, z.y, z.width, z.height).add(f.markerGroup)
```

**Comment by pawelfus** [comment]
Hi @xantore 

Thank you for sharing the demo. I'm not sure if this should be changed - you are setting `lessImportant` state on an point that doesn't have related graphic element. Please check `point.graphic` before doing this: http://jsfiddle.net/BlackLabel/f0qtz4p5/11/

Good luck! :)

**Comment by sebastianbochan** [comment]
Closed due to inactivity. Please reopen when new details will be available.
