### ISSUE TITLE
ChartResetZoomButtonThemeOptions lacks type definitions

### ISSUE THREAD

**Issue by Timppe** [highcharts/highcharts#10040]
#### Expected behaviour
Typesafe declaration of the resetZoomButton -> theme options other than zIndex

#### Actual behaviour
Typescripts complains that my display: "none" is not compatible, even though it basically should be

#### Live demo with steps to reproduce
https://jsfiddle.net/nh9Lvjbr/ try this with types and it will complain, or just try the official example as well https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/resetzoombutton-theme/

#### Product version
Highcharts 7.0.2

**Comment by Timppe** [comment]
You won't believe the amount of dirty casting I've done due to lacking types after updating Highcharts to 7.0.2 and deciding to take into use your types instead of our custom types for Highcharts :D I've only reported a couple so far... I've been thinking about starting to contribute regarding these types, but where to find the time... :)

**Comment by JusuVh** [comment]
This should be reopened: theme accepts states that does not accept css attributes

```
  chart: {
    resetZoomButton: {
      theme: {
        states: {
          hover: {
            fill: '#c3d0db',
            style: {
              color: '#4285F4'
            }
          } as any
        }
      }
    }
```

**Comment by bre1470** [comment]
@JusuVh Thank you for your feedback. This will be fixed with the next update.
