### ISSUE TITLE
network graph nodes not draggable on android

### ISSUE THREAD

**Issue by timdisher** [highcharts/highcharts#10041]
#### Expected behaviour
Network graph nodes are draggable on android

#### Actual behaviour
Tooltip functions but points are not draggable

#### Live demo with steps to reproduce
Examples on https://www.highcharts.com/docs/chart-and-series-types/networkgraph 
are draggable on windows but not android.

#### Affected browser(s)
Chrome for android

**Comment by pawelfus** [comment]
Thanks for reporting!
