### ISSUE TITLE
from 5.0.14 to latest: highmaps do not show labels for null values

### ISSUE THREAD

**Issue by DK-Unit4** [highcharts/highcharts#10049]
#### Expected behaviour
Sorry if I miss something : I hasn't found information on the changelog in case it is a change of behaviour. If it is : is it possible to make it work the old way with a setting?

The name of regions is shown for the null values

#### Actual behaviour
The name of regions is not shown for the null values

#### Live demo with steps to reproduce
https://jsfiddle.net/Kumlander/cm936w5n/2

notice no has null: the Norway name is shown

remove above the highmaps version, i.e. change
<script src="https://code.highcharts.com/maps/5.0.14/highmaps.js"></script>
to
<script src="https://code.highcharts.com/maps/highmaps.js"></script>

now the Norway name is not shown
#### Product version
latest

#### Affected browser(s)

Chrome

**Comment by pawelfus** [comment]
Hi @DK-Unit4 

Thank you for reporting the issue. 

*Internal note:*
This is direct result of this fix: 54bb0e46d
