### ISSUE TITLE
duplicate labels don't export in pie charts when downloading as CSV or XLS

### ISSUE THREAD

**Issue by odyth** [highcharts/highcharts#10056]
#### Expected behaviour
Take your browser pie chart and give Firefox 3 axises and then try and export. You should see 3 values for Firefox in the CSV / XLS.

#### Actual behaviour
You will see Firefox is only exported once and it is the last value.

#### Live demo with steps to reproduce
https://jsfiddle.net/2pwdoy0L/

#### Product version
7.0.2

#### Affected browser(s)
All

```

// Build the chart
Highcharts.chart('container', {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie'
    },
    title: {
        text: 'Browser market shares in January, 2018'
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: false
            },
            showInLegend: true
        }
    },
    series: [{
        name: 'Brands',
        colorByPoint: true,
        data: [{
            name: 'Chrome',
            y: 61.41,
            sliced: true,
            selected: true
        }, {
            name: 'Internet Explorer',
            y: 11.84
        }, {
            name: 'Firefox',
            y: 10.85
        }, {
            name: 'Firefox',
            y: 4.67
        }, {
            name: 'Firefox',
            y: 4.18
        }, {
            name: 'Other',
            y: 7.05
        }]
    }]
});
```

Here is what you see in the CSV
```
"Category","Brands"
"Chrome",61.41
"Internet Explorer",11.84
"Firefox",4.18
"Other",7.05
```

This is what you should see
```
"Category","Brands"
"Chrome",61.41
"Internet Explorer",11.84
"Firefox",10.85
"Firefox",4.67
"Firefox",4.18
"Other",7.05
```

**Comment by pawelfus** [comment]
Hi @odyth 
 
Thanks for reporting the issue. You are right, we should export all available points, even when matching names are found. It works nice for a categorized xAxis ( https://jsfiddle.net/BlackLabel/ej9owxhc/1/ ), but for a pie chart it's broken.

**Comment by TorsteinHonsi** [comment]
It's caused by these lines - if we remove them, it works as intended:

https://github.com/highcharts/highcharts/blob/04303faf5660d18d920aa03515c6795eed034019/js/modules/export-data.src.js#L416-L419
