### ISSUE TITLE
TS2339: Property does not exist on type 'SymbolDictionary', custom symbol

### ISSUE THREAD

**Issue by Abbo44** [highcharts/highcharts#10058]
I want to create a custom symbol
#### Expected behaviour
`
 Highcharts.SVGRenderer.prototype.symbols.plus = function (x, y, w, h) {
    return ['M', x, y + h / 2, 'L', x + w, y + h / 2, 'M', x + w / 2, y, 'L', x + w / 2, y + h, 'z'];
  };
`
#### Actual behaviour
I have this typescript Error: 
TS2339: Property 'plus ' does not exist on type 'SymbolDictionary'.
In the highcharts code, there is 
`
export type SymbolDictionary = {
    [key in SymbolKey]: (() => void|undefined);
};`
`
export type SymbolKey = ("arc"|"callout"|"circle"|"diamond"|"square"|"triangle"|"triangle-down");
`

How can you add a custom SymbolKey ?

#### Product version
Highcharts 7.0.2

#### Affected browser(s)
//

**Comment by KacperMadej** [comment]
Hi @Abbo44 

Thank you for reporting about the problem.

As a workaround you could cast to `any` like in

```ts
let cont: HTMLElement = new HTMLElement();
let SVGRenderer: Highcharts.SVGRenderer = new Highcharts.SVGRenderer(cont, 100, 100);

(SVGRenderer.symbols as any).plus = function() { ...
```

(tested on VS Code)

_Internal note:_
Could we set in TS defs something that would allow adding custom symbols? or only adding new method (like `addSymbol`) will work?
@bre1470

**Comment by bre1470** [comment]
The problem lies in the fact, that you can not redeclare types and `[key in ...]` is only working with literal types / `[key: ...]` only without literal types. The only way I see is to convert the dictionary to an interface and remove the `SymbolKey` type:
```
export interface SymbolDictionary {
    [key: string]: () => void;
    arc: () => SVGPathArray;
    callout: () => SVGPathArray;
    circle: () => SVGPathArray;
    diamond: () => SVGPathArray;
    square: () => SVGPathArray;
    triangle: () => SVGPathArray;
    "triangle-down": () => SVGPathArray;
}
```
