### ISSUE TITLE
Highmaps - borderWidth: 0 is not working

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#10057]
#### Expected behaviour
For Highmaps,, when borderWidth is set to 0, it is not reflected on chart.

#### Actual behaviour
For Highmaps, when borderWidth is set to 0, no border should be applied to chart.

#### Live demo with steps to reproduce
It was working fine till v6.1.0 - https://jsfiddle.net/xocdbfes/
But it is not working with latest library - https://jsfiddle.net/g0d9npv5/

**Comment by pawelfus** [comment]
Hi @tejaspchordiya 

Thanks! 

*Internal note:*
Regression after 5ac59e5e2

**Comment by KacperMadej** [comment]
**Workaround**:
set `borderColor: 'none',` - [demo](https://jsfiddle.net/BlackLabel/7zt4d5xc/)

**Comment by tejaspchordiya** [comment]
Thanks for the workaround.
