### ISSUE TITLE
IE11 - exporting module issue 

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#10052]
On IE11 with loaded standard modules (highcharts/exporting/export-data) print option doesn't work and console shows error informing that "SCRIPT438: Object doesn't support property or method 'forEach'". 

After adding oldie and oldie-polyfills modules to manage 'forEach' error, downloading JPEG, PNG, PDF, SVG and print options still doesn't work on Internet Explorer11 browser while using online editors - like jsFiddle. When this same code is reproduced locally and opened on IE11 - downloading works fine, but print options still don't work. 

#### Live demo with steps to reproduce

[jsFiddle](https://jsfiddle.net/BlackLabel/aL6e9u4o/)

#### Product version

Highcharts v7.0.2

#### Affected browser(s)

IE11

**Comment by KacperMadej** [comment]
`oldie-polyfills` should handle this and add a polyfill for the NodeList object as IE doesn't support this.
https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach

**Workaround** - add a polyfill that handles this (example is in the above link)

**Comment by TorsteinHonsi** [comment]
Actually `oldie-polyfills` is intended for IE 6-8. This issue will also happen in IE 9-11, some older versions of Edge and probably some others. In all modern browsers, `forEach` is available on NodeLists.

**Comment by TorsteinHonsi** [comment]
#### Workaround
```js
if (!NodeList.prototype.forEach) {
	NodeList.prototype.forEach = Array.prototype.forEach;
}
```

[View it live on jsFiddle](https://jsfiddle.net/highcharts/h1aqfu4b/4/).
