### ISSUE TITLE
Annotations module is rendered more than once. 

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#10061]
After resizing the window when the annotations module is added more than once chart renders more than one annotation. This problem was noticed and reported by Angular user. 

#### Live demo with steps to reproduce

[DEMO](https://jsfiddle.net/BlackLabel/k3140d2u/)

#### Product version

Highcharts 7.0.2

#### Affected browser(s)

All

**Comment by KacperMadej** [comment]
The similar problem was resolved here: 
https://github.com/highcharts/highcharts/issues/7729#issuecomment-364853012

**Comment by TorsteinHonsi** [comment]
Yes I would prefer a similar solution. You don't need to add another boolean like `Highcharts.annotationsLoaded`. Since the annotations module registers `H.Annotation`, you can simply check for that.

**Comment by pawelfus** [comment]
It's already fixed, closing.
