### ISSUE TITLE
Change symbol key to `triangleDown` instead of `triangle-down` to ease usage

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#10068]
#### Expected behaviour

use `SVGRenderer.symbols.triangleDown`

#### Actual behaviour

you have to write `SVGRenderer.symbols['triangle-down']`

**Comment by TorsteinHonsi** [comment]
It's used for the marker symbols in https://api.highcharts.com/highcharts/plotOptions.series.marker.symbol, can't change it without breaking backwards compatibility.
