### ISSUE TITLE
Proximate legend alignment does not work with panes

### ISSUE THREAD

**Issue by opatut** [highcharts/highcharts#10063]
#### Expected behaviour

In a stacked chart (y-axis defitions have non-overlapping `height` and `top` attributes), the legend entries should still align near their series (with `legend.layout: "proximate"`).

#### Actual behaviour

They sort as they would if the axes weren't stacked, but the series are plotted differently. So they don't align.

#### Live demo with steps to reproduce

http://jsfiddle.net/zxst2gk5/

#### Product version

Highcharts JS v7.0.2 (2019-01-17)

#### Affected browser(s)

At least Firefox 65.0, probably not browser dependent though.

**Comment by TorsteinHonsi** [comment]
I changed the title, as the term "stacked" in Highcharts is used for stacked series. Just to avoid confusion.
