### ISSUE TITLE
TypeScript: Missing isSeriesBoosting on Serie object

### ISSUE THREAD

**Issue by Abbo44** [highcharts/highcharts#10067]
#### Expected behaviour
In Highcharts 6.5.2, to check if the serie is boosted, I call `isSeriesBoosting`
`
 for (const serie of chart.series) {
    if (serie.isSeriesBoosting) {
      return true;
    }
  }
`
#### Actual behaviour
In Highcharts 7.0.2, isSeriesBoosting is absent

#### Product version
Highcharts 7.0.2

#### Affected browser(s)
//

**Comment by KacperMadej** [comment]
Hi @Abbo44 

Thank you for reporting about the problem.

As a workaround you could check is the chart is in series boost mode using `isChartSeriesBoosting` as in

```ts
Highcharts.Chart.isChartSeriesBoosting(chart: Highcharts.Chart): boolean
```

**Comment by bre1470** [comment]
`isChartSeriesBoosting` is the official replacement for `isSeriesBoosting`
