### ISSUE TITLE
add option to add tooltip in place of  credits in highcharts 

### ISSUE THREAD

**Issue by Usama-Tahir** [highcharts/highcharts#10060]
#### Expected behavior
Can customize highcahrts to put a tooltip in place of credits section 

#### Actual behaviour
seems impossible to add a tooltip in place of credits section

**Comment by pawelfus** [comment]
Hi @Usama-Tahir 

Thanks for sharing your idea. Could you also post your idea on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api)? Thanks!

**Comment by Usama-Tahir** [comment]
@pawelfus I posted the idea there also 
https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/36753466-add-option-to-add-tooltip-in-place-of-credits-in-h
