### ISSUE TITLE
TypeScript: rangeSelector.buttonTheme needs states

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#10064]
#### Expected behaviour
rangeSelector.buttonTheme allows states as mentioned in API reference:
https://api.highcharts.com/highstock/rangeSelector.buttonTheme

#### Actual behaviour
No states

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/rangeselector/styling/

#### Product version
7.0.2

_Internal note:_
fyi @bre1470

**Comment by bre1470** [comment]
@KacperMadej 
Thank you for your feedback! I have trouble to find information about the type for the states. Are they just a bunch of SVG attributes? Can they contain more states as well?

**Comment by pawelfus** [comment]
List of states is available here: https://api.highcharts.com/highstock/rangeSelector.buttonTheme 

> The object can also be extended with states, so you can set presentational options for `hover`, `select` or `disabled` button states.

Where each state is [`Highcharts.SVGAttributes`](https://api.highcharts.com/class-reference/Highcharts.SVGAttributes) type.

**Comment by Leolik** [comment]
sorry, but if use `states` in `buttonTheme` I get warning in console:
```
Highcharts warning: Invalid attribute 'states' in config 
```

**Comment by KacperMadej** [comment]
Hi @Leolik 
Thank you for reporting the problem - this should be a new issue so I will open it.
Here it is: https://github.com/highcharts/highcharts/issues/15178
