### ISSUE TITLE
Styled mode - should other series dim while hovering over disabled series in legend?

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10071]
As in title.

#### Actual behaviour
When series is hidden, while hovering over this series legend item - other series should still be dimming?
 
jsFiddle showing this: https://jsfiddle.net/BlackLabel/ket9nvj5

#### Suggested behaviour
Or maybe hovering over hidden series should not affect others?

https://jsfiddle.net/BlackLabel/37z1gmef

Would you classify this as a bug and should be fixed? 

#### Product version
7.0.3

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Classified as a bug.

**Comment by siggysamson** [comment]
Thanks @raf18seb for creating the issue - I think hovering a disabled legend item shouldn't affect other series. If there is a version with a fix for this I'm happy to give it a try if possible 🙂

**Comment by raf18seb** [comment]
Hi @siggysamson,

Thanks for sharing your opinion. We agree with you - it is a bug and will be fixed soon.

When hovering over the series, the CSS class **highcharts-legend-series-active** is always added on the chart container. As a workaround, for this moment you can check (in Legend.prototype.setItemEvents method) whether the series is visible and if not, stop from adding this class.

Workaround: https://jsfiddle.net/BlackLabel/37z1gmef
