### ISSUE TITLE
Scatter Chart : no automatic turn off of Boost mode during zoom 

### ISSUE THREAD

**Issue by Abbo44** [highcharts/highcharts#10075]
#### Expected behaviour
I want when I zoom in the chart to remove the boost module

#### Actual behaviour
In scatter chart type, boost isn't turn off when I zoom.

#### Live demo with steps to reproduce
Boost mode turn off after zoom in - With a chart type Line => https://jsfiddle.net/Kheysermanu/ah1m3g2w/

no automatic turn off of Boost mode during zoom in - With a chart type Scatter => https://jsfiddle.net/Kheysermanu/fzmn0e5s/

#### Product version
Highcharts 6.5.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @Abbo44 

Thank you for reporting the issue. You are right, it's broken.

**Workaround:**
After loading Highcharts and all modules, add line:
```javascript
Highcharts.seriesTypes.scatter.prototype.sorted = true;
```

**Comment by TorsteinHonsi** [comment]
In a static scatter chart, the `boostThreshold` is respected: http://jsfiddle.net/highcharts/fmrg9dpv/2/

**Comment by viart** [comment]
In case of `highcharts-react-official` after applying the workaround and zooming in points don't render (disappear). Are there any other solutions?

**Comment by KacperMadej** [comment]
@viart 
Have you reported this on the `highcharts-react-official` repo?

fyi @ppotaczek

**Comment by viart** [comment]
I haven’t since the issue and the workaround is described here, should I copy paste it there?

**Comment by ppotaczek** [comment]
Hi @viart, 

It is not necessary, but could you reproduce that issue in some online code editor? 
The workaround seems to work with `highcharts-react-official`: https://codesandbox.io/s/highcharts-react-demo-f2px6

Best regards!

**Comment by viart** [comment]
@ppotaczek found the reason and it's not React specific, it fails if the data is not sorted in ascending order by `X`, to reproduce just replace this line
`arr.push([i, 2 * Math.sin(i / 100) + a + b + c + spike + Math.random()]);` by
`arr.push([2 * Math.sin(i / 100) + a + b + c + spike + Math.random(), i]);` maybe it's expected, but I don't remember seeing this in docs about Boost.

Working workaround:
> After loading Highcharts and all modules, add line:
> 
> ```js
> Highcharts.seriesTypes.scatter.prototype.sorted = true;
> ```
> 
and **make sure your data is sorted by X in an ascending order**

**Comment by MiguelCh24** [comment]
> Hi @Abbo44
> 
> Thank you for reporting the issue. You are right, it's broken.
> 
> **Workaround:** After loading Highcharts and all modules, add line:
> 
> ```js
> Highcharts.seriesTypes.scatter.prototype.sorted = true;
> ```
> 
> Demo: https://jsfiddle.net/BlackLabel/vLzc10ke/

Hi, I'm getting this issue in angular - Any suggestions on how I can fix it?

**Comment by karolkolodziej** [comment]
@MiguelCh24 Could you please test[ the demo ](https://stackblitz.com/edit/highcharts-angular-line-ag98qb)and tell me if you still get this issue?

**Comment by MiguelCh24** [comment]
> @MiguelCh24 Could you please test[ the demo ](https://stackblitz.com/edit/highcharts-angular-line-ag98qb)and tell me if you still get this issue?

I just validated the link that you shared with me and I don't have that issue there - but even so, in an implementation that I have in one of my projects I have that issue - I tried to implement this (**Highcharts.seriesTypes.scatter.prototype.sorted = true;**
) but I get issues when I try to do it.

_**Thanks a lot for your help**_
