### ISSUE TITLE
Polar chart has a hole when series of type 'area' are used

### ISSUE THREAD

**Issue by dosi-bingov** [highcharts/highcharts#10074]
#### Expected behaviour
There should be no hole. 

#### Actual behaviour
A hole in the area is visible when yAxis min is negative

#### Live demo with steps to reproduce
https://jsfiddle.net/8ugnza4y/1/

#### Product version
Highcharts  v7.0.3 (2019-02-06)

#### Affected browser(s)
Firefox, Chrome

**Comment by pawelfus** [comment]
Hi @dosi-bingov 

Thanks for reporting the issue. In a polar chart, area starts from 0. Please change `threshold` for the series to fill the hole: https://jsfiddle.net/BlackLabel/yeogrzvd/

**Comment by KacperMadej** [comment]
This doesn't look like a bug according to the `threshold` API reference: https://api.highcharts.com/highcharts/series.area.threshold

**Comment by dosi-bingov** [comment]
Thank you for you fast response. I like this solution.
Still when a series contains negative values below yAxis min a point is drawn (in opposite direction https://jsfiddle.net/46qukt0c/).  In my opinion this can lead to chart distortion. For example this is not the case in https://plot.ly/python/radar-chart/ where no point is drawn when series value is below yAxis min. Am I missing something here ?

**Comment by KacperMadej** [comment]
Value below yAxis min is drawn incorrectly (the opposite direction) and this is a bug, but that is a different issue than the one described here. Nevertheless, thank you for pointing that problem out. I think this is not reported (not respecting yAxis max was reported and resolved), so could you open a new issue for that problem?

**Comment by dosi-bingov** [comment]
Yes I will do Thank you!

**Comment by TorsteinHonsi** [comment]
Regarding the threshold, you can set it to `null` instead of hard coding it to match your data: https://jsfiddle.net/highcharts/u8qL9641/
