### ISSUE TITLE
stock chart flag rendering problem with allowOverlapX: false

### ISSUE THREAD

**Issue by keithmdragon** [highcharts/highcharts#10073]
#### Expected behaviour
no rendering issue

#### Actual behaviour
rendering issue when lots of flags and time period is large

#### Live demo with steps to reproduce
https://jsfiddle.net/kdragon/0zcg7qn4/6/ 

run the above fiddle

either select "All" time range or drag the from range to the far left and notice the flags get all clumpy and don't represent the actual flags on the actual dates

if you uncomment: allowOverlapX: true, (which highsoft support recommended as a work around), it no longer has the rendering issues, but will obviously overlap, which may not be desired. they think the bug is "Highcharts distributing algorithm seems to work incorrectly"

#### Product version

highstock 6 and 7.02

#### Affected browser(s)
latest chrome: Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Hi @keithmdragon 

Thank you for reporting the issue. You are right, it looks wrong. There's certainly enough space for other flags on the left side. 

*Internal note:*
Reversing order of flags gives similar output, for flags are grouped on the left side: https://jsfiddle.net/BlackLabel/zn7sv5oa/1/ - that suggests problem is with distribution algorithm. 

Standalone demo (without Highstock): https://jsfiddle.net/BlackLabel/tp2fbsvy/10/ (just duplicated the last item from the distribution demo).

**Comment by Basts** [comment]
User from forum noticed very similar behaviour. 

[demo](https://jsfiddle.net/BlackLabel/64she9ma/)

**Comment by IamMille** [comment]
Still broken in 7.1.1, FYI

**Comment by IamMille** [comment]
Have anyone here perhaps come up with a workaround regarding this?

**Comment by pawelfus** [comment]
Possible workaround is to replace `flags.drawPoints` method and let developer define which flags are the most important. This way, devs have a possibility to set for each flag `point.rank=number` option, compare demos

- with workaround: http://jsfiddle.net/BlackLabel/246d13up/ (`rank` is randomized, just like data)
- without workaround: http://jsfiddle.net/BlackLabel/246d13up/2/

**Comment by IamMille** [comment]
@pawelfus Thanks a lot for the workaround. I tried to implement it, but still seams to act weird. 

I used your fiddle and just changed your for-loop to give me the loop index, and then `rank: index`, which resulted in only a couple of the last flags where showing. 

Am I missing something here?

**Comment by pawelfus** [comment]
Setting `rank: index` is no different from the basic config - if `rank` is not provided, then index of the element is taken. It's just a simple workaround, not a solution. Requires some more details, like which flags are important, but at least we can workaround the issue. Alternative workaround is to change max distance (in pixels) for flag to be rendered: 
```
diff --git a/js/parts/FlagsSeries.js b/js/parts/FlagsSeries.js
index 1eafe71ef..3b71dbb62 100644
--- a/js/parts/FlagsSeries.js
+++ b/js/parts/FlagsSeries.js
@@ -386,7 +386,7 @@ seriesType('flags', 'column'
                 box.plotX = box.anchorX;
                 boxes.push(box);
             });
-            H.distribute(boxes, inverted ? yAxis.len : this.xAxis.len, 100);
+            H.distribute(boxes, inverted ? yAxis.len : this.xAxis.len, 1000);
             points.forEach(function (point) {
                 var box = point.graphic && boxesMap[point.plotX];
                 if (box) {
```

But I don't think it looks better: http://jsfiddle.net/BlackLabel/246d13up/5/

**Comment by IamMille** [comment]
I see. And I understand that it's not a solution. But using the rank property it actually got worse. Instead of see some flags disappear, I see *only* the last flags even when it's not crowded in the beginning of the timeline. 

I'll try playing around with the distance and see if can make my case work. Thank you kindly for your help and time.

**Comment by pawelfus** [comment]
> Instead of see some flags disappear, I see only the last flags even when it's not crowded in the beginning of the timeline.

This is exactly the issue described in this ticket. See:  https://jsfiddle.net/BlackLabel/28co0tmL/ (or open OP's demo and click `All`).

**Comment by Denyllon** [comment]
+1

Here is the another (minified) example, where the labels should be visible in free space on the right side, but they're not.

https://jsfiddle.net/BlackLabel/Lhcx703t/

**Comment by GoncaloDuarte98** [comment]
Any updates?

**Comment by KacperMadej** [comment]
Hi @GoncaloDuarte98 ,
The issue was closed by the stale bot due to inactivity.
Let's open it again since it's active.
No updates.

Maybe the cluster markers module could be used in some cases as a workaround?
API reference: https://api.highcharts.com/highcharts/series.scatter.cluster
Demo in Highstock: https://jsfiddle.net/BlackLabel/2a0ec5wq/
More about marker clusters: https://www.highcharts.com/docs/advanced-chart-features/marker-clusters

**Comment by mkosir** [comment]
Hey guys, we love to use highstocks library, but this is really a bummer for us. Flags stopped showing for our users, once we went approximately over 50 😞 
Maybe there could be at least something like `maxFlagsItems: number` parameter to set, so  devs would be aware of this (bug) limitation before implementing (and agreeing with stakeholders) certain feature.

**Comment by pawellysy** [comment]
Hello @mkosir, thanks for the suggestion.
Did you reach out to us via our official support channels?
Maybe our support engineers could figure out how to adjust your chart to have a workaround for this issue in your case. Thanks!

**Comment by mkosir** [comment]
Sure, will do 👍
