### ISSUE TITLE
exception "Highcharts error #16" is thrown when library is loaded as npm package if window.Highcharts is already occupied

### ISSUE THREAD

**Issue by fedulovivan** [highcharts/highcharts#10087]
Page contains legacy code with Highcharts where library is loaded via 
```js
<script type="text/javascript" src="/plugins/highcharts-4.1.9/js/highcharts.js"></script>
```
and some compiled bundle with instruction
```js
import Highcharts from 'highcharts';
```

#### Expected behaviour
No conflict issue, both versions are working fine

#### Actual behaviour
`Highcharts error #16` exception is thrown on attempt to import highcharts as npm package.

#### Product version
Tested with 4.1.9 and 7.0.3

**Comment by cmm0004** [comment]
We are having this exact issue with our monolith single-page-app using an older version on Highcharts, and a Vue.js micro-frontend being mounted on a div. The vue microfrontend imports Highcharts 7.0.3 via the npm package the same way as the OP, and we see the same error.

Our current workaround is this module in our vue.config.js
```
module.exports = {
...
configureWebpack: {
module: {
      rules: [
        {
          test: /highcharts\.js$/,
          loader: 'string-replace-loader',
          options: {
            search: 'a.Highcharts?a.Highcharts.error(16,!0):',
            replace: ''
          }
        }
      ]
    }
  }
}
```

which, obviously, is a terrible solution.

there doesn't seem to be any interaction with the microsites' highcharts and the one our monolith puts on the window, it simply checks to see if its there, and if so stops the execution of the page, and if not, works fine.

**Comment by fedulovivan** [comment]
My workaround is to prevent occupying `window.Highcharts` right after loading it via script:
```js
<script type="text/javascript" src="/LinkWorkbench/plugins/highcharts-4.1.9/js/highcharts.js"></script>
<script type="text/javascript">
  if (window.Highcharts) {
    window.Highcharts_4_1_9 = window.Highcharts; delete window.Highcharts;
  }
</script>
```

**Comment by pawelfus** [comment]
Hi guys,

Thank you for reporting the issue. Let us discuss this issue internally and go back to you next week.

Personally, I think we should keep this error. I don't recommend loading different versions of the same library on a one website. Upgrade to the latest version should be done for all modules that use specific library, to prevent loading similar resources, increasing memory and app weight.

I would suggest to keep this error,  improving error message with a workaround.

Regarding your workarounds:
@cmm0004 - I'm not sure how this rule exactly works, but for me you only remove the error. That means you don't support both version of Highcharts, only the one loaded later. That means all of charts created after that point in time will use that one version. If you are currently fine with this, you probably just one step ahead of removing old version and using the new one (assuming that v7 is loaded later).

@fedulovivan Your workaround is better, but you should keep in mind all other modules loaded for Highcharts (e.g. `highcharts-more` or `exporting`) should be loaded before changing namespace: 
```javascript
<script type="text/javascript" src="/plugins/highcharts-4.1.9/js/highcharts.js"></script>
<script type="text/javascript" src="/plugins/highcharts-4.1.9/js/highcharts-more.js"></script>
...
<script type="text/javascript">
  if (window.Highcharts) {
    window.Highcharts_4_1_9 = window.Highcharts; delete window.Highcharts;
  }
</script>
```

PS: Thanks eVestment team for voting for this ;)

**Comment by fedulovivan** [comment]
Hi @pawelfus, thanks for detailed answer! 
In our particular case this exception is some kind of side effect of loading a big bundle on the page where one of react components requires highchart library. This compoтent is actually not mounted to DOM and not used but exception is still thrown.

Just have tested following scenario with [create-react-app](https://github.com/facebook/create-react-app):
1. created fresh react application with `create-react-app highcharts-10087` 
2. added highcharts package with `yarn add highcharts`
3. imported highcharts in src/App.js as `import highcharts from 'highcharts';`
![image](https://user-images.githubusercontent.com/752105/52501905-7f570480-2bf2-11e9-8bfc-a26ade0ae48f.png)
4. added script tag in public/index.html as `<script type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>`
![image](https://user-images.githubusercontent.com/752105/52501932-87af3f80-2bf2-11e9-8dc4-9c6c4a2808d6.png)
5. rebuild production bundle with `yarn build`
6. launch server `serve -s build/`
7. reload browser and viola..: `Uncaught Error: Highcharts error #16: www.highcharts.com/errors/16` 
![image](https://user-images.githubusercontent.com/752105/52501951-9990e280-2bf2-11e9-864b-368fdd49bd63.png)

**Comment by ravagedsnail** [comment]
Could I get some clarification on the below?

> **Personally**, I think we should keep this error. I don't recommend loading different versions of the same library on a one website. Upgrade to the latest version should be done for all modules that use specific library, to prevent loading similar resources, increasing memory and app weight.
> That means you don't support both version of Highcharts, only the one loaded later. That means all of charts created after that point in time will use that one version.

If we are using highcharts as a module does it act separately from what is on the window/global namespace? In our case, we have one module that uses a specific version of highcharts loaded in a legacy application where we'd prefer to not update/change the version.  In our testing, when using the imported version of highcharts it did not seem to populate the global namespace.

For further context, our use case is using the vue plugin for highcharts (https://github.com/highcharts/highcharts-vue) which does not indicate either way its behavior whenever highcharts is already loaded on the page.

**Comment by pawelfus** [comment]
Hi @ravagedsnail 

Sure! You combined two unrelated paragraphs from my previous comment. I don't recommend loading similar/the same modules multiple times, it's just a waste of resources. I think that is clear.

Regarding second paragraph, it was related to the workaround only. It looks like I was wrong, package indeed does not populate the global namespace, simple injection is used.

Regarding the https://github.com/highcharts/highcharts-vue package - you need the Highcharts package to be installed in order to use it ( https://github.com/highcharts/highcharts-vue#requirements ). highcharts-vue will probably use the library that is defined in your `package.json`. Sorry for the confusion!

**Comment by ravagedsnail** [comment]
Thanks for the reply @pawelfus!

Definitely understand that its not ideal to load similar resources twice.  We're just trying to understand what our options are working within a legacy application which seems as though it'd be a common use case.

Just clarifying, but ultimately my question here is as follows:
1) Can highcharts imported via npm coexist in a legacy application that loads its own version of highcharts or is the error there to prevent things from breaking during execution when used in this fashion?

Looking forward to the results of your internal discussion.  Thanks again for looking into this for us!

**Comment by bre1470** [comment]
The legacy way and the ES6 way share the same global namespace and therefore can not be combined. Our UMD pattern instead is mostly capsuled, except for the initial phase. So it is important that the module loaded versions of `highcharts.js` do not find an global Highcharts object during initialization. After the initial phase an older version can be added to the page like in this example:

```html
<html>
    <head>
        <script src="require.js"></script>
        <script>
            require.config({
                packages: [{
                    name: 'highcharts6',
                    main: 'highcharts'
                }, {
                    name: 'highcharts7',
                    main: 'highcharts'
                }],
                paths: {
                    'highcharts6': 'https://code.highcharts.com/6.2',
                    'highcharts7': 'https://code.highcharts.com'
                }
            });
        </script>
    </head>
    <body>
        <div id="container5"></div>
        <div id="container6"></div>
        <div id="container7"></div>
        <script>

            /* *
             *
             *  Highcharts v5
             *
             * */
            document.body.addEventListener('highcharts7loaded', function () {

                const highcharts5 = document.createElement('script');
                highcharts5.setAttribute('src', 'https://code.highcharts.com/5.0.14/highcharts.js');

                const highcharts5exporting = document.createElement('script');
                highcharts5exporting.setAttribute('src', 'https://code.highcharts.com/5.0.14/modules/exporting.js');

                const highcharts5accessibility = document.createElement('script');
                highcharts5accessibility.setAttribute('src', 'https://code.highcharts.com/5.0.14/modules/accessibility.js');

                highcharts5.onload = function () {
                    document.body.appendChild(highcharts5exporting);
                };

                highcharts5exporting.onload = function () {
                    document.body.appendChild(highcharts5accessibility);
                };

                highcharts5accessibility.onload = function () {
                    window.Highcharts.chart('container5', {
                        title: {
                            text: Highcharts.version
                        },
                        series: [{
                            data: [1,1,0,0,0]
                        }]
                    });
                };

                document.body.appendChild(highcharts5);

            });

            /* *
             *
             *  Highcharts v6
             *
             * */
            require([
                'highcharts6',
                'highcharts6/modules/exporting',
                'highcharts6/modules/accessibility'
            ], function (Highcharts, ExportingModule, AccessibilityModule) {
                ExportingModule(Highcharts);
                AccessibilityModule(Highcharts);
                Highcharts.chart('container6', {
                    title: {
                        text: Highcharts.version
                    },
                    series: [{
                        data: [5,4,3,2,1]
                    }]
                });
            });

            /* *
             *
             *  Highcharts v7
             *
             * */
            require([
                'highcharts7',
                'highcharts7/modules/exporting',
                'highcharts7/modules/accessibility'
            ], function (Highcharts, ExportingModule, AccessibilityModule) {
                ExportingModule(Highcharts);
                AccessibilityModule(Highcharts);
                Highcharts.chart('container7', {
                    title: {
                        text: Highcharts.version
                    },
                    series: [{
                        data: [1,2,3,4,5]
                    }]
                });
                document.body.dispatchEvent(new Event('highcharts7loaded'));
            });
        </script>
    </body>
</html>
```
