### ISSUE TITLE
[TypeScript] Series[Type]DataOptions type doesn't allow null values for y

### ISSUE THREAD

**Issue by Timppe** [highcharts/highcharts#10084]
#### Expected behaviour
I expect that I can assign `null` to `y` options in e.g. `Highcharts.SeriesLineDataOptions` because Highcharts will allow this.

#### Actual behaviour
The typing is `y?: number`, so essentially it allows it to be either `undefined` or `number` and will therefore complain if I assign a null value

#### Live demo with steps to reproduce
https://jsfiddle.net/tuorcxsq/ put these options in to a typed configuration and TS will complain

#### Product version
Highcharts 7.0.3

**Comment by KacperMadej** [comment]
Hi @Timppe 

Thank you for reporting about the problem.
