### ISSUE TITLE
[parallelcoordinates] graph not resizing on update

### ISSUE THREAD

**Issue by ramakrishnan3** [highcharts/highcharts#10081]
Chart not getting resized on update

Type 1: Graph with lesser axes data updated to data with more axes.
Type 2: Graph with more axes data updated to data with less axes

*above types(scenarios) are depicted in the jsfiddle example
#### Expected behaviour
Type 1: The graph shrinks to accommodate more data. All the data appears in the view.
Type 2: The graph resizes(maximize) to show the lesser data

#### Actual behaviour

Type 1: The additional data overflows the div.
Type 2: Extra space is not utilized. 

#### Live demo with steps to reproduce
https://jsfiddle.net/ramakrishnan3/a5hnsfyu/24/

#### Product version
highcharts@7.0.1

**Comment by KacperMadej** [comment]
Hi @ramakrishnan3 

Thank you for reporting about the problem.

**Comment by pawelfus** [comment]
**Workaround:**
Before using `chart.update(options)`, call `chart.setParallelInfo(options)`. It may not resolve all of the issues, but the demo works fine now.

Demo: https://jsfiddle.net/BlackLabel/6vn9yekm/3/

**Comment by ramakrishnan3** [comment]
@KacperMadej Thanks for the reply.

@pawelfus Thanks for the workaround.
