### ISSUE TITLE
In polar chart value below yAxis min is drawn incorrectly (the opposite direction)

### ISSUE THREAD

**Issue by dosi-bingov** [highcharts/highcharts#10082]
#### Expected behaviour
When a series value is below yAxis min the point should be treated as null value.

#### Actual behaviour
The point is drawn in opposite direction and that can lead to chart distortions 

#### Live demo with steps to reproduce
https://jsfiddle.net/46qukt0c/

#### Product version
Highcharts v7.0.3 (2019-02-06)

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @dosi-bingov 

Thank you for opening new issue for this bug report.

**Comment by TorsteinHonsi** [comment]
> When a series value is below yAxis min the point should be drawn at yAxis min.

I'm not sure I agree with this expected behavior. It is mathematically wrong to draw it a yAxis min. Instead, I would expect it to be clipped away.

**Comment by dosi-bingov** [comment]
Yes you are right, a point with a  value below yAxis min should be treated as null.

**Comment by pawelfus** [comment]
IMHO, tooltip shouldn't be displayed for points outside the extremes, just like in a regular charts: https://jsfiddle.net/BlackLabel/zg6djwf8/
