### ISSUE TITLE
Boost mode retina support (high DPI displays)

### ISSUE THREAD

**Issue by zloylos** [highcharts/highcharts#10096]
Boost mode does not support retina displays (and displays with devicePixelRatio > 1).
The first image without boost optimisation. 

|<img width="180" alt="screenshot 2019-02-07 at 21 47 07" src="https://user-images.githubusercontent.com/1593308/52435190-43546e80-2b22-11e9-8c04-5f74d7d81b5b.png">| <img width="150" alt="screenshot 2019-02-07 at 21 47 13" src="https://user-images.githubusercontent.com/1593308/52435191-43546e80-2b22-11e9-98bb-aa061fab568e.png">

Fix for canvas looks like this:
```(js)
const dpr = window.devicePixelRatio || 1;

canvas.setAttribute('width', width * dpr);
canvas.setAttribute('height', height * dpr);
canvas.style.width = `${width}px`;
canvas.style.height = `${height}px`;

const ctx = canvas.getContext('2d');
ctx.scale(dpr, dpr);
```
https://www.html5rocks.com/en/tutorials/canvas/hidpi/
But it doesn't work for WebGL.

**Comment by pawelfus** [comment]
Hi @zloylos 

Thank you for reporting the issue. You are right, chart looks fuzzy, comparing our column+boost [demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/boost/column), we get:
Retina:
<img width="438" alt="screen shot 2019-02-08 at 16 42 16" src="https://user-images.githubusercontent.com/1453926/52488696-af85af80-2bc0-11e9-9cb4-7516d1ea6ceb.png">
External:
![screen shot 2019-02-08 at 16 42 09](https://user-images.githubusercontent.com/1453926/52488697-b01e4600-2bc0-11e9-9ed9-713880f1c889.png)

Tested on Chrome v71.

**Comment by TorsteinHonsi** [comment]
FYI @cvasseng 

Given a dpr of 2, the webGL renderer would probably have to render this as if the canvas was double the size, and every graphic must be translated by that amount (coordinates, line widths, textures etc). Then when painted on the scaled-down canvas, it should render sharp.

**Comment by 52flutter** [comment]
This problem does not seem to be resolved

**Comment by raf18seb** [comment]
Our state bot closed this issue due to inactivity. Reopening.

**Comment by 52flutter** [comment]
any update？

**Comment by raf18seb** [comment]
Hi @52flutter,

unfortunately, we don't have ETA for this issue at this moment.

**Comment by 52flutter** [comment]
@raf18seb @KacperMadej 
I have a LicenseID, can I ask for help? This problem has a great impact on us

**Comment by TorsteinHonsi** [comment]
Hi @52flutter, thanks for your patience! This is an improvement we have been planning for a while, but been short on resources. Thanks for the push.

Anyway, here's the [draft PR](https://github.com/highcharts/highcharts/commit/d5fc68e50dbd5f0f87ef786c2ed01697f0f6c7cb). Please try it out and see what you think. An unfortunate limitation is the `lineWidth` that is always 1px in 1:1 renderings, but on Retina it will be scaled down to 0.5px.

**Comment by 52flutter** [comment]
@TorsteinHonsi 
Very cool, thank you for your support, but there is still a little problem

![image](https://user-images.githubusercontent.com/11569655/146497179-a98db238-e422-472f-a590-13796fdcb183.png)

**Comment by 52flutter** [comment]
![WX20211217-141329](https://user-images.githubusercontent.com/11569655/146498032-551cdb5a-bd0a-4e0a-8d0e-b72f19604fd4.png)
<img width="761" alt="WX20211217-141309@2x" src="https://user-images.githubusercontent.com/11569655/146498038-1ffcece6-834c-482b-9cdc-51032fa740c4.png">
I tried it in our product. It’s a bit strange that the line width of the high-definition screen is 0.5, and the color becomes very dim, and it doesn’t look clear.

**Comment by TorsteinHonsi** [comment]
Thanks for testing @52flutter !

The misplaced label. I can't imagine that this has anything to do with the change. The axis labels are rendered in SVG, not WebGL. I can't see it in my screen with Mac/Chrome...

Regarding the line width, there's an [open issue on it](https://github.com/highcharts/highcharts/issues/11794).

> and the color becomes very dim, and it doesn’t look clear.

I would say this is the expected look when the line width is 0.5. You can see the fluctuation better in the lower chart because there is not so much overlap between the lines. Maybe you can verify the rendering itself by disabling the Boost module and set the `lineWidth` to 0.5? To see how the non-boost SVGRenderer handles the same data.

**Comment by 52flutter** [comment]
linewidth 0.5 
![image](https://user-images.githubusercontent.com/11569655/146512206-7efe2ffc-0adf-4a3d-9c97-e4a58fdd0019.png)
linewidth 1
![image](https://user-images.githubusercontent.com/11569655/146512647-347c0317-6680-4833-b30d-8665b67b2cbf.png)

**Comment by 52flutter** [comment]
By comparison, when lineWidth=1 and boost is turned on, the peak value will not be obvious under the high-definition screen. I think there are more and more high-definition screens now, and there will only be more in the future. Boost line width limitation This problem needs to be resolved as soon as possible

**Comment by 52flutter** [comment]
@TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Yes we will prioritize implementing `lineWidth` in Boost as soon as possible.

> the peak value will not be obvious under the high-definition screen

But the Boost module now renders it like non-boost with a `lineWidth` of 0.5, right? At least then we've got the `pixelRatio` implementation correct and can close this PR.

**Comment by 52flutter** [comment]
Thank you for your support, it can be closed, I hope the boost line width will be resolved this morning

**Comment by 52flutter** [comment]
I have two screens, one is high-definition, one is not high-definition, the two screens drag the chart back and forth, consider automatic adaptation
