### ISSUE TITLE
Printing issue. Characters missing. Chrome. Windows 10. 

### ISSUE THREAD

**Issue by michalsw** [highcharts/highcharts#10092]
#### Expected behaviour
Charts legend and labels are printed normally using Chrome (latest version) and Windows 10

#### Actual behaviour
It has never been an issue before, but now when printing Highcharts, the print preview removes some characters from the legend and labels leaving only "i", "l", "-". Everything goes back to normal after removing `font-family: "Lucida Grande", "Lucida Sans Unicode"` from styles `svg.highcharts-root` (the font changes though). It works well on MacOS and Fedora 28.

#### Live demo with steps to reproduce
Print the webpage using Chrome _Print..._ option on Windows 10
https://www.highcharts.com/demo/line-basic

#### Product version
Highcharts 

#### Affected browser(s)
Chrome Version 
72.0.3626.81
72.0.3626.96 (latest)

**Comment by KacperMadej** [comment]
Hi @michalsw 

Thank you for reporting about the problem.

Looks like a general Chrome issue - https://jsfiddle.net/BlackLabel/dyt2c849/19/
Reported: https://bugs.chromium.org/p/chromium/issues/detail?id=930136

**Workaround**: do not use bold version of the used font (see legend) https://jsfiddle.net/BlackLabel/56a2e1yv/

**Comment by KacperMadej** [comment]
Looks like the bug is resolved (tested in Chrome v 72.0.3626.109).
Closing as resolved. If you still see the problem please leave a comment and the issue could be reopened.
