### ISSUE TITLE
Column Chart: Interference within Column

### ISSUE THREAD

**Issue by fkramer90** [highcharts/highcharts#10105]
hello, 
I'm about to build highcharts in a salesforce sandbox and insert it into a lightning component. Unfortunately, it often happens that hover effects or bar charts show disturbances in the bar. Here is an example screenshot. Similar errors also occur without the border color. Don't worry about November. for this month there are no values available

![view impact error](https://user-images.githubusercontent.com/24522563/52560810-ce22bb00-2df9-11e9-9b53-6b59d4c0921a.PNG)

#### Expected behaviour
Graph should be displayed normally without orange line in july bar

#### Actual behaviour
Strange line is displayed in july bar. it looks like it was the border of the previous month

#### Live demo with steps to reproduce
Errors only shown within Lightning Components, not in Jsfille

#### Product version
Jquery 3.1.1 and highcharts

#### Affected browser(s)

Firefox and Chrome

**Comment by fkramer90** [comment]
I dont know if it is the same problem but strange lines are also shown here:

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/plotoptions/series-states-hover/

**Comment by pawelfus** [comment]
Hi @fkramer90 

Thanks for reporting the issue. Could you attach a screenshot of these strange lines from the jsfiddle above? You said that you can not recreate issue in jsFiddle, only within Lightning Components - can be that an issue with Lightning Components? Some kind of a CSS issue? 

Note that without live demo we won't be able to fix the issue.

**Comment by fkramer90** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24522563/52780451-7202a580-304a-11e9-81c3-3b74cdb68c68.gif)

**Comment by fkramer90** [comment]
please have a look at greenland for example

**Comment by fkramer90** [comment]
@pawelfus https://jsfiddle.net/fkramer/95yLgc73/25/ i built it with jsfiddle, maybe you can find an error in my code but in that version it is shown correctly in jsfiddle, not in my lightning component

**Comment by pawelfus** [comment]
Hi @fkramer90 

My apologies for the late reply! I didn't notice your previous posts - thanks for the heads up.  I'm able to recreate the same issue in Firefox 65.0.1, not in Chrome 72.0.3626.119 (thanks for the gif btw!) - only on the external monitor. On retina it works fine. 

Simplified demo: https://jsfiddle.net/qnac7psb/

@fkramer90 - could you disable tooltip and let us know if issue still exists?

@TorsteinHonsi  - any thoughts? For me it looks like browser artifacts. No action is needed - lines hide after a few milliseconds. However, when we disable tooltip, it works fine: https://jsfiddle.net/qnac7psb/1/

**Comment by TorsteinHonsi** [comment]
Yes, typical browser artefacts. It looks like the edge of the region that has to be redrawn when the tooltip moves. 

Could be related to #9745, though this should be fixed with Firefox v65.
