### ISSUE TITLE
axis.showEmpty does not hide title in heatmap

### ISSUE THREAD

**Issue by monicajianu** [highcharts/highcharts#10106]
#### Expected behaviour

Axis titles should be hidden, similar to the behaviour for a line series: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/yaxis/showempty/

#### Actual behaviour

Axis titles are still displayed, even if there is no data being shown.

#### Live demo with steps to reproduce
https://jsfiddle.net/monicajianu/64owL3df/

#### Product version
Highcharts v7.0.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @monicajianu 

Thank you for reporting the issue. This is how it works: https://jsfiddle.net/BlackLabel/a6kwvxdq/ - the title is rendered, even if `Series 2` has no data, but it's **visible**.

I'm not sure about expected behaviour here. Docs says `no data`, but should be rather `no data and visible series`. @TorsteinHonsi - is that a bug in docs or in code?

**Workaround:**
```javascript
Highcharts.Axis.prototype.hasData = function() {
  return (
    Highcharts.defined(this.min) &&
    Highcharts.defined(this.max) &&
    this.tickPositions &&
    this.tickPositions.length > 0
  )
}
```

Demo: https://jsfiddle.net/BlackLabel/9fkjvLzc/6/

**Comment by TorsteinHonsi** [comment]
I'm not sure... You have had support cases like this before. Do you recommend we change the behaviour? What do users typically expect?

**Comment by pawelfus** [comment]
In general, I would say users need better control over that option. A few related issues: #8917, #2408 and #705. So either we will change the behaviour, or add some other options for a better control.

From my perspective if points are not rendered within extremes, axes are expected to be hidden. Something like this maybe:

```javascript
hasData: function () {
  var prop = this. isXAxis ? 'x' : 'y';
  return (
    this.hasVisibleSeries &&
    this.series.some(s => {
      s.points.length >= 2 ||
      s.points.length === 1 ?
        s.points[0][prop] <= this.max && s.points[0][prop] >= this.min : 
        false
    )
  );
}
```
Not tested, but solves all cases I'm aware of (only one point within extremes, zooming between two points).

Alternatively, we could reuse `no-data-to-display` logic, where series implements `series.hasData()`. Then it would be easier and code is already tested (I don't remember complains about when no-data is rendered, like we have for `showEmpty`):

```javascript
hasData: function () {
  return this.series.some(s => s.hasData());
}
```

-----
If we decide to add options for that (and pollute config imho), then we would need to to add some options that I can not imagine, unfortunately. Something like `showEmptyWhenSeriesHidden`, `showEmptyWhenExtremesDefined`?  Or `isEmpty: function () { ... }`? I don't know.

**Comment by TorsteinHonsi** [comment]
Ok, let's change the behaviour then. It seems that is what most users expect. We can do that with v7.1. We can move the `Series.hasData` feature from `no-data-to-display.js` to `Series.js` (and for those series types checking only the point length, to their specific prototypes).
