### ISSUE TITLE
bubbleLegend bug using stock.js and map.js module

### ISSUE THREAD

**Issue by jbkunst** [highcharts/highcharts#10101]
Hi there:

I'm trying to get a bubble legend using the next configuration/modules:

```
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/stock.js"></script>
<script src="https://code.highcharts.com/maps/modules/map.js"></script>
```

#### Expected behaviour

Have only one bubble legend.

#### Actual behaviour

There are 3 legends overlapping:

![image](https://user-images.githubusercontent.com/56481/52529760-87887000-2cd6-11e9-8aca-7812fc482050.png)

#### Live demo with steps to reproduce

https://jsfiddle.net/jbkunst/L7cfweg1/1/

#### Product version

Stables version at this date

#### Affected browser(s)

At least google chrome

**Comment by KacperMadej** [comment]
Hi @jbkunst 

Thank you for reporting about this problem.

The part responsible shouldn't be loaded multiple times. The same events are being added for each file containing the bubble legend part.

_Internal note:_
@ppotaczek please see [this comment](https://github.com/highcharts/highcharts/issues/7729#issuecomment-364853012) and the commit above it for the suggested fix
