### ISSUE TITLE
DateTimeLabelFormat showing day of week when not specified

### ISSUE THREAD

**Issue by david97j** [highcharts/highcharts#10114]
#### Expected behaviour
The graph should be showing in the tooltip date only the values that I specify in the dateTimeLabelFormat property.

#### Actual behaviour
The graph is showing day of week in the tooltip but i haven't declared it on the dateTimeLabelFormat property.

#### Live demo with steps to reproduce
https://jsfiddle.net/a3b5Lfnm/

#### Product version
Last version of highcharts

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @david97j 

Let me explain:
> The graph should be showing in the tooltip date only the values that I specify in the dateTimeLabelFormat property.

This is not correct. You only change default values for: https://api.highcharts.com/highcharts/tooltip.dateTimeLabelFormats - that means `millisecond` still has default format `%A, %b %e, %H:%M:%S.%L`. You can change it like any other option: https://jsfiddle.net/BlackLabel/hzapqtum/1/
