### ISSUE TITLE
Lines appear on Browser resize

### ISSUE THREAD

**Issue by andrewcampey** [highcharts/highcharts#10113]
#### Expected behaviour
When I zoom in or out on my browser my column chart with no spaces between columns should remain a solid block.

#### Actual behaviour
When I use the zoom functionality of my browser to zoom in or out (Ctrl + Mouse Wheel on Windows also works) then white bars appear on my graph.
See here
http://recordit.co/pzbb4N1aWV

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8b2cnogy

#### Product version
Highcharts 7.0.3

#### Affected browser(s)
Chrome
(On Firefox the lines appear to always appear)

**Comment by pawelfus** [comment]
Hi @andrewcampey 

Thanks for reporting the issue. This is how anti-aliasing works in browsers. You can change this behaviour:

```css
svg {
  shape-rendering: crispEdges;
}
```
Demo: https://jsfiddle.net/BlackLabel/8b2cnogy/6/

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
