### ISSUE TITLE
First/last xAxis label cut off

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#10111]
#### Expected behaviour
Last x-axis label should be allowed to extend beyond the plot area when chart.spacingRight provides room for it.

#### Actual behaviour
The last x-axis label gets an ellipsis.

#### Live demo with steps to reproduce
http://jsfiddle.net/kzoon/6oq0327b/23/ shows that the the last x-axis label gets an ellipsis, while there is plenty room to render it, because I set chart.spacingRight to 100.
When I 'make room' by using an opposite y-axis the label _doesn't_ get cut off. See https://jsfiddle.net/kzoon/3p6cm217/4/
Notice that in the last fiddle the _first_ axis label gets cut off.

Applying 'overflow': 'allow' on the label did not solve my issue, because it suppresses ellipsis altogether (see http://jsfiddle.net/kzoon/6oq0327b/26/)

#### Product version
HighCharts 6, 7

#### Affected browser(s)
All

**Comment by kzoon** [comment]
Probably my fault: 
If I use marginRight< I do get my last label: http://jsfiddle.net/kzoon/6oq0327b/32/

Without marginRight it looks like it cuts off too soon, but I could be wrong:  http://jsfiddle.net/kzoon/6oq0327b/35/

**Comment by KacperMadej** [comment]
Hi @kzoon 

Using `marginRight` will resolve the issue as you already shown in your demo.

Default last label overflows the axis on right side, so it's being moved left to fit under the axis. After that move the label will overlap with the closest label (or is so close that is being classified as overlapping), so ellipsis is being applied.

Would you like me to label this issue as enhancement suggestion for axis labels spacing?

**Comment by kzoon** [comment]
My only remaining issue is the cut-off in case you set neither margin nor spacing (http://jsfiddle.net/kzoon/wy967hv5/1/). I suppose it's technically correct, but a bit unexpected.
