### ISSUE TITLE
Area chart cannot be exported to PDF when using svg2pdf explicitly

### ISSUE THREAD

**Issue by constantintaivan** [highcharts/highcharts#10112]
Hello, 

#### Expected behaviour
Area chart should be exported to PDF.

#### Actual behaviour
The export does not work due to console errors within svg2pdf.js. It looks like clipPathId is null.
![image](https://user-images.githubusercontent.com/19735774/52595160-16b39600-2e45-11e9-87e3-5dcc9870d1fe.png)
This issue is reproduced for jsPDF 2.0.1 and svg2.pdf 1.3.3

#### Please see this chart example. 
In this case is not reproduced.  Libraries need to be updated as above.
http://jsfiddle.net/4k5qsy6L/

Thank you!

#### Product version
Highcharts JS v7.0.1 (2018-12-19)

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
It seems to work with the current versions from our CDN: http://jsfiddle.net/highcharts/pzvhfa4b/2/

**Comment by pawelfus** [comment]
Hi @constantintaivan 

Thanks for reporting the issue. Unfortunately, I'm not able to recreate the issue, just downloaded packages from yWorks team (I don't know why, it still says v2.0.0 in jsPDF), and copy&pasted them in fiddle: http://jsfiddle.net/BlackLabel/kx8cjdyo/4/ - looks fine. Could you try setting up the demo again? Thanks!

**Comment by constantintaivan** [comment]
Hello Torstein,

Please check this fiddle: http://jsfiddle.net/5qxLvzh4/3/
I could reproduce it here by adding manually the SVG generated with Highcharts. Please see console errors:
![image](https://user-images.githubusercontent.com/19735774/52720628-e03e5e00-2f9f-11e9-948a-cf41d89d7541.png)

In my case I was testing with uncompressed .js files and the error is the same.

Thank you!
Regards,

**Comment by TorsteinHonsi** [comment]
It seems to be caused by the clip path referring a location of the web page that generated the chart. If we remove the clip path, your fiddle works:  

`clip-path="url(http://inside-local/#highcharts-rzqbh5z-4834)"`

Instead of reading the SVG directly off the page, you should use [Chart.getSVG](https://api.highcharts.com/class-reference/Highcharts.Chart#getSVG) where this is taken care of.

**Comment by constantintaivan** [comment]
Thank you! That was the issue. Now beautiful charts are rendered in PDF too. 
I start using Chart.getSVG.
