### ISSUE TITLE
Vector series don't follow to no clip

### ISSUE THREAD

**Issue by C0D3D3V** [highcharts/highcharts#10115]
#### Expected behaviour
Vectors should be able to be drawn outside of the grid, just like windbarbs in the demo.

#### Actual behaviour
Vectors (in red) are not displayed outside the grid, but windbarbs (in green) are displayed outside.

#### Live demo with steps to reproduce
https://jsfiddle.net/c0d3d3v/jhg9navL/

**Comment by C0D3D3V** [comment]
The same is also true for Scatter charts.
Is this a desired behavior?

**Comment by pawelfus** [comment]
Hi @C0D3D3V 

Thank you for reporting the issue. Vector, scatter (and other) series render marker/points only when `x` and `y` values are within extremes. For a windbarb series, we check only `x` to be within extremes.

Windbarb:
https://github.com/highcharts/highcharts/blob/f7a04222141ed57a1ce3155a529c24c91ecd8aa4/js/modules/windbarb.src.js#L248-L250

Vector:
https://github.com/highcharts/highcharts/blob/f7a04222141ed57a1ce3155a529c24c91ecd8aa4/js/modules/vector.src.js#L196-L197

Unfortunately, I don't know the origin of that difference. @TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
> Unfortunately, I don't know the origin of that difference

It's because we wanted to be able to render wind barbs below the pane. But there's really no good reason for not allowing the same with vectors.
