### ISSUE TITLE
Missing types in class Chart

### ISSUE THREAD

**Issue by Timppe** [highcharts/highcharts#10125]
#### Expected behaviour
I expect that all the members and methods in class Chart (and all other classes for that matter) exist in both the official documentation and in the type definitions. https://api.highcharts.com/class-reference/Highcharts.Chart

#### Actual behaviour
They don't. For instance, I would currently need hoverPoint, hoverPoints and hoverSeries, but they aren't in the documentation and neither are they in the type definitions.

#### Steps to find this out
Put a breakpoint into a running application and hover on `this.chart` to see which members and methods actually exist in the chart. E.g. when I did this, I could see these things (exluding members starting with _ because I don't expect those to be publicly available because _ suggests that it's an internal variable): 
`"angular", "axes", "axisOffset", "bounds", "btnCount", "buttonOffset", "callback", "cancelClick", "chartBackground", "chartHeight", "chartWidth", "clipBox", "clipOffset", "clipRect", "colorCounter", "container", "containerHeight", "containerWidth", "exportDivElements", "exportEvents", "exportSVGElements", "exporting", "exportingGroup", "hasCartesianSeries", "hasRendered", "hcEvents", "hoverPoint", "hoverPoints", "hoverSeries", "index", "inverted", "isDirtyBox", "isDirtyExporting", "isResizing", "labelCollectors", "legend", "margin", "marginBottom", "marginRight", "mouseDownX", "mouseDownY", "mouseIsDown", "navigation", "onload", "options", "pane", "plotBackground", "plotBorder", "plotBorderWidth", "plotBox", "plotHeight", "plotLeft", "plotSizeX", "plotSizeY", "plotTop", "plotWidth", "pointCount", "pointer", "polar", "proceed", "renderTo", "renderer", "series", "seriesGroup", "spacing", "spacingBox", "styledMode", "subtitle", "symbolCounter", "time", "title", "titleOffset", "tooltip", "unbindReflow", "userOptions", "xAxis", "yAxis"`

#### Product version
Highcharts 7.0.3

**Comment by pawelfus** [comment]
Hi @Timppe 

We are aware of missing private properties (not only starting with `_` explicite) that are not documented. We are adding them as type definitions progress. Personally, I think most of the members your listed shouldn't be available - for example `exportSVGElements`, `hcEvents` or `unbindReflow`. The most important ones area already available: https://api.highcharts.com/class-reference/Highcharts.Chart#axes (like `xAxis`, `yAxis`, `chartWidth`, `chartHeight` etc). From the list you posted I would say these should be available: 
- `hoverPoint` (sync charts)
- `hoverPoints` (sync charts)
- `hoverSeries` (sync charts)
- `index` (sync charts)
- `inverted` (plugins)
- `userOptions` (plugins, storing chart)

@bre1470, @TorsteinHonsi  - what do you think? Should we provide TS (and docs) for the whole library?

**Comment by Timppe** [comment]
Thanks for your response. Yes, I should probably not have stated "all", since I don't know exactly what is supposed to be private and what not, I just assumed my request applies to many of those members, since it applied to the ones I needed. You are the ones who knows best.

Nevertheless, I already would expect the official docs to contain all the publicly intended members and methods (including at least the ones you listed), since this is a commercial product. I can understand if everything is not typed yet, since your official statement is still that TS is in beta currently.

**Comment by TorsteinHonsi** [comment]
> I already would expect the official docs to contain all the publicly intended members

Agreed, with a focus on _publicly intended_. As Pawel says, most of those you listed are privately intended, but nonetheless, I agree some of them should be exposed.

I agree with Pawel's suggestions on properties that should be documented.

**Comment by bre1470** [comment]
We should just be aware, that we have to support every official property for some time. If we change internal processes thanks to ES6 migration, we can earliest get rid of documented API members in the next major version.
