### ISSUE TITLE
Highcharts.js (Highstock.js) issue: when Boost module used then chart is shown with distortion even when useGPUTranslations and usePreallocated options are set to false

### ISSUE THREAD

**Issue by ogorobets** [highcharts/highcharts#10120]
Hello,

#### Expected behaviour
Expected behaviour is to show candlestick chart without distortions when Boost module is used

#### Actual behaviour
I need to display 15000 points for both candlestick and column charts. When I don't use Boost module candlestick chart is displayed properly ( https://prnt.sc/mk44dr, live demo: https://jsfiddle.net/ogorobets/4nf02k9o/4/ ). But when I use Boost module (even with useGPUTranslations and usePreallocated options are set to false) then some parts of chart are missing in candlestick chart (https://prnt.sc/mk45qx), here is live demo: https://jsfiddle.net/ogorobets/t96ch5q7/6/ . Candlestick chart should look the same with using Boost module comparing to case when we don't use Boost module.

#### Live demo with steps to reproduce

Chart displaying properly: https://jsfiddle.net/ogorobets/4nf02k9o/4/ 
Some parts of candlestick chart are missing: https://jsfiddle.net/ogorobets/t96ch5q7/6/ 
No specific steps, just code from JSFiddle should be run and you can see the results.

#### Product version

Highcharts.js v6.2.0

#### Affected browser(s)
Tested in Chrome browser Version 71.0.3578.98 (Official Build) (64-bit), MacOS Mojave v. 10.14

Best regards,
Oleksandr Horobets

**Comment by pawelfus** [comment]
Hi @ogorobets 

Thank you for reporting the issue. You are right, charts should look the same with and without the boost module. It seems that `xAxis.ordinal` option is broken in boost mode, when disabling this in a chart without boost, we get the same result: https://jsfiddle.net/BlackLabel/pjnfketd/2/

**Comment by kamilkulig** [comment]
+1

**Comment by ivan0071** [comment]
Hello guys,

I was wondering, is there any ETA for this fix?
Can we have at least some approximate date, since that will help me a lot in planning the delivery of my product.

Regards,
Ivan

**Comment by cvasseng** [comment]
Hi @ogorobets, candlestick series are not supported in boost currently, but it should still of course work as expected in non-boosting mode when the rest of the chart is boosted.

We're currently looking into resolving this, and hope to have a fix within the end of the week.

**Comment by cvasseng** [comment]
The issue is caused by the lack of support for ordinal axis when using the boost module. In other words, the ordinal flag is disabled by the boost module as long as one of the series is boosting which causes the gaps in the candlestick series.

We're currently investigating potential workarounds.
