### ISSUE TITLE
Can not expand collapsed node in treegrid when initially set to collapsed : true

### ISSUE THREAD

**Issue by straaand** [highcharts/highcharts#10129]
#### Expected behaviour
When clicking the node it expands.

#### Actual behaviour
Nothing happens.

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/gantt/treegrid-axis/collapsed/

#### Product version

Latest stable for Highcharts Gantt / module treegrid

#### Affected browser(s)
Chrome, Firefox

**Comment by KacperMadej** [comment]
Hi @straaand 

Thank you for reporting about the bug.

Last working version is 7.0.2 - you could use it as a workaround.

**Comment by stridsbr** [comment]
I have the same issue with a twist. When I set it to false I can collapse it and open it. But when I set it to true I can't open it. I have tried Edge, Chrome and firefox.

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/gantt/treegrid-axis/collapsed/

**Comment by KacperMadej** [comment]
@stridsbr 
It's the same demo and your reported problem seems to be the same. Could you provide more info about the twist?

**Comment by stridsbr** [comment]
@KacperMadej It might be the same. But in the title it says: " initially set to collapsed : false" I only added that I see the issue when I start with collapsed: true, if I have Collapsed: false it works as expected.

**Comment by KacperMadej** [comment]
@stridsbr Right, thank you for pointing this our. Since this is the problematic scenario, I have updated the issue title.

**Comment by kamilkulig** [comment]
+1
