### ISSUE TITLE
Web fonts with Offline exporting not exported properly

### ISSUE THREAD

**Issue by Iswaryar22** [highcharts/highcharts#10135]
#### Expected behaviour
When using web fonts with offline-exporting.js then the font family is not captured properly when we export (Downlooad PNG,JPEG,SVG or PDF).Works fine without offline-exporting.

#### Actual behaviour
Web fonts should also be supported with offline exporting

#### Live demo with steps to reproduce
http://jsfiddle.net/ounb2e0k/

#### Product version
Highcharts v7.0.3

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @Iswaryar22 

Thanks for reporting the issue. 

Simplified demo: http://jsfiddle.net/z9dj31b2/

@oysteinmoseng FYI
