### ISSUE TITLE
Legend Click - Not Hide Space

### ISSUE THREAD

**Issue by lrapchan** [highcharts/highcharts#10133]
#### Expected behaviour
When you click on a caption, the series item is applied hide and realigns the graphic

#### Actual behaviour
When you click on the first item of the legend it totally removes and realigns the graphic, but if you click on any other, with the first one enabled it adds the item but not the space

#### Live demo with steps to reproduce
[http://jsfiddle.net/yURKz/](http://jsfiddle.net/yURKz/)

#### Product version
v5.0.14 

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @lrapchan 

Thank you for contacting us.

If you hide or show a series that will change axis extremes then the axis will change it's scale - so clicking first or last series is doing that, but others don't, unless clicked after some series are already hidden - but the same rule applies.

This is not a bug, so the issue will be closed. If you are looking for a feature that would recalculate axis categories based on visible series and their points then you could contact technical support for pointers, but that feature is not implemented and you might be facing two options - add the feature yourself or submit an idea on userVoice where the most popular are being implemented.

https://www.highcharts.com/blog/support/

https://highcharts.uservoice.com/forums/55896-general

**Comment by lrapchan** [comment]
![image](https://user-images.githubusercontent.com/39376117/52785960-99547500-3040-11e9-8cc7-eaea6b6a805f.png)

right, but if I click on the second or third item, it is not removed, it takes up space on the chart

**Comment by sebastianbochan** [comment]
Hi @lrapchan,
You can catch [legendItemClick](https://api.highcharts.com/highcharts/series.column.events.legendItemClick) and try to apply the workaround from the demo: http://jsfiddle.net/whFvA/4/. If you will not be able to use it in your scenario, please prepare a simple demo on the jsfiddle and contact with us by one of the tech-support channels (forum / stackoverflow or email)

**Comment by TorsteinHonsi** [comment]
As a best practice note, Highcharts is not designed to set up one-point-per-series like that. Typically, a series is a series of points. In your case, it would look like this: http://jsfiddle.net/highcharts/qasyug95/.

Then you don't get the interactive legend, if that's a requirement for you. But as far as I can see it doesn't matter much in this case, at least not until you get more items in the chart. But the chart data is already easily readable since you have the category axis labels below each column - you don't really need the legend for the sake of interpreting the chart.

**Comment by lrapchan** [comment]
hello @sebastianbochan 
I used the following code and it worked for now, however when clicking the drilldown and then drillup stops working.

`                             legendItemClick: function () {
                                var series = this,
                                        seriesIndex = series._i,
                                        xAxis = series.xAxis,
                                        newBreaks = [];
                                if (series.visible) {
                                    newBreaks = xAxis.options.breaks;
                                    newBreaks.push({
                                        from: seriesIndex,
                                        to: seriesIndex + 1,
                                        seriesIndex: seriesIndex
                                    });
                                } else {
                                    Highcharts.each(xAxis.options.breaks, function (br) {
                                        if (br.seriesIndex !== seriesIndex) {
                                            newBreaks.push(br);
                                        }
                                    });
                                }
                                xAxis.update({
                                    breaks: newBreaks
                                });`

**Comment by sebastianbochan** [comment]
Hi @lrapchan,
Could you simplify your chart and reproduce as live demo on the jsfiddle.net? It will allow me to debug it
