### ISSUE TITLE
Pie chart event.click delayed update [selected, sliced]

### ISSUE THREAD

**Issue by yingyuk** [highcharts/highcharts#10136]
#### Expected behaviour
When the series is clicked for the first time, `event.point.options` [selected and sliced] status is `true`

#### Actual behaviour
when the series is clicked, `event.point.options` [selected and sliced] status is delayed update

#### Live demo with steps to reproduce
[https://jsfiddle.net/8bcqjdL7/](https://jsfiddle.net/8bcqjdL7/)

#### Product version
7.0.3

#### Affected browser(s)
Chrome 72

**Comment by pawelfus** [comment]
Hi @yingyuk 

Thank you for reporting the issue. This is expected behaviour. State of the point is not updated until custom callback is executed. This is designed this way, because depending on what you return in the callback, you can prevent default action from being called or let it happen. For example: https://jsfiddle.net/BlackLabel/z1uop06w/1/ - state is never updated because we always return `false`.

**Comment by yingyuk** [comment]
Hi @pawelfus 
I need the `selected` state to associate some UI interactions; [https://jsfiddle.net/r9sxko3m/](https://jsfiddle.net/r9sxko3m/)
So I can't stop the default behavior;

Is there any way to get real-time selected?

**Comment by yingyuk** [comment]
Not elegant method.
[https://jsfiddle.net/4f9v23rb/](https://jsfiddle.net/4f9v23rb/)

**Comment by pawelfus** [comment]
Hi @yingyuk 

If you need `selected` state, then I suggest [`series.point.events.select`](https://api.highcharts.com/highcharts/series.pie.point.events.select) ( and `unselect`) events instead. It's called the same way as `click` (`options.selected` is delayed), but you have exact information about the action, so you don't need `options.selected` option at all. Demo: https://jsfiddle.net/BlackLabel/3tqkjLoh/6/

Of course, if you need all selected points, call `getSelectedPoints()`. Then in `select` event don't forget to use `this` (current point) with other select points in other actions. In `unselect` event, don't forget to remove `this` from selected points array. Actually, the same you can do in `click` event, but `select` and `unselect` events sound better anyway.

**Comment by yingyuk** [comment]
thank you
