### ISSUE TITLE
Problem to delete flags on Highstock chart with GUI tools

### ISSUE THREAD

**Issue by fabiocvalente** [highcharts/highcharts#10144]
When using GUI tools of Highstock, I can add and edit flags, but I can't remove then.

#### Expected behaviour
Remove flags when the trash icon is clicked.

#### Actual behaviour
Flags are not removed when the trash icon is clicked.

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/stock-tools-gui

1. Click on the flag button os the toolbar.
2. Add one or more flags on the chart.
3. Click on one of the flags.
4. Click on the trash icon on the panel that appears on the upper right side of the chart.

#### Product version
Highstock v7.0.3

#### Affected browser(s)
Any

**Comment by pawelfus** [comment]
Hi @fabiocvalente 

Thank you for reporting the issue. You are right, button should remove the flag, right now it does nothing.

**Comment by amargautam** [comment]
@pawelfus are you planning a fix for this in an upcoming release?

**Comment by pawelfus** [comment]
Yes, I am.
