### ISSUE TITLE
Tooltip formatter has wrong TypeScript definitions

### ISSUE THREAD

**Issue by ngehlert** [highcharts/highcharts#10147]
#### Expected behaviour
Have correct typings :)

In the documentation it is mentioned that the the tooltip formatter `this` changes, based on whether the tooltip is shared. However the typings only work for tooltips that are not shared.
```
export interface TooltipFormatterContextObject {
    color: ColorString;
    colorIndex?: number;
    key: number;
    percentage?: number;
    point: Point;
    series: Series;
    total?: number;
    x: number;
    y: number;
}
```
E.g. this.points is missing for shared tooltip.

Also if you use a flag-series the typings for this.point are also not correct, e.g. the title and text from the flag is missing

**Comment by sebastianbochan** [comment]
Hi @ngehlert,
Thank you for reporting.

FYI @bre1470

**Comment by ngehlert** [comment]
thanks for adding the `this.points`. Just want to bring this up again because of the second issue regarding the tooltip formatter 

> flag-series the typings for this.point are also not correct, e.g. the title and text from the flag is missing

**Comment by bre1470** [comment]
Thank you. I have overlooked this one.
