### ISSUE TITLE
variwide chart axis label alignment issue with rotation

### ISSUE THREAD

**Issue by rajeshdanabal** [highcharts/highcharts#10145]
#### Expected behaviour

Vertically rotated x-axis labels should align properly.

#### Actual behaviour
When we have multiple x-axis labels which are rotated vertically, label alignments are becoming misplaced.

#### Live demo with steps to reproduce
http://jsfiddle.net/rajeshdanabal/wmds2p5k/24/

#### Product version

Highcharts-V7.0.3

#### Affected browser(s)
Google Chrome - Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Hi @rajeshdanabal 

Thank you for reporting the issue. 

Simplified demo: http://jsfiddle.net/z3andem8/

**Comment by rajeshdanabal** [comment]
Hi @pawelfus  

Thank you for your response. Could you please provide me some work around, if there is any?

**Comment by sebastianbochan** [comment]
Hi @rajeshdanabal,
As a workaround, you can define [step](https://api.highcharts.com/highcharts/xAxis.labels.step) which improves readability. 

Demo:
- http://jsfiddle.net/BlackLabel/w80u27rh/1/

**Comment by rajeshdanabal** [comment]
Hi @sebastianbochan,

Thank you for the work around. I figured it out that when we define **step : 1** (by default *undefined*), It is working as expected.

Demo:
* http://jsfiddle.net/rajeshdanabal/wmds2p5k/28/
