### ISSUE TITLE
Typescript typing for AxisSetExtremesEventObject could be improved

### ISSUE THREAD

**Issue by ngehlert** [highcharts/highcharts#10151]
This one is a little bit more tricky than my other typing questions, so I'll start by explaining the use case.

I have a basic Highstock chart with a navigator and need a proper onChange-Event once the range is changed in the navigator (an event when the change is complete, not while dragging but rather on mouseup or hard click)

Those are the checks I'm currently doing in `Chart.xAxis.events.setExtremes`
```
// When the navigation bar was moved by mouse
if (event.DOMEvent && event.DOMEvent.type === 'mouseup') {
    onRangeChangeCallback(event);
}

// On click in the navigation bar chart
if (event.trigger === 'navigator' && event.triggerOp === undefined) {
    onRangeChangeCallback(event);
}

// On click on the navigation bar
if (
    event.DOMEvent &&
    event.DOMEvent.type === 'click' &&
    event.trigger === 'navigator' &&
    event.triggerOp === 'navigator-drag'
) {
    onRangeChangeCallback(event);
}
```

But `DOMEvent` and `triggerOp` are not available in the `AxisSetExtremesEventObject` interface. 

Is there a different/better way to properly recognize this change event (debounce is currently not an option)? Can those two properties be added to the interface?

**Comment by pawelfus** [comment]
Thanks @ngehlert 

I think `DOMEvent` should be available.  Regarding `triggerOp` - it's not used anymore, and should be removed. We can keep this for a backward compatibility, however it's better to use `event.DOMEvent.type === 'mouseup'` in this case. I won't remove `triggerOp` now, let me leave that decision up to @TorsteinHonsi.

@bre1470 - the available options for `trigger` list (all `Events`, not only `AxisSetExtremesEventObject)`: `scrollbar` (stock), `zoom` (highcharts), `pan` (highcharts), `navigator` (stock), `rangeSelectorButton` (stock), `rangeSelectorInput` (stock), `traverseUpButton` (treemap) - can we somehow provide that list?

**Comment by bre1470** [comment]
@pawelfus Is this about all Highcharts events with `trigger` property?

There is probably a way to solve it one way or the other.

**Comment by pawelfus** [comment]
Yes, that's a list of known values for a `trigger` property (with a module name in the brackets) - for any event. I think it would be cool to have this list, but it might be hard to maintain..
