### ISSUE TITLE
Export styling options not applied in exported chart (jpg, svg, png)

### ISSUE THREAD

**Issue by daviddebie** [highcharts/highcharts#10154]
#### Expected behaviour
Providing additional styling options to exporting.js should result in the exported chart being styled different from the actual chart

#### Actual behaviour
Options for xAxis styling are ignored, while options for legend styling are applied. The styling for xAxis worked in Highcharts 5

#### Live demo with steps to reproduce
https://jsfiddle.net/daviddebie/xrLj75ub/1/

#### Product version
Highcharts 7, Export module

**Comment by sebastianbochan** [comment]
Hi @daviddebie,
The problem is more complex and related with the bug: https://github.com/highcharts/highcharts/issues/2022

**Workaround:**
Use the array of objects instead of the single object as xAxis.

```
exporting: {
    chartOptions: {
      plotOptions: {
        series: {
          dataLabels: {
            enabled: true
          }
        }
      },
      xAxis: [{
        labels: {
          style: {
            fontSize: "30px"
          }
        }
      }],
      legend: {
        itemStyle: {
          fontSize: "30px"
        }
      }
    }
  }
```

Demo:
-
