### ISSUE TITLE
Typescript typing and documenation for navigator.series is missing a property

### ISSUE THREAD

**Issue by ngehlert** [highcharts/highcharts#10150]
In the (highstock) navigator.series documentation there is no data property mentioned (https://api.highcharts.com/highstock/navigator.series), however in your example (https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/navigator/series-data/) you provide a data attribute.

I guess you covered it with the sentence in the introduction 'Available options are the same as any series'. But the problem is if it is not reflected in the documentation it is not available in TypeScript

Would be great if you can adjust the documentation and TS type for NavigatorSeriesOptions

Note: Just cross-post this here, since I wasn't sure which is the proper channel for TypeScript Typings (https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/36859579-improve-navigator-series-documentation)

**Comment by bre1470** [comment]
@ngehlert 
Thank you for bringing this up.
