### ISSUE TITLE
Treemap - update issue

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#10159]
After get into the nested node and update to some data, a button 'back' stay, what create error, because the function is trying to invoke name for a previously nested data. 

#### Live demo with steps to reproduce

[demo](https://jsfiddle.net/BlackLabel/b3pucref/)

#### Product version

Highcharts v7.0.3

#### Affected browser(s)

All

**Comment by sebastianbochan** [comment]
**Internal note**
Related with https://github.com/highcharts/highcharts/pull/9976
