### ISSUE TITLE
Scrolling backwards then forward causes latest point to vanish

### ISSUE THREAD

**Issue by JimmyDonDimDome** [highcharts/highcharts#10168]
#### Expected behavior
1.) Change Zoom from "All" to "1m"
2.) Change chart type from ohlc to candlestick

When scrolling backwards on x-axis then forwards (using your mouse), the latest candlestick should be visible as per initialization

#### Actual behavior
1.) Change Zoom from "All" to "1m"
2.) Change chart type from ohlc to candlestick

When scrolling backwards on x-axis then forwards (using your mouse), the latest candlestick is no longer visible

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/stock-tools-gui

#### Product version
Highstock v7.0.3 (2019-02-06)

#### Affected browsers tested on
Firefox v65.0.1
Chrome v72.0.3626.109

**Comment by sebastianbochan** [comment]
Hi @JimmyDonDimDome,
Thank you for reporting. I agree that its a bug related with dataGrouping.

**Internal note**
Related with the https://github.com/highcharts/highcharts/issues/4076
