### ISSUE TITLE
Gantt chart with only one category

### ISSUE THREAD

**Issue by hiroko3** [highcharts/highcharts#10161]
#### Expected behaviour
I want to create a Gantt chart with only one category.  
  
#### Actual behaviour
I can not display it as requested.   
The line of yAxis has extended to the second area.   
  
#### Live demo with steps to reproduce

https://jsfiddle.net/hiroko3/9ftmnh5o/81/  
  
#### Product version

Highcharts Gantt - Highcharts JS v7.0.3 (2019-02-06)  
  
#### Affected browser(s)
Google Chrome

**Comment by sebastianbochan** [comment]
Hi @hiroko3,
Thank you for reporting about the bug.

FYI @jon-a-nygaard @oysteinmoseng

**Comment by raf18seb** [comment]
Hi,

As a workaround, you can use **yAxis.uniqueNames**
https://jsfiddle.net/BlackLabel/160wcsf8
