### ISSUE TITLE
Charts smaller after upgrade from 5.0.12 to 6.2.0

### ISSUE THREAD

**Issue by MiroLiska** [highcharts/highcharts#10167]
#### Expected behaviour
Pie charts should be a bit bigger, as they used to be in 5.0.12. Maybe you have changed some default which I need to set back to the original value.

#### Actual behaviour
Charts are smaller. 

#### Live demo with steps to reproduce
See the chart in 5:0.12 : http://jsfiddle.net/yrtspd3n
![chartin5012](https://user-images.githubusercontent.com/23024867/52963566-6e4f8580-33a0-11e9-8644-69160062c57a.png)

And exactly the same code with 6.2.0: http://jsfiddle.net/yrtspd3n/1/
![chartin620](https://user-images.githubusercontent.com/23024867/52963574-74456680-33a0-11e9-9292-5f536df9dbd7.png)

#### Product version
6.2.0 and higher

#### Affected browser(s)
e,g. Firefox

**Comment by MiroLiska** [comment]
I have just seen that the problem is cause by legend - it is somehow bigger than before and that makes the chart smaller. How can I set the legend back so that it looks exactly as in 5.0.12?

**Comment by pawelfus** [comment]
Hi @MiroLiska 

Thanks for reporting the issue. I think this is a bug, with border we can see this clearly: http://jsfiddle.net/BlackLabel/rb1aLwpt/

**Workaround:**
Set [`legend.alignColumns`](https://api.highcharts.com/highcharts/legend.alignColumns) to false: http://jsfiddle.net/BlackLabel/Lr4g2oz0/15/ - it won't work exactly as in v5, but pie's diameter will be the same. Or use version before v6.1.0 - bug was introduced in v6.1.0 with `alignColumns` option.

*Internal note:*
It's a regression after a851faa03

**Comment by MiroLiska** [comment]
Hi

Unfortunately, I have to use the alignColumns feature, because without it I would have another breaking change against 5.0.12.

Original code (5.0.12):
jsfiddle.net/L3614pjv/1/

[cid:image001.png@01D4C85A.E6FF9B70]
New code (6.2.0):
jsfiddle.net/L3614pjv/

[cid:image002.png@01D4C85A.E6FF9B70]

5.0.12 may look messy, but I desperately fight with space in my application ☺

Best regards

Miro
