### ISSUE TITLE
Series getting disappear on adding points to series

### ISSUE THREAD

**Issue by sowmyakj** [highcharts/highcharts#10169]
Hi,
I have added three series to chart, when i'm trying to shift the chart on adding point to it dynamically in faster rate, one series among them starts to disappearing from left end, if i disable other two series then it will render properly.

![image](https://user-images.githubusercontent.com/25794715/53016231-251c3600-3473-11e9-8400-16bc918f0dc1.png)

When other two series disabled

![image](https://user-images.githubusercontent.com/25794715/53016326-5f85d300-3473-11e9-933f-4ed2bcbcbd21.png)

Highcharts, Highstock v6.0.7 version i'm using.

Any help will be appriciated, thank you in advance.

**Comment by pawelfus** [comment]
Hi @sowmyakj 

Thanks fo reporting the issue. It looks like connected to [`xAxis.ordinal`](https://api.highcharts.com/highstock/xAxis.ordinal) - did you try to disable it? If that's not the case, please recreate issue in jsFiddle, thanks!

**Comment by sebastianbochan** [comment]
Closed due to inactivity. Please reopen when new details will be available.
