### ISSUE TITLE
Labels do not appear in pie charts if text is in RTL language

### ISSUE THREAD

**Issue by ahmedqasid** [highcharts/highcharts#10162]
#### Expected behaviour
The labels in Arabic and Hebrew should appear

#### Actual behaviour
The charts shows only text in English and Simplified Chinise
But Arabic and Hebrew text is not displayed at all
![image](https://user-images.githubusercontent.com/915362/52901870-9b216280-3211-11e9-8a16-bf2c65c6af5c.png)
#### Live demo with steps to reproduce

https://jsfiddle.net/yat9L67p/1/

#### Product version

Highcharts
#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Hi @ahmedqasid 

Thank you for reporting the issue and my apologies for the late reply. I didn't receive any notification about your issue.

**Workaround:**
Set [`series.dataLabels.style.textOutline`](https://api.highcharts.com/highcharts/plotOptions.pie.dataLabels.style) to `"none"`: https://jsfiddle.net/BlackLabel/e56pwuo9/

**Comment by ahmedqasid** [comment]
Thanks for your response @pawelfus
And thanks for the workaround

**Comment by sebastianbochan** [comment]
The second workaround is settin the `useHTML` flag as true.

Demo:
- http://jsfiddle.net/BlackLabel/m702Lxqz/

**Comment by sebastianbochan** [comment]
**Internal note**
It looks like a problem in the `applyTextOutline` method and lines:

```
tspans.forEach(function (tspan, y) {
                var clone;
                // Let the first line start at the correct X position
                if (y === 0) {
                    tspan.setAttribute('x', elem.getAttribute('x'));
                    y = elem.getAttribute('y');
                    tspan.setAttribute('y', y || 0);
                    if (y === null) {
                        elem.setAttribute('y', 0);
                    }
                }
                // Create the clone and apply outline properties
                clone = tspan.cloneNode(1);
                attr(clone, {
                    class: 'highcharts-text-outline',
                    fill: color,
                    stroke: color,
                    'stroke-width': strokeWidth,
                    'stroke-linejoin': 'round',
                    zIndex: 0
                });

                elem.insertBefore(clone, firstRealChild);
            });
```

It seems that `elem.insertBefore(clone, firstRealChild);` push the element in wrong place. 
The questions is if in that case when solution is setting `useHTML` or we should refactor this method.

**Comment by TorsteinHonsi** [comment]
> It seems that elem.insertBefore(clone, firstRealChild); push the element in wrong place.

Does it mean that we can fix the issue by inserting the element in another place? In that case, we should try inserting it conditionally.

**Comment by ochristensen** [comment]
I partially retract the workaround's effectiveness:
https://jsfiddle.net/zenzizen/jpds3hv1/15/
the label containing RTL becomes very disjointed, badly affecting our desired formatting
