### ISSUE TITLE
HighCharts Circular or Pie Chart having issues in Chrome

### ISSUE THREAD

**Issue by KrisGurusamy** [highcharts/highcharts#10175]
#### Expected behaviour
The pie charts are supposed to deliver in full size when displayed in browser

#### Actual behaviour
In Chrome, we keep seeing the circular charts shrinking into an unusable form. Multiple users have reported this issue, and since Chrome is one of the most-used browsers by our customers, we need to fix this with some urgency.

At first we thought it was related to a browser extension, but that wasn't consistently reproducible. Turning off the extension would fix it for a while, and then it would break again. And then turning the extension back on fixed it again temporarily, and it then broke once again. The only consistent thing I can do is to clear all cache/cookies, restart the browser, and then only the first time I view the charts, they appear correctly. Every time thereafter they break.

#### Product version
4.1.9

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @KrisGurusamy 

Thanks for reporting the issue. I can't help you without live demo (e.g. jsFiddle) of the issue. Note that you use quite old version of Highcharts (v4), while the current one is v7. It may be a bug in old version, in that case please upgrade Highcharts.

**Comment by sebastianbochan** [comment]
Closed due to inactivity. Please reopen when new details will be available.
