### ISSUE TITLE
Exporting using custom theme with export npm

### ISSUE THREAD

**Issue by vamsiak** [highcharts/highcharts#10177]
I am using Highchart themes, setting global font on UI by using Highcharts.setOptions() method ,
and I am using Highcharts export npm for exporting the same charts as images.
 
How do I get to pass on the same options/themes  wile export with export server npm.

**Comment by pawelfus** [comment]
Hi @vamsiak 

You posted on our bug tracker. For questions, please our other support channels: https://www.highcharts.com/blog/support/

PS: You can find answer in our exporting docs:
- CLI: `--globalOptions`: https://github.com/highcharts/node-export-server#command-line-arguments
- HTTP Server: argument `globalOptions`: https://github.com/highcharts/node-export-server#http-server
