### ISSUE TITLE
Microsoft Edge specific : Tooltip is not seen immediately on the chart

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#10171]
#### Live demo with steps to reproduce
https://jsfiddle.net/amrutaJgtp/dc34wLoh/

Follow the steps below on browsers Google Chrome and Microsoft Edge:-
1) Hit the JS fiddle
2) Press F12 - > Under Sources tab -> Open the highstock.src.js file
3) In API drawTrackerPoint, add 2 breakpoints : one at the call "point.onMouseOver(e)" and other one at the call "pointer.onTrackerMouseOut(e)"
4) Go to the JS Fiddle output, hover on any series point to see the tooltip
5) Observe where the debugger stops

It is observed that, we have 2 cases with respect to the browsers -
Case 1: On Google Chrome
When the mouse is hovered on any series point, the debugger stops on breakpoint "point.onMouseOver(e)" only.
Case 2: On Microsoft Edge
When the mouse is hovered on any series point, the debugger 1st stops on "point.onMouseOver(e)" and then also on 2nd breakpoint "pointer.onTrackerMouseOut(e)"
onTrackerMouseOut API internally calls the tooltip.hide function. Thus in my application, on Microsoft Edge browser, tooltip is hidden.
I verified it on other browsers(Google Chrome, Mozilla firefox, IE11), it works fine - tooltip is seen correctly and immediately without the need to click on the chart's plot area.
Hence I would like to know why the "onTrackerMouseOut" API is called in case of Microsoft Edge browser only? Since on Edge, the tooltip is not seen immediately. I have to click on the chart's plot area after which the tooltip is seen correctly.

#### Product version
Highcharts version : Observed on v6.1.1, reproduced on latest stable version also.
Microsoft Edge version : Microsoft Edge 41.16299.785.0, Microsoft EdgeHTML 16.16299
Google Chrome version : Version 71.0.3578.98

#### Affected browser
Microsoft Edge

This issue maybe similar to - https://github.com/highcharts/highcharts/issues/9403

**Comment by KacperMadej** [comment]
Hi @amruta30 

I'm not sure if the demo you provided is not showing the problem or if there's no problem.

Placing break points into code will cause the pause that triggers mouseout on Edge.
Here's a demo with copied core function and added console logs that doesn't interrupt code execution, but still allow to track what events are being fired. https://jsfiddle.net/BlackLabel/n0m95d7f/

I'm unable to see the problem (delayed or no tooltip on Edge) in a chart.

**Comment by sebastianbochan** [comment]
Im closing this ticket due to inactvitation.

Please reopen if live demo and additional details will be available.
