### ISSUE TITLE
Highstock chart missing series in navigator

### ISSUE THREAD

**Issue by MiroLiska** [highcharts/highcharts#10172]
#### Expected behaviour
The navigator should show data, exactly as in version 5.0.12.

#### Actual behaviour
The version 6.2.0 does not show the line chart anymore in the navigator below the chart.

#### Live demo with steps to reproduce
Have a look at the implementation in 5.0.12:
https://jsfiddle.net/j29rc8Lf/
![chartin5012](https://user-images.githubusercontent.com/23024867/53017636-bcbc5d00-3450-11e9-9889-58849bd5bfb7.png)

And now the same code in 6.2.0 - the line in navigator is gone:
https://jsfiddle.net/j29rc8Lf/1/ 
![chartin620](https://user-images.githubusercontent.com/23024867/53017639-bfb74d80-3450-11e9-928f-12d12744dd23.png)

#### Product version
Highstock 6.2.0 and higher

#### Affected browser(s)
Edge

**Comment by pawelfus** [comment]
Hi @MiroLiska 

This is expected behaviour. Since any series can be displayed in the navigator, visibility of the navigator-series is inherited from the parent series. In your case, it's `visible: false` - so both series are hidden. You can control navigator series through [`series.navigatorOptions`](https://api.highcharts.com/highstock/series.line.navigatorOptions) config, see: https://jsfiddle.net/BlackLabel/bm5erqjs/2/

**Comment by MiroLiska** [comment]
Hi

Only the first of my series (Not adjusted Prices) is set to not visible, the second (Adjusted Prices) is visible and that's why I can also see it.

    // now the data
    series: [{
        "type": "line",
        "name": "Not adjusted Prices",
        "visible": false,
        "color": chartPricesChartColors[0],
        "pointInterval": 86400000,
        "pointStart": Date.UTC(1999, 6, 7),
        "dataLabels": {},
        data: [90.75, 90.75, 93.25, 93.25, 93.25, 94
    }, {
        "type": "line",
        "name": "Adjusted Prices",
        "color": chartPricesChartColors[1],
        "pointInterval": 86400000,
        "pointStart": Date.UTC(1999, 6, 7),
        "dataLabels": {},
        data: [45.38, 45.38, 46.63, 46.63, 46.63, 47
    }]

I the series were not visible I would not see them, but I do. In 5.0.12 I can also see the series in the navigator, in 6.2.0 I see the Adjusted Prices series, but I see nothing in the navigator.

Miro

**Comment by MiroLiska** [comment]
One more thing, In your example at https://jsfiddle.net/BlackLabel/bm5erqjs/2/ it is sufficient to click twice in the legend on 'Not adjusted prices'.  That will cause the Navigator to get empty again ☹

**Comment by pawelfus** [comment]
Hi @MiroLiska 

I'm sorry, I don't follow your first answer. Could you explain this part?
> Only the first of my series (Not adjusted Prices) is set to not visible, the second (Adjusted Prices) is visible and that's why I can also see it.

Regarding hiding/showing series in the navigator, again it's expected. Navigator series is linked to the parent series, inheriting it's visibility state.

I guess you simply need a separate series in the navigator: https://jsfiddle.net/BlackLabel/bm5erqjs/13/
Changed options: 
- `plotOptions.series.showInNavigator` => false
-  added navigator series options: 
  ```
      "navigator": {
        "top": 445,
        series: {
        	data: getData(),
          visible: true,
          pointInterval: 86400000,
          pointStart : Date.UTC(1999, 6, 7)
        }
      },
   ```

**Comment by MiroLiska** [comment]
Hello
We have several points here:
1. I forgot that navigator shows only one series, I implemented our chart some years ago, that's why the confusion
2. We are still using 5.0.12. I wanted to upgrade to higher version and I saw the discrepancy described in this issue. I.e., either it is a bug now or it was a bug before and I was relying on buggy implementation in 5.0.12
3. The new implementation in 6.2.0 is in my opinion buggy - your example https://jsfiddle.net/BlackLabel/bm5erqjs/2/ shows the problem - initially is the navigator showing the series, but after clicking twice on the first series in the legend, the navigator will get empty and never show anything anymore.

**Comment by pawelfus** [comment]
ad 1. Navigator can show multiple series, as much as you want to: https://jsfiddle.net/BlackLabel/bm5erqjs/15/

ad 3. See my answer above:
 > Regarding hiding/showing series in the navigator, again it's expected. Navigator series is linked to the parent series, inheriting it's visibility state.

It's a direct result of #6193. If you want to keep navigator series always visible, please use separate series for the [navigator](https://api.highcharts.com/highstock/navigator.series). See my demo above for the example implementation.

**Comment by MiroLiska** [comment]
Ad 3 again - 'hiding' is OK, but where is the 'showing'? The navigator will never show anything anymore! https://jsfiddle.net/BlackLabel/bm5erqjs/2/

**Comment by pawelfus** [comment]
@MiroLiska - I'm sorry, it works for me..
![navigator](https://user-images.githubusercontent.com/1453926/53104540-d1bbed80-352f-11e9-8979-9c57da20b1a0.gif)

**Comment by MiroLiska** [comment]
You are right, I have described it wrongly - I am obviously confused from navigatorOptions: { visible: true } - what is it good for at all? It works only for initial state and then (after legend clicking) the navigator follows the current series visibility anyway? Moreover, when I apply it to second series, it does not do anything at all - https://jsfiddle.net/e5jvhzxo/

**Comment by pawelfus** [comment]
Hi @MiroLiska 

See #6193. How `visibility` is  helpful? If you don't have the legend, then you have a way to control what's displayed on the chart and you can change it. In a case of the legend, this is how `visibility` works. End user has an option to show/hide items on the chart through the legend, behaviour does not change.

Your second series doesn't work because `showInNavigator` is not set.

If you have any other questions, or something is not clear, please contact our support. This is our bug tracker.

**Comment by MiroLiska** [comment]
Then we need something like visibility : 'always', exactly the way it was in 5.0.12, because that behavior is gone. 
Visibility set to true together with legend makes no sense at all, since it works only for the first time the chart is displayed. I cannot imagine anybody would need such a thing.

**Comment by pawelfus** [comment]
I agree, this sounds strange. However, this is exactly how [`visible`](https://api.highcharts.com/highstock/series.line.visible) was designed: 

> Set the **initial visibility** of the series.

Just in case you need `always` option, you can simply hide series when you expect series to be hidden ([demo](https://jsfiddle.net/BlackLabel/ufg486dz/7/)): 

``` javascript
events: {
  hide: function () {
    if (this.options.isInternal) {
      this.setVisible(true, false);
    }
  }
},  
```
