### ISSUE TITLE
Narrator can't read HighChart while scan mode is off with Edge using 7.0.3

### ISSUE THREAD

**Issue by jayleems2018** [highcharts/highcharts#10184]
![narrator does not read while scan mode is off on edge](https://user-images.githubusercontent.com/38473977/53118742-a2db5280-3502-11e9-88d2-ff1a3193480e.JPG)
#### Expected behaviour
It should read the data in chart
![narrator does not read while scan mode is off on edge](https://user-images.githubusercontent.com/38473977/53118667-77f0fe80-3502-11e9-9003-323856dfbacc.JPG)

**Comment by jayleems2018** [comment]
Hi, I am show this chart.  The steps are to use Window 10 Edge. 
1. Start Narrator and press Caps + space to set scan off
2. Press tab key into each data point and notice it does not read
3. Tab into group name and notice it does not read.

Expect:
It should support which Narrator scan mode is off and read data correctly

**Comment by jayleems2018** [comment]
I tried on your sample with adding accessibility as on enclosed.  It behaves same as Narrator does not read data while scan mode is off.

**Comment by jayleems2018** [comment]
I accidently hit close

**Comment by sebastianbochan** [comment]
Hi @jayleems2018,
Thank you for reporting.

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
This will be fixed in the upcoming v7.1 release. A temporary workaround (provided by user) is available by editing the source of the accessibility module:

![image](https://user-images.githubusercontent.com/5276642/53187372-490e8180-3603-11e9-83f0-8bc8009c62a7.png)
