### ISSUE TITLE
Highstock.js issue: when new points are added to chart ( without chart redrawing) and then updated then "Cannot read property 'update' of undefined" error message appears

### ISSUE THREAD

**Issue by ogorobets** [highcharts/highcharts#10188]
Hello,

#### Expected behaviour
When new points are added using addPoint() API method to chart (without chart redrawing) and then new points are updated with someSeries.data[index].update(options) API method no error message should appear and those points should be updated properly. 

#### Actual behaviour
In this live demo (https://jsfiddle.net/ogorobets/71tfhs69/24/) I recreated roughly case of my application. We have a few tabs in application and one chart is shown in each of tabs. Chart is redrawn only for active tab. For not active tab chart data are updated with addPoint() API method and someSeries.data[index].update(options) API method and chart is redrawn only after tab becomes active. For chart in not active tab when someSeries.points[index].update(options) API is called for last chart point then "Cannot read property 'update' of undefined" error message appears in console of browser and chart points are not updated. To see error message in console live demo application should work a few minutes.

Initially to workaround this issue I used code as:
```
 let min = this.chart.xAxis[0].getExtremes().min;
 let max = this.chart.xAxis[0].getExtremes().max;
 this.chart.zoomOut();
 this.chart.xAxis[0].setExtremes(min, max);
```
After calling this code all points appear in someSeries.data array and all points can be updated properly. But for big charts (with 30000 points) this code works slowly so I stopped using it.

Now I use following workaround to update last point of area, candlestick and column charts:
```
 areaSeries.yData[areaSeries.yData - 1] = areaObj.y;
 areaSeries.isDirty = true;
 areaSeries.isDirtyData = true;
 areaSeries.options.data[areaSeries.options.data.length - 1] = areaObj;

 candlestickSeries.yData[candlestickSeries.yData.length - 1] = [
        candlestickObj.open,
        candlestickObj.high,
        candlestickObj.low,
        candlestickObj.close,
 ];
 candlestickSeries.isDirty = true;
 candlestickSeries.isDirtyData = true;
 candlestickSeries.options.data[candlestickSeries.options.data.length - 1] = candlestickObj;

 volumeSeries.yData[volumeSeries.yData.length - 1] = volumeObj.y;
 volumeSeries.isDirty = true;
 volumeSeries.isDirtyData = true;
 volumeSeries.options.data[volumeSeries.options.data.length - 1] = volumeObj;
```
But it would be good to have someSeries.data[index].update(options) API fixed to not use this hack. 

#### Live demo with steps to reproduce

Here is video where steps to reproduce issue are shown: https://screencast-o-matic.com/watch/cqnrol0he0
Live demo: https://jsfiddle.net/ogorobets/71tfhs69/24/
Steps to reproduce:
1. Open live demo
2. Wait for 2 mins
3. You can see in console "Cannot read property 'update' of undefined" error message appears

#### Product version

Highstock JS v7.0.3 

#### Affected browser(s)
Chrome browser version 71.0.3578.98 (Official Build) (64-bit), macOS Mojave v.10.14

Regards,
Oleksandr Horobets

**Comment by pawelfus** [comment]
Hi @ogorobets 

Thank you for reporting the issue. I'm not sure if I should classify this as a bug. As far as I remember, generating points is a bit heavy, so we resigned from that and `update()` should be called only on existing points. At this moment you just pick some point from `xData`, which does not have the reference in `data`.

Regarding your workaround: I think you don't need `isDirty` and `isDirtyData` flags to be set to true, instead I would do this:

```javascript
if (series.data[lastIndex]) {
  // Active chart, point added:
  series.data[lastIndex].update(...);
} else {
  // Inactive chart, point not created
  series.options.data[lastIndex] = ...;
  series.yData[lastIndex] = ...;
}
```
This will be certainly faster than the workaround I posted below.

**Simplified demo:**
https://jsfiddle.net/BlackLabel/3b8uyvce/2/

**Simplified workaround:**
Call `series.generatePoints()` after `series.addPoint()`:
- OP's demo: https://jsfiddle.net/BlackLabel/0rthadsv/1/
- simplified demo: https://jsfiddle.net/BlackLabel/3b8uyvce/6/
