### ISSUE TITLE
Elliot waves are showing one less line

### ISSUE THREAD

**Issue by amargautam** [highcharts/highcharts#10183]
#### Expected behaviour

Elliot 3 & 5 line should have 3 and 5 lines respectively.

#### Actual behaviour

Elliot 3 & 5 line has only 3 and 5 lines respectively.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui/

#### Product version

Highstock v7.0.3

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @amargautam,
Thank you for reporting. I understand you that one line is missing (in each case) and there should be i.e 3 lines (instead of 3 points and 2 lines). Is it correct?

**Comment by amargautam** [comment]
Hi @sebastianbochan 

Here are some examples

#### Elliot 3 (ABC) :point_down:

<img width="671" alt="screen shot 2019-02-21 at 9 43 50 pm" src="https://user-images.githubusercontent.com/3035438/53216232-f1334300-3621-11e9-849b-2c1f5df8c464.png">



#### Elliot 5 (12345) :point_down:

<img width="773" alt="screen shot 2019-02-21 at 9 43 20 pm" src="https://user-images.githubusercontent.com/3035438/53216244-fc866e80-3621-11e9-8717-f0ca98e8093f.png">

**Comment by sebastianbochan** [comment]
Hi @amargautam,
Thank you for your feedback. We will fix it as soon as possible.
