### ISSUE TITLE
Axis lineWidth is zero in IE9-64 using doc-mode 8

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#1018]
1. Start IE9 64 bit
2. Open example at http://jsfiddle.net/ZLAw4/2/show (the x axis line width defaults to 1 pixel and is visible)
3. Open Dev-tools (F12)
4. Change the Document Mode from IE9 to IE8

Result: The axis line is not visible
Expected: The line to be visible in both IE9 and IE8 document mode.

**Comment by cvasseng** [comment]
Hi! We're doing a bit of spring cleaning, and closing old issues. If you're still experiencing issues with this, please feel free to open a new issue! Thanks!
