### ISSUE TITLE
Update with null values issue

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#10187]
Update issue. The bug exists when one of the updated series include 'null' values and length of arrays is the same. 

#### Live demo with steps to reproduce

[Demo](https://jsfiddle.net/BlackLabel/4xqhaz5r/)

#### Product version

Highcharts JS v7.0.3

#### Affected browser(s)

All

**Comment by sebastianbochan** [comment]
**Workaround:**
Set x positions in each point.

Demo:
- https://jsfiddle.net/BlackLabel/opr6muwg/
