### ISSUE TITLE
SMA and EMA on volume series doesn't work

### ISSUE THREAD

**Issue by amargautam** [highcharts/highcharts#10192]
#### Expected behaviour
When applying SMA to volume series, the indicator should display on the volume pane and candlestick data should still be there.

#### Actual behaviour
When applying SMA to volume series, the indicator displays in the candlestick pane and replaces the candlestick data.

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/stock-tools-gui

1. Click on stocktools > indicator 
2. Select SMA
3. On the dropdown for series select APPL Volume
4. Click on Add

#### Product version
Highstock v7.0.3

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
HI @amargautam 

Thanks! You are right, it's broken - SMA should be displayed on the same pane as the main series, let me fix that.

**Comment by amargautam** [comment]
Hi @pawelfus 

Thank you for accepting it as a bug. Any idea which milestone you planning this for? I see that you already fixed it. Can we do it in v7.0.4?

**Comment by pawelfus** [comment]
Yes, I hope it will get into the master branch (v7.0.4 candidate).

PR: https://github.com/highcharts/highcharts/pull/10198
