### ISSUE TITLE
Highstock stocktools customization

### ISSUE THREAD

**Issue by amargautam** [highcharts/highcharts#10191]
This is more of a question after failing to find answers in the docs. I am sorry if I missed it in the docs. If you can kindly point me to the right place.

#### Expected behaviour
Annotations like verticle labels, Elliot 5 lines etc - any of them, would be light colored on dark background. How do I change all of these to color of my choosing if I use dark background?

#### Actual behaviour
Annotations by default are set to rgb(0,0,0). 

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/stock-tools-gui/dark-unica

#### Product version
Highstock v7.0.3

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @amargautam,
The github is our bugtracker, so for general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.

**Comment by pawelfus** [comment]
@amargautam - please check #9938 ticket.

@sebastianbochan any news about the issue? Do you think it will get into the next release?

**Comment by amargautam** [comment]
@sebastianbochan - Sorry about that. I am new here. Will try to follow the guidelines.

@pawelfus - Thank you so much for directing me to the right issue. I will keep a watch.
