### ISSUE TITLE
Bubble Series fillOpacity not working

### ISSUE THREAD

**Issue by jamesapowers** [highcharts/highcharts#10190]
#### Expected behaviour
https://github.com/highcharts/highcharts/blob/f69a4f2fe/js/parts-more/BubbleSeries.js#L89-#L91

marker opacity to change to when adjusting marker.fillOpacity 

#### Actual behaviour
Opacity does not change

#### Live demo with steps to reproduce
https://jsfiddle.net/652usxpL/1/

#### Product version
Highcharts 5.0.19

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @jamesapowers,
The `fillOpacity` option is dedicated to bubble series, not circle marker in line series.

**Bubble series example:**
- https://jsfiddle.net/BlackLabel/5oqmpL24/

If you would like to adapt line series' marker, set `rgba` color definition. Be aware of visible line in background.

**Demo:**
- https://jsfiddle.net/BlackLabel/er6a1wjn/4/

**Comment by jamesapowers** [comment]
Cool, Thanks! Sorry for the misunderstanding
