### ISSUE TITLE
plotOptions.vbp.params not working

### ISSUE THREAD

**Issue by amargautam** [highcharts/highcharts#10196]
#### Expected behaviour
The volume by price indicator should work on for following customized values -

plotOptions.vbp.params

```
plotOptions: {
      vbp: {
        params: {
          ranges: 36
        }
      },
    }
```

#### Actual behaviour
Volume by profile is not picking up plotOptions.vbp.params

#### Live demo with steps to reproduce
https://jsfiddle.net/amargautam/eudxypao/15/

#### Product version
Highstock v7.0.3

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @amargautam 

Thanks for reporting. I'll fix this.

**Workaround:**
Use `Highcharts.setOptions()` instead of chart config: https://jsfiddle.net/BlackLabel/4sb67pd8/

```javascript
Highcharts.setOptions({
  plotOptions: {
    vbp: {
      params: {
        ranges: 36,
        volumeSeriesID: "aapl-volume"
      }
    },
  }
});
```
