### ISSUE TITLE
Right click triggers event selection

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#1019]
From samples: http://jsfiddle.net/gh/get/jquery/1.7.1/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/zoomtype-x/
Using right click to context menu we can zoom in chart, which isn't expected.

**Comment by vadimpopa** [comment]
Just wondering how come this hasn't been fixed up to now, we have the same issue on 5.x and the Fiddle runs on latest and still has the issue ?

**Comment by KacperMadej** [comment]
@TorsteinHonsi Are there any known limitations preventing the workaround to be included by default in core? or to make it settable from options in case of backwards compatibility issues?
