### ISSUE TITLE
Using `showInNavigator` option and adding points after removing a series causes an error

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#10193]
#### Expected behaviour

The chart should work similar like with `update` method: 
http://jsfiddle.net/BlackLabel/5oz1fpxs/

#### Actual behaviour

Using `addPoint` or `setData` methods causes this error:
`Uncaught TypeError: Cannot read property '0' of undefined`

#### Live demo with steps to reproduce
1. Opne jsfiddle: http://jsfiddle.net/BlackLabel/qv2kozLu/
2. Click on the `Add series` button
3. Click on the `Remove first series` button
4. Click on the `Add a point`

#### Product version
Highcharts 7.0.3

#### Affected browser(s)
All

**Comment by RossGraeber** [comment]
We are having this same issue with our HighStock chart.  We have a chart that updates periodically that a user can add or remove series from. This breaks the charts ability to add new points dynamically after a user removes a series from our graph.

**Comment by sebastianbochan** [comment]
**Workaround:**
Add extra series to the navigator, instead of using `showInNavigator`.

Demo:
- http://jsfiddle.net/BlackLabel/kumt493q/

**Comment by pawelfus** [comment]
**Workaround:**
Demo: 
http://jsfiddle.net/BlackLabel/qv2kozLu/22/

```javascript
(function(H) {
  H.wrap(H.Navigator.prototype, 'addBaseSeriesEvents', function(p) {
    var nav = this;

    p.apply(nav, Array.prototype.slice.call(arguments, 1));

    (nav.baseSeries || []).forEach(function(series) {
      H.addEvent(series, 'remove', function() {
        H.erase(nav.baseSeries, series);
      });
    });
  });
})(Highcharts);
```
