### ISSUE TITLE
Highstock stochastic indicator should open in its own pane

### ISSUE THREAD

**Issue by amargautam** [highcharts/highcharts#10201]
#### Expected behaviour
When we set stochastic indicator on price series in candlesticks charts, it should open in its own y-axis and pane like other indicators e.g. rsi and cci. 

#### Actual behaviour
As of now it opens in the same pane as the candlesticks and pushes the candlesticks up.

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/stock-tools-gui

#### Product version
Highstock v7.0.3

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @amargautam,
Thank you for reporting about the problem.

**Comment by amargautam** [comment]
Hi @sebastianbochan 

Can we please put this in v7.0.4?

**Comment by sebastianbochan** [comment]
Hi @amargautam,
The fix is already committed and will be the part of 7.0.4 release.
