### ISSUE TITLE
bug with series hiding when using legend in gantt chart

### ISSUE THREAD

**Issue by dunkoh** [highcharts/highcharts#10211]
#### Expected behaviour
tasks linked to series should hide and points/bars should shift up.

#### Actual behaviour
it removes the labels on the left but doesn’t shift up the bars on the right. on activating the series again the first task is missing collapse icon and some of the other hierarchy is screwy.

#### Live demo with steps to reproduce
https://jsfiddle.net/dunkoh/y7d24whq/

Steps to recreate:
1. load the chart, click on the first series in the legend, it removes the labels on the left but doesn’t shift up the bars on the right
2. click the first series again, and the items come back, but the collapse icon is missing now - and some of the hierarchy seems screwy on the left. If you hide all 3 series, and add them back in order it displays them properly.

I have found a similar bug using one of your demo jsfiddle’s (not quite the same but similar)

https://jsfiddle.net/dunkoh/2a5p8jgr/

If you click the 2nd series, it will hide correctly, and clicking again shows again correctly.

If you click the first series, it hides it, but shows the 2nd series labels but not their points. clicking the first series again shows the first series but no longer shows the 2nd series at all

#### Product version
Highcharts 7.0.3

#### Affected browser(s)
N/A

**Comment by pawelfus** [comment]
Hi @dunkoh 

Thanks for reporting the issue. I agree, it looks buggy.

@jon-a-nygaard - could you take a look?

**Comment by 888ba8** [comment]
Is there any update on this? See also https://www.highcharts.com/forum/viewtopic.php?f=19&t=45651 Where is a good on-line example of a working legend for a Gannt highchart?

**Comment by PaulDalek** [comment]
Hi @888ba8 

Thank you for contacting us. This issue is already fixed in the newest version. As for the example, there is one in the first comment of this thread (look below). Also, next time please try to reach out to us through the available [support channels](https://www.highcharts.com/blog/support/) first. Thanks!

**Demo**
https://jsfiddle.net/BlackLabel/cmkv03n5/
