### ISSUE TITLE
Stocktools full screen loads wrong chart

### ISSUE THREAD

**Issue by maxcramer** [highcharts/highcharts#10214]
#### Expected behaviour
Expected to load the correct chart to full screen, when displaying more than one chart (I am displaying TWO)

#### Actual behaviour
I have TWO charts on the page.  When I click on the full screen button on one chart, the other goes full screen. 

#### Live demo with steps to reproduce
https://codepen.io/anon/pen/rRaWBe?&editable=true

#### Product version
Highcharts / highstock 7.0.3

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @maxcramer,
Thank you for reporting.

Updated demo:
- https://codepen.io/anon/pen/droYBy
