### ISSUE TITLE
Percentage height in responsive chart options not applying on initial chart load

### ISSUE THREAD

**Issue by scarroll142** [highcharts/highcharts#10213]
StackOverflow response that directed me here - https://stackoverflow.com/questions/54872764/percentage-height-responsive-highchart-option-not-applied-on-chart-load

#### Expected behaviour
When the condition for a responsive chart is met, all of the responsive rules are applied.

#### Actual behaviour
All the conditions were applied except height because it was a percentage.

#### Live demo with steps to reproduce
https://jsfiddle.net/scarroll142/b8ogxh9u/19/

Simply loading the fiddle will show that some the responsive options are applied, but not the height. When the chart is resized or reflowed, the chart then applies the percentage height. If a height in pixels is set instead it applies immediately. Presumably percentage width would also be affected by this.

#### Product version
Current Version 7.0.2

#### Affected browser(s)
All

#### Proposed Fix
The problem seems to be at lines 600 and 601 in Dynamics.js. This is part of the update function that is called within Responsive.js. At these lines both height and width are checked with isNumber() which prevents percentages from being accepted. A simple change to this condition would allow setSize() to be called and correctly resize the chart.

**Comment by pawelfus** [comment]
Hi @scarroll142 

Thanks for reporting the issue! And for the details, you are right - we should consider percentage values too.

@TorsteinHonsi FYI

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: https://jsfiddle.net/highcharts/5rw7zga6/2/
