### ISSUE TITLE
Series animation is not applied in update with the same gradient color

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#10216]
#### Expected behaviour
The series animation should be applied, as in a situation with the same color:
http://jsfiddle.net/BlackLabel/zbp9aryw/

#### Live demo with steps to reproduce
1. Open jsfiddle: http://jsfiddle.net/BlackLabel/t59Lvuaw/
2. Click on the 'Update' button

This issue is problematic with the use of the Highcharts wrappers.

#### Product version
Highcharts v7.0.3

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
It's basically the same as #10010. When we're running update with other options than `data` or `name`, Highcharts is unsure what to do with the points, freaks out and destroys and rebuilds all.

**Comment by TorsteinHonsi** [comment]
Demo with the new soft-update feature branch: http://jsfiddle.net/highcharts/otL0w76j/2/
