### ISSUE TITLE
Additional bin appears in histogram series

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#10225]
#### Expected behaviour
There should be always the same amount of bins on the chart as the `binsNumber` value set by user.

#### Actual behaviour
Additional bin is sometimes added on the graph.

#### Live demo with steps to reproduce
Live example: https://jsfiddle.net/BlackLabel/jLhdovtb/
Regardless the `binsNumber` is set equal to `7`, there are 8 bins on the graph.

_Internal Note:_
_The last bin start value is almost equal (the difference is on 11th decimal place) to the max data value of series. It's caused by to small precision of float correction._

**Comment by TorsteinHonsi** [comment]
@Denyllon After this fix, the bins at http://utils.highcharts.local/samples/#test/highcharts/demo/histogram are differently computed from before. Can you confirm that the new one is correct?

![Skjermbilde 2019-03-27 kl  09 16 08](https://user-images.githubusercontent.com/227836/55060131-0cee9680-5071-11e9-9e15-c64750f89749.png)

**Comment by Denyllon** [comment]
Confirm. The number of 13 bins is calculated by the algorithm on both cases, but on the left side is one less than required.
