### ISSUE TITLE
setOptions ignores legend option for stockChart

### ISSUE THREAD

**Issue by slavede** [highcharts/highcharts#10228]
#### Expected behaviour
I expect that setOptions applies legend options to all charts when using stockChart

#### Actual behaviour
setOptions in case of highstock ignores global legend options. It works fine in Highcharts

#### Live demo with steps to reproduce

http://jsfiddle.net/uh024xrg/

#### Product version

Highstock JS v7.0.3 (2019-02-06)

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @slavede,
Thank you for reporting. Im closing this issue due to duplicate of the https://github.com/highcharts/highcharts/issues/8357 ticket.
