### ISSUE TITLE
Specifiying yAxis.min doesn't work if data is only made of min values.

### ISSUE THREAD

**Issue by TheGreatYamcha** [highcharts/highcharts#10226]
#### Expected behaviour
the yAxis should start from 0 (at the bottom of the yAxis) and the line should be at the bottom too.
I've tried fiddling with floor, softMin, minPadding, etc. Didn't help.
 
#### Actual behaviour
0 is at the middle of the yAxis.

#### Live demo with steps to reproduce
https://jsfiddle.net/87L4xeyp/

#### Product version
Latest

#### Affected browser(s)
Chrome 71

**Comment by sebastianbochan** [comment]
Hi @TheGreatYamcha,
Thank you for reporting. By default calculation of ticks positions is based on data points. When your points values are the same, then we set a single tick only (positioned in center). You can control ticks by [tickPositioner](https://api.highcharts.com/highcharts/yAxis.tickPositioner) [tickPositions](https://api.highcharts.com/highcharts/yAxis.tickPositions), min/max values.

**The solution 1:** 
Use tickPositions / tickPositioner

**Demo:**
- https://jsfiddle.net/BlackLabel/fm40ngst/

**The solution 2:** 
Set the `max` and `tickInterval` parameters as 1.

**Demo:**
- https://jsfiddle.net/BlackLabel/k7nxo460/

**Comment by TheGreatYamcha** [comment]
But shouldn't the default tick positions respect the yAxis.min value?

**Comment by TheGreatYamcha** [comment]
the other problem is in solution 2, this doesn't work with "softMax" (only works with "max"). So I have to explicitly go through the data and see if they are all the same, then apply special rules in that case.

**Comment by pawelfus** [comment]
I think the best solution here is to use [`tickPositioner`](https://api.highcharts.com/highstock/yAxis.tickPositioner): https://jsfiddle.net/BlackLabel/rmL6hwd1/4/ - we can simply add another tick (I don't know, neither Highcharts, what is the correct range, so I placed there `+1`):
```javascript
        tickPositioner: function (min, max) {
            if (this.tickPositions.length === 1) {
              this.tickPositions.push(
              	this.tickPositions[0] + 1 // define the range in this case
              );
            }
            return this.tickPositions;
        },
```

**Comment by TheGreatYamcha** [comment]
@pawelfus that works. Although I still believe this is a bug and the default tick positions should take 
yAxis.min and max into account. This is also how flot and excel work.
![image](https://user-images.githubusercontent.com/10838193/53657180-423acc80-3c0a-11e9-853d-f6e9f4a1970b.png)

**Comment by KacperMadej** [comment]
Another workaround could be to set `tickAmount` - https://jsfiddle.net/BlackLabel/5ywev2xs/

**Comment by TorsteinHonsi** [comment]
> Although I still believe this is a bug and the default tick positions should take
yAxis.min and max into account. 

In your original demo you set `yAxis.min` only. Highcharts does actually take it into account, but since both `yAxis.min` and all the data points are the same value, we don't assume that you are plotting something between 0 and 1 like Excel does. We know one thing about your axis, which is that you want to plot the number 0, so that's what we do. 

There's one thing that looks buggy though - I would expect `minRange` to give the same result as Excel does above: https://jsfiddle.net/highcharts/bvufxos5/

**Comment by KacperMadej** [comment]
> There's one thing that looks buggy though

Reopening and labeling as a bug.

**Comment by TorsteinHonsi** [comment]
With the fix applied, we can now set `minRange` and the Y axis will show 0-1: https://jsfiddle.net/highcharts/9tj780k1/. Unlike Excel, we don't assume a specific range (for example if we're dealing with population, decimals make no sense), so `minRange` must be specified.

When setting the `max` but not the `min`, the `minRange` will be added to the negative area: https://jsfiddle.net/highcharts/9tj780k1/2/.

When setting neither `min` nor `max`, the points axis will extend in both directions: https://jsfiddle.net/highcharts/9tj780k1/4/.

**Comment by KacperMadej** [comment]
@TorsteinHonsi 
Looks like when `min` and `minRange` are used the yAxis scale is forced to show the `minRange` starting from `min`. Demo: https://jsfiddle.net/BlackLabel/qjc6n2bo/

The same for `max` - https://jsfiddle.net/BlackLabel/qjc6n2bo/1/

**Comment by TorsteinHonsi** [comment]
Yes, that's the intension. If I set `min: 0` and `minRange: 10`, I want the Y axis to go from 0 to 10, not -5 to 5, right?

**Comment by KacperMadej** [comment]
I would expect the minRange to be only [`the minimum range to display on this axis`](https://github.com/highcharts/highcharts/issues/10226). So if data suggests that the range should be bigger, and min nor max blocks it, then it should be bigger. With all data at 0, min set to -10, minRange set to 1, I would expect for the axis range to start at -10 and end at 0.

**Comment by TorsteinHonsi** [comment]
You're right. I missed the point.

**Comment by TheGreatYamcha** [comment]
I think if softMin = 0 and softMax = 1, then it should draw the axis between 0 and 1 (like Excel). That's currently not the case and I don't understand why. https://jsfiddle.net/L0yto6aq/

**Comment by KacperMadej** [comment]
@TheGreatYamcha 
The fixed code is not yet published. You could test it using github based link like in this demo: https://jsfiddle.net/BlackLabel/w8Lvt37q/

**Comment by TheGreatYamcha** [comment]
excellent. Thank you.
