### ISSUE TITLE
Freeform drawing doesn't work with Android 2.x

### ISSUE THREAD

**Issue by joelhegg** [highcharts/highcharts#1023]
I'm having trouble getting our code that does freeform drawing to work in Android 2.x, and freeform drawing was not one of the compatibility issues I saw listed at http://www.highcharts.com/documentation/compatibility

Here's one example based on one from your documentation: http://jsfiddle.net/RThtx/. The "Max" bubble shows up fine on a desktop browser, but on Android 2.x it positioned incorrectly and there's no text.

Here's a simpler example using just the renderer: http://jsfiddle.net/gJWTe/. "Hello world" shows up on a desktop browser but not on Android 2.x.

Finally, here's one showing an image that renders on a desktop browser but not Android 2.x: http://jsfiddle.net/nAYyR/.

**Comment by cvasseng** [comment]
Hi! We're doing a bit of spring cleaning, and closing old issues. If you're still experiencing issues with this, please feel free to open a new issue! Thanks!
