### ISSUE TITLE
CSS Classes still gets applied with styledMode:false

### ISSUE THREAD

**Issue by DronkWynie** [highcharts/highcharts#10235]
#### Expected behaviour
When Styled Modes is set to false, CSS Classes should not be applied.

#### Actual behaviour
Currently when styled mode is set to false, css classes are still being applied, and it styles the chart with confusing colors

#### Live demo with steps to reproduce
In below example i have 3 graphs showing the issue.

Change `var styledMode = false;` to  `var styledMode = true;` and run again to view differences.

https://jsfiddle.net/1L54q9za/2/

#### Product version

Highcharts  -  7.0.3

#### Affected browser(s)
All

**Comment by remiuz** [comment]
I've quite the same issue. 

I use x-range serie where I set a color for each range. I set  styleMode to false on the chart object but Highcharts continues to apply colors from its CSS instead of using the color attribute value on data.

Example here : http://jsfiddle.net/xz8bw1f6/
The black color should be purple (#b868c7). If i remove the highcharts.css import, it works perfectly.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! 

I don't think this is a bug, rather we should discuss how to meet your requirement.

> When Styled Modes is set to false, CSS Classes should not be applied.

Highcharts will apply class names to its element regardless of styled mode. The difference is that when styled mode is true, no _presentational attributes_ are applied.

> Highcharts continues to apply colors from its CSS instead of using the color attribute value on data

That's how SVG/CSS works. If an element has an attribute setting and the same setting is applied in CSS, the CSS takes precedence. See https://jsfiddle.net/highcharts/0c49jbkd/

So the question is how to achieve what you want. In addition to toggling the styled mode, you could consider enabling and disabling the style sheet too.

**Comment by remiuz** [comment]
Thank you for your answer @TorsteinHonsi 

The issue is that we develop an Ember app. So, we use ember-highcharts wrapper (https://github.com/ahmadsoe/ember-highcharts) and it seems that we cannot have to control to disable the default Highcharts CSS.

**Comment by remiuz** [comment]
Another problem is that I need to check that the other charts that we use in our application doesn't need this default Highcharts CSS. Because if I manage to disable the import of the CSS, it can cause some other issues in other charts.

**Comment by remiuz** [comment]
I found a fix that resolve the problem in my case. I set a colorIndex of 9999 for each data of this chart. So it cannot find a CSS rule for that color index and it uses the correct color (set by the color attribute).

**Comment by DronkWynie** [comment]
> Highcharts will apply class names to its element regardless of styled mode. The difference is that when styled mode is true, no _presentational attributes_ are applied

Does the `.highcharts-color-{n}`  classify as an **_presentational attributes_**?

In my case this is the class causing the issue

**Comment by DronkWynie** [comment]
I just realized how it works. 

My workaround: 
Chart Config:
`  chart: {
    styledMode: true,
    className: 'styled-mode'
  },`

CustomCSS:
`.style-mode .highcharts-color-0 {
  fill: #ff00FF;
  stroke: #ff00FF;
}`

IE:
https://jsfiddle.net/q41de8xs/

@remiuz  Maybe this can solve your problem too>?

**Comment by TorsteinHonsi** [comment]
> Is it possible to implement similar approach for styled-mode? 

I'm not quite sure how that would work - all Highcharts related CSS classes are prefixed `.highcharts-`, so I think the best approach is to do what you did, to wrap it all in a class name that is set higher up.
