### ISSUE TITLE
honeycomb fixed tile size

### ISSUE THREAD

**Issue by mhauschild** [highcharts/highcharts#10238]
#### Expected behaviour:
Keep the tile size while having just a view number of data points.
For instance https://github.com/d3/d3-hexbin even if you take lots of data points out of the chart the tile size will stay the same.
Is there any flag I can set to keep the tile size constant?

#### Actual behaviour
If I have just 3 datapoints left in https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/honeycomb-usa/
and those are close together I get this result 
![image](https://user-images.githubusercontent.com/16018113/53630207-d6f3f900-3c0f-11e9-9fa7-a1f9f6c08e3e.png)
which is very poor.

Thanks alot for your feedback. We would be happy to produce all our charts with highcharts instead of using d3 for this issue!

#### Live demo with steps to reproduce
https://jsfiddle.net/2zenxtq1/

#### Product version
v606 - 5.2.2018

#### Affected browser(s)
Chrome

**Comment by oysteinmoseng** [comment]
Workaround: Set axis min/max explicitly https://jsfiddle.net/x54ky0Lu/

**Comment by stappi** [comment]
> 
> 
> Workaround: Set axis min/max explicitly https://jsfiddle.net/x54ky0Lu/

Thanks a lot for your response. I tried that fix and it worked in the beginning. In our case we need a different Axis labeling. In your case the labeling and ticksize is from 0 to 7. Since the ticksize is perfect to keep the tiles in shape we now want to have a different labeling we putted another axis for x, see here: http://jsfiddle.net/x56jyqcs/3/

Now we want to have also another labeling for the yAxis so we putted an extra yAxis here: http://jsfiddle.net/x56jyqcs/4/ this does not seem to work anymore. Is there another way to identify the labeling?

Thanks alot in advance for your support!

**Comment by KacperMadej** [comment]
@stappi 
Adding a dummy series that will have the yAxis that you want to show set in options will make the second yAxis visible. Demo: http://jsfiddle.net/BlackLabel/9h2u6g1e/

**Comment by stappi** [comment]
> 
> 
> @stappi
> Adding a dummy series that will have the yAxis that you want to show set in options will make the second yAxis visible. Demo: http://jsfiddle.net/BlackLabel/9h2u6g1e/

Thanks a lot for your response. Is there a way, to set a logarithmic axis, like this example: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-log-axis/
Here is my current chart: http://jsfiddle.net/92ugyLr8/

Thanks alot in advance for your support!

**Comment by KacperMadej** [comment]
@stappi 
This is a question that should be asked on a technical support channel - https://www.highcharts.com/blog/support/
We are using GitHub issues for bug reports.

P.S. To set axis type you could use option [`type`](https://api.highcharts.com/highcharts/xAxis.type). Support for negative values on a logarithmic axis is linked in docs and in this demo: http://jsfiddle.net/BlackLabel/c7zpq2mb/
