### ISSUE TITLE
Swatch legend is inconsistent among the other charts

### ISSUE THREAD

**Issue by karolinakuzniewicz** [highcharts/highcharts#10232]
#### Expected behaviour
Legend can be hidden by default but after setting `series[i].showInLegend: true`, the legend should look the same and acts the same way as in other charts, eg. pie, line, bubble, etc. The colours should be the same as the series colours, the markers should be as big as marker in other charts.

#### Actual behaviour
Legend is hidden by default but after setting `series[i].showInLegend: true`, the legend is uncolorized/gray and the marker is a line instead of square. If the `series[i].marker` is set to `square` the `<rect>` in html is smaller (8 pixels) than other rects in legend (12 pixels).

#### Live demo with steps to reproduce
https://jsfiddle.net/zxvuwn5q/1/

#### Product version
Highcharts 7.0.03

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @karolinakuzniewicz 

Thanks for reporting!

**Workaround:**
Borrow from column-type series rendering legend item: http://jsfiddle.net/BlackLabel/o1p9dq52/7/
```javascript
Highcharts.seriesTypes.solidgauge.prototype.drawLegendSymbol = function() {
  this.color = this.userOptions.color;

  return Highcharts.LegendSymbolMixin.drawRectangle.apply(this, arguments);
};
```

**Comment by karolinakuzniewicz** [comment]
lack of types:
-  `seriesTypes`: Property 'seriesTypes' does not exist on type 'typeof import("../node_modules/highcharts/highcharts")'. 
- `LegendSymbolMixin`: Property 'LegendSymbolMixin' does not exist on type 'typeof import("../node_modules/highcharts/highcharts")'. 
need to cast to `any` to avoid TS errors.

**Comment by pawelfus** [comment]
Hi @karolinakuzniewicz  - That's correct, workaround uses internal methods, not available in TS files.

Just realized that gray comes from `colorByPoint` option, which by default is set to true: [docs](https://api.highcharts.com/highcharts/series.solidgauge.colorByPoint). 

Setting this to `false` simplifies the workaround to: https://jsfiddle.net/BlackLabel/bcqtrj8u/2/
```javascript
Highcharts.seriesTypes.solidgauge.prototype.drawLegendSymbol = Highcharts.LegendSymbolMixin.drawRectangle;
```

After the fix, please don't forget to set `colorByPoint` to false - I won't change default value for API options.
