### ISSUE TITLE
Stacked area charts break when using x-axis breaks

### ISSUE THREAD

**Issue by meibegger** [highcharts/highcharts#10237]
#### Expected behaviour
The area and lines should be drawn continuously

#### Actual behaviour
There are drawing errors

#### Live demo with steps to reproduce
https://jsfiddle.net/ha8kwqpz/3/

#### Product version
Current (7.0.3)

#### Affected browser(s)
I guess all - but at least latest Firefox and Chrome on Mac

**Comment by pawelfus** [comment]
Hi @meibegger 

Thank you for reporting the issue.

Simplified demo: https://jsfiddle.net/BlackLabel/wqhxat3g/5/ - note that issue happens only when point falls into the break. Having points on edges works fine: https://jsfiddle.net/BlackLabel/wqhxat3g/6/
