### ISSUE TITLE
Recalculate custom indicator values upon data grouping

### ISSUE THREAD

**Issue by pathvine** [highcharts/highcharts#10242]
#### Expected behaviour
On Highstock, I am looking for the ability to recalculate custom indicator values upon data grouping. Currently approximation function doesn't provide this ability. I am raising this question because the resulting points from this indicator cannot be grouped together; they require recalculation for the entire series altogether.

#### Actual behaviour
I currently can't find any way to do this in the documentation or on stackoverflow/online.

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @pathvine 

For technical support please see https://www.highcharts.com/blog/support/

GitHub issues are used as bug tracker.

P.S.
You could create a custom indicator (https://www.highcharts.com/docs/stock/custom-technical-indicators) that will check if data of the base series is grouped in `getValues`. [`dataGrouping.enabled`](https://api.highcharts.com/highstock/series.area.dataGrouping.enabled) could be set to `false` for an indicator series preventing it from grouping points. You might get more info and more help when contacting technical support about this case - you could add more info and a live demo, to get better suggestions.
