### ISSUE TITLE
Boost enabled zoom y axis min issue

### ISSUE THREAD

**Issue by meriahoneil** [highcharts/highcharts#10246]
#### Expected behaviour
Zooming in should exclude data outside of zoomed range

#### Actual behaviour
Data outside of zoomed y axis min still visible when boost enabled

#### Live demo with steps to reproduce
https://jsfiddle.net/efocv2r8/
Zoom in on Tokyo line (such that you exclude the other line). Note that no matter how zoomed, other line still visible

#### Product version
Current (7.0.3)

**Comment by sebastianbochan** [comment]
Hi @meriahoneil,
Thank you for reporting about the problem.

**Internal note**
It looks like the `minRange` also does not solve the problem:
- https://jsfiddle.net/BlackLabel/qywaj6xh/

FYI @cvasseng

**Comment by cvasseng** [comment]
This has now been fixed in de832d5.

Preview of fix: https://jsfiddle.net/4dkcv92p/

Pull request has been created (https://github.com/highcharts/highcharts/pull/10254), and will be part of the next release.

Thanks again for reporting!

**Comment by meriahoneil** [comment]
Great, thanks for the quick fix! Will this be in v 6 as well?

**Comment by pawelfus** [comment]
Hi @meriahoneil 

Fix will be part of v7.0.4+ releases. You can apply fix to older version of Highcharts locally: de832d59683736262a0a580630415b2dc2d5a18e
