### ISSUE TITLE
Axis labels settings included in 'exporting.chartOptions' are not respected while exporting.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#10241]
#### Expected behaviour
In this case values of `color` and `reserveSpace` properties should be applied on exported chart.

#### Actual behaviour
Options set within `exporting.chartOptions.xAxis` (and also yAxis) are not applied on exported chart.

#### Live demo with steps to reproduce
Live example: https://jsfiddle.net/BlackLabel/f5cn6ea9/
Open the example above, and export the chart to see the options are not applied

#### Product version
Noticeable from v7.0.0
On v6.2.0 looks like everything is working fine, but after 1ae61e6d0 it breaks.

**Comment by sebastianbochan** [comment]
**Workaround:**
Use array of axis instead of the single object.

```
xAxis: [{
        labels: {
          reserveSpace: true,
          style: {
          	color: 'red'
          }
        }
}]
```

Demo:
- https://jsfiddle.net/BlackLabel/b6pm4Lvy/

**Comment by Denyllon** [comment]
Using above workaround resolves the issue, but not entirely, because the axis type is no longer set to `category`, and its labels are presented as numbers. Additionally, setting the `type` or even `categories` again is needed:

```
xAxis: [{
        categories: ['Label one', 'Label two', 'Label three'],
        labels: {
          reserveSpace: true,
          style: {
          	color: 'red'
          }
        }
}]
```
Live example: https://jsfiddle.net/BlackLabel/nt8ucqvh/

**Comment by LaniMoo** [comment]
> Using above workaround resolves the issue, but not entirely, because if the axis type was set to 'category' before exporting, then on exported images is no longer set as before, and its labels are presented as numbers. Additionally, setting the `type` or even `categories` again is needed

I ran into this same issue too with @sebastianbochan's workaround since my x-axis type is also `category`. @Denyllon's suggested workaround for the workaround to set `type` as `'category'` again fixed the labels for me.

Also I think the issue of chart options not getting overwritten with export options applies to all chart objects that may potentially be an array, such as series. Example:

https://jsfiddle.net/lanimelrok/etv85pjy/

**Comment by Denyllon** [comment]
I suggest to open the new issue with more specific description and refer it to this one.

**Comment by pawelfus** [comment]
@LaniMoo , @Denyllon 

This is not a bug. Options that are set in `series[index]` always have higher priority than `plotOptions.series`. This is correct way to change dataLabels: https://jsfiddle.net/BlackLabel/rsLcvm45/1/

**Comment by andi1984** [comment]
> > Using above workaround resolves the issue, but not entirely, because if the axis type was set to 'category' before exporting, then on exported images is no longer set as before, and its labels are presented as numbers. Additionally, setting the `type` or even `categories` again is needed
> 
> I ran into this same issue too with @sebastianbochan's workaround since my x-axis type is also `category`. @Denyllon's suggested workaround for the workaround to set `type` as `'category'` again fixed the labels for me.
> 
> Also I think the issue of chart options not getting overwritten with export options applies to all chart objects that may potentially be an array, such as series. Example:
> 
> https://jsfiddle.net/lanimelrok/etv85pjy/
> 
> But let me know if you'd like me to log it as a separate issue. Thanks!

@LaniMoo @Denyllon Looks to me that this is not only the case for these few, but also the axis labels style etc. I have to set there again. Would be good to have a ticket for that. It is a bit unclear for me why this changed. In v6 it seems to me that inside exporting chartOptions settings got inhertited from the non-exporting chartOptions.

**Comment by pawelfus** [comment]
@andi1984 - I don't understand, ticket for what? This bug describes issue with `xAxis`/`yAxis` and options set there (issue with `series` is not a bug, as priority is the same as in general config). Did I miss something? Thanks!
