### ISSUE TITLE
DataLabel disappearing when value is too small and inside is set to true 

### ISSUE THREAD

**Issue by scarroll142** [highcharts/highcharts#10245]
#### Expected behaviour
Setting the inside option to true will cause datalabels to be but inside bars when possible.

#### Actual behaviour
If the value of the data point is extremely small relative to the other data, then the data label is not shown.

#### Live demo with steps to reproduce
https://jsfiddle.net/scarroll142/b8ogxh9u/58/

Simply use the toggle button to switch between having the "inside" option set to true and false. Only when inside is set to true and the value is very small, does the data label disappear. If you inspect the chart you can find that the label is being placed offscreen. 

#### Product version
Current Version, 7.0.3

#### Affected browser(s)
At least chrome, edge, and firefox

**Comment by sebastianbochan** [comment]
Hi @scarroll142,
Thank you for reporting. 

**Workaround**
Set the [crop](https://api.highcharts.com/highcharts/series.column.dataLabels.crop) param and adapt y value.

Demo:
- https://jsfiddle.net/BlackLabel/fy35Lnwx/

**Internal note**
In case of setting crop and justify (allow value), all labels should be at the same level (visible). What do you think?

**Comment by TorsteinHonsi** [comment]
> In case of setting crop and justify (allow value), all labels should be at the same level (visible). What do you think?

I think it should work like https://jsfiddle.net/BlackLabel/fy35Lnwx/, so the numbers don't cover the axis line

**Comment by TorsteinHonsi** [comment]
I'm reverting this, it broke http://utils.highcharts.local/samples/#test/highcharts/demo/heatmap. Sorry, have no time to dig further...
