### ISSUE TITLE
TypeScript: RangeSelectorButtonsOptions.type missing 'hour'

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#10248]
#### Behaviour
RangeSelectorButtonsOptions.type missing 'hour'

#### There is:

```ts
    /**
     * (Highstock) Defined the time span for the button. Can be one of
     * `millisecond`, `second`, `minute`, `hour`, `day`, `week`, `month`, `ytd`,
     * `all`.
     *
     * @see https://api.highcharts.com/highstock/rangeSelector.buttons.type
     */
    type?: ("all"|"day"|"millisecond"|"minute"|"month"|"second"|"week"|"ytd");
```

so `type` is missing `hour`.

#### Product version
7.0.3

**Comment by KacperMadej** [comment]
The related `validvalue` is incomplete:

https://github.com/highcharts/highcharts/blob/30377d0a25a60c2f3180348d137e7bd5f65c23c5/js/parts/RangeSelector.js#L232-L239

**Comment by KacperMadej** [comment]
Also, "year" options should be added to both TS defs and docs. It works fine and is presented in our API docs demos. E.g. https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/rangeselector/datagrouping/

**Comment by mcenkar** [comment]
Hi, what is expected release date for this? Apart from missing `year` we're also getting this:

```
error TS2322: Type 'string' is not assignable to type '"all" | "day" | "minute" | "month" | "second" | "week" | "millisecond" | "ytd"'.
```

so I need to do following:

```
        buttons: [
          {
            type: 'month' as 'month',
            count: 1,
            text: '1m',
          },
```

**Comment by bre1470** [comment]
The next update will contain the fix, but the release this week has been delayed to maybe next week.

Your mentioned literal type detection is a problem in some older TypeScript versions and vanishes with an update.
