### ISSUE TITLE
[bug] Highcharts pie chart duplicates on update()

### ISSUE THREAD

**Issue by MisterTicot** [highcharts/highcharts#10249]
This can easily demonstrated with the [responsive demo chart](http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/responsive/)  displayed as a pie chart: http://jsfiddle.net/gdb9q2ps/

The problem happens because update() doesn't erase the previous iteration of the pie chart as it should.

I reproduced that bug with Highcharts 6 & 7 under Chromium 71.0.3578.98 & Firefox 65.0.1 running on Ubuntu 18.10 64bits.

_Note:_ the responsive feature makes use of the update() method, and the bug comes from the update() method itself.

**Comment by pawelfus** [comment]
Hi @MisterTicot 

Thanks for reporting the issue. Your demo has duplicated labels (and slices) because you have multiple series, see: http://jsfiddle.net/BlackLabel/j3c82oab/1/ - I've just removed all other code except multiple series. Working chart with responsive rules, but without multi series: http://jsfiddle.net/BlackLabel/j3c82oab/4/

**Comment by MisterTicot** [comment]
I can confirm that the error is related to the points I'm using in the serie data.

My serie data is an array of objects having a lot of properties. When I use objects trimmed down with only the relevant data instead, the pie chart doesn't duplicate anymore. Due to the large number of properties, I'm having difficulties to spot the culprit and to reproduce the situation.

**Comment by pawelfus** [comment]
Hi @MisterTicot 

Number of properties shouldn't be a problem. Maybe you have an array for `dataLabels` and you define multiple dataLabels per point?

**Comment by MisterTicot** [comment]
No I don't. I replaced series object by striped down ones and it's working fine now. I did not find the source of the functioning though. I you guy are interested I can make the unfixed interface & the source code available somewhere.

**Comment by pawelfus** [comment]
If you could create a live demo (so I can easily debug, without setting whole app) that would be great.

**Comment by MisterTicot** [comment]
Unfortunately I've been unable to create a reproduction of the bug. Anyway you can check it live [here − under the graph tab](https://test.equilibre.io/?address=GAWO2C52D57XBT7SQL6YB3XPHFLFD2J4Z5RN7HPFZSHXJMXH72HRXNV3#portfolio). If you reduce the window to trigger responsive display you'll see how it duplicates. If you continue to switch between modes you'll get a dozen of duplicates. Each chart point is logged into the web console.

The chart configuration is as follow:

```js
    this.chart = Highcharts.chart(this.container, {
      title: "",
      legend: { enabled: false },
      chart: {
        type: "pie",
        backgroundColor: "#fbfbfd"
      },
      tooltip: {
        style: { fontSize: "14px" },
        pointFormat: `
${__("Amount")}: {point.amount} {point.code}<br>
${__("Price")}: {point.price} ${global.currency}<br>
<b>${__("Value")}: {point.y} ${global.currency}</b>
`
      },
      colors: [
        "rgba(231,  76,  60, 0.8)",
        "rgba(230, 126,  34, 0.8)",
        "rgba(242, 202,  39, 0.8)",
        "rgba(46,  204, 112, 0.8)",
        "rgba(52,  152, 219, 0.8)",
        "rgba(155,  89, 182, 0.8)",

        "rgba(231,  76,  60, 0.6)",
        "rgba(230, 126,  34, 0.6)",
        "rgba(242, 202,  39, 0.6)",
        "rgba(46,  204, 112, 0.6)",
        "rgba(52,  152, 219, 0.6)",
        "rgba(155,  89, 182, 0.6)",

        "rgba(231,  76,  60, 0.4)",
        "rgba(230, 126,  34, 0.4)",
        "rgba(242, 202,  39, 0.4)",
        "rgba(46,  204, 112, 0.4)",
        "rgba(52,  152, 219, 0.4)",
        "rgba(155,  89, 182, 0.4)"
      ],

      plotOptions: {
        pie: {
          allowPointSelect: true,
          animation: false,
          cursor: "pointer",
          dataLabels: {
            style: { fontSize: "14px" },
            format: "{point.amount} {point.code}<br>({point.percentage:.0f}%)"
          },
          point: {
            events: {
              select: x => this.parent.select(x.target.options),
              legendItemClick: x => {
                this.parent.select(x.target.options)
                return false
              }
            }
          }
        }
      },

      series: [
        {
          name: __("Amount"),
          colorByPoint: true,
          ignoreHiddenPoint: true,
          data: this.parent.portfolio.assets
            .filter(asset => asset.value)
            .map(makeAssetPoint)
            .sort((a, b) => b.y - a.y)
        }
      ],
      credits: { enabled: false },

      responsive: {
        rules: [
          {
            condition: {
              maxWidth: 500
            },
            chartOptions: {
              legend: { enabled: true },
              plotOptions: {
                pie: {
                  showInLegend: true,
                  dataLabels: {
                    format: "{point.percentage:.0f}%",
                    distance: -20
                  }
                }
              }
            }
          }
        ]
      }
    })
  }
}
```

The function generating the points derive them from an Asset object:

```js
function makeAssetPoint (asset) {
  const assetPoint = Object.create(asset)
  assetPoint.y = Number(nice(asset.value, 2))
  assetPoint.niceAmount = nice(asset.amount)
  assetPoint.nicePrice = nice(asset.price)
  console.log(assetPoint)
  return assetPoint
}
```

The bug cease to happen if I create fresh objects instead:

```js
function makeAssetPoint (asset) {
  return {
    name: asset.name,
    code: asset.code,
    y: +nice(asset.value, 2),
    amount: nice(asset.amount),
    price: nice(asset.price),
    percentage: asset.percentage
  }
}
```

**Comment by pawelfus** [comment]
Thanks for the details and the demo. It looks like whatever `asset` is (a promise? that's what `asset.getInfo()` returns) - it complicates the process of rendering a point. In general, when we create `Point` class (aka `Slice` in Pie series), we copy all options from config to the Point class (so later you can use for example simple formats: `{point.niceAmount}`). In the `asset` class must be something that replaces/removes `dataLabels`/`dataLabel` properties.

PS: The longer app is open in the tab, the more charts you create - check `makePie` process. It's not related, just wanted to let you know :)

**Comment by MisterTicot** [comment]
`Asset` themselves are not Promises, but yeah `asset.getInfo()` is an asynchronous function. However Asset class extends a Projectable class that deals with events & tying properties together in such a way that changing one will update the others. Things such as:

```js
// value will get updated using each time amount or price changes.
Asset.define("value", ["amount", "price"], function () {
  return this.amount * this.value
})
```

I don't see how it could mess up though. There's no reason for it to alter properties that have not been defined that way. Maybe because values are actually enclosed by getters/setters? Or maybe because of something in \_\_proto__ that takes over an Highcharts function?

Other than that yes I destroy & re-make the chart each time data gets an update. I know: it's very wrong (^.^). I have no idea how you noticed?

**Comment by pawelfus** [comment]
It's hard to say, code is minified so it's not easy to debug. Access to `window.Highcharts` could help too. Do you think you can use source file (for highstock.src.js) or attach `highstock.js.map` for a day or two? A while ago I've tried getters/setters and those were fine for `series.data` points.

How I noticed? I added breakpoint in this line: `this.chart = Highcharts.chart(this.container, {`. Then waited for the update and you create chart several times :) It's not about recreating chart on data update (which is fine in some situations), but number of these recreations.

**Comment by MisterTicot** [comment]
@pawelfus I found the bug you mentioned about chart creation spamming. Thank  you for that. I'll create a better debugging ground for you this week or the next one.

**Comment by MisterTicot** [comment]
(Sorry for the delays)

**Comment by KacperMadej** [comment]
@MisterTicot Any updates?

**Comment by MisterTicot** [comment]
@pawelfus @KacperMadej 

I think I procrastinated this one beyond reason.

What matters to the issue is, at that point, I'm totally unable to reproduce this bug, and I can re-implement the original design without encountering any problem.

It could be related to some change I made into the software (it evolved a lot since then), but I'd rather guess that an update on your side fixed it as a collateral effect.

**Comment by pawelfus** [comment]
Ok, thanks for the info! Let me close the issue then.

**Comment by jonasarielberner** [comment]
I have the same issue when using on React

**Comment by sebastianbochan** [comment]
Hi @jonasarielberner,
Could you share your live demo on a sandbox?
