### ISSUE TITLE
Duplicate: Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by ruaneg** [highcharts/highcharts#10250]
#### Expected behaviour
Stacked Charts should appear correctly

#### Actual behaviour
Console error 
```
highcharts.js:320 Uncaught TypeError: Cannot read property '0' of null
    at p.translate (VM99 highcharts.js:320)
    at p.translate (VM99 highcharts.js:375)
    at VM99 highcharts.js:281
```

#### Live demo with steps to reproduce
I seem to be running into the same error at the closed ticket, at the same location.
Closed tickets:
https://github.com/highcharts/highcharts/issues/10160
PR with comments stating issue is not resolved:
https://github.com/highcharts/highcharts/pull/10227

I've tried the fix in the _bugfix/10160-stacking-null-point_ PR, but its not resolving the issue.
https://github.com/highcharts/highcharts/commit/4373a2702e04fad53a22b75367fcfd185a1e241b

This is a replication of the issue running on our current version 6.0.7:
https://jsfiddle.net/ruaneg/65eronp3/22/

The working data objects in the data array, contain 1 object and 4 nulls. The particular object causing the error contains 2 objects and 3 nulls. If I replace the "SIP" object with null it works fine.

```
		"categories": ["GTP_V2C", "SIP", "SIP_TCP", "DIAMETER", "DIAMETER-SCTP"]
....
{
		"name": "020316838",
		"data": [{
			"name": "GTP_V2C",
			"tooltipData": {
				"buckets": [{
					"name": "Application",
					"value": "GTP_V2C"
				}, {
					"name": "Sub Test",
					"value": "020316838"
				}]
			},
			"y": 17.77,
			"value": 2270,
			"totalValue": 12773
		}, {
			"name": "SIP",
			"tooltipData": {
				"buckets": [{
					"name": "Application",
					"value": "SIP"
				}, {
					"name": "Sub Test",
					"value": "020316838"
				}]
			},
			"y": 20.66,
			"value": 847,
			"totalValue": 4099
		}, null, null, null],
		"allowContextMenu": true
	}
```

I have being able to get rid of the error message and get the charts to render by adding a null check hack around the code throwing the error.

highcharts/js/parts/Series.js

https://github.com/highcharts/highcharts/blob/d325976788f178f83397822a0660a6d516f952ff/js/parts/Series.js#L3658-L3659

```
            if(stackValues !== null){
              yBottom = stackValues[0];
              yValue = stackValues[1];
            }
```

#### Product version
6.0.7

#### Affected browser(s)
ALL

**Comment by pawelfus** [comment]
Thanks @ruaneg for creating a separate issue!

**Comment by pawelfus** [comment]
Wait a second. @ruaneg - issue seems to be fixed: https://jsfiddle.net/BlackLabel/bs7nxL2t/ - you probably tried **before** changes..

**Comment by ruaneg** [comment]
Hi @pawelfus,

I tried the fix in the _bugfix/10160-stacking-null-point_ PR on **v6.0.7** and it didn't work.
https://github.com/highcharts/highcharts/commit/4373a2702e04fad53a22b75367fcfd185a1e241b

However, as you say it appears to have fixed the issue on master. I think we can probably close this, sorry for any inconvenience 👍 

cheers

**Comment by pawelfus** [comment]
There were more than just one commit on the branch - that's probably the reason :) Great, thanks for the confirmation! Closing the issue then.

**Comment by ruaneg** [comment]
Ah yes, I didnt notice the latter commit with the safety check.

All good, thanks again
