### ISSUE TITLE
annotations is not working

### ISSUE THREAD

**Issue by gypjoy** [highcharts/highcharts#10251]
I'm trying to use annotations and it doesn't seems to work properly.

I'm loading the module like this:

import Annotation from '../../node_modules/highcharts/modules/annotations.js'
Annotation(Highcharts)

And after that adding some data throught the options:
annotations: [{
          labels: [{
            point: {x: 0, y: 0},
            text: 'Label'
          }]
        }],
But when the graph loads, it doesn't show any annotations, just a string "[object Object]" on the top-left corner

highcharts version : 5.0.14
I also tried to update highcharts to 7.X   but still not working. Error isSVG is not definded

**Comment by pawelfus** [comment]
Hi @gypjoy 
Annotations were released in v6, please update Highcharts to use built-in annotations. Additionally, make sure you update **all** plugins to the same version.

PS: This is our bug tracker, if you have problems with installing/using our plugins, please contact our [support](https://www.highcharts.com/blog/support/).

**Comment by gypjoy** [comment]
> Hi @gypjoy
> Annotations were released in v6, please update Highcharts to use built-in annotations. Additionally, make sure you update **all** plugins to the same version.
> 
> PS: This is our bug tracker, if you have problems with installing/using our plugins, please contact our [support](https://www.highcharts.com/blog/support/).

the v6 is v6.0.0?

**Comment by pawelfus** [comment]
Yes, it's v6.0.0 and higher

**Comment by gypjoy** [comment]
> Yes, it's v6.0.0 and higher

update highcharts to 7.0.3,   Error isSVG is not defined

**Comment by sebastianbochan** [comment]
Can you confirm that all work properly, after update?

**Comment by pawelfus** [comment]
@gypjoy 

Let me remind:
> Additionally, make sure you update all plugins to the same version.

If that does not help, please contact our support: https://www.highcharts.com/blog/support/
