### ISSUE TITLE
yAxis extremes set by 'setExtremes()' function are not respected on exported chart.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#10258]
#### Expected behaviour
Exported chart should have the same extremes.

#### Actual behaviour
If setting new extremes on yAxis using `Axis.setExtremes()` function, the new extremes are not set on exported chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/jf3468mh/
1. Click on button below chart to set new extremes
2. Export image

#### Product version
Highcharts Gantt

#### Workaround
New extremes can be stored somewhere on every call of `afterSetExtremes` event on yAxis, and then we can set it on `exporting.chartOptions.chart.events.load` function, like below:

```js
var newMin, newMax;

// THE CHART
Highcharts.ganttChart('container', {
    exporting: {
      chartOptions: {
      	chart: {
          events: {
            load() {
              this.yAxis[0].setExtremes(newMin, newMax)
            }
          }
        }
      }
    },
    yAxis: {
      events: {
      	afterSetExtremes() {
          var ext = this.getExtremes()
          newMin = ext.min
          newMax = ext.max
        }
      }
    },
    series: [{
       // Series here
    }]
});
```

Live example: http://jsfiddle.net/BlackLabel/pnq8z73y/

**Comment by sebastianbochan** [comment]
**Internal note**
The problem is that extremes are ignored on `yAxis` (after zoom) in exporting. 

Simplified demo:
- http://jsfiddle.net/BlackLabel/qomfLyru/
