### ISSUE TITLE
last yAxis tick is out of bounds

### ISSUE THREAD

**Issue by omryr** [highcharts/highcharts#10266]
The last tick of the yAxis always goes out of the chart bounds and instead of getting its y and x positions right is set to x:0 and y: -9999 

<text x="0" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="-9999">10</text>

you can see this happen in this example:

https://codesandbox.io/s/jzjzr57jw?from-embed

is there a way i can force it to render in the right place? or am i missing something?

**Comment by pawelfus** [comment]
Hi @omryr 

To control the last label visibility simply set [`yAxis.showLastLabel`](https://api.highcharts.com/highstock/yAxis.showLastLabel) to true, demo: https://codesandbox.io/s/yqz43yr43z
