### ISSUE TITLE
Range selector button click function receives no event argument

### ISSUE THREAD

**Issue by Konpon96** [highcharts/highcharts#10261]
I wanted to stop propagation of my range selector button click event, because one of the functions I'm executing in my callback recreates the chart so once the event finishes, there is no chart the event could return its value to. This results in errors which could be possibly avoided by calling `stopPropagation()` method on the event. However, the event object is undefined, although according to the documentation it should be there.

#### Expected behaviour
According to documentation (https://api.highcharts.com/highstock/rangeSelector.buttons.events.click) the range selector button callback should have event object passed to the function.

#### Actual behaviour
Event function is not passed to the button callback function.

#### Live demo with steps to reproduce
Here is the demo, based on one of Highchart demos: https://jsfiddle.net/konpon96/g48yubks/

If you click "1m" zoom button, a button callback function will be called. The function simply prints to the console the event object, received as its argument. However, "undefined" is printed to the console. 

#### Product version
Highstock, version 7.0.3.

#### Affected browser(s)
Chrome and Firefox for sure, didn't check on other ones, but those two pretty much cover vast majority of used browser engines.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, it is fixed in the master and will be part of the next release.

Demo with the fix applied: https://jsfiddle.net/highcharts/wr3hamtf/1/
