### ISSUE TITLE
Heatmap uses wrong min/max values on datetime x-axis

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/highcharts#10263]
#### Expected behaviour
Setting the min and max values on the x-axis should properly be applied to the extremes.

#### Actual behaviour
Setting min/max on heatmap seems to always add an additionial/hidden tick. I also tried both setting the min/max properties of the x-axis and using the setExtremes() method but neither seem to work

#### Live demo with steps to reproduce
I am uncertain if the other options in my example contribute to the problem, but this is the configuration I need for my use case:
https://jsfiddle.net/lanimelrok/4vw2stjn/

#### Product version
Highstock 7.0.3

**Comment by sebastianbochan** [comment]
Hi @LaniMoo,
Thank you for reporting about the problem.

FYI @jon-a-nygaard

**Comment by LaniMoo** [comment]
Would you be able to recommend any workarounds in the meantime?

**Comment by jon-a-nygaard** [comment]
Hi @LaniMoo, I am currently looking into the issue and checking if we can provide a workaround. Will come back to you as soon as I know some more.

**Comment by sebastianbochan** [comment]
Hi @LaniMoo,
Until @jon-a-nygaard will publish better workaround, Im posting the really simple workaround with categories.

https://jsfiddle.net/BlackLabel/uo30crd2/

**Comment by jon-a-nygaard** [comment]
@LaniMoo I believe the following example https://jsfiddle.net/jon_a_nygaard/s086fknc/ could be a potential workaround for you.
It removes the added `pointRangePadding` that you in this case want to avoid.

**Comment by LaniMoo** [comment]
Thank you both for your suggestions!!

@jon-a-nygaard that workaround worked great, thank you! I added one minor tweak to make it more flexible since the column size and x-range extremes will vary in my use case depending on the resolution of my data (e.g. hourly, daily, weekly, etc): https://jsfiddle.net/lanimelrok/p0scoute/
