### ISSUE TITLE
Text in overlapping flags are visible (IE8)

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#1026]
1. Open http://jsfiddle.net/gh/get/jquery/1.7.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/flags-general/ in IE8 or IE9 with doc-mode 8
2. Look at the flags 'C' and 'D' that are overlapping. C should be covered by D

Result: The circle is covered ok but the text for both flags are visible.
Expected: Only 'D' should be readable

**Comment by KacperMadej** [comment]
I am unable to recreate the problem from the demo provided and a simple chart with overlapping flags shows correctly in IE8 - like in the image below:

![ie8-flags](https://cloud.githubusercontent.com/assets/8960408/24244515/8ea345a8-0fbf-11e7-9756-12006919cb6f.jpg)

If the problems is still existing, please provide a demo for verification and the issue will be reopened.
