### ISSUE TITLE
Missing type definition on Range Selector and Navigator 

### ISSUE THREAD

**Issue by briankpw** [highcharts/highcharts#10274]
#### Expected behaviour
Range Selector and Navigator should able to apply theme, `Highcharts.setOption(theme)`

##### 1.
I try to use `declare` in app.component.ts to apply theme on angular. The Range Selector’s Button Theme doesn’t apply theme, and Navigator maskFill doesn’t reflect the color. 
 
```ts
declare module 'highcharts' {
  interface NavigatorSeriesOptions {
    color: Highcharts.ColorString;
  }
 
  interface SVGAttributes {
    states: Highcharts.CSSObject;
  }
}
```

#### Live demo with steps to reproduce
https://stackblitz.com/edit/highchart-angular?file=app%2Fapp.component.ts

##### 2.
BoxPlot unable to apply theme. I am apply plotOptions in `Highcharts.setOptions();`

`boxplot: { fillColor: 'rgb(100,100,100)' },`
 
Its doesn’t reflect the color. 

#### Live demo with steps to reproduce
https://stackblitz.com/edit/highchart-angular-chart?file=app%2Fapp.component.ts

#### Product version

Highcharts v7.0.3 and highchart-angular 2.4.0

**Comment by sebastianbochan** [comment]
Hi @briankpw,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by bre1470** [comment]
@sebastianbochan 
I am unsure if this report is just about the TypeScript interfaces or also about missing changes after applying the theme.

I will answer the first point:
a) `NavigatorSeriesOptions` officially does not provide a `color` option so far. Should we make this official, @TorsteinHonsi ?
b) `SVGAttributes` will support custom properties like 'states' with the next update.

**Comment by TorsteinHonsi** [comment]
If it's a Highcharts issue we need a pure JS demo.

> NavigatorSeriesOptions officially does not provide a color option so far. Should we make this official, @TorsteinHonsi ?

Yes I think that should be official.
