### ISSUE TITLE
Changing the 'data.rowsURL' value through 'Chart.update()' doesn't affect chart.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#10273]
#### Expected behaviour
Chart should be updated with new 'data.rowsURL' value, and filled by new data collected from updated URL.

#### Actual behaviour
Calling 'Chart.update()' with new 'data.rowsURL' value doesn't affect chart appearance, and the data is still the same as before updating.

#### Live demo with steps to reproduce
Live example: https://jsfiddle.net/BlackLabel/07dh2gmz/

_Internal Note:_
_After opening Network tab, it's noticeable that all data requests are still addressed to the old URL_

**Comment by halloleo** [comment]
Looks like this is fixed already! Thanks a lot. 

However, how can I get this fix into an existing  Vue app? I had HighCharts imported as a `node_modules` via `yarn`.

    yarn add highcharts
    yarn add highcharts-vue

How can I updated this to the version with the fix? 

Many thanks.

**Comment by Denyllon** [comment]
Hi @halloleo 

The most recommended way would be to wait for the new release of Highcharts, but also you can apply the fix, which Wojtek made for you on the [forum topic](https://www.highcharts.com/forum/viewtopic.php?f=9&t=41671&p=145860#p145860).

Kind regards!

**Comment by halloleo** [comment]
Thanks so much!
