### ISSUE TITLE
xAxis.min is treated as a series element index and not a base axis value

### ISSUE THREAD

**Issue by gh-andre** [highcharts/highcharts#10277]
#### Expected behaviour

Axis minimum should define the base value for the axis, which increases with every axis step and is associated with a series element positionally, so column data rendered at the axis minimum would come from the 0th series data element for any `xAxis.min` value. 

#### Actual behaviour

`xAxis.min` is interpreted as an index into the series data, so value `1` skips the first element in the series data array. 

#### Live demo with steps to reproduce
The first element in the series is ignored because `xAxis.min` is interpreted as a starting series data array index and not as a series base value.
```
Highcharts.chart('container', {
    title: {
        text: "xAxis.min is treated as a series element index and not a base axis value"
    },
    xAxis: {
        min: 1,
        max: 10,
    },
    series: [{
        type: "column",
        data: [1, 2, 0, 4, 0, 0, 7, 8, 9, 0]
    }]
});
```
#### Product version

Highcharts v7.0 latest

#### Affected browser(s)

Not browser specific.

**Comment by pawelfus** [comment]
Hi @gh-andre 

Thanks for reporting the issue. I might be wrong, but I think the option you are looking for is [`series.pointStart`](https://api.highcharts.com/highcharts/series.line.pointStart). By default `pointStart = 0`, so you points have x-values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]. When you set `xAxis.min = 1` then you remove the first point from the viewport.

**Comment by gh-andre** [comment]
I may not explained this well. Let me elaborate. `xAxis.min` is defined in Highcharts docs as

> The minimum value of the axis. If null the min value is automatically calculated.

Axis values are defined in terms of user-visible values, like days or years, so "_minimum value of the axis_" suggests that it's the minimum value, like a first day or year. 

However, `xAxis.min` implemented as an index into the series data array, which doesn't agree with the definition above.

`series.pointStart` would allow me to shift the series within the axis, but not define the base value for the axis. 

`xAxis.min` visually behaves as an axis value in that it renders `1` if assigned a value of `1`, but the fact that it uses this value as an index doesn't make much sense to me. 

Anyway, I worked around this problem by removing `min`/`max` completely and by adding `categories` to the axis, so I'm not blocked and since you already closed the bug, you can just ignore this comment. I will also not follow up on it. I do suggest, however, to run this by your Product. They may see the issue I'm describing.

**Comment by KacperMadej** [comment]
@gh-andre 
I'm still unable to understand what the problem was. Here's a live demo with your options - https://jsfiddle.net/BlackLabel/yn1a9vtk/

Series is cropped to fit into the limited axis range, so the first point (with x index equal to 0) is outside of the currently visible axis range.

xAxis.min is **not** implemented as an index into the series.

**Comment by gh-andre** [comment]
@KacperMadej 

> Series is cropped to fit into the limited axis range

Series has 10 values and `min`/`max` specifies `1`/`10`. The axis has exactly the number of values that is in the series and, yet, the first value is dropped, as you can see only `2` is shown on the left. 

> with x index equal to 0

There, you actually said "index". Note that `x` actually is supposed to show axis values, which is, say, days, so it cannot be `0`. What you are talking about is the actual index into the series data array, which indeed is zero. The data is supposed to change from `min` to `max` with some step and should reflect only actual axis values.

**Comment by KacperMadej** [comment]
> Series has 10 values and min/max specifies 1/10.

Series has 10 points with set y values. X values are not set, so by default they start from 0 with interval of 1. This makes first point as `{x: 0, y: 1}`, second as `{x: 1, y: 2}`, and so on.

Min and max are set on xAxis, so x values will be affected. Since min on xAxis is set to 1, then the point with x: 0 will be out of the set range.

> The data is supposed to change from min to max with some step and should reflect only actual axis values.

We have no such feature (to work like this by default) implemented. To get this kind of a chart you would have to use series' pointStart and pointRange, and set those two options based on series data size (number of points), so if you want to spread 10 points from 1 to 10, then you have to calculate what should be the pointStart and pointRange, so it would work as you need with set xAxis min and max.

**Comment by gh-andre** [comment]
> Series has 10 points with set y values. X values are not set, so by default they start from 0 with interval of 1. This makes first point as {x: 0, y: 1}, second as {x: 1, y: 2}, and so on.

I see what's going on. You generate `x` values for each series starting with a zero and ending with a series size minus one and then render only those `x`/`y` pairs that have `x` greater or equal than `min`, even though those generated `x` values have nothing to do with user data other than define the order of elements in the series array.

`pointStart ` is a defined for the series. `min` is defined for the axis. There is a difference:

* If I defined an X axis for a month and defined a minimum and a maximum for it as `1` and `30` and plot a few series of 30 values on this axis, I would expect those series start in the first slot of my axis, which would be my minimum of `1`. Having to think about some positional zero-based `x` values the implementation injects doesn't sound very logical to me. 

* If one of my series is missing a couple of days at the beginning, I could shift this series with something like `pointStart`, but that's a per-series shift amount. Having to define such value for each series just to deal with those generated `x` values doesn't sound very logical to me either. 

It would sound more logical to me if those generated `x` values started with the axis `min` value, not with a zero, and then would be either offset by or assigned `pointStart`. As things stand now, `min` for column-like series can only be used for some obscure zero-based series filtering, where series elements from zero to `min - 1` would be ignored.

**Comment by KacperMadej** [comment]
You could set x values for a point - as [fully described in the API docs](https://api.highcharts.com/highcharts/series.line.data) - you could define series data as arrays of keys, like `[x, y]` or objects with named properties, like `{x: ..., y: ....}`. If you are using 3rd way of data format (only `y` values) then `x` values will be assigned based on used `pointStart` and `pointInterval`. The default values for those are `0` and `1`. This not connected to any axis in any way. Axis options are connected with how data is being displayed and not how it's defined or set for a series. All the info I have provided for you is based on our documentation and API reference. I'm just trying to explain how things are right now and how they work.

Your expectations are rather uncommon - have you been using some library, programming language or environment where the described behavior is a standard or default? Maybe this would allow me to better understand what's your logic based on.

We are open for all enhancement suggestions, so if you would like us to implement a new feature please send us your idea via UserVoice - https://highcharts.uservoice.com/forums/55896-general 
The most popular ideas are getting implemented.

**Comment by gh-andre** [comment]
Before I say anything else, let me thank you for your feedback and the software in general. Please do not consider my responses below as argumentative. Once I realized that rendering Y-only series is done with an X/Y chart rendering engine, it became clear to me how to work structure my charts. 

> you could define series data as arrays of keys, like [x, y]

Yes, this is how I did it at first, but it's rather wasteful having to create anonymous objects with X values that are always sequential anyway. I realize that Highcharts does it anyway behind the scenes, but I just find it easier for people to work with a single set of series values that starts at common point for their axis. I stack multiple Y axis against the same X axis and having to set `pointStart` for each chart to the same value is unnecessary, given that I set up the X axis to work for all charts.

> Your expectations are rather uncommon - have you been using some library, programming language or environment where the described behavior is a standard or default? Maybe this would allow me to better understand what's your logic based on.

Charting in most spreadsheet applications distinguish column/etc charts from X/Y charts and in the former case allow one to pick Y values and can associate a range of auto-filled cells for the X axis, which all Y value charts share. Granted, this can be viewed simply as categories, but from the spreadsheet user's point of view it's just a counter range with a start and step for the single axis. 

Anyway, thanks again for spending the time to dive into this thread and thoughtful comments. It is much appreciated.
