### ISSUE TITLE
How to install highcharts so that it will work as a local CDN?

### ISSUE THREAD

**Issue by karezza** [highcharts/highcharts#10278]
#### Expected behaviour
Installing allows localhost to behave as cdn for export server

#### Actual behaviour
Installing via npm a folder is installed; linking folder to /var/www/html does not result in a valid cdn

#### Live demo with steps to reproduce
I've also tried using zip files resulting in the following structure:
/var/www/html/7.0.3/highcharts.js
/var/www/html/stock/7.0.3/highstock.js

This is by moving the 'code' folder from the zip file to be 7.0.3 in each case.

It sets up via 'node ./build.js' just fine, appears to find all the files it needs.  Runs without any errors, but the resulting image file is not a valid image file.  Specifying the public CDN works, so everything else is setup right ... it's just the structure, as far as I can see, that must not be quite right... out of ideas, appreciate any help.

#### How to install highcharts so that it can be used as a local CDN?

**Comment by pawelfus** [comment]
Hi @karezza 

Thanks for choosing Highcharts. However, you posted your issue on our bug tracker. If you have questions, please use our [other support channels](https://www.highcharts.com/blog/support/).
