### ISSUE TITLE
[BUG]: "Cannot read property 'series' of undefined"

### ISSUE THREAD

**Issue by TitaneBoy** [highcharts/highcharts#10284]
Hello team. I'm facing a particular issue with HighCharts since few days. I remember that I didn't observed this behavior few weeks/months ago... And I didn't change anything in the code the of Angular component.

Here is the context: I have an Angular Web Page that contains a components who display an Highcharts chart. The first time I hit this page, everything works well and I have no issue. Then When I decide to click in a menu to go to another page (For example: Home page), then after When I decide to click again to go to the Highcharts page, The Highcharts seems to crash and to not work..

Here is the sequence flow:

![image](https://user-images.githubusercontent.com/15614466/54033234-c13b8200-4181-11e9-8b75-ab32836533c7.png)

As I said, When doing the first click to go to the HighCharts page, everything is going well...No problem, error or issue.

![image](https://user-images.githubusercontent.com/15614466/54033407-3c9d3380-4182-11e9-990b-77cdc240d125.png)

Then I decide to go to the home page:

![image](https://user-images.githubusercontent.com/15614466/54033584-ae757d00-4182-11e9-9c11-0620bc0c5245.png)

This action will call the ngDestroy of my component containing Highcharts

After, I click on the "Real Time Highcharts" button again to get the chart page, and it is at this moment Highcharts seems to crash somehow

![image](https://user-images.githubusercontent.com/15614466/54033748-23e14d80-4183-11e9-90cd-f1612be10c44.png)

Here is the content of the html part of my component:
**status-highcharts.component.html:**

```
<highcharts-chart id="statusHighchart" [Highcharts]="Highcharts" [constructorType]="chartConstructor" [options]="chartOptions" [(update)]="updateFlag" style="width: 100%; height: 600px; display: block;">

</highcharts-chart>
```

Here is the content of the component itself:

**status-highcharts.component.ts**

```
import { Component, OnDestroy, OnInit } from '@angular/core';

import * as Highcharts from 'highcharts';
import StockModule from 'highcharts/modules/stock';
StockModule(Highcharts);

import HC_exporting from 'highcharts/modules/exporting';
import * as AvocadoTheme from 'highcharts/themes/avocado';
import * as DarkBlueTheme from 'highcharts/themes/dark-blue';
import * as DarkGreenTheme from 'highcharts/themes/dark-green';
import * as DarkUnicaTheme from 'highcharts/themes/dark-unica';
import * as GrayTheme from 'highcharts/themes/gray';
import * as GridTheme from 'highcharts/themes/grid';
import * as GridLightTheme from 'highcharts/themes/grid-light';
import * as SandSignikaTheme from 'highcharts/themes/sand-signika';
import * as SkiesTheme from 'highcharts/themes/skies';
import * as SunsetTheme from 'highcharts/themes/sunset';

import { Subscription } from 'rxjs';
import { ResumeLiveService } from '../services/resume.live.service';

HC_exporting(Highcharts);

@Component({
  selector: 'rbwc-status-highcharts',
  templateUrl: './status-highcharts.component.html',
  styleUrls: ['./status-highcharts.component.css'],
})
export class StatusHighchartsComponent implements OnInit, OnDestroy {
  private seriesIndexMap = new Map<number, number>();
  statusReadingSubscription: Subscription;
  Highcharts = Highcharts;
  chartConstructor = 'chart'; // stockChart
  lastUpdated: Date = new Date();
  chartOptions = {
    chart: {
      zoomType: 'x',
      type: 'spline',
    },
    boost: {
      seriesThreshold: 3,
    },
    title: {
      text: 'Real Time Gas measurement status',
    },
    subtitle: {
      text: document.ontouchstart === undefined ?
        'Click and drag in the plot area to zoom in' : 'Pinch the chart to zoom in',
    },
    xAxis: {type: 'datetime'},
    yAxis: {
      title: {
          text: 'Number of ppm',
      },
    },
    legend: {
      enabled: true,
    },
    rangeSelector: {
      buttons: [{
          count: 1,
          type: 'minute',
          text: '1M',
      }, {
          count: 5,
          type: 'minute',
          text: '5M',
      }, {
          type: 'all',
          text: 'All',
      }],
      inputEnabled: false,
  },
  }; // required
  updateFlag = false; // optional boolean

  constructor(private resumeLiveService: ResumeLiveService) {
    DarkBlueTheme(this.Highcharts);
  }

  ngOnInit() {
    this.updateFlag = true;
    this.statusReadingSubscription = this.resumeLiveService.getLiveResumeData().subscribe((liveReadings) => {

      if (!this.updateFlag) {
        for (const reading of liveReadings) {
          if (reading.measurement_info.id > 10) {
            continue;
          }
          const serieIndex = this.seriesIndexMap.get(reading.measurement_info.id);
          if (serieIndex === undefined) {
            this.seriesIndexMap.set(reading.measurement_info.id, this.Highcharts.charts[0].series.length);
            const series = this.Highcharts.charts[0].addSeries({
              name: reading.measurement_info.name,
              type: 'spline',
            });
            series.addPoint([new Date(reading.reading.timestamp).getTime(), reading.reading.value]);
          } else {
            const dataTemp = this.Highcharts.charts[0].series[serieIndex].data;
            if (dataTemp[dataTemp.length - 1] !== undefined && dataTemp[dataTemp.length - 1].y !== reading.reading.value &&
                dataTemp[dataTemp.length - 1].x !== new Date(reading.reading.timestamp).getTime()) {
              const tempRandom = Math.floor((Math.random() * 10) + 1);
              const tempDate = new Date(reading.reading.timestamp);
              let tempYValue = reading.reading.value;
              const tempXValue = (tempDate.getTime());
              if (tempRandom === 5) {
                console.log('Insertion de NUll dans le graph pour' + reading.measurement_info.name + ' à x = ' +
                tempDate.toString());
                tempYValue = null;
              }
              this.Highcharts.charts[0].series[serieIndex].addPoint([tempXValue, tempYValue]);
            }
          }
        }
        this.updateFlag = true;
      }
    });
  }

  ngOnDestroy() {
    if (this.statusReadingSubscription) {
      this.statusReadingSubscription.unsubscribe();
    }
  }
}
```

Here is the section where it crashes with Chrome and Firefox (line 94):
![image](https://user-images.githubusercontent.com/15614466/54034152-255f4580-4184-11e9-86a4-c06673e24487.png)

#### Expected behaviour
No error when visiting again (after user quits the page) the page containing Highcharts component.

#### Actual behaviour
On Chrome:

![image](https://user-images.githubusercontent.com/15614466/53989380-d36edf00-40f3-11e9-892e-f356963aeafb.png)

![image](https://user-images.githubusercontent.com/15614466/53989414-e97c9f80-40f3-11e9-9ce5-13485974e628.png)

On FireFox:

![image](https://user-images.githubusercontent.com/15614466/53989474-0f09a900-40f4-11e9-9cbd-b23828f72004.png)

![image](https://user-images.githubusercontent.com/15614466/53989516-234da600-40f4-11e9-9b27-c6c9edd06474.png)

#### Product version

highcharts: 7.0.3
highcharts-angular: 2.4.0
#### Affected browser(s)
Chrome 72.0.3626.119 (Official Build) (64 bits)
FireFox: 65.0.2 (64 bits)

As I said before, I didn't have this behavior few months ago...and now, I got this issue. I didn't change the code of my component so I suppose something is happening in the Highchart library.  Can you guys help me to determine if there is a true issue in the Highchart package or if I'm doing something wrong ?

Thank you in advance for your help.

**Comment by KacperMadej** [comment]
Hi @TitaneBoy 

Thank you for reporting about the problem.

Please add a live demo, so we could recreate the problem, debug it and test possible solutions.
Looks like the problem is caused by your custom code, so you could check if it works as it should.
If the code was working some time ago, then you could try using older version of Highcharts. Here's a changelog: https://www.highcharts.com/blog/changelog/

**Comment by TitaneBoy** [comment]
Hi @KacperMadej 

[Here](https://stackblitz.com/edit/angular-1otupd) is, as requested, a live demo project that recreates the problem and [here](https://angular-1otupd.stackblitz.io/home) is the URL that executes the live demo. 

Here is the flow:

Click on the "Real Time Highcharts" button (I know, it doesn't seems like a button but it's kind of...

![image](https://user-images.githubusercontent.com/15614466/54225357-e574c700-44d1-11e9-920e-d23036ce538c.png)

You will see the HighCharts working as expected without error.

![image](https://user-images.githubusercontent.com/15614466/54225778-d04c6800-44d2-11e9-9c3d-4384a34678c1.png)


Then Click on the "Home Page" button:

![image](https://user-images.githubusercontent.com/15614466/54225858-fd991600-44d2-11e9-932b-608bf2d3bd16.png)


Then again, click on the "Real Time HighCharts" button

You will see the HighCharts page, but with no data / Chart displayed... If you see the console, you will see the error:

![image](https://user-images.githubusercontent.com/15614466/54226006-4355de80-44d3-11e9-9bf3-b465ea8f39a2.png)

You can see, in the console of the StackBlitz live demo project (the first [link](https://stackblitz.com/edit/angular-1otupd), the same error:

![image](https://user-images.githubusercontent.com/15614466/54226199-ae071a00-44d3-11e9-9c95-394e1651dc89.png)

**Comment by pawelfus** [comment]
This is wrong:

> this.Highcharts.charts[0]

You are always referring the first chart in `charts` array, which may not be the case. Instead you should get the chart instance, see [docs](https://github.com/highcharts/highcharts-angular#chart-instance).

**Comment by TitaneBoy** [comment]
@pawelfus Thank you for the hint. This information resolve completly my issue and it is now more clear what is happening.. 

Again, thank you.

**Comment by jhonnyperezm** [comment]
Hello, I present the same problem not found a solution to the problem of the series




![1](https://user-images.githubusercontent.com/33642805/55915195-ab6d1280-5bae-11e9-81c4-f53a11f54114.png)
![2](https://user-images.githubusercontent.com/33642805/55915196-ac05a900-5bae-11e9-8cad-d6648ead67e7.png)

**Comment by sebastianbochan** [comment]
Hi @jhonnyperezm,
Could you post your live demo of problem? It will allow us to debug and find a solution.

**Comment by jhonnyperezm** [comment]
@sebastianbochan 
Hello, you have created an error repository and a live demo

**Repositorio**
https://github.com/jhonnyperezm/apli-grafica

**live**
https://codesandbox.io/embed/8l9m3jo410?fontsize=14

I was grateful for a possible solution

**Comment by KacperMadej** [comment]
Duplicate of https://github.com/highcharts/highcharts-angular/issues/122#issuecomment-483184888
