### ISSUE TITLE
[bug?] Responsive pie chart not reseting legend

### ISSUE THREAD

**Issue by MisterTicot** [highcharts/highcharts#10286]
#### Actual behaviour
I'm using responsive property to display pie chart legend only under a given container width. If I enlarge container over the responsive rule threshold, legend box still shows.

#### Expected behaviour
The legend box should disappear when responsive rule doesn't apply anymore.

#### Live demo with steps to reproduce
http://jsfiddle.net/0n2jgt9v/1/

Shrink & enlarge the container: legend box appear when container is under width threshold but doesn't disappear thereafter.

#### Product version
Latest

#### Affected browser(s)
Chromium

#### Priority
Low

**Comment by KacperMadej** [comment]
Hi @MisterTicot 

Thank you for reporting about the problem.

As a **workaround** you could disabled and enable chart's legend using responsive rules to ensure it's visibility. Demo: http://jsfiddle.net/BlackLabel/e3agL2z0/

**Comment by MisterTicot** [comment]
Thank you!

**Comment by TorsteinHonsi** [comment]
A demo with a toggle button makes it more predictable for debugging: 
http://jsfiddle.net/highcharts/v7jfmcsg/6/
