### ISSUE TITLE
Gantt chart yaxis label does not adjust size with long label text

### ISSUE THREAD

**Issue by TweededBadger** [highcharts/highcharts#10281]
#### Expected behaviour
When a long name is supplied to a gantt chart row, the label should be clipped with ellipsis, and the surrounding grid resize accordingly

#### Actual behaviour
The label is clipped with ellipsis, but the grid does not resize.
![image](https://user-images.githubusercontent.com/3278046/54025294-ff40a200-4191-11e9-8394-ab3304737f7a.png)
(I've searched hard for a configuration option that may fix this but have had no luck)

#### Live demo with steps to reproduce
https://jsfiddle.net/k41eg257/

#### Product version
Highcharts v7.0.3

**Comment by sebastianbochan** [comment]
Hi @TweededBadger,
Thank you for reporting. 

As a workaround you can declare `width / height` and apply CSS styles.

```
    yAxis: {
    	labels: {
      	useHTML: true,
      	style:{
        	width: '100px',
          height: '18px'
        }
      }
    },
```

**Demo:**
- https://jsfiddle.net/BlackLabel/b391do7t/1/
