### ISSUE TITLE
HTML <base> tag Firefox with Scatter series - click events are not applied

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10283]
When HTML **base** tag is defined, click events are not applied to the Scatter series:
- series.events.click
- series.point.events.click

Also, **series.cursor: 'pointer'** doesn't work.
Line and column series work properly.

#### Live demo with steps to reproduce
Open in Firefox: https://jsfiddle.net/BlackLabel/hn4xkw6d

#### Product version
Highcharts 7.0.3

#### Affected browser(s)
Firefox 65.0.2 x64

**Comment by TorsteinHonsi** [comment]
Firefox has some specific issues with internal relative paths and base URLs. In this case it seems to be something with the clip path.

#### Workaround
Set `clip` to false: https://jsfiddle.net/yj1o4Lsa/

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: https://jsfiddle.net/highcharts/myfvuehs/
