### ISSUE TITLE
"exporting" specific title is not shown when printing a chart

### ISSUE THREAD

**Issue by FuadBalashov** [highcharts/highcharts#10297]
#### Expected behaviour
When printing a chart using the export module the title nested in the `exporting` section of the options should be displayed in the chart.

#### Actual behaviour
When printing a chart using the export module the title nested in the `exporting` section of the options is not included.

* Note that if you select any of the other options the title WILL be shown.
* If you include a title OUTSIDE of the exporting options it will be shown when printing but will be overridden when performing any other export: http://jsfiddle.net/6d23xtrq/

#### Live demo with steps to reproduce
Live Demo at: http://jsfiddle.net/BdHJM/
Code at the bottom of issue.
Steps:
1) Click the export button
2) Select the "Print chart" option
3) Note that the title is missing from the chart

#### Product version
Highcharts Export module
Version: 7.0.3
This seems to have been happening since 2013: https://stackoverflow.com/a/14751827/6526330

#### Affected browser(s)
* Chrome, IE, edge

Code from demo:
```
$(function () {
    var chart;
    $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'container',
                type: 'line'
            },
            exporting:{
                chartOptions:{
                    title: {
                        text:'aaaaa'
                    }
                }
            },
            series: [{
                name: 'Tokyo',
                data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
            }]
        });
    });
    
});
```

**Comment by sebastianbochan** [comment]
Hi @FuadBalashov,
Thank you for reporting about the problem.

**Workaround**
Use `before / afterPrint` events and set title by API.

Demo:
- http://jsfiddle.net/BlackLabel/j8g7vdr9/

**Comment by FuadBalashov** [comment]
Hi Sebastian, thank you for sharing the workaround. It works well in my case since I just need to set the title when I print! 

I did a bit of digging and there are two remaining issues with the workaround that suggest that the issue should be fixed instead of changing the API:

1) The position of the title is not correct when using the before and after print functions:
As you can see in the demos and images below, the title gets positioned over the chart when you use the before and after functions.

| Case | Title is statically set | Title is set with Before/After print |
| ----- | --------------------- | ------------------------------------- |
| Demo Link | http://jsfiddle.net/8z9gyq2a/ | http://jsfiddle.net/BlackLabel/j8g7vdr9/ |
| Image | ![image](https://user-images.githubusercontent.com/7839848/54205929-acc2f680-44ad-11e9-85dc-f9b4ff22a828.png) | ![image](https://user-images.githubusercontent.com/7839848/54205283-720c8e80-44ac-11e9-9ce6-108b30fe5465.png) |

2) Other fields in the `exporting` options do not get persisted to the chart:
Even if this works for the title, the same issue happens on other fields that I include in the exporting options. I am not sure if it is for all of them, but here is another example with the credits disabled in export options which displays the same behavior as the title.

http://jsfiddle.net/k5tazg0L/

Code:
```
$(function() {
  var chart;
  $(document).ready(function() {
    chart = new Highcharts.Chart({
      chart: {
        renderTo: 'container',
        type: 'line',
      },
      title: {
        text: 'aaaa',
      },
      series: [{
        name: 'Tokyo',
        data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
      }],
      exporting: {
        chartOptions: {
          credits: {
              enabled: false,
          },
        },
      },
    });
  });
});
```

**Comment by TorsteinHonsi** [comment]
> I observed that exporting options are ignored during "print" in general. According to our API it should work, so the question is, should we edit API or fix this issue?

Actually the API says "Additional chart options to be merged into an exported chart", which is rather vague, but the functionality has always been related to charts exported to images (via the export server), not printed. So it is in fact a docs issue. 

If we were to apply the `chartOptions` to the printed chart, it would be as an enhancement.
