### ISSUE TITLE
Calling Series.update results in additional show and hide challbacks execution

### ISSUE THREAD

**Issue by flare256** [highcharts/highcharts#10296]
#### Expected behaviour

Series.update should not affect how many times show and hide callbacks are executed.

#### Actual behaviour

Each Series.update call results in one additional show and hide callback call (not during update, but for example on legend item click). Both functions are set via plotOptions.

#### Live demo with steps to reproduce
https://jsfiddle.net/futj0a83/

Open developer console, click on button and then toggle menu item.

#### Product version
Highstock JS v7.0.3

#### Affected browser(s)
Tested on Chrome 72.0.3626.121 (Official) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @flare256,
Thank you for reporting about the problem. 

**Internal note**
The problem is seems to be caused by incorrect destroy props of series. Inside the function, `hcEvents` are skipped during action.

@TorsteinHonsi 
This lines fixes the problem, but Im not sure what is the reason of this condition. 
```
            objectEach(series, function (val, prop) {
                //if (!keepEvents || prop !== 'hcEvents') {
                    delete series[prop];
                //}
            });
```

**Comment by TorsteinHonsi** [comment]
It is somehow related to #10100, but that fix doesn't fix this one. It seems like it's the navigator that triggers the extra events.

**Comment by pawelfus** [comment]
Yes, issues comes from navigator, when `showInNavigator` is set to false, no extra events: https://jsfiddle.net/BlackLabel/vwa45gLm/

**Comment by pawelfus** [comment]
Unstale
