### ISSUE TITLE
Multiple loaded `solid-gauge` module and use of `rounded` option throws an exception

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#10293]
#### Expected behaviour
The chart should work without any errors: https://jsfiddle.net/BlackLabel/13ha9g26/

####  Actual behaviour
The chart works incorrectly: https://jsfiddle.net/BlackLabel/7tj6dyu0/

#### Product version
Highcharts v7.0.3

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
This is fixed with the new assembler, that keeps track of module loading and avoids running the same module twice.
