### ISSUE TITLE
Lazy loading multiple series causes various bugs in highcharts and highstock functions

### ISSUE THREAD

**Issue by faebuk** [highcharts/highcharts#10290]
#### Expected behaviour
Lazy loading with multiple series should work as expected. Means the "Reset Zoom" and range selectors should work correctly. Also there shouldn't be displayed wrong values.

#### Actual behaviour
For highcharts:
- sometimes it reexecutes the afterSetExtremes to many times. After that, there is a loading loop, which resizes the chart everytime and reexecutes the afterSetExtremes
- The "Reset zoom" button doesn't work as expected, doesn't zoom out the whole range

For highstock:
- After manually zooming and then resetting the button back to "All" causes wrong values being shown
- Loading loop as for highcharts sometimes created

#### Live demo with steps to reproduce

For highcharts: 
https://codepen.io/anon/pen/WmpBBr   
- Original demo taken
- Modified 1 series to 3 (taking low and high as new serie)
- Changed to line chart

Steps to reproduce:
Bug 1:
- Manually zoom in
- Try to click the "Reset zoom" button
- Doesn't zoom out the whole range

Bug 2:
- Hard to reproduce
- Sometimes when you zoom in the right amount, it creates a loading loop which rescales/moves the chart a bit, recalls afterSetExtremes, rescales it and so on

For highstock:
https://codepen.io/anon/pen/GeWVvv   
- Original demo taken
- Modified 1 series to 3 (taking low and high as new serie)
- Changed to line chart

Steps to reproduce:
Bug 1:
- Original screen looks like this https://i.imgur.com/ZPXIPNP.png
- Manually zoom in few times
- Click the "All" range selector
- Wrong values being shown https://i.imgur.com/9woTznM.png

Bug 2:
- Also hard to reproduce but zoom in a few times (pretty close, like 5min range)
- Then the afterSetExtremes function gets in a loop with slightly different values
- seems like the loop continues until minRange is reached
See https://i.imgur.com/0lvO2QN.png

#### Product version
Highstock 7.0.3 

#### Affected browser(s)
All

#### Related issues
This issue is somewhat related to https://github.com/highcharts/highcharts/issues/8718 however datagrouping can be disabled and same behaviour

**Comment by KacperMadej** [comment]
Hi @faebuk 

Thank you for reporting about the problem.

1. Lack of navigator might be causing this - there's no reference to the first axis size because there's no series with such data, like in Highstock with navigator.

2. Use a single redraw to avoid the second problem:

```js
chart.series[0].setData(data.map((d) => [d[0], d[1]]), false);
    chart.series[1].setData(data.map((d) => [d[0], d[2]]), false);
    chart.series[2].setData(data.map((d) => [d[0], d[3]]), false);
    chart.redraw();
    chart.hideLoading();
```

3. Highstock - apply the above code (limit number of redraws) and the error is not showing.

4. 2nd for Highstock - I was unable to recreate this, but the code fix should help here. If not, please try to provide a step by step instruction for how to recreate the problem.

Please let me know if this helps with your problem or provide more info.

**Comment by faebuk** [comment]
Hi @KacperMadej 
Seems to work a bit better, thank you!

However there is another issue:
If you click the 1h button, the xAxis labels are gone, even if you change it back to "All". Can you have a look at this one too?

The other Bugs couldn't be reproduced yet with your code.

**Comment by KacperMadej** [comment]
@faebuk 
The another issue seems to be a bug.

**Minimal demo** (edited with minimal changes from one of the official demos): https://jsfiddle.net/BlackLabel/v9ncezw1/1/

**Bug description:**
Ticks are wrongly positioned for lazy loading demo when series type is area (or not column related).

**Steps to recreate:**
Click on `1h` and `All` button alternately until ticks will be gone.
Simple sequence of `1h` -> `All` shows the problem for me all the time.

**Workaround:**
Force additional axis redraw.

```js
    chart.redraw();
    chart.hideLoading();
    setTimeout(function(){
      chart.xAxis[0].isDirty = true;
      chart.redraw();
    }, 500);
```

The `500` delay is big and it's so only to show that this helps. Reduce the delay for smoother update animation.
Demo with workaround (based on your code @faebuk): https://codepen.io/Blacklabel/pen/MxEMrw

**Comment by pawelfus** [comment]
*Internal note:*
Simplified demo of the bug: http://jsfiddle.net/BlackLabel/0puwjsn7/ (without Highstock). 

Everything comes down to `series.threshold` option, which under certain circumstances forces xAxis to redraw (and re-render xAxis ticks and labels). For column (and related) series threshold is nullified. In Highstock, additional issue is related to `xAxis.ordinal` (no ticks at all), but most probably that's the same issue.
