### ISSUE TITLE
XAxis labels collapsed with Offline PDF Export

### ISSUE THREAD

**Issue by VBIManonmaniM** [highcharts/highcharts#10299]
#### Expected behaviour
When I exporting a chart with offline exporting library, xaxis label shpuldn't get collapsed 

#### Actual behaviour
But xaxis labels got collapsed with offline exporting but xaxis label not get collapsed with Export server of highcharts

#### Live demo with steps to reproduce
http://jsfiddle.net/bef6qr0m/3/

#### Product version

Highcharts

**Comment by VBIManonmaniM** [comment]
@nsdevaraj Please look into the issue.

**Comment by sebastianbochan** [comment]
Hi @VBIManonmaniM,
Thank you for reporting about the problem. When I export in offline / online version I always receive the result like in a chart.

![chart - 2019-03-12T102936 018](https://user-images.githubusercontent.com/2115686/54189776-ca468f00-44b2-11e9-9acf-24c83582f6d8.png)

Let me know about your browser details and please attach your results. Which size of chart do you use?

**Comment by VBIManonmaniM** [comment]
chrome 72.0.3626.121

**Comment by sebastianbochan** [comment]
Please attach your results. Which size of chart do you use?

**Comment by VBIManonmaniM** [comment]
Please find the Attached PDF using offline export
[chart.pdf](https://github.com/highcharts/highcharts/files/2956115/chart.pdf)

**Comment by sebastianbochan** [comment]
Thank you you for feedback. The solution is add the `useHTML` flag into `xAxis.labels` option.

**Demo:**
- http://jsfiddle.net/BlackLabel/dvoxp207/

@VBIManonmaniM please confirm if that this solution works for you.

**Internal note**
The bug is visible only in exporting to pdf.

FYI @oysteinmoseng
