### ISSUE TITLE
Default value of tooltip.followPointer property for scatter and bubble - docs

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10305]
For tooltip.followPointer doc says: 

> By default it behaves this way for scatter, bubble and pie series...
https://api.highcharts.com/highcharts/tooltip.followPointer

But only pie series has followPointer set to **true** by default.
Should be correct the docs or change the default behavior of scatter and bubble?

Bubble example: https://jsfiddle.net/BlackLabel/L20z3nax

#### Product version
7.0.3

**Comment by pawelfus** [comment]
Actually it's set to true for:
- sankey
- wordcloud
- map series
- polygon
- pie

Last version where `scatter.followPointer` (and bubble inherited this) was set to true: v3.0.10

**Comment by raf18seb** [comment]
So I assume that the docs should be changed?
