### ISSUE TITLE
Plot line events don't fire outside of initial Navigator range

### ISSUE THREAD

**Issue by shoebie22** [highcharts/highcharts#10302]
#### Expected behaviour
Plot line events should fire consistently across entire chart.

#### Actual behaviour
Plot line events don't fire for lines outside of the initial Navigator range

#### Live demo with steps to reproduce
https://jsfiddle.net/ajz7echp/4/

1.  Hover over black plot line at March 1, 2019.  Mouseover event fires correctly.
2.  Move Navigator to Sept 1, 2017.  Mousing over red plot line does not fire an event

#### Workaround
It seems like using the `to` and `from` fields (from plotBands) on each plotLine DOES cause the events to fire consistently. 

#### Product version
Highstock 7.0.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @shoebie22 

Thank you for reporting the issue.

Simplified demo (Highcharts):
https://jsfiddle.net/BlackLabel/mrzjf8h9/5/

*Internal note:*
It looks like we add events when creating a plotline, but we add elements to the DOM only when it's within the visible range.
