### ISSUE TITLE
No "Alt" property for the Graph (image)

### ISSUE THREAD

**Issue by v-khkuma** [highcharts/highcharts#10304]
**Expected behaviour**
Should have "Alt" property of the Graph (Image)

**Actual behaviour**
No Alt property if exposed

 **Product version**
Highcharts

**Affected browser(s)**
Chrome, IE, Edge

**Comment by TorsteinHonsi** [comment]
The Highcharts chart is inserted in the web page as an `<svg>` tag (not an `<img>` tag), which doen't require an `alt` attribute, so I'm not sure what you mean. Please elaborate.

**Comment by v-khkuma** [comment]
Suppose the code is like this: 
<rect x="40" y="40" width="40" height="40" fill="rgb(0,0,255)"  role="img"></rect>
where role=image, so is there option to add "Alt" attribute in this case. 
And if not then how will it describe the chart while narrator is used and focus will go there.

**Comment by pawelfus** [comment]
Hi @v-khkuma 

Do you use our Highcharts Accessibility module?
- docs: https://www.highcharts.com/docs/chart-concepts/accessibility
- API: https://api.highcharts.com/highcharts/accessibility

**Comment by v-khkuma** [comment]
I guess as per my requirement screenReaderSectionFormatter will be useful. Any suggestions?

**Comment by pawelfus** [comment]
@v-khkuma 

This is our bug tracker, if you have questions I suggest to contact our support: https://www.highcharts.com/blog/support/
