### ISSUE TITLE
chart#update isn't including lang.drillUpText

### ISSUE THREAD

**Issue by anathematic** [highcharts/highcharts#10309]
Hi team,
I'm having trouble updating the `drillUpText` dynamically in my chart - whilst my example isn't ideal (_why would you update the drillUpText this way?_) I figured it was a simple demonstration of the problem 😎

Thanks!

#### Expected behaviour

`chart.update` should include updating properties in the `lang` object.

#### Actual behaviour

Function appears to ignore `lang.drillUpText` property

#### Live demo with steps to reproduce
https://jsfiddle.net/anathematic/vrs6egcf/2/

#### Product version
Highcharts v7.0.3

#### Affected browser(s)

Only tested on Chrome.

**Comment by pawelfus** [comment]
Hi @anathematic 

Thanks for reporting the issue. `lang` options (and `global`) are settable only by: `Highcharts.setOptions({ lang: { ... } , global: { ... } })`, as described in our API: https://api.highcharts.com/highcharts/

When you call `chart.update({ ... })` you should use **chart options**, where `lang` is not listed. If you want to change some global options (e.g. lang), then you need to call `Highcharts.setOptions()` then recreate the chart.

**Comment by anathematic** [comment]
Hi there,
Thanks for that prompt reply (I'm sorry the weekend took over my response!).

In that case I'll need to find another way to dynamically update our `lang.drillUpText` - that's definitely not a Github issue so I'll close this. Thanks!
