### ISSUE TITLE
Highchart stock slow when update yAxis with update function

### ISSUE THREAD

**Issue by viethien** [highcharts/highcharts#10316]
#### Expected behaviour
I have a series real time data of multiple source. I want to switch from single yAxis to multiple yAxis but when i change to multiple yAxis, it slow.

#### Actual behaviour

I tried show yAxis by this method
yAxis.update({
                            visible: true,
                            opposite: true,
                            labels: {
                                rotation: 270
                            }
                        });

Each update function take about 200ms with 300 point data, it increase if number of point data is increased.

So if i have 20 tags, it will be about ~ 4 second to switch axis, I use for to update each yAxis

#### Product version

I use Highstock Angular library

**Comment by sebastianbochan** [comment]
Hi @viethien,
Thank you for reporting. Do you use our official angular wrapper? Could you simplify you chart and setup a live demo? It will allow us to debug.

**Comment by sebastianbochan** [comment]
Closed due to inactivity. Please reopen the ticket when new details will be available.
