### ISSUE TITLE
Printing changes the original chart dimensions ratio

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#10313]
#### Expected behaviour
Columns should't overlap in print version of the chart.

#### Actual behaviour
They do. I seems that the exporting module changes container's ratio of width to height.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/k9w5tbmc/
Click context menu > _Print chart_.

#### Product version
7.0.3

**Comment by pawelfus** [comment]
This is caused by setting fixed `pointWidth` and not changing [`exporting.printMaxWidth`](https://api.highcharts.com/highcharts/exporting.printMaxWidth). Fixed demo: http://jsfiddle.net/BlackLabel/k9w5tbmc/11/
