### ISSUE TITLE
Packed Bubble Overlaping With 2 Bubbles of the Same Size

### ISSUE THREAD

**Issue by jrae26** [highcharts/highcharts#10325]
#### Expected behaviour
Two bubbles of the same size are plotted at different positions

#### Actual behaviour
Bubbles are overlapping

#### Live demo with steps to reproduce
If you toggle series 2/3 on/off you can see the two separate bubbles during the animation.  This seems to work fine if I combine all of my points into one `packedbubble` type series but I need separate series for coloring purposes.

https://jsfiddle.net/o7fkun9r/

#### Product version
Highcharts 7.0+

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @jrae26 

I'm unable to recreate the problem. Maybe width of the chart needs to be hard-coded or maybe some browser + OS is required - what have you used? (Tested on Chrome / Win7)

We're preparing an update for the packed bubble series with 7.1.0, so this problem might be already resolved. We're in a middle of merging branches, so I'll post a link for test when it will be done (few days at most, probably).

If you just needs different colors then you could use `colorByPoint` - demo: https://jsfiddle.net/BlackLabel/ar0d2gun/

**Comment by jrae26** [comment]
Hi @KacperMadej 

Thank you for the swift reply! I tested on Chrome v62 / Windows 10.  After seeing your reply I went back and tested on a Mac (Chrome and Firefox) and did not encounter the issue.  Below is what I am seeing:

https://ibb.co/7pXJj51

Thank you for the tip regarding `colorByPoint`! I must have missed that my first time through.  I have switched to using that with a single data series and it has resolved the problem.

**Comment by KacperMadej** [comment]
That's an old Chrome, so it might be the problem.
I'm unable to recreate the problem, so it's either old Chrome related issue or specific chart width is required.

Let's wait for v 7.1 release and maybe the problem will be resolved with the packed bubble series update.

**Comment by jrae26** [comment]
@KacperMadej I have updated to the latest version of Chrome and it has fixed the problem.  Thank you for your assistance!
