### ISSUE TITLE
Gantt - grid cellHeight doesn't work. 

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#10324]
Gantt - on xAxis it's impossible to change the height of cells by using **grid.cellHeight** feature.  

#### Live demo with steps to reproduce

[Demo](https://jsfiddle.net/BlackLabel/vxj4Lshe/)

#### Product version

Highcharts JS v7.0.3

#### Affected browser(s)

All

**Comment by KacperMadej** [comment]
+1
