### ISSUE TITLE
Data module parses all dates as local

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#10322]
#### Expected behaviour
To detect whether they are local or UTC. 

#### Actual behaviour
Always local.

#### Live demo with steps to reproduce
* Minimal demo: http://jsfiddle.net/highcharts/2scbLq5e/

#### Product version
7.0.3

#### Discussion
Responsible code:
https://github.com/highcharts/highcharts/blob/f0d795ebc1308b228898404f943e1dee0645865b/js/modules/data.src.js#L1867-L1880

In order to fix this, we must do it conditionally so that we still parse date strings without timezone information as local dates. We must add a check for whether timezone information exists in the string, for example `2018-03-13T17:00:00+00:00`, `2018-03-13T17:00:00Z`, `2018-03-13T17:00:00 CET` or `2018-03-13T17:00:00 GMT-0400`. It is complex and not standardized.

**Comment by bre1470** [comment]
The browser offset could be detected like this:
```
parseInt((new Date('1970-01-02T00:00:00Z')).toTimeString().substr(0,2))
```
The direction (positive/negative) like this
