### ISSUE TITLE
Zooming on timeline series

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#10323]
#### Expected behaviour
Zooming should work

#### Actual behaviour
1. Set extremes on the X axis doesn't work
2. When fixing that by removing the code in `processData` that modifies the X axis, the connectors don't show up for new data labels.

#### Live demo with steps to reproduce
http://jsfiddle.net/highcharts/wuc1xfgp/3/

#### Product version
Pre-release

This code block is problematic:
```
                // Adjust axis extremes to currently visible points.
                if (!series.chart.resetZoomButton) {
                    xAxis.min = visiblePoints[0].x;
                    xAxis.max = visiblePoints[visiblePoints.length - 1].x;
                }
```
@Denyllon Can you show the use case that requires the min and max of the X axis to be modified? We should probably resolve it in a different way. 

The second problem is that it has a condition for the `resetZoomButton`, which is only one of several ways of zooming on an axis. A more solid way would be to look for `xAxis.userMin` and `xAxis.userMax`. But ideally I would prefer not having to modify the X axis this way.

**Comment by leenooks** [comment]
I'm not sure this has been fixed (the connector not appearing when zooming). I'm trying it out on your fiddle on your website - and when you zoom in to points (that are not shown unzoomed because `overlap` is `false`) - the connector to the box is not showing when zooming (although the box is appearing).

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series-timeline/datetime-axis

**Comment by KacperMadej** [comment]
Thank you for reporting about the problem @leenooks 

Steps:
1. zoom into hidden labels
2. labels are shown, but there's no visible connector (opacity set to 0)

From short debugging: looks like `point.dataLabel.opacity` used for the connector opacity is from before the zoom

fyi @Denyllon

**Comment by leenooks** [comment]
BTW: I just noticed if you zoom in to the "first" zoom, the connector is not shown. But if you zoom in further (even to the same full area), the connector is shown on the second zoom.
