### ISSUE TITLE
Tooltip formatter return type incorrect

### ISSUE THREAD

**Issue by meriahoneil** [highcharts/highcharts#10326]
#### Expected behaviour
Should be able to return string, boolean, or array (based on documentation)

#### Actual behaviour
FormatterCallbackFunction only returns string

#### Product version
v7

**Comment by KacperMadej** [comment]
Hi @meriahoneil 

Thank you for finding this and notifying us about it.
This is a documentation error - the code works fine.

**Comment by sebastianbochan** [comment]
FYI @bre1470

**Comment by bre1470** [comment]
It is merged into the branch of the next version
