### ISSUE TITLE
Overlapping data in Gauge

### ISSUE THREAD

**Issue by topn0tch** [highcharts/highcharts#10321]
I have this issue where suddenly the data is overlapping each other. 
Any ideas on how to fix this? 

#### Expected behaviour
![image](https://user-images.githubusercontent.com/19737717/54415907-15081700-46fe-11e9-8bff-2f87c5b136b2.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/19737717/54415936-23eec980-46fe-11e9-93fe-180529da9887.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/dzxh79bm/
https://jsfiddle.net/ozg84cbs/

You can see here that changing the data numbers, suddenly fixes it. 
https://jsfiddle.net/ozg84cbs/1/
Only numbers have been changed.

#### Product version
Latest

#### Affected browser(s)
Any

**Comment by sebastianbochan** [comment]
Hi @topn0tch,
Thank you for reporting about the problem. It looks like a problem with rounding edges. Without it works properly.

**Internal note**
It looks like "size of round" is not included in panes properly.

Lets compare two scenarios:
- https://jsfiddle.net/BlackLabel/epdLza82/ (no round) -> correct
- https://jsfiddle.net/BlackLabel/06czrj7d/ (round) -> wrong

**Comment by TorsteinHonsi** [comment]
Maybe off topic, but it looks like the OP here is trying to do something that the solid gauge was not designed for.

The required chart looks more like a donut chart with some modifications. With a little plugin to the pie series type, and borrowing the solid gauge's extended `arc` function, it works well: 

https://jsfiddle.net/highcharts/06ashdkn/
