### ISSUE TITLE
.NET Wrapper does not camel case plotShadow properties

### ISSUE THREAD

**Issue by Jmaharman** [highcharts/highcharts#10336]
#### Expected behaviour
To be able to set the shadow property of the chart using the .NET wrapper.

#### Actual behaviour
The values are set, but they are not serialized correctly for JS and come out as PascalCase, not camelCase.

#### Live demo with steps to reproduce
Set the Chart.PlotShadow using the .NET wrapper
![image](https://user-images.githubusercontent.com/215359/54534888-3f1f3a80-4985-11e9-9994-0ebc97e8e7ff.png)
On outputting the JS on the page you will see the properties of Shadow are PascalCase not camelCase.
![image](https://user-images.githubusercontent.com/215359/54534755-f49dbe00-4984-11e9-99e9-28fc287bd2f9.png)

#### Product version
7.0.3 through nuget

#### Affected browser(s)
All

#### Work around
The values we wanted were global, so we set those properties globally via Highcharts.setOptions

**Comment by sebastianbochan** [comment]
Hi @Jmaharman,
Thank you for reporting about the problem. Our .NET developer will post an answer as soon as possible.

**Comment by Jmaharman** [comment]
Was this issue resolved @brofixo ?

**Comment by brofixo** [comment]
That is correct.

śr., 26 sie 2020, 10:38 użytkownik John Harman <notifications@github.com>
napisał:
