### ISSUE TITLE
Highstock GUI issue

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#10332]
After drawing a segment line and moving end point whole chart area is selected. 

#### Live demo with steps to reproduce

[Gif which shows the issue](https://imgur.com/ao9CWwD)
[Demo to test it](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui/)

#### Product version

Highstock JS v7.0.3

#### Affected browser(s)

All

**Comment by pawelfus** [comment]
**Workaround:**
Disable text selection in CSS:

```
#container {
  -webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Safari */
     -khtml-user-select: none; /* Konqueror HTML */
       -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* Internet Explorer/Edge */
            user-select: none; /* Non-prefixed version, currently
                                  supported by Chrome and Opera */
}
```

Demo: https://jsfiddle.net/BlackLabel/asy3cm1w/2/
