### ISSUE TITLE
HTML tooltips don't fade on mouseout when using range selector

### ISSUE THREAD

**Issue by shoebie22** [highcharts/highcharts#10342]
#### Expected behaviour
Tooltips fade when the mouse leaves the plot area

#### Actual behaviour
After a ranges selector button w/ dataGrouping has been selected, the tooltip text never fades from the chart even after mouseout.

#### Live demo with steps to reproduce
https://jsfiddle.net/n39dswLe/

1.  Select 1 month (no dataGrouping).  Mouse over and out of chart, tooltip displays correctly.
2.  Select 3 months (dataGrouping IS specified).  mouse over and out of chart, tooltip text remains

The bug seems to occur under the following conditions:
1.  tooltip useHTML = true
2.  tooltip formatter is configured
3.  active range selector button has a dataGrouping object specified.

Unless all  3 of the above are true, I can't repro the bug

#### Product version
Highstock 7.0.2

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @shoebie22,
Thank you for contacting us. 

Have you tried to update your Highstock to the newest version v7.0.3 ? 

Unfortunately I was not able to reproduce it in Chrome and FF.

MacOSX: 10.12.4
Chrome: 73.0.3683.75
FF: 65.0.1

**Comment by shoebie22** [comment]
Thanks for reviewing @sebastianbochan.

I updated to Chrome 73.0.3683.75 and tried in Incognito mode, still found the buggy behavior.  See below:
![highstock_tooltip](https://user-images.githubusercontent.com/2263262/54630992-4bb09b00-4a38-11e9-9dcf-3876f08fc880.gif)

The demo is using highstock.js from the Highcharts CDN, which I assume is the latest version 7.0.3.

**Comment by sebastianbochan** [comment]
Hi @shoebie22,
Thank you for feedback. Now I was able to reproduce the problem.

**Internal note**
It looks like regression since v6.0 and seems to be related with two issues:
- https://github.com/highcharts/highcharts/issues/6957
- https://github.com/highcharts/highcharts/issues/7180

**Comment by TorsteinHonsi** [comment]
The problem appears when the formatter returns a string and we're using `split` tooltip.

#### Workaround
Set `tooltip.split` to `false`: https://jsfiddle.net/highcharts/0a2qroz6/

**Comment by TorsteinHonsi** [comment]
Simplified demo:
http://jsfiddle.net/highcharts/e14k83mL/
