### ISSUE TITLE
Highcharts 7 typescript declaration: pointDescriptionFormatter should return a string but is declared as "()=>void"

### ISSUE THREAD

**Issue by hojovi** [highcharts/highcharts#10345]
#### Expected behaviour
pointDescriptionFormatter function should return a string(based on its comment)

#### Actual behaviour
pointDescriptionFormatter function is decalared to return void

#### Source code
![image](https://user-images.githubusercontent.com/5494895/54577696-c75e1800-4a37-11e9-81a3-11685abb6c65.png)

#### Product version

7.0.3

**Comment by hojovi** [comment]
There're other places where the declarations mismatch with comments.

**Comment by sebastianbochan** [comment]
Hi @hojovi,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by hojovi** [comment]
@bre1470 Is there any way to hacky fix this in the current version? Or could you share when the fix version will be published? Thanks!

**Comment by bre1470** [comment]
@hojovi 
Yes. As described in our [documentation](https://www.highcharts.com/docs/advanced-chart-features/typescript), you can extend Highcharts with modified declarations yourself. For this case it would look like this:
```ts
declare module 'highcharts' {
    interface AccessibilityOptions {
        pointDescriptionFormatter?: (() => void|(context: Point) => string)
    }
}
```
But Actually it should not be necessary. `() => void` includes every possible function, so you can set the option simply with an more advanced function like this:
```ts
accessibility: {
    pointDescriptionFormatter: (context: Highcharts.Point) => {
        return 'My point description';
    }
}
```

**Comment by hojovi** [comment]
@bre1470 Thank you very much!
The 2nd solution works as expected, but the 1st solution seems not working, I got this error when I tried to redeclare this property.
![image](https://user-images.githubusercontent.com/5494895/54972664-8b8ef980-4fc7-11e9-8ad2-4735652b7657.png)

**Comment by bre1470** [comment]
@hojovi 
I am sorry for the mistake. Unfortunately the first suggestion is not working, so only the second suggestion solves it in the meantime. Thank you for the feedback.
