### ISSUE TITLE
Highcharts.SVGRenderer#button cannot use HTML

### ISSUE THREAD

**Issue by BigDrums00** [highcharts/highcharts#10360]
#### Expected behaviour
Pass HTML into text argument and have it render in button.
(documentation states "The text or HTML to draw.")

#### Actual behaviour
HTML is replaced with svg elements

#### Live demo with steps to reproduce

http://jsfiddle.net/9fmv1p7s/1/

#### Product version

Highcharts 7.0.3

#### Affected browser(s)
All

If the documentation is correct, the issue looks to be where label is generated in button method, useHTML is null and cant be set.

**Comment by sebastianbochan** [comment]
Hi @BigDrums00,
Thank you for reporting about the problem.

As a workaround you can use `renderer.label`

```
chart.renderer.label(
            "<div class='blue'>Hello <span class='red'>People</span></div>",
            point.plotX,
            point.plotY,
            'button',
            null,
            null,
            true
        ).add();
```

Demo:
- http://jsfiddle.net/BlackLabel/c8dopybv/

**Internal note**
The `renderer.button` uses `renderer.label` but ignores the `useHTML` flag.

I will fix it as soon as possible.
