### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [highcharts/highcharts#10362]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by sebastianbochan** [comment]
Hi @gustavosizilio,
Thank you for contacting us. Github is our bug tracker so for general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.
