### ISSUE TITLE
Can we have dataLabel position for semicircle donut to change dynamically?

### ISSUE THREAD

**Issue by ask3341** [highcharts/highcharts#10374]
#### Expected behaviour
To have Data label (Slice) at end of green color.

#### Actual behaviour
Showing in the center of green color

#### Live demo with steps to reproduce

http://jsfiddle.net/akhil1993/Lktrz5hp/10/

**Comment by sebastianbochan** [comment]
Hi @ask3341,
Thank you for reporting about the problem. It is not a bug, so for general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

ps. As a workaround you can disable `dataLabels` and use [renderer.text](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#text) to place label anywhere.
