### ISSUE TITLE
event click on boosted charts doesn't bubble on iphone

### ISSUE THREAD

**Issue by TheGreatYamcha** [highcharts/highcharts#10390]
We've wrapped a line chart in an anchor (`<a>`), so that clicking on the series would take you to the anchor link. This works everywhere, except on iphone, **when the chart is boosted**.
My guess is the click event isn't bubbling to the anchor.

#### Expected behaviour
Clicking on the chart (inside an anchor) should call the anchor's href. Again, this works everywhere, except on boosted charts on iphone.

#### Actual behaviour
Instead nothing happens. The tooltip does show though.

#### Product version
Latest Highcharts
#### Affected browser(s)
iphone (ios 12, both Chrome and Safari)
Works fine on Android and desktop.

**Comment by sebastianbochan** [comment]
Hi @TheGreatYamcha,
Thank you for reporting about the problem. I created the simple demo here: https://jsfiddle.net/BlackLabel/01xvrgty/3/ and it looks like that also does not work on desktop. Could you update my example with your code to debug in different devices?

**Comment by TheGreatYamcha** [comment]
your example works fine in chrome (desktop and Android). It also doesn't do anything on iphone (safari) as I mentioned, other than showing the tooltip.
Google has x-frame enabled, so it refuses connection:
![image](https://user-images.githubusercontent.com/10838193/54839503-38940a00-4c88-11e9-909f-13eabf54d8eb.png)
Setting the link to something else should work:
https://jsfiddle.net/c0k14vxr/

**Comment by TheGreatYamcha** [comment]
@sebastianbochan is this still "Pending Reply"?

**Comment by sebastianbochan** [comment]
Hi @TheGreatYamcha,
I apologize for late reply (the first notification was missing). 

When I run the demo: https://jsfiddle.net/BlackLabel/vjpfbq5n/1/ I am able to click on chart and website is opened. Could you confirm? 

iOS 12.1.4

**Comment by Basts** [comment]
Hi @TheGreatYamcha @sebastianbochan ,

I have tested the demo sent by Sebastian and everything worked fine - chart was rendered perfectly and after click on the chart, the website was opened. I can't reproduce the issue which you have reported. 

Tested on iOS 12.1.4.

**Comment by TheGreatYamcha** [comment]
@sebastianbochan 
I can confirm that your demo works. **However**, you are using `target="_blank"` , without this (target=_self) it doesn't work.
check my demo again:
https://jsfiddle.net/c0k14vxr/
make sure you click on the actual series (clicking the labels seem to work fine).
I suspect this might have to do with the fact that in boost, the svg has an `href`, which I think might be interfering with the anchor's href.
What's even more interesting is if I set a breakpoint on "touchDown" event on the svg, it works fine!! but if I disable the breakpoint, it doesn't.

**Comment by sebastianbochan** [comment]
Hi @TheGreatYamcha,
The issue was caused also in desktop version due to https conflict. The main url uses SSL (https://jsfiddle...) but url in `<a>` does not. When I correct it, all works properly.

See demo:
- https://jsfiddle.net/BlackLabel/tcqbkw9L/show

**Comment by TheGreatYamcha** [comment]
I couldn't reproduce the issue in jsfiddle (everything is fine).
But in my application, it wasn't working properly. Believe it or not, iOS 12.2 dropped a few days ago and solved the issue.

**Comment by sebastianbochan** [comment]
Thank you for the feeback.
