### ISSUE TITLE
Scatter3D displays nothing for 2k+ data points

### ISSUE THREAD

**Issue by marco-boeck** [highcharts/highcharts#10405]
#### Expected behaviour
Scatter3D displays a chart with ~2k or more data points.

#### Actual behaviour
Scatter3D does not display data points and also no error messages. It is just empty.

#### Live demo with steps to reproduce
https://jsfiddle.net/5yzok21b/

#### Product version
Highcharts 7.0.3

#### Affected browser(s)
All browsers (tested against latest version of Chrome, Firefox, Edge)

**Comment by pawelfus** [comment]
Hi @marco-boeck 

Thanks for reporting the issue! 

**Workaround:**
Set `series.turboTreshold`, demo: https://jsfiddle.net/BlackLabel/gubhv9mp/
