### ISSUE TITLE
Define breaks in navigator series with Gantt

### ISSUE THREAD

**Issue by straaand** [highcharts/highcharts#10407]
Not sure if this is a bug, it's not supposed to work this or if I'm doing something wrong.

#### Expected behaviour
Defining a break for the yAxis series in the navigator used together with a gantt chart does not work. 
The following should "skip" row 1 and 2 in the navigator for a Gantt chart with a total of 6 rows.
`        yAxis: {
            min: 0,
            max: 5,
            reversed: true,
            categories: [],
            breaks: {
            	from: 1,
              to: 2
            }
        }
`

See JsFiddle for full implementation.

#### Actual behaviour
Two empty rows ends up in the navigator.

#### Live demo with steps to reproduce
https://jsfiddle.net/a53rxyp2/

#### Product version
Highcharts Gantt 7.0.3

#### Affected browser(s)
Chrome 73

**Comment by pawelfus** [comment]
Hi @straaand 

Thanks for reporting the issue. It looks like in general broken yAxis in Gantt chart is not supported. Setting breaks for the main yAxis doesn't change a thing: https://jsfiddle.net/BlackLabel/ns9Ly4o5/4/ 


*Internal note:*
I guess it's connected to GridAxis, basic xrange+yAxis are fine: https://jsfiddle.net/BlackLabel/zh9opdbv/9/
