### ISSUE TITLE
Range selector input fields shown over export menu

### ISSUE THREAD

**Issue by romant-1** [highcharts/highcharts#10404]
This issue has been already reported, and possibly fixed, in #4457.
Unfortunately, the same problem is currently present in the 7.0.3 version.

steps to reproduce:
[http://www.highcharts.com/stock/demo/areasplinerange](http://www.highcharts.com/stock/demo/areasplinerange)
Just click one of the range selector input fields, tab away and open the export menu - the input fields will be on top of the export menu as reported originally.

**Comment by pawelfus** [comment]
Hi @romant-1 

Thanks for reporting this regression! 

*Internal note:*
Bisect lead to: 793866c5e

**Comment by sebastianbochan** [comment]
**Internal note**
I recovered test from this commit: https://github.com/highcharts/highcharts/commit/bf1dddf194fe3a7c31687fdb0b7991aef86bf04c to test #4730 case. It worked, but with current code:

```
                updateExtremes();
                rangeSelector.hideInput(name);
                input.blur(); // #4606
```

it works properly without condition. As a result it fixes #10404, #4710, #4606.

@TorsteinHonsi any ideas if there is something more which I should consider?

**Comment by TorsteinHonsi** [comment]
> any ideas if there is something more which I should consider?

I can't think of anything, so if this resolves the issues then go for it 👍

**Comment by TorsteinHonsi** [comment]
@sebastianbochan Unfortunately I had to revert this, as the CI test broke in Firefox. It seems like the branch was created before we set up CI, and Circle didn't run on the branch before merging into master.
