### ISSUE TITLE
Shared tooltip and 'split' option doesn't work properly.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#10406]
#### Expected behaviour
The `tooltip.shared` and `tooltip.split` options should also work with Gantt chart, but both parameters are not even available in API documentation.

#### Actual behaviour
Using `tooltip.shared`set to `true` causes throwing the error in console.
```
Uncaught TypeError: Cannot read property 'series' of undefined
    at a.Tooltip.refresh (highcharts-gantt.src.js:22359)
```

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/Lp97yu1w/
1. Hover on any of points.
2. Open the browsers console to see the error.

**Comment by sebastianbochan** [comment]
FYI @jon-a-nygaard
