### ISSUE TITLE
Funnel datalabels left align

### ISSUE THREAD

**Issue by deepakkoirala** [highcharts/highcharts#10401]
#### Expected behaviour
How do I keep all the data labels in funnel on left side ?

#### Actual behaviour
All data labels are coming on right side.  I kept datalabels.x and kept -450. The items are coming on left side but alignments are messed up. And the softconnector are on right side.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/funnel

#### Product version
highcharts 6.0.4

#### Affected browser(s)
Chrome, Firefox

**Comment by pawelfus** [comment]
Hi @deepakkoirala 

Please use `dataLabels.position` ("left"|"right") and change `center` option (to make more space on the left side): https://jsfiddle.net/BlackLabel/6z210jnx/1/

*Internal note:*
`dataLabels.position` is not listed in our API, we should add this.
