### ISSUE TITLE
 Multi - axis rendering exception

### ISSUE THREAD

**Issue by xuexiaobin5** [highcharts/highcharts#10409]
#### Expected behaviour
After double-clicking a legend in the upper left corner, the chart's vertical axis and the chart display are inconsistent with the initial rendering.

#### Live demo with steps to reproduce
https://jshare.com.cn/xuexiaobin/4FPvxk/1

#### Product version

v7.0.3

**Comment by pawelfus** [comment]
Hi @xuexiaobin5 

Thanks for reporting the issue, however I'm not able to recreate the issue (your demo is not working). I used the same dataset in jsFiddle and it looks fine: https://jsfiddle.net/BlackLabel/k3dpe179/2/

I assume this is the issue with different xAxis extremes? If that's the case, then it's correct, initial extremes might be different from the extremes after chart interactions (legend click, browser resize etc.). You can find more details in related issues: #5628 and #4535

**Comment by wenhui-prudencemed** [comment]
Hi @pawelfus ,
I create the demo in jsfiddle to reproduce this issue:
https://jsfiddle.net/q10atknp/

the test5 series highest value is 2051, but the max axis value for test5 series is 2800.

if you unselect test1 and then select test1 again, it looks correct (the max axis value for test5 is 2400 now), which is more makes sense.

here is the screenshot: https://imgur.com/a/D8Xnebw

Thanks,
Wenhui

**Comment by sebastianbochan** [comment]
Hi @wenhui-prudencemed,
The issue is related with missing `alignTicks` param. 

Demo:
- https://jsfiddle.net/BlackLabel/r1xfoqps/

Let me know if it worked like you expect.

**Comment by wenhui-prudencemed** [comment]
Hi @sebastianbochan ,

So when the initial loading, it aligns second axis(test 5) to first axis(test 1), and when I disable test 1 and enable it again, it aligns first axis(test 1) to second axis(test 5).
This makes the result different, am I right?

Thanks,
Wenhui

**Comment by pawelfus** [comment]
Ok, I needed different height of the chart to recreate the issue: https://jsfiddle.net/BlackLabel/m3awp1v8/

In general, as I said earlier, initial rendering may be a bit different from rendering after chart interactions. When creating chart, we reserve some space for items (e.g. axis labels, title, legend etc.). After initial rendering we have elements "in place" so calculations are more accurate. You can see that no matter how many times you hide/show "test 1" the result is always the same.
