### ISSUE TITLE
Need scroll bar for HighStock advanced indicators 

### ISSUE THREAD

**Issue by rkarlberg** [highcharts/highcharts#10403]
#### Expected behaviour
On this stock demo, the advanced indicators dialog has many indicators to choose from, but you can only see a few listed - there needs to be a scrollbar here.

#### Actual behaviour
List gets cut off

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/stock-tools-gui

#### Product version
Highstock 7.0

#### Affected browser(s)
Chrome

**Comment by rkarlberg** [comment]
I tried to create both a Codepen and Fiddle from this demo, but they show up blank, which is also strange...

**Comment by sebastianbochan** [comment]
Hi @rkarlberg,
Thank you for reporting. The bug is known issue and has been already fixed in our master branch.

Im closing the issue as duplicate of https://github.com/highcharts/highcharts/issues/9988

**Comment by rkarlberg** [comment]
Ok, great to know, thanks!
