### ISSUE TITLE
Chart BackgroundColor does not change YAxes' background 

### ISSUE THREAD

**Issue by SSJ2912** [highcharts/highcharts#10416]
**Expected behaviour**
Chart backgroudColor with alpha value as 0 should change the plotArea as well as the Axes pane. 

**Actual behaviour**
For ScrollablePlotArea, setting chart backgroudColor with alpha value as 0 changes the plotArea but not the Axes pane.

**Live demo with steps to reproduce**
I have reproduced the issue in the link below
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea

**Product version**
version 7.0.3

**Comment by sebastianbochan** [comment]
Hi @SSJ2912,
Thank you for reporting about the problem. 

Simplified demo:
- https://jsfiddle.net/BlackLabel/cg026Lv1/

**Workaround:**
Remove fill from `highcharts-scrollable-mask`.

Demo:
- https://jsfiddle.net/BlackLabel/sp6b75zn/

**Comment by SSJ2912** [comment]
Chart is unable to scroll when using `highcharts-scrollable-mask`. Is there any way to solve it?

**Comment by sebastianbochan** [comment]
Hi @SSJ2912,
I apologize for incorrect demo, the fill should be reset by CSS styles.

Could you confirm that now worked properly?

**Comment by SSJ2912** [comment]
Could you please explain me, what do you mean by resetting fill by CSS styles?

**Comment by sebastianbochan** [comment]
I mean set transparent color by CSS:

```
.highcharts-scrollable-mask {
  fill: rgba(0,0,0,0);
}
```

https://jsfiddle.net/BlackLabel/ehm23xa9/
