### ISSUE TITLE
Stacked column chart not showing all data points

### ISSUE THREAD

**Issue by langen** [highcharts/highcharts#10412]
#### Expected behaviour
Stacked column chart should show stack slice for each data point in the series.

#### Actual behaviour
Some data points are missing from the stack, resulting in gaps in the stack or inaccurate stack size

#### Live demo with steps to reproduce
An example can be found here, https://jsfiddle.net/slangen/pe7qsxay/17/
Although this example results the in the problem reported here, https://github.com/highcharts/highcharts/issues/10160.  When manually testing with the fixed committed for the earlier issue (10160) there are no console errors, but rather gaps in the stacks (see attached image).  Note the data point for category 7995180, ID = 1000000007 is missing and shows a gap in the stack.

#### Product version
6.0.7

#### Affected browser(s)
Chrome Latest

**Comment by langen** [comment]
![image](https://user-images.githubusercontent.com/4227846/54950036-68ecda00-4f0e-11e9-823c-79387df9d1bb.png)

**Comment by ppotaczek** [comment]
Hi @langen, Thank you for reporting!

This problem is related with stacking points without names in `category` axis type. 
Simplified example: https://jsfiddle.net/BlackLabel/acezjxfw/

To workaround use only the `categories` property: https://jsfiddle.net/BlackLabel/bew75yz6/

    "xAxis": {
        //"type": "category",
        "categories": [
            "7995180",
            "896267",
            "7098913"
        ]
    },

Best regards!

**Comment by langen** [comment]
Thank you, that work around appears to work.
