### ISSUE TITLE
Highcharts 7 accessibility: Internationalization

### ISSUE THREAD

**Issue by hojovi** [highcharts/highcharts#10415]
I've noticed the API document didn't contain more detailed properties on chart anymore, such as "screenReaderRegionLabel", "navigationHint", they're assigned literal constants in "a11y-i18n.src.js" file.

Does this mean it's deprecated to set these properties by the developer? This could be a problem when we try to do internationalization on this part for my project.

**Comment by sebastianbochan** [comment]
Hi @hojovi,
Thank you for reporting.

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
There seems to be an issue with our API docs. All of the text set in the `a11y-i18n` file can be set in the [lang.accessibility](https://api.highcharts.com/highcharts/lang.accessibility) options, just as before. We will look into what has happened with our API docs and push a fix soon.

**Comment by hojovi** [comment]
@oysteinmoseng Is it possible to add typescript support for this part? Current definition on lang.accessibility is simply object.

**Comment by sebastianbochan** [comment]
FYI @oysteinmoseng @bre1470

**Comment by oysteinmoseng** [comment]
What do you think @bre1470?

**Comment by bre1470** [comment]
If it shows up in the online documentation it should also get automatically into the declaration. At the moment I can not confirm that it is the case.

**Comment by bre1470** [comment]
Confirmed: `LangAccessibilityOptions` interface gets created.
