### ISSUE TITLE
addPoint() does not return point

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/highcharts#10413]
The one-liner `return point;` is missing from addPoint() so it returns nothing. Please hear out my use-case:

Since there is no way to toggle visibility of categories, I must remove the points manually to "hide" them. If storing the added points were possible:

#### Expected behaviour
```
// Adding data
let points = [];

for (let value of category1.data) {
   // Store the added point!!
   let point = series.addPoint({
      name: 'Category 1',
      y: value
   });

   points.push(point);
}
```

Then I would be able to do this:

```
// Hiding a category
for (let point of points) {
   point.remove();
}
```

#### Actual behaviour
But instead I have to iterate through the entire series to find the points to remove for one category:
```
for (let points of series.points) {
   if (point.name === 'Category1') {
      point.remove();
   }
}
```

#### Live demo with steps to reproduce
https://jsfiddle.net/lanimelrok/1b6z8vqk/

Looking at the source code, it looks like just a one-liner to return the point. Could we please return the added point so that I won't have to iterate through possibly hundreds of points in a series just to delete a few? Thank you so much for your understanding. 

https://github.com/highcharts/highcharts/blob/891c59ae75d8118a6da7bd2e0efb90d16c599c03/js/parts/Dynamics.js#L825-L897

**Comment by pawelfus** [comment]
Hi @LaniMoo 

Thanks for sharing the idea! I agree with you, it would be useful to get that point. Just like we do with `addSeries` and `addAxis`.

**Comment by LaniMoo** [comment]
Wonderful!! Thanks for your understanding, @pawelfus!!!!

**Comment by LaniMoo** [comment]
Bummer, I see it got reverted. Any chance `return point;` will be added back any time soon? Thanks!

**Comment by pawelfus** [comment]
No ETA @LaniMoo - we will try to add this in the next release.

**Comment by TorsteinHonsi** [comment]
The reason we're not returning the point is that there are cases where a `Point` object is actually not generated. For example, in a Highstock chart with data grouping, when running `addPoint` adds the point _configuration_ to a list, but `Point` instances actually reflect groups of data points. So there is no guarantee that when you run `addPoint` it will result in a `Point` instance.

Another case is if we have a chart that is zoomed to, say X values 0-500. If you add a point at x=1000, we don't generate a `Point` instance until the user zooms out to see it. 

Bottom line, as a CPU/memory optimization, `Point` instances are only created when needed.

I see two viable solutions:

1. Return the index of the point. This lets you look up the point by `series.points[index]`, or run `series.removePoint(index)` directly. A caveat is that indexes may change as other points are added or removed. See [this demo](https://jsfiddle.net/highcharts/x4L58vtk/), where the indices are mapped to Points immediately after generation.
2. Supply a callback to run when the point is actually generated. This is perhaps a bit more complicated to implement, but avoids the problem of keeping track of changing indices.

@pawelfus

**Comment by TorsteinHonsi** [comment]
Or a third solution could be to either add a series event on point generated, or refactor the existing `addPoint` to not run until there's an actual `Point` instance to pass over.

**Comment by pawelfus** [comment]
Thanks for the details! Yup, that makes sense now. How about simply returning `undefined` when actual point was not created? I think potential issues with `index` are not worth implementation.

This suppose to be a simple fix, but given the complexity of the issue, we may delay this. Honestly, this sounds more like a promise use case. We can try to implement something similar (like your other proposed solutions), but I'm not sure if it's worth it.

**Comment by TorsteinHonsi** [comment]
I agree returning a promise would be the most natural solution. Returning the index would help, but  would need to come with a warning. Maybe it's best to leave it for now, as the points can already be found using `id`.
