### ISSUE TITLE
The dipendency arrow is drawn by key-shaped line

### ISSUE THREAD

**Issue by hiroko3** [highcharts/highcharts#10414]
I am a "Highcharts gantt" user. 

The dipendency arrow is drawn by key-shaped line,   
when the width of the drawing area is narrow.   
ex:attached file (a screenshot of your demo)   
  
I want to show with straight line also in this case,   
could you tell me how to do this.   
  
#### Live demo with steps to reproduce
![image](https://user-images.githubusercontent.com/33454604/54957358-da23a000-4f95-11e9-91df-c33901baf885.png)

#### Product version

 Highcharts JS v7.0.3 (2019-02-06)
 Gantt series

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @hiroko3,
Thank you for reporting. The issue is known bug and reported here: https://github.com/highcharts/highcharts/issues/10329

Im closing this ticket as duplicate.
