### ISSUE TITLE
Highcharts rendering length of array? in x-axis labels

### ISSUE THREAD

**Issue by rramaa** [highcharts/highcharts#10410]
#### Expected behaviour
The X-Axis labels should only be the labels provided in the `xAxis.categories` field

#### Actual behaviour
The X-Axis labels is printing possibly the length of the array of data. It is happening with many more data sets

#### Live demo with steps to reproduce
[JsFiddle](https://jsfiddle.net/50rxt6Lj/)

#### Product version
 Highcharts v7.0.3 

#### Affected browser(s)
Chrome v72.0.3626.121

**Comment by pawelfus** [comment]
Hi @rramaa 

Thanks for reporting the issue. This is expected behaviour. If you provide less categories than you have data points, then every category outside the `xAxis.categories` array will render as index of the point.

**Comment by rramaa** [comment]
@pawelfus But in my example, the length of the categories and the data is exactly the same in all 3 series(75). Still the X-Axis is rendering the index

**Comment by sebastianbochan** [comment]
Hi @rramaa,
The issue is caused by using `endOnTick` which rounds ticks positions. When you disable it, categories are draw without index.

Demo:
- https://jsfiddle.net/BlackLabel/h3srd9ag/

Does it work like you expect?

**Comment by pawelfus** [comment]
Thanks @rramaa for pointing this out! I didn't notice that lengths are the same. Just like @sebastianbochan said, it's caused directly by `endOnTick` setting, but let me explain what exactly happens. Let's start with simple demo: https://jsfiddle.net/BlackLabel/h3srd9ag/13/

As you can see, categories don't fit the given space, even when rotating, so we automatically increase `tickInterval = 2`. Last category has value=`7` - the odd number, so when setting `endOnTick`=true, you force chart to add an extra category. As @sebastianbochan said - simply remove that option if you don't want that behaviour.

**Comment by rramaa** [comment]
@pawelfus @sebastianbochan Thanks for the solution and explanation. It worked!
Just curious if its documented somewhere? I couldn't find it in the docs.

**Comment by sebastianbochan** [comment]
Hi @rramaa 
You can find a description of the option here:
- https://api.highcharts.com/highcharts/xAxis.endOnTick
