### ISSUE TITLE
chart.labels are not updating

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#10429]
#### Expected behaviour
`chart.labels` should update using `chart.update()` with new labels options.

#### Actual behaviour
`chart.labels` are not updating.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/fxuypzw5/

**Comment by sebastianbochan** [comment]
It looks like the `renderLabels` function does not set reference to rendered label. As a result update does not recognize object and does not apply new options.

**Workaround**
The solution is adding label by `renderer.label`, keep reference and call the `attr()` method as update.

**Demo:**
-  https://jsfiddle.net/BlackLabel/vdo1sfkw/

**Docs:**
- https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#text

**Comment by pawelfus** [comment]
Maybe we should slowly deprecate this `chart.label` in a favour of annotations?

**Comment by sebastianbochan** [comment]
The second solution is keeping all labels in extra array like `chart.labels` or something. As a result reference to labels will exist.

**Internal note**
Regarding to pawel's idea, I agree but, how about back-compatibility?
@TorsteinHonsi what do you think?

**Comment by TorsteinHonsi** [comment]
I agree with Pawel, the `chart.labels` feature is so limited that we should rather slowly deprecate it in favour of annotations.

**Comment by sebastianbochan** [comment]
We will focus on changing docs only or remove the functionality in core too?

**Comment by TorsteinHonsi** [comment]
> I suggest to start with update docs at the beginning.

Yes I agree. The functionality is so small that it doesn't hurt to leave it there.
