### ISSUE TITLE
Typescript: "YAxisOptions" "min" and "max" does not accept "null"

### ISSUE THREAD

**Issue by GitHubStig** [highcharts/highcharts#10428]
#### Issue
I am trying to use bar chart and tried setting `null` into `YAxisOptions.min` property and the Typescript linter threw an error.
![Screenshot 2019-03-27 at 5 04 10 PM](https://user-images.githubusercontent.com/9544391/55063212-7773f680-50b2-11e9-8948-835fda0a44cb.png)
My variable is typed as `number | null` but `YAxisOption.min` only accepts `number | undefined`
![Screenshot 2019-03-27 at 4 58 34 PM](https://user-images.githubusercontent.com/9544391/55063243-88246c80-50b2-11e9-9a80-8a8f6f9a6c67.png)
According to the above picture and https://api.highcharts.com/highcharts/yAxis.min, `null` is acceptable and actually produces the correct result for me.

It might seem like if I needed `null`, I may as well not define the property in the first place. But in my scenario, my maximum chart value is 40, if I set the value to `100` and then update the value later to `undefined`, the chart does not re-render properly, but setting it to `null` works as if the maximum value is `40` which is the expected behavior.

#### Expected behaviour
I expect to be able to set `null` into `YAxisOptions.min` and `YAxisOptions.max`

#### Actual behaviour
I could not.

#### Live demo with steps to reproduce
(none)

#### Product version
HIghcharts v7.03

#### Affected browser(s)
(was happening in my VSCode IDE)

**Comment by sebastianbochan** [comment]
Hi @GitHubStig,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by bre1470** [comment]
Fixed with v7.1.0.
