### ISSUE TITLE
Highcharts boost: x-axis value is incorrect in tooltip, when shared attribute set as true

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#10432]
#### Expected behaviour
Highcharts boost: When tooltip attribute shared is set as true, x-axis value in tooltip should be correct.

#### Actual behaviour
Highcharts boost: When tooltip attribute shared is set as true, x-axis value seen in tooltip is incorrect.

#### Live demo with steps to reproduce
[https://jsfiddle.net/nrdo0Lz3/2/](https://jsfiddle.net/nrdo0Lz3/2/)

**Comment by sebastianbochan** [comment]
Hi @tejaspchordiya,
Thank you for contacting us. 

Please let me know if you mean that xAxis category name is missed or Im wrong.

**Comment by tejaspchordiya** [comment]
Yes, I meant xAxis category name. Thanks for the workaround.
Shouldn't it be provided OOTB?
When I disable boost functionality, by default, I get xAxis category name in tooltip. [Demo](https://jsfiddle.net/rkezfd2t/)

**Comment by sebastianbochan** [comment]
Hi @tejaspchordiya,
I agree with you and yes, it should work. I replace the tag with bug and will notify our boost developer about the problem.

FYI @cvasseng

**Comment by pawelfus** [comment]
Simplified demo: https://jsfiddle.net/BlackLabel/uc0t5L9v/ - note that `shared` option does not matter,  in general category is missing from the tooltip.

**Alternative workaround:**
```js
Highcharts.wrap(Highcharts.Series.prototype, 'getPoint', function (proceed) {
  var point = proceed.apply(this, Array.prototype.slice.call(arguments, 1));
  
  point.category = Highcharts.pick(
    this.xAxis.categories ? this.xAxis.categories[point.x] : point.x,
    point.x
  );
  
  return point;
});
```

Demo: https://jsfiddle.net/BlackLabel/uc0t5L9v/1/
