### ISSUE TITLE
connectNulls doesn't work in Area Stacking

### ISSUE THREAD

**Issue by soetji** [highcharts/highcharts#10447]
#### Expected behaviour
Connecting

#### Actual behaviour
Not connecting

#### Live demo with steps to reproduce
https://jsfiddle.net/soetji/zhc8okbd/

#### Product version
7.0.3

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
The issue is related with known bug here: 
- https://github.com/highcharts/highcharts/issues/2069

Im closing the issue as duplicate.
