### ISSUE TITLE
Axis Title and Line Displaying when showEmpty is False

### ISSUE THREAD

**Issue by scarroll142** [highcharts/highcharts#10456]
#### Expected behaviour
If you have a simple line chart with one single series, setting the showEmpty attribute on an axis to false and passing in an empty array of data to the series should mean that the axis line and title should be hidden.

#### Actual behaviour
If the series is visible then the axis line and title still show despite the series itself having no data.

This seems to be because when hasData() is called to determine if the axis should be hidden or not, the function calls hasData() on each one of the series. This function will return true if the series is currently visible. Therefore, hasData() for the axis returns true. 

Whether this is actually a bug or design choice of hasData() I leave to whomever reads this. At the very least, the documentation states that the option indicates "Whether to show the axis line and title when the axis has no data" and to me that indicates that all series having no data would hide the axis.

#### Live demo with steps to reproduce
https://jsfiddle.net/scarroll142/qy2f163k/
You can immediately see the xAxis line is still there, but toggling the series off hides it.

#### Product version
7.0.3

#### Affected browser(s)
Presumably all

**Comment by sebastianbochan** [comment]
Hi @scarroll142,
Thank you for reporting about the problem. 

It looks like a problem with the `axis.showAxis = showAxis = hasData || pick(options.showEmpty, true);` which detects that series has data but does not.

Its related with incorrect condition:

```
            hasData: function () {
                return (
                    this.hasVisibleSeries ||
                    (
                        defined(this.min) &&
                        defined(this.max) &&
                        this.tickPositions &&
                        this.tickPositions.length > 0
                    )
                );
            },
```

**Workaround**
- https://jsfiddle.net/BlackLabel/dnr5pg37/

**Internal note**
When we replace OR with AND, looks like work properly. @TorsteinHonsi what do you think?
