### ISSUE TITLE
V7 Heatmap and Treemap replaced style fill from css to attribute causing external default CSS overwrite

### ISSUE THREAD

**Issue by JingLiNaomi** [highcharts/highcharts#10454]
#### Expected behaviour
fill does not overwritten by external !default css

#### Actual behaviour
fill color overwritten by external !default CSS which causes heatmap and treemap all cells show same fill color, which is applied to highcharts-color-0 by CSS

#### Product version
7.0.3

#### Affected browser(s)
all

**Comment by JingLiNaomi** [comment]
Suggest to move fill attribute back to inline CSS style, or remove the highcharts-color-0 class

**Comment by sebastianbochan** [comment]
Hi @JingLiNaomi,
Thank you for reporting about the problem. I created a simple demo: https://jsfiddle.net/BlackLabel/qt785dzf/. Please let me know if you mean that each rect should have own class name for styling or Im wrong?

**Comment by JingLiNaomi** [comment]
Hi,

I resolved this by setting styledMode to true. Thanks.

Jing

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pawelfus** [comment]
Thanks! Closing the issue then.
