### ISSUE TITLE
Annotations: updated options prevent updates from pop up

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#10460]
#### Behaviour
If the same object is used to update annotations, then later editions from the pop up are not being applied. The changes are visible in the pop up, but are not applied to the annotation.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/ef98bjcu/1/

Wait about 2 seconds, edit the annotation through the pop up, save changes, the changes are not applied.

#### Product version
Highstock 7.0.3

**Comment by pawelfus** [comment]
Simplified demo: http://jsfiddle.net/BlackLabel/ef98bjcu/18/

**Comment by pawelfus** [comment]
**Workarund:**
```js
Highcharts.Annotation.prototype.addLabels = function () {
  (this.options.labels || []).forEach(function (labelOptions, i) {
    var label = this.initLabel(labelOptions, i);
  }, this);
};
```
