### ISSUE TITLE
Reset zoom button goes offscreen when using scrollablePlotArea

### ISSUE THREAD

**Issue by glacials** [highcharts/highcharts#10466]
#### Expected behaviour
When using a chart with both `chart.scrollablePlotArea.minWidth` and `chart.zoomType` set:

1. When zooming in then scrolling the chart horizontally, the "Reset zoom" stays in the top-right (or wherever it's been positioned) of the chart.

2. When scrolling the chart horizontally then zooming in, the "Reset zoom" is visible in the top-right (or wherever it's been positioned) of the chart.

#### Actual behaviour
1. The "Reset zoom" button scrolls offscreen with the rest of the chart when scrolling horizontally.

2. The "Reset zoom" button is not visible. You must scroll the zoomed chart back to the initial position to see it.

#### Live demo with steps to reproduce
https://jsfiddle.net/glacials/pq84a97y/
1. Zoom into the chart by clicking and dragging your mouse
2. Scroll horizontally

Expected: The "Reset zoom" button stays where it relative to the page
Actual: The "Reset zoom" button is cemented onto its position on the chart, scrolling offscreen when the chart does

#### Product version
v7.1.0

#### Affected browser(s)
Tested in macOS Mojave Chrome 72.0.3626.121 and macOS Mojave Safari 12.0.3.

**Comment by pawelfus** [comment]
Hi @glacials 

Thank you for reporting the issue.

*Internal note:*
It's not a regression, since the beginning it works that way.
