### ISSUE TITLE
Highcharts boost module renders markers on wrong Y-Axis on Zoom

### ISSUE THREAD

**Issue by purcellchristopher** [highcharts/highcharts#10464]
#### Expected behaviour
The markers should be rendered on the same Y-Axis as the the point.

#### Actual behaviour
Markers are rendered on a different Y-Axis.

#### Live demo with steps to reproduce
https://jsfiddle.net/o1pzc5jg/

Zoom anywhere on the chart such that a couple of hours of data is shown.  Observe the markers for the line chart drawn on the Y-Axis of the scatter chart.

#### Product version
Highchart 6.1.4, Highchart 7.1.0

#### Affected browser(s)
Chrome, Safari, Firefox
![Fiddle Screenshot](https://user-images.githubusercontent.com/6345433/55355569-b204d700-5496-11e9-84e4-caf58adc2a47.png)

**Comment by pawelfus** [comment]
Hi @purcellchristopher 

Thanks for reporting the issue. 

*Internal note:*
Old boost module (v5) works fine. It looks like markers are attached to wrong group, or y-offset is applied twice.

**Comment by pawelfus** [comment]
Partially fixed in #10473 PR. What is missing is fix for halo - bottom series rendered halo on the top pane.

Demo: http://jsfiddle.net/BlackLabel/m8dL5pc0/3/

**Comment by purcellchristopher** [comment]
Is there a timeline for when this issue might be resolved?

https://github.com/highcharts/highcharts/issues/10464
[https://avatars3.githubusercontent.com/u/15981345?s=400&v=4]<https://github.com/highcharts/highcharts/issues/10464>

Highcharts boost module renders markers on wrong Y-Axis on Zoom · Issue #10464 · highcharts/highcharts<https://github.com/highcharts/highcharts/issues/10464>
Expected behaviour The markers should be rendered on the same Y-Axis as the the point. Actual behaviour Markers are rendered on a different Y-Axis. Live demo with steps to reproduce https://jsfiddl...
github.com

Synchronizing multiple charts is the only other solution we know of and is a real pain and quite slow.

Chris Purcell
________________________________

**Comment by ppotaczek** [comment]
Hi @purcellchristopher,

At the time we don't have any specific date, but I will try to solve this problem in the near future. Sorry for the inconvenience.

**Comment by pawelfus** [comment]
Unstale

**Comment by TorsteinHonsi** [comment]
Simplified demo: https://jsfiddle.net/highcharts/u9yq5xp8/
