### ISSUE TITLE
Gantt series.data.completed - fill issue when resizing, regression after 7.1.0

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10474]
#### Expected behaviour
Point is filled with complete color correctly when we resize chart.

#### Actual behaviour
When we resize, the point's fill is applied incorrectly.
![Gantt fill](https://user-images.githubusercontent.com/23310742/55405383-32404080-555a-11e9-813b-8e951e346f0d.PNG)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/s2u1jymf
Resize the window

#### Product version
**7.1.0**
Working fine in 7.0.3: https://jsfiddle.net/BlackLabel/aokx5uvd
You can use the previous version as a workaround:
`<script src="https://code.highcharts.com/gantt/7.0.3/highcharts-gantt.js"></script>`

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, this actually turned up on one of the visual tests, but I didn't understand why, so I let it pass. It's a regression since 325775905eef0d8553d161a8870066216cc63ba8.
