### ISSUE TITLE
Pareto chart not working on a baseindex of 0

### ISSUE THREAD

**Issue by pmrcripps** [highcharts/highcharts#10471]
#### Expected behaviour
When the baseindex is set to 0 for a pareto chart the line should be displayed

#### Actual behaviour
When the baseindex is set to 0 for a pareto chart the pareto line is not displayed

#### Live demo with steps to reproduce
https://jsfiddle.net/zc8nyhwq/

the chart should display the pareto line for both Complaints0 and Complaints1 but it is only displayed for Complaints1

#### Product version
6.2, 7.1

**Comment by pawelfus** [comment]
Thanks for reporting the issue @pmrcripps !
