### ISSUE TITLE
Using Draggable items sometimes fail to drag with boost module enabled

### ISSUE THREAD

**Issue by rbudnar** [highcharts/highcharts#10488]
#### Expected behaviour
I have a column that should be draggable by dragging any point of the column, as shown here without the boost module:
https://jsfiddle.net/rbudnar/kh0de2yw/4/

#### Actual behaviour
When I add in the boost module, the column is only draggable from the top 25% or so of the column.
https://jsfiddle.net/rbudnar/hfaqyjv5/9/

#### Live demo with steps to reproduce
See above. I think this is as about stripped down as I can make it. In reality we have several more line series with a few thousand points each that are actually boosted (boostThreshold >0). Please let me know if I can provide any further details.

#### Product version
Latest

#### Affected browser(s)
Chrome latest.

**Comment by pawelfus** [comment]
Hi @rbudnar 

Thank you for reporting this issue. This is how events are propagated in boost mode. In SVG, for column-like series type we add events to direct HTML elements (e.g. `<rect>` in column series), so we know exactly which element is hovered/dragged. For other types (e.g. scatter, line or area), we create a tree to search for the closest point in x/y dimensions. In webGL (boost module), we don't have exact DOM element (like rect) for columns, so we use the same k-d tree for all series types that are boostable.

**Workaround:**
Disable [`enableMouseTracking`](https://api.highcharts.com/highcharts/plotOptions.series.enableMouseTracking) option for not draggable series: https://jsfiddle.net/BlackLabel/jd8asqw1/

**Comment by rbudnar** [comment]
Thanks @pawelfus, that appears to work!

**Comment by rbudnar** [comment]
Update - I notice that you can now click and drag anywhere and it causes the column to move. Do you have any ideas on how to restrict it to just the column?

**Comment by pawelfus** [comment]
Unfortunately, it's not an easy task - as I said above, k-d tree searches during mousemove for the closest point, which in this case will be always that one column. So when in drag&drop this particular column is available always..
