### ISSUE TITLE
Highmaps - demo to adding points and lines.

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#10482]
One of the official demos from [documentations](https://www.highcharts.com/docs/maps/adding-points-and-lines) needs some modification. Get series configuration works only for the first rendered chart - in this case, world map. After loading other maps and triggering "get series configuration" error occurs. [Demo](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/maps/chart/events-click-getcoordinates/)

@KacperMadej suggested solution: [Demo](http://jsfiddle.net/BlackLabel/utrkdh7j/).

#### Product version
Highmaps/Highcharts JS v7.1.0

**Comment by TorsteinHonsi** [comment]
Thanks! Will you create a PR for it @Basts ?

**Comment by Basts** [comment]
@TorsteinHonsi Sure! I will take care of it.
