### ISSUE TITLE
Width issue if element or ANY parent has transform

### ISSUE THREAD

**Issue by thki** [highcharts/highcharts#10498]
Regarding the [fix](https://github.com/highcharts/highcharts/commit/840ddc7f51b9b17d0521a96e5586923ca52e05ad) of [issue #9871](https://github.com/highcharts/highcharts/issues/9871), this issue also occurs if ANY PARENT element of the element el has a transform.

Occured in Highcharts v7.1.0

**Comment by pawelfus** [comment]
Thanks @thki for pointing this out.

**Live demo:**
https://jsfiddle.net/BlackLabel/fp86w4eL/

**Comment by kzoon** [comment]
I ran into the same problem:
http://jsfiddle.net/kzoon/y3Lgtnru

The problem does NOT occur when:
-  you explicitly set the width/height of the chart in the options: http://jsfiddle.net/kzoon/y3Lgtnru/5
- the transform scale is directly on the container Highcharts renders to: http://jsfiddle.net/kzoon/y3Lgtnru/6

**Comment by balkarov** [comment]
@pawelfus I want to know when you fix it, because it is import for our projects.

**Comment by TorsteinHonsi** [comment]
It's now fixed and will be part of the next maintenance release. Until then, here's how to apply a drop-in snippet for the fix: https://jsfiddle.net/gtyr508h/
