### ISSUE TITLE
Export not visible lines

### ISSUE THREAD

**Issue by smokir** [highcharts/highcharts#10494]
#### Expected behaviour

Even if line has `visible: false` let export its data after `serie.setOption({includeInDataExport: true})`

#### Actual behaviour

The only option for exporting not visible line is setting `serie.visible = true`

#### Live demo with steps to reproduce

https://jsfiddle.net/xqagc15r/

#### Product version

Highcharts 7.1.0

**Comment by pawelfus** [comment]
Hi @smokir 

Thanks for reporting the issue. `includeInDataExport=true` is set by default. This option prevents a series from exporting (always), when set to false.

At this moment, only visible series are exported. Let me mark this issue as an enhancement.

**Comment by smokir** [comment]
Hi @pawelfus 

Actually [docs](https://api.highcharts.com/highcharts/plotOptions.line.includeInDataExport) says than `includeInDataExport` defaults to `undefined`, thats why I've suggested using `true` for this case.

**Comment by pawelfus** [comment]
Oh, right, thanks for pointing this out!
