### ISSUE TITLE
Incorrect point's tooltip is showing when hover on second dataLabel

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#10492]
#### Expected behaviour
Specific point's tooltip should appear, regardless which its data label is currently hovered.

#### Actual behaviour
When point's second data label is hovered, then the tooltip presents the data of other point.

#### Live demo with steps to reproduce
Official demo with two data label definitions: https://jsfiddle.net/BlackLabel/qbLp9jn3/
1. Hover the right data label of first point, and see the tooltip for last point is shown.

#### Product version
Gantt Chart

#### Workarounds

1. Setting CSS property 'pointer-events' equal to 'none' on second data labels:
```js
    dataLabels: [{
      enabled: true,
      format: 'Left label',
      align: 'left'
    }, {
      enabled: true,
      format: 'Right label',
      align: 'right',
      style: {
        'pointer-events': 'none'
      }
    }],
```
2. Assign empty function to Gantt's `buildKDTree` prototype function:
```js
(function(H) {
  H.seriesTypes.gantt.prototype.buildKDTree = H.noop
})(Highcharts)
```

_Internal note:_
1. The `drawTrackerPoint` function only reads a `point.dataLabel` object, instead of iterating on `point.dataLabels` array. Then all point's data labels would have point reference available on their `element` objects. https://github.com/highcharts/highcharts/blob/647d870ef152ad694bbbe89a7b2d0603a150e76c/js/parts/Interaction.js#L67-L78
2. Shoudn't Gantt series also have `buildKDTree: H.noop` set on its prototype?,_

**Comment by TorsteinHonsi** [comment]
1. I agree that's likely the problem.
2. Yes I think you're right about that.
