### ISSUE TITLE
Data labels are deferred when animation duration is 0

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/highcharts#10496]
#### Expected behaviour
The data labels should not be deferred and animated in when animation duration is set to 0.

#### Actual behaviour
The data labels are deferred and animated in after a while.

**Workaround:** Set `series.animation` to `false` and it works as expected.

#### Live demo with steps to reproduce
Use the following example to reproduce the issue, see the comments for more information.
[Example of issue](https://jsfiddle.net/jon_a_nygaard/0Ltfhjus/)

#### Product version
Highcharts v7.1

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
@jon-a-nygaard - aren't dataLabels controlled by `dataLabels.defer` option? See: https://jsfiddle.net/BlackLabel/3bL5o1h0/

**Comment by jon-a-nygaard** [comment]
Yes they are, but when series.animation is false they are not deferred as it takes precedence.
Since `animation: { duration: 0 }` can be considered the same as `animation: false` in Highcharts, then I believe they should have the same behavior.

**Comment by pawelfus** [comment]
Hm, right, that makes sense. Defer should show labels after animation, so since animation is disabled, then labels should show up right away.

**Comment by TorsteinHonsi** [comment]
The fix will be to parse `series.animation` through `H.animObject` and then check for `duration` on the result.
