### ISSUE TITLE
Change in default behavior of series highlighting/dimming

### ISSUE THREAD

**Issue by jakrivan** [highcharts/highcharts#10509]
#### Expected behaviour
No default change of behavior - series should not dimm on other serie hover (that should be opt-in behavior)

#### Actual behaviour
From version 7.1.0 the series start to dimm by default if other serie is hovered over

#### Live demo with steps to reproduce
Behavior in previous versions (expected):
http://jsfiddle.net/jakrivan/wqem2sga/3/

Behavior in current version (no code change, behavior changes. New behavior should be explicitt opt-in):
http://jsfiddle.net/jakrivan/wqem2sga/1/

#### Product version
Highcharts v7.1.0

#### Affected browser(s)
Chrome

**Comment by jakrivan** [comment]
Probably caused by this item? https://github.com/highcharts/highcharts/issues/9899
What is the current opt-out method?

**Comment by pawelfus** [comment]
Hi @jakrivan 

Thanks for reporting the issue. This is expected behaviour change between 7.0 and 7.1. You can control this option through [`series.states.inactive.opacity`](https://api.highcharts.com/highcharts/series.column.states.inactive.opacity) (set to 1 to get the same results as in v7.0).

**Comment by jakrivan** [comment]
Thanks @pawelfus - I confirm that that option makes series to behave as in previous version(s).
