### ISSUE TITLE
When chart is rotated and tooltip use html is not calculating the correct text position.

### ISSUE THREAD

**Issue by emidev98** [highcharts/highcharts#10501]
Dear Support,

As I explained in the subject when the chart is rotated the tooltip text is not in the correct place. Also the top right and bottom left corner are cropped in a diagonal shape.

[Demo] https://jsfiddle.net/emiDev98/72yfvmse/10/

![image](https://user-images.githubusercontent.com/49301655/55627284-146b1980-57ae-11e9-8aab-f9e15baf04e9.png)

Thanks, so much

**Comment by pawelfus** [comment]
Thanks for reporting @emidev98 !

**Comment by sebastianbochan** [comment]
Hi @emidev98,
The workaround is a little bit complex, but possible in this case.

1. Disable default tooltip and create empty div (with unique ID)
2. Apply styles for the tooltip ( `position: absolute` etc)
3. Catch `mouseOver` and `mouseOut` on point and fill out the tooltip with content
5. Set the correct position

**Demo:**
- https://jsfiddle.net/BlackLabel/t1ksuyg4/

**Comment by emidev98** [comment]
Dear @sebastianbochan,

Thanks so much for you workaround, but I had to make a static tooltip.

**Comment by sebastianbochan** [comment]
Hi @emidev98,
I apologize for my late reply (github did not notify me about your comment here). Could you elaborate what you mean by "static tooltip" and how it should work or be draw?

**Comment by emidev98** [comment]
Hello again @sebastianbochan ,

Don't warry my mistake I didn't explained correctly. I wanted to say fixed position.

See the example here: https://jsfiddle.net/emidev/txp8Loay/
