### ISSUE TITLE
Wordcloud single orientation not rendered

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#10518]
#### Expected behaviour
Single orientation should render with defaults for the angle

#### Actual behaviour
Using orientations: 1 in wordcloud rotation fails to render. It only renders if you supply a start angle.
All other values for orientations _do_ render with defaults for from and to angles.
See https://jsfiddle.net/kzoon/6vjrcn4k/
Adding from: 90 _does_ render correctly

#### Live demo with steps to reproduce
https://jsfiddle.net/kzoon/6vjrcn4k/

#### Product version
Highcharts  v7.1.0

**Comment by kzoon** [comment]
Maybe related:
Wordcloud also fails to render when you use  orientations: 1 and from: 0 (without supplying a value for to)
See https://jsfiddle.net/kzoon/6vjrcn4k/2/

**Comment by pawelfus** [comment]
Thanks again @kzoon - however I'm not sure if this is a bug. Defaults are `orientations: 2`  and `from: 0` + `to: 90`. When you set `orientations: 1`, which value do you expect? 0, 45 or 90? I think user should set `from/to` when only one orientation is expected.

From the other hand, we should render something - blank chart is just wrong.

**Comment by kzoon** [comment]
Actually, the value of from and to is ignored when orientations: 1. See https://jsfiddle.net/kzoon/6vjrcn4k/3/.
Fine by me, but don't force me to supply them :-)

**Comment by pawelfus** [comment]
Right, thanks @kzoon :))

@jon-a-nygaard FYI
