### ISSUE TITLE
Hidden axis labels after large zoom

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#10516]
#### Expected behaviour

All labels should be shown.

#### Actual behaviour
![Zrzut ekranu 2019-04-9 o 11 18 25](https://user-images.githubusercontent.com/22988131/55788785-4388d000-5ab9-11e9-87e7-e778f5bf909e.png)

#### Live demo with steps to reproduce
1. Open jsfiddle: https://jsfiddle.net/BlackLabel/37c0uwba/
2. Trigger a large zoom:
![Zrzut ekranu 2019-04-9 o 11 18 08](https://user-images.githubusercontent.com/22988131/55788798-4be10b00-5ab9-11e9-905c-dbbc0f1da5e9.png)
3. Click on a `Reset zoom` button.

#### Product version
Highcharts v7.1.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
*Internal note:*

Stable demo: https://jsfiddle.net/BlackLabel/4yLbdg9q/ - note that only Chrome is affected which suggests bug in that particular browser (bisected up to HC v2.2.0 - all the same) I don't believe such bug would be in the HC core undiscovered by users for so long.. I will try to pin point the issue and report to Chrome devs.

**Comment by pawelfus** [comment]
Standalone demo: https://jsfiddle.net/BlackLabel/o8ah3wvf/

Reported to Chrome devs: https://bugs.chromium.org/p/chromium/issues/detail?id=950963

**Comment by TorsteinHonsi** [comment]
>  as a workaround we can limit max position of an element (text) to be around 30 000 000.

Yes we should do that. We have had similar problems in the past, like #3923, with a similar fix/workaround in our end.

**Comment by pawelfus** [comment]
**Worakround:**
Demo: https://jsfiddle.net/BlackLabel/o2kjbupe/

Snippet:
```js
Highcharts.SVGElement.prototype.ySetter = function(value, key) {

  if (value < -5000000) {
    value = -5000000;
  } else if (value > 5000000) {
    value = 5000000;
  }

  this.element.setAttribute(key, value);

  return this;
};
```
