### ISSUE TITLE
Not able to vertically align stacklabels of waterfall chart towards top

### ISSUE THREAD

**Issue by kalandher** [highcharts/highcharts#10513]
#### Expected behaviour
Stacklables should be aligned towards Top of waterfall columns 

#### Actual behaviour
Only first and last column labels are aligned to top rest are in botton.

#### Live demo with steps to reproduce
https://jsfiddle.net/8rjyt1fd/

#### Product version
highcharts.js : 6.1.0
highcharts-more.js: 6.1.0

Using older version as i dont see stacked labels for same chart in 7.1.0

#### Affected browser(s)
Chrome

![waterfall](https://user-images.githubusercontent.com/24358595/55724555-4b992f00-5a29-11e9-8d77-cbac5b036add.png)

**Comment by pawelfus** [comment]
Hi @kalandher 

Thanks for reporting this issue. We have this reported under #3165 ticket. Let me close this ticket as duplicate.
