### ISSUE TITLE
Charts with pattern fill create elements with duplicate ids

### ISSUE THREAD

**Issue by bvancea** [highcharts/highcharts#10510]
#### Expected behavior
In a page, render multiple charts, each with pattern fill. The HTML document should not contain elements with duplicate id attributes, in order to comply with [WCAG 4.1.1](https://www.w3.org/WAI/WCAG21/Understanding/parsing.html). The duplicate ids could cause issues with assisstive technologies.

#### Actual behavior
Highcharts creates multiple `<pattern>` elements with the same id.

#### Live demo with steps to reproduce
1. Access https://codepen.io/anon/pen/zXKQrV
2. Execute the following command in the browser console: `document.querySelectorAll("#highcharts-default-pattern-0")`

#### Product version
Highcharts 7.1, but the issue appears in older versions as well.

#### Affected browser(s)
All browsers.

**Comment by pawelfus** [comment]
Hi @bvancea 

Thanks for reporting this bug! 

FYI @oysteinmoseng
