### ISSUE TITLE
`setState('hover')` does not show crosshairs

### ISSUE THREAD

**Issue by mattgreenfield** [highcharts/highcharts#10528]
#### Expected behaviour
When using `setState('hover')` on a chart with crosshairs enabled, the crosshairs should show.

#### Actual behaviour
The point state is set to hover (the halo appears) but the crosshair is not shown.

#### Live demo with steps to reproduce
http://jsfiddle.net/qp6j5etn/2/
- Hover the chart to see the crosshairs working
- Click the 'Select point 8' to see that point 8 updates but the crosshair does not show.

#### Product version
Highcharts v7.1.1

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @mattgreenfield 

Thank you for reporting the issue. I think `point.setState(state)` shouldn't show crosshairs, just like  doesn't show the tooltip. `point.setState()` sets a state on a point while crosshairs belong to xAxis or yAxis.

If you want to draw a crosshair, use `Axis.drawCrosshair(event, point)`: https://api.highcharts.com/class-reference/Highcharts.Axis#drawCrosshair Demo: http://jsfiddle.net/BlackLabel/fc3o29my/
