### ISSUE TITLE
Gantt: completed number in chart is wrong.

### ISSUE THREAD

**Issue by shetz163** [highcharts/highcharts#10539]
#### Expected behaviour
the completed label in chart is right

#### Actual behaviour
the amount I fillin is 0.14, but in the chart it shows 14.000000000000002%

#### Live demo with steps to reproduce
https://jsfiddle.net/g50yxre2/3/

#### Product version
Highcharts Gantt 7.0.3

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @shetz163 

Thank you for reporting the issue.

**Workaround:**
```js
    dataLabels: {
      formatter: function() {
        var point = this,
          amount = point.point.partialFill;

        if (Highcharts.isObject(amount)) {
          amount = amount.amount;
        }
        if (Highcharts.isNumber(amount) && amount > 0) {
          return Highcharts.correctFloat(amount * 100) + '%';
        }
      }
    },
```
Demo: https://jsfiddle.net/BlackLabel/5ab9ksoe/1/

*Internal note:*
Why do we redefine `dataLabels.formatter` for Gantt? It seems that inherited formatter from xrange series is fine (no missing `correctFloat()`).

**Comment by TorsteinHonsi** [comment]
>  Why do we redefine dataLabels.formatter for Gantt?

Good point, I don't see any substancial differences. Will remove the gantt implementation.
