### ISSUE TITLE
how to display the names of data in legend

### ISSUE THREAD

**Issue by Surekaraja** [highcharts/highcharts#10537]
#### Expected behaviour
to display the name in data array as legend

#### Live demo with steps to reproduce
https://jsfiddle.net/ocjbk6tz/2/

#### Product version
Highcharts v7.1.1

**Comment by pawelfus** [comment]
Hi @Surekaraja 

This is our bug tracker, if you have questions please other support channels: https://www.highcharts.com/blog/support/
