### ISSUE TITLE
Doclets 7.1.0 issues

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#10530]
List of wrong/missing options:

- [x] `series.pyramid3d.data` extends `series.pyramid3d.data`. Probably should be`series.funnel3d.data`
- [x] `series.funnel3d.data` extends `series.funnel3d.data`. Probably should be`series.column.data`
- [ ] `plotOptions.series.states.select` is available for Highmaps only (didn't we fix that?)
- [x] `plotOptions.packedbubble.layoutAlgorithm.parentNodeOptions.marker` extends `plotOptions.line.marker`, should be `plotOptions.series.marker`
- [x] `Highcharts.AnnotationsOptions` is missing from namespace

**Comment by bre1470** [comment]
`plotOptions.series.states.select` is explicitly added in ColumnSeries, so it is probably not a fault. @TorsteinHonsi Is a select state in column series something new ?
