### ISSUE TITLE
Plot area does not display when legend item names are too long, even when using "Adapt Chart to Legend" plugin

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/highcharts#10534]
#### Expected behaviour
Plot area and legend are displayed in export file.

#### Actual behaviour
Plot area is not displayed in export file if legend item names are too long.

#### Live demo with steps to reproduce
1. Create any type of chart that has series with long names
2. Export chart
http://jsfiddle.net/lanimelrok/qg3fw7z4/

#### Product version
Highstock 7.0.3

**Comment by sebastianbochan** [comment]
Hi @LaniMoo,
Thank you for reporting about the problem. I moved this issue to the tracker of the `adapt-chart-to-legend` plugin.

Ref:
- https://github.com/highcharts/adapt-chart-to-legend/issues/13
