### ISSUE TITLE
After zoom in and zoom out some of the xAxis labels are not display

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#10532]
#### Expected behaviour

The chart should look like in initial state:

![Zrzut ekranu 2019-04-10 o 14 51 47](https://user-images.githubusercontent.com/22988131/55880109-4dd1c980-5ba0-11e9-8498-737f80012226.png)

#### Actual behaviour

After a large zoom, only every second label is displayed:

![Zrzut ekranu 2019-04-10 o 14 52 07](https://user-images.githubusercontent.com/22988131/55880085-45798e80-5ba0-11e9-91ac-17ff01466af1.png)

Original example with zoom: https://jsfiddle.net/BlackLabel/1s4zq079/

#### Live demo with steps to reproduce
1. Open jsfiddle: https://jsfiddle.net/BlackLabel/hsLn0jyz/
2. Wait 4 seconds

#### Product version
Highcharts v 7.1.1

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
@TorsteinHonsi FYI

**Comment by sebastianbochan** [comment]
**Workaround:**
Use `axis.tickPositioner` and return array of all positions.

Demo:
- https://jsfiddle.net/BlackLabel/7bgj6tvs/
