### ISSUE TITLE
Missing types v7.1.1

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#10549]
List of missing types:

- [x] [xAxis.margin](https://api.highcharts.com/highcharts/xAxis.margin) - and the same for all other axes (yAxis, zAxis, colorAxis and parallelAxes)
- [x] [organization.dataLabels.nodeFormatter](https://api.highcharts.com/highcharts/series.organization.dataLabels.nodeFormatter)
- [x] [accessibility.keyboardNavigation.order](https://api.highcharts.com/highcharts/accessibility.keyboardNavigation.order)
- [x] [annotations.events](https://api.highcharts.com/highcharts/annotations.events) - all events (add, afterUpdate, remove)
- [x] [Highcharts.SeriesSunburstDataLabelsOptionsObject](https://api.highcharts.com/highcharts/plotOptions.sunburst.dataLabels) (clicking on Highcharts.SeriesSunburstDataLabelsOptionsObject shows 404 page) + missing types for `Highcharts.SeriesSunburstDataLabelsOptionsObject.allowOverlap` and `Highcharts.SeriesSunburstDataLabelsOptionsObject.align`

FYI @bre1470

**Comment by bre1470** [comment]
@oysteinmoseng I guess the type for `accessibility.keyboardNavigation.order` is `Array<string>`. Correct me if I am wrong.

**Comment by oysteinmoseng** [comment]
@bre1470 That is correct.
