### ISSUE TITLE
NetworkGraph - Link labels border is not aligned properly

### ISSUE THREAD

**Issue by jeffersonswartz** [highcharts/highcharts#10545]
#### Expected behaviour
The Border for the link lables hsould be aligned to the text

#### Actual behaviour
The borders for the link labels are shown in the top left corner

#### Live demo with steps to reproduce
https://jsfiddle.net/jeffersonswartz/st3ury4q/4/

#### Product version

Highcharts - 7.1.0

#### Affected browser(s)
Chrome - Windows - Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Hi @jeffersonswartz 

Thanks for reporting this bug! In general, borders and backgrounds are not available for rotated and path-following labels. When disabling `linkTextPath` option we get proper results: https://jsfiddle.net/BlackLabel/7345ehxf/ 

We will update docs and remove wrong borders/backgrounds for labels that use `textPath`. Thanks one again!

**Comment by jeffersonswartz** [comment]
Thanks @pawelfus 

Is there a way to show borders to the data labels alone even though having the link text enabled?

**Comment by pawelfus** [comment]
I'm not sure what do you mean. This is how is gonna look networkgraph after fixing this issue:

![Screen Shot 2019-04-12 at 15 00 58](https://user-images.githubusercontent.com/1453926/56039125-de8cde80-5d33-11e9-8a57-95c4b7b4e889.png)

(no extra borders in the top left corner).

**Comment by jeffersonswartz** [comment]
Ya That's it. Borders just around the datalabels.

**Comment by pawelfus** [comment]
Great, thanks! 

*Internal note:*
We probably should call them "node labels" and "link labels", because just "data labels" is a bit ambiguous. Especially for networkgraph where `series.data` contains connections..
