### ISSUE TITLE
DataLabels' default options are no longer available in docs

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#10546]
Example: https://api.highcharts.com/gantt/series.gantt.dataLabels

We can't check all available options for dataLabels, neither it's defaults. In older versions of API documentation, we were able to expand `dataLabels` from the left side navigation.

FYI: @bre1470

**Comment by pawelfus** [comment]
Note: It's important issue, as a result, dataLabels are not configurable in mobile wrappers: https://github.com/highcharts/highcharts-ios/issues/180

**Comment by bre1470** [comment]
I do not understand the issue. The option is referencing an interface type with all options. You click on the type and see the interface. The interface contains the `rotation`,`y`, and the `format` properties as well.

**Comment by pawelfus** [comment]
Ok, at this moment, types for dataLabels are highly inconsistent. Maybe I am missing something here. Or we just have two separate issues (in just one ticket ;) ).

1) Examples (for highcharts/highcharts-ios#180):

  - Missing type, defined children:

```js
"dataLabels": {
  "doclet": {
    "description": "Extended data labels for range series types. Range series data labels\nhave no `x` and `y` options. Instead, they have `xLow`, `xHigh`,\n`yLow` and `yHigh` options to allow the higher and lower data label\nsets individually.",
    "extends": "plotOptions.arearange.dataLabels",
    "since": "2.3.0",
    "exclude": [
      "x",
      "y"
    ],
    "products": [
      "highcharts",
      "highstock"
    ]
  },
  "meta": {
    "filename": "highcharts/js/parts-more/ColumnRangeSeries.js",
    "line": 37,
    "lineEnd": 48
  },
  "children": {}
},
```

  - defined children, type "*" (similar for `pyramid3d`):

```js
"dataLabels": {
  "doclet": {
    "type": {
      "names": [
        "*"
      ]
    }
  },
  "meta": {
    "fullname": "plotOptions.funnel3d.dataLabels",
    "name": "dataLabels",
    "line": 124,
    "lineEnd": 124,
    "column": 8,
    "filename": "highcharts/js/modules/funnel3d.src.js"
  },
  "children": {
    "align": {
      "doclet": {
        "type": {
          "names": [
            "string"
          ]
        }
      },
      "meta": {
        "fullname": "plotOptions.funnel3d.dataLabels.align",
        "name": "align",
        "line": 128,
        "lineEnd": 128,
        "column": 12,
        "filename": "highcharts/js/modules/funnel3d.src.js",
        "default": "right"
      },
      "children": {}
    },
    "crop": {
      "doclet": {
        "type": {
          "names": [
            "boolean"
          ]
        }
      },
      "meta": {
        "fullname": "plotOptions.funnel3d.dataLabels.crop",
        "name": "crop",
        "line": 126,
        "lineEnd": 126,
        "column": 12,
        "filename": "highcharts/js/modules/funnel3d.src.js",
        "default": false
      },
      "children": {}
    },
    "inside": {
      "doclet": {
        "type": {
          "names": [
            "boolean"
          ]
        }
      },
      "meta": {
        "fullname": "plotOptions.funnel3d.dataLabels.inside",
        "name": "inside",
        "line": 127,
        "lineEnd": 127,
        "column": 12,
        "filename": "highcharts/js/modules/funnel3d.src.js",
        "default": false
      },
      "children": {}
    },
    "overflow": {
      "doclet": {
        "type": {
          "names": [
            "string"
          ]
        }
      },
      "meta": {
        "fullname": "plotOptions.funnel3d.dataLabels.overflow",
        "name": "overflow",
        "line": 125,
        "lineEnd": 125,
        "column": 12,
        "filename": "highcharts/js/modules/funnel3d.src.js",
        "default": "allow"
      },
      "children": {}
    }
  }
},
```

- missing type, doclet, everything (the same for `plotOptions.column.dataLabels`, `plotOptions.funnel.dataLabels` and probably others):
```js
"dataLabels": {
  "doclet": {},
  "meta": {
    "fullname": "plotOptions.bubble.dataLabels",
    "name": "dataLabels",
    "line": 51,
    "lineEnd": 51,
    "column": 4,
    "filename": "highcharts/js/parts-more/BubbleSeries.js"
  },
  "children": {}
},
```

2) > In older versions of API documentation, we were able to expand dataLabels from the left side navigation.

I think it's a UX flaw that we can not expand options anymore. As a developer, I would consider this troublesome that I need to compare two types manually to check what is default for `dataLabels.format`. In previous API versions, we could get this at first sight. Just like we have for `states` -> https://api.highcharts.com/highcharts/series.xrange.states Why `dataLabels` are different? Are we gonna remove all expandable options and move them do interface definitions? Is there any other option which is defined the same way? I understand that makes sense for `SVGAttributes` or `CSSStyles` where we don't need/want to list all of styles/attributes available.

**Comment by bre1470** [comment]
The plan is to remove every unnecessary redundancy in options. Without the common interface every series has it own data label interface (and sub interfaces). The fact, that interfaces are not a navigation tree, is simply a result of the splitted generators for namespace and options.

**Comment by pawelfus** [comment]
Does that mean every `plotOptions<seriesType>` will be removed and only reference to the interface will be left? All of them have the same common interface (with own sub interfaces). The same for `yAxis`/`xAxis`/`colorAxis` - share the same options (+additional ones and changed defaults).

Could you answer to my first issue (with three bullet points) in the post above? Are these configs correct (even though are quite different)?

Extra question: `dataLabels` is an object config, but `dataLabels` can be also array of objects - I assume it's somehow resolved?

**Comment by bre1470** [comment]
Sorry for the late response.

1.) Yes, the following interfaces will be available:
- DataLabelsOptionsObject
  - SeriesAreaRangeDataLabelsOptionsObject
  - SeriesNetworkDataLabelsOptionsObject
  - SeriesPackedBubbleDataLabelsOptionsObject
  - SeriesPieDataLabelsOptionsObject
  - SeriesSankeyDataLabelsOptionsObject
    - SeriesOrganizationDataLabelsOptionsObject
  - SeriesSunburstDataLabelsOptionsObject

2.) No, they look incorrect.

3.) Extra Answer: Which `dataLabels` option do you mean? The `series.<name>.data.dataLabels` one?
