### ISSUE TITLE
Pie does not animate slices when toggling legend items

### ISSUE THREAD

**Issue by JllyGrnGiant** [highcharts/highcharts#10540]
#### Expected behaviour
When toggling a legend item, the pie animates filling in gap created by hiding a series or animates the series back in as it shrinks other series.
https://jsfiddle.net/tao8fn4z/1/

#### Actual behaviour
Slices are immediately resized without animation.

#### Live demo with steps to reproduce
https://jsfiddle.net/tao8fn4z/
Click a legend item to toggle the visibility of a point

#### Product version
Highcharts 7.1.0 and 7.1.1

**Comment by pawelfus** [comment]
Hi @JllyGrnGiant 

Thank you for reporting the issue. You are right, animation is missing.

*Internal note:*
It's probably caused by `inactive` state implementation. Will bisect next week.

**Comment by pawelfus** [comment]
Bisect leads to 60b19fed6
