### ISSUE TITLE
Meteogram symbol not moving with scrollbar

### ISSUE THREAD

**Issue by nzahasan** [highcharts/highcharts#10553]
#### Expected behaviour
Symbols should move with scroll

#### Actual behaviour
Symbols stays in position while scrollbar is moving

#### Live demo with steps to reproduce
https://jsfiddle.net/q10z3wko/3/

#### Product version
Highstock  v7.1.1

#### Affected browser(s)
Chrome,Firefox

**Comment by pawelfus** [comment]
Hi @nzahasan 

Meteogram is an advanced demo for chart & [renderer](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer) combination. It is designed to work in a fixed-width container, without additional features (zooming, scrolling etc). We can solve the issue by storing weather images and gridlines for wind arrows and on [`chart.events.redraw`](https://api.highcharts.com/highcharts/chart.events.redraw) update them: https://jsfiddle.net/BlackLabel/mcof63zh/ - it's still not a perfect solution (e.g. wind arrow boxes are bound to xAxis ticks, which may cause last one to be hidden). Some polishing is still required, good luck!

**Comment by nzahasan** [comment]
@pawelfus thanks, that works for me.
