### ISSUE TITLE
Text goes beyond legend in exported chart - font difference (Windows 10)

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10558]
Like in the title. Probably fonts differ because the problem occurs when using e. g. "%" but doesn't occur when using normal letters.

**Displayed chart:** 
![Legend1](https://user-images.githubusercontent.com/23310742/56122767-6f053200-5f73-11e9-8d2b-929a6e9552e7.PNG)

**Exported chart:**
![Legend2](https://user-images.githubusercontent.com/23310742/56122775-74627c80-5f73-11e9-9dfd-5aa8ef68de2c.PNG)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/xb5v8apw

#### Product version
Highcharts 7.1.1

#### Affected browser(s)
All
Issue occurs on Windows 10.

**Comment by pawelfus** [comment]
Works fine on osx:

- FF: 
<img width="911" alt="Screen Shot 2019-04-15 at 12 08 50" src="https://user-images.githubusercontent.com/1453926/56124613-4e3edb80-5f77-11e9-9b99-7c5812708e6f.png">

- Chrome: 
<img width="907" alt="Screen Shot 2019-04-15 at 12 09 03" src="https://user-images.githubusercontent.com/1453926/56124612-4e3edb80-5f77-11e9-90e7-947ec63eb9c7.png">

**Comment by raf18seb** [comment]
Tested on Windows 10
