### ISSUE TITLE
Links to source code in docs are broken

### ISSUE THREAD

**Issue by KyleW** [highcharts/highcharts#10551]
On any page in the api docs (e.g. https://api.highcharts.com/highcharts/data), the link in the top right corner of each section with the version information (e.g. "Since 6.1.0") leads to a 404 page on github.

For example, the doc for xAxis.accessibility points to https://github.com/highcharts/highcharts/blob/ae67e072a/js/modules/accessibility/options.js#L526-#L533 which does not exist.

**Comment by sebastianbochan** [comment]
Hi @KyleW,
Thank you for reporting.

FYI @jon-a-nygaard

**Comment by bre1470** [comment]
The version hash is simply not the one of our official release (v7.1.1) - I will regenerate the documentation.

**Comment by bre1470** [comment]
Links have been fixed. Thanks for the report!
