### ISSUE TITLE
Highlighting in areaspline with shared tooltip

### ISSUE THREAD

**Issue by mchong-teal** [highcharts/highcharts#10552]
#### Expected behaviour
I have an areaspline graph with a shared tooltip.  In order to keep the spline behaving the way I would like, I replace any 'null' data points with '0'.  However, this means that every point is displayed in the tooltip (which is fine), and that all series are highlighted, even when the series has no data (which is not what I want, as this essentially makes highlighting useless).
This is maybe actually two bugs:
a) I would like to have highlighting in my stacked areaspline with shared tooltip
b) If I make data points 'null' instead of 0, areaspline looks weird

- I would like a way (e.g. in the tooltip formatter) to disable the tooltip (i.e. highlighting) for points where y == 0.
#### Actual behaviour
See attached jsfiddle, which includes areas of the graph that demonstrate both issues a) and b) described above :
- where data points are '0', all series are shown in the tooltip, and are therefore highlighted.  I would like series with data points '0' not to be highlighted (see left hand side of graph).
- where data points are 'null', highlighting behaviour works as expected (series with no data are not highlighted), but the areaspline looks all funny and makes me sad :( (see middle-ish of graph)

It would be nice maybe to have a callback to determine whether a point should be included in the shared tooltip?

#### Live demo with steps to reproduce
https://jsfiddle.net/sjyod93w/

#### Product version
Highcharts 7.1.1

#### Affected browser(s)
Tested in Chrome

**Comment by mchong-teal** [comment]
I guess I could use the existing tooltip formatter to manage the hover/inactive states for each series?  But I would need to disable the default mouse interaction behaviour for series state somehow..

**Comment by pawelfus** [comment]
Hi @mchong-teal 

Thank you for reporting issues! You are correct, using `tooltip.formatter` is a way to go in your case, please take a look: https://jsfiddle.net/BlackLabel/6dz4qw5e/

Snipptet:
```js

  tooltip: {
    shared: true,
    formatter: function() {
      var chart = this.points[0].series.chart,
        str = '',
        header = '<span style="font-size: 10px">' + this.x + '</span><br/>',
        footer = '';


      this.points.forEach(function(tooltipPoint) {
        if (tooltipPoint.y === 0) {
          // Temporary disable animation for halo:
          Highcharts.setAnimation(false, chart);
          // Set normal state for zero points
          tooltipPoint.point.setState('normal');
          // Restore the animation:
          Highcharts.setAnimation(true, chart);
        } else {
          str += '<span style="color:' + tooltipPoint.color + '">\u25CF</span> ' + tooltipPoint.series.name + ': <b>' + tooltipPoint.y + '</b><br/>';
        }
      });

      // If all points are zeros, don't show tooltip
      return str === '' ? false : header + str + footer;
    }
  },
```

So in general, `a)` is not a bug, `0` is a valid value, so in general users want to display that in tooltip :) Regarding `b)` - it's a known problem with null points in stacked area/areaspline series, see #2069.

Let us know if you find any issues with the solution above or if we can close the ticket. Thanks!

**Comment by mchong-teal** [comment]
Thanks, @pawelfus, the above solution gets me part of the way there.

The main behaviour I was trying to get is the highlighting of the _areas_ that have non-zero values (not just the points).  E.g. in the jsfiddle you provided, hovering over the x value '7' should highlight the areas for 'series 1' and 'series 4', and 'disable' the areas for other series (in the same way areas are highlighted/disabled when moused over when the tooltip is not shared).

It seems by using a shared/split tooltip, the area highlighting is effectively disabled in my case.

**Comment by pawelfus** [comment]
That's correct, when `shared = true` all series that have hovered points are active series. When `shared = false`, other series are dimmed (get `inactive` state). You can manually set this `inactive` state too. `series.setState('inacive')` is the method you need, take a look: https://jsfiddle.net/BlackLabel/6dz4qw5e/1/ (notice that you need to reset to normal state afterwards),
