### ISSUE TITLE
Network Graph - Cannot remove a node

### ISSUE THREAD

**Issue by jeffersonswartz** [highcharts/highcharts#10565]
#### Expected behaviour
The `removePoint` is not removing the exact node.

#### Actual behaviour
It is removing the link alone not the node

#### Live demo with steps to reproduce
Try clicking the remove point button
https://jsfiddle.net/jeffersonswartz/o89Lrq6s/11/

#### Product version

Highcharts - 7.1.0
#### Affected browser(s)
Chrome - Windows - Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Thanks for reporting @jeffersonswartz 

**Workaround:**
Use `series.points[index].remove()` instead: https://jsfiddle.net/BlackLabel/04xcy37m/

**Comment by jeffersonswartz** [comment]
Thanks for the super quick reply @pawelfus :)

But it still removes the link not the node. What should I do to remove the a node completely?

**Comment by pawelfus** [comment]
Good point! This should be possible by calling `chart.series[index].nodes[index].remove()`, but apparently it's broken too.

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/zmr0go9s/

Snippet:
```js
Highcharts.seriesTypes.networkgraph.prototype.pointClass.prototype.remove = function(redraw, animation) {
  var dataset = this.isNode ? this.series.nodes : this.series.data;

  this.series.removePoint(
    dataset.indexOf(this),
    redraw,
    animation
  );
};
```

**Comment by jeffersonswartz** [comment]
That's Unfortunate.

Actually what I am trying to achieve is When we click a node all the child nodes will be hidden and when we click again it will be shown. It is just like collapsing and expanding a node.

 Is there a workaround to achieve this?

**Comment by pawelfus** [comment]
With the snippet below, `series.nodes[index].remove()` will be supported. Could you @jeffersonswartz test this solution? I have tested some basic operations and it looks promising. Please, let me me know if you find any bugs, I will try to fix this asap.

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/suwgocd6/

```js
Highcharts.seriesTypes.networkgraph.prototype.pointClass.prototype.remove = function(redraw, animation) {
  var point = this,
    series = point.series,
    dataOptions = series.options.data,
    links = series.points,
    index;

  // For nodes, remove all connected links:
  if (point.isNode) {
    // Temporary disable series.points array, because
    // Series.removePoint() modifies it
    series.points = [];

    // Remove link from all nodes collections:
    [].concat(point.linksFrom)
      .concat(point.linksTo)
      .forEach(
        function(linkFromTo) {
          // Incoming links
          index = linkFromTo.fromNode.linksFrom.indexOf(
            linkFromTo
          );
          if (index > -1) {
            linkFromTo.fromNode.linksFrom.splice(
              index,
              1
            );
          }

          // Outcoming links
          index = linkFromTo.toNode.linksTo.indexOf(
            linkFromTo
          );
          if (index > -1) {
            linkFromTo.toNode.linksTo.splice(
              index,
              1
            );
          }

          // Remove link from data/points collections
          Series.prototype.removePoint.call(
            series,
            series.data.indexOf(linkFromTo),
            false,
            false
          );
        }
      );

    // Restore points array, after links are removed
    series.points = series.data;

    // Proceed with removing node. It's similar to
    // Series.removePoint() method, but don't modify other arrays
    series.nodes.splice(series.nodes.indexOf(point), 1);

    if (point) {
      point.destroy();
    }

    // Run redraw if requested
    series.isDirty = true;
    series.isDirtyData = true;
    if (redraw) {
      series.chart.redraw(redraw);
    }
  } else {
    series.removePoint(
      series.data.indexOf(point),
      redraw,
      animation
    );
  }
};
```

**Comment by jeffersonswartz** [comment]
@pawelfus Sorry for the late reply and Thanks for the workaround, It works fine in all the cases that I have tested.
