### ISSUE TITLE
Can't set pre-defined themes to highcharts charts

### ISSUE THREAD

**Issue by TitaneBoy** [highcharts/highcharts#10567]
#### Expected behaviour
Be able to load pre-defined HighCharts theme with Typescript

#### Actual behaviour
Having error while trying to set theme

![image](https://user-images.githubusercontent.com/15614466/56215235-4e99ae00-602d-11e9-9a9b-a02b440a38af.png)

#### Code
```
import * as Highcharts from 'highcharts';
import StockModule from 'highcharts/modules/stock';
StockModule(Highcharts);
import HC_exporting from 'highcharts/modules/exporting';
HC_exporting(Highcharts);
import * as DarkBlueTheme from 'highcharts/themes/dark-blue';
...
export class StatusHighchartsComponent implements OnInit, OnDestroy {
  private chart: Highcharts.Chart;
  Highcharts = Highcharts;
  chartConstructor = 'chart'; // stockChart

  constructor(private resumeLiveService: ResumeLiveService) {
    DarkBlueTheme(this.Highcharts);
  }
}
```

![image](https://user-images.githubusercontent.com/15614466/56215857-5efe5880-602e-11e9-904a-e1ba64638b10.png)

#### Product version

"highcharts": "7.1.1",
"highcharts-angular": "2.4.0",

Hello there...In previous versions, I was able to load pre-defined themes in my Angular component in this way:

```
import * as DarkBlueTheme from 'highcharts/themes/dark-blue';
DarkBlueTheme(Highcharts);
```
But know, there is no way to load these themes without having typescript error.. I was trying to search in your docs the way to load these themes but could not find any reference. Is there any chance that Highcharts has an (typescript) issue about loading pre-defined theme or am I missing something ?

Thank you in advance for your help.

**Comment by pawelfus** [comment]
Hi @TitaneBoy - thanks for reporting the issue! 

@bre1470 - could you take a look?

**Comment by bre1470** [comment]
Import it like modules:
```ts
import DarkBlueTheme from 'highcharts/themes/dark-blue';
```

**Comment by TitaneBoy** [comment]
@bre1470 ..Thank you for your answer..It works like a charm now.. :-)
