### ISSUE TITLE
Pie animation on series.setData missing

### ISSUE THREAD

**Issue by jakub-noga-antsolutions** [highcharts/highcharts#10575]
#### Expected behaviour
Slices will animate

#### Actual behaviour
Slices change their size instantly

#### Live demo with steps to reproduce
Compare behaviour between 7.0.1 and 7.1.1 version on "Set data in pie" example
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/series-setdata-pie/

#### Product version
7.1.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @jakub-noga-antsolutions 

Thanks for reporting the issue. It's a regression after 60b19fed6 - which is the same as #10540 ticket (different action, but it's a general problem with missing animation). Closing this ticket as a duplicate.
