### ISSUE TITLE
Gantt: treegrid fails when collapsing.

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#10570]
#### Expected behaviour
Collapsing should work correctly as in versions below 7.1.0

#### Actual behaviour
While collapsing the error occurs and the chart is broken.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/hbz4tq8u/

1) Collapse and uncollapse planning multiple times
2) Check the console error

#### Product version
Highcharts Gantt 7.1.0 and above

#### Affected browser(s)
all

**Comment by wchmiel** [comment]
This bug is caused by this commit: https://github.com/highcharts/highcharts/commit/c56e2e7d8.

**Workaround:**
1) Use version 7.0.3
2) set the main category as a separate series: https://jsfiddle.net/BlackLabel/heoLfw3k/

**Comment by JackLinstead1** [comment]
@sebastianbochan @wchmiel I am getting this issue too, the workaround (7.0.3) works - however I lose exporting functionality & the scrollbar at the bottom? Is there a way to get the best of both worlds? Many Thanks, Jack

**Comment by wchmiel** [comment]
Export functionality requires the exporting module - more about it here: https://www.highcharts.com/docs/export-module/export-module-overview, demo with exporting: https://jsfiddle.net/BlackLabel/9m4d0g7k/. Could you explain more precisely what is "the scrollbar at the bottom"?

**Comment by JackLinstead1** [comment]
@wchmiel It appears if you switch to 7.0.3 on JS Fiddle (HTML line: 1)
from:
<script src="https://code.highcharts.com/gantt/highcharts-gantt.js"></script>

TO

<script src="https://code.highcharts.com/gantt/7.0.3/highcharts-gantt.js"></script>

You will notice sadly the exporting disappears.

The scroll bar is another new feature that disappears too.

**Comment by wchmiel** [comment]
All modules should be loaded with the same version. Check this demo: https://jsfiddle.net/BlackLabel/xk1bmu8q/

**Comment by JackLinstead1** [comment]
Thanks @wchmiel (me being daft). I really appreciate your help. Exporting works perfectly now in that version!

On the other hand - the scroll still doesn't appear to work in 7.0.3 properly. This feature (https://www.highcharts.com/gantt/demo/with-navigation) But I suspect that is what @sebastianbochan was mentioning.

**Comment by sebastianbochan** [comment]
FYI @jon-a-nygaard
