### ISSUE TITLE
The 'connectNulls' can not be disabled in area with 'percent' stacking

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#10574]
#### Expected behaviour
It should be possible to disable the `connectNulls` option: http://jsfiddle.net/BlackLabel/z1hqsfL9/

#### Actual behaviour

The `connectNulls` property can not be disabled: http://jsfiddle.net/BlackLabel/7hzcbLku/

Original use case: http://jsfiddle.net/BlackLabel/vdmquy1f/

#### Product version
Highcharts 7.1.1

#### Affected browser(s)
All

Internal note:
_Caused by:_
https://github.com/highcharts/highcharts/blob/c1c90833544207fcee4c5975814fdd12b87b2f9e/js/parts/AreaSeries.js#L339

Possible imporvement: 
`connectNulls = H.pick(options.connectNulls, stacking === 'percent'),`

**Comment by TorsteinHonsi** [comment]
That seems to be working well.
