### ISSUE TITLE
dataRefreshRate works as milliseconds for google spreadsheets

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#10572]
Chart configuration: 
```
data: {
    googleSpreadsheetKey: '1wezC75MlNjRd3uUW7m5s30Eaemc6mCaE1Hk1D8YNVRk',
    enablePolling: true,
    dataRefreshRate: 3600
  }
```
Docs: https://api.highcharts.com/highcharts/data.dataRefreshRate

#### Expected behaviour

Highcharts shouldn't make perpetual AJAX calls since `dataRefreshRate` is set to 1 hour and the chart is properly loaded.

#### Actual behaviour

It does a call every 3600 **milliseconds**:
![image](https://user-images.githubusercontent.com/13188589/56280536-afe37f00-610a-11e9-980d-92c2ce5dbf06.png)

The problem seems to occur only for google spreadsheets.

If we multiply `dataRefreshRate` by `1000`, the code works as initially intended: http://jsfiddle.net/BlackLabel/mbxquefg/

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/u9j4fzv6/
Open _Network_ tab in developer's console.

#### Product version
7.1.1

**Comment by pawelfus** [comment]
Already fixed in #10621 PR. Will be part of the next release.
