### ISSUE TITLE
Split tooltip: label color doesn't change for different color points in a single series

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#10571]
#### Behaviour
Split tooltip doesn't change stroke color of a label when points in a single series have different colors. The tooltip label exists as a reference on the series, so it's not getting color calculated again based on a new point color.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/z8bvyc3p/4/

#### Workaround
https://jsfiddle.net/BlackLabel/z8bvyc3p/3/

**Comment by JuanSenoret** [comment]
Thanks, @KacperMadej for your support. The workaround works fine for me. Waiting for the fixed version. Thanks again
