### ISSUE TITLE
position of start/end label in solid gauge

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#10587]
In arc-shaped solid gauges there are typically 2 labels: the axis min and the axis max value. The axis itself is typically not shown.
#### Expected behaviour
Center the min and max label below the start/end of the pane background/series

#### Actual behaviour
The labels are rendered relative to the y-axis that is not shown, resulting in the min lining out to the left and the max lining out to the right.

#### Live demo with steps to reproduce
http://jsfiddle.net/kzoon/9ktr7vw2/

I understand this is because these are axis labels. However, I can't explain that to my customers, because there is no axis visible.
Maybe an option to show only min and max label would help. If selected the min and max would be rendered in their proper location.

**Comment by sebastianbochan** [comment]
Hi @kzoon,
Thank you for reporting about the problem. Im not sure if it is a bug, because when you set oversized chart (130%) the shape is also out of edges. Please elaborate the use case of this kind of scenario.

**Comment by kzoon** [comment]
I think solid gauge is typically used like in your demo: https://www.highcharts.com/demo/gauge-solid.

The grey background plus the axis min and max labels (0 and 200, 0 and 6) neatly signify the possible range of data. For the user the min and max labels are part of the arc-background. A location centered at the base of the  arc-background is the most logical location for these labels.

But technically they are part of y-axis, which determines where these labels are rendered. With the current axis label options, I can't guarantee the centered location that I want.

In my application the same chart can be rendered in very different sizes. Currently the size of the chart influences the location oft he min and max labels. Compare these three fiddles, which only differ in size:

http://jsfiddle.net/kzoon/9ktr7vw2/4/
http://jsfiddle.net/kzoon/9ktr7vw2/5/
http://jsfiddle.net/kzoon/9ktr7vw2/6/

You will see that the label position is all over the place.

An option that would center these labels for me would be ideal: they would always be in the right place. Ideally it would also handle the y position, which I now have to change depending on the font size.

**Comment by pawelfus** [comment]
Thanks for the details @kzoon 

What we need is kind of "auto" distance, like this:

- http://jsfiddle.net/BlackLabel/8j6d9rg7/
- http://jsfiddle.net/BlackLabel/v4p3f9z8/
- http://jsfiddle.net/BlackLabel/30xmyc4f/
- http://jsfiddle.net/BlackLabel/enutszcm/

Snippet: 
```js
(function(H) {
  H.wrap(H.Axis.prototype, 'render', function(proceed) {

    if (this.isRadial && this.isCircular && !this.isXAxis) {
      this.options.labels.distance = -(this.center[2]) / 8;
    }

    return proceed.apply(this, Array.prototype.slice.call(arguments, 1));
  });
})(Highcharts);
```

**Workaround:**
Use [`responsive.rules`](https://api.highcharts.com/highcharts/responsive.rules) to define chart's size thresholds and distances for labels.

**Comment by kzoon** [comment]
Exactly.

Thanks for the snippet. I was struggling with translating the percentages in the radius settings into pixels for the distance setting. Yours looks like a good approach for this!

**Comment by pawelfus** [comment]
Hmm.. interesting idea. Percentage of what? Size of the chart, just like pane/axis? That might be confusing, why label distance has any relation to size of the chart.

Maybe simple `align: "left"|"center"|right"` should align label to the edge of arc shape instead of setting "text-anchor"? But, what if someone needs more labels, because of the design? Like this: http://jsfiddle.net/BlackLabel/r1zm4ae5/ 

Still, the tricky part is to apply this change only for "solid-gauge" series. As you noticed, it's still an axis. We have some similar changes (where series determines an axis options/behaviour) and this causes bugs like #6408..

**Comment by kzoon** [comment]
The percentage would have the same base as:
pane.Background.innerRadius
pane.Background.outerRadius
series.radius
series.InnerRadius

As for your last remark: axis.labels.distance is already only applicable for gauges (according to the API). The change would concern how you set axis.labels.distance. In pixels or percentage.

**Comment by pawelfus** [comment]
Added percentage support, as you suggested. Take a look: http://jsfiddle.net/BlackLabel/z7Lmkovw/

Let us know if you find any issues with that solution.

**Comment by kzoon** [comment]
Works very well so far. Thanks for your help!
