### ISSUE TITLE
Category label strings surrounded by < and > do not render

### ISSUE THREAD

**Issue by rcdubya** [highcharts/highcharts#10581]
#### Expected behaviour
Category strings wrapped in < > will render in the chart. For example, the category `"<All>"` will render on the chart.

#### Actual behaviour
Category strings wrapped in < > does not render in the chart. A category string such as `"<All>"` does not render on the chart. However, `"< All >"`, or `"< All>"` does render.

Any clarification on any this is happening as my customer would like to use these characters to indicate special categories? I'm assuming there is some kind of XSS or HTML handling to strip our potentially bad HTML.

Would appreciate further insight on why this is happening and whether there's anything In terms of HC options or consumption that we can implement to make it possible would be really helpful.

#### Live demo with steps to reproduce
https://codepen.io/anon/pen/PgRqNW

#### Product version
Latest build. Also, observed as far back as Highstock 2.1.9

#### Affected browser(s)
Observed in latest desktop Chrome, and iOS Safari 12.2

**Comment by sebastianbochan** [comment]
Hi @rcdubya,
Thank you for reporting.

**Workaround**
You can use the HTML entities `&lt;` or `&gt;` instead of `< >`.

Demo:
- https://codepen.io/anon/pen/VNXmLY

**Comment by rcdubya** [comment]
Thanks @sebastianbochan for the reply. I'll see what we can do with that in the meantime. 

I just tried it in our application and the problem is that although the characters then appear correctly in the chart, elsewhere in our application (filter controls, etc) we show the raw characters for that category which looks ugly. I'm hoping to avoid having to process the data differently prior to pushing into a HC series.

**Comment by sebastianbochan** [comment]
Hi @rcdubya,
Please let me know how can I replicate your problem. Is it possible to set a live demo of your problem?

**Comment by rcdubya** [comment]
Hi @sebastianbochan, this link from the original submission is probably the best example:
https://codepen.io/anon/pen/PgRqNW

The "<Grapes>" category is exactly the case that replicates passing in the "<All>" category that I described. This example just contained a few other cases I tried as well.

Thanks!

**Comment by pawelfus** [comment]
Hi @rcdubya 

I understand it may be a bit problematic, so please escape `<` and `>` from strings you have. You can do that only for a chart: https://codepen.io/anon/pen/eorGaX - no need to refactor entire application. Why it's problematic? Because we don't know if `<pears>` is your custom HTML tag, or it's just a category name. 

Snippet:
```js
var escapeEntities = function (str) {
  var escapes = {
    '&lt;': '<',
    '&gt;': '>'
  };
  
  Object.keys(escapes).forEach(function (key) {
      str = str.toString().replace(
        new RegExp(escapes[key], 'g'),
        key
      );
  });
  return str;
};
```

Usage:
```js
  xAxis: {
    categories: ['< Apples >', '< Oranges>', '\<Pears\>', '<Grapes>', 'stuff'].map(escapeEntities)
  },
```

PS: I have edited your first post, but when you check your previous message you will see that tags are not escaped too :) See:
> The "" category is exactly the case that replicates passing in the "" category that I described. This example just contained a few other cases I tried as well.
