### ISSUE TITLE
Navigator doesn't change base series xAxis extremes

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#10580]
#### Expected behaviour
X axis extremes should always change with selected range in Navigator.

#### Actual behaviour
When move navigator's shade to the left edge, then a base series x axis extremes doesn't change while moving a shade to the right.

#### Live demo with steps to reproduce
Official demo: https://www.highcharts.com/gantt/demo/with-navigation
Move up a shade extremely to the left, and then to the right to see what happening.

#### Product version
Gantt 

_Internal note:_
_It happens because `series.isDirtyData` is always set, and `navigator.updatedDataHandler`function is called on every redraw._

**Comment by Denyllon** [comment]
Possible workaround is to set reset the `series.isDirty` and `series.isDirtyData` after every `series.setData` function call.

```js
(function(H) {
  H.wrap(H.seriesTypes.gantt.prototype, 'setData', function(proceed, data, redraw, animation, updatePoints) {
    var series = this;
    
    proceed.apply(series, Array.prototype.slice.call(arguments, 1));
    series.isDirty = series.isDirtyData = false
  })
})(Highcharts)
```

Live example: http://jsfiddle.net/BlackLabel/p5g4a21o/

**Comment by aaronbeall** [comment]
That workaround solved it for me. Is this something that could be patched? Are there any performance side effects? I have found the navigator introduces a big performance bottleneck in my use case.

**Comment by aaronbeall** [comment]
@Denyllon 
I'm using a setup with scrollbar and navigator like this: http://jsfiddle.net/j5quwvz9/

I noticed that with navigator enabled the dragging of bars and scrolling is performs badly. If I disable the navigator both are very smooth.

This is with 200 rows. My real use case will actually exceed 1,000.

**Comment by Denyllon** [comment]
Indeed, a performance is not sufficiently fluent on the attached example. I took a closer look on the issue, and the problem is definitely the same. The `series.setData()` function with new data set is called on **every redraw** triggered on the chart, which is definitely not correct conception.

The problem is absolutely very complex, and it's necessary to fix it as soon as possible, because also other official demos are broken. This issue is also directly related with https://github.com/highcharts/highcharts/issues/10570

**Comment by aaronbeall** [comment]
@Denyllon Thanks for the update. We'll be watching the progress of the Gantt chart with anticipation. :)
