### ISSUE TITLE
Unable to load Highstock library

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#10584]
#### Expected behaviour
Highstock should be loaded to render chart.

#### Actual behaviour
Highstock library is not getting loaded and throwing script error.

#### Live demo with steps to reproduce
[Demo](http://jsfiddle.net/zLngrvoh/)

#### Product version
v7.1.1

Am I missing something here?

**Comment by pawelfus** [comment]
Hi @tejaspchordiya 

Thanks for reporting the issue. The `/stock/` part should be defined in path: 
```js
      requirejs.config({
        paths: {
          'highcharts': 'https://code.highcharts.com/stock'
        }
      });
```
So we can resolve this by `highcharts/highstock` name.

Demo: http://jsfiddle.net/BlackLabel/mvnqwk93/

Note that `Highstock` can be loaded as module for Highcharts, demo: http://jsfiddle.net/BlackLabel/nk6yrbvh/ ([from docs](https://github.com/highcharts/highcharts#load-highcharts-from-the-cdn-as-an-amd-module))

**Comment by tejaspchordiya** [comment]
Thanks for your reply. It is working.

Further, for the sake of minimum server request, I merged files and created a single file highcharts.js. This highcharts.js file contain following files one below the other:

- highstock.js
- highchart-3d.js
- highcharts-more.js
- map.js
- solid-gauge.js
- treemap.js
- sunburst.js
- boost-canvas.js
- boost.js

When I am trying to load highcharts.js, just the code of highstock.js is getting loaded.

Why are rest of the files not getting loaded?

**Comment by sebastianbochan** [comment]
Hi @tejaspchordiya,
The highstock contains all highcharts features, so you should not load highcharts.js too. Let me know if it solved your problem.

**Comment by tejaspchordiya** [comment]
I think you misinterpreted my question. I know highstock.js contains all highcharts.js features.

Here, I am trying to merge multiple files to create a single file called highcharts.js, and load these multiple files in a single request. But for the sake of giving a relevant name, I am calling this file as highcharts.js, I can even call this file as chartlibrary.js.

Merging and creating a single file like I mentioned was possible till v6.1.1

**Comment by pawelfus** [comment]
Hi @tejaspchordiya 

I'm sorry, I don't understand the issue. Is that related to paths in requirejs or it's a separate question?

In general, when you have a question, please contact our support: https://www.highcharts.com/blog/support/ - this is our bug tracker.

**Comment by tejaspchordiya** [comment]
okay. Thanks.
