### ISSUE TITLE
Highstock - stock tools - indicators feature for multiple charts

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#10599]
Highstock - stock tools - unexpected behaviour for multiple charts. After click indicators button for the first chart, the indicator popup windows are opening on every chart. 

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/BlackLabel/zo1t24y6/)

#### Product version
Highcharts JS v7.1.1 (2019-04-09)

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @Basts,
You should declare unique [bindingsClassName](https://api.highcharts.com/highstock/navigation.bindingsClassName) per each chart.

**Demo**
- https://jsfiddle.net/BlackLabel/xe9sLy6t/
