### ISSUE TITLE
Datetime API broken link

### ISSUE THREAD

**Issue by mcandre** [highcharts/highcharts#10593]
The Axes page https://www.highcharts.com/docs/chart-concepts/axes links to https://api.highcharts.com/class-reference/Highcharts.Highcharts%23numberFormat , which does not exist.

**Comment by sebastianbochan** [comment]
Hi @mcandre,
Thank you for reporting about the problem.

**Internal note**
The link is in the paragraph

```
// Built in Highcharts date formatter based on the PHP strftime (see API reference for usage)
Highcharts.dateFormat("Month: %m Day: %d Year: %Y", 20, false);
```

@jon-a-nygaard @mekhatria

**Comment by jon-a-nygaard** [comment]
Thanks @mcandre for reporting the issue.

I have now updated the url in the link to https://api.highcharts.com/class-reference/Highcharts#.dateFormat 

Please let us know should there be anything else.
