### ISSUE TITLE
Cannot read property 'defIds' of undefined

### ISSUE THREAD

**Issue by brandynbennett** [highcharts/highcharts#10594]
#### Expected behaviour
If the chart is destroyed mid-animation an error will not be thrown from [pattern-fill](https://github.com/highcharts/highcharts/blob/master/js/modules/pattern-fill.src.js#L512)
Error `Uncaught TypeError: Cannot read property 'defIds' of undefined` is not thrown from [pattern-fill](https://github.com/highcharts/highcharts/blob/master/js/modules/pattern-fill.src.js#L512)

#### Actual behaviour
`Uncaught TypeError: Cannot read property 'defIds' of undefined` is thrown after chart is destroyed mid-animation.

#### Live demo with steps to reproduce

I'm struggling to reproduce in isolated environment. Somehow you have to destroy the chart while the animation is running.
Likely doing a check to see if `this.renderer` exists would fix it

#### Product version
Highcharts 7.0.3 && 7.1.1

#### Affected browser(s)
Evergreen

**Comment by sebastianbochan** [comment]
Hi @brandynbennett,
Thank you for reporting about the problem.

FYI @oysteinmoseng

**Comment by Blapi** [comment]
Hi, I'm experiencing the same issue, I've got multiple times this error while using highcharts

```
Uncaught TypeError: Cannot read property 'defIds' of undefined
    at a.Chart.<anonymous> (pattern-fill.js:164)
    at highcharts.js:645
    at a.fireEvent (highcharts.js:647)
    at highcharts.js:6119
```

highcharts-react-official version "2.1.3" (using highcharts version "7.1.2") on Chrome 74.0

Any updates/hints ?

**Comment by oysteinmoseng** [comment]
I will investigate this week, it is probably an easy fix.
