### ISSUE TITLE
features in highcharts

### ISSUE THREAD

**Issue by Surekaraja** [highcharts/highcharts#10595]
#### Expected behaviour
Need some new features to be supported in the highcharts

#### Actual behaviour
these features are not present in the highcharts

#### Live demo with steps to reproduce
https://www.vizlib.com/venndiagram/

#### Product version
highcharts v7.1.1

**Comment by sebastianbochan** [comment]
Hi @Surekaraja,
Thank you for contacting us. This is our tracker for reporting bugs and problems.

I advise you to post your suggestions in our uservoice. The service where we gather all ideas from our users.

- https://highcharts.uservoice.com/
