### ISSUE TITLE
stock tools -- annotation miss its position when print and export as image

### ISSUE THREAD

**Issue by wy1713** [highcharts/highcharts#10605]
#### Expected behaviour
With stock tools user can make an text, circle, square annotation on the highstock chart. The annotation position should be exactly the same place when it is drawn on the chart when using the exporting module to print the chart, export the chart to different types.

#### Actual behaviour
however when exporting the chart, or print,  the annotation missed it's original position of the chart and locationed somewhere else

#### Live demo with steps to reproduce
https://jsfiddle.net/wzLfrhgs/
see attachment, I draw an small square on the highest value. but when I export as an png, it is miss aligned.

#### Product version
![Screenshot (21)](https://user-images.githubusercontent.com/36648934/56608042-bff1d780-65be-11e9-9f9c-510312002e66.png)

lastest

#### Affected browser(s)
chrome

**Comment by TorsteinHonsi** [comment]
@sebastianbochan

**Comment by TorsteinHonsi** [comment]
@pawelfus The test fails in Firefox, can you fix? Precision issues.
