### ISSUE TITLE
Gauge dial backgroundColor is not properly updated

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#10607]
#### Expected behaviour
Gauge color should change when chart.update is used

#### Actual behaviour
Gauge is not changing the color on chart.update

#### Live demo with steps to reproduce
http://jsfiddle.net/izothep/7wm9shLu/10/ - click on change theme button

Worked in 7.0.3
http://jsfiddle.net/izothep/7wm9shLu/11/

#### Product version
Highcharts 7.1.0

#### Affected browser(s)
all

**Comment by TorsteinHonsi** [comment]
Bisected to https://github.com/highcharts/highcharts/commit/af24cb21a1f48bda932c8c001666931b49bd1d2b. Prior to that, all series elements were scrapped and re-built, now we're trying to do it smarter by updating only when needed.
