### ISSUE TITLE
Responsive rules do not apply when using update - multiple charts on the page

### ISSUE THREAD

**Issue by pgupta2601** [highcharts/highcharts#10606]
#### Expected behaviour
Responsive behavior should work on chart.update. We are using jQuery 3.3.1

#### Actual behaviour
Responsive behavior is not working work on chart.update or .setoptions

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/swyd7bht/

#### Product version
Highcharts 7.1

#### Affected browser(s)
Chrome and IE
[Code.txt](https://github.com/highcharts/highcharts/files/3109363/Code.txt)

**Comment by sebastianbochan** [comment]
Hi @pgupta2601,
Thank you for reporting about the problem.

Simplified demo:
- https://jsfiddle.net/BlackLabel/yjzutrg7/1/

Steps to reproduce:
1. click `update responsive`
2. click small / large

Legend is still the same, instead of applying correct layout.

**Internal note**
It looks like related with the bug: https://github.com/highcharts/highcharts/issues/9617

Triggering `chart.setResponsive(options)` before or after update also do not affect.

**Comment by pgupta2601** [comment]
Any workaround or date when it will be fixed. We are currently using Highcharts.NET API Version 7.0.3.0

Please let me know if this can be done using Highcharts.NET latest API?

**Comment by pawelfus** [comment]
Hi @pgupta2601 - no ETA at this moment

**Workaround:**
Demo: http://jsfiddle.net/BlackLabel/he1tgqod/

Note that responsive rules are now replaced with new options. It's not perfect, but at least we are able to provide combined options for rules if necessary.

Snippet:
```js
(function (H) {
  H.addEvent(
    H.Chart,
    'update',
    function(event) {
      if (event.options && event.options.responsive) {
        this.userOptions.responsive = this.options.responsive = event.options.responsive;
      }
    }
  );
})(Highcharts)
```

To add workaround in .NET, simply create a separate file (e.g. `highcharts-workaround-10606.js`) with workaround and load file like any other plugin (e.g. exporting):

```html
<script src="path/to/highcharts.js"></script>
<script src="path/to/exporting.js"></script>
<script src="path/to/highcharts-workaround-10606.js"></script>
```

**Comment by pgupta2601** [comment]
Thanks Pawel. 

Please suggest if the Responsive Rules can be implemented on Highcharts.NET API side. Here's the code that we tried, but i**t didn't work** with the Highcharts7.0.3.0 version.


Responsive = new Responsive()
                {
                    Rules = new List<ResponsiveRules>()
                    {
                        new ResponsiveRules()
                        {
                            Condition = new ResponsiveRulesCondition()
                            {
                                MaxWidth = 370
                            },
                            ChartOptions = (new Legend
                            {
                                X = -15,
                                Y = 260,
                                Floating =  true,
                                Align = LegendAlign.Left,
                                VerticalAlign = LegendVerticalAlign.Top,
                                Layout= LegendLayout.Horizontal,
                                Width = 315
                            })
                        },
                        new ResponsiveRules()
                        {
                            Condition = new ResponsiveRulesCondition()
                            {
                                MaxWidth = 370
                            },
                            ChartOptions = (new Chart
                            {
                                Width = 260,
                                Height= 400,
                                MarginLeft = 40,
                                MarginTop = -100
                            })
                        }
                    }
                }

**Comment by pawelfus** [comment]
Did you add the workaround I posted above? It works with v7.0.3: http://jsfiddle.net/BlackLabel/he1tgqod/2/
