### ISSUE TITLE
Plotlines often invisible by default

### ISSUE THREAD

**Issue by mcandre** [highcharts/highcharts#10604]
Plotlines don't always show up on highcharts. This is because the default width is zero, and because the range of the axis does not automatically expand to include the plotlines.

Let's fix these default behaviors, so that when the developer adds plotlines, they reliably show up on the charts.

**Comment by sebastianbochan** [comment]
Hi @mcandre,
Thank you for contacting. The github is our tracker for reporting bugs so for the general [support](http://www.highcharts.com/support) questions please use email / stackoverflow or forum.

ps. You can catch `chart.events.load` and then extract min / max values from all plotbands. Compare with current min / max and call `setExtremes`.

Demo:
- https://jsfiddle.net/BlackLabel/07Lfs5z2/
