### ISSUE TITLE
Highmaps - Unable to update series

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#10617]
#### Expected behaviour
https://jsfiddle.net/BlackLabel/tuokmpvy/

#### Actual behaviour

https://jsfiddle.net/BlackLabel/yks1zw0d/

#### Product version
Highmaps 7.1.1

#### Affected browser(s)
All

**Internal note:**
_Regression from version 7.1.0_

**Comment by sebastianbochan** [comment]
**Workaround**
Use `series.setData`

Demo:
- https://jsfiddle.net/BlackLabel/m1g4du7t/

**Comment by KacperMadej** [comment]
Bisect tree look rather hard to track for me, but this seems to be the offending commit:
https://github.com/highcharts/highcharts/commit/1fe7b09
