### ISSUE TITLE
Custom Marker Symbol in Legend

### ISSUE THREAD

**Issue by nithyavanig** [highcharts/highcharts#10613]
#### Expected behaviour
I have used the below image as a custom marker symbol in my chart.

url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACsAAAADCAYAAAAKovabAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAAAaSURBVChTY/yU1/ufYYgAJig9JMAQciwDAwDtagLyVWaM9wAAAABJRU5ErkJggg==)

The marker symbol in the legend should look same.

#### Actual behaviour

The legend shows a different shaped marker .

#### Live demo with steps to reproduce

https://jsfiddle.net/nithivani86/sy0zkruo/6/
Please note the Image Symbol . It should not be a square in the Legend.

#### Affected browser(s)
Chrome , IE

**Comment by sebastianbochan** [comment]
Hi @nithyavanig,
Thank you for reporting about the problem. By default marker is re-scaled according to default size. 

You can control the size of marker by options:
- [symbolWidth](https://api.highcharts.com/highcharts/legend.symbolWidth)
- [symbolHeight](https://api.highcharts.com/highcharts/legend.symbolHeight)

Please be aware that marker of legend is calculated as square.

Related topic:
- https://github.com/highcharts/highcharts/issues/4782

**Internal note**
In my opinion we should not calculate image as square, but allow to resize marker according to symbol options.

**Comment by pawelfus** [comment]
Maybe just two options, like `series.legendMarkerWidth` and `series.legendMarkerHeight` could be enough? So that could work for all symbol types (image, rect, triangle etc.)? 


**Workaround:**
Modify legend symbol after rendering:

Demo:
https://jsfiddle.net/BlackLabel/ju9fy87g/

Snippet:
```js
(function(H) {

  H.wrap(H.Series.prototype, 'drawLegendSymbol', function(proceed) {
    var series = this,
      width = series.options.legendMarkerWidth,
      height = series.options.legendMarkerHeight;

    proceed.apply(series, Array.prototype.slice.call(arguments, 1));


    if (
      series.legendSymbol &&
      series.symbol.indexOf('url') === 0 &&
      width &&
      height
    ) {

      series.legendSymbol.imgwidth = width;
      series.legendSymbol.imgheight = height;

      series.legendSymbol.attr({
        width: width,
        height: height,
        translateX: -width / 2,
        translateY: -height / 2
      })
    }
  });
})(Highcharts)
```
