### ISSUE TITLE
3D Stacked charts: Series data labels crop and overflow options are not working properly

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#10614]
#### Expected behaviour
Series data labels overflow and crop options should work correctly and expected result should be seen for different configurations on 3D Stacked chart.
For example: Below JS fiddles show that series data labels overlap with axis tick labels. If crop is set as true, why aren't the data labels hidden?

#### Actual behaviour
For following combination of overflow and crop options, stacked chart series data labels show the same result:
                        overflow= none,                              crop=false
                         overflow=none,                              crop= true
                        overflow= justify,                            crop= true
                        overflow= justify,                            crop= false
Crop true is not hiding the series data labels going outside the plot area.

#### Live demo with steps to reproduce
Corresponding to the above combinations, refer the following fiddles:
overflow= none,                              crop=false
https://jsfiddle.net/amrutaJgtp/qgtcokf7/
overflow=none,                              crop= true
https://jsfiddle.net/amrutaJgtp/qgtcokf7/1/
 overflow= justify,                            crop= true
https://jsfiddle.net/amrutaJgtp/qgtcokf7/2/
overflow= justify,                            crop= false
https://jsfiddle.net/amrutaJgtp/qgtcokf7/3/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @amruta30 

Thanks for reporting the issue. This is caused by the definition of `overflow` and `crop` options, where **plotting area** is the key. In 2D charts, we have plotting area defined as rectangle, in 3D we don't have this simple rect and we crop labels according to point's visibility. In general, bars' data labels are not positioned correctly at all, see #5508

**Comment by darbelaez** [comment]
Hi @pawelfus  - thanks for the suggestion provided in ticket #5508 - however for the long term solution, is there an ETA on when this will be properly supported?

**Comment by pawelfus** [comment]
Hi @darbelaez  - no ETA at this moment.
