### ISSUE TITLE
Docs: The @since tag has bad default

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#10610]
#### Expected behaviour
In the API, when a `@since` tag is not given for an option, no text should be printed. It means we don't have records of when the option was added. It may have been any time before ~v3 when we started recording this.

#### Actual behaviour
Whan a `@since` tag is not given, the API displays "Since v1.0.0".

#### Live demo with steps to reproduce
https://api.highcharts.com/highcharts/chart

**Comment by bre1470** [comment]
This is inherited from parent options. Which version should be the default?

**Comment by TorsteinHonsi** [comment]
When a `@since` tag is not present, the Since statement should simply be left out. This is a regression. 

It seems that the API app checks for the precense of `since`: https://github.com/highcharts/api-docs/blob/master/include/api.js#L603. 

> Which version should be the default?

Maybe we could revert the old behaviour by letting `undefined` be the default? Or an empty string or 0 or something?

**Comment by bre1470** [comment]
Fixed with https://github.com/highcharts/highcharts-documentation-generators/commit/26512aa2964a2753b95636058754be2b9dbf71df
