### ISSUE TITLE
Annotation in basic chart load event does not fire

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#10628]
#### Expected behaviour
Working
```js
Highcharts.chart('container', {…}, function (chart) {
    chart.addAnnotation({
        labels: [{
            point: 'max',
            text: 'Max'
        }]
    }, true);
});
```

#### Actual behaviour
Failing

#### Live demo with steps to reproduce
https://jsfiddle.net/1cun809k/

**Comment by bre1470** [comment]
Workaround at the moment is to use `chart.events.load` option: https://jsfiddle.net/BlackLabel/p4sg5cnu/

**Comment by pawelfus** [comment]
*Internal note:*
It's caused by order of `H.Chart.prototype.callbacks` events. Those are called **after** callback: `chart('container', options, callback)`
