### ISSUE TITLE
Network Graph - setData should update only the changed Data

### ISSUE THREAD

**Issue by jeffersonswartz** [highcharts/highcharts#10625]
#### Expected behaviour
The Data should only update the changed data

In line chart if we update the data it will just change the data rather than re-rendering the whole chart. Example: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/series-setdata/

#### Actual behaviour
The whole network chart is re-rendered 

#### Live demo with steps to reproduce
https://jsfiddle.net/jeffersonswartz/qfda1n5w/1/

Click on The Update Data button.

#### Product version

 Highcharts JS v7.1.1 (2019-04-09)

#### Affected browser(s)
73.0.3683.103 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Thanks for reporting @jeffersonswartz ! I will take a look, probably after the next week.
