### ISSUE TITLE
Axis labels overlap series for 3/4 solid gauge

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#10635]
Solving https://github.com/highcharts/highcharts/issues/10587 helped the positioning of the start/end axis label in halve solid gauges.

Now I created a 3/4 solid gauge, and run into the next problem: the x-posistion of the labels. The demo http://jsfiddle.net/kzoon/eo6hksd3/ shows that the 0 is too much to the left and the 100 is too much to the right.

Setting yAxis label **align right** fixes the position of 100: http://jsfiddle.net/kzoon/eo6hksd3/1/
Setting yAxis label **align left** fixes the position of 0: http://jsfiddle.net/kzoon/eo6hksd3/2/

It would solve my problems if yAxis label alignment on circular axes would be automatic, based on the position of the axis label.
Alternatively, somehow allowing me to set yAxis label alignment per axis label would also work.

**Comment by pawelfus** [comment]
Thanks @kzoon 

At this moment, labels are always center-aligned. We don't have an option to apply different alignment per axis label.

**Workaround:**
Change labels alignment in `chart.events.load` callback: http://jsfiddle.net/BlackLabel/ksda19un/

Snippet:
```js
  chart: {
    type: 'solidgauge',
    borderWidth: 1,
    events: {
      load: function() {
        var yAxis = this.yAxis[0];

        yAxis.ticks[yAxis.tickPositions[0]].label.attr({
          'text-anchor': 'start'
        })
        yAxis.ticks[yAxis.tickPositions[1]].label.attr({
          'text-anchor': 'end'
        })
      }
    }
  },
```

**Comment by kzoon** [comment]
Fair enough automatic left/right alignment would probably fail anyway on circular axes with many labels.
Thanks for the workaround, that will do well for me!

**Comment by pawelfus** [comment]
Digging a bit more: we already have automatic alignment for radial axes, but in your case it would look broken: http://jsfiddle.net/BlackLabel/veLrw4by/ vs http://jsfiddle.net/BlackLabel/veLrw4by/4/ What you want is the opposite effect. At this moment code assumes labels are outside the axis radius, so are aligned in a way they won't overlap the axis itself.
