### ISSUE TITLE
Solidgauge - null point is rendering

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#10630]
In the solidgauge chart, the null point is rendered as a tiny line (path). 

Expected behaviour - same as when data is an empty array. 

#### Live demo with steps to reproduce

[Demo](http://jsfiddle.net/BlackLabel/co9jseLm/)

#### Product version

Highcharts JS v7.1.1 (2019-04-09)

#### Affected browser(s)

All

**Comment by kzoon** [comment]
Thanks for the workaround!
