### ISSUE TITLE
Pie dataLabels overlapping when two pie series are used

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#10639]
#### Expected behaviour
dataLabels should never overlap

#### Actual behaviour
When two pie series with only one point are used, dataLabels are overlapping.

#### Live demo with steps to reproduce
https://jsfiddle.net/izothep/h20ykr59/7/

#### Product version
Highcharts 7.1.1.

#### Affected browser(s)
All

**Comment by Nijadas** [comment]
https://codepen.io/nijadas/pen/XQvWyw
Is this what you are expecting
