### ISSUE TITLE
HighCharts annotation remove not working

### ISSUE THREAD

**Issue by ztpkwame** [highcharts/highcharts#10648]
#### Expected behaviour
Highcharts should delete annotations with integer id

#### Actual behaviour
Throws an error: Uncaught TypeError: c.destroy is not a function
    at a.Chart.removeAnnotation (annotations.src.js:3599)
    at HTMLButtonElement.<anonymous> ((index):166)
    at HTMLButtonElement.dispatch (jquery-3.1.1.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.1.1.min.js:3)

#### Live demo with steps to reproduce
https://jsfiddle.net/30jw6sm7/1/

#### Product version
 Highcharts, Highstock Version 7.1.1

#### Affected browser(s)
Google Chrome Version 76.0.3777.0 

#### Fall back 
Use annotation id as string instead of integer

**Comment by pawelfus** [comment]
Thanks for reporting the issue @ztpkwame 

Actually it works as designed, see docs: https://api.highcharts.com/highcharts/annotations.id - `id: string`. However, I agree, it shouldn't be hard to add integers support too.
