### ISSUE TITLE
Columns Showing Negative When Data is Zero

### ISSUE THREAD

**Issue by SovietFrontier** [highcharts/highcharts#10646]
#### Expected behaviour
The columns will show slightly above zero because of the `plotOptions.column.minPointLength`.

#### Actual behaviour
All of the columns show below zero on the y-axis.

#### Live demo with steps to reproduce
You can view this [`jsFiddle`](https://jsfiddle.net/sovietfrontier/1Lok4ubh/) to view the issue.

#### Product version
`v6.2.0`

#### Affected browser(s)
Firefox, Chrome, IE, Edge (haven't tried any others)

You can view the original question asked on StackOverflow with a real life example [here](https://stackoverflow.com/questions/55921808/highcharts-columns-showing-negative-when-data-is-zero/55923908).

**Comment by pawelfus** [comment]
Thanks for reporting the issue @SovietFrontier 

It's a regression after cf8377865eca45ebb6e5b9673d41cd0789ebc404 - last working version is v5: http://jsfiddle.net/BlackLabel/bjdkn6yz/2/

@KacperMadej - FYI

**Comment by KacperMadej** [comment]
Short workaround just for that data set - reverse yAxis. Demo: https://jsfiddle.net/BlackLabel/hcoe9a7r/

**Comment by SovietFrontier** [comment]
I am assuming this bug was fixed for `v7` only?

**Comment by pawelfus** [comment]
That's correct, sorry for missing milestone!
