### ISSUE TITLE
Boost module shows extra lines when zooming in on some parts of the chart

### ISSUE THREAD

**Issue by dwilkie81** [highcharts/highcharts#10652]
#### Expected behaviour

Zooming in on the chart should show the same data as shown when zoomed out

#### Actual behaviour

Zooming in on an area of the chart where there is only data for 1 series sometimes shows lines from a second series when there is no data for that series in that area.

#### Live demo with steps to reproduce
https://jsfiddle.net/davewilkie/ydoen1xh/35/

Zoom in at the end of the chart where only series 2 has data (e.g. from around 65 to around 75 on the x-axis) - for some zoom windows, a blue series 1 line will be draw across the chart even though there is no data for series 1 for that x-axis range.

In a chart with a lot of series, I see a lot of these artifacts.

#### Product version
7.1.1

#### Affected browser(s)
Happens in both Chrome and Edge (Windows), not tested other browsers.

**Comment by KacperMadej** [comment]
Hi @chored 

Thank you for reporting about the problem.

Simple demo with coded recreation steps: https://jsfiddle.net/BlackLabel/4w2oxsh8/1/
Result:
![chart (5)](https://user-images.githubusercontent.com/8960408/57130175-fb4b8d80-6d98-11e9-8458-88753ab1b03d.png)

(note that blue series data ends at 60 on x and there are no 2 points in the middle - only 3 points total, so 1 in the middle, but on the chart it's different)

**Comment by TorsteinHonsi** [comment]
@cvasseng I think it bisects to af82e852a2df808db6e14b996a1bec586f5d3256, though not sure as this commit doesn't build.
