### ISSUE TITLE
Hover over lines with intersecting series

### ISSUE THREAD

**Issue by jdmoliner** [highcharts/highcharts#10651]
I'm trying to hover over lines in series with intersections. The problem happens in zones with the intersections:

![image](https://user-images.githubusercontent.com/8101692/57069045-bf022980-6cd3-11e9-841f-5897555d4b38.png)

In my demo if you hover over black line (series 2) in the zones with arrows nothing happens. (hover over points works perfectly)

Is there any way to fix it? Is it a normal behavior?

Demo:

https://jsfiddle.net/0pkfgn8L/

**Comment by pawelfus** [comment]
Hi @jdmoliner 

Thanks for reporting the issue. For me it works fine: when I hover black line, closest point (x and y distance) looks for the closest point, which is green or blue one. Then show tooltip for this point:
![closest](https://user-images.githubusercontent.com/1453926/57073577-c7616100-6ce1-11e9-8cfc-9481712cc39e.gif)

Should I use specific browser? Your report is missing some details from our issue-report format.

**Comment by jdmoliner** [comment]
Hi @pawelfus 

You have the same problem, I want that when I hover over black line it is highlighted (Serie 2)

When I hover over zones with arrows in my image green and blue series (serie 1 and 3) are highlighted but not black. I test with `findNearestPointBy: 'xy'` with same result.

**Comment by pawelfus** [comment]
Thanks for the details @jdmoliner - I was confused that "nothing happens" when definitively tooltip should show up. This is expected behaviour (changed in Highcharts ~v3). When moving cursor over the plotting area, Tooltip looks for the closest points (in x/xy dimensions). Dark line points area too far away from cursor to be highlighted. 

Did you consider different tooltips? Shared or split? Take a look:
- split: https://jsfiddle.net/BlackLabel/m1Lk8j2z/
- shared: https://jsfiddle.net/BlackLabel/8gvb2L97/

**Comment by jdmoliner** [comment]
Sorry for explaining me so bad my English is very bad. Thanks for the tips about tooltips but that's not what I want.

In my example I want that when I'am over the black line (on its entire length) the black line be highlighted but blue and green are semitransparents

The current behavior when I'm hover the black line (in areas with intersections) is this:

![c_a](https://user-images.githubusercontent.com/8101692/57084277-52e6ec00-6cfa-11e9-9cc4-1df70143b447.jpg)

But I need this:

![c_b](https://user-images.githubusercontent.com/8101692/57084290-59756380-6cfa-11e9-9397-cb8f9f046937.jpg)

I hope I have explained this better.

**Comment by pawelfus** [comment]
Thanks for the details! I totally forget about `series.stickyTracking` option, take a look: https://jsfiddle.net/BlackLabel/os5b1xdj/

**Comment by jdmoliner** [comment]
exactly that! great!
