### ISSUE TITLE
Chart shifts up when tabbing using keyboard navigation

### ISSUE THREAD

**Issue by miczhongMSFT** [highcharts/highcharts#10650]
#### Expected behaviour
Charts should not shift up when being tabbed through using keyboard navigation.

#### Actual behaviour
Charts will shift up when tab focus is shifted from series to legend. 

Cause: This is caused by the invisible toggle visibility buttons inside of `<div aria-label = "Toggle series visibility"... />`. Enable accessibility.keyboardNavigation and give it a try.

Work around: Set the height of each button to 0 using selector `'*[data-highcharts-chart] button'` on a wrapper 1 level above Highcharts.

Can this be fixed in the source code though? Can y'all set these invisible button's height to 0?

**Comment by sebastianbochan** [comment]
Hi @miczhongMSFT,
Thank you for reporting about the problem.

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
Hi @miczhongMSFT, I am not able to reproduce the issue you are outlining. Example: https://jsfiddle.net/ohzn2urb/2/show (tested in Chrome). Could you provide a jsFiddle demo and more details?

**Comment by sampoturve** [comment]
I think this is a duplicate of: https://github.com/highcharts/highcharts/issues/10564

**Comment by oysteinmoseng** [comment]
Closing as duplicate

**Comment by sgavathe** [comment]
Even though this issue is closed. I still see it happening under IE 11. Under chrome i was able to fix it with @miczhongMSFT suggestions!

**Comment by pawelfus** [comment]
@sgavathe - issue was closed because it's a duplicate. Main issue is still open: #10564
