### ISSUE TITLE
Tooltip misplacement on increasing body zoom value

### ISSUE THREAD

**Issue by RamakrishnanVBI** [highcharts/highcharts#10659]
#### Expected behaviour
In particular window size i will increase body zoom size in that scenario **tooltip** positions will be miss aligned.
@media only screen and (max-width: 1920px) {
 body {
   zoom: 50%;
 }
}

#### Actual behaviour
I will increase the body zoom percentage, tooltip body not related to the actual point.

#### Live demo with steps to reproduce

https://jsfiddle.net/v938zwq6/

#### Affected browser(s)
All browsers

**Comment by sebastianbochan** [comment]
Hi @RamakrishnanVBI,
Thank you for reporting about the problem. This is known bug which has been already reported here: https://github.com/highcharts/highcharts/issues/2299.

I am closing this ticket as duplicate.

**Comment by RamakrishnanVBI** [comment]
We implemented your workaround, But it does not works.
