### ISSUE TITLE
Improve a set visibility in venn during interactivity

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/highcharts#10663]
#### Expected behaviour
When hovering a set in a venn diagram, it should distinguish itself clearly from the other sets.

Some possible behaviours that may achieve this is:
- When hovering a shape, the shape gets the highest zIndex which pushes it on top of the other shapes. This will make it very clear which point/shape is hovered, and how large it is. Downside is that it will hide the intersection shapes underneath itself during hover. Similar functionality exists in treemap today.
- When hovering a shape then it would use hover effects on all the other shapes it includes. E.g. a chart with sets A and B, when hovering A it would apply effects to the set A and the intersection A&B. This should help distinguish how large set A is, while still keeping the intersections visible. Downside is that it may still be visually difficult to see what shape is actually hovered, and it may be a more complicated and performance heavy solution.
- When hovering a point, the other points get an inactive state which fades them out. This functionality already exists, and may be the more natural choice, but at the moment it is not tested how well it works with the venn series.

#### Actual behaviour
The point is hovered with effects and its tooltip is displayed, but if the point is overlapped by many other points it will still be difficult to view.

See the following example where it can be difficult to see the actual size of the sets A, B, C and D due to their large overlap https://codesandbox.io/s/74vny3ry7q

**Comment by pawelfus** [comment]
ad 3) This is how Venn could work with inactive state + zIndexing: https://codesandbox.io/s/busy-davinci-cmnjn

Config required to achieve that: 
```js
          point: {
            events: {
              mouseOver: function() {
                this.graphic && this.graphic.toFront();
              },
              mouseOut: function() {
                this.graphic &&
                  this.graphic.attr({
                    zIndex: this.sets && this.sets.length ? this.sets.length : 0
                  });
              }
            }
          },
          inactiveOtherPoints: true,
```

**Comment by Basts** [comment]
@TorsteinHonsi

Might this issue by closed by this merge: https://github.com/highcharts/highcharts/pull/12898?

**Comment by pawelfus** [comment]
Yes, we can close it now, thanks for pointing this out!
