### ISSUE TITLE
Tooltip position after addPoint() in Highstock 1.1.6

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#1067]
Example: http://jsfiddle.net/TheEvilHammer/asPHF/show/
Steps to reproduce:
1) change the navigator  to see data wihtout new one comming
2) hover somewhere on a chart to see tooltip 
3) wait until new point (5sec) will come - tooltip changed position.

From forum : http://highslide.com/forum/viewtopic.php?f=12&t=18349
As said in thread - may be caused by two fixes:
- https://github.com/highslide-software/highcharts.com/issues/349
- https://github.com/highslide-software/highcharts.com/issues/424

Of course it doesn't happen in 1.1.5.

**Comment by donnietarrosa** [comment]
at what version of highcharts does this issue fixed?

**Comment by donnietarrosa** [comment]
We are currently encountering problem with the highcharts area spline in which the tooltip quickly disappears and the points are not animating if the mouse hovers on. we are using highcharts 2.3.3 along with YUI in IE.

**Comment by highslide-software** [comment]
According to [the changelog](http://www.highcharts.com/documentation/changelog) it was fixed with Highcharts 3.0.3. 

You're running a very old Highcharts version, and we strongly recommend you to upgrade. Current version is 4.0.4.
