### ISSUE TITLE
Gantt chart cannot collapse with subtask and navigator 

### ISSUE THREAD

**Issue by zonggang** [highcharts/highcharts#10672]
gantt chart with subtask and navigator.
    yAxis: {
        uniqueNames: true
    },
    navigator: {
        enabled: true,
        liveRedraw: true,
        series: {
            type: 'gantt',
            pointPlacement: 0.5,
            pointPadding: 0.25
        },
        yAxis: {
            min: 0,
            max: 3,
            reversed: true,
            categories: []
        }
    },
    scrollbar: {
        enabled: true
    },
    rangeSelector: {
        enabled: true,
        buttons: [{
                type: 'day',
                count: 3,
                text: '3d'
            }, {
                type: 'week',
                count: 1,
                text: '1w'
            }, {
                type: 'month',
                count: 1,
                text: '1m'
            }, {
                type: 'all',
                text: 'All'
            }],
        selected: 0
    },

#### Expected behaviour
the parent task can be collapse or expanded.

#### Actual behaviour
nav the scrollbar.
issue 1:
when collapse or expand the planning
highcharts-gantt.src.js:47292 Uncaught TypeError: Cannot read property 'push' of undefined
    at highcharts-gantt.src.js:47292
    at Array.forEach (<anonymous>)
    at highcharts-gantt.src.js:47291
    at Array.forEach (<anonymous>)
    at r (highcharts-gantt.src.js:47287)
    at Object.getTree (highcharts-gantt.src.js:47381)
    at A (highcharts-gantt.src.js:48633)
    at highcharts-gantt.src.js:48694
    at Array.forEach (<anonymous>)
    at a.Chart.D (highcharts-gantt.src.js:48662)

issue 2:
when collapse or expand the the design
the develop will disappeared.

#### Live demo with steps to reproduce
https://jsfiddle.net/6qnwzxmf/

#### Product version
highcharts-gantt 7.1.1

#### Affected browser(s)
chrome

**Comment by sebastianbochan** [comment]
Hi @zonggang,
Thank you for reporting about the problem. This is known bug which has been already reported here: https://github.com/highcharts/highcharts/issues/10570.

Im closing this ticket as duplicate.
