### ISSUE TITLE
For a heatmap containing zones, hovering over and exiting a cell turns it light blue.

### ISSUE THREAD

**Issue by pietschk** [highcharts/highcharts#10670]
#### Expected behaviour
After hovering over and exiting a heatmap cell, it should return to its original color.

#### Actual behaviour
After hovering over and exiting a heatmap cell, it turns light blue if the heatmap contains zones. This occurs even if `plotOptions.heatmap.states.hover.enabled` is `false`.

#### Live demo with steps to reproduce
http://jsfiddle.net/wgs0a96j/
- Hover over and exit any cell.

#### Product version
Highcharts v6.0.7 (also tested against the [hosted version](https://code.highcharts.com/highcharts.js))

#### Affected browser(s)
Chrome v73

**Comment by sebastianbochan** [comment]
Hi @pietschk,
Thank you for reporting about the problem.

FYI @jon-a-nygaard
