### ISSUE TITLE
Responsive "spacing" option causes "maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by stevethemacguy** [highcharts/highcharts#10671]
#### Expected behaviour
Chart resizes without any errors.

#### Actual behaviour
Setting  the "spacing" option in the responsive rules causes the browser to hang and eventually throw an "Uncaught RangeError: Maximum call stack size exceeded" error.

#### Steps to reproduce:
Click the "Small" html button.

#### Live demo with steps to reproduce
https://jsfiddle.net/stevethemacguy/cnefr80w/

#### Product version
Highcharts 7.1.1 
(I upgraded from HighCharts 6.2.0, so I'm not sure which version introduced this bug)

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @stevethemacguy,
Thank you for reporting about the problem.

**Internal note**
Its a regression since v7.1.1

Related with https://github.com/highcharts/highcharts/issues/9795

Bisect leads me to https://github.com/highcharts/highcharts/commit/3ad430a

**Comment by stevethemacguy** [comment]
Hi @sebastianbochan, thanks for taking a look. Is there a known workaround besides avoiding the spacing option for now?

**Comment by pawelfus** [comment]
Version v7.1.0 is unaffected: https://jsfiddle.net/BlackLabel/txu1v6jb/ - will that do for now @stevethemacguy ?

**Comment by stevethemacguy** [comment]
Yes, that's fine. Thank you.
