### ISSUE TITLE
Networkgraph throws type error if you specify linkLength in typescript

### ISSUE THREAD

**Issue by michaelthegreat** [highcharts/highcharts#10686]
#### Expected behaviour
Highcharts API docs specifically mention that you can set linkLength in network graph layout algorithm options. https://api.highcharts.com/highcharts/series.networkgraph.layoutAlgorithm.linkLength

#### Actual behaviour
The typescript type definition for this does not include linkLength (highcharts.src.d.ts) and this causes compiler errors. (error pasted at the end of this issue). Propose adding linkLength as an optional field for the type definition of PlotNetworkgraphLayoutAlgorithmOptions. 

#### Live demo with steps to reproduce

Not reproducible using this template because this is a typescript specific issue

#### Product version

    "highcharts": "^7.1.1",
    "highcharts-angular": "^2.4.0",
#### Affected browser(s)
All browsers

ERROR in ...chart.ts(118,11): error TS2322: Type '{ cursor: string; type: "networkgraph"; layoutAlgorithm: { linkLength: number; integration: "euler"; maxIterations: number; enableSimulation: true; gravitationalConstant: number; }; point: { ...; }; data: string[]; dataLabels: { ...; }; }' is not assignable to type 'SeriesAbandsOptions | SeriesAdOptions | SeriesAoOptions | SeriesApoOptions | SeriesAreaOptions | SeriesArearangeOptions | SeriesAreasplineOptions | SeriesAreasplinerangeOptions | ... 88 more ... | SeriesZigzagOptions'.
  Type '{ cursor: string; type: "networkgraph"; layoutAlgorithm: { linkLength: number; integration: "euler"; maxIterations: number; enableSimulation: true; gravitationalConstant: number; }; point: { ...; }; data: string[]; dataLabels: { ...; }; }' is not assignable to type 'SeriesNetworkgraphOptions'.
    Types of property 'layoutAlgorithm' are incompatible.
      Type '{ linkLength: number; integration: "euler"; maxIterations: number; enableSimulation: true; gravitationalConstant: number; }' is not assignable to type 'PlotNetworkgraphLayoutAlgorithmOptions'.
        Object literal may only specify known properties, and 'linkLength' does not exist in type 'PlotNetworkgraphLayoutAlgorithmOptions'.

**Comment by pawelfus** [comment]
Hi @michaelthegreat 

Thanks for reporting this issue! 

@bre1470 - could you take a look?
