### ISSUE TITLE
Enable Datalabels when exporting multiple charts to single pdf file

### ISSUE THREAD

**Issue by Jeevanuday** [highcharts/highcharts#10688]
#### Expected behaviour

I want to export multiple charts to single **pdf** file with enabling dataLabels dynamically while exporting.

#### Actual behaviour

 I am able to export to png file with dataLabels, but i am not able to export to pdf file with dataLabels enabling dynamically.

#### Live demo with steps to reproduce
https://jsfiddle.net/JeevanUday/dnkor5Lp/1/

#### Product version
I am using a highchart gem.

**Comment by sebastianbochan** [comment]
Hi @Jeevanuday,
Thank you for reporting about the problem. The reason of that is really simple, incorrect configuration.

```
{
      plotOptions: {
        series: {
          dataLabels: {
            enabled: true
          }
        }
      }
    }
``` 

should be used as third argument of the `exportCharts` function.

Fixed demo:
- https://jsfiddle.net/BlackLabel/apdg1efn/

**Comment by Jeevanuday** [comment]
Thank you @sebastianbochan it was very helpful for me.

**Comment by Jeevanuday** [comment]
Hi @sebastianbochan 
Is their any way i can customize each chart's dataLabel style and export all at once.

**Comment by sebastianbochan** [comment]
I adapted the script to extracting options from the `exporting.chartOptions` object. 

Demo:
- https://jsfiddle.net/BlackLabel/8mjesa4L/

For the further [support](http://www.highcharts.com/support) questions, please use our forum / stackoverflow or email.
