### ISSUE TITLE
Series area does not always animate when updating data

### ISSUE THREAD

**Issue by rbudnar** [highcharts/highcharts#10696]
#### Expected behaviour
When setting/updating a series area's points, animation should be applied consistently.

See the below codepen for demo. The right series area should animate the same way the left series area does.

#### Actual behaviour
https://codepen.io/rbudnar/pen/vwLRee
There are two series areas in the codepen for demonstration. Please disregard the usage of the draggable module, it is for demonstration purposes only and the behavior described happens regardless of using dragging operations (e.g., I'll be using this programmatically).

The area on the left correctly animates when you drag the left column. It simply updates the second point of the data to reflect the new x tick and animation is applied as expected. This is what I want :+1:

The area on the right does NOT animate when dragging the right column. SetData runs without applying any animations (all I care about is duration in this case). This is incorrect behavior 👎 

EDIT: If it helps to find a workaround, in my use case there will always be exactly 2 points in each series area (overlay) - a start and an end. 

#### Live demo with steps to reproduce
https://codepen.io/rbudnar/pen/vwLRee
Drag the right column, observe 

#### Product version
Latest highcharts and highstock. Draggable module is in use.

#### Affected browser(s)
Chrome, firefox.

**Comment by pawelfus** [comment]
Thanks for reporting the issue @rbudnar 

**Workaround:**
Demo: https://codepen.io/anon/pen/KLzvXp

Snippet:
```js
(function (H) {
    H.wrap(H.seriesTypes.area.prototype, 'getGraphPath', function (p) {
      var path = p.apply(this, Array.prototype.slice.call(arguments, 1));
      
      delete path.xMap;
      delete this.areaPath.xMap;
      
      return path;
      
    })
})(Highcharts);
```

*Internal note:*
Stripped down to the `animate()` method for graph/line: https://jsfiddle.net/BlackLabel/1wxqo925/

Simplified demo: https://jsfiddle.net/BlackLabel/1wxqo925/1/
