### ISSUE TITLE
Venn diagram - invalid opacity after mouse out

### ISSUE THREAD

**Issue by jdrobiecki** [highcharts/highcharts#10699]
#### Expected behaviour
After hovering over the graph and moving out, colors should be the same.

#### Actual behaviour
Opacity is double applied.
g.highcharts-series-group > g has opacity set but shouldn't.

#### Live demo with steps to reproduce
https://jsfiddle.net/jgex9rc1/1/
1. mouse over the graph
2. move mouse out of the graph

#### Product version
Highcharts 7.1 and 7.1.1.
7.0 works fine.

#### Affected browser(s)
Chrome, FF.

**Comment by sebastianbochan** [comment]
Hi @jdrobiecki,
Thank you for reporting about the bug.

FYI @jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
Thanks again for reporting @jdrobiecki 

Internal Note: This issue is caused by the introduction of the inactive state in v7.1.0. At the moment it is configured to apply per series, while it should probably be configured to apply per point instead on the venn series.

**Comment by pawelfus** [comment]
It looks correct with `inactiveOtherPoints` (inactive state per point): https://jsfiddle.net/BlackLabel/jux84ke7/
