### ISSUE TITLE
Multiline labels do not work as expected

### ISSUE THREAD

**Issue by m-niedermaier** [highcharts/highcharts#10709]
#### Expected behaviour
3 Lines should be shown of the Data labels, but it works only if total height is modified.

#### Live demo with steps to reproduce
this works as expected:
https://jsfiddle.net/6wzq9rb0/5/

just modifying height from 160 to 150 results in label shows only one line for the label:
https://jsfiddle.net/6wzq9rb0/6/

**Comment by sebastianbochan** [comment]
Hi @m-niedermaier,
Thank you for reporting about the bug.

**Workaround**
You should overwrite the `word-wrap` CSS declaration by default option.

Demo:
- https://jsfiddle.net/BlackLabel/8sjpcfzh/

After that, you need to adapt `max-height` in your `format` option.

**Comment by m-niedermaier** [comment]
Yes, reducing the may-height also works. But it's more a workaround. But it's not clear why only one line is shown in this sample:

https://jsfiddle.net/6wzq9rb0/6/

If I set the height instead of the max-height the strange behavior becomes maybe a bit more clearer:
https://jsfiddle.net/r83x6asp/
