### ISSUE TITLE
How do I style the series labels on a pie chart?

### ISSUE THREAD

**Issue by biltongza** [highcharts/highcharts#10700]
I am trying to change the font-weight of the series labels on a pie chart, since the font we are using has a pretty terrible rendering of `font-weight: bold`:

![image](https://user-images.githubusercontent.com/2845704/57542328-a50abb80-7351-11e9-92a8-f4c1d1b033e3.png)

This is what I have tried so far (based on guidance from https://api.highcharts.com/highcharts/plotOptions.pie.label):
```
plotOptions: {
    pie: {
        label: {
            style: {
                fontWeight: 500,
            }
        }
    }
},

```
It seems to have no effect.

I'm using this for my global Highcharts config:
```
import * as Highcharts from "highcharts";
import * as HC_Series from 'highcharts/modules/series-label';

HC_Series(Highcharts);
Highcharts.setOptions({
    chart: {
        style: {
            fontFamily: '"Neue Helvetica W05", "M Hei HK W42", Arial, Helvetica, sans-serif',
        },
    },

});
```

#### Product version
Highcharts 6.2.0, highcharts-angular 2.4.0

**Comment by sebastianbochan** [comment]
Hi @biltongza,
Thank you for contacting us. The github is our tracker for reporting bugs, so w for general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.
