### ISSUE TITLE
highcharts.d.ts AxisLabelsFormatterContextObject is missing pos

### ISSUE THREAD

**Issue by OmarMustafa** [highcharts/highcharts#10703]
#### Expected behaviour
AxisLabelsFormatterContextObject should contain attribute "pos" of type number | undefined

#### Actual behaviour
AxisLabelsFormatterContextObject doesn't contain pos

#### Live demo with steps to reproduce
None, not needed.

#### Product version
7.1.1

#### Affected browser(s)
Not a browser issue

**Comment by KacperMadej** [comment]
Hi @OmarMustafa 

Thank you for notifying about the problem.
