### ISSUE TITLE
highcharts.d.ts Highcharts.Series is missing userOptions attribute

### ISSUE THREAD

**Issue by OmarMustafa** [highcharts/highcharts#10706]
#### Expected behaviour
Highcharts.Series is missing userOptions which contains at least tooltipEntryName

#### Actual behaviour
Series doesn't have userOptions

#### Live demo with steps to reproduce
None

#### Product version
7.1.1

#### Affected browser(s)
Not a browser issue

**Comment by sebastianbochan** [comment]
Hi @OmarMustafa,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by bre1470** [comment]
Hello @OmarMustafa,
Series.userOptions is at the moment internal. You can use `Chart.userOptions.series` or `Series.options`.

If you like to get the pure dynamic `Series.setOptions`, listen to the `setOptions` event like this:
```ts
const removeListener = Highcharts.addEvent(Highcharts.Series.prototype, 'setOptions', function (this: Highcharts.Series, args: Highcharts.Dictionary<object>) {
    console.log(args.userOptions as Highcharts.SeriesOptionsType);
});
```

Does this fits your use case?

**Comment by bre1470** [comment]
We have decided to remove `Series.setOptions` from the declarations. It is an internal function.

Please use the combination of `Series.update` and `Series.options`.
