### ISSUE TITLE
highcharts.d.ts TooltipOptions is missing attributes

### ISSUE THREAD

**Issue by OmarMustafa** [highcharts/highcharts#10704]
#### Expected behaviour
TooltipOptions is missing chart which is of type undefined | {
            chartHeight: number;
            chartWidth: number;
        }

#### Actual behaviour
TooltipOptions doesn't have it

#### Live demo with steps to reproduce
None

#### Product version
7.1.1

#### Affected browser(s)
Not a browser issue

**Comment by KacperMadej** [comment]
Hi @OmarMustafa 

Thank you for notifying about the problem.

**Comment by bre1470** [comment]
`TooltipOptions` does not support these properties, use `Highcharts.Tooltip.chart.chartWidth`.
