### ISSUE TITLE
highcharts.d.ts Highcharts.Series is missing graph attribute

### ISSUE THREAD

**Issue by OmarMustafa** [highcharts/highcharts#10705]
#### Expected behaviour
Series is missing
graph?: GraphObject;

#### Actual behaviour
Series doesn't have it

#### Live demo with steps to reproduce
None

#### Product version
7.1.1

#### Affected browser(s)
Not a browser issue

**Comment by sebastianbochan** [comment]
Hi @OmarMustafa,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by bre1470** [comment]
I see no indication, that `Highcharts.Series#graph` should be public. It is used internal only.

Workaround

**Comment by bre1470** [comment]
I see no indication, that Highcharts.Series#graph should be public. It is used internal only.

Workaround: `(series as any).graph as Highcharts.SVGElement`

@OmarMustafa 
For which purpose do you need it?

**Comment by OmarMustafa** [comment]
@bre1470 we use it to change the color of the series on hover.
`mouseOver: function(): void {
    if (this.graph && this.graph.stroke === lineColorNotSelected) {
        this.graph.attr("stroke", lineColorOnHover);
    }
},
mouseOut ... // similar code, with lineColorNotSelected`

I filed the bug to avoid casting to any, thinking it's missed, but if it's internal, then I can do that.

**Comment by bre1470** [comment]
Thank you for the insight. We have decided to make `Series.graph` an official property together with `Series.area`, so casting is in the future not necessary anymore.

**Comment by bre1470** [comment]
Internal note: Probably a hint in the description, that `zones` option hides default `area` & `graph` could be a good idea. (@pawelfus)
