### ISSUE TITLE
highcharts.d.ts PatternOptionsObject.width is mispelled

### ISSUE THREAD

**Issue by OmarMustafa** [highcharts/highcharts#10702]
#### Expected behaviour
Per the docs
    /**
     * Width of the pattern. For images this is automatically set to the width
     * of the element bounding box if not supplied. For non-image patterns the
     * default is 32px. ...
     */
    with: number;

#### Actual behaviour
"width" is mispelled to "with"

#### Live demo with steps to reproduce
None, not needed.

#### Product version
7.1.1

#### Affected browser(s)
Not a browser issue

#### Fix
Fix typo to width

**Comment by KacperMadej** [comment]
Hi @OmarMustafa 

Thank you for notifying about the problem.

**Comment by OmarMustafa** [comment]
@bre1470 can you please take a look at this. Should be a simple fix.
Thanks.

**Comment by bre1470** [comment]
@OmarMustafa Thank you for the report. Fix should be soon go into master and released with the next update.
