### ISSUE TITLE
Theme: minified files has invalid code

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#10714]
#### Behaviour
Due to an error caused by difference between .src.js and .js file versions:

https://github.com/highcharts/highcharts-dist/blob/8c6661a7b36bbed9f9fb679610af023c96c31373/themes/sunset.src.js#L23
`var _modules = Highcharts ? Highcharts._modules : {};`

https://github.com/highcharts/highcharts-dist/blob/master/themes/sunset.js#L26
`var _modules = {};`

I found that the minified file is not minified at all and is different than the .src.js code.

This looks like an error in generating files.
fyi: @bre1470

**Comment by bre1470** [comment]
Looks like follow up dist tasks are overwriting the minification.

**Comment by bre1470** [comment]
FYI @TorsteinHonsi
