### ISSUE TITLE
xAxis Breaks Cause xAxis Label Gaps

### ISSUE THREAD

**Issue by toddgroff** [highcharts/highcharts#10718]
#### Expected behaviour
When using xAxis breaks on a line chart, I would expect xAxis labels to be determined with breaks in mind so as to avoid gaps in xAxis labels.

#### Actual behaviour
When xAxis breaks are included (in my case, to exclude weekends on a 'datetime' xAxis), xAxis labels appear gappy because labels that would be within a break are, understandably, not rendered. 

Is there a known workaround or approach to have the xAxis label locations calculated with breaks in mind to maintain a consistent label spread and avoid gaps?

#### Live demo with steps to reproduce
http://jsfiddle.net/zjgxmw4q/2/

#### Product version
6.0.2
7.1.1

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @toddgroff 

Thanks for reporting the issue. I think this is problem with breaks config. xAxis labels are rendered at 00:00:00.000 (for days). In your case, break-end is defined at ~07:00:00.000 so part of the day is removed, the part where label is defined. With simple changing hours to midnight, we get proper results, take a look: http://jsfiddle.net/BlackLabel/gd7p3n5m/1/

**Comment by toddgroff** [comment]
Thanks for responding so quickly @pawelfus 

Unfortunately, when I make the suggested change, Friday points are no longer shown as you'll notice in your jsfiddle. 

My colleague and I found a sort of workaround by modifying the `tickPositions` array within the `xAxis.tickPositioner` callback function to help reduce some of those gaps. 

Thanks again!
