### ISSUE TITLE
xAxis.reversed should reverse partialFill

### ISSUE THREAD

**Issue by eladmotola** [highcharts/highcharts#10717]
#### Expected behaviour
Setting opposite:true should flip the partialFill 

#### Actual behaviour
partialFill behave like opposite:false

#### Live demo with steps to reproduce
https://codepen.io/anon/pen/GajLxQ

If it's not working, open codepen from https://www.highcharts.com/demo/x-range
copy and paste the following config:

`Highcharts.chart('container', {
  chart: {
    type: 'xrange'
  },
  title: {
    text: 'Highcharts X-range'
  },
  xAxis: {
    type: 'datetime',
    reversed:true
  },
  yAxis: {
    title: {
      text: ''
    },
    categories: ['Prototyping'],
    reversed: true,
    opposite:true
  },
  series: [{
    name: 'Project 1',
    // pointPadding: 0,
    // groupPadding: 0,
    borderColor: 'gray',
    pointWidth: 20,
    data: [{
      x: Date.UTC(2014, 10, 21),
      x2: Date.UTC(2014, 11, 2),
      y: 0,
      color:'rgb(124, 181, 236)', //blue
      partialFill: {
        amount:0.25,
        fill:'rgb(144, 237, 125)' //green
      }
    }],
    dataLabels: {
      enabled: false
    }
  }]
});`

#### Product version
Latest highcharts - 7.1.1, as used in your xrange codepen example

#### Affected browser(s)
Chrome 74, i dont know for others.

I can "trick" this by changing the colors and set amount to 0.75( 1- 0.25 ....)
But I dont see it as a good behavior.

**Comment by pawelfus** [comment]
Hi @eladmotola 

Thanks for reporting the issue. [yAxis.opposite](https://api.highcharts.com/highcharts/yAxis.opposite) controls where axis should be rendered (labels, ticks, title etc). That option does not change anything else (like `partialFill`). If you want opposite effect, then yes, I suggest to calculate new `partialFill.amount`. 

Maybe you mean `xAxis.reversed`, not `yAxis.opposite` ? Then yes, I would expect partialFill starting from the right edge of the point.

**Comment by eladmotola** [comment]
@pawelfus yes you are right, it's `xAxis.reversed` . The combination of all moving the graph to the right made me confused when openning the issue. So thank you for the correction.
