### ISSUE TITLE
Solid gauge data label is misaligned

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#10712]
#### Expected behaviour
The data label gets rendered dead center when I use verticalAlign "middle".

#### Actual behaviour
The data label gets rendered below center.
I can rectify this by using y: 0, suggesting that you apply a wrong default value for y.

#### Live demo with steps to reproduce
http://jsfiddle.net/kzoon/3L2wer8d/
With my workaround: http://jsfiddle.net/kzoon/3L2wer8d/5/

**Comment by pawelfus** [comment]
Hi @kzoon 

This is expected behaviour. By default, dataLabel has offset (y=16). When you change `verticalAlign` option, you should also change `y`.

**Comment by kzoon** [comment]
Without changing verticalAlign it looks like this: http://jsfiddle.net/kzoon/3L2wer8d/6/
Maybe the default dataLabel offset is not particularly suitable for this chart type?

**Comment by pawelfus** [comment]
Yes, maybe. @TorsteinHonsi - what do you think? Historically we have changed this default value between versions (30 -> 35 -> 16).

**Comment by TorsteinHonsi** [comment]
The default value 15 is inherited from the `gauge` series. In the gauge, the data label is [shifted down to avoid covering the pivot](https://github.com/highcharts/highcharts/blob/cb5c4d8ab96c944bb890d1225ba8cad1e7c46553/js/parts-more/GaugeSeries.js#L58-L59). 

So I agree with @kzoon, it shouldn't do that in a solid gauge. Will fix.
