### ISSUE TITLE
Collapse of a column chart bars after drilldown

### ISSUE THREAD

**Issue by fiantsev** [highcharts/highcharts#10715]
#### Expected behaviour

1. click on any column bar
2. after drilldown - i can see bars and labels

#### Actual behaviour
column bars are collapsed

#### Live demo with steps to reproduce
[https://jsfiddle.net/rnoq8d42/7/](https://jsfiddle.net/rnoq8d42/7/)

#### Product version
Highcharts: 6.2.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thanks @fiantsev for reporting this issue. It looks like a general issue with updating xAxis categories from short strings to long ones. Simplified demo to `setData()`: https://jsfiddle.net/BlackLabel/09rkLqme/ - the same result.

Could you simplify your names for categories? Those are really long. For example limit length of a category to ~25characters? Something like this: https://jsfiddle.net/BlackLabel/09rkLqme/2/

**Comment by TorsteinHonsi** [comment]
Definately a bug in the label handling. Interestingly, it's only the labels on the left side that are too long.

**Comment by TorsteinHonsi** [comment]
It's a regression, bisected to 08b85659e7ec4f4ff979fe338b39d2ed8776276c

**Comment by fiantsev** [comment]
thanks for workaround, i will try if new version doesnt fix it))
