### ISSUE TITLE
Missing TypeScript definitions Highcharts.Color()

### ISSUE THREAD

**Issue by adumesny** [highcharts/highcharts#10725]
#### Actual behaviour
copied some sample code that deals with radialGradient in a typescript app

import * as Highcharts from 'highcharts';
...
Highcharts.Color(color).brighten(-0.3).get('rgb')

gives error (but runs fine) that Color() is not defined (other classes/methods are showing ok in VS Code as code hint...

had to do this to compile 
(Highcharts as any).Color(color).brighten(-0.3).get('rgb')

#### Product version
highcharts@7.1.1, typescript@2.9.2

#### Full code
private _options: Highcharts.Options = {
  colors: Highcharts.map(Highcharts.getOptions().colors, function(color: Highcharts.ColorString) {
      return {
        radialGradient: {
          cx: 0.5,
          cy: 0.3,
          r: 0.7
        },
        stops: [
          [0, color],
          [1, (Highcharts as any).Color(color).brighten(-0.3).get('rgb')] // darken
        ]
      };
  })
};
public ngOnInit() {
  Highcharts.chart('container', this._options);
}

**Comment by sebastianbochan** [comment]
Hi @adumesny,
Thank you for reporting.

FYI @bre1470

**Comment by bre1470** [comment]
@adumesny 
`Highcharts.Color` is a internal class. You are supposed to use `Highcharts.ColorString` and `Highcharts.GradientColorObject`.

@TorsteinHonsi 
Maybe we should make `Highcharts.Color` official?

**Comment by TorsteinHonsi** [comment]
Yes I think so. We're actually using it in some of our samples.

**Comment by adumesny** [comment]
> Yes I think so. We're actually using it in some of our samples.

yep, that's where I got it from https://www.highcharts.com/demo/pie-gradient
Note that Highcharts.ColorString and Highcharts.GradientColorObject are not defined either in TS definition files... Might want to add them too.
