### ISSUE TITLE
Funnel 3d Legend

### ISSUE THREAD

**Issue by nithyavanig** [highcharts/highcharts#10724]
#### Expected behaviour
The series data names should be available in legend in Funnel -3d , just like funnel series.

#### Actual behaviour
The series data names are not available. Only the measure names are displayed in the legend.

#### Live demo with steps to reproduce
Same series in "funnel" and "funnel3d" chart types.
In funnel type, the legend is getting displayed properly.
In funnel-3d, the legend shows a different one.

https://jsfiddle.net/nithivani86/n7xkcwrf/9/
https://jsfiddle.net/nithivani86/tw2kn8Lc/20/

**Comment by KacperMadej** [comment]
Hi @nithyavanig 

Thank you for reporting about the problem.

Currently this type of legend is not supported, but when few options are changed and the click item for legend is copied from pie type series you could have a chart like this: https://jsfiddle.net/BlackLabel/8mpfeLhs/

The main difference is that when a point is hidden others are not recalculated.
