### ISSUE TITLE
Highstocks - Bar chart with one series incorrect scrollbars

### ISSUE THREAD

**Issue by chored** [highcharts/highcharts#10733]
#### Expected behaviour

When displaying a bar chart with a single series, scrollbars enabled and xAxis min/max both set to 0 the scrollbar thumb height should take up the whole size of the scrollbar and scrolling shouldn't be possible. 

#### Actual behaviour

The scrollbar thumb is non-existent (rendered outside the scrollbar area?) and clicking on the up/down arrows scrolls away from the data.

In addition, errors are thrown in the console:

Error: <rect> attribute height: Expected length, "NaN".

#### Live demo with steps to reproduce
https://jsfiddle.net/davewilkie/2za39gku/3/

Click on either the up or down arrow on the scrollbar

#### Product version

Highstocks - 7.1.0 and 7.1.1

This worked as expected in 7.0.3 - same fiddle as above for old version:

https://jsfiddle.net/davewilkie/2za39gku/1

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @chored 

Thanks for reporting this regression!

**Workaround:**
Modify extremes a bit: https://jsfiddle.net/BlackLabel/skwo2cLe/

*Internal note:*
Bisect leads to e866e68cb
