### ISSUE TITLE
Sunburst - Export CSV Multiple data with same name prints only once in CSV

### ISSUE THREAD

**Issue by jeffersonswartz** [highcharts/highcharts#10737]
#### Expected behaviour
Export should show all the data of a parent.

#### Actual behaviour
The different parent having children with same name prints once

#### Live demo with steps to reproduce

https://jsfiddle.net/w6cg7m05/
In the above fiddle, each parent has the same children names. All the similar names data are printed once in the CSV, unless we name them different.

#### Product version

Highcharts 7.1.0
#### Affected browser(s)
Chrome Version 74.0.3729.131 (Official Build) (64-bit) - Windows 10

**Comment by pawelfus** [comment]
Thanks for reporting @jeffersonswartz 

**Simplified demo:**
https://jsfiddle.net/BlackLabel/51c9ksap/ - it's caused by the same name for series that don't require sorting.

*Internal note:*
Seems to be an easy fix, I will dig a bit tomorrow (`xTaken` changes key too late).
