### ISSUE TITLE
Highstock: old points not removed after updating data with dataGrouping enabled

### ISSUE THREAD

**Issue by julamb** [highcharts/highcharts#10745]
When updating a spline series' data, the line updates correctly but the point markers from the previous data are not removed. Disabling dataGrouping for this serie fixes the issue.

https://jsfiddle.net/mn0f78z9/
Click the button to update the series data, the old points are not removed. Set `dataGrouping` to `false` to fix the issue.

In this example, the old data has daily points and the new data has hourly points (there's more points, and closer to each other), so it probably has something to do with a series switching from non-grouped points to grouped points.

I could not find an existing issue on github but the same problem and its cause seems to be discussed here: https://www.highcharts.com/forum/viewtopic.php?t=16188

#### Product version
Highstocks v7.1.1

**Comment by pawelfus** [comment]
Hi @julamb 

Thanks for reporting this bug. It seems to be a bug in `series.update()` method. Using recommended `series.setData()` is unaffected: https://jsfiddle.net/BlackLabel/8sd2jhvL/

**Workaround:**
Use [`series.setData(newData)`](https://api.highcharts.com/class-reference/Highcharts.Series#setData): https://jsfiddle.net/BlackLabel/8sd2jhvL/

*Internal note:*
Probably `keepPoints` flag is wrong.
