### ISSUE TITLE
boost-canvas crashes when rendering large series (arearange)

### ISSUE THREAD

**Issue by known-as-bmf** [highcharts/highcharts#10758]
It seems that rendering area range on very large series with boost (more precisely boost-canvas) imported crashes

Tests ran with:
* Firefox (66.0.5 (64 bits))
* Chrome Version 74.0.3729.157 (Build officiel) (64 bits)

#### Expected behaviour
Chart rendering wether boost or boost-canvas is used

#### Actual behaviour
Highcharts detects WebGL in Chrome and renders fine,
Highcharts does not detect WebGL in Firefox - error 26 - and crash in `boost-canvas.js:196` `c.eachAsync is not a function`

#### Live demo with steps to reproduce

* Run the above link in Chrome and Firefox
* Chrome should render without issue
* Firefox should not
https://jsfiddle.net/5mte784s/1/

#### Product version

Highcharts latest version (7.1.1)

**Comment by sebastianbochan** [comment]
Hi @known-as-bmf,
Thank you for reporting about the bug. Currently I did not receive any errors in the Firefox, as a result I was not able to reproduce the issue.

MacOSX 10.12.4.
FF: 66.0.3

Please let me know about your OS / FF version details.

**Comment by known-as-bmf** [comment]
Hi,

Thank you for the feedback

I'm using Windows 10 (1809) and the latest FF 66.0.5 (64 bits)

I think the problem is in the boost-canvas module, have you tried disabling WebGL and running the jsfiddle ?

I guess it only happens in FF on my machine because WebGL isn't properly detected

**Comment by sebastianbochan** [comment]
Hi,
I will test and get back to you with the feedback.

**Comment by sebastianbochan** [comment]
Hi @known-as-bmf,
I tested in the same environment like yours and still was not able to reproduce the issue. Is it possible to reproduce it in different stable conditions?

**Comment by known-as-bmf** [comment]
To reproduce in Chrome:

* close all instances of chrome
* launch chrome with command line: `chrome --disable-webgl`
* test that webgl is disabled here https://webglreport.com/?v=1
* go to https://jsfiddle.net/5mte784s/1/

the following error should appear `Uncaught TypeError: c.eachAsync is not a function`

**Comment by sebastianbochan** [comment]
Hi @known-as-bmf,
Thank you for details. Now I was able to reproduce the issue.

Windows: 10 (1809)
Chrome: 74.0.3729.157 x64
Disabled webgl.

**Internal note**
The `boost.seriesThreshold = 1` does not solve the issue, like I expected when found the other bug: https://github.com/highcharts/highcharts/issues/6842.

FYI @cvasseng

**Comment by andnig** [comment]
Hey guys, any news on this issue. I also have troubles with this one as it seems.

**Comment by sebastianbochan** [comment]
I have passed the case to our boost developers. He will answer you as soon as possible.

@cvasseng
