### ISSUE TITLE
Title , SubTitle overlaps when Vertical Align property is set

### ISSUE THREAD

**Issue by ShivaRam1989** [highcharts/highcharts#10755]
#### Expected behaviour
title ,subtitle should maintain space between both when 'vertical align property is set to either top or bottom . It should not overlap each other , when floating is false and 'y' property is not set.
#### Actual behaviour

Title and Subtitle overlaps whenever Vertical Align property is set irrespective of floating property set to true or false

#### Live demo with steps to reproduce
https://jsfiddle.net/shivaram1989/3yezLav1/1/

#### Product version
Highcharts 6.0.7

#### Affected browser(s)
All browsers

**Comment by vbinithyanandamv** [comment]
Any particular reason why you don't want to use yoffset to avoid overlap?

**Comment by ShivaRam1989** [comment]
@vbinithyanandamv yes when i set y offset for title , subtitle, legend it works, but then the legend overlaps on chart when i add series dynamically. In my case u have to add series dynamically and should not overlap chart

**Comment by vbinithyanandamv** [comment]
> @vbinithyanandamv yes when i set y offset for title , subtitle, legend it works, but then the legend overlaps on chart when i add series dynamically. In my case u have to add series dynamically and should not overlap chart

My one suggestion would be why don't you give margin to your chart area since am not sure completely about the problem. Thanks for the prompt reply.

**Comment by pawelfus** [comment]
Hi @ShivaRam1989 

This works as expected. Setting `vertlicalAlign` makes tooltip floating always, see docs: [`title.verticalAlign`](https://api.highcharts.com/highcharts/title.verticalAlign): 
> The vertical alignment of the title. Can be one of "top", "middle" and "bottom". When a value is given, the title behaves as if floating were true.

**Comment by ShivaRam1989** [comment]
@pawelfus i understand , so if we change the **verticalAlign** dynamically , is it expected to be floating as true ?

**Comment by pawelfus** [comment]
That's correct @ShivaRam1989 - when setting **`title.verticalAlign`**, title behaves the same way as if `title.floating` was set to true, no matter what will be set in `title.floating` option.

**Comment by ShivaRam1989** [comment]
Thanks for the information
