### ISSUE TITLE
Labels do not support rotation, is falling back to text, and ignores useHTML.

### ISSUE THREAD

**Issue by IgorFIE** [highcharts/highcharts#10765]
#### Expected behaviour
When I create a sunburst with labels, set isHTML to true, create a css class with a property like color:red, implement formatter on data label for sunburst and return a span with the css class.
It should draw the text red, for what I found the sunbrust is not being converted to html, because we still have <tspan's> instead of <span's>, and I need to use fill to actually apply the color.

This works for column charts, so I would expect it to work the same way for sunburst.

#### Live demo with steps to reproduce
column chart example : https://jsfiddle.net/IgorFIE/k4t1cja9/3/
sunburst example: https://jsfiddle.net/IgorFIE/bnuvayz7/2/

**Comment by sebastianbochan** [comment]
Hi @IgorFIE,
Thank you for reporting about the problem.

**Internal note**
I debugged the `dataLabels` method and useHTML is used properly. But in the `tree module` dataLabels method overwrite some parameters.

FYI @jon-a-nygaard Could you take look at it?

**Comment by IgorFIE** [comment]
I also notice that when you actually do this it creates a new <tspan> with the new information, making the label having two values on top of the other, if you take the fill from the default one, you can see it more clean. in this example it's not a bigger problem but in my own data the text actually overrides one another. I would say that it should remove the default one and only apply the new one or combine the two of them. Since this works correctly on pie charts, I also put a image of the html as an example.

Data from before:
![Screenshot from 2019-05-22 09-37-01](https://user-images.githubusercontent.com/17085338/58160202-ec5c4a80-7c75-11e9-8a69-e39988da324c.png)

My own data example:
![Screenshot from 2019-05-22 09-37-46](https://user-images.githubusercontent.com/17085338/58160294-1150bd80-7c76-11e9-8096-ab169081ee19.png)

Pie chart example data:
![Screenshot from 2019-05-22 09-59-24](https://user-images.githubusercontent.com/17085338/58161520-4d851d80-7c78-11e9-9af6-dec4fe9d6a9d.png)

**Comment by jon-a-nygaard** [comment]
Thanks again for reporting.

@sebastianbochan This is likely not an issue in sunburst, but with the support of rotation on data labels, see the following: https://github.com/highcharts/highcharts/blob/c7251e2ad1e17404f68193593d6ffe43ba162ed1/js/parts/DataLabels.js#L932-L949

The same issue appears in column and other series types when we apply rotation to data labels, it is just more apparent in sunburst which utilize rotation heavily. Please see following example https://jsfiddle.net/jon_a_nygaard/c60dL8wa/
