### ISSUE TITLE
series.animation.step callback isn't working for all series and is not documented.

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10760]
I haven't found any documentation about **series.animation.step**. Step method is defined globally in H.Fx.prototype.step, but isn't working for all series.

https://jsfiddle.net/BlackLabel/cnvearz3

#### Product version
Highcharts 7.1.1

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
It's currently regarded internal, and is working well where needed. Should we choose to expose it, we need to make it reliable for all series too.
