### ISSUE TITLE
Vertical scroll: unable to scroll on touch device

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#10768]
#### Expected behaviour
Default 2 finger scroll to scroll the chart and a 1 finger scroll to scroll the web site.

#### Actual behaviour
Only the arrow buttons on the ends of the scrollbar are working on a touch device.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/hsm957qg/3/show

Open on a mobile device and try to scroll page and the chart.

#### Affected devices
Tested on Android 7.0 and iPad

about scrollbar fyi: @pawelfus

**Comment by TorsteinHonsi** [comment]
An alternative approach to fixing could be to enable vertical scrolling in `scrollablePlotArea`. It works in a different way, by rendering the plot area in a specific div, and will provide a much smoother scrolling experience for both mobile and desktop. 

It is already a popular request at #9378.

**Comment by sebastianbochan** [comment]
The idea with `scrollablePlotArea` sounds good, but im afraid that in combination with this bug https://github.com/highcharts/highcharts/issues/8607 will be really limited.

**Comment by TorsteinHonsi** [comment]
Work in progress on `scrollablePlotArea`: https://highcharts.github.io/highcharts-utils/samples/#gh/f67b942449/sample/highcharts/chart/scrollable-plotarea-vertical

> The idea with scrollablePlotArea sounds good, but im afraid that in combination with this bug #8607 will be really limited.

That shouldn't be too hard to fix.
