### ISSUE TITLE
Tooltip ClassName instead of highcharts-tooltip

### ISSUE THREAD

**Issue by IgorFIE** [highcharts/highcharts#10766]
This is more of a improvement, tooltip should have a ClassName so we can use our own unique class's on a tooltip instead of using highcharts-tooltip css class. We can see this behaviour/ implementation in https://api.highcharts.com/highcharts/chart.className

**Comment by sebastianbochan** [comment]
Hi @IgorFIE,
Thank you for your suggestion, I set the enhancement status of the case.
