### ISSUE TITLE
When adding data dynamically, MACD draws incorrectly

### ISSUE THREAD

**Issue by mysex** [highcharts/highcharts#10774]
#### Expected behaviour
When adding data points dynamically, MACD index changes dynamically and renders correctly

#### Actual behaviour

Macd draws errors when changing range selector or dragging navigation after adding data points dynamically

#### Live demo with steps to reproduce

[https://jsfiddle.net/92w71byk/4/](url)

operation：
1.  change rangeSelector 
2.  drag navigation

**Comment by sebastianbochan** [comment]
Hi @mysex,
Thank you for reporting about the problem. When I run your demo, I was not able to reproduce your issue.

![macd](https://user-images.githubusercontent.com/2115686/58160618-1d8d4880-7c7f-11e9-8ed2-363c20dce953.gif)


Please share your OS / browser details (including full number of version) and correct me if Im doing something wrong.

MacOSX: 10.12.4
Chrome: 74.0.3729.157

**Comment by mysex** [comment]
Hi @Sebastian，
 
Thank you for your reply. I saw an error in drawing the MACD line in your screenshot. This may be due to the dynamic addition of data after drawing. You can see the screenshot I gave you. Its MACD has turned into red stripes.







------------------ 原始邮件 ------------------
发件人: "Sebastian"<notifications@github.com>; 
发送时间: 2019年5月22日(星期三) 下午4:48
收件人: "highcharts/highcharts"<highcharts@noreply.github.com>; 
抄送: "邢天乐"<1085075895@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [highcharts/highcharts] When adding data dynamically, MACD drawsincorrectly (#10774)




Hi @mysex,
 Thank you for reporting about the problem. When I run your demo, I was not able to reproduce your issue.
 

 
Please share your OS / browser details (including full number of version) and correct me if Im doing something wrong.
 
MacOSX: 10.12.4
 Chrome: 74.0.3729.157

**Comment by sebastianbochan** [comment]
Hi @mysex,
Thank you for your feedback. I was focused on errors in console and missed columns issue. Now all is clear.

**Internal note**
Its a regression since v7.0.3.
Bisect leads me to https://github.com/highslide-software/highcharts.com/commit/3620b52
