### ISSUE TITLE
Add documentation for labelRank for stackLabels

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#10773]
#### Behaviour
The option is respected and works, but is not documented.
xAxis.stackLabels.labelRank
yAxis.stackLabels.labelRank

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/47fnm06w/

Related UserVoice ticket: https://highcharts.uservoice.com/admin/v3/suggestions/37673596/

**Comment by TorsteinHonsi** [comment]
I don't think this is currently implemented.

In the jsFiddle, the applied option is `labelRank`, but in the code it is lowercase `labelrank`.

Plus, it is already hard coded and doesn't look for an option: https://github.com/highcharts/highcharts/blob/4144ab944058c4b878b64d96b08262001496882b/ts/parts/Stacking.ts#L332

**Comment by KacperMadej** [comment]
If it is possible to predict what value will be set for `labelrank` for stackLabels then it is possible to set `labelrank` for series dataLabels to decide the order. 

The enhancement seems to be pointless in this case. I will close this for now, but if anyone has any relevant comments then the issue could be reopened.
