### ISSUE TITLE
innerRadius option doesn't exists in plotOptions::solidgauge

### ISSUE THREAD

**Issue by SaeedZhiany** [highcharts/highcharts#10777]
#### Expected behaviour
Allow setting `innerRadius` option within plotOption::solidgauge

#### Actual behaviour
Gives TS2322 error because the `innerRadius` is not defined in `PlotSolidgaugeOptions` interface

#### Live demo with steps to reproduce
there is no need to example

#### Product version
highcharts version: 7.1.1

**Comment by sebastianbochan** [comment]
Hi @SaeedZhiany,
Thank you for reporting about the problem.

FYI @bre1470
