### ISSUE TITLE
Gantt points disappear when have same start and end times.

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10781]
#### Expected behaviour
All points are rendered.

#### Actual behaviour
When multiple points have the same start and end time, only the last of them is rendered.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/zmwrpa1o

#### Product version
Gantt 7.1.1

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
**Internal note**
FYI @jon-a-nygaard

**Comment by raf18seb** [comment]
Internal note: when resizing, the last of the mentioned points jumps on the place of the first point and chart isn't displaying all points but adapts.

**Comment by jon-a-nygaard** [comment]
Internal Note: Regression since v7.1.0

**Comment by jon-a-nygaard** [comment]
Seems to have been fixed in latest version v7.1.2, see https://jsfiddle.net/BlackLabel/86x5esmw
