### ISSUE TITLE
Show tool tip on hovering datalabel

### ISSUE THREAD

**Issue by Amarnath92** [highcharts/highcharts#10785]
#### Expected behaviour
When inserting a data label(lets say data label is an image) for each bars, hovering on the image should display a pop hover message with some custom style. How we can achieve this in angular application.  Please provide your input ASAP.

#### Actual behaviour
Inserted the data labels but we could see only the tool tip always. Please find the below link for working demo. Here i am expecting on hover of the data label should show the custom pop hover or a tool tip with a link.

http://jsfiddle.net/q5s09oaz/7/ 

And provide some input how we can position the image in the data labels.

**Comment by sebastianbochan** [comment]
Hi @Amarnath92,
Thank you for contacting us. The github is our bug tracker for reporting issues, so for general [support](http://www.highcharts.com/support) questions please use forum / email or stackoverflow.
