### ISSUE TITLE
Feature request: adding some sort of options to include or exclude series from exporting

### ISSUE THREAD

**Issue by SaeedZhiany** [highcharts/highcharts#10783]
#### Expected behaviour
some times we have to use some tricks to generate some special shapes because there is no straight forward approach to achieve what we want. for example, take a look at two charts below:

![image](https://user-images.githubusercontent.com/13766432/58149341-c33cb980-7c77-11e9-8cc4-64dc57dd82ef.png)

I couldn't find a normal way to draw some progress bars using highcharts options; so I achieve the chart by drawing a bar chart and define a fake series two generate the gray part to simulate a progress bar. that's OK and it works fine, **But the main problem** is when I want to export the chart to a CSV file. the fake data is also exported. So I have to override export function to exclude them and only export real chart data. I just thought I would be great if there are some boolean options that we could specify a series must be exported or not in different export functionalities.

something like this:

```
series: [
    {
        // other options
        export: {
            always: true, // for enabling or disabling for all export functionalities 
            PNG: true,
            JPG:  true,
            CVS: false,
            and other export extensions: 
        }
    }
]
```

for another example please take a look at pictures below,
I use pie chart options to generate a chart like this:
![Annotation 2019-05-22 101334](https://user-images.githubusercontent.com/13766432/58150275-63481200-7c7b-11e9-85ee-47a452041ef8.jpg)

when user disable all series by clicking legend items the chart is shown as picture below,
![Annotation 2019-05-22 101022](https://user-images.githubusercontent.com/13766432/58150351-9ab6be80-7c7b-11e9-8924-54a16fb8481a.jpg)

but I like to show my chart as the picture below:
<img width="209" alt="sadsadsadasddsa" src="https://user-images.githubusercontent.com/13766432/58150401-bde16e00-7c7b-11e9-8988-1d9650878b43.png">

So similar to the previous example I have to show fake data in these cases and there is a chance that user want to export a CSV file from such chart. it's better to see an empty CSV file by the user than non-relevant fake data.

#### Actual behaviour
There is no such option to exclude some series from export.

**Comment by sebastianbochan** [comment]
Hi @SaeedZhiany,
Thank you for contacting us. The github is our bug tracker, so please share your idea in our uservoice [here](https://highcharts.uservoice.com/).
