### ISSUE TITLE
Feature Request: Enable second row of boxes in timeline

### ISSUE THREAD

**Issue by leenooks** [highcharts/highcharts#10798]
#### Expected behaviour
In the timeline graph, if there is sufficient height in the graph, it would be great if the points that are hidden because `overlap: false` is set, that if there was space to render "two" (or more) rows of boxes (with longer connecting dots) that those boxes were rendered  above/below the original boxes.

#### Actual behaviour
With `overlap:false` rendered boxes are now shown. (Which is still good.)

**Comment by sebastianbochan** [comment]
Hi @leenooks,
Thank you for your suggestion.

Please share your ideas in our [uservoice](https://highcharts.uservoice.com) service where other users can vote for the idea too. It will allow us to implement the most popular ideas in our products.
