### ISSUE TITLE
Highstock series removed , but still on chart

### ISSUE THREAD

**Issue by Konbuscus** [highcharts/highcharts#10795]
#### Expected behaviour
All series on chart are removed

#### Actual behaviour
Before remove : 
![BeforeRemove](https://user-images.githubusercontent.com/9660713/58186578-75df3d00-7cb5-11e9-89cd-b81df744b1c2.JPG)

After remove : 
![AfterRemove](https://user-images.githubusercontent.com/9660713/58186604-81326880-7cb5-11e9-8098-6444beaafda9.JPG)

Series in dom are removed, but chart still displays the series.
On the console chart.series.length gives me 0.
#### Live demo with steps to reproduce

Can't reproduce for security reasons. 
However it happens only on the last call of chart.series[0].remove(false);
chart.redraw() is called when all series are totally removed.
Series are removed from legend.
No interactions with the "After remove".
During display process, minDateNavigator is edited to match a certain date.
but minDateNavigator is not edited while series are being removed.

No errors are raised in the console.

#### Product version
Highchart v 5.014 and Highstock v 6.0.1

#### Affected browser(s)

All

**Comment by sebastianbochan** [comment]
Hi @Konbuscus,
Have you tried to update to the newest HS 7.1.1? If not, please try and let me know if problem still appears.

**Comment by sebastianbochan** [comment]
Im closing this ticket due to inactvitation.

Please reopen if live demo and additional details will be available.
