### ISSUE TITLE
Dependency breaks when navigation is applied.

### ISSUE THREAD

**Issue by AnanditaP** [highcharts/highcharts#10804]
Please find detailed information inside attached document

[HighGanttPOCIssue1.docx](https://github.com/highcharts/highcharts/files/3211312/HighGanttPOCIssue1.docx)

**Comment by raf18seb** [comment]
Hi @AnanditaP, 
Thank you for reporting this issue.

Dependency arrows are rendered incorrectly when using Gantt with navigator.

#### Live demo with steps to reproduce
Simplified jsFiddle: https://jsfiddle.net/BlackLabel/xcsyab72

#### Product version
Gantt v7.1.1

#### Affected browser(s)
All

FYI @jon-a-nygaard

**Comment by datiecher** [comment]
Any idea when we might expect this one to get fixed? A Gantt chart that uses dependencies and has a navigator seems like a common enough use-case.

**Comment by jon-a-nygaard** [comment]
Thanks again for reporting.

I am currently looking into the issue, and will come back to you with more information as soon as I know more during today.

**Comment by jon-a-nygaard** [comment]
I have submitted a PR which solves this issue. It is currently in review, but expected to be included in the next maintenance version v7.1.3.

Unfortunately I do not see an easy workaround for this issue that can be used in the meantime.

**Comment by KrullCepush** [comment]
this problem is relevant today(

**Comment by KacperMadej** [comment]
@KrullCepush 
Unable to recreate. Please add a live demo.
Check v7.1.2 ([demo](https://jsfiddle.net/BlackLabel/xcsyab72/19/)) to be sure the same problem shows and if not, consider opening a new issue for a new problem.
