### ISSUE TITLE
 Two line charts series -> states -> hover -> enabled: false does not work

### ISSUE THREAD

**Issue by Rasmus060780** [highcharts/highcharts#10807]
#### Expected behaviour
            series -> states -> hover -> enabled: false 

Should disable hovering effects for all series as i read the documentation.

As extra info was found updating a page from Highcharts v4.1.10 to v7.1.1. The 4.1.10 had some issues with the Edge browser where parts of lines and areas dissapeared when hovering. 7.1.1 fixed that issue but introduced unwanted hovering effects on charts with multiple lines or coumns. Therefore we wanted to disable to hover effects, but was not able to do so.

#### Actual behaviour

Does not work in graph with more then one line.
Similar issue for column charts.

#### Live demo with steps to reproduce
One line working:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-states-hover-enabled/

Two lines not working:
https://jsfiddle.net/6ojeLqma/

#### Product version
Newest Highcharts

#### Affected browser(s)
Reporduced in Edge and Chrome

**Comment by raf18seb** [comment]
Hi @Rasmus060780, 

In v7.1.0 we added a new state which actually is the opposite of hover. It's called **inactive state** and you can read about it here: https://www.highcharts.com/blog/changelog/#highcharts-v7.1.0
and find it in docs here: https://api.highcharts.com/highcharts/plotOptions.series.states.inactive

To disable it, simply set inactive.opacity property to 1:
`plotOptions: {
        series: {
            states: {
                hover: {
                    enabled: false
                },
                inactive: {
                		opacity: 1
                }
            }
        }
    },`
Demo: https://jsfiddle.net/BlackLabel/fqj08n3a

**Comment by Rasmus060780** [comment]
Solved by setting the inacttive state that apperently sets the opacity of the other lines not beign hovered to e.g. 1:
            states: { inactive: {opacity: 1}, }
or maybe even
            states: { inactive: {opacity: 0.8}, }
That in my view is a lot better effect- that could maybe be better explained in the docuemntation... :-)
