### ISSUE TITLE
Gauge dataLabel disappears in Firefox

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10803]
Sometimes a dataLabel in gauge disappears in Firefox.

I couldn't find a pattern, but it depends on chart's height, yAxis.min and max and number of digits in data.
Works fine in 7.0.1. Doesn't work from 7.0.2.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/cz47d2kv

#### Product version
The issue occurs since Highcharts **7.0.2**

#### Affected browser(s)
Firefox 67

**Comment by pawelfus** [comment]
**Workaround:**
Set `dataLabels.allowOverlap` to true: https://jsfiddle.net/BlackLabel/cz47d2kv/2/

Bisected to commit 0a5d555a3e

**Comment by sebastianbochan** [comment]
The issue is also valid in Chrome: 79.0.3945.88 (MacOSX: 10.14.5).

**Comment by KacperMadej** [comment]
Working correctly in v9.1.0
Closing as resolved
