### ISSUE TITLE
Missing `tooltipOptions` for class Series type

### ISSUE THREAD

**Issue by briwa** [highcharts/highcharts#10814]
#### Expected behaviour
I should be able to find the types for `tooltipOptions` in Series Class when using Highcharts in Typescript.

#### Actual behaviour
There isn't any type for `tooltipOptions` in class Series. 
![Screen Shot 2019-05-24 at 12 12 49 PM](https://user-images.githubusercontent.com/8046636/58302357-48ad9e80-7e1d-11e9-9029-e248f03e2707.png)
Also, there isn't one in the [docs](https://api.highcharts.com/class-reference/Highcharts.Series) as well.

In the code, it seems to be there (CMIIW): https://github.com/highcharts/highcharts/blame/master/js/parts/Series.js#L2738

#### Live demo with steps to reproduce
Hover on any of the tooltips and see the console tab:
https://jsfiddle.net/eqw9ztvm/

#### Product version
I'm using Highcharts v7.1.1

#### Affected browser(s)
None

#### Note
I'm starting to think, is this supposed to be a private property (because it's not exposed in the docs)? If it is, might still wanna add in the type definitions too as private.

**Comment by sebastianbochan** [comment]
Hi @briwa,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by TorsteinHonsi** [comment]
@briwa There are many private properties in the Highcharts classes that are not (and should not be) exposed. 

Probably you should access `series.options.tooltip` or the general `tooltip.options` instead. What is your use case?

**Comment by briwa** [comment]
@TorsteinHonsi Yes, my approach can definitely be changed. I was just thinking since it's there in the [code](https://github.com/highcharts/highcharts/blame/master/js/parts/Series.js#L2738), I just thought it was publicly available. So basically, if it's not in the docs, it's not meant to be public anyway, so it doesn't have the typing. Is that correct?

**Comment by bre1470** [comment]
Yes, that is our approach. Usually we try to expose as few properties as possible to prevent any future compatibility issues.

Additionally our TypeScript declarations are already huge, so we prefer to keep all private members out of it. I will therefor close this issue with a `won't fix` label.

Nevertheless feel free to point out missing properties, if there is no way to get them via other properties or functions.
