### ISSUE TITLE
Unicode in labels converted on getSVG()

### ISSUE THREAD

**Issue by OriginalJef** [highcharts/highcharts#10825]
#### Expected behaviour
When I export an SVG the unicode arrows `&#x25b6;` I defined in combination with my labels are shown as plain text in my SVG. The `getSVG()` function turns the `&` into `&amp;` which results in `&amp;#x25b6;`. 

#### Actual behaviour
It should be shown in SVG exactly as it is on web.

#### Live demo with steps to reproduce
https://jsfiddle.net/q9m31opt/1/
-> download as SVG

#### Product version
7.0.3

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @OriginalJef,
Thank you for reporting about the problem. You should enable the `exporting.allowHTML` parameter.

**Demo:**
- https://jsfiddle.net/BlackLabel/umewsn3o/

**Docs**
- https://api.highcharts.com/highcharts/exporting.allowHTML
