### ISSUE TITLE
Network graph nodes connected line click event

### ISSUE THREAD

**Issue by leosun1221** [highcharts/highcharts#10829]
#### Expected behaviour

When I click on the connected line between two nodes, I want to trigger click event, and find the connected node information

#### Actual behaviour

not trigger

**Comment by sebastianbochan** [comment]
Hi @leosun1221,
Thank you for contacting us. This is our bug tracker for reporting bugs, so for general feature request please us our our uservoice service: https://highcharts.uservoice.com
