### ISSUE TITLE
Network graph Zoom in/out

### ISSUE THREAD

**Issue by leosun1221** [highcharts/highcharts#10828]
#### Expected behaviour

 Should be able to zoom in/out the network graph with the zoomType config

chart: {
       type: 'networkgraph',
       zoomType: 'xy'
}

#### Actual behaviour

unable to zoom in/out the network graph

**Comment by sebastianbochan** [comment]
Hi @leosun1221,
Thank you for reporting about the problem. The zoom option is available only when chart has x and y axis and can apply extremes (min and max values).

In case of pie / gauge / packed bubble / networkgraph series do not use axis. As a result this option is not available, because we cannot predict extremes.

**Comment by tushar-git-lti** [comment]
HaHaHa Behold! I present you a solution!

**Comment by tushar-git-lti** [comment]
Behold Fellas As My First Ever Community Contribution I bring you a possible solution, ;)
Well, it can be done by  ngx-panZoom: https://www.npmjs.com/package/ngx-panzoom.

Apply PanZoom on the div you use to render HighCharts. e.g
<pan-zoom [config]="panZoomConfig">
     <highcharts-chart
                  [Highcharts]="Highcharts"
                  ....................some options 
                ></highcharts-chart>
                   
                       or

            <div id='toRenderHighchart'></div>
</pan-zoom>

NOTE : 
JUST MAKE SURE THE PARENT DIV OF <pan-zoom></pan-zoom> SHOULD HAVE FIXED DIMENSIONS i.e. not dynamic not in %

**Comment by crackerranjan** [comment]
HAHHAHA , Behold Fellas As My First Ever Community Contribution I bring you a possible solution, ;)
Well, it can be done by  ngx-panZoom: https://www.npmjs.com/package/ngx-panzoom.

Apply PanZoom on the div you use to render HighCharts.
 e.g

```
<pan-zoom [config]="panZoomConfig">
             <highcharts-chart
                  [Highcharts]="Highcharts"
                  ....................some options 
               ></highcharts-chart>
                       
                or the other way to render

             <div id='toRenderHighchart'></div>
</pan-zoom>
```

NOTE : 
JUST MAKE SURE THE PARENT DIV OF `<pan-zoom></pan-zoom>` SHOULD HAVE FIXED DIMENSIONS i.e. not dynamic not in %
