### ISSUE TITLE
Animation in zoom x axis does not work with more 4 series

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#10832]
The axis is not animated, where the series is >= 4

![3](https://user-images.githubusercontent.com/6030335/58455963-a0088300-812b-11e9-8a40-665e6381d38c.gif)

#### Expected behaviour
animated

#### Actual behaviour
not animated

#### Live demo with steps to reproduce
https://jsfiddle.net/eoLrung6/2/

#### Product version
Highcharts 7.1.1

#### Affected browser(s)
Google Chrome 74.0.3729.169

**Comment by sebastianbochan** [comment]
Hi @balkarov,
Thank you for reporting the bug.

**Internal note:**
In case of using 3 series, the zooming animation is triggered.

Demo:
- https://jsfiddle.net/BlackLabel/tzy14cud/

Editing the `animationLimit` does not solve the problem too.

**Comment by TorsteinHonsi** [comment]
Yes, somehow we need to pass over the animation limit, though I don't think we should introduce another option.

**Comment by sebastianbochan** [comment]
The problem is that we have access to chart, not current rendered series. It was one of the reasons of idea of extra param.

**Comment by pawelfus** [comment]
Perhaps we can include `chart.animation` option here? [API](https://api.highcharts.com/highcharts/chart.animation) says that animation by default is enabled ("true") which is incorrect - it's `undefined` but we treat this as `true`. Setting `animation: true` could be a solution then.

**Comment by TorsteinHonsi** [comment]
Actually this is a docs issue. In reality, `chart.animation` is undefined, which defaults to a `pick` where it tests the point count. We need to reflect that in the docs. 
The simple workaround for this issue is to set `chart.animation` to true.

**Comment by balkarov** [comment]
Version 8.0.4 it did not fix. Why you closed?

**Comment by pawelfus** [comment]
@balkarov - did you set `chart.animation = true`? Demo: https://jsfiddle.net/BlackLabel/9n7boywm/
