### ISSUE TITLE
Loading circle animation not working when giving 'verticalAlign' for 'setTitle'

### ISSUE THREAD

**Issue by hakkim** [highcharts/highcharts#10835]
#### Expected behaviour
While giving` verticalAlign: 'middle',` for `chart.setTitle` the pie chart must be loading with a circle animation

#### Actual behaviour
Chart is simply loading with a slight bottom to animation instead of circle drawing effect. If we remove ` verticalAlign: 'middle',` it will work. in Highchart v7.0.3 it works fine

#### Live demo with steps to reproduce

https://codepen.io/abdulhakkim/pen/PvBmmj

#### Product version

Highchart v7.1.1 - Having issue
Highchart v7.0.3 - Not having issue

#### Affected browser(s)
Browser - Chrome

**Comment by sebastianbochan** [comment]
Hi @hakkim,
Thank you for reporting about the problem.

**Internal note**
Bisect leads me to https://github.com/highcharts/highcharts/commit/60b19fe

FYI @pawelfus

**Comment by pawelfus** [comment]
This is already fixed, see master branch: https://codepen.io/anon/pen/byzxxx

Already reported as #10540. Closing as duplicate.
