### ISSUE TITLE
Error With Funnel.js

### ISSUE THREAD

**Issue by danura** [highcharts/highcharts#10830]
#### Expected behaviour

Pyramid Does Not Work 
#### Actual behaviour

Uncaught TypeError: Cannot read property 'parts/Globals.js' of undefined
    at funnel.src.js:31
    at funnel.src.js:22
    at funnel.src.js:11
#### Product version

7.1.1

**Comment by sebastianbochan** [comment]
Hi @danura,
Please ensure that all your files (Highcharts, exporting etc) are in the same version 7.1.1.

**Comment by sebastianbochan** [comment]
Im closing this ticket as duplicate of https://github.com/highcharts/highcharts/issues/10465
