### ISSUE TITLE
Data labels color `contrast` triggers incorrectly 

### ISSUE THREAD

**Issue by ovidiu-munteanu** [highcharts/highcharts#10838]
#### Expected behaviour
`color: 'contrast'` is triggered incorrectly for some data labels when certain combinations of increased font size and relatively small chart container are used - see the JSFiddle example.

#### Actual behaviour
`color: 'contrast'` should not trigger for the given case - see the JSFiddle example.

#### Live demo with steps to reproduce
https://jsfiddle.net/hu9eyj0b/1/

#### Product version
Highcharts 6.1.1

#### Affected browser(s)
Browser agnostic.

**Comment by sebastianbochan** [comment]
Hi @ovidiu-munteanu,
Thank you for reporting about the problem.

**Simplified demo:**
- https://jsfiddle.net/BlackLabel/qwu213xf/

_Internal note_
It looks like a problem with custom color palette or title margins. When disable one of this option, solves problem.

**Comment by pawelfus** [comment]
*Internal note:*
Looks similar to #6657 - bisect leads to different commit, but it's probably caused by height of the chart.

**Comment by pawelfus** [comment]
Fixed on master branch: https://jsfiddle.net/BlackLabel/4x1saLbc/
