### ISSUE TITLE
Fix samples that access `Highcharts.theme` instead of `Highcharts.defaultOptions`

### ISSUE THREAD

**Issue by adumesny** [highcharts/highcharts#10840]
#### Expected behaviour
sample doc code https://www.highcharts.com/demo/pie-basic doesn't compile under typescript due to Highcharts .theme not defined. similar to #10725

#### Actual behaviour
plotOptions: {
      pie: {
        allowPointSelect: true,
        cursor: 'pointer',
        dataLabels: {
          enabled: false,
          format: '{point.name}: {point.y}',
          style: {
            color: ((Highcharts as any).theme && (Highcharts as any).theme.contrastTextColor) || 'black' // theme not defined in 7.1.1

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/pie-basic/

#### Product version
7.1.1

**Comment by sebastianbochan** [comment]
Hi @adumesny,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by bre1470** [comment]
The examples have to be fixed. All theme options are applied to `Highcharts.defaultOptions` and should be referenced there instead.

So the line of code in the example should be written like this:
```
color: Highcharts.defaultOptions.title.style.color || 'black' // theme 
```

**Comment by adumesny** [comment]
ok thanks. yes I've been relying on the doc samples to learn my way though those options...

**Comment by bre1470** [comment]
Potentially every option can be undefined. Usually TypeScript should be complaining about misuse of it. To be sure about the existence, you have to inline check agains undefined:
```
color: Highcharts.defaultOptions.title && Highcharts.defaultOptions.title.style && Highcharts.defaultOptions.title.style.color || 'black' // theme 
```

**Comment by adumesny** [comment]
or you can do something like that with later TS: `Highcharts.defaultOptions?.title?.style?.color) || 'black'` but wasn't sure if it ever set (on when...). thanks.
