### ISSUE TITLE
Serie marker disappears in legend when serie color is gradient

### ISSUE THREAD

**Issue by Astimus** [highcharts/highcharts#10841]
There are two series on the chart. One is gradient color and one is solid color. There is no marker for the first serie in the legend.
https://jsfiddle.net/capwogr8/2/
![image](https://user-images.githubusercontent.com/7124116/58539235-94868c00-81ff-11e9-8b49-0fd9c037cbf1.png)

But when I press on the gradient serie in the legend, a marker appears.
![image](https://user-images.githubusercontent.com/7124116/58539374-e16a6280-81ff-11e9-90ff-b2ab85655de1.png)

Of course, I want the gradient serie marker to be visible in the legend and colored in gradient.

#### Product version
highcharts 6.2.0

#### Affected browser(s)
Google Chrome 74.0.3729.169 (64 bit)

**Comment by sebastianbochan** [comment]
Hi @Astimus,
Thank you for contacting us. Im closing this ticket as duplicate of https://github.com/highcharts/highcharts/issues/1936.

**Comment by Astimus** [comment]
@sebastianbochan thank you
