### ISSUE TITLE
export data downloadXLS: the filename is wrong

### ISSUE THREAD

**Issue by prui** [highcharts/highcharts#10849]
#### Expected behaviour
my chart title text is like  'XX_AA_2015-09-8_2016-08-09'( XX is Chinese),
but exported filename is 'aa-2015-09-8-2016-08-09.xls',
and when i use excel open this file , it will have a waring:
**The file format and extension do not match. The file may be damaged or unsafe. Do not open unless you trust its source. Do you still want to open it?**

#### Actual behaviour
i hope get the right filename like my chart title，and do not have a warning when i open this file

#### Live demo with steps to reproduce

just use the funtion chart.downloadXLS

#### Product version

in package.json: "highcharts": "^7.1.1",

#### Affected browser(s)
in mac chrome

**Comment by sebastianbochan** [comment]
Hi @prui,
Have you tried to set [title.useHTML](https://api.highcharts.com/highcharts/title.useHTML) and [exporting.allowHTML](https://api.highcharts.com/highcharts/exporting.allowHTML) parameters as true? If problem will be still valid, could you share your chart as live demo (i.e by jsfiddle.net service). It will allow us to debug the problem.

**Comment by prui** [comment]
It does not work. It look like then then export-data can not set Chinese and '_' to the filename , Chinese will be ignore and '_' will replace by '-'. I use downloadXLS() to export a excel file.
Here is our chart options: （I am sorry that it is very slow to use jsfiddle in China）
{
      chart: {
        type: 'areaspline'
      },
      legend: {
        align: 'right',
        verticalAlign: 'top',
        x: -106,
        y: -94,
        floating: false,
        itemMarginTop: 5,
        itemStyle: {
          color: '#333',
          fontWeight: 'normal',
          fontSize: '14px'
        },
        symbolHeight: 8,
        symbolWidth: 8,
        navigation: {
          activeColor: '#F8981C',
          animation: true,
          arrowSize: 10,
          inactiveColor: '#CCC',
          style: {
            fontWeight: 'bold',
            color: '#333',
            fontSize: '12px'
          }
        }
      },
      title: {
        text: '表格二_DAU_2019-05-16_2019-05-30',
        style: {
          visibility: 'hidden'
        },
        margin: 70
      },
      exporting:{
        allowHTML:true
      },
      tooltip: {
        enabled: false
      },
      xAxis: {
        categories: xAxisData,
        offset: 10,
        tickmarkPlacement: 'on',
        title: {
          text: '时间',
          style: {
            color: 'transparent'
          }
        },
        lineColor: 'white',
        tickColor: 'white',
        labels: {
          style: {
            color: '#333',
            fontWeight: 'bold',
            fontFamily: 'Microsoft YaHei',
            fontSize: 12
          }
        }
      },
      yAxis: {
        min: 0,
        minRange: 1,
        allowDecimals: false,
        title: {
          text: ''
        },
        labels: {
          style: {
            color: '#666',
            fontFamily: 'Microsoft YaHei',
          }
        },
        gridLineColor: '#EEE'
      },
      credits: {
        enabled: false
      },
      plotOptions: {
        areaspline: {
          enableMouseTracking: false,
          dataLabels: {
            enabled: true,
            style: {
              fontSize: 14,
              color: '#333',
              fontFamily: 'Microsoft YaHei',
              fontWeight: 'normal'
            }
          },
          stacking: 'normal',
          lineColor: '#F8981C',
          lineWidth: 2,
          marker: {
            lineWidth: 1,
            radius: 2,
            lineColor: '#F8981C',
            symbol: 'circle',
            fillColor: 'white'
          }
        },
      },
      series: [{
        name: 'xxxx',
        data: [],
        color: '#F8981C',
        fillOpacity: 0.05
      }],
      navigation: {
        buttonOptions: {
          enabled: false
        }
      }
    }

**Comment by sebastianbochan** [comment]
Hi @prui,
Thank you for reporting. It looks like a problem with extracting chinese from the title, like in the simplfiied demo:
- https://jsfiddle.net/BlackLabel/vcwj65nt/

But when you use `exporting.filename` option, then file is correct.
**Demo:**
- https://jsfiddle.net/BlackLabel/c3r1s4gm/

**Internal note**
FYI @oysteinmoseng

**Comment by prui** [comment]
Think you, it resolve my problem.
However, there is still have a warning when i open the exported file in my mac office excel, and I want to know what make this warning, is a bug or other reason?
Here is the waring: The file format and extension do not match. The file may be damaged or unsafe. Do not open unless you trust its source. Do you still want to open it?

**Comment by sebastianbochan** [comment]
Hi @prui,
The warning is known issue which is already reported here: https://github.com/highcharts/highcharts/issues/7977.

**Comment by prui** [comment]
Ok, thank you very much

**Comment by oysteinmoseng** [comment]
I would consider this a bug, as we should be able to read the correct unicode text content from the title to build the filename by default

**Comment by TorsteinHonsi** [comment]
The file name comes from this function: 

https://github.com/highcharts/highcharts/blame/85afba68e2d312b981a5469a1903cfab7a106f14/js/modules/exporting.src.js#L1289-L1313

The current function is designed to only allow latin characters a-z, which is robust, but not satisfactory if the title is, say, completely made out of Chinese or Arabic characters. For languages like the Scandinavian ones, German or French, it is mainly satisfactory because most characters are latin.

I haven't found a reliable way to match letters of all languages. This one works in Chrome and Safari, but fails in Firefox:

`.replace(/[^\p{L}0-9-]/ug, '') // preserve only characters, numbers and dashes`

See https://jsfiddle.net/highcharts/p7an3wzf/1/
