### ISSUE TITLE
Exporting large data sets as blob uses obsolete function

### ISSUE THREAD

**Issue by ondrusekjoshua** [highcharts/highcharts#10848]
#### Expected behaviour
When trying to export large data sets, I expect to either to be able to download the data, or for the chart to display a message saying it's too much data.

#### Actual behaviour
Currently, nothing happens, and an error is output to the console: 'Failed to convert to blob'. This only occurs when the `dataURL` is larger than 2000000, because when this is the case, it attempts to convert it to blob. This if-case is in the `downloadURL` function in 'highcharts/js/mixins/download-url.js'. After this, eventually `getBlobFromContent` is called in 'highcharts/js/modules/export-data.src.js'. This is where the error occurs. This function attempt to call `win.navigator.msSaveOrOpenBlob`. At runtime, the function `msSaveOrOpenBlob` appears to be undefined, causing this export to fail.

Checking [https://developer.mozilla.org/en-US/docs/Web/API/Navigator/msSaveOrOpenBlob](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/msSaveOrOpenBlob) indicates that this function is both non-standard and obsolete, which would make sense as to why it is undefined at runtime.

#### Live demo with steps to reproduce
[https://jsfiddle.net/rdgb98ps/](https://jsfiddle.net/rdgb98ps/)
This is demo highstocks chart is slightly changed to attempt to download right after chart creation. 

#### Product version
Highcharts JS v7.1.1 (2019-04-09)

#### Affected browser(s)
Tested in:
- Firefox 66.0.4 
- Chrome 74.0.3729.157

**Comment by sebastianbochan** [comment]
Hi @ondrusekjoshua,
Thank you for reporting about the problem. I passed the case to our exporting developer and he will answer you as soon as possible.

FYI @cvasseng
