### ISSUE TITLE
`yAxis.stackLabels` inline styles in `styledMode`

### ISSUE THREAD

**Issue by sntran** [highcharts/highcharts#10855]
With the following configuration:

```js
{
  chart: {
    styledMode: true
  },
  yAxis: {
    stackLabels: {
      enabled: true
    }
  },
  plotOptions: {
    column: {
      stacking: `normal`
    }
  }
}
```

#### Expected behaviour

The rendered SVG should have the following:

```svg
<g class="highcharts-stack-label" visibility="visible" data-z-index="6" transform="translate(35,10)" aria-hidden="true">
  <text x="255"  text-anchor="middle" transform="translate(0,0)" y="37">
    <tspan x="255" y="37" class="highcharts-text-outline" fill="#FFFFFF" stroke="#FFFFFF" stroke-width="2px" stroke-linejoin="round" style="">6</tspan>
    <tspan x="255" y="37">6</tspan>
  </text>
</g>
```

The class should be `highcharts-stack-label`, and the inner `<text>` should not have `style` attribute (per [documentation](https://api.highcharts.com/highcharts/yAxis.stackLabels))

#### Actual behaviour

```svg
<g class="highcharts-stack-labels" visibility="visible" data-z-index="6" transform="translate(35,10)" aria-hidden="true">
  <text x="255" style="color:#000000;font-size:11px;font-weight:bold;fill:#000000;" text-anchor="middle" transform="translate(0,0)" y="37">
    <tspan x="255" y="37" class="highcharts-text-outline" fill="#FFFFFF" stroke="#FFFFFF" stroke-width="2px" stroke-linejoin="round" style="">6</tspan>
    <tspan x="255" y="37">6</tspan>
  </text>
</g>
```

The class is `highcharts-stack-labels` and inner text has `style` attribute, making it harder to style using CSS.

#### Live demo with steps to reproduce

https://jsfiddle.net/3n7aet14/

#### Product version

Highcharts v7.1.1

#### Affected browser(s)
Google Chrome version 74.0.3729.169 (Official Build) (64-bit).

**Comment by sebastianbochan** [comment]
Hi @sntran,
Thank you for reporting about the bug.
