### ISSUE TITLE
Regression since 7.0.2: Click handlers leak on data series

### ISSUE THREAD

**Issue by davidje13** [highcharts/highcharts#10861]
#### Expected behaviour
When assigning a click handler (likely applies to any kind of event) on a data series:

```javascript
{
  // ...
  series: [
    {
      events: {
        click: (e) => console.log(e)
      }
    }
  ]
}
```

This click handler should be removed if the options are changed (i.e. they should be replaced with the newly provided click handler, or removed entirely if no click handler is given).

#### Actual behaviour
Each time the data changes, a new click handler is *appended*. In applications where clicking causes a refresh, this situation causes an exponential build-up of handlers (eventually hanging the page).

Note that if the click handler is the exact same function as already registered, it will not build up (in the example above, a new lambda is defined each time, but providing `console.log` directly will not demonstrate the bug)

This was observed when using the [highcharts-angular](https://github.com/highcharts/highcharts-angular) wrapper, but is a bug in the core project. It was introduced by [this commit](https://github.com/highcharts/highcharts/pull/10256/commits/9c5bc9198d5675d7c7f5f674e7737eca3ba0b7bf) which was to address https://github.com/highcharts/highcharts/issues/10010

#### Live demo with steps to reproduce
https://jsfiddle.net/hLv9dc0u/

Open the console, click update a few times, then click a bar. The event will be logged many times instead of just once.

#### Product version
7.1.1 (no bug in 7.0.2)

#### Affected browser(s)

Tested in Chrome, likely applies to all.

**Comment by sebastianbochan** [comment]
Hi @davidje13,
Thank you for reporting about the problem.

**Comment by pawelfus** [comment]
Bisected to commit 0b42ff0c61
