### ISSUE TITLE
LinearGauge Chart need right click action 

### ISSUE THREAD

**Issue by RamakrishnanVBI** [highcharts/highcharts#10862]
#### Expected behaviour
After adding the third party library file **customEvents.js**, in my chart right click in chart events
contextmenu function is want to show some details.

#### Actual behaviour
Now right click is chart event function it does not enter the contextmenu function.

#### Live demo with steps to reproduce
https://jsfiddle.net/z0a4h6k9/2/

**Comment by sebastianbochan** [comment]
Hi @RamakrishnanVBI,
The case is related with `custom-event` plugin, so I moved this problem to appropriate repo.

https://github.com/blacklabel/custom_events/issues/137
