### ISSUE TITLE
HighChart doesn't load after reinstalling

### ISSUE THREAD

**Issue by SaeedZhiany** [highcharts/highcharts#10864]
#### Expected behaviour
Work just like before reinstalling.

#### Actual behaviour
For some reason, I had to remove `node_module` folder and reinstall my project dependencies again. I didn't change the version of highcharts dependency, but after installing the dependencies my project does not run and give me this error: 
```
./node_modules/highcharts/lib/canvg.js
Module not found: Can't resolve 'stackblur' in '......\workspace\project_name\node_modules\highcharts\lib'
```

I worked perfectly before the reinstallation. also, I tried to clean npm-cache folder, remove package-lock.json and reinstall again but no success.

#### Live demo with steps to reproduce
---

#### Product version
7.1.1

#### Affected browser(s)
all browsers

**Comment by sebastianbochan** [comment]
Hi @SaeedZhiany,
Thank you for contacting us. Have you tried to use `rm -rf node_modules && npm i` ?

**Comment by SaeedZhiany** [comment]
I am on windows and `rm` is not a window command, but as I mentioned before, I removed `node_modules ` folder manually and reinstall dependencies.

If it's matter, I must mention that I use Highcharts library in typescript based react project, and my index.tsx file looks like below:

```
import * as Highcharts from 'highcharts';
import solidGauge from 'highcharts/modules/solid-gauge';
import exporting from 'highcharts/modules/exporting';
import offlineExporting from 'highcharts/modules/offline-exporting';
import exportData from 'highcharts/modules/export-data';

// @ts-ignore
window.canvg = require( 'highcharts/lib/canvg');

// @ts-ignore
window.jsPDF = require('highcharts/lib/jspdf');

// @ts-ignore
window.svg2pdf = require( 'highcharts/lib/svg2pdf');

// @ts-ignore
window.Highcharts = Highcharts;

solidGauge(Highcharts);
exporting(Highcharts);
offlineExporting(Highcharts);
exportData(Highcharts);
```

**Comment by KacperMadej** [comment]
The missing modules should be installed via require and are used in the canvg library after `require("rgbcolor"),require("stackblur")`, so please try to manually install the packages to resolve the conflict.

**Comment by SaeedZhiany** [comment]
I tried to install stackblur dependency in my `pakcage.json` and import it like below:

```
// @ts-ignore
window.stackblur = require( 'stackblur-canvas/src/stackblur');
```

but still, the error remains. must I install the `rgbcolor` too?
I really wonder why my code worked before I remove and reinstall dependencies. I didn't any changes in my code, I just reinstall the dependencies.

**Comment by SaeedZhiany** [comment]
Already the relevant part of my index.tsx file is like below:

```
import * as Highcharts from 'highcharts';
import solidGauge from 'highcharts/modules/solid-gauge';
import exporting from 'highcharts/modules/exporting';
import offlineExporting from 'highcharts/modules/offline-exporting';
import exportData from 'highcharts/modules/export-data';
require("rgbcolor");
require("stackblur");

// @ts-ignore
window.canvg = require( 'highcharts/lib/canvg');

// @ts-ignore
window.jsPDF = require('highcharts/lib/jspdf');

// @ts-ignore
window.svg2pdf = require( 'highcharts/lib/svg2pdf');

// @ts-ignore
window.Highcharts = Highcharts;

solidGauge(Highcharts);
exporting(Highcharts);
offlineExporting(Highcharts);
exportData(Highcharts);
```

but the error remains.

**Comment by KacperMadej** [comment]
`require("stackblur")` runs in `canvg` and it cannot be resolved, so maybe installing the package in the main app using `npm` or `yarn` could help?

You have `require("stackblur");` in your code - doesn't it throw any errors? Have you changed TS or React environment options in a way that could cause any of those problems?

Please create a simple app that could be used to build a live demo or use an online sandbox to recreate the problem and the error.

**Comment by SaeedZhiany** [comment]
@KacperMadej 

AS I mentioned I installed the two dependencies in my main app.

before I have no `require('stackblur)` or `require('rgbcolor')` in my code and it worked without any problem. also adding the codes according to your advice does not resolve the problem and doesn't throw any new error but the same error I mentioned earlier:

```
 ./node_modules/highcharts/lib/canvg.js
Module not found: Can't resolve 'stackblur' in '...........\workspace\project_name\node_modules\highcharts\lib'
```

Also, I didn't change any TS or react environment options. As I said before I just upgrade project's other dependencies and reinstall all dependencies by remove `node_module` and run `npm install` command

**Comment by SaeedZhiany** [comment]
@KacperMadej @sebastianbochan 

Unfortunately, I couldn't reproduce the problem but I realize that it's not really necessary adding `require(...)` as you said. please see [my sample](https://codesandbox.io/s/great-hellman-opj0r)

Although I can not reproduce the problem (because I don't know how to remove `node_modules` folder in sandbox) I'm sure I didn't change anything related to Highcharts library

**Comment by SaeedZhiany** [comment]
@KacperMadej 

Can you please test the scenario on your PC? my case is not really reproducible on online editors

**Comment by KacperMadej** [comment]
@SaeedZhiany 
Yes, I can test the project as soon as you could share files required to run it.
It will be better to this than to recreate the issue by using the shared code from the sandbox demo, because even slight differences might prevent the problem from being reproduced.

**Comment by SaeedZhiany** [comment]
@KacperMadej 

fortunately, I can finally reproduce in a simple app by creating from scratch project and already share it in [this GitHub repository](https://github.com/SaeedZhiany/my-app).

in this app, when you try to start the app, you will get the error below

```
Failed to compile.

./node_modules/highcharts/lib/canvg.js
Module not found: Can't resolve 'rgbcolor' in 'C:\Users\SAEED\WebstormProjects\my-app\node_modules\highcharts\lib'
```

Although, in this case, the problem is with `rgbcolor`, I'm sure the problem is the same as the one in my main project.

**Comment by SaeedZhiany** [comment]
@KacperMadej 

I think I could solve the problem, I try this way yesterday but I don't really have any idea why didn't work.

I install `stackblur` and `rgbcolor` in my project and everything just works (without needing to import them using `require` function). I guess before upgrading and reinstalling my dependencies, `stackblur` and `rgbcolor` were peer-dependencies of my other project dependencies and installed in `node_modules` folder automatically so I didn't get any error.

However, I think it's better to add a description to [this page](https://www.highcharts.com/docs/export-module/client-side-export) to inform users that they must install `stackblur` and `rgbcolor` dependencies themselves.

Also, I took a look at highcharts `lib` directory, I'm wondering why the two files `rgbcolor.js` and `rgbcolor.src.js` exist in that directory? is there any internal usage from the files? if so, why you guys didn't include `stackblur.js` and `stackblur.src.js` files too?

![image](https://user-images.githubusercontent.com/13766432/58875120-efc4ec80-86df-11e9-845c-7194ff39c72e.png)

**Comment by KacperMadej** [comment]
> note that you must install stackblur dependency not stackblur-canvas.

This what I have suggested through

> require("stackblur") runs in canvg and it cannot be resolved, so maybe installing the package in the main app using npm or yarn could help?

Anyway, thank you for finding the source of the problem.

I'll label this issue as docs enhancement.

> Also, I took a look at highcharts lib directory, I'm wondering why the two files rgbcolor.js and rgbcolor.src.js exist in that directory? is there any internal usage from the files? if so, why you guys didn't include stackblur.js and stackblur.src.js files too?

I do not know the reason behind this. @TorsteinHonsi / @cvasseng ?

_Internal note:_ add info for general docs as suggested in the comment above

**Comment by TorsteinHonsi** [comment]
> Also, I took a look at highcharts lib directory, I'm wondering why the two files rgbcolor.js and rgbcolor.src.js exist in that directory? is there any internal usage from the files? if so, why you guys didn't include stackblur.js and stackblur.src.js files too?

I didn't know canvg depended on stackblur. When we set this up I recall the only dependency was rgbcolor, that's probably the reason behind it.
