### ISSUE TITLE
chart.plotBackgroundColor expects wrong type

### ISSUE THREAD

**Issue by Lolmewn** [highcharts/highcharts#10867]
#### Expected behaviour
I am trying to apply a gradient to the plot's background through this API option: https://api.highcharts.com/highcharts/chart.plotBackgroundColor 
As stated there, I am trying to use this (relevant part of the) config: 
```
chart: {
    margin: [0, 0, null, 0],
    backgroundColor: null,
    plotBackgroundColor: {
    	linearGradient: {x1: 0, x2: 1, y1: .5, y2: .5},
    	stops: [
    		[0, 'lime'],
    		[0.4, 'yellow'],
    		[1, 'red']
    	]
    },
    plotBorderColor: '#606063'
  },
```
I am using Highcharts v7.1.1, Angular v8.

I checked out the typings, it would appear that `plotBackgroundColor` is of type `ColorString`, which in turn is simply defined as being a `string`. Instead, I believe this should be either a `ColorString` or a `GradientColorObject` or even a `PatternObject`, just like a bunch of other (background)color fields.

#### Actual behaviour
A type check error: 
![image](https://user-images.githubusercontent.com/663563/58809272-e4a88880-861b-11e9-95e3-d46a170126a5.png)

#### Live demo with steps to reproduce
N/A since it won't compile.

#### Product version

I am using Highcharts v7.1.1, Angular v8, typescript v3.4.5.

#### Affected browser(s)
N/A since it won't compile.

**Comment by sebastianbochan** [comment]
Hi @Lolmewn,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by bre1470** [comment]
Thanks for the report. This type fix will be part of the next update.
