### ISSUE TITLE
Updating marker symbol doesn't update on chart but updates legend

### ISSUE THREAD

**Issue by willmitchell98** [highcharts/highcharts#10870]
#### Expected behaviour
Calling `series.update(...)` to change the marker symbol should update the chart with the new marker symbol.

#### Actual behaviour
The symbol does not update. It does, however, update on the legend.

#### Live demo with steps to reproduce
Below is a link to the jsfiddle, click the 'Change Marker' button to replicate.

https://jsfiddle.net/s84d671v/

#### Product version
Latest HighCharts 7

#### Affected browser(s)
Chrome 74, Firefox 60

**Comment by pawelfus** [comment]
Thanks for reporting the issue @willmitchell98 

It looks like a regression, v7.0 used to work: https://jsfiddle.net/BlackLabel/8nquh21b/
