### ISSUE TITLE
Updating chart data from undefined does not render tooltip

### ISSUE THREAD

**Issue by jonfreedman** [highcharts/highcharts#10874]
#### Expected behaviour
It's useful to be able to prime a chart with undefined y values in order to render the x-axis prior to some updates.

#### Actual behaviour
In this situation when a series y values are updated from undefined the tooltip rendered does not show that series.

#### Live demo with steps to reproduce
http://jsfiddle.net/du5mvgt1/1/
vs
http://jsfiddle.net/du5mvgt1/2/

Click the Set new data button and hover over the chart - version 1 will show a tooltip just showing "foo1" or "foo2" while version 2 will show the values of the foo and bar series at each point.

#### Product version
Higcharts 7.1.2

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @jonfreedman,
Thank you for reporting about the problem. 

Its a regression since v7.1.0.

**Comment by jonfreedman** [comment]
Thanks, unfortunately we need some of the fixes that were in 7.1.0 so we can't downgrade - any idea when this will be fixed?
