### ISSUE TITLE
Grid axis' cells are too wide

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#10888]
#### Expected behaviour
The grid should adjust to the size of the labels.

#### Actual behaviour
It doesn't - there's a lot of unused space:
![image](https://user-images.githubusercontent.com/13188589/58944813-d628b100-8782-11e9-9994-90b7031e23fa.png)

#### Live demo
https://jsfiddle.net/BlackLabel/ny1qd94o/

#### Product version
Gantt 7.1.2

**Comment by sebastianbochan** [comment]
Hi @kamilkulig,
Im closing this bug as duplicate of https://github.com/highcharts/highcharts/issues/10281
