### ISSUE TITLE
Redrawing chart asynchronously causes a flash of axis labels and grid lines

### ISSUE THREAD

**Issue by whawker** [highcharts/highcharts#10883]
#### Expected behaviour
Axis labels and grid lines do not temporarily disable, when redraw is asynchronous (the same as a synchronous redraw)

Apart from the redraw being async, this is following recommended Highcharts practice of passing `redraw = false` to individual updates, then calling `chart.redraw()` afterwards.

#### Actual behaviour
Axis labels and gridlines disappear before they are redrawn, causing a flash effect

#### Live demo with steps to reproduce
https://jsfiddle.net/o15ygv9x/1/

Press the buttons underneath the chart, 
* The left button, with timeout will cause a flash (may require repeat presses)
* The right button, does not have the same issue

#### Product version
Highcharts 7.1.2 (have also tested 7.0.0, and 6.0.0, where issue is also present)

#### Affected browser(s)
Chrome, Firefox - probably others

**Comment by pawelfus** [comment]
Hi @whawker 

This is kind of expected behaviour. When you call `axis.update()` old axis is replaced with new one. If you don't redraw chart, then new axis is not rendered thus you can see flashing title/labels. If you remove `chart.redraw()` you will see it clearly: https://jsfiddle.net/BlackLabel/eh29xtor/ (hit "with timeout" button). If you delay chart's redrawing, then axis will not be present for a short while. We recommend redrawing chart **right after** applying changes.

Could you elaborate a bit your use case? It's strange to delay `chart.redraw()`.

**Comment by whawker** [comment]
Ah interesting, my use case is in my React library that wraps Highcharts.

A Highcharts chart in my library would look something like this
```jsx
<HighchartsChart plotOptions={plotOptions}>
  <Title>Solar Employment Growth by Sector, 2010-2016</Title>
  <Subtitle>Source: thesolarfoundation.com</Subtitle>
  <Legend layout="vertical" align="right" verticalAlign="middle" />
  <XAxis>
    <XAxis.Title>Time</XAxis.Title>
  </XAxis>
  <YAxis>
    <YAxis.Title>Number of employees</YAxis.Title>
    <LineSeries name="Installation" data={[43934, 52503, 57177, 69658, 97031, 119931, 137133, 154175]} />
  </YAxis>
</HighchartsChart>
```

Basically all the components inside `<HighchartsChart>` watch for their props to change - if a change occurs, they call something context appropriate like `this.axis.setTitle('New Title', false)`

My use case is, that to prevent an excessive amount of redraws, I call [a debounced redraw function](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/BaseChart/BaseChart.js#L105-L109) that tries to limit the number of redraws

**Comment by whawker** [comment]
With hindsight, I think I might take a look at using a debounce based on `requestAnimationFrame` rather than the lodash one based on `setTimeout`

**Comment by pawelfus** [comment]
Let us know the results, thanks!
