### ISSUE TITLE
Series labels can't be styled in styled mode

### ISSUE THREAD

**Issue by stuffisthings** [highcharts/highcharts#10896]
#### Expected behaviour
- Series labels should receive a class based on the colorIndex of their associated series, so that they can be styled properly in styled mode (```highcharts-color-0``` for example)

- Series labels should be able to be assigned a className.

- Style attribute on series.label should have no effect in styled mode.

#### Actual behaviour
- Series labels don't receive any class based on the series's colorIndex. By default, all series labels are assigned ```color:undefined;```, e.g.:

```
<g class="highcharts-label highcharts-series-label highcharts-series-label-1" style="color:undefined;" opacity="1" data-z-index="3" transform="translate(880,308)"><path class="highcharts-label-box" d="M 0 0"></path><text x="0" data-z-index="1" style="font-weight:bold;" y="12">Label</text></g>
```
- setting the color attribute on label.style allows manually defining a color (the only workaround for this at the moment).
- series.label has no className option.

#### Live demo with steps to reproduce
[Fiddle (showing workaround)](https://jsfiddle.net/8mzy0vt4/)

#### Product version
Latest stable

#### Affected browser(s)
Chrome, Edge, Firefox

**Comment by sebastianbochan** [comment]
Hi @stuffisthings,
Thank you for reporting about the problem. 

**Internal note**
The problem is in the labelBySeries object.
```
series.labelBySeries = label = chart.renderer
                            .label(series.name, 0, -9999, 'connector')
                            .addClass(
                                'highcharts-series-label ' +
                                'highcharts-series-label-' + series.index + ' ' +
                                (series.options.className || '')
                            )
                            .css(extend({
                                color: onArea ?
                                    chart.renderer.getContrast(series.color) :
                                    series.color
                            }, series.options.label.style));
```

**Comment by TorsteinHonsi** [comment]
@sebastianbochan A simple condition should do here. If `chart.styledMode`, add a class name based on `series.colorIndex`, otherwise run `label.css` with the style options.

**Comment by sebastianbochan** [comment]
@TorsteinHonsi I agree, so will commit this modification soon.
