### ISSUE TITLE
I am not able to show connectors for 3d funnel

### ISSUE THREAD

**Issue by shashankj99** [highcharts/highcharts#10890]
https://i.stack.imgur.com/sIys4.png

Above is the image of the error...

**Comment by shashankj99** [comment]
`function sales_funnel(key_val, response) {

    Highcharts.setOptions({
        lang: {
            thousandsSep: ','
        }
    });

    Highcharts.chart('funnel_container', {
        chart: {
            type: 'funnel3d',
            options3d: {
                enabled: true,
                alpha: 10,
                depth: 50,
                viewDistance: 50
            }
        },
        title: {
            text: 'Sales Funnel'
        },
        plotOptions: {
            funnel3d: {
                label: {
                    enabled: true,
                    connectorAllowed: true,
                    connectorNeighbourDistance: 30
                },
            },
            series: {
                dataLabels: {
                    enabled: true,
                    format: '{point.name} ({point.y:,.0f})',
                    color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black',
                },
                neckWidth: '30%',
                neckHeight: '25%',
                width: '80%',
                height: '80%'
            }
        },
        series: [{
            name: response[1],
            data: key_val
        }]
    });
}`

**Comment by KacperMadej** [comment]
Hi @shashankj99 

Thank you for submitting the enhancement suggestion.

Connectors are not available for funnel 3d.
