### ISSUE TITLE
Highchart Cloud embed iframe won't update

### ISSUE THREAD

**Issue by S-mardii** [highcharts/highcharts#10903]
#### Expected behaviour
After updating and publishing a chart in Highchart Cloud, the embed link should display the updated version of the chart.

#### Actual behaviour
However, the embed link still displays the old version of the graph.

#### Live demo with steps to reproduce
- Open an existing chart
- Update the chart
- Publish the chart and select "embed" options
- Copy and paste the embed link in WordPress editor

#### Product version
HighCharts Cloud

#### Affected browser(s)
- Chrome
- Firefox

**Comment by kamilkulig** [comment]
Hello @S-mardii and thank you for reporting the problem. Did you save the chart before publishing it?

**Comment by S-mardii** [comment]
I must have missed that. It is wonderful that I just need to click "Save" and the chart in my WordPress was updated automatically.

**Comment by S-mardii** [comment]
By the way, I have been trying to look for the official document on how to work with "Customize > Advanced" of HighCharts. Would you mind sharing me the link to that?

**Comment by kamilkulig** [comment]
Sure, here it is (the description is rather brief): https://cloud.highcharts.com/docs/#/customization?id=_2-advanced-customization
The Advanced Customization section is a simplistic GUI that allows you to modify most of Highcharts constructor options. They're all listed here: https://api.highcharts.com/highcharts/
