### ISSUE TITLE
Area chart has unwanted space above the x-axis

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#10909]
#### Expected behaviour
The area is plotted from x-axis 0 line without an empty space above it.

#### Actual behaviour
The area has a space above the x-axis.

![issue](https://user-images.githubusercontent.com/34909457/59087894-46ac0b00-8906-11e9-9e59-f71ad512bbb2.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/L8eo4760/

#### Product version
Highcharts

**Comment by pawelfus** [comment]
*Internal note:*
Can bo connected to crisping lines for gridlines and not doing that for area's graph, or it's just a simple mistake (I wish that). When comparing, we get:
- gridline's y: 285.5
- path's threshold: 237.75 + 47 (plotTop) -> 284.75
