### ISSUE TITLE
Regression: series.update({data: ...}) generates incorrect points/data for bubble/heatmap/scatter

### ISSUE THREAD

**Issue by pomack** [highcharts/highcharts#10901]
#### Expected behaviour

Calling `series.update({..., data: ...})` when all options are the same as the original series should cause a redraw with the same chart.  Problem occurs in heatmap/bubble/scatter where more than 1 x/y value is valid in a series.

#### Actual behaviour

The first set of matching x coordinate points are kept, the rest removed, new points are added but merged incorrectly causing the graph to change markedly.

#### Live demo with steps to reproduce
Clicking update series (which only sets values to the same data, deeply copied), causes the list of points to merge incorrectly in 7.1.2
https://jsfiddle.net/pomack/rgkcx6f8/15/

Works in 7.0.3
https://jsfiddle.net/pomack/rgkcx6f8/17/

#### Product version
Fails in Highcharts 7.1.x

#### Affected browser(s)
All (tested in Chrome/Safari)

#### Explanation of Actual Behaviour

My example has 20 points, 4 x values, and 5 y values in a bubble map.

https://github.com/highcharts/highcharts/blob/v7.1.2/js/parts/Dynamics.js#L1188
`series.update({..., data: ...})` calls `series.setData(...)`. By the end of this call:
   * The following are a subset of the original data (4 values in my example, corresponding to initial x coordinate matches):
      * `series.data`
      * `series.points`
   * The following have the full 20 points, but re-arranged where the original 4 are shifted to the front:
      * `series.processedXData`
      * `series.processedYData`
      * `series.xData`
      * `series.yData`
      * `series.zData`
   * `options.data` has the full 20 points in the order the user passed it in, and inconsistent with  any of the above.

https://github.com/highcharts/highcharts/blob/v7.1.2/js/parts/Dynamics.js#L1204
With `keepPoints: true`, a merge then happens which is basically a no-op as the `options.data` takes precedence over anything else.

The inconsistency between `processedXData`/`processedYData` and `series.data` causes `series.generatePoints()` to  generate inconsistently.

**Comment by sebastianbochan** [comment]
Hi @pomack,
Thank you for reporting the issue. 

**Internal note**
Bisect leads me to https://github.com/highcharts/highcharts/commit/1fe7b09

**Comment by TorsteinHonsi** [comment]
#### Simplified demos
Bubble: https://jsfiddle.net/highcharts/3sdqb6z4/
Scatter: https://jsfiddle.net/highcharts/3sdqb6z4/1/

**Comment by pawelfus** [comment]
Fixed on master branch: https://jsfiddle.net/BlackLabel/qnkyf8ur/

Most probably the same issue as #11244.
