### ISSUE TITLE
Uneven spacing between x-axis labels

### ISSUE THREAD

**Issue by nixonnix05** [highcharts/highcharts#10936]
![Screen Shot 2019-06-10 at 12 53 20 PM](https://user-images.githubusercontent.com/19186935/59182288-00191380-8b87-11e9-8682-631872b9b8a8.png)
#### Expected behaviour
All the X-axis labels should be equally spaced

#### Actual behaviour
X-axis labels are not equally spaced

#### Live demo with steps to reproduce
Go to
https://www.highcharts.com/stock/demo/candlestick-and-volume

click on 1m filter

The X-axis labels are not equally spaced. Could not understand the pattern of occurrence. Found the same issue with other data sets on flags marking events chart as well for 1m filter. 

https://www.highcharts.com/stock/demo/flags-general 

#### Product version
Highstock version 7

#### Affected browser(s)
I have tested on Chrome, FF, IE, Edge
![uneven-spacing-flags-mark](https://user-images.githubusercontent.com/19186935/59182183-b3cdd380-8b86-11e9-8ebb-a47a830938fc.PNG)
![uneven-spacing-candlestics](https://user-images.githubusercontent.com/19186935/59182184-b3cdd380-8b86-11e9-9464-3a593319ee11.PNG)

**Comment by pawelfus** [comment]
Hi @nixonnix05 

This is expected behaviour, caused by [`xAxis.ordinal`](https://api.highcharts.com/highstock/xAxis.ordinal), see disabled option: https://jsfiddle.net/789wgjvz/
