### ISSUE TITLE
xAxis.minPadding doesn't work in some cases when grouping is enabled

### ISSUE THREAD

**Issue by fameriks** [highcharts/highcharts#10932]
#### Expected behaviour
Setting xAxis.minPadding when data grouping is enabled should add left padding for the line, so it will not start from the chart left border, but will have space between.

#### Actual behaviour
There is no min padding in some cases when data grouping is applied.

Related to this [closed issue](https://github.com/highcharts/highcharts/issues/8335) and this [pull request](https://github.com/highcharts/highcharts/pull/8937)

#### Live demo with steps to reproduce
https://jsfiddle.net/5evrtsdw/

#### Product version
Highstock 6.1.0 - 7.1.2
Worked fine in 6.0.7

#### Affected browser(s)
All

#8335 #8937

**Comment by pawelfus** [comment]
Thanks for reporting @fameriks 

*Internal note:*
Bisected to commit f1f4adcf5b
