### ISSUE TITLE
column chart issue in angular

### ISSUE THREAD

**Issue by aiswaryaam** [highcharts/highcharts#10933]
#### Expected behaviour
no space corresponding to bar for zero values.
#### Actual behaviour
Getting space for all the zero values in the series.I tried some code to remove white space for zero values and its not working

#### Live demo with steps to reproduce
http://jsfiddle.net/zmktekak/14/
tried out in this way.And its not working for me.

#### Product version
"highcharts": "^7.1.1",
    "highcharts-angular": "^2.4.0",

**Comment by pawelfus** [comment]
Hi @aiswaryaam 

You posted on our bug tracker. In case you have questions, please contact our support: https://www.highcharts.com/blog/support/
