### ISSUE TITLE
There are much less data labels in case of rotated chart

### ISSUE THREAD

**Issue by DK-Unit4** [highcharts/highcharts#10931]
#### Expected behaviour
The amount and logic of labels should be same independently if the chart is rotated. 
PS: I would assume that in case of rotated chart data labels are missing

#### Actual behaviour
Rotated chart has much less labels

#### Live demo with steps to reproduce
"normal" chart: https://jsfiddle.net/Kumlander/3qhco1xm/35/
rotated chart: https://jsfiddle.net/Kumlander/3qhco1xm/36/ - here data labels are present only in the middle

#### Product version
latest highcarts

#### Affected browser(s)
At least Chrome, but I do not think it is browser specific

**Comment by sebastianbochan** [comment]
Hi @DK-Unit4,
Thank you for contacting us. The reason of the issue is that in the rotated chart, datalabels overlap. As a result some of them are hidden, because in HC there is not anty-overlapping algorithm. 

You can enable the `dataLabels.allowOverlap` option.

Demo:
- https://jsfiddle.net/BlackLabel/ajbo70yh/

**Comment by DK-Unit4** [comment]
There is no such problem if it is not rotated although the labels overlaps exactly same way, so I would not agree with you answer

**Comment by pawelfus** [comment]
I think @DK-Unit4 is right, compare:

- with useHTML:
![Screen Shot 2019-06-10 at 11 27 04](https://user-images.githubusercontent.com/1453926/59186269-be7e6d80-8b72-11e9-815c-bf8e028d6503.png)
- without useHTML:
![Screen Shot 2019-06-10 at 11 26 56](https://user-images.githubusercontent.com/1453926/59186271-be7e6d80-8b72-11e9-8c5d-c63e5d107386.png)

Some of dataLabels don't overlap anything (e.g. top and bottom left ones).

**Comment by DK-Unit4** [comment]
Hi, Do you plan to reopen it?

**Comment by pawelfus** [comment]
Right, sorry, thanks for being cautious!
