### ISSUE TITLE
Tooltip > 'callout' goes behind the Y Axis title text

### ISSUE THREAD

**Issue by AntonyJos** [highcharts/highcharts#10939]
#### Expected behaviour
Hovering on the series datapoints, tooltip goes behind behind Y Axis titles

#### Actual behaviour
All the tooltip 'callout' should be displayed over the Y Axis title so that the values along with series name can be seen at all times.

#### Live demo with steps to reproduce

https://jsfiddle.net/jt8qagho/

Ensure (yAxisTiTle).useHTML and (seriesToolTip).useHTML to be true

![tooltip cropped](https://user-images.githubusercontent.com/42953694/59194247-0f5b8980-8ba6-11e9-9276-9aca234e3967.png)

#### Product version

Highstock - 7.1.2

#### Affected browser(s)
Only tested out in Google Chrome - ^74.0.x

**Comment by pawelfus** [comment]
Hi @AntonyJos 

Thanks for reporting the issue. This is known limitation when using HTML labels. See docs: https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting

Apart from `tooltip.outside` option, you can set `tooltip.useHTML`: https://jsfiddle.net/BlackLabel/nk5bsh71/2/ - now simply disable build-int SVG styles and apply your own in CSS:  https://jsfiddle.net/BlackLabel/nk5bsh71/6/
