### ISSUE TITLE
the heatmapseries has unwanted region

### ISSUE THREAD

**Issue by weifeng0715** [highcharts/highcharts#10934]
`public static PlotModel HeatMapSeries2()
        {
            var model = new PlotModel { Title = "HeatMapSeries" };
            double x0 = 10.9;
            double x1 = 12.9;
            double y0 = 1.6;
            double y1 = 2.6;
            Func<double, double, double> peaks = (x, y) => 3 * (1 - x) * (1 - x) * Math.Exp(-(x * x) - (y + 1) * (y + 1)) - 10 * (x / 5 - x * x * x - y * y * y * y * y) * Math.Exp(-x * x - y * y) - 1.0 / 3 * Math.Exp(-(x + 1) * (x + 1) - y * y);
            var xx = ArrayBuilder.CreateVector(x0, x1, 5);
            var yy = ArrayBuilder.CreateVector(y0, y1, 3);
            double[,] peaksData = new double[5,3];
            peaksData[0, 0]=	96133.5433;
		    peaksData[0, 1]=	75793.2872	;
		    peaksData[0, 2]=	57680.5878	;
		    peaksData[1, 0]=	73908.6788	;
		    peaksData[1, 1]=    56721.4425	;
		    peaksData[1, 2]=	35293.8694	;
		    peaksData[2, 0]	=58322.2705	;
		    peaksData[2, 1]	=34200.9124	;
		    peaksData[2, 2]	=14445.8054	;
		    peaksData[3, 0]	=28271.7449	;
		    peaksData[3, 1]	=13844.2264	;
		    peaksData[3, 2]	=92315.8221	;
		    peaksData[4, 0]	=13630.712	;
		    peaksData[4, 1]	=91164.0748	;
		    peaksData[4, 2]	=67240.967	;

            model.Axes.Add(new LinearColorAxis { Position = AxisPosition.Right, Palette = OxyPalettes.Jet(500), HighColor = OxyColors.WhiteSmoke, LowColor = OxyColors.Black });

            var hms = new HeatMapSeries
            {
                X0 = x0,
                X1 = x1,
                Y0 = y0,
                Y1 = y1,
                Data = peaksData
            };
            model.Series.Add(hms);

            var cs = new ContourSeries
            {
                Color = OxyColors.Black,
                LabelBackground = OxyColors.Wheat,
                ColumnCoordinates = xx,//yy,
                RowCoordinates = yy,//xx,
                Data = peaksData,
                //LabelStep = 2,
                //ContourLevelStep = 0.5
                //ContourColors = new[] { OxyColors.SeaGreen, OxyColors.RoyalBlue, OxyColors.IndianRed }

            };
            model.Series.Add(cs);
            return model;
        }`
<img width="842" alt="unwantted region" src="https://user-images.githubusercontent.com/25336824/59165950-56d40e00-8af1-11e9-9703-78c11e0da13f.PNG">

As shown in the uploaded image, the region in the red line is what I want. The program extend the region to other parts.

**Comment by pawelfus** [comment]
Hi @weifeng0715 

Wrong repo ;) This is Highcharts JS repo, not OxyPlot
