### ISSUE TITLE
top or bottom bar hidden sometimes when scrolling

### ISSUE THREAD

**Issue by HarishSha** [highcharts/highcharts#10940]
#### Expected behaviour
All bars must be visible as per the axis.

#### Actual behaviour
During scrolling, sometimes top or bottom one bar is hidden.

#### Live demo with steps to reproduce
https://jsfiddle.net/harishk3499/kbLacjx0/5/

To replicate it, scroll down a bit or scroll up.. u can see there, bottom or top bar will not be visible

#### Product version
Highstock latest version

#### Affected browser(s)
all browser

**Comment by pawelfus** [comment]
Hi @HarishSha 

Could you attach a screenshot? Do you mean this:

![Screen Shot 2019-06-11 at 10 11 34](https://user-images.githubusercontent.com/1453926/59254878-55116400-8c31-11e9-86bf-648c0a14314b.png)

(no top column, only category name)

If that's the case, you can control this by setting [`bar.cropThreshold`](https://api.highcharts.com/highcharts/series.bar.cropThreshold), see demo: https://jsfiddle.net/BlackLabel/x9jwqbyf/

**Comment by HarishSha** [comment]
![Screenshot 2019-06-11 at 2 01 04 PM](https://user-images.githubusercontent.com/19326727/59256413-869a2780-8c51-11e9-9464-bcd3488dd7a3.png)
![Screenshot 2019-06-11 at 2 01 20 PM](https://user-images.githubusercontent.com/19326727/59256414-869a2780-8c51-11e9-985d-e882ccf9939b.png)
![Screenshot 2019-06-11 at 2 01 43 PM](https://user-images.githubusercontent.com/19326727/59256416-8732be00-8c51-11e9-99a8-5def37b0d8f2.png)


In these screenshots, Top/bottom bar is not visible.

**Comment by pawelfus** [comment]
@HarishSha - did you try my solution? From the post above:
> If that's the case, you can control this by setting bar.cropThreshold, see demo: https://jsfiddle.net/BlackLabel/x9jwqbyf/

Increase this value, so points outside the extremes will be visible.

**Comment by HarishSha** [comment]
Yes, It worked.. Thank you so much. 👍

**Comment by HarishSha** [comment]
Can we stop animation while scrolling. As appearing of number and bar is different.

**Comment by pawelfus** [comment]
Hi @HarishSha 

You can disable live redraws: https://jsfiddle.net/BlackLabel/x9jwqbyf/4/

Docs: https://api.highcharts.com/highstock/xAxis.scrollbar.liveRedraw

If you have more questions, please contact our support: https://www.highcharts.com/blog/support/ - this is our bug tracker ;) Thanks!

**Comment by HarishSha** [comment]
Thanks @pawelfus
