### ISSUE TITLE
Stack chart is not plotted properly when some y values are null

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#10941]
#### Expected behaviour
Stack chart should ignore y with null value and plot rest of the data points properly.

#### Actual behaviour
Stack chart is not getting plotted properly.

#### Live demo with steps to reproduce
https://jsfiddle.net/foL5phs6/ (v6.1.1 - In this case, script error is also thrown on console.) 
https://jsfiddle.net/j9tn5b7z/ (v7.1.2)

**Comment by pawelfus** [comment]
Thanks for reporting @tejaspchordiya 

Simplified demo: https://jsfiddle.net/BlackLabel/cefo683m/

It seems that space is correctly reserved for both points in second series, but both rectangles are rendered in the same place.
