### ISSUE TITLE
Completed fill is not applied after hiding and showing a category

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#10942]
#### Expected behaviour

The completed fill should be unchanged.

#### Actual behaviour

The completed fill is not applied.

#### Live demo with steps to reproduce

1. Open jsfiddle: https://jsfiddle.net/BlackLabel/gkh3Lu7y/
2. Hide 'Test prototype' by clicking on 'Start prototype'
3. Show 'Test prototype' 

#### Product version
Gantt 7.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/bmz8tg53/

Snippet:
```js
Highcharts.addEvent(Highcharts.Axis, 'afterBreaks', function() {
  this.series.forEach(function(series) {
    series.data.forEach(function(point) {
      point.graphicOverlay = point.graphicOverlay && point.graphicOverlay.destroy()
    });
  });
});
```
