### ISSUE TITLE
inverted option for scrollbar and navigator

### ISSUE THREAD

**Issue by kasyan-sergey** [highcharts/highcharts#1095]
scrollbar and navigator don't work properly when i using inverted option for chart. it will be great if scrollbar and navigator have inverted option too or inverted automatically when chart option inverted is true.
http://jsfiddle.net/fj6d2/2163/

**Comment by pawelfus** [comment]
UserVoice related [ticket](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/2364547-add-navigation-bar-for-y-axis-in-highstock).

**Comment by pawelfus** [comment]
Added in 5.0.7.
