### ISSUE TITLE
Trend two finger zooming on the Windows tablet (W8.1 & W10) stopped working after Highcharts v4.2.7.

### ISSUE THREAD

**Issue by TrevorMcAlister** [highcharts/highcharts#10960]
#### Expected behaviour
Two finger zooming on the tablets causes Highcharts to perform a selection and re-draw the chart.

#### Actual behaviour
Attempting to zoom on the Windows tablet results in the native tablet zoom, which just makes the web page bigger. The same as doing Ctrl++ (zoom in). This issue was present using both IE11 and Chrome 75 on the windows tablet.

It’s also worth noting that we have IPads running iOS 9.3.5 & 8.2, which does not exhibit the same issue. (Two finger zooming works correctly)

#### Live demo with steps to reproduce
Replication instructions:
Using the ‘Chart selection demo’ that is linked in the API reference.
https://jsfiddle.net/trevormcalister/x6fqaop9/
We changed the source location of the ‘highcharts.js’ file to be a fixed version, rather than the latest.
Repeated testing of two finger Trend zooming on the Windows tablet, narrowed it down to last working in v4.2.7, it stopped working in v5.0.0, and still doesn’t work in the latest v7.1.2.

Unfortunately the changes between v4.2.7 and v5.0.0 are too great to be able to identify where things may be going wrong.
I tried putting in breakpoints into the ‘drag’ & ‘drop’ functions, but the execution wasn’t getting that far.
Without a Windows tablet to test on, it may be near impossible to replicate. Please let me know if there are any additional tests or breakpoint debugging that you would like me to try to aid any investigation.

Background info:
Our product upgraded from Highcharts v4.1.7 to v5.0.12 back in 2017, but this issue has only just been spotted. We were looking to upgrade our product from v5.0.12 to the latest stable release, but the product stakeholders rejected this proposal. The scope of the fix required for this issue may enable us to proceed with an upgrade.

#### Product version
Highcharts v4.2.7 and later versions

#### Affected browser(s)
System info:
Browsers IE11 (11.212.105860) and Chrome 75.0.3770.80 (32bit)
Windows 10 Pro 32bit (Version 1511) and Windows 8.1 Pro 32bit
Tablet Dell Latitude 10 ST2
CPU 1.8GH Atom Z2760
RAM 1.92GB
Pen and full windows touch support with 5 touch points
Screen 1366 x 768

**Comment by sebastianbochan** [comment]
Hi @TrevorMcAlister,
Thank you for reporting about the problem.

**Comment by pawelfus** [comment]
Thank you for reporting @TrevorMcAlister - you are right, in v5 we had quite a lot of changes.

Similar issue was reported some time ago, could you try work workaround posted here: #3993 ?

*Internal note:*
Issue confirmed by @jon-a-nygaard
FYI @TorsteinHonsi 
Related/duplicates: #6100 and #4014

**Comment by TrevorMcAlister** [comment]
It looks like you have already spotted that I had created #3993, I double checked that for our website the setting “X-UA-Compatible" is still set to "IE=Edge”.
But as described above, I was able to make the ‘Chart selection demo’ go from working to not just by changing the Highcharts version from v4.2.7 and v5.0.0.

**Comment by pawelfus** [comment]
Thanks for double checking this!

**Comment by jon-a-nygaard** [comment]
I will look into this issue today and see if there may be a workaround or fix for this. Will post an update as soon as I know some more.

**Comment by jon-a-nygaard** [comment]
I have registered a PR https://github.com/highcharts/highcharts/pull/11214 which solves this issue. It is currently in review, but I expect that it will be included in our next maintenance version unless a serious flaw is discovered.
