### ISSUE TITLE
scrollbar.zIndex / navigator.xAxis.gridZIndex not picked for navigator handles

### ISSUE THREAD

**Issue by AntonyJos** [highcharts/highcharts#10963]
#### Expected behaviour
highcharts-navigator-xaxis gridline and labels should not be overlapping navigator handles

#### Actual behaviour
Able to see the navigator gridlines through the navigator handles

#### Live demo with steps to reproduce

https://jsfiddle.net/gwvtj8s6/1/

Ensure 
          scrollbar.zIndex
          navigator.xAxis.gridZIndex
          navigator.xAxis.labels.zIndex 
are set.

![overlap](https://user-images.githubusercontent.com/42953694/59332297-84989d00-8d13-11e9-94f8-bcbf934ad9dd.PNG)

Highlighted the handle overlap in the above image

#### Product version

Highstock - 7.1.2

#### Affected browser(s)
Only tested out in Google Chrome - ^74.0.x

**Comment by pawelfus** [comment]
Hi @AntonyJos 

Navigator has hardcoded zIndex=8. By increasing `gridZIndex` you make gridlines to be rendered on top of the navigator. We can add an option `navigator.zIndex`, but increasing it will give the same effect as not setting `gridZIndex` at all. Could you explain what do you want to achieve?

In general, all navigator elements are within one SVG group (handles, masks etc.) so you can only control rendering zIndex of all navigator elements at once. For example you can render axis' gridlines under the navigator or above the navigator. You can't render gridlines above the masks and below the handles.

**Comment by AntonyJos** [comment]
Hello @pawelfus,

Hope you might have got that i am trying to update my `navigator.top`  on the scroll event.

Initial fiddle

https://jsfiddle.net/02nvbuax/

![inAndOut](https://user-images.githubusercontent.com/42953694/59348893-f4b81a80-8d35-11e9-86ad-47e477603361.PNG)

In such case, my navigator appears to be transparent in nature./ remove default `fill-opacity`

On trying to achieve this through the below css

```
rect.highcharts-navigator-mask-inside {
    fill: red;
}

rect.highcharts-navigator-mask-outside {
    fill: green;
}
```
_The data-labels in the navigator seems to be entirely missing_

![data-labels missing](https://user-images.githubusercontent.com/42953694/59349099-6d1edb80-8d36-11e9-8e17-41ca0d950a0c.PNG)

So inorder to see my datalabels, i was forced to give `fill-opacity` like below

![overlapChart](https://user-images.githubusercontent.com/42953694/59349222-bc650c00-8d36-11e9-8887-4a02d66226d1.PNG)

Later, i came to tweak this with the help of zindex and gridZindex like below

![noChartOverlap](https://user-images.githubusercontent.com/42953694/59349366-14037780-8d37-11e9-9b1c-be72d435b867.PNG)

This was a perfect solution to match my requirement, but later noticed that my navigator axis labels seems to be overlapping the navigator handles.

Initially i thought, adding `scrollbar.zIndex `would resolve this but it never did.

**Comment by pawelfus** [comment]
Ok, thanks for the explanation. As I said, navigator and it's xAxis+yAxis don't work that way. Those are separate components, which can not have mixed zIndexs within.

To improve navigator's readability, I suggest to simply add [`plotBands`](https://api.highcharts.com/highstock/yAxis.plotBands) which will imitate navigator's background. Here is a simple example: https://jsfiddle.net/BlackLabel/wjqn6kt4/ - note that masks/handles are still above the labels/grids as designed.

Navigator's config:
```
  navigator: {
    top: pageBottom - 75,
    xAxis: {
      gridZIndex: 5
    },
    yAxis: {
      min: 0,
      max: 1,
      plotBands: [{
        from: 0,
        to: 1,
        color: 'green',
        zIndex: 4
      }]
    }
  },
```

Regarding:
> Initially i thought, adding `scrollbar.zIndex` would resolve this but it never did.

That's expected, scrollbar is just another component. Like navigator.

**Comment by AntonyJos** [comment]
Closing this defect as behavior seems to be as expected from the above comments...
