### ISSUE TITLE
Annotations block mousedown event even when dragging is disabled 

### ISSUE THREAD

**Issue by f1ghtingfalcons** [highcharts/highcharts#10961]
#### Expected behaviour
When an annotation is not considered 'drag-able' it should not call `Event​.stop​Propagation()`. This can mess with click handlers implemented on the element by the user.

#### Actual behaviour
All annotations register a mousedown event handler and call stop​Propagation() even when they are not drag-able.

#### Live demo with steps to reproduce
https://jsfiddle.net/f1ghtingfalcons/jnhtpc6x/14/

In the demo clicking on the series or any where outside the annotation will show an alert. Clicking in the annotation area will result in nothing.

#### Product version
Highcharts JS v7.1.2 with Annotations Module

#### Affected browser(s)
any

**Comment by pawelfus** [comment]
Thanks for reporting this bug @f1ghtingfalcons
