### ISSUE TITLE
t is impossible to click on a point of a series which is behind another one

### ISSUE THREAD

**Issue by DK-Unit4** [highcharts/highcharts#10978]
#### Expected behaviour
PS: Not sure if it is a bug or a limitation
It is possible to click on a point of a series which is behind another one

#### Actual behaviour
It is impossible to click on a point of a series which is behind another one, although tooltip and highlight works fine

#### Live demo with steps to reproduce
https://jsfiddle.net/Kumlander/1jx56eow/2/

try to click on "Series 1 / Feb" - impossible also highlight works fine. If I try to change to order of those series then it will not be possible to click on the other series March.

#### Product version
latest

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @DK-Unit4 

This is how events are fired when one is rendered on top of another - browser does not fire events for elements that are under. You can workaround this issue by disabling events for path/graph, demo: https://jsfiddle.net/BlackLabel/2jr1vqh6/

CSS snippet:
```css
g.highcharts-series path {
  pointer-events: none;
}
```

Cons: click event for series graph won't be called: https://jsfiddle.net/BlackLabel/2jr1vqh6/3/ (still works for points).

**Comment by DK-Unit4** [comment]
Thank you for the workaround. Unfortunately those cons do not let us to use it. 
Do you have plans to recognize it as an issue and include the fix into future versions?

**Comment by pawelfus** [comment]
Hmm.. personally, I think this is wrong. Firing click event on Series A and click event on Point from Series B. It's just how HTML works, only the top element captures events, not the ones that are below.. The same happens with cursor: pointer - it's not applied in CSS, so click event is not even suggested to user. See simple HTML demo: https://jsfiddle.net/BlackLabel/j8m7ukpb/

I'm not saying it's impossible, take a look: https://jsfiddle.net/BlackLabel/2jr1vqh6/10/ - you can catch all click events on the container, and check if `chart.hoverPoint` is defined. If it's defined, then tooltip is visible. Distance from clicked coordinates to the point are stored in `chart.hoverPoint.dist` (direct distance) and `chart.hoverPoint.distX` (x-distance). This way you can determine if your callback should be fired or not.

@TorsteinHonsi - what do you think about this? I understand the need to fire `click` event.
