### ISSUE TITLE
Always show min and max value as y-axis label

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#10971]
I have a very hard time to get my y-axis to display 2 labels: the lowest value of the axis and the highest value of the axis.

When the min and max of the axis are explicitly set, I can use axis.tickPositions:
http://jsfiddle.net/kzoon/569fd3be/
But when the max is automatically calculated, I must rely on axis.tickAmount = 2:
http://jsfiddle.net/kzoon/569fd3be/11/
However, axis.tickAmount can ruin my axis scaling when I DO have a fixed max: 
http://jsfiddle.net/kzoon/569fd3be/14/ (the max becomes 60 instead of 50)

When my scale starts below zero, event axis.tickAmount doesn't guarantee that the two ticks are the actual  start and end of the scale: http://jsfiddle.net/kzoon/569fd3be/18/

It would be much more convenient if I could use max and min in axis.tickPositions, like so:

`tickPositions: [min, max]`

 During rendering min and max will be replaced by the actual min and max of the axis.

I demonstrate this with a solid gauge, but the same would be valid for the y-axis on a line or column chart

**Comment by pawelfus** [comment]
Hi @kzoon 

In your case I think [`yAxis.tickPositioner`](https://api.highcharts.com/highcharts/yAxis.tickPositioner) is the best solution:

- fixed min&max: http://jsfiddle.net/BlackLabel/f2ehx37t/
- fixed negative min & fixed max: http://jsfiddle.net/BlackLabel/d1zjy6ga/

It does exactly what you mean by `tickPositions: [min, max]`, but just in a form of function.

**Comment by kzoon** [comment]
I tried that, but it only works when both are fixed. In that case tickPostions works just as good.

I tried it with automatic scaling, but the positioner influenced the axis min and max: there are no ticks, so what would endOnTick do?
Maybe the core issue is that auto scaling doesn't work very well when you have only 1 data point, because there is no real data range?

**Comment by pawelfus** [comment]
I'm here a bit lost. You have two different cases (defined and undefined `max`), right?

When extremes are defined you use `tickPositions`, but when undefined you use `tickAmount`. And problem is when those are used together, then you get different result from what you expect?

> Maybe the core issue is that auto scaling doesn't work very well when you have only 1 data point, because there is no real data range?
> Is there a way to calculate the next 'nice value' from extremes.dataMax? In that case I could use that nice value in yAxis.tickPositioner.

That's correct. I had an attempt to find a solution that works nicely for one-point series, see #5956.

Personally, I would use conditionally `tickPositions` + `max` or `tickAmount` when `max` is not defined. Alternatively, we can always provide to the library calculated `max`: http://jsfiddle.net/BlackLabel/nea16pcm/20/ (in line 28 you can assign value to max and solution will adapt).

**Comment by kzoon** [comment]
I agree. My original request is covered by yAxis.tickPositioner.
The problem was that I always provide a max value based on the value in the data and then relied on endOnTick to get to the nearest nice number.
With the code you provided I can apply nice numbering myself.
