### ISSUE TITLE
Network graph - weight property for data 

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#10983]
In the documentation of data for the network graph, we can find a **weight** feature which has been added wrongly. This option doesn't exist in the network graph.  

#### Live demo with steps to reproduce
[Link to documentation](https://api.highcharts.com/highcharts/series.networkgraph.data.weight)
[Simple demo showing that this feature do nothing](https://jsfiddle.net/BlackLabel/8wnzj0xy/)

**Comment by pawelfus** [comment]
*Internal note:*
Seems to be inherited/copied from sankey series, that was a base for nodes logic.
