### ISSUE TITLE
7.1.1 introduced Point properties as any's for Typescript.

### ISSUE THREAD

**Issue by justinmwarner** [highcharts/highcharts#10982]
#### Expected behaviour
No [property: string]: any in type definition for Point.
![image](https://user-images.githubusercontent.com/2288818/59379454-7d6d9100-8d0b-11e9-80aa-c51e25380a76.png)

#### Actual behaviour
Anyone can act like any property is on the point. This has two problems.

1. It loses type safety.
2. In the case Highcharts adds a property that someone is acting like it exists (ie: they're forcing values in, because now even Typescript won't complain because it has all properties), it could be used incorrectly.

#### Live demo with steps to reproduce
N/A

#### Product version
Introduced in 7.1.1
https://github.com/highcharts/highcharts/commit/935b858a428555a6ff6289cab8d31f602f8fd556

#### Affected browser(s)
N/A

**Comment by sebastianbochan** [comment]
Hi @justinmwarner,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by bre1470** [comment]
I do not understand the problem. This is done for custom properties in the data objects, that get automatically applied to the point instances. Which type do you expect instead of any?

**Comment by justinmwarner** [comment]
@bre1470 , do you have more information on the custom properties? (Documentation or something?).

We may be consuming things wrong on our side.

**Comment by OmarMustafa** [comment]
Consider the case where someone tries to do the following:

`const point: Highcharts.Point = { ... ];
const color = point.colr; // mistype color`

Previously, if someone does that, it would complain and notifies the developer that colr doesn't exist.

With the change done in 7.1.2, we'll have absolutely no idea that the attribute is mistyped and the value will always be undefined until it's noticed.

I understand that sometimes we need to have custom properties, but adding `[property: string]: any` makes the object less strongly typed.

I propose adding to Point a new property called something like
`customProperties: {[property: string]: any}` to store the custom properties in a nested level to make it obvious to distinguish between the native props and the custom ones.

**Comment by justinmwarner** [comment]
Another option is already documented here- https://github.com/bre1470/highcharts-declarations-documentation#extending-highcharts-in-typescript

This is how we've been doing it up to this point.

**Comment by bre1470** [comment]
@OmarMustafa Thank you for your suggestion! I prefer a subproperty for this kind of data as well.
@justinwarner Yes, that is true. We will discuss the problem internally and will likely revert the change with the next update.

**Comment by OmarMustafa** [comment]
Thanks @bre1470.

FYI, you tagged the wrong Justin. The author is justin**m**warner
