### ISSUE TITLE
v7.1.2 doclets issues

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#10991]
- [x] `item.marker` should extend `plotOptions.series.marker` instead of `plotOptions.line.marker`
- [x] [`solidgauge.dataLabels`](https://api.highcharts.com/highcharts/series.solidgauge.dataLabels) and [`gauge.dataLabels`](https://api.highcharts.com/highcharts/series.solidgauge.dataLabels) - missing type
- [x]  [`x/y/zAxis.plotLines.events`](https://api.highcharts.com/highcharts/xAxis.plotLines.events) - missing type
- [x] ~~`Highcharts.PlotSeriesOptions` is defined in tree.json, but does not exist in tree-namespace.json (simply wrong name?)~~
- [ ] `SeriesSunburstDataLabelsOptionsObject.align` and `SeriesSunburstDataLabelsOptionsObject.allowOverlap` have `undefiend` type

**Comment by pawelfus** [comment]
@bre1470 - could you take a look?

**Comment by bre1470** [comment]
@pawelfus 
Regarding the 4th point: tree.json and tree-namespace.json are defining together the namespace. tree-namespace.json contains all class references. Originally it was not intended to be like this, but it evolved to this state. Naming is confusing, sorry.

**Comment by pawelfus** [comment]
Sorry about 4th point - I was meaning `used`, not `defined`. In short `PlotSeriesOptions` is missing

**Comment by bre1470** [comment]
PlotSeriesOptions is the interface name of the options path 'plotOptions.series'. See https://github.com/highcharts/highcharts/wiki/Tools:-tree.json#user-content-how-to-use-it

**Comment by bre1470** [comment]
> Now you have a complete tree, which you might like to filter, or use as the source for a wrapper. The following steps (preferably as a recursion) are necessary to generate all interfaces out of the tree:
>
> Create for each node with children a blank interface and name it accordingly to you platform. For TypeScript the following steps are like this:
>
> Join the full node path and capitalize each path element's first letter. For example plotOptions.series becomes PlotOptionsSeries.
>
> Remove every Options string in the name and attach it to the end. For example PlotOptionsSeries becomes PlotSeriesOptions.

**Comment by bre1470** [comment]
5th point is correct - these properties from `Highcharts.DataLabelsOptionsObject` are not supported by the interface and get disabled.

**Comment by pawelfus** [comment]
Shouldn't we simply exclude them then?

**Comment by bre1470** [comment]
We do this the JSDoc/TypeScript-way. This is an interface in the namespace. Our proprietary `@excluding` will not work.
