### ISSUE TITLE
 Highcharts timeline, markers visibile outside of xAxis

### ISSUE THREAD

**Issue by RonjaKnudtsen** [highcharts/highcharts#10993]
#### Expected behaviour
The markers in the timeline chart are clipped and kept within the x-axis area, even with zoom and panning.

#### Actual behaviour
The markers glitch outside the area and are shown over the labels. 

#### Live demo with steps to reproduce
Add a zoom level, 
Turn on panning
Enable labels
```
 chart: {
        type: 'timeline',
        panning: true,
    },
    xAxis: {
        type: 'datetime',
				min: Date.UTC(1988, 4, 0),
				max: Date.UTC(1998, 10, 20)
    },
 yAxis: {
        labels: {
          enabled: true
        }
    },
```
Interaction: Pan until you are close to a new point. The marker is visible over the yaxis number.

https://jsfiddle.net/Lgrf4ns2/1/

Turn off the labels and the markers looks good. 

#### Product version
"highcharts": "7.1.2",

#### Affected browser(s)
Tested in chrome

**Comment by pawelfus** [comment]
Thanks for reporting! This is expected behaviour (for all series, not only timeline) - we used to clip markers, but users reported this as a bug, so now markers received some space (~99px) on both sides to prevent this. 

*Internal note:*
It's not the first time that opposite solution is expected. We should consider an option `clipMarkers` or something similar to let users config this.

**Comment by RonjaKnudtsen** [comment]
Thank you for referencing the other posts.

I am not sure why this would be expected behaviour however.

Let me give you another example
This is from our charts, which we want to put in production.
![highcharts](https://user-images.githubusercontent.com/11744728/59508311-c8270e80-8ead-11e9-8e61-299b88bbccf0.JPG)

As you can see from a user perspective, the behaviour of the top chart looks very different from the area chart at the bottom. Because the area chart perfectly stops at the min axis point. 

This chart also has some extra margin so that they would be aligned. 
And our users percieve this as an ui bug in our application. 

I am not sure what marker space you are refering to.

**Comment by pawelfus** [comment]
Hi @RonjaKnudtsen 

Thanks for the details. You are right, just now I realized that visible point is outside the given extremes. Better example: https://jsfiddle.net/BlackLabel/17eb3dwm/

*Internal note:*
@Denyllon - could you check `point.isInside` logic? Probably something is broken there.
