### ISSUE TITLE
Declaring xAxis.lineWidth greater than 1 prevents line series data points on yAxis min from rendering

### ISSUE THREAD

**Issue by lukeokane** [highcharts/highcharts#11005]
#### Expected behaviour
Highstock 7.1.2 behaves as it did in 5.0.14, where declaring [xAxis.lineWidth](https://api.highcharts.com/highcharts/xAxis.lineWidth) with a number greater than 1 allows the data points on the [yAxis.min](https://api.highcharts.com/highcharts/yAxis.min) to render.
#### Actual behaviour
Data points that are on the [yAxis.min](https://api.highcharts.com/highcharts/yAxis.min) do not render when [xAxis.lineWidth](https://api.highcharts.com/highcharts/xAxis.lineWidth) is greater than 1.

#### Live demo with steps to reproduce
[Highstock 5.0.14, xAxis.lineWidth greater than 1 (issue does not occur)](https://jsfiddle.net/8gwxefn5/)

[Highstock 7.1.2, xAxis.lineWidth greater than 1 (issue occurs)](https://jsfiddle.net/8gwxefn5/1/)

[Highstock 7.1.2, xAxis.lineWidth set to 1 (issue does not occur)](https://jsfiddle.net/8gwxefn5/2/)

#### Product version
Highstock 7.1.2

#### Affected browser(s)
Google Chrome: v75.0.3770.90
Firefox Quantum: v67.0.2
Microsoft Edge: v42.17134.1.0
Internet Explorer: v11.829.17134.0

**Comment by sebastianbochan** [comment]
Hi @lukeokane,
Thank you for reporting about the problem.

**Internal note**
Bisect leads me to https://github.com/highcharts/highcharts/commit/903e5f8

**Comment by TorsteinHonsi** [comment]
Simplified demo: https://jsfiddle.net/0q6m1ad9/
