### ISSUE TITLE
Enabling markers only on selected points

### ISSUE THREAD

**Issue by tzaitoun** [highcharts/highcharts#11006]
I have a chart with a lot of points and I am trying to enable point selection, however the only way it works, is if I enable markers and set radius to 0.1 to make them "hidden" (a solution suggested here in previous posts). This solution doesn't work for large data sets by slowing down the zooming in and reset zoom button significantly. 

I am selecting these points programatically using point.select() through the chart click event and the point click event. I have access to the point objects of all selected points. How can I achieve this select state in the UI without drawing all the markers? Any help is appreciated. 

I tried disabling markers and using point.update() to add a marker option but I am seeing strange behavior.

**Comment by sebastianbochan** [comment]
Hi @tzaitoun,
Thank you for contacting us. The github is our bugtracker so for general [support](http://www.highcharts.com/support) questions, please use stackoverflow / forum or email.
