### ISSUE TITLE
Removing annotations doesn't deselect removed annotation

### ISSUE THREAD

**Issue by Elektropepi** [highcharts/highcharts#11015]
#### Expected behaviour
When having plotOptions.series.showInNavigator = true, then clicking on an annotation, then removing it, then clicking on a new annotation should not produce any error in the console.

#### Actual behaviour
When having plotOptions.series.showInNavigator = true, then clicking on an annotation, then removing it, then clicking on a new annotation **sometimes** produces TypeError: this.controlPoints is undefined.

This is due to `this.activeAnnotation` in the annotations module function `deselectAnnotation` still being set, although the annotation was removed from the chart. This results into `this.activeAnnotation` being an empty object and therefore `this.controlPoints` in `setControlPointsVisibility` is undefined.

#### Live demo with steps to reproduce
https://jsfiddle.net/trj5fndp/

#### Product version
Highstock v7.1.1

#### Affected browser(s)
Firefox 67.0

**Comment by pawelfus** [comment]
Thanks for reporting @Elektropepi 

**Workaround:**
```js
addEvent(H.Annotation, 'remove', function () {
    if (this.chart.navigationBindings) {
        this.chart.navigationBindings.deselectAnnotation();
    }
});
```
