### ISSUE TITLE
TypeScript Migration

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#11020]

**Comment by cvasseng** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Migrate Series to TypeScript #10859](https://github.com/highcharts/highcharts/issues/10859) | N/A | bre1470 | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by bre1470** [comment]
Code migration is done and enough for this epic.
