### ISSUE TITLE
overflow: hidden on highcharts's container

### ISSUE THREAD

**Issue by smokir** [highcharts/highcharts#11089]
Recently discovered this thing which in my case hides some tooltip parts. Is it expected behavior?

#### Expected behaviour

Dont change container styles

#### Actual behaviour

Highcharts 7 sets `overflow: hidden` to its container

#### Live demo with steps to reproduce
https://jsfiddle.net/9ps872h3/

#### Product version

Highcharts 7.1.2 vs Highcharts 6.2.0

**Comment by pawelfus** [comment]
Hi @smokir 

This is expected behaviour. If your tooltip is too big and cut off, then please set [`tooltip.outside = true`](https://api.highcharts.com/highstock/tooltip.outside).

**Comment by danmaftei** [comment]
Setting `tooltip.outside = true` does not prevent `overflow: hidden` from being added to the container. Are there other things we can do to suppress this inline style from being set on the container?

**Comment by pawelfus** [comment]
Hi @danmaftei - that's correct, it does not prevent `overflow: hidden` from being set. It does prevent tooltip from being cut off. There are multiple reasons to keep this CSS (flex-boxes, context-menu etc). If you really need to change this, then in `chart.events.load` event, modify inline CSS manually.

**Comment by vinuthakaranth** [comment]
Is there any solution for this?

**Comment by karolkolodziej** [comment]
Does setting the tooltip `outside: true` not work for you? 
Could you please give me an example of where it fails?

**Comment by TheRev433** [comment]
Setting `tooltip.outside : true` did nothing for me. The labels on x axis still gets cut off on first render. After resizing window or manually calling `chart.reflow()` after rendering the chart kind of fix it. Any suggestions? 

I can manually overwrite that `overflow: hidden` css with `overflow: visible !important` but obviously it adds the scrollbar.

**Comment by karolkolodziej** [comment]
Can you please provide a demo with your higcharts version where this is visible?
