### ISSUE TITLE
Top BorderRadius(Rounded Corner of Bars) in Bar chart is not supporting 

### ISSUE THREAD

**Issue by Prakshi** [highcharts/highcharts#11092]
I want all the bars of bar chart to be rounded from **top end** and not from bottom.

Using **borderRadius** property in bar chart, the bars are getting rounded from both ends i.e. top and  bottom

I am testing it in chrome.
Request immediate support.

Thanks

**Comment by pawelfus** [comment]
Hi @Prakshi 

You posted on our bug tracker. In case of questions, please contact our support: https://www.highcharts.com/blog/support/

PS: Yo answer your case, use [rounded corners](https://github.com/highcharts/rounded-corners) plugin.

**Comment by alvarotrigo** [comment]
@pawelfus the plugin doesn't work as expected. Big issues: https://github.com/highcharts/rounded-corners/issues/30

And it seems to be unmaintained... Issues not getting answered at all.
