### ISSUE TITLE
After using method Highcharts.chart.update property switchRowsAndColumns not saved

### ISSUE THREAD

**Issue by Serzh470** [highcharts/highcharts#11095]
#### Expected behaviour
save property switchRowsAndColumns in Highchart.chart.options and in Highchart.chart.options.data.

#### Actual behaviour
Property not saved. Other property, like csv and delimiters saved correctly after update.
If save chart.options object and try to render a new chart with this object, chart will be not correct, if we switch rows and columns in previous version.

#### Product version
highcharts 7.03

**Comment by pawelfus** [comment]
Hi @Serzh470 

Thanks for reporting the issue, but I'm unable to recreate the issue, see demo: https://jsfiddle.net/BlackLabel/jzrxybwu/1/ (in console observe current value of `switchRowsAndColumns`). Please, recreate issue in jsFiddle, thanks!

**Comment by TorsteinHonsi** [comment]
I think I see the problem @pawelfus , the OP mentions using `chart.update`. Here I am not able to set `switchRowsAndColumns` to false after first setting it to true: https://jsfiddle.net/gnmbd26s/1/

**Comment by pawelfus** [comment]
Right, I'm blind, demo was recreating the chart. Thanks!

**Comment by Serzh470** [comment]
Yes, sorry for delay, I restore in jsfiddle this bug:
[https://jsfiddle.net/smatyushkov/nf0uhm27/16/](url)
I'm saving chart.options on server, because user can change properties of chart on front-end. So, if we update chart by setting data.switchRowAndColumns to true/false, there are no changes in global objects options (Highcharts.charts[0].options.data.switchRowAndColumns). It's still undefined. When I use chart.options for rendering this chart next time, I get chart with switchRowAndColumns in underfined(false) state.
