### ISSUE TITLE
Responsive chart crashes on setSize

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#11101]
Demo:
http://jsfiddle.net/1a0kb8c4/ - also seen on https://www.highcharts.com/demo/responsive

Click "small" and then click "large".

Tested in Chrome. Works as expected in Highcharts v7.0.

**Comment by TorsteinHonsi** [comment]
Bisected to 7aefc37131eea58af8aa5c5beadbe9f295699f17
