### ISSUE TITLE
Trackable point outside yAxis extremes (polar)

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#11148]
#### Expected behaviour
No points can be tracked if their value is higher than yAxis.max

#### Actual behaviour
Although the points' y is bigger than yAxis.max, they can be tracked as long as they are within the plot area.

![polar](https://user-images.githubusercontent.com/23310742/60019671-bbb16b80-968e-11e9-9aff-02f2fe2200fd.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/goL7b1r6

#### Product version
Highcharts 7.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/xdh1bfm4/

Snippet:
```js
Highcharts.wrap(Highcharts.Chart.prototype, 'isInsidePlot', function(p, x, y, inv) {
  var isInside,
    center = this.yAxis[0].center;

  if (this.polar) {
    isInside = Math.sqrt(
      (x - center[0]) * (x - center[0]) +
      (y - center[1]) * (y - center[1])
    ) < center[2] / 2;

  } else {
    isInside = p.apply(this, Array.prototype.slice.call(arguments, 1));
  }

  return isInside;
});
```
