### ISSUE TITLE
How to add marker if you are using the 2dimensional array to plot large data

### ISSUE THREAD

**Issue by nakul91** [highcharts/highcharts#11149]
<img width="1013" alt="Screen Shot 2019-06-24 at 6 27 37 PM" src="https://user-images.githubusercontent.com/7921710/60020579-ec54cd80-96ad-11e9-90a1-e383cbbec092.png">
#### Considering the map above the pink color plotted graph was ploted using below data

obj = {x: new Date(year.slice(4,6) + '/01/' + year.slice(0,4)).getTime(), y: newplots[year], marker: {symbol: url, width: 30, height: 30, enabled: true}};

and grey map with lots of data was plotted using a 2dimensional array so my question is how to plot marker when you use 2 dimensional arrray

**Comment by pawelfus** [comment]
Hi @nakul91 

Thanks for contacting us. In general, when you have a question, please contact use directly or post on our forum: https://www.highcharts.com/forum/

PS: You can use [`series.keys`](https://api.highcharts.com/highcharts/series.line.keys) or simply use objects (like in your first series) with disabled [`series.turboThreshold`](https://api.highcharts.com/highcharts/series.line.turboThreshold).
