### ISSUE TITLE
Packed bubble - documentation

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#11155]
In the documentation of the packed bubble are some mistakes.
[API](https://api.highcharts.com/highcharts/series.packedbubble.maxSize) - here you can find information which is saying that: 

> Bubbles will automatically size between the minSize and maxSize to reflect the z value of each bubble.

While in the data [documentation](https://api.highcharts.com/highcharts/series.packedbubble.data) of the packed bubble we can find that z value doesn't exist and, what is more, we can find **y** value, but packed bubble series requires "value" property rather than **y**.

#### Live demo with steps to reproduce

[Proof that y isn't working](https://jsfiddle.net/BlackLabel/zndLuvpj/)
[Proof that z value doesn't do anything](https://jsfiddle.net/BlackLabel/9mhrwetp/)

**Comment by KacperMadej** [comment]
fyi @Izothep
