### ISSUE TITLE
Draggable not working with group points in line chart when boost module enabled

### ISSUE THREAD

**Issue by ngmikeng** [highcharts/highcharts#11156]
#### Expected behaviour
I have grouped points by `groupId` for draggable a line data, and it works fine without boost module, as you can see the link bellow, you can drag and drop a line data.
https://jsfiddle.net/s8joy32a

#### Actual behaviour
But when using with boost module, unfortunately you can't drag and drop the line data anymore, I checked the console and it logged this error.

```
Uncaught TypeError: Cannot read property 'groupId' of undefined
    at draggable-points.src.js:1539
    at Array.filter (<anonymous>)
    at P (draggable-points.src.js:1538)
    at E (draggable-points.src.js:1611)
    at HTMLDivElement.<anonymous> (draggable-points.src.js:2533)
```

#### Live demo with steps to reproduce
https://jsfiddle.net/sw8pbatj

#### Product version
Latest

#### Affected browser(s)
Chrome latest

**Comment by pawelfus** [comment]
Thanks for reporting the issue @ngmikeng !
