### ISSUE TITLE
undefined value for lang.loading renders as "undefined"

### ISSUE THREAD

**Issue by fantapop** [highcharts/highcharts#11169]
#### Expected behaviour

loading text should not be rendered

#### Actual behaviour

text rendered is "undefined"

#### Live demo with steps to reproduce
https://jsfiddle.net/94gfz061/

#### Product version
 Highcharts JS v7.1.2 (2019-06-03)

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @fantapop,
Thank you for reporting. The problem is caused by using `element.innerHTML` to add a text. By default it does not recogonize `undefined` properly in native Javascript.

_Demo:_
- https://jsfiddle.net/kq3axdb4/

**Workaround**
Use `null` value instead of `undefined`.

**Internal note**
We should use `H.defined` and then use string.

```
chart.loadingSpan.innerHTML = str || options.lang.loading;
```

**Comment by fantapop** [comment]
`null` was not allowed by the type.  I was able to use empty string to hide the text and setting `display: inline-block` allowed me to render an svg.  Otherwise, I was only able to render a background image when there was text.

```
        .highcharts-loading-inner {
            display: inline-block;
            background: url('/img/loading.svg');
            height: 8px;
            width: 30px;
        }
```

It looked like setting other items in lang to undefined was pattern for having them not render so I was expecting the same here.  If undefined here is not supported, the type and docs should be updated.  Thank you for looking at this.  I've been having fun with your product so far. It's very capable.  `styledMode` examples are light however and its sometimes unclear which things aren't supported in styled mode.
