### ISSUE TITLE
Tools: Publish nightly to npm using a nightly/beta/next tag

### ISSUE THREAD

**Issue by activist** [highcharts/highcharts#11166]
With a nightly build we may also publish to npm using the `npm dist-tag` command. That way it will be possible for experimental users to use `npm install highcharts@nightly`

More info here: http://jbavari.github.io/blog/2015/10/16/using-npm-tags/

**Comment by bre1470** [comment]
We have to make sure, that the `nightly` build use an other version scheme as otherwise we are not able to publish the same version later on the regular `latest` tag.

**Comment by activist** [comment]
@bre1470 I was thinking that we should use 'next' as tag. 

I.e let CI modify package.json version e.g to `7.1.0-modified.20191203` and then run `npm publish --tag next`

There is a slight issue with this as you mention, and that is that by semver versioning 7.1.0-modified.20191203 < 7.1.0. I reckon that is more related to how we are historically have been bumping the version after each release. Ideally we should bump to something like 7.1.1-rc after releasing 7.1.0 in order be compliant with semver, but with regards to publishing of nightly builds on npm I'm not sure if it really matters at all as long as we make sure not to use 'latest' tag. 

An alternative way of omitting this could be to publish nightly builds under e.g 'highcharts-nightly' on npm. 

What do you think? Any other suggestions?

**Comment by activist** [comment]
Concluded that we will go for using GitHub dependency for now: `npm i github:highcharts/highcharts-dist#nightly`

Docs will be added via this PR: https://github.com/highcharts/highcharts/pull/12587

**Comment by activist** [comment]
Solved via https://github.com/highcharts/highcharts/pull/12587

Documentation for installing nightly can be found here: https://www.highcharts.com/docs/getting-started/install-from-npm
