### ISSUE TITLE
SVGElement.fadeIn doesn't work

### ISSUE THREAD

**Issue by anikolaev** [highcharts/highcharts#11164]
#### Expected behaviour
API documentations mentions `fadeIn` method in `Highcharts.SVGElement` 
https://api.highcharts.com/class-reference/Highcharts.SVGElement#fadeIn
but it doesn't work returning
`Uncaught TypeError: renderer.g(...).fadeIn is not a function`

I also couldn't find any implementation is source files.

#### Actual behaviour
Either method should exist or the documentation should be updated.

#### Live demo with steps to reproduce
http://jsfiddle.net/k5grd1cz/

#### Product version
Highcharts v7.1.2

**Comment by pawelfus** [comment]
Hi @anikolaev 

As per docs, you need to install `drilldown` module: 

![Screen Shot 2019-06-25 at 15 26 12](https://user-images.githubusercontent.com/1453926/60102251-98092680-975d-11e9-9440-9d9e45a75b01.png)

Demo: http://jsfiddle.net/BlackLabel/pL0nrd9b/

**Comment by anikolaev** [comment]
Hmm, I missed it. It is the only method requiring additional 10KB module implementing unrelated tasks. Maybe it worth moving this method to the core code.

**Comment by pawelfus** [comment]
The only module that uses `fadeIn` is `drilldown`. I agree, it would be nice to have all features in one place. From the other hand, we would force all other users that don't use `fadeIn()` to load extra bytes..

**Comment by TorsteinHonsi** [comment]
It is just a shorthand for setting opacity to 0 then animating it to 1, so the workaround is minimal: http://jsfiddle.net/highcharts/54v07hqo/
