### ISSUE TITLE
Force-Directed NetworkGraph in Highcharts #11124: Another problem was discovered

### ISSUE THREAD

**Issue by leostar-eva** [highcharts/highcharts#11171]
#11124 Thanks for the answer to my question, but at the same time, I found another problem: when 'chart.update()' exists in the click event of the node to update the node, the node will still move. For example, we need to change the node's 'lineColor', 'lineWidth', 'radius', and update the node through' chart.update() '. Like this:

`point: {
          events: {
            click: function (e) {
              this.update({
				  marker: {
					...this.marker,
					...{
					  lineColor: this.commonColor // '#f73cb2'
					}
				  }
				})
            }
          }
        }`

So I wonder if I can add some judgment in 'chart.update ()', if the node only changes some appearance properties, and does not change the number of nodes and the relationship between nodes, there is no need to recalculate the position. Or you can update the appearance properties of the node in some other way. Very urgent. Thank you.

#### Affected browser(s)
Chrome,
Not tried in other browsers.

**Comment by pawelfus** [comment]
Hi @leostar-eva 

Context in `point.events.click` refers to `point`, so you call `point.update()`, not `chart.update()`. Anyway, did you consider using simple `marker.states`? See: https://jsfiddle.net/BlackLabel/xk9t2hye// - states are doing exactly as you expect - only visual attributes are changed.

API:
- https://api.highcharts.com/highcharts/series.networkgraph.allowPointSelect
- https://api.highcharts.com/highcharts/series.networkgraph.marker.states

PS: Please, don't spam our tickets. It really won't speed up things - actually the opposite.. If you have more questions, please contact our [support](https://www.highcharts.com/blog/support/). Thanks  for your understanding!

**Comment by leostar-eva** [comment]
@pawelfus I'm sorry that I sent you junk mail without knowing it. It may be a mistake. I checked my mailbox and did not send any records, so why?

To get back to the problem, I need to click the node under the different branches under the root node to change it to a different color, as shown in figure 1. At the beginning, all nodes are gray. When clicked, as shown in figure 2, the nodes under different branches under the root node need to change different colors, so `marker.states` cannot process them.

I used `this.update()` in the click event of `point` in the code. `this` here means `point`, so I did not directly use `chart.update()` , so the problem still exists. 

`point: { events: { click: function (e) { this.update({ marker: { ...this.marker, ...{ lineColor: this.commonColor // '#f73cb2' } } }) } } }`

![image](https://user-images.githubusercontent.com/10704179/60168551-a1ff5800-9837-11e9-85c4-91523a312331.png)

![image](https://user-images.githubusercontent.com/10704179/60168634-c5c29e00-9837-11e9-9b80-7c8925b26c7a.png)

**Comment by pawelfus** [comment]
Hi @leostar-eva 

You posted under three different tickets the same message :) This one (#11171), #11139 and #11107 

Thanks for the detailed explanation, could you contact our support with this details? Thanks!

**Comment by leostar-eva** [comment]
@pawelfus Thanks for your advice. I contacted the support center and got inspiration. After many attempts, I found the following problems:

Please see here: [https://jsfiddle.net/leostar_eva/gebhq69w/1](url). Click after the node does not move, but the source code error.The following figure:
![image](https://user-images.githubusercontent.com/10704179/60316859-fe30bc00-999e-11e9-9279-77fea731b095.png)

This is a problem I discovered when I started development. To avoid it, I looked through the source code and added 'index' attributes to each node in my code.The following figure:
![image](https://user-images.githubusercontent.com/10704179/60317036-d42bc980-999f-11e9-8b74-52f62d6d5885.png)

This avoids the error location in the source code, it seems that the problem is solved, but it led to a series of problems mentioned in my post later, click on the node will move. Please see here: [https://jsfiddle.net/leostar_eva/gebhq69w/7](url)

Source code error is really an objective existence, I hope you can pay attention to and solve. I'm really sorry for disturbing you these days. Thank you.

**Comment by pawelfus** [comment]
Thanks for the details and demos! Let me open separate issue for `node.update()` error:  #11211

Regarding restarting simulation - not much we can do with limited number of iterations. System is not stable, so whenever data update occurs, layout's algorithm starts over. The same happens if you resize browser window. 

You can workaround by fixing positions of nodes when you update point and stop simulation right after updating, see: https://jsfiddle.net/BlackLabel/yhpdwmqa/ This way click event should look:

```js
        click: function() {
          // Pin nodes to it's positions
          this.series.nodes.forEach(function(node) {
            node.fixedPosition = true;
          });

	  // Update marker
          this.update({
            marker: {
              fillColor: 'red',
              lineColor: 'blue',
              radius: 20
            }
          });

	  // Let nodes reposition on window resize etc.
          this.series.nodes.forEach(function(node) {
            delete node.fixedPosition;
          });

          // Stop nodes positioning
          this.series.layout.stop();
        }
```

I would still recommend `marker.states` though:  https://jsfiddle.net/BlackLabel/t2uy159p/ - I just realized that `selected` state is flooding all other nodes, reported separately: #11212

Thank you once again for all the details! Let us know if you find any other issues.
