### ISSUE TITLE
Export data module(XLS) - wrong number format on Microsoft Excel

### ISSUE THREAD

**Issue by CesarBMartinez** [highcharts/highcharts#11170]
#### Expected behavior
Have numeric format options in the Export Data module.

#### Actual behaviour
I have a series of data of integer numbers and when exporting the chart as XLS and open it in Excel, the numbers are formatted with decimals(,00).

![Screenshot_66](https://user-images.githubusercontent.com/13169567/60127178-efab9000-9765-11e9-803b-cd33c9edb7ae.png)

I believe that this occurs because of this line here: 
https://github.com/highcharts/highcharts/blob/master/js/modules/export-data.src.js#L843

When I edited the source XLS and remove this style, works as expected.

#### Live demo with steps to reproduce
https://jsfiddle.net/eotg0pn8/

- Download XLS
- Open in Microsoft Excel

#### Product version
Highcharts 7.1.2

#### Affected browser(s)
Google Chrome

**Comment by sebastianbochan** [comment]
Hi @CesarBMartinez,
Thank you for reporting about the problem.

**Internal note**
We can consider to add format of numbers according to  the `lang.decimalPoint` option.

**Comment by pawelfus** [comment]
We have something like this for `csv` exporting: [`exporting.csv.decimalPoint`](https://api.highcharts.com/highcharts/exporting.csv.decimalPoint) - equivalent should be enough.

**Comment by TorsteinHonsi** [comment]
@CesarBMartinez I assume you meant this line

https://github.com/highcharts/highcharts/blob/040e8603774a4003b33953dc61b95117bc575907/js/modules/export-data.src.js#L844

Line numbers in the master are a moving target :)

Anyway I am not sure why this is at all needed. Instead of hardcoding to two decimals, it would probably be better to leave it to Excel to decide.

> We can consider to add format of numbers according to the lang.decimalPoint option.

I don't think the decimal point is the issue, rather the number of decimals. Correct me if I'm wrong.

**Comment by CesarBMartinez** [comment]
@TorsteinHonsi

**Comment by CesarBMartinez** [comment]
Hello guys!

> I don't think the decimal point is the issue, rather the number of decimals. Correct me if I'm wrong.

Yes @TorsteinHonsi, the problem here is with de number of decimals while I really don't want them.
So would be very nice if we have control of that.

![Screenshot_67](https://user-images.githubusercontent.com/13169567/60351996-4fd84700-999d-11e9-849c-6c87152a943b.png)

**Comment by sheariley** [comment]
I second this.  We need to be able to set formatting options for cells/columns/rows in XLS exports.
