### ISSUE TITLE
Sensible defaults for plotLines

### ISSUE THREAD

**Issue by theodoretliu** [highcharts/highcharts#11184]
#### Expected behaviour
When providing plotsLines, only providing the value should be sufficient.

#### Actual behaviour
At the very minimum, color, width, and value all need to be supplied. 

#### Live demo with steps to reproduce
https://jsfiddle.net/o2yq64vw/6/

#### Product version
Highcharts 7.1.2

#### Affected browser(s)
My browser is Chrome 74.0.3729.169 but would expect the problem to persist in most browsers.

**Comment by sebastianbochan** [comment]
Hi @theodoretliu,
Thank you for reporting. This is expected functionality, but I think that we can improve our docs and add information about mandatory fields.

@TorsteinHonsi  whad do you think?

**Comment by pawelfus** [comment]
Alternatively TS interface could provide this info. At this moment all options are optional, while the three above should be required:
```
        interface AxisPlotLinesOptions {
            color: ColorString;
            value: number;
            width: number;

            acrossPanes?: boolean;
            className?: string;
            dashStyle?: DashStyleValue;
            events?: any;
            id?: string;
            label?: AxisPlotLinesLabelOptions;
            zIndex?: number;
        }
```

**Comment by mlucool** [comment]
What is the reason for not having a default color/width? It would seem like there should be some default here like there are for series.

**Comment by theodoretliu** [comment]
To echo some of the sentiments here, I think types would certainly help enforce this. Also, the documentation at "https://api.highcharts.com/highcharts/yAxis.plotLines" does not seem to indicate that all three are required before the line shows up at all. Maybe console warnings if not all three are provided?

From an API design perspective, I do agree with @mlucool. As a user, I really only expect there to be a strict requirement on the most necessary of data. In this case, I feel like that is only the location of the line, not its style.

**Comment by TorsteinHonsi** [comment]
Consistent with other options in Highcharts, it should definately work by defining as little information as possible.

**Comment by theodoretliu** [comment]
Didn't mean to leave this hanging open for so long. The commit is in, so thanks everyone for their fast responses all those months ago!
