### ISSUE TITLE
Using Highcharts with lit-element (was: Polymer)

### ISSUE THREAD

**Issue by sebastianroming** [highcharts/highcharts#11180]
#### Expected behaviour
Importing and using Highcharts and all its modules.

#### Actual behaviour
Importing Highcharts with
`import 'highcharts';`
and using the modules is not possible:

If one imports a module with 
``` 
import Exporting from 'highcharts/modules/exporting';
```
an error is thrown:
```
The requested module '../../../../node_modules/highcharts/modules/exporting.js' does not provide an export named 'default'
```

If I try to import with `import 'highcharts/modules/exporting'`, I can't access the module.

***How can I correctly import and use Highcharts with all modules***?

#### Live demo with steps to reproduce
Full example:
```
import { LitElement, html } from 'lit-element';
import 'highcharts';
import 'highcharts/highcharts-more';
// import 'highcharts/modules/exporting';
// import Exporting from 'highcharts/modules/exporting';
// import * as Exporting from 'highcharts/modules/exporting';

class LdChart extends LitElement {

  firstUpdated() {
    this._enableChart();
  }

  _enableChart() {
    Highcharts.chart(this.shadowRoot.querySelector('#container'), {
      xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
        ]
      },
      series: [{
        data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
        type: 'column'
      }]
    });
  }

  render() {

    return html`
      <div id='container' style='width:500px;height:300px;'></div>
    `;
  }

}

customElements.define('ld-chart', LdChart);
```
In this example, the chart is rendered correctly, but I can't extend with modules as they don't have a default export.

#### Product version
`"highcharts": "^7.1.2"`

#### Affected browser(s)
Google Chrome 75.0.3770.100

**Comment by sebastianbochan** [comment]
Hi @sebastianroming,
Thank you for contacting us. The github is our bugtracker, so for general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.

ps. Please ensure if all modules are installed in the same version and try:

```
import * as Highcharts from 'highcharts';
import HC_exporting from 'highcharts/modules/exporting';
HC_exporting(Highcharts);
```

**Comment by sebastianroming** [comment]
Thanks. See [StackOverflow](https://stackoverflow.com/questions/56786792/using-highcharts-and-modules-with-lit-element) or the [live (not) working example](https://jsfiddle.net/sebastianroming/uer59cnw/6/)

**Comment by ashubham** [comment]
For anyone looking at this later https://github.com/ashubham/highcharts-webcomponent ... is a convenience ready to use wrapper over highcharts for web components (implemented using Lit).
