### ISSUE TITLE
Tooltip doesn't work with mootools and "position: fixed"

### ISSUE THREAD

**Issue by slawekkolodziej** [highcharts/highcharts#1118]
Go to this demo: http://jsfiddle.net/2zeZu/1/ when you scroll down tooltip stop working. Everything seems to work fine when you scroll up or switch to jQuery.

**Comment by jon-a-nygaard** [comment]
Since Highcharts has dropped adapters as of version 4.2, this issue will be closed.
Read more about  [the benefits of Highcharts without framework dependencies](http://www.highcharts.com/component/content/article/2-news/198-highcharts-drops-adapters)
