### ISSUE TITLE
Docs are confusing/incomplete for dateTimeLabelFormats

### ISSUE THREAD

**Issue by Lolmewn** [highcharts/highcharts#11198]
#### Expected behaviour
As described on the docs page (https://api.highcharts.com/highstock/xAxis.dateTimeLabelFormats) I expect that I can write the configuration of the dateTimeLabelFormats section as described in the default values. 

#### Actual behaviour
Instead of the values accepting a string, like in the defaults, it requires an object - some of which have both a `main` and a `range` variable, some of which only have a `main` value. It is not described what those variables are for, albeit that it's obvious that the `main` value is for the formatting string.

#### Live demo with steps to reproduce
n/a

#### Product version
Highcharts 7.1.2, typescript 3.4.5.

#### Affected browser(s)
n/a

**Comment by pawelfus** [comment]
Thanks for reporting the issue @Lolmewn 

Current defaults are:
```
                dateTimeLabelFormats: {
                    millisecond: {
                        main: '%H:%M:%S.%L',
                        range: false
                    },
                    second: {
                        main: '%H:%M:%S',
                        range: false
                    },
                    minute: {
                        main: '%H:%M',
                        range: false
                    },
                    hour: {
                        main: '%H:%M',
                        range: false
                    },
                    day: {
                        main: '%e. %b'
                    },
                    week: {
                        main: '%e. %b'
                    },
                    month: {
                        main: '%b \'%y'
                    },
                    year: {
                        main: '%Y'
                    }
                },
```

*Internal note:*
At this moment both formats are supported, but not in TS. We should change the defaults in docs to be consistent. The `XAxisDateTimeLabelFormatsSubOptions` interface should probably be interchangeable with `string` - I'll leave this decision up to @bre1470 and @TorsteinHonsi
