### ISSUE TITLE
Downloading the chart as image creates a duplicate datatable

### ISSUE THREAD

**Issue by Dhara-ZYMR** [highcharts/highcharts#11193]
#### Expected behaviour
Downloading the chart should only download it as image and not create another datatable

#### Actual behaviour
Downloading the chart as image creates a duplicate datatable

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/export-data/showtable/

- Currently, in this demo, we see a chart and a datatable.
Now, if you go to menu and download the chart as PNG/JPEG, a new datatable comes up below the existing one.

#### Product version
Highcharts

#### Affected browser(s)
Chrome Version 75.0.3770.100

**Comment by pawelfus** [comment]
Thank you for reporting the issue @Dhara-ZYMR 

**Workaround:**
Set `exporting.chartOptions.exporting.showTable` to false: https://jsfiddle.net/BlackLabel/vzdyn428/
