### ISSUE TITLE
grid line placement broken for single category y axis

### ISSUE THREAD

**Issue by robahs** [highcharts/highcharts#11199]
#### Expected behaviour
There should be a grid line on the top of the axis and one on the bottom.

#### Actual behaviour
The top grid line has moved to the middle, going straight through the points.

#### Live demo with steps to reproduce
broken in 7.0.2: https://jsfiddle.net/w0xfr2d3/
working in 7.0.1: https://jsfiddle.net/qu1pc5z2/

This only happens when there is only one category.

#### Product version
Highcharts 7.0.2 and above

#### Affected browser(s)
Firefox, chrome, Internet Explorer 11

**Comment by pawelfus** [comment]
Thank you for reporting this regression @robahs 

**Workaround:**
Disable `yAxis.startOnTick`, `yAxis.endOnTick` and modify a bit `yAxis.min` and `yAxis.max`: https://jsfiddle.net/BlackLabel/9x7w5yrf/ 

Snippet:
```js
    yAxis: {
        ...
        startOnTick: false,
        endOnTick: false,
        min: -0.1,
        max: 0.1
    },
```

*Internal note:*
Bisected to commit f32d7a00ee
