### ISSUE TITLE
highstock navigator render issue with fixed value data

### ISSUE THREAD

**Issue by boborua** [highcharts/highcharts#11191]
#### Expected behaviour
the line shape in navigator is waving when the data are all fixed value.

#### Actual behaviour
the line shape in navigator should be a straight line same with main area. 

#### Live demo with steps to reproduce

https://jsfiddle.net/kc4pjgut/

**Comment by pawelfus** [comment]
Thank you for reporting this issue @boborua 

**Workaround:**
Modify `dataGrouping.approximation` for navigator series.

Demo: https://jsfiddle.net/BlackLabel/pmef5roy/

Snippet:
```js
  navigator: {
    series: {
      dataGrouping: {
        approximation: function(arr) {
          var len = arr.length,
            ret = Highcharts.approximations.sum(arr);

          // If we have a number, return it divided by the length. If not,
          // return null or undefined based on what the sum method finds.
          if (Highcharts.isNumber(ret) && len) {
            ret = Highcharts.correctFloat(ret / len);
          }

          return ret;
        }
      }
    }
  },
```

**Comment by boborua** [comment]
hi Paweł, it seems that in my context, there's no property named approximations under Highcharts object.
my highchart version is:     "highcharts": "5.0.11"

**Comment by pawelfus** [comment]
Demo for you @boborua : https://jsfiddle.net/BlackLabel/pmef5roy/1/
