### ISSUE TITLE
Highcharts indicator SMA edit feature not distinguishable on series

### ISSUE THREAD

**Issue by Pratyush2710** [highcharts/highcharts#11206]
#### Expected behaviour
Whenever we draw SMA indicator or any indicator on stockcharts, it draws on the selected chart but on edit option we see the default first series for that SMA in the dropdown.

#### Actual behaviour

Whenever we draw SMA indicator or any indicator on stockcharts, it draws on the selected chart but on edit option we cannot see the previous selected series for that SMA, default top series is selected in dropdown.

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/stock-tools-gui

Steps:
1. Draw SMA indicator on the AAPL Stock Price
2. Draw SMA indicator on the AAPL Volume
3. Edit the Indicator modal, with both SMA drawn we have AAPL Stock Price selected as series by default.

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Thanks for reporting the issue @Pratyush2710 

@sebastianbochan  could you take a look?
