### ISSUE TITLE
A negative width/height of heatmap cells is not valid

### ISSUE THREAD

**Issue by lanhq** [highcharts/highcharts#11229]
#### Expected behaviour
Heatmap is rendered without Js error

#### Actual behaviour
If there are many categories on xAxis or yAxis then the original width/height of heatmap cells may be less than `pointPadding * 2`. So after applying pointPadding, the cells have negative width or height.
example: 
`{Height: 1px; pointPadding: 2px}`
=> after apply pointPadding, new height is `-3` and heatmap is rendered with js error
`Error: <rect> attribute height: A negative value is not valid. ("-3")`

#### Live demo with steps to reproduce
https://jsfiddle.net/corundhope/nzphexyv/10/

#### Product version

Highcharts 7.1.1

#### Affected browser(s)
All browsers

**Comment by sebastianbochan** [comment]
Hi @lanhq ,
Thank you for reporting about the problem.

FYI @jon-a-nygaard
