### ISSUE TITLE
Typescript typing issue when using bar chart

### ISSUE THREAD

**Issue by maxailloud** [highcharts/highcharts#11221]
Configuring my chart to display my data and I get typing issue on it.

#### Expected behaviour
No typing issue on something that looks on the correct type.

#### Actual behaviour
I am using it in an Angular project, but the typescript error comes from highcharts typedef not from the angular package.

The configuration for my chart:
```js
{
    chart: {
        type: 'bar',
        backgroundColor: '#F8F8F8',
        margin: 0,
    },
    series: [
            {name: 'Lost Power', data: [10], color: '#ED4D6C'},
            {name: 'Offline', data: [10], color: '#FFD560'},
            {name: 'Unconfigured', data: [10], color: '#77D6DD'},
            {name: 'Uncalibrated', data: [10], color: '#994BC3'},
            {name: 'Online', data: [10], color: '#7CDC9C'},
            {name: 'In Use', data: [10], color: '#3183F5'},
        ],
    plotOptions: {
        bar: {
            stacking: 'percent',
            animation: false,
            enableMouseTracking: false,
            pointWidth: 25,
        }
    }
}
```

The error that I get when `ng serve`:
```
ERROR in src/app/my.component.ts(209,13): error TS2322: Type '{ name: string; data: number[]; color: string; }[]' is not assignable to type '(SeriesAbandsOptions | SeriesAdOptions | SeriesAoOptions | SeriesApoOptions | SeriesAreaOptions | SeriesArearangeOptions | SeriesAreasplineOptions | SeriesAreasplinerangeOptions | ... 88 more ... | SeriesZigzagOptions)[]'.
      Type '{ name: string; data: number[]; color: string; }' is not assignable to type 'SeriesAbandsOptions | SeriesAdOptions | SeriesAoOptions | SeriesApoOptions | SeriesAreaOptions | SeriesArearangeOptions | SeriesAreasplineOptions | SeriesAreasplinerangeOptions | ... 88 more ... | SeriesZigzagOptions'.
        Property 'type' is missing in type '{ name: string; data: number[]; color: string; }' but required in type 'SeriesZigzagOptions'.
```

In the `SeriesZigzagOptions` class the `type` property is as follow `type: "zigzag";`.
I don't understand what I can do with that.
Adding `type: 'area'` for an area chart did the trick but for this one adding `type: 'bar'` just give me an other error `Type 'string' is not assignable to type '"zigzag"'.`. Not helpful.

#### Product version

highcharts v7.1.2

**Comment by sebastianbochan** [comment]
Hi @maxailloud,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by bre1470** [comment]
@maxailloud 
You have to specify the type property in each series. TypeScript does not support a default series type for checking types. See: https://api.highcharts.com/highcharts/series.bar

**Comment by maxailloud** [comment]
@bre1470 I tried adding `type: 'bar'` to all of my series, but I got a different typing error in that case:
```
Types of property 'type' are incompatible.
            Type 'string' is not assignable to type '"zigzag"'.
```

My new configuration:
```
{
    chart: {
        type: 'bar',
        backgroundColor: '#F8F8F8',
        margin: 0,
    },
    series: [
            {name: 'Lost Power', data: [10], color: '#ED4D6C', type: 'bar'},
            {name: 'Offline', data: [10], color: '#FFD560', type: 'bar'},
            {name: 'Unconfigured', data: [10], color: '#77D6DD', type: 'bar'},
            {name: 'Uncalibrated', data: [10], color: '#994BC3', type: 'bar'},
            {name: 'Online', data: [10], color: '#7CDC9C', type: 'bar'},
            {name: 'In Use', data: [10], color: '#3183F5', type: 'bar'},
        ],
    plotOptions: {
        bar: {
            stacking: 'percent',
            animation: false,
            enableMouseTracking: false,
            pointWidth: 25,
        }
    }
}
```

Maybe i'm missing something to do it correctly but I genuinely don't see what.

**Comment by bre1470** [comment]
Some older TypeScript versions had problems to distinguish between literal types and strings. I tested with v2.9.2, v3.4.5, v3.5.2 - and your latest options work for me. Therefor I suggest that you double check, that you actually using the latest version of TypeScript and Highcharts.

**Comment by maxailloud** [comment]
With the version of Angular I am using I can't use Typescript v3.5.2, compiler requires `>=3.4.0 and <3.5.0`.
After maybe it comes from my typing for the chart options. I used `Highcharts.Options`. Is it the right type to use for that?

**Comment by bre1470** [comment]
`Highcharts.Options` is the correct type. Here is the code, that works for me:
```ts
import * as Highcharts from 'highcharts';

const container: (HTMLElement|null) = document.getElementById('container');
const options: Highcharts.Options = {
    chart: {
        type: 'bar',
        backgroundColor: '#F8F8F8',
        margin: 0,
    },
    series: [
            {name: 'Lost Power', data: [10], color: '#ED4D6C', type: 'bar'},
            {name: 'Offline', data: [10], color: '#FFD560', type: 'bar'},
            {name: 'Unconfigured', data: [10], color: '#77D6DD', type: 'bar'},
            {name: 'Uncalibrated', data: [10], color: '#994BC3', type: 'bar'},
            {name: 'Online', data: [10], color: '#7CDC9C', type: 'bar'},
            {name: 'In Use', data: [10], color: '#3183F5', type: 'bar'},
        ],
    plotOptions: {
        bar: {
            stacking: 'percent',
            animation: false,
            enableMouseTracking: false,
            pointWidth: 25,
        }
    }
};

if (container) {
    Highcharts.chart(container, options);
}
```

**Comment by maxailloud** [comment]
That's pretty much what I have, except the options is an attribute of my component (Angular component).
Highcharts v7.1.2 so the last version. Maybe because of Typescript I don't know. Or maybe angular compiler doing something different.

**Comment by bre1470** [comment]
Hmm... I will test it with an Angular setup. My `tsconfig.json` looks like this btw:
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "es6",
        "outDir": "bin/",
        "strict": true,
        "moduleResolution": "node"
    },
    "exclude": [
        "node_modules"
    ],
    "include": [
        "src/**/*.ts"
    ]
}
```

**Comment by maxailloud** [comment]
Mine is as follow:
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "src",
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "module": "esnext",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "importHelpers": true,
        "target": "es2015",
        "suppressImplicitAnyIndexErrors": true,
        "noImplicitAny": true,
        "noImplicitThis": true,
        "alwaysStrict": true,
        "strictNullChecks": true,
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2018",
            "dom"
        ],
    },
}
```

If i'm not mistaking pretty much the basic angular-cli one.

**Comment by bre1470** [comment]
I tested with `@angular-cli` v8.0.6 and others and it compiles fine with your options. I have no idea, how to reproduce it.

Maybe there is a conflict between local node modules and globals. Try `npx ng serve` to use you project specific modules.

Or maybe you can solve the problem by creating a new project and move all you custom code over.

**Comment by bre1470** [comment]
Here is my test project: https://github.com/bre1470/highcharts-declarations-issue11221

**Comment by dandv** [comment]
I have the same problem when using `series.update`:

![image](https://user-images.githubusercontent.com/33569/78461712-865aa380-771f-11ea-8df8-86cdc1c8561c.png)

If I add a bogus `type` value, the error goes away.

Highcharts 8.0.3, TypeScript 3.8.3.

**Comment by bre1470** [comment]
Yes, TypeScript goes through all the possible sets of series options for a match and fails after SeriesZigZagOptions. Try `series.update({ type: 'bar', color: 'purple' })`.
