### ISSUE TITLE
Piecewise linear time scale (PLTS) option for X-axis

### ISSUE THREAD

**Issue by ryantenney** [highcharts/highcharts#1124]
I was recently made aware of the concept of a piecewise linear time scale or PLTS, thanks to a blog post: http://metamarkets.com/2012/time-in-perspective/

The examples are implemented with D3.js, but I'd be interested in applying this to my existing highcharts graphs.  Is this a feature you'd consider adding?

Thanks for the great product,
Ryan

**Comment by oysteinmoseng** [comment]
Closing as this is already doable in Highstock, either using the [ordinal datetime axis](https://jsfiddle.net/gLs16yL7/), or using [multiple X axes](http://jsfiddle.net/pboh6ss7/).

**Comment by TorsteinHonsi** [comment]
I believe [axis breaks](https://api.highcharts.com/highcharts/xAxis.breaks) is the simplest way of doing this now.

**Comment by oysteinmoseng** [comment]
Can we do this with axis breaks?

**Comment by TorsteinHonsi** [comment]
No. I was wrong 😩
