### ISSUE TITLE
Variwide chart - logarithmic yaxis spacing issue

### ISSUE THREAD

**Issue by rajeshdanabal** [highcharts/highcharts#11249]
#### Expected behaviour
Chart should plot with in the range of yaxis values  with out unwanted space.

#### Actual behaviour
Chart is plotting with some empty space on yaxis

#### Live demo with steps to reproduce

http://jsfiddle.net/rajeshdanabal/s978at46/

On the above example, yaxis type linear is setting axis till 100 and yaxis type logarithmic is setting axis till 200.

#### Product version

Highcharts V7.1.2
#### Affected browser(s)
Google chrome -  Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @rajeshdanabal,
By default, yAxis has applied the `maxPadding` option. When you reset it and disable `endOnTick`, your chart will be draw like you expect.

**Docs:**
- https://api.highcharts.com/highcharts/yAxis.endOnTick
- https://api.highcharts.com/highcharts/yAxis.maxPadding

**Demo:**
- http://jsfiddle.net/BlackLabel/73vcbfro/
