### ISSUE TITLE
Ichimoku Cloud future dates should consider 'ordinal' flag

### ISSUE THREAD

**Issue by spatel76** [highcharts/highcharts#11245]
#### Expected behaviour
this indicator should not include weekends on 'period' future dates.

#### Actual behaviour
it does show weekends.

#### Live demo with steps to reproduce
https://www.highcharts.com/forum/viewtopic.php?f=12&t=42183

#### Product version

highstock version 7.1.2 (may be all)

**Comment by Basts** [comment]
[Demo] which is showing weekends for future dates (http://jsfiddle.net/fsLy3che/)

Suggested [workaround](https://jsfiddle.net/BlackLabel/9mxo5pu3/)

The above link to forum includes a detailed user description and images of the noticed issue.

**Comment by pawelfus** [comment]
Hi @spatel76 

Thank you for reporting this issue. Let me explain: `ordinal` axis does not remove wekeends, but simply removes empty space between points. In our Ichimoku cloud, points are generated according to the closest range between two points, then added to the end with values. 

I agree, it would be nice to skip weekends, but then what should be do with bank holidays? Not to mention bank holidays in different countries. Maybe an API option for Ichimoku, to inform algorithm which time ranges should be skipped? For example `skip: [{ from: timestamp, to: timestamp }]`. This way you could remove weekends, and, if using Ichimoku cloud with other granularity, non-working hours.

**Comment by spatel76** [comment]
giving options to user to skip ranges would be really nice. that would be ideal.
