### ISSUE TITLE
Styled mode: Invalid xAxis crosshair's width when xAxis has categories

### ISSUE THREAD

**Issue by metoule** [highcharts/highcharts#11246]
#### Expected behaviour

If the xAxis has categories, and `crosshair` is set to `true`, then the crosshair's width should be one category, as specified in the [API](https://api.highcharts.com/highcharts/xAxis.crosshair.width).

That doesn't works as expected when in styled mode (but it works when NOT in styled mode).

#### Actual behaviour

When in styled mode, the crosshair's width is 1px instead of one category.

#### Live demo with steps to reproduce

- 6.2.0 version: crosshair width is one category: http://jsfiddle.net/Metoule/2wp19qda/2/
- 7.1.2 version: crosshair width is 1px: http://jsfiddle.net/Metoule/2wp19qda/3/

#### Product version

Highcharts >= 7.0.0

#### Affected browser(s)

All

**Comment by pawelfus** [comment]
Hi @metoule 

Thank you for reporting the issue.

Bisected to commit b8d8a4361c
