### ISSUE TITLE
Dashboard editor and Publish feature

### ISSUE THREAD

**Issue by kalimuthu123** [highcharts/highcharts#11255]
#### Expected behaviour
             I  need to be publish dashboard across the internet

#### Actual behaviour
            interactive and filter level charta are mixed and arranged in Dashboard

#### Live demo with steps to reproduce
 Publish level of dashboard feature is requested

**Comment by pawelfus** [comment]
Hi @kalimuthu123 

You posted on our bug tracker. Please contact our support first: https://www.highcharts.com/blog/support/ Thank you!
