### ISSUE TITLE
Variwide: Wrong threshold to autorotate x-labels

### ISSUE THREAD

**Issue by hosekp** [highcharts/highcharts#11260]
#### Expected behaviour
If the columns are too narrow for horizontal x-labels, the labels are rotated to prevent overlap.

#### Actual behaviour
Labels are overlapping if chart is wide enough to prevent overlaps in classic no-variwide chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/hosekp/w7La6xk4/1/
Labels are overlaping if chart width is between 1500px and 5500px

#### Product version
Highcharts v7.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @hosekp 

Thank you for reporting this issue.

*Internal note:*
Related ticket: #7635 - most probably reason behind that is the same: available slot for xAxis.label is calculated for equal categories, which is not the case in variwide. That rotates/hides labels too late.
