### ISSUE TITLE
Imports highcharts-more and solid-gauge

### ISSUE THREAD

**Issue by TheRisa** [highcharts/highcharts#11261]
#### Expected behaviour
Imports Hicharts-more and solid gauge by direct import.

#### Actual behaviour
Can't directly import Hicharts-more and solid-gauge. Have to use this work-aroud:

`require('highcharts/highcharts-more')(Highcharts);`
`require('highcharts/modules/solid-gauge')(Highcharts);`

#### Product version
highcharts: ^7.1.1

#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Hi @TheRisa 

Thanks for reporting the issue, but this is expected: first load `highcharts-more` then `solid-gauge`, so this:

```js
require('highcharts/highcharts-more')(Highcharts);
require('highcharts/modules/solid-gauge')(Highcharts);
```
Is not a workaround but the correct way to load `solid-gauge`.
