### ISSUE TITLE
Axis padding incorrect (or at very least non-intuitive) with threshold

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#11291]
Take the following example:

https://jsfiddle.net/4xuthona/1/

When it loads, data up to October is shown.  The plot is almost touching the x axis. 

Now a new data point comes in for November... change the boolean variable `showNovemberValue` to `true` to show it.  This is the only change from the above example to the following example:

https://jsfiddle.net/4xuthona/2/

Now, suddenly, the plot is spaced apart from the x axis, just by the addition of this one new point. 

The reason this happens is because the new point happens to lie below the `threshold` (Fahrenheit freezing point of 32F), so that `minPadding` now suddenly starts working.

This to me is incorrect behaviour, or at the very least completely illogical and non-intuitive. 

In my use case, the data being displayed is real-world, live data, and I have no control over whether the line will lie entirely above the `threshold`, entirely below it, or crossing through it.  And yet I still require a consistent minimum (and maximum) padding to be shown, regardless of the data (and I need non-zero padding as opposed to zero padding).  

This slightly inconsistent padding behviour makes it very difficult to achieve, without resorting to a custom `tickPositioner()` and/or `min`/`max`, which I don't believe should be necessary for such a basic charting requirement, i.e. consistent and predictable placement of the line.

Playing with `softThreshold` seems to have no effect.

**Comment by pawelfus** [comment]
Thanks for reporting the issue @drmrbrewer 

It's a bug in our docs, saying that threshold applies only to the negative color. `threshold` option disables `minPadding`/`maxPadding` when all data is above (`minPadding`) or below (`maxPadding`) threshold.

Instead I recommend to use [`zones`](https://api.highcharts.com/highcharts/series.line.zones) which don't alters `min/madPadding` options: https://jsfiddle.net/BlackLabel/vdx5rf1q/

**Comment by bre1470** [comment]
Despite of the workaround with the [`zone`](https://api.highcharts.com/highcharts/series.line.zones) option this issue has been solved in the latest versions (v8.0.4) by improving the padding behaviour.
