### ISSUE TITLE
Boost and responsive rules makes chart is drawing twice

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#11293]
As in the title: Boost module and responsive rules to hide chart title and subtitle make chart is drawing twice.

#### Live demo with steps to reproduce

[Demo](https://jsfiddle.net/BlackLabel/9moru07g/). After window resizes, the chart is rendering properly. 

#### Product version

Highcharts JS v7.1.2 (2019-06-03)

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
**Workaround**
Call `chart.setSize` with current size of container.

Demo:
- https://jsfiddle.net/BlackLabel/4s02x6nh/

**Comment by e965** [comment]
This bug still exists in the Highcharts. [Crutch](https://github.com/highcharts/highcharts/issues/11293#issuecomment-508383518) with `chart.setSize` can fix all, but it is annoying.
