### ISSUE TITLE
[Accessibility] View Full Screen as Toggle

### ISSUE THREAD

**Issue by Eddie-Hartman** [highcharts/highcharts#11296]
#### Expected behaviour
After clicking "View in full screen" as added in #9895, I'd expect that that menu item then becomes "exit full screen".

#### Actual behaviour
The menu item stays "View in full screen" and does nothing when the graph is full screened.

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/LLExL/

#### Product version
7.1.0 forward.

#### Affected browser(s)
All.

#### Additional notes
Mainly just seems like a simple usability enhancement.

**Comment by sebastianbochan** [comment]
Hi @Eddie-Hartman,
Thank you for the good suggestion. I marked this case as enhancement.

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
This is a great idea.

Changed the title slightly for searchability.

**Comment by Eddie-Hartman** [comment]
@raf18seb Any updates on the timeline of this? I see that you've moved it from in progress to backlog.

I mainly just ask because this is something that we were waiting on to upgrade to a later version. 
Definitely something we were looking forward to.

**Comment by raf18seb** [comment]
Hi @Eddie-Hartman 

We don't have an official ETA for this - we are prioritizing the new Highcharts 8 features now and the full-screen module is not on that list. However, I believe that full-screen will be added to Highcharts with 8.0.0 or 8.0.1.

Best regards!
