### ISSUE TITLE
SolidGauge leaks labelCollectors

### ISSUE THREAD

**Issue by DomJo** [highcharts/highcharts#11290]
#### Expected behaviour
Updating options of a solidGauge should not degrade performance.

#### Actual behaviour
Every time a solidgauge is updated like this:
```
    chartSpeed.update({
      yAxis: {
        min: 0,
        max: 200,
        title: {
          text: 'Speed'
        }
      },

      series: [{
        data: [10],
      }]
```
a new function is added to Chart.labelCollectors. This happens in RadialAxis.js, line 537 (the init event). There is no corresponding cleanup event. 
If the update is done periodically, the application quickly becomes irresponsive. When profiling, you see that a lot of time is spent in hideOverlappingLabels.

#### Live demo with steps to reproduce
http://jsfiddle.net/zmu9wfov/

#### Product version
Highcharts 7.1.2

#### Affected browser(s)
Tested on Chrome

**Comment by sebastianbochan** [comment]
Hi @DomJo,
Thank you for reporting about the bug.
