### ISSUE TITLE
New functionality: Centering columns inside the categories with nullPoints 

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#11308]
When null points are present in the data (and should be ignored on graph), they should not occupy space in related category.

Current version:
![Screenshot 2019-07-04 at 11 55 28](https://user-images.githubusercontent.com/15050812/60658040-adafd780-9e52-11e9-8ade-69c5f1a024d5.png)

Current workaround:
http://jsfiddle.net/hgjvpqab/

Demo with a workaround:
![Screenshot 2019-07-04 at 11 55 36](https://user-images.githubusercontent.com/15050812/60658063-ba343000-9e52-11e9-914a-aca0d5c9d77a.png)

**Comment by shashank1010** [comment]
There is a strong use case of the same functionality with bar charts as well.

**Comment by raf18seb** [comment]
Hi,

This feature will be working with column, bar and columnrange series. Additionally, we are planning to add more series in the future like errorbar and boxplot.

**Comment by dm1tr** [comment]
Hi,

Could you please tell, when are you going to add it in a release?

Thanks.

**Comment by pawelfus** [comment]
Hi @dm1tr - I expect this feature to be released in v8.0.1 or v8.0.2.

**Comment by shashank1010** [comment]
Hi,

Kindly update on the expected availability for this functionality.

Thanks.
