### ISSUE TITLE
New functionality: Vertical panning implementation

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#11315]
Implementing vertical panning in Highstock.

**Comment by WhiteRaBot17** [comment]
How's the progress on this would love to implement it on my chart.

**Comment by sebastianbochan** [comment]
Hi @WhiteRaBot17,
At this moment we are at the begining of developing process and we do not have ETA for this feature, yet.

**Comment by Izothep** [comment]
Closed by https://github.com/highcharts/highcharts/pull/11779
