### ISSUE TITLE
New Series Type: Lollipop

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#11311]
Creating Lolipop Series.

Internal: 
It should be possible to borrow logic from errorbar or columnrange for creating similar graph.

**Comment by pawelfus** [comment]
Alternative approach:
Borrow logic from arearange (multiple markers per point) + columnrange (connector between markers). What would be missing is different configs per marker in point.

**Comment by Izothep** [comment]
Closed by #11740
