### ISSUE TITLE
Transform issue with tooltip.outside

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#11329]
The hover on line charts is off when you use css **transform** on a parent container.

On http://jsfiddle.net/kzoon/jswhn2v8/3/ hover activates data points to the left of the actual mouse pointer. The more to the right, the worse it gets.
The column series does NOT have this issue ?!?!

It looks like the fix of https://github.com/highcharts/highcharts/issues/10498 doesn't work in all cases.
In the meantime, my own workaround for tooltip positions (see https://github.com/highcharts/highcharts/issues/2405) doesn't help here anymore.

For me this issue is quite urgent, because the problem happens in a version already released to my customers.

**Comment by pawelfus** [comment]
Hi @kzoon 

Let me answer your questions:
> The column series does NOT have this issue ?!?!

Columns show tooltip when hover happens directly over a rectangle. For other series types (like area, line, spline etc.) we use k-d tree for searching the closest point to the pointer. Values used for searching and rendering are the same, but `transform: scale()` changes how rendered chart looks.

> It looks like the fix of #10498 doesn't work in all cases.

Issue #10498 refers to the width of the chart, not related to the tooltip's position.



Is that issue any different from #2405? At this moment it seems to be a duplicate which I should close..

Workaround posted originally by @TorsteinHonsi seems to be fine (simplified a little): http://jsfiddle.net/BlackLabel/6jng50dy/

**Comment by kzoon** [comment]
The workaround works in the fiddle I supplied. My problem now is that it doesn't in the real world. So, the fiddle was not representative of the real problem. I will try to make a fiddle that shows my problem.

**Comment by kzoon** [comment]
Found it. You added scale: 0.7 to the chart JSON in order to make the workaround work. I can't do that. The transform happens in a different application layer from the one that adds the chart, so I can't just put the scale into the chart config.

So I'm looking for a workaround that doesn't require the chart to know the transform scale.

I had such a workaround based on getBoundingClientRect and offsetWidth of the chart container (see my code in https://github.com/highcharts/highcharts/issues/2405) but that one doesn't work anymore.

**Comment by kzoon** [comment]
Found the real problem:
 ```
 tooltip: {
    outside: true
  },
```
makes the tooltip to go all over the place when using transform scale.
See   http://jsfiddle.net/kzoon/0arw8t7j/6/

**Comment by pawelfus** [comment]
Thanks for the details! 

We have a few problems in the demo:
- different scales (for tooltip and chart)
- wrong position
- callout for manually translated tooltip

In short, I would add the same scale for tooltip's container, use `tooltip.positioner` for wrong position and change shape of the tooltip: http://jsfiddle.net/BlackLabel/w1xs48ga/ (note: instead of defining `scale` I used your solution for getting scale of the element).

**Comment by kzoon** [comment]
Thanks for the workaround. I think I will get problems with my customers if I change the shape of the tooltip on all charts. Is there a way to prevent this?

Any idea when Highcharts can have a final solution to the 'outside' scaling issue ( or all scaling issue)?

**Comment by pawelfus** [comment]
Well, another wrap can add anchor if that's important: http://jsfiddle.net/BlackLabel/y750sjvz/

> Any idea when Highcharts can have a final solution to the 'outside' scaling issue (or all scaling issues)?
No idea, it's vacation time so fixes can be delayed.

**Comment by kzoon** [comment]
I keep running into additional problems. The workarounds fail when the div with the scaling on it is not positioned on the top-left of the screen.
I replicated this issue in this fiddle: http://jsfiddle.net/kzoon/nwfj650d/4/ by setting an top and left margin to the div.
Can we compensate for that as well?

**Comment by pawelfus** [comment]
It seems that [`tooltip.positioner`](https://api.highcharts.com/highcharts/tooltip.positioner) is the best to work with, for example: http://jsfiddle.net/BlackLabel/L0kx9qhs/

**Comment by kzoon** [comment]
In http://jsfiddle.net/BlackLabel/L0kx9qhs/ the tooltip is below the mouse pointer.

I appreciate the effort you put in helping me out with workarounds, but I think I will have to wait for the real bug fix. My customers have a large degree of freedom designing dashboards with charts on them. I can't be sure that a workaround will cover all different configurations. 

These are the issues that we have seen so far (demonstrated in http://jsfiddle.net/kzoon/5tob7d2h/)

- On line series the wrong data point is activated: hovering point 5 activates point 3. On column series the correct data point is activated
- The scaling used for tooltip position is off: the tooltip on the last column is much farther away from the mouse pointer than on the first column.
- The tooltip position gets worse when the Highcharts container is not positioned top-left (done with margin-left/top in the fiddle).
- The tooltip itself is not scaled (too large for scale 0.7)
- Tooltip option outside: true seems to cause extra trouble

**Comment by ocenteno** [comment]
Good morning,

Sorry for putting pressure on this ticket but it´s very urgent for us as it impacts all our customers.
Any hotfix is deeply appreciated.

Regards

**Comment by oysteinmoseng** [comment]
@ocenteno @kzoon

Thank you for your patience with this. I have created a fix that seems to function adequately for the scenarios discussed in this thread, as well as other potentially critical scenarios (chart.inverted, split tooltip etc). Please test this drop-in fix out and let me know if there are further issues: http://jsfiddle.net/cta3e6vy/

Once we have a satisfactory solution we can discuss if there is a good way to integrate this into the core for the next version.

**Comment by ocenteno** [comment]
Thanks a lot @oysteinmoseng we will test it and come back to you

**Comment by ocenteno** [comment]
Update
On our test environment the fix is working, we will continue the testing in staging.

**Comment by ocenteno** [comment]
The fix works ok in our staging environment.

Thanks a lot for your support.

**Comment by sebastianbochan** [comment]
Thank you for the feedback.

**Comment by Dams591** [comment]
Hey guys,
I'm facing a related issue using the latest highchart build.
Updating the transform/scaling will result in tooltip being badly placed.

Here's an example:
Everything looks good until you click the "update" button that change the scaling

http://jsfiddle.net/16qkbLv0/

Any workaround I could apply ?
Thank you.

**Comment by sebastianbochan** [comment]
Hi @Dams591,
Your issue is related with our two other cases: https://github.com/highcharts/highcharts/issues/11975 and https://github.com/highcharts/highcharts/issues/12031.

**Comment by Dams591** [comment]
@sebastianbochan you're right, if I understand correctly there's no (and never will be) automatic reflow of highchart when the scale (or window size) is changing ? I have to implement chart render manually ?

**Comment by sebastianbochan** [comment]
At this moment, yes, you are correct. Both cases are still opened, so you should use one of solutons there.

**Comment by kzoon** [comment]
@sebastianbochan can you please reopen this issue? Or create a new one?

In 6.2.0 + drop-in setting the scale afterwards **IS** handled correctly, as you can see in this fiddle: http://jsfiddle.net/kzoon/eq6y0sgr/

In 7.2.1 and higher versions without the drop-in setting the scale afterwards **IS NOT** handled correctly: 
http://jsfiddle.net/kzoon/5npf3wLd/

So, Highcharts can handle scale changes after rendering, but somehow the functionality got changed when it was included in the main Highcharts code.

I have already installed versions with 7.2.1, so again I am anxious to solve/work around this issue.

**Comment by pawelfus** [comment]
Thanks @kzoon for the examples. It's already reported (and closed) here: #11975 - see the solution and comment from Oystein there. If you have any suggestions, please share them in #11975 - thanks!
Demo based on #11975 answer: http://jsfiddle.net/BlackLabel/m5baezyq/1/
