### ISSUE TITLE
Range selector button highlight issue

### ISSUE THREAD

**Issue by coded9** [highcharts/highcharts#11325]
#### Expected behaviour
Corresponding rangeSelector button  should get highlighted

#### Actual behaviour
Corresponding rangeSelector button doesn't get highlighted

#### Live demo with steps to reproduce
   https://jsfiddle.net/gjyv0rLw/ 
Initially the day button gets highlighted,but from the subsequent click it stops highlighting.

#### Product version
Highstock 6.1.0

#### Affected browser(s)
Chrome,Firefox

**Comment by pawelfus** [comment]
Hi @coded9 

Thanks for reporting the issue. This is default behaviour, to release dataGrouping when user changes extremes. You can change this behaviour by setting [`rangeSelector.buttons[index].preserveDataGrouping`](https://api.highcharts.com/highstock/rangeSelector.buttons.preserveDataGrouping), see: https://jsfiddle.net/BlackLabel/vq7uwzb3/2/
