### ISSUE TITLE
flask string output begin with 0 not show in title text

### ISSUE THREAD

**Issue by 345161974** [highcharts/highcharts#11331]
I want to show text value {{ result_df['AccountID'][0] }}, in flask jinja template it show normally, but in highcharts title the string begin with 0 not show normally. I dont know how to show normally.

![hcharts1](https://user-images.githubusercontent.com/3973297/60725005-9401b380-9f6a-11e9-9c93-1501241f5d7e.png)
![hcharts2](https://user-images.githubusercontent.com/3973297/60725026-a1b73900-9f6a-11e9-98a1-b6e067b5db00.png)
![hcharts3](https://user-images.githubusercontent.com/3973297/60749273-0d7cbe80-9fca-11e9-863a-4bc2b252b601.png)

**Comment by sebastianbochan** [comment]
Hi @345161974,
Thank you for contacting us. The github is our bugtracker so for general [support](http://www.highcharts.com/support) questions, please use stackoverflow / forum or email.

**Comment by pawelfus** [comment]
Hi @345161974 

This is expected behaviour for flask. What you passed to the JS is **number**, while you need string. Convert `{{ result_df['AccountID'][0] }}` to string: `{{ result_df['AccountID'][0]|string }}`
