### ISSUE TITLE
Pie chart tooltip not displayed when hovering series

### ISSUE THREAD

**Issue by skyghis** [highcharts/highcharts#11336]
#### Expected behaviour

Tooltip should be displayed on all series like in version `7.0.3`.

#### Actual behaviour

Tooltip of first series is displayed once, then tooltip is never shown again for any series after hovering others series.

#### Live demo with steps to reproduce

Not working in version `7.1.2`: https://jsfiddle.net/37v4ehbk/

Working in version `7.0.3`: https://jsfiddle.net/g9utn8py/

#### Product version

Highcharts version 7.1.2

#### Affected browser(s)

Tested in Firefox 67.0.4 and Chromium 75.0.3770.90

**Comment by sebastianbochan** [comment]
Hi @skyghis,
Thank you for reporting about the issue.

**Internal note**
Bisect leads me to https://github.com/highcharts/highcharts/commit/a70f664303710b692f1494b9f353f25457fb3f1b

**Comment by skyghis** [comment]
F.Y.I., Issue is still present in version `7.1.3`: https://jsfiddle.net/y4kgd78o/

**Comment by skyghis** [comment]
F.Y.I., Issue is still present in version 7.2.0: https://jsfiddle.net/euvmq7n9

I can't figure a workaround, and this regression block my migration from 7.0 to future versions.
Any idea on how to workaround this issue ?

Thanks in advance

**Comment by KacperMadej** [comment]
@skyghis 
As a workaround, you could disable the chart's legend: https://jsfiddle.net/BlackLabel/w54o6xhe/

**Comment by skyghis** [comment]
Oh good catch @KacperMadej Thanks you !

**Comment by skyghis** [comment]
F.Y.I., Issue is still present in version 8.0.0: https://jsfiddle.net/f7dohqz6/

I have included, in comment, the workaround of @KacperMadej in the demo.
