### ISSUE TITLE
Exporting a big amount of points to CSV/XLS does not work.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#11340]
#### Actual behaviour
An attempt to export a large group of points to CSV or XLS does not succeed. When trying to export to CSV, the following error is thrown in a browser's console:
```
export-data.src.js:233 Uncaught Error: Failed to convert to blob
    at Highcharts.downloadURL (export-data.src.js:233)
    at a.Chart.Highcharts.Chart.downloadCSV (export-data.src.js:1071)
    at a.Chart.onclick (export-data.src.js:1213)
    at HTMLDivElement.onclick (exporting.src.js:1705)
```
In case of exporting to XLS, then the file is not complete, and does not include all data points.

#### Live demo with steps to reproduce
Official demo with `export-data.js` module, and decreased the amount of points.
Live example: https://jsfiddle.net/BlackLabel/9md4j0pb/
1. Export to CSV or XLS

**Comment by oysteinmoseng** [comment]
Internal note: This happens because the export data module is using data URIs instead of Blobs in most cases, and there is a length limit for data URIs. We should reuse code from the offline exporting module, which handles this better
