### ISSUE TITLE
pie chart color issue

### ISSUE THREAD

**Issue by vnanaware** [highcharts/highcharts#11345]
Hello,

         I want to set custom pie chart pie background color 
![img](https://user-images.githubusercontent.com/16416191/60875719-14b8fc00-a258-11e9-8c93-f525db594ee3.png)

 pie.data = [
                    [
                        "name": "Open",
                        "y": NSNumber(value: 56.33)//,
                       
                    ],
                    [
                        "name": "Close",
                        "y": NSNumber(value: 24.03)
                    ]
                ]

**Comment by pawelfus** [comment]
Hi @vnanaware 

You posted on our bug tracker. In case you have a question, please contact our support: https://www.highcharts.com/blog/support/

**Comment by vnanaware** [comment]
yes  I have problem to set color for pie chart, how to set color?

**Comment by sebastianbochan** [comment]
Hi @vnanaware,
The github is our bugtracker, so for general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.
