### ISSUE TITLE
Some stock-icons always served from CDN

### ISSUE THREAD

**Issue by spazmodius** [highcharts/highcharts#11344]
#### Expected behaviour
Setting the option `stockTools.gui.iconsURL`, should cause all icons to be served from my local server.

#### Actual behaviour
A few background-images in `popup.css` and `gui.css` are hardcoded to be served from `https://code.highcharts.com/7.1.2/gfx/stock-icons/`

#### Product version
Highstock 7.1.2

Perhaps these background images can use relative URLs?  Or be overlayed with JS instead of CSS `background`?

**Comment by sebastianbochan** [comment]
Hi @spazmodius,
Thank you for reporting about the bug. I agree that it is confusing, so will change it by the end of this week.
