### ISSUE TITLE
No scrolling options in timeline series

### ISSUE THREAD

**Issue by vikashrajgupta** [highcharts/highcharts#11358]
#### Expected behaviour
There should be a visible scrollbar after a fixed width for timeline series.

#### Actual behaviour
It tries to adjust all the data in the provided width

**Comment by KacperMadej** [comment]
Closing as implemented - https://jsfiddle.net/BlackLabel/3s02w6La/
Related API: https://api.highcharts.com/highcharts/chart.scrollablePlotArea
