### ISSUE TITLE
Stock-tools horizontal-line cursor / annotationOptions

### ISSUE THREAD

**Issue by 3Ue** [highcharts/highcharts#11366]
#### Expected behaviour
Cursor for horizontal line from stock-tools should be set by default to 'ns-resize' and for vertical line to 'ew-resize'.

Manually setting `navigation.bindings.horizontalLine.annotationOptions.draggable` to 'y' should work.

#### Actual behaviour
Cursor for horizontal- and vertical line from stock-tools are set by default to 'move'.

Manually setting `navigation.bindings.horizontalLine.annotationOptions.draggable` to 'y' does not work. Instead `navigation.bindings.infinityLine.annotationsOptions.draggable` is used also for horizontalLine (note the difference between the documented `annotationOptions` and the actual implementation `annotationsOptions`).

#### Live demo with steps to reproduce
https://jsfiddle.net/geshnqbv/

1. Add horizontal line over stock-tools
2. Hover mouse over the line

#### Product version
Highstock 7.1.2

#### Affected browser(s)
FF, probably all

**Comment by pawelfus** [comment]
Thanks for reporting the issue @3Ue 

It seems you found a few issues in one. Bug in docs (should be `annotationsOptions`), wrong type config merge (`horizontalLine` vs `infinityLine`) and lastly missing defaults for `draggable` vertical/horizontal lines.
