### ISSUE TITLE
TraverseUp button not hidden on export for Sunburst

### ISSUE THREAD

**Issue by marco-boeck** [highcharts/highcharts#11364]
#### Expected behaviour
When I export a Sunburst chart which displays the details of an inner ring, the "< Back" button should NOT be visible on the exported image. Just like when doing the same for a zoomed-in line series, the zoom out button is not visible.

#### Actual behaviour
The image contains the "< Back" button.

#### Live demo with steps to reproduce
https://jsfiddle.net/knachrtz/

1. Click on "Asia"
2. Export via hamburger as an image

#### Product version
HighCharts 7.1.2

#### Affected browser(s)
All browsers

**Comment by sebastianbochan** [comment]
Hi @marco-boeck,
Thank you for reporting about the bug.

**Workaround**
Use [exporting.chartOptions](https://api.highcharts.com/highcharts/exporting.chartOptions) and set position of the button.

Demo:
- https://jsfiddle.net/BlackLabel/o7aku8dq/
