### ISSUE TITLE
Problem displaying scatterplot tooltip on ipad

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#1136]
System: Safari on an iPad, Version 5.1 (9B176)
1. Open http://www.highcharts.com/demo/combo-regression
2. Try to show the tooltip for the scattered points

Result: It is very difficult to hit the points, even when turning off the regression line this is hard to do.
Expected: A better snap-to-point algorithm that works on touch devices.

**Comment by oysteinmoseng** [comment]
K-D tree tooltips have been implemented in Highcharts for a while now, closing this.
