### ISSUE TITLE
Blank screen in the browser. For some examples just the configuration bar.

### ISSUE THREAD

**Issue by TravelTrader** [highcharts/highcharts#11370]
I just downloaded the zip-file, unzipped and then wanted to run the examples on my server (apache2/ubuntu 18.04). But in my browser (Firefox) I only see a blank page, for some examples the configuration bar. It seems it changes sometimes. Very curious. Clicking the examples again with the bar, I do not see anything the next time.
I do not have any problems with other pages, codes or anything.

I downloaded the current version of Highstock with `wget https://code.highcharts.com/zips/Highstock-7.1.2.zip`.

Any ideas how I could solve this? I even don't know where I could start!?

Thank you.

**Update:**
The "Intraday ..."-examples are working but "Stock chart with GUI" for example does not work.

**Comment by pawelfus** [comment]
Hi @TravelTrader 

Thanks for reporting the issue. Demos in the package don't need server to be fine. Why do you need this? 

> Any ideas how I could solve this? I even don't know where I could start!?

I would check JS console for errors and apache logs for server errors.

**Comment by TravelTrader** [comment]
Thank you, @pawelfus, for the fast response.

> I would check JS console for errors and apache logs for server errors.

The apache logs are fine. But I did not know anything about a JS console. I remembered to just watch at the developer tools of my browser.
I saw a message of the `.json` file, downloaded it in the folder and ... now it works!

Therefore: Thanks a lot to lead me to the solution!
