### ISSUE TITLE
When hovering over bar charts, the tooltip is opaque

### ISSUE THREAD

**Issue by shrutisrivas** [highcharts/highcharts#11377]
#### Expected behaviour
When hovering over bar charts, the tooltip is no longer transparent.

#### Actual behaviour
When hovering over bar charts, if there are multiple bars hovering over one covers the other bar charts which was not the case earlier. It appears that several tooltip background are superimposed to increase the opacity.

#### Live demo with steps to reproduce

http://jsfiddle.net/btxavuLk/1/

#### Product version

7.1.2

#### Affected browser(s)
Firefox, Chrome

Version 7.1.2 - Several tooltip background images superimposed 
![Screen Shot 2019-07-11 at 2 36 49 PM](https://user-images.githubusercontent.com/26885350/61082450-7f546e00-a3f7-11e9-84d4-a59f0d226720.png)

Version 6.0.7 - Just one
![Screen Shot 2019-07-11 at 2 36 06 PM](https://user-images.githubusercontent.com/26885350/61082451-7f546e00-a3f7-11e9-9cfe-2925f0a5f155.png)

**Comment by sebastianbochan** [comment]
Hi @shrutisrivas,
Thank you for reporting about the problem.

**Internal note**
Apart of `.highcharts-tooltip-box` duplicate, the shadow is also duplicated multiple time.

<img width="728" alt="Zrzut ekranu 2019-07-12 o 08 22 15" src="https://user-images.githubusercontent.com/2115686/61106692-2f6cba00-a47e-11e9-97d6-56bd3b79438c.png">
