### ISSUE TITLE
Range selector week button disabled 

### ISSUE THREAD

**Issue by coded9** [highcharts/highcharts#11372]
#### Expected behaviour
Week button should get enabled and show the dataGrouping for data in the 2 weeks(Dec 29-Jan 4 and Jan5 -12)

#### Actual behaviour
Week button is disabled 

#### Live demo with steps to reproduce
https://jsfiddle.net/n9h1L857/

#### Product version
Highstock 6.1.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @coded9 

This is expected behaviour. RangeSelector button is enabled only when available data meets required by button range. In your case, you have range 02 Jan - 09 Jan, so it's only a week of data, but button requires 2 weeks. If you want to enable this button enable [`rangeSelector.allButtonsEnabled`](https://api.highcharts.com/highstock/rangeSelector.allButtonsEnabled). Demo: https://jsfiddle.net/BlackLabel/0xy6heof/1/

**Comment by coded9** [comment]
Hi Pawelfus,
I'm not still clear on this 
For Ex: In my given example , I have data between Dec 29 - Jan 4 and Jan 5 - Jan 12 which is two weeks.
If I specify count as 2 for week , should  I have atleast 14 data points within any date range or data within 2 weeks date range ? Could you please explain ?

**Comment by coded9** [comment]
Also ,can you please explain why week button is showing data for the next week for which dataset doesn't contain any data points in the below fiddle ? 
https://jsfiddle.net/jgcb96Lx/

**Comment by pawelfus** [comment]
Hi @coded9 

Sure, let me explain:
> For Ex: In my given example , I have data between Dec 29 - Jan 4 and Jan 5 - Jan 12 which is two weeks.

You have data **between** two weeks, while data should be **at least** two weeks. One week = 7 days. In your demo you have dataset:
```
var data = [
  [1230876000000, 144.09],
  [1230962400000, 142.73],
  [1231048800000, 144.18],
  [1231135200000, 144.18],
  [1231221600000, 145.53],
  [1231308000000, 145.74],
  [1231394400000, 147.77],
  [1231480800000, 147.77]
]
```

Where first point is `Fri Jan 02 2009 07:00:00 GMT+0100 (Central European Standard Time)` and last `Fri Jan 09 2009 07:00:00 GMT+0100 (Central European Standard Time)` which is range 02.01.2009 - 09.01.2009 -> 7days -> **1 week**.

Given when buttons are enabled (docs):
> By default buttons are only enabled if the **corresponding time range exists** on the X axis

Your `week` button does not meet requirements - you required 2weeks = 14days, but your dataset provides only range of 7 days.

Regarding this: 
> If I specify count as 2 for week , should I have atleast 14 data points within any date range or data within 2 weeks date range ?

The first one is closer to the truth, but not exactly - you don't need 14points (number of points) does not matter), but points that range between first and last one is at least 2 weeks.

If you have more questions, or something is not clear, please contact our support: https://www.highcharts.com/blog/support/
