### ISSUE TITLE
Dependency wheel styles are missing from the styled mode version

### ISSUE THREAD

**Issue by amyspark** [highcharts/highcharts#11389]
#### Expected behaviour

Using dependency wheel with styled mode on an off results in exactly the same behaviour on hover.

#### Actual behaviour

If styled mode is enabled, the chords are not dimmed and are rendered on top of each other at the same opacity. Upon opening the Dev Tools, and hovering on each of them, we can see that the classes `highcharts-point-hover` and `highcharts-point-inactive` are applied, but to no effect.

Since I use other charts with styled mode enabled in the same page, disabling it for just the wheel results in broken behaviour.

#### Live demo with steps to reproduce
These codepens demo the issue: [styled mode off](https://codepen.io/anon/pen/WqWYOZ), [styled mode on](https://codepen.io/anon/pen/jjRQzz), and [styled mode off but with the css loaded](https://codepen.io/anon/pen/JQVeZP).

In the codepen for the styled mode, I added four CSS classes to demo a possible fix.

#### Product version

Highcharts 7.1.2

#### Affected browser(s)

Tested in Firefox 70.0a1 and Vivaldi 2.6.1566.44 (Chrome/75.0.3770.102).

**Comment by pawelfus** [comment]
Thanks for reporting the issue @amyspark
