### ISSUE TITLE
CSS filter does not affect on exported chart in styled mode

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#11386]
#### Expected behaviour
Exported chart should have applied all filters defined through CSS selector.

#### Actual behaviour
When some element have the `filter: url(#filter_id)` applied through CSS selector, then does not affect on exported chart, namely there is no any filters noticeable on exported file.

#### Live demo with steps to reproduce
Live example: http://jsfiddle.net/BlackLabel/gybkhdz8/
1. Filter is applied on the yAxis labels
2. After exporting the chart to any format, that filter is not noticeable at all.

#### Product version
All versions

**_Internal Note:_**
_Most probably it's caused by the following `replace()` call. When the `style=""` declaration have not space between css attributes, then regular expression does not work properly:
https://github.com/highcharts/highcharts/blob/91df181bb32a3d8235d9e83ea527893d55d9df17/js/modules/exporting.src.js#L1061_

_That regex does not classify every `url()` as a new matched result, but the expression which starts with first `&quot;` or `"` and ends on the same string of characters, what can be seen noticed on the below example:_
https://regexr.com/4hbsi

_It should be replaced by:_ 
```regex
/url\(("|&quot;)(.*?)("|&quot;)\;?\)/g
```

**Live example with fix applied:** http://jsfiddle.net/BlackLabel/4g5ty1or/

**Comment by ChronoSIDA** [comment]
Hello Danieal, somehow i still couldn't fix the problem with the workaround that you provided. Here is a JsFiddle link to it: http://jsfiddle.net/8gjsezky/5/

Would you please take a look where i missed when you get free?

**Comment by pawelfus** [comment]
Hi @ChronoSIDA 

In your case there's additional issue, you apply CSS with ID in path: `#id .class-name`. When chart is being exported, a copy of a chart is created, so path does not match (only one ID per page can be used). Instead of referencing charts via ID, use custom [`chart.className`](https://api.highcharts.com/highstock/chart.className): http://jsfiddle.net/BlackLabel/g8oq4eh5/

**Comment by ChronoSIDA** [comment]
Hello @pawelfus 

The problem is solved! Thank you for the help!

My best,
Sida
