### ISSUE TITLE
Chart options missing in API documentation 

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#1139]
**Axis.showEmpty** is not documented in http://www.highcharts.com/ref (see also http://highcharts.uservoice.com/forums/55896-general/suggestions/1813731-hiding-of-y-axis)

**Comment by vickychijwani** [comment]
Hi, there are 2 open documentation-related issues that probably belong here: #4228 and #4478. If this thread is re-opened those other issues can be closed so all docs changes can be tracked centrally. There also are a few other issues labelled "Docs" that may belong here as well: https://github.com/highslide-software/highcharts.com/labels/Docs. Also a note could be added to the README directing users to point out documentation-related issues by commenting on this thread :)
