### ISSUE TITLE
Word Cloud keyboard access broken - accessibility

### ISSUE THREAD

**Issue by tipantaz** [highcharts/highcharts#11397]
Hi to all! 
Working with Microsoft and came across this error.
Any help will be greatly appreciated!
Thanks!

#### Expected behavior
When navigating in the word cloud with the keyboard and use arrows up and down to select and focus on words, the words are selected with an outline around them.

#### Actual behavior
There is a non-moving outline in the center instead of around each word.

#### Live demo with steps to reproduce
https://jsfiddle.net/b3enhvw5/

Select the word cloud and try moving around word with the arrows.

#### Product version
    highcharts: 7.1.1

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting the issue @tipantaz 

@oysteinmoseng FYI

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng Any thoughts?

**Comment by oysteinmoseng** [comment]
This should be a good introductory issue for new devs.

The size of the focus border is correct, but the focus border logic in `focusBorder.ts` that applies the focus border to an element does not take the following things into account:

- Text alignment (text-anchor & alignment-baseline)
- x & y offsets for the text

The focus border logic gets the position and size of the element using `SVGElement.getBBox`. It might be expected that this was handled there, or that we introduce a new function for getting the dimensions of text elements (I assume this is logic that is also needed for e.g. data labels?).

If this is not shared logic, we can add a new function in `focusBorder.ts` that deals specifically with getting the position and size of text elements. The `addFocusBorder` function should then call this function for text elements to modify the bounding box accordingly. It is probably necessary to run this logic on text elements only, as we have to make sure that adding x/y offsets does not fail for other SVG element types. I believe `getBBox` already takes the x/y props into account for `rect` elements, for example - although I could be wrong here.
