### ISSUE TITLE
highcharts : pie cannot set animation axis

### ISSUE THREAD

**Issue by lvshaoping** [highcharts/highcharts#11390]
#### Expected behaviour
i want the pie start with the animation from R,not the point of pie center

#### Actual behaviour
i can not change the animation

#### Live demo with steps to reproduce

this is the Expected behaviour   https://jshare.com.cn/temp/VZZWWo
but the real is https://jshare.com.cn/temp/BB4WW7 
can you help me

#### Product version

 Highcharts JS v6.1.3

**Comment by lvshaoping** [comment]
i find that you do this on( i forkede from your demo ) http://jsfiddle.net/bulingTang/r4826zgo/
but i used  demo cannot use Highcharts.chart
the demo is use Highcharts.Renderer   
is there (Highcharts.chart) has attribute to let the animation like your demo 
thank you very much

**Comment by pawelfus** [comment]
Hi @lvshaoping 

You posted on our bug tracker, if you have a question, please use other support channels: https://www.highcharts.com/blog/support/

PS: To answer your question, please check this snippet on our blog: https://www.highcharts.com/blog/snippets/customize-your-pie-charts-animation/ - you can modify any part of animation you want to with some customization: https://jsfiddle.net/BlackLabel/Lvboe6hn/ (heads up: don't forget you always can change `easing` in animation: https://api.highcharts.com/highstock/plotOptions.series.animation).
