### ISSUE TITLE
The plotline on y axis is not visible when value is given 0 to 0.99

### ISSUE THREAD

**Issue by tushar-chandra-030389** [highcharts/highcharts#11405]
#### Expected behaviour
The plot line on y - axis is rendered outside the view port when the series data is positive [0, 0.3, 0.5, 1, 2] and the plotline value is 0 to 0.99.

#### Actual behaviour
Please refer the negative data [0, -0.3, -0.5, -1, -2], the plot line is visible for value 0.

#### Live demo with steps to reproduce
https://jsfiddle.net/tushar_chandra_030389/ov71mzrg/6/

#### Product version
 Highcharts JS v7.1.2 (2019-06-03)

#### Affected browser(s)
Chrome, rest as well.

![image](https://user-images.githubusercontent.com/5112100/61281385-2e69be80-a7d7-11e9-8a07-b81c3c807d15.png)

**Comment by pawelfus** [comment]
HI @tushar-chandra-030389 

Thanks for reporting the issue, but I'm afraid it's not a bug, but a simple mistake, consider these parts:

```js
var seriesDataPositive = [0, 0.3, 0.5, 1, 2];
```

And:
```js
    plotLines: [
      {
        dashStyle: 'ShortDot',
        value: seriesDataPositive[0.99],
        color: '#FF0000',
        width: 1
      },
    ],
```
In short:
Value: `seriesDataPositive[0.99]` is undefined (there's no 0.99 index in `seriesDataPositive` array). Maybe you simple want to show plotLine at `0.99`? Then it should be: `value: 0.99`, demo: https://jsfiddle.net/BlackLabel/5t290njq/

**Comment by tushar-chandra-030389** [comment]
Sorry that as a typo at my end.

What I wanted to show was, if the value at the index is `0`, then the plot-line is not rendered in viewport.
https://jsfiddle.net/tushar_chandra_030389/ov71mzrg/10/
![image](https://user-images.githubusercontent.com/5112100/61293120-98429200-a7f0-11e9-858f-3ca7a9bf5248.png)

**Comment by pawelfus** [comment]
Ah, thanks! 

Simplified demo: https://jsfiddle.net/BlackLabel/o513nw6m/3/ - it's caused by crisping logic for paths - we translate these paths by 0.5px for odd widths (1px, 3px etc) always to the bottom so path is sharp, not blurred. You can observe how this would work without this crisping logic: https://jsfiddle.net/BlackLabel/t7fg80so/ (I recommend to check this in Chrome).

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/abpghq4e/

**Heads up:** 
Don't forget to set `plotLine.zIndex` to render plotLine on top of the gridLine!

**Snippet:**
```js
(function(H) {
  H.wrap(H.Axis.prototype, 'getPlotLinePath', function(proceed, options) {
    var path = path,
      lineWidth = options.lineWidth;

    // Modify temporary width:
    if (!this.horiz && H.defined(options.value) && options.value === this.min) {
      options.lineWidth = H.defined(options.lineWidth) ? options.lineWidth * -1 : -1;
    }

    path = proceed.call(this, options);

    // Restore width
    options.lineWidth = lineWidth;

    return path
  });
})(Highcharts);

```
