### ISSUE TITLE
any possible to add success callback for exportChartLocal()

### ISSUE THREAD

**Issue by crapthings** [highcharts/highcharts#11403]
i want to use puppeteer headless to render chart as image.

but i don't know if image was saved.

```js
  await page.evaluate(async ({ body, rid }) => {
    const chart = Highcharts.chart('container', body)
    chart.exportChartLocal({
      filename: rid,
    })
  }, {
    body,
    rid,
  })
```

so i've to check if file exist inside a looping

```js
const downloadUrl = await new Promise(async resolve => {
    const filename = rid + '.png'
    const filepath = path.resolve(__dirname, 'public', filename)
    const timerId = setInterval(async function () {
      if (!fs.existsSync(filepath)) return
      await page.close()
      await browser.disconnect()
      clearInterval(timerId)
      resolve('/' + filename)
    }, 10)
  })
```

i've read that there is an 'error' callback, but any possible adding a success cb?

**Comment by pawelfus** [comment]
Hi @crapthings 

Thanks for your idea. Is there any particular reason to use offline-exporting & `exportChartLocal` instead of exporting & [`chart.getSVG()`](https://api.highcharts.com/class-reference/Highcharts.Chart#getSVG) ? `getSVG()` returns string (SVG) which you can process as you wish (e.g. save in the filesystem).

**Comment by crapthings** [comment]
i want to change format, by passing exportOptions

chart.exportChartLocal({
        filename: rid,
        type,
        ...exportOptions
      })

i think by using the highcharts builtin feature can save some code. :)

**Comment by pawelfus** [comment]
Thanks for the details! Well, exporting-offline was designed to work with.. browsers. So no need for success callback - file is simply downlaoded :) Anyway, thank for the idea!

FYI @oysteinmoseng

**Comment by davidrochin** [comment]
Any workaround for this? I'm trying to intercept the call from Java. Before, I could do it by replacing `Highcharts.downloadUrl` but after updating Highcharts that's no longer working.

**Comment by oysteinmoseng** [comment]
Hi @davidrochin 

Overriding `Highcharts.downloadURL` is no longer supported, unfortunately. Is your use case also to determine the success of the call, or do you have a different use case? We are considering adding a success event that fires when a chart has been exported - would this be a sufficient solution?

**Comment by davidrochin** [comment]
> Hi @davidrochin
> 
> Overriding `Highcharts.downloadURL` is no longer supported, unfortunately. Is your use case also to determine the success of the call, or do you have a different use case? We are considering adding a success event that fires when a chart has been exported - would this be a sufficient solution?

Yes, that would be very useful.

**Comment by jasonclg** [comment]
Hi @oysteinmoseng 
Is there a reason why Highcharts.downloadURL was removed from namespace in 8.2.0?
We have use case to override that method.

> Hi @davidrochin
> 
> Overriding `Highcharts.downloadURL` is no longer supported, unfortunately. Is your use case also to determine the success of the call, or do you have a different use case? We are considering adding a success event that fires when a chart has been exported - would this be a sufficient solution?

**Comment by oysteinmoseng** [comment]
@jasonclg It has not been removed from the namespace, and can still be accessed with `Highcharts.downloadURL`, but we have moved to using a modern ES6 pattern internally that unfortunately prohibits overriding these types of utility functions. What is your use case? Are there alternative solutions that we could consider from our side?
