### ISSUE TITLE
Highcharts polar not rendering when in series

### ISSUE THREAD

**Issue by FilipeamTeixeira** [highcharts/highcharts#11407]
#### Expected behaviour
In the JSFiddle below, I'm trying to have two polar charts in one container.
However, it seems that for some reason, it never takes the polar argument and it shows instead a bar chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/cf9jexgv/1/

#### Affected browser(s)

**Comment by pawelfus** [comment]
Hi @FilipeamTeixeira 

Thanks for reporting the issue, but you simply didn't load `highcharts-more` module, please load it: `https://code.highcharts.com/highcharts-more.js`

**Comment by FilipeamTeixeira** [comment]
Unfortunately when using the polar tag something goes visibly wrong https://jsfiddle.net/6tjh5re1/.

**Comment by pawelfus** [comment]
Configuration is wrong - check how to define multiple panes in the chart here: https://www.highcharts.com/demo/gauge-vu-meter

If you have any other questions, please contact our support: https://www.highcharts.com/blog/support/
