### ISSUE TITLE
Highres Miller Maps wrong info Netherlands (both label position and center on click)

### ISSUE THREAD

**Issue by ssuess** [highcharts/highcharts#11413]
#### Expected behaviour
Label for Netherlands should be centered over country. When clicking on country (using zoomTo()), map should zoom and center on that country (NL).

#### Actual behaviour
Label for Netherlands is in North Africa. When clicking on country (using zoomTo()), map  center is mid-atlantic.

This happens with world-highres2 and world-highres3 maps

**Comment by sebastianbochan** [comment]
Hi @ssuess,
Thank you for reporting about the problem.

FYI @KacperMadej

**Comment by ssuess** [comment]
This does not seem to be fixed yet, and I missing something?

**Comment by PaulDalek** [comment]
Hi @ssuess

Could you please provide us with a minified example where this behavior occurs? Thanks.

**Comment by KacperMadej** [comment]
The placement could be better.
As a workaround, it is possible to adjust the label position: https://jsfiddle.net/BlackLabel/eaf64zsr/

The issue belongs to the map collection repository. Moving to --> https://github.com/highcharts/map-collection-dist/issues/81
