### ISSUE TITLE
Facing issue while rendering highchart in jsdom

### ISSUE THREAD

**Issue by partha0103** [highcharts/highcharts#11412]
Getting 
> Highcharts error #18: www.highcharts.com/errors/18
while trying to run test cases in my react component using jsdom

`const highchart = Highcharts.chart(`lineChart-${this.id}`, highchartConfig);`

The config passed here is according to doc as it's rendering perfectly in browser

Version- 6.2.0

**Comment by sebastianbochan** [comment]
Hi @partha0103,
Github is our bug tracker so sor general [support](http://www.highcharts.com/support) questions please use stackoverflow / forum or email.

ps. The error is caused by reference to non-existed yAxis.
