### ISSUE TITLE
highcharts networkgraph loading a large number of data pages is very slow

### ISSUE THREAD

**Issue by wangdi244** [highcharts/highcharts#11428]
Hello, I found in the process of using large amount of data after page loading is very slow, searise nodes > 500, data > 900, how can I optimize the page, can speed up the page loading speed, please advise.

**Comment by wangdi244** [comment]
Thank you for your reply.I checked your Demo.My code was modified on the basis of demo.I paste the code for your advice.
It takes 22 seconds for my code to access (data to be loaded locally) pages.
It takes 1.6 minutes for the subordinates to visit the pages in the production environment, but the loading of cross-segment access pages is very slow and can not be opened.

This is my code:
<script>
             step1:Getting graphical data from the back end

             var host_color = {};
             var application_module_color = {};
             var check_db = new String("");
             var db_app = {};
             var app = {};
             if ('{{ db_name }}' != '' || '{{ db_name }}' != 'all') {
                var url = "/screen" + '?db_name=' + '{{ db_name }}'
             }else{
                var url = "/screen"
             }
                $.ajax({
                    async:false,
                    type:"POST",
                    url:url,
                    data:{'host_color':"get_host_color"},
                    success : function(data) {
                        if (data[0].status == 'ok')
                            for(var key in data[2]) {
                                host_color[key] = data[2][key]
                            };
                            for(var key1 in data[3]){
                                application_module_color[key1] = data[3][key1]
                            };
                            for(var key2 in data[4]){
                                db_app[key2] = data[4][key2]
                            };
                            for(var key3 in data[5]){
                                app[key3] = data[5][key3]
                            }
                            check_db = data[1].db_name
                    }
                })

           step2:Give node color and size

            Highcharts.addEvent(
                Highcharts.seriesTypes.networkgraph,
                'afterSetOptions',
                function (e) {
                    var colors = Highcharts.getOptions().colors,
                        i = 0,
                        nodes = {};
                    e.options.data.forEach(function (link) {
                        if (db_app.hasOwnProperty(link[0])) {
                            nodes[link[0]] = {
                                id: link[0],
                                marker: {
                                    radius: 57
                                },
                                {% if db_name == '' or db_name == 'all' %}
                                    color: db_app[link[0]],
                                {% endif %}
                            };
                            if ( check_db !== 'all') {
                                if (app.hasOwnProperty(link[1])) {
                                  nodes[link[1]] = {
                                        id: link[1],
                                        marker: {
                                            radius: 20
                                        },
                                        color: app[link[1]],
                                    };
                                };
                            }else {
                                nodes[link[1]] = {
                                        id: link[1],
                                        marker: {
                                            radius: 7
                                        },
                                        color: host_color[link[1]]
                                };
                            }
                        } else if (nodes[link[0]] && nodes[link[0]].color) {
                            if ( check_db === 'all') {
                                nodes[link[1]] = {
                                    id: link[1],
                                    marker: {
                                        radius: 10
                                    },
                                    color: host_color[link[1]]
                                };
                            }else{
                                nodes[link[1]] = {
                                    id: link[1],
                                    marker: {
                                        radius: 10
                                    },
                                    color: nodes[link[0]].color
                                };
                            }
                        }
                    });
                    e.options.nodes = Object.keys(nodes).map(function (id) {
                        return nodes[id];
                    });
                }
            );

           step3:Loading data and drawing graphics. The jinja2 template framework is applied in the second part.

           Highcharts.chart('container', {
                chart: {
                    type: 'networkgraph',
                    height:800,
                    width:1600,
                    backgroundColor: 'rgba(0,0,0,0)'
                },
                title: {
                    useHTML:true,
                    text: "<div> <a>数据库关联关系" + {% if db_name != 'all' %}'('+'{{ db_name }}'+'库'+')'{% else %}'全景图'{% endif %}+"</a></div>",
                    style: {
                        color: 'white',
                        fontSize: '30px',
                    },

                },
                plotOptions: {
                    networkgraph: {
                        keys: ['from', 'to'],
                        layoutAlgorithm: {
                            enableSimulation: false,
                            friction: -1.0,
                            integration: 'verlet',
                            linkLength: 135,
                            initialPositions: 'circle',
                            approximation:'O(N^2)',
                            theta:1.0
                        }
                    }
                },
                credits: {
                    enabled: false
                },
                lang: {
                    downloadCSV: '下载CSV文件',
                    downloadXLS: '下载XLS文件',
                },
                series: [{
                    marker: {
                      radius: 13
                    },
                    dataLabels: {
                      enabled: true,
                      linkFormat: '',
                    },
                    data: {{ data|tojson }},
                }]
            })

**Comment by wangdi244** [comment]
We look forward to your reply

**Comment by sebastianbochan** [comment]
Hi @wangdi244,
Unfortunately we do not have an access to your back-end so as a result we are not able to reproduce your issue. One of the reasons on slow working demo can be also long-time of ajax request.

Please update my previous demo with your hardcoded data for the further debugging.

**Comment by wangdi244** [comment]
Hello, I'm sorry that it took so long to reply to your letter. I wrote the data directly into HTML and visited this page directly. The response time has not changed. I think we can eliminate the network factor. Is there any requirement for this and the configuration of the visiting client, for example, the client with high configuration will access faster?

**Comment by pawelfus** [comment]
Hi @wangdi244 

In general, when rendering a lot of nodes/points in the networkgraph, we recommend enabling simulation, see [networkgraph.layoutAlgorithm.enableSimulation](https://api.highcharts.com/highcharts/series.networkgraph.layoutAlgorithm.enableSimulation) option. This way, user can see how nodes are translated to the final destinations, without waiting for the final result.

Additionally, depending on your dataset, you may consider tinkering other `layoutAlgorithm` options, for example [`maxSpeed`](https://api.highcharts.com/highcharts/series.networkgraph.layoutAlgorithm.maxSpeed), [`maxIterations`](https://api.highcharts.com/highcharts/series.networkgraph.layoutAlgorithm.maxIterations) and [`friction`](https://api.highcharts.com/highcharts/series.networkgraph.layoutAlgorithm.friction).

**Comment by wangdi244** [comment]
Thank you very much for your reply. When I turn on the enableSimulation option, the graphics will appear very soon. But the problem is that there are many data points. I want to see which points are related to one another. Because the graphics are always moving, how to satisfy the fast speed of drawing and try not to let the dots in the graphics move as much as possible?

**Comment by pawelfus** [comment]
@wangdi244 - this is general speed/precision trade-off in networkgraph algorithms: for example you can decrease `maxIterations` (e.g. set to 100), so graph will end simulation much faster, but may not look as good as with defaults. You can also increase `maxSpeed` so nodes will move faster especially in the initial steps or increase/decrease `friction` - note that too small friction may cause oscillations in the graph (e.g. disabled friction in Euler integration: https://jsfiddle.net/BlackLabel/5873jtpn/1/ ).

**Comment by wangdi244** [comment]
Hello, I have another question. When I open the enableSimulation parameter, another graph with more points loads data faster. The page turns white after a few seconds of moving the points on the graph. There is no point on the graph. How can I adjust it?

**Comment by pawelfus** [comment]
Hi @wangdi244 

Hard to say without checking a live example. Could you please contact our support? See: https://www.highcharts.com/blog/support/ - thanks!

**Comment by wangdi244** [comment]
Thank you very much for your guidance. At present, graphics appear faster, but some points overlap with each other. How to adjust the spacing between points? How can I put more data points in a more beautiful picture, please advise, thank you.

**Comment by wangdi244** [comment]
[](url)

**Comment by pawelfus** [comment]
Hi @wangdi244 

Please check all options under [`layoutAlgorithm`](https://api.highcharts.com/highcharts/series.networkgraph.layoutAlgorithm) - for example `linkLength`. You can use different integrations: Verlet or Euler - both produce different chart's layout. You can also achieve different results byt tinkering other options. For example you can modify forces and achieve completely different graph. If you have more questions, please contact our support - this is our bug tracker. Thanks! :)
