### ISSUE TITLE
Highcharts Gantt RTL does not change Completed fill direction

### ISSUE THREAD

**Issue by gazu36** [highcharts/highcharts#11425]
#### Expected behaviour

When I set xAxis: { reversed: true } AND yAxis: { opposite: true }, the expected behavior is that that inner task progress bar will change direction to RTL as well.

#### Actual behaviour

Everything changes but the progress bar remains LTR.

#### Live demo with steps to reproduce
https://jsfiddle.net/mw5xcqp8/

#### Product version
Highcharts v7.1.2

#### Affected browser(s)
Tested in Chrome

**Comment by sebastianbochan** [comment]
Hi @gazu36,
Thank you for reporting about the problem. I agree that the internal task should be also flipped.

FYI @jon-a-nygaard

**Comment by gazu36** [comment]
@sebastianbochan Ty for the swift reply

We have thought about the same workaround but were afraid it would cause us maintenance problems, which is why this issue was opened and we decided to wait for the fix. Thanks again!

**Comment by gazu36** [comment]
@sebastianbochan Any estimation when the fix will be published? :)

**Comment by pawelfus** [comment]
Hi @gazu36 

It seems that v7.1.3 resolves the issue, your demo looks fine: https://jsfiddle.net/mw5xcqp8/ (released a few days ago).

Could you confirm? Thanks!

**Comment by gazu36** [comment]
Hey @pawelfus 

Yes, I can confirm this resolves the issue, thanks.

Also double checked with the fiddle by @sebastianbochan - the previous fix now works as the bugged behavior.
