### ISSUE TITLE
Highcharts Stalling while rendering line charts in 6.0.0

### ISSUE THREAD

**Issue by jak-ecoaxis** [highcharts/highcharts#11429]
#### Actual behaviour
I have seen demo of several thousands of data points rendered smoothly. Not sure why this is not loading smoothly.  

In Highcharts 6.0.0, while rendering this chart with about 1000 data points.  It stalls/pauses for some time - tooltip on mouse over comes up after a long pause.  It deteriorates further with more data.

In Highcharts 6.2.0, the problem was slightly different - it stalls/pauses while rendering but after graph is rendered the tooltip loads instantly.

#### Expected behaviour
It should render the graph with tooltip so that when the user moves the mouse over the graph it should show the tooltip value instantly.

#### Live demo with steps to reproduce
6.0.0
http://jsfiddle.net/u61dmqrp/

6.2.0
http://jsfiddle.net/m2ak3s6h/

#### Product version
https://cdnjs.cloudflare.com/ajax/libs/highcharts/6.0.0/highstock.js

#### Affected browser(s)
Chrome latest

**Comment by sebastianbochan** [comment]
Hi @jak-ecoaxis,
Thank you for reporting about the issue. The bug has been already fixed in the 7.0.0 version. I recommend you to update your libraries to the newest versions.  

Demo:
- http://jsfiddle.net/BlackLabel/ns17gdvq/

**Comment by jak-ecoaxis** [comment]
Thanks Sebastian for the quick revert.

Is the back ported patch on 6.x branch? There are multiple graphs that is breaking in 7.x and we can't upgrade easily.

**Comment by pawelfus** [comment]
Hi @jak-ecoaxis 

Did you follow "Upgrade notes" when upgrading from v6.x to v7.0? See: https://www.highcharts.com/blog/changelog/

If you find any other issues during upgrade to v7.x please contact our support. We never intended to break backward compatibility. We don't have plans to release another v6 version.
