### ISSUE TITLE
On highcharts gantt with a certain date range both rows of x-Axis show the same data

### ISSUE THREAD

**Issue by danielroach** [highcharts/highcharts#11427]
#### Expected behaviour
The lower row of the xAxis range should show more specific data ie months or quarters, if the top row shows years.

#### Actual behaviour
Both xAxis rows show years.

#### Live demo with steps to reproduce
https://codepen.io/anon/pen/EqYqwd

The window width needs to be quite wide for it to happen with the data example i provided.

In my case 1918px wide 

#### Product version
Highcharts Gantt JS v7.1.2

#### Affected browser(s)
Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)

![Screen Shot 2019-07-18 at 10 12 00 am](https://user-images.githubusercontent.com/6583635/61420124-8114b900-a944-11e9-9483-dce5d4edf26f.png)

**Comment by sebastianbochan** [comment]
Hi @FilipeCosta06,
Thank you for reporting about the problem.

FYI @jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
Thanks again for reporting,

I agree, the behavior here seems odd, and that this could be enhanced by having one of the axes show either a range of years, or quarters.

There is [logic in GridAxis that handles this](https://github.com/highcharts/highcharts/blob/91df181bb32a3d8235d9e83ea527893d55d9df17/js/parts-gantt/GridAxis.js#L599), but it does not seem to account for range of years.

**Comment by jbeaslas** [comment]
We have the same issue and it is very problematic for us.

See the following example:
https://jsfiddle.net/jbeaslas/2v5nf6hr/1/

**Comment by danielroach** [comment]
Hi @jon-a-nygaard just checking if there was any update on this one please?

Regards,
Daniel

**Comment by rnickerson** [comment]
What is the status with the Highcharts response? This is 2 months old now affecting customer satisfaction?

**Comment by jon-a-nygaard** [comment]
Hi @danielroach, this issue has unfortunately not been picked up by a developer yet. I will make sure we  get this prioritized and start working on a solution for it ASAP.

**Comment by pawelfus** [comment]
**Workaround:**
This can be actually an official solution, not only a workaround: remove years from available [`xAxis.units`](https://api.highcharts.com/gantt/xAxis.units).

Demo: https://jsfiddle.net/BlackLabel/w8hymv01/

Config:
```js
  xAxis: [{
    units: [
      [
        'millisecond',
        [1, 10, 100]
      ],
      [
        'second',
        [1, 10]
      ],
      [
        'minute',
        [1, 5, 15]
      ],
      [
        'hour',
        [1, 6]
      ],
      [
        'day',
        [1]
      ],
      [
        'week',
        [1]
      ],
      [
        'month',
        [1]
      ]
    ]
  }, {}],
```
