### ISSUE TITLE
Polar xAxis labels cut

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#11423]
#### Actual behaviour
When the chart's width is low, the labels are cut by the chart's container.

![labelsCut](https://user-images.githubusercontent.com/23310742/61381706-c20cbf00-a8ab-11e9-877e-a357cbb3e010.PNG)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/bzrL36p8

Decrease window width to ~350 or less

#### Product version
Highcharts 7.1.2

#### Affected browser(s)
All

Seems like fix from this ticket #7248 isn't working anymore.

**Comment by raf18seb** [comment]
#7248

**Comment by sebastianbochan** [comment]
**Workaround**
You can set the [responsive rules](https://api.highcharts.com/highcharts/responsive) and define how `dataLabels` should behave.

**Comment by vsssunder** [comment]
Hope this is issue is being under work in progress, expect it to be sorted out with a proper fix.
Resize of the chart should happen considering the entire width of the chart including the labels.

**Comment by oysteinmoseng** [comment]
@vsssunder We are looking into the issue, and will update here as soon as we have more info

**Comment by oysteinmoseng** [comment]
Internal note: Does not seem to be a regression. The fix for #7248 in `v6.0.4` did make things slightly better, but it looks like this has always been broken.

**Comment by oysteinmoseng** [comment]
Internal note: Seems axis label offset is deliberately ignored for radial axes. Removing the forced 0 offsets has some effect, but labels are still cut, and centering seems to be off: https://jsfiddle.net/3q94g07x/
