### ISSUE TITLE
Positioning errors on variwide charts with many small values

### ISSUE THREAD

**Issue by stuffisthings** [highcharts/highcharts#11424]
This issue relates to variwide charts with many very small values. Highcharts seems to round the widths of the segments up or down either 0 or 1 pixels, but the x position of the following segments appears to be based on the actual sum of the preceding values, not their rounded pixel values. When there are lots of small values, this can result in segments being seriously out of position/overlapping. This seems to only affect segments with negative Y values.

I am not sure if this is related to #9304.

#### Expected behaviour

Variwide columns should be properly positioned regardless of their values. Here is our chart with about 3800 data points rendering more or less correctly:

![methane working](https://user-images.githubusercontent.com/6656179/61385657-15ced680-a8b3-11e9-9429-6230e638eb06.PNG)

I've solved the problem by filtering out values whose width would be below 1 pixel, though you can still see some small overlaps. This approach is not ideal as it depends on knowing the width of the plot area in pixels.

#### Actual behaviour

Without the filtering, the chart renders like this:

![methane bug](https://user-images.githubusercontent.com/6656179/61385672-1f583e80-a8b3-11e9-9782-5786a259714d.PNG)

#### Live demo with steps to reproduce
It's hard to reproduce with a contrived dataset, however I've uploaded a version of the production app showing the error [here](https://www.iea.org/media/vue-components/methane-bug/).

#### Product version
Highcharts 7.1.2

#### Affected browser(s)
Chrome and Edge, at least

**Comment by sebastianbochan** [comment]
Hi @stuffisthings,
Thank you for reporting about the bug. I was able to reproduce it and indeed the shape is incorrect.

MacOSX: 10.14.5
Chrome: 75.0.3770.142

As I see the application is in VUE, so please let me know if you use our Vue official wrapper.
Could you also update the demo (in native JS not Vue) https://jsfiddle.net/BlackLabel/48tsmf0z/ with your data / chart Options. It will allow us to detect if its bug in Vue or Highcharts.

**Comment by stuffisthings** [comment]
Hi @sebastianbochan 

Yes, it's using the official wrapper.

There are several layers of components, but Highcharts is externalized so the Highcharts object can be accessed from the console. I extracted the final options from `Highcharts.charts[0].userOptions` via JSON.stringify and copied into the fiddle: https://jsfiddle.net/0kgstch7/

It does reproduce the problem -- the only things I changed were removing `styledMode: true`, and setting `colorByPoint: true` so you can see the overlaps. Sorry it's a bit hard to read =)

(By the way, I'm super impressed by Highcharts' performance here. I was sure we wouldn't be able to use the big global dataset, but even with the roundtrip to the API, data sorting and processing, and turboThreshold turned off, it's nice and responsive!)

**Comment by pawelfus** [comment]
Thanks! For the demo and kind words :) It seems that huge difference between the widest and the narrowest column cause the issue.

**Simplified demo:**
https://jsfiddle.net/BlackLabel/2g65dt81/1/
