### ISSUE TITLE
Datagrouping not being applied to arearange series with Highstock since 7.0.3

### ISSUE THREAD

**Issue by gbenthomas** [highcharts/highcharts#11426]
#### Expected behaviour
Datagrouping settings should be applied by default in `arearange` series with Highstock

#### Actual behaviour
Datagrouping is disabled unless you specify an empty `dataGrouping: {}` setting for the series

#### Live demo with steps to reproduce
Zoom the following chart out. Notice not dataGrouping is applied:
https://jsfiddle.net/k0d7xw14/2/

Adding empty `dataGrouping: {}` option to series fixes this:
https://jsfiddle.net/k0d7xw14/3/

#### Product version
Highstock 7.0.3+

#### Affected browser(s)
Tested in Chrome

**Comment by pawelfus** [comment]
Thanks for reporting the issue @gbenthomas 

Bisected to commit 8e6a65e738
