### ISSUE TITLE
Bar chart with height more than 100000 has the top few bars collapsed

### ISSUE THREAD

**Issue by skollip2** [highcharts/highcharts#11443]
#### Expected behaviour
All the bars in the chart will be displayed correctly

#### Actual behaviour
Top few bars in the chart who has the <rect> x values of 100000 are collapsed

#### Live demo with steps to reproduce
https://jsfiddle.net/fhcp4qkr/

#### Product version
v7.1.2

#### Affected browser(s)
Chrome, may be others

**Comment by sebastianbochan** [comment]
Hi @skollip2,
Thank you for reporting the bug.

**Internal note**
It looks like the issue is also with regular column chart.

https://jsfiddle.net/BlackLabel/k9wac2h7/
