### ISSUE TITLE
Right BorderRadius(Rounded Corner of Horizontal stacked Bars) in type Bar chart is not supported

### ISSUE THREAD

**Issue by raksha-scb** [highcharts/highcharts#11445]
I want all the stacked bars (each series) of type bar chart to be rounded from right end  corner only.

I found a plugin but this does not support rounded corners for stacked bar chart
https://github.com/highcharts/rounded-corners

If there is any other plugin available or any solution already in Highcharts please let me know.
Request immediate support, as i am having a urgent requirement.

Thanks.

**Comment by sebastianbochan** [comment]
Hi @raksha-scb,
Thank you for contacting us. In [support](http://www.highcharts.com/support) cases please use the stackoverflow / forum or email.

ps. You can create the ticket about your enhancement in plugin's repo.

**Comment by codenote04** [comment]
@raksha-scb did you find the solution for this type of requirement. ?
