### ISSUE TITLE
Bubble legend in Highmaps causes chart grid lines

### ISSUE THREAD

**Issue by marco-boeck** [highcharts/highcharts#11448]
#### Expected behaviour
When enabling the bubble legend for bubblemaps, there are no y-axis grid chart grid lines appearing.

#### Actual behaviour
Horizontal grid lines appear when enabling the bubble legend.

#### Live demo with steps to reproduce
https://jsfiddle.net/da1pwxv5/

#### Product version
7.1.2

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Thanks for reporting the issue @marco-boeck 

**Workaround:**
Manually set `yAxis.gridLineWidth=0`, demo: https://jsfiddle.net/BlackLabel/9da14jkc/

**Comment by sebastianbochan** [comment]
FYI @ppotaczek
