### ISSUE TITLE
Highcharts generate series, not presented in csv file

### ISSUE THREAD

**Issue by Serzh470** [highcharts/highcharts#11459]
#### Expected behaviour
Render only series names from csv input file

#### Actual behaviour
id there are any numbers in series name array, highcharts generate series from 0 to this number. If I make this number not valid for parser (Number(x) return NaN), highcharts works correct, but it requires adding function to before parse.

#### Live demo with steps to reproduce
not correct work:
[https://jsfiddle.net/smatyushkov/2p8s91ru/](https://jsfiddle.net/smatyushkov/2p8s91ru/)

correct work:
[https://jsfiddle.net/smatyushkov/2p8s91ru/2/](https://jsfiddle.net/smatyushkov/2p8s91ru/2/)

#### Product version
higcharts 7.1.2

#### Affected browser(s)
any

**Comment by pawelfus** [comment]
Hi @Serzh470 

I'm not sure if this is a bug. In data module, we are trying to guess the correct format for each line of the CSV. In your case some of them look like categories, other like a basic linear axis. Numbers in general are treated as category indexes (or just x-value), not category names, unless you setup your xAxis to be categorized, see: https://jsfiddle.net/BlackLabel/6afvc5bx/ - this way, you tell stricte Highcharts to read first column as categories.

Why reading first column as category index? In case of supplying categories separately (e.g. langpack), indexes are useful when data is missing some points: https://jsfiddle.net/BlackLabel/6afvc5bx/4/

**Comment by Serzh470** [comment]
Hi @pawelfus !
Thank you for detailed response, setting up xAxis type as "category" helps!
