### ISSUE TITLE
Packed Bubble - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Mohamed-Ghanem** [highcharts/highcharts#11452]
#### Expected behaviour
To render without errors

#### Actual behaviour
RangeError: Maximum call stack size exceeded is thrown at the console

#### Live demo with steps to reproduce
https://jsfiddle.net/AhmedHassan/g7jf14uh/

#### Product version
Highcharts: 7.1.2
Highcharts More: 7.1.2

#### Affected browser(s)
Chrome 74.0.3729.169 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Thanks for reporting the issue @Mohamed-Ghanem 

**Workaround:**
Limit legend's width to bubbles will get some space to render: https://jsfiddle.net/BlackLabel/5ks30d6w/
