### ISSUE TITLE
Clicking Exporting Context Button opens wrong menu

### ISSUE THREAD

**Issue by sent1nel** [highcharts/highcharts#11457]
#### Expected behaviour

When I have multiple charts on a single web page, and I click the exporting module's context button, the context menu for that chart should become visible.

#### Actual behaviour

When there are multiple charts on the page, clicking the context button reveals and shifts focus to the context menu for the previous chart.

#### Product version
 
7.1.2

#### Affected browser(s)

Firefox 67.0, Chromium

**Comment by sent1nel** [comment]
I believe this has to do with the accessibility module's proxy buttons.

**Comment by sebastianbochan** [comment]
Hi @sent1nel,
Thank you for reporting about the problem.

**Comment by sent1nel** [comment]
No trouble, @sebastianbochan.

I have more information:

See here that event handlers are attached to `H.Chart`; this is a global which I think does not point to the correct chart when buttons are being rebound to add accessibility features. https://github.com/highcharts/highcharts/blob/master/js/modules/accessibility/accessibility.js#L458

Here you can see that event handlers are attached within callbacks, which are passed the correct chart. https://github.com/highcharts/highcharts/blob/master/js/modules/exporting.src.js#L2171

I replaced the accessibility module's global bindings with local bindings, then re-compiled and re-installed the module, and this solved my problem.

**Comment by sent1nel** [comment]
Nevermind all that. It looks like AccessibilityComponent's addProxyGroup's use of `nextSibling` for positioning is causing the issue. Swapping this out for `previousSibling` works.

**Comment by oysteinmoseng** [comment]
@sent1nel Thank you for the thorough detective work so far! I am not able to reproduce this bug on my system with multiple charts on the same page. Can you reproduce this in a jsFiddle or similar environment?

**Comment by oysteinmoseng** [comment]
Closing for now due to inactivity.
