### ISSUE TITLE
Chart.update fails when a new series with a previously unknown id is provided, and oneToOne is set

### ISSUE THREAD

**Issue by mben-romdhane** [highcharts/highcharts#11471]
#### Expected behaviour
When I use Chart.update with oneToOne set to true, and I add a new series with a new ID, update should not raise an exception.

#### Actual behaviour
Highcharts raises:
It tries to find the series object by calling `Chart.get` on the id, and when a series with a corresponding id is not found, it tries to check each point in `series.points` for each `series` in `Chart.series`. However, at this point, all the points are actually null values, so you end up calling `null.id`, which raises an exception. 

This is the console error:
```
Uncaught TypeError: Cannot read property 'id' of null
    at itemById (highstock.src.js:24127)
    at Array.find (<anonymous>)
    at H.find (highstock.src.js:1929)
    at H.Chart.get (highstock.src.js:24136)
    at highstock.src.js:33374
    at Array.forEach (<anonymous>)
    at highstock.src.js:33371
    at Array.forEach (<anonymous>)
    at H.Chart.update (highstock.src.js:33353)
    at (index):50
```

#### Live demo with steps to reproduce
https://jsfiddle.net/he7f43kt/3/
If you remove "id" of the "eurusd" series in the update call, it works.

#### Product version
Highstock 7.2.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thanks for reporting the issue @mben-romdhane 

It's directly related to `series.dataGrouping` - when disabled, works fine: https://jsfiddle.net/BlackLabel/y36uok48/ 

*Internal note:*
DG clears points here:
https://github.com/highcharts/highcharts/blob/91df181bb32a3d8235d9e83ea527893d55d9df17/ts/parts/DataGrouping.ts#L813-L828

**Comment by pphotirath** [comment]
I had the same issue but while removing "id" from the added series works, in my case that is not helpful as I am using the Stock Tools Gui and the id is needed on the data series in order to use the tool with it.

**Comment by pawelfus** [comment]
Did you consider using `chart.addSeries(options)` and `chart.series[index].remove()` instead of `chart.update(series)`? That should solve the issue.

**Comment by pphotirath** [comment]
Hi pawelfus! Thank you for replying! I'm sorry that I wasn't so clear as I saw the above symptoms and it sounded just like mine except I'm actually creating the graph through highcharts-react-official and using a parent component to dynamically generate the dataset to passdown as a prop to the child component which renders the chart (and has the gui). It's breaking when after the chart is mounted and I add new data series. If I hard coded multiple series upfront, then it works mine, it's just when I dynamically add them.

**Comment by pawelfus** [comment]
Ah, react wrapper, thanks for the details! Yes, defining series/creating placeholders should be a safe solution too.

**Comment by pphotirath** [comment]
Yeah, so unfortunately, for the time being, the dynamically added series, I don't apply the id to it so I can't use stock-tools on them, only the main data series (which is the first loaded) has the id. It's a work around that I had hoped to eventually find a solution to solve but haven't found a way around it. Thanks for replying though!

**Comment by pawelfus** [comment]
**Workaround:**
Replace `Chart.get` method with your own, protecting from the error:
```js
Highcharts.Chart.prototype.get = function(id) {
  var ret, series = this.series,
    i;
  /**
   * @private
   * @param {Highcharts.Axis|Highcharts.Series} item
   * @return {boolean}
   */
  function itemById(item) {
    // WORKAROUND #11471 - check `item` too.
    return item && item.id === id || (item.options && item.options.id === id);
  }
  ret =
    // Search axes
    find(this.axes, itemById) ||
    // Search series
    find(this.series, itemById);
  // Search points
  for (i = 0; !ret && i < series.length; i++) {
    ret = find(series[i].points || [], itemById);
  }
  return ret;
};
```

Demo: https://jsfiddle.net/BlackLabel/7qforv46/

**Comment by pawelfus** [comment]
*Internal note:*
Bisected to commit 1fe7b090fc 

Either implement solution from the workaround above, or set `series.points = null` in `destroyGroupedData`. The second one might be problematic, I remember we had some other problems with clearing points, need to test.

**Comment by jesperwiner** [comment]
Ran into same issue when turning on data-grouping, but I've been messing around with the config and when reducing the number of data points the issue also goes away.

Reproduced this without react wrapper, just a simple chart.update

(these fiddle configs are not what we use in prod, just to show the error)

Crashes on chart.update
https://jsfiddle.net/xhts1z9e/2/ 

No crash on chart.update
https://jsfiddle.net/xhts1z9e/3/

For now I'm just gonna override the Chart.get until there is a fix for the underlying problem
