### ISSUE TITLE
Some series.tooltip settings do not override defaults nor chart.tooltip

### ISSUE THREAD

**Issue by sauerdough** [highcharts/highcharts#11470]
#### Expected behavior
Setting options in [`series.tooltip`](https://api.highcharts.com/highcharts/series.column.tooltip) should overwrite the default settings, or override setting for `chart.tooltip`.

#### Actual behavior
Many settings in `series.tooltip` don't seem to do anything, while others do (see example below)

#### Live demo with steps to reproduce
https://jsfiddle.net/k9uq21xn/1/
Scroll over any bar then move mouse out of bar. `series.tooltip` settings such as `hideDelay`, `borderColor`, and `shadow` are not being applied, however `useHtml`, `pointFormatter`, and `headFormat` do. Uncomment `chart.tooltip` section to see that `series.tooltip` does not overwrite all settings.

#### Product version
Seen on Highcharts v7.0.3, as well as v7.1.2

#### Affected browser(s)
Chrome, FF (At least)

**Comment by pawelfus** [comment]
Hi @sauerdough 

Thanks for reporting the issue. Most of the options you mentioned are not part of the `series.tooltip`'s API: there's no `borderColor` or `shadow`. `hideDelay` shouldn't be there too, so it's a bug in docs.
