### ISSUE TITLE
Inverted Variwide with hidden X-axis labels - Cannot set property 'labelrank' of null

### ISSUE THREAD

**Issue by rajeshdanabal** [highcharts/highcharts#11476]
#### Expected behaviour

Inverted Variwide with hidden X-axis labels renders chart with out any error.

#### Actual behaviour
Inverted Variwide with hidden X-axis labels results in,
*Uncaught TypeError: Cannot set property 'labelrank' of null*

#### Live demo with steps to reproduce
Issue URL: https://jsfiddle.net/rajeshdanabal/hm38gw1x/

Go to URL and in the console you can see the error.

#### Product version
Highcharts v7.1.2 (2019-06-03)

#### Affected browser(s)
Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Thanks for reporting the issue @rajeshdanabal

**Comment by rajeshdanabal** [comment]
Do we have any work around to get chart instance? Since it breaks, I am unable to proceed further.

**Comment by pawelfus** [comment]
Yes, sorry! Instead of disabling label, render them as empty strings: https://jsfiddle.net/BlackLabel/7me8x62q/1/

**Comment by rajeshdanabal** [comment]
Ahh... Nice... I will try your suggestion.. Thank you for the reply.
