### ISSUE TITLE
[CandleStick] - lastVisiblePrice doesn't follow lastPrice indicator

### ISSUE THREAD

**Issue by slashvortal** [highcharts/highcharts#11483]
#### Expected behaviour
The lastVisiblePrice label should follow the last tick price just like the lastPrice indicator.

**Actual behaviour**
lastVisiblePrice doesn't follow lastPrice indicator

**Reproducible live demo:**
https://codesandbox.io/s/reactfunn-003w6

**Steps to reproduce:**
- lastVisiblePrice indicator is not visible on the floating candle.
- Wait till the candle close (1 min). After the candle closes, the lastVisiblePrice indicator appears to follow the closed candle only but not the lastPrice.

**Product version**
7.1.2

<img width="725" alt="Screenshot 2019-07-25 at 12 13 15" src="https://user-images.githubusercontent.com/10398252/61866562-a9b52980-aed5-11e9-90b5-ce1070b32108.png">

**Comment by sebastianbochan** [comment]
Hi @slashvortal,
Thank you for reporting about the bug. The problem is caused by enabled dataGrouping which reflects on internal calculations.

Im preparing the fix of the bug, but meantime you can:
- disable datagrouping
- replace the line `crop = (points[points.length - 1].x === x) ? 1 : 2;` with `crop = (points[points.length - 1].x === x) || (serie.yData.length > points.length) ? 1 : 2;`

**Comment by slashvortal** [comment]
Great, I look forward for the fix.

Unfortunately, in my real app, I depend heavily on dataGrouping. So I must wait for the fix before enabling the lastVisiblePrice.

Could you please elaborate more on where to replace the line of crop mentioned? do you mean to touch the HighCharts library?

**Comment by sebastianbochan** [comment]
Hi @slashvortal,
I prepared a fix which just waiting for approve and merge. It should be in the middle of August (dut to vacation time).

Meantime you can edit source of `price-indicator.src.js` files in your `node_modules` and replace line https://github.com/highcharts/highcharts/blob/master/js/modules/price-indicator.src.js#L121
with
```
var pointRange = seriesOptions.pointRange;
crop = (points[pLength - 1].x === x) || pointRange === null ? 1 : 2;
```
(this fix is better then previous).

The second solution is remove module and try to apply JS code in your application (I do not hany details of app, but posted you a simple demo below).

Example:
- https://jsfiddle.net/BlackLabel/o1x5fc6q/
