### ISSUE TITLE
I find a bug in highcharts-gantt

### ISSUE THREAD

**Issue by MichealWind** [highcharts/highcharts#11485]
Expected behaviour
In a grouptask highchart gantt, when hide some parent item, and drag some other point, It will be fine.

Actual behaviour
Many points disappeared. And I can not interact with gantt.

Uncaught TypeError: Cannot read property 'push' of undefined
at highcharts-gantt.src.js:43547
at Array.forEach ()
at highcharts-gantt.src.js:43546
at Array.forEach ()
at l (highcharts-gantt.src.js:43542)
at Object.getTree (highcharts-gantt.src.js:43636)
at B (highcharts-gantt.src.js:44888)
at highcharts-gantt.src.js:44962
at Array.forEach ()

Live demo with steps to reproduce
https://jsfiddle.net/fav2Lwkb/

hide "Product launch" parent item
drag some item in "test drag"

Product version
Highchart-gantt 7.1.2

Affected browser(s)
all

**Comment by pawelfus** [comment]
Hi @MichealWind 

Thanks for reporting the issue, but could you follow our pattern to report a bug? How does it break the chart? What is the expected behaviour? And the most important, please share a live demo (for example in jsFiddle). Thanks!

**Comment by MichealWind** [comment]
> Hi @MichealWind
> 
> Thanks for reporting the issue, but could you follow our pattern to report a bug? How does it break the chart? What is the expected behaviour? And the most important, please share a live demo (for example in jsFiddle). Thanks!

Sorry, I will show an example:
In a grouptask highchart gantt, when I hide some parent item, and drag some other point, It will cause a bug:
Uncaught TypeError: Cannot read property 'push' of undefined
    at highcharts-gantt.src.js:43547
    at Array.forEach (<anonymous>)
    at highcharts-gantt.src.js:43546
    at Array.forEach (<anonymous>)
    at l (highcharts-gantt.src.js:43542)
    at Object.getTree (highcharts-gantt.src.js:43636)
    at B (highcharts-gantt.src.js:44888)
    at highcharts-gantt.src.js:44962
    at Array.forEach (<anonymous>)

And then many point will disappeared.

It can be tested in this fiddle:
[https://jsfiddle.net/Lpya927c/](url)

In this example, when I hide the "Product launch" parent item, and drag some item in "test drag", the bug will appear.
