### ISSUE TITLE
 Navigator overrides Axis min/max settings on series update even though extremes were never set

### ISSUE THREAD

**Issue by mben-romdhane** [highcharts/highcharts#11482]
#### Expected behaviour
The navigator forces series to stick to the left if the series was originally stuck to the left. For that, it uses the min/userMin settings. The expectation is when a user exclusively uses min for updates and setExtremes is never called (i.e. userMin is never set and is undefined), userMin is not changed by the navigator. That way, the next time the user updates the min of an Axis, changes are reflected in the chart, and not overridden by the userMin. Same thing applies to Axis.max/userMax.    

#### Actual behaviour
The navigator updates both min and userMin, and updates to the axis min value are ignored. It's set here:
https://github.com/highcharts/highcharts/blob/bbbcfa00445324005c4651866896fd544499f112/ts/parts/Navigator.ts#L2462-L2471

#### Live demo with steps to reproduce
https://jsfiddle.net/Lwca14tu/
Clicking through the buttons reproduces the scenario, with an update of axis min/max working at first, but then failing after series is updated.

#### Product version
Highstock 7.1.2

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @mben-romdhane 

Thanks for reporting the issue!

**Workaround:**
Use `Axis.setExtremes()` to change extremes and  `Series.setData()` to change dataset. Demo: https://jsfiddle.net/BlackLabel/k3d7jrhL/
