### ISSUE TITLE
No animation when updating series

### ISSUE THREAD

**Issue by yshwaker** [highcharts/highcharts#11484]
When set marker radius to 0 and have some zones options, updating series don't have any animation.

#### Expected behaviour
animate when updating data

#### Actual behaviour
no anitmation

#### Live demo with steps to reproduce
https://jsfiddle.net/wd30apcb/3/

#### Product version
7.1.2

**Comment by pawelfus** [comment]
Thank you for reporting the issue @yshwaker 

**Workaround:**
Use `series.setData()` instead of `chart.update()`, demo: https://jsfiddle.net/BlackLabel/68mzk7qf/

**Comment by yshwaker** [comment]
Thanks for reply. But I'm actually using `highcharts-react-official` which use `chart.update()` internally I think. Maybe not related to this repo.

**Comment by pawelfus** [comment]
@yshwaker - good repo, don't worry :)
