### ISSUE TITLE
Improve demo to reflect changes in caused by TS - dateformats

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#11497]
#### Behaviour
Demo

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/global/dateformats

should be updated to reflect changes done in #9920, so adding `W` instead of full object, so TS won't throw an error.

This demo is causing confusion among users, so it should be fixed.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/global/dateformats

#### Product version
7.1.0+

**Comment by VaLeXaR** [comment]
You can change the code for TS
`// @ts-ignore
Highcharts.dateFormats = {
  W: (timestamp) => {
    const date = new Date(timestamp);
    const day = date.getUTCDay() === 0 ? 7 : date.getUTCDay();
    date.setDate(date.getUTCDate() + 4 - day);
    const dayNumber = Math.floor((date.getTime() - new Date(date.getUTCFullYear(), 0, 1, -6).getTime()) / 86400000);
    return 1 + Math.floor(dayNumber / 7);
  }
};`
