### ISSUE TITLE
Highmaps GeoJSON causes Error 10 with logarithmic colorAxis 

### ISSUE THREAD

**Issue by fpayer** [highcharts/highcharts#11495]
I took the drilldown example (https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/map-drilldown/) for Highmaps and added a single line to the colorAxis settings:

```
type : 'logarithmic',
```

This causes an error 10 to be thrown, just with the map data. I removed all actual data and it still causes an error. 

I've tried importing the geojson via es6 and not using the Highcharts.geojson wrapper and that works.

eg:
```
import usMap from 'libs/maps/us/us-all.geo.json';
...
{
  mapData : usMap,
},

```
But this does not
```
var usMap = Highcharts.geojson(Highcharts.maps['countries/us/us-all'])
{
  mapData : usMap,
},
```

However, when I use the es6 import and dont call .geojson, drilldown does not work.

#### Expected behaviour

An error 10 should not be thrown. 

#### Actual behaviour

An error 10 is thrown.

#### Live demo with steps to reproduce
https://jsfiddle.net/u987a6xd/

#### Product version
Highcharts/Highmaps version 7.0.3

#### Affected browser(s)
Testing in Google Chrome 75

**Comment by pawelfus** [comment]
Hi @fpayer 

Thanks for reporting the issue, but in this demo you need to change two things to get a proper chart:

- change `colorAxis.min` to a value that is higher than `0`
- modify data/remove data - at this moment, data values start from `0`, so simple change in the demo `this.value = i` to `this.value = i + 1` is enough

See working demo: https://jsfiddle.net/BlackLabel/ma5xos0q/1/

**Comment by fpayer** [comment]
Ah, the colorAxis.min was the culprit. Thanks for the quick response.
