### ISSUE TITLE
rangeSelector input and export button missalignment

### ISSUE THREAD

**Issue by hakkim** [highcharts/highcharts#11491]
I have highchart with rangeSelector. My problem is when I disable the rangeSelector label the rangeSelector input overlapping with the export button.

```
Highcharts.stockChart('container', {

    rangeSelector: {
        labelStyle: {
            display: 'none',
        },
    },

    series: [{
        data: usdeur
    }]
});
```

#### Expected behaviour
rangeSelector and export button must be shown in a side to side

#### Actual behaviour
rangeSelector overlapping with export button

#### Live demo with steps to reproduce
https://jsfiddle.net/hakkim/akzvtxb5/2/

#### Product version
Highcharts JS v7.1.2

#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Thanks for reporting the issue @hakkim 

**Workaround:**
Instead of setting `labelStyle.display`, use `Highcharts.setOptions({ lang: { ... } });` to replace text with empty strings, demo: https://jsfiddle.net/BlackLabel/xqa8sLo3/

**Comment by hakkim** [comment]
> Thanks for reporting the issue @hakkim
> 
> **Workaround:**
> Instead of setting `labelStyle.display`, use `Highcharts.setOptions({ lang: { ... } });` to replace text with empty strings, demo: https://jsfiddle.net/BlackLabel/xqa8sLo3/

I fixed it with `visibility: 'hidden'`
