### ISSUE TITLE
Y Axis scaled using set Extremes Is inappropriate 

### ISSUE THREAD

**Issue by AntonyJos** [highcharts/highcharts#11493]
#### Expected behaviour
Hovering on the Chart should display the values of the series in the tooltip that belongs to the View of the chart, in effect

#### Actual behaviour
The tool-tip displays the values that does not belong to the View in effect of the chart

#### Live demo with steps to reproduce

1. Create Multiple Y Axises that are not opposite to each other.
That is, It is being arranged below one after the other.
2. Add one or multiple Series to each of these axises.
3. Let the data points vary from a range of 70 - 100.
4. Scale one of the Axises between 85 - 90
5. Hover over the Chart
6. Observe the tooltips that are being displayed

Observation
The tooltip displays values above 90 for the Axis which has been scaled till 90

Please find the below working fiddle

https://jsfiddle.net/uk1exc89/1/

See the tooltip before and after clicking on the 'Set Scale Range' button

Please find the image below for the outcome

![AfterScaling](https://user-images.githubusercontent.com/42953694/61900919-372b6480-af3c-11e9-8ba3-536aa27bb2ca.png)

The toolTip that belongs to the **Title 4** region is being displayed along with **Title 3** region which does not make any sense to the user at all.

#### Product version

Highstock - 7.1.2

#### Affected browser(s)
Only tested out in Google Chrome - ^74.0.x

**Comment by pawelfus** [comment]
Thanks for reporting the issue @AntonyJos 

*Internal note:*
FYI @jon-a-nygaard - it seems to be the same issue as #7650 - tooltip shared/split is not limited to the visible xAxis/yAxis dimensions.

**Comment by AntonyJos** [comment]
@pawelfus / @jon-a-nygaard  / @TorsteinHonsi ,

The Parent Defect #7650 seems to be in the open state for more than an year.
Is It still work in Progress?
When can the fix be expected...

**Comment by jon-a-nygaard** [comment]
Thanks again for reporting @AntonyJos,

I am currently looking into the issue, and it seems that I am able to make a fix for this that can be included in the next maintenance release.

Will keep you posted once I know more.

**Comment by AntonyJos** [comment]
Wish to reopen the defect
Fix needed to be revisited

The series seems to be only visible while hovering over the respective series

![seriesHighlighted](https://user-images.githubusercontent.com/42953694/62622644-72666400-b93c-11e9-867d-cdc4d07f211c.png)

While the series opacity is reduced while hovering over the same point at a different series

![seriesColourMissing](https://user-images.githubusercontent.com/42953694/62622686-8c07ab80-b93c-11e9-8554-aa9f48e835a5.png)


Observe the series for the Title 4 after scaling in both the cases at **Sunday, May 26, 22:10**

**Comment by AntonyJos** [comment]
@pawelfus / @jon-a-nygaard , Kindly do the needful

**Comment by AntonyJos** [comment]
@pawelfus , @sebastianbochan 

Again the fix introduced has turned out to be vague..
Kindly revisit the link to reproduce the defect once more

@jon-a-nygaard , @TorsteinHonsi, 

Is there a way to reduce the count of regression defects.
Do we have a test case for each of the defects fixed?

So that next time something is committed potential to break this functionality
The test case should ideally be failing...

**Comment by pawelfus** [comment]
Bisected to commit 03abca5bec

@TorsteinHonsi - FYI

**Comment by TorsteinHonsi** [comment]
I'm reverting the fix. In the following scenario, it is not right to clamp the tooltip: https://jsfiddle.net/highcharts/ad40vbeL/ . Look at the first and second points. The new tooltip position gives the false impression that the data value is at axis minimum, 100. 

Instead, I think the tooltip should be hidden in this case.

**Comment by TorsteinHonsi** [comment]
For line series, the tooltip for values outside the axis should not appear. This currently works correctly for a full size axis, regardless of `split`, `shared` or none: https://jsfiddle.net/highcharts/nzcv5rx4/1/

For column series, the tooltip is clamped if it is `shared`: https://jsfiddle.net/highcharts/nzcv5rx4/2/ . The rationale here is that the tooltip is at the top, top it is pointing down towards where the point is.

However, if we set a `height` for the Y axis, the tooltip displays also for values outside the axis area: https://jsfiddle.net/highcharts/nzcv5rx4/3/. So when fixed, this should be consistent. Probably we need to use `axis.pos` and `axis.len` to determine the bounds of the tooltip instead of `chart.plotTop` and `chart.plotHeight`.
