### ISSUE TITLE
Tooltip z-index problem with outside:true

### ISSUE THREAD

**Issue by jwh2018** [highcharts/highcharts#11494]
#### Expected behaviour
When the following parameters are met the tooltip should be completely opaque:
1. A <section> around the chart (#outer in the jsfiddle) has a z-index greater than 3
2. The container div for the chart has position: relative (.container in the jsfiddle)
3. The tooltip has outside: true
4. The tooltip span has a fully opaque color (i.e. rgba(100,100,100,1)

#### Actual behaviour
Tooltip is not opaque. But if you change any one of the items above (other than 4) then it will be opaque.

#### Live demo with steps to reproduce
https://jsfiddle.net/te1qc2wn/

The issue seems to be that when Outside is true, the z-index of the tooltip is set to 3 and there is no way to change it using css. In previous versions the z-index was not set to 3 and it worked fine.

#### Product version
Is not a problem in Highcharts version 7.1.1, but is a problem in more recent versions.

#### Affected browser(s)
Only tested in Chrome

**Comment by pawelfus** [comment]
Thanks for reporting the issue @jwh2018 

*Internal note:*
Regression since 48a82ce80ba946839e3a1280e63ca02ab1f88ec0

**Comment by yusuf-9** [comment]
Is there a way to use this workaround with the highcharts react wrapper?
