### ISSUE TITLE
Is there any in-built functions to automatically switch the datalabels, axes and series color depending on the chart background

### ISSUE THREAD

**Issue by Sundarcj** [highcharts/highcharts#11503]
The gridlines color are automatically changed according to the given background(For eg. If the background color is 'black', gridlines are automatically switched to 'white'). Likewise, is there any in-built methods to handle this type of intelligence for axes Labels, DataLabels and series color.

I came across one manual solution(please refer http://jsfiddle.net/BlackLabel/u36d8r24/). This works fine with the "load" event, but with "redraw" or "render" it unfortunately resulted in an infinite redraw loop.

**Comment by sebastianbochan** [comment]
Hi @Sundarcj,
Thank you for contacting us. The github is our bug tracker so for general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow of email.
