### ISSUE TITLE
stackLabels misalignment when yAxis left value is defined

### ISSUE THREAD

**Issue by aswinkumar863** [highcharts/highcharts#11500]
**Expected behaviour**

`stackLabels` needs to be aligned outside of horizontal bar

**Actual behaviour**

`stackLabels` get misaligned when `yAxis` `left` value is defined. 

**Live demo with steps to reproduce**
```
yAxis: {
  left: '50%', 
  ...
}
```
_Fiddle with `left` value_ - http://jsfiddle.net/aswinkumar863/moq3ntf0/8/ _(misaligned)_
_Fiddle without `left` value_ - http://jsfiddle.net/aswinkumar863/moq3ntf0/9/

**Product version**

Highcharts v7.1.2

**Affected browser(s)**

Google Chrome 75.0.3770.142 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Thank you for reporting the issue @aswinkumar863 

It seems in general top/left are not respected when positioning `stackLabels`.

Simplified demo: http://jsfiddle.net/BlackLabel/ozca65nh/ (non inverted)
