### ISSUE TITLE
Can't disable animation for packedbubble charts

### ISSUE THREAD

**Issue by k-dauda** [highcharts/highcharts#11514]
For large series, rendering performance takes a hit with all the animations. It would be nice if we could disable the animations based on a limit or completely but neither option works.

#### Expected behaviour
Animation is turned off when plotOptions.series.animation is false or plotOptions.series.animationLimit is 0.

#### Actual behaviour
Animation is still turned on.

#### Live demo 
https://jsfiddle.net/c1hn2uwq/

#### Product version
7.1.2

**Comment by sebastianbochan** [comment]
Hi @k-dauda,
Thank you for contacting us. The github is our bug tracker, so for general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or forum.

ps. You can disable it by the option [enableSimulation](https://api.highcharts.com/highcharts/series.packedbubble.layoutAlgorithm.enableSimulation)
