### ISSUE TITLE
Highcharts export does not not display emojis

### ISSUE THREAD

**Issue by pomartel** [highcharts/highcharts#11512]
#### Expected behaviour

When a chart is exported as an image, it should display emojis included in labels. The export server probably doesn't have the required package to deal with the emoji encoding.

#### Actual behaviour

Emojis are ignored and not displayed.

#### Live demo with steps to reproduce

http://jsfiddle.net/jxLvdu29/

**Comment by TorsteinHonsi** [comment]
You're probably right that the required package is not installed.

#### Workaround
Use the offline exporting module: http://jsfiddle.net/highcharts/dy7ev9wo/

**Comment by pomartel** [comment]
Oh yeah, that's a great workaround! Thanks a lot @TorsteinHonsi!
