### ISSUE TITLE
Variwide chart does not display some points

### ISSUE THREAD

**Issue by vforchi** [highcharts/highcharts#11510]
#### Expected behaviour
The chart should display all input points

#### Actual behaviour
If the width of the columns is small compared to the total x range, some elements are not displayed

#### Live demo with steps to reproduce
https://jsfiddle.net/bed7fsqc/5/
The first three points are not displayed

#### Product version
Highcharts

#### Affected browser(s)
Firefox, Chrome (at least)

**Comment by pawelfus** [comment]
Thank you for reporting the issue. You are right, it seems that some of the points are missing - more than just first three, we can observe many points in the DOM that have width=0, like this one:

```svg
<rect x="15" y="327" width="0" height="4" fill="orange" opacity="1" class="highcharts-point highcharts-color-2"></rect>
```

We can add minimum width for a bar, like this:

```js
(function(H) {
  H.wrap(H.seriesTypes.variwide.prototype, 'translate', function(proceed) {
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));

    this.points.forEach(function(point) {
      if (point && point.shapeArgs) {
        point.shapeArgs.width = Math.max(point.shapeArgs.width, 1);
      }
    });
  });
})(Highcharts);
```

Demo: https://jsfiddle.net/BlackLabel/o5a2fxgp/

However, now bars will overlap - not a perfect solution, but this is what happens in column series too: https://jsfiddle.net/BlackLabel/o5a2fxgp/2/

Any thoughts @TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
> Any thoughts @TorsteinHonsi ?

Yes, I think it should behave like the column series, so the width never is less than 1px. It is better with 1px columns overlapping each other, than the columns disappearing.
