### ISSUE TITLE
Excuse me. I'm just asking you a questio about highstock stock-tools.

### ISSUE THREAD

**Issue by JUKOOK** [highcharts/highcharts#11517]
Hi. I am a developer studying high charts and high stocks.
(I am currently studying with 'Highstock Demos> Stock chart with GUI')

It is not a bug issue, I have a question and I write.

When we finished drawing one stock tool, we saw that the cursor: move on the chart disappears and class: highcharts-active of the tool's button (exactly li.highcharts-segment, etc.) disappears.

My question is this.
I am looking at 'highcharts/modules/annotations-advanced' and 'highcharts/modules/stock-tools' and I can not find a method or part to figure out(or catch) the event at the end of drawing one stock tool.

For example, if I want to display "Hi!" on the console(console.log("Hi!")), at the moment the drawing of the stock tool ends, where do I add it?

**Comment by pawelfus** [comment]
Hi @JUKOOK 

Thanks for choosing Highcharts and Highstock! You can use [`navigation.events.deselectButton`](https://api.highcharts.com/highstock/navigation.eventshttps://api.highcharts.com/highstock/navigation.events.selectButton).

PS: This is our bug tracker - when you have a question, please use our other support channels: https://www.highcharts.com/blog/support/
