### ISSUE TITLE
When arearange series starts with NaN, series is not drawn

### ISSUE THREAD

**Issue by gbenthomas** [highcharts/highcharts#11513]
Related: #3571

#### Expected behaviour
Series should be drawn when first value of arearange series is NaN

#### Actual behaviour
Series is not drawn when first value of arearange series is NaN

#### Live demo with steps to reproduce
http://jsfiddle.net/mdezob53/

Works if you make second value of the first point a valid number: http://jsfiddle.net/mdezob53/1/

#### Product version
Highcharts/Highcharts More 7.1.2

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
Series data accept `number` or `null`, so you should filter your data and replace `NaN` with `null`: http://jsfiddle.net/highcharts/umt8axyq/1/

**Comment by gbenthomas** [comment]
@TorsteinHonsi 

NaN works for arearange series when it's not the first point: http://jsfiddle.net/5Ls9hfbk/

NaN also works for line series: http://jsfiddle.net/4j60cn9p/

If this isn't a bug, I would like to request adding this info to the documentation since it wasn't clear. According to other GitHub issues, NaN is supported for at least some series (#3571). Why is it only not supported for the first point in an arearange series?

(Also, just to be pedantic, `NaN` has a type of `number`)

**Comment by TorsteinHonsi** [comment]
Yes you're right, it filters out NaN in other cases.
