### ISSUE TITLE
Can we generate heat map like this

### ISSUE THREAD

**Issue by bdevika** [highcharts/highcharts#11516]
![Screenshot (1)](https://user-images.githubusercontent.com/40199188/62184033-13bc4b80-b37a-11e9-9121-5ab93a368374.png)

**Comment by sebastianbochan** [comment]
Hi @bdevika,
Thank you for contacting us. The github is our bug tracker so for [general support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.
