### ISSUE TITLE
Accessibility module adds h6 elements to chart

### ISSUE THREAD

**Issue by supermonkeybrainz** [highcharts/highcharts#11511]
#### Expected behaviour
I should be able to override the default behavior of placing heading elements inside of the InfoRegionComponent.

#### Actual behaviour
I get h6 elements when activating the accessibility plugin that can't be removed.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/accessible-pie/

#### Product version
All

#### Affected browser(s)
All

The code that appends the `h6` elements may be found here:

https://github.com/highcharts/highcharts/blob/d96783fcaeebd4548256d93c1476cbb50d2d716a/js/modules/accessibility/components/InfoRegionComponent.js

**Comment by supermonkeybrainz** [comment]
The reason I am submitting this issue is that by using the chart with the accessibility module I get header order validation issues.  I would like to remove the header elements, or at the least set the heading level to use.  I presume these exist for navigation, but would it be better to just rely on tabindex?  Not an a11y expert. :)

**Comment by sebastianbochan** [comment]
Hi @supermonkeybrainz,
Thank you for reporting about the problem.

Developer of the module will be available next week and answer you as soon as possible.
