### ISSUE TITLE
`nodePadding` can mess up any sankey chart

### ISSUE THREAD

**Issue by futpib** [highcharts/highcharts#11526]
#### Expected behaviour

No combination of [`series.sankey.nodePadding`](https://api.highcharts.com/highcharts/series.sankey.nodePadding) and [`chart.height`](https://api.highcharts.com/highcharts/chart.height) can break the chart. If respecting both `nodePadding` and `height` is not possible, `nodePadding` is ignored.

Alternatively, an error is thrown if layout is not possible with given combination of `height`, `nodePadding` and `data` instead of a broken chart rendering.

Alternatively, documentation advises that users adjust their `nodePadding` depending on the number of data points.

#### Actual behaviour

When `nodePadding` times *maximum number of nodes in a column* is greater than chart height, the chart is broken.

#### Live demo with steps to reproduce

Example with `nodePadding: 100`: https://jsfiddle.net/efhgc6ux/
Example with `height: 200` and `nodePadding: 60`: https://jsfiddle.net/efhgc6ux/1/

#### Product version

highcharts@7.1.2

#### Affected browser(s)

Latest Chrome and Firefox

**Comment by pawelfus** [comment]
FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! I think it should be default reduce the rendered `nodePadding` to the largest possible amount when this situation occurs.

**Comment by khlieng** [comment]
Fixed since 8.0.1 (#12931).
