### ISSUE TITLE
Tooltip box with useHTML

### ISSUE THREAD

**Issue by rahbari** [highcharts/highcharts#1152]
When useHTML is true for tooltips, their text is rendered using HTML but the box itself is still SVG and they are positioned somehow that the text is upon box.  

With RTL languages like Arabic this leads to bad positioning, so text is not always upon the box.

I just wonder why all the box is not HTML. it can be rendered using a simple div with border-radius.

**Comment by jcrben** [comment]
For anyone running across this in Google, I found the following Stackoverflow answer helpful for eliminating SVG: https://stackoverflow.com/a/32867140/4200039
