### ISSUE TITLE
Highcharts layout breaks when printing in IЕ11.

### ISSUE THREAD

**Issue by fredure** [highcharts/highcharts#11536]
#### Expected behaviour
![2019-08-01_14-48-34 (2)](https://user-images.githubusercontent.com/8024592/62284377-f1efc100-b46c-11e9-94f3-ec5b78e7a98a.png)

#### Actual behaviour
Layout of diagrams breaks when printing in IE11.
![2019-08-01_14-49-34 (2)](https://user-images.githubusercontent.com/8024592/62284452-1350ad00-b46d-11e9-842c-af239e6ad9d0.png)

#### Product version
HighCharts 7.0.3

#### Affected browser(s)
IE11

**Comment by pawelfus** [comment]
Hi @fredure 

Thank you for reporting the issue, but please recreate issue in jsFiddle. Thanks!

**Comment by fredure** [comment]
> Hi @fredure
> 
> Thank you for reporting the issue, but please recreate issue in jsFiddle. Thanks!

Sorry, but I can not emulate output printing jsFiddle in IE11.
http://jsfiddle.net/nwt34yu9/2/

**Comment by KacperMadej** [comment]
@fredure 
Prints for me in IE11 like in the attached image.
Please describe what is the problem and where is the overlay you have reported in the images of your first comment.

[asdf.pdf](https://github.com/highcharts/highcharts/files/3456532/asdf.pdf)

**Comment by fredure** [comment]
@KacperMadej 
Need to scroll the document after printing
http://jsfiddle.net/jhvguepf

![image](https://user-images.githubusercontent.com/8024592/62293920-24a4b400-b483-11e9-88fc-8b5fd36cd97a.png)

**Comment by KacperMadej** [comment]
It's a general problem with printing SVG images that are partially inside two pages. A solution for this would be to add a page break. A demo better showing the issue:
http://jsfiddle.net/BlackLabel/3fryb04q/

And exported in IE11 image:
[asdf4.pdf](https://github.com/highcharts/highcharts/files/3456818/asdf4.pdf)

This doesn't looks like a Highcharts issue as we support printing charts through export module.

**Comment by fredure** [comment]
@KacperMadej 
Thank you very much for the answer.
