### ISSUE TITLE
packedbubble - Unable to update chart with reduced amount of series and 'oneToOne' flag

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#11545]
#### Expected behaviour

The chart should be updated without any errors.

#### Actual behaviour

Error: `Uncaught TypeError: Cannot read property 'renderer' of undefined`

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/w7y9eq2f/

Original use case: https://codesandbox.io/s/hopeful-thompson-4hmj0

#### Product version
Highcharts v7.1.2

#### Affected browser(s)
All

FYI: @Izothep

**Comment by Izothep** [comment]
closed by e28fbc4
