### ISSUE TITLE
Gantt: scrollablePlotArea.minHeight doesn't work and turns chart invisible

### ISSUE THREAD

**Issue by FilipeCosta06** [highcharts/highcharts#11556]
#### Expected behaviour
> The minimum height for the plot area. If it gets smaller than this, the plot area will become scrollable.

Setting `chart.scrollablePlotArea.minHeight` attribute should display a vertical scrollbar if the chart gets smaller than the provided value.

#### Actual behaviour
- When configured alone (no `minWidth`), the chart is either invisible or has the height of the xAxis labels (weeks/day). The `div.highcharts-scrolling`'s height attribute is set to `87px`.
- When `minWidth` is also set, the height is back to "auto" I suppose and the only Y scrollbar you get is the one from the body (proved by setting `body { overflow: hidden }` in the CSS).

Also, as a side note, the API gives [3 demo links](https://api.highcharts.com/gantt/chart.scrollablePlotArea) and the 3rd one is specifically meant to be a vertically/Y scroll Gantt demo but instead points to the second demo too.

#### Live demo with steps to reproduce
https://jsfiddle.net/8j1L34ef/

#### Product version
Highcharts Gantt (v7.1.2)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting @FilipeCosta06 

It seems that setting height for the chart helps with it: https://jsfiddle.net/BlackLabel/eLbugfyq/

Just to be on the same page:
> When minWidth is also set, the height is back to "auto" I suppose and the only Y scrollbar you get is the one from the body (proved by setting body { overflow: hidden } in the CSS).

That is expected, just above the three demos, you can find the answer:
> Since v7.1.2, a scrollable plot area can be defined for either horizontal or vertical scrolling, depending on whether the minWidth or minHeight option is set.

You can use only one, vertical or horizontal scrolling.

@TorsteinHonsi - FYI

**Comment by FilipeCosta06** [comment]
Hi @pawelfus,

Oh we can't combine them ? That's good to know _(but also a bummer ahah)_. 

I was trying to "force" the graph into having specific dimensions (1920x1080, etc...) but the size attributes like `height` and `width` don't display scrollbars (other than the body's). And I don't want the chart to become responsive (at least, past the specified dimensions) which is why I love `scrollablePlotArea`.

Then again, in your demo, by setting both `chart.height` and and `scrollablePlotArea.minWidth`, **I am able to achieve what I want**: the body provides the vertical scroll I need. I must've had some CSS code interfering somewhere. My personal problem will be that, in my case, I have various widgets above/below the chart that'll make this scroll-Y appear sooner than expected but I'm sure I can find a CSS solution to that.

Thanks again, I'll keep your fix in mind ^^
