### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'forExport' of undefined

### ISSUE THREAD

**Issue by jhonnyperezm** [highcharts/highcharts#11553]
![Error](https://user-images.githubusercontent.com/33642805/62395990-7ad32f00-b537-11e9-9470-a9be30c1702c.png)

```typescript
MediosdPPrincipal: typeof Highcharts = Highcharts;
  MediosdPPrincipalChart: Highcharts.Options = {
    lang: {
      printChart: 'Imprimir Grafico',
      downloadCSV: 'Descargar CSV',
      downloadJPEG: 'Descargar JPEG',
      downloadPDF: 'Descargar PDF',
      downloadPNG: 'Descargar PNG',
      downloadSVG: 'Descargar SVG',
      downloadXLS: 'Descargar XLS',
    },
    title: {
      text: 'Ventas generales por artículos'
    },
    subtitle: {
      text: 'Datos Obtenidos de los ultimos 6 meses - Valores en miles '
    },
    credits: {
      enabled: false
    },
    xAxis: {
      categories: []
    },
    yAxis: [{
      className: 'highcharts-color-0',
      title: {
        text: ' '
      }
    }, {
      className: 'highcharts-color-1',
      opposite: true,
      title: {
        text: ' '
      }
    }],
    series: [{
      name: 'Año Actual',
      data: [],
      type: 'column'
    }, {
      name: 'Año Pasado',
      visible: false,
      data: [],
      type: 'column'
    }],
    exporting: {
      filename: 'Grafico-principal-formadepago',
      buttons: {
        contextButton: {
          menuItems: ['printChart', 'separator', 'downloadPNG', 'downloadSVG',
            'downloadJPEG', 'downloadPDF', 'separator', 'downloadCSV', 'downloadXLS'],
          //text: 'Exportar',
          symbolStroke: 'green'
        }
      }
    },
  };
```

```typescript
ArticulosPrincipalG(fechainicial, fechafinal) {
    this.GestorArticulos.getGestorArticulosPrincipal(fechainicial, fechafinal, this.puntosPorZona).subscribe(
      (data) => {
        const actual = data.map(x => x.actual);
        const nombre = data.map(x => x.nombre);
        const pasado = data.map(x => x.pasado);
 
        this.MediosdPPrincipalChart.xAxis['categories'] = nombre;
        this.MediosdPPrincipalChart.series[0]['data'] = actual;
        this.MediosdPPrincipalChart.series[1]['data'] = pasado;
      	Highcharts.chart('MediosdPPrincipal', this.MediosdPPrincipalChart);

        // tslint:disable-next-line: no-unused-expression
 
        console.log("Cuando ingresa a la funcion", this.MediosdPPrincipalChart);

        // tslint:disable-next-line: label-position
        // tslint:disable-next-line: no-unused-expression

        console.log("Cuando ingresa sale de la funcion", this.MediosdPPrincipalChart);

      }, (err) => {
        console.error(err);
      });
```

```html
<div class="contenedor-grafica4">
      <highcharts-chart id="MediosdPPrincipal" [Highcharts]="MediosdPPrincipal" [options]="MediosdPPrincipalChart"
        style="width: 100%; display: flex; justify-content: center;">
      </highcharts-chart>
    </div>
```

**Hello**,
The graph loads well, the error happens when I want to leave the component to another

**Comment by KacperMadej** [comment]
Hi @jhonnyperezm 

Thank you for reporting about the problem.

Please create a live demo for the problem. This could lead to a resolvable solution for the highcharts-angular wrapper that you are using, but first we need to debug the issue to confirm that it is not caused by avoidable or not needed function calls.

Are you destroying the chart in any way before the component gets destroyed?
To track the destroy event you could add an option to the chart in chart.events.destroy to log each of the destroy calls and then you will be able to track origin of those destroy calls. If you can create and share a demo then I could debug the code, but I'm letting you know what you could do if a live demo is not available.

**Comment by jhonnyperezm** [comment]
Hi ,@KacperMadej 
You have created an error repository and a live demo

Repositorio
https://github.com/jhonnyperezm/apli-grafica

live
https://stackblitz.com/edit/angular-cmvg1f

I was grateful for a possible solution

**Comment by Brechttz** [comment]
I'm experiencing the same issue with Highcharts-Vue.

[Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'forExport' of 

 TypeError: Cannot read property 'forExport' of undefined
    at a.Chart.destroy (highcharts.js?ea7f:294)
    at VueComponent.beforeDestroy (highcharts-vue.min.js?4452:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at callHook (vue.runtime.esm.js?2b0e:4213)
    at VueComponent.Vue.$destroy (vue.runtime.esm.js?2b0e:3972)
    at destroy (vue.runtime.esm.js?2b0e:3159)
    at invokeDestroyHook (vue.runtime.esm.js?2b0e:6108)
    at invokeDestroyHook (vue.runtime.esm.js?2b0e:6113)
    at invokeDestroyHook (vue.runtime.esm.js?2b0e:6113)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js?2b0e:6461)`

**Comment by KacperMadej** [comment]
@jhonnyperezm 

Thank you for the demo.
You are creating a chart without usage of the highcharts-angular wrapper in the same container that already has a chart with a chart created using the wrapper, so it doesn't registers destroy (on new chart being created in the same container). This is not a supported usage of the highcharts-angular wrapper, so you could either update the chart and in case you want to discard it - destroy the component and create a new one, or stop using the wrapper and create the chart using pure Highcharts library.

This is not a bug, the issue will be closed, but if you have any more questions please let us know.

@Brechttz 
Please report the bugs in the wrapper on the wrapper repository with a live demo included.

**Comment by jhonnyperezm** [comment]
@KacperMadej 

Thank you very much for the answer, you can solve the error and in the same way you will find the answer

**Comment by ldsenow** [comment]
I have similar issue with the highchart vue wrapper.

The root cause could be a bug from the ui lib i use. It somehow triggers onMounted events multiple times. When I navigate to another page, i have the error about trying to destroy the chart which it has done already. I think the onBeforeMount is called multiple times due the multiple mounts in the early beginning.

I dig up the code which does the destroy in this repo as below 

```
function destroyChart () {
  if (this.chart) {
    this.chart.destroy()
  }
}
```

I reckon we can delete this.chart to avoid the issue described above.

```
function destroyChart () {
  if (this.chart) {
    this.chart.destroy()
    delete this.chart
  }
}
```

I hope it helps.
