### ISSUE TITLE
typescript: Axis class should have minRange field

### ISSUE THREAD

**Issue by pdeva** [highcharts/highcharts#11555]
#### Expected behaviour

`minRange` field should be present in typescript definition of `Axis` class

#### Actual behaviour

No `minRange` field in the typescript definition of Axis class
 
 

#### Product version
highcharts 7.1.2

**Comment by sebastianbochan** [comment]
Hi @pdeva,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by bre1470** [comment]
@TorsteinHonsi Can we make `minRange` (and maybe `userMinRange`) public properties?

**Comment by TorsteinHonsi** [comment]
I'd rather not, they are internal properties used for computation. However there's a `minRange` _option_.

**Comment by bre1470** [comment]
@pdeva The solution is to access `Axis.options.minRange` option, which will be part of the official API with the next update in a few days.

**Comment by pdeva** [comment]
I am a little confused.

currently i have code like this.

```js
events: {
 selection: function (event: ChartSelectionContextObject) {
	event.preventDefault();

	const selection = event.xAxis[0];
       // IS THIS LINE  CORRECT?
	const minRange = (selection.axis as any).minRange;

	if (range >(selection.max-selection.min)) {
	    //do application stuff
	}

	return false;
 }
}
```

As you can see, I am currently casting `selection.axis` to `any` to get `minRange`. 

With the modification you prescribed, will things just work out of the box without me needing to cast to `any` or do i need to get `minRange` via some other method?

**Comment by bre1470** [comment]
There is a difference between `Axis.minRange` and `Axis.options.minRange`. They will not be necessarily share the same value. With the next update you can do
```ts
const minRange = (selection.axis.options.minRange || 0);
```

**Comment by pdeva** [comment]
@bre1470 can you tell me where to find the docs for `Axis.options.minRange`.

I dont see any `options` object here for `xAxis`
https://api.highcharts.com/highcharts/xAxis

**Comment by bre1470** [comment]
@pdeva With the current version this property is unfortunately not documented and therefor not in the TypeScript declarations. The documentation and declarations of the next Highcharts update will instead contain `Axis.options` and `Axis.userOptions`. The release of the update is probably this or next week.

**Comment by bre1470** [comment]
As a temporary workaround to avoid `any` casts, you can patch your project like this:
```ts
declare module `highcharts` {
    interface Axis {
        options: AxisOptions;
        userOptions: AxisOptions;
    }
}
```
