### ISSUE TITLE
How to build an npm package from source?

### ISSUE THREAD

**Issue by sakekasi** [highcharts/highcharts#11554]
#### Expected behaviour
In the readme.md, it describes how to build the source to dist, but not how to build a local npm package with all the typings included. I'd like to modify the highcharts package (to include some commented out code allowing boost to render bubble charts with color by point) and use it locally with npm. Could this info be added to the docs?

#### Actual behaviour
The current docs only include basic info on how to build highcharts, not how to build a node module with typescript typings

#### Product version

Highstock 7.1.2

**Comment by jon-a-nygaard** [comment]
Hi @sakekasi,

You can run `npx gulp scripts && npx gulp scripts-compile && npx gulp jsdoc-dts` to create the source code, compiled code, and the typescript typings. All the files will be outputted to the `./code` folder in the highcharts repository, which you can copy to your own project.

I am not sure if this is something that we would like to document externally as it is somewhat rare that our users create their own custom distribution of Highcharts, but I will discuss it with the rest of the team to see if it may be of interest.

You should also be aware that customizing the Highcharts code may limit the support we can provide if any future issues should arise related to the customization.

Best regards
Jon

**Comment by sakekasi** [comment]
Hi, 

It's a pretty minor change, just uncommenting line 235 and lines 510-517 in wgl-renderer.js. But understood on limiting support.

I'm also running into problems trying to run gulp. I get the following errors when I run `npx gulp scripts`. https://www.dropbox.com/s/5xjeg4w1ov2xsl5/Screenshot%202019-08-05%2009.53.40.png?dl=0

Can you shed some light on this? 

Thanks

**Comment by sakekasi** [comment]
Also, even if it's not in the readme.md, it might be worth including a quick comment with a sentence saying what each gulp build task does in gulpfile.js. Even that would help a lot

**Comment by sakekasi** [comment]
Got it compiling on MacOS with a few minor changes to tsconfig.json and Pathfinder.js. LMK if it's worth making these changes a pull request

**Comment by jon-a-nygaard** [comment]
Hi @sakekasi, I forgot to mention that it is necessary to run `npm install` before the previously mentioned command.
I was unable to reproduce the errors you posted, so I am not sure if a missing install was the cause of your issues.

It could also maybe be a difference in TypeScript versions, I am currently running `typescript@3.4.5` without errors in our `master` branch.

Let me know if you are still experiencing issues with this.

**Comment by jon-a-nygaard** [comment]
**FYI:** We are currently working on migrating our source of documentation to GitHub which should be done soon. In this process we will also add public documentation on our tooling, build and distribution process. I will let you know about the progress of this.

**Comment by sakekasi** [comment]
Sounds good, thanks!

Saketh

**Comment by TorsteinHonsi** [comment]
See https://github.com/highcharts/highcharts/blob/master/docs/getting-started/how-to-create-custom-highcharts-files.md
