### ISSUE TITLE
Migrate `modules/map` to TypeScript

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#11581]

**Comment by bre1470** [comment]
@jon-a-nygaard This `modules/map.src.js` is empty. Do you agree, that we can delete it?

**Comment by sebastianbochan** [comment]
It is used by maps like https://www.highcharts.com/docs/maps/getting-started and its not empty here: http://code.highcharts.com/maps/modules/map.js

**Comment by bre1470** [comment]
Okay, but that comes from `js/masters` which does not make use of the empty one in `js/modules`.

**Comment by jon-a-nygaard** [comment]
Yes, the [js/modules/map.src.js](https://github.com/highcharts/highcharts/blob/7df1899ad9bdae2fee39064870d00e2da2c5de1f/js/modules/map.src.js) can be deleted. If there is any references to this file, then they should be removed as well to avoid something breaking.
