### ISSUE TITLE
Can't get highcharts to recognise license key in appsettings.json

### ISSUE THREAD

**Issue by NibblyPig** [highcharts/highcharts#11610]
Now that this is available for .NET Core, we'd like to put the license key into the `appsettings.json` file, but I can't find any information about if this is possible. A .net core project doesn't have a web.config so cannot put it in there as a key value pair.

Could this be added as an option and/or the documentation expanded to explain how we can configure this?

**Comment by pawelfus** [comment]
Hi @NibblyPig 

Thanks for reporting the issue - you are right, we are missing this info in out docs.

You can add your key this way:
> var renderer = new HighchartsRenderer(chartOptions, _your_license_key_);

We will update our docs, thanks again!

**Comment by NibblyPig** [comment]
Do you have any plans to allow it to be stored in a global variable within appsettings? It would make it a bit easier than specifying it each time.

**Comment by pawelfus** [comment]
Good idea, we will add it too. Thanks again!

**Comment by bre1470** [comment]
With the recent license changes the latest products include the official wrappers. Therefor a product key is not required anymore: https://www.nuget.org/packages/Highsoft.Highcharts/
