### ISSUE TITLE
Polar chart with arearange series not working as expected

### ISSUE THREAD

**Issue by tomaslevin** [highcharts/highcharts#11627]
#### Expected behaviour
Rendering the area range series in polar chart correctly.
In the given example should be only one colored area.

#### Actual behaviour
The polar arearange series has two areas which are rendered.
Notice that only the 'real' area has tooltips and so on, and the 'mistake' one doesn't have them.

#### Live demo with steps to reproduce
https://jsfiddle.net/ofdLzw2s/1/

#### Product version
all (I think)

#### Affected browser(s)
Checked on Chrome.

**Comment by pawelfus** [comment]
Thank you for reporting the issue @tomaslevin 

Simplified demo: https://jsfiddle.net/BlackLabel/0dcny314/ - we can observe "two" issues here: `connectNulls` and `connectEnds` does not end graph correctly.

**Comment by khlieng** [comment]
Fixed since 8.2.0 (#13921).
