### ISSUE TITLE
Highstock - xrange series - tooltip issue

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#11625]
The split tooltip in Highstock doesn't work properly for xrange series when point has the same initial x value. 

#### Live demo with steps to reproduce

[Demo](https://jsfiddle.net/BlackLabel/3c8g6dma/) showing the issue. 

#### Product version

Highcharts JS v7.1.2 (2019-06-03)

#### Affected browser(s)

All

**Comment by pawelfus** [comment]
It's a general issue with split/shared tooltip for multiple points with the same x: https://jsfiddle.net/BlackLabel/qh62451e/

**Comment by clarghi** [comment]
Hi,
I have this problem too: if the start datetime is the same the tooltip is showed always for the first (last if not reversed) point.
Used latest version of highstocks.
P.s. I'm a licensed user.
Demo: https://jsfiddle.net/clarghi/v80ea27z/15/
Thank's.
