### ISSUE TITLE
Bubble chart with identical series.data (overlapping)

### ISSUE THREAD

**Issue by Borovensky** [highcharts/highcharts#11628]
Hi there.
I'm stuck with one case on bubble chart. Will be very pleased for help or any suggestion to solve it.

#### Actual behaviour
In case I have the same size and coordinate for the series.data (it could be 2 or 100 bubbles) I have an access only to the top one (the last data serie in array).

In the live demo you can see that the tooltip is only for 'test4'.
So my question is how I can get access to the 'test1', 'test2'...e.t.?
Is there a way to change zIndex of the bubble by clicking on it? Or display the list of the series in the tooltip?

#### Live demo with steps to reproduce
https://jsfiddle.net/yj9r621m/15/

Thanks in advance

**Comment by pawelfus** [comment]
Hi @Borovensky 

Thanks for using Highcharts. You posted on our bug tracker - if you have questions, please other channel supports: https://www.highcharts.com/blog/support/

PS: One of possible solutions is to use [`series.jitter`](https://api.highcharts.com/highcharts/series.bubble.jitter), see demo: https://jsfiddle.net/BlackLabel/xwph3z4y/

**Comment by Borovensky** [comment]
@pawelfus Thanks for quick response!
