### ISSUE TITLE
Network Graph Nodes Are Cutoff at the Edges

### ISSUE THREAD

**Issue by l2silver** [highcharts/highcharts#11632]
#### Expected behaviour
Nodes will not be cutoff.

#### Actual behaviour
Nodes are cutoff

#### Live demo with steps to reproduce
https://jsfiddle.net/95czybet/4/

If you run the fiddle, the top most node is cutoff. It slowly drops down after a few seconds so that it isn't cut off, however if the version that I'm running on my app, it stays up. Not sure what the difference is as the config I provided is the JSON.stringified config that I'm using on my app.

#### Product version
Highcharts 7.1.2

#### Affected browser(s)
Tested on Chrome

**Comment by pawelfus** [comment]
Thanks for reporting the issue @l2silver 

**Workaround:**
Set [`chart.margins`](https://api.highcharts.com/highcharts/chart.margin) to the same value as `marker.radius` (or the largest radius of markers): https://jsfiddle.net/BlackLabel/xtfewh2r/

Simplified demo: https://jsfiddle.net/BlackLabel/vn04a1gb/
