### ISSUE TITLE
Scrolling doesn't trigger tooltip hide when cursor leaves the chart's container

### ISSUE THREAD

**Issue by siddarthkanted** [highcharts/highcharts#11635]
#### Expected behaviour
1. consider there are 10 charts in one page from top to bottom.
2. Now scroll the page multiples time top to bottom using mouse wheel
3. All the tool-tips get clustered and do not disappear.

#### Actual behaviour
1. Tool tips should disappear and do not get clustered

#### Product version
    "highcharts": "7.1.2",

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @siddarthkanted,
Thank you for reporting about the bug. Unfortunately I was not able to reproduce the issue in simplified demo: https://jsfiddle.net/tskphz7L/2/.

Could you update my code with your simplified demo for the further debugging?

**Comment by siddarthkanted** [comment]
Hey @sebastianbochan I cannot reproduce in JSFiddle, the issue that I see is "there are around 10 charts in one page. While moving from one chart to second, the tooltip of 1st chart does not disappear"
http://jsfiddle.net/highcharts/VqruM/

![image](https://user-images.githubusercontent.com/13218256/62772521-69e96700-babd-11e9-8031-833f46fe9d47.png)

**Comment by pawelfus** [comment]
Hi @siddarthkanted 

Without live demo we won't be able to debug and fix the issue. If you're not able to recreate the issue then please do the following:
- double check Highcharts version - maybe it's a bug in old version
- check installed Highcharts modules - maybe one of them is broken
- remove custom code (e.g. third party plugins) for Highcharts - maybe one of the plugins overwrites `Tooltip.prototoype.hide` method
- check [`tooltip.hideDelay`](https://api.highcharts.com/highcharts/tooltip.hideDelay) - maybe it's a big number
- check CSS, maybe something interferes with events (unlikely)

**Comment by jacknkandy** [comment]
@pawelfus Hi, I am also having this issue, I can understand @siddarthkanted difficulty in creating a JSFiddle to demonstrate this issue as it only occurs in specific circumstances.

I have modified the JSFiddle he has provided to make it easier to demonstrate the issue under such conditions - https://jsfiddle.net/g3s1po02/.

In order for this issue to occur, you need to perform the following steps:

- Hover over a chart's series so the tooltip appears
- Quickly scroll to a chart before the first tooltip disappears in such a way that the mouse will end up being on top of a series on the second chart (its easier to reproduce when the data points of each series line up horizontally so the mouse hover event gets immediately triggered on the second chart's series)
- This will cause the second tooltip to toggle, but the old one will be stuck and wont automatically hide

This screenshot shows the issue as it is occurring within our project:

![image](https://user-images.githubusercontent.com/40873630/64321725-7ac9c180-d004-11e9-86bb-20154c9dfcb5.png)

It is also reproducible using the JSFiddle provided above:

![image](https://user-images.githubusercontent.com/40873630/64321782-9c2aad80-d004-11e9-9d39-a94e59095887.png)

In both screenshots, the mouse is hovering over the second chart, but as you can see the first tooltip is still stuck showing. Once you move the mouse off the second chart, the first tooltip is still stuck:

![image](https://user-images.githubusercontent.com/40873630/64321941-e57afd00-d004-11e9-917d-0d9c5dc3e383.png)

The only way to get the stuck tooltip to disappear, is to hover back over the series and then move the mouse out of the chart.

**Comment by KacperMadej** [comment]
@jacknkandy 

Please add a screen recording and information about used OS and browser (names and versions).

**Comment by jacknkandy** [comment]
Hi @KacperMadej 

No problem please see the screen recordings below:

As it appears in our project (obvious there is some customisation here):
![ee-tooltip-bug](https://user-images.githubusercontent.com/40873630/64397875-2414c400-d0a6-11e9-95f4-d17634234a29.gif)

As it appears in a minimal reproducible example (as per the JSFiddle above):
![jsfiddle-tooltip-bug](https://user-images.githubusercontent.com/40873630/64398065-d187d780-d0a6-11e9-818d-d543cc646830.gif)

I'm running Windows 10 (1709) and the issue appears in Chrome 74.0.3729.131 as well as Firefox 68.0.1.

Cheers!

**Comment by KacperMadej** [comment]
Thank you for the full explanation. I have updated the issue title and labels.

**Comment by Denyllon** [comment]
+1
