### ISSUE TITLE
Highstock datepicker example using angular 7 & typescript

### ISSUE THREAD

**Issue by rammohangowdt** [highcharts/highcharts#11633]
I am looking for Highstock datepicker examples using Anular7 & typescript. I could see few examples, but they are using jquery.

> https://jsfiddle.net/BWEm5/611/

would like to check if there are any examples available using Angular7 & typescript with datepicker(if I select some date or changinging range selector should trigger an event to call service).

**Comment by sebastianbochan** [comment]
Hi @rammohangowdt,
Thank you for contacting us. The github is our bug tracker for reporting issues. Please use one of our [channels](http://www.highcharts.com/support) for support questions.
