### ISSUE TITLE
Highcharts demo responsive

### ISSUE THREAD

**Issue by mkloar** [highcharts/highcharts#11652]
#### Expected behaviour
I think a chart would be nice to be responsive in your demo responsive website.

#### Actual behaviour
Bug on your main demo website;[Highcharts demo responsive]( https://www.highcharts.com/demo/responsive)
The chart is not responsive when switching between large and small chart.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/responsive

#### Affected browser(s)
Google Chrome

**Comment by sebastianbochan** [comment]
Hi @mkloar,
Thank you for reporting about the bug. We will fix it as soon as possible.

**Comment by TorsteinHonsi** [comment]
This has already been fixed in the master, will be part of the upcoming release this week. See https://jsfiddle.net/highcharts/xs7may56/
