### ISSUE TITLE
solid-gauge point's width cannot be set as pixels

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#11659]
#### Expected behaviour
In docs, it is written that we can set the size of below properties in **pixels**
- yAxis.tickLength
- pane.size
- pane.background.innerRadius
- pane.background.outerRadius
- series.radius
- series.innerRadius

#### Actual behaviour
Below properties read **percentage size only**
- series.radius
- series.innerRadius

![gauge](https://user-images.githubusercontent.com/23310742/62858426-93430680-bcfa-11e9-9029-f478f3763f76.PNG)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/rzn2s0kb

#### Product version
7.1.2

**Comment by pawelfus** [comment]
*Internal note:*

Seems to be a bug in docs, since `point.radius` and `point.innerRadius` were implemented, these values always were percentage values (f5eaf47da92c797d5e35643dfeb5c5ef7b8e5f36).
