### ISSUE TITLE
Heatmap data overflow

### ISSUE THREAD

**Issue by mkloar** [highcharts/highcharts#11658]
If I resize my browser window I have problem with data overflow in heatmap chart.
![Screenshot from 2019-08-12 11-09-02](https://user-images.githubusercontent.com/17946736/62855298-2af02700-bcf2-11e9-9123-a7d2636f03dd.png)

#### Actual behaviour
I need to center data inside highcharts-data-label with my custom CSS.

I tried this when window width is less than 800px:
```
@media (max-width: 800px) {
    .highcharts-label.highcharts-data-label text {
        font-weight: normal !important;
        font-size: 8px !important;
        margin-left: -5px !important;
        padding-left: -3px !important;
        text-align: center !important;
    }
    .highcharts-data-label {
        margin-left:5px !important;
        margin-right: 5px !important;
        margin-left: -3px !important;
        text-align: center !important;
    }
}
```

#### Product version
v5.0.14
#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Hi @mkloar 

Thanks for using Highcharts. Could you contact our support? See details: https://www.highcharts.com/blog/support/

You posted on our **bug tracker**.
