### ISSUE TITLE
Solid Gauge showing value when choosing zero mark

### ISSUE THREAD

**Issue by jak-ecoaxis** [highcharts/highcharts#11664]
#### Expected behaviour
In Solid gauge when he value is zero, choosing the mark (12' o clock position) is difficult for user to view the values.  We have tried a work around by plotting another layer in which case choosing the entire circle works for showing values.  But when we do this, we don't get the selected portion highlighted because there is a overlay on top of it.

Is there a way to show values in solid gauge when the entire circle is chosen instead of clicking only the highlighted portion?

#### Actual behaviour
If the value is zero, choosing the thin selected line/portion is very difficult to see the value.  Is there a way to see the value on mouse over or click on the entire circle irrespective of the selected portion?

#### Live demo with steps to reproduce
https://jsfiddle.net/teLuxobd/
(with the workaround implemented)

#### Product version
Latest
#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @jak-ecoaxis 

Thanks for reporting the idea. In your case I think you can simply reverse order of points, and get the desired result: https://jsfiddle.net/BlackLabel/qsj5f26u/

Additionally, you can also disable `inactive` state: https://jsfiddle.net/BlackLabel/qsj5f26u/1/

**Comment by jak-ecoaxis** [comment]
Hi @pawelfus 
Thank you and that helps.
