### ISSUE TITLE
Highstock - dynamically enabled rangeSelector - from and to issue

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#11669]
After dynamically enabling rangeSelector feature - "from" and "to" inputs labels doesn't work. 

Can be related to: [#10457](https://github.com/highcharts/highcharts/issues/10457), [#2210](https://github.com/highcharts/highcharts/issues/2210)

#### Live demo with steps to reproduce

[Demo](https://jsfiddle.net/BlackLabel/1eam524n/)

#### Product version

Highcharts JS v7.1.2 (2019-06-03)

#### Affected browser(s)

All

**Comment by TorsteinHonsi** [comment]
Also, the layout is not adjusted to make room for the range selector. I have tested old versions, it seems like this never worked.

A *partial workaround* is to initialize the chart with the range selector enabled, then immediately disable it. It resolves the problem with _from_ and _to_ input boxes, but not the layout problem: https://jsfiddle.net/highcharts/92g6ufam/4/.
