### ISSUE TITLE
ColorAxis update test fails in Windows 7 Chrome 76

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#11666]
Chrome 76.0.3809 (Windows 7.0.0) Highcharts Color axis updates FAILED
        Geometry ok after resize (#6025)
        Expected: 151
        Actual: 150
            at Object.<anonymous> (http://utils.highcharts.local/samples/#test/unit-tests/coloraxis/coloraxis-update)
            at runTest (node_modules/qunit/qunit/qunit.js:3044:30)
            at Test.run (node_modules/qunit/qunit/qunit.js:3030:6)
            at node_modules/qunit/qunit/qunit.js:3257:12
            at processTaskQueue (node_modules/qunit/qunit/qunit.js:2623:24)
            at node_modules/qunit/qunit/qunit.js:2627:8

**Comment by bre1470** [comment]
Unit test fails in the current master. Windows 10 Chrome 76 has no issue.

**Comment by bre1470** [comment]
Windows 10 variant is now failing too.

**Comment by bre1470** [comment]
Issue was probably on BrowserStack environment. Retesting every commit now succeeds.

**Comment by TorsteinHonsi** [comment]
This still happens from time to time in the Circle tests. I am able to reproduce it on BrowserStack from time to time using Windows 10 and Chrome 76. Start utils by `sudo node server --emulateKarma`, then open http://utils.highcharts.local/samples/#test/unit-tests/coloraxis/coloraxis-update in the remote browser. It fails about 20% of the time.

**Comment by TorsteinHonsi** [comment]
Traced the glitch back to [this line](https://github.com/highcharts/highcharts/blob/v7.2.0/ts/parts/Chart.ts/#L1244), where `getBBox` would usually return a height of 28, but occationally 28.03. Fixed by rounding the height.

**Comment by bre1470** [comment]
Maybe this comes from a slightly unfinished animation?

**Comment by TorsteinHonsi** [comment]
That may be, though at least in theory animation shouldn't run in the tests. Or a font that hasn't finished loading. 

But I think the fix is valid anyway, as a bounding box difference of 0.03 shouldn't result in a full pixel offset.
