### ISSUE TITLE
Highcharts legend: Customize legends on highcharts

### ISSUE THREAD

**Issue by JAISAIKIRANALLURI** [highcharts/highcharts#11663]
#### Expected behaviour
Can we create a button on highcharts to display the legends on click?

#### Actual behaviour
In the documentation, I didn't find any steps to perform the above behavior.

The feature as follows:
1. If the legends are overflown, i.e 50 or So, Since, we are displaying the legend in the horizontal layout we are getting them in 10 lines.
2. So, if the legend count is more than one line , we need to display the remaining legend i.e. from 2nd line to end on click of a button or some menu.
  
Will the above custom feature be possible?

**Comment by pawelfus** [comment]
Hi @JAISAIKIRANALLURI 

What you are looking for is [`legend.navigation`](https://api.highcharts.com/highcharts/legend.navigation), see demo: https://jsfiddle.net/BlackLabel/51mcvz70/

In case you have more questions, please contact our support first: https://www.highcharts.com/blog/support/ - you posted on our bug tracker :)
