### ISSUE TITLE
Don't change max value if user doesn't want this

### ISSUE THREAD

**Issue by dmitrygorbenko** [highcharts/highcharts#11678]
Hi,
I want to render solid gauge chart which shows percentage of some amount. And in my case it's 100% of some value (50 of 50).
Like the [speedometer](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/gauge-speedometer/) you have but without axes/ticks, just a circle.
Here what I have: https://jsfiddle.net/4ydm98ho/
Also I want to disable any ticks on Y axis and but disable the whole Y axis I can't because I need to see the title on this axis.

In HC's source code I found next lines:
```		                
this.transA *= (currentTickAmount - 1) / (tickAmount - 1);
this.min = tickPositions[0];
this.max = tickPositions[tickPositions.length - 1];
```
which changes the min/max values, so in my example the max became 60 and this is why I don't get full circle.

Can you introduce some setting which disables ticks completely ?

Thanks

#### Expected behaviour
Chart which has full (360 degree) blue circle, like here: https://jsfiddle.net/px36rLz1/

#### Actual behaviour
The highcharts library changes yAxis by changing max value provided by user and thus changes the chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/4ydm98ho/

#### Product version
7.1.2

#### Affected browser(s)
Any browser

**Comment by pawelfus** [comment]
Hi @dmitrygorbenko 

Thanks for reporting the issue. Personally, I never considered using `yAxis.tickAmount` to hide all ticks, I think it's much better to set `yAxis.tickPositions = []` instead, see: https://jsfiddle.net/BlackLabel/ru6nz1xo/ or simply remove `tickAmount = 0` from your config, then it looks as you described: https://jsfiddle.net/BlackLabel/asfow05b/

Setting `tickAmount` may cause the issue you have, see docs: [`yAxis.max`](https://api.highcharts.com/highcharts/yAxis.max): 
> If a tickAmount is set, the axis may be extended beyond the set max in order to reach the given number of ticks. 

Of course, you have zero ticks defined, then it's hard to reach that number..

**Comment by dmitrygorbenko** [comment]
I see, thank you, Pawel.
You are right, it works :)
I don't know what to say, except, thank you...
If I can suggest something I would say: can we add to
https://api.highcharts.com/highcharts/yAxis.tickPositions
more information about it's behavior ?
Something like next:
`If you specify an empty array when it would disable ticks at all and the min/max values will stay as were specified by options` ?

Anyway, thank you for helping me.

Dima
