### ISSUE TITLE
Tooltip markers won't disappear when tooltip disappears after zooming in and back out (accessibility v7.1.2)

### ISSUE THREAD

**Issue by MattF-NSIDC** [highcharts/highcharts#11679]
#### Expected behaviour

1) Zoom in on line
2) Zoom out
3) Hover over the portion of the line that was previously in the zoomed frame
4) See tooltip
5) Move mouse
6) Tooltip disappears, along with its marker

#### Actual behaviour

1) Zoom in on line
2) Zoom out
3) Hover over the portion of the line that was previously in the zoomed frame
4) See tooltip
5) Move mouse
6) Tooltip disappears but marker remains
7) More markers keep accumulating as you move the mouse

#### Live demo with steps to reproduce

https://jsfiddle.net/ysjn8Laf/7/

Follow the steps above, but change the version of the accessibility module from 7.1.2 to 7.1.1 and observe the difference. With 7.1.2 markers accumulate, but do not with 7.1.1.

https://media.giphy.com/media/SUp3OxrDzOQnNad5VN/source.gif

I apologize for the janky recording. My screen recorder seems to be dropping some frames.

#### Product version

Highcharts Accessibility v7.1.2
Highcharts v7.1.2 works perfectly with Accessibility v7.1.1.

#### Affected browser(s)
Chromium Version 75.0.3770.100 (Official Build) Arch Linux (64-bit)
Firefox 68.0.1 (64-bit)

All of my co-workers are able to repro this on their various browsers, so I think most browsers would be impacted.

**Comment by pawelfus** [comment]
Thanks for reporting the issue @MattF-NSIDC - we really appreciate all of the details! Could you test our master branch (candidate for v7.1.3): https://jsfiddle.net/BlackLabel/nxd2wq8b/ ? It seems that bug is already fixed and should be part of the next release (this week) :)

**Comment by MattF-NSIDC** [comment]
@pawelfus Happy to! Thank you for the response and for your work.

That fiddle works perfectly fine for me with the master branch bundle! Glad to see it's fixed in the next version; we'll be sure to upgrade when that's out.
