### ISSUE TITLE
Not fit parent container in Firefox when resizing

### ISSUE THREAD

**Issue by smokir** [highcharts/highcharts#11684]
#### Expected behaviour

Fit container when resizing as it does in Chrome and Safari.

#### Actual behaviour

When resizing chart in Firefox it can grows in height but not decreasing (right scroll appears near chart). 
Works fine in Chrome and Safari.

![screencast 2019-08-14 19-52-01](https://user-images.githubusercontent.com/2204174/63040145-83c7e700-becd-11e9-9a35-c77ef64d350c.gif)

First part in Firefox and then switching window to Chrome.

#### Live demo with steps to reproduce
https://jsfiddle.net/nkvczr9o/

#### Product version
Highcharts 7.1.2

#### Affected browser(s)
Firefox 68.0.1 (64) / 68.0.2 (64)

**Comment by pawelfus** [comment]
Thanks for reporting @smokir 

For me it works the same for Chrome - height is increased, never decreased. Tested with Chrome Version 76.0.3809.100 (Official Build) (64-bit):

![height](https://user-images.githubusercontent.com/1453926/63165551-141c3e00-c02c-11e9-8533-6bbe598f3db6.gif)

**Comment by TorsteinHonsi** [comment]
This is caused by the chart itself blocking the container div from being shrunk. 

#### Workaround
Set `position:absolute` and a percentage width and height. https://jsfiddle.net/4Lfrqxzb/
