### ISSUE TITLE
scrollablePlotArea and drilldown button position

### ISSUE THREAD

**Issue by fpsoto** [highcharts/highcharts#11687]
When I click on the bar of the chart, back button to return to the previous level appears in the upper left corner, which if there are many elements disappears from the view when moving the 
horizontal scroll, I need that the button can be fixed in the same corner of the chart widget.

![image](https://user-images.githubusercontent.com/17752806/63047976-844b8800-bea3-11e9-99f3-7a98d5958de3.png)

Please check my demo with the same bug when you click a bar in the chart = > 
 https://jsfiddle.net/x7w09u6j/1/

I'm working with the following versions of HC => "highcharts": "^7.0.3" &
"highcharts-angular": "^2.4.0" (angular 7 +.net core development)

This bug happens in Chrome, Safari in my case.

**Comment by pawelfus** [comment]
Thanks for reporting the issue @fpsoto
