### ISSUE TITLE
onMouseOver throws an error if tooltip.outside is true

### ISSUE THREAD

**Issue by ThomasHickman** [highcharts/highcharts#11688]
If onMouseOver is called with no arguments, it doesn't call `normalize`, so `this.chartPosition` doesn't get set and https://github.com/highcharts/highcharts/blob/42ff5c66cb0144da2c1576b73ed11e05b7fce4f3/ts/parts/Tooltip.ts#L856
then errors.

#### Live demo with steps to reproduce
https://jsfiddle.net/t6fovums/1/

* Click on "onMouseOver"
* Check the console and there's an error

#### Product version
Highcharts v7.1.3
#### Affected browser(s)
All supported browsers (that I can see)

**Comment by sebastianbochan** [comment]
Hi @ThomasHickman,
THank you for reporting about the problem.

**Internal note**
It looks like that `chart.tooltip.refresh()` is also broken.

Demo:
- https://jsfiddle.net/BlackLabel/19rdkup4/
