### ISSUE TITLE
Highcharts pie chart titletext suddenly positioned higher

### ISSUE THREAD

**Issue by lonika62** [highcharts/highcharts#11696]
#### Expected behaviour
I use multiple highcharts pie charts, where I use the title-text positioned in the middle. Because I use a very small chart and large text, it's position is pretty important.

#### Actual behaviour
Since yesterday all my title text spans are suddenly positioned about 10px higher.. 

I saw there has been an update..
Is this a bug that will be fixed.. or is it just new?

**Comment by sebastianbochan** [comment]
Hi @lonika62,
Thank you for contacting us. I was not able to reproduce the issue by this demo: https://jsfiddle.net/BlackLabel/e5otnzbk/. Could you update my jsfiddle with your chart's options? It will allow me to reproduce and debug the problem.

**Comment by TorsteinHonsi** [comment]
Here's the reproduction: 
https://jsfiddle.net/highcharts/mfgbr105/2/

Here's how it was with v7.1.2:
https://jsfiddle.net/highcharts/mfgbr105/3/

As you can see, in the new release, the title is positioned more correctly in the middle. In the old version, the title would be aligned by its top line, so a `verticalAlign` to `bottom` would actually render it below the chart. As a result, it had to be adjusted using the `y` option. I added an upgrade note to the changelog, commit coming soon.

**Comment by lonika62** [comment]
I see.. for my charts.. I now have to adjust all the y positions to get it right ;)

https://jsfiddle.net/Lonneke/g0u4y9e5/
