### ISSUE TITLE
Highchart 7.1.3. tooltip width smaller than a tooltip content

### ISSUE THREAD

**Issue by binasm** [highcharts/highcharts#11698]
#### Expected behaviour
Hovering over tooltip at Highcarts 1.4.8. was behaving like this: 
http://prntscr.com/ot1am4

#### Actual behaviour at Highcharts >6.1
http://prntscr.com/ot1av0
tooltip options:
http://prntscr.com/ot1bfr

#### Product version
Highcharts 7.1.3

#### Affected browser(s)
Chrome, Firefox, Edge...

**Comment by sebastianbochan** [comment]
Hi @binasm,
Thank you for reporting about the problem. In the current version you can use [tooltip.outside](https://api.highcharts.com/highcharts/tooltip.outside) option to show regular witdth of tooltip too.

Let me know if all worked properly.

**Comment by binasm** [comment]
Hi @sebastianbochan,

Thank you for your answer. But... As you can see in my screenshot above, I already do use tooltip.outside option and it's set to true: https://prnt.sc/ot1bfr. So, the issue is not that tooltip is not shown, it is, but it's cropped (its width is less than a content width: https://prnt.sc/ot1av0 for an example "1,021%" and ".. TG" part of "Symmetry TG" string are out of borders).

Is there any workaround here I can use in order to make it look as in previous version (whole content of tooltip inside borders as it should be) ?

Thanks in advance!

**Comment by TorsteinHonsi** [comment]
@binasm Can you share a live demo with us? It is hard for us to guess what goes wrong without actually being able to see and debug it. My guess is that is has to do with loading of web fonts - maybe the bounding box is computed before the font is rendered, then when the font arrives async, the text overflows. But that is just a guess.

**Comment by binasm** [comment]
Hey @TorsteinHonsi , thanks, I understand...

Here is the screenrecording: https://xfl.jp/muvHxg showing that in other parts of application tooltip behaves fine, but when outside property is enabled, it gets broken. So it's probably less likely that this has to do something with a font rendering?

(If this does not work, I can try to make js fiddle so you can try to debug it)

**Comment by TorsteinHonsi** [comment]
Thanks for the screen recording! It helps me understand how the issue manifests, but we still need to see it live in order to debug, and bisect if it is a regression.

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
