### ISSUE TITLE
More than one `select` doesn't work when using a shared graphic in setState

### ISSUE THREAD

**Issue by ThomasHickman** [highcharts/highcharts#11693]
If you have a graph with a where `setState` uses a shared graphic, the second call onwards of `select` doesn't do anything.

#### Live demo with steps to reproduce
https://jsfiddle.net/qbwc0g6f/
* Click select
* No points are selected

#### Product version
Highcharts v7.1.3

#### Affected browser(s)
I tested this on chrome 76

**Comment by ThomasHickman** [comment]
I've just investigated this further, and this bug still occurs when you don't have points marked for each point (i.e. setState uses a shared graphic), so I've updated the description accordingly

**Comment by pawelfus** [comment]
Thanks for reporting the issue @ThomasHickman 

You are right, when markers are disabled, only shared marker is available, so selecting multiple points within the same series is not supported. Workaround is to enable very small markers for all points instead, take a look: https://jsfiddle.net/BlackLabel/20b1e5a7/

Downside of this solution is missing default feature (`enabled = undefined` means to automatically hide/show markers when data is dense/widespread).
