### ISSUE TITLE
Organization HighChart error for same column relations

### ISSUE THREAD

**Issue by DPareshB** [highcharts/highcharts#11702]
Details:
In Organizational Highcharts,for some particular kind of from and to relations the graph is not getting displayed and it throws an error in the console. Though with the same codebase and just reversing that particular relation the graph gets displayed.

Expected behaviour:
Organizational Highchart should be displayed

Actual behaviour:
no chart is displayed. Console gives an error:"Cannot read property 'states' of undefined"

#### Live demo with steps to reproduce
https://jsfiddle.net/6k97xcrw/7/

In the above Example if we reverse just a single from, to relation( ["13", "10"] -->  ["10", "13"] in line 26) the chart is displayed.

#### Product version
Highcharts_version- 7.1.2
Angular version- 6.1.1

**Comment by pawelfus** [comment]
Thank you for reporting the issue @DPareshB 

Simplified demo: https://jsfiddle.net/BlackLabel/t68xjedy/
