### ISSUE TITLE
Implement levels in dependency wheel chart (sunburst)

### ISSUE THREAD

**Issue by amyspark** [highcharts/highcharts#11706]
#### Expected behaviour
Add a parent to each node and have the dependency wheel group nodes by the specified parent (as in the sunburst chart). This should also accumulate the values of the links.

#### Actual behaviour
The parents can be added, but they are not recognised by the chart. They are not rendered either.

#### Live demo with steps to reproduce
https://jsfiddle.net/v3tdo2rh/

#### Product version
Highcharts 7.1.3

#### Affected browser(s)
Tested in Firefox 70.0a1 (2019-08-15) (64-bit) in Windows 10 1903.

**Comment by pawelfus** [comment]
Thanks for sharing your idea!

Could you also create a ticket for that on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api) ? The most popular ideas are often implemented in the core. Thanks once again!
