### ISSUE TITLE
Typings for Axis don't include defaultLabelFormatter (or other inherited props)

### ISSUE THREAD

**Issue by mniebling** [highcharts/highcharts#11705]
#### Expected behaviour
When trying to use an axis label formatter in a Typescript project, as per the [docs](https://api.highcharts.com/highcharts/yAxis.labels.formatter), `defaultLabelFormatter` should be available on `this.axis` inside the formatter.

#### Actual behaviour
It _is_ available and the code does work, but the TS compiler complains because the typings don't include the properties inherited from the prototype.

#### Live demo with steps to reproduce
https://stackblitz.com/edit/typescript-m9f8uc

(I couldn't get type errors to appear in JSFiddle even with the TS option turned on.)

#### Product version
Highcharts 7.1.3

#### Affected browser(s)
n/a

**Comment by pawelfus** [comment]
Thanks for reporting this issue!

**Comment by bre1470** [comment]
@TorsteinHonsi Axis.defaultLabelFormatter is half official in the API documentation. (1) If we like to support it completely, we have to make it here public: https://api.highcharts.com/class-reference/Highcharts.Axis (2) Otherwise we have to do a workaround with special Axis interfaces.

**Comment by mniebling** [comment]
Nice, thanks for the fix!
