### ISSUE TITLE
Combining columnrange and column causes imprecise rendering

### ISSUE THREAD

**Issue by jarib** [highcharts/highcharts#11711]
#### Expected behaviour

In a `column` chart I'd like to visualize error margins using a `columnrange`. The error margins should be precisely rendered, with equal height above and below the end of the column.

#### Actual behaviour

The `columnrange` is higher above the end of the column than below. The problem appears to become worse for lower values. The black and red box has equal height in this image:

![image](https://user-images.githubusercontent.com/572/63274196-a8daa200-c29f-11e9-95ff-f57df37e8069.png)

#### Live demo with steps to reproduce

https://codepen.io/jarib/pen/NWKRrNw

#### Product version

7.1.3 

#### Affected browser(s)

Observed in Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Hi @jarib 

Thank you for reporting the issue. This is actually caused by crisping logic for column series. In column series, columns are rounded to the nearest full pixel. In column-range series, values low and high are rendered with exact position (e.g. 19.2234234px).

**Workaround:**
Remove crisping logic: 
```js
Highcharts.seriesTypes.column.prototype.crispCol = function (x, y, w, h) {
  return {
    x: x,
    y: y,
    width: w,
    height: h
  };
};
```

Demo: https://jsfiddle.net/BlackLabel/q34yLgaz/

**Comment by jarib** [comment]
Thanks!

**Comment by jarib** [comment]
Actually, I'll let you decide if this should be closed :)

**Comment by pawelfus** [comment]
It might be a good idea to keep this open - if other users encounter this issue, and post here, then we should really consider improving the current solution :)

**Comment by jarib** [comment]
I noticed https://api.highcharts.com/highcharts/plotOptions.column.crisp – perhaps the real bug is that this doesn't do the same as modifying the prototype?

**Comment by pawelfus** [comment]
`crisp` option only affects `x` and `width` values of the shape and is recommended for dense datasets:
> In some cases, when there are a lot of densely packed columns, this leads to visible difference in column widths or distance between columns. In these cases, setting crisp to false may look better, even though each column is rendered blurry.
