### ISSUE TITLE
In logarithmic chart with only one category with value as 650, the yaxis label shows 650.0000000001 instead of 650

### ISSUE THREAD

**Issue by sunilkumarkakarlapudi** [highcharts/highcharts#11727]
#### Expected behaviour
Yaxis label should have 650

#### Actual behaviour
Yaxis label shows 650.0000000001

#### Live demo with steps to reproduce
https://cloud.highcharts.com/edit/243992

#### Product version
latest version

#### Affected browser(s)
All browsers i presume

**Comment by pawelfus** [comment]
Thanks for reporting the issue @sunilkumarkakarlapudi 

** Simplified demo:**
https://jsfiddle.net/BlackLabel/04j5rs6w/
