### ISSUE TITLE
Labels stop cropping after chart.redraw

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#11722]
Hello.

After calling chart.redraw(); labels on xAxis stop cropping.

![1](https://user-images.githubusercontent.com/6030335/63335011-463be180-c345-11e9-9ef4-dfef8ce23e4a.gif)

#### Expected behaviour
Words leave the same as like before `redraw`

#### Actual behaviour
Labels stop cropping.

#### Live demo with steps to reproduce
https://jsfiddle.net/86qag7ty/

#### Product version
Highcharts 7.1.3

#### Affected browser(s)
Google Chrome 76.0.3809.100

**Comment by sebastianbochan** [comment]
Hi @balkarov,
Thank you for reporting about the problem.

As a solution you can set the HTML labels with declared CSS ellipsis.

Demo:
- https://jsfiddle.net/BlackLabel/edzb0ufo/

**Comment by balkarov** [comment]
But now all labels in left position

**Comment by sebastianbochan** [comment]
Hi @balkarov,
Thank you for the feedback.

You can try to set `step: 1` and avoid rotating labels.

Demo:
- https://jsfiddle.net/BlackLabel/secfw69u/

Please be aware that it is only workaround (not full complex solution) which can be limited in some cases.

**Comment by balkarov** [comment]
Hello. When you fix the bug?

**Comment by sebastianbochan** [comment]
Hi @balkarov,
At this moment we do not have official ETA for fixing this bug. Have you tried to used workaround from my previous post?

**Comment by balkarov** [comment]
@sebastianbochan I tried, but sometimes I need rotating labels.

**Comment by sebastianbochan** [comment]
Hi @balkarov,
Currently, I set the higher priority for this bug.

**Comment by Basts** [comment]
@sebastianbochan 

It seems that in the current version it works fine: https://jsfiddle.net/BlackLabel/t3y4kxzg/

**Comment by sebastianbochan** [comment]
@Basts confirm.

@balkarov could you also confirm that all works properly in your scenarios?

**Comment by pawelfus** [comment]
Closing. If any further information will be available, please share (e.g. demo of an issue).
