### ISSUE TITLE
Sunburst - Missing point data for dataLabels formatter when using typescript.

### ISSUE THREAD

**Issue by samwilcock** [highcharts/highcharts#11732]
I have recently convered a project to typescript from vanilla javascript that uses the Sunburst graph. I am hvaing issues with the dataLabels formatter. 

#### Expected behaviour
When using the vanilla javascript version of my project I was able to access the point for each dataLabel through this.point so I could format it however I wanted. Using conditions to change the labels depending on the value from a collection of radio buttons.

#### Actual behaviour
Now when using typescript I lose the ability to use this.point in the dataLabels formatter in the series object. 

#### Live demo with steps to reproduce
https://jsfiddle.net/8vwg3zyq/1/

The demo shows the structure of the dataLabels formatter for the series with this.point that was working when using vanilla JS and now fails with TS. 

#### Product version
Highcharts 7.1.3
Vue (latest)
Typescript(latest)

#### Affected browser(s)
All Browsers.

**Comment by pawelfus** [comment]
Hi @samwilcock 

Thanks for reporting the issue. I'm not sure if this is the issue in demo, but in general:
```js
      formatter: () => {
        return store.getters.getSimpleNodeFormat(this.point);
      }
```

Won't work - see: https://jsfiddle.net/BlackLabel/6Lv4ow9z/ - `p` will always be undefined in this case, because `this` in arrow function refers to the originating context, which in demo will be `window`. 

@bre1470 - could you take a look? Thanks!

**Comment by bre1470** [comment]
Accessing `this` in an arrow function reports TypeScript in strict mode as failure and is right about it. Arrow functions always lack their own scope of `this`. This does not work and has to be written as a regular function like
```
formatter: function () {
    return store.getters.getSimpleNodeFormat(this.point);
}
```

**Comment by samwilcock** [comment]
This worked great thanks. I didn't releasie that arrow functions lacked their own scope of this. Thank you for your help @pawelfus @bre1470
