### ISSUE TITLE
Treemap - update issue when same amount of points

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#11738]
Update feature doesn't work in the case of updating the same amount of points as the number of points for initial series.

Last working version is 7.0.3 - [demo](https://jsfiddle.net/BlackLabel/pxdjk4yo/)

#### Live demo with steps to reproduce

[Demo](https://jsfiddle.net/BlackLabel/8ux9j7d4/)

#### Product version
versions > 7.0.3

**Comment by Rojuinex** [comment]
Just wondering if there's a patch or a temporary fix for this issue that can be applied until it's merged in master? We have a dynamic component that changes size of a treemap and we are using features already in 7.2.0 that are not in 7.0.3. We tried downgrading but got a ton of type errors and lost some important features. It would be awesome if we can figure out how to patch this temporarily.

**Comment by pawelfus** [comment]
**Workaround:**
Instead of `series.update()` use `series.setData()`, demo: https://jsfiddle.net/BlackLabel/L18uyoex/

**Comment by Rojuinex** [comment]
> **Workaround:**
> Instead of `series.update()` use `series.setData()`, demo: https://jsfiddle.net/BlackLabel/L18uyoex/

I don't think that will actually work for us.  We're trying to call `chart.reflow()` when the size of it's container changes and that's what ends up breaking the colors.

**Comment by pawelfus** [comment]
Could you provide a demo? I will check this. Thanks!

**Comment by Rojuinex** [comment]
As I look into it deeper I think the issue has to do with the way HighchartsReact updates attributes.  This is our specific use case and here is a link to the JSFiddle with an example of what we're experiencing.  https://jsfiddle.net/91zn7vu2/

I think I could for now use `chart.setSize` as a work around.

**Comment by pawelfus** [comment]
Right, wrapper uses internally `chart.update()`. Following [the recommended way](https://github.com/highcharts/highcharts-react#optimal-way-to-update) to update a chart, we can avoid this issue: https://jsfiddle.net/BlackLabel/hcaftpLz/

**Comment by zachariahtimothy** [comment]
@pawelfus that is a good point but I believe a bug remains. I took your working fiddle and updated the series on the resize me and it demonstrates tree map losing color. 
https://jsfiddle.net/5hjr0318/

**Comment by pawelfus** [comment]
That's correct @zachariahtimothy, bug is still there

**Comment by wjhcc2018** [comment]
I had the same problem，in highcharts-vue，Is there a solution？

**Comment by pawelfus** [comment]
Bisected to commit 1fe7b090fc - but I believe this is the culprit commit: 1fe7b090fcc47050cdb2c10ab99e5965fbae0a38



**Workaround:**
Let me know if you find any issues with the workaround below:
Demo: https://jsfiddle.net/BlackLabel/p6kvnbed/

Plugin:
```js
(function(H) {
  H.wrap(
    H.seriesTypes.treemap.prototype.pointClass.prototype,
    'draw',
    function(p, options) {
      if (options.group) {
        options.group.survive = true;
      }

      return p.call(this, options);
    }
  );
})(Highcharts)
```

**Comment by wjhcc2018** [comment]
@pawelfus Thanks for answering my question，I found that version 7.1.2 did not have this problem,and I retracted the version to 7.1.2

**Comment by pawelfus** [comment]
That's interesting, for me v7.1.2 is broken too: https://jsfiddle.net/BlackLabel/p6kvnbed/2/
