### ISSUE TITLE
legend.itemStyle.width doesn't work in styled mode

### ISSUE THREAD

**Issue by Sdavletshina** [highcharts/highcharts#11734]
I am trying to set max width for the legend aligned to the right. 
Before switching to styled mode I used legend.itemStyle.width property and it worked perfectly, but now, legend takes all available space and squeezes my chart.
Please let me know if workaround exists 

#### Expected behaviour
Legend box should be aligned to the right and take 75px

#### Actual behaviour
Legend box takes all available space and squeezes the chart.

#### Live demo with steps to reproduce

http://jsfiddle.net/sabira/xmcqjnvg/49/
if you comment out styledMode property, it will show you expected result.
#### Product version
Highcharts 7.0.1

**Comment by pawelfus** [comment]
Hi @Sdavletshina 

Thank you for reporting the issue. This is expected behaviour - all styles options are not applied in styled-mode. For this particular case, you have an alternative: [`legend.itemWidth`](https://api.highcharts.com/highcharts/legend.itemWidth) which works in styled mode too: http://jsfiddle.net/BlackLabel/5yewqa3s/

**Comment by Sdavletshina** [comment]
Thank you!

**Comment by Sdavletshina** [comment]
I apologize, I think I made a mistake on explanation.
If I use itemStyle and set width property to 75px, and let's say my legend content would be 30px long, it will produce 30px legend box, but not 75px(so that means 75px is maxWidth for legend box), but in suggested approach with itemWidth property, it keeps 75px legend box even I have 30px content.
fiddle with <75px content using itemStyle http://jsfiddle.net/sabira/xmcqjnvg/56/
fiddle with >75px content using itemStyle http://jsfiddle.net/sabira/xmcqjnvg/58/
fiddle with <75px content styled mode/itemWidth http://jsfiddle.net/sabira/xmcqjnvg/61/
fiddle with >75px content styled mode/itemWidth http://jsfiddle.net/sabira/xmcqjnvg/63/

Hope it makes sense.

**Comment by Sdavletshina** [comment]
Thank you very much! Here is solution https://jsfiddle.net/BlackLabel/fpwdtghk/
