### ISSUE TITLE
positive and negative column/bar do not behave the same at the bottom

### ISSUE THREAD

**Issue by gangli2010** [highcharts/highcharts#1173]
If we set borderWith = 0, and <b>gridLineWidth =  1</b> we can see the "negative" bar bottom is covering half width of the "y=0" gridLine, but the "positive" bar bottom is covering the full width of the "y=0" gridLine. http://jsfiddle.net/99GbV/9/ (you need to look really close, or zoom in enough)

But if we set  <b>gridLineWidth =  4</b>, we can see that both positive and negative bar are covering half width of the gridLine. http://jsfiddle.net/99GbV/11/

Should both "positive" and "negative" bar bottom behave the same with different gridLineWidth setting?

**Comment by oysteinmoseng** [comment]
I think this works as expected now, within the restraints of pixel amounts. Both bars overlay the grid line, which is centered between the bars: http://jsfiddle.net/47z2f594/
