### ISSUE TITLE
Drilldown categories - cropped labels on inverted chart 

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#11736]
Drilldown categories - the xAxis labels are being cropped after initial load when the chart is inverted. They look fine after window resize.

#### Live demo with steps to reproduce

[Demo](https://jsfiddle.net/BlackLabel/7snzvetf/) with current version

It seems that v 5.0.14 is the last version when labels were rendered fine - [Demo](https://jsfiddle.net/BlackLabel/0m63zbj7/)

#### Product version
versions > 5.0.14

**Comment by pawelfus** [comment]
Closing as duplicate of #10531
