### ISSUE TITLE
tooltip date is not displayed in case of bubble graph

### ISSUE THREAD

**Issue by guptavirendra** [highcharts/highcharts#11747]

**Comment by guptavirendra** [comment]
Please look into urgent basis.

**Comment by guptavirendra** [comment]
class ToolTipProvider:ToolTipConfigurable, UserDefaultUnitConvertable {
    var toolTip: HITooltip {
        let tooltip = HITooltip()
        let  timeChoice = TimeGroupingChoice(index: 0, tittle: toolTipModelprotocol.groupBy!)
         tooltip.xDateFormat = timeChoice?.toolTipFormat
        /* if collection chart then show only tooltip*/
        if toolTipModelprotocol.collectionChart == true {
            tooltip.pointFormat = "{point.tooltip}"
        }else { /* if prefix available then add prefix*/
            if let _ = toolTipModelprotocol.tooltipPrefix, toolTipModelprotocol.tooltipPrefix?.count ?? 0 > 0 {
                tooltip.valuePrefix = toolTipModelprotocol.tooltipPrefix! + ":"
            }
            /* if suffix avilable then add suffixe*/
            if let _ = toolTipModelprotocol.tooltipSuffix {
              let unitConvertor = GraphUnitConverter(isMetric: isMetric, title: toolTipModelprotocol.collectionString[0] ?? "", unit: toolTipModelprotocol.tooltipSuffix ?? "", convertSugarUnit: convertSugarUnit, value:nil)
                tooltip.valueSuffix = " " + unitConvertor.getUnit()
            }
         if toolTipModelprotocol is GraphMaster {
                let graphData = (toolTipModelprotocol as! GraphMaster)
/* if collection type health tracker and has tooltip text then add with prefix and tooltip else show normal*/     if graphData.collectionType == "healthtracker"{
                    if let  graphArray = graphData.collections?.values {
                        if let graphdataArray = graphArray.first{
                        let filtered  =   graphdataArray?.filter({ (graphData) -> Bool in
                            var valueString = ""
                            switch graphData.tooltip!{
                            case .double( let x):
                                valueString = String(format:"%f", x)
                            case .string( let x):
                                valueString =  x
                            case .int(let x):
                                valueString = String(format:"%d", x)
                            }
                                return valueString.count > 0
                            })
                            if filtered?.count ?? 0 > 0{
                               tooltip.pointFormat = toolTipModelprotocol.tooltipPrefix! + ":" + "{point.tooltip}"
                            }else{
                                tooltip.pointFormat = "{point.y} "
                            }
                        }
                    }
                }else {
                     tooltip.pointFormat = "{point.y} "
                }
            }
        }
        return tooltip
    }
    private var toolTipModelprotocol:ToolTipModelProtocol
    init(toolTipModelprotocol:ToolTipModelProtocol) {
        self.toolTipModelprotocol = toolTipModelprotocol
    }
}

**Comment by guptavirendra** [comment]
When I used point.tooltip then in that case it was not displaying

**Comment by guptavirendra** [comment]
if marker appear then date is not displayed

**Comment by guptavirendra** [comment]
if bubble.name present then it was not appeared.

**Comment by guptavirendra** [comment]
![Image-1 (2)](https://user-images.githubusercontent.com/891554/63525340-2b22ca80-c51b-11e9-91e5-7903bd05e2da.jpg)

**Comment by guptavirendra** [comment]
Please do respond. it's urgent

**Comment by guptavirendra** [comment]
please

**Comment by pawelfus** [comment]
Hi @guptavirendra 

I think you posted on wrong repo, this is Highcharts.js repo, I think you use [Highcharts iOS](https://github.com/highcharts/highcharts-ios/).

**Comment by guptavirendra** [comment]
thanks
