### ISSUE TITLE
Treemap - data labels issue

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#11744]
In the treemap chart, long data labels are rendered wrong when useHTML feature is set to true. 

Last working versions, where data labels were rendered as users expect is 7.0.1 - [demo](https://jsfiddle.net/BlackLabel/572rya6b/)

Temporary [workaround](https://jsfiddle.net/BlackLabel/aqyjh7zu/). 

Could be related to: [#8160](https://github.com/highcharts/highcharts/issues/8160)

#### Live demo with steps to reproduce

[Demo](https://jsfiddle.net/BlackLabel/xc8zr7d2/)

#### Product version
versions > 7.0.1

**Comment by pawelfus** [comment]
Bisected to commit 1a37c04527

**Comment by KacperMadej** [comment]
If the style has `white-space` set to something that allows wrapping then it seems to render correctly: https://jsfiddle.net/BlackLabel/xc8zr7d2/1/
Closing as resolved, but could be reopened - if you have any relevant info please add a comment.
