### ISSUE TITLE
Pie chart - single datalabels - distance

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1174]
When you set "globally" distance, pie datalabels work fine, but when you would like to change set other distance for single datalabel then it is ignored.

http://jsfiddle.net/K2Un6/3/

**Comment by CinKon** [comment]
Still no fix here? :(
http://jsfiddle.net/j6gvxowx/1/

**Comment by highslide-software** [comment]
Are you asking for the x and y properties for individual labels?

**Comment by CinKon** [comment]
Yeah

**Comment by Izothep** [comment]
+1

**Comment by sebastianbochan** [comment]
+1

**Comment by PaulDalek** [comment]
+1
