### ISSUE TITLE
StyledMode + stackLabels error

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#11758]
yAxis.stackLabels combined with styledMode produce an error:
`30Error: <rect> attribute width: Unexpected end of attribute. Expected length, "".`

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/Lta2xdor

#### Product version
7.1.3

#### Affected browser(s)
All (chart is not displayed in FF at all)
Related to #10855

**Comment by markbailey1980** [comment]
I'm encountering this issue, any activity on this bug?

**Comment by pawelfus** [comment]
No ETA, but we definitively should fix this - no errors should be thrown.

*Internal note:*
Simplified to the renderer case: http://jsfiddle.net/BlackLabel/de5pwsq2/ - updating label's text (or other prop that forces `updateBoxSize`) **before** adding to the DOM cause the issue.

**Comment by davidje13** [comment]
This has also impacted our codebase. Any known workarounds while we wait for a fix? (other than disabling `styledMode`). Our tests fail if any console errors are logged, so we don't have the option to just ignore this.

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/d9r8qpzw/

Snippet:
```js
(function(H) {
  H.SVGElement.prototype.strokeWidth = function() {
    // In non-styled mode, read the stroke width as set by .attr
    if (!this.renderer.styledMode) {
      return this['stroke-width'] || 0;
    }
    // In styled mode, read computed stroke width
    var val = this.getStyle('stroke-width'),
      ret = 0,
      dummy;
    // Read pixel values directly
    if (val.indexOf('px') === val.length - 2) {
      ret = parseInt(val);
      // Other values like em, pt etc need to be measured
    } else if (val !== '') {
      dummy = H.doc.createElementNS('http://www.w3.org/2000/svg', 'rect');
      H.attr(dummy, {
        width: val,
        'stroke-width': 0
      });
      this.element.parentNode.appendChild(dummy);
      ret = dummy.getBBox().width;
      dummy.parentNode.removeChild(dummy);
    }
    return ret;
  };
})(Highcharts);
```

Note: Workaround is not perfect, may cause misplacements for wide borders.
