### ISSUE TITLE
Wrong path fill for small shape in Chrome 76.0.3809.100

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#11755]
#### Expected behaviour
As in other browsers (even older Chrome) - no path visible.

#### Actual behaviour
Probably this is a bug in Chrome version 76.0.3809.100
reported here: https://bugs.chromium.org/p/chromium/issues/detail?id=997104&can=2&q=svg%20wrong%20fill%20small%20path

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/kt674smz/15/

#### Affected browsers
In Chrome 76.0.3809.100 / Windows 10 the path is red.
Win10: FF, Edge, IE11 - no path visible.

**Comment by sebastianbochan** [comment]
Since Chrome 79.0.3945.88, the path is hidden and works like in other browsers.

Im closing this ticket. 

Please reopen when issue will be valid in other versions.
