### ISSUE TITLE
Documentation for the series.setState() API is inaccurate or incomplete

### ISSUE THREAD

**Issue by KevinFernandes** [highcharts/highcharts#11759]
The API documentation for the sereis.setState() API implies that thee are only two valid values for the state; "hover" and "undefined" (to return to normal).

[https://api.highcharts.com/class-reference/Highcharts.Series#setState](https://api.highcharts.com/class-reference/Highcharts.Series#setState)

Because the parameter is a "string", the documentation should list all possible states or at least reference another doc link that lists all possible states.

States that I am aware of so far are "hover", "inactive" and "normal".  There may be others as well.

The Typescript description for this type should also restrict the input to the valid list of strings that it can accept.

**Comment by sebastianbochan** [comment]
Hi @KevinFernandes,
Thank you for reporting about the problem.
