### ISSUE TITLE
Docs: Duplicate "marker" in Highcharts.PointOptionsObject?

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#11769]
At https://api.highcharts.com/class-reference/Highcharts.PointOptionsObject#low

![image](https://user-images.githubusercontent.com/33569/63634999-031e8e80-c623-11e9-8eb7-2efc10b98516.png)

I don't know the difference between PlotSeriesPointMarkerOptions and Highcharts.PointMarkerOptionsObject, so if they are meant to be two different types, then the anchor in the left-hand panel should be different (it's "#marker" for both).

**Comment by KacperMadej** [comment]
Hi @dandv 

Thank you for reporting the problem.

This issue has been resolved already through https://github.com/highcharts/highcharts/commit/33f47b068a6211e8d7008b065f1ea69fd803f795#diff-4f996a3dc66bf057d739082d2582c311

The changes will be visible with the next code release.
