### ISSUE TITLE
Raw embed code in Series concepts docs page

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#11768]
At https://www.highcharts.com/docs/chart-concepts/series:

![image](https://user-images.githubusercontent.com/33569/63634769-a15d2500-c620-11e9-9f57-3ec3ea72d243.png)

**Comment by KacperMadej** [comment]
Hi @dandv 

Thank you for reporting the problem.

This is a website issue and will be notified to our webmasters.

**Comment by KacperMadej** [comment]
Closing as resolved.
