### ISSUE TITLE
How to enable resize option for annotation shape

### ISSUE THREAD

**Issue by ShivaRam1989** [highcharts/highcharts#11763]
#### Expected behaviour
Currently we have annotations label shapes are like this 
![image](https://user-images.githubusercontent.com/47973853/63632866-798bb280-c65c-11e9-9325-efe63ba1d09a.png)

#### Actual behaviour

I need the annotations labels to respond to resize option , that html provides like this
![image](https://user-images.githubusercontent.com/47973853/63632874-9b853500-c65c-11e9-9559-78ab65f4ba3f.png)

Could you please help out in achieving this ?

**Comment by sebastianbochan** [comment]
Hi @ShivaRam1989,
Thank you for using our annotations module. The github is our bug tracker so for general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.

ps. At this moment the option is not available yet, but you can post your suggestion in our uservoice here: https://highcharts.uservoice.com/
