### ISSUE TITLE
API documentation anchors lead to 404 page

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#11762]
Navigate to https://api.highcharts.com/class-reference/#toc5. After a second or two, the page redirects to a "Not found" https://api.highcharts.com/highcharts/toc5.

This happens in practice because the links to the left at https://api.highcharts.com/class-reference/ get indexed by Google and users may click them in search results:

![image](https://user-images.githubusercontent.com/33569/63631496-fa5f9580-c5ed-11e9-80bf-5a7f0b130247.png)

**Comment by dandv** [comment]
Turns out this happens in the more common scenario of simply browsing the documentation. Sorry if the issue has already been reported.

![Documentation 404](https://user-images.githubusercontent.com/33569/63633438-39054800-c60e-11e9-9219-d497ea00f7fb.gif)
* start at https://api.highcharts.com/class-reference/Highcharts
* search for `settitle`
* (separate issue: I wish I were able to click on the setTitle method from the results, but that doesn't work)
* click "Class: Chart" and use the browser's search function to find the setTitle method
* click "Highcharts.Chart#setTitle" under setSubtitle

Screecash attached.

**Comment by KacperMadej** [comment]
Hi @dandv 

Thank you for reporting the problem.

I have checked links with steps you have provided and even checked for the redirect starting from Google search, but everything works fine for me.
I am unable to recreate the problem, maybe this depends on the used browser and/or OS.
I have checked both issues using Chrome on Windows 10.

Please let us know which browser and OS have you used to get the problem and if you are able to recreate this case now.

**Comment by dandv** [comment]
I was using Chromium 76 on Linux, but I can no longer reproduce now (using the same browser/OS).

Hopefully a transient error that was fixed by some other update.
