### ISSUE TITLE
Docs: repeated mention of `type option must always be set` for TypeScript in line series docs

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#11772]
At https://api.highcharts.com/highcharts/series.line:

![image](https://user-images.githubusercontent.com/33569/63670901-c4641200-c7a3-11e9-9a54-453be6b9f64f.png)

**Comment by KacperMadej** [comment]
Hi @dandv 

Thank you for reporting the problem.

_Internal note:_
Looks like this line is the source of the problem:
https://github.com/highcharts/highcharts/blob/628b2d715a2d6f2fd46fa14ee54f5686c139ee24/ts/parts/Series.ts#L6074
