### ISSUE TITLE
Docs: PointOptionsObject section repeated 8 times

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#11770]
At https://api.highcharts.com/class-reference/Highcharts.PointOptionsObject, I see the "Interface: PointOptionsObject" TOC 8 times in the left nav, and the section is repeated 8 times in the main content.

![image](https://user-images.githubusercontent.com/33569/63635100-11b97580-c624-11e9-8a7e-64a7c968e005.png)

**Comment by KacperMadej** [comment]
Hi @dandv 

Thank you for reporting the problem.

_Internal note:_
@bre1470 Could this be a more common problem caused by TS and extending interfaces in jsdoc lie in here: https://github.com/highcharts/highcharts/blob/628b2d715a2d6f2fd46fa14ee54f5686c139ee24/ts/parts/Legend.ts#L171-L177 ?

**Comment by bre1470** [comment]
Yes, the reason for it is, that the doclets get defined on several places. In the end it is all the same though.
