### ISSUE TITLE
dataLabels are not visible in 3D column chart

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#11776]
#### Expected behaviour
dataLabels should be visible like in standard 2D chart

#### Actual behaviour
dataLabels are not visible at all in 3D chart

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/1toqferL/

#### Product version
Highcharts 7.1.3.

#### Affected browser(s)
All

Internal Note:

The part of code behind current behaviour is in plotGroup wrap:

```
if (this[prop]) {
  delete this[prop];
}

```

**Comment by KacperMadej** [comment]
It looks like a regression.
Worked fine in version 7.1.1 - https://jsfiddle.net/BlackLabel/1toqferL/1/

**Comment by Izothep** [comment]
Yes, the issue is related to a different fix with updating chart from 2D to 3D.

simple workaround is to change above part of code to:

```
if (this[prop] && prop !== 'dataLabelsGroup') {
  delete this[prop];
}
```
