### ISSUE TITLE
Can't able to scroll the tooltip in mobile in column graph highchart

### ISSUE THREAD

**Issue by Appstute-shubhamkadam** [highcharts/highcharts#11787]
#### Expected behaviour
At time tool tip scroll background column bar of that tool tip can't be click.

#### Actual behaviour
We have plotted bar graph and showing tooltip of the values on click event in mobile. As values are more we have given scrollbar to the tooltip and this is working fine in desktop. But in mobile click event and scroll touch are overriding and while scrolling its opening the tooltip.
How can we keep both the events separate so that while scrolling tooltip will not open the tooltip?

#### Live demo with steps to reproduce
https://jsfiddle.net/rckstr/r3c2dpLt/5/

#### Product version

highcharts7.1.2
#### Affected browser(s)

chrome

**Comment by sebastianbochan** [comment]
Hi @Appstute-shubhamkadam,
Thank you for contacting us. 

Its our bug tracker for reporting issues, so please use forum / stackoverflow or email.

ps. You can use the [followTouchMove option](https://api.highcharts.com/highcharts/tooltip.followTouchMove)
