### ISSUE TITLE
Selection is not provided in split packed bubble

### ISSUE THREAD

**Issue by Surekaraja** [highcharts/highcharts#11782]
#### Expected behaviour
Need to select each group in split packed bubble as like in pie chart

#### Actual behaviour
Selection can't be achieved as like in pie chart. Provide solution 

#### Live demo with steps to reproduce
template: https://jsfiddle.net/hvecayfx/1/ 

#### Product version
highcharts v7

**Comment by Izothep** [comment]
Hi @Surekaraja!

Thank you for reporting your issue. 

Could you please send us more specific information how you would like to select split packed bubbles? 

For now it is already possible to select packed bubbles using allowPointSelect option.

Live example: https://jsfiddle.net/BlackLabel/175xhsek/

**Comment by Surekaraja** [comment]
Hi

Here in your reply you have given selection only for individual points of particular split group. I need selection for that particular split group not for the points inside that particular split group. Kindly reply as early as possible.


Kind Regards,

Sureka R

BI Developer - Trainee

[cid:52521dd3-6bef-4982-9f80-0236d7c06395]

Look Forward. Think Ahead.

Main: +91-9710062203
Mobile: +91-8610845038

Innovation & Services Hub<http://visualbi.com/about-us/locations/>

________________________________

**Comment by Izothep** [comment]
Thank you for providing us with further information about your idea. 

Unfortunately, for now it is not possible to use similar feature as it was not intended to give point events callback functionality to parentNodes. I think it might be good idea to add similar option in future Highcharts releases.

For now, as a workaround it might be possible to manually call parentNode.select:
https://jsfiddle.net/BlackLabel/t8vd61mx/

**Comment by Surekaraja** [comment]
Hi
 You have given the solution for single series but I need solution for series array without doing iteration. If possible can you provide solution without that extra function. Do you have any other options for this kind of selection?

 https://jsfiddle.net/ekcqfg7z/1/


Kind Regards,

Sureka R

BI Developer - Trainee

[cid:985a5c6e-44ff-4e0c-819e-b5e9efe320d7]

Look Forward. Think Ahead.

Main: +91-9710062203
Mobile: +91-8610845038

Innovation & Services Hub<http://visualbi.com/about-us/locations/>

________________________________

**Comment by sebastianbochan** [comment]
Hi @Surekaraja,
Thank you for the feedback. 

Updated demo:
- https://jsfiddle.net/BlackLabel/6e7k0t1y/

Please be aware of limits of the solution because at this moment its only workaround.

**Comment by Surekaraja** [comment]
Hi

Do you have any other alternative option without using this function to select particular group? And at a time only one group should be selected but in your solution it is able to select more than one group at a time.


Kind Regards,

Sureka R

BI Developer - Trainee

[cid:ba5b82d4-c7a5-4a51-82ef-ec2742a8820c]

Look Forward. Think Ahead.

Main: +91-9710062203
Mobile: +91-8610845038

Innovation & Services Hub<http://visualbi.com/about-us/locations/>

________________________________

**Comment by Izothep** [comment]
Hi @Surekaraja,

Unfortunately, as we have mentioned for now fully supported version of such a feature is not implemented - we consider it as an enhancement that might be added in future releases.

Please find an example of a workaround for selecting and deselecting parentNodes below:
https://jsfiddle.net/BlackLabel/6e7k0t1y/1/
