### ISSUE TITLE
Nothing is visible for a single block (i.e. when to is null)

### ISSUE THREAD

**Issue by DPareshB** [highcharts/highcharts#11799]
#### Expected behaviour
Single Block should be present

#### Actual behaviour
No Blocks are Present

#### Live demo with steps to reproduce
https://jsfiddle.net/p1gaj7un/3/

#### Product version

Angular- 6.1.1
Highcharts version- 7.1.2

**Comment by sebastianbochan** [comment]
Hi @DPareshB ,
Thank you for reporting about the problem. It looks like similar to https://github.com/highcharts/highcharts/issues/11792

Internal note
FYI @TorsteinHonsi

**Comment by DPareshB** [comment]
#11792- seems to be resolved but this issue is still not resolved. We are unable to see a single component without any relation. Once we set a relation the component is visible.

**Comment by sebastianbochan** [comment]
Fixed since 8.0.4

Demo:
- https://jsfiddle.net/BlackLabel/vd26scnr/

Closing the ticket as resolved.
