### ISSUE TITLE
lineWidth has no effect when boost is enabled for line series

### ISSUE THREAD

**Issue by manu-st** [highcharts/highcharts#11794]
If you set `lineWidth` to a value different than 1, then this setting has no effect when boost is enabled. I saw a few references in the highcharts forum about this but no github issues. Is the solution to use triangle to fix this planned?

See https://www.highcharts.com/forum/viewtopic.php?t=39846
See https://mattdesl.svbtle.com/drawing-lines-is-hard

#### Expected behaviour
The line should have the specified width.

#### Actual behaviour
All lines have a width of 1.

#### Live demo with steps to reproduce
boost enabled: http://jsfiddle.net/c619o4ek/
boost disabled: http://jsfiddle.net/1nmt6awz/

#### Product version
6.x and 7.x

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @manu-st,
Thank you for reporting about the bug.

**Internal note**
The style mode also ignores `lineWidth`

Demo:
- http://jsfiddle.net/BlackLabel/nh6g90r7/

It looks like these lines overwrite options.

```

                if (settings.lineWidth > 1 && !H.isMS) {
                    gl.lineWidth(settings.lineWidth);
                }
```

@cvasseng

**Comment by TorsteinHonsi** [comment]
> The style mode also ignores lineWidth

That's expected behaviour, instead `stroke-width` must be set in CSS.

**Comment by manu-st** [comment]
@TorsteinHonsi What do you mean exactly? If a special css style is needed, why doesn't Highcharts do it automatically for us?

**Comment by TorsteinHonsi** [comment]
Sorry for the confusion @manu-st. My comment is actually off topic, it answers to @sebastianbochan's comment about _styled mode_.

But it is not relevant to the issue, which is _boost mode_. We will be cack with a comment on that.

**Comment by cvasseng** [comment]
Hey @manu-st, we're currently looking into using either triangulation or some shader magic to properly implement `lineWidth`. The issue is, as you alluded, that WebGL lacks support for setting line width in a consistent manner (modern WebGL implementations only supports a line width of `1.0`). I will get back to you shortly with more details in terms of time frame/feasibility.

**Comment by iamanoopmk** [comment]
In the latest version of Highcharts this issue is still there. Any updates on this?

**Comment by pawelfus** [comment]
@cvasseng FYI

**Comment by 90michael** [comment]
Any news?

**Comment by pawelfus** [comment]
We will investigate the issue and let you know

**Comment by pawelfus** [comment]
For now, it is considered a boost limitation caused by non-trivial task to implement line-width in WebGL.

**Please vote for this feature by adding a thumbs-up reaction to the first post.**

We prioritize the most popular enhancements/feature requests.

**Comment by TorsteinHonsi** [comment]
Since we're implementing support for `window.devicePixelRatio` (as in Retina), this issue is more important. With a device pixel ratio of 2 (typical Retina), the 1px line width is scaled down to 0.5px.

**Comment by TorsteinHonsi** [comment]
After internal discussion in the team, we came up with sort of a quick workaround. We can use SVG filters to thicken the lines. See https://jsfiddle.net/highcharts/mn368rsL/ . It's not perfect, so any ideas for improving the filter are welcome.

**Comment by manu-st** [comment]
Will the workaround be implemented by default? Or is this something client will need to do?

**Comment by hubertkozik** [comment]
Hey @manu-st! We've added this Enhancement to our backlog and prioritized the issue. When someone starts working on it, you'll get a notification here, in the GitHub thread.

**Comment by MarkusBarstad** [comment]
> After internal discussion in the team, we came up with sort of a quick workaround. We can use SVG filters to thicken the lines. See https://jsfiddle.net/highcharts/mn368rsL/ . It's not perfect, so any ideas for improving the filter are welcome.

@TorsteinHonsi Seems like we can eliminate at least some of the color-distortion with using `feDropShadow`: https://jsfiddle.net/mkb93/toq1a4bv/148/

Its hard to find a way to tame the jagged lines though 🤔
