### ISSUE TITLE
Org Chart with only one data

### ISSUE THREAD

**Issue by Hokseed** [highcharts/highcharts#11792]
Hello,

I am trying to dynamically create Org Charts and sometimes the chart only contains one data.

With a network graph, it's possible to have only one node like this : ['node1', 'node1'] in the datas of the serie but I have an error when I do that with an Org Chart.

Fiddle : https://jsfiddle.net/epkwgurz/
Error: Uncaught TypeError: Cannot read property 'options' of undefined at a.<anonymous> (VM922 sankey.js:22)

**Comment by sebastianbochan** [comment]
Hi @Hokseed,
Thank you for reporting about the problem. 

**Internal note**
FYI @TorsteinHonsi

**Comment by Hokseed** [comment]
Can you tell me when this will be fixed or if you find a workaround ? Thx
