### ISSUE TITLE
Gauge does not render when max less than value and min is undefined

### ISSUE THREAD

**Issue by manojmari** [highcharts/highcharts#11802]
#### Expected behaviour
Should plot a solid gauge filled with chart color

#### Actual behaviour
Plots no gauge and only shows the value

#### Live demo with steps to reproduce
https://jsfiddle.net/3ztLgmwc/

#### Product version
v7.1.2

**Comment by sebastianbochan** [comment]
Hi @manojmari,
The reason of that is setting `yAxis.max` as 200 and point's value of `300` which is out of scale.

Summarising, the `yAxis.max` value should be higher than point's value.
