### ISSUE TITLE
Option (series.)dataLabels.enabled not mentioned in documentation

### ISSUE THREAD

**Issue by luuuke** [highcharts/highcharts#11803]
On e.g. https://api.highcharts.com/highcharts/plotOptions.bar.dataLabels the "enabled" attribute is not listed as an possible option for dataLabels, it is only mentioned briefly as an example within the general description of dataLabels. I think it should be added.

**Comment by sebastianbochan** [comment]
Hi @luuuke,
Thank you for reporting about the problem. We will fix it as soon as possible.

**Comment by bre1470** [comment]
Not solveable at the moment.
