### ISSUE TITLE
Gantt chart: yAxis row height increases on setting 'yAxis .uniqueNames = true' 

### ISSUE THREAD

**Issue by Dronh** [highcharts/highcharts#11807]
#### Expected behaviour

![Capture](https://user-images.githubusercontent.com/22931138/63929806-b5b17f80-ca6f-11e9-8a5d-9b0304fc3bcc.PNG)

#### Actual behaviour
After setting yAxis.uniqueNames = true, height of the yAxis rows increased and bars shifted to top. 
![Capture](https://user-images.githubusercontent.com/22931138/63929940-f5786700-ca6f-11e9-8d1d-cac3152a5aa5.PNG)

#### Live demo with steps to reproduce
https://jsfiddle.net/6okwvupb/5/

**Comment by sebastianbochan** [comment]
Hi @Dronh,
Thank you for reporting about the problem. This is known bug reported here: https://github.com/highcharts/highcharts/issues/11796.

Im closing the issue as duplicate.
