### ISSUE TITLE
RangeSelector zoom around the beginning of the dataset

### ISSUE THREAD

**Issue by max0x7ba** [highcharts/highcharts#1180]
I needed RangeSelector component to zoom around the beginning of the range, rather then the end of the range. To do so I had to modify it a little. 

I've attached a patch for Highstock JS v1.1.6 (2012-06-08) that introduces a new RangeSelector option called "fixedMin" to make it zoom around the beginning of the range. I thought you might like to integrate it.

```
diff --git a/3rd-party-src/java-script/highcharts/js/highstock.src.js b/3rd-party-src/java-script/highcharts/js/highstock.src.js
index 7579bab..530ca8c 100644
--- a/3rd-party-src/java-script/highcharts/js/highstock.src.js
+++ b/3rd-party-src/java-script/highcharts/js/highstock.src.js
@@ -16706,12 +16706,13 @@ RangeSelector.prototype = {
            baseDataMax = extremes && extremes.dataMax,
            dataMin = mathMin(baseDataMin, pick(navDataMin, baseDataMin)),
            dataMax = mathMax(baseDataMax, pick(navDataMax, baseDataMax)),
-           newMin,
+           newMin = baseAxis && mathMax(extremes.min, dataMin),
            newMax = baseAxis && mathMin(extremes.max, dataMax),
            now,
            date = new Date(newMax),
            type = rangeOptions.type,
            count = rangeOptions.count,
+           fixedMin = rangeSelector.fixedMin,
            baseXAxisOptions,
            range,
            rangeMin,
@@ -16734,6 +16735,9 @@ RangeSelector.prototype = {

        if (fixedTimes[type]) {
            range = fixedTimes[type] * count;
+            if(fixedMin)
+                newMax = mathMin(newMin + range, dataMax);
+            else
            newMin = mathMax(newMax - range, dataMin);
        } else if (type === 'month') {
            date.setMonth(date.getMonth() - count);
@@ -16807,6 +16811,7 @@ RangeSelector.prototype = {

        chart.extraTopMargin = 25;
        rangeSelector.buttonOptions = buttonOptions;
+       rangeSelector.fixedMin = options.fixedMin;

        /**
         * The handler connected to container that handles mousedown.
```

**Comment by McNetic** [comment]
We would also be interested in the feature. Currently, I consider adding this as a custom extension in our product; unfortunately, I'd have to copy and reimplement the whole `RangeSelector.prototype.clickButton()`method, which would not be very convenient nor maintainable...

**Comment by TorsteinHonsi** [comment]
Are you familiar with the `wrap` function? http://jsfiddle.net/highcharts/vy081q8f/

**Comment by McNetic** [comment]
Sure, but as the new zoom boundaries are calculated in the middle of the clickButton() method, and it also does various pre-checks and collect its own input data, and also does the whole update afterwards, I do not see an option to modify these boundaries without rewriting the whole thing.... If you have an idea, I'd greatly appreciate it.
