### ISSUE TITLE
Word cloud Exporting - exported image differs from actual word cloud

### ISSUE THREAD

**Issue by rajeshdanabal** [highcharts/highcharts#11804]
#### Expected behaviour
When we export word cloud to Image or PDF, It should be remain as same as plotted word cloud.

#### Actual behaviour
Word's position and angle in the exported image or PDF is different from actual word cloud.

#### Live demo with steps to reproduce
https://jsfiddle.net/rajeshdanabal/az69ufe4/

#### Product version
Highcharts Version 7.1.3

#### Affected browser(s)
Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
HI @rajeshdanabal,
Thank you for reporting about the problem. Its a known bug reported here https://github.com/highcharts/highcharts/issues/8496.

Im closing this ticket as duplicate.
