### ISSUE TITLE
Inverted X axis labels will not position correct on resize if useHtml flag is set

### ISSUE THREAD

**Issue by jswinson** [highcharts/highcharts#11808]
#### Expected behaviour
Label align correct

#### Actual behaviour
I found the issue - when making the chart's width low enough that the middle label is wrapped, it aligns to the left when making the chart wider.
It happens only with "xAxis.labels.useHTML: true"

#### Live demo with steps to reproduce
https://jsfiddle.net/jswinson/goeahujd/5/

#### Product version
@license Highcharts JS v7.1.0 (2019-04-01)

#### Affected browser(s)

Also see my issue entered on the forms 
Inverted X axis labels will not position correct on resize if useHtml flag is set
https://www.highcharts.com/forum/viewtopic.php?f=9&t=42537

**Comment by sebastianbochan** [comment]
Hi @jswinson,
Thank you for reporting about the problem.

The solution is set `white-space:normal` for breaking words into a few lines.

Demo:
- https://jsfiddle.net/BlackLabel/8y5nruh1/

Additionally you can set the static width of label:
- https://jsfiddle.net/BlackLabel/v2mcenrw/

**Comment by jswinson** [comment]
Thank you for your workaround but all of our labels are created dynamically based on data. So we do not know the label size until we load the chart. Is there a way we can change the label width at run-time? Or find the largest label?

**Comment by sebastianbochan** [comment]
Hi @jswinson,
Are you able to estimate maximum length of label? It will allow me to adapt the solution for the edge-case.

**Comment by jswinson** [comment]
I can get the label string length but how do I calculate the pixel length that the string will take?

**Comment by sebastianbochan** [comment]
Whats the maximum string of category? Could you paste?

**Comment by jswinson** [comment]
There is no maximum string length it depends on the data we only know this when we build the category string to load into the chart.

**Comment by sebastianbochan** [comment]
I think that the best option is using ellipsis.

Demo:
- https://jsfiddle.net/BlackLabel/3s2gkobv/

**Comment by jswinson** [comment]
I have tried your demo with ellipsis. There is a problem that I am seeing if you watch the last label.
When you size the window to right with narrow width the label will wrap and then resize the window to left the long label stays wrapped.

**Comment by jswinson** [comment]
I found similar issue to mine here.
https://github.com/highcharts/highcharts/issues/4746
