### ISSUE TITLE
pointPlacement with disabled grouping is not correct for series with only 1 point

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#11800]
#### Behaviour
If series have only one point each then pointRange is not calculated correctly and pointPlacement is not visibly set to the series points.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/Lqadutbe/1/
All are overlapping while there should be 2 stacks as seen in Highcharts version prior to 7.1.0
https://jsfiddle.net/BlackLabel/Lqadutbe/2/

#### Workaround
Set `pointRange` to `1`.
Demo: https://jsfiddle.net/BlackLabel/Lqadutbe/3/

#### Product version
7.1.0 - 7.1.3+

**Comment by khlieng** [comment]
Fixed since 7.2.1.
