### ISSUE TITLE
Documentation on gauge dial `path`

### ISSUE THREAD

**Issue by danielbartsch** [highcharts/highcharts#11816]
#### Expected behaviour
There should be documentation about the `path` property in the `dial` property of `gauge` series.
I have seen in the code that the property can be used, and it can be used. But it is unclear to me how to actually use it.
It seems to be hard to make responsive paths like the default one with just the `path` property.
As you can see in the live demo below (if the chart gets bigger or smaller, the custom dial stays the same size, as there are no variables to incorporate into the path)

#### Actual behaviour
- no documentation
- no example usage

#### Live demo with steps to reproduce
https://jsfiddle.net/gj3z2ucr/

#### Product version
latest

#### Affected browser(s)
every

**Comment by sebastianbochan** [comment]
Hi @danielbartsch,
Thank you for the suggestion. I agree that it can be as part of our API.

FYI @bre1470

**Comment by bre1470** [comment]
There is no indication that this is something that should be official. It does not refresh and goes directly as a SVGAttribute into the point. The dial type in TypeScript though is wrong and has to be fixed independently.

@TorsteinHonsi Your opinion about making `series.gauge.dial.path` an option?

**Comment by danielbartsch** [comment]
imo, it makes sense to be able to customize the dial. Think of maybe showing a threshold with for example a dashed line.

**Comment by bre1470** [comment]
Yes, I agree that something like this could be useful. The path property though is not an forgotten option, but instead in internal property on the options instance. There has to be something implemented for the idea to work.

**Comment by kaguya3222** [comment]
Any update on this?

**Comment by pawellysy** [comment]
Hello @kaguya3222! We haven't scheduled work for this feature since there wasn't much interest in this feature. We will move this ticket higher in the backlog though.
