### ISSUE TITLE
"Arearange" series with pattern fill issue after zoom

### ISSUE THREAD

**Issue by KevinFernandes** [highcharts/highcharts#11814]
#### Product version
7.1.3
#### Affected browser(s)
Chrome 76

If create an "arearange" series using a pattern fill  (see #11811), it looks fine when initially drawn
![image](https://user-images.githubusercontent.com/2169454/63970250-a6cbcc80-ca71-11e9-884e-a7396583b5c4.png)

but when I zoom in, the pattern fill seems to disappear, scrolling does not seem to bring it back, only zooming back out appears to draw it correctly again.
![image](https://user-images.githubusercontent.com/2169454/63970798-05de1100-ca73-11e9-976a-e6c730d0bb7c.png)

Any thoughts on this being an issue or user error?

**Comment by sebastianbochan** [comment]
Hi @KevinFernandes,
Thank you for reporting about the problem. When I run the demo of area / arearange I was not able to reproduce the issue and all works properly.

- https://jsfiddle.net/BlackLabel/yqnab0fc/

Could you update my demo with your simplified charts options for the further debugging?

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
