### ISSUE TITLE
Column/Bar series with pattern fill questions/issues

### ISSUE THREAD

**Issue by KevinFernandes** [highcharts/highcharts#11811]
#### Product version
7.1.3

Using Chrome 76

I am trying to display column/bar series with a pattern fill and I am getting some odd behavior.
It may or may not be related to issues #8658
I am using patterns specified directly in the configuration, not referenced through IDs or what not.

What I am trying to achieve is a bar/column chart that shows a dashed border with opacity 1, filled using the border color with an opacity of 0.5, and a pattern hash on top of that with an opacity of 1.

I can get a dashed border by specifying "borderColor", "dashStyle" (not documented for column/bar series by the way), "color" and "opacity".
In this case the solid color bars work.

The issues I am experiencing are with the pattern fill.
If I specify a "pattern" object instead of a hex color I get the following:
![image](https://user-images.githubusercontent.com/2169454/63948261-57bc7200-ca46-11e9-8fb2-154c8774d6f4.png)

You can see that the pattern border is correct but the pattern is not showing.

If I hover over one of the series, the pattern appears like this
![image](https://user-images.githubusercontent.com/2169454/63948370-80dd0280-ca46-11e9-9ee0-3c2414bc6426.png)

Is this a bug or is there some other step I need to do to make the pattern appear immediately?

I am using the following pattern definition in code (taken from one of the pattern demos)
```          
pattern: {
  path: {
    d: 'M 0 0 L 10 10 M 9 -1 L 11 1 M -1 9 L 1 11',
    strokeWidth: 1
  },
  width: 10,
  height: 10,
  color: colorValue
}
```

So the pattern is in the color I want, at this point.  But I really want the bar to be filled in with the same color but with an opacity of 0.5 (for example or lower).
I can't seem to figure out if this is possible or what combination of properties need to be set to achieve this.
Bar/column series do not seem to have a "fillColor" or "fillOpacity", it seems to all be controlled through "color" and "opacity".

By the way, if I use the same pattern fill with an area series, it draws correctly immediately (not requiring a hover to get it to draw).  I would like to get the background to fill with the color as well, but that might be a different question :)

Any hints or demos of this capability would be appreciated.

**Comment by sebastianbochan** [comment]
Hi @KevinFernandes,
Thank you for reporting about the problem. When I run the demo of column I was not able to reproduce the issue and all works properly.

- https://jsfiddle.net/BlackLabel/vfubek62/

Could you update my demo with your simplified charts options for the further debugging?

**Comment by KevinFernandes** [comment]
Using your demo and with heavy modifications to replicate (as much as possible) what settings, data and operations we are doing in our app, I am not able to reproduce this issue or #11814.

Our application is Angular 7 based - and I am wondering if that might have something to do with it.  Sometimes in Angular certain functions need to be executed "outside" the Zone, maybe some Highcharts updates need to be executed that way?

What I did notice with the pattern fill is that if some other chart update happens, like showing or hiding another series (or the mouse hover), then the pattern fill refreshes and draws as expected.  Its almost as if its missing an update of some sort.

I should also note that if we use the standard color fill rather than a pattern everything works fine for both bar/column and arearange series.  We also have multiple charts in view that use pattern fills which is why I though it might be related to #8658.

Our Angular application is quite complex so I would not be surprised to learn that we might be doing something that is causing this issue.  I will try to produce a trimmed down Angular application and see if that can reproduce the issue.

**Comment by KacperMadej** [comment]
Using a simple demo in Angular, with the official Highcharts wrapper for Angular, the problem is not visible: https://codesandbox.io/s/angular-uhfjo

Maybe you are using some Angular router features that are messing up the patterns `url`s?
You could compare set color for the elements in the chart in your app and in the working pure JS demo (or even the working demo I have provided above).

In case you have a private project and do not feel comfortable sharing it here you could contact technical support via e-mail: https://www.highcharts.com/blog/support/

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
