### ISSUE TITLE
Chart.update doesn't update colorAxis if the initial config didn't contain it

### ISSUE THREAD

**Issue by Katona** [highcharts/highcharts#11812]
#### Expected behaviour

```js
 var chart = Highcharts.chart('container', {
        chart: {
            type: 'heatmap',
        },
				title: {
        		text: 'Resize window to fail'
        },
        //colorAxis: { },
        series: [{
            data: [[0, 0, 10], [0, 1, 19], [0, 2, 8], [0, 3, 24], [0, 4, 67], [1, 0, 92], [1, 1, 58], [1, 2, 78], [1, 3, 117], [1, 4, 48]]
        }]
    });
    chart.update({ 
    	colorAxis: {
    		reversed: true
      }
    });
```

`Chart#update` should update `colorAxis` regardless of the initial config.

In general I would expect 
```
Highcharts.chart('container', config)
``` 
and 
```
let chart = Highcharts.chart('container', {})
chart.update(config, true, true)
``` 
to be identical.
#### Actual behaviour
`colorAxis` is not updated if the initial config doesn't contain `colorAxis`.

#### Live demo with steps to reproduce
http://jsfiddle.net/7u9g6h30/1/
#### Product version

7.1.3

**Comment by sebastianbochan** [comment]
Hi @tahajahangir,
Thank you for reporting about the problem. 

The colorAxis has been already redesigned and refactored (related case: https://github.com/highcharts/highcharts/pull/11713 ). Now it is available as beta on our master branch.

Demo:
- http://jsfiddle.net/BlackLabel/4Lur5qmx/

Please let me know if all works properly, but be aware that its release-candidate branch and can include some other issues. 

The official release should be in a next few weeks.
