### ISSUE TITLE
Column chart with logarithmic x axis

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#11825]
The following is a neat-and-tidy column chart with a linear x axis:

https://jsfiddle.net/3uxscp6h/

But just un-commenting the `type` line for the `xAxis`, to make the x axis logarithmic, breaks things rather badly:

https://jsfiddle.net/3uxscp6h/1/

Maybe I've just overestimated what is possible... it was my hope to have a logarithmic column chart with columns along the x axis that just touch each other.

**Comment by sebastianbochan** [comment]
Hi @drmrbrewer,
Thank you for reporting about the problem. The data is not logarithic re-scaled (there are linear x points), so when you change pointRange, it its not mathematically correct. I.e when the first point will have size as 2000000, it will be wider than second logarithmic tick (2M). As a result you should not declare this param or set is as 1.

**Demo:**
- https://jsfiddle.net/BlackLabel/9nufabs8/

The best chart for this kind of data is variwide type of chart.

**Demo**
- https://jsfiddle.net/BlackLabel/8hyu5qer/

**Comment by drmrbrewer** [comment]
@sebastianbochan I would have hoped that highcharts would handle the log scaling not only of the point positions (column centres) but also of the column widths, without having to use a completely separate chart/series type (with another source file to load).

That said, you're correct that the variwide chart/series type does appear to achieve what I'm after:

https://jsfiddle.net/Lws2aph0/

In the above example, each column is a constant width so we're not really making use of '**vari**wide' per se, but at least it handles non-linear axes better than 'column' type.

**Comment by KacperMadej** [comment]
1. The current design is like you have seen - columns with equal widths. You could either use a different series type or suggest that the design will be changed, but this will be an enhancement idea and it should be submitted through userVoice: http://highcharts.uservoice.com/forums/55896-general

2. It is start and width for the variwide, so I'm not sure if I got this one right. Could you elaborate on this?

3. Not all of the modules are listed there. Full list of modules could be found in NPM packaged or zipped packaged downloadable from our main download site: https://www.highcharts.com/blog/download/

4. Variwiderange could be obtained by stacking one variwide on top of another hidden and linked variwide series. Demo: https://jsfiddle.net/BlackLabel/8b5pzh6e/

**Comment by drmrbrewer** [comment]
> it is start and width for the variwide

oh ok, with no placement options like 'on' or 'between' like for column charts?  Of course, it's easy enough to map between middle/width, start/end, and start/width because they're all effectively defining the same range, so I'll just do that knowing that I have to end up with start/width for the variwide point definition.

and thanks for the tip about creating an effective `variwiderange` type.
