### ISSUE TITLE
column bar 可以旋转吗  怎么实现下图示例？

### ISSUE THREAD

**Issue by lvguangxin131130** [highcharts/highcharts#11828]
#### Actual behaviour
![资源 1@2x-100](https://user-images.githubusercontent.com/47817456/64106618-2081f400-cdab-11e9-98c2-8047efa2ee85.jpg)

**Comment by sebastianbochan** [comment]
Hi @lvguangxin131130,
Thank you for contacting us. For the general [support questions](http://www.highcharts.com/support) please use stackoverflow / forum or email.
