### ISSUE TITLE
Custom navigator Series does not hide when disabling legend item of related chart series

### ISSUE THREAD

**Issue by SaeedZhiany** [highcharts/highcharts#11868]
#### Expected behavior
When clicking on a legend item, it must hide both related chart series and custom navigator series.

#### Actual behavior
Disabling a legend item only hides chart series and navigator series remains.

#### Live demo with steps to reproduce
https://jsfiddle.net/saeedzhiany/sfy82rgw/1/

this is a simple example. it may seem unreal at first. in my real case, I should update chart asynchronously and I want the navigator always show data of all time. so my server sends me a sperate data for it and I'm using it in my navigator series.

#### Product version
7.1.3

#### Affected browser(s)
all browsers.

**Comment by sebastianbochan** [comment]
Hi @SaeedZhiany,
Thank you for contacting us. This is not build-in functionality and it is not a bug. So for general [support questions](http://www.highcharts.com/support) please use stackoverflow / forum or email. 

ps. You can achieve this by catch the [legendItemClick](https://api.highcharts.com/highcharts/series.line.events.legendItemClick) event and find a related series.

Demo:
- https://jsfiddle.net/BlackLabel/23pbuoq0/

**Comment by SaeedZhiany** [comment]
@sebastianbochan 
thank you for your workaround. but series in navigator hasn't `linkedTo` property and I will get typescript error if I want to use it. 
is type definition file incomplete and will be added in future or you added the property name yourself?

**Comment by sebastianbochan** [comment]
Hi @SaeedZhiany,
It was my parameter, but can be replaced by id and comparing both of them.

Updated demo:
- https://jsfiddle.net/BlackLabel/3psygh6k/
