### ISSUE TITLE
Some chart demos does not shown

### ISSUE THREAD

**Issue by SaeedZhiany** [highcharts/highcharts#11867]
#### Expected behavior
All official website chart demos shown just like previous.

#### Actual behavior
recently I noticed that some chart demos not shown nether on the official website nor jsfiddle and codepen. I think it because of the latest version of highcharts (7.1.3) 

#### Live demo with steps to reproduce
just take a look at [this demos](https://www.highcharts.com/stock/demo/lazy-loading)

| chrome | firefox |
|----------|--------|
|![image](https://user-images.githubusercontent.com/13766432/64145874-e870c480-ce2f-11e9-956d-5ff5464606f8.png)|![image](https://user-images.githubusercontent.com/13766432/64145939-308fe700-ce30-11e9-9c9b-3458adf575b6.png)|

#### Product version
7.1.3

#### Affected browser(s)
I have tested on chrome and firefox. result is the same.

**Comment by sebastianbochan** [comment]
Hi @SaeedZhiany,
Thank you for reporting about the problem. We will fix it as soon as possible.

**Comment by TorsteinHonsi** [comment]
Thanks! Fixed with 835ce2b9896c911c055330587b2a8adc114c0a5c.
