### ISSUE TITLE
Change Navigator's series property to be an array in type definition file

### ISSUE THREAD

**Issue by SaeedZhiany** [highcharts/highcharts#11866]
#### Expected behavior
All series in highcharts can be an array. the same is expected for navigator's series option.

#### Actual behaviour
Current typescript definition does not allow to set an array of series for navigator's series option.
the issue is only in the type definition, implementation has no problem and works well.

#### Live demo with steps to reproduce
I think this is an obvious problem and does not need to reproduce.

#### Product version
7.1.2

#### Affected browser(s)
---

**Comment by sebastianbochan** [comment]
Hi @SaeedZhiany,
Thank you for the suggestion. I agree that is works properly.

Demo:
- https://jsfiddle.net/BlackLabel/1zwtesu2/

FYI @bre1470
