### ISSUE TITLE
Navigator mask and handles don't show up when showInNavigator of all series set to false.

### ISSUE THREAD

**Issue by SaeedZhiany** [highcharts/highcharts#11879]
#### Expected behavior
Navigator mask and handles must be shown up

#### Actual behavior
for an unknown reason, my chart has been rendered like below, as you can see the series data has been shown but the navigator's mask and handles not shown and I'm wondering why? I search a lot on the internet and also read highstock navigator's documentation. there is no option to hide those, As far as I understand, technically they must be shown regardless of whether what combination of other option has been used.

![image](https://user-images.githubusercontent.com/13766432/64160157-b885e900-ce50-11e9-9bde-0c1bd1244224.png)

the related options might help to clarify the problem for you maintainers:

```
{
  scrollbar: {
    enabled: false,
  },
  navigator: {
      adaptToUpdatedData: false,
      series: serverTotalData.map((item) => ({
        type: 'line' as 'line',
        data: item.serverData,
      })),
  },
  series: serverSeriesData.map((item) => ({
    type: 'area' as 'area',
    data: item.seriesData,
    dataGrouping: {
      enabled: false,
    },
    showInNavigator: false,
}
```

#### Live demo with steps to reproduce
I have tested similar options on other chart samples in jsfiddle. unfortunately, I can't reproduce the issue with a simple example. 

I'm not sure is this issue a real bug or something wrong with my configuration, so I confused whether I should post it in StackOverflow or here. I hope maintainers can help me.

#### Product version
7.1.2

#### Affected browser(s)
All browsers

**Comment by sebastianbochan** [comment]
Hi @SaeedZhiany,
Thank you for contacting us. For general [support questions](http://www.highcharts.com) please use stackoverflow / forum or email.

**Comment by SaeedZhiany** [comment]
@sebastianbochan 
Just tell me this, have you seen or faced such issue before? I think it's not usual behavior, I couldn't even find an example of it with a mask and navigational categories hidden.
I also ask this question in [this link](https://www.highcharts.com/forum/viewtopic.php?f=12&t=42584). please answer me on that thread if here is not the proper place. (Although I am gradually convinced that this is a bug)

**Comment by KacperMadej** [comment]
@SaeedZhiany 
Please continue with the thread on the forum and if this is a bug then one of our support engineers will confirm that to you.
