### ISSUE TITLE
TypeError: highcharts__WEBPACK_IMPORTED_MODULE_5___default.a.setOptions is not a function

### ISSUE THREAD

**Issue by afsanefda** [highcharts/highcharts#11893]
#### Expected behaviour

I'm using these charts with my nextjs application but I got this error while setting options:

```
import Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';

Highcharts.setOptions({
  lang: {
    numericSymbols: ['Th', ' M', 'B', 'T'],
  },
});
```

in render : 

```
 <HighchartsReact
     highcharts={Highcharts}
     options={options}
     constructorType="chart"
     immutable
 />
```

#### Actual behaviour
TypeError: highcharts__WEBPACK_IMPORTED_MODULE_5___default.a.setOptions is not a function

As soon as I remove the set option the chart works fine! I've also tried to put it inside constructor but still doesn't work!

```
class Index extends Component {
  constructor(props) {
    super(props);
    Highcharts.setOptions({
      lang: {
        numericSymbols: ['Th', ' M', 'B', 'T'],
      },
    });
  }

  render() { .... }
```
Do you know why ?

**Comment by KacperMadej** [comment]
Hi @afsanefda 

Yes, this is a known issue [caused by nextjs](https://github.com/zeit/next.js/wiki/FAQ#i-use-a-library-which-throws-window-is-undefined).

In short: nextjs runs twice and the first run (server-side) is done in an environment where Highcharts is loaded as a function while it must be an object. It is loaded correctly on a second run.

Here's full info in a related issue: https://github.com/highcharts/highcharts-react/issues/76#issuecomment-446408078

**Comment by afsanefda** [comment]
> Hi @afsanefda
> 
> Yes, this is a known issue [caused by nextjs](https://github.com/zeit/next.js/wiki/FAQ#i-use-a-library-which-throws-window-is-undefined).
> 
> In short: nextjs runs twice and the first run (server-side) is done in an environment where Highcharts is loaded as a function while it must be an object. It is loaded correctly on a second run.
> 
> Here's full info in a related issue: [highcharts/highcharts-react#76 (comment)](https://github.com/highcharts/highcharts-react/issues/76#issuecomment-446408078)

Yes thank you :pray:

**Comment by pranavmshinde** [comment]
This issue occurs when graph is rendered on server side. To run component only on client side we can use dynamic import in nextjs. We have created this graph component and imported it like this

````
const PeGraph = dynamic(() => import("../../component/PeGraphs"), {
  ssr: false,//render this component only on client side
});
````
