### ISSUE TITLE
Link should specify plotOptions.series.crosshairs

### ISSUE THREAD

**Issue by Rojuinex** [highcharts/highcharts#11896]
It is unclear from the text `[series.dashStyle](#plotOptions.series.dashStyle)` that series.dashStyle references `plotOptions`.

Using `[plotOptions.series.dashStyle](#plotOptions.series.dashStyle)` would prevent a lot of confusion.

https://github.com/highcharts/highcharts/blob/97906a93e93a48d141784ea6cdccbe1a5b0d13a4/js/parts/Axis.js#L464-#L478

**Comment by sebastianbochan** [comment]
Hi @Rojuinex,
Thank you for reporting about this.

FYI @bre1470

**Comment by Rojuinex** [comment]
Thoroughly impressed with the velocity in responding to and fixing this issue.  :)  Very happy to have recently adopted Highcharts into our product!

**Comment by bre1470** [comment]
Thank you! :)
