### ISSUE TITLE
Boost options are not updated when using chart.update

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#11909]
#### Expected behaviour
Boost options should be updated when using chart.update method.

#### Actual behaviour
Boost is not updated, even thought other chart options are updated properly

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/mwdpo8Lt/4/

#### Product version
Highcharts 7.2.0

**Comment by ZeSzymi** [comment]
Any updates on this issue?

**Comment by Martin-Nyaga** [comment]
+1 for this on v8.0.0. Is this a bug or intended behaviour? Are there any workarounds?

**Comment by pawelfus** [comment]
I think it's a bug, I see no reason why updating `boost` options shouldn't work as all other options.

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/mwdpo8Lt/6/

Snippet:
```js
Highcharts.Chart.prototype.propsRequireUpdateSeries.push('boost')
```

**Comment by Martin-Nyaga** [comment]
@pawelfus thanks! The workaround works fine in 8.2.2. It doesn't work in 8.0.0 which I was previously using, but I was able to upgrade and get it working.

**Comment by lizhu68** [comment]
Any updates for this issue? I just tried the workaround on the version 11.1.0 and it doesn't work.
