### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. 

### ISSUE THREAD

**Issue by vukoviciv** [highcharts/highcharts#11907]
#### Expected behaviour
Highcharts.js should be optimised for performance.

#### Actual behaviour
Chrome is throwing fallowing warning: 
```[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. ```

#### Possible solution
`addEventListener` can now take `{ passive: true }`; see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners) for more info.

#### Product version
Highcharts.js version 7.2.0

#### Affected browser(s)
Chrome: version 76.0.3809.132

**Comment by sebastianbochan** [comment]
Hi @vukoviciv,
Thank you for reporting the problem. This is known bug and reported here: 
- https://github.com/highcharts/highcharts/issues/11353

Im closing this ticket as duplicate.
