### ISSUE TITLE
Object expected error in latest of v2.3 branch

### ISSUE THREAD

**Issue by jmurph** [highcharts/highcharts#1191]
Trying the radial branch as of commit e8ea7a144873f776ecd7bdea3c16fca6c41f9ca4 using highcharts.src.js.

I tried using the latest just to see if there are any issues with our project, and I found one.  The VMLElement.attr() function contains these lines in it's variable init section (line 4265):

``` javascript
            element = wrapper.element || {},
            elemStyle = element.style,
```

In this case, if wrapper.element is null or undefined, then elemStyle will be undefined.  But, elemStyle is used in the body of the function without checking this.  In particular, I'm hitting this condition on line 4395.

Our code might be doing something wrong, but I don't think highcharts should be throwing an error in any case.

**Comment by oysteinmoseng** [comment]
Closing this, feel free to reopen if still somehow relevant.
