### ISSUE TITLE
Using the `addColorAxis` method in Highmaps hides the map

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#11924]
#### Expected behaviour

The map should not disappear.

#### Actual behaviour
The map disappears.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/30wg2xra/

#### Product version
Highmaps 7.2 - master

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
_Internal note_
@jon-a-nygaard @bre1470 can it be related with this PR https://github.com/highcharts/highcharts/pull/11923 ?

**Comment by ppotaczek** [comment]
That problem is caused by: https://github.com/highcharts/highcharts/pull/11832/commits/8d97517c7f93e2c85ba11ec01397658ab9758128

**Comment by jon-a-nygaard** [comment]
> @jon-a-nygaard @bre1470 can it be related with this PR #11923 ?

I strongly doubt it, because the deleted file was not used anywhere in our code, and if it was then it would probably already have been caught when trying to run `npx gulp scripts`.
