### ISSUE TITLE
3d pie is misplaced after calling `series.update`

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#11928]
#### Expected behaviour

The pie chart should be placed correctly.

#### Actual behaviour

The pie chart is misplaced.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/52z8jfnL/

#### Product version
Highcharts v7.2.0

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Look like connected to initial animation. You could disable it as a workaround.
If you will call the update in a timeout then it will work or stop the animation in a later stage.
Demo: http://jsfiddle.net/BlackLabel/52z8jfnL/3/
Workaround: http://jsfiddle.net/BlackLabel/52z8jfnL/5/

**Comment by sebastianbochan** [comment]
_Internal note_
Bisect leads me to https://github.com/highcharts/highcharts/commit/1fe7b090fcc47050cdb2c10ab99e5965fbae0a38

**Comment by wjhcc2018** [comment]
yes，it's   happened in `"highcharts": "8.0.3",
      "highcharts": "8.0.4",`   but,8.0.2 is ok
