### ISSUE TITLE
tooltip displays data for two points, Error

### ISSUE THREAD

**Issue by ZORfree** [highcharts/highcharts#11926]
#### Expected behaviour
tooltip displays data for two points. Then add new two points and automatically activate the tooltip box
#### Actual behaviour
![image](https://user-images.githubusercontent.com/26847215/64612033-64a57200-d405-11e9-9a2f-3e36a89b8de7.png)

#### Live demo with steps to reproduce
[https://jshare.com.cn/highcharts/hhhhG1/2](https://jshare.com.cn/highcharts/hhhhG1/2)

**Comment by pawelfus** [comment]
I think it's misused `refresh()`, not a bug - I would simply improve [docs](https://api.highcharts.com/class-reference/Highcharts.Tooltip#refresh) for `tooltip.refresh()` to mention that array of points is needed for `shared`/`split` tooltip.

Alternatively we can `splat` points in the `refresh()` function for `split`/`shared` tooltip. Seems to be an easy solution, but then we should also test&guard non shared/split use case.
