### ISSUE TITLE
Bundle size increase after v6 to v7 upgrade

### ISSUE THREAD

**Issue by ZachJW34** [highcharts/highcharts#11931]
#### Expected behaviour

The bundle size for the upgrade of highcharts v6 to v7 should be small.

#### Actual behaviour

The bundle size increased by over 300kb.

#### Context

My company uses Highcharts in an Angular repo. The code below shows how Highcharts was initialized for v6:
```typescript
import * as Highcharts from 'highcharts/highstock';
import * as HighchartsMore from 'highcharts/highcharts-more';
import * as Exporting from 'highcharts/modules/exporting';

#### Context
// More modules

HighchartsMore(Highcharts);
Exporting(Highcharts);
// More Factory

export default Highcharts;
```
<img width="646" alt="Screen Shot 2019-09-10 at 10 39 48 PM" src="https://user-images.githubusercontent.com/25158820/64666450-fa4bfc00-d41b-11e9-8d02-7e2a43b78550.png">

With the upgrade to v7, this changed to:
```typescript
import * as Highcharts from 'highcharts/highstock';
import HighchartsMore from 'highcharts/highcharts-more';
import Exporting from 'highcharts/modules/exporting';

HighchartsMore(Highcharts);
Exporting(Highcharts);

export default Highcharts;
```
<img width="797" alt="Screen Shot 2019-09-10 at 10 44 49 PM" src="https://user-images.githubusercontent.com/25158820/64666644-9ece3e00-d41c-11e9-966a-012ba00bd223.png">

With webpack-bundle-analyzer, I can see that both `Highcharts.js` and `Highstock.js` is included when all I want is `Highstock.js`.
I see there is a similar issue [here](https://github.com/highcharts/highcharts/issues/8667), but the issue is a bit stale and this issue seems recent as it involved the update from v6.2.0 to v7.2.0.

#### Problem

I dug into the code to wee why webpack would be bundling `highcharts.js` and I learned that by adding any module or add-on to Highcharts, such as `highcharts/highcharts-more` or `highcharts/modules/exporting` would cause webpack to bundle highcharts.js. What I believe is happening is that the UMD module definition between v6 and v7 has changed and now lists `highcharts.js` as a depednency for all modules for the AMD definition. Taking `highcharts/modules/exporting` as an example, the UMD definition changed from 
```javscript
(function (factory) {
	if (typeof module === 'object' && module.exports) {
		module.exports = factory;
	} else if (typeof define === 'function' && define.amd) {
		define(function () {
			return factory;
		});
	} else {
		factory(Highcharts);
	}
}
```
to
```javascript
(function (factory) {
    if (typeof module === 'object' && module.exports) {
        factory['default'] = factory;
        module.exports = factory;
    } else if (typeof define === 'function' && define.amd) {
        define('highcharts/modules/exporting', ['highcharts'], function (Highcharts) {
            factory(Highcharts);
            factory.Highcharts = Highcharts;
            return factory;
        });
    } else {
        factory(typeof Highcharts !== 'undefined' ? Highcharts : undefined);
    }
}
```
If I change the AMD definition to reflect the former, webpack no longer bundles `highcharts.js`. I do not believe this extra information in the AMD definition is needed, and could be a result of Highcharts using Typescript to compile down to a UMD module.

Note that I can fix this problem by adding `highcharts: ["node_modules/highcharts/highstock"]` to my apps `tsconfig.json` paths, but this is not an ideal solution.

**Comment by sebastianbochan** [comment]
Hi @ZachJW34,
Thank you for reporting about the problem.

FYI @jon-a-nygaard

**Comment by pawelfus** [comment]
**Workaround:**

Load Highcharts + Stock module instead of Highstock:

```js
import * as Highcharts from 'highcharts';
import Highstock from 'highcharts/modules/stock';
import HighchartsMore from 'highcharts/highcharts-more';
import Exporting from 'highcharts/modules/exporting';

Highstock(Highcharts);
HighchartsMore(Highcharts);
Exporting(Highcharts);

export default Highcharts;
```

**Comment by jon-a-nygaard** [comment]
> the UMD module definition between v6 and v7 has changed and now lists `highcharts.js` as a depednency for all modules for the AMD definition

@ZachJW34 Yes you are correct, we added AMD dependencies to Highcharts in #10375 to have them automatically included for our users.

As far as I know there are two ways of configuring your project to avoid having Highcharts included twice. I am not quite sure how your project setup is with bundlers and loaders, so you may have to adapt the solution some.

The solution @pawelfus described above with loading the stock module is one of them.

Alternatively you can configure your project to have Highstock as the main entry for the `highcharts` package. Then everywhere `highcharts` is named as a dependency it will load Highstock. You can see an example of this at https://jsfiddle.net/jon_a_nygaard/q3npx461/

Please let us know if this solves your issue.

**Comment by ZachJW34** [comment]
@jon-a-nygaard That's what I ended up doing via paths in `tsconfig.json`. @pawelfus thanks for the alternate solution. There is enough info here to fix this problem, so I'll go ahead and close the issue.
