### ISSUE TITLE
Error #15 after updating with changed point names order

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#11940]
#### Expected behaviour
The error should not appear

#### Actual behaviour
Highcharts error 15

#### Live demo with steps to reproduce
1. Open jsfiddle: http://jsfiddle.net/BlackLabel/2La4q0ku/
2. Wait 2 seconds

#### Product version
Highcharts v7.2.0

#### Affected browser(s)
All

**Original use case:** https://github.com/highcharts/highcharts-react/issues/158
___
**_Internal note:_** 

_It looks like a regression since 7.1: http://jsfiddle.net/BlackLabel/qLo3uvf5/_

**Comment by sebastianbochan** [comment]
Workaround:
- set index of points (x param)

Demo:
- http://jsfiddle.net/BlackLabel/bp6v05xj/
