### ISSUE TITLE
RangeSelector buttons not behaving correctly when navigator is disabled

### ISSUE THREAD

**Issue by DanielMuckelbauer** [highcharts/highcharts#11943]
#### Expected behaviour
Range selector buttons show the range of the chart defined in their definition, regardless of the navigator being enabled or not. 

#### Actual behaviour
The last selected range button decreases the date by one day when clicking instead of increasing the range to 5 years. This behavior does not occur when enabling the navigator.

#### Live demo with steps to reproduce
https://jsfiddle.net/Dadamuck/6bsf74yg/

1. Open link
2. Click the selected range buttons one by one
3. The last one decreases day by one instead of increasing range

Was not able to reproduce with smaller data set.

#### Product version
Highstock JS v7.2.0

#### Affected browser(s)
Tested on Firefox and Chrome

**Comment by pawelfus** [comment]
Hi @DanielMuckelbauer 

Thank you for reporting the issue, but unfortunately I'm unable to recreate the issue. This is the result:

![Screen Shot 2019-09-11 at 16 34 41](https://user-images.githubusercontent.com/1453926/64706707-3c278180-d4b2-11e9-9153-331bfdbbc585.png)

Could you set fixed width for the chart in the demo? Thanks!

This hint might be important:
> Was not able to reproduce with smaller data set.

That suggests [`dataGrouping`](https://api.highcharts.com/highstock/series.line.dataGrouping) is involved. Could you try disabling dataGrouping and let us know the results?

**Comment by DanielMuckelbauer** [comment]
I set the fixed width, but unfortunately disabling dataGrouping did not fix the issue. 
About reproducing it: In my demo, click the buttons 1M, 3M, 1J, 3J and 5J in that order. The last button should not be selected, and instead the "From" date in the input box decreases by one day.

**Comment by khlieng** [comment]
Fixed since 8.0.0 (#12507).
