### ISSUE TITLE
treemap is rendered as lines on chart update with changed size properties 

### ISSUE THREAD

**Issue by pulbere** [highcharts/highcharts#11953]
#### Expected behaviour
The treemap chart should be rendered correctly with new size

#### Actual behaviour
The treemap chart is rendered a bunch of connected lines

#### Live demo with steps to reproduce
https://jsfiddle.net/pulbere/5sp9tha7/
1. Open link
2. wait 2 seconds for the update 

#### Product version
Highcharts JS  7.1.2, 7.1.3

#### Affected browser(s)
Tested on Chrome

**Comment by pawelfus** [comment]
Thanks for reporting this regression @pulbere !

Simplified demo: https://jsfiddle.net/BlackLabel/L70qkmey/1/

*Internal note:*
Bisected to commit d94c64d17f

**Comment by pawelfus** [comment]
Closing as duplicate of #11829
