### ISSUE TITLE
Webstorm: Typescript interface files are too big

### ISSUE THREAD

**Issue by radzk** [highcharts/highcharts#11960]
It's really hard to use typescript capabilities with highcharts. The highcharts.d.ts has over 220k lines and is 8.8mb. When Webstorm points me to this file, it gets super slow because of size of it and its pretty impossible to scroll (got 16gb ram).
Is there a way to split this file into smaller chunks?

**Comment by pawelfus** [comment]
FYI @bre1470

**Comment by bre1470** [comment]
Duplicate of #10004

**Comment by bre1470** [comment]
This is not so much about the file size, but more about the type dependency tree. There is no use of splitting as every type in the file depends on others directly or indirectly. The performance problem is known to JetBrains: https://youtrack.jetbrains.com/issue/WEB-36866 Workaround after partial fix is to add more memory like suggested by the editor.
