### ISSUE TITLE
Candle Plotting issue using highChart

### ISSUE THREAD

**Issue by anand-mishra1984** [highcharts/highcharts#11978]
Hi Support,

I am creating candlesticks using highChart but after a few seconds of plotting it stop plotting. Again after few mins it again starts plotting. Please suggest how to solve this issue. There is no issue with data, data is flowing properly.

<img width="1093" alt="candle_not_plotting" src="https://user-images.githubusercontent.com/55394443/64960873-d96b2700-d8b1-11e9-9a23-c85419cdce18.png">
<img width="1098" alt="Candle_plotting" src="https://user-images.githubusercontent.com/55394443/64960874-d96b2700-d8b1-11e9-8798-b41e125d59cb.png">

**Comment by pawelfus** [comment]
Hi @anand-mishra1984 

Thanks for using Highcharts! You used wrong channel, please contact our [support](https://www.highcharts.com/blog/support/) (use direct contact) - they will help you debug the issue and decide if this is a bug in Highcharts core. 

Thanks!
Paweł

**Comment by anand-mishra1984** [comment]
Dear @pawelfus ,

I have used you support url :'https://www.highcharts.com/blog/support/'  and title : '**I have found a bug, and I have reproduction steps** '. It redirected me here. Please take a look of screenshot.

<img width="977" alt="Screen Shot 2019-09-18 at 12 51 21 PM" src="https://user-images.githubusercontent.com/55394443/65125690-78f3fb00-da13-11e9-991a-16eca660c003.png">

<img width="1415" alt="Screen Shot 2019-09-18 at 12 51 31 PM" src="https://user-images.githubusercontent.com/55394443/65125699-7ee9dc00-da13-11e9-931c-88934aa9f242.png">

**Comment by pawelfus** [comment]
Dear @anand-mishra1984 

The key here is "**I have reproduction steps**" :) If you have them, please follow our's Issue template (the one that shows up when you create a ticket - for example live demo, steps etc.) and share them. 

I assumed you only have screenshots so I redirected you to support's page to **use direct contact** ("I want to contact you directly" paragraph in your screenshot), so our support team could help you setting up demo, figuring out the steps etc.

**Comment by anand-mishra1984** [comment]
Dear @pawelfus, 

I clicked the button "I want to contact you directly " but this is getting canceled on support forum which you can see the console result from the screenshot attached. Please suggest me some other way.
<img width="1429" alt="Screen Shot 2019-09-18 at 3 49 06 PM" src="https://user-images.githubusercontent.com/55394443/65140522-5de1b500-da2c-11e9-9896-62cc52b8535c.png">

**Comment by pawelfus** [comment]
> To contact us through our helpdesk, open a ticket in our Support portal, or **send an email to support@highcharts.com**. One of our support engineers will answer you within approximately 24 hours on business days.
