### ISSUE TITLE
Gauge Chart vs. Responsive Rules: center of gauge needle moving upon value update

### ISSUE THREAD

**Issue by bramus** [highcharts/highcharts#11972]
I'm having this issue where the center of the needle of a gauge chart moves when updating the value dynamically.

I'm seeing this occur when there is also a `responsive` rule (which contains a left margin) is set.

#### Live demo with steps to reproduce

http://jsfiddle.net/bramus/k40oztb6/

Note the use of the `responsive` block along with the `setInterval` which updates the value dynamically.

#### Expected behaviour

The base of the needle remains in the center of the chart

#### Actual behaviour

The center of the needle shifts upon update of the series' value

#### Product version

Using highcharts 7.2.0 now. The bug itself got introduced with version 7.1.3.

If you alter the demo to use version 1.7.2 then you'll see the whole gauge pane get shifted (due to the `responsive` rule) upon initializing. Starting with version 7.1.3 the gauge pane itself does not move upon load.

#### Affected browser(s)

Seeing this in latest Chrome, latest Firefox, latest Safari

#### Further findings

1. The tooltip is immediately positioned at the correct position.
2. When wrapping the `#container` into a `#wrapper`, and setting the width/height on the `#container` (see http://jsfiddle.net/bramus/b8v35L2s/), the rendering issue can be corrected by resizing the window : you'll see the gauge pane get moved around upon a window resize.
3. When immediately setting the left margin (instead of through a responsive rule) the chart renders correctly

Points 2 and 3 above leave me to think that the responsive rules aren't applied properly after load.

**Comment by pawelfus** [comment]
Thanks for reporting the issue @bramus 

I think you are right, it seems that setting margins in responsive rules doesn't work on chart load.

Simplified demo: http://jsfiddle.net/BlackLabel/Lgd15w7a/

Used to work fine up to v7.1.2: http://jsfiddle.net/BlackLabel/hk86j7mv/ (chart is translated before first point's update, not only the needle).

Bisected to commit 94c5a58dc7

**Comment by sebastianbochan** [comment]
_Internal note_
After some debugging it looks like a problem with the `setResponsive` method which does not apply marginLeft properly. Moreover the `pane.update()` is missing too, when redraw series (but marginLeft is applied). It looks like very tricky.
