### ISSUE TITLE
Updating plotOptions in drilldown event between 2 drilled layers breaks chart

### ISSUE THREAD

**Issue by janM37** [highcharts/highcharts#11980]
Might be related to [#10597](https://github.com/highcharts/highcharts/issues/10597) and fix  [#11110](https://github.com/highcharts/highcharts/pull/11110)
#### Expected behaviour
I want to show a `checkbox` in the last layer of a barchart with multiple drilldown (and hide it on any other layer). 

#### Actual behaviour
While `chart.update()` works fine between root layer and first drilled layer, it seems that the chart breaks if the function is used between two drilled layers

#### Live demo with steps to reproduce
https://jsfiddle.net/janM37/ckdp0f91/

- If you drill down and up only on the first layer, there is no issue
- Problem appears on second sublayer. It might be that `chart.series` is not handled properly.

#### Product version
On Highcharts 7.0.x, drilldown does not work at all with  `chart.update()`. Starting 7.1.0, this problem appears

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting the issue.

**Workarkound:**
Configure drilldown series with all expected options and avoid using `chart.update()` in drilldown/up events: https://jsfiddle.net/BlackLabel/6npzt97x/
