### ISSUE TITLE
Overlapping stackLabels

### ISSUE THREAD

**Issue by danazelniker** [highcharts/highcharts#11982]
#### Expected behaviour

labels shouldn't overlaps one another when there is not enough space

#### Actual behaviour

labels overlaps

#### Live demo with steps to reproduce
![insights bug](https://user-images.githubusercontent.com/16417615/64968804-6d85c000-d8ab-11e9-823a-7f5d67abf5ff.png)

#### Product version
 Highcharts: 6.1.1

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Hi @danazelniker 

Thanks for reporting this issue.

I see two issues here:

- first arrow: 
  There's no logic in overlapping dataLabels and other columns, only overlapping between labels is supported. I suggest to create an idea on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api) - if the idea gets popular it will be implemented to the core (or as a plugin) :) 

- second arrow:
  That looks like a bug. Could you confirm that [`series.dataLabels.allowOverlap`](https://api.highcharts.com/class-reference/Highcharts.DataLabelsOptionsObject#allowOverlap) is set to false? Could you also check if current version (v7.2.0) has the same issue? If none of the above resolve the issue, please provide a live demo (e.g. jsFiddle). Thanks!

**Comment by danazelniker** [comment]
Hi @pawelfus 

I'm not sure where I should add `series.dataLabels.allowOverlap: false`.
currently the `series` key is an array of my data.
you can see it here:
https://jsfiddle.net/vf2dw6xa/1/
Thanks!

**Comment by pawelfus** [comment]
If you didn't set it, then by default it's set to false, no need to change anything. Just in case, by `series.dataLabels.allowOverlap` I mean on of:
- `{ plotOptions: { series: { dataLabels: { allowOverlap: false } } } }`
- `series: [{ dataLabels: { allowOverlap: false } }]`

Anyway, your demo (https://jsfiddle.net/vf2dw6xa/1/) does not show issue of overlapping two dataLabels.

**Comment by danazelniker** [comment]
you can see it on the left side:
![image](https://user-images.githubusercontent.com/16417615/65154212-c2544280-da33-11e9-80a5-e27973dd3c17.png)

**Comment by pawelfus** [comment]
Ah, you mean `stackLabel`! Thanks, you are right, it's broken, thanks for pointing this out! :) It's a regression - in v7.1 this used to work fine: https://jsfiddle.net/BlackLabel/q36safp9/


*Internal note:*
Bisected to commit ed7ea403ac
@Basts - could you take a look?

**Comment by pawelfus** [comment]
We need to find different solution for this issue, otherwise it causes regressions.
