### ISSUE TITLE
xAxis labels overlap for custom xAxis.dateTimeLabelFormats.day

### ISSUE THREAD

**Issue by smokir** [highcharts/highcharts#11992]
#### Expected behaviour

Prevent xAxis labels from overlapping.

#### Actual behaviour

When I set `"xAxis": {"dateTimeLabelFormats": {"day": "%d.%m.%y"` labels on xAxis begin to overlap. It looks like there are some options in `xAxis.tick*` and `xAxis.minor*` groups that are preconfigured for standard `dateTimeLabelFormats`, but I can't find right options combination to prevent overlapping without losing some options that are automatically computed.

Chrome and Safari
![Снимок экрана 2019-09-17 в 13 44 07](https://user-images.githubusercontent.com/2204174/65035706-86957c00-d952-11e9-8929-84bbde409c19.png)

In Firefox labels are truncated with ellipsis.

#### Live demo with steps to reproduce
https://jsfiddle.net/5boptzxd/

#### Product version
Highcharts 7.1.2

#### Affected browser(s)
Chrome 75.0.3770.100 
Safari 12.1.2
Firefox 69.0

**Comment by pawelfus** [comment]
Thanks for reporting the issue @smokir 

**Workarkound:**
Demo: https://jsfiddle.net/BlackLabel/dznxhpmg/

Snippet:
```js
Highcharts.Axis.prototype.getSlotWidth = function(tick) {
  // #5086, #1580, #1931
  var chart = this.chart,
    horiz = this.horiz,
    labelOptions = this.options.labels,
    slotCount = Math.max(this.tickPositions.length, 1),
    marginLeft = chart.margin[3];
  return (tick &&
    tick.slotWidth // Used by grid axis
  ) || (horiz &&
    (labelOptions.step || 0) < 2 &&
    !labelOptions.rotation && // #4415
    ((this.staggerLines || 1) * this.len) / slotCount) || (!horiz && (
    // #7028
    (labelOptions.style &&
      parseInt(labelOptions.style.width, 10)) ||
    (marginLeft &&
      (marginLeft - chart.spacing[3])) ||
    chart.chartWidth * 0.33));
};
```

*Internal note:*
I'm not sure why `slotWidth` takes `ticks.length - 1` for datetime/linear but for categorized it's just `ticks.length`. Related commit: 2e1106f65f768eaef2a0bc21dd9be4dc4aef3a2f - increasing that `slotWidth` to `ticks.length` does not change the rendered chart.

**Comment by smokir** [comment]
Thank you for answer @pawelfus

Suggested workarkound is close to how [my demo](https://jsfiddle.net/5boptzxd/) works in Firefox.

![screencast 2019-09-17 16-20-49](https://user-images.githubusercontent.com/2204174/65045755-0a0d9800-d968-11e9-9b8a-39e6ac614145.gif)

But what I want is that labels not truncated with three dots or overlaps but just switch to another labels grid like it happens when using default `dateTimeLabelFormats` (when it switches from `2.Jul  4.Jul  6.Jul  8.Jul ...` to `6.Jul  13.Jul ...`).

It looks like some kind of `width` option but only for `xAxis.dateTimeLabelFormats.day: "%d.%m.%y"`, so that in other cases all things and options will be automatically computed.

**Comment by pawelfus** [comment]
Oh, thanks for the explanation! If that's the case, then simply forget about my workaround and increase [`xAxis.tickPixelInterval`](https://api.highcharts.com/highcharts/xAxis.tickPixelInterval), take a look: https://jsfiddle.net/BlackLabel/arhkwobx/
