### ISSUE TITLE
Incorrect wordcloud animation on unsorted data

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#11993]
This report is about wordclouds where the data is _not_ sorted by weight.

## Expected behaviour
1 Words move from the old to the new position
2 Correct color on words after animation

#### Actual behaviour
1 Words start their animation from an seemingly arbitrary position and then move to their new position
2 The words get new colors assigned. The color of the first word in the data no longer corresponds with the first color in the plotoptions colors.

#### Live demo with steps to reproduce
https://jsfiddle.net/kzoon/tmowrf9j/
Click 'update chart'. Clicking 'update chart' repeatedly makes the issue even clearer, because the data is exactly the same...

https://jsfiddle.net/kzoon/akyn5u9w/, which uses sorted data, shows the correct behavior.

**Comment by pawelfus** [comment]
Thanks for reporting @kzoon 

FYI @jon-a-nygaard

**Comment by kzoon** [comment]
I need to wrap up my new word cloud implementation and deliver it to my customers.
Is there any chance on as solutions or workaround for these issues by the end of the week? Otherwise I need to start working on my own workarounds (if possible)

**Comment by pawelfus** [comment]
I can't provide solutions, but the easiest workaround is to sort data before rendering wordcloud.

This can be done on a Highcharts level too:
https://jsfiddle.net/BlackLabel/97cmaodq/2/

Snippet:
```js
(function(H) {
  H.wrap(
    H.seriesTypes.wordcloud.prototype,
    'setData',
    function(proceed, data, ...args) {
      data = data.sort(function(p1, p2) {
        return p2.weight - p1.weight;
      });

      return proceed.apply(this, [data, ...args]);
    }
  );
})(Highcharts);

```

**Comment by jon-a-nygaard** [comment]
Thanks again for reporting @kzoon,

We will start working on this and try to have it ready for the next maintenance release. I am though not sure when the next release will be, it could be everything from 1-3 weeks. Therefore I will recommend for now to use one of the workarounds from @pawelfus if possible.

**Comment by kzoon** [comment]
OK, 
For now I will use the sorting workaround. 
Still looking forward to the unsorted animation, because that allows me to keep the words in the same order, which (hopefully) will make each word move from its old position to its new position.

**Comment by kzoon** [comment]
@jon-a-nygaard, I found an anomaly in the animation on sorted data as well.
When I update with the exact same data, I would expect nothing to happen, but if fact a lot of words move around. 

See https://jsfiddle.net/kzoon/rezp3av2/1/ 

Only after 2 or 3 updates, the words stay in the same place.

**Comment by pawelfus** [comment]
Works fine for me (latest Chrome):

![wordcloud](https://user-images.githubusercontent.com/1453926/65949021-b1480000-e43b-11e9-9e44-a77b1aefebea.gif)

Could you try setting fixed width?

**Comment by pawelfus** [comment]
Yes, that's it! With zoom to 110% first update repositions words.

**Comment by kzoon** [comment]
Even without zoom:
In https://jsfiddle.net/kzoon/rezp3av2/3/show  two items swap place when you click update chart: 'USB Stick' and 'Portable LCD TV'

**Comment by pawelfus** [comment]
osx + latest chrome, 100%:
![wordcloud2](https://user-images.githubusercontent.com/1453926/66031595-08b1a300-e504-11e9-93e4-b05d013d80a2.gif)

**Comment by jon-a-nygaard** [comment]
> Even without zoom:

I was able to experience this on one of my monitors, but not sure what causes it. Does not happen on my laptop screen.

**Comment by sebastianbochan** [comment]
@jon-a-nygaard maybe its related that your laptop screen is retina, but external diplay, not?
