### ISSUE TITLE
Zooming does not work properly with boost module and multiple series.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#12016]
#### Expected behaviour
The boost mode should be turned off if the amount of points in series is fewer than the `series.boostThreshold` value after zooming the chart. 

**NOTE:** _If there is only one series on the chart, everything is working as expected._

#### Actual behaviour
Boost module is almost always turned on after zooming, regardless of the `series.boostThreshold` value and number of points in each series.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/xz9sm17e/
1. Click on the "zoom to 200-210" button to set the new x extremes.
2. See the number of points in each series (11)
3. The `series.boostThreshold` is set to `500`, so the boost should be now disabled, but it is not.

_Interestingly, the boost mode is turned off only after clicking 3 times on the mentioned button._
_Could be related with https://github.com/highcharts/highcharts/issues/10075, but I'm not really sure._

**Comment by gustavoittner** [comment]
Hi, this issue will not be fixed?

**Comment by karolkolodziej** [comment]
@gustavoittner as far as I can see this issue is no longer visible.
Are you able to replicate this?
