### ISSUE TITLE
Collapsing/Expanding sometimes visually not happening when the Gantt has a fixed height

### ISSUE THREAD

**Issue by FilipeCosta06** [highcharts/highcharts#12012]
#### Expected behaviour
Collapsing and expanding should hide/show data.

#### Actual behaviour
When setting a fixed height, some combinations of collapse/expands don't visually update the Gantt.

#### Live demo with steps to reproduce
https://jsfiddle.net/g6t8yh0r/1/
This demo is just the official subtask demo. I removed the title and added a fixed height of `300`.

To reproduce, in this example: 
- first, click on "Design" (works OK) 
- then, click on "Planning" (visually, nothing happens)
- finally, click on "Develop" (this will cause both this Tick and Planning to collapse)

And some similar issues happen when trying to expand.

I thought simply calling `chart.redraw()` or `chart.update({})` would fix it but it didn't.

#### Product version
Product: Highcharts Gantt v7.2.0

#### Affected browser(s)
Chrome, but I assume any other too.

**Comment by pawelfus** [comment]
Thanks for reporting @FilipeCosta06 

@jon-a-nygaard - could you take a look?

**Comment by jon-a-nygaard** [comment]
Thanks again for reporting. This is obviously a bug, and me or one of the other developers will start working on a solution as soon as possible.

**Comment by sebastianbochan** [comment]
_Internal note:_
Related with https://github.com/highcharts/highcharts/issues/11742

**Comment by amitlivnat** [comment]
Hey guys,
Any update on this one? I have  few clients' complaints about it and need to know how to answer to them. 
Please advise.
Thanks.
Amit

**Comment by pawelfus** [comment]
Hi @amitlivnat 
No updates at this moment, but issue is prioritized.
