### ISSUE TITLE
LinkedTo series not changing opacity when its related legend-item is hovered.

### ISSUE THREAD

**Issue by jvorssel** [highcharts/highcharts#12015]
I've altered an existing demo for a series with the "linkedTo" property configured.
I've introduced a new line-series with random values that has no "linkedTo" property.
When you hover the item in the legend for the new series (Range2), all other series are transparent, except the series with the "linkedTo" property.

#### Expected behaviour
When you hover the item in the legend for the new series (Range2), all other series are expected to be transparent.

#### Actual behaviour
When you hover the item in the legend for the new series (Range2), all other series are transparent, except the series with the "linkedTo" property.

#### Live demo with steps to reproduce
[Fiddle](https://jsfiddle.net/raybbo/tfs3jv2b/4/)

1. Hover the legend-item "Temperature"
2. The series "Range2" becomes transparent **OK**
3. Hover the legend-item "Range2"
4. The "Temperature" series (line) becomes transparent **OK**
5. The "Temparature" series (range) stays opaque **NOK**

#### Product version
Highcharts v7.2.0

#### Affected browser(s)
Firefox and Chrome

**Comment by pawelfus** [comment]
Hi @jvorssel 

Thank you for reporting the issue. This is expected behaviour: only series that are visible in the legend are inactivated. When you enable this series in legend you will see inactive state on all other series: https://jsfiddle.net/BlackLabel/872o4r0w/

The same effect you can observe when you remove `linkedTo` option and remove that series from legend: https://jsfiddle.net/BlackLabel/gxdnp60L/

**Comment by jvorssel** [comment]
> 
> 
> Hi @jvorssel
> 
> Thank you for reporting the issue. This is expected behaviour: only series that are visible in the legend are inactivated. When you enable this series in legend you will see inactive state on all other series: https://jsfiddle.net/BlackLabel/872o4r0w/
> 
> The same effect you can observe when you remove `linkedTo` option and remove that series from legend: https://jsfiddle.net/BlackLabel/gxdnp60L/

Ah okay, thanks for the quick reply!

I've been looking around for a way to still change the opacity for the linked-series, for about a day. Do you know any way around this behaviour? So the linked-series will still become transparent when the legend-item is hovered?

Thanks!

**Comment by pawelfus** [comment]
Any other than showing linked series in legend (https://jsfiddle.net/BlackLabel/872o4r0w/) ? 

Another possible solution is to take control over legend items and manage state (`'inactive'` vs `'normal'`): https://jsfiddle.net/BlackLabel/jo7z51vx/

```js
  chart: {
    events: {
      load: function() {
        var chart = this;

        // Add events:
        chart.series.forEach(function(series) {
          if (series.legendGroup) {
            Highcharts.addEvent(series.legendGroup.element, 'mouseover', function() {
              // Internal method
              // Can be also implemented manually as `series.setState('inactive');`
              chart.pointer.applyInactiveState([series.points[0]]);
            });
            Highcharts.addEvent(series.legendGroup.element, 'mouseout', function() {
              chart.series.forEach(function(s) {
                s.setState();
              });
            });
          }
        });
      }
    }
  },
```

**Comment by max0x7ba** [comment]
> This is expected behaviour: only series that are visible in the legend are inactivated.

The documentation says that _toggling the visibility of a legend item also toggles the linked series_. But hover over legend item doesn't change the opacity of linked series. 

IMO, such an inconsistent behaviour cannot be called _expected_.

**Comment by kzoon** [comment]
I ran into this bug today. 

See my example: https://jsfiddle.net/kzoon/79sc5jk3/

In my example linked series are lines on scatter chart which are derived by a calculation on the scatter points (like regression). It is obvious that hiding/hovering should impact both the scatter series as the linked line series.

A bug fix would be much appreciated!

**Comment by sebastianbochan** [comment]
@kzoon thank you for the additional example.

**Comment by hanyuei** [comment]
> IMO, linkedTo should also change the opacity of the linked series on hover. The shared legend item should affect all linked series in the very same way as if they had individual legend items.

is there any workaround for this ?

**Comment by PaulDalek** [comment]
Hi @hanyuei

Yes, check this comment: https://github.com/highcharts/highcharts/issues/12015#issuecomment-533095850. You could also set `showInLegend` of the `arearnage` series and hide the legend item through CSS.

**Workaround**
https://jsfiddle.net/BlackLabel/o7uky0zj/

**Comment by kzoon** [comment]
Any chance of solving this issue?

**Comment by KacperMadej** [comment]
Yes, it is still open.
Marking the issue for internal prioritization discussion.
