### ISSUE TITLE
Sankey nodes don't have correct height, when we put minLinkWidth

### ISSUE THREAD

**Issue by slesarevns** [highcharts/highcharts#12014]
#### Expected behaviour
Sankey nodes have the same height like sankey links, when  put ```minLinkWidth``` property
![sankey-default](https://user-images.githubusercontent.com/10522353/65157184-03028a80-da39-11e9-9d71-c0abea547a9d.png)

#### Actual behaviour
Sankey nodes don't have correct height, when  put ```minLinkWidth: 100```
![sankey-messing](https://user-images.githubusercontent.com/10522353/65156118-29bfc180-da37-11e9-874e-cb3d11373d6d.png)

#### Live demo with steps to reproduce

We need only to put ```minLinkWidth: 100``` here https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/sankey-diagram/ 
![sankey-messing](https://user-images.githubusercontent.com/10522353/65156118-29bfc180-da37-11e9-874e-cb3d11373d6d.png)

#### Product version

Highcharts 7.2.0
#### Affected browser(s)
Chrome, Firefox, Safari

Best Regards

**Comment by slesarevns** [comment]
@sebastianbochan @pawelfus @oysteinmoseng  any feedback? 😃

**Comment by pawelfus** [comment]
Hi @slesarevns 

Thanks for reporting the issue! :) This is expected behaviour - `minLinkWidth` only changes the width of the path in SVG, without any relation to the node's height. We decided to prevent this relation because of your second screenshot, where presentational attributes would break the chart's values. We recommend to use `minLinkWidth` with small values like 1-2px where disturbances are barely visible and you really want to show very small values in relation to huge ones. In case you need higher values for `minLinkWidth`, consider setting `nodes.height` for specific nodes that might be to small: https://jsfiddle.net/BlackLabel/v0uLkeb9/

**Comment by slesarevns** [comment]
Hi @pawelfus  thanks 👍  But in my case it's doesn't work even if I put 2px 
![sankey-node](https://user-images.githubusercontent.com/10522353/65239319-69de7d00-dae7-11e9-9d02-5f6474992e68.png) Maybe you have a solution when we can calculate `nodes.height` dynamically not just hardcoding node height like here https://jsfiddle.net/BlackLabel/v0uLkeb9/ (sadly but it's not working)? Or any other suggestions?

**Comment by pawelfus** [comment]
Could you create basic demo to generate similar output? We will take a look

**Comment by slesarevns** [comment]
@pawelfus here the demo https://jsfiddle.net/slesarev_1909/m138fk0h/5/

**Comment by pawelfus** [comment]
Perhaps something like this could resolve your issue: https://jsfiddle.net/BlackLabel/z76jahLf/ 

Note that solution could be improved, maybe just checking the last link instead of all could be enough (needs to be tested). There's also a risk that with huge `minLinkWidth` will force nodes to overlap: https://jsfiddle.net/BlackLabel/z76jahLf/1/

Plugin:
```js
Highcharts.wrap(
  Highcharts.seriesTypes.sankey.prototype,
  'translateNode',
  function(proceed, node, column) {
    var series = this,
      increaseHeight = false;
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));

    node.linksTo.forEach(function(link) {
      if (series.translationFactor * link.weight < series.options.minLinkWidth) {
        increaseHeight = true;
      }
    });

    if (increaseHeight) {
      node.shapeArgs.height += series.options.minLinkWidth;
    }
  }
);
```

**Comment by slesarevns** [comment]
@pawelfus big thanks 👍  But I have another problem in my case `Highcharts.seriesTypes.sankey.prototype` doesn't exit inside Highcharts object 
![Без названия (2)](https://user-images.githubusercontent.com/10522353/65257500-f7cb5f80-db09-11e9-900f-e01d9a581dd1.png) any idea how it's possible?, because I cannot use the plugin, get an error 😞 Also I'm using the latests Highcharts version 7.20 like in your example

**Comment by KacperMadej** [comment]
@slesarevns 
Please note that the plugin https://code.highcharts.com/modules/sankey.js is required for the `sankey` options to be added to the Highcharts instance.

**Comment by slesarevns** [comment]
Hi @KacperMadej  thnaks 👍  any opportunity install the plugin using npm?

**Comment by slesarevns** [comment]
Hi @pawelfus @KacperMadej big thanks but with really data the plugin doesn't work 
![Без названия (4)](https://user-images.githubusercontent.com/10522353/65325468-9a8de780-dbb7-11e9-9f3d-0598ea2bf78b.png). I'll provide the demo to generate similar output soon

**Comment by slesarevns** [comment]
@pawelfus @KacperMadej  here the demo https://jsfiddle.net/slesarev_1909/a3u7o8cj/5/

**Comment by KacperMadej** [comment]
Links *to* were the only one accounted for. Here's a demo with links *from* also processed: https://jsfiddle.net/BlackLabel/m26er70o/

There will probably still be some issues, as this is only a temporary and not fully tested workaround, but please let me know (or Paweł, he will be back in the office on Monday) in case the wrap should be adjusted further.

**Comment by slesarevns** [comment]
Hi @pawelfus @KacperMadej  big thanks 👍 But we still have a small issue when we put `nodePadding` the last nodes don't look so good, could you take a look? 
![Без названия (6)](https://user-images.githubusercontent.com/10522353/65425956-e2ab4500-de17-11e9-9076-6fda6ee5d824.png)
Here the demo https://jsfiddle.net/slesarev_1909/3nr5jafc/3/

**Comment by pawelfus** [comment]
You can temporary disable `series.clip`, see: https://jsfiddle.net/BlackLabel/7f4sy2u5/ - it won't work with huge node paddings though: https://jsfiddle.net/BlackLabel/7f4sy2u5/1/

**Comment by slesarevns** [comment]
Seems 'series.clip' the perfect solution for me. Thanks @pawelfus 👍  Anyways this is only a temporary solution any updates when it will be fix inside the libraries? Because without the plugin, 
the property `minLinkWidth` looks useless

**Comment by pawelfus** [comment]
No ETA at this moment @slesarevns

**Comment by TorsteinHonsi** [comment]
There's a lot going on in this thread, but as I can understand, the basic problem is that `minLinkWidth` is not reflected in the height of the nodes. 

I propose that we create a `minNodeHeight` option to match. Does that sound like a viable fix?

**Comment by jkxplg** [comment]
We hope that this should do the trick and solve the issue for us.

**Comment by slesarevns** [comment]
It's a good idea but doesn't solve issue totally, because if we have `minLinkWidth` we need to add it to  `nodeHeight` as result re-calculate `nodeHeight` but when we will have `minNodeHeight` it'll cover only some cases, not all but anyways better than nothing 😄

**Comment by TorsteinHonsi** [comment]
> Looks like to solve the issue we need to add minLinkWidth to nodeHeight and recalculate nodeHeight. 

I would argue that we don't recalculate the `nodeHeight` because it will give a false impression of the node's weight. Instead we should let the links overlap close to the node.

**Comment by slesarevns** [comment]
Sorry I don't sure how it's totally woking, but in my case I'm using the hack and increase `shapeArgs.height` base on `translationFactor * weight < minLinkWidth`.  And it looks like I recalculate `shapeArgs.height` and etc 😄
