### ISSUE TITLE
Printing chart is all messed up for packed bubble chart

### ISSUE THREAD

**Issue by abisha-thapa** [highcharts/highcharts#12027]
#### Expected behaviour
The chart is expected to be printed as in jpeg.
![carbon-emissions-around (2)](https://user-images.githubusercontent.com/18100706/65247545-467bf800-db10-11e9-883a-e427d806312f.jpeg)

#### Actual behaviour
Since **enableSimulation** is set **true** for UI, the chart gets printed while in motion.
![image](https://user-images.githubusercontent.com/18100706/65247722-9fe42700-db10-11e9-9b8a-531b24b4accc.png)

I tried to set **enableSimulation** to false in beforeprint. But I could not disable the simulation when **Print chart** is clicked.

**Comment by KacperMadej** [comment]
Hi @abisha-thapa 

Thank you for reporting the problem.

Printing works fine when the chart has finished the simulation and will print mid-simulation if you decide to print in the middle of the simulation. You could use [`afterPrint`](https://api.highcharts.com/highcharts/chart.events.afterPrint) and [`beforePrint`](https://api.highcharts.com/highcharts/chart.events.beforePrint) events of a chart to update the chart, before printing.

**Comment by abisha-thapa** [comment]
Hello @KacperMadej 

How can I know the simulation is finished after I click **Print chart**? The chart gets rendered again after the **Print chart** is clicked. Also, how can I update chart in beforePrint and afterPrint? I need to update the **enableSimulation** flag to false after I click **Print chart** and get the settled chart in preview.

**Comment by KacperMadej** [comment]
The option you want to change is set in series options, so you could update the series using `Series.update()`. In case of problems please share a demo with the code you have problem with.

This doesn't look like a bug and should be resolved using a technical support channel and not the GitHub issue as we are using it as a bug tracker, but we could continue here to save you the jumps all over different support channels.

**Comment by abisha-thapa** [comment]
Well, I asked those questions trying to crack out some way of fixing the issue.

Here is the [fiddle](https://jsfiddle.net/abisha/htx0f4L2/8/). The issue exists when **Print chart** is clicked. It is related with width. If the width is small, the chart print preview is quite well but might get shifted away from center. In my case, the chart width is quite large and the chart print preview contains a chart in motion.

**Comment by KacperMadej** [comment]
It looks like it's not possible to update the layoutAlgorithm to disable simulation (by `enableSimulation` change in series).
Demo: https://jsfiddle.net/BlackLabel/p0mznd43/
@Izothep Is this a known issue or should this be a bug? If the latter, do we have any workaround for this issue?

**Comment by Izothep** [comment]
Thanks for such detailed explanation of the problem @abisha-thapa ! 

We should definitely consider adding support for dynamic layoutAlgorithm update as soon as possible, due to described issue with printChart method.

**Comment by Izothep** [comment]
It looks that we should be able to use series.update method for dynamically updating layout options as well. Live example:
http://jsfiddle.net/BlackLabel/ywajpfkx/

However, the performance of such operation looks limited. @KacperMadej @pawelfus
