### ISSUE TITLE
change opacity of  bubble  , does not work

### ISSUE THREAD

**Issue by succulen-plants** [highcharts/highcharts#12023]
#### Expected behaviour
{
        name: item[0],
        value: item[4],
        marker: { fillOpacity:1 },
}

**Comment by pawelfus** [comment]
Hi @succulen-plants 

There's no `point.marker` options in bubble series, take a look: https://api.highcharts.com/highcharts/series.bubble.data - only `series.marker`: https://api.highcharts.com/highcharts/series.bubble.marker

There's an option to change opacity per point, but it's working only by accident, may one day be removed, demo: https://jsfiddle.net/BlackLabel/snt08j9a/

Snippet:
```js
      {
        x: 86.5,
        y: 102.9,
        z: 14.7,
        marker: {
          states: {
            normal: {
              opacity: 1
            }
          }
        }
      },
```

**Comment by pawelfus** [comment]
After further testing, it might be a bug in docs (missing marker) - all other options work fine: https://jsfiddle.net/BlackLabel/p9873rjs/ and `fillOpacity` is the only option that's not working. Thus setting `undecided` label.

@TorsteinHonsi - could you confirm it's a bug in docs and `fillOpacity` should work like other options?

**Comment by succulen-plants** [comment]
ok, problem solved

**Comment by TorsteinHonsi** [comment]
Yes as far as I can see it's a bug in the docs. It should work like [scatter](https://api.highcharts.com/highcharts/series.scatter.data.marker).
