### ISSUE TITLE
Y pointer hover position after transform scale on line charts (after render)

### ISSUE THREAD

**Issue by tkmiller3** [highcharts/highcharts#12031]
#### Expected behaviour

When a DOM ancestor of a chart div has a transform scale value > 1, the tooltip should correctly track the X,Y position of the rendered points on hover.

NOTE: This issue is similar to #11975.  The proposed solution, i.e., to re-render the chart after scaling the container, corrects the issue for the X-coordinate but not the Y-coordinate.

#### Actual behaviour
If the container scale is greater than 1, the Y-coordinate of the tooltip is incorrect.  It appears above the point by an offset that appears to be proportional to the scale factor.

#### Live demo with steps to reproduce
https://jsfiddle.net/tkmiller3/5jgk6c98/

Use the +/- buttons to scale the ancestor.  Note the Y position of the tooltip when hovering over the points.

#### Product version
Highcharts v7.2.0

**Comment by KacperMadej** [comment]
Hi @tkmiller3 

Thank you for reporting the problem.

Looks like tooltip's distance is wrongly scaled.
As a workaround, you could update the tooltip's distance after the transform or just set it to zero to avoid the problem.

**Comment by tkmiller3** [comment]
Thank you for the quick response.  Can you advise how to set the tooltip distance?

**Comment by KacperMadej** [comment]
The relevant option is `tooltip.distance` - demo: https://jsfiddle.net/BlackLabel/snuzL6td/
It should be in API reference, but isn't, so it's another problem that should be fixed.

_Internal note:_
`tooltip.distance` is missing in docs

**Comment by tkmiller3** [comment]
Thanks very much.  I didn't like the looks of setting distance to 0, but found the following  to be a good solution:

  chart.update({
    tooltip: {
      distance: 10 / scale
    }
  });
  chart.render();

**Comment by EPurpl3** [comment]
> #### Live demo with steps to reproduce
> https://jsfiddle.net/tkmiller3/5jgk6c98/

Your jsfiddle works perfect for me with Highstock v8.1.2 (2020-06-16), solved all my problems. Thanks.
