### ISSUE TITLE
Error when toggling stacked/unstacked area series with nulls

### ISSUE THREAD

**Issue by KevinFernandes** [highcharts/highcharts#12033]
#### Expected behaviour
Stacked area series would return to normal area series (un-stacked)

#### Actual behaviour
Error when setting the series stacking to "undefined" (not stacked)

Uncaught TypeError: Cannot read property '1' of undefined
    at e (highcharts.src.js:33240)
    at d.getGraphPath (highcharts.src.js:33293)
    at drawGraph (highcharts.src.js:30303)
    at drawGraph (highcharts.src.js:33321)
    at d.render (highcharts.src.js:30659)
    at d.redraw (highcharts.src.js:30739)
    at highcharts.src.js:23769
    at Array.forEach (<anonymous>)
    at c.Chart.redraw (highcharts.src.js:23767)
    at d.update (highcharts.src.js:32806)

#### Live demo with steps to reproduce
This is a modified version of the Highcharts demo from here
[https://www.highcharts.com/demo/area-missing/gray](https://www.highcharts.com/demo/area-missing/gray)

[https://codepen.io/kevinfernandes/pen/XWryKvK](https://codepen.io/kevinfernandes/pen/XWryKvK)

Click the button to toggle from un-stacked to stacked, then click again to go from stacked to un-stacked and you get the error above.

Only happens when going from stacked to un-stacked.
Only happens with Area, not with line or bar series styles

#### Product version
The demo is using Highcharts only
The demo is using the web version of Highcharts.

#### Affected browser(s)
Chrome 77

**Comment by KacperMadej** [comment]
Hi @KevinFernandes 

Thank you for reporting the bug.

As a workaround, you would have to force points to be destroyed. You could do that using [`Series.setData()`](https://api.highcharts.com/class-reference/Highcharts.Series#setData) with `updatePoints` set to `false` or is you will remove the series first and add new ones in a second update ([`chart.update`](https://api.highcharts.com/class-reference/Highcharts.Chart#update) will be able to add and/or remove series if `oneToOne` flag is set to `true`).

_Internal note:_
Points after the second update do not have the stacking related properties (e.g. `rightCliff`) cleared.

**Comment by KevinFernandes** [comment]
Thanks for the workaround.
Is there any idea when this might get fixed?  Just curios if it will be within our release scope.

Thanks. :)

**Comment by KacperMadej** [comment]
Currently, we do not have ETA for the fix.
