### ISSUE TITLE
highcharts.d.ts PaneBackgroundOptions.backgroundColor has incorrect type

### ISSUE THREAD

**Issue by OmarMustafa** [highcharts/highcharts#12034]
#### Expected behaviour
PaneBackgroundOptions.backgroundColor should support string values.

#### Actual behaviour
It's currently of type `GradientColorObject`. It should be` GradientColorObject | string`
or maybe `(ColorString|GradientColorObject|PatternObject)` like `borderColor` type.

#### Product version
7.2.0

**Comment by KacperMadej** [comment]
Hi @OmarMustafa 

Thank you for reporting the TS definition mistake.

_Internal note:_
@bre1470 this issue could be merged with any other existing a general task related to using `ColorType` type for colors in all parts of the repo code if have or will have such ticket

**Comment by bre1470** [comment]
It is not decided, if we replace the pattern `ColorString|GradientColorObject|PatternObject` everywhere with the `ColorType` alias. It becomes a bit harder to understand color options in the API.

@TorsteinHonsi Should we promote `ColorType` everywhere instead of the type list?

**Comment by TorsteinHonsi** [comment]
> Should we promote ColorType everywhere instead of the type list?

In general I prefer the shorter `ColorType`. Depends on just how hard it would be to understand it in the API. The API page for the ColorType will lead further to the different subtypes, right?

**Comment by bre1470** [comment]
> The API page for the ColorType will lead further to the different subtypes, right?
Yes, each color type is then two clicks away, instead of one.
