### ISSUE TITLE
Columns are drawn at an angle when boost is enabled in a column chart

### ISSUE THREAD

**Issue by DavGer** [highcharts/highcharts#12047]
#### Expected behaviour
The columns should be drawn vertical

#### Actual behaviour
Some of the columns are drawn at an angle (kinda like domino's)

#### Live demo with steps to reproduce
https://jsfiddle.net/kbvxrno0/

#### Product version
Highstock JS v7.2.0 (2019-09-03)

#### Affected browser(s)
Chrome, Edge, Firefox, IE

**Comment by pawelfus** [comment]
Thank you for reporting the issue @DavGer 

Simplified demo: https://jsfiddle.net/BlackLabel/gmob3zct/

It seems that setting [`useGPUTranslations = true`](https://api.highcharts.com/highstock/boost.usePreallocated) resolves the issue: https://jsfiddle.net/BlackLabel/cL7tm5ex/

@cvasseng - FYI
