### ISSUE TITLE
Navigator handles bugs on touch

### ISSUE THREAD

**Issue by PAPIONbit** [highcharts/highcharts#12043]
### Expected behavior:
**Navigator handles** with **touch** on phones or browsers developing tools, **slip well**, when **liveDraw**  is **enable**.

### Actual behavior:
If scrollbar **liveRedraw** be enabled, by any **redrawing**, **touchStart** will **end**.
so we cant move the handles of navigator with one touch.

### Product version:
Highstock 7.2.0

### Where is the BUG?
The problem is in **highstock.src.js** in line number **41767**
the if is :
```
if (e.DOMType !== 'mousemove') {
```
but i think it should be :
```
if (e.DOMType !== 'mousemove' && e.DOMType !== 'touchmove') {
```

Best Regards

**Comment by pawelfus** [comment]
Thanks for reporting the issue @PAPIONbit
