### ISSUE TITLE
Nothing rendered using chart.renderTo configuration option 

### ISSUE THREAD

**Issue by mablebee** [highcharts/highcharts#12056]
#### Expected behaviour
chart.renderTo does not work as described in the documentation

#### Actual behaviour
Nothing is rendered when using the chart.renderTo configuration option

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/treemap-large-dataset/

When changing the original code:

    Highcharts.chart('container',{
        series: [{
            type: 'treemap',
            layoutAlgorithm: 'squarified',
            allowDrillToNode: true,
            animationLimit: 1000,
            dataLabels: {
                enabled: false
            },
            levelIsConstant: false,
            levels: [{
                level: 1,
                dataLabels: {
                    enabled: true
                },
                borderWidth: 3
            }],
            data: points
        }],
        subtitle: {
            text: 'Click points to drill down. Source: <a href="http://apps.who.int/gho/data/node.main.12?lang=en">WHO</a>.'
        },
        title: {
            text: 'Global Mortality Rate 2012, per 100 000 population'
        }
    });

to:

    Highcharts.chart({
    		chart: [{
        		renderTo: 'container',
        }],
        series: [{
            type: 'treemap',
            layoutAlgorithm: 'squarified',
            allowDrillToNode: true,
            animationLimit: 1000,
            dataLabels: {
                enabled: false
            },
            levelIsConstant: false,
            levels: [{
                level: 1,
                dataLabels: {
                    enabled: true
                },
                borderWidth: 3
            }],
            data: points
        }],
        subtitle: {
            text: 'Click points to drill down. Source: <a href="http://apps.who.int/gho/data/node.main.12?lang=en">WHO</a>.'
        },
        title: {
            text: 'Global Mortality Rate 2012, per 100 000 population'
        }
    });

nothing is rendered

#### Product version
Current online version

#### Affected browser(s)
Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Hi @mablebee 

Thanks for reporting the issue. This part is wrong: 
```js
chart: [{
    renderTo: 'container',
}],
```

Should be:
```js

chart: {
    renderTo: 'container',
},
````
