### ISSUE TITLE
Overlapping legend items when layout: 'proximate',

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#12055]
#### Expected behaviour
Legend items should not overlap each other with layout: 'proximate' but should be separated from each other. It should be possible to change padding between legend items.

#### Actual behaviour
Legend items overlap each other.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/nLuqh1wm/

**Comment by garybrain** [comment]
I use highstock a lot for some of the features and also use the Proximate.

Live demo with steps to reproduce
https://jsfiddle.net/0u3sfL26/

**Comment by TorsteinHonsi** [comment]
It's the `useHTML` setting that does it. Without it the padding is fine.

To do:
- Make the layout with `useHTML` identical to that without.
- Implement the existing `itemMarginTop` and `itemMarginBottom` options for proximate layout so that users can control the amount of padding.
