### ISSUE TITLE
percent compare stock chart throwing console error if the series data has only single value.

### ISSUE THREAD

**Issue by manojdaggubati** [highcharts/highcharts#12058]
#### Expected behaviour
Should render the single value

#### Actual behaviour
Console Error : <path> attribute d: Unexpected end of attribute. Expected number, "M 428 "
And also doesn't display the single value. 

#### Live demo with steps to reproduce
https://jsfiddle.net/manoj_dmc/nermpwsb/2/

#### Product version
Reproducible in the latest version also.

**Comment by pawelfus** [comment]
Thanks for reporting the issue @manojdaggubati

**Comment by TorsteinHonsi** [comment]
Simplified demo: https://jsfiddle.net/highcharts/8wtd6ym3/2/
