### ISSUE TITLE
In highcharts gantt could series.gantt.data.parent accept an array for multiple parents

### ISSUE THREAD

**Issue by danielroach** [highcharts/highcharts#12057]
#### Expected behaviour
Some highcharts gantt subtasks could belong to more than one parent task, ie if it is a task in a project and it belongs to more than one task category we might want it to show up twice in the gantt view once under each parent item.

Would it be possible to please consider an option to specify multiple parent tasks in gantt by accepting an array for the `series.gantt.data.parent` option?

#### Actual behaviour
series.gantt.data.parent only accepts a string value, ie it does not work with the multiple containing value use case scenario we have come across

https://github.com/highcharts/highcharts/blob/14ec92bc4/js/parts-gantt/GanttSeries.js#L331-#L341

&

https://api.highcharts.com/gantt/series.gantt.data.parent

#### Live demo with steps to reproduce

https://jsfiddle.net/me6ngf8x/1/
Notice line 44

#### Product version
Highcharts Gantt 7.1.3

#### Affected browser(s)
Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Thanks for sharing the idea @danielroach !

FYI: @jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
Thanks again for sharing the idea @danielroach.

We will consider implementing this feature during our continuous development of Highcharts.
One note to consider is that this may require some complex adjustment to the internal logic, as a data entry can now represent 1 or many points.

**Workaround:**
It is possible to achieve this by adding functionality to transform your data before you pass it into the chart. E.g https://jsfiddle.net/jon_a_nygaard/ep0bjao5/9/
The example provided in this comment is quite simple and does not account for children of the points with multiple parents, but it demonstrates the concept.

**Comment by danielroach** [comment]
Thank you very much for the workaround @jon-a-nygaard that was very helpful, I hadn't considered approaching it like that.
