### ISSUE TITLE
Is  there a way to reference group colors?

### ISSUE THREAD

**Issue by rchancey** [highcharts/highcharts#12050]
I am using the scatter 3D chart. 

I  am trying to set the color on individual  points.. because as  I  create each point it needs a color based on the state of the data. 

I do  this by passing in a radial color .. such as this:
{
        name: data.name,
        radialGradient: { cx: 0.5, cy: 0.3, r: 0.7 },
        stops: [
            [0, '#FD8645'],
            [1, Highcharts.Color('#FD8645).brighten(-0.3).get('rgb')] // darken
        ]
    };

and set on the point  using this:

 x,  y, z, marker: { fillColor: getRadializedColor("blue"), radius: 8, symbol: "triangle" }

but I am having to pass in a LOT of data and it is slowing down the render.. I rather just  set the  colors using  
Highcharts.setOptions({
  colors: myColors});

but how do I reference a color ? I tried  a few  things but no  deal.. just somehow picks whatever color it wants

what would be nice is to say 'fillColor': 'red' and it reference the 'red' color in teh colorOptions.

This way the colors are global and referencable

anyone have any ideas?

**Comment by pawelfus** [comment]
Hi @rchancey 

I think this is the demo you are looking for: https://www.highcharts.com/demo/3d-scatter-draggable

You can observe how to set global [`colors`](https://api.highcharts.com/highcharts/colors) array. Then set `series.colorByPoint=true` and every point will pick color from `colors` array according to **it's index**. For example first point will pick first color, n-th point will pick n-th color. Once you have more points than colors, `colors` array will be reused (e.g. 3 colors => fourth point will pick first color).

That's not a perfect solution: let's imagine you want 10 red points and one blue. `color` array doesn't allow such configs. You would need to add null points to solve such problem:
```
colors: ['red', 'blue'],
...
series: [{
  data: [
    [1, 1, 1], // red
    [2, 2, 2], // blue
    [3, 3, 3], // red
    null, // blue
    [4, 4, 4], // red
    null, // blue
    [5, 5, 5], // red
    null, // blue
    ...
 }]
```

Alternative solution is to use colorAxis (if there's some logic behind the colors, e.g. custom parameter to decide which color should be used). See demo: https://jsfiddle.net/BlackLabel/d1k2b4hm/ (dataClasses are connected to y-value by default, controlled by [`series.colorKey`](https://api.highcharts.com/highcharts/series.scatter.colorKey)).

Regarding performance, I think you need to explain `a LOT of data` - maybe you render 1 000 000 of points and this will be simply slow.

**Comment by rchancey** [comment]
well, the performance thing.. if you go to the demo you pasted.. just take the series and copy and paste until you have ~1000 points.. and then drag the chart.. and you will see. So I don't think the performance has anything to do with my passing the colors.. I thought it did but just in that demo you can replicate the lagginess with raw points.

On the color passing.. I need too specify each point color and size.. I guess I could always create a series for each specific color and each specific size.. seems heavy handed though.

I will look at the links you sent.. but please do copy and paste and just create a 1000 point series and drag the chart around and please let me know what we can do to improve the performance.

I am using the burst package .. not that big a help somehow. 

thank you for responding btw.. sorry I put this on the bug channel.. but lets be honest a 1k element series should not be laggy (maybe an excuse for me asking on this channel hee hee) ..

**Comment by pawelfus** [comment]
In general we recommend to [turn off markers](https://www.highcharts.com/docs/getting-started/frequently-asked-questions#optimize-performance), but for a scatter series that doesn't make sense. Boost module (I assume this is what you mean by burst package?) is designed for 2D charts.

Let me explain a little the problem here: it's number of DOM elements - every marker is another DOM element, so every operation for reading/setting properties takes time. I did quick profiling on this demo: https://jsfiddle.net/BlackLabel/tq15627g/ - out of ~3s of dragging, ~1.9s was spent on zIndexing elements. In SVG there's no zIndex (like in HTML), the element rendered later is rendered in front. We emulate zIndexing (so correct markers are in front of others, crucial for 3D) by removing and reinserting elements at correct positions. If we add other DOM operations (fill, x+y position opacity etc.) - we get ~2.5s in setting/animating attribs.

Attaching CPU profile:
[highcharts-12050.cpuprofile.zip](https://github.com/highcharts/highcharts/files/3643102/highcharts-12050.cpuprofile.zip)

**Comment by rchancey** [comment]
yes.. sorry I meant Boost.. my bad. I was not aware it was only for 2D.. dang.. seems like a good idea to use that  for the 3D charts as well since can render on the GPU  if the device has it. 

So I understand the number of DOM elements and not using markets.. but again if you just take the demo here:  https://www.highcharts.com/demo/3d-scatter-draggable and just copy and paste the series 10 times.. you  will see the lag..and no markers or anything.. just raw array of data. 

I know you have a series that has 1m points.. but that is 2D and not being dragged.

So, any ideas on how to improve the render lag when dragging on that demo above?

**Comment by pawelfus** [comment]
Yes, probably implementing 3D in webGL should improve performance - could you create an idea on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api)? If this gets popular we will invest some resources to implement this.

Regarding markers, I don't mean `marker` options, but point markers, like this one:
![Screen Shot 2019-09-24 at 11 01 31](https://user-images.githubusercontent.com/1453926/65497530-b268b280-deba-11e9-8dbb-eb6ed84fb551.png)

I don't see any way to improve performance in my demo above (https://jsfiddle.net/BlackLabel/tq15627g/) - JS<->DOM communication seems to be the bottleneck.
