### ISSUE TITLE
Breaking changes with addSeries in version 6

### ISSUE THREAD

**Issue by gebeuhler** [highcharts/highcharts#12065]
Cannot see series when upgrade to version 6+, series is added with chart.addSeries(). Works in 5.0.14.

Any ideas?

` $scope.chart.addSeries({
                id: id,
                name: name,
                type: 'line',
                data: dataPoints
              });`

dataPoints is array of x and y values

**Comment by sebastianbochan** [comment]
Hi @gebeuhler,
Thank you for contacting us. For the general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.
