### ISSUE TITLE
Bubbles get stuck in packed bubble chart

### ISSUE THREAD

**Issue by abisha-thapa** [highcharts/highcharts#12063]
#### Expected behaviour
All chart bubbles should be moving along with outer big bubble in UI.

#### Actual behaviour
This UI issue is random in nature.
![image](https://user-images.githubusercontent.com/18100706/65600619-33f63880-dfc0-11e9-9deb-3024c2a947bc.png)

#### Product version

Highcharts version 7.2.0

**Comment by sebastianbochan** [comment]
Hi @abisha-thapa,
Thank you for reporting about the problem. When I run the demo: https://jsfiddle.net/hc6f347s/ I was not able to reproduce the problem. Could you update my demo with your simplified code? It will allow me to debug it.

**Comment by abisha-thapa** [comment]
Hi @sebastianbochan,

It took a lot of effort to replicate it in the fiddle. Finally, here is the demo: https://jsfiddle.net/abisha/zoL94hxy/2/
However, it is sporadic for some combination of width and height.

**Comment by pawelfus** [comment]
Thanks @abisha-thapa !

Unfortunately, I'm unable to recreate the issue. Tried to refresh demo mulitple times, the end result is always the same:

![Screen Shot 2019-09-26 at 11 13 59](https://user-images.githubusercontent.com/1453926/65675765-fee4f700-e04e-11e9-94f3-b582d6aa606d.png)

**Comment by abisha-thapa** [comment]
![image](https://user-images.githubusercontent.com/18100706/65676237-3fed0380-e06f-11e9-8c46-84582dc555a4.png)

This is the chart rendered after simulation is finished.

**Comment by sebastianbochan** [comment]
Please let us know which browser you have.

**Comment by pawelfus** [comment]
This is the whole animation (you can observe "Germany" never leaves its parent, like on your screenshot):

![bubble](https://user-images.githubusercontent.com/1453926/65677098-4c626380-e051-11e9-948f-2716b270a899.gif)

I can also observe missing border in the parent bubbles - maybe there's an error in JS console that breaks the simulation? Could you provide OS + browser details? Thanks!

**Comment by abisha-thapa** [comment]
![captured](https://user-images.githubusercontent.com/18100706/65688137-4e94e400-e08a-11e9-835f-1882a85dcedf.gif)

**Browser:** Version 77.0.3865.90 (Official Build) unknown (64-bit)
I am able to replicate it in the other version of chrome as well.

**Comment by sebastianbochan** [comment]
Hi @abisha-thapa,
Please let us know about OS (including full number of version).

I was also not able to reproduce it:
- Chrome 77.0.3865.90 
- MacOSX 10.14.5 (18F132)

**Comment by abisha-thapa** [comment]
Hi @sebastianbochan,

OS: **ubuntu 16.04 LTS** **Linux 4.10.0-28**
There are no errors in the console.

You can reproduce it by altering the width and height. Probably in your case increasing the height pixel by pixel may help reproduce the issue.

**Comment by glennjhicks** [comment]
Hi @sebastianbochan I can reproduce with your given example https://jsfiddle.net/hc6f347s/. If you change the width of the window (sliding the JSFiddle bar), the points will recalculate and eventually they do leak out of the bubble. Obviously this is an extreme case, but I have reproduced it in the past with my own charts.

I know this thread is stale, but the problem still seems to exist.

Windows 10, Chrome 87.0.4280.141. No errors in console

![image](https://user-images.githubusercontent.com/17492006/104435279-1b7aaa80-5584-11eb-9959-5f0f3058cce3.png)

**Comment by PaulDalek** [comment]
Hi @glennjhicks 

Thank you for contacting us and providing us with more details. I’ve tested the demo on my side and I was able to reproduce the behavior.

**Simulation enabled**
![simulation-on](https://user-images.githubusercontent.com/19933566/104479512-cf4f5a80-55c3-11eb-9305-6377250707a1.gif)

**Simulation disabled**
![simulation-off](https://user-images.githubusercontent.com/19933566/104479540-d7a79580-55c3-11eb-9481-b1409f819bd6.gif)

Tested on:
- Chrome v87.0.4280.141
- Firefox v84.0.2
- Edge v87.0.664.75

FYI @pawelfus
