### ISSUE TITLE
Zone conflict with line series HOVER animation

### ISSUE THREAD

**Issue by PAPIONbit** [highcharts/highcharts#12061]
#### Expected behaviour
Setting zones, work well with all animations.

#### Actual behaviour
If you set any zone, animations never work anymore!

#### Live demo
Remove the comment about zone and compare:
https://jsfiddle.net/PAPIONbit/0p4oxs5y/25/

#### Product version
Highstock 7.2.0

Best Regards

**Comment by sebastianbochan** [comment]
Hi @PAPIONbit,
Thank you for contacting us. When I run your demo in both cases initial animation is triggered:
Zone:
![zone](https://user-images.githubusercontent.com/2115686/65599676-a524f400-df9e-11e9-8279-43a43121a91d.gif)

Non-zone:
![nzone](https://user-images.githubusercontent.com/2115686/65599681-a7874e00-df9e-11e9-9c8c-8eea5cac3524.gif)

Could you ellaborate your unworking demo in more details? Please leave us a browser details.

**Comment by PAPIONbit** [comment]
compare with this please:
[https://jsfiddle.net/PAPIONbit/0p4oxs5y/27/](https://jsfiddle.net/PAPIONbit/0p4oxs5y/27/)

I mean this settings will not work anymore:
```
			states: {
				hover: {
					animation: {
						duration:1200
					},
                                lineWidthPlus:10
				},
			},
```

**Comment by PAPIONbit** [comment]
### Where is the BUG?
With pleasure, I found the bug and dedicated it to its creators:
The problem is in **highstock.src.js** in line number **39231** in the **while**:
```
series['zone-graph-' + i].attr(attribs);
```
but i think it should be :
```
series['zone-graph-' + i].animate(attribs, stateAnimation);
```

Best Regards

**Comment by pawelfus** [comment]
Thanks for clarifying the issue!
