### ISSUE TITLE
Gantt chart time axis repeats week number

### ISSUE THREAD

**Issue by mwolochuk** [highcharts/highcharts#12076]
#### Expected behaviour
Week should not repeat

#### Actual behaviour
See screen shot - week 48 repeats:

![ganttrepeatweek](https://user-images.githubusercontent.com/17186271/65704063-b3c0e900-e03a-11e9-9354-84f981a0b080.png)

#### Product version
Highcharts Gantt 7.2

#### Affected browser(s)
Chrome

The following HTML page reproduces the issue. Note that you may need to adjust your computer timezone to cause the bug. It should reproduce with a time zone of GMT - 8.

<html lang="en">

<head>
	<title>Gantt Chart Bug</title>
	<script src="https://code.highcharts.com/gantt/highcharts-gantt.js"></script>
</head>
	
<body>

<div>
    <div id="container"></div>
</div>

<script type="text/javascript">
	var data = [{ name: 'Task #1', start: 1543865127000, end: 1545337863000}];
    
Highcharts.setOptions({
	time: {
        timezoneOffset: 7*60
    }
});

Highcharts.ganttChart('container', {
	
series: [{
	name: 'Task',
    data: data,
}]
});

</script>
</body>
</html>

**Comment by pawelfus** [comment]
Thanks for reporting the issue @mwolochuk 

Demo moved to jsFiddle: https://jsfiddle.net/BlackLabel/v4mcgw62/3/

**Comment by TorsteinHonsi** [comment]
> Demo moved to jsFiddle
I don't that timezone actually displayed the issue. This one does: https://jsfiddle.net/highcharts/qju1te8g/1/

**Comment by karolkolodziej** [comment]
It looks like this issue was solved in the 8.0.1 version.
Live demo: https://jsfiddle.net/BlackLabel/wcxLsamy/

**Comment by pawelfus** [comment]
Thanks! Closing the issue then. If this happens again, please let us know.
