### ISSUE TITLE
zIndex of halo not work, if markers be enabled in plotOption

### ISSUE THREAD

**Issue by PAPIONbit** [highcharts/highcharts#12079]
### Expected behavior:
Any kind of **setExtreme**, do not change the zIndex of any object. Specially when we have markers and labels and etc...

### Actual behavior:
If you have markers enabled. (Try to have some different color fill to see it)
```
       	plotOptions: {
			series: {
				marker: {
					enabled:undefined,
					enabledThreshold: 3.2,
					radius: 4.6,
					fillColor:'#ffffff',
					lineColor:this.color,
					lineWidth: 2,
				},
```
Then hover a point to **halo** be made.
Then set 2 Time **setExtreme** from 10% of end of xAxis to 10% of first of xAxis. (We want to push the render function to just **redraw all of point again** [no any point be left])
Like this:
![ezgif-4-d67288490cd8](https://user-images.githubusercontent.com/47592258/65720921-d7754500-e0b5-11e9-8bb2-1482f2dbb490.gif)
look at the dear halo:
![image](https://user-images.githubusercontent.com/47592258/65721082-3a66dc00-e0b6-11e9-98bb-56a5335725c7.png)
**Halo position** will go on top of markers!
### JsFiddle
[https://jsfiddle.net/PAPIONbit/yg07r4aw/](https://jsfiddle.net/PAPIONbit/yg07r4aw/)

### Product version:
Highstock 7.2.0

### Where is the BUG?
It can be in a few wrong deciding, like:
- A) why all point be removed, when we are sure we want to draw again?
- B) why halo be not special about add in the SVG group?
- **C)** why makers have no zIndex option to **zIndexSetter** Function can help us
but i choosed **C**.

The problem can be fixed in **highstock.src.js** before line number **27792** in **marker** default options:
```
                 * States for a single point marker.
                 */
                states: {
                    /**
```
but i think it better to be something like this:
```
                 * States for a single point marker.
                 */
                zIndex:0,
                states: {
                    /**
```
to zIndexSetter can decied and data-z-index="-1" be not useless.

+ or any better idea

Best Regards

**Comment by pawelfus** [comment]
Thanks for reporting @PAPIONbit - nice work with debugging!

**Workaround:**
Set `marker.zIndex`: 

```js
      marker: {
        enabled: undefined,
        enabledThreshold: 3.2,
        radius: 4.6,
        fillColor: '#ffffff',
        lineColor: this.color,
        lineWidth: 2,
        zIndex: 1 // workaround
      },
```

*Internal note:*
The issue comes from SVGRenderer: http://jsfiddle.net/BlackLabel/msp10g8n/ - adding an element without zIndex should be rendered above negative zIndexes.
