### ISSUE TITLE
Highcharts histogram crashes page on long decimals

### ISSUE THREAD

**Issue by wenyichen** [highcharts/highcharts#12077]
#### Expected behaviour
Renders correctly

#### Actual behaviour
Crashes page

#### Live demo with steps to reproduce
https://jsfiddle.net/me0d795h/19/

#### Product version
Highcharts / Highstock 7

#### Affected browser(s)
Chrome >=15 digits after decimal point
Firefox >=14 digits after decimal point
Safari >=14 digits after decimal point

**Comment by pawelfus** [comment]
Thanks for reporting the issue @wenyichen !

**Comment by sebastianbochan** [comment]
Still valid in HC v8.

MacOSX: 10.14.5
Chrome: 79.0.3945.88

**Comment by mariomacedo** [comment]
Any chances of fixing it any time soon?

Thanks.

**Comment by sebastianbochan** [comment]
I run the demo: https://jsfiddle.net/me0d795h/19/ and was not able to reproduce the issue at this moment. 

Could you share your browser/os details?

Chrome: 80.0.3987.132

**Comment by sebastianbochan** [comment]
_Internal note_
FYI @Denyllon

**Comment by Denyllon** [comment]
Thank you for summoning @sebastianbochan, I will take a look on that in upcoming week.
