### ISSUE TITLE
Datalabels misplaced in 3D Pie Chart

### ISSUE THREAD

**Issue by yogesh-mali44** [highcharts/highcharts#12078]
Expected behaviour
When dataLabels.enabled is set to true, the dataLabels should be displayed properly.

Actual behaviour
The dataLabels are displayed incorrectly.

Live demo with steps to reproduce
https://jsfiddle.net/yogesh44/s6z1u0r5/1/

Affected browser(s)
Chrome

**Comment by yogesh-mali44** [comment]
I have an enterprise edition of highcharts and would line the datalabels to be inside the chart. I have noticed that this is a known issue with the bar chart, so wanted to check if its a known issue with 3D pie chart as well.

**Comment by sebastianbochan** [comment]
Hi @yogesh-mali44,
Thank you for reporting about the problem. Its know bug which has been reported here: https://github.com/highcharts/highcharts/issues/3259.

Im closing this issue as duplicate.
