### ISSUE TITLE
ReferenceError: Can't find variable: modules

### ISSUE THREAD

**Issue by prasadrajacse** [highcharts/highcharts#12080]
I am trying to implement highcharts wrapper within react-native application following this 

https://www.highcharts.com/blog/post/creating-mobile-charts-with-highcharts-react-native/

On running the app with expo start on device, it returned me below error

Warning: %s: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI., RootErrorBoundary

ReferenceError: Can't find variable: modules * App.js:21:8 in render

Line 21 of App.js have the highcharts container HighchartsReactNative

Any leads will be highly helpful

**Comment by sebastianbochan** [comment]
Hi @prasadrajacse,
Thank you for contacting us. You should declare modules as array.

```
const modules = [
    'highcharts-more',
    'solid-gauge'
];
```

You can find more info in our docs (Readme.md) here:
- https://github.com/highcharts/highcharts-react-native

For the future bugs in react native wrapper, please use the repo: https://github.com/highcharts/highcharts-react-native
