### ISSUE TITLE
Disable autoRotation but keep auto calculated step and line breaks

### ISSUE THREAD

**Issue by smokir** [highcharts/highcharts#12094]
Initial state:

`xAxis` with `categories`, `xAxis.labels.autoRotation: [0]` (which behavior looks the same as `xAxis.labels.autoRotation: false`), `xAxis.labels.autoRotationLimit: 55`:

<img width="685" alt="Снимок экрана 2019-09-28 в 19 53 32" src="https://user-images.githubusercontent.com/2204174/65820023-d31f6800-e22c-11e9-97d6-6d708cd03538.png">

#### Expected behaviour

On resize hide some labels and keep line breaks in visible labels:

<img width="396" alt="Снимок экрана 2019-09-28 в 20 02 33" src="https://user-images.githubusercontent.com/2204174/65820027-e29eb100-e22c-11e9-8416-998c0eb9313a.png">

`staggerLines` and `step` is not a solution for us.

#### Actual behaviour

On resize all labels stays and truncates with ellipsis:

<img width="396" alt="Снимок экрана 2019-09-28 в 20 02 47" src="https://user-images.githubusercontent.com/2204174/65820031-ed594600-e22c-11e9-8ac2-8b9394611adc.png">

The closest I can get to expected result is by setting `xAxis.labels.autoRotation: [1]` which at least hides some labels, but it looks like it leaves only first and last, and still loses line breaks for labels:

<img width="398" alt="Снимок экрана 2019-09-28 в 20 03 01" src="https://user-images.githubusercontent.com/2204174/65820037-f64a1780-e22c-11e9-8f4f-637e008c2ea2.png">

#### Live demo with steps to reproduce

https://jsfiddle.net/1jetp6df/

#### Product version

Highcharts 7.2.0

#### Affected browser(s)

Chrome 75.0.3770.2015
Firefox 69.0.1
Safari 12.1.2

**Comment by sebastianbochan** [comment]
Hi @smokir,
Thank you for the reporting. I agree with your point of view and the problem looks like more complex. But as a workaround you can set `useHTML` and declare `word-break` CSS style for labels which allows you to achieve your expectation.

```
.highcharts-xaxis-labels {
  width: 50px!important;
  word-break: break-all!important; 
}
```

**Demo:**
- https://jsfiddle.net/BlackLabel/9g1x35pk/

**Comment by pawelfus** [comment]
Did you consider using `datetime` axis instead? Demo: https://jsfiddle.net/BlackLabel/xd7rm82f/
