### ISSUE TITLE
venn.src.js:723 Uncaught Error: f(a) and f(b) must have opposite signs.

### ISSUE THREAD

**Issue by jakub-sterba** [highcharts/highcharts#12097]
#### Expected behaviour
Venn diagram is displayed

#### Actual behaviour
Venn diagtam is not displayed + exception in console:

Uncaught Error: f(a) and f(b) must have opposite signs.
    at L (venn.src.js:723)
    at f (venn.src.js:906)
    at M (venn.src.js:923)
    at venn.src.js:961
    at Array.reduce (<anonymous>)
    at X (venn.src.js:937)
    at d.translate (venn.src.js:1429)
    at highcharts.src.js:24833
    at Array.forEach (<anonymous>)
    at c.Chart.renderSeries (highcharts.src.js:24832)

#### Live demo with steps to reproduce
https://jsfiddle.net/smLn35cz/

Chart options:
{"series":[
   {"type":"venn",
    "data":[{"sets":["A"],"value":269},
             {"sets":["B"],"value":4350},
             {"sets":["C"],"value":2330},
             {"sets":["A","B"],"value":131},
             {"sets":["A","C"],"value":9},
             {"sets":["B","C"],"value":12},
             {"sets":["A","B","C"],"value":8}] 
    }]
}

#### Product version
Highcharts 7.2.0

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @jakub-sterba,
Thank you for reporting about the problem.

FYI @jon-a-nygaard
