### ISSUE TITLE
Panning is not working properly after zoom

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#12099]
#### Expected behaviour
It should be possible to pan in both directions.

#### Actual behaviour
When the `xAxis` extremes are initially set to a data extremes, it's not possible to pan the chart in both horizontal directions **after zoom**.

#### Live demo with steps to reproduce
https://jsfiddle.net/kr7nedsg/
Try to pan the chart to the right

#### Product version
v7.1.3 and above

_Internal Note:_
_Bisected to: https://github.com/highcharts/highcharts/commit/af07e43a560fb699892600c4c7a36ea94932ab68_

**Comment by TorsteinHonsi** [comment]
This fix goes back to https://github.com/highcharts/highcharts/commit/49e6611965fece884365912cfc388f0551cf5dc5.

**Comment by AleksandrPogorielov** [comment]
Look like the issue is still presented in version 9.3.0.

**Comment by karolkolodziej** [comment]
In version 9.3.0 I'm still able to pan after pressing the alt/option key.
Demo: https://jsfiddle.net/BlackLabel/8b41v7zo/

Could you please try that and let me know what am I missing here?

**Comment by AleksandrPogorielov** [comment]
Yes, you are right, it works with option key, thank you! I was using zooming tool from the toolbar and thought it will be switched off after usage.

BTW: Do you know the right version for zooming with mouse wheel? I've switched from v. 9.0.1 to 9.3.0 because of another issue, and figured out zooming with a wheel does not work anymore...

**Comment by karolkolodziej** [comment]
In version 9.3.0 we removed the axis from the map and the workaround for zooming with the mouse wheel doesn't longer work.
You might find a potential workaround replacement and explanation  in this request: https://github.com/highcharts/highcharts/issues/16658

**Comment by AleksandrPogorielov** [comment]
Thank you so much @karolkolodziej  !
