### ISSUE TITLE
TickInterval and tickpositions of yAxis get changed when chart height is decreased for lengthy xAxis datalabels 

### ISSUE THREAD

**Issue by protimamondal** [highcharts/highcharts#12103]
#### Expected behaviour

Irrespective of the chart height the yAxis  categories should not reduce in number 

#### Actual behaviour

When the chart height and width are more ,the categories of yAxis are rendering properly 5 ,
but when the height and width are less and the datalabel of xAxis names are lengthy then the categories of yAxis are getting reduced to 3 . 

<img width="773" alt="no_issue" src="https://user-images.githubusercontent.com/52485089/65882511-c9c00800-e3b2-11e9-9778-92b8f3570836.PNG">

<img width="360" alt="collapsed_datalabel" src="https://user-images.githubusercontent.com/52485089/65882521-cf1d5280-e3b2-11e9-8f3f-c4215f6c5289.PNG">

**Comment by pawelfus** [comment]
Hi @protimamondal 

Thank you for reporting the issue! Could you provide some more details? What exactly is reduced to 3 or rendered 5? And please provide **live demo** of the issue (e.g. jsFiddle) :) Thanks!

**Comment by TorsteinHonsi** [comment]
@protimamondal This is the correct behaviour as per the [tickInterval](https://api.highcharts.com/highcharts/yAxis.tickPixelInterval) option, which "sets the approximate pixel interval of the tick marks". There are many options available if the default behaviour doesn't suit you. You can use the `tickInterval` option to set a fixed tick interval regardless of scale, use `tickAmount` to always apply 5 ticks, use the `tickPositions` option for a predefined array of tick positions, or the `tickPositioner` callback for your own decisions. Among others.
