### ISSUE TITLE
single datapoint chart

### ISSUE THREAD

**Issue by cisxadmin** [highcharts/highcharts#1210]
Hi,

a chart with a single data point has a couple of minor problems:
the point does not show in the chart (unless the mouse is near it to cause it to highlight)
the point does not show on the navigator minichart.

ex of data
[
[1173859203000,null],
[1195482600000,92.827],
[1343391083000,null]
]

**Comment by siva-veeranki** [comment]
@TorsteinHonsi do we have any alternate approach to handle this scenario without enabling markers?

**Comment by sebastianbochan** [comment]
@siva-veeranki In the case that you have a single point, you cannot draw a line, due to mathematical reasons. As a result you can only draw a marker.

**Comment by siva-veeranki** [comment]
Ok @sebastianbochan, understood your point, I would like to try for an approach of enabling markers only for the single data points so that markers wont appear for all data points and also not missing the single data points. Is this sounds feasible? please share your suggestions...

**Comment by TorsteinHonsi** [comment]
Here's a small hack that you can use to temporary enable markers when there is only a single point: http://jsfiddle.net/w2ouwccw/

**Comment by siva-veeranki** [comment]
Oh yeah, this makes sense @TorsteinHonsi, thanks for your suggestion, this helped me to find an approach to handle my scenario.

**Comment by KarmaProd** [comment]
@siva-veeranki could you please share your workaround? @TorsteinHonsi 's hack doesn't work when handling a point surrounded by nulls, which is @cisxadmin 's case and my case too, see this fiddle: http://jsfiddle.net/KarmaProd/w2ouwccw/2/

**Comment by KacperMadej** [comment]
@KarmaProd Please try with getting valid points (not nulls) instead of all series points - demo: http://jsfiddle.net/w2ouwccw/3/

**Comment by KarmaProd** [comment]
@KacperMadej Thanks for helping. Your workaround works well in one of my graphics, while it doesn't in another where a lot of data manipulation is involved. Can you explain how/why it works, so I can try to extend it? Sorry if this is not the place for this kind of requests, but I could find almost no information about getValidPoints().

**Comment by KacperMadej** [comment]
@KarmaProd It would better to use other support channels (https://www.highcharts.com/support). However, the function returns the series points with null points filtered out. So if you have two points surrounded by nulls, then you will get two points from the function and the wrapper will run the original (proceed) function. To get markers for all single points you could could parse your data and set marker options per point or edit the wrapper to do the same.

Demo with the wrapper: http://jsfiddle.net/w2ouwccw/4/

Demo with data parsed (to show how it should look): http://jsfiddle.net/w2ouwccw/5/
