### ISSUE TITLE
When machine timezone is IST and the highchart timezone offset is also IST. Then if we don't use "full hours" like "2:30pm" then dataGrouping.forced  is rounding x-axis time to "2:00pm".

### ISSUE THREAD

**Issue by KrnAggarwal** [highcharts/highcharts#12102]
#### Expected behaviour
The chart should show exact same time. i.e 2:30pm

#### Actual behaviour
The chart is showing 2:00pm

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/nvrz4L1g/

#### Product version
highcharts 7.1.2

#### Affected browser(s)
Chrome, Mozilla, IE (all latest)

**Comment by pawelfus** [comment]
Thanks for reporting the issue @KrnAggarwal 

**Workaround:**
Set [`dataGrouping.smoothed`](https://api.highcharts.com/highstock/series.column.dataGrouping) to true: https://jsfiddle.net/BlackLabel/d9o3qmg6/

**Comment by pawelfus** [comment]
Since v9.1.0 this can be controlled by setting [`dataGrouping.anchor`](https://api.highcharts.com/highstock/series.line.dataGrouping.anchor) option ([`dataGrouping.smoothed`](https://api.highcharts.com/highstock/series.line.dataGrouping.smoothed) is now deprecated).
