### ISSUE TITLE
yAxis labels stuck to chart plot area when scrollablePlotArea is enabled and useHTML is true

### ISSUE THREAD

**Issue by jacobworrel** [highcharts/highcharts#12112]
#### Live demo with steps to reproduce
Link: https://jsfiddle.net/jacobworrel/nbrec197/2/

Steps to reproduce:
1. scroll left to the middle of the chart
2. unselect both series by clicking on the two legend items
3. select one of the series again by clicking on one of the legend items

Chart options:
- scrollablePlotArea is enabled
- yAxis label useHTML is set to true

#### Expected behaviour
yAxis labels stay fixed to right/left masked areas when using the scrollablePlotArea feature after toggling all series on and off for that yAxis.

#### Actual behaviour
yAxis labels remain fixed to the chart plot area when using the scrollablePlotArea feature after toggling all series on and off for that yAxis.

#### Product version
highcharts 7.2.0

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @jacobworrel,
Thank you for reporting about the problem.

**Comment by gbt518** [comment]
@sebastianbochan This may be related but you can see the same behavior if you do a chart.update and change yAxis options:

https://jsfiddle.net/uzwxt7rm/

**Comment by jessicaonly** [comment]
Hey guys! Any update on this? I'm finding the same bug in my app. If it's helpful, for me it only seems to happen when the yAxis is aligned to the right (when it's left-aligned, it works fine). 

Thanks!

**Comment by pawelfus** [comment]
Hi @jacobworrel !

We don't have ETA for this issue. Meanwhile, please try my workaround: https://jsfiddle.net/BlackLabel/9vbn0jgq/

```js
  plotOptions: {
    series: {
      events: {
        legendItemClick: function() {
          var chart = this.chart;
          setTimeout(function() {
            chart.moveFixedElements();
          }, 0);
        }
      }
    }
  }
```

And workaround for @gbt518 

Demo: https://jsfiddle.net/BlackLabel/7daxgujb/
And snippet:
```js
setTimeout(() => {
  chart.update({
    yAxis: {
      title: 'New Title'
    }
  });
  chart.moveFixedElements()
}, 2000);
```

*Internal note:*
It seems either method is not called or related elements don't exist yet.
