### ISSUE TITLE
How to align highchart legend when using multiple pie chart in one container?

### ISSUE THREAD

**Issue by cyberfly** [highcharts/highcharts#12113]
Hi I have two pie chart in one container using HighCharts. 

Right now I want to align each pie chart legend so user can differentiate which legend belongs to which pie chart.

How to solve this?

Thanks

```
Highcharts.chart('container', {
    chart: {
        type: 'pie'
    },
    plotOptions: {
        series: {
        dataLabels: {
            enabled: false
        }
      }
    },
    series: [{
        size: '50%',
        center: ['25%', '50%'],
        data: [1, 2, 3, 4, 5, 6],
        showInLegend: true,
    }, {
        size: '50%',
        center: ['75%', '50%'],
        data: [1, 2, 3, 4, 5, 6],
        showInLegend: true,
    }]
});
```

#### Expected behaviour

Each legend align under their Pie Chart

#### Actual behaviour

Legend not align according to their Pie Chart

![image](https://user-images.githubusercontent.com/1756170/66027816-45928f80-e52e-11e9-8f88-5e7cf219546f.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/f9dLhuv0/

**Comment by sebastianbochan** [comment]
Hi @cyberfly,
Thank you for contacting us. The github is our bug tracker, so for general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email
