### ISSUE TITLE
Creating a High Charts Cloud demo while not logged in, then logging in, loses the chart

### ISSUE THREAD

**Issue by chrissmithhill** [highcharts/highcharts#12126]
#### Expected behaviour
Create and save a highcharts cloud chart while not logged in, log in and continue to edit save the same chart, or a copy of it.

#### Actual behaviour
Create and save a highcharts cloud chart while not logged in
Log in
clicking on any button on the existing chart asks you to log in again, then loads an empty chart, there is no way to go back to the chart you just produced, losing all your work.

**Comment by sebastianbochan** [comment]
Hi @chrissmithhill,
Thank you for reporting. I moved your ticket to the correct repo: highcharts/highcharts-cloud-issues#7
