### ISSUE TITLE
"Google Spreadsheet ID" has no help tooltip

### ISSUE THREAD

**Issue by chrissmithhill** [highcharts/highcharts#12128]
#### Expected behaviour
Hovering over "Google Spreadsheet ID" in the link a sheet form would provide an explanation of what a Google Spreadsheet ID is.

#### Actual behaviour
There is no explanation of what a google spreadsheet id is. It needs to be googled.

**Comment by sebastianbochan** [comment]
Hi @chrissmithhill,
Thank you for reporting. I moved your ticket to the correct repo: highcharts/highcharts-cloud-issues#5
