### ISSUE TITLE
High Charts Cloud Color Picker Moves around

### ISSUE THREAD

**Issue by chrissmithhill** [highcharts/highcharts#12129]
#### Expected behaviour
Data Series Color picker stays in the same place

#### Actual behaviour
When initially editing a data series color in the Customize section of High Charts Cloud, the picker is underneath the "Series Type" dropdown. 
When you go to edit another Data Series' color, the Negative Color picker has taken its place. It is highly confusing. 

#### Product version
High Charts Cloud

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @chrissmithhill,
Thank you for reporting. I moved your ticket to the correct repo: highcharts/highcharts-cloud-issues#4
