### ISSUE TITLE
High Charts Cloud - Load Spreadsheet button provides no feedback

### ISSUE THREAD

**Issue by chrissmithhill** [highcharts/highcharts#12127]
#### Expected behaviour
When Linking Google Sheet, in the Data section of the High Charts Cloud Editor, clicking "Load Spreadsheet" would provide success/fail feedback

#### Actual behaviour
When Linking Google Sheet, in the Data section of the High Charts Cloud Editor, clicking "Load Spreadsheet" does not provide any feedback on success/failure

#### Product version
HighCharts Cloud

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @chrissmithhill,
Thank you for reporting. I moved your ticket to the correct repo: highcharts/highcharts-cloud-issues#6
