### ISSUE TITLE
Variwide chart - Columns overlap while border width is set & chart size is small

### ISSUE THREAD

**Issue by rajeshdanabal** [highcharts/highcharts#12125]
#### Expected behaviour
While we have border for variwide chart, Columns in variwide chart should be displayed with out overlapping on each other.

#### Actual behaviour
Columns in variwide chart overlap on each other while chart size is small and border is set.

#### Live demo with steps to reproduce
https://jsfiddle.net/rajeshdanabal/mus90yhr/

#### Product version
Highstock JS v7.2.0

#### Affected browser(s)
Google Chrome - Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @rajeshdanabal,
Thank you for reporting about the problem.

Simplified demo:
- https://jsfiddle.net/BlackLabel/g7je0ovc/

**Comment by rajeshdanabal** [comment]
Hi @sebastianbochan,

Thank you for the reply, Is there any work around to fix this problem?

**Comment by sebastianbochan** [comment]
Hi @rajeshdanabal,
As a simple and limited workaround you can wrap the `translate` method and include borderWidth in calculation of xAxis positions.

Demo:
- https://jsfiddle.net/BlackLabel/c69qx150/

Please be aware that this solution is not complex and can not work with all data / params.
