### ISSUE TITLE
stackLabel misaligned when having a scrollable plot area in bar chart

### ISSUE THREAD

**Issue by akrmmar** [highcharts/highcharts#12133]
#### Expected behaviour
Labels should be aligned to each column

#### Actual behaviour
Labels are misaligned.

#### Live demo with steps to reproduce
https://jsfiddle.net/xhsrm9db/

#### Product version
7.1.2
7.2.0

#### Affected browser(s)
Google Chrome  77.0.3865.90 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Thanks for reporting the issue @akrmmar 

*Internal note:*
Horizontal axis' stack labels are fine: https://jsfiddle.net/u3f4ow2y/

**Comment by fabioman** [comment]
Hello,

I have this exact issue using Highcharts version v10.2.0

Can you please reopen the issue?

Greatings

**Comment by pawellysy** [comment]
Hi @fabioman, could you please share your demo, where the issue is reproduced? Thanks!

**Comment by raf18seb** [comment]
Hi @fabioman, thank you for providing a demo. Yes, a bug still exists and the issue will remain open.
Simplified demo: https://jsfiddle.net/BlackLabel/6u40fe7b/

**Comment by pkExec** [comment]
Can we push this to a priority? It's open for 2 years with no workaround.

**Comment by pawellysy** [comment]
Hi @pkExec, thanks for bringing our attention to this bug. We will prioritize it, and move further in our prioritization board 👍

**Comment by TorsteinHonsi** [comment]
Reopening, the fixing PR broke a test in Safari.
