### ISSUE TITLE
High Charts cloud - Color picker text is not always readable

### ISSUE THREAD

**Issue by chrissmithhill** [highcharts/highcharts#12130]
#### Expected behaviour
Color picker text is always readable

#### Actual behaviour
The color picker text box is the same color as the last selected color (why? no other color picker does that) making it hard/impossible to read entered text when on a light color.

#### Product version
Highcharts cloud

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @chrissmithhill,
Thank you for reporting. I moved your ticket to the correct repo: highcharts/highcharts-cloud-issues#3
