### ISSUE TITLE
High Charts Cloud - Advanced Customizer - Clicking on a Folder NAME opens but does not close folder

### ISSUE THREAD

**Issue by chrissmithhill** [highcharts/highcharts#12132]
#### Expected behaviour
Clicking on a Folder Name has On/Off Effect

#### Actual behaviour
Clicking on a folder name only opens the folder. 

#### Product version
High Charts Cloud

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @chetansastry,
Thank you for reporting. I moved your ticket to the correct repo: https://github.com/highcharts/highcharts-cloud-issues/issues/1
