### ISSUE TITLE
High Charts Cloud - Published chart is cut off by HighCharts Cloud Menu bar

### ISSUE THREAD

**Issue by chrissmithhill** [highcharts/highcharts#12131]
#### Expected behaviour
The published chart is fully visible

#### Actual behaviour
The published chart is cut off by the menu bar

#### Live demo with steps to reproduce
https://cloud.highcharts.com/show/yri5CC43-

#### Product version
High Charts cloud

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @chrissmithhill 

Thank you for reporting the problem.
Our Highcharts Cloud developers were notified about the problem.

**Comment by sebastianbochan** [comment]
Hi @chetansastry,
Thank you for reporting. I moved your ticket to the correct repo: highcharts/highcharts-cloud-issues#2
