### ISSUE TITLE
Workday and date are one day off

### ISSUE THREAD

**Issue by mgorabbani** [highcharts/highcharts#12147]
#### Expected behaviour
Workday and date are one day off
`1 May 2019` should be `Wednesday`. But it is showing `Thursday` in the tooltip.
i am using this format ` xDateFormat: '%A, %B %e, %Y',`

![image](https://user-images.githubusercontent.com/12911638/66203855-a98d9300-e6a9-11e9-99a0-c713cb648614.png)

#### Product version
 `  "highcharts": "^7.1.1",` - though i tried with latest version and its the same.

**Comment by pawelfus** [comment]
Hi @mgorabbani 

Thanks for reporting the issue, but when you report an issue, please provide live demo (e.g. in jsFiddle). I have tried to reproduce this but it looks fine: https://jsfiddle.net/BlackLabel/os4d16zf/ 

![Screen Shot 2019-10-04 at 15 31 19](https://user-images.githubusercontent.com/1453926/66211296-085c0800-e6bc-11e9-9277-95ae4a282e84.png)

**Comment by mgorabbani** [comment]
I cannot reproduce it. seems like it's on my code base
