### ISSUE TITLE
Wrong 'Tooltip.pointFormatter' type definition after parsing to d.ts

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#12145]
#### Expected behaviour
Context should indicate the Point object, and all series properties should exist on `this.series` within formatter function.

#### Actual behaviour
The `Tooltip.pointFormatter` definition is not correct after parsing to `highcharts.d.ts` file.
Before it looks like:
```ts
pointFormatter?: FormatterCallbackFunction<Point>;
```
when the `FormatterCallbackFunction` is:
```ts
interface FormatterCallbackFunction<T> {
    (this: T): string;
}
```
but after parse it looks like not complete or overwritten by something else:
```ts
pointFormatter?: () => void;
```

This cause errors within custom formatter function, a few 'does not exist' warnings, and wrong context
![image](https://user-images.githubusercontent.com/15111955/66201681-2c135400-e6a4-11e9-98f1-4a32129645f6.png)

**Comment by Denyllon** [comment]
@bre1470 ☝️

**Comment by sebastianbochan** [comment]
Live demo:
- https://stackblitz.com/edit/highcharts-cloning-chart-dvxmpu

**Comment by KacperMadej** [comment]
I did the testing for the issue and something was not refreshed correctly.
The actual problem is as you could see in the live demo, so in `tooltip.pointFormatter` the context is a point that has series as one of its properties. That series is of a type that doesn't allow accessing `color` property - neither directly (`series.color`), or through options (`series.options.color`).

**Comment by bre1470** [comment]
You have to define the `this` parameter of your formatter function to be of type `Highcharts.Point`. Additionally you try to cast the series to an option interface. You can find the options under `series.options`.

That said, there is no color property on the series instance on runtime. I do not see how this is a TypeScript bug.

**Comment by KacperMadej** [comment]
> You can find the options under `series.options`.

`color` isn't there, but `opacity` is.

**Comment by bre1470** [comment]
The color options is not supported by every series, therefor the series options have to be casted to a specific interface and then `color` options checked agains `undefined`.

**Comment by bre1470** [comment]
Further investigation shows, that the `supertrend` indicator is the only series, that does not support the `color` option. Maybe we can change this and then color becomes automatically a common series option.

**Comment by pawelfus** [comment]
I agree, we can `color` to `supertrend` (can be the same as `risingTrendColor` or `fallingTrendColor`). We have similar case for `candlestick` where we have `color` and `upColor`.

@wchmiel FYI
