### ISSUE TITLE
Legend update with proximate layout

### ISSUE THREAD

**Issue by mari-pwbm** [highcharts/highcharts#12159]
Using either chart.update() on the legend or chart.legend.update() does not behave as expected when changing the legend layout either to or from "proximate."

#### Expected behaviour
Update legend would update to label settings specified.

#### Actual behaviour
Proximate to horizontal: Legend drops out of view.

Horizontal to proximate: Legend items stack at top.

#### Live demo with steps to reproduce
Updating from proximate to horizontal
[https://jsfiddle.net/1curdyf6/1/](https://jsfiddle.net/1curdyf6/1/)

Updating from horizontal to proximate
[https://jsfiddle.net/Ldjvr3n0/](https://jsfiddle.net/Ldjvr3n0/)

#### Product version
Highcharts 7.2.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting the issue @mari-pwbm 

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/o06cdqvj/

Plugin:
```js
(function(H) {
  H.addEvent(
    H.Legend,
    'afterUpdate',
    function() {
      if (this.proximate) {
        this.unchartrender = H.addEvent(this.chart, 'render', function() {
          this.legend.proximatePositions();
          this.legend.positionItems();
        });

        this.proximatePositions();
        this.positionItems();

      } else if (this.unchartrender) {
        this.unchartrender();
        this.render();
      }

    }
  );
})(Highcharts);
```

**Comment by mari-pwbm** [comment]
Thanks! 

Just a heads up, I was trying to make the legend responsive and the workaround worked for moving from horizontal to proximate, but not the other way (see fiddle below).

[https://jsfiddle.net/p16zb5gj/](https://jsfiddle.net/p16zb5gj/)

I added a timeout to the function firing on resize to fix.

[https://jsfiddle.net/p16zb5gj/1/](https://jsfiddle.net/p16zb5gj/1/)

I also tried using the highcharts responsive property, which worked for going from proximate to horizontal, but there was a bug in going from horizontal to proximate (works if you resize again).

[https://jsfiddle.net/5z0fcpxd/](https://jsfiddle.net/5z0fcpxd/)
