### ISSUE TITLE
Set a fixed range - rangeSelector button

### ISSUE THREAD

**Issue by dolanmiu** [highcharts/highcharts#12158]
Hey,

I have a business requirement to set the range of a chart from 8AM to current time

![Screenshot 2019-10-07 at 17 50 55](https://user-images.githubusercontent.com/2917613/66331767-2aa78d00-e92b-11e9-9717-425b69867a1a.png)

Here is my code:

```ts
rangeSelector: {
            inputEnabled: false,
            allButtonsEnabled: true,
            buttons: [
              {
                type: 'minute',
                count: 10,
                text: 'live',
              },
              {
                type: 'all',
                text: '24h',
              },
              {
                text: 'Market Open',
                type: 'all',
                events: {
                  click: () => {
                    const startDate = new Date();
                    startDate.setHours(8);
                    const startDateMillis = startDate.getTime();
                    const currentDateMillis = new Date().getTime();

                    setTimeout(() => {
                      this.chart.xAxis[0].setExtremes(startDateMillis, currentDateMillis);
                    }, 400);
                  },
                },
              },
            ],
            buttonTheme: {
              width: 100,
            },
          },
```

Notice how the `Market Open` configuration is a little funny. It has `all`, and then an `event` handler to manually set the extremes. And how I need to do a `setTimeout` to correct it after `all` was applied. Messy.

This means the graph will do a little jump to `all` before going to the correct 8AM

Is there a better way to do this?

**Comment by sebastianbochan** [comment]
Hi @dolanmiu,
Thank you for contacting us. The github is our bug tracker so for general [support](http://www.highcharst.com/support) cases please use forum / stackoverflow or email.

**Comment by pawelfus** [comment]
Hi @dolanmiu 

To prevent default action return `false` (so you don't need `setTimeout`), see docs [`rangeSelector.buttons.events.click`](https://api.highcharts.com/highstock/rangeSelector.buttons.events.click).

Regarding `all` - it might be a little funny, but keep in mind that what you actually do is completely replacing logic hidden under the button. We don't provide hm.. `any` (?) template button. In theory you should use [`chart.renderer.button`](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#button) and manage all states and position of the button on your own.. I belivie it's much easier to use `type: "all"` :)
