### ISSUE TITLE
xAxis labels with useHTML are overlapping after few zooms

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#12154]
#### Behaviour
xAxis labels with `useHTML` set to `true` are overlapping after few zooms.
It looks like the problematic labels are too width due to some caching.

![labeloverlaphtml](https://user-images.githubusercontent.com/8960408/66311544-01790380-e90f-11e9-80ff-23c1a391292d.jpg)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/p0bt967d/
(The zooms are applied automatically)

#### Product version
7.2.0

#### Affected browser(s)
Probably all, but the problem might depend on the font size, so it's visible for sure in Chrome/Windows 10.

#### Workaround
Set in the labels style `'text-align': 'center'`.
Demo: https://jsfiddle.net/BlackLabel/p0bt967d/1/
(The labels still has the wrong width, but it is not visible)

**Comment by Jerome2606** [comment]
Please note that in my duplicated ticket, the workaround text-align: center is not working.
I'm stuck actually with this behavior :(.

Thanks for the help

**Comment by pawelfus** [comment]
Hi @Jerome2606 - but other workaround posted in #12238 does work for you, right? It's not that convenient as "text-align", but prevents from the bug.

**Comment by Jerome2606** [comment]
I finally removed the useHtml In my code

**Comment by KacperMadej** [comment]
a further activity occurs
