### ISSUE TITLE
Allow series `states` default behavior to be disabled

### ISSUE THREAD

**Issue by nzayatz14** [highcharts/highcharts#12156]
#### Expected behaviour

Currently there is no way to disable the default behavior of the `inactive` or `hover` states for a series. I would still like to use the series states programmatically, just not the default behavior of them. I have discussed with @pawelfus an another ticket about adding an option along the lines of `series.states.inactive.enabled` that would disable the default behavior of series states, while still allowing for the series state to be set programmatically.

Previous issue: https://github.com/highcharts/highcharts/issues/12120

#### Actual behaviour

Currently, to disable the default behavior for the `inactive` state, the changelog mentioned adding this block to the plotOptions
```
states: {
    inactive: {
        opacity: 1
    }
}
```
But this just updates the styling of the inactive state, not disabling the default behavior of it.

**Comment by pawelfus** [comment]
Thanks @nzayatz14 !

**Comment by Piedalu** [comment]
+1

In one of my charts, I want to highlight the selected point by decreasing the opacity of all others, but when I hover my chart the opacity is changing by itself !
This behaviour may be regarded as bug, in my opinion.

**Comment by TorsteinHonsi** [comment]
I agree, seems there is a need for being able to turn this off.

**Comment by pawelfus** [comment]
The commit above adds docs for `inactive.enabled` option. For now it's possible to **entirely** disable inactive state. That means `series.setState('inactive')` will be disabled too. 

It's possible, with a simple hack to programatically enable inactive state, demo: https://jsfiddle.net/BlackLabel/ak09qo2w/
Snippet:
```js
  series.options.states.inactive.enabled = true;
  series.setState('inactive');
  series.options.states.inactive.enabled = false;
```
