### ISSUE TITLE
Allow for category Axis to collapse when data is not present

### ISSUE THREAD

**Issue by nzayatz14** [highcharts/highcharts#12168]
#### Expected behaviour

It would be nice to have a way to collapse categories that do not have any data associated with them with an axis that has categories.

#### Actual behaviour

Currently it does not look like there is a way to collapse categories when there is no data for them. At least I could not find a way to do this in the documentation. It looks like items that do not have values on the outside of the axis are being trimmed, but if the empty category is between categories with values it will not be removed.

#### Live demo with steps to reproduce

https://jsfiddle.net/qz548g2o/

**Comment by pawelfus** [comment]
Thanks for sharing the idea @nzayatz14 

Related ticket: #7664

You can find a solution here: https://www.highcharts.com/forum/viewtopic.php?t=34905

Demo: https://jsfiddle.net/BlackLabel/bg1y23kn/
