### ISSUE TITLE
Offline exporting: workaround for previous browser bugs no longer needed

### ISSUE THREAD

**Issue by Tankzor** [highcharts/highcharts#12169]
`Highcharts.svgToDataUrl (modules/offline-exporting.src.ts)`

#### Expected behaviour
A CSP blocking "data:" scheme for img-src would still allow image export via "blob:"

#### Actual behaviour
Export fails in Firefox and (presumably) Safari, due to a workaround put in place for previous browser bugs.

```
// Safari requires data URI since it doesn't allow navigation to blob
// URLs. Firefox has an issue with Blobs and internal references,
// leading to gradients not working using Blobs (#4550)
```

Previous issue #4550 highlighted an issue with Firefox not handling internal references correctly, workaround was to fallback to "data:".

This has subsequently been fixed in Firefox. Related bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=841920
https://bugzilla.mozilla.org/show_bug.cgi?id=1280584
https://bugzilla.mozilla.org/show_bug.cgi?id=1447262

Also, there's a workaround in there for Safari with comment saying Safari does not allow navigation to "blob:", which I believe is also fixed (based on discussion in this issue, but I don't have a mac to check): https://bugs.webkit.org/show_bug.cgi?id=102914 

#### Affected browser(s)
Firefox & Safari (?)

**Comment by Tankzor** [comment]
here's a sample with a CSP, PNG export fails in Firefox/Safari (confirmed): http://www.tests.massivedev.com/highcharts/csp/

**Comment by Tankzor** [comment]
Quick update: I was able to make it work in Firefox by butchering the .IndexOf("") string to not match firefox (in the minified file) as a sort of proof the workaround is no longer needed.

Also I was able to make it work in Safari as well by doing a similar thing, but I also had to remove the ";charset-utf-16" from the mime-type to make it work in Safari - which could introduce other issues, I have no idea..

http://www.tests.massivedev.com/highcharts/csp/2/

Sorry, quite a hacky way to do it, but I hope it proves the workaround is no longer needed at least for Firefox..

**Comment by sebastianbochan** [comment]
Hi @Tankzor,
Thank you for reporting about the problem.

FYI @oysteinmoseng

**Comment by Tankzor** [comment]
stalebotnothankyou
