### ISSUE TITLE
Changing Chart Type With Dynamic dataLabels Removes That Data Value From View

### ISSUE THREAD

**Issue by wergeld** [highcharts/highcharts#12178]
#### Expected behaviour
Clicking on packedbubble circle to show dataLabel and changing chart type to bar should still show the dataLable or at the least not remove the value.

#### Actual behaviour
Clicking on a circle in packedbubble chart to enable the dataLabel works. Now click the button to change the chart type (we go from packed bubble to bar). That item's xAxis category label exists but the data point is not rendered. Clicking to enable a bar's dataLabel and then switching back to packedbubble chart "removes" that circle

#### Live demo with steps to reproduce
https://jsfiddle.net/y3kqajw7/
Click on center circle and note its name.
Click on the "Change Type" button.
Note that the category name has no value/bar drawn.

Click on a bar to show its dataLabel and note its  name.
Click on the "Change Type" button.
Note that the circle that would have contained that data element is no longer shown.

#### Product version
HighStock 7.1.2 and 7.2.0

#### Affected browser(s)
Chrome
IE

**Comment by wergeld** [comment]
So the solution is to put the value in twice in the series? I thought if I set the keys property for both the series types that would suffice to tell each series what their keys are.

**Comment by pawelfus** [comment]
That's correct and it works fine unless you update a point.

Maybe this demo will be better to explain what I mean: https://jsfiddle.net/BlackLabel/eduyhtpc/ - open console and click on a bubble. In console you can observe how `series.data` options look now:
```js
[
  [ ... ],
  ["Life, Physical, and Social Science", 6980, 0, 0, "190000", "rgb(251,154,153)"],
  ...
  { name: "Office and Administrative Support", value: 150090, supp: 0, priv: 0, idx: "430000" ... }, // <- object generated after point.update
  ...
  [ ... ],
  [ ... ]
]
```

`series.keys` are used only for arrays, not for objects. This object was build from `keys` for Series A, then when you change series type to Series B, and Series B requires different key for value (`y` vs `value`) then point doesn't have this information.

**Comment by wergeld** [comment]
If it works it works. I just want to be sure that doing the following is not proper:
```
plotOptions.bar.keys: ['name', 'y', 'supp', 'priv', 'idx', 'color', 'dataLabels.enabled']
plotOptions.bar.packedbubble: ['name', 'value', 'supp', 'priv', 'idx', 'color', 'dataLabels.enabled']
```

Where my data looks like:
`['Office and Administrative Support', 150090, 0, 0, '430000', colorbyTaxonmyParent('430000'), false]`

Seems like if i am explicitly given the keys definition in plotOptions it should work? Adding in the y/value entries in twice looks more like a workaround.

**Comment by pawelfus** [comment]
>  I just want to be sure that doing the following is not proper:

This is proper.

> Where my data looks like: (...)

Data looks that way **until you update a point**.

> Seems like if i am explicitly given the keys definition in plotOptions it should work?

It works - but it works **only for arrays**.

> Adding in the y/value entries in twice looks more like a workaround.

Yes, you can call it workaround. From my perspective it's a configuration that gives chart all necessary info for your use case.

Of course, it would be great to support your case, but I would rather expect `point.update(['Office and Administrative Support', 150090, 0, 0, '430000', colorbyTaxonmyParent('430000'), true])` in use. Then we could improve the solution. When you update point with object (`{ dataLabels: { enabled: true } }`), then I think the current workflow is correct. I'm leaving this ticket open, to be decided in future.
