### ISSUE TITLE
3D area charts

### ISSUE THREAD

**Issue by gypjoy** [highcharts/highcharts#12171]
How to draw 3D area chart by highcharts

**Comment by sebastianbochan** [comment]
Hi @gypjoy,
Thank you for contacting us. The github is our bug tracker so for general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or forum.

ps. You can try to use the contour plugin, which allows you to draw a custom shapes.

Ref:
- https://www.highcharts.com/plugin-registry/single/35/contour
