### ISSUE TITLE
The pie chart is not round

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#12170]
#### Expected behaviour
Display the pie chart correctly
#### Actual behaviour
The pie chart is not round
![QQ截图20191009102918](https://user-images.githubusercontent.com/6789138/66447485-06f65b00-ea81-11e9-9ed3-e3d02dfd985b.png)

#### Product version

"highcharts": "^7.2.0",
 "highcharts-vue": "^1.3.5",
#### Affected browser(s)
 Google Chrome 76.0.3809.100（正式版本） （64 位）

**Comment by sebastianbochan** [comment]
Hi @wjhcc2018,
     Thank you for reporting about the problem. Could you elaborate your question in more details? It will allow us to understand your problem and find a solution.

     Please let me know if problem is with dataLabels which are wrong i.e connectors or labels?

**Comment by wjhcc2018** [comment]
@sebastianbochan
  this demo has the same problem https://jshare.com.cn/caicai/KVI7uL
  I think maybe it's a visual difference
![QQ截图20191010113548](https://user-images.githubusercontent.com/6789138/66537183-2ad5a180-eb52-11e9-9707-28212054dbd4.png)

**Comment by sebastianbochan** [comment]
@wjhcc2018,
Let me know if this line should be disabled or not?

**Comment by pawelfus** [comment]
@wjhcc2018 

Please try:
```js
  plotOptions: {
    pie: {
      dataLabels: {
        enabled: true
      }
    }
  },
```

Or:
```js
  plotOptions: {
    pie: {
      dataLabels: {
        connectorWidth: 0
      }
    }
  },
```

**Comment by pawelfus** [comment]
Closing due too inactivity. If my answer above is not enough or doesn't work, let us know, we will reopen this ticket.
