### ISSUE TITLE
I am unable to render image inside series.tooltip

### ISSUE THREAD

**Issue by mterczynski** [highcharts/highcharts#12175]
#### Expected behaviour

I would like to be able to render images for tooltips that are bound to specific series

#### Actual behaviour

I am able to use image in tooltip that is shared for whole chart.

http://jsfiddle.net/u3sk92zw/1/

I am unable to use image in tooltip that is bound to specific series

http://jsfiddle.net/u3sk92zw/

#### Affected browser(s)

Chrome

**Comment by pawelfus** [comment]
Hi @mterczynski 

Thanks for reporting the issue. There's no [`series.tooltip.useHTML`](https://api.highcharts.com/highstock/plotOptions.series.tooltip) option, only [`tooltip.useHTML`](https://api.highcharts.com/highstock/tooltip.useHTML) - setting it in correct place resolves the issue: http://jsfiddle.net/BlackLabel/d6y8p039/
