### ISSUE TITLE
Custom dateTimeLabelFormat only shows time when using custom timezone

### ISSUE THREAD

**Issue by eldjuve** [highcharts/highcharts#12182]
#### Expected behaviour
Date formatter should use correct custom dateTimeFormat format when setting specific timezone or offset from UTC.

#### Actual behaviour
Date formatter only shows the "minute" formatting, even when showing historical data

#### Live demo with steps to reproduce
https://jsfiddle.net/yrja26ez/

- Only showing HH:MM in tooltip
- Showing full date and time when removing timezone

#### Product version
Highstock 7.2.0

#### Affected browser(s)
Tested in chrome

**Comment by pawelfus** [comment]
Hi @eldjuve 

Thanks for reporting this issue. Could share a screenshot how it rendered for you? This is mine:

![Screen Shot 2019-10-10 at 14 30 13](https://user-images.githubusercontent.com/1453926/66568875-9a578b00-eb6a-11e9-8a15-d05d9c28f77c.png)

If it's the same, then could you tell us what is the expected result? Thanks!

**Comment by eldjuve** [comment]
Hi @pawelfus 

If you remove the timezone you will see my expected result:
![image](https://user-images.githubusercontent.com/8972838/66646873-b66d3200-ec27-11e9-969b-603362300c17.png)

Basically I am expecting to see the formatting specified for 'day', but it seems like the formatter is based on the offsetted timestamp rather than the original UTC timestamp, and that it selects the 'hour' formatting in stead of the day formatting as the offsetted timestamp is 01.00 rather than 00.00. This is different to when using local timesamp (useUTC = false) as it then selects the formatting based on the UTC timestamp not the time zone corrected. So for me in Norway useUTC=false and timezone="Europe/Oslo" does not give the same result.

**Comment by pawelfus** [comment]
Ah, I see it now, thanks!

**Comment by TorsteinHonsi** [comment]
I am not sure it's a bug... In the [original demo](https://jsfiddle.net/yrja26ez/), it shows the `hour` format because the points are plotted at 02:00. In the configuration, the hour format is set to show only the hour and minutes, while the default configuration is to show the full date and the hours: https://jsfiddle.net/highcharts/no50pz6c/4/ . This is the intended behaviour.

**Comment by eldjuve** [comment]
Hi Torstein, not sure I got your conclusion. My intended use it to only show HH:MM in the tooltip on intraday stock data, and only date on historical stockdata. The historical stock data all have UTC timestamps at 00:00:00, that seems to be identified as dates by your "time format picker". This also works as expected when showing the time in "nonUTC", meaning it is still identifies the timstamp as dates even though the timestamps are 01:00:00 with UTC+1 here in Norway.

When I specify the timezone to make sure i.e. Oslo stocks are always displayed in Oslo timezone, it does however identify the UTC timestamp as beeing a time, rather than a date. Meening I no longer have the option to not show HH:MM (that looks even worse with 01.00) for historical prices with UTC timestamps at 00:00:00.

**Comment by TorsteinHonsi** [comment]
> it does however identify the UTC timestamp as beeing a time, rather than a date

Yes, Highcharts doesn't really distinguish between date and time (of day). It's all `datetime`. So when a datetime occurs at 01:00 AM, we assume that the time of day is of interest.

I think you need different strategies to deal with that. One option is to use a specific tooltip format for that series: http://jsfiddle.net/highcharts/38z94tos/. Another option would be to preprocess the UTC data into local time.
