### ISSUE TITLE
Gauge Plotarea 

### ISSUE THREAD

**Issue by RamakrishnanVBI** [highcharts/highcharts#12189]
#### Expected behaviour

1. Need Gauge Plot area to occupy the 100% of the container area.
2. Need Datalabel position near to the needle end point

#### Actual behaviour
1. Gauge Plot area to occupy same space between the container area.
2. Datalabel position placed bottom of the needle point.

#### Live demo with steps to reproduce
http://jsfiddle.net/o9ck57vg/1/

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @RamakrishnanVBI,
The github is our bug tracker, so for general [support](http://www.higcharts.com/support) questions please use forum / stackoverflow or email.
