### ISSUE TITLE
Tooltip is not shown on hover for large datasets using Firefox browser

### ISSUE THREAD

**Issue by mynameiswhat1** [highcharts/highcharts#12181]
#### Expected behaviour

Using Firefox 60.9.0esr (32-bit) browser I would expect the tooltip of a given data point to be displayed when I hover over a specific data point.

#### Actual behaviour

When I hover over a specific data point no tooltip is shown, also the crosshair is not visible.

#### Live demo with steps to reproduce
[https://jsfiddle.net/21mof9x4/](https://jsfiddle.net/21mof9x4/)

#### Product version
Highcharts/Highstock v 6.2.0 

#### Affected browser(s)
Firefox (at least 60.9.0esr (32-bit)), in chrome it works fine.

This seems to have something to do witth the witdth of the individual rect svg elements. If the witdth is increased using the developer tools the tooltip will be shown on hover. Can you please check this issue?

Thank you

**Comment by mynameiswhat1** [comment]
Is it possible it is something to do with this: [https://stackoverflow.com/questions/9208244/how-to-hover-over-an-svg-rect](https://stackoverflow.com/questions/9208244/how-to-hover-over-an-svg-rect) ?

**Comment by pawelfus** [comment]
Thanks for reporting this @mynameiswhat1 

It seems to be a bug in FF (tested with v69.0.2): https://jsfiddle.net/pfez3qaw/ - in Chrome events are fired correctly when crossing blue rects. Demo with more rectangles: https://jsfiddle.net/56azmgfb/

As you noticed, increasing width to 2px resolves the issue: https://jsfiddle.net/ztd5m8wp/

Reported: https://bugzilla.mozilla.org/show_bug.cgi?id=1587745

You are right, setting `pointer-events: all` workarounds the issue: https://jsfiddle.net/BlackLabel/r9ey7am4/2/

**Comment by mynameiswhat1** [comment]
Thank you for your help @pawelfus
