### ISSUE TITLE
Doc of sankey need update

### ISSUE THREAD

**Issue by nodew** [highcharts/highcharts#12194]
#### Expected behaviour
https://github.com/highcharts/highcharts/blob/0017f6c643/js/modules/sankey.src.js#L76

#### Actual behaviour
The nodeFormat and nodeFormatter are not listed in the latest document.
![image](https://user-images.githubusercontent.com/9988582/66643011-78383880-ec50-11e9-9be9-8c7cfa219c8d.png)

**Comment by sebastianbochan** [comment]
Hi @nodew,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by pawelfus** [comment]
Just in case:

All options are listed here: https://api.highcharts.com/class-reference/Highcharts.SeriesSankeyDataLabelsOptionsObject

URL can be found in "See also" part
![Screen Shot 2019-10-11 at 12 39 18](https://user-images.githubusercontent.com/1453926/66645595-2da0c700-ec24-11e9-9ff6-a94c32feb2b6.png)
