### ISSUE TITLE
Charts of type heat map not rendering in v7.2.0

### ISSUE THREAD

**Issue by AntonyMayer** [highcharts/highcharts#12191]
#### Expected behaviour
Chart of type heat map to render.

#### Actual behaviour
Since update 7.2.0 heat map charts keeps on throwing error:
```
Uncaught Error: Highcharts error #17
The requested series type does not exist
```

#### Live demo with steps to reproduce
Following demo is a copy of official demo.
The only difference is versions of `highcharts` and `highcharts-more` libs are set to 7.2.0
https://jsfiddle.net/tyoqcsm3/1/

#### Product version
v7.2.0

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @AntonyMayer,
The heatmap series requires to use `heamap.js` module instead of `highcharts-more.js`.

Demo:
- https://jsfiddle.net/BlackLabel/9mrxvqad/

For the further [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

**Comment by pawelfus** [comment]
Just to be on the same page:

Official demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/heatmap/

HTML in demo:
```html
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/heatmap.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>


<div id="container" style="height: 400px; min-width: 310px; max-width: 800px; margin: 0 auto"></div>
```
