### ISSUE TITLE
The chart does not work in React Native

### ISSUE THREAD

**Issue by zetorby** [highcharts/highcharts#12203]
Hi!
Hi, I tried to use the graph in RN and ran into the problem that the problem that the webView is no longer in the core.

**Comment by KacperMadej** [comment]
Hi @zetorby 

Thank you for contacting us. The information you have provided so far makes this issue a support case and should be resolved through other support channels: https://www.highcharts.com/blog/support/

What was the last version that was containing the webView?
By "the core" you mean React Native or Highcharts?

We have the official wrapper for React Native that is responsible for making Highcharts work in React Native: https://github.com/highcharts/highcharts-react-native

**Comment by zetorby** [comment]
Hi, Kacper
I use the native native ver 0.61.2 and wrapper for React Native and get the error that the webview cannot be imported from the native-native.
[Please use the react-native-community/react-native-webview fork of this component instead.](https://facebook.github.io/react-native/docs/webview)

**Comment by pawelfus** [comment]
Hi @zetorby 

Thanks! But it's wrong repo :) If you use our React Native wrapper, please post your issue on this repo: https://github.com/highcharts/highcharts-react-native Thanks!
