### ISSUE TITLE
Gradient does not work with Boost

### ISSUE THREAD

**Issue by ashwanigarg** [highcharts/highcharts#12202]
#### Expected behaviour
Linear Gradient should work with Boost Module

#### Actual behaviour
Chart is shown blank(empty) but hovering it shows only hidden data points

#### Live demo with steps to reproduce
 https://jsfiddle.net/vzk49h7q/ 

#### Product version
Highcharts 7.2.0, highcharts-angular 2.4.0

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @ashwanigarg,
The boost module is the extension which limits some functionalities (i.e markers, gradients) to increase performance.

@cvasseng should we consider it as a bug?
