### ISSUE TITLE
stock tools GUI menu - mobile issue

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#12216]
#### Expected behaviour

Stock tools GUI menu should work on mobile devices same as on the desktop version. 

#### Actual behaviour

After choosing some options (like type change i.e.) chart doesn't trigger wanted functionality. 

#### Live demo with steps to reproduce

(mobile)
1. Click on the "Type change" options, 
2. Choose another type than the actual is,
3. Nothing happened,
4. Click on the "Type change" button,
5. Chart change the series type,

Comparing to the desktop version - step 3 and 4 shouldn't exist. 
[Official demo](https://jsfiddle.net/BlackLabel/5gchqsbf/show)

#### Affected browser(s)
Tested on Safari iOS

**Comment by ani979** [comment]
Hi, any idea when this is going to be fixed? Thanks.

**Comment by pawelfus** [comment]
Hi @ani979 

Sorry for the late reply! No ETA at this moment, I will check this next week

**Comment by ani979** [comment]
Thank you. Does it get reflected in the released versions immediately after you commit to master?

**Comment by pawelfus** [comment]
Fix will be included in all upcoming releases. v7.2.1 and older versions won't have this fix.
