### ISSUE TITLE
Element.attr() with x behaves incorrectly in IE < 9

### ISSUE THREAD

**Issue by Akkuma** [highcharts/highcharts#1221]
In IE < 9 the position of custom rendered circle elements will not correctly render as expected in comparison to other browsers.

For instance, this is the code that has to be written to compensate for IE:

``` javascript
var $body = $(document.body),
    isIE7or8 = $body.hasClass('ie7') || $body.hasClass('ie8'),
    adjust = isIE7or8 ? 6 : 0,
    ieRedrawFix = isIE7or8 ? -1 * bigRadius: 0,
    smallRedrawRadius = isIE7or8 ? smallRadius/2 : smallRadius;

/* Need to fix for IE */
function redraw() {
    var bigX = $bigNumbers.width()/2;

    big.attr({x: bigX + adjust + ieRedrawFix});
    bigOutline.attr({x: bigX  + ieRedrawFix});

    if (showPotentialSavings) {
        small.attr({x: bigX - smallRedrawRadius + adjust + ieRedrawFix});
        smallOutline.attr({x: bigX - smallRedrawRadius + ieRedrawFix });
    }
}
```

In IE the rendered circles I draw have to be shifted by the radius of my `big` circle (everything is based off that), adjust my `small` circles' xs differently, and shift the center circle (`big` and `small`) to allow it to be properly outlined.

**Comment by cvasseng** [comment]
Hi! We're doing a bit of spring cleaning, and closing old issues. If you're still experiencing issues with this, please feel free to open a new issue! Thanks!
