### ISSUE TITLE
Show VWAP on OHLC

### ISSUE THREAD

**Issue by otsybulsky** [highcharts/highcharts#12215]
#### Expected behaviour
I would like to place a vwap on the price chart using this interface like SMA
![Screen Shot 2019-10-15 at 3 51 18 PM](https://user-images.githubusercontent.com/34866613/66834811-079e5e00-ef67-11e9-947d-998823891e35.png)

#### Actual behaviour
vwap is displayed separately
![Screen Shot 2019-10-15 at 3 51 34 PM](https://user-images.githubusercontent.com/34866613/66834857-200e7880-ef67-11e9-9eba-84c576897916.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui

**Comment by pawelfus** [comment]
Thanks @otsybulsky for reporting this issue. You are right, `VWAP` should be placed on the same pane as main series.

**Comment by otsybulsky** [comment]
@TorsteinHonsi Hi! I can see that the changes  vwap have been made. When i can expect a release, my users are very waiting for this hotfix.

**Comment by pawelfus** [comment]
Hi @otsybulsky  - this will be part of the next release, but the release date is not specified. Feel free to modify source code of `stock-tools.src.js` file (as you can see it's a simple change: d2488d3a9c880df526d2ade691faca596b8230af ) until new version will be released.
