### ISSUE TITLE
Highcharts.SVGRenderer.prototype.symbols.triangle receives different options

### ISSUE THREAD

**Issue by liepa** [highcharts/highcharts#12219]
We are overriding triangle rendering so that the triangle is pointing in the same direction (not rotated based on a horizontal or a vertical chart).

#### Expected behaviour
When calling Highcharts.SVGRenderer.prototype.symbols.triangle on chart rendering and on hover should pass the same options.

#### Actual behaviour
When rendering chart Highcharts.SVGRenderer.prototype.symbols.triangle receives only Hash with options.
When hovering specific triangle symbol Highcharts.SVGRenderer.prototype.symbols.triangle receives c.SVGElement 

#### Live demo with steps to reproduce
Output of the options passed to Highcharts.SVGRenderer.prototype.symbols.triangle is visible in the developer console.
https://jsfiddle.net/4yjmr8se/

#### Product version
Highcharts 7.1.2, also the same for Highcharts 7.2

#### Affected browser(s)
Firefox developer edition 70.0b12 (64-bit)
Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Thanks for reporting the issue @liepa 

Note that both hash an SVGElement contain the same config options (x, y, r, width, height etc).

*Internal note:*
This inconsistency comes from these lines:
https://github.com/highcharts/highcharts/blob/ca5ba96d8fdae4008e50c6336224f4402705dba8/ts/parts/SvgRenderer.ts#L1620-L1628

**Comment by liepa** [comment]
Thanks for looking into this issue.

I have related question regarding symbol rotation - why do symbols rotate in the first place? 
Here is a good example (http://jsfiddle.net/x54dkjrt/), if I use images as the custom symbol and render an inverted chart, why do symbols rotate 90 degrees? 

Shouldn't marker symbol stay the same as for legend?

Thanks

**Comment by pawelfus** [comment]
Yes, they should. This is bug, reported in #422

**Comment by pawelfus** [comment]
**Workaround:**

Demo: http://jsfiddle.net/BlackLabel/uyvgcmw0/

Plugin: 
```js
  (function(H) {
    H.addEvent(
      H.Chart,
      'render',
      function() {
        var chart = this;

        if (!chart.inverted) {
          return;
        }

        chart.series.forEach(function(series) {
          series.points.forEach(function(point) {
            var transform = point.graphic.attr('transform'),
              rotate = ' rotate(90, ' +
              (point.plotX + point.graphic.imgwidth / 2) + ', ' +
              (point.plotY + point.graphic.imgheight / 2) + ')';

            if (point.graphic.rotateTransform) {
              point.graphic.attr({
                transform: transform.replace(point.graphic.rotateTransform, rotate)
              })
            } else {
              point.graphic.attr({
                transform: transform + rotate
              });
            }

            point.graphic.rotateTransform = rotate;
          });
        });
      }
    );
  })(Highcharts);
```

Plugin should be safe to use: rotation update is called on each chart redraw (e.g. window resize, zooming, updating data etc.)

**Comment by liepa** [comment]
Workaround plugin works.

Will remove it when [#422](https://github.com/highcharts/highcharts/issues/422) is fixed.

Thanks!
