### ISSUE TITLE
Issue while downloading CSV and Excel files in HighCharts

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [highcharts/highcharts#12221]
#### Expected behaviour
The export to CSV/Excel should download proper datetime values

#### Actual behaviour
It is not exporting proper date and time values

#### Live demo with steps to reproduce

https://jsfiddle.net/nykwzx2b/
#### Product version

Latest version of the products
#### Affected browser(s)
Effects all browsers.

**Comment by pawelfus** [comment]
Hi @aditya-padhi-kbl 

Thanks for reporting the issue. Your chart is misconfigured, please do one of the following:

A) Remove `type: "datetime"` if you want to use categories: https://jsfiddle.net/BlackLabel/74bnma8w/

B) Remove `categories: [ ... ]` and set x-values in dataset: https://jsfiddle.net/BlackLabel/brn7tz8f/

**Comment by aditya-padhi-kbl** [comment]
Hi @pawelfus ,

[demo-of-reusing-but-modi.csv.zip](https://github.com/highcharts/highcharts/files/3733406/demo-of-reusing-but-modi.csv.zip)

Thank-you for your sharing the details.  I tried earlier with option A.
With point A, the date-time values are exported as Epoch (whatever is in the categories).  The end user will again have to format it in Excel.  In our application we wanted to prevent end user from doing this additional [step.](url)

**Comment by pawelfus** [comment]
You can use already defined strings in categories instead of timestamps, take a look: https://jsfiddle.net/BlackLabel/spfg8w4y/

**Comment by aditya-padhi-kbl** [comment]
Hi @pawelfus 
Thank-you very much.  Appreciate your quick response.  This fiddle suits the use case.
