### ISSUE TITLE
Make SVG Title/Subtitle selectable with mouse

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [highcharts/highcharts#12232]
#### Expected behaviour
User should be able to select the title/subtitle using mouse 

#### Actual behaviour
User is not able to select title/subtitle using mouse

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/spfg8w4y/

#### Product version
I am using the latest versions of HighCharts

#### Affected browser(s)
All browsers

**Comment by sebastianbochan** [comment]
Hi @aditya-padhi-kbl,
Thank you for reporting. The bug is known bug and has been already reported in our github repo here: https://github.com/highcharts/highcharts/issues/11294

Im closing this ticket as duplicate.
