### ISSUE TITLE
Highmaps: Uncaught ReferenceError: Highcharts is not defined

### ISSUE THREAD

**Issue by afenrir** [highcharts/highcharts#12231]
I'm getting a reference error in Highmaps:

```
 Uncaught ReferenceError: Highcharts is not defined at H.ColorAxis.getSeriesExtremes
```

The error is arising from this line:

https://github.com/highcharts/highcharts/blob/a188b87b3d2b4f386672ee48e547110e8e61b2a2/js/parts-map/ColorAxis.js#L814

My current workaround is to place Highcharts on the window object. I am using Highmaps inside a React wrapper.

**Comment by sebastianbochan** [comment]
Hi @afenrir,
Thank you for reporting. Let me know if you use our [official react wrapper](https://github.com/highcharts/highcharts-react). Could you use any sandbox for prepare a live demo?

**Comment by pawelfus** [comment]
*Internal note:*
Bisected to: 7689db4793dc1208a951b12a05d7a7c4719b6d46 @ppotaczek - please use `H.Series` or `Series`, instead of `Highcharts.Series`.

**Comment by afenrir** [comment]
Hi Sebastian,

Yes, I am using the official wrapper. I am happy to provide a sandbox demo. However, I would say that the problem here is quite apparent: you're referencing a variable that has not been defined. Are you sure a demo is necessary?  Do you have a template I can use?

**Comment by pawelfus** [comment]
I think no need for the demo this time, issue is already tagged as a bug.

Regarding:
> Do you have a template I can use?

When you open a new issue you have our bug report template (and live demo template in jsFiddle) - please follow the template with descriptions, that really helps us! Thanks

**Comment by pawelfus** [comment]
No problem, thanks for understanding :)

**Comment by RagulSithuraj** [comment]
Hi ,
I am facing the same issue Do we have any solution for this bug or it is already patched up?

**Comment by afenrir** [comment]
@RagulSithuraj My current workaround is to place Highcharts on the window object:

```javascript
import Highcharts from 'highcharts/highcharts';

window.Highcharts = Highcharts;
```
