### ISSUE TITLE
Axis labels and Data labels are overlapping with the tooltip text.

### ISSUE THREAD

**Issue by mgopidi** [highcharts/highcharts#12236]
#### Expected behaviour

X-Axis Labels and Data labels are not expected to be overlapped with the tool tip text even though the Z-index is highest and opacity is 1 for the tooltip box. 

#### Actual behaviour
Currently, Labels are shown above the tool tip text as shown below:
![image](https://user-images.githubusercontent.com/52533578/67000103-d18ee480-f0f4-11e9-9b67-0709c0a9474b.png)

NOTE:  As we are dealing with other font customization, "useHTML: true" is added for both data labels and also X-axis labels. If we remove this property, labels are no longer overlapping and issue is resolved but other font customizations related to labels(ex: **B**, _I_,) doesn't work. 

#### Affected browser(s)
IE, Chrome

**Comment by pawelfus** [comment]
Hi @mgopidi 

This is expected result when some elements are rendered in SVG (e.g. tooltip's background) and others in HTML (dataLabel). See docs: https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting

**Comment by mgopidi** [comment]
Thank you @pawelfus for the immediate response on this.

**Comment by omnibrain** [comment]
But it also happens when I use both HTML tooltips and HTML labels, see this example: https://jsfiddle.net/u2zxewvm/7/

**Comment by pawelfus** [comment]
@omnibrain try setting `tooltip.outside` as described in the docs I referred above: https://jsfiddle.net/BlackLabel/zrqs6ygx/

> It will always be laid out on top of all other SVG content. Specifically the tooltip may be rendered below the useHTML label. Since Highcharts v6.1.1 this can be avoided by setting tooltip.outside to true.

Just to explain why it happens: setting `useHTML` in tooltip does not change how the background is rendered, it's still in SVG. It renders tooltip text as HTML.
