### ISSUE TITLE
waterfall with overlap stacking misaligned after reflow

### ISSUE THREAD

**Issue by cjyetman** [highcharts/highcharts#12248]
I'm trying to make a waterfall chart using `stacking: "overlap"` with multiple stacks. If the container has explicitly set width and height, the chart draws as expected, but as soon as anything causes a `reflow`, the first stack is misaligned. Further reflows compound the misalignment. A reflow can be triggered by changing the width or height of the container and then explicitly running `reflow()` on the chart, as in the example below, however, a reflow can/will be caused by other events as well, for instance...
- if you click on one of the series in the legend to hide it and then click again to reshow it
- if the container's height and/or width is not explicitly set, the browser causes and immediate reflow on load, so that the chart will never plot correctly
- etc.

#### Expected behaviour
after reflow, chart should look the same (relatively speaking, if the container size has changed)

#### Actual behaviour
after reflow, chart looks different

#### Live demo with steps to reproduce
https://jsfiddle.net/Loqpta41/

#### Product version
Highcharts JS v7.2.0 (2019-09-03)
https://code.highcharts.com/highcharts.js
https://code.highcharts.com/highcharts-more.js

#### Affected browser(s)
on macOS 10.15
Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)
Safari Version 13.0.2 (15608.2.30.1.1)
Firefox Quantum 69.0.3 (64-bit)

**Comment by PaulDalek** [comment]
Thanks for reporting the issue. In a nutshell, the arrays that should contain a correct min (stackedYNeg array) and max (stackedYPos array) values for each single stack hold incorrect values, therefore the visible y range is disturbed after each redraw. We're working on a fix for this right now, and it should be available in a next few days.

_Internal issue:_
This behaviour is a regression casued by this commit: https://github.com/highcharts/highcharts/commit/6c31b76389b56becc76e2823ef58686c9f80897f.

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/6dkx2w73/

Plugin:
```js
(function(H) {
  H.addEvent(
    H.Chart,
    'beforeRedraw',
    function() {
      this.yAxis.forEach(function(axis) {
        axis.waterfallStacks = {
          changed: true
        };
      });
    }
  );
})(Highcharts);
```
