### ISSUE TITLE
Typescript type for "Point" does not contain "index" property

### ISSUE THREAD

**Issue by ryanhaney** [highcharts/highcharts#12250]
Given a populated "TooltipFormatterContextObject" called "context", typescript complains when accessing `context.point.index` property.

To access the property while using typescript, you must cast `context.point` to `any`.

`const index = (context.point as any).index`

Can we get the type definitions updated please?

#### Live demo with steps to reproduce
N/A

#### Product version
Highcharts 7.2.0

#### Affected browser(s)
Tested using Chrome

**Comment by sebastianbochan** [comment]
Hi @ryanhaney,
Thank you for reporting about the probelm.

FYI @bre1470

**Comment by bre1470** [comment]
@TorsteinHonsi Can we make the `Highcharts.Point.index` public?

**Comment by TorsteinHonsi** [comment]
Yes, shouldn't be a problem

**Comment by ryanhaney** [comment]
Thanks so much for completing this! What version will this be applied to in NPM?

**Comment by bre1470** [comment]
The change will become part of the next major version of Highcharts.

**Comment by ryanhaney** [comment]
Major as in `8.x.x`? Are there significant breaking changes? Is there an estimated release date? I am currently using `7.2.0` as mentioned in the PR. I suppose it's not a _huge_ deal as there is a workaround, but it would've been nice to get a patch applied to `7.2`.

**Comment by pawelfus** [comment]
Hi @ryanhaney 

> Major as in 8.x.x?

Yes, major as v8.

> Are there significant breaking changes?
All breaking changes (if any) should be posted under "Upgrade notes" in our changelog: https://www.highcharts.com/blog/changelog/

> Is there an estimated release date?

Q4 2019
