### ISSUE TITLE
Chart update with the option enableMouseTracking doesn't work as intended when passing state true to false

### ISSUE THREAD

**Issue by ArnaudGeorges** [highcharts/highcharts#12258]
Hi,
Small example here, a chart with a single serie with enableMouseTracking set to false and two buttons, one to activate the enableMouseTracking and the other to desactivate it with the method Chart.update().
You can see it at : https://jsfiddle.net/6zwdeguo/5/
The activation (false to true) is working perfectly but when you try to desactivate (true to false), the chart is still reacting to the user's mouse.
Am i missing something here or is it a bug ?

Best regards, 
Arnaud

**Comment by sebastianbochan** [comment]
Hi @ArnaudGeorges,
Thank you for reporting about the problem.

**Simplified demo:**
- https://jsfiddle.net/BlackLabel/bewt6gLx/

**Workaround**
Remove listeners on each point of series.

Demo:
- https://jsfiddle.net/BlackLabel/x0q63ca2/

**Comment by ArnaudGeorges** [comment]
Thank you for your solution, it fits my needs for the moment. 
Best regards,
Arnaud
