### ISSUE TITLE
Wrong positioning of date-time points? 

### ISSUE THREAD

**Issue by personalGitRep** [highcharts/highcharts#12256]
As can be seen in the picture and the demo link below, the 24 of October is not correctly positioned on the xAxis. I assume I'm missing something? Why this happened?

#### Actual behaviour

![Untitled](https://user-images.githubusercontent.com/38632477/67235422-edc3b600-f453-11e9-9059-b95a96a6e943.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/c28Lweg7

**Comment by pawelfus** [comment]
Hi @personalGitRep 

Let me explain: xAxis renders ticks at 00:00:00.000, while your demo is using `Date.now()` which returns for example 14:12:45.123 which is rendered exactly at position defined in time.

If you have more questions, please contact our support: https://www.highcharts.com/blog/support/ - thanks!
