### ISSUE TITLE
Waterfall chart error when invisble and first value below 0

### ISSUE THREAD

**Issue by Yuruh** [highcharts/highcharts#12267]
#### Expected behaviour
Create a waterfall serie that is invisible by default.

#### Actual behaviour
Highcharts-more crashes in the method `getCrispPath`.

#### Live demo with steps to reproduce
When specifying `visible: false` and a value below 0 in the series configuration it crashes: https://jsfiddle.net/2q3Loz5h/
Otherwise it renders correctly and can be set visible or invisible: https://jsfiddle.net/2q3Loz5h/1/

#### Product version
Last versions of Higcharts and Highcharts-more

#### Affected browser(s)
Reproduced on Chrome and Firefox

**Comment by sebastianbochan** [comment]
Hi @Yuruh,
Thank you for reporting about the problem.

FYI @PaulDalek
