### ISSUE TITLE
Stock tools GUI doesn't work on the second axis

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#12268]
#### Expected behaviour

Stock tools GUI should work for both axes. 

#### Actual behaviour

It is impossible to add any stock tools on the second axis. 

#### Live demo with steps to reproduce

[Official GUI demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui/)

#### Product version
Highcharts JS v7.2.0 (2019-09-03)

**Comment by raf18seb** [comment]
Hi, thanks for reporting.

There is an **addClipPaths()** method that adds clipPath on annotations that are outside of axes.
You can simply disable this functionality:
```Highcharts.Annotation.prototype.addClipPaths = function() {};```

Demo: https://jsfiddle.net/BlackLabel/hydLu05f

**Comment by mubeenellahi1** [comment]
@raf18seb Thank you for your suggestion it was super helpful.

But this partially solves the issue. What I am able to do is:
Create a flag annotation on the first axis and them move it around to all the axis.
The functionality required is that I want to create separate annotations for separate y axis. For now clicking on the second y axis does not create an annotation.

**Comment by raf18seb** [comment]
Hi @mubeenellahi1 

Unfortunately, the yAxis is hardcoded and, for this moment, adding annotations to other axes is impossible.
As @Basts reported above, it's an enhancement and maybe will be added to Highcharts in the future.
I strongly advise reporting this on our UserVoice channel here: https://highcharts.uservoice.com - it might speed up the development process if other users want this feature too.

For now, you can add annotations only to the first axis and, if you want to move them over the second axis, disable clipPaths as suggested above.

**Comment by raghavakrishnab** [comment]
Hi 
i m  getting error  **addClipPaths doesn't exist on type 'Annotation'**  when i tried to disable clippaths as per your suggestion.
Highcharts.Annotation.prototype.addClipPaths = function() {};

Please assist.

**Comment by raf18seb** [comment]
I am not seeing any error in the above [demo](https://jsfiddle.net/BlackLabel/hydLu05f) (latest Chrome, Windows 10). Can you provide more info/steps so I can reproduce your issue?

**Comment by raghavakrishnab** [comment]
Hi,
In the same [demo](https://jsfiddle.net/BlackLabel/hydLu05f) (latest Chrome, Windows 10).

1)  I'm trying to draw a line vertically from first axis to untill end of axis. but it is not working  similar to circle and rectangle.

2) Highcharts.Annotation.prototype.addClipPaths = function() {}; This is not working when i load highcharts  using  TypeScript + UMD (https://api.highcharts.com/class-reference/#toc4). I will create a example project after some time. Below is the sample code.

import * as Highcharts from 'highcharts/highstock';
import IndicatorsAll from 'highcharts/indicators/indicators-all';
import AnnotationsAdvanced from 'highcharts/modules/annotations-advanced';
import StockTools from 'highcharts/modules/stock-tools';

IndicatorsAll(Highcharts);
AnnotationsAdvanced(Highcharts);
 StockTools(Highcharts);

declare var require: any;
const Boost = require('highcharts/modules/boost');
const noData = require('highcharts/modules/no-data-to-display');
const More = require('highcharts/highcharts-more');
const Stocks = require('highcharts/highstock');

Boost(Highcharts);
noData(Highcharts);
More(Highcharts);
noData(Highcharts);

in Angular - ngOnit(){
Highcharts.Annotation.prototype.addClipPaths = function() {};
Stocks.stockChart(this.chartsOptions);
} 

3) In the same demo as a user i want to draw a line, circle , rectangle and add text beyond second axis.

Please advice

**Comment by raf18seb** [comment]
Hi, thanks for clarifying that you mean lines instead of circles, rectangles, etc.
Lines are different types of annotations, so you need to disable clipping function on crookedLines:
```Highcharts.Annotation.types.crookedLine.prototype.setClipAxes = function() {};```
Simplified demo: https://jsfiddle.net/BlackLabel/51qgmnrx

In case of any further questions, please use our support channels: https://www.highcharts.com/blog/support
GitHub is our bug/enhancement tracker.

**Comment by raghavakrishnab** [comment]
Hi, Thanks for solution .. It worked :-).

**Comment by raghavakrishnab** [comment]
Hi,  
Stock tool  "Text" annotations is limited to few characters.  Currently i cannot more text ( more than 50 characters using stool tool annotations).  When i select  text annotation and click anywhere on charts i want show input filed and save button.  Please suggest .

**Comment by raf18seb** [comment]
As I said in the previous comment, for any further support please use our support channels. We use GitHub to track **bugs only**.

**Comment by raghavakrishnab** [comment]
Thanks.

**Comment by raghavakrishnab** [comment]
Hi 
Rectangle annotation  left border doesnt show up while adding annotations
https://jsfiddle.net/raghava_2121/891g0mpe/1/
![image](https://user-images.githubusercontent.com/61841873/77421007-fafa1d80-6dc2-11ea-8f68-98cce1730d77.png)

**Comment by pawelfus** [comment]
Thanks for reporting this @raghavakrishnab - it looks like a separate issue, could you create one? Thanks! Workaround for you: https://jsfiddle.net/BlackLabel/qmysr2hx/

**Comment by raghavakrishnab** [comment]
sure  I will create one . Workaround is working fine. Thanks

Is there a way to disable zooming while adding annotation and re-enable zooming onec annotation is added

**Comment by pawelfus** [comment]
> Is there a way to disable zooming while adding annotation and re-enable zooming onec annotation is added

Use support channel please :) This is ticket about Stock tools GUI and secondary axis.
