### ISSUE TITLE
Sunburst with levelSize weight 1 is not always using 100% of plot area

### ISSUE THREAD

**Issue by MOberlaender** [highcharts/highcharts#12262]
#### Expected behaviour
The sunburst charts should always use the same size.

#### Actual behaviour
If the sunburst chart is not balanced - all leafes on same level - a drilldown / up action will change the sunburst chart size based on the numbers of levels. 

#### Live demo with steps to reproduce
https://jsfiddle.net/1tsqh0Lc/
![sunburst_scaling](https://user-images.githubusercontent.com/38975694/67388471-012c6980-f599-11e9-89bf-ba0c8338aaf7.gif)

#### Product version
Highcharts JS v7.2.0

#### Affected browser(s)
Firefox 69.0.3
Safari 13.0.2

**Comment by jon-a-nygaard** [comment]
Hi @MOberlaender, you are able achieve this by using the option [`series.sunburst.levelSize`](https://api.highcharts.com/highcharts/series.sunburst.levelSize).
Setting the size to a static percentage value based on the number of levels, will make the points have the same size when navigating through the levels. Please see the following example: https://jsfiddle.net/jon_a_nygaard/bg7Lznvq/

**Comment by MOberlaender** [comment]
Hi,
@jon-a-nygaard is it possible that all visible levels (after drilldown) will always use 100% heighth and width?

**Comment by jon-a-nygaard** [comment]
> chart with all visible levels (after drilldown) will always use 100% height and width

@MOberlaender If I understand you correctly, then for instance when clicking on the point named `"81553171"` you would like the two visible levels to fill the chart 100% instead of 66%?

This behavior seems to be a bug, so we will have this fixed in an upcoming maintenance version.

## Workaround
One possible workaround for this is to apply the following patch to the `modules/sunburst.src.js`:
```diff
diff --git a/js/modules/sunburst.src.js b/js/modules/sunburst.src.js
index 18e057368..428946b6d 100644
--- a/js/modules/sunburst.src.js
+++ b/js/modules/sunburst.src.js
@@ -310,6 +310,13 @@ var getDrillId = function getDrillId(point, idRoot, mapIdToNode) {
     }
     return drillId;
 };
+var getLevelFromAndTo = function getLevelFromAndTo(_a) {
+    var level = _a.level, height = _a.height;
+    // Never displays levels below 1
+    var from = level > 0 ? level : 1;
+    var to = level + height;
+    return { from: from, to: to };
+};
 var cbSetTreeValuesBefore = function before(node, options) {
     var mapIdToNode = options.mapIdToNode, nodeParent = mapIdToNode[node.parent], series = options.series, chart = series.chart, points = series.points, point = points[node.i], colors = (series.options.colors || chart && chart.options.colors), colorInfo = getColor(node, {
         colors: colors,
@@ -712,10 +719,11 @@ var sunburstSeries = {
         });
         // NOTE consider doing calculateLevelSizes in a callback to
         // getLevelOptions
+        var _a = getLevelFromAndTo(nodeRoot), from = _a.from, to = _a.to;
         mapOptionsToLevel = calculateLevelSizes(mapOptionsToLevel, {
             diffRadius: diffRadius,
-            from: nodeRoot.level > 0 ? nodeRoot.level : 1,
-            to: tree.height
+            from: from,
+            to: to
         });
         // TODO Try to combine setTreeValues & setColorRecursive to avoid
         //  unnecessary looping.
```

## Todo
- Apply the patch below to `ts/modules/sunburst.src.js`
- Add unit tests for `getLevelFromAndTo`
- Check if `from` and `to` can be reused as parameters in `getLevelOptions`
```diff
diff --git a/ts/modules/sunburst.src.ts b/ts/modules/sunburst.src.ts
index 93e4112fd..8e09cb87d 100644
--- a/ts/modules/sunburst.src.ts
+++ b/ts/modules/sunburst.src.ts
@@ -597,6 +597,15 @@ var getDrillId = function getDrillId(
     return drillId;
 };
 
+const getLevelFromAndTo = function getLevelFromAndTo(
+    { level, height }: Highcharts.SunburstNodeObject
+): { from: number, to: number } {
+    // Never displays levels below 1
+    const from = level > 0 ? level : 1;
+    const to = level + height;
+    return { from, to }
+};
+
 var cbSetTreeValuesBefore = function before(
     node: Highcharts.SunburstNodeObject,
     options: Highcharts.SunburstNodeValuesObject
@@ -1133,10 +1142,11 @@ var sunburstSeries = {
         }) as any;
         // NOTE consider doing calculateLevelSizes in a callback to
         // getLevelOptions
+        const { from, to } = getLevelFromAndTo(nodeRoot);
         mapOptionsToLevel = calculateLevelSizes(mapOptionsToLevel, {
-            diffRadius: diffRadius,
-            from: nodeRoot.level > 0 ? nodeRoot.level : 1,
-            to: tree.height
+            diffRadius,
+            from,
+            to
         }) as any;
         // TODO Try to combine setTreeValues & setColorRecursive to avoid
         //  unnecessary looping.
```
