### ISSUE TITLE
The axis will block the line graph

### ISSUE THREAD

**Issue by 52flutter** [highcharts/highcharts#12272]
#### Expected behaviour
When xAxis minPadding is set to 0, set the plotBorderWidth to be the line should be on it.

#### Actual behaviour
When xAxis minPadding is set to 0, set the plotBorderWidth to block the line.

#### Live demo with steps to reproduce

This is demo:https://jshare.com.cn/temp/OrVoGu/1
#### Product version

7.2.0
#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting the issue @YinRenjie1993 

Demo in jsFiddle: https://jsfiddle.net/BlackLabel/pkqvr0La/
