### ISSUE TITLE
【highcharts-vue】can't import funnel3d & cylinder

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#12278]
#### Actual behaviour
I can't import the funnel3d & cylinder,
`import highchartsFunnel3d from 'highcharts/modules/funnel3d'`
![QQ截图20191026162308](https://user-images.githubusercontent.com/6789138/67646640-1246f300-f96a-11e9-9db1-64f6c3fcd3f7.png)

#### Product version

"highcharts": "7.1.2",
"highcharts-grouped-categories": "^1.1.3",
"highcharts-regression": "^2.0.1",
"highcharts-vue": "^1.3.5",
#### Affected browser(s)
Google Chrome 77.0.3865.90（正式版本） （64 位）

**Comment by pawelfus** [comment]
Hi @wjhcc2018 

Did you follow instructions to load funnel-3d? See: https://www.highcharts.com/docs/chart-and-series-types/funnel-3d

So other modules should be loaded (`highcharts-3d.js` and `cylinder.js`) first and then `funnel3d.js`.

**Comment by pawelfus** [comment]
Closing, please follow this ticket: https://github.com/highcharts/highcharts-vue/issues/114#issuecomment-549124243
