### ISSUE TITLE
Iframe element remains in the DOM tree after exporting chart with style mode

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#12273]
#### Expected behaviour
The temporary `<iframe>` element should also be removed altogether with the `dummySVG`.

#### Actual behaviour
After exporting the chart, we can notice that the unnecessary `<iframe>` element remains in the DOM tree after every initiation of exporting process.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/eaudj73o/
Click on `getSVG` button few times, and take a look on the `document.body` structure.

_Internal Note:_
_Probably there is only need to remove the mentioned element within `tearDown` function:_
https://github.com/highcharts/highcharts/blob/4605ae2c31481deb6dda80de461572ca9f13ebbd/js/modules/exporting.src.js#L1775-L1777

**Comment by alvarezguille** [comment]
Any suggested workaround for this issue?

**Comment by Denyllon** [comment]
Hi @alvarezguille ,

Sure thing. Here is the example with workaround applied: http://jsfiddle.net/BlackLabel/y65me4o8/

Kind regards!
