### ISSUE TITLE
Axis.minRange is not working for logarithmic axes

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#1227]
This would be expected to work the same as tickInterval, where the unit is the logarithm. So a minRange of 1 means that the user is allowed to zoom to 10-100 or 100-1000 etc.

http://jsfiddle.net/highcharts/P6PfY/5/

**Comment by highslide-software** [comment]
Here's a case where it fails with JS errors, which is more serious: http://jsfiddle.net/highcharts/rt1zjzdw/6/

**Comment by sebastianbochan** [comment]
+1 

Extra demo:
 - http://jsfiddle.net/og44fuq2/
