### ISSUE TITLE
Treemap - tree depth 4 'back' traverse error

### ISSUE THREAD

**Issue by mialso** [highcharts/highcharts#12286]
#### Expected behaviour
nodes tree is traversed 'back' properly

#### Actual behaviour
nodes tree is traversed 'back' improperly in case tree depth is 4.
The error appears on 2nd level and is resulted in 3rd level rendered within 2nd level with improper click handling

#### Live demo with steps to reproduce
steps:
go deep with path like  0_0 -> 1_0 -> 2_0 to end on 4th level, go back 2 levels up
[demo here](https://jsfiddle.net/mialso/8thw4e35)

#### Product version
Highcharts 7.2.0

#### Affected browser(s)
bug is reproduced on Linux OS (xUbuntu 18.04):
Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)
Firefox 70.0
others not tested

**Comment by pawelfus** [comment]
Thanks for reporting @mialso 

Simplified demo:
https://jsfiddle.net/BlackLabel/g940mb8u/

Visual steps: 
![treemap](https://user-images.githubusercontent.com/1453926/67758009-260f5980-fa3d-11e9-9c0a-8c39b47ed3e7.gif)
- there shouldn't be tooltip for `2_1` on `1_0`/`1_1` level

**Comment by TorsteinHonsi** [comment]
Turns out traversing the tree from a single root node is broken altogether since https://github.com/highcharts/highcharts/commit/6db37ec3ed33ff196bfc183e7d0c48e5f023e5fa.
