### ISSUE TITLE
Legendbox is misaligned on windows

### ISSUE THREAD

**Issue by JonasNiestroj** [highcharts/highcharts#12284]
#### Expected behaviour
The legendbox should look the same on windows and on the other operating systems.

#### Actual behaviour
The legendbox is misaligned on windows.
The values in the transform from the legend items are different.

#### Live demo with steps to reproduce
https://jsfiddle.net/claytonlloyd/snc5p03h/53/

If you open the demo on windows it looks like this:
![Capture](https://user-images.githubusercontent.com/7408528/67692457-74bae600-f9a0-11e9-9175-3d2fef470150.PNG)

If you open the demo on os x it looks like this:
![image](https://user-images.githubusercontent.com/7408528/67692547-9916c280-f9a0-11e9-91a4-cb76fd9ae976.png)

#### Product version

Highcharts 7.2.0
#### Affected browser(s)
It is on all browsers on windows the same.

**Comment by pawelfus** [comment]
Hi @JonasNiestroj 

Thanks for reporting the issue. Instead of trying to position legend items manually, did you consider using `layout: "proximate"` option? Take a look: https://jsfiddle.net/BlackLabel/u50wdbzj/1/

@KacperMadej - could you confirm?

**Comment by JonasNiestroj** [comment]
Hi @pawelfus 

Thank you for you reply. This one looks better but there is one thing. If i click on the item in the legendbox it is moved to the bottom. Do you know why this happens?

**Comment by pawelfus** [comment]
Not really, proximate renders as close to the last point as possible. In case of no data (or hidden series) legend item is rendered at the origin of the yAxis. Hide every series in this  [demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/legend/layout-proximate). In this case `proximate` won't work for you.

**Comment by JonasNiestroj** [comment]
I have some cases with no data. How can i handle the item position without `proximate`?

**Comment by pawelfus** [comment]
We are working on a module to define multiple legends on a chart and organize them the way you like it (e.g. every series can be in a different legend, positioned separately) - I think this is exactly  what you need, but this will come no sooner than in v8.x.

Of course, the issue you reported should be fixed, once confirmed by @KacperMadej

**Comment by KacperMadej** [comment]
This looks like a matter of font - it has a slightly different size on Windows. There's not much we could do about this since the problem is caused by operating system differences in font rendering. You could try changing the font to a different type that will be consistent across different operating systems.

Another way to resolve the problem is to detect OS and set your options for not-Windows and the options from below demo (font size set to `11px`) for Windows.
Demo: https://jsfiddle.net/BlackLabel/01ufLp97/

**Comment by JonasNiestroj** [comment]
@pawelfus @KacperMadej 
Thank you very much for your help. 
I will try it with a different font or with the os detect solution.
