### ISSUE TITLE
Unable to update `plotBackgroundImage`

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#12296]
#### Actual behaviour

If `plotBackgroundImage` property was defined, it is not possible to update it.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/o3g8ewz1/

#### Product version
Highcharts v7.2

#### Affected browser(s)
All

Original issue: https://github.com/highcharts/highcharts-react/issues/170

**Comment by ckirk** [comment]
Hey I was having the same problem. As this solution is not incorporated into a stable release yet, I was able to incorporate it into my codebase by replacing the contents of my 'highcharts' folder in my node_modules directory with the contents of https://github.com/highcharts/highcharts-dist/tree/nightly. 

Is there any way to install these nightly builds from npm or does it have to be done manually? Thanks!

**Comment by pawelfus** [comment]
Hi @ckirk 

For now you need to install those manually, we will check if we can easily ship this to npm.
