### ISSUE TITLE
StackLabels outside xAxis min & max range are displayed

### ISSUE THREAD

**Issue by aroue2** [highcharts/highcharts#12294]
Having a stacked column graph with two series of 10 columns each, but displaying only columns with xAxis >= 2 and xAxis <= 8

#### Expected behaviour
StackLabels of not showed columns are not showed

#### Actual behaviour
StackLabels of not showed columns are showed

#### Live demo with steps to reproduce
https://jsfiddle.net/so7jnzwg/ : A chart with stackLabels and dataLabels. We can see that dataLabels of not showed columns are not displayed while stackLabels are displayed.

#### Product version
Highcharts 7.2.0

#### Affected browser(s)
At least Firefox, and Google Chrome

**Comment by Basts** [comment]
Closed by #12779
