### ISSUE TITLE
Two labels from left and right Y axis are displayed

### ISSUE THREAD

**Issue by fameriks** [highcharts/highcharts#12298]
#### Expected behaviour
In a case when user clicks on chart to enter "edit" mode (see jsfiddle for implementation) if there is disabled and "shared: false" tooltip it will display TWO data labels for right series (red color on example).

#### Actual behaviour
Should display only ONE data label per crosshair on the left/right depending on the series Y axis.

#### Live demo with steps to reproduce
https://jsfiddle.net/fameriks/2pxvgs3o/50/

Steps to reproduce:

1. open jsfiddle
2. move cursor to any point from red series
3. hit mouse click AND don't move cursor
4. observe two labels on left and right Y axes

Looks like this setting affects it (even when tooltip is disabled) https://api.highcharts.com/highstock/tooltip.shared - One label when shared is "true". Two labels when shared is "false"

#### Product version
Highstock 7.2.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting this issue @fameriks 

*Internal note:*
On update we render crosshairs for all axes, not only the linked to point ones: https://github.com/highcharts/highcharts/blob/d6ee188291f7e390bfcfbad69dcb5a103f734664/js/parts/Pointer.js#L647-L652
