### ISSUE TITLE
Cannot read property 'graphic' of undefined when no data and acessibility module is enabled.

### ISSUE THREAD

**Issue by vicentemaximilianoh** [highcharts/highcharts#12299]
#### Expected behaviour
No errors when accessibility module is enabled and data is empty.

#### Actual behaviour
I'm getting an error when there are not points and accessibility module is enabled.

```
ERROR TypeError: Cannot read property 'graphic' of undefined
    at k.H.Series.setA11yDescription (accessibility.src.js:120)
    at k.<anonymous> (accessibility.src.js:113)
    at k.a.<computed> [as render] (highstock.js:18)
    at k.redraw (highstock.js:297)
    at highstock.js:239
    at Array.forEach (<anonymous>)
    at a.each (highstock.js:26)
    at a.Chart.redraw (highstock.js:238)
    at highstock.js:154
    at a.fireEvent (highstock.js:28)
```
The issue is in line 120. If there aren't points then `this.points[0]` is undefined.
Some check needs to be added (e.g. `this.points.length`).

This has been fixed in 7.2 version.

```
getSeriesFirstPointElement: function (series) {
                return (
                    series.points &&
                    series.points.length &&
                    series.points[0].graphic &&
                    series.points[0].graphic.element
                );
            }
```

#### Live demo with steps to reproduce
--

#### Product version
5.0.0

**Comment by pawelfus** [comment]
Hi @vicentemaximilianoh 

Thanks for reporting the issue - as you noticed it's fixed, so please update Highcharts to v7.2.
