### ISSUE TITLE
Functionality in highcharts which support a spline chart and inverted stacked column in a same chart

### ISSUE THREAD

**Issue by saishikkanderCL** [highcharts/highcharts#12290]
Do we have functionality in highcharts which support a spline chart and inverted stacked column in a same chart like the below chart? If yes, Can you please provide some code samples? I have given a mock image below.

Note : In the below image please consider the spline chart and the bottom activity stacked bar chart alone

![image](https://user-images.githubusercontent.com/52405719/67754690-da2ad780-fa71-11e9-89a0-8b979ae8dec7.png)

**Comment by pawelfus** [comment]
Hi @saishikkanderCL 

In case of questions, please use our other support channels: https://www.highcharts.com/blog/support/ (forum/email). You posted on our bug tracker :)

PS: Check x-range series: https://www.highcharts.com/demo/x-range
