### ISSUE TITLE
how to sankey drilldown  to dependencywheel 

### ISSUE THREAD

**Issue by jianghong3** [highcharts/highcharts#12303]
#### Expected behaviour

snakey  drilldown  to dependencywheel, how to achieve it?

**Comment by pawelfus** [comment]
Hi @jianghong3 

Thanks for using Highcharts! You posted on our bug tracker, for questions please use other support channels (forum, stackoverflow or contact us via email): https://www.highcharts.com/blog/support/

**Comment by jianghong3** [comment]
I can't contact your administrator, and my email was returned, and I can't register. Please help me

**Comment by sebastianbochan** [comment]
Which email / IP do you have? Will check our spam list.
