### ISSUE TITLE
variablepie : setting data.z & data.y to 0 doesn't removes data labels and connector line

### ISSUE THREAD

**Issue by mukeshsharma1201** [highcharts/highcharts#12304]
#### Expected behaviour
setting series.data.z and series.data.y value of variablepie to 0 should remove the series data from the graph and remove data labels and connector line.

#### Actual behaviour
setting series.data.z and series.data.y value of variablepie to 0 doesn't remove connector line and data labels.

#### Live demo with steps to reproduce

https://jsfiddle.net/mukeshshamra1201/3jny26a1/

#### Quick Fix
In my testing, I found that setting series.data.z and series.data.y to -1 removes it from the graph.

#### Product version

Highcharts JS v7.2.0 (2019-09-03)

#### Affected browser(s)
Chrome, Safari
Not Checked on other browsers

**Comment by pawelfus** [comment]
Hi @mukeshsharma1201 

Thanks for reporting this issue! This is however expected behaviour. You can hide/disable labels using `dataLabels.formatter`: 
```js
dataLabels: {
    formatter: function () {
      	return this.z === 0 && this.y === 0 ? undefined : this.name;
    }
},
```
Demo: https://jsfiddle.net/BlackLabel/ywbjpLmu/

**Comment by mukeshsharma1201** [comment]
@pawelfus Thanks for helping me out.  I was facing the same issue with pie as well. 
I wasn't aware that this is expected behaviour!

adding this data label formatter fixed the issue
```
dataLabels: {
    	formatter: function () {
      	return this.z === 0 && this.y === 0 ? undefined : this.name;
      }
    }
```

**Comment by mukeshsharma1201** [comment]
I am closing the issue as it was expected behaviour.
