### ISSUE TITLE
For stacked labels changed poistion after 7.1.3

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#12308]
In version 7.1.2 -> 7.1.3 for stackedLabels changed position.
7.1.2
![image](https://user-images.githubusercontent.com/6030335/67851157-e028c300-fb1a-11e9-92b1-6ea0a99964b4.png)

7.1.3
![image](https://user-images.githubusercontent.com/6030335/67851202-f8004700-fb1a-11e9-8a1e-a000e4c9f627.png)

#### Expected behaviour
Did not change position

#### Actual behaviour
Changed position

#### Live demo with steps to reproduce
7.1.2
https://jsfiddle.net/ju1b86c4/
 
7.1.3
https://jsfiddle.net/txoLpnec/

#### Product version
Highcharts 7.1.2 - 7.2.0

#### Affected browser(s)
Chrome 77.0.3865.120

**Comment by pawelfus** [comment]
Hi @balkarov 

Thanks for reporting. I'm not sure if this is an intended change (@TorsteinHonsi , @Basts, could you confirm?), but in v7.1.3 `stackLabels` were improved to support features like overflow/crop/padding/border/background etc.

Now you can set padding (which defaults to 0) for labels, to get the same output as in v7.1.2: https://jsfiddle.net/BlackLabel/dnvL2ebh/

**Comment by balkarov** [comment]
Hello @pawelfus 

thank you for your answer.
Why when you added new properties did not leave this padding (6)? Why did 0?

**Comment by Basts** [comment]
Hi @balkarov, @pawelfus,

It was an intended change. Before implementing overflow and crop features into stack labels, labels were rendered as a text (not a label) with fixed padding set to 6 without possibility to change it. Now it is more 'flexible' and the user has the possibility to set wanted padding. 

[Demo](https://jsfiddle.net/BlackLabel/pdwuahkm/) - v7.1.3 with padding set to 6
[Demo](https://jsfiddle.net/BlackLabel/81f3c6ub/) - previous version with padding set to 20 which doesn't change anything

**Comment by balkarov** [comment]
@Basts @pawelfus 
For `column` chart you have space between column and stacklabels by default
https://jsfiddle.net/jrea47Lv/

![image](https://user-images.githubusercontent.com/6030335/67934065-24c66400-fbd8-11e9-9732-6d894782924c.png)


But for `bar` not
![image](https://user-images.githubusercontent.com/6030335/67934092-3445ad00-fbd8-11e9-8588-103a5b03c48d.png)

**Comment by Basts** [comment]
@balkarov,

Thank you for reporting it, you are right. I will set default padding to 6 for both series and delete fixed distance value for column (which I just found).

**Comment by Basts** [comment]
Closed by #12779
