### ISSUE TITLE
Docs: Link to the getSelectedPoints doesn't work

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#12305]
#### Actual behaviour
https://api.highcharts.com/highcharts/plotOptions.series.allowPointSelect
After clicking on `getSelectedPoints` link I'm redirected to the page that doesn't exist 
https://api.highcharts.com/class-reference/Highcharts.Highcharts%23Chart#getSelectedPoints

#### Affected browser(s)
Google Chrome 78.0.3904.70

**Comment by KacperMadej** [comment]
The correct link should be https://api.highcharts.com/class-reference/Highcharts.Chart#getSelectedPoints
