### ISSUE TITLE
Unable to add annotations with html data 

### ISSUE THREAD

**Issue by ShivaRam1989** [highcharts/highcharts#12319]
#### Expected behaviour
Annotations should be added 

#### Actual behaviour

Annotations are not getting added

#### Live demo with steps to reproduce
Open this fiddle
click on hi button on chart , it should add two annotations but instead it adds only one

https://jsfiddle.net/shivaram1989/19e2gb7j/

**Comment by pawelfus** [comment]
Hi @ShivaRam1989 

Thanks for reporting the issue. This is caused by [`crop`](https://api.highcharts.com/highcharts/annotations.labels.crop) option - set this to false, to change this behaviour: https://jsfiddle.net/BlackLabel/ysto83er/3/
