### ISSUE TITLE
stackedLabel has incorrect position after resize chart container

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#12337]
Hello. 

**Case:**
Resize chart container and update chart size chart.reflow(); and return the size back.

![1](https://user-images.githubusercontent.com/6030335/68295413-6f961f00-00a3-11ea-90da-35ea5de3dd48.gif)

#### Expected behaviour
stackedLabel the same position.
![image](https://user-images.githubusercontent.com/6030335/68295478-905e7480-00a3-11ea-82ea-1282acef1914.png)

#### Actual behaviour
stackedLabel incorrect position.

![image](https://user-images.githubusercontent.com/6030335/68295330-35c51880-00a3-11ea-8ae1-95931645998e.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/nhxy8a91/

#### Product version
Highcharts 7.2.1

#### Affected browser(s)
Google Chrome 78.0.3904.87

**Comment by pawelfus** [comment]
Thanks for reporting this bug @balkarov 

@Basts - could you take a look? Looks like a regression since v7.1.3, v7.1.2 is fine: https://jsfiddle.net/BlackLabel/hp85q3km/

**Comment by TorsteinHonsi** [comment]
Bisected to ed7ea403acc4299600cf8dc5a7d98d53b9ce78b6

**Comment by Basts** [comment]
Closed by #12779
