### ISSUE TITLE
Fill Patterns in polygons are not exported

### ISSUE THREAD

**Issue by brnomendes** [highcharts/highcharts#12339]
#### Expected behaviour
Polygons created with fill patterns should be when exporting the chart to PNG, JPEG, PDF, or SVG.

#### Actual behaviour
When programmatically add a fill pattern and polygon to the chart, the fill patterns are not displayed when export the chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/brnomendes/ys3m81eq/

#### Product version
Highcharts JS v7.2.1 (2019-10-31)

#### Affected browser(s)
Google Chrome 77.0.3865.120

**Comment by pawelfus** [comment]
Thanks for reporting @brnomendes 

This is caused by using `renderer.addPattern(options)` method (which is private). Using official API everything works fine: https://jsfiddle.net/BlackLabel/7s91uae3/

**Comment by brnomendes** [comment]
> Thanks for reporting @brnomendes
> 
> This is caused by using `renderer.addPattern(options)` method (which is private). Using official API everything works fine: https://jsfiddle.net/BlackLabel/7s91uae3/

So for every new polygon added, should necessarily create a new fill pattern?
Isn't there a way to define a pattern with an Id, and reuse it in multiple polygons?

**Comment by pawelfus** [comment]
If the same patterns are found (with the same ID) then patterns are reused for series (not for legend items): https://jsfiddle.net/BlackLabel/og8psqrh/

![Screen Shot 2019-11-06 at 15 22 45](https://user-images.githubusercontent.com/1453926/68306232-74f66800-00a9-11ea-945a-ed2b8ff2120b.png)

If you know all patterns in advance, you can use your solution this way: https://jsfiddle.net/BlackLabel/wd8nbo9y/ (add patterns in callback) or a bit more robust solution: https://jsfiddle.net/BlackLabel/cen1yh8f/ (leveraging fact that callback is called for exported chart too).

**Comment by brnomendes** [comment]
Perfect, thanks for the solutions!
