### ISSUE TITLE
connectNulls for gaps without null values

### ISSUE THREAD

**Issue by smokir** [highcharts/highcharts#12332]
#### Expected behaviour

Not to connect gaps between dots which have more space than one `closestPointRange` between them

#### Actual behaviour

Gap shows only when there is at least one `null` value between distant points 

#### Live demo with steps to reproduce
https://jsfiddle.net/qx97c8fg/

#### Product version
Highcharts

#### Affected browser(s)
Chrome 76.0.3809.1768
FF 69.0.3
Safari 13.0.2

**Comment by pawelfus** [comment]
Hi @smokir 

This feature is available in Highstock and it's called [`series.gapSize`](https://api.highcharts.com/highstock/plotOptions.series.gapSize). Demo: https://jsfiddle.net/BlackLabel/m5pqLdsu/1/
