### ISSUE TITLE
Charts using colorAxis not rendering properly on Mac

### ISSUE THREAD

**Issue by ckirk** [highcharts/highcharts#12336]
#### Expected behaviour
When attempting to add a colorAxis to a column graph the colorAxis should apply colors to the columns based on the value provided for colorKey as in [this](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/coloraxis/custom-color-key) JSfiddle

![Screen Shot 2019-11-05 at 3 51 29 PM](https://user-images.githubusercontent.com/7276073/68245823-99890c00-ffe5-11e9-80c8-1350098b12bb.png)

#### Actual behaviour
HeatMaps and TreeMaps seem to be working properly, but if I try to add a colorAxis to a graph of type column, scatter, packedbubble, etc. it does't render as expected. I get regular, solid-colored points, columns, etc. with a colorAxis in the legend with no numbers or ticks on it. See screencap below:

![Screen Shot 2019-11-05 at 4 01 43 PM](https://user-images.githubusercontent.com/7276073/68246120-3186f580-ffe6-11e9-97d1-edf76b95630e.png)

#### Live demo with steps to reproduce

This is working fine in JSfiddle as my link above demonstrates. It also works fine on PC. However I have tested on multiple macs and they all have this issue in my node/react development environment. 

I am using the same exact code as in the JSfiddle demo, with small changes for npm imports and use of the highcharts-react-official package as a react wrapper. 

I am importing highcharts and initializing the heatMap module as follows: 

```
import Highcharts from "highcharts";
import HighchartsReact from "highcharts-react-official";
import HighchartsHeatmap from "highcharts/modules/heatmap";

HighchartsHeatmap(Highcharts);
```

The JSfiddle demo imports colorAxis.js itself, which doesn't seem to be an option anymore using the npm highcharts package (if this isn't the case, how do I import it?). However importing the entire heatMap module instead of colorAxis.js still renders fine with JSfiddle. Removing the colorAxis or heatMap module entirely on JSfiddle gives me a result similar to my screencap, but without any remnants of a colorAxis in the legend. 

I don't think this is a problem with my implementation because, as I said, it is working just fine with the same exact code on a PC. I believe this is a mac specific bug. 

Any help or advice would be very much appreciated. Thanks!

#### Product version

Highcharts @ 7.2.1
highcharts-react-official @ 2.2.2

#### Affected browser(s)
Chrome, Safari, Electron

**Comment by pawelfus** [comment]
Hi @ckirk 

Thanks for reporting the issue. This is strange, do you have any errors in JS console?

We had similar error in v7.2.1 (see #12231) but should be resolved in v7.2.2 - could you try updating to v7.2.2? Or test this workaround: https://github.com/highcharts/highcharts/issues/12231#issuecomment-544382222

If that's not the case, please recreate issue in standalone env, e.g. stackblitz (good starting point: https://stackblitz.com/edit/react-4ded5d?file=index.js). We will debug this.

To answer your question:

> The JSfiddle demo imports colorAxis.js itself, which doesn't seem to be an option anymore using the npm highcharts package (if this isn't the case, how do I import it?)

To import `coloraxis` module use:
```js
import HighchartsColorAxis from "highcharts/modules/coloraxis"; 

HighchartsColorAxis(Highcharts);
```

**Comment by ckirk** [comment]
No errors in the JS console unfortunately :(

Yeah I tried importing `coloraxis` that way. Doesn't work. There is no coloraxis.js file located in node_modules/highcharts/modules/ in highcharts v7.2.1

I get the following error when I try: 

```
Module not found: Can't resolve 'highcharts/modules/coloraxis' in ...[REDACTED]
```
Happy to try upgrading to v7.2.2 however I can't seem to figure out how to do that. npm doesn't seem to have that version available yet. I'm currently on v7.2.1 is there a specific branch I need to pull from? Also I'll try to recreate the problem on stackBlitz and post here if/when I do. 

Thanks for the quick response!

**Comment by ckirk** [comment]
Sorry I misreported my highcharts version number. I was actually on v7.1.3 before. On v7.2.1 I can import the `coloraxis` module no problem and it appears to fix the issue 👍
