### ISSUE TITLE
Memory leak in polar charts when calling setData

### ISSUE THREAD

**Issue by skrtheboss** [highcharts/highcharts#12335]
#### Expected behaviour
Calling `setData` on a `polar` chart should not result in memory `leak`.

#### Actual behaviour
Calling `setData` multiple times creates new `clippath` elements in the chart's `defs` and does not clean up old ones.

After some debugging i noticed that the `hasClipCircleSetter` is undefined even if it should be true.
https://github.com/highcharts/highcharts/blob/03b23b624103421a18d6e24100190491fb9e45f0/ts/parts-more/Polar.ts#L391-L412

#### Live demo with steps to reproduce
Go to [CodePen](https://codepen.io/skrtheboss/pen/eYYMzrm) and open console, see how the `defs` collection grows.

#### Product version
7.2.1

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Thanks for reporting this @skrtheboss

**Comment by skrtheboss** [comment]
Hi @pawelfus, i tried your solution and it fixes the issue with the clip-paths, but i found another leak with the hcEvents property if i also update the series. Can you please have a look?

[CodePen](https://codepen.io/skrtheboss/pen/YzzLxPr)
