### ISSUE TITLE
CSV Export of arearange series appears to reverse high and low columns

### ISSUE THREAD

**Issue by KevinFernandes** [highcharts/highcharts#12345]
#### Expected behaviour
Exported column headers should match the exported data

#### Actual behaviour
Exports headers appear to be reversed from the data (high = low, low = high)

#### Live demo with steps to reproduce
I am attaching the CSV output text - you can see the last two columns, reflecting the arearange series appear to be reversed.

There are no special configurations or other code manipulations, I just call getCSV() on the chart object.

[chart.txt](https://github.com/highcharts/highcharts/files/3814943/chart.txt)

**Comment by pawelfus** [comment]
Hi @KevinFernandes 

Thanks for reporting the issue, but instead of providing generated CSV could you recreate in jsFiddle? So we can actually debug this. Thanks!

**Comment by KevinFernandes** [comment]
OK, sorry looks like it was our mistake :(
After attempting to recreate the issue using the HighCharts areareange demo - I was unable to reproduce the issue.

So I went back and looked at out code that built the arearange and discovered that we were putting the values in the wrong order.

The area range still drew correctly and the tooltip appeared to display the values correctly as well so it was easily missed until the export was used.
