### ISSUE TITLE
Gauge chart and No data to display

### ISSUE THREAD

**Issue by mungerj** [highcharts/highcharts#12343]
#### Expected behaviour
When a gauge chart has no data to display, the defined noData message should be visible. 

#### Actual behaviour
The message is rendered but behind the main pane, so we can't see it.

#### Live demo with steps to reproduce
https://jsfiddle.net/nq0hos8m/

#### Product version
Highcharts 6.2, but same results with Highcharts 7.2.1

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting @mungerj 

zIndex (and in general the position) of the message can be configured: https://jsfiddle.net/BlackLabel/j0b962q5/ 

API reference:
- zIndex: [`noData.attr`](https://api.highcharts.com/highcharts/noData.attr)
- position: [`noData.position`](https://api.highcharts.com/highcharts/noData.position)

*Internal note:*
It would be nice to set some default zIndex (I guess `1` should be enough).

**Comment by TorsteinHonsi** [comment]
> It would be nice to set some default zIndex (I guess 1 should be enough).

Agreed, this should work out of the box. We also have the same situation with plot bands, plot lines and grid lines, which is likely the same problem: http://jsfiddle.net/highcharts/Lsy9m02r/. This is also solved by setting the `zIndex` to 1.
