### ISSUE TITLE
Memory leak when calling series.update

### ISSUE THREAD

**Issue by skrtheboss** [highcharts/highcharts#12355]
#### Expected behaviour
Updating series should not result in a memory `leak`.

#### Actual behaviour
When calling `series.update()` new events are registered on the `series` and old ones are not removed.

#### Live demo with steps to reproduce
Open one of the `codepens` provided below and see how `events` array grows.

Polar [CodePen](https://codepen.io/skrtheboss/pen/YzzLxPr)
Non Polar [CodePen](https://codepen.io/skrtheboss/pen/gOOzGPV)

#### Product version
Highcharts 7.2.1

#### Affected browser(s)
all

**Comment by skrtheboss** [comment]
I found this `addEvent` call, which is executed on every update call, but previous is not removed:
https://github.com/highcharts/highcharts/blob/75b67ceba8a8e3896ec8a1e8323470ff5f9fc120/js/parts/Series.js#L4112

**Comment by skrtheboss** [comment]
@pawelfus @TorsteinHonsi is there any progress on this?

**Comment by pawelfus** [comment]
Not yet @skrtheboss - ticket is marked with high priority so should be resolved in the next release.

**Comment by bre1470** [comment]
Memory leak started with Highcharts v7.0.3.

**Comment by skrtheboss** [comment]
@TorsteinHonsi are you going to make a new realease soon?

**Comment by sebastianbochan** [comment]
The next release should be available at the beginning of December.
