### ISSUE TITLE
[Typescript] low property is not known for PointOptionsType

### ISSUE THREAD

**Issue by Lolmewn** [highcharts/highcharts#12352]
#### Expected behaviour
In Highcharts v7.1.2., the following point object was valid for a `columnrange` series:
```
{
    x: 0,
    low: 5,
    high: 10
}
```
According to the docs, this should still be valid in Highcharts v7.2.1.: https://api.highcharts.com/highcharts/series.columnrange.data.low

#### Actual behaviour
Typescript throws the following error:
```
ERROR in node_modules/highcharts/modules/map.d.ts(135,26): error TS2304: Cannot find name 'MapDataObject'.
    src/app/chart/render/series/CompareDataSeries.ts(121,13): error TS2345: Argument of type '{ x: number; low: any; high: any; }' is not assignable to parameter of type 'string | number | (string | number)[] | PointOptionsObject'.
      Object literal may only specify known properties, and 'low' does not exist in type '(string | number)[] | PointOptionsObject'.
```

#### Live demo with steps to reproduce
n/a

#### Product version
Highcharts v7.2.1.

#### Affected browser(s)
n/a

**Comment by sebastianbochan** [comment]
Hi @Lolmewn,
Thank you for reporting.

FYI @bre1470
