### ISSUE TITLE
Funnel - dataLabels with allowOverlap set to false wrongly positioned after point hide

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#12350]
#### Behaviour
Funnel chart with `dataLabels.allowOverlap` set to `false` that has a point clicked in the legend is positioning dataLabels in wrong places.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8m60L2b4/
Click one legend item to hide a point and all dataLabels are wrongly positioned.

#### Product version
7.2.1

**Comment by TorsteinHonsi** [comment]
And while we're at it - using the `inside` option, the (default) vertical alignment is wrong. Setting `verticalAlign` to `middle` helps, but the one on the base of the neck/funnel is still a bit off: https://jsfiddle.net/highcharts/j0po635w/
