### ISSUE TITLE
[Typescript] description property is not known for PointOptionsType

### ISSUE THREAD

**Issue by Lolmewn** [highcharts/highcharts#12353]
#### Expected behaviour
In Highcharts v7.1.2., the following point object was valid for a `column` series:
```
{
    x: 0,
    y: 5,
    description: "Some description"
}
```
According to the docs, this should still be valid in Highcharts v7.2.1.: 
https://api.highcharts.com/highcharts/series.column.data.description

#### Actual behaviour
Typescript throws the following error:
```
    src/app/chart/render/series/OutlierDataSeries.ts(76,11): error TS2345: Argument of type '{ x: number; y: number; description: number; }' is not assignable to parameter of type 'string | number | (string | number)[] | PointOptionsObject'.
      Object literal may only specify known properties, and 'description' does not exist in type '(string | number)[] | PointOptionsObject'.
```

#### Live demo with steps to reproduce
n/a

#### Product version
Highcharts v7.2.1.

#### Affected browser(s)
n/a

**Comment by sebastianbochan** [comment]
Hi @Lolmewn,
Thank you for reporting.

FYI @bre1470

**Comment by TorsteinHonsi** [comment]
FYI @oysteinmoseng This is a deprecated accessibility option right?

**Comment by oysteinmoseng** [comment]
Yes, and removed as of a few minutes ago. Will be removed from docs with the next release.

If you want to add a description to a column point to be picked up by screen readers, `point.accessibility.description` is now the default way to do that. If you are adding the description for your own use (e.g. to display in tooltip), I am not sure how our TS declarations handle that (@bre1470 ?)

**Comment by bre1470** [comment]
If a doclet contains a `@deprecated` tag, it will be not included in declarations.

**Comment by bre1470** [comment]
Workaround is to use the [`[series].accessibility.description`](https://api.highcharts.com/highcharts/series.column.accessibility.description) option. For implementations, that can not be changed, you can modify existing declarations as followed:
```ts
declare module 'highcharts' {
    interface SeriesOptions {
        description: string;
    }
}
```
See https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-beta#extending-highcharts-in-typescript

**Comment by bre1470** [comment]
As this is about a deprecated option, the issue has been closed.
