### ISSUE TITLE
Zooming with drilldown and boost enabled

### ISSUE THREAD

**Issue by Katona** [highcharts/highcharts#12369]
Drilldown into a value on the x-axis, then zoom in several times.

#### Expected behaviour
Zooming should stop at the lowest possible level.

#### Actual behaviour
Zoom stops, but the colors disappear from the chart (everything becomes white).

#### Live demo with steps to reproduce
https://jsfiddle.net/3e0816zb/

#### Product version
7.2.1

**Comment by sebastianbochan** [comment]
Hi @Katona,
Thank you for reporting.

Steps to reproduce:
1. Zoom 2 times
2. drill down (by xAxis label)
3. zoom 2 times

![drilldown](https://user-images.githubusercontent.com/2115686/68661149-bf109b00-053a-11ea-9bb5-e8e98864a11d.gif)

The solution is disable the `seriesThreshold` parameter or disable boost module.

@cvasseng should we consider it as a bug?

**Comment by Katona** [comment]
Thanks for checking it @sebastianbochan. Is there any other workaround apart from disabling the boost module? We are displaying large heatmaps so we would rather not disabling it.

**Comment by Katona** [comment]
This seems to be no longer present in the latest version.

**Comment by pawelfus** [comment]
Thanks @Katona 

Closing as fixed in v8.
