### ISSUE TITLE
"TS2339: Property does not exist on type" for Axis.categories

### ISSUE THREAD

**Issue by sm-Fifteen** [highcharts/highcharts#12363]
The [Highcharts.Axis class appears to have no documented `categories` property](https://api.highcharts.com/class-reference/Highcharts.Axis), even though [the Heatmap demo](https://www.highcharts.com/demo/heatmap) uses it for its tooltip formatter. That feature cannot currently be replicated using [format strings](https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting).

#### Expected behaviour
The following snippet (taken from the heatmap demo linked above) should be considered valid by the Typescript checker.
```ts
import Highcharts from "highcharts/highcharts";

let testTooltip: Highcharts.TooltipOptions = {
    // // pointFormat can't handle categories and has no built-in category formatter
    // pointFormat:'<b>{series.xAxis.categories[this.point.x]}</b> sold <br>' +
    //             '<b>{point.value}</b> items on <br>' +
    //             '<b>{series.yAxis.categories[this.point.y]}</b>',
    formatter: function() {
        return '<b>' + this.series.xAxis.categories[this.point.x] + '</b> sold <br><b>' +
            this.point.value + '</b> items on <br><b>' + this.series.yAxis.categories[this.point.y] + '</b>';
    }
}
}
```

#### Actual behaviour
Typescript reports `TS2339: Property does not exist on type` for both `xAxis.categories` and `yAxis.categories`. 

#### Live demo with steps to reproduce
Can't provide live demo for Typescript type checking.

#### Product version
Highcharts and Highstock v7.1.1 + Online documentation

#### Affected browser(s)
No browsers, only type validation.

**Comment by pawelfus** [comment]
Thanks for reporting @sm-Fifteen 

@bre1470, @TorsteinHonsi - any objections?

**Comment by TorsteinHonsi** [comment]
I think we can safely expose `Axis.categories`, though as read only.
