### ISSUE TITLE
Cannot disable series hover

### ISSUE THREAD

**Issue by Kierchon** [highcharts/highcharts#12377]
#### Expected behaviour
When I set hover to false, I want to disable all the effects of hovering over the chart

#### Actual behaviour
With multi series charts, the series is highlighted on hover no matter what

#### Live demo with steps to reproduce

https://jsfiddle.net/pro1uq3v/

Create a chart with multiple series and set hover and tooltip to false
#### Product version

All

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
The `hover` state is actually correctly disabled in your demo - what we see is the `inactive` state dimming the other series. So the solution is to disable that too: https://jsfiddle.net/highcharts/gb1v2046/
