### ISSUE TITLE
Sankey nodes are rearranging itself

### ISSUE THREAD

**Issue by harpalshergill** [highcharts/highcharts#12374]
I have a sankey diagram, where I am reassigning the nodes in specific columns based on business case. However, when browser window is resized or user click on "View in full screen" at top right, the Sankey nodes are rearranged itself. 

#### Expected behaviour
regardless of change in size of browser or "view in full screen" click event, the chart should display the same design as at initial load. here is a screen shot

![image](https://user-images.githubusercontent.com/5815210/68511771-ac4d4c00-0244-11ea-941d-9bacde3396e6.png)

#### Actual behaviour

![image](https://user-images.githubusercontent.com/5815210/68511757-a0fa2080-0244-11ea-868e-436b7fd82dd2.png)

#### Live demo with steps to reproduce
template: https://jsfiddle.net/harpalshergill/1zyp25kw/15/

once the chart is rendered, click on "View In Full Screen", you will see that column 2 and 3 have been rearranged. 

#### Affected browser(s)
Chrome, Firefox and IE Edge

**Comment by pawelfus** [comment]
Thanks for reporting this issue @harpalshergill 

@TorsteinHonsi - could you take a look?

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! It is an issue in how the nodes are ordered within the `generatePoints` function.

#### Workaround
Modify the sankey series prototype like this:
`Highcharts.seriesTypes.sankey.prototype.orderNodes = false;`

[View it live on jsFiddle](https://jsfiddle.net/highcharts/9b3ty6og/).
