### ISSUE TITLE
drill down issue in edge browser

### ISSUE THREAD

**Issue by bdevika** [highcharts/highcharts#12379]
device ->microsoft surface pro(Windows 10 home)
browser -> Microsoft edge 44.18362.387.0
example -> https://www.highcharts.com/demo/column-drilldown
step to reproduce the issue
1. open above example in edge browser
2. A single tap on the bar (not using a mouse, taping on the bar, not name link), I expected it will drill down but on double-tap drill down happens . is this actual behavior? if so in iPad on a single tap drill-down happens.
3. Try to zoom in chart it zooms the entire page instead of a graph. But on the iPad, it works fine.

**Comment by jon-a-nygaard** [comment]
Thanks for reporting the issue @bdevika.
We will look into solving this issue as soon as possible.

**Internal note:**
I am experiencing the same issue on my setup, same device and same browser version.

My assumption is that the column is using `Highcharts.addEvent` to register the click event, while the label is using `Highcharts.SVGElement.on` to register its click event. Alternatively it could be the other way around.

The `on` function seems to be handling click events on touch devices in a special way. https://github.com/highcharts/highcharts/blob/73f384bb813ae41420113df7e66f966fd91f839d/ts/parts/SvgRenderer.ts#L1921-L1933

Interesting observation is that double tapping on the column will actually achieve a drilldown.

If my assumption above is correct, then I believe that somehow unifying these to event register functions would be beneficial. For example moving the custom logic in `on` into `addEvent`, and have `on` call `addEvent` internally.
