### ISSUE TITLE
TS2339: Property 'dataMax' does not exist on type 'Series'. (also dataMin)

### ISSUE THREAD

**Issue by RandScullard** [highcharts/highcharts#12378]
The TypeScript definition of `Highcharts.Series` in `highcharts.d.ts` is missing the `dataMin` and `dataMax` properties, even though these properties are present at runtime (via `this.series`) in formatter functions. [This JSFiddle](http://jsfiddle.net/d4aLp5u9/1/) (authored by @TorsteinHonsi)  illustrates a data label formatter that uses `series.dataMax`.

#### Expected behaviour
This bit of code (from the JSFiddle linked above) should compile successfully in TypeScript:

```
$(function() {
  $('#container').highcharts({
    chart: {
      type: 'column'
    },
    xAxis: {
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },
    plotOptions: {
      series: {
        allowPointSelect: true,
        dataLabels: {
          enabled: true,
          formatter: function() {
            var dataMax = this.series.dataMax; // *** This line fails to compile ***
            if (this.y === dataMax) {
              return this.y;
            }
          }
        }
      }
    },
    series: [{
      data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    }]
  });

```

#### Actual behaviour
The following compiler error occurs where `this.series.dataMax` is referenced in the formatter function:
`TS2339: Property 'dataMax' does not exist on type 'Series'.`

Same problem if you reference `this.series.dataMin`.

#### Live demo with steps to reproduce
Not applicable to TypeScript compile-time issue.

#### Product version
Highcharts 7.2.1

#### Affected browser(s)
Not applicable to TypeScript compile-time issue.

**Comment by sebastianbochan** [comment]
Hi @RandScullard,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by TorsteinHonsi** [comment]
In my opinion it wouldn't hurt to expose these properties. They are read only.

**Comment by bre1470** [comment]
@TorsteinHonsi I wonder if we should make `Series.getExtremes` public as well, as it might become handy in dealing with it in some situations.
