### ISSUE TITLE
Bar or Stacked Bar rotation label

### ISSUE THREAD

**Issue by kekko1** [highcharts/highcharts#12375]
Hi, 
When I create a Bar or Stacked Bar chart and set the rotation 135 (example) the chart labels are hidden.
https://jsfiddle.net/pfbu54d0/

How can I solve it?
thanks

**Comment by TorsteinHonsi** [comment]
For some reason the auto alignment makes the labels render outside the chart area. Probably the issue hasn't been detected before because rendering labels upside down is not a common use case.

#### Workaround
Set `labels.align` to `center`: https://jsfiddle.net/highcharts/6cLar2sg/

**Comment by kekko1** [comment]
I have set the parameter align = center
and it works well.
tested on the latest version (in previous versions, it could have problems eg v4.2.5).
Last consideration, this is fine in Bar or Stacked graphs

thanks 👍
