### ISSUE TITLE
Trojan:JS/Sonbokli.A!cl

### ISSUE THREAD

**Issue by MasterRyd3l** [highcharts/highcharts#12386]
this is found in highchart.js 7.2.1 by windows defender.

windows defender didn't set off alarm with version 7.2.0

**Comment by pawelfus** [comment]
Hi @MasterRyd3l 

How did you get Highcharts and which file? Did you install them from NPM or Bower? Did you download this from **our** CDN? Is it `highcharts.js` or `highcharts.src.js`? Or perhaps one of modules?

Thanks for all of the details you can provide!

**Comment by MasterRyd3l** [comment]
I installed from npm with yarn. I cleared yarn cache first. The vulnerability is from highchart.js in yarn's cache folder

**Comment by PhanidharG** [comment]
We tested this on two machines and reproduced the issue to be sure.

**Comment by AntonyJos** [comment]
@pawelfus / @TorsteinHonsi ,
Hope this issue is being dealt with high priority

**Comment by oysteinmoseng** [comment]
Internal note: The file in the yarn cache on my mac is identical to the one released here: `http://code.highcharts.com/7.2.1/highcharts.js`.

**Comment by jon-a-nygaard** [comment]
I was unable to reproduce this issue. System information and steps are available below.
I think we may need more information on the system and steps required to reproduce this issue.

# System information
OS Name: Microsoft Windows 10 Pro
Version: 10.0.18362 Build 18362

# Steps
1. Downloaded and ran Yarn installer from https://yarnpkg.com/en/docs/install#windows-stable
2. Opened cmd and ran the following commands:
```cmd
C:/.../> yarn -v
1.19.1

C:/.../> mkdir yarn-test

C:/.../> cd yarn-test

C:/.../yarn-test> yarn cache clean
yarn cache v1.19.1
success Cleared cache.
Done in 0.30s.

C:/.../yarn-test> yarn init --yes
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
Done in 0.06s.

C:/.../yarn-test> yarn add highcharts
yarn add v1.19.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ highcharts@7.2.1
info All dependencies
└─ highcharts@7.2.1
Done in 3.02s.
```

3. Go to the Windows Start and open the app named Windows Security
4. Click on "Virus & threat protection"
5. Click on "Scan options"
6. Select "Custom scan" and click on "Scan now"
7. Select the folder named "yarn-test" in the file navigation, and click on "Select Folder"
8. Windows Defender outputs the following:
```
No current threats.
Last scan: 11/13/2019 1:50 PM (custom scan)
0 threats found.
Scan lasted 1 seconds
1072 files scanned.
```
9. I did the same scan for the directory that is outputted when running `yarn cache dir`, and it also returned `No current threats.`

**Comment by oysteinmoseng** [comment]
Same results as Jon on a different Windows computer with the same OS build version.

[VirusTotal](https://www.virustotal.com/gui/home/upload) also found no issues with the file.

**Comment by jon-a-nygaard** [comment]
@MasterRyd3l, @PhanidharG, and @AntonyJos, any information that you can provide about OS, Yarn, Windows Defender, and the alarmed files will be greatly appreciated.
Our research so far is unable to find any traces of malware in our distributed files.

**Comment by MasterRyd3l** [comment]
I appear to not be able to repro anymore either. This is most puzzling. I will close the issue for now.

**Comment by massilvaLaz** [comment]
Hello, 
I'm still having the issue 

OS Name: Windows 10 Famille
Version: 18362.900
nodejs version :  v12.18.0
npm version : 6.14.4

I ran the following:
`npm install highchart@8.1.2`
