### ISSUE TITLE
Crash when show/hide series with zones

### ISSUE THREAD

**Issue by KevinFernandes** [highcharts/highcharts#12391]
Data needs to be in a certain form and user interaction needs to follow a certain pattern.

Our data is large so we have dataGrouping, thresholds and the boost module enabled.  I cannot be certain if any of them or some combination of them is contributing to the issue.

We have two series of hourly data; series 1 starts at the beginning of the month and ends at about the middle of the month, series 2 starts some time after series 1 and ends at the end of the month.

Zones are created for both series from the beginning of the month to the end of the month.
I mention this specifically because the error indicates it is applying zone information.

The demo here depicts the issue as close as I could get it with one of the Highcharts demos.
[https://jsfiddle.net/kevinfernandes/ozp4L7c0/](https://jsfiddle.net/kevinfernandes/ozp4L7c0/)

To reproduce the issue with this demo:
1. The chart begins zoomed into a spot already (this is important, the problem only seems to happen when zoomed), scroll to the left until both series are visible.
2. Scroll back to the right until only one series is visible
3. Click the button at the bottom of the chart to toggle one of the series (the series that should no longer be visible), you may have to click twice to hide then show the series.  You will receive an error in the browser console like the following:

```
Uncaught TypeError: Cannot read property 'clip' of undefined
    at highstock.src.js:30683
    at Array.forEach (<anonymous>)
    at d.applyZones (highstock.src.js:30616)
    at d.render (highstock.src.js:30846)
    at d.redraw (highstock.src.js:30925)
    at highstock.src.js:23915
    at Array.forEach (<anonymous>)
    at c.Chart.redraw (highstock.src.js:23913)
    at d.setVisible (highstock.src.js:39484)
    at d.show (highstock.src.js:39498)
```

The problem occurs only when zoomed into a portion of the chart such that one of the series is no longer visible and then that series is toggled to hide/show - we have also been able to reproduce it with a series.update() or when resizing the browser window.

#### Product version
The demo uses Highstock from the web - not sure which version this is.
The version we encountered the issue is Highstock 7.2.0

#### Affected browser(s)
Tested and found using Chrome 78

**Comment by pawelfus** [comment]
Thanks for reporting the issue @KevinFernandes 

*Internal note:*
Issue comes from this place (checking `series.graph`, but calling `series['zone-graph-N']`):
https://github.com/highcharts/highcharts/blob/f395e0ee54ea510c0f9f1166b50017d50026f78e/ts/parts/Series.ts#L6034-L6040

In the scenario described above (zoom into series, zoom out of series, hide series, show series) we end up with defined `series.graph` but removed `series['zone-graph-N']`. Additionally we can add zones to preserved shapes here in `series.update()`:
https://github.com/highcharts/highcharts/blob/f395e0ee54ea510c0f9f1166b50017d50026f78e/ts/parts/Dynamics.ts#L1514-L1516

**Comment by dantish** [comment]
Hi! I’m experiencing the same issue too, is there any progress on this?

**Comment by pawelfus** [comment]
Hi @dantish - we haven't had time to prioritise this issue.

**Comment by sebastianbochan** [comment]
Simplified demo:
- http://jsfiddle.net/BlackLabel/faer2uo0/
