### ISSUE TITLE
Links in tooltips are unclickable when using styledMode

### ISSUE THREAD

**Issue by andrewpucci** [highcharts/highcharts#12394]
#### Expected behaviour

Should be able to interact with links in tooltips when styledMode is true.

#### Actual behaviour

Tooltips are visible, but links are not able to be clicked

#### Live demo with steps to reproduce

Using the [CodePen boilerplate](https://codepen.io/anon/pen/eQyawK) mentioned in the docs, I created a fork that adds the following lines of code: https://codepen.io/andrewpucci/pen/wvvEpmm

```javascript
tooltip: {
    followPointer: false,
    useHTML: true,
    style: {
      pointerEvents: 'auto',
    },
    formatter() {
      return `<a href="https://www.google.com">Link</a>`;
    }
  },
```

Hover over one of the pie slices and try to click the link in the tooltip. Notice that the pointer does not change, nor does clicking on the link open Google.

#### Product version

Highcharts 7.2.1

#### Affected browser(s)

Tested in Chrome 78.0.3904.97, Firefox 70.0.1, and Safari 13.0.3, all on macOS 10.14.6

**Comment by pawelfus** [comment]
Hi @andrewpucci 

Thanks for reporting the issue. In styled mode, you should place styles in CSS. For example:
```css
.highcharts-tooltip {
    pointer-events: auto;
}
```

Demo: https://jsfiddle.net/BlackLabel/2oyf0v79/

**Comment by andrewpucci** [comment]
Hi @pawelfus, can you please explain the [custom theme using SASS section](https://www.highcharts.com/docs/chart-design-and-style/custom-themes-in-styled-mode#b-custom-theme-using-sass) in the documentation, then? The CodePen I forked was directly from the documentation and I didn't change any of the styling rules.

We use SCSS to generate our styles and I would rather use our existing variables for colors, fonts, etc to override the values rather than overwrite CSS rules.

**Comment by andrewpucci** [comment]
Apologies, @pawelfus, I think I read your reply incorrectly. The emphasis was on the fact that I can't use `style: { pointerEvents: 'auto', },` in my chart config because it wouldn't be used in styledMode. The documentation was confusing to me here.

In this case, I think there should be a SCSS variable defined that will allow you to set the highcharts-tooltip pointer-events to `auto` so we don't have to write CSS overrides.

Maybe something like `$tooltip-pointer-events: none !default;`. But this is an enhancement, so I'll move it over to uservoice.

Thanks!

**Comment by pawelfus** [comment]
Thanks for you suggestion! 

FYI @TorsteinHonsi
