### ISSUE TITLE
AxisOptions width is missing in documentation

### ISSUE THREAD

**Issue by Sintifo** [highcharts/highcharts#12392]
#### Expected behaviour
Setting the width correctly adjusts the width of the xAxis. This allows to set 2 axes next to each other.
Argument should be documented in documentation and therefore in generated types.

#### Actual behaviour
Width is missing in documentation

#### Live demo with steps to reproduce
1. Configure chart
2. Set width in axis config 
```
{
    xAxis: [
        {
          id: 'xAxis-low',
          type: 'datetime' as 'datetime',
          min: xmin,
          max: xmin + 0.5 * (xmax - xmin),
          width: '50%',
          left: '50%',
          offset: 0,
        },
        {
          id: 'xAxis-high',
          type: 'datetime' as 'datetime',
          min: xmin + 0.5 * (xmax - xmin),
          max: xmax,
          width: '50%',
          offset: 0 
        },
    ]
}
```

#### Product version
Tested with highcharts@7.2.1

I tried to fix the documentation and set a PR but was not sure about the correct formation and there is nothing about correct documentation contribution in the CONTRIBUTING.md.

**Comment by pawelfus** [comment]
Thanks for reporting @Sintifo 

Any comments here @bre1470, @TorsteinHonsi ? In Highstock, `height`+'`top` is documented.

**Comment by TorsteinHonsi** [comment]
Yes I think it should be documented. Also, since `height` and `top` is already working in Highcharts as well as Highstock, we shouldn't hide them from Highcharts.
