### ISSUE TITLE
Legend width not working when legend item contains html tags

### ISSUE THREAD

**Issue by tanek100** [highcharts/highcharts#12404]
#### Expected behaviour
All legend items should be wrapped and go to separate lines, if they go over the borders of legend box.

#### Actual behaviour
Items without html tags work almost correct but the ones containing html does not.

#### Live demo with steps to reproduce
https://jsfiddle.net/Lua21twc/

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

It's a bug in the `SVGRenderer`, here demonstrated without the legend: 
https://jsfiddle.net/highcharts/vfxq2u5h/
