### ISSUE TITLE
Firefox + Styled Mode causes "Unexpected value  parsing width attribute."

### ISSUE THREAD

**Issue by swrobel** [highcharts/highcharts#12412]
#### Expected behaviour
Page renders as it does in Chrome, Opera, Safari, etc. This page worked fine in Firefox before I [switched to using styled mode](https://github.com/swrobel/meta-surf-forecast/commit/51f714fd4ee01583699cf02bdeaa1a8689d50413#diff-71c78393466e83d5917f06e1537662b2).

#### Actual behaviour
Charts do not render & console shows:
```
Unexpected value  parsing width attribute. highcharts.js:92
NS_ERROR_FAILURE: highcharts.js:1084
The above error occurred in the <t> component:
    in t (at SpotChart.jsx:89)
    in ErrorBoundary (at SpotChart.jsx:88)
    in SpotChart
```

As best as I can tell, this is the line on which the error occurs: https://github.com/highcharts/highcharts/blob/v7.2.1/js/parts/SvgRenderer.js#L1168

#### Live demo with steps to reproduce
Visit https://metasurfforecast.com/california/los-angeles
Source available at: https://github.com/swrobel/meta-surf-forecast

#### Product version
Highcharts 7.2.1
Highcharts-react-official 2.2.2

#### Affected browser(s)
Firefox 71 on macOS 10.14
Firefox 70 on Windows 10

**Comment by pawelfus** [comment]
Hi @swrobel 

As you noticed, #11758 is already fixed in the master branch and fix will be part of the next release.

Meanwhile, you can use [this workaround](https://github.com/highcharts/highcharts/issues/11758#issuecomment-546377142).
