### ISSUE TITLE
Reduced plotwidth and plotheight

### ISSUE THREAD

**Issue by aoilti** [highcharts/highcharts#12429]
#### Expected behaviour
create chart in dialog, when this dialog hava zoon animate, and create chart after ajax, expected to create a normal sized chart

#### Actual behaviour
If my Ajax speed is faster than the opening speed of dialog's animation, chart width and height less than container size

#### Live demo with steps to reproduce
https://jsfiddle.net/aoilti/czfusLh2/2/

#### Product version
7.2.1

#### Affected browser(s)
chrome 78.0.3904.97

**Comment by sebastianbochan** [comment]
The github is our bug tracker, so for general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.
