### ISSUE TITLE
Boosted charts have unboosted data remaining on the chart after zoom and reset zoom

### ISSUE THREAD

**Issue by yoderexploder** [highcharts/highcharts#12422]
#### Expected behaviour
Start with a boosted chart that uses zones.  Zoom in, chart is no longer boosted.  Reset zoom, chart becomes boosted again.

#### Actual behaviour
Start with a boosted chart that uses zones.  Zoom in, chart is no longer boosted.  Reset zoom, chart becomes boosted again.  However, the unboosted traces remain on the graph.  **Seems to only happen if zones are being used.**

#### Live demo with steps to reproduce
[https://jsfiddle.net/5xq29pwn/](https://jsfiddle.net/5xq29pwn/)

Upon load you'll see:
![image](https://user-images.githubusercontent.com/22594963/68950030-5703c400-0789-11ea-8d03-132b5803f302.png)
Zoom way in like this:
![image](https://user-images.githubusercontent.com/22594963/68950107-78fd4680-0789-11ea-879d-f1fedcc3aeb2.png)
Now reset Zoom:
![image](https://user-images.githubusercontent.com/22594963/68950164-98946f00-0789-11ea-9efb-d200f7b405c7.png)

#### Product version
Highcharts & Boost Module, current versions (7.1.1+)

#### Affected browser(s)
Chome, no other browsers tested.

**Comment by sebastianbochan** [comment]
Hi @yoderexploder,
Thank you for reporting about the problem.

FYI @cvasseng

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/uk95bywg/2/

Config:
```js
    boost: {
    	seriesThreshold: 1
    },
```

**Comment by yoderexploder** [comment]
Thank you @sebastianbochan and @pawelfus.  Forcing the series to always boost using your workaround is what I settled on for now for line charts.  

However, this doesn't seem to work well for area charts.  As you zoom in on an area chart it renders more like a stem/column chart, which you've documented in [issue # 7925](https://github.com/highcharts/highcharts/issues/7925).  Any ides for a workaround with area charts?

Thanks again, great library!

**Comment by pawelfus** [comment]
Thanks!

There's no better workaround for area series - by design those are rendered as vertical lines.

**Comment by tzaitoun** [comment]
@pawelfus  Why doesn't this work when the zone-axis is **"x"**? 
Using your workaround demo by always making it boost: https://jsfiddle.net/34bLw0m9/

There was this fix some time ago: https://github.com/highcharts/highcharts/pull/10439  
Looking at it briefly I see that it checks for y values only and doesn't seem to take the zoneAxis into consideration?
https://github.com/highcharts/highcharts/blob/master/js/Extensions/Boost/WGLRenderer.js#L524

**Comment by pawelfus** [comment]
It looks like a bug in implementation. Could you create separate ticket for that @tzaitoun ? Thanks!
