### ISSUE TITLE
How to enable legend box for a network graph in Highcharts

### ISSUE THREAD

**Issue by babonaresh** [highcharts/highcharts#12424]
#### Expected behaviour

Legend box enabled and visible
#### Actual behaviour
Legend title is displayed but not the legend box

**Comment by sebastianbochan** [comment]
Hi @babonaresh,
Thank you for reporting.

Simplified demo:
- https://jsfiddle.net/BlackLabel/kzhg965b/

Its a regression since 7.0

**Comment by babonaresh** [comment]
> Hi @babonaresh,
> Thank you for reporting.
> 
> Simplified demo:
> 
> * https://jsfiddle.net/BlackLabel/kzhg965b/
> 
> Its a regression since 7.0

The simplified demo doesn't seem to be working. When you enable the showInLegend in data, the entire chart disappers as you can see in the given Demo

**Comment by pawelfus** [comment]
Hi @babonaresh, isn't that the issue? If you wanted to report something else, then please provide **live demo** (follow our issue-template). Thanks

**Comment by pawelfus** [comment]
Bisected to commit 35423a9fc7

**Comment by pawelfus** [comment]
**Workaround:**
Snippet:
```js
Highcharts.seriesTypes.networkgraph.prototype.drawLegendSymbol = Highcharts.LegendSymbolMixin.drawRectangle;
```
Demo: https://jsfiddle.net/BlackLabel/m0s2cygf/

**Comment by ecemkavaz** [comment]
Hello, I am having a problem with creating a legend to a network graph. I want to have more than one series in the legend but I couldn't find any reference regarding this. I have a network graph and I assigned four different colours to the nodes manually. When I enable the legend, series1 appears below the graph. By clicking it I can turn on and off the whole graph. But this is not what I want. I have four colours (categories) and I want to have a legend according to these. Thank you in advance. I would appreciate your help.

**Comment by ecemkavaz** [comment]
Thank you @KacperMadej
