### ISSUE TITLE
sunburst - series update breaks the chart

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#12425]
Doing an update on the series breaks chart functionality (drilldown stops work after it).

#### Live demo with steps to reproduce

[Demo](http://jsfiddle.net/BlackLabel/nv38Lmx7/)
1. Update doesn't change colors,
2. After the update, drilldown stops working,
3. After the second click, drilldown works again,

#### Product version

Highcharts JS v7.2.1 (2019-10-31)

**Comment by TorsteinHonsi** [comment]
FYI @jon-a-nygaard
