### ISSUE TITLE
Webview is no more available with updated version of RN so my app is crashing when i use this library

### ISSUE THREAD

**Issue by nikunjjaineaton** [highcharts/highcharts#12428]
#### Expected behaviour
Should use react-native-webview 

#### Actual behaviour
The library is still referencing to old webview

**Comment by sebastianbochan** [comment]
Hi @nikunjjaineaton,
Thank you for reporting about the bug. The bug has been already reported and all informations are available here: https://github.com/highcharts/highcharts-react-native/issues/8.

Im closing this ticket as duplicate.
