### ISSUE TITLE
Venna diagram: f(a) and f(b) must have opposite signs

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#12434]
#### Expected behavior
We have 3 sets:
A: 5
B: 3
C: 1

And section relations:
A^B: 3
A^C: 1
B^C: 1
A^B^C: 1

It is mathematically possible to create this chart, the final result should look like the chart in the picture: 
![Zrzut ekranu 2019-11-18 o 10 28 41](https://user-images.githubusercontent.com/50931078/69044458-435c9580-09f5-11ea-9256-e283d8032469.png)

#### Actual behaviour
The chart is not displayed + exception in the console:
```
Uncaught Error: f(a) and f(b) must have opposite signs.
    at L (venn.src.js:705)
    at c (venn.src.js:886)
    at M (venn.src.js:898)
    at venn.src.js:930
    at Array.reduce (<anonymous>)
    at Y (venn.src.js:912)
    at e.translate (venn.src.js:1332)
    at highcharts.src.js:24982
    at Array.forEach (<anonymous>)
    at c.Chart.renderSeries (highcharts.src.js:24981)
```

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/jv0p8e3L/

#### Product version
Highcharts 7.2.1

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard
