### ISSUE TITLE
No update for pane options(?)

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#12444]
I am trying to update the pane color in a solid gauge chart by calling chart.update. 
See http://jsfiddle.net/kzoon/k3yb29oz/
The pane color doesn't change.

Am I using the wrong method to update the pane properties?

**Comment by pawelfus** [comment]
Hi @kzoon 
No, it's just a simple mistake: http://jsfiddle.net/BlackLabel/2zL6k8eb/ - you used `chart.update()` without defining `chart` variable.

**Comment by kzoon** [comment]
Man, do I feel stupid!

**Comment by pawelfus** [comment]
Don't worry :) It's dangerous to go alone! Take this: ☕️
