### ISSUE TITLE
Can't update solid gauge border

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#12445]
Solid gauge does accept series options for border width and color, but series.update() doesn't update them. 

See http://jsfiddle.net/kzoon/mgunjf5h/

The series color and data get updated, the border not

**Comment by pawelfus** [comment]
Thanks @kzoon !

*Internal note:*
stroke/stroke-width are only initialized, never updated: 
https://github.com/highcharts/highcharts/blob/d46da1428b65569f6aa1a55b0bf8c7489514ee1c/ts/modules/solid-gauge.src.ts#L522-L548
