### ISSUE TITLE
Montreal missing in countries/ca/ca-all-all

### ISSUE THREAD

**Issue by reward72** [highcharts/highcharts#12441]
#### Expected behaviour
The Canada admin2 map seems to be missing the island of Montreal.  It's the second biggest city in Canada so it's pretty important for the map to be useful.  

#### Actual behaviour
The surrounding divisions are there, but the Island is not. 

#### Product version

Highcharts

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Moving to the correct repo --> https://github.com/highcharts/map-collection-dist/issues/47
