### ISSUE TITLE
dataGrouping points X coordinate

### ISSUE THREAD

**Issue by diogen737** [highcharts/highcharts#12455]
#### Actual behaviour
Grouped points cannot be aligned to certain points within groups when `dataGrouping` is applied.
In fiddle - last point in the series is Nov 19 2019 but last point over which I can hover is Nov 18 2019.

#### Expected behaviour
Being able to control X coordinate for grouped points

#### Live demo with steps to reproduce
https://jsfiddle.net/vz7xwpsn/

#### Product version
7.2.0

#### Affected browser(s)
All

#### To do list:
- [x] - implementation
- [x] - deprecate `smoothed` option + implemented fallback to the new API (e.g. Navigator series use `smoothed` option by default)
- [x] - tests
- [x]  - demos:
  - [x] - candlestick with static data to show `anchor` in action
  - [ ] - line series with "live data" to show `lastAnchor` using `lastPoint` and `firstAnchor` using `firstPoint`
- [x] - API (https://api.highcharts.com/highstock/plotOptions.series.dataGrouping)
- [x] - update docs (https://www.highcharts.com/docs/stock/data-grouping)

**Comment by pawelfus** [comment]
Hi @diogen737 

Did you consider using [`dataGrouping.smoothed`](https://api.highcharts.com/highstock/plotOptions.line.dataGrouping.smoothed) option? This shifts data to the middle of the group.

In general, please post your ideas on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api) - we use github issues as bug trackers. Thanks!

**Comment by diogen737** [comment]
Hi @pawelfus 

Thanks for the reply. `dataGrouping.smoothed` is not an option because I need exactly the last point of the group to be displayed

**Comment by pawelfus** [comment]
Thanks for the explanation. Alternative approach is to use [lazy-loading](https://www.highcharts.com/blog/news/48-loading-millions-of-points-in-highcharts/) solution instead of dataGrouping. In lazy-loading you have full control over all points (meaning both, x and y, values).

**Comment by diogen737** [comment]
@pawelfus good point, but in that case I'll have to go through the series and group points manually every time extremes are set, right?

will there be such option in `dataGrouping` section?

**Comment by pawelfus** [comment]
That's correct @diogen737, but only if you want to do this in browser. In lazy loading, you can group points, for example daily in the backend, and just serve data.

In general (no matter if this is calculated in frontend or backend), you can try our [dataGrouping](https://www.highcharts.com/docs/working-with-data/server-side-data-grouping) module and modify that last point's `x` value.

> will there be such option in dataGrouping section?

This depends on number of votes in the UserVoice ticket.

**Comment by diogen737** [comment]
@pawelfus noted. But unfortunately in my case it's not an option to modify backend or setup new one. Besides this kind of grouping I need appears in pretty rare case so there's no point in server side grouping.

Anyway thanks for the help and waiting for the UserVoice ticket

**Comment by pawelfus** [comment]
If anyone needs this too, please vote for it: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/39090745-provide-control-over-x-axis-point-in-datagroupng

**Comment by nzayatz14** [comment]
+1

**Comment by pawelfus** [comment]
*Internal note:*
First stage: Define API draft (week 7-8)

**Comment by NielsHolt** [comment]
Hi
In the current version the period use to create the x-axis-label is between the first timestamp and the timestamp after the last timestamp minus 1 millisecond. 
So a period covering 3 hourly values at ea.. 18:00, 19:00 and 20:00 will get the period 
18:00:00:000 - 20:59:59:999 
A period covering 3 monthly values  at ea. Jan, Feb and Mar 2020 will get the period
2020-01-01 00:00:00:000 to 2020-03-31 23:59:59:999

It is only the formatting of the time and date that remove the "decimals"

I do not think that it is a scientific standard to say that ea.. the values at 18:00, 19:00, and 20:00 represent the time interval 18:00-20:59. 
It could be the interval “17:01-20:00” or “17:30-20:30” or simple the 3 values at “18:00–20:00” with the next period being “21:00-23:00”

Therefore I would like to propose a new options for Highstock data-grouping to set how a time-interval is displayed. 
I don’t know what to call the options, but its possible values could be:

`“exact” `: 18:00, 19:00, 20:00 => `“18:00-20:00”` (should be default)
`“center”`: 18:00, 19:00, 20:00 => `“17:30-20:30”`. Calculated as "first timestamp minus half period to last timestamp plus half 
period"

If needed the possible values could be extended with 
`“start”`: 18:00, 19:00, 20:00 => `“17:01-20:00”`
`“end”`: 18:00, 19:00, 20:00 => `“18:00-20:59”` (= current implementation)

**Comment by pawelfus** [comment]
Hi @NielsHolt 

First of all, thank you for sharing your ideas. We really appreciate your help!

Just to be on the same page:

Do you mean the tooltip value should change, or the point's position on xAxis should change? If the former, then you can modify what's displayed in the tooltip using [`tooltip.formatter`](https://api.highcharts.com/highstock/tooltip.formatter). Or perhaps you want to control how the grouping is decided (where the group starts and ends)? Note the ticket is about x-value of the grouped point. What x-value should be decided for a point. 

> So a period covering 3 hourly values at ea.. 18:00, 19:00 and 20:00 will get the period
> 18:00:00:000 - 20:59:59:999
> ...
> I do not think that it is a scientific standard to say that ea.. the values at 18:00, 19:00, and 20:00 represent the time interval 18:00-20:59.

I'm not sure if I understand the problem. For example, 3H `dataGrouping`, means we start from a point in time X, and group all following points that happened in the next three hours. Excluding the point X+3h, which starts a new group. Given the example with points at 18:00, 19:00, and 20:00, we get:
- 18:00 - 18:59:59.999 - the first hour
- 19:00 - 19:59:59.999 - the second hour
- 20:00 - 20:59:59.999 - the third hour

If we change the granularity, from one hour to one minute (points at 18:01, 18:02, ... , 20:58, 20:59), then I would expect from 3H dataGrouping a grouping of 180 points, not 121.

> “center”: 18:00, 19:00, 20:00 => “17:30-20:30”. Calculated as "first timestamp minus half period to last timestamp plus half period"

I have a small problem with this one. This looks nice only if we have round x-values. In many scenarios, it's not the case. Events on the timeline can happen any time, for example at 17:45. If we start a group from 18:00, but represent this on the chart as a group starting at 17:30, then I'm afraid it would be incorrect?

Or do you want to control the grouping range, so 3H grouping should not start from 18:00, but from 17:30?

> “exact” : 18:00, 19:00, 20:00 => “18:00-20:00”

I'm sorry, this one seems unnatural to me. What range should be in the next group? `21:00 - 23:00`? Then what should happen with points that happen between 20:00 and 20:59? Or should it be `20:01 - 22:01`? Then the next one would be `22:02 - 00:02`? Most probably I'm missing something here :)

**Comment by NielsHolt** [comment]
Hi @pawelfus 

Your questions made me rethink the proposal and I realized that I did not consider the case where the period between the points is less than the unit used to display the grouping-period.  
I will split my proposal into two parts.
The first is a change in the way you set time-range in the tooltip. 
If you have a series with period between each point of 10 min and you make a data-grouping of 2 hours starting at 18:00 you will use the 12 values at 18:00, 18:10, 18:20,...19:40, 19:50, but the time-range will be displayed as 18:00:00:000 - 19:59:59:999
I propose that the correct time-range is 18:00:00:000 - 19:50:00:000
You calculate the end-time in the range as start-time plus 2 hours minus 1 millisecond. 
I think that it would be correct to calculate it as start-time plus 2 hours minus 1 _PERIOD_

The second part is a proposal to have an option allowing the user to use a different position of the values relative to the time-stamp (it is easier to show with an example :-))

In the above example the 2 hour mean value at timestamp 18:00 is calculated from the 12 points _at and after_ the timestamp meaning that the timestamp is at the _start_ of the range.

I propose that the relative placement of the range could be optional. 
The new option could have one of the following values: 
`"start"` =>  mean value at timestamp 18:00 is calculated from the 12 values at 18:00, 18:10,..., 19:40, 19:50 (default)
`"middle"` => mean value at timestamp 18:00 is calculated from the 12 values at 17:30, 17:40,..., 19:10, 19:20
`"end"` => mean value at timestamp 18:00 is calculated from the 12 values at 17:10, 17:20,..., 17:50, 18:00

I hope that this makes more sense :-)

**Comment by pawelfus** [comment]
Thanks for clarifying, now everything seems crystal clear :) 

 1. Tooltip header (datetime formatting)
 
 This is already possible, using `toolitp.formatter`, take a look: https://jsfiddle.net/BlackLabel/q9pmtLhx/
 
 2. Configuring where a group starts and ends.
 
Perhaps we can achieve both, your idea and OP's idea. It seems to be the same, just a bit different perspective. The idea in this issue is to configure where the grouped point is rendered. Given the example 18:00-20:59, by default we render a point at 18:00, and we want to give a possibility to change it for example to 19:00, 21:00, or even 18:45:50.123. Instead of changing start/end of the group, we keep the group as is, changing the resulting point.

So in your case it would be:
- `"start"` => mean value at timestamp 18:00 is calculated from the 12 values at 18:00, 18:10,..., 19:40, 19:50 (default) <= the same as you described
- `"middle"` => **mean value at timestamp 19:00** is calculated from the 12 values at 18:00, 18:10,..., 19:40, 19:50
- `"end"` => **mean value at timestamp 20:00** is calculated from the 12 values at 18:00, 18:10,..., 19:40, 19:50

In fact, the first and last options are exactly the same. And the "middle" one, is already implemented as [`dataGrouping.smoothed`](https://api.highcharts.com/highstock/plotOptions.line.dataGrouping.smoothed) option.

**Comment by NielsHolt** [comment]
Hi @pawelfus 

Regarding item 1: 
I still think that it would be correct to use the actually end date (19:50:00:000) as parameter instead of next time stamp minus 1 millisecond (19:59:59:000). The `toolitp.formatter` is for formatting and it (I think) do not have access to the actual period between the points.  

Regarding item 2: 
I agree. It is the same idea with different perspective witch be very useful for us as well

Thank you :-)
