### ISSUE TITLE
Zero node are shown in dependency wheel

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#12453]
#### Expected behaviour
Nodes with only 0 weights are not shown

#### Actual behaviour
Nodes with only 0 weights are shown

#### Live demo with steps to reproduce
http://jsfiddle.net/kzoon/9u5vfq7e/

Workaround: filter out the 0 values from your data

**Comment by pawelfus** [comment]
FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
The same applies to sankey, so we should look for a fix in the node mixin or in the sankey module: http://jsfiddle.net/highcharts/Lq9jkpxt/6/. In this case the 0 point is not visible, but there is a double distance between the two visible nodes, plus the data label is rendering.

Changing `isValid` is not enough, at it runs to early to know that the sum is 0, plus that these points are strictly valid, they are just 0. So we should look for a fix in the translate / drawPoints logic.
