### ISSUE TITLE
Links misaligned in dependency wheel

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#12456]
#### Expected behaviour
There is a perfect fit between the nodes and their links

#### Actual behaviour
There is a (slight) misalignment between links and their links

#### Live demo with steps to reproduce
See http://jsfiddle.net/kzoon/L79xjed6/
The links of Belgium, Norway and Netherlands extend beyond their node (2 pixels?)
The link from Germany to Spain partially overlaps the link from Netherlands to Spain

#### Product version
Latest

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting!
