### ISSUE TITLE
No legend items in dependency wheel legend

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#12452]
#### Expected behaviour
The legend of a dependency wheel shows the nodes of the dependency wheel

#### Actual behaviour
The legend of a dependency wheel shows only the series name

#### Live demo with steps to reproduce
http://jsfiddle.net/kzoon/6axoy2vh/

I expect the nodes to be in the legend, just like in a pie chart:
https://jsfiddle.net/kzoon/udqgfsat/

**Comment by pawelfus** [comment]
Thanks for sharing the idea @kzoon 

It's not official, but possible, to show legend items per **link** (just like in pie chart: one point=one legend item), not **nodes**: http://jsfiddle.net/BlackLabel/tqencry3/ (not official because hide/show does not work).

**Comment by kzoon** [comment]
I was expecting the node colors + labels in the legend. From the user's point of view that would make the most sense because the colors correspond with nodes and not links.
I hoped to replace the node labels with a legend because node labels get easily cropped (see node labels)
