### ISSUE TITLE
Highcharts.Series#setState: Please add 'normal', 'select' and 'inactive' to the official documentation

### ISSUE THREAD

**Issue by swiss-chris** [highcharts/highcharts#12467]
#### Expected behaviour
https://api.highcharts.com/class-reference/Highcharts.Series#setState mentions not only `'hover'` and `undefined`, but also `'normal'`, `'select'` and `'inactive'` 

Also, there is a mention to use this in combination with https://api.highcharts.com/class-reference/Highcharts.Series#update as mentioned here: https://github.com/highcharts/highcharts/issues/11750#issuecomment-524296009

#### Actual behaviour
https://api.highcharts.com/class-reference/Highcharts.Series#setState mentions only `'hover'` and `undefined` and there's no mention of using it in combination with https://api.highcharts.com/class-reference/Highcharts.Series#update as mentioned here: https://github.com/highcharts/highcharts/issues/11750#issuecomment-524296009

#### Live demo with steps to reproduce
https://jsfiddle.net/afv6tmug/

#### Product version
Highcharts 7.2.1

**Comment by pawelfus** [comment]
Thanks for reporting @swiss-chris
