### ISSUE TITLE
Filenames that contain "/" are missing all content before the "/" and the "/" is not replaced with a different, safe, character

### ISSUE THREAD

**Issue by Chewieez** [highcharts/highcharts#12462]
#### Expected behaviour
When exporting a chart with a custom filename that contains a "/" character, the "/" is replaced with a safe character such as "-" or "_". When the chart is exported, the filename contains all of the characters, minus the "/".

Example, exporting a chart with a custom filename of "Medical/Dental Office" should export as "Medical-Dental Office" or "Medical_Dental Office". 

#### Actual behaviour
When you export a chart with a custom filename such as "Medical/Dental Office" the filename that is generated is "Dental Office" and you lose all the characters that are before the "/". 

#### Notes
We are dynamically generating filenames based on user submitted names, so we cannot guarantee that the user will not place a "/" in the name. 

I have noticed that other frameworks used to export charts handle replacing "/" characters automatically. Tested in html2pdf.js and Filesaver.js

#### Live demo with steps to reproduce
Export the chart in this demo and compare the filename exported versus the filename set in the code. 
demo: https://jsfiddle.net/2wrxe7v3/1/

#### Product version
highcharts version 7.2.0

#### Affected browser(s)
Chrome (Mac and Windows)

**Comment by pawelfus** [comment]
Thanks for reporting @Chewieez 

I believe that for now you can replace this character in config: https://jsfiddle.net/BlackLabel/agvptw7z/ - no matter what user inputs, you need to pass this option to config, so before rendering the chart it should be possible to modify this simple string.

*Internal note:*
We do something similar with chart's title, perhaps this option should be secured the same way? @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Yes, we can replace `/` by `-`. This should only apply to the filename _option_. The default filename is picked from the `title.text` option, and in that case we already do a lot of string filtering.

The code in question is here: 

https://github.com/highcharts/highcharts/blob/fccbd474954486f6f4378e8379fb1cf543bfd7f3/ts/modules/exporting.src.ts/#L1541-L1543
