### ISSUE TITLE
tickAmount not updating when undefined is set

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#12471]
#### Expected behaviour
Return `tickAmount` to `undefined` default.

#### Actual behaviour
Nothing.

#### Live demo with steps to reproduce
http://jsfiddle.net/y52oz9kr/
Steps:
 - A default Chart with default `tickAmount` is loaded (which doc says that is `undefined`).
 - If you change `tickAmount` to a number and update, it works as expected.
 - If you try to change it back to `undefined`, does nothing.
 - If you set it to `null` instead of `undefined`, do not work as expected, as the amount of ticks compared to the starting one is different. Seems that defaults to `5` when `null` is set.

#### Product version
Highcharts 7.2.1 (latest)

#### Affected browser(s)
Chrome?

**Comment by pawelfus** [comment]
Thanks for reporting @Llorx 

It kind of works as expected: as [documented](https://api.highcharts.com/highcharts/yAxis.tickAmount), `tickAmount` should be defined as number, not null/undefined.

On the other hand, calling `yAxis.update()` works fine, please take a look: http://jsfiddle.net/BlackLabel/t1b9sq2g/1/

@TorsteinHonsi - what do you think? This might be an issue especially in wrappers that depends heavily on `chart.update()`.

**Comment by Llorx** [comment]
Yes, just noticed that updating the yAxis directly works as expected.

I think is a bug, or a at least is not normalized, because `chart.update` don't works the same way as `yAxis.update` in this case.
