### ISSUE TITLE
how to fill background color due to its own percentage in pie chart?

### ISSUE THREAD

**Issue by srhtylmz19** [highcharts/highcharts#12472]

**Comment by sebastianbochan** [comment]
Hi @srhtylmz19,
Thank you for contacting us. The github is our bug tracker so for general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.

**Comment by pawelfus** [comment]
Short answer: use coloraxis module with pie chart: https://jsfiddle.net/BlackLabel/a3fdz41L/1/
