### ISSUE TITLE
Does not call click event in point in iOS safari after transform scale

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#12475]
Open this url http://jsfiddle.net/akohp5s2/show in iOS safari and try click same column. 

Video for reproduce 
https://youtu.be/E0si4puJ4Oo

#### Expected behaviour
Click event is called always

#### Actual behaviour
After transform scale click event does not call

#### Live demo with steps to reproduce
http://jsfiddle.net/akohp5s2/ - 7.1.3
http://jsfiddle.net/xr9L32s1/ - 7.2.1

#### Product version
Highcharts 7.2.1

#### Affected browser(s)
iOS 13.2.3 Safari

On highcharts version 6.2.0 it worked
http://jsfiddle.net/srz2pm0y/

**Comment by sebastianbochan** [comment]
Hi @balkarov,
Thank you for reporting about the problem. I agree that problem appears in Safari on iOS.

It looks like a regression.

**Comment by pawelfus** [comment]
*Internal note:*
Needs a bisect first.

**Comment by khlieng** [comment]
Fixed since 9.0.0 (#14810).
