### ISSUE TITLE
Area selection error treemap

### ISSUE THREAD

**Issue by pasapsi** [highcharts/highcharts#12488]
#### Expected behaviour
The area that is selected should increase

#### Actual behaviour
The area is exactly the opposite.

#### Live demo with steps to reproduce
![image-2019-10-04-17-37-49-565](https://user-images.githubusercontent.com/5254401/69519039-1ca8dc80-0f6a-11ea-8622-314ab23148a0.png)

#### Product version
Highcharts 7.2

#### Affected browser(s)
In all browsers

**Comment by pawelfus** [comment]
Hi @pasapsi 

Thanks for reporting. The area you select is actually area you want to zoom in (`zoomType: 'xy'`). You can keep selection functionality without zooming by returning false in [`chart.events.selection`](https://api.highcharts.com/highcharts/chart.events.selection) event.

**Comment by pasapsi** [comment]
Thanks for the answer, but I'm talking about something else. I want to enlarge the area that I highlight with the mouse

**Comment by pawelfus** [comment]
Ah! Thanks for the explanation! It seems that yAxis is kind of reversed? Any idea @jon-a-nygaard ?

I tried to write custom zooming logic: https://jsfiddle.net/BlackLabel/achy3en0/ - first zoom-in action is fine, but all others are still broken (probably value=100 should be calculated).

**Comment by pasapsi** [comment]
@pawelfus Thanks for the decision.

>> It seems that yAxis is kind of reversed?
Yes it is.

**Comment by jon-a-nygaard** [comment]
@pawelfus The `bindAxes` is likely called again, and overrides the `dataMax` and `dataMin` that was set by `setExtremes`. There is also another issue #12326 related to the `bindAxes`.

**Comment by pasapsi** [comment]
@jon-a-nygaard That is, is this a mistake? Please tell me when you can expect a solution to the problem?

**Comment by jon-a-nygaard** [comment]
@pasapsi Yes this is a bug. I have submitted a PR that fixes this issue. It is currently in review, but if accepted the fix should be included in our next maintenance release.

**Internal Note:** When looking at this once more, I realized that it was not related to the `bindAxes` as I mentioned previously. For more information see the related PR.

**Comment by pasapsi** [comment]
@jon-a-nygaard and @pawelfus, Thank you very much for your help and quick feedback.
