### ISSUE TITLE
Highstock-Question: Labels might overlap the rangeSelector. A way yo fix?

### ISSUE THREAD

**Issue by personalGitRep** [highcharts/highcharts#12487]
**Is there option to set a margin between RangeSelector and PlotArea?**

![4](https://user-images.githubusercontent.com/38632477/69478506-8a3cf780-0e08-11ea-9131-4536b39bbe5f.png)

**Comment by pawelfus** [comment]
Hi @personalGitRep 

There's no `margin` option, but you can achieve this by setting [`chart.marginTop`](https://api.highcharts.com/highstock/chart.marginTop) and [`rangeSelector.y`](https://api.highcharts.com/highstock/rangeSelector.y) values, when [`rangeSelector.floating`](https://api.highcharts.com/highstock/rangeSelector.floating) is enabled: https://jsfiddle.net/BlackLabel/qx2n1ms7/3/

**Comment by personalGitRep** [comment]
Hello @pawelfus 
This solution worked great for me. 
Thank you so much.
