### ISSUE TITLE
Chart's width is impacting to my second x axis labels

### ISSUE THREAD

**Issue by christiansr85** [highcharts/highcharts#12486]
In the application I'm working on I have a chart with two x axes. Both are of `category` type (but I think that's irrelevant) and all the series have to be attached to the first axis, so the second has no related data.

The problem is that depending on the width of the chart, the second axis labels are rendered or not. I want always to render them (because it is completely related to the first one).

I have posted a [question in stackoverflow](https://stackoverflow.com/questions/58993222/charts-width-is-impacting-to-my-second-x-axis-labels-in-highcharts) where a couple of workarounds have been proposed.

#### Expected behaviour
A second x axis should display its labels properly independently of the chart's width.

#### Actual behaviour
If the chart is **too width**, then the **second x axis doesn't render its labels**.

#### Live demo with steps to reproduce
https://jsfiddle.net/bch32xn9/

#### Product version
Highcharts v7.2.1 (actually, I found it in the v6.1.0)

#### Affected browser(s)
Mozilla Firefox 70.0.1
Google Chrome 78.0.3904.108
Microsoft Edge 44.18362.449.0

**Comment by pawelfus** [comment]
Thanks for reporting this issue @christiansr85 

The easiest workaround is to add a series to this xAxis: https://jsfiddle.net/BlackLabel/r7gupcnL/ - series does not need to render in legend or anywhere, just bound to the xAxis.

*Internal note:*
In the demo above, when chart is wide enough, we don't recalculate ticks again:

https://github.com/highcharts/highcharts/blob/618fd2ffbe3e6f9fc0550b5bf5049f60350d9c72/ts/parts/Chart.ts#L2537-L2555

**Comment by christiansr85** [comment]
Ok, @pawelfus , I've tried your workaround and it is working fine, so thanks.

**Comment by khlieng** [comment]
Looks like this has been fixed on master.
