### ISSUE TITLE
[Help wanted] How to draw a encapsulating 'plotband' for stacked and non-stacked column chart

### ISSUE THREAD

**Issue by DongShi** [highcharts/highcharts#12497]
Hi there:
The story begins with a request from our UX for a darken background for each category in column chart (be it stacked or not), something like this:

![image](https://user-images.githubusercontent.com/5009987/69593444-2860d580-1034-11ea-8971-0e4f619497f9.png)

My immediate thoughts brings up the [plotBand feature](https://api.highcharts.com/highcharts/xAxis.plotBands), yet it turns out that it is a bit difficult to set the "from" and "to" property of plotBand to make the band encapsulate closely to the bars. 

After some search, I find someone proposed this solution 
http://jsfiddle.net/rgs9uv39/
This is using 'grouping' property and I think it works well for non-stacked case.
However after I apply the same methodology to stacked cases, I can see that some bars are off the the position they should be: 
http://jsfiddle.net/exu81sgj/

![image](https://user-images.githubusercontent.com/5009987/69601448-2a845d80-104f-11ea-8511-1e0467a44789.png)

Also it seems the label '15' is always there, even I disabled the data label for the particular series.

Just wonder is it possible to get those bar's position right?
If grouping is not an option, is it possible to enhance the plotBand property so I can get it encapsulate the bars closely.,

#### Expected behaviour
http://jsfiddle.net/rgs9uv39/

#### Actual behaviour
http://jsfiddle.net/exu81sgj/

#### Product version

Highcharts

#### Affected browser(s)
all.

**Comment by pawelfus** [comment]
Hi @DongShi 

Thanks for using Highcharts. FYI: You posted on our bug tracker, when you want to post a question, post it on our forum or contact our support team directly (see [details](https://www.highcharts.com/blog/support/)).

Short answer:
- `grouping` should be disabled for all series
- extra labels are `stackLabels`, not `dataLabels` - which you can enabled only **per yAxis**, not per stack

Demo with two yAxes instead: http://jsfiddle.net/BlackLabel/c4zuhqex/3/
