### ISSUE TITLE
Packed bubble drop events not firing

### ISSUE THREAD

**Issue by ashleyHutton** [highcharts/highcharts#12495]
#### Expected behaviour
The packed bubble chart is not firing drop events as expected. Looking into the issue, the `draggable-points` module seems to require that the chart has a cartesian series:

```
function isChartDraggable(chart) {
            var i = chart.series ? chart.series.length : 0;
            if (chart.hasCartesianSeries && !chart.polar) {
                while (i--) {
                    if (chart.series[i].options.dragDrop &&
                        isSeriesDraggable(chart.series[i])) {
                        return true;
                    }
                }
            }
        }
```

Which doesn't really make sense for the packed bubble charts since they don't sit on a visible axis.

Since the packed bubble chart allows drag and drop for points in the series (with the `dragBetweenSeries` option), I'd expect there to be a way to handle those events. Is there a specific configuration that I am missing?

#### Live demo with steps to reproduce
https://jsfiddle.net/ashleyhutton/gwvfe3co/13/

#### Product version
Highcharts 7.2.1

**Comment by pawelfus** [comment]
Hi @ashleyHutton 

Thanks for reporting this issue. This is bug in docs, `draggable-points` module is not compatible with packed bubble series and `dragDrop` options shouldn't be listed there. Demo without draggable-points still allows you to drag&drop bubbles: https://jsfiddle.net/BlackLabel/vd2th6zn/

Regarding events (`dragStart`, `drag` and `drop`) we can fire those in packed bubble too.

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/89yj7zdw/

Plugin:
```js
(function(H) {
  H.wrap(H.seriesTypes.packedbubble.prototype, 'onMouseDown', function(proceed, point, event) {
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    point.importEvents();
    H.fireEvent(point, 'dragStart');
  });
  H.wrap(H.seriesTypes.packedbubble.prototype, 'onMouseMove', function(proceed, point, event) {
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    if (point.fixedPosition && point.inDragMode) {
      H.fireEvent(point, 'drag');
    }
  });
  H.wrap(H.seriesTypes.packedbubble.prototype, 'onMouseUp', function(proceed, point, event) {
    if (point.fixedPosition && point.inDragMode) {
      H.fireEvent(point, 'drop');
    }
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));
  });
})(Highcharts);
```

**Comment by ashleyHutton** [comment]
@pawelfus thanks for the workaround!

Is there a way then to determine which bubble the point has been dropped into? I seem to only be able to get the bubble that the point originated in.

**Comment by pawelfus** [comment]
Yes, you can find which series has a new point, for example something like this:
```js
  H.wrap(H.seriesTypes.packedbubble.prototype, 'onMouseUp', function(proceed, point, event) {
    const lengths = this.series.map(s => s.points.length);
    let newSeries;

    if (point.fixedPosition && point.inDragMode) {
      H.fireEvent(point, 'drop');
    }
    proceed.apply(this, Array.prototype.slice.call(arguments, 1)); // bubble is moved here
    
    this.series.forEach((s, i) => {
      if (s.length > lengths[i]) {
        newSeries = s;
      }
    });

    console.log('point moved to: ', series);
  });
```

**Comment by mdabagh** [comment]
Hi
Please explain how I can record in the drop log what item was transferred from where to where?
console.log('item ' + event.point.name + ' from series ' + event.point.series.name + ' to series ' + event.series.name + ' moved.');

**Comment by bm64** [comment]
Hello @mdabagh 

Something like this can be achieved with [the workaround provided above ](https://github.com/highcharts/highcharts/issues/12495#issuecomment-558574424). Demo: https://jsfiddle.net/BlackLabel/zhu014rL/

**Comment by mdabagh** [comment]
Hi @bm64 
This piece of code got me working.
```
Highcharts.wrap(Highcharts.seriesTypes.packedbubble.prototype, 'onMouseUp', function (proceed, point, event) {
    const lengths = this.chart.series.map(s => s.points.length);
    let newSeries;
    const name = point.name;
    const oldSeries = point.series.name;

    if (point.fixedPosition && point.inDragMode) {
        Highcharts.fireEvent(point, 'drop');
    }

    proceed.apply(this, Array.prototype.slice.call(arguments, 1)); // bubble is moved here

    this.chart.series.forEach((s, i) => {
        if (s.points.length > lengths[i]) {
            newSeries = s;
        }
    });

    console.log(name);
    console.log('Point moved from: ', oldSeries);
    console.log('point moved to: ', newSeries.name);
});
```
