### ISSUE TITLE
Single tooltip with scrollable plot area

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/highcharts#12498]
#### Expected behaviour
The tooltip should position itself next to the hovered point.
Tooltip should also limit itself to the scrollable plot area.

#### Actual behaviour
When using scrollablePlotArea the tooltip is positioning itself incorrectly, and either the chart or the scrollable plot area is increased on interaction.

#### Live demo with steps to reproduce
Simplified: https://jsfiddle.net/highcharts/e9xrncdz/1/
OP: https://jsfiddle.net/jon_a_nygaard/8dszmk5t/

1. Hover the points
2. See that the tooltip is positioned wrongly, and that it can dissapear below the chart
3. See that the size of the chart or scrollable area is increased when the tooltip is dissapears below the chart.

#### Product version
Highcharts v7.2.1

**Comment by TorsteinHonsi** [comment]
The same issue applies to horizontal scrolling too: https://jsfiddle.net/highcharts/e9xrncdz/4/
.. And with line series, but a bit differently: https://jsfiddle.net/highcharts/e9xrncdz/6/

**Comment by TorsteinHonsi** [comment]
It's a regression since https://github.com/highcharts/highcharts/commit/7b9485b45873bffdec0da61db5e9adeac47165bd. This needs to be refactored in combination with #12416.
