### ISSUE TITLE
Heatmap big values are offscreened

### ISSUE THREAD

**Issue by brunoscopelliti** [highcharts/highcharts#12491]
#### Expected behaviour

All values are displayed correctly in heatmap.

#### Actual behaviour

When the value of a number is too big it gets translated off screen.

#### Live demo with steps to reproduce

[Demo](https://codepen.io/brunouber/pen/BaaeVXz)

Open the demo in a tab, you'll see that some cells are empty.

It is due to the fact that the cell gets applied a css transform that vertically translate it to -9999px. The function responsible for this is `Highcharts.SVGElement#updateTransform`.

#### Product version
Highcharts JS v7.2.1 (2019-10-31)
Highmaps JS v7.2.1 (2019-10-31)

#### Affected browser(s)

All.

**Comment by sebastianbochan** [comment]
Hi @brunoscopelliti,
Thank you for reporting about the problem. The reason of that is `datalabels.allowOverlap` option which is disabled by default. If you enable it all labels are displayed.

Docs:
- https://api.highcharts.com/class-reference/Highcharts.DataLabelsOptionsObject#allowOverlap

**Comment by brunoscopelliti** [comment]
I see, thank you.
