### ISSUE TITLE
Legend Navigation Scrolling Icons Without Text in IE/Edge

### ISSUE THREAD

**Issue by dscrimshaw** [highcharts/highcharts#12509]
#### Expected behaviour
When legend wraps and legend navigation appears, arrows should scroll the entire item in the row (icon + text/description), as it does with Chrome/Firefox

#### Actual behaviour
Only the icons scroll up, leaving the text of the legend items below impossible to see, and causing overlapping UI.

Seems to be caused by the 'useHTML' option of the legend configuration, which is necessary in our implementation.

#### Live demo with steps to reproduce
https://jsfiddle.net/denholms/v1n74qwr/14/

#### Product version
Highstock 6.0.3

#### Affected browser(s)
Microsoft Edge 42.17134.1.0
IE 11.950.17134.0

**Comment by pawelfus** [comment]
Hi @dscrimshaw 

Thanks for reporting the issue. This looks like a bug in old version, should be fixed in v7: https://jsfiddle.net/BlackLabel/5bwdy7q9/ - could you confirm?

**Comment by dscrimshaw** [comment]
@pawelfus Yes, it's fixed in the newest version. I presume upgrading is the only solution then?

Thanks,
Denholm

**Comment by pawelfus** [comment]
Alternatively you can check which version exactly has fixed this bug and find in changelog related ticket/PR then modify source code. I definitively recommend updating Highcharts though.

**Comment by dscrimshaw** [comment]
Alright, thanks for looking into it.
