### ISSUE TITLE
columnpyramid charts，label wrong when data is 0

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#12514]
#### Expected behaviour
show labels rightly
#### Actual behaviour
when data is 0,the datalabels show wrong
![QQ图片20191128162244](https://user-images.githubusercontent.com/6789138/69789345-5a706400-11fb-11ea-9076-d02c3ff1cfcc.png)

#### Live demo with steps to reproduce

https://jshare.com.cn/temp/INVbr7

**Comment by pawelfus** [comment]
Thanks for reporting this bug @wjhcc2018 

@sebastianbochan FYI
