### ISSUE TITLE
Reset button not showing when using scrollablePlotArea 

### ISSUE THREAD

**Issue by FilipeCosta06** [highcharts/highcharts#12517]
#### Expected behaviour
The Reset Zoom should show on the top right of the chart after a zoom.

#### Actual behaviour
Regardless of whether I use HighCharts or GanttCharts, if the `scrollablePlotArea.minWidth`value is big enough to cause the right end of the chart to appear off-screen, the Reset Zoom button won't show.

According to [this issue](https://github.com/highcharts/highcharts/issues/10466) (#10466), it was normal for the Reset Zoom Button to stick to the right end of the chart when zooming, even if that end is off-screen. Furthermore, this behaviour seemed to have been fixed https://github.com/highcharts/highcharts/commit/8e46848c4068ca5cb18073802c5da9cd64691244. 

Therefore, I suspect it to be a regression, but maybe I missed something.

From my observations, the `transform=translate(x,y)` seems to be computed based on the `minWidth` value and, as such, the absolute positioning isn't reachable since it isn't affected by the plot area being scrolled.

#### Live demo with steps to reproduce
Gantt demo
https://jsfiddle.net/1sto4fqg/1/

(make sure to edit the `minWidth` value if you happen to have a screen bigger than 3000 pixels, the value I set in this demo.

1. Zoom (xAxis) anywhere by clicking and dragging
2. Scroll horizontally (`Shift + scroll`, on Windows) to reach the right end of the chart
3. The Reset Zoom button isn't there 
(you can see it exists in the DOM tree by searching for the `highcharts-reset-zoom` class. The translate value for the button seems to `transform="translate(2896,112)"`).

Same thing happens in the first issue I mentioned (#10466)

#### Product version
HighCharts and Gantt v7.2.1 

#### Affected browser(s)
Chrome
Any ?

**Comment by FilipeCosta06** [comment]
I've also encountered similar issues with positioning when the plot area is scrolled because of `winWidth` (thought it might be related to #12498 since the problem seems to be because of `scrollablePlotArea`).

I am unable to reproduce it but, after scrolling to view tasks that were off-screen due to the `minWidth`, my tooltips are misplaced (kinda like the reset button here, if I scroll, the tasks move but the tooltip seems placed absolutely and relative to the `minWidth` value, not the actual "visible" plot area size

![image](https://user-images.githubusercontent.com/25252573/69794641-ee760780-11ca-11ea-8d66-fd27e5bb9ddd.png)

And a similar thing happens if I then try to move (after scrolling a bit): 
The "blue area", the one indicating where I'm trying to zoom, is misplaced.

_(I had to insert the mouse position in the screenshot, but I swear I'm not lying about their positioning)_
When scrolled all the way to the left (default, "normal", position), it behaves correctly...
![image](https://user-images.githubusercontent.com/25252573/69795138-e7032e00-11cb-11ea-9004-64bf27631648.png)

... but when scrolled to the right, the scroll "offset" is ignored by the zoom
![image](https://user-images.githubusercontent.com/25252573/69795443-81637180-11cc-11ea-86a8-ee5fc32441ca.png)

as if the computation uses my mouse position, relative to the screen (good), but forgets to add the current scroll offset (bad).

I happen to be using the draggable plugin in my main code (where the problems occur. I am unable to reproduce it in a JS Fiddle, for now) and override the drag/drop events but they aren't related to the Zoom events and I don't think that's the issue. Thought I'd mention it too.

**Comment by pawelfus** [comment]
Thanks for reporting @FilipeCosta06 

FYI @TorsteinHonsi

**Comment by nickwinger** [comment]
Hello, we also have this issue.
Actually this is a major issue and i think it should be resolvable in minutes...

**Comment by edouardreg** [comment]
Hello,

Same issue !
