### ISSUE TITLE
Venndiagram - Datalabel enabled-False is not working 

### ISSUE THREAD

**Issue by Surekaraja** [highcharts/highcharts#12511]
#### Expected behaviour
- Datalabel Enable false should disable the datalabel.

#### Actual behaviour
-  Datalabel Enable false is not disabling the datalabel.

#### Live demo with steps to reproduce
template: https://jsfiddle.net/q6k3n1ha/5/ 

#### Product version
 Highcharts  v7.2.1 

#### Affected browser(s)
- chrome

**Comment by pawelfus** [comment]
Hi @Surekaraja 

It's `dataLabels`, not `datalabels`, see fixed demo: https://jsfiddle.net/BlackLabel/yhxLrkc8/
