### ISSUE TITLE
Can't update 3D pie depth

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#12515]
#### Expected behaviour

can't update 3d pie depth properties after chart created , both `series.update` and `chart.update`  has no affect.

#### Live demo with steps to reproduce
https://jsfiddle.net/x1843zvm/

#### Product version
7.2.1

**Comment by pawelfus** [comment]
Thanks for reporting this bug @zhy1stgg 

Bisected to commit af24cb21a1
