### ISSUE TITLE
[Typescript]`tooltipFooterHeaderFormatter` property is not known for Tooltip 

### ISSUE THREAD

**Issue by sprengerjo** [highcharts/highcharts#12516]
**Expected behaviour**

I can accessTooltip.tooltipFooterHeaderFormatter

**Actual behaviour**

In Highcharts v7.1.0. tsc raises an error: TS2339: Property `tooltipFooterHeaderFormatter` does not exist on Tooltip.

**Live demo with steps to reproduce**
n/a

**Product version**
Highcharts v7.2.0.

**Affected browser(s)**
n/a

**Comment by pawelfus** [comment]
Hi @sprengerjo 

Thanks for reporting. Why do you need `tooltipFooterHeaderFormatter` method? It's our internal method, not a public one and should not be available in TS.

You can add your own definition to this method: https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-beta#extending-highcharts-in-typescript

**Comment by bre1470** [comment]
Well, I am curious about the reason behind the request. The `tooltip.pointFormatter` option should cover all needs in combination with `tooltip.footerFormat` option and `tooltip.headerFormat` option.

**Comment by sprengerjo** [comment]
Thx for the quick response!

I replaced our usage of the private method with `tooltip.pointFormatter`.
