### ISSUE TITLE
New Functionality: Chart per point

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#12526]
The main idea of this functionality is to give more support for adding statistical series inside the graph, just like current mappie series works with map areas.
![Screenshot 2019-11-28 at 10 59 58](https://user-images.githubusercontent.com/15050812/69796403-482c0100-11ce-11ea-9f8c-ccf7048ba396.png)

**Comment by KacperMadej** [comment]
> a further activity occurs <

**Comment by KacperMadej** [comment]
a further activity occurs
