### ISSUE TITLE
New Functionality: Drilldown go-to-level + breadcrumbs

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#12528]
Adding go-to-level functionality for drilldown to specific level. Additionally, create breadcrumbs in drilldown module.

**Comment by bbrudnoy** [comment]
Presumably this will introduce breadcrumbs in treemap charts. Certainly thumbs up. This a desired feature in my company.

**Comment by karolkolodziej** [comment]
The breadcrumbs functionality introduced here: https://github.com/highcharts/highcharts/pull/15767
