### ISSUE TITLE
New Series Type: Partial Fill

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#12529]
Implementing ~~Partial Fill~~ Pictorial series.

Internal Note: There is already a study on a Partial fill series available inside **studies** folder. We should be able to continue the work based on current state.

**Comment by pawelfus** [comment]
Ref: [Study](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/studies/pictorial/)

**Comment by karolkolodziej** [comment]
Introduced by: https://github.com/highcharts/highcharts/pull/16923
