### ISSUE TITLE
Sankey chart - Multiple series overlapping

### ISSUE THREAD

**Issue by JustinDraude** [highcharts/highcharts#12533]
#### Expected behaviour
When multiple series are added, I expected the chart to be drawn in a way the series don't overlap. As when all data is in one series object, difference being with them in separate series objects, you can disable them individually by legend.

#### Actual behaviour
Series overlap, with the last series in the stack being accessible by hover.

#### Live demo with steps to reproduce
https://jsfiddle.net/ntjafd0e/

#### Product version
Highcharts 7.2.1

![sankeyIssue](https://user-images.githubusercontent.com/13571647/69855312-f0f06400-1293-11ea-9650-095517b78840.PNG)

**Comment by pawelfus** [comment]
Thanks for reporting @JustinDraude 

At this moment, only one Sankey series per chart is supported.

**Comment by JustinDraude** [comment]
Fair enough!
