### ISSUE TITLE
Make a sunburst point/ section in sunburst chart slice out on mouse hover

### ISSUE THREAD

**Issue by edoteee** [highcharts/highcharts#12536]
As we can set the `sliced` option in sunburst chart as mentioned [here](https://github.com/highcharts/highcharts/issues/7390)
Is it possible to make a sunburst point/ section in sunburst chart slice out on mouse hover ?

**Comment by pawelfus** [comment]
Hi @edoteee 

Thanks for using Highcharts. Note that you posted on our **bug tracker**. When you have a question, please contact our [support](https://www.highcharts.com/blog/support/) team.

PS: Consider using `point.update({ sliced: true/false });`.

**Comment by edoteee** [comment]
This works, thank you @pawelfus
