### ISSUE TITLE
Live highstocks OHLCV data series disapear

### ISSUE THREAD

**Issue by hagilani** [highcharts/highcharts#12535]
Hi sir,
I want to create a 1 second live data with OHLCV. Data fetche  from server and show on the chart, but after five or six candles, first data disapears. I couldn't find a way to show all data added to chart.

I'm using this code to add to series :
`
  $(document).ready(function () {
      $(function () {
        Highcharts.setOptions({
          global: {
            useUTC: false
          }
        });

        var graph = new Highcharts.stockChart({
          title: { text: 'Real Time OHLCV' },
          chart: {
            height: 700
          },
          rangeSelector: {
            selected: 1
          },
          yAxis: [{
 
            gridLineDashStyle: 'Dot',
            labels: {
              align: 'right',
              x: -3
            },
            title: {
              text: 'OHLC'
            },
            height: '70%',
            lineWidth: 2,
            resize: {
              enabled: true
            },
            ordinal: false,
            showLastLabel: true,
          }, {
            labels: {
              align: 'right',
              x: -3
            },
            title: {
              text: 'Volume'
            },
            top: '65%',
            height: '35%',
            offset: 0,
            lineWidth: 2,
            ordinal: false
          }],

          tooltip: {
            shape: 'square',
            headerShape: 'callout',
            borderWidth: 0,
            shadow: false,
          },
          chart: {
            type: 'candlestick',
            renderTo: 'graph_container',
            events: {
              load: function () {
 

                var seriesOhlc = this.series[0];
                var seriesVol = this.series[1], chart = this;
                var isNew = true;
                var socket = io.connect('http://localhost:3000');
                socket.on('chart_data', function (data) {
                  //add chart data to series

                  var ohlc_temp = [];
                  var volume_temp = [];

                  console.log(data.results);
                  var obj = data.results;
                  // $.each(data.results, function (k, obj) { 

                  //var last = seriesOhlc.data[seriesOhlc.data.length - 1];
                  // var lastx = seriesVol.data[seriesVol.data.length - 1];

                  seriesOhlc.addPoint([
                    obj.date, // the date
                    parseFloat(obj.open), // open
                    parseFloat(obj.high), // high
                    parseFloat(obj.low), // low
                    parseFloat(obj.close),// close 
                  ], true, true);
                  seriesVol.addPoint([
                    obj.date, // the date
                    parseFloat(obj.volume)// the volume
                  ], true, true);
  

                });

              }
            }
          },

          plotOptions: {
            series: {
              dataGrouping: {
                units: groupingUnits
              }
            }
          },
          rangeSelector: {
            buttons: [{
              count: 60,
              type: 'minute',
              text: '1M'
            }, {
              count: 300,
              type: 'minute',
              text: '5M'
            }, {
              count: 3600,
              type: 'Hour',
              text: '1H'
            }, {
              count: 14400,
              type: 'Hour',
              text: '1H'
            }, {
              type: 'all',
              text: 'All'
            }],
            inputEnabled: false,
            selected: 0
          },

          series: [{
            type: 'candlestick',
            id: 'dataBitmex',
            name: 'dataBitmex',
            data: ohlc, 
            dataGrouping: {
              enabled: false
            }
          }, {
            type: 'column',
            name: 'Volume',
            yAxis: 1,
            data: volume, 
            dataGrouping: {
              enabled: false
            }
          }],
          responsive: {
            rules: [{
              condition: {
                maxWidth: 2800
              },
              chartOptions: {
                rangeSelector: {
                  inputEnabled: false
                }
              }
            }]
          }
        });

      });
    });

`
 
Could you please help me to resolve this problem?

**Comment by sebastianbochan** [comment]
Hi @hagilani,
The github is our bug tracker so for general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

**Comment by pawelfus** [comment]
PS: Consider setting [`addPoint(options, redraw=true, shift=false)`](https://api.highcharts.com/class-reference/Highcharts.Series#addPoint).

**Comment by hagilani** [comment]
@pawelfus  Thanks for your help bro
