### ISSUE TITLE
Can't set relative width

### ISSUE THREAD

**Issue by bvinicius** [highcharts/highcharts#12540]
Hello,

I'm using angular-2-highcharts in my Angular application, and i'm trying to set the chart's width relative to it's parent div. In `Highcharts.chart`, i set `height: '100%'`, and it works fine. However, when I do the same thing using `width`, it returns me some kind of NaN error. 

How could I proceed?

**Comment by KacperMadej** [comment]
Hi @bvinicius 

Thank you for reporting the problem.

This looks like a problem that should be resolved through technical support and not a bug report that could stay on this GitHub repository issues list.

Please create a live demo of the problem and contact technical support.
The problem you have might be related to a dynamically created DOM elements that are not having accessible size at the time you are creating the chart or simply by not having a higher container that has a defined width (so it's not possible to determinate what is the `100%` based on). Hard to be sure without a live demo.

Additionally, the wrapper `angular2-highcharts` is a community made / 3rd-party wrapper, so we have limited options to support it and resolve problems with it. 

The official wrapper is [highcharts-angular](https://github.com/highcharts/highcharts-angular) and our [technical support is here](https://www.highcharts.com/blog/support/).

**Comment by bvinicius** [comment]
Alright! Didn't know there was a official wrapper. Thank you
