### ISSUE TITLE
3dscatter points are not displayed when the first one has z=null

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#12548]
Setup: 3dscatter chart, with ``        data: [
			[50,50, null],
            [15, 35, 50],
            [10, 20, 30],
        ]``
#### Expected behaviour
All three points are displayed (null is counted as 0)
OR
The first point is not displayed, but other points are
#### Actual behaviour
No points are displayed

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/kgv6rd1a/

The problem occurs only in a situation when the first point of data have z = null. Surprisingly if that point is not the first point in data, all three points are displayed correctly. In any other situation, the point, where one of the coordinates(x or y) is null, the point is not displayed but it doesn't affect the behavior of other points.

#### Related forum post
https://www.highcharts.com/forum/viewtopic.php?f=9&t=42737&start=15

#### Product version
Highcharts JS v7.2.1 (2019-10-31)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
*Internal note:*
`undefined` is fine: https://jsfiddle.net/BlackLabel/kgv6rd1a/5/ (rendered as z=0)
Related ticket: #4507
