### ISSUE TITLE
Wrong extremes for bubble series when xAxis.max is set

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#12543]
#### Expected behavior
Extremes should be set correctly.

#### Actual behaviour
Extremes are set incorrectly.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/z1kb3v98/

1) decrease the xAxis.max value using the input field
2) when the max value is lower than 2053 bubbles disappear

#### Product version
Highcharts

**Comment by pawelfus** [comment]
*Internal note:*
Most probably connected to `Axis.beforePadding` method, when disabled extremes are correct: https://jsfiddle.net/BlackLabel/z1kb3v98/6/ (ignore missing bubbles, their radii are not calculated when `beforePadding` is disabled/removed).
