### ISSUE TITLE
Inverted not working on live chart

### ISSUE THREAD

**Issue by laurenceschellevisch** [highcharts/highcharts#12556]
#### Expected behaviour
The Y axis is supposed to invert with the X axis on the option inverted: false/true

#### Actual behaviour
Doesnt work with live charts

#### Live demo with steps to reproduce
https://jsfiddle.net/ascnhf12/10/
put the inverted option to true and false.

#### Product version
Highcharts,  Latest version

#### Affected browser(s)
Firefox, Chrome

**Comment by pawelfus** [comment]
Hi @laurenceschellevisch 

I assume you realized that `bar` series type forces `inverted` option. Use `column` + `inverted` instead: https://jsfiddle.net/BlackLabel/nf2wzsbj/

**Comment by laurenceschellevisch** [comment]
> 
> 
> Hi @laurenceschellevisch
> 
> I assume you realized that `bar` series type forces `inverted` option. Use `column` + `inverted` instead: https://jsfiddle.net/BlackLabel/nf2wzsbj/

yes i fixed it already `column` option works thanks
