### ISSUE TITLE
Divergent chart possible with Highcharts?

### ISSUE THREAD

**Issue by solancer** [highcharts/highcharts#12555]
Does highcharts have an option to have a multi Y axis diverged like in the below attached screenshot?

P.S Any other option apart having two highchart types of charts, and rendering them next to each other.

<img width="785" alt="Screenshot 2019-12-04 at 3 22 02 pm" src="https://user-images.githubusercontent.com/800668/70132554-7a47d200-16aa-11ea-820a-b8ec9382de69.png">

**Comment by pawelfus** [comment]
Hi @solancer 

You posted on our **bug tracker** - in case you have a question, please use other [support channels](https://www.highcharts.com/blog/support/).

PS: Yes, it's possible, simple demo: https://jsfiddle.net/BlackLabel/6rfb7jmz/

**Comment by solancer** [comment]
@pawelfus thank you for the swift reply, apologies for posting this in bug tracker :) btw is their a gitter.im channel for highcharts?

**Comment by solancer** [comment]
@pawelfus thank you for the swift reply, apologies for posting this in bug tracker :) btw is there a gitter.im channel for highcharts?

**Comment by pawelfus** [comment]
No, we don't have such channel
