### ISSUE TITLE
Cannot download PDF due to content security policy issue

### ISSUE THREAD

**Issue by crazyUI** [highcharts/highcharts#12553]
Error - Refused to load the script 'https://code.highcharts.com/6.0.7/lib/jspdf.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Hi,

I am getting this error when using 'exportChartLocal' method to download multiple charts in PDF format.  Can you please suggest how to fix this issue. Is there a meta tag that could be included in the html file to avoid this security issue?

Thank you!

#### Product version
6.0.7

#### Affected browser(s)
chrome

**Comment by crazyUI** [comment]
If I override the 'exportChartLocal' method like this fiddle example,
http://jsfiddle.net/2578sz52/

I am getting the error -
Uncaught TypeError: Cannot read property 'baseVal' of undefined
    at u (offline-exporting.js:13)
    at l (offline-exporting.js:14)

**Comment by sebastianbochan** [comment]
Hi @crazyUI,
Thank you for reporting about the problem.

It looks like similar to the issue: https://github.com/highcharts/highcharts/issues/7697

Have you tried to update your files to the newest (7.x.x) ?

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
This sounds to me like the page is trying to load the script from our CDN, while your code explicitly sets CSP to disallow that. You could try hosting the `jsPDF` library from your own server, and set the https://api.highcharts.com/highcharts/exporting.libURL option to point Highcharts to the right location. Note that you might also have to host `CanVG`, `RGBColor` and `svg2pdf`. These are all available on our CDN (e.g. https://code.highcharts.com/6.0.7/lib/canvg.js)

**Comment by crazyUI** [comment]
Thanks for your response. If I install the dependencies jsPDF and svg2pdf , then I need to still give the node_modules path in the exporting.libURL.  I also saw the file names in the installation have 'min' in it. Instead can I copy the dependencies from the URL 'https://code.highcharts.com/6.0.7/lib/jspdf.js' and place them in directory in codebase. If I give this path to 'libURL' it works. But is this valid approach. Please advise.  In future, if we upgrade highcharts library, do we need to change these dependencies as well. Thanks for your support.

**Comment by oysteinmoseng** [comment]
@crazyUI 
The path of `libURL` should reflect the path to the files when your application is running/online. Highcharts will then load these files on demand as they are needed. If this is not possible you can also manually load these files whenever you load Highcharts, as long as they are always loaded when Highcharts runs.

You can absolutely copy the dependencies from https://code.highcharts.com/6.0.7/lib/jspdf.js directly. It is recommended to update these when you update Highcharts, but generally not necessary unless there are relevant bugs that are fixed. These are 3rd party libraries, and not maintained by us.

I am closing this issue as not a bug for now. Should you require any further assistance with the issue, please contact our [support team](https://support.highcharts.com/support/home).

**Comment by crazyUI** [comment]
Thanks @oysteinmoseng for your response. If I install these package and then import them, highcharts is not picking them up. Only way to not make highcharts go the code.highcharts.com and pick up from node_modules is to specify the libURL?  In that case, how can I give two links in the libURL..one for svg2pdf and one for jspdf.

**Comment by oysteinmoseng** [comment]
@crazyUI `libURL` should point to the directory where all of the dependencies are located, both `svg2pdf` and `jspdf`
