### ISSUE TITLE
Graph navigation ignores multiple data series

### ISSUE THREAD

**Issue by janitza-pawe** [highcharts/highcharts#12578]
#### Expected behaviour
The graph navigation shows and navigates multiple data series at once.
It is possible to slide both navigation bars in order to inspect multiple data series without having the graph to loose it's focus.

#### Actual behaviour
If you have multiple series the Highstocks navigation shows only the x-axis range of the first series. When you try to move the right handle of the navigation and move it to the left the chart jumps into the end of the first series. You cannot navigate through the second series with the navigation handles.

#### Live demo with steps to reproduce
Loading of the jsfiddle is quite slow as there are lots of data points.

URL to jsfiddle for reproduction: https://jsfiddle.net/oliverbohnes/zj2dw4by/9/

#### Product version
"highcharts": "^7.2.1",
"highcharts-react-official": "^2.2.2",

#### Affected browser(s)
Chrome, Edge, Firefox

**Comment by pawelfus** [comment]
Hi @janitza-pawe 

Thanks choosing Highstock!

You can control this by setting [`series.showInNavigator`](https://api.highcharts.com/highstock/series.line.showInNavigator) option: https://jsfiddle.net/BlackLabel/fuLt2w31/1/
