### ISSUE TITLE
Highstock without scroll navigator jumps

### ISSUE THREAD

**Issue by Lukasz196** [highcharts/highcharts#12573]
#### Expected behaviour
After moving selected timerange navigator should scale with chart chart. Longer labels after moving makes chart smaller and then navigator not scales correctly.

#### Actual behaviour

I have weird problem with histock chart with data containing big value diferences. When i move selected area in navigator from small values area to big values area with disabled scroll, navigator not scales correctly. Howto solve this problem? I want chart with no animation and scroll.

#### Live demo with steps to reproduce
Steps to reproduce:

1. Set range in area marked with (1)
2. Move selected range to area marked with (2). Long labels from chart makes chart and navigator smaller but one container in navigator (3) not scalling like rest.
3. Move selected range to other place in area (2). In this moment when left mouse button is down and move selected range a litle navigator is scaling and selected range is moving and line (3) scales correctly.

http://jsfiddle.net/ch38kj15/4/

![image](https://user-images.githubusercontent.com/13440319/70211269-f686f780-1734-11ea-8e93-47bb3eb4dd02.png)
![image](https://user-images.githubusercontent.com/13440319/70211281-ff77c900-1734-11ea-9f4a-725b5244c99b.png)
![image](https://user-images.githubusercontent.com/13440319/70211297-07d00400-1735-11ea-92d1-661fa09f42a1.png)

#### Product version
 Highstock 7.2.1

#### Affected browser(s)
Chrome, Firefox

**Comment by pawelfus** [comment]
Thanks for reporting this issue @Lukasz196 

**Workaround:**
Render labels inside the plotting area: https://jsfiddle.net/BlackLabel/ev3L1r7z/

*Internal note:*
It's probably order of: rendering navigator and yAxis title.
