### ISSUE TITLE
Wrong type for SeriesPieDataLabelsOptionsObject.distance

### ISSUE THREAD

**Issue by trygveaa** [highcharts/highcharts#12575]
#### Expected behaviour

The type for `distance` in `SeriesPieDataLabelsOptionsObject` should include string. The [documentation](https://api.highcharts.com/class-reference/Highcharts.SeriesPieDataLabelsOptionsObject#distance) states:

> Can also be defined as a percentage of pie's radius.

And when I try to define it as e.g. `-50%` it works fine, but I get a type error.

#### Actual behaviour

The type is defined as `number` which doesn't allow percentage strings.

#### Live demo with steps to reproduce

There wasn't typescript support in the template, but this would give an error: https://jsfiddle.net/7y6gfsoh/

#### Product version

Highcharts 7.2.1

#### Affected browser(s)

Not applicable

**Comment by pawelfus** [comment]
Thanks for reporting @trygveaa 

FYI @bre1470
