### ISSUE TITLE
Incomplete display of the first yAxis label.

### ISSUE THREAD

**Issue by perry14** [highcharts/highcharts#12572]
#### Expected behaviour
Display Complete yAxis labels.

#### Actual behaviour
Incomplete display of the first yAxis label.

#### Live demo with steps to reproduce
https://jsfiddle.net/p3rry14/x632dnm0/2/
![HighChartsDemo](https://user-images.githubusercontent.com/1539151/70202106-93588d80-1753-11ea-940d-16682d48dfb2.png)

#### Product version
Highcharts 7.2.0

#### Affected browser(s)
Chrome, Safari, Firefox

**Comment by sebastianbochan** [comment]
Hi @perry14,
The reason of the problem is using negative `labels.y`, which moves labels to place which does not exists (top spacing).

The solution is increase spacingTop param.

Demo:
- https://jsfiddle.net/BlackLabel/r1uog2fL/

**Comment by perry14** [comment]
Hi @sebastianbochan,
Thank you very much.
The spacingTop param solved my problem
