### ISSUE TITLE
Common H.merge of arrays with `Array[0].id` match

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#12581]
#### Expected behaviour

There should be a common merge functionality for arrays, that works similar to series merge and exporting. It should make use of the `id` property for each array item to determinate, which items remain in the array and get merged with the new item properties.

#### Actual behaviour

Only special handling for merging arrays like for series array exists, which prevents broader usage of option arrays like in `defs` options for example.

**Comment by TorsteinHonsi** [comment]
This should probably be refactored out from [this code block](https://github.com/highcharts/highcharts/blob/v8.0.4/ts/parts/Dynamics.ts/#L785-L860) inside `chart.update`, where the described functionality currently applies when updating series, axes, and panes.

The same logic could apply to collections of `dataLabels`.

**Comment by bre1470** [comment]
There is too much chart/item specific code. I do not believe that this can be refactored: https://github.com/highcharts/highcharts/blob/master/ts/parts/Dynamics.ts#L831-L837
