### ISSUE TITLE
Pie chart resizes incorrectly when size option is greater than 100%

### ISSUE THREAD

**Issue by amlehman** [highcharts/highcharts#12582]
#### Expected behaviour
Pie chart would fit inside its container when resized regardless of the option passed to size

#### Actual behaviour
The sides of the chart are clipped when resized down to smaller size when using providing a value greater than 100% to the size option

![Screenshot from 2019-12-05 15-24-03](https://user-images.githubusercontent.com/4624053/70275252-63b97d80-1773-11ea-9ccf-85666890a4b3.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/alehman/nvLzsxd9/

#### Product version
Highcharts 7.2.1

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting @amlehman 

## Workaround
Demo: https://jsfiddle.net/BlackLabel/jLhz4obm/

Snippet:
```js
(function(H) {
  H.wrap(
    H.seriesTypes.pie.prototype,
    'getCenter',
    function(proceed) {
      const chart = this.chart;

      let positions = proceed.call(this);

      positions[2] = Math.min(chart.plotWidth, chart.plotHeight, positions[2]);
      positions[3] = Math.min(chart.plotWidth - 5, chart.plotHeight - 5, positions[3]);

      return positions;
    }
  );
})(Highcharts);
```
