### ISSUE TITLE
Chart reflow not working with multiple y axis with top defined.

### ISSUE THREAD

**Issue by maddy25** [highcharts/highcharts#12590]
#### Expected behaviour
When changing height of chart using chart.setSize() and calling chart.reflow after that, the graph should be readjusted to be in the container. 

#### Actual behaviour
With highcharts having multiple Y axis and one of the axis having "top" defined:
1. Removing the 1st graph
2. Reduce the height using setSize()
3. Call chart.reflow()
4.Bottom graph gets cropped.

#### Live demo with steps to reproduce
http://jsfiddle.net/p6w4xjtf/2/
Add axis and then click the remove axis button

#### Product version

6.2

#### Affected browser(s)
Tested in chrome

**Comment by maddy25** [comment]
http://jsfiddle.net/p6w4xjtf/2/ this is the right jsfiddle link

**Comment by pawelfus** [comment]
Hi @maddy25 

Thanks for reporting the issue! Honestly, I have no idea how the chart should behave in this case. yAxis config is missing some pieces (e.g. height?). I have added border to the chart so we can see what happens: http://jsfiddle.net/BlackLabel/k9j5nr4o/ - and this is what I would expect to render with your config.. Could you elaborate the issue? Thanks!

**Comment by maddy25** [comment]
Hello @pawelfus 
I was thinking chart.reflow() should be able to adjust the chart inside the container such that it doesn't crop.
http://jsfiddle.net/f6oxp8y5/1/
Here the container height: 750 px,
1st graph height: 200 px
2nd graph after adding axis : height: 200, top: 150
Now removing the 1st graph axis, reducing the height by 150 but the second graph gets cropped. Is this the expectation or chart.reflow should be able to adjust the so that graph doesn't get cropped.

**Comment by maddy25** [comment]
I guess i will have to adjust the "top" for charts. How do I programtically update the top of for an axis ?

**Comment by pawelfus** [comment]
In general, I recommend to use percentage values (`height: 'x%')` instead of pixels (`height: x`). For example like this: http://jsfiddle.net/BlackLabel/c7L1wz8o/ - then yAxis will adapt to the available space (100% = plot size). 

To be on the same page:
Height (or width) of an axis does not increase chart's size.
`chart.reflow()` does not increase size of the container, only resizes chart to fit the container.

> How do I programtically update the top of for an axis ?

Use `chart.yAxis[0].update({ top });`

**Comment by maddy25** [comment]
Thanks, I am programatically updating the top for chart to fit in the container.
I was not looking for increase of container size but to adjust top. I guess that is not possible with chart.reflow
Also I see in docs that chart.flow() only works for width

**Comment by pawelfus** [comment]
Ok, then to adjust `yAxis.top` you should call `yAxis.update({ top });`.

Should I close the issue?

**Comment by maddy25** [comment]
Yes please. Thank you.
