### ISSUE TITLE
X values are wrong when updating two series simultaneously

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#1259]
Demo: http://jsfiddle.net/highcharts/Mdwf3/

Click the Add button to add one point at a given x value at the end of the series.

Result: Every other time the button is clicked, the new point is drawn on the same X as the previous.
Expected: That the given X be respected.

**Comment by oysteinmoseng** [comment]
Closing this for now, feel free to reopen if we want to reconsider this as a bug.
