### ISSUE TITLE
v7.2.1 Sparkline tooltip regression is back

### ISSUE THREAD

**Issue by bhagwat** [highcharts/highcharts#12606]
#### Expected behaviour
Expecting to see the tooltip appear when hovering over the sparkline. Seems the regression is back as the same was reported and closed for v5.0.0 here: #5745 and here: #5820

<img width="218" alt="expected-behaviour" src="https://user-images.githubusercontent.com/109787/70601689-a4ecda00-1c18-11ea-87d8-46239d378905.png">

#### Actual behaviour
Tooltip should not be clipped:
<img width="205" alt="actual-behaviour" src="https://user-images.githubusercontent.com/109787/70601674-9b637200-1c18-11ea-9a74-e88621274c4c.png">

#### Live demo with steps to reproduce
Hover over sparkline chart to see the clipped tooltip:
http://jsfiddle.net/bhagwat/t4wndr82/

#### Product version
Highcharts 7.2.1

#### Affected browser(s)
Chrome
Firefox
Safari

**Comment by pawelfus** [comment]
Thanks for reporting @bhagwat 

**Simplified demo:**
http://jsfiddle.net/BlackLabel/ryc3atwz/

**Workaround:**
Use `tooltip.outside`: http://jsfiddle.net/BlackLabel/b109o6qp/

*Internal note:*
Bisected to commit 02b559d0de

**Comment by pawelfus** [comment]
*Internal note:*
Set in demo `tooltip.outside`. This option should be encouraged for small charts in general.
