### ISSUE TITLE
Inconsistent quoting in the API docs

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#12613]
#### Expected behaviour
Strings be quoted. Numbers, booleans, null, undefined - not.

#### Actual behaviour
Randomly added quotes

![Skjermbilde 2019-12-11 kl  13 06 32](https://user-images.githubusercontent.com/227836/70620476-b08bd100-1c17-11ea-9337-239e5386bba7.png)
https://api.highcharts.com/highcharts/chart.panning

**Comment by TorsteinHonsi** [comment]
@bre1470 FYI

**Comment by bre1470** [comment]
Solved with https://github.com/highcharts/highcharts-documentation-generators/commit/259754ed001456571055d0b59a8c0effe1ef5d4c (v0.5.5)

**Comment by bre1470** [comment]
It has been solved with the API documentation for version 8.0.1.
