### ISSUE TITLE
Empty pie chart animation is not configurable

### ISSUE THREAD

**Issue by laurent-h** [highcharts/highcharts#12619]
#### Expected behaviour
Animation should be configurable on empty pie chart.

#### Actual behaviour
Unable to disable animation on empty pie chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/nfb3wh18/

#### Product version
Highcharts 8.0.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting this bug @laurent-h 

*Internal note:*
Probable `series.animation` option is not passed on to `animate()` method in `drawEmpty` method.
