### ISSUE TITLE
Pie chart legend labels overlapping on drilldown

### ISSUE THREAD

**Issue by briandick** [highcharts/highcharts#12627]
#### Expected behaviour
Labels should not overlap

#### Actual behaviour
Labels overlap when clicking on a pie section to drilldown

#### Live demo with steps to reproduce
https://jsfiddle.net/en0qrkt9/

#### Product version
Highcharts 8.0.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting this bug @briandick 

*Internal note:*
Bisected to commit b05785120e

**Comment by ppotaczek** [comment]
To workaround add this plugin:

    (function(H) {
        H.wrap(H.Point.prototype, 'destroy', function(proceed) {
            if (this.legendItem) { // pies have legend items
                this.series.chart.legend.destroyItem(this);
            }
            proceed.apply(this, Array.prototype.slice.call(arguments, 1));
        });
    }(Highcharts));

**Live example:** https://jsfiddle.net/BlackLabel/2hgptm9q/

**Comment by jjzjx118** [comment]
> To workaround add this plugin:
> 
> ```
> (function(H) {
>     H.wrap(H.Point.prototype, 'destroy', function(proceed) {
>         if (this.legendItem) { // pies have legend items
>             this.series.chart.legend.destroyItem(this);
>         }
>         proceed.apply(this, Array.prototype.slice.call(arguments, 1));
>     });
> }(Highcharts));
> ```
> 
> **Live example:** https://jsfiddle.net/BlackLabel/2hgptm9q/

it works, but will this bug be fixed in the future？

**Comment by pawelfus** [comment]
Hi @jjzjx118 - bug is already fixed and should be part of the next release.
