### ISSUE TITLE
Uncaught error when updating a series data after setting null data

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#12620]
#### Expected behaviour
Update a series with new data, or at least error when you set `null` data.

#### Actual behaviour
After setting `null` data without any problem, an uncaught error happens when updating with valid data.

#### Live demo with steps to reproduce
https://jsfiddle.net/vqf2r5au/

Steps:
- Just open the fiddle and wait 2 seconds for the timers to run.

I guess that it should return "invalid data" with a nice Highcharts error (the one with the link and error number) when you try to set `null` data. If `null` is an accepted data value, then it should not crash when you update with a valid data value later.

#### Product version
Latest Highcharts

#### Affected browser(s)
Chrome Win7

**Comment by sebastianbochan** [comment]
Hi @Llorx,
Im not sure if we should consider it as a bug, because the type of data is array. As a result if you need to reset points, set an empty array like: `data: []`.

@TorsteinHonsi  @pawelfus what do you think?

**Comment by pawelfus** [comment]
Not sure either, as you said, `data` should be an array. From the other hand, it would be nice to get rid of that error in console.

**Comment by Llorx** [comment]
Yeah, more than a bug, I think is an inconsistency. It was a bit hard to determine why we are getting an error with valid data, and the reason was that we were setting a `null` data before. Maybe throw an error when `null` data is set, just like when you set invalid data, or maybe allow receiving valid data after a `null` data was set, or something like that.

I know now the problem, but maybe in the future there's another person like me, not knowing why crashes with valid data.
