### ISSUE TITLE
Flags are not visible in some cases, likely a bug

### ISSUE THREAD

**Issue by DangoDaikazoku** [highcharts/highcharts#12625]
#### Expected behaviour

All the flags should be visible.

#### Actual behaviour

Flags are not visible on higher zoom level and after a point in x axis.

#### Live demo with steps to reproduce

https://jsfiddle.net/dango_x_daikazoku/uoszwrya/24/

To reproduce try zooming in and out and sliding through x-axis.

I have commented the flag series data key, it is reproducible with any of the commented versions.

#### Product version

Tested on 

Highstock JS v8.0.0 
Highstock JS v7.0.0 

#### Affected browser(s)

Google chrome Version 78.0.3904.108 (Official Build) (64-bit)
Firefox 70.0.1 (64-bit)

**Comment by DangoDaikazoku** [comment]
Also seen here https://www.highcharts.com/forum/viewtopic.php?t=41294

**Comment by DangoDaikazoku** [comment]
`
            boxes.some(function (box) {
                var posInCompositeBox = 0;

                if (box.targets.some(function () {
                    origBoxes[i].pos = box.pos + posInCompositeBox;

                    // If the distance between the position and the target exceeds
                    // maxDistance, abort the loop and decrease the length in increments
                    // of 10% to recursively reduce the  number of visible boxes by
                    // rank. Once all boxes are within the maxDistance, we're good.
                    if (
                        Math.abs(origBoxes[i].pos - origBoxes[i].target) >
                        maxDistance
                    ) {
                        // Reset the positions that are already set
                        origBoxes.slice(0, i + 1).forEach(function (box) {
                        console.log('deleted box pos', box, box.pos)
                        // delete box.pos;
                        });

                        // Try with a smaller length
                        origBoxes.reducedLen =
                            (origBoxes.reducedLen || len) - (len * 0.1);

                        // Recurse
                        if (origBoxes.reducedLen > len * 0.1) {
                            H.distribute(origBoxes, len, maxDistance);
                        }

                        // Exceeded maxDistance => abort
                        return true;
                    }

                    posInCompositeBox += origBoxes[i].size;
                    i++;

                })) {
                    // Exceeded maxDistance => abort
                    return true;
                }
            });
`
in https://github.com/highcharts/highcharts/blob/5b7fca922453428858b6b09de05f395bfaddc09f/js/parts/DataLabels.js#L97 is at fault. Rank is never defined for the boxes and it just trims from the end.

**Comment by pawelfus** [comment]
Thanks for reporting this @DangoDaikazoku 

This is already reported in #10073 - I'm closing this ticket as a duplicate.
