### ISSUE TITLE
Urgent: Exporting Same Timestamp Cause CSV formatting Issue

### ISSUE THREAD

**Issue by hartbert95** [highcharts/highcharts#12628]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/40552612/70762772-d686b200-1d8c-11ea-9901-9a21d9522172.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/40552612/70763151-0c786600-1d8e-11ea-801c-ef240bbe9ff1.png)

#### Live demo with steps to reproduce
When there is the same datetime, the value should not go down for a new line when export.

#### Product version
Highchart 7.0.3

(Customize export-data.js File)
[export.txt](https://github.com/highcharts/highcharts/files/3958600/export.txt)

**Comment by pawelfus** [comment]
Could you recreate issue in jsFiddle? We will check this, thanks!

**Comment by hartbert95** [comment]
Hi @pawelfus , Sorry for late replies, here is the reproduced jsfiddle but in stackbliz 
https://stackblitz.com/edit/highchart-angular-chart-beehfn

**Comment by KacperMadej** [comment]
Looks like a general issue with export-data module. When multiple series have different data sets then some categories are not merged together correctly.

Demo: https://jsfiddle.net/BlackLabel/15rft7hs/

2nd category should have 2 entries because both series have 2 points with that x index and yet there are 3 rows of data.

**Comment by hartbert95** [comment]
Hi, Thanks for clarify, so is there any workaround or ETA time for the fix?

**Comment by sebastianbochan** [comment]
Hi @hartbert95,
At this moment we do not have ETA for this case, we will try to find a workaround. If will be possible, then post it here.

@oysteinmoseng do we have any workaround / solution for this kind of scenario?

**Comment by oysteinmoseng** [comment]
It should be possible to work around this by processing the data manually using the https://api.highcharts.com/highcharts/chart.events.exportData option. The data to be exported is sent as a parameter to this callback function and can be modified.
