### ISSUE TITLE
plotOptions.packedBubble should be written with a small letter

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#12639]
#### Behaviour
plotOptions.packedBubble should be written with a small letter. It causes problems with API, displaying double options plotOptions.packedbubble as well as plotOptions.packedBubble

https://github.com/highcharts/highcharts/blob/663825404345a074e465c34bdadf97eeb54c9ce9/js/parts-more/PackedBubbleSeries.js#L295 

#### Product version
8.0.0

#### Internal note
FYI: @sebastianbochan  @Izothep

**Comment by sebastianbochan** [comment]
Hi @madepiet,
Thank you for reporting about the issue.
