### ISSUE TITLE
Tools: Visual test comparison can report diff even when there seemingly is none

### ISSUE THREAD

**Issue by activist** [highcharts/highcharts#12640]
The diff produced by karma seems to sometimes be a false positive. Take for instance https://vrevs.highsoft.com/pr/12508/review from #12508 where there are diffs reported. In the produced gif there is possible to see a small diff that seems like font rendering or delay in rendering between the samples. 

When downloading SVGs in question, converting them to PNG and comparing with pixelmatch no diff is found which seems correct to me when visually comparing the two SVG files.

E.g 
https://s3.eu-central-1.amazonaws.com/staging-vis-dev.highcharts.com/visualtests/diffs/pullrequests/12508/highcharts/demo/heatmap/reference.svg
and 
https://s3.eu-central-1.amazonaws.com/staging-vis-dev.highcharts.com/visualtests/diffs/pullrequests/12508/highcharts/demo/heatmap/candidate.svg
seems identical to me.

We should do some digging to see if we can find the culprit or perhaps use pixelmatch to do the diffing in both cases.

**Comment by Denyllon** [comment]
I was able to notice the difference in `dotplot-equalizer` demo. It seems that the `marker.radius` is not applied at all, but i don't know what could cause the problem, because I'm not able to reproduce it locally.

**Comment by activist** [comment]
@Denyllon Regarding `dotplot` the diff reported is very small (< 10px), so in those cases is likely something that we can ignore. Often this seems to be due to fonts or rendering delays or similar (the real cause is yet to be found). 

As for the other/larger diffs in heatmap I'm not sure why the CI reports a diff, but what I mean with my above comment is that we should align the code that creates the baseline/reference image with the code that creates the snapshot/candidate image. Right now they differ slightly and that may be the reason as to why the CI reports that diffs are found (unless I miss something obvious).

**Comment by TorsteinHonsi** [comment]
@activist A possible improvement to understand small changes is to include an SVG string diff in the visual review tool. The utils has this. It takes the SVG, pretty-prints it, and compares.

![Skjermbilde 2019-12-17 kl  10 37 49](https://user-images.githubusercontent.com/227836/70983579-42cd2280-20b9-11ea-857c-6049d5fdc6fe.png)

**Comment by activist** [comment]
Ok, I could add something like that to the review tool. 

As mentioned above I think we also should align the way the SVG are stored so that we at least can exclude that as source of the "false positives". Do you agree or are there other possible reasons as to why these "false positive" diffs are reported that we should focus on instead? E.g could it be fonts (which I believe shouldn't be an issue when the svgs are created on the same platform) or animations that run?

**Comment by TorsteinHonsi** [comment]
I can't think of anything else but fonts. Yes, maybe animations, but in that case we need to fix it with our test suite, because all animation should be turned off everywhere. And yes, we should align the way the SVGs are stored so we are comparing one-to-one.

**Comment by Denyllon** [comment]
@activist I see, that actually there is the difference in 5575 pixels on `dotplot-equalizer`, but maybe I missed something important, or we're discussing about different things.
![Screenshot 2019-12-17 at 14 57 16](https://user-images.githubusercontent.com/15111955/71001657-05c75700-20de-11ea-95cf-be37977f3d86.png)

Furthermore (as I mentioned before) we can see that all markers does not have radius set on graphic:
Reference - ![Screenshot 2019-12-17 at 15 02 41](https://user-images.githubusercontent.com/15111955/71001802-550d8780-20de-11ea-8d74-e938ae2cd36a.png) Candidate - ![Screenshot 2019-12-17 at 15 02 50](https://user-images.githubusercontent.com/15111955/71001916-8a19da00-20de-11ea-8151-fea2342a26a0.png)

Unfortunately I can't reproduce it on all of my browsers (Chrome, FF, Safari). Maybe it is caused by the fact, that all modules are loaded one by one in Karma, and something has overridden? I'm only guessing.

**Comment by activist** [comment]
@Denyllon Yea, I must have misread the pixels for the `dotplot-equalizer` sample. Clearly there is something going on there and I have added better viewing of such differences in the review tool as well as textual diff of SVGs (will be deployed after xmas freeze). 

Once PR #12659 has been merged you can try to merge in master to your pr branch and hopefully the found differences should not be there anymore. (:crossed_fingers:)

**Comment by activist** [comment]
FYI: A new version of the visual review tool has been deployed which highlights these kinds of changes better, does an in-browser comparison and also includes a SVG string diffing option.
