### ISSUE TITLE
TypeScript: getTimezoneOffset should be a Function

### ISSUE THREAD

**Issue by cexbrayat** [highcharts/highcharts#12641]
#### Expected behaviour

`TimeOptions.getTimezoneOffset` should accept a callback to return the timezone offset. It is defined as accepting `any` in the typings of v7.2.1:

```typescript
/**
 * (Highcharts, Highstock, Gantt) A callback to return the time zone offset
 * for a given datetime. It takes the timestamp in terms of milliseconds
 * since January 1 1970, and returns the timezone offset in minutes. This
 * provides a hook for drawing time based charts in specific time zones
 * using their local DST crossover dates, with the help of external
 * libraries.
 */
getTimezoneOffset?: any;
```

#### Actual behaviour

The typings for `TimeOptions` in v8.0.0 is:

```typescript
getTimezoneOffset?: string;
```

raising compilation issues when updating projects to the latest release.

#### Product version

HighCharts v8.0.0

**Comment by sebastianbochan** [comment]
Hi @cexbrayat,
Thank you for reporting about the problem. 

FYI @bre1470
