### ISSUE TITLE
Export: xAxis & yAxis options are ignored inside of chartOptions

### ISSUE THREAD

**Issue by leettaylor** [highcharts/highcharts#12646]
#### Expected behaviour
I expect to be able to customise the `xAxis` and `yAxis` options inside of `exporting.chartOptions` so that the customisation displays when exporting the chart.

#### Actual behaviour
The chart exports without any changes applied from `exporting.chartOptions.xAxis` or `exporting.chartOptions.yAxis`

#### Live demo with steps to reproduce
https://jsfiddle.net/q3obaf6t/13/

1. Export chart as PNG
2. xAxis, yAxis, and Title should all be in the color `hotpink`

#### Product version
Highcharts v8.0.0

#### Affected browser(s)
N/A

**Comment by sebastianbochan** [comment]
Hi @leettaylor,
Thank you for reporting about the issue. The problem has been already reported here: https://github.com/highcharts/highcharts/issues/2022

Im closing this ticket as duplicate.
