### ISSUE TITLE
Can't translate tooltip dateTimeLabelFormats

### ISSUE THREAD

**Issue by julienfouilhe** [highcharts/highcharts#1264]
I'm currently translating a website using HighCharts/HighStock.
I didn't have any problem when I had to translate main sentences (like _"Loading"_, etc), but I realized that I forgot to translate the date format which was displaying in the tooltip.

I looked for "Week from", found it in two places in the same file : **highstock.src.js**.
1.  _**The first one**_ (**line 1,538**). It's easily translated, I used `Highcharts.setOptions();` and it was done, I can see it has been translated using Firebug. But my problem is that Highcharts is not using the translated sentence.
2.  _**The second one**_ (**line 14,663**). _How can we translate it ?_

**Comment by peterbraden-amana** [comment]
How did you get the first one to be replaced with setOptions? When setting the tooltip properties it doesn't seem to be overwritten.

A quick google shows that I'm not the only one with this problem: https://stackoverflow.com/questions/19932556/highstocks-tooltip-remove-the-phrase-week-from-monday

As an aside, why is an language-specific string not accessible from the lang object? It isn't currently possible to completely translate the graphs with lang.
