### ISSUE TITLE
Drilldown column chart appears broken after resize with latest version

### ISSUE THREAD

**Issue by brunoscopelliti** [highcharts/highcharts#12656]
## Live demo with steps to reproduce
https://jsfiddle.net/1uc0wxpe/1/

## Steps to reproduce.

1. Click on the label* "Internet Explorer" to drilldown to the Internet Explorer detail series.

2. Click the "Back to Browser" button to drillup to the main graph.

3. Click the label* "Firefox" to drilldown to the Firefox detail series.

\*  In order to reproduce the issue it's important you click on the label, not on the column.

### Expected Behaviour

I see Firefox specific data.

### Actual Behaviour

Graph appears broken.
Same code works fine (https://jsfiddle.net/bs823Lac/) with version 7.1.2

#### Product version
Highcharts v 8.0.0

#### Affected browser(s)
Chrome, Firefox (Mac).
It doesn't look like dependent on the browser.

**Comment by sebastianbochan** [comment]
Hi @brunoscopelliti,
Thank you for reporting about the problem. It looks like a regression.

_Internal note_
Bisect leads me to https://github.com/highcharts/highcharts/pull/12382/commits/078d442064a955e4a36c53eab0820fcc1c04fab0
