### ISSUE TITLE
Calling `series.setData` on pie chart with legend, results in a memory leak and visual artifacts

### ISSUE THREAD

**Issue by skrtheboss** [highcharts/highcharts#12651]
#### Expected behaviour
Calling `series.setData` on pie chart with legend should not result in a `memory leak/visual artifacts`.

#### Actual behaviour
If `setData` is called with diffrent `amount` of data, it does not clean up old legend entries.

#### Live demo with steps to reproduce
Open this [codepen](https://codepen.io/skrtheboss/pen/VwYmqqj), open console and see how the legends group array grows.

#### Product version
Higcharts v8.0.0

#### Affected browser(s)
All

**Comment by skrtheboss** [comment]
Issue may be related to #12627.

**Comment by kamilkulig** [comment]
Fixed in #12627 
**Live demo**: http://jsfiddle.net/BlackLabel/qmbtcogh/
The functionality will work correctly in the next Highcharts release.
