### ISSUE TITLE
Map in Highcharts throw error when data object has "state" property

### ISSUE THREAD

**Issue by gopinathshiva** [highcharts/highcharts#12653]
#### Expected behaviour
Highcharts shouldn't throw error when object has property such as "state"

#### Actual behaviour
Highcharts throw error when data object has "state" property

#### Live demo with steps to reproduce
https://codepen.io/gopinathshiva/pen/BayQMKx

1. Click on any of the lat lon
2. Then click on any of the 2 lat lon points
3. Find error in console

#### Product version
8.0.0

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @gopinathshiva 

Thank you for reporting the problem.
`state` is an internal and restricted property that is used for setting a state of a point - like hovered, selected, etc. Similar situation is with `color`, so if you will set `color` for a point then it will be used to set the color for the element.
`state` cannot be used as a custom property of a point as it is already used internally in code.
This issue could be resolved by adding the relevant information to documentation and/or API reference.

@gopinathshiva could you let me know where would you expect to find such info? Have you search for a possible solution in our docs and/or API reference? If yes, then we could add the info there, so please share the relevant links you have visited if possible.

_Internal note:_
This is a general Highcharts problem, but using `state` in a map is a more natural example of the problem.

**Comment by gopinathshiva** [comment]
@KacperMadej Thanks for replying. It makes sense why the error is thrown now.

I didn't find any docs containing "state" as data property in highcharts. 

I came across this issue when I load data from api (which has state as property) directly into highcharts api. So I thought it would be great to let you guys know that there is an issue going on with this custom property. 

So are you suggesting not to have "state" as property in data? or are you planning to work on any solution for this.

**Comment by KacperMadej** [comment]
Yes, `state` shouldn't be used as a data property. You could use something like `state_name`, `state-id`, `st`, `"parent state"`, etc. instead of `state` in your data. Currently, the only considered solution is to increase awareness of this limitation by adding the info to docs, so for you it won't change anything as you already know this limitation.

**Comment by bre1470** [comment]
@KacperMadej @TorsteinHonsi 
Maybe we should consider underscore syntax for internal options, so that no conflict occurs with custom user options. Or allow custom user options under a sub property of type dictionary only.

**Comment by KacperMadej** [comment]
Both look like a breaking change - either for accessing custom or internal properties from any `formatter`s, `positioner`s or `event`s functions. For the sake of size of changes in code (and also it might be better for TS definitions) the sub-property, like `customOptions`, seems to me like a better option IMO.
