### ISSUE TITLE
Changing axis color for export doesn't work

### ISSUE THREAD

**Issue by elladan06** [highcharts/highcharts#12665]
#### Expected behaviour
The configuration of exporting.chartOptions.xAxis should be use when export to image or pdf.

#### Actual behaviour
The configuration of exporting.chartOptions.xAxis is not use when export to image or pdf.

#### Live demo with steps to reproduce
template: http://jsfiddle.net/w1r0kjeg/

#### Product version
Highcharts JS v8.0.0 (2019-12-10)
with exporting module

#### Affected browser(s)
Only tried on Chrome

**Comment by sebastianbochan** [comment]
Hi @elladan06 ,
Thank you for reporting about the issue. The problem has been already reported here: https://github.com/highcharts/highcharts/issues/2022

Im closing this ticket as duplicate.
