### ISSUE TITLE
Hide series with visible:false on click

### ISSUE THREAD

**Issue by PierreClementCazon** [highcharts/highcharts#12667]
Hi ,

My problem is simple but I have not been able to solve it.

How to detect, with jQuery, on click, the items of a legend having as parameter visible:false to replace it by showInLegend:false ?

Thanks in advance for your help.

**Comment by sebastianbochan** [comment]
Hi @PierreClementCazon,
The github is our bug tracker, so for general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or forum.

ps. you can catch the [legendItemClick](https://api.highcharts.com/highcharts/plotOptions.line.events.legendItemClick) event and iterate on each series to detect current status.
