### ISSUE TITLE
Problem with tooltip not showing when all sets in legend selected when zoomed in

### ISSUE THREAD

**Issue by wilwet** [highcharts/highcharts#12660]
I have a problem that a tooltip is not show when zoomed in, when zoomed out the tooltip does works fine. It does not matter witch of de sets is selected the last one  disables the tooltip. This only happens when zoomed in. 

Chrome works fine, FF,Safari en Brave does not work.   Tested under version 8.0.0 

<img width="968" alt="Schermafbeelding 2019-12-18 om 16 41 25" src="https://user-images.githubusercontent.com/25547191/71100428-4ba31e80-21b5-11ea-942c-74334763032b.png">

<img width="1005" alt="Schermafbeelding 2019-12-18 om 16 42 28" src="https://user-images.githubusercontent.com/25547191/71100461-5e1d5800-21b5-11ea-808d-e93588946219.png">

formatter: function() {

                var s = '<b>'+ Highcharts.dateFormat('%A, %Y-%m-%d', this.x) +'</b>';
                var d = this.points;
                var piekVerbruikt=dalVerbruikt=piekGeleverd=dalGeleverd=gasVerbruikt=waterVerbruikt=0;
                
                for (var i=0,  tot=d.length; i < tot; i++) {
                    //console.log (d[i].series.userOptions.id);

                    if  ( d[i].series.userOptions.id === 'piek_ver') {
                        piekVerbruikt = d[i].y;
                    }
                    if  ( d[i].series.userOptions.id === 'dal_ver') {
                        dalVerbruikt = d[i].y;
                    }
                    if  ( d[i].series.userOptions.id === 'piek_gel') {
                        piekGeleverd = d[i].y;
                    }
                    if  ( d[i].series.userOptions.id === 'dal_gel') {
                        dalGeleverd = d[i].y;
                    }
                    if  ( d[i].series.userOptions.id === 'gas_ver') {
                        gasVerbruikt = d[i].y;
                    }
                    if  ( d[i].series.userOptions.id === 'water_ver') {
                        waterVerbruikt = d[i].y;
                    }
                }
                
                /*
                console.log ('piekVerbruikt='+piekVerbruikt);
                console.log ('dalVerbruikt='+dalVerbruikt);
                console.log ('piekGeleverd='+piekGeleverd);
                console.log ('dalGeleverd='+dalGeleverd);
                console.log ('gasVerbruikt='+gasVerbruikt);
                console.log ('waterVerbruikt='+waterVerbruikt);
                console.log ('----------------------------\n');
                */
                
                var index = null;
                for (var i=0,  tot=GpiekDataVerbr.length; i < tot; i++) {
                    if ( GpiekDataVerbr[i][0] === d[0].key ) {
                            index = i;
                            //console.log('index='+i);
                            break;
                        }
                }
                
                var KWhVerbruikt     = 'onbekend';
                var kWhLevering      = 'onbekend';
                var GasM3Verbruikt   = 'onbekend';
                var WaterM3Verbruikt = 'onbekend';
                // AANGEPAST MET NIEUWE API
                if ( GExtraData[index][1] !== null ) { KWhVerbruikt     = GExtraData[index][2].toFixed(2); } 
                if ( GExtraData[index][2] !== null ) { kWhLevering      = GExtraData[index][3].toFixed(2); }
                if ( GExtraData[index][3] !== null ) { GasM3Verbruikt   = GExtraData[index][4].toFixed(3); }
                if ( GExtraData[index][4] !== null ) { WaterM3Verbruikt = GExtraData[index][5].toFixed(3); }
                
                var pv1=pv2=dv1=dv2=pg1=pg2=dg1=dg2=pt1=pt2=dt1=dt2=gas1=gas2=net1=net2=gasm21=gasm22=verbrkwh1=verbrkwh2=levrkwh1=levrkwh2=water1=water2=water21=water22='';
                var totVerbruikt=0;
                var totGeleverd=0;
                  
                totVerbruikt = parseFloat( piekVerbruikt )+ parseFloat( dalVerbruikt ) + parseFloat( gasVerbruikt ) + parseFloat( waterVerbruikt );
                totGeleverd  = parseFloat( piekGeleverd ) + parseFloat( dalGeleverd );
                totaalNetto  = parseFloat( totVerbruikt ) + parseFloat( totGeleverd );

                //console.log(totVerbruikt);
                //console.log(totGeleverd);
                //console.log(totaalNetto);
                
                if ( $('#CostChartVerbr').highcharts().series[0].visible === true ) {	
                    pv1 = '<span style="color: #FFC311;">Piek kosten verbruik:</span><br/>';
                    pv2 = '&nbsp;&euro;&nbsp;'+piekVerbruikt.toFixed(2)+'<br/>';
                }
                if ( $('#CostChartVerbr').highcharts().series[1].visible === true ) {
                    dv1 = '<span style="color: #CEA731;">Dal kosten verbruik:</span><br/>';
                    dv2 = '&nbsp;&euro;&nbsp;'+dalVerbruikt.toFixed(2)+'<br/>';
                }
                
                if ( $('#CostChartVerbr').highcharts().series[4].visible === true ) {
                    gas1 = '<span style="color: #507ABF;">Gas kosten verbruik:</span><br/>';
                    gas2 = '&nbsp;&euro;&nbsp;'+gasVerbruikt.toFixed(2)+'<br/>';
                    gasm21 = '<br/>Gas verbruik:';
                    gasm22 = '<br/>'+GasM3Verbruikt +' m&#179;';
                }
                
                if ( $('#CostChartVerbr').highcharts().series[5].visible === true ) {
                    water1  = '<span style="color: #6699ff;">Water kosten verbruik:</span><br/>';
                    water2  = '&nbsp;&euro;&nbsp;' + waterVerbruikt.toFixed(2) + '<br/>';
                    water21 = '<br/>Water verbruik:';
                    water22 = '<br/>' + WaterM3Verbruikt + ' m&#179;'; //+ ' m<sup>3</sup>';
                }

                if ( $('#CostChartVerbr').highcharts().series[2].visible === true ) {
                    pg1 = '<span style="color: #98D023;">Piek kosten geleverd:</span><br/>';
                    pg2 = '&nbsp;&euro;&nbsp;'+piekGeleverd.toFixed(2)+'<br/>';
                }
                if ( $('#CostChartVerbr').highcharts().series[3].visible === true ) {
                    dg1 = '<span style="color: #7FAD1D; ">Dal kosten geleverd:</span><br/>';
                    dg2 = '&nbsp;&euro;&nbsp;'+dalGeleverd.toFixed(2)+'<br/>';
                }

                if ( $('#CostChartVerbr').highcharts().series[0].visible === true && $('#CostChartVerbr').highcharts().series[1].visible === true && $('#CostChartVerbr').highcharts().series[5].visible === true && $('#CostChartVerbr').highcharts().series[4].visible === true ) {
                    pt1 = '<span style="color: #6E797C;"><b>Totaal verbruikt:</b></span><br/>';
                    pt2 = '&nbsp;&euro;&nbsp;'+totVerbruikt.toFixed(2)+'<br/>';
                    verbrkwh1 = '<br/>kWh verbruik:'
                    verbrkwh2 = '<br/>'+KWhVerbruikt+' kWh'
                }
                if ( $('#CostChartVerbr').highcharts().series[2].visible === true && $('#CostChartVerbr').highcharts().series[3].visible === true ) {
                    dt1= '<span style="color: #6E797C;"><b>Totaal geleverd:</b></span><br/>';
                    dt2= '&nbsp;&euro;&nbsp;'+totGeleverd.toFixed(2)+'<br/>';
                    levrkwh1 = '<br/>kWh levering:';
                    levrkwh2 = '<br/>' + kWhLevering +' kWh';
                }

                if ( $('#CostChartVerbr').highcharts().series[7].visible === true ) {
                    // adjust text if we we have to pay or get money back
                    if (totaalNetto >= 0) {
                        net1 = '<span style="color: #6E797C;"><b>Netto kosten:</b></span><br/>';
                    } else {
                        totaalNetto = Math.abs(totaalNetto) // no minus numbers
                        net1 = '<span style="color: #6E797C;"><b>Netto opbrengsten:</b></span><br/>';
                    }
                    net2 = '&nbsp;&euro;&nbsp;'+totaalNetto.toFixed(2)+'<br/>';
                }

                s += '<div style="width: 220px; z-index: 9999">';
                    s += '<div class="float-left">';
                        s += pv1;
                        s += dv1;
                        s += gas1;
                        s += water1;
                        s += pt1;
                        s += dg1;
                        s += pg1;
                        s += dt1;
                        s += net1;
                        s += verbrkwh1;
                        s += levrkwh1;
                        s += gasm21;
                        s += water21;
                    s += '</div>';
                
                    s += '<div class="float-right">';
                        s += pv2;
                        s += dv2;
                        s += gas2;
                        s += water2;
                        s += pt2;
                        s += dg2;
                        s += pg2;
                        s += dt2;
                        s += net2;
                        s += verbrkwh2;
                        s += levrkwh2;
                        s += gasm22;
                        s += water22;
                    s += '</div>';
                s += '</div>';
                //console.log(s);
                return s;

            },

**Comment by sebastianbochan** [comment]
Hi @wilwet,
Thank you for reporting about the problem. Its really difficult to debug form the screenshot, could you share a live demo? Do you receive any errors in the console ?

**Comment by wilwet** [comment]
I kind of solved it by changing the container size from 480px to 500px. <div id="CostChartVerbr" style="width:100%; height:500px;"></div> I tried using  outside: true on the tooltip but to no avail.  When i used this  together with useHTML: true the tooltip appears but  but the content is not show. 
<img width="528" alt="Schermafbeelding 2019-12-26 om 10 01 51" src="https://user-images.githubusercontent.com/25547191/71468592-d3e17f00-27c6-11ea-8ae9-0b2466aae6e3.png">
 
The resize helps but is still feels like a bug.

**Comment by sebastianbochan** [comment]
Hi @wilwet,
I am really sorry but it is really difficult to debug from the screenshots. Is it possible to setup a simple live demo? Do you receive any errors in the console ?

**Comment by wilwet** [comment]
Hi there are no error's in the console. I will look if making a live demo is possible.

**Comment by wilwet** [comment]
I solved the problem.  the style="width: 220px; z-index: 9999">';  was wrong. When the div is not wide enough then it won't show up. Changing the wide to 260px fixed it.
