### ISSUE TITLE
`zoomKey` is ignored

### ISSUE THREAD

**Issue by FilipeCosta06** [highcharts/highcharts#12669]
#### Expected behaviour
According to the [documentation](https://api.highcharts.com/highcharts/chart.zoomKey)

> zoomKey: string
> Set a key to hold when dragging to zoom the chart. **This is useful to avoid zooming while moving points**.

(included in the [now deprecated](https://github.com/highcharts/draggable-points) `draggable-points` file, which 
>  is deprecated as of November 2018, and replaced by the featured draggable-points Highcharts module that includes the same functionality and more.

).

Therefore, setting 
```
chart: {
    panning: true,
    panKey: 'shift',
    animation: false,
    zoomType: 'x',
    zoomKey: 'ctrl'
}
```
should mean that it is impossible to zoom without holding the `ctrl` key, right ? Or did I misunderstand it (not English native).

#### Actual behaviour
We are able to zoom without pressing the specified key.

#### Live demo with steps to reproduce
https://jsfiddle.net/ejns8dkt/1/

1. Drag/Drop anywhere on the graph without holding the Control key 
2. Observe the chart zooming

#### Product version
HighCharts and Highcharts Gantt 8.0.0, also in 7.2.1

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @FilipeCosta06,
Thank you for reporting about the problem. It looks like the `zoomKey` option does not work.

Demo:
- https://jsfiddle.net/BlackLabel/uqmLh9ot/

**Comment by pawelfus** [comment]
Well, I'm not sure if this is a bug or some expected behaviour. This option works only when points are actually draggable, to distinguish between drag&drop vs zooming in, see demo: https://jsfiddle.net/BlackLabel/s6xfnvze/ (use shift-key too zoom in)

Any comment @oysteinmoseng ?

**Comment by FilipeCosta06** [comment]
I forgot to signal that I discovered this while having `zoomKey` and `drag-dropping` enabled, in a Gantt [demo](https://jsfiddle.net/347bwz9g/). Even though I have 
```
    chart: {
      spacingLeft: 1,
      animation: false,
      panning: true,
      panKey: "ctrl",
      zoomType: 'x',
      zoomKey: 'shift'
    },
```
We are able to zoom without pressing `Shift`, while drag dropping is available.

PS:
Sorry for the mess, I tried my best to extract the `userOptions` of the go-to demo I made to test features/ideas (and I'm probably introducing bugs as I do so since it doesn't seem like Gantt Chart is meant to have both multiple tasks per line AND sub-tasks, "collapsable" groups, as we discussed in previous issues).

**Comment by pawelfus** [comment]
Still, it works as described: https://jsfiddle.net/BlackLabel/zx89wn76/ 

Steps:
- drag&drop first bar "Etude" - drag&drop performed without issues
- drag&drop first bar "Etude" with Shift key - zooming instead of point's drag&drop is performed

As described above, this option distinguishes only between zooming and dragging a point.

**Comment by FilipeCosta06** [comment]
Oh indeed I see what you meant now.

I thought the point of this option was to only "allow" zoom when the key was pressed. I may have been confused about that all along, and maybe this isn't even a bug then. 

Is there an event like `zoomStart` I could use to achieve what I want (preventing the zoom/shadow if the `zoomKey` isn't pressed) ? A `dragStart` but for the background/plotOptions ?

**Comment by pawelfus** [comment]
Hmm.. there's no `zoomStart` event, however this plugin should work: https://jsfiddle.net/BlackLabel/mgj7bL8k/

```js
(function(H) {
  H.wrap(
    H.Pointer.prototype,
    'dragStart',
    function(proceed, event) {
      const zoomKey = this.chart.options.chart.zoomKey && this.chart.options.chart.zoomKey + 'Key';

      if (event[zoomKey]) {
        proceed.call(this, event);
      }
    }
  );
})(Highcharts);
```

API:
```js
{
  chart: {
    zoomKey: 'shift'
  }
}
```

**Comment by FilipeCosta06** [comment]
Thanks a lot for the workaround @pawelfus ! This'll do perfectly.

Sorry for the confusion if this issue was actually the normal behaviour.

**Comment by pawelfus** [comment]
You're welcome!

I think it would be nice to have this option anyway. Or at least improve description in API to avoid further confusion. Let's await @oysteinmoseng opinion here.
