### ISSUE TITLE
zoom xy with series-label enabled keeps zooming indefinetely

### ISSUE THREAD

**Issue by JeremyRippert** [highcharts/highcharts#12676]
#### Expected behaviour

I zoom only once when I zoom on a serie

#### Actual behaviour

When I zoom on series 1 the zoom window selector stays active.
When I zoom on series 2 or in an empty space it only zooms once, as expected.

#### Live demo with steps to reproduce

Here is a video showing the behavior: https://vimeo.com/user106720322/review/381156652/6b73b8eabe
Here is the fiddle used in the video https://jsfiddle.net/ek0csqxt/
You can delete the line 
`<script src="https://code.highcharts.com/modules/series-label.js"></script>`
in the html to make the zoom feature work as expected

The same bug is happening with Highstock

#### Product version

Highcharts JS v8.0.0 (2019-12-10)
Highstock JS v8.0.0 (2019-12-10)

#### Affected browser(s)
Firefox for Ubuntu 71.0 (64-bit)

**Comment by KacperMadej** [comment]
Hi @JeremyRippert 

Thank you for reporting the problem.

Minimal demo: https://jsfiddle.net/BlackLabel/sLpvryx3/
(after 1 second a zoom will trigger the error in the browser console)

_Internal note:_
When zooming into a range with a line connecting some points but with no visible points KD tree cannot use them and `searchPoint` returns `undefined`.

**Comment by khlieng** [comment]
Fixed since 8.1.0.
