### ISSUE TITLE
Legend not cleaning up on chart update with v8.0.0

### ISSUE THREAD

**Issue by semihozbag** [highcharts/highcharts#12674]
When updating a chart with different values, it seems highcharts is not cleaning up old legend data and puts the new items over old ones

First call:
![Screenshot from 2019-12-23 14-16-57](https://user-images.githubusercontent.com/6987196/71355127-29334b80-258f-11ea-88f0-fdc0301d04c2.png)
![Screenshot from 2019-12-23 14-18-34](https://user-images.githubusercontent.com/6987196/71355123-25072e00-258f-11ea-8894-91613b5ccfd1.png)

After update data:
![Screenshot from 2019-12-23 14-17-26](https://user-images.githubusercontent.com/6987196/71355141-3819fe00-258f-11ea-841c-8b9e9c64857c.png)
![Screenshot from 2019-12-23 14-17-14](https://user-images.githubusercontent.com/6987196/71355149-3bad8500-258f-11ea-86b8-1d2cad9c03ce.png)

**Comment by KacperMadej** [comment]
Hi @semihozbag 

Thank you for reporting the problem.
Please add a live demo of the problem.

**Comment by semihozbag** [comment]
@KacperMadej sorry for absence,

Here it is: https://jsfiddle.net/cj1Ls0ra/

**Comment by sebastianbochan** [comment]
Hi @semihozbag,
We are developing completely new legend module, so will test this case too. Thank you for the hint.

**Comment by kamilkulig** [comment]
The problem has already been fixed in #12627 and merged to the master branch (the fix will be available in the next release of Highcharts).
**Demo**: https://jsfiddle.net/BlackLabel/6rgn0fvu/
