### ISSUE TITLE
Panning: maps panning type 'xy' not working

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#12671]
#### Behaviour
Looks like enabling vertical panning for Stock broke it for Maps.

@Denyllon 
https://github.com/highcharts/highcharts/commit/f5b56c90d4e254e616737c2b599a74c34f3b378a

The new state is added only for Stock. When debugging a Highmaps demo - the needed property is undefined.

By default panning of type 'xy' should be enabled for the `map` constructor in Highmaps - otherwise, the vertical panning feature will cause a regression for Highmaps.

BTW: `panningState` is added to colorAxis as well as to yAxis, so this could be fixed too.

I have checked if loading the Stock module will work as a workaround, but it doesn't help since panningState is being filled with `NaN`s - series.yData for map series is full of `undefined`.

fyi: @sebastianbochan 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/q74vr8aj/

Zoom in and try panning vertically.
Only horizontal panning is visible.

#### Product version
8.0.0

**Comment by jamesroyston** [comment]
+1. Vertical panning works in 7.2.1 for those who are needing a solution now.

**Comment by TorsteinHonsi** [comment]
It still happens in the OP demo.

**Comment by Denyllon** [comment]
It's something wrong with `master` branch on our `github.highcharts.com` CDN. If I'm changing the links so that they refers the commit of merge with master, it works fine.
https://jsfiddle.net/BlackLabel/zfvtug2h/

**Comment by Denyllon** [comment]
Looks like it does work well on `master` now. I'm closing the ticket.
https://jsfiddle.net/BlackLabel/y6ew7g2x/

**Comment by angeliqueIcono** [comment]
Hi!
I think it's not fixed when you use highcharts.js... I still have the bug!

**Comment by pawelfus** [comment]
Did you try https://github.highcharts.com/highcharts.js file? Bug seems to be fixed on our **master** branch, so it's not released yet.

**Comment by angeliqueIcono** [comment]
ah ok I didn't understood, I have the last version 8.0.4 but if the fix is not released yet it's normal... Do you know when it's going to be released?

**Comment by pawelfus** [comment]
No ETA for the next release, but I expect something within a few weeks.

**Comment by lesliecdubs** [comment]
Hi @pawelfus, any updates or ETA on this release? 🙂 Thanks!

**Comment by sebastianbochan** [comment]
@lesliecdubs 
We're just preparing and testing the final release, which should be really soon.

Thank you for patience.
