### ISSUE TITLE
Automatic min/max range is not set correctly for 'area' and 'column' fill types

### ISSUE THREAD

**Issue by ibrhmyzc** [highcharts/highcharts#12673]
#### Expected behaviour
all types should have the same min max values
#### Actual behaviour
When the type is line, min and max values are set, but for others types for spiderweb or polar chart, it shows values from 0 to max

#### Live demo with steps to reproduce
https://jsfiddle.net/kd8qsbjy/5/

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @ibrhmyzc 

This is correct behavior as `threshold` for area type series is 0 by default.
You could change it to `null` - demo: https://jsfiddle.net/BlackLabel/kf402Lmz/

This doesn't look like a bug, so I will close this issue.
