### ISSUE TITLE
scrollablePlotArea: hover triggers wrong point hover state and bad tooltip

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#12675]
#### Behaviour
When the scroll is positioned on the left side of the scrollbar hovered point is correct. But when You start to scroll to the right hover position has a gap between cursor. The gap depends on the distance of the scroll from the left side.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea

Hover over the chart and notice bad hovered points and a bad tooltip.

#### Product version
8.0.0

**Comment by roniRamon** [comment]
is there a fix for this?

**Comment by sebastianbochan** [comment]
Hi @roniRamon,
At this moment we do not have any ETA for this issue, because of christmas and new year eve time.

**Comment by pawelfus** [comment]
Bisected to commit 7b9485b458

**Comment by roniRamon** [comment]
@sebastianbochan Thank you for the quick answer. will wait until for the patch release

**Comment by pawelfus** [comment]
Fixed since v8.0.1: https://jsfiddle.net/BlackLabel/e3pkytz9/
