### ISSUE TITLE
label "Navigator 1" appears in navigator when curve color is light blue (e.g #7CB5ED)

### ISSUE THREAD

**Issue by JeremyRippert** [highcharts/highcharts#12677]
#### Expected behaviour

I don't see a label "Navigator 1" on the right of the navigator

#### Actual behaviour

When the curve color is light blue (e.g #7CB5ED), I see "Navigator 1" on the right of the navigator

#### Live demo with steps to reproduce

In this fiddle : https://jsfiddle.net/yxw0hmg3/
For the first series:
set color: "#7CB5ED" to show the bug
set color: "#0000FF" to show the correct behavior

#### Product version

Highstock JS v8.0.0 (2019-12-10)

#### Affected browser(s)
Mozilla Firefox for Ubuntu (71.0)

**Comment by sebastianbochan** [comment]
Hi @JeremyRippert,
Thank you for report about the problem. It looks like a small problem with contrast option, but you can apply the color in the `series.label.style` option.

**Demo:**
- https://jsfiddle.net/BlackLabel/r34mqaj2/

_Internal note_
The problem also appears in Chrome 78.0.3904.108 (MacOSX)

**Comment by JeremyRippert** [comment]
Hi @sebastianbochan , thank you for your answer.

My problem isn't that much that "Navigator 1" isn't the same color as the label on the series, but that it shows at all.

It there a way not to show "Navigator 1" for any color ?

**Comment by sebastianbochan** [comment]
You can disable it by the `navigator.series.label` option.

Demo:
- https://jsfiddle.net/BlackLabel/syncmv7L/

**Comment by JeremyRippert** [comment]
Hi @sebastianbochan , thank you very much :)

**Comment by Rouhollah** [comment]
> I apologize for my misunderstood! You can disable it by the `navigator.series.label` option.
> 
> Demo:
> 
> * https://jsfiddle.net/BlackLabel/syncmv7L/

it solved my problem. thank you.

**Comment by halloleo** [comment]
It fixed the same issue for me too. 

(Still odd that just a change of colour can make the text "Navigator 1" appear or disappear (when `navigator.series.label ` is _not_ disabled).)
