### ISSUE TITLE
Is there a way to get point.y of all series in tooltip.headerFormat

### ISSUE THREAD

**Issue by perry14** [highcharts/highcharts#12670]
#### Expected behaviour
I want tooltip  looks like:

series1 name    |  series2 name
---- | ---
series1 point.y  | series2 point.y 

As shown in the red box below.

![Screen Shot 2019-12-23 at 3 05 28 PM](https://user-images.githubusercontent.com/1539151/71343351-8680ca00-259a-11ea-902b-d448ff4adbac.png)

Is there a way to get point.y of all series in tooltip.headerFormat ?

#### Actual behaviour

series1 name    |  series1 point.y
---- | ---
series2 name  | series2 point.y 

As shown in the blue box above.

#### Live demo with steps to reproduce
https://jsfiddle.net/p3rry14/yre1q7u3/9/

#### Product version
Highcharts JS v8.0.0 (2019-12-10)

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @perry14,
The github is our bug tracker, so for general [support]() questions please use stackoverflow / forum or email.

ps. You can customize the tooltip content by [tooltip.formatter](https://api.highcharts.com/highcharts/tooltip.formatter)
