### ISSUE TITLE
Tooltip has wrong position when scrollable plot area turned on.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#12682]
#### Expected behaviour
Tooltip should be positioned relative to chart container, not to a whole page.

#### Actual behaviour
The tooltip is positioned relative to page, instead of chart's container. We can notice the problem while using `tooltip.positioner` function, and return the object with e.g `x: 0, y: 0`.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/y64Lhk8f/

#### Product version
 Highcharts >= v7.1.2

Probably related with #12498

**Comment by KacperMadej** [comment]
Might be related to #12657 and #12675

**Comment by jareware** [comment]
Not sure if it's pertinent or not, but it's not just the tooltip, it's also clicks: any click event you register will get the incorrect coordinates and/or data point passed to it.

**Comment by sirhvd** [comment]
I think this issue related to scrollingContainer.  
Problems have been solved temporarily by remove **chart.scrollingContainer** from **getChartPosition()**

`
Highcharts.Pointer.prototype.getChartPosition = function () {
     var chart = this.chart;
  var container = chart.container;
  return (this.chartPosition ||
          (this.chartPosition =  Highcharts.offset(container)));
};
`

Demo: https://jsfiddle.net/sirhvd/tw0b5Lm1/

**Comment by kamilkulig** [comment]
The problem doesn't seem to occur if we disable `tooltip.outside` option (`true` is the default value for the charts with scrollable plot area): https://jsfiddle.net/BlackLabel/L0ryz4sn/
So, now I wonder if it actually works as expected because when the tooltip is `outside` then it is meant to be positioned relatively to the whole page.
