### ISSUE TITLE
Venn Fast can't be selected, can't show toolip

### ISSUE THREAD

**Issue by cxf0505** [highcharts/highcharts#12684]
#### Expected behaviour
Fast can't be selected, can't show toolip
I set the datalabels property enabled to false

#### Actual behaviour
![image](https://user-images.githubusercontent.com/25787258/71463065-2e430580-27f0-11ea-8cac-c51d1ea674b7.png)

#### Live demo with steps to reproduce

https://jshare.com.cn/demos/RFMD8W/9
#### Product version

7.2.1
#### Affected browser(s)
All browsers

**Comment by sebastianbochan** [comment]
Hi @cxf0505,
Thank you for reporting about the bug.

_Internal note_
Related with: https://github.com/highcharts/highcharts/issues/12049

**Simplified demo:**
- https://jsfiddle.net/BlackLabel/z392m7do/

**Comment by pawelfus** [comment]
**Workaround:**
Change order from the highest value to the lowest.
Demo: https://jsfiddle.net/BlackLabel/rs7qveaL/

**Comment by pawelfus** [comment]
Use internally data-sorting, so behind the scenes, we order points like in the workaround.
