### ISSUE TITLE
Column data label disappears in very specific cases

### ISSUE THREAD

**Issue by tsirilson** [highcharts/highcharts#12688]
#### Expected behaviour
All column data labels should show

#### Actual behaviour
Some very small data labels get hidden if `series.column.borderWidth` is set to 0, in combination with a small chart height.

#### Live demo with steps to reproduce
https://jsfiddle.net/roqeugsn/

In this example, the label for the value `0.6` doesn't show if the chart's height is anywhere between `172px` and `275px` in height, while `borderWidth` is `0`. Removing `borderWidth` solves the issue.

At first glance it looks like an absurdly specific case, but this is what led me to figure out that a recent change broke my chart that's been fine for 3-4 years now. 

This combination of parameters seems to work fine on all versions up to v7.2.1.

#### Product version
Since v8.0.0

#### Affected browser(s)
All of them

**Comment by sebastianbochan** [comment]
Hi @tsirilson,
Thank you for the reporting. It looks like a regression.

_Internal note_
Related case: https://github.com/highcharts/highcharts/issues/12390

**Comment by pawelfus** [comment]
Bisected to commit 41225588ed
FYI @wchmiel

**Comment by tsirilson** [comment]
You guys are golden. I spent more time than I'm ready to admit, trying to figure out why my chart does this, until I checked the change log and subsequent pull requests.
