### ISSUE TITLE
Regression: series.setData(...) incorrectly updates points and xData

### ISSUE THREAD

**Issue by pomack** [highcharts/highcharts#12696]
#### Expected behaviour
In Highstocks, when viewing last 1M of 1Y series the `series.xData` is 1Y of entries whereas `series.points` is ~1M of data. Calling `series.setData(...)` calls `series.findPointIndex()` which should look at `series.points` to update point.

#### Actual behaviour

Calling `series.setData()` calls `series.findPointIndex()` which incorrectly gets the index from `series.xData` instead of `series.points`. This causes points before the last 1M to be moved, duplicated, and reordered. It also screws up `series.userOptions.data`

Specifically the interplay of https://github.com/highcharts/highcharts/blob/v8.0.0/js/parts/Series.js#L3107
and 
https://github.com/highcharts/highcharts/blob/v8.0.0/js/parts/Series.js#L3163

#### Live demo with steps to reproduce
https://jsfiddle.net/pomack/ns415gvu/78/

#### Product version
Highstocks 7.1.x, 7.2.1, 8.0.0

Was correct in 7.0.3 and earlier.

#### Affected browser(s)
All (Chrome and Safari tested)

**Comment by pawelfus** [comment]
Thanks for reporting this bug @pomack 

*Internal note:*
Bisected to commit 98db6d3ffb (worth to check also: 3ed88b376658b76185cc8043ddf7d55531a9880c)
