### ISSUE TITLE
accessibility module causing render issues in funnel 3d chart

### ISSUE THREAD

**Issue by cor3000** [highcharts/highcharts#12690]
#### Expected behaviour

use the live demo below and remove accessibility.js

![image](https://user-images.githubusercontent.com/3894309/71576981-5e124600-2b2d-11ea-86e3-93417a27cccc.png)

#### Actual behaviour

![image](https://user-images.githubusercontent.com/3894309/71576968-505cc080-2b2d-11ea-937e-16690d2dd37c.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/r2skt4ju/

#### Product version
8.0.0

#### Affected browser(s)
reproduced in Chrome

**Comment by sebastianbochan** [comment]
Hi @cor3000,
Thank you for reporting about the problem.

FYI @oysteinmoseng

**Comment by pawelfus** [comment]
Bisected to commit 7ecef2fa7b - rather unrelated commit, but many tests I had to skip because of various errors in console.
