### ISSUE TITLE
High Charts 3D - Property "depth" get not automatically adjusted

### ISSUE THREAD

**Issue by egloffmark** [highcharts/highcharts#12698]
#### Expected behaviour

In case you have a 3D pie chart, the "depth" get not automatically adjusted if you shrink the diagram or if you look at the page on your mobile phone. It would be good if the "depth" would be automatically adjusted or if you can enter a percentage value instead of an absolute number

![Selection_270](https://user-images.githubusercontent.com/7382336/71624636-d63b4300-2be3-11ea-81c9-bf8ec4738d34.png)
![Selection_272](https://user-images.githubusercontent.com/7382336/71624732-582b6c00-2be4-11ea-9a6a-947547fb4d8b.png)

#### Actual behaviour

The "depth" stays the same and will not be adjusted if you shrink the space of the diagram i.e. on your mobile phone compared to a desktop view.

![Selection_270](https://user-images.githubusercontent.com/7382336/71624636-d63b4300-2be3-11ea-81c9-bf8ec4738d34.png)
![Selection_271](https://user-images.githubusercontent.com/7382336/71624637-d9363380-2be3-11ea-9138-ef569a407c60.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/3d-pie  Enter here a bigger depth like "120" and shrink the view of the diagram or compare the view between desktop and mobile
```
 plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            depth: 120,
            dataLabels: {
                enabled: true,
                format: '{point.name}'
            }
        }
    },
```
#### Product version
Highcharts 3D, latest available version 
```
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
```

#### Affected browser(s)
All tested : Firefox, Chrome

**Comment by pawelfus** [comment]
Hi @egloffmark 

Thanks for reporting this issue. `depth` only accepts numbers, not percentage. To achieve what you need, you should use [`responsive`](https://api.highcharts.com/highcharts/responsive) option. Because of #12515 bug it won't work in v7.2.1 and v8.0.0, but this should be fixed in the next release. Example: https://jsfiddle.net/BlackLabel/5uqtLsg6/
