### ISSUE TITLE
Gantt chart without the `renderTo` argument in a constructor method is not created

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#12708]
#### Expected behaviour

It should work in the same way as with the basic chart constructor: http://jsfiddle.net/BlackLabel/wzsu6ey1/

#### Actual behaviour

Error: 

`Uncaught TypeError: Cannot read property 'series' of undefined`

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/s1rkyupn/

#### Product version
Gantt v8.0.0

#### Affected browser(s)
All
___
_Internal note:_

Probably caused by the wrong order of setting options:

https://github.com/highcharts/highcharts/blob/f2fb01cb33fd562098001078ea5d7c8cb0237a83/ts/parts-gantt/GanttChart.ts#L79-L85

**Comment by castortech** [comment]
Here are the changes that I made and this is working for me:

`var hasRenderToArg = typeof renderTo === 'string' || renderTo.nodeName, defaultOptions = H.getOptions(), defaultLinkedTo;`
`options = arguments[hasRenderToArg ? 1 : 0];`
`var seriesOptions = options.series, userOptions = options;`

and at function end:
`return hasRenderToArg ?`
`                new Chart(renderTo, options, callback) :`
`                new Chart(options);`

**Comment by castortech** [comment]
Here are the changes that I made and this is working for me:

`var hasRenderToArg = typeof renderTo === 'string' || renderTo.nodeName, defaultOptions = H.getOptions(), defaultLinkedTo;`
`options = arguments[hasRenderToArg ? 1 : 0];`
`var seriesOptions = options.series, userOptions = options;`

and at function end:
`return hasRenderToArg ?`
`                new Chart(renderTo, options, callback) :`
`                new Chart(options, callback);`

**Comment by castortech** [comment]
Here is some heartbeat keep alive activity.

**Comment by raf18seb** [comment]
@castortech let us please close this ticket. It's been fixed since v9.1.0. Bisect didn't say which commit fixed it, but it's working fine in the newest version.
