### ISSUE TITLE
Error 17 in highcharts : Highcharts-more is not loading 

### ISSUE THREAD

**Issue by Sravani0804-git** [highcharts/highcharts#12702]
I was updated highcharts 6.1.1 version with 8.0.0. Then i got errors in highcharts. Charts are not loading. 
it is showing this message:
"**This error happens when setting chart.type or series.type to a series type that isn't defined in Highcharts. A typical reason may be that the module or extension where the series type is defined isn't included.
For example in order to create an arearange series, the highcharts-more.js file must be loaded**".  I downloaded highcharts-more, highcharts, highcharts-exporting.js files and i kept in define. But only highcharts file is loading but not highcharts-more and highcharts-exporting. How to load files.

**Comment by sebastianbochan** [comment]
Hi @Sravani0804-git,
The github is our bug trakcer, so for general [support](http://www.highcharts.com/support) cases, please use forum / stackoverflow or email.

Ps. please ensure that you load files in correct order (highcharts.js and then highcharts-more.js).

**Comment by Sravani0804-git** [comment]
I added in correct order only. Highcharts then highcharts-more,
highcharts-exportig, highcharts-accessbility. But only highcharts file is
loading. Script error is coming in my side when i try load charts. Could
you help me out this issue?

**Comment by sebastianbochan** [comment]
Hi @Sravani0804-git,
Please share a live demo of your chart and contact with us by one of support channels (forum / stackoverflow or email.
