### ISSUE TITLE
Chart.update() api does not align legend properly vertically, when font-size is changed

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#12705]
#### Expected behaviour
Chart.update() api should align legend properly vertically, when font-size is changed.

#### Actual behaviour
Chart.update() api when called with legend options with increased font-size, legend items gets vertically aligned to top. Ideally, it should vertically aligned in middle as the default case.

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/5phbxv9s/2/)

**Comment by pawelfus** [comment]
Thanks for reporting this issue @tejaspchordiya 

Comparison demo: https://jsfiddle.net/BlackLabel/n96c0bus/

**Comment by sebastianbochan** [comment]
_Internal note_
Can be related with https://github.com/highcharts/highcharts/issues/12683
