### ISSUE TITLE
Titles starting with `<` and ending with `>` are not shown

### ISSUE THREAD

**Issue by ipavlic** [highcharts/highcharts#12701]
#### Expected behaviour

Titles starting with `<` and ending with `>` are properly shown

#### Actual behaviour

Titles are not shown, likely due to some escaping/sanitizing

#### Live demo with steps to reproduce
https://jsfiddle.net/h74et1cx/4/

#### Product version
Highcharts 8.0.0

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @ipavlic ,
Thank you for reporting about the problem.

**Workaround**
You can use the HTML entities `&lt`; or `&gt;` instead of < >.

**Demo:**
- https://jsfiddle.net/BlackLabel/7h01sbad/

_Internal note_
Similar to the topic: #8892 / https://github.com/highcharts/highcharts/issues/10581

**Comment by pawelfus** [comment]
Actually it's a duplicate of #10581 - please check the explanation and solution in the ticket.

**Comment by sebastianbochan** [comment]
I missed that! Thanks Pawel!
