### ISSUE TITLE
Chart.update on regular pie chart to 3d

### ISSUE THREAD

**Issue by kai2468** [highcharts/highcharts#12714]
#### Expected behaviour

Pie chart changes from a regular pie chart to a 3d one.
Looks to be a regression as it used to work in v7:
https://jsfiddle.net/BlackLabel/1036gu2f/

#### Actual behaviour
Pie does not change over to a 3d version

#### Live demo with steps to reproduce
https://jsfiddle.net/35yqdcga/1/
Push the "Click me" button to try changing the pie chart to a 3d pie. It doesnt work.

#### Product version
Latest.

**Comment by pawelfus** [comment]
Bisected to commit af24cb21a1
