### ISSUE TITLE
Tooltip not inheriting 'dir' property on body

### ISSUE THREAD

**Issue by scottyk92** [highcharts/highcharts#12715]
#### Expected behaviour
When the 'dir' property of the <body> tag is set to 'rtl,' the table inside a tooltip should rendered as right to left, similar to how all the other child elements behave.

#### Actual behaviour
The table inside a tooltip should rendered as left to right even though the 'dir' property of the <body> tag is set to 'rtl.'

#### Live demo with steps to reproduce
https://jsfiddle.net/scottk92/0pbz4w7s/6/

Steps to reproduce:
1. Open up the JS Fiddle above.
2. Hover on any point in the chart to trigger the tooltip.

Notice how the table inside the tooltip does not follow a right-to-left flow. I created a table above the chart with the same markup; notice how that table does respect the right-to-left flow.

#### Product version
Highcharts 8.0.0

#### Affected browser(s)
Chrome version 78.0.3904.97.

**Comment by pawelfus** [comment]
Hi @scottyk92 

Thanks for reporting this issue. Even if this is a bug, it seems `dir="ltr"` is forced in Highcharts container for a reason.

**Workaround:**
Set in CSS:
```css
.highcharts-container div {
  direction: rtl;
}
```

**Comment by scottyk92** [comment]
Thanks @pawelfus, I didn't see that `dir="ltr"` was being hard coded onto the Highcharts container.
