### ISSUE TITLE
Split tooltip headers missing fill and stroke in styled mode

### ISSUE THREAD

**Issue by stephen-hannon** [highcharts/highcharts#12711]
#### Expected behaviour
In styled mode, the split tooltip header should look the same as it does without styled mode (translucent white fill, black stroke):
![image](https://user-images.githubusercontent.com/36610262/71684851-453ba780-2d5c-11ea-8937-91358c74499b.png)

Here is the behavior in styled mode, Highcharts 7.2.0 (https://jsfiddle.net/6yLtukfb/2/):
![image](https://user-images.githubusercontent.com/36610262/71686809-d9f4d400-2d61-11ea-89ee-5db9f1d8f9b2.png)

#### Actual behaviour
The tooltip is not styled at all:
![image](https://user-images.githubusercontent.com/36610262/71684963-99df2280-2d5c-11ea-8a76-b334c2529bcd.png)

I believe this is a regression caused by #12150. Perhaps the fix is as simple as adding the class `highcharts-tooltip-box` in addition to `highcharts-tooltip-header`?

#### Live demo with steps to reproduce

* Go to https://jsfiddle.net/6yLtukfb/1/
* Hover over points and see that the tooltip header in the x-axis is not properly styled.
* Comment out `styledMode: true` and the CSS import, re-run, and see that it is styled as expected.

#### Product version

Highcharts 8.0.0

#### Affected browser(s)
Chrome 79, Firefox 71, probably others

**Comment by pawelfus** [comment]
Thanks for reporting this bug @stephen-hannon - you are right, bisected to commit: ca5ba96d8f which refers to #12150.
