### ISSUE TITLE
change tooltip depend on mouse action 

### ISSUE THREAD

**Issue by khoramshahy** [highcharts/highcharts#12728]
hey guys
Is there a way to detect the mouse action in tooltip section.
In my case I want to show some info about specific point when the mouse is hover on it and then show a menu(including some options) when user clicks on the specific point. so I'm looking for a way to detect mouse action the tooltip formatter section or maybe is there a way to define multiple tooltips and use each one in specific mouse action?

**Comment by sebastianbochan** [comment]
Hi @khoramshahy,
The github is our bug tracker, so for general [support](http://www.highcharts.com/support) questions please use stackoverflow / forum or email.

ps. you can use the [custom-events](https://github.com/blacklabel/custom_events/) extension and catch i.e right click and then show your custom menu.

**Comment by khoramshahy** [comment]
Ok 
thanks Sebastian
