### ISSUE TITLE
HighCharts 3D Pie - how to control which data labels get omitted when size is too small?

### ISSUE THREAD

**Issue by egloffmark** [highcharts/highcharts#12725]
#### Expected behaviour
I like to control for which value thresholds the data labels get omitted when the diagram space get narrowed. See the two pictures below. 

![Selection_018](https://user-images.githubusercontent.com/7382336/71840762-3f2c2a80-30be-11ea-8a30-e94be8bdf18d.png)
![Selection_019](https://user-images.githubusercontent.com/7382336/71840769-42bfb180-30be-11ea-9ea5-ffd0625a300a.png)

So far I only found the option "padding" and "crop". However none of them allows me to enforce that all labels get shown.

- Is there a way to enforce that all data labes get shown with the risk that it is no longer readable?
- Is there a possibility that a threshold can be set? i.e. for values below 1%? 
- Exists the possibility to change the data label font size and to update it dynamically?

#### Steps to reproduce

current example chart options
```
       chartOptions: {
          colors: [
            '#d65db1', '#7798BF','#845ec2',  '#ff6f91', '#ff9671','#ffc75f',
            '#f9f871', '#fbeaff', '#c4fcef','#008f7a', '#00c9a7', '#008e9b'
            ,'#b39cd0', '#f45b5b', '#8085e9', '#8d4654',
            '#7798BF', '#aaeeee', '#ff0066', '#eeaaee', '#55BF3B',
            '#DF5353', '#7798BF', '#aaeeee',
            ],
          title: {
            text: ''
          },
          tooltip: {
            formatter: function () {
              return '<b>' + this.point.name + '</b>: ' + this.percentage.toFixed(2) + ' %';
            }
          },
          chart: {
            type: 'pie',
            height: '36%',
            options3d: {
              enabled: true,
              alpha: 45,
            },
          },
          series: [{
            name: '',
            data: [...],
            tooltip: {
              valueDecimals: 0
            },
            animation: false

          }],
          plotOptions: {
            pie: {
              allowPointSelect: true,
              cursor: 'pointer',
              innerSize: '30%',
              depth: 50,
              dataLabels: {
                allowOverlap: true,
                crop:false,
                padding: 0,
                enabled: true,
                percentageDecimals: 2,
                color: '#002a52',
                connectorColor: '#002a52',
                formatter: function () {
                  return '<b>' + ((this.point.name.charAt(1) == ' ' || this.point.name.charAt(1) == ':') ? this.point.name.charAt(0) : this.point.name)  + '</b>: ' + this.percentage.toFixed(2) + ' %';
                }
              }
            }
          },
          responsive: {
            rules: [{
              condition: {
                maxWidth: 450
              },
              chartOptions: {
                plotOptions: {
                  pie: {
                    depth: 25
                  }
                }
              }
            }]
          },
          credits: {
            enabled: false
          },
          exporting: {
            buttons: {
              printButton: {
                enabled: false
              },
              contextButton: {
                enabled: false
              }
            }
          },
        }
```
#### Product version
Current latest available versions
```
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
```

#### Affected browser(s)

Tested with Firefox and Chrome

**Comment by pawelfus** [comment]
Hi @egloffmark 

Thanks for choosing Highcharts! Note that you posted on our bugtracker - for questions, please other support channels: https://www.highcharts.com/blog/support/

> Is there a way to enforce that all data labes get shown with the risk that it is no longer readable?

When two labels overlap, the one with the lowest [`labelrank`](https://api.highcharts.com/highcharts/series.pie.data.labelrank) is always hidden.

> Is there a possibility that a threshold can be set? i.e. for values below 1%?

Yes, you can use [`pie.dataLabels.formatter`](https://api.highcharts.com/highcharts/series.pie.dataLabels.formatter) or [`pie.dataLabels.filter`](https://api.highcharts.com/highcharts/series.pie.dataLabels.filter).

> Exists the possibility to change the data label font size and to update it dynamically?

Each point can have it's own `dataLabels` configuration, that includes font-size etc. You can also define [`responsive`](https://api.highcharts.com/highcharts/responsive) options to apply different options for different screen/chart sizes.

PS: Did you consider using different chart type? There's a limit how much a pie chart can show.

**Comment by egloffmark** [comment]
> PS: Did you consider using different chart type? There's a limit how much a pie chart can show.

Can you elaborate here more what you mean on this "limit"?

**Comment by pawelfus** [comment]
Hi @egloffmark 

I mean general rules for creating charts - human perception limit. Rendering 360points in pie chart is simply a bad idea: https://jsfiddle.net/BlackLabel/npktdymL/ Personally I think the upper limit is ~10categories.

You can read more on our blog post: https://www.highcharts.com/blog/tutorials/what-chart-to-use-when-your-data-adds-up-to-100/
