### ISSUE TITLE
Highmaps: switching between tween and category dataClassColor

### ISSUE THREAD

**Issue by mari-pwbm** [highcharts/highcharts#12726]
#### Expected behaviour
Map changes back to having a "tween" color axis with a min and max from a color axis with data classes.

#### Actual behaviour
Map color axis remains the same even when switching from category dataClassColor to tween.

#### Live demo with steps to reproduce
Click "Update chart" button to toggle from tween to category and once more to toggle back. First toggle works, second does not.
[https://jsfiddle.net/27mwLqn3/2/](https://jsfiddle.net/27mwLqn3/2/)

(version toggling between tween and tween: [https://jsfiddle.net/27mwLqn3/3/](https://jsfiddle.net/27mwLqn3/3/))
(version toggling between category and category: [https://jsfiddle.net/27mwLqn3/4/](https://jsfiddle.net/27mwLqn3/4/))

#### Product version

Highmaps 8.0.0

#### Affected browser(s)
At least Chrome and Firefox

**Comment by pawelfus** [comment]
Hi @mari-pwbm 

Thanks for reporting the issue. You don't remove old dataClasses, so those are still valid, please consider this demo: https://jsfiddle.net/BlackLabel/wzk5capm/ - it works without issues.
