### ISSUE TITLE
Mousing over tooltip should not dismiss it, move it, or change points.

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#12736]
#### Expected behaviour
Hover content, such as tooltips, are required by WCAG 2.1 to be persistent when hovered over. When hovering over the tooltip content, the tooltip should stay in place. This has several use cases, but particularly helps users of magnification tools.

#### Actual behaviour
Currently, if hovering over the tooltip causes the mouse pointer to be closer to a different point, the tooltip will move to that point instead.

#### Suggested improvement
Keep the tooltip fixed when mousing over it.

With this behavior, the tooltip may block access to points beneath it. We may want to allow the tooltip to be closed by clicking it, or add a close icon on tooltip hover.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-basic/

Hover over the "Other" series, and try to hover over the tooltip. The tooltip will move to the above series.

**Comment by pawelfus** [comment]
Just an idea: clicking on a point (that has tooltip displayed) will stick tooltip to that point until clicked again (on the same or another point).

**Comment by oysteinmoseng** [comment]
@pawelfus This could be a useful feature, but in order to comply with WCAG we would not be allowed to require additional interaction for this feature. It would be hard for users to know that a click is required to keep the tooltip in place. I also imagine it could be troublesome with charts that already have point click events, either custom or drilldown.

But if we implement a tooltip.stay/freeze/stick() function or similar, we could allow users to call this function on point click events.

**Comment by TorsteinHonsi** [comment]
I think we need to make this optional. Tests will show, but it may completely block the current user experience when dragging the finger/mouse across a line chart and the tooltip follows.

**Comment by oysteinmoseng** [comment]
Making it optional should not be an issue, but it should probably be enabled by default at least when loading the a11y module
