### ISSUE TITLE
Switch to named import/export and ES6 class pattern

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#12738]
Before we can compile the masters in TypeScript, we have to switch the sources to named import/export, so that a partial namespace is not a problem anymore.

- [x] Accessibility
- [x] Core/Axis/Axis
- [x] Core/Axis/Axis3D
- [x] Core/Axis/BrokenAxis
- [x] Core/Axis/ColorAxis
- [x] Core/Axis/DateTimeAxis
- [x] Core/Axis/GridAxis
- [x] Core/Axis/HiddenAxis
- [x] Core/Axis/LogarithmicAxis
- [x] Core/Axis/MapAxis
- [x] Core/Axis/NavigatorAxis
- [x] Core/Axis/OrdinalAxis
- [x] Core/Axis/PlotLineOrBand
- [x] Core/Axis/RadialAxis
- [x] Core/Axis/ScrollbarAxis
- [x] Core/Axis/StackingAxis
- [x] Core/Axis/Tick
- [x] Core/Axis/Tick3D
- [x] Core/Axis/TreeGridAxis
- [x] Core/Axis/TreeGridTick
- [x] Core/Axis/VMLAxis3D
- [x] Core/Axis/ZAxis
- [x] Core/Chart/Chart
- [x] Core/Chart/Chart3D
- [x] Core/Chart/GanttChart
- [x] Core/Chart/StockChart
- [x] Core/Color
- [x] Core/Globals
- [x] Core/Legend
- [x] Core/MSPointer
- [x] Core/Navigator
- [x] Core/Options (a bit tricky, similar to Utilities)
- [x] Core/Pointer
- [x] Core/Renderer/HTML
- [x] Core/Renderer/SVG/SVGElement
- [x] Core/Renderer/SVG/SVGLabel
- [x] Core/Renderer/SVG/SVGPath
- [x] Core/Renderer/SVG/SVGRenderer
- [x] Core/Renderer/SVG/SVGRenderer3D
- [x] ~Core/Responsive~
- [x] Core/Scrollbar
- [x] Core/Series/DataLabels
- [x] Core/Series/Point
- [x] Core/Series/Series3D
- [x] Core/Time
- [x] Core/Tooltip
- [x] Core/Utilities
- [x] Extensions/Annotations
- [x] Extensions/Annotations/ControlPoint
- [x] Extensions/Annotations/MockPoint
- [x] Extensions/Annotations/NavigationBindings
- [x] Extensions/Annotations/Controllables/ControllableCircle
- [x] Extensions/Annotations/Controllables/ControllableImage
- [x] Extensions/Annotations/Controllables/ControllableLabel
- [x] Extensions/Annotations/Controllables/controllableMixin
- [x] Extensions/Annotations/Controllables/ControllablePath
- [x] Extensions/Annotations/Controllables/ControllableRect
- [x] Extensions/Annotations/Controllables/markerMixin
- [x] Extensions/Annotations/Types/BasicAnnotation
- [x] Extensions/Annotations/Types/CrookedLine
- [x] Extensions/Annotations/Types/ElliotWave
- [x] Extensions/Annotations/Types/Fibonacci
- [x] Extensions/Annotations/Types/InfinityLine
- [x] Extensions/Annotations/Types/Measure
- [x] Extensions/Annotations/Types/Pitchfork
- [x] Extensions/Annotations/Types/Tunnel
- [x] Extensions/Annotations/Types/VerticalLine
- [x] Extensions/ArrowSymbols
- [x] Extensions/Boost
- [x] Extensions/BoostCanvas
- [x] Extensions/CurrentDateIndicator
- [x] Extensions/Data
- [x] Extensions/DataGrouping
- [x] Extensions/Debugger
- [x] Extensions/DragPanes
- [x] Extensions/DraggablePoints
- [x] Extensions/Drilldown
- [x] Extensions/ExportData
- [x] Extensions/Exporting
- [x] Extensions/FullScreen
- [x] Extensions/GeoJSON
- [x] Extensions/Math3D
- [x] Extensions/MarkerClusters
- [x] Extensions/Mixins/Ajax
- [x] Extensions/Mixins/CenteredSeries
- [x] Extensions/Mixins/ColorMapSeriesMixin
- [x] Extensions/Mixins/ColorSeriesMixin
- [x] Extensions/Mixins/DerivedSeries
- [x] Extensions/Mixins/DownloadURL
- [x] Extensions/Mixins/DrawPoint
- [x] Extensions/Mixins/Geometry
- [x] Extensions/Mixins/GeometryCircles
- [x] Extensions/Mixins/IndicatorRequired
- [x] Extensions/Mixins/LegendSymbol
- [x] Extensions/Mixins/MultipleLines
- [x] Extensions/Mixins/Navigation
- [x] Extensions/Mixins/NelderMead
- [x] Extensions/Mixins/Nodes
- [x] Extensions/Mixins/OnSeries
- [x] Extensions/Mixins/Polygon
- [x] Extensions/Mixins/ReduceArray
- [x] Extensions/Mixins/TreeSeries
- [x] Extensions/Mixins/LegendSymbol
- [x] Extensions/NoDataToDisplay
- [x] Extensions/OfflineExporting
- [x] Extensions/OldiePolyfills
- [x] Extensions/Oldie
- [x] Extensions/OverlappingDataLabels
- [x] Extensions/Pane
- [x] Extensions/ParallelCoordinates
- [x] Extensions/PatternFill
- [x] Extensions/Polar
- [x] Extensions/PriceIndication
- [x] Extensions/RangeSelector
- [x] Extensions/ScrollablePlotArea
- [x] Extensions/SeriesLabel
- [x] Extensions/Sonifcation
- [x] Extensions/Stacking
- [x] Extensions/StaticScale
- [x] Gantt/Pathfinder
- [x] Gantt/PathfinderAlgorithms
- [x] Gantt/Tree
- [x] Maps/Map
- [x] Maps/MapNavigation
- [x] Maps/MapPointer
- [x] Series/Area/AreaSeries
- [x] Series/AreaRange/AreaRangeSeries
- [x] Series/AreaSpline/AreaSplineSeries
- [x] Series/AreaSplineRange/AreaSplineRangeSeries
- [x] Series/Bar/BarSeries
- [x] Series/Bellcurve/BellcurveSeries
- [x] Series/BoxPlot/BoxPlotSeries
- [x] Series/Bubble/BubbleLegend
- [x] Series/Bubble/BubbleSeries
- [x] Series/Bullet/BulletSeries
- [x] Series/Candlestick/CandlestickSeries
- [x] Series/Column/ColumnSeries
- [x] Series/Column3D/Column3DSeries
- [x] Series/ColumnPyramid/ColumnPyramidSeries
- [x] Series/ColumnRange/ColumnRangeSeries
- [x] Series/Cylinder/Cylinder
- [x] Series/Dependency/DependencyWheelSeries
- [x] Series/Dotplot/DotplotSeries
- [x] Series/Dumbbell/DumbbellSeries
- [x] Series/Error/ErrorBarSeries
- [x] Series/Flags/FlagsSeries
- [x] Series/Funnel3D/Funnel3DSeries
- [x] Series/Funnel/FunnelSeries
- [x] Series/Gantt/GanttSeries
- [x] Series/Gauge/GaugeSeries
- [x] Series/Heatmap/HeatmapSeries
- [x] Series/Histogram/HistogramSeries
- [x] Series/Item/ItemSeries
- [x] Series/Line/LineSeries
- [x] Series/Lollipop/LollipopSeries
- [x] Series/MapBubble/MapBubbleSeries
- [x] Series/MapLine/MapLineSeries
- [x] Series/MapPoint/MapPointSeries
- [x] Series/Map/MapSeries
- [x] Series/Networkgraph/NetworkgraphSeries
- [x] Series/OHLC/OHLCSeries
- [x] Series/Organization/OrganizationSeries
- [x] Series/PackedBubble/PackedBubbleSeries
- [x] Series/Pareto/ParetoSeries
- [x] Series/Pie/PieSeries
- [x] Series/Pie3D/Pie3DSeries
- [x] Series/Polygon/PolygonSeries
- [x] Series/Pyramid/Pyramid3D
- [x] Series/Pyramid3D/Pyramid3DSeries
- [x] Series/Sankey/SankeySeries
- [x] Series/Scatter/ScatterSeries
- [x] Series/Scatter3D/Scatter3DSeries
- [x] Series/SolidGauge/SolidGaugeSeries
- [x] Series/Spline/SplineSeries
- [x] Series/Steamgraph/SteamgraphSeries
- [x] Series/Sunburst/SunburstSeries
- [x] Series/Tilemap/TilemapSeries
- [x] Series/Timeline/TimelineSeries
- [x] Series/Treemap/TreemapSeries
- [x] Series/VariablePie/VariablePieSeries
- [x] Series/Variwide/VariwideSeries
- [x] Series/Vector/VectorSeries
- [x] Series/Venn/VennSeries
- [x] Series/Waterfall/WaterfallSeries
- [x] Series/Windbarb/WindbarbSeries
- [x] Series/Wordcloud/WordcloudSeries
- [x] Series/XRange/XRangeSeries
- [x] Stock/Indicators/ABandsIndicator
- [x] Stock/Indicators/ADIndicator
- [x] Stock/Indicators/AOIndicator
- [x] Stock/Indicators/APOIndicator
- [x] Stock/Indicators/ATRIndicator
- [x] Stock/Indicators/AroonIndicator
- [x] Stock/Indicators/AroonOscillatorIndicator
- [x] Stock/Indicators/BBIndicator
- [x] Stock/Indicators/CCIIndicator
- [x] Stock/Indicators/CMFIndicator
- [x] Stock/Indicators/ChaikinIndicator
- [x] Stock/Indicators/DEMAIndicator
- [x] Stock/Indicators/DPOIndicator
- [x] Stock/Indicators/EMAIndicator
- [x] Stock/Indicators/IKHIndicator
- [x] Stock/Indicators/IndicatorLike
- [x] Stock/Indicators/IndicatorValuesObject
- [x] Stock/Indicators/KeltnerChannelsIndicator
- [x] Stock/Indicators/MACDIndicator
- [x] Stock/Indicators/MFIIndicator
- [x] Stock/Indicators/MomentumIndicator
- [x] Stock/Indicators/NATRIndicator
- [x] Stock/Indicators/PCIndicator
- [x] Stock/Indicators/PPOIndicator
- [x] Stock/Indicators/PSARIndicator
- [x] Stock/Indicators/PivotPointsIndicator
- [x] Stock/Indicators/PriceEnvelopesIndicator
- [x] Stock/Indicators/ROCIndicator
- [x] Stock/Indicators/RSIIndicator
- [x] Stock/Indicators/RegressionIndicators
- [x] Stock/Indicators/RequireIndicatorsResultObject
- [x] Stock/Indicators/SMAIndicator
- [x] Stock/Indicators/SlowStochasticIndicator
- [x] Stock/Indicators/StochasticIndicator
- [x] Stock/Indicators/SupertrendIndicator
- [x] Stock/Indicators/TEMAIndicator
- [x] Stock/Indicators/TRIXIndicator
- [x] Stock/Indicators/TrendLineIndicator
- [x] Stock/Indicators/VBPIndicator
- [x] Stock/Indicators/VWAPIndicator
- [x] Stock/Indicators/WMAIndicator
- [x] Stock/Indicators/WilliamsRIndicator
- [x] Stock/Indicators/ZigzagIndicator
- [x] Stock/StockToolsBindings
- [x] Stock/StockToolsGui

**Comment by bre1470** [comment]
The following technique helps with the series migration. You can move every series function one by one and test in between, if something breaks:
```ts
class SomeSeries extends ParentSeries {
  public static defaultOptions = merge(ParentSeries.defaultOptions, {
    // some options
  });
  // here are the functions after movement
  // you can use super instead of seriesTypes.parent like
  public init(): void {
    super.init.apply(this, arguments as any);
  }
}
interface SomeSeries extends ParentSeries {
  // here are the class definitions taken from Highcharts namespace
}
extend(
  SomeSeries.prototype,
  {
    // here are the functions before movement (like in the seriesType factory)
    // properties from the factory will stay here and not be moved,
    // because they need to be on the prototype (not instance)
  }
);
Series.addSeries('some', SomeSeries);
```

Excerpt from https://github.com/highcharts/highcharts/pull/14377

**Comment by bre1470** [comment]
This part is done, but does not make it compatible to tree shaking. Additional work has to be done related to issue #8667.

**Comment by hakimio** [comment]
@bre1470 It's already possible to save a lot by using [custom master files](https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files) which only imports from `highcharts/es-modules`. Thank you for your work 👍
