### ISSUE TITLE
Highstock navigator RTL

### ISSUE THREAD

**Issue by behnam7171** [highcharts/highcharts#12748]
#### Expected behaviour
I could not find any RTL functionallity for navigator. when set opposite option to true, it just made UI inconsistent when my chart is not inverted. is there any option that I can mirror the navigation? for example dates increase from right to left in navigator

#### Actual behaviour
I could not find any RTL/Mirroring functionallity for navigator.

#### Live demo with steps to reproduce
https://jsfiddle.net/qhy6p7kb/1/

#### Product version
version 6.0.4 & 8.0.0 have this bug

#### Affected browser(s)
generated in chrome version 79

**Comment by pawelfus** [comment]
Hi @behnam7171 

You need `xAxis.reversed` and `navigator.xAxis.reversed` options, take a look: https://jsfiddle.net/BlackLabel/gnukesc4/

PS: You posted on our bug tracker - for questions, please use other support channels: https://www.highcharts.com/blog/support/
