### ISSUE TITLE
yAxis title does not render in scatter chart when running Node Export on Windows

### ISSUE THREAD

**Issue by MikeYeager** [highcharts/highcharts#12758]
#### Expected behaviour
Both xAxis and yAxis titles render properly on scatter charts on Linux and Windows servers.

#### Actual behaviour
Artifacts of the title on the xAxis can sometimes be seen, depending on the letters used in the title. Adjusting properties such as rotation and offset show the artifacts moving as they're adjusted, but the majority of the text is not visible. The xAxis title renders properly.

#### Live demo with steps to reproduce
I'm using PostMan to test. It works the same with curl. When I hit your server (or use JSFiddle), it works as expected. When I hit our server created with the source code for v2.0.27 (have also tried v2.0.17) running on Windows in Azure as an Azure App Service, everything works except the yAxis title does not render properly. Our server is hosted at: https://treadstatchartservicedev.azurewebsites.net 

Please note that Windows does not come with the default Lucida Grande font installed and the server does not fall back to the other fonts. We have to set fontFamily: Arial for the chart to get any text to show up at all. This is a separate issue, but since we have a work-around, we're haven't submitted an issue for it. Unfortunately, we can't run on Linux in this particular instance and we appreciate you supporting Windows.

Here is a sample chart where the yAxis title does not show:
{
	"infile": {
		"chart": {
			"type": "scatter",
			"zoomType": "xy",
			"style": {
				"fontFamily": "Arial","fontSize":"12px"
			}
		},
		"title": {
			"text": null
		},
		"exporting": {
			"enabled": false
		},
		"credits": {
			"enabled": false
		},
		"xAxis": {
			"title": {
				"enabled": true,
				"text": ["Hours"]
			},
			"startOnTick": true,
			"endOnTick": true,
			"showLastLabel": true
		},
		"yAxis": {
			"title": {
				"enabled": true,
				"text": ["Days"]
			}
		},
		"legend": {
			"layout": "horizontal",
			"align": "left",
			"verticalAlign": "top",
			"x": 10,
			"y": 5,
			"borderWidth": 0.01,
			"symbolPadding": 2,
			"symbolWidth": 8,
			"itemWidth": 90,
		
			"rtl": true
		},
		"plotOptions": {
			"scatter": {
				"marker": {
					"radius": 2
				}
			}
		},
		"series": [{
				"name": "24.00R35 YO RB42",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[78, 77], [267, 76], [460, 76], [724, 73], [896, 71], [1169, 68], [1473, 65], [2448, 56], [2706, 49], [839, 48], [1099, 38], [292, 68], [554, 60], [820, 50], [56, 80], [704, 75], [798, 74], [1084, 73], [1358, 72], [1750, 69], [1899, 69], [2095, 68], [2365, 64], [2553, 62], [2825, 60], [3079, 58], [3667, 44], [3937, 42], [4185, 38], [23, 79], [281, 73], [548, 70], [1223, 55], [1437, 48], [1690, 46], [292, 64], [554, 57], [820, 48], [839, 50], [1099, 42], [67, 78], [0, 88], [221, 78], [499, 72], [711, 70], [955, 68], [1250, 64], [1921, 57], [2191, 56], [2439, 53], [235, 68], [497, 59], [763, 51], [235, 68], [497, 62], [763, 50], [0, 88], [221, 76], [499, 72], [711, 70], [955, 68], [1250, 61], [1921, 51], [2191, 48], [2439, 42], [514, 70], [776, 66], [1042, 63], [56, 80], [704, 74], [798, 72], [1084, 70], [1358, 68], [1750, 64], [1899, 64], [2095, 62], [2365, 59], [2553, 54], [2825, 53], [3079, 48], [3667, 34], [3937, 32], [4185, 31], [898, 46], [1158, 35], [23, 79], [281, 74], [548, 73], [1223, 58], [1437, 54], [1690, 50], [514, 72], [776, 70], [1042, 67], [67, 78], [42, 78], [115, 78], [229, 76], [496, 74], [685, 73], [878, 72], [1142, 70], [1314, 65], [1587, 63], [1891, 60], [2866, 52], [3124, 50], [65, 78], [898, 49], [1158, 37], [65, 78]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[78, 77], [65, 78]]
			}, {
				"name": "26.5-25 YO Y545",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[0, 86], [272, 80], [796, 78], [1491, 76], [1599, 76], [1605, 76], [2110, 72], [2493, 72], [2526, 72], [2719, 70], [2926, 68], [0, 86], [272, 80], [796, 77], [1491, 77], [1599, 75], [1605, 75], [2110, 72], [2493, 70], [2526, 70], [2719, 70], [2926, 70], [0, 86], [272, 80], [796, 80], [1491, 78], [1599, 76], [1605, 76], [2110, 74], [2493, 71], [2526, 71], [2719, 69], [2926, 69], [0, 86], [272, 80], [796, 80], [1491, 78], [1599, 78], [1605, 78], [2110, 75], [2493, 72], [2526, 72], [2719, 72], [2926, 72]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[0, 86], [2926, 72]]
			}, {
				"name": "26.5R25 NW #16",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[205, 18]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[205, 18], [205, 18]]
			}, {
				"name": "26.5R25 TI STL3",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[205, 20], [35, 48], [164, 44], [291, 43], [690, 41], [831, 40], [1010, 38], [1250, 36], [1484, 36], [1630, 35], [2488, 29], [2842, 27]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[205, 20], [2842, 27]]
			}, {
				"name": "26.5R25 YO RB31",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[205, 33]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[205, 33], [205, 33]]
			}, {
				"name": "29.5-25 YO Y545",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[1740, 84], [3613, 68], [7186, 52], [1354, 84], [2099, 79], [855, 84], [2228, 78], [3230, 74], [5220, 61], [6192, 56], [7000, 50], [8129, 46], [488, 88], [974, 86], [2542, 78], [3041, 76], [3271, 76], [3833, 72], [855, 87], [2228, 77], [3230, 73], [5220, 56], [6192, 48], [7000, 42], [8129, 38], [1740, 79], [3613, 68], [7186, 52], [855, 88], [2228, 80], [3230, 76], [5220, 65], [6192, 60], [7000, 58], [8129, 52], [488, 86], [974, 84], [2542, 76], [3041, 75], [3271, 74], [3833, 72], [855, 86], [2228, 80], [3230, 75], [5220, 58], [6192, 52], [7000, 44], [8129, 40], [411, 88], [1479, 84], [2981, 74], [4820, 62], [6675, 51], [7431, 49], [8085, 44], [9228, 43], [1740, 77], [3613, 58], [7186, 37], [411, 88], [1479, 83], [2981, 72], [4820, 61], [6675, 52], [7431, 50], [8085, 48], [9228, 45], [411, 88], [1479, 83], [2981, 72], [4820, 59], [6675, 48], [7431, 46], [8085, 42], [9228, 40], [411, 88], [1479, 84], [2981, 76], [4820, 67], [6675, 59], [7431, 56], [8085, 54], [9228, 45], [488, 85], [974, 83], [2542, 75], [3041, 72], [3271, 72], [3833, 69], [1354, 80], [2099, 76], [1354, 82], [2099, 78], [1740, 82], [3613, 66], [7186, 46], [1354, 82], [2099, 80], [488, 88], [974, 87], [2542, 80], [3041, 78], [3271, 76], [3833, 75]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[1740, 84], [3833, 75]]
			}, {
				"name": "35/65-33 NW #30",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[705, 68], [991, 65], [1273, 65], [1730, 60], [1893, 58], [2243, 56], [2559, 50], [3623, 36], [3955, 34], [0, 79], [917, 72], [2292, 60], [2692, 56], [3136, 53], [3533, 52], [3557, 52], [4350, 40], [4415, 40], [4566, 38], [4912, 29], [5586, 22], [6059, 20], [6549, 16], [7047, 16], [7558, 12], [0, 79], [917, 74], [2292, 61], [2692, 58], [3136, 55], [3533, 48], [3557, 48], [4350, 42], [4415, 42], [4566, 42], [4912, 40], [5586, 30], [6059, 30], [6549, 20], [7047, 20], [7558, 20], [705, 68], [991, 64], [1273, 64], [1730, 60], [1893, 60], [2243, 60], [2559, 54], [3623, 44], [3955, 38]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[705, 68], [3955, 38]]
			}, {
				"name": "35/65-33 NW #30 L-4",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[76, 74], [669, 61], [1337, 58], [245, 70], [452, 69], [878, 64], [1315, 64], [2123, 57], [2204, 55], [2484, 55], [245, 68], [452, 68], [878, 64], [1315, 56], [2123, 50], [2204, 43], [2484, 43]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[76, 74], [2484, 43]]
			}, {
				"name": "35/65-33 YO Y545",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[245, 71], [452, 66], [878, 59], [1315, 52], [2123, 44], [2204, 36], [2484, 28], [245, 68], [452, 64], [878, 51], [1315, 50], [2123, 35], [2204, 34], [2484, 22], [86, 74], [110, 74], [903, 66], [968, 64], [1119, 58], [1465, 51], [2139, 44], [2612, 40], [3102, 32], [3600, 30], [4111, 29], [76, 74], [669, 65], [1337, 60], [76, 74], [669, 66], [1337, 62], [86, 74], [110, 74], [903, 67], [968, 64], [1119, 57], [1465, 47], [2139, 40], [2612, 32], [3102, 27], [3600, 24], [4111, 22]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[245, 71], [4111, 22]]
			}, {
				"name": "35/65R33 BS VSNT",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[61, 78], [449, 70], [880, 64], [1266, 58], [1675, 52], [2577, 36], [2940, 31], [4025, 26], [4357, 23]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[61, 78], [4357, 23]]
			}, {
				"name": "35/65R33 MI XTXL",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[1172, 59], [1619, 55], [2092, 48], [1172, 58], [1619, 56], [2092, 51]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[1172, 59], [2092, 51]]
			}, {
				"name": "35/65R33 NW #30",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[3, 80], [468, 68], [751, 66], [1116, 60], [1546, 52], [2777, 50], [3224, 40], [3697, 25], [76, 75], [669, 71], [1337, 68], [3, 80], [468, 76], [751, 74], [1116, 72], [1546, 70], [2777, 60], [3224, 52], [3697, 52]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[3, 80], [3697, 52]]
			}, {
				"name": "35/65R33 NW L4",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[482, 76], [926, 74], [1413, 71], [1540, 66], [2711, 60], [3359, 56], [4264, 51], [4643, 47], [4925, 44], [5294, 40], [5967, 38], [6062, 33], [6727, 28], [7558, 21], [7890, 12]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[482, 76], [7890, 12]]
			}, {
				"name": "35/65R33 NW L4",
				"type": "scatter",
				"showInLegend": true,
				"siteName": null,
				"data": [[482, 76], [926, 74], [1413, 71], [1540, 66], [2711, 60], [3359, 56], [4264, 51], [4643, 47], [4925, 44], [5294, 40], [5967, 38], [6062, 33], [6727, 28], [7558, 21], [7890, 12]]
			}, {
				"name": "",
				"type": "line",
				"showInLegend": true,
				"siteName": null,
				"data": [[482, 76], [7890, 12]]
			}
		]
	}
}

#### Product version
HighCharts Node Export (on Windows) v2.0.27

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @MikeYeager 

Thanks for reporting, but this is wrong repo :) Please report the issue in Highcharts Node.js export server: https://github.com/highcharts/node-export-server

Did you follow setup for fonts? See: https://github.com/highcharts/node-export-server#installing-fonts

**Comment by MikeYeager** [comment]
Apologies for the mis-post and thanks for your quick response. We've deployed to Azure App Services, so we're not able to add any fonts to the server, we have to use what's available.
Cheers!
