### ISSUE TITLE
Incorrectly named provinces on the Afghanistan map

### ISSUE THREAD

**Issue by harmananm** [highcharts/highcharts#12757]
### Issue:
The Afghanistan map has two misnamed provinces:
- The Daykundi province is incorrectly named as Uruzgan, which already exists; this results in two duplicate Uruzgan provinces
- The Panjshir province is incorrectly named as Parwan, which also already exists. 

![image](https://user-images.githubusercontent.com/50335756/72084379-0bdedb00-330c-11ea-96ae-b32af512da55.png)

### Cause:
As I understand it, the issue stems from this file: https://code.highcharts.com/mapdata/countries/af/af-all.js. 

### Live demo:
- https://jsfiddle.net/gh/get/library/pure/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/af/af-all.

**Comment by pawelfus** [comment]
Hi @harmananm 

Thanks for reporting. Unfortunately, this is wrong repo to report this issue. Could you please report this here: https://github.com/highcharts/map-collection-dist/issues ? Thanks!
