### ISSUE TITLE
Histogram binWidth does not apply

### ISSUE THREAD

**Issue by kennyjwilli** [highcharts/highcharts#12759]
#### Expected behaviour
The number of bins set by the property `binWidth` appear in the chart.

#### Actual behaviour
The default number of bins are used.

#### Live demo with steps to reproduce
https://jsfiddle.net/rj8mxgsw/

The demo has `binWidth` set to `20`.

1. Comment out `binWidth` & run
2. Note the chart is identical to when the `binWidth` property was set. 

#### Product version
v8.0.0

#### Affected browser(s)
Tested on Chrome 79.0.3945.88

**Comment by kennyjwilli** [comment]
`binsNumber` also does not appear to change the chart: https://jsfiddle.net/rj8mxgsw/75/. Perhaps some other setting needs to be set?

**Comment by pawelfus** [comment]
Hi @kennyjwilli 

Thanks for reporting the issue. This is not how you should define histogram series, please take a look: https://jsfiddle.net/BlackLabel/ucxoy189/ - histogram requires another series that can use as a base calculation and shouldn't provide `data` options.

Note that for your dataset `binWidth=20` is huge. Data set has points in range <0, 3>, so `binWidth` like `0.5` is more likely to use: https://jsfiddle.net/BlackLabel/qejhmr31/

If something is not clear, or you have more questions, please our other support channels: https://www.highcharts.com/blog/support/

**Comment by kennyjwilli** [comment]
I saw that example and noted that it did work. It just seemed so strange to require a second series to display a histogram that I thought this had to be a bug. Is there a technical reason for this? I imagine most often users would like to see a histogram without the data overlaid on top. Certainly worth adding a note in the [documentation](https://www.highcharts.com/docs/chart-and-series-types/histogram-series) of needing to set `visible: false` to display a histogram without a scatter plot and that the second series is **required**.

**Comment by pawelfus** [comment]
> Is there a technical reason for this?

Yes, there's a few reasons why it's designed that way. Histogram series is just one of many derived-data series. Series that don't use their own `data`, but rather use other series for some calculations. I understand you prefer different config, perhaps more natural for you, but for anyone who actually wants to display the main series this is the best solution - amount of data passed onto the chart is reduced. It would be confusing if `data` would be available for that types of series.

> Certainly worth adding a note in the documentation of needing to set visible: false to display a histogram without a scatter plot and that the second series is required.

I believe it's pretty well described under [**How to create a Histogram**](https://www.highcharts.com/docs/chart-and-series-types/histogram-series#how-to-create-a-histogram) with a minimal example: 

![Screen Shot 2020-01-13 at 10 48 07](https://user-images.githubusercontent.com/1453926/72246058-370a4880-35f2-11ea-9f82-9f43fd4151cd.png)
