### ISSUE TITLE
It doesn't show what it's supposed to look like

### ISSUE THREAD

**Issue by Merely-chao** [highcharts/highcharts#12760]
#### Expected behaviour
The two Y-axis points are equal

#### Actual behaviour
The two Y-axis points are not equal

#### Live demo with steps to reproduce

https://jshare.com.cn/temp/RJGrnc
#### Product version

8.0.0

**Comment by sebastianbochan** [comment]
Hi @Merely-chao,
The github is our bug tracker so for general [support](http://www.highcharts.com/support) questions please use stackoverflow / forum or email.

ps. You can link both yAxis by the option: 

Demo:
- https://jsfiddle.net/BlackLabel/wb13mp0k/

Docs:
- https://api.highcharts.com/highcharts/yAxis.linkedTo
```
// second yAxis
{
   linkedTo: 0,
   //... other options
}
```
