### ISSUE TITLE
Android - Highstock - navigator 

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1276]
In Android / iOS navigator dragging range doesn't work properly. Sometimes only handles positions are changed, but all "draggable range" not move.

related topic: http://highslide.com/forum/viewtopic.php?f=12&t=21057

Android 4

**Comment by ShashankOodles1** [comment]
Hi I am facing issue while performing pinch and moving slider left and right in Android.
I have increase Height of Navigator but sometimes it is Freeze and not able to Slide

**Comment by ShashankOodles1** [comment]
Highcharts.stockChart('container', {
         navigator: {
          height: 100
          
    },
        yAxis: [{
            labels: {
                align: 'left'
            },
            "title": {
                "text": "Hash Rate"
            },
            resize: {
                enabled: true
            }
        }, {
            labels: {
                align: 'left'
            },
          
            top: '80%',
            height: '20%',
            offset: 10

        }],
        tooltip: {

            shape: 'square',
            headerShape: 'callout',
            borderWidth: 0,
            shadow: false,
            positioner: function (width, height, point) {
                var chart = this.chart,
                    position;


                if (point.isHeader) {
                    position = {
                        x: Math.max(

                            // Left side limit
                            chart.plotLeft,
                            Math.min(
                                point.plotX + chart.plotLeft - width / 2,
                                // Right side limit
                                chart.chartWidth - width - chart.marginRight
                            )
                        ),
                        y: point.plotY
                    };
                } else {
                    position = {
                        x: point.series.chart.plotLeft,
                        
                        y: point.series.yAxis.top - chart.plotTop
                    };
                }

                return position;
            }
        },
        series: [{

            type: 'line',
            name: 'Computed Average Hash Rate',
            data: spline

        }],
        credits: {
         enabled: false
          },
        responsive: {
            rules: [{
                condition: {
                    maxWidth: 800
                },
                chartOptions: {
                    rangeSelector: {
                    
   
                        inputEnabled: false
                    }
                }
            }]
        }
    });
});

**Comment by MuhammedHarisMKS** [comment]
+1 

Same issue here 

@TorsteinHonsi  I have the exact issue described here. 

Can you please explain how to add the time delay or the loading button things in my code?
