### ISSUE TITLE
With the width and height of the chart in percent and the styledMode option turned on, there is an empty ticks object in the tickPositioner

### ISSUE THREAD

**Issue by fredure** [highcharts/highcharts#12762]
#### Expected behaviour
I expect a non-empty ticks object

#### Actual behaviour
With the width and height of the chart in percent and the table option turned on, there is an empty tick object in the tick positioner. Does not fulfill the condition.
https://github.com/highcharts/highcharts/blob/e15e3e56faca7902844e19006c4c6f3d5adf5b0f/js/parts/Chart.js#L1758

#### Live demo with steps to reproduce
https://jsfiddle.net/jwtsvygq/5/

#### Product version
Highcharts 7.0.2

#### Affected browser(s)
All browsers

![image](https://user-images.githubusercontent.com/8024592/72143803-38046580-33b9-11ea-95a0-3c3985793955.png)

**Comment by pawelfus** [comment]
Hi @fredure 

`axis.ticks` object is generated according to `tickPositions` you will return in `tickPositioner`. If you access this object, and some ticks are stored there, then it means you refer to the old ticks.

Sometimes, as you noticed, `axis.ticks` will be generated on initial rendering, but this happens only under certain conditions. When you create a chart, some of the required space (e.g. space for title, xAxis title, xAxis labels, yAxis title etc.) is predicted, not calculated. If the difference between these values (`redoHorizontal` or `redoVertical` flags) is too big, then elements need to be reflow. In this case you can observe `axis.ticks` available in your `tickPositioner`, but again, those are old ticks.

**Comment by fredure** [comment]
@pawelfus  
Can I otherwise find out the width of the labels in the tickPosionioner?
I want form an array with ticks regarding the width of the label. Let's say I have 20 labels. I take the width of the axis and divide it by the maximum width of the label. So I get the number of labels that are guaranteed to fit on the axis. From this number you can determine the number of ticks.

**Comment by pawelfus** [comment]
You can always use [`chart.renderer.text`](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#text) to render some label outside the view, get the dimensions and remove that label. I assume that every label has more or less similar size.
