### ISSUE TITLE
Scale not working on Patterns

### ISSUE THREAD

**Issue by IgorFIE** [highcharts/highcharts#12763]
Looking at the SVGAttributes I thought the properties scaleX/scaleY/rotation would work in a pattern:path since a path receives a SVGAttribute object. For some reason they are not working. Am I doing this correctly?
https://jsfiddle.net/panintelligence/ojcm5grd/4/

https://api.highcharts.com/class-reference/Highcharts.PatternOptionsObject#path
https://api.highcharts.com/class-reference/Highcharts.SVGAttributes

**Comment by sebastianbochan** [comment]
Hi @IgorFIE,
Thank you for reporting about the problem.

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
Unsure why this would not work as expected, but you can accomplish the same by using SVG `transform`s: http://jsfiddle.net/0cn56qLk/

**Comment by IgorFIE** [comment]
Sorry about the delay. So maybe I got a wrong idea on how this should work, because I though this would work like this. https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform

### Given transform: 'scale(1)'
![Screenshot from 2020-01-30 13-24-01](https://user-images.githubusercontent.com/17085338/73453654-6811a980-4364-11ea-9614-1cbd66c6f72b.png)

### Given transform: 'scale(5)'
![Screenshot from 2020-01-30 13-24-11](https://user-images.githubusercontent.com/17085338/73453675-6fd14e00-4364-11ea-8fee-a7842d01463c.png)

Is there a way for me to achieve this result?

PS: The rotate option is actually doing something strange if you change the value to 30 it rotates 90 degrees.

**Comment by oysteinmoseng** [comment]
Because the pattern has a width/height set, you would need to increase this as well in order to achieve the result you are looking for.

As for the rotate strangeness, SVG transforms are a bit tricky here. Firstly, the rotation origin is (0,0) unless otherwise specified, and secondly the order of transform operations matter. For the most predictable results, you should perform `scale` before `rotate` and set the rotation transform parameters to the center of your SVG path. Alternatively, you could use `translate` to move the path back into view after rotating.

Example with width/height and rotation origin set: https://jsfiddle.net/0wy9xs8f/

**Comment by IgorFIE** [comment]
Right so I made an example of what I want vs what highcharts provides: https://jsfiddle.net/panintelligence/ngo9Lr7e/28/

I understand that the scale highcharts provide is local to the pattern (i.e. on the path). What I want is to scale the whole pattern:
```javascript
      color: {
        pattern: {
          path: {
            d: 'M 0 0 L 5 10 L 10 0',
            fill: 'white'
          },
          transform: 'rotate(10) scale(1.2, 1.2)'
          backgroundColor: 'green',
          width: 10,
          height: 10,
        }
      }
```

**Comment by oysteinmoseng** [comment]
Ah, I see, thank you for the demo. Looks like you want to apply the transformation to the entire pattern fill, not to the individual path.

We would have to introduce a new option to allow this, but it should be easy enough to do, and probably useful in more circumstances. I will look into it.

For now it is possible to achieve this with some custom logic: https://jsfiddle.net/12g0sj37/.

**Comment by IgorFIE** [comment]
Yes that's what I want.
Do you think this is something that may take a while for you guys to implement and if I can be notified of it, Because we would prefer to wait for this feature instead of implementing a work around.

**Comment by oysteinmoseng** [comment]
Already added, you can test it [here](https://jsfiddle.net/9su5nmgq/) (but do not use the `github.highcharts.com` URLs in production as it will be slow).

It should be available in the next release, probably coming in one of the next weeks.

**Comment by IgorFIE** [comment]
Cool thank you! I have my current task in waiting so I'll wait for highchart next release.
