### ISSUE TITLE
Mapdata for Malawi (admi1) is incorrect

### ISSUE THREAD

**Issue by MaluwaLMK** [highcharts/highcharts#12766]
#### Expected behaviour
The mapdata provided here https://code.highcharts.com/mapdata/countries/mw/mw-all.geo.json has an error. For `"woe-id": "20070125"`, the `"name"` should be `"Karonga"` and `"woe-name": "Karonga"`. This will result in correct labels for `Karonga` and `Chitipa` on the map.

#### Live demo with steps to reproduce

Hover on the two northernmost districts. The one on the west is Chitipa and on the east is Karonga.
https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/mw/mw-all

**Comment by pawelfus** [comment]
Hi @MaluwaLMK 

Thanks for reporting this issue! You actually posted this in the wrong repo, could you please reporting this here: https://github.com/highcharts/map-collection-dist/issues ? Thanks!
