### ISSUE TITLE
How to set right margin of a grid column

### ISSUE THREAD

**Issue by NordicLight** [highcharts/highcharts#12771]
#### Expected behaviour
It should be possible to set both left and right margin/padding of a grid column

#### Actual behaviour
Tried all possible combinations using styles, css, format or formatter without success.

#### Live demo with steps to reproduce
https://jsfiddle.net/JohanBrodin/f5gswar7/3/

#### Product version
8

<img width="350" alt="Screenshot 2020-01-11 at 13 36 32" src="https://user-images.githubusercontent.com/9700899/72204413-e1aa2c00-3477-11ea-9853-9c6787ab16ba.png">

**Comment by pawelfus** [comment]
Thanks for reporting @NordicLight 

**Workaround:**
Define for every column `labels.x` (defaults to -15), then add plugin: https://jsfiddle.net/BlackLabel/ajtnke61/

Plugin:
```js
(function(H) {
  H.addEvent(
    H.Tick,
    'afterGetLabelPosition',
    function(e) {
      if (H.defined(this.axis.options.labels.x)) {
        e.pos.x += this.axis.options.labels.x;
      }
    }
  );
})(Highcharts);
```
