### ISSUE TITLE
scrollPositionX: 1 causes hovers on incorrect points in official demo

### ISSUE THREAD

**Issue by jareware** [highcharts/highcharts#12783]
#### Expected behaviour

Hovering over points [in this official demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea) should look like this:

![highcharts-scrollPositionX-correct](https://user-images.githubusercontent.com/560055/72337255-f4686f00-36ca-11ea-84e3-e7a76cf9745a.png)

#### Actual behaviour

The amount of x-scroll is deducted from the cursor position for the hover:

![highcharts-scrollPositionX-issue](https://user-images.githubusercontent.com/560055/72337484-50cb8e80-36cb-11ea-83f1-92e81fdd4719.png)

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea

1. Open page
1. Hover on the chart

#### Product version

`v8.0.0 (2019-12-10)` served from https://code.highcharts.com/highcharts.js

#### Affected browser(s)

Verified on:

* Latest Chrome on macOS
* Latest Firefox and Chrome on Ubuntu

**Comment by sebastianbochan** [comment]
Hi @jareware ,
Thank you for reporting about the problem. The issue has been already reported here: https://github.com/highcharts/highcharts/issues/12682.

Im closing this ticket as duplicate.

**Comment by jareware** [comment]
OK, sorry, tried looking for dupes but didn't spot that one!

**Comment by sebastianbochan** [comment]
You're welcome ;)
