### ISSUE TITLE
Tooltip position is behaves weirdly when the chart is within a scrollable container

### ISSUE THREAD

**Issue by PericlesTheo** [highcharts/highcharts#12799]
I have a Highcharts instance that is rendered within a scrollable container. The [tooltip.outside](https://api.highcharts.com/highcharts/tooltip.outside) option is also set to `true`.

When you scroll however, you can see tooltip following the scrolling. Moreover, when you hover over the series, the tooltip renders in various positions that _seem_ wrong. Another interesting point that illustrates this is that once you leave the chart and hover again on the series, the tooltip is at the correct position (top).

#### Expected behaviour
- Tooltip does not follow the scrolling
- Tooltip stays at the top on hover again.

#### Actual behaviour
- Tooltip follows the scrolling
- Tooltip renders in various positions on the series

#### Live demo with steps to reproduce
Illustration of the issue I'm describing: https://imgur.com/a/Zj3NstL - It doesn't include the hover out of the chart and then back in and on top of a series.

Example: https://jsfiddle.net/tcqeo415/2/ I've added a long paragraph to show that the `window.scroll` is fine. So you might need to scroll a bit to see the charts 😄 

#### Product version
7.2.1, 7.1.1, 8

#### Affected browser(s)
All as far as I am aware but I checked on Chrome and Safari explicitly.

**Comment by PericlesTheo** [comment]
2 similar solutions: https://stackoverflow.com/questions/59754313/highcharts-tooltip-in-scrollable-container-scrolls-with-the-content/59769430 (one of them is my answer)

**Comment by nickwinger** [comment]
I don't understand why you close this issue.
Not even the example of your documentation is working:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea

The library gives the ability to do scrolling, then also the mouse (tooltips) should work correctly.
If you scroll the x axe, then the mouse and tooltips are not in sync anymore...
Why there needs to be a workaround.

If the library says it supports scrolling out-of-the-box (https://api.highcharts.com/highcharts/chart.scrollablePlotArea.minWidth)
Then the sync with the mouse and tooltips should also be already handled...omg

**Comment by nickwinger** [comment]
ah ok, the issue is already handled here:
https://github.com/highcharts/highcharts/issues/12682
