### ISSUE TITLE
Android - hide series

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1279]
We click series2 marker, tooltip appears correct, but when we hide series2 from legend then tooltip stil exist. Morever when we drag crosshair then tooltip appears with wrong color and position.

http://jsfiddle.net/utgXp/

**Comment by jon-a-nygaard** [comment]
Closing this issue due to we are not able to reproduce the it, and it has been inactive for a long time. Should anyone have further information on this issue, please add a comment and/or reopen.
