### ISSUE TITLE
Sunburst incorrectly shows back button after drill up

### ISSUE THREAD

**Issue by jbolotin** [highcharts/highcharts#12804]
#### Expected behaviour
After drilling down to a specific layer, the back button should only be displayed until the user clicks it the number of layers that they drilled down to

#### Actual behaviour
Back button always shows one layer more than it should. For example, after clicking to the second layer, the back button should only need to be clicked one time before it disappears. Instead, it needs to be clicked two times in order for it to disappear. 

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/sunburst

1. Click on Asia. The sunburst should drill down to the Asia section of the chart
2. Click the back button. The sunburst drills up to the full chart. At this time, since the entire chart is being displayed, the back button should not still be shown. Instead, it needs to be clicked one extra time in order to disappear. 

#### Product version
Highcharts 8.0.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thank you for reporting this issue @jbolotin 

**Simplified demo:**
https://jsfiddle.net/BlackLabel/wxpc8ygv/

Steps: 
- Click on `Parent` node. The "Back" button shows up.

*Internal note:*
It seems that actually the traversing is wrong. For example after clicking `A.2` we should display only `B.1`, but both, `A.2` and `B.1`, are rendered.
