### ISSUE TITLE
API documentation typo: should say Y axis

### ISSUE THREAD

**Issue by quackenbush** [highcharts/highcharts#12803]
This is a copy/paste typo, where it should say Y, but says X.

#### Expected behaviour
An array of objects representing plot lines on the Y axis

#### Actual behaviour
An array of objects representing plot lines on the X axis

#### Live demo with steps to reproduce

https://api.highcharts.com/highcharts/yAxis.plotLines

#### Product version
LATEST

**Comment by sebastianbochan** [comment]
Hi @quackenbush,
Thank you for reporting. The issue has been already fixed and just waiting for merge.
