### ISSUE TITLE
Broken link to v7 styled mode

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#12802]
Googling for "highcharts styled mode" produces a link to https://www.highcharts.com/blog/docs/chart-design-and-style/style-by-css, which can no longer be fonud.

![image](https://user-images.githubusercontent.com/33569/72566107-05afa800-3892-11ea-897c-e8769b75909f.png)

**Comment by sebastianbochan** [comment]
Hi @dandv,
Thank you for reporting about the bug.

**Comment by KacperMadej** [comment]
Unable to recreate through the required steps.
Closing as resolved.
