### ISSUE TITLE
Lollipop/dumbbell connector width (crisping)

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#12819]
#### Expected behaviour
The connector line should be in the middle of the lollipop.

#### Actual behaviour
In the below example, the connector is moved a little bit right.

I know crispConnector() is an old browser fix, but it seems like something has changed in new versions of browsers. I tested it on all Windows 10 browsers with different (even/odd) connectorWidths.

#### Live demo with steps to reproduce
Current: https://jsfiddle.net/BlackLabel/sh8evd2p (line 6)
![image](https://user-images.githubusercontent.com/23310742/72814485-67db2500-3c65-11ea-854a-fc26f327e825.png)

I think it should work like this: https://jsfiddle.net/BlackLabel/qdke1shv (line 5)
![image](https://user-images.githubusercontent.com/23310742/72814515-73c6e700-3c65-11ea-94fb-d3129cac2140.png)

#### Product version
Highcharts 8.0.0

#### Affected browser(s)
All Windows browsers

**Comment by raf18seb** [comment]
FYI @sebastianbochan @TorsteinHonsi

**Comment by sebastianbochan** [comment]
Agree with @raf18seb. Especially that we tested it with different line width. 

Suggest to create PR.

**Comment by pawelfus** [comment]
The suggested solution has fuzzy lines instead of sharp ones. Position looks better but it's not ideal. Can we find a solution to have both, sharp lines and connector directly in the middle? Note it's a general issue (e.g. scatter + column: #1843)
