### ISSUE TITLE
Spelling mistake / grave accent encoding in French mapdata

### ISSUE THREAD

**Issue by MatthiasGan** [highcharts/highcharts#12815]
Hello,

First of all, thank you for your work on this library.

Using HighMaps (through Highcharter), I recently encountered spelling mistakes in French departments having a grave accent, which causes the "è" to be wrongly encoded (e.g Ardčche instead of Ardèche), and prevents me from displaying external department-related data due to wrong key label when using the joinBy argument.

Exemple from JSFiddle with wrong spelling [here](https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/fr/custom/fr-all-all-mainland) (on the leftest department for example)

Do you know when will this be patched?

Have a nice day,

**Comment by sebastianbochan** [comment]
Hi @MatthiasGan,
Thank you for reporting about the problem. I moved your ticket to the correct maps repo here: https://github.com/highcharts/map-collection-dist/issues/55

**Comment by MatthiasGan** [comment]
Je suis absent(e) du bureau jusqu'au 19/03/2020




Remarque : ceci est une réponse automatique à votre message  "Re:
[highcharts/highcharts] Spelling mistake / grave accent encoding in French
mapdata (#12815)" envoyé le 20/01/2020 17:04:53.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.

__________________________________________________________

Tout usage de ce message par une personne autre que son destinataire est strictement interdit.
L'intégrité de ce message n'étant pas assurée sur Internet, GAN Assurances ne peut être tenu pour responsable de son contenu.

Toute modification, utilisation quelle qu'elle soit ou diffusion non autorisée est interdite.
Si vous n'êtes pas destinataire de ce message, vous devez le détruire et avertir l'expéditeur.

The information above is for the sole use of the individual or entity to which it is intended.
If you are not the intended recipient of this message, you are here by notified that any dissemination, any alteration, distribution or copying of this document is strictly prohibited.
The integrity of this message cannot be guaranteed on the Internet, GAN Insurance, shall in no way be liable for its content.
Please destroy this message and notify the sender.

__________________________________________________________

**Comment by MatthiasGan** [comment]
Je suis absent(e) du bureau jusqu'au 19/03/2020




Remarque : ceci est une réponse automatique à votre message  "Re:
[highcharts/highcharts] Spelling mistake / grave accent encoding in French
mapdata (#12815)" envoyé le 20/01/2020 17:04:54.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.

__________________________________________________________

Tout usage de ce message par une personne autre que son destinataire est strictement interdit.
L'intégrité de ce message n'étant pas assurée sur Internet, GAN Assurances ne peut être tenu pour responsable de son contenu.

Toute modification, utilisation quelle qu'elle soit ou diffusion non autorisée est interdite.
Si vous n'êtes pas destinataire de ce message, vous devez le détruire et avertir l'expéditeur.

The information above is for the sole use of the individual or entity to which it is intended.
If you are not the intended recipient of this message, you are here by notified that any dissemination, any alteration, distribution or copying of this document is strictly prohibited.
The integrity of this message cannot be guaranteed on the Internet, GAN Insurance, shall in no way be liable for its content.
Please destroy this message and notify the sender.

__________________________________________________________
