### ISSUE TITLE
Gantt Missing dependency connection if task is not fully visible

### ISSUE THREAD

**Issue by castortech** [highcharts/highcharts#12810]
#### Expected behaviour
When any portion of a task is shown, its dependency connection should be visible.

#### Actual behaviour
Connection only shows when making sure the full task is visible by changing the visible range.

#### Live demo with steps to reproduce

https://jsfiddle.net/alpic80/seuqrotj/3/

Notice that the task "Send to color house" is not connected to "Generate proofs". Click on All for the range and it will reveal the connection.

#### Product version

current version (8)

#### Affected browser(s)
All AFAICT

**Comment by sebastianbochan** [comment]
Hi @castortech,
Thank you for reporting about the problem.
