### ISSUE TITLE
Chart choke or tooltip fail to show when width >= 1400px

### ISSUE THREAD

**Issue by totszwai** [highcharts/highcharts#12816]
#### Expected behaviour
Chart should render tooltips the same way regardless of the width.

#### Actual behaviour
It seems the Highcharts is choking/lagging when you render multiple charts with the width of 1400px, the **last** charge would have problem displaying the tooltip.

![image](https://user-images.githubusercontent.com/4440365/72752079-4dcf1300-3b8f-11ea-8ae3-9404c67fedc6.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/totszwai/mt045so8/

Change the container's width to 1399px and it would work again TO SOME DEGREE. It still chokes.

#### Product version
8.0.0

#### Affected browser(s)
Tested in Chrome and Edge (Chrome)

**Comment by sebastianbochan** [comment]
Hi @totszwai,
Thank you for reporting about the problem. I run the demo in my browser and was not able to reproduce the issue.

![tooltip-hover](https://user-images.githubusercontent.com/2115686/72788084-76a7e480-3c31-11ea-8223-9595235c4334.gif)
Chrome: 79.0.3945.117
MacOSX: 10.14.5 

Could you supply us more details / steps to reproduce the issue? Let me know about version of your OS and Chrome.

**Comment by totszwai** [comment]
Wow... you are right, at home with my browsers I was not able to reproduce it either but at work, I could. Let me try to get more details tomorrow.

**Comment by totszwai** [comment]
@sebastianbochan 
I can reproduce it again. It looks like the height also play a factor.
See: https://drive.google.com/file/d/1XMOAvqMD12niYhjX21Sl-OB5P7p8VhzC/view?usp=sharing


Chrome: Version 79.0.3945.117 (Official Build) (64-bit)
```
------------------
System Information
------------------
      Time of this report: 1/24/2020, 14:08:37
         Operating System: Windows 10 Enterprise 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
                 Language: English (Regional Setting: English)
      System Manufacturer: HP
             System Model: HP EliteBook 840 G3
                     BIOS: N75 Ver. 01.23 (type: UEFI)
                Processor: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 CPUs), ~2.8GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16232MB RAM
                Page File: 17779MB used, 10741MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: Unknown
           DxDiag Version: 10.00.18362.0387 64bit Unicode
```

**Comment by totszwai** [comment]
Actually, is weird, the video doesn't seem to be able to capture the actual lag... The pauses you see in the video, my mouse cursor is actually hovering on other bars, but it doesn't render the tooltip.

**Comment by pawelfus** [comment]
I'm not able to reproduce this neither (the same config as @sebastianbochan: OSX + Chrome). Tested with both 300px and 250px heights.

You are right, I can see some short moments in your video where nothing happens. Since screen capture can't record this, then perhaps your machine chokes? Maybe plugins, installed programs etc cause this? That would explain why it happens only on your machine at work. Does it happen in incognito mode too?

**Comment by totszwai** [comment]
Sorry, my bad. This was quite unexpected... The root cause was because in Windows Slack App, if you enable the build-in notification, there would be some kind of invisible windows or overlay sitting in the lower right portion of the screen preventing mouse event to happen!!!!!

I disabled build-in notification and everything worked. Sorry for wasting your times guys!
