### ISSUE TITLE
highcharts endOnTick option showing unspecified value on axis

### ISSUE THREAD

**Issue by anooppv09** [highcharts/highcharts#12813]
In highcharts when i have set endOnTick true on x axis in my chart, then the chart showing unspecified value in the end of x axis.
below is the code
https://jsfiddle.net/anooppv09/ap2h8utv/

**Comment by sebastianbochan** [comment]
Hi @anooppv09,
Thank you for contacting us. The `endOnTick` works in combination with the `maxPadding` param. I guess that you expect show the point "on the top" line of a chart. If yes, you should reset the maxPadding by 0 value.

Demo:
- https://jsfiddle.net/BlackLabel/eq7vo1p8/

Please correct me if Im wrong.

**Comment by sebastianbochan** [comment]
Close due to inactivity.
