### ISSUE TITLE
Highcharts export server can use javascript extensions but not in batch mode

### ISSUE THREAD

**Issue by benjewhite** [highcharts/highcharts#12826]
#### Expected behaviour

Given a json model input.json containing arbitrary input like:

{"title": {"text": "Steep Chart"}, "xAxis": {"categories": ["Jan", "Feb", "Mar"]}, "series": [{"data": [29.9, 71.5, 106.4]}]}

...and, in the same directory, a resource file resources.json containing:

{
  "files": "lineArrow.js"
}

...and, in the same directory, a file lineArrow.js containing an extension like that at:

https://stackoverflow.com/questions/38392948/how-to-draw-arrows-on-a-line-chart-with-highcharts

...the following commands should, when also run in the same directory, render a line chart with an arrow:

(1) highcharts-export-server --infile input.json --outfile curlout.png

(2) highcharts-export-server --batch "curlinput.json=curlout.png"

#### Actual behaviour

(1) Works

(2) Fails to render

Note that the underlying reason seems to be that the resources option is broken. In fact, it cannot be used with batch mode either. This also fails:

highcharts-export-server --batch "curlinput.json=curlout.png;curlinput2.json=curlout2.png" --resources={"files":"lineArrow.js"}

where curlinput2.json is copy of curlinput.json

#### Steps to reproduce

As above

#### Product version
  "dependencies": {
    "highcharts": "^6.2.0",
    "highcharts-export-server": "^2.0.24",
  }

#### Affected browser(s)

N/A

**Comment by pawelfus** [comment]
Hi @benjewhite 

Thanks for reporting the issue, but you reported this in wrong repo, please use exporting server one: https://github.com/highcharts/node-export-server
