### ISSUE TITLE
Click event on point doesn't work on IE if colorAxis is turned on

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#12828]
#### Expected behaviour
Click event working on all browsers.

#### Actual behaviour
It is not working on IE.

#### Live demo with steps to reproduce
Click on the point, and look for the "Test" log in the console.
https://jsfiddle.net/BlackLabel/5fpozr4n/

#### Product version
 Highcharts JS v8.0.0 (2019-12-10)

#### Related forum thread
https://www.highcharts.com/forum/viewtopic.php?f=14&t=43203

#### Affected browser(s)
IE

**Comment by pawelfus** [comment]
@ppotaczek FYI

**Comment by ppotaczek** [comment]
_Internal note:_ Broken since 8.0.0

**Comment by KacperMadej** [comment]
The offending commit is https://github.com/highcharts/highcharts/commit/d722bdc378ba3a33e126d118da962848f61671a0

**Comment by KacperMadej** [comment]
Code on the master branch works correctly - closing as fixed.
The fix should be published with the next version release.

Workaround: before the chart is created prevent moving to the top of the hovered element by adding the below code line for the series type that should be fixed - in this case `map`.
`Highcharts.seriesTypes.map.prototype.pointClass.prototype.moveToTopOnHover = false;` 
Demo: https://jsfiddle.net/BlackLabel/5fpozr4n/13/
