### ISSUE TITLE
Invalid week number in Gantt header

### ISSUE THREAD

**Issue by castortech** [highcharts/highcharts#12825]
#### Expected behaviour
Weeks should be numbered correctly and not repeat

#### Actual behaviour
Seeing week 3 appears twice

#### Live demo with steps to reproduce
http://jsfiddle.net/alpic80/925xc3jL/18/

#### Product version
Current

#### Affected browser(s)
AFAICT

**Comment by sebastianbochan** [comment]
Hi @castortech,
Thank you for reporting about the problem.

FYI @oysteinmoseng

**Comment by pawelfus** [comment]
Probably related to timezone, screenshot from my osx + latest chrome:
![Screen Shot 2020-01-22 at 10 14 52](https://user-images.githubusercontent.com/1453926/72880898-0e740400-3d00-11ea-9a23-5e13d255c4d8.png)

Could you tell us your timezone @castortech ? Thanks!

**Comment by castortech** [comment]
Timezone is UTC - 5, Eastern (US/Canada) w/ daylight savings.
And all start/end date values are days adjusted for UTC (o/w would provide incorrect tooltip info)

**Comment by castortech** [comment]
Even added as a test time.useUTC true but didn't change anything

**Comment by pawelfus** [comment]
@castortech 
Could you attach screenshot and browser + os details? Thanks!

**Comment by castortech** [comment]
Screenshot
![image](https://user-images.githubusercontent.com/85858/72893749-d6f95d80-3ce7-11ea-8ad8-38c4d36668ae.png)

Browser, both with Firefox and Chrome, OS: Windows 10

**Comment by pawelfus** [comment]
Got it, thanks @castortech 

It's a duplicate of #12076 - closing this ticket.
