### ISSUE TITLE
plotOptions.area.threshold Typescript type does not accept null

### ISSUE THREAD

**Issue by Rmafive** [highcharts/highcharts#12824]
#### Expected behaviour

Typescript linter will allow `plotOptions.area.threshold` to be `null`.

#### Actual behaviour

The Typescript linter throws the error below when setting `plotOptions.area.threshold` to `null`. According to the documentation this should be allowed. 

https://api.highcharts.com/highcharts/plotOptions.area.threshold

![image](https://user-images.githubusercontent.com/5626056/72826838-9518da80-3c47-11ea-9a7c-463c1574e65b.png)

![image](https://user-images.githubusercontent.com/5626056/72826888-b37ed600-3c47-11ea-85b6-53f19f34346e.png)

#### Live demo with steps to reproduce
_None_

#### Product version
8.0.0

#### Affected browser(s)
Issue appears in the VSCode IDE.

**Comment by sebastianbochan** [comment]
Hi @Rmafive,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by bre1470** [comment]
@sebastianbochan I agree that this option should not allow the null type as it has the same result as the value zero (`0`).

**Comment by TorsteinHonsi** [comment]
The docs description is correct - `null` does not behave like 0. Consider this case (jsfiddle is down at the moment):

```js
Highcharts.chart('container', {
    xAxis: {
    	categories: ['Apples', 'Pears', 'Bananas', 'Oranges']
    },
    series: [{
        data: [101, 104, 103, 105],
        type: 'area',
        threshold: null
    }]
});
```
This config will produce a chart with the Y axis minimum at ~100, as if it were a line chart. Now if we change the `threshold` to 0, which is default for area charts, the Y axis minimum will be 0.
