### ISSUE TITLE
Sunburst chart showing two tooltips when hovered on overflowed data label.

### ISSUE THREAD

**Issue by rajshekhar-heremath** [highcharts/highcharts#12838]
Expected behaviour
For sunburst chart when hover on datalabels it should show show only one tooltip.

#### Actual behaviour
whereas now it is showing two tooltips a) tooltip formatter and b) black backgrounded tooltip when hovered on a datalabel with longer text(ie., when text is truncated with css text-overflow: ellipsis property)

#### Live demo with steps to reproduce
[https://www.highcharts.com/demo/sunburst](https://www.highcharts.com/demo/sunburst)

#### Product version
8.0.3

#### Affected browser(s)
chrome
![screenshot](https://user-images.githubusercontent.com/43060303/72968146-e7453180-3de8-11ea-8346-01c366074d08.png)

**Comment by pawelfus** [comment]
Hi @rajshekhar-heremath 

This is expected behaviour. This black tooltip is the default browser's tooltip, displaying full text instead of the truncated one for a dataLabel. Example in HTML: https://jsfiddle.net/BlackLabel/8tL7zyra/ - hover text and wait a while.

**Comment by rajshekhar-heremath** [comment]
Closed
