### ISSUE TITLE
Highstock: trying to move the scrollbar when series are hidden and xAxis min and max are set breaks the min and max

### ISSUE THREAD

**Issue by Korbraan** [highcharts/highcharts#12834]
#### Expected behaviour

Nothing should happen when a user try to move the scrollbar and no series is visible.

#### Actual behaviour

If a min and a max are set for the x axis and all the series are not visible, trying to move the scrollbar breaks the min and max.

#### Live demo with steps to reproduce
https://codepen.io/Korbraan/pen/jOEXoRW

Hide the series with the button and then try to move the scrollbar.

#### Product version
Highstock 6.0.3+

#### Affected browser(s)
Firefox, Opera, Chrome, ...

**Comment by pawelfus** [comment]
Thanks for reporting this issue @Korbraan 

**Workaround:**
Set [`scrollbar.showFull`](https://api.highcharts.com/highstock/scrollbar.showFull) to `false`.

**Comment by pawelfus** [comment]
**Simplified demo:**
https://jsfiddle.net/BlackLabel/stf4kure/

Steps:
- hide series
- drag&drop scrollbar
- extremes are <0, 200> instead of <100, 200>
