### ISSUE TITLE
Export don't display rendered image

### ISSUE THREAD

**Issue by deguich** [highcharts/highcharts#12845]
#### Expected behaviour
Exporting module export image like displayed in svg (on the webpage).

#### Actual behaviour
Image dynamically added on the chart not displayed when exporting

#### Live demo with steps to reproduce
Click on export button and export as png. 
1) Working case : image added with onComplete at creation time : http://jsfiddle.net/sLp4vbcj/

This is the exported png graph :
![chart_OK](https://user-images.githubusercontent.com/7642281/73059722-9a1f9900-3e96-11ea-9b06-19618955f148.png)

2) Not working case : image dynamically added after chart creation : http://jsfiddle.net/mguichar/9tmh1xbj/

This is the exported png graph :
![chart_NOK](https://user-images.githubusercontent.com/7642281/73059753-b02d5980-3e96-11ea-8f8b-a88e78d18c27.png)

For example, case 2 is usefull to update the image when switching data (kind of watermark depending on data).

Other example visible on this webpage when  :
https://www.sonel.org/spip.php?page=gps&idStation=851

#### Product version
Last version of highcharts and exporting (v8.0.0)
Tested with export server and offline exporting.

Cause : image tag in SVG is not sent to server.

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @deguich 

Thanks for reporting the issue. This is expected behaviour: chart is recreated for exporting (so exported chart can be different from the rendered one using for example [`exporting.chartOptions`](https://api.highcharts.com/highstock/exporting.chartOptions) options). That means every item created via renderer requires rendering for exported chart too. You can achieve this using external storage for elements, for example (jsfiddle is down, so just a snippet): 

```js
var chart;
var rendererComponents = []; // external storage

$(function() {
  chart = new Highcharts.Chart({
    chart: {
      renderTo: "container"
    },
    xAxis: {
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },

    series: [{
      data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    }]

  }, chart => {
    // Callback is executed when chart is being exported
    rendererComponents.forEach(component => {
      chart.renderer.image(...component).add();
    });
  });

  setTimeout(() => {
    // Store rendering component
    var index = rendererComponents.push(
      ['http://dev.w3.org/SVG/tools/svgweb/samples/svg-files/android.svg', 100, 100, 100, 50]
    ) - 1;

    chart.renderer.image(...rendererComponents[index])
      .add();
  }, 1000)
});
```

**Comment by raf18seb** [comment]
@teraiyamayurcontact sorry, could you ask your question more precisely?
