### ISSUE TITLE
Updating stock tools + polar chart

### ISSUE THREAD

**Issue by kai2468** [highcharts/highcharts#12851]
#### Expected behaviour
Updating a polar chart which has a stock tools config to render properly

#### Actual behaviour
Cannot read property '0' of undefined in the console and chart doesnt update 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/eav5kxg7/

Push the click me button to see the error

#### Product version
Latest

**Comment by pawelfus** [comment]
Fixed since v8.0.1
Demo: https://jsfiddle.net/BlackLabel/2p6oawux/
