### ISSUE TITLE
Regression, tooltip in polar chart

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#12856]
#### Expected behaviour
1. Tooltips in polar charts should work
2. In https://jsfiddle.net/highcharts/6fgxjuva/1/, a tooltip should pop up after chart load

#### Actual behaviour
Tooltips in polar charts failed because we tried to guard against a failure in 2.

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/6fgxjuva/1/

#### Product version
Pre-production regression after https://github.com/highcharts/highcharts/commit/d81da7da61a8e9e45efad105c2c4b6a65ed6d85a

**Comment by raf18seb** [comment]
It is related to this commit: https://github.com/highcharts/highcharts/commit/0b5d8744b7a781130afe3b521dc1da4fc8e946bf

Waiting for a @bre1470 comment

**Comment by bre1470** [comment]
The original PR (https://github.com/highcharts/highcharts/issues/11148) for https://github.com/highcharts/highcharts/commit/d81da7da61a8e9e45efad105c2c4b6a65ed6d85a did not contain the latest master CI configuration and was therefor not testing with the CI visual tests before merge. This is failing with the following command line in two tests: `npx karma start test/karma-conf.js --tests highcharts/*/* --reference --browsercount 2 --no-fail-on-empty-test-suite`.

As far as our tests were going, we know the following: The `Pointer.runPointActions` is calling for unknown reasons the `Tooltip.refresh` in a polar chart with an empty `points` array. In Highcharts v8.0 the tests end up with two points for Tooltip.refresh, which has to be restored somehow. A patch agains `points.length` in `Pointer.runPointActions` or `Tooltip.refresh` is therefor **NOT** a solution.

The failing tests are:
* highcharts/demo/polar-spider
* highcharts/series-polar/tooltip-shared
