### ISSUE TITLE
Regression in 7.1.3: Tooltip hover markers are not rendered in boosted charts

### ISSUE THREAD

**Issue by cascornelissen** [highcharts/highcharts#12870]
#### Expected behaviour
Tooltip hover markers should be visible in boosted charts

![image](https://user-images.githubusercontent.com/1304939/73342023-12fb6800-427e-11ea-93c6-6e8e0e488771.png)

#### Actual behaviour
Tooltip markers don't show up when a chart is in boost mode since `7.1.3` (so `7.2.0`, `7.2.1`, and `8.0.0` as well)

![image](https://user-images.githubusercontent.com/1304939/73342051-21498400-427e-11ea-9e29-8239584036f9.png)

#### Live demo with steps to reproduce
Example for 8.0.0: https://jsfiddle.net/m3hwok5d/ (not working)
Example for 7.1.2: https://jsfiddle.net/m3hwok5d/1/ (working)

#### Product version
Highcharts `7.1.3`, `7.2.0`, `7.2.1`, and `8.0.0`

#### Affected browser(s)
Chrome, Safari, Firefox

**Comment by pawelfus** [comment]
Thanks for reporting this regression bug @cascornelissen 

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/6o0yauxh/
Snippet:
```js
(function(H) {
  H.wrap(
    H.Series.prototype,
    'getPoint',
    function(proceed, ...args) {
      var point = proceed.apply(this, args);

      point.isInside = typeof point.plotY !== 'undefined' &&
        point.plotY >= 0 &&
        point.plotY <= this.yAxis.len && // #3519
        point.plotX >= 0 &&
        point.plotX <= this.xAxis.len;

      return point;
    }
  );
})(Highcharts);
```

*Internal note:*
Bisected to commit 55686211b0
Workaround is just a copy-paste from here: https://github.com/highcharts/highcharts/blob/3b6485e00b0deae51e5446f15180c82d7b55e63d/ts/parts/Series.ts#L5188-L5193
