### ISSUE TITLE
Sunburst with accessibility module, series loses color after drilldown.

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#12876]
#### Expected behaviour
After coming back from a drilldown all series should have the same background color as before.

#### Actual behaviour
After coming back from a drill down all series except the drilldowned one are losing its color. 
It is happening only with the accessibility module in the 8.0.0+ version.

![Jan-31-2020 09-12-27](https://user-images.githubusercontent.com/50931078/73522943-073cac80-440a-11ea-804b-ae6f682a9cb7.gif)
#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/yg8x51su/

Steps to reproduce:
1. Click on the Western Africa
2. Click on the Back button to leave drilldown

#### Product version

 Highcharts JS v8.0.0 (2019-12-10)
#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Already fixed on master branch: https://jsfiddle.net/BlackLabel/g7Lfpvmk/

**Comment by avinash2k** [comment]
When will this be pushed to CDN ?

**Comment by sebastianbochan** [comment]
The master branch will be released within a few weeks.

Currently the master is available only on github (see urls in the @pawelfus demo).
