### ISSUE TITLE
Highcharts column chart not rendering in Edge

### ISSUE THREAD

**Issue by soso-maitha** [highcharts/highcharts#12886]
Hi, 

I created line and column charts, everything is working perfectly in local machine. However, when I moved to production, column chart was not displaying the bars. In Chrome it is working perfectly, but in Edge and IE it is not showing and Edge is our corporate browser. 

I searched a lot on Google, but nothing worked. Most of the sites suggest adding below tag.
```
<meta http-equiv="X-UA-Compatible" content="IE=edge">
```
and
``` 
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
```

Appreciate your help as I need to fix it urgently.

regards,

**Comment by pawelfus** [comment]
Hi @soso-maitha 

Thanks for contacting us, but this is wrong channel. Our github issues are bug reports or feature requests, not support questions. Please use other support channels: https://www.highcharts.com/blog/support/ (e.g. StackOverflow or contact us directly).
