### ISSUE TITLE
Week number error

### ISSUE THREAD

**Issue by cvinhar** [highcharts/highcharts#12884]
#### Expected behaviour
The week number for January 2020 should start with Week 1.
Week 1 should start from 30th December 2019 until 5th January 2020

#### Actual behaviour
The week number for January 2020 start with Week 52.
![image](https://user-images.githubusercontent.com/46776508/73640359-0b3a2a00-46a9-11ea-9e6d-e7b2f7abf636.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/cvinhar/4cp0fa1q/3/

#### Product version
https://code.highcharts.com/gantt/highcharts-gantt.js

#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Hi @cvinhar 

Thanks for reporting the issue! Yes, according to [ISO week day](https://en.wikipedia.org/wiki/ISO_week_date#First_week) - this should be first week, not the last week of previous year.

**Workaround:**
Define your own week-numbering logic: https://jsfiddle.net/BlackLabel/uxtfm4bq/

Snippet:
```js
Highcharts.dateFormats.W = function(timestamp) {
  var d = new Date(timestamp),
    yearStart, weekNo;
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + 4 - (d.getDay() || 7));
  yearStart = new Date(d.getFullYear(), 0, 1);
  weekNo =
    Math.ceil((((d - yearStart) / 86400000) + 1) / 7);
  return weekNo;
};
```

*Internal note:*
The workaround simply adds `+4` to start on Thursday (majority of its days in a week)
