### ISSUE TITLE
Sankey chart does not render correctly with specific data, but ok after resize

### ISSUE THREAD

**Issue by jainez** [highcharts/highcharts#12882]
Hi, I'm having the same problem reported in Issue #9818. When rendering a Sankey chart some lines are broken and after resizing, the graphic is displayed correctly.

#### Expected behaviour
![image](https://user-images.githubusercontent.com/60517314/73559884-ef722200-4423-11ea-8b32-7ed7944f90c1.png)

#### Actual behaviour
![Sankey Graph](https://user-images.githubusercontent.com/60517314/73559904-f8fb8a00-4423-11ea-8cca-ce1465a83168.PNG)

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/sankey-diagram/

-> replace series.data with following data:
['C', 'A', 1039] ,
['GBLSA', 'A', 28755] ,
['GBLSA', 'COST', 29847] ,
['GBLSA', 'GBLSRL', 65084] ,
['GBLSA', 'PHIL', 7000] ,
['GBLSA', 'PHILF', 16415] ,
['GBLSRL', '(*) GBLSRL', 20876] ,
['GBLSRL', 'A', 39008] ,
['GBLSRL', 'GBLBE', 985] ,
['HEIN', 'A', 1402] ,
['OPTI', 'A', 15400] ,
['TEC', 'A', 60336] ,
['TUR', 'A', 32040]

#### Product version
Highcharts JS v8.0.0 (2019-12-10)

#### Affected browser(s)
Chrome 79.0.3945.130

**Comment by pawelfus** [comment]
Thanks for reporting this issue @jainez 

**Simplified demo:**
Pattern: a->c, a->b, b->c
https://jsfiddle.net/BlackLabel/wz1nj90r/

*Internal note:*
It happens only with specific widths.

**Comment by jainez** [comment]
Thanks for the quick reply!
