### ISSUE TITLE
Highcharts works with the "name" field of a function that is not supported in the IE11

### ISSUE THREAD

**Issue by fredure** [highcharts/highcharts#12899]
#### Expected behaviour
If I pass an object with a date into the configuration, then the isClass function will not work correctly, since the name field in IE11 is not supported. This causes the Highcharts to go in cycles, the error falls "maximum call stack size".
https://github.com/highcharts/highcharts/blob/7e49f9c8ad06218882cefb86bab70e799807fbfe/js/parts/Utilities.js#L938

#### Actual behaviour
The function isClass should work correctly in IE11

#### Live demo with steps to reproduce
jsfiddle does not work in IE11
![image](https://user-images.githubusercontent.com/8024592/73852336-cf41c900-4850-11ea-9e9b-fa2d4f8901e9.png)

![image](https://user-images.githubusercontent.com/8024592/73852316-c650f780-4850-11ea-83f2-4967447ba81b.png)

#### Product version
Highcharts 7.0.3 

#### Affected browser(s)
IE11

**Comment by pawelfus** [comment]
Hi @fredure 

Thank you for reporting the issue, but could please provide a live demo?
Where do you pass Date object into configuration? Is that supported by our API?

**Comment by sebastianbochan** [comment]
Close due to inactivity.
