### ISSUE TITLE
Typescript: tickPositioner

### ISSUE THREAD

**Issue by ecnaidar** [highcharts/highcharts#12896]
#### Expected behaviour
All available properties are typed and working as expected 

#### Actual behaviour
tickPositioner types are not sufficient to properly use with TypeScript. 
I understand that it is the last resort for ticks positioning customisation but there is no documentation on "info" property for time axes whatsoever and you get quite incomprehensible code as a result.
 
In my case I want to have monthly ticks to be shown at the end of the month instead of the start.

#### Live demo with steps to reproduce
```typescript
          tickPositioner: function() {
            const { tickPositions } = this
// this.tickPositions can be undefined but tickPositioner is not allowed to return undefined  
            if (tickPositions === undefined) return []

// getting info property off tickPositions the is quite nasty
// as I understand it is only present for time axes and there are no types for it at all
            const info:
              | undefined
              | {
                  unitRange: number
                  count: number
                  unitName: "year" | "month" | "millisecond" | "week"
                  higherRanks: object
                  totalRange: number
                  segmentStarts: number[]
                } = (this.tickPositions as any).info

            if (info?.unitName === "month") {
              const newTickPositions = tickPositions.map(timestamp => {
                return moment(timestamp)
                  .endOf("month")
                  .valueOf()
              })

// assigning info property on number[] is somewhat nasty
              // @ts-ignore
              newTickPositions.info = info

              return newTickPositions
            }

            return tickPositions
          }
```

#### Product version
    "highcharts": "8.0.0"
    "highcharts-react-official": "2.2.2"

**Comment by pawelfus** [comment]
FYI @bre1470 

IMHO we should get rid of `.info` details from `tickPositions`. Perhaps move those to Axis instance instead (even simple `tickPositionsInfo` could be enough). Of course, that is a breaking change.

@TorsteinHonsi your thoughts?

**Comment by bre1470** [comment]
I agree with @pawelfus.

What do you think, @TorsteinHonsi?

**Comment by TorsteinHonsi** [comment]
The `info` object is meta information on the time ticks. Storing it on the Axis is not sufficient, as `getTimeTicks` is also used in data grouping. In my opinion I can't really see a problem with storing meta information on the array itself, as long as it is properly typed...

I don't understand the whole problem here, but it seems that the `TimeTicksInfoObject` interface is defined in Time.ts along with the `AxisTickPositionsArray.info` property? Is it not available in the definitions?

**Comment by bre1470** [comment]
For the definitions it has to be declared in the doclets as well, which is the case. So I guess, the type of `Highcharts.Axis#tickPositions` is incorrect. I still find it a bad design to add properties to an instance of an build in class as it could break with future script versions. How about, we replace `AxisTickPositionsArray` with an container object like
```ts
interface AxisTickPositionsObject {
    ticks: Array<number>
    info: TimeTicksInfoObject;
}
```

**Comment by TorsteinHonsi** [comment]
> So I guess, the type of Highcharts.Axis#tickPositions is incorrect. 

Yes

> How about, we replace AxisTickPositionsArray with an container object like

That will break all existing implementations of `tickPositioner`.

**Comment by daniel500tech** [comment]
I understand that @bre1470 suggestion is a huge breaking change, but you can at least for now correct the `TimeTicksInfoObject` interface as @ecnaidar suggested

```typescript
export type UnitName = 'day' | 'month' | 'whatever';

export interface TimeTicksInfoObject extends TimeNormalizedObject {
  higherRanks: Record<string, UnitName>;
  totalRange: number;
  unitName: UnitName;
  ...
}
```

currently it creates a nasty code on the consumer side in order to make tsc happy :)

Love Highcharts!

**Comment by daniel500tech** [comment]
And another type to fix is
```typescript
export type AxisTickPositionerCallbackFunction = (this: Axis) => Array<number>;

// should be
export type AxisTickPositionerCallbackFunction = (this: Axis) => AxisTickPositionsArray;
```
