### ISSUE TITLE
Highstock animation breaks after using the setExtremes.

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#12895]
#### Expected behaviour

The animation should work as works after the first button click. 

#### Actual behaviour

After a few extremes changes animation doesn't work. 

Noticed: 

1. Works fine in Highcharts,
2. Works fine if changing only one extreme value, 

Demo: https://jsfiddle.net/BlackLabel/t6kcb0q9/

#### Live demo with steps to reproduce

Issue demo: https://jsfiddle.net/BlackLabel/bgt24cLf/

#### Product version

 Highstock JS v8.0.0 (2019-12-10)

**Comment by pawelfus** [comment]
It's caused by dataGrouping, when disabled, animation is available: https://jsfiddle.net/BlackLabel/fe7ywzcq/

**Workaround:**
Disable [`dataGrouping`](https://api.highcharts.com/highstock/series.line.dataGrouping).
