### ISSUE TITLE
Add defer option as animation parameter

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#12901]
@pawelfus @TorsteinHonsi 

As in the title, there was a proposal to add the defer option as the animation parameter in the animation engine.

Suggested defer-and-fade-in sequence: 

```
element.attr({ opacity: 0 })
    .animate({
        defer: 1000,
        duration: 150,
        opacity: 1
    });

```

When this feature will be ready to use current defer logic could be removed from series labels, data labels and annotations and replaced by the new one. Additionally, I think that it should be easy to implement it for stackLabels. 

I would like to discuss the idea that the **defer** could be also a number which value could be set as the defer time for particular label or annotation in their options if user would like to set it too (not only a value inherited from series).

**Comment by pawelfus** [comment]
I suggest to implement this is steps:
- [ ] - implement `SVGElement.animate({ defer })` - can be PR-drafted, before proceeding further
- [ ] - implement `series.animation.defer`
- [ ] - replace `series.dataLabels.defer` with [to be decided] `series.dataLabels.animation.defer` 
- [ ] - replace logic in `series.label` and add `series.label.animation.defer` option (if needed)
- [ ] - add `annotation.animation.defer`, `annotation.shapes[].animation.defer` and `annotation.labels[].animation.defer`
- [ ] - consider implementing `yAxis.stackLabels.animation.defer`

Quite a lot of new options, perhaps some of them are not needed (e.g. `series.label.animation.defer`, or `annotation.shapes[].animation.defer`) and can be implemented later, on demand. Every suggested option above should inform in docs that `defer` is applied only on chart/series/annotation/etc. init.
