### ISSUE TITLE
Behaviour mismatch between point.color and series.color update

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#12900]
#### Expected behaviour
When you update a point color to a `undefined/null/""` state, internally use a default color (exactly as series do).

#### Actual behaviour
`undefined/null/""` color is set, having weird visual results.

#### Live demo with steps to reproduce
Just load the fiddle a wait a couple of seconds while the timeouts change the point color: https://jsfiddle.net/y5kp0d73/

See how the behaviour is different as when doing it with a series color: https://jsfiddle.net/cygthzx3/

#### Product version
Highcharts 7, but tested on Highcharts 8 and having the same issue.

#### Affected browser(s)
Chrome, but all, I guess.

**Comment by pawelfus** [comment]
Hi @Llorx 

In general, setting `undefined` or `null` **does not reset** an option. Only situation, when `null` or `undefined` makes sense is when an option has specific behaviour (for example `series.threshold`) and is listed as valid type. As per [API](https://api.highcharts.com/highcharts/series.pie.data.color) - color should be one of: color, pattern or gradient. Not null, undefined, boolean etc.

@TorsteinHonsi - should we improve [Point.update()](https://api.highcharts.com/class-reference/Highcharts.Point#update) (and others) description about null/undefined values?

**Comment by Llorx** [comment]
Oh I see. Then `series.update` with an undefined color should act equal, right? Right now is kinda confusing between both as there's a behaviour mismatch, but the [API explanation](https://api.highcharts.com/highcharts/plotOptions.series.color) is the same for both. More than a bug, I say is a behaviour mismatch.

Without this option working the same as series, how can I select a default value from the `options.colors` array in a point the same way as a series do? Right now I see a small limitation here.

Being picky, the documentation says that by default its value is `undefined` and that it will pick a color from the color pool, so is easy to understand that `undefined` means that is going to pick a color from the color pool (And that's exactly what a series do):
![image](https://user-images.githubusercontent.com/702490/73941309-517fcb00-48ed-11ea-815f-80c238f47827.png)

If you want to avoid setting values as `null/undefined`, we need a way to revert those values to its original default behaviour. When I think about reverting any library or whatever to its default behaviour, I think to set it to its default value, hence setting "color" to `undefined` here. I think that if a value is invalid for a property it should not be the default value. It means that by default the property is invalid.

Also, in Highcharts there are a lot of properties that revert to default behaviour succesfully when are set to its default `null/undefined` value (specially the ones that are autocalculated when they are set to `null`), but there are properties that not (like point color, which is autocalculated by default but you cannot revert to autocalculation default behaviour). I still think that is a behaviour mismatch between different properties actually.

**Comment by Llorx** [comment]
UPDATE: Is easy. When you modify a series color, it gets regenerated from almost zero, so it calls `this.getColor();` which calculates the new color. But when you change a point color it won't call `this.resolveColor();` so will keep the color property to `undefined`. The mismatch in code is that series do calculate the color when the color is updated but the point not.

Right now I'm going to do a small workaround where I will call `point.resolveColor()` after a color update, but I guess that this is an internal thing: https://jsfiddle.net/f0ord1pn/

**Comment by pawelfus** [comment]
> Without this option working the same as series, how can I select a default value from the options.colors array in a point the same way as a series do? Right now I see a small limitation here.

Simply store it before setting a new color (https://jsfiddle.net/BlackLabel/La7gztn0/). Or, if it's possible (depends on your requirements), consider using `point.select()` with defined selected state: https://jsfiddle.net/BlackLabel/vuxLhq3f/ (or `point.setState('select')`).

The key point here is how `Series.update()` and `Point.update()` methods work. In `point`, we update necessary items (e.g. updated marker? destroy and recreate it, updated value? just move marker, updated dataLabel? destroy and recreate it etc).

For series, it's completely different: https://api.highcharts.com/class-reference/Highcharts.Series#update

> For a clean and precise handling of new options, all methods and elements from the series are removed, and it is initialized from scratch.

Regarding this:
> Also, in Highcharts there are a lot of properties that revert to default behaviour succesfully when are set to its default null/undefined value

Still, I'm not sure if this is the safe solution. Only types defined in docs are supported and these should be used. If something accidentally works (because of the workflow or just because of JavaScript) then it's fine.

I'm leaving the decision here up to @TorsteinHonsi

**Comment by Llorx** [comment]
Yep. I get your point.
