### ISSUE TITLE
Legend LabelFormatter style applied with <br />

### ISSUE THREAD

**Issue by MitchMcBride** [highcharts/highcharts#1290]
Legend LabelFormatter styles applied on text containing a `<br />` doesn't applied styles to all lines of text.

The style is only applied to the first tspan element and not subsequent ones.

http://jsfiddle.net/ArmRM/14803/

**Comment by sebastianbochan** [comment]
Set the useHTML parameter  for legend / tooltip, then styles are applied for all lines.
