### ISSUE TITLE
minPadding and maxPadding not effective when data is flat

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#12916]
Not sure if this is a bug or is expected.

With padding set as follows:

        minPadding: 0.0,
        maxPadding: 0.9

I expect the curve to sit tight to the bottom of the chart, with space above.

This is indeed what happens for normal data:

https://jsfiddle.net/96r1hnej/3/

But when the data is flat the line snaps to the middle of the chart:

https://jsfiddle.net/96r1hnej/2/

A workaround is to specify an arbitrary non-zero value for `minRange`:

https://jsfiddle.net/96r1hnej/4/

But should this be necessary?  I'd expect even a flat line to sit in the right place, based on the padding settings.  I know that the issue probably relates to the fact that for flat data the axis has zero range (hence the above workaround) so maybe it's expected, even if slightly annoying.

**Comment by drmrbrewer** [comment]
Related to [this](https://github.com/highcharts/highcharts/issues/6274)?

**Comment by sebastianbochan** [comment]
Hi @drmrbrewer,
In my opinion it is not a bug, because of default functionalities and calculations of axis extremes.

Regarding to the second scenario, the easiest way to place "series line close to bottom" is setting min/max values instead of calculating minRange.

Demo:
- https://jsfiddle.net/BlackLabel/vytqjb4p/

@pawelfus what do you think?

**Comment by pawelfus** [comment]
I agree, this is not a bug. You can prevent that from happening using some options: `minRange`, `min`, `max`, `softMin`, `softMax`, `tickAmount`, `tickPositions`, `tickPositioner`. I believe that's more than enough options to control this behaviour.

Honestly, with flat dataset, (e.g. value=2.5) which extremes do you expect to see? For one user it's 0-10, but other user can say 0-5. Not to mention that `minPadding` and `maxPadding` confuses me even more..

A few years ago I created a plugin to modify extremes for flat datasets (for values > 1): https://jsfiddle.net/BlackLabel/bd89cns7/ - but I have never tested this solution with other configs (e.g. `minPadding`+`maxPadding`), demo: https://jsfiddle.net/BlackLabel/dLs82fm1/.

I agree, it is slightly annoying, but I don't see a perfect solution that satisfy all users..
