### ISSUE TITLE
Variwide chart with stacking - Export is not working while any legend item is disabled

### ISSUE THREAD

**Issue by rajeshdanabal** [highcharts/highcharts#12915]
#### Expected behaviour

When we export variwide chart with a disabled legend item, chart should get exported.

#### Actual behaviour

While we click on legend item and make it disabled then export the chart, it is not exporting and the below errors are showing in console.

![image](https://user-images.githubusercontent.com/33329058/74039657-3ba30080-49e8-11ea-9f67-a7afb82286df.png)

![image](https://user-images.githubusercontent.com/33329058/74039584-1a421480-49e8-11ea-8660-bc14911520d1.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/rajeshdanabal/7tvLo8bc/

* Go to the above fiddle.
* Click on the any legend item and now it will get disabled.
* Click on export menu and choose Download PNG Image.

#### Product version
Highcharts V8.0.0

#### Affected browser(s)
Checked in Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @rajeshdanabal,
Thank you for reporting about the problem. I agree that is the bug.

**Workaround:**
Overwrite the `correctStackLabels` function and add the condition of verifying stacks.

Demo:
- https://jsfiddle.net/BlackLabel/ekfagtnh/

**Comment by pawelfus** [comment]
Last working version: v7.1.3

Bisected to commit 9c10762d51
