### ISSUE TITLE
Filtered datasets end up with a line joining between the missing points

### ISSUE THREAD

**Issue by daddyg** [highcharts/highcharts#12919]
#### Expected behaviour
Given a series that contains data for Mondays-Fridays only
And a series that contains data for Fridays and Saturdays only
When plotted in a highstock chart with connectNulls set to false
Then Sundays should not appear in the x-axis at all
And other periods in a series that are not present should not be displayed as a line
![HopesAndDesires](https://user-images.githubusercontent.com/1352786/74142947-d1f64280-4bf1-11ea-99b6-887b40a761ce.png)

#### Actual behaviour
As expected, Sundays are not plotted. The Mon-Fri series has the Friday point connected to the Monday point with a straight line. The Friday - Saturday series has Saturday joined to Friday
![Actual](https://user-images.githubusercontent.com/1352786/74140449-fc91cc80-4bec-11ea-8000-6e75625942e1.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/4e2xu6yc/1/

#### Product version
Licensed version is 6.0.1, but replicated against the latest version in jsfiddle

#### Affected browser(s)
I imagine all, but only tested in Chrome

**Comment by pawelfus** [comment]
Hi @daddyg 

Thanks for reporting the issue. This is expected behaviour, let me explain:
- your datasets don't have null points
- instead of [`series.connectNulls`](https://api.highcharts.com/highstock/series.line.connectNulls) you want to use [`series.gapSize`](https://api.highcharts.com/highstock/series.line.gapSize) option: https://jsfiddle.net/BlackLabel/1zs7by6t/

**Comment by daddyg** [comment]
Hi @pawelfus ,

The problem with gap size is that Sundays are now displayed in the x-axis, where they previously were removed completely form the x-axis. So, whilst it fixes one problem, it introduces another, and I cannot find an elegant and reliable way to work around this. The best I can do is to loop through all my data sets at the point of building the chart and finding the commonly excluded points. I than add all these as x-axis breaks. Whilst I think this could work it is very unwieldy.

Currently the default functionality of the x-Axis is that it cleverly truncates itself when there are no datapoints for a specific time. Sadly, when another series forces some of these previously excluded points back in, the default decision of highcharts is to join the points before and after the gap together with a line. Using gapSize allows me to tell highcharts that any gap over a certain threshhold is to be considered a gap. Therefore, the bug is that there is no way for me to have the x-axis truncation process working, and for any remaining gaps to be displayed as gaps.

![chart (20)](https://user-images.githubusercontent.com/1352786/74151438-168ad980-4c04-11ea-835a-7a0c60bcfd24.png)

**Comment by daddyg** [comment]
Linking to my original description of the issue here: https://www.highcharts.com/forum/viewtopic.php?f=12&t=43284

**Comment by pawelfus** [comment]
Thanks for the detailed explanation. You can not render 6th of January and 8th of January exactly at the same position on xAxis. Not without using breaks. `ordinal` only positions points equally on xAxis, regardless of the time or x-distance between them. If points have different x-values, then available space will be equally divided between them ([docs](https://api.highcharts.com/highstock/xAxis.ordinal)). In other words, distance between 5th and 6th January should be exactly the same as between 6th and 8th January. And that's how chart is rendered.

Let's say you want to render Monday-Thursday and Friday-Saturday filter: https://jsfiddle.net/BlackLabel/xsvqj74t/ - as you can see, every point has equal distance between each other. Gaps are still visible between series.

**Comment by daddyg** [comment]
Thank you for that explanation, that clears a few things up. I thought the x-axis truncation that is already happening was resulting in multiple points with the same value. Having looked again at the final graph I posted I can now see that there was more interpolation than I had realised.

Carry on the good work, and I will take a look at how I might implement it with x-axis breaks.
