### ISSUE TITLE
Tick sync on two independent yAxis.

### ISSUE THREAD

**Issue by bosseDev** [highcharts/highcharts#12937]
Hi,
I am working on a diagram with 2 independent y-axes. I want to synchronize the ticks from the right axis with the ticks and grid lines from the left axis. 

#### Expected behaviour
with tickPixelInterval both axis should have same tick positions without scaling the series down.

#### Actual behaviour
Either the synchronization of the tick positions do not match but the series are correctly scaled or the series are correctly scaled but the tick positions do not match. =)

#### Live demo with steps to reproduce

I have achieved synchronization with tickPixelInterval, but only with startOnTick and endOnTick enabled. But unfortunately this will scale the series down.
https://jsfiddle.net/chartman2000/wLrf9s7x/5/

Is there a solution to synchronize the ticks and get a correct scaling like in the chart in the second fiddle, where endOnTick and startOnTick are disabled?
https://jsfiddle.net/chartman2000/wLrf9s7x/

( violet, brown and orange series belongs to the left axis  | blue series belongs to the right axis )

**Comment by sebastianbochan** [comment]
Hi @bosseDev,
The github is our bug tracker, so for general [support](https://www.highcharts.com/support) questions please use other channels (forum / stackoverflow or email).

ps. have you tried to use [alignTicks](https://api.highcharts.com/highcharts/chart.alignTicks) option?
