### ISSUE TITLE
drillupButton position not working on responsive

### ISSUE THREAD

**Issue by pitersm** [highcharts/highcharts#12934]
#### Expected behaviour
  When rendered on a mobile viewport (lower than 500px width), the drilldown -> drillUpButton -> position should respect what's established on the responsive setting object.

#### Actual behaviour
  The position of the rendered chart on a mobile viewport does not respect the X and Y values established by the position coordinates inside the responsive settings.

#### Live demo with steps to reproduce
https://jsfiddle.net/pitersm/eksfq3bu/9/

#### Product version
Highcharts 7.2.1

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @pitersm,
Thank you for reporting about the problem.

I simplified your demo here:
- https://jsfiddle.net/BlackLabel/307gu2p8/

When I run the demo, rules are applied correctly (x/y and aligning) - see demo below.

![btn](https://user-images.githubusercontent.com/2115686/74245711-bbc8af00-4ce3-11ea-8fae-0b60200c5bc3.gif)


Please correct me if Im testing the chart incorrectly.

**Comment by pitersm** [comment]
@sebastianbochan Hello. I'm sorry for not mentioning the steps to reproduce.
  Indeed, in your fiddle it works, but your fiddle is much simpler than mine.
  The steps are:
  1)Do not click on the buttons (large, medium). I've set it so that it always render on mobile width (400px)
  2)Do a drilldown. You will then notice that the drillUpButton renders in a place that does not respect the X and Y coordinates inside the responsive section.
  3)Try change the X and Y values for that button's position. It does not work, the button will still render on the same default place.

**Comment by sebastianbochan** [comment]
Hi @pitersm,
I simplified demo again https://jsfiddle.net/BlackLabel/cjpLf4aq/ and it turned out that on init the responsive rules are completely ignored. Could you confirm that it visualize your issue ?

**Comment by pitersm** [comment]
Yeah, this is it.
