### ISSUE TITLE
radar labels display error

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#12938]
#### Expected behaviour
Automatic  hiding the whole labels
#### Actual behaviour

![radar](https://user-images.githubusercontent.com/6789138/74298769-a906b680-4d85-11ea-9daf-f0065b588df3.png)

#### Product version

"highcharts": "8.0.0",
"highcharts-vue": "^1.3.5",
#### Affected browser(s)
版本 78.0.3904.70（正式版本） （64 位）

**Comment by sebastianbochan** [comment]
Hi @wjhcc2018,
Thank you for reporting about the problem. Could you update my demo with your simplified chart's options? It will allow me to debug, because in our default demo, problem does not exist.

https://www.highcharts.com/demo/polar

**Comment by wjhcc2018** [comment]
@sebastianbochan  Thanks for your reply to my question，When I upgraded to version 8.0.2, it was normal

**Comment by sebastianbochan** [comment]
@wjhcc2018 can I close the ticket?

**Comment by wjhcc2018** [comment]
@sebastianbochan  yes  Thank you very much

**Comment by wjhcc2018** [comment]
> @wjhcc2018 can I close the ticket?

yes ,thank you very much
