### ISSUE TITLE
Data label alignment issue while stacking column and area spline

### ISSUE THREAD

**Issue by rajeshdanabal** [highcharts/highcharts#12947]
#### Expected behaviour
While we have column and area spline stacked series and the data label alignment is set to right, both area spline and column's data labels should be aligned right.

#### Actual behaviour
While we have column and area spline stacked series and _the data label's alignment is set to right_, _**area spline's data label is aligned left and column's data label is aligned right.**_ The same is reproducible for datalabel's left alignment too.

#### Live demo with steps to reproduce
https://jsfiddle.net/rajeshdanabal/kuqL6t0n/

#### Product version
Highcharts V8.0.0

#### Affected browser(s)
Checked in Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @rajeshdanabal,
Thank you for contacting us. Let me explain how aligning works. If you set a right value, the right side of the label should be touching the point (anchor point). For points with an extent, like columns, the alignments also dictates how to align it inside the box, as given with the inside option. As a result label is aligned in "area of column" not according to anchor point.

**Comment by rajeshdanabal** [comment]
Thanks for the clarification and detailed explanation @sebastianbochan. Now I understood it.
