### ISSUE TITLE
Using dataSorting in a drilldown bar chart bugs when drilldown/drillup/drilldown again

### ISSUE THREAD

**Issue by vegaelce** [highcharts/highcharts#12949]
#### Expected behaviour

We want to use the new feature dataSorting in a drilldown bar chart. It works nice : the agregate chart is sorted, when we click on the first bar (for example), it display the second level wich is correctly sorted too. We expect to be able to drilldown/drillup many times...

#### Actual behaviour

After the first drilldown, we go back (by the back button) to the first level but when we want to click again on a bar, an error occured

message in the browser : 

Uncaught TypeError: Cannot read property 'point' of undefined
    at w.firePointEvent (highcharts.src.js:26786)
    at w.onMouseOut (highcharts.src.js:39619)
    at c.Pointer.reset (highcharts.src.js:21636)
    at c.Chart.p.applyDrilldown (drilldown.src.js:590)
    at c.Chart.p.addSeriesAsDrilldown (drilldown.src.js:480)
    at c.Chart.<anonymous> (drilldown.src.js:946)
    at c.fireEvent (highcharts.src.js:2442)
    at w.h.Point.doDrilldown (drilldown.src.js:932)
    at w.<anonymous> (drilldown.src.js:1034)
    at highcharts.src.js:2433

Note that this error does not  occure if you use the label link to drill (instead of clicking in the colored bar).

#### Live demo with steps to reproduce

https://jsfiddle.net/vegaelce/Lx21rqdk/

#### Product version

Highchart 8.0.0

#### Affected browser(s)

Google Chrome, Edge

**Comment by pawelfus** [comment]
Thanks for reporting @vegaelce 

FYI @ppotaczek

**Comment by ppotaczek** [comment]
As a workaround disable animation at the chart level:

    chart: {
      ...,
      animation: false
    }

**Live demo:** https://jsfiddle.net/BlackLabel/u86scbgt/
