### ISSUE TITLE
Documentation on DataLabelsFormatterCallbackFunction is wrong

### ISSUE THREAD

**Issue by totszwai** [highcharts/highcharts#12952]
#### Expected behaviour
This documentation:
https://api.highcharts.com/class-reference/Highcharts#.DataLabelsFormatterCallbackFunction

should be similar to:
https://api.highcharts.com/class-reference/Highcharts#.TooltipFormatterCallbackFunction

The DataLabelsFormatterCallbackFunction actually gets call with an argument that is from `plotOptions.<type>.dataLabels`.

```
          plotOptions: {
            column: {
              dataLabels: {
                enabled: true,
                formatter: function(dataLabels) {
                  console.log(dataLabels);
                }
              }
            }
          }
```

Dumping the content of dataLabels, you get this structure:
![image](https://user-images.githubusercontent.com/4440365/74367078-3efb0b00-4d9f-11ea-89f8-c73ad528a26d.png)

And I'm unable to locate the actual type definition in highcharts.d.ts that match the structure, I suspect the DataLebels definition is actually missing as well.

#### Product version
    "highcharts": "^8.0.0",
    "highcharts-angular": "^2.4.0",

**Comment by sebastianbochan** [comment]
Hi @totszwai,
Thank you for reporting about the problem.

FYI @bre1470
