### ISSUE TITLE
X-axis gantt chart label alignment issue

### ISSUE THREAD

**Issue by cvinhar** [highcharts/highcharts#12953]
#### Expected behaviour
On zoom all the data label should be align properly

#### Actual behaviour
On zoom all the x-axis lable y value are wrongly placed

#### Affected browser(s)
![2](https://user-images.githubusercontent.com/46776508/74403513-66ff7280-4e62-11ea-9232-981d7ed64cc9.png)

**Comment by sebastianbochan** [comment]
Hi @cvinhar,
Thank you for reporting about the problem. It looks like the same issue as https://github.com/highcharts/highcharts/issues/12884, but without your code I can only assume. Could you confirm that is the same problem?

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
