### ISSUE TITLE
Y-axis tick goes as low as the x-axis for single values which are bigger than around 4.5035e+15

### ISSUE THREAD

**Issue by ozeno** [highcharts/highcharts#12954]
Y-axis tick goes as low as the x-axis for single values which are bigger than around 4.5035e+15

#### Live demo with steps to reproduce
Change data to 4.5035e+15 and it'll work correctly
https://jsfiddle.net/fbj5scuL/

**Comment by sebastianbochan** [comment]
Hi @ozeno,
Thank you for reporting about the problem. 

You can use tickPositions / tickPositioner / min and max to set proper extremes on the yAxis.

Docs:
- https://api.highcharts.com/highcharts/yAxis
