### ISSUE TITLE
Solid Gauge - "stops" color when provided in hex not working

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/highcharts#12955]
#### Expected behaviour
In my Solid gauge, below is the data stops, max value is 300 and data value is 143.88. Hence I expect to see the color "#0000ff" (which is Blue) in my gauge, but its showing green. Now, if I replace "#0000ff" with "Blue" (thats the only change I made), the gauge will start showing Blue color which is the expected color.

This is my configuration, which is not working.

    "stops": [
      [
        0,
        "#000000"
      ],
      [
        0.11333333333333333,
        "#ff0000"
      ],
      [
        0.19666666666666666,
        "#ff8040"
      ],
      [
        0.28,
        "#ffff00"
      ],
      [
        0.3466666666666667,
        "#00ff00"
      ],
      [
        1,
        "#0000ff"
      ]
    ],

This is the configuration which works (only change I did is I replaced "#0000ff" with "blue")

      [
        0,
        "#000000"
      ],
      [
        0.11333333333333333,
        "#ff0000"
      ],
      [
        0.19666666666666666,
        "#ff8040"
      ],
      [
        0.28,
        "#ffff00"
      ],
      [
        0.3466666666666667,
        "#00ff00"
      ],
      [
        1,
        "blue"
      ]

Why its not showing the correct color when it was hex, but its showing only when I give the color as text.

#### Actual behaviour

Showing wrong color in the Solid gauge.

#### Live demo with steps to reproduce

Below is the link to my jsfiddle, where its shows wrong color in my gauge, if you replace "#0000ff" with 'blue', gauge will start showing blue color.

https://jsfiddle.net/9adLk8ft/1/

#### Product version

Highcharts-4.0.1

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @Sreejithga,
Thank you for reporting about the problem. We have two separate issues here.
1. The green color is correct. Let me explain why. When you have a scale between 0 and 300, the value (143.88) is more or less 0.45/0.5 of the whole range. So the color is extracted not from the last stop (1, because 1 = value 300 not 143.88), but from 0.346 value. 
2. When you apply the "blue" it should not be visible, green should still be here. It is a bug.

**Comment by pawelfus** [comment]
Only rgb(a) and hex colors are supported in this case. Please check documentation: https://www.highcharts.com/docs/chart-design-and-style/colors

> Primarily, Highcharts supports solid colors given in hex format #00FF00 and rgb format rgb(0,255,0).
