### ISSUE TITLE
Sankey doesn't put lines to correct columns

### ISSUE THREAD

**Issue by slesarevns** [highcharts/highcharts#12967]
#### Expected behaviour
Sankey puts lines to correct columns (based on all lines columns not only one line columns)

#### Actual behaviour
When we don't have the previous column (in one line case) the sankey puts the 3rd column line to the 1st column (based on all lines we have more than 5 columns)
#### Live demo with steps to reproduce
Hello, as we can see, 3rd columns lines start from 1st column because they don’t have previous columns (but based on all lines we have more than 5 columns), it’ll be nice if 3rd columns lines will start from 3rd column (based on all lines columns not only one line) or at least any solution for now how to remove such of type lines?
![Без названия (60)](https://user-images.githubusercontent.com/10522353/74542770-dbaedb80-4f4c-11ea-98f7-b157c63cf670.png)

#### Product version

7.2.0

Affected browser(s)
Chrome, Firefox

**Comment by pawelfus** [comment]
Hi @slesarevns 

There's an option for that, see [`series.nodes.column`](https://api.highcharts.com/highcharts/series.sankey.nodes.column).
