### ISSUE TITLE
'dashStyle' does not exist in type SeriesColumnOptions

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/highcharts#12971]
#### Expected behaviour
`dashStyle` should be a valid property on SeriesColumnOptions.

#### Actual behaviour
TypeScript is complaining of `'dashStyle' does not exist in type SeriesColumnOptions`,
even though Highcharts is actually picking up the option and using it in the visualization.

This seems to be a mistake as dashStyle is documented in series.column: https://api.highcharts.com/highcharts/series.column.dashStyle

But the option is possibly missing from plotOptions.column: https://api.highcharts.com/highcharts/plotOptions.column

#### Live demo with steps to reproduce
https://stackblitz.com/edit/typescript-ctjps3?file=index.ts

#### Product version
v8.0.0

#### Affected browser(s)
All

**Comment by bre1470** [comment]
Hello @jon-a-nygaard,
Thank you for reporting the issue. :)

**Comment by jon-a-nygaard** [comment]
Hi @bre1470 😄 

I have not checked if this may already be fixed by the PR, but I noticed the same issue with `annotations[].shapeOptions.dashStyle`. See https://stackblitz.com/edit/typescript-uulcxu?file=index.ts

Should I create a separate issue for it?

**Comment by bre1470** [comment]
I am not sure about annotations as it is not a clear `@excludes` bug.

@wchmiel Does `annotations.shapeOptions` lack a `dashStyle` option? And if so, should this be a separate issue report?

**Comment by pawelfus** [comment]
Cheers @jon-a-nygaard :)
`annotations.shapeOptions.dashStyle` works fine: https://jsfiddle.net/BlackLabel/qohf7se6/ - so I would add this to TS definitions and API.

**Comment by bre1470** [comment]
I added `annotations.shapeOptions.dashStyle` in the PR. No separate issue needed.
