### ISSUE TITLE
Giving 404 Error Code

### ISSUE THREAD

**Issue by abhinav-goyall** [highcharts/highcharts#12977]
#### Expected behaviour
While going through the documentation i came across highstock and on the below mentioned URL there is one links as FAQ Item which on clicking giving 404.

So please check is this expected behaviour or not?

PFB URL:
https://www.highcharts.com/blog/docs/getting-started/frequently-asked-questions#highstock-features-in-highcharts

**Comment by KacperMadej** [comment]
Hi @abhinav-goyall 

Thank you for reporting the problem.

The correct link is probably https://www.highcharts.com/docs/getting-started/frequently-asked-questions#can-i-use-features-from-highstock-in-highcharts

Where have you found the wrong URL?

**Comment by abhinav-goyall** [comment]
hi @KacperMadej 

I have found this on below URL:
https://www.highcharts.com/docs/stock/flag-series

Hyperlink Text: FAQ Item

**Comment by KacperMadej** [comment]
Thank you!
This should be fixed soon.
