### ISSUE TITLE
UseHTML is ignored for rotated data labels

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#12986]
#### Expected behaviour
useHTML is honored by all data labels

#### Actual behaviour
useHTML is ignored by rotated data labels

#### Live demo with steps to reproduce
https://jsfiddle.net/kzoon/6nys12kh/

Probable cause: 

Series.prototype.drawDataLabels contains a call to renderer.text that omits the useHTML parameter:
                                  // Labels don't rotate, use text element
                                    renderer.text(labelText, 0, -9999)
should be 
                                  // Labels don't rotate, use text element
                                    renderer.text(labelText, 0, -9999, labelOptions.useHTML)

#### Product version
Latest

#### Affected browser(s)
All

**Comment by bre1470** [comment]
Hello @kzoon! Thank you for reporting the issue. We will investigate and fix it. Best regards.

**Comment by bre1470** [comment]
The issue was already fixed in the master branch and will be part of the next update. (See https://github.com/highcharts/highcharts/pull/12921, Demo: https://jsfiddle.net/c67trhs5/)
