### ISSUE TITLE
Bubble Chart Tooltips Issue *Urgent

### ISSUE THREAD

**Issue by hartbert95** [highcharts/highcharts#12981]
#### Expected behaviour
When Hover to the simosSept19<V03, tooltips will display simosSept19<V03

#### Actual behaviour
When hover to simosSept19<V03, tooltips only display simosSept19, <V03 is missing.

Step 
1. Go to Catalog
2. Click Render Chart
3. Hover to simosSept19<V03
4. the tooltips is displaying without <V03

#### Live demo with steps to reproduce
https://stackblitz.com/edit/highchart-angular-chart-oamkiw?file=app/views/catalog/catalog.component.ts

#### Product version
7.2.1

**Comment by sebastianbochan** [comment]
Hi @hartbert95,
The github is our bug tracker. So for general [support](https://www.highcharts.com/support) questions please use other channels like stackoverflow / forum or email.

p.s When I run your demo I see only LOGIN title and two extra links. Based on yoru description, I guess that its problem with `<` tag. Please try to set the [useHTML](https://api.highcharts.com/highcharts/tooltip.useHTML) option in chart's config. If it will not work, use entity like: `&lt;`

**Comment by hartbert95** [comment]
Hi, to access to the chart, click on the third link, catalog, and click render chart. i have set the useHTML as well. because the naming is dynamic so i can't have fix entity there

**Comment by pawelfus** [comment]
@hartbert95 - I believe you can fix entities there, simply replace `<` with `&lt;`, demo: https://stackblitz.com/edit/highchart-angular-chart-sykrwr?file=app/views/catalog/catalog.component.ts

**Comment by hartbert95** [comment]
Hi @pawelfus , It's work well, thanks, but can i know the reason why '<' is not rendered properly?

**Comment by sebastianbochan** [comment]
@hartbert95,
In general its related with our renderer functionality. The issue is more global and related i.e with the ticket: https://github.com/highcharts/highcharts/issues/12701
