### ISSUE TITLE
Gantt collapsed tasks added via addSeries

### ISSUE THREAD

**Issue by tony-co** [highcharts/highcharts#12984]
#### Expected behaviour
Tasks should be collapsed

#### Actual behaviour
Tasks are not collapsed when series are added via addSeries (see jsfiddle)

#### Live demo with steps to reproduce
https://jsfiddle.net/tony_cosentino/tn0u2frq/7/

#### Product version
Gantt 8.0.0

#### Affected browser(s)
I'm on Chrome but probably all are affected ?

**Comment by sebastianbochan** [comment]
Hi @tony-co,
Thank you for reporting about the problem.

_Internal note_
The issue is related with https://github.com/highcharts/highcharts/issues/9980 and https://github.com/highcharts/highcharts/issues/11350.

@oysteinmoseng
