### ISSUE TITLE
The pyramid 3d is cut at the bottom edge.

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#12980]

**Comment by sebastianbochan** [comment]
Hi @weixingcai,
Thank you for sharing your link. Could you elaborate your problem / bug ? Is it a problem with datalabels or different?

**Comment by weixingcai** [comment]
你看一下我给你发的连接 下面显示不全呀

**Comment by weixingcai** [comment]
仿佛被切掉了一块的 https://jshare.com.cn/temp/BPGrXQ 看一下这个

**Comment by sebastianbochan** [comment]
Hi @weixingcai,
Thank you for reporting.

**Description:**
The funnel is cut at the bottom edge.

**Workaround**
You can declare `spacingBottom: 40` param.

Docs:
- https://api.highcharts.com/highcharts/chart.spacingBottom

ps. please use English language, it will allow us to communicate more efficient.
