### ISSUE TITLE
Click event en line chart

### ISSUE THREAD

**Issue by comoriano76** [highcharts/highcharts#12988]
Hello,
I would like to knwo how can I put on url the date information stored in categories. 
Like thie : http://localhost/index.php?r=openbydate&month=02-2019

Any helps are Welcome  :D 

`

$(function () {
    var chart;

    $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'conReportByQueueClosed',
                type: 'spline',
                marginRight: 130,
                marginBottom: 25
		
            },
            title: {
                text: 'Stats Titre',
                x: -20 //center
            },
            subtitle: {
                text: 'Source: Kace',
                x: -20
            },
            xAxis: {
                categories: ['09-2019','10-2019','11-2019','12-2019','01-2020','02-2020']
            },
            yAxis: {
                title: {
                    text: 'Tickets'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
				crosshairs: true,
                formatter: function() {
                        return '<b>'+ this.series.name +'</b><br/>'+
                        this.x +': '+ this.y + (this.series.name=='File1'?' ouverts':
											(this.series.name=='Reouvert file'?' ont été ouverts':' ouverts'));
											
                }
            },			
			    plotOptions: {
        series: {
            point: {
                events: {
                    click: function () {
                        window.location.href = this.series.options.website;
                    }
                }
            },
            cursor: 'pointer'
        }
    },	
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'top',
                x: -10,
                y: 45,
                borderWidth: 0
            },
            series: [{
                name: 'Titre1',
                data: [10 ,20 ,30],
				website: 'http://localhost/index.php?r=openbydate&month='+ this.x

            }
			, {
                name: 'Titre2',
                data: [70,80,90,50,70,35] ,
				website: 'http://localhost/index.php?r=openbydate&month='+ this.x
            } 

			]
        });
    });
    
});
	`

Regards.

**Comment by sebastianbochan** [comment]
Hi @comoriano76,
Thank you for contacting us. The github is our bug tracker, so for general [support](https://www.highcharts.com/support) questions please use other channels like stackoverflow / email or forum.

ps. you can use [tooltip.formatter](https://api.highcharts.com/highcharts/tooltip.formatter) and customize the tooltip's content to show custom param.
