### ISSUE TITLE
Pie datalabel y position offset ignored on points

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#12985]
#### Expected behaviour
I can set the y position offset per point

#### Actual behaviour
The  y position offset per point is ignored

#### Live demo with steps to reproduce
See https://jsfiddle.net/kzoon/fvcs1h8x/
The data label y position offset of -30 specified for Firefox is ignored in favor of the -3 specified for the pie chart.

(I am trying to correct the position of data labels that have a different font size)

#### Product version
Latest

**Comment by pawelfus** [comment]
Hi @kzoon 

Thanks for reporting the issue. `series.data[].dataLabels.y` (and `x`) were never implemented for a pie chart - it's a bug in docs. I don't see any reason for this inconsistency for a pie series - I think we should add it (so it will work just like in column: https://jsfiddle.net/BlackLabel/5t1zd8as/)

**Comment by kamilkulig** [comment]
Thank you for reporting the problem @kzoon - it's a bug.
_Internal note:_
It seems that pie series has always ignored `data[i].dataLabels.y` properties.
