### ISSUE TITLE
Tests: A test seems to be failing at random or is unstable

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#12982]
#### Behaviour
There is an unstable test or a sign of instability of the tests environment shown in this PR as the failed visual test result - https://github.com/highcharts/highcharts/pull/12978

fyi: @activist 

More details:
The test is `series-packedbubble/spiral`.
The difference is in the opacity of a single element. Looks like this could be related to some unfinished animation or, as @pawelfus suggested, related to `defer`.

**Comment by TorsteinHonsi** [comment]
In general, all animation should be [turned off by default in karma-setup.js](https://github.com/highcharts/highcharts/blob/master/test/karma-setup.js/#L32-L86). Are we missing some opacity animation option in the packed bubble?

**Comment by KacperMadej** [comment]
(Packed bubble question - fyi: @Izothep @sebastianbochan )

**Comment by Izothep** [comment]
In case of spiral packing, layoutAlgorithm animation is not used at all. The only animation is related to standard bubble series, which looks to be disabled in karma-setup. 

I would like to take a deeper look into this issue.

**Comment by pawelfus** [comment]
It's quite strange that we can observe the issue with only one dataLabel..

**Comment by Izothep** [comment]
Ok, I believe I have found the problem. 

It looks that the issue is simply related to allowOverlap functionality of dataLabels. When `allowOverlap: true` is not set, with current graph width the one differing dataLabels is getting hidden by fading out. 

Live example:
https://jsfiddle.net/BlackLabel/zmt9vu3x/
