### ISSUE TITLE
The chart time interval is incorrect

### ISSUE THREAD

**Issue by sungwonsojang** [highcharts/highcharts#12995]
#### Expected behaviour
2 minutes interval of build of candlestick

#### Actual behaviour
Change from two minutes to one minute
But, Operate normally for several minutes

#### Live demo with steps to reproduce

http://star.comlex.co.kr/rent/basic/gbp/aud/2
testid : test/12345

#### Product version
Highcharts ver 

#### Affected browser(s)
Crome

**Comment by pawelfus** [comment]
Hi @sungwonsojang 

Thanks for reporting the issue. Could you attach a screenshot which time interval is wrong? Thanks!

**Comment by sungwonsojang** [comment]
p{margin-top:0;margin-bottom:0}
    


    
Thank  you for your consideration. 


                                                                                                                                                                                                                                                                    송지훈                                                                                                    CTO|연구소장                                                                                                    t 1666-9652|m  010-4709-2797|e  cto@comlex.co.kr                                                                                                    H.Q : 경기도 안양시 만안구 안양로 401 3F (우) 13988
Lab : 경기도 안양시 만안구 안양동 517 202호 (우) 14034                                                                                                                                                                                                            

--------- 원본 메일 ---------

    
        보낸사람: Paweł Fus <notifications@github.com>
        받는사람: highcharts/highcharts <highcharts@noreply.github.com>
        
            참조: sungwonsojang <assbulldozer@daum.net>, Mention <mention@noreply.github.com>
        
        날짜: 20.02.21 00:00 GMT +0900
        제목: Re: [highcharts/highcharts] The chart time interval is incorrect (#12995)
        
        
    
    
        Hi @sungwonsojang
Thanks for reporting the issue. Could you attach a screenshot which time interval is wrong? Thanks!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by sebastianbochan** [comment]
Hi @sungwonsojang,
Could you describe your problem in more details and attach some screenshots? Currently we are not able to know where exactly problem is.

**Comment by sungwonsojang** [comment]
p{margin-top:0;margin-bottom:0}
    


    
I want a candlestick of 2minutes chart.

But as the screensht shows, it changes from a 2 minutes to a 1 minute chart.

                                                                                                                                                        송지훈                                                                                                    CTO|연구소장                                                                                                    t 1666-9652|m  010-4709-2797|e  cto@comlex.co.kr                                                                                                    H.Q : 경기도 안양시 만안구 안양로 401 3F (우) 13988
Lab : 경기도 안양시 만안구 안양동 517 202호 (우) 14034                                                                                                                                                                                                            


--------- 원본 메일 ---------

    
        보낸사람: Sebastian <notifications@github.com>
        받는사람: highcharts/highcharts <highcharts@noreply.github.com>
        
            참조: sungwonsojang <assbulldozer@daum.net>, Mention <mention@noreply.github.com>
        
        날짜: 20.02.21 18:08 GMT +0900
        제목: Re: [highcharts/highcharts] The chart time interval is incorrect (#12995)
        
        
    
    
        Hi @sungwonsojang,
Could you describe your problem in more details and attach some screenshots? Currently we are not able to know where exactly problem is.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by pawelfus** [comment]
Hi @sungwonsojang 

There's no attached image in your message. Instead of answering via email, please answer directly  in the github issue. Thanks!

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
