### ISSUE TITLE
xAxis labels wrong when update charts highcharts v8.0.0 

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#12993]
#### Expected behaviour

![1](https://user-images.githubusercontent.com/6789138/74916649-32ab2980-5401-11ea-8252-fda01636f73c.png)

#### Actual behaviour
![2](https://user-images.githubusercontent.com/6789138/74916667-39d23780-5401-11ea-80a1-c3e74a0ba9b8.png)

#### Live demo with steps to reproduce

Live demo：https://jshare.com.cn/temp/ZIGG0s
#### Product version

 "highcharts": "8.0.0",
    "highcharts-3d": "^0.1.7",
    "highcharts-grouped-categories": "^1.1.3",
    "highcharts-regression": "^2.0.1",
    "highcharts-vue": "^1.3.5",

**Comment by sebastianbochan** [comment]
Hi @wjhcc2018 
Thanks for reporting the issue, but you reported this in wrong repo, please use grouped-categories one: https://github.com/blacklabel/grouped_categories
