### ISSUE TITLE
xAxis render wrong when useHTML:true and change rotation

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#12992]
#### Expected behaviour

xAxis can render correctly
![QQ图片20200220160342](https://user-images.githubusercontent.com/6789138/74912934-9847e780-53fa-11ea-852e-211d539b5504.png)

#### Actual behaviour
![QQ图片20200220160414](https://user-images.githubusercontent.com/6789138/74912967-ab5ab780-53fa-11ea-95dc-ba965dac9c90.png)

#### Live demo with steps to reproduce

Live demo : https://jshare.com.cn/temp/SeGrWa
#### Product version

   "highcharts": "8.0.0",
    "highcharts-3d": "^0.1.7",
    "highcharts-grouped-categories": "^1.1.3",
    "highcharts-regression": "^2.0.1",
    "highcharts-vue": "^1.3.5",

**Comment by sebastianbochan** [comment]
Hi @wjhcc2018 
Thanks for reporting the issue, but you reported this in wrong repo, please use grouped-categories one: https://github.com/blacklabel/grouped_categories
