### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by abhinav-goyall** [highcharts/highcharts#12990]
When i am trying to access the below Link it should not return me 404 error code.
https://www.highcharts.com/blog/contribute  .

This page should ideally be get loaded.

But this page is not getting loaded , when i am navigating to contribute from the below URL:
https://www.highcharts.com/docs/index

Hyperlink Text:  Contribute under Developer Section in footer.

I am reading the documentation in Chrome. But i guess it will be same across all the browsers. Please check.

**Comment by goransle** [comment]
Hi @abhinav-goyall, thank you for letting us know. This link is meant to take you to https://www.highcharts.com/blog/community/.

Our webmasters have been informed, and the link should be fixed soon.

**Comment by abhinav-goyall** [comment]
Thanks @goransle
