### ISSUE TITLE
ScrollablePlotArea minHeight is not responsive

### ISSUE THREAD

**Issue by krzysiek3d** [highcharts/highcharts#12991]
#### Expected behaviour
When You change the window height from beneath scrollablePlotArea minHeight value to above the scrollablePlotArea minHeight, then the chart should not have vertical scroll bar and should fit whole height container.

#### Actual behaviour
When You change the window height beneath scrollablePlotArea minHeight value and then change again the height of window to be above, then the chart stays with fixed height and scroll.

#### Live demo with steps to reproduce
https://jsfiddle.net/zqtkoc8p/9/
Steps:
1. Resize the window height to be less than 400px
2. Resize the window height to be more than 400px

#### Product version
from Highcharts 7.1.2 to Highcharts 8.0.0

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @krzysiek3d,
Thank you for reporting about the problem. 

_Internal note_
Can be related with https://github.com/highcharts/highcharts/issues/11209

**Comment by krzysiek3d** [comment]
Hi @sebastianbochan 
 "2. Responsive rules seem to be ignored -> https://jsfiddle.net/BlackLabel/rndzcwxv/" when You comment out the minHeight inside scrollablePlotArea object the chart is fully responsive.
When do You fix this issue ?

**Comment by pawelfus** [comment]
ETA on fixing this issue is not specified @krzysiek3d

**Comment by krzysiek3d** [comment]
I have a workaround for this just add to css
.highcharts-scrolling {
  height: 100% !important;
}

Maybe with this You can add the fix to next version of highcharts ?

**Comment by pawelfus** [comment]
Thanks! We will check this.
FYI @TorsteinHonsi
