### ISSUE TITLE
Crosshairs + shared tooltip causes focus issues

### ISSUE THREAD

**Issue by KrishnaKumarHariprasannan** [highcharts/highcharts#13002]
#### Expected behaviour
Crosshairs should focus on the serie that is closest to the mouse pointer

#### Actual behaviour
Only the first series gets focused

#### Live demo with steps to reproduce
https://jsfiddle.net/z1b64ksd/

#### Affected browser(s)
Chrome

I'll note that this is not the case when tooltip.shared == false.

**Comment by pawelfus** [comment]
Thanks for reporting!

**Workaround:**
Bind every series to a separate yAxis, so each series will get it's own crosshair. Note that the design with multiple yAxes can be different from the same with just one yAxis. Demo: https://jsfiddle.net/BlackLabel/jh08zLr4/

*Internal note:*
This happens here:
https://github.com/highcharts/highcharts/blob/5d7a807ace923cabcbe2f896b437d7a356e577d8/ts/parts/Pointer.ts#L2087-L2101

Where `find()` gets the first point connected to the axis without considering distance to the pointer/cursor.
