### ISSUE TITLE
Chart style not work in scrollablePlotArea

### ISSUE THREAD

**Issue by sirhvd** [highcharts/highcharts#13001]
#### Expected behaviour
```
chart :  {
        className: 'relative-pos',
        style   : {
            fontFamily: 'Roboto',
        },
        scrollablePlotArea: {
            minWidth: 800
        },
},
```
Chart style will apply styles, class to all fixed and scrolling container (**highcharts-fixed and highcharts-scrolling**).

In my case, it's should apply **fontFamily: 'Roboto' to "highcharts-fixed"** too.

#### Actual behaviour
Chart style only applies styles to **highcharts-scrolling**. 

#### Live demo with steps to reproduce
http://jsfiddle.net/sirhvd/7xdsg6ez/

#### Product version
Highcharts 8.0.0

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @sirhvd,
Thank you for contacting us. When I run your demo the font is applied on labels, tooltip like on screenshot.

Could you elaborate your problem? Do you mean that the font is missing in legend's items?

**Comment by sirhvd** [comment]
I'm creating Highchart with options:
```javascript
       chart: {
         renderTo: 'draw_chart_kpi_csat_chinhanh',
         height: 350,
         type: 'column',
         style: {
           fontFamily: 'Roboto',
         },
         scrollablePlotArea: {
           minWidth: 2000
         },
       },
```

I'm using font Family 'Roboto' for the chart. But seem likes font Family not applied to the chart.

Font family only applied to the elements which inside container have id = **' highcharts-scrolling'**. 

The expected result is font family will apply to the elements inside container have id =**'highcharts-fixed'** too.

You can use Developer tools ( Inspect ) on browsers to check for it.

**Comment by pawelfus** [comment]
Thanks for the explanation @sirhvd ! You are right, fontFamily is missing (in general styles are not applied).

Simplified demo: https://jsfiddle.net/BlackLabel/3qdafhu4/
