### ISSUE TITLE
Documentation is missing for Packed Bubble plot options

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#13009]
All or most of items documented for [Packed Bubble series](https://api.highcharts.com/highstock/series.packedbubble) should be shown for [Packed Bubble plot options](https://api.highcharts.com/highstock/plotOptions.packedBubble), but currently only data labels is shown.
#### Expected behaviour
![image](https://user-images.githubusercontent.com/9820084/75100513-2ed10000-55d7-11ea-9431-11e94e00060d.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/9820084/75100511-1fea4d80-55d7-11ea-8ae8-2b1f1b5a5175.png)

**Comment by sebastianbochan** [comment]
Hi @alvarezguille,
Thank you for reporting about the problem.

FYI @bre1470 @Izothep

**Comment by bre1470** [comment]
@Izothep 
Should packed bubble show up in Highstock? Bubble series does, but there are quite a few product limitations to Highcharts in the packed bubble doclets.

**Comment by bre1470** [comment]
After internal discussion it is now clear, that packed bubble series is only part of Highcharts. Therefor the series options tree is misleading.
