### ISSUE TITLE
highcharts legends doesn't upgrade

### ISSUE THREAD

**Issue by mosijava** [highcharts/highcharts#13008]
#### Bug Description
I use Highcharts in react and as soon as I upgrade to version 8. I notice a bug in piechart legends which doesn't upgrade when series data is upgraded or when I drilldown.

#### Live demo with steps to reproduce
you can see the bug in the sandbox link below.
just click on pie chart to see the drilldown series and drill up again.

https://codesandbox.io/s/highcharts-react-simple-chart-oowgy

#### Product version
Highcharts version 8

**Comment by sebastianbochan** [comment]
Hi @mosijava 
Thanks for reporting the issue, but you reported this in wrong repo, please use react wrapper one:   https://github.com/highcharts/highcharts-react

**Comment by mosijava** [comment]
Hi @sebastianbochan 
I think this bug is not related to the react wrapper.
as you can in see in this fiddle:
https://jsfiddle.net/mosijava/9bs4xqjm/1/

**Comment by sebastianbochan** [comment]
Hi @mosijava,
Thank you for details. The bug has been already fixed in the master branch: https://jsfiddle.net/BlackLabel/8ka3gx0m/ and will be a part of the next official release.
