### ISSUE TITLE
Another Broken Link in Footer -- For Wrappers and AddOns

### ISSUE THREAD

**Issue by abhinav-goyall** [highcharts/highcharts#13010]
Please check the below 2 links in the footer which are giving 404 Error Code.

https://www.highcharts.com/blog/wrappers

https://www.highcharts.com/blog/addons

Please check and get it corrected.

**Comment by pawelfus** [comment]
Thanks for reporting @abhinav-goyall 

Could you point us to the site where we listed those links? We will fix that. Thanks!

**Comment by pawelfus** [comment]
Fixed, thanks once again @abhinav-goyall 

Let us know if you find any other dead links!

**Comment by abhinav-goyall** [comment]
Thanks @pawelfus . Sure i will let you know.
