### ISSUE TITLE
xAxis labels disappears with set step after responsive rules has been applied

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#13011]
xAxis labels disappear after responsive rules have been applied with the step feature. The issue is visible while the window resizing.

#### Live demo with steps to reproduce

Demo to test: https://jsfiddle.net/BlackLabel/56pgtz19/

Gif to see the issue: https://imgur.com/gallery/0jW80gA 

#### Product version

Highcharts JS v8.0.0 (2019-12-10)

**Comment by KacperMadej** [comment]
Isn't this how the `step` should work?

> [...]show only every n'th label on the axis, set the step to n. Setting the step to 2 shows every other label.

https://api.highcharts.com/highcharts/xAxis.labels.step

**Comment by Basts** [comment]
@KacperMadej Actually, you are right, my mistake - I understood it wrongly.
