### ISSUE TITLE
windbarb profile plot vector placement

### ISSUE THREAD

**Issue by cgalvarino** [highcharts/highcharts#13013]
#### Expected behaviour
I would expect to see the windbarbs collocated with the points on a line for a wind profile plot.

#### Actual behaviour
Initial render:
![image](https://user-images.githubusercontent.com/180985/75175115-bb76dd80-56ff-11ea-8d1a-f11d29bbccea.png)

After hide / show render:
![image](https://user-images.githubusercontent.com/180985/75175142-c893cc80-56ff-11ea-965b-6c7675d94455.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/4u7fse05/

#### Product version
8

#### Affected browser(s)
Tested w/ chrome.

**Comment by sebastianbochan** [comment]
Hi @cgalvarino,
Thank you for reporting. Generally, for a [support](https://www.highcharts.com/support) question, please use other channels like forum / stackoverflow or email.


ps. Both series should be sorted by x ascending. Use sorted value and `chart.inverted` option to draw chart like you requested.

Demo:
- https://jsfiddle.net/BlackLabel/617spndt/
