### ISSUE TITLE
rangeSelector buttons are anchored incorrectly

### ISSUE THREAD

**Issue by KrishnaKumarHariprasannan** [highcharts/highcharts#13014]
#### Expected behaviour
rangeSelector buttons to be right aligned correctly according to the position of yAxis

#### Actual behaviour
In stock charts, changing the default yAxis alignment, results in incorrect anchoring of rangeSelector buttons

#### Live demo with steps to reproduce
https://jsfiddle.net/h9g3eLm2/5/

#### Product version
Highstock - 8.0.0

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @KrishnaKumarHariprasannan,
Thank you for reporting about the problem.

**Workaround:**
Set a negative value of x param.

Demo:
- https://jsfiddle.net/BlackLabel/2wsdum75/

_Internal note_
The issue is related with disabled exporting icon.
