### ISSUE TITLE
Highcharts tooltip does not automatically close when scrolling

### ISSUE THREAD

**Issue by ngovanbon16** [highcharts/highcharts#13021]
Expected behavior: Tooltip will be lost if the user scrolls the page.
Actual behavior: Tooltip is not lost when the user scrolls the page

Live demo with steps to reproduce
https://youtu.be/EDkvMb2qy20
Code demo: https://jsfiddle.net/ngovanbon16/7j49ehxL/6/
Product version: 8.0.0

**Comment by KacperMadej** [comment]
Hi @ngovanbon16 

Thank you for reporting - this is already reported here: https://github.com/highcharts/highcharts/issues/11635
Closing as a duplicate.
