### ISSUE TITLE
Line series above axis space when zooming

### ISSUE THREAD

**Issue by miguelpinto98** [highcharts/highcharts#13027]
Hi

I am using Highcharts with Angular 9 and i found a issue when the query params of routing changes affect the chart zooming.

Basically the data on chart change based on the query params of the url and if i click to make zoom on chart the series appears to be above y axis.
Check the image.

#### Expected behaviour 
![Expected Behaviourt](https://i.ibb.co/fk3h3GT/Screenshot-2020-02-26-at-18-39-06.png)

#### Actual behaviour
![Actual Behaviourt](https://i.ibb.co/z2b3KH1/Screenshot-2020-02-26-at-11-48-38.png)

I already tried to change the z-index of axis, series... but nothing works.
Note: the first loaded chart don't have the problem with the zoom, it only appears when we change the query params dynamically.

I created a little sandbox to reproduce this problem. Only appears in Chrome with this example (but in the project I have in safari too).

#### Live demo with steps to reproduce
Steps:
1. Click on tab1 or tab2
2. Make zoom

[https://codesandbox.io/s/highcharts-angular-wrapper-route-bug-8g8wq?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/highcharts-angular-wrapper-route-bug-8g8wq?fontsize=14&hidenavigation=1&theme=dark)

^ This sandbox use the highchairs-angular wrapper.

v This another one, only use the library:
[https://codesandbox.io/embed/highcharts-angular-route-bug-zb431?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/highcharts-angular-route-bug-zb431?fontsize=14&hidenavigation=1&theme=dark)

#### Product version
 Highcharts

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thanks for reporting the issue, it's already reported, see #5244 - closing as a duplicate.
