### ISSUE TITLE
Issue with auto margin computation

### ISSUE THREAD

**Issue by KrishnaKumarHariprasannan** [highcharts/highcharts#13025]
#### Expected behaviour
stockChart to compute the margin in relation to other elements above the plot area

#### Actual behaviour
margin computed is quite large when both the legend and rangeSelector are placed above the plot area

#### Live demo with steps to reproduce
https://jsfiddle.net/5v3L1jch/2/

Product version
Highstock - 8.0.0

Affected browser(s)
Chrome

Note: This can be worked around by setting a margin in userland but I find the auto computed margin to be extremely useful so I'd prefer if we don't have to set the margin manually.

**Comment by pawelfus** [comment]
Thanks for reporting this issue @KrishnaKumarHariprasannan 

Most probably both margins, from rangeSelector and legend, are accumulated - instead the max size of both should be used (if possible).

As you noticed, you can workaround this by setting fixed margin with different [`responsive.rules`](https://api.highcharts.com/highcharts/responsive).

**Comment by pawelfus** [comment]
**Simplified demo:**
https://jsfiddle.net/BlackLabel/s1notcj9/

*Internal note:*
Legend should be rendered below the rangeSelector.
