### ISSUE TITLE
Series update on piecharts leaves the legend in inconsistent state

### ISSUE THREAD

**Issue by Katona** [highcharts/highcharts#13039]
#### Expected behaviour

Updating the series of a piechart should update its legend properly.
#### Actual behaviour
The legend displays the values of the old and new series overlapped.

#### Live demo with steps to reproduce
https://jsfiddle.net/7zLtjb05/

A workaround of triggering a legend update exists:

`chart.legend.update(chart.legend.options);`

**Comment by pawelfus** [comment]
Hi @Katona 

Thanks for reporting the issue. This is already fixed on the master branch and will be part of the next release (ETA: next week).
