### ISSUE TITLE
drillUp function is missing from Chart object 

### ISSUE THREAD

**Issue by mohyeid** [highcharts/highcharts#13037]
#### Expected behaviour
should be able to call `chart.drillUp();`

#### Actual behaviour
Have to do casting to make it work `(<any>this.chart).drillUp();`

#### Product version
8.0.0

#### Affected browser(s)
Typescript

We just upgraded from version 6 to 8, and we were using  `chart: Highcharts.ChartObject;` which no longer exist. Now we switched to use   `chart: Highcharts.Chart;` and found that `chart.drillUp();` is no longer an option. We are creating few custom buttons using the exporting feature which disallow us from using the native drillUp button. Now after upgrading ``chart.drillUp();` is throwing a type error `Property 'drillUp' does not exist on type 'Chart'.ts(2339)` where after casting it to `any` the functionality still work as expected. I think we are missing some typings for `drillUp` function?

**Comment by sebastianbochan** [comment]
Hi @mohyeid,
Thank you for reporting.

FYI @bre1470

**Comment by bre1470** [comment]
Hello @mohyeid! I am not able to reproduce the problem. Your code might lack the necessary import pattern to have `Chart.drillUp` available:
```ts
import * as Highcharts from 'highcharts';
import DrilldownModule from 'highcharts/modules/drilldown';
DrilldownModule(Highcharts);
```
Please let me know, if this solves your problem.

**Comment by mohyeid** [comment]
We are going to try this, but regarding your comment `DrilldownModule(Highcharts); // only one time necessary` 

Where do you suggest doing this? In the module? Or the component? Will it create issues if it was done in the component and the component is being loaded multiple times with different data?

**Comment by bre1470** [comment]
You should add the additional import statement, where you import Highcharts. If you have to write the third line, depends on your deployment target (only for CommonJS).
- If you use AMD / RequireJS, it is not necessary, but as a redundant call also does not hurt.
- If you use CommonJS, the third line will extend the Highcharts namespace with the module additions, when you call it the first time. You can call it multiple times without issues, but it is only once necessary.
- If you use Highcharts in classic mode (as a global namespace) by including each file as a `<script src="…"></script>` in the HTML head, you do not have to do import statements and instead add the files in your [`tsconfig`](https://www.typescriptlang.org/v2/en/tsconfig#typeRoots).
