### ISSUE TITLE
bug or settings？

### ISSUE THREAD

**Issue by HeroMeiKong** [highcharts/highcharts#13046]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/30972348/75656567-2f385d80-5c9f-11ea-9fe1-80edd2317b8f.png)

#### Actual behaviour

**### _pc is normal, but phone is wrong_**

![image](https://user-images.githubusercontent.com/30972348/75656616-46774b00-5c9f-11ea-8c08-7396bfafe6cc.png)

#### Live demo with steps to reproduce

the wrong url => https://bigquant.com/live/mall/strategy?id=12505

#### Product version

 Highstock JS v7.1.3 (2019-08-14)
 (c) 2009-2018 Torstein Honsi

**Comment by sebastianbochan** [comment]
Hi @HeroMeiKong,
Thank you for reporting about the problem. Please let me know about xAxis extremes to reproduce that. I was not able to do that using rangeselector buttons and navigator.

![Zrzut ekranu 2020-03-2 o 10 52 24](https://user-images.githubusercontent.com/2115686/75665193-123a6500-5c74-11ea-9c42-09707933159d.png)


Please ensure that your data is sorted by x ascending. If probllem will still appear, share your browser details.

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
