### ISSUE TITLE
getTimeZoneOffset callback passes inconsistent value type

### ISSUE THREAD

**Issue by mediafreakch** [highcharts/highcharts#13042]
#### Expected behaviour
`time.getTimezoneOffset` should take a parameter `timestamp` that is milliseconds since January 1 1970 [according to docs](https://api.highcharts.com/highstock/time.getTimezoneOffset)

#### Actual behaviour
Effectively `timestamp` is sometimes the number of milliseconds, but also a `Date()` object. I think it depends on what kind of "thing" is being transformed (label, axis, value, ...).

#### Live demo with steps to reproduce
https://jsfiddle.net/tw6gujfv/ (observe in console)

#### Product version
Highcharts JS v8.0.0 (2019-12-10)

#### Affected browser(s)
all

**Comment by mediafreakch** [comment]
On this occasion, maybe also the return type of the function should be documented correctly: It should be [`number`](https://github.com/highcharts/highcharts/blob/f6bd2837d8192c7e637ed58ce47de04e30944c8d/ts/parts/Time.ts#L659) and not `string`.

**Comment by pawelfus** [comment]
Thanks for reporting @mediafreakch 

FYI @TorsteinHonsi, @bre1470

**Comment by bre1470** [comment]
Looks like the documentation is incorrect and we will investigate, why it sometimes provide timestamp instead of Date instance. As timezone information is only available on the Date instance and timestamp is always GMT, it makes more sense to have always a Date instance for this callback.

**Comment by mediafreakch** [comment]
@bre1470 We use this callback to get around the limitation that timezones are only supported with Moment.js. We use `date-fns-tz` and those Date instances have no timezone information.

We use the following callback to transform to a highcharts compatible format:


```typescript
export function getTimezoneOffset(timestamp: number | Date): number {
  let serverUTCTime: number

  if (typeof timestamp === 'object') {
    serverUTCTime = timestamp.getTime()
  } else {
    serverUTCTime = timestamp
  }

  const stationUnixTime = utcToZonedTime(serverUTCTime, this.timeZone).getTime()
  const utcUnixTime = utcToZonedTime(serverUTCTime, 'UTC').getTime()

  // for highcharts, we need the reverse-offset: how  much does UTC offset from stationTime?
  // For Date.UTC(2020, 0, 1) Europe/Zurich it is -01:00
  const offsetInMinutes = Math.floor((utcUnixTime - stationUnixTime) / 1000 / 60)
  return offsetInMinutes
}
```

**Comment by bre1470** [comment]
@mediafreakch 
Thank you for the additional example of implementation! So in your use case a `number` type would be clearly more beneficial.
