### ISSUE TITLE
In 3D doughnut chart,when changing the size of the chart,it will not render properly

### ISSUE THREAD

**Issue by ma1990213** [highcharts/highcharts#13044]
#### Expected behaviour
Correct render thickness

#### Actual behaviour
The thickness is compressed

#### Live demo with steps to reproduce

![normal ](https://user-images.githubusercontent.com/17824026/75621829-8c1b1180-5bd4-11ea-901d-305f773385bd.png)
![abnormal](https://user-images.githubusercontent.com/17824026/75621831-8fae9880-5bd4-11ea-96bc-2cac03c693c9.png)

#### Product version

"highcharts": "8.0.0",
"highcharts-3d": "^0.1.7",
"highcharts-vue": "^1.3.5"
#### Affected browser(s)
Google Chrome 80.0.3987.122

**Comment by pawelfus** [comment]
Hi @ma1990213 

Thanks for reporting the issue, but please provide **live demo** (using e.g. jsFiddle, stackblitz) - we are not able to debug using images.

**Comment by ma1990213** [comment]
It was a mistake, I have solved the problem, thank you very much.

**Comment by ziasam** [comment]
@ma1990213 How did you solve it?

**Comment by pawelfus** [comment]
Hi @ziasam - my guess is setting [`size`](https://api.highcharts.com/highcharts/plotOptions.pie.size) and [`innerSize`](https://api.highcharts.com/highcharts/plotOptions.pie.innerSize) to the same value, for example: https://jsfiddle.net/BlackLabel/c3ys7oze/

**Comment by ziasam** [comment]
Hi @pawelfus thanks for pointing out. In my case the outer circle radius gets thinner as more data are populated. I am guessing it's the default behavior . Thanks.

**Comment by pawelfus** [comment]
Perhaps you might want to consider using a different series type. For example column? Or group small values into one "Other" category? 

Anyway, it shouldn't happen with more points: https://jsfiddle.net/BlackLabel/c3ys7oze/ - unless the chart is too narrow: https://jsfiddle.net/BlackLabel/c3ys7oze/2/

**Comment by ziasam** [comment]
@pawelfus I have the exact same definition in my chart as your first link attachment of HighChart . But it's still shrinking.

**Comment by ziasam** [comment]
@pawelfus I got that issue. Thanks for your references.

**Comment by pawelfus** [comment]
That's great to hear!
