### ISSUE TITLE
Marker clusters not working with scatter series.

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#13050]
## Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5wvr8bfj/

#### Product version
Highcharts

**Comment by KacperMadej** [comment]
@wchmiel Is demo intentionally set to the last version 7? Because this seems to be working fine for the current (8.0.2) - https://jsfiddle.net/BlackLabel/5wvr8bfj/3/

**Comment by wchmiel** [comment]
Right, it's working fine after the last release. I'm closing the issue.
