### ISSUE TITLE
Broken Link in footer

### ISSUE THREAD

**Issue by abhinav-goyall** [highcharts/highcharts#13055]
Please check the Documentation Hyperlink in the footer(Under Support Category) which is giving 404 Error Code.

Error Link: https://www.highcharts.com/blog/documentation

Please check and get it corrected.

**Comment by sebastianbochan** [comment]
Hi @abhinav-goyall,
Thank you for reporting about the problem.

**Comment by LindaSve93** [comment]
Fixed.
