### ISSUE TITLE
YAxis title not rotating when using angle property in polar chart

### ISSUE THREAD

**Issue by thejensi1** [highcharts/highcharts#13064]
When using the angle property within an yAxis the title of this axis is not rotated in polar chart. 

#### Expected behaviour
Setting angle to a value other than 0 should also rotate the title.

#### Actual behaviour
Title not rotated - see fiddle.

#### Live demo with steps to reproduce
https://jsfiddle.net/thejensi1/h1k27b6e/1/

**Comment by sebastianbochan** [comment]
Hi @thejensi1,
Thank you for reporting. By default this option is not part of title's functionality, but I prepared you a snippet which covers your requiremets.

Demo:
- https://jsfiddle.net/BlackLabel/gyfmh7aw/

_Internal note_
The workaround looks like a beta solution, so I need to do some tests to add this to the core. I will appreciate feedback.

**Comment by thejensi1** [comment]
Thanks for the workaround, looks good in first place. :-) Unfortunately the position of the axis label is not always correct - but I guess one can tweak your snippet a bit to always find a good position for every angle?! And also I guess there needs to be a way to avoid overlapping the axis caption and the tick labels.

**Comment by sebastianbochan** [comment]
Hi @thejensi1,

> Unfortunately the position of the axis label is not always correct - but I guess one can tweak your snippet a bit to always find a good position for every angle

Could you share a demo of unworking example?

> And also I guess there needs to be a way to avoid overlapping the axis caption and the tick labels.

Currently Highcharts does not have anty-collision mechanism, so at this moment we can only add a functionality which hides a label/title when overlap.

**Comment by thejensi1** [comment]
When I change the angle within your example (see https://jsfiddle.net/thejensi1/dbm2t4g3/) the yaxis title will have an offset to the actual axis.
Another issue I discovered is that when deactivating the series (by just clicking on the legend) within this example and activating it again the yaxis title moves away from the axis.
