### ISSUE TITLE
Histogram wrong columns value calculations

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#13069]
The histogram doesn't calculate the values for the column properly. 

Take a look at this demo: https://jsfiddle.net/BlackLabel/b1oqupwn/ values from range less than -25 are missed. 

Works as expected in the 6 version: https://jsfiddle.net/BlackLabel/59wxpatr/

#### Product version

Highcharts JS v8.0.2 (2020-03-03)

**Comment by KacperMadej** [comment]
The last working version is 7.0.3 and the problem is visible since version 7.1.0.

**Comment by pawelfus** [comment]
Bisected to commit cd96f38a04

FYI @Denyllon
