### ISSUE TITLE
DashStyle for BoxPlot charts doesn't work

### ISSUE THREAD

**Issue by thejensi1** [highcharts/highcharts#13065]
Cannot use the dashStyle property for box plot charts. Only stemDashStyle works but this will just change to style of the stems instead the style for all lines/dashes.

#### Expected behaviour
Setting a dashStyle for a box plot chart should result in changing the style for all lines/dashes.

#### Actual behaviour
Doesn't work at all.

#### Live demo with steps to reproduce
https://jsfiddle.net/thejensi1/Lgms6fn9/3/

**Comment by raf18seb** [comment]
Hi @thejensi1 ,

The API for _series.botplot_ is incorrect (should not be here): https://api.highcharts.com/highcharts/series.boxplot.dashStyle
For this moment, as you said above, setting dashStyle in boxplot works only for a stem.
