### ISSUE TITLE
When the 'polar' of the line chart is' true ', the annotation display is incomplete

### ISSUE THREAD

**Issue by LbyKevin** [highcharts/highcharts#13077]
#### Expected behaviour
When the 'polar' of the line chart is' true ', all annotations are displayed

#### Actual behaviour
When the 'polar' of the line chart is' true ', the annotation display is incomplete

#### Live demo with steps to reproduce
https://jshare.com.cn/temp/VdGGLs

#### Product version

highcharts:8.0.0
#### Affected browser(s)
Google Chrome:80.0.3987.122

**Comment by pawelfus** [comment]
Thanks for reporting the issue @LbyKevin 

Simplified demo: https://jsfiddle.net/BlackLabel/xLjztf6g/ 0 only two out of six labels are displayed. Setting `allowOverlap = true` does not resolve the issue. We can find labels created in DOM, with `opacity=0` (`allowOverlap = true` resolves that) and `x=-9999`.

Perhaps checking if annotation is inside plot is wrong. Could you check this @raf18seb ?

**Comment by raf18seb** [comment]
You are right.
_point.isInsidePane()_ method doesn't handle polar charts.

**Workaround:** https://jsfiddle.net/BlackLabel/de5t2zqx/
