### ISSUE TITLE
Accessibility: isHighContrastModeActive method: network request generated in IE11

### ISSUE THREAD

**Issue by bobleap** [highcharts/highcharts#13071]
#### Expected behaviour
No network request should be needed for a test. 

#### Actual behaviour
The url(#) is generating a network request. 

#### Product version
V7.2.1

#### Affected browser(s)
IE11

Proposed solution: replace the url(#) with url(data:). This seems to generate no new request.

**Comment by pawelfus** [comment]
Hi @bobleap 

Thanks for reporting the issue. Could you:
- check v8.0.0 and v8.0.2 version and let us know if the issue still exists?
- create a simple demo in jsFiddle?

Thanks!

**Comment by bobleap** [comment]
Thanks Pawel. jsfiddle does not work with IE11, but you can see it with any of the standard examples such as: https://www.highcharts.com/demo/line-basic. In the network panel of the dev tools, note this image-initiated request: 
![image](https://user-images.githubusercontent.com/57220967/75880070-96165d80-5dea-11ea-8d3b-0c08e61c7d93.png)


Re: whether this still exists, yes -- refer to line 32 of https://github.com/highcharts/highcharts/blob/master/js/modules/accessibility/high-contrast-mode.js
![image](https://user-images.githubusercontent.com/57220967/75880012-7c751600-5dea-11ea-84c4-079be3699565.png)

Thanks for a great product.

**Comment by pawelfus** [comment]
Thanks for the details @bobleap !
FYI @oysteinmoseng
