### ISSUE TITLE
Tick Marks not configurable

### ISSUE THREAD

**Issue by amydyson** [highcharts/highcharts#13073]
#### Expected behaviour
Tick marks  appear on the xAxis and are configurable with  tickWidth and tickLength, as well as working with tickPixelInterval.

#### Actual behaviour

Tick marks do not appear on the xAxis. tickWidth and tickLength do not work.
 

#### Live demo with steps to reproduce
https://codepen.io/amybethmegjo/pen/xxGqVMj?editors=1111

See lines 114-116

#### Product version
Highcharts gantt

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @amydyson 

Thanks for using Highcharts Gantt! Ticks are used to render the grid in grid axis, so you can control them using grid options: https://api.highcharts.com/gantt/xAxis.grid For example:
```js
  xAxis: [{
    grid: {
      borderColor: 'white',
      borderWidth: 5,
      cellHeight: 25
    },
    ...
  }]
```

You can also disable grid axis, then ticks will work as in a regular axis:
```js
    grid: {
      enabled: false
    },
```
