### ISSUE TITLE
Gantt Chart Scrolling looks bad

### ISSUE THREAD

**Issue by amydyson** [highcharts/highcharts#13072]
#### Expected behaviour
Scrolling is smooth and text is between the expected lines.

#### Actual behaviour
It is behaving oddly. I think in general there’s a lag in response. Is there a way to speed it up? I have included three screenshots and a video of the problem on our real project.

#### Live demo with steps to reproduce
Simplified problem below;

https://jsfiddle.net/BlackLabel/L78mkans/

#### Affected browser(s)
Chrome

Files describing problem more:

![scroll-disappearingNameAndLine](https://user-images.githubusercontent.com/28379782/75809401-94429080-5d3d-11ea-863f-bd1ae37dcb96.png)
![scroll-overlapping-name](https://user-images.githubusercontent.com/28379782/75809402-94db2700-5d3d-11ea-8985-2360be6a653f.png)
![scrollOverlappingDatetime](https://user-images.githubusercontent.com/28379782/75809405-94db2700-5d3d-11ea-8af1-a16baddaee8b.png)

**Comment by pawelfus** [comment]
Thanks for reporting this @amydyson 

**Simplified demos:**
- https://jsfiddle.net/BlackLabel/quvmhrdk/ - first label and gridLine are missing
- https://jsfiddle.net/BlackLabel/r5x4astv/ - bottom xAxis label is isplaced
- https://jsfiddle.net/BlackLabel/rfqLtanm/ - use xAxis scrollbar and notice flashing labels

**Comment by goransle** [comment]
Regarding horizontal scrolling: Setting `startOnTick: true` and moving the scrollbar settings out of xAxis (as per the [api](https://api.highcharts.com/gantt/scrollbar)) produces a snappier animation. See https://jsfiddle.net/goransle/yds8o3hc/

**Comment by lazyanger** [comment]
The y-axis label will be more weird when using grid. See https://jsfiddle.net/hcvsfqjd/
![image](https://user-images.githubusercontent.com/18509186/83214641-a8105e00-a197-11ea-87a7-19f5e2ed4400.png)
![image](https://user-images.githubusercontent.com/18509186/83214704-cf672b00-a197-11ea-8d5f-5c288afd003b.png)

**Comment by sebastianbochan** [comment]
Hi @lazyanger,
Thank you for additional demo. The issue looks like more complex than we expected.

**Comment by karolkolodziej** [comment]
It looks like that we can fix the flashing x-axis by applying data time format as a list of possible formats.
When the list doesn't exist the `shortenLabel` function won't be triggered.
Example: http://jsfiddle.net/BlackLabel/0nb2msjq/
```
                // Set up conditional formatting based on the format list if existing.
                list = dateTimeLabelFormats && dateTimeLabelFormats.list;
                if (list) {
                    tick.shortenLabel = function () {
                        for (i = 0; i < list.length; i++) {
                            label.attr({
                                text: axis.labelFormatter.call(extend(tick.formatCtx, { dateTimeLabelFormat: list[i] }))
                            });
                            if (label.getBBox().width <
                                axis.getSlotWidth(tick) - 2 *
                                    pick(labelOptions.padding, 5)) {
                                return;
                            }
                        }
                        label.attr({
                            text: ''
                        });
                    };
                }
```
