### ISSUE TITLE
Annotation - draggable "xy" is not working for HTML labels

### ISSUE THREAD

**Issue by rajeshdanabal** [highcharts/highcharts#13070]
#### Expected behaviour

When we have html annotation labels set with draggable as xy, We should be able to drag and change its position.

#### Actual behaviour
When we have html annotation labels set with draggable as xy, We are unable to drag and change its position.

#### Live demo with steps to reproduce
https://jsfiddle.net/rajeshdanabal/jxmokdv5/

#### Product version
Highcharts v8.0.1

#### Affected browser(s)
Google Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Thanks for reporting the issue @rajeshdanabal
