### ISSUE TITLE
change static method uniqueKey not working

### ISSUE THREAD

**Issue by roniRamon** [highcharts/highcharts#13074]
before version 8.0.2
changing the method worked (in order to Overrides dynamic id generation for testing)
```
Highcharts.uniqueKey = (function() {
  var idCounter = 0;
  return function() {
    return 'highcharts-' + idCounter++;
  };
})();

HighchartsMore(Highcharts);
```
now it is not changing anything

**Comment by sebastianbochan** [comment]
Hi @roniRamon,
Thank you for reporting about the problem. As I see in the source code, the method still exists. Could you share a simplified demo of use case?

**Comment by pawelfus** [comment]
Hi @roniRamon 
That's correct, you shouldn't be able to override `Highcharts.uniqueKey` method, even for tests. Just in case, generated unique keys are in format: `highcharts-{hash}-{iterator}`.

As fair as I know we don't have plans to allow overriding any of methods under `Highcharts` namespace (it might be possible for some of them as we speak), could you confirm @bre1470 @TorsteinHonsi ?

**Comment by bre1470** [comment]
Yes, that is correct. As we are moving to ES6 patterns, we deprecated wrap mechanics. Instead events are the favored approach. So we could discuss, if an event or callback is helpfull in that case.

I wonder though, what the original problem was, that led to this replacement. Maybe there is a better solution than changing unique IDs. We have a debugger module for example, that could be improved.

**Comment by roniRamon** [comment]
Thank you @bre1470 for the quick answer! the original problem was jest snapshot was failing because the id || url keep changing. the solution until now was to override the unique id to be `highcharts-{iterator}` so the snapshot will be the same. 

I wonder if you have any suggestion or a better solution to the issue?

**Comment by bre1470** [comment]
If the chart is just a snapshot-comparison. You cold go over the SVG string with a regular expression  to remove the hash:
```js
replace(/(["'])highcharts-[0-f]+-(\d)\1/gm, '$1highcharts-$2$1')`.
```

@TorsteinHonsi 
Maybe we should consider a debug mode, where we produce the IDs without a hash. The `debugger` module could set a flag and then `Highcharts.uniqueKey` simple skips the hash addition. What do you think?

**Comment by bre1470** [comment]
@roniRamon
If the chart is just a snapshot-comparison, you cold go over the SVG string with a regular expression  to remove the hash:
```js
replace(/(["'])highcharts-[0-f]+-(\d)\1/gm, '$1highcharts-$2$1')
```

@TorsteinHonsi 
Maybe we should consider a debug mode, where we produce the IDs without a hash. The `debugger` module could set a flag and then `Highcharts.uniqueKey` simple skips the hash addition. What do you think?

**Comment by bre1470** [comment]
Hello @roniRamon,
We are unsure what to do with this issue. Works the replace approach for your testing setup? Or do you still need session-based IDs out of the box?

**Comment by jamescrowley** [comment]
I have the same issue using Jest snapshots using Highcharts in a React app. 

The replace string doesn't quite work for me, I needed `/(["'])highcharts-[0-z]+-(\d)-?\1/gm` (0-z rather than 0-f and I sometimes have a stray '-' at the end of the digit.

While the replace works as a workaround, it's a pain if you want to keep the same 'readable' snapshot format as before, as you have to reach into Jest internals, and there is some double-encoding that gets into the snapshot as the result. If there was a way to turn off the random element of Highcharts.uniqueKey that would be fab.

For reference for anyone else, this is what I ended up using:

```
import { utils } from 'jest-snapshot'

const fixHighchartsIds = (snapshot:any) => {
  return utils.serialize(snapshot).replace(/(["'])highcharts-[0-z]+-(\d)-?\1/gm, '$1highcharts-$2$1');
}
```
and then
```
  expect(fixHighchartsIds(container)).toMatchSnapshot();
```
