### ISSUE TITLE
Color axis: When only minColor is set, other colors should be none

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#13086]
#### Expected behaviour
If only minColor of color axis is set, it is expected that maxColor should be None.

#### Actual behaviour
Plot treemap or geomap with color axis. Set the minColor of color axis only. It is observed that some blue color is set as maxColor. Why this color is set?
Now, set the maxColor of color axis only. It is observed that none color is set as minColor which seems correct.

#### Live demo with steps to reproduce
Refer JS fiddles:
Only min color is set: https://jsfiddle.net/amrutaJgtp/htvnj915/1/
Only max color is set: https://jsfiddle.net/amrutaJgtp/htvnj915/2/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @amruta30 

You can find the answer in our docs:
- default value for minColor: https://api.highcharts.com/highcharts/colorAxis.minColor
- default value for maxColor: https://api.highcharts.com/highcharts/colorAxis.maxColor

**Comment by amruta30** [comment]
@pawelfus Thanks for your reply!
