### ISSUE TITLE
Highcharts-boxplot-tooltip-issue

### ISSUE THREAD

**Issue by rammohan201** [highcharts/highcharts#13087]
#### Expected behaviour
Tooltip shoud be shown only when I hover on a particular outlier or box.

#### Actual behaviour
I hovered on 2nd box, first box's tooltip is shown. weird behavior, If I hover middle of the box or chart, nearest outlier's (name is from the below jsfiddle's example) tooltip is shown

#### Live demo with steps to reproduce
https://jsfiddle.net/rammohanreddy201/ga20p14y/5/

after launching the above demo, do the following
place cursor between 2 and 3 categories as shown in below snapshot. tooltip is showing on the first category circle. my expectation is I want to be able to see tooltip only when I hover on it.
how can I control this behavior?
![image](https://user-images.githubusercontent.com/12894116/75961494-225a7a80-5ee8-11ea-98aa-12f8bc9962f8.png)

#### Product version
7.1.1

#### Affected browser(s)
Chrome, I have not tested in other browsers

**Comment by sebastianbochan** [comment]
Hi @rammohan201,
Thank you for reporting about the problem. This is the default functionality when [stickyTracking] is enabled (by default).

Demo:
- https://jsfiddle.net/BlackLabel/0mr1sv4u/

Let me know if it solves your problem.

**Comment by rammohan201** [comment]
> Hi @rammohan201,
> Thank you for reporting about the problem. This is the default functionality when [stickyTracking](https://api.highcharts.com/highcharts/plotOptions.series.stickyTracking) is enabled (by default).
> 
> Demo:
> 
> * https://jsfiddle.net/BlackLabel/0mr1sv4u/
Thank you so much for resolving my issue.
@sebastianbochan, one more question, is there way to display tooltip from median instead of maximum?

**Comment by sebastianbochan** [comment]
Hi @rammohan201,
For general [support questions](https://www.highcharts.com/support) please use stackoverflow / forum or email.
