### ISSUE TITLE
(IE8 + MooTools) Arg: Illegal input string in Vector2D

### ISSUE THREAD

**Issue by PabloDeGrote** [highcharts/highcharts#1309]
I have a problem in IE8 with the horizontal bars example together with the MooTools framework.

Please check out this example: http://jsfiddle.net/DuLF4/

Steps to reproduce the below error:
- Open IE8 and goto the fiddle example
- Move your mouse from the label "Apples" towards the bar, after you mouseleave "Apples" and hit the first border in the graph area the following error will occur.

```
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
Timestamp: Mon, 15 Oct 2012 07:55:05 UTC

Message: Arg: Illegal input string in Vector2D
Line: 389
Char: 30
Code: 0
URI: http://fiddle.jshell.net/js/lib/mootools-core-1.4.5-nocompat.js
```

This is the mootools (core) function where the adapter fails.

```
   append: function(original){
      for (var i = 1, l = arguments.length; i < l; i++){
         var extended = arguments[i] || {};
         for (var key in extended) original[key] = extended[key];
      }
      return original;
   }
```

It breaks on this specified code: 

```
for (var key in extended) original[key] = extended[key];
```

All frameworks are up 2 date.
MooTools 1.4.5
Highcharts 2.3.3

---

The problem is caused by the mousetracking code. If I disable mousetracking, the error wont occur.
I tried making the tracking viewport (default 1x1 in IE8) to the same chart demensions but that wasn't sadly the fix.
I'm lost and can't spend more time on debugging so I hope somebody can help me with this.

**Comment by cvasseng** [comment]
Hi! We're doing a bit of spring cleaning, and closing old issues. If you're still experiencing issues with this, please feel free to open a new issue! Thanks!
