### ISSUE TITLE
 Wordcloud animation options in series doesn't work.

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13098]
#### Expected behaviour
According to the API, it should be possible to change the animation duration on the series.
API references: https://api.highcharts.com/highcharts/series.wordcloud.animation

#### Actual behaviour
It is not possible to change animation.duration on series. 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/usrgeqx9/

#### Product version
Highcharts JS v8.0.3 (2020-03-05)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
*Internal note:*
It seems that wordcloud animates points individually, disregarding `series.animation` (`draw` method).

**Comment by pawelfus** [comment]
*Internal note:*
Check how column-type series animate (`column.animation`). Perhaps the implementation can be reused.

**Comment by TorsteinHonsi** [comment]
@karolkolodziej Also note there's a difference between `series.options.animation` used for the initial animation, and general chart-level animation used for updating. Good luck!
