### ISSUE TITLE
Tools: prep-release fails

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#13097]
#### Expected behaviour
`gulp prep-release` should prepare for release by updating the version in files.

#### Actual behaviour
Fails with JS error

#### Live demo with steps to reproduce
In the repo root, run `gulp prep-release --nextversion x.y.z`

Also test `npx gulp prep-release --cleanup --commit` 

#### Product version
v8.0.3

#### Affected browser(s)
None, this is a tooling issue. Fails on the Mac. Possibly works on Linux, where it was authored.

A suggested debugging path is to use GitHub blame to identify when the function was first introduced, then test if it ever worked on the Mac. If it did, we can bisect to find the regression.

**Comment by goransle** [comment]
@TorsteinHonsi [this commit](https://github.com/highcharts/highcharts/commit/5e221800f5aed3185b3518aedb39bd0bc3db9bf3) seems to be the issue. OSX does not support the 'tmp/*.bak' syntax for the `-i` argument.

Simplest fix may be to use `sed -i'.bak'` and add `.bak` files to `.gitignore`.

It also seems that the `grep` script for setting next version in docs does not work not work on OSX.
