### ISSUE TITLE
setup is not working

### ISSUE THREAD

**Issue by nisarhassan12** [highcharts/highcharts#13096]
As specified in the README running `gulp` from the root after `npm install` gives the following error:

![image](https://user-images.githubusercontent.com/46004116/76046546-fbe91d80-5f81-11ea-86d4-b13f3b7ba4dd.png)

 and `npm run build` also fails: 
![image](https://user-images.githubusercontent.com/46004116/76046694-669a5900-5f82-11ea-872a-086824b29337.png)

also, there is no npm package called `woker_threads`:

![image](https://user-images.githubusercontent.com/46004116/76046738-921d4380-5f82-11ea-8618-c6832639efee.png)

**Comment by pawelfus** [comment]
Could you tell us your node and npm versions? Thanks!

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
