### ISSUE TITLE
highcharts.d.ts: Missing declarations for constructors such as Tooltip

### ISSUE THREAD

**Issue by udinkar** [highcharts/highcharts#13103]
#### Issue
Class Tooltip has a constructor that takes two arguments as per here:
https://api.highcharts.com/class-reference/Highcharts.Tooltip
The declaration file for Highcharts (highcharts.d.ts) is missing constructor definition for it.

Typing augmentation along with some hacky code can be used to work around it.

IMO a missing constructor is much worse than missing members, which can be fixed relatively cleanly using declaration merging. The workaround for missing members is contained in one place (i.e. the declaration merging file) and when the issue is resolved, it is rather easy to remove the workaround code.
However, for constructors, the workaround has to leak into the code wherever the constructor is used. This, I believe, is worse.
**Hence missing constructor definition issues, such as this one, should be prioritized over missing members.**

#### Product version
Highcharts v8

#### Effects
Typescript compilation errors when a new Tooltip is created in this fashion:
   new Tooltip(chart, options)

**Comment by sebastianbochan** [comment]
Hi @udinkar,
Thank you for reporting.

FYI @bre1470

**Comment by bre1470** [comment]
We look into our distribution routines, as this is not supposed to happen. API documentation and TypeScript definitions are based on the exact same AST files.

**Comment by bre1470** [comment]
Please update to [`highcharts@8.0.3`](https://www.npmjs.com/package/highcharts). It contains the correct declarations. Sometimes the editor / IDE needs to be closed and opened again, to recognize the changed declarations.
