### ISSUE TITLE
navigator dragg event

### ISSUE THREAD

**Issue by horstlaubenthal** [highcharts/highcharts#1310]
Hi,

maybe this is an enhancement request. So: Is it possible to get an event fired when someone draggs the handles on the navigator in Highstocks? 

How we made it work:

line 16369: 

/**
         \* Event handler for the mouse move event.
         */
        scroller.mouseMoveHandler = function (e) {
            var scrollbarHeight = scroller.scrollbarHeight,
                navigatorLeft = scroller.navigatorLeft,
                navigatorWidth = scroller.navigatorWidth,
                scrollerLeft = scroller.scrollerLeft,
                scrollerWidth = scroller.scrollerWidth,
                range = scroller.range;

```
        e = chart.tracker.normalizeMouseEvent(e);
        var chartX = e.chartX;

        // validation for handle dragging
        if (chartX < navigatorLeft) {
            chartX = navigatorLeft;
        } else if (chartX > scrollerLeft + scrollerWidth - scrollbarHeight) {
            chartX = scrollerLeft + scrollerWidth - scrollbarHeight;
        }

        // drag left handle
        if (scroller.grabbedLeft) {
            hasDragged = true;
            scroller.render(0, 0, chartX - navigatorLeft, scroller.otherHandlePos);

        // drag right handle
        } else if (scroller.grabbedRight) {
            hasDragged = true;
            scroller.render(0, 0, scroller.otherHandlePos, chartX - navigatorLeft);

        // drag scrollbar or open area in navigator
        } else if (scroller.grabbedCenter) {
            hasDragged = true;
            if (chartX < dragOffset) { // outside left
                chartX = dragOffset;
            } else if (chartX > navigatorWidth + dragOffset - range) { // outside right
                chartX = navigatorWidth + dragOffset - range;
            }

            scroller.render(0, 0, chartX - dragOffset, chartX - dragOffset + range);
        }
        /**
```

-->          \* BEGIN CHANGES 
             _/
            if (hasDragged) {
                var eventArgs = {
                    'minDate': xAxis.translate(scroller.zoomedMin, true),
                    'maxDate': xAxis.translate(scroller.zoomedMax, true),
                    'grabbed': function() {
                        if (scroller.grabbedCenter) {
                            return 'center';
                        }
                        if (scroller.grabbedRight) {
                            return 'right';
                        }
                        if (scroller.grabbedLeft) {
                            return 'left';
                        }
                    }(),
                    'handles': scroller.handles
                };
                fireEvent(chart, 'navigatorDragged', eventArgs);
            }
            /_*
             \* END CHANGES
             */

**Comment by c0mm0n** [comment]
Bumping this old issue.

Would really be great to have a on idle or end drag event. (_a la_ Google Maps)
Using AfterSetExtremes while dragging the navigator triggers very often, makes updating an external data table based on min/max uneasy.

Am I missing something ?

**Comment by TorsteinHonsi** [comment]
You could check if the mouse is down in the `afterSetExtremes` callback, or fire it in a timeout to prevent firing too often?

**Comment by pawelfus** [comment]
In current (v6) version of Highstock, event can be added without modifying source code, snippet:

```javascript
(function(H) {
  H.wrap(H.Navigator.prototype, 'onMouseMove', function (proceed, event) {
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    fireEvent(this, 'navigatorDragged', event); // event added to Navigator, event can be extended with more options
  });
})(Highcharts);
```

But it doesn't change how often the event is triggered (on each mouse-move action). So synced timeout solution on this event is a good idea.

**Comment by TorsteinHonsi** [comment]
Here's the version with a pure event handler approach:
```js
    xAxis: {
    	events: {
        	setExtremes: function (e) {
            	if (e.trigger === 'navigator' && (e.DOMEvent.type === 'mouseup' || e.DOMEvent.type === 'touchend')) {
                	console.log('dropped', this.getExtremes());
                }
            }
        }
    },
```

http://jsfiddle.net/0w5we1ck/3/
