### ISSUE TITLE
In doughnut chart, the guide line do not render correctly.

### ISSUE THREAD

**Issue by ma1990213** [highcharts/highcharts#13104]
#### Expected behaviour
Correct render guide line

#### Actual behaviour
The guide line is forky

#### Live demo with steps to reproduce
https://jshare.com.cn/temp/FSGGwn
![1](https://user-images.githubusercontent.com/17824026/76140250-2971bc00-6093-11ea-9fa6-af3101030b44.png)
![2](https://user-images.githubusercontent.com/17824026/76140252-2aa2e900-6093-11ea-94e1-4ab7a5abf157.png)

#### Product version
"highcharts": "8.0.2",
"highcharts-vue": "^1.3.5"

#### Affected browser(s)
Google Chrome 80.0.3987.12

**Comment by sebastianbochan** [comment]
Hi @ma1990213,
Thank you for reporting. It looks like a bug.

Simplified demo:
- https://jsfiddle.net/BlackLabel/hq5vosfu/

**Comment by sebastianbochan** [comment]
Hi @ma1990213,
Thank you for reporting about the problem. It looks like an issue in native SVG, not in Highcharts, so I would not consider it as a bug in our core.

Simplified demo:
- https://jsfiddle.net/BlackLabel/1vqobguw/
