### ISSUE TITLE
How can make a animation with highcharts?

### ISSUE THREAD

**Issue by diennt90** [highcharts/highcharts#13106]
Hi everyone, I am newbie
I need create a animation with bar chart like this video:
https://www.youtube.com/watch?v=X0_iaNq8Y0U

I hope that someone would or could help me
Many thanks

**Comment by sebastianbochan** [comment]
Hi @diennt90,
Thank you for requesting. For [support questions](https://www.highchats.com/support), please contact with our developers by stackoverlow / forum or email.

ps. consider to use sorted animated demo: https://www.highcharts.com/docs/advanced-chart-features/data-sorting
