### ISSUE TITLE
Drill up text and drill up button does not acquire proper width and height when chart is initially hidden and we load a drilldown view.

### ISSUE THREAD

**Issue by dkodedara** [highcharts/highcharts#13108]
#### Expected behaviour
drill up button and drill up text should get shown properly

#### Actual behaviour
drill up button and drill up text does not get shown properly

#### Live demo with steps to reproduce
https://jsfiddle.net/dkodedara/nwyc5z9e/

click on button "recreate issue"

**Comment by pawelfus** [comment]
Thanks for reporting the issue @dkodedara - it's caused, as you noticed, by rendering chart in a hidden container. When we calculate size of the box, we get text's bounding box from browser using `SVGElement.getBBox()`, which returns `{ x: 0, y: 0, width: 0, height: 0 }`. Simple demo without Highcharts: https://jsfiddle.net/BlackLabel/d37f496y/ - click "recreate issue" and check the console.

**Simplified demo:**
https://jsfiddle.net/BlackLabel/okaerxzu/
This happens with every button that was rendered in a hidden container.

*Internal note:*
We do render chart in a visible container when is hidden (or one of it's parents). But after that we hide the container back, so any operation done after rendering the chart is done on a hidden chart. Not sure about a perfect solution here.. render buttons in a separate and visible container? Perhaps `chart.reflow()` should be able to solve it?

**Comment by dkodedara** [comment]
didnt try chart.reflow() but  chart.showDrillUpButton() worked as a temporary fix for me..
