### ISSUE TITLE
Cannot read property 'animate' of undefined

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#13101]
Hello.

Case:

1. Piechart with drilldown and with negative value.
2. Call `.select(false, false)` on negative value.

#### Expected behaviour
Unselect point

#### Actual behaviour
Error `Cannot read property 'animate' of undefined`
![image](https://user-images.githubusercontent.com/6030335/76082512-a716c880-5fbc-11ea-956b-09bc317fcce2.png)

PS: on positive values works.

#### Live demo with steps to reproduce
https://jsfiddle.net/39stjv0x/1/

#### Product version
Highcharts JS v8.0.3 (2020-03-05)

#### Affected browser(s)
Google Chrome 80.0.3987.132

**Comment by pawelfus** [comment]
Thanks for reporting. Of course we will fix this.

Could you tell us why do you use negative values in a pie chart? You should consider other series types when displaying negative values (e.g. column/bar). Any why are your trying to select a slice that doesn't exists?

**Comment by balkarov** [comment]
Case in our project: we controll drilldown and drillup. 
When the user select a point the point is highlighted and for user shows "drilldown" button and "clear selected points" button. After click "clear selected points" we have this problem with negative values.
Yes, negative points on pie chart is starange. But it needs for our project.
