### ISSUE TITLE
Organizational Chart - Node Labels Disappears

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#13100]
#### Actual behaviour
Sometimes, depending on the size of the elements or the chart, node labels are not displayed properly. The positions of these elements receive incorrect values:
`highcharts-label
top: -9999px;
opacity: 0;
`

![1](https://user-images.githubusercontent.com/39968065/76081081-a70ccd80-5fa8-11ea-8183-1d27c81b63a7.png)

#### Live demo
https://jsfiddle.net/BlackLabel/zq21nsoe/

#### Simplified demo
https://jsfiddle.net/BlackLabel/ukf75sm9/

#### Product version
v8.0.3

#### Affected browser(s)
Chrome: 80.0.3987.122
Firefox: 73.0.1

**Comment by madepiet** [comment]
Setting the `series.dataLabels.allowOverlap` forces labels to be displayed.

#### Live demo:
https://jsfiddle.net/BlackLabel/4dskhf6r/

**Comment by fschlaef** [comment]
I have the same issue and can confirm the `allowOverlap` workaround functions.
