### ISSUE TITLE
8.0.4:A lot of charts, page load caton

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#13118]
#### Actual behaviour
![QQ图片20200311170256](https://user-images.githubusercontent.com/6789138/76400042-9f8b6100-63ba-11ea-900a-ec2c2a7ba8f5.png)

#### Live demo with steps to reproduce

```js
<highcharts v-for="item in chartSplitList"
                                v-if="chartOptions&&isAggdataFinish"
                                :options="item"
                                :updateArgs="updateArgs"
                                style="float:left;"
                                ref="ref-highcharts-chart-split"></highcharts>
updateArgs: [true, true, false],
```
#### Product version

```js
  "highcharts": "8.0.4",
    "highcharts-3d": "^0.1.7",
    "highcharts-grouped-categories": "^1.1.3",
    "highcharts-regression": "^2.0.1",
    "highcharts-vue": "^1.3.5",
```

**Comment by pawelfus** [comment]
Hi @wjhcc2018 

Thanks for reporting, but could you please edit your question and fill requested paragraphs?
These ones:

> Expected behaviour
> Actual behaviour
> Live demo with steps to reproduce

Image is not enough to debug the issue, neither the snippet you provided. And the issue description is crucial.

Thank you

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
