### ISSUE TITLE
3d - axis labels overlap

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13115]
#### Expected behaviour
Axis should not overlap.

#### Actual behaviour
Axis labels overlap.

#### Live demo with steps to reproduce
https://jshare.com.cn/temp/ZCGGv1

#### Product version
8.0.3

#### Affected browser(s)
The maximum value of the X-axis 1000 coincides with the minimum value of the z-axis 0

**Comment by sebastianbochan** [comment]
Hi @weixingcai,
Thank you for reporting. Currently Highcharts does not have anty-collision detector for labels.

As workaround you can disable last value by [showLastLabel](https://api.highcharts.com/highcharts/xAxis.showLastLabel) option.
