### ISSUE TITLE
Highstock Navigator position breaks with StockTools & series options

### ISSUE THREAD

**Issue by laventnc** [highcharts/highcharts#13114]
#### Expected behaviour
Should be able to explicitly define a separate series for the Navigator, as well as stockTools gui, and have it position / react as show in the demos.

#### Actual behaviour
When setting plotOptions.series.showInNavigator: false, the position of the Navigator gets messed up when toggling the stockTools menu (using the menu arrow). [ Also, initial load of the Navigator often gets positioned incorrectly on my site.](https://imgur.com/dSRNFuj) I wasn't able to reproduce this issue on jsFiddle; however, I'm assuming they are related b/c using showInNavigator: true fixes both. 

#### Live demo with steps to reproduce
https://jsfiddle.net/nlaventis/azoy58fr/24/

The linked fiddle uses absolute positioning for the charts and a flex container, simply because that's most similar to my use case. Removing absolute positioning/flex styling does not solve the issue.

#### Product version
Highstock - 8.0.0

#### Affected browser(s)
Chome - Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Thanks for reporting the issue @laventnc 

Simplified demo: https://jsfiddle.net/BlackLabel/kw78fzLj/1/ - it seems that disabled scrollbar and using external series in navigator breaks it. At this moment I suggest to enable the scrollbar.

Last working version v4, broken since v5. But in v4, `showInNavigator` didn't exist, so most likely it never did work.

**Comment by laventnc** [comment]
No problem, thank you for the reply.

Interesting, I'll enable the scrollbar for now on related charts. I'll keep my eye on the changelog for a fix!

**Comment by laventnc** [comment]
@pawelfus I recently came across this exact issue again when using the highcharts vue wrapper.

In summary, if you don't explicitly define the navigator series, then it's all good. However, if you try to define the navigator series and disable the scrollbar, the mask & handles disappear. I've attached a [link to a demo](https://codesandbox.io/s/navigator-scrollbar-nmrf6?file=/src/components/Chart.vue) so you can verify the problem.

- explicitly set navigator.series & try toggle scrollbar.enabled (note: that scrollbar.liveRedraw & navigator.adaptToUpdatedData appear to have no effect)
- use series.showInNavigator = true, and it works

**Comment by KacperMadej** [comment]
Hi @IvanGuardado 

You are using a version of Highcharts before the fix was introduced, so it doesn't work.
I have tested your demo with the current Highcharts version (v9.0.0) and the problem is not visible.

**Comment by IvanGuardado** [comment]
@KacperMadej I think you wanted to mention @laventnc instead :)
