### ISSUE TITLE
https://jshare.com.cn/temp/9CGGvw     Y problem

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13117]
#### There should be no negative values on the Y-axis

####No negative values on the Y-axis

#### Affected browser(s)

**Comment by sebastianbochan** [comment]
Hi @weixingcai,
The github is our bug tracker, so for the general support questions please use stackoverflow / forum or email.

ps. you should set minPadding: 0 / maxPadding: 0 on yAxis.

Docs:
- https://api.highcharts.com/highcharts/yAxis.minPadding

**Comment by weixingcai** [comment]
Sorry, I thought it was a bug

**Comment by sebastianbochan** [comment]
No problem. I recommend you to contact with our supporter,  they will help you to debug and decide about bug.

**Comment by weixingcai** [comment]
How to contact your supporters

**Comment by sebastianbochan** [comment]
I recommend you to visit our website: https://www.highcharts.com/support

**Comment by weixingcai** [comment]
thank you
