### ISSUE TITLE
boost - lines marker after zoom

### ISSUE THREAD

**Issue by someusersomeuser** [highcharts/highcharts#13128]
#### Expected behaviour

normal lines marker color and size

#### Actual behaviour

in boost mode, when scatter outside after zoom, lines markers are set to color and size of hidden scatter

#### Live demo with steps to reproduce
https://jsfiddle.net/8qfmpeo0/

before zoom:
![image](https://user-images.githubusercontent.com/36192774/76534169-2e1ae380-648a-11ea-8270-048304d9918c.png)

after zoom (scatter outside):
![image](https://user-images.githubusercontent.com/36192774/76534264-51de2980-648a-11ea-8cb1-2872f31573f9.png)

#### Product version
latest

#### Affected browser(s)
all

**Comment by sebastianbochan** [comment]
Hi @someusersomeuser,
Thank you for reporting about the problem. It looks like a problem stricly related with data. When I remove points (#15 error about unsorted data) it worked properly.

Simplified demo of problem:
- https://jsfiddle.net/BlackLabel/zv8p7mof/

_Internal note_
@cvasseng its seems that `boost.seriesThreshold: 1` does not solve the issue.

Possibly related with https://github.com/highcharts/highcharts/issues/12422
