### ISSUE TITLE
Deleted annotations shows up on chart export

### ISSUE THREAD

**Issue by PadWorks** [highcharts/highcharts#13129]
With a delete button I want to delete all annotations on the chart. This also works correctly. But with the export the annotations are still displayed.

[https://jsfiddle.net/PadWorks/pcdrtz4n/](url)

1. Click "Add 1 marker" (marker was shown up)
2. Click "Delete markers" (marker was deleted)
3. Click "Save PNG" (marker still visible)

#### Product version
Highcharts 8.0.4 and Main

#### Affected browser(s)
Chrome, Firefox...

**Comment by sebastianbochan** [comment]
Hi @PadWorks,
Thank you for the reporting. The exporting process extract options from `chart.options` where annotations are stored too.

Solution:
- https://jsfiddle.net/BlackLabel/1hb24apr/

_Internal note_
I think that we should remove the annotation from `chart.options` too when destroy.

**Comment by pawelfus** [comment]
That is expected behaviour - that's exactly how `annotation.destroy()` works - does not modify the options. Like everywhere else in your code use `chart.removeAnnotation()` method, see docs:

- https://api.highcharts.com/class-reference/Highcharts.Chart#removeAnnotation
