### ISSUE TITLE
When Data is condensed and graph type is line, then I am not able to hover above some points where many points are gathered.

### ISSUE THREAD

**Issue by shiv1154331** [highcharts/highcharts#13120]
![rsz_screenshot_from_2020-03-11_16-40-19](https://user-images.githubusercontent.com/61269219/76411352-a6fd3b00-63b7-11ea-8de7-7f19b6e1a2b1.png)

**Comment by shiv1154331** [comment]
Please reply fast

**Comment by pawelfus** [comment]
Hi @shiv1154331 

You posted on our bugs/enhancements tracker, for questions please use other support channels: https://www.highcharts.com/blog/support/

PS: Check [`scatter.jitter`](https://api.highcharts.com/highcharts/series.scatter.jitter), [`scatter.findNearestPointBy`](https://api.highcharts.com/highcharts/series.scatter.findNearestPointBy) and the most important one: [`chart.zoomType`](https://api.highcharts.com/highcharts/chart.zoomType).
