### ISSUE TITLE
Error: <g> attribute transform: Expected number, "…late(0,0) scale(NaN NaN)"

### ISSUE THREAD

**Issue by mmanikandan123** [highcharts/highcharts#13137]
#### Expected behaviour
I am adding highchart map to our application using angular v9.

#### Actual behaviour

when i try add highchart map getting error in the console like below, i am not able to see the map.

**Error: <g> attribute transform: Expected number, "…late(0,0) scale(NaN NaN)".
highcharts.js:54 Error: <g> attribute transform: Expected number, "…late(0,0) scale(-Infinity -Infin…".**

#### Product version

    "@angular/animations": "~9.0.2",
    "@angular/cdk": "^9.1.1",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/material": "^9.1.1",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
    "@azure/msal-angular": "^0.1.4",
    "@highcharts/map-collection": "^1.1.3",
    "bluebird": "^3.7.2",
    "bootstrap": "^4.4.1",
    "highcharts": "^8.0.4",
    "highcharts-angular": "^2.4.0",
    "rxjs": "~6.5.4",
    "rxjs-compat": "^6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"

#### html
         <highcharts-chart
                        id="map-container" 
                        [Highcharts]="Highcharts"
                        [constructorType]="chartConstructor"
                        [options]="mapOption"
                         style="width: 100%; height: 400px; display: block;">
                    </highcharts-chart>
#### ts

               import { Component, OnInit } from '@angular/core';
               import * as Highcharts from 'highcharts';
                import MapModule from 'highcharts/modules/map';
                  import * as worldmap from '@highcharts/map-collection/custom/world.geo.json';
                 MapModule(Highcharts);
                 @Component({
                   selector: 'app-pricing-overview',
                    templateUrl: './pricing-overview.component.html',
                    styleUrls: ['./pricing-overview.component.scss']
                  })
                  export class PricingOverviewComponent implements OnInit{
                   chart;
                   updateFromInput = false;
                  Highcharts = Highcharts;
                   chartConstructor = "mapChart";
                   chartCallback;
                   public stockOptions: object = {
                   chart: {
                        zoomType: 'x'
                     },

                     rangeSelector: {
                       selected: 2
                     },

                     series: [{
                       name: 'USD to EUR',
                       data: stockData
                     }]
                };

                   public mapOption: object = {
                    chart: {
                      map: worldmap
                    },
                     title: {
                       text: 'Highmaps basic demo'
                     },
                    mapNavigation: {
                      enabled: true,
                      buttonOptions: {
                        alignTo: 'spacingBox'
                       }
                     },
                     colorAxis: {
                       min: 0
                     },
                     series: [{
                       name: 'Random data',
                      states: {
                         hover: {
                           color: '#BADA55'
                         }
                      },
                       dataLabels: {
                         enabled: true,
                         format: '{point.name}'
                       },
                        allAreas: false,
                        data:[['ug-2595', 0], ['ug-7073', 1]]
                     }]
                    };

                 constructor() { 

                   const self = this;

                   this.chartCallback = chart => {
                     self.chart = chart;
                   };

                 }
                 ngOnInit() {
                   Highcharts.mapChart('map-container',this.mapOption);
                 }

               }

**Comment by sebastianbochan** [comment]
Hi @mmanikandan123,
Thank you for reporitng. Could you share a simplified live demo? It will allow us to debug the problem.

**Comment by mmanikandan123** [comment]
@sebastianbochan find my below link to reproduce the issue.
[](https://stackblitz.com/edit/angular-23yxcu)

**Comment by mmanikandan123** [comment]
[](https://stackblitz.com/edit/angular-23yxcu)

**Comment by KacperMadej** [comment]
Are you able to recreate the problem in the demo?
I have used Chrome/Win10 and I am unable to recreate the problem, but I had to apply a few changes to the code to make it run in the sandbox:

```ts
import { Component } from '@angular/core';
import * as Highcharts from 'highcharts/highmaps';
//import MapModule from 'highcharts/modules/map';
import * as worldmap from '@highcharts/map-collection/custom/world.geo.json';
//MapModule(Highcharts);

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  chart
  Highcharts = Highcharts;
  chartConstructor = "mapChart";
  chartCallback;
  name = 'Angular';
  public mapOption: object = {
    chart: {
      map: worldmap
    },
    title: {
      text: 'Highmaps basic demo'
    },
    mapNavigation: {
      enabled: true,
      buttonOptions: {
        alignTo: 'spacingBox'
      }
    },
    colorAxis: {
      min: 0
    },
    series: [{
      name: 'Random data',
      states: {
        hover: {
          color: '#BADA55'
        }
      },
      dataLabels: {
        enabled: true,
        format: '{point.name}'
      },
      //allAreas: false,
      data:[['ug-2595', 0], ['ug-7073', 1]],
      keys: ['code_hasc', 'value'],
      joinBy: 'code_hasc'
    }]
  };
   constructor() { 

    const self = this;

    this.chartCallback = chart => {
      self.chart = chart;
    };

  }
  ngOnInit() {
    //Highcharts.mapChart('map-container',this.mapOption);
  }

}
``` 

1) Load Higcharts Maps instead of Highcharts + map module (this is a problem with the sandbox and was never recreated and reported otherwise for Highcharts or highcharts-angular module).
2) The code in `ngOnInit` doesn't look like needed for anything - is the target container even accessible?
3) Commented out `allAreas: false,` to see the map - otherwise, the data you have used makes an empty chart. (Tested with this and without it - both work fine and without any errors in browser console)

**Comment by mmanikandan123** [comment]
@KacperMadej  Thanks for your reply. i am able to see the map.

**Comment by MisterSingh** [comment]
https://codepen.io/mistersingh/pen/abZeJaJ
^ I'm facing the same issue on drawing country level data
Custom maps are being drawn perfectly but in country level facing the same '<g> NaN' issue

**Comment by PaulDalek** [comment]
Hi @MisterSingh

Thank you for reporting this issue. There are two problems in your demo. First of all, I receive the **options2 is not defined** error (get rid of the second highmaps tag in the app container). Secondly, you refer to the wrong map. It should be **'countries/in/in-all'**, not the **'custom/europe'**. Below is a corrected demo that works without a problem.

**Demo**
https://jsfiddle.net/BlackLabel/0vrmk5ny/

**Comment by MisterSingh** [comment]
I need a world map like [this in vue](https://codesandbox.io/s/highcharts-vue-demo-cop9z)  but this wont scope to a country on click. The working example without vue is [here](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/all-maps)
With the approach suggested I have to either import the country data for all the country or install the **92 mb** npm package?

**Comment by PaulDalek** [comment]
@MisterSingh

This is our bug tracker and your issue is not related with the one initially reported. I have noticed that you created a couple of tickets on [SO](https://stackoverflow.com/questions/64946054/unable-to-draw-country-level-maps-using-geojson-in-highcharts) and [forum](https://www.highcharts.com/forum/viewtopic.php?f=14&t=45389#p161559) regarding this topic. Please, continue in one of them.
