### ISSUE TITLE
Gantt Chart : Task Progress Indicator how to show each and every task under the project in days.

### ISSUE THREAD

**Issue by santhanamKheshu** [highcharts/highcharts#13135]
#### Expected behaviour
series.data.completed.amount: 

completed: {
                        amount: 0.12,
                        fill: '#fa0'
                    }

How to pass the values in integer "amount"? I need to pass values like 18 in days to show my task progress.

#### Actual behaviour
Currently i can able to give values 1 to 10 in amount.

**Comment by pawelfus** [comment]
Hi @santhanamKheshu 

You posted on our bug tracker. For questions, please use other support channels: https://www.highcharts.com/blog/support/
