### ISSUE TITLE
Lollipop Chart - Error Bar Placement Issue

### ISSUE THREAD

**Issue by rajeshdanabal** [highcharts/highcharts#13134]
#### Expected behaviour
In column chart, Error bars are displayed on column as shown below.

![image](https://user-images.githubusercontent.com/33329058/76620014-435b4500-6552-11ea-9a11-e057e23e26ac.png)

I expect that the same behavior for lollipop chart as well. 

#### Actual behaviour
In lollipop chart, Error bars are misaligned  as shown below.

![image](https://user-images.githubusercontent.com/33329058/76619944-17d85a80-6552-11ea-85a6-372d6b45d016.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/rajeshdanabal/u7rdz06h/

#### Product version
Highcharts Basic v8.0.4

#### Affected browser(s)
Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @rajeshdanabal,
Thank you for reporting. It looks like the lollipop has influence on x Axis calculations. 

**Workaround:**
Set the lollipop / dumbell series as the last in series object.

Demo:
- https://jsfiddle.net/BlackLabel/93xdcbLg/

_Internal note_
Dumbell modify x position for error bar chart. Probably its conflict between `getColumnMetrics:` methods.

**Comment by rajeshdanabal** [comment]
Hi @sebastianbochan,

Thank you for the workaround.
