### ISSUE TITLE
tickAmount don't works when chart size is small

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#13136]
#### Expected behaviour
tickAmount working.

#### Actual behaviour
tickAmount don't changes nothing.

#### Live demo with steps to reproduce
https://jsfiddle.net/bsqn1v0u/1/

See how there's no 3 ticks, but only 2. But if you change the height to 400px you will get 3 ticks (or whatever amount you put, like 100 ticks, so is not a density problem).

#### Product version
Latest

#### Affected browser(s)
Chrome

**Comment by Llorx** [comment]
Addendum: Setting `tickPixelInterval` to 0 fixes this problem, but I don't get why I don't need to set it to 0 when the chart is 400px height. I guess is a small inconsistency then.

**Comment by pawelfus** [comment]
Thanks for reporting this issue @Llorx - for me height=190px reproduces the issue: https://jsfiddle.net/BlackLabel/8uecp90t/

___
*Internal note:*
It seems it's done on purpose, when `tickPixelInterval` is higher than length of the axis:
https://github.com/highcharts/highcharts/blob/eb26f694c5edc7f6a5ae865d8d2b1c2ce0f041d3/ts/parts/Axis.ts#L5779-L5793

Not a regression, it always worked that way, implemented altogether with `tickAmount` option: 200db0b6a6b84aca24c941e948371e8ee2740708

FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
I agree we should fix it. When `tickAmount` is set, there's no need to check whether `tickPixelInterval` is smaller than the axis length, because the `tickPixelInterval` doesn't apply anyway.
