### ISSUE TITLE
A new (unidentified) category is added when another (longer)series is hidden

### ISSUE THREAD

**Issue by hubaksis** [highcharts/highcharts#13146]
When you have two (or more) series, and one of them is not in the middle of the chart, and you are hiding all long series ('London' in the example below), a new category is added on the right when highchart tries to place the last series in the middle of the chart.

#### Expected behaviour
Category is not added, the defined category 'Jan' should be the last one.

#### Actual behaviour
If you hide 'London', categories moves a bit to the left to show only 'Tokyo' and a new category with the number '6' is added on the right.

#### Live demo with steps to reproduce
1. Open https://jsfiddle.net/Guest538/s4c5tze0/
2. Click on 'London' in the legend

Here is another example, where categories are added on the left side, and there are two of them if you hide 'London': https://jsfiddle.net/Guest538/s4c5tze0/3/
When you turn on 'London' back, a new category '-1' is still visible on the left side of 'Aug'.

#### Product version
Highcharts 7.2.1, 8.0.4

#### Affected browser(s)
Firefox 74.0
Chrome 80.0.3987.132
Edge 44.18362.449.0
IE 11.719.18362.0

**Comment by sebastianbochan** [comment]
Hi @hubaksis,
Thank you for reporting. Highcharts adds space to axis by default (min/maxPadding), and when you calculate extrames, new values (min and max) are rounded. If it is space for new tick, then is added. In your case new tick is out of categories array (array has 6 elements), but you add 7th element. As a result you see the number.

The solution is declare min/max value by params.

Fixed demo:
- https://jsfiddle.net/BlackLabel/a91h0vq3/

ps. the github is our bug tracker, so for general [support](http://www.highcharts.com/support) questions, please use other channels like email / stackoverflow or forum.

**Comment by hubaksis** [comment]
This solution helped me to keep graph responsiveness:

> It is caused by xAxis.minRange which is set to 5 by default. When your series has fewer points than 5, then spaces are created.
> Please, set xAxis.pointRange to 1 and it will be working as you expect, see demos:
> https://jsfiddle.net/BlackLabel/ztyv2kwh
> https://jsfiddle.net/BlackLabel/a1g2ytxu
> API Reference: https://api.highcharts.com/highcharts/xAxis.minRange
