### ISSUE TITLE
Organization Chart cuts nodes

### ISSUE THREAD

**Issue by benzmarkus** [highcharts/highcharts#13157]
#### Expected behaviour
Fully rendered without getting cut

#### Actual behaviour
Getting cut

#### Live demo with steps to reproduce
https://jsfiddle.net/g4yxewbc/

#### Product version
Newest Highcharts version

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @benzmarkus,
Thank you for reporting. It looks like a bug.

Simplified demo:
- https://jsfiddle.net/BlackLabel/1stL2043/

FYI @TorsteinHonsi

**Comment by weixingcai** [comment]
This is also a bug, should now be solved is interception, there may be interception of half the value, the remaining half, very unfriendly
