### ISSUE TITLE
Improve navigation.bindings docs

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#13150]
1. Main description is suggesting only exporting menu: https://api.highcharts.com/highcharts/navigation

> navigation
>
> A collection of options for buttons and menus appearing in the exporting module.

2. Only demo in Highstock is available, add others:
- https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/stocktools/basic-gui
- https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/stocktools/custom-popup

3. Split document into two separate docs (Stock Tools and Annotations GUI / bindings):
- https://www.highcharts.com/docs/stock/stock-tools - note that using bindings we can add annotations, as well as modify chart (e.g. change series type, enable/disable zooming etc).

4. Link the article above in API.

**Comment by raf18seb** [comment]
We could also add more simple demos e.g.:
- custom navigation buttons in Highcharts
- demo for _navigation.bindings_ - _init/steps/end_

**Comment by karolkolodziej** [comment]
Documentation will be splited under a separate task: #16392

**Comment by shayded-exe** [comment]
Why is this feature not mentioned anywhere in the annotations documentation page?

It's hard to discover that this feature even exists at all.

**Comment by pawelfus** [comment]
Hello @shayded-exe 

Good point @shayded-exe! At this moment, `navigation.bindings` is described only in [Stock Tools docs](https://www.highcharts.com/docs/stock/stock-tools), but should also get its own documentation page, mentioned in the Annotations page. Thank you for pointing this out! Created a separate ticket for that: https://github.com/highcharts/highcharts/issues/21227
