### ISSUE TITLE
highcharts8.0.2：pie dataLabels formatter  executes multiple times

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#13159]
#### Expected behaviour
pie dataLabels formatter  executes only one times

#### Actual behaviour
pie dataLabels formatter  executes multiple times，
the same code,when type is bar ,executes one times,but when type is pie executes multiple times

bar：
![QQ截图20200318174044](https://user-images.githubusercontent.com/6789138/76946838-a0367100-693f-11ea-9bdc-97cad92c222e.png)
pie:
![QQ截图20200318174120](https://user-images.githubusercontent.com/6789138/76946891-b5ab9b00-693f-11ea-8712-728e0e65a68d.png)

#### Live demo with steps to reproduce

```js
plotOptions: {
        type:'dynamic',
        styleOperaType: 'plotOptions',
        lineStyle:'line',
        areaStyle:'area',
        series: {
            stickyTracking:false,
            borderWidth: 0,
            label: {
                enabled:false,
            },
            dataLabels: {
                enabled:true,
                useHTML:true,
                style:{
                    textOutline: 'none',
                },
                formatter:function(){
                    console.log('uuuuuuuuuuuuuuuuuuuuu')
                    return 2;
                },
                allowOverlap: false,
            },
        },
    },
```
#### Product version

```js
   "highcharts": "8.0.2",
    "highcharts-3d": "^0.1.7",
    "highcharts-grouped-categories": "^1.1.3",
    "highcharts-regression": "^2.0.1",
    "highcharts-vue": "^1.3.5",
```

**Comment by pawelfus** [comment]
Thanks for reporting the issue @wjhcc2018 

This is expected behaviour - by default, pie chart shrinks to make space for dataLabels. You can disable this, by setting fixed [`pie.size`](https://api.highcharts.com/highcharts/plotOptions.pie.size): https://jsfiddle.net/BlackLabel/6mLub2rj/
