### ISSUE TITLE
loses reference after dispatching redux action from highcharts event

### ISSUE THREAD

**Issue by silversd13** [highcharts/highcharts#13165]
#### Context
I am trying to render a highcharts chart while using a redux to control state updates. The highcharts chart needs to
1. update based on the redux store (this is executed in the chart.events.render and works fine)
2. dispatch actions on events to update the redux store (I want to execute this in scatter.point.events.mouseOver/mouseOut/click, but it is failing for mouseOver/mouseOut)

#### Expected behaviour
On a point mouseOver event, action is dispatched, reference to point is not lost and tooltip continues to refresh/display.

#### Actual behaviour
On a point mouseOver event, action is dispatched, point object contains null references and tooltip refresh throws an error: `TypeError: Cannot read property 'tooltipOptions' of type null`.

Note that the dispatched action updates the state as expected.

#### Live demo with steps to reproduce

It's a bit difficult to demo this since it requires setting up redux stores, but here is a snippet

```
const config = {
      series: [...guides, ...series],
      chart: {
        height: height || 500,
        width: width || 500,
        zoomType: "xy",
        animation: false,
        events: {
          render: function () {
            this.series.forEach(dataSeries => {
                dataSeries.data.forEach(datum => {
                  if (datum.result && (selectedResults.has(datum.result.id))) {
                    datum.select(true, true);
                  } else if (datum.result && (!selectedResults.has(datum.result.id))) {
                    datum.select(false, true);
                  }
                  if (datum.result && (highlightedResults.has(datum.result.id))) {
                    datum.setState('hover');
                  }
                })
              }
            );
          },
        },
      },
      title: {
        text: title,
      },
      tooltip: {
        enabled: true,
        useHTML: true,
        animation: false,
        hideDelay: 0,
        formatter() {
          return keyValueTableTooltipFormatter(this.point.meta);
        },
      },
      xAxis: {
        title: {
          text: xAxisTitle,
        },
        min: xMin,
        max: xMax,
        gridLineWidth: 0,
        tickAmount: 6,
      },
      yAxis: {
        title: {
          text: yAxisTitle,
        },
        min: yMin,
        max: yMax,
        gridLineWidth: 0,
        lineWidth: 1,
        tickAmount: 6,
        tickWidth: 1,
      },
      legend: {
        enabled: false
      },
      plotOptions: {
        series: {
          allowPointSelect: true,
          animation: false,
          cursor: 'pointer',
          stickyTracking: false,
        },
        scatter: {
          point: {
            events: {
              click: function(e) {
                const result_id = this.result.id;
                const point = Object.assign({}, this);
                console.log(point, this)
                onClick(selectedResults, e, result_id)
              },
              mouseOver: function (e) {
                const pt = Object.assign({}, this);
                const result_id = this.result.id;
                console.log('in', result_id, pt, this)
                highlightResult(result_id);
              },
              mouseOut: function (e) {
                const result_id = this.result.id;
                console.log('out', result_id)
                dehighlightResult(result_id);
              },
            },
          },
        },
      },
    };

    return (
      <div>
        <ReactHighcharts config={config} />
      </div>
    );
```

and here is a screenshot of the console:
<img width="786" alt="Screen Shot 2020-03-18 at 2 00 26 PM" src="https://user-images.githubusercontent.com/5520438/77007186-06f86200-6921-11ea-8cce-1592504dbdcd.png">

#### Product version

react-highcharts version 16.1.0

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @silversd13,
Thank you for reporting. The github is our bug tracker, so I advise you to use our [support](http://www.highcharts.com/support) channels like email / stackoverflow or forum.

ps.  The [react-highcharts](https://www.npmjs.com/package/react-highcharts) is not our official wrapper, so please contact with authors of this extension.

ps2. I recommend you to use our official react wrapper available here: https://www.npmjs.com/package/highcharts-react-official
