### ISSUE TITLE
Unable to internationalize "Category", and "DateTime" words in export-data

### ISSUE THREAD

**Issue by gtanczyk** [highcharts/highcharts#13166]
#### Expected behaviour
I would like to be able to internationalize all contents of XLS export

#### Actual behaviour
It's not possible.

https://github.com/highcharts/highcharts/blob/6cae030f630f092d4de845dea4e2e054a32d100a/js/modules/export-data.src.js#L308

**Comment by sebastianbochan** [comment]
HI @gtanczyk,
Thank you for reporting about the problem. I agree that we can extract it to the lang object.

**Comment by raf18seb** [comment]
@sebastianbochan I think we should take it from xAxis title if defined instead of `lang`. See multiple x-axes: https://jsfiddle.net/BlackLabel/7r9js4fw

**Comment by sebastianbochan** [comment]
I agree that we can extract all static labels from data module to the lang object. 
@oysteinmoseng what do you think?

**Comment by oysteinmoseng** [comment]
Agree 100% that we should put all static text in `lang` - and also agree with @raf18seb that it could be useful to add a note in the API somewhere (or in the tutorial docs for the export data module) on how the table is built.

Looking at the current `lang` options, we might want to pull the export-related keys into a new `lang.exporting` option group, and add deprecation/compatibility fixes. Not sure how many new keys the export data module would add. @TorsteinHonsi might have further thoughts on that
