### ISSUE TITLE
xRange - point placement with stacking enabled

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13161]
#### Expected behaviour
After enabling stacking the points should be stack on the same "row".

#### Actual behaviour
The first point is placed on the second row.

#### Live demo with steps to reproduce
The green bar should be placed next to the red one, like yellow is placed next to blue.
https://jsfiddle.net/BlackLabel/aLty3nug/

#### Product version
 Highcharts JS v8.0.4 (2020-03-10)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Note: There's no `xrange.stacking` option. We should skip this series type, when `plotOptions.series.stacking` is set. The expected result can be set using `grouping=false`, demo: https://jsfiddle.net/BlackLabel/aLty3nug/1/
