### ISSUE TITLE
stockTools full-screen button doesn't work

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#13175]
The stockTools full-screen button doesn't work.

Workaround: https://jsfiddle.net/BlackLabel/vyxt195u/

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui/

#### Product version

Highstock JS v8.0.4 (2020-03-10)

**Comment by sebastianbochan** [comment]
In the past the fullscreen did not work in IFRAMEs by default (javascript limits). If it works, we should focus on the lines:

https://github.com/highcharts/highcharts/blob/1e6571d179ba4ab3a36c4b2afb8cc4721343f741/js/modules/stock-tools-gui.js#L815
