### ISSUE TITLE
Update of column series color does not work if zones are used

### ISSUE THREAD

**Issue by KevinFernandes** [highcharts/highcharts#13177]
#### Expected behaviour
Calling series.update() with a different color than what the series was created with, will update the column colors and point marker colors appropriately.

#### Actual behaviour
Calling series.update() with a different color does not update the column color if zones are used.  It appears that the individual point colors and marker colors are not updated if zones are used, even for line charts.

#### Live demo with steps to reproduce
https://jsfiddle.net/kevinfernandes/2j7xLnz9/

This is forked from one of your column chart demos.

Clicking the "Color" button on the bottom of the chart updates the legend with the new colors, and the line updates as well, but the columns and the point markers on the line do not.

If you comment out the zones on each series and run it again, the points and columns update as expected.

#### Product version
Found in version 7.2.1
Not sure what version the demo is using.

#### Affected browser(s)
Tested in Chrome v80

**Comment by sebastianbochan** [comment]
Hi @KevinFernandes,
Thank you for reporting. I would not consider it as a bug. The zone color has the highest priority in color/fill stack. So when you update the series color, the zone color is "more important". 

If you would like to update color, you should edit zones too.

**Comment by KevinFernandes** [comment]
Hi @sebastianbochan 
Ok, maybe this is not a bug - but the implementation of zones appears to be misleading at best.

If you create a zone and do not specify the "color" attribute, as in the demo, then one can assume that the zone will use the color from the series (which is what it does).  Based on that assumption, if you update the series with a new color, one would then assume that the zone (which took its color from the series) would also update with the new color, but it does not.  So zones do not appear to work as expected.  The documentation implies that the "color" property of the zone is optional and acts as an "override" of the series color, so color = zone.color || series.color - which ever is defined, if an override is not specified then the series color would be used.  But it seems that once a zone is defined, it takes its color from the series (if not specified) and then acts "independently" of the series.

You also mention "editing" the zones.  Is there a way to get access to the zones on a series in order to update them?
I could not find a "public" API to either "get" or "update" the existing zones.  The only way I found to update them was to recreate them, from scratch, each time the series is updated.  This feels wrong to me, like there should be a better (easier) way to do this.

If I do update the series with new "zone" objects but do not specify their "color" property (assuming it would take the new updated series color), the zones do not change to the new series color, they continue to display the old color, as if the new zones were ignored or they are getting the color from something other than the series color, I have to specify the color explicitly in the zone object in order for it change color as expected.

So maybe this is not a "bug" but it does not appear to work intuitively either - at least not to me :)

**Comment by sebastianbochan** [comment]
After some debugging I found the problem and agree that is the bug.

Lets consider the demo without zones: 
- https://jsfiddle.net/BlackLabel/Ls02cw6h/ 

After update, color is applied on `series.color` (line) and `point.color` (marker or column). 

In case of using zones, color is applied only on `series.color` but not on `point.color`.
Demo:
- https://jsfiddle.net/BlackLabel/5y7qh1tb/

**Comment by KevinFernandes** [comment]
Thank you for the update and appreciate you taking another look at it.

:)

**Comment by TorsteinHonsi** [comment]
I agree it's a bug. As far as I can see, the part _outside_ the zones behaves wrong. In https://jsfiddle.net/highcharts/8wf2cp1b/, the markers and the lines correctly have red color initially. After update, the line is correctly green, but the markers are not updated.

**Comment by pawelfus** [comment]
*Internal note:*
Might be related to `nonZonedColor` property.
