### ISSUE TITLE
Internet Explorer Some Histogram Values does not show up

### ISSUE THREAD

**Issue by frankhli843** [highcharts/highcharts#13178]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/51806469/77199203-d817f280-6abe-11ea-9207-bed2f02bc8a2.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/51806469/77199224-dfd79700-6abe-11ea-9216-1a8477012c7e.png)

#### Live demo with steps to reproduce
*  [JS Fiddle](https://jsfiddle.net/q0w2f4dk/)
*  [Link that works for internet explorer](https://jsfiddle.net/q0w2f4dk/embedded/result,css,html,js)

#### Product version
- Highcharts JS v8.0.4

#### Affected browser(s)
- Internet Explorer 
![image](https://user-images.githubusercontent.com/51806469/77199456-3e047a00-6abf-11ea-838d-94ff4d10c2a5.png)

**Comment by KacperMadej** [comment]
Hi @frankhli843 

Thank you for contacting us about the problem.

It looks like you have set a bad code for the color (D9514EFF - 8-digit) and Chrome handles it as 6-digit hex color while IE11 fails to do so. If you really wanted to use a 8-digit color then for opacity control I am recommending alpha channel in rgba color encoding.
