### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Saravana29** [highcharts/highcharts#13174]
We recently upgraded hightchart version from 7.0.0 to 7.1.1

Highcharts are not loading after this upgrade and below error appears on console

RangeError: Maximum call stack size exceeded
    at u (highcharts.js:16)
    at Object.<anonymous> (highcharts.js:16)
    at Object.a.objectEach (highcharts.js:29)
    at u (highcharts.js:16)
    at Object.<anonymous> (highcharts.js:16)
    at Object.a.objectEach (highcharts.js:29)
    at u (highcharts.js:16)
    at Object.<anonymous> (highcharts.js:16)
    at Object.a.objectEach (highcharts.js:29)
    at u (highcharts.js:16)

Line number 16: `strokeSetter:function(){this.elem.attr(this.prop,a.color(this.start).tweenTo(a.color(this.end),this.pos),null,!0)}};a.merge=function(){var k,e=arguments,q,t={},u=function(e,p){"object"!==typeof e&&(e={});a.objectEach(p,function(h,d){!a.isObject(h,!0)||a.isClass(h)||a.isDOMElement(h)?e[d]=p[d]:e[d]=u(e[d]||{},h)});return e};!0===e[0]&&(t=e[1],e=Array.prototype.slice.call(e,2));q=e.length;for(k=0;k<q;k++)t=u(t,e[k]);return t};a.pInt=function(a,e){return parseInt(a,e||10)};a.isString=function(a){return"string"===`

Line number 29: 
`b||a&&a!==d.timers[m].prop||(d.timers[m].stopped=!0)},Y=d.objectEach=function(b,a,m){for(var f in b)Object.hasOwnProperty.call(b,f)&&a.call(m||b[f],b[f],f,b)};Y({map:"map",each:"forEach",grep:"filter",reduce:"reduce",some:"some"},function(b,a){d[a]=function(a){return Array.prototype[b].apply(a,[].slice.call(arguments,1))}});var fa=d.addEvent=function(b,a,m,f){void 0===f&&(f={});var c=b.addEventListener||d.addEventListenerPolyfill;var p="function"===typeof b&&b.prototype?b.prototype.protoEvents=b.prototype.protoEvents||`

After exploring the minified version of highcharts.js line number 16 and 29. I found its part of the source code [https://github.com/highcharts/highcharts/blob/master/ts/parts/Utilities.ts](https://github.com/highcharts/highcharts/blob/master/ts/parts/Utilities.ts) 

line number 16 -> Utilities.ts (line number 1339):
doCopy = function(copy: any, original: any): any {
    // An object is replacing a primitive
    if (typeof copy !== 'object') {
        copy = {};
    }

    objectEach(original, function(value: any, key: string): void {

        // Copy the contents of objects, but not arrays or DOM nodes
        if (isObject(value, true) &&
            !isClass(value) &&
            !isDOMElement(value)
        ) {
            copy[key] = doCopy(copy[key] || {}, value);

            // Primitives and arrays are copied over directly
        } else {
            copy[key] = original[key];
        }
    });
    return copy;
};

line number 29-> Utilities.ts(line number 2798)
   `const objectEach = H.objectEach = function objectEach<T>(
    obj: any,
    fn: Highcharts.ObjectEachCallbackFunction<T>,
    ctx?: T
): void {
    /* eslint-enable valid-jsdoc */
    for (var key in obj) {
        if (Object.hasOwnProperty.call(obj, key)) {
            fn.call(ctx || obj[key], obj[key], key, obj);
        }
    }
};`

Need help to fix this issue

#### Affected browser(s)
Chrome, Edge

**Comment by Saravana29** [comment]
Hi @sebastianbochan ,
Thank you for the response, I updated the issue with complete code details.
Please read the issue again which may help you to analyze the rootcause.

We will be using the version 7.1.1 for few more months and we are planning to update the latest highchart version(8.0.4) after getting approval internally which is time consuming process.

Really appreciate if you provide the fix for the version 7.1.1

Thank You,
Saravana

**Comment by pawelfus** [comment]
Hi @Saravana29 

Thank you for debugging, but Sebastian asked for a simplified live demo, for example using jsFiddle.

Most likely it's caused by self-referencing options object, for example: https://jsfiddle.net/BlackLabel/4zwmx8c0/ - so I would start with checking your options. The simplest test is to use `console.log(JSON.stringify(options))` which will throw error in case of circular references, take a look: https://jsfiddle.net/BlackLabel/ndajz0tg/

**Comment by Saravana29** [comment]
Hi @pawelfus 
I  upgraded to version 8.0.4 and still the same error as described in the issue.
Right now its difficult for me to create a sample using jsfiddle, because the code base of the project and data is complex.

We are using Angular 6, and below are the versions related to highchart

    "highcharts": "^8.0.4",
    "highcharts-angular": "^2.4.0",
    "angular-highcharts": "^6.2.6",

Please help based on the details I provided.

Thank You,
Saravana

**Comment by sebastianbochan** [comment]
Hi @Saravana29,
Thank you for details. Currently we are not able to reproduce the problem without example of your data and chart options. Please share these details for the further debugging.

**Comment by Saravana29** [comment]
@sebastianbochan I am closing this issue, it's a code issue where we had options "Highcharts: Highcharts". After removing this line its working fine. But we are not facing this issue in 7.0.0.

Thank you all for the replies on this issue.
