### ISSUE TITLE
Dynamically populated tooltip is clipped when tooltip.outside is set to `true`

### ISSUE THREAD

**Issue by alfonsomunozpomer** [highcharts/highcharts#13173]
#### Expected behaviour
The tooltip is fully shown.

#### Actual behaviour
The tooltip is clipped.

#### Live demo with steps to reproduce
```bash
git clone https://github.com/ebi-gene-expression-group/atlas-components.git
cd atlas-components
npm install
npx lerna bootstrap
cd pacakges/scxa-tsne-plot
npx webpack-dev-server -d    # browse http://localhost:9000
```

![image](https://user-images.githubusercontent.com/4425744/77168760-499c7480-6ab0-11ea-9f83-27ce47a4ba75.png)
Left tooltip is populated with [an `async` function that does a `fetch` to retrieve the tooltip contents](https://github.com/ebi-gene-expression-group/atlas-components/blob/71bc1145d6956a26591548c672c7f92304fcbc10/packages/scxa-tsne-plot/src/ClusterTSnePlot.js#L88). The right one is static.

#### Product version
Highcharts 8.0.3

#### Affected browser(s)
Firefox 73, 74, 75
Chromium 79

**Comment by alfonsomunozpomer** [comment]
I fixed this by adding the following style:
```css
.highcharts-tooltip-container svg {
  overflow: visible;
}
```

I’m not sure why `overflow` is set to `hidden`, or if it’s just inherited.

**Comment by sebastianbochan** [comment]
Hi @alfonsomunozpomer,
The github is a bug tracker, so for general [support](https://www.highcharts.com/support) questions please use our other channels like forum / stackoverflow or email.

**Comment by alfonsomunozpomer** [comment]
I’d argue this is a bug, since it requires an undocumented CSS fix, and the behaviour you get from using `tooltip.outside:true` isn’t what one would expect.

**Comment by sebastianbochan** [comment]
Could you share simplified live demo of your chart? It will allow us to debug.

**Comment by alfonsomunozpomer** [comment]
Here you have it:
https://jsfiddle.net/amunoz/pgho7jL0/59/

Please see the comments in the JS block, under `tooltip` and in the CSS block.

**Comment by pawelfus** [comment]
Async tooltip's content is not fully supported, not yet, see #6824 - I see you use workaround to update tooltip's text, but it's just a workaround and may require, as in your case, a bit more changes. I suggest to add your demo (+workaround) to #6824 ticket, so we keep all use cases in one place. Thanks!
