### ISSUE TITLE
Wrong extremes with dynamically disabled scrollbar

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#13184]
#### Expected behaviour
The `xAxis` should have the same extremes as without the scrollbar: http://jsfiddle.net/BlackLabel/rLqm140s/3/

#### Actual behaviour
In the second update `xAxis.min` property is not respected. 

Actual: -3 --- 0. 
Expected: 0 --- 0.

#### Live demo with steps to reproduce
1. Open jsfiddle: http://jsfiddle.net/BlackLabel/rLqm140s/2/
2. Wait 4 seconds

#### Product version
Highstock 8.0.4

#### Affected browser(s)
All

#### Original issue
https://github.com/highcharts/highcharts-react/issues/206

**Comment by pawelfus** [comment]
**Workaround:**

Use `xAxis.scrollbar` instead of `scrollbar` option: http://jsfiddle.net/BlackLabel/rLqm140s/4/
