### ISSUE TITLE
IE7 - Dashed lines lose style when moving the chart DOM element

### ISSUE THREAD

**Issue by leoasis** [highcharts/highcharts#1318]
This happens only in IE7, in all other browsers this seems to work fine.
If you have a chart with dashed series (or any line in general, vertical or horizontal), and you render the chart in an element, when you try to move it to another place of the dom (detach the node and then attach it somewhere else), the dashed lines lose their styles and colors, and appear as thin black dashed lines.

Here is an example, you will see the chart correctly for 2 seconds, and then the chart is moved so you can see the difference:

http://jsfiddle.net/2xUqQ/3/

**Comment by cvasseng** [comment]
Hi! We're doing a bit of spring cleaning, and closing old issues. If you're still experiencing issues with this, please feel free to open a new issue! Thanks!
