### ISSUE TITLE
Tooltip is shown for hidden points when using colorAxis.dataClasses

### ISSUE THREAD

**Issue by aleksandr-kovalenko** [highcharts/highcharts#13195]
#### Expected behaviour
Tooltip should not be shown for hidden points (the same behaviour if we just hide serie in legend).

#### Actual behaviour
After user hides points from chart with `colorAxis.dataClasses` used it is still possible to hover over hidden points to get tooltip.

#### Live demo with steps to reproduce
https://jsfiddle.net/Lj6t4590
STR:
1. open demo from link
2. hide points by clicking ranges in the legend
3. move mouse pointer over places where points were present

#### Product version
 Highcharts JS v8.0.4 (2020-03-10) (latest CDN version)

#### Affected browser(s)
Google Chrome 80.0.3987.149 64-bit MacOS

**Comment by pawelfus** [comment]
Thank you for reporting this @aleksandr-kovalenko 
___
FYI @ppotaczek
