### ISSUE TITLE
Y axis ticks & labels are not seen center aligned for vertical tick label orientation when align Y axis is enabled

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#13204]
#### Expected behaviour
Y axis tick labels should be center alligned with the Y axis ticks for vertical tick label orientation.

#### Actual behaviour
When align ticks is ON, Y axis ticks and labels are not seen center alligned when tick labels orientation is set as vertical.

#### Live demo with steps to reproduce
Align Y axis ON - https://jsfiddle.net/amrutaJgtp/c3eup5qx/6/ 
Align Y axis OFF - https://jsfiddle.net/amrutaJgtp/c3eup5qx/5

**Comment by pawelfus** [comment]
Thanks for reporting @amruta30 

**Simplified demo:**
https://jsfiddle.net/BlackLabel/or03hvg6/

**Workaround:**
Set [`yAxis.labels.align`](https://api.highcharts.com/highcharts/yAxis.labels.align) = `"center"` (and `labels.x` if necessary), demos:
- https://jsfiddle.net/BlackLabel/bt0hzgf4/
- https://jsfiddle.net/BlackLabel/4e1ghbyk/

**Comment by amruta30** [comment]
@pawelfus  Thanks for the workaround!
