### ISSUE TITLE
highstock rangeselector behaviour

### ISSUE THREAD

**Issue by behnam7171** [highcharts/highcharts#13205]
#### Expected behaviour
In highstock, In range selector, in mentioned example bellow, when I change 'from' datetime to '2019/12/23 00:00:00.000', the input will change to 7 hours past to '2019/12/22 17:00:00.000'.
Any datetime in 'from' input will have same behaviour. I believe this can be a bug. I could not find any explanation in documents or internet.

#### Actual behaviour
to show '2019/12/23 00:00:00.000' in the input and filter the data properly (which I believe it does filter properly)

#### Live demo with steps to reproduce
https://jsfiddle.net/skd4t382/1/

#### Product version
8.0.4 also in 6.x

#### Affected browser(s)
Chrome Version 80.0.3987.149

**Comment by pawelfus** [comment]
Thanks for reporting @behnam7171 

**Workaround:**
Use custom [`rangeSelector.inputDateParser`](https://api.highcharts.com/highstock/rangeSelector.inputDateParser) to add timezone offset: https://jsfiddle.net/BlackLabel/48uah2x1/

Snippet:
```js
    inputDateParser: function(value) {

      var date = new Date(value);

      return date.getTime() - date.getTimezoneOffset() * 60 * 1000;
    }
```

@TorsteinHonsi could you take a look? In short:
- chart is using UTC time
- inserted value `2019/12/21 00:00:00.000` is translated to `1577055600000` (using `Date.parse('2019/12/23 00:00:00.000')`)
- then:
```
> Highcharts.dateFormat('%Y/%m/%d %H:%M:%S.%L', 1577055600000);
< "2019/12/22 23:00:00.000"
```

With `useUTC: true` we get two subtracted hours. With `useUTC: false` we get one subtracted hour. In theory, we compensate for timezone offset after changing value.

**Comment by TorsteinHonsi** [comment]
I think we should create a fix that implements Pawel's workaround as the default `inputDateParser`, instead of a simple `Date.parse`. Make sure to test with `useUTC` with local time. Since `new Date` parses it as local time, maybe we should not substract the timezone offset in that case?
