### ISSUE TITLE
Tooltips - xDateFormat -not working for groups of data (missing API?)

### ISSUE THREAD

**Issue by Eldenroot** [highcharts/highcharts#13219]
#### Expected behaviour
When I set my custom time and date format for my tooltips - all is fine until you have groups data

#### Actual behaviour
When data are grouped -> default datetime format it used

#### Live demo with steps to reproduce

- set to 6H period in the Zoom (top left - "Období")
- check the X tooltip - it is something like this
![image](https://user-images.githubusercontent.com/778890/77774836-f85e2900-704b-11ea-80c8-97cffd50626b.png)

I use this format: %A - %e.%B %Y, %H:%M:%S

- set to 3D period in the Zoom (top left - "Období")
- check again the tooltip - data are grouped (range: '-', time and date format is not as I set (because the default one from library is used).
![image](https://user-images.githubusercontent.com/778890/77775024-4115e200-704c-11ea-9219-71c56a47be9f.png)

How to set my format also for grouped data?! Is there any way or is it missing from API?

#### Product version

latest - CDN

here is my site: http://net.cekuj.net/

#### Affected browser(s)
all tested (Chrome, Firefox, Edge, ...)

**Comment by sebastianbochan** [comment]
Hi @Eldenroot,
Thank you for reporting. 

The github is our bug tracker, so for general [support](https://www.highchats.com/support) questions please use other channels like forum / stackoverflow or email.

ps. your demo is hanging, so please recreate your simplified chart as live demo i.e on jsfiddle.
