### ISSUE TITLE
Wrong pointer position after a reflow

### ISSUE THREAD

**Issue by Chris-Lauer** [highcharts/highcharts#13220]
#### Expected behaviour
Hovering over a chart samples the correct point (correct cursor position) after a chart.reflow (called when the parent div is resized)

#### Actual behaviour
The cursor is in the wrong spot and the wrong datapoint is sampled after a reflow.

#### Live demo with steps to reproduce
Rather conveniently, this bug is apparent in an official example!
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/events-container/
Run the fiddle. Click the chart. Try to mouse over the chart to sample some data. The wrong point will be sampled, it'll sample somewhere left of where your mouse is. 

#### Product version
7.2.1 and above (worked find in 7.2.0)

#### Affected browser(s)
Definitely: Google Chrome
Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @Chris-Lauer,
Thank you for reporting.  It's a regression.

_Internal note_
Bisect leads me to https://github.com/highcharts/highcharts/commit/8359afc2223b24508cb039bb7ad4ced7b2517923

FYI @TorsteinHonsi

**Comment by johnhansen-js** [comment]
It's a big problem for me as well. Here is another modified example from highcharts.com where I reproduced this issue: https://jsfiddle.net/0ocagyf8/

**Comment by Chris-Lauer** [comment]
The workaround in the linked issue worked great for us, and was easy to implement: chart.pointer.chartPosition = null;

**Comment by johnhansen-js** [comment]
Thank you very much, @Chris-Lauer . That worked perfectly!

with bug: https://jsfiddle.net/0ocagyf8/2/
with workaround: https://jsfiddle.net/0ocagyf8/3/

**Comment by spogulis** [comment]
My use case is using `areaspline` chart within Vue, together with` <component :is="">` and a modal where the chart is within a `slot` of the changing component. Unfortunately just setting the `pointer.chartPosition` to `null` on the load callback didn't work but using a timeout of 500ms did the trick if anyone else is struggling with this.

Highcharts version: 9.3.0
