### ISSUE TITLE
Axis labels with step do not show up with smaller chart width

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#13227]
#### Expected behaviour
Show axis labels with a specified step

#### Actual behaviour
When the chart width is smaller we can see only the first label. 
To observe that, change the output width (in my case it is 800px)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/d370r2gp/

#### Product version
Highcharts v8.0.4

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
I agree with @sebastianbochan - you can observe what happens when `labels.step` is disabled: https://jsfiddle.net/BlackLabel/d370r2gp/1/ As you can see, there's only ~12 labels, so setting `step=100` does render only the first label.
