### ISSUE TITLE
Semi circle donut with no data

### ISSUE THREAD

**Issue by awocallaghan** [highcharts/highcharts#13229]
#### Expected behaviour

When rendering a semi circle donut chart with no data the pie shape should still be a semi circle

#### Actual behaviour

The semi circle becomes a full circle moved downwards

#### Live demo with steps to reproduce

No data: https://jsfiddle.net/y4750g9f/
With data: https://jsfiddle.net/2aj5tsxm/

#### Product version
Latest version

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @awocallaghan,
Thank you for reporting. I would also consider the border which should not be rendered at all. 

Workaround:
- reset border: https://jsfiddle.net/BlackLabel/z4dv1709/

**Comment by sebastianbochan** [comment]
_Internal note_

We should use `renderer.arc` to draw shape instead of `renderer.circle` in `drawEmpty` method.

https://github.com/highcharts/highcharts/blob/d753ebd22cf5d9e4a475ba2088ecd012c97f5985/js/parts/PieSeries.js#L783

@pawelfus any doubts?
