### ISSUE TITLE
Tooltip preventing interaction with chart components

### ISSUE THREAD

**Issue by gbenthomas** [highcharts/highcharts#13226]
#### Expected behaviour
Navigator should be draggable after interacting with tooltip even if tooltip overlaps the navigator

#### Actual behaviour
Top part of navigator is not draggable after interacting with tooltip around navigator

#### Live demo with steps to reproduce
https://jsfiddle.net/Lvtrzna7/

1. Hover over the last point in the chart to display the tooltip
2. Try dragging the navigator by using the right handle. The top part of the navigator handle is not clickable.

![TooltipNavigatorIssue](https://user-images.githubusercontent.com/35936423/77934952-68e88e00-7276-11ea-8c97-04f004506988.gif)

The navigator height in our app is set to be smaller than the default. This is how I found the issue.

Just an observation: I noticed "pointer-events: none" was being set on the group with the .highcharts-tooltip-header class before. If I set it manually in Chrome, this works as expected. 

#### Product version
Highstock v8.0.4 (8.0.3 does not have this behavior)

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @gbenthomas,
Thank you for reporting abou the problem.

Its a regression.

**Comment by Izothep** [comment]
Bisected to commit b5e724f889
