### ISSUE TITLE
The labels of x-axis in Gantt chart will be messy after zoom

### ISSUE THREAD

**Issue by lazyanger** [highcharts/highcharts#13221]
#### Expected behaviour
The labels should be well rendered.

#### Actual behaviour
The labels will be messy after zoom like this:
![image](https://user-images.githubusercontent.com/18509186/77865896-3ed9a080-7263-11ea-8b8b-731d7b93c0c8.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/38djgahx/

**Comment by sebastianbochan** [comment]
Hi @lazyanger,
Thank you for reporting about the problem. 

_Internal note_
It looks like similar to https://github.com/highcharts/highcharts/issues/12884

**Comment by TorsteinHonsi** [comment]
Simplified demo: https://jsfiddle.net/highcharts/4q56epws/
