### ISSUE TITLE
Boxplot q1, q3, median are not displaying when max and min are null

### ISSUE THREAD

**Issue by rammohan201** [highcharts/highcharts#13243]
#### Expected behaviour
q1, q3 and median should be displayed when max and max are null in data

#### Actual behaviour
complete box is not displaying

#### Live demo with steps to reproduce
Go to below fiddle and check the first category in the chart, boxplot is not rendered because min and max of the first category are null, I expected that boxplot will be displayed with lower, upper quartile and median. but it is not showing
https://jsfiddle.net/rammohanreddy201/ga20p14y/28/

I can try setting whiskerWidth, stemWidth and whiskerLenght 0 but that will not display tooltip.
Please suggest.

#### Product version

7.x
#### Affected browser(s)
I am testing in chrome. but this is not browser specific

**Comment by sebastianbochan** [comment]
Hi @rammohan201,
Thank you for reporting. In math definition a boxplot is:

>  a standardized way of displaying the dataset based on a five-number summary: the minimum, the maximum, the sample median, and the first and third quartiles.

So all param are required in Highcharts too.

I would not consider it as a bug.

@TorsteinHonsi what do you think?

**Comment by rammohan201** [comment]
@sebastianbochan Thanks for responding so quickly, is there any work around in boxplot to achieve this behavior?

**Comment by sebastianbochan** [comment]
@rammohan201,
The simplest way is preprocess data and replace null values with first value (median).

Demo:
- https://jsfiddle.net/BlackLabel/ob49krz0/

Please be aware that is really simple workaround and not full complex solution.
