### ISSUE TITLE
All JSFiddle examples do not work from https://api.highcharts.com/highcharts/ with https://code.highcharts.com/highcharts.js

### ISSUE THREAD

**Issue by pacocom** [highcharts/highcharts#13248]
All JSFiddle examples do not work from https://api.highcharts.com/highcharts/ with https://code.highcharts.com/highcharts.js

#### Expected behaviour

Not working
```html
<script src="https://code.highcharts.com/highcharts.js"></script>
<div id="container" style="height: 400px"></div>
```

Working
```html
<script src="https://github.highcharts.com/highcharts.js"></script>
<div id="container" style="height: 400px"></div>
```

#### Actual behaviour
Not render Highchart chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/showlastlabel-true/

#### Affected browser(s)
I try with Chrome, Firefox and Edge (Windows 10).

**Comment by sebastianbochan** [comment]
Hi @pacocom,
Thank you for reporting. It looks like auto-run option is broken in jsfiddle, but please be aware that we are not developers of this tool.

Solution:
- click on RUN button then demo works.
