### ISSUE TITLE
time.getTimezoneOffset called with NaN when using stockChart

### ISSUE THREAD

**Issue by mediafreakch** [highcharts/highcharts#13247]
#### Expected behaviour
The chart renders without any errors.

#### Actual behaviour
Rendering the chart throws an error because it got `timestamp` that is `NaN`.

#### Live demo with steps to reproduce
https://codesandbox.io/s/happy-night-hoqp2

#### Product version
8.0.4

#### Affected browser(s)
Chrome

#### Comments

I am using `time.getTimezoneOffset` to avoid Moment.js. Instead, I am using `date-fns-tz`. But the conversion of the timestamp to the desired timezone fails, because `getTimezoneOffset` is called with `NaN` for an unknown reason.

- I assume it should be possible to display 2 different series (one type line, the other type column) on the same axis.
- The xAxis min, max, minRange settings seem to affect this bug as well (try to comment them, while type="column" is commented)
- I included the unminified highcharts source, it's easy to debug the internals like this. Make sure though you open the preview in a separate tab

**Comment by pawelfus** [comment]
Thanks for reporting the issue @mediafreakch 

In general, when updating chart with multiple operations, we recommend to set `redraw=false` and then calling `chart.redraw()`. It seems that also resolves the issue: https://codesandbox.io/s/reverent-jones-rkxjw

___
*Internal note:*
It seems that `dataGrouping` is involved here: trying to group points in the second, empty series, gets wrong extremes, when disabling it's fine: https://codesandbox.io/s/practical-borg-2jr1j

I would start debugging from this point:
https://github.com/highcharts/highcharts/blob/47fb5fe159a2851f2476d715eb721f7102c1c763/ts/parts/DataGrouping.ts#L718-L735

Where `Math.min(123, [][0])` returns NaN.

**Comment by mediafreakch** [comment]
Thanks for the quick reply! I tested it in my original source code and it **doesn't** fix the problem. Something else might be in play here. I'll try to find the difference and i'll give an update here when I find something.
