### ISSUE TITLE
Bubble Chart: Problem with positioning dataLabels when bubble is beyond plotArea

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#13240]
#### Expected behavior
Possibility to set dataLabels position in the middle of the bubble with available API options.

#### Actual behavior
In the case of this chart configuration where the bubble goes beyond plotArea, it is not possible to set dataLabels correctly, see demo: https://jsfiddle.net/BlackLabel/dutzanxh/ 

The documentation would indicate that with the options I used in the above demo it should be possible: https://api.highcharts.com/highcharts/series.bubble.dataLabels.overflow 

##### Internal notes
This issue may be related to this case: https://github.com/highcharts/highcharts/issues/8923

#### Product version
Highcharts v8.0.4

#### Affected browser(s)
Chrome 80.0.3987.149

**Comment by pawelfus** [comment]
**Workaround:**
Use data labels alignment from `scatter` series type: https://jsfiddle.net/BlackLabel/t9n3y271/

Snippet:
```js
Highcharts.seriesTypes.bubble.prototype.alignDataLabel = Highcharts.seriesTypes.scatter.prototype.alignDataLabel;
```
