### ISSUE TITLE
Animation error when adding null values and then shifting

### ISSUE THREAD

**Issue by jamilwalker** [highcharts/highcharts#1325]
http://jsfiddle.net/Pj5wA/1/. 

To demo the issue:

Click the start button to begin plotting. Then click stop. Wait a few seconds then click start again. 

The chart animation gets messed up.

Happens in all browsers.

Any help in fixing this is greatly appreciated. Thanks.

Jamil

**Comment by oysteinmoseng** [comment]
Still relevant when adding two points in quick succession: http://jsfiddle.net/genz47pw/.
