### ISSUE TITLE
plotoptions.pie.datalabels.inside does not have any effect in pie chart

### ISSUE THREAD

**Issue by Bethhh** [highcharts/highcharts#13254]
#### Expected behaviour
Pie chart labels should be inside.

#### Actual behaviour
Pie chart label position does not change. (still outside)

#### Live demo with steps to reproduce
https://jsfiddle.net/bzecLwfr/1/

#### Product version
5.0.6

**Comment by sebastianbochan** [comment]
Hi @Bethhh,
Thank you for reporting. It looks like API docs issue, because of requirement to use negative distance in pie chart.

Demo:
- https://jsfiddle.net/bzecLwfr/1/

FYI @bre1470
