### ISSUE TITLE
Problem with using pan and zoom on mobile browsers

### ISSUE THREAD

**Issue by e965** [highcharts/highcharts#13253]
Hi everyone! I am trying to get a live chart update when panning on mobile browser. As far as I understand, the default behavior of the library doesn't imply this.

I found a [potential solution](https://github.com/highcharts/highcharts/issues/5270#issuecomment-342767958) to my problem from one of the developers of Highcharts, but when using it breaks the chart drag with one finger on the Y-axis.

Live demo: https://codepen.io/e965/pen/PoqvWJq (dots and Highcharts options taken from real work project). By the way i am using Highcharts boost module.

How can i resolve problem with panning on Y-axis? I will be grateful for any help :)

**Comment by sebastianbochan** [comment]
Hi @e965,
Thank you for contacting us. The github is our bug tracker, so please use our other channels (forum / stackoverflow or forum) for [support](https://www.highcharts.com/support) questions.
