### ISSUE TITLE
Gantt chart - group expand only displays last point

### ISSUE THREAD

**Issue by cyau73** [highcharts/highcharts#13257]
When there is more than 1 data point with the same name, all points are supposed to appear when the group is expanded after its collapsed. But only the last one appears.
Also happens when you click to expand another group.

Live version: https://jsfiddle.net/cyau73/wzcdgq4t/
Click on Group 1 to collapse then again to expand. Only 1 data is displayed.

Version: Highcharts Gantt JS v8.0.4 

Browsers: Chrome, Safari

**Comment by sebastianbochan** [comment]
Hi @cyau73,
Thank you for reporting.

Simplified demo:
- https://jsfiddle.net/BlackLabel/0swe1kyo/

FYI @oysteinmoseng

**Comment by LLIyRiK** [comment]
Still not working, are there any plans to fix it?

**Comment by karolkolodziej** [comment]
Thank you @LLIyRiK for bringing our attention to this issue once again.
We will take a look and will keep you posted!

**Comment by MarkusBarstad** [comment]
If I understand this correctly, setting `uniqueNames` to `false` for the `yAxis` will give the desired behavior, unless I am missing something 🤔

**Comment by karolkolodziej** [comment]
@MarkusBarstad with `uniqueNames: false` initially you have:
![image](https://github.com/highcharts/highcharts/assets/57004120/69c600db-e18a-4695-a5c6-ef3117da1c59)

And after you collapse and expand you get:
![image](https://github.com/highcharts/highcharts/assets/57004120/995d1350-3ffc-4fef-ac96-68737ccee800)

See the points missing

**Comment by MarkusBarstad** [comment]
Thank you for your reply @karolkolodziej I see now what you are saying!

I have one more question about the gantt series in general and the users demo: I notice that in his demo multiple points share a similar `id`. Is this a correct configuration of a gantt point or do we expect users to supply a unique id per point?

With a unique `id` the points do reappear upon expanding/collapsing: https://jsfiddle.net/796tyuv3/2/

**Comment by karolkolodziej** [comment]
@MarkusBarstad good catch- `id` should be unique otherwise isn't the correct configuration.
