### ISSUE TITLE
Boost crashes not boosted charts - makes it unable to redraw

### ISSUE THREAD

**Issue by melloc01** [highcharts/highcharts#13265]
## What happens

After _a while_ charts seem to lose their series context.

**Note 1: Charts [0] [1] and [2] are crashed**

**Data in series**
![image](https://user-images.githubusercontent.com/4994258/78626943-9e890a80-7866-11ea-969a-9bc3557c4946.png)

**Note 2: Boost is disabled but `allowForce` is true**:
![image](https://user-images.githubusercontent.com/4994258/78627238-54545900-7867-11ea-8adf-51fd18997fc7.png)
No series boosting though

**Note 3: We have in-browser compression over time**
Is there a possibility that when we remove points the series goes out of the boost mode and then it crashes?

**Series types:**
![image](https://user-images.githubusercontent.com/4994258/78627952-296b0480-7869-11ea-9df1-2aee4d5375ba.png)

Actually, I'm not entirely sure of what would help on debugging, but follow screenshots of function calls that appear on the Stack trace:

**Stack trace:**
![image](https://user-images.githubusercontent.com/4994258/78628124-b8781c80-7869-11ea-9e5b-4fb0815cdd19.png)

_highcharts.js?26fb:319 Uncaught TypeError: Cannot read property 'x' of undefined_
![image](https://user-images.githubusercontent.com/4994258/78628086-967e9a00-7869-11ea-91b7-dc74e4b0c7d0.png)

_at p.c (boost.js?af68:54)_
![image](https://user-images.githubusercontent.com/4994258/78628156-c7f76580-7869-11ea-9aca-2fb2bdd58bae.png)

Please let me know if I can be more helpful, as you can see I'm clueless of any internal arrangement that could cause this.

**Comment by melloc01** [comment]
Not related to boost, removed it and it still happens.
Trying to figure out what is happening, if anyone can shed some light.. :)

![image](https://user-images.githubusercontent.com/4994258/78628864-e9595100-786b-11ea-9aaa-2a362e9bc105.png)

**Comment by sebastianbochan** [comment]
HI @melloc01,
Thank you for reporting. Could you share your live demo (including simplified charts options and data) i.e by jsfiddle? It will allow us to debug because of images it's really difficult.

**Comment by melloc01** [comment]
Hi @sebastianbochan, turned out the bug was caused by removing points on our compress process without redrawing first. Thanks

**Comment by melloc01** [comment]
By the way, @sebastianbochan - why does removing points would cause such error? 

Would removing points, with redraw:true, after with pending `addPoint` with redraw:false cause this?

If so, why? Is there any doc regarding this?

**Comment by pawelfus** [comment]
Hi @melloc01 

Thank you for all of the details you provided in the issue, but all of them are not helpful without live demo. We don't know how your setting does look like, what is the process to recreate the issue etc. 

> Please let me know if I can be more helpful, as you can see I'm clueless of any internal arrangement that could cause this.

The best would be to follow our "Bug report" template. That really helps us to understand the issue and fix, or explain, why this happens.

> Would removing points, with redraw:true, after with pending addPoint with redraw:false cause this?

Perhaps you use mismatching indexes? Instead of `series.addPoint()` + `point.remove()` did you try using `series.setData(data, redraw, animation, oneToOne)`?

**Comment by melloc01** [comment]
Hi @pawelfus 

> Perhaps you use mismatching indexes? Instead of series.addPoint() + point.remove() did you try using series.setData(data, redraw, animation, oneToOne)

That is probably spot on - but why would that cause the chart to crash? I mean, it should crash my code if I try to remove a point that doesn't exist -  instead, the chart doesn't recover from it. 

On the architecture here, a point comes from a stream of events and the compressing process is scheduled (lodash's debounce 30sec) when a specific kind of event arrives. There is also another function that removes points that is `removeOutersAtLeft` that removes points that shouldn't be on the chart anymore since the x axis has moved. 

Also, the wrapper's redraw itself is the debounced chart's redraw function, so I feel that these scheduling tasks could at some point be running in different conditions - calling the actual redraw  inside the compress task actually fixed it but I feel this report should be here. 

I could make a buffer from that iteration and use setData instead, but I actually benchmarked that and it doesn't seem to make much difference (performance-wise).


> Thank you for all of the details you provided in the issue, but all of them are not that helpful without the live demo. We don't know how your setting does look like, what is the process to recreate the issue etc. The best would be to follow our "Bug report" template. That really helps us to understand the issue and fix, or explain, why this happens.

I'll try to reproduce on a jsfiddle and open a new issue using the Bug Report template, thanks!
