### ISSUE TITLE
Exporting Image different than expected

### ISSUE THREAD

**Issue by cvinhar** [highcharts/highcharts#13274]
#### Expected behaviour
![Expected](https://user-images.githubusercontent.com/46776508/78735383-485abb00-797d-11ea-8f42-c5cc00e6058e.jpg)

#### Actual behaviour
![Reality](https://user-images.githubusercontent.com/46776508/78735389-4db80580-797d-11ea-912c-bc269f40652e.jpg)

Hi there currently I'm facing an issue with exporting the highcharts-gantt as two Image posted above. To be precise I have enable the useHTML true for all the yellow color box that appears in the Expected behaviour. however when I download it as jpeg or png the size is different from what I'm seeing in the front end and all the yellow color box background has been disable.

**Comment by cvinhar** [comment]
here is the code I'm using:

chart: {           
            title: {
                text: 'QPDS Device Roadmap'   
            },
            
            yAxis: {
                uniqueNames: true,
                visible: false,
                labels: {
                    enabled: false,
                },
            },
            xAxis: [
              {                  
                  tickInterval: self.tickinterval(),
                  grid: {
                      cellHeight: 30
                  },
                  tickColor: 'black',
                  lineColor: 'black',
                  labels: {
                      style: {
                          color: 'white',
                      }
                  },
                  currentDateIndicator: {
                      width: 5,
                      color: 'orange',
                      label: {
                          format: 'Today',
                          fontSize: 12
                      }
                  },
              }, {
                  lineColor: '#727373',
                  tickColor: '#727373',
                  labels: {
                      align: 'center',
                      style: {
                          fontWeight: 'bold',
                      }
                  },
              }],
            navigator: {
                enabled: true,
                liveRedraw: true,
                maskFill: '#00000038',
                tickPixelInterval: 20,
            },
            scrollbar: {
                enabled: true
            },
            tooltip: {
                enabled: true,
                headerFormat: '',
                pointFormat: '***Hold left and right mouse button to highlight and copy the text***',

                backgroundColor: 'white',
                borderWidth: 0,
                borderRadius: 0,
                positioner: function () {
                    return { x: 10, y: 35 };
                },
                shadow: false,
                split: false
            },
            rangeSelector: {
                enabled: true,
                selected: 0
            },
            series: [{
                name: 'Event for QPDS',
                data: seriesData,
                dataLabels: [{
                    enabled: true,
                    formatter: function () {
                        if (this.point.VersionName != "") {
                            let format = '<center>' + this.point.VersionName + '</center>';
                            return format
                        }
                    },
                    shape: 'circle',
                    padding: 10,
                    backgroundColor: 'rgba(0, 0, 0, 0.75)',
                    color: 'white',
                    style: {
                        cursor:"context-menu",      
                    },
                    verticalAlign: 'top',  
                    y: 'max',
                }, {
                    formatter: function () {
                        if (this.point.DisplayName != "") {
                            let text = ''
                            return text
                        }
                    },
                    style: {
                        cursor: "context-menu",                        
                    },
                    shape: 'connector',
                    color: 'white',
                    enabled: true,
                    borderWidth: 3,
                    borderColor: 'black',
                }, {
                    useHTML: true,
                    inside: true,
                    style: {
                        color: self.StatusId() == 1 ? 'blue' : (self.StatusId() == 2 ? '#98a198' : (self.StatusId() == 3 ? 'red' : 'green')),
                        textDecoration: self.StatusId() == 3 ? 'line-through' : '',
                        textOutline: 'none',
                    //    cursor: "context-menu"
                    },                    
                    allowOverlap:false,
                    formatter: function () {
                        if (this.point.DisplayName != "") {
                            let format = '<center id="timelinelabels">' + this.point.DisplayName + '</center>';
                            return format
                        }
                    },
                }
                ],
            }],

**Comment by pawelfus** [comment]
Hi @cvinhar 

Check our docs regarding rendering HTML in Highcharts: https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#html-in-highcharts

I don't see anywhere in your code [`exporting.allowHTML`](https://api.highcharts.com/highcharts/exporting.allowHTML) option set to true. Could you set it and let us know the result? Thanks!

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
