### ISSUE TITLE
Drag the map vertically

### ISSUE THREAD

**Issue by angeliqueIcono** [highcharts/highcharts#13270]
The bug seems to be fixed and closed in highmaps but I use highcharts and I still have the bug...

**Comment by pawelfus** [comment]
Hi @angeliqueIcono 

As explained in #12671 - this should be fixed on the master branch, take a look: https://jsfiddle.net/BlackLabel/du8bow32/ (first zoom-in, then use alt+drag&drop to use panning). 

If you found a case when it's broken, then please create new issue and follow our "Bug report" template when creating new issue.
