### ISSUE TITLE
Field 'label' instead of 'mark' holds SVGElement for a Tick in 8.0.4 contrary to the API.

### ISSUE THREAD

**Issue by Sakkyoku-Sha** [highcharts/highcharts#13281]
Using the latest yarn/npm install "highcharts": "^8.0.4", with typescript

#### Expected behaviour

Field 'Mark' holds the SVGElement for the tick.

#### Actual behaviour

Undefined typescript field 'label' holds the SVGElement for the XAxis tick forcing me to do the following: 

```
//@ts-ignore
chart?.xAxis[0]?.ticks[1]?.label?.on('click', () => {window.alert("click on mark")});
```

Clicking on 1 should not result in a alert in the following example https://jsfiddle.net/yow68ajn/2/ given the typescript definitions.

The documentation on the [Highcharts API seems to imply that label is no longer used to hold the SVGElement for the tick past version 8.0.0](https://api.highcharts.com/class-reference/Highcharts.Tick#Tick).  However in practice the field 'Mark' holds no actual value. 

This issue would be closed by either adding label to the official typescript definition, or moving the label's SVGElement to be rendered under the 'Mark' field.

**Comment by sebastianbochan** [comment]
Hi @Sakkyoku-Sha,
Thank you for reporting.

FYI @bre1470

**Comment by bre1470** [comment]
Hello @Sakkyoku-Sha,
I am not sure, if I understand the issue report. In your example `Axis.mark` is holding the tick element, and `Axis.label` contains the label element. Each tick has two elements generated, if labels are enabled. So I assume you like us to make `Axis.label` a documented property like `Axis.mark`. If this is not, what your are asking for, please let us know.

**Comment by bre1470** [comment]
Hello @Sakkyoku-Sha,
Sorry, I confused the classes. This is a request about the `Tick.label` property becoming public like `Tick.mark`.
