### ISSUE TITLE
Volume by price indicator isn't working

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#13287]
The VBP indicator is not working.

#### Live demo with steps to reproduce
Open, below demo - VBP is not displayed. When moving navigator, it is displayed for a while, then throws many errors into the console.

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/indicators/volume-by-price

#### Product version
Highstock 8.0.4

FYI @PaulDalek

**Comment by raf18seb** [comment]
Seems like it is working now. We will reopen if the problem occurs again.

**Comment by pawelfus** [comment]
It still looks broken to me:
<img width="468" alt="Screen Shot 2020-04-15 at 13 46 46" src="https://user-images.githubusercontent.com/1453926/79333899-993f5600-7f1f-11ea-8dfb-23dff40233b8.png">

@PaulDalek
