### ISSUE TITLE
Overflow:justify doesn't work when linkedTo is used

### ISSUE THREAD

**Issue by andrewkolesnikov** [highcharts/highcharts#1328]
The following combination is not producing justified labels:

``` javascript
  opposite: true,
  linkedTo: 0,            
  overflow: 'justify'
```

Isolated test: http://jsfiddle.net/EEr9j/

**Comment by oysteinmoseng** [comment]
Not sure what expected behavior is here, should the label not be rendered at all? We now have automatic ellipsis for axis labels, that kicks in here.

Closing for now, feel free to reopen if still relevant.
