### ISSUE TITLE
chart.destroy instance method throws TypeError: Cannot read property 'isSVG' of undefined

### ISSUE THREAD

**Issue by nc-reesl** [highcharts/highcharts#13295]
#### Expected behaviour
`chart.destroy` instance method successfully destroys the chart instance without error.

#### Actual behaviour
When using the annotations module, invoking the `chart.destroy` instance method results in the following error:

```
index.js:1 TypeError: Cannot read property 'isSVG' of undefined
    at a.SVGElement.destroy (highcharts.js:54)
    at a.Chart.<anonymous> (annotations.js:28)
    at highcharts.js:31
    at Array.forEach (<anonymous>)
    at Object.a.each (highcharts.js:29)
    at a.fireEvent (highcharts.js:31)
    at a.Chart.destroy (highcharts.js:273)
```

This problem seems to be independent of the options that are passed to the chart (I've tried this using very simple sets of options). This issue does not occur without the annotations module. Updating to highcharts 8 seems to fix this issue, but this is not an option for us since we are not licensed for this version.

#### Live demo with steps to reproduce
n/a

#### Product version
highcharts 6.2.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @nc-reesl 

Thank you for reporting the issue, but we don't have plans to release new version of v6. And it seems to be working fine: https://jsfiddle.net/BlackLabel/6qu20th9/ (wait ~1s to destroy the chart).

Please, recreate issue in jsFiddle and contact our support: https://www.highcharts.com/blog/support/ - maybe they will be able to find a workaround for you.
