### ISSUE TITLE
stacking area chart connectNulls:true setting is not working

### ISSUE THREAD

**Issue by wy1713** [highcharts/highcharts#13304]
#### Live demo with steps to reproduce
https://jsfiddle.net/q7omybph/1/

#### Product version
latest

#### Affected browser(s)
chrome

**Comment by sebastianbochan** [comment]
Hi @wy1713,
Thank you for reporting about the problem. This bug is know and has been already reported in our repo.

Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/2069

**Comment by pawelfus** [comment]
Just a note: This was not a bug. In stacking, null points are treated as 0, when `connectNulls` is set to true.
