### ISSUE TITLE
Offline DPF export for vertical charts is cutting the chart

### ISSUE THREAD

**Issue by aggiustino** [highcharts/highcharts#13309]
#### Issue
Then exporting a vertical chart (where the height is greater than the width) to PDF using the offline export, the downloaded PDF is chopping the chart. The page orientation seems wrong.

#### Live demo with steps to reproduce
[https://jsfiddle.net/4s6wuoyd/6/](https://jsfiddle.net/4s6wuoyd/6/)

#### Product version
Highcharts 8.0.4

#### Affected browser(s)
Chrome 80
Safari 13.1
Firefox 75

**Comment by pawelfus** [comment]
Thank you for reporting the issue @aggiustino 

It seems that landscape (`'l'` vs `'p'`) mode is always set: 
https://github.com/highcharts/highcharts/blob/1ae472ded0517e4352fa82948e6e447e3b25f3c4/ts/modules/offline-exporting.src.ts#L356-L360
