### ISSUE TITLE
Norfolk Island in Australian Highmaps looks like it has the wrong coordinates

### ISSUE THREAD

**Issue by paul-jcu** [highcharts/highcharts#13306]
#### Expected behaviour
Plots Norfolk Island more north that it is.

#### Actual behaviour
Looks like it is plotting where Lord Howe Island is located instead.

#### Product version
Highmaps v8.0.4

#### Affected browser(s)
Assume all

**Comment by KacperMadej** [comment]
Hi @paul-jcu 

Thank you for reporting the problem.
The bug is like you have described it.
I will just move this issue to the correct repository:
https://github.com/highcharts/map-collection-dist/issues/58
