### ISSUE TITLE
yAxis values are not rendered properly as per given min max

### ISSUE THREAD

**Issue by nagdevbharat** [highcharts/highcharts#13301]
#### Expected behaviour
Y-Axis values should be properly rendered as per given in min and max value at the time of the initialization process 

#### Actual behaviour
the Y-Axis range values are not in between given min and max value as provided an option at the time of initialization process

#### Live demo with steps to reproduce
A demo which shows the Y-Axis range values are not expected as per given in option
http://jsfiddle.net/gqtaup70/1/

We searched and found & tried the "startOnTick" and "endOnTick" options. But doesn't get expected result
http://jsfiddle.net/gqtaup70/

#### Product version
Highstock JS v5.0.12 (2017-05-24)

#### Affected browser(s)
All browsers

**Comment by sebastianbochan** [comment]
Hi @nagdevbharat,
Thank you for contacting us. The problem is related with aligning ticks of multiple yAxis by default. The solution is disable this option by param [chart.alignTicks](https://api.highcharts.com/highcharts/chart.alignTicks)

Demo:
- http://jsfiddle.net/BlackLabel/fueszLpo/

**Comment by nagdevbharat** [comment]
Hello @sebastianbochan 

Thanks for the update
We have tried the solution you have suggested but still, the problem didn't get resolved.
AS per shown in the chart details Ymin is -3 and Ymax is 5 but though after implementing the solution suggested by you the value displayed on Y-axis is 
Ymin -4 and Ymax +2 which is still not proper.
Can you please help us with any other solution?

Thanks in advance.

**Comment by pawelfus** [comment]
Hi @nagdevbharat 

Could you please elaborate this?
> We searched and found & tried the "startOnTick" and "endOnTick" options. But doesn't get expected result http://jsfiddle.net/gqtaup70/

For me this is exactly the expected result you described: 
> Y-Axis values should be properly rendered as per given in min and max (...)

`start/endOnTick` options are disabled, so **yAxis does not start on a tick**, and yAxis has exactly the extremes you set in options:

```js
> Highcharts.charts[0].yAxis[0].getExtremes()
<
{
  min: 26
  max: 60
  dataMin: 42.52017825113323
  dataMax: 43.476367017293775
  userMin: undefined
  userMax: undefined
}
>  Highcharts.charts[0].yAxis[1].getExtremes()
< 
{
  min: -3
  max: 5
  dataMin: 2.836414995692539
  dataMax: 3.1721162295783345
  userMin: undefined
  userMax: undefined
}
```

This is how chart is rendered:
<img width="494" alt="Screen Shot 2020-04-15 at 08 40 14" src="https://user-images.githubusercontent.com/1453926/79306027-c4608000-7ef4-11ea-98f7-a249eee2c943.png">

**Comment by nagdevbharat** [comment]
Hello @pawelfus
Thanks for your help

We are getting almost the nearest value but still not getting the exact value.
Our expected output is min -3 and max 5
but we are getting output as min -2.5 and max 2.5

Moreover as shown in the screenshot, there are two lines showing near the values of 40 and 30 which should be one line only. 
![79306027-c4608000-7ef4-11ea-98f7-a249eee2c943](https://user-images.githubusercontent.com/43880269/79462562-4a73e800-8015-11ea-91b9-69a9125db4f1.png)

It will be great if you would help us to solve this which would get us the desired outcome.

Thanks in advance.

**Comment by sebastianbochan** [comment]
Hi @nagdevbharat,
The reason of that is calculated tickInterval. Set the parameter as i.e 1 and then both extremes will be respected.

Demo:
- http://jsfiddle.net/BlackLabel/nohak05t/
