### ISSUE TITLE
Highstock accessibility

### ISSUE THREAD

**Issue by dcowen91** [highcharts/highcharts#13305]
#### Expected behaviour
In an accessible chart with scrollbar enabled, when scrolling to a point that is outside the current viewpane, the chart should scroll to display it

#### Actual behaviour
the chart doesn't scroll, so the content is not visible but the tooltip indicates that the next point has been selected

#### Live demo with steps to reproduce
https://jsfiddle.net/5nbg7wt9/
1. Use tab key to select an item in the series
2. use arrow keys to navigate to an item that is not visible inside the current scrollable section

#### Product version
Latest

#### Affected browser(s)
 Chrome

![image](https://user-images.githubusercontent.com/6540263/79168416-b0a30580-7d9e-11ea-8f5b-3fd2e616678e.png)

**Comment by sebastianbochan** [comment]
Hi @dcowen91,
Thank you for reporting about the problem.

FYI @oysteinmoseng
