### ISSUE TITLE
Make highcharts responsive

### ISSUE THREAD

**Issue by maitrivasa** [highcharts/highcharts#13303]
Context: I am trying to create 3 charts on 1 row (each has a minimum width) such that on window resize, the charts should also resize and may go to the next row depending on the browser total width.

#### Expected behaviour
If the screen is not big enough, the charts can go to the next row. Also, on resize of the window, the highchairs should resize up to its minimum width

#### Actual behaviour
Currently, I am missing something in the CSS because the chart is overflowing within the demo container below. The tooltip looks fine, but only half of the chart is seen in the container and both the axes are also hidden.

#### Live demo with steps to reproduce
https://stackblitz.com/edit/angular-wftxkw?embed=1&file=src/app/app.component.ts

#### Product version
I am using the latest version of Highcharts and Angular 7.

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @maitrivasa,
Thank you for contacting us. The github is our bug tracker so please stackoverflow / forum or email for general [support](https://www.highcharts.com/support) questions.

ps. you can declare [responsive rules](https://api.highcharts.com/highcharts/responsive) for charts.
