### ISSUE TITLE
Missing Mymensingh Division of Bangladesh 

### ISSUE THREAD

**Issue by anjarul** [highcharts/highcharts#13300]
# Description of the feature
Missing Mymensingh Division of Bangladesh

# Library related to the feature
Might be highcharts/map-collection/countries/bd/bd-all.geo.json

**Comment by KacperMadej** [comment]
Hi @anjarul 

Thank you for reporting about the map change.
The map we have is from before the missing division was created.
I will just move this case to the correct repository: 
 https://github.com/highcharts/map-collection-dist/issues/59
