### ISSUE TITLE
`stickOnContact` has confilct with `useHTML`

### ISSUE THREAD

**Issue by imrickywong** [highcharts/highcharts#13313]
#### Expected behaviour
`stickOnContact` can still function well when the toolip is built with `useHTML`

#### Actual behaviour
If turn `useHTML` on, the `stickOnContact` works weriedly

#### Live demo with steps to reproduce

https://jsfiddle.net/Rickyyyyyyyyy/e7th9a4g/17/

#### Product version

v8.0.4

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting, but it's already reported: #13310

Closing as duplicate of #13310
