### ISSUE TITLE
Export data module having private members affecting TypeScript types

### ISSUE THREAD

**Issue by henrieri** [highcharts/highcharts#13316]
#### The issue
Using chart.downloadXLS() gives me TypeScript error. 

#### Why it happens
I think it happens because in this file:
https://github.com/highcharts/highcharts/blob/cccf5a0d61133ac0b5982f4df33f92f0936f1657/js/modules/export-data.src.js
Highcharts.Chart.prototype.downloadXLS is marked as `@private`. 

Although within this file it exists https://github.com/highcharts/highcharts/blob/cccf5a0d61133ac0b5982f4df33f92f0936f1657/ts/modules/export-data.src.ts

In the generated export-data.src.d.ts there are 5 available methods and none of them are `@private` so this leads me to believe that this is the issue.

I would suggest a fix where `@private` was removed from downloadXLS and other similar methods within that file.

#### Product version
Highcharts 8.04

**Comment by pawelfus** [comment]
Thanks for reporting @henrieri 

Could you take a look @bre1470 ?

I agree, methods `Chart.downloadXLS` and `Chart.downloadCSV` should be available in API and TS. The rest of private methods should remain private.

**Comment by bre1470** [comment]
@pawelfus 
Yes. We will make `Chart.downloadXLS` and `Chart.downloadCSV` public.
