### ISSUE TITLE
Styled mode - offline export - PDF - data label borders

### ISSUE THREAD

**Issue by dhrimov** [highcharts/highcharts#13319]
There are several key points to match:
- Styled mode enabled
- Use custom color index
- Use offline exporting
- Export to PDF
- Data labels enabled

#### Expected behaviour
Data labels should not have any borders

#### Actual behaviour
Each data label has a border

#### Other info / Workarounds
Does not reproduce if pass a color for each point, but then legend color will be wrong.
Does not reproduce if use exporting server.
Works well with other exporting types - e.g. image works correctly

#### Live demo with steps to reproduce
https://jsfiddle.net/demongd/dbjxzan5/

- Open fiddle
- Export to PDF using burger menu
- Open the file

#### Product version
Highcharts 7.1.1
Highcharts 8.0.4

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @dhrimov,
Thank you for reporting about the problem.

_Internal note_
The issue is only in the offline-module.
FYI @oysteinmoseng
