### ISSUE TITLE
x number of minor ticks per major tick

### ISSUE THREAD

**Issue by awall** [highcharts/highcharts#13338]
# Description of the feature
When minorTicks is set to "auto", we get 5 minor ticks per major tick. Ideally, I would like to set the major ticks using other properties, like tickPixelInterval or tickAmount, and set the minor ticks as "2 minor ticks per major tick", or any other arbitrary multiple. Why restrict it to exactly 5?

Add some property to set this value from 5 to any arbitrary integer.
Please make sure it works in logarithmic and date axes, too!

# Library related to the feature
Highcharts

You can vote for the feature by adding thumbs-up reaction for this post.

**Comment by sebastianbochan** [comment]
Hi @awall,
Thank you for your suggestion. I think that it could be something like tickAmount, but minorTickAmount.

We could parametrize this line:
https://github.com/highcharts/highcharts/blob/f9dc90de6c19a4410bba40c56846cec283155e37/js/parts/Axis.js#L1484-L1487

Have you tried to use [minorTickInterval](https://api.highcharts.com/highcharts/xAxis.minorTickInterval) ?

**Comment by awall** [comment]
Thanks @sebastianbochan. In my case, the minorTickInterval does not work, it does work correctly for logarithmic or date axes (I've logged separate bugs for these issues already).

**Comment by KacperMadej** [comment]
It works for logarithmic (https://jsfiddle.net/BlackLabel/vem4q6yt/) but doesn't look good since the offset is critical. It works for datetime (https://jsfiddle.net/BlackLabel/vem4q6yt/1/) - the units are milliseconds.

**Comment by awall** [comment]
@KacperMadej Logarithmic only works for very specific numbers, try changing that "0.1" to "0.5" and see what happens ;). I've logged this bug already as https://github.com/highcharts/highcharts/issues/13337

As for datetime, I'd really like to use the default behaviour for the major ticks, and then just "2 minor ticks per major tick". If I use tickInterval and minorTickInterval, I need to write an enormous amount of tricky code involving dates and the chart width... this code is already built-in to how highcharts determines the major ticks on a date axis, and it is very painful to have to reverse engineer and duplicate that code.

**Comment by pawelfus** [comment]
See plugin posted in #13336.  Demo: https://jsfiddle.net/BlackLabel/oc70hqxm/

**Comment by pawellysy** [comment]
unstale

**Comment by ReillyBova** [comment]
Unstale — this is a pretty reasonable customization request. 5 minor ticks per major is very noisy / visually dense. Having the option to set the "auto" value would be much appreciated

**Comment by TorsteinHonsi** [comment]
Thank you for your input @ReillyBova , I think we can get this done. We will do some internal discussions about how.

**Comment by TorsteinHonsi** [comment]
After some internal discussion, we decided to add a new option `minorTicksPerMajor`, which will default to 5. The implementation appears to be quite simple, just replace the number 5 on this line:

https://github.com/highcharts/highcharts/blob/4800dec33e9d77e625092f4fef4fef20ae292f23/ts/Core/Axis/Axis.ts#L1957

My preliminary tests show that this works on linear, logarithmic and datetime axes.

**Comment by ReillyBova** [comment]
Awesome! Thank you!
