### ISSUE TITLE
Tooltip does not to properly pop up when changing chart height dynamically since Chrome 81 

### ISSUE THREAD

**Issue by hitochan777** [highcharts/highcharts#13342]
### Expected behaviour

After dynamically increasing chart height (say, from 0.1 to 400), tooltip should still pop up not only when the mouser cursor is on the line but also when the cursor is on the empty space in a chart.

### Actual behaviour

**After upgrading from chrome 80 to chrome 81,**
Tooltip does not pop up as you move the mouse cursor on the empty space in the chart, but it does pop up if you move the cursor onto the line.

### Live demo with steps to reproduce
[Reproduction in CodeSandbox](https://codesandbox.io/s/highcharts-vue-demo-93b6i)

**Google Chrome 80.0.3987.149**
![chrome80](https://user-images.githubusercontent.com/6002787/79629786-2801dc00-8187-11ea-88ca-01eb4be08ca2.gif)

**Google Chrome 81.0.4044.113**
![chrome81](https://user-images.githubusercontent.com/6002787/79629785-26381880-8187-11ea-993a-feed70ef4216.gif)

### Product version
* highcharts: 8.0.3
* highcharts-vue: 1.3.5

### Affected browser(s)
Chrome 81

**Comment by sebastianbochan** [comment]
Hi @hitochan777,
Thank you for reporting.

**Simplified demo:**
- https://jsfiddle.net/BlackLabel/q4nak9fm/

Chrome: 81.0.4044.113
MacOSX: 10.14.6

**Comment by TorsteinHonsi** [comment]
Yes, it should be enough to change the test for `container.offsetHeight` to `> 2`. We previously had a similar workaround for IE.
