### ISSUE TITLE
Offline PDF export failure when setting an image as a export contextButton symbol

### ISSUE THREAD

**Issue by aggiustino** [highcharts/highcharts#13341]
#### Expected behaviour
When `fallbackToExportServer` is set to false and export module is present, the PDF should be generated locally and downloaded. 

#### Actual behaviour
DPF generation is failing with a console error. This happens when setting an image as a export contextButton symbol.

#### Live demo with steps to reproduce
https://jsfiddle.net/4kxg2j7z/

#### Product version
8.0.4

#### Affected browser(s)
All.

**Comment by sebastianbochan** [comment]
Hi @aggiustino,
Thank you for reporting the problem. Im not sure if it is a bug, because of the definition of problem here https://www.highcharts.com/errors/28/, the fallback should be declared for offline exporting.

_Internal note_
FYI @oysteinmoseng what do you think?

**Comment by oysteinmoseng** [comment]
PDF offline-export does not support images, as mentioned in our [client side exporting documentation](https://www.highcharts.com/docs/export-module/client-side-export), so this is intended behavior.

Note that you can easily install [your own version](https://www.highcharts.com/docs/export-module/setting-up-the-server) of our export server on your local server if you have security-related limitations with using our online server.
