### ISSUE TITLE
It doesn't show the problem

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13344]
####

All of them show up

#### Actual behaviour

The red line in the picture is not shown

#### Live demo with steps to reproduce

https://jshare.com.cn/temp/BHGT7n

![1](https://user-images.githubusercontent.com/48822299/79717359-f2650c00-82c8-11ea-8150-84c46cd6a3bd.png)

**Comment by sebastianbochan** [comment]
Hi @weixingcai,
Thank you for contacting. The chart is draw according to connections defined in your series. As I see all of them are correct. Could you elaborate why these extra red lines should be visible? Im not sure what is the reason of that.

**Comment by weixingcai** [comment]
Because they have their own description and name, some of this chart is shown, some is not shown, not shown is not correct, should be displayed

**Comment by sebastianbochan** [comment]
Now I understand, you mean that labels inside boxes are missing.

The problem has been already reported here: https://github.com/highcharts/highcharts/issues/13100 and is resolved in our master branch. Will be a part of next official release within next few weeks.
