### ISSUE TITLE
Gantt chart with yAxis scrollbar and grids multiplies the scrollbar

### ISSUE THREAD

**Issue by JohanBrodinSinch** [highcharts/highcharts#13359]
#### Expected behaviour
Only one scrollbar is expected

#### Actual behaviour
Each grid is causing the chart to add an extra scrollbar. So four grid columns renders four scrollbars.

#### Live demo with steps to reproduce
https://jsfiddle.net/JohanBrodin/bwc183gp/4/

#### Product version
Latest. Did use one of your demos

#### Affected browser(s)
Tested on Chrome but assume all

<img width="830" alt="Screenshot 2020-04-22 at 18 18 30" src="https://user-images.githubusercontent.com/50442378/80007195-3a04b700-84c6-11ea-9061-e7256e5d4a49.png">

**Comment by JohanBrodinSinch** [comment]
Did read below workaround suggestion. However where should you add the corresponding min and max? Independently if you put it under yAxis or in the first column the scrollbar is always 100% extended. So not a workaround if you cannot use the scrollbar.

https://github.com/highcharts/highcharts/issues/10641

**Comment by sebastianbochan** [comment]
Hi @JohanBrodinSinch,
Thank you for reporting. It looks like a bug.

As a workaround you can disable scrollbars in each grid.

Demo:
- https://jsfiddle.net/BlackLabel/fb712kys/

FYI @oysteinmoseng

**Comment by JohanBrodinSinch** [comment]
Thx for your quick replay! Yes it is working fine with your workaround. 

For me this also looks like a bug. You cannot do scrolling per grid so having to disable them individually is not an expected user behaviour.

**Comment by sebastianbochan** [comment]
Hi @JohanBrodinSinch,
I found also a simpler solution: declare scrollbar in the grid, which should include it.

Demo:
- https://jsfiddle.net/BlackLabel/tsmhyLug/

As a result you do not need to disable in others grids.

I agree that is a bug.
