### ISSUE TITLE
Is there any way to sort the order of "to" part of the series?

### ISSUE THREAD

**Issue by digish777** [highcharts/highcharts#13368]
I have this Sankey Chart, I want Z to option to be displayed, as the last item in "to" section the Sankey Chart.

**Comment by digish777** [comment]
I ma using, HighCharts 8.0.0. You have added this Question to Development Flow. Does this mean, it is under developement?

**Comment by sebastianbochan** [comment]
Hi @digish777,
Thank you for contacting us. The github is our bug tracker, so for general [support](https://www.highcharts.com/support) questions please use stackoverflow / email or forum.

ps. The assigning to project is auto to keep proper tracking in our kanban.
