### ISSUE TITLE
Tick amount changes when changing series visibility- scatter

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#13369]
#### Expected behaviour
Tick amount should remain the same when you change series visibility.

#### Actual behaviour
When changing the series visibility, tick amount changes. 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/6wbzfnsd/

#### Product version
Highcharts 8.0.4

#### Affected browser(s)
All

**Comment by madepiet** [comment]
It can also be related to this issue. When we draw a chart with two yAxis, the redraw method is called at the very end. Everything works fine until we redraw the chart which causes recalculation of the ticks: https://jsfiddle.net/BlackLabel/g54xpf1y/

It looks like tickAmount is counting incorrectly after redraw, so possible workaround may be marking all axis as isDirty, and calling redraw with use of fixed number once again after initially drawing chart: https://jsfiddle.net/BlackLabel/y2jmpd8k/
