### ISSUE TITLE
plotBand events not working if it was added with the api addPlotBand()

### ISSUE THREAD

**Issue by prdatur** [highcharts/highcharts#13375]
If the chart is initialized without a plotBand option within the xAxis option, no events are attached if it get's added at a later point.
If there is an existing plotBand option, the event's will be attached, the plotBand option must not include any plotBand, just the option needs to exist.

Problem is that `isNew` is false on second loop without an existing plotBand option.
I checked this with:
`console.log('create plot', isNew, options.id, path);`

before

```
// common for lines and bands
if ((isNew || !svgElem.d) && path && path.length) {
```

If the `plotBand` option **does not** exists, isNew is within the first call `true` and on second `false`
If the `plotBand` option **does** exists, on first and second isNew is `true`

#### Expected behaviour

Events should get attached correctly.

#### Actual behaviour

`if ((isNew || !svgElem.d) && path && path.length) {` is false and the events are not attached.

#### Live demo with steps to reproduce
http://jsfiddle.net/d2k6r1bs/13/

Saved version has the issue, uncomment the plotBand option to get the expected behaviour

#### Product version
Highstock JS v8.0.4 (2020-03-10)

#### Affected browser(s)
All, (Verified in Firefox + Chrome in Win + Linux, IE 11 + Edge (not the chrome version))

**Comment by sebastianbochan** [comment]
Hi @prdatur,
Thank you for reporting about the problem. 

Simplified demo:
- http://jsfiddle.net/BlackLabel/dy4rjmzx/
