### ISSUE TITLE
Crash in item chart with no or empty data in horizontal/vertical layout

### ISSUE THREAD

**Issue by egraether** [highcharts/highcharts#13379]
#### Expected behaviour
No crash when series object does not hold data or data is empty.

#### Actual behaviour
Crash when series object has no data property, or data is empty

#### Live demo with steps to reproduce
https://jsfiddle.net/axnu0smv/

* Run -> crash
* Change chart type to `pie` -> works
* Change layout to circular by defining `startAngle` and `endAngle` -> works

#### Product version
8.0.4

#### Affected browser(s)
Tested in Chromium

**Comment by sebastianbochan** [comment]
Hi @egraether,
Thank you for reporting about the problem.

ps. We are grateful for your detailed tests of the new item series.
