### ISSUE TITLE
Gantt multiple bugs

### ISSUE THREAD

**Issue by JohanBrodinSinch** [highcharts/highcharts#13376]
#### Expected behaviour
1. Independent how the gantt bars are dragged by the user error #15 should not be triggered. Or it should be possible to disable error #15.
2. xAxis setExtreams shall be called when user draggs gantt bar to the right. This forces the xAxis to scroll so the extream value is changed.
3. It shall be possible to have an empty navbar. 

Please see picture below as well as demo link

#### Actual behaviour
1. Error #15 are triggered dragging the example "Testing" gantt bar to the right.
2. xAxis setExtreams are not triggered dragging the example "Testing" gantt bar to the right.
3. Removing series having a empty navbar causes strange lines to be drawn.

#### Live demo with steps to reproduce
https://jsfiddle.net/JohanBrodin/nb07o36t/20/

#### Product version
Latest. Used the current demo from your homepage

#### Affected browser(s)
Tested on Chrome but assume all browsers

<img width="1280" alt="Gantt errors" src="https://user-images.githubusercontent.com/50442378/80348707-7f323b80-886e-11ea-8762-bf8990f287cf.png">

**Comment by sebastianbochan** [comment]
Hi @JohanBrodinSinch,
Thank you for reporting.

**Comment by pawelfus** [comment]
Just a word of explanation:

- error 1) - it's caused by these strange lines in the navigator. You can simply disable the series in navigator (or use gantt type, not line) by setting `navigator: { series: { data: [] } }`, demo: https://jsfiddle.net/BlackLabel/amyo1xgb/
- error 2) - use `afterSetExtremes`, demo: https://jsfiddle.net/BlackLabel/amyo1xgb/1/
- error 3) - solved in the first point

Let us know if you find any other issues @JohanBrodinSinch

**Comment by JohanBrodinSinch** [comment]
Thank you for the replay!

- #1 This is unfortunately not the solutions. Adding  navigator: { series: { data: [] } } has the side effect that the navigator, in your example, stops scrolling when dragging items to the right (Please see below picture)
- #2 Great thank you!
- #3 Not the solution since first point is not working.

Is there a way to manually disable error #15

<img width="500" alt="Screenshot 2020-05-07 at 00 54 38" src="https://user-images.githubusercontent.com/50442378/81236967-a91df780-8ffe-11ea-90ae-c009c2cd7b8c.png">

Regards
Johan

**Comment by pawelfus** [comment]
Thanks for the explanation @JohanBrodinSinch 

In this case I suggest one of two possible solutions:
- use `gantt` type in the navigator: https://jsfiddle.net/BlackLabel/amyo1xgb/2/ - recommended in Gantt type
- use [`series.point.events.drag`](https://api.highcharts.com/gantt/series.gantt.point.events.drag) and manually update extremes on change, when required

> Is there a way to manually disable error #15

In theory you can't.  Practically, you can set `Highcharts.seriesTypes.line.prototype.requireSorting = false;` to false, see: https://jsfiddle.net/BlackLabel/zmg03df4/ - but **I don't recommend that**. Potential side effects may break other things in your chart and we will not fix that.

**Comment by JohanBrodinSinch** [comment]
Thank you for the replay!

Using gantt was our first solution but is not an option either. You have to select a fixed subset to show in the navigator and with e.g. 15 items in the gantt chart it is very confusing for the user since only the top subset ones are displayed...

All to all there is a workaround for issue 2)

There is more or less no new features coming on gantt and we have seen multiple issues with the dynamic drag&drop flavour. As an example we just figured out that xAxis maxPadding is not either working when you have it in combination with navigator. I would kindly ask highcharts to test dynamic  gantt more thoroughly and at least fix the error 15 that never should be thrown.

**Comment by pawelfus** [comment]
FYI @oysteinmoseng 

In theory, we can keep gantt-like navigator, and exclude items from it by setting `min` and `max` options: https://jsfiddle.net/BlackLabel/amyo1xgb/3/

Regarding error 15 - it's not a bug, not per se. In Gantt chart, navigator should be Gantt type. Using different type (e.g. line) requires different dataset, resulting in missing connection between drag&drop changes and navigator series. I am not sure what is the best solution here, leaving the decision up to @oysteinmoseng

**Comment by oysteinmoseng** [comment]
@JohanBrodinSinch Thank you for taking the time to report these issues.

I agree with Pawel, I think the solution here should be too keep the navigator as a Gantt series, as intended, and configure its presentation as required. Perhaps we could make our documentation and demos more clear to cover this use case. Error 15 with the line series is a good thing in this case, as it stops other errors that would be more difficult to find from happening.

Have you opened an issue for the maxPadding problem?

**Comment by JohanBrodinSinch** [comment]
Setting the min and max to minus did the trick for issue 3). Some time ago I did try out with 0 that did show one bar but did not understand setting minus was a valid value. So you might consider updating documentation since I think having an empty navbar is a common use case.

The error  #15 is tricker. Going back to the original top demo JSFiddle it is not any more occurring with or without using the type gantt in navigator series (fixed by 8.1.0?). Sounds great however running on our angular app using latest 8.1.0 it is still there. Cannot ask you to debug our target system and since it is not having any side effect (at least what we can see) you can close the issue. However I think that if you are running gantt with dragDrop: {} you should disable it all togheter.

  series: { type: 'gantt' },
		yAxis: {
			max: -1,
			min: -2
		}

I will report the maxPadding issue shortly

**Comment by Izothep** [comment]
Just as an internal note:

In case of `setExtremes`, it looks that the event is not triggered with standard Highcharts version as well:
https://jsfiddle.net/BlackLabel/rfqLtanm/4/
