### ISSUE TITLE
Property 'data' does not exist on type 'SeriesOptionsType'.

### ISSUE THREAD

**Issue by JBudny** [highcharts/highcharts#13373]
#### Expected behaviour
`data` property should exist on SeriesOptionsType type.

#### Actual behaviour
TypeScript Error:
`Property 'data' does not exist on type 'SeriesOptionsType'.`
`Property 'data' does not exist on type 'SeriesAbandsOptions'.ts(2339)`

#### Live demo with steps to reproduce

[https://stackblitz.com/edit/angular-highcharts-ts?file=src/app/chart/chart.component.ts](https://stackblitz.com/edit/angular-highcharts-ts?file=src/app/chart/chart.component.ts)
Error in: src/app/chart/chart.component.ts:92
#### Product version

8.0.4
#### Affected browser(s)
__
#### Additional info
I am using Angular 9.0.7 with typescript 3.7.5.

**Comment by bre1470** [comment]
The `data` option has different structures depending on the series type. Therefor you have to check the series type first:

```ts
      if (this.config.series[0].type === 'column') {
        this.config.series[0].data = [...data];
      }
```

Does this solve your problem?

**Comment by bre1470** [comment]
Hello @JBudny,
Thanks for your report. I try ones more to answer this completly. The `data` option has different structures depending on the series type. By default each series is only the most common type with properties like `name` and `type`. When you check the series type though, TypeScript is able to pin down the correct set of series options, which includes the missing `data` property:

```ts
      if (this.config.series[0].type === 'column') {
        this.config.series[0].data = [...data];
      }
```

Does this solve the issue for you?

**Comment by JBudny** [comment]
Hey, @bre1470. Thank you, it solves my issue.

**Comment by cjonasw** [comment]
Hey @bre1470, thanks for this..

```
 if (this.config.series[0].type === 'column') {
     this.config.series[0].data = [...data];
 }
```
This does work, however is there a definitive list of types that *don't* have data? It'd be nice to do something like this instead:

```
 if (!['abands', 'ads'...].includes(this.config.series[0].type)) {
     this.config.series[0].data = [...data];
 }
```

any help appreciated!

**Comment by pawellysy** [comment]
Hello @cjonasw. The types, that you listed here are technical indicators. Those series types don't accept data, because the data is calculated based on the linked series. You can read more here: https://www.highcharts.com/docs/stock/technical-indicator-series

**Comment by cjonasw** [comment]
Thanks @pawellysy. I posted as a potential generic alternative to @bre1470. However TS doesn't seem to be clever enough to check a type outcome depending on "includes".

**Comment by Shyam-Chen** [comment]
```ts
import type { Options } from 'highcharts';

const lineChartOptions = {
  {
    title: {
      text: '',
    },
    xAxis: {
      categories: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
    },
    yAxis: {
      title: {
        text: '',
      },
    },
    tooltip: {
      shared: true,
    },
    series: [
      {
        type: 'spline',
        name: '2021',
        data: [40, 68, 86, 74, 56, 60, 87],
        color: '#6366f1',
      },
      {
        type: 'spline',
        name: '2022',
        data: [65, 78, 66, 44, 56, 67, 75],
        color: '#ec4899',
      },
    ],
  }
} as Options & { series: (Options['series'] & { data: number[] })[] };

const idx_2021 = lineChartOptions.series.findIndex((serie) => serie.name === '2021');
lineChartOptions.series[idx_2021].data = Array.from({ length: 7 }, () => randomInt());
```
