### ISSUE TITLE
TooltipPositionerCallbackFunction is incorrectly typed

### ISSUE THREAD

**Issue by causbas** [highcharts/highcharts#13370]
#### Expected behaviour
Parameter `point` should be of type `TooltipPositionerCallbackFunction`, which contains properties `plotX` and `plotY` as mentioned in the description of `tooltip.positioner`.

The type of `this` is missing, which should be `Tooltip`.

#### Actual behaviour
Accessing `point.plotX` or `point.plotY` will cause a 'does not exist' error.

#### Product version
8.0.4

**Comment by sebastianbochan** [comment]
Hi @causbas,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by causbas** [comment]
Thank you
