### ISSUE TITLE
Crash in item chart when using drilldown in horizontal/vertical layout

### ISSUE THREAD

**Issue by egraether** [highcharts/highcharts#13372]
#### Expected behaviour
Clicking a data point should update the displayed data to the specified drilldown data, exactly like in the circular layout.

#### Actual behaviour
When clicking a data point for drilldown the data disappears.

#### Live demo with steps to reproduce
https://jsfiddle.net/6sbcwrjq/1/

* Click on any of the data points for drilldown -> crash
* Uncomment the *circular options*
* Try again -> works

#### Product version
Highcharts 8.0.4

#### Affected browser(s)
Chromium

**Comment by sebastianbochan** [comment]
Hi @egraether,
Thank you for reporting about the problem.

_Internal note_
The problem is with missing `shapeArgs`, which also cause the issue here: https://github.com/highcharts/highcharts/issues/13371
