### ISSUE TITLE
Crash in item chart when enabling data labels without setting size

### ISSUE THREAD

**Issue by egraether** [highcharts/highcharts#13371]
#### Expected behaviour
The item chart should not crash and automatically scale to optimally fit chart and data labels (like the pie chart)

#### Actual behaviour
The item chart crashes with: `highcharts.src.js:36896 Uncaught RangeError: Maximum call stack size exceeded`

#### Live demo with steps to reproduce
https://jsfiddle.net/2swtvh1a/

* Crashes when running
* changing the chart type to `pie` fixes the issue
* adding `size` fixes the issue

#### Product version
Highcharts 8.0.4

#### Affected browser(s)
Tested in Chromium and Firefox

**Comment by sebastianbochan** [comment]
Hi @egraether,
Thank you for reporting about the problem.
