### ISSUE TITLE
Issue with axis title is not reading for tool tip 

### ISSUE THREAD

**Issue by v-abkhot** [highcharts/highcharts#13385]
#### Expected behaviour
This is bring to your notice that below bug is been tagged as "By Design" the issue here is "Narrator/NVDA should read about Month and No of shipments details present in the graph" below is the screenshot added for your reference.

#### Actual behaviour
This is bring to your notice that below bug is been tagged as "By Design" the issue here is "Narrator/NVDA is not reading about Month and No of shipments details present in the graph" below is the screenshot added for your reference.

#### Live demo with steps to reproduce

![image](https://user-images.githubusercontent.com/63849538/80444764-262adc00-8930-11ea-934c-8ddd89f2a748.png)

**Comment by v-abkhot** [comment]
when can i expect the updates ?

**Comment by sebastianbochan** [comment]
Hi @v-abkhot,
Thank youfor reporting about the problem. I have passed your case to our a11 developer.

FYI @oysteinmoseng 

ps. please be aware that we are available on support between 10:00 and 18:00 CET, (Central European Time) business days.

**Comment by oysteinmoseng** [comment]
Hi @v-abkhot, are you able to reproduce this in a Codepen/jsFiddle demo? I assume you are loading the accessibility module?

**Comment by v-abkhot** [comment]
yes i have added accessibility module

**Comment by v-abkhot** [comment]
https://codepen.io/pen/?&editable=true=https%3A%2F%2Fwww.highcharts.com%2Fsamples%2Fcodepen%2Fhighcharts%2Fdemo%2Fcolumn-drilldown


this issue is same in demo version as well you can check the same

**Comment by oysteinmoseng** [comment]
Okay, if I understand you correctly, you would like to add the axis title to each data point? You can do this by configuring the [accessibility.point.valueDescriptionFormat](https://api.highcharts.com/highcharts/accessibility.point.valueDescriptionFormat) option. Be aware, however, that most screen reader users will find this overly verbose.

**Comment by v-abkhot** [comment]
can you please give an example ? because i have tried this it is not effective.

**Comment by v-abkhot** [comment]
even on focus to whole graph for NVDA in chrome browser, it is narrating axis but not for each point. and for narrator for edge chromium neither for whole graph focus nor for each point it is narrating axis title

**Comment by oysteinmoseng** [comment]
@v-abkhot Here is an example: https://codepen.io/oysteinmoseng/pen/eYpRVER?editors=0010. 

Let me know if this works for you.

**Comment by v-abkhot** [comment]
yes it works thank you so much for the support

**Comment by oysteinmoseng** [comment]
Great! Closing this issue.
