### ISSUE TITLE
(Highcharts.NET Wrapper) can't set 'crosshair' for axis with boolean value

### ISSUE THREAD

**Issue by Alex-Sokol** [highcharts/highcharts#13381]
**Expected behavior**
Using Highcharts.NET Wrapper should have an ability to set 'crosshair' for an axis in 'true', like in documentation: https://api.highcharts.com/highcharts/xAxis.crosshair and example here: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/crosshair-both/

**Actual behavior**
in Highcharts.NET the class 'XAxis' has only one property 'Crosshair' which is a type of XAxisCrosshair: http://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_x_axis.html#acbcbb37f95fc9b1c24d009f265d46ba0.

So I haven't an ability to set just 'true/false' there.

_Note_: In the previous version of .Net Wrapper (v6.1.0.26) there was a property 'CrosshairBool' for these purposes.

**Product version**
Highcharts .NET Wrapper v8.0.0.3

**Comment by sebastianbochan** [comment]
Hi @Alex-Sokol ,
Thank you for reporting about the problem. Our .NET developer will answer as soon as possible.

**Comment by brofixo** [comment]
Hi, @Alex-Sokol ,
It's a bug. It will be fixed by next week.

**Comment by Alex-Sokol** [comment]
Hi @brofixo ,
Thanks for the answer, waiting for the fix.

**Comment by kutensky** [comment]
@brofixo Are we still expecting for this bug to be fixed soon?

**Comment by brofixo** [comment]
@kutensky, Yes it is going to be release this week.
