### ISSUE TITLE
(Highcharts.NET Wrapper) Can't attach annotation to the point using point id.

### ISSUE THREAD

**Issue by Alex-Sokol** [highcharts/highcharts#13380]
#### Expected behavior
Using Highcharts.NET Wrapper should have an ability to attach an annotation to the point, using point 'id'. Like in the documentation: https://api.highcharts.com/highcharts/annotations.labels.point.

#### Actual behaviour
in Highcharts.NET the class AnnotationsLabels has only one property 'Point' which is a type of AnnotationsLabelsPoint: http://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_annotations_labels.html#ab21c23a578c75246274736a848dbc231.

So I have an ability to set only coordinates for annotation.

Note: In the previous version of .Net Wrapper (v6.1.0.26) there was a property 'PointString' for these purposes.

#### Product version

Highcharts .NET Wrapper v8.0.0.3

**Comment by sebastianbochan** [comment]
Hi @Alex-Sokol ,
Thank you for reporting about the problem. Our .NET developer will answer as soon as possible.

**Comment by brofixo** [comment]
Hi @Alex-Sokol ,
It's a bug. Next release will have fix for this issue.

**Comment by Alex-Sokol** [comment]
Hi @brofixo ,
Thanks for the answer, waiting for the fix.

**Comment by kutensky** [comment]
@brofixo Are we still expecting for this bug to be fixed soon?

**Comment by brofixo** [comment]
@kutensky , it is going to be released this week.
