### ISSUE TITLE
Organization doesn't display all labels properly

### ISSUE THREAD

**Issue by nikhilnediyodath** [highcharts/highcharts#13391]
#### Expected behavior
Should display all labels

#### Actual behaviour
Doesn't shown all labels

#### Live demo with steps to reproduce
https://jsfiddle.net/nikhilnediyodath/Lzf862h5/6/

#### Product version
Highcharts JS v8.0.4 (2020-03-10)

**Comment by sebastianbochan** [comment]
Hi @nikhilnediyodath,
Thank you for reporting. I think that the problem is in your configuration. Lets multiply amount of nodes by declared width (6*200 = 1200px). We need to add paddings etc, so its more than 1000px which you declared.

Could you elaborate how it should look like or attach mockup?

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
