### ISSUE TITLE
x-axis reformats when toggeling legend

### ISSUE THREAD

**Issue by jl-giag** [highcharts/highcharts#13396]
![1-Initial loading](https://user-images.githubusercontent.com/64532036/80591267-ada24900-8a1d-11ea-89e6-cdd8a7e25ba4.png)
![2-After toggeling legend](https://user-images.githubusercontent.com/64532036/80591283-b7c44780-8a1d-11ea-9ffc-2535a2bdf9ee.png)

#### Expected behaviour
x-axis label keeps formatted the same way after hiding and redisplaying series

#### Actual behaviour
format changes and are partially overlapping

#### Live demo with steps to reproduce
// occurs only with certain widths of chart

window.chart = new Highcharts.Chart({

    chart: {
        renderTo: 'container',
    },

    xAxis: {
        labels: {
            formatter: function () {
                return 'veryyyyy long label here';
            },
        },
        crop: true,
        showLastLabel: false,
        type: 'datetime',
    },

    series: [{
        data: [1,2,3,4,5,6,7,8,9,10,11,12],
        type: 'column',
        clip: true,
        showInLegend: true,
        grouping: true
    }]

});

#### Product version
Highcharts 7.2 and 8.0.4

#### Affected browser(s)
Chrome 80, FF 75

**Comment by sebastianbochan** [comment]
Hi @jl-giag,
Thank you for reporting, could you share your live demo by url? Images are helpful but does not allow to debug poperly.

**Comment by jl-giag** [comment]
Hi,

I hope this helps: https://jsfiddle.net/hr4fa679/
Maybe you have to resize the chart part to see the issue.

Kind regards
Jürgen

**Comment by sebastianbochan** [comment]
@jl-giag,
Thank you for demo.

The issue is caused by long words which are not broken by default (in Higcharts and in CSS). You can set the `useHTML` flag and overwrite breaking work/spaces. Please remember about the `width` declaration.

Demo:
- https://jsfiddle.net/BlackLabel/udo6vm1c/

**Comment by jl-giag** [comment]
Hi Sebastian

Thx for your quick reply.

The way you describe solves the overlapping. But as you can see here (https://jsfiddle.net/m2k4y8r6/) there is plenty of room for the labels. And it does not look nice, does it?

The issue I wanted to report is, that the chart displays on initial loading every second label but when hiding and redisplaying the last series, every label is shown with other formatting than before.
IMO the reason is that when the last series is hidden the Y values disappear and the X axis expands for this. After redisplaying the series the charts uses this width for label calculation which is wrong then. The chart should do the computation after the Y values are shown again.

Do you have any better matching solution?

Kind regards
Jürgen

**Comment by jl-giag** [comment]
Hi Sebastian

I know this is not a jsfiddle but here you can see the effect:

[cid:image001.png@01D61F96.EE799830]

[cid:image002.png@01D61F96.EE799830]

[cid:image003.png@01D61F96.EE799830]




From: Jürgen Lotzmann
Sent: Friday, May 1, 2020 7:46 AM
To: 'highcharts/highcharts' <reply@reply.github.com>; highcharts/highcharts <highcharts@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [highcharts/highcharts] x-axis reformats when toggeling legend (#13396)

Hi Sebastian

Thx for your quick reply.

The way you describe solves the overlapping. But as you can see here (https://jsfiddle.net/m2k4y8r6/) there is plenty of room for the labels. And it does not look nice, does it?

The issue I wanted to report is, that the chart displays on initial loading every second label but when hiding and redisplaying the last series, every label is shown with other formatting than before.
IMO the reason is that when the last series is hidden the Y values disappear and the X axis expands for this. After redisplaying the series the charts uses this width for label calculation which is wrong then. The chart should do the computation after the Y values are shown again.

Do you have any better matching solution?

Kind regards
Jürgen

**Comment by sebastianbochan** [comment]
Hi @jl-giag,
Unfortunatley the screenshots are missing. Could you paste all of them again? Without live demo its really difficult to reproduce and debug the issue.

ps. In my demo you can increase the width value in CSS (use the CSS tab and correct width param).

**Comment by jl-giag** [comment]
Hi Sebastian

No problem, here the screenshots again. Pls let me know if you still do not get them.

[cid:image001.png@01D61FA8.CB192D80]

[cid:image002.png@01D61FA8.CB192D80]

[cid:image003.png@01D61FA8.CB192D80]

**Comment by sebastianbochan** [comment]
Still all of them are missing. 

Please contact with us by email: support@highcharts.com and elaborate your case (including screenshot).

If it will be a bug, I will reopen this ticket.
