### ISSUE TITLE
Highstock legend layout 'proximate' makes navigator overlap plotarea

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#13392]
When _legend.layout_ is set to `proximate` in Highstock, the navigator is displayed over the main plot area

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/2etsqk5m/

#### Product version
Highstock 8.0.4

**Comment by sebastianbochan** [comment]
_Internal note_
The problem is that dynamic spacing of rangeselector detects this legend as positioned at the bottom. 

Workaround:
Set the `legend.verticalAlign` as middle.

Demo:
- http://jsfiddle.net/BlackLabel/gjphq2rv/
