### ISSUE TITLE
Inconsistent Axis label on charts for datetime renderings

### ISSUE THREAD

**Issue by clockworked247** [highcharts/highcharts#1340]
The problem occurs only when the data passed to the chart is within a 33 month timespan. Instead of showing tick marks by year, the chart renders by month.

Any data rendering OVER a span of 33 month timespan or less than 12 month timespan shows up as expected.

The expected result would be to show year, rather than month, for points spanning over 12 months.

http://jsfiddle.net/clockworked247/nwPM9/

**Comment by oysteinmoseng** [comment]
This seems to no longer be a relevant issue, with the current label logic.
