### ISSUE TITLE
highcharts fixed point width is not working when one of the serieses is not visible by default

### ISSUE THREAD

**Issue by rammohan201** [highcharts/highcharts#13418]
#### Expected behaviour
bar / point width should 
be always same even after showing and hiding a series
#### Actual behaviour
bars width is not same, middle bar is squeezed.

#### Live demo with steps to reproduce
access the below fiddle and click on series 2 on legend(enabling), observe width of bars, middle bar's width is not same as others. I think highcharts is trying to fit the bars within the available chart width. how can I make sure bars are having equal width without space between them. I have tried with the below options
 pointPadding: 0,
 borderWidth: 0,
 shadow: false,
 pointWidth: 10,

https://jsfiddle.net/rammohanreddy201/mugp32hy/5/

#### Product version
7.x
#### Affected browser(s)
tried with chrome, but is not dependent on browser type

**Comment by sebastianbochan** [comment]
Hi @rammohan201,
Thank you for reporting about the problem. The visible param does not have influence on columns rendering process. As I see without that its also broken.

Demo:
- https://jsfiddle.net/BlackLabel/60bn29wq/

As a workaround you set the [pointRange](https://api.highcharts.com/highcharts/series.column.pointRange) param.

Demo:
- https://jsfiddle.net/BlackLabel/03d1sLgn/
