### ISSUE TITLE
series.keys does not work as expected with TS

### ISSUE THREAD

**Issue by Blackbaud-TylerGreen** [highcharts/highcharts#13412]
#### Expected behaviour
When using the keys attribute in a series, an object can have attributes mapped to the corresponding highchart attributes. 

#### Actual behaviour
When using typescript, this doesn't happen

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series/data-keys/

This can be demonstrated by taking the code in this jsfiddle and using it in your typescript project

#### Product version
Highcharts : 8.0.4

**Comment by sebastianbochan** [comment]
Hi @Blackbaud-TylerGreen,
Thank you for reporting.

FYI @bre1470

**Comment by bre1470** [comment]
@Blackbaud-TylerGreen I do not understand the issue. I used you example in TypeScript and it compiled as expected. So could you elaborate, what you expect to be/happen differently?

**Comment by Blackbaud-TylerGreen** [comment]
huh, weird, when I use the code above in my angular project, I get a blank pie chart. Any chance you could post your code and how you are implementing this?

**Comment by Blackbaud-TylerGreen** [comment]
oh, I see what my problem is!!! I was providing an array of objects for the data, instead of an array of arrays. Is there a way to provide a key to access an attribute of an object in an array of objects? Or do I have to use an array of arrays?

Sorry for the mix up, that's on me!

**Comment by bre1470** [comment]
@Blackbaud-TylerGreen Okay, no problem. Keys is only for arrays of arrays to convert them internally according to the mapping into arrays of objects. If you like to convert arrays of objects, you should make use of `Array.map` before assigning the data into the series options:

```js
{//...
        data: [
        	{
            	browser: 'Firefox',
                share: 45
            },
            {
            	browser: 'Edge',
                share: 26.8
            },
            {
            	browser: 'Chrome',
                share: 12.8,
                highlight: true
            },
            {
            	browser: 'Safari',
                share: 8.5
            },
            {
            	browser: 'Others',
                share: 6.9
            }
        ].map(function (data) {
        	return {
                    name: data.browser,
                     y: data.share,
                     sliced: data.highlight || false,
                     selected: data.highlight || false
                }
        })
}//...
```
https://jsfiddle.net/zm1cdaer/

**Comment by Blackbaud-TylerGreen** [comment]
Thanks! darn, wish there was a way to use an array of objects, oh well. If anyone runs into this thread, I didn't have the data at the time of initializing the pie chart options, so to augment the data beforehand I used `.map( Object.values )` to convert my object array into an array of arrays, here is the full line. `this.pieChartStatusOptions.series[0].data = this.crossFilterStatusDimension.group().all().map( Object.values );`
