### ISSUE TITLE
behaivor of translate function in SVGElement

### ISSUE THREAD

**Issue by Rezakarimi66** [highcharts/highcharts#13416]
#### Expected behaviour
I expect that the translate(x,y) function moves svg by x and y

#### Actual behaviour
It moves svg to x and y!

#### Live demo with steps to reproduce
https://jsfiddle.net/wptkq971/

#### Product version
8.0.4

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @Rezakarimi66,
Thank you for reporting. Let me explain how it works. The arguments (x, y) of `label` define the position, which is set by the `translate()` method. Its by default. 

As a result when you call the `translate(0,0)` the values are overwritten and the label is moved to position.

Solution: 
- extract current `translateX` and `translateY` values and add move which you need.

Demo:
- https://jsfiddle.net/BlackLabel/38t6z27r/

**Comment by Rezakarimi66** [comment]
Thanks for the clarification. It's good to add that example and also update the documentation :)
