### ISSUE TITLE
Shifting multiple series when adding points to chart that updates every second.

### ISSUE THREAD

**Issue by jamilwalker** [highcharts/highcharts#1342]
Hi,

This is related to issue #1325 but not the same. This issue should probably be tagged as an enhancement.

Shifting a series when you add point to a single series chart works great. The demo (http://www.highcharts.com/demo/dynamic-update) provides a good example. But is it possible to shift more than one series? I have created a jsFiddle to demonstrate my issue:

http://jsfiddle.net/bRp6h/2/

Usage error:

User clicks start/stop button to get data reading. Each start creates a new reading (series). The range that the chart displays is 10 seconds (60 points). After 10 seconds the data should shift off the chart. It works fine with one series but doesn't work if the user has started/stopped multiple times (creating more than one series). The 60 points only refers to the current series so only the current series gets shifted and your left with orphan series on the chart.

**Comment by vickychijwani** [comment]
@highslide-software I have this use-case too. I hope setting a fixed range on the X axis doesn't leak memory because we didn't explicitly shift / remove the points that are vanishing off the left edge?

**Comment by highslide-software** [comment]
It will build up memory, so I recommend you run Point.remove() on those points to the left of the axis minium programmatically. Just loop up series.points and look at the X value of each point.
