### ISSUE TITLE
Downloaded zip file doesn't contain all files

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#13438]
After downloading Highmaps 8.0.4 zip file from https://www.highcharts.com/blog/download/ I go to the `/examples/all-maps/` folder and open `index.html` file - the error is thrown to the console that  
`/Highmaps-8.0.4/code/mapdata/index.js` file is not found.

The line responsible for this:

```
<script src="../../code/mapdata/index.js?1"></script>
```

That local demo (index.html) is a mirror of https://www.highcharts.com/maps/demo/all-maps but locally maps are not accessible.

#### Product version

Highmaps 8.0.4 (issue still occurs in 8.1.0)

**Comment by KacperMadej** [comment]
@TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
Actually I cannot find the `code/mapdata` folder at all. I don't think we ever shipped the mapdata with the zip. This is the contents of `Highmaps 8.0.4.zip`:

![Skjermbilde 2020-05-19 kl  10 02 46](https://user-images.githubusercontent.com/227836/82301005-ec417880-99b7-11ea-907e-b63cf7677913.png)

Also, going back to for example v5.0, shows no mapdata in the zip file.

**Comment by raf18seb** [comment]
@TorsteinHonsi Sorry, I made a mistake in the main description above. I edited it.
