### ISSUE TITLE
Highstock- errors in console when adding new series to chart with no data

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#13437]
#### Expected behaviour
Add series without errors

#### Actual behaviour
Errors in console
`Error: <rect> attribute width: Expected length, "NaN".`

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/qa1vyhz9/

#### Product version
Highstock 8.0.4

#### Affected browser(s)
All

**Comment by maddy25** [comment]
What should we do for now? Was working on updating our highcharts version for 6 to latest (8.1.2). Is there a more stable version that can be used?

**Comment by pawelfus** [comment]
v8.1.2 is the most recent, stable version. Last version without bug: v8.0.0

**Workaround (v8.0.1+):**
Demo: http://jsfiddle.net/BlackLabel/74m9sf8c/
Plugin:
```js
(function(H) {
  H.wrap(
    H.Navigator.prototype,
    'drawMasks',
    function(proceed, zoomedMin, zoomedMax) {
      if (!H.isNumber(zoomedMin) || !H.isNumber(zoomedMax)) {
        return;
      }
      proceed.apply(this, Array.prototype.slice.call(arguments, 1))
    }
  );
})(Highcharts);
```

*Internal note:*
Bisect and find out why it's a regression. `zoomedMax` and `zoomedMin` shouldn't be NaN in the first place.

**Comment by maddy25** [comment]
I got the above error for 8.1.2 version as well

**Comment by maddy25** [comment]
Also the zoom seems to be not working. Have created a separate ticket for that. https://github.com/highcharts/highcharts/issues/13774

**Comment by pawelfus** [comment]
Zooming is fine, see my answer in #13774

I said that last working version is v8.0.0, it's broken since v8.0.1, including v8.1.2.

**Comment by maddy25** [comment]
Property 'Navigator' does not exist on type 'typeof when I use the plugin above. Plz note I am using highcharts with Angular 8.

**Comment by pawelfus** [comment]
Please make sure that you use my plugin after loading Highcharts, for example:
```js
import Highcharts from 'highcharts';

import Exporting from 'highcharts/modules/exporting';
// Initialize exporting module. (CommonJS only)
Exporting(Highcharts);

(function(H) {
  H.wrap(
    H.Navigator.prototype,
    'drawMasks',
    function(proceed, zoomedMin, zoomedMax) {
      if (!H.isNumber(zoomedMin) || !H.isNumber(zoomedMax)) {
        return;
      }
      proceed.apply(this, Array.prototype.slice.call(arguments, 1))
    }
  );
})(Highcharts);
```

**Comment by maddy25** [comment]
Yes I am using the plugin after loading highcharts.

**Comment by pawelfus** [comment]
Could you share your imports? Thanks

**Comment by maddy25** [comment]
import * as Highcharts from 'highcharts/highstock';
declare var require: any;
require('highcharts/modules/annotations')(Highcharts);
require('highcharts/highcharts-more')(Highcharts);
require('highcharts/modules/data')(Highcharts);
require('highcharts/modules/drilldown')(Highcharts);
require('highcharts/modules/exporting')(Highcharts);
require('highcharts/modules/funnel')(Highcharts);
require('highcharts/modules/heatmap')(Highcharts);
require('highcharts/modules/histogram-bellcurve')(Highcharts);
require('highcharts/modules/offline-exporting')(Highcharts);
require('highcharts/modules/parallel-coordinates')(Highcharts);
require('highcharts/modules/pareto')(Highcharts);
require('highcharts/modules/boost')(Highcharts);
(function(H) {
    H.wrap(
        H.Navigator.prototype,
        'drawMasks',
        function(proceed, zoomedMin, zoomedMax) {
            if (!H.isNumber(zoomedMin) || !H.isNumber(zoomedMax)) {
                return;
            }
            proceed.apply(this, Array.prototype.slice.call(arguments, 1))
        }
    );
})(Highcharts);

**Comment by pawelfus** [comment]
Thanks! This looks good. Is that your error perhaps generated by TS ? Note that in my workaround you might need to place `as any` in some places, for example: `H.Navigator.prototype` -> `(H as any).Navigator.prototype`.

**Comment by Izothep** [comment]
Bisected to https://github.com/highcharts/highcharts/commit/6ded81e009a29096675278bf312045a736de4402

**Internal Note**:
It looks that the solution is to add check for `zoomedMin`/`zoomedMax` in `if` statement added in above commit.
