### ISSUE TITLE
Highcharts map zoom buttons create invalid html

### ISSUE THREAD

**Issue by guceda** [highcharts/highcharts#13436]
#### Expected behaviour
It returns the right value for the style and states attribute of the highcharts zoom buttons

#### Actual behaviour
The element it generates has a [object, Object] value for both style and states
_`<g class="highcharts-button highcharts-map-navigation highcharts-zoom-in    highcharts-button-normal" states="[object Object]" style="[object Object]" data-z-index="5" transform="translate(10,429)">`_

#### Live demo with steps to reproduce
https://jsfiddle.net/mrx7u24h/
1. Load de jsfiddle.
2. Open the inspector
3. Select the **zoom in** or **zoom out** button in the map and check the inspector.
#### Product version
Highcharts 8.0.4

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @guceda,
Thank you for reporting about the problem.

**Comment by guceda** [comment]
@sebastianbochan you're very welcome!

**Comment by khlieng** [comment]
Fixed on master.
