### ISSUE TITLE
Highmaps: Error when calling chart.events.load and series.point.events.click

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#13445]
#### Expected behaviour
Correct operation of click and load events, no errors in the console.

#### Actual behaviour
When we update the chart using chart.events.load and then use series.point.events.click we get the following error in the console:
`Uncaught RangeError: Maximum call stack size exceeded`

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/xw5sorba/

#### Possible workaround
Calling click on series.events.click:
https://jsfiddle.net/BlackLabel/5gaj7e8d/

#### Product version
v8.1.0

**Comment by madepiet** [comment]
According to the documentation, both options should work correctly, but in this case, an error occurs when we set series.point.events.click:
https://api.highcharts.com/highmaps/plotOptions.series.point.events.click
https://api.highcharts.com/highmaps/plotOptions.series.events.click

**Comment by khlieng** [comment]
Fixed on master.
