### ISSUE TITLE
 Running drill down with the preventDefault causes seriesOptions = undefined

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13448]
#### Expected behaviour
`seriesOptions` shouldn't be undefined

#### Actual behaviour
It seems that because of the `preventDefault()` the `chart.ddDupes` array will not be cleared up so that `seriesOptions` will always be undefined.
 ```
Point.prototype.doDrilldown = function (_holdRedraw, category, originalEvent) {
            var series = this.series, chart = series.chart, drilldown = chart.options.drilldown, i = (drilldown.series || []).length, seriesOptions;
            if (!chart.ddDupes) {
                chart.ddDupes = [];
            }
            while (i-- && !seriesOptions) {
                if (drilldown.series[i].id === this.drilldown &&
                    chart.ddDupes.indexOf(this.drilldown) === -1) {
                    seriesOptions = drilldown.series[i];
                    chart.ddDupes.push(this.drilldown);
                }
            }
(...)
```
#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/12qz0sue/
1. click blue column,
2. click blue column again,
3. check console for two entries: seriesOptions and undefined - both from the clicks, both from e.seriesOptions in drilldown event

#### Workaround
Manually reset the `chart.ddDupes`
https://jsfiddle.net/BlackLabel/j5sqvp7m/
```
drilldown:  function (e) {
                	e.preventDefault();
                  console.log(e.seriesOptions);
                  this.ddDupes.length = 0;
                return true;
              }
```

#### Product version
Highcharts JS v8.1.0 (2020-05-05)

#### Affected browser(s)
All

**Comment by p-himik** [comment]
Just stumbled upon this as well, only with Highcharts 12.6.0.
