### ISSUE TITLE
Shadow improperly rendered

### ISSUE THREAD

**Issue by Corbeau3000** [highcharts/highcharts#1345]
In Internet Explorer 7 and 8 the shadow is not always properly rendered when there is stacked columns.

I made the following example :
http://jsfiddle.net/Corbeau3000/dEkSg/2/

The first and third column have too much shadow on top but the second column is ok.

**Comment by cvasseng** [comment]
Hi! We're doing a bit of spring cleaning, and closing old issues. If you're still experiencing issues with this, please feel free to open a new issue! Thanks!
