### ISSUE TITLE
Issues related to documentation

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [highcharts/highcharts#13462]
Hi Team,

I have a short query regarding the documentation of different HighChart versions.
Can you please provide link for version 7.2.1

**Comment by sebastianbochan** [comment]
Hi @aditya-padhi-kbl,
Thank you for suggestion. Since HC8+ the api is available in the zip package http://code.highcharts.com/zips/Highcharts-8.0.0.zip  where 8.0.0 is version of Highcharts.
