### ISSUE TITLE
Focus issue in high-contrast mode

### ISSUE THREAD

**Issue by v-abkhot** [highcharts/highcharts#13464]
#### Expected behaviour
In column highchart focus on column in high-contrast mode should be linear or sequential.

#### Actual behaviour
In column highchart focus on column in high-contrast mode getting alternate column focus 

#### Live demo with steps to reproduce

1st column focus.
![image](https://user-images.githubusercontent.com/63849538/81372139-3eacaa80-9117-11ea-9857-0fcce7e5e5f2.png)
 after tab or arrow 
![image](https://user-images.githubusercontent.com/63849538/81372195-613ec380-9117-11ea-955b-82fc18c5d6b2.png)

**Comment by sebastianbochan** [comment]
Hi @v-abkhot,
Thank you for reporting about the problem.

FYI @oysteinmoseng

**Comment by v-abkhot** [comment]
any inputs for this ?

**Comment by oysteinmoseng** [comment]
I am not sure if this is a Highcharts issue, high contrast mode should not affect keyboard navigation at all. There currently appear to be some issues with high contrast mode in Edge with SVGs.

We will take a look at what is happening and report back.

**Comment by v-abkhot** [comment]
thank you for your inputs

**Comment by oysteinmoseng** [comment]
@v-abkhot This is a browser bug with Edge, it seems. For every keyboard arrow click, we are getting two keydown events.
