### ISSUE TITLE
stackLabels position has changed

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#13467]
Hello.

Thank you for your library.

In version 6.2 stackLabels was above columns. But now (v. 8.1) stackLabels on the solumns

#### Expected behaviour
stackLabels above columns
![image](https://user-images.githubusercontent.com/6030335/81386322-80d8ea80-911d-11ea-8d83-7057dffeac18.png)

#### Actual behaviour
stackLabels on the column
![image](https://user-images.githubusercontent.com/6030335/81386377-9221f700-911d-11ea-846a-a8b3dc46a830.png)

#### Live demo with steps to reproduce
8.1
https://jsfiddle.net/neyqxvot/
6.2
https://jsfiddle.net/unserg5z/

#### Product version
Highcharts 8.1

#### Affected browser(s)
Google chrome 81.0.4044.129

**Comment by pawelfus** [comment]
Hi @balkarov 

Thanks for reporting. This is expected behaviour. Since ~7.1.3 you can control this behaviour by setting `overflow` and `crop` options, just like in `dataLabels`. See: https://jsfiddle.net/BlackLabel/cyjbz85r/

**Comment by balkarov** [comment]
@pawelfus thank you.
