### ISSUE TITLE
Axis labels formatted differently with multiple axes

### ISSUE THREAD

**Issue by Katona** [highcharts/highcharts#13465]
#### Expected behaviour
Axis label formatting should be independent of the number of axes. Ideally, I would expect labels to be skipped so that they can be displayed without truncating or wrapping.

#### Actual behaviour
Labels are formatted differently if there are multiple y-axes: with one axis, they are rotated to avoid overlapping. with two axes they are wrapped.

#### Live demo with steps to reproduce
https://jsfiddle.net/ut0jdpf3/2/
Note that there are two charts in the fiddle to demonstrate the difference: one with two y-axes and another with one axis.

#### Product version
Highcharts 8.1.0.

**Comment by pawelfus** [comment]
Hi @Katona 

Thank you for reporting the issue. This is expected behaviour to prevent overlapping labels. You can disable all options (rotation, word-wrapping, ellipsis etc), demo: https://jsfiddle.net/BlackLabel/cvn2sqde/ and labels will start to overlap. I suggest to increase `tickPixelInterval` in this case: https://jsfiddle.net/BlackLabel/ervxjkyL/

**Comment by Katona** [comment]
Hi @pawelfus,

Thanks for the response. Isn't there an option which resulted in automatically skipping labels if they would overlap each other?

Thanks,
Gabor

**Comment by sebastianbochan** [comment]
Hi @Katona,
Could you elaborate your question? By default overlapped labels are missing, if you need to display all of them, you can use options described by @pawelfus.

**Comment by pawelfus** [comment]
No, there's no option (`allowOverlap`) like for `stackLabels` or `dataLabels`.

Implementation idea: https://jsfiddle.net/BlackLabel/Lh7sqz9k/

Plugin:
```js
(function(H) {

  H.addEvent(
    H.Chart,
    'afterInit',
    function() {
      const chart = this;

      this.labelCollectors.push(
        function() {
          const coll = [];

          chart.yAxis.forEach(axis => {
            axis.tickPositions.forEach(tick => {
              if (axis.ticks[tick] && axis.ticks[tick].label) {
                coll.push(axis.ticks[tick].label);
              }
            })
          });
          return coll;
        }
      );
    }
  );
})(Highcharts);
```

**Comment by Katona** [comment]
Hi @pawelfus,

Thanks for the tip, it seems to be doing exactly what I need. Can you please elaborate a little bit how it works?

Thanks,
Gabor

**Comment by pawelfus** [comment]
Sure, @Katona:
- [`addEvent()`](https://api.highcharts.com/class-reference/Highcharts#.addEvent%3CT%3E) docs
- [`afterInit`](https://api.highcharts.com/class-reference/Highcharts.Chart#init) callback reference:
- Highcharts has internal, build-in system of `labelCollectors` (not part of API), which gathers callbacks that should return array of `SVGElement`s (can be created via [`Renderer.label()`](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#label))
- leveraging that Axis labels are created as `label`, we collect them and let the core hide overlapping labels
- Axis ticks references:
  - [tickPositions](https://api.highcharts.com/class-reference/Highcharts.Axis#tickPositions)
  - [ticks](https://api.highcharts.com/class-reference/Highcharts.Axis#ticks)
  - [ticks[tickPosition].label](https://api.highcharts.com/class-reference/Highcharts.Tick.html#label)

**Comment by Katona** [comment]
Excellent, thanks @pawelfus!

**Comment by Katona** [comment]
Hi @pawelfus,

Sorry for reopening, only for one question: it seems the solution breaks if the chart uses different font (we happen to use `Calibri`): https://jsfiddle.net/d4ge7o5x/. If the chart is resized the axis labels occasionally overlap each other, which doesn't happen if the font is not specified. Do you have any idea why, and if there is any fix?

Thanks,
Gabor

![image](https://user-images.githubusercontent.com/1146931/81713722-85333980-9476-11ea-9e81-f023f6c178bd.png)

**Comment by pawelfus** [comment]
I don't know why it happens, but we can fix it (but the solution may decrease the performance): 
```js
(function(H) {

  H.addEvent(
    H.Chart,
    'afterInit',
    function() {
      const chart = this;

      this.labelCollectors.push(
        function() {
          const coll = [];

          chart.yAxis.forEach(axis => {
            (axis.tickPositions || []).forEach(tick => {
              if (axis.ticks[tick] && axis.ticks[tick].label) {
                coll.push(axis.ticks[tick].label);
              }
            })
          });
          return coll;
        }
      );
    }
  );

  H.addEvent(
    H.Chart,
    'endResize',
    function() {
      var labels = [];

      (this.labelCollectors || []).forEach(function(collector) {
        labels = labels.concat(collector());
      });

      this.hideOverlappingLabels(labels);
    }
  )
})(Highcharts);
```

Demo: https://jsfiddle.net/BlackLabel/cLv7sfea/

**Comment by Katona** [comment]
Hi @pawelfus,

It still has some issues with our config. At the very least can we enable the autorotation function somehow? That doesn't seem to work either: https://jsfiddle.net/51xe3hk0/

**Comment by pawelfus** [comment]
It seems that `chart.alignTicks` is the culprit here, when disabled works fine: https://jsfiddle.net/BlackLabel/bh69mzw2/ (apart from ticks being aligned). 

Thanks for pointing this out! If you don't mind I will create a separate issue for that, because the original issue here is not a bug: different number of axes may result in different labels. New issue: #13550

**Comment by Katona** [comment]
Ok, thanks for the help!
