### ISSUE TITLE
TypeScript error for numeric series data set

### ISSUE THREAD

**Issue by Ky6uk** [highcharts/highcharts#13460]
#### Expected behaviour

TypeScript doesn't raise an error for code

```ts
HighCharts.chart({
  series: [{
    data: [0, 1, 2]
  }]
});
```

#### Actual behaviour

TypeScript doesn't compile the code with error:

`Type 'number' has no properties in common with type 'XrangePointOptionsObject'`

<img width="795" alt="Screenshot 2020-05-07 at 18 42 36" src="https://user-images.githubusercontent.com/46930/81315082-8806e680-9092-11ea-81da-24a6fbddc928.png">

#### Product version

Highcharts: 8.1.0
TypeScript 3.8.3

[Codesandbox link](https://codesandbox.io/s/agitated-lederberg-fy9kz?file=/src/index.ts)

**Comment by sebastianbochan** [comment]
Hi @Ky6uk,
Thank you for reporting about the problem.

FYI @bre1470

**Comment by bre1470** [comment]
Hello @Ky6uk 
You have to define the series `type` in the series options as mentioned in the documentation, otherwise TypeScript is not able to validate the options: https://api.highcharts.com/highcharts/series.line
