### ISSUE TITLE
Focus issue in graph on export menu

### ISSUE THREAD

**Issue by v-abkhot** [highcharts/highcharts#13463]
#### Expected behaviour
In column chart when focus is on export menu on click enter, menu gets expanded. When press escape focus should stay at export menu only 

#### Actual behaviour
In column chart when focus is on export menu on click enter, menu gets expanded. When press escape focus goes to back to the last column.

#### Live demo with steps to reproduce

![image](https://user-images.githubusercontent.com/63849538/81370985-3dc64980-9114-11ea-9451-cb8c43e1cb4c.png)
after press escape 
![image](https://user-images.githubusercontent.com/63849538/81371041-62babc80-9114-11ea-89f5-d65538d8d8e6.png)

**Comment by sebastianbochan** [comment]
Hi @v-abkhot,
Thank you for reporting about the problem.

FYI @oysteinmoseng

**Comment by v-abkhot** [comment]
so this bug can we expect in next release ?

**Comment by sebastianbochan** [comment]
Hi @v-abkhot,
At this moment we do not have an ETA for fixing this issue.

**Comment by oysteinmoseng** [comment]
@v-abkhot I have looked into the issue, it should be part of the next release.

**Comment by SreejaPampara** [comment]
could you please let us Know the version in which this bug can be fixed, as it still seems to be reproducing in the web page
