### ISSUE TITLE
chart.xAxis[0].isDatetimeAxis is undefiend in 8.1 vs 8.0.4

### ISSUE THREAD

**Issue by smokir** [highcharts/highcharts#13461]
Callback function `(chart) => console.log(chart.xAxis[0].isDatetimeAxis)` shows `undefined` in console instead of `true` after upgrading HC to 8.1 from 8.0.4. Is it expected behaviour? Didn't find such info in [8.1.0 changelog](https://www.highcharts.com/blog/changelog/#highcharts-v8.1.0)

<img width="1064" alt="Снимок экрана 2020-05-07 в 19 34 15" src="https://user-images.githubusercontent.com/2204174/81320385-c7850100-9099-11ea-8657-866b5d368e2a.png">

#### Live demo with steps to reproduce

https://jsfiddle.net/thr52aw7/

#### Product version

Highcharts 8.1.0

**Comment by TorsteinHonsi** [comment]
It is (loosely) covered by this bullet point under "Upgrade notes": 
> The Axis class was refactored as part of the TypeScript migration. Axis extensions like log axis, broken axis, parallel axis, datetime axis and ordinal axis are now handled as compositions. Instead of adding multiple properties to the main axis instance, they now add a single object that holds all properties. This does not affect the options API, but it may affect implementations that are based on some of our samples that used the original properties. Our samples have been updated to use the new structure.

The equivalent test can now be done by checking for the `Axis.dateTime` composition: https://jsfiddle.net/highcharts/wm74eb0k/ .

**Comment by pedroteixeira** [comment]
Backwards compatibility on this property seems to be a good idea

**Comment by pawelfus** [comment]
Instead of checking internal property, I would suggest to test `x/yAxis.options.type === "datetime"`. This is safe as it depends on options directly.
