### ISSUE TITLE
disappearing column/bar when scrolling beyond point value

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13473]
#### Expected behaviour
All points should be visible after scrolling.

#### Actual behaviour
When you scroll out the chart so the first point will be outside of the scroll area it will disappear after scrolling back.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/x40da2gq/
Steps: 
1/ Scroll fully to the right, 
2/ Return to the starting position
3/ The first point won't be visible anymore

#### Workaround
After setting the min value everything is working correctly:
https://jsfiddle.net/BlackLabel/tz69qwa1/

#### Product version
8.1.0

#### Affected browser(s)
All

**Comment by Mani2693** [comment]
@mateuszkornecki  Do we have any workaround for this issue ? 

Thanks 
Manigandan

**Comment by pawelfus** [comment]
Hi @Mani2693 

You can find the workaround in the post above: 
> After setting the min value everything is working correctly:
https://jsfiddle.net/BlackLabel/tz69qwa1/
