### ISSUE TITLE
issue with view in full screen option in export menu

### ISSUE THREAD

**Issue by v-abkhot** [highcharts/highcharts#13470]
#### Expected behaviour
click on export menu -> click on View full screen then press escape from full screen. it should fit in existing dimensions. container height should not change.

#### Actual behaviour
click on export menu -> click on View full screen then press escape from full screen. it should fit in existing dimensions. container height is getting changed.

#### Live demo with steps to reproduce

![image](https://user-images.githubusercontent.com/63849538/81396152-7d0b8f00-9142-11ea-9f7b-c16caae1ccde.png)

after clicking view full screen. and exiting from full screen 

![image](https://user-images.githubusercontent.com/63849538/81396291-c065fd80-9142-11ea-8a12-6e82d73f262f.png)

height is getting changed

**Comment by sebastianbochan** [comment]
Hi @v-abkhot,
Thank you for reporting. The issue has been already reported here: https://github.com/highcharts/highcharts/issues/13222.

Im closing as duplicate.

**Comment by v-abkhot** [comment]
Hi team i have applied changes as per your recommendations but the still issue is there ... issue with the SVG height not the container height.
![image](https://user-images.githubusercontent.com/63849538/81778771-11923a80-9511-11ea-8f11-3f09b14e19c5.png)
please refer the attachment for the problem

**Comment by v-abkhot** [comment]
so please give some input on this

**Comment by sebastianbochan** [comment]
Hi @v-abkhot,
Please keep all comments in the single thread (#13222), including live demo of your case. As a result we will keep the consistency.
