### ISSUE TITLE
"areaspline" series animation bug

### ISSUE THREAD

**Issue by Ky6uk** [highcharts/highcharts#13475]
#### Expected behaviour

Chart with type `areaspline` has an animated transition when data in the series is changed.

#### Actual behaviour

Chart with type `areaspline` doesn't have transition animation if new data in series contains less amount of items than before. From less to more items, it works.

#### Live demo with steps to reproduce

https://jsfiddle.net/jvauq94n/

#### Product version

8.1.0

**Comment by Ky6uk** [comment]
Hmm, it looks the type of chart isn't important.

**Comment by pawelfus** [comment]
Thanks for reporting the issue @Ky6uk 

Not related to the issue itself, but we recommend to use matching ID's for points, so for example column series will animate properly: https://jsfiddle.net/BlackLabel/ydt05eLw/

*Internal note:*
This is bug in renderer animation. Demo, not related to series type: https://jsfiddle.net/BlackLabel/bvprjLd6/ Most likely, we need to implement this case in `Fx.prototype.initPath`
