### ISSUE TITLE
axis range is unnecessarily larger than minRange

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#13485]
Example:

https://jsfiddle.net/rnk4sq65/

When setting a `minRange` of `250` (as above), the y axis is given a range of `0-300` when it could be given a range of `0-250`.  This always seems to be the case: one full extra tick interval is added, when it needn't be.

**Comment by sebastianbochan** [comment]
Hi @drmrbrewer,
Thank you for reporting. The round of value is related with default `minPadding` and `maxPadding` params. Moreover you can control start and end on tick.

When you reset all options you will resolve your problem.

Demo:
- https://jsfiddle.net/hLptcfsj/

I would not consider it as a bug.

**Comment by drmrbrewer** [comment]
@sebastianbochan but with your example the range is still `300` (from `-50` to `250`) despite setting `minRange` to `250`.  Even with `startOnTick` and `endOnTick` both set to `true` (which is the effect I want), it should easily be possible to set the axis range to `0 to 250` shouldn't it?

**Comment by pawelfus** [comment]
Hi @drmrbrewer 

`minRange` is applied before options like `maxPadding` or `endOnTicks`. This is the example where `minRange` is exactly as set: https://jsfiddle.net/BlackLabel/zerkLb8m/ - open console and see the results.

It's explained here: https://api.highcharts.com/highcharts/yAxis.minRange

> Note that the `minPadding`, `maxPadding`, `startOnTick` and `endOnTick` settings also affect how the extremes of the axis are computed.

**Comment by drmrbrewer** [comment]
@pawelfus I'm not sure how HC comes to the conclusion that the axis min should be

**Comment by drmrbrewer** [comment]
@pawelfus I guess it just looks like the wrong end result, no matter how the result is arrived at.  In this case, most people looking at the data and the `minRange` requirement would simply say "well it's obvious that, to satisfy all requirements, the range should be from 0 to 250".  that is all requirements, including `minRange`, `minPadding`, `maxPadding`, `startOnTick` and `endOnTick`... nothing is left out.  Maybe there is a better way of determining how `minRange` is applied?

**Comment by pawelfus** [comment]
> So maybe there is a different way of determining how minRange is applied so that it works better in situations like this?

Perhaps there is, it's hard to say, given how that should would interfere will all other options. Changing how `minRange` works will break/change every existing chart (because `minRange` is by default, used in every chart) that was created until now. Maybe we can consider introducing this change in major versions (e.g. v9), but only if this ticket will get enough other users attention, or we receive similar feedback through other support channels.

Just to be on the same page: `minRange` works just as described. Setting `minRange = 250` does not mean that the range will be **exactly 250**, but it means that range will not go below **250**, and, to be mathematically correct, <-50, 250>, or <0, 300> ranges do fulfill the statement of range higher than 250 (range=300).

That being said, I understand, that just thinking about option `minRange`, users may think "I have values 20-50, setting to 250 will show range of <0, 250>" and the result might be a bit misleading, but still, `minRange` has detailed explanation in API.

PS: You still can use `tickPositioner` like this:
```js
tickPositioner: function (min, max) {
  if (Math.abs(this.max - this.min) < 250) {
   return [this.tickPositions[0], this.tickPositions[0] + 250];
  } else {
    return this.tickPositions;
  }
}
```

**Comment by drmrbrewer** [comment]
> Setting `minRange = 250` does not mean that the range will be **exactly 250**, but it means that range will not go below **250**, and, to be mathematically correct, <-50, 250>, or <0, 300> ranges do fulfill the statement of range higher than 250 (range=300).

Yes but using the same logic, highcharts could also fulfil the request for a min range of `R` by giving the axis a range of `10R`... strictly speaking it satisfies the user's request but it is still not what the user expects.

> That being said, I understand, that just thinking about option `minRange`, users may think "I have values 20-50, setting to 250 will show range of <0, 250>" and the result might be a bit misleading

I'd say that users wouldn't expect a range of `0` to `250`, but maybe a range of `-90` to `160`, i.e. still centred around the actual data... but I guess that the threshold also comes into play and maybe this requires `softThreshold` set to `true`.

> PS: You still can use tickPositioner

Thanks for the suggestion... maybe that's the way to go to get what I want... I'm just hopig to avoid manual customisation where possible because I know that in most cases highcharts does things a lot better than I ever could (and it will be improved over time, while my manual overrides languish and gather dust).  

> only if this ticket will get enough other users attention

Maybe this ticket won't get much attention because most users won't be paying sufficient attention to these details, or it won't be critical in their use case.  However, I truly believe that the default behaviour could and should be closer to what the user expects (if they pay attention to detail).

**Comment by pawelfus** [comment]
> (...) but I guess that the threshold also comes into play and maybe this requires `softThreshold` set to true.

Exactly, and that's just another option that might change the result of `minRange`. Other possibilities are: `softThreshold`, `softMin`, `softMax`, `ceiling`, `floor`, `maxPadding`, `minPadding`, `startOnTick`, `endOnTick`, `tickInterval`, `tickPixelInterval`, `alignTicks`, `min`, `max`, `minTickInterval`, `tickAmount`, `units`, `pointRange`, `series.type` (e.g. bubble series with it's markers, column series with it's paddings..), `series.threshold`, linked axes and probably a few more, that I don't remember right now.

> I'm just hoping to avoid manual customisation where possible because I know that in most cases highcharts does things a lot better than I ever could (and it will be improved over time, while my manual overrides languish and gather dust).

Thanks! We try really hard to render the best possible chart for the given data, with the minimal configuration.
