### ISSUE TITLE
Error when printing chart from export menu when highcharts-more module is loaded

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#13489]
#### Expected behaviour
No exception is thrown, print dialog is opened.

#### Actual behaviour
>Uncaught TypeError: Cannot read property 'forEach' of undefined
    at H.Chart.<anonymous> (highcharts-more.src.js:8178)
    at fireInOrder (highcharts.src.js:1420)

`this.graphLayoutsLookup` safely accessed previously in the file, but not in these listeners:
https://github.com/highcharts/highcharts/blob/91aec3b102384bed1c833cf99a53e90516e367d1/ts/modules/networkgraph/layouts.ts#L933-L951

#### Live demo with steps to reproduce
https://jsfiddle.net/alvarezg/z69tk31b/

1. Open exporting menu
1. Click "Print chart"

(Can also be reproduced by calling `chart.print()`)

#### Product version
Highcharts and Highstock 8.1.0

**Comment by sebastianbochan** [comment]
Hi @alvarezguille,
Thank you for reporting.

FYI @Izothep

**Comment by Izothep** [comment]
Thanks @alvarezguille! I will look on it right away.

**Comment by alvarezguille** [comment]
Thanks for quick response 🎉

**Comment by nickelaos** [comment]
I am facing the same issue. What should I do?
![image](https://user-images.githubusercontent.com/21063721/82803166-b9e8bd00-9e88-11ea-8daa-03ce4bb0379e.png)

**Comment by Izothep** [comment]
Hi @nickelaos,

Thank you for report. The issue is already solved on our GitHub Master branch so it should be possible to use this branch until the next Highcharts version will be released:
https://jsfiddle.net/BlackLabel/o95vym1x/

**Comment by nickelaos** [comment]
@Izothep Thank you for the reply. It helps. I just wondering if there is a risk to brake something after the update. Can I replace 
<script src="https://code.highcharts.com/highcharts.js"></script>
with
<script src="https://github.highcharts.com/highcharts.js"></script>
safely?

**Comment by pawelfus** [comment]
Sorry for the late response @nickelaos !

Our `github.highcharts.com` serves auto-tested candidate for the next release. This scripts may accidentally break something, so we discourage to use it in production. For development, or when testing new features - it should be okay to use it.

The next release should be ready this week, but for anyone who uses v8.1.0, temporary workaround:
```js
Highcharts.Chart.prototype.graphLayoutsLookup = [];
```

Demo: https://jsfiddle.net/BlackLabel/w9yxkbo1/
