### ISSUE TITLE
Markers can't be disabled on styled mode when accessibility module is loaded

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#13482]
#### Expected behaviour
Initial setting or update of marker.enabled to false should hide markers.

#### Actual behaviour
Only marker from legend is disabled, markers in data series are still show.

#### Live demo with steps to reproduce
https://jsfiddle.net/alvarezg/42e35c86/

#### Product version
Highcharts and Highstock 7.1.2 or later

**Comment by sebastianbochan** [comment]
Hi @alvarezguille,
Thank you for reporting. 

FYI @oysteinmoseng

**Comment by TorsteinHonsi** [comment]
As @oysteinmoseng mentioned in the PR, I agree this fix is quick and effective, but perhaps not a permanent solution. The better approach would probably be to add a class name to the marker group (`.highcharts-markers-hidden` for example) and add that to the default CSS.

```
.highcharts-markers-hidden .highcharts-point:not(.highcharts-point-hover) {
    display: none;
}
```

### Workaround for v8.1.0
Add that CSS to the `.highcharts-markers` group:
https://jsfiddle.net/highcharts/f1jxt98v/

**Comment by oysteinmoseng** [comment]
Note: For better a11y use `opacity: 0` instead of `display: none`.
