### ISSUE TITLE
ColorAxis is always added on chart when loaded and present in theme, regardless of Series type

### ISSUE THREAD

**Issue by egraether** [highcharts/highcharts#13493]
#### Expected behaviour
A ColorAxis should only be added to the chart when specified.

#### Actual behaviour
A ColorAxis is always added when node module `highchartsHeatMap` is used, regardless of the used Series type. It adds extra text nodes to the top left corner and changes color mapping.

#### Live demo with steps to reproduce
I was not able to reproduce this on JSFiddle (see **context** below).
**Edit:** Issue caused by `theme`, sample here: http://jsfiddle.net/hdLf394o/

![Screenshot from 2020-05-13 11-41-03](https://user-images.githubusercontent.com/201867/81798511-6a150800-9510-11ea-8568-b8776fe826b4.png)

#### Product version
8.1.0

#### Affected browser(s)
Tested in Chromium

#### Context

We are working on upgrading from Highcharts `7.0.3` to `8.1.0`.
We are using `node`, `React`, `highcharts-react-official` and lots of modules:
```
import highchartsMore from 'highcharts/highcharts-more'
import highchartsBoost from 'highcharts/modules/boost'
import highchartsHeatMap from 'highcharts/modules/heatmap'
import highchartsTreemap from 'highcharts/modules/treemap'
import highchartsDrilldown from 'highcharts/modules/drilldown'
import highchartsExporting from 'highcharts/modules/exporting'
import highchartsFunnel from 'highcharts/modules/funnel'
import highchartsSolidGauge from 'highcharts/modules/solid-gauge'
import highchartsGantt from 'highcharts/modules/gantt'
import highchartsNoDataToDisplay from 'highcharts/modules/no-data-to-display'
import highchartsWordCloud from 'highcharts/modules/wordcloud'
import highchartsXRange from 'highcharts/modules/xrange'
```
All modules are loaded and added to `Highcharts` within one file.

After upgrading I saw that some charts showed **weird numbers in the top left**, also the chart **colors were sometimes not right** (see legend vs. chart). 

![Screenshot from 2020-05-12 14-01-49](https://user-images.githubusercontent.com/201867/81687551-61adc600-9459-11ea-9776-646cbf28b6df.png)

During debugging I found that the issue is only present when the module `highchartsHeatMap` is used.

Because I wasn't able to reproduce this outside our app, I had a look at the implementation and after some investigation I found that the issue is caused by `ColorAxis` listening to `"bindAxes"`, which always adds an axis of type `colorAxis`:

https://github.com/highcharts/highcharts/blob/b6ab03b2e30b0a2158833c76ef2f2ab69f09abb9/ts/parts-map/ColorAxis.ts#L1464-L1473

This is done regardless of the current Series type.

So far I couldn't find a good workaround for this. Any suggestions?

**Comment by ppotaczek** [comment]
Hi @egraether, 

Thank you for contacting us!

Indeed, color axis is added to axis types of every series, but it should not be an issue. The axis is activated only if it is specified in a chart configuration object.

Could you share options for some of the affected chart? 
Here: http://jsfiddle.net/BlackLabel/7Lgoj2yh/ everything works as expected with loaded all of the listed modules.

As a workaround please try to set the axis to an empty array: `colorAxis: []`

Best regards!

**Comment by egraether** [comment]
Hello @ppotaczek, thank you for your feedback!

We realized that `colorAxis` was present in our theme, which is always added to the `Highcharts` instance. I was able to build a minimum sample to reproduce this now: http://jsfiddle.net/hdLf394o/

**Comment by ppotaczek** [comment]
That is normal behavior. Since v7.2 you can use one or multiple color axis for almost all series types.

**API**: https://api.highcharts.com/highcharts/colorAxis

**Comment by egraether** [comment]
@ppotaczek This is definitely a bug. Just because `colorAxis` is listed somewhere in my `theme`, does not mean I want it to show up on every chart.

**Comment by ppotaczek** [comment]
No it is not a bug. Highcharts themes work in this way. If you add for example three y-axis to a theme, they will be present in all charts: http://jsfiddle.net/BlackLabel/rkhb6vd5/1/

You can set all options in theme, not only the styling ones.

**Comment by egraether** [comment]
If that's the case, then I guess you can just close this, since it's not gonna be fixed anyways.

**Comment by karolkolodziej** [comment]
@dword-design You still can style individual charts- there is no need to put everything in the theme object.

The `theme` is useful if you have multiple charts on the page. 
The style/properties from it are applied to every chart as Paweł described previously.

**Comment by karolkolodziej** [comment]
I agree, with 
```js
// Apply the theme
Highcharts.setOptions(Highcharts.theme);
```
You apply the staying globally.

You can always suggest how would you like it to work.
