### ISSUE TITLE
Float Legend Bug

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1349]
If I define legend with y:329 I can see the legend If i define y:330 I can't see it. 
With float I should be able to place the legend I any place of I chart and I can't.

Problem occures in Chrome 22.0.1229.94 (Windows), but in MacOSX  version all works properly. (the same version).

Example: 

http://jsfiddle.net/jlbriggs/JfTbj/2/

**Comment by oysteinmoseng** [comment]
Seems to work as expected with latest: http://jsfiddle.net/JfTbj/21/
