### ISSUE TITLE
bubble series not visible after second call to addSeries

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#13494]
#### Expected behaviour
`addSeries` is called twice and two series are visible.
![image](https://user-images.githubusercontent.com/9820084/81692632-5c577800-9467-11ea-8f74-5939226e9550.png)

#### Actual behaviour
Only the second series is visible
![image](https://user-images.githubusercontent.com/9820084/81692538-3631d800-9467-11ea-8cc1-fba09e9bb726.png)

#### Live demo with steps to reproduce

https://jsfiddle.net/alvarezg/3xdkucny/
(resizing viewport or toggling series visibility in legend seems to fix the issue but initial render is wrong)
#### Product version

Highcharts, Highstock 8.0.3 and newer (works with 8.0.2)

**Comment by sebastianbochan** [comment]
Hi @alvarezguille,
Thank you for reporting. The problem here is that when the first series is added, the animation is run but not finished yet because of the next redraw and animation of the second series.

The solution is skip redraw (and animation) on the first series and run on the second. You also increase the performance of your chart.

Demo:
- https://jsfiddle.net/BlackLabel/bdtago5s/

**Comment by pawelfus** [comment]
It's a regression in v8.0.3, v8.0.2: works fine: https://jsfiddle.net/BlackLabel/k9qjrstn/

Most probably caused by one of the commits:
- ef8d54df5e0fc1c1567ff9ce30bd34e30d6109a1
- 5b06bed1a73f146b604a5a5fae2782989c04ed88

**Comment by alvarezguille** [comment]
Thanks for the quick feedback!
Personally I see the suggested solution more like a workaround. The live demo I provided is the minimal and simplest way to reproduce the issue, but in actual cases it might not be so trivial for us to know which is the last series that should do the redraw. 

Just out of curiosity, does pending reply mean the issue is waiting for me to provide some more info?

**Comment by TorsteinHonsi** [comment]
> but in actual cases it might not be so trivial for us to know which is the last series that should do the redraw.

The recommended practice is to skip redraw for _all_ series and then call `chart.redraw()` at the end: https://jsfiddle.net/highcharts/6wmgdxLv/

**Comment by alvarezguille** [comment]
Thanks for the tip, I'll take a look at it, at first I thought that would animate all series in case a third series is added later and redraw is called, but seems to animate only the new one. 🙇‍♂️

**Comment by TorsteinHonsi** [comment]
The rule is, if you're doing it sync, use a common redraw at the end.
