### ISSUE TITLE
Exporting - axes styling options regression

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#13492]
#### Expected behaviour

Last properly working version is 6.2.0: https://jsfiddle.net/BlackLabel/ayx1zq9u/
 
#### Actual behaviour

The styling options don't affect the axes while exporting. 

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/7t4aod0y/

Export the charts from both demos and compare to see the difference in axis styling. 

#### Product version

Highcharts JS v8.1.0 (2020-05-05)

Temporary workaround: https://jsfiddle.net/BlackLabel/kumhvwtc/

**Comment by ptijul** [comment]
I've reported this issue on stackoverflow. 
The workaround proposed, crashes on IE 11 with the error : 
Expected ':'

The IE console points out on "load()" as he is expecting a ":", but this seems completly correct.
Is there anything I can do ? (note that the JSFiddle is no longer supporting IE11....)

**Comment by pawelfus** [comment]
I don't have access to IE11 right now, but try changing `load() {` to `load: function() {`, demo: https://jsfiddle.net/BlackLabel/kumhvwtc/1/

**Comment by ptijul** [comment]
Many thanks for your quick reply. 
Oh yeah thanks @pawelfus, this make complete sense, I've tested and that works everywhere :)
To be honest, I hate IE11...but unfortunately the customers in the company I work for are mostly using IE11 (Windows 7).
