### ISSUE TITLE
incorrent chart width after printing landscape

### ISSUE THREAD

**Issue by klaskow** [highcharts/highcharts#13496]
#### Expected behaviour
Highcharts should adjust witdh to landscape printing (equal margin left and margin right) 

#### Actual behaviour
Too big right margin.

#### Live demo with steps to reproduce
https://codesandbox.io/s/highcharts-print-a4-right-margin-qpeey?file=/src/App.js
1. Open in New Window in CodeSandbox
2. Click Highcharts button menu
3. Print chart

#### Product version
highcharts 8.1.0
highcharts-react-official 3.0.0

#### Affected browser(s)
All major browsers.

**Comment by sebastianbochan** [comment]
Hi @klaskow,
Thank you for reporting about the problem.
Simplified demo:
- https://jsfiddle.net/BlackLabel/2v1ntrhd/

**Workaround:**
Catch [`beforePrint`](https://api.highcharts.com/highcharts/chart.events.beforePrint) and [`afterPrint`](https://api.highcharts.com/highcharts/chart.events.afterPrint) events and declare bigger size. (Please also set the correct CSS styles).

Demo:
- https://jsfiddle.net/BlackLabel/b51e7ugq/

**Comment by klaskow** [comment]
Hi @sebastianbochan 
Thank for your answer. Unfortunately, the solution you suggested  does not work. Regardless of the bigger width, the margin on the right is stil too large. Should be equal as left margin.

Here are screenshots from Your demos at jsfiddle (Print chart after Full screen view).

![2020-05-13_16-47-13](https://user-images.githubusercontent.com/51476475/81828027-a577fc80-9539-11ea-881e-624823474a71.jpeg)
![2020-05-13_16-47-42](https://user-images.githubusercontent.com/51476475/81828045-a7da5680-9539-11ea-89ac-7a52322de702.jpeg)

Let me know if You need more details.

**Comment by sebastianbochan** [comment]
Hi @klaskow,
I sent you not the final version of jsifddle, sorry!

Updated demo:
- https://jsfiddle.net/BlackLabel/o0pnc7e5/

There was missing the [printMaxWidth](https://api.highcharts.com/highcharts/exporting.printMaxWidth) param.

_Internal note_
It looks like the `printMaxWidth` does not work properly with landscape A4 format.
