### ISSUE TITLE
Updating the chart to be non-polar breaks point hover

### ISSUE THREAD

**Issue by l4z** [highcharts/highcharts#13490]
**Expected behavior:**
Point hover effect (halo, tooltip) should continue working after updating a chart to be non-polar.

**Actual behaviour:**
Hovering over datapoints while polar _and then_ subsequently updating the chart to be non-polar makes the points on the sides (but not the ones in the middle) lose their hover effects, the halo and the tooltip.

**Fiddle:**
https://jsfiddle.net/L444Z/pw9uemLh/21/

Steps:
1. Hover over the chart points to see their tooltips (don't skip this!)
2. Click the button to make the chart non-polar
3. Hover over a point in the beginning or in the end of the series

**Version:** Highcharts 8.1.0

I'd also be happy with a workaround!

**Comment by pawelfus** [comment]
Thanks for reporting the issue @l4z !

Bisected to commit d81da7da61

Last working version: v8.0.0

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/0fowqmrt/

Plugin:
```js
(function(H) {
  H.addEvent(
    H.Pointer,
    'beforeGetHoverData',
    function(e) {
      if (!this.chart.polar) {
        this.chart.hoverPane = undefined;
      }
    });
})(Highcharts);
```

FYI @raf18seb

**Comment by l4z** [comment]
Thanks @pawelfus! The plugin works like a charm
