### ISSUE TITLE
Rotation in IE8 doesn't displayed correctly

### ISSUE THREAD

**Issue by nZeus** [highcharts/highcharts#1350]
Open these pages in IE8:
http://jsfiddle.net/Fusher/4ghhf/3/
http://www.highcharts.com/tests/?file=text-rotation

Font is unreadable.

**Comment by cvasseng** [comment]
Hi! We're doing a bit of spring cleaning, and closing old issues. If you're still experiencing issues with this, please feel free to open a new issue! Thanks!
