### ISSUE TITLE
Moving navigator highlights text if cursor moves out of the navigator while zooming

### ISSUE THREAD

**Issue by gbt518** [highcharts/highcharts#13503]
#### Expected behaviour
v8.0.4: https://jsfiddle.net/7obh2dwm/
![navigator-old](https://user-images.githubusercontent.com/2381312/81747346-90359c00-946d-11ea-845e-19c745512edd.gif)

#### Actual behaviour
v8.1.0: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/basic-line/
![navigator-new](https://user-images.githubusercontent.com/2381312/81747374-9cb9f480-946d-11ea-8b19-2fc602d45cc4.gif)

#### Live demo with steps to reproduce
See links above

#### Product version
Highstock v8.1.0+

#### Affected browser(s)
Chrome

I'm not sure if this is related to the fix for https://github.com/highcharts/highcharts/issues/13226 (Note that v8.0.3 does not have this behavior either)

This issue is very apparent in our app due to a much smaller navigator height which makes it very easy to slightly move the cursor off the navigator while zooming

**Comment by sebastianbochan** [comment]
Hi @gbt518,
Thank you for reporting about the problem.

As a workaround you can declare css styles:
```
#container {
  -webkit-user-select: none;  /* Chrome all / Safari all */
  -moz-user-select: none;     /* Firefox all */
  -ms-user-select: none;      /* IE 10+ */
  user-select: none;          /* Likely future */      
}
```

Demo:
- https://jsfiddle.net/BlackLabel/hpqc826L/

FYI @Izothep
