### ISSUE TITLE
Page re-requested when Highcharts completes load (IE only)

### ISSUE THREAD

**Issue by gmiller1763** [highcharts/highcharts#13502]
#### Expected behaviour
When the loading of a chart completes in IE 11, no additional, unintentional requests are made. 

This was was working as expected in Highcharts 7.1.1, but I recently upgraded from Highcharts 7.1.1 to Highcharts 8.0.4. After noticing the bug in 8.0.4, I upgraded to the latest available download: Highcharts 8.1.0, but the problem persisted.

#### Actual behaviour
When the loading of a chart completes in IE 11, the page containing the chart is re-requested.
![image](https://user-images.githubusercontent.com/8700136/81722967-26f36000-9450-11ea-8eda-f2320ac95487.png)

#### Live demo with steps to reproduce
jsFiddle does not support IE 11, but this bug is reproducible using the demos on the Highcharts website: https://www.highcharts.com/demo/line-basic

#### Product version
Highcharts 8.1.0
(This bug does not exist in 7.1.1)

#### Affected browser(s)
IE 11 - this bug is not reproducible in Chrome, FF, or Edge.

**Comment by KacperMadej** [comment]
Hi @gmiller1763 

Thank you for reporting the problem.

I have set up a simple demo on local server, without any other scripts, without any cookies and tracking scripts and the page was not requested again, so I am not sure if this is a problem with Highcharts library or with something else. Debugging in IE11 shows only that the source of the request is some image and I have no more info to work with.

Have you set up a clean Highcharts demo on your server that could show the problem? How is this page reloading a problem for you?

**Comment by gmiller1763** [comment]
Thank you for your help! 

I was having trouble trying to isolate the issue in a clean environment.  The page re-request was leading to JavaScript issues, but with the latest version of Highcharts (Version 8.1.1), the page is no longer being re-requested in IE!

Please mark this issue as solved. Thank you!
