### ISSUE TITLE
Remove extra spacing/padding from

### ISSUE THREAD

**Issue by chetanpingale** [highcharts/highcharts#13515]
While rendering solidgauge chart adds default padding, I want to remove that.
Below is code using for chart oprions

const options = {
        credits: {
            enabled: false
        },
        chart: {
            type: "solidgauge",
            height: "100%",
            backgroundColor: 'rgba(255, 255, 255, 0.0)',
            events: {
                render: renderIcons
            }
        },

        title: {
            text: "",
            style: {
                fontSize: "24px"
            }
        },

        tooltip: {
            borderWidth: 0,
            backgroundColor: "none",
            shadow: false,
            style: {
                fontSize: "16px"
            },
            valueSuffix: "%",
            pointFormat:
                '<span style="font-size:2em; color: {point.color}; font-weight: bold">{point.y}</span>',
            positioner: function(labelWidth) {
                return {
                    x: (this.chart.chartWidth - labelWidth) / 2,
                    y: this.chart.plotHeight / 2 + 15
                };
            }
        },

        pane: {
            startAngle: -90,
            endAngle: 90,
            background: [
                {
                    // Track for Move
                    outerRadius: "50%",
                    innerRadius: "30%",
                    backgroundColor: Highcharts.Color(Highcharts.getOptions().colors[0])
                        .setOpacity(0.3)
                        .get(),
                    borderWidth: 0
                }
            ]
        },

        yAxis: {
            min: 0,
            max: 100,
            lineWidth: 0,
            tickPositions: []
        },

        plotOptions: {
            solidgauge: {
                dataLabels: {
                    enabled: true
                },
                linecap: "round",
                stickyTracking: false,
                rounded: false
            }
        },

        series: [
            {
                name: "",
                type: "solidgauge",
                data: [
                    {
                        color: "#e6cb00",
                        radius: "50%",
                        innerRadius: "30%",
                        y: '',
                        val: ''
                    }
                ],
            }
        ]
    };

#### Live demo with steps to reproduce

![Screenshot 2020-05-13 at 3 26 05 PM](https://user-images.githubusercontent.com/13327646/81856021-25986500-952e-11ea-9592-a26c361fcd1b.png)

**Comment by sebastianbochan** [comment]
Hi @chetanpingale,
Thank you for contacting us. The github is our bug tracker so for general [support]() questions please use other channels like stackoverflow, email or forum.

ps. during the contact, please share your live simplified demo.
