### ISSUE TITLE
[Question] Roadmap: New dashboard package

### ISSUE THREAD

**Issue by kuraga** [highcharts/highcharts#13524]
Good day!

There is an item in Roadmap:

```
New dashboard package which will administer the data layer and communication between multiple charts and other components. Commenced work in Q2 2020.
```

Are the some branches/issues/documentation/code about it?

This feature is what our company is interested for. Thanks!

P.S. Sorry, I ask here because the Forum don't send registration message to my e-mails.

**Comment by sebastianbochan** [comment]
Hi @kuraga,
At this moment we are creating a scope of the project and we will develop components soon.

For the future, you can use also our email. You can find more information about support [here](https://www.highcharts.com/support)
