### ISSUE TITLE
Gradient fill with CSS doesn't work in Edge

### ISSUE THREAD

**Issue by rocklan** [highcharts/highcharts#13526]
#### Expected behaviour
Column bars to be gradient filled

#### Actual behaviour
Column bars not shown

#### Live demo with steps to reproduce
https://jsfiddle.net/kr0tx7a1/

#### Product version
v8.1.0

#### Affected browser(s)
Edge only (AFAIK)

I am pretty sure this is a bug in Edge. If you manually remove the `highcharts-color-0` class from the `highcharts-series` *<g>* tag, it works. If you remove the same css class from the *<rect>* tag it works too. But if you have the same class applied to both, nothing is shown! 

I will do a pull request fix for this - either the `highcharts-color-0` class can be removed from the `highcharts-point` *<rect>* or removed from the group. As far as I can tell one series cannot have multiple colors so it doesn't make sense to have the class applied at the point level - it might as well just be removed. I have tried this for my graphs and it's working ok. I assume you guys can do better testing than me :)

**Comment by TorsteinHonsi** [comment]
Thanks for the PR! I'm tagging this for the Backlog, then someone in our team can assess it. We can't use your PR directly, as the `.js` files are generated from `.ts` files.

**Comment by KacperMadej** [comment]
Hi @rocklan

Thank you for reporting the problem.

The gradients are showing fine for me when using Edge version 81.0.416.72.
What version of Edge have you tested?

**Comment by rocklan** [comment]
This is on Microsoft Edge 41.16299.1480.0 which uses Microsoft EdgeHTML 16.16299. Version 81 is the new chromium based version with a different layout engine. At last check 6% of our users are on the older EdgeHTML version of Edge so I have to support them.

**Comment by KacperMadej** [comment]
Please try a demo with limited CSS (gradient options moved to JS): https://jsfiddle.net/BlackLabel/r4g0bstd/

Have you tried to recreate the problem without Highcharts and report it to Microsoft? If other browsers are working fine then maybe this is a bug in Edge v41.

**Comment by raf18seb** [comment]
I was able to reproduce the issue in Edge 44.18362.449.0 with EdgeHTML 18.18363. The issue occurs when we define gradient on both element and its parent.

As a **workaround**, you can define gradient on one element only (single `.highcharts-color-0` class): https://jsfiddle.net/BlackLabel/L7ez0tcf/

```css
.highcharts-point.highcharts-color-0,
.highcharts-legend-item.highcharts-color-0,
.highcharts-tooltip .highcharts-color-0 {
    fill: url(#gradient0);
}
```

I'm not sure whether this bug is caused by Highcharts or Edge browser.

**Comment by pawelfus** [comment]
Regarding the proposed solution, we can not implement this. At least one of the options will be broken (`colorByPoint`): https://jsfiddle.net/BlackLabel/r6fum5a0/ - but this one we can filter out.

Additionally, by removing this class, we will break current implementations (tests report: 3D pie chart and solid-gauge at least), introduce regressions.

Given the fact it's a bug in browser I suggest to use either workaround posted above, or resign from using gradients in Microsoft Edge versions 41-44.  I'm sorry for the inconvenience.

I would love to report this bug to Edge devs, but I am not able to find their issue tracker at all. I'm serious.. Everything redirects me to main webpage about ms edge.

**Comment by rocklan** [comment]
That workaround is fantastic @raf18seb  - I never thought of that. Thanks very much everyone involved and really appreciate the quick response and great communication.
