### ISSUE TITLE
Bubbles - shadow option issue

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#13531]
#### Expected behaviour

The shadow effect should be visible on points. 

#### Actual behaviour

The shadow option doesn't work. Documentation suggests that this option should work on this type of the series - https://api.highcharts.com/highcharts/series.bubble.shadow

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/0rhvxnes/

#### Product version

Highcharts JS v8.1.0 (2020-05-05)

**Comment by pawelfus** [comment]
It works as described: 

> Whether to apply a drop shadow to **the graph line.**

Demo: https://jsfiddle.net/BlackLabel/dk8echqv/1/ - markers do not have shadows.
