### ISSUE TITLE
Chart with draggable points throws errors on touch devices

### ISSUE THREAD

**Issue by pjanaya** [highcharts/highcharts#13534]
#### Expected behaviour
Touch devices supported

#### Actual behaviour
Using charts with draggable points with touch devices make them unresponsive

#### Live demo with steps to reproduce
This can be reproduced on any official jsFiddle from the documentation.
1) Go here: https://api.highcharts.com/highcharts/plotOptions.series.dragDrop
2) Select "[Draggable column and line series](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/dragdrop/resize-column)"
3) With Chrome Developer Tools enable "Device Toolbar" and select iPad as device.
4) Just click anywhere on the chart. It throws this:
````
highcharts.src.js:22772 Uncaught TypeError: Cannot read property '0' of undefined
    at f.normalize (highcharts.src.js:22772)
    at x (draggable-points.src.js:1322)
    at HTMLDocument.<anonymous> (draggable-points.src.js:2260)
````
I've been able to track this down to this file: https://github.com/highcharts/highcharts/blob/master/ts/parts/Pointer.ts

In the [line 1194](https://github.com/highcharts/highcharts/blob/39793279986ac351d42b66e7ae789579380f5234/ts/parts/Pointer.ts#L1194): 
````
// iOS (#2757)
const ePos = (
    touches ?
        touches.length ?
            touches.item(0) as Touch :
            touches.changedTouches[0] :
         e as unknown as PointerEvent
);
````

It looks like ``touches.changedTouches`` is ``undefined``, because ``e.touches.changedTouches`` is ``undefined``. It should be ``e.changedTouches`` instead. I tried locally and that simple change seems to fix the problem and make it work for both touch and non-touch devices.

Possible fix:
````
// iOS (#2757)
const ePos = (
    touches ?
        touches.length ?
            touches.item(0) as Touch :
            e.changedTouches[0] :
         e as unknown as PointerEvent
);
````
#### Product version
Highcharts: 8.1.0
Draggable Points: 8.1.0

#### Affected browser(s)
Safari on iPad Pro
Chrome with iPad mode enabled

**Comment by sebastianbochan** [comment]
Hi @pjanaya,
Thank you for reporting. It looks like a problem in the `touches` structure. I prepared you a simple workaround for that, which fixed the problem.

```
Highcharts.Pointer.prototype.normalize = function(e, chartPosition) {
              var touches = e.touches;
              // iOS (#2757)
              var ePos = (touches ?
                touches.length ?
                touches.item(0) :
                ((touches.changedTouches && touches.changedTouches[0])) :
                e);

              // Get mouse position
              if (!chartPosition) {
                chartPosition = this.getChartPosition();
              }

              if (ePos && ePos.pageX && ePos.pageY) {
                var chartX = ePos.pageX - chartPosition.left,
                  chartY = ePos.pageY - chartPosition.top;
                // #11329 - when there is scaling on a parent element, we need to take
                // this into account
                var containerScaling = this.chart.containerScaling;
                if (containerScaling) {
                  chartX /= containerScaling.scaleX;
                  chartY /= containerScaling.scaleY;
                }
              }
              return Highcharts.extend(e, {
                chartX: Math.round(chartX),
                chartY: Math.round(chartY)
              });
            };
```

Demo:
- https://jsfiddle.net/BlackLabel/gbu74smw/

Please be aware that it can be limited in use.

**Comment by sebastianbochan** [comment]
Hi @pjanaya,
Does it work properly? In all my test-cases yes, but need to ensure. If yes I will commit this changes to the module.

**Comment by pjanaya** [comment]
Hi @sebastianbochan,
I'm can't confirm. Before you sent this workaround I prepared my own:
````
    var normalize = Highcharts.Pointer.prototype.normalize;

    Highcharts.Pointer.prototype.normalize = function(e, chartPosition) {
      if (e.touches) {
        if (e.changedTouches && !e.touches.changedTouches) {
          e.touches.changedTouches = e.changedTouches;
        }
      }
      return normalize.bind(this, e, chartPosition)();
    };
````
I could possibly try yours tomorrow. Do you want me to do that?

**Comment by sebastianbochan** [comment]
If you can, would be grateful, because as I said, in my tests, all work properly. So I would liek to ensure that in your use-case it works too.

**Comment by pjanaya** [comment]
Well, I can't even run it. The ``chartX`` and ``chartY`` properties are declared inside the new ``if`` block, but they are used in the ``return`` from outside. Naturally this throws an error: ``Cannot find name 'chartX'``. 

Worth noting that I'm using Typescript, so I had to make a few changes. This is the code that DOES NOT WORK:

````
Highcharts.Pointer.prototype.normalize = function(
      e: MouseEvent | PointerEvent | TouchEvent,
      chartPosition?: Highcharts.OffsetObject | undefined
    ) {
      const touches = (e as any).touches;
      // iOS (#2757)
      const ePos = touches
        ? touches.length
          ? touches.item(0)
          : touches.changedTouches && touches.changedTouches[0]
        : e;

      // Get mouse position
      if (!chartPosition) {
        chartPosition = this.getChartPosition();
      }

      if (ePos && ePos.pageX && ePos.pageY) {
        let chartX = ePos.pageX - chartPosition.left,
          chartY = ePos.pageY - chartPosition.top;
        // #11329 - when there is scaling on a parent element, we need to take
        // this into account
        const containerScaling = (this as any).chart.containerScaling;
        if (containerScaling) {
          chartX /= containerScaling.scaleX;
          chartY /= containerScaling.scaleY;
        }
      }
      return Highcharts.extend(e, {
        chartX: Math.round(chartX),
        chartY: Math.round(chartY),
      }) as any;
    };
````

Apart from what I mentioned, I also had to replace the first line. The currently released version says: ``const touches = (e as TouchEvent).touches;``. However, that does not work anymore because: ``Property 'changedTouches' does not exist on type 'TouchList'``.

**Comment by sebastianbochan** [comment]
Thank you for feedback!

**Comment by raf18seb** [comment]
I think the same issue causes errors when clicking on legendItem on touch device.

Steps to reproduce: go to https://www.highcharts.com/demo/line-basic and open developer console in "mobile view", then click legendItem.

If it's not the same, let me know and I'll create a separate ticket.

**Comment by sebastianbochan** [comment]
@raf18seb I debugged the issue and its related with accessibilty module. Please create a separate ticket.
