### ISSUE TITLE
Tooltips don't work in Firefox after using history.pushState

### ISSUE THREAD

**Issue by mimus** [highcharts/highcharts#1353]
In Firefox, when you create a new Bar chart with dataLabels enabled, and then use history.pushState, tooltips don't display - except for the last series which is ok.

Example: http://jsfiddle.net/6Gka6/

The chart that is drawn initially is correct: all 3 bars have a tooltip.
Press the 'Set new data' button and a new chart will be drawn, immediately followed by pushState: only the top bar has a tooltip.

I see this in Firefox 16.0.1 on Ubuntu and 16.0.2 on Windows.

**Comment by oysteinmoseng** [comment]
Doesn't seem to be an issue with latest Firefox and latest Highcharts. Closing for now.
