### ISSUE TITLE
Auto Adjusting of axis labels on x-Axis resulting in text overlaps while expanding navigator

### ISSUE THREAD

**Issue by AviralVarshney123** [highcharts/highcharts#13537]
#### Expected behaviour
On resizing, labels should not overlap and they should auto-rotate if required

#### Actual behaviour
Auto Adjusting of axis labels on x-Axis resulting in text overlaps while expanding navigator

#### Live demo with steps to reproduce

![hgichart](https://user-images.githubusercontent.com/7874449/82121481-ffcbc400-97aa-11ea-83b9-040bc45f91f5.gif)

#### Product version 
8.0.0

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @AviralVarshney123,
Thank you for reporting. Could you share update my demo with your simplified data and chart options? 

- https://jsfiddle.net/BlackLabel/9ra3gwb6/

It will allow me to debug the problem, which looks like similar to https://github.com/highcharts/highcharts/issues/12238
