### ISSUE TITLE
Label, Circle, Rectangle annotations are not editable in Highcharts 8.1.0

### ISSUE THREAD

**Issue by marioil** [highcharts/highcharts#13532]
#### Expected behaviour
Annotations of type "label", "circle" and "rectangle" to be editable.

#### Actual behaviour
In version 8.1.0 the mentioned annotations can't be edited.

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/stock-tools-gui

**Comment by sebastianbochan** [comment]
Hi @marioil,
Thank you for reporting. Its a regression which is caused by decomposition in TS.

Will fix as soon as possible.

**Comment by pawelfus** [comment]
Yes, it seems annotation is not sending meta info about fields.

@Basts - could you take a look? In short:
https://github.com/highcharts/highcharts/blob/2a5ecafce9fa44f4852bc1c0d86b7e8855fc753b/ts/annotations/navigationBindings.ts#L295-L298

Is not compatible with changes: 
https://github.com/highcharts/highcharts/blob/2a5ecafce9fa44f4852bc1c0d86b7e8855fc753b/ts/annotations/navigationBindings.ts#L306-L308
