### ISSUE TITLE
403 Forbidden on export.highcharts.com

### ISSUE THREAD

**Issue by RodrigoSalto** [highcharts/highcharts#13547]
#### Expected behaviour

A url with the exported chart
#### Actual behaviour
A 403 error from cloud fare comes up with the text `>Please complete the security check to access export.highcharts.com`

#### Product version
Highcharts Latest version

#### Affected browser(s)
Im using laravel with the Guzzle client

**Comment by sebastianbochan** [comment]
Hi @RodrigoSalto,
Thank you for reporting. When I run a simple demo: https://jsfiddle.net/BlackLabel/dzrjg32m/ I am not able to reproduce the problem. Could you update my example with your chart's options and data?

**Comment by RodrigoSalto** [comment]
@sebastianbochan here is the update fiddle https://jsfiddle.net/s4e7dz69/1/ 

However your test is using javascript which is not my case, im using php with the laravel http client https://laravel.com/docs/7.x/http-client 

The main difference is that in your example the request will be made by the user browser and it will send the user's browser headers and ip, in my use case the request is being made by the laravel http client which makes use of Guzzle http://docs.guzzlephp.org/en/stable/ and the request is being made by a server not a browser which for some reason cloudfare is blocking.

**Comment by pawelfus** [comment]
We will check that, but in general, that means you (or someone's else using your IP) was considered as bot/spammer or did some other suspicious actions against our CloudFlare-protected server.

In general, you can test (I'm sorry, I don't know Laravel, neither Guzzle) the server using curl, for example:

> curl -d "async=true&type=jpeg&width=400&options=%7B%22xAxis%22:%7B%22categories%22:%5B%22Jan%22,%22Feb%22,%22Mar%22%5D%7D,%22series%22:%5B%7B%22data%22:%5B29.9,71.5,106.4%5D%7D%5D%7D" https://export.highcharts.com/

And then test the output, for example:

```html
<img src="https://export.highcharts.com/....">
```
For example
```html
<img src="https://export.highcharts.com/charts/chart.766265c68d7e410b92f9ff08484a6d48.png">
```

This is mine output:
![Screen Shot 2020-05-20 at 10 19 12](https://user-images.githubusercontent.com/1453926/82422932-61c64b00-9a83-11ea-86d9-d39c814cf472.png)

If the error will occur again, then please consider setting up your own exporting server, see docs: https://www.highcharts.com/docs/export-module/setting-up-the-server
