### ISSUE TITLE
The 'oneToOne' parameter of 'Chart.update' does not work properly.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#13541]
#### Expected behaviour
Updating the chart with `oneToOne` flag set equal to `true` should work as it is described in documentation.

#### Actual behaviour
Updating chart with the new series array, where all series contain `id` does not work as it is described in documentation.

Per the documentation:
> If the series have id's, the new series options will be matched by id, and the remaining ones removed.

However, the following example shows that it does not work in that way, because it should result in removing the first series, keeping the second without any changes, and add the third. The effect is keeping only the third one.

This issue could be related with #9606.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/bt0acn2w/

**Comment by lukesaunders** [comment]
The related issue has been open since 2018. It's quite hard for me to use highcharts (via the vue wrapper) with this bug and seems quite important that `oneToOne` works as described, so please prioritise the fix.
