### ISSUE TITLE
Custom error handling not working

### ISSUE THREAD

**Issue by kai2468** [highcharts/highcharts#13549]
#### Expected behaviour
Expect to run custom error handling code when set

#### Actual behaviour
Custom error handling doesnt get picked up

#### Live demo with steps to reproduce
Can be seen in one of your demos, run the code and it doesnt work, it just outputs the error in the console:
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/highcharts-error/

If I change the code.highcharts link to v7.0 and it starts to work again:
http://jsfiddle.net/yrktezd1/

**Comment by sebastianbochan** [comment]
Hi @kai2468,
Thank you for reporting. We refactored the core and now uses events to trigger the custom actions instead of wrapping.

The solution is use `displayError` event.

Demo:
- http://jsfiddle.net/BlackLabel/ex5n8sqd/

I would not consider it as a bug.
