### ISSUE TITLE
Exception on logarithmic scatter chart with negative x-values

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#13553]
#### Expected behaviour
Points with values <0 are ignored om logarithmic scaled axis when the axis minimum is set above 0.

As stated in the documentation:

> As a consequence, Highcharts will remove 0 or negative points associated to the axis, and if you try to set the axis.min option to 0 or negative, it will fail with an error.

#### Actual behaviour
When the x value of a scatter point is <0 you get Highcharts exception 10.

#### Live demo with steps to reproduce
http://jsfiddle.net/kzoon/cpey9qkf/
Notice that points with negative y-values _are_ ignored without the exception:
http://jsfiddle.net/kzoon/5yvkxqLo/

#### Product version
Highcharts latest, probably earlier as well

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting the issue @kzoon 

*Internal note:*
We don't check value on xAxis, only yAxis:
https://github.com/highcharts/highcharts/blob/0cceea08b8690add619759dfd13f0c4b1d3a4a9e/ts/parts/Series.ts#L5191-L5197
