### ISSUE TITLE
Accessibility module throwing an error in the console

### ISSUE THREAD

**Issue by rocklan** [highcharts/highcharts#13556]
After including `exporting.js` and `accessibility.js` I am getting an error in the console. Just wondering if it's an obvious problem or not.

```
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>```
```

#### Expected behaviour
No error :)

#### Actual behaviour
The following error is shown in the console:

```
highcharts-accessibility.js:65 Uncaught TypeError: (a.annotations || []).reduce is not a function
    at h (highcharts-accessibility.js:65)
    at getPointAnnotationTexts (highcharts-accessibility.js:68)
    at u (highcharts-accessibility.js:74)
    at highcharts-accessibility.js:76
    at Array.forEach (<anonymous>)
    at r (highcharts-accessibility.js:75)
    at describeSeries (highcharts-accessibility.js:78)
    at highcharts-accessibility.js:94
    at Array.forEach (<anonymous>)
    at a.onChartRender (highcharts-accessibility.js:94)
```

#### Product version
Highcharts 8.1

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @rocklan 

Thanks! Are you able to recreate issue in a standalone demo, for example jsFiddle? Just tested and looks fine: https://jsfiddle.net/BlackLabel/fjyrLahn/ - no error :)

**Comment by rocklan** [comment]
Ahha. The issue that I was using an old version of the `annotations` module. The `chart.annotations` variable has changed from an object to an array, so in the initialisation all I had to do is change is to:
```
        if (!chart.annotations)
            chart.annotations = [];
```
