### ISSUE TITLE
Accessibility Module and Legend Proximate

### ISSUE THREAD

**Issue by garybrain** [highcharts/highcharts#13554]
#### Expected behaviour
When using the legend proximate, when clicking on each item it should toggle the visibility.

#### Actual behaviour
When the accessibility module is loaded the legend items stop referencing the correct line so when an item moves to the bottom of the list and you then try and enable it another legend is affected.

#### Live demo with steps to reproduce
https://jsfiddle.net/garybrain/m9e37zyp/10/

#### Product version
8.1.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Could you provide steps to reproduce the issue in your demo? For me it looks fine: 
![accessibility](https://user-images.githubusercontent.com/1453926/82411139-81547800-9a71-11ea-96f5-65da842b93df.gif)

**Comment by garybrain** [comment]
Hi @pawelfus , very strange. The fiddle link above gives me the follow output.

![2020-05-20_09-49-49](https://user-images.githubusercontent.com/4255782/82426187-7274c200-9a7f-11ea-958d-b119c04241f0.gif)

Thanks

G.

**Comment by pawelfus** [comment]
Ah.. I didn't expect to click in the empty space, thanks for clarifying! :)
FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
Workaround: Disable pointer events on proxy buttons as follows (insert code before creating chart)

```js
Highcharts.wrap(Highcharts.AccessibilityComponent.prototype, 'setProxyButtonStyle', function (proceed, btn) {
  proceed.apply(this, Array.prototype.slice.call(arguments, 1));
  btn.style.pointerEvents = 'none';
});
```

https://codepen.io/oysteinmoseng/pen/mdeaxOz?editors=0010

**Comment by garybrain** [comment]
@pawelfus Sorry should have been clearer as I did mention the accessibility.

Confirmed fixed :)

thanks

G.
