### ISSUE TITLE
Error reported removeElementFromCollection of undefined when updating the networkgraph data

### ISSUE THREAD

**Issue by jiazhuangzhexiaozhang** [highcharts/highcharts#13570]

**Comment by sebastianbochan** [comment]
Hi @jiazhuangzhexiaozhang,
Thank you for reporting. Could you share your live demo ? It will allow us to debug the problem and find a solution.

ps. Please use our template instead of placing the problem description in the title.

**Comment by KacperMadej** [comment]
**Demo**: https://jsfiddle.net/BlackLabel/81a4cLd5/
**Steps**: an update runs after 1.5s and the chart crashes with the error

_Internal note:_
The issue description matches the issue I wanted to redirect from the Angular wrapper (https://github.com/highcharts/highcharts-angular/issues/194)

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/93cf2n4v/

Plugin:
```js
(function(H) {
  H.seriesTypes.networkgraph.prototype.destroy = function() {
    if (this.layout) {
      this.layout.removeElementFromCollection(this, this.layout.series);
    }

    H.NodesMixin.destroy.call(this);
  }
})(Highcharts);
```

**Comment by Himanshi-Kansara** [comment]
i am getting the same error in highchart version 7.2.0 ,i can't update the version. is there any way to add the above solution in typescript file

**Comment by pawelfus** [comment]
The solution above is using internal methods, so our typescript definitions are not covering them. To use it in TS, simply cast to `any` anything that causes issues.
