### ISSUE TITLE
Drag and drop in the boxplot series doesn't work.

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#13576]
#### Expected behaviour
The low, high, q1 and q3 values should be draggable.
As it is in the version 6.2.0: https://jsfiddle.net/BlackLabel/2go6sf43/ 

#### Actual behaviour
Only two of this values are draggable. 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/e42uhg80/

#### Product version
Highcharts v8.1.0 

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Bisected to commit baaca05bff
