### ISSUE TITLE
Fibonacci zones are not visible on the demo

### ISSUE THREAD

**Issue by mekhatria** [highcharts/highcharts#13577]
#### Expected behavior
Fibonacci zones appear on the chart.

#### Actual behaviour
due to the late date in the annotation feature, the chart doesn't pick the right Fibonacci zones:

`fibonacciRetracements(Date.UTC(2016, 10, 14), 105, Date.UTC(2017, 8, 4), 170)],`

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/annotations/fibonacci-retracements

**Comment by pawelfus** [comment]
Note that it's only a bug in demo, so it should be fixed in the demo.

We agreed on using fixed dataset in the demo instead of the dynamic one (https://www.highcharts.com/samples/data/aapl-ohlc.json). Perhaps we already have one, for example intraday?

**Comment by goransle** [comment]
It might be OK to use the current dataset, as the dynamic version will transition to demo-live-data.highcharts.com. 

@mekhatria Should it look something like this? https://jsfiddle.net/64enapby/

**Comment by mekhatria** [comment]
It is fine as long as users can see the result of the Fibonacci on a chart: 


![Screenshot 2020-06-15 at 11 45 39](https://user-images.githubusercontent.com/12743677/84643348-fe063500-aefd-11ea-9aa0-2c2646bda321.png)

**Comment by goransle** [comment]
[Fixed!](https://www.highcharts.com/samples/stock/annotations/fibonacci-retracements)
