### ISSUE TITLE
Fullscreen on iOS

### ISSUE THREAD

**Issue by hillerrv** [highcharts/highcharts#13583]
#### Expected behaviour
Full screen view opens.

#### Actual behaviour
Full screen view does not open.

#### Live demo with steps to reproduce
- Open https://www.highcharts.com/demo/line-basic in Safari on iOS 13
- Click burger menu -> 'view in full screen'

#### Product version
Highcharts v 8.1.0

#### Affected browser(s)
Safari and Chrome on iOS

**Comment by sebastianbochan** [comment]
Hi @hillerrv,
Thank you for reporting. As I see in the scope of functionality, the Fullscreen API is not supported in iOS Safari and has partial support in Safari: [more on this](https://caniuse.com/#feat=fullscreen).

As I tested the fullscreen works on iPad, but not on iPhone.

**Comment by hillerrv** [comment]
Hi @sebastianbochan 
I do see the problem that the official Fullscreen API is not supported on iPhone. However, using a decent library I would not expect the need to implement the workaround myself.

**Comment by raf18seb** [comment]
Hi @hillerrv

As @sebastianbochan said, the scope of our fullscreen module functionality is limited to the browser [Full Screen API](https://caniuse.com/#feat=fullscreen) which is limited in some browsers.

We could do some research and extend it in the future, but it is not on our high priority features list right now. I agree with you that, for now, we could create our official support matrix and add it into our docs, but, in the end, it would be very similar to the one shown in the link above.

I am sorry for the inconvenience, but there is not much we can do with it at this moment.

**Comment by urvesh86** [comment]
Hi @sebastianbochan & @raf18seb, 

we are facing the same issue in IOS device too. I went through whole thread. It is really helpful if you fix it asap.

Thank you!!

**Comment by hillerrv** [comment]
Hi @raf18seb 
I agree that your documentation would be very similar to the link of caniuse, but as a developer I do not know that you implemented the highcharts fullscreen mode with the Full Screen API. Thus, it would be very useful if you would add a note in the documentation for other developers.

**Comment by raf18seb** [comment]
@hillerrv good point, thanks for sharing your opinion.

**Comment by urvesh86** [comment]
Hi @sebastianbochan & @sebastianbochan,

I have upgraded latest version of highchart (8.1.2), still facing the same issue. If you have any plan to solve this issue in near future, please share tentative date of when this feature will be available. It would helpful to us in planning.

**Comment by sebastianbochan** [comment]
HI @urvesh86,
At this moment we do not have an ETA for this issue, but will try to debug it next week.

**Comment by sebastianbochan** [comment]
After deep debugging and find a solution / workaround it turned out that its still limited by iOS. There is no workaround except a rebuild of app: https://stackoverflow.com/questions/16485919/open-webpage-in-fullscreen-in-safari-on-ios#

I found only one information on the apple site about release fullscreen for ipad here: https://developer.apple.com/documentation/safari-release-notes/safari-12-release-notes.

We should wait for the official support this functionality by iOS. 
Related topic:
- https://developer.apple.com/forums/thread/133248

Meanwhile I updated the docs about limits.

**Comment by vlad-tura** [comment]
IOS can now use [webkitEnterFullscreen](https://developer.apple.com/documentation/webkitjs/htmlvideoelement/1633500-webkitenterfullscreen).

Is it possible to revive this issue?

**Comment by bm64** [comment]
Hello @vlad-tura 

As far as I know [webkitEnterFullscreen](https://developer.apple.com/documentation/webkitjs/htmlvideoelement/1633500-webkitenterfullscreen) works only for video elements, doesn't it? https://developer.apple.com/documentation/webkitjs/htmlvideoelement/1628805-webkitsupportsfullscreen, https://developer.apple.com/forums/thread/133248

**Comment by vlad-tura** [comment]
You are right
