### ISSUE TITLE
The X-axis shows the problem

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13582]
#### 
The X-axis should not show up when I don't have it set

#### 
I didn't set the minute, it came out at 12:00

#### Live demo with steps to reproduce

https://jshare.com.cn/temp/HdGykr

**Comment by sebastianbochan** [comment]
Hi @weixingcai,
Thank you for reporting. When I run your demo, I am not able to reproduce the problem.

The result is:

<img width="502" alt="Zrzut ekranu 2020-05-25 o 09 52 07" src="https://user-images.githubusercontent.com/2115686/82791115-7a60a780-9e6d-11ea-9b3f-5487c6ca3075.png">

I am not observe the time in your chart.

ps. You can edit labels by formatters:
- https://api.highcharts.com/highcharts/tooltip.dateTimeLabelFormats
- https://api.highcharts.com/highcharts/xAxis.dateTimeLabelFormats

**Comment by weixingcai** [comment]
When your chart is wide in width, it will appear in hours


link： https://jshare.com.cn/temp/HdGykr
![111](https://user-images.githubusercontent.com/48822299/82791608-a6495080-9ea0-11ea-8de0-1e78ec1a8734.png)

Please take a look at the red mark on the picture. There are no hours on the day, month and year, but it appears

**Comment by sebastianbochan** [comment]
You have two options:
- set tickInterval as 24 * 3600 * 1000 (1 day in miliseconds)
- edit the datetimeLabelFormat for hour and set the same rule as for day.

ps. For the future please use other channels for general [support](https://www.highcharts.com/support) cases.
