### ISSUE TITLE
Pie chart: CSS classes not being added/removed correctly

### ISSUE THREAD

**Issue by webdevan** [highcharts/highcharts#13590]
#### Expected behaviour
When you clickOn/mouseOver a chart segment it should add a class to the svg path and when you  clickOff/mouseOut it should remove the class.

Similarly `point.update({ className: 'foo' })` should add `foo` class to the path and `point.update({ className: null })` should remove the `foo` class.

#### Actual behaviour
Classes get added without a space separating them and you see something like
`highcharts-pointhighcharts-color-0`.

Or you see something like `highcharts-point highcharts-color-0foo` and then `point.update({ className: null })` has no effect.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/pie-basic
1. right click on the "Chrome" chart segment and "inspect"
2. notice the class attribute is OK, eg `highcharts-point highcharts-point-select highcharts-color-0`
3. left-click the "Chrome" segment
4. notice the class attribute has broken `highcharts-pointhighcharts-color-0`.

PS. same issue exists when I use `point.update({ className: 'foo' })` but I don't have a demo ready.

#### Product version
8.x

#### Affected browser(s)
All?

**Comment by sebastianbochan** [comment]
Hi @webdevan,
Thank you for reporting about the problem. 

Internal note:
Related with commit: https://github.com/highcharts/highcharts/commit/6c07e009422e3d0dee643c6283c81820e2213496 

We should not remove both spaces, so the problem is really simple in the Regexp.
