### ISSUE TITLE
Hover boundary issue for shared tooltips in 3D charts

### ISSUE THREAD

**Issue by terziani** [highcharts/highcharts#13592]
Tooltip type is set to "shared" in 3D bar, column, line charts.

#### Expected behaviour
Moving outside of the plot area (i.e. into the legend) would cause tooltips to fade out.

#### Actual behaviour
Hovering in the legend area persists the tooltip for the nearest data values, potentially blocking legend items.

#### Live demo with steps to reproduce
https://jsfiddle.net/vsab4qt1/2/

#### Product version
Highcharts JS v8.1.0 (2020-05-05)

#### Affected browser(s)
Reproduced on:
Chrome - Version 81.0.4044.138 (Official Build) (64-bit)
Firefox 75.0

**Comment by sebastianbochan** [comment]
Hi @telepsis,
Thank you for reporting. It looks like a problem with stickyTracking. Moreover the `enableMouseTracking` seems to be ignored and does not allow to disable it (when in plotOptions). In case of declaration in series, tooltip is ignored.

Demo:
- https://jsfiddle.net/BlackLabel/yu3q4sd6/

FYI @Izothep

**Comment by Izothep** [comment]
Thanks for report @telepsis!

**Internal Note:**
The issue in here is related to `isInsidePlot` method that is always returning true in case of 3D graphs. It is a known 3D graph limitation. I believe it should be possible to resolve the problem by:

a) changing `isInsidePlot`
b) recalculating plotArea so it will match the area after `perspective` method.
