### ISSUE TITLE
Timezone Problems in Gantt

### ISSUE THREAD

**Issue by algomia** [highcharts/highcharts#13591]
Timezone "Europe/Berlin" is set in Gantt chart.

#### Expected behaviour

1. Weekday indication shall be correct in all zoom levels
2. Conversion of time shall be correct

#### Actual behaviour

1. The weekday indication depends on the zoom level of the Gantt. In the reproduction scenario, look at week 23. If zoomed-out, week 23 has the weekdays SMTWTFS (incorrect for timezone Europe/Berlin), if zoomed-in, the week has the weekdays "Mon, 1. Jun", "Tue, 2. Jun", ..., "Sun, 7. Jun" (correct for timezone Europe/Berlin).

2. Consider the task with the id "SU-INTE-Input" in the scenario, which has the start-timestamp 1591048800000. The Gantt converts this to "Monday, 1 Jun", which is wrong for timezone Europe/Berlin. Verify here - https://www.andre-jochim.de/unix_timestamp_umrechnen.htm - that the timestamp 1591048800 maps to 2020-06-02 00:00:00 for timezone Europe/Berlin.

#### Live demo with steps to reproduce

http://jsfiddle.net/yf1Letjn/1/

#### Product version

Highcharts JS v8.1.0 (2020-05-05)
Highcharts Gantt JS v8.1.0 (2020-05-05)

//! moment.js
//! version : 2.26.0

//! moment-timezone.js
//! version : 0.5.31

#### Affected browser(s)

Reproduced on Firefox

**Comment by sebastianbochan** [comment]
Hi @algomia,
Thank you for reporting about the problem.

**Comment by karolkolodziej** [comment]
The second issue will be fixed by the #14141 PR.
