### ISSUE TITLE
Unclear docs: pointWidth for xRange changes the element height

### ISSUE THREAD

**Issue by marcellobarile** [highcharts/highcharts#13600]
#### Expected behaviour
pointWidth should not change the actual height of the xrange element.

#### Actual behaviour
pointWidth changes the element height.

#### Live demo with steps to reproduce
Go here and play around with the "pointWidth" option: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/x-range/ 

#### Product version
Highcharts

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @marcellobarile,
Thank you for reporting. The pointWidth param increases the width of column. When the chart is inverted, the param has influence on "height" which is natural, because of rotation.

Its not a bug, its a default functionality.

**Comment by marcellobarile** [comment]
hi @sebastianbochan,
in the Fiddle, which has been taken from the official documentation, I don't see any "inverted" configuration under the chart options... could you please further explain your point? Thanks in advance.

**Comment by KacperMadej** [comment]
The width is the dimension that is not based on the point value.

For xrange series - it's the vertical length.
For column series - it's the horizontal length.
For bar series (this is inverted column series) - it's the vertical length.
For xrange series in an inverted chart - it's the horizontal length - demo: https://jsfiddle.net/BlackLabel/2th3d6Lj/

I hope this clears things up, but if you have more questions or if anything is unclear, please ask.

**Comment by marcellobarile** [comment]
thanks @KacperMadej, your comment indeed clarifies the case.
I still think that the name (width) and some lack in the documentation can be misleading but, at least, I have a better vision of the current situation.

Enjoy the rest of the day.

**Comment by KacperMadej** [comment]
Resolved and closed through https://github.com/highcharts/highcharts/pull/13819
