### ISSUE TITLE
How to use category type and treegrid type together in highcharts gantt?

### ISSUE THREAD

**Issue by meysamm22** [highcharts/highcharts#13618]
I want to have a Gantt chart like the below picture with highcharts. Actually I want to category the tree grids in my Gantt chart. if the tree grids are toggled, the related category will be stretched. I would appreciate it if there is some feature to do this!

![bVP69](https://user-images.githubusercontent.com/13147196/83408031-29c9eb00-a427-11ea-94c8-ff8c440e33be.png)

**Comment by sebastianbochan** [comment]
Hi @meysamm22,
Thank you for the suggestion. Ideally the grid should support the filtering this kind of data and allow to add custom column.

Summarising: https://jsfiddle.net/BlackLabel/5doqn870/ should work.

**Comment by pawellysy** [comment]
unstale

**Comment by liaoyu1992** [comment]
Hello, I am implementing the same feature, I would like to ask how you implemented it

**Comment by liaoyu1992** [comment]
> Hi @meysamm22, Thank you for the suggestion. Ideally the grid should support the filtering this kind of data and allow to add custom column.
> 
> Summarising: https://jsfiddle.net/BlackLabel/5doqn870/ should work.

it is not working？

**Comment by psaltelk** [comment]
Was this feature implemented? I am also interested in using it. Thanks
