### ISSUE TITLE
Gantt chart color setting problem

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13613]
####
I can set the colors of two different color segments separately, such as the places marked on the picture
#### 
No such property was found

####
https://jshare.com.cn/temp/e9Gybi
![1111](https://user-images.githubusercontent.com/48822299/83374474-4f8eca00-a3fe-11ea-913d-22bc5e8bf50d.png)

**Comment by sebastianbochan** [comment]
Hi @weixingcai,
Thank you for reporting. The github is our bug tracker, so for general [support](http://www.highcharts.com/support) questions please use other channels like: forum / stackoverflow or email.

**Comment by weixingcai** [comment]
In my opinion, this problem, the document development does not have this property, and I did not set it, but there are two different colors, without the support of the property should be a bug

**Comment by pawelfus** [comment]
You can configure it @weixingcai , see docs:
- https://api.highcharts.com/gantt/series.gantt.partialFill
- https://api.highcharts.com/gantt/series.gantt.data.completed

Check our demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/gantt/demo/progress-indicator/

Let us know if we are missing something. Thanks!
