### ISSUE TITLE
Typescript types problems inside options charts.

### ISSUE THREAD

**Issue by NicolasZim** [highcharts/highcharts#13619]
Hi there, i'm facing many issues using Typescript and highcharts in the options of the charts. It's like highcharts is missing some **types**. In this post i will report the `tooltip formatter` **function** using **this**.
#### Expected behaviour
Access all data inside **this** with all types inside it.
#### Actual behaviour
Can't access all data because typescript doesn't recognize types. Example: `this.series.userOptions` in grouped stakced column.
#### Live demo with steps to reproduce
**Template**: https://stackblitz.com/edit/grouped-stacked-column-highcharts-done?file=Chart.tsx
**Highcharts Support Forum**: https://www.highcharts.com/forum/viewtopic.php?f=9&t=44046&p=155905#p155905

For reproduce you simply create a project with typescript and highcharts(In this case React too) and create an component to built the options for you. 
In options it's quite hard to build function for process data for you. As an example, if you want an function to return an series of array objects you will need know specefic types of what are you doing to make them work togheter(the options.series and the function). That would be massive since series has so many types. ( You can see it [here](http://prntscr.com/srrkow) )
#### Product version
highcharts: 8.1.0
highcharts-react-official: 3.0.0
#### Affected browser(s)
Any.
#### Conclusion
That's not the first time i'm facing this and changing the typescript file isn't the smartest thing to do. Since if you change your enviorement and delete node_modules you will lost and possibly forget what  you changed and where you changed it until you face the problem and solve him again. Also, highcharts don't have any instructions or simple examples to how use typescript with highcharts.
**Examples:**
- How to extend an type
- How to find an type from an object. (like wich type use inside **series**?!)
- How to fix an type thats creating error types. (Needs the above example as a solution)

However the typescript files it's readable, i solved some problems by reading the code and searching a little bit. It would be easier to solve them if there are any tutorials or simple examples with typescript. As [here](https://www.highcharts.com/forum/viewtopic.php?f=9&t=44038&p=155854#p155854) i has another problem with another part of options but a similar problem that i need to understand the types for build an solution. This other problem it's related to this new feature request #13606

**Comment by sebastianbochan** [comment]
Hi @NicolasZim,
Thank you for reporting.

FYI @bre1470

**Comment by bre1470** [comment]
Hello @NicolasZim ,

Highcharts declarations only contain the officially supported members from our class reference: https://api.highcharts.com/class-reference/

Usage of TypeScript is described in our general documentation: https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-declarations#extending-highcharts-in-typescript

In your case you would extend it like this:
```ts
declare module 'highcharts' {
    interface Series {
        userOptions: Partial<Highcharts.SeriesOptionsType>;
    }
}
```

**Comment by bre1470** [comment]
We will add `Series.userOptions` to the official documentation and declarations.

**Comment by bre1470** [comment]
I do not believe, that you necessarily have to wait for the changes in the declarations as it is a type issue and not something on implementation side. The simplest workaround would be to do something like `(series as any).userOptions` in the meantime.
