### ISSUE TITLE
Chart series not properly visible if I resize and toggle data labels continuously (3 to 4 times)

### ISSUE THREAD

**Issue by burgala** [highcharts/highcharts#13616]
I have a datalables on/off and window width reduce based on some button clicks. When I click these buttons one after one continuously (3 to 4 times), at one point Chart series disturbing

#### Expected behaviour
Chart should be plotted with series

#### Actual behaviour
Chart series disturbed

#### Live demo with steps to reproduce
http://jsfiddle.net/vcrd3fp8/3/

#### Product version
I am using 6.1.0 but reproducible in latest also

**Comment by sebastianbochan** [comment]
Hi @burgala,
Thank you for reporting.

Do you mean that a datalabel is missing or "overlap" the bar like below?

<img width="298" alt="Zrzut ekranu 2020-06-1 o 14 03 19" src="https://user-images.githubusercontent.com/2115686/83407295-b7e6a700-a410-11ea-9da8-0c31b91ec783.png">

**Comment by burgala** [comment]
Hi @sebastianbochan, 

Please have a look into below screenshot, series is not plotted as expected (Highlighted in yellow)

<img width="462" alt="chat_series" src="https://user-images.githubusercontent.com/66246084/83407719-f5f2c380-a42e-11ea-8d6d-8d5aa69459e2.PNG">

**Comment by sebastianbochan** [comment]
Hi @burgala,
Could you share your browser and OS details? Being honest, I was not able to reproduce this issue.

**Comment by burgala** [comment]
Hi @sebastianbochan,
I don't know why it is not reproducible at your end. From Highcharts support team, @wchmiel redirected me here to raise issue, he experienced same.

Browser
Google Chrome
Version 83.0.4103.61 (Official Build) (32-bit)

OS
Windows 10 Enterprise 1709 64-bit

**Comment by sebastianbochan** [comment]
Hi @burgala,
After consultation and clip which you attached there, I was able to reproduce it.

Steps:
![labels](https://user-images.githubusercontent.com/2115686/83499828-436a4180-a4be-11ea-9e0c-24fefe7fadb5.gif)

**Comment by pawelfus** [comment]
*Internal note:*
In DOM we can observe duplicated clip paths (probably 2x for dataLabels and 2x for rectangles). This shouldn't happen, probably cached key is wrong.

**Comment by khlieng** [comment]
Fixed since 8.2.2 (#14258).
