### ISSUE TITLE
Heatmap - cropThreshold doesn't work

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13615]
#### Expected behaviour
The series should be cropped, like in this example (column series):
http://jsfiddle.net/BlackLabel/8sr1hw5z/

According to the API, it should be possible: https://api.highcharts.com/highcharts/plotOptions.heatmap.cropThreshold

#### Actual behaviour
The series is not cropped.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/x4Lpvnc3/

It might be also the API bug, forced cropThreshold doesn't work well on the Heatmap:
https://jsfiddle.net/BlackLabel/x4Lpvnc3/1/

#### Product version
8.1.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
It's a bug in docs - there's no cropping mechanism when data can be unsorted (we can accidentally remove point that are within the visible range).

**Comment by bre1470** [comment]
@pawelfus 
So `cropThreshold ` will not work for Heatmap series and therefor has to be excluded?

**Comment by pawelfus** [comment]
That's correct. The same applies to other series with `requireSorting=false` (e.g. scatter). I'm not sure about non-cartesian series though (e.g. pie, sankey etc) - probably the same, but I would check this first in `cropData()`.
