### ISSUE TITLE
Labels disapper when serie is hide (navigator disabled)

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1362]
To reproduce: 
1. click the "USD to EUR" label to hide the line
2. change the range selector to "2w" from "6m"
3. click the "USD to EUR" label to show the line again

http://jsfiddle.net/KZeas/

**Comment by pawelfus** [comment]
Looks like actual version prevents from clicking on buttons, when we don't display at least one series. As of Highstock 2.1.6
