### ISSUE TITLE
time.useUTC spoils the bar of chart

### ISSUE THREAD

**Issue by urvesh86** [highcharts/highcharts#13622]
We are using highchart api to stencil framework web component. Below are the code snippet of render method.
```
render() {
    Highcharts.setOptions({
      time: {
        useUTC: false
      }
    });
    Highcharts.stockChart('container', varChartOptions);
  }
```
We observed that when new series is added to the chart, volume bar of the chart is distorted. 
This issue is only produced when _useUTC_ flag is set to false. 

I am not sure whether I have explained understandable or not. 

Thanking you in advance for your support.

![ezgif com-crop](https://user-images.githubusercontent.com/64583343/83484665-57ea1200-a49d-11ea-8e39-ea64d6118a44.gif)

#### Product version
8.1.0

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @urvesh86,
Thank you for reporting. The github is our bug tracker, so for general support questions please use forum / stackoverflow or email.

ps. During the contact share a live demo, please
