### ISSUE TITLE
highcharts和map.js结合，无数据缩小后纯白

### ISSUE THREAD

**Issue by 1713735544** [highcharts/highcharts#13626]
After combining the two, when the data is empty, after I zoom in to white, the zoom back will become pure white and cannot be displayed
两者结合后，当数据是空时，我放大到白色之后，缩放回来会变成纯白，无法正常显示

**Comment by sebastianbochan** [comment]
Hi,
Unfortunately our tech-support use only English / Norwegian or Polish language. Please use one of them for the contact.

**Comment by pawelfus** [comment]
I'm afraid that's not enough information @1713735544 - could you please first contact our support team? Thank you.

Link to support: https://www.highcharts.com/blog/support/ (see "Contact us directly" card)
