### ISSUE TITLE
Offline exporting - Edge - points out of plot area are visible

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#13620]
#### Actual behaviour
After zooming, the points that are out of the plot area are still visible on the exported image.
The issue occurs only with **offline** exporting in the **Edge** browser.

![Edge offline exporting issue](https://user-images.githubusercontent.com/23310742/83426830-0e171280-a430-11ea-96e3-004169aa5d3a.PNG)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/na5dhm1v/

#### Product version
Highcharts 8.1.0

#### Affected browser(s)
Edge 44.18362.449.0
EdgeHTML 18.18363

**Comment by sebastianbochan** [comment]
FYI @oysteinmoseng

**Comment by alozickiSV** [comment]
Hi, 
   We raised this bug
   Do you have any advance or ETA on this, will be included in the next version?
Thanks in advance

**Comment by oysteinmoseng** [comment]
@alozickiSV We are looking into this ASAP

**Comment by raf18seb** [comment]
Internal notes:

*   issue occurs only in Edge Legacy (based on EdgeHTML). Works fine on new Edge (Chromium).
*   SVG is exported correctly, so we can't easily check SVG. Issue occurs only when exporting to PNG/JPEG

**Comment by alozickiSV** [comment]
Are you including this in your next release? What are the next steps?

**Comment by oysteinmoseng** [comment]
@alozickiSV This is likely a browser bug with the old version of Edge. With the latest Windows updates, all users of Edge are now pushed to the new Edge Chromium, where this bug does not appear. Will this still be an issue for you and your use case?

**Comment by alozickiSV** [comment]
Our user base is extensive, and Edge legacy version is the default browser for many users. We don't have a timeline for shifting to chromium. So, yes, this is an issue for us. Is there a plan/ ETA to fix this for edge legacy in future ?

**Comment by oysteinmoseng** [comment]
@alozickiSV We will take a look and see if there is anything we can do

**Comment by oysteinmoseng** [comment]
@alozickiSV After investigating further, this seems to be an issue with the particular Edge browser version where it fails at correctly rendering an SVG image object to canvas. The image is created correctly, and can be displayed correctly in the browser, but once it is rendered to canvas and converted to PNG/JPEG it fails.

I would have to recommend disabling offline exporting (or alternatively [install your own version](https://www.highcharts.com/docs/export-module/setting-up-the-server) of our export server if e.g. security is an issue) until you have a chance to update users to a newer version of Edge, as there unfortunately does not seem to be much we can do from our side.
