### ISSUE TITLE
Number appears in the chart legend after clicking on one of legend items

### ISSUE THREAD

**Issue by BognaMrx** [highcharts/highcharts#13632]
Expected behaviour: 
Number (-1)shouldn't appears after clicking on of legend items.
Actual Result:
Number (-1) appears in the chart legend: https://monosnap.com/file/S8Fwi7EIoLEnDCVu5BjR4IsQGFfjFJ

Steps to reproduce:
Click one of  items on chart legend

Product version:
Highcharts version: 8.1.0

Environment:
Safari, Firefox 76.0.1 on MacOS

**Comment by sebastianbochan** [comment]
Hi @BognaMrx,
Thank you for reporting. Could you share simplified your live demo? It will allow us to verify your chart's configuration and debug. From the clip its really difficult to debug and predict your data/charts options.

ps. You can declare min and max values on xAxis.
Docs:
- https://api.highcharts.com/highcharts/xAxis

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
