### ISSUE TITLE
Translate function does not return reliable results.

### ISSUE THREAD

**Issue by styks1987** [highcharts/highcharts#1364]
Please see:

http://jsfiddle.net/styks1987/w9wCz/3/
- Move the slider and observe the console.
- On afterSetExtremes we call a shift_tools function that translates a point to a coordinate and then back to a point. Then we subtract the two points and see if they match. As you can see the values do not line up.
  - We are seeing major descrepencies when the chart is zoomed in closely.
  - Reproduce by:
    - Load the url above, change the date range to be within 5 days or so.
    - Notice the x value difference is rather large. It ranges but I have seen values in difference of ~45 hours or ~26 hours

How I found this:

http://jsfiddle.net/styks1987/w9wCz/1/

I am trying to reliably re-plot a line every time the chart moves. This is the closest solution I could come up with, but it also fails at very small points or at obscure times.

Thank you for such a great tool and I look forward to your reply.

**Comment by oysteinmoseng** [comment]
Closing as no longer seems to be an issue, feel free to reopen if it is
