### ISSUE TITLE
In mobile view, legendItem click throws an error when accessibility module is attached

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#13641]
#### Actual behaviour

In a mobile view, the legend is not working and the error is shown in the console:  
`Uncaught TypeError: Cannot read property 'length' of undefined`  
The error occurs only with `accessibility` module attached.

#### Live demo with steps to reproduce

Open demo in a mobile view (in a developer console choice a responsive view) and click the legendItem  
https://jsfiddle.net/BlackLabel/xay13q6v

#### Product version

Highcharts 8.1.0

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
Internal note: The cloned event is always a MouseEvent, even when it should be a TouchEvent.
