### ISSUE TITLE
yAxis.stops type

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13652]
#### Expected behaviour
According to the API 
> The stops is an array of tuples, where the first item is a float between 0 and 1 assigning the relative position in the gradient, and the second item is the color.

I would expect that the following config will match the type of the `yAxis.stops`

```javascript
stops: [
          [
            0.5,
            {
              linearGradient: {
                x1: 0,
                x2: 1,
                y1: 0,
                y2: 0
              },
              stops: [[0.1, "#7bbb1d"], [0.9, "#f8df14"]]
            }
          ],
          [
            0.9,
            {
              linearGradient: {
                x1: 0,
                x2: 1,
                y1: 0,
                y2: 0
              },
              stops: [[0.1, "#7bbb1d"], [0.5, "#f8df14"], [0.9, "#f84f42"]]
            }
          ]
        ]
```

It looks like Highcharts expects the second item of the array to be a `string` (`Highcharts.ColorString` ), it should accept `Highcharts.GradientColorObject` too.

#### Actual behaviour

```typescript
Type '{ linearGradient: { x1: number; x2: number; y1: number; y2: number; }; stops: (string | number)[][]; }' is not assignable to type 'string'.
```
#### Workaround

cast entire yAxis options to the `Highcharts.YAxisOptions`

#### Live demo with steps to reproduce
https://stackblitz.com/edit/angular-ivy-j7xtuj?embed=1&file=src/app/chart/chart.component.ts

#### Product version
8.1.0

#### Affected browser(s)
All

**Comment by bre1470** [comment]
So you like to see that gradient stops accept gradients?

**Comment by mateuszkornecki** [comment]
Yes, especially since it is possible in the vanilla JS.

https://stackblitz.com/edit/angular-ivy-dg5jhy
