### ISSUE TITLE
chart.map type

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13651]
#### Expected behaviour
`chart.map` property should accept JSON imported from official map collection ('@highcharts/map-collection/custom/world.geo.json').

#### Actual behaviour
```typescript
Type 'typeof import("*.json")' is not assignable to type 'string | any[]'.
Type 'typeof import("*.json")' is missing the following properties from type 'any[]': length, pop, push, concat, and 25 more.
```

#### Live demo with steps to reproduce
https://stackblitz.com/edit/highcharts-angular-map-drjs4y

#### Workaround
cast imported map to the `any`

#### Product version
8.1.0

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
FYI @bre1470

**Comment by bre1470** [comment]
The proper workaround looks similar to this:
```ts
{
  chart: {
    map: H.geojson(worldMap)
  }
}
```
