### ISSUE TITLE
annotations - measure - multiple yAxis

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#13664]
#### Expected behaviour

The measure annotation should have been added like in case of assigning it to the first axis. Demo: https://jsfiddle.net/BlackLabel/64xr3sb0/

#### Actual behaviour

The measure annotation doesn't add to the second axis. Works fine when the `selectType` option is set to `xy`. 

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/pfectnb0/

#### Product version

Highcharts JS v8.1.0 (2020-05-05)

**Comment by pawelfus** [comment]
FYI @sebastianbochan

**Comment by sebastianbochan** [comment]
Its duplicate of https://github.com/highcharts/highcharts/issues/12268

**Comment by hasnain095** [comment]
Hi, any update on this bug?

**Comment by sebastianbochan** [comment]
Hi @hasnain095,
At this moment we do not have ETA for this ticket, but will try to debug as soon as possible.

**Comment by hasnain095** [comment]
I would really appreciate it if this pull-request is approved asap. Thanks.

**Comment by hasnain095** [comment]
Guys, I don't think it's fixed. Please check the demo below

https://jsfiddle.net/BlackLabel/pfectnb0/

The measure X is not visible on the second yAxis

**Comment by pawelfus** [comment]
Hi @hasnain095 - it's fixed on the master branch, take a look: https://jsfiddle.net/BlackLabel/pfectnb0/2/ - fix will be included in the next release (within a few weeks).

**Comment by hasnain095** [comment]
Thank you @pawelfus
