### ISSUE TITLE
Time.timezoneOffset - initial value shows bad options handling

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#13670]
#### Expected behaviour
Updating of timezoneOffset (check first point tooltip):
https://jsfiddle.net/BlackLabel/g3an1qrk/

#### Actual behaviour
However, if you set timezoneOffset for the initial options - the chart is not updating correctly.
https://jsfiddle.net/BlackLabel/g3an1qrk/1/

#### Product version
8.1.0

#### Debugging details
clearRecusively in chart update compares against options that are not reflecting current chart options and the initial value is picked up on every update

**Comment by khlieng** [comment]
Fixed since 8.2.2 (#14263).
