### ISSUE TITLE
Inverting timeline results in incorrect label positioning

### ISSUE THREAD

**Issue by epfromer** [highcharts/highcharts#13671]
#### Expected behaviour
When chart.inverted changed, labels are in proper order/position.

#### Actual behaviour
Labels are out of order.

#### Live demo with steps to reproduce
https://codepen.io/epfromer/pen/abdvEyY/ 
- Click on invert button to toggle

#### Product version
8.1.0 

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting @epfromer 

Could you check it @Denyllon ? It looks like initial rendering is always good, but on `update()` something does not change (anchor? alignment?).

**Comment by epfromer** [comment]
Looks like this has been fixed, thanks.

**Comment by Denyllon** [comment]
Hi @epfromer,

I see that has not been fixed (also on `master`). Could you tell us what makes you think that is already repaired?

JSFiddle example: https://jsfiddle.net/BlackLabel/zcnju2e7/

**Comment by epfromer** [comment]
Apologies- I did a quick look in a local app and thought it was fixed.  I was wrong.
