### ISSUE TITLE
Missing fix for #13541 in changelog v8.1.1

### ISSUE THREAD

**Issue by LoganDupont** [highcharts/highcharts#13685]
The [changelog v8.1.1](https://www.highcharts.com/blog/changelog/#highcharts-v8.1.1) doesn't mention that there was a fix for #13541. Is it possible to check if this was also released and add it to the changelog?

**Comment by sebastianbochan** [comment]
Hi @LoganDupont,
Thank you for reporting. We will try to fix it as soon as possible.

FYI @TorsteinHonsi
