### ISSUE TITLE
`Highcharts is not defined` when importing the data-module via es-modules

### ISSUE THREAD

**Issue by goransle** [highcharts/highcharts#13681]
## Expected behaviour
Import working as with previous version

#### Actual behaviour
Error `Highcharts is not defined` when importing the data-module via es-modules with the new release. Both from CDN and highcharts-dist. 

#### Live demo with steps to reproduce
https://jsfiddle.net/b8957rsd/14/

#### Product version
Highcharts 8.1.1

**Comment by goransle** [comment]
FYI @bre1470 @TorsteinHonsi

**Comment by bre1470** [comment]
It looks like a merge restored some removed reference.

**Comment by bolatovumar** [comment]
I'm still getting the same error when using version `8.1.2`.

<img width="764" alt="Screen Shot 2020-06-25 at 12 04 25 PM" src="https://user-images.githubusercontent.com/1934678/85783588-4f6faa80-b6dc-11ea-85ac-ac5ac6b783ea.png">

**Comment by pawelfus** [comment]
Hi @bolatovumar - issue has been fixed and will be part of the next release (within a few weeks).

**Comment by bolatovumar** [comment]
@pawelfus ok, thanks for letting me know.
