### ISSUE TITLE
Property value of highcharts.d.ts AxisLabelsFormatterContextObject has only type number

### ISSUE THREAD

**Issue by LoganDupont** [highcharts/highcharts#13689]
#### Expected behaviour
AxisLabelsFormatterContextObject should contain property "value" of type number | string. 
Sometimes we have string labels on the x-axis. ex. http://jsfiddle.net/tDSrd/310/

#### Actual behaviour
AxisLabelsFormatterContextObject contains property "value" of type number

**Comment by bre1470** [comment]
Is there a practical problem that makes the change necessary? It will break most use cases and current implementations, if it becomes a union type, so I oppose a fix.

**Comment by LoganDupont** [comment]
Well, I am using the `XAxisLabelsOptions.formatter` which expects `Highcharts.FormatterCallbackFunction<Highcharts.AxisLabelsFormatterContextObject>`. The callback function should return a value of type `string`. Due the fact that the `AxisLabelsFormatterContextObject.value` is of type `number`, I have to transform the `value` property to a string in order to avoid typescript compile errors.

```
          formatter: ((params: Highcharts.AxisLabelsFormatterContextObject) => {
            return params.value.toString().includes('vs.')
              ? params.value.toString().replace('vs.', '<br/>vs.<br/>')
              : params.value.toString();
          }) as Highcharts.FormatterCallbackFunction<
            Highcharts.AxisLabelsFormatterContextObject
          >,
```

**Comment by bre1470** [comment]
@LoganDupont Thank you for the example. I have an idea how to cover all needs.
