### ISSUE TITLE
Missing fix XSS in changelog v8.1.1

### ISSUE THREAD

**Issue by LoganDupont** [highcharts/highcharts#13687]
NPM warned me that all Versions of highcharts prior to 8.1.1 are vulnerable to Cross-Site Scripting (XSS). See https://www.npmjs.com/advisories/1227. But in the changelog there is nothing that mentions this vulnerability has been fixed.

**Comment by sebastianbochan** [comment]
Hi @LoganDupont,
Thank you for reporting. We will try to fix it as soon as possible.

FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
@LoganDupont The XSS issue is fixed, but we failed to add it in the changelog. Will do so ASAP.
