### ISSUE TITLE
Bug: referencing global variable `Highcharts` 

### ISSUE THREAD

**Issue by AngusFu** [highcharts/highcharts#13684]
#### Expected behaviour
Works fine with webpack bundling.

#### Actual behaviour

![image](https://user-images.githubusercontent.com/8180186/84217758-95831680-aaff-11ea-840b-6ae37e6a5a15.png)

I found TWO  places using the global `Highcharts` directly. The screenshot below is from a prettified version of `highcharts@v8.1.1` from unpkg.com  ——

![image](https://user-images.githubusercontent.com/8180186/84217903-e85cce00-aaff-11ea-830a-5f8de6ead2c2.png)
![image](https://user-images.githubusercontent.com/8180186/84217932-f90d4400-aaff-11ea-8557-ecae7c0f84c2.png)

#### Product version

v8.1.1

#### Affected browser(s)

All

**Comment by sebastianbochan** [comment]
Hi @AngusFu,
Thank the reporting. Its known bug which has been already reported here: https://github.com/highcharts/highcharts/issues/13684.

Im closing as duplicate.
