### ISSUE TITLE
Error: <rect> attribute height: Expected length, "NaN".

### ISSUE THREAD

**Issue by dslinnard** [highcharts/highcharts#13680]
#### Expected behaviour
Chart renders without error

#### Actual behaviour
Error: <rect> attribute height: Expected length, "NaN".

#### Live demo with steps to reproduce
http://www.kpfp.org/index.php?module=indicators&controller=index&action=socioneeds

and observe console log
#### Product version

v8.1.1.  works fine with v8.1.0
#### Affected browser(s)
Firefox, Chrome

**Comment by sebastianbochan** [comment]
Hi @dslinnard,
Thank you for reporting. When I run the demo, I am not able to reproduce the problem. Could you share your OS and browser details (including a full number of version) ?

**Comment by dslinnard** [comment]
Ah sorry we reverted to v8.1.0 on the above link as this was one of live sites and it needed to be fixed. OS would have been the latest Mac OS 10.15.4 with Chrome version 83.0.4103.61. 

So in short I'm not sure how we can recreate the issue at the moment. By the way this was seen by numerous people, not just me. If I can come up with a fiddle I will do.

**Comment by anajavi** [comment]
Here's a reproduction of this problem:
https://jsfiddle.net/hkof4dmL/2/

Without setSize, the code works. With Highcharts 8.1.0 the code also works.

With 8.1.1 the real browser console shows:
```
Error: attribute height: Expected length, "NaN".
```

**Comment by sebastianbochan** [comment]
Hi @anajavi,
Thank you for details. Its a regression.

_Internal note_
Bisect leads me to https://github.com/highcharts/highcharts/commit/57ce06ee444abb7b9c5e962c68dc6f5f831b64ae

@TorsteinHonsi
