### ISSUE TITLE
Legend is missing the last page

### ISSUE THREAD

**Issue by ktakahashimtb** [highcharts/highcharts#13683]
#### Expected behaviour
Legend has the 7th page containing series 97 to 100. (in the attached JSFiddle case) 

#### Actual behaviour
Legend does not have the 7th page.

#### Live demo with steps to reproduce
https://jsfiddle.net/ktakahashimtb/shLpjcqb/

** Might need to open it on Windows to see the issue **

This issue seems to happen only when a legend has N x N arrangement of the items. 
In this example, the container element is sized so that the legend has 4 x 4 items on a page.

In addition, setting maxHeight seems to be a necessary ingredient.

#### Product version
Highcharts v8.1.1 (to at least v 7.2.0)

#### Affected browser(s)
Chrome, Edge, Firefox (on Windows)
(could not reproduce this on MacBook - Chrome and Safari)

**Comment by raf18seb** [comment]
Hi @[ktakahashimtb](https://github.com/ktakahashimtb) and thank you for reporting the issue.

Looks like a regression after 0cc353e, related ticket: #2617

As a workaround for now, you can undone above commit changes: https://jsfiddle.net/BlackLabel/8odaexqf/

The issue occurs on Windows (tested on Chrome, FF, Edge).

**Comment by raf18seb** [comment]
FYI @TorsteinHonsi

**Comment by karolkolodziej** [comment]
It looks like this issue only occurs only on Windows, I was not able to recreate that on mac.
Tested on:
macOS Catalina, Chrom Version 87.0.4280.67 (Official Build) (x86_64)- 5 legend pages and I can see all items
macOS Big Sur, Chrom Version 87.0.4280.67 (Official Build) (x86_64)- 6 legend pages and all item visible.

**Comment by KacperMadej** [comment]
Another demo with the last line cut in half: https://jsfiddle.net/BlackLabel/d4nrx7zp/
(Win10/Chrome)
