### ISSUE TITLE
PlotColumnDataLabelsOptions.y should be a number

### ISSUE THREAD

**Issue by Den-dp** [highcharts/highcharts#13699]
#### Expected behaviour
`y` in `dataLabels` (PlotColumnDataLabelsOptions) https://api.highcharts.com/highcharts/plotOptions.column.dataLabels.y should be declared as a number in typescript definitions.

#### Actual behaviour
Compile-time error for any numeric `y`:
Type 'number' is not assignable to type 'string'.

#### Live demo with steps to reproduce
Can be reproduced in WebStorm or VSCode
```
> npm i typescript@3 highcharts@8
> echo "import * as Higcharts from 'highcharts';Higcharts.chart({plotOptions: {column: {dataLabels: {y: 0}}}})" > app.ts
> npx tsc app.ts
app.ts:7:17 - error TS2322: Type 'number' is not assignable to type 'string'.

7                 y: 0
                  ~
```

#### Product version
Highcharts 8.1.1

**Comment by sebastianbochan** [comment]
Hi @Den-dp,
Thank you for reporting.

FYI @bre1470
