### ISSUE TITLE
updated points not visible with highstock

### ISSUE THREAD

**Issue by smokir** [highcharts/highcharts#13697]
#### Expected behaviour

Correct points visibility with Highstock when updating points with point.update for first render and setExtremes

#### Actual behaviour

[256 points](https://yadi.sk/i/ZerrTcFZpbYq1Q) - visible points on start only on specific width or after moving navigator

[800 points](https://yadi.sk/i/0Vmr_-NdCjGuUw) - visible points on start, no points on moving navigator

#### Live demo with steps to reproduce

https://jsfiddle.net/ytr4vbmL/

#### Product version

Highstock 8.1.1

#### Affected browser(s)

Safari 13.0.2, Firefox 76.0.1, Chrome 81.0.4044.96

**Comment by sebastianbochan** [comment]
Hi @smokir,
Thank you for reporting. Highstock uses [dataGrouping](https://api.highcharts.com/highstock/series.line.dataGrouping) option by default. The solution increases the performance of charts with a lot of points. You can disable it by the [`dataGrouping.enabled`](https://api.highcharts.com/highstock/series.line.dataGrouping.enabled) param.
