### ISSUE TITLE
Keyboard navigation does not behave as expected when using tabIndex

### ISSUE THREAD

**Issue by dcaley** [highcharts/highcharts#13698]
#### Expected behaviour
When navigating a page with explicit tabIndices via keyboard ("tabbing") I expect that after a chart gains keyboard focus, I can continue to hit tab, and focus will move to the element with the next sequential tabIndex.

#### Actual behaviour
When a chart has focus, and we have tabbed through all of the focusable portions of the chart, hitting tab will not move focus to the next expected element.

#### Live demo with steps to reproduce
https://jsfiddle.net/y60ev8t5/

Steps:
1. Click the first textbox (tabIndex==1) to give it focus.
2. Hit the tab key once to give the chart (tabIndex==2) focus
3. Continue hitting tab to move through the focusable chart sections, in this case the pie itself, and the menu.
4. Once we have tabbed through these sections, hit tab again, with the expectation that the second textbox (tabIndex==3) will gain focus.  It never does.

#### Product version
Highcharts JS v8.1.1

#### Affected browser(s)
Tested and reproduced in both firefox latest and chrome latest.

**Comment by sebastianbochan** [comment]
Hi @dancek,
Thank you for reporting.

FYI @oysteinmoseng
