### ISSUE TITLE
How to add plugins(contour) in vue

### ISSUE THREAD

**Issue by dharmatv** [highcharts/highcharts#13706]
We have tried following ways in vue to display contour chart.

1. Included CDN in index.html, shows following screenshot 
https://snipboard.io/5pLyeV.jpg
2. Tried a require function also
3. append link dynamically to head tag

But getting errors like show the following screenshot
https://snipboard.io/Ah65So.jpg

Could u please anyone provide any other way to do for this issue

**Comment by sebastianbochan** [comment]
Hi @dharmatv,
Thank you for contacting us. The github is our bug tracker, so for genera [support](https://www.highcharts.com/support) questions please use forum / stackoverflow or forum.
