### ISSUE TITLE
Sankey graph deformation on div resize when using data with a -> a pattern 

### ISSUE THREAD

**Issue by romanbitca** [highcharts/highcharts#13705]
#### Expected behaviour
Smooth graph redraw.

#### Actual behaviour
A part of graph is deformed and alighted to right.
GIF demo included. 
![ScreenFlow](https://user-images.githubusercontent.com/15247287/84512203-49d39700-acd0-11ea-9191-2894ba561921.gif)

#### Function used to redraw
`resize () {
      const { sankey } = this.$refs
      if (sankey) {
        clearTimeout(this.timeoutID)
        this.timeoutID = setTimeout(() => {
          sankey.chart.setSize(null)
          sankey.chart.redraw()
        }, 200)
      }
    }`

#### Product version
"highcharts": "^7.1.2",
"highcharts-vue": "^1.3.5",

#### Affected browser(s)
All browsers.
Gif demo is recorded on Chrome.

**Comment by sebastianbochan** [comment]
Hi @romanbitca,
Thank you for reporting. Could you share a live demo of your chart? It will allow us to reproduce and debug the problem.

**Comment by romanbitca** [comment]
Here it is:
https://codesandbox.io/s/eloquent-chaplygin-y3hqz?file=/src/App.vue

Try slowly to resize the sandbox windows.

**Comment by pawelfus** [comment]
Thank you for the demo @romanbitca 

**Simplified demo:**
https://jsfiddle.net/BlackLabel/19d7jrbo/

This is caused by self-referencing node:
```js
      [
        31252,
        31252,
        199204
      ],
```

When removed - works fine.

**Comment by romanbitca** [comment]
We know that self-referencing node produces this bug. And I need to display this ‘loop’.
Any solution?

**Comment by pawelfus** [comment]
I think there is a workaround you cna try to implement, while this bug is open: set fixed column

Just realized that issue was wrongly tagged - fixed.

Simplified demo: https://jsfiddle.net/BlackLabel/tdymnhvj/1/
Simplified demo with workaround: https://jsfiddle.net/BlackLabel/tdymnhvj/2/

**Comment by romanbitca** [comment]
Ok, thank you.
Waiting for bug fix.
