### ISSUE TITLE
H.keys doesn't work

### ISSUE THREAD

**Issue by paulo-raca** [highcharts/highcharts#13708]
#### Expected behaviour
`H.keys()` should work just as `Object.keys()`:

#### Actual behaviour
```
Object.keys({"foo":"bar"})
["foo"]

Highcharts.keys({"foo":"bar"})
Highcharts error #32: www.highcharts.com/errors/32/?Highcharts.keys=Object.keys
Highcharts.keys: Object.keys
highcharts.src.js:2026 Uncaught TypeError: Cannot convert undefined or null to object
    at Arguments.keys (<anonymous>)
    at Object.H.keys (highcharts.src.js:2026)
```

#### Live demo with steps to reproduce
https://jsfiddle.net/j4aq97ds/

Just run, you'll the output from Object.keys() and the error from Highchart.keys()

#### Product version
Highcharts 8.1.1 

#### Affected browser(s)
Tested on Chrome, probably affects all browsers

**Comment by paulo-raca** [comment]
I briefly looked into the code to see if I could send a PR, and the source is simply:

```
/**
 * Returns an array of a given object's own properties.
 *
 * @function Highcharts.keys
 * @deprecated
 *
 * @param {*} obj
 *        The object of which the properties are to be returned.
 *
 * @return {Array<string>}
 *         An array of strings that represents all the properties.
 */
H.keys = Object.keys;
```

However some compilation magic transforms it into

```
        H.keys = function () {
            error(32, false, void 0, { 'Highcharts.keys': 'Object.keys' });
            return Object.keys.apply(arguments);
        };
```

I'm not sure how this magic happens, but this should be `return Object.keys.apply(null, arguments);`

**Comment by sebastianbochan** [comment]
Hi @paulo-raca,
Thank you for reporting.

_Internal note_
Looks like the problem with `inArray` here: https://github.com/highcharts/highcharts/issues/9225

**Comment by TorsteinHonsi** [comment]
It comes from this commit:

https://github.com/highcharts/highcharts/commit/44ccd59d048cd5929672100d7cf84e5ecd8924f3#diff-4902869e857fed10664dc3f6cb635c92R1952-R1955

> some compilation magic

@paulo-raca Probably your source is outdated.

**Comment by paulo-raca** [comment]
Thanks!
