### ISSUE TITLE
setState doesn't apply after redraw

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#13719]
#### Expected behaviour

Should work as in the previous version - the state set by using the `setState` feature should be applied after the redraw call. 

Demo: https://jsfiddle.net/BlackLabel/qha91tpm/

#### Actual behaviour

After the redraw call, the `setState` feature doesn't affect the chart. 

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/38wxhmpb/ (resize the window to call the redraw)

#### Product version

Highcharts JS v8.1.1 (2020-06-09)

**Comment by pawelfus** [comment]
Bisected to commit dd0703b73f

**Workaround:**
Plugin:
```js
(function(H) {
  H.wrap(
    H.Series.prototype,
    'plotGroup',
    function(proceed, prop, name, visibility, zIndex, parent) {
      var op = this.opacity;

      if (this.state) {
        delete this.opacity;
      }

      var ret = proceed.call(this, prop, name, visibility, zIndex, parent);

      this.opacity = op;

      return ret;
    }
  );
})(Highcharts);
```

Demo: https://jsfiddle.net/BlackLabel/7k1j8gxz/2/
