### ISSUE TITLE
Line chart is not getting focused when we do shift+tab

### ISSUE THREAD

**Issue by GayatriDeviP** [highcharts/highcharts#13729]
#### Expected behaviour
Line chart should get focus when we do shift+tab.

#### Actual behaviour
Line chart is not getting focused when we do shift+tab

#### Live demo with steps to reproduce
step1: open https://jsfiddle.net/4wqy1h2L/1/
step2: there is a "btn1", "line chart" and "btn2" in output window. Navigate using tab.
step3: chart is getting focused when we  use tab.
step4: from "btn2", navigate back to chart using shift+tab. chart is not getting focused and if we do again shift+tab, focus is going to "btn1"

#### Product version
Latest. 8.1.1

#### Affected browser(s)
chrome, edge.

**Comment by pawelfus** [comment]
Thank you for reporting the issue @GayatriDeviP 

It seems that focus is correct (after shift+tab from "btn2", push arrow-down button, first point in the chart will get focus) - just the border is missing.

FYI @oysteinmoseng

**Comment by GayatriDeviP** [comment]
Thank you pawelfu,

I tried the way you suggested (after shift+tab from "btn2", push arrow-down button) but first point is not focused.  when i keep on trying with all arrow keys multiple times , sometimes focus is on first point and sometimes on last point of chart. 
if we do same from "btn1" using tab , first point on the chart got focused (using arrow-down button)

i have verified that not only the border is missing but also missing focus.
below is the screenshot for reference, tested with "Nvda+chrome" where it is not reading anything on shift+tab from btn2

![image](https://user-images.githubusercontent.com/58205918/84890989-d0192000-b0b8-11ea-8fd6-2b62b142c6ed.png)

**Comment by pawelfus** [comment]
Okay, thanks for the details!
