### ISSUE TITLE
SVG Export with base64 encoded image dataLabels

### ISSUE THREAD

**Issue by timminss** [highcharts/highcharts#13726]
#### Expected behaviour
I have a chart which includes dataLabels, which contain base64 encoded images. When exported as SVG, the generated SVG appears to be malformed. Exporting as PNG works fine.

#### Actual behaviour
A malformed SVG is produced. It appears as though `<img>` tags are not correctly closed. I have tried several combinations (`<img />`, `<img></img>`, and so on).

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8rwjmkx4/
Burger Menu -> Download SVG Vector Image

#### Product version
HighCharts

#### Affected browser(s)
Not a browser-specific bug, as far as I can tell. I spoke with one of your support agents who recommended submitting this bug report, and they reckoned it was an issue with the export server.

Thanks!

**Comment by pawelfus** [comment]
Thanks for reporting the issue @timminss 

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/cgoynqbp/

Plugin:
```js
(function(H) {
  H.wrap(
    H.Chart.prototype,
    'sanitizeSVG',
    function(proceed, svgAndHthml, options) {
      var split = svgAndHthml.indexOf('</svg>') + 6,
        html = svgAndHthml.substr(split),
        svg = svgAndHthml.substr(0, split);

      if (html && options && options.exporting && options.exporting.allowHTML) {
        html = html.replace(/(<img[^>]+)>/g, "$1 ></img>");
      }

      return proceed.apply(this, [svg + html, options]);
    }
  );
})(Highcharts);
```

*Internal note:*
> document.createElement('img')

Returns: `<img>`, not `<img/>` and this is perfectly fine for void elements in HTML5 (eg `img` or `br`), but SVG's `foreignObject` uses xhtml, where each tag should be closed.

**Comment by timminss** [comment]
No problem @pawelfus - cheers for the quick response :)
