### ISSUE TITLE
Not able to Export Highcharts - BoxPlot type

### ISSUE THREAD

**Issue by linzhu02** [highcharts/highcharts#13720]
#### Description
I using phantomJS to export highcharts on the server side. It worked perfectly for all other chart types, expect BoxPlot. I make sure I included highcharts-more.js (required for BoxPlot per official document). But I am still seeing the same error as below:
`Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=boxplot
missingModuleFor: boxplot

  phantomjs://code/highcharts.js:12 in b
  phantomjs://code/highcharts.js:32 in fireEvent
  phantomjs://code/highcharts.js:12 in error
  phantomjs://code/highcharts.js:300 in initSeries
  phantomjs://code/highcharts.js:328
  :0 in forEach
  phantomjs://code/highcharts.js:328 in firstRender
  phantomjs://code/highcharts.js:300
  phantomjs://code/highcharts.js:32 in fireEvent
  phantomjs://code/highcharts.js:298 in init
  phantomjs://code/highcharts.js:298 in getArgs
  phantomjs://code/highcharts.js:297 in Chart
  phantomjs://code/highcharts.js:298 in chart
  :2
  :67`

#### Steps to reproduce
1. I had downloaded the following js files, and put them in the same directory of phantomjs.exe
https://code.highcharts.com/highcharts.js
https://code.highcharts.com/highcharts-more.js
https://code.highcharts.com/modules/exporting.js

2. run in cmd: phantomjs boxPlotChart.js

#### Product version
PhantomJS version: 2.1.1
Which OS: Windows
Latest Highcharts lib

#### Code for my boxPlotChart.js:
I am attaching the following files:
![Folder Structure](https://user-images.githubusercontent.com/26882605/84667345-399a0280-aef0-11ea-9feb-5a472dd796f5.PNG)
Run cmd for `phantomjs boxPlotChart.js`

[Phantomjs.zip](https://github.com/highcharts/highcharts/files/4780742/Phantomjs.zip)

#### Final Result
![BoxPlotChart](https://user-images.githubusercontent.com/26882605/84666758-7adde280-aeef-11ea-9f75-3e7af13d6d60.PNG)

**Comment by pawelfus** [comment]
Hi @linzhu02 

Thank you for reporting the issue. Could you try matching versions of files? Right now you have some files from v8.1.1, others from v8.1.0. We have just released v8.1.2 - please try this version.

Alternatively, you can use our node exporting server, see CLI usage: https://github.com/highcharts/node-export-server#note-about-resources-and-the-cli

**Comment by linzhu02** [comment]
Hi @pawelfus,

Updating everything to v8.1.2, and it worked! 

Thanks a lot!
