### ISSUE TITLE
Zooming is interfered by browser's drag-and-drop behavior

### ISSUE THREAD

**Issue by ktakahashimtb** [highcharts/highcharts#13737]
#### Expected behaviour

Mouse drag initiates zoom without activating drag and drop 

#### Actual behaviour

Mouse drag initiates zoom, but also activates drag and drop, which prevents zoom from reacting to mouse move and mouse up events, and visually interfering with user's action.

#### Live demo with steps to reproduce
https://jsfiddle.net/ktakahashimtb/radqh2ws/

This issue happens when container element has an ancestor with **dragabble="true"**.
My assumption is that the user can still drag-and-drop the element containing a chart while zoom is supported regardless to the parent's being draggable or not.

It does not happen prior to 8.1.0.
https://jsfiddle.net/ktakahashimtb/mcng78az/

The commit which changed this behavior appears to be: https://github.com/highcharts/highcharts/commit/91469ddcc

Prior to this update, `e.preventDefaults()` was invoked inside `onContainerMouseDown ` function which prevented the browser's default action. 

#### Product version
Highcharts 8.1.0 and up.

#### Affected browser(s)
Chrome, Firefox, Edge, Safari

**Comment by pawelfus** [comment]
Thanks for reporting the issue @ktakahashimtb 

@bre1470 - could you take a look? Thanks!

**Comment by ktakahashimtb** [comment]
@bre1470 @pawelfus - many thanks for having this issue addressed quickly!  Really appreciate if a new release of Highcharts come out very soon :)

**Comment by sebastianbochan** [comment]
The new version should be released within a few weeks.
