### ISSUE TITLE
Property 'plotX' does not exist on type 'Point'

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13738]
#### Expected behaviour
Since `point.plotX` property exists on a point, shouldn't it also exist on its type?

#### Actual behaviour
```javascript
Property 'plotX' does not exist on type 'Point'.
```

#### Live demo with steps to reproduce
Uncomment the following line: `console.log(point.plotX, point.plotY);` and check the TS error

Live demo:https://stackblitz.com/edit/highcharts-angular-basic-line-mbjvmf

#### Product version
8.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
FYI @bre1470 - it's strange, it's defined in the Series.ts file..

**Comment by bre1470** [comment]
I believe this is as it should be, as `plotX` is not part of our official documentation. See: https://api.highcharts.com/class-reference/Highcharts.Point

Maybe you are confusing it with our temporary internal namespace, which supports the migration process of our code base. 

This is not related to our documentation or the declarations files. They both rely on doclets.

**Comment by michalmikolajczyk** [comment]
hitting the same problem - how to resolve?

**Comment by michalmikolajczyk** [comment]
quick workaround:

```
interface PlottablePoint extends Highcharts.Point {
    plotX: number;
    plotY: number;
}

const plottablePoint = (chart.series[0].data[period] as PlottablePoint);
const optimalA_x = plottablePoint.plotX + chart.plotLeft;
…
```

**Comment by bre1470** [comment]
@TorsteinHonsi Should `point.plotX` and `point.plotY` become public? We use it in a lot of demos.

**Comment by bestcodermm** [comment]
hitting same error.
i think this is a bug in the callback function: https://api.highcharts.com/class-reference/Highcharts#.TooltipPositionerCallbackFunction 
Highcharts.Point doesn't have plotx and ploty. but this callback function input parameter type is Highcharts.Point | Highcharts.TooltipPositionerPointObject. v8.0.3 and lower do not have this problem.

**Comment by centi** [comment]
It seems, that the Typescript definition for the `TooltipPositionerCallbackFunction` is incorrect. Not only does it specify an incorrect type for the `point` argument (should be `TooltipPositionerPointObject`?), but it lacks the definition for `this` context aswell.

**Comment by Tolluset** [comment]
> @TorsteinHonsi Should `point.plotX` and `point.plotY` become public? We use it in a lot of demos.

It would be nice to be in the public. In my case I use it by add types in the `highcharts.d.ts`

```ts
export class Point {
    plotX: number;
    plotY: number;
    /**
     * For categorized axes this property holds the category name for the point.
     * For other axes it holds the X value.
     */
    category: string;
    /**
     * The point's current color.
     */
    color?: (ColorString|GradientColorObject|PatternObject);
    /**
     * The point's current color index, used in styled mode instead of `color`.
     * The color index is inserted in class names used for styling.
     */
    colorIndex: number;
...
```

Like this.
Is there a reason why you don't want it to be public?

**Comment by donat-ebp** [comment]
Is this going to be addressed at some point?

**Comment by TorsteinHonsi** [comment]
Sure, we can make it public.

**Comment by caleb-artifact** [comment]
Seems very odd for plotX and plotY to be private when they're passed to a public callback:
https://api.highcharts.com/highcharts/tooltip.positioner

**Comment by bre1470** [comment]
The issue has been solved.
