### ISSUE TITLE
Sankey chart legend does not show series colors

### ISSUE THREAD

**Issue by Jilocasin** [highcharts/highcharts#13743]
#### Expected behaviour
The individual legend entries should indicate their series "color" data in a sankey type chart, as the legend does for other chart types.

#### Actual behaviour
The legend entries always show a gray icon, ignoring the provided series color.

#### Live demo with steps to reproduce
https://jsfiddle.net/bLyjs0t3/4/

#### Product version
Highcharts JS v8.1.2 (2020-06-16)

#### Affected browser(s)
Firefox 77.0.1 (64-Bit)

#### Additional information
In the given jsfiddle I tried to crudely overcome the limitation of just having one series per sankey chart, as I have the requirement to distinguish multiple types of data (say e.g. apples and bananas).

Thus I included one series for the actual data (hidden in the legend) and two empty series that exist solely to provide information about the link colors.

A workaround I found to achieve my desired behaviour would be something like this: https://jsfiddle.net/8hf3oymc/
I am not sure though how the implicitly added X and Y axes from the column series are affecting Highcharts internally and would like to avoid that hack. Also clicking the dummy-series obviously has no effect on the actual chart.

**Comment by pawelfus** [comment]
Hi @Jilocasin 

Thanks for reporting the issue. This is caused by `colorByPoint` option, which is by default set to true in Sankey series: https://jsfiddle.net/BlackLabel/xn5o2fwh/

Note that setting `colorByTrue=true` in column series gives the same results: https://jsfiddle.net/BlackLabel/xn5o2fwh/2/
