### ISSUE TITLE
Updating OHLC/Candlesticks in a dynamic chart causes the axes to jump around

### ISSUE THREAD

**Issue by gulrotkake** [highcharts/highcharts#1374]
When running this chart for a little while the YAxis seems to lose its range, using only the values in the last updated candlestick to set the new extremes. This causes some candlesticks to become invisible or only partly visible within the chart.

http://jsfiddle.net/m2P5a/

**Comment by avilajhonalex** [comment]
do you have an example of this code, but with AJAX?
