### ISSUE TITLE
JS error and tooltips issue when focus a bar series item and tooltip.outside=true

### ISSUE THREAD

**Issue by danail-vasilev** [highcharts/highcharts#13748]
Hello,
When tooltips are rendered outside (tooltip.outside=true) and you focus a bar series item (via keyboard navigation):
1) a JS error is thrown. A tooltip is shown at the upper left corner with no styles.
2) If you hover over the item and then focus it, the tooltip is properly rendered but on focusing the next chart, the current tooltip is not hidden.

**Comment by pawelfus** [comment]
Hi @danail-vasilev 

Thank you for reporting the issue, but could you please follow our template? We need all information, especially:

#### Live demo with steps to reproduce
// template: https://jsfiddle.net/highcharts/LLExL/ -->

#### Product version
// Highcharts, Highstock or Highmaps plus version number -->

#### Affected browser(s)
// e.g. Chrome Version 83.0.4103.106, Firefox version..

Please, create a new bug report and fill all of the fields. Thanks!

**Comment by danail-vasilev** [comment]
hello,
Thank you for you reply ! I didn't provided a runnable example as I couldn't enable the keyboard navigation with the online example. Could you please provide me with an example where bar series navigation is enabled with the keyboard ?

**Comment by pawelfus** [comment]
Sure, here it is: https://jsfiddle.net/BlackLabel/asdoe4bv/show

**Comment by tejas127** [comment]
Hi, I am running into the same issue as the OP. It specifically happens in highcharts 7.0.0. Here is the reproducer:-

https://jsfiddle.net/r4xk5t2L/4/show

Would be great if someone can please help investigate this. Thank you.

**Comment by pawelfus** [comment]
Hi @tejas127 - thanks for the demo.

@oysteinmoseng - could you take a look? It seems that the steps are:
- hover over chart (mouse)
- tab into bars (keyboard)
- as long as mouse stays over the chart, it's fine, as soon as we move mouse out of the chart, keyboard navigation breaks and throws errors


![keyboard](https://user-images.githubusercontent.com/1453926/89994086-ed690580-dc87-11ea-95d9-47ca7246f7fe.gif)

**Comment by oysteinmoseng** [comment]
This seems to be an issue with Tooltip or Pointer, that appears to have been fixed in `v7.2.0`. Any chance you can update to `v7.2.0` or later @tejas127?
