### ISSUE TITLE
Reference error in 8.1 - Highcharts.SVGRenderer.prototype

### ISSUE THREAD

**Issue by andrewtaylor** [highcharts/highcharts#13746]
#### Expected behaviour
Displaying a pie chart with no data should work when using Highcharts as an import, for example in an Angular application (ie not as a global reference).

#### Actual behaviour
The fix to #13229 seems to have introduced a global reference to `Highcharts` which causes the following error in our application when displaying an empty pie chart:

```
ReferenceError: Can't find variable: Highcharts
    at n.drawEmpty (...)
    at n.redrawPoints (...)
    at n.render (...)
```

#### Live demo with steps to reproduce
Open a pie chart with no data in an application that imports Highcharts rather than using a global variable.

#### Product version
Highcharts 8.1.1+

#### Affected browser(s)
Tested with Chrome 83.

**Comment by sebastianbochan** [comment]
Hi @andrewtaylor ,
Thank you for reporting. The issue has been already reported and fixed on the master branch.

Im closing the ticket as duplicate of #13710
