### ISSUE TITLE
getting error as Highchart is undefined error when using it with react

### ISSUE THREAD

**Issue by Tanmay2711** [highcharts/highcharts#13759]
#### Expected behaviour
I am using Highcharts in my react application followings are import statements

functional react component <ChildComponent /> :
import PieChart from 'highcharts-react-official';
import Highcharts from 'highcharts';

<PieChart highcharts={Highcharts} options={options} />

<ParentComponent />
                        <ChildComponent />
first time when it renders the view it shows the pie-chart correctly, upon state change of parent component when parent component re-renders it should show pie-charts with updated data.

#### Actual behaviour

upon state change of parent component, it gets re-render and re-render child components, at that time gets error as **"Highcharts is undefined"** and it breaks the whole application,
we fix this issue temporarily by adding "window.Highcharts = Highcharts;" next to line "import Highcharts from 'highcharts';", but we dont want to go with this fix and wanted to know how we can load the Highcharts correctly using ES6 module import syntax.

#### Product version

"highcharts": "^8.1.0",
"highcharts-react-official": "^3.0.0",

#### Affected browser(s)
Google chrome, Microsoft Edge, Internet Explorer, Firefox

**Comment by pawelfus** [comment]
Thanks for reporting the issue! 
That issue sounds like duplicate of #13710 - could you confirm, @Tanmay2711 ?

PS: Please, always provide "Live demo with steps to reproduce".

**Comment by Tanmay2711** [comment]
Thanks @pawelfus  , I referred the discussion in the link provided by you. and tried solution provided by user @goransle
it worked for me in my project. Thank you, can you confirm the solution suggested by this user is appropriate to use to fix this issue for highchart version 8.1.0 ?

![image](https://user-images.githubusercontent.com/48334190/86395808-77ec3b80-bcbe-11ea-8ab8-7c38fb53c5ab.png)

**Comment by goransle** [comment]
@Tanmay2711 Issue #13710 was introduced in 8.1.1, so it should not apply to 8.1.0. However, I see that you wrote `"highcharts": "^8.1.0"` in your initial post, so it may be that you are actually on 8.1.1 or 8.1.2, depending on when you installed your dependencies (check your lock-file to confirm).

The workaround should work anyhow, but it may be redundant on 8.1.0.

**Comment by Tanmay2711** [comment]
Thank you @goransle . yes you are correct, my project has Highchart version 8.1.2 where the workaround you suggested works fine. And I also tried explicitly installing Highchart version 8.1.0, then without workaround also it worked for me. Thanks for the solution. We can close this issue now.
