### ISSUE TITLE
highcharts.ts doesnot exist even after installing highcharts with npm

### ISSUE THREAD

**Issue by rkor1984** [highcharts/highcharts#13755]
#### Actual behaviour

ERROR in ./node_modules/highcharts/highcharts-more.js
Module not found: Error: Can't resolve 'highcharts' in 'C:\Users\Rupinder.Kaur\source\repos\rm\Cube.Rdm.Client.App\ClientApp\node_modules\highcharts'
resolve 'highcharts' in 'C:\Users\Rupinder.Kaur\source\repos\rm\Cube.Rdm.Client.App\ClientApp\node_modules\highcharts'
  Parsed request is a module
  using description file: C:\Users\Rupinder.Kaur\source\repos\rm\Cube.Rdm.Client.App\ClientApp\node_modules\highcharts\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:/Users/Rupinder.Kaur/source/repos/rm/Cube.Rdm.Client.App/ClientApp/src/
        using description file: C:\Users\Rupinder.Kaur\source\repos\rm\Cube.Rdm.Client.App\ClientApp\package.json (relative path: ./src/)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\Rupinder.Kaur\source\repos\rm\Cube.Rdm.Client.App\ClientApp\package.json (relative path: ./src/highcharts)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\Rupinder.Kaur\source\repos\rm\Cube.Rdm.Client.App\ClientApp\src\highcharts doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              **C:\Users\Rupinder.Kaur\source\repos\rm\Cube.Rdm.Client.App\ClientApp\src\highcharts.ts** doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\Rupinder.Kaur\source\repos\rm\Cube.Rdm.Client.App\ClientApp\src\highcharts.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\Rupinder.Kaur\source\repos\rm\Cube.Rdm.Client.App\ClientApp\src\highcharts.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              **C:\Users\Rupinder.Kaur\source\repos\rm\Cube.Rdm.Client.App\ClientApp\src\highcharts.js** doesn't exist
            as directory

**Comment by pawelfus** [comment]
Hi @rkor1984 

Thanks for reporting the issue, but this error:
```
ERROR in ./node_modules/highcharts/highcharts-more.js
Module not found: Error: Can't resolve 'highcharts' in
```
Suggests you are trying to load `highcharts-more.js` without loading `highcharts.js`. Could you please provide code that produces this error? Thanks!

**Comment by rkor1984** [comment]
> Hi @rkor1984
> 
> Thanks for reporting the issue, but this error:
> 
> ```
> ERROR in ./node_modules/highcharts/highcharts-more.js
> Module not found: Error: Can't resolve 'highcharts' in
> ```
> 
> Suggests you are trying to load `highcharts-more.js` without loading `highcharts.js`. Could you please provide code that produces this error? Thanks!


export function highchartsFactory() {

    // var hc = require('highcharts');
    // var hcm = require('highcharts/highcharts-more');
    // var map = require('highcharts/modules/map');

    // hcm(hc);
    // map(hc);

    // return hc;
}

erorr goes away after commenting out this code.

**Comment by rockerest** [comment]
This problem is specific to 8.1.2 installed maybe (?) in the last 24 hours or so.

I also had a problem where `highcharts.js` simply wasn't in the `node_modules/highcharts` directory.

However, re-installing today left `highcharts.js` in the directory, so something seems to have been broken with 8.1.2 and/or npm over the last day or so, but it's fixed now (for me). Presumably this is the same problem with the `.ts` file.

**Comment by rkor1984** [comment]
> This problem is specific to 8.1.2 installed maybe (?) in the last 24 hours or so.
> 
> I also had a problem where `highcharts.js` simply wasn't in the `node_modules/highcharts` directory.
> 
> However, re-installing today left `highcharts.js` in the directory, so something seems to have been broken with 8.1.2 and/or npm over the last day or so, but it's fixed now (for me). Presumably this is the same problem with the `.ts` file.

Thanks, it went away now.

**Comment by rkor1984** [comment]
it was temporary issue , and today working fine
