### ISSUE TITLE
Regression line disappears when zooming in 

### ISSUE THREAD

**Issue by talavivi03** [highcharts/highcharts#13756]
I'm rendering a scatter plot with a regression line using the boost mode. 
When zooming in the regression line disappears.

#### Expected behaviour
Should be able to see the regression line when zooming in

#### Actual behaviour
When zooming in, the regression line disappears. 

#### Live demo with steps to reproduce
https://codepen.io/talavivi03/pen/wvMdaXx

**Comment by pawelfus** [comment]
Thank you for reporting the issue @talavivi03 

Simplified demo: https://jsfiddle.net/BlackLabel/w3o8bmyz/

After zooming in, we can observe what happens: first series is rendering line connection between points from the second series.
