### ISSUE TITLE
Highcharts.js contains viruses

### ISSUE THREAD

**Issue by Mangor1no** [highcharts/highcharts#13754]
#### Expected behaviour
I implemented the highcharts.js file into my codes, then commit it into my svn.

#### Actual behaviour
When my colleages update codes from svn, window defender notice that highcharts.js contains viruses and remove it.

#### Product version
Highcharts 8.1.2

![image](https://user-images.githubusercontent.com/39774481/85281849-ece89580-b4b4-11ea-8fc1-757211a93e18.png)
![image](https://user-images.githubusercontent.com/39774481/85281817-de9a7980-b4b4-11ea-90e4-7f3423b19200.png)

**Comment by pawelfus** [comment]
Thank you for reporting the issue @Mangor1no Could you tell us how did you download Highcharts? From NPM? From our CDN? Other source? 

Any ideas @TorsteinHonsi @oysteinmoseng @KacperMadej ?

**Comment by Mangor1no** [comment]
> Thank you for reporting the issue @Mangor1no Could you tell us how did you download Highcharts? From NPM? From our CDN? Other source?
> 
> Any ideas @TorsteinHonsi @oysteinmoseng @KacperMadej ?

I downloaded Highcharts from official website, then extract the highcharts.js file into my project. Seem like it's a bug with min highcharts.js file because when i remove dit and replaced it with highcharts.src.js, the problem went away.

**Comment by Mangor1no** [comment]
I also seeked for this issue on google and found several similar post. It's the same trojan name that was dectected by window defender
![Screenshot_2020-06-22-20-35-58-362_com android chrome](https://user-images.githubusercontent.com/39774481/85293855-1e1e9100-b4c8-11ea-8ed7-67cf41c3458a.png)

**Comment by osamamaruf** [comment]
We are also facing this issue in v8.1.2. v8.1.1 works fine. The file is deleted by the scanner while doing `bower install --force`.

**Comment by pawelfus** [comment]
Thanks for the heads up @osamamaruf 

@Mangor1no - the issue you are linking was a bug in Windows Defender. Perhaps it's the same issue, we are investigating it.

**Comment by oysteinmoseng** [comment]
We have submitted a false positive report to Microsoft. Hopefully the issue will be resolved quickly.

**Comment by oysteinmoseng** [comment]
Microsoft has removed the detection. Here are their instructions for how to update your Windows Defender definitions:

```
1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
```
