### ISSUE TITLE
With stock module, the righthand side of the gragh becomes missing when the the number of digits on Y-axis is dynamically decreased.

### ISSUE THREAD

**Issue by hanahageWanko** [highcharts/highcharts#13751]
#### Expected behaviour
The points, lines, and areas of the graph should be drawn without loss even if the value of the Y axis changes dynamically.

#### Actual behaviour
**With stock module,**
the righthand side of the gragh becomes missing when the the number of digits on Y-axis is dynamically decreased.

#### Live demo with steps to reproduce

1. press Add new series 
2. press remove series
 => the righthand side of the gragh becomes missing

##### With stock module
[Reproduction in CodeSandbox](https://codesandbox.io/s/with-stock-module-7w392)
![With stock module](https://user-images.githubusercontent.com/43740354/85198296-98151580-b322-11ea-95c7-64a4199f072b.gif)

##### Without stock module
[Reproduction in CodeSandbox](https://codesandbox.io/s/without-stock-module-p5yfz)
![Without stock module](https://user-images.githubusercontent.com/43740354/85198306-a3684100-b322-11ea-8513-58552fa7b789.gif)

#### Product version
highcharts: 8.1.2
highcharts-vue: 1.3.5

#### Affected browser(s)
Chrome 81

**Comment by pawelfus** [comment]
Thank you for reporting the issue @hanahageWanko 

Simplified demo: https://jsfiddle.net/BlackLabel/gs8h7ny3/

**Workaround:**
If chart does not need zoom, set [`series.clip = false`](https://api.highcharts.com/highcharts/series.line.clip).
Demo: https://jsfiddle.net/BlackLabel/gs8h7ny3/1/

**Comment by hanahageWanko** [comment]
Is there any workaround while enabling zoom?

**Comment by pawelfus** [comment]
This is an alternative:

```js
(function(H) {
  H.addEvent(H.Series, 'render', function() {
    var chart = this.chart;

    if (!this.clipBox) {
      var clipHeight = this.yAxis.len;
      // Include xAxis line width (#8031) but only if the Y axis ends on the
      // edge of the X axis (#11005).
      if (this.xAxis.axisLine) {
        var dist = chart.plotTop + chart.plotHeight -
          this.yAxis.pos - this.yAxis.len,
          lineHeightCorrection = Math.floor(this.xAxis.axisLine.strokeWidth() / 2);
        if (dist >= 0) {
          clipHeight -= Math.max(lineHeightCorrection - dist, 0);
        }
      }

      this.clipBox = H.merge(chart.clipBox);
      this.clipBox.width = this.xAxis.len;
      this.clipBox.height = clipHeight;
    }
  }, 1);
})(Highcharts);
```
Demo: https://jsfiddle.net/BlackLabel/e96ud3a4/1/

It shouldn't break anything, but if you find something, let us know.

*Internal note:*
Bisected to commit 5b06bed1a7

Most likely this is no longer correct (`this.animate` always exists after the commit above):
https://github.com/highcharts/highcharts/blob/ecf1eb33c51e821370b34e5cd02c38de85fd8d50/ts/Core/Chart/StockChart.ts#L1053-L1074

**Comment by nakagawata** [comment]
@pawelfus 

> Demo: https://jsfiddle.net/BlackLabel/e96ud3a4/1/

It's not fixed yet.
Reproduce by the same procedure.

**Comment by pawelfus** [comment]
Hi @nakagawata 

The workaround was necessary in v8.1.

The issue should be fixed in v.8.2+, could you test it? Demos from this thread are fine:
- https://codesandbox.io/s/with-stock-module-forked-t8m4z?file=/src/main.js
- https://jsfiddle.net/BlackLabel/e96ud3a4/5/

**Comment by nakagawata** [comment]
Hi @pawelfus 

I think both of them still have bugs.

> https://codesandbox.io/s/with-stock-module-forked-t8m4z?file=/src/main.js

![dataline-lost](https://user-images.githubusercontent.com/54659043/91245577-c41c9f00-e788-11ea-978d-1a736e58d9dc.gif)


> https://jsfiddle.net/BlackLabel/e96ud3a4/5/

![dataline-lost2](https://user-images.githubusercontent.com/54659043/91245581-c67ef900-e788-11ea-808b-305d56631761.gif)

Perhaps this procedure is more likely to occur.
1. Press the Add new series button.
2. Wait a moment.
3. Press the remove series button.

**Comment by pawelfus** [comment]
Right, I needed to wait a second or two, thank you for pointing this out!

Please, try this in v8.2+: https://jsfiddle.net/BlackLabel/e96ud3a4/6/

**Comment by nakagawata** [comment]
Thank you!
I think it's fixed.

**Comment by nakagawata** [comment]
@pawelfus 

Will this fix be included in the next update?

**Comment by pawelfus** [comment]
Yes, we want to fix this in the next update
