### ISSUE TITLE
Spiderweb/Windrose/Radar charts not displaying all x labels

### ISSUE THREAD

**Issue by IgorFIE** [highcharts/highcharts#13762]
#### Expected behaviour
Given: I have a spiderweb chart
When: I enable `useHTML` on the chart labels
Then: I should see all labels on the spiderweb chart

#### Actual behaviour
It is only drawing half of the labels.
This also happens in windrose and Polar (radar) chart

#### Live demo with steps to reproduce
https://jsfiddle.net/panintelligence/kqt0r9w1/

#### Product version
We updated from 7.2.0 to 8.1.0 and the problem started to appear.
This is also a problem in the last version

**Comment by pawelfus** [comment]
Thank you for reporting the issue @IgorFIE 

Broken since v8.1.0, up to v8.0.4 it was fine.

*Internal note:*
Bisect fails. Just a guess, but might be connected: 94a22637d9d291b890df9cd448a701cb5efb74f4 - @PaulDalek could you check it?

**Comment by PaulDalek** [comment]
Hi @IgorFIE,

In a nutshell, the `xOffset` variable used for calculating a label's `x` position is `NaN` when `useHTML` is set to true. As for now you can use a simple workaround which prevents `NaN` in calculation.

#### Workaround
https://jsfiddle.net/BlackLabel/zmah2swf/

**Comment by IgorFIE** [comment]
Hi @pawelfus and @PaulDalek ,

For now we decided to downgrade to 8.0.4 until there's a version with the fix.
I'll keep an eye on this issue.

Thanks.
