### ISSUE TITLE
DataLabel overlapping issue when dragging xrange points

### ISSUE THREAD

**Issue by pjanaya** [highcharts/highcharts#13761]
#### Scenario
* I have two series:
  * Line
  * X-Range
* Line series has enabled data labels.
* X-Range has enabled dragging.
* Once rendered, the data labels from the line series are not overlapping (which is ok), even when they are really close to each other.

#### Expected behaviour
When I drag an xrange point, the line series datalabel should be kept the same, with no overlapping.

#### Actual behaviour
When I drag an xrange point, all line series datalabels are shown, no matter how close they are to each other.

#### Live demo with steps to reproduce
* Two demos:
  * Using the "[Draggable X range series](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/dragdrop/drag-xrange)" example from the [API Reference](https://api.highcharts.com/highcharts/plotOptions.xrange.dragDrop), I only did minor modifications to add an extra line series with very closed points: https://jsfiddle.net/twos269v/22/
  * Based on the previous demo, I tried to strip away all the superfluous code in order to keep it as simple as possible and make sure there were no other attributes affecting: https://jsfiddle.net/pcwme9jk/20/

#### Screenshots based on the [second demo](https://jsfiddle.net/pcwme9jk/20/)
After initial render status (no overlapping):
![Screen Shot 2020-06-23 at 13 33 06](https://user-images.githubusercontent.com/5021038/85410173-494fc180-b556-11ea-8902-5558f937f6e6.png)

After dragging blue xrange point (overlapping on points 0 and 2):
![Screen Shot 2020-06-23 at 13 33 15](https://user-images.githubusercontent.com/5021038/85410450-a2b7f080-b556-11ea-8067-703a874b1aab.png)

Video:
![ezgif-4-a296ec5d0407](https://user-images.githubusercontent.com/5021038/85410529-c11dec00-b556-11ea-8b1a-f877395c6841.gif)

#### Extra things I've noticed
A redraw of the chart would revert the points to their non-overlapping status.
On those demos, the easiest way to force a redraw is:
* Dragging one of the points in the line series
* Resizing the window.

If ``liveRedraw`` is enabled, the overlapping issue happens right after the dragging move starts

#### Product version
* Highcharts JS v8.1.2 (2020-06-16)

#### Affected browser(s)
* Chrome v83
* Safari on iPad Pro and iOS13

**Comment by Izothep** [comment]
Hi @pjanaya! Thank you for contacting us with your issue and for such a detailed description. 

It looks that the issue is related with https://github.com/highcharts/highcharts/issues/13742 and the fix provided in mentioned topic is solving the problem in your case as well: https://jsfiddle.net/BlackLabel/Lhxtojzq/

Could you please confirm?

**Comment by pjanaya** [comment]
Hi @Izothep. 

Thanks for your answer and the proposed workaround. I don't understand why but when I try to apply that fix to my project, Highcharts renders all dataLabels. There is no overlapping detection anymore. I also tried to copy-paste it directly to the .src.js file, to make sure it wasn't a problem with the function overriding, but I got the same result. As I said, I don't understand why and I can't really come up with a jsFiddle for you to check.

I'll keep trying.

**Comment by Izothep** [comment]
@pjanaya, thanks for the update. Could you please try with an example below? https://jsfiddle.net/BlackLabel/Lhxtojzq/1/

**Comment by pjanaya** [comment]
@Izothep, sorry but I'm experiencing the same. All datalabels are shown and there is no overlapping detection. My project uses Typescript so I have to make a few changes to make the snippet work. I'm not sure if it's related to that and I'm breaking something important. Whenever you update with the new changes, I'll use the official package from NPM and I'll try again. Sorry for the trouble.

**Comment by pjanaya** [comment]
Hi @Izothep! The latest Highcharts version (v8.2.0) seems to have successfully fixed this issue. Thanks for the help!
