### ISSUE TITLE
Navigator resizing problem.

### ISSUE THREAD

**Issue by mateBe95** [highcharts/highcharts#13772]
#### Expected behaviour
Navigator resize work.

#### Actual behaviour

Navigator resizing is not working when try to resize.

#### Product version
From version 7+ its not working. When i downgrade to <7 it works perfectly. When i try to resizne on JsFiddle it works perf, but in my polymer framework no.

#### Affected browser(s)
All.

**Comment by pawelfus** [comment]
Hi @mateBe95 

Thanks for reporting the issue, but could you attach live demo (jsFiddle, stackBlitz etc. I'm not sure which one does support polymer)? We will check it.

**Comment by pawelfus** [comment]
Closed due to inactivity.
