### ISSUE TITLE
Incorrect clip path after update

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13777]
#### Expected behaviour
The whole series should be visible

#### Actual behaviour
Incorrect clip-path after update (it requires specific chart config, more details in the demo). After resizing the window, or calling `reflow()`  clip-path will be corrected.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/x4ra2s6u/

#### Product version
8.1.2

#### Affected browser(s)
All

**Comment by slavede** [comment]
In case of big data, reflow didn't help without specific / larger reflow.

It cuts it like this for me:

![image](https://user-images.githubusercontent.com/2838038/86459069-89692e00-bd26-11ea-9c87-8730937b2dc4.png)


Afer window resize it gets displayed correctly

![image](https://user-images.githubusercontent.com/2838038/86459115-9be36780-bd26-11ea-94dc-6f2731571a0e.png)

**Comment by pawelfus** [comment]
In case of disabled zooming and using only one pane, it should be possible to workaround the issue by setting `series.clip` to false: https://api.highcharts.com/highcharts/series.line.clip

**Comment by khlieng** [comment]
Fixed since 8.2.2 (#14258).
