### ISSUE TITLE
[Spider chart] Tooltip not showing when value is equal to maximum

### ISSUE THREAD

**Issue by Ghalnas** [highcharts/highcharts#13771]
Hello !
We have an issue with the spider chart. When we set a maximum value on the y axis and some of our data is equal to this maximum, the tooltip doesn't appear at all on that specific point.

#### Expected behaviour
The tooltip to display when hovered

#### Actual behaviour
The tooltip doesn't display

#### Live demo with steps to reproduce
https://jsfiddle.net/mvgbp62f/14/

#### Product version
8.0+ (we are on 8.1.2, tested on 8.0, but no issue on 7.2.1)

#### Affected browser(s)
Chrome, Firefox

**Comment by pawelfus** [comment]
Thanks you for reporting the issue @Ghalnas 

Bisected to commit f3423c994f

FYI @raf18seb
