### ISSUE TITLE
Gantt: navigator overlaps with chart

### ISSUE THREAD

**Issue by eqlz** [highcharts/highcharts#13783]
#### Expected behaviour
Navigator will render below chart with a space between them.

#### Actual behaviour
Navigator's top overlaps with chart's bottom

#### Live demo with steps to reproduce
https://jsfiddle.net/2qokmxuw/

<img width="741" alt="Screen Shot 2020-06-28 at 8 38 30 PM" src="https://user-images.githubusercontent.com/29101953/85962572-697ce780-b97f-11ea-9c31-829af768f1f3.png">

#### Product version
highcharts 7.2.1

#### Affected browser(s)
Chrome Version 83.0.4103.61
IE 11.836.1836.0
Edge 83.0.478.45

**Comment by pawelfus** [comment]
Hi @eqlz 

Thank you for reporting the issue but I can't recreate this. This is my result on OSX + Chrome Version 83.0.4103.116 (tested both, v7.2.1 and v8.1.2):

<img width="520" alt="Screen Shot 2020-06-29 at 10 18 32" src="https://user-images.githubusercontent.com/1453926/85990353-2ad44500-b9f2-11ea-8bd9-986894180be4.png">

Are there any necessary steps to recreate the issue? Thanks!

**Comment by eqlz** [comment]
> Hi @eqlz
> 
> Thank you for reporting the issue but I can't recreate this. This is my result on OSX + Chrome Version 83.0.4103.116 (tested both, v7.2.1 and v8.1.2):
> 
> <img alt="Screen Shot 2020-06-29 at 10 18 32" width="520" src="https://user-images.githubusercontent.com/1453926/85990353-2ad44500-b9f2-11ea-8bd9-986894180be4.png">
> 
> Are there any necessary steps to recreate the issue? Thanks!

Hi @pawelfus 

Thanks for the reply.  I was using a laptop and the issue appears.  I wonder if you're using a desktop or bigger screen/browser window.  

I think if the screen/browser window's height is not tall enough to handle too many rows in chart, this will happen.  

This issue happened in our production: there can be a dozen of rows in charts, and the chart can only occupy part of the space in the page since there are other components in the page.

**Comment by sebastianbochan** [comment]
Could you hardcode the width and height of the container (in CSS) ? It will allow us to test it again.

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
