### ISSUE TITLE
Wordmap export based on x and y axis

### ISSUE THREAD

**Issue by dcr31000** [highcharts/highcharts#13785]
#### Expected behaviour
Export data

#### Actual behaviour
Export x and y axis with incremental integer

#### Live demo with steps to reproduce
http://jsfiddle.net/wbyn6cx3/

View data table:
Category	Value
x	y
Canada	0	
United States of America	1	
Japan	2	
Russia	3	

#### Product version
Highcharts 8.1.2 (tested on >= 8.1)

#### Affected browser(s)
Tested on Firefix

**Comment by dcr31000** [comment]
Note : it's working fine on 8.0. This issue is only since 8.1.1

**Comment by pawelfus** [comment]
Thank you for reporting the issue @dcr31000

**Workaround:**
Set `xAxis.type = "category"`.
Demo: https://jsfiddle.net/BlackLabel/4nujvhtk/ 

*Internal note:*
Bisected to commits: 126a573eeac34f8f2ce8e3a2fa352a513ee0fe22 and e8f02d53035e0f869acc748447445a56a8b4dccf

FYI @Basts

**Comment by dcr31000** [comment]
Thank you for the workaround
