### ISSUE TITLE
polar - connectEnds issue

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#13789]
#### Expected behaviour

There shouldn't be any additional path between last and the first pair of points for the `arearange` series. 

#### Actual behaviour

When the `connectEnds` property is set to false, the chart is not rendering properly - some additional path is added between last and the first pair of points. 

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/5yz4gsjc/

#### Product version

Highcharts JS v8.1.2 (2020-06-16)

**Comment by uajqq** [comment]
Does anyone have a temporary workaround for this? Right now I’ve been setting all null data to 0 to avoid the extra path being rendered.

**Comment by uajqq** [comment]
Seems like this is similar to a bug that was closed a few years back (issue #5186)

**Comment by PaulDalek** [comment]
Hi @uajqq,

Thanks for the info. As for now here's a workaround where a arearange path is rendered correctly (used lowerPath and higherPath of the graphPath) if the connectEnds is set to false.

#### Workaround
https://jsfiddle.net/BlackLabel/5ycvr1ue/
