### ISSUE TITLE
After setting the width and color of the border in the structure drawing, the area below does not show the full problem

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13784]
After setting the width and color of the border in the structure drawing, the area below does not show the full problem

https://jshare.com.cn/temp/9tG0ik
![6e4f545d65452f27b3fc0fa85b4ec7b](https://user-images.githubusercontent.com/48822299/85967025-07aa9500-b9f4-11ea-8a05-d27f86013d2b.png)

**Comment by pawelfus** [comment]
Thank you for reporting the issue @weixingcai 

**Workaround:**
Disable clip, demo: https://jsfiddle.net/BlackLabel/98dc5jxw/

Config:
```js
series: [{
  type: 'organization',
  clip: false,
  ...
}]
```

**Comment by weixingcai** [comment]
thanks
