### ISSUE TITLE
Map of China should include Taiwan province.

### ISSUE THREAD

**Issue by sunny-chao** [highcharts/highcharts#13781]
#### Expected behaviour
Map of China **SHOULD** include Taiwan province.

#### Actual behaviour
Taiwan province is missing in map of China.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/cn/cn-all

#### Product version

All version.

**Comment by pawelfus** [comment]
Hi @sunny-chao 

Thanks for reporting the issue, but this is wrong repo, please report this in the map collection repo: https://github.com/highcharts/map-collection-dist/issues
