### ISSUE TITLE
Highmaps: French Guiana missing in South America map

### ISSUE THREAD

**Issue by egraether** [highcharts/highcharts#13790]
#### Expected behaviour
The map of South America should contain all regions.

#### Actual behaviour
French Guiana is not part of the South America map: Map Collection - Custom - South America https://code.highcharts.com/mapdata/custom/south-america.svg

![Screenshot from 2020-06-29 12-54-16](https://user-images.githubusercontent.com/201867/86001124-beb40a00-ba0e-11ea-9b89-aa3f4fc643bc.png)

![Screenshot from 2020-06-29 13-47-14](https://user-images.githubusercontent.com/201867/86001459-34b87100-ba0f-11ea-9da6-9cbffe8694b6.png)

https://www.google.com/maps/place/French+Guiana/@4.02896,-55.3300419,7z/data=!3m1!4b1!4m5!3m4!1s0x8d12155785f7d753:0xde27f7e90f0af446!8m2!3d3.933889!4d-53.125782

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/custom/south-america

**Comment by pawelfus** [comment]
Hi @egraether 

Thank you for reporting, but could you report this issue in the map-collection repo? See: https://github.com/highcharts/map-collection-dist

Thanks!

**Comment by egraether** [comment]
> Hi @egraether
> 
> Thank you for reporting, but could you report this issue in the map-collection repo? See: https://github.com/highcharts/map-collection-dist
> 
> Thanks!

Done highcharts/map-collection-dist/issues/67
