### ISSUE TITLE
with highcharts 8.1.0,xAsix lable display is incomplete

### ISSUE THREAD

**Issue by ma1990213** [highcharts/highcharts#13795]
#### Expected behaviour
xAsix lable display is complete

#### Actual behaviour
xAsix lable display is incomplete

#### Live demo with steps to reproduce
![yAxis-display-issue](https://user-images.githubusercontent.com/17824026/86105226-a79a1880-baf1-11ea-8b69-652a7d1b8113.png)

#### Product version
"highcharts": "8.1.0",
"highcharts-3d": "^0.1.7",
"highcharts-vue": "^1.3.5"

#### Affected browser(s)
google chrome 81.0.4044.113

**Comment by pawelfus** [comment]
Hi @ma1990213 

Thank you for reporting the issue, but please provide live demo of the issue. We are not able to debug from the image :) Thanks!

PS: `"highcharts-3d": "^0.1.7",` - this sounds like unofficial module for 3D. `highcharts-3d` module is included in `highcharts` package.

**Comment by pawelfus** [comment]
Closed due to inactivity.
