### ISSUE TITLE
Animation after zoom on mobile device

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#13806]
Open the following on a mobile touchscreen device:

https://jsfiddle.net/3mn0sh9g/show/

Zoom in and pan around.  When you end the zoom/pan, the view quick jumps back to the previous state, then animates to the new state.  This is very disorientating.  For now I just have to disable animation:

https://jsfiddle.net/xt84keg7/show/

I appreciate that animating at the end of the zoom/pan doesn't do much because the SVG is already roughly in the right place (albeit just a scaled version of the original).  So I'm not bothered too much about animating after the zoom/pinch.  However, I would at least like to be able to animate other transitions, like the transition that happens when hitting the Reset Zoom button, *after* a zoom/pan.  But this isn't possible if I have to disable animation.

**Comment by pawelfus** [comment]
Thanks for reporting the issue @drmrbrewer 

I agree, there's no point to animate after zoom/pan on mobile - and by default we disable it, unless `chart.animation` is enabled in options .  For now you can avoid setting `chart.animation` - that does disable the zoom in/pan animation, but keeps zoom out animation in place.

*Internal note:*
Related code in core:

- animation disabled by default:
https://github.com/highcharts/highcharts/blob/c6b99cbb62a22fc00cc2d5b0edcd507437c337be/ts/parts/Pointer.ts#L605-L619

- animation forced by `chart.animation` option:
https://github.com/highcharts/highcharts/blob/c6b99cbb62a22fc00cc2d5b0edcd507437c337be/ts/parts/Interaction.ts#L727-L733

**Comment by drmrbrewer** [comment]
> you can avoid setting chart.animation

OK that works as I'd expect: https://jsfiddle.net/Lrfxwzv3/show

However, as it happens, this has a knock-on effect in that it messes with my x-axis labelling (labels don't appear or appear sporadically)... this doesn't happen with the above demo so it must be another issue.

**Comment by pawelfus** [comment]
Sounds like a different issue. If you recreate it, please, report :)

**Comment by pawelfus** [comment]
*Internal note:*
Blamed up to: 9c592a334, seems that options are in pick in that order since the beginning.

**Comment by TorsteinHonsi** [comment]
Yes...I wonder why. And I wonder what happens if we swap the order of the two first ones. We could start by identifying in which other cases animation is passed over as an event argument. My guess is none. In that case, I'm inclined to say that the two first `pick` arguments should be swapped.

**Comment by pawelfus** [comment]
Other cases:
- `chart.zoomOut()` - does not use event
- `series.onDrillToCluster()` - passes over the event argument, does not change the animation, event type: browser event (originalEvent)

**Comment by pawelfus** [comment]
Fixed in v11, after zooming/panning refactor. Demo: https://jsfiddle.net/BlackLabel/qn1f74jk/2/
