### ISSUE TITLE
Scatter plot doesn't redraw when setting lineWidth to 0

### ISSUE THREAD

**Issue by nbrown96** [highcharts/highcharts#13816]
#### Expected behaviour
1. I have a scatter plot with one series, and that series has lineWidth=1
2. I use chart.update with redraw=true to change the series' lineWidth=0
3. The chart should redraw so that the line connecting the points of the series isn't visible.

#### Actual behaviour
Instead, after step 2, the line doesn't disappear from the chart until I move my cursor over the chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/wxo5n6hL/21/
1. Run the jsfiddle
2. Click the Connect button - a line should be drawn between the points
3. Click the Disconnect button - I expect the line to disappear, but it doesn't
4. Mouseover the chart - the line disappears

#### Product version
Noticed in v8.1.0. I'm upgrading from Highcharts v6.2.0 to v8.1.0, and did not see this issue before upgrading.

#### Affected browser(s)
I tried out the jsfiddle on Chrome, Firefox, and Edge and got the same results.

I think I've figured out all the other relevant (to me) changes between the two versions, so I'm hoping there's a workaround for this!

**Comment by pawelfus** [comment]
Thank you for reporting the issue @nbrown96 

*Internal note:*
Broken since v7.1.0. Bisected to commit 4dc2b388fc

**Comment by nbrown96** [comment]
Great, thank you!
