### ISSUE TITLE
yaxis labels not full 

### ISSUE THREAD

**Issue by viethoanganh79** [highcharts/highcharts#13810]
when i set width of column chart from 445px to 500px
the label not show full text
pls help me
thanks for support
![image](https://user-images.githubusercontent.com/15764130/86231203-63277f00-bbbc-11ea-8957-ae6df897e526.png)

**Comment by pawelfus** [comment]
Hi @viethoanganh79 

Thanks for choosing Highcharts!

Could you contact our support team? See: https://www.highcharts.com/blog/support/ - for me it seems it's not a bug, but something on your page overlaps the label. And if this is actually a bug, then our support will help you reporting this as a bug properly. 

Thanks!
