### ISSUE TITLE
Disable Heatmap Legend "hover" arrow?

### ISSUE THREAD

**Issue by bucky-badger-gesmer** [highcharts/highcharts#13815]
#### Expected behaviour
When a user hovers on a heatmap, the legend should not show the arrow on the legend.

#### Actual behaviour
Hovering on heatmap displays "hover" arrow on legend.

#### Live demo with steps to reproduce

https://imgur.com/gvVgdd7

#### Product version

Highcharts 8.1.2
#### Affected browser(s)
All

**Comment by bucky-badger-gesmer** [comment]
@mateuszkornecki can anyone help me with this please?

**Comment by pawelfus** [comment]
Hi @bucky-badger-gesmer 

Sorry for the delay. For some unknown reason I did not receive notification from github.

You can find the answer in our docs: https://api.highcharts.com/highcharts/colorAxis.marker

> The triangular marker on a scalar color axis that points to the value of the hovered area. To disable the marker, set `marker: null`.

Demo: https://jsfiddle.net/BlackLabel/e20scdxy/

**Comment by bucky-badger-gesmer** [comment]
@pawelfus Thank you so much! I really appreciate it and I will for sure use the support channel in the future!
