### ISSUE TITLE
can't override series partialFill color for a specific point

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#13811]
#### Expected behaviour
PartialFill fill color can be defined as an object in plotOptions, series and data.
When defined for a data point I expect it to override the fill color defined in the series or plotOptions level.

#### Actual behaviour
Fill color defined in plotOptions or series level can't be overriden.

#### Live demo with steps to reproduce
https://jsfiddle.net/alvarezg/0nu2t75p/
Partial fill in top left point should be black.
Partial fill in bottom left point should be red
.
#### Product version
Highcharts 8.1.2

**Comment by pawelfus** [comment]
Thank you for reporting the issue @alvarezguille 

*Internal note:*
Most likely order of options to pick the color is wrong. Point options should have higher priority than series options.
