### ISSUE TITLE
Property dataMax is missing on type Series

### ISSUE THREAD

**Issue by Geoffrynagy** [highcharts/highcharts#13820]
#### Expected behaviour
In highcharts.d.ts, the property dataMax is missing on the class Series.
This used to be there in previous versions

#### Actual behaviour
Propert `dataMax` to be available in the typings of Series.

#### Live demo with steps to reproduce
/
#### Product version
Highcharts 8.1.2

**Comment by pawelfus** [comment]
FYI @bre1470 

I'm not sure if this should be public or not, but `dataMin` is available. Not all series have `dataMin` and `dataMax` though (e.g. networkgraph and others that don't have `y-value`).

**Comment by bre1470** [comment]
I believe it is a mistake, that `dataMax` is not public. I will also add `undefined` as a valid value of these two properties and make a remark about your example.
