### ISSUE TITLE
In the honeycomb，I want the mouse to move out of a single square ， the tooltip box to disappear，what should I do？

### ISSUE THREAD

**Issue by idjiang** [highcharts/highcharts#13823]
#### Expected behaviour
[https://www.highcharts.com/demo/honeycomb-usa](https://www.highcharts.com/demo/honeycomb-usa)，In the honeycomb，I want the mouse to move out of a single square ， the tooltip box to disappear，what should I do？

**Comment by pawelfus** [comment]
Hi @idjiang 

You should contact our support first :) See details: https://www.highcharts.com/blog/support/
