### ISSUE TITLE
Linked errorbar series don't dim on legend hover.

### ISSUE THREAD

**Issue by max0x7ba** [highcharts/highcharts#13829]
In the top two chats at https://max0x7ba.github.io/atomic_queue/html/benchmarks.html when I hover mouse over the series name in the legend, it dims the other series columns, but it doesn't dim the errorbars which are linked to the corresponding column series.

How do I make the linked errorbars also dim, please?

#### Expected behaviour
The series and linked errorbars series dim when other series name is hovered upon in the legend.

#### Actual behaviour
The linked errorbars series don't dim.

#### Live demo with steps to reproduce
https://max0x7ba.github.io/atomic_queue/html/benchmarks.html 

#### Product version
https://code.highcharts.com/highcharts.js

#### Affected browser(s)
Google Chrome and Opera on Linux.

**Comment by pawelfus** [comment]
Thank you for reporting the issue @max0x7ba - this is expected behaviour: only items visible in legend receive inactive state. See #12015 - you can use workaround posted there.

Closing as duplicate of #12015
