### ISSUE TITLE
The X-axis is not in the right format

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13830]
The X-axis is set to year, month and day, but it is not displayed correctly

https://jshare.com.cn/temp/NFG0qG
![gantetu](https://user-images.githubusercontent.com/48822299/86560468-e23bff00-bf90-11ea-8047-0b405a21ae59.png)

**Comment by sebastianbochan** [comment]
Hi @weixingcai,
Thank you for reporting. For the general support](https://www.highcharts.com/support) questions please use stackoverflow / forum or email.

**Comment by weixingcai** [comment]
According to the documentation Settings, it doesn't work and should be a bug

**Comment by pawelfus** [comment]
It does work, you set `week` config, but your labels use `month` option. For more details, please contact our support team.

**Comment by weixingcai** [comment]
Setup day doesn't work either you guys tried it

**Comment by pawelfus** [comment]
@weixingcai - I said **month**. Tested, works fine: 

![Screen Shot 2020-07-07 at 10 27 14](https://user-images.githubusercontent.com/1453926/86748502-cd1caa00-c03c-11ea-8f72-637e8363a9dc.png)
