### ISSUE TITLE
Ball does not return to the problem

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13831]
When the ball is rendered, click the ball, the ball does not move, does not return to its parent

https://jshare.com.cn/temp/rFG0q8
![圆堆积图](https://user-images.githubusercontent.com/48822299/86566777-cd656880-bf9c-11ea-9c85-f0ac0af07f7c.png)

**Comment by weixingcai** [comment]
https://jshare.com.cn/temp/rFG0q8

**Comment by pawelfus** [comment]
Thanks for reporting the issue @weixingcai 

It's a regression since v7.1.3, v7.1.2 used to work fine: https://jsfiddle.net/cfebnu1v/

**Workaround:**
Demo: https://jsfiddle.net/cfebnu1v/1/

Plugin:
```js
(function(H) {
  H.wrap(
    H.dragNodesMixin,
    'onMouseUp',
    function(proceed, point) {

      if (!this.options.fixedDraggable) {
        delete point.fixedPosition;
      }

      return proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    }
  );
})(Highcharts);
```


*Internal note:*
Bisected to commit bb722c88a1

**Comment by weixingcai** [comment]
thanks

**Comment by Izothep** [comment]
*Internal Note*:

What I think would be a good solution in here is to simply split the `if` statement so we will achieve similar block of code as below:
```
{
        if (point.fixedPosition) {

            if (point.hasDragged) {
                if (this.layout.enableSimulation) {
                    this.layout.start();
                } else {
                    this.chart.redraw();
                }
            }

            point.inDragMode = point.hasDragged = false;
            if (!this.options.fixedDraggable) {
                delete point.fixedPosition;
            }
        }
    },
```
