### ISSUE TITLE
Export Highcharts Gantt Chart Error

### ISSUE THREAD

**Issue by cvinhar** [highcharts/highcharts#13847]
#### Expected behaviour
Expected to download the chart exactly as developed in the UI like in the picture below
![image](https://user-images.githubusercontent.com/46776508/86787934-31b92280-c098-11ea-91e3-19763ef33e0b.png)

#### Actual behaviour
What I actually get to see in jpeg when I download
![gantt-chart-with-navigat (1)](https://user-images.githubusercontent.com/46776508/86788482-d0458380-c098-11ea-8f5d-a5b7a31f3674.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/cvinhar/scx6f4ph/21/

#### Product version
Highcharts Gantt JS v8.1.2 (2020-06-16)
Highcharts JS v8.1.2 (2020-06-16)

#### Affected browser(s)
So far tested in Google Chrome

**Comment by pawelfus** [comment]
Thank you for reporting the issue @cvinhar

**Simplified demo:**
https://jsfiddle.net/BlackLabel/zckg8tLs/1/ - export chart to png and observe extra dataLabels in navigator.

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/zckg8tLs/

Config (note: number of `dataLabels` in config must match definition in `plotOptions`):
```js
  navigator: {
    enabled: true,
    liveRedraw: true,
    series: {
      type: 'gantt',
      dataLabels: [{
        enabled: false
      }, {
        enabled: false
      }, {
        enabled: false
      }]
    }
  },
```

*Internal note:*
It works fine for `dataLabels: {}`, but it's broken for `dataLabels: [{}]`.

We also have different results in Highcharts Stock and Gantt:
- Stock: https://jsfiddle.net/BlackLabel/z4rv9fu7/  (broken exporting and in-browser rendering)
- Gantt: https://jsfiddle.net/BlackLabel/zckg8tLs/3/ (broken exporting)

**Comment by cvinhar** [comment]
Thank you for your quick response @pawelfus

One more main bug I think you have overlooked which is the background color of the data labels.
If you have noticed in my UI there are multiple labels in the chart however when I export the chart I able to see the black color only but the yellow and blue color are disappeared 

before download (In the UI)
![86787934-31b92280-c098-11ea-91e3-19763ef33e0b](https://user-images.githubusercontent.com/46776508/86866237-1f280300-c103-11ea-95c3-f4a4143dbb1f.png)

after download
![gantt-chart-with-navigat (1)](https://user-images.githubusercontent.com/46776508/86866303-3d8dfe80-c103-11ea-8c52-888cf437242b.jpeg)

**Comment by pawelfus** [comment]
It's explained in our docs: https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting

Additionally, your styles are not defined inline in chart, but outside, so SVG with HTML that is send to our exporting server does not know about them. Place styles inline and should be fine. Or use [styled mode](https://www.highcharts.com/docs/chart-design-and-style/style-by-css).
