### ISSUE TITLE
Stock Line Chart broken with responsive options

### ISSUE THREAD

**Issue by nickwinger** [highcharts/highcharts#13858]
#### Expected behaviour
When using the responsive feature the line chart should not be broken

#### Actual behaviour
if the container of the highstock-line-chart has a fixed height and you use the responsive feature
(to disable rangeSelector and legend for example) the Line in the Chart is broken.

#### Live demo with steps to reproduce
http://jsfiddle.net/nickwinger/pk5rdq6g/5/

#### Product version

Highstock

#### Affected browser(s)
Chrome, Safari, latest

**Comment by sebastianbochan** [comment]
Hi @nickwinger,
Thank you for reporting. The problem is caused by `return: true` before animations' end.

Workaround:
Use timeout to call the return.
- http://jsfiddle.net/BlackLabel/a5vobe36/

Its a regression, because of working 8.0.1 version.
- http://jsfiddle.net/BlackLabel/0a1kdctp/

Bisect leads me to: https://github.com/highcharts/highcharts/commit/5b06bed1a73f146b604a5a5fae2782989c04ed88

**Comment by nickwinger** [comment]
@sebastianbochan  this is not a workaround, as you can see now the rangeSelector is shown. Because the function just returns undefined. you cannot call a timeout in a non-async method, this just returns undefined.
you would have to call something like Thread.sleep() (which is not available in javascript) or make the whole method async

**Comment by nickwinger** [comment]
even with a synchronous sleep function it is not working as you said:
http://jsfiddle.net/nickwinger/pk5rdq6g/9/

**Comment by pawelfus** [comment]
**Simplified demos:**
- http://jsfiddle.net/BlackLabel/pzvrg1xb/
- http://jsfiddle.net/BlackLabel/pzvrg1xb/1/

Not a perfect workaround, but once chart is loaded we can call `chart.update({ })` to force resizing clips. Downside is that we can observe the animation: http://jsfiddle.net/BlackLabel/g4zysrwu/

Snippet:
```js
let chart = Highcharts.stockChart('container', newOptions, (chart) => chart.update({}));
```

*Internal note:*
Related to the way Stock implements clipping. Works fine in Highcharts. Does not matter if we disable RangeSelector or just Title: http://jsfiddle.net/BlackLabel/pzvrg1xb/1/

**Comment by nickwinger** [comment]
Hi Pawel,

could you already fix this bug ?
Actually it's pretty urgent for us, as we want to release a first Demo to the customers.
There is another thing with the responsive options:
Everytime we use the responsive options the first time the charts are shown, they are empty.
We have to click with the mouse outside the container that is containing all the charts to make the chart visible.
I don't know how the browser is triggering the redraw here.
Calling update on the chart itself does not make it draw... maybe it's only a browser bug, because it only
happens on windows with chromium browsers and not on macos.

Can you tell me where i can look at the source code of the responsive implementation ?
Maybe then i can find how to force HighChart to redraw itself again...

Here are the options we use:
`responsive: {
        rules: [
          {
            chartOptions: {
              scrollbar: {
                enabled: false
              },
              legend: {
                enabled: false
              },
              rangeSelector: {
                enabled: false
              },
              navigator: {
                enabled: false
              }
            },
            condition: {
              callback: () => {
                return document.body.clientWidth > xs && (
                  widgetVm.widget.widgetSize !== 'full'
                );
              }
            }
          }
        ]
      }`

**Comment by nickwinger** [comment]
Also if you resize the browser width, sometimes the charts just dissappear for a certain width and then come back again.
It depends on the starting width after a browser refresh...
so i guess something is calculated with the responsive options

**Comment by pawelfus** [comment]
I will try to prioritize the issue, my apologies for the delay!

**Comment by nickwinger** [comment]
yes, but can you please tell me where in your source code i find the logic for the responsive feature.
so maybe i can figure out a workaround until final fix.
thanks

**Comment by pawelfus** [comment]
In distribution file search for `Core/Responsive.js`. In sources check [`ts/Core/Responsive.ts`](https://github.com/highcharts/highcharts/blob/master/ts/Core/Responsive.ts)

**Comment by nickwinger** [comment]
Thanks for pointing me there, sadly i couldn't figure out anything. I also downloaded the whole source code to lookup where the seetResponsive method is called, but i can't figure out any issues here.
It seems you have to know more internals of the whole update-workflow.

However on our side it's very sad that this doesn't work, as it is really important to have nice looking charts, but the first time (and sometimes) the chart line just is not drawn with this option.

Also i tried using plain css, but that also doesn't work as it is a SVG, and it doesn't automatically change height and space when setting one item to "display: none"

**Comment by nickwinger** [comment]
@pawelfus would it be possible to make a teams or teamviewer session, so i can show some behaviour and our source code.
Because it is too complicated to put it into a jsFiddle.

**Comment by pawelfus** [comment]
Hi @nickwinger 

I think the issue is not related to responsive options (those internally simply call `chart.update()`). It seems that issue is related how clip-paths are calculated in Highstock.

We can manually, after setting responsive options, resize clip-paths:
Demo: http://jsfiddle.net/BlackLabel/g4zysrwu/3/
```js
(function(H) {
  H.wrap(
    H.Chart.prototype,
    'setResponsive',
    function(proceed) {
      var chart = this;

      // Set options
      proceed.apply(chart, Array.prototype.slice.call(arguments, 1));

      // Redraw clip paths:
      chart.series.forEach(function(series) {
        if (series.sharedClipKey) {
          if (chart[series.sharedClipKey]) {
            chart[series.sharedClipKey].attr({
              height: series.yAxis.height
            });
          }

          if (chart[series.sharedClipKey + 'm']) {
            chart[series.sharedClipKey + 'm'].attr({
              height: series.yAxis.height
            });
          }
        }
      });
    }
  );
})(Highcharts);
```

Could you test it and let us know the results?

> would it be possible to make a teams or teamviewer session, so i can show some behaviour and our source code.
Because it is too complicated to put it into a jsFiddle.

Thank you for your proposition, but that kind of sessions don't help us debug/fix issues faster. What we need is a standalone Highcharts demo we can debug and test different solutions. And, finally, convert to a test, so we won't cause more regressions in future. And this issue already has a demo :)

**Comment by nickwinger** [comment]
your fix seems to work
