### ISSUE TITLE
mapbubble - colorAxis not working?

### ISSUE THREAD

**Issue by jordandev** [highcharts/highcharts#13850]
#### Expected behaviour
bubbles change color according to colorAxis

#### Actual behaviour
bubbles all the same color

#### Live demo with steps to reproduce
https://jsfiddle.net/vrc10h37/1/

#### Product version
tried both 7.1.3, 8.1.2

**Comment by pawelfus** [comment]
Hi @jordandev 

Color is applied correctly, just enable legend and compare `type`: 
- "logarithmic" - https://jsfiddle.net/BlackLabel/e4qfb9hw/
- "linear" - https://jsfiddle.net/BlackLabel/e4qfb9hw/1/

There's no many countries with population <10k so colors loooks quite similar:
![Screen Shot 2020-07-08 at 10 22 27](https://user-images.githubusercontent.com/1453926/86895688-2223f300-c105-11ea-8dcb-0a91805eb11d.png)
