### ISSUE TITLE
Accessibility bug - Screen reader is providing incorrect state as “Off” when legend toggle button is “On”

### ISSUE THREAD

**Issue by violetVo** [highcharts/highcharts#13864]
[MAS4.1.2_Screen reader is providing incorrect state as “Off” when button is “On” present under the chart on “Chart” section..wmv.zip](https://github.com/highcharts/highcharts/files/4894916/MAS4.1.2_Screen.reader.is.providing.incorrect.state.as.Off.when.button.is.On.present.under.the.chart.on.Chart.section.wmv.zip)
#### Expected behaviour
When clicking on legend button to turn is OFF, the Narrrator should say: "Toggle visibility of X - toggle OFF"

#### Actual behaviour
When clicking on legend button to turn is OFF, the Narrrator should say: "Toggle visibility of X - toggle ON"

#### Live demo with steps to reproduce
https://codepen.io/Voronetzky/pen/ExPWGVR

See the attached video.

#### Product version
Highcharts 8.1.2

#### Affected browser(s)
Edge

**Comment by sebastianbochan** [comment]
Hi @violetVo,
Thank you for reporting.

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
The current behavior is technically correct, but the label is confusing. The button is pressed "On" when the series is hidden. Especially with screen readers that announce the pressed state as "On/Off" rather than "Pressed/Not pressed". 

I think the best way to handle this is to change the label of the button from `Toggle visibility of series ...` to e.g. `Hide series ...`. Since most screen readers will announce this as a toggle button along with the state, it should be clear how to operate it.

**Comment by violetVo** [comment]
Thanks for the fix! when will this fix be publish to a new HC version?

**Comment by oysteinmoseng** [comment]
@violetVo The fix will be part of the upcoming release, expected one of the coming weeks. In the meantime you can override the text yourself by setting the [lang.accessibility.legend.legendItem](https://api.highcharts.com/highcharts/lang.accessibility.legend.legendItem) option to `Hide {itemName}`.

**Comment by aartiverma1** [comment]
@oysteinmoseng I don't want accessibility to read Togglebutton even. How can I remove that. Can you please help me into this

**Comment by oysteinmoseng** [comment]
@aartiverma1 You could do something like this: https://jsfiddle.net/qcrxk9o4/2/. This would be considered bad accessibility with the default behavior though.

**Comment by aartiverma1** [comment]
@oysteinmoseng I applied that but now it's reading 'Button' after text. Any solution to this?

**Comment by oysteinmoseng** [comment]
@aartiverma1 Not practically, no. It is a button, and Narrator will read "button" to let users know that. Do you have something else specific that you would want it to read? You could change the ARIA role of the button, or use roledescription, but Narrator will always announce something to tell the user what element type it is - as it should.

**Comment by aartiverma1** [comment]
@oysteinmoseng Currently I am using version 7.1.2 for High Chart. Will it work after updating version to 8.0.0 and using "legendLabelNoTitle" property of legend and it can remove reading "button" after using this. Anyways Thanks for your immediate reply :)

**Comment by oysteinmoseng** [comment]
@aartiverma1 No, that option sets the label for the legend when there is no legend title. The only thing you could do to avoid this would be to [disable accessibility on the legend](https://api.highcharts.com/highcharts/legend.accessibility.enabled) completely, but of course in that case a screen reader user or keyboard only user would not be able to use the legend at all.

**Comment by aartiverma1** [comment]
@oysteinmoseng Even after returning false from legendItemClick, it's still reading Toggle button at end.

**Comment by oysteinmoseng** [comment]
@aartiverma1 Yes, as mentioned above, the only way to avoid Narrator reading the type of element is to remove the element from screen readers completely. (https://api.highcharts.com/highcharts/legend.accessibility.enabled)
