### ISSUE TITLE
Indicator Slow-Stochastic not work.

### ISSUE THREAD

**Issue by JAMJAMJAMJAMJAMJAMJAM** [highcharts/highcharts#13866]
import indicators.all.js

**Comment by pawelfus** [comment]
I'm not sure what exactly the problem is, but always use our template to report bugs.

Just in case anyone meets similar problem, here is simple demo that works: https://jsfiddle.net/BlackLabel/qu4cdLa0/ - please update it to recreate the issue. Thanks!
