### ISSUE TITLE
Custom Spacing cuts the X Axis labels on first render, on reflow it fixes itself.

### ISSUE THREAD

**Issue by dragoshzava** [highcharts/highcharts#13870]
#### Expected behaviour
The chart should keep the same visual aspect on same width/height

#### Actual behaviour
Initial render is bugged, and the chart fixes itself after reflow.

Attached gif with repro.
![Basic column](https://user-images.githubusercontent.com/3819194/87037395-6c33d400-c1ec-11ea-9af0-ff00ee11b43d.gif)

#### Live demo with steps to reproduce
https://codepen.io/dragoshzava/pen/eYJrjgB

#### Product version
v8.1.2 (2020-06-16)

#### Affected browser(s)
Tested on latest Chrome/FF/Edge

**Comment by sebastianbochan** [comment]
Hi @dragoshzava,
Thank you for reporting. The reason of the issue is declared width: “935.75px” which is oversized. In this case the width of the chart should be at least 11 * 935px. I recommend you to recalculate it or skip at all.

**Comment by dragoshzava** [comment]
Hey @sebastianbochan, 
I do not fully understand why it should be at least 11 * 935 ? 11 labels with 935 pixels ?

Highcharts labels are dynamic and can wrap text in multiple columns if necessary or rotate them, like in this case 
![image](https://user-images.githubusercontent.com/3819194/87424846-fe691d00-c5dc-11ea-9914-e36cc0b52c57.png)

Unfortunately for our solution and case, we cannot set the width of the charts, that is user dependent and they set their own highcharts width/height, and the labels can be anything, from 5 characters to 100+.

example attached.
![image](https://user-images.githubusercontent.com/3819194/87425047-5142d480-c5dd-11ea-9d3d-bc3e2a6a87f4.png)

Another use case if our custom logic of filtering highcharts data ( we set points to selected false/true in the background and redraw the chart after we set the points ).
![datapine - regr](https://user-images.githubusercontent.com/3819194/87425561-26a54b80-c5de-11ea-89a5-f3490c8a2c9e.gif)

So, to answer, we cannot force users to have width depending on their labels, the width of the chart is user set.

**Comment by sebastianbochan** [comment]
Hi @dragoshzava,
In your example there is the declaration: 
```
"xAxis": [
    {
      "labels": {
        "style": {
          "color": "#666",
          "fontWeight": "normal",
          "fontStyle": "normal",
          "fontSize": "10px",
          "textOverflow": "clip",
          "overflow": "visible",
          "whiteSpace": "initial",
          **"width": "935.75px"**
        },
```
Which means that each label has width 935px. When we multiply by amount of ticks (11 in your demo) we have a final width of container. If the width is flexible, you should disable the static width of label, which is too big.

**Comment by dragoshzava** [comment]
Hey @sebastianbochan 
Ah ok, thank you very much

We do indeed need to set width of labels depending on chart type, so will find a solution.
