### ISSUE TITLE
lastVisiblePrice label is overriding the yAxis crosshairs label settings.

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13875]
#### Expected behaviour
Individual settings for the `yAxis.crosshair.label` should be respected while using `lastVisiblePrice`

#### Actual behaviour
The `yAxis.crosshair.label` background color is overridden.

#### Live demo with steps to reproduce
1/ Without `lastVisiblePrice.label` enabled the `yAxis.crosshair.label` background color is red.
2/ After enabling `lastVisiblePrice`, the background it will no longer be red.

https://jsfiddle.net/BlackLabel/0gzjyqrn/

#### Product version
8.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
FYI @sebastianbochan

**Comment by karolkolodziej** [comment]
Looks like this issue was raised in #14495 and solved via #14523 PR.
