### ISSUE TITLE
Disabling current price indicator via stock tools (yAxis.crosshairs.label + lastVisiblePrice) error

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13876]
#### Expected behaviour
No error.

#### Actual behaviour
When the `yAxis.crosshair.label` and `lastVisiblePrice` are enabled after disabling the current price indicator vis stock tools button the following error will occur: `Uncaught TypeError: Cannot read property 'setAttribute' of undefined`.

It might be related to https://github.com/highcharts/highcharts/issues/13875

#### Live demo with steps to reproduce
Steps: 
1/ Hover over the plot area
2/ Click on the 'Current Price Indicator` button 3 times
3/ Check error in the console.

https://jsfiddle.net/BlackLabel/rt5wgczo/

#### Product version
8.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
FYI @sebastianbochan
