### ISSUE TITLE
The structure diagram does not distinguish the corresponding level problem

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13874]
Here, it's impossible to tell which of the two of them belongs to the hierarchy below the CEO CDO. The hierarchy is unclear

https://jshare.com.cn/temp/rOGfrD
![111](https://user-images.githubusercontent.com/48822299/87112898-a3af8880-c29f-11ea-800c-6c05caf82b7f.png)

**Comment by sebastianbochan** [comment]
Hi @weixingcai,
Thank you for reporting. The issue has been already reported here: https://github.com/highcharts/highcharts/issues/11009.

Im closing this case as duplicate.
