### ISSUE TITLE
pie chart rendering not proper

### ISSUE THREAD

**Issue by RandomlyCreative** [highcharts/highcharts#13887]
[####](url) Expected behaviour
the chart after drilldown is not updated it seems. It should not show any issue with rendering again.

#### Actual behaviour
![issue](https://user-images.githubusercontent.com/39943529/87249115-d06bc780-c47a-11ea-99a7-1eab086d39e7.PNG)

#### Product version

I cannot post the code here due to policies but it would be really helpful if anyone had any idea on how to tackle this issue, or any insight. Thank You.

**Comment by pawelfus** [comment]
Thanks for reporting the issue @RandomlyCreative - however, without config, we won't be able to help you. I can only guess the reason behind this issue - you have multiple series, like this:
```js
series: [{
  data: ...
}, {
  data: ...
}, {
  data: ...
}]
```

Anyway, I suggest to contact our support first: https://www.highcharts.com/blog/support/ - thanks!
