### ISSUE TITLE
Zones for boosted charts do not work for an "x" zoneAxis

### ISSUE THREAD

**Issue by tzaitoun** [highcharts/highcharts#13895]
#### Expected behaviour
When configuring a **boosted** series, setting up the zones and setting the zoneAxis to **"x"** should display zones based on x-axis.

#### Actual behaviour
The current behavior is it displays zones based on the y-axis regardless if you set the zoneAxis to "x". Meaning that it will always use the plot's y-values to zone ignoring the zoneAxis.

There was this fix some time ago: #10439
Looking at it briefly I see that it checks for y values only and doesn't seem to take the zoneAxis into consideration?
https://github.com/highcharts/highcharts/blob/master/js/Extensions/Boost/WGLRenderer.js#L524

#### Live demo with steps to reproduce
https://jsfiddle.net/34bLw0m9/

#### Product version
Highcharts v8.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks!
