### ISSUE TITLE
[Highstock] Incorrect default marker behavior for line series

### ISSUE THREAD

**Issue by KrishnaKumarHariprasannan** [highcharts/highcharts#13892]
#### Expected behaviour
Marker symbols to be enabled based on data denseness

#### Actual behaviour
Marker symbols are not enabled unless explicitly specified

#### Live demo with steps to reproduce
https://jsfiddle.net/dn57yg92/2/

#### Product version
Highstock - 8.1.2

#### Affected browser(s)
Google Chrome (likely to be the same behavior in other browsers)

#### Workaround
Using plotOptions.line.marker.enabled = undefined

**Comment by pawelfus** [comment]
Thanks for reporting the issue @KrishnaKumarHariprasannan - it's a bug in our docs. By default, markers in Highstock are disabled.

@bre1470 - could you take a look? Doclet looks correct: https://github.com/highcharts/highcharts/blob/4832c0f62/js/parts/Series.js#L1293-#L1309 - but API page is wrong: https://api.highcharts.com/highstock/series.line.marker.enabled

**Comment by bre1470** [comment]
@pawelfus I believe you mean API page: https://api.highcharts.com/highstock/plotOptions.series.marker.enabled
