### ISSUE TITLE
The checkbox does not scroll when page change

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [highcharts/highcharts#13911]
#### Expected behaviour

![gif](https://user-images.githubusercontent.com/22312092/87533254-eb327c00-c6c6-11ea-9c99-cd7f21502115.gif)

<details>
<summary>Code</summary>
<pre><code>
// 修正图例复选框位置
(function (H) {
	H.wrap(H.Legend.prototype, 'positionCheckboxes', function (p, scrollOffset) {
		var alignAttr = this.group.alignAttr,
			translateY,
			clipHeight = this.clipHeight || this.legendHeight;
		if (alignAttr) {
			translateY = alignAttr.translateY;
			H.each(this.allItems, function (item) {
				var checkbox = item.checkbox,
					bBox = item.legendItem.getBBox(true),
					top;
				if (checkbox) {
					top = (translateY + checkbox.y + (scrollOffset || 0) + 3);
					H.css(checkbox, {
						left: (alignAttr.translateX + item.checkboxOffset + checkbox.x - 85 - bBox.width) + 'px',
						top: top -1 + 'px',
						display: top > translateY - 6 && top < translateY + clipHeight - 6 ? '' : 'none'
					});
				}
			});
		}
	});
})(Highcharts);
var isCheckboxEvent = false;
Highcharts.chart('container', {
	xAxis: {
		categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
	},
	legend: {
		margin: 25,
		enabled: true,
		maxHeight: 100,
		// floating: true,
		// y: 100,
		useHTML: true
	},
	responsive: {
		rules: [
			{
				condition: {
					maxWidth: 1500,
				},
			},
		],
	},
	plotOptions: {
		series: {
			events: {
				legendItemClick() {
					const $this = this;
					$this.chart.series.forEach(function(e) {
						if (e.index != $this.index) {
							e.hide();
							(e).checkbox.checked = false;
						} else {
							e.show();
							(e).checkbox.checked = true;
						}
					});
					return false;
				},
				checkboxClick(event) {
					if (event.checked) {
						event.item.show();
					} else {
						event.item.hide();
					}
					// const $this = this;
					// $this.chart.series.forEach(function(e) {
					//   if (e.checked) {
					//     e.show();
					//   } else {
					//     e.hide();
					//   }
					// });
					return false;
				},
				afterAnimate() {
					(this).checkbox.checked = true;
				},
			},
			showCheckbox: true,
			showInLegend: true,
			marker: {
				enabled: false,
			},
		},
	},
	series: [{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
		selected: true  // selected 表示选中状态，对应的复选框会选中
	},{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4].reverse(),
		selected: false,
		visible: false
	}]
});
</code></pre>
</details>

The checkbox could scroll when page change
#### Actual behaviour

checkbox always fixed

#### Live demo with steps to reproduce

miniRepo: <https://jshare.com.cn/temp/UCGf8n>

#### Product version

highcharts: 6.2.0

**Comment by sebastianbochan** [comment]
Hi @Mr-jiangzhiguo,
Thank you for reporting.

The piece of code with wrap does fixed position: 

```
(function (H) {
	H.wrap(H.Legend.prototype, 'positionCheckboxes', function (p, scrollOffset) {
		var alignAttr = this.group.alignAttr,
			translateY,
			clipHeight = this.clipHeight || this.legendHeight;
		if (alignAttr) {
			translateY = alignAttr.translateY;
			H.each(this.allItems, function (item) {
				var checkbox = item.checkbox,
					bBox = item.legendItem.getBBox(true),
					top;
				if (checkbox) {
					top = (translateY + checkbox.y + (scrollOffset || 0) + 3);
					H.css(checkbox, {
						left: (alignAttr.translateX + item.checkboxOffset + checkbox.x - 85 - bBox.width) + 'px',
						top: top -1 + 'px',
						display: top > translateY - 6 && top < translateY + clipHeight - 6 ? '' : 'none'
					});
				}
			});
		}
	});
})(Highcharts);
```

If you remove that, checkboxes will be scrolled.

Im not sure why do add these piece of code, if you don't need that. Could you elaborate?

**Comment by Mr-jiangzhiguo** [comment]
@sebastianbochan 
 In fact,, I also find this compromise method and I remove that code

By the way, is there a method make checkbox in left and could be scrolled?

**Comment by pawelfus** [comment]
We don't have API option to change that. Using wrapper, similar to the one you have is the easiest solution:
Demo: https://jsfiddle.net/BlackLabel/3qvsyxku/
```js
(function(H) {
  H.wrap(
    H.Legend.prototype,
    'positionCheckboxes',
    function(proceed) {
      this.allItems.forEach(function(item) {
        item.checkboxOffset = 0; // Set the needed offset
      });

      return proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    }
  );
})(Highcharts);
```
