### ISSUE TITLE
Logarithmic axis - negative values. 

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#13914]
#### Expected behaviour

According to this [article](https://www.highcharts.com/blog/snippets/alternative-maths-plotting-negative-values-logarithmic-axis/), the negative values should be displayed (thanks to this custom code), however, something is broken after the 8.0.4 version. 

Last working version: http://jsfiddle.net/BlackLabel/bj3dwe4t/

#### Actual behaviour

The current version, the negative points are hidden: http://jsfiddle.net/BlackLabel/cdguh2zp/

#### Product version

Highcharts JS v8.1.2 (2020-06-16)

**Comment by pawelfus** [comment]
Bisected to commit a31155e409 - not really helpful. It might be related to the way we refer `log2lin` and `lin2log` values. Any ideas @bre1470 ?

**Comment by bre1470** [comment]
Amazing. I have no idea yet, but I will look into that.

**Comment by bre1470** [comment]
For me this is the breaking commit: https://github.com/highcharts/highcharts/commit/daddf2e58c135dda5f72fb24dc8ca862552fdd68

**Comment by bre1470** [comment]
Okay, so I found the reason. It is not a bug, but just the wrong usage of the axis prototype. If you set the option `yAxis.allowNegativeLog` to true, everything is working as expected. See: http://jsfiddle.net/u3o2qaw0/

```ts
Highcharts.chart('container', {

    title: {
        text: 'Logarithmic axis with custom conversion allows negative values'
    },

    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
            'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },

    yAxis: {
        type: 'logarithmic',
        allowNegativeLog: true
    },

    series: [{
        data: [-1000, -100, -10, -1, -0.1, 0, 0.1, 1, 10, 100, 1000]
    }]

});
```

**Comment by bre1470** [comment]
@Basts @pawelfus Can you confirm the solution?

**Comment by Basts** [comment]
@bre1470
Yeah, it seems like the right option to set, however, this option doesn't exist in the API and it doesn't work in the previous versions: http://jsfiddle.net/BlackLabel/bj3dwe4t/, so I think that some update (in the API and article) is required to clearly explain to users how to use it.

**Comment by TorsteinHonsi** [comment]
Negative values on a log axis is (mathematically) not a thing, and we only keep this hidden option as a convenience so that [our demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/yaxis/type-log-negative) can work. 

Please revert this commit, as we want to keep the footprint as low as possible, and don't need to support backwards compatibility.

**Comment by bre1470** [comment]
@TorsteinHonsi Please note, that without this change the LogarithmicAxis composition always have redundant conversion functions directly on the axis to allow the demo in its current state to work with ES6. See https://github.com/highcharts/highcharts/blob/master/ts/Core/Axis/LogarithmicAxis.ts#L227-L233
