### ISSUE TITLE
Can we have chart like this ..?

### ISSUE THREAD

**Issue by esplorado** [highcharts/highcharts#13918]
![Annotation 2020-07-16 164621](https://user-images.githubusercontent.com/54854569/87665059-eaabeb00-c783-11ea-9821-a24a7faef818.png)

**Comment by pawelfus** [comment]
Hi @esplorado 

Thanks for contacting us. Some parts of the chart can be generated with options, others require custom renderer shapes (e.g. background under labels). Good starting point: https://www.highcharts.com/demo/polar-spiderFor more details, please contact our support:  https://www.highcharts.com/blog/support/ - we use GitHub issues as a bug tracker. Thanks!
