### ISSUE TITLE
Organization Chart, wrong position for children with normal layout

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#13915]
#### Expected behaviour
Nodes are placed below their parent node if possible.
![image](https://user-images.githubusercontent.com/9820084/87642547-5c6b4100-c752-11ea-9117-d6733ff3c139.png)

#### Actual behaviour
Position of node's children seems off. 
Both when having mixed layouts in a level or when having all normal layout in a level.
Nodes are shifted to the right.
![image](https://user-images.githubusercontent.com/9820084/87640814-f54c8d00-c74f-11ea-8eea-c804ebe0c781.png)

#### Live demo with steps to reproduce
All normal layout: https://jsfiddle.net/alvarezg/rb3ftuLy/
Mixed normal and hanging: https://jsfiddle.net/alvarezg/g7aepx49/

#### Product version

Highcharts, Highstock 8.1.2

**Comment by sebastianbochan** [comment]
Hi @alvarezguille,
Thank you for reporting.

As a workaround, you can declare a negative [offset](https://api.highcharts.com/highcharts/series.organization.nodes.offset).

Demo:
- https://jsfiddle.net/BlackLabel/fakhdm18/

**Comment by alvarezguille** [comment]
Thanks for the quick answer and the workaround! 🙇‍♂️

**Comment by pawelfus** [comment]
Hi @jethas-bennettjones 

You can change order of nodes in a tree: https://jsfiddle.net/BlackLabel/bws9o75a/1/ or change layout: https://jsfiddle.net/BlackLabel/bws9o75a/2/

**Comment by jethas-bennettjones** [comment]
Hi @pawelfus 

Thanks for the tips, though the graph I used as an example is a lot simpler than the one I'm trying to put together.
Here is an idea of the problem that I'm faced with: 
![image](https://user-images.githubusercontent.com/62298251/91496188-ed1c5d00-e878-11ea-9333-f8e3d94527a5.png)

We're also trying to do this programmatically, so having each node have it's own layout element might not be feasible, especially since the end goal is to have this be user-driven.

**Comment by pawelfus** [comment]
Thanks for providing more details! I don't see any other workaround you can use at this moment

**Comment by jethas-bennettjones** [comment]
Hi @pawelfus. Is there a potential roadmap for when this might get fixed?

**Comment by pawelfus** [comment]
I can't provide any estimate, but it seems we forget to label the issue (or GH tricked us..) so it was never discussed internally. I will mention this issue on the next meeting, if this will get into the planned releases, ticket will get proper status.

**Comment by jethas-bennettjones** [comment]
Hi @pawelfus, is there any update on this?

**Comment by pawelfus** [comment]
We didn't find any good solution for your chart. With current algorithm, it's quite tricky issue with correctly positioning such datasets. We might need to implement this from scratch (different algorithm perhaps?), unlikely to happen in the nearest feature. I will highlight this issue again, on the next meeting, perhaps we will come up with some new ideas.

**Comment by pawelfus** [comment]
We think this issue can get an acceptable solution with:
- forcing all nodes that are children of the `hanging` layout to use `hanging` layout too
- making space for all hanging children, translating other nodes to the bottom

This is the idea in action:
- https://jsfiddle.net/BlackLabel/89z2x40y/
- https://jsfiddle.net/BlackLabel/nc3zrgq6/2/

Mixing `normal` and `hanging` layouts is not an easy task (see image above).

What do you think @jethas-bennettjones ? Could you test my solution above and let us know the results?

**Comment by brentbalog** [comment]
I'm facing the same issue as discussed [here](https://www.highcharts.com/forum/viewtopic.php?f=9&t=47792&p=172295#p172295).  Alternating hanging and normal layouts only gets you so far, and manual offset adjustments is not a viable solution for us.  It seems like this has been WIP for awhile, what process do you use to prioritize these issues into your dev process?  Thanks,
