### ISSUE TITLE
Label display problem

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13925]
#### Expected behaviour
Label display complete

#### Actual behaviour
When I customized the tag for the x axis, when rotation is equal to 0, the tag will not show up

https://jshare.com.cn/temp/4HGfzA

![11](https://user-images.githubusercontent.com/48822299/87765846-e5fe3a00-c84a-11ea-9a67-b269f62d90a0.png)

**Comment by pawelfus** [comment]
Thanks for reporting this issue @weixingcai 

Simplified demo (without 3d): https://jsfiddle.net/BlackLabel/5rjzyuLq/

**Workaround:**
Disable  [`xAxis.labels.style.textOverflow`](https://api.highcharts.com/highcharts/xAxis.labels.style) option: https://jsfiddle.net/BlackLabel/5rjzyuLq/2/

**Comment by weixingcai** [comment]
Overlap tenderness occurs when the textOverflow is none and the data is large

https://jshare.com.cn/temp/4HGfzA
![222](https://user-images.githubusercontent.com/48822299/87783992-17d1c980-c868-11ea-97e5-c2b57b0487bb.png)

**Comment by pawelfus** [comment]
Good point @weixingcai 

Then for now I suggest to enable auto rotation (remove `labels.rotation: 0`).
