### ISSUE TITLE
Highcharts and the JS inject code

### ISSUE THREAD

**Issue by jnhartshorne1994** [highcharts/highcharts#13923]
Hi there, great library so thanks for the hard work!

We have a website whereby the client would like to be able to inject the Highcharts charts they've created (using the Everviz online editor) into their site.

They've been doing this using iframe elements in the past however we are having issues printing those. As a result we are now trying to use the JS inject method that is also available, however, when we go down this route, of simply injecting the below code, we get a Highcharts is not defined error. We are also using requirejs on the site which seems to be causing this, but I don't understand why that would prevent the script below from working?

Any help would be very much appreciated!

`<div id="highcharts-6gfXhtnJm"><script src="https://app.everviz.com/inject/6gfXhtnJm/" defer="defer"></script></div>`

**Comment by pawelfus** [comment]
Hi @jnhartshorne1994 

Thank you for reporting the issue. Did you contact Everviz support? We use this repo as bug tracker for Highcharts library, not Everviz :)

**Comment by sebastianbochan** [comment]
Hi @jnhartshorne1994,
Please contact with our supporters by email: support@everviz.com. Someone will assist you and solve your problem.

**Comment by jnhartshorne1994** [comment]
Thanks @pawelfus. I'll get in touch with them and go from there.
