### ISSUE TITLE
Highcharts gets slow in v8.1.2 as compared v6.2.0

### ISSUE THREAD

**Issue by geekboy0801** [highcharts/highcharts#13930]
Does anyone here notice that highcharts gets slow in the latest version (8.1.2)? 

We've been using Highcharts(6.2.0) in our React.js project, we are planning to bump the highcharts version to the latest one.(8.1.2)  While testing the version upgrade, we noticed that Highcharts got slow in many aspects such as the **responsiveness of the tooltip while hovering**.

Hope your advice on here.

**Comment by pawelfus** [comment]
Hi @geekboy0801 

No, nobody reported on github similar issues. One of the features added in v7.1 was [`series.states.inactive` option](https://api.highcharts.com/highcharts/series.line.states.inactive.enabled) - could you try disabling it? Thanks!

Just in case, check our suggestions for improving performance: https://www.highcharts.com/docs/getting-started/frequently-asked-questions#how-can-i-get-the-best-performance-out-of-highcharts

If none of the above helps, please recreate issue in jsFiddle or contact our support: https://www.highcharts.com/blog/support/

**Comment by geekboy0801** [comment]
Thanks for the quick reply. Actually, we already tried all those things. 
It usually works good but for the apps that have 60+ series with ~1000 data points in each series, the responsiveness of tooltips is not as smooth as was in v6.2.2.
Let me try to provide the live code link so that you can have a look.

**Comment by geekboy0801** [comment]
I figured out the reason why tooltips are not responsive on my browser. I was putting some data in the console when rendering chart for the debug purpose. 😜 When I removed it, it's gone!!!
Thanks for your attention, @pawelfus

**Comment by pawelfus** [comment]
Thanks, I'm glad you resolved that! :) 

Closing the issue
