### ISSUE TITLE
Typescript ignores map.joinBy property

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13932]
#### Expected behaviour
The `map.joinBy` property should be taken into account while type checking.

#### Actual behaviour
TypeScript ignores the `map.joinBy` and throws warning even the config is correct (copy & pasted from official demo)
```typescript
Type '{ code: string; }[]' is not assignable to type '(number | [string, number] | SeriesMapDataOptions)[]'.
Type '{ code: string; }' is not assignable to type 'number | [string, number] | SeriesMapDataOptions'.
Type '{ code: string; }' has no properties in common with type 'SeriesMapDataOptions'.
```

#### Live demo with steps to reproduce
https://stackblitz.com/edit/typescript-gmc91n

#### Product version
8.1.2

#### Affected browser(s)
All

**Comment by mateuszkornecki** [comment]
FYI @bre1470

**Comment by andrescornejo** [comment]
To whom it may concern:
I managed to work around this issue by changing 'highcharts.d.ts'.

In line 55560 I modified:
```joinBy?: string;```
to
```joinBy?: string|Array<string>;```

With that change I can now, for instance, use:
```joinBy: ['iso-a2','hc-key'],```

And the data is displayed correctly.

This was a pain to realize, since I am very new to typescript and I thought I was making some sort of mistake. When in reality, it was the library that had something wrong!

Hope it helps.
Cheers.

**Comment by alexburner** [comment]
@bre1470 @mateuszkornecki @TorsteinHonsi I see you closed this with https://github.com/highcharts/highcharts/pull/14071

However, I'm still seeing this issue in Highcharts 10.3.3:
```
Type '{ code: string; }[]' is not assignable to type '(number | [string, number] | SeriesMapDataOptions)[]'.
  Type '{ code: string; }' is not assignable to type 'number | [string, number] | SeriesMapDataOptions'.
```

Here it is in an updated version of the original example:
<img width="1191" alt="Screenshot 2023-03-13 at 11 03 24 AM" src="https://user-images.githubusercontent.com/409114/224789599-4205156f-516c-4aef-8746-0e933954bb68.png">
https://stackblitz.com/edit/typescript-98ycow?file=tsconfig.json,index.ts

_(Note: for some reason you may have to tweak `tsconfig.json` and save it to make the `esModuleInterop` error go away in `index.ts` — I've just been commenting & uncommenting `"strict": true` as needed)_

Should I be doing something differently?
