### ISSUE TITLE
Responsive seems to mess up markers

### ISSUE THREAD

**Issue by brunnerh** [highcharts/highcharts#13931]
I tried the responsive trigger on one of the official demos (time data with irregular intervals) and the marker gets resized correctly when the charts gets too small, but when the chart is enlarged again, the markers on the lines disappear and the markers in the legend become larger than they should be.

#### Expected behaviour
Return to initial state after exiting responsive rule condition:

![image](https://user-images.githubusercontent.com/834235/87926785-7c687080-ca82-11ea-9b12-e0716cb89b2b.png)

#### Actual behaviour
- Missing markers on lines
- Larger markers in legend

![image](https://user-images.githubusercontent.com/834235/87926754-71154500-ca82-11ea-8c47-85600f722d74.png)

#### Live demo with steps to reproduce
[Demo on website](https://www.highcharts.com/demo/spline-irregular-time)
[Fiddle](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/spline-irregular-time)

Steps:
- Resize to below 500px width
- Resize to above 500px width

#### Product version
Highcharts JS v8.1.2 (2020-06-16)
Also checked Highcharts JS vmaster (2020-07-13)

#### Affected browser(s)
Chrome 84.0.4147.89 (Official Build) (64-bit)
Firefox 78.0.2 (64-bit)

**Comment by pawelfus** [comment]
Thanks for reporting the issue @brunnerh 

**Workaround:**
Set `plotOptions.series.marker.radius` in options too (not only in `responsive` options). Demo: https://jsfiddle.net/BlackLabel/h82n7tr1/
