### ISSUE TITLE
Some series go beyond yAxis (are not clipped) after y zooming

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#13939]
#### Expected behaviour
I expect series to be clipped after zooming so it is visible only inside yAxis (yAxis.height is set).

#### Actual behaviour
The series goes beyond its yAxis.
It works fine for **line** series, but fails for **ohlc** or **candlestick**

**ohlc**:
![image](https://user-images.githubusercontent.com/23310742/88067051-c9c20c00-cb6e-11ea-8d3b-422edd6cc964.png)

**line**:
![image](https://user-images.githubusercontent.com/23310742/88067123-de9e9f80-cb6e-11ea-861b-bb8a8fa0a33e.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/d2c368u9/

#### Product version
8.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Related to #7711

**Comment by pawelfus** [comment]
*Internal note:*
This should be fixed on the series level, for example by implementing clipping for markers. Might apply to candlestick series too. Related issue (with tooltip) should be resolved separately.

**Comment by khlieng** [comment]
Fixed since 8.2.2 (#14258).
