### ISSUE TITLE
Page crashes with memory limit when xAxis intervals are out of range

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#13934]
#### Expected behaviour
Chart should be displayed without any points. 

#### Actual behaviour
When `plotOptions.series.dataGrouping` is enabled, the page crashes. When disabled the chart is rendered.

#### Live demo with steps to reproduce
http://jsfiddle.net/brkxgwq8/

#### Product version
Highstock JS v8.1.2 (2020-06-16)

#### Affected browser(s)
Chrome, Firefox

**Comment by pawelfus** [comment]
Thanks for reporting this issue @govinda18 

Broken since v7.0.2

*Internal note:*
Bisected to commit f32d7a00ee (calculated range now equals 0, because min and max are equal).
