### ISSUE TITLE
boost.useGPUTranslations is super slow. There is not much difference to a disabled boost mode

### ISSUE THREAD

**Issue by benzanderuni** [highcharts/highcharts#13944]
#### Expected behavior
Demo of the problem with a jsFiddle instance: https://jsfiddle.net/1prh50nc/
The expectation is that the chart is reacting faster. The chart will show and if I click at a series in the legend to disable a series I expect that the chart is getting faster because fewer points are shown. If I hide more series then the browser gets slower and slower. Chrome dies after hiding the third or fourth series.

#### Actual behaviour
If I hide more series then the browser gets slower and slower. Chrome dies after hiding the third or fourth series.

#### Live demo with steps to reproduce
https://jsfiddle.net/1prh50nc/

#### Product version
newest version

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @benzanderuni 

Thanks for reporting the issue. I'm unable to open your demo - probably issue with jsFiddle. Could you check if you included `boost` module in the first place? Link: https://code.highcharts.com/modules/boost.js
