### ISSUE TITLE
xAxis labels style beeing ignored. (BUG)

### ISSUE THREAD

**Issue by NicolasZim** [highcharts/highcharts#13942]
#### Expected behaviour
Style apply on **labels** and ignore the normal style provided by highcharts.

#### Actual behaviour
Some attributes provided in `xAxis: { labels: { style :{} } } } ` are ignored by highcharts.

So far away i tested:
- color
- fontWeight
- textDecoration
#### Live demo with steps to reproduce

[Live Demo](https://stackblitz.com/edit/grouped-stacked-column-highcharts-problem2?file=Chart.tsx)
You can find inside demo exactly where happens by searching with Ctrl + F with **STYLE IGNORED**.

I lost some time to note that my styles are getting ignored, i already tried to force style inside of `format` or `formatter` but some attributes still getting ignored with or without `!important`, i guess it's because the parent `span` has more effect than `!important` attribute in child elements.
The `span` i quoted it's where i'm guessing the `xAxis: { labels: { style :{} } } } ` affect.
#### Product version

```
"highcharts": "^8.1.0",
"highcharts-react-official": "^3.0.0",
```
#### Affected browser(s)
Current tested on:
Version 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit) -- Brave Browser
78.0b1 (64-bits) -- Firefox Dev

Also i'm using a lot this live demo i provided, it contains all my context and use cases.

**Comment by pawelfus** [comment]
Hi @NicolasZim 

Styles are ignored, because of the drilldown-category styles, see: https://api.highcharts.com/highcharts/drilldown.activeAxisLabelStyle

Demo: https://stackblitz.com/edit/grouped-stacked-column-highcharts-problem2-ktrral?file=Chart.tsx
