### ISSUE TITLE
Offline exporting color axis to pdf with 'highlighted' value results in a file reader can't open

### ISSUE THREAD

**Issue by l4z** [highcharts/highcharts#13948]
#### Expected behavior
Exporting a chart (with the below described properties) offline, to pdf should result in a well-behaved pdf file, containing the chart roughly as it appears in the browser.

Scenario:
Have a chart with a color axis, with custom stops defined. Using the stops, 'highlight' a special value with a different color that is not part of any gradient (see config in fiddle)

#### Actual behavior
Exporting the above described chart offline to pdf results in a file Adobe reader can't open properly (a warning is shown, dismissing it will show the chart with many parts missing, typically all the axes). Browsers do open it, but the color axis (apart from the ticks and labels) appears transparent (tried with Chrome and Edge).

#### Live demo with steps to reproduce
https://jsfiddle.net/L444Z/fyctm67q/14/

Steps:
1. Click the hamburger and then click download pdf document menu item
2. Open the result file with either Acrobat reader or your browser (they produce different behavior as described above)

#### Product version
Highcharts 8.1.2

**Comment by sebastianbochan** [comment]
Hi @l4z,
Thank you for reporting. I was able to reproduce it too.

Details:
- Adobe Reader DC
- MacOSX 10.14.6

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
Only happens with legend enabled, and seems to happen because the two first color axis stops have the same threshold value. One easy workaround could be to ensure there is a small difference between them: https://jsfiddle.net/oysteinmoseng/rkxsua2e/1/.

**Comment by l4z** [comment]
Thanks @oysteinmoseng! I ended up with similar workaround myself. This results in a small gradient section on the color axis, which is not present in browser - which is very strange, but ok-ish. 

Anyhow, something weird is going on here, thought you guys would be interested - that's why I posted. Could also be a problem in one of the 3rd party pdf libs used.

**Comment by oysteinmoseng** [comment]
@l4z Absolutely, and thanks for reporting! We should test it with the latest versions of jsPDF and svg2pdf as well, it could very well be an issue there as you mention.

Another workaround that would avoid the gradient in the PDF could be something like this: https://jsfiddle.net/oysteinmoseng/hfagu61p/. It would involve preprocessing the data into two series, where one uses the color axis and the other a fixed color.

**Comment by goransle** [comment]
Seems to be an issue with the linear gradient implementation in svg2pdf. I submitted an issue [on their repo](https://github.com/yWorks/svg2pdf.js/issues/151).

*Internal note*:
Looks like svg2pdf from [v2 onwards](https://github.com/yworks/svg2pdf.js/releases) has breaking changes for our implementation.
