### ISSUE TITLE
Y axis labels don't redraw when supplied with new values (noticed in stacked column charts)

### ISSUE THREAD

**Issue by bbrudnoy** [highcharts/highcharts#13946]
#### Expected behaviour
I'd like to update Y axis labels on a stacked column chart some time after the chart was originally drawn. For that I'm introducing a new Y axis label formatter and calling `chart.redraw()`. I've expected this to be sufficient for new labels to appear.

#### Actual behaviour
I encountered a condition where new labels aren't rendered, and that's when the Y axis `tickInterval` is `1` (see live demo).

#### Live demo with steps to reproduce
https://codepen.io/rlcreator/pen/yLeGdeo

#### Product version
Highcharts JS v8.1.2; issue also exists when master is used.

#### Affected browser(s)
Chrome 84.0.4147.89, Firefox 78.0.2

**Comment by pawelfus** [comment]
Hi @bbrudnoy 

Thanks for reporting the issue, but this is not a correct way to update formatter. Instead, you should use our API:
- `chart.update()` or `yAxis.update()`: https://api.highcharts.com/class-reference/Highcharts.Chart#update and https://api.highcharts.com/class-reference/Highcharts.Axis#update
- `yAxis.labels.formatter` option:  https://api.highcharts.com/highcharts/yAxis.labels.formatter

Demo: https://codepen.io/pawelfus/pen/gOPEOQP
