### ISSUE TITLE
Tooltip gets rendered on the wrong side

### ISSUE THREAD

**Issue by nickwinger** [highcharts/highcharts#13943]
If you have a small width for the chart and set tooltip/outside to true and put the chart on the right side of the screen
the tooltip gets rendered on the right, therefore you don't see it. it should be rendered on the left side

#### Expected behaviour
With a small chart and tooltip outside true, when there is no space on the right, the tooltip should be rendered on the left side

#### Actual behaviour
the tooltip gets rendered on the right side and exceeds the screen, although there is space on the left

#### Live demo with steps to reproduce
http://jsfiddle.net/nickwinger/qtg4a8rL/1/

#### Product version

latest

**Comment by pawelfus** [comment]
Thanks for reporting

**Comment by nickwinger** [comment]
we still have this issue, any plans when this will be solved ?
(it also appears with the tooltip on the bottom)

**Comment by pawelfus** [comment]
Hi @nickwinger 

Issue is in our backlog, that means it's priority for us to fix this issue. My apologies for the delay - we are in the middle of migration to typescript.
