### ISSUE TITLE
Highcharts Stock - Line with markers is not loading and throws error

### ISSUE THREAD

**Issue by sreejith-ms** [highcharts/highcharts#13957]
#### Expected behaviour
Highcharts Stock - Line with markers and shadow

#### Actual behaviour
Chart not loading
![image](https://user-images.githubusercontent.com/13817581/88457020-b9789c80-cea0-11ea-9a31-e74bbaa163ab.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/gjcfb205/1/

#### Product version
Highstock JS v8.1.2

#### Affected browser(s)
Google Chrome, Firefox

**Comment by pawelfus** [comment]
Thanks for reporting the issue @sreejith-ms 

This is caused by mixing object and array configs and exceeding the default [`turboThreshold=1000`](https://api.highcharts.com/highstock/series.line.turboThreshold). To solve this, disable `turboThreshold` or increase it's value.

**Comment by sreejith-ms** [comment]
Thanks @pawelfus, disabling `turboThreshold` solves the issue.

**Comment by pawelfus** [comment]
*Internal note:*
We should replace the error above with more descriptive one (https://www.highcharts.com/errors/12/).
