### ISSUE TITLE
Dosc: staticScale demo is not working correctly

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#13958]
#### Expected behaviour
Change `staticScale` properly.

#### Actual behaviour
Can't change the `staticScale` - module is missing.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/t63a5emu/

#### Product version
Highcharts JS v8.1.2 (2020-06-16)

#### Affected browser(s)
ALL

**Comment by pawelfus** [comment]
This is the URL with issue: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/gantt/xrange-series/demo/

Actually we have two issues here (correct me if I'm wrong!):
- in CSS height is set to 300px
- `highcharts.js` is used, while `highcharts-gantt.js` should be used

**Comment by karolkolodziej** [comment]
Thank you for this correction, my demo was a workaround, but the real issue is in the demo you have provided. 

Yep!
The CSS height property doesn't make sense in this case, and the modules should be changed.
