### ISSUE TITLE
After click on print, chart will go into left side

### ISSUE THREAD

**Issue by dharmatv** [highcharts/highcharts#13964]
Hi

Whenever click on the print chart menu item present in the small modal, In browser chart will move into the left side and then the print modal will open. In the print modal, we have two options like cancel and print, In which I click on any of those two options It will redirect back to chrome(browser) then the chart will be restored. So I don't know this feature is default or not.
If it's the default - it's okay. But I need a chart that will be same positioned without moving into the left side while clicking on print option
If it's not - could u please suggest any solution

E.g., https://www.highcharts.com/demo/line-basic

**Comment by pawelfus** [comment]
Hi @dharmatv 

Yes, that's how printing works. Browsers' printing API prints whatever is rendered, so we hide all elements except chart, then restore them. There's no option to change how our `chart.print()` implementation works, however you can implement your own `print` method, see how to define context menu items: https://api.highcharts.com/highcharts/exporting.buttons.contextButton.menuItems - simplified demo: https://jsfiddle.net/BlackLabel/0ug6pxyL/
