### ISSUE TITLE
Highcharts.ajax does not support post/put

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#13965]
#### Expected behaviour

Highcharts.ajax should be compatible to every HTTP method.

#### Actual behaviour

Highcharts.ajax does only support the HTTP get method.

#### Live demo with steps to reproduce

Google API v4 requires broader support: https://jsfiddle.net/BlackLabel/f3zt5ok1/

#### Product version
Highcharts. v8.1.2

#### Affected browser(s)
all

**Comment by bre1470** [comment]
No, it is not true. You can define put/get with the ajax attributes.

**Comment by sebastianbochan** [comment]
In the TS i do not see the `put` option:

https://github.com/highcharts/highcharts/blob/e06fb000fa9fc2ad816a9c5ec4f29e311d90bf9b/ts/mixins/ajax.ts#L40

**Comment by bre1470** [comment]
Okay, the typing has to be adjusted. `head` is also missing. The implementation is supporting every function though.
