### ISSUE TITLE
The graph doesn't show up first few datetime x-axis values (30min to one hour)

### ISSUE THREAD

**Issue by shabareesh** [highcharts/highcharts#13961]
The Chart shows incorrect x-axis after 30 mins of an hour.

Mostly doesn't work with India timezone.

#### Live demo with steps to reproduce
https://codepen.io/shabareesh/pen/jOWRRYa

Could someone please help me to solve this issue?

Thanks in advance!!

![image](https://user-images.githubusercontent.com/2136300/88548188-5de31600-d03c-11ea-8d3f-1246581f8492.png)

**Comment by pawelfus** [comment]
Thanks for reporting this bug @shabareesh 

Actually it's a regression since v8.0.1. v8.0.0 used to work fine.

**Simplified demo:**
https://jsfiddle.net/BlackLabel/bp4hrsn8/

*Internal note:*
Bisected to commit 60f376dc64
FYI @TorsteinHonsi

**Comment by shabareesh** [comment]
Thanks @pawelfus I have downgraded it to v8.0.0 and it worked.

**Comment by akash18m** [comment]
This change is not released yet I guess! Any idea by when this change will be Release? @khlieng @TorsteinHonsi
