### ISSUE TITLE
Highmaps: Exported PDF files cannot be opened in Adobe Reader

### ISSUE THREAD

**Issue by jlherren** [highcharts/highcharts#13963]
#### Expected behaviour
The exported PDF file should be a valid PDF file.

#### Actual behaviour
The generated PDF file contains NaN values which makes Adobe Reader choke on it. Here's a snippet of that produced PDF file (line 91 - 99):

```
1. 0. 0. 1. -10. -53. cm
q
q
0.10 0.10 0.45 rg
NaN w                      <------ Faulty line
0.80 G
1. 0. 0. 1. 10. 53. cm
513.7142857142857792 146.1861751152073907 m
517.0285714285714675 140.0921658986175089 l
```

Adobe Reader version: 2020.009.20074.

#### Live demo with steps to reproduce
Reproducible with highmaps' very own demo page: https://www.highcharts.com/demo/maps/color-axis
In the menu select "Download PDF document". Open the PDF with Adobe Reader.

Note that Chrome's and Firefox' built-in PDF viewers can still open the file.

#### Product version
Highmaps 8.1.2

#### Affected browser(s)
Chrome & Firefox, probably others.

**Comment by sebastianbochan** [comment]
Hi @jlherren,
Thank you for reporting the problem. It looks like as known bug, which has been already reported here: https://github.com/highcharts/highcharts/issues/13948.

**Comment by jlherren** [comment]
I suppose it could be the same bug, even though the error in the PDF looks a bit different. I'll close this for now and subscribe to the other bug. Thanks!
