### ISSUE TITLE
xhtml2pdf is not loading the javascript in my html template

### ISSUE THREAD

**Issue by FerociousCentaur** [highcharts/highcharts#13962]
####I am using xhtml2pdf to convert a html template (in django) to pdf in background and mail those pdfs to people.My html template contains highcharts within script tags.  

####the pdf sent to mail  contains everthing but the highcharts.

**Comment by pawelfus** [comment]
Hi @FerociousCentaur 

Thanks for reporting the issue. Could you contact our support team first? See: https://www.highcharts.com/blog/support/ - they will help you to find the root of the issue and decide if this is a bug in Highcharts, or perhaps in xhtml2pdf lib. Thanks!

**Comment by FerociousCentaur** [comment]
Hi @pawelfus .
Thank u so much for ur reply.
I went to highcharts forum and couldnot find any link to post an issue in there.There was a link which redirected me here on github.

**Comment by pawelfus** [comment]
Yes, the link was saying "report a bug" :) I'm afraid your question does not qualify as a bug. Just checked - it seems that `xhtml2pdf` does not support javascript in HTML, library is able to render static content only. Did you contact authors of `xhtml2pdf` how to use it with JS libraries? I might be wrong. Not that I am no experts in `xhtml2pdf` lib. 

I don't know if you checked other html2pdf libraries, but if you need to use `xhtml2pdf`, and it really does not work with generating HTML on the fly, then you cna do the following:
- before sending en email, generate chart image (can be base64 for example): https://www.highcharts.com/docs/export-module/render-charts-serverside
- when creating html website to use it `xhtml2pdf`, inject image into the HTML. I don't know how to do that, you must ask `xhtml2pdf` support at this point, sorry
