### ISSUE TITLE
Download builder generates invalid bundles

### ISSUE THREAD

**Issue by sm-Fifteen** [highcharts/highcharts#13971]
A number of elements from `H`/`parts/Globals.js` are reported as `undefined` when loading files generated by the [Download Builder][1].

#### Steps to reproduce
1. Using the [Download Builder][1], create a bundle containing all available modules (with the expectation that this combination cannot result in missing dependencies).
2. Save that file to a directory and create a simple html file that loads it: `<html><head><script src="./highcharts-custom.js"></script></head></html>`
3. Open said HTML file in the browser of your choice and look at the JS console.

#### Expected behaviour
The file should load correctly and no errors should be logged.

#### Actual behaviour
The following error is reported while loading `ColorAxis.js`:

```
Uncaught TypeError: can't access property "prototype", Series is undefined
```

Looking at the site where the exception was thrown, this is because `H.Series` appears to be undefined while the module is loading.

#### Product version
* Highcharts 8.1.2
* Download builder from highcharts.com
* Possibly [the section of the doc on custom builds](https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files) (untested)

#### Affected browser(s)
* Firefox 79
* Chrome 84

[1]:https://www.highcharts.com/blog/download/#downloadbuilder

**Comment by pawelfus** [comment]
Thanks for reporting the issue @sm-Fifteen 

@bre1470 - can you check it?

**Comment by sm-Fifteen** [comment]
There might be other locations than just ColorAxis where this occurs, this just happens to be the first one in the loading order when all the modules are included in the build.
