### ISSUE TITLE
v8.1.2bug:column render wrong when set polar:true and inverted:true

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13973]
#### Expected behaviour
chart can render right

### ****when  set polar:true and inverted:true,chart render wrong**, but it's works right in v8.1.0**

![image](https://user-images.githubusercontent.com/48822299/88889851-5063a100-d273-11ea-8b3d-9072a7ea41cc.png)
**only set  polar:true**
![image](https://user-images.githubusercontent.com/48822299/88889893-5eb1bd00-d273-11ea-8012-75394ddb0a74.png)
**only set  inverted:true**
![image](https://user-images.githubusercontent.com/48822299/88889937-6ffac980-d273-11ea-85c0-a6419f78de38.png)

#### Product version

"highcharts": "8.1.2",
"highcharts-grouped-categories": "^1.1.3",
"highcharts-regression": "^2.0.1",
"highcharts-vue": "^1.3.5",
#### Affected browser(s)
正在更新 Google Chrome
版本 83.0.4103.116（正式版本） （64 位）

**Comment by pawelfus** [comment]
Hi @weixingcai 

Thank you for reporting the issue, but please, always provide live demo. Our official demo looks fine: https://www.highcharts.com/demo/polar-radial-bar

**Comment by weixingcai** [comment]
@pawelfus **live demo** ： https://codesandbox.io/s/highcharts-vue-demo-puyn9?file=/src/components/Chart.vue

**Comment by weixingcai** [comment]
@pawelfus 
**live demo**  https://codesandbox.io/s/highcharts-vue-demo-puyn9?file=/src/components/Chart.vue

**Comment by pawelfus** [comment]
Thanks for the demo!

**Demos without Vue:**
- https://jsfiddle.net/BlackLabel/xq59Ltdj/7/
- simplified: https://jsfiddle.net/BlackLabel/xq59Ltdj/8/ (but in this demo we can remove `stacking` and chart will be fine - might be different issue?)

**Workaround:**
Use `chart.update()` instead: https://codesandbox.io/s/highcharts-vue-demo-xst3d?file=/src/components/Chart.vue

Bisected to commit 57ce06ee44 - FYI @TorsteinHonsi

**Comment by khlieng** [comment]
Fixed on master (#14414).
