### ISSUE TITLE
highcharts credits being shown in image even after setting it false.

### ISSUE THREAD

**Issue by FerociousCentaur** [highcharts/highcharts#13972]
#### I am making a post request to www.exports.highcharts.com as mentioned in https://www.highcharts.com/docs/export-module/export-module-overview
I have set "credits": {
                        "enabled": false
                    }, in my json file. which should turn off the highcharts credits in returned image

**Comment by pawelfus** [comment]
Hi @FerociousCentaur 

To me it works fine: https://jsfiddle.net/BlackLabel/79wskar8/

> the image comes with a small toggle button icon at yop -right corner which i dont want

I don't know what you mean. Perhaps you want to use [`exporting.enabled`](https://api.highcharts.com/highcharts/exporting.enabled) option? That's the icon we have at top right corner in our images, but by default it's disabled in exported images..

Did you contact our support first? Our GitHub tickets are reserved for bug reports, not questions. If my demo above won't help you, please contact our support with the details. Thanks!
