### ISSUE TITLE
xAxis covers the graph,when polar: true

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#13979]
#### Expected behaviour

**xAxis does not cover the graph,xAxis  and graphics are displayed separately**

#### Actual behaviour
![image](https://user-images.githubusercontent.com/6789138/88994273-9162c080-d31a-11ea-9139-ff6a8a29478e.png)
#### Live demo with steps to reproduce

https://jshare.com.cn/temp/IIGfxW
#### Product version

highcharts：v8.1.0 and highcharts：v8.1.2

**Comment by sebastianbochan** [comment]
Hi @wjhcc2018,
Thank you for reporting. For general [support](https://www.highcharts.com/support) questions please use forum / stackoverflow or email.

ps. The issue is caused by the `xAxis.offset` param.
