### ISSUE TITLE
Marker Cluster module with xAxis min/max undefined and data set to empty array - chart does not display

### ISSUE THREAD

**Issue by codywsears** [highcharts/highcharts#13981]
#### Expected behaviour
The chart will show with no data until the series data is updated.

#### Actual behaviour
Nothing renders. Seems like the module gets stuck in an infinite loop.

#### Live demo with steps to reproduce
https://codepen.io/codywsears/pen/jOWgBJy

#### Product version
Highcharts v8.1.2

#### Affected browser(s)
Found on chrome

**Comment by wchmiel** [comment]
Thanks for reporting the issue @codywsears 

As a workaround you can add this code:
```js
(function(H) {
  var baseGeneratePoints = H.Series.prototype.generatePoints;

  H.wrap(H.seriesTypes.scatter.prototype, 'generatePoints', function(proceed) {
    if (this.data.length) {
      proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    } else {
      baseGeneratePoints.apply(this, Array.prototype.slice.call(arguments, 1));
    }

  });
})(Highcharts);
```
