### ISSUE TITLE
plotOptions.timeline.lineWidth missing from API docs

### ISSUE THREAD

**Issue by nk9** [highcharts/highcharts#13994]
[The API docs](https://api.highcharts.com/highcharts/plotOptions.timeline) make no mention of the `lineWidth` property, which can be used to adjust the width of the line of each series on a timeline. This setting is really essential when working with multiple series on a timeline, since otherwise the default lines with the various colors overlap lines and markers and look pretty poor.

I wonder if there are any other settings from `plotOptions.line` that are relevant to `plotOptions.timeline` but aren't spelled out in the docs?

**Comment by pawelfus** [comment]
Thanks for reporting the issue @nk9 

You are right, `lineWidth` is missing from options, but I'm not sure why you need this option, though. This is `lineWidth` in action: https://jsfiddle.net/BlackLabel/y9z1so7q/ (the gray line under the markers).

> the default lines with the various colors overlap lines and markers and look pretty poor.

Could you elaborate? For example could you update my demo to see what exactly do you mean? Thanks!

**Comment by nk9** [comment]
Hi Pawel. [Here's an example](https://jsfiddle.net/1000autumns/bcwazrfn/3/) of what I mean. See the entry for 19 Apr 1971. The purple line overlaps the black one because it started earlier. The solution is to eliminate the lineWidth from each series and have a single line on the yAxis.

**Comment by Denyllon** [comment]
Hi @nk9 ,

While creating the timeline series we did not have intentions to make it possible to present multiple series/timelines on one chart, and not consider whether this property would be usable in any way, that's why it is not available between the other API options. I think that, for now, this ticket can be marked with the `Enhancement` label and reconsidered when implementing multi-timeline series.
@pawelfus What do you think about that?

Kind regards!

**Comment by pawelfus** [comment]
Thanks for the demo @nk9 ! Option is already available, but not documented: https://jsfiddle.net/BlackLabel/8kam3nho/

@Denyllon - is there something you have in mind when saying "multi-timeline" series? For me it already works quite nice.

**Comment by Denyllon** [comment]
@pawelfus Something like that, but without using two y axes: https://jsfiddle.net/BlackLabel/whc1bLjs/

**Comment by pawelfus** [comment]
I see. That might be a nice feature, but we need to gather more feedback first. For now, in the scope of that ticket, let's focus on missing `lineWidth` option in API.

**Comment by nk9** [comment]
Thanks for the ping, Mr Bot. Any progress on this attribute being added to the docs?

**Comment by pawellysy** [comment]
Hello @nk9, I will add it to the inbox for now.
