### ISSUE TITLE
Zoom rectangle appears at a wrong place after scrolling inside containing element

### ISSUE THREAD

**Issue by ktakahashimtb** [highcharts/highcharts#13996]
#### Expected behaviour
The left-top of the zoom rectangle appears where the mouse is clicked, and the right-bottom at the current cursor position.

#### Actual behaviour
The zoom rectangle appears at a wrong spot (looks to be off by the scrolled distance)

#### Live demo with steps to reproduce
https://jsfiddle.net/ktakahashimtb/eno1pvz8

Move the cursor on top of the chart and scroll down inside the container element using mouse wheel, trackpad or arrow keys.
Now, try zooming in the chart.  The zoom rectangle appears at a wrong place, thus zooming in at the unintended plot area.

This behavior can cause **unexpected zoom-in** to happen when scrolling horizontally inside the chart.

https://jsfiddle.net/ktakahashimtb/5wndme3r

In the above fiddle, try:
1. zoom in
2. scroll down (in the container element) with mouse wheel or trackpad
3. scroll horizontally in the graph
4. **Unexpected zoom** happens because the mouse-drag action **on the horizontal scrollbar** is misinterpreted to have happened in the plot area, thus zoom-in is now activated.

#### Diagnosis ####
The problem appears to be happening inside the `Pointer.prototype.normalize` function, where `chartPosition` was not updated properly after an scroll event, thus computed `chartY` and `chartX` values are not correct.

https://github.com/highcharts/highcharts/blob/e06fb000fa9fc2ad816a9c5ec4f29e311d90bf9b/ts/Core/Pointer.ts#L1118

It appears to me that, instead of computing `chartY` and `chartX` based on the _current viewport offset_ of an mouse event (`e.PageX`, `e.PageX`) and the chart position (`chartPoition.Left`, `chartPoition.Top`),  we can just copy values from `e.offsetX` and `e.offsetX` to obtain the mouse position relative to the chart.

https://jsfiddle.net/ktakahashimtb/w7ucx40j/

In the fiddle above, I'm overwriting `e.PageX`, and `e.PageY` values with `e.offsetX` and `e.offsetX` using [wrap](https://www.highcharts.com/docs/extending-highcharts/extending-highcharts#wrapping-up-a-plugin).  Now, the zoom rectangle appears at the correct location.  I'm not sure if there are reasons for not setting `e.PageX` and `e.PageY` this way, but so far this workaround has fixed the issue with no side effect.  That said, I'd like to have this issue fixed in the Highcharts code.

#### Product version
Highstock v8.1.2 (Highstock v7.2.1 shows the same issue)

#### Affected browser(s)
Chrome, Firefox, Edge,

**Comment by Izothep** [comment]
Hi @ktakahashimtb!

Thank you for contacting us with such a detailed description of a bug. The issue is bisected to:
https://github.com/highcharts/highcharts/commit/8359afc2223b24508cb039bb7ad4ced7b2517923

As a quick workaround, it should be possible to override getChartPosition method so it will not take cached value but calculate it every time instead:
https://jsfiddle.net/BlackLabel/euqazLr1/
