### ISSUE TITLE
Unstable rendering upon update() with identical options

### ISSUE THREAD

**Issue by badeball** [highcharts/highcharts#13997]
#### Expected behaviour

When calling `update()` with identical options as when constructing the chart, I expect nothing to change.

#### Actual behaviour

The "navigator" of Highstocks changes ever so slightly. This can be seen [here](https://jsfiddle.net/21w6hspa/39/).

Why would you call update() immediately and with the same options you might ask. Well, I'm actually using React and the `highcharts-react-official` package. As you might know as a React-developer, one don't always control tightly the amount of re-rendering that's occurring and we're experiencing unstable rendering of our graphs when dispatching unrelated Redux-actions. This is somewhat prohibiting us from performing visual regression tests, where we require stable and pixel perfect rendering. FYI, we _have_ pixel-perfect rendering of everything else, as we're running a specific version of Chrome in Docker, so this isn't at all infeasible as someone might claim (pardon me, I'm just trying to get ahead of a potential argument here).

#### Live demo with steps to reproduce

The issue can be seen [here](https://jsfiddle.net/21w6hspa/39/). After 5 seconds, you can observe a slight change in the graph in the navigator, just in the middle where it "dips". I've also created an example that illustrates it from a React POV [here](https://jsfiddle.net/21w6hspa/34/).

#### Product version

We're using highstock-8.1.2.

#### Affected browser(s)

At least chromium-83.0.4103.116 and chrome-75.0.3770.100.

**Comment by badeball** [comment]
Furthermore, if you change `yAxis.opposite` to `true`, then the problem disappears. Not user if that's relevant.

**Comment by pawelfus** [comment]
Thanks for reporting the issue @badeball 

I can't reproduce the issue. Nothing changes in the chart, tested with:
> Google Chrome is up to date
> Version 84.0.4147.105 (Official Build) (64-bit)
> OSX 10.13.6

Anyway, some minor resizing may happen. In short, initial rendering may vary a little with every subsequent redraw/update/resize. This is related to reserving space for some components on the chart (e.g. Axis' labels). You can find the longer explanation here: https://github.com/highcharts/highcharts/issues/13451#issuecomment-625734460

> Furthermore, if you change `yAxis.opposite` to `true`, then the problem seems to disappear. Not sure if that's relevant.

It probably is. Let's compare yAxis labels: `opposite=false` -> labels are rendered outside the plotting area, we need to reserve the space. `opposite=true` -> labels are rendered inside the plotting area, so we don't need to reserve the space.

**Comment by badeball** [comment]
In order to make this issue abundantly clear to everyone, I've created a video to illustrate the issue. At some point you can see the graph change ever so slightly. I recommend focusing right in the middle of the picture to register it.

![output](https://user-images.githubusercontent.com/730419/89397042-a3c06e00-d70f-11ea-8a40-b52e9048da8e.gif)

@pawelfus, do you still not observe the issue illustrated in the video?

**Comment by badeball** [comment]
> Anyway, some minor resizing may happen. In short, initial rendering may vary a little with every subsequent redraw/update/resize. This is related to reserving space for some components on the chart (e.g. Axis' labels). You can find the longer explanation here: https://github.com/highcharts/highcharts/issues/13451#issuecomment-625734460

Ah, I understand. This is very unfortunate for us. We've previously had to make use of an undocumented option for testing purposes (kdNow), which we're fine with. There wouldn't just happen to be a similar, undocumented option to make the rendering stable?

**Comment by pawelfus** [comment]
Oh, I missed that! Thanks :) Yes, I see that in the demo too.

My description in https://github.com/highcharts/highcharts/issues/13451#issuecomment-625734460 is not sufficient in this case. The reasoning is the same, but the result is connected to [`dataGrouping`](https://api.highcharts.com/highstock/series.line.dataGrouping) option. On the initial rendering, points in navigator are grouped in one-day groups. After update, points are grouped in two-days groups.

That means you can workaround the issue by setting specific `dataGrouping` for navigator, for example: https://jsfiddle.net/BlackLabel/np0tujv9/ You can also completely disable it, but this will affect the performance.

This solution can be safely used in testing env, but in production you might prefer dynamic `dataGrouping` (where grouping depends on number of data points, screen size or zoomed range by user).

**Comment by badeball** [comment]
Thanks for the great insight and impeccable response time, @pawelfus!

In the end we were able to circumvent the need for that by memoizing options and ensuring that only graph-related Redux-actions would trigger a component update (the HOC is [memoized](https://github.com/highcharts/highcharts-react/blob/v3.0.0/src/HighchartsReact.js#L93) itself). This makes the graph stable until it's actually supposed to change and thus allows us to continue to do visual testing.

Hence I'm closing this as solved / explained.
