### ISSUE TITLE
setSize on dynamically built chart prevents render of second series

### ISSUE THREAD

**Issue by anajavi** [highcharts/highcharts#13995]
#### Expected behaviour
When adding series dynamically all series should show up after setSize is called.

#### Actual behaviour
When setSize is called with:
```js
// any of these will fail
chart.setSize(undefined, 200);
chart.setSize(400, 200);
chart.setSize(400);
chart.setSize(undefined, undefined);
```

Second series on second axis does not render.

#### Live demo with steps to reproduce
https://jsfiddle.net/2mb6vyrn/1/

Second series does not render unless call to setSize is removed.

#### Product version
Highcharts 8.1.1 and 8.1.2
In 8.1.0 this works.

#### Affected browser(s)
Chrome 84

#### Original issue
https://github.com/whawker/react-jsx-highcharts/issues/299#issuecomment-668433074

**Comment by anajavi** [comment]
This is most likely related to #13680, as that fixed setSize for single series.

**Comment by pawelfus** [comment]
Thanks for reporting this issue @anajavi - you are right, it's a bug since v8.1.1

FYI @TorsteinHonsi
