### ISSUE TITLE
The Ichimoku Kinco Hyo indicator throwing the error in console, when base series has no data.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#13992]
#### Expected behaviour
It should not throw the error even when the base series data is empty, like every other indicator.

#### Actual behaviour
The Ichimoku Kinco Hyo indicator throwing the `TypeError: Cannot set property '0' of undefined` when its base series does not have data.

#### Live demo with steps to reproduce
Official IKH demo without data set on base series: https://jsfiddle.net/BlackLabel/u8pjmy6a/

#### Workaround
Applying the below fix of the `getGraphPath` prototype function, which checks whether the calculated SMA is not empty.
```js
(function(H) {
  const SMA = H.seriesTypes.sma;

  H.seriesTypes.ikh.prototype.getGraphPath = function(points) {
    var indicator = this,
      path = [],
      spanA,
      spanAarr = [];

    points = points || this.points;
    if (indicator.fillGraph && indicator.nextPoints) {
      spanA = SMA.prototype.getGraphPath.call(
        indicator,
        indicator.nextPoints
      );
      if (spanA.length) {
        spanA[0][0] = "L";
        path = SMA.prototype.getGraphPath.call(indicator, points);
        spanAarr = spanA.slice(0, path.length);
        for (var i = spanAarr.length - 1; i >= 0; i--) {
          path.push(spanAarr[i]);
        }
      }
    } else {
      path = SMA.prototype.getGraphPath.apply(indicator, arguments);
    }
    return path;
  };
})(Highcharts)
```
Demo with fix: https://jsfiddle.net/BlackLabel/0d1e635j/

**Comment by hamedrajabpour** [comment]
when it's fix in (HighChart-Vue & Highstock) library ?

**Comment by madepiet** [comment]
> when it's fix in (HighChart-Vue & Highstock) library ?

Hi @hamedrajabpour! This will be added in the next version of Highcharts.
