### ISSUE TITLE
Pie: dataLabels show "Slice" instead of value

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#13993]
#### Expected behaviour
Correct display of dataLabels format for pie chart.

#### Actual behaviour and demo with steps to reproduce
When we have a chart with dataLabels turned on, it works fine, but when we change it to pie, 'Slice' is displayed instead of the value: https://jsfiddle.net/BlackLabel/dzbfh0qa/

We need to add a format for it to work properly.

From API:
Defaults format: '{point.value}' - does not exist for pie chart
https://api.highcharts.com/highcharts/series.pie.dataLabels.format

#### Product version
v8.1.2

**Comment by pawelfus** [comment]
It's a bug in docs. By default, pie chart uses formatter:
```js
formatter: function () {
    return this.point.isNull ? void 0 : this.point.name;
}
```
