### ISSUE TITLE
Accessibility issue with Stacked Highchart in full screen mode on firefox browser

### ISSUE THREAD

**Issue by richadoshi20** [highcharts/highcharts#14000]
#### Expected behaviour
In fullscreen mode NVDA screen reader should only read elements present on the screen

#### Actual behaviour
In fullscreen mode NVDA screen reader reads elements of parent page also along with fullscreen elements

#### Live demo with steps to reproduce
Check this link https://www.highcharts.com/demo/column-stacked on firefox browser.
1. Click on fullscreen option from context menu
2. Open NVDA and click on tab multiple times
3. NVDA reads view options, edit in JS fiddle, privacy policy etc while on fullscreen mode of chart
#### Product version

Highcharts: 7.1.12

#### Affected browser(s)
Firefox

**Comment by sebastianbochan** [comment]
Hi @richadoshi20,
Thank you for reporting.

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
I don't quite see how this could be a Highcharts issue as long as the chart enters the fullscreen viewing mode of the browser - we are simply using the browser's fullscreen API.

Do you get the same issue with other charts and on other pages? [This chart](https://www.highcharts.com/samples/highcharts/accessibility/accessible-pie) for example?

How about other fullscreened elements? See for example these demos:
- http://labs.qnimate.com/full-screen-api/
- https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_fullscreen
- https://codepen.io/wle8300/pen/gOpvzJE

**Comment by oysteinmoseng** [comment]
Closing this for now, let's reopen if we get more information.
