### ISSUE TITLE
Override legendItemClick to make it like hovering but with persistence 

### ISSUE THREAD

**Issue by ajbee07** [highcharts/highcharts#14005]
In React, Is there a way to make the legendItemClick change the opacity of not selected legend just like when hovering in the legend?

then if the legend is click again then it will return to normal.

This will like imitate the hover but the clicked legend will be persisted unless the user clicks on other legend or click again on that legend

**Comment by pawelfus** [comment]
Hi @ajbee07 

Thanks for contacting us, but for questions please use other support channels: https://www.highcharts.com/blog/support/ - this is our bugs/features tracker, not a Q&A forum :) 

PS: Did you try using `series.update()` or `series.setState()` in `legendItemClick`?

**Comment by ajbee07** [comment]
how can I access `series.update(`)?

**Comment by sebastianbochan** [comment]
Please use one of our support channels. Our react specialist will assist you.
