### ISSUE TITLE
Series data labels allowOverlap option doesnt seem to work correctly when chart is resized

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#14007]
#### Expected behaviour
Highcharts API reference mentions that allowOverlap option decides whether to allow data labels to overlap. We expected that on setting the allowOverlap attribute as true, the series data labels will be always shown irrespective of the space available to plot the chart. On resizing to small space, still it was expected that all the labels will be seen though overlapped or crowded.
Refer Column chart JS Fiddle. 
Please let us know if there are any other logic applied from Highcharts that will hide the data labels in some cases even though the allowOverlap option is set as true in options.

#### Actual behaviour
It is observed that in some cases where the chart is resized such that it gets less space for plotting, few of the series data labels seem to disappear.  Refer Pie chart JS Fiddle.
Similar issue is observed for other charts like Gauge chart, Boxplot, etc

#### Live demo with steps to reproduce
Pie chart - https://jsfiddle.net/amrutaJgtp/063fdsm2/2/
Column chart - https://jsfiddle.net/amrutaJgtp/063fdsm2/3/

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @amruta30,
Thank you for reporting. The reason of that is lack of space. You can use the [alignTo](https://api.highcharts.com/highcharts/series.pie.dataLabels.alignTo) option to display dataLabels on the edges. 

Set the responsive rules in case of problem on smaller resolutions.

Demo:
- https://jsfiddle.net/BlackLabel/5w8ncgzp/1/

**Comment by amruta30** [comment]
Hi @sebastianbochan ,

Thanks for replying. I studied the alignTo option provided by Highcharts. But its only applicable for charts like Pie and Sunburst.. Hence it does not seem to be a full proof solution for all other chart types such as Column, Gauge, Boxplot, etc.

In our implementation of allowOverlap option of series data labels, we expected that Highcharts will always show the series data labels maybe intensively overlapped inspite of the space available.

So we think that there should be a support to show all the datalabels irrespective of the space or the size of data labels or the chart is resized to smaller size when allowOverlap is set as true.

**Comment by sebastianbochan** [comment]
Hi @amruta30,
When I run the demo: https://jsfiddle.net/amrutaJgtp/063fdsm2/3/ I am not able to find a missing datalabel. Could you post a screenshot of a skipped label?

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
