### ISSUE TITLE
On graph reports, the graph nodes' tooltips are misaligned with mouse cursor (shifted to the left).

### ISSUE THREAD

**Issue by Ternulf** [highcharts/highcharts#14018]
![image](https://user-images.githubusercontent.com/49244259/89731613-b35df080-da48-11ea-81c9-bc91fbca9c50.png)
![image](https://user-images.githubusercontent.com/49244259/89731624-c4a6fd00-da48-11ea-958c-b3ed30860cae.png)

**Comment by sebastianbochan** [comment]
Hi @Ternulf,
Thank you for reporting. Could you share a live demo of your chart? It will allow us to debug and find a solution.

**Comment by Ternulf** [comment]
Yes Do You want me to make a mp4 recording?

**Comment by Ternulf** [comment]
Did You get the mp4 file?

**Comment by sebastianbochan** [comment]
Hi @Ternulf,
By the live demo I mean a demo which I can open in my browser. It will allow me to debug, check your chart's configuration or CSS styles.

**Comment by Ternulf** [comment]
Hi
Thank you for the response.

I can try to arrange a demo.

I will be back to you.

During the meantime I want to ask You.
Is this a known problem or is it belonging to this application?



Best regards

 

Yngve Ternulf

**Comment by Ternulf** [comment]
This is a test and demo on a very slow server.
You might have to wait approx 40 s after starting

http://77.246.233.139:8080/Actron-MPC/login?client=demoretailchain

User name                Sebastian 
password                  Bochan

**Comment by Ternulf** [comment]
Hi Sebastian,
Did You manage to see the problem?

**Comment by sebastianbochan** [comment]
Hi @Ternulf,
Unfortunately I was not able to run the demo. I still has the hanging loader without success.

**Comment by Ternulf** [comment]
Maybe it was during a deployment
I have no problem to login.  (The user name and password are case sensistive) Please ty again

**Comment by sebastianbochan** [comment]
Hi @Ternulf,
After some time (about 10 minutes of waiting) the chart is visible. I debugged it and it looks like a problem with your CSS / Bootstrap or custom JS code elements. When I extracted the native chart here: https://jsfiddle.net/BlackLabel/73tbxomz/ all works properly.

I advise you to debug your custom code and styles. 

If you will have any further problems, please use one of our [support](https://www.highcharts.com/support) channels like stackoverflow / forum or email.

**Comment by Ternulf** [comment]
Thank You very much. I have transferred to my dev team.
I informed that this demo is running on a very slow server. It can take minute. But a minute feels like 10 minutes
I have a second question 
We are rather close to the launch of the product. 95% of what is done is very nice.
But there is one thing which is terrible.
The reports have to be printed out either as charts, tables or combined charts & tables. 
The charts are nice. But the tables are terrible. What can that do to get professional and flexible tables
![Ugly tables](https://user-images.githubusercontent.com/49244259/89906287-7aaa4c80-dbeb-11ea-951d-98964e5198c8.png)

**Comment by Ternulf** [comment]
Hi again
Do you have any tips how we can improve the tables?

**Comment by sebastianbochan** [comment]
Hi @Ternulf,
The github is our bug tracker, so please use our [support channels](https://www.highcharts.com/support) for the general support questions.

ps. Unfortunately we do not have knowledge about your custom code. I recommend you to consider our solution about including datatable in the exported chart. 

Docs:
- https://www.highcharts.com/docs/getting-started/frequently-asked-questions#can-i-add-a-data-table-to-the-exported-chart

**Comment by Ternulf** [comment]
Hi Sebastian,

 

You assited me some time ago wit a question.

But our developers still can not find where the problem is

Do You think that you can assist further. 

It does not look nice. 

Please check the small video

Best regards

 

Yngve Ternulf

**Comment by pawelfus** [comment]
Hi @Ternulf 

In general, Highcharts is a library to render charts, not tables. We experimented a little with tables & exporting, you can check this here: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/studies/exporting-table-html 
However, I would recommend to export Highcharts chart to image, then attach it to your report.

If you have any further questions, please contact our support team: https://www.highcharts.com/blog/support/

**Comment by Ternulf** [comment]
Hi 
Thanks for Your reply.
My question was rather regarding the question 
"On graph reports, the graph nodes' tooltips are misaligned with mouse cursor (shifted to the left)."  Ref 14018 above.
We got a reply from Sebastian. But it did not help our developers. 
I would appreciate if You could check e.g. this link:
http://report.actron.com.ru/Actron-MPC/login?client=LargeDemoMall
User name DemoMallEng   Password 1000
Best regards 
Yngve Ternulf

**Comment by PaulDalek** [comment]
Hi @Ternulf

I was able to login, check the demo and see the issue but it is hard to indicate what causes it. I have prepared a simple JSFiddle example based on the `userOptions` of your chart where the tooltip behaves normally so, as Sebastian noted before, it is most likely a problem with your custom JS code or CSS. Please provide us with a minified live example of the chart only, where this issue occurs otherwise it is going to be hard to find the cause of this behavior.

**Demo**
https://jsfiddle.net/BlackLabel/b204stqm/

**Comment by Ternulf** [comment]
Hi
Thank You
How do I create a minified live example of the chart only.
I am not the developer.

**Comment by pawelfus** [comment]
Hi @Ternulf 

Could you please ask your developers to assist you? Simply ask them to recreate issue in jsFiddle. @PaulDalek's demo is a good starting point.

**Comment by Ternulf** [comment]
Hi Paul
Thanks for Your support

Now we understand that this bug is related to Zooming
When it is < = 100% Zoom there is no problem.

When it is > 100% zoom the problem comes on any PC.
When it comes it is a very irritating bug. 
I think that HighCharts should do something about it. 
Please confirm that You understand the problem.

**Comment by PaulDalek** [comment]
@Ternulf

Thank you for further information but still it is hard to say for sure what is causing it without any simplified demo. It looks like it might be the same problem as the one that is described here #12489. Try to use the workaround from this [comment](https://github.com/highcharts/highcharts/issues/14579#issuecomment-728902159) and let us know if it helps. If it doesn’t, please try to create a demo as requested before.

**Comment by Ternulf** [comment]
Thank You
But I am not sure that it is the same problem
![image](https://user-images.githubusercontent.com/49244259/100543431-66e52d80-3250-11eb-8f13-60527da6c157.png)
It looks very bad when this comes up.
Unfortunately most people are using the zoom in this application
Could you fix it or is there a way around for this?

**Comment by PaulDalek** [comment]
@Ternulf

I really want to help you find the cause of this behavior but as I mentioned in my previous messages, without any simplified demo we cannot do much. Please, try to prepare such an example as requested previously, so we can debug it and hopefully fix the problem.

**Comment by Alex-Actron** [comment]
Hello!

I have debugged the problem.
The cause is that Highcharts has an issue with CSS zoom property.
Here's the live demo: https://jsfiddle.net/cbq71u0x/1/

On the site zoom property is used to scale the page to different screen resolutions.
Is it possible to make Highcharts internally support CSS zoom property correctly?

**Comment by PaulDalek** [comment]
Hi @Alex-Actron

Thank you for an example that recreates the problem. This is a bug that was reported some time ago. In other words, it is a duplicate of the #2299.
