### ISSUE TITLE
Legend- unable to properly set the y position when verticalAlign: 'top'.

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14019]
#### Expected behaviour
Have the ability to position the legend counting from the top of the chart (`verticalAlign: 'top'`).

#### Actual behaviour
When `verticalAlign: 'top'` and when the legend is positioned at the bottom using the `y` offset, the border and the legend items disappear.

If the legend is first positioned at the middle or at the bottom, this issue doesn't occur. 
Can be treated as a workaround. Demo: https://jsfiddle.net/BlackLabel/5vera1yL/

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/h209gLjo/

#### Product version
 Highcharts JS v8.1.2 (2020-06-16)

#### Affected browser(s)
ALL

**Comment by pawelfus** [comment]
Note: Seems to be related to `legend.navigation`, when disabled, it's fine: https://jsfiddle.net/BlackLabel/h209gLjo/3/
