### ISSUE TITLE
Data with similar ranges, why the yAxis range is different

### ISSUE THREAD

**Issue by songhua-river** [highcharts/highcharts#14012]
[ jshare](https://jshare.com.cn/temp/4UGfWf) 

I have two sets of data, what I expect is that the yAxis range of the second set of data is smaller than the first set of data, but it seems that the second set of data is affected by the first set of data

How do the HighCharts calculate the yAxis range of the two sets of data

**Comment by pawelfus** [comment]
Hi @songhua-river 

This is caused by `chart.alignTicks` option, check our API: https://api.highcharts.com/highcharts/chart.alignTicks

**Comment by songhua-river** [comment]
Thanks.

**Comment by songhua-river** [comment]
> Hi @songhua-river
> 
> This is caused by `chart.alignTicks` option, check our API: https://api.highcharts.com/highcharts/chart.alignTicks

Thank.
