### ISSUE TITLE
Marker Cluster: Point.update error and not able to be used

### ISSUE THREAD

**Issue by codywsears** [highcharts/highcharts#14017]
#### Expected behaviour
Steps:
1. Hover over a point in a scatter series that is not clustered
2. The symbol changes when using the Point.update with a symbol change in the marker
3. The symbol for the marker changes back to the original on mouseOut

#### Actual behaviour
1. Hover over a point in a scatter series
2. The symbol does not change
3. The console outputs: "Highcharts marker-clusters module: Running `Point.update` when point belongs to clustered series is not supported."

#### Live demo with steps to reproduce
https://codepen.io/codywsears/pen/YzqPRaX

#### Product version
Highcharts v8.1.2

#### Affected browser(s)
Found in Chrome

**Comment by sebastianbochan** [comment]
Hi @codywsears,
Thank you for reporting. 

FYI @wchmiel

**Comment by wchmiel** [comment]
This issue is not a bug. As you can read in the console the point can not be updated when a series is clustered. I will mark it for now as a feature request and check if it is possible to implement it.

**Comment by codywsears** [comment]
@wchmiel thanks for checking on this! It is ok that the clustered point is not able to be updated. However, would it be possible for a non-clustered point (one that is in a series that has clustering enabled) use the Point.update functionality?

**Comment by wchmiel** [comment]
@codywsears You're welcome! For now, this is not supported (updating a single point that belongs to the series that has clustered points). I will check and try to implement it, yet I can not give you any ETA.

**Comment by wchmiel** [comment]
Unfortunately, this feature will require a lot of changes in the core implementation of marker clusters (and also data grouping because it uses the same logic). So, for now, this feature will not be implemented.

As a workaround for a point updating in this use case you can use SVGElement.attr() to set for example a different fill color on mouse over a noise point. Demo: https://jsfiddle.net/BlackLabel/j6mbr71u/.
