### ISSUE TITLE
PlotLineOrBand type should expose the axis

### ISSUE THREAD

**Issue by jnizet** [highcharts/highcharts#14020]
#### Expected behaviour

When registering mouse event listeners to a plot line or a plot band, the listener event callback doesn't have any access to the axis (and its chart), which makes it hard to, for example, display a floating label for the plot line of plot band.

The constructor of `PlotLineOrBand` takes the axis as argument, and at runtime, the axis is available, but the TypeScript definition of `PlotLineOrBand` doesn't expose any `axis` property. See https://api.highcharts.com/class-reference/Highcharts.PlotLineOrBand

#### Actual behaviour

TypeScript code such as

```
const eventsOptions: XAxisPlotLinesEventsOptions = {
  mouseover(this: PlotLineOrBand) {
    const chart = this.axis.chart;
    // ... display a label on the chart
  }
};
``` 

does not compile

#### Live demo with steps to reproduce
NA

#### Product version
HighCharts 8.1.2

#### Affected browser(s)
 NA

**Comment by pawelfus** [comment]
Thanks for reporting the issue @jnizet 

FYI @bre1470 
I think it's safe to make this an Axis type, it's a reference to the `chart.xAxis[index]`/`chart.yAxis[index]` anyway.
