### ISSUE TITLE
Value in tooltip not formatted properly

### ISSUE THREAD

**Issue by MiroLiska** [highcharts/highcharts#14023]
#### Expected behaviour
tooltipOptions.valueDecimals set to 0 should work regardless on number size. It worked in 5.0.12, in 7.0.1 it does not work anymore.

#### Actual behaviour
The tooltip values are not rounded if the number is too small ( 2e-7) and valueDecimals is set to 0. If valueDecimals is set to 1 or 2, the tooltip works properly.

#### Live demo with steps to reproduce
Correct behavior: http://jsfiddle.net/hLprzecq/  
![Correct](https://user-images.githubusercontent.com/23024867/89792639-20df4f00-db25-11ea-8d13-f394283ffa1b.png)

Incorrect behavior: http://jsfiddle.net/bn7tj1fw/ 
![Incorrect](https://user-images.githubusercontent.com/23024867/89792655-276dc680-db25-11ea-87a9-299f42777395.png)

I have created a ticket 7844 for this issue, but instead of fixing the bug I have received a hint that I should create a bug report over here. This is ineffective, the ticket 7844 should be automatically converted to a bug and I should not be forced to retype the whole thing again here in GitHub.

#### Product version
Highcharts 7.0.1 (the bug was introduced in 6.*,I think)

**Comment by pawelfus** [comment]
Thanks for reporting the issue @MiroLiska 

It's most likely a regression since ad892cbe83a1b08628e6dc3761f1a80c835e58ad (not bisected)

**Workaround:**
Use `tooltip.pointFormatter` instead of `tooltip.pointFormat` and apply `valueDecimals` and `valueSuffix` manually.
Demo: http://jsfiddle.net/BlackLabel/z1qjmsnx/
Snippet:
```js
  plotOptions: {
    column: {
      tooltip: {
        pointFormatter: function() {
          return `<span>${this.series.name}</span>: <b>${Math.round(this.y)}%</b><br/>`
        }
      },
      ...
    }
  },
```

**Comment by MiroLiska** [comment]
Hi.

I will rather wait for a bugfix from your side. Adding pointFormatter to ~80 charts is out of question. Especially because I already use pointFormatter in many charts for different purposes and the valueDecimals is set to various precisions, depending on the database and user settings. The bug occurs only if valueDecimals is set to 0. Your workaround completely ignores the valueDecimal settings, which I use sometimes for the whole plotOptions and sometimes also on the series level.

I see that Torstein wanted to fix a problem with huge numbers. Small numbers were forgotten ☺ Maybe put this case into unit tests.

Thanks in advance.
Miros

**Comment by pawelfus** [comment]
Sorry, missed that part: 

> I have created a ticket 7844 for this issue, but instead of fixing the bug I have received a hint that I should create a bug report over here. This is ineffective, the ticket 7844 should be automatically converted to a bug and I should not be forced to retype the whole thing again here in GitHub.

Interesting idea (converting support ticket to gh ticket), thanks for sharing!

**Comment by MiroLiska** [comment]
Hello

What do you think, is a fix for this issue coming soon?

Thanks

Miro

**Comment by pawelfus** [comment]
Yes, I think so. Probably after v8.2.2 release (v8.2.1 will be skipped).
