### ISSUE TITLE
Series name is cut off if custom labelFormatter and series name is long enough (download png/jpeg/pdf/svg)

### ISSUE THREAD

**Issue by klaskow** [highcharts/highcharts#14039]
#### Expected behaviour
I could not find events like beforePrint and afterPrint but for download png/jpeg/pdf/svg. 
So I can not change custom labelFormatter before it is exported to png/jpeg/pdf/svg.

#### Actual behaviour
If series name is custom and long enough, after downloaded png/jpeg/pdf/svg series name is cut off.
I need some way to change labelFormatter CSS styles before and restore after downloaded png/jpeg/pdf/svg.

#### Live demo with steps to reproduce
https://codesandbox.io/s/highcharts-labelformatter-download-2fm9k

I created series name with long name and additional row with some data.
As you can see, my addiotional row with values are below series name, but on png it is on the same line and with broken styles for values.

#### Product version
HighchartsReact 8.1.2
HighchartsExporting 3.0.0

#### Affected browser(s)
All browsers.

**Comment by pawelfus** [comment]
Hi @klaskow 

Thanks for reporting the issue. This is caused by not setting [`exporting.allowHTML`](https://api.highcharts.com/highcharts/exporting.allowHTML) to true. Take a look: https://jsfiddle.net/BlackLabel/La2pesd1/

**Comment by klaskow** [comment]
Hi, allowHTML is only partial solution because if series name is very long it is still cutting off.
I need to change this.name (by doing some chunk with extra divs) in some way but only before exporting but I couldn't find any usefull event to attach.
So in short. I need to change whole structure that is returned from legend.labelFormatter but only when exporing as image png/jpeg/pdf/svg.

Example code with longer text: https://codesandbox.io/s/highcharts-labelformatter-download-2fm9k

And screenshots (the first one is after exporting, the second from browser):
![my-chart(1)](https://user-images.githubusercontent.com/51476475/90377890-f6d3e280-e078-11ea-9127-57d47c85c2e7.png)
![MScreenshot_17](https://user-images.githubusercontent.com/51476475/90377964-0eab6680-e079-11ea-9b14-9471a616c7a3.jpeg)

**Comment by pawelfus** [comment]
Hi @klaskow 

> So in short. I need to change whole structure that is returned from legend.labelFormatter but only when exporting as image png/jpeg/pdf/svg.

I'm afraid this is incorrect. You need to do that always. Simply resize your browser and you will see the same issue with chart as with the exported image: 
![Screen Shot 2020-08-17 at 11 23 00](https://user-images.githubusercontent.com/1453926/90380194-0d2f6d80-e07c-11ea-8233-94edd6d99107.png)

If you really want to use different `labelFormatter` for exported chart then either use [`exporting.chartOptions.legend.labelFormatter`](https://api.highcharts.com/highcharts/exporting.chartOptions) option or in `labelFormatter` check for `this.chart.options.chart.forExport` flag.
