### ISSUE TITLE
Radial Chart is not working normal on React

### ISSUE THREAD

**Issue by dominwong4** [highcharts/highcharts#14043]
#### Expected behaviour
Showing the Normal Radial Chart

#### Actual behaviour
Showing the Nomrmal Bar Chart instead

#### Live demo with steps to reproduce
[](https://jsfiddle.net/w1reL728/8/)
[](https://stackblitz.com/edit/react-bzkshd?file=index.html)

**Comment by dominwong4** [comment]
[https://stackblitz.com/edit/react-bzkshd?file=index.html](url)
[https://jsfiddle.net/w1reL728/8/](url)

**Comment by sebastianbochan** [comment]
Hi @dominwong4,
Thank you for contacting. The github is our bug tracker. For the general [support](https://www.highcharts.com/support) questions please use forum / stackoverflow or email.

ps. There is highcharts-more missing reference. Add the module like in the demo: https://stackblitz.com/edit/react-pt7jie?file=index.js
