### ISSUE TITLE
customize spider dots colors

### ISSUE THREAD

**Issue by roufa95** [highcharts/highcharts#14042]
**how can i customise my spider chart like the chart in the image below in android ?**
I want to customise the color of the dots according to an interval of values.

![image](https://user-images.githubusercontent.com/32592175/90193219-6b2e2d80-ddbc-11ea-8f5b-eec888ef8a21.png)

**Comment by sebastianbochan** [comment]
Hi @roufa95,
The github is our bug tracker, so for [general support](https://www.highcharts.com/support) questions please use forum / stackoverflow or forum.

ps. You can edit colors by `point.color`. Demo: https://jsfiddle.net/BlackLabel/4h6vprtf/

**Comment by roufa95** [comment]
thank you for your response
next time i will use stackoverflow 
thanks again
