### ISSUE TITLE
setting ordinal = true is not working when I use boost.js in Highchart

### ISSUE THREAD

**Issue by rameshkan** [highcharts/highcharts#14055]
ordinal property should remove the no data points in the series and working fine normally.

But if we include boost.js to improve the performance, the above said behavior is not working and displaying all the dates between the start and end date

Please find the below demo page in jsFiddle. Please remove/add boost.js to reproduce the issue. 

http://jsfiddle.net/rameshkan/7f4crsvL/5/

**Comment by pawelfus** [comment]
Thank you for reporting the issue @rameshkan 

It seems that `ordinal`-option + `boost`-mode is not implemented.

Simplified demo: http://jsfiddle.net/BlackLabel/ch2dk47u/1/

**Comment by rameshkan** [comment]
Thank you for your reply. It is breaking our existing behavior of the chart if we use the boost mode. 

Any plan to fix/add this feature in any of the future release?

**Comment by pawelfus** [comment]
No plans at this moment, all updates regarding this feature will be available in this ticket.

**Comment by graysadler** [comment]
Any workarounds suggested for this bug?

**Comment by karolkolodziej** [comment]
_Internal note:_ 
Bisected to commit ac1067e0ab- boost stopped working when data grouping enabled

**Comment by karolkolodziej** [comment]
_Internal note:_
After some further investigation, it looks like [this commit ](https://github.com/highcharts/highcharts/commit/174f8d07c328fdf50b265bbc2fcb97f329c8c922) leads to lack of boost with an ordinal axis. 
I'll try to untangle this and evaluate potential performance problems.
