### ISSUE TITLE
Gantt- navigator doesn't match the chart

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14060]
#### Expected behaviour
The yAxis in navigator should be reversed and the series in the navigator should match the series on the chart.
Workaround: https://jsfiddle.net/BlackLabel/swnjrvgd/

#### Actual behaviour
Series in the navigator doesn't match the series on the chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/n3ypguLq/

#### Product version
Highcharts Gantt JS v8.1.2 (2020-06-16)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
I don't know if this is a bug, but it would be nice to set the same default options for `yAxis` and `navigator.yAxis`. 

Note: Our official demo also sets `navigator.yAxis.reversed`: https://www.highcharts.com/demo/gantt/with-navigation

**Comment by pawelfus** [comment]
*Internal note:*
Decided to inherit yAxis option from base yAxis. The same should happen in Stock - check if Stock has the same bug and if has, provide universal solution. If not, make sure Highcharts Gantt has the same solution as Stock.
