### ISSUE TITLE
Bug in flags series when using scrollbar on an inverted chart

### ISSUE THREAD

**Issue by brnomendes** [highcharts/highcharts#14063]
#### Expected behaviour
Adding a flags series to an inverted chart, when using the scrollbar the flags should be displayed without error.

#### Actual behaviour
Adding a flags series to an inverted chart, when using the scrollbar an error is displayed on the console: 
 - Chrome: `Error: <g> attribute transform: Expected number, "translate(NaN,NaN) rotate(…".`
 - Firefox: `Unexpected value translate(NaN,NaN) rotate(90) scale(-1,1) scale(1 1) parsing transform attribute.`

and near the limit of the chart the flag is cut off.

#### Live demo with steps to reproduce
https://highcharts-8-ts-flags-series.stackblitz.io
https://stackblitz.com/edit/highcharts-8-ts-flags-series?file=index.ts
![highcharts-flags-bug](https://user-images.githubusercontent.com/7743931/90395761-778be200-e06b-11ea-9a45-b3d82f601054.gif)

#### Product version
Highstock 8.1.0

#### Affected browser(s)
Google Chrome 84.0.4147.125 64 bits
Firefox 79.0 64-bit

**Comment by pawelfus** [comment]
Thank you for reporting the issue @brnomendes 

**Workaround:**
Demo: https://stackblitz.com/edit/highcharts-8-ts-flags-series?file=index.ts

Plugin:
```ts
Highcharts.addEvent(Highcharts.Series, "render", function() {
  if (this.type === "flags") {
    (this as any).isCartesian = false;
  }
});
Highcharts.addEvent(Highcharts.Series, "afterRender", function() {
  if (this.type === "flags") {
    (this as any).isCartesian = true;
  }
});
```

*Internal note:*
We already have `series.invertable` property, but it's for non-cartesian series (e.g. Sankey). It would be nice to have a not invertible cartesian series too. Something like `group.inverted = pick(series.invertible, series.isCartesian)` + `invertible=false` for flags? Just an idea.

**Comment by micbuh** [comment]
@pawelfus, I just stumbled over the same issue. Your workaround does only fix the error, right? Is there any workaround regarding the cut off close to the bottom? My chart is twice as high as its width - so flags are only visible in the upper half.

**Comment by pawelfus** [comment]
Hi @micbuh - try setting `clip=false`: https://stackblitz.com/edit/highcharts-8-ts-flags-series-q9lhee?file=index.ts
