### ISSUE TITLE
HighChart not getting proper Update after adding flags onces chart created

### ISSUE THREAD

**Issue by pankajd1990** [highcharts/highcharts#14065]
#### Expected behaviour
suppose,firstly,i created chart with 2 y axis.so i have assigned data to 2 y axis accordigly .but after chart created,
i want to set flags on one y axis.
If i added flags to chart ,that flags should be displayed on axis.
Kindly click on update button to add more data onces chart created

#### Actual behaviour
suppose,firstly,i created chart with 2 y axis.so i have assigned data to 2 y axis accordigly .but after chart created,
i want to set flags on one y axis.
If i added flags to chart ,that flags should be displayed on axis
now it's not working..now after adding flags on already created chat,chat showing wrongly .

#### Live demo with steps to reproduce
i am sharing  my jsfiddle link
https://jsfiddle.net/pankaj_durve/od5jwagm/

#### Product version

latest version

#### Affected browser(s)
checked on chrome

**Comment by sebastianbochan** [comment]
Hi @pankajd1990,
Thank you for contacting. New data is added according to x values. Flags still exist "at the beginning" of the chart. 

![Zrzut ekranu 2020-08-18 o 11 02 13](https://user-images.githubusercontent.com/2115686/90493166-4cc08d00-e142-11ea-9cb1-eda41b03af51.png)

If you would like to control the range on xAxis (after update series or add points) you should call [xAxis.setExtremes](https://api.highcharts.com/class-reference/Highcharts.Axis#setExtremes)

p.s The github is our bug tracker, so for [general support](https://www.highcharts.com/support) questions please use other channels like stackoverflow / forum or email.

**Comment by pankajd1990** [comment]
i got ..solved using    this.stock.xAxis[0].setExtremes(first, last);

**Comment by pankajd1990** [comment]
i am closing this issue.
