### ISSUE TITLE
Boosted chart with `usePreallocated: true` causes all series points to appear at the same location

### ISSUE THREAD

**Issue by burtyish** [highcharts/highcharts#14078]
#### Expected behaviour
Each point should appear in its provided coordinates
![image](https://user-images.githubusercontent.com/4200728/90526491-20743300-e179-11ea-9c60-bf70cf178674.png)

#### Actual behaviour
With `boost.usePreallocated: true`, all series' points overlap
![image](https://user-images.githubusercontent.com/4200728/90526392-05a1be80-e179-11ea-8d3e-ae7c8221c5e4.png)

#### Live demo with steps to reproduce
https://codepen.io/burtyish/pen/jOqrKax?editors=1011

#### Product version
8.1

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @burtyish,
Thank you for reporting. Please be aware that this functionality is still experimental.

FYI @cvasseng

**Comment by burtyish** [comment]
You're welcome.

> Please be aware that this functionality is still experimental.

Be aware that the documentation at https://www.highcharts.com/docs/advanced-chart-features/boost-module does to mention it's experimental. As is, the text leads us to believe that this is a good choice.
![image](https://user-images.githubusercontent.com/4200728/90622759-3f78d080-e21e-11ea-98f0-3f2d89fd4133.png)


Also, I'd recommend that it's usage be removed from the examples, such as the codepen on [the 1M point scatter page](https://www.highcharts.com/demo/scatter-boost), which where I copied the options from.

**Comment by sebastianbochan** [comment]
I apologize for confusions. The full description is available of the function is here: https://api.highcharts.com/highcharts/boost.usePreallocated
