### ISSUE TITLE
issue is not fixed, y axis values are showing if y axis value comes 1000 range **[[97376700000, 2500],

### ISSUE THREAD

**Issue by pankajd1990** [highcharts/highcharts#14079]
issue is not fieed, y axis values are showing if y axis value comes 1000 range **[[97376700000, 2500],
         [1597376701000, 2600]]**,..but in other case if value comes as 100 or 200,y axis value are not displaying.
kindly refer 
https://jsfiddle.net/pankaj_durve/m8zobfg2/4/

_Originally posted by @pankajd1990 in https://github.com/highcharts/highcharts/issues/14076#issuecomment-675550844_

**Comment by sebastianbochan** [comment]
Hi @pankajd1990,
Im closing as duplicate of https://github.com/highcharts/highcharts/issues/14079
