### ISSUE TITLE
Spider web chart tooltip not showing correclty

### ISSUE THREAD

**Issue by sureshinfocorp** [highcharts/highcharts#14073]
#### Expected behaviour
Spider web all the points should show tool-tip. 

#### Actual behaviour
Some points tool tip are not showing. 

#### Live demo with steps to reproduce
https://jsfiddle.net/0n35j19t/

#### Product version
8.1.2

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Thank you for reporting the issue @sureshinfocorp 

*Internal note:*
Bisected to commit f3423c994f - FYI @raf18seb - could you check it?

**Comment by khlieng** [comment]
Fixed since 8.2.0 (#13801).
