### ISSUE TITLE
Tooltip dimensions calculated wrong

### ISSUE THREAD

**Issue by qoalu** [highcharts/highcharts#14082]
#### Expected behaviour
labelWidth and labelHeight corresponding with tooltip dimensions

#### Actual behaviour
labelWidth and labelHeight are 16

![image](https://user-images.githubusercontent.com/1624045/90605574-d9308580-e1fe-11ea-8617-292aec530e02.png)

#### Live demo with steps to reproduce

Happens when using custom header or point formatter with a display block/flex etc
```
    tooltip.headerFormat: '<span class="highcharts__cTooltipHeader">{point.key}</span>',

   .highcharts__cTooltipHeader {
      display: block;
   }
```

#### Product version
    "highcharts": "^8.1.2"
    "highcharts-react-official": "^3.0.0"

#### Affected browser(s)
Chrome, Safari

**Comment by sebastianbochan** [comment]
Hi @qoalu,
Thank you for reporting. Could you share your live demo? It will allow us to debug and find a solutions.

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
