### ISSUE TITLE
Could I avoid some operations during redraw?

### ISSUE THREAD

**Issue by poppinlp** [highcharts/highcharts#14081]
Hi.

I try to update only 1 point in a chart. The sample code is [here](https://stackblitz.com/edit/highcharts-try-instance?file=index.js) and the rendered page is [here](https://highcharts-try-instance.stackblitz.io/).

But I find that the painted area is always flashing for the whole chart by chrome dev tool, even the numbers on the axis.
![image](https://user-images.githubusercontent.com/1970625/90589961-edca4900-e211-11ea-8f18-ab43e5b749c5.png)

Could I do something to avoid that since I only wanna update 1 point? Really thanks.

**Comment by sebastianbochan** [comment]
Hi @poppinlp,
Thank you for contacting. When I run your demo I was not able to reproduce the problem with flickering. Please let me know about your OS and browser (including the full number of version).

![boost](https://user-images.githubusercontent.com/2115686/90608889-886f5b80-e203-11ea-8e7a-7346465ac8c3.gif)

**Comment by poppinlp** [comment]
Hi @sebastianbochan,

You could check the "Paint Flashing" checkbox in the Rendering tab from chrome dev tool on the [rendered page](https://highcharts-try-instance.stackblitz.io/). Then you will see it. :)

**Comment by poppinlp** [comment]
Seems I got the answer from another issue. Thanks.

**Comment by sebastianbochan** [comment]
Thank you for the feedback.
