### ISSUE TITLE
White line on stacked area charts 

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1408]
I've noticed in the examples that stacked area charts with no lineWidth shows a very thin white line separating each area of the graph. The line doesn't appear when stacking is null. 

http://jsfiddle.net/BN4SV/

Current master branch doesn't solve this problem.

**Comment by sdom** [comment]
+1

There is a white gap between two stacked areas.
Demo: http://jsfiddle.net/788k6aLg/9/

The gap doesn't appear on Ubuntu 14/Chrome 51.
System/browser tested on which appeared:
Ubuntu 14/Firefox 41

Windows 8.1/Chrome 51, Firefox 41, IE 11

**Comment by KacperMadej** [comment]
Unable to recreate using version 6.1.4
Tested on Win 10: Chrome / FF / Edge / IE11
