### ISSUE TITLE
android highcharts

### ISSUE THREAD

**Issue by sarah-geara** [highcharts/highcharts#14088]
i am using bar highchart , i have an issue concerning formatting numbers in tooltip i tried this way :
tooltip.setPointFormat("

<td style="text-align: right">{point.y:,.2f}");
and also this way :
chartView.lang = new HILang();
chartView.lang.setThousandsSep(",");

please note that i am using hichart in recyclerview .
Also note that when i use my hichart in a view pager the comma is showing.
Please help me to fix this, i am using this version : 6.1.4

**Comment by sebastianbochan** [comment]
Hi @sarah-geara,
Thank you for reporting. If you use our official android wrapper, please report the issue in the proper repo here: https://github.com/highcharts/highcharts-android. Android developer will answer you as soon as possible there.
