### ISSUE TITLE
Dynamically adding series with axis 'min' set to value causes series to render outside of plot area

### ISSUE THREAD

**Issue by gbenthomas** [highcharts/highcharts#14092]
#### Expected behaviour
Series should be rendered inside plot area when dynamically adding series + axis with `min` set.

#### Actual behaviour
Series gets rendered outside of plot area:

![image](https://user-images.githubusercontent.com/35936423/90665788-24a05f00-e212-11ea-8a88-ee3aaf1fe181.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/tvdr9a6q/

#### Product version
Highstock v8.1.2

#### Affected browser(s)
Chrome

Note: Redrawing the chart after a short delay fixes the issue. However, it still seems like a bug since all the APIs are redrawing (addAxis, addSeries, setData). Configurations for axes/series are all constructed dynamically and data is populated asynchronously in my app so knowing the right time to redraw without redrawing unnecessarily is challenging.

**Comment by pawelfus** [comment]
Thank you for reporting the issue @gbenthomas 

**Workaround:**
Disable animation: https://jsfiddle.net/BlackLabel/t0xgeuc7/

*Internal note:*
Might be related to #13939

**Comment by pawelfus** [comment]
Fixed since v8.2.0: https://jsfiddle.net/BlackLabel/ykwn1vfh/
