### ISSUE TITLE
How to make Bubble chart bubbles to stick together instead of overlapping or a way to position them so that its not cluttered

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/highcharts#14091]
#### Expected behaviour
Bubble chart with bubbles not too much overlapped or cluttered, so that its sticked to each other and easily readable

#### Actual behaviour
This is the jsfiddle with the issue. Here as you see the bubbles are overlapping. Please can you help sort this issue, so that the bubble dont overlap so that they will stick to the boundaries of each other, or a better way to show them a little bit overlapped, but not cluttered and it has to be easily readable

#### Live demo with steps to reproduce

https://jsfiddle.net/sreejithga/9bsnrkto/

#### Product version

Highcharts 8
#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Hi @Sreejithga 

Thanks for reporting the issue. Your idea of using `jitter` was a good one. Just this config should be set on the series level, not per point: https://jsfiddle.net/BlackLabel/06p9wkjv/1/ - however, it's configurable **per series**, so all points are misplaced the same way.

Concept of a plugin implementation to achieve jitter for all series, not per series:
Demo: https://jsfiddle.net/BlackLabel/06p9wkjv/2/

Plugin:
```js
(function(H) {
  H.wrap(
    H.seriesTypes.bubble.prototype,
    'applyJitter',
    function(proceed) {
      var series = this,
        jitter = this.options.jitter,
        len = this.points.length,
        sLen = this.chart.series.length,
        seriesOffset = series.index / (sLen + 1); // Plugin change
      /**
       * Return a repeatable, pseudo-random number based on an integer
       * seed.
       * @private
       */
      function unrandom(seed) {
        var rand = Math.sin(seed) * 10000;
        return rand - Math.floor(rand);
      }
      if (jitter) {
        this.points.forEach(function(point, i) {
          ['x', 'y'].forEach(function(dim, j) {
            var axis, plotProp = 'plot' + dim.toUpperCase(),
              min, max, translatedJitter;
            if (jitter[dim] && !point.isNull) {
              axis = series[dim + 'Axis'];
              translatedJitter =
                jitter[dim] * axis.transA;
              if (axis && !axis.isLog) {
                // Identify the outer bounds of the jitter range
                min = Math.max(0, point[plotProp] - translatedJitter);
                max = Math.min(axis.len, point[plotProp] + translatedJitter);
                // Find a random position within this range
                point[plotProp] = min +
                  (max - min) * unrandom(i + j * len + seriesOffset); // Plugin change
                // Update clientX for the tooltip k-d-tree
                if (dim === 'x') {
                  point.clientX = point.plotX;
                }
              }
            }
          });
        });
      }
    }
  );
})(Highcharts);
```

**Comment by Sreejithga** [comment]
Great thanks for your timely response. This helps indeed. Thank you !!!
