### ISSUE TITLE
Multiple series stock chart comes back as blank.

### ISSUE THREAD

**Issue by nectario** [highcharts/highcharts#14098]
The Multiple series stock chart comes back as blank. See below link from your demos. Click on "Compare multiple Series"

[https://www.highcharts.com/demo/stock/compare](https://www.highcharts.com/demo/stock/compare)

**Comment by sebastianbochan** [comment]
Hi @nectario,
Thank you for reporting. We will fix it as soon as possible.

**Comment by goransle** [comment]
Demo is now redeployed and is working as it should.
