### ISSUE TITLE
Exporting x-range data to CSV

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#14108]
#### Expected behaviour
Default options for exporting x-range data to CSV.

#### Actual behaviour
It looks like it only includes start dates, which isn't very helpful.
You have to customize and build your own table in the getDataRows function each time.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/ytL517mo/

#### Product version
v8.2.0

**Comment by LaniMoo** [comment]
Hi there, would it be possible to get a workaround for this?

**Comment by PaulDalek** [comment]
Hi @LaniMoo 

Thank you for contacting us. Here's the working workaround which simply appends the correctly formatted value of the `x2` to an existing category.

**Workaround**
https://jsfiddle.net/BlackLabel/dwmg45st/
