### ISSUE TITLE
Chart didn't render when only Axis maximum is set for scatter bubble chart in version 7.x

### ISSUE THREAD

**Issue by seintun** [highcharts/highcharts#14101]
Hello, I am experiencing the following failing visualization for Bubble Chart when maximum of axis is set.
This bug is identified after upgrading to Highcharts v7.2.1
**Failing between v6.1.4 and version 8. Possible some changes introduced in v6.1.4**

Reproduced when only axis maximum of either `x` or `y` is set.
The following example
• Didn't render when only xAxis.maximum is set anywhere from 4 to 14
• Render when both Axis.maximum and Axis.minimum is provided. Eg. (2, 4)
• Render when includeZero is enabled
• Render when Axis.maximum is given number equal/larger than 14
• Render when Axis.minimum is provided. Eg. (2)

Much appreciated!
Reference from https://www.highcharts.com/forum/viewtopic.php?f=9&t=44770&p=158652#p158652
#### Expected behaviour
![min2max4](https://user-images.githubusercontent.com/10414451/90894951-369b1280-e376-11ea-9d1d-5e1fd84883e7.png)

#### Actual behaviour
• Didn't render when only xAxis.maximum is set anywhere from 4 to 13
![max4](https://user-images.githubusercontent.com/10414451/90895005-4c103c80-e376-11ea-839e-7dab7019d4d8.png)

#### Alternative scenarios where it works
• Render when both Axis.maximum and Axis.minimum is provided. Eg. (2, 4)
![min2max4](https://user-images.githubusercontent.com/10414451/90895108-7a8e1780-e376-11ea-8bc8-90cc0ff96f01.png)

• Render when includeZero is enabled
![includeZero](https://user-images.githubusercontent.com/10414451/90895116-7eba3500-e376-11ea-9605-1278af20ccbd.png)

• Render when Axis.maximum is given number equal/larger than 14
![max14](https://user-images.githubusercontent.com/10414451/90895137-88439d00-e376-11ea-8628-a2661af500a2.png)

• Render when Axis.minimum is provided. Eg. (2) This snapshot is also how it looks like without any Axis.maximum or Axis.minimum given
![min2](https://user-images.githubusercontent.com/10414451/90895344-e2dcf900-e376-11ea-9747-b554b0109453.png)

#### Live demo with steps to reproduce

This is my data sets. Am I misconfiguring something based on the above screenshot?

v6.0.0 (Working)
https://jsfiddle.net/seintun/jwe5b7vf/5/
v6.1.4 (Started Failing)
https://jsfiddle.net/seintun/jwe5b7vf/9/
v7.0.0 (Failed)
https://jsfiddle.net/seintun/jwe5b7vf/3/
v8.0.0 (Working)
https://jsfiddle.net/seintun/jwe5b7vf/6/

#### Product version

Identified after upgrading to Highcharts v7.2.1 from v5.0.12
This bug appears to be introduced in Highcharts v7.0.0. Referring to same datasets and configs but different versions below:

#### Affected browser(s)
N/A

**Comment by pawelfus** [comment]
Hi @seintun 

Thank you for reporting the issue. That's correct, we have fixed this bug with bubble-series extremes in v8.0.0. Related ticket #12543

Please, upgrade your Highcharts version to v8+

**Comment by karolkolodziej** [comment]
As Paweł said, this issue has been resolved and works correctly since v8.x.x.
Closing as it no longer is a bug.
