### ISSUE TITLE
Highcharts .Net Wrapper properties missing or mismatch from API doc

### ISSUE THREAD

**Issue by JayHTang** [highcharts/highcharts#14102]
This is a problem related to the .net wrapper, not highcharts js.

After making changes according to http://dotnet.highcharts.com/Highcharts/Demo/Docs?section=UpgradeToStandard when upgrading Highsoft.Highcharts from version 6.2.0.23 to 8.1.2.1, I have found the following data errors.

1. 'PlotOptionsPie' does not contain a definition for 'DataLabels'. The API doc states DataLabels of type Hashtable as a property of PlotOptionPie.

2. SplineSeries.DashStyle should be type SplineSeriesDashStyle as per API doc, but the wrapper is expecting a Hashtable.

#### Expected behaviour

1. ![image](https://user-images.githubusercontent.com/12468970/90970516-d1f1cc00-e4cb-11ea-8485-6ba0b16108f9.png)

2. ![image](https://user-images.githubusercontent.com/12468970/90970503-a7077800-e4cb-11ea-8084-350aaa44de0b.png)

#### Actual behaviour
1. ![image](https://user-images.githubusercontent.com/12468970/90970568-5e9c8a00-e4cc-11ea-826a-88269a0f89d1.png)

2. ![image](https://user-images.githubusercontent.com/12468970/90970550-2bf29180-e4cc-11ea-8be6-7a6ff1b0c667.png)

#### Live demo with steps to reproduce
Can't make it in fiddle. But it can be easily reproduced in Visual Studio.

#### Product version
Identified after upgrading Highsoft.Highcharts from version 6.2.0.23 to 8.1.2.1
Microsoft Visual Studio Enterprise 2019 Version 16.6.4

#### Affected browser(s)
N/A

**Comment by brofixo** [comment]
Bugs. 
Expected release date for next version with fixes for those issues is current week.
