### ISSUE TITLE
No labels are shown below the color axis

### ISSUE THREAD

**Issue by creativeprogramming** [highcharts/highcharts#14105]
#### Expected behaviour
Show numeric labels below horizontal coloraxis gradient

#### Actual behaviour
![image](https://user-images.githubusercontent.com/954291/91021707-69523e80-e5f4-11ea-9874-3df8ba42e1cb.png)

**Comment by pawelfus** [comment]
Hi @creativeprogramming 

Thanks for reporting the issue. Could you provide live demo? Thanks!

**Comment by creativeprogramming** [comment]
Sorry was not an issue of highcharts but of our code to add custom svg title to color axis. Please consider the feature request https://github.com/highcharts/highcharts/issues/14107
