### ISSUE TITLE
legend navigation problem

### ISSUE THREAD

**Issue by hasuikhs** [highcharts/highcharts#14115]
#### Expected behaviour
apply navigation

#### Actual behaviour
i have been add navigation option.

like this.

`legend: {
    navigation: {
        arrowSize:12
}
}`

why this option is not working?

![problem](https://user-images.githubusercontent.com/50775570/91126071-1bb20080-e6de-11ea-8b25-e6af5fc4aec5.JPG)

#### Affected browser(s)
chrome

**Comment by pawelfus** [comment]
Hi @hasuikhs 

Thanks for reporting the issue. It's hard to say why it doesn't work for you. Could you recreate this issue in jsFiddle? We will check it. Official demo works fine: https://jsfiddle.net/BlackLabel/d2vs4Lyc/

**Comment by hasuikhs** [comment]
like this code.

this code.

Highcharts.chart('container', {
            chart: {
                Type: 'xy',
            },
            title: {
                text: null,
                align: 'left',
                margin: 40,
                x: 0,
                style: {
                    color: '#2a2e3d',
                    fontWeight: '500'
                }
            },
            xAxis: {
                categories: ["2020-01", "2020-02", "2020-03", "2020-04", "2020-05", "2020-06"],
                gridLineWidth: 1,
                gridLineColor: '#e8e8e8',
                crosshair: true
            },

            yAxis: [{
                title: {
                    text: 'data'
                }
            }],
            plotOptions: {
                area: {
                    fillOpacity: 0.2
                }
            },

            tooltip: {
                shared: true,
            },

            legend: {
                itemStyle: {
                    fontSize: '12px',
                    fontWeight: 'normal',
                    color: '#666666'
                },
                layout: 'horizontal',
                align: 'center',
                verticalAlign: 'top',
                symbolWidth: 20,
                borderWidth: 0,
                x: 0,
                itemMarginTop: -10,
                itemDistance: 20,
                itemHiddenStyle: {
                    color: '#9ea0ac'
                },
                navigation: {
                    animation: true,
                    arrowSize: 12
                }
            },

            series: [
            {
            name: 'one',
            type: 'area',
            data: [1, 2, 3, 4, 5, 6],
            marker: {radius:0}
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }, {
            name: 'two',
            type: 'spline',
            data: [1, 2, 3, 4, 5, 6]
            }
            ],

            responsive: {
                rules: [{
                    condition: {
                        maxWidth: 500
                    },
                    chartOptions: {
                        legend: {
                            layout: 'horizontal',
                            align: 'center',
                            verticalAlign: 'bottom'
                        }
                    }
                }]
            }
            })

**Comment by pawelfus** [comment]
The navigation doesn't start because there's plenty of space on the chart. To turn on navigation:
- remove `itemMarginTop: -10` 
- set `maxHeight: 40` (or any other value)

See working chart: http://jsfiddle.net/BlackLabel/n6b5h4o9/5/

**Comment by hasuikhs** [comment]
thank you very much.
