### ISSUE TITLE
[WORDPRESS PLUGIN] Error fired on TinyMce Button

### ISSUE THREAD

**Issue by hellosubotai** [highcharts/highcharts#14113]
Hello,
I just tried to test your plugin for WordPress.
It installs correctly and the new button displays well in the content editor.

Problem encountered: When I click on the button to display the chart editor, a red message appears and says:

There's a problem with your chart!
[object Object]

And I can't play with the data or display it as a graph.

Clarification: I am in freshly updated WordPress 5.5.

Thank you

**Comment by pawelfus** [comment]
Hi @hellosubotai 

Could you tell us which WordPress plugin do you use? Perhaps you use [`highcharts-editor`](https://github.com/highcharts/highcharts-editor), not Highcharts?

**Comment by hellosubotai** [comment]
Hi @pawelfus 
Thanks for the answer.
Yes, it's highcharts-editor WordPress plugin wich I got here : https://github.com/highcharts/highcharts-editor/releases

**Comment by pawelfus** [comment]
Thanks! Could you please report the issue here: https://github.com/highcharts/highcharts-editor/issues ? This repo is for Highcharts core bugs only. Thanks!

**Comment by hellosubotai** [comment]
Oh ok !! I'll do it. Thanks
