### ISSUE TITLE
label.element.contains gives an error in SVGLabel on Internet Explorer11

### ISSUE THREAD

**Issue by SharunSomani** [highcharts/highcharts#14110]
#### label.element.contains or span.element.contains throws an unhandled exception
on highcharts for ie11. It happens on hover

#### Product version
<!--- Highcharts, :8.0.0>

**Comment by pawelfus** [comment]
Hi @SharunSomani 

Thank you for reporting the issue, but could you create a demo where it fails? We tested it with this demo: https://jsfiddle.net/BlackLabel/h91fas7r/ - no errors on hover in legend or data labels.

**Comment by SharunSomani** [comment]
Fiddle cannot help as it is not able to run on ie-11, it is fine for other browsers , but we are facing this issue in ie11

**Comment by SharunSomani** [comment]
![image](https://user-images.githubusercontent.com/70138973/91168365-24610180-e6f3-11ea-8157-7050c23cf090.png)

**Comment by pawelfus** [comment]
Oh, I didn't know that. Do you encounter this issue in any of our official demos? https://www.highcharts.com/demo

**Comment by SharunSomani** [comment]
![image](https://user-images.githubusercontent.com/70138973/91215300-f0f19780-e731-11ea-993f-b674d481497e.png)
Sorry to say but they also don't seem to work in ie, can you test any of your demo app in ie

**Comment by SharunSomani** [comment]
Please check the issue in IE I can share you the exact error message

**Comment by pawelfus** [comment]
Thanks @SharunSomani - we are still unable to recreate the issue. Demo works fine, tested on:

> Windows 10 Pro 18363.1016
> IE11 11.1016.18362.0

**Comment by SharunSomani** [comment]
Can you please share same with me

**Comment by pawelfus** [comment]
This is the demo I was testing: https://www.highcharts.com/demo/annotations

**Comment by SharunSomani** [comment]
![image](https://user-images.githubusercontent.com/70138973/91289329-d8c05d80-e7af-11ea-9877-e5bdb9a02b9e.png)

**Comment by SharunSomani** [comment]
Same demo is not opening at my end Highcharts version which we are using is 8.0.0

**Comment by SharunSomani** [comment]
No chart opens on ie browser , worked hard on same can you share me screenshot ffor working chart and ie browser same verson

**Comment by SharunSomani** [comment]
![image](https://user-images.githubusercontent.com/70138973/91297352-cd732f00-e7bb-11ea-8dce-1fd6ff7df4ad.png)

**Comment by SharunSomani** [comment]
### on highcharts svg label hover

**Comment by pawelfus** [comment]
Thanks! Retested, it seems our website with demos is broken in IE11 (because of fat arrow function used on website, we will fix this as soon as possible) - thanks for pointing this out!

Meanwhile the same demo, tested in IE11: 

![image](https://user-images.githubusercontent.com/1453926/91430792-b259fb00-e85f-11ea-87ef-e3d1fa04e710.png)

Still, no errors when hovering elements on the chart. Should I focus on something particular?

**Comment by SharunSomani** [comment]
![image](https://user-images.githubusercontent.com/70138973/91431426-f9ef7f80-e87d-11ea-8cfa-354fc28ae3b7.png)

**Comment by SharunSomani** [comment]
My focus was on distance svg label

**Comment by SharunSomani** [comment]
how were you able run this on ie please share me the url

**Comment by pawelfus** [comment]
It was just copied code from demo to a local files.

Anyway, we are working on our demos in IE11: https://www.highcharts.com/demo/annotations - demo should be visible now (still some unrelated issues may pop up). Can you check it once again? Do you see the same error with label? We are still unable to recreate this, sorry.

**Comment by pawelfus** [comment]
@SharunSomani - are you able to recreate the issue with current demos? Thanks!

**Comment by KacperMadej** [comment]
Minimal demo (the key options are the tooltip settings):

```html
<!DOCTYPE html>
<html><head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script src="https://code.highcharts.com/highcharts.src.js"></script>
        <style>
            #container {
              width: 80%;
            }
        </style>
	</head><body>
        <div id="container"></div>

    <script type="text/javascript">
        Highcharts.chart('container', {
            series: [{
                data: [1,2,3]
            }],
            tooltip: {
                useHTML: true,
                style: {
                    pointerEvents: 'auto'
                }
            }
        });
    </script>
</body></html>
```
Steps: use IE11 and hover over the tooltip -> an error will show in the browser console.

The error (`label.element.contains` is `undefined`) happens in (on the line 294):
https://github.com/highcharts/highcharts/blob/ec2b3845069f09a1cf4375b4363797a04c70350b/ts/Core/Renderer/SVG/SVGLabel.ts#L270-L311

_Internal note:_
`label.element` is [`SVGGElement`](https://developer.mozilla.org/en-US/docs/Web/API/SVGGElement) and IE9+ has no support for the `contains` method for it (source: https://developer.mozilla.org/en-US/docs/Web/API/Node/contains)
