### ISSUE TITLE
Color Axis color gradient mismatch

### ISSUE THREAD

**Issue by creativeprogramming** [highcharts/highcharts#14125]
#### Expected behaviour
Color should be interpolated by the gradient

#### Actual behaviour
the color mismatch
![image](https://user-images.githubusercontent.com/954291/91205242-832f7680-e705-11ea-981c-b7dd0f651434.png)

**Comment by pawelfus** [comment]
Hi @creativeprogramming 

Could you please add **live demo** of the issue? We are not able to debug from images :) 

Thanks!

**Comment by creativeprogramming** [comment]
was due to using some non hex color in the stops
