### ISSUE TITLE
Column stacking is broken after chart update with specific options. 

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#14130]
#### Expected behavior
After chart update stacking should be applied correctly.

#### Actual behaviour
After chart update stacking is broken.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/w17ctxbd/

1. Just run the demo
2. Both charts should look the same, as in v8.1.0: https://jsfiddle.net/BlackLabel/e3o4fay9/

#### Product version
Highcharts v8.1.1

Bisected to commit: https://github.com/highcharts/highcharts/commit/57ce06ee444abb7b9c5e962c68dc6f5f831b64ae

**Comment by robguinness** [comment]
I confirm a similar issue when using v8.2.0. The stacked chart is broken on first load (some data missing), and when reloaded, it displays all data correctly. In v8.1.0, everything works fine.

**Comment by pawelfus** [comment]
FYI @TorsteinHonsi 

*Internal note:*
Removed wrong label
