### ISSUE TITLE
Misplaced tooltip when yAxis max value set (column chart)

### ISSUE THREAD

**Issue by rarakiroa** [highcharts/highcharts#14138]
I configured a column chart so that the yAxis has a max value and allowed to draw a tooltip outside of the chart as well. Columns that are cut off because of the max value seem to effect the tooltip position with their original size. 
When displaying negative values in combination with a min value set the same problem occurs.

![image](https://user-images.githubusercontent.com/7533426/91470851-878a9980-e895-11ea-84b2-388bda821e7b.png)

I would expect the tooltip to be positioned on top of the visible column.

Please see https://jsfiddle.net/rarakiroa/zbm92j7k/4/ to reproduce the issue. Hover any of the points exceeding the value of 100.

**Comment by pawelfus** [comment]
Thank you for reporting the issue @rarakiroa 

**Workaround:**
Use custom [`tooltip.positioner`](https://api.highcharts.com/highcharts/tooltip.positioner)
Demo: https://jsfiddle.net/BlackLabel/ax40zfrg/
Config:
```js
  tooltip: {
    outside: true,
    positioner: function(w, h, p) {
      var ret = this.getPosition(w, h, p);
		
      return {
        x: ret.x,
        y: this.chart.container.getBoundingClientRect().top + Math.max(this.chart.plotTop, p.plotY - h / 2) 
      }
    }
  },
```

**Comment by rarakiroa** [comment]
@pawelfus thanks for the workaround

**Comment by mwenz7178** [comment]
The tooltip does not get positioned properly using positioner when outside=true depending on where the main window scroll is at. 
All these work arounds/ fixes do not work.  High Charts should baseline the positioner to always take into consideration where the actual chart location is taking into consideration if the main window is scrolled or not.

**Comment by Izothep** [comment]
Thank you for your feedback @mwenz7178!

It looks that your report is related to another issue, available in the link below:
https://github.com/highcharts/highcharts/issues/14002
