### ISSUE TITLE
Tooltip's stickOnContact is not working when useHTML and split are enabled

### ISSUE THREAD

**Issue by andrzej-bieniek** [highcharts/highcharts#14143]
#### Expected behaviour
Tooltip should not change while mouse pointer is on it.

#### Actual behaviour
Tooltip jumps to next point when mouse is moved (default behaviour).

#### Live demo with steps to reproduce
https://jsfiddle.net/6hmz3k17/

Steps: Move mouse over a tooltip to observe tooltip jumping to next point.

#### Product version
Highcharts JS v8.2.0 (2020-08-20)

#### Affected browser(s)
All I tried with: chromium, firefox.

**Comment by pawelfus** [comment]
Thanks for reporting the issue @andyhelp 

@bre1470 - could you check it?

**Comment by raf18seb** [comment]
+1

**Comment by KacperMadej** [comment]
_Internal note:_
Looks like this is only a problem with `useHTML` + `stickOnContact` and not related to `split`.

**Comment by charlottedeiss** [comment]
I am also having this problem.
