### ISSUE TITLE
Waterfall stacking connectors are broken when yAxis reversed

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#14148]
#### Expected behavior
Stacking connectors should be rendered correctly.

#### Actual behaviour
Stacking connectors are rendered in the wrong places.

#### Live demo with steps to reproduce
v8.1.0 regression -> https://jsfiddle.net/BlackLabel/k3mqwc2u/
v8.0.4 expected result -> https://jsfiddle.net/BlackLabel/wd27cz9b/

#### Product version
Highcharts v8.1.0

**Comment by pawelfus** [comment]
*Internal note:*
Bisected to commit e70baaba67 (yes, there are some waterfall related changes).

Could you take a look @PaulDalek ?

**Comment by sebastianbochan** [comment]
Unstale

**Comment by khlieng** [comment]
@sebastianbochan why is this open again?

**Comment by sebastianbochan** [comment]
My mistake, the comment should be placed on a different ticket.

Sorry for the confusion!.
