### ISSUE TITLE
Range series jsFiddle demo on website isn't working

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#14140]
The jsFiddle demo at the bottom of [this website](https://www.highcharts.com/docs/chart-and-series-types/range-series) isn't working with https protocol: https://jsfiddle.net/highcharts/XjzFH/

#### Product version
Highcharts 8.2.0

**Comment by pawelfus** [comment]
Just a note: Don't fix the demo, use official fiddle from here: https://www.highcharts.com/demo/columnrange
