### ISSUE TITLE
xrange chart with more than one series tooltip position

### ISSUE THREAD

**Issue by Fadi2019** [highcharts/highcharts#14147]
#### Expected behaviour
tooltip should appear above the xrange point in the middle

#### Actual behaviour
the tooltip does not appear in the center

#### Live demo with steps to reproduce
https://jsfiddle.net/L5o21pyt/2/
![image](https://user-images.githubusercontent.com/58138368/91722709-536bed00-eba3-11ea-8840-e9e72c6a913b.png)

#### Product version
Highcharts

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Thank you for reporting this bug @Fadi2019 

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/x1Ldnzy7/
Plugin: 
```js
(function(H) {
  var clamp = Highcharts._modules['Core/Utilities.js'].clamp;

  H.wrap(
    H.seriesTypes.xrange.prototype,
    'translatePoint',
    function(p, point) {
      var ret = p.apply(this, Array.prototype.slice.call(arguments, 1));

      if (!this.chart.inverted) {
        point.tooltipPos[0] = clamp(
          point.plotX + point.shapeArgs.width / 2,
          0,
          this.xAxis.len - 1
        );
      }

      return ret;
    }
  )
})(Highcharts);
```

**Comment by Fadi2019** [comment]
worked, thanks, but needed to upgrade to 8.2 version of highcharts (does not work on 8.1 version for example)

**Comment by PaulDalek** [comment]
Hi @Fadi2019

To make it work with the 8.1.0 version, instead of the `'Core/Utilities.js'` use the `'parts/Utilities.js'` to load the `clamp` function.

**Demo:**
https://jsfiddle.net/BlackLabel/db2tengL/

**Comment by Fadi2019** [comment]
I am trying to be type strict (I don't want to use any),
do you have such the relevant types?

**Comment by pawelfus** [comment]
Hi @Fadi2019 

The workaround posted above uses internal methods/properties that are not available in TS definitions (and shouldn't be). You need to use `any` or wait for the official fix.
