### ISSUE TITLE
Open Redirect vulnerability when passing an HTML link to text elements on a chart

### ISSUE THREAD

**Issue by noahsal** [highcharts/highcharts#14157]
_Note: Text elements on a chart include axis titles, plot line labels, etc. This issue probably appears for any element being created using the `SVGRenderer.prototype.buildText` function._

#### Expected behaviour
The axis title, plot line label, etc. is not clickable and the input is rendered as plain text.

#### Actual behaviour
The text is clickable and is defined using an `<a>` tag that contains a `tspan` with the class name `highcharts-anchor`, and links the the inputted `href` url.

#### Live demo with steps to reproduce
[JSFiddle](https://jsfiddle.net/ph4q8m56/4/) - Hover over the "Click here" text to see the cursor update and the link destination. JSFiddle doesn't allow redirects, but you can open the link as a new tab as well. 

Note: The above JSFiddle uses the workaround posted in https://github.com/highcharts/highcharts/issues/13559 for ease of demonstration. However, this behavior was also observed on Highcharts 8.2.0.

#### Product version
Highcharts 8.2.0, Highcharts 6.1.0 (with and without workaround linked above) 

#### Tested browser(s)
Chrome Version 84.0

**Comment by pawelfus** [comment]
Thank you for reporting this issue @noahsal 

I'm not sure if this is a bug - this was expected behaviour since I remember.. This way you can add redirects to your chart (e.g. in tooltip, or xAxis labels). Ticket #13559 was about **how** it's implemented (`onclick` vs `a href`). Do I miss something? 

FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Agreed, it is not a bug. Highcharts allows a subset of HTML, including anchors. If you want to restrain end users from entering anchors into Highcharts, it must be filtered out before being passed to the chart configuration.
