### ISSUE TITLE
Gradient colors not working in plotOptions for specific charts types ex. bar

### ISSUE THREAD

**Issue by LoganDupont** [highcharts/highcharts#14156]
Highcharts TypeScript Declarations doens't allow to set `GradientColorObject[]` on colors instead we can only set `ColorString[]` (https://api.highcharts.com/highcharts/colors). It mentions that it's possible to also set default colors on series or series.type. So I investigated `plotOptions.[type].colors`. Here it's possible to set `GradientColorObject[]` (https://api.highcharts.com/highcharts/plotOptions.bar.colors).

#### Expected behaviour
If I set `GradientColorObject[]` on `plotOptions.[type].colors` I would expect that the gradient colors would be implemented on the different series. Ex. plotOptions.bar.colors

#### Actual behaviour
No gradient colors are visible on the chart. Instead we need to set `colorByPoint` to true in order to see gradient colors. But we don't want to see a different gradient color for each point. Instead this should be possible for each serie. I expect there are more chart types where this doesn't work. If we take a pie chart as example it seems to work (https://jsfiddle.net/pmkL2nho/).

If we don't look at the TypeScript Declarations and allow to set `GradientColorObject[]` on `colors` we are able to see the gradient colors on different series.  (https://jsfiddle.net/veLny8oz/1/)

#### Live demo with steps to reproduce
https://jsfiddle.net/veLny8oz/

#### Product version
Highcharts v8.0.0

#### Affected browser(s)
/

**Comment by pawelfus** [comment]
Hi @LoganDupont 

Thanks for reporting the issue. In fact there are two issues reported, and let me answer to them separately:

> Highcharts TypeScript Declarations doens't allow to set `GradientColorObject[]` on colors

That's a bug, it our definitions should allow this. @bre1470 could you take a look?

> If I set `GradientColorObject[]` on `plotOptions.[type].colors` I would expect that the gradient colors would be implemented on the different series. Ex. `plotOptions.bar.colors`

`plotOptions.[type].colors` applies only when `colorByPoint` is set to true. Check the description: https://api.highcharts.com/highcharts/plotOptions.bar.colors

**Comment by LoganDupont** [comment]
Okay thank you, I will wait until the fix is implemented.

**Comment by pawellysy** [comment]
unstale
