### ISSUE TITLE
Point.setVisible() missing in API docs

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#14167]
Link: https://api.highcharts.com/class-reference/Highcharts.Point

Note `Point.setVisible()` is available only for Pie series. Most of the others don't have this method implemented.

**Comment by totszwai** [comment]
Could Highcharts team please update the doc as well as the missing `TypeScript` definition on `Point`? :P

**Comment by raf18seb** [comment]
Hi @totszwai, we'll take a look at it soon. Thanks for bumping this up!
