### ISSUE TITLE
Highstock: Overlapping xAxis labels with ordinal false and tickPixelInterval

### ISSUE THREAD

**Issue by benebun** [highcharts/highcharts#1416]
After a lot of tests I hope I have narrowed down the problem of overlapping xAxis labels:

With ordinal set to false the xAxis labels get spaced out too generously and only a few labels are displayed. Lowering the tickPixelInterval makes the labels overlap.
The problem: There is no middle ground between those two extremes: Either they are spaced out too generously or they overlap.

Jsfiddle: a change of tickPixelInterval 70 (overlap: http://jsfiddle.net/benebun/VseVz/13/) to 75 (too wide: http://jsfiddle.net/benebun/VseVz/14/) illustrates the problem.
(The switch between those extremes already appears with +/- 1 difference of tickPixelInterval but to safely illustrate the problem across different OS and font renderings I used +/- 5)

**Comment by oysteinmoseng** [comment]
This seems to be an issue still, depending on whether or not we expect anti-overlapping logic even if the user specifies a `tickPixelInterval`.
