### ISSUE TITLE
centerInCategory for column chart results as one column

### ISSUE THREAD

**Issue by smokir** [highcharts/highcharts#14164]
#### Expected behaviour

Setting `centerInCategory: true` should work like [described](https://api.highcharts.com/highcharts/series.column.centerInCategory)

#### Actual behaviour

Setting `centerInCategory: true` results as one column for each category even categories with more than one columns

#### Live demo with steps to reproduce

https://jsfiddle.net/c7foq8ay/1/

#### Product version

Highcharts 8.2.0

#### Affected browser(s)

Chrome 84.0.4147.893

**Comment by smokir** [comment]
<img width="631" alt="Снимок экрана 2020-09-02 в 23 19 12" src="https://user-images.githubusercontent.com/2204174/92033285-17d44d00-ed74-11ea-918d-e1894a86d1e0.png">

Could you also please help me with correct set of options to prevent overlapping for columns in one category?

**Comment by pawelfus** [comment]
Hi @smokir 

Thanks for reporting the issue. Is that a real use-case? Do you have ~150 series on a chart? What I want to say: you have ~30 categories. That means you need to divide your chart into 30 equal parts and fit in there columns. Assuming you have 150series, that means you need at least 1px for each series to fit in there a potential point. In other words you need 150px per one category, 30x150px=> 4500px chart's width to fit all 1px columns. Now, you set `pointWidth: 5px` which means you need 22500px fit everything inside (also, I should mention that by default, every column has a 1px white border).

Let's increase the size of the chart and see the results: https://jsfiddle.net/BlackLabel/4hzL9wtv/1/ - we can observe now column directly above the category name. Columns are centered within the category, but huge amount of series cause them to be rendered in the middle - which looks like those overlap. Let's decrease number of series, just 10 of them: https://jsfiddle.net/BlackLabel/4hzL9wtv/2/ - as you can see, 10 series is reserving some space inside every category for every potential point that is right now null.

What you can do? Rethink how much data on a chart you want to display. In the worst case scenario, you are going to plot 150x30 -> 4500 columns on small chart, for example 450px, which means you will try to render 10columns in 1px. I am pretty sure this is not what your users wants to analyse :) 

Perhaps you want to use different series type? It's hard to guess. For sure, you can filter out all series that contains only null points in your dataset. Like this: https://jsfiddle.net/BlackLabel/4hzL9wtv/4/

If you have any other questions, please contact our support: https://www.highcharts.com/blog/support/

I can not acknowledge this issue as a bug - it's a limitation of how much you can display at once with given config, so I'm closing the ticket.

**Comment by smokir** [comment]
@pawelfus fair enough :) Thank you for reply!

It is indeed a real use-case. 

But what seems wrong is that we need to check data and viewport before enabling `centerInCategory: true`. I mean why does it look like 
<img width="613" alt="Снимок экрана 2020-09-07 в 22 26 07" src="https://user-images.githubusercontent.com/2204174/92413535-3e6dfb80-f159-11ea-946a-2755dc414839.png">
instead of 
<img width="607" alt="Снимок экрана 2020-09-07 в 22 26 18" src="https://user-images.githubusercontent.com/2204174/92413542-45950980-f159-11ea-947f-fae80cb50a5e.png">
even with `centerInCategory: true`? It doesn't look like backward compatibility.

**Comment by pawelfus** [comment]
Hi @smokir 

My apologies for the late reply! I'm not sure what do you mean by backward compatibility, I think `centerInCategory` always worked that way.

Regarding why it's rendered this way:
> Columns are centered within the category, but huge amount of series cause them to be rendered in the middle - which looks like those overlap.
