### ISSUE TITLE
Rendering buggy

### ISSUE THREAD

**Issue by iniatse** [highcharts/highcharts#14169]
#### Expected behaviour
The chart should render correctly if the chart gets created within an `div` with an `width: auto;` or an percantage width like `width:100%;` even if it gets created within a parent element which has not been added to the DOM at the creation of the chart.

Q: Why is this so important? 
A: First I want to mention that `width: auto;` and `width: 100%;` is of course fairly common and not everything has and should have an `width` defined in `px`. When you always have to create a highcharts only within an element which has already been added to the DOM, then you essentially force people to code in an suboptimal way which in turn introduces friction. 

As an example lets assume you have a `Slider` `class` and you want to provide an API which lets people add the slides via `options.elements.slides` like so:

```
var slide0 = document.createElement('div'); // `slide0` has an `width:auto;` and gets added to the DOM later at `slider.render()`
Highcharts.chart(slide0, {...});

var slide1 = document.createElement('div'); // `slide1` has an `width:auto;` and gets added to the DOM later at `slider.render()`
Highcharts.chart(slide1, {...});

var slider = new Slider({
	'elements': {
		'slides': [
			slide0,
			slide1,
		],
	},
})
slider.render();
```

It would not be possible to do that, it would not render correctly like within the jsfiddle.

So you are being forced to code in an other way like for example what would work is create a derived class from `Slider`, for example `FooSlider` and overwrite `Slider.render` within the derived class `FooSlider` by calling `render()` from the base-class `Slider` and then creating the charts like so:

```
FooSlider.prototype.render = function ()
{
	Slider.prototype.render.call(this);

	// Create charts here
};
```

But that is not very optimal, because now you do not know within `Slider.render` if there are empty slides etc you only know that after the execution of `FooSlider.render`.

#### Actual behaviour
The chart does not render correctly, see the jsfiddle's below.

#### Live demo with steps to reproduce
`width:auto;` example: [https://jsfiddle.net/0ut3yaq5/](https://jsfiddle.net/0ut3yaq5/)
`width:100%;` example: [https://jsfiddle.net/7hpujtmn/1/](https://jsfiddle.net/7hpujtmn/1/)

#### Product version
Highcharts

#### Affected browser(s)
Firefox and Chrome for sure, but I think all

**Comment by PaulDalek** [comment]
Thanks for reporting the issue @iniatse

We will check it and investigate it further but at first glance it seems that this problem occurs when the flexbox layout is in use.

**Comment by iniatse** [comment]
Thx, but not using flexbox layout at all is not an option for several reasons.

**Comment by pawelfus** [comment]
Workaround (solution?) is to set some artificial width (e.g. 1px) then resize chart calling `chart.setSize(null, null)`, for example: https://jsfiddle.net/BlackLabel/hwakne4u/2/

Why this happens? Because when you create a chart in a detached node, we don't know it's size. We need them to properly position elements (e.g. legend), so we temporary add this to DOM (parent=body). That means browsers return correct size (for width: 100%) but when later you add this container to a flex container, it's not resized (we don't use MutationObserver to monitor when container is added to DOM).

PS: When using `flex` container, don't forget about this issue #6427 (and workaround posted there).

**Comment by iniatse** [comment]
The animation in your example is completely different.

> Why this happens? Because when you create a chart in a detached node, we don't know it's size. We need them to properly position elements (e.g. legend), so we temporary add this to DOM (parent=body). That means browsers return correct size (for width: 100%) but when later you add this container to a flex container, it's not resized (we don't use MutationObserver to monitor when container is added to DOM).

Thx for the insight. Yes it seems that `MutationObserver` is the only way to solve this issue. Like so: [stackoverflow](https://stackoverflow.com/questions/20420577/detect-added-element-to-dom-with-mutation-observer#answer-45267350)

You could check if the element in which the chart should be rendered is already part of the DOM and if not use an `MutationObserver`.

**Comment by pawelfus** [comment]
Alternative workarounds:
1. Use this MutationObserver to create chart when element is added into the DOM. Something like this: https://jsfiddle.net/BlackLabel/hwakne4u/4/ (IE11+ required). 

2. Implement `afterRender` (or similar) events in `Slider` to create chart after first render.

**Comment by iniatse** [comment]
>     1. Use this MutationObserver to create chart when element is added into the DOM. Something like this: https://jsfiddle.net/BlackLabel/hwakne4u/4/ (IE11+ required).

I think this would work and I'll try that soon, but it would be much nicer if this "`MutationObserver` code" would live inside `highcharts`, because it is a bug. Would it be possible to fix this within future `highcharts` revisions?

>     2. Implement `afterRender` (or similar) events in `Slider` to create chart after first render.

I already did that, but that approach is  from my point of view extremely ugly.

**Comment by pawelfus** [comment]
>I think this would work and I'll try that soon, but it would be much nicer if this "MutationObserver code" would live inside highcharts, because it is a bug. Would it be possible to fix this within future highcharts revisions?

Yes, that would be nice to have this in core, I'm not saying we won't implement this!

> I already did that, but that approach is from my point of view extremely ugly.

I understand. Just my from point of view it's extremely clean solution.

**Comment by pawelfus** [comment]
That was not my point. What I wanted to say, that libraries providing event interfaces (e.g. `afterRender`, `afterSlide`, `afterSetExtremes` etc), that follow e.g. pub/sub pattern are easy to extend, manage, maintain and, what's the most important, easy to connect to each other. But that's not the point of this ticket anyway.

And yes, workarounds are never clean.

**Comment by iniatse** [comment]
> That was not my point. What I wanted to say, that libraries providing event interfaces (e.g. `afterRender`, `afterSlide`, `afterSetExtremes` etc), that follow e.g. pub/sub pattern are easy to extend, manage, maintain and, what's the most important, easy to connect to each other. But that's not the point of this ticket anyway.

Sry, then I missunderstood that. Can you please point me to a source or so where I can read something about that? I'm not sure what you mean.

**Comment by pawelfus** [comment]
I would suggest to read more about event-driven architectures and loose coupling. Probably stack exchange could be a good starting point.

**Comment by iniatse** [comment]
Ahhh I know hat you mean. I read over the word "event"...
