### ISSUE TITLE
Tooltip with scroll and action button - Donut chart

### ISSUE THREAD

**Issue by nikhilsaha** [highcharts/highcharts#14160]
#### Expected behaviour
On click or hover of the chart element, the tooltip opens. Custom data is shown inside which might require scroll and also further action button. Tooltip can be possibly a popup

![Sample State](https://user-images.githubusercontent.com/70641000/91979686-c01ded80-ed43-11ea-977b-4b8470418d23.JPG)

#### Actual behaviour
Not able to capture the tooltip for piecharts for click event

#### Product version
Highcharts 8.2.0

#### Affected browser(s)
Chrome
Safari

**Comment by pawelfus** [comment]
Hi @nikhilsaha 

Thank you for reporting the issue. Did you try `useHTML` option with some styling? For example: https://jsfiddle.net/BlackLabel/3suwxLdq/1/

**Comment by nikhilsaha** [comment]
Hi,

Thank you for the quick response. We are working on an Angular setup, this solution does not seem applicable there.

Also, is there any way we can select the text appearing on tooltip?

**Comment by pawelfus** [comment]
Hi @nikhilsaha 

Framework should not change how this solution works. Regarding this and other questions, could you please contact our support? See: https://www.highcharts.com/blog/support/

We are using GitHub issues for bugs and features reporting, not for support questions. Thanks!
