### ISSUE TITLE
Typescript type error for stockTools - gui - buttons

### ISSUE THREAD

**Issue by ziXet** [highcharts/highcharts#14173]
#### Expected behaviour
Expected this to work:
```
stockTools: {
                gui: {
                    "buttons": [ 'simpleShapes', 'lines', 'crookedLines', 'measure', 'advanced', 'toggleAnnotations', 'separator', 'verticalLabels', 'flags', 'separator', 'fullScreen' ],
                    enabled: true
                }
            },
```

#### Actual behaviour
It's throwing ts type error fir buttons:
Type 'string[]' is not assignable to type 'string'.      

#### Live demo with steps to reproduce
in highcharts.d.ts the type of the buttons defined as string instead of string[]
https://ibb.co/SKG5yNq

#### Product version
8.2.0

#### Affected browser(s)
All browsers

**Comment by PaulDalek** [comment]
Thanks for reporting the issue @ziXet

**Comment by hihajdus** [comment]
Fixed on master
