### ISSUE TITLE
Cluster Data Label Off Center Sporadically

### ISSUE THREAD

**Issue by codywsears** [highcharts/highcharts#14179]
#### Expected behaviour
The Highcharts cluster data labels will be center aligned vertically and horizontally within the cluster marker.

#### Actual behaviour
The Highcharts cluster data labels are mostly center aligned vertically and horizontally, but sporadically there will be one that is slightly to the right by a pixel or 2.
![image](https://user-images.githubusercontent.com/11416449/92257979-f6b25000-ee8a-11ea-9131-918289b713c7.png)
Notice the 9 in the above screenshot is not centered with the cluster.

#### Live demo with steps to reproduce
https://codepen.io/codywsears/pen/ZEWaMyJ

Refresh the page a couple times until you see a data label off-center.

#### Product version
Highcharts npm package version 8.1.2
MarkerClusters module

#### Affected browser(s)
Found on chrome

**Comment by KacperMadej** [comment]
Hi @codywsears 

Thank you for reporting the problem.

This issue could depend on the font and the difference between circle possible sub-pixel precision of the center placement and font pixel precision align. 1-2 pixel difference is within the rounding error between sub-pixel and pixel precision, so I am not sure if this could have a universal solution.

I am not able to recreate any significant placement difference for the same cluster points - maybe you could prepare a demo with fixed data and chart size, so the problem will be more visible?

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
