### ISSUE TITLE
Highstocks: color axis does not apply on "All" range in range selector

### ISSUE THREAD

**Issue by xy2iii** [highcharts/highcharts#14180]
#### Expected behaviour
When using a color axis, and selecting the "All" range in the [range selector](https://www.highcharts.com/docs/stock/range-selector), we should expect the colors to apply.

#### Actual behaviour
The color axis does not apply only on the "All" period.

#### Live demo with steps to reproduce
Demo: https://jsfiddle.net/xy2iii/1L0sgm8r/4/
1. Click on any period other than "All" in the range selector. The colors apply.
2. Click on the "All" period in the range selector. The colors do not apply.

#### Product version
Latest Highstock (v8.2.0)

#### Affected browser(s)
Chrome, Firefox

Thank you for your time!

**Comment by KacperMadej** [comment]
Hi @xy2iii 

Thank you for contacting us about the problem.

In case there is a lot of point the data in a Highcharts Stock chart will be grouped and color approximation by default uses the series color. If you will reduce the width of the chart in your demo the same problem will be visible with smaller x axis time range.

To resolve this you could disable dataGrouping like in this demo: https://jsfiddle.net/BlackLabel/ysmag85v/

This is not a bug, so the issue will be closed.
We use GitHub Issues as our official bug tracker. For technical support please use one of the support channels available for you listed here: https://www.highcharts.com/blog/support/
