### ISSUE TITLE
Dragging doesn't work on the added point - Gantt

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#14188]
#### Expected behaviour

It should work as in the case of using the `yAxis.categories`.

Demo: https://jsfiddle.net/BlackLabel/m572ebLr/

#### Actual behaviour

The attempt of dragging the added point adds a new point.

Demo: https://jsfiddle.net/BlackLabel/hpL2z0aq/

Related issue: https://stackoverflow.com/questions/63764542/problem-adding-new-point-in-my-chart-with-draggable-points#63764542
#### Product version
Highcharts Gantt JS v8.2.0 (2020-08-20)

**Comment by KacperMadej** [comment]
_Internal note:_
`addPoint` adds 2 points instead of 1 - after the drag, the points are visibly separated

**Comment by karolkolodziej** [comment]
_Internal note:_
A similar issue reported here #11439

**Comment by karolkolodziej** [comment]
It looks like merging #14221, will solve this issue.
Demo: https://jsfiddle.net/BlackLabel/7xtsyru5/ 
I'm going to add some test there to prevent that in the future.

**Comment by karolkolodziej** [comment]
From version 8.2.2 this issue doesn't occur. Looks like some commit between version fixed that.
v8.2.0 demo: https://jsfiddle.net/BlackLabel/t0azb6h2/
