### ISSUE TITLE
Update specific record

### ISSUE THREAD

**Issue by pankajd1990** [highcharts/highcharts#14181]
#### Expected behaviour
my scenario is i want to update specific data to chart

#### Actual behaviour
above is not working.
i am struggling in this issue.so kindly help me

#### Live demo with steps to reproduce
https://jsfiddle.net/pankaj_durve/v36ry5h1/21/

#### Product version
Highcharts, Latest

#### Affected browser(s)

chrome

**Comment by KacperMadej** [comment]
Hi @pankajd1990 

Thank you for contacting us.
This is not a bug - for technical support please contact us using one of the available for you support channels: https://www.highcharts.com/blog/support/

To update any point you could set id for each point. Next, find the point using [`chart.get`](https://api.highcharts.com/class-reference/Highcharts.Chart#get) and [`update`](https://api.highcharts.com/class-reference/Highcharts.Point#update) it. To update a series you could use the same steps as the API is consistent.

For more questions about this topic please continue in a correct support channel as we are using GitHub issues for bug reports and enhancement ideas only.
