### ISSUE TITLE
Variwide x-axis label wrong placed and overlap

### ISSUE THREAD

**Issue by vegaelce** [highcharts/highcharts#14187]
#### Expected behaviour
When displaying a Variwide (many columns with various width), x-axis labels should be calculated to be placed correctly

#### Actual behaviour
Some labels are wrong placed (see LEVALLOIS-PERRET label in the live demo) or there si an overlaping on the labels
I tried to change the orientation of the label (90°) but same things happened.

#### Live demo with steps to reproduce
http://jsfiddle.net/vegaelce/0vdgqfL3

#### Product version
current version

#### Affected browser(s)
all

**Comment by KacperMadej** [comment]
Hi @vegaelce 

Thank you for contacting us about the problem.

There is no "LEVALLOIS-PERRET" label in the demo you have shared. Could you check if the demo is wrong or if the labels string is?

Demo with a **workaround** from the related issue: http://jsfiddle.net/BlackLabel/mgqk836o/3/

_Internal note:_

Demo with the problem: http://jsfiddle.net/BlackLabel/z5ns9eLa/

Related / similar / same as #7635

**Comment by vegaelce** [comment]
Sorry,
I didn't saved my fiddle. 
Now the demo is OK, you'll can see the problem.
http://jsfiddle.net/vegaelce/0vdgqfL3
![image](https://user-images.githubusercontent.com/60974808/92404090-09e74900-f133-11ea-9b4f-af4b7f87c4d5.png)
