### ISSUE TITLE
MACD indicator dosn't work properly after changing shortPeriod

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14197]
#### Expected behaviour
Calculate this indicator for the whole available data.

#### Actual behaviour
After changing `shortPeriod` to a smaller number, few last points on the MACD indicator are missing.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/indicators/macd/
Change `shortPeriod` to 11.

#### Product version
Highstock JS v8.2.0

#### Affected browser(s)
ALL

**Comment by pawelfus** [comment]
A little bit better demo: https://jsfiddle.net/BlackLabel/30t4p9me/
