### ISSUE TITLE
Scrollbar Problem: Mobile Device

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#14193]
#### Expected behaviour
Correct operation of the scrollbar on a mobile device (as on a desktop).

#### Actual behaviour
When using the scrolling on the phone, we are not able to navigate with the scrollbar but only with the scrollbar buttons.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/a5fkphzq/

![test](https://user-images.githubusercontent.com/39968065/92454338-b1f72380-f1c0-11ea-9a95-ac961eec3e6e.gif)

#### Product version
Highcharts Basic v8.2.0

**Comment by pawelfus** [comment]
*Internal note:*
Broken since v7.0.2, v7.0.1 used to work fine: https://jsfiddle.net/BlackLabel/a5fkphzq/8/
