### ISSUE TITLE
Typescript declarations: Sunburst chart series levels

### ISSUE THREAD

**Issue by herecoulbeyourname** [highcharts/highcharts#14196]
#### Expected behaviour
The type _PlotSunburstLevelsOptions_ is missing the _'level?: number'_ property in highcharts 8. I assumed that this property was not necessary anymore. However, the _'levelSize'_ property among others are ignored without _'level'_ defined. Either add _'level?: number'_ back to _PlotSunburstLevelsOptions_ or make it work without it (treat the first _PlotSunburstLevelsOptions_ in the _'levels'_ array as level 1 and so on...)

#### Actual behaviour
The _PlotSunburstLevelsOptions[]_ typed levels defined in the sunburst options series don't work without a defined _'level'_ property

#### Live demo with steps to reproduce
Sunburst levelSize example:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/sunburst-levelsize/

The example doesn't work anymore if you remove the _'level'_ properties from the _PlotSunburstLevelsOptions_ object defined in _'levels'_:
https://jsfiddle.net/xtfbzn4o/

#### Product version
highcharts 8.2.0

#### Affected browser(s)
Chrome

**Comment by PaulDalek** [comment]
Hi @herecoulbeyourname 

Thank you for reporting this issue.

FYI @bre1470

**Comment by raf18seb** [comment]
As an addition from #14347 - we can consider adding API doclet for the `level` (sunburst.levels.level) property. Currently it's missing: https://api.highcharts.com/highcharts/series.sunburst.levels.level
