### ISSUE TITLE
forEach console error

### ISSUE THREAD

**Issue by miloszwojcik** [highcharts/highcharts#14192]
Hello,

I'm having some issues with the console error. 
I recreated the issue in this js fiddle https://jsfiddle.net/40khrmuj/1/

You can replicate the issue by doing these steps: 
1. Unselect items from the highcharts-legend-box
2. Try to add Vertical labels or Flags to the chart space

When I'm trying to add the label I'm getting the error. Is there any way to disable the specific GUI tab if there is no series shown? 

Thanks!

**Comment by PaulDalek** [comment]
Thanks for reporting the issue @miloszwojcik

_Internal note:_
Trying to place a flag in case series is hidden results in an error (in the `attractToPoint` function, from the `NavigationBindings` utils, `stock-tools` module) because `forEach` is called on null (the `points` property).

**Comment by miloszwojcik** [comment]
@PaulDalek same issue while using 'silmple shapes' form highstock gui. 

Replicate the issue by these steps:
1. add a circle to the chart
2. unselect the 'AAPL' series

NOTE: the circle jumps and the error appears in the console. Add a series and move the circle => errors in the console. 

<img width="1075" alt="Screen Shot 2020-09-21 at 12 05 36" src="https://user-images.githubusercontent.com/33060899/93755346-67839700-fc03-11ea-879f-403aa595a1a4.png">

**Comment by pawelfus** [comment]
**Workaround:**
Set [`chart.ignoreHiddenSeries`](https://api.highcharts.com/highcharts/chart.ignoreHiddenSeries) to true: https://jsfiddle.net/BlackLabel/unz6fx9c/

I agree with you @miloszwojcik - the best would be to disable certain buttons when there's no way to add annotations (pane is invisible).

**Comment by OldBuddy** [comment]
@pawellysy looks like b6d67535f5dbf3a9f769a94086ea6eaff83fc63c has broken my button on highcharts.
This is the error I'm getting when clicking it: `ERROR TypeError: i.button.className.indexOf is not a function`.
Tried to debug it, and in my case, `i.button.className` is [SVGAnimatedString](https://developer.mozilla.org/en-US/docs/Web/API/Element/className#notes)
Could you please check usage of `classname`? Thanks.

**Comment by pawellysy** [comment]
Hi @OldBuddy, Thanks for contacting us with your issue. My guess is that you are using your own custom GUI, am I right? Could you reproduce your Issue in the demo?
You could use this demo: https://jsfiddle.net/BlackLabel/u2z6s3jw/

**Comment by OldBuddy** [comment]
@pawellysy, [Here](https://jsfiddle.net/rfuLzdyh/1/) is simplified demo. Click on custom button: 'Add new annotation'.

**Comment by pawellysy** [comment]
Thank you for sharing your demo! I've opened a new issue here: https://github.com/highcharts/highcharts/issues/16675
You can track this issue for an ETA in solving it, or possible workaround
