### ISSUE TITLE
highcharts-3d renders columns with two yAxis incorrectly

### ISSUE THREAD

**Issue by mosijava** [highcharts/highcharts#14198]
#### Expected behaviour
expected 3d form of this chart:
![chartnot3d](https://i.ibb.co/tYj11HM/Screenshot-from-2020-09-09-13-41-06.png)

#### Actual behaviour
this is a [fiddle](https://jsfiddle.net/mosijava/rgh63ve8/5/) to actual behaviour

as you can see all of the columns renders in one `yAxis` and stacked together.

![chart3d has problem with two yAxis](https://i.ibb.co/N79vWVX/Screenshot-from-2020-09-09-13-47-13.png)

**Comment by PaulDalek** [comment]
Hi @mosijava

Thank you for reporting this issue. It looks like all columns are displayed in the same yAxis section as the last visible series.

FYI @Izothep 

_Internal note:_
The `columnGroup` receives `translateX` and `translateY` from the lastly rendered series (the wrap of the `plotGroup`, in the `highcharts-3d` module).
