### ISSUE TITLE
Axis extremes update failing after manual scrolling

### ISSUE THREAD

**Issue by churajw2** [highcharts/highcharts#14200]
#### Expected behaviour
After a manual scroll, the axis extreme update should scroll the chart.

#### Actual behaviour
After the manual scroll, the programmatic scrolling fails to update the chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/jchura/e2uj5q39/
Focus the graph and use 'up' and 'down' arrow keys to update the view.  
Use the mouse to grab the scrollbar and scroll the view manually.  
Focus the graph again and try to use the arrow keys, nothing updates.

#### Product version
Highcharts 8.1.2, Highstock 8.1.2

#### Affected browser(s)
Chrome

**Comment by PaulDalek** [comment]
Hi @churajw2

Thank you for reporting this. This behavior is not a bug. In a nutshell, changing the extremes the way you do it, updates only the `min` and `max` options. It will work, until the manual scrolling occurs. Then, the `userMin` and `userMax` properties are created. Upon updating the `axis` later, they are remembered and they take precedence over the new `min` and `max` values, therefore ultimately the extremes won't change and the visible range will stay the same. So it's better to use the `setExtremes` function (https://api.highcharts.com/class-reference/Highcharts.Axis#setExtremes) as it modifies values of the `userMin` and `userMax` as well.

**Demo**
https://jsfiddle.net/BlackLabel/q79xz21r/
