### ISSUE TITLE
Histogram does not update when empty array passed as new data

### ISSUE THREAD

**Issue by johngwilkinson** [highcharts/highcharts#14209]
#### Expected behaviour
When a histogram is updated from having data to having none, it should update to match what appears when the histogram has no data initially.

#### Actual behaviour
The chart does not change when updated with an empty array.

#### Live demo with steps to reproduce
https://jsfiddle.net/uabwevzL/

#### Product version
Highcharts 8.1.2

#### Affected browser(s)
Chrome (probably all)

**Comment by johngwilkinson** [comment]
This may be related to the fix for #11388
https://github.com/highcharts/highcharts/pull/11411/files

**Comment by PaulDalek** [comment]
Hi @johngwilkinson

Thank you for reporting this issue. When the series is updated with an empty array, the calculation for the histogram series isn’t performed (see the `setDerivedData` function, in the `histogram-bellcurve` module).

**Workaround**
```
(function(H) {
  H.seriesTypes.histogram.prototype.setDerivedData = function() {
    var yData = this.baseSeries.yData;

    if (!yData.length) {
      this.setData([], false);
      return;
    }

    var data = this.derivedData(yData, this.binsNumber(), this.options.binWidth);
    this.setData(data, false);
  };
}(Highcharts));
```

**Demo**
https://jsfiddle.net/BlackLabel/evhnxs75/

**Comment by johngwilkinson** [comment]
Thanks for the workaround! Do you expect to ship a fix at some point?
