### ISSUE TITLE
Can't load in rsi for small ohlc values 

### ISSUE THREAD

**Issue by jestersimpps** [highcharts/highcharts#14202]
#### Expected behaviour

load the rsi line normally

#### Actual behaviour

rsi is always 100

#### Live demo with steps to reproduce
https://jsfiddle.net/26khypbL/

#### Product version

    "highcharts": "^8.2.0",
    "highcharts-indicators": "^2.1.6",

#### Affected browser(s)

all

**Comment by PaulDalek** [comment]
Hi @jestersimpps

Thank you for reporting this. Actually, you can by simply increasing the number of decimals that are used in RSI calculations. It can be set through the `decimals` option (https://api.highcharts.com/highstock/series.rsi.params.decimals). By default it’s set to 4.

Demo
https://jsfiddle.net/BlackLabel/43f0cypw/

**Comment by jestersimpps** [comment]
Nice! that works! thx
