### ISSUE TITLE
Documentation demo links not working

### ISSUE THREAD

**Issue by qoalu** [highcharts/highcharts#14206]
#### Expected behaviour
jsfiddle demo links working

#### Actual behaviour
Not working

#### Live demo with steps to reproduce
1. Open: https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting
2. Open any [DEMO] link

**Comment by qoalu** [comment]
The fix is setting the highcharts library url to https

**Comment by PaulDalek** [comment]
Hi @qoalu

Thank you for reporting this issue.
