### ISSUE TITLE
Average data grouping for column chart

### ISSUE THREAD

**Issue by pankti11** [highcharts/highcharts#14203]
#### Expected behaviour
Column chart configured to apply average grouping.
series['dataGrouping'] = {approximation: 'average'};

#### Actual behaviour
Column chart applying sum grouping probably. Please explain me if my math is wrong

#### Live demo with steps to reproduce
at 12:22 the value here is 2.82 with time range 11:30 am to 3:00 PM
![image](https://user-images.githubusercontent.com/25067151/92644005-adaa3380-f2b0-11ea-99c1-01617e09e211.png)

However, when the time frame is decreased to 12:21 PM to 12:23 PM, there is no value more than 0.79. So, I think if I am using average grouping it should be somewhere near to 0.79. That is what makes me confused.
![image](https://user-images.githubusercontent.com/25067151/92644144-dfbb9580-f2b0-11ea-9130-11d5b8903498.png)

#### Product version
version: 7.2.1

Please let me know if I am missing any configuration or any concept

**Comment by PaulDalek** [comment]
Hi @pankti11

Thank you for reporting this.

The point’s value depends on the y values that build the grouped point. You can always check if calculations are correct by investigating the `dataGroup` object (https://api.highcharts.com/class-reference/Highcharts.Point#dataGroup) of a point to see the length and starting index of a group. If you still think that it’s a bug, please provide us with a live example where this behavior can be recreated. Also, it is more of a support question, so please next time consider contacting us using one of the available support channels first (more info here: https://www.highcharts.com/blog/support/).

**Comment by pankti11** [comment]
Hello @PaulDalek 

Thanks for the quick response!

I Figured out the bug in our code. Closing the issue.
