### ISSUE TITLE
Case sensitive import issue in `FlagsSeries.js`

### ISSUE THREAD

**Issue by thematho** [highcharts/highcharts#14201]
#### Expected behaviour
Adding Highstocks in a lit-element wrapper and demoing using `@open-wc/demoing-storybook": "^0.4.0"`

Import Highstocks as `es-module`:
`import Highcharts from 'highcharts/es-modules/masters/highstock.src.js';`

#### Actual behaviour
Error:
```
Module not found: Error: [CaseSensitivePathsPlugin] `/user/myproject/node_modules/highcharts/es-modules/Mixins/OnSeries.js` does not match the corresponding path on disk `mixins`.
 @ ./node_modules/highcharts/es-modules/Series/FlagsSeries.js 21:0-50 285:15-28 286:16-29
```
The `highcharts/es-modules/Series/FlagsSeries.js` is trying to import: `highcharts/es-modules/Mixins/OnSeries.js` however the real path is `highcharts/es-modules/`**`mixins`**`/OnSeries.js`

#### Product version
`"highcharts": "^8.2.0"`

**Comment by PaulDalek** [comment]
Hi @thematho

Thank you for reporting this issue.

**Comment by pawelfus** [comment]
FYI @bre1470

**Comment by bre1470** [comment]
Distribution repository has been modified. It should fix the case issue in all our distribution channels with the next release.

**Comment by bre1470** [comment]
Fix confirmed.
