### ISSUE TITLE
Inconsistent tick alignment

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#14216]
#### Expected behaviour
Tick alignment and amount should be persistent on a certain container width.

#### Actual behaviour
After resizing the container to the smaller width, and then resizing it back to the initial value the tick amount/positions will be different than on the initial width. 

Note: it is not working correctly since the **8.1.1** version

#### Live demo with steps to reproduce
**Steps:**
0/ Remember the actual tick positions/amount
1/ Click on the "275" button
2/ Click on the "900" button
3/ Note that ticks are different than before resizing 

**Live demo:**
https://jsfiddle.net/BlackLabel/jazvkhcm/

#### Product version
8.1.1 and above

#### Affected browser(s)
All

**Comment by mateuszkornecki** [comment]
I didn't mention that, but it might be crucial to reproduce the issue. The result view in the JSfiddle should be set to **580px**, then you should notice the bug.

### 8.2.0
**BEFORE:**
![Screenshot 2020-09-15 at 08 12 47](https://user-images.githubusercontent.com/50931078/93172743-bb860b80-f72b-11ea-8d7c-94c1899f0674.png)
**AFTER:**
![Screenshot 2020-09-15 at 08 12 56](https://user-images.githubusercontent.com/50931078/93172748-bd4fcf00-f72b-11ea-8cb1-5c6cbc3387c9.png)

### 8.1.0
**BEFORE:**
![Screenshot 2020-09-15 at 08 13 18](https://user-images.githubusercontent.com/50931078/93172784-cc368180-f72b-11ea-8b8f-8ef3d48623e6.png)
**AFTER:**
![Screenshot 2020-09-15 at 08 13 24](https://user-images.githubusercontent.com/50931078/93172793-cfca0880-f72b-11ea-9d12-0338524bcae6.png)

**Comment by pawelfus** [comment]
Bisected to commit 57ce06ee44

PS: I'm not sure if this is really a bug. Just a standard use-case where initial `tickPositions` are different from every subsequent redraw. What do you think @TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
It's not a bug. Highcharts _approximates_ the tick pixel interval between redraws, so it may not be exactly the same on initial load and after a redraw.

**Comment by ori007a** [comment]
@TorsteinHonsi but this is only from version 8.1.1 - before it's works great!
How can we solve this?

**Comment by TorsteinHonsi** [comment]
Actually since v9.0 it works again like it did in v8.1.0: https://jsfiddle.net/BlackLabel/jazvkhcm/

**Comment by ori007a** [comment]
@TorsteinHonsi 
on resize it still have the bug.
check out this gif (left axis) before resize max value is 30. after resize and back to normal size, max value is 32.
![2021-03-09 11 06 33](https://user-images.githubusercontent.com/16095252/110446432-d5dfe700-80c7-11eb-97ec-d948a3384533.gif)

can you advive?
using HC 9.0.1 version.

**Comment by ori007a** [comment]
In my browser both versions works as expected.
It's should be on resize and not reflow.
I'm not sure what problem do you see in your browser. can you show me?

![2021-03-10 12 19 56](https://user-images.githubusercontent.com/16095252/110614475-0ba1d000-819b-11eb-9823-e0471ea04dfd.gif)

**Comment by KacperMadej** [comment]
The inner yAxis starts with max as `30` and changes for good to `32` after the first reflow.

![resize-30-32](https://user-images.githubusercontent.com/8960408/110643338-49f7b900-81b4-11eb-920a-eee7719eab89.gif)

Tested on Windows 10 with
- Chrome v88
- Firefox v86
- Edge v89
- Opera v74

@ori007a  You could try changing the height of the chart by a few pixels until the problem will show - that is how I recreated it. What's your OS and browser?

**Comment by ori007a** [comment]
@KacperMadej 
I succeed to recreate it. with change the sizes little bit.
Here: 
https://jsfiddle.net/m2h9spn8/
I used mac os Catalina with Chrome Version 89.0.4389.72

![2021-03-11 16 09 13](https://user-images.githubusercontent.com/16095252/110799800-37e54b80-8284-11eb-86a1-3184bdab3c12.gif)

can you solve this?

**Comment by ori007a** [comment]
@KacperMadej  ?

**Comment by KacperMadej** [comment]
Right, sorry about the delay.

> this is only from version 8.1.1 - before it's works great!

I am unable to resolve the problem through v8.1.1 - are you, @ori007a ?

It looks like when there is no need then the axis scale is not changed.
The initial render is different than the one with a small width because the available space is different.
When going back to the initial width the change of space is not significant enough to cause different ticks layout.
As a **workaround**, it could be forced by an update that will force the change: https://jsfiddle.net/BlackLabel/wzcvsed3/

If the used small size is closer to the initial width then the problem is not recreated. This might be so because the demo doesn't recreate your problem fully.

If there are chart widths that you need to support differently you could use [`responsive`](https://api.highcharts.com/highcharts/responsive) option. Otherwise to ensure a consistent tick layout you could set tickPositioner with a more strict function than the one used by default.
