### ISSUE TITLE
What is error/13,as below picture

### ISSUE THREAD

**Issue by luly2020** [highcharts/highcharts#14218]
![image](https://user-images.githubusercontent.com/71260871/93073610-c00fdd00-f6b5-11ea-9f82-eb23e65bcca9.png)

**Comment by PaulDalek** [comment]
Hi @luly2020

Thank you for reporting this. This [error](https://www.highcharts.com/errors/13/) means that the rendering div for a chart was not found. As this ticket doesn't describe an issue, please use one of the available [support channels](https://www.highcharts.com/blog/support/) to ask such questions in the future.

**Comment by luly2020** [comment]
Hi PawelDalek,

Thank you for your reply.
Another problem: https://www.highcharts.com/errors/13/  I cannot access it and only show loading…
[cid:image001.png@01D68B48.FEC4B9E0]
