### ISSUE TITLE
Highsoft.Highcharts missmatch behaviour

### ISSUE THREAD

**Issue by wencesbc** [highcharts/highcharts#14215]
Brief summary:
Seems like the Highsoft.Highcharts is not up- to date against js API as there is one object on organization charts wich seems to be the wrong type in the .net code.

#### Expected behaviour
The Highcarts .net library allows to generate a 1:1 match to the js highchart for all chart types.

#### Actual behaviour
On the .net library the type for OrganizationSeries.Nodes is OrganizationSeriesNodes with is a single object and not a collection of OrganizationSeriesNode (assumed name).

#### Live demo with steps to reproduce
Compare documentation of .net and js libraries

https://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_organization_series.html
vs 
 https://api.highcharts.com/highcharts/series.organization

#### Product version
Highsoft.Highcharts 8.1.2.3
HighCharts JS 8.2

#### Affected browser(s)
All (Server Side)

**Comment by PaulDalek** [comment]
Hi @wencesbc

Thank you for reporting this issue. I’ve notified our .NET developer about this problem so it should be resolved soon.
