### ISSUE TITLE
Parliament Chart throws error for negative values

### ISSUE THREAD

**Issue by SanjanaPriya** [highcharts/highcharts#14214]
Expected behaviour
        If any one of the inputs contains negative value, parliament chart can simply ignore that negative value and plot rest of the values.

Actual behaviour
        Parliament chart throws error if the input contains negative values.

Demo
       https://jsfiddle.net/s3dgua1t/

Product version
      Highcharts v8.2.0

**Comment by PaulDalek** [comment]
Hi @SanjanaPriya

Thank you for reporting this issue.

**Internal note** 
In case of a negative value of any of the points, the `series.slots` array of the last series is shorter than is supposed to be, which results in `undefined` when the `series.slots.shift()` is called (the `drawPoints` of the `item-series` module).

Here’s a quick workaround that prevents the error (but still isn’t a final solution).

**Workaround**
https://jsfiddle.net/BlackLabel/pcj1ntos/

**Comment by pawelfus** [comment]
*Internal note:*
Solution: Use the same logic as in a pie chart to handle negative values (`point.isValid()` method).
