### ISSUE TITLE
Can not freely drag (liveRedraw) with Navigator/Scrollbar+ xAxis(label format) functionality.

### ISSUE THREAD

**Issue by AnanditaP** [highcharts/highcharts#14217]
#### Expected behaviour
User should be able to drag beyond frame with Navigator/scrollbar+xAxis(label format) functionality.

#### Actual behaviour
User is not able to drag beyond certain date. This happens because navigator: {enabled: true}. If navigator removed, then user can drag freely but label format on the xAxis breaks.

#### Live demo with steps to reproduce
Please Run this below code -
```js
Highcharts.ganttChart('container', {
  chart: {
    type: 'gantt'
  },
  navigator: {
    enabled: true
  },
  xAxis: [{
    "grid": {
      "enabled": true
    },
    "opposite": true,
    "tickInterval": 86400000,
    "labels": {
      "format": "{value: %d}",
      "align": "center",
      "overflow": "allow",
      "useHTML": true
    },
    "minPadding": 0.2,
    "maxPadding": 0.2,
    "type": "datetime",
    "index": 0,
    "isX": true
  }, {
    "grid": {
      "enabled": true
    },
    "opposite": true,
    "linkedTo": 0,
    "tickInterval": 2592000000,
    "labels": {
      "format": "{value: %b, %Y}",
      "align": "center",
      "overflow": "allow",
      "useHTML": true
    },
    "minPadding": 0.2,
    "maxPadding": 0.2,
    "type": "datetime",
    "index": 1,
    "isX": true
  }],
  series: [{
    dragDrop: {
      draggableX: true,
    },
    data: [{
      start: Date.UTC(2020, 8, 12),
      end: Date.UTC(2020, 8, 23),
    }]
  }]
});

```

#### Product version
Hichart Gantt - 8.0,4

**Comment by pawelfus** [comment]
Thank you for reporting this issue @AnanditaP 

This is related to the `minPadding` and `maxPadding` options that are increasing the visible plot area. I thought that options are disabled when using navigator, but it seems I'm wrong (Highcharts Stock: https://jsfiddle.net/BlackLabel/m8uqskwa/2/).

**Workaround:**
Remove (or set to 0) `minPadding` and `maxPadding` options: https://jsfiddle.net/BlackLabel/m8uqskwa/5/

**Comment by AnanditaP** [comment]
Hi @pawelfus ,

Thank you for the reply.

I'm unable to drag beyond the date 22nd sept, In the workaround fiddle that you shared -(https://jsfiddle.net/BlackLabel/m8uqskwa/5/).

Please check dragging provided by below two different codes. The only difference is minPadding and maxPadding is provided in one and not in other. 

**Code 1 -** 

Highcharts.ganttChart('container', {
    chart: {
        type: 'gantt'
    },

    title: {
        text: 'Highcharts draggable gantt demo'
    },

    xAxis: {
        minPadding: 0.2,
        maxPadding: 0.2
    },
    series: [{
        name: 'Project 1',
        dragDrop: {
            
            draggableX: true,
           
        },
        data: [{
            start: Date.UTC(2014, 11, 1),
            end: Date.UTC(2014, 11, 2),
            completed: 0.95,
            groupId: 'group1',
            y: 0
        }, {
            start: Date.UTC(2014, 11, 3),
            end: Date.UTC(2014, 11, 5),
            groupId: 'group1',
            y: 0
        }, {
            start: Date.UTC(2014, 11, 2),
            end: Date.UTC(2014, 11, 5),
            y: 1
        }]
    }]
});


**Code 2 -** 

Highcharts.ganttChart('container', {
    chart: {
        type: 'gantt'
    },

    title: {
        text: 'Highcharts draggable gantt demo'
    },

    xAxis: {
      
    },
    series: [{
        name: 'Project 1',
        dragDrop: {
            
            draggableX: true,
           
        },
        data: [{
            start: Date.UTC(2014, 11, 1),
            end: Date.UTC(2014, 11, 2),
            completed: 0.95,
            groupId: 'group1',
            y: 0
        }, {
            start: Date.UTC(2014, 11, 3),
            end: Date.UTC(2014, 11, 5),
            groupId: 'group1',
            y: 0
        }, {
            start: Date.UTC(2014, 11, 2),
            end: Date.UTC(2014, 11, 5),
            y: 1
        }]
    }]
});

Kindly let me know If I'm missing anything.

**Comment by pawelfus** [comment]
You can, but there's very little space between right edge of the plotting area and chart's container:

![right-edge](https://user-images.githubusercontent.com/1453926/93185788-24767f00-f73e-11ea-9c17-0f57f42a7ebe.gif)

**Comment by AnanditaP** [comment]
Expecting user to drag the bar slowly and putting so much efforts does not seem to be user friendly.
​Dragging behavior should be smooth.
​Also, the other issue with the solution provided is that xAxis labels are getting crunched when dragged for a longer span.

**Comment by pawelfus** [comment]
> Expecting user to drag the bar slowly and putting so much efforts does not seem to be user friendly.

I agree with you, it's not really user-friendly. Any thoughts @oysteinmoseng ?

> ​Also, the other issue with the solution provided is that xAxis labels are getting crunched when dragged for a longer span.

It's caused by setting `tickInterval` to one day.

**Comment by oysteinmoseng** [comment]
Agree that we should look into ways to make this more user friendly. You'll observe similar UX issues trying to drag the whole point beyond the current x/y axis minimum/maximum - where the axis very quickly expands.

**Comment by AnanditaP** [comment]
Is there any way by which I can switch from day to week, week to month , month to 3 months , 3 months to 6 months and then finally 6 months to years while dragging like rangeSelectors to avoid xAxis label UI breaking
Please suggest any solution or workaround.

**Comment by pawelfus** [comment]
@AnanditaP - simply remove `tickInterval` and let Highcharts handle this. You can also use other options, like [`tickPixelInterval`](https://api.highcharts.com/gantt/xAxis.tickPixelInterval), [`tickAmount`](https://api.highcharts.com/gantt/xAxis.tickAmount) and finally [`tickPositioner`](https://api.highcharts.com/gantt/xAxis.tickPositioner).

**Comment by AnanditaP** [comment]
![without-tickinterval](https://user-images.githubusercontent.com/50946271/93602338-1e9fc880-f9e0-11ea-8ef7-d54cad2c497b.png)
![without-tick-interval-month-ending](https://user-images.githubusercontent.com/50946271/93602344-1fd0f580-f9e0-11ea-852d-21dc50894256.png)
![with-tick-interval](https://user-images.githubusercontent.com/50946271/93602346-20698c00-f9e0-11ea-8d03-c39499e5abc3.png)
![with-tick-interval-month-ending](https://user-images.githubusercontent.com/50946271/93602349-21022280-f9e0-11ea-9910-999ce9a7b8df.png)

PFA - Images with and without tickInterval. I tried using tickPixelInterval, tickAmount and tickPositioner in place of tickIntervals, but I didn't get required result.

**Comment by AnanditaP** [comment]
`Highcharts.ganttChart('container', {
    chart: {
        type: 'gantt'
    },

    title: {
        text: 'Highcharts draggable gantt demo'
    },
    navigator:{
    	enabled: true
    },

   xAxis: [{labels: {
   	format: '{value: %d}'
    
   },
   tickInterval: 1000 * 60 * 60 * 24
   },{labels: {
   	format: '{value: %b %Y}'
    
   	},
    tickInterval: 1000 * 60 * 60 * 24 * 7
   }],
    
    rangeSelector: {
    enabled: true,
    selected: 0,
    buttons: [{
    type: 'week',
    count: 1,
    text: '1w'
}, {
    type: 'month',
    count: 1,
    text: '1m'
}, {
    type: 'month',
    count: 3,
    text: '3m'
}, {
    type: 'month',
    count: 6,
    text: '6m'
}, {
    type: 'ytd',
    text: 'YTD'
}, {
    type: 'year',
    count: 1,
    text: '1y'
}, {
    type: 'all',
    text: 'All'
}]
    },

    yAxis: {
        type: 'category',
        categories: ['A', 'B', 'C'],
        min: 0,
        max: 2
    },

    series: [{
        name: 'Project 1',
        dragDrop: {
            
            draggableX: true
           
        },
        data: [{
            start: Date.UTC(2014, 1, 1),
            end: Date.UTC(2014, 11, 2),
            completed: 0.95,
            groupId: 'group1',
            y: 0
        }, {
            start: Date.UTC(2014, 11, 3),
            end: Date.UTC(2014, 11, 5),
            groupId: 'group1',
            y: 0
        }, {
            start: Date.UTC(2014, 11, 2),
            end: Date.UTC(2014, 11, 5),
            y: 1
        }]
    }]
});
`
Please run above code.
When removed navigator, rangeSelectors and xAxis (keep only minPadding, maxPadding on xAxis), dragging behavior becomes smooth. Can we have same smooth dragging behaviour keeping navigator, rangeSelectors and xAxis label format with tickIntervals?

**Comment by PaulDalek** [comment]
Hi @AnanditaP

To arrange the ticks as presented in the third and fourth screenshots, you can get rid of the `tickInterval` option from both axes and instead use the [`units`](https://api.highcharts.com/gantt/xAxis.units) array.

**Demo**
https://jsfiddle.net/BlackLabel/0vfyoz96/

**Comment by pawelfus** [comment]
Note:
Issue with drag&drop was moved to a separate ticket: https://github.com/highcharts/highcharts/issues/14285
