### ISSUE TITLE
 503 appears when HTML is displayed

### ISSUE THREAD

**Issue by yappleb** [highcharts/highcharts#14213]
**预期行为**
将全屏结果链接嵌入Axure内联接,预览时正常显示

**实际行为**
部分图表不显示,出现503报错

**产品版本**
高图8.1.2

**受影响的浏览器**
Google Chrome
![QQ图片20200914110712](https://user-images.githubusercontent.com/57162972/93039859-32170080-f67b-11ea-9cef-778afb40c36e.png)

**Comment by PaulDalek** [comment]
Hi @yappleb

Thank you for reporting this behavior. Could you please provide us with a live demo where this issue can be reproduced? Also, please try to report your issues/questions in English next time.

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
