### ISSUE TITLE
Tick label auto rotation doesn't work when step set to 1

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14226]
#### Expected behaviour
Rotate the labels when the `step` declared.

#### Actual behaviour
When the label `step` it set to 1 the auto-rotation doesn't work. 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/2kduLxr1/

#### Product version
Highcharts JS v8.2.0

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
_Internal note:_
After some digging, it turns out that this behaviour is by design.
However, an information about that is missing in the `rotation`, `staggerLines` and `step` API documentation.

**Comment by pawelfus** [comment]
*Internal note:*
We should check if we can use forced `step` from options to calculate auto-rotation.

**Comment by karolkolodziej** [comment]
unstale
