### ISSUE TITLE
No color fill in stacked area chart with broken-axis module. 

### ISSUE THREAD

**Issue by necobaka** [highcharts/highcharts#14236]
#### Expected behaviour
No console errors. Chart filling is ok. 

#### Actual behaviour
 - Console errors (6.2.0 version). In actual version no console errors
 - Color filling is broken in the middle of chart

#### Live demo with steps to reproduce
https://jsfiddle.net/necobaka/0u9cxqrt/6/

#### Product version
Highcharts-6.2.0

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Thank you for reporting the issue @necobaka 

Issue was fixed in v7.1.0: https://jsfiddle.net/BlackLabel/2stjvdfp/

Apparently, in v8.2.0 similar bug was reintroduced: https://jsfiddle.net/BlackLabel/2stjvdfp/1/

*Internal note:*
Bisected to commit ff9880e79b

FYI @Basts
