### ISSUE TITLE
Zero values comes with only three label pie chart?

### ISSUE THREAD

**Issue by aghilanbaskar** [highcharts/highcharts#14235]
#### Expected behaviour
Pie chart not coming with all label name which I have passed to it.

**Don't know it is a bug or something I'm missing in my code.**

#### Actual behaviour
Comes with only three labels
Sometimes it comes with two labels also.

#### Live demo with steps to reproduce
template: https://jsfiddle.net/aghilanbaskar/x78s1fgv/1/

#### Product version
 Highcharts JS v8.2.0 (2020-08-20)

#### Affected browser(s)
(All)

**Comment by pawelfus** [comment]
Thank you for reporting the issue @aghilanbaskar 

This is expected behaviour - we don't render all labels when those will be rendered to far away from a point or if those will overlap. Instead of `dataLabels` you can use legend to display all points in the dataset: https://jsfiddle.net/BlackLabel/ep98Ltr3/

**Comment by aghilanbaskar** [comment]
Thank you for replying @pawelfus 
Is there any option to show a message in pie charts if all the values are zero. with a custom message and custom background colour inside the pie.
dataset: [https://jsfiddle.net/aghilanbaskar/vpzabs6k/8/](url)

I haven't read the documentation for no-data-display.
Can you help me with a custom message display? 
I have changed the background colour but is there a way to make the background colour only for pie chart

**Comment by pawelfus** [comment]
Hi @aghilanbaskar - could you please contact our support? See: https://www.highcharts.com/blog/support/ - we use GH issues as bug reports, not support tickets.

PS: If you set options in just one chart, then only this chart should be changed. See also [`fillColor`](https://api.highcharts.com/highcharts/series.pie.fillColor) option.
