### ISSUE TITLE
No error when series' have duplicate ids

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#14241]
#### Expected behaviour
Throw error if series have duplicate ids. 

#### Actual behaviour
No error is thrown. `chart.get()` simply returns the series with lowest index.

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/pgrsd408/)

#### Product version
Highcharts JS v8.2.0 (2020-08-20)

#### Affected browser(s)
Chrome

**Comment by PaulDalek** [comment]
Hi @govinda18 

Thank you for reporting this. I don’t think it’s an issue, as it depends on the user to provide unique ids for series, points or axes. The `get` function first looks for axes then for series and lastly for points.

**Demo**
https://jsfiddle.net/BlackLabel/jtfsvL2q/
