### ISSUE TITLE
Pie, ignoreHiddenPoint set to false - point doesn't show up when clicking legendItem

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#14246]
In pie, when `series.ignoreHiddenPoint` is set to `false`, clicking twice on the same legendItem doesn't show the point again.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/f1zjL86t

#### Product version
8.2.0
Works fine in 7.1.2, but it's broken since 7.1.3

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/f1zjL86t/2/

*Internal note:*
Bisected to commit 7f2e4012ca
In `pie` series, we hide the slice via translation, but we don't show it the same way (we use `inherit`/`visible`) - in the demo, the only change is in line 28 (`true` -> `vis`).

**Comment by sfranke** [comment]
Thank you, this workaround works beautifully!
