### ISSUE TITLE
Tooltip in waterfall series with multiple axes shows up in the wrong place

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14244]
#### Expected behaviour
Show tooltip above columns

#### Actual behaviour
When `waterfall` series are assigned to a different axis, the tooltip shows up in the wrong place.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/3ux2tk5h/

#### Product version
Highcharts JS v8.2.0 (2020-08-20)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
*Internal note:*
The same happens in column: http://jsfiddle.net/BlackLabel/3ux2tk5h/1/
