### ISSUE TITLE
Chord chart does not show the problem

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#14256]
#### Expected behaviour
Let me show you the graph

#### Actual behaviour
The chart doesn't show

#### Live demo with steps to reproduce
https://jshare.com.cn/temp/SOG8bA  
When the height gets smaller the graph doesn't show up, when it gets bigger it shows up, the expectations can be shown up

**Comment by PaulDalek** [comment]
Hi @weixingcai

Thank you for reporting this issue. The reason why your chart doesn’t show up is the [`minLinkWidth`](https://api.highcharts.com/highcharts/series.dependencywheel.minLinkWidth) property, which by default is set to 0. Changing it to 1 will display the chart.

**Demo**
https://jsfiddle.net/BlackLabel/z1uxfcr7/

**Comment by weixingcai** [comment]
thanks
