### ISSUE TITLE
YAxis.linkedTo shows tick labels only on one yAxis in case master yAxis is second one

### ISSUE THREAD

**Issue by thejensi1** [highcharts/highcharts#14253]
When using multiple yAxis in combination with linkedTo property and the master yAxis is not the first one the tick labels disappear. When the master yAxis is the first one the tick labels appear like in the given example (https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/yaxis/linkedto/) from the API (https://api.highcharts.com/highcharts/yAxis.linkedTo)

#### Expected behaviour

Tick labels should appear even if the master yAxis is the second one.

#### Actual behaviour

Tick labels are not shown.

#### Live demo with steps to reproduce
I modified the jsFiddle from above to apply the series data to the second yAxis (yAxis: 1) and link the first yAxis in the axis array to the second one (linkedTo: 1). I would expect the same result as without my changes but the labels of the first yAxis are not drawn anymore: https://jsfiddle.net/thejensi1/dby95jwt/1/

**Comment by PaulDalek** [comment]
Hi @thejensi1

Thank you for reporting this issue. If an `axis` is linked to some other parent `axis`, then at some point in the code (in the `setTickInterval` function to be more precise) the `min` and `max` of the parent are also assigned to the `axis` that is linked. These are later used to find a correct `tickInterval` and therefore distribute `ticks`. If you link the first `axis` to the second one, the `min` and `max` properties on the parent `axis` will be `undefined` as they weren’t calculated yet. An `axis` should be linked to the one of the previous `axis` in order for linking to work correctly.
