### ISSUE TITLE
Highstock plotBands acrossPanes flag has no effect

### ISSUE THREAD

**Issue by gbenthomas** [highcharts/highcharts#14254]
#### Expected behaviour
Setting `acrossPanes` to false for plotBands in Highstock should only render plot band in single pane.

#### Actual behaviour
Setting `acrossPanes` to false for plotBands in Highstock has no effect. (Possibly related to fix  for #6644 )

#### Live demo with steps to reproduce
https://jsfiddle.net/xkuc5dvt/ (Notice plot band spans all panes)

#### Product version
Highstock 8.2.0

#### Affected browser(s)
Chrome

**Comment by PaulDalek** [comment]
Hi @gbenthomas

Thank you for reporting this issue. It seems that the `acrossPanes` is not used correctly in the `getPlotBandPath`, the function responsible for creating a plot band path array. Below is a demo where the `acrossPanes` is used correctly.

**Demo**
https://jsfiddle.net/BlackLabel/2kmsj9wx/

_Internal note_
The `getPlotBandPath` function definition doesn’t provide the `options` as a third argument, while it gets it when called. Right now the `acrossPanes` option is taken from the `this.options` where `this` refers to `axis`.
