### ISSUE TITLE
TypeError: Cannot read property 'options' of undefined and 'find' of null

### ISSUE THREAD

**Issue by itsvamshiks** [highcharts/highcharts#14269]
#### Expected behaviour
Generating **Column, Line and Scatter plots** using Highcharts

#### Actual behaviour
Works **fine** when there are **less number data points**(for example: 500). The **error** is thrown when there are a **large number of data points** (for example: 150,000)

#### Live demo with steps to reproduce
Sorry, could not generate the demo as its part of a huge app, and involves sensitive org data.

#### Product version
**"highcharts": "8.1.0"**

#### Affected browser(s)
Tested in just Chrome

Hello, I have been using Highcharts version 8.1.0 in my **Angular 8 app** to generate Line, Column and Scatter plots. When there are less number of data points, the plots are generated without any issue. When I try to generate the plots with large number of data points (like 150000 data points), I get the following **error in the browser console**

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'options' of undefined
TypeError: Cannot read property 'options' of undefined
    at n.generatePoints (highstock.js:376)
    at n.e.generatePoints (highstock.js:615)
    at n.b (boost.js:125)
    at n.b.<computed> [as generatePoints] (highstock.js:21)
    at n.translate (highstock.js:378)
    at n.b (boost.js:125)
    at n.b.<computed> [as translate] (highstock.js:21)
    at n.redraw (highstock.js:399)
    at highstock.js:303
    at Array.forEach (<anonymous>)
    at resolvePromise (zone-evergreen.js:797)
    at zone-evergreen.js:707
    at fulfilled (tslib.es6.js:71)
    at ZoneDelegate.invoke (zone-evergreen.js:359)
    at Object.onInvoke (core.js:39699)
    at ZoneDelegate.invoke (zone-evergreen.js:358)
    at Zone.run (zone-evergreen.js:124)
    at zone-evergreen.js:855
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)

ERROR TypeError: Cannot read property 'find' of null
    at k.find (highstock.js:27)
    at highstock.js:249
    at Array.forEach (<anonymous>)
    at l.getHoverData (highstock.js:249)
    at l.runPointActions (highstock.js:261)
    at l.onContainerMouseMove (highstock.js:254)
    at HTMLDivElement.wrapFn (zone-evergreen.js:1191)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)

ERROR TypeError: Cannot read property 'options' of undefined
    at n.generatePoints (highstock.js:376)
    at n.e.generatePoints (highstock.js:615)
    at n.b (boost.js:125)
    at n.b.<computed> [as generatePoints] (highstock.js:21)
    at n.translate (highstock.js:378)
    at n.b (boost.js:125)
    at n.b.<computed> [as translate] (highstock.js:21)
    at n.redraw (highstock.js:399)
    at highstock.js:303
    at Array.forEach (<anonymous>)


```

This is my import statement : 

`import * as Highcharts from 'highcharts/highstock';`

Could you please help. Thanks

**Comment by pawelfus** [comment]
Hi @itsvamshiks 

Thank you for reporting the issue.

It seems you use boost module too? Could you double check your imports? Could you also test v8.2.0 to make sure it's not already fixed?

If you have sensitive data, please use some random dataset in the demo.

Thanks!

**Comment by itsvamshiks** [comment]
Hello @pawelfus ,

Thanks for getting back to me. Yes, we are using the boost module too. Sorry to have forgotten it earlier. So I have tried using the v8.2.0, and the issue still exists. We have found what might be causing the issue. So, the following is the chart config we use in our app:

```
 plotOptions: {
  series: {
    turboThreshold: 0,
    animation: {
      duration: 0
    },
    connectNulls: true,
    dataGrouping:{
      dateTimeLabelFormats: dateTimeLabelFormats
    }
  },
  pie: {
    colorByPoint: true,
    allowPointSelect: true,
    cursor: 'pointer',
    dataLabels: {
      enabled: true,
      format: '<b>{point.name}</b>: {point.y}'
    },
    tooltip: {
      pointFormat: '{point.name}: <b>{point.y}</b><br/>'
    }
  },
  line: {
    **boostThreshold: 5000,**
    marker: {
      radius: 1,
      enabled: true,
      lineWidth: 2,
      lineColor: null,
      symbol: 'circle'
    }
   },
  scatter:{
    marker: {
      symbol: 'circle'
    }
  }
},
boost:{
  enabled: true,
}
```

We use this config, and the addSeries() function to plot the charts. So the case where these errors occur, there are more than 10 series in one chart. Some series might have just 100 datapoints while some have around 150,000. So the default boostThreshold we use is 5000. So, if we set the boostThreshold value to 1, we don't see this error. But we are using the highcharts tooltip, which is being faulty when the boostThreshold is set to 1. Our chart has millisecond values in x-axis, and when the boostThreshold value is 1, the tooltip always shows a time range in minute format, not the actual time point, when we zoom into a small area in the plotted chart. So thats stopping us from setting the boost Threshold value to 1. Is there a workaround for this?

![image](https://user-images.githubusercontent.com/32715221/94321280-24a42500-ff5d-11ea-90de-f17020ba2fe0.png)
Highcharts tooltip

**Comment by pawelfus** [comment]
Thank you for the details @itsvamshiks 
It's really hard to say what's happening without something I can debug.

Are you sure you are using Highcharts? Not Highcharts Stock (Highstock)? From the config you posted I see you set `dataGrouping`, which should be disabled when using boost module (those are two separate tools to handle big datasets). That  option: [`dataGrouping.dateTimeLabelFormats`](https://api.highcharts.com/highstock/series.line.dataGrouping.dateTimeLabelFormats) suggests you most likely use some specific groupings and format tooltip according to `dateTimeLabelFormats` variable.

**Comment by itsvamshiks** [comment]
Hey @pawelfus . Yes, we are using Highstock. So I disabled the dataGrouping in the config, and the error wont show up, and the tooltip works fine. But, setting the boostThreshold to 1 is causing an issue with Column chart with big datasets. The columns in the chart look zig-zagged and imperfect. Also, There is this problem with zooming into the chart. No matter how much I try to zoom in, the columns still wont expand, but are seen as thin lines. There is no issue with the line and scatter charts, but only with column charts. Below is how the column chart looks like. The first image is the default zoom level. The second image is when I zoomed into the chart.

![image](https://user-images.githubusercontent.com/32715221/94716222-888f6a80-031c-11eb-8866-2d918c669c32.png)

![image](https://user-images.githubusercontent.com/32715221/94716557-05224900-031d-11eb-8c73-e02f26347bc9.png)

**Comment by pawelfus** [comment]
Hi @itsvamshiks 

Thank you for the details. Zig-zagged columns sounds like another bug, can you recreate this and report as a separate issue? Thanks!

Regarding thin column lines: That is expected behaviour, see our docs: https://www.highcharts.com/docs/advanced-chart-features/boost-module#caveats
