### ISSUE TITLE
Error in console while setting responsive options for xAxis

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#14266]
#### Expected behaviour
No errors in the console, the ability to correctly set responsive options.

#### Actual behaviour
Unable to set options correctly:
`TypeError: Cannot read property 'forEach' of undefined`

Related with: https://github.com/highcharts/highcharts/issues/14247

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/g9jr75vb/

#### Product version
Highcharts Basic v8.2.0

#### Affected browser(s)
Android 10
Google Chrome V85.0.4183.102

**Comment by khlieng** [comment]
Fixed on master (#14414).
