### ISSUE TITLE
Y max is not same post drilling it down to another chart and coming back.

### ISSUE THREAD

**Issue by chauhansumit12** [highcharts/highcharts#14276]
#### Expected behaviour
Y max should remain same after user returns from a drilled down chart.

#### Actual behaviour
Y max is increasing after user return from a drilled down charts.

#### Live demo with steps to reproduce

https://jsfiddle.net/yfc384dk/

Steps 
1.Open above jsffiddle .
2.yMax seen is 75 i.e last tick on y Axis.
3.Click on chrome.
4.Click on back to browser.
 
Issue:Y axis last tick is 80 although nothing has changed.

#### Affected browser(s)
All

**Comment by PaulDalek** [comment]
Hi @chauhansumit12

Thank you for reporting this issue. This behavior it’s not a bug. Here’s explanation why (a comment from a similar issue): https://github.com/highcharts/highcharts/issues/14216#issuecomment-692621029. Additionally, the [`alignTicks`](https://api.highcharts.com/highcharts/chart.alignTicks) property affects it as well.
