### ISSUE TITLE
Scrollbar interaction

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1427]
If you click on the Update Data button, you see that nothing changes. That button adds an additional 30 points to the data set (it does so by replacing the existing data via setData). My expectation is that the scrollbar would adjust to reflect that there are now 30 more data points. If you click on the 1h button you'll see it positions the scrollbar correctly. And, if you then click on 5m button the scrollbar is positioned correctly.

http://jsfiddle.net/jSq3v/2/

**Comment by pawelfus** [comment]
Works fine with 4.2.5: http://jsfiddle.net/oa3rztvL/
