### ISSUE TITLE
Highcharts .NET changed some attributes to hashtables

### ISSUE THREAD

**Issue by PadWorks** [highcharts/highcharts#14275]
#### Expected behaviour
Highcharts .NET v8.1.2.4 should work with the same types than v81.1.1

#### Actual behaviour
After updating Highcharts v8.1.1.1 to v8.1.2.4 some object-types changed to Hashtable e.g.
- Highcharts.PlotOptions.Series.States.Inactive.Opacity changed from number to Hashtable
Unfortunately I can't found the changelog for this change or the documentation how the hashtable should looks like.

#### Product version
Highcharts .NET v8.1.2.4
Highcharts 8.2.0

**Comment by PaulDalek** [comment]
Hi @PadWorks

Thank you for reporting this issue. I’ve notified our .NET developer about this.

**Comment by PadWorks** [comment]
Thank you @pauld91 

Are there any news according to the still existing problem?

**Comment by pawelfus** [comment]
Confirmed, it's a bug - no ETA yet for this issue.

**Comment by PadWorks** [comment]
It would be really nice if .NET Development could fix the bugs a little faster, or at least if a timeline was known. It looks like other .NET serialization-hashtable bugs have been added?

https://github.com/highcharts/highcharts/issues/14376

**Comment by brofixo** [comment]
@PadWorks , all Style objects are defined as Hashtable to give any user a possibility to define styles in more flexible way. 
Opacity will be fixed in next realease which will happen during current week.

**Comment by ksherman** [comment]
@brofixo This is still very much an issue, several of the "Styles" properties were changed to Hastables when they should not have been. 

https://stackoverflow.com/questions/68304026/highcharts-net-latest-yaxis-gridlinedashstyle-hashtable-doesnt-work-with-cli

**Comment by brofixo** [comment]
Release with this fix should be released current week.

Daniel Drwięga
Brofixo

pt., 23 lip 2021, 16:43 użytkownik Kevin Sherman ***@***.***>
napisał:

**Comment by ksherman** [comment]
that's great to hear! 🎉 🎉
