### ISSUE TITLE
Issue with Detailed map, US counties in highcharts 

### ISSUE THREAD

**Issue by mahendrathakur18180** [highcharts/highcharts#14274]
![AdvancedMapIssue](https://user-images.githubusercontent.com/72020621/94429141-7d6afc00-01af-11eb-8375-51bdfcbeba4b.png)

We are trying to configure the Detailed map, US counties in our system, we are seeing a white block in the middle of the map. We verified the same in the highcharts, the white block is present in highcharts as well. The details of the white block as mentioned below.

Code: us-sd-102
name: Oglala lakota county, SD
value: 10.9

Could you please help us understand the same. Thanks

**Comment by chris-vecchio** [comment]
FYI to Highcharts devs in case it's helpful:
On May 1, 2015, the Census Bureau changed Shannon County, South Dakota (FIPS: 46113) to Oglala Lakota County, South Dakota (FIPS: 46102).

Not sure which file OP is using but I don't see us-sd-102 in [us-all-all.js](https://code.highcharts.com/mapdata/countries/us/us-all-all.js)

[Census Bureau County Change Reference](https://www.census.gov/programs-surveys/geography/technical-documentation/county-changes.2010.html)

**Comment by PaulDalek** [comment]
Hi @mahendrathakur18180, @chris-vecchio 

Thank you for reporting this issue. It seems that some points might have incorrect codes or are missing from the JSON with the data for counties.

**Comment by KacperMadej** [comment]
This is a map collection issue and belongs on the map collection repo. This is an already reported problem - https://github.com/highcharts/map-collection-dist/issues/23
Closing as a duplicate.
