### ISSUE TITLE
Mobile: Overlapping of data labels 

### ISSUE THREAD

**Issue by skarthikeyan96** [highcharts/highcharts#14281]
Problem is data labels are overlapping when the charts adjust to the mobile view

#### Expected behaviour

Data label should not overlap inside the bar when re-sized to the mobile view

#### Actual behaviour

Data label is overlapping inside the bar when re-sized to the mobile view

Screenshot: 

![image](https://user-images.githubusercontent.com/23126394/94648780-dd2ce880-0310-11eb-8ba3-cb21b9d71a38.png)

#### Product version

Version 7.2.1

**Comment by pawelfus** [comment]
Hi @skarthikeyan96 

Thanks for reporting the issue. Could you also provide live demo of the issue? We will check this, thanks!

**Comment by skarthikeyan96** [comment]
Sure will update the codepen link

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
