### ISSUE TITLE
chart.update to allow updatePoints be false for setting the series data

### ISSUE THREAD

**Issue by artu-ole** [highcharts/highcharts#14287]
#### Expected behaviour
Would like to be able to call chart.update forcing [`updatePoints`](https://api.highcharts.com/class-reference/Highcharts.Series#setData) set to false, otherwise series point order gets mangled up for line and spline charts.
There are some workarounds I know of such as updating to empty series first which is illogical or calling series.setData directly which is not convenient if number of series changes on updates. 
One can also provide original series with gaps filled with null values and set connectNulls to true which is okay, but the logical "out-of-the-box" way or updatePoints sorting them correctly for line chart would be ideal.
I would be glad to hear other reasonable workarounds I've missed.

#### Actual behaviour
Series points are updated instead of redrawn which results in out of order line chart
![image](https://user-images.githubusercontent.com/15938416/94822617-835d1900-040b-11eb-9947-fe3f96cc1779.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/artuole/zw0xv6tg/3/

#### Product version
Highcharts v8.2.0

**Comment by pawelfus** [comment]
Hi @artu-ole 

Thank you for reporting this bug. If this is your dataset, then you don't need to set `xAxis.type = "category"`: https://jsfiddle.net/BlackLabel/Lnta87k3/ (`xAxis.categories` is enough).

**Comment by artu-ole** [comment]
@pawelfus Thank you! Your solution works for production dataset as well.
