### ISSUE TITLE
Update ColorAxis visible property issues

### ISSUE THREAD

**Issue by rbaudrillard** [highcharts/highcharts#14283]
#### Actual behaviour

Issue 1:
If we start with visible color axis on init, if we update it to hide, ticks and labels hide but not the color bar.

Issue 2:
If we start with not visible color axis on init, if we update it to show, it doesn't

#### Expected behaviour

Color axis should update correctly

#### Live demo with steps to reproduce

http://jsfiddle.net/t3mugL0x/3/

Issue 1 :  Visible on init > Update visible
Issue 2:  Not visible on init > Update visible

#### Product version

Highcharts 8.2.0
https://www.npmjs.com/package/highcharts/v/8.2.0

#### Affected browser(s)

All

**Comment by pawelfus** [comment]
Thank you for reporting this issue @rbaudrillard 

FYI @ppotaczek

**Comment by ppotaczek** [comment]
To workaround add this plugin:


	(function(H) {
		H.ColorAxis.prototype.destroy = function() {
			this.chart.isDirtyLegend = true;

			this.destroyItems();
			H.Axis.prototype.destroy.call(this);
		};
	}(Highcharts));


**Live demo:** http://jsfiddle.net/BlackLabel/51hjL4w2/
