### ISSUE TITLE
Infinite loop in histogram caused by series values

### ISSUE THREAD

**Issue by weltall** [highcharts/highcharts#14289]
When using highchart to render histogram with certain values it ends up in an infinite loop in histogram-bellcurve.js inside the function derived data on this loop 

```
// If binWidth is 0 then max and min are equaled,
                // increment the x with some positive value to quit the loop
                for (x = min; 
                // This condition is needed because of the margin of error while
                // operating on decimal numbers. Without that, additional bin
                // was sometimes noticeable on the graph, because of too small
                // precision of float correction.
                x < max &&
                    (series.userOptions.binWidth ||
                        correctFloat(max - x) >= binWidth ||
...
```

The cause seems to be the value of x never varies with certain values (almost surely because of precision issues)

#### Expected behaviour
That the chart would display.

#### Actual behaviour
Highchart ends in an infinite loop till the browser asks to stop the script or to wait more, as it's an infinite loop the only way out is stopping the script

#### Live demo with steps to reproduce
Just run this
https://jsfiddle.net/ytLhqa8j/1/

By removing a last digit in the value the loop is not happening anymore: https://jsfiddle.net/ytLhqa8j/

```
        "data": [{
            "y": 0.508304338907063,
        }
```

to 
```

        "data": [{
            "y": 0.50830433890706,
        }
```

#### Product version
Highcharts JS v8.2.0 (2020-08-20)

#### Affected browser(s)
Firefox Chrome last versions

**Comment by PaulDalek** [comment]
Hi @weltall

Thank you for reporting this issue. Yes, this behavior comes from the precision (the default value of the `prec` in the `correctFloat` function is 14). As a workaround you can modify the `derivedData` function to pass a higher precision factor (within the range specified in the [`toPrecision`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Number/toPrecision)).

**Demo**
https://jsfiddle.net/BlackLabel/f8k2y59n/
