### ISSUE TITLE
Browser hangs while loading and downloading of highchart with large dataset

### ISSUE THREAD

**Issue by NikitaJain750** [highcharts/highcharts#14288]
Whenever I am trying to load highchart with large dataset it takes too much time to load on browser. And if it is loaded successfully and I am trying to download png, jpg or any other type of download then browser hangs. It gives a pop-up saying wait or kill the page.
Example - Let say I want to load heatmap of 50X50 matrix usinh large heatmap from highcharts. This data is part of one series, so it should be loaded at once. As soon as it is loaded, browser becomes slow and starts consuming almost all memory. After this if I click on download file option then it will be hanged completely.

#### Product version
Highcharts Version - 8.0.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @NikitaJain750 

Thank you for reporting the issue. Did you contact our support first? See: https://www.highcharts.com/blog/support/

There are many ways to improve performance in Highcharts, see our docs: https://www.highcharts.com/docs/getting-started/frequently-asked-questions#how-can-i-get-the-best-performance-out-of-highcharts - in your case I would definitely use Boost module.

If that does not help, are there any changes to recreate issue in jsFiddle? Can be random data. This is good starting point: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/boost/heatmap/ - thanks!

**Comment by NikitaJain750** [comment]
Hi,

I have tried implementing boost module for the charts but the issue
remain the same.

My heatmap is loaded on the screen successfully but as soon as I click on
export module my browser completely hangs. Can you please let me know the
reason for this?

Thanks in advance

Regards
Nikita Jain

**Comment by pawelfus** [comment]
Hi @NikitaJain750 

Without live demo of the issue I can only guess. Please, provide live demo so we cen check this. Thanks!
