### ISSUE TITLE
y-axis scaled differently after addSeries() than after setData() with exactly same data

### ISSUE THREAD

**Issue by michahagg** [highcharts/highcharts#14297]
#### Expected behaviour
When I add a series to a chart with redraw=true, then the y-axis is scaled and the graph is drawn. When I replace the data on that series with exactly the same data using setData() with redraw=true, then I would expect to see exactly the same scaled y-axis and exactly the same graph drawn.

#### Actual behaviour
When I replace the data on that series with exactly the same data using setData() with redraw=true, then I see that the y-axis is scaled differently and the graph is drawn differently accordingly.

This could be related to issue https://github.com/highcharts/highcharts/issues/13485. That would mean that the y-axis is scaled neatly the first time and too large the second time.

#### Live demo with steps to reproduce
https://jsfiddle.net/miicha/b0ow127z/1/

#### Product version
Highcharts 8.2.0

#### Affected browser(s)
Chrome 85.0.4183.121

**Comment by PaulDalek** [comment]
Hi @michahagg

Thank you for reporting this issue. [Here](https://github.com/highcharts/highcharts/issues/14216#issuecomment-692621029) is the explanation why this behavior isn’t considered as a bug. You can try to use options such as `tickInterval` or `tickPositioner` to maintain a similar ticks distribution.

**Demo**
https://jsfiddle.net/BlackLabel/1fq2ng0v/

**Comment by michahagg** [comment]
Thank you for the clear answer!! I'll go and play with those options!! :-D
