### ISSUE TITLE
Fill opacity doesn't override opacity when color is given by #rrggbbaa

### ISSUE THREAD

**Issue by Blewin** [highcharts/highcharts#14290]
#### Expected behaviour
When color is given in format of `#rrggbbaa`, the given opacity should be overriden by default value of 0.75 fillOpacity when unspecified, or specified opacity

#### Actual behaviour
It does not get overridden

#### Live demo with steps to reproduce
https://jsfiddle.net/6m0ohnw3/

#### Product version
highcharts 8.1.0
#### Affected browser(s)
newest chrome

This bug doesn't affect me anymore, but in my setup it caused a  difference between production and development  envs which was hard to debug, so it could help others.

**Comment by pawelfus** [comment]
Hi @Blewin 

Thanks for reporting the issue. We support  only`#rrggbb`, `rgba(r,g,b,a)` and `rgb(r,g,b)` formats for colors: https://api.highcharts.com/class-reference/Highcharts#.ColorString - `#rrggbbaa` is not supported.
