### ISSUE TITLE
Venn Diagram Circles Alignment Inconsistent for 4 circles

### ISSUE THREAD

**Issue by HafizHussain31** [highcharts/highcharts#14296]
#### Expected behaviour

https://jsfiddle.net/pj675bv8/ 

For the given data in this jsfiddle, venn works as expected (The alignment of circle). 

I understand this works because, we have a sample data with similar values as you can see in the series data.

#### Actual behaviour

https://jsfiddle.net/57cjogr2/

But, When I give actual data which is not similar to each other as given in fiddle above, the circles takes horizontal alingment position which is not what we are expecting. We need an alignment that looks similar as in the expected behavior fiddle.  

#### Live demo with steps to reproduce
Bug Fiddle : https://jsfiddle.net/57cjogr2/

Sample Data Fiddle : https://jsfiddle.net/pj675bv8/

**Comment by pawelfus** [comment]
Hi @HafizHussain31 

I think the data is incorrect? In your dataset you have Action&Comedy&Horror but there is no Action&Comedy, see added missing points: https://jsfiddle.net/BlackLabel/0gny7zbx/

Still, layout can change when values change, for example: https://jsfiddle.net/BlackLabel/5grpzsaf/

Note that non-circular shapes are not supported: #10503

**Comment by HafizHussain31** [comment]
Hi @pawelfus 

Yes, you are right, I was using the data with missing values. Adding the missing data with proper values did the trick. 

Thanks for the insight.
