### ISSUE TITLE
Check cancelable on touch events before calling preventDefault

### ISSUE THREAD

**Issue by xPaw** [highcharts/highcharts#14298]
I enabled reporting api (`Report-To`) on my website, and get an intervention report from Chrome browsers with the following message:

```json
{
  "columnNumber": 169,
  "id": "IgnoredEventCancel",
  "lineNumber": 63,
  "message": "Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.",
  "sourceFile": "highstock.js?v=32550416a08fb3d3"
}
```

Looking at the minified file, I believe it is being caused by this:
https://github.com/highcharts/highcharts/blob/aaa230381d4423928080c00b7187dd78d01b459c/ts/Core/Renderer/SVG/SVGElement.ts#L2123

I think the fix is to check if `e.cancelable` is true before calling it.

#### Product version

Highstock v8.2.0

#### Affected browser(s)
Chrome 85 on Android (or touch devices)

**Comment by pawelfus** [comment]
Thanks for reporting the issue! @xPaw
