### ISSUE TITLE
Navigator - IE8

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1429]
Navigator serie appeard partly.

Reproduce steps:
1. Open IE8 but not in full screen and go to highcharts.com highstock demos.
http://diamondsrw.nazwa.pl/seba/screenshots//IE8_%5BRunning%5D-20130102-114215.jpg
2. Resize window horizontally
http://diamondsrw.nazwa.pl/seba/screenshots//IE8_%5BRunning%5D-20130102-114319.jpg
3. Navigator serie is cutted.

**Comment by KacperMadej** [comment]
Unable (99% sure, images are missing, so hard to be 100% sure) to recreate using version 6.1.4.
Closing as resolved.
