### ISSUE TITLE
Crosshairs are hidden behind filled area

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#143]
Demo: http://jsfiddle.net/highcharts/ftmcC/

Crosshairs should appear above the area, but ideally below the points.

**Comment by oysteinmoseng** [comment]
Still an issue with current code: http://jsfiddle.net/ftmcC/6/
Not really noticable with default crosshair color, though: http://jsfiddle.net/ftmcC/7/

**Comment by KacperMadej** [comment]
This is basically an edge case of #8935 and since the other issue has a suggested workaround I'm closing this issue as a duplicate.
