### ISSUE TITLE
Mutated options after chart update

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#14305]
#### Expected behaviour
It should work as in version 7.1.1: http://jsfiddle.net/BlackLabel/pxnsa03r/

#### Actual behaviour
Properties in a configuration object are overwritten, for example:

Before update: 
`options1:  {...,"title":{"text":"random1"}} options2:  {"title":{"text":"random2"}}`

After update:
`options1:  {...,"title":{"text":"random2"}} options2:  {"title":{"text":"random2"}}`

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/h9b5mt6w/

#### Product version
Highcharts v8.2

#### Affected browser(s)
All

**Comment by PaulDalek** [comment]
_Internal note_
Bisected to commit
https://github.com/highcharts/highcharts/commit/fd7c92f1b1993700ace95228b9783e1662e9bb3c

The original chart options are mutated by the `merge` call from the `update` function.

**Workaround**
Adding an event on `update` that copies the `userOptions` object.

**Demo**
http://jsfiddle.net/BlackLabel/sdmLkxha/
