### ISSUE TITLE
Areaspline series with normal stacking disappear on update

### ISSUE THREAD

**Issue by Dron007** [highcharts/highcharts#14304]
#### Expected behaviour
Areaspline series should be rendered on update.

#### Actual behaviour
Areaspline series disappear on update, just points are rendered. Toggling series off and on again makes it visible.

#### Live demo with steps to reproduce
Open: https://codesandbox.io/s/highcharts-react-simple-chart-forked-ttlci
Press "Update Series" button. => No areaspline series.

#### Product version
Highcharts >= 8.1.1. 
It worked fine in v8.1.0: https://codesandbox.io/s/highcharts-react-simple-chart-forked-k20qx

I noticed that problem disappears after removing any of these lines:
`"spacing": [14, 32, 20, 32]`
` "stacking": "normal"`

**Comment by PaulDalek** [comment]
Hi @Dron007 

Thank you for reporting this issue.

**Comment by PaulDalek** [comment]
_Internal note_
Bisected to commit https://github.com/highcharts/highcharts/commit/57ce06ee444abb7b9c5e962c68dc6f5f831b64ae

FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Duplicate of #14130
