### ISSUE TITLE
plotBand added with addPlotBand on not visible xAxis doesn't respond to chart zooming

### ISSUE THREAD

**Issue by smokir** [highcharts/highcharts#14310]
#### Expected behaviour

1. Prevent adding plotBand by using `addPlotBand` on `xAxis` with `visible: false`. If you add plotBand directly in `xAxis` section with `visible: false` then plotBand won't be shown.
2. (preferable) Respond to zoom correctly

#### Actual behaviour

`plotBand` added with `addPlotBand` on not visible `xAxis` doesn't respond to chart zooming:

![Oct-07-2020 15-28-13](https://user-images.githubusercontent.com/2204174/95330969-fa822980-08b1-11eb-81c6-f387b0bb0c9c.gif)

When `xAxis` is visible:

![Oct-07-2020 15-29-12](https://user-images.githubusercontent.com/2204174/95330929-ea6a4a00-08b1-11eb-9d0a-82f9b053a21c.gif)

#### Live demo with steps to reproduce

https://jsfiddle.net/smokir/qx0tnf87/

#### Product version

Highcharts

#### Affected browser(s)

Chrome 85.0.4183.1697

**Comment by PaulDalek** [comment]
Hi @smokir

Thank you for reporting this issue. When the `visible` is set to `false`, the `axis` isn’t rendered, therefore any potential `plotBands` aren’t rendered too. I think that the visibility factor should also be taken under consideration when it comes to plot bands added dynamically with the `addPlotBand` function.

**Workaround**
Check the axis’ visibility in the `addPlotBandOrLine` function.

**Demo**
https://jsfiddle.net/BlackLabel/oz6th8g9/
