### ISSUE TITLE
PDF download is not working on v7.2.2

### ISSUE THREAD

**Issue by jaquesdias-riskmethods** [highcharts/highcharts#14319]
#### Expected behaviour

Highcharts v7.2.2 should work the same as v6.2.0.

#### Actual behaviour

After upgrading Highcharts from v6.2.0 to v7.2.2 the PDF download is not working anymore. It seems that the`https://code.highcharts.com/7.2.2/lib/jspdf.js` file doesn't exist in this version:

![image](https://user-images.githubusercontent.com/59443679/95440659-7daa8a80-0959-11eb-8141-b9f4ca749df0.png)

#### Product version
Highcharts v7.2.2

**Comment by pawelfus** [comment]
Thank you for reporting this bug @jaquesdias-riskmethods 

**Workaround:**
Use libs from v7.2.1, by setting [`exporting.libURL`](https://api.highcharts.com/highcharts/exporting.libURL): 
```js
{
  exporting: {
    libURL: 'https://code.highcharts.com/7.2.1/lib'
  }
}
```
