### ISSUE TITLE
[Snapshots - Vue] Inconsistent transform definitions

### ISSUE THREAD

**Issue by gomorizsolt** [highcharts/highcharts#14328]
#### Expected behaviour

The transform definitions within the `transform` attribute shall remain intact.

#### Actual behaviour

Occasionally there's a slight difference between the transform values, which makes the snapshot tests fail:

<img width="1439" alt="inconsistent-transform-values-highcharts" src="https://user-images.githubusercontent.com/30864202/95548983-8b6a1980-0a06-11eb-8677-de5168db68bd.png">

Here's the diff if you can't spot it from the screenshot:

```
Snaphot: transform="translate(0,10) scale(1 0.001)"
Received: transform="translate(0,10) scale(1 0.0010024649316718226)"
```

#### Live demo with steps to reproduce

Please note that it's *not* guaranteed that you'll be able to reproduce the issue right away, it's quite arbitrary (i.e. you'll most likely need to rerun the tests even 20-30 times to reproduce the issue).

Steps:
- Clone https://github.com/gomorizsolt/vue-highcharts-snapshot-issue
- `npm install`
- `npm run test`

FWIW, it's also reproducible when the `type` is set to e.g. `bar`. Diff:

```
Snaphot: transform="translate(NaN,NaN) rotate(90) scale(-1,1) scale(1 0.001)"
Received: transform="translate(NaN,NaN) rotate(90) scale(-1,1) scale(1 0.0010024649316718226)"
```

The `NaN` values also got me curious, but that's a different story I guess.

#### Product version

```
"highcharts": "^8.2.0",
"highcharts-vue": "^1.3.5",
```

**Comment by KacperMadej** [comment]
Hi @gomorizsolt 

Thank you for contacting us about the problem.

I am unable to recreate the scale value in a standard demo. Could you elaborate on this and the purpose of your test?
Because the problem is not possible to be recreated consistently then maybe something in the testing environment could be causing this problem?

`scale` is duplicated in your second code sample.

Google found only 1 thing when asked about `0.0010024649316718226` - and it was [a demo in JSFiddle](http://jsfiddle.net/daniel_s/0ra0gmo6/) done by @Denyllon 
Maybe you know something that could help with this issue @Denyllon ? :)

**Comment by gomorizsolt** [comment]
Hi @KacperMadej!

> I am unable to recreate the scale value in a standard demo. 

That's weird. Just to make sure, have you cloned the repository and tried rerunning the `test` script several times?

> then maybe something in the testing environment could be causing this problem?

It's reproducible on my co-worker's environment as well, and it's also affecting our CI/CD workflow.

> Could you elaborate on this and the purpose of your test?

For our internal [Storybook](https://storybook.js.org/) project, we're using the [Storyshots](https://storybook.js.org/docs/react/workflows/snapshot-testing) add-on to generate snapshot artifacts for every story. We noticed that our CI/CD pipeline started to fail when we had implemented stories for the column chart component.

That's enough context I believe. I also doubt it has anything to do in particular with the add-on.

> scale is duplicated in your second code sample.

I doubt that's my fault. I double-checked that those transform definitions were copy-pasted as-is from the terminal (here's also a screenshot of the diff to prove it):

<img width="1435" alt="bar-chart-diff" src="https://user-images.githubusercontent.com/30864202/95710874-e8154080-0c61-11eb-962d-262ab87bab3b.png">

**Comment by Denyllon** [comment]
@KacperMadej Weird thing, but after opening the demo found by Google, there is no any result for searching `0.0010024649316718226` phrase, so it's hard to find guess what can cause the issue. One thing which comes to my mind here that might be doing the snapshot before finished the animation process, but I'm not pretty sure.

@gomorizsolt Could you try to completely disable animation on chart, and series as well?
You can do it by applying below options:
```js
chart: {
 animation: false
},
plotOptions: {
  series: {
    animation: false
  }
}
```

API References:
https://api.highcharts.com/highcharts/chart.animation
https://api.highcharts.com/highcharts/plotOptions.series.animation

**Comment by gomorizsolt** [comment]
Hi @Denyllon!

Turning off the animations altogether seems to eliminate the issue.

> Is there a way to set the delay of running the snapshot? 

I don't think that there's a way to delay the running of snapshots.

The other workaround I could think of for now is to disable the animations exclusively for the tests:

```js
chart: {
 animation: process.env.NODE_ENV !== "test"
}
```

But frankly it's a bit odd. On the other hand, if there's no other suggestion to get around the issue, then I'd say it's fine.

**Comment by Denyllon** [comment]
> I don't think that there's a way to delay the running of snapshots.

Do you use the default Vue testing setup, or something else? Anyway, I think that you just need to use async/await function combined with timeout to run delayed action within the test, for example: 
```js
const delayedTest = async (miliseconds) => {
  const timeout = async () => {
    return await new Promise(resolve => {
      console.log('Start delay...')
      setTimeout(resolve, miliseconds)
    })
  }

  await timeout(miliseconds)
  
  // Put some action here (like test) which should be run after delay
  console.log('Called after ' + miliseconds + 'ms' )
}

delayedTest(2000)
```
And then:
```js
  it('do some async action', async () => {
    const delay = 2000;

    const timeout = async () => {
      return await new Promise(resolve => {
        console.log('Start delay...')
        setTimeout(resolve, miliseconds)
      })
    }
    await timeout(delay);
    // Called after delay
    console.log(`Called after ${delay}ms delay.`)
    expect(1).toBe(1);
  });
```
> But frankly it's a bit odd.
I do not think that could be something wrong, because we're running a vast majority of our package tests with disabled animation (as they're basically asynchronous actions) by default, and using fake timers to sync those actions up. It makes us sure that the problems like this are hardly ever happens while testing.
Well, please try the above solution and let me know about the result :)

**Comment by gomorizsolt** [comment]
> Do you use the default Vue testing setup, or something else?

I guess you mean [vue-test-utils](https://vue-test-utils.vuejs.org/) as the default Vue test setup. Nothing's been tweaked.

> Anyway, I think that you just need to use async/await function combined with timeout to run delayed action within the test

Indeed, it seems a minimal amount of timeout resolves the issue (it should be greater than 1000ms based on my tests). My initial thought was that there should be a "Jest-ish" way out of the box, to either delay the execution of tests or wait for the component to finish the mount phase (with animations).

> I do not think that could be something wrong, because we're running a vast majority of our package tests with disabled animation (as they're basically asynchronous actions) by default, and using fake timers to sync those actions up.

I'm glad to hear that because I'm personally not a huge fan of this approach, although I'll have to coordinate with my team.

Feel free to close the issue. Thanks for your help, I appreciate it.
