### ISSUE TITLE
Unvalidated input for HTTP response causing XSS vulnerability.

### ISSUE THREAD

**Issue by SachinT123** [highcharts/highcharts#14326]
### Security scans indicated that the code snippets involve unvalidated input for HTTP Request and its usage it to display results to the user making it vulnerable to Cross-Site Scripting attack.

```
highcharts/exporting-server/java/highcharts-export/highcharts-export-convert/src/main/resources/phantomjs/highcharts-convert.js -- line 514
highcharts/exporting-server/java/highcharts-export/highcharts-export-convert/target/classes/phantomjs/highcharts-convert.js -- line 514
sites/all/libraries/highcharts/exporting-server/phantomjs/highcharts-convert.js -- line 514
```
```
startServer = function (host, port) {
  var server = require('webserver').create();

  server.listen(host + ':' + port,
    function (request, response) {
      var jsonStr = request.post, //// NO VALIDATION before creating & parsing the JSON string.
        params,
        msg;
      try {
        params = JSON.parse(jsonStr);
        if (params.status) {
          // for server health validation
          response.statusCode = 200;
          response.write('OK');
          response.close();
        }
      // code
      }
    }
```

**Comment by KacperMadej** [comment]
Hi @SachinT123 

Thank you for contacting us about the problem.

Please provide more info about the source of the paths and code. If this is a code for the legacy export server in Java then I suggest using a newer and NodeJS based version of the exporting server: https://github.com/highcharts/node-export-server

**Comment by KacperMadej** [comment]
Closed due to inactivity. In case you have more info (details in the previous comment) please share and the issue could be reopened.
