### ISSUE TITLE
Property 'dataLabels' does not exist on type 'IndividualSeriesOptions'

### ISSUE THREAD

**Issue by pascalfossouo** [highcharts/highcharts#14327]
#### Expected behaviour
Property 'dataLabels' does not exist on type 'IndividualSeriesOptions'.

#### Actual behaviour

The 'dataLabels' property is not in the serie array of IndividualSeriesOptions

#### Product version
 "dependencies": {
    "@agm/core": "1.0.0-beta.0",
    "@angular/animations": "^10.1.4",
    "@angular/cdk": "^10.2.4",
    "@angular/common": "^10.1.4",
    "@angular/compiler": "^10.1.4",
    "@angular/core": "^10.1.4",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "^10.1.4",
    "@angular/http": "^7.2.16",
    "@angular/material": "^10.2.4",
    "@angular/platform-browser": "^10.1.4",
    "@angular/platform-browser-dynamic": "^10.1.4",
    "@angular/router": "^10.1.4",
    "@ngui/map": "^0.30.3",
    "@ngui/utils": "^0.8.1",
    "@swimlane/ngx-charts": "^4.4.0",
    "@swimlane/ngx-datatable": "9.2.0",
    "@types/gapi": "0.0.39",
    "@types/gapi.auth2": "0.0.51",
    "@types/google-maps": "^3.2.2",
    "@types/googlemaps": "^3.39.3",
    "@types/highcharts": "^4.2.54",
    "angular-calendar": "0.15.0",
    "angular-file-saver": "^1.1.3",
    "angular-md5": "^0.1.10",
    "angular-tree-component": "3.6.0",
    "angular-websocket": "^2.0.1",
    "angular2-font-awesome": "^1.1.0",
    "angular2-google-maps": "0.17.0",
    "angular2-highcharts": "^0.5.5",
    "base-64": "^0.1.0",
    "chart.js": "2.5.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^3.6.5",
    "d3": "4.9.1",
    "dragula": "3.7.2",
    "font-awesome": "^4.7.0",
    "google-charts": "^2.0.0",
    "highcharts": "^6.0.5",
    "highcharts-more": "^0.1.7",
    "html2canvas": "^1.0.0-rc.5",
    "intl": "1.2.5",
    "leaflet": "1.0.3",
    "moment": "^2.24.0",
    "ng2-charts": "1.5.0",
    "ng2-dragula": "1.3.1",
    "ng2-file-upload": "1.2.1",
    "ng2-translate": "5.0.0",
    "ng2-validation": "4.2.0",
    "ngrx": "0.0.1-security",
    "ngx-color-picker": "^4.0.3",
    "perfect-scrollbar": "0.7.0",
    "quill": "^1.3.7",
    "rxjs": "^6.6.3",
    "rxjs-compat": "^6.6.3",
    "save": "^2.4.0",
    "screenfull": "^4.2.1",
    "ts-md5": "^1.2.7",
    "tslib": "^1.9.0",
    "utf8": "^3.0.0",
    "zlibjs": "^0.2.0",
    "zone.js": "^0.11.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1001.4",
    "@angular/cli": "^10.1.4",
    "@angular/compiler-cli": "^10.1.4",
    "@angular/language-service": "^10.1.4",
    "@types/jasmine": "^3.5.14",
    "@types/node": "^14.11.5",
    "codelyzer": "^6.0.1",
    "jasmine-core": "^3.6.0",
    "jasmine-spec-reporter": "^6.0.0",
    "karma": "^5.2.3",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "^4.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "^7.0.0",
    "rxjs-tslint": "^0.1.8",
    "ts-node": "~2.0.0",
    "tslint": "^6.1.3",
    "typescript": "^4.0.3",
    "webpack": "^4.44.2"
  }

**Comment by PaulDalek** [comment]
Hi @pascalfossouo

Thank you for reporting this issue. Please provide the demo where you encounter this error. Thanks.

**Comment by pascalfossouo** [comment]
I have this error when I migrate from Angular 4 to 10. I think this is due to the typescript version. because the old version (Angular 4 and  "typescript": "~2.2.0") has this error but I can build and run the application.

**Comment by pawelfus** [comment]
Hi @pascalfossouo 

You are using old version of Highcharts (v6) with unofficial TS definitions (`"@types/highcharts": "^4.2.54",`).

Please upgrade Highcharts and use official definitions: https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-declarations

If you need to use v6, then report this to authors, but it seems package is deprecated and no longer supported: https://www.npmjs.com/package/@types/highcharts
