### ISSUE TITLE
bar, column, line chart xAxis problem in categories mode

### ISSUE THREAD

**Issue by behnam7171** [highcharts/highcharts#14333]
#### Expected behaviour
When I toggle visibility of a 's3' by clicking the 's3' legend, I expect xAxis 'Asia' to be gone, and not seeing index -1 of xAxis.
And also after bringing the 's3' series back, I expected to not see the -1 index.

#### Actual behaviour
when I click the 's3' legend, 'Asia' still is visible and not in a good position and also -1 index in the xAxis. Also when I toggle it back, I still see -1 in the xAxis

#### Live demo with steps to reproduce
https://jsfiddle.net/behnam71/f3uk05aw/1/
I so far tested it in bar, column, and line chart.

#### Product version
Tested In 8.2 and 6.0.4

#### Affected browser(s)
Chrome 85

**Comment by PaulDalek** [comment]
Hi @behnam7171

Thank you for reporting this issue. This is not a bug and the wanted effect can be achieved by setting the [`minRange`](https://api.highcharts.com/highcharts/xAxis.minRange) property with some smaller value (e.g. 0.1).

**Demo**
https://jsfiddle.net/BlackLabel/bLmrptvn/

**Comment by behnam7171** [comment]
Thank you for the tip, that will resolve my issue, But when I toggle a series to hide and again toggle it back to visible, the user does not expect to see -1 because he was not seeing it before toggling.

**Comment by PaulDalek** [comment]
@behnam7171

So you say this behavior is still visible even after setting the `minRange`? Could you please provide me with steps to reproduce it? Thanks.
