### ISSUE TITLE
Y-axis having only one tick with a fixed range (regression)

### ISSUE THREAD

**Issue by ktakahashimtb** [highcharts/highcharts#14337]
#### Expected behaviour
Y-axis has at least two ticks

#### Actual behaviour
Y-axis is showing just one tick

#### Live demo with steps to reproduce

https://jsfiddle.net/ktakahashimtb/wn9sftq6/

This seems to happen when an axis range is specified (min, max), and also `endOnTick` is set to false.
Additionally, the vertical space for the graph is limited due to a 'tall' legend.  With this example, I'm simulating this by setting series name arbitrary long, but in my normal use case, this is happening with a large number of series.

This is a somewhat specific scenario, but was working before Highcharts version 8.1, implying (hopefully) this is not an intended behavior.

https://jsfiddle.net/ktakahashimtb/jetv68pf/

#### Product version

Highcharts and Highstock, version 8.1.0 and up.

#### Affected browser(s)

Chorme, Firefox, Edge
(Not seeing this on Safari)

**Comment by pawelfus** [comment]
Hi @ktakahashimtb 

Thank you for reporting the issue, but I'm unable to recreate the issue, this is how charts are rendered on my side:
- v8.0.4:
![Screen Shot 2020-10-13 at 11 01 24](https://user-images.githubusercontent.com/1453926/95839692-980eaa80-0d43-11eb-9c35-92996be4ad13.png)
- v8.2.0:
![Screen Shot 2020-10-13 at 11 01 54](https://user-images.githubusercontent.com/1453926/95839689-96dd7d80-0d43-11eb-9aac-7694a12f8adc.png)

First chart has two ticks, the second one has three ticks.

Anyway, we are trying to guess the best amount of ticks according to default options (e.g. [`yAxis.tickPixelInterval`](https://api.highcharts.com/highcharts/xAxis.tickPixelInterval)). If you want different behaviour than the default one, you can control this by setting [`yAxis.tickAmount`](https://api.highcharts.com/highcharts/yAxis.tickAmount) option.

**Comment by ktakahashimtb** [comment]
@pawelfus Thank you for the reply!   After doing a bit more testing, it appears that the screen resolution also impacts the outcome.  On my MacBook Pro, I'm seeing the same results as you with both Chrome and Safari.  On my Windows PC (no higher resolution monitor), I'm seeing only one tick with 8.2.0 as I described.  

I'm hoping that I really don't have to specify `yaxis.tickAmount` in my use case because I'm generating graphs from dynamic data on the fly with varying graph sizes so I'd like to let Highcharts' 'smarts' handle as much as possible :), including precise tick locations and intervals.  I understand this is a very specific case, and there probably are several workarounds.  The reason why I did submit this was because it was working fine under prior versions to 8.1.0, thus this may be due to an error introduced at some point.  If this is what we should expect how Highcharts render the graph under these specific cases, that information itself is also very helpful.

Thank you again!!

**Comment by pawelfus** [comment]
Thanks! Indeed, Windows PC shows the issue.

Bisected to commit: 4423e913cd7a255fee11977f98299c5691cb3b7f

The change shouldn't affect low resolution screens without affecting high resolution ones.. Most likely the issue is with us much longer, but changed default logic for `yAxis.allowDecimals=undefined` makes this somehow more obvious. Can you compare these two charts and let me know the results? Demo: https://jsfiddle.net/BlackLabel/3fdwb90c/ (top one is a default setting in v8.1.0+, while bottom one is a default setting in older versions).

Thanks!

**Comment by ktakahashimtb** [comment]
Yes, I see the bottom chart showing two ticks, behaving as if it is running under an older version of Highcharts.   I'll definitely consider applying this workaround for my case.  Thank you!


Related to this issue, there seems like a limit on how short the chart can be while keeping more than 2 ticks displayed.  Once I make the container height less than 390px, neither setting `yAxis.allowDecimals = true` or running an older version helps.
