### ISSUE TITLE
"View data table" export option always toggles the 11th button in the list, regardless of actual position

### ISSUE THREAD

**Issue by les-lim** [highcharts/highcharts#14338]
#### Expected behaviour

When using the export-data.js "View data table" option, that option's button text should toggle between "View data table" and "Hide data table".

#### Actual behaviour

The 11th item in the list is the button text that changes, regardless of the actual position of "View data table".

The code to determine `menuItems` in `Chart.prototype.toggleDataTable` does not look at the user-defined `menuItems` in `this.options`. It always gets the default `menuItems` setting, where `viewData` is at index position 10. If you have fewer than 11 options, it throws an error.

#### Live demo with steps to reproduce
http://jsfiddle.net/79jdfvtb/

#### Product version
Highcharts JS v8.2.0 (2020-08-20)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting the issue @les-lim 

**Workarounds:**

-  A) Set `exporting options using `Highcharts.setOptions()`, demo: http://jsfiddle.net/BlackLabel/1aLw498m/
Snippet:
```js
Highcharts.setOptions({

  exporting: {
    buttons: {
      contextButton: {
        menuItems: ['viewData']
      }
    }
  }
})
```

-  B) Use plugin, demo: http://jsfiddle.net/BlackLabel/1aLw498m/1/
Snippet:
```js
(function(H) {
  H.Chart.prototype.toggleDataTable = function() {
    var exportDivElements = this.exportDivElements,
      menuItems = this.options.exporting.buttons.contextButton.menuItems,
      lang = this.options.lang;

    if (this.isDataTableVisible) {
      this.hideData();
    } else {
      this.viewData();
    }

    // Change the button text based on table visibility.
    if (
      this.options.exporting.menuItemDefinitions &&
      lang.viewData &&
      lang.hideData &&
      menuItems &&
      exportDivElements &&
      exportDivElements.length
    ) {
      exportDivElements[menuItems.indexOf('viewData')]
        .innerHTML = this.isDataTableVisible ? lang.hideData : lang.viewData;
    }
  };
})(Highcharts);
```
