### ISSUE TITLE
load event fires before chart is visible

### ISSUE THREAD

**Issue by mrdemeanour** [highcharts/highcharts#1434]
The chart.load event fires before the chart is visible (the4 axes and gridlines have been drawn, but no points have been plotted). There seems to be no other event that could be used to detect that the chart is ready to be viewed. Reproduced on Chrome and on Firefox.

I am trying to use phantomjs to capture chart images automatically on the server, and it seems that I will have to insert an arbitrary time delay in order to not get an empty set of axes. 

To replicate, select any JSFiddle chart, and add to the createChart() call a load handler function thus:
function() {
  prompt("Loaded");
}
Observe that when the prompt comes up, axes and gridlines are visible, but no chart data has been plotted.

**Comment by curtfehr** [comment]
> Run the prompt at the end of the animation: http://jsfiddle.net/highcharts/8UFFC/2/
This doesn't work most of the time.  If you run this fiddle over and over, you will find that most of the time it's broken, and sometimes you get the event twice.

**Comment by JosePascual** [comment]
Any news related to this issue?

**Comment by raf18seb** [comment]
You can use `series.events.afterAnimate` event: https://api.highcharts.com/highcharts/plotOptions.series.events.afterAnimate
