### ISSUE TITLE
H.dataURLtoBlob - Regex does not accommodate filename=generated.pdf;

### ISSUE THREAD

**Issue by timminss** [highcharts/highcharts#14356]
#### Expected behaviour

When calling 'getSVGForLocalExport' on a chart, 'dataURLtoBlob' is eventually calls and falls over, when the passed in 'dataURL' argument includes the following string: 'filename=generated.pdf;'

I found another user who was having a similar issue, and was glad to find a workaround in the form of a plugin proposed:

https://github.com/highcharts/highcharts/issues/10243#issuecomment-493015314

Unfortunately this workaround is no longer applicable, and @pawelfus asked me to create this bug.

#### Actual behaviour

dataURLtoBlob fails to convert the dataURL to a blob.

**Comment by pawelfus** [comment]
Thank you @timminss

**Comment by timminss** [comment]
No problem @pawelfus . D'you reckon there is any workaround that could be used in the meantime? Thanks again for taking a look!

**Comment by pawelfus** [comment]
I can't suggest any safe workaround. The easiest for now would be download file, modify it, then use it instead of our module.

**Comment by timminss** [comment]
No worries. I will instead downgrade to 8.1.2, use the 'wrap' workaround, and watch this space :) Thanks again for your help.

**Comment by pawelfus** [comment]
Actually, this is quite clever idea. I didn't think about that @timminss - thanks! :)
