### ISSUE TITLE
Solidgauge pane track flickers on update

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#14351]
It seems that in the new version (8.1.0) the solid gauge started to flick after the update, it has an impact on the React wrapper working - reported [here](https://github.com/highcharts/highcharts-react/issues/260). Not sure if it is a regression or intended behavior.

It could be disabled when the `chart.animation` is set to false: https://jsfiddle.net/BlackLabel/sjmxdzb9/

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/dusLaz3h/

#### Product version
> 8.0.0

**Comment by pawelfus** [comment]
**Simplified demo:** https://jsfiddle.net/BlackLabel/dusLaz3h/1/

Bisected to commit e70baaba67
