### ISSUE TITLE
Gantt wrong week count in the new year

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14361]
#### Expected behaviour
Start week 1 at the beginning of the new year.
Workaround: https://jsfiddle.net/BlackLabel/koymv9pj/

#### Actual behaviour
Week 1 starts a few days after the new year.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/uwxh48vq/

#### Product version
Highcharts Gantt JS v8.2.0 (2020-08-20)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
This is not a bug. As per ISO 8601, week numbers contains 7 days and when 1st of January is Friday, then W01 starts from 4th of January.
