### ISSUE TITLE
3d pie chart - incorrect datalabels distance

### ISSUE THREAD

**Issue by SShubham31** [highcharts/highcharts#14363]
#### Expected behaviour
Datalabel should in center of the slice but it is misplaced

#### Actual behaviour
 it is misplaced

#### Live demo with steps to reproduce
http://jsfiddle.net/3038m708/

**Comment by PaulDalek** [comment]
Hi @SShubham31,

Thank you for reporting this issue. There is no `inside` option for the data labels of the `pie` series and it looks like its presence in the `pie.dataLabels` section is a mistake in the API. If you want to display data labels closer to the center, you need to use negative `distance`.

**Comment by DJTechnoo** [comment]
Hello @PaulDalek ,
If I am not mistaken, this is an issue with the docs, and not an actual bug?
