### ISSUE TITLE
Need an onChange prop to get current/updated state of specific enable/disable legend from legends

### ISSUE THREAD

**Issue by sunnybhagtana** [highcharts/highcharts#14365]
#### Expected behaviour
We are trying to get the updated state while enabling or disabling specific legend from legends

#### Actual behaviour
We can disable/enable but don't have a prop to catch the current updated state

**Comment by pawelfus** [comment]
Hi @sunnybhagtana 

Thank you for using Highcharts! You can use these two events to listen to:
- [`series.events.hide`](https://api.highcharts.com/highcharts/plotOptions.series.events.hide)
- [`series.events.show`](https://api.highcharts.com/highcharts/plotOptions.series.events.show)

You can also use [`series.events.legendItemClick`](https://api.highcharts.com/highcharts/plotOptions.series.events.legendItemClick) if you want to check it only when legend item is clicked.

**Comment by sunnybhagtana** [comment]
Thanks for the reply, I am trying to get updated states of legends enable/disable so I can update the same state for a pop up chart dynamically.

**Comment by pawelfus** [comment]
Hi @sunnybhagtana 

Did you contact our [support](https://www.highcharts.com/blog/support/) team? I think they can help you more with your issue.

Note that we use GitHub issues as bug reports or feature requests. I don't see any bug here?

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
