### ISSUE TITLE
Changing colorIndex doesn't update styles if called through chart.update()

### ISSUE THREAD

**Issue by pettod** [highcharts/highcharts#14364]
When removing series, the color is not updated.
Bug is same as in [#8791](https://github.com/highcharts/highcharts/issues/8791) but in this case with stacked bar chart. When removing series, the old colors will remain and then adding new series will create copies of existing series.

#### Expected behaviour

Example:
1. Existing Series
Series 0, colorIndex: 0
Series 1, colorIndex: 1

2. Remove Series 0
Series 1, **colorIndex: 0**

#### Actual behaviour

1. Existing Series
Series 0, colorIndex: 0
Series 1, colorIndex: 1

2. Remove Series 0
Series 1, **colorIndex: 1**

#### JSFiddle
When removing 3 → 2 color changes properly: ![green](https://via.placeholder.com/15/90ed7d/000000?text=+), ![black](https://via.placeholder.com/15/434348/000000?text=+), ![blue](https://via.placeholder.com/15/7cb5ec/000000?text=+) → ![black](https://via.placeholder.com/15/434348/000000?text=+), ![blue](https://via.placeholder.com/15/7cb5ec/000000?text=+)
Removing from 2 → 1 it doesn't work. Should be: ![black](https://via.placeholder.com/15/434348/000000?text=+), ![blue](https://via.placeholder.com/15/7cb5ec/000000?text=+) → ![blue](https://via.placeholder.com/15/7cb5ec/000000?text=+), but color stays ![black](https://via.placeholder.com/15/434348/000000?text=+)
https://jsfiddle.net/m15kezyd/3/

#### Another JSFiddle
When adding new series, there also happens weird things in all cases (with 1 and 2 series especially). Maybe fixing the removing error above could fix this issue as well.
https://jsfiddle.net/d8ugc1e3/2/

#### Affected browser(s)
At least firefox

**Comment by pawelfus** [comment]
Thank you for reporting the issue @pettod 

**Workaround:**
Set `series.id`, so Highcharts will know which series should update to which options: https://jsfiddle.net/BlackLabel/28msc9fz/

*Internal note:*
In theory `colorIndex` is not supported in non-styledMode, but the option does not really matter here. The same happens for example with `name` option: https://jsfiddle.net/BlackLabel/jg4by17n/ 

This comes from a simple issue: `series.options.id` is set when calling `chart.update()`. Later, calling `series[0].remove()` does not reindex series. So next time we use `chart.update({ series })`, indexes are wrong.

Simplified demo: https://jsfiddle.net/BlackLabel/28r50L3n/ - wrong series name is updated in the last step: first series should have different name, not the second (green) one.

**Comment by pettod** [comment]
Thank you @pawelfus for providing solution. Using `series.id` fixes the problem.
