### ISSUE TITLE
AddSeries has no animation

### ISSUE THREAD

**Issue by Kang127** [highcharts/highcharts#14362]
I'm using addSeries to add a curve, why is there no animation, it makes no difference if the third parameter is true or false, I want to animate the curve, just like the animation of the first render.How do I set this

**Comment by pawelfus** [comment]
Hi @Kang127 

Thanks for reporting the issue! 

Demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/chart-addseries/

Steps:
Click on button - there's no animation. 

Last working version: v8.0.2

*Internal note:*
Bisected to commit 5b06bed1a7
