### ISSUE TITLE
.NET serialization of functions is very broken

### ISSUE THREAD

**Issue by brunnerh** [highcharts/highcharts#14376]
#### Expected behaviour

Functions (e.g. event handlers and formatters) get serialized as raw JS, rather than strings.

#### Actual behaviour

Sometimes a function will be output as a string, rather than raw JS. Highcharts will then try to invoke `call` on the string and throw an exception.

#### Live demo with steps to reproduce

As this concerns serialization, there is no live demo. 

Example program that illustrates the problem:

```c#
using Highsoft.Web.Mvc.Charts;
using Highsoft.Web.Mvc.Charts.Rendering;
using System;

namespace HighchartsSerializationIssue
{
    class Program
    {
        static void Main(string[] args)
        {
            var chart = new Highcharts
            {
                Series =
                {
                    new ScatterSeries { Events = { Click = "jsFunction1" } },
                    new ScatterSeries { Events = { Click = "jsFunction2" } },
                },
            };

            var json = new HighchartsRenderer(chart).GetJsonOptions();

            Console.WriteLine(json);
            Console.ReadKey(true);
        }
    }
}
```

This will output the following (formatted for convenience):

```js
{
	"series": [
		{
			"type": "scatter",
			"events": { "click": "jsFunction1" },
			"cluster": { "layoutAlgorithm": { "type": "scatterclusterlayoutalgorithm" } }
		},
		{
			"type": "scatter",
			"events": { "click": jsFunction2 },
			"cluster": { "layoutAlgorithm": { "type": "scatterclusterlayoutalgorithm" } }
		}
	]
}
```

Only `jsFunction2` was written as a JS literal. That is because the renderer uses a static `Hashtable` that associates a function with a value. However the function keys are always the same for every *type* of function. So since both of these handlers use same property (`ScatterSeriesEvents.Click`), the last used value is the only one that is still in the table.

In the case of this specific click event the value is set like this:

```c#
internal override Hashtable ToHashtable()
{
	// ...
	Highcharts.AddFunction("a291fa64-be4d-4f38-bb3f-f7c14709fb59.click", Click);
	// ...
}
```

Maybe this GUID was intended to be different for every object instance, but it appears to have been compiled into the assembly as a constant.

---

There is another bug with the function un-escaping mechanism: It is incredibly naive.

The code tries to do a simple string replacement on the key-value-pair in the JSON, which breaks as soon as the function code contains any characters that have to be escaped.

Example program that illustrates the problem:

```c#
using Highsoft.Web.Mvc.Charts;
using Highsoft.Web.Mvc.Charts.Rendering;
using System;

namespace HighchartsSerializationIssue
{
    class Program
    {
        static void Main(string[] args)
        {
            var chart = new Highcharts
            {
                Series =
                {
                    new ScatterSeries { Events = { Click = "function () { console.log(\"double quotes\") }" } },
                    new LineSeries { Events = { Click = "function () { console.log('single quotes') }" } },
                },
            };

            var json = new HighchartsRenderer(chart).GetJsonOptions();

            Console.WriteLine(json);
            Console.ReadKey(true);
        }
    }
}
```

This will output the following (formatted for convenience):

```js
{
	"series": [
		{
			"cluster": { "layoutAlgorithm": { "type": "scatterclusterlayoutalgorithm" } },
			"events": { "click": "function () { console.log(\"double quotes\") }" },
			"type": "scatter"
		},
		{
			"type": "line",
			"events": { "click": function () { console.log('single quotes') } }
		}
	]
}
```

The function containing double quotes is not serialized correctly, because the code does this:

```c#
string oldValue = $"\"{name}\":\"{value}\"";
string newValue = $"\"{name}\":{value}";
text = text.Replace(oldValue, newValue);
```

Here `name` will be `click` and `value` is the original C# value `"function () { console.log(\"double quotes\") }"`.
`oldValue` will not be found because the serialized JSON will be equivalent to the C# string `"function () { console.log(\\\"double quotes\\\") }"` which contains a backslash as part of the string.

#### Product version

Highsoft.Highcharts NuGet package v.8.1.2.4

**Comment by PaulDalek** [comment]
Hi @brunnerh

Thank you for reporting this issue. I’ve notified our .NET developer about this problem.

**Comment by pawellysy** [comment]
unstale
FYI @brofixo
