### ISSUE TITLE
Inactive state not applied to color patterns

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#14372]
#### Expected behaviour
Inactive state properly set on elements that use pattern fill.

#### Actual behaviour
Opacity is not set.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/wm2trzsf/5/

Hover over "A" circle, "A&B" circle should be dimmed out, just like with a regular color.

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/wm2trzsf/7/
Plugin:
```js
(function(H) {
  H.wrap(
    H.seriesTypes.venn.prototype,
    'pointAttribs',
    function(proceed, point, state) {
      var ret = proceed.apply(this, Array.prototype.slice.call(arguments, 1));


      if (point.color && point.color.pattern) {
        var options = H.merge(
          this.options,
          this.options.states && this.options.states[state] || {},
          point.options.states && point.options.states[state] || {}
        );

        if (
          state === 'inactive' &&
          options &&
          options.opacity !== 'undefined' &&
          // Make sure it's only for pattern plugin:
          point.color && point.color.pattern
        ) {
          ret.opacity = options.opacity;
        } else {
          ret.opacity = 1;
        }
      }

      return ret;

    }
  )
})(Highcharts);
```

**Comment by HafizHussain31** [comment]
Tried with typescript, it says H.seriesTypes.venn.prototype, H.seriesTypes is not defined. 

Can you check, if I am missing anything.

**Comment by pawelfus** [comment]
@HafizHussain31 workaround is using internal prototype and methods. For any issue like that in my workaround above, please cast to any (`(H.seriesTypes as any).venn.prototype`).

**Comment by HafizHussain31** [comment]
It worked as expected, with just a small change  ((H as any).seriesTypes.venn.prototype).

**Comment by pawelfus** [comment]
*Internal note:*
It's a bug in pattern plugin, demo reduced to renderer: https://jsfiddle.net/BlackLabel/wm2trzsf/8/
