### ISSUE TITLE
scrollablePlotArea- yAxis is not scrolling with the gauge

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14379]
#### Expected behaviour
Move the gauge yAxis while scrolling.
Workaround: https://jsfiddle.net/BlackLabel/jovu6k21/

#### Actual behaviour
When the scrollablePlotArea is enabled, the gauge yAxis is not scrolling. 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/wp3ud9k8/

#### Product version
Highcharts JS v8.2.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
*Internal note:*
In general, yAxis should not be scrolled (just like with a basic yAxis in line/column charts). However, radial axes can be exceptions in this case.
