### ISSUE TITLE
Cannot use json format for data if there is more than 1000 plots in the chart

### ISSUE THREAD

**Issue by kareshi** [highcharts/highcharts#14383]
#### Expected behaviour
Being able to specify data point as Json object like 
{
  x: 0,
  y: 123,
}

#### Actual behaviour
When defining up to a thousand points with JSON, the chart can be displayed.
From 1001 JSON points, the chart does not display anymore

#### Live demo with steps to reproduce

https://jsfiddle.net/Saigonara/f5ybouxe/11/
Line 36 if n (number of data points) is 1000, the diagram will display.
Line 36 if n (number of data points) is 1001, the diagram will not display anymore

#### Affected browser(s)
Safari and Chrome

**Comment by PaulDalek** [comment]
Hi @kareshi

Thank you for reporting this issue. This behavior is not a bug and it can be controlled by the [`turboThreshold`](https://api.highcharts.com/highcharts/series.line.turboThreshold) (see the error [#12](https://www.highcharts.com/errors/12/) in the console). Set it to a higher value or set it to 0 to disable it.

**Demo**
https://jsfiddle.net/BlackLabel/g7qn53dy/

**Comment by kareshi** [comment]
Hi @PaulDalek,

Thank you for your quick answer.
You are absolutely right. Adding the flag is allowing me to display the chart.
I noticed the error message as well when the flag value is smaller. Apologize for not seeing it before.

Regards,
Ivan
