### ISSUE TITLE
Documentation and Typescript type of stockTools.gui.buttons should be Array<string>

### ISSUE THREAD

**Issue by jonfreedman** [highcharts/highcharts#14389]
The documentation and typescript types are wrong and specify this property as a string, this was changed between 7.2.1 and 8.2.0

### Wrong
https://api.highcharts.com/highstock/stockTools.gui.buttons
https://unpkg.com/highcharts@8.2.0/highcharts.d.ts

### Correct
https://github.com/highcharts/highcharts/blob/master/ts/Stock/StockToolsGui.ts#L85

**Comment by pawelfus** [comment]
Thank you for reporting the issue @jonfreedman 

@bre1470 - could you check it? Thanks!
