### ISSUE TITLE
Shared tooltip setting does not work with gauges

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/highcharts#14387]
#### Expected behaviour
When setting `tooltip: { shared: true }`, the dials on the gauge should share a tooltip.

#### Actual behaviour
Tooltips are still displayed separately per dial.

#### Live demo with steps to reproduce
https://jsfiddle.net/lanimelrok/gk3cbdwn/

#### Product version
Highcharts latest

**Comment by pawelfus** [comment]
Hi @LaniMoo 

Thanks for reporting the issue! This is expected behaviour, `gauge` is a type of a series with unordered data (similar to pie or scatter), so shared is not intended to show up. 

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/snzbchd4/
Change:
```js
Highcharts.seriesTypes.gauge.prototype.noSharedTooltip = false;
```

**Comment by LaniMoo** [comment]
Thank you so much for your help as always, @pawelfus :)
