### ISSUE TITLE
dataLabels.animation.defer in networkgraph is not respected

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#14398]
#### Expected behaviour
`dataLabels.animation.defer` should defer rending dataLabels like for other series.

#### Actual behaviour
`dataLabels.animation.defer` is ignored, dataLabels are rendered right away.

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/18vrf9su/

*Internal note:*
By design, networkgraph disables all animations. Everything happens in `rAF`, where every node's position is calculated. In every simulation step, labels are checked for overlapping and rendered. Perhaps we can simply delay this overlapping logic by the `animation.defer` value.

**Comment by pawellysy** [comment]
unstale
