### ISSUE TITLE
colorAxis responsive legend position does not work normal

### ISSUE THREAD

**Issue by yasinakbulut** [highcharts/highcharts#14395]
#### Expected behaviour
when legend options changed, colorAxis data and pie chart colors should work stable
this code does not work normal with colorAxis
`legend: {
   	    enabled: true,
            align: 'left',
            verticalAlign: 'middle',
            layout: 'horizontal',
            borderWidth: 1,
            backgroundColor: 'white'
        },
responsive: {
          rules: [{
            condition: {
              maxWidth: 625,
            },
            chartOptions: {
            	legend: {
                  align: 'right',
                  verticalAlign: 'middle',
                  layout: 'vertical',
              },
            },
          }],
        },`

#### Actual behaviour
by responsive rules when legend options changed, coloraxis data does not seem and minColor, maxColor dont work for pie chart

#### Live demo with steps to reproduce
https://jsfiddle.net/o5ypbumw/4/

#### Product version
latest version

#### Affected browser(s)
chrome

**Comment by pawelfus** [comment]
Thank you for reporting the issue @yasinakbulut 

**Simplified demo:**
https://jsfiddle.net/BlackLabel/90th8vug/ 

FYI @ppotaczek

**Comment by yasinakbulut** [comment]
![image](https://user-images.githubusercontent.com/58821245/96731659-2e844100-13c0-11eb-980d-2cf2d72eda93.png)
sorry but looks like not working because colorAxis data does not look if you check the screenshoot

**Comment by ppotaczek** [comment]
**Workaround:** 
Hide x-axis, y-axis and set `chart.hasCartesianSeries = true;`
```
  chart: {
    events: {
      load: function() {
        this.hasCartesianSeries = true;
      }
    }
  },
  xAxis: {
    visible: false
  },
  yAxis: {
    visible: false
  },
```
**Live demo:** https://jsfiddle.net/BlackLabel/cm1yu8o4/
___

_Internal note:_
Problem related with calculating extremes after color-axis re-creation process. 
https://github.com/highcharts/highcharts/blob/edb442236f7df1395bcb9e5e7926e4adda84683d/ts/Core/Chart/Chart.ts#L833-L879
Everything works fine with cartesian series, example: https://jsfiddle.net/BlackLabel/udtbcsmj/

**Comment by yasinakbulut** [comment]
@ppotaczek Thank you. This worked for me. `this.hasCartesianSeries = true;`
