### ISSUE TITLE
Options other than "point" for legendType?

### ISSUE THREAD

**Issue by bpbraun** [highcharts/highcharts#14401]
https://github.com/highcharts/highcharts/blob/5ee7fe79e88ebe870b6a7874c9ccb775da3d2b3d/js/Series/TimelineSeries.js#L87-#L87

What are the other options other than "point"? I'm trying to have my timeline chart display unique values for each of type of event not every one in the legend.

**Comment by PaulDalek** [comment]
Hi @bpbraun

Thank you for reporting this issue. From what I can see the only correct value of the `legendType` property in case of a `timeline` series is `point`. It looks like this option shouldn’t be available in the API (should be ignored like in case of the `pie` series).

**Comment by pawelfus** [comment]
FYI @Denyllon

**Comment by Denyllon** [comment]
I agree with @PaulDalek, it supposed to be implicitly set equal to `point` "under the hood" in any way, like it's done in case of `pie` series, and should not be available in API. I would suggest to also mark this issue with `Product: Docs` label.

**Comment by Denyllon** [comment]
If you would really want to set the legend item per series, you can use the below workaround, but need to be aware of that is not perfect solution, and e.g the data labels will overlap between the series (what can be avoided for instance by setting the different data labels `distance` for a specific series, and at the same time disabling the `dataLabels.alternate` option).
```js
(function(H) {
  H.seriesTypes.timeline.prototype.getXExtremes = function(xData) {
    var series = this,
      arrayMin = H._modules['Core/Utilities.js'].arrayMin,
      arrayMax = H._modules['Core/Utilities.js'].arrayMax,
      pointLegend = series.options.legendType === "point",
      filteredData;

    if (pointLegend) {
      filteredData = xData.filter(function(x, i) {
        return series.points[i].isValid() && series.points[i].visible;
      });
    }

    return {
      min: arrayMin(pointLegend ? filteredData : xData),
      max: arrayMax(pointLegend ? filteredData : xData)
    }
  }
})(Highcharts)
```
Demo with applied workaround: https://jsfiddle.net/BlackLabel/2h9cmxd1/

Kind regards!
