### ISSUE TITLE
hover.fillColor is using series instead of point settings

### ISSUE THREAD

**Issue by slawekkolodziej** [highcharts/highcharts#1440]
Let's say we have scatter series. We set hover state fillColor to null, and specify color for each point in options. Now when we hover any point it still appears in series color.

According to the docs it should work a bit different. If you set fillColor to null, it should use point settings: http://api.highcharts.com/highcharts#plotOptions.scatter.marker.states.hover.fillColor

However I looked into the source code and it's quite simple to solve, but I'm not sure if I won't broke something else. Basically you should reverse order of `base1`, `base2` and `base` around line [1622](https://github.com/highslide-software/highcharts.com/blob/master/js/parts/Series.js#L1622).

For now, the code looks like this:

``` javascript
obj[attr] = pick(options[option], base1[attr], base2[attr], base3[attr]);
```

I propose to change it to something like this:

``` javascript
obj[attr] = pick(options[option], base3[attr], base2[attr], base1[attr]);
```

related topic on forum: http://highslide.com/forum/viewtopic.php?f=9&t=23494

**Comment by sebastianbochan** [comment]
+1

**Comment by abhisheksimion** [comment]
+1 related question on stackoverflow https://stackoverflow.com/questions/30642310/how-can-i-have-same-hover-point-color-in-highcharts

**Comment by highslide-software** [comment]
#### Workaround
Set the fillColor to an object:
```js
        marker: {
            radius: 6,
            states: {
                hover: {
                    fillColor: {}
                }
            }
        }
```
[View jsFiddle](http://jsfiddle.net/highcharts/9ezjvycd/).

**Comment by sebastianbochan** [comment]
Looks like an issue also in the heatmap.

Example:
- http://jsfiddle.net/qw5sugt5/ 

Workaround: set empty object for the color param, but then brightness is ignored.
- http://jsfiddle.net/Lm580w7a/

**Comment by ewels** [comment]
This is quite an old bug with a proposed fix. Are there any plans to fix this?
