### ISSUE TITLE
Y Axis X Axis series point issue

### ISSUE THREAD

**Issue by NaveedAhmed07** [highcharts/highcharts#14402]
Hi,

I'm creating a custom chart everything is gone good.

1. the marker cutt in xaxis ages side.
2. but my yaxis series value having 0 the marker gone bottom side and cutt in bottom agis. you can check number 6 value (basically number 6 value is 0 value).

kindly check my demo link
https://jsfiddle.net/CongoTech312/8nqLf9kz/8/

Ihave attached screenshot for my expectation properties.

![area-chart-feedback](https://user-images.githubusercontent.com/62809447/96822429-78fad180-1443-11eb-9ad1-7d9d1020a120.JPG)

**Comment by PaulDalek** [comment]
Hi @NaveedAhmed07 

Thank you for reporting this issue. This is a support question, so please next time contact us through any of our [support channels](https://www.highcharts.com/blog/support/) first. This is not a bug but a custom implementation of a chart. In your case you can use custom `tickPositions` along with a custom `labels.formatter` to achieve the effect from the screenshot.

**Demo**
https://jsfiddle.net/BlackLabel/wq4xz97m/

**Comment by NaveedAhmed07** [comment]
Thanks
