### ISSUE TITLE
[Help] How to set empty parent node size in packed bubble split

### ISSUE THREAD

**Issue by Mokaffe** [highcharts/highcharts#14407]
####  First time to use Highchart, try to use exist API to config empty parent node size. But failed.

I want to set empty parent node size bigger.
<img width="538" alt="expected" src="https://user-images.githubusercontent.com/9446480/96875900-58b22d80-14aa-11eb-8465-b377969b35f7.png">

`const options2 = {
  chart: {
    type: 'packedbubble',
    height: '100%',
  },
  title: {
    text: 'APIs Governance Map By Category',
  },
  tooltip: {
    useHTML: true,
    pointFormat: '<b>{point.name}</b>',
  },
  legend: {
    verticalAlign: 'top',
  },
  plotOptions: {
    packedbubble: {
      minSize: '20%',
      maxSize: '100%',
      zMin: 0,
      zMax: 1000,
      layoutAlgorithm: {
        gravitationalConstant: 0.05,
        splitSeries: true,
        seriesInteraction: false,
        dragBetweenSeries: false,
        parentNodeLimit: true,
      },
      dataLabels: {
        enabled: true,
        format: '{point.name}',
        allowOverlap: true,
        style: {
          color: 'black',
          textOutline: 'none',
          fontWeight: 'normal',
        },
      },
    },
  },
  series:[
    {name: 'parent node', data:[{name: 'aa', value: 1}, {name: 'bb', value: 1} ]},
    {name: 'empty parent node#1', data:[]},
    {name: 'empty parent node#2', data:[]},
  ]
};
`

**Comment by PaulDalek** [comment]
Hi @Mokaffe

Thank you for reporting this feature. The radius of the parent node is calculated in the `calculateParentRadius` function. There is the `minParentRadius` property which by default is set to 20.

**Demo**
https://jsfiddle.net/BlackLabel/76p0ymLd/

**Comment by Mokaffe** [comment]
Hi @PaulDalek,

Thank you. 👍
