### ISSUE TITLE
I am unable to move the tooltip to right side when bubble is near to left side area 

### ISSUE THREAD

**Issue by ashrafmansuri123** [highcharts/highcharts#14419]
![Screenshot (74)](https://user-images.githubusercontent.com/60643884/97111511-25b7a600-1705-11eb-9b66-e14e2a9db475.png)
in the attached image the tooltip is getting cut in the area and it should be moved to the left of point when we are very near to the left side 
please provide the source code 
so that tooltip can be moved to left (when the point/node is near to right end side) and tooltip can be moved to right(when the point/node is near to left end side)

**Comment by PaulDalek** [comment]
Hi @ashrafmansuri123

Thank you for reporting this issue. Please provide a live example where this behavior can be observed. Thanks.

**Comment by ashrafmansuri123** [comment]
Hi @PaulDalek , 
I can't provide you the live example , but it will be great , if you can provide me the tooltip positioning source code

**Comment by pawelfus** [comment]
@ashrafmansuri123 

You can find it in the source code: http://code.highcharts.com/highcharts.src.js (search for `defaultPositioner`).

Related TS:
https://github.com/highcharts/highcharts/blob/6d7be4645358ef17ecc837c8e5e9a977215b3071/ts/Core/Tooltip.ts#L1487-L1526

> I can't provide you the live example

Without any demo we can not mark this as a bug, and issue will be closed soon.

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
