### ISSUE TITLE
Draggable vertical line in synchronised graphs

### ISSUE THREAD

**Issue by fmmattioni** [highcharts/highcharts#14418]
Hi everyone,

I was wondering if this example here:

https://www.highcharts.com/demo/synchronized-charts

Instead of the hover functionality, this could be a draggable vertical line instead? Ideally, with the numbers getting updated constantly, and not only the mouse is released. I hope that makes sense.

Thank you,
Felipe

**Comment by pawelfus** [comment]
Hi @fmmattioni 

Yes, this is possible. We don't have such demo though. You can achieve this in multiple ways (use annotations, separate series, plotLines, or just build-in Renderer class). I think annotations are the easiest solution here. In steps:

1. Create annotation, that is draggable and updates it's label on drag&drop: https://jsfiddle.net/BlackLabel/50g1tyjh/
2. Sync annotations: https://jsfiddle.net/BlackLabel/7t59w4po/

Alternative approach, using Renderer:

1. Create a line+label element (`const line = chart.renderer.path(...).attr(...).add();`)
2. Implement drag&drop (`Highcharts.addEvent(line, 'mousedown', function () { ... }` etc.);
3. Sync lines+labels across charts - when one line+label is being dragged, update positions for all others

**Comment by fmmattioni** [comment]
Dear @pawelfus, this is fantastic! Thanks a lot for the demos! That is exactly what I was looking for!

**Comment by pawelfus** [comment]
Great to hear that! 

PS: If you have any other questions, please contact our support team first: https://www.highcharts.com/blog/support/ - we use GitHub issues as bug reports/feature requests
