### ISSUE TITLE
yAxis min property and startOnTick/endOnTick not working properly

### ISSUE THREAD

**Issue by adetl** [highcharts/highcharts#14417]
#### Expected behaviour

When I use startOnTick and endOnTick as false, and min property in yAxis, if that min value is greater than all the values of the points then chart should be empty (it shouldn't draw any point)

#### Actual behaviour

When I use startOnTick and endOnTick as false and a min property in yAxis, if the min value is greater than the values of the points, it actually draws some points (that are lower than the min value). Also, it seems that the chart is inverted

#### Live demo with steps to reproduce
https://jsfiddle.net/ladet/0k45zcdb/2/

#### Product version
Highcharts 8.1.2 with Highcharts-react

**Note**: I need both startOnTick and endOnTick as false, and it shouldn't be drawing any points when the min is greater than the points. If I set startOnTick and endOnTick as true, this doesn't happen. If I set a max property it works correctly, but since both max and min are set dynamically by the user, it should be possible to only select a minimum limit and it should be working properly whether the values are lower than said minimum or higher.

![image](https://user-images.githubusercontent.com/66751026/97060593-2962f580-156a-11eb-90b2-e3d203a51573.png)

This also happens with columns charts but is worse since it draws a full column when it shouldn't draw any column
![image](https://user-images.githubusercontent.com/66751026/97060735-b0b06900-156a-11eb-84fa-bb144be7e6af.png)

**Comment by pawelfus** [comment]
Thank you for reporting this bug @adetl 

**Workaround:**
As mentioned above, set `xAxis.max` or disable one of the options.
Alternatively, use this plugin: https://jsfiddle.net/BlackLabel/3h2zc7pa/
```js
(function(H) {
  H.wrap(
    H.Axis.prototype,
    'trimTicks',
    function(proceed, positions, startOnTick, endOnTick) {

      proceed.apply(this, Array.prototype.slice.call(arguments, 1));

      if (this.min > this.max) {
        if (this.options.min !== undefined) {
          this.max = this.min;
        } else if (this.options.max !== undefined) {
          this.min = this.max;
        }
      }
    }
  )
})(Highcharts);
```

**Comment by adetl** [comment]
Thanks, @pawelfus for the workarounds!
Also, this happens when I put a max that is lower than any point in the chart.
