### ISSUE TITLE
tickpositions - datetime xAxis

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1441]
In case when xAxis has datetime type and we set tickPositions as timestamps, then labels are not dates, but numbers.

http://jsfiddle.net/topatidle/AWeNf/1/ HC
http://jsfiddle.net/AWeNf/3/ HS

**Comment by oysteinmoseng** [comment]
This is still an issue with the latest code.

**Comment by kaikuchn** [comment]
Additionally I observed that `autoRotation` has no effect when using `tickPositions`.

**Comment by mateuszkornecki** [comment]
+1

**Comment by jamesonhill** [comment]
Also an issue for me on v8.0.0

**Comment by PaulDalek** [comment]
Hi @jamesonhill

Thank you for contacting us. This is still labeled as a bug. You can use the workaround with the [`formatter`](https://api.highcharts.com/highcharts/xAxis.labels.formatter) function that is mentioned above or use the [`tickPositioner`](https://api.highcharts.com/highcharts/xAxis.tickPositioner) that returns required ticks along with an additional object in the array (`info`) which contains information necessary to create a label’s format. We will take a closer look at this problem.

**Workaround**
https://jsfiddle.net/BlackLabel/pa3mbdkv/
