### ISSUE TITLE
Data labels overlap with responsive options

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#14411]
#### Expected behaviour
Some data labels should be hidden to prevent overlapping.

#### Actual behaviour
Data labels overlap when responsive options are set.

#### Live demo with steps to reproduce
v.8.1.0 regression -> https://jsfiddle.net/BlackLabel/atuvcy5L/
v8.0.4 working as expected -> https://jsfiddle.net/BlackLabel/3Latosfm/

#### Product version
Highcharts v.8.1.0

**Comment by PaulDalek** [comment]
This is already fixed in the newest release.

**Demo**
https://jsfiddle.net/BlackLabel/p5wbjy7v/
