### ISSUE TITLE
Enabling drilldown on existing series does not initially work

### ISSUE THREAD

**Issue by KarlBaumann** [highcharts/highcharts#14428]
#### Expected behaviour
Drilldown columns are clickable from the start

#### Actual behaviour
Drilldown columns are clickable only after going one level deeper and then coming back to start.
As you see in my example, clicking on chart columns does not work.
Initially you are only able to click on xAxis ticks (years), then you click "Back" button and only then you can click on the columns.

#### Live demo with steps to reproduce
https://codepen.io/SoWhat/pen/RwRoMQq

#### Product version
All versions up to 8.0.0. When testing with newer versions, my chart did not work at all.

#### Affected browser(s)
All

I think this is a bug, because the point.update({ drilldown: true }, false); function only changes cursor to pointer, but does not actually enable drilldown initially.

**Comment by KarlBaumann** [comment]
Guys, do you have any estimates on this? Did somebody take a deeper look? @circleci-mu

**Comment by PaulDalek** [comment]
Hi @KarlBaumann

Thank you for reporting this issue. You’re right, the drilling should be possible after points update. The workaround here is to fire the `afterInit` event for each point which adds the `click` event for drilling. As for the ETA for the fix, it is hard to say as the issue just has been reported.

**Demos**
https://jsfiddle.net/BlackLabel/yaq62wr7/ - simplified
https://jsfiddle.net/BlackLabel/mfpzxhkL/

_Internal note_
The `afterInit` event for the `Point` from the drilldown module where the `click` event for drilling is set, is fired on Point’s `init` only therefore clicking on a point after it is updated with the `drilldown` property won’t result in a drilldown. Drilling through the category and back initialize points again causing in adding the `click` event.
