### ISSUE TITLE
I am unable to change the legend view  ( expected legend in single line)

### ISSUE THREAD

**Issue by ashrafmansuri123** [highcharts/highcharts#14421]
current legend view 
![image](https://user-images.githubusercontent.com/60643884/97112240-2c481c80-1709-11eb-98d0-db853af99615.png)

expected legend view (in one line )
![image](https://user-images.githubusercontent.com/60643884/97112275-5e597e80-1709-11eb-905c-138d70ef1422.png)

please provide source code to put all the legends in one line

**Comment by PaulDalek** [comment]
Hi @ashrafmansuri123 

Thank you for reporting this issue. This already can be achieved using the [`legend`](https://api.highcharts.com/highcharts/legend) options.

**Demo**
https://jsfiddle.net/BlackLabel/eohcuv5g/

**Comment by ashrafmansuri123** [comment]
Thanks @PaulDalek
