### ISSUE TITLE
Vertical panning after zooming

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14426]
#### Expected behaviour
Pan on the vertical axis after zoom to `0`.

#### Actual behaviour
After zooming, new min equal the minimal data is set on the y-axis.
Unable to pan on the vertical axis below the `1.2`.

#### Live demo with steps to reproduce
Zoom in, then try to pan below `1.2` on the y-axis.
https://jsfiddle.net/BlackLabel/v27u1tks/

#### Product version
Highcharts JS v8.2.2 (Vertical panning available from 8.1.0)

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
It seems that vertical panning goes and stops at `yAxis.dataMin` which, in this case, is 1.2. It makes sense with other types of series e.g. [line](https://jsfiddle.net/BlackLabel/78n2Lvcu/)

In column series, it should take `column.threshold` (usually 0): https://jsfiddle.net/BlackLabel/t5932o4k/ (line 83)

**Comment by sebastianbochan** [comment]
FYI @Denyllon

**Comment by Denyllon** [comment]
Agree with @raf18seb, as current implementation does make sense with line (and familiar) series, vertical panning on columns should be handled by taking into account the `series.threshold`, so indeed, the workaround suggested in the mentioned demo could be the fix here.
