### ISSUE TITLE
I am unable to fix the bubble overlapping  

### ISSUE THREAD

**Issue by ashrafmansuri123** [highcharts/highcharts#14420]
![image](https://user-images.githubusercontent.com/60643884/97111686-4c2a1100-1706-11eb-837e-7a97312abe44.png)
the bubbles are getting overlaped i tried to reduce the bubble outer radius 

the code i used to reduce the size is 
  (function(H) {
                H.wrap(
                    (H as any).seriesTypes.packedbubble.prototype,
                    'calculateParentRadius',
                    function(proceed) {
                        proceed.apply(this, Array.prototype.slice.call(arguments, 1));
                        //   var diff = this.points.length === 1 ? 30 : 10;
                   
                        var  diff = this.points.iterated ? 0 :20;
                    // var iterateTime = this.dataFinalArray.length;
                    if (this.parentNode && this.points.length === 1 && this.parentNodeRadius > 30 && this.parentNode.radius > 30 && this.parentNode.marker.radius > 30) {
                            this.parentNode.marker.radius = 70;
                            this.parentNode.radius = 0;
                            this.parentNodeRadius = 0;
                            this.points.iterated = true;
                            isSizeReduced = true;
                    }else {

                    }
                }
                )
              })(Highcharts);

**Comment by pawelfus** [comment]
Thanks @ashrafmansuri123 

Please, provide live demo of the issue. Thanks!

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
