### ISSUE TITLE
Tooltip `stickOnContact` has confilct with `outside`

### ISSUE THREAD

**Issue by ytnytn1** [highcharts/highcharts#14434]
#### Expected behaviour

Tooltip should not change while mouse pointer is on it.

#### Actual behaviour

Tooltip is closed

#### Live demo with steps to reproduce
https://jsfiddle.net/fv5qkr4c/

#### Product version
v8.2.2

#### Affected browser(s)
Tested on Chrome 86.0.4240.111

**Comment by PaulDalek** [comment]
Hi @ytnytn1

Thank you for reporting this issue.

**Simplified demo**
https://jsfiddle.net/BlackLabel/cfbqotnw/

**Comment by jakobloekke** [comment]
Seems to be broken since 8.0.4.

8.0.3 -> https://jsfiddle.net/0fse39jh/
8.0.4 -> https://jsfiddle.net/0fse39jh/1/

**Comment by jakobloekke** [comment]
And it doesn't seem to ever work on column charts.
8.0.1 -> https://jsfiddle.net/0fse39jh/2/

**Comment by PaulDalek** [comment]
Hi @jakobloekke

Thank you for contacting us and for your observation. It looks like there is a typo in the [API](https://api.highcharts.com/highcharts/tooltip.stickOnContact). The `stickOnContact` was [introduced](https://www.highcharts.com/blog/changelog/#highcharts-v8.0.4) in v8.0.4, not v8.0.1. So it’s still a bug, not a regression.

**Comment by jakobloekke** [comment]
@PaulDalek, I see. :)
Yeah, I was looking in the API, which says 8.0.1.

**Comment by jkumor-applause** [comment]
Hi,
Are there any plans for fixing this issue in foreseeable future?
Best regards!

**Comment by KacperMadej** [comment]
Looks like the PR got stuck. Any news @khlieng ?

**Comment by khlieng** [comment]
No, but the fix works, @TorsteinHonsi wanted a simpler check.

**Comment by qiwxue** [comment]
Is there any progress for the fix? https://github.com/highcharts/highcharts/pull/15960? @khlieng  @TorsteinHonsi

**Comment by khlieng** [comment]
Its just waiting for a review, which should happen in a couple weeks.
