### ISSUE TITLE
Legend Items rotate fill patterns

### ISSUE THREAD

**Issue by weytani** [highcharts/highcharts#14441]
#### Expected behaviour
For the legend item to look like the fill pattern on the related chart section

#### Actual behaviour
Legend item seems to rotate -90 or 270 degrees then flip as if in a mirror

#### Live demo with steps to reproduce
https://jsfiddle.net/6atqvf7o/63/
So here is an attempt i made to correct the issue. You will notice natural gas has a css override attempting to  rotate  the legend item. Unfortunately spacing becomes an issue at this point and makes this solution unusable. I can't seem to address the spacing issue with CSS. You'll notice wind is broken and believe they all are in fact. a 270 degree rotation that then mirrors would reproduce the diagonal lines perfectly, so I'm convinced this is what is happening.

#### Product version
current version

#### Affected browser(s)
Brave, chrome, edge

**Comment by pawelfus** [comment]
Thank you for reporting this issue @RB-232 

I think your solution is quite usable, with just some polishing: https://jsfiddle.net/BlackLabel/ej3mfLhv/
```css
.highcharts-legend .highcharts-point {
  transform: rotate(90deg) scale(-1, 1) translate(-14px, -14px);
}
```
