### ISSUE TITLE
Chart goes outside plot on zoom with boost

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#14444]
#### Expected behaviour
Chart should be redrawn within the plot area

#### Actual behaviour

![image](https://i.imgur.com/3lF48xr.gif)

As you can see, on zooming in the bars go out of the plot area. In many cases, they go a lot out distorting other content in the page.

#### Live demo with steps to reproduce
Minimal reproducer: https://jsfiddle.net/v7t9kefn/2/

#### Product version
Highcharts JS v8.2.2 (2020-10-22)

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thank you for reporting this bug @govinda18 

The same happens with other inverted series types: https://jsfiddle.net/BlackLabel/0vm8sL5k/ - probably caused by wrong clip-path in inverted charts.

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/0vm8sL5k/1/
Plugin:
```js
(function(H) {
  H.addEvent(H.Chart, 'render', function() {
    if (this.boostClipRect) {
      this.boostClipRect.attr({
        height: this.plotHeight,
        y: this.plotTop
      });
    }
  })
})(Highcharts);
```

**Comment by govinda18** [comment]
Thanks @pawelfus.

**Comment by pawelfus** [comment]
*Internal note:*
This seems to be a bug in inverted chart only, check how it's done for non-inverted chart and use the same logic in clipping (or, perhaps, swap width & height for inverted chart).
