### ISSUE TITLE
'adjustForMissingColumns' is not  function for columnrange series with centerInCategory=true

### ISSUE THREAD

**Issue by Justinetz** [highcharts/highcharts#14440]
I try to create several highchart instances (each on separate 'div' container). Chart type - columnrange. 
PlotOptions for **columnrange** contains 'centerInCategory' = true

Expected behaviour
I expect to see all charts on the page

Actual behaviour
I don't see the chart and see exception
_Uncaught TypeError: f.adjustForMissingColumns is not a function
    at highcharts.src.js:39892
    at Array.forEach (<anonymous>)
    at translate (highcharts.src.js:39840)
    at t.<anonymous> (highcharts-more.src.js:10242)
    at t.b.<computed> (highcharts.src.js:1090)
    at translate (highcharts-more.src.js:2328)
    at highcharts.src.js:29254
    at Array.forEach (<anonymous>)
    at f.renderSeries (highcharts.src.js:29253)
    at f.render (highcharts.src.js:29373)_

Live Demo evenr for only one chart:
**https://jsfiddle.net/rofk9xLq/2/**

Product version
Highcharts 8.2.2 

Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting the issue @Justinetz 

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/tdyr56f8/
Code:
```js
Highcharts.seriesTypes.columnrange.prototype.adjustForMissingColumns = Highcharts.seriesTypes.column.prototype.adjustForMissingColumns;
```

**Comment by Justinetz** [comment]
> Thanks for reporting the issue @Justinetz
> 
> **Workaround:**
> Demo: https://jsfiddle.net/BlackLabel/tdyr56f8/
> Code:
> 
> ```js
> Highcharts.seriesTypes.columnrange.prototype.adjustForMissingColumns = Highcharts.seriesTypes.column.prototype.adjustForMissingColumns;
> ```

**Comment by Justinetz** [comment]
Thanks @pawelfus ! Works for me. Hope this functionality will be added to columnrange too

**Comment by pawelfus** [comment]
We will do it, so let's keep this issue open. Thanks once again :)
