### ISSUE TITLE
Data lines disappear on resize when using 'responsive' options to adjust tooltips

### ISSUE THREAD

**Issue by diogen737** [highcharts/highcharts#14442]
#### Actual behaviour
Data lines disappear when resizing the window and then appear again when resizing further or back.
Notably the width range on which the bug appears is different every time.

When `responsive` option is removed or `chartOptions` doesn't include `tooltip` settings the bug isn't there anymore.

#### Expected behaviour
Lines resize smoothly along with the chart container

#### Live demo with steps to reproduce
https://jsfiddle.net/9zknf61u/

#### Product version
Highstock 8.2.2

**Comment by PaulDalek** [comment]
Hi @diogen737

Thank you for reporting this issue. It looks like this is related to data grouping (see this simplified demo: https://jsfiddle.net/BlackLabel/01xcr24s/). Setting the `dataGrouping` options explicitly (in the `plotOptions` section for example) seems to resolve the problem.

**Demo**
https://jsfiddle.net/BlackLabel/5ateynmj/

**Comment by diogen737** [comment]
Hi @PaulDalek 
thanks for the reply and the workaround.

It's still a bug, right? Because it's pretty wild if one could pick an unrelated (at least on the surface) chart option and fix chart behavior with it :) And besides, what if I need `dataGrouping` to be explicitly disabled for some reason?

**Comment by PaulDalek** [comment]
@diogen737

Yes, it’s still labeled as a bug.

_Internal note_
Points created through the `generatePoints` (on the series' `redraw` when resizing a chart) have incorrect `x` values (starting from the beginning of the raw `xData`), therefore the generated `plotX` values (in the `translate` function) are wrong (negative values, outside the visible range).

**Comment by PaulDalek** [comment]
**Simplified demo**
https://jsfiddle.net/BlackLabel/paxetn2v/

**Steps to reproduce**
1. Click on the ‘Set width to 400’ button.
2. Only a part of the points is visible.

**Comment by K009** [comment]
From version 9.0.0 it works fine.
