### ISSUE TITLE
Drill-up button dissappears when using scrollablePlotArea.minHeight

### ISSUE THREAD

**Issue by shahimclt** [highcharts/highcharts#14448]
#### Expected behaviour
There should be a drillup button on the top right. It works when there is no scroll to the chart area

#### Actual behaviour
When scrollablePlotArea.minHeight is set, the drillup button no longer appears, 

and there is a wierd translucent white bar at the top that I can not seem to find using the inspector.
![image](https://user-images.githubusercontent.com/8318002/97405179-41959480-191d-11eb-80b0-eaadaf785f8c.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/shahimclt/cpLmuo06/

https://jsfiddle.net/shahimclt/4xqeg5v3/5/

#### Product version
Highcharts/Highmaps version 8.2.2

#### Affected browser(s)
Chrome/Firefox

**Comment by PaulDalek** [comment]
Hi @shahimclt

Thank you for reporting this issue. It looks like the higher value of the [`minHeight`](https://api.highcharts.com/highcharts/chart.scrollablePlotArea.minHeight), the drillUp button goes further to the right until eventually it is out of the visible area. Setting the [`align`](https://api.highcharts.com/highcharts/drilldown.drillUpButton.position.align) to the `'left'` seems to resolve the problem. As for the semi-transparent white bar, it comes from the scrollable plot area and it can be controlled by the [`opacity`](https://api.highcharts.com/highcharts/chart.scrollablePlotArea.opacity) option.

**Demo**
https://jsfiddle.net/BlackLabel/8yfk5pcz/

**Comment by shahimclt** [comment]
Yes. That makes sense. Thank you.

**Comment by PaulDalek** [comment]
**Simplified demo**
https://jsfiddle.net/BlackLabel/xqwcve9p/

**Steps to reproduce**
1. Click on the first column (the button is slightly covered).
2. Click on the ‘Back to Main series’ button.
3. Update minHeight to 500 (button below).
4. Click on the first column (the button is pushed further to the right).
