### ISSUE TITLE
Bar chart - border cut off

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1444]
In case when border is set for stacked bar, then is cutted of in the edge. 

http://jsfiddle.net/zKgsF/

Workaround is set max as 100.1 and endOnTick as false.

http://jsfiddle.net/zKgsF/25/

**Comment by oysteinmoseng** [comment]
This is still relevant, and I would consider it a bug. The border should have a higher z-priority than grid lines

**Comment by RakhmatovR** [comment]
Agree, border should be shown without some worakarounds.
