### ISSUE TITLE
Drilldown to point of same name as parent column on 3d column chart causes error

### ISSUE THREAD

**Issue by marklofdahl** [highcharts/highcharts#14458]
#### Expected behaviour
Drilldown when series has 1 point with same name as parent point should work.

#### Actual behaviour
Drilldown when series has 1 point with same name as parent point produces javascript error.
Axis3D.wrapGetSlotWidth - nextTick.label is undefined

#### Live demo with steps to reproduce
http://jsfiddle.net/marklofdahl/re1fjh6y/
Click on "Museums" to drilldown - causes javascript error

#### Product version
Highcharts 8.2

#### Affected browser(s)
all

If the point name is not the same as the parent point, then it does not error.

I worked around it by setting nextTick.label...

    /* wrap Axis.getSlotWidth for 3D, to fix missing label bug */
    Highcharts.wrap(Highcharts.Axis.prototype, 'getSlotWidth', function (proceed, tick) {
        var axis = this;
        var chart = axis.chart;
        var ticks = axis.ticks;
        var gridGroup = axis.gridGroup;
        var width;

        if (axis.categories &&
            chart.frameShapes &&
            chart.is3d() &&
            gridGroup &&
            tick &&
            tick.label) {

            var tickId = tick.pos,
                prevTick = ticks[tickId - 1],
                nextTick = ticks[tickId + 1],
                prevLabel,
                nextLabel;

            if (tickId !== 0 && prevTick && !prevTick.label) {
                prevTick.label = {};
                prevLabel = true;
            }
            if (nextTick && !nextTick.label) {
                nextTick.label = {};
                nextLabel = true;
            }
            width = proceed.apply(axis, [].slice.call(arguments, 1));
            if (prevLabel) {
                delete prevTick.label;
            }
            if (nextLabel) {
                delete nextTick.label;
            }
        } else {
            width = proceed.apply(axis, [].slice.call(arguments, 1));
        }
        return width;
    });
})(Highcharts);

**Comment by sebastianbochan** [comment]
Hi @marklofdahl,
Thank you for reporting.

@TorsteinHonsi maybe we should consider to add the information to docs about unique "name" param? What do you think, is it a bug or not?

**Comment by pawelfus** [comment]
I think it's a bug, it works fine in 2D charts: http://jsfiddle.net/BlackLabel/3572whtb/
