### ISSUE TITLE
Stack bar chart update with 500 series

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#14453]
#### Expected behaviour
The `chart.update` should draw full bars as expected.

#### Actual behaviour
![](https://i.imgur.com/Kw5bmWK.gif)

As you can see the update does not work as expected. On a little debugging locally, I figured it is due to `chart.spacing`. When I am not setting this, the update works fine.

#### Live demo with steps to reproduce
https://jsfiddle.net/v7t9kefn/4/ - I was not able to reproduce with dummy data. Hence, I have hosted with original data so it may be a little tough to play around with. However, I can surely say that as I stated above, without `chart.spacing`, things work fine. 

#### Product version
Highcharts JS v8.2.2 (2020-10-22)

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thank you @govinda18 

**Simplified demo:**
https://jsfiddle.net/BlackLabel/uobrgq81/1/

In short, updating `chart.spacing` + `plotOptions.<<series>>.stacking` options at the same time causes wrong rendering.

**Workaround:**
Demos:
- https://jsfiddle.net/BlackLabel/uobrgq81/2/  (simplified)
- https://jsfiddle.net/BlackLabel/e5b0fyr6/

Code:
Before creating a chart:
```js
Highcharts.Chart.prototype.propsRequireReflow.splice(Highcharts.Chart.prototype.propsRequireReflow.indexOf('spacing'));
```
After calling update with `spacing` call manually `chart.reflow()`. All options that most likely have the same issue:
```js
        'margin',
        'marginTop',
        'marginRight',
        'marginBottom',
        'marginLeft',
        'spacing',
        'spacingTop',
        'spacingRight',
        'spacingBottom',
        'spacingLeft'
```

*Internal note:*
Something is wrong with stacking, even though `spacing` seems to be the culprit. We have `yAxis.stacking.stacks.undefined` while should be `yAxis.stacking.stacks.bar,,,`. Somehow stack key is undefined, rendering points incorrectly.

**Comment by TorsteinHonsi** [comment]
Fixed in the latest master: https://jsfiddle.net/2y3fm8go/

**Comment by govinda18** [comment]
Hi, Thanks for the workaround.

I think the issue is not restricted to stack column chart as I faced a different issue with line chart and the same solution worked - https://jsfiddle.net/4wrxak8q/.

Just wanted to confirm if this is a reliable fix and We can safely incorporate it into our code? If you can just explain what the workaround does would be great, so I can see if it can potentially break something in our code. 

Thanks a lot!

**Comment by pawelfus** [comment]
You're welcome!

> I think the issue is not restricted to stack column chart as I faced a different issue with line chart and the same solution worked - https://jsfiddle.net/4wrxak8q/.

That's correct, in my post above you can see I mention any series, not only column/bar.

> Just wanted to confirm if this is a reliable fix and We can safely incorporate it into our code? If you can just explain what the workaround does would be great, so I can see if it can potentially break something in our code.

It is not a fix, just a workaround. Issue is already fixed on our master branch, you can test is: https://github.highcharts.com/highcharts.js We don't recommend using it on the production.

Side effect of my workaround is that you need to call `chart.reflow()` after updating chart.

Workaround is removing `spacing` from `propsRequireReflow` array, which prevents from calling `chart.reflow()` internally. In fact we change order: `chart.reflow() && chart.redraw();` to `chart.redraw() && chart.reflow();`.

**Comment by govinda18** [comment]
Cool got it! For the time being, I will fix my code with the workaround suggested until we the change is released and we can upgrade. Thanks a lot!

**Comment by pawelfus** [comment]
Great, you're welcome!
