### ISSUE TITLE
Issue with requirejs

### ISSUE THREAD

**Issue by mirshahreza** [highcharts/highcharts#14463]
This code is your documentation sample.
It not works (with latest stable version) but when I change the highcharts refrence to 7.0.2 it works fine !!!

```
<script src="require.js"></script>
<script>
  require.config({
        packages: [{
          name: 'highcharts',
          main: 'highcharts'
        }],
        paths: { // Change this to your server if you do not wish to use our CDN. 'highcharts': 'https://code.highcharts.com' } }); 

</script>
<script>
  require(['highcharts', 'highcharts/modules/exporting', 'highcharts/modules/accessibility'], function(Highcharts) { // This function runs when the above files have been loaded.
    // Create a test chart.
    Highcharts.chart('container', {
      series: [{
        data: [1, 2, 3, 4, 5]
      }]
    });
  });

</script>
</body>
```

**Comment by PaulDalek** [comment]
Hi @mirshahreza

Thank you for reporting this issue. I was able to create a working example that uses RequireJS loader without any problems. I have noticed that the piece that you provided lacks some elements (like containing div or a correct link to RequireJS). Take a look at the demo below (taken from the [API](https://api.highcharts.com/class-reference/#toc5)).

**Demo**
https://jsfiddle.net/BlackLabel/g6sbpcqy/

**Comment by mirshahreza** [comment]
Hi @PaulDalek 
It seems ok. but I will try to use it in my project maybe the issue is other one.
Anyway thank u for reply 👍
