### ISSUE TITLE
how to stop color transition observed  in split packed parent bubble 

### ISSUE THREAD

**Issue by ashrafmansuri123** [highcharts/highcharts#14464]
Hi
I observed unnecessary color transition iin split packed bubble , when we mouse  hover on the split packed bubble it's
color slightly change , and after removing the mouse pointer from the bubble the original color does not appear back ,
the color from the transition is persisted there 

color before mousing hover 
![image](https://user-images.githubusercontent.com/60643884/97801944-281a8280-1c66-11eb-9008-cf1ab168e526.png)

color after mousing hover 
![image](https://user-images.githubusercontent.com/60643884/97801970-54ce9a00-1c66-11eb-8f82-b653efc87794.png)

best case the original color should appear back when the mouse pointer is put away from the bubble
please provide the source code to stop this color  transition or to get the original color back when removing the pointer from the bubble

**Comment by PaulDalek** [comment]
Hi @ashrafmansuri123 

Thank you for reporting this issue. Could you please provide me with a live example where this behavior can be observed? Thanks.

**Comment by ashrafmansuri7272** [comment]
> Hi @ashrafmansuri123
> 
> Thank you for reporting this issue. Could you please provide me with a live example where this behavior can be observed? Thanks.

Hi 
This behaviour is observed in all packed bubble charts 
You can pick any to observe such behaviour

**Comment by PaulDalek** [comment]
**Simplified demo**
https://jsfiddle.net/BlackLabel/6g2r1myj/

**Steps to reproduce**
1. Hover on the parent node (color is changed).
2. Hover out of the parent node (color stays).

**Comment by shirleyow** [comment]
Hi, I am encountering the same issue as well, may I know if there's a fix for this? Thanks in advance!

**Comment by KacperMadej** [comment]
As a workaround, you could style the parent node to look like the same from the start: https://jsfiddle.net/BlackLabel/6g2r1myj/1/

**Comment by KacperMadej** [comment]
@wootera 
Without the extra code it works and the same can be seen (working, and no bug) in the minimal demo posted in 2020.
https://jsfiddle.net/BlackLabel/6g2r1myj/12/
