### ISSUE TITLE
series.events.click is not fired via keyboard enter / return / space

### ISSUE THREAD

**Issue by ayrtonmassey** [highcharts/highcharts#14460]
#### Expected behaviour
If I add a click event under `series.events.click`:

```js
series: [{
        events: {
            click: () => alert("Clicked!")
        }
    }]
```

That event should be fired when I click on the series with the mouse, **or** when the series has the keyboard focus and I press enter / return / space.

#### Actual behaviour
The event is only fired when I click on the series. The event does not fire when I press enter / return / space.

If I add a click event under `series.point.events.click` that event *does* fire when I navigate to a point in the chart and press enter / return / space.

#### Live demo with steps to reproduce
Event does not fire on keyboard interaction with `series.events.click`:
http://jsfiddle.net/njb15qc2/

Event fires with mouse and keyboard interaction with `series.point.events.click`: 
http://jsfiddle.net/njb15qc2/1/

#### Product version
`highcharts.js` 8.2.0
`modules/accessibility.js` 8.2.0

#### Affected browser(s)
Google Chrome - Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @ayrtonmassey,
Thank you for reporting.

FYI @oysteinmoseng

**Comment by ayrtonmassey** [comment]
Thanks for the quick turnaround on the fix, guys. Much appreciated!
