### ISSUE TITLE
Outdated 'pattern-fill' API, tutorial, docs.

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#14465]
#### Actual behaviour
After reading this article https://www.highcharts.com/blog/tutorials/pattern-fills/ you might think that it is possible to use the default highcharts pattern by assigning `url(#highcharts-default-pattern-0)` to the `point.color` property. 

```
// https://www.highcharts.com/blog/tutorials/pattern-fills/

"(...)The module adds 10 default SVG patterns. These are used by referencing their IDs:
color:  'url(#highcharts-default-pattern-0)'"
```

It seems that it is not working. The demo that is included in the tutorial is using `color: { patternIndex: 0 }` and it is not working with the `color: "url(#highcharts-default-pattern-0)"`.

I was not able to find any mentions in the changelog, but the "new syntax" is working from `8.0.0`, and the last version that supported the previous one ('url(#highcharts-default-pattern-0') was `7.2.0`.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/43kLb0jt/ (current version)
https://jsfiddle.net/BlackLabel/7be1fywp/ (7.2.0)

#### Product version
8.2.2

#### Affected browser(s)
All

**Comment by PaulDalek** [comment]
_Additional information_
The introduction of the `patternIndex` is mentioned [here](https://www.highcharts.com/blog/changelog/#highcharts-v8.0.0) (the first element on the Bug Fixes list). Also, here is [the comment](https://github.com/highcharts/highcharts/pull/12577#issuecomment-562606374) that says about the backwards compatibility problem with setting patterns through `url(#...)`.

**Comment by pawelfus** [comment]
*Internal note:*
Update the article and check all related docs if we accidentally don't suggest deprecated API

**Comment by goransle** [comment]
Added notice to the blog post, linking to the documentation for current options. Closing this as the change was deliberate and introduced in a major release.
