### ISSUE TITLE
[Help] I have some questions about Packedbubble

### ISSUE THREAD

**Issue by Ruifeng-Wu** [highcharts/highcharts#14466]
I don't want to have an initialization animation for packed bubble, so I disabled the enableSimulation attribute. But doing so makes the page very stuck.

In addition, in the packed bubble with animation, sometimes the page will have some errors.

# Description of the feature

1. When there's a lot of data, some bubbles bounce all the time. So if I want to disable animation, what should I do?
2. If I disable enableSimulation to disable animation, can I disable the drag function of the bubble and just keep the interaction of the hover?
3. Any suggestions for errors in the picture?
<img width="469" alt="error" src="https://user-images.githubusercontent.com/25561978/97847174-24503400-1d2a-11eb-8488-9c2f3024b4aa.png">

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by pawelfus** [comment]
Hi @Ruifeng-Wu 

Thank for choosing Highcharts!

> When there's a lot of data, some bubbles bounce all the time. So if I want to disable animation, what should I do?

This it not an animation - when you set `enableSimulation = true` you see exactly what happens and how bubbles are positioned, step by step. Disabling it won't improve performance drastically, but just hide the bubbles moves. `enableSimulation = false` is only recommended for a small datasets.

> If I disable enableSimulation to disable animation, can I disable the drag function of the bubble and just keep the interaction of the hover?

Yes, you can. See details: https://api.highcharts.com/highcharts/series.packedbubble.draggable (demo: https://jsfiddle.net/BlackLabel/x4d83s70/ )

> Any suggestions for errors in the picture?

It's hard to say. Please, recreate issue in jsFiddle, we will check it.

**Comment by Ruifeng-Wu** [comment]
Hi @pawelfus 
Thank you for your reply. This is a react project. We used _highcharts-react-official_ and the problem cannot recurs steadily, it only occurs after the page is rendered. The code may needs some desensitization, please let me know if you have any guesses. 


We have used some code from the demo, and we are not sure if the usage is correct. Whether this will lead to the problem.
```
(function (H) {
  const { clamp } = H._modules['Core/Utilities.js']; // eslint-disable-line

  H.seriesTypes.packedbubble.prototype.calculateParentRadius = function () { // eslint-disable-line
    const series = this;
    let bBox;
    const parentPadding = 20;
    const minParentRadius = 70;

    bBox = series.seriesBox();  // eslint-disable-line
    series.parentNodeRadius = clamp(Math.sqrt(2 * series.parentNodeMass / Math.PI) + parentPadding, minParentRadius, bBox // eslint-disable-line
      ? Math.max(Math.sqrt(Math.pow(bBox.width, 2) // eslint-disable-line
        + Math.pow(bBox.height, 2)) / 2 + parentPadding, minParentRadius) // eslint-disable-line
      : Math.sqrt(2 * series.parentNodeMass / Math.PI) + parentPadding);
    if (series.parentNode) {
      series.parentNode.marker.radius = series.parentNode.radius = series.parentNodeRadius; // eslint-disable-line
    }
  };
}(Highcharts));
```

**Comment by Ruifeng-Wu** [comment]
`draggable` holds the bubble in place. Thanks @pawelfus

**Comment by pawelfus** [comment]
Code looks fine, I don't see anything wrong with the snippet above. If you use our official plugin, then you can recreate issue in stackblitz or something similar that supports building react apps.

As for the guesses, I would start with checking chart updates. Perhaps some update in done on the series that is broken? Using `highcharts.src.js` instead of `highcharts.js` would help too (so error will be a little more readable).

Great to hear at least `draggable` issue is solved! :)

**Comment by Ruifeng-Wu** [comment]
Thanks
