### ISSUE TITLE
Stacked column chart become normal after update if margin is set 

### ISSUE THREAD

**Issue by artemkasan** [highcharts/highcharts#14488]
Hallo,

I've faced to a problem with the stacked bar chart. I use the highcharts-react-official library to render charts. This library calls the chart update method after each rerender. After several updates the stacked bar chart become a simple bar chart where bars are rendered one behind another. But if I remove margin property from options everything start to work just fine.

#### Expected behaviour
The stacked bar chart always rendered as a stacked bar chart.

#### Actual behaviour
After the second chart update, the stacked bar chart become a simple bar chart. 

#### Live demo with steps to reproduce
https://jsfiddle.net/fj3pcb29/5/
Click on the "Break chart" two times after the second click columns start to render from the y point 0 instead of render one after another.

If remove the "margin" option everything start to work just fine.

#### Product version
Highcharts JS v8.2.2 

The bug was introduced in v8.1.1

#### Affected browser(s)
At least Chrome and Firefox

**Comment by PaulDalek** [comment]
Hi @artemkasan 

Thank you for reporting this issue. Issue related to #14453. Already fixed on the master.

**Simplified demo**
https://jsfiddle.net/BlackLabel/0fk4y6pa/
