### ISSUE TITLE
Add translation for word "week" to language options

### ISSUE THREAD

**Issue by Shelendra404** [highcharts/highcharts#14492]
Hello!

It would be nice to have the following feature available:
Add possibility to add translations to the word "week" to translations in language options (https://api.highcharts.com/gantt/lang)

Currently this is done on xAxis dateTimeLabelFormats, and in so doing, if one wants to have the top-level labels above it (month/year), it also requires labels formatter-function. Removing the formatter function also removes the top-level labels, and makes the chart quite hard to understand when date range is several years.

Using formatter function seems to, in some edge cases (which unfortunately I haven't been able to reproduce in a fiddle) break the way the top labels are shown, causing both duplicates entries and a shift in following entries. Without xAxis-modification, with the same code, the values are shown correctly. This seems to be due to different way of handling the leftmost-datetime-value, even though with debugging, the server returns exactly the value it should - the leftmost dates zero-time form (i.e. Mon 18 November 2019 00:00:00).

**Top value discrepancy bug while using formatter:**
![top-label-value-discrepancy](https://user-images.githubusercontent.com/58692281/98222236-3c59ca80-1f59-11eb-97e0-c79e364015e6.png)

Here is a fiddle that shows the used code used for making the custom top label [https://jsfiddle.net/rdocu8mz/8/](url). In this fiddle, as mentioned before, the top-label discrepancy doesn't get reproduced, it is merely to show there should be no weirdness in the formatter code itself.

Best regards,

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by PaulDalek** [comment]
Hi @Shelendra404

Thank you for reporting this issue and for proposing the feature. From what I have checked upper labels don’t disappear when getting rid of the formatter. Please, check the demo below and let me know if the issue still occurs on your side.

**Demo**
https://jsfiddle.net/BlackLabel/Lvnx4h16/

**Comment by Shelendra404** [comment]
Hi,

I noticed that in your example, the xAxis has dateTimeLabelFormats listed twice (one replacing the original formatter-function). Doubling up indeed allows for the top-level labels to appear, thank you! Getting rid of the formatter also miraculously fixed the issue with the left-most top label being duplicated and the rest of the labels being off by one.

That is a whole lot of headache from my side just gone :)

**So with the problems gone, I guess I will leave this thread to the part of "it would still be nice to have all translations in the language options". While not critical at all, it would still be prettier.** 

And I'll just pray I won't have to touch the formatter ever again, since the top label discrepancy bug was just... nope. I encountered some other bugs while fighting with this though, so I will check the issues list to see if they have been reported as of yet, and whether they still actually are an issues without the formatter-function.

Cheers

**Comment by PaulDalek** [comment]
Hi @Shelendra404

Ok, let’s leave it as a `Feature request`. As for the list of further issues that you encounter, please try to contact our support team first, using one of the [available support channels](https://www.highcharts.com/blog/support/).
