### ISSUE TITLE
The lastVisiblePrice label in price-indicator module overwrites the backgroudColor prop of crosshair label

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#14495]
When the LastVisiblePrice label is enabled, the crosshair label backgroudColor gets the value of the LastVisiblePlace label and ignores its own value. 
If LastVisiblePrice is not defined, then the crosshair label has correct color. 

Live demo: https://jsfiddle.net/BlackLabel/13qmwfkr/
Steps to reproduce:  
Hover the chart, and notice, that the crosshair label color is same, as the last defined LastVisiblePrice label color. 

Workaround: 
https://jsfiddle.net/BlackLabel/0qcwprjn/

#### Product version
 Highstock JS v8.2.2
#### Affected browser(s)
All

**Comment by PaulDalek** [comment]
_Internal note_
The code responsible for it can be found in the [`price-indicator`](https://code.highcharts.com/modules/price-indicator.src.js) module https://github.com/highcharts/highcharts/blob/a28de2d239475ae9c5788c6499a50d6953063ae7/js/Extensions/PriceIndication.js#L100-L102

The `this.options.crosshair` of the crosshair is the same as the merged options of the latest `lastVisiblePrice` label.
