### ISSUE TITLE
How to add zoom function for renderer.circle or renderer.rect？

### ISSUE THREAD

**Issue by lingjun1270** [highcharts/highcharts#14498]
the chart has zoomType，but if I want to draw circle and rect，there are no zoom function for the renderer.circle，How to add zoom function for renderer.circle or renderer.rect？

**Comment by pawelfus** [comment]
Hi @lingjun1270 

Thanks for using Highcharts! In general, if you have questions, please ask them on our forum, stackoverflow or cotact us directly (email), see details: https://www.highcharts.com/blog/support/

I'm not sure what do you mean that there is no zoom function for `renderer.circle()`. Perhaps you want to increase/decrease radius of a circle after zoom in/out? Then use `Axis.afterSetExtremes()` callback to update your circle with new radius. If that is not the case, please contact our support team.

Thanks!
