### ISSUE TITLE
Scrollbar can be moved to values outside the chart range

### ISSUE THREAD

**Issue by brnomendes** [highcharts/highcharts#14500]
#### Expected behaviour
With data starting at zero and, setting `min` and extremes `newMin` at zero, the scollbar shouldn't go beyond zero (to negative values).

#### Actual behaviour
In the demo, adding data from 0 to 3, when setting the `min` and `max` of the X axis to 0 and 3, and `setExtremes` to 0 and 2, it's possible to move the chart with the scrollbar to values outside the range of the `min` value.

Is there a workround that the user cannot move the scrollbar to negative values (for this demo)?

Note: In the demo, when changing the `tickAmount` to `10` the bug doesn't happen.

#### Live demo with steps to reproduce
https://stackblitz.com/edit/highcharts-8-ts-scrollbar-out-range

**Demo:** Clicking in arrow button and Dragging the scrollbar (after setting min/max and extremes).
![highcharts-scroll-out-range](https://user-images.githubusercontent.com/7743931/98358309-4507da80-2005-11eb-9c91-1a208b3ab89b.gif) ![highcharts-scroll-out-range-2](https://user-images.githubusercontent.com/7743931/98359025-5ac9cf80-2006-11eb-8f64-b4ab6fef1ac3.gif)

#### Product version
Highstock 8.2.2

#### Affected browser(s)
Google Chrome 84.0.4147.125 64 bits
Firefox 79.0 64-bit

**Comment by pawelfus** [comment]
Thank you for reporting this bug @brnomendes 

**Simplified demo:** (not related to scrollbar)
https://jsfiddle.net/BlackLabel/juo0hz3p/4/
Click on button, which will try setting extremes `(0, 1.99)` and -0.2 will be the minimum.

**Workaround:**
Setting different value for `tickAmount` is risky and depends on a dataset/chart dimensions (e.g. this is broken too: https://jsfiddle.net/BlackLabel/juo0hz3p/5/).

Instead use [`Axis.tickPositioner`](https://api.highcharts.com/highcharts/xAxis.tickPositioner) to filter out ticks that are outside the extremes: 
- https://stackblitz.com/edit/highcharts-8-ts-scrollbar-out-range-dd9hfs
- simplified: https://jsfiddle.net/BlackLabel/juo0hz3p/6/

*Internal note:*
Bisected to commit 4b0f2e30d4 - not really a regression, before that commit, that issue did not happen with `min` but with `max`.
On every action (button click, move step in drag&drop) extremes are slightly increased, growing indefenitely.
