### ISSUE TITLE
Threshold on bosxplot use max values instead of median values

### ISSUE THREAD

**Issue by CodeTroopers** [highcharts/highcharts#14507]
#### Expected behaviour
When a threshold is defined in options :
```
plotOptions: {
	series: {
		threshold: 90,
		negativeColor: '#ffaa00',
	}
}
```
And we use a boxplots chart, then boxplot with median under the threshold should be colored with negative color

#### Actual behaviour
Actually only boxplots with max values under the threshold are colored with negative color

#### Live demo with steps to reproduce
Demo : [https://jsfiddle.net/1mz94xhf/](https://jsfiddle.net/1mz94xhf/)

#### Product version
Highcharts : 8.2.0

**Comment by PaulDalek** [comment]
Hi @CodeTroopers

Thank you for reporting this issue. By default, the property that is used to determine if a point is negative (checks if it is smaller than the `threshold`) is `y`. There is an option called [`zoneAxis`](https://api.highcharts.com/highcharts/series.boxplot.zoneAxis) which is used with the [`zones`](https://api.highcharts.com/highcharts/series.boxplot.zones) functionality but setting it to 'median' will color box plot points as you expect.

**Simplified demo**
https://jsfiddle.net/BlackLabel/pjsrhL48/

**Comment by CodeTroopers** [comment]
@PaulDalek Thanks for your reply.

Is there a way to leave the part of boxplot above the threshold with the main color and to color the part under the threshold with the negative color (for a same boxplot)?

**Comment by PaulDalek** [comment]
@CodeTroopers

Currently it’s not possible to color a boxplot such a way using options. The only available options are to color each element of a boxplot separately.

**Demo**
https://jsfiddle.net/BlackLabel/qr3e6Lzp/
