### ISSUE TITLE
[Screen Reader - Power Apps Admin- Analytics]: Screen reader is not giving proper information when focus moves to chart bar graph.

### ISSUE THREAD

**Issue by rishuSrivastava11hcl** [highcharts/highcharts#14515]
### **Test Environment:**

- Version: 2004 (OS Build: 19041.508).
- Browser: Edge chromium Version 87.0.634.0 (Official build) dev (64-bit).
- Screen Reader: Narrator, NVDA
- #URL:https://admin.powerplatform.microsoft.com/

### **Repro Steps:​**

1. Open URL: https://admin.powerplatform.microsoft.com/ and login with valid credentials.
2. Power Platform Admin center page will get appear, navigate to 'Analytics' tab and expand it, Select Common Data Services tab .
3. Enable the narrator and navigate to all controls present under 'Active Users' tab in scan mode using down arrow key.
4. Navigate to first bar graph of 'Active users' chart and observe the screen reader behavior.
5. Verify the issue.

###  **Actual Result:**
Screen reader is not giving proper information when focus moves to chart bar graph.
When focus moves to first bar graph of 'Active users' chart, screen readers are reading as "Interactive chart toggle visibility series 1 Thursday, Sep 17, 11:00, 1 image".

 ### **Expected Result:**
Screen reader should give proper complete information when focus moves to all chart graphs.
When focus moves to first bar graph of 'Active users' chart, screen readers should read it as "Active Users Interactive chart toggle visibility series Thursday, Sep 17, 11:00, Active users 1 image".

**ScreenShot:NA**

### **Note:**

1. Same issue also exist with 'Firefox + NVDA'.
2. Same issue also exits for all the graph charts of 'Mode of Access' tab section.

### **WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships

**Comment by rishuSrivastava11hcl** [comment]
#Accessibility;#WCAG1.3.1;#HCL;#HCL-PowerAppsAdminCenter;#A11ySev2;#Benchmark

**Comment by PaulDalek** [comment]
Hi @rishuSrivastava11hcl

Thank you for reporting this issue. If you can, please provide us with a live example (e.g. JSFiddle) where this behavior can be recreated. Thanks!

FYI @oysteinmoseng

**Comment by sebastianbochan** [comment]
Closed due to inactivity.

**Comment by rishuSrivastava11hcl** [comment]
> Hi @rishuSrivastava11hcl
> 
> Thank you for reporting this issue. If you can, please provide us with a live example (e.g. JSFiddle) where this behavior can be recreated. Thanks!
> 
> FYI @oysteinmoseng

![image](https://user-images.githubusercontent.com/72869551/117441921-b04e4d00-af53-11eb-8d65-eac0e95caf25.png)

**Comment by KacperMadej** [comment]
I am not sure if we are able to check this issue without a live demo. If you could share the chart's configuration and used version of Highcharts then we might be able to try recreating the problem.

**Comment by oysteinmoseng** [comment]
@rishuSrivastava11hcl It looks like you want to configure what the accessible text of data points are. If so, take a look in our documentation for [configuring the accessibility module](https://www.highcharts.com/docs/accessibility/configure-the-accessibility-module). This will allow you to customize the information that screen readers read for data points. Highcharts tries to be smart by default, but sometimes you will have to do a bit of configuration to get things right.

**Comment by oysteinmoseng** [comment]
Closing this for now, feel free to comment to reopen.

**Comment by v-ajrai** [comment]
Hi @oysteinmoseng 
Can you please provide information about which props(property) we need to set to add legend name inside bar chart aria label.
![image](https://user-images.githubusercontent.com/62233982/133066076-fca582d4-bf39-4065-9706-ccc55ffcd5ed.png)

**Comment by rishuSrivastava11hcl** [comment]
Hi @oysteinmoseng ,

As per above ask "Can you please provide information about which props(property) we need to set to add legend name inside bar chart aria label." 
Could you please provide some reference on same?

**Comment by oysteinmoseng** [comment]
Hi, @rishuSrivastava11hcl and @v-ajrai. 

The series name (the name displayed in the legend) is added by default in recent versions of Highcharts, if you have multiple series in the chart.

You can customize the content of the aria-labels on points in many ways, including [point.valueDescriptionFormat](https://api.highcharts.com/highcharts/accessibility.point.valueDescriptionFormat), or [point.descriptionFormatter](https://api.highcharts.com/highcharts/accessibility.point.descriptionFormatter) if you need more control.

Also see the Accessibility configuration tutorial linked above: https://www.highcharts.com/docs/accessibility/configure-the-accessibility-module.

**Comment by v-ajrai** [comment]
Hi @oysteinmoseng we are trying to use the properties  valueDescriptionFormat and valueSuffix as you suggested ,but we are not able to override this property. Can you please suggest any alternative approach that need to implement inside conditional statement as below.

    if (options.series[i].name == 'Bar1Name') {
     options.accessibility.valueSuffix ="overriding value suffix"; 
     options.accessibility.valueDescriptionFormat="overriding valueDescriptionFormat";   
    }

**Comment by oysteinmoseng** [comment]
@v-ajrai Could you please contact support at support@highcharts.com and send them a demo of your case, or at least all the information you can provide? This way we can help you better.

**Comment by v-ajrai** [comment]
@oysteinmoseng for other graphs we are able to get the correct aria-label for the bars that also read legend name with point . But for one particular graph we are  not able to override the properties you shared. We tried to set value description format as per below code snippet.
But still we not found legend name inside aria-label.
![image](https://user-images.githubusercontent.com/62233982/133772748-1245f01f-bc2b-474e-91fb-4723ca0eee5d.png)

![image](https://user-images.githubusercontent.com/62233982/133772593-3a85b6d6-03b5-4d00-9a8a-b04731aa13e4.png)

**Comment by raf18seb** [comment]
> @v-ajrai Could you please contact support at support@highcharts.com and send them a demo of your case, or at least all the information you can provide? This way we can help you better.

@v-ajrai have you contacted our technical support with your issue?

**Comment by raf18seb** [comment]
> @v-ajrai Could you please contact support at [support@highcharts.com](mailto:support@highcharts.com) and send them a demo of your case, or at least all the information you can provide? This way we can help you better.

@v-ajrai have you contacted our technical support with your issue?
