### ISSUE TITLE
Incorrect clip path with multiple panes

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14522]
#### Expected behaviour
Create identical clip-paths in Stock and in Chart.

#### Actual behaviour
In the Chart, the clip-path is generated globally for the whole chart.

#### Live demo with steps to reproduce
Zoom in to see the difference.
Chart: http://jsfiddle.net/BlackLabel/27n8mt9u/
Stock: http://jsfiddle.net/BlackLabel/ecp1qgzv/

#### Product version
Highcharts / Highstock JS v8.2.2 (2020-10-22)

#### Affected browser(s)
All

**Comment by gbenthomas** [comment]
Hello, we encountered a similar issue with multiple panes. The axes and series are added dynamically and a `min` is set on the yAxis.
![image](https://user-images.githubusercontent.com/35936423/98841868-54749280-240e-11eb-9e5b-738ad0b63e70.png)

I was also able to reproduce this by modifying the candlestick and volume demo to dynamically add the axes and series: https://jsfiddle.net/51mo3x8b/1/

Do you think this is the same issue or should I open a new issue?

**Comment by karolkolodziej** [comment]
Thanks for bringing out attention to this, but it looks like a separate issue. 
Most likely it's regression after some changes in the 8.0.3 version.
I've created a ticket here #14549

**Comment by karolkolodziej** [comment]
Fixed in v9.3.0
