### ISSUE TITLE
Can't select custom date within range

### ISSUE THREAD

**Issue by nunoarruda** [highcharts/highcharts#14535]
#### Expected behaviour
Able to select a custom date within the range

#### Actual behaviour
Can't select a custom date within the range, date input gets reverted back to the previous date:
![range-select](https://user-images.githubusercontent.com/1189149/98709996-a36cea00-2372-11eb-83d7-8adbfeae9db8.gif)

Am I missing something or is this a possible issue/bug with Highcharts?

#### Live demo with steps to reproduce
https://jsfiddle.net/nunoarruda/hbgovnkc/17/

1. Click inside the "From" input
2. Try changing the date from `2020-01-15` (January 15, 2020) to `2020-02-15` (February 15, 2020)

#### Product version
Highstock JS v8.2.2 (2020-10-22)

#### Affected browser(s)
All of them

**Comment by PaulDalek** [comment]
Hi @nunoarruda

Thank you for reporting this issue. The cause of this behavior is that the default [`minRange`](https://api.highcharts.com/highstock/xAxis.minRange) calculated for this data is about 4 months. It prevents from decreasing the visible range. To resolve this problem you can set the `minRange` explicitly with some smaller value (for example one day).

**Demo**
https://jsfiddle.net/BlackLabel/7ud0L2gb/
