### ISSUE TITLE
Multiple panes don't create correct clip-path for dynamically added axis

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14549]
#### Expected behaviour
Create clip-path for dynamically added axis the same as for static.
This feature works correctly in the 8.0.2 version.
Demo: https://jsfiddle.net/BlackLabel/pqco92kv/

#### Actual behaviour
Series clip-path exceeds the axis when it's added dynamically.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/n91a3rmw/

#### Product version
Highstock JS v8.2.2 (2020-10-22)

#### Affected browser(s)
All

**Comment by PaulDalek** [comment]
_Internal note_
Bisect led to this commit ef8d54df5e0fc1c1567ff9ce30bd34e30d6109a1.
