### ISSUE TITLE
PointPadding for treemap, docs error

### ISSUE THREAD

**Issue by K009** [highcharts/highcharts#14552]
#### Expected behaviour
In the documentation, it is said that we can set pointPadding in the treemap series. 
https://api.highcharts.com/highcharts/series.treemap.data.pointPadding 

#### Actual behaviour
This property does not work for this kind of series. Probably it was meant for the tilemap series.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/2trzouwy/

#### Product version
8.2.2

#### Affected browser(s)
All

**Comment by BDRobin** [comment]
Running into this problem as well. Any updates on a fix?

**Comment by raf18seb** [comment]
Hi @BDRobin! We will fix the docs as soon as it's possible. However, it's only an API issue - the `data.pointPadding` property will not be implemented for the treemap and the heatmap series.

**Comment by BDRobin** [comment]
Oh! Alright, good to know! 

So the treemap items don't have a way to change the spacing between them like the tilemap items do?

**Comment by raf18seb** [comment]
@BDRobin,

By API - no. You can extend the core and define your own padding e.g. this way: https://jsfiddle.net/BlackLabel/zqjh5ne6/

**Comment by raf18seb** [comment]
@BDRobin actually I made a mistake. The `data.pointPadding` is implemented in the heatmap and is working fine! The issue concerns only the treemap series.
