### ISSUE TITLE
shift option in function addPoint dont work in Highstock

### ISSUE THREAD

**Issue by guisimon28** [highcharts/highcharts#14560]
Hi Highchart team,

we use highstock to real time consumption for our client. So we use addPoint functionnality to insert live data in chart.
The shift parameter seems to not be used in highstock as you can see : https://jsfiddle.net/vLfawm3g/

regards,

**Comment by PaulDalek** [comment]
Hi @guisimon28

Thank you for reporting this issue. From what I have checked, the `shift` parameter works as expected. In your demo it is set to `false`. If you change the position of the `navigator` to the beginning of the whole data range, you will see that the first point isn’t removed. You can see it more clearly when you decrease the number of points.

**Demo**
https://jsfiddle.net/BlackLabel/hmc5sad7/
