### ISSUE TITLE
Highcharts background width and height is always smaller

### ISSUE THREAD

**Issue by pwang2** [highcharts/highcharts#14571]
#### Expected behavior
As below, hightcharts container always rounds the parent container dimensions to an integer number. This cause some subpixel alignment issue as described in actual behavior. 
![image](https://user-images.githubusercontent.com/1592014/99137544-1daaa200-25f1-11eb-83ee-374859aa9db5.png)

I know for canvas, we can not assign subpixel as width/height, but not a restriction for SVG. https://jsfiddle.net/c0xewk69/ 
```
"canvas", [object DOMRect] {
  bottom: 308.796875,
  height: 300,
  left: 8,
  right: 308,
  toJSON: function toJSON() { [native code] },
  top: 8.796875,
  width: 300,
  x: 8,
  y: 8.796875
}
"svg", [object DOMRect] {
  bottom: 308.796875,
  height: 300.796875,
  left: 312,
  right: 612.796875,
  toJSON: function toJSON() { [native code] },
  top: 8,
  width: 300.796875,
  x: 312,
  y: 8
}
```
#### Actual behaviour
These 2 charts are in a gutterless grid which should touch each other.
![image](https://user-images.githubusercontent.com/1592014/99137232-fb178980-25ee-11eb-8df7-b57d63725ad8.png)

#### Live demo with steps to reproduce
Any demo

#### Product version
8.2.2

**Comment by PaulDalek** [comment]
Hi @pwang2

Thank you for reporting this issue. Could you please provide us with a simplified live demo where this behavior can be seen? From what I have checked both, parent and container divs have the same `height`.

**Demo**
https://jsfiddle.net/BlackLabel/ogxe2np1/

**Comment by pwang2** [comment]
https://jsfiddle.net/tpq1x8gy/
I think the width is the issue here. 

![image](https://user-images.githubusercontent.com/1592014/99419932-44532c00-28c2-11eb-878b-e16773252083.png)

**Comment by PaulDalek** [comment]
@pwang2

In a nutshell, inside the `getStyle` function, the `floor` action is performed on the `boundingClientRectWidth` property which results in a shorter container’s width. It works like that because the `scrollWidth` (which is used to determine the size of the container) doesn't support the subpixel precision. For more information take a look at this [comment](https://github.com/highcharts/highcharts/issues/6427#issuecomment-435881777) (and the whole thread).

**Comment by pwang2** [comment]
@PaulDalek 
Thanks for your comment.  Yes. that's exactly the case here. That thread actually helped me reason another issue better related to resizing .  I will close this issue and subscribe that thread for any further update. Thanks again.
