### ISSUE TITLE
Bar chart with reversed: false attribute on X axis reverts keyboard arrow navigation

### ISSUE THREAD

**Issue by Scumble** [highcharts/highcharts#14577]
Expected behaviour:
Disabling reversed attribute on X axis should not lead to reversing of keyboard arrow navigation

Actual behaviour: 
Disabling reversed attribute on X axis leads to reversing of keyboard arrow navigation

Live demo with steps to reproduce:
https://jsfiddle.net/wvmyfjae/

Product version:
highcharts: 8.0.4

Affected browser(s):
Google Chrome Version 86.0.4240.193 (Official Build) (64-bit)

**Comment by PaulDalek** [comment]
Hi @Scumble

Thank you for contacting us and reporting this issue.

FYI @oysteinmoseng
