### ISSUE TITLE
Sankey chart, overlapping data labels link doesn't work

### ISSUE THREAD

**Issue by hihajdus** [highcharts/highcharts#14584]
#### Expected behavior
When overlapping is set to false data labels links should not be overlapped.
This feature works correctly in the 8.0.0 version.
Demo: [https://jsfiddle.net/BlackLabel/e0kxn56c/](https://jsfiddle.net/BlackLabel/e0kxn56c/)

#### Actual behaviour
Data labels links are overlapped when overlapping is set to false.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8gx1yhtu/

#### Product version
Highcharts JS v8.2.2 (2020-10-22)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Bisected to commit 6dc7be2b8d

**Comment by TorsteinHonsi** [comment]
Please see https://github.com/highcharts/highcharts/pull/14622 for a suggested fix.
