### ISSUE TITLE
Add Jump line charts support to high charts

### ISSUE THREAD

**Issue by EzzahWaseem** [highcharts/highcharts#14581]
# There is no such type in high charts for making jump line charts . Add jump line chart support to it too 

# [https://www.highcharts.com/](https://www.highcharts.com/)

----

Refer to this issue
[https://stackoverflow.com/questions/64870773/jump-line-charts-in-high-charts](https://stackoverflow.com/questions/64870773/jump-line-charts-in-high-charts)

**Comment by pawelfus** [comment]
Hi @EzzahWaseem 

Thanks for sharing the idea.

You can create that kind of a chart using:
- [Bullet graphs](https://www.highcharts.com/demo/bullet-graph)
- [Bar series](https://www.highcharts.com/demo/bar-basic) with [Columnrange series](https://www.highcharts.com/demo/columnrange)
- or by combining [Bar series](https://www.highcharts.com/demo/bar-basic) and [Scatter series](https://www.highcharts.com/demo/scatter) with a [custom marker](https://api.highcharts.com/highcharts/series.scatter.marker.symbol) on the same chart

**Comment by EzzahWaseem** [comment]
Hi @pawelfus 

Thanks for suggesting me this. I'll try this and let you know
