### ISSUE TITLE
Implement donuts chart nodes in Network Graph.

### ISSUE THREAD

**Issue by Max2131970** [highcharts/highcharts#14588]
It could be an idea for you to expand highcharts potencial. Donuts Charts in Network Graph Nodes as you can see in attached image. 
![graph](https://user-images.githubusercontent.com/74265295/99389010-afa6f900-28d6-11eb-8c4e-e7ffd2ce071a.png)

**Comment by PaulDalek** [comment]
Hi @Max2131970 

Thank you for contacting us and proposing this feature.

**Comment by pawelfus** [comment]
Related issue: #12526
