### ISSUE TITLE
plotOptions.series.threshold Typescript type does not accept null

### ISSUE THREAD

**Issue by mlo42** [highcharts/highcharts#14583]
#### Expected behaviour
plotOptions.series.threshold can be set to null in order to automatically scale the y-axis according to the data shown, not e.g.  have as lower limit default 0 but a value close to the minimum value of the data.

#### Actual behaviour
plotOptions.series.threshold cannot be set to null, since typescript definition only allows Number and undefined.

#### Live demo with steps to reproduce
I copied this example from https://github.com/highcharts/highcharts/issues/12824, where the problem seems to be solved at least for some cases. "threshold: null" cannot be used when using typescript.

Highcharts.chart('container', {
    xAxis: {
    	categories: ['Apples', 'Pears', 'Bananas', 'Oranges']
    },
    series: [{
        data: [101, 104, 103, 105],
        type: 'area',
        threshold: null
    }]
});

#### Product version
8.2.2

#### Affected browser(s)
Has nothing do with a browser.

**Comment by pawelfus** [comment]
Thank you for reporting the issue @mlo42 

Could you check it once again? It seems that `null` is accepted, simple demo: https://stackblitz.com/edit/typescript-zsvueb

FYI @bre1470

**Comment by mlo42** [comment]
Thank you for your quick answer @pawelfus.

Hm, that's strange, perhaps I got the wrong attribute. Perhaps a screenshot of my problem will help to identify the right one:
![Screenshot 2020-11-17 at 13 42 22](https://user-images.githubusercontent.com/61318387/99391825-0b738100-28db-11eb-8b2a-7469f06cf438.png)

**Comment by pawelfus** [comment]
Did not help, sorry :( 

Could you share your **actual config**, instead of the one posted above? Feel free to test it first in my demo, thanks! :)

**Comment by mlo42** [comment]
Ok, I think the problem is not that Highcharts does not accept it, since when I copy my code as simplified as possible into your demo, there is also no complain. Only ESLint complains since "threshold" (highcarts.d.ts: PlotSeriesOptions.threshold) only does have type "number | undefined" but also needs "null".

>> actual config
Since I'm not very advanced with Highcharts I'm sorry I cannot reduce our rather complex example to work within your demo within a fair amount of time. This the closes I came in which "threshold" is used, but as I wrote above, there is no complain in the demo:

```
const options_3: Options = {
    plotOptions: {
      column: {
        pointPlacement: 'between',
      },
      series: {
        threshold: null,
        lineWidth: 2.5,
        states: {
          hover: {
            lineWidthPlus: 1,
          },
        },
        shadow: {
          offsetY: 2,
          opacity: 0.01,
          width: 10,
        },
      },
      area: {
        fillOpacity: 1,
      },
    },
    series: <insert data in here>,
  };

```

**Comment by bre1470** [comment]
@mlo42 Thank you for the feedback. I believe I found the problem of the type inconsistency and will fix it.
