### ISSUE TITLE
Series.setData is undocumented

### ISSUE THREAD

**Issue by Martin-Nyaga** [highcharts/highcharts#14598]
#### Expected behaviour
`Series.setData` should be documented in the latest API docs [here](https://api.highcharts.com/class-reference/Highcharts.Series). 

#### Actual behaviour
`Series.setData` is undocumented. It's unclear if this is intentional, as the documentation for `Series.update` refers to it.

#### Live demo with steps to reproduce
[URL](https://api.highcharts.com/class-reference/Highcharts.Series)

#### Product version
API Docs build:    
v8.2.2 - Generated from branch master (commit 4f52c155c), on Thu Oct 22 2020 10:59:02 GMT+0200 (sentraleuropeisk sommertid)

#### Affected browser(s)
N/A

**Comment by PaulDalek** [comment]
Hi @Martin-Nyaga

Thank you for reporting this issue. I agree, the `setData` should be documented in the API (it is documented in the source).

**Comment by khlieng** [comment]
New API docs have been deployed.
