### ISSUE TITLE
panning.type = 'y' or 'xy' sometimes messes up aligned y-axes

### ISSUE THREAD

**Issue by javolio** [highcharts/highcharts#14624]
#### Expected behaviour
Enabling or disabling y-axis panning should not impact y-axis tick positioning of aligned axes when the chart has not been panned and is fully zoomed out. Data in a series mapped to an automatically-sized axis should not be out of view.

#### Actual behaviour

If the panning type is "xy" or "y" and there are two or more y-axes, with automatic bounds but set to startOnTick and endOnTick, the extrema may not be calculated correctly, and data will be drawn off-screen. Whether or not they will be drawn correctly depends on the data and on the vertical space allocated to the chart.

#### Live demo with steps to reproduce
Demo: https://jsfiddle.net/vjub85az/9/

Observe that the data from series y goes off the bottom of the chart; it should not.

Modify the values set in the first two lines to test different panning configurations. The data problem exists with panningType = "xy" or "y" but not "x". panningEnabled = true or false has no impact.

#### Product version
Highcharts JS v8.2.2

#### Affected browser(s)
Chrome, Firefox, and Safari; others not tested

**Comment by pawelfus** [comment]
Thank you for reporting this bug @javolio 

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/4eohdfky/

```js
(function(H) {
  H.wrap(
    H.Axis.prototype,
    'hasVerticalPanning',
    function(proceed) {
      return this.chart.options.chart &&
        this.chart.options.chart.panning &&
        this.chart.options.chart.panning.enabled === true &&
        proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    }
  )
})(Highcharts);
```

*Internal note:*
As in the workaround, `hasVerticalPanning` should not only check the panning type, but also if panning is enabled.

**Comment by javolio** [comment]
https://jsfiddle.net/2hz349v6/

The workaround fixes part of the issue. However, having vertical panning enabled (via `panning.type = 'xy'` or `'y'` and `panning.enabled = true`) still results in data being drawn out of bounds.

Furthermore, I've just noticed that if you shift + drag on the chart in the example--a non-zoomed chart--it will think the chart has been panned, and display the "Reset Zoom" button, though it doesn't actually pan (as it shouldn't, being fully zoomed out). I can make a separate issue for that if desired.

**Comment by pawelfus** [comment]
> The workaround fixes part of the issue. However, having vertical panning enabled (via panning.type = 'xy' or 'y' and panning.enabled = true) still results in data being drawn out of bounds.

Good point. It should look like this: https://jsfiddle.net/BlackLabel/3w2ucrms/

Because `startOnTick` and `endOnTick` as per documentation should be disabled: https://api.highcharts.com/highcharts/yAxis.endOnTick

> Furthermore, I've just noticed that if you shift + drag on the chart in the example--a non-zoomed chart--it will think the chart has been panned, and display the "Reset Zoom" button, though it doesn't actually pan (as it shouldn't, being fully zoomed out). I can make a separate issue for that if desired.

Yes, please. Thank you!
