### ISSUE TITLE
`useHtml` converts HTML attributes to lower case

### ISSUE THREAD

**Issue by metaloha** [highcharts/highcharts#14638]
#### Expected behaviour
HTML attributes remain as entered.

#### Actual behaviour
HTML attributes are being lower-cased.

Some libraries (like PrimeNg's tooltips) are case-sensitive when it comes to attaching events to HTML attribute tags. For example, `pTooltip` will appear as `ptooltip` which prevents PrimeNG tooltips from working.

#### Live demo with steps to reproduce
https://jsfiddle.net/vtxbrq3n/

#### Product version
Highcharts 8.2.2

#### Affected browser(s)
Chrome 87

**Comment by pawelfus** [comment]
Hi @metaloha 

Thank you for reporting this issue. AFAIK html attributes are case insensitive, so for example: `getAttribute('pTooltip')` and `getAttribute('ptooltip')` are equal, `document.querySelectorAll('span[pTooltip]')` and `document.querySelectorAll('span[ptooltip]')` return the same node lists. You can't have both at the same time: https://jsfiddle.net/BlackLabel/kn2wuv8r/ 

Could you report this issue to `PrimeNg` authors? It seems they did not pick some tags somehow (perhaps the ones created after initializing?). Checking this HTML: https://stackblitz.com/edit/primeng-tooltip-demo - seems that tags are lower case in HTML.

**Comment by metaloha** [comment]
You're right, this is likely a PrimeNG problem. It's not an initialization problem though, because if you use `ptooltip` instead of `pTooltip`, the tooltip will not appear (or possibly, there are two problems 🤷 ).

Thanks for checking!
