### ISSUE TITLE
Regression issue with series.pointPlacement since v8.0

### ISSUE THREAD

**Issue by praveenvitara** [highcharts/highcharts#14637]
#### Expected behaviour
when pointPlacement is set to "between" for line series, point marker should be placed between the ticks on the category axis.

#### Actual behaviour
when pointPlacement is set to "between" for line series, point markers are placed on the tick.

#### Live demo with steps to reproduce
https://jsfiddle.net/praveenx9/p2L597tz/48/

#### Product version
Highcharts 8.0

#### Affected browser(s)
Chrome

**Comment by PaulDalek** [comment]
Hi @praveenvitara

Thank you for reporting this issue. It is a regression since v8.0.1.

**Simplified demo**
https://jsfiddle.net/BlackLabel/m7epf2xh/

Bisected to commit: https://github.com/highcharts/highcharts/commit/a9326b2e6b35f33c869cfcc825840924aea3ec7e
