### ISSUE TITLE
Tooltip doesnot display if point is outside plot.

### ISSUE THREAD

**Issue by auoiuiouio** [highcharts/highcharts#1464]
I am using highstock-1.2.4. I have set zoomtype: x and xAxis.minRange=1sec. My issue is, consider I have data for a day where points are at an interval of 2-3 hours. Using navigator handler I zoom the graph to get 10 mins graph. I do zooming at the middle of two points. Now if I hover over the graph I don't get tooltip (since the points are too far from plot area). 

Please see this example: http://jsfiddle.net/rdBKp/1/
![Screenshot1](https://f.cloud.github.com/assets/2162482/85858/ba5bb8fe-647b-11e2-9507-f383603da4d4.png)
![Screenshot2](https://f.cloud.github.com/assets/2162482/85860/c4970076-647b-11e2-9068-30df9ac12e73.png)

**Comment by TorsteinHonsi** [comment]
Closing this - the tooltip is not expected to display for points outside the plot area.
