### ISSUE TITLE
Error: <g> attribute transform: Expected number, "…late(0,0) scale(NaN NaN)"

### ISSUE THREAD

**Issue by MisterSingh** [highcharts/highcharts#14642]
#### Expected behaviour
Draw country level charts

#### Actual behaviour
Error: <g> attribute transform: Expected number, "…late(0,0) scale(NaN NaN)"
https://jsfiddle.net/mv06xshy/
#### Product version

Highmaps: highcharts@6

#### Affected browser(s)
Chrome

**Comment by PaulDalek** [comment]
Hi @MisterSingh

Thank you for reporting this issue. This is not a bug. As you can read in the API, the [`map`](https://api.highcharts.com/highmaps/chart.map) property can be set as a string which acts as a property name of an object that contains GeoJSON.

**Demo**
https://jsfiddle.net/BlackLabel/u2s7Lg3r/
