### ISSUE TITLE
 problem with not cleared marker point after zoomed out

### ISSUE THREAD

**Issue by ashwiniIot** [highcharts/highcharts#14641]
zoom in until we see markers
reset zoom and don't move mouse
you can still observe markers from previously zoomed range (shouldn't that be cleaned in reset zoom?)
original points (series.points) are correct, but in chart.hoverPoints we still have a point from the old range - but point.graphic was destroyed (nullified points). Interesting part: that marker is still visible..
```
 xAxis: {
      type: 'linear',
      crosshair: true,
      labels: {
        autoRotation: false,
        formatter: xAxisFormatter,
      },
      events: {
        afterSetExtremes(event) {
          const enabled = event.min !== undefined;
          this.series[0].update({
            marker: {
              enabled,
            },
          });
        },
      },
    },
```

**Comment by pawelfus** [comment]
@ashwiniIot 

Could you please follow our template when reporting a bug? Thank you.

Missing details:
- Highcharts version
- Affected browsers
- Live demo

I tried to reproduce your issue, but it seems fine: http://jsfiddle.net/BlackLabel/oghnmpew/

**Comment by ashwiniIot** [comment]
hello sir,
  please my high chart versions-:
  "highcharts": "^8.0.4",
  "highcharts-react-official": "^3.0.0",

I fixed that issue after the zoom marker will get clear, but I am facing another issue, when I zoom in the chart sometimes unable to show markers ..unable to send jsfiddle sending complete config file 

`export const lineChartConfig_live_data = (
  unit: string,
  setExtremes: Highcharts.AxisSetExtremesEventCallbackFunction | undefined,
  data:
    | (
        | number
        | [string | number, number | null]
        | Highcharts.PointOptionsObject
        | null
      )[]
    | undefined
): Highcharts.Options => {
  const MAX_POINTS = 550;
  return {
    lang: {
      noData: 'No data found',
    },
    noData: {
      style: {
        fontWeight: 'bold',
        fontSize: '15px',
      },
    },
    chart: {
      animation: true,
      zoomType: 'x',
      events: {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        load(event: any) {
          console.log('***inside load');

          const { series } = this;
          if (series[0]?.points.length < MAX_POINTS) {
            series[0]?.update({
              marker: {
                enabled: true,
              },
            });
          }
        },
      },
      resetZoomButton: {
        position: { align: 'right' },
        // position: {
        //   x: 0,
        //   y: 0,
        // },
      },
    },
    title: {
      text: '',
    },
    xAxis: {
      type: 'linear',
      tickPixelInterval: 150,
      // tickInterval: 24 * 3600,
      crosshair: true,
      labels: {
        autoRotation: false,
        formatter: xAxisFormatter,
      },
      events: {
        afterSetExtremes(zoomAxis) {
          console.log('***inside afterset extreme');
          const { min } = zoomAxis;
          const { max } = zoomAxis;
          const axis = zoomAxis.target;
          const { chart } = axis;
          let visiblePoints: any = 0;
          // eslint-disable-next-line func-names
          Highcharts.each(axis.series, function(obj) {
            // eslint-disable-next-line func-names
            Highcharts.each(obj.data, function(p: any) {
              if (p.x >= Math.round(min) && p.x <= Math.round(max)) {
                visiblePoints += 1;
              }
            });
          });
          if (visiblePoints > MAX_POINTS) {
            chart.series[0]?.update({
              marker: {
                enabled: false,
              },
            });
          }
        },
        setExtremes,
      },
      minRange: 1,
    },
    tooltip: {
      // shared: true,
      useHTML: true,
      formatter: TooltipFormatter,
    },
    time: {
      useUTC: false,
    },
    yAxis: [
      {
        title: {
          text: unit,
        },
        height: '75%',
        labels: {
          align: 'left',
          x: -3,
        },
        plotLines: [
          /* {
            color: 'red',
            dashStyle: 'Dash',
            value: 60,
            zIndex: 2,
          }, */
        ],
      },
    ],
    rangeSelector: {
      enabled: false,
      buttonPosition: {
        align: 'right',
        x: -25,
      },
      buttonTheme: {
        // styles for the buttons
        fill: 'none',
        stroke: 'none',
        'stroke-width': 0,
        style: {
          fontWeight: 'bold',
        },
        states: {
          hover: {
            fill: 'none',
          },
          select: {
            fill: 'none',
            style: {
              color: 'white',
            },
          },
          // disabled: { ... }
        },
      },
      inputBoxBorderColor: 'gray',
      inputBoxWidth: 120,
      inputBoxHeight: 18,
      inputStyle: {
        color: '#00b1c1',
        fontWeight: 'bold',
      },
      buttons: [
        {
          type: 'all',
          text: 'Reset',
        },
      ],
      inputEnabled: false,
      labelStyle: {
        display: 'none',
      },
    },
    scrollbar: {
      liveRedraw: false,
    },
    exporting: {
      enabled: false,
    },
    navigator: {
      enabled: false,
      adaptToUpdatedData: true,
      xAxis: {
        type: 'linear',
        labels: {
          formatter: xAxisFormatter,
        },
      },
    },
    credits: {
      enabled: false,
    },
    // plotOptions: {
    //   // line: {
    //   //   marker: {
    //   //     enabled: false,
    //   //   },
    //   // },
    // },
    series: [
      {
        // boostThreshold: 1,
        data,
        // boostThreshold: 1,
        pointStart: 1329163200000,
        pointInterval: 1000 * 3600, // * 24,
        type: 'line',
        name: 'AI1',
        showInLegend: false,
        cropThreshold: 1000,
        // marker: {
        //   enabled: false,
        //   states: {
        //     hover: {
        //       enabled: false,
        //     },
        //   },
        // },
        tooltip: {
          valueDecimals: 2,
        },
        dataGrouping: {
          enabled: false,
        },
      },
    ],
  };
};
`


![Screenshot from 2020-12-02 11-26-14](https://user-images.githubusercontent.com/30647505/100842615-1dd6e880-349f-11eb-9e20-d89cbc2993cc.png)

**Comment by pawelfus** [comment]
Hi @ashwiniIot 

Could you please contact our support team first? See: https://www.highcharts.com/blog/support/

We use GitHub issues as bug reports and feature requests only :)

Thanks!
