### ISSUE TITLE
Update flag fillColor

### ISSUE THREAD

**Issue by munasinghecm** [highcharts/highcharts#14649]
#### Expected behaviour
In a flag array, I change the portion of the same flag array that includes the fill color method as well. When I change the portion of the array everything should be updated including the fill color.

#### Actual behaviour
In a flag array, I change the portion of the same flag array that includes the fill color method as well. When I change the portion of the array everything updated except the fill color. The fill color change only when I hover the mouse over each and every changed flag. Do you have a method to change the fill color without hovering each flag when I change the portion of the flag array?

#### Live demo with steps to reproduce

Here the JSFiddle regarding my concern. Here initially all flags are in green color, then when clicks on the button "Change Flag" the first two buttons change their title from A to B but the fillColor does not change. But in the array, I change the fillColor to blue. BTW when hovering the flags the color change to blue.

https://jsfiddle.net/munasinghecm/32qLdhr7/36/

How can I change the fillColor when the button click event happens without hovering over flags?
#### Product version

highcharts-angular "2.8.2"
highcharts: "8.2.2"

**Comment by munasinghecm** [comment]
From which version is it available

**Comment by khlieng** [comment]
It will be in the next release.

**Comment by munasinghecm** [comment]
Thank You
