### ISSUE TITLE
Disappearing borderRadius on mouseover of column where data point has borderRaidus

### ISSUE THREAD

**Issue by GCheung55** [highcharts/highcharts#1466]
Where a datapoint has a borderRadius, hovering over it in a column chart causes the borderRadius on the datapoint to disappear.

Example: http://jsfiddle.net/dcPdP/

First data point in Monday series has borderRadius: 5. Hovering over that data point causes the border radius rule to be disregarded.

**Comment by pawelfus** [comment]
*Internal note:*
Shouldn't we replace `borderRadius` option with [Rounded-Corners](http://www.highcharts.com/plugin-registry/single/5/Rounded-Corners) plugin?

**Comment by highslide-software** [comment]
Maybe... It would add some weight though. Do you feel this is a frequently requested feature?

**Comment by pawelfus** [comment]
I thought rather by disabling `borderRadius` in the core and in the API add link to that plugin instead. Rounded corners is much better than `borderRadius`, even in the example you can see workaround to set radius only for top of the rect.

**Comment by KacperMadej** [comment]
`borderRadius` can be set on series level and it's working fine.
Demo: http://jsfiddle.net/BlackLabel/dcPdP/1/

**Comment by dereklin** [comment]
It's not working properly when threshold is used:

http://jsfiddle.net/dereklin/dcPdP/2/

Any idea how to have the border radius only on one side?

**Comment by sebastianbochan** [comment]
I think that at this moment the most flexible solution is using Rounded corners plugin.

Demo:
- http://jsfiddle.net/BlackLabel/d1mL36pb/

**Comment by KacperMadej** [comment]
@dereklin 

Threshold looks fine. http://jsfiddle.net/BlackLabel/dcPdP/3/

`low` in a column point data is not a supported property.

**Comment by dereklin** [comment]
@KacperMadej 
I expect the border radius to show only at the end of column, not at the start.  In other words, only one side should have a rounded corner, not both sides.

**Comment by dereklin** [comment]
@sebastianbochan 
Take this column, the first column of your jsfiddle:
![rounded-corner-column](https://user-images.githubusercontent.com/2231799/36031048-5fbcd45a-0d5e-11e8-9c18-e4fc5965334d.PNG)

I want to the rounded corner to be on the other side. Like this:
![other-side](https://user-images.githubusercontent.com/2231799/36031145-9a2e8af2-0d5e-11e8-9113-2dabe9aaaccd.PNG)

**Comment by KacperMadej** [comment]
@dereklin 
Sebastian suggested the plugin already. The options are set on series level, so you could edit the plugin to accept point level options or create another series for the different shape required. Demo:
http://jsfiddle.net/BlackLabel/wv4od3L7/1/
