### ISSUE TITLE
Suggestion: Plot Band Generalization

### ISSUE THREAD

**Issue by Marcelluszebra** [highcharts/highcharts#14677]
Hi,

Plot bands are useful but I hope can be simply extended.
A plot band is a rectangle having to side limitless.
In general we can consider a rectangle with 4 optional parameters xfrom, xto, yfrom, yto, I call it PlotAreas.

A PlotArea with values only in xfrom, xto is a vertical plotband
A PlotArea with only yfrom, yto is an horizontal plotband
A PlotArea with xfrom, xto, yfrom, yto is a rectangle (with borders, labels as a plot band)
A PlotArea with values xfrom, xto, yfrom is a rectangle unlimited on top

foreach values combination we can draw useful annotations.
I hope this can be implemented for the future.

marc.

**Comment by pawelfus** [comment]
Hi @Marcelluszebra 

Thank you for sharing the idea! At this moment, PlotBands/Lines are tightly coupled with the Axis where are created.

Did you consider using [Annotations](https://www.highcharts.com/docs/advanced-chart-features/annotations-module)  module? With annotations module you can create any shape, with multiple labels, draggable features etc.

**Comment by Marcelluszebra** [comment]
Hi pawelfus,

I want exactly that PlotAreas was coupled with axes!
I want to draw an area based on axis values (not on pixels) that can have some side limitless.

In example, a rectangle (with text) on x1=1, y1=1, x2=10, y2=10 (Axis values)
Or a band for all values having y>10 (x1=null, y1=10, x2=null, y2=null)

I can obtain it with Annotations Module?

**Comment by pawelfus** [comment]
Yes, you can :) Simple example for you: https://jsfiddle.net/BlackLabel/x0vako6c/3/ - three different annotations, using pixel coordinates, chart coordinated and a mixed one :)

**Comment by Marcelluszebra** [comment]
Ok, real interesting!
We can also obtain a text aligned top/center/bottom left/center/right as in plot bands?
If yes my suggestion can be closed! :-)

marc.

**Comment by pawelfus** [comment]
Label's point works the same way as path points in a rect. You can configure it as you wish - just provide x+y (and optionally xAxis + yAxis) to render label there. It requires a bit more options than simple `align` and `verticalAlign` options in plotBands, but is more robust. Demo: https://jsfiddle.net/BlackLabel/x0vako6c/4/

Just try it out and let us know if you find any issues!

**Comment by Marcelluszebra** [comment]
Dear Pawelfus,

Thank's very much.
At te end:

1) We can emulate the PlotArea using big numbers in annotations.
2) If we know exactly the label length/height and the ration between pixels and axis unit we can emulate also the text alignment using a fine tuning.

1) is a little bit "dirty", 2) don't happens in a lot of real cases.

Tank you, I will try to apply your suggestions, but I repeat mine.
I think that a solid PlotArea with text,  borders, alignments, optional values, textures (!!). and without "tricks" will be really useful.

**Comment by pawelfus** [comment]
Thank you for your feedback @Marcelluszebra 

Could you explain what do you mean by optional values and textures (!!) ? By textures I assume you might want to use `pattern-fill` plugin, which is compatible with both, plotBands and annotations: https://jsfiddle.net/BlackLabel/x0vako6c/5/

> We can emulate the PlotArea using big numbers in annotations.

Yes, good point. I don't really like it neither. What if we would add an option to use percentage coordinates of yAxis and yAxis? So for example this:
```js
{
  points: [{
    xAxis: 0,
    yAxis: 0,
    x: 50,
    y: 50,
    usePercentPosition: true // working title
  }
}, {
  ...
}]
```
Would start rendering rectangle from the middle of the plotting area? 100 would mean 100%, full width in pixels in relation to the x/yAxis etc. The same would apply to label position.

What do you think?

**Comment by Marcelluszebra** [comment]
Dear Pawelfus,
Really good for fill options!

I think percentage can be a good idea, but this is not a complete solution.
The real problem is how set label position relative to the shape.
An Idea can be a parameter that define the point of the label that we are setting position.

Suppose an Hexagon with a centered label that say "Hello!"
Let x1, y1 and x2, y2 the top/left corner of rectangle that contains the hexagon. Let x2, y2 the bottom, right corner.

A solution can be to define a label in:

x = (x1+x2)/2
y = (y1+y2)/2
LabelPointXReference = Center
LabelPointYReference = Center

And the engine put the center of the label at the center of the shape.
What do you think?

**Comment by pawelfus** [comment]
I'm afraid I don't understand why we need a relation between `shape` and `label`. Could you elaborate a little?

Given the hexagon example, you need six points on a plane. Let's say we used xAxis and yAxis coordinates, so we get this: https://jsfiddle.net/BlackLabel/x0vako6c/6/ - to generate such hexagon, you need to know all 6 points, and you know the label alignment you want to achieve. Then you know which point you want to align your label to, e.g. PX(`x = (x1+x2)/2`, `y = (y1+y2)/2`). What if one wants to use not the bounding box, but largest inscribed rectangle in the shape? Or fit label in some very detailed shape, or without space for label to fit in? For example: https://jsfiddle.net/BlackLabel/x0vako6c/7/

Thanks!

**Comment by Marcelluszebra** [comment]
I'm sorry, my english is pretty terrible... 

We can consider your second sample:
https://jsfiddle.net/BlackLabel/x0vako6c/7/

Now, the label "align me" has the property that "its arrow tip is aligned with the center of the shape"
Instead, we want that the center of text is on the center of the shape.
And we don't want to apply fine tuning because we don't know, in real case, label content.

An idea can be to specify the relative point  of the label that we are defining position, in the case some similar to:

labels: [{
   text: 'align me', 
 xReferencePoint: 'center',
 yReferencePoint: 'center',
  point: {x: 2.5, y: 15, xAxis: 0, yAxis: 0}}]

Consider now a rectangle shape with a text aligned top right without fine tuning, we will can use some similar to:

labels: [{
   text: 'align me', 
 xReferencePoint: 'right',
 yReferencePoint: 'top',
  point: {x: 2.5, y: 15, xAxis: 0, yAxis: 0}}]

I hope this can be more clear.

>PS: Just to be on the same page, it's not possible to render hexagon using plotBands (in a cartesian chart). And this is not the idea of issue, right?

Yes, Shapes can be really more useful than plotbands or plotarea. Now I'm on Annotations. :-)

**Comment by Marcelluszebra** [comment]
Dear pawelfus,

I used all your suggetions working in a real case:
https://jsfiddle.net/pdj91z2r/

Some problems:

1) Annotation stroke (border) is out of the screen for left and bottom side
2) The "real" label is aligned "Top/Left"  (Consider that I don't know the user axis range settings and I don't know the label content)
3) This is out of topic, but fill patterns don't work good in chrome for mac)

I attach the expected result create with scicharts.

Thanks very much
marc.

<img width="309" alt="Schermata 2020-12-02 alle 11 21 55" src="https://user-images.githubusercontent.com/48215101/100860673-1577b100-3491-11eb-88a1-7b5e3d7001b4.png">

**Comment by pawelfus** [comment]
> I'm sorry, my english is pretty terrible...

I must disagree, it's perfectly fine :) 

Regarding label & align: this is already possible! Name are the same as in plotBands: `align` and `verticalAlign`. That options align label in relation to the point (in `labels[].point` config). Take a look: https://jsfiddle.net/BlackLabel/x0vako6c/9/ - just default settings (background, border, shape, offset etc) may not suit your needs.

Given your second example, that would be it: https://jsfiddle.net/BlackLabel/azcfb152/

Regarding border and aligning to other corners (top-left, bottom-left etc): I believe all of them will be automatically resolved if we let `point` to get percentage values.

As for the patterns, this is most likely related to rendering huge rectangle: 1 600 000 000px width, 4 600 000 000px height. I believe we can forgive Chrome for having issues with this :)

There is a way to achieve what you need, using just annotations. Every `point` can be actually a function that should return a config. It's not documented (should be!), but you can observe this in action: https://jsfiddle.net/BlackLabel/azcfb152/1/

**Comment by Marcelluszebra** [comment]
Dear pawelfus,

You have solved a lot of my doubts, thanks very much.
Now I'm completely with you, allowing percentage setting of point params I can solve all my problems.
Percentage setting means:

The percentage value x (or y) is the percentage of chart area width (height) if an axis is not set.
The percentage value x (or y) is the percentage of axis width (height) if an axis is set.
If a position is set in percentage mode, zoom, pan, resize etc... invoke a position recalculation.

What do you think?

**Comment by pawelfus** [comment]
I agree with you :) Thank for your time! Helping us understand what you want to achieve and how can we implement this in the annotations module.

Just in case you need this feature right now, please use solution from this demo: https://jsfiddle.net/BlackLabel/azcfb152/1/ (function that returns a point, instead of a static point). All of the issues you mentioned earlier (border, label alignment, Chrome bug with pattern) don't exist.

**Comment by Marcelluszebra** [comment]
Yes, I'm already using it!
Thank's!
I close the issue.

**Comment by Marcelluszebra** [comment]
Dear Pawelfus,

various alignment problems appears if use can change axis direction and/or chart.inverted property.
I solved creating a dynamic point the label position in all case, in example if we want that label is top/left it is top left foreach configuration, at the moment it work pretty good!

`function f_PlotAreaLabelSet(a, x1, y1, x2, y2, xa, ya, ha, va) {

    /*
     * a: passed from dynamic point
     * x1, y1: coordinates of bottom/left point
     * x2, y2: coordinates of top/right point
     * xa, ya: axis indexes
     * ha: horizontal align: 0=left, 1=right, 2=center
     * va: vertical align: 0=top, 1=bottom, 2=middle
    */

    //Chart/Axis inverted
    var inverted = a.chart.inverted;
    var xaa = a.chart.xAxis[xa];
    var yaa = a.chart.yAxis[ya];
    var xar = xaa.reversed;
    var yar = yaa.reversed;

    //current rectangle x1<x2 and y1<y2
    x1 = x1 === null ? xaa.min : x1;
    y1 = y1 === null ? yaa.min : y1;
    x2 = x2 === null ? xaa.max : x2;
    y2 = y2 === null ? yaa.max : y2;

    //now we can determine xleft, xright, yleft, yright
    var xl, xr, yt, yb;
    if (inverted) {
        xl = xar ? x1 : x2; //x grow from bottom to top (when not inverted)!
        xr = xar ? x2 : x1;
        yt = yar ? y2 : y1;
        yb = yar ? y1 : y2;
    }
    else
    {
        xl = xar ? x2 : x1;
        xr = xar ? x1 : x2;
        yt = yar ? y1 : y2; //y grow from bottom to top (when not inverted)!
        yb = yar ? y2 : y1;
    }

    //now we can determine the label reference point based on horizontal alignement ha and vertical alignment va
    var x, y;
    
    if (ha === 0) x = xl; //left
    else if (ha === 2) x = xr; //right
    else x = (xl + xr) / 2; //center

    if (va === 0) y = yt; //top
    else if (va === 2) y = yb; //bottom
    else y = (yt + yb) / 2; //center

    //now we can set label position to respect to the point x,y
    if (ha === 0) a.options.align = 'left';
    else if (ha === 2) a.options.align = 'right';
    else a.options.align = 'center';
    if (va === 0) a.options.verticalAlign = 'top';
    else if (va === 2) a.options.verticalAlign = 'bottom';
    else a.options.verticalAlign = 'middle';

    return { x: x, y: y, xAxis: xa, yAxis: ya }
}`

**Comment by pawelfus** [comment]
Thank you for sharing your solution! 

Alternatively, you can simply remove/add/update annotation when changing axis direction and/or inverted option.
