### ISSUE TITLE
Datalabels being cut off when dataSorting is enabled and maxPadding is set to 0

### ISSUE THREAD

**Issue by radkerodrigo** [highcharts/highcharts#14689]
#### Expected behaviour
The dataLabels of the first four columns should be placed inside to avoid the labels being cut off.

#### Actual behaviour
The dataLabels are placed on the top of the columns and are being cut off.

#### Live demo with steps to reproduce
1. Open https://jsfiddle.net/radkerodrigo/4w6x93re/7/
2. The first four dataLabels are being cut off.
3. Disable the dataSorting (series[0].dataSorting.enabled = false)
4. The dataLabels of the biggest columns are placed inside the columns.

#### Product version
Highcharts 8.2.2

#### Affected browser(s)
Tested on Chrome 86

**Comment by PaulDalek** [comment]
Hi @radkerodrigo

Thank you for reporting this issue. It seems that enabling the [`dataSorting`](https://api.highcharts.com/highcharts/series.column.dataSorting) functionality disables the default value of the [`overflow`](https://api.highcharts.com/highcharts/series.column.dataLabels.overflow) option for data labels (which is `justify`). To resolve this, you can explicitly set the `overflow` to `justify`.

FYI @ppotaczek 

**Demo**
https://jsfiddle.net/BlackLabel/sr053182/
