### ISSUE TITLE
Stacked column chart - columns being positioned in a wrong way

### ISSUE THREAD

**Issue by patryksuchowierski** [highcharts/highcharts#14684]
#### Expected behaviour
properly positioned chart columns
![1](https://user-images.githubusercontent.com/15261174/100433825-ed0c4300-309b-11eb-8a9e-eeeb599e55d3.png)

#### Actual behaviour
columns positioned on the edges of the chart (it's because there's no series that belongs to 2 columns) 
![2](https://user-images.githubusercontent.com/15261174/100433832-eed60680-309b-11eb-9098-cf455292b91f.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/5e0jhrm7/1/ (comment out line 23 to see the issue)

#### Product version
Highcharts v8.2.2

#### Affected browser(s)
All of them

**Comment by PaulDalek** [comment]
Hi @patryksuchowierski

Thank you for reporting this issue. This is not a bug. You can set the [`pointRange`](https://api.highcharts.com/highcharts/series.column.pointRange) to one year in order to display points as expected.

**Demo**
https://jsfiddle.net/BlackLabel/9b5g206v/
