### ISSUE TITLE
First of the Bolded subtitles in the annotation edit popup is moved to the last place

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#14691]
When clicking the edit button on annotation, the first bolded subtitle is displayed in the wrong place. Should be on top of the list of properties, and is on the bottom. 

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui

- Add the rectangle shape annotation to the chart
- Click the edit button
- Notice, that the subtitle (in this case 'shape options') is in the wrong position
Firefox ---->
![image](https://user-images.githubusercontent.com/26306846/100453273-02449a00-30bb-11eb-8dda-ee5c0e49ea22.png)

Chrome ----> 
<img width="392" alt="image" src="https://user-images.githubusercontent.com/26306846/100453394-20aa9580-30bb-11eb-81e7-b4289bd4ffd4.png">

For different shape it looks like the first title, that is displayed in the options is moved to the last place: 
Firefox --->
![image](https://user-images.githubusercontent.com/26306846/100453532-62d3d700-30bb-11eb-9fcf-80c6af841439.png)
Chrome --->
<img width="391" alt="image" src="https://user-images.githubusercontent.com/26306846/100453602-839c2c80-30bb-11eb-9049-dc55920d2327.png">

#### Product version
Highstock v8.2.2

#### Affected browser(s)
Firefox

**Comment by pawelfus** [comment]
*Internal note:*
Caused by using browser's `sort()` instead of `stableSort()`: https://github.com/highcharts/highcharts/blob/099a579abaca902659dd7c8d054f7c4df5629745/ts/Extensions/Annotations/Popup.ts#L687-L689
