### ISSUE TITLE
Highchart Candlestick Range selector not showing for ranges other than ALL.

### ISSUE THREAD

**Issue by iamanthos** [highcharts/highcharts#14703]
#### Expected behaviour
Should work when changing the range.

#### Actual behaviour
Not working when range is changed either via slider or updating text input.

#### Live demo with steps to reproduce
https://jsfiddle.net/4c1xfozs/10/

Not working with this json data - https://api.jsonbin.io/b/5fc3db57177c556ef9b43953

But working with this data - https://demo-live-data.highcharts.com/aapl-ohlc.json

In JSfiddle it is showing currently one candlestick, but same implementation in react show proper data.

See screenshot.

![all](https://user-images.githubusercontent.com/36125782/100549399-c2d3a480-3298-11eb-8b41-97f4a2eae6c7.PNG)
![changing_range](https://user-images.githubusercontent.com/36125782/100549401-c404d180-3298-11eb-8024-4e6d5fbb64d5.PNG)

#### Product version

"highcharts": "^8.2.2",
  "highcharts-react-official": "^3.0.0",

#### Affected browser(s)
Only using Chrome.

**Comment by PaulDalek** [comment]
Hi @iamanthos

Thank you for reporting this issue. When I run your demo I have noticed that the [#15](https://www.highcharts.com/errors/15/) error occurs. It means that the data isn’t sorted in ascending order, which is required in Highcharts. Try to sort your data and let us know if that helped.

**Comment by iamanthos** [comment]
Hi Paul, which api do you recommend to generate data for intraday, I have tried with MarketStack and AlphaVantage for getting intraday data but it seems The chart is working as expected only with the data you are you using with your demo.

Ideally it should work with every api but at this point I just want it to work.

PS. I am getting the data and converting it into OHLC format as mentioned in the demo.

**Comment by iamanthos** [comment]
> Hi @iamanthos
> 
> Thank you for reporting this issue. When I run your demo I have noticed that the [#15](https://www.highcharts.com/errors/15/) error occurs. It means that the data isn’t sorted in ascending order, which is required in Highcharts. Try to sort your data and let us know if that helped.

Hi Paul, Sorting the data seems to be working. The error seems to be buried between my Array logs. Thanks.

Can you point me to some open source projects you know which uses candlestick charts or point me to the project using customisation of chart using differrent  colors and hovering events.

**Comment by PaulDalek** [comment]
@iamanthos

Sure, no problem. As for your question, I can refer you to our [demos section](https://www.highcharts.com/demo/stock) where you find a few candlestick examples. When it comes to chart customization that concerns changing the colors and hover behaviors, please contact our support team using one of the [available channels](https://www.highcharts.com/blog/support/).
