### ISSUE TITLE
Responsive behavior of axis labels when margin bottom is applied

### ISSUE THREAD

**Issue by tanmayshah95** [highcharts/highcharts#14706]
#### Expected behaviour
Axis labels should be responsive such as auto rotation (if rotation not set), ellipsis (if rotation is set) etc. is auto calculated, when chart margin is modified.
Ellipsis should be automatically handled so that, only 4-5 characters are displayed as space is not available for labels (similar handling as of dynamic margin handling)
Had discussion regarding this issue on Forum: https://www.highcharts.com/forum/viewtopic.php?f=9&t=45440&sid=627b36dac4a90a1198a307b1ec66e32e

#### Actual behaviour
On setting marginBottom on chart, if labels are having rotation they are getting cut out of chart area or are overlapping on legend.
It works properly if margin is set for bar chart and labels are horizontal.
Also if xAxis.scrollbar is used, scrollbar is not coming inside chart area due to margin bottom.

#### Live demo with steps to reproduce
https://jsfiddle.net/tanmayshah95/usxfcyvb/1/
Here, margin bottom is set to 100. And labels are overlapping and getting cut due to chart area.

#### Product version
latest version of highcharts/highstock

**Comment by PaulDalek** [comment]
Hi @tanmayshah95

Thank you for contacting us and reporting this issue. As a workaround, you can use the [`responsive`](https://api.highcharts.com/highcharts/responsive) options to set the `rotation`, shorter `width` and `textOverflow` for labels.

**Demo**
https://jsfiddle.net/BlackLabel/7v1fL4t6/
