### ISSUE TITLE
Legend - floating option

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1470]
When floating options is set, then i.e xAxis labels are visible in legend. 

http://jsbin.com/ubapaz/24/ (useHTML options doens't solve this issue).

**Comment by ShoresOfNowhere** [comment]
Sorry, but that doesn't solve the issue, as you can see here:

http://www.faromed.it/_hcbugs/BadLegendVsAxisLabelsZindex.htm

Also, in this example you can see that also the y axis has the same problem.

The only way I found to resolve the problem was moving the highchart-legend G tag after the axis tags in the svg output manually, but this isn't a real solution! ;)

**Comment by ShoresOfNowhere** [comment]
The resolution can also be applied to the live svg with this:

        chart: {
            events: {
            load: function(event) {
				//resolve legend z-index bug
                var z = this.legend.group.element, zzz = z.parentNode;
    			zzz.removeChild(z);
    			zzz.appendChild(z);
	            }}

Which shifts the legend as the very last child of its container.

**Comment by pawelfus** [comment]
Thanks for pointing this out! Standalone demo: http://jsfiddle.net/a240t3tu/

Another solution, to set zIndex for series is to wrap rendering method and change zIndex, example:

    (function (H) {
      H.wrap(H.Legend.prototype, 'render', function (p) {
        p.apply(this, [].slice.call(arguments, 1));
        
        if (this.group) {
          this.group.attr({
            zIndex: 100
          });
        } 
      });
    })(Highcharts);

Demo: http://jsfiddle.net/a240t3tu/1/

**Comment by ShoresOfNowhere** [comment]
This bug is still present in the latest github version:

A big legend rendered with 4.2.7:

https://www.faromed.it/_hcbugs/BadLegendVsAxisLabelsZindex_v4.htm

With the latest version:

https://www.faromed.it/_hcbugs/BadLegendVsAxisLabelsZindex.htm

**Comment by KacperMadej** [comment]
Unable to recreate (or see) the problem in version 6.1.4 when zIndex is adjusted for both axes.
Demo: http://jsfiddle.net/BlackLabel/a240t3tu/2/
Closing as resolved.

In case of a comment with a live demo or more info the issue could be reopened.
