### ISSUE TITLE
pointWidth typings mismatch

### ISSUE THREAD

**Issue by artemipanchuk** [highcharts/highcharts#14710]
#### Expected behaviour
In my code I do:
![image](https://user-images.githubusercontent.com/15093838/100595958-aa04d680-330c-11eb-9aaa-b6e935a0e2db.png)

I consider `null` to be expected value for `pointWidth` because the doc says so: https://api.highcharts.com/highcharts/series.bar.pointWidth.

#### Actual behaviour
I get type error:
![image](https://user-images.githubusercontent.com/15093838/100596787-9b6aef00-330d-11eb-8faf-d599215da4d6.png)

I guess, that
`pointWidth?: number;`
should be something like
`pointWidth?: number | null;`

#### Live demo with steps to reproduce
n/a

#### Product version
Highcharts 8.2.2

#### Affected browser(s)
n/a

**Comment by PaulDalek** [comment]
Hi @artemipanchuk

Thank you for contacting us and reporting this issue.

FYI @bre1470
