### ISSUE TITLE
Inputting JSON String to phantomJS and chart generation

### ISSUE THREAD

**Issue by kalyansworld** [highcharts/highcharts#1472]
I want to render highcharts on server-side using phantomJS,i will be giving json string & highcharts library as input,whether it wil generate svg for me?

I know this can be done using one2team source+Rhino,help with a for phantomJS tooo...

**Comment by nakulogale** [comment]
Hi guys,

This is my scenario.
Following json is accepted by the exporting-server.
File A-
{
"infile":
	"{
	xAxis: {categories:['Apr 16,15 16:37:31','Apr 16,15 16:37:32','Apr 16,15 16:37:33']},
	series:[{data:[50,60,70]}]
	};",
"constr":"Chart",
"outfile":"/tmp/image.png"
}

However, the following does not.
File B-
{
"infile":
	{
	"xAxis":{"categories":["Apr 16,15 18:06:45","Apr 16,15 18:06:46","Apr 16,15 18:06:47"]}
	"series":[{"data":[50,60,70]}],
	},
"constr":"Chart",
"outfile":"/tmp/image.png"
}

Differences between the two : 
1. A has xAxis (without the double quotes), B has "xAxis" (with the double quotes).
2. A has 'Apr 16,15 16:37:31', B has "Apr 16,15 18:06:45". 

File A works perfectly but not file B.

My scenario : 
I am invoking REST call to the exporting-server through a Java class.

**Comment by highslide-software** [comment]
Your file B has malformed JSON. A comma is missing behind the xAxis definition. The following works when passed to http://export.highcharts.com through the GUI:
```json
{
"xAxis":{"categories":["Apr 16,15 18:06:45","Apr 16,15 18:06:46","Apr 16,15 18:06:47"]},
"series":[{"data":[50,60,70]}]
}
```

**Comment by nakulogale** [comment]
So here is what I notice. 
1. Go to http://export.highcharts.com. 
{
        "xAxis": { "categories":["Apr 16,15 18:06:45","Apr 16,15 18:06:46","Apr 16,15 18:06:47"]},
        "series": [ {"data":[50,60,70]}]
};
This works.
2. Setup local server.
This doesnt work when the JSON is 
{"infile":
"{
        "xAxis": { "categories":["Apr 16,15 18:06:45","Apr 16,15 18:06:46","Apr 16,15 18:06:47"]},
        "series": [ {"data":[50,60,70]}]
}",
"outfile":"/tmp/image.png",
"constr":"Chart"
}
ie as a part of value of "infile" tag.

I wonder what I am doing wrong.

**Comment by gvaartjes** [comment]
I answered your question [here](http://forum.highcharts.com/post115060.html#p115060).  For further question, please address your questions to the right channel at highcharts.com/support. On Github we discuss mainly bugs or code changes.

**Comment by manuelids** [comment]
Can this return a byte array instead? I don't want it to save to disk, since it usually takes an avg of 3 seconds and I need it stored in cloud

**Comment by TorsteinHonsi** [comment]
@cvasseng
