### ISSUE TITLE
Upgrading from Highcharts/Highstock v4 to v8 has resulted in increased rendering times, for Internet Explorer 11

### ISSUE THREAD

**Issue by LiquidTony** [highcharts/highcharts#14740]
#### Expected behaviour
Upgrading from Highcharts/Highstock v4 to v8 should not result in increased rendering times

#### Actual behaviour
Upgrading from Highcharts/Highstock v4 to v8 has resulted in increased rendering times, for Internet Explorer 11

E.g. The time taken to render the below live demo has increased from 50 seconds (Highcharts 4.2.5) to 6 minutes (Highcharts 8.0.4):

Highcharts Version | Firefox/Chrome/Edge | Internet Explorer
-- | -- | --
8.2.2 | 7s | **6m**
8.0.4 | 7s | **6m**
7.2.2 | 7s | **6m**
6.2.0 | 7s | 50s
4.2.5 | 7s | 50s

#### Live demo with steps to reproduce
template: https://jsfiddle.net/JSTony/w65jspyu/12/

#### Product version
Highcharts/Highstock v7+

#### Affected browser(s)
Intenet Explorer 11.  (Firefox, Chrome and the Chromium build of Edge are all unaffected)

**Comment by PaulDalek** [comment]
Hi @LiquidTony

Thank you for reporting this issue. I tested provided demo on my side (Windows 8.1, x64) and times for chart rendering are as follows:

Without boost module:
Chrome (v87.0.4280.66): **6377.41796875ms**
IE11 (v11.0.9600.19846): **46627.5ms**

With boost module:
Chrome (v87.0.4280.66): **2720.087890625ms**
IE11 (v11.0.9600.19846): **11407.2ms**

Both tested on the newest Highcharts (v8.2.2). Also, I have created an example based on your code locally in order not to run the demo through JSFiddle. Try to do the same and see if the rendering times improve.

**Comment by LiquidTony** [comment]
Hi @PaulDalek,

Thank you for taking a look at this issue.  I have re-created my JSFiddle demo in JSBin (unlike JSFiddle, JSBin does seem to work in IE), hopefully you can see this here:

- https://jsbin.com/wipopaq/edit?html,js,output

Testing with and without the boost module, I get the following times (all times are approximate):

Browser | Without Boost | With Boost
-- | -- | --
Chrome (87.0.4280.88) | 6s | 2s
IE (11.572.19041.0) | 1m15s | 11s

Unfortunately when using the boost module, the chart does not render correctly for me.  There is only one bar instead of many bars.  In my demo, if you toggle the boost enabled value in the JavaScript, you should see the difference:

Without Boost | With Boost
-- | --
![Without Boost](https://user-images.githubusercontent.com/75374809/101180896-1c92f080-3644-11eb-971c-b081548c401a.png) | ![With Boost](https://user-images.githubusercontent.com/75374809/101180898-1d2b8700-3644-11eb-9bc2-eef6c33f7e1f.png)

Please could you advise?

Many thanks,

Tony

**Comment by PaulDalek** [comment]
@LiquidTony

Thanks for the demo but still I'm not able to reproduce this long time rendering behavior. On my side (tested locally without using any online IDE) the time is approx 50s. Could you please try to test it locally and if the times (you can use the `console.time` function for more accurate values) are still high, could you provide us with a zip package with a simplified demo that recreates the problem? As for the points in one bar problem when using the boost module, I have noticed that points don't have the `x` values. Since the points are distributed one point per series and the `pointPlacement` option doesn't work in boost module, they will be displayed in one column (just like if the `grouping` is set to false). You can try to set points with a correct `x` value and see if they are displayed correctly.

**Comment by LiquidTony** [comment]
Hi @PaulDalek,

Thank you, setting x values together with using the boost module seems to have done the trick!  The charts now render faster than ever (especially in IE).

When running with boost however, I notice the following is now logged in the console:
> "Highcharts warning #12: www.highcharts.com/errors/12/"

I gather this is something to do with the turboThreshold, I have updated my JSFiddle demo as follows for you to see:
- https://jsfiddle.net/JSTony/w65jspyu/12/ (without boost, without x values: no warning) 
- https://jsfiddle.net/JSTony/87cubrmx/6/ (with boost, with x values: warning)

Perhaps I have done something incorrectly?

Many thanks,

Tony

**Comment by PaulDalek** [comment]
@LiquidTony

To get rid of this error you need to change the structure of points to array notation. For more information, please read the error [#12](https://www.highcharts.com/errors/12/) or the description of the [`turboThreshold`](https://api.highcharts.com/highcharts/series.column.turboThreshold) in the API.

**Comment by LiquidTony** [comment]
Thanks @PaulDalek :+1:
