### ISSUE TITLE
scrollablePlotArea - issue after changing `chart.inverted`

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#14758]
#### Expected behaviour

After changing the chart series type the vertical scrolling should change to the horizontal one. 

#### Actual behaviour

Chart keeps the vertical scrolling and the horizontal is missing. 

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/kL1z064d/

#### Product version

Highcharts JS v8.2.2 (2020-10-22)

**Comment by pawelfus** [comment]
This is not an issue with changing series type, but switching from/to inverted chart: https://jsfiddle.net/BlackLabel/kL1z064d/3/
