### ISSUE TITLE
tilemap module, adding property tileShape: "square" throwing error.

### ISSUE THREAD

**Issue by praveenvitara** [highcharts/highcharts#14766]
#### Expected behaviour
tile map to render with each tile in square shape

#### Actual behaviour
tile map failing to render with an error.

#### Live demo with steps to reproduce
https://jsfiddle.net/praveenx9/dpo9ycnf/8/

#### Product version
Tested with version 8.1.2 and latest.

#### Affected browser(s)
Chrome

**Comment by khlieng** [comment]
Duplicate of #14267.
