### ISSUE TITLE
Wrong "spikes" on line graphs

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#1477]
I use Highcarts to view the temperatures from my home.

On many graphs, I can see many "spikes" in data rendering. 

![chart](https://f.cloud.github.com/assets/3426150/110366/fd969efe-6ac0-11e2-93ad-6aa39973b516.png)

On this example; the data file which is sent by server doesn't containts any spike, and this is comfirmed when you make a chart from MS Excel.

The tooltip also comfirms this bug, since the value at the cursor shows 8.63°, but is rendered as about 30°.

Here is a live example, with all data !

http://lemarinel.net/highcharts/

**Comment by Attrash-Islam** [comment]
Thanks @TorsteinHonsi 
+1 for your great answer!
