### ISSUE TITLE
Info icon #9432 shows up garbled when image of chart is downloaded

### ISSUE THREAD

**Issue by WolfeyeOfIowa** [highcharts/highcharts#14779]
#### Affected browser(s)
![Untitled](https://user-images.githubusercontent.com/75683017/101498857-32e5c880-3932-11eb-9382-087bb3289ab2.jpg)
![actual](https://user-images.githubusercontent.com/75683017/101498884-38431300-3932-11eb-8208-30c9b8e59791.jpg)

**Comment by pawelfus** [comment]
Hi @WolfeyeOfIowa 

Thank you for reporting the issue. Could you recreate the issue in jsFiddle? We will check it.

My guess, you did set `useHTML: true` for the chart, but did not set [`allowHTML: true`](https://api.highcharts.com/highcharts/exporting.allowHTML) in exporting options.

**Comment by WolfeyeOfIowa** [comment]
This fixed the issue, thank you!
________________________________
