### ISSUE TITLE
Incorrect tooltip position on inverted area chart with adjusted width

### ISSUE THREAD

**Issue by Hawk30100** [highcharts/highcharts#14771]
#### Expected behaviour
For an inverted area chart with adjusted width, the tooltips should be positioned near the data points, as for a bar chart:
![correct_bar_chart](https://user-images.githubusercontent.com/5665044/101358061-9cb29380-389a-11eb-8659-195365bf4713.png)

#### Actual behaviour
The tooltips are misplaced:
![incorrect_line_chart](https://user-images.githubusercontent.com/5665044/101358073-a1774780-389a-11eb-990e-94b84d50fddd.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/8qdkvocz/
http://jsfiddle.net/8m1qdbjo/3/

#### Product version
Highcharts 8.2.2

#### Affected browser(s)
Firefox 83.0, Microsoft Edge 87.0.664.55 and others

**Comment by pawelfus** [comment]
Thank you for reporting this bug @Hawk30100
