### ISSUE TITLE
hover/click regression when using dataClasses under IE11

### ISSUE THREAD

**Issue by rmott-littler** [highcharts/highcharts#14774]
#### Expected behaviour
Hover and click actions are consistent when `dataClasses` are used. Cursor does not flicker and click events process cleanly.

#### Actual behaviour
IE11 hover/click events are inconsistent when using `dataClasses` on a map. Tooltips work fine, but hover highlights are missing or inconsistent; cursor flickers between `pointer` (hand) and `default` (arrow). Inspecting the DOM the `highcharts-series-hover` classes are missing (rapidly added and removed). `point.click` and `point.select` events fire rarely if at all. Zooming in and out can sometimes "fix" the behavior temporarily.

#### Live demo with steps to reproduce

- https://www.highcharts.com/demo/maps/data-class-ranges : in IE11, the tooltip works but no hover color (works in Chrome)
- https://www.highcharts.com/demo/maps/data-class-two-ranges : in IE11, hover inconsistent and states intermittently clickable. Zooming in and out may fix temporarily (or trigger the bug)
- https://www.highcharts.com/demo/maps/honeycomb-usa : type `tilemap` with `dataClasses` works fine in IE11 (bug limited to type `map`?)

#### Product version
The problem first appears in version 8.0.0 and persists through current release. Maps with `dataClasses` seem to work fine on IE11 through version 7.2.2. 

#### Affected browser(s)
IE11

**Comment by PaulDalek** [comment]
Hi @rmott-littler

Thank you for contacting us and reporting this issue. I was able to recreate the behavior in IE11. It looks like the function `setState` that, as the name suggests is responsible for changing the actual state of a point, runs two times. The first one sets the correct state, which is `hover` and correctly changes the `fill` of a path. After that, another call of the function occurs but this time, with the `undefined` state. The last correctly working version is v7.2.1.

**Simplified demo**
https://jsfiddle.net/BlackLabel/kqm92w8h/

**Comment by rmott-littler** [comment]
Thanks for confirming. To be clear, I see no visual regressions on v7.2.2 - I think that is the last correctly working version?

**Comment by PaulDalek** [comment]
@rmott-littler

Yes, you are right. It was a special security hotfix released on npm but not available on https://code.highcharts.com/.
