### ISSUE TITLE
Offline export to PNG/JPEG with HTML content without fallback to export server

### ISSUE THREAD

**Issue by miiihi** [highcharts/highcharts#14780]
#### Expected behaviour
Offline export to PNG/JPEG with HTML content without fallback to export server should work as it is supported by all modern browsers

#### Actual behaviour
Offline export to PNG with HTML content without export server fails

#### Live demo with steps to reproduce
[https://jsfiddle.net/7qdxp526/2/](https://jsfiddle.net/7qdxp526/2/)

Fiddle with default PNG Export failing and simple workaround showing that export is possible and shouldn't fail in default export

#### Product version

All

**Comment by miiihi** [comment]
A note on fiddle workaround - it works for FF. For Chrome, additional change is required, that is to remove the special handling of Chrome in [offlineexporting.svgToDataUrl](https://github.com/highcharts/highcharts/blob/f4237313462ea6125728ad8984da19380d3bcaeb/js/Extensions/OfflineExporting.js#L58) 
Not sure why the special handling of Chrome is there at all...

**Comment by pawelfus** [comment]
Hi @miiihi 

Thank you for reporting this issue. We will check if we can change this. At this moment, it fails as explained in the error (https://www.highcharts.com/errors/28/): 
> ( ... ) The offline exporting module will fail for certain browsers, and certain features (e.g. **exporting.allowHTML** ), ( ... )

**Comment by miiihi** [comment]
Hi @pawelfus 

right, https://www.highcharts.com/errors/28/ does mention `allowHTML`, but the https://www.highcharts.com/docs/export-module/client-side-export where all the details should be, doesn't mention HTML at all, it mentiones only images as problematic. 

And, as said, as browser don't have problem with HTML, there is no need to prevent it...

**Comment by papakay** [comment]
@pawelfus I'm having similar issue. Please when should we expect a fix for this?

**Comment by PaulDalek** [comment]
Hi @papakay

Thank you for contacting us. Exporting a chart in such a scenario still throws error [#28](https://www.highcharts.com/errors/28/). There is no ETA for this fix right now but we will look into it.

**Comment by roychowdhuryrohit-dev** [comment]
Offline export to PNG not working.

Browser: Safari 

Font: Google's Varela Round

<img width="1070" alt="Screenshot 2021-02-06 at 19 42 28" src="https://user-images.githubusercontent.com/24897721/107120449-be88c080-68b3-11eb-8d98-86eb83fe0051.png">
