### ISSUE TITLE
Last legend line is cut off when maxHeight is set to a % of the chart height.

### ISSUE THREAD

**Issue by emanette** [highcharts/highcharts#14796]
#### Expected behaviour
All items can be seen in the legend when navigation is enabled.

#### Actual behaviour
The last line is cut off in the legend by the navigation bar (sometimes) when maxHeight is set to percentage of the chart height.

#### Live demo with steps to reproduce
Code is in C#; not sure how to reproduce in jsfiddle.

#### Product version
Latest

#### Affected browser(s)
Firefox
![legen-cutoff](https://user-images.githubusercontent.com/52761750/101976048-622c5c00-3bf6-11eb-8d84-53f11b63a2a3.jpg)

**Comment by PaulDalek** [comment]
Hi @emanette

Thank you for contacting us and reporting this issue. If you want to display all items, simply disable the `navigation` or set lower/higher value of the `maxHeight` in order to not show cut labels. Also, as you can read in the API, the [`maxHeight`](https://api.highcharts.com/highcharts/legend.maxHeight) accepts only number values.

**Demo**
https://jsfiddle.net/BlackLabel/y2sejLa7/

**Comment by emanette** [comment]
We would like to have the navigation as too many items in the legend was squishing the chart too much. I want the height of the legend to be flexible depending on the size of the screen and chart. It is a number since it's a percentage of the chart height which is also a number. So why is the last line getting cut off?

**Comment by PaulDalek** [comment]
@emanette

The reason why the last legend item is cut is because it simply doesn’t fit in the legend area limited by the `maxHeight` value. You could create a simple function that will calculate the new `maxHeight` for a chart based on the height of a legend item and available space in the legend box. Take a look at the simple demo below.

**Demo**
https://jsfiddle.net/BlackLabel/hL9ofjks/

**Comment by emanette** [comment]
Why is there whitespace added at the end of the legend in some cases such that the user can see the last line in the legend and in other cases, there isn't? It seems to happen in Firefox. Shouldn't there be more scrolling available until you can see the last line?

**Comment by PaulDalek** [comment]
@emanette

Do you mean the group of the navigation elements? Please, provide me with a simplified live example (e.g. JSFiddle) where this behavior occurs and which can be recreated on Firefox browser. Thanks.

**Comment by emanette** [comment]
Because we coded our solution in C#, I couldn't figure out how to get a similar solution in jsfiddle. I tried several ideas. There's a screenshot above of what the last line looks like in the legend. You can see the navigation box that contains the arrows and numbers cuts off the last 2 items instead of continuing to scroll so that you can see them.

**Comment by KacperMadej** [comment]
>  maxHeight is set to percentage of the chart height

[`maxHeight`](https://api.highcharts.com/highcharts/legend.maxHeight) supports only height in pixel. Could you elaborate on how are you using that option? Maybe this is the source of the problem.

I can recreate the problem with some options (demo below) and we would be working on resolving that problem. However, we would like to work on your problem instead. We want to avoid leaving resolving your problem to coincidence or luck, so if you could share used chart options or recreate a live demo then we could better track how your problem is being resolved.

It is possible to recreate a similar or the same problem with setting `itemMarginTop`. Demo: https://jsfiddle.net/BlackLabel/y2sejLa7/4/

As a workaround, you could use `itemMarginBottom`. Demo: https://jsfiddle.net/BlackLabel/y2sejLa7/5/

![legend_cut](https://user-images.githubusercontent.com/8960408/102924766-7a239b80-4492-11eb-9315-601cfcdc76e5.jpg)

**Comment by emanette** [comment]
We're setting the chart height in pixels:
`window.innerWidth * 0.97;`
And then the maxHeight based on the chart height:
`lineData.legend = { enabled: true, maxHeight: lineData.chart.height * 0.15 };`
I've tried to get a re-creation in jsfiddle with no luck. I've also tried the itemMarginBottom, but with no luck. The problem doesn't seem to occur in Chrome, but is reproducible in Firefox, IE11, and Edge.

**Comment by PaulDalek** [comment]
@emanette

If you cannot reproduce it in a live demo, could you at least provide us with full chart options so we can try to recreate the behavior on our side? Thanks.

**Comment by emanette** [comment]
I'm not sure what you mean by "full chart options?" We've got some code in a few places so I'm not sure exactly what to send.

**Comment by PaulDalek** [comment]
@emanette

I mean the options object that you pass to the `Chart` constructor. Here’s more [info](https://www.highcharts.com/docs/getting-started/how-to-set-options#the-options-object).

**Comment by emanette** [comment]
Ok, just verifying I was understanding your request correctly, thank you. I can't send the series data as it's sensitive information, but here are the options:
`{​

              ImageResolution: 2,

​              chart: {

​​                             events: {

​​​                                           afterPrint: afterPrint(),

​​​​                                           beforePrint: beforePrint(),

                                           click: click(),

                                           redraw: redraw(),

​​​​                                           selection: selection(event)

                             },

                             height: 350

​​                             plotBackgroundColor: {

​​​                                           linearGradient: {

​​​​                                                          x1: 1,

​​​​                                                          x2: 1,

​​​​                                                          y1: 1,

​​​​                                                          y2: 0

                                           },

​​​​                                           stops: [

​​​​                                                          0: Array [ 0, "#FFFFFF" ],

                                                          1: Array [ 1, "#FDF5E6" ],

                                                          length: 2

                                           ]

                             },​​​

                             renderTo: <div id="barChart" class="columnChart" style="flex: 1 1 0%; height: 350px; overflow: hidden;" data-highcharts-chart="0">,

​​                             type: "column",

​​                             zoomType: "y"

              },

​​              credits: {

​​                             enabled: false

              },

​​              customData: {

​​                             ColorViewId: 0,

​​                             displayType: "percent"

              },​

              legend: {

​​                             enabled: true,​​

                             maxHeight: 52.5

              },

              message: "",

              plotOptions: {

                             series: Object { lineWidth: 1, threshold: 0 }

              },

​​              series: Array(21) [ {…}, {…}, {…}, … ],

​              show: true,

              title: {

​​                             text: "Historical Performance"

​​              },

              tooltip: {

​​                             borderColor: "#000000",

​​                             footerFormat: "</table>",

​​                             headerFormat: "<table><tr><th colspan=\"2\">{point.key}</th></tr>",

                             pointFormatter: pointFormatter(),

​​​​​                             shared: true,

​​                             useHTML: true

​​              },

              xAxis: {

​​                            categories: [

​​​                                           0: "Last Quarter",

​​​                                           1: "Previous Month",

​​​                                           2: "YTD QTR end",

​​​                                           length: 3

                             ],

​​​                             crosshair: {

​​​                                           color: "rgba(124,181,236,0.2)"

​​​                             },

                             gridLineColor: "#999999",

​​                             gridLineWidth: 0.5,

​​                             labels: {

                                           style: {

​​​​                                                          fontSize: "11px",

​​​​                                                          whiteSpace: "normal"

​​​​                                           }

                             },

                             lineColor: "#999999",

                             ​tickColor: "#999999",

​​                             tickWidth: 0,

                             type: "category",

​​              },

              yAxis: {

​​                             gridLineColor: "#999999",

​​                             gridLineWidth: 0.5,

​​                             labels: {

​​​                                           formatter: formatter()

                             },

​​​​                             lineColor: "#999999",

​​                             minRange: 0.05,

​​                             minTickInterval: 0.01,

​​                             tickColor: "#999999",

​​                             type: "linear"

​​              }

}`
`

**Comment by PaulDalek** [comment]
@emanette

I used the options that you provided, applied your `chart.height` and `legend.maxHeight` calculations along with my load event that calculates a new `maxHeight` and I couldn’t recreate this behavior. The last element is not cut as in the first image. I’m afraid that without any live example from you that would recreate this, it is going to be hard to investigate why this is happening.

**Demo**
https://jsfiddle.net/BlackLabel/9L8n62ku/
