### ISSUE TITLE
styledMode:true - chart solid black

### ISSUE THREAD

**Issue by LimarenkoDenis** [highcharts/highcharts#14795]
#### Expected behaviour
styledMode activated, no visual bugs

#### Actual behaviour
![image](https://user-images.githubusercontent.com/15944879/101917470-f4ba0480-3bd0-11eb-8e1e-cc7a00445fd7.png)

#### Live demo with steps to reproduce
https://codesandbox.io/s/highchart-stock-indicators-with-angular-forked-hz14c?file=/src/app/app.component.ts:483-493

#### Product version
    "highcharts": "8.1.0",
    "highcharts-angular": "2.4.0",

#### Affected browser(s)
Google Chrome is up to date
Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by khlieng** [comment]
You need the Highcharts css for styled mode: `import "highcharts/css/highcharts.css";`
