### ISSUE TITLE
Memory usage in Chrome with setData

### ISSUE THREAD

**Issue by paooolino** [highcharts/highcharts#1479]
test:
http://jsfiddle.net/paooolino/k4Wt6/

Chrome > Memory keeps to grow.
FF > works fine.

Also I tested this issue
https://github.com/highslide-software/highcharts.com/issues/67

and it seems to have the same problem with Chrome.

I am aware about some garbage collector issues with Chrome (for example https://code.google.com/p/v8/issues/detail?id=2073)

**Comment by oysteinmoseng** [comment]
Closing this as it doesn't seem to happen with current Chrome & Highcharts.
