### ISSUE TITLE
Bubbles are not visible on bubble chart after applying series [Intermittent Behavior]

### ISSUE THREAD

**Issue by crohit7** [highcharts/highcharts#14804]
#### Expected behaviour
Bubble should be visible

#### Actual behaviour
Bubbles are not visible [intermittent]

#### Live demo with steps to reproduce
![image](https://user-images.githubusercontent.com/37010744/102181526-bffbc500-3ed0-11eb-82c5-01cc4a9cee6c.png)
![image](https://user-images.githubusercontent.com/37010744/102181653-051ff700-3ed1-11eb-9d77-2703a4f9b268.png)

#### Product version
8.2.2

#### Affected browser(s)
ALL

**Comment by PaulDalek** [comment]
Hi @crohit7

Thank you for contacting us and reporting this issue. Please, provide us with the live simplified demo (e.g. in JSFiddle) where this behavior can be observed. Thanks.

**Comment by pawellysy** [comment]
Closed due to inactivity
