### ISSUE TITLE
[Gantt] Highcharts throws error when enabling scrollbar and setting uniqueNames to true 

### ISSUE THREAD

**Issue by SMH110** [highcharts/highcharts#14808]
Hi,
#### Expected behaviour
Be able to  configure the y-axis to show scrollbar and use `uniqueNames`.

#### Actual behaviour
Highcharts throws error when enabling scrollbar and setting uniqueNames to true 
![image](https://user-images.githubusercontent.com/16171515/102218767-61d1e080-3ed6-11eb-8012-f01a4a8fc61c.png)

#### Live demo with steps to reproduce
[https://codesandbox.io/s/y-scrollbar-vsign?file=/src/index.ts](https://codesandbox.io/s/y-scrollbar-vsign?file=/src/index.ts)

1. Create basic gantt chart options
2. set `uniqueNames` in `yAxis` to true
3. enable scrolling on the y-axis by adding ` {scrollbar: {enabled: true}  ` to `yAxis` 

#### Product version
Highchart 8.2.2

#### Affected browser(s)
- Chrome

**Comment by PaulDalek** [comment]
Hi @SMH110 

Thank you for contacting us and reporting this issue. This is a regression (the latest working version is 8.2.0).

**Simplified demo**
https://jsfiddle.net/BlackLabel/0bj8ecak/

_Internal note_
Bisected to commit https://github.com/highcharts/highcharts/commit/4f8d2b1dad7cae722f42b23f564020e82b57048f

FYI @karolkolodziej
