### ISSUE TITLE
Error is thrown while adding series to Stacked Area Chart

### ISSUE THREAD

**Issue by crohit7** [highcharts/highcharts#14805]
#### Expected behaviour
chart should be plotted with all series items

#### Actual behaviour
chart is plotted partially

#### Live demo with steps to reproduce
![image](https://user-images.githubusercontent.com/37010744/102182780-d9057580-3ed2-11eb-8f9d-9ad3abfa9111.png)
![image](https://user-images.githubusercontent.com/37010744/102182838-efabcc80-3ed2-11eb-8d9b-5fe4b7168d51.png)

#### Product version
8.2.2

#### Affected browser(s)
ALL

**Comment by PaulDalek** [comment]
Hi @crohit7 

Thank you for reporting this issue. In order for us to find out what is the reason for this error to happen, we need a simple live example that recreates it, so please create and provide us with one. Thanks.

**Comment by pawellysy** [comment]
Closed due to inactivity
