### ISSUE TITLE
[Gantt] Documentation and declaration file are missing the color property 

### ISSUE THREAD

**Issue by SMH110** [highcharts/highcharts#14803]
Hi,
#### Expected behaviour
In Gantt chart, the `color` property can be used to set individual task color.

#### Actual behaviour
This property is not mentioned in the documentation and I have Typescript complaining when I use `color` in my `data` object

#### Live demo with steps to reproduce
Create chart options object and use color property in the data object 
[https://codesandbox.io/s/delicate-lake-030cz?file=/src/index.ts](https://codesandbox.io/s/delicate-lake-030cz?file=/src/index.ts)
[https://api.highcharts.com/gantt/series.gantt.data](https://api.highcharts.com/gantt/series.gantt.data)
![image](https://user-images.githubusercontent.com/16171515/102102293-87ea7880-3e23-11eb-9396-667c1f6db5ab.png)

#### Product version
Highcharts version 8.2.2

**Comment by PaulDalek** [comment]
Hi @SMH110 

Thank you for contacting us and reporting this issue. Could you take a look at this @bre1470?
