### ISSUE TITLE
Empty pie chart causes "Uncaught ReferenceError"

### ISSUE THREAD

**Issue by sag-tobias-frey** [highcharts/highcharts#14802]
#### Expected behaviour
Empty pie chart rendered and no errors.

#### Actual behaviour
Exception thrown and rendering stopped.

#### Live demo with steps to reproduce
This error happens when bundling highcharts with webpack (or other bundler) because PieSeries.ts references the prototype of the SVGRenderer at line 766:

https://github.com/highcharts/highcharts/blob/855736d29632531b89892a669700bdecf6a04805/ts/Series/Pie/PieSeries.ts#L766

in the highcharts.src.js file this is compiled to

--> Highcharts.SVGRenderer.prototype.symbols.arc( ... )

The problem is that when bundling with webpack or other bunders the HighCharts global variable is NOT available and this will fail at runtime. Only when loading the *.js directly or explicitly setting window.Highcharts = Highcharts after importing solves this problem.

LiveDemo: http://plnkr.co/edit/HtSdLECqr62ZmOxV?open=index.js&deferRun=1&preview

#### Product version
HighCharts 8.1.2

#### Affected browser(s)
ALL

**Comment by PaulDalek** [comment]
Hi @sag-tobias-frey

Thank you for contacting us and reporting this issue. As for now, you can use mentioned solution by placing the Highcharts in window (`window.Highcharts = Highcharts`).
