### ISSUE TITLE
No data message not aligns within area, it gets hidden.

### ISSUE THREAD

**Issue by crohit7** [highcharts/highcharts#14807]
#### Expected behaviour
All message should be displayed

#### Actual behaviour
message gets hidden

#### Live demo with steps to reproduce
![image](https://user-images.githubusercontent.com/37010744/102200680-2beb2700-3eeb-11eb-94b4-bbd410d3d0cc.png)
![image](https://user-images.githubusercontent.com/37010744/102200754-402f2400-3eeb-11eb-8b5c-f0db81d0835a.png)

#### Product version
8.2.2

#### Affected browser(s)
ALL

**Comment by PaulDalek** [comment]
Hi @crohit7 

Thank you for reporting this issue. In case of a small chart’s width, you can decrease the font’s size of a text or place break line elements (`<br>`) in the string. More options can be found in the [API](https://api.highcharts.com/highcharts/noData).

**Demo**
https://jsfiddle.net/BlackLabel/fxkcmy6u/
