### ISSUE TITLE
Tooltip content goes outside of the area

### ISSUE THREAD

**Issue by crohit7** [highcharts/highcharts#14806]
#### Expected behaviour
tooltip content should be aligned inside area

#### Actual behaviour
tooltip content goes outside

#### Live demo with steps to reproduce
![image](https://user-images.githubusercontent.com/37010744/102183892-9a70ba80-3ed4-11eb-8f07-dfa686d74700.png)

#### Product version
8.2.2

#### Affected browser(s)
ALL

**Comment by PaulDalek** [comment]
Hi @crohit7 

Thank you for reporting this issue. Can you send a demo where tooltip behaves just as it can be seen in the provided image? Thanks.

**Comment by crohit7** [comment]
@PaulDalek please find the live demo below.
The tooltip content gets hidden when it overflows. Try removing overflow hidden from div container in inspect. 
https://jsfiddle.net/63u58n1y/

**Comment by KacperMadej** [comment]
To recreate the problem `outside` for the tooltip should be set to `true`.

Minimal demo: https://jsfiddle.net/BlackLabel/0gcf654v/

Workaround - don't use `useHTML`: https://jsfiddle.net/BlackLabel/0gcf654v/1/
or set `width` in the tooltip's style (demo based on the @crohit7 's code): https://jsfiddle.net/BlackLabel/v5ntez7f/

Please let us know if the workarounds are working for your case and if not please provide more info about the problem and a live demo.

_Internal note:_
Short description: `useHTML: true` + `outside: true` might cause wrong tooltip box/callout size.

**Comment by crohit7** [comment]
@KacperMadej Workaround - don't use useHTML worked for me.
Thanks for the fix
