### ISSUE TITLE
Heatmap point border doesnt work in newer versions

### ISSUE THREAD

**Issue by h11a** [highcharts/highcharts#14812]
#### Expected behaviour
I try to add a border colour using the following code when a user clicks on a point. 

```
events: {
        click: function(event) {
                this.borderColor = thiss.selectedBorderColour;
                this.update();
        },
    }
```
Which worked in version "8.0.4" no longer works since i updated to "^8.2.2".

Also when i mouseover the square shapes change size and become larger/have different widths/heights, which is also new behavior i cant find a way of preventing.
#### Actual behaviour
the border is no longer added and the hover makes the shapes become different sizes. This did not happen in the previous version. 

#### Product version

Highcharts: "^8.2.2"

#### Affected browser(s)
Chrome, although I have not tried others

**Comment by PaulDalek** [comment]
Hi @h11a

Thank you for contacting us and reporting this issue. Since [v8.1.0](https://www.highcharts.com/blog/changelog/#highcharts-v8.1.0), the heatmap points can have a different marker symbol, so setting the border color of a point is now done through the [`marker.lineColor`](https://api.highcharts.com/highcharts/series.heatmap.marker.lineColor) option. As for your second problem, could you provide us with the demo where on hover action the size of a point changes? Thanks.

**Demo**
https://jsfiddle.net/BlackLabel/f8nrs7um/

**Comment by h11a** [comment]
Thanks for replying @PaulDalek, the lineColor has fixed the one problem :). The hover effect can actually be seen in your example. 

If you select the bottom left point and the mouseover the point above it, you lose the top red border and end up with this (I think because the square above has become larger). The effect also persists after the mouse leaves the point. 

![image](https://user-images.githubusercontent.com/52792193/102331663-0873bb00-3f83-11eb-82d6-9552e335f7c6.png)

If you have a lot of squares and you mouseover the row it can really make the heatmap look bad. It wasn't doing this in earlier versions.

**Comment by PaulDalek** [comment]
@h11a

Each tile of a heatmap series is a path which can have the `stroke-width` set. They are placed next to each other, so in case the border width is set to a value higher than 0, they overlap. Hovering on a specific element simply puts it upfront giving the described effect (run the first demo below and click on the middle point and then hover over all points around it). In that situation you can decrease the width and height of points by using the [`colsize`](https://api.highcharts.com/highcharts/series.heatmap.colsize) and [`rowsize`](https://api.highcharts.com/highcharts/series.heatmap.rowsize) options.

**Demos**
https://jsfiddle.net/BlackLabel/phfz04cd/
https://jsfiddle.net/BlackLabel/4xund0gv/ - different `colsize` and `rowsize`

**Comment by h11a** [comment]
Thanks @PaulDalek... its all working now!
