### ISSUE TITLE
The tick positions aren't calculated correctly, when using big numbers

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#14819]
When you want to display the data point value is big (e.g. 2.3E+306) the whole axis and each of the corresponding series is invisible. It is hard to find the exact threshold when the ticks start to behave strangely, because it depends on some additional factors, like if there are some extra axes if there are tickAmount or tickInterval properties defined if the type of the axis is defined to be logarithmic, etc. 

#### Demos where the issue is reproduced
https://jsfiddle.net/BlackLabel/pz19u8cw/
https://jsfiddle.net/BlackLabel/6f8cak1d/

#### Product version

v8.2.2
#### Affected browser(s)
all

**Comment by KacperMadej** [comment]
The max value for JavaScript is 2^1024 (just under 1.8e308). If that value is exceeded during ticks placement and axis range calculation then it results in a number being `Infinity` and this might cause problems.

For big numbers you could use suffixes in the labels format or add info in the axis title. For example when y axis should display population in millions then the info is added to the axis title and the ticks show values divided by a million.

Another option would be to use [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt), but Highcharts doesn't use nor support this number format.

Could you share a real live case when the JS number limitations are causing problems for a chart? We might be able to suggest some workaround and get to know the problem better.
