### ISSUE TITLE
Tooltip pointFormatter not using the current candlestick color

### ISSUE THREAD

**Issue by SoftDevDanial** [highcharts/highcharts#14826]
Hi,

Here is the link to the Highchart forum. It contains the problem that i found for the upColor candlestick for the tooltip.

https://www.highcharts.com/forum/viewtopic.php?p=162437#p162437

**Comment by KacperMadej** [comment]
Hi @SoftDevDanial 

Thank you for reporting the problem.

1. Getting the color for the tooltip:

In general, you could extract the color of the point directly from the graphic. `point.graphic.stroke` for format options like pointFormat:

```js
tooltip: {
	pointFormat: '<span style="color:{point.graphic.stroke};">O: {point.open}</span>'
}
```

Demo: https://jsfiddle.net/BlackLabel/3ero8xcn/1/

This could be used as a workaround and in case you are using a custom format or formatted for the tooltip.

2. The bug - wrong default tooltip color being used.

The border of the tooltip box should have the same color as the hovered point and `upColor` is not used correctly in those cases. 

_Internal note:_
See how `negativeColor` options is respected while the `upColor` should be used: https://jsfiddle.net/BlackLabel/3ero8xcn/2/
