### ISSUE TITLE
yAxis.stackLabels not working with chart.polar enabled.

### ISSUE THREAD

**Issue by praveenvitara** [highcharts/highcharts#14835]
#### Expected behaviour
stackLabels should be displayed at end of bars

#### Actual behaviour
stackLabels are not rendered on enabling polar mode

#### Live demo with steps to reproduce
https://jsfiddle.net/praveenx9/wvy4q59e/6/

#### Product version
HC 8.1.2

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @praveenvitara 

Thank you for reporting the problem.

As a workaround, you could edit the format of the top-most series' dataLabels and display totals there. Demo: 
https://jsfiddle.net/BlackLabel/szkud7to/1/

_Internal note:_
The stack labels are rendered but are not positioned as they are calculated to be outside of the plot area (?).
