### ISSUE TITLE
Heatmap's coloraxis legend flips the order with every update

### ISSUE THREAD

**Issue by ktakahashimtb** [highcharts/highcharts#14834]
#### Expected behaviour
Heatmap renders coloraxis in the order specified with [colorAxis.reversed](https://api.highcharts.com/highcharts/colorAxis.reversed) option.

#### Actual behaviour
Heatmap alternates the color-axis order every time update happens.

#### Live demo with steps to reproduce
Here is a demo of how we ran into this issue when Heatmap is created through Highcharts React wrapper.
(please press the update button several times to see the issue)

https://stackblitz.com/edit/highcharts-heatmap-coloraxis-flipping?file=src/App.js

This is a more stripped down version, calling [Chart.update](https://api.highcharts.com/class-reference/Highcharts.Chart#update) manually, simulating Hightcharts React wrapper updating the chart.

https://jsfiddle.net/ktakahashimtb/c5osgm0v/

It appears that, in order to cause this issue, the colorAxis.reversed option needs to be set to a non-default value, and also [colorAxis.tickPositions](https://api.highcharts.com/highcharts/colorAxis.tickPositions) need to be set.   There may be other properties besides tickPositions, which can also trigger this issue.

This happens with both 'vertical' or 'horizontal' [layout](https://api.highcharts.com/highcharts/colorAxis.layout)

Also, the issue seems to start happening only from the second update.  It does not happens on the first update.

#### Product version
Highcharts & Highstock, with currently released version:  8.2.2

#### Affected browser(s)
Chrome, Firefox, Edge, Safari

**Comment by KacperMadej** [comment]
Hi @ktakahashimtb 

Thank you for reporting the problem.

Minimal demo for the problem (using the current version):  https://jsfiddle.net/BlackLabel/v2uLbsct/1/
(after 1 second the color changes - ok, and the color axis flips - bug)

This is a regression. The last version working correctly is 7.1.1: https://jsfiddle.net/BlackLabel/v2uLbsct/

Bisected to commit b8e8972b35
(fyi @sebastianbochan )
