### ISSUE TITLE
Grouped column with pareto issue

### ISSUE THREAD

**Issue by manikandanvengatesan** [highcharts/highcharts#14841]
#### Expected behaviour
Pareto point is not starting based on the base series index. In the below fiddle example I want the pareto point to start on middle of first column(Complaint 0 series)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/30241688/102893362-79d1d300-4487-11eb-9a55-ad5f5dcfa4ae.png)

Pareto point starting in between the grouped column

#### Live demo with steps to reproduce
https://jsfiddle.net/manikandan_vengatesan/h7aj30xL/

#### Product version
V8.22

#### Affected browser(s)
All browsers

**Comment by KacperMadej** [comment]
Hi @manikandanvengatesan 

Thank you for reporting the problem.

As a workaround, you could set `pointPlacement` for the pareto series to `-0.15`.
Demo: https://jsfiddle.net/BlackLabel/3hwn6ztg/

_Internal note:_
The same feature is working correctly in error bar series - https://jsfiddle.net/BlackLabel/b23zrwg9/

**Comment by manikandanvengatesan** [comment]
> Hi @manikandanvengatesan
> 
> Thank you for reporting the problem.
> 
> As a workaround, you could set `pointPlacement` for the pareto series to `-0.15`.
> Demo: https://jsfiddle.net/BlackLabel/3hwn6ztg/
> 
> _Internal note:_
> The same feature is working correctly in error bar series - https://jsfiddle.net/BlackLabel/b23zrwg9/

What is the Highcharts version used on this fiddle?

**Comment by KacperMadej** [comment]
Right, good point. The version is the next release candidate. The next release is planned in Q1 2021. The workaround is based on a fix present in the next release candidate and is not available in the current (8.2.2) version.

To get a working workaround in the current version of Highcharts please also add `pointRange: 1` - demo: https://jsfiddle.net/BlackLabel/3hwn6ztg/1/

I must have left the script paths after testing the problem on different code versions (next release candidate included). I am sorry about the confusion. You can use the next release candidate, but please note that it's not stable and is constantly changing.

**Comment by manikandanvengatesan** [comment]
Thanks @KacperMadej. Just a note, when you have both Pareto and Error bar on the same series we have the same issue with error bar as well.

**Comment by KacperMadej** [comment]
@manikandanvengatesan 
Could you share a live demo for this? I am unable to recreate it - it works well for me: https://jsfiddle.net/BlackLabel/b23zrwg9/2/
