### ISSUE TITLE
getting error while implementing dependency wheel  "Type '[string, string, number]' has no properties in common with type 'SeriesSankeyPointOptionsObject'.ts(2559)"

### ISSUE THREAD

**Issue by ashrafmansuri7272** [highcharts/highcharts#14849]
Type '[string, string, number]' has no properties in common with type 'SeriesSankeyPointOptionsObject'.ts(2559)

![image](https://user-images.githubusercontent.com/60643228/103175652-90b26400-4891-11eb-8812-fd61f538d83f.png)

![image](https://user-images.githubusercontent.com/60643228/103175665-aaec4200-4891-11eb-9655-44df8afe13e2.png)

**Comment by sebastianbochan** [comment]
Hi @ashrafmansuri7272,
Could you reproduce your example as a live demo?

**Comment by ashrafmansuri7272** [comment]
Hi @sebastianbochan I am getting error because of type thing the data we provide in the series is giving error with the type
so I just need to know am i missing some module to import 
or you can provide me a working dependency chart in the way providing the highChartOptions to highchart.chart

**Comment by bre1470** [comment]
Hi @ashrafmansuri7272 !
Take a look in the API documentation: https://api.highcharts.com/highcharts/series.dependencywheel.data
The data option of dependencywheel supports only objects.

**Comment by mrpeabody** [comment]
> Hi @ashrafmansuri7272 !
> The data option of dependencywheel supports only objects.

This is not true. Look at any JSFiddle example of this series type. Arrays can be used along with the `keys` param set: https://api.highcharts.com/highcharts/series.dependencywheel.keys

**Comment by bre1470** [comment]
True, good point. This will then internally construct objects. The typing gets complicated though, as an array will only be valid, when the keys are defined. It is hard to put this into a type, as you can not overload interfaces. So you end up with multiple interfaces with different names for mostly the same series options.

Maybe if we have a generic option set for the combination of `keys` and `data` array, it could become easy enough.

**Comment by nithin-neewee** [comment]
![image](https://user-images.githubusercontent.com/89136881/147200399-cadd9d64-4210-4388-a2ae-598c83a3d716.png)
Hi All,
I am not able to figure out why this error is comming - and also in angular tryying to implement this Kindly please help.

Type '[string, string]' has no properties in common with type 'SeriesSankeyPointOptionsObject'.ts(2559)

**Comment by nithin-neewee** [comment]
@sebastianbochan  can you guide me on the above error.

**Comment by ashrafmansuri7272** [comment]
Hi Nithin it’s simple issue you just need to import some dependencies it
will work

**Comment by nithin-neewee** [comment]
@ashrafmansuri7272 what is the dependency, can you mention - I am really stuck with it, it would be great help

**Comment by KacperMadej** [comment]
As already explained by **bre1470**, TS definitions support and allow only an object while the code works fine with the `keys` + `data: array[]`. To suppress the TS error cast to `any`.

**Comment by nithin-neewee** [comment]
ok @KacperMadej Thanks for the reply, I will add and check it.
