### ISSUE TITLE
IE11 exportChartLocal() broken in 7.2.2

### ISSUE THREAD

**Issue by senyahnoj** [highcharts/highcharts#14843]
#### Expected behaviour

Custom button which activates a offine export of the chart to PNG should work in IE11.

This functionality worked in highcharts 7.2.1 but on upgrade to 7.2.2 it ceased working.

This is using the exportChartLocal() function.

#### Actual behaviour

Export to PNG button does nothing. It works fine in other browsers except IE11 (e.g. latest firefox, chrome and edge).

#### Live demo with steps to reproduce

I'm sorry that I have been unable to produce a live demo in either jsfiddle or codepen because they both don't seem to support IE11 any more!

So I will have to include inline HTML code examples:

So here is the code using v7.2.2 which the button does not work as expected

```html
<!DOCTYPE html>
<html>
<head>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/highcharts@7.2.2/highcharts.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/highcharts@7.2.2/modules/exporting.js"></script>
<script src="https://cdn.jsdelivr.net/npm/highcharts@7.2.2/modules/offline-exporting.js"></script>

</head>
<body>
<figure class="highcharts-figure">
    <button type="button" id="export-png">Export to PNG</button>
    <div id="container"></div>
</figure>
<script>
var chart = Highcharts.chart('container', {
    exporting: {
        chartOptions: {
            plotOptions: {
                series: {
                    dataLabels: {
                        enabled: true
                    }
                }
            }
        },
        sourceWidth: 400,
        sourceHeight: 300,
        scale: 1,
        fallbackToExportServer: false
    },
    title: {
        text: 'Offline export'
    },
    chart: {
        type: 'area'
    },
    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
            'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },
    series: [{
        data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 126.0, 148.5, 216.4, 194.1, 95.6, 54.4]
    }]
});
$('#export-png').click(function () {
    chart.exportChartLocal();
});
</script>
</body>
</html>
```

1. Save the above HTML to a file and run in the latest IE11. 
2. You will see that there is a button on the top-left hand corner of the page called 'Export to PNG'. Please click this.
3. You will see that nothing happens :(

To confirm that this isn't a bug in 7.2.1 please change the version in the above CDN sources to be 7.2.1 and repeat the test. You will see that the "Export to PNG" button works as expected when the version is downgraded.

I hope this is acceptable way of getting the bug report to you. Many thanks for your help.

#### Product version

Highcharts 7.2.2

#### Affected browser(s)
 
IE11

**Comment by KacperMadej** [comment]
Hi @senyahnoj 

Thank you for reporting the problem.

Version 7.2.2 is not updated to the official CDN and the missing file is not loaded from https://code.highcharts.com/7.2.2/lib/rgbcolor.js

FYI @TorsteinHonsi  - another reason to have 7.2.2 on the official CDN.

As a workaround, you could use the 3rd party libraries as provided on the CDN that you are using or to a different Highcharts version (e.g. 7.2.1). The options API reference: https://api.highcharts.com/highcharts/exporting.libURL

```js
    exporting: {
        libURL: 'https://cdn.jsdelivr.net/npm/highcharts@7.2.2/lib',
...
```

I have tested the above option and it works correctly in IE11.

**Comment by senyahnoj** [comment]
Thank you so much for your response. Happy for this ticket to be closed now :)

We're not actually using CDNs in our implementation but we've added the following extra libraries from the npm package for our build

- rgbcolor.js
- canvg.js
- jspdf.js
- svg2pdf.js

So it's now working all fine from our end.

(Thanks too in advance for putting 7.2.2 on your CDN. I was confused to start with when I couldn't find it and had to go to a third party one).

Wishing you and all at Highcharts a very Merry Christmas!
