### ISSUE TITLE
Gauge: yAxis extremes not as set in options

### ISSUE THREAD

**Issue by MaxCode-fan** [highcharts/highcharts#14847]
test url : https://jshare.com.cn/demos/hhhhiD

当我尝试重新更新仪表盘的最大值的时候发现了这个BUG
I found this bug when I tried to update the maximum value of the dashboard again

经过在官方的测试地址验证,确实存在此问题
After verification in the official test address, this problem does exist

当我尝试将最大值更新为60的时候,我发现最大值不能正常展示
When I tried to update the maximum value to 60, I found that the maximum value could not be displayed normally
![image](https://user-images.githubusercontent.com/57091336/102985118-9a626180-4549-11eb-9b4d-5ed700b2f268.png)

更新为40的时候,最大值消失了
When it is updated to 40, the maximum value disappears
![image](https://user-images.githubusercontent.com/57091336/102985212-c54cb580-4549-11eb-9ec8-5c393e39844d.png)

我不知道为什么会这样,麻烦官方尽快处理,谢谢
I don't know why this happened. Please deal with it as soon as possible. Thank you

**Comment by KacperMadej** [comment]
Hi @MaxCode-fan 

Thank you for reporting the problem and translating into English.

Axis min and max are not the same as tick and axis labels placement, but this could be easily resolved by `ticksPositions` matching `min` and `max` options like in the code below:

```js
var chart1 = Highcharts.chart('container-speed', {
	yAxis: {
		min: 0.1,
		max: 187.23,
		tickPositions: [0.1, 187.23],
```

This allows setting any `min`, `max` with matching labels and axis range.

I wanted to create an updated demo in the same platform that you have used, but I unable to set up an account there. However, the above code was tested.

This doesn't look like a bug and the issue will be closed. For more questions about Highcharts please try reaching our technical support: https://www.highcharts.com/blog/support/

**Comment by MaxCode-fan** [comment]
> 嗨@ MaxCode-fan
> 
> 感谢您报告问题并翻译成英文。
> 
> 轴的最小值和最大值与刻度和轴标签的放置位置不同，但是可以通过`ticksPositions`匹配`min`和`max`选项（如下面的代码）轻松解决：
> 
> ```js
> var  chart1  =  Highcharts 。图表（'容器速度' ， { 
> 	Y轴：{
> 		分钟：0.1 ，
> 		最大值：187.23 ，
> 		tickPositions：[ 0.1 ， 187.23 ] ，
> ```
> 
> 这样就可以设置任何`min`，`max`并带有匹配的标签和轴范围。
> 
> 我想在与您使用的平台相同的平台上创建一个更新的演示，但无法在该平台上设置帐户。但是，上面的代码已经过测试。
> 
> 这看起来不像是一个错误，问题将被解决。有关Highcharts的更多问题，请尝试与我们的技术支持联系：[https](https://www.highcharts.com/blog/support/) : [//www.highcharts.com/blog/support/](https://www.highcharts.com/blog/support/)

Thank you very much. This problem has been fixed by setting the options
