### ISSUE TITLE
Can't extend navigator range

### ISSUE THREAD

**Issue by Myndale** [highcharts/highcharts#1484]
The documentation states that the navigator xAxis options should be the same as for any other xAxis but if I try to set the min/max values in order to increase the scroll area it doesn't work, the navigator scrollbar snaps to the range of visible values:

http://jsfiddle.net/Wgkqc/

(Note that the range in the main chart is 2000-2017 whereas for the navigator it's 2004-2010).

Is this a bug? Or is there another way to do this?

**Comment by pawelfus** [comment]
This is caused by `ordinal` axis. In fact, extremes are probably set, but ordinal axis utilizes space to place evenly all of the points. Simple `ordinal: false` resolves issue: http://jsfiddle.net/Wgkqc/1/
