### ISSUE TITLE
Allow call to defaultPositioner from TooltipPositionerCallbackFunction

### ISSUE THREAD

**Issue by causbas** [highcharts/highcharts#14848]
# Description of the feature
It would be helpful to call the function `defaultPositioner` from a custom positioner function (type `TooltipPositionerCallbackFunction`), e.g. when I like to fix the tooltip position only on one axis. Unfortunately, this is not really possible. `defaultPositioner` is not part of the public interface of `Tooltip` and the required arguments are different than those of `TooltiPositionerCallbackFunction`.

# Library related to the feature
Highcharts

**Comment by KacperMadej** [comment]
Hi @causbas 

Thank you for submitting the feature request.

The default tooltip position for **shared** or **standard** tooltip could be obtained by calling `tooltip.getPosition` with the same arguments as the ones available in the `positioner` function. Demo: https://jsfiddle.net/BlackLabel/9nzbhf80/

Relevenat code part: 
```js
 tooltip: {
   positioner: function() {
     var pos = this.getPosition.apply(this, arguments);
```

For **split** tooltip, the default position is placed in a scope that is not accessible - one would have to copy the source code to use it.

**Comment by causbas** [comment]
Thanks for the answer! This was really helpful. The method `getPosition` is marked private and it does not seem to be part of the public interface of `Tooltip`. 

https://github.com/highcharts/highcharts/blob/f4f7ca81a71dfad0ebcb6a6fd0a6ae6c5df6bc28/ts/Core/Tooltip.ts#L838

Would you mind making it public so there is full typing support via Typescript?

**Comment by sebastianbochan** [comment]
@bre1470 what do you think about it ?

**Comment by bre1470** [comment]
`Tooltip.getLabel` is public, so imho it would be reasonable to have `Tooltip.getPosition` public as well. In the end it is up to @TorsteinHonsi to decide.

@causbas 
In the meantime you can do the following to be typesafe:
```ts
declare module 'highcharts' {
    /**
     * Place the tooltip in a chart without spilling over
     * and not covering the point it self.
     */
    interface Tooltip {
        getPosition(boxWidth: number, boxHeight: number, point: Point): PositionObject;
    }
}
```
