### ISSUE TITLE
Axis label unnecessary ellipsis

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#14854]
#### Expected behaviour
Axis labels only display ellipsis when there is not enough space to display the full label

#### Actual behaviour
In numeric x-axis the last label goes to ellipsis when there is enough space to display the full label

#### Live demo with steps to reproduce
See http://jsfiddle.net/kzoon/5qd1yrp8/

When you enable textOverflow: 'none', it is clear that there _is_ enough space to display the full label: http://jsfiddle.net/kzoon/5qd1yrp8/14/
Playing around with label padding doesn't change anything.

#### Product version
Highcharts latest

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @kzoon,
Thank you for reporting. The problem is more complicated, because of many options there like "overflow".

**Internal note:** 
We can consider the edit function and add the marginRight condition. What do you think @TorsteinHonsi ?

https://github.com/highcharts/highcharts/blob/f4f7ca81a71dfad0ebcb6a6fd0a6ae6c5df6bc28/ts/Core/Axis/Axis.ts#L6558-L6600

**Comment by TorsteinHonsi** [comment]
Sorry for the late reply @sebastianbochan .

> We can consider the edit function and add the marginRight condition.

That would allow us to extend the label outside the plot area, but I don't think it would look good. It would overflow the `spacing` setting. 

> When you enable textOverflow: 'none', it is clear that there is enough space to display the full label

Yes apparently, but the way the current label placement works, is that each label is given a slot to render inside. The limit between the slots is half way between the tick marks. So in http://jsfiddle.net/highcharts/e5uzn7jm/, the last label doesn't overlap the previous label, but it does overlap the previous slot. If we add some zeroes to the labels, we see the effect: http://jsfiddle.net/highcharts/e5uzn7jm/1/

**Comment by kzoon** [comment]
So, essentially the problem is that in numeric axes the slot of the last axis label is smaller then the other slots, because the axis ends on the tick. 
The effect is that the most important label (i.e. the one showing the axis max) is cut off. My users can't understand that this happens when there seems to be enough room to render it.

Some change or option to work around this would be much appreciated. From a functional point of view I would be helped with either of the following:

- Don't cut off the last label when there is enough room left to render it without overlapping the previous.
- An option that allows the label to extend beyond the plot area, but not beyond the chart itself
