### ISSUE TITLE
Annotation with default shape 'callout' and align: 'right' don't display the line to point

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#14858]
When an annotation is displayed with the shape: 'callout' and align: 'right', the line, that should indicate the original anchor place is not displayed. 

#### DEMO
https://jsfiddle.net/BlackLabel/abyfm931/

#### Product version
HC v8.2.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Deep down, it's a bug with the `callout` shape: https://jsfiddle.net/BlackLabel/abyfm931/4/

For even border-width the same happens with left-aligned annotations: https://jsfiddle.net/BlackLabel/abyfm931/5/

**Comment by himmxt** [comment]
This bug appears to still exist -- is it possible to have the developers take another look? It would be hugely appreciated

**Comment by KacperMadej** [comment]
@himmxt 
Sure, we will take another look. I have checked the top demo and I am unable to recreate the problem. Please add a live demo.

**Comment by himmxt** [comment]
@KacperMadej Thank you so much -- does the bug show up for you in this demo? https://jsfiddle.net/fbqpt0ed/ (For the "LOREM IPSUM" annotation)

**Comment by KacperMadej** [comment]
With fixed with of 660px it shows for me as you have described - https://jsfiddle.net/BlackLabel/3xjeygbt/1/
Tested on Win10/Chrome.

As a **workaround**, you could adjust `x` to `-1` or less (for me `-1` is enough but I have not tested all browsers).
Demo: https://jsfiddle.net/BlackLabel/3xjeygbt/

_Internal note:_
The edge case for the callout shape is for anchor placed under a corner: https://jsfiddle.net/BlackLabel/abyfm931/6/

**Comment by ryanwhitemedia** [comment]
I still get thus issue years later. Not fixed? Is there a right-callout shape I can use?
<img width="195" alt="Screenshot 2024-11-19 at 11 23 27 AM" src="https://github.com/user-attachments/assets/44382b4c-6f05-4cc8-a81e-c8dab0612264">

**Comment by pawelfus** [comment]
The original bug was fixed in v8, and the edge case in v11.2.0. Ccould you check your version and let us know?

If you have the latest one, please recreate the issue in jsFiddle, we will look into that. Thanks!
