### ISSUE TITLE
Highstock - data grouping causes fake data points outside visible range

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#1486]
Demo: http://www.highcharts.com/jsbin/uhetih/8/edit

Click the set extremes button. Note the columns on either sides of the navigator view. The columns also have tooltips, but the date value doesn't correspond to the real data. 

If data grouping is disabled on the column series, it works like expected.

**Comment by oysteinmoseng** [comment]
Seems to be working as expected with current code.
