### ISSUE TITLE
Panning the map up and down after panning enabled programmatically

### ISSUE THREAD

**Issue by pterenin** [highcharts/highcharts#14861]
Hi. I want to disable by default panning for  Highmaps and enable it by button click:
    `chart.update({
      chart: {
        panning: true
      }
    });`
But once panning option is introduced panning y-axis does not work

#### Expected behavior
 Highmaps should pan up and down

#### Actual behaviour
Panning y-axis does not work when chart.panning is enabled or if it's updated on the fly

#### Live demo with steps to reproduce
Try to zoom in and pan map up and down
https://jsfiddle.net/PavelT1983/efxh3m05/2/

#### Product version
 Highmaps

#### Affected browser(s)
Google Chrome is up to date
Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by pawelfus** [comment]
Hi @pterenin 

Thank you for reporting the issue. This is caused by setting `panning=true`. That resolves to `panning: { enabled: true, type: 'x' }`. Instead use `panning: { enabled: true, type: 'xy' }`, demo: https://jsfiddle.net/BlackLabel/fbe1ps4t/
