### ISSUE TITLE
How to add "scrollbar" to "heatmap" in React?

### ISSUE THREAD

**Issue by yuvalr55** [highcharts/highcharts#14863]

**Comment by pawelfus** [comment]
Hi @yuvalr55 

I am afraid, you don't use Highcharts, are you sure you did report this in the correct repo? This is Highcharts repository, not ApexCharts (?).

Anyway, to use Scrollbar feature with Highcharts, you need Highcharts Stock. All you would need to change is: `import Highcharts from 'highcharts'` -> `import Highcharts from 'highcharts/highstock'`

**Comment by yuvalr55** [comment]
> import :
> 
> ```
> import Chart from 'react-apexcharts'
> ```
> 
> I added this code in "options":
> 
> ```
>   scrollbar: {
>                     enabled: true
>                 },
> ```
> 
> And this code too
> 
> ```
>   yAxis: {
>                     categories: this.props.series.map(data=>data.name),
>                     title: null,
>                     min: 0,
>                     max: 5,
>                     scrollbar: {
>                         enabled: true
>                     }
>                 }
> ```
> 
> And the "scrollbar" is not added.
> 
> **Why in react it does not work?**
> 
> jsx:
> 
> ```
>   <Chart options={this.state.options} highcharts={Highcharts} series={this.state.series} type="heatmap" width="100%" height={70+this.state.series.length*35} />
> ```
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/59453585/103415977-2cdbb400-4b8d-11eb-8ef6-696afd3c8de1.jpg)



> _No description provided._

**Comment by rahulsingh806080** [comment]
> Hi @yuvalr55
1.Is highstock we need to purchase seperately
2. scrollablePlotArea: can we use this desktop. I can see its scrolling is working there but scrollbar is not visible
> 
> I am afraid, you don't use Highcharts, are you sure you did report this in the correct repo? This is Highcharts repository, not ApexCharts (?).
> 
> Anyway, to use Scrollbar feature with Highcharts, you need Highcharts Stock. All you would need to change is: `import Highcharts from 'highcharts'` -> `import Highcharts from 'highcharts/highstock'` (if you use Highcharts of course).

**Comment by pawellysy** [comment]
HI @rahulsingh806080, thanks for contacting us with your question!
We use GitHub to track bugs and feature requests.
Your issue however looks like a typical support question.
Please prepare a demo with your issue in some online code editor and use [one of the available support channels ](https://www.highcharts.com/blog/support/)where our support engineers are going to help you with that.
Thanks for understanding!
