### ISSUE TITLE
Datetime: date on crosshair decreased by 1

### ISSUE THREAD

**Issue by valoakenfold** [highcharts/highcharts#14864]
#### Expected behaviour
I use Area with negative values (https://www.highcharts.com/demo/area-negative)
Data in my array (maked from sql db by php) has timestamp values. I choose xAxis type as 'datetime' and transmit pairs [timestamp, value] to JS script.
It's ok: xAxis has right values, and I think labels on chart points (when crosshair is on it) must match. 

#### Actual behaviour
Date values on chart points (when crosshair is on it) are decreased by one day.

#### Live demo with steps to reproduce
https://jsfiddle.net/xbeam/t4kyh0po/10/

example:
FIrst Timestamp in Series in each Data is 1609448400000 - it's 01/01/2021. And it's right on xAxis. Bun on chart point (crosshair) it is 31/12/2020.
Another points has the same behavour.

**Comment by PaulDalek** [comment]
Hi @valoakenfold 

Thank you for contacting us and reporting this issue. If you hover over a specific point, you will see that it’s timestamp is different from the nearing `xAxis` label. If you want both, point and label, to be aligned, you can set custom tick positions using such options as [`tickPositions`](https://api.highcharts.com/highcharts/xAxis.tickPositions) or [`tickPositioner`](https://api.highcharts.com/highcharts/xAxis.tickPositioner).

**Demo**
https://jsfiddle.net/BlackLabel/d81p2ytn/
