### ISSUE TITLE
yAxis.tickPositions is not respected when panning enabled

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#14860]
#### Expected behaviour
Ticks should be set as defined in `yAxis.tickPositions` array.

#### Actual behaviour
`yAxis.tickPositions` is not respected.

#### Live demo with steps to reproduce
v8.1.0 -> http://jsfiddle.net/BlackLabel/9tnqefpm/
v8.0.4 -> http://jsfiddle.net/BlackLabel/an4moj2w/

#### Product version
above Highcharts v8.1.0

Bisected to commit: https://github.com/highcharts/highcharts/commit/23d46326a5da50eacf85fe5052d0e247197d369e

**Comment by PaulDalek** [comment]
Already fixed on master.

**Demo**
http://jsfiddle.net/BlackLabel/szo56b9h/
