### ISSUE TITLE
minPointLength not showing bar in case of zero value for scenario where one series has all zero values and other has all negative values

### ISSUE THREAD

**Issue by kartik468** [highcharts/highcharts#14876]
#### Expected behaviour
minPointLength should show small bar in case of zero values

#### Actual behaviour
minPointLength not showing small bar in case of zero values

#### Live demo with steps to reproduce

https://jsfiddle.net/4z5s80ra/

`xAxis: {
        categories: ['c1', 'c2', 'c3']
    },
    series: [
    	{
      	name: 's1',
        data : [0, 0, 0]
      },
      {
      	name: 's2',
        data: [-12, -13.4, -5]
      }
    ],
    plotOptions: {
    	series: {
      	minPointLength: 2
      },
      column: {
      	dataLabels: {
        	enabled: true
        }
      }
    }`

When all values of one series has zero values and other series has only negative values then var is not appearing.
If one of the value is non zero then it works as expected

FYI
When all values of one series has zero values and other series has only negative values then var is not appearing.
![image](https://user-images.githubusercontent.com/8514301/103734389-ea452c00-5011-11eb-800b-22b99aff851f.png)

If one of the value is non zero then it works as expected
![image](https://user-images.githubusercontent.com/8514301/103734448-0517a080-5012-11eb-8b32-aa2c983e7655.png)

#### Product version

highcharts: 8.2.2 and 7.2.0

#### Affected browser(s)
chrome

**Comment by sebastianbochan** [comment]
Hi @kartik468,
Thank you for reporting. It looks like regression.

It looks like related with the https://github.com/highcharts/highcharts/issues/10646

Last working demo: v7.1.1
- https://jsfiddle.net/BlackLabel/f3rmwxas/

FYI @KacperMadej
