### ISSUE TITLE
Highstocks: Crosshair label formatter, current price indicator

### ISSUE THREAD

**Issue by rogerwalt** [highcharts/highcharts#14880]
I stumbled upon this issue while trying to define a formatter for the current price indicator label. Is there a way do that..?

#### Expected behaviour
I expect crosshair labels and current price indicator labels to work independently.

#### Actual behaviour
Using the current price indicator overwrites the defined crosshair label formatter.

#### Live demo with steps to reproduce
http://jsfiddle.net/rogerwa/t3oghkzr/1/

1. Hover your mouse over the plot and notice how the crosshair label formatter on the yaxis works as expected.
2. Enable current price indicators.
3. Hover over the plot and notice that the current price indicator now moves with the crosshair. Expected: Second label for the crosshair, with the correct formatter.
4. Disable current price indicators.
5. Hover over the plot and notice that the crosshair label formatter is no longer visible.
6. Enable current price indicators.
7. Notice that no current price indicator label is visible anymore.

#### Product version
Highstocks v8.2.2

#### Affected browser(s)
Chrome v87
Firefox v84

**Comment by KacperMadej** [comment]
Hi @rogerwalt 

Thank you for reporting the problem.

The format should be possible to set in https://api.highcharts.com/highstock/series.line.lastVisiblePrice.label like in this demo: http://jsfiddle.net/BlackLabel/0ody7ax3/

**Workaround**: show the price indicator before hovering over the chart to get 2 labels (indicator + on hover)

The formats are different when using the next release candidate code: http://jsfiddle.net/BlackLabel/0ody7ax3/1/
Please note that the next release candidate code is not stable and is changing frequently.

_Internal note:_
The master code (from GitHub) has different formats (correct) when both labels are shown - http://jsfiddle.net/BlackLabel/0ody7ax3/1/.
This issue could be broken into smaller issues about breaking format, visibility, and adding a working option (and docs) to set format for the indicator's label (http://jsfiddle.net/BlackLabel/0ody7ax3/ - it overrides axis crosshair label format and is not documented - https://api.highcharts.com/highstock/series.line.lastVisiblePrice.label)

**Comment by karolkolodziej** [comment]
The issue is very similar to #13876. Will be resolved after merging the PR.
Demo: https://jsfiddle.net/BlackLabel/t9kfn87L/
