### ISSUE TITLE
When window is resized, Uncaught RangeError error is thrown

### ISSUE THREAD

**Issue by nitinayir8** [highcharts/highcharts#14886]
#### Expected behaviour
On window resize, tree map charts should be displayed

#### Actual behaviour
On window resize, screen goes blank and sunburst.js:21 Uncaught RangeError: Maximum call stack size exceeded
    at sunburst.js:21
    at Array.forEach (<anonymous>)
    at x.buildNode (sunburst.js:21)
    at sunburst.js:21
    at Array.forEach (<anonymous>)
    at x.buildNode (sunburst.js:21)
    at sunburst.js:21
    at Array.forEach (<anonymous>)
    at x.buildNode (sunburst.js:2

Error is displayed

#### Product version
Highcharts Basic v8.2.2 (2020-10-22) 

#### Affected browser(s)
Chrome, Microsoft Edge, Mozilla

**Comment by KacperMadej** [comment]
Hi @nitinayir8 

Thank you for contacting us about the problem.

Please add a live demo for the problem as I am unable to recreate the problem in our default demo (https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/treemap-coloraxis).

You have reported an error in the sunburst module and that demo is also working fine for me (https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/sunburst).
