### ISSUE TITLE
Specifying axis label format breaks thousand separator

### ISSUE THREAD

**Issue by petterw03** [highcharts/highcharts#14893]
#### Expected behaviour
yAxis.labels.format is specified using `{value}`. The values on the labels should adhere to the normal thousands separator rules.

#### Actual behaviour

No thousands separator is used, even though the format option contains nothing more than the default setting `{value}`. Numeric symbols are also not in use, although that part might be by design.

#### Live demo with steps to reproduce
https://jsfiddle.net/zbw23s7h/1/

If the line `format: '{value}'` is removed, the thousands separator works normally.

#### Product version
Highcharts ~8.2.0

#### Affected browser(s)

Tested in Chrome, Firefox, Edge.

**Comment by KacperMadej** [comment]
Hi @petterw03 

The default format is more complex and documentation has a simplified description.

The format closer to the default behavior for the axis type and its range in your demo is `format: '{value:,f}'`.
Demo: https://jsfiddle.net/BlackLabel/np2L10mr/

I am guessing your problem with the formatted might be different than the reported issue, as there is no point in setting the options that would make the chart work the same as without the option, so in case you have a more complex problem with the formatter please share your code.

**Comment by petterw03** [comment]
Hi and thanks for the reply. Your demo seems to be working with my use case, which is to add a suffix to the value label. I kept my demo as simple as possible to show that not even using the unmodified [default value according to the documentation](https://api.highcharts.com/highcharts/yAxis.labels.format) works. 

So it seems that this is more an issue of documentation? I definitely think it is an issue though. This was causing us bugs for several weeks before I managed to pin down the cause.

**Comment by KacperMadej** [comment]
This is definitely an issue and it will remain open until resolved.

The full description in the API reference should be clear enough to avoid this and any confusion.
The feature works as expected, but is not documented clearly enough.
