### ISSUE TITLE
Hided legend item still appears in png export

### ISSUE THREAD

**Issue by fgoulet** [highcharts/highcharts#14894]
#### Expected behaviour
The legend on the exported image should contains only MFST and GOOG.

#### Actual behaviour
The legend on the exported image contains  MFST, AAPL and GOOG.

#### Live demo with steps to reproduce
[repro](https://codepen.io/fgoulet/pen/JjRZXPd)

1. Click "Hide AAPL legend" button.
2. Export the chart in png

#### Product version
 Highstock 8.2.2

#### Affected browser(s)
All

**Comment by PaulDalek** [comment]
Hi @fgoulet

Thank you for contacting us and reporting this issue. In order to update the series’ visibility in the legend section, use the [`update`](https://api.highcharts.com/class-reference/Highcharts.Series#update) function.

**Demo**
https://jsfiddle.net/BlackLabel/q6dx3vmt/
