### ISSUE TITLE
Narrator is not reading the chart label in Edge

### ISSUE THREAD

**Issue by naksenzh** [highcharts/highcharts#14898]
#### In the application as well as in the demo link https://www.highcharts.com/demo/ios/accessible-pie# the title (Label) of the chart is not read by Narrator 
![image](https://user-images.githubusercontent.com/66734515/104045267-950a4580-51de-11eb-8c09-9ebeca585283.png)

Narrator jumps directly to the NVDA 40.6% and skips Primary Desktop/Laptop screen readers

#### Live demo with steps to reproduce is attached
[Highcharts bug.zip](https://github.com/highcharts/highcharts/files/5788621/Highcharts.bug.zip)

#### Product version
Latest as in the website

#### Affected browser(s)
Edge

**Comment by naksenzh** [comment]
@oysteinmoseng could you please help to assign ?

**Comment by oysteinmoseng** [comment]
@naksenzh Apologies if I am misunderstanding, but I believe this is intended behavior? Tabbing should only move between actionable elements, and the chart title is not actionable. If you use arrow keys to scan all elements in the page, the title should be announced by Narrator as expected.

**Comment by naksenzh** [comment]
Thank you for the quick feedback, @oysteinmoseng , could you please share with me the video on how to navigate with arrows to the title? Unfortunately for me it was just announcing the chart values in the round and when I tab, it jumps to the next control element.
