### ISSUE TITLE
stacked labels disappears after update 

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#14890]
#### Expected behaviour
Stack labels shouldn't disappear.

#### Actual behaviour
It looks like since 8.1.1 stacked labels are not working correctly - they are disappearing after performing a specific update. Everything was working correctly in the 8.1.0 version.

#### Live demo with steps to reproduce
1/ Click on the update button
2/ Observe stack labels

**Live demo:**
https://jsfiddle.net/BlackLabel/jay1rbht/

#### Product version
8.2.2

#### Affected browser(s)
All

**Comment by mateuszkornecki** [comment]
Related issue: <br>
https://github.com/highcharts/highcharts-angular/issues/258

**Comment by khlieng** [comment]
Fixed on master (#14414).
