### ISSUE TITLE
groups of columns overlap, when scrollable plot Area width is over 110k

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#14909]
When scrollable plot area minWidth is defined to be over 110k, the groups of columns from the last indexes are getting placed on top of the previous group. The bigger value of the minWidth property, the more groups are rendered on top of each other. 

### Demo
scroll to the last column group, which is visible.
https://jsfiddle.net/BlackLabel/kvemd2o5/

#### Product version
Highcharts JS v8.2.2

#### Affected browser(s)
all

**Comment by jsyvino** [comment]
I am also having this same issue, hoping for a resolution or workaround!

**Comment by PaulDalek** [comment]
Hi @pawellysy, @jsyvino

Thank you for contacting us and reporting this issue. This behavior comes from the range limitation that is set (pixel range from -100000 to 100000) for the available plotting area. It is set to prevent from various rendering issues (see the comment near the `limitedRange` declaration). Setting the `minWidth` to 150000 simply exceeds the available range, therefore all points outside the range will be rendered in one place. As a workaround I’ve modified the `limitedRange` function to accept an additional argument that will be a new range (the `chart.scrollablePixelsX`). Bear in mind that this is not tested and it might cause some rendering problems.

**Workaround**
https://jsfiddle.net/BlackLabel/4ub32djw/

_Internal note_
The `limitedRange` should accept a bigger range in case of the big values of the `scrollablePlotArea.minWidth`.

**Simplified demo**
https://jsfiddle.net/BlackLabel/e39mzvdb/
