### ISSUE TITLE
Inconsistent outcome with 2 Y axes, different widths and legend positions

### ISSUE THREAD

**Issue by benochr** [highcharts/highcharts#14902]
#### Expected behaviour
Rendering charts with different legend positions and different container widths for the same data set should give the same outcome.

#### Actual behaviour
Following ways of rendering a chart on the same data set gives different results:
1. chart with default legend and container width of 800px
2. chart with default legend and container width of 400px
3. chart with right aligned legend and container width of 800px
4. chart with right aligned legend and container width of 400px

The ticks on the primary (left) and secondary (right) Y axis are aligned differently. If you resize the window manually (make it smaller or wider) the alignment sometimes pops into place. In some cases the alignment is then kept when you resize again, but in other cases it breaks again on resize.

For example, the first chart with default legend and width of 800px renders correct initially. It gets corrupted when you make the window smaller (less than 500px). If you then resize it to more than 1000px, it remains wrong. But if you resize it to around 700px, it's back as expected.

For example, the 3th chart with right aligned legend and container width of 800px renders wrong initially. It renders correct when you resize to 450px. After that it remains correct regardless of how you wide you make it.

#### Live demo with steps to reproduce
http://jsfiddle.net/psvrywqo/

#### Product version
Highcharts 8.2.2

#### Affected browser(s)
Chrome, Safari

**Comment by PaulDalek** [comment]
Hi @benochr

Thank you for contacting us and reporting this issue. Please take a look at the following issue: #14216 to understand why this isn’t considered as a bug. If you want to preserve the initial ticks, you can use [`tickPositions`](https://api.highcharts.com/highcharts/yAxis.tickPositions) or [`tickPositioner`](https://api.highcharts.com/highcharts/yAxis.tickPositioner).

**Demo**
http://jsfiddle.net/BlackLabel/5zgL9qe0/
