### ISSUE TITLE
Gantt: animation a triangle symbol in a drop down table on yAxis, after double click.

### ISSUE THREAD

**Issue by hihajdus** [highcharts/highcharts#14904]
#### Expected behaviour
The triangle animation should point to the position of the vertex to the right if the drop down menu is closed.
When the menu is opened, the vertex of the triangle should point downwards.

<img width="432" alt="Screen Shot 2021-01-11 at 4 02 15 PM" src="https://user-images.githubusercontent.com/22296099/104200428-f160a580-5428-11eb-81ee-f28bd94c3418.png">

#### Actual behaviour
When you drop down the menu at the table on yAxis, collapse it and double click it, when it has not collapsed completely, the triangle symbol changes animation.

#### Live demo with steps to reproduce
template: https://jsfiddle.net/BlackLabel/w8zrj0kn/

<img width="432" alt="Screen Shot 2021-01-11 at 4 08 54 PM" src="https://user-images.githubusercontent.com/22296099/104200915-7a77dc80-5429-11eb-9e38-8c7798eec26b.png">

<img width="432" alt="Screen Shot 2021-01-11 at 4 03 09 PM" src="https://user-images.githubusercontent.com/22296099/104200501-0b9a8380-5429-11eb-97a6-496125e1ca01.png">

#### Product version
Highcharts Gantt JS v8.2.2 (2020-10-22)

#### Affected browser(s)
All

**Comment by DJTechnoo** [comment]
Hello @hihajdus This issue seems to have been fixed by itself by a recent commit. Are you still able to reproduce this issue from the latest?

**Comment by hihajdus** [comment]
Hi @DJTechnoo this problem was solved but after tests, I found another similar one.

After double click "New offices", triangle is missing in the "Parent item".

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/oxfm182d/

<img width="432" alt="Screen Shot 2021-01-13 at 11 59 19 AM" src="https://user-images.githubusercontent.com/22296099/104443504-cf853100-5596-11eb-9fc8-e1da1df6d36c.png">

**Comment by DJTechnoo** [comment]
Interesting! Will have a look at it
