### ISSUE TITLE
Ticks not visible when timezoneOffset set.

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#14911]
#### Expected behaviour
Ticks should be visible in the same way as without timezoneOffset.

#### Actual behaviour
Not all ticks are visible.

#### Live demo with steps to reproduce
v6.0.4 - https://jsfiddle.net/BlackLabel/xmo6wb2u/
v6.0.5 - https://jsfiddle.net/BlackLabel/qzvyrpgn/

#### Product version
Highcharts v6.0.5

Bisected to the commit: https://github.com/highcharts/highcharts/commit/3965fda197290c327cb85944277e4cce796fc6d2

**Comment by khlieng** [comment]
Fixed on master (#14731) :)
