### ISSUE TITLE
Small weight value lines not displayed in Sankey chart

### ISSUE THREAD

**Issue by egraether** [highcharts/highcharts#14919]
#### Expected behaviour

The Sankey chart should display every edge with a weight `> 0` using at least a single pixel line.

#### Actual behaviour

If some edge weights are very small compared to others there is no visible node or edge on the chart. Only the data label of the node is visible.

#### Live demo with steps to reproduce
https://jsfiddle.net/j8pdne0c/

#### Product version
8.2.2

#### Affected browser(s)
Chrome (and probably all)

**Comment by PaulDalek** [comment]
Hi @egraether

Thank you for contacting us and reporting this issue. There is an option called [`minLinkWidth`](https://api.highcharts.com/highcharts/series.sankey.minLinkWidth) that allows to set the minimum width of a link.

**Demo**
https://jsfiddle.net/BlackLabel/0s6q19dc/
