### ISSUE TITLE
Labels do not wrap (or cut) after drilldown 

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#14934]
### Expected behaviour
labels words wrap and columns show normal
![image](https://user-images.githubusercontent.com/6030335/104580927-ed25c980-566e-11eb-9309-70e4484427af.png)

### Actual behaviour
labels show full name and columns not visible
![image](https://user-images.githubusercontent.com/6030335/104580886-e1d29e00-566e-11eb-83f2-8b83b6ed63c0.png)

I found my old issue and workaround
https://github.com/highcharts/highcharts/issues/9218

But [here ](https://github.com/highcharts/highcharts/issues/9218#issuecomment-759316735) my answer about workaround (it does not work in different cases)

#### Live demo with steps to reproduce
https://jsfiddle.net/j4Lapgke/

#### Product version
Highcharts JS v8.2.2 (2020-10-22)

#### Affected browser(s)
Google Chrome 87.0.4280.141

**Comment by KacperMadej** [comment]
Hi @balkarov 

Thank you for reporting the problem and opening a new issue for the case.

Minimal demo (with an even worse outcome): https://jsfiddle.net/BlackLabel/5vs2cbag/
Steps: drill into the first point
