### ISSUE TITLE
Chart plotOption value "compare" does not update dynamically

### ISSUE THREAD

**Issue by JustinPhung** [highcharts/highcharts#14932]
**Expected behaviour**
I expect the chart to reload itself when chart.update() is called with different compare options.

**Actual behaviour**
When I change the compare option and I update the chart nothing happens.
Live demo with steps to reproduce

https://codepen.io/justinphung/pen/JjRejJG

Click on button 'Toggle Compare'
Notice that the subtitle changes but the x- and y-axis does not.
When changing the compare value in the code for initializing the chart the x- and y-axis is different after codepen reloads.

**Product version**
Highstock v8.2.2

**Affected browser(s)**
Chrome v87

**Comment by KacperMadej** [comment]
Hi @JustinPhung 

Thank you for reporting the problem.

The issue should be resolved soon and included in the next release.
You could check the fixed code with your demo in here: https://codepen.io/Blacklabel/pen/dypwYXo

**Comment by JustinPhung** [comment]
Hi @KacperMadej,

I have to thank you for fixing the problem so quick!
Me and my Colleges are reporting some bugs here, because we are in a company which is using a licensed highcharts in our product. It is very calming for us to see that you are working on solutions this quick!

**Comment by JustinPhung** [comment]
Hi @KacperMadej,

could you please tell me when the next release will be published?

Thank you for the answer!

**Comment by KacperMadej** [comment]
@JustinPhung 

The next release is planned to be published in a few weeks - in late January or early February.
