### ISSUE TITLE
Gettting a lot of "Cannot read property 'y' of undefined"

### ISSUE THREAD

**Issue by ritox842** [highcharts/highcharts#14938]
#### Expected behavior
The error should be suppressed

#### Actual behaviour
Our logs show this error thousands of times.
From my investigation it's coming from [tick.ts](https://github.com/highcharts/highcharts/blob/ec2b3845069f09a1cf4375b4363797a04c70350b/ts/Core/Axis/Tick.ts), inside the _moveLabel_ method.
We're trying to access the 'y' property of _labelPos_ that probably doesn't exist. 
Please add protection to verify that indeed there's a label before trying to access it.

#### Product version
8.2.2

#### Affected browser(s)
Chrome (Probably all of them).

**Comment by KacperMadej** [comment]
Hi @ritox842 

Thank you for contacting us about the problem.

Please add a live demo with the steps required to recreate the problem.

**Comment by ritox842** [comment]
Hello @kacper

I wasn't able to reproduce it but our production error monitor catches this error in the thousands... I'm guessing it some kind of edge case when the user quiet the page while the label is trying to be shown and then getting the undefined error message.

Can you share more knowledge about what triggers the flow in which _moveLabel_ is called? Screen resize? user action?

**Comment by KacperMadej** [comment]
The function runs on an animation of a label in an axis - could happen when zooming or panning the axis.

I tried to run looped zooming in and out in a demo. It runs moveLabel without any error. A tab with the demo runs the function while running in the background without any errors. Demo: https://jsfiddle.net/BlackLabel/x1f9jesw/

Without a way to recreate the problem, we won't be able to investigate and fix it. Maybe you could edit the demo I have created to get the error you have reported?

**Comment by ritox842** [comment]
I've found out that it's happening when the client resizes the window rapidly, causing the charts to reflow.
Uploading Screen Recording 2021-01-17 at 18.48.25.mov…
![image (1)](https://user-images.githubusercontent.com/7280441/104849922-148dc800-58f5-11eb-8421-c187b361429b.png)


I wasn't able to reproduce it in jsfiddle, but in our env, it happens all the time. I've noticed that if we comment out our label value formatter it works fine but nothing there should cause the script to crash.

![image](https://user-images.githubusercontent.com/7280441/104846212-0a160300-58e2-11eb-827a-956ab645b9c1.png)

**Comment by KacperMadej** [comment]
Please share a minimal chart configuration that you are using to recreate the problem. If you could create a stand-alone HTML file, a link to a project, or a website that would allow us to check the problem then we could investigate the case.

Minified code is not the best for debugging. We are providing mapping for the minified files, so the debugger will point to the code with named variables. We also provide .src.js extensions for all .js files on the official CDN (code.highcharts.com) to make debugging even better.

**Comment by ritox842** [comment]
We found out that the callback method we supplied as the label formatter wasn't stable and when in crashed it caused the highchart error to appear.
Anyway I think that its a good idea to verify that there's a label object before accessing it.

I'm closing this issue since it's not an highchart bug.
