### ISSUE TITLE
High Charts export Data Table filtering data by range selector

### ISSUE THREAD

**Issue by Waqar06** [highcharts/highcharts#14959]
When you click on it shows a data table below the chart. The problem I am facing is that if I select a particular value from the Range selector the view data table still shows a complete dataset. The range selector has no effect on it. How can I only display data that is given upon selecting a particular range selector value?

For example, if I have selected data for the last minutes and the chart is showing data for the 10 mins the data table should also show data for the last 10 mins, It should not display the entire dataset.

**Comment by PaulDalek** [comment]
Hi @Waqar06 

Thank you for contacting us and suggesting the enhancement. I’ve prepared an example where I modified the `viewData` and `getDataRows` functions, that allows to display only the visible points. Bear in mind, though, that this is only a workaround which isn't fully tested.

**Demo**
https://jsfiddle.net/BlackLabel/or9ceyw8/

**Comment by Waqar06** [comment]
@PaulDalek  Thanks. I also made a custom solution for myself. But I had to make changes in the export-data.js files. However If I want to use your solution how can I use it? Do I need to add the fiddle code in my solution or you can add changes to export.js library?

**Comment by Waqar06** [comment]
@PaulDalek  Your solution works, I tested it. Another enhancement could be that the data table updates when ever the range selectors changes.

**Comment by PaulDalek** [comment]
@Waqar06

As for your first question, the answer is by overwriting the specific function (take a look at my example). When it comes to updating data in the table dynamically you can simply call the `getTable` function in the `afterSetExtremes` events and it will replace data on the fly. Take a look at the updated demo below.

**Demo**
https://jsfiddle.net/BlackLabel/n49jf1qp/

**Comment by Waqar06** [comment]
It worked
