### ISSUE TITLE
Gradient is not applied on line when all points have the same values

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#14955]
#### Expected behaviour
Line should be visible

#### Actual behaviour
The line is gone when all points have equal y values.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/0kqy1h32

#### Product version
Highcharts 8.2.2

#### Affected browser(s)
All

**Comment by PaulDalek** [comment]
Closing as a duplicate of the #1677.
