### ISSUE TITLE
Gantt- after adding a point to a collapsed task, chart renders incorrectly

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14958]
#### Expected behaviour
Add point under the collapsed task as you can do this now with the not collapsed task.

#### Actual behaviour
After adding point when the task is collapsed, the chart is rendered incorrectly.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/sbx2oym6/

#### Product version
Highcharts Gantt JS v8.2.2 (2020-10-22)

#### Affected browser(s)
all

**Comment by sebastianbochan** [comment]
_Internal note:_
Can be related (partially) with https://github.com/highcharts/highcharts/issues/11350
