### ISSUE TITLE
Optimize SVG code

### ISSUE THREAD

**Issue by rafalbromirski** [highcharts/highcharts#14968]
# Description of the feature

**Important note**: this feature focuses on line charts, didn't checked other types but it might apply as well.

While working with big datasets and standard setup (no boost mode), I've noticed that HC component generates SVG which is quite big (especially if you compare it to other players like Plotly). My standard chart can weight up to 800KB (SVG size) but it only renders 2 lines (5000 data points each) - example attached at the bottom.

Not sure if it's something that can be optimized / controlled by user but it seems like 2nd path contributes a lot to the final size (especially if it's a complex path) but it's invisible(?).

```svg
 <g class="highcharts-series highcharts-series-1 highcharts-line-series" data-z-index="0.1" opacity="1" transform="translate(51,20) scale(1 1)" clip-path="url(#highcharts-sedxcja-8239-)">
  <path
    fill="none"
    d="..."
    class="highcharts-graph"
    data-z-index="1"
    stroke="rgba(0,0,0,0.5)"
    stroke-width="1"
    stroke-linejoin="round"
    stroke-linecap="round"
  ></path>
  <path
    fill="none"
    d="..."
    visibility="visible"
    data-z-index="2"
    class="highcharts-tracker-line"
    stroke-linecap="round"
    stroke-linejoin="round"
    stroke="rgba(192,192,192,0.0001)"
    stroke-width="21"
  ></path>
</g>
```

Now if you take more than 2 traces like that, your size will increase even more.

Interesting enough when I inspect my chart and remove these two paths, it's still working well: there is full interaction, tooltips are there and markers are visible.

# Library related to the feature

Highstocks

# Example:

Before: 789KB
After deletion: 490KB (37% less)

[hc.zip](https://github.com/highcharts/highcharts/files/5849508/hc.zip)

**Comment by PaulDalek** [comment]
Hi @rafalbromirski 
 
Thank you for contacting us and suggesting the enhancement. The boost module is specially designed for the increasing performance purpose in case of a big number of points/series (more information on [boost module](https://www.highcharts.com/docs/advanced-chart-features/boost-module)). As for the second path with the class name `highcharts-tracker-line`, in a nutshell is a necessary element for all sorts of mouse events.

**Comment by rafalbromirski** [comment]
@PaulDalek Could the 2nd path `highcharts-graph` be combined with `highcharts-graph` to save some KB?

I'm familiar with boost mode but it has other caveats which SVG actually solved pretty well - these extra KBs here and there are actually causing mobile browsers to freeze because html/svg markup is too much for some of them.

**Comment by PaulDalek** [comment]
@rafalbromirski 

Are the SVGs that you provided simply copied from a page or did you export the chart some other way than through the exporting module? When downloading a SVG by using the module, the [`enableMouseTracking`](https://api.highcharts.com/highcharts/series.line.enableMouseTracking) of each series is set to `false` to prevent from creating `highcharts-tracker-line` elements in a chart’s copy. You can do the same in the live version, to increase the performance but it will get rid of the tracking area completely.

**Comment by rafalbromirski** [comment]
I copied it from my page.

> You can do the same in the live version, to increase the performance but it will get rid of the tracking area completely.

Will check it out but probably interaction has to stay.

Thanks anyway
