### ISSUE TITLE
spline chart creating additional straight horizontal bar

### ISSUE THREAD

**Issue by albsaad** [highcharts/highcharts#14963]
#### Expected behaviour
It should display a single bar against each series 
![Expected Result](https://user-images.githubusercontent.com/77774614/105320865-88c3b680-5be8-11eb-8ad2-1b2f9a186063.png)

#### Actual behaviour
Sometimes it adds additional straight bar with expected or actual bar.
![Behavior](https://user-images.githubusercontent.com/77774614/105320937-9f6a0d80-5be8-11eb-98ca-a0bc9a8be23b.png)

Here is my JS Code:
```
var chart = Highcharts.chart('container', {
  chart: {
    type: 'spline'
  },
  title: {
    text: 'Total Pool Overview'
  },
  subtitle: {
    text: 'Total work force capacity in contract hours per Week'
  },
  xAxis: {
    type: 'datetime',
    dateTimeLabelFormats: { // don't display the dummy year
      month: '%e. %b',
      year: '%b'
    },
    title: {
      text: 'Date'
    }
  },
  yAxis: {
    title: {
      text: 'Hours'
    },
    min: 0
  },
  tooltip: {
    headerFormat: '<b>{series.name}</b><br>',
    pointFormat: '{point.x:%e. %b}: {point.y:.2f}'
  },
  legend: {
    layout: 'vertical',
    align: 'right',
    verticalAlign: 'middle'
  },
  plotOptions: {
    series: {
      marker: {
        enabled: true
      },
      pointInterval: 7 * 24 * 3600 * 1000,
      point: {
        events: {
          mouseOver: function() {
            console.log(this);
            var index = this.index;
            UpdateHeaderValuesWeeklyBased(index);
          },
          mouseOut: function() {
            console.log(this);
            var index = this.index;
            ResetHeaderValues();
          }
        }
      }
    }
  },
  series: [{
    name: 'Total Maximum Hours',
    data: maxArray,
    color: '#0000ff'
  }, {
    name: 'Total Minimum Hours',
    data: minArray,
    color: '#00ff00'
  }, {
    name: 'Capacity',
    data: CapacityArray,
    color: '#ff0000'
  }],
  responsive: {
    rules: [{
      condition: {
        maxWidth: 500
      },
      chartOptions: {
        plotOptions: {
          series: {
            marker: {
              radius: 2.5
            }
          }
        }
      }
    }]
  }
});
```

**Comment by PaulDalek** [comment]
Hi @albsaad

Thank you for contacting us and reporting this issue. This behavior occurs because your data isn’t sorted (see error [#15](https://www.highcharts.com/errors/15/)). Check your data and sort it in an ascending order to make the series display correctly.

**Comment by albsaad** [comment]
i have checked my data its sorted and chart is creating this additional line on the same data on which it renders correctly.

**Comment by albsaad** [comment]
means sometimes it adds this additional line, it has no certain scenario  on which it occurs.

**Comment by KacperMadej** [comment]
Please recreate the problem in a live demo or share the chart configuration with exemplary data set that should be used to recreate the problem, so we could debug the problem and suggest some solutions.

**Comment by albsaad** [comment]
I don't know the exact scenario so its difficult to replicate this issue, it happens randomly, can you please tell me what possible reasons can cause this behavior so i can look into it.

**Comment by PaulDalek** [comment]
@albsaad

As I mentioned before, the first and most common reason is not sorted data. Please, just to be sure, check your console if error [#15](https://www.highcharts.com/errors/15/) occurs. If it doesn’t, just as Kacper mentioned in the comment above, try to recreate this scenario in a simplified live demo. Otherwise it might be hard to detect the cause of this behavior.

**Comment by albsaad** [comment]
Thanks guys i was able to replicate the issue by giving unsorted data, hopefully i will resolve it now.
