### ISSUE TITLE
Heatmap touch zoom overflow his area

### ISSUE THREAD

**Issue by telran** [highcharts/highcharts#14970]
#### Expected behaviour
If I enlarge the chart in the y-axis, it is shown outside of the graph area. The problem only occurs with touch devices with zoom gesture.

![first](https://user-images.githubusercontent.com/4060508/105369123-866e5600-5c02-11eb-953c-d5b5ea8f6af1.jpeg)
![last](https://user-images.githubusercontent.com/4060508/105369127-88d0b000-5c02-11eb-97b4-a8a74d1dc0b1.jpeg)

#### Actual behaviour
The chart should not overlap the title like the legend.

#### Live demo with steps to reproduce
Not from me but with the same issue
https://jsfiddle.net/NayanaDas/08evyf33/

#### Product version
8.2.2

#### Affected browser(s)
All browsers with touch input

**Comment by PaulDalek** [comment]
Hi @telran

Thank you for contacting us and reporting this issue. The `heatmap` series is not clipped correctly when zoom is performed. It looks like a regression. The latest working version is v8.0.4.

**Simplified demo**
https://jsfiddle.net/BlackLabel/k6gua7xb/
