### ISSUE TITLE
Categories - minorTicks not displayed.

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1497]
In case when categories are used, then minor ticks are not displayed.

http://jsfiddle.net/KtbYU/

**Comment by MichaelSundhed** [comment]
"Minor ticks don't exist on a category axis..." - not true and i'm missing this function as well.
In my case this is for audiograms which doctors and patients need to interpolate values for their hearing session.
I.e how much hearing loss do i have (dB vs. %).
![image](https://user-images.githubusercontent.com/116732119/198034178-d1a37e48-fb49-4172-b1ed-bca3e88b0ad7.png)

**Comment by karolkolodziej** [comment]
@MichaelSundhed in your case the `yAxis` categories can be easily replaced by numbers- [demo](https://jsfiddle.net/BlackLabel/rzgyjobm/).

Then you are able to add those minor ticks between as I did in the demo.

**Comment by MichaelSundhed** [comment]
@karolkolodziej the yAxis was not the problem, it is minorTicks on the xAxis with a category. See the second chart.

**Comment by MichaelSundhed** [comment]
@karolkolodziej this was exactly what i needed, thank you.
