### ISSUE TITLE
lastPrice.color of series attribute does not work

### ISSUE THREAD

**Issue by JustinPhung** [highcharts/highcharts#14972]
#### Expected behaviour
The crosshair line for the current price index to be red. And the attribute series -> lastPrice.color to function.

#### Actual behaviour
The crosshair has no color

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/Ld6cb4uk/
click on Current Price Indicator button

#### Product version

Highstock v8.2.2

#### Affected browser(s)
Chrome v87
Firefox v84

**Comment by PaulDalek** [comment]
Hi @JustinPhung

Thank you for contacting us and reporting this issue. The reason for this behavior is the default CSS styles for a `highcharts-crosshair` element that are loaded in the demo. As a workaround you can set the `className` in the `lastPrice` section and set the color through a CSS class.

**Workaround**
https://jsfiddle.net/BlackLabel/ptdr6wam/

_Internal note_
The `stroke` attribute of the last price path should use the `color` value from the options unless the styled mode is enabled.

**Comment by khlieng** [comment]
I think the solution here is to not include `highcharts.css` if you are not using styled mode, the `stroke` attribute does get set but CSS classes take precedence over SVG attributes: https://www.w3.org/TR/SVG/styling.html#PresentationAttributes

**Comment by JustinPhung** [comment]
Thank you @PaulDalek and @khlieng,

in our project styled mode is essential therefor the classname attribute seems to be a good workaround!

**Comment by JustinPhung** [comment]
@khlieng, @PaulDalek: I am sorry for bad news.
The workaround does not seem to work for multiple lines: http://jsfiddle.net/6anty32b/1/

**Comment by PaulDalek** [comment]
@JustinPhung

From what I have checked, the class is applied for all of the last price indicator lines. Increase the `stroke-width` to see it (http://jsfiddle.net/BlackLabel/k6ys7ha1/). You can of course set the different `className` for each line too (http://jsfiddle.net/BlackLabel/Lwgv30fx/). Also, you can increase the `zIndex` to display the lines above the `lastVisiblePrice` paths. 

Yes, @khlieng you are right. The CSS classes take precedence but I was thinking rather to make the last price indicator line to behave in a similar way as series (color can be set through options) when CSS are loaded but the `styledMode` is disabled. I modified the `afterRender` event from the `price-indicator` module to use `lastPrice.color`, `series.color` and the default color (in that order) as a color for the line.

**Demo**
https://jsfiddle.net/BlackLabel/jskygrv4/

**Comment by JustinPhung** [comment]
Hi @PaulDalek,
Thank you for the second demo. I suppose you were right. With the new z-index the color is visible.
Thanks for your help!
