### ISSUE TITLE
Column chart bug: switching to / from stacked with centerInCategory: true

### ISSUE THREAD

**Issue by nulle** [highcharts/highcharts#14980]
#### Expected behaviour
Toggling stacked option on series should switch series between two states

#### Actual behaviour
Toggling stacked option the second time makes stacks overlap

#### Live demo with steps to reproduce
https://jsfiddle.net/nulle/x7pLeatr/
1. Loaded state is a stacked chart with **two stacks** (two series in each stack), and **centerInCategory: true** (let's call this state1).
2. Click "Toggle Stacked" button once, and stacked option is removed, chart now has 4 columns in each category (state2). 
3. Click "Toggle Stacked" button once more. Expected: state1 (same as on initial load). Actual result: stacked bars are not next to eachother, but overlapping (clearly visible when tooltipping).

Note that with either "centerInCategory" turned off, or just one stack, everything works as expected.
Possibly connected to https://github.com/highcharts/highcharts/issues/14921 ? Though, just one y axis here.

#### Product version
Highcharts 8.2.2

#### Affected browser(s)
Probably all (using Chrome 87.0.4280.141 on MacOS)

**Comment by KacperMadej** [comment]
Hi @nulle 

Thank you for reporting the problem.
