### ISSUE TITLE
Gantt: Last y axis label not visible when having 2 series 

### ISSUE THREAD

**Issue by SMH110** [highcharts/highcharts#14982]
Hi,
#### Expected behaviour
To see y-axis labels correctly positioned and visible when using more than one series 

#### Actual behaviour
The last label in the y-axis is not visible and first label is incorrectly positioned 

#### Live demo with steps to reproduce
[Live Demo](https://jsfiddle.net/Sayed110/vqahmtx9/11/)
![image](https://user-images.githubusercontent.com/16171515/105625364-a9765100-5e20-11eb-96f3-4de140f16cf9.png)

#### Product version
Latest version of Highcharts Gantt

#### Affected browser(s)
All browsers

**Comment by KacperMadej** [comment]
Hi @SMH110 

Thank you for reporting the problem.

As a workaround, you could add empty points to fill the data and chart space: https://jsfiddle.net/BlackLabel/9tzofLqm/
