### ISSUE TITLE
Restrict High Chart to show original value rather than average for range selector

### ISSUE THREAD

**Issue by Waqar06** [highcharts/highcharts#14985]
High chart should allow another approximation type where we can get the original value from data displayed inline charts rather then displaying an average as default when DataGrouping is forcefully applied for long ranges. 

It should just display the first value of every Data group array with its original X and Y value.  

for example: For this one date '1 Dec 2020' It shows different values.

Range selector All: 26.28

Range selector 5 years: 26.28

Range selector 6 months: 26.4

IT should just display the original value 26.4  rather than averaging. 

Some say 'approximation: close' but it's not entirely accurate. 
Some kind of data needs a very accurate description of data such as stock rates over the last 5 years.

**Comment by KacperMadej** [comment]
Hi @Waqar06 

The feature that you have described is available through a named function (e.g. "average", "sum", etc.) or a custom algorithm (function) in the approximation option of dataGrouping. More info in the API reference: 
https://api.highcharts.com/highstock/series.line.dataGrouping.approximation

Another option could be to disable dataGrouping client-side and group data on a server as described here: https://www.highcharts.com/docs/working-with-data/server-side-data-grouping

If this feature request is about something different then please elaborate.

**Comment by Waqar06** [comment]
The feature you described above only gives average, sum, high, close option or some data it can work however if you need an option for data that should be accurate such as stock prices.  It is better to display the actual price of the stock on that day rather than showing an average of 10 days. I think if there is an option that instead of showing an average of 10 days can show the actual price of 1 single day from that group will be more accurate and desirable.  

About your point 1, I tried manipulating the data in approximation, I was trying to get one starting value from each data group to show in the chart. For example, there are 20 data groups. I tried taking points from each group to display on the map however I was not successful because data groups are not accessible. 

About point 2, I disabled data grouping for my data. My data is perfectly fine till I select 1 year of data in my range selector however when I choose 5 yr and more I noticed the API explicitly makes data groups in order to show data. 

So for that cases, my data is showing an average which I do not want.

**Comment by KacperMadej** [comment]
It might be easier if you could share your chart configuration in a live demo because for me everything works fine.
https://jsfiddle.net/BlackLabel/rtn7bup2/
In the above demo, the chart's width and data grouping are forced so you should be able to get a tooltip on hover with info telling that the average value is `(x-1) + 0.5` for the approximation average and `x` for the custom approximation.

The demo doesn't work correctly but this should be resolved as a bug in another issue that I have opened here: https://github.com/highcharts/highcharts/issues/14995

fyi: @pawelfus

**Comment by pawelfus** [comment]
Hi @Waqar06 

Did you resolve the issue with the demo that Kacper created for you? In this demo: https://jsfiddle.net/BlackLabel/rtn7bup2/1/ you can see how to retrieve the very first point for each group, instead of average, sum etc. approximations

**Comment by Waqar06** [comment]
@pawelfus  Yes. Thank you

**Comment by pawelfus** [comment]
Thank you @Waqar06
