### ISSUE TITLE
Drilldowns renders incomplete columns with drillup events

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#14984]
#### Expected behaviour
Drilldowns should work fine even when `chart.events.drilldown` is set.

#### Actual behaviour
Drilldown renders incomplete columns. Please see the following gif - 

![](https://s2.gifyu.com/images/chart-drilldown-issue.gif)

#### Live demo with steps to reproduce
I am somehow not able to reproduce the issue in a fiddle but here is a fiddle containing the config I am using. Note that when I comment out the xAxis title update in drillup events, things work just fine.

https://jsfiddle.net/vf0xnpje/

#### Product version
Highcharts JS v8.2.2

#### Affected browser(s)
Chrome

**Comment by khlieng** [comment]
It should be `this.xAxis[0].setTitle({ text: "asd" })`, could you check if that helps with the rendering?

**Comment by govinda18** [comment]
Sorry it was my mistake while typing actually. But that was correct in my code.

**Comment by KacperMadej** [comment]
Hi @govinda18 

Thank you for reporting the problem.

Please recreate the problem in a live demo or share the chart configuration with exemplary data set that should be used to recreate the problem, so we could debug the problem and suggest some solutions.

Please check errors in the browser console (when you are able to see the issue).

**Comment by govinda18** [comment]
Hi @KacperMadej, It seems to me that the bug was fixed in 8.2.2 and we were using 8.1.2. 
[v8.2.2](https://jsfiddle.net/1bd8enqp/)
[v8.1.2](https://jsfiddle.net/1bd8enqp/)

Thanks for your response. Closing the issue.
