### ISSUE TITLE
IE10 - polar chart

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1499]
Polar chart is not displayed correctly, data is not show, but when you hover over chart, then series appear.

Example: http://jsfiddle.net/R8z3Q/show/

IE10 - 10.0.9200.16466 
Windows 8

**Comment by fatinabila** [comment]
What's the solution for this issue?

**Comment by sebastianbochan** [comment]
Hi @fatinabila,
The issue is already fixed in the Highcharts. Please let me know if problem still appears in the newst highcharts.
