### ISSUE TITLE
Stock: data grouping approximation demo

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#14995]
#### Behaviour
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/series-datagrouping-approximation

The console logs are bad - the `start` variable is wrongly calculated and the data comes up empty like
`(index):77 dataGroupInfo: Object Raw data: Array(0)`.

The demo is linked in the API reference here: https://api.highcharts.com/highstock/series.line.dataGrouping.approximation

**Comment by pawelfus** [comment]
That's correct. Since v7.1.2 we don't need to use `this.cropStart` as it's included in `dataGrpupInfo.start` value.

Related commit: 2d0d702c6493aad166ced3d6bb3df07771fa5c54
