### ISSUE TITLE
Problem with linked axes and multiple (non-linked) axes

### ISSUE THREAD

**Issue by slawekkolodziej** [highcharts/highcharts#150]
Disabling a chart title causes that extra lines are shown on the linked axis. 
Here is an example: http://jsfiddle.net/8Nr46/22/
Chart'll look correct if you remove this:
title: {
  text: ''
},

thread on highcharts forum, with more examples: http://highslide.com/forum/viewtopic.php?f=9&t=8594

**Comment by pawelfus** [comment]
Still valid in 4.1.8: http://jsfiddle.net/wx6Rk/1/

**Comment by cosycode** [comment]
I failed to reproduce the problem, tested on Chrome 62, Chrome 63, Firefox 57, Internet Explorer 8, Internet Explorer 11, Safari 11, and Safari Mobile 10.

**Comment by KacperMadej** [comment]
I would love to close this old issue, but unfortunately I am able to recreate the problem.
Chrome 63 / Win10.
![chart 23](https://user-images.githubusercontent.com/8960408/34102572-efed14d4-e3e9-11e7-9e87-81772ff9e095.png)
First horizontal line is visibly thicker.

**Comment by cosycode** [comment]
Thank! I could reproduce the issue. It is linked to the width of the chart and gets thicker. I will look into it.

**Comment by KacperMadej** [comment]
Unable to recreate using version 6.1.4
Closing as resolved
