### ISSUE TITLE
HighStock selection event callback is not firing

### ISSUE THREAD

**Issue by Rsl1122** [highcharts/highcharts#15002]
#### Expected behaviour

- Selection event callback is called when range filter is changed

#### Actual behaviour

- Selection event callback is not called

#### Live demo with steps to reproduce

Demo found from https://api.highcharts.com/highstock/chart.events.selection:
- https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/chart/events-selection/

1. Change range filter
2. Observe how innerHtml of report element does not change

#### Product version

Using https://code.highcharts.com/stock/highstock.js 
> Highstock JS v8.2.2 (2020-10-22)

Also present in v7.1.2 (2019-06-03)

#### Affected browser(s)

- Firefox 85.0 64bit
- Google Chrome 88.0.4324.104 64bit

**Comment by PaulDalek** [comment]
Hi @Rsl1122

Thank you for contacting us and reporting this. The `selection` event works as intended. What you are looking for is the [`afterSetExtremes`](https://api.highcharts.com/highcharts/xAxis.events.afterSetExtremes) event.

**Demo**
https://jsfiddle.net/BlackLabel/79xhr2w0/
