### ISSUE TITLE
Highstock chart point get wrong dataGroup start index when dataGrouping's options groupAll is true

### ISSUE THREAD

**Issue by wy1713** [highcharts/highcharts#15005]
#### expected behavior
get correct point.dataGroup.start index no matter zoom range is used or not

#### Actual behaviour
get wrong point.dataGroup.start when zoom range is selected. 

this problem only happens when dataGrouping setting groupAll: true, if groupAll:false, both scenario get corrected index.

#### Live demo with steps to reproduce
https://jsfiddle.net/98t1v4cp/3/

#### Product version
lastest

#### Affected browser(s)
![bug](https://user-images.githubusercontent.com/36648934/106055739-a8eced00-60a2-11eb-8214-359565db3e65.gif)

**Comment by KacperMadej** [comment]
Hi @wy1713 

Thank you for reporting the problem.

**Comment by wy1713** [comment]
Hi,

I reported this issue and glad to see it is resolved today. however when I try to use it, it is still not working. see my examples and screenshot. the index for that point before zoom is 17, and after zoom it is suppose to be 17 too. 


![chart](https://user-images.githubusercontent.com/36648934/110049334-80da5480-7d06-11eb-84d4-cbbcd75fa92f.gif)
fiddle: https://jsfiddle.net/npse8r5g/
