### ISSUE TITLE
series.venn.data.className not adding to circle's class attribute since version 8.2

### ISSUE THREAD

**Issue by oliviathorne1** [highcharts/highcharts#15009]
#### Expected behaviour
Previously, specifying the series.venn.data.className property value set the class of the circle element within the Venn SVG. (See JSFiddle of previous behaviour in 8.1: https://jsfiddle.net/079dbo4m/16/)

#### Actual behaviour
Now, the series.venn.data.className property is ignored, and no class attribute is added to the circle elements, meaning styling is not added. (JSFiddle of current behaviour in 8.2: https://jsfiddle.net/cfr0hed4/4/)

#### Live demo with steps to reproduce
Previous: https://jsfiddle.net/079dbo4m/16/
Current: https://jsfiddle.net/cfr0hed4/4/

Steps to reproduce:
1. Create a Venn diagram using highcharts
2. Add series.venn.data with sets and values properties set to render the chart
3. Add the series.venn.data.className property and add a corresponding class to the .css
4. Notice that the class is not pulled through on the element

#### Product version
Highcharts 8.2+

#### Affected browser(s)
This was reproduced on Chrome

**Comment by KacperMadej** [comment]
Hi @oliviathorne1 

Thank you for reporting the problem.

You could preview the fix in this demo: https://jsfiddle.net/BlackLabel/3pzy1xbj/
