### ISSUE TITLE
Keyboard navigation in legend items doesn't react to space key

### ISSUE THREAD

**Issue by vks-financial-com** [highcharts/highcharts#15014]
#### Expected behaviour
Pressing the `space` key should toggle focused series item in legend.

#### Actual behaviour
Pressing `space` key on the focused legend items doesn't do anything.

#### Live demo with steps to reproduce
jsfiddle seems to capture keyboard events, which doesn't allow to navigate in preview frame

#### Product version
Highcharts v8.2.2, using highstock module

#### Affected browser(s)
Current Chrome/Firefox

Any workaround would be greatly appreciated.

**Comment by khlieng** [comment]
Do have the accessibility module loaded? Here's a demo where space toggling works: https://www.highcharts.com/samples/highcharts/accessibility/accessible-line

**Comment by vks-financial-com** [comment]
> Do you have the accessibility module loaded? Here's a demo where space toggling works: https://www.highcharts.com/samples/highcharts/accessibility/accessible-line

Thanks for the hint! Yes, the accessibility modules is loaded. Our chart has the `.highcharts-a11y-proxy-container` element as well, but unlike in the example, the buttons inside of the container are not positioned on the labels, having zeroed positions and dimensions. Must be some configuration conflict..

**Comment by khlieng** [comment]
A jsfiddle would be helpful, tab navigation seems to work fine after clicking outside the chart in the preview tab.

**Comment by vks-financial-com** [comment]
> A jsfiddle would be helpful, tab navigation seems to work fine after clicking outside the chart in the preview tab.

Thanks for willingness to help. I'm closing the issue, as it seems to be some multitude of factors causing the problem due to complexity of our application.
