### ISSUE TITLE
tooltip's useHTML, split and outside don't get along

### ISSUE THREAD

**Issue by itayganor** [highcharts/highcharts#15018]
#### Expected behaviour
When using:
```js
tooltip: {
    useHTML: true,
    outside: true,
    split: true,
}
```

We'd expect the content of the tooltip to be shown above the tooltip's background.

#### Actual behaviour

The tooltip's content is drawn behind the tooltip's background.

#### Live demo with steps to reproduce

1. Take this JSFiddle from [docs](https://api.highcharts.com/highcharts/tooltip.outside):
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/outside

Tooltips are fine.

![image](https://user-images.githubusercontent.com/6430313/106399023-f066d680-641e-11eb-85c8-6e447082d2cd.png)

2. Now, add `useHTML: true` and `split: true` to `tooltip`.

Now it looks like this:

![image](https://user-images.githubusercontent.com/6430313/106399043-0e343b80-641f-11eb-982e-09bf74582752.png)

#### Product version
Highcharts v8.2.2

#### Affected browser(s)
Tried on Chrome 88

**Comment by KacperMadej** [comment]
Hi @itayganor 

Thank you for reporting the problem.

_Internal note:_
Minimal demo: https://jsfiddle.net/BlackLabel/gx06qwve/
