### ISSUE TITLE
Panning after zoom is limited to the first series range.

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#15022]
#### Expected behaviour
Pan regardless of the series number and its' range.

#### Actual behaviour
After zooming in the chart with multiple series, chart extremes can be changed by panning only in a range of the first series.

#### Live demo with steps to reproduce
1. Zoom in
2. Try to pan (change the series index and repeat).

Demo 1: https://jsfiddle.net/BlackLabel/4bv7f1cp/
Demo 2: https://jsfiddle.net/BlackLabel/ct7en1fo/

#### Product version
Highcharts JS v8.2.2 (2020-10-22)

#### Affected browser(s)
All

**Comment by PaulDalek** [comment]
_Internal note_
The `startMin` and `startMax` are found based on extremes from the first series (only when the `panningState` is `undefined`) in the `pan` function. Related to #14426.
