### ISSUE TITLE
Tooltip is a shadow with this set (split+outside+useHTML) 

### ISSUE THREAD

**Issue by hihajdus** [highcharts/highcharts#15036]
#### Expected behaviour
The tooltip should be visible.

#### Actual behaviour
Tooltip is shadow with this set:
`  tooltip: {
    outside: true,
    useHTML: true,
    split: true
  },`

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/L2cxfnz4/](https://jsfiddle.net/BlackLabel/L2cxfnz4/)
#### Product version
Highcharts JS v9.0.0 (2021-02-02)
#### Affected browser(s)
All

**Comment by khlieng** [comment]
Duplicate of #15018.
