### ISSUE TITLE
Wrong typing for `RangeSelectorOptions.enabled` in 9.0.0

### ISSUE THREAD

**Issue by jnizet** [highcharts/highcharts#15034]
#### Expected behaviour

The type of `RangeSelectorOptions.enabled` should be `boolean` (as it was before version 9), or it should be documented.

#### Actual behaviour

Since V9, the type is `string`, and the documentation doesn't say what the accepted values are.
The example about this option (https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/rangeselector/enabled/) still shows `false`, a boolean, not a string as value.

#### Product version

9.0.0

#### Affected browser(s)
NA

**Comment by KacperMadej** [comment]
Hi @jnizet 

Thank you for reporting the problem.

The option type should be `boolean` - this is a documentation error.

**Comment by jnizet** [comment]
Just to be sure my issue is well understood: the issue is not just about the documentation. It's about the TypeScript typings. Due to this change, code that compiled doesn't compile anymore, and a dirty hack (`enabled: (false as unknown) as string`) must be used to make the code compile again.

**Comment by KacperMadej** [comment]
Added the TS label 👍 

The code's comments (in this case [this one](https://github.com/highcharts/highcharts/blob/ea08706707/js/Extensions/RangeSelector.js#L233-#L241)) are used for both the API reference documentation and the public TS definitions (.d.ts) - fixing one will resolve both.
