### ISSUE TITLE
Organization chart module does not work

### ISSUE THREAD

**Issue by che607** [highcharts/highcharts#15033]
#### Expected behaviour
Organization Functionality working

#### Actual behaviour
Organization module does not work
live demo: https://www.highcharts.com/docs/chart-and-series-types/organization-chart

**Comment by KacperMadej** [comment]
Hi @che607 

The demo works fine for me.

Make sure to clear your browser cache as a new version (9.0.0) of Highcharts was released today and your browser might be loading some files from cache creating a version mismatch between core and modules.

**Comment by che607** [comment]
You are right!  Thanks!
