### ISSUE TITLE
Missing strokes in Boxee browser

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#1503]
Demo: www.highcharts.com

In the Boxee browser, all strokes seem to be missing from the SVG shapes, only the fills are visible. When we copy the source code of www.highcharts.com into jsFiddle and start removing content, the strokes appear again. So the issue seems to be related to the complexity of the page.

**Comment by oysteinmoseng** [comment]
Boxee seems to have been dead since 2012, so closing this.
