### ISSUE TITLE
Highstock scrollbar after zooming, doesn't allow to scroll vertically, numbers on the y-axis are unformatted.

### ISSUE THREAD

**Issue by hihajdus** [highcharts/highcharts#15046]
#### Expected behaviour
The scrollbar after zooming allows you to pan vertically at all times.
The numbers on the y-axis are properly formatted.

#### Actual behaviour
After zooming, the scrollbar when scrolling horizontally doesn't allow you to scroll vertically.
The numbers on the y-axis are unformatted.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/1gkza8e9/](https://jsfiddle.net/BlackLabel/1gkza8e9/)

https://user-images.githubusercontent.com/22296099/106753673-43fa3f80-662c-11eb-9476-aba514912704.mp4

#### Product version
Highstock JS v9.0.0 (2021-02-02)

#### Affected browser(s)
All.

**Comment by KacperMadej** [comment]
**Workaround**: set `getExtremesFromAll: true` - https://jsfiddle.net/BlackLabel/1gkza8e9/1/
