### ISSUE TITLE
High contrast mode displaying all pie chart data point in the same color

### ISSUE THREAD

**Issue by duvesing** [highcharts/highcharts#15040]
#### Expected behaviour
It should be possible to set the colors in the pie chart so that each slice of the pie chart is displayed in different color when in high contrast mode. The different colors should also be visible in the legend, next to the buttons that filter the chart.

#### Actual behaviour
When in high contrast mode, the color of data points within the series in the pie chart seems to be overridden to always be "window". So all slices in the chart are displayed in the same color. The colors of the data points aren't visible in the legend at all.

I glanced at the source code and I believe the problem is in the following function: https://github.com/highcharts/highcharts/blob/bfb7411d76a8c3d06663f6663cc42e5f43ed3f73/js/Accessibility/HighContrastMode.js#L69
It seems to set colors for all the data points in the pie chart to the same value.

#### Live demo with steps to reproduce
https://jsfiddle.net/3rouscw4/ 
The issue is visible when I turn on the Windows high contrast mode and open the above jsfiddle in the browser. 
(The the jsfiddle is a copy of the official one with the accessibility module imported: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series/pattern-fill-pie)

#### Product version
Highcharts JS v9.0.0 (2021-02-02)

#### Affected browser(s)
Microsoft Edge Version 88.0.705.56

**Comment by KacperMadej** [comment]
Hi @duvesing 

Thank you for reporting the problem.

The theme for the high contrast could be set using [`accessibility.highContrastTheme`](https://api.highcharts.com/highcharts/accessibility.highContrastTheme).
Demo: https://jsfiddle.net/BlackLabel/a8cno3m5/1/

The default theme uses the same colors for legend items and the chart background - so they are not visible.
fyi: @oysteinmoseng (a11y)

**Comment by oysteinmoseng** [comment]
Hi @duvesing, this is by design. The high contrast mode is intended for users to limit the number of colors visible, in order to specify the colors that work best for them. This is typically done so that boundaries have a higher contrast, and can be clearly seen by people with low vision.

In a pie chart, the colors of the slices should not usually carry information, and as such the contrast between slices is what needs to be highlighted.

As mentioned by Kacper, it is possible to configure the high contrast theme differently if this is preferred in your particular use case.

I am closing this for now, please comment and we can reopen if needed.

**Comment by oysteinmoseng** [comment]
Reopening as the legend symbols should still be visible in High contrast mode.

**Comment by duvesing** [comment]
We use the pie chart without data labels, like in the example below:
https://jsfiddle.net/n1uxbzkq/2/

In this case, the colors of the slices carry information. In high contrast mode, it would be preferable to display different slices by filling them with different patterns (as is the case in normal mode in the example above). I apologize if that intention wasn't clear from my initial query.

However, patterns seem to be assigned using the color attribute in the code. I couldn't find a way to set different patterns for slices in high contrast mode.

**Comment by oysteinmoseng** [comment]
I see, thanks for clarifying. We should change the implementation to allow setting this in the theme configuration.

That being said, I think a more accessible solution for you would be to enable data labels in High contrast mode, if at all possible.

**Comment by KacperMadej** [comment]
@duvesing 
As a workaround, it is possible to use the chart's internal event `afterA11yUpdate` and update the chart with some more a11y-friendly options.
Demo: https://jsfiddle.net/BlackLabel/39c01f7t/3/

**Comment by PetarNikValchev** [comment]
Hi! I am trying to have a bar chart show me different colors for the different series in high contrast mode by using the `afterA11yUpdate` event (as suggested above). 

I am able to do it in this example - https://jsfiddle.net/kx8Ljzuy/. However, I am unable to use this event for the charts in our app. I can only use the events specified in the documentation - https://api.highcharts.com/highcharts/chart.events. I tried with versions 9.3.3 and 10.0.0. 

I can see that `afterA11yUpdate` is an "internal" event. Does this mean I have to do something additional to be able to use it?

@oysteinmoseng I can see that you introduced this event (https://github.com/highcharts/highcharts/pull/12134). Do you have any idea what might be the reason we are unable to use it? Maybe there is a setting/import/dependency that we are missing.

**Comment by raf18seb** [comment]
Hi @PetarNikValchev,

This might be obvious, but are you 100% sure you have the `modules/accessibility.js` module included in your app?
If you do and you are still not able to fire the event, could you somehow provide a demo of your app so we can take a look at it?

**Comment by oysteinmoseng** [comment]
@PetarNikValchev It seems the updates are negated by other code running after yours, so it can be solved by running a small timeout: https://jsfiddle.net/oysteinmoseng/6gbhxrqf/. I would call this a bug normally, but since we are hacking internal events here I suppose it is to be expected.
