### ISSUE TITLE
'adjustForMissingColumns' doesn't work for columnrange series type

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#15045]
#### Expected behaviour
The visible columns should ignore the missing ones and should be centered in their group when some columns are missing. 

#### Actual behaviour
The columns are positioned in a way, to leave the space for missing columns: 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/j6rhLex9/

#### Product version
v9.0.0

#### Affected browser(s)
all

**Comment by KacperMadej** [comment]
Since API reference says it's supported then it should work - https://api.highcharts.com/highcharts/series.columnrange.centerInCategory

Labeling as a bug.

fyi @raf18seb

**Comment by raf18seb** [comment]
In the end, the `centerInCategory` feature was not written by me.

I am not sure if this is related to this ticket, but something strange also moves the blue column to the left: https://jsfiddle.net/BlackLabel/yuxq3dhe/
