### ISSUE TITLE
Only one data serie with entire color and not all the series to fadeout

### ISSUE THREAD

**Issue by Wartaron** [highcharts/highcharts#15049]
#### Expected behaviour
When you go hover a data serie in a bar chart, you should able to set the other data points in a fade out and not the entire serie

Example:  If you hover the "Joe" series in the apples categories, the other "Joe" series in the categories (Oranges, pears, grapes and bananas) should fade out as well with the other series 

#### Actual behaviour
The entire serie is selected no matter if it is in another category

![image](https://user-images.githubusercontent.com/12474087/106772028-98da8d80-660d-11eb-86a7-7224a8a6a39f.png)

https://www.highcharts.com/demo/bar-stacked

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/bar-stacked

#### Product version
Highcharts/Highmaps version 8.2.2

#### Affected browser(s)
Chrome/Firefox

**Comment by KacperMadej** [comment]
Hi @Wartaron 

Thank you for reporting the problem.

This doesn't look like a bug - the code works like that by design.

To change this you could use a undocumented / unofficial / internal API option `inactiveOtherPoints` - https://jsfiddle.net/BlackLabel/sokj2wf6/

If you would like to have this option as a part of the official API you could open a feature request in a new issue.

**Comment by Wartaron** [comment]
Thanks for the response @KacperMadej 

I solved this trough a temporary solution using CSS with the classes `.highcharts-point .highcharts-series-hover .highcharts-point-hover` but have two problems.

To solved this has to guess the opacity value and for solved something with the opacity delay have to guess as well the transition value.

Can you please guide me to know how open a feature request? I'm new with this library.

For future references, here is the CSS code that I use if someone else need this solution.

```
*:not(.highcharts-series-hover)
  & > *.highcharts-point
    opacity: 1!important
    transition: opacity 1s ease-out!important

.highcharts-series-hover
  & > *:not(.highcharts-point-hover)
    opacity: 0.2
    transition: opacity 0.05s ease-out!important
```

**Comment by KacperMadej** [comment]
When opening a new issue you have 3 options and one of them is a feature request - https://github.com/highcharts/highcharts/issues/new/choose

Thank you for sharing your solution.
(It might be useful for others if you could add a live demo, e.g. in JSFiddle or CodePen.)
