### ISSUE TITLE
Call to update() with new errorbar data messes up chart UI

### ISSUE THREAD

**Issue by kakarlus** [highcharts/highcharts#15059]
#### Expected behaviour
Highcharts should update the newly added errorbar data without having to hide other chart data when method update is called

#### Actual behaviour
Highcharts UI hides some chartdata and errorbar color changes

#### Live demo with steps to reproduce
Added errorbar at series[3] after 5 seconds.
https://jsfiddle.net/39zLteb0/63/

#### Product version
v9.0.0

#### Affected browser(s)
tested in Chrome Version 88.0.4324.146 and Safari Version 13.1.3

**Comment by PaulDalek** [comment]
Hi @kakarlus 

Thank you for contacting us and reporting this. The behavior is expected as by default the option `oneToOne` in the [`update`](https://api.highcharts.com/class-reference/Highcharts.Chart#update) function is set to `false`. The 'Year 2016' `column` series is updated to `errorbar` therefore columns disappear and error bars display. To ensure that the `update` works as expected, you need to set `id` in each series to establish a correct order and set `linkedTo` in `errorbar` series to indicate where `errorbar` series should be displayed. In your case though, the better idea is to simply add errorbar series with the [`addSeries`](https://api.highcharts.com/class-reference/Highcharts.Chart#addSeries) function that contains a correctly set `linkedTo` property.

**Demos**
https://jsfiddle.net/BlackLabel/fxuetsb7/ - using `id` and `linkedTo` options
https://jsfiddle.net/BlackLabel/zkvrt1yb/ - adding a series

**Comment by kakarlus** [comment]
hello @PaulDalek,

am i right to assume that addSeries is performant compared to update?

regards,
Carlos

**Comment by PaulDalek** [comment]
@kakarlus

Yes, as in the first demo the `addSeries` function will be called internally (for the last `errorbar` series) along with all the updating code for the existing series. In case of the second demo, existing series are left intact.
