### ISSUE TITLE
Offline export to PNG/PDF not rendering properly with rangeSelector (BTC, ETH Unicode issue fixed!).

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [highcharts/highcharts#15062]
**Offline export to PNG/PDF not rendering properly with rangeSelector.**

Browser: Safari, Chrome

Font: Google's Noto Sans

<img width="1070" alt="Screenshot 2021-02-06 at 19 42 28" src="https://user-images.githubusercontent.com/24897721/107120449-be88c080-68b3-11eb-8d98-86eb83fe0051.png">

UPDATE: Mentioning a separate font for exporting doesn't seem to solve the issue.

```
exporting: {
    chartOptions: {
        chart: {
            style: { 
                fontFamily: 'Times New Roman', 
            }
        }
    }
},
```

UPDATE: Unicode characters like Bitcoin(₿), Ethereum(Ξ), Euro(€) are not rendering properly in offline export (only with _Download PDF document_).

<img width="1379" alt="Screenshot 2021-02-06 at 21 18 23" src="https://user-images.githubusercontent.com/24897721/107123383-41654780-68c3-11eb-9bbb-d5bf78b491f2.png">

UPDATE: Also facing an issue in Chrome where it's impossible to type the correct dates unlike in Safari where I'm able to type the whole date just like before. Suppose when I want to set 'November' as month, I cannot type two 1s to represent number 11. Although it is possible to set 'November' month by clicking on calendar datepicker as a workaround.

**Comment by KacperMadej** [comment]
Hi @roychowdhuryrohit-dev 

Thank you for reporting the problem.

Please add a live demo for the issue.
Please let us know the browsers' versions and the OS with the version that you are using to recreate the problem.

If you have multiple problems then please open a new ticket for each different problem.

**Comment by roychowdhuryrohit-dev** [comment]
![demo](https://user-images.githubusercontent.com/24897721/107153565-34fcef80-6994-11eb-8509-7004a0005774.gif)

OS: macOS 10.15.7
Browser: Safari 14.0.2/Chrome 88.0.4324.96
Font: Default font
Theme: Same problem with default theme.

**Comment by roychowdhuryrohit-dev** [comment]
Finally got it working.
I've loaded the Google Font called _NotoSans-Regular.ttf_ which seems to have support for **Bitcoin(Ƀ), Ethereum(Ξ), Euro(€)** and loading the **jspdf** and **svg2pdf** objects on window. The latest versions of jspdf and svgpdf are absolutely incompatible with Highcharts Offline Export. So I have imported the dependencies from the default libURL. This is the only temporary workaround now.
```
  loadHighchartsLib() {
    const script1 = document.createElement("script");
    script1.src = "https://code.highcharts.com/9.0.0/lib/jspdf.js";
    script1.async = true;
    script1.onload = () => {
      window.jsPDF.API.events.push(['addFonts', callAddFont]);
    };
    document.body.appendChild(script1);

    const script2 = document.createElement("script");
    script2.src = "https://code.highcharts.com/9.0.0/lib/svg2pdf.js";
    script2.async = true;
    document.body.appendChild(script2);
  }
```

**Comment by KacperMadej** [comment]
Thank you for the details and invetigating the problem.

> What font family does Highcharts Offline Export use to render PDF?

It should use the font set in the chart options - default or set chart options and exporting options.

I will mark that the issue has a workaround and keep the pending reply label as we still do not have a live demo for the problem.
