### ISSUE TITLE
Stock rangeSelector UI issue in Internet Explorer 11 IE11 in version 9

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#15060]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/23310742/107038372-b3069e00-67bc-11eb-963f-d26df9873824.png)

#### Actual behaviour
The new UI (v9) of rangeSelector doesn't fully work in IE11.
![image](https://user-images.githubusercontent.com/23310742/107038415-c580d780-67bc-11eb-80a8-555fc36a1d6f.png)

#### Live demo with steps to reproduce
Open in IE11
https://www.highcharts.com/demo/stock/basic-line

#### Product version
Highcharts Stock 9

#### Affected browser(s)
Internet Explorer 11

**Comment by khlieng** [comment]
This is probably because of the shorter width, Safari also has some problems but IE is trying to cram a clearing cross in there aswell.

**Comment by roychowdhuryrohit-dev** [comment]
Also facing an issue in Chrome where it's impossible to type the correct dates unlike in Safari where I'm able to type the whole date just like before. Suppose to set 'November' month, I cannot type two 1s to represent number 11.

**Comment by KacperMadej** [comment]
@roychowdhuryrohit-dev 
Please provide a live demo link and precise steps required to recreate the problem.

I have tried with [the basic demo](https://www.highcharts.com/demo/stock/basic-line). The "From" input works fine and "To" intpu (2nd, the one on the right side) has no data from that month in that year, so doesn't work either by input or datepicker - this is expected and correct. Tested on Chrome / Windows 10.

**Comment by khlieng** [comment]
@KacperMadej set the from input to 2019 first, then try to enter 1 in as the month. This is related to the data starting after January.

**Comment by roychowdhuryrohit-dev** [comment]
@KacperMadej The issue persists in your basic demo as well. 
First click “All” button -> Click on the month section of “From” -> Try typing 11 (6/11/2019).
