### ISSUE TITLE
Solid gauge demo looks bad 

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#15065]
#### Behaviour
![solid-gauge-bad-demo](https://user-images.githubusercontent.com/8960408/107153173-5c3fc680-696c-11eb-8b6c-55952fa0041f.jpg)

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/gauge-solid

Overlapping panes with wrong (too big) sizes.
JSFiddle demo looks fine - the problem is only on the Highcharts website.

Looks like the pane sizes are wrongly calculated because the height is 300 instead of 200 pixels.

Caused by

```css
.demo .chart-container {
    min-height: 300px;
}
```

in https://www.highcharts.com/demo/static/css.css

#### Product version
v9.0.0

**Comment by goransle** [comment]
Removed the offending rule, looks better now 👍
