### ISSUE TITLE
lastPrice color property is not applied properly

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#15074]
#### Expected behaviour
Always apply the color for the `lastPrice` line as declared in options.

#### Actual behaviour
After two clicks color changes.

#### Live demo with steps to reproduce
Click twice the `currentPriceIndicator` button.
http://jsfiddle.net/BlackLabel/n1wz7hbe/

#### Product version
Highstock JS v9.0.0 (2021-02-02)

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Thanks for catching this! The color is being overwritten here: https://github.com/highcharts/highcharts/blob/513c1d928ab0d8f038b1d9db62a8ab4f3be16c31/ts/Stock/StockToolsBindings.ts#L2092
```js
series.update({
    // line
    lastPrice: {
        enabled: !lastPrice,
        color: 'red'
```

Internal note: the current price indicator button is assigned to the first series rigidly. Nothing important, but we can keep it in mind and consider extending it in the future.

Internal note 2: the original issue came up from the named color `'red'` in tests. I've also found two other Stock Tools' drawing-tools that use this named color: `verticalArrow` and `pitchfork`.
