### ISSUE TITLE
Tooltip label for errorbar is on the wrong spot

### ISSUE THREAD

**Issue by kakarlus** [highcharts/highcharts#15077]
#### Expected behaviour
Tooltip must sit beside its target 'second-col'

#### Actual behaviour
Tooltip is sitting beside the last col 'fourth-col'

#### Live demo with steps to reproduce
https://jsfiddle.net/wg7yoj3L/17/

#### Product version
v9.0.0

#### Affected browser(s)
Chrome, Safari

**Comment by KacperMadej** [comment]
Hi @kakarlus 

Please add steps for how to recreate the problem and a demo with fixed-width so it would be stable.

A screenshot with marked good and bad positions of the tooltip would be nice.

**Comment by kakarlus** [comment]
![Screen Shot 2021-02-10 at 9 27 00 am](https://user-images.githubusercontent.com/809310/107436830-2ecc6600-6b82-11eb-81fa-866b6c574f3e.png)

The last errorbar tooltip at **Year 2016** is supposed to be for **Year 1800: 133**

**Comment by KacperMadej** [comment]
The order is the same as the series order in the chart options - change that series order and you will get a tooltip with different series items order. Demo: https://jsfiddle.net/BlackLabel/4pqeg39a/

Tooltip rendering and its text formatting is not connected to series being linked or dependant on each other but purely on the order. You could change it using tooltip formatter and create a custom format that will meet your requirements. Demo: https://jsfiddle.net/BlackLabel/4pqeg39a/1/
