### ISSUE TITLE
Some Stock Tools annotations (e.g. infinity line or pitchfork) aren't working with yAxis.top

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#15075]
The Pitchfork tool, Infinity Line, Vertical Line and similar aren't working properly when `yAxis.top` is defined.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/4toy0fa8/

#### Product version
Highcharts Stock 9.0.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
List of broken annotations:
- Arrow ray
- Line
- Arrow line
- Horizontal line
- Pitchfork
- Vertical counter
- Vertical label
- Vertical arrow

Demo: https://jsfiddle.net/BlackLabel/chfvLqw6/1/
