### ISSUE TITLE
Docs [Chart concepts]: Replace old images with new ones

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#15086]
List of articles with images to update:

- https://www.highcharts.com/docs/chart-concepts/understanding-highcharts
- https://www.highcharts.com/docs/chart-concepts/title-and-subtitle
- https://www.highcharts.com/docs/chart-concepts/axes
- https://www.highcharts.com/docs/chart-concepts/series
- https://www.highcharts.com/docs/chart-concepts/tooltip
- https://www.highcharts.com/docs/chart-concepts/legend
- https://www.highcharts.com/docs/chart-concepts/plot-bands-and-plot-lines

**Comment by mekhatria** [comment]
![Axes](https://user-images.githubusercontent.com/12743677/107791939-d5686080-6d54-11eb-89f4-d2a5882d4af0.png)
![Title and subtitle](https://user-images.githubusercontent.com/12743677/107791945-d7322400-6d54-11eb-89cc-9bcd5126eb35.png)
![Understanding Highcharts](https://user-images.githubusercontent.com/12743677/107791946-d7caba80-6d54-11eb-982d-03869daac15e.png)
