### ISSUE TITLE
Chart synchronization does not work when charts are besides each other

### ISSUE THREAD

**Issue by melloc01** [highcharts/highcharts#15097]
#### Expected behaviour
From the original example, I just put "flex" on the chartcontainer, and width:50% on charts.

#### Actual behaviour
Charts are out of sync
![image](https://user-images.githubusercontent.com/4994258/107498250-4d2a6580-6b72-11eb-9734-be91a94bfbb1.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/6xputa73/1/

Is there an official example on how to sync charts on a grid? This would be helpful

**Comment by PaulDalek** [comment]
Hi @melloc01 

Thank you for contacting us and reporting this.The `chartX` and `chartY` are calculated based on the event’s `pageX` and `pageY` so when hovering over the charts on the left, the coordinates will be correct while for the charts on the right, they will be negative. All you need to do is to pass an event with a correctly adjusted `chartX` value in the event listener callback.

**Demo**
https://jsfiddle.net/BlackLabel/86msfpd5/

**Comment by melloc01** [comment]
That's nice, I actually had figured that out on the way, forgot to get back here. 

Actually I am using rxjs subject to hold the `x, originChart` value since there is not only highcharts on the dashboard, so I'm doing something like this, what do you think? I am probably overdoing stuff

```js
pointService.subscribe(point => {
        try {
            const parent = document.querySelector('.dashboard-content')
            const originChart: Highcharts.Chart | void = point.chart

            if (point.x == null) TooltipService.hideTooltips()

            // highlight points in all rendered charts
            Highcharts.charts.forEach(chart => {
                if (!chart) return

                if (point.x == null) {
                    chart.hoverPoint = null
                    chart.hoverPoints = []
                    // Hide the previous highlighted point
                    // this is hiding other points
                    // chart.hoverPoints.forEach(p => p.setState('normal'))

                    return
                }

                // Only visible widgets
                const widgetContainer = Utils.closestParent(chart.container, '.widget-container')
                if (!Utils.isDomElementVisible(parent, widgetContainer)) return

                const siblings = chart.series
                    .map(s => s.visible && pointService.getClosestPoint(s.points, { x: point.x }))
                    .filter(Boolean)

                if (!siblings.length) return

                const hoverPoint = siblings.find(p => p.x === point.x) ?? siblings[siblings.length - 1]
                const { enabled, shared } = chart.tooltip.options

                chart.hoverPoints?.forEach(p => p.setState(''))
                chart.hoverPoint = hoverPoint
                chart.hoverPoints = siblings
                chart.hoverPoints?.forEach(p => p.setState('hover'))

                // return to not double-refresh tooltip
                if (originChart === chart) return

                // Show the tooltip
                if (enabled) {
                    chart.tooltip.refresh(shared ? siblings : hoverPoint)
                }

                const xAxis = hoverPoint.series.xAxis
                const chartX = Math.max(xAxis.toPixels(point.x, false), 0)
                xAxis.drawCrosshair(
                    {
                        ...(point?.event ?? {}),
                        chartX: xAxis.chart.inverted ? null : chartX,
                        chartY: xAxis.chart.inverted ? chartX : null
                    },
                    hoverPoint
                )
            })
```

**Comment by KacperMadej** [comment]
Thank you for sharing the code.
The code change suggested in the first comment by Paweł is smaller as long as the original demo code is used.
It seems like parts of your code are not in the snippet, so maybe it might be possible for you to share a live demo?
In the end, if your code works fine then it's all good. It doesn't look like there is an overdoing here.
For technical support please see https://www.highcharts.com/blog/support/
