### ISSUE TITLE
Consecutive stacking area graph points render incorrectly

### ISSUE THREAD

**Issue by glovvorn** [highcharts/highcharts#15107]
When using consecutive stacked graphs, the data point / marker for the point where one graph ends and the other begins renders incorrectly.  This causes the entire graph to appear to take up less of the overall chart area.

#### Expected behaviour
All data points / markers render on the top line of the area chart.

#### Actual behaviour
The marker / tooltip point is rendered above both graphs off by itself, and it causes the rest of the graph to render lower in the chart area.

#### Live demo with steps to reproduce
https://jsfiddle.net/aujxzr31/

#### Product version
Highcharts 6.2.0 and newer

#### Affected browser(s)
Only tested in Chrome.  May affect others as well.

**Comment by glovvorn** [comment]
This is probably a better example of what I'm trying to achieve.  

https://jsfiddle.net/f7sm3vLd/3/

And here's on 'graph group'

https://jsfiddle.net/f7sm3vLd/2/

Overall, I have a few groups of graphs that will look like this that I'm trying to display on the same chart on top of each other, which is why I'm trying to use stacked graphs.

**Comment by KacperMadej** [comment]
Hi @glovvorn 

Thank you for reporting the problem.

The stacking logic seems to be working correctly. The stacking starts at the point, so only the point is stacked as the area before the point has nothing to be stacked on.

It is possible to set `connectNulls: true` to get a chart like this: https://jsfiddle.net/BlackLabel/0p1tcamu/  
Could you add an image of the expected chart? If the points shouldn't be stacked then you could disable series stacking.
