### ISSUE TITLE
Working with microseconds data in highstock and tickpositions on x-axis

### ISSUE THREAD

**Issue by raghava2121** [highcharts/highcharts#15101]
#### Expected behaviour

X-axis should show proper microseconds. (Hh:mm.ss.milliseconds and microseconds)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/6311517/107518912-952ea400-6bd5-11eb-87d9-ad4a487d3cf5.png)

#### Live demo with steps to reproduce

http://jsfiddle.net/raghava_2121/L6euqt57/

#### Product version
Highstock 

#### Affected browser(s)

Chrome

**Comment by PaulDalek** [comment]
Hi @raghava2121

Thank you for contacting us and reporting this. Time is counted in milliseconds in Highcharts but if you want format to xAxis labels to show microseconds (if a timestamp has a decimal), you can use the [`formatter`](https://api.highcharts.com/highstock/xAxis.labels.formatter) function.

**Demo**
https://jsfiddle.net/BlackLabel/nokxj5gf/
