### ISSUE TITLE
lines ,points squeezed instead of expanding out(screenshot attached)

### ISSUE THREAD

**Issue by anirudh54** [highcharts/highcharts#15126]
> #### Expected behaviour
shouldn't the chart adjust itself so that there is no empty space at the top and bottom? just want to know if its a bug or my configuration setup is wrong.

#### Actual behaviour
<img width="721" alt="chart" src="https://user-images.githubusercontent.com/6538684/107790629-fa42e080-6d20-11eb-91e0-5cbfd9706f05.PNG">

**Comment by PaulDalek** [comment]
Hi @anirudh54 

Thank you for contacting us and reporting this. Please, provide us with a live example of a chart from the image in order for us to see your configuration. Thanks.

**Comment by anirudh54** [comment]
Sorry ! you can close the issue. the issue was with the tickinterval not setting up as required.
