### ISSUE TITLE
Networkgraph - series update

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#15134]
#### Expected behaviour

The networkgraph series should be changed after triggering the update event.

Workaround: https://jsfiddle.net/BlackLabel/8w6xgjkp/

#### Actual behaviour

The networkgraph series doesn't update. 

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/g2L7ateu/

It seems that the color update used to work in the previous version: https://jsfiddle.net/BlackLabel/szx8Lhmt/, however, the update of the `layoutAlgorithm` property didn't. 

#### Product version

Highcharts JS v9.0.0 (2021-02-02)

**Comment by KacperMadej** [comment]
Bisected to https://github.com/highcharts/highcharts/commit/df6f164217094d8f5dd912d3b7120ab0b51d0891

**Comment by KacperMadej** [comment]
_Internal note:_
Let's keep this issue for the regression and I will open a new issue for the layoutAlgorithm in networkgraph.
