### ISSUE TITLE
Contrast issue on highcharts.com/demo 

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#15132]
Microsoft Accessibility Insights reports contrast issues with selected elements in the menu, as well as code text in the chart description on our demo pages (see red highlighted rectangles). The footer text is also reported as having too low contrast against the background.

![107470140-ec5e5580-6b90-11eb-86ab-528040e7a200](https://user-images.githubusercontent.com/5276642/107926693-505c9180-6f76-11eb-918b-a8054d25c9e3.png)

**Comment by goransle** [comment]
Fix is live. @LindaSve93 FYI: the footer contrast (and also the YouTube link missing a `title`) also applies to the homepage.
