### ISSUE TITLE
Type YAxisOptions is missing property ordinal

### ISSUE THREAD

**Issue by d3dc** [highcharts/highcharts#15130]
#### Expected behaviour
YAxisOptions has property ordinal

#### Actual behaviour
Build fails due to typescript error

#### Product version
9.0.0

**Comment by PaulDalek** [comment]
Hi @d3dc 

Thank you for contacting us and reporting this. As you can read in the API (or see in the [code](https://code.highcharts.com/stock/highstock.src.js) directly - look for the comment above the `Axis.defaultYAxisOptions` initialization), the [`ordinal`](https://api.highcharts.com/highstock/xAxis.ordinal) option should apply only to the `xAxis`. Could you please provide us with more details about the error that you encounter? Thanks.

**Comment by d3dc** [comment]
Graph isn't part of my code, but was included in my migration task from v6 in the last month.

I reached out and am waiting to hear if the prop had a purpose.

**Comment by d3dc** [comment]
More than likely this is a migration issue. I'll close it.
