### ISSUE TITLE
Directional Movement Index (DMI) technical indicator

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#15140]
Implement DMI technical indicator:

- [x] - algorithm (ATR should not be included, loaded manually)
- [x] - algorithm tests - (@karolkolodziej)
- [x] - create a demo (e.g. https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/indicators/apo/)
- [x] - describe `params` in API (e.g. https://api.highcharts.com/highstock/series.ad.params)
- [x] - add it to list of indicators (https://www.highcharts.com/docs/stock/technical-indicator-series) - if necessary, add to the bottom list too: https://www.highcharts.com/docs/stock/technical-indicator-series#multiple-series-bindings
- [x] - add it to indicators-all.js (http://code.highcharts.com/stock/indicators/indicators-all.src.js)
- [x] - test it in StockTools (e.g. separate yAxis for Oscillators)
- [ ] - test it in Popup (e.g. if params are not missing)
- [x] - if necessary, add `lang` in API (https://api.highcharts.com/highstock/lang.navigation.popup)
- [x] - add the indicator to the demo with all indicators (http://utils.highcharts.local/samples/#view/stock/demo/all-indicators)

**Comment by imdanshraaj** [comment]
how can i remove dx line in highcharts? i just want to show plus di and minus di line.

**Comment by karolkolodziej** [comment]
@imdanshraaj The easiest would be simply hiding that line by setting the line width to zero. 
In this case, you also have to change the tooltip - [demo](https://jsfiddle.net/BlackLabel/8Lcrx4hz/).

If that is not what you have been looking for you can always create your custom indicator - [guide](https://www.highcharts.com/docs/stock/custom-technical-indicators).

For future reference, with questions like this, please contact us via [available support channels.](https://www.highcharts.com/blog/support/)
