### ISSUE TITLE
Stock Tools gui flags buttons are described incorrectly or don't work correctly

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#15156]
The flags names and icons say that different button adds flag with a different shape: circle, rectangle, diamond, simple (rectangle without connector).

When I'm adding a circle flag, a circle shape with a connector is added and this is correct. When I'm adding a diamond flag, I expect the shape to be diamond - but it's a rectangle (just the same as for 3 of all 4 flag shapes). Only circle and rectangle have the correct flag's shape.

The only difference between a diamond and a rectangle flag is the position of the connector.

![image](https://user-images.githubusercontent.com/23310742/108086162-5fc30400-7076-11eb-87ba-ea8f11402406.png)

Also, "Flag square" should be named "Flag rectangle".

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/stock/stock-tools-gui

#### Product version
Stock 9.0.1 (it has always worked this way)

**Comment by KacperMadej** [comment]
@raf18seb 
Looks like a bug - the implementation does not follow the documentation. If this never worked as expected then it's just not a regression. Not sure why labeled as undecided.

**Comment by pawelfus** [comment]
It's not decided if the shape should be implemented (bug) or rather "docs" problem (wrong description)
