### ISSUE TITLE
X Axis Labels with Auto Rotate on Chart.Redraw() displays incorrectly on specific widths.

### ISSUE THREAD

**Issue by dragoshzava** [highcharts/highcharts#15152]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/3819194/108057480-fe3d6e00-7052-11eb-8fcf-6a69fd60c741.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/3819194/108057504-08f80300-7053-11eb-947e-78b2c834d369.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/Resems/ub4faw02/

#### Product version
Tested 8.2.2 - 9+ ( Latest )

#### Affected browser(s)
Chrome, Firefox, Edge - All latest versions.

#### Comment.
Unfortunately our containers are flexible, so the end users can resize the width of containers to their liking.

Would appreciate any solutions or suggestion.

As far as looking from the source code of highcharts, the issue lies in this part -> 

`chart.plotWidth = plotWidth = Math.max(0, Math.round(chartWidth - plotLeft - chart.marginRight));`

and in function unsquish

`slotSize = this.len / (((this.categories ? 1 : 0) +
                        this.max -
                        this.min) /
                        tickInterval)`

Because this function is called only in the first time, after plotLeft is updated, the function unsquish is not called again for a recalculation, thus on first chart render it works with initial width, on redraw it works with the updated width, hope this helps.

**Comment by KacperMadej** [comment]
Hi @dragoshzava 

Thank you for reporting the problem.

For a workaround, you could force the xAxis redraw: https://jsfiddle.net/BlackLabel/swL8hyoc/

Minimal demo: https://jsfiddle.net/BlackLabel/or5bjLze/

**Comment by dragoshzava** [comment]
Hey @KacperMadej , thanks a lot.

In the end i made it working by adding and saving the previous plotWidth and check if it changed.

```javascript
Highcharts.addEvent(Highcharts.Chart, 'afterSetChartSize', function (e) {
        //handle multiple chart types
        if(this._previousPlotWidth && this.xAxis && this.xAxis.length) {
            if(this._previousPlotWidth != this.plotWidth) {
                this.xAxis[0].tickInterval = this.xAxis[0].unsquish()
            }
        }
        this._previousPlotWidth = this.plotWidth;
    });
```

Hope this comes in handy for anyone.
