### ISSUE TITLE
Networkgraph: layoutAlgorithm

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#15163]
#### Expected behaviour
Working updates and different behaviours for different series if they have different `layoutAlgorithm` options.

#### Actual behaviour
Updating `layoutAlgorithm` for networkgraph is not working and the `layoutAlgorithm` seems to be shared for all series.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/g2L7ateu/1/

#### Related issue
https://github.com/highcharts/highcharts/issues/15134

**Comment by w99910** [comment]
Can I know if this issue is fixed? I'm still not able to update the options. 
Is there workaround that I can solve it?
Thanks.
**Live demo**
[https://codepen.io/w99910/pen/bGqGpyp](https://codepen.io/w99910/pen/bGqGpyp)

**Comment by KacperMadej** [comment]
The issue is open and not fixed.
The workaround is to use the same layout algorithm for all series in the same chart.
