### ISSUE TITLE
Add padding to packedbubble chart when useSimulation is false

### ISSUE THREAD

**Issue by LeoRosse** [highcharts/highcharts#15169]
#### Expected behavior
Is there any way to set bubble padding when the useSimulation option is false?

We would need to space out the bubbles a bit.

#### Actual behaviour
Actually, the bubbles are too attached, it seems that the padding is only editable when the useSimulation is true, through the layoutAlgorithm.
 
Thanks a lot! 

<img width="853" alt="Schermata 2021-02-18 alle 11 53 18" src="https://user-images.githubusercontent.com/36762103/108346668-e9daac00-71df-11eb-9320-7453d1784913.png">

**Comment by KacperMadej** [comment]
Hi @LeoRosse 

Thank you for contacting us.

This option is not yet supported.

_Internal note:_
The initial position (as used for packed bubbles when the simulation is disabled) of the points is calculated based only on the radii of the bubbles and the padding is not considered.
