### ISSUE TITLE
sub-title not using $subtitle-font-size as font-size

### ISSUE THREAD

**Issue by NielsHolt** [highcharts/highcharts#15162]
#### Expected behaviour
Font-size of sub-title to be 1em as given by $subtitle-font-size

#### Actual behaviour
Font-size of sub-title = 12px set in svg.highcharts-root

#### Live demo with steps to reproduce
Any demo

#### Product version
9.0.1

#### Solution
Extend the class `highcharts-subtitle` with `font-size`
```
.highcharts-subtitle {
    fill: $neutral-color-60;
    font-size: $subtitle-font-size; //<---
}

```

**Comment by KacperMadej** [comment]
Hi @NielsHolt 

Thank you for reporting the problem.
Please add a live demo - I'm unable to recreate the problem based on your description: https://jsfiddle.net/BlackLabel/5go8yvpu/1/

For styling the subtitle you could use the API option https://api.highcharts.com/highcharts/subtitle.style

**Comment by NielsHolt** [comment]
Hi @KacperMadej 
In your jsfiddle you have put the SCSS-variable `$subtitle-font-size` in the css.  That will not work...
If you create a chart with `options.styledMode: true` the subtitle is styled by class `highcharts-subtitle` but the class do not have `font-size: $subtitle-font-size;`

**Comment by KacperMadej** [comment]
I am still not sure if this is what you want to report, but is it that [the CSS file for styled mode](https://code.highcharts.com/css/highcharts.css) doesn't use the SCSS `$subtitle-font-size` ?
https://github.com/highcharts/highcharts/blob/e665778f5dc02033d5e51f217367129e7ec7cb60/css/highcharts.scss#L36

**Comment by NielsHolt** [comment]
Yes :-)
