### ISSUE TITLE
Animation on wrong pie slice with series addPoint

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#1517]
See this example to illustrate: http://jsfiddle.net/VTnTU/

When adding a point the new slice is added but lacks animation. Instead the second last slice is animated.

tested in Chrome and IE10

**Comment by pawelfus** [comment]
What kind of animation is expected? Compare:

- animate from inner radius: 
![anim_with_radius](https://cloud.githubusercontent.com/assets/1453926/9907715/b5cc8466-5c90-11e5-8d3c-d70227ea4573.gif)

- animate from the next points edge: 
![anim_without_radius](https://cloud.githubusercontent.com/assets/1453926/9907722/bfd46cbc-5c90-11e5-91af-b3997c60d553.gif)

**Comment by highslide-software** [comment]
Cool gifs :)

Which one do you prefer? Does one of them have simpler code?

**Comment by pawelfus** [comment]
Thanks! LiceCap is a nice tool for gifs :) 

The code is almost the same, difference:

- `r: series.oldCenter[3] / 2,` (animate from inner-radius)
- `r: shapeArgs.r,` (animate with full radius)

I prefer top one - consistent with initial animation for a pie.

**Comment by highslide-software** [comment]
Okay, then we go for that!

**Comment by pawelfus** [comment]
Notes:

- I tried to create more generic solution, easy to extend for other series. As for example we can also implement similar animation for funnel? See: http://jsfiddle.net/xomotuu0/ (however, here we have two missing animations: for a new point and when point enters/leaves neck)
- Any comments highly appreciated

**Comment by highslide-software** [comment]
Okay, I didn't realize we needed that much extra code... It's a bit too much for just eye-candy.

**Comment by pawelfus** [comment]
I was afraid of that kind of response ;) In fact, the problem is that `setData()` with the same number of points animates them and things are getting complicated. I think this can be simply worked around by this snippet: http://jsfiddle.net/VTnTU/6/ (without adding anything extra to the core)

    var series = chart.series[0],
    	point,
    	oldCenter = chart.series[0].center;
    
    series.addPoint(Math.random() * 100); 
    point = series.points[series.points.length - 1];
    point.graphic.attr({
        start: series.endAngleRad,
        end: series.endAngleRad,
        innerR: oldCenter[3] / 2,
        r: oldCenter[3] / 2,
        x: oldCenter[0],
        y: oldCenter[1]
    }).animate(point.shapeArgs);
