### ISSUE TITLE
AST trows a warning for a button with theme with states

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#15178]
#### Behaviour
If states are used in buttonTheme I get a warning in the console:
`Highcharts warning: Invalid attribute 'states' in config `

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/rangeselector/styling/

or 

https://api.highcharts.com/highcharts/chart.resetZoomButton.theme
Steps: zoom to show the button -> warning

#### Product version
v9.0.0+

#### Workaround
Ignore it - everything works fine anyway.

#### Internal notes
`states` end up in `normalState` (from the theme), but could be safely deleted before running `AST.filterUserAttributes(normalState)` because `normalState` is already a copy and `states` are provided to `SVGRenderer.prototype.button` as arguments and later used from them

**Comment by drmrbrewer** [comment]
@TorsteinHonsi @KacperMadej @DJTechnoo I'm seeing this warning in HC 10.0.0... seems to have re-appeared?

Steps to reproduce:

- Open the `Theming the button` demo linked from https://api.highcharts.com/highcharts/chart.resetZoomButton.theme
- zoom to show the button
- warning is shown in console

BTW is it possible to add a *top* padding for the button text (or a negative bottom padding)?  I'm finding that the text is sitting a little high in the button:

![image](https://user-images.githubusercontent.com/9009792/161720355-38574093-4785-4701-b48b-626c936f6f97.png)

**Comment by TorsteinHonsi** [comment]
Thanks! The fix for this issue only fixed range selector and map navigation buttons. So we should probably dig a bit deeper to try to cover all kinds of buttons.

Regarding offsetting the text, there is currently no API option for it, but CSS transform seems to work fine: https://jsfiddle.net/highcharts/eLkfz40w/
