### ISSUE TITLE
Point marker and grid line don't always line up (crisping)

### ISSUE THREAD

**Issue by lukasgeiter** [highcharts/highcharts#15179]
#### Expected behaviour

In order to center point markers on 1px wide grid lines, I've set the marker radius to 2.5. I expect every marker to perfectly line up with the grid lines, crosshairs etc.

#### Actual behaviour

Some of the markers are not horizontally centered on the grid line.

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/up2ch65b/

On my screen markers at 0 and 2 are both offset 1 pixel to the right. It might be different for you depending on your screen resolution and scaling factor, so here's a screenshot of the issue as well: 
![image](https://user-images.githubusercontent.com/5907946/108422698-2d143980-7237-11eb-9315-e79982c55e60.png)

#### Analysis

I've identified the cause for this behavior in the following piece of code:

https://github.com/highcharts/highcharts/blob/8de4d3091cd6f59c230e3dcfd682d0c49b71fdfd/ts/Core/Series/Series.ts#L5221-L5223

The value of `point.plotX` is rounded _before_ subtracting the radius. In order to account for floating point radii, the rounding should be done _after_ subtracting the radius.

Here is the same demo but with my proposed fix: https://jsfiddle.net/aw2exbpr/

**Comment by KacperMadej** [comment]
Hi @lukasgeiter 

Thank you for reporting the problem and suggesting the solution.

_Internal note:_
It looks like the problem shows only if the marker radius is defined with sub-pixel precision.
