### ISSUE TITLE
Highcharts  Export throwing error with custom buttons

### ISSUE THREAD

**Issue by tashigarg** [highcharts/highcharts#15189]
#### Expected behaviour
Using highcharts with react. Adding a custom button to do export actions on highchart.
First time export works fine. Next time it always fails with error
Cannot read property 'exporting' of undefined

Click on custom button without refreshing. It always fails.

#### Actual behaviour
It should work seamlessly as it works with default chart buttons.

#### Live demo with steps to reproduce

https://codesandbox.io/s/export-pdf-s4rlr
- Click on ''Export PDF' button, chart pdf is generated
- Again click on Export PDF button. It fails

#### Product version

9.0.0

#### Affected browser(s)
All

**Comment by khlieng** [comment]
If you wrap the setting of `this.chartInstance` in the callback with `if (!chart.options.chart.forExport)` it should work.

**Comment by KacperMadej** [comment]
Hi @tashigarg 

Thank you for contacting us.

When a chart is exported the exporting module is creating a copy of the chart - a new chart with modified options. The copy runs the same callbacks as the original chart. A solution is suggested in the above comment.

For technical support please see https://www.highcharts.com/blog/support/

**Comment by khlieng** [comment]
And heres a demo using a ref: https://codesandbox.io/s/export-pdf-forked-l0cj4

**Comment by tashigarg** [comment]
Thank you. That really helps. It works seamlessly now.
