### ISSUE TITLE
Color zones not working with polar charts

### ISSUE THREAD

**Issue by uajqq** [highcharts/highcharts#15180]
#### Expected behaviour
Polar chart colors should change according to zones set on the y-axis, as with a horizontal chart. Color should change with increasing distance from the center of the graph.

#### Actual behaviour
The zones are oriented horizontally across the polar chart instead of radially around the center.

#### Live demo with steps to reproduce
https://jsfiddle.net/h21q9n4y/

#### Product version
Latest public Highcharts

#### Affected browser(s)
Safari, Chrome

<img width="362" alt="Screen Shot 2021-02-18 at 9 45 59 PM" src="https://user-images.githubusercontent.com/46248396/108450165-b412e300-7232-11eb-9d13-bce0b0b3b889.png">

**Comment by KacperMadej** [comment]
Hi @uajqq 

Thank you for reporting the problem.

Currently, zones are not implemented for polar charts.

As a workaround, you could use stacked series - demo: https://jsfiddle.net/BlackLabel/chwxrf79/1/
