### ISSUE TITLE
allowedAttributes missing on type Highcharts.AST

### ISSUE THREAD

**Issue by EstelleDoreau** [highcharts/highcharts#15192]
#### Actual behaviour
allowedAttributes missing on type Highcharts.AST
doc : https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#filtering

Hello, 
I need to push _onclick_ into allowedAttributes, but property 'allowedAttributes' does not exist on type 'typeof AST'. 
Is this an oversight or do I need to do something else?
thanks

#### Product version
Highcharts version 9.0.1

**Comment by khlieng** [comment]
It looks like there is a typo in the doc comments we generate declarations from.

**Comment by EstelleDoreau** [comment]
hello, 
OK thanks. 
But I think in the pull request, you have overwritten allowedTags instead of add allowedAttributes to AST's class

Have a nice day

**Comment by KacperMadej** [comment]
@EstelleDoreau 
`allowedTags` were duplicated. You could see unfixed duplication in the docs here: https://api.highcharts.com/class-reference/Highcharts.AST)
Nothing will be removed - all 3 options will be still available after the fix.

**Comment by EstelleDoreau** [comment]
Hello @KacperMadej 
Sorry, I thought it had been replaced in the class here:
![image](https://user-images.githubusercontent.com/15243798/108833850-ac09c900-75cd-11eb-97fe-aa26d68f8948.png)

:) thanks !
Have a nice day

**Comment by a2441918** [comment]
@TorsteinHonsi What should I use instead of allowedAttributes? I am trying to allow 'data-html2canvas-ignore'. I am on Highcharts 9.0.1

**Comment by a2441918** [comment]
@TorsteinHonsi What should I use instead of allowedAttributes? I am trying to allow 'data-html2canvas-ignore'. I am on Highcharts 9.0.1

**Comment by KacperMadej** [comment]
@a2441918 
Use `allowedAttributes` for attributes. Is 'data-html2canvas-ignore' an attribute? If yes, then use `allowedAttributes`. If no, then let us know what is it through comment with more info and a live demo.

In general, for technical support see https://www.highcharts.com/blog/support/

**Comment by KacperMadej** [comment]
@a2441918 
The error you getting is fixed (that is why the issue is closed) but the fixed code is not yet published - it will be a part of the next release.

**Comment by a2441918** [comment]
@KacperMadej Thanks

**Comment by pjkp** [comment]
> @a2441918
> The error you getting is fixed (that is why the issue is closed) but the fixed code is not yet published - it will be a part of the next release.

Hi, have you got an idea about the date of the next release @KacperMadej ? Thanks.
