### ISSUE TITLE
update colors for each segment on graphe dynamiccally

### ISSUE THREAD

**Issue by aszymkiw** [highcharts/highcharts#15214]
Hello,

I would like to know if it was possible to change color each segment without using the range zone of highchart.
I saw a plugin : multicolor series which permits this, but it is not available with highchart-vue. I tried this plugin but there are many problems, so i returned to highchart-vue.

I know that it is possible to change the color with the range or in the plotoption. But i would like to change color dynamiccally.
Thank you !

**Comment by KacperMadej** [comment]
Hi @aszymkiw 

For technical support please see https://www.highcharts.com/blog/support/

Zones are for color change within defined segments. When contacting technical support please describe why and how zones are not working for you.
