### ISSUE TITLE
Bar chart with centerInCategory enabled - tooltips display in the "non centered" position

### ISSUE THREAD

**Issue by DonaldBrower** [highcharts/highcharts#15217]
#### Expected behaviour
after setting series.bar.centerInCategory to true, the tooltip will display right next to the bar.

#### Actual behaviour
the tooltip displays where it would if the bars weren't centered.

#### Live demo with steps to reproduce
[https://jsfiddle.net/seaberry/5d2trz90/13/](https://jsfiddle.net/seaberry/5d2trz90/13/)

This is the demo from the series.bar.centerInCategory section of the docs. The only difference is that the chart type is "bar" instead of "column".

You'll also notice that the data appears to be in reverse order, but setting xAxis.reverse to false fixes this. 

#### Product version
Highcharts 8.2.2

#### Affected browser(s)
I tried this on Chrome 88 and Firefox 85

**Comment by KacperMadej** [comment]
Hi @DonaldBrower 

Thank you for reporting the problem.

You could test the fix in this demo https://jsfiddle.net/BlackLabel/8f34hqmp/

**Comment by DonaldBrower** [comment]
Seems to do the trick! Thank you very much @khlieng and @KacperMadej
