### ISSUE TITLE
Updating options with different amount of colorAxis fails

### ISSUE THREAD

**Issue by artu-ole** [highcharts/highcharts#15213]
#### Expected behaviour
Expecting to be able to change amount of `colorAxis` on the fly:
<img src="https://user-images.githubusercontent.com/15938416/109005290-74c11800-76b2-11eb-9f28-fbe76ac335ad.png"  width="250" height="125" /> => <img src="https://user-images.githubusercontent.com/15938416/109005606-ce294700-76b2-11eb-9015-16841db3dcc1.png" width="250" height="125" /> => <img src="https://user-images.githubusercontent.com/15938416/109005290-74c11800-76b2-11eb-9f28-fbe76ac335ad.png"  width="250" height="125" />

#### Actual behaviour
It seems to function if amount of `colorAxis` increases or decreases once, however, fails switching from more to less to more again.
In the demo:
1 `colorAxis` -> 2 `colorAxis` - ok
2 `colorAxis` -> 1 `colorAxis` - ok
1 `colorAxis` -> 2 `colorAxis` - fail

![image](https://user-images.githubusercontent.com/15938416/109005161-51966880-76b2-11eb-8901-374de6bea1c7.png)

#### Live demo with steps to reproduce
Taking "Column chart with color axis" from [docs](https://api.highcharts.com/highcharts/colorAxis) as a basis:
https://jsfiddle.net/artuole/x5fnbjer/

just 2 -> 1 -> is enough to reproduce:
https://jsfiddle.net/artuole/x5fnbjer/17/

#### Product version
9.0.1

**Comment by KacperMadej** [comment]
Hi @artu-ole 

Thank you for reporting the problem.

You could test the fix here: https://jsfiddle.net/BlackLabel/phqrtd50/
(I have added a copy of the initial options to be used in the last update because the second color axis gets erased from `options` object after the first update)

**Comment by artu-ole** [comment]
Hi @KacperMadej,

Thank you for the quick turnaround on the issue! Fix works for the most part, other than for the fact that you mentioned where `colorAxis` gets erased from the options after the first update in your demo and it doesn't get erased if first update has has 1 `colorAxis` and next one has 2 two:
https://jsfiddle.net/artuole/4L25bmgr/ vs https://jsfiddle.net/artuole/4L25bmgr/7/
Isn't this a bug in it of itself and one should be able to trust that their options options object will not be mangled up?

**Comment by artu-ole** [comment]
My bad, I do see now that it get's updated in the first case as well instead of library keeping own copy of the array it seems. 
It's all good by me then if that's a design decision, the original bug is indeed fixed for all intensive purposes.

**Comment by KacperMadej** [comment]
> Isn't this a bug in it of itself and one should be able to trust that their options options object will not be mangled up?

Yes, it is. I have opened a new issue for this here: https://github.com/highcharts/highcharts/issues/15234
