### ISSUE TITLE
Page Up/Down should scroll legend pages when navigating with keyboard

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#15224]
Page Up/Down should scroll between legend pages when navigating with the keyboard.

Something like this: https://jsfiddle.net/ce3hujs0/1/show 

We would however only want this to be active when the legend is focused, and we would want to move the focus to the first item on each page when scrolling.

**Comment by oysteinmoseng** [comment]
Note: We might also want the page up/down buttons included in the tab order.

**Comment by Ashwinipola26** [comment]
Regressed the bug in the latest sales environment
#URL:[Dynamics 365 Sales Forecasting Grid](https://tp1sg832plain73110org1.crm10.dynamics.com/main.aspx?appid=ce661ce0-44e8-eb11-94ef-000d3a1436ad&pagetype=control&controlName=ForecastingControls.FieldControls.ForecastGridPage)
Server version: 9.2.21114.00106
Client version: 1.4.3523-2111.4
Organization name: tp1sg832plain73110org1

### OS Details:
Windows 10 Version 20H2(OS Build 19042.1288)
### Browser Details:
ChromiumEdge Version 97.0.1072.13 (Official build) dev (64-bit)

Issue is fixed, video added for reference
Hence closing the bug

**Comment by oysteinmoseng** [comment]
Closing as this was added in Highcharts v9.3.0
