### ISSUE TITLE
Custom log axis scale breaks in version 9

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#15228]
Based [on this](https://www.highcharts.com/forum/viewtopic.php?t=39137) I have been using a custom scale on my x axis to create an axis that is both `datetime` and `log` (or indeed any one of a number of different custom scales, not just linear or log).

This is how it works in `v8.2.2`: http://jsfiddle.net/dzwcx50j/  (log scaling)

And this is it in `v9.0.1`: http://jsfiddle.net/1vs9ow40/   (log scaling not working)

Worryingly, I do see the following comment in the source for `v8.2.2`:

	// HC <= 8 backwards compatibility, allow wrapping
	// Axis.prototype.lin2log and log2lin
	// @todo Remove this in next major

So this might explain why it isn't working in `v9.0.1`... but please tell me it is still possible in some way to achieve custom scaling on my `datetime` x axis?  This is such a powerful feature.  For example it easily allows my datetime axis to be set up so that it stretches out during daytime hours (to show more detail where it matter), and contract during nighttime hours (asleep anyway), or to have a square root scaling, or to have a linear scale for each day but getting more compressed each day, or some combination of the above.

Please tell me it will still be possible to override `lin2log` and `log2lin`  🙏🙏🙏

**Comment by khlieng** [comment]
You could do something like this: http://jsfiddle.net/230fbwkh/9/

**Comment by drmrbrewer** [comment]
Thanks.  Phew, at first sight it seems to work the same... I'll have to do some more extensive testing to see if it works the same in all situations... do you know of any reason why it wouldn't?

**Comment by khlieng** [comment]
No, it should be fine :)

**Comment by drmrbrewer** [comment]
OK thanks, I'll do some more playing, but assume it's OK for now and thanks for your assistance!

**Comment by TorsteinHonsi** [comment]
@drmrbrewer I think you copy-pasted your setup from one of our samples. The updated version of our sample is https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/yaxis/type-log-negative/ .

**Comment by drmrbrewer** [comment]
@TorsteinHonsi thanks.  It's very useful to have (and still have!) the ability to customise the log scaling (particularly to make it something that really isn't log scaling at all).  👍

**Comment by TorsteinHonsi** [comment]
Yes, I know! We just needed to refactor it a bit.
