### ISSUE TITLE
chart.update() does not correctly draw chart fill

### ISSUE THREAD

**Issue by ndom91** [highcharts/highcharts#15220]
#### Expected behaviour

When changing datetime ranges in the dropdown we're running running a vue watch handler() to run `chart.update()`. 

In the `update()` we're updating `xAxis: { min, max }` and `series[0]: { data: { ... }}`. 

See code:

```js
  watch: {
    check: {
      deep: true,
      handler (newData) {
        this.$refs.chartRef.chart.showLoading()
        this.$refs.chartRef.chart.update({
          xAxis: {
            alignTicks: true,
            min: new Date(this.$route.query.from * 1000).getTime(),
            max: new Date(this.$route.query.to * 1000).getTime()
          },
          units: [
            ['hour', [0, 3, 6, 12]],
            ['day', [1]]
          ],
          series: [{
            data: newData.chartData.map(hour => ({
              y: hour[this.activeChart],
              x: new Date(hour.bucket).getTime()
            }))
          }]
        }, true, false, false)
        this.$refs.chartRef.chart.hideLoading()
      }
    }
  },
```

The graphs should update and the fillGradient should be fully filled as it is on initial render. However, when moving from a smaller datetime range to a larger one, the fillGradient (same error happens with a static fill color btw) doesn't cover the whole series. 

Am I missing something in the `update()` function? We're always just swapping series[0] for another, i.e. only displaying one series at a time. I've tried adjusting the other arguments on the `update()` method, i.e. redraw, oneToOne and animation and all variants produce said behavior.

#### Actual behaviour

As you can see, the fillGradient doesn't fill the entire width of the chart / series.

**EDIT**: It seems to always be missing the fill for the amount of data it was previously covering. For example, it I had it set to 'last 24 hours' and go to 'last 7 days', the fillGradient will be missing for the last day of the 'last 7 days' chart. 

Same deal with 'last 30 days', if I go from 'last 7 days' to 'last 30 days', the fillGradient will be missing for the most recent 7 days in the 'last 30 days' chart.

![highcharts_fillGlitch1](https://user-images.githubusercontent.com/7415984/109156937-bd8bd600-7771-11eb-8496-3dcbd21e1124.gif)

With more complicated data, there is a similar and I believe related issue with the chart line appearing glitchy:

![highcharts_fillGlitch2](https://user-images.githubusercontent.com/7415984/109157600-810caa00-7772-11eb-8107-f7b9f416dece.gif)

**EDIT** I've slowed the animation way down to make it clear what its doing:

![highcharts_fillGlitch3](https://user-images.githubusercontent.com/7415984/109160769-84099980-7776-11eb-9621-361ccb2248d8.gif)

It seems to be saying, when moving from 7d -> 30d for example, 'hey we already have the chart drawn for days 1-7, so lets shrink down the original drawing and append it on the end of the newly drawn day 23-30', but then unnecessarily draws that straight connecting line through days 1-7 when the preexisting drawn table would have sufficed. I've tried it with and wihtout `connectNulls` and it doesn't make a difference and `connectEnds` is only for polarCharts, right?

#### Product version

`highcharts: 8.2.2` (glitch still appears in `9.0.1` btw)
`highcharts-vue: 1.3.5`

#### Affected browser(s)

Chromium 88

**Comment by KacperMadej** [comment]
Hi @ndom91 

Thank you for reporting the problem.

An update of series data will try to update each point if the number of points is the same, so all matching points will be updated, and new points will be added to it. This might break the data order and cause the bad animation as in your gifs.

On lower level update (series.setData) there is an option to prevent this behavior (`updatePoints` in [setData](https://api.highcharts.com/class-reference/Highcharts.Series#setData)), but there is no such option in chart.update. A workaround for this could be to run an update with empty data before applying the final data set.

If there is an issue with the wrong points' order then you should be getting an error in the browser console about it. I might be able to better test possible solutions and check if this is a bug if you could create a minimal live demo.

**Comment by ndom91** [comment]
@KacperMadej thanks for the quick response! Calling `update()` with an empty set of data before doing our actual update worked like a charm :tada:
