### ISSUE TITLE
scrollablePlotArea & min/max xaxis not working with column, but work with spline

### ISSUE THREAD

**Issue by mostman47** [highcharts/highcharts#15238]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/3487302/109628354-83b32a80-7af7-11eb-9e77-0de91e8bca33.png)
not too much space

#### Actual behaviour
![image](https://user-images.githubusercontent.com/3487302/109628425-94fc3700-7af7-11eb-9995-d1021647126a.png)
A lot of space

#### Live demo with steps to reproduce
https://jsfiddle.net/vkz23q9s/2/

#### Product version

Highcharts
newest

**Comment by KacperMadej** [comment]
Hi @mostman47 

Thank you for reporting the problem.

`pointRange` of series is used to calculate default column widths and to provide additional xAxis padding on both ends (so a column on edge would fit). This could be resolved by setting `pointRange` in series - demo: https://jsfiddle.net/BlackLabel/2e10qbos/

This looks like a bug. If `pointWidth` is set then this should be used for the xAxis padding (that serves for column fitting on edges).

**Comment by mostman47** [comment]
Thanks so much

Nam Phan 

    On Tuesday, March 2, 2021, 10:11:01 AM PST, Kacper Madej <notifications@github.com> wrote:  
 
 


Hi @mostman47

Thank you for reporting the problem.

pointRange of series is used to calculate default column widths and to provide additional xAxis padding on both ends (so a column on edge would fit). This could be resolved by setting pointRange in series - demo: https://jsfiddle.net/BlackLabel/2e10qbos/

This looks like a bug. If pointWidth is set then this should be used for the xAxis padding (that serves for column fitting on edges).
