### ISSUE TITLE
Treatment of html in version 9

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#15235]
Hit `Run` repeatedly with the following jsfiddle:

http://jsfiddle.net/ohmkqzub/

This is meant to simulate that the title is made up of individual components, each of which is subject to different formatting based on user settings, and the word separator is also a user option... and a valid and common choice is just a space character (` `).

Now try it with highcharts version 9:

http://jsfiddle.net/tna93r6x/

Why does the space character get wiped out?  Anything to do with the new [filtering feature](https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#filtering)?

**Comment by KacperMadej** [comment]
Every whitespace text is filtered (maybe @TorsteinHonsi might be able to provide more info about this?):
https://github.com/highcharts/highcharts/blob/3e09d20f3bd33fbb880ae5ffad270e647e4cc1d1/ts/Core/Renderer/HTML/AST.ts#L469-L472

**Workaround**: use a blank Braille block ([source](https://stackoverflow.com/a/59523326/4046096))
Demo: http://jsfiddle.net/BlackLabel/jt8fL1zq/

@drmrbrewer If you need to disable this AST feature for further testing - the ugly hack continues in the top JS code lines: http://jsfiddle.net/BlackLabel/jt8fL1zq/1/

**Comment by drmrbrewer** [comment]
@KacperMadej thanks... I think the only viable workaround is to disable AST... as mentioned in the other issue I can't really see the value of AST in the first place, particularly if it can so easily just be disabled via a hack!

**Comment by TorsteinHonsi** [comment]
I acknowledge this as a bug.

#### Minimal demo
https://jsfiddle.net/highcharts/gj9uv7wz/

>  I can't really see the value of AST in the first place, particularly if it can so easily just be disabled via a hack!
Our aim with the AST and allow-lists is to stop XSS coming in from string configuration in _chart options_. When you have full access to scripting in the page, you can do insert anything you'd like into the DOM, with or without Highcharts.

**Comment by TorsteinHonsi** [comment]
I think the whitespace filtering is an attempt to port this check:

https://github.com/highcharts/highcharts/blob/4f52c155c6f3afe0263b3866cf0db31e52576e82/ts/Core/Renderer/SVG/SVGRenderer.ts#L1293

But whitespace in between elements have a meaning in HTML and SVG, so we need to preserve it for cases like this. Perhaps what we need to do instead is to just trim the HTML before parsing. Then the unit and visual tests will reveal unwanted side effects.

**Comment by drmrbrewer** [comment]
@TorsteinHonsi is this really fully fixed in `9.2.0` like it's claimed to be?  Maybe in your "minimal demo", but here is a continuation of my earlier series above:

HC 8.2.2: http://jsfiddle.net/es54m2jf/ (working)
HC 9.0.1: http://jsfiddle.net/wfsjLpkq/ (broken)
HC 9.0.1: http://jsfiddle.net/k3hgmauq/ (working with hack to disable AST)
HC 9.2.0: http://jsfiddle.net/tdpz5sfr/ (still broken?)

**Comment by TorsteinHonsi** [comment]
Thanks for the additional case! Here's a "minimal demo" of your complex case: https://jsfiddle.net/highcharts/6nLq38eb/

The problem seems to arise with nested structures, so if you remove the outer div, it works as expected.

**Comment by drmrbrewer** [comment]
Trouble is that in my actual code I'm building up the title dynamically from a number of different sources, each with different colour/style, as I've tried to simulate in my demo.  Perhaps the outer div is itself doing something useful, and can't just be removed:

http://jsfiddle.net/thomq2f1/

Bottom line is that, if you disable AST then it works even with messy, perhaps less-than-optimised html:

http://jsfiddle.net/6Lzayqxr/

So there must be a way in which the behaviour of AST can be modified further to avoid judging a user's sub-optimal use of a complicated nested html structure?  :-)

**Comment by TorsteinHonsi** [comment]
Yes, I acknowledge the bug, just proposed a workaround. I'm looking into it.
