### ISSUE TITLE
Mutated axis options on init and after update

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#15234]
#### Behaviour
Properties in a configuration object are overwritten.

#### Live demo with steps to reproduce
1) https://jsfiddle.net/BlackLabel/phqrtd50/2/
after chart's init the chart options for color axes are modified

2) https://jsfiddle.net/BlackLabel/phqrtd50/1/
additionally: after an update, the original options are changed
(based on [fixed colorAxis update code](https://github.com/highcharts/highcharts/commit/1dea0659ea4e1b0b82aae707d762e56b54188284))

_Internal note:_
It looks as if the fix for the colorAxis update only made the issue more visible.

**Comment by khlieng** [comment]
This happens with all axis types, because `merge` doesnt copy arrays: https://jsfiddle.net/bhxmyfg2/18/
