### ISSUE TITLE
Styleable Custom HTML Markers

### ISSUE THREAD

**Issue by jrusc257** [highcharts/highcharts#15237]
I'd like to be able to supply HTML content to markers.  Currently in Styled Mode I cannot apply css attributes to markers because I am limited to an image option, and the SVG space does not allow for conventional CSS.  I need the marker to respond to a color theme, without supplying a new image.  In my specific use case I have a unicode character from an icon font that I would like to include, but cannot because there is no affordance to do so.

In a perfect world I would like plotOptions.series.marker to include a parameter for HTMLContent, or just Content.

![image](https://user-images.githubusercontent.com/2762682/109529998-dbac4b80-7a7b-11eb-9dfa-cbd13da508e7.png)

**Comment by KacperMadej** [comment]
How about using dataLabeles? - demo: https://jsfiddle.net/BlackLabel/kr6jc50w/ 
Data label could be placed in the marker position and supports `useHTML` option to allow HTML.

**Comment by jrusc257** [comment]
@KacperMadej Oh wow, that will end up working perfectly, thank you so much!
