### ISSUE TITLE
xAxis.labels.style -> whitespace bad render of htmlentities depending on the number of values

### ISSUE THREAD

**Issue by AnaelMobilia** [highcharts/highcharts#15254]
#### Expected behaviour
Having HTML entities in graph axes rendered in human readable version.

#### Actual behaviour
When using [`xAxis.labels.style => whiteSpace: 'nowrap',`](https://api.highcharts.com/highcharts/xAxis.labels.style), HTML entities are displayed as is or in human readable format depending the number of points on the axe.

For example (see the live demo), with only 6 points on the graph => HTML entities are displayed as is :
![image](https://user-images.githubusercontent.com/6187125/109829684-0e05a680-7c3e-11eb-97af-23722b93542a.png)

Same example with 9 points activated (quantity appears to depend on screen size) => HTML entities are displayed "human readable"
![image](https://user-images.githubusercontent.com/6187125/109829878-38effa80-7c3e-11eb-9c2c-0e0e53b26d1b.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/x5Lmgv6b/
Let low number of point in the serie in order to have the HTML entities not rendered as human readable.
Add more points (uncomment points) in order to have HTML entities rendered as human readable

#### Product version
Highcharts, current version (9.0.1)

#### Affected browser(s)
Tested on Firefox 86 and Chromium 88

**Comment by khlieng** [comment]
Workaround: http://jsfiddle.net/ph468d3g/

**Comment by KacperMadej** [comment]
Hi @AnaelMobilia 

Thank you for reporting the problem.

Another workaround is to set `useHTML:true` for the axis labels to always correctly display the HTML entities: http://jsfiddle.net/BlackLabel/jneas8b7/

The inconsistency is a bug.
