### ISSUE TITLE
Mouse tracking while updating causes wrong color

### ISSUE THREAD

**Issue by gulrotkake** [highcharts/highcharts#1525]
It seems that if you update a point which is mouse tracked, (colored by TRACKER_FILL?), the color leaks and is used when redrawing other chart points.

In the below fiddle, try hovering one of the bars while an update occurs, on another bar, and watch the color of the updated bars. Remove the hover and eventually (after another update of the discolored bar) the color is properly updated.

Fiddle [edited]: http://jsfiddle.net/highcharts/qqyBP/

**Comment by oysteinmoseng** [comment]
No longer an issue with latest code: http://jsfiddle.net/qqyBP/28/
