### ISSUE TITLE
Empty chart with range selector and marginTop

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#15251]
#### Expected behaviour
Chart should render fine.

#### Actual behaviour
Chart is not rendered.

#### Live demo with steps to reproduce
https://jsfiddle.net/4yu3xrkd/

#### Product version
Highstock JS v9.0.1 (2021-02-15)

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @govinda18 

Thank you for contacting us about the problem.

[`marginTop`](https://api.highcharts.com/highcharts/chart.marginTop) must be a number, then it works fine: https://jsfiddle.net/BlackLabel/k6wgjL4n/
