### ISSUE TITLE
Polygon chart update with wrong data with button click in highcharts react 

### ISSUE THREAD

**Issue by zhenming91** [highcharts/highcharts#15255]
Goal : To change the polygon series used in the chart with a button. For example, I want to display a yellow square initially, then with a button, display a different red square. 

#### Expected behaviour

Yellow square is displayed correctly. When button is clicked, red square is displayed correctly 

#### Actual behaviour

Both yellow and red squares are not displayed correctly. 

#### Live demo with steps to reproduce
https://stackblitz.com/edit/react-a4whqv?file=index.js

#### Product version
    "highcharts": "8.2.2",
    "highcharts-react-official": "3.0.0",

#### Affected browser(s)

Chrome

**Comment by khlieng** [comment]
So theres the same kind of issue with the first click as in #15253, but theres also some other problems that look related to #13123.

Heres a demo of it without react: https://jsfiddle.net/2aftp8rc/14/
