### ISSUE TITLE
cannot Reach Point click Event if there is DataLabel over him on LineChart

### ISSUE THREAD

**Issue by abazdarov** [highcharts/highcharts#15264]
#### Expected behaviour:
I want to reach PointEvent. If there is a way with PointLabel event to reach dataLabel behind him or to disabled DataLabel clickEvent, or any other way to reach PointEvent. 

#### Actual behaviour:
Start DataLabel point events

#### Live demo with steps to reproduce:
Just click on some points which have Datalabel Over them
![image](https://user-images.githubusercontent.com/80046563/109968634-a9a91c80-7cfb-11eb-9929-c71065d24fd4.png)
https://jsfiddle.net/j9dkynx4/8/

#### Product version
Latest highcharts version

**Comment by khlieng** [comment]
You can do this by setting `pointer-events: none` on the dataLabels: https://jsfiddle.net/fsx4n89o/

**Comment by abazdarov** [comment]
Thanks for the fast response. That was exactly what I looking for.
