### ISSUE TITLE
Column tracker

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#1526]
Example: http://jsfiddle.net/8htkj/3/
With human readable dates: http://jsfiddle.net/highcharts/8htkj/4/

Steps:
1) Zoom to day view, so close that only a few columns are visible
2) Click on column
3) Compare timestamp in alert and tooltip

As we can see, timestamps are wrong, also wrong point has selected state.

**Comment by hbhatt18** [comment]
Was this fixed under any highchart release?can you please provide details about the fix?

**Comment by pawelfus** [comment]
Hi @havardge - this should be fixed in ~2.1.0 version of Highstock (and v3.0.0 for Highcharts). Tracker for tooltip (for columns) is not used since that time. If you are able to recreate the issue, let us know - we will check this. Live demo is necessary in this case.

**Comment by hbhatt18** [comment]
I do not see it mentioned on highcharts/highstock change log: https://www.highcharts.com/blog/changelog/

If I am using older version of highchart, is there any workaround I can use to fix the issue?

Thanks,
Het

**Comment by pawelfus** [comment]
There's no particular commit that fixed this issue - that was a design change. There's no simple fix/workaround (at least I'm not aware of any) for removing trackers for columns in v2. v3.0.0 was released ~6 years ago and is no longer supported. I suggest to update Highcharts to a version that is more up to date.
