### ISSUE TITLE
Cannot sort stacked bar chart via sortkey update

### ISSUE THREAD

**Issue by jmersonuo** [highcharts/highcharts#15276]
#### Expected behaviour
Using chart options to set a new sort key value does not resort the chart

#### Actual behaviour
Nothing happens

#### Live demo with steps to reproduce

https://jsfiddle.net/jmerson/Lj1nqkd0/1/
NOTE: changing the initial sort variable at then and rerunning the fiddle displays the chart with alternate sorts.  It just won't update. Use the global variable at the top of the JS to see this.

The function sortChart (the first button) gets the current value and should switch it by assigning the new value to the series options. The title and sort _direction_ change to show that the function generally works, just not the sort value. 
The function sortChart2 (the second button) gets the current value and should switch it by assigning the new value. I added the color change, so you can see that the function generally works, just again not the sort value 

#### Product version

Highcharts JS v9.0.1 (2021-02-15)

#### Affected browser(s)
Tested in Chrome and FF

**Comment by KacperMadej** [comment]
Hi @jmersonuo 

Thank you for reporting the bug.
This is already reported here: https://github.com/highcharts/highcharts/issues/13033 (the issue there covers this more specific problem)

A workaround (based on the info in the lined issue): https://jsfiddle.net/BlackLabel/ebc248sg/1/
