### ISSUE TITLE
highstock with chart type arearange do not show points when zoom

### ISSUE THREAD

**Issue by wy1713** [highcharts/highcharts#15270]
#### Expected behaviour
points shows 

#### Actual behaviour
points are not shown, see attachment

#### Live demo with steps to reproduce
https://jsfiddle.net/m2ukwn0d/
#### Product version

latest

#### Affected browser(s)
![chart](https://user-images.githubusercontent.com/36648934/110038957-58962a00-7cf5-11eb-994d-dae3be821ee0.gif)

**Comment by khlieng** [comment]
This appears to be fixed on master (most likely by #15114): https://jsfiddle.net/o7xdycs8/

**Comment by KacperMadej** [comment]
Hi @wy1713 

Thank you for reporting the problem - it is already fixed in the next release candidate code version and will be published within the next few weeks.

Closing as resolved.
