### ISSUE TITLE
Fullscreen type is missing

### ISSUE THREAD

**Issue by jer-tx** [highcharts/highcharts#15275]
Getting an error when building my Angular project:

Error: node_modules/highcharts/modules/full-screen.d.ts:17:21 - error TS2304: Cannot find name 'Fullscreen'.

17         fullscreen: Fullscreen;

#### Product version

Highcharts 8.1.2

**Comment by KacperMadej** [comment]
Hi @jer-tx 

Thank you for reporting the problem.

Please add a way to recreate the problem - e.g. a demo in an online sandbox with the Angular app or a project to download and run (with instructions on how to install and run the project).
Please check with a newer version of Highcharts to see if the problem is still visible.

Please make sure that you are loading matching versions of core and modules - not only the release version number must match but also if you are using .src.js all files (core + modules) must do the same.

**Comment by jer-tx** [comment]
Repo that replicates this problem is available here:

https://github.com/jer-tx/highcharts_fullscreen_bug

Once dependencies are installed, run `npm run dev:ssr` to use with angular universal.

This is a base angular project with a simple Highcharts chart. Runs correctly as is, but for Angular Universal, it appears to have a problem with the missing type definition for Fullscreen in the file mentioned in the original comment.

Uncomment lines 4 and 5 in the App component (here: https://github.com/jer-tx/highcharts_fullscreen_bug/blob/main/src/app/app.component.ts ) and you will get the error listed above.

**Comment by KacperMadej** [comment]
Unable to run due to an error:

```console
npm run dev:ssr

> fullscreen@0.0.0 dev:ssr
> ng run fullscreen:serve-ssr

****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling highcharts-angular : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
- Generating browser application bundles...Error: ENOENT: no such file or directory, lstat 'C:/test/highcharts_fullscreen_bug-main/highcharts_fullscreen_bug-main/tsconfig.server.json'
    at Object.lstatSync (fs.js:1077:3)
...

**Comment by khlieng** [comment]
You currently need to import `exporting` before `full-screen`.

**Comment by pavelkaps** [comment]
The same errror, any updates?

**Comment by KacperMadej** [comment]
@pavelkaps How about https://github.com/highcharts/highcharts/issues/15275#issuecomment-882092816 ?

**Comment by adigourdi** [comment]
I have encountered this issue today, with the latest versions of angular and highcharts.

### Steps to reproduce:

1. `ng new project`
2. `cd project`
3. `npm i highcharts@latest`

Now edit `app.component.ts` with the following:

```diff
@@ -1,4 +1,7 @@
 import { Component } from '@angular/core';
+import * as Highcharts from 'highcharts';
+import highchartsFullScreen from 'highcharts/modules/full-screen';
+highchartsFullScreen(Highcharts);

 @Component({
   selector: 'app-root',
```

### Result

`ng build` returns:

```
✔ Browser application bundle generation complete.

Error: node_modules/highcharts/modules/full-screen.d.ts:17:21 - error TS2304: Cannot find name 'Fullscreen'.

17         fullscreen: Fullscreen;
                       ~~~~~~~~~~
```

### Environment

The issue occurs on
* an existing angular 12 project with highcharts 9,
* a new project on my local machine,
* and on a fresh docker container `docker run -it --rm node:16`

**Comment by karolkolodziej** [comment]
Please first import the `exporting` module as suggested previously as shown in the code snippet below: 
```
import * as Highcharts from 'highcharts';
import HC_exporting from 'highcharts/modules/exporting';
import highchartsFullScreen from 'highcharts/modules/full-screen';
HC_exporting(Highcharts);
highchartsFullScreen(Highcharts);
```

**Comment by adigourdi** [comment]
Unintuitive, but yes it works !

Just importing the module do suffice, without actually calling/using it,
I guess because it's a typing issue, and not actual code.
