### ISSUE TITLE
Tooltip jumps among all the series when dragging the point

### ISSUE THREAD

**Issue by annaiszhou** [highcharts/highcharts#15290]
#### Expected behaviour
I want to change tooltip style when I drag the point. Basically, I want shared tooltip for all the series when I'm not dragging the point. And when I'm dragging the point, only display that point on the tooltip. And after I drop the point, the tooltip should go back to the shared one.

The expected behaviour is when dragging the point, the tooltip should only show that point, and not jump among all the series.

#### Actual behaviour
When dragging the point, the tooltip will jump among all the series and go crazy like this screenshot: https://drive.google.com/file/d/1lZI7NKp16a5OED1I2Vxk7puNZZk2WQKb/view.

#### Live demo with steps to reproduce
https://jsfiddle.net/08cetkub/1/

#### Product version
Highcharts v9.0.1

#### Affected browser(s)
Chrome, Firefox, Safari

**Comment by KacperMadej** [comment]
Hi @annaiszhou 

Thank you for reporting about the problem.

`drag` event fires while dragging, so you could check if `tooltip` needs an update before calling `chart.update`.

As a **workaround**, it is possible to disable all other series from being detected for tooltip (`enableMouseTracking:false`): https://jsfiddle.net/BlackLabel/v5j8qape/

Minimal demo: https://jsfiddle.net/BlackLabel/v5j8qape/1/
Steps: drag a black series point over other points on the same x

The tooltip should stay fixed on the dragged point but is for some reason losing focus.
