### ISSUE TITLE
Top circles and labels in pie chart multipage legend are clipped

### ISSUE THREAD

**Issue by twin720** [highcharts/highcharts#15292]
#### Expected behaviour
In the pie chart multipage legend, the top circles and labels are not clipped

#### Actual behaviour
In the pie chart multipage legend, the top circles and labels are clipped at the top 

#### Live demo with steps to reproduce
https://jsfiddle.net/pd7jrwo8/1/

#### Product version
Highcharts 9.0.1

#### Affected browser(s)
Firefox browser 86.0 (64-bit)
Google Chrome 88.0.4324.192

![110607633-33019880-81ad-11eb-96f0-631e9d80b417](https://user-images.githubusercontent.com/18051646/110607851-72c88000-81ad-11eb-81a3-fcd55ce357f6.png)

**Comment by KacperMadej** [comment]
Hi @twin720 

Thank you for reporting the problem.

Minimal demo: https://jsfiddle.net/BlackLabel/Lcag2tzs/

Possible solutions/workarounds:
- decrease `symbolHeight`: https://jsfiddle.net/BlackLabel/Lcag2tzs/1/
- increase `itemMarginTop`: https://jsfiddle.net/BlackLabel/Lcag2tzs/2/
