### ISSUE TITLE
Pie chart outer dataLabels lose set width

### ISSUE THREAD

**Issue by nulle** [highcharts/highcharts#15295]
#### Expected behaviour
Pie chart labels would update their sizes and positions after the chart has been resized.

#### Actual behaviour
Pie chart outer labels lose their set widths when `setSize` is called on the chart (changing only height).
This only happens on dataLabels with `useHTML` enabled.

#### Live demo with steps to reproduce
https://jsfiddle.net/nulle/fr6m3yja/
When chart is loaded, the left-side label is shortened (working correctly). 
After calling `setSize` on the chart to update the height, the labels lose their width and overflow the chart. You can test this by pressing the "Toggle height" button once. Not even returning to the initial height (pressing the button 2nd time) fixes the label sizes. You'll have to restart the fiddle after to get them shortened again.

#### Product version
Highcharts 9.0.1

#### Affected browser(s)
Probably all. Tested in Google Chrome 88.0.4324.192 on MacOS.

**Comment by KacperMadej** [comment]
Hi @nulle 

Thank you for reporting the problem.

As a **workaround** you could set `dataLabels.style.textOverflow:'ellipsis'` - demo: https://jsfiddle.net/BlackLabel/bz6y0oLq/1/

_Internal note:_
If a `dataLabel` is too long it gets shortened, marked with a flag `shortened`.
On a redraw this resets in:

https://github.com/highcharts/highcharts/blob/2c820c0c0934cafa95a33590749864980c64a1ac/ts/Core/Series/DataLabels.ts#L1231-L1243

but `textOverflow` is now `'clip'`.

In `htmlUpdateTransform` for `width` to be set a condition must be fulfilled:

https://github.com/highcharts/highcharts/blob/2c820c0c0934cafa95a33590749864980c64a1ac/ts/Core/Renderer/HTML/HTMLElement.ts#L285-L290

If there is `textOverflow` set (like in the workaround) then using `.css()` it is applied and the next step is to call `htmlUpdateTransform` that successfully sets the `width`.

**Comment by nulle** [comment]
Hey @KacperMadej , thanks for the workaround idea. However, I still have problems making it work in `styledMode`. Overflow in css stylesheet does not seem to be taken into account. 
https://jsfiddle.net/nulle/xv8op6aj/
