### ISSUE TITLE
XAxis placed at the wrong place when adding responsive rule and enabling the navigator 

### ISSUE THREAD

**Issue by SMH110** [highcharts/highcharts#15307]
Hi,
#### Expected behaviour
X Axis placed at the top of the gantt chart and to be removed when page width exceed the responsive condition rule

#### Actual behaviour
After resizing the page, the X Axis placed at the top of the navigator.

#### Live demo with steps to reproduce
steps to reproduce:
1. Create a basic gantt with navigator and responsive rule 
2. Resize the page until you meet the responsive rule condition
3. Resize again until you don't meet the responsive rule condition

You should see something similar to this:
![image](https://user-images.githubusercontent.com/16171515/110920429-49c2ff00-8315-11eb-9284-0ac1c98079a4.png)

**Live demo:** https://jsfiddle.net/Sayed110/co3ukd40/15/

#### Product version
Highchart Gantt latest version 

#### Affected browser(s)
All

**Comment by khlieng** [comment]
This looks like it has been fixed on master: https://jsfiddle.net/251fdnme/
