### ISSUE TITLE
Strange rendering of stacked area with different step settings enabled

### ISSUE THREAD

**Issue by belakm** [highcharts/highcharts#15311]
#### Expected behaviour
Areas dont overlap and dont produce empty spaces.

#### Actual behaviour
Areas overlap and produce empty spaces.

![image](https://user-images.githubusercontent.com/13392444/110936024-894b1480-8330-11eb-8212-770a0645dea6.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/hbkscnj8/

Have two series, both have a step setting, one "left", one "right" and both are of type area with stacking.

#### Product version
Highcharts: v9.0.1

#### Affected browser(s)
Probably all, tested on Brave.

**Comment by KacperMadej** [comment]
Hi @belakm 

Thank you for reporting the problem.

Different step settings are not stacking correctly. However, could you create an image of the expected chart that will be showing correctly both the step setting and keep the area size as set in data?

Currently, the values are stacked correctly and rendering of the series with different step options is only affecting the shape of individual series. It seems to me that series with different step options are not compatible with each other so cannot be stacked.

**Comment by belakm** [comment]
Im not exactly sure what the picture for this one should look like, it looks wrong tho, doesnt it?

Maybe something like this?

![image](https://user-images.githubusercontent.com/13392444/111550913-6630c280-877f-11eb-95d9-cf4384e56257.png)

For #15310 its a lot easer:

![image](https://user-images.githubusercontent.com/13392444/111550703-f02c5b80-877e-11eb-943b-4a483f1010c6.png)
