### ISSUE TITLE
Strange rendering with stacked areas where one or multiple have step enabled

### ISSUE THREAD

**Issue by belakm** [highcharts/highcharts#15310]
#### Expected behaviour
Stacked area is rendered correctly without empty areas

#### Actual behaviour
Stacked ares are rendered with jagged empty areas where steps are:

![image](https://user-images.githubusercontent.com/13392444/110935545-da0e3d80-832f-11eb-8c28-237f2aad0675.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/beu1j4zx/

Have 2 series, one with a step and one without, both being stacked and area type.

#### Product version
Highcharts: v9.0.1

#### Affected browser(s)
Probably all browsers, tested on Brave.

**Comment by KacperMadej** [comment]
Please see https://github.com/highcharts/highcharts/issues/15311#issuecomment-800429762
Currently, this seems to be a duplicate of the other issue.

**Comment by belakm** [comment]
I would argue it isn't a duplicate as it concerns a two different types of series, one having a step option and the other not, while with #15311 both series have a step setting.

The outcome is the same though.
