### ISSUE TITLE
Vertical legend y position is incorrect

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#15328]
#### Actual behaviour
The `vertical` legend's `y` position is too high (the first item is cut).
![image](https://user-images.githubusercontent.com/23310742/111289037-0930f180-8645-11eb-859f-df20065f7274.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/z9mhncj4/

#### Product version
Highcharts 9.0.1

#### Affected browser(s)
All

**Comment by khlieng** [comment]
Sounds like #15292 🤔

**Comment by raf18seb** [comment]
Right, I should have checked first! Closing as a duplicate of #15292
