### ISSUE TITLE
rangeSelector inputs not working with 'inputEditDateFormat' on desktop Safari

### ISSUE THREAD

**Issue by diogen737** [highcharts/highcharts#15339]
#### Expected behaviour
Since desktop Safari doesn't support `type="date"` inputs users should be able to input rangeSelector dates manually from the keyboard, even when the `inputEditDateFormat` option is applied.

#### Actual behaviour
If ``inputEditDateFormat`` option is set, rangeSelector date input stops working at all.

#### Live demo with steps to reproduce
https://jsfiddle.net/aojuyvg9/

#### Product version
Highstock 9.0.1

#### Affected browser(s)
Safari MacOS

**Comment by khlieng** [comment]
Currently `inputEditDateFormat` needs to be something that works with `Date.parse` as mentioned in the docs: https://api.highcharts.com/highstock/rangeSelector.inputEditDateFormat

**Comment by diogen737** [comment]
@khlieng I take it there's no easy workaround for that?

**Comment by khlieng** [comment]
Other than maybe using some date parsing library and providing a `inputDateParser` callback, no.

**Comment by diogen737** [comment]
looks like safari has learned to work with native date inputs, closing the issue
