### ISSUE TITLE
"Invalid attribute 'x2' in config" when adding linear gradient.

### ISSUE THREAD

**Issue by k31h31** [highcharts/highcharts#15332]
#### Expected behaviour
Value of 'x2' should be accepted and linear gradient should start at the specified side.

#### Actual behaviour
Console warning "Highcharts warning: Invalid attribute 'x2' in config" gets displayed, even though it is correctly set in the defs. When we inspect into the svg-defs no 'x2' attribute can be found and the linear gradient starts at the wrong side. Note that we enabled the styled mode.

#### Live demo with steps to reproduce
https://jsfiddle.net/msuv9rxy/

Just start the provided demo and look at the console.
Please ignore the styling. Thanks

#### Product version
highcharts: 9.0.1
highcharts-angular: 2.10.0

**Comment by KacperMadej** [comment]
Hi @k31h31 

Thank you for reporting the problem.

This is already fixed on the next release candidate code version: https://jsfiddle.net/BlackLabel/4pd3bar5/

The next version release could be expected in the next few weeks.
