### ISSUE TITLE
`rangeSelector` start date input bug

### ISSUE THREAD

**Issue by diogen737** [highcharts/highcharts#15336]
Expected behaviour
Proper keyboard date input for the rangeSelector's start date

Actual behaviour
When trying to enter year 2020 in the rangeSelector start date it just resets to 0000. End date input works just fine.

Live demo with steps to reproduce
https://jsfiddle.net/4c5a8d0e/2/

Product version
Highstock 9.0.1

Affected browser(s)
Chrome 89 (Linux, MacOS)

**Comment by khlieng** [comment]
Fixed on master (#15066): https://jsfiddle.net/4wgvLkue/

**Comment by diogen737** [comment]
@khlieng sorry, is it included  in the 9.0.1 release? cause I use 9.0.1 in my project and the input still behaves weirdly.

**Comment by khlieng** [comment]
No it will be included in the next release, possibly within a few weeks.

**Comment by diogen737** [comment]
@khlieng thanks a lot
