### ISSUE TITLE
point.plotY is wrongly calculated, when the point is placed on the edge of the plot Area.

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#15353]
#### Expected behaviour
The points are calculated correctly. 

#### Actual behaviour
One of the points, that is on the edge of the plotArea, has its plotY value calculated to be negative. 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/89njm30b/

check the console, and investigate, that one of the points has a value ~ -1.4e-14

#### Product version
v9.0.1

#### Affected browser(s)
all

**Comment by raf18seb** [comment]
Internal note: after further debugging, adding `H.correctFloat` on a  `localA` variable inside the `H.Axis.prototype.translate` method helps in this case: https://jsfiddle.net/BlackLabel/jtdvfzgc/

**Comment by pawellysy** [comment]
Fixed in v10.0.0
