### ISSUE TITLE
Narrator not able to read role property with customized button 

### ISSUE THREAD

**Issue by XiaoxuHU** [highcharts/highcharts#15367]
#### Expected behaviour
I added by using `chart.renderer.button().attr()` to add role property as button for customized button in high chart. 
We expected screen read can read role property out as we configured

#### Actual behaviour
We can see role attribute added into button by inspecting HTML, but screen reader(Narrator) not read role property out
![image](https://user-images.githubusercontent.com/23129934/111849605-38589480-88cb-11eb-8dca-6497a6e82bf0.png)
#### Live demo with steps to reproduce
http://jsfiddle.net/XiaoXu_Hu/djcu7gkx/14/

#### Product version
8.2
#### Affected browser(s)
Edge

**Comment by KacperMadej** [comment]
Hi @XiaoxuHU 

Thank you for reporting the problem.

Have you tried using a newer version of Highcharts? The current version is 9.0.1.

FYI @oysteinmoseng - a11y

**Comment by oysteinmoseng** [comment]
Hi @XiaoxuHU 

Simply adding the `role="button"` might not be enough in this case. Instead the preferred method is to use the [Highcharts Accessibility Module](https://www.highcharts.com/docs/accessibility/accessibility-module), and creating a custom accessibility component. Here is a simple demo of how to accomplish this: https://jsfiddle.net/vfL6nb7x

This will also allow Narrator and other screen readers to go through the chart and interact with it, and the button can be placed in the keyboard navigation with the rest of the chart.

Note that Narrator seems to currently have an issue where it is not reading subelements in SVG in Scan mode.
