### ISSUE TITLE
mapChart doesn't update colored areas after changing joinBy

### ISSUE THREAD

**Issue by desyk** [highcharts/highcharts#15374]
#### Expected behaviour
I have a default joinBy parameter for map instantiation. For example: `joinBy: ['iso-a3', 'code']`. After retrieving new data I'm checking for actual country iso standard and update chart accordingly.
`chart.series[0].update({
  data: data,
  joinBy: ['iso-a2', 'code']
});`
I expect chart to bind country codes to a map correctly

#### Actual behaviour
Chart doesn't respect `joinBy` param in `update` method.

Actually I achieved updating of map by applying joinBy explicilty before calling for update method. Like this:
chart.series[0].joinBy = ['iso-a2', 'code'];
chart.series[0].update({data: data});

But this workaround doesn't work on jsfiddle

#### Live demo with steps to reproduce
http://jsfiddle.net/Lu4ybx2p/
Press "update series"

#### Product version
I'm using highcharts 8.2.2. (Angular)
JSFiddle has version 9.0.1

#### Affected browser(s)
Google chrome Version 89.0.4389.82 (Official Build) (64-bit)

**Comment by KacperMadej** [comment]
Hi @desyk 

Thank you for reporting the problem.

Workaround: with `allAreas: false` update `joinBy` first and `data` next - http://jsfiddle.net/BlackLabel/3hkz6mq9/

_Internal note:_
Every map point is created with bad data and after an update, the new points are under the null points.
This could be better seen with `allAreas: false` as the null points won't be obstructing the view.
http://jsfiddle.net/BlackLabel/3hkz6mq9/1/

When `joinBy` is updated data points created based on the previous `joinBy` option should be updated or destroyed.
