### ISSUE TITLE
flag.shape can't be dynamically update()'

### ISSUE THREAD

**Issue by himmxt** [highcharts/highcharts#15384]
#### Expected behaviour
flag.shape to change on update() 

#### Actual behaviour
flag.shape is unchanged

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/cm6zh231/
https://jsfiddle.net/doxtry1w/
https://www.highcharts.com/forum/viewtopic.php?f=12&t=46158&sid=dfb89f23e05530ff9f9ae9a2e5c5e6f3

#### Product version
 Highstock JS v9.0.1 (2021-02-15)

#### Affected browser(s)
Chrome / all

**Comment by KacperMadej** [comment]
Hi @himmxt 

Thank you for reporting the problem.

Minimal demo: https://jsfiddle.net/BlackLabel/cm6zh231/1/
