### ISSUE TITLE
Polar plot showing columns, when there is no data present

### ISSUE THREAD

**Issue by oddlodd** [highcharts/highcharts#15382]
#### Expected behavior
Wind Rose Polar plot should not show visual columns, when there is no data for this "wind-sector".
Columns not correctly plotted for interval 20-29 m/s looks very similar in structure to data used from Data Interval 0-9 m/s.

#### Actual behavior
When choosing Data interval 2 (in this case 20-29 m/s), the first 5 columns shows a green visualization, even though it has no data. Both the JSON object and when hovering the actual column "0" data is reported (eg: the column "N" reports 0%).

#### Live demo with steps to reproduce
https://jsfiddle.net/ham28y1p/2/

#### Product version
 Version? I use the CDN, so the latest version?
![WindRose2](https://user-images.githubusercontent.com/61726932/112157071-20dd1c80-8be7-11eb-9c0d-be8c67d6067b.PNG)

#### Affected browser(s)
Only tested with chrome.
![WindRose](https://user-images.githubusercontent.com/61726932/112156666-bfb54900-8be6-11eb-9f39-e546eabd2996.PNG)

**Comment by KacperMadej** [comment]
Hi @oddlodd 

Thank you for reporting the problem.
Demo with the fix for testing: https://jsfiddle.net/BlackLabel/dL9hsfwo/

-------------
> Version? I use the CDN, so the latest version?

Yes, the latest (v9.0.1). The version is in the top lines of the files and also in `Highcharts.version`.

**Comment by oddlodd** [comment]
Hi thanks. The test Fiddle is how its expected to work :) 
@KacperMadej 
Not beeing familiar with the process and configuration here:
How do i implement this fix into my code? I need to do something? Or do i wait for next release? -If so, how do i track the relase.

**Comment by khlieng** [comment]
Heres a plugin you can use while waiting for a release: https://jsfiddle.net/ewto384x/, you can click watch to get a github notification when releases happen.
