### ISSUE TITLE
Tap and hold gesture triggers highlighting on highcharts on iOS devices.

### ISSUE THREAD

**Issue by bysz71** [highcharts/highcharts#15386]
#### Expected behaviour
Callbacks bind to "press (tap and hold)" gesture(hammer.js) on an legend item will work properly.

#### Actual behaviour
Tap and hold on the highcharts on an iOS device will cause certain part of the chart or the entire chart get highlighted. It's conflicting with the function we bind to the legend items with a "press (tap and hold)" gesture provided by hammer.js.
This issue does not replicate on an older version of Highcharts (6.1.4).
Modules being used are Highcharts.js, highcharts-more.js highcharts-3d.js, funnel.js solid-gauge.js, grouped-category.js.

#### Live demo with steps to reproduce
any highcharts demo on your website will do, you could see the highlighting after tap and hold.

#### Product version
Highcharts 9.01

#### Affected browser(s)
wkwebview, iOS safari.

**Comment by KacperMadej** [comment]
Hi @bysz71 

Thank you for reporting the problem.

Please add info about the used iOS and Safari versions.

Is there any reason for mentioning hammer.js? From your description, the issue is not related to it because it is possible to be recreated in any demo.

**Comment by KacperMadej** [comment]
_Internal note:_
Recreated 3 times in the below video. Touch on: a legend title (1,2) and a series (3).

https://user-images.githubusercontent.com/8960408/112613543-82d49680-8e20-11eb-8145-e668ac0faf80.MP4

**Comment by bysz71** [comment]
btw could use e.preventDefault to workaround it but not perfect solution
