### ISSUE TITLE
IndicatorRequired mixin isn't working in v9

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#15409]
#### Expected behaviour
When running an indicator that requires another indicator module to be loaded (for example the dema indicator except `dema.js` also requires `ema.js` to be loaded) without the required module, the `console.log()` with an error description should be thrown into the console.

#### Actual behaviour
No description in the console. Instead, other errors are displayed.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/9msbrceq/

#### Product version
Since v9.0.0

**Comment by pawelfus** [comment]
It's not a bug/regression in the `indicatorRequired` mixin. It works the same way it used to, but it's a problem related to tree shaking and modularizing series dependencies (under the hood, every technical indicator is just a series). Once similar issues will be resolved (e.g. sankey and dependency wheel series) we will be able to pick this up.

Status: On hold

**Comment by bre1470** [comment]
It is impossible to combine this with tree shaking. I tried several approaches, but it depends on the deprecated seriesType factory when it comes to options and constructor.

If we move the logic out of init right before the class, we could at least trigger the error message right before it fails. Opinions?

**Comment by bre1470** [comment]
@raf18seb @pawelfus Could you take a look?

**Comment by pawelfus** [comment]
> If we move the logic out of init right before the class, we could at least trigger the error message right before it fails. Opinions?

The idea to implement this in `init` was to throw an error and prevent running all the calculations (which could throw a lot of other errors, which would be really messy and easy to miss the most important error). I think we can safely move this out of the `init` function, as you suggest 👍 If we could also somehow prevent defining the indicator class, that would be great. So in the end, if we would end up with only two errors (missing dependency and error-17 (missing series)).

Perhaps we should resign from `indicatorRequired` mixin? Instead, let's create a mechanism (or refactor the existing one) that does the check for any module? Demo for the Sankey and Dependency-wheel: https://jsfiddle.net/BlackLabel/fmdLj4cs/1/ (missing Sankey dependency)

**Comment by raf18seb** [comment]
There's still `Uncaught TypeError: Cannot read property 'prototype' of undefined` error before error-17. If this is not a concern for us, maybe we could reuse the logic from error-17?

**Comment by bre1470** [comment]
The prototype error comes from the transpiled code, that TypeScript produces for the class inheritance.

**Comment by bre1470** [comment]
> Perhaps we should resign from `indicatorRequired` mixin? Instead, let's create a mechanism (or refactor the existing one) that does the check for any module?

I am not sure if that is possible. What you try to check would be already checked by the static ESM system. Thinking about this now, I wonder if indicators should be rewritten as compositions on top of the parent series. Then you can simply check for the indicator properties to figure out, which compositions are missing, and throw a helpful error.
```
DEMA.attachTo(series)
series.indicators.dema // typeof DEMA
series.indicators.ema // undefined
```

**Comment by pawelfus** [comment]
> Thinking about this now, I wonder if indicators should be rewritten as compositions on top of the parent series. 

Hmm... does it make sense for Sankey and Dependency wheel? A technical indicator series is basically any other series. 

```
DependencyWheel.attachTo(series)
series.???.depencencywheel
```
---
In fact, we have two "types" of inheritance in indicators:

a) Stochastic -> SlowStochastic. SlowStochastic uses the whole logic (rendering and math) and adds some extra logic (smoothens the data)
b) EMA -> DEMA. In fact, DEMA could be created from SMA (or an abstract IndicatorSeries class, if we had one ;) ). All that is necessary for DEMA, is the algorithm from EMA.

Just to be on the same page: Technical indicators used to inform users (with a clear message) when they didn't load the required dependency. Now then have a vague error

**Comment by pawelfus** [comment]
Since v9, architecture has changed (related to tree-shaking), and the `IndicatorRequired` mixin will no longer work. That means we will solve the issue this way:
- [ ] - move EMA to `indicators.js` module (already many other technical indicators is based on EMA) -> decrease the number of potential issues
- [ ] - add all missing `"Requires ..."` in [api.highcharts.com](https://api.highcharts.com), list of indicators which require this info (like any other series type):
  - [ ] - TRIX (requires TEMA module)
  - [ ] - SlowStochastic (requires Stochastic module)
  - [ ] - NATR (requires ATR module)
  - [ ] - LinearRegressionSlope (requires LinearRegression module)
  - [ ] - LinearRegressionIntercepts (requires LinearRegression module)
  - [ ] - LinearRegressionAngle (requires LinearRegression module)
  - [ ] - AroonOscillator (requires Aroon module)
- [ ] - remove `IndicatorRequired` mixin
- [ ] - update [v9.0.0 changelog's "Upgrade notes"](https://www.highcharts.com/blog/changelog/#highcharts-stock-v9.0.0) with this info
