### ISSUE TITLE
funnel3d.js invalid attribute 'tableValues' in config

### ISSUE THREAD

**Issue by wonderiuy** [highcharts/highcharts#15401]
#### Expected behaviour
No warning in browser console

#### Actual behaviour
Browser (firefox) console report this warning:
Highcharts warning: Invalid attribute 'tableValues' in config
probably coming from funnel3d.js

#### Live demo with steps to reproduce
https://jsfiddle.net/hy97qjvt/

#### Product version
Highcharts 9.0.1

#### Affected browser(s)
Firefox

**Comment by KacperMadej** [comment]
Thank you for reporting the bug.

The attribute [`tableValues`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/tableValues) should be allowed - added to the default list.

As a **workaround**, you could add the missing attribute to the allowed list in AST.
`Highcharts.AST.allowedAttributes.push('tableValues');`
Demo: https://jsfiddle.net/BlackLabel/qmbch64e/2/
