### ISSUE TITLE
Keyboard navigation freezes after clicking a value in Heatmap

### ISSUE THREAD

**Issue by franklinefrancis** [highcharts/highcharts#15413]
#### Expected behaviour
Keyboard navigation across data points of Heatmap works without any glitches

#### Actual behaviour
After using keyboard to navigate a few data points of Heatmap and then clicking on one of the data points causes keyboard navigation not to work anymore.

![Heatmap Keyboard Navigation](https://user-images.githubusercontent.com/1227574/112712344-e7f9bc00-8ef4-11eb-9460-aebceeee2ccf.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/franklinefrancis/upd0bv3w/

#### Product version
8.2.0

#### Affected browser(s)
Chrome, Firefox

**Comment by KacperMadej** [comment]
Thank you for reporting the bug.

a11y - fyi: @oysteinmoseng  

_Internal note:_
This is also visible when a point is focused via a11y module selection and a mouse hover doesn't hide the selection.
