### ISSUE TITLE
Api callback help

### ISSUE THREAD

**Issue by lo-ve-ly** [highcharts/highcharts#15422]
Hello I am loving you charts - they are included with the wpdatatables. and work fabulously together.
I have a very short question if you can help me correct the following callback which is refusing to work - I only need to remove the markers from the line charts:

```
<script type="text/javascript">
jQuery(window).on('load',function(){
    if( typeof wpDataChartsCallbacks == 'undefined' ){ wpDataChartsCallbacks = {}; }
        wpDataChartsCallbacks[16] = function(obj){
                obj.options.plotOptions.series.marker= {enabled= false};
            }
});
</script>
```

or it should be?

```
<script type="text/javascript">
jQuery(window).on('load',function(){
    if( typeof wpDataChartsCallbacks == 'undefined' ){ wpDataChartsCallbacks = {}; }
        wpDataChartsCallbacks[16] = function(obj){
                obj.options.plotOptions.series.marker.enabled= false};
            }
});
</script>

```

can you help correct the syntax?

**Comment by lo-ve-ly** [comment]
can someone please help? I am sure there is a tiny error lurking somewhere visible to the pros like you at once!)

**Comment by khlieng** [comment]
`obj.options.plotOptions.series.marker = { enabled: false };`

Or if series is not defined:

`obj.options.plotOptions.series = { marker: { enabled: false } };`

**Comment by lo-ve-ly** [comment]
fantastic - it worked - thanks a lot - hicharts-pro!)
