### ISSUE TITLE
Color axis not updating as expected

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#15436]
#### Expected behaviour
https://jsfiddle.net/9sbq2wLj/ - On directly loading chart

#### Actual behaviour
https://jsfiddle.net/b6tvk842/1/ - On updating the config

#### Live demo with steps to reproduce
Added above

#### Product version
Highcharts 9

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @govinda18 

Thank you for reporting the bug.

As a workaround for your case (no legend before the update), it is possible to update with [`oneToOne`](https://api.highcharts.com/class-reference/Highcharts.Chart#update) set as `true` - https://jsfiddle.net/BlackLabel/cy48bx5e/

Minimal demos with short descriptions. After update with `oneToOne` as:
- `false` (default) - `colorAxis` update does nothing. https://jsfiddle.net/BlackLabel/yx6kp07c/1/
- `true` - `colorAxis` overlaps previous legend elements. https://jsfiddle.net/BlackLabel/yx6kp07c/

**Comment by govinda18** [comment]
Thanks for the workaround @KacperMadej
