### ISSUE TITLE
The phenomenon that the series is not drawn or is cut off when using highstock

### ISSUE THREAD

**Issue by edgar-km** [highcharts/highcharts#15435]
#### Actual behaviour
Series and y-axis are dynamically added to express various metrics.
![스크린샷 2021-04-05 오전 10 57 41](https://user-images.githubusercontent.com/81945541/113536454-238d3800-9611-11eb-8e65-b2ddcc67e1bf.png)
![스크린샷 2021-04-05 오전 11 33 59](https://user-images.githubusercontent.com/81945541/113536462-26882880-9611-11eb-9728-9da07d1758e4.png)
The end of the series is not drawn like the attached image

I need help. Help

#### Product version
v9.0.1

#### Affected browser(s)
ALL

**Comment by KacperMadej** [comment]
Hi @edgar-km 

Please add a live demo for the problem.

**Comment by edgar-km** [comment]
Hi @KacperMadej 

Too hard to do a live demo
I'll show you a video before the live demo.

https://user-images.githubusercontent.com/81945541/113796573-7dfdd400-978a-11eb-9af0-2556550d906d.mp4

**Comment by edgar-km** [comment]
re Hi @KacperMadej 
I prepared a live demo very hard.
Press the buttons randomly.(A~J2)
If you try to turn on/off consecutively, you will get a bug

Live Demo
https://codesandbox.io/s/eloquent-grothendieck-qty2l?file=/src/components/Chart.vue
(I want you to know that the actual code is more complicated than this.)

Live Demo Capture
![스크린샷 2021-04-07 오후 12 06 20](https://user-images.githubusercontent.com/81945541/113809348-de007480-97a2-11eb-94a3-b9b4a9bfdd84.png)

**Comment by KacperMadej** [comment]
Thank you @edgar-km for the demo.

I have managed to get a stable minimal demo: https://jsfiddle.net/BlackLabel/Lx9j8m6n/2/

Shows only for Highcharts Stock (or like in the original demo: HC + Stock module).
A resize resolves the problem as the plot is correctly clipped after it.

**Comment by edgar-km** [comment]
Hi @KacperMadej 
I watched the demo, but I think the same issue occurs.
(demo captured.)
![스크린샷 2021-04-12 오전 9 44 11](https://user-images.githubusercontent.com/81945541/114327392-d6aae380-9b73-11eb-9234-78dc0f15c160.png)

We already know that after a bug occurs, you have to resize the browser to draw it well.
I'm not sure what to refer to in the given demo..
It seems like a phenomenon that only appears when using the stock module.
Can't you fix the issue?

There are two things I want.
It would be appreciated if you could modify the stock module or write the flag series on highchart.
I need help. Please help me.

**Comment by wchmiel** [comment]
It seems the bug is a regression after `v8.2.2`, see: https://jsfiddle.net/BlackLabel/nxk3ac6p/.

**Comment by KacperMadej** [comment]
> I watched the demo, but I think the same issue occurs.

Yes, this is a stable minimal demo - showing the problem every time with minimal code.

**Comment by edgar-km** [comment]
Thank you very very very much!!
