### ISSUE TITLE
Can't load es-modules version of highcharts-more due to CORS

### ISSUE THREAD

**Issue by CharlieEriksen** [highcharts/highcharts#15437]
The file `https://code.highcharts.com/es-modules/masters/highcharts-more.src.js` is not setting the appropriate CORS headers to allow cross-origin loading like `https://code.highcharts.com/es-modules/masters/highcharts.src.js` is. This prevents the `highcharts-more.js` file from being loaded as demonstrated in the documentation.

#### Expected behaviour
The [second example](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/esm/async-await/) in the [documentation for how to load es modules should work](https://github.com/highcharts/highcharts#load-highcharts-from-the-cdn-as-ecmascript-modules)

#### Actual behaviour
[The example](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/esm/async-await/) doesn't work due to the file not allowing CORS. 

```
Access to script at 'https://code.highcharts.com/es-modules/masters/highcharts-more.src.js' from origin 'https://fiddle.jshell.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Failed to load resource: net::ERR_FAILED

Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://code.highcharts.com/es-modules/masters/highcharts-more.src.js
```

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/esm/async-await/

#### Product version
Latest

#### Affected browser(s)
All browsers.

**Comment by KacperMadej** [comment]
Hi @CharlieEriksen 

Works fine for me now (Win10/Chrome, Win10/Edge).
Please try again with cleared or blocked browser cache.

**Comment by CharlieEriksen** [comment]
It does indeed seem to work again!
