### ISSUE TITLE
When series are hidden, the plotBand is still visible as a thin line

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#15434]
#### Expected behaviour
When you hide all of the series, the plotbands should be invisible.

#### Actual behaviour
The plotbands remain visible as a thin line and translate to the beginning of the axis.

#### Live demo with steps to reproduce

Click on the legend to hide the series, and notice, that the plotBand remain visible with the width of 0.5 px at the beginning of the axis. 
https://jsfiddle.net/BlackLabel/Lqxf9e17/

#### Possible Workaround
https://jsfiddle.net/BlackLabel/e4tkdug2/

#### Product version
v9.0.1

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Broken since v8.0.0: https://jsfiddle.net/BlackLabel/Lqxf9e17/1/ - bisect needed
