### ISSUE TITLE
Removing zone from boosted graph turns curve black

### ISSUE THREAD

**Issue by tzaitoun** [highcharts/highcharts#15432]
#### Expected behaviour
Calling
```
chart.update({
  plotOptions: {
    series: {
      zones: []
    }
  }
})
```
should restore boosted graph to original color.

#### Actual behaviour
The curve becomes black when calling the above method on chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/c3pzuef5/

In this demo, click the remove zone button so that it calls the chart.update mentioned previously and the curve will turn black.

#### Product version
v9.0.1

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @tzaitoun 

Thank you for reporting the problem.

Zones are not officially supported in boost module - https://www.highcharts.com/docs/advanced-chart-features/boost-module

Minimal demo: https://jsfiddle.net/BlackLabel/f5vw938t/
`series.zones:[]` renders wrongly in a boosted chart.

Workaround: use an infinite zone with the desired color - demo: https://jsfiddle.net/BlackLabel/f5vw938t/1/

**Comment by khlieng** [comment]
@KacperMadej #10439
