### ISSUE TITLE
Docs- update custom technical indicators documentation

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#15443]
#### Description
Update the [documentation](https://www.highcharts.com/docs/stock/custom-technical-indicators) (text, demos, references) with the new method called `registerSeriesType` instead of deprecated `seriesType`.

**Comment by pawelfus** [comment]
*Internal note:*
When updating to `registerSeriesType`, please leave a note (and current jsfiddle demo) on how to use it before vX (where X is the first version that implements `registerSeriesType`).

**Comment by karolkolodziej** [comment]
We've decided to don't proceed with that issue for now.
The existing code and documentation of the `seriesType` method work well and the `registerSeriesType` might introduce unnecessary confusion especially for the IE users (`class` is not supported there).

Demo with class: https://jsfiddle.net/BlackLabel/s83ptrnb/
Demo with code after compiling: https://jsfiddle.net/BlackLabel/zc3eq0t6/
