### ISSUE TITLE
Unicode characters not rendered correctly in title and data label if passed as HTML entity

### ISSUE THREAD

**Issue by jasonclg** [highcharts/highcharts#15450]
#### Expected behaviour
Unicode characters such as this https://www.compart.com/en/unicode/U+1F847
should be rendered correctly in chart's title and data label

#### Actual behaviour
HTML entity was rendered directly

#### Live demo with steps to reproduce
https://jsfiddle.net/mtLfwykj/

#### Product version
Highcharts 8.2.0

**Comment by KacperMadej** [comment]
Hi @jasonclg 

[`useHTML`](https://api.highcharts.com/highcharts/title.useHTML) needs to be set to `true` - demo: https://jsfiddle.net/BlackLabel/2edakm0j/
