### ISSUE TITLE
Gantt navigator is reset when data is updated

### ISSUE THREAD

**Issue by DaveGitUser** [highcharts/highcharts#15452]
#### Expected behaviour
No moving of the navigator selector when data is updated.

#### Actual behaviour
Navigator selector is moved to the start (left) when it's moved somewhere inside the first half of the navigator space and data is updated. When it is moved somewhere inside right half of the navigator space, it is correct (no moving anywhere after data is updated)

#### Live demo with steps to reproduce
https://jsfiddle.net/rx3ewmuL/

1) When chart is displayed, change size of the navigator "zoom range" and move it somewhere between very begining (left) and the middle
2) Wait for setInterval() countdown trigger, which will run a function that will update data in gantt
3) Navigator "zoom range" is "reset" (moved) to the very begining (left)
4) When you move it somewhere between the middle and the end (right), it is OK (no moving)

#### Product version
Highcharts Gantt 9.0.1

#### Affected browser(s)
Google Chrome

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

Minimal demo in a simple Stock chart: https://jsfiddle.net/BlackLabel/tm24fgoh/
(Looped data update and simulated zoom - data update for unsorted data (like scatter or gantt's default series type gantt) changes axis range).
No problem for sorted data: https://jsfiddle.net/BlackLabel/tm24fgoh/1/

**Comment by shamshadkhan** [comment]
Is there any update on this bug?

**Comment by karolkolodziej** [comment]
Hi @shamshadkhan for now nothing has changed. 
There is no ETA for this issue fix.
