### ISSUE TITLE
Display stack label used in grouped and stacked chart

### ISSUE THREAD

**Issue by builderModel** [highcharts/highcharts#15462]
![stack](https://user-images.githubusercontent.com/82135910/113973827-8de4e900-985a-11eb-94a1-6371df77c9a1.png)
Require a feature to display the stack label below the chart

**Comment by KacperMadej** [comment]
Hi @builderModel 

This is doable with the current API.
Relevenat `stackLabels` options: 
```js
	verticalAlign: 'bottom',
	y: 25,
	overflow: 'allow',
	crop: false
```
Demo: https://jsfiddle.net/BlackLabel/L5x6obvw/

**Comment by pawellysy** [comment]
Closing as it it already implemented
