### ISSUE TITLE
Getting error- Cannot read property length of undefined.

### ISSUE THREAD

**Issue by VadirajSarvothama** [highcharts/highcharts#15467]
Hi I am new to highcharts , I am having 12k data points , Points consist of 2D arrays [[1,2],[2,3]]..etc . When I tried plotting more than 5k elements I'm getting error like "Cannot read property length of undefined" in Series.prototype.translate function of highchart.src.js(PFA of attachment image)  

#### Expected behaviour
It should plot chart with any number of elements

#### Actual behaviour
Getting error if 2D array consists of more than 5k elements

#### Affected browser(s)
![image](https://user-images.githubusercontent.com/50216431/114014830-a8cd5280-9886-11eb-8107-4ee83b06bf21.png)

**Comment by KacperMadej** [comment]
Hi @VadirajSarvothama 

A live demo would help us recreate your problem.

Here is a working 12k point chart (with data in the described format), so you could edit the below demo to show you the issue or contact technical support for assistance (e.g. if you are not sure if a problem is a bug, need more help with Highcharts).
https://jsfiddle.net/BlackLabel/msdr1ohx/5/

For technical support please see https://www.highcharts.com/blog/support/
