### ISSUE TITLE
Legend text bellow symbol

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#15463]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/6030335/113981662-959f9000-9850-11eb-85a5-d5bc11bb5a6a.png)

#### Actual behaviour

![image](https://user-images.githubusercontent.com/6030335/113981364-40637e80-9850-11eb-86c7-a429f7f1f902.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/ftksh8eg/

#### Product version
Highcharts 9.0.1

#### Affected browser(s)
Google Chrome  89.0.4389.114

**Comment by khlieng** [comment]
Workaround (https://jsfiddle.net/px6gtfzq/): Set `symbolWidth` aswell.
