### ISSUE TITLE
Highchart not respecting flexboxes width

### ISSUE THREAD

**Issue by tusharchutani** [highcharts/highcharts#15473]
#### Expected behaviour
I have a flexboxes who's flex width is controlled by a button. I want to expand and contract the div based on the state of the component. One of the component obviously has a Highchart chart. From my research I am suppose to do a chart.reflow in order to reset the width. I noticed that if the chart is initially set to a container with small width and then we expand the container width the chart will expand. However if we make the make the width of the container smaller the chart will not contract. 

#### Actual behaviour
The chart should contract with the width of the container

#### Live demo with steps to reproduce
https://codesandbox.io/s/line-chart-x44my?file=/src/App.js

#### Product version
Highchart 3.0

**Comment by khlieng** [comment]
This happens because `min-width` defaults to `auto` inside flex containers, you can fix this by setting it to `0`: https://codesandbox.io/s/line-chart-forked-temqp

**Comment by KacperMadej** [comment]
Closing as answered.
For technical support see https://www.highcharts.com/blog/support/
