### ISSUE TITLE
Ui issue on  y axis tittle when axis tittle orientation is set as diagonal

### ISSUE THREAD

**Issue by crohit7** [highcharts/highcharts#15476]
#### Expected behaviour
title should not overlap on labels

#### Actual behaviour
title gets overlap on labels

#### Live demo with steps to reproduce
https://jsfiddle.net/o4sbnq1a/

#### Product version
9.0.1

**Comment by KacperMadej** [comment]
Hi @crohit7 

Thank you for reporting the problem.

**Workaround**: set `textAnchor:'end'` in `style` options for the `yAxis.title` - https://jsfiddle.net/BlackLabel/kavg73mw/

**Comment by crohit7** [comment]
Thanks for workaround @KacperMadej
