### ISSUE TITLE
Gantt - xAxis overflow settings not working as expeced

### ISSUE THREAD

**Issue by makranczizoltan** [highcharts/highcharts#15487]
#### Expected behaviour
The setting https://api.highcharts.com/gantt/xAxis.labels.overflow , when set to "allow", should let the text overflow in a cell on the xAxis. (and preferably, offer ellipsis support). 

#### Actual behaviour
If the text in the axis label overflows, regardless of xAxis.labels.overflow's value, it isn't visible.

#### Live demo with steps to reproduce
https://jsfiddle.net/w9thvcan/1/

Post on the HC forum: https://www.highcharts.com/forum/viewtopic.php?f=19&t=46265

#### Product version
Highcharts Gantt, v9.0.1

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Thank you for reporting the bug.
