### ISSUE TITLE
Highcharts .NET Pie Chart - How to add hidden data points to Pie Chart

### ISSUE THREAD

**Issue by kgopdev** [highcharts/highcharts#15499]
Hi,
I need to add invisible data points to a pie chart. In Highcharts JS setting the _visible_ property to _false_ on the data point hides the data point. 
[Highcharts JS example - Pie chart with hidden data point](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/pie-ignorehiddenpoint/)

How I can achieve the same effect with the Highcharts .NET wrapper since there is no _visible_ property for _PieSeriesData_
Current code -
```
var dataPoint = new PieSeriesData
{ 
   Y = 12,
};
```
I have contacted support. The support engineer informed me that it's a bug and advised me to open an issue on GitHub.
Thanks!

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

fyi @brofixo

**Comment by kgopdev** [comment]
Hi,
Would greatly appreciate if there is any update as to when this will be resolved. It's blocking us from releasing a new charting feature in our application. Thanks!

**Comment by brofixo** [comment]
There is no `visible` property in https://api.highcharts.com/highcharts/series.pie.data so there is nothing to fix on the .NET wrapper side. 
If there is a need to add additional property to an object then there is a `Custom Fields` property designed for that purpose.
