### ISSUE TITLE
Range selector button adaptive width

### ISSUE THREAD

**Issue by diogen737** [highcharts/highcharts#15491]
#### Expected behaviour
Range selector buttons adjust their size depending on the content.

#### Actual behaviour
When the text of the button is long enough it just overflows beyond buttons boundaries instead of expanding the container.

#### Live demo with steps to reproduce
https://jsfiddle.net/j8xv6u2d/2/ (see 'Seit Vergleich' button)

#### Product version
Highstock 9.0.1

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @diogen737 

Thank you for reporting the problem.

It is possible to set `width` in `buttonTheme` to `'auto'`, so the width will be adjusted for every button to fit the text inside.
Demo: https://jsfiddle.net/BlackLabel/pg8Lqez2/

_Internal note:_
This functionality is not documented and works the same if `width` is set to any not-empty string (demo: https://jsfiddle.net/BlackLabel/pg8Lqez2/1/)

**Comment by diogen737** [comment]
@KacperMadej thanks for the reply. indeed 'auto' solves the problem. but there are two more regarding buttons style:
https://jsfiddle.net/xu4L1ema/
1. if I change button's font size the text is no longer vertically aligned
2. with width 'auto' left and right paddings are too small but I can't change them without changing top/bottom paddings as well

any suggestions?

**Comment by KacperMadej** [comment]
1. Vertical alignment could be adjusted using `height` - https://jsfiddle.net/BlackLabel/vdqhg70c/  - this problem looks like a bug.
2. `height` could help here too, but text won't be centered vertically anymore - no solution here, this is not resolvable via API, as there is no support for array input for the `padding` option that would allow setting different padding on different sides.

**Comment by diogen737** [comment]
@KacperMadej I believe `height` solves all of my problems, thanks a lot

**Comment by khlieng** [comment]
There is `paddingLeft` and `paddingRight`, `paddingRight` doesnt work at all currently because its filtered by the AST and `paddingLeft` is a bit wonky.
