### ISSUE TITLE
change chart type after drilldown

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#15496]
#### Expected behaviour

Changing the chart type on the nested series should work properly (without re-rendering an additional graph) and the back-up button shouldn't trigger any errors. 

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/c5etjdL2/

Steps to reproduce:

1. click on the first column, 
2. change the chart type to pie - click on the pie button under the plot,
3. click on one of the points to drilldown to the third level - a new graph is rendered,
4. click drill-up button - the error occurs in the console

#### Product version

Highcharts JS v9.0.1 (2021-02-15)

**Comment by vegaelce** [comment]
We have the same problem when changing chart rendering (with different inverted value) during drilldown/drillup.

**Live demo** 

This drilldown/drillup works fine (chart rendering are : level 1 = **column** - level 2 = **bar** - level 3 = **line**) : https://jsfiddle.net/vegaelce/1xt9kzwu/

But the same code changing only the order of rendereing type charts (level 1 = **bar** - level 2 = **column** - level 3 = **line**) is not working (default in the third level and drillup from it) : https://jsfiddle.net/vegaelce/6o17w9nL/

**Product version**

Highcharts JS v9.3.1

Can you give me a workaround to fix that please ?
Thanks

**Comment by EdmundoDelGusto** [comment]
Got the same issue.
Here is my highcharts-vue implementation:

https://jsfiddle.net/EdmundoDelGusto/hfy547d2/7/
