### ISSUE TITLE
Highcharts .NET version 9.0.1.1 - How to set the ScatterSeriesStatesHoverHalo size

### ISSUE THREAD

**Issue by kgopdev** [highcharts/highcharts#15498]
Hi, 
I've upgraded the Highcharts .NET Nuget version from 8.1.1.1 to 9.0.1.1 
In the previous version the _Size_ property of _ScatterSeriesStatesHoverHalo_ was type _double_. Now it is type _Hashtable_. I am unable to get the size to work with the new type. Please advise as to how I can set the size.
[Highsoft.Web.Mvc.Charts.ScatterSeriesStatesHoverHalo Class Reference](https://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_scatter_series_states_hover_halo.html)

New code -
```
States = new ScatterSeriesStates {
 Hover = new ScatterSeriesStatesHover {
  Enabled = true,
  Halo = new ScatterSeriesStatesHoverHalo { Size = new Hashtable { { "size", 20 } } }
 }
}
```
Old code -
```
States = new ScatterSeriesStates {
 Hover = new ScatterSeriesStatesHover {
  Enabled = true,
  Halo = new ScatterSeriesStatesHoverHalo { Size = 20 }
 }
}
```
I have contacted support. The support engineer informed me that it's a bug and advised me to open an issue on GitHub.
Thanks!

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

fyi @brofixo

**Comment by kgopdev** [comment]
Hi,
Would greatly appreciate if there is any update as to when this will be resolved. It's blocking us from releasing a new charting feature in our application. Thanks!
