### ISSUE TITLE
Issue with Series.addPoint not shifting using prototype adapter

### ISSUE THREAD

**Issue by jefflub** [highcharts/highcharts#155]
If you have two series, and are trying to addPoint with a shift to both of them, they eventually stop shifting and just draw the points to the right edge of the graph.  Having the addPoint redraw parameter false and using Chart.redraw sometimes works, but will also eventually fail.

See http://jsfiddle.net/TZaV2/1/

Either click the "Doesn't work" button, or click "Works" several times in quick succession and you should see the issue.  Repro's on both Firefox and Chrome.

**Comment by oysteinmoseng** [comment]
Seems to work in current code, even if animation is a bit weird.
