### ISSUE TITLE
<u> getting stripped for useHTML: true

### ISSUE THREAD

**Issue by kakarlus** [highcharts/highcharts#15509]
#### desc
i assume it's getting stripped because the `<u>` tag is deprecated? 
but it's back and not deprecated as per https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u

#### Expected behaviour
`<u>` tag should render the `<u>` tag

#### Actual behaviour
`<u>` tag getting stripped

#### Live demo with steps to reproduce
https://jsfiddle.net/yhtz0ma4/

1. set title useHTML: true
2. set text to '<u>some text</u>'

#### Product version
9.0.0

#### Affected browser(s)
chrome

**Comment by KacperMadej** [comment]
Hi @kakarlus 

Thank you for reporting the problem.

`<u>` tag is not included in the default list of allowed tags filtered for security.
Let's keep the issue open until `u` tag will be added to the default list.

As a workaround, you could use a `span` tag styled with "text-decoration: underline;`.
Demo: https://jsfiddle.net/BlackLabel/w23o6t4a/

Another solution is to [extend the list](https://api.highcharts.com/class-reference/Highcharts.AST#.allowedTags) of allowed HTML tags - add `u`.
Demo: https://jsfiddle.net/BlackLabel/w23o6t4a/1/

**Comment by kakarlus** [comment]
Hello @KacperMadej ,

Are there security risks for the second solution? 

Regards,
Carlos

**Comment by TorsteinHonsi** [comment]
@kakarlus 

> Are there security risks for the second solution?

No, that would be safe
