### ISSUE TITLE
Gauge, error on needle and label when updating chart subtitle

### ISSUE THREAD

**Issue by estemendoza** [highcharts/highcharts#1550]
In Gauge chart, if you change the chart's subtitle when updating needle point, the needle and the label moves a little bit. Tested on FF 18.0.2 and IE 9

On the fiddle below, wait until refreshes 2 o 3 times.

http://jsfiddle.net/v8TE6/

**Comment by KacperMadej** [comment]
Working correctly since version 3.0.10 - http://jsfiddle.net/v8TE6/4/
and in the current (6.0.1) - http://jsfiddle.net/v8TE6/5/
