### ISSUE TITLE
No graph shown on same y-values and glow effect

### ISSUE THREAD

**Issue by k31h31** [highcharts/highcharts#15518]
#### Expected behaviour
When creating a glow for a line-series it is expected that, when there is data to display, the line graph is visible with a glowing effect.

#### Actual behaviour
When creating this glow effect the graph is invisible when there are two points with the same y value.
Please note that we are using styled mode.

#### Live demo with steps to reproduce
https://jsfiddle.net/jo93pa60/

In this fiddle you can see two series:
- One with 2 datapoints that have the same y-value. No glowy-line is visible between those points. When we remove the glow effect (line 31 in css), the graph appears. If you change one y-value to be different to the other, the graph appears too.
- One with 2 datapoints that have different y-values. Here a glowy-line can be seen.

#### Product version
Highcharts: 9.0.1
Highcharts-Angular: 2.10.0

Thanks in advance!

**Comment by KacperMadej** [comment]
Hi @k31h31 

Thank you for reporting the problem.

This is an SVG limitation as explained here: https://stackoverflow.com/questions/36284828/svg-adding-shadow-filter-makes-straight-line-invisible

This could be resolved by using `scatter` series type with some [`jitter`](https://api.highcharts.com/highcharts/series.scatter.jitter)
Demo: https://jsfiddle.net/BlackLabel/3k6bn8pu/
