### ISSUE TITLE
Changing axisOffset in afterGetOffset yAxis event handler causes highcharts failure

### ISSUE THREAD

**Issue by skrtheboss** [highcharts/highcharts#15519]
#### Expected behaviour
Should not fail if `axisOffset` is adjusted.

#### Actual behaviour
Fail if `axisOffset` is adjusted.

I have done some investiagtion, and i think the problem has been caused by [this](https://github.com/highcharts/highcharts/pull/13459/commits/88d982e76bd17e2b659bb60c896e13c83be03ba0) refactor.
The check before calling `beforeSetTickPositions` has changed to `this.isRadial` instead of `this.beforeSetTickPositions`. This check does not always work, because the `beforeSetTickPositions` is only added to [visible](https://github.com/highcharts/highcharts/blob/12540607569b99467d91c447e23eb1d3b869e16d/ts/Core/Axis/RadialAxis.ts#L911-L915) radial axes.

#### Live demo with steps to reproduce
https://jsfiddle.net/crqz7dvw/

#### Product version
9.0.1

**Comment by KacperMadej** [comment]
Hi @skrtheboss 

`afterGetOffset` is not a part of the public API - https://api.highcharts.com/highcharts/yAxis.events
`chart.axisOffset` is not a part of the public API.
Those are internal events and property - using or changing then is not supported.
