### ISSUE TITLE
Dragging doesn't seem to work correctly on mobile devices

### ISSUE THREAD

**Issue by garagataya-pinedev** [highcharts/highcharts#15513]
Dragging doesn't seem to work correctly on mobile devices – I've checked all the examples that are available, which have draggable points (e.g. this code doesn't work properly too https://jsfiddle.net/highcharts/sk3m3o7d/ )

Let me explain the steps to reproduce an issue:
1. Open chart in mobile browser
2. Start dragging the point (all good here)
3. Start dragging another point – and here is where things get weird. The wrong point starts moving and this repeats from here on. If I try to drag one point – the other one starts moving and also coordinates are somehow moving in a weird way.

It seems like this kind of charts just doesn't fully work on mobile in general.

**Comment by KacperMadej** [comment]
Hi @garagataya-pinedev 

[The plugin is deprecated](https://github.com/highcharts/draggable-points#deprecated-draggable-points-for-highcharts) but was upgraded to an official module which is working fine - https://jsfiddle.net/BlackLabel/wdaxLgyk/1/show
Tested on Android/Chrome.

More info and demos at https://api.highcharts.com/highcharts/series.line.dragDrop
