### ISSUE TITLE
Gap in series is relocated during animation when updating a null data-point

### ISSUE THREAD

**Issue by pfoedermayr** [highcharts/highcharts#15510]
#### Expected behaviour
When updating any data-point (with or without a value) the animation of the series should be the same.

#### Actual behaviour
If a `null` data-point is updated the animation "relocates" the other gaps.  
**Steps to reproduce**:
When clicking the "Update position 3" button in the demo, you can see that the gap (which was originally between 7 and 10) is beeing relocated during the animation (the gap "moves" from beeing between 10 and 11, back to 7 and 10).

If a data-point with a value is updated, the gaps are shown correctly in the animation.
**Steps to reproduce**:
When clicking the "Update position 4" button in the demo, you can see that the gap stays at the same position during the animation.

#### Live demo with steps to reproduce
http://jsfiddle.net/p8en0y4o/2/

#### Product version
Highcharts 8.1.2 (but also applies to latest version - see demo)

#### Affected browser(s)
Tested in Chrome (89), FF (87)

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

This is not a workaround but it might help for now to disable the animation - http://jsfiddle.net/BlackLabel/dsL02thw/
