### ISSUE TITLE
Organization Chart, wrong position for children with multiple hanging layouts

### ISSUE THREAD

**Issue by sebastian-hien-cf** [highcharts/highcharts#15527]
#### Expected behaviour
![grafik](https://user-images.githubusercontent.com/62055190/115210798-3cace300-a0ff-11eb-92eb-b8725397e719.png)

#### Actual behaviour
![grafik](https://user-images.githubusercontent.com/62055190/115209622-1175c400-a0fe-11eb-9831-1ae210fd3664.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/rta6nmq4/1/

#### Product version
Actual version I guess, dont know where to look it up

#### Affected browser(s)
Firefox, Chrome

**Comment by khlieng** [comment]
Probably related to #13915.

**Comment by sebastian-hien-cf** [comment]
> 
> 
> Probably related to #13915.

Thank you for the hint, but not really. I checked the post before creating my ticket, it is not about the wrong display of **multiple** hanging layouts I am facing.
