### ISSUE TITLE
Negative color is used even for positive values in Lollipop

### ISSUE THREAD

**Issue by vegaelce** [highcharts/highcharts#15523]
#### Expected behaviour
When defining a color and a negativeColor parameters, we should get positive values colored with the "color" parameter and negative values colored with the "negativeColor" parameter

#### Actual behaviour
Both positive and negative values are colored with the "negativeColor" parameter

#### Live demo with steps to reproduce
https://jsfiddle.net/vegaelce/ztkdm21v/

#### Product version
Highcharts 9.1

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.
