### ISSUE TITLE
Data points are not toggled using Enter/Space key in legend

### ISSUE THREAD

**Issue by franklinefrancis** [highcharts/highcharts#15520]
#### Expected behaviour
Data labels are enabled/disabled by pressing Enter/Space key in legend

#### Actual behaviour
Data labels are not disabled by pressing Enter/Space key in legend

#### Live demo with steps to reproduce
https://jsfiddle.net/franklinefrancis/1a3xwLh9/

1. Focus on the legend
2. Press Enter/Space on any data label - no change in visibility of data point
3. Click on any legend item - data point is hidden as expected

#### Product version
8.2.0

#### Affected browser(s)
Firefox only

**Comment by KacperMadej** [comment]
Hi @franklinefrancis 

Thank you for reporting the problem.

Default click actions for point and legend items are not the same in a pie series.
Why should click on a point or its text label (dataLabel) hide the point?

You could set up a custom point's click event - https://api.highcharts.com/highcharts/series.pie.point.events.click

**Comment by franklinefrancis** [comment]
@KacperMadej, the issue is not about click action of legend item. It is about discrepancy in default keyboard event and click event on legend items. If Space/Enter key is pressed after a legend item receives focus, the data point gets hidden and then gets immediately displayed again. But if I click a legend item, the data point gets hidden.

The following recording should clarify it hopefully:

![Uploading 15520.gif…]()

**Comment by khlieng** [comment]
I was able to reproduce this only in Firefox with the space key.

**Comment by franklinefrancis** [comment]
Correct @khlieng, this is reproducible only in Firefox.

**Comment by franklinefrancis** [comment]
@khlieng, can this fix be backported to 8.2.0 for which it was reported?

**Comment by khlieng** [comment]
Heres a plugin you can use: https://jsfiddle.net/506dowmj/

**Comment by franklinefrancis** [comment]
Thanks @khlieng. But the plugin also seems to be buggy. Disabled items are re-enabled on using arrow keys within the legend.

**Comment by khlieng** [comment]
Hmm, not able to reproduce, unless you mean just the color of the text in the legend.

**Comment by franklinefrancis** [comment]
Yes, I meant the legend text colour.

**Comment by khlieng** [comment]
Ok, thats just how the legend works in all browsers. @oysteinmoseng

**Comment by oysteinmoseng** [comment]
This is a bug, opened a new issue here: https://github.com/highcharts/highcharts/issues/15640
