### ISSUE TITLE
Chart remains to be greyed out even after losing focus

### ISSUE THREAD

**Issue by franklinefrancis** [highcharts/highcharts#15521]
#### Expected behaviour
Chart is not greyed out after losing focus

#### Actual behaviour
Data points of Donut, pie and bubble charts remain to be greyed out after losing focus

#### Live demo with steps to reproduce
https://jsfiddle.net/franklinefrancis/1a3xwLh9/

1. Focus on any data point
2. Use left/right arrow keys to navigate - inactive data points are greyed out
3. Press Tab or Shift+Tab - all data points are greyed out unless mouse is moved

#### Product version
8.2.0

#### Affected browser(s)
All browsers

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

Also visible in v9.0.1.

**Comment by oysteinmoseng** [comment]
Internal note: Also visible on official demo https://www.highcharts.com/samples/highcharts/accessibility/accessible-pie.
