### ISSUE TITLE
Clicking Data Labels doesn't trigger drilldown for Area and Line charts

### ISSUE THREAD

**Issue by AlissonRS** [highcharts/highcharts#15525]
#### Expected behaviour
In column charts with drilldown, when we click on the data labels it triggers drilldown, but the same doesn't happen to "area"  and "line" charts. For area it triggers the drilldown only if we click on the data point itself or in the axis label, but not in the data labels.

#### Actual behaviour
Clicking on data labels should trigger the drilldown. In the jsfiddle below, you can try changing the chart type to "column" and you'll see it works fine.

#### Live demo with steps to reproduce
https://jsfiddle.net/jgtkcrvy/

#### Product version
Highcharts JS v9.0.1

#### Affected browser(s)
Tested in Chrome Version 89

**Comment by KacperMadej** [comment]
Hi @AlissonRS 

Thank you for reporting the problem.

Line and area do not trigger a point click event on a dataLabel click.
As a workaround, it is possible to use scatter - https://jsfiddle.net/BlackLabel/uf906p4s/

Another solution: add `className: 'highcharts-tracker'` to series to have all its elements tracked for click - https://jsfiddle.net/BlackLabel/uf906p4s/1/

@TorsteinHonsi Is click on dataLabels for area or line prevented for some reason? or is this a bug?

**Comment by AlissonRS** [comment]
@KacperMadej thanks for the quick response.

Seems like adding `className: 'highcharts-tracker'` did the trick.

In my opinion (if I may share), this should be considered a bug because when drilldown is enabled, the data label gets styled as if it was clickable (blue with underline), so clicking on it should trigger the drilldown. Also, the data label for other chart types triggers the event just fine. If the data label is not supposed to trigger the event for line and area charts, then it should not get styled as if it was clickable (blue with underline).

Thanks for your help!!!
