### ISSUE TITLE
Y Axis Log Scale: InternalError Too much recursion

### ISSUE THREAD

**Issue by vmlopezr** [highcharts/highcharts#15536]
*Sorry for closing/reopening, accidentally pressed enter and this got submitted without finishing*
#### Expected behaviour
Appropriately display log scale on the y axis for any given series. 

My application  (using HighchartsReact wrapper) allows for any amount of series from some spreadsheet, and gives controls for setting the y axis of the series, the scale (linear/logarithmic),  tick amount, etc. 

As such, it should be able to toggle any y axis from linear to logarithmic.
Here is a simple example of my general usage. You can:
- Add y axes by clicking the 'Add Axis' button
- Assign a y axis to the series with the selects on the right.

https://stackblitz.com/edit/react-y4v8de?file=index.js

#### Actual behaviour

Found a recursion issue when Highcharts is calculating the ticks for a log scale y axis, specifically when the range of the series `max - min`  is less than 1.  For example a time series with the data:
```js
      series: [
        {
          type: "line",
          data: [[1598918400000, 1.2], [1604188800000, 1.2404]]
        }
      ]
```
<img width="324" alt="Screen Shot 2021-04-19 at 12 40 37 PM" src="https://user-images.githubusercontent.com/35988895/115280988-23f7f980-a10e-11eb-9b2f-39a9c16b5f4b.png">

#### Live demo with steps to reproduce
Here is a simple reproduction of the issue (using [HighchartsReact](https://github.com/highcharts/highcharts-react)). 
https://stackblitz.com/edit/react-7dxnsn?file=index.js

The series data is:
```js
series: [
   {
     type: "line",
     data: [[1598918400000, 1.2], [1604188800000, 1.2404]]
   }
]
```
Click on the 'Toggle Y Axis Type' button to set the axis to log scale. 

Here's another example with just Highcharts:
https://jsfiddle.net/eomdgauc/9/

#### Product version

Highcharts: 8.2.1
Highcharts: 9.0.1
#### Affected browser(s)
MacOS:
Tested on latest firefox, chrome and safari

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.
