### ISSUE TITLE
Rounded corner on bullet chart causes target bar to disappear

### ISSUE THREAD

**Issue by cgandhamQB** [highcharts/highcharts#15547]
#### Expected behaviour
The bullet chart's progress bar should have rounded corner on top. Target mark should not disappear

#### Actual behaviour
Able to get the rounded edge in the top of the bar but it causes the target mark to disappear when I use 'borderRadiusTopLeft' and 'borderRadiusBottomRight' on the series of my bullet chart. 

#### Live demo with steps to reproduce
https://jsfiddle.net/chandanasri/moe3L2c9/1/

**Comment by cgandhamQB** [comment]
Hi, am still getting the same issue. I see that am able to reproduce the issue in the fiddle also. https://jsfiddle.net/chandanasri/moe3L2c9/1/  . How can I consume your latest changes related to this bug? 
thanks

**Comment by KacperMadej** [comment]
v9.1.0 (current)

**Comment by cgandhamQB** [comment]
thank you, will I be able to style the target bar also to have the rounded edge?

**Comment by KacperMadej** [comment]
At this moment the functionality is not available in the plugin. This should be a part of the plugin, so should be reported in the plugin repository as an issue / feature request. https://github.com/highcharts/rounded-corners/issues
