### ISSUE TITLE
Make Scroll bar in Gantt Chart disappear when Range selector 'All' is selected

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/highcharts#15559]
#### Expected behaviour

Gantt chart scroll bar to disappear when 'All' is selected in Range selector

#### Actual behaviour

The scroll bar is always visible irrespective of the option chosen from Range selector

![image](https://user-images.githubusercontent.com/53110553/115694175-acc29f80-a371-11eb-814a-23025611d477.png)

#### Product version

Highcharts 8.0.0
#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @Sreejithga 

Thank you for reporting the problem.

By default, scroll bars (stand-alone and belonging to an axis) are visible when full. This could be changed through API: https://api.highcharts.com/highstock/xAxis.scrollbar.showFull
