### ISSUE TITLE
Pie Chart with Labels inside overlap

### ISSUE THREAD

**Issue by dragoshzava** [highcharts/highcharts#15552]
#### Expected behaviour
The overlapping labels should be hidden.

#### Actual behaviour
The labels are overlapped.

#### Live demo with steps to reproduce
https://jsfiddle.net/Resems/g3fyn87v

#### Product version
Highcharts latest ( v9.0.1 )
Highcharts 8+

#### Affected browser(s)
All

#### Additional Question
Is it possible to detect or somehow to hide the labels for specific data points?
Do note the data is dynamic, so in our case we would have to auto detect on runtime.
Any other alternative is welcome, thanks.

**Comment by KacperMadej** [comment]
Hi @dragoshzava 

Thank you for reporting the problem.

Pie series labels for points are placed to prevent overlapping when the `dataLabels.distance` has a positive value.
When negative the labels are placed on top of each slice and a filter could be used - see below.

Data labels could be [filtered](https://api.highcharts.com/highcharts/series.pie.dataLabels.filter) - demo: https://jsfiddle.net/BlackLabel/x7zyhfse/
