### ISSUE TITLE
Wrong automatic width for vertical map legend/color axis

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#15551]
#### Expected behaviour
Legend/color axis get correct automatic width 

#### Actual behaviour
Vertical Legend/color axis is too narrow when using longer labels

#### Live demo with steps to reproduce
See http://jsfiddle.net/kzoon/9jqwg3mL/

When aligned right: Legend will only fit when you fiddle around with x
When aligned left: Legend will only fit when you fiddle around with margin

#### Product version
Highmaps any version

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

Legend in vertical layout does not have its width adjusted to the colorAxis width (long labels).
Minimal demo: https://jsfiddle.net/BlackLabel/3gwyejxs/

Workaround: adjust manually through `legend.labelPadding` - http://jsfiddle.net/BlackLabel/xfkonqrz/
