### ISSUE TITLE
Two series with the same data overlap and you can only see one

### ISSUE THREAD

**Issue by 4insite** [highcharts/highcharts#15573]
#### Expected behaviour
User should be able to see both series on the chart.

#### Actual behaviour
When user create a series chart using highchart and two series have the same data, then you can't see both series...it just picks one to display

#### Live demo with steps to reproduce

https://user-images.githubusercontent.com/83086438/115907086-3bd8c180-a41d-11eb-9fa7-604330f2fc35.mov
<img width="1423" alt="request_1m" src="https://user-images.githubusercontent.com/83086438/115913239-33848480-a425-11eb-9482-975a247607c9.png">

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
For technical support see https://www.highcharts.com/blog/support/

A video is not a live demo.

You could use different chart types to display data that is now showing clearly for you but this is more a data visualization problem and not a bug that could be reported here. You could try stacked series or column-type series.
