### ISSUE TITLE
"Uncaught TypeError: Cannot read property '0' of undefined" (moveSegment) when setting extremes

### ISSUE THREAD

**Issue by nunoarruda** [highcharts/highcharts#15589]
#### Expected behaviour
Not throw an error when setting extremes.

#### Actual behaviour
Throws error on settings extremes in a very specific scenario when:
1. using type `area`
2. using dataGrouping enabled `false`
3. setting xAxis extremes to a range with no available data points
4. using null points (see demo below)
5. having a specific list of data points (see demo below)

#### Live demo with steps to reproduce
Demo: https://codepen.io/nunoarruda/pen/poRYrBZ?editors=1010
1. Open DevTools console
2. Click the set extremes button
3. Click the "3m"  button
4. Click the set extremes button again
5. See the error on the console

https://user-images.githubusercontent.com/1189149/116254686-13283300-a761-11eb-939e-c34dae91460a.mov

Note: Looking at the source code, this might be related to `moveSegment` being undefined. This issue might or might not be related to #14939.

#### Product version

Highstock JS v9.0.1 (2021-02-15)

#### Affected browser(s)
All of them.
Error on Chrome: `Uncaught TypeError: Cannot read property '0' of undefined`
Error on Firefox: `Uncaught TypeError: h is undefined`
Error on Safari: `TypeError: undefined is not an object (evaluating 'h[0]')`

**Comment by khlieng** [comment]
Fixed on master (#15538).
