### ISSUE TITLE
Maps: stickyTracking for mappoint is not documented in API

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#15594]
The API property `mappoint.stickyTracking` is missing in the API for Maps
https://api.highcharts.com/highmaps/plotOptions.mappoint.stickyTracking

#### Product version
Highcharts Maps 9.0.1

**Comment by KacperMadej** [comment]
Demos showing that the feature works:
https://jsfiddle.net/BlackLabel/0m1urvp4/
https://jsfiddle.net/BlackLabel/Lenyhsor/
