### ISSUE TITLE
'stickOnContact' not working, when outside is true

### ISSUE THREAD

**Issue by lkree** [highcharts/highcharts#15600]
#### Expected behaviour
Hovered tooltip dont dissapear, while outside is true and stickOnContact is true

#### Actual behaviour
when outside is true and stickOnContact is true, tooltip is closed, when hovered.
when outside is false and stickOnContact is true, tooltip IS NOT closed, when hovered.

#### Live demo with steps to reproduce
https://jsfiddle.net/xksb13vu/

#### Product version
9.0.1

**Comment by khlieng** [comment]
Duplicate of #14434.
