### ISSUE TITLE
Indicators with multiple lines should have default colors

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#15608]
#### Expected behaviour
For indicators with multiple lines, for example, MACD (line, signal, histogram) default colour should be set.
In another way, adding the indicator through GUI results in a hard to read indicator with only one color.

#### Live demo with steps to reproduce
Add a MACD indicator through the GUI.
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui

#### Product version
Highstock JS v9.0.1 (2021-02-15)

#### Affected browser(s)
All

**Comment by rendimentofondi** [comment]
Hallo, this issue is in to do list since more that 1 year.
Should be possible to prioritise this ticket?
This bug is very bad looking.
Do you have any potential due date for solving?

Thank you 
Walter

**Comment by raf18seb** [comment]
Hi @rendimentofondi, sorry for the late reply. Yes, we are working on a solution. It should be available in one of the next Highcharts releases.
