### ISSUE TITLE
Bug Gantt with subtask - Wrong data in the drop event identifying the drag and drop rows

### ISSUE THREAD

**Issue by JohanBrodinSinch** [highcharts/highcharts#15601]
#### Expected behaviour
The use case is to implement rearrange items with drag and drop on gantt with subtask. The problem is that the drop row (e.newPoint.y) is not consistently returning the correct value. To me it sounds like a timing bug on your side.

#### Actual behaviour
* Very buggy giving different values. Sometimes it is working 10 times before giving wrong drop row value

Example bugs
In the demo randomly drag bars and drop on others. There is an alert showing the drop row value and pay attention when hat will start reporting the wrong value.

#### Live demo with steps to reproduce
https://jsfiddle.net/6vLfz0ky/

#### Product version
Latest modifying the demo

#### Affected browser(s)
tested on chrome but should be all

**Comment by raf18seb** [comment]
Hi @JohanBrodinSinch! Thanks for writing to us with your issue.

I am not sure if I understood your problem well. You have set the `series.dragMaxY: 2`. It's not affecting anything, it's only limiting the `e.newPoint.y` value, however, you can get the real point's `y` value form `e.target.y`, or you can get rid of `series.dragMaxY` totally and get the current "dragged to" y like this: https://jsfiddle.net/BlackLabel/4yunzhft/

If I misunderstood you, could you maybe provide a gif or the exact steps helping me reproduce your issue? Thanks in advance.

**Comment by JohanBrodinSinch** [comment]
Thank you for your replay!

You are right it works just fine setting the dragMaxY to the max row value or removing it completely. You can close this issue and I should have seen this myself sorry! 

However an improvement on your end could be to not trigger the drop event on rows below the dragMaxY value. This would in my book be a better use experience then triggering it with with the dragMaxY value.
