### ISSUE TITLE
Highcharts.NET: Cannot implicitly convert type 'Highsoft.Web.Mvc.Charts.PlotOptionsPieDataLabels' to System.Collections.Hashtable

### ISSUE THREAD

**Issue by Jochen-Scharr** [highcharts/highcharts#15612]
Why does this

![2021-04-29 12_24_00-Window](https://user-images.githubusercontent.com/6214342/116538678-244f7c00-a8e8-11eb-9874-7d2b7b84125b.png)

work but and this

![2021-04-29 12_23_01-Window](https://user-images.githubusercontent.com/6214342/116538880-68428100-a8e8-11eb-8830-9b48aaec9b9d.png)

does not?

Compiler says "Cannot implicitly convert type 'Highsoft.Web.Mvc.Charts.PlotOptionsPieDataLabels' to System.Collections.Hashtable'". It worked in Highcharts.NET Version 6, but now in Version 9.0.1.1 it does not work anymore. Why? How can I workaround it? I feel frustrated and lost. 

#### Product version
Highcharts.NET Version 9.0.1.1

**Comment by KacperMadej** [comment]
Thank you for reporting.

fyi @brofixo
