### ISSUE TITLE
Axis label click event gives wrong position (label.pos) on Gantt Chart

### ISSUE THREAD

**Issue by sanoopsp** [highcharts/highcharts#15614]
I have created highcharts gantt chart with 200+ rows. The Y-axis name/label is same for all the rows. I am getting inconsistent click position when I click on Y-Axis names.

#### Expected behaviour
It should give correct row number as we need to update the label on click event.

#### Actual behaviour
Getting inconsistent click position when I click on Y-Axis names

#### Live demo with steps to reproduce
https://jsfiddle.net/SanoopSP/v3qzxk07/3/

Steps to reproduce:
1. Click on Y-Axis label of first row (Result is correct)
2. Scroll to last
3. Click on Y-Axis label of last row (Result is **wrong**)
4. Again scroll to top
5.  Click on Y-Axis label of first row (Result is **wrong**)

#### Product version
v8.2.0

#### Affected browser(s)
Chrome Version 89.0.4389.114 (Official Build) (64-bit)

**Comment by raf18seb** [comment]
Hi @sanoopsp thank you for reporting the issue.

**Comment by sanoopsp** [comment]
Hello,
Any release plan with a fix for this issue?
Thank you.
Regards,
Sanoop

**Comment by raf18seb** [comment]
@sanoopsp 
Sorry, we don't have ETA for fixing it yet. You will get a notification in this ticket when we decide to start working on it.

**Comment by KacperMadej** [comment]
A scrollable chart is implemented for Gantt only as scrollablePlotArea (vertical scrolling).
https://github.com/highcharts/highcharts/issues/9378
Gantt API doesn't support a scrollbar on an axis.
Unable to recreate through the correct chart options: https://jsfiddle.net/BlackLabel/xhkr1dja/
Closing for now.
Please leave a comment with more info in case you would like to see the issue reopened.
