### ISSUE TITLE
Chart Series are merging together when browser window is zoomed in/out

### ISSUE THREAD

**Issue by Anudeep-Kadavergu** [highcharts/highcharts#15619]
I have created a chart with 5 series, 4 columns, 1 line which loads upto 20k points.
When Iam zooming in/out the browser window, the chart gets collapsed/merged into single. I have found no error in my code.

#### Product version
Latest

![issue](https://user-images.githubusercontent.com/40947280/116656422-4ad5eb80-a9aa-11eb-8a7d-3fa4e327c942.png)

**Comment by raf18seb** [comment]
Hi @Anudeep-Kadavergu, thank you for reporting the issue.

Are you able to reproduce this behavior in an online code editor, e.g. jsFiddle so we can take a closer look at it? Thanks in advance

**Comment by Anudeep-Kadavergu** [comment]
I am dealing with some large amount of data. I didn't found out that behavior in jsfiddle snippet, Only on live web page that is occured.

**Comment by Anudeep-Kadavergu** [comment]
[jsfiddle](https://jsfiddle.net/Anudeep001/ke9ybdcn/60/)

**Comment by raf18seb** [comment]
Unfortunately, I tested it on a local web page and I still don't see any problem. Could you provide the exact steps to reproduce the issue?

**Comment by Anudeep-Kadavergu** [comment]
I got the issue, The series are merging due to change in height and width of the browser. I am able to solve issue by giving width attribute.
chart:{
     width:100,
}
Can you please give me some idea how to make chart responsive?

**Comment by raf18seb** [comment]
@Anudeep-Kadavergu there should be a better fix than defining width rigidly. However, I am still not able to reproduce the issue.
I repeat my question - could you provide the exact steps to reproduce the issue?

If you are not sure if this is a bug or maybe there might be something wrong with your app - please, contact us on one of the dedicated support channels: https://www.highcharts.com/blog/support/
It is worth checking whether this is a bug and locate it first, before creating a GitHub ticket.

**Comment by Anudeep-Kadavergu** [comment]
Thank you for your time.
