### ISSUE TITLE
Incorrect axis extremes in indicator series

### ISSUE THREAD

**Issue by KrishnaKumarHariprasannan** [highcharts/highcharts#15617]
#### Expected behaviour
Extremes to be computed for the data point in view

#### Actual behaviour
Extremes computed includes data point that is not in view

#### Live demo with steps to reproduce

https://jsfiddle.net/Lwk0j5as/5/ - click one of the range selector buttons to reproduce. This was previously discussed in https://www.highcharts.com/forum/viewtopic.php?f=12&t=46367. Summary of the discussion there:

The above fiddle demonstrates the issue with incorrect axis extremes computation - this is because the value at `minIndex - 1`is considered for computing the axis extremes for a range [minIndex, maxIndex].

I was able to workaround that in https://jsfiddle.net/Lwk0j5as/6/ by defining a cropShoulder value of 0 (as opposed to the default value of 1) which lead to issues with shoulder of the curve in some cases. 

Two questions emerge from the above:

1. Is there an alternate solution to the axis extremes issue in https://jsfiddle.net/Lwk0j5as/5/ ?
2. In the solution with cropShoulder=0, how can I ensure to restrict the plot area to start and end exactly at minExtreme and maxExtreme respectively?

#### Product version

9.0.1

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @KrishnaKumarHariprasannan 

Thank you for reporting the problem.

The series is rendered in a way to show a line going away from the visible series plot to the next point that is not visible, so the plotline won't be cut if and connection to the point outside of the visible range is correctly shown.

1. You could change whole series data, but this is not a better solution.
2. Do you want to restrict y-axis scale? If yes, then the below options should be enough:
```js
 	yAxis: {
		minPadding: 0,
		maxPadding: 0,
		startOnTick: false,
		endOnTick: false
	}
```
Demo: https://jsfiddle.net/BlackLabel/etdL1qyg/

**Comment by KacperMadej** [comment]
After a better look into the issue:
this is by design and is used as explained in the above comment - in your case, the line connecting the point is sometimes almost not visible and might be problematic for the chart. Your case seems to be an edge case, so it might require additional work to make it work perfectly - like modifying cropShoulder or changing series data to match viewed range.

**Comment by KrishnaKumarHariprasannan** [comment]
Thanks for the reply @KacperMadej ! 2. from above works as a better workaround than 1. and I'll use the same.
