### ISSUE TITLE
Gantt chart yAxis is expanded when clicking on the legend series

### ISSUE THREAD

**Issue by AndriiMakar** [highcharts/highcharts#15610]
#### Expected behaviour
yAxis items should not be expanded when clicking on the legend series

#### Actual behaviour
All items that have children are expanded

#### Live demo with steps to reproduce
Click on Series 2 in the legend. Series 1 will be expanded
https://jsfiddle.net/9krcay8g/

#### Product version
Highcharts Gantt JS v9.0.1

#### Affected browser(s)
Google Chrome, Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by KacperMadej** [comment]
Thank you for reporting the bug.
