### ISSUE TITLE
Exporting chartOptions with dataLabels

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#1562]
Example: http://jsfiddle.net/YARYv/

Steps to reproduce:
- try to export chart to PNG or others

As you can see, background is changed properly, but dataLabels aren't added to the exported image.

**Comment by sebastianbochan** [comment]
Seems that size parameter is also ignored in chartOptions. http://jsfiddle.net/nkj2msvp/3/

**Comment by mischah** [comment]
Any news on that?

**Comment by highslide-software** [comment]
The OP's issue does work now, you are able to enable data labels in the chartOptions: http://jsfiddle.net/highcharts/YARYv/14/. But I had to remove the textShadow due to another issue that we're working on.

The pie size however doesn't work.

**Comment by mischah** [comment]
My usecase is a bit different:

I make use of the `formatter` function because I have to deal with large numbers and I want the datalabel of every column to be visible in a short form.
Example: `16,0 Mio` instead of `15998000`

The real number is shown in the tooltip.

In the exported graphic is no tooltip available :smile: 
… so I want to show the exact and large number as datalabel. Therefore I need to overwrite the `formatter` function.

 See http://jsfiddle.net/mischah/YARYv/15/

**Comment by mischah** [comment]
Sorry for highjacking this issue. Should I open another one?

**Comment by pawelfus** [comment]
I think this is not necessary - in general, it looks like a problem with `dataLabels` options. Now it's possible to enable labels for exporting, but issue with formatter remains. 

Anyway, there is simple workaround for your case, check flag `forExport` in your formatter to return two different strings, for example: 

                    formatter: function () {
                        var value = this.y;
                        if (!this.point.series.chart.options.chart.forExport) { // flag for exporting
                            if (value > 1000000) {
                                value = Math.round(value / 100000) + '';
                                value = value.charAt(0) + value.charAt(1) +
                                    ',' + value.charAt(2) +
                                    " Mio.";
                            } else if (value > 1000) {
                                value = Math.round(value / 1000) + " Tsd.";
                            }
                        }

                        return value;
                    },

And demo: http://jsfiddle.net/YARYv/16/

**Comment by mischah** [comment]
Hah. superb. That’s valid workaround. Thank you very much :heart_eyes: 

But it’s not a solution :wink: 
Because I have to reimplement the default formatting to get the thousands seperators back for printing. 

Like so:

```javascript
formatter: function() {
  var value = this.y;
  if (!this.point.series.chart.options.chart.forExport) { // flag for exporting
    if (value > 1000000) {
      value = Math.round(value / 100000) + '';
      value = value.charAt(0) + value.charAt(1) +
        ',' + value.charAt(2) +
        " Mio.";
    } else if (value > 1000) {
      value = Math.round(value / 1000) + " Tsd.";
    }
  } else {
  	// reimplement default formatting 
  }

  return value;
},
```

**Comment by pawelfus** [comment]
Do you mean you need to use [`Highcharts.numberFormat()`](http://api.highcharts.com/highcharts#Highcharts.numberFormat)? ;)

**Comment by highslide-software** [comment]
... or more general, call the default formatter from the default options: 

```
value = Highcharts.getOptions().plotOptions[this.point.series.type].dataLabels.formatter.call(this);
```
[View it live on jsFiddle](http://jsfiddle.net/highcharts/YARYv/17/).

**Comment by mischah** [comment]
@pawelfus @highslide-software 
Interesting :+1: 

… I see there are way more options than I thought about.

Thanks for sharing :blush:

**Comment by bkfunk** [comment]
Note, also, that the OP's issue is still a problem if you want to _overwrite_ an option in the default.

See here, where, if you set the original chart to have dataLabels not enabled, the exported chart won't have them even if explicitly overridden:
http://jsfiddle.net/YARYv/18/

**Comment by upendrasharma221** [comment]
Also when we drilldown a chart and then export it, datalabels are visible twice in png. This is the url for demo http://jsfiddle.net/upendrasharma221/ham570tm/

**Comment by highslide-software** [comment]
@upendrasharma221 Your demo doesn't have drilldown? Anyway there is a bug with textShadow causing duplicated text in some cases. You can set textShadow to `none` to fix it: http://jsfiddle.net/highcharts/ham570tm/3/

**Comment by blaDDI** [comment]
http://jsfiddle.net/XWCke/58/

**Comment by AstashinVladimir** [comment]
@highslide-software 
Hello!
I want to ask if problem with plotting labels on export is solved for 3d charts?
My example unfortunatly isn't working :(
http://jsfiddle.net/xvQNA/134/
Can you help me?

**Comment by blaDDI** [comment]
check the example: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pie-basic/

**Comment by AstashinVladimir** [comment]
@blaDDI I need to hide datalabels on diagramm and show it only on exported diagramm, but this functionality seems not working.
Thanks

**Comment by blaDDI** [comment]
try use 2 containers, first with dataLabels=false and a second with atribute hide and dataLabels=true.
In exporting.js change this line 
// get the SVG from the container's innerHTML use the second container
svg = chartCopy.container.innerHTML;

**Comment by pawelfus** [comment]
Your options are wrong: `plotOptions` should be under `chartOptions`. However, indeed it doesn't work, let's reopen issue. 

Reliable demo: http://jsfiddle.net/YARYv/23/ - note `plotOptions.series.dataLabels = false` options has to be set strictly, not the default value. That's why for pie chart it is common issue (where data labels are enabled by default).

**Comment by AstashinVladimir** [comment]
@blaDDI Thank yoг for help, but I can't use this variant with multiplying my programm code, because I got a lot of different charts in my project and they have different logic, it seems to be a bug in library.

@pawelfus So problem is opened and this problem as I can see appears only for 3d pie charts/ Standart graphic(not pie) is work properly.

**Comment by AstashinVladimir** [comment]
Guys, hi all!
Any news about this bug?

**Comment by AstashinVladimir** [comment]
@pawelfus @TorsteinHonsi 
 So I've reproduced it in this version http://jsfiddle.net/xvQNA/134/ and it still not working, can you help me with this question?

**Comment by AstashinVladimir** [comment]
@pawelfus @TorsteinHonsi 
Sorry. this one http://jsfiddle.net/xvQNA/138/

**Comment by upendrasharma221** [comment]
Try this http://jsfiddle.net/xvQNA/139/

**Comment by AstashinVladimir** [comment]
@upendrasharma221 I need to show datalabels only in exported image

**Comment by upendrasharma221** [comment]
Oh, let me try that

**Comment by pawelfus** [comment]
You can update series when chart is rendered for exporting server, take a look: http://jsfiddle.net/xvQNA/140/

**Comment by AstashinVladimir** [comment]
@pawelfus Thank you, it workiing!

**Comment by TorsteinHonsi** [comment]
This one now works: http://jsfiddle.net/highcharts/YARYv/26/

**Comment by pawelfus** [comment]
It works for line series, but doesn't for a pie chart: http://jsfiddle.net/YARYv/27/

**Comment by TorsteinHonsi** [comment]
Fixed: http://jsfiddle.net/highcharts/YARYv/28/

It's a quite risky fix, since we risk losing options that are updated on the base series. But I have tested selected cases plus all the regression tests, so if anything comes up I think we should fix those cases instead of reverting this.

**Comment by LoganDupont** [comment]
I have also an example where I want to export chartOptions with dataLabels on all series. But due to dataLabels that are disabled in specific series i'm not able to see all datalabels in the export. Probably it gets overwritten. What is the best solution to solve this problem? https://jsfiddle.net/w1cL4f3x/3/

**Comment by pawelfus** [comment]
The best way is to use `series` instead of `plotOptions`, take a look: https://jsfiddle.net/BlackLabel/pq5m6cnu/

**Comment by LoganDupont** [comment]
> The best way is to use `series` instead of `plotOptions`, take a look: https://jsfiddle.net/BlackLabel/pq5m6cnu/

@pawelfus I didn't mention it but the amount of series can be dynamic. So I don't know how many series I will have in order to change the dataLabels in my export

**Comment by pawelfus** [comment]
In `load` event we can update every series, take a look: https://jsfiddle.net/BlackLabel/zefk1vjw/
