### ISSUE TITLE
lastVisiblePrice and lastPrice can't be set through the plotOptions for multiple series

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#15621]
#### Expected behaviour
For multiple series, there should be a possibility to add and modify the `lastVisiblePrice` and `lastPrice` through `plotOptions`.

#### Actual behaviour
`lastVisiblePrice` and `lastPrice` properties declared in `plotOptions` doesn't effect the indicator.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/d8rjkLoc/

#### Product version
Highstock JS v9.0.1 (2021-02-15)

#### Affected browser(s)
All

**Comment by khlieng** [comment]
Doesnt it work if you set it on [plotOptions.series](https://api.highcharts.com/highstock/plotOptions.series.lastVisiblePrice)?: https://jsfiddle.net/vcj07936/

**Comment by karolkolodziej** [comment]
![tenor](https://user-images.githubusercontent.com/57004120/117637391-0bfe1d80-b182-11eb-901c-9a358a2a6c30.gif)
