### ISSUE TITLE
The xAxis labels are mispositioned in some cases when resizing the chart.

### ISSUE THREAD

**Issue by wbrzosko** [highcharts/highcharts#15624]
#### Expected behaviour
The chart container has 1660px at the start and xAxis labels are correctly positioned.
When the width of the chart parent container is decreased (700px) and increased back again the labels should go back to the original position.

#### Actual behaviour
1) Click the Resize 700px button - the chart will shrink
2) Click the Resize 1660px button - the chart will expand again
3) The first label is positioned wrongly, it's placed outside the visible area

The same happens when you just start resizing the chart section.

#### Live demo with steps to reproduce
https://jsfiddle.net/wojciech_brz/4hfa803s/
#### Product version
Highcharts v9.0.1, Highmaps  v9.0.1 

#### Affected browser(s)
Chrome, Firefox on Windows

**Comment by raf18seb** [comment]
Hi @wbrzosko, thanks for reporting the issue.

Seems like a bug. Simplified demo: https://jsfiddle.net/BlackLabel/9euy1twg/

The xAxis labels are mispositioned in some situations:
![xAxis labels mispositioned](https://user-images.githubusercontent.com/23310742/117323365-1cb34880-ae8f-11eb-84e7-d41cce818cbe.gif)
