### ISSUE TITLE
[Accessibility]: Screen Reader(or Keyboard) is skipping those graph series whose previous series data point is set to '0' when user navigates inside Graph Up/Down arrow key.

### ISSUE THREAD

**Issue by Shubham786786** [highcharts/highcharts#15622]
#### User Impact: 
Screen Reader user are impacted here as Screen reader is announcing incorrect count and position when user navigates inside Graph Up/Down arrow key due to skipping of a particular series which is confusing.

#### Test Environment ​​
OS: Version 2004 (OS Build 21332.1000)
Browser: Edge Anaheim
Browser version: Version 90.0.818.6(Official build) dev (64-bit)
URL: [https://www.highcharts.com/demo/area-stacked-percent](url)  
Screen Reader: NVDA

#### Repro steps
1. Open above [https://www.highcharts.com/demo/area-stacked-percent](url) on Anaheim Dev Browser.
2. Navigate to 'Edit in JSFIDDLE' and activate it.
3. In JS Code, Set Europe first data point as '0' just like this ->[0, 203, 276, 408, 547, 729, 628]
3. Run the Code.
4. Open Graph in Full Screen View .
5. Open NVDA Screen Reader.
6. Navigate to Asia Series using tab key.
7. Now Navigate to other series(Africa, Europe, America ...) using 'Down/Up' key and Observe the issue.

#### Expected behaviour
Screen Reader(or Keyboard) should not skip that graph series data point whose previous series data point is set to '0' when user navigates inside Graph Up/Down arrow key. 

#### Actual behaviour
Screen Reader(or Keyboard) is skipping those graph series whose previous series data point is set to '0' when user navigates inside Graph Up/Down arrow key. For Example: when Europe series first data point is set to '0' Screen Reader(or Keyboard) skip 'America' series.

#### Observation
Same issue repro with NVDA Screen Reader.

#### WCAG(or MAS) Guideline
[https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships](url)

#### Bug Repro Attachments
[Issue Repro Attachments.zip](https://github.com/highcharts/highcharts/files/6404476/Issue.Repro.Attachments.zip)

NVDA Screen Reader download link [https://www.nvaccess.org/download/](url)

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.
