### ISSUE TITLE
[Question] Hide unwanted indexes from Y-Axis from a stacked bar chart

### ISSUE THREAD

**Issue by nabeelsuspg** [highcharts/highcharts#15633]
#### Expected behavior
I have data set with building names on Y-axis and decimal values on the x-axis. I want to show users a stacked bar chart with one or more buildings. Each building has multiple decimal values associated with them. For example, if a user selects one building then the Y-axis should contain only one building name and the x-axis should have all values.

#### Actual behaviour
Y-axis has unknown-unwanted indexes.  

#### Screenshot
![Stacked-bar-JSFiddle-Code-Playground](https://user-images.githubusercontent.com/76268417/117042251-921cee80-acc0-11eb-8993-12f99fadbddf.png)

**Comment by raf18seb** [comment]
Hi @nabeelsuspg!
Please, for any support questions, use our dedicated support channels: https://www.highcharts.com/blog/support/

If you want to hide unwanted xAxis labels, you can use `xAxis.labels.formatter`: https://jsfiddle.net/BlackLabel/5p0od3k6/
If you want to keep only the first point, you can set xAxis.min: 0`: https://jsfiddle.net/BlackLabel/wtopns2L/ or you can hide unnecessary points: https://jsfiddle.net/BlackLabel/wn0dq3mb/
