### ISSUE TITLE
Missing type definition for 'processedYData' in class 'Series'.

### ISSUE THREAD

**Issue by dota2Pro** [highcharts/highcharts#15630]
#### Expected behaviour
In this Stackblitz example I am using tickPositioner on Y-axis, and I noticed that series is missing definition for 'processedYData' line number 46 in app.component.ts
But It works if you type cast series object as "any"

#### Actual behaviour
There should be a type definition for 'processedYData' and 'processedXData' 

#### Live demo with steps to reproduce

https://stackblitz.com/edit/highcharts-angular-basic-line-9qpzew?file=src%2Fapp%2Fapp.component.ts
#### Product version

    "highcharts": "^8.2.0",
    "highcharts-angular": "^2.8.0",
    "highcharts-rounded-corners": "^1.0.6",
#### Affected browser(s)
Chrome 89

**Comment by KacperMadej** [comment]
Hi @dota2Pro 

I apologize for the late reply.

The public API for [Series](https://api.highcharts.com/class-reference/Highcharts.Series) doesn't have definitions for  'processedYData' and 'processedXData'. Those are internal properties and might cause unexpected breaking changes in your chart if you are using them with any Highcharts version update (even maintenance), so it is not safe to use those without selecting a precise version (e.g. "highcharts": "8.2.0" should be fine).

Casting to `any` should allow access (despite potentially questionable different versions compatibility) or you could extend TS definitions as shown in the docs: https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-declarations#extending-highcharts-in-typescript

Would you like me to change this issue into a feature request? or close as an explained question? or maybe you have more relevant info that you would like to share?
