### ISSUE TITLE
Data label not working with box plot

### ISSUE THREAD

**Issue by ajinkyabapat1** [highcharts/highcharts#15631]
#### Expected behaviour
Hi,

I am trying to put the value of the lower and upper quartile on the box plot. But it's not showing.

can anybody suggest? How to get that.

I am trying to implement it in the below fiddle.

https://jsfiddle.net/BlackLabel/zjsugt0y/

![box plot req](https://user-images.githubusercontent.com/36852923/116916477-fdd46c80-ac6a-11eb-9d1e-68245241adf6.png)

**Comment by khlieng** [comment]
Box plot does not support data labels officially, but something like this?: https://jsfiddle.net/at38smkh/

**Comment by raf18seb** [comment]
Hi @ajinkyabapat1,
this is our bug tracker - in case of any support questions, it would be better for you to use other support channels: https://www.highcharts.com/blog/support/

I am closing the ticket here :)
