### ISSUE TITLE
Sorting Y Axis with Multiple Series

### ISSUE THREAD

**Issue by AlissonRS** [highcharts/highcharts#15632]
#### Expected behaviour
To be honest I'm not sure this is a bug, I think I might be misusing the `series.dataSorting` config.

I have a chart with multiple series, I wanted to sort by the Y value within each group label. If you look in my jsfiddle, each "Day Name" will have three different OS (Android, iOS, WP8), and I wanted the OS to display sorted by their Value for that day name. It looks ok for Saturday and Friday, but wrong for the other days.

#### Actual behaviour
If you look at Sunday in the iOS series (in the code), the value is 177379282, but in the chart this is being shown in the "Saturday" group.

#### Live demo with steps to reproduce
https://jsfiddle.net/4a17twqr/3/

#### Product version
Highcharts v9.0.1

**Comment by raf18seb** [comment]
Hi @AlissonRS!
Yes, this is not a bug. The `series.dataSorting` config works a little bit differently.

I think you are looking for something like this, am I right? https://jsfiddle.net/BlackLabel/w319g8tn/
It is not supported in Highcharts - feel free to create a separate feature request ticket.

For the future - this is our bugs tracker, so if you are not sure about our API or you are not sure whether something is a bug, please use our other support channels. More info: https://www.highcharts.com/blog/support/
