### ISSUE TITLE
Cannot create multiple polygons dynamically with setData

### ISSUE THREAD

**Issue by jmitzka** [highcharts/highcharts#15644]
#### Expected behaviour
Would like to add polygons to chart dynamically using either series.setData or series.update.

#### Actual behaviour

polygon series correctly draws multiple polygons (rectangles) if they are defined in the data of the series before the chart is rendered. Adding the same polygons using setData (or update) does not draw the polygons correctly, it starts to combine the rectangles into other shapes.

#### Live demo with steps to reproduce
https://jsfiddle.net/qeksbwt1/

drag mouse to create xy selection
selection coordinates form a polygon (rectangle), added to mypoly series
![image](https://user-images.githubusercontent.com/11504233/117036066-0b254180-acd3-11eb-87d9-7468066df299.png)

repeat with different selection
![image](https://user-images.githubusercontent.com/11504233/117036342-50497380-acd3-11eb-9301-3f9d64214888.png)

repeat for a third time, see distorted polygons
![image](https://user-images.githubusercontent.com/11504233/117036512-8129a880-acd3-11eb-9e61-c0842b94e87d.png)

Next uncomment the data of the 'mypoly' series and rerun. Polygons (rectangles) are drawn properly.

**Comment by KacperMadej** [comment]
Hi @jmitzka 

Thank you for contacting us about the problem.

`setData` by default will try to update points and this is causing the problem. You could set 3rd argument of the `setData` to false and the issue will be resolved - demo: https://jsfiddle.net/BlackLabel/pq5603vk/

Closing as answered question. If you would like to see the issue reopened please add a comment with more info.

**Comment by jmitzka** [comment]
Thank you, that seems to work.
