### ISSUE TITLE
Highcharts highmap mouse wheel zoom doesn't work on windows machine

### ISSUE THREAD

**Issue by rengare** [highcharts/highcharts#15656]
#### Expected behaviour
In Edge or Chrome mouse wheel should trigger zoom.
On MacOs, user has to hold shift with mouse wheel to zoom the map.

#### Actual behaviour
Mouse wheel doesn't zoom in map.

#### Live demo with steps to reproduce
https://jsfiddle.net/wL6j9ten/

#### Product version
 Highmaps JS v9.1.0

#### Affected browser(s)
Windows:
- Edge
- Chrome

**Comment by raf18seb** [comment]
Thank you for reporting the issue.

Confirmed that the mouse wheel navigation is working fine in all mac browsers, but isn't working on any Windows browser.

**Comment by TorsteinHonsi** [comment]
@raf18seb Thanks for the heads up. I assume it has to do with either introducing the `onwheel` event, or the `e.deltaY` property. So we need better decisions on when to use what.

**Comment by hihajdus** [comment]
Hi, this problem still exists, I have had two reports from users, on Windows.

**Comment by olessiap** [comment]
Hello, is there a plan to get this fixed in the near future? My team is also experiencing this issue on windows machines and we are blocked from implementing zoom with a mouse wheel because of it.
Kind regards.

**Comment by KacperMadej** [comment]
The issue is planned to be fixed this or next week.
