### ISSUE TITLE
Highcharts Scatter render change bug

### ISSUE THREAD

**Issue by atmgrifter00** [highcharts/highcharts#15667]
#### Expected behaviour

Switching between line and marker options for scatter data using 'update' method keeps hover render behavior consistent.

#### Actual behaviour

When starting out with just a line plot (in 'scatter' mode), and then you switch to showing markers (changing lineWidth to 0, but marker->radius to some non-0 value), then on hover, the line visual still gets rendered between points. If you instead started off showing markers and having lineWidth set to 0, you do not get the hover behavior showing lines.

#### Live demo with steps to reproduce
https://codepen.io/atm_grifter/pen/qBrBrbb

Just press the 'Change Render' button to see that on hover you still see the line visual.

To see it start out with markers and not show lines on hover, change 'markerEnabled' to default to true, and change the defaults of marker->radius to 2, and lineWidth to 0.

#### Product version
9.1.0

#### Affected browser(s)
All?

**Comment by khlieng** [comment]
Workaround, set `states.hover.lineWidthPlus`: https://jsfiddle.net/856fz02o/1/

**Comment by atmgrifter00** [comment]
Yep, that's the workaround, but I just wanted to bring up the issue in case it was considered a problem worth addressing without the need of the workaround.

**Comment by raf18seb** [comment]
Thanks for reporting, @atmgrifter00.

Bisected to https://github.com/highcharts/highcharts/commit/4dc2b388fc23b352841274501c184a75b7f16dca
Generally, it's a regression after #10256

v7.0.3 is working fine: https://jsfiddle.net/BlackLabel/b4ukc36j/
v7.1.0 is broken: https://jsfiddle.net/BlackLabel/8uqa0gp6/ (line stays, hides on mouseout and shows on mouseover)
v9.1.0 (current) is broken: https://jsfiddle.net/BlackLabel/0k9eqbdc/ (line disappears on update, but shows on mouseover)

**Comment by KacperMadej** [comment]
This is expected and by design or at very least in opposition to https://github.com/highcharts/highcharts/issues/13816
Maybe more info in [the API docs](https://api.highcharts.com/highcharts/series.scatter.lineWidth) could resolve this?

**Comment by atmgrifter00** [comment]
To be clear, the expected behaviors between this issue and the one you reference are _not_ in opposition of each other.

**Comment by KacperMadej** [comment]
@atmgrifter00 Thank you for point this out - you are right.
I missed the `lineWidthPlus` was set to zero in the #13816.

So how about setting default `lineWidthPlus` for scatter type series to zero?
I mean it is the same as the suggested workaround but would work out of the box (by default options).

**Comment by atmgrifter00** [comment]
The only reason being you lose the highlight behavior when switching a rendering mode to "lines". To me, it seems appropriate for Highcharts to only use the 'lineWidthPlus' state, _if_ the plot is being rendered as lines, but perhaps this is a naive perspective.
