### ISSUE TITLE
Unwanted stack labels after the drill-up

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#15663]
#### Expected behaviour

Should work as it used to be in the previous versions: https://jsfiddle.net/BlackLabel/cjv85yqk/

#### Actual behaviour

Unwanted '0' stack labels remain after the drill up event: https://jsfiddle.net/BlackLabel/t3j9wdoz/

**Comment by khlieng** [comment]
Fixed by #15616: https://jsfiddle.net/8Lngwc72/

**Comment by Basts** [comment]
@khlieng I wasn't able to find this one because I filtered out through the open issues 😄  Thanks!
