### ISSUE TITLE
chart options scrollablePlotArea not working when Chart is created using highstock.js

### ISSUE THREAD

**Issue by NielsHolt** [highcharts/highcharts#15676]
#### Expected behaviour
According to the documentation _"Highcharts is already included in Highcharts Stock, so it not necessary to load both."_
So creating a standard highchart using Highcharts Stock should work.

#### Actual behaviour
Using the **Highcharts**-package to creating a simple chart with `scrollablePlotArea`-options works fine: https://jsfiddle.net/NielsHolt/tygn239u/2/

When creating the exact same chart using the **Highcharts Stock**-package: https://jsfiddle.net/NielsHolt/v7bgzsyo/3/ 
The scrolling effect do _not_ work correct: The first part of the chart is not drawn

 

#### Live demo with steps to reproduce
Created with Highcharts: https://jsfiddle.net/NielsHolt/tygn239u/2/
Created with Highcharts Stock: https://jsfiddle.net/NielsHolt/v7bgzsyo/3/

#### Product version
9.1.0

#### Affected browser(s)
Tested in Chrome on Windows

**Comment by NielsHolt** [comment]
The problem disappear when setting options.series.clip = false (thanks to Karol Kołodziej :-))
I would propose that this info is added to the documentation.
Since it is not a code-issue I will close this Issue

**Comment by pawelfus** [comment]
Let me reopen this. It's great to hear that `clip=false` resolves the issue for you! However, both charts should look the same, without the need to set `clip=false` :)

**Comment by pawelfus** [comment]
Issue fixed in v9.3.0, where clip paths were refactored
