### ISSUE TITLE
Stacked column chart, click one, other column will become transparent. How to cancel this default behavior?

### ISSUE THREAD

**Issue by webpig** [highcharts/highcharts#15671]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/24989439/117402133-69069300-af38-11eb-9751-0d71c99f8506.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/24989439/117402178-80458080-af38-11eb-8652-07a84ec87608.png)

#### Live demo with steps to reproduce

https://jshare.com.cn/demos/hhhhDz
#### Product version

 "highcharts": "^9.0.1",
  "highcharts-vue": "^1.3.5",
#### Affected browser(s)
Chrome 90.0.4430.93

**Comment by khlieng** [comment]
Something like this?: https://jsfiddle.net/5ayLrq8x/2/

**Comment by webpig** [comment]
> Something like this?: https://jsfiddle.net/5ayLrq8x/2/

Thank you! It works perfectly!
