### ISSUE TITLE
> Hi @rishuSrivastava11hcl, are you able to provide a [jsFiddle](https://jsfiddle.net/) demo reproducing the issue for us to debug? I am not able to log in to the portal linked in the issue.

### ISSUE THREAD

**Issue by rishuSrivastava11hcl** [highcharts/highcharts#15675]
> Hi @rishuSrivastava11hcl, are you able to provide a [jsFiddle](https://jsfiddle.net/) demo reproducing the issue for us to debug? I am not able to log in to the portal linked in the issue.

![image](https://user-images.githubusercontent.com/72869551/117443012-299a6f80-af55-11eb-9853-4427df81b3a4.png)
 please observe the issue in above image.

Please reverify issue on below highcharts https://www.highcharts.com/demo/line-basic

_Originally posted by @rishuSrivastava11hcl in https://github.com/highcharts/highcharts/issues/14513#issuecomment-834286674_

**Comment by oysteinmoseng** [comment]
Closing this and reopening the other one for context

**Comment by rishuSrivastava11hcl** [comment]
okay
