### ISSUE TITLE
Type definition for SVGPathArray is not valid

### ISSUE THREAD

**Issue by udinkar** [highcharts/highcharts#15670]
**Issue:**
This type here - https://api.highcharts.com/class-reference/Highcharts#.SVGPathArray is not valid.
For instance renderer.path(['M', 10, 10, 'L', 30, 30, 'z']) is a valid statement.

However the type definition does not permit that path.

**Product Version:**
v9.1.0

**Effects:**
Typescript compilation errors

**Workaround:**
_path_ as any

**Comment by KacperMadej** [comment]
Hi @udinkar 

Thank you for reporting the problem.

This is by design. The way you see it as valid is working only thanks to backward compatibility.
The suggested and supported way is documented correctly.

**Comment by udinkar** [comment]
Hi @KacperMadej, thanks for getting back to me.
I believe the types should also be backward compatible if the implementation is.

**Comment by KacperMadej** [comment]
The old format is deprecated, not documented, and not supported fully (e.g. animation).
Implementation might be valid for internal usage, so not always perfectly reflects API documentation and the public TS definitions.
