### ISSUE TITLE
Function xAxis maxRange not working for mouse zoom out

### ISSUE THREAD

**Issue by PaulJaker** [highcharts/highcharts#15694]
#### Expected behaviour
If is set xAxis maxRange for 60days, then is expected the zoom out by mouse will not exceed this period.
But the zoom out is possible to see all datas.
Function maxRange not working for mouse zoom out in xAxis.

#### Actual behaviour
If is set xAxis maxRange for 60days, then the zoom out by mouse will not exceed this period.
Function maxRange working correctly only for navigator, there is not possible exceed this period.
Function minRange working correctly with mouse zoom in.

#### Live demo with steps to reproduce
https://jsfiddle.net/PaulJaker/mrgk5s19/127/

#### Product version
Highstock

#### Affected browser(s)
Google Chrome,Firefox

**Comment by KacperMadej** [comment]
Hi @PaulJaker 

Thank you for reporting the problem.

How exactly are you zooming out by mouse?
Which action via mouse is done to zoom out?

Is the problem about `rangeSelector` buttons being enabled?
You have force enabled them all through `allButtonsEnabled` and set them to never work if `maxRange` is followed, so I am not sure here what is the desired outcome when using those options like that. Please provide more info.

**Comment by PaulJaker** [comment]
Hello KacperMadej,

**How exactly are you zooming out by mouse?**
For zoom out, I just scrool middle button on mouse.

**Which action via mouse is done to zoom out?**
Just scroolin the middle button on mouse. There are no others actions or written code. 
For using zoom I use code below..
`mapNavigation: 
                                            {
                                                enabled: true,
                                                enableMouseWheelZoom: true,
                                                enableButtons: false
                                                
},`

Is the problem about rangeSelector buttons being enabled?
No, I tried to disable rangeSelector buttons,but zoom out still doesn't work.

**Comment by KacperMadej** [comment]
Thank you for explaining the problem - I get this now. I had to wrap my mind around the expected behavior from your first comment being a full description of the problem. In this case, this is a bug.

However, `maxRange` work as described in docs ("Maximum range which can be set using the navigator's handles. Opposite of xAxis.minRange.", so this is more like adding a new feature than fixing a bug.

**Comment by PaulJaker** [comment]
Maybe you are right.
But it make sense maxRange should work oposite as minRange as well.

**Comment by karolkolodziej** [comment]
_Internal note:_ 
Indeed the `maxRange` property is only being used in the `Navigator.ts` file.
```TS
        } else if (
            defined(maxRange) &&
            correctFloat(currentRange - pointRange) > (maxRange as any)
        ) {
            if (this.grabbedLeft) {
                pxMin = xAxis.toPixels(
                    newMax - (maxRange as any) - pointRange,
                    true
                );
            } else if (this.grabbedRight) {
                pxMax = xAxis.toPixels(
                    newMin + (maxRange as any) + pointRange,
                    true
                );
            }
        }
```

Right now I can see possible solutions on how to make it work. 
The implementation will depend on where this feature is going to be mostly used.
1. Add a scroll event to detect the changes and modify the navigator. Basic idea: https://jsfiddle.net/BlackLabel/nmedszbL/
2. Implement similar logic in the `mapZoom` method.
3. Move that part into the core. Perhaps in the `setExtremes`?
