### ISSUE TITLE
Error happened under development: Error "Highcharts is not defined" thrown when invalid HTML attributes are set under tooltip:pointFormatter

### ISSUE THREAD

**Issue by hojovi** [highcharts/highcharts#15698]
#### Expected behaviour
There should only be warning or error in console under development instead of throwing error when invalid HTML attributes are set under tooltip:pointFormatter

#### Actual behaviour
The application is broken under development when invalid HTML attributes are set under tooltip:pointFormatter

#### Screenshot
![image](https://user-images.githubusercontent.com/5494895/117738723-4ffb2c00-b22f-11eb-895a-139e26d53dc0.png)

Below is related code in my project (never mind on the code styling though, it's a demo project....):
![image](https://user-images.githubusercontent.com/5494895/117738275-3d342780-b22e-11eb-9733-66af5822674a.png)

#### Product version

Highcharts 9.1.0

#### Affected browser(s)
Chrome

By the way, it seems like we introduced related changes in this PR:  #15675, @KacperMadej could you help when there's chance? Thanks a lot! :)

**Comment by hojovi** [comment]
> Hi @hojovi
> 
> Thank you for reporting the problem.
> 
> If Highcharts are available as a global variable the code works correctly - there is a warning in the browser console. `Highcharts warning: Invalid attribute 'align' in config`
> 
> This could be resovled by adding attribute `align` like this:
> 
> ```js
> Highcharts.AST.allowedAttributes.push('align');
> ```
> 
> Demo: https://jsfiddle.net/BlackLabel/ug53tfhv/1/
> The above workaround prevents the error from showing so should work well, but in case it doesn't please create a live demo for your problem.
> 
> In short: This is a bug. In code we have access to the Highcharts instance and using global Highcharts doesn't work every time.
> Demo of the bug: https://jsfiddle.net/BlackLabel/ug53tfhv/2/

It does work, thank you for your quick reaction @KacperMadej !

**Comment by lexanth** [comment]
@TorsteinHonsi / @KacperMadej do you know when this fix might get released? It's turning warnings into crasher errors.

**Comment by TorsteinHonsi** [comment]
@lexanth I'm sorry for the inconvenience! We will publish a release ASAP.
