### ISSUE TITLE
Incorrect tick interval with flag series

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#15700]
#### Expected behaviour
Tick intervals should be of a day with flag series

#### Actual behaviour
Labels show intra day time as well

#### Live demo with steps to reproduce
https://jsfiddle.net/erq3wvg0/
Just commenting out the flag series type fixes the issue

While I know I can set tickInterval = 25 * 60 * 1000, this messes up things when the data is large. 
![image](https://user-images.githubusercontent.com/25079291/117780744-8a7bbd80-b25d-11eb-9ba1-e19964f65357.png)

Is there a better way to hide hours. `dateTimeLabelFormats.hour` does not seem to give expected result.

#### Product version
Highstock 9

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @govinda18 

For technical support see: https://www.highcharts.com/blog/support/

You could use `units` in `xAxis`.
Demo: https://jsfiddle.net/BlackLabel/m4d02Lt1/
API: https://api.highcharts.com/highstock/xAxis.units
