### ISSUE TITLE
Download PNG/JPEG Image options fail when using IE11 and color axis

### ISSUE THREAD

**Issue by Locutus83** [highcharts/highcharts#15714]
#### Expected behaviour
An image file should download

#### Actual behaviour
In the Dev console, the error appears:

`Error: Object doesn't support property or method 'getAnchorDelta'`

This error refers to line 93 of canvg.js

#### Live demo with steps to reproduce
This happens on your own demo site: https://www.highcharts.com/demo/maps/color-axis

1. Load the page
2. Launch the dev console
3. Click the menu (hamburger button)
4. Click "Download PNG image" or "Download JPEG image"

#### Product version
I would think your page is using 9.1.0. We get the issue in our app using 9.0.1.

#### Affected browser(s)
IE11

**Comment by KacperMadej** [comment]
Hi @Locutus83 

Thank you for reporting the problem.

_Internal note:_
Offline exporting module issue: 3rd party script - canvg.js - fails in IE11 when trying to export a chart.

**Comment by anirudhchronus** [comment]
@Locutus83 @KacperMadej any workaround for this?

**Comment by KacperMadej** [comment]
As a workaround, you could change the [libURL](https://api.highcharts.com/highcharts/exporting.libURL) to point to the location of libraries that are working correctly in IE11.

**Comment by Locutus83** [comment]
Since we are working to discontinue support for IE11 and this is a lesser-used feature for our users, we elected to remove those download options for IE11. Not ideal for all uses but it made sense for our use case.

**Comment by anirudhchronus** [comment]
@KacperMadej not working when i tried with  Client side exporting module for v9.0.1 with libURL:"https://code.highcharts.com/6.1.4/lib/ as other parts of the highcharts were in v.9.0.1. Am i missing something?

**Comment by KacperMadej** [comment]
The last working Highcharts version is 8.2.2 - you could use it as a workaround.

_Internal note:_
Regression since 9.0.0.
Error source: https://github.com/highcharts/highcharts/blob/5173e24250982257b4c83d0ef80b661af78dd49f/ts/Core/Renderer/SVG/TextBuilder.ts#L312-L316
Caused by: nested `tspan` elements. If `tspan` has a parent that is not `text` and set any `x` attr then the error and the fail happens. Is the nesting of `tspan` needed or is accidental and could be resolved? @TorsteinHonsi 

Nested `tspan`s look like this (2nd line):
```html
<text x="0" data-z-index="1" y="11" style="color:#FFFFFF;font-size:11px;font-weight:bold;fill:#FFFFFF;">
  <tspan class="highcharts-text-outline" ... style="">NJ<tspan x="0" y="11">&ZeroWidthSpace;</tspan>
  </tspan>NJ
</text>
```

**Comment by anirudhchronus** [comment]
@Locutus83 @KacperMadej we cant roll back to 8.2.2, Is there a work around for v9.0.1?

**Comment by TorsteinHonsi** [comment]
Thanks for your patience! We have fixed this in the above PR, will be published with the next release.

#### Workaround 1
The most obvious workaround is not not use `offline-exporting.js` and instead fall back to our online export server. Optionally remove `offline-exporting.js` only for IE11. See the docs for the [reasons to use offline exporting](https://www.highcharts.com/docs/export-module/client-side-export).

#### Workaround 2
This is the workaround that makes offline exporting work as announced.

1. Load the latest version of canvg in your page (Highcharts will pick it up from the global scope):
`<script src="https://unpkg.com/canvg@3.0.4/lib/umd.js"></script>`

2. Highcharts uses that canvg 2 API, so we need to add a compatibility snippet:
```js
CanvasRenderingContext2D.prototype.drawSvg = function (svg) {
    const v = window.canvg.Canvg.fromString(this, svg);
    v.start();
};
```
[View it live on jsFiddle](https://jsfiddle.net/highcharts/7f6c1ygk/). (Except JSFiddle doesn't support IE11 but at least you can see how it comes together).
