### ISSUE TITLE
Toggling from y axis logscale to linear: Missing points

### ISSUE THREAD

**Issue by vmlopezr** [highcharts/highcharts#15721]
#### Expected behaviour
When toggling a series that has y values < 0, log scale hides them. When toggling back to linear scale the hidden points should be visible again.

#### Actual behaviour

When toggling back to linear scale, the hidden points stay hidden.

#### Live demo with steps to reproduce

https://jsfiddle.net/o0sa7t2n/1/

Click on the log button to set to log scale, and click again to set to linear.
#### Product version

Latest
#### Affected browser(s)
Latest Firefox, Safari, Chrome

**Comment by KacperMadej** [comment]
Hi @vmlopezr 

Thank you for reporting the problem.

Logarithmic axis is too aggressive and permanently alters series data, so this type of toggling is removing the "illegal" (from the logarithmic axis point of view) points.

As a workaround, you could allow negative log - https://jsfiddle.net/BlackLabel/sdqhmzvt/
API original demo for reference:  https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/yaxis/type-log-negative/
Related API: https://api.highcharts.com/highcharts/xAxis.type

_Internal note:_
The points should not be removed permanently.
