### ISSUE TITLE
I18n: Thoundands Separator and Decimal Point cannot be changed

### ISSUE THREAD

**Issue by anoack93** [highcharts/highcharts#15747]
#### Expected behaviour

lang.thousandsSep and lang.decimalPoint chart options should be reflected in the chart number formatting.

#### Actual behaviour

No effect, thounsandsSep is always " " and decimalPoint "." (defaults)

#### Live demo with steps to reproduce

[https://jsfiddle.net/d6gckzf5/3/](https://jsfiddle.net/d6gckzf5/3/)

![Bildschirmfoto von 2021-05-19 11-36-14](https://user-images.githubusercontent.com/82465949/118791074-a94e0580-b896-11eb-9a0d-788174f5124a.png)

#### Product version

Highcharts JS v9.1.0

#### Affected browser(s)

* Chrome 90
* Firefox 88

**Comment by khlieng** [comment]
You need to set it with `Highcharts.setOptions` as mentioned in the [API docs](https://api.highcharts.com/highcharts/lang): https://jsfiddle.net/57y36gsj/

**Comment by anoack93** [comment]
Oh okay, I thought one can choose this option for each chart individually. Thank you for the quick answer.
I would suggest to log a warning to the user if he tries to set this options in the chart options.

**Comment by KacperMadej** [comment]
@anoack93 

> I would suggest to log a warning to the user if he tries to set this options in the chart options.

Usage of options outside of API is guarded in TS, so you would have to use some environment supporting TS like Angular.

If you would like an additional module for JS that could check all chart options and log / warn / error about bad usage of chart options please open a new feature request issue - https://github.com/highcharts/highcharts/issues/new?assignees=&labels=Type%3A+Feature+Request&template=feature_request.md&title=
