### ISSUE TITLE
Heatmap: setting select: true doesn't select the point

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#15746]
#### Expected behaviour
When defining the data, if you specify the `select: true` property for the point in the data array, the point should be selected initially. 

#### Actual behaviour
The given point isn't selected

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/mk5x4wL1/

#### Workaround
select the point in load event via

```js
events: {
	load: function () {
		this.series[0].points[index].select();
	}
}
```
https://jsfiddle.net/BlackLabel/8dgu7vhz/

#### Product version
v9.1.0

#### Affected browser(s)
all

**Comment by khlieng** [comment]
It should be `selected: true` but it still doesnt work properly.
