### ISSUE TITLE
When set tooltip pointerEvents：'all', point's click event not triggered.Mobile.

### ISSUE THREAD

**Issue by webpig** [highcharts/highcharts#15745]
#### Expected behaviour
point's event is work!

#### Actual behaviour
tooltip set pointerEvents：'all', point's click event not triggered.

#### Product version

"highcharts": "^9.0.1",
"highcharts-vue": "^1.3.5",
#### Affected browser(s)
Chrome 90.0.4430.93
iphone, mobile

**Comment by webpig** [comment]
> #### Expected behaviour
> point's event is work!
> 
> #### Actual behaviour
> tooltip set pointerEvents：'all', point's click event not triggered.
> 
> #### Live demo with steps to reproduce
> #### Product version
> "highcharts": "^9.0.1",
> "highcharts-vue": "^1.3.5",
> 
> #### Affected browser(s)
> Chrome 90.0.4430.93

**Comment by raf18seb** [comment]
Hi @webpig!
Could you explain your issue more precisely? An online demo with steps to reproduce would be perfect.

If you are not sure whether this is a bug, you should use our dedicated support channels, more info: https://www.highcharts.com/blog/support/

**Comment by webpig** [comment]
> Hi @webpig!
> Could you explain your issue more precisely? An online demo with steps to reproduce would be perfect.
> 
> If you are not sure whether this is a bug, you should use our dedicated support channels, more info: https://www.highcharts.com/blog/support/

Sorry, I should provide a demo.
