### ISSUE TITLE
Heatmap borderRadius

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#15757]
#### Expected behaviour
Apply `borderRadius` to the `heatmap` series and update the API.

#### Actual behaviour
In [heatmap API](https://api.highcharts.com/highcharts/series.heatmap) the `borderRadius` property isn't listed.
However, in version 8.2.0 it worked properly. 

Workaround: https://jsfiddle.net/BlackLabel/tphydk24/

#### Live demo with steps to reproduce
8.2.0: https://jsfiddle.net/u2qn3e87/
8.2.2 and higher : https://jsfiddle.net/u3kfmsLb/

#### Product version
 Highcharts JS v9.1.0 (2021-05-03)

#### Affected browser(s)
All

**Comment by khlieng** [comment]
Caused by #12508 in 8.1.0.
