### ISSUE TITLE
Heatmap does not render properly when generated using update method

### ISSUE THREAD

**Issue by alexboss** [highcharts/highcharts#15756]
#### Expected behaviour
Heatmap loads fine when generated using `update`.

#### Actual behaviour
Heatmap loads title. And then JS error `highcharts.src.js:18376:16`
```
Uncaught TypeError: d.options[this.coll] is undefined
    update highcharts.src.js:18376
    update heatmap.src.js:673
    update highcharts.src.js:31681
    update highcharts.src.js:31680
    <anonymous> (index):157
```

#### Live demo with steps to reproduce
HC 9.1.0: https://jsfiddle.net/oeqwf9rn/1/ (❌ KO)
HC master (@ 19/05/2021): https://jsfiddle.net/2c1zraw9/ (✔️ OK)

#### Product version
Highcharts 9.1.0

#### Affected browser(s)

Mozilla Firefox (78.10.0esr (64-bit))

#### Extra information

It works fine with latest version in master, however, wanted to report this just in case someone has the same issue OR it has other implications somewhere else.

**Comment by khlieng** [comment]
Fixed by #15658.
