### ISSUE TITLE
The arearange series isn't working in parallel coordinates

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#15752]
#### Expected behaviour
Let's consider this arearange data:
```js
data: [
      [23, 25],
      [-1, -0.5],
      [1.5, 4],
      [1.5, 5],
      [4, 5]
]
```
The arearange series should be displayed like this:

![image](https://user-images.githubusercontent.com/23310742/118816595-a103c380-b8b2-11eb-8f6c-0c6b5c781d6f.png)

#### Actual behaviour
With the above data, the arearange series is displayed incorrectly:
![image](https://user-images.githubusercontent.com/23310742/118816693-ba0c7480-b8b2-11eb-988c-dc9461f6d62c.png)

To display it correctly, we need to correct the data - calculate the `high` value based on the first yAxis scale:
```js
data: [
      [23, 25],
      [-1, 23.5],
      [1.5, 25],
      [1.5, 26],
      [4, 24]
]
```

#### Live demo with steps to reproduce
Real data, not working: https://jsfiddle.net/BlackLabel/qobuj3tp/
Corrected data, but obviously it shouldn't work like that: https://jsfiddle.net/BlackLabel/kmgh8fad/

#### Product version
Highcharts 9.1.0

**Comment by karolkolodziej** [comment]
To make it fully bullet prove you have to make sure that each chart's axis is going to look exactly the same.
Especially you have to make sure that it is going to have the same ticks by for example setting a fixed `tickAmout` or even `ticksPositions`.
As you can see from the screens above the RotB axis has a max of 15 in the first case and 12 in the second.

Demo: https://jsfiddle.net/BlackLabel/czusb1q8/

**Comment by cfarmerga** [comment]
Hmm.  This example doesn't seem to work well.  The RotB axis looks correct, that's true, but other axes' arearanges are off now.  I'd like to to be able to draw accurate arearanges for any arbitrary number of axes and axis min/max ranges.  I would be ok with using a common tickAmount if needed, but this example doesn't seem sufficient to solve that.

![image](https://user-images.githubusercontent.com/341051/179760609-bcc6b274-6f28-437b-adcc-6e4c4fcd16fc.png)
