### ISSUE TITLE
Error when namespacing Highcharts

### ISSUE THREAD

**Issue by nhorvath** [highcharts/highcharts#15764]
#### Expected behaviour
There are no errors if Highcharts does not exist in window.

#### Actual behaviour
There is an error generated by this line from highcharts.src.js when highcharts is not in global namespace and a highcharts error/warning such as dates out of order happens
```
            fireEvent(Highcharts, 'displayError', { chart: chart, code: code, message: message, params: params }, defaultHandler);
```
In this function Highcharts is scoped to H so changing it to 
```
            fireEvent(H, 'displayError', { chart: chart, code: code, message: message, params: params }, defaultHandler);
```
resolves the issue.

#### Live demo with steps to reproduce

https://jsfiddle.net/h2dcLjst/

#### Product version

Highcharts 9.1.0

#### Affected browser(s)
all

**Comment by khlieng** [comment]
Fixed on master (#15702).
