### ISSUE TITLE
Plot line label extends past the plot area into chart area

### ISSUE THREAD

**Issue by drssoccer55** [highcharts/highcharts#15777]
#### Expected behaviour
Since the plot line is cut off at the plot area I would expect that the label text should also get cut off in the plot area

#### Actual behaviour
![image](https://user-images.githubusercontent.com/23265878/119420247-e2c8ab80-bcb0-11eb-88d6-0181478a4c5c.png)

#### Live demo with steps to reproduce
[https://jsfiddle.net/3uy672o4/](https://jsfiddle.net/3uy672o4/)

#### Product version
Highcharts JS v9.1.0

#### Affected browser(s)
Tested Firefox/Chrome. Probably all browsers.

**Comment by KacperMadej** [comment]
Hi @drssoccer55 

Thank you for reporting the problem.

The label is currently not clipped in any way.
