### ISSUE TITLE
Error when try to generate histogram with empty array data and no title

### ISSUE THREAD

**Issue by gmerciel** [highcharts/highcharts#15776]
#### Expected behaviour
Chart should generate even if data array is empty regardless the title definition.

#### Actual behaviour
There is error thrown in console, when trying to create the chart with histogram series, and an empty data array is passed through baseSeries's configuration. This only happens if you also set title option to null. If you specify a title (or the default options are left) it works. And if you set title to null, but put a non-empty array in data, it also works as expected (no title is displayed)

#### Live demo with steps to reproduce
https://jsfiddle.net/Lkqmzesw/

#### Product version
Highcharts 9.1.0

#### Affected browser(s)
All

#### Workaround
As a workaround, you can configure a non-empty array as data and set it back to an empty array after the chart is created:

https://jsfiddle.net/nksrL541/

**Comment by KacperMadej** [comment]
Hi @gmerciel 

Thank you for reporting the problem.

`null` is not a valid option for `title`. Most of the time nothing happens, but for some series (e.g. that require additional computation and trigger some updates during the chart's load) this ends with an error and the chart is not rendered at all.

To disable the title set its `text` to an empty string - https://jsfiddle.net/BlackLabel/fa2gjou0/1/

**Comment by gmerciel** [comment]
Thanks! I've been wrongly using null for title for years 😋
