### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pos' of undefined     at highstock.src.js:9 (Combination Chart)

### ISSUE THREAD

**Issue by Anudeep-Kadavergu** [highcharts/highcharts#15774]
#### Expected behaviour
Show tooltip when hovered on point

#### Actual behaviour
Giving error 'pos; of undefined, tooltip is showing as usual

#### Live demo with steps to reproduce
[Live Demo ](https://jsfiddle.net/Anudeep001/h2wckjpb/20/)

#### Product version
 Highstock Latest

**Comment by raf18seb** [comment]
Duplicate of https://github.com/highcharts/highcharts/issues/13868
