### ISSUE TITLE
HighStock multiple yAxis label/legen overlaps and narrows the view

### ISSUE THREAD

**Issue by nickwinger** [highcharts/highcharts#15772]
#### Expected behaviour
The label/legend of the multiple yAxis should not overlap and therefore narrow down the view

#### Actual behaviour
The top/bottom legend/title of the yAxis overlap and therefore the view gets narrowed.
A workaround to make some space inside should be done by the framework and not by the user.
if i set 2 axix with 50% i expect that the highcharts framework knows what i want and does not overlap the legend/title
and narrow down the view, the should stay inside the 50% limit...

#### Live demo with steps to reproduce
<img width="670" alt="image" src="https://user-images.githubusercontent.com/9943675/119149541-e8728700-ba4d-11eb-9bbd-3b60a24be9c5.png">

#### Product version

latest

**Comment by KacperMadej** [comment]
Hi @nickwinger 

Please add a live demo for the problem.

You could disable first or last labels and set offset to 0 for the yAxes.
Some related API references:
https://api.highcharts.com/highstock/yAxis.showFirstLabel
https://api.highcharts.com/highstock/yAxis.showLastLabel
https://api.highcharts.com/highstock/yAxis.offset

**Comment by nickwinger** [comment]
Hello @KacperMadej ,

here is a demo:
https://stackblitz.com/edit/ionic-v4-angular-tabs-6hddw4?file=src/app/tab1/tab1.page.ts

You workaround certainly works kinda, but i think it's not good, because:
1. The Highcharts-Framework should handle that by himself (i guess no one wants to shrink down the chart and create whitespace)
2. leaving the first and last label reduces information quiet a bit

In my opinion there should be an option, "stay inside contraints", meaning the axis labels should not exceed their height
(in best case also have some padding so that the last label of the first chart and the first label of the second chart have some space)
This is what the user wants i guess.
If not an extra option then maybe just check if the last and first label of 2 charts are overlapping, if so don't go outside but just move the labels closer to another so that they all stay in their constraint height.

**Comment by KacperMadej** [comment]
The axis labels placement has an already open issue that you could vote on by thumbs-up reaction: https://github.com/highcharts/highcharts/issues/13573

Highcharts doesn't handle this by itself, for now, so let's keep this issue open as a feature request.
