### ISSUE TITLE
NVDA/Narrator is not reading all the information present in tooltip of a chart

### ISSUE THREAD

**Issue by GayatriDeviP** [highcharts/highcharts#15780]
#### Expected behaviour
Narrator/NVDA should read all the tooltip information displayed.

#### Actual behaviour
Narrator/NVDA is not reading the all the information present in tooltip of a chart

#### Live demo with steps to reproduce
step1: open https://jsfiddle.net/ohdyxms1/7/
step2: Turn on the Screen Reader(Narrator for edge / NVDA for chrome), Navigate using tab.
step3: It receives focus on the bar and tooltip appears. 
step4: It reads only header and first line of tooltip.

#### Product version
Highcharts lastest version

#### Affected browser(s)
chrome, edge

**Comment by GayatriDeviP** [comment]
It is observed that if there is only 1 bar in the chart , screen readers are reading the tooltip information line by line by pressing down arrow. Please check here https://jsfiddle.net/ohdyxms1/14/

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

**Comment by oysteinmoseng** [comment]
We need better handling of stacks and shared tooltips.

For now, here is a workaround where all of the point descriptions are merged into the first series, and the latter series are hidden from AT. https://jsfiddle.net/j8spfdx7/
