### ISSUE TITLE
Hanburger exporting menu not visible.

### ISSUE THREAD

**Issue by YannEsker** [highcharts/highcharts#15782]
Hello

Issuing HighCharts Map, if exporting menu is left align with map navigation enabled. the exporting button is not visible if there is no title.

A workaround is to move the navigation menu.

"mapNavigation": {
    "enabled": true,
    "buttons": {
      "zoomIn": {
        "y": 33
      },
      "zoomOut": {
        "y": 60
      }
    }

#### Product version
Highmaps 9.0.1

#### Affected browser(s)
Chrome at least.

**Comment by KacperMadej** [comment]
Hi @YannEsker 

Please add a live demo for the problem.

**Comment by KacperMadej** [comment]
Demo: https://jsfiddle.net/BlackLabel/2zey9Lgu/
Workaround applied: https://jsfiddle.net/BlackLabel/2zey9Lgu/1/
