### ISSUE TITLE
LinkedTo issue with reversed Y axis

### ISSUE THREAD

**Issue by Blaster69** [highcharts/highcharts#15781]
#### Expected behaviour
Double bar charts, with a reversed Y-axis on the left side, a standard Y-axis on the right side and X axis moved to the center. To keep the scale on both Y axis, the Y axis on the right side is linked to the other Y axis on the left side (which always has the maximum values).
(expected result available in the codepen)

#### Actual behaviour
The Y axis on the right side is also reversed: apparently, the linkedTo not only has the effect of linking the extremes, but it also links the reversed state of the first Y axis to the second, causing the second axis to be reversed, and therefore misplaced. Moreover, the second Y axis is sometimes not drawn (your mileage may vary), but a simple chart.redraw() always fix it.
(current result available in the codepen)

#### Live demo with steps to reproduce
https://codepen.io/dengeral/full/wvBGGLg

#### Product version
Highcharts

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @Blaster69 

Thank you for reporting the problem and providing a workaround.

**Comment by dgervalle** [comment]
Hi @KacperMadej,

I wrote the liked Codepen.

I would not consider the very dirty way we actually patch the offending function an acceptable workaround. It's just an acceptable way to demonstrate the issue, no more. FYI, the patch work only with a given minimized version and is absolutely not generic.

So, the status of this issue is not appropriate.
Sorry if this was confusing.

**Comment by raf18seb** [comment]
Hi @dgervalle and @Blaster69,

You could also use a simpler way to synchronize extremes between your y-axes (without using `linkedTo`): https://jsfiddle.net/BlackLabel/pfwqt70r/
```js
chart: {
  type: 'bar',
  events: {
    load: function() {
      this.yAxis[0].setExtremes(this.yAxis[1].min, this.yAxis[1].max, null, false);
    }
  }
},
```

**Comment by dgervalle** [comment]
Hi @raf18seb ,

I know I am reacting late on this, I am sorry to only say thank you today for your proposed workaround which was indeed working perfectly until version 11.3.0 of Highcharts (see https://codepen.io/dengeral/pen/VYPBjmy)

From that version, you need to use true in place of null as the third argument to setExtremes to keep it working (see https://codepen.io/dengeral/pen/GgrBqOY)

Using LinkedTo has still the same issue in version 13.0.0, see https://codepen.io/dengeral/pen/yygqJaL

Anyway, late thanks for your suggestion, which is still working with a minor change.
