### ISSUE TITLE
Illogical behavior when setting minRange 

### ISSUE THREAD

**Issue by NielsHolt** [highcharts/highcharts#15793]
#### Expected behavior
Demo 1: min-range on y-axis = 300. Data range 54-216 => Expected y-axis range of 0 to 300 or 50 to 350 or similar 
Demo 2: min-range on y-axis = 300. Data range 1-216 => Expected y-axis range of 0 to 300 or -50 to 250

#### Actual behavior
Demo 1 with the smallest data-range gets a y-axis range of 0-400
Demo 2 with the largest data-range gets  a y-axis range of 0-300

It is illogical that a smaller data-range result in a larger y-axis range

#### Live demo with steps to reproduce
Demo 1: https://jsfiddle.net/NielsHolt/4L50rte8/11/
Demo 2: https://jsfiddle.net/BlackLabel/kh65begw/

#### Product version
9

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @NielsHolt 

Thank you for contacting us about the problem.

Other options like startOnTick, endOnTick, and default tick placement (on even numbers) are also affecting the axis range.
With a smaller data range ticks are calculated differently, but as long as all setting options are respected I see no reason to report this as a bug.

Even when the data range is 0 you could get an axis range of 500 for `minRange:300` and this is also following all set options: https://jsfiddle.net/BlackLabel/x062qwca/

The minRange is respected in both your demos, so there is no bug here.
For technical support see https://www.highcharts.com/blog/support/
