### ISSUE TITLE
Ellipsis dataLabels hover shows web browser's native tooltip

### ISSUE THREAD

**Issue by maciejklocek** [highcharts/highcharts#15795]
#### Expected behaviour
When` dataLabels.style.textOverflow= 'ellipsis'` dottet too long labels it should have only one tooltip - higchart's tooltip. Browser's native tooltip  shouldn't appear.

#### Actual behaviour 
The long dataLabels have two tooltips - one from higcharts lib, which it's ok and second tooltip web browser's native.
Its caused by HTML `<title>` generated in DOM for ellipsis text inside highcharts

![image](https://user-images.githubusercontent.com/25222556/119664326-82ae4280-be33-11eb-8c15-78c5e44f2a6f.png)

#### Live demo with steps to reproduce
1. hover on dotted label
2. wait for a second until browser's tooltip appear
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/pie-datalabels-overflow/

#### Product version
Highcharts 7.2.2

#### Affected browser(s)
Chrome, Firefox and probably others.

**Comment by KacperMadej** [comment]
Hi @maciejklocek 

Thank you for reporting the problem.

Disabling `title` attribute should be an option to avoid duplicated tooltip.
