### ISSUE TITLE
Pie Chart DataLabels Getting Cut Off

### ISSUE THREAD

**Issue by mm-gmbd** [highcharts/highcharts#1581]
Pie Chart container does not account for position of data labels - they get cut off sometimes. Modified the original pie chart example to just two browsers, both data labels cut off.

Example: http://jsfiddle.net/aZ9VA/1/

Apologies if this has already been fixed (I've searched through references to "Pie Chart" in the issues and found related issues, but not specifically the data labels).

**Comment by skoub** [comment]
It doesn't seams to be solved yet: http://jsfiddle.net/9g030veq/1/

If i add the dataLabels width, it's better but labels can be stacked between them: http://jsfiddle.net/9g030veq/2/

**Comment by BackSik** [comment]
skoub, have a same problem
http://prntscr.com/6lwadr here i turn on visualize the slots where allocate labels. Have overlaping labels at left-bottom corner. Why slots have a different height at left and right side?
i try branch "rambera"  and see this http://prntscr.com/6lwca6. Here have a good position of labels, but something wrong with labelConnectors and chart sectors.
I think this method of positioning labels is unsuccessful, need to find other algorithm, or upgrade this.

**Comment by BackSik** [comment]
skoub, have a same problem
http://prntscr.com/6lwadr here i turn on visualize the slots where allocate labels. Have overlaping labels at left-bottom corner. Why slots have a different height at left and right side?
i try branch "rambera"  and see this http://prntscr.com/6lwca6. Here have a good position of labels, but something wrong with labelConnectors and chart sectors.
I think this method of positioning labels is unsuccessful, need to find other algorithm, or upgrade this.

**Comment by highslide-software** [comment]
> I think this method of positioning labels is unsuccessful

The ideal algorithm takes each label's height into consideration and reserves space for that. It should be as generic as possible, and could also be reused for Highstock flags and general data labels. Here are the requirements:

* Start out with a length, say the space available is from 0 to 1000.
* Start out with a set of bounding boxes, like { x: 120, width: 20} and { x: 390, width: 120}
* Each bounding box has a preferred position. In the case of the pie, this is directly outside the pie slice.
* The algorithm will detect collision, and move objects away from nearby objects if necessary.
* If it runs out of space, the boxes with lowest rank should be removed. Rank can be set on the object.

See also #2630.

**Comment by Silviusconcept** [comment]
:+1:

**Comment by llincoln** [comment]
This might help someone. I was having this same issue on smaller screens e.g iPad so a work around for me was to specify the distance for the connector:
`...
dataLabels: {
     distance: 10,
}`

**Comment by fahamk** [comment]
Using d3pie my solution was to increase "canvasWidth" until my words fit
