### ISSUE TITLE
Two zones with dotstyle

### ISSUE THREAD

**Issue by Sgajjar08** [highcharts/highcharts#15838]
#### Expected behaviour
I want to add two different colour dot style zones for the same axis.

#### Actual behaviour
When I try to get it it's overlapping with the same colour.

#### Live demo with steps to reproduce
https://jsfiddle.net/65czhn7b

#### Product version
Highchart => 7.2.0

**Comment by KacperMadej** [comment]
Hi @Sgajjar08 ,

Zones needs to have values defined so Highcharts will "know" where to draw them - https://jsfiddle.net/BlackLabel/ztg6ob2u/

This is not a bug but rather a support question - for technical support see  https://www.highcharts.com/blog/support/
