### ISSUE TITLE
Dynamic candle update does not update color

### ISSUE THREAD

**Issue by otsybulsky** [highcharts/highcharts#15849]
#### Expected behaviour
A red candle (open >= close) should be filled with red color.

#### Actual behaviour
 I have a problem with mass updating of chart. Sometimes some candles are filled with the wrong color (green instead of red).

#### Live demo with steps to reproduce
I was able to reproduce this here: http://jsfiddle.net/otsybulsky/6L8t7g1y/ Just press the button "Swap". 

#### Product version
Highcharts 9.1.0

#### Affected browser(s)
All

**Comment by otsybulsky** [comment]
I`m trying 9.1.2 version.  The bug is still present. Maybe this happens when updating the current candle?
![2021-06-18_14-05-32](https://user-images.githubusercontent.com/34866613/122552611-34a9ea80-d03f-11eb-9b1e-f49d36e8859f.png)

**Comment by khlieng** [comment]
The fix did not make it into 9.1.2.

**Comment by otsybulsky** [comment]
https://github.com/highcharts/highcharts/compare/v9.1.2...master  There is #15849. Did I misunderstand something?

**Comment by khlieng** [comment]
Yes, those are the changes that have happened on master after 9.1.2 got released. https://github.com/highcharts/highcharts/compare/v9.1.1...v9.1.2 would be the 9.1.2 commits.

**Comment by otsybulsky** [comment]
If this was not fixed, why was the issue closed?

**Comment by khlieng** [comment]
It gets closed when the fix gets merged into master, since theres nothing more to do with it at that point. And the fix will be available when the next release happens.

**Comment by otsybulsky** [comment]
ok, thank you for help.
