### ISSUE TITLE
Unable to update networkgraph options

### ISSUE THREAD

**Issue by w99910** [highcharts/highcharts#15846]
#### Expected behaviour
I was expecting to change the `enableSimulation` options of **networkgraph** chart by clicking button.

#### Actual behaviour
But the update doesn't effect the chart. The simulation is still disable.

#### Live demo with steps to reproduce

[https://codepen.io/w99910/pen/bGqGpyp](https://codepen.io/w99910/pen/bGqGpyp)
#### Product version

 `"highcharts": "^9.1.0",`

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment]
Hi @w99910!

Are you looking for something like this? https://jsfiddle.net/BlackLabel/d3wfc01u/

**Comment by w99910** [comment]
@raf18seb Oh I thought it was a bug. That's what I'm looking for. Thanks a lot :D
