### ISSUE TITLE
x-axis labels don't rescale correctly when chart is minimized then expanded

### ISSUE THREAD

**Issue by clemzio** [highcharts/highcharts#1584]
(Tried with Highcharts 2.x and 3.0)

Here is a demo showing the problem:

http://jsfiddle.net/DmWdq/

First reduce the chart width by reducing the window's size. You should see hyphens added to the labels "Programming is fun". Then just increase the chart width to its initial state, you'll see that hyphens are not removed and that the width of the label container doesn't scale correctly.

![step1](https://f.cloud.github.com/assets/359716/245123/5a8a5bd4-8a77-11e2-9bfe-beebf9ab786b.png)
![step2](https://f.cloud.github.com/assets/359716/245122/5a8d8dd6-8a77-11e2-807b-f2fac0528358.png)
![step3](https://f.cloud.github.com/assets/359716/245124/5b230866-8a77-11e2-992b-1d8da08ee610.png)

**Comment by oysteinmoseng** [comment]
While the original issue might not be as relevant with current logic, xAxis labels still struggle with resizing, particularly when `useHTML` is enabled: http://jsfiddle.net/sc2v1s4e/

**Comment by TorsteinHonsi** [comment]
Works well now
