### ISSUE TITLE
Cannot access custom values in split tooltip formatter of StockChart

### ISSUE THREAD

**Issue by finnhvman** [highcharts/highcharts#15848]
#### Expected behaviour
Acccess custom value(s) by key within tooltip formatter function on the `this.points[0]` object. E.g. if keys are `[ 'x', 'y', 'comment' ]`, then access comment value by `this.points[0].comment`.

#### Actual behaviour
`this.points[0].comment` is undefined when the tooltip is split. If tooltip is not split `this.point.comment` returns the cutom value.

#### Live demo with steps to reproduce
https://jsfiddle.net/vhz17ju9/

#### Product version
Highstock 9.1.1

#### Affected browser(s)
All

**Comment by khlieng** [comment]
You can access the full point at `this.points[0].point`: https://jsfiddle.net/2n5dvb49/

**Comment by finnhvman** [comment]
Indeed, thanks!
