### ISSUE TITLE
Remains zoom area after using download with exporting.

### ISSUE THREAD

**Issue by hihajdus** [highcharts/highcharts#15845]
#### Expected behaviour
The zoom area should disappear after downloading the chart image by exporting.

#### Actual behaviour
The zoom area remains after download the chart image.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/rn35bud0/

#### Product version
Highcharts JS v9.1.1 (2021-06-03)

#### Affected browser(s)
All

**Comment by bre1470** [comment]
Oh no, what a typo... Thanks for fixing @khlieng! 😅
