### ISSUE TITLE
Heatmap title overlaps plotArea 

### ISSUE THREAD

**Issue by ZeroX-DG** [highcharts/highcharts#15854]
#### Expected behaviour

The title should push the plotArea down not overlapping it.

#### Actual behaviour

When a title contains line break or it's too long and highcharts have to wrap it. The title ended up overlapping the graph instead of pushing it down. This only happen on heatmap.
![image](https://user-images.githubusercontent.com/12984316/121120869-8fd72280-c872-11eb-92c2-16f913ddfebe.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/f6yupoxh/

#### Product version
Highcharts JS v9.1.1 (2021-06-03)

#### Affected browser(s)
Chrome

**Comment by khlieng** [comment]
You can fix this by not setting `chart.marginTop`: https://jsfiddle.net/w9r6zt5a/

**Comment by ZeroX-DG** [comment]
@khlieng You're right! I forgot to check for the margin. Thanks!
