### ISSUE TITLE
Chart is distorted with xAxis ordinal false and unsorted data series with missing months data

### ISSUE THREAD

**Issue by ff-sgupta** [highcharts/highcharts#15855]
#### Actual behaviour
Chart is distored with following data:

1. xaxis ordinal set to false
2. data series is not sorted
3. missing data for few months

JS fiddle: https://jsfiddle.net/g0jps75u/

Analysis: if we sort the data series based on xaxis the chart works fine. Setting ordinal to true does not solve the issue completely as the xaxis is not displaying all the months

#### Expected behaviour
chart shoud be like the one here https://jsfiddle.net/g0jps75u/1/ . The only change here is that the first series data is sorted,
Please click on "All" in the range selector

#### Product version
Highstock JS v6.1.1 (2018-06-27)

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi @ff-sgupta

Highcharts requires data to be sorted. If you check the developer console, you will see the "error 15" warning.
All you need to do is to pre-sort the data.
