### ISSUE TITLE
Weird Behavior When Implementing dataSorting with legendItemClick

### ISSUE THREAD

**Issue by abhoward** [highcharts/highcharts#15853]
#### Expected behaviour
Expecting categories to sort with data after clicking on legend item for multiple series.

#### Actual behaviour
Categories do not sort along with data for the second series after initially being sorted correctly.

#### Live demo with steps to reproduce
Example: https://jsfiddle.net/h4a2zjf7/

Steps to reproduce - click on the legend items in the following order:
1. Bananas
2. Bananas
3. Apples
4. Apples
5. Bananas

#### Product version
Highcharts 9.1.1

#### Affected browser(s)
Discovered and tested in Google Chrome Version 91.0.4472.77

**Comment by raf18seb** [comment]
Hi @abhoward!

Are you sure this is a Highcharts core bug? We use GitHub to track bugs only.
In case of any support questions, please contact us on other dedicated support channels: https://www.highcharts.com/blog/support/

I am closing the ticket here. Thanks for understanding.

**Comment by abhoward** [comment]
Hi raf!

I actually did about about this on the forum first and was directed here. You can see my post [here](https://www.highcharts.com/forum/viewtopic.php?f=9&t=46706&p=167651#p167587).

With that said, I'm not confident enough in my utilization of the dataSorting feature to 100% declare this as a bug, but I haven't been able to find an appropriate solution, and the behavior is definitely unintentional. If there's a better place for these kinds of posts I'd be more than happy to post there, but I would like for this to be reopened (if possible) if it is indeed a bug.

Thanks!

**Comment by KacperMadej** [comment]
Looks like a bug as the used options seem correct and based on API - not sure why this happens.

_Internal note:_
Initial debugging doesn't show anything useful for me - might require a deeper dive.
