### ISSUE TITLE
[Gantt] bug with filling task execution

### ISSUE THREAD

**Issue by KrullCepush** [highcharts/highcharts#15859]
when entering the minimum width, there is a problem with the filling of the problem

#### Expected behaviour
the task will be covered depending on the percentage of completion

#### Actual behaviour
the task is filled at will

#### Live demo with steps to reproduce
https://jsfiddle.net/am42z5x6/

#### Product version
"highcharts": "^9.1.0",

#### Affected browser(s)
All browsers

**Comment by raf18seb** [comment]
Hi @KrullCepush, thank you for reporting the issue.

Internal note: completed fill should follow the minPointLenght width as well.
![image](https://user-images.githubusercontent.com/23310742/122055067-899ff380-cde8-11eb-9a99-142b3f176f6e.png)


Simplified demo: https://jsfiddle.net/BlackLabel/7du0na2j/ (decrease the chart's width so the blue point is 200px width long).
