### ISSUE TITLE
Reset Zoom button issues on Surface Pro

### ISSUE THREAD

**Issue by melanki** [highcharts/highcharts#15866]
#### Expected behaviour
Reset Zoom using Touch

#### Actual behaviour
Only works with keyboard & mouse.
Reset zoom button is shown even when doing a pan action

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/cbenm7kt/

#### Product version
Highcharts 9.1

#### Affected browser(s)
Windows 10 w. latest **Edge** browser

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

The issue is also happening in native iOS/Safari and Chrome/Mac, so it is a general touch issue.

Steps to reproduce
* Open https://jsfiddle.net/BlackLabel/cbenm7kt/ in Chrome
* In the developer tools, enable mobile preview in the Device Toolbar
* Pan left

**Comment by khlieng** [comment]
@melanki is the issue here also not being able to reset the zoom using touch or is it just the button showing after panning?

**Comment by melanki** [comment]
> We are unable to click the reset zoom button in Surface Pro touch pad, using the touch action.
> Only when external keyboard or mouse is attached to the Surface Pro, we are able to click the reset zoom button.
> Could you please check the same and update the reason?

> The issue persists at our end still on the surface pro device alone. (Other touch devices are working fine)
> Also, in surface pro alone Reset zoom button is shown even when doing a pan action.

@khlieng Will ask customer to provide more information in this thread.

**Comment by kamineel** [comment]
> @melanki is the issue here also not being able to reset the zoom using touch or is it just the button showing after panning?

Yes. Unable to use reset zoom button in surface pro using touch screen. It works fine when keyboard is attached to surface pro.
