### ISSUE TITLE
Issue exporting XLS from the graphs gives warning message in Excel

### ISSUE THREAD

**Issue by rignaldspan** [highcharts/highcharts#15861]
We are implementing the new highcharts 9 and have a question about the export to Excel.
Also in your demo we see that it happens and we get this message.
![image](https://user-images.githubusercontent.com/85559297/121182256-2f8cb480-c863-11eb-8166-ffefd908df70.png)

#### Expected behaviour
Open Excel directly without the box

#### Actual behaviour
https://www.highcharts.com/demo/line-basic
Select Download XLS from the graphmenu and it will open Excel with the message

![image](https://user-images.githubusercontent.com/85559297/121180812-8b563e00-c861-11eb-8e12-d7242db4764f.png)

**Comment by raf18seb** [comment]
Hi @rignaldspan,

this is a known issue. Please find more info here: https://github.com/highcharts/highcharts/issues/14239
