### ISSUE TITLE
Navigator and rangeSelector in 9.1.1 different from 9.1.0

### ISSUE THREAD

**Issue by HansR00** [highcharts/highcharts#15864]
#### Expected behaviour
When selected one  of the ranges I expect the range in the navigator to be selected on the right

#### Actual behaviour
It is selected on the left so the first part of the navigator is selected iso the last part.

#### Live demo with steps to reproduce
Explanation and jsFiddle can be seen here: https://www.highcharts.com/forum/viewtopic.php?f=12&t=46704#p167638

#### Product version
9.1.1

#### Affected browser(s)
All

**Comment by khlieng** [comment]
#15615 @karolkolodziej
