### ISSUE TITLE
Indicator series linked to multiple base series

### ISSUE THREAD

**Issue by KrishnaKumarHariprasannan** [highcharts/highcharts#15881]
# Description of the feature

With the existing capabilities of Indicators, it is possible to link an indicator series with only one other series. For use-cases such as creating the arithmetic difference between two series requires access to those linked series. Can we please add in this feature of linking an indicator series to more than one base/parent series?

# Library related to the feature

Highcharts Stock 

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by raf18seb** [comment]
Hi @KrishnaKumarHariprasannan, thanks for creating the ticket.

None of our indicators use 2 (or more) separate series to calculate values yet. When implementing a custom indicator for the arithmetic difference between two series only, you can add a simple custom logic that would find the second series (e.g. using the `chart.get()` method): https://jsfiddle.net/BlackLabel/pcuo67Lm/
