### ISSUE TITLE
Solid Gauge - Remove and add plotband

### ISSUE THREAD

**Issue by guldevec** [highcharts/highcharts#15885]
Using Highcharts with solid gauge 

wanting to use plotband as an indicator for Load 0-100 that will be updated by ajax

throws TypeError: t.push is not a function

https://jsfiddle.net/guldevec/5bvpnqjh/10/

Highcharts 9.1.1

**Comment by khlieng** [comment]
[xAxis.plotBands](https://api.highcharts.com/highstock/xAxis.plotBands) needs to be an array: https://jsfiddle.net/ys59t4v1/
