### ISSUE TITLE
Org Chart issues between version 8.0.0 and 9.1.1

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/highcharts#15882]
#### Expected behaviour
In version 8.0.0 of the Org chart I was able to format nodes so that I was manipulating html to insert image tags and adding onclick event. But when I upgraded to 9.1.1, they are not working.

Example jsFiddle is provided here
https://jsfiddle.net/sreejithga/duoxyj51/3/

Fiddle is created with 8.0.0 version, so if you click on the texts in the node, it gives you an alert.
For the same code, if you just replace 8.0.0 with 9.1.1, the latest version, the click on the nodes will not give you alert.

Please can you help us to get it working in 9.1.1 also with the same code, or a solution to this issue.

#### Live demo with steps to reproduce
https://jsfiddle.net/sreejithga/duoxyj51/3/

#### Product version
9.1.1

#### Affected browser(s)
Chrome

**Comment by khlieng** [comment]
You could add `onclick` to `allowedAttributes`: https://jsfiddle.net/d6k0wc1b/1/

There is some more discussion about this in #15031.

**Comment by Sreejithga** [comment]
Thanks it worked, thanks for the guidance provided.
