### ISSUE TITLE
highstock chart navigator setExtremes event returns inaccurate min/max values

### ISSUE THREAD

**Issue by RaviDasari** [highcharts/highcharts#15897]
I am using a stacked column chart as navigator and non UTC datetime values for xAxis. When I change navigator handles and set the dates to say 14th and 16th may, I get below range...
Set extremes: e.min: 2021-05-14 16:06:12 | e.max: 2021-05-15 15:53:47 | e.trigger: navigator

And if I move my right handle to 17th may, and leave the left handle as is, I get below range...
Set extremes: e.min: 2021-05-14 16:00:00 | e.max: 2021-05-16 16:06:12 | e.trigger: navigator
If you notice, the `min` has been changed from before and `max` value doesn't show as 17th may.

If I moved my right handle again to 18th may, I get...
Set extremes: e.min: 2021-05-14 12:50:41 | e.max: 2021-05-17 16:00:00 | e.trigger: navigator

BTW, the issue is only with column chart. If I remove the chart type, it reverts back to default (spline) and the setExtremese event returns correct min/max values. But I would like to get this working with column chart which was working fine until 7+ version and is broken since 8+

I have asked same question on forum and didn't find any workarounds - https://www.highcharts.com/forum/viewtopic.php?f=12&t=46759 

#### Expected behavior
setExtreme returns correct min/max values for a selected range.

#### Actual behavior
it returns bad values and doesn't follow any logic and returns different wrong values.

#### Live demo with steps to reproduce
https://jsfiddle.net/ravidasari/m92kdqxv/32/

#### Product version
 Highstock JS v9.1.1 (2021-06-03)

#### Affected browser(s)
chrome

**Comment by KacperMadej** [comment]
Hi @RaviDasari 

Thank you for reporting the problem.

Looks like regression (working better in v7.0.0).

**Comment by pawelfus** [comment]
*Internal note:*
This needs a bisect

**Comment by pawellysy** [comment]
_Internal Note:_
Bisected commit: https://github.com/highcharts/highcharts/commit/e50704e3f8b4d8e47779d0bf24ae823a20ca8085
