### ISSUE TITLE
Highcharts v9.1.1 no longer renders in wkhtmltopdf

### ISSUE THREAD

**Issue by daveherman71** [highcharts/highcharts#15894]
#### Expected behaviour
Highcharts v9.1.1 should render charts in a PDF created with wkhtmltopdf. Highcharts up to v9.1.0 renders correctly.

#### Actual behaviour
Highcharts v9.1.1 no longer renders the charts.

#### Live demo with steps to reproduce
I use the following assets:
1. wkhtmltopdf v0.12.6 which can be download from https://wkhtmltopdf.org/downloads.html
2. The attached sample HTML file (rename the .txt to .html) [sample.txt](https://github.com/highcharts/highcharts/files/6638866/sample.txt)

3. The command line:

`wkhtmltopdf.exe --enable-javascript --javascript-delay "3000" --disable-smart-shrinking "sample.html" "demographics.pdf"`

#### Product version
Highcharts v9.1.1

#### Affected browser(s)
n/a

**Comment by KacperMadej** [comment]
Hi @daveherman71 

Thank you for reporting the problem.

It looks like a wkhtmltopdf problem.
Have you tried increasing the javascript-delay option?

**Comment by daveherman71** [comment]
Hi @KacperMadej 

Yes, increased it to 20 seconds and it still doesn't render the chart although v9.1.0 renders perfectly.
There are no errors in wkhtmltopdf - also opened with QTWeb and no errors are reported their either.

**Comment by KacperMadej** [comment]
After an initial debugging, it looks like Highcharts v9.1.1+ is not loaded at all by jQuery's ajax call.
Works fine in JSFiddle in Chrome (https://jsfiddle.net/BlackLabel/msdr1ohx/8/), so maybe something is wrong in QT or jQuery.

**Comment by KacperMadej** [comment]
This shows the same error (`Can't find variable: Intl`) as reported in #15938.
After testing it looks like the fix for that issue will also resolve this.

**Comment by daveherman71** [comment]
Unfortunately v9.1.2 does not fix the issue. The charts still do not render in wkhtmltopdf.

I also tried by removing the jQuery ajax call and simply including the `highcharts.js` and `modules/data.js` scripts in the original HTML file and version v9.1.0 renders correctly but 9.1.1 and 9.1.2 do not render.

**Comment by KacperMadej** [comment]
@daveherman71 
To test the fix that I mentioned you could try loading Highcharts like:
`url: 'https://github.highcharts.com/d144b7c3f2/highcharts.js', cache: true,`
(URL with the hash of the commit fixing the problem; `cache` set to `true` to prevent jQuery from altering the URL with a `?=timestamp` query as it fails on `github.highcharts.com`)
and similar for the module:
`jQuery.ajax({ url: 'https://github.highcharts.com/d144b7c3f2/modules/data.js', cache: true,`

**Comment by daveherman71** [comment]
Hi @KacperMadej

That fix works (`d144b7c3f2`) - the chart is now rendered in the PDF document.

**Comment by marcovtwout** [comment]
Confirmed that https://github.com/highcharts/highcharts/pull/15940 fixes this issue, tested on wkhtmltopdf 0.12.6

**Comment by Kumaresan165** [comment]
we want to upgrade the latest version of highchart. we will get latest stable version with this fix also?

**Comment by KacperMadej** [comment]
@talitaBehrens
Thank you for reporting the problem.

Debugged QT (the browser used internally by wkhtmltopdf) and it throws an error on the Highcharts library load.
![image](https://github.com/highcharts/highcharts/assets/8960408/a1dc338d-d55a-4940-bdb6-29d3a939af81)

I'll debug it further to get a meaningful error and open a new bug report.
