### ISSUE TITLE
Inconsistent panning in charts with async server loaded data

### ISSUE THREAD

**Issue by mediafreakch** [highcharts/highcharts#15891]
Not sure whether this should be a bug report or feature request. Maybe it's both.

This somehow seems to be related to https://github.com/highcharts/highcharts/issues/15012 . Although I think the problem at the moment is that panning in general is inconsistent.

#### Expected behaviour

Panning is possible in charts with async server loaded data on all devices (touch/mouse). 

#### Actual behaviour

To demonstrate this, here's an example where panning actually works for touch devices in charts with async loaded data (with some caveats, more on that later).

Code: https://jsfiddle.net/j3k8yhoz/ 
Demo: https://jsfiddle.net/j3k8yhoz/show (Use device toolbar in your DevTools to emulate touch device)

**Steps to reproduce in the demo**

1. Click on "Earlier"
2. Use 1 finger and pan to the right (towards newer dates)

Voilà, panning as I would expect. 

On the other hand, the same is not possible when using a mouse device (with panning enabled and `Shift` key):

Code: https://jsfiddle.net/ghc71txf/
Demo: https://jsfiddle.net/ghc71txf/show

**Odd behaviour**

As you saw in the demo, I implemented external buttons to navigate backwards and forwards in time. This was a workaround for the panning not working. But it led to an interesting behaviour: When `xAxis.min` and `xAxis.max` values are set when initializing the chart, panning is possible once outside of that initial timerange, as shown in the first demo.

Here again as a GIF:

![d4a260f0240f06619388d9c50e8af5c5](https://user-images.githubusercontent.com/777093/121670442-b7fe9580-caad-11eb-8b7b-ed078b93aa8a.gif)

#### Product version

Highstock 9.1.1

#### Affected browser(s)

Chrome 91

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

**Comment by raf18seb** [comment]
Internal note:

Bisected to https://github.com/highcharts/highcharts/commit/4a37cf920382e46b7ea6ca478023134dd0fed462
Regression after https://github.com/highcharts/highcharts/issues/7451
