### ISSUE TITLE
Gantt chart scroll bar issue on upgrade to 9.1.1

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/highcharts#15896]
#### Expected behaviour
Gantt Chart should show Y axis scroll bar with below settings

		yAxis:{
					max:2,
            scrollbar: {
                enabled: true,
            },
			},

This works fine with the version 8.0.0, when upgraded to 9.1.1, scroll bar disappeared with the same config

In the provided jsfiddle, which is pointing to 8.0.0, you will see the scrollbar, but if you change it to point to 9.1.1, the scrollbar will disappear. Kindly guide us what needs to be done for scroll bar to appear in version 9.1.1

#### Live demo with steps to reproduce
https://jsfiddle.net/sreejithga/ph703yz8/6/

#### Product version
9.1.1

#### Affected browser(s)
Chrome

**Comment by khlieng** [comment]
Bisected to 12f589d

**Comment by LMprasadkulkarni** [comment]
I am facing the similar issue , here is an example https://jsfiddle.net/w986qdno/10, I am not able to see scrollbar

**Comment by Sreejithga** [comment]
Dear Team, please let us know once the fix is ready as its highly urgent ! Thanks you !

**Comment by Sreejithga** [comment]
Dear Team, Kindly correct me if I'm wrong. If I download the 9.1.1 version again, will this issue be fixed in that one ? or should I specifically download any files as a fix to this issue in my installed 9.1.1 version ? In that case would you mind guiding me on the same please.

Thanks

**Comment by KacperMadej** [comment]
Hi @Sreejithga 
The issue is fixed on the mast branch (next version candidate) and could be loaded as explained here: http://code.highcharts.com/
The current version is 9.1.2 and it was not changed since the fix was merged, so the next release should have the fix implemented as a part of the code. There is no ETA for the next version at this moment - might be within the next few weeks.

**Comment by Sreejithga** [comment]
Thanks, once the next version is released (9.1.3)  I will have it downloaded and used. As its highly urgent from our customer side, I hope you can speed up the release asap please..

Thank you for the support...
