### ISSUE TITLE
Network graph 'euler' reflow issue

### ISSUE THREAD

**Issue by jmitzka** [highcharts/highcharts#15900]
#### Expected behaviour
When the chart size of a network graph is changed then a call to chart.reflow() is supposed to rerun the simulation so as to properly position the nodes in the much larger (or much smaller) chart plot area. 

#### Actual behaviour
chart.reflow() seems to have no effect on the nodes position and they remain in a corner of the plot area. However this works properly if the series layoutAlgorithm.integration is set to 'verlet'

#### Product version
9.1

**Comment by KacperMadej** [comment]
Hi,

Please add a live demo for the problem.

**Comment by jmitzka** [comment]
https://jsfiddle.net/2azbojnL/

Uncomment the verlet version to see difference

var chart = createChart('container-1', 'euler', 30);
//var chart = createChart('container-1', 'verlet', 30);

**Comment by raf18seb** [comment]
@jmitzka thank you for providing a demo.
Simplified demo: https://jsfiddle.net/BlackLabel/7ct18vb0/

FYI @pawelfus

**Comment by pawelfus** [comment]
It seems the barycenter force is not implemented/broken in the Euler integration. Setting `gravitationalConstant` to zero gives the same results: https://jsfiddle.net/BlackLabel/7ct18vb0/1/ - I would start debugging there
