### ISSUE TITLE
Why parents of level 2 are linking to same child nodes either their child are different in organization Highcharts

### ISSUE THREAD

**Issue by EzzahWaseem** [highcharts/highcharts#15907]
There's bug highlighted by me . Please check it and help me out

[https://stackoverflow.com/questions/67903550/why-parents-of-level-2-are-linking-to-same-child-nodes-either-their-child-are-di](https://stackoverflow.com/questions/67903550/why-parents-of-level-2-are-linking-to-same-child-nodes-either-their-child-are-di)

**Comment by KacperMadej** [comment]
Hi @EzzahWaseem 

Please open a new bug report and add the needed info outlined by the bug report template.
