### ISSUE TITLE
Heatmaps with xAxis breaks leaves empty space

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#15919]
#### Expected behaviour
xAxis breaks should be respected and there should not be any empty space

#### Actual behaviour
xAxis breaks leaves space in between for heatmaps

#### Live demo with steps to reproduce
https://jsfiddle.net/b1raetv7/

#### Product version
Highstock 9.0.1

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @govinda18 

Thank you for reporting the problem.

I was trying to recreate this issue with some more readable data but wasn't successful - https://jsfiddle.net/BlackLabel/Luk8yqgr/
Please update your demo with comments or `Data.UTC` usage (like in my demo), and sorted data without duplicates so it will be esier to see what is happeneing in the demo.

**Comment by govinda18** [comment]
Hi @KacperMadej,
Sorry for the delayed response.

Does this work? - https://jsfiddle.net/urdt679v/

**Comment by raf18seb** [comment]
Hi @govinda18,

This is your simplified demo: https://jsfiddle.net/BlackLabel/nfq8rgwu/
And here is a working demo showing how you should define breaks: https://jsfiddle.net/BlackLabel/kfeqtph6/
