### ISSUE TITLE
`ReferenceError: Node is not defined` if running HC with JSDOM

### ISSUE THREAD

**Issue by DiegoCardoso** [highcharts/highcharts#15913]
You can pass a custom `window` object to Highcharts when importing it. But some parts of the code assume that there's a global window object instead of using the one provided by the user.

This line, for instance:
https://github.com/highcharts/highcharts/blob/ed63271415f908f023bc8b567a9d2aa32262e0db/ts/Core/Renderer/SVG/TextBuilder.ts#L333

#### Expected behaviour
Running Highcharts from another environment works fine.

#### Actual behaviour
Running Highcharts with JSDOM throws `ReferenceError`.

#### Live demo with steps to reproduce
Run https://github.com/highcharts/highcharts-jsdom with latest Highcharts

#### Product version
Tested Highcharts, Highstock on 9.1.1

**Comment by KacperMadej** [comment]
Hi @DiegoCardoso 

Thank you for reporting the problem.

_Internal note:_
Maybe there could be a general solution for this and similar issues (e.g. [Intl](https://github.com/highcharts/highcharts/pull/15940))?

**Comment by jaredculp** [comment]
I also have this problem. Is there a workaround?

**Comment by KacperMadej** [comment]
As a workaround, you could set `Node` on one of the scopes available for the Highcharts - could be global scope, so on window or an equal to that object in your environment, or it could as a variable set in any scope.

_Internal note:_
The variable should be loaded from `H.win` instead of the global scope.

**Comment by Vazonik** [comment]
Fixed in https://github.com/highcharts/highcharts-jsdom/commit/2c06dcdd5c04b39a1f1147c72159197d742543c6
