### ISSUE TITLE
Heatmap issue - 8.0.0 versus 9.1.1

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/highcharts#15922]
#### Expected behaviour
When we were using version 8.0.0, the Risk heat map was coming alright.
but when upgraded to 9.1.1, the cell borders are lost also the numbers (value) which was being shown inside each cell is also lost..

Here is the JSFiddle created with 8.0.0 version

https://jsfiddle.net/sreejithga/rwbd1u8g/1/

which is as per our expectation.

Now if you change the url to point to 9.1.1 (replace 8.0.0 by 9.1.1), we get a map with no borders and no cell values, which is not correct.

Screenshot from 9.1.1 version which is the issue with no borders and and no cell values
-------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/53110553/122346726-57160800-cf5a-11eb-9e95-a59584e774ea.png)

Kindly help us fix this issue in 9.1.1, so it works as it was working in 8.0.0

#### Live demo with steps to reproduce

https://jsfiddle.net/sreejithga/rwbd1u8g/1/

#### Product version
9.1.1

#### Affected browser(s)
Chrome

**Comment by khlieng** [comment]
You can use `marker.lineColor`/`lineWidth` on the [series](https://api.highcharts.com/highcharts/series.heatmap.marker.lineColor) or per [point](https://api.highcharts.com/highcharts/series.heatmap.data.marker.lineColor): https://jsfiddle.net/gc1z7vhk/8/

The labels work without `useHTML`: https://jsfiddle.net/gc1z7vhk/9/

**Comment by KacperMadej** [comment]
The labels with `useHTML` could use `format` as a workaround: https://jsfiddle.net/BlackLabel/v5yp30sc/
