### ISSUE TITLE
Creating a seconday datetime axis linkedTo an axis containing breaks renders ticks incorrectly

### ISSUE THREAD

**Issue by DavidKim01** [highcharts/highcharts#15929]
#### Expected behaviour
When creating a secondary datetime x-axis which links to an existing datetime x-axis, while utilizing breaks to eliminate certain data points, I should expect that secondary axis to render ticks in the same manner as the original axis.

#### Actual behaviour
Instead, I am seeing a greater number of ticks being rendered on the additional x-axis, some even overlapping.

#### Live demo with steps to reproduce
https://jsfiddle.net/pay1gkv2/

This demo is forked from the official highstock basic line demo: https://www.highcharts.com/demo/stock/basic-line

#### Product version

Highstock v9.1.1

#### Affected browser(s)

Chrome

Update: simplified some live demo code

**Comment by raf18seb** [comment]
Hi @DavidKim01! Thank you for reporting a problem.

Simplified demo (uncomment breaks): https://jsfiddle.net/BlackLabel/v584dnye/
