### ISSUE TITLE
Date picker format on edit does not format the dates with inputEditDateFormat in rangeSelector

### ISSUE THREAD

**Issue by hardikdarji07** [highcharts/highcharts#15936]
#### Expected behaviour
Even if we applied the rangeSelector.inputEditDateFormat option in the chart but it does not reflect on the chart. It should be applied the same as inputDateFormat option.

#### Actual behaviour
If the inputEditDateFormat option is set, range selector date input not applying the format that we passed in the option.

#### Live demo with steps to reproduce
https://jsfiddle.net/zcrmqegy/

#### Product version
v9.0.1

#### Affected browser(s)
Tested in chrome and mozila

**Comment by khlieng** [comment]
`inputEditDateFormat` only applies when the browsers native date input is not supported or cant be used to input the current `inputDateFormat`.

**Comment by raf18seb** [comment]
Hi @hardikdarji07 

As the [API](https://api.highcharts.com/highstock/rangeSelector.inputEditDateFormat) says, it will be used only for the input type `text`, e.g. in the IE browser. In modern browsers, the used type is `date`. The text format is based on the default format used in a specific country.
