### ISSUE TITLE
LabelFormatter is a bool type (.NET NuGet Package)

### ISSUE THREAD

**Issue by alexdarc** [highcharts/highcharts#15939]
#### Expected behaviour
Should be a string type, isn't?

#### Actual behaviour
Actually is a bool type

#### Live demo with steps to reproduce

Can't reproduce, but here is a documentation link https://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_legend.html#ac3575a9150d891a08399e1615d7112f3

#### Product version

9.1.0 Nuget Package

**Comment by raf18seb** [comment]
Thank you @alexdarc, I reported it on our .NET wrapper repo: https://github.com/highcharts/highcharts.net/issues/168
