### ISSUE TITLE
Logic in format strings

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#15933]
# Description of the feature
Support some simple logic in [format strings](https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#format-strings). 

Format strings are preferred over formatter callbacks in situations where 
* The configuration is XSS critical because it comes from an unfiltered, untrusted source (like is the case on our own export server), or
* The configuration is relayed from another programming language so function callbacks can not easily be serialized.
* The configuration must be serialized to JSON for storage etc.

For these reasons, it is sometimes required that the format strings support some simple logic. We should model it on well-known and well-tested template languages like Handlebars. Primarily, these features should be considered:
* Conditions. Model it on Handlebars `#if`/`else` syntax.
* Loops. Handlebars have `#each` loops. These can take blocks of template code, unlike our internal Accessibility module's `#each` function. Consider either providing a compliance rewrite or using a different name.
* Simple math. An analysis of our own demos reveals that we often use multiplication and division in our formatters because string formats don't support those operations. For example by converting a fraction to a percentage, or a value to an `{n}k` numeric symbol.
* Array indexing? The accessibility module has this.
* Nested functions? Handlebars has this.

This should be implemented as a pluggable system, allowing contributors to add their own formatting functions. If the core implementation becomes too bulky, consider not adding it to core `highcharts.js`, but as a module script instead.

### Use cases
Conditional tooltip format
```js
pointFormat: '<span class="{#if point.negative}negative{else}positive{/if}">{y:.0f}</span>'
```
Math
```js
labels: {
  format: '{value * 100}%' // Alternatively function called multiply
}
```

# Library related to the feature
Highcharts

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by KrishnaKumarHariprasannan** [comment]
Thanks for opening this @TorsteinHonsi ! Conditionals, loops and simple math would be a great start here - for cross-language use-cases, these would be a huge improvement on the status-quo.
