### ISSUE TITLE
ReferenceError with HC 9.1.2: Can't find variable: Intl

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#15938]
So with 9.1.2 I'm getting `ReferenceError with HC 9.1.2: Can't find variable: Intl`.  Seems like this new version of highcharts is referencing `Intl` for the first time?  I'm mostly using highcharts in a slightly old browser environment (phantomjs to be precise).  Is there a recommended polyfill for `Intl` so that I can get things up and running with 9.1.2?

**Comment by marcovtwout** [comment]
Confirmed that #15940 fixes this issue, tested on wkhtmltopdf 0.12.6
