### ISSUE TITLE
Column chart - zoom x

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1594]
In case when zoom type is set as x, and we zoom our chart, then yAxis extremes also are modified.

Example: http://jsfiddle.net/b8Bu2/

**Comment by oysteinmoseng** [comment]
Closing, as this seems to work as expected in latest code. Feel free to reopen.

**Comment by Myles-JB** [comment]
Would someone be able to point me to the solution/ documentation update for this issue. I'm currently facing battling this issue and I believe it is the same problem that when setting axis min and max via setExtremes the reset zoom button disappears.
