### ISSUE TITLE
Stacked column chart shows 0 on negative stack

### ISSUE THREAD

**Issue by maxedin** [highcharts/highcharts#15956]
#### Expected behaviour
'0.0' stack label should be hidden because 0 is neither positive or negative value

#### Actual behaviour
'0.0' stack label is visible like positive value

#### Live demo with steps to reproduce
https://jsfiddle.net/9537orgc/56/

#### Product version
Highcharts v8.2.2

#### Affected browser(s)
all

**Comment by maxedin** [comment]
![image](https://user-images.githubusercontent.com/1277079/123032556-7533aa80-d429-11eb-97f6-b6be8bb1a339.png)

**Comment by PaulDalek** [comment]
Hi @maxedin

Thank you for reporting this issue. The reason behind this behavior is because the text value is taken from the `cumulative` value of a stack, which in this case is 0. You can easily prevent from displaying 0 values by setting a custom stack labels formatter.

**Demo**
https://jsfiddle.net/BlackLabel/ovz72mew/

_Internal note_
We can prevent 0 values in the `StackItem.prototype.render` function if we only want to display positive and negative values.

**Demo**
https://jsfiddle.net/BlackLabel/0hrvj8up/

**Comment by maxedin** [comment]
@PaulDalek thank you, I've tried formatter before. There are couple of issue with it:

1. If total sum of stacked series is 0, it is still should show `0.0` column but column disappears https://jsfiddle.net/kdzbL0vf/4/
2. `formatter` overrides `format` so you can't apply custom formatting from the user like `{total:,.1f}`. Using `Highcharts.numberformat()` is not always an option.

The '0' problem exists for negative stacked series only. It is works fine for positive stacks. There must be some logic `>=0` somewhere that makes `0` to be a positive value, while it is neither positive or negative.

**Comment by PaulDalek** [comment]
@maxedin

The 0 value is counted into a positive stack (see the `isNegative = negStacks && y < (stackThreshold ? 0 : threshold);` condition in the `setStackedPoints` function) so the 0.0 stack label is shown above the -10. You can use modification of the `render` from the previous comment to get rid of the 0’s but that will cause them to disappear entirely.

**Demo**
https://jsfiddle.net/BlackLabel/L6uega0y/

**Comment by maxedin** [comment]
@PaulDalek 
Thank you for another example and thank you confirming that 0 value is counted into a positive stack.
I believe we see a fundamental mathematical issue here: _**0 isn't a positive number or a negative number, it is a neutral value**_ (https://www.quora.com/Is-0-a-positive-number-or-a-negative-number)
Therefore,  0 should not be counted as positive stack. Expected behavior for stacked chart:

1. positive stack - hides 0 (working)
2. zero stack - shows 0 (working)
3. negative stack - hides 0 (not working)

As you see, there is no workaround to make all 3 scenarios to work using formatter. 
Is it something you could possibly plan to fix in future? Thank you.

**Comment by PaulDalek** [comment]
@maxedin

I agree but right now this is how it works and for now there are no plans to change that. If you want, you can report this as an enhancement.
