### ISSUE TITLE
Setting ordinal to true for an xAxis appears to cause any additional x-axes linking to it to calculate ticks incorrectly

### ISSUE THREAD

**Issue by DavidKim01** [highcharts/highcharts#15955]
#### Expected behaviour
When duplicating the x-axis via an additional array entry in the xAxis chart options, which has the ordinal property set to true, I should expect the second x-axis to render ticks identically to the first xAxis.

#### Actual behaviour
You can observe a greater number of ticks being rendered on the additional x-axis, some even overlapping.

This may be related to the issue I had posted a few days earlier: https://github.com/highcharts/highcharts/issues/15929
The difference here is that I am not utilizing any breaks whatsoever.

#### Live demo with steps to reproduce
https://jsfiddle.net/qe6wv1r7/

Setting ordinal to true for the duplicated x-axis as well does not appear to fix the issue either:
https://jsfiddle.net/muw5zLcd/

#### Product version
Highstock v9.1.1

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment]
Hi @DavidKim01.

Thanks for posting more info. I was testing #15929 for ordinal and non-ordinal axis, but with breaks it didn't change anything. I'll add more info in the original thread.
