### ISSUE TITLE
Freeze first row on horisontal bar chart

### ISSUE THREAD

**Issue by pnrdk** [highcharts/highcharts#15969]
We have a horisontal bar chart with vertical scroll, we would like to have the possibility to “freeze” the first row in the chart, because it shows a summary of all the data below. 

![image](https://user-images.githubusercontent.com/11608793/123620444-881ff380-d80a-11eb-8697-13372b431017.png)

I have asked you support regarding this feature and they advised me to create it here :-)

**Comment by PaulDalek** [comment]
Hi @pnrdk 

Thank you for contacting us and suggesting this enhancement. As a workaround you can two charts, where the first one will show the summary bar and the second will be the main one with all the data. See the simplified example below.

**Demo**
https://jsfiddle.net/BlackLabel/ab1vd3nj/

**Comment by pnrdk** [comment]
Hi @PaulDalek 
Thanks very much for you suggestion!, we will try to implement thar and see how it will work :-)

**Comment by khlieng** [comment]
Heres how you could do something similar using multiple axes: https://jsfiddle.net/hpcr63sf/7/
