### ISSUE TITLE
Data labels collision between stacked column and line

### ISSUE THREAD

**Issue by ver1000000** [highcharts/highcharts#15964]
I think this is not an expected behaviour. I want to make the line data labels always on top of column data labels. All manipulations with `zIndex` property don't give any results.

![image](https://user-images.githubusercontent.com/3034821/123382685-6df0d600-d5bc-11eb-8ca2-9c7cb964b54f.png)

The only thing I can do is `allowOverlap: true` which is not an option:
![image](https://user-images.githubusercontent.com/3034821/123382852-9f69a180-d5bc-11eb-9bf6-7e4d8854d9e5.png)

Would be great if I can manually control where to show data labels. For example, if it overlaps above the marker I can move label below.

**Comment by raf18seb** [comment]
Hi @ver1000000,

this is intended behavior. We do not provide an option for placing dataLabels from others series so they don't overlap.
For now, is it OK for you to move your dataLabels manually? See demo: https://jsfiddle.net/BlackLabel/cd6183oy/

For future questions, please use our other support channels (this is a bug tracker). https://www.highcharts.com/blog/support/

**Comment by ver1000000** [comment]
@raf18seb it doesn't help unfortunately. I've seen a custom anti-collision algorithm and tried to use it https://jsfiddle.net/ver1000000/edzgfr9o/31/ but it ignores opacity property. Also not sure it can detect label collision between series.

**Comment by raf18seb** [comment]
@ver1000000 yes, unfortunately, as I said in my previous comment, we don't provide (and I haven't seen) any workaround for dataLabels collisions with other series.
