### ISSUE TITLE
Incorrect focus outline for rotated data labels in Word Cloud

### ISSUE THREAD

**Issue by franklinefrancis** [highcharts/highcharts#15973]
#### Expected behaviour
Focus outline of rotated data labels in word cloud should not overlap with the data label themselves

#### Actual behaviour
Focus outline is inconsistent for rotated data labels

![Rotated Word Cloud](https://user-images.githubusercontent.com/1227574/123789803-2d19f980-d8fb-11eb-9cad-1a06011d7be1.PNG)

#### Live demo with steps to reproduce
https://jsfiddle.net/franklinefrancis/La609cs2/

#### Product version
8.2.0

#### Affected browser(s)
Firefox

**Comment by khlieng** [comment]
@raf18seb did you try it in Firefox? 8.2.0, 9.1.2 and master all had the same problem for me.

**Comment by franklinefrancis** [comment]
@raf18seb,

This is issue was seen only in Firefox. Here is the screen recording:

![Rotated word cloud](https://user-images.githubusercontent.com/1227574/123898907-cb51a200-d983-11eb-8a76-64cdc1feaecf.gif)

And here are the steps:

1. Open the JSFiddle link in Firefox
2. Start tabbing from the first input field
3. Once Wordcloud is in focus, use arrow keys to see the focus 
4. Notice that for a few data labels the focus outline overlaps with the data label

**Comment by raf18seb** [comment]
You are right, it's a Firefox issue - I was testing on Chrome. 👍
