### ISSUE TITLE
TileMap content do not fill the whole available space

### ISSUE THREAD

**Issue by palpatine1991** [highcharts/highcharts#15974]
#### Expected behaviour
When I specify the chart size explicitly and disable all the features around the chart area (legend, title, etc..), I expect that the tiles fill the whole area which is provided.

The motivation for this is that I want to create a honeycomb with regular hexagons. THe number of hexagons and the layout depends on the data from backend. Therefore I need to compute the size of the chart and pass it into highcharts configuration but it is not possible if there are paddings on each side and these paddings are not fixed (they are different based on the number of hexagons in the chart and their layout).

#### Actual behaviour
Currently, not all the space is used. Moreover, it seems that the amount unused space depends on the tile count and position.

#### Live demo with steps to reproduce
http://jsfiddle.net/auqp1jw2/1/

On this demo, I would expect that the hexagon fills the whole space (200x200) but it is only 85px wide.

#### Product version
Highmaps 9.1.2

#### Affected browser(s)
Chrome (but most probably all of them)

**Comment by raf18seb** [comment]
Hi @palpatine1991, thanks for creating the ticket.

Setting all the options you have set doesn't change the "paddings/margins" inside plotArea and the way the series points are drawn. I am afraid we do not provide any option that would make points (or 1 point in this case) fill the whole available space.

You can write your own custom logic for drawing the points (here is an example working only for 1 tilemap point): https://jsfiddle.net/BlackLabel/296e1q87/

```js
// Change the coords to fill all the available plot area space
      if (series.points.length === 1) {
        var plotSize = series.chart.plotSizeX,
          a = plotSize / 2;

        x1 = y1 = plotSize;
        x2 = (plotSize - a) / 2 + a;
        x3 = (plotSize - a) / 2;
        x4 = 0;
        y3 = 0;
      }

      // Store points for halo creation
      point.tileEdges = {
        x1: x1,
        x2: x2,
        x3: x3,
        x4: x4,
        y1: y1,
        y2: y2,
        y3: y3
      };
      // Finally set the shape for this point
      point.shapeType = 'path';
      point.shapeArgs = {
        d: [
          ['M', x2, y1],
          ['L', x3, y1],
          ['L', x4, y2],
          ['L', x3, y3],
          ['L', x2, y3],
          ['L', x1, y2],
          ['Z']
        ]
      };
