### ISSUE TITLE
Misalignment of long titles in exported image

### ISSUE THREAD

**Issue by rdp1414** [highcharts/highcharts#15971]
This bug exists only in exported image and not in the rendered chart.

#### Expected behaviour
The second line of title in the exported image should be aligned with the first line.
```
    This is a really really really really really
    really long title
```

#### Actual behaviour
The second line of title in the exported image is misaligned.
```
    This is a really really really really really
really long title
```

#### Live demo with steps to reproduce
https://jsfiddle.net/e6hz3od9/3/ Try downloading chart image by clicking on export button. In the chart image, you can see the above mentioned problem,

#### Product version
Highcharts version `9.1.2`

#### Affected browser(s)
Chrome

**Comment by khlieng** [comment]
It works with [exporting.allowHTML](https://api.highcharts.com/highcharts/exporting.allowHTML) enabled: https://jsfiddle.net/oarm9341/

**Comment by khlieng** [comment]
This will get fixed by #16063.

**Comment by rdp1414** [comment]
Hello @khlieng / @PaulDalek,

1. Highcharts by default sets [exporting.allowHTML](https://api.highcharts.com/highcharts/exporting.allowHTML) to `false`. So, in my team, we are planning to internally set it to `true` for our use-case.
2. I just wanted to confirm/consult that are there any vulnerabilities/repercussions with it to set it to `true` because highcharts doesn't set it to `true` by default which appears a very natural thing to have? 

Thank You,
Rajdeep

**Comment by raf18seb** [comment]
@rdp1414, yes, you can set `allowHTML: true` without any fears. The only difference is that you'll have the HTML elements exported as well.
