### ISSUE TITLE
Stocktools change series icon 

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#15984]
#### Expected behaviour
Fit the icon to the series while first render.

#### Actual behaviour
When you initiate the chart with series different than the OHLC the change series icon doesn't fit.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/tor4j3qw/

#### Product version
Highstock JS v9.1.2 (2021-06-16)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
**Workaround:**
Reorder list of items under `typeChange` button, [demo](https://jsfiddle.net/BlackLabel/tor4j3qw/1/), snippet:

```js
    stockTools: {
      gui: {
        definitions: {
          typeChange: {
            items: [
              'typeLine', // the first one is by default the active one
              'typeOHLC',
              'typeCandlestick'
            ]
          }
        }
      }
    },
```
