### ISSUE TITLE
does this type of graph possible with high charts

### ISSUE THREAD

**Issue by MVREDDY-STI** [highcharts/highcharts#15989]
<img width="214" alt="Screenshot 2021-06-30 at 12 43 23 PM" src="https://user-images.githubusercontent.com/61783693/124126648-82d7d880-da98-11eb-88b3-e70eac024429.png">

**Comment by raf18seb** [comment]
Hi @MVREDDY-STI,

GitHub is our bugs and features tracker only. Please, use other dedicated support channels: https://www.highcharts.com/blog/support/
