### ISSUE TITLE
Regarding High charts highcharts-exit-anchor issue.

### ISSUE THREAD

**Issue by shivarajuv** [highcharts/highcharts#15986]
Hi,

I am shivaraju from OpenText. We have an issue while calling below code.
var clientChart = actuate.report.Chart[ "ClientChart" + chartElement.id ];
chart.update( {
  chart: {
    width: null,
    height: null
  }
} );

after calling this method with width and height as null, chartElement **highcharts-exit-anchor** div has been removed. because of this my custom tab order flow has getting problem. May I know why it is getting deleted after calling that. This is the effective div after calling the method.

 **<div class="highcharts-exit-anchor" tabindex="0" aria-hidden="false"></div>**

Please let me know is there any other way we can get that div back again after calling this.(We are considering based on exit anchor div we are moving focus to next other charts).

**Comment by khlieng** [comment]
Regression since 8.0.1, exit anchor vanishes on any `Chart.update`, I think the end marker gets re-created after having been turned into an exit anchor. @oysteinmoseng

Demo: https://jsfiddle.net/y2f14ur8/15/

**Comment by shivarajuv** [comment]
This is broken in latest version(9.1.2) also (https://jsfiddle.net/t4jrkLmq/). Request to backport fix to 8.2.0 version.

**Comment by khlieng** [comment]
Heres a plugin that fixes 8.2.0: https://jsfiddle.net/Lto0b2d1/3/

**Comment by shivarajuv** [comment]
Updated with that method its working fine, Thank you.
