### ISSUE TITLE
Large datasets with PackedBubble (or alternative chart type)

### ISSUE THREAD

**Issue by fbegue** [highcharts/highcharts#15992]
#### Issue

After struggling to render large (13 series, 650+ datapoints) datasets with the PackedBubble chart type, I looked into use the Boost module - but from the documentation, it appears this type of chart is not supported. 

Is there anyway to speed up the rendering here, or am I just asking too much?
If so, can you recommend any other method of achieving my end goal the basically boils down to:
 "displaying the entire library of information in one graph so that the relative sizes of the different series can be visually compared" ?

The first thing I considered was:
1) turn off the animation
2) moving the render code to a webworker in order to perform this in the background

But turning off the animation for a dataset of this size completely seizes up the browser :/

I have a live demo below that renders a reduced dataset initially.
In the App() render JSX you can comment **in** and **out** the 1-liner that will render the problem dataset. 

Thanks ahead of time, love the library! 

#### Live demo with steps to reproduce
https://codesandbox.io/s/packed-bubble-split-boost-gluhz?file=/src/App.js

**Comment by raf18seb** [comment]
Hi @fbegue, thanks for writing to us!

This is our bugs and features tracker only. With any support questions, could you please contact us on the other dedicated channels? Thanks for understanding.
https://www.highcharts.com/blog/support/

ps. could you double-check your demo and make sure that you saved it correctly?
