### ISSUE TITLE
Issue found within plotOptions.series.showCheckbox

### ISSUE THREAD

**Issue by shivabalakrishna** [highcharts/highcharts#15991]
Expected: **showCheckbox** : If true, a checkbox is displayed next to the legend item to **allow selecting the series**.

Issue: _The checkbox is displayed but does not select the series_

[DOCS LINK](https://api.highcharts.com/highcharts/plotOptions.series.showCheckbox)
 [SAMPLE LINK](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-showcheckbox-true/)

Highcharts V9.1.2

Affected in all browsers

**Comment by khlieng** [comment]
Selecting a series just means that it gets [selected](https://api.highcharts.com/class-reference/Highcharts.Series#selected) set to `true` and gets returned by [Chart.getSelectedSeries()](https://api.highcharts.com/class-reference/Highcharts.Chart#getSelectedSeries), and that seems to work: https://jsfiddle.net/oe9cnwya/2/
