### ISSUE TITLE
defaultLabelFormatter thousands separator

### ISSUE THREAD

**Issue by diogen737** [highcharts/highcharts#16006]
#### Expected behaviour
A thousand separator should be added to Axis labels less than 10k
In the fiddle I've reproduced defaultLabelFormatter's behavior, seems like there's a mistake in line 47 - 10000 should be 1000.

#### Live demo with steps to reproduce
https://jsfiddle.net/yv5nes9m/

#### Product version
Highstock 9.1.2

**Comment by khlieng** [comment]
This is done to avoid adding thousands separators to years on linear axes, some more info in #3811 and #2466.
