### ISSUE TITLE
Shared tooltip with multiple yAxis and "top" for positioning of the first yAxis won't work for all markers

### ISSUE THREAD

**Issue by nr-mi** [highcharts/highcharts#16004]
#### Expected behaviour
Highcharts should shows the shared tooltip on every marker (if not disabled or configured otherwise).

#### Actual behaviour
In this case, the tooltip for all markers of "BD" and "AD" aren't shown.
I think this is because the first yAxis has `"top":"65%",`.
It works as expected for "AU" and "BU".

#### Live demo with steps to reproduce
https://jsfiddle.net/6nke2uLo/

#### Product version
newest

#### Affected browser(s)
all

**Comment by riteshwaghela** [comment]
Facing the same issue. Any Idea when this will be available in latest version?

**Comment by raf18seb** [comment]
@riteshwaghela sorry for the late reply. The pull request fixing it is being reviewed, but we are not sure whether the issue is fixed and we don't have ETA for releasing it yet.
