### ISSUE TITLE
Pie chart ring is not rendered when Date is mocked

### ISSUE THREAD

**Issue by vlcr** [highcharts/highcharts#16015]
![image](https://user-images.githubusercontent.com/17763177/124920726-ee212d80-dff7-11eb-928c-1240ecd4e78f.png)

#### Expected behaviour
Pie chart ring should render correctly.

#### Actual behaviour
Pie chart animation to draw the rind does not start when current date is mocked.

#### Live demo with steps to reproduce
https://codesandbox.io/s/highcharts-mocked-date-issue-x75sc?file=/demo.jsx

#### Product version
`highcharts` - `v9.1.2`
`highcharts-react-official` - `v3.0.0`

#### Affected browser(s)
At least Chrome & Safari, probably every browser

**Comment by raf18seb** [comment]
Hi @vlcr, thanks for creating the ticket.

I don't think this is a Highcharts issue. MockDate is interfering with the whole global `Date` object which is overwritten:
```js
function set(date) {
        var dateObj = new Date(date.valueOf());
        if (isNaN(dateObj.getTime())) {
            throw new TypeError('mockdate: The time set is an invalid date: ' + date);
        }
        // @ts-ignore
        Date = MockDate;
        now = dateObj.valueOf();
    }
```

No workaround from the Highcharts side at this moment.

Simplified JS demo: https://jsfiddle.net/BlackLabel/vo8bj6pk/

FYI @TorsteinHonsi

**Comment by vlcr** [comment]
> No workaround from the Highcharts side at this moment.
>
> Works with a line but without animation: https://jsfiddle.net/BlackLabel/ztrq389o/

Yeah, some kind of work around is to turn off the `animation`, it works for `pie` as well.
Demo: https://jsfiddle.net/oa32wy7n/

But it looks like an animation of `bar` is affected as well: https://jsfiddle.net/2bejrovf/
