### ISSUE TITLE
Responsive options for yAxis will ignore any updates to chart y-axis

### ISSUE THREAD

**Issue by tzaitoun** [highcharts/highcharts#16010]
#### Expected behaviour
https://jsfiddle.net/o2hgtdL6/2/

**Context:** the example above has a responsive setting on the chart width, at 600 and below, it will hide the y-axis title by setting it to an empty string. The example also updates the title of the y-axis after creating the chart.

To reproduce:
1) Start off at size of the chart greater than 600 so the title shows. The title should be "New Y-axis".
2) Minimize the width of the chart until the title disappears.
3) Resize the chart back again to greater than 600 so the title shows again. You would expect the title to be "New Y-axis" since we updated it from "Y-axis" to "New Y-axis" after creating the chart. However, it becomes "Y-axis".

#### Actual behaviour
The title of the y-axis is "Y-axis" instead of "New Y-axis"

#### Product version
Latest, the fiddle works for v8.2.2 so you can uncomment that line in the fiddle to check that it works as expected in that version.

#### Affected browser(s)
All

**Comment by khlieng** [comment]
This will likely get fixed by #15904.
