### ISSUE TITLE
responsive not working over multiple size changes

### ISSUE THREAD

**Issue by scottg521** [highcharts/highcharts#16011]
#### Expected behavior
Responsive rules will apply whenever condition is met

#### Actual behavior
Rules are applied the first time, but not subsequent times after the view has reverted back

#### Live demo with steps to reproduce
https://jsfiddle.net/wevu95g2/1/

When graph first appears, it is above responsive threshold, and left axis (which is actually an x axis) and annotations appear as expected.
1. click 'Small' and left axis disappears as specified in responsive rule; the left annotation does not disappear but the right one does (or maybe it is just off-screen)
2. click 'Large' and left axis reappears as expected; annotation does not change
3. click 'Small' and left axis does not disappear
4. further clicking of 'Large', then 'Small' does not show any responsive effect.

#### Product version
master (9.1)

#### Affected browser(s)
Edge, Chrome, Firefox

#### Further notes:
I discovered this because I am trying to get responsive to work in my application, which is in Angular 9 and uses "highcharts-angular": "2.10.0" to integrate highcharts as an Angular component. In the Angular code, the chart HTML is:

```
  <highcharts-chart
      [Highcharts]="Highcharts"
      [options]="chartOptions"
      [oneToOne]="true"
      (chartInstance)="storeChartId($event)"
      style="display: block;"
    >
  </highcharts-chart>
```

I copied chartOptions from the debugger and pasted them into the jsfiddle. That is when I discovered this bug.

But my real problem is that responsive is not working at all in my app--the axis does not disappear no matter how narrow the container is.

/label ~Bug

**Comment by khlieng** [comment]
You can fix the axis part of this by using an array in the responsive rules: https://jsfiddle.net/3jgy26b4/

The annotation update part is a bug.

**Comment by scottg521** [comment]
Still not able to get it to work at all in my Angular app, but thanks for the quick response.

**Comment by khlieng** [comment]
Heres an angular demo where the axis hiding works: https://stackblitz.com/edit/highcharts-angular-basic-line-kuqkrq?file=src%2Fapp%2Fapp.component.ts
