### ISSUE TITLE
yAxis title not showing and wrong chart width

### ISSUE THREAD

**Issue by mediafreakch** [highcharts/highcharts#16026]
#### Expected behaviour

The example below has a responsive setting for the yAxis. On devices < 910px, the yAxis title should be placed on top of the axis, not on the left side of it.

This works fine when rendering the chart for the first time.

#### Actual behaviour

However if I change the device's orientation from landscape to portrait and back (which causes the responsive setting to take effect), the yAxis title doesn't show at all. Also it seems like the width of the yAxis is calculated wrongly (too wide, but not only because of the missing title).

![2f1e137e234107ebcde5bceed106ef5e](https://user-images.githubusercontent.com/777093/125285156-a57cb380-e31a-11eb-8ac0-ab666400eaa6.gif)

#### Live demo with steps to reproduce

Fiddle: https://jsfiddle.net/1v96web7/
Fiddle to preview: https://jsfiddle.net/1v96web7/show

**Steps to reproduce**

1. Open DevTools and Device Toolbar
2. Choose "IPad" from the list (or something that is wider than 910px in landscape mode and narrower than that in portrait)
3. Make sure the device is in landscape mode
4. Run the fiddle
5. Change orientation to portrait and then back

If I omit the yAxis responsive settings, everything works as expected. So I wonder if this is related to https://github.com/highcharts/highcharts/issues/16010 and will be fixed by https://github.com/highcharts/highcharts/pull/15904 ?

#### Product version

9.1.2

#### Affected browser(s)

All

**Comment by khlieng** [comment]
It should be fixed by that PR yes.
