### ISSUE TITLE
hoverChartIndex no longer exists with versions >= 9.1.1

### ISSUE THREAD

**Issue by h11a** [highcharts/highcharts#16021]
#### Expected behaviour
The hoverChartIndex no longer exists with the new versions. I am using this with my synchronized charts and they just stopped working all of a sudden (I had ^ on the package version number). I can confirm it works correctly on 9.1.0

#### Actual behaviour
I need the hoverChartIndex  or an alternative way to access it. 

Currently I am doing this 

```
        const charts = Highcharts.charts;

        // the original value of the chart mouseovered
        const sourceChart = charts[Highcharts['hoverChartIndex']];
```

#### Product version
9.1.1

#### Affected browser(s)
Chrome

**Comment by khlieng** [comment]
It has moved to `Highcharts.Pointer.hoverChartIndex`.

**Comment by h11a** [comment]
thanks @khlieng  :)
