### ISSUE TITLE
click tooltip will trigger point click event

### ISSUE THREAD

**Issue by webpig** [highcharts/highcharts#16022]
#### Expected behaviour
click tooltip dont't trigger point click event

#### Actual behaviour
click tooltip will trigger point click event
![image](https://user-images.githubusercontent.com/24989439/125227967-70666600-e306-11eb-9c75-f07f528365a5.png)

#### Live demo with steps to reproduce

https://jsfiddle.net/webpig/cms9n4qL/4/

#### Affected browser(s)
Chrome: 91.0.4472.114

**Comment by khlieng** [comment]
You could set `pointerEvents` to `auto`: https://jsfiddle.net/gkctLfo1/

**Comment by webpig** [comment]
> You could set `pointerEvents` to `auto`: https://jsfiddle.net/gkctLfo1/

I set ```pointerEvents``` to ```auto```, console.log is not work. But click tooltip will change current select point. I hope click tooltip, nothing will happen.

**Comment by webpig** [comment]
> You could set `pointerEvents` to `auto`: https://jsfiddle.net/gkct
