### ISSUE TITLE
I want to remove and edit built-in flag from Highcharts Stock Chart from the UI (Chart)

### ISSUE THREAD

**Issue by nadirefe** [highcharts/highcharts#16024]
**Expected behaviour**
I want to remove and edit built-in flag from Highcharts Stock Chart from the UI (Chart).

**Actual behaviour**
Right now, user cannot remove or edit the flag from the UI. It is not even clickable unlike annotations. 

**The main reason for this feature**
I am implementing Highcharts Stock Chart with Stock Tools. Also, user can save the chart from the button in the Stock Tools(the last one in the default Stock Tools).  When user draw sth(annotations, lines, circles etc.) and clicks that save button, the data go to local storage and when the user renders the page again, I show the saved chart to user. But unlike annotations and indicators, flags cannot be editable after that session. I also tried to add flags manually and it couldn't work either.

**Live demo with steps to reproduce**
https://jsfiddle.net/qrandmzp/1/

**Product version**
"highcharts": "^9.1.2",
"highcharts-react-official": "^3.0.0",

**Affected browser(s)**
At least Chrome & Safari, probably every browser

**Comment by pawelfus** [comment]
Thank you for sharing the idea @nadirefe !

When adding a `flags` series upon chart init (not from GUI), we treat this series as any other main series (volume, exchange rate, etc.). It is possible to show the popup on click on flag-point, take a look: [demo](https://jsfiddle.net/BlackLabel/safr27wt/). 

Snippets:
- to show the popup:
```js
function showPopup() {
  var point = this,
    options = point.options,
    navigation = point.series.chart.navigationBindings;

  Highcharts.fireEvent(navigation, 'showPopup', {
    point: point,
    formType: 'annotation-toolbar',
    options: {
      langKey: 'flags',
      type: 'flags',
      title: [
        options.title,
        navigation.utils.getFieldType(options.title)
      ],
      name: [
        options.name,
        navigation.utils.getFieldType(options.name)
      ]
    },
    onSubmit: function(updated) {
      if (updated.actionType === 'remove') {
        point.remove();
      } else {
        point.update(navigation.fieldsToOptions(updated.fields, {}));
      }
    }
  });
}
```
- usage in a flag series:
```js
    {
      type: 'flags',
      name: 'Flags in pane',
      data: [{
        x: lastDate - 50 * days,
        title: 'WHAT IS THAT'
      }, {
        x: lastDate - 35 * days,
        title: 'On series'
      }],
      onSeries: 'dataseries',
      shape: 'squarepin',
      y: 10,
      // Adds "showPopup" callback
      point: {
        events: {
          click: showPopup
        }
      }
    }
```
