### ISSUE TITLE
Exporting charts In PDF when the charts are loaded inside a function 

### ISSUE THREAD

**Issue by Ashsrivastava7** [highcharts/highcharts#16032]
Hello I am ash I used the export PDF functionality through the button outside the highchart.
I have one different case my charts are loading within a function and I load that function on document.ready function when I use this case the exporting module is not working and throw an error " chart.getSVG is not a function ".But when I remove the function module it works fine for me can you please tell me how to export chart in pdf by external button when chart is loaded within the function.

I will share my jsfiddle link  for better understanding of the issue

here is the first case where the exporting module is working fine

https://jsfiddle.net/Ash_Srivastava/8xymsdn7/17/

here is the second case where it is not working

https://jsfiddle.net/Ash_Srivastava/8xymsdn7/22/

**Comment by khlieng** [comment]
You need to place the variables outside the functions so that your click handler can access them: https://jsfiddle.net/1Le3hoaw/

You could also just pass in `Highcharts.charts`: https://jsfiddle.net/1Le3hoaw/1/

**Comment by raf18seb** [comment]
Hi @Ashsrivastava7! I believe this is a question, not a feature request, am I right?
In case of any further questions, please contact us on dedicated support channels - GitHub is the issues/features tracker only.
https://www.highcharts.com/blog/support/

I am closing the ticket now. If you believe it should be opened or continued here, feel free to open and elaborate.
