### ISSUE TITLE
Indicator VbP ("Volume by Price") rescale and positioning not working if volumeDivision enabled

### ISSUE THREAD

**Issue by robocop98** [highcharts/highcharts#16036]
#### Expected behaviour
Add an OHLC series, a volume series and a "vbp" indicator with parameter volumeDivision: { enabled: true }.
Then scale the chart, e.g. by using xAxis.setExtremes().
Expect both (the positive and negative colored) "vbp" bars to be correctly scaled and positioned into their respective zones.

#### Actual behaviour
The right part, negative/red "vbp" bars is updated correctly by VBPIndicator.prototype.translate.
But the left part, positive/green "vbp" bars are not translated and stay in their initial scale and position.

With volumeDivision disabled all works as expected.

The issue seems to lay in how VBPIndicator.prototype.drawPoints adds the two required "points".
Looks like the first added "point" (the positive/green) is overwritten by the second "point" (negative/red).
VBPIndicator.prototype.translate only finds the last added "points" (the negative/red ones) and is not able to translate the first "points" (positive/green ones).

#### Live demo with steps to reproduce
Issue can be reproduces in the sample linked for the indicator:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/indicators/volume-by-price

Simply change the period several times and you can see that the green bar points are not correctly resized and positioned any more.

#### Product version
Highstock 9.1.0 and 9.1.2

#### Affected browser(s)
Should not depend on browser, but tested in Chrome 91.0.4472.106 and Firefox Developer 86.0b9

**Comment by khlieng** [comment]
Bisected to c620998 @karolkolodziej
