### ISSUE TITLE
Tooltip data not visible if we add opacity to tooltip  tyle object and hover over zoom out button

### ISSUE THREAD

**Issue by brdzamasina** [highcharts/highcharts#16045]
If we add opacity to tooltip, zoom it in and position of the chart bar is near the reset zoom button

https://i.ibb.co/ysvJ52t/example.jpg

hen hover over chart bar so the tooltip is being shown and then again hover over reset zoom button text from tooltip will disappear. If we remove the opacity from tooltip style object this will not happen.

#### Expected behaviour

Tooltip data is visible

#### Actual behaviour
Tooltip data is not visible

#### Live demo with steps to reproduce
https://jsfiddle.net/tojpbad7/

#### Product version
9.1.2

**Comment by brdzamasina** [comment]
Hi guys, any new info about this ?

**Comment by raf18seb** [comment]
Hi @brdzamasina, sorry for the delay with the first PR.
A new PR is being reviewed now.

**Comment by raf18seb** [comment]
@brdzamasina, the bug has been fixed and is merged to master. It will be a part of the next release. Thanks for bumping up!
