### ISSUE TITLE
Opacity and Fillopacity not considered when hovered on Line chart in some cases

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/highcharts#16047]
#### Expected behaviour
The chart types where opacity = 0 and fillopacity = 0 should remain transparent in the chart and on hover also it should remain transparent as per my understanding.
It behaves correctly but in the example fiddle provided you can see on hover the line chart for the series 'E' shows up for some reason.

Please can you help and tell me what could be the reason. There are other line charts also in the same container, which remains transparent always on hover too.

https://jsfiddle.net/sreejithga/an74zukd/4/

Normal
--------
![image](https://user-images.githubusercontent.com/53110553/125614089-f2527630-732f-40d6-84e7-71b6d427664b.png)

On hover to a certain part of the container, the line shows up, you can see my mouse in the picture and the line that suddenly appeared
---------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/53110553/125614197-70d24ea9-789c-4ef3-86dd-720bf20b1467.png)

**Comment by khlieng** [comment]
You could fix this by setting `states.inactive.opacity` to `0`: https://jsfiddle.net/5w40oczs/

**Comment by Sreejithga** [comment]
Thank you so much.. :)
