### ISSUE TITLE
Flag series is hidden when chart width is fixed when text is long

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#16041]
#### Expected behaviour
Flag series is hidden when chart width is fixed when text is long.

#### Actual behaviour
Flag series should show up, may be with some ellipsis text overflow.

#### Live demo with steps to reproduce
https://jsfiddle.net/07zok3t8/

On commenting out line no 3 in JS code, we can see flag series showing up.

#### Product version
Highstock JS v9.1.2 

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

**Comment by karolkolodziej** [comment]
_Internal note:_

The part which is failing is the code bellow. the `box.pos` isn't defined
``` TS
                    // Hide flag when its box position is not specified
                    // (#8573, #9299)
                    if (!defined(box.pos)) {
                        (point.graphic as any).attr({
                            x: -9999,
                            anchorX: -9999
                        });
                        (point.graphic as any).isNew = true;
                    } else {
                        (point.graphic as any).isNew = false;
                    }
```
And the main reason why it is missing is the `H.distribution` method.
When we change how the `pos` is being calculated there we might see the flag. 
Demo: http://jsfiddle.net/BlackLabel/bhjmveo9/

I guess the fix should be placed somewhere here where we might add the styling to the text.
