### ISSUE TITLE
Highstock.NET: Legend not visible

### ISSUE THREAD

**Issue by eschgi** [highcharts/highcharts#16043]
#### Actual behaviour

I try to display the legend, but I'm not able to display it.

I tried to enable the legend with the following code.

```csharp

var chartOptions = new Highstock
{
    ...
    Legend = new Legend
    {
        Enabled = true,
    },
    ...
};
```

What I found out is that the generated JavaScript code doesn't set the "enable" property of the legend in JavaScript to true when the flag in .NET is set to true. 

But when the flag is set to false in .NET then also the "enable" property in JavaScript is set to false.

#### Product version

I use Highstock.NET in version 9.1.2.

Thanks in the meantime.

**Comment by KacperMadej** [comment]
Hi @eschgi 

Thank you for reporting the problem.

fyi @brofixo

**Comment by eschgi** [comment]
Hi @fceci90,

I personally found no workaround for the problem.

**Comment by fceci90** [comment]
@eschgi thank you. That is unfortunate.

To Highcharts, I also found that there are other properties in Legend that don't get brought over to JavaScript as well. Of the 4 I am using (Enabled, Align, VerticalAlign, and Y), only the Y value is brought over the others are not. I have not tested the other properties, but I suspect there will be other properties that don't work as well.

**Comment by brofixo** [comment]
Thank you for reporting this issue. I'm gonna take care of it next week.

**Comment by raf18seb** [comment]
The fix should be available in the next version that will be released tomorrow (July 5, 2022).

**Comment by raf18seb** [comment]
@brofixo could you answer the above question? ☝️

**Comment by fceci90** [comment]
Hi @brofixo, the issue with the range selector looks like it has been resolved and is working normally in the latest release. Thank you.
However, the issue with the legend not appearing when legend Enabled = true still exists for me.

**Comment by brofixo** [comment]
@fceci90 , I've just tested package Highsoft.Highstock v10.2.0.1 published 21th July and `"legend":{"enabled":true}` renders correctly. Please confirm that on your side and let me know.

**Comment by fceci90** [comment]
@brofixo I'm using `Legend = new Highsoft.Web.Mvc.Stocks.Legend
        {
            Enabled = true
        },`
and it does not show a legend for me. I also have a highsoft chart on the page. I commented out that code in case highsoft and highstock were interfering with each other, but the legend still does not show up.

I am using Highsoft.Highcharts and Highsfot.Highstock Nuget packages both versions 10.1.0.1 published on August 1, 2022.

**Comment by brofixo** [comment]
@fceci90 , please try to upgrade and let me know.

**Comment by fceci90** [comment]
@brofixo Yes that fixed it! Thank you. I apologize for not seeing the newer version in Nuget.
