### ISSUE TITLE
Random white gaps in X-Range chart between bars

### ISSUE THREAD

**Issue by heivo** [highcharts/highcharts#16042]
#### Expected behaviour

There should be no gaps between bars when there are no gaps in the series data.

#### Actual behaviour

Random white gaps between bars are rendered. When zooming in the gaps appear at different places.

#### Live demo with steps to reproduce

JSFiddle: https://jsfiddle.net/6gay3mcs/2/

![image](https://user-images.githubusercontent.com/12901858/125592914-0ec9fcab-2787-4ced-b695-2edf688010be.png)

After zooming:
![image](https://user-images.githubusercontent.com/12901858/125593018-b5fe06ff-ba85-4732-837c-701e9162e099.png)

#### Product version

Highcharts JS v9.1.2

#### Affected browser(s)

The screenshots above were taken in Chrome (Version 91.0.4472.114).
When using Firefox (89.0.2) the JSFiddle example initially does not show gaps but they still appear after zooming.

**Comment by heivo** [comment]
@khlieng thanks for the quick fix! Is it possible to also make a 7.x release with this fix once it is merged?

**Comment by khlieng** [comment]
We dont backport fixes but heres a plugin: https://jsfiddle.net/j73f8uLm/4/

**Comment by heivo** [comment]
That works for me, thanks alot :+1:
