### ISSUE TITLE
Added series points have markers unexpectedly appear

### ISSUE THREAD

**Issue by gwatts-klipfolio** [highcharts/highcharts#16052]
#### Expected behaviour

- If the marker.enabled is set to false on data points within a new series the markers should not appear. 

#### Actual behaviour

- When a new series is added followed by a Chart.redraw specifically disabled markers appear.
- Note, this also occurs when clicking on legend items to have them disappear then re-appear (This behaviour can be seen in the jsfiddle provided)

#### Live demo with steps to reproduce
https://jsfiddle.net/e96xy0z1/

- Click on a legend item to have an area disappear
- Click on the hidden legend item to have it reappear
- Notice the marker in the middle of the area, also notice in the spec that the marker is specifically disabled.
- Occurs with area and line charts

#### Product version
Highcharts: 9.0.1

**Comment by khlieng** [comment]
Related to #15480 @oysteinmoseng

**Comment by gwatts-klipfolio** [comment]
The workaround described in #15480 (Making the markers the same size as the line) works to hide the markers, however, we also need to disable the hover state (tooltip) for the markers in question. These will still appear.
