### ISSUE TITLE
Issue #15864 is closed but does still not work

### ISSUE THREAD

**Issue by HansR00** [highcharts/highcharts#16059]
#### Expected behaviour
As discussed in [the original issue](https://github.com/highcharts/highcharts/issues/15864)

#### Actual behaviour
https://jsfiddle.net/mcrossley/m9gyu6tr/3/ 
The fiddle still has the range selected on the left side while it should be on the right.

#### Live demo with steps to reproduce
See fiddle above

#### Product version
Highstock 9.1.1

#### Affected browser(s)
All

**Comment by khlieng** [comment]
The fix has not been released yet, heres what it looks like: https://jsfiddle.net/dt0en58c/

**Comment by HansR00** [comment]
So when will it be released?

**Comment by khlieng** [comment]
There is no ETA at the moment, but it will probably at least 3-4 weeks until the next release.

**Comment by khlieng** [comment]
Heres a plugin with the fix: https://jsfiddle.net/jtx0mfLr/1/

**Comment by HansR00** [comment]
Thanks
