### ISSUE TITLE
Panning problem on highstock mobile

### ISSUE THREAD

**Issue by klhebs** [highcharts/highcharts#16055]
#### Expected behaviour
panning should be available to reach any point on the series

i need to use the ordinal axis because my chart also have to display minute data of days, i need the ordinal axis to handle the trading break between trading hour
#### Actual behaviour

when it pan to a certain mark it will bounce back so user cannot pan toward the start.
#### Live demo with steps to reproduce
[https://codesandbox.io/s/highcharts-vue-demo-forked-jscmz?file=/src/components/Chart.vue](https://codesandbox.io/s/highcharts-vue-demo-forked-jscmz?file=/src/components/Chart.vue)
step
1. click the open in new window 
2. use inspect the web and switch to any mobile environment
3. pan toward the start of the data then click the add data button (important: try panning first then add data otherwise is fine)
4. keep panning toward the start and the min will stuck at a certain time that bounce the extremes back

#### Product version

9.1.2

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

**Comment by khlieng** [comment]
Bisected to 9ea0e0b @karolkolodziej 😉

**Comment by khlieng** [comment]
Demo without vue: https://jsfiddle.net/8ucx1kjs/

**Comment by karolkolodziej** [comment]
_Internal note:_
`extendedOrdinalPositions` is not being recalculated after adding/updating the data.
Add `afterUpdate` event to recalculate the `extendedOrdinalPositions` and assign it to the ordinal axis.

**Comment by pawelfus** [comment]
> Add afterUpdate event to recalculate the extendedOrdinalPositions and assign it to the ordinal axis.

Event is already there, just add the cleanup: 
https://github.com/highcharts/highcharts/blob/49a925eb98237f8d303a3fe90431ea2a8bf2e9b3/ts/Core/Axis/OrdinalAxis.ts#L1288-L1294

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/qk3bvoys

Plugin: 
```js
(function(H) {
  H.addEvent(
    H.Series,
    'updatedData',
    function() {
      const xAxis = this.xAxis;
      // Destroy the extended ordinal index on updated data 
      if (xAxis && xAxis.ordinal) {
        delete xAxis.ordinal.extendedOrdinalPositions;
      }
    }
  );
})(Highcharts);
```
