### ISSUE TITLE
edit a line by draggable-points

### ISSUE THREAD

**Issue by igarciafe** [highcharts/highcharts#16064]
#### Expected behaviour
It must be possible to edit a line by dragging the points on lower scales.

#### Actual behaviour
If I scaled a stock graph and draw a line, when I try to edit the line, the draggable-point doesn't follow the mouse.

#### Live demo with steps to reproduce
You can reproduce this problem even in  the demo on your website:

https://user-images.githubusercontent.com/79041910/126065372-a5bdcfd7-fe52-458c-a209-a2184826fe18.mp4

#### Affected browser(s)
I'm using Chrome versión 91.0.4472.124.

**Comment by khlieng** [comment]
Bisected to 8d24cad @karolkolodziej, does not seem to be fixed by #15987, reproducible in https://www.highcharts.com/samples/stock/demo/stock-tools-gui even without touching extremes:

1. Create line annotation
2. Try dragging control point

**Comment by karolkolodziej** [comment]
Thank you for reporting that!

I've tested your scenario with the fixed from PR #15987.
Everything seems to work fine with that fix.
For now, you might use the 9.1.1 version as a workaround.

Demo: http://jsfiddle.net/BlackLabel/5yuhrp8s/
