### ISSUE TITLE
Waterfall chart not displaying data labels

### ISSUE THREAD

**Issue by maxworkday** [highcharts/highcharts#16066]
#### Expected behaviour
data labels always displayed

#### Actual behaviour
data labels are hidden depending on max/min values
for example:
if you set min: 75 - labels displayed
if you set min: 70 - labels hidden

#### Live demo with steps to reproduce
https://jsfiddle.net/6h70uwrj/37/

#### Product version
Highcharts v8+

#### Affected browser(s)
any browser

**Comment by KacperMadej** [comment]
Hi @maxworkday 

Thank you for reporting the problem.

Please check a workaround in the issue linked below.

Duplicate of https://github.com/highcharts/highcharts/issues/15334
