### ISSUE TITLE
Add custom tooltip for x axis label hover action

### ISSUE THREAD

**Issue by saikumar-madana** [highcharts/highcharts#16071]
Hi,

I want to show a custom tooltip on hover of label on x-Axis. I tried to use something like below:

```
this.chartOptions.xAxis['labels'].events.mouseover = (e) => {
      e.chart.renderer.label("tooltip text", e.x, e.y, 'rectangle').css({
        color: '#FFFFFF'
      })
      .attr({
        fill: 'rgba(0, 0, 0, 0.75)',
        padding: 8,
        r: 4,
      })
      .add()
      .toFront();
    }
```

But, here the problem is the **event does not have any renderer** in it. So, not able to add the custom label. Please help me solve this problem. 
I am using angular and highcharts angular.

Thanks

**Comment by KacperMadej** [comment]
Hi @saikumar-madana 

For technical support see https://www.highcharts.com/blog/support/

Please contact technical support with a live demo of the chart in question.
We are using GitHub issues in this repository to track bugs and to use for feature requests.
