### ISSUE TITLE
`resetSelection` does not exist on `ChartSelectionContextObject` Typescript type

### ISSUE THREAD

**Issue by ashleyryan** [highcharts/highcharts#16076]
#### Expected behaviour

`resetSelection` is a prop on `ChartSelectionContextObject` type

#### Actual behaviour

I was following this example for determining if the chart is currently zoomed in: https://stackoverflow.com/questions/66536206/styling-highcharts-reset-zoom-button-with-material-ui-button

But with typescript, I have to extend the `ChartSelectionContextObject` type on the `selection` event to add support for the property.

```
const onChartSelection: ChartSelectionCallbackFunction = (
    e: ChartSelectionContextObject,
  ) => {
    if ((e as any).resetSelection) {
      setIsZoomed(false);
    } else {
      setIsZoomed(true);
    }
    return undefined;
  };

const options: Options = {
    chart: {
      zoomType: 'xy',
      panning: {
        enabled: true,
        type: 'xy',
      },
      panKey: 'shift',
      events: {
        selection: onChartSelection,
      },
    },
  };
 ```

#### Product version
9.1.2

**Comment by KacperMadej** [comment]
Hi @ashleyryan 

Thank you for reporting the problem.

_Internal note:_
This is probably related to `any` casting in drill down module as this prop is used there
https://github.com/highcharts/highcharts/blob/49a925eb98237f8d303a3fe90431ea2a8bf2e9b3/ts/Extensions/Drilldown.ts#L1709-L1710

and is also related to another `any` casting in here
https://github.com/highcharts/highcharts/blob/e6da93c9462d4c2b45d5d85f0734e837b56f1b24/ts/Core/Chart/Chart.ts#L3515-L3524
