### ISSUE TITLE
Gantt chart tooltip does not dynamically shift

### ISSUE THREAD

**Issue by conniebernard-wk** [highcharts/highcharts#16081]
#### Expected behavior

Tooltip arrow should move with tooltip box along/around gantt chart bar as space runs out. 

This [example](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/marker-clusters/europe/) models expected behavior, as the mouse hovers over clusters near the bottom the arrow on the tooltip switches from top to bottom as space allows. 

#### Actual behavior

The tooltip arrow remains fixed to the top center of the gantt bar, rather than moving to the bottom center or side of chart as needed based on size of tooltip/surrounding space. Tooltip arrow should point to the outside of the gantt bar closest to the tooltip box. e.g. the top when the box is above, and the bottom when the box is below

#### Live demo with steps to reproduce

[Live Demo](https://jsfiddle.net/t8s0aor6/)
- Hover mouse over the top gantt bar. The tooltip arrow should be fixed to the top center of the bar while the tooltip box appears over the bar, obscuring it.
- Hover mouse over any other gantt bar. The tooltip arrow wills still be fixed to the top center of the bar, but the box will appear over the bar, and the gantt bar will remain unobscured. 

#### Product version
Highcharts 9.1.2

#### Affected browser(s)

All

**Comment by KacperMadej** [comment]
Hi @conniebernard-wk 

Thank you for reporting the problem.

**Comment by raf18seb** [comment]
@KacperMadej I would say it's a more general Highcharts issue, not related to the Gantt only.

Simplified demo with the xrange series in Highcharts: https://jsfiddle.net/BlackLabel/56742Lfc/
