### ISSUE TITLE
Selection for multiple points on line series does not work

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#16083]
#### Expected behaviour
When dragging with selection, the selection for multiple points should work the same for scatter and line series.

#### Actual behaviour
Only one point gets highlighted

#### Live demo with steps to reproduce
https://jsfiddle.net/nevo6j5x/

select multiple points and notice, that only 1 point is selected.
NOTICE: Doesn't work on firefox for UBUNTU 20.04

Reported by the user on Highcharts official Forum: 
https://www.highcharts.com/forum/viewtopic.php?f=9&t=46928#p168724

#### Product version
v9.1.2

#### Affected browser(s)
Firefox on Ubuntu 20.04

**Comment by khlieng** [comment]
So in the screenshot in the forum post there are no markers, this happens when the chart is below a certain width and can be seen in all browsers, setting a lower `enabledThreshold` will prevent that from happening.
