### ISSUE TITLE
Website error in IE11

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#16086]
#### Behaviour
Bad syntax in
```
<script async="">
  window.addEventListener('load', () => {
```
in https://www.highcharts.com/demo/stock/stock-tools-gui
This is about `() => {` and is looks like a web site problem.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/stock/stock-tools-gui

**Comment by goransle** [comment]
Should be fixed now 👍
