### ISSUE TITLE
Sankey: chart broken when updating point with the same 'from' and 'to'

### ISSUE THREAD

**Issue by crohit7** [highcharts/highcharts#16080]
#### Expected behaviour
Chart should render with updated color

#### Actual behaviour
Chart is broken

#### Live demo with steps to reproduce
https://jsfiddle.net/frnmdL5x/

#### Product version
9.1.2

**Comment by raf18seb** [comment]
Hi @crohit7, thanks for reporting the issue.

This happens when updating any point when one of the points goes to itself.

Simplified demo: https://jsfiddle.net/BlackLabel/aomk7fsd/

**Comment by crohit7** [comment]
yes, exactly @raf18seb

**Comment by crohit7** [comment]
@raf18seb @khlieng 
Looks like issue is fixed at your end.
Can we get beta version so that we can verify at our end
We have product launch in next week, could you please let us know by when we will get actual fix for this?
Thanks!

**Comment by khlieng** [comment]
The release is probably at least about 3 weeks away, heres a plugin you can use while waiting: https://jsfiddle.net/ek8hdj1o/2/

**Comment by crohit7** [comment]
@khlieng Thanks for the update
