### ISSUE TITLE
Finding width of secondary yAxis

### ISSUE THREAD

**Issue by h11a** [highcharts/highcharts#16107]
Hi 

Is there anyway way to get the width of the secondary yaxis in terms of the scale and the label.

For example: 

![image](https://user-images.githubusercontent.com/52792193/127124777-9a194a9b-20b1-4eea-8094-19fc4aa6e6d8.png)

This is the sandbox i am using.

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/combo-dual-axes

This is probably simple but I can't see a way of doing it.

I have tried combining multiple values such as ```charts[i]['axes'][1].right``` and ```charts[0].plotSizeX``` but it always seems to give a value that is either too large or too small depending on whether the label wraps onto 2 lines. The yAxis width also seems to give the width of the chart, is this expected?

Any help is appreciated 

Thanks

**Comment by raf18seb** [comment]
Hi @h11a! GitHub is our bug/features tracker only. With support questions, please contact us on other dedicated support channels: https://www.highcharts.com/blog/support/

**Comment by h11a** [comment]
@raf18seb Alright will ask on the forumn
