### ISSUE TITLE
Tooltips at beginning and end  of timeseries defaulting to highest and lowest value

### ISSUE THREAD

**Issue by mrclapham** [highcharts/highcharts#16102]
# Description of the feature
On timeseries the first and last date/values are often the most crucial to know. On larger sets it is difficult to hit the exact correct pixel at the beginning and end due to the values inhabiting a fraction of a pixel. A 'buffer' zone where the highest/lowest would be displayed would be very useful.
# Library related to the feature
Highcharts / Highcharts Stock

It affected a project I am working on. I'm not able to share due to confidentiality rules.

**Comment by KacperMadej** [comment]
Hi @mrClapham 

Thank you for submitting the feature request.

If the chart's background will have class `highcharts-tracker` then it will allow showing tooltip and the found point will be closest one so hovering outside of the series plot but still over the chart will show the tooltip for the edge points. To increase the "buffer" zone you could change [margin](https://api.highcharts.com/highcharts/chart.margin) options in the chart.

Demo: https://jsfiddle.net/BlackLabel/654u1o30/
