### ISSUE TITLE
Highchart with HIQPDF

### ISSUE THREAD

**Issue by Kumaresan165** [highcharts/highcharts#16103]
The HIQPdf will just convert the HTML directly into the PDF. It works fine with HighChart V8.x but not with V9.x. As per the analysis the HIQPdf is working fine. I think there is some change with HighChart V9.x which is causing this. Can you please look into this.

You can download the demo application of HIQPDF from the link provided below
 https://www.hiqpdf.com/downloads.aspx

**Comment by khlieng** [comment]
Fixed on master (#15940).

**Comment by Kumaresan165** [comment]
great, Thanks, looks it is started working

**Comment by raf18seb** [comment]
Linking the first reported ticket: https://github.com/highcharts/highcharts/issues/15894

**Comment by Kumaresan165** [comment]
we want to upgrade the latest version of highchart. we will get latest stable version with this fix also?

**Comment by khlieng** [comment]
Yes, it will be included in the next release.

**Comment by Kumaresan165** [comment]
Thanks! got it, any idea that when will be next stable release?

**Comment by khlieng** [comment]
In a few weeks i would expect.

**Comment by Kumaresan165** [comment]
got it, Thank you.
