### ISSUE TITLE
Axis.update causes plot lines to disappear

### ISSUE THREAD

**Issue by metre-netapp** [highcharts/highcharts#1611]
Using highcharts 3.0 if I update an axis that has plot lines they disappear after the axis update.

Example:
http://jsfiddle.net/etre0/ESqBP/

**Comment by randomjohnnyh** [comment]
I believe this causes plot lines to be duplicated instead of disappearing after an axis update, especially when repeatedly adding/removing plot lines.

**Comment by randomjohnnyh** [comment]
This is a combination of two issues: plot bands/lines are not removed from userOptions.plotBands/Lines upon removePlotBandOrLine. In addition, plot bands/lines are not updated until a redraw, which is extremely confusing for code that tries to modify them in between an update and a redraw.

The above fix is definitely not ideal.
