### ISSUE TITLE
Data labels on vertical bar chart inconsistency

### ISSUE THREAD

**Issue by lamqhoan** [highcharts/highcharts#16110]
#### Expected behaviour
Labels should either wrap or fit into a single line.
Overflow ellipse should only be used when lines are not allowed to wrap.
There shouldn't be a case of some labels can be wrapped while some are done with overflow ellipsis

#### Actual behaviour
Some labels can be wrapped while others overflow (demonstrated in the jsfiddle below)

#### Live demo with steps to reproduce

https://jsfiddle.net/5w7pnjq8/

#### Product version

Highcharts 9.1.2

#### Affected browser(s)
Google Chrome

**Comment by PyroSA** [comment]
https://jsfiddle.net/p8why9re/

Stripped the includes down to only highcharts and highcharts-3d.

labels.skew3d does not seem to affect this - the output remains:
```
...
<text x="164.64830084166292" style="color: #666666; cursor: default; font-size: 11px; fill: #666666" text-anchor="middle" transform="translate(0,0)" y="382.7574807205684" z="94.65215317431321" opacity="1" >
  FooBar FooBar
  <tspan dy="14" x="164.64830084166292">&ZeroWidthSpace;</tspan>
  FooBar FooBar
</text>
<text x="253.24604185738355" style="color: #666666; cursor: default; font-size: 11px; fill: #666666" text-anchor="middle" transform="translate(0,0)" y="392.3637456870303" z="69.26575460945375" opacity="1" >
  <title>Nothing wraps any more</title>
  Nothing wrap…
</text>
...
```

Note that the first is split with the tspan, the second is exactly the ellipse value.

![image](https://user-images.githubusercontent.com/3801259/127167221-cc482f7d-79f9-4138-af36-29ecceb3eaae.png)

**Comment by raf18seb** [comment]
Hi, thanks for reporting a problem. Seems like a bug, or at least very intuitive behavior.

Slightly simplified demo: https://jsfiddle.net/BlackLabel/4mg5zrfp
