### ISSUE TITLE
Drilldown is no longer passing through originalEvent.

### ISSUE THREAD

**Issue by sturichardson** [highcharts/highcharts#16115]
#### Expected behaviour
Chart drilldown event is no longer passing through the originalEvent as it used to... instead it is undefined.

#### Actual behaviour
In drilldown.src.js line 1025
A new function has been added:

        Point.prototype.doDrilldown = function () {
            this.runDrilldown();
        };

it should be:

        Point.prototype.doDrilldown = function (holdRedraw, category, originalEvent) {
            this.runDrilldown(holdRedraw, category, originalEvent);
        };

This change appears to overcome the bug that has been introduced by my upgrading the version of highcharts that we are using.

#### Product version
Highcarts9.1.2

#### Affected browser(s)
All

**Comment by khlieng** [comment]
There are no calls to `doDrilldown` from within the highcharts codebase, the old version of `doDrilldown` was renamed to `runDrilldown`, were you calling it yourself and passing in an event?

**Comment by sturichardson** [comment]
I am using https://www.npmjs.com/package/highcharts-custom-events which calls doDrilldown and I am also calling it in another part of my codebase.

**Comment by khlieng** [comment]
@sebastianbochan should custom-events perhaps call `runDrilldown` instead?

**Comment by raf18seb** [comment]
Hi,

@sturichardson thanks for reporting.

@khlieng there are no calls in the core code, but it can be called by a user and it's a part of our official API, see: https://api.highcharts.com/class-reference/Highcharts.Point#doDrilldown
Demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/drilldown/programmatic

We should always try to backport the old versions and I don't see any reason why the new `doDrilldown` should not pass the arguments.

Tagging as a regression for now. Maybe @TorsteinHonsi will say more.
