### ISSUE TITLE
Narrator with Edge is not reading point description of each point of HeapMap

### ISSUE THREAD

**Issue by shwetanana** [highcharts/highcharts#16116]
#### Expected behaviour
Narrator with edge should read point description of point in HeatMap.

#### Actual behaviour
Narrator with edge is not reading point description of each point in HeatMap. Its reading only for the 1st point description

#### Live demo with steps to reproduce

step1: open https://jsfiddle.net/14br7d2y/27/
step2: Turn on the Screen Reader(Narrator for edge ), Navigate using tab.
step3: It receives focus on the 1st point.
step4: It reads point description of 1st point.
step5: 
- Pressing down arrow, focus is going to the end of chart 
-  Pressing left arrow, focus is moving but Narrator is not reading it's description.

#### Product version

Highcharts: 9.1.0

#### Affected browser(s)
Edge

**Comment by raf18seb** [comment]
Probably related to #16114 , closing as a duplicate. Please, feel free to reopen if sure it's not related.

**Comment by shwetanana** [comment]
Hi @raf18seb  This bug is related to HeatMap narrator issue.
