### ISSUE TITLE
Narrator with Edge is not reading point description of each bar in  bar/column chart

### ISSUE THREAD

**Issue by shwetanana** [highcharts/highcharts#16114]
#### Expected behaviour
Narrator with edge should read point description of each bar/column in bar/column chart

#### Actual behaviour
Narrator with edge is not reading point description of each bar/column in bar/column chart. Its reading only for the 1st bar/column description

#### Live demo with steps to reproduce
**For Bar Chart**
step1: open https://jsfiddle.net/3865qxvy/2/
step2: Turn on the Screen Reader(Narrator for edge ), Navigate using tab.
step3: It receives focus on the 1st bar.
step4: It reads point description of 1st bar.
step5: Pressing down arrow, focus will be at next bar but narrator is not reading it expected description.

**For Column Chart**
step1: open https://jsfiddle.net/3865qxvy/4/
step2: Turn on the Screen Reader(Narrator for edge ), Navigate using tab.
step3: It receives focus on the 1st column.
step4: It reads point description of 1st column.
step5: Pressing right arrow, focus will be at next column but narrator is not reading it expected description.

#### Product version

Highcharts: 9.1.0

#### Affected browser(s)
Edge

**Comment by raf18seb** [comment]
Hi @shwetanana, thank you for creating the ticket.

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
Internal note: Works as expected with VoiceOver in latest Edge on macOS. Could be a Narrator issue.
