### ISSUE TITLE
different border color for different points not working with stockChart

### ISSUE THREAD

**Issue by araju57** [highcharts/highcharts#16125]
Hi,

I would like to specify different border colors to each point based on the critical level using stockChart column type graph
but i could not find any solution, please suggest if anything can be done

and also i would like to display datalabels to describe the colors applied to borders.

#### Live demo with steps to reproduce
https://jsfiddle.net/a5e4qct8 -- Not working with stockChart
https://jsfiddle.net/a5e4qct8/1/ -- working with chart

**Comment by khlieng** [comment]
Column `borderWidth` defaults to `0` in stock, so you need to set it: https://jsfiddle.net/x7zLpyak/

**Comment by araju57** [comment]
Hi,
thank you, its working but same not working for below graph

https://jsfiddle.net/42mq8arz/1/

 https://jsfiddle.net/42mq8arz/2/  - Not working

and i need labels like in attached image for the border colors

![image](https://user-images.githubusercontent.com/79351195/127860937-f478a532-5a11-4586-abaf-bc8b5b39b8a1.png)

**Comment by raf18seb** [comment]
Hi @araju57,
you are defining your data incorrectly.

GitHub is our issues (and features) tracker only. For any support questions or problems, please use our other dedicated channels: https://www.highcharts.com/blog/support/
