### ISSUE TITLE
Original series gets messed-up upon drill-up from drill-series back to original-series

### ISSUE THREAD

**Issue by rdp1414** [highcharts/highcharts#16135]
#### Expected behaviour
The original series should remain the same before drilling down to drill-series and after drilling up back to original series.

#### Actual behaviour
Upon drill-up from drill down series back to original series, two problems occur:
1. There appear white spaces in original series.
2. The last xAxis label is faulty.

#### Live demo with steps to reproduce
Reproducer of above bug - See [fiddle](https://jsfiddle.net/2dn37Lra/).

#### Product version
Highcharts version `9.1.2`

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment]
Hi @rdp1414, thank you for reporting the bug.

Simplified demo: https://jsfiddle.net/BlackLabel/dLne23pz/

**Comment by rdp1414** [comment]
Hello Highcharts Team,

Can you please tell what is the ETA for this issue?

**Comment by raf18seb** [comment]
Hi @rdp1414,

We will provide more info soon.

For now, you can use this workaround (set `series.cropThreshold` to a higher value): https://jsfiddle.net/BlackLabel/aumsne6q/
