### ISSUE TITLE
Tooltips has visibility: visible even though it is hidden

### ISSUE THREAD

**Issue by wederer** [highcharts/highcharts#16140]
#### Expected behaviour
Tooltips that are not visible should have `visibility: hidden` as a style.

#### Actual behaviour
When using `useHTML: true` in conjunction with `hideDelay: 0` tooltips will keep their visibility set to `visibility: visible` even after vanishing via `opacity: 0`.
In our project this lead to an invisible tooltip covering part of our chart, which - as a result - did not receive ClickEvents anymore. A workaround for us was setting `hideDelay: 1` (any value above 0 works), but this should probably be fixed and in both cases `visibility` should be set to `hidden`.

#### Live demo with steps to reproduce
https://jsfiddle.net/bg8x3tfs/6/

#### Product version
9.1.2

#### Affected browser(s)
All of them would be my guess.

#### Note
I tried finding the corresponding code in the highcharts project, but could not determine where the visibility is set. If somebody points me in the right direction I will open a PR.

**Comment by khlieng** [comment]
This will get fixed by #16054: https://jsfiddle.net/4fnuLz72/
