### ISSUE TITLE
inlined image (png) encoded in base64 doesn't apply as a label

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#16149]
#### Expected behaviour

The image should be rendered as a xAxis label. Should work as in 8.2.2 version: https://jsfiddle.net/BlackLabel/aLx4o7u3/

#### Actual behaviour

Nothing shows up. 

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/q57xtugd/ (works fine in 8.2.2)

#### Product version

Highcharts JS v9.1.2 (2021-06-16)

**Comment by khlieng** [comment]
Workaround: `Highcharts.AST.allowedReferences.push('data:')`
