### ISSUE TITLE
Sunburst chart - Issue observed when drill down to first level.

### ISSUE THREAD

**Issue by harshad-kumbhar** [highcharts/highcharts#16146]
Expected behavior - Chart should display properly

Actual behavior - Chart is broken after drill down

Live demo with steps to reproduce
https://jsfiddle.net/p0vgzr41/

Product version
9.1.2

Chart before drill down-
![image](https://user-images.githubusercontent.com/59466420/128168492-2a36dcdf-e3f4-4aa7-a640-6cf5a4c9555a.png)

Chart after drill down-
![image](https://user-images.githubusercontent.com/59466420/128168547-8954ddbb-8968-4c6e-af45-3411b59f59ae.png)

**Comment by khlieng** [comment]
Its broken before drilldown as well, and its caused by the negative values: https://jsfiddle.net/xte4qwc2/5/

**Comment by harshad-kumbhar** [comment]
Thank you @khlieng 
Can you provide me any other solution, In which the sunburst chart can support negative values without manipulating the data?

**Comment by khlieng** [comment]
I guess this should work the same way as in pie charts where negative values are not shown at all, I'll tag this as a bug.
