### ISSUE TITLE
Column Range stacking doesn't work in v9 release

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#16148]
#### Expected behaviour
Column range stacking should have the same behavior as it did in V8.

![image](https://user-images.githubusercontent.com/14222462/128214332-e51d8490-0f4c-4ce1-9c57-995ce52d4945.png)

#### Actual behaviour
The stacking option is being ignored.

![image](https://user-images.githubusercontent.com/14222462/128214489-0f50ea6a-b877-4b45-8a4b-89c73880a430.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/vfh0jw85/
Initial rendering is with 8.1 which works correctly, update the script tags to use 9.0 and you will see the new incorrect rendering.

#### Product version
V9.0

#### Affected browser(s)
Chrome

**Comment by khlieng** [comment]
See https://github.com/highcharts/highcharts/issues/14359#issuecomment-712662410 for more info on why this change happened.

**Comment by Rashaine** [comment]
Grouping doesn't seem adequate in this case where we need specific columns to overlap into specific "stacks". Is there an approach to reproduce the v8 rendering with grouping that I'm missing?

**Comment by khlieng** [comment]
Perhaps something like this?: https://jsfiddle.net/j7Lp6efo/

**Comment by Rashaine** [comment]
That's basically the workaround we came up with too but it required a bit of coding to calculate the correct placements based on the dynamic stacks. I would much prefer for Highcharts to re-add stacking support but that workaround should do for now. Thank you.

**Comment by bazzacad** [comment]
I'm having the same issue. My Columnrange used to stack correctly in V8 & no longer does in V9.
The pointPlacement workaround won't work, as each person has a different stack.

**V8**
![image](https://user-images.githubusercontent.com/23222121/140162015-1d543a6f-5e83-426c-89f0-2aceac37e0ea.png)

**V9**
![image](https://user-images.githubusercontent.com/23222121/140162103-ced2f6d0-6c70-4820-97b6-3e08aee9cc38.png)
