### ISSUE TITLE
Series Line using the processedData instead of the data 

### ISSUE THREAD

**Issue by haroldlatina** [highcharts/highcharts#16144]
#### Expected behaviour
The created series line will use the passed data for plotting the line 
![image](https://user-images.githubusercontent.com/51808505/128112704-ff5e06e9-180e-4e22-bd14-41d46d1a05a0.png)

#### Actual behaviour
The created series line uses a different data points w/c causes misalignment on the series line

**Comment by raf18seb** [comment]
Hi @haroldlatina, is there anything we should check? Or the ticket should remain closed?

**Comment by haroldlatina** [comment]
hi @raf18seb this issue still persists

**Comment by raf18seb** [comment]
@haroldlatina could you provide more info about your issue then? A live demo would be perfect. Thanks!
