### ISSUE TITLE
setExtremes() isn't honoured exactly with variwide series type

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#16155]
Consider the following example:

https://jsfiddle.net/6z4520fs/

In the load event I am trying to set the xAxis extremes as follows:

    this.xAxis[0].setExtremes(1, 4);

I want the x axis to start exactly at 1 and end exactly at 4, regardless of the data, and regardless of whether this chops a variwide column short. At present, highcharts is choosing to show me from 0.75 to 4.25... rather than what I have actually asked for.

I suspect that this is intended behaviour but IMHO it is incorrect to effectively ignore what has been asked for.  Maybe this should be a feature request rather than a bug report?

**Comment by khlieng** [comment]
Works with `pointPlacement: 'on'`: https://jsfiddle.net/stw71nLf/

**Comment by drmrbrewer** [comment]
Out of interest, what is the rationale behind this behaviour, and is it consistent with column series?

**Comment by raf18seb** [comment]
@drmrbrewer,

Yes, it is consistent with the column series: https://jsfiddle.net/BlackLabel/y2dhvstb/
More info: https://api.highcharts.com/highcharts/series.column.pointPlacement

**Comment by drmrbrewer** [comment]
@raf18seb thanks.  I've just noticed that `pointPlacement` doesn't seem to have any actual affect on point placement with `variwide`... in other words, `x` still sets the *start* of the column (with `z` setting the width)?  All it does is affect the behaviour of `setExtremes()`?  This seems a bit misleading/inconsistent to me, but so long as it provides an easy switch for me to achieve the effect I want, I'm not complaining!
