### ISSUE TITLE
Line chart Data Labels do not work the same way as other charts on click

### ISSUE THREAD

**Issue by tanmaya-git** [highcharts/highcharts#16152]
When I click on the data label in the line chart, the event does not return the point value where as for other charts like bar, column, pie, donut etc when I click on the data label, it gives the point value. How do I obtain the point value when I click on the data label. I am using it in angular

**Comment by raf18seb** [comment]
Hi @tanmaya-git!
What event are you writing about? The point click event is working fine when clicking on both point and dataLabel for the line series, see demo: https://jsfiddle.net/BlackLabel/7bq90tzd/

If this is the case and you need further support, please contact us on dedicated support channels, more info: https://www.highcharts.com/blog/support/ (GitHub is our issues and features tracker only).

If you believe that this is a bug, then please reproduce it in an online demo (jsFiddle would be perfect) with steps to reproduce, and feel free to reopen the ticket.
