### ISSUE TITLE
The columnpyramid series isn't working with yAxis width and inverted

### ISSUE THREAD

**Issue by TheresaJoy** [highcharts/highcharts#16150]
Hi, 

I posted this issue in Highcharts Forum. So  Higcharts Developer @K009   suggested that I post it here to have a closer look into it. 

We tried  to get a vertical version of this:
https://jsfiddle.net/Theresa_Joy/4x6rfom9/16/

We tried to get it done, and this is our result.
https://jsfiddle.net/Theresa_Joy/j270L9y5/36/

There seems to be no script error, but we only see kind of bars with a slight angle instead of pyramids.
We checked this in Chrome, Mozilla and Edge.

Reply of @K009 
It happens because the axis is smaller (eg. 25% instead of 100%) and the points don't have enough place to be displayed, which results in no angled corners. Simplified demo with this issue: https://jsfiddle.net/BlackLabel/o390gwje/

I think that it might be a bug. Could you report it on our GitHub so we could take a closer look at it?
Here's a link: https://github.com/highcharts/highchart ... new/choose

**Can you pls. check it out at the earliest and let us know.** This is one very important feature we want to have, for our graphs. Since Highcharts has already an inbuilt Column Pyramid Chart, it was a very good candidate for our choice.

**Comment by raf18seb** [comment]
Hi @TheresaJoy, thank you for reporting the bug.

Indeed, the `columnpyramid` has never worked with `chart.inverted` and `yAxis.width`.
Simplified demo: https://jsfiddle.net/BlackLabel/3d4t9hp1

**Comment by raf18seb** [comment]
Hi @TheresaJoy,

Our developer has started working on a fix which should be available soon in the next release version.

**Comment by TheresaJoy** [comment]
Thank you for the info. We would like to use this in our project if this issue is fixed. When would be approx. the next release?

**Comment by raf18seb** [comment]
@TheresaJoy,

We have found the problem and we hope that it will be fixed in the core soon.
We released v9.2.2 yesterday, so the next version should be released within few weeks (or months the most). We don't have ETA at this moment.

For now, you can use this workaround plugin: https://jsfiddle.net/BlackLabel/9qx6nuLt/
