### ISSUE TITLE
x-axis scrolling cause category merge with each other.

### ISSUE THREAD

**Issue by shantvan** [highcharts/highcharts#16162]
#### Expected behaviour
x-axis scrolling not properly work.

#### Actual behaviour
x-axis scrolling category is merge with each other.
please check live demo.

#### Live demo with steps to reproduce
https://jsfiddle.net/rt1ve5zb/

**Comment by pawelfus** [comment]
Hi @shantvan 

Thank you for contacting us. To prevent merging categories, please set [`xAxis.uniqueNames`](https://api.highcharts.com/highcharts/xAxis.uniqueNames) to false. Demo with current (v9.1.2) version: https://jsfiddle.net/BlackLabel/ts5369ec/ (v6 has bugs with scrollbar and categorized xAxis)

Let me know if you find any issues with the current version, thanks!

**Comment by shantvan** [comment]
Thanks @pawelfus.
