### ISSUE TITLE
Thin gap between plot bands

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#16161]
https://jsfiddle.net/9wqbmtxr/

In the above example, you should notice that there is a very thin gap between plot bands, despite ending one plot band and starting the next plot band at the same x axis value.  You may have to zoom in to see the gaps, because I suspect that they are only a pixel or two wide.  

Doesn't seem much but these gaps are very noticeable in some situations.  I'm trying to achieve a complicated contiguous fill effect (including some horizontal gradient fill) by placing multiple plot bands (corresponding to different time periods) side-by-side, but this isn't working as I'd like because of these gaps.

I did report this on the forum too (https://www.highcharts.com/forum/viewtopic.php?f=9&t=47061) but it was suggested there that it might be a bug.

**Comment by raf18seb** [comment]
Hi @drmrbrewer, thanks for creating the ticket!

Related to https://github.com/highcharts/highcharts/issues/7495, you can find more info in that ticket.

As a workaround, you can render the plotBands a little bit bigger: https://jsfiddle.net/BlackLabel/d1zef5uo/

**Comment by drmrbrewer** [comment]
@raf18seb I already tried making the bands slightly wider but the problem then is that (without knowing *exactly* what the gap is that needs filling, and applying an arbitrary amount as in your example) I end up with slightly overlapping bands... which creates a similar problem of unwanted vertical lines when the overlapping bands have opacity less than 1, because the opacities sum in the overlap to create a different rgba value there.

**Comment by raf18seb** [comment]
@drmrbrewer true. I checked rendering plotBands for 1px, 0.5px and 0.3px more, but the issue is still visible (either plotBands don't overlap enough, or plotBands are visible with doubled opacity: https://jsfiddle.net/BlackLabel/jtew8Lsd/

Unfortunately, as I said, this is a browser issue and there's nothing we can do in our code :(

**Comment by drmrbrewer** [comment]
😞😭

**Comment by raf18seb** [comment]
But... you can write a simple algorithm that would look for the plotBands that end and start in the same place and merge them into one plotBand.

For example:
Instead of `[{from: 0, to: 4}, {from: 4, to: 5}, {from: 5, to: 7}, {from: 9, to: 12}, {from: 12, to: 14}]` use just [{from: 0, to: 7}, {from: 9, to: 14}]`

**Comment by drmrbrewer** [comment]
I was just considering that as a possible solution but I have gradient fills not just solid fills, and furthermore there is a mix of gradient direction (some horizontal, some vertical) 😕

**Comment by pawelfus** [comment]
I'm curious if this is a case, where `shape-rendering: crispEdges` makes sense? I'm not sure about the gradient solution, but the basic example looks good, take a look: https://jsfiddle.net/BlackLabel/6ovy9akp/

**Comment by drmrbrewer** [comment]
@pawelfus I think you may be onto something there!  In my actual application (with gradient fills), this does seem to close the gap in most places, though sometimes there is still a very very thin line, whilst in other cases the gap seems to widen.  I'm not sure, however, whether those effects are more to do with the data I'm plotting, and the way I'm calculating the gradient fill stops etc, so I need to look into it further, and maybe try to create a simple jsfiddle to reproduce the issue more specifically.

Do you know of any possible downsides to using `shape-rendering: crispEdges` in the context of highcharts (other than what is stated in the docs for this SVG attribute: perhaps a drop in "rendering speed and geometric precision")?

**Comment by pawelfus** [comment]
> this does seem to close the gap in most places, though sometimes there is still a very very thin line, whilst in other cases the gap seems to widen. 

Interesting. In theory, when rendering two plotbands, where end_prev = start _next, then those should render exactly at the same pixel position on the screen (then antialiasing kicks in). Maybe you have a very narrow `borderWidth` option set?

> Do you know of any possible downsides to using shape-rendering: crispEdges in the context of highcharts (other than what is stated in the docs for this SVG attribute: perhaps a drop in "rendering speed and geometric precision")?

No, I don't know. Everything related to `shape-rendering` that affects Highcharts come from SVG.

**Comment by drmrbrewer** [comment]
As I had anticipated, the remaining thin (but slightly inconsistent) gaps I see in my actual application are due to some horrible kludge I put in a while ago to deal (rather badly) with a specific scenario (a zero-width band).  I've now put in a far less horrible kludge (in fact, not a kludge at all), and now there are no gaps!!  Of course, there were still gaps without with your `shape-rendering: crispEdges` fix (as seen the original jsfiddle demo... i.e. my kludge was not the sole cause of the gaps, but maybe exacerbated them), but with your `shape-rendering: crispEdges` fix it all looks perfect!  Thanks so much for this!
