### ISSUE TITLE
"borderRadius" disappears after hovering the pointer over plot in heatmap

### ISSUE THREAD

**Issue by PurpleTape** [highcharts/highcharts#16165]
Hello! 
Faced such a problem:

#### Expected behaviour
"borderRadius" doesn't disappear 

#### Actual behaviour
If you set the "borderRadius" of the plots, then after hovering over them with the pointer, the rounding disappears 
(https://api.highcharts.com/highcharts/series.heatmap.borderRadius)

#### Live demo with steps to reproduce
Live: https://jsfiddle.net/Lpsb2c1v/6/
1. Move the pointer over some plot
2. Move the pointer away

#### Product version
Version: 9.1.2

#### Affected browser(s)
OSX
Firefox: 90.0.2
Chrome: 89.0.4389.114

**Comment by pawelfus** [comment]
Hi @PurpleTape 

Thank you for reporting this bug!

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/wp1qa3gn/1/
Plugin:
```js
Highcharts.addEvent(
  Highcharts.seriesTypes.heatmap.prototype.pointClass,
  'afterSetState',
  function(e) {
    var point = this;
    if (point.graphic) {
      point.graphic.attr({
        r: point.series.options.borderRadius || 0
      });
    }
  }
);

```
