### ISSUE TITLE
Could not find Highchart class

### ISSUE THREAD

**Issue by saravanakumarRamraj** [highcharts/highcharts#16167]
#### Expected behaviour
Added "**implementation (name: 'highcharts-release-v9.1.2', ext:'aar')**" in build.gradle file, and Added ".aar" file locally in libs folder. The project should get built successfully. On running the project in Android Studio Arctic fox with Android SDK 30, the app should get loaded without any errors and high chart should display multicoloured graph as usual.

#### Actual behaviour
Added "**implementation (name: 'highcharts-release-v9.1.2', ext:'aar')**" in build.gradle file, and Added ".aar" file locally in libs folder. The project is getting built successfully. When I run the project in Android Studio Arctic fox with Android SDK 30, the app gets loaded with an error "Could not find :highcharts-release-v9.1.2:"

This was working fine with Android SDK 29, Only failing when I updated the node packages and moved to Android SDK 30.

**Comment by ankit-dev777** [comment]
Hi,

I am facing the same problem in my application as well. Can anyone please provide a solution for this?

I am unable to find any alternative graph library for high chart that can plot multicoloured gradient line chart.

**Comment by pawelfus** [comment]
Hi @saravanakumarRamraj  and @ankit-dev777 

Thank you for reporting the issue. Could you provide a bit more information?

- Did it work with the previous release versions (v9.1.1, v9.0.0, v8.0.0)?
- Is #16142 the same issue report? Should we close #16142?
- Could you provide a small package with the issue, so we can recreate the issue on our end? With info on how to set up the project (I don't have experience with "Android Studio Arctic fox")

Thanks!

**Comment by ankit-dev777** [comment]
Hi @pawelfus 

Thanks for your response. 
[Point 1]: The moment I upgraded the app to android SDK 30, none of the previous high chart versions are working. HighChart was working fine till SDK 29.
[Point 2]: Yes, you can close the second issue [Duplicate].
[Point 3]: This will take us sometime. I will share it with you soon.

**Comment by pawelfus** [comment]
Thank you for your answers @ankit-dev777 !

> [Point 1]: The moment I upgraded the app to android SDK 30, none of the previous high chart versions are working. HighChart was working fine till SDK 29.

Did you contact SDK 29 support? To me, it seems they broke something accidentally.

> [Point 2]: Yes, you can close the second issue [Duplicate].

Thanks!

> [Point 3]: This will take us sometime. I will share it with you soon.

Thanks!

**Comment by saravanakumarRamraj** [comment]
Hi @pawelf
[point3] 
create sample application using static data and repository link is  
https://github.com/saravanakumarRamraj/NewHighChartApp

this app create at android SDK 30 and arctic fox IDE, Hight chart library is 8.1.2
Thanks

**Comment by ankit-dev777** [comment]
@raf18seb Thanks for your analysis and response. We had raised the issue with SDK support team on 13th Aug and have not received any response from their side yet.

Here: https://issuetracker.google.com/issues/196441762

**Comment by pawelfus** [comment]
Thank you for the link!

The best workaround I can suggest right now is to downgrade SDK to version 29. This way, you won't be blocked with new releases.

I have starred the issue, I hope to get notifications when they will respond. I suggest adding the demo app (https://github.com/saravanakumarRamraj/NewHighChartApp) to the [ticket](https://issuetracker.google.com/issues/196441762?pli=1)
