### ISSUE TITLE
centerInCategory setting reverses stack groups order

### ISSUE THREAD

**Issue by OldBuddy** [highcharts/highcharts#16169]
#### Expected behaviour
`centerInCategory: true` in combination with `reversedStacks: false` shouldn't affect order of different stacks.

#### Actual behaviour
`centerInCategory: true` affects order of different stacks (also labels are misplaced).

#### Live demo with steps to reproduce
https://jsfiddle.net/gv4skudb/
(_series 1_ and _series 2_ stack group must be first)
#### Product version
8.1.1 and later

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi @OldBuddy, thank you for reporting the problem.

**Comment by OldBuddy** [comment]
Hi @raf18seb, any estimates on fixing this? It's quite affecting our UX.

**Comment by KacperMadej** [comment]
Currently, there is no other workaround than reversing the series in the chart options to get the correct order.
There is no ETA for the fix of the issue just yet.
Bumping priority of the issue.

**Comment by karolkolodziej** [comment]
Internal note:
`adjustForMissingColumns` method doesn't calculate the `indexInCategory` correctly and returns incorrect `x` position.
