### ISSUE TITLE
Overlapping of long labels with anchor tags in it and extra marginBottom issue

### ISSUE THREAD

**Issue by ujjwal502** [highcharts/highcharts#16173]
#### ISSUE
In version 6.2.0 :- When we have long labels having an anchor tag as we set useHTML as true, they are overlapping and they are not being wrapped. Also because of the autoRotationLimit ( that is 60 ), when they are being rotated, the text is clipped.
For the normal text, we set useHTML as false. So when we have a longer text, it is wrapped but we get extra margin bottom between the chart and the legend-item.

In the latest version that is 9.2.0, behaviour is very weird when we set useHTML as true. Please refer the fiddle links for more clarity on this.

#### Expectation
We would like to have a consistent behaviour in which we don't have to worry about the overlapping or extra margin bottom that is being talked about.

#### Live demo with steps to reproduce for version Highcharts-6.2.0
 https://jsfiddle.net/ujjwal03/2jkdxL45/27/

#### Live demo with steps to reproduce for version Highcharts-9.1.2
 https://jsfiddle.net/ujjwal03/2jkdxL45/29/

**Comment by ujjwal502** [comment]
hey @raf18seb if you toggle the useHTML property as true and false in both the fiddles ( i.e. both the versions ), you will see the difference. Please tell me if you need any more inputs after that.

**Comment by raf18seb** [comment]
@ujjwal502, thanks for providing more info!

Looks like a regression. Bisected to https://github.com/highcharts/highcharts/commit/faf7273f1eab6d361d1f420f00b32e9621f3c357

**Comment by ujjwal502** [comment]
yeah, thanks @raf18seb

**Comment by raf18seb** [comment]
@chetan1507 we will discuss this ticket at our next prioritization meeting. Do you have a valid Advantage license? If yes, please contact us at support@highcharts.com (with your license id), it will raise the priority.

**Comment by KacperMadej** [comment]
For the current version it is possible to set `style.textOverflow: 'ellipsis'` to  get:
https://jsfiddle.net/BlackLabel/4mnfh87a/2/

**Comment by TorsteinHonsi** [comment]
It has to do with how text lines are broken down in SVG to provide hyperlinks. I will look into this issue in a few days, just need to release v9.1.3 with a couple of critical issues.

**Comment by TorsteinHonsi** [comment]
Minimal demo: https://jsfiddle.net/vz4aogb1/

**Comment by TorsteinHonsi** [comment]
#### Workaround
A workaround, seemingly without side effects, is to put a `<span>` inside the anchors: https://jsfiddle.net/highcharts/384o6sdL/

**Comment by chetan1507** [comment]
<span> doesn't work in older releases. ellipses however does work in both, but that results in lesser optimised use of space in case the bar width is bigger
