### ISSUE TITLE
Unable to set the navigator type as line when boost enable in stock chart.

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#16179]
#### Expected behaviour
Being able to set navigator series type to the line when the boost is enabled to the main series.

#### Actual behaviour
From version 9.0.0 there is no possibility to set the navigator series type to `line` when the boost is enabled.
It looks like, from that version, the series in the navigator is grouped instead of boosting.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/0fy6vpnt/

#### Product version
From v.9.0.0

#### Affected browser(s)
All

**Comment by khlieng** [comment]
Probably caused by #15817, since 9.2.0 the grouped navigator series is at least visible.

**Comment by karolkolodziej** [comment]
The navigator series works correctly (as it used to work before v9) from the 9.2.0 version.
Bisect leads to: https://github.com/highcharts/highcharts/commit/31aeb7e25a7bebed00669c31114ce6dec2acfa1c
