### ISSUE TITLE
PDF export: have the same visual as the PNG export

### ISSUE THREAD

**Issue by SuzyR** [highcharts/highcharts#16175]
#### Expected behaviour

When exporting in pdf, i would like to have the same visual as the PNG export
I'm using wkhtmltopdf.

#### Actual behaviour
When exporting as pdf, labels are not in the box : 
![image](https://user-images.githubusercontent.com/88716169/128854663-8e8533b5-1e23-4bed-a329-e5598f914ea4.png)
However, exporting as png, everything is okay :
![image](https://user-images.githubusercontent.com/88716169/128854799-f0ae6c30-763e-4dd4-b2be-6bb9e319e9bc.png)

Is there an option to set ? Or maybe a way to have the same result ? 
#### Product version

    "@highcharts/map-collection": "^1.1.3",
    "highcharts": "^9.1.0",

#### Affected browser(s)
All

Thank you so much for your attention :)

**Comment by raf18seb** [comment]
Hi @SuzyR! Thanks for creating the ticket.

Can you reproduce this bug in a live demo? Or provide the exact steps so I can reproduce it anyhow? Thanks in advance

**Comment by SuzyR** [comment]
Hi :) thank you for your answer, here is the demo : https://jsfiddle.net/BlackLabel/t06hvxs8/

**Comment by raf18seb** [comment]
@SuzyR please double-check whether you forked your demo, because the demo above is a simple chart without any exporting module attached.

**Comment by SuzyR** [comment]
Sorry, i don't know jsfiddle very well.. 
https://jsfiddle.net/2xp7t8co/3/#&togetherjs=NsDxCh6dq1 and with this ?

**Comment by raf18seb** [comment]
There are buttons `Save` and `Fork` in the top-left corner. The last URL is enough.

You still haven't attached the `exporting.js` or any other module, so this is a forked demo with our `exporting.js` module, and both PNG and PDF files look exactly the same: https://jsfiddle.net/BlackLabel/L5xqnc4k/
