### ISSUE TITLE
Data labels rotation throws console error when value is other than 0

### ISSUE THREAD

**Issue by gs-vsingh** [highcharts/highcharts#16176]
Hi Team,

Whenever we are giving data label's rotation with any value(other than 0) throws errors in the console and doesn't behave as expected. And when data label is long and if rotation value is provided, then it doesn't show any data labels.

JSFiddle example:-
[https://jsfiddle.net/KrishnaPriyaE/h06L3vzg/2/](https://jsfiddle.net/KrishnaPriyaE/h06L3vzg/2/)

We have used highcharts V8.x in an angular project.

All browser have the same issue.

**Comment by raf18seb** [comment]
Hi @gs-vsingh, thanks for reporting the issue!

Simplified demo: https://jsfiddle.net/BlackLabel/4Lr7zpv5/
The dataLabels are rotated properly, just errors are thrown into the console.
