### ISSUE TITLE
The transform rotate isn't implemented

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#16171]
#### Expected behaviour
You should be able to animate rotation in SVGRenderer.

#### Actual behaviour
When you call `shape.animate({transform: rotate(...), duration}` you get an error ` attribute transform: Expected transform function, "…10547969, 164.5)NaN".`

#### Live demo with steps to reproduce

https://jsfiddle.net/BlackLabel/9b1p5vkn/19/

#### Product version
Highcharts V9.1.2
#### Affected browser(s)
all

**Comment by khlieng** [comment]
Why not just use the `rotation` attribute?: https://jsfiddle.net/xd4omfbu/

`transform` gets built in `SVGElement.updateTransform` based attributes like `rotation`, `rotationOriginX` etc.

**Comment by pawellysy** [comment]
Closing - not a bug
