### ISSUE TITLE
On load - segment line

### ISSUE THREAD

**Issue by haroldlatina** [highcharts/highcharts#16189]
#### Expected behaviour
Segment line will be created on load when there is a data for it, is there a function that I can call and pass data point so 
there will be a segment drawn on load?

#### Actual behaviour
You need to redraw everything

**Comment by raf18seb** [comment]
Hi @haroldlatina! GitHub is our bugs/features tracker only. If you have any support questions, please contact us on the other, dedicated support channels: https://www.highcharts.com/blog/support/
Thanks!
