### ISSUE TITLE
highchart column range border is disappearing sometimes

### ISSUE THREAD

**Issue by zuberspathan** [highcharts/highcharts#16193]
#### Expected behaviour
Highchart column range border should always appears

![graph_outline_exists](https://user-images.githubusercontent.com/7569931/129315058-c72dd11d-3abc-4997-8c75-659b60c1afd5.png)

#### Actual behaviour
Highchart column range border disappearing sometimes

![graph_outline_not_exits](https://user-images.githubusercontent.com/7569931/129315051-ad230117-f568-420f-9217-3b9e0af17ad5.png)

**Comment by raf18seb** [comment]
Hi @zuberspathan! Like in your previous ticket - could you reproduce the issue in a live demo? Thanks!

**Comment by zuberspathan** [comment]
@raf18seb its happening once in multiple times. I will definately try to repro it.

**Comment by zuberspathan** [comment]
> Hi @zuberspathan! Like in your previous ticket - could you reproduce the issue in a live demo? Thanks!

@raf18seb  is happening when I have integrated my angular app into another site portal as module. Its affecting on only on this part all other things are working fine

**Comment by raf18seb** [comment]
@zuberspathan, I am sorry, but without an online demo showing the problem we are not able to investigate this.

**Comment by pawellysy** [comment]
Closing - No reproduction steps provided
