### ISSUE TITLE
Plot a yAxis plotlines on cloumn cell only.

### ISSUE THREAD

**Issue by harshad-kumbhar** [highcharts/highcharts#16194]
#### Expected behaviour
Can I plot a yAxis plotlines on column cell only?
Refer a below screenshot => {
![image](https://user-images.githubusercontent.com/59466420/129315421-7103ed56-ccc2-442c-8718-a0d75d9995dd.png)

**Comment by raf18seb** [comment]
Hi @harshad-kumbhar!
Yes, you can render this kind of line in many ways. Similar questions are already answered on our official Forum and StackOverflow - please, do some searching.
In case of any problems or questions, please contact us on our dedicated support channels: https://www.highcharts.com/blog/support/

GitHub is our **bugs and features** tracker only, so I'm closing this question ticket here. Thanks for understanding.
