### ISSUE TITLE
TypeError: Cannot create property 'userOptions' on boolean 'false', Was working in 9.1.0 and break in 9.1.2

### ISSUE THREAD

**Issue by iuyt9003** [highcharts/highcharts#16201]
#### Expected behaviour
We have a chart that didn't change, same code, same flow. but when we upgraded to 9.1.2 the chart stopped rendering.

#### Actual behaviour
That the chart will be displaying and working.

#### Live demo with steps to reproduce
It's hard to reproduce because we override with many of our logic but ill post the chart configuration and using highcharts-angular and stuff. 

`{
  "chart": {
    "zoomType": "x",
    "type": "timeline"
  },
  "credits": false,
  "title": false,
  "plotOptions": {
    "series": {
      "cursor": "pointer",
      "dataLabels": {
        "allowOverlap": false,
        "useHTML": true,
        "enabled": true,
        "padding": 10,
        "width": 300
      },
      "marker": {
        "enabled": true,
        "symbol": "circle"
      },
      "states": {
        "hover": {
          "enabled": false
        }
      }
    }
  },
  "colors": [
    "#1089F3"
  ],
  "xAxis": {
    "type": "datetime",
    "visible": false
  },
  "yAxis": {
    "gridLineWidth": 1,
    "title": null,
    "labels": {
      "enabled": false
    }
  },
  "legend": {
    "enabled": false
  },
  "tooltip": false,
  "series": [
    {
      "data": [
        {
          "x": 1420934400000,
          "label": [
            {
              "title": "Dec 11, 2014",
              "subtitle": "test again"
            },
            {
              "title": "$31,000",
              "subtitle": "Test"
            }
          ]
        },
        {
          "x": 1580515200000,
          "label": [
            {
              "title": "Jan 1, 2020",
              "subtitle": "end of date"
            }
          ]
        },
        {
          "x": 1629072000000,
          "text": "Today",
          "label": null,
          "dataLabels": {
            "className": "hide-label-styles"
          }
        },
        {
          "x": 1738368000000,
          "label": [
            {
              "title": "Jan 1, 2025",
              "subtitle": "test"
            }
          ]
        }
      ]
    }
  ]
}`

We getting error :

![image](https://user-images.githubusercontent.com/23431551/129543246-72ce84a2-eef7-414f-b688-d84ebe907116.png)

#### Product version
9.1.2

#### Affected browser(s)
Was in Chrome

**Comment by iuyt9003** [comment]
HIghCharts angular -> to highchart

![image](https://user-images.githubusercontent.com/23431551/129544306-06cd01bc-abb8-4234-af1a-e4a00e2c6cc2.png)

**Comment by OldBuddy** [comment]
@iuyt9003, this shouldn't work on other versions as well.
In your example there is a `"tooltip": false`, but `"tooltip"` must be an object.

**Comment by iuyt9003** [comment]
Oh, so I am confused how it’s worked on 9.1.0. Didn’t saw any change on this implementation but I’ll change it to object accordingly

**Comment by raf18seb** [comment]
Hi @iuyt9003, @OldBuddy

As @OldBuddy said, the `tooltip` property must be an object. To disable the tooltip, set `tooltip.enabled: false`.

It didn't throw an error in the `v9.1.0` because of the bug - the Highcharts' minified code didn't use `use 'strict'`:

![image](https://user-images.githubusercontent.com/23310742/129589648-1d5b13f8-5ccf-40a9-a152-cf2ee38bb677.png)
-----
vs
-----
![image](https://user-images.githubusercontent.com/23310742/129589791-0a60665a-5774-49af-ab3a-1d838aa9e1ae.png)

Solution: use `tooltip.enabled: false` instead of `tooltip: false`.

**Comment by iuyt9003** [comment]
Thanks guys!
