### ISSUE TITLE
Datalabel dynamic y position 

### ISSUE THREAD

**Issue by criestlav** [highcharts/highcharts#16219]
Hi! Is there any way to be able to update the datalabel y position (in series) depending on it's value without using events callbacks? It would be really hepful if We could update that through the formatter function or something liket that.

**Comment by raf18seb** [comment]
Hi @criestlav!

GitHub is our bugs/features tracker only. With support questions, please contact us on dedicated support channels.
More info: https://www.highcharts.com/blog/support/

I am closing the ticket here now. Thanks for understanding!
