### ISSUE TITLE
yAxis panning broken for stacked column chart

### ISSUE THREAD

**Issue by willgearty** [highcharts/highcharts#16217]
#### Expected behaviour
After zooming in to the chart, you should be able to pan to the maximum y value (11 for the example below).

#### Actual behaviour
After zooming in to the chart, you can only pan to the maximum single y axis value (7 for the example below). If your zoom selection includes a y value greater than this value, you can pan down, then you can not pan up. My guess is that the limit for the axis while panning is being calculated based on the individual series values, not the summed stacked value.

#### Live demo with steps to reproduce
https://jsfiddle.net/willgearty/1ed47m6h/

#### Product version
Highcharts v.9.1.2

**Comment by raf18seb** [comment]
Hi @willgearty, thanks for reporting the issue!

The problem lays in the `Highcharts.Chart.prototype.pan` method, where the `paddedMax` value is calculated incorrectly (isn't taking the `extremes.dataMax` into consideration).

Workaround: https://jsfiddle.net/BlackLabel/0d2r791m/

**Comment by willgearty** [comment]
Perfect, thank you for the workaround @raf18seb!
