### ISSUE TITLE
Number of data values in column series effects column placement (pointPlacement & pointPadding set)

### ISSUE THREAD

**Issue by Kanatorabo** [highcharts/highcharts#16228]
#### Expected behaviour
column should be placed side by side independent of how many data points are set

#### Actual behaviour
columns are on top of each other on fewer data points

#### Live demo with steps to reproduce
Demo with first series has 3 data points (works like a charm)
http://jsfiddle.net/Kanatorabo/uobLm1d0/7/

Demo with first series has 2 data points (totally weird)
http://jsfiddle.net/Kanatorabo/t0s6fpLa/6/

Demo with first series has 1 data point (columns are stacking)
http://jsfiddle.net/Kanatorabo/sfb46m73/7/

#### Product version
 Highcharts JS v9.2.0 (2021-08-18)

#### Affected browser(s)
Chrome Version 92.0.4515.107 (Offizieller Build) (64-Bit)

**Comment by KacperMadej** [comment]
Hi @Kanatorabo 

[`pointRange`](https://api.highcharts.com/highcharts/series.column.pointRange) is calculated based on the minimal distance between points within a series' data. A small data set or irregular data `pointRange` should be set to avoid any issues. Modified demos:
http://jsfiddle.net/BlackLabel/ej8gvw95/
http://jsfiddle.net/BlackLabel/kd2h1wcm/

This doesn't look like a bug. Please let me know if we could close the issue.

**Comment by Kanatorabo** [comment]
Thanks a lot. This works for me.
