### ISSUE TITLE
Regression with SVG Migration / not all svg attributes 

### ISSUE THREAD

**Issue by Darex1991** [highcharts/highcharts#16229]
#### Expected behaviour
Able to display all attributes on svg.

#### Actual behaviour
No all attributes in svg

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/Darex1991/qb3m26cp/) - please inspect red icon on yAxis - there are no attributes like "viewBox" or "xmlns" in SVG and "fill-rule" or 'clip-rule' in path.

#### Product version
From version 9.0.0 rendering svg had problems. Probably regression of [PR](https://github.com/highcharts/highcharts/pull/15602)

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @Darex1991 

Thank you for reporting the problem.

This can be resolved by adding tags to AST - https://jsfiddle.net/BlackLabel/6uv7p0fx/1/
This works when correct attributes are used - e.g. `fill-rule` and not `fillRule`.
Docs: https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#filtering

This doesn't look like connected to the migration.
This doesn't look like a bug - please let me know if we could close the issue.

**Comment by Darex1991** [comment]
Nice 🎉  your example works great. Thank you very much 😄 
For other people: `Highcharts.AST.allowedAttributes.push('viewBox', 'xmlns', 'fill-rule', 'clip-rule');`
