### ISSUE TITLE
Setting zIndex of html dataLabels doesn't work as expected

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#16237]
Since I have complex formatting in my dataLabels, which I could only get to work nicely using html, I have them set to `useHTML: true`.  Unfortunately, this seems to have the consequence of messing up their zIndex positioning.

As further background, I also have overrides in my code so that (ideally) all plot features (lines, plotBands, labels) sit within the same zIndex regime, not as separate groups with each group on top of the other.  This concept (with workaround) is explained in [this issue](https://github.com/highcharts/highcharts/issues/3321).

So, the above issue does provide a neat solution to ensuring that all chart elements sit within the same zIndex regime (which I am using)...

That is, until I start using html for the dataLabels :-(

Here is a jsfiddle to show the problem: https://jsfiddle.net/gyoqp251/

The zIndexes are set at the top of the code.  What I want is for the labels to be just above the corresponding series line.  And, in this example, the blue line *and labels* should be *above* the green line and labels.

However, not only do the labels sit on top of everyting (even the plotBand with a lower zIndex), but the green labels are above the blue labels.

Is there any way of making this work as expected?  I have come across issues with html dataLabels before... I understand that, html is rendered over svg and it's not possible to interleave them.  

But is there *really* no hack to get around this?  For example, wrapping an html element (data label) inside an svg element, so that the svg wrapper (with label) can sit where you want it in within the svg space?

At the very least, the html labels should themselves honour the zIndex given to them, within their own grouping?  At the moment, green is on top of blue despite the zIndexes asking for the opposite.

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

zIndex option should be respected between HTML elements - marking the issue as a bug.

> But is there really no hack to get around this?

The scrollable plot area feature is based on creating 2 SVG within different containers, so it allows placing HTML elements between SVG elements (because there are 2 SVGs). 

> the blue line and labels should be above the green line and labels

Demo: https://jsfiddle.net/BlackLabel/hge0Lwur/
In the chart's callback, one of the class names that triggers the moving of an element is added. setTimeout must be used instead of a direct update because the scrollable plot area feature runs after the callback.

**Comment by drmrbrewer** [comment]
This looks promising @KacperMadej thanks!  Is there any way to extend your demo further so that the plotBand is properly positioned between the two series (both lines and labels)?  According to the zIndexes at the top of the code, I want the plotBand to be above the green line AND green labels... with your demo the plotBand is above the green line but *below* the green *labels*.  

If I have one bugbear with highcharts, which is otherwise amazing, it is that the zIndex regime is a very confusing and difficult to get right... I think that most people would expect the zIndex to apply globally, regardless of whether it's a line, label or band, and regardless of whether (under the hood) the feature is rendered via html or svg.

**Comment by KacperMadej** [comment]
> Is there any way to extend your demo further so that the plotBand is properly positioned between the two series (both lines and labels)?

Adding the same class as for other elements seems to be working correctly - https://jsfiddle.net/BlackLabel/hge0Lwur/1/

There are some related feature requests:
https://github.com/highcharts/highcharts/issues/15398
https://github.com/highcharts/highcharts/issues/8935
You can vote for these features by adding a thumbs-up reaction to the top posts.

**Comment by drmrbrewer** [comment]
Thanks.  I see that the workaround is quite specific to this use-case, by manipulating just the first (blue) series, and it doesn't work when I try e.g. to put the blue series (and labels) underneath everything by changing zIndexes at the top:

https://jsfiddle.net/9kv6awyb/

I'm guessing that it wouldn't be easy to generalise this approach to work with any number of series, with any zIndexes applied to each series and series labels?

**Comment by KacperMadej** [comment]
An alternative for the currently suggested workaround would be to use [foreignObject](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject) that is not supported by any IE, so this is not a good solution.

If HTML and SVG groups need to be placed in any order then it will require creating multiple layers - in my demo, there are only 4 layers (SVG, HTML, SVG, HTML) and you need another one for the plotBand to be placed on top of the HTML labels.

It might be easier to look for a different solution for your dataLabels format and check if it could work without `useHTML: true`.

**Comment by drmrbrewer** [comment]
Ah yes, `foreignObject` seems to be exactly the sort of thing I had in mind with my original suggestion to wrap an html element (i.e. the html data label) inside an svg element... that way everything is in the svg realm.  However, I wouldn't have any idea where to start with this, within the context of the highcharts SVG/HTML world, but maybe it's one for the future... in your view would this be suitable for anyone other than a highcharts guru?  And not being supported by IE is fine, because I'm using this almost entirely on a mobile browser (all supported) and within node.js (supported) and for testing purposes in Chrome (supported).

**Comment by drmrbrewer** [comment]
@KacperMadej this is almost too good to be true!  And the solution is surprisingly concise and simple!  You are a genius!  Finally, with the various workarounds in place, including your latest `foreignObject` workaround, I can have the advanced formatting flexibility of html data labels (svg formatting doesn't quite cut it), and also put the labels exactly where I want them in `z` order.  Thanks so much!  

So far the solution seems to work also in my actual code, though with just one extra check to avoid trying to work on series without any `series.dataLabelsGroup.div`:

	if ((series.dataLabelsGroup || {}).div && (series.options.dataLabels || {}).useHTML) {

It's a shame that this can't be the default, or at least available via a switch in view of the lack of support in IE.

(And I suppose that this issue remains open anyway, because the zIndex of 'pure' html labels, in their normal place without this `foreignObject` workaround, doesn't seem to be working?)

**Comment by KacperMadej** [comment]
Good to see that this works for you.
Thank you for the extra check - I will update the demo in my previous comment.

The bug here, as you wrote, is the lack of support for zIndex in HTML labels.

The more advanced manipulations for full control of zIndex is also an open case, but tracked as an enhancement request here:
https://github.com/highcharts/highcharts/issues/15398

**Comment by drmrbrewer** [comment]
@KacperMadej is there an equivalent trick to wrap plotBand labels in a similar way, to bring them also into the same zIndex regime?

Take this example (based on your demo, just adding a plotBand label): https://jsfiddle.net/g6yjnr9e/

I'd like to be able to control the zIndex of the plotBand label so that it doesn't sit on top of the Reset Zoom button (and other buttons I add)... I feel like it should be possible?

**Comment by KacperMadej** [comment]
Yes, this is possible in a similar way - [demo](https://jsfiddle.net/BlackLabel/t40d3esh/).

**Comment by drmrbrewer** [comment]
@KacperMadej thanks... just perfect!
