### ISSUE TITLE
export & styled mode

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#16231]
#### Expected behaviour

The last properly working version is 9.1.2: https://jsfiddle.net/BlackLabel/6qhgfLk4/

#### Actual behaviour

It seems that the styled config is not applied in the exported chart.

#### Live demo with steps to reproduce

Demo: https://www.highcharts.com/demo/styled-mode-column

**Comment by khlieng** [comment]
Bisected to cd390f5.
