### ISSUE TITLE
Regression in scrollbar and dynamic data

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#16248]
#### Expected behaviour
The scrollbar should retain its width when sticking to the left, like it did in v9.1.0.

#### Actual behaviour
It preserves the max data when min data is removed.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/dynamic-update/
1. Move the scrollbar all the way to the left
2. Observe how the scrollbar shrinks. When it reaches 0 width, it jumps up again where it started.

#### Product version
v >= 9.1.1. Fails since 06cc31f3b159800123fd1db9335d35398653248b

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
Fixed by https://github.com/highcharts/highcharts/pull/16515
