### ISSUE TITLE
Additions.prototype.getIndexOfPoint throws error in case of ordinal xAxis and invisible Series 

### ISSUE THREAD

**Issue by robocop98** [highcharts/highcharts#16255]
#### Expected behaviour
No error to be thrown

#### Actual behaviour
Error is thrown:
```
highstock.src.js:48606 Uncaught TypeError: Cannot read property '0' of null
    at highstock.src.js:48606
    at Array.forEach (<anonymous>)
    at a.getIndexOfPoint (highstock.src.js:48605)
    at c.y [as lin2val] (highstock.src.js:47924)
    at c.translate (highstock.src.js:19192)
    at c.toValue (highstock.src.js:19247)
    at c.<anonymous> (highstock.src.js:58808)
    at highstock.src.js:1661
    at Array.forEach (<anonymous>)
    at x (highstock.src.js:1658)
```

#### Live demo with steps to reproduce
I desperately tried to set up a fiddle to reproduced the issue, but did not succeed.
Anyhow the fix ("catch undefined points array") is an easy stability win, should not have side effects and can maybe implemented without a working fiddle. Would be great :)

The core reason (as far as I could track down) is that one or more invisible series have data (processed data, etc), but no points array ("undefined"). Then the above error is triggered from afterDrawCrosshair event.

**Error:** "Additions.prototype.getIndexOfPoint" crashes at this check: "if (defined(series.points[0])".
**Fix:** An additional pre-check for "defined(series.points)" solves the issue.

The parameters that seem to be relevant are:
- xAxis is ordinal = true: else "getIndexOfPoint" is not called
- a visible series using yAxis[0]
- an invisible series using yAxis[1]
- both series use the same xAxis

#### Product version
Issue occurs in Highstocks 9.2.0, 9.2.1, 9.2.2
No problems in versions 9.1.2 and earlier.

#### Affected browser(s)
Tested in Chrome and Firefox

**Comment by Belomor123** [comment]
Getting the same error when loading/updating the chart.
I have a single highcharts element having stock data and extra graphs on top of it. All charts are being drawn on the same xAxis and differing yAxis.

This is the error I get upon render:

TypeError: Cannot read properties of null (reading '0')
(anonymous function)
C:/.../highstock.src.js:48606
a.getIndexOfPoint
C:/.../highstock.src.js:48604
c.y [as lin2val]
C:/.../highstock.src.js:47924
c.translate
C:/.../highstock.src.js:19186
c.toValue
C:/.../highstock.src.js:19247
a.render
C:/.../highstock.src.js:54622
c.<anonymous>
C:/.../highstock.src.js:55622
(anonymous function)
C:/.../highstock.src.js:1661
x
C:/.../highstock.src.js:1658
c.a.redraw
C:/.../highstock.src.js:30596
c.a.update
C:/.../highstock.src.js:32560
(anonymous function)
C:/src/HighchartsReact.js:55
  52 |   createChart();
  53 | } else {
  54 |   if (props.allowChartUpdate !== false) {
> 55 |     if (!props.immutable && chartRef.current) {
     | ^  56 |       chartRef.current.update(
  57 |         props.options,
  58 |         ...(props.updateArgs || [true, true])
View compiled
▶ 19 stack frames were collapsed.
loadFunc
C:/.../src/layouts/Instrument.js:136
  133 |     data.title = headerArr[1]
  134 |     data.stockIsFavorite = stockFavorite
  135 |     data.xAxis = 0
> 136 |     setInstrument(data)
      | ^  137 |     setLBCValue(data.LBCBars)
  138 | } else {
  139 |     // console.log(data)
View compiled

**Comment by raf18seb** [comment]
@Belomor123, the issue has been fixed and will be released within a new Highcharts version. Until then, you can use this workaround:
```js
(function() {
    var defined = Highcharts.defined,
      Additions = Highcharts._modules['Core/Axis/OrdinalAxis.js'].Additions;

    Additions.prototype.getIndexOfPoint = function(val, ordinalArray) {
      var ordinal = this,
        axis = ordinal.axis,
        firstPointVal = ordinal.positions ? ordinal.positions[0] : 0;
      var firstPointX = axis.series[0].points &&
        axis.series[0].points[0] &&
        axis.series[0].points[0].plotX ||
        axis.minPixelPadding; // #15987

      // When more series assign to axis, find the smallest one, #15987.
      if (axis.series.length > 1) {
        axis.series.forEach(function(series) {
          if (
            series.points &&
            defined(series.points[0]) &&
            defined(series.points[0].plotX) &&
            series.points[0].plotX < firstPointX
          ) {
            firstPointX = series.points[0].plotX;
          }
        });
      }

      // Distance in pixels between two points
      // on the ordinal axis in the current zoom.
      var ordinalPointPixelInterval = axis.translationSlope *
        (ordinal.slope || axis.closestPointRange || ordinal.overscrollPointsRange),
        // toValue for the first point.
        shiftIndex = (val - firstPointX) / ordinalPointPixelInterval;

      return Additions.findIndexOf(ordinalArray, firstPointVal) + shiftIndex;
    };
  })()
```

Demo: https://jsfiddle.net/BlackLabel/uqf89tjd/

**Comment by Belomor123** [comment]
Fantastic!

Thanks for the prompt response!
