### ISSUE TITLE
Fonts and Style not retained in PNG, JPEG, PDF Document etc exports

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/highcharts#16250]
#### Expected behaviour
The export outputs of the chart should retain the fonts and styles applied in the chart.

#### Actual behaviour
The export outputs of the chart is not retaining the fonts and styles applied in the chart.
it always takes a default style in the export outputs ignoring the font and style for the chart what we see in the browser.

Open Sans is applied in the Chart fonts, but in the export output its ignoring the font family and styles

**In browser this is how it looks**
![image](https://user-images.githubusercontent.com/53110553/130625936-d1a59606-ea34-4023-81f4-d303d526d42b.png)

**whereas in export output it looks different from what Im seeing in the browser, please help us resolve this issue.**

![image](https://user-images.githubusercontent.com/53110553/130626076-2594a807-1530-4277-bf42-634b6078ce9a.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/sreejithga/objrendg/1/

#### Product version
Latest

#### Affected browser(s)
Google Chrome

**Comment by raf18seb** [comment]
Hi @Sreejithga, thanks for creating the ticket.

It's not like the export output always uses the default styles.
When exporting the chart, you are sending the config to our export server. Some fonts are installed on the server and if the font in the config is found, then the output uses the font. But if the font defined in the config is not installed on the export server, then the chart uses the default font.

You can create a feature request ticket on our [export server](https://github.com/highcharts/node-export-server/issues) repo - the feature would be about installing the additional font on our export server, or...
You can install your own export server with whatever fonts (installed on your server) you like.

I am closing the ticket here. If you would like to continue, please create the ticket on the [export server](https://github.com/highcharts/node-export-server/issues) repo.
