### ISSUE TITLE
Is there a way to export underlying data of the Chart into a tabular format

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/highcharts#16251]
Dear Team,

We would like to know if there is an option in Highcharts which enables us to export the underlying data of the chart into a tabular format.

Kindly revert as this is an urgent requirement from one our clients.

Thanks

**Comment by raf18seb** [comment]
Hi @Sreejithga.

With any support-related questions, please contact us on dedicated support channels (GitHub is our bugs and features tracker only).
More info: https://www.highcharts.com/blog/support/
Thank you for understanding.
