### ISSUE TITLE
Legend item text jumps horizontally on chart resizing

### ISSUE THREAD

**Issue by twin720** [highcharts/highcharts#16261]
#### Expected behaviour
If legend.useHTML= true legend item text is center by horizontally on chart resizing

#### Actual behaviour
If legend.useHTML= true legend item text jumps horizontally on chart resizing

steps:
1. Open example https://jsfiddle.net/Lvo9xs07/2/
2. Make sure that legend item text is in center of chart by horizontal
3. Resize chart to minimum width (use resizer, drag right bottom corner on chart) and then resize to initial width
3. Make sure that legend item move to left side

#### Live demo with steps to reproduce
https://jsfiddle.net/Lvo9xs07/2/
video: https://nimb.ws/qh47zb

#### Product version
Highcharts v9.2.2

#### Affected browser(s)
Google Chrome 92.0.4515.159 (x86_64)
Firefox 91.0.1 (x64)

https://user-images.githubusercontent.com/18051646/130970829-c0446585-2c5b-4bff-9e19-d6087edef2bf.mp4

**Comment by khlieng** [comment]
I think this is a regression since 6bf7ff5, related to the handling of css `width` on the text.

#12154 is likely also caused by the same thing.

@TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Simplified demo: https://jsfiddle.net/highcharts/941tam2g/

Bisecting actually leads me to f1d4da654a5c1a54ee0f28d38366f1327bdd0da2
