### ISSUE TITLE
Reset Zoom on X Axis for HighStock Chart Creates Infinity Loop of AfterSetExtreme Event.

### ISSUE THREAD

**Issue by thesaadmirza** [highcharts/highcharts#16278]
#### Expected behavior
I have added a Multiple Series Chart, with dynamic Data on AfterSetExtreme Event, which should work the same as any other event, Reset Zoom is zooming out.

#### Actual behaviour
But the problem is When we Reset the Zoom, it triggers an infinite Loop of AfterSetExtreme Event, It is only Happening when we reset Zoom.

#### Here is My Config

`
Highcharts.removeEvent(Highcharts.Chart, 'beforeShowResetZoom');
var chart = Highcharts.stockChart('container', {

    chart: {
        zoomType: 'x',
        height: '500px',

    },
    tooltip: {
        valueDecimals: 2
    },

    rangeSelector: {
        buttons: [
            {
                type: 'minute',
                count: 15,
                text: '15min'
            },
            {
                type: 'hour',
                count: 1,
                text: '1h'
            },
            {
                type: 'day',
                count: 1,
                text: '1d'
            },
            {
                type: 'day',
                count: 7,
                text: 'week'
            },
            {
                type: 'month',
                count: 1,
                text: '1m'
            },
            {
                type: 'month',
                count: 3,
                text: '3m'
            },
            {
                type: 'year',
                count: 1,
                text: '1y'
            },
            {
                type: 'all',
                text: 'All'
            }],

        selected: 4, // all
        verticalAlign: 'top'
    },

    navigator: {
        adaptToUpdatedData: false,
        series: series,
        margin: 60
    },
    exporting: {
         menuItemDefinitions: {
            // Custom definition
            rtOptions: {
                onclick: function () {
                    $('#exampleModal').modal('toggle');
                },
                text: 'RT OPTIONS'
            }
        },
        buttons: {
            contextButton: {
                menuItems: ['viewFullscreen', 'printChart','separator', 'downloadPDF','downloadPNG', 'downloadSVG', 'separator', 'rtOptions']
            },
            customButton: {
                x: -250,
                onclick: function () {
                     autorefresh(false, true);
                },
                text: 'Refresh'
            },

        }

    },

    scrollbar: {
        liveRedraw: false
    },

    xAxis: {
        type: 'datetime',

        events: {
            afterSetExtremes(event) {
                console.log("trying to Fetch Data ..")
                fetchData(Highcharts.dateFormat(
                    '%Y-%m-%d %H:%M:%S',
                    event.min
                    ),
                    Highcharts.dateFormat(
                        '%Y-%m-%d %H:%M:%S',
                        event.max
                    ));
            }
        },
        minRange: 60 * 1000 // one minute
    },

    series: series,

});`

#### Product version
 Highstock JS v9.2.2 (2021-08-24)

#### Affected browser(s)
All of them.

**Comment by raf18seb** [comment]
Hi @thesaadmirza,

It looks like you are not reporting a Highcharts bug, but you have a general problem with your chart/app. Please, contact our technical support on one of our dedicated support channels. GitHub is our bugs/features tracker only.

Also, when contacting our support team, please remember to recreate your problem in an online code editor (jsFiddle would be perfect). You haven't provided your data (`series` variable).

**Comment by thesaadmirza** [comment]
here is my Series.

  `let data_set = {
          label: 'name',
          name: 'name',
          color: colors[key],
          data: [],
          visible: true,
     
  
      };
    series.push(data_set);`

**Comment by raf18seb** [comment]
@thesaadmirza your data is empty.

As I said, GitHub is a bugs/features tracker only. Please contact our support team on dedicated support channels.
See https://www.highcharts.com/blog/support/

**Comment by thesaadmirza** [comment]
I sent the demo data.
The series is set by dynamic Data once it is loaded or navigation changed.
by doing chart.series[i].setData();

 I will add it in the blog too, thanks.
