### ISSUE TITLE
Tooltip shared not shown when different series types are on separate yAxis

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#16279]
Create a chart with 2 yAxes and column series assigned to both axes. Then add another series of a different type. Set the `tooltip.shared: true`.

#### Live demo with steps to reproduce
Hover the mouse over the green left-bottom column - the tooltip is not showing. Hovering over the other points is working fine.
https://jsfiddle.net/BlackLabel/po0qtj9s/

![tooltip-shared-bug](https://user-images.githubusercontent.com/23310742/131507137-f5af7abd-73d0-4a34-a802-2e8ae9f20633.gif)

#### Product version
Highcharts 9.2.2
Worked fine in 9.0.1, broken since 9.1.0
Bisected to https://github.com/highcharts/highcharts/commit/9b58c8a9efd579da4f0bc17d1ed6f7dbd5bdd14a

FYI @khlieng

**Comment by khlieng** [comment]
#16004 #16005
