### ISSUE TITLE
Drilldown for Organization with Multiple Children

### ISSUE THREAD

**Issue by jedix** [highcharts/highcharts#16288]
#### Expected behaviour

Once a drilldown on an organization chart is activated, the drilldown data should be displayed correctly.

#### Actual behaviour

Instead of straight lines between nodes, there are colored triangles.

#### Live demo with steps to reproduce
https://jsfiddle.net/o3p65dmz/
Click on Division 01 (compared to any other devision with only one child)

The example was taken from https://github.com/highcharts/highcharts/issues/13711#issuecomment-645877408 and only a second node below Devision 01 was added.

#### Product version
Highcharts 9.2.2

#### Affected browser(s)
Firefox 90.0.2
Google Chrome 92.0.4515.131

**Comment by raf18seb** [comment]
Hi @jedix, thanks for reporting the bug.

Simplified demo: https://jsfiddle.net/BlackLabel/L8khoswd/

**Comment by jedix** [comment]
I'm not that deep into the highcharts code, but in the resulting output I would assume "fill=none" on the paths instead of "fill=rgb(...)" (with the color from the parent node) should solve the problem. 

Thanks for the simplified demo, should have thought of that myself. On the other hand, I wanted to use an "official" example and modify as little as possible to show the behaviour :)

**Comment by KacperMadej** [comment]
Workaround: force fill=none via CSS
Demo: https://jsfiddle.net/BlackLabel/ay1czgxp/
