### ISSUE TITLE
Default height changes when adding accessibility module and using styled mode

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#16282]
Default height changes when adding accessibility module and using styled mode and it doesn't match chartHeight anymore.
The height difference seems to come from the hidden `ul` element used for toggling series visibility which has default margin of 12px. The `ul` element used by the exporting menu has 0px margin and doesn't affect the chart size.

#### Expected behaviour
container.getBoundingClientRect().height matches chart.chartHeight independently of accessibility being imported or not

#### Actual behaviour
When not setting a specific size the container height defaults to 412px while chartHeight defaults to 400px

#### Live demo with steps to reproduce
With accessibility: https://jsfiddle.net/alvarezg/pure8b3j/
Without accessibility: https://jsfiddle.net/alvarezg/63f0xer5/

#### Product version
9.2.2

#### Affected browser(s)
Chrome at least

**Comment by alvarezguille** [comment]
I noticed that this happens after load, when creating the minimal example I first used load event and the height matched, but it didn't after render.
I'm not sure, but I think that the margin could be set here:
https://github.com/highcharts/highcharts/blob/master/ts/Accessibility/ProxyProvider.ts#L137-L140

Another thing that I noticed now is that the chart height keeps growing constantly when resizing the window in the [example with accessibility](https://jsfiddle.net/alvarezg/pure8b3j/)
![chart resize height](https://user-images.githubusercontent.com/9820084/131847617-6b77d49f-e962-487a-a553-59cfcc28389f.gif)
It looks like a regression of #7494

**Comment by raf18seb** [comment]
I think this is the same issue, so no need to create a separate ticket. When during the fixing process someone finds out that this is a separate bug, then we will create a separate ticket. Once again, thanks!

**Comment by oysteinmoseng** [comment]
I can not seem to reproduce this in latest, so assuming it was fixed by the rewrite of the proxy logic. Feel free to comment if you can reproduce still and we will reopen.
