### ISSUE TITLE
scatter chart export (highchart-export-server , svg export) does not work on ubuntu

### ISSUE THREAD

**Issue by davinder-ficode** [highcharts/highcharts#16295]
I am using "highchart-export-server" as a module in my node service, and using below function in my service to export chart to svg. i.e
'chartExporter.export(exportOptions, (err, chartRes)=>{}'

exportOptions are [link](https://ficodeo365-my.sharepoint.com/personal/davinder_ficode_in/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fdavinder%5Fficode%5Fin%2FDocuments%2FtestExport%2Ejson&parent=%2Fpersonal%2Fdavinder%5Fficode%5Fin%2FDocuments&originalPath=aHR0cHM6Ly9maWNvZGVvMzY1LW15LnNoYXJlcG9pbnQuY29tLzp1Oi9nL3BlcnNvbmFsL2RhdmluZGVyX2ZpY29kZV9pbi9FV3hKZFNYdHMwdE9taTRTTFVwLWVEc0JnY2doa2tnLS1VRVYyWnRmUkEzWW1BP3J0aW1lPVlDRkFjWmR1MlVn)

it works pretty well on MAC (Local). But when i deployed same on ubuntu(18.04) it gives corrupted svg i.e
[screen_shot_svg](https://paste.pics/535e139600635744213e154d3be12794)

Node:- 12.0.0
highchart-export-server: 2.1.0

Thanks

**Comment by davinder-ficode** [comment]
This is error if export to png in ubuntu
[screen_shot](https://paste.pics/5308b43f62ab1dc753531b9c77e80273)

On Local(Mac) it exports fine

**Comment by raf18seb** [comment]
Hi @davinder-ficode!

Could you report your issue in the right repo here?: https://github.com/highcharts/node-export-server/issues
Thanks!
