### ISSUE TITLE
Issue with axis labels alignment

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#16300]
#### Expected behaviour
Coming from a discussion ([Reference](https://www.highcharts.com/forum/viewtopic.php?f=9&t=47277&p=170143#p170143)) on highcharts forum, it seems the documentation as well as the code for `yAxis.labels.align` is a little buggy.

From the documentation of Highcharts API ([Reference](https://api.highcharts.com/highcharts/yAxis.labels.align)) the default value of labels.align is right. and for Highstock API ([Reference](https://api.highcharts.com/highstock/yAxis.labels.align)) the default value is left.

#### Actual behaviour
1. When yAxis.opposite is false:
Highcharts - https://jsfiddle.net/bz0taf1v/ - Aligned to right
Highstock - https://jsfiddle.net/bz0taf1v/1/ - Aligned to right
2. When yAxis.opposite is true:
Highcharts - https://jsfiddle.net/bz0taf1v/2/ - Aligned to left
Highstock - https://jsfiddle.net/bz0taf1v/3/ - Aligned to right

#### Live demo with steps to reproduce
Added above

#### Product version
Highstock JS v9.2.2

#### Affected browser(s)
Chrome

Adding response from mateusz:
```
Hi govinda,

Thanks for contacting us with your question.

You're right, there is definitely a bug in the documentation, but not only there.

For Highcharts, the default label placement for Y axis is right, and when opposite: true, it is left. I think that the documentation should be should be supplemented by that information.

When it comes to Highstock, according to documentation the align defaults to left, but that information is incorrect. Regardless of the opposite option, the default align is right. That's not the only problem. As you may have already noticed, when opposite: true, each of the available options (left, center, right) differs from default behaviour, and this is bug in our code.

Thanks a lot for pointing out that issue, and you should definitely report it on github.
Best regards!
```

**Comment by raf18seb** [comment]
Hi @govinda18, thanks for creating the ticket and such a detailed explanation!
Indeed, the docs should be corrected.

**Comment by raf18seb** [comment]
Also, there's a problem with left spacing (the labels are cut) when `yAxis.opposite: false` and `align: 'left'` (and some other cases too): https://jsfiddle.net/BlackLabel/wrqst75o/

**Comment by govinda18** [comment]
Thanks for addressing @raf18seb. Yes, at times when `yAxis.opposite` is true and `align: 'left'`, I also noticed that the first xAxis label was being cut. I will reproducing some of these later this week in a fiddle and update here. 

Also, while the documentation is incorrect, I feel the behaviour should be consistent in both highcharts and highstock i.e. with the `opposite: false`, labels should be right aligned and left aligned otherwise.
