### ISSUE TITLE
Annotation with measure type "y" does not work when the data has weekends 

### ISSUE THREAD

**Issue by felipejacobsexternal** [highcharts/highcharts#16316]
#### Expected behaviour
I'm expected the below behaviour as shown in the documentation
https://jsfiddle.net/Lindus93/jxm17dnz/

#### Actual behaviour
in this configuration i only had one week and one monday for the next week and it not works but if i remove the last field the yAxis measure works.

https://jsfiddle.net/e257nqzx/

https://www.highcharts.com/demo/stock/stock-tools-custom-gui

PD: i try to put the xAxis breaks for this weekend and the line for the measure works but the measure data is not showing

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/stock/stock-tools-custom-gui

#### Product version
Highcharts/ Highstock 9.1.2

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi @felipejacobsexternal, thank you for reporting the bug.

Simplified demo: https://jsfiddle.net/BlackLabel/o1jyu7dt/
Probably regression after https://github.com/highcharts/highcharts/issues/16132

FYI @karolkolodziej
