### ISSUE TITLE
Module functions not allowed in typescript

### ISSUE THREAD

**Issue by temka1234** [highcharts/highcharts#16314]
#### Expected behaviour

`highcharts/ts/Extensions/NoDataToDisplay.ts`
![api](https://user-images.githubusercontent.com/3648995/132708631-baab10f1-e7b1-45b4-8a8b-8d26766df1b1.PNG)

#### Actual behaviour
![problem](https://user-images.githubusercontent.com/3648995/132709943-133beec6-009a-4cdd-8dc9-480048da5ce5.PNG)

#### Live demo with steps to reproduce
https://codesandbox.io/s/ts-module-methods-not-availible-197rs

#### Product version
Highcharts 9.1.2
TS 4.3.5

**Comment by KacperMadej** [comment]
Hi @temka1234 

TS definitions are not the same as the public API.
Here are more details and an example: https://github.com/highcharts/highcharts/issues/16236#issuecomment-915289645

showNoData is an internal function of Highcharts code and it is not a part of the public API:
https://api.highcharts.com/class-reference/Highcharts.Chart

If there is a need for a prop to be a part of public API please let us know the reason why it should be added. The public API is intended for general usage and not for extending Highcharts functionality, so not all properties are a part of the public API.

**Comment by temka1234** [comment]
Here is my problem:
https://jsfiddle.net/temka1234/p1ax2qsd/5/

I use highcharts react and have few async series that loading from different sources.  
In my case i want to wait until all of them are loaded.  

Example in pseudo code
```
const loading1 = useRequestHook((data) => {
  chart.series[0].setData(...);
});

const loading2 = useRequestHook((data) => {
  chart.series[0].setData(...);
});

const loading3 = useRequestHook((data) => {
  chart.series[0].setData(...);
});

const loading = loading1 || loading2 || loading3;

if (loading) {
  chart.showLoading();
} else {
  chart.hideLoading();
}
```

**Comment by temka1234** [comment]
I think this is a module bug and there is no need to move NoData API to public.

**Comment by KacperMadej** [comment]
It is possible to update the chart to change the noData text to an empty string. To refresh the noData label it should be turned off and back on - e.g. by series update forcing it to hide and show. Demo: https://jsfiddle.net/BlackLabel/vz6a1ph4/

You could also place any of the overlapping labels in different spots to prevent the overlap.
Demo: https://jsfiddle.net/BlackLabel/vz6a1ph4/1/

It seems to me that this kind of case belongs to one of our support channels - until it is clear what is a bug and what could be solved through tech support. See: https://www.highcharts.com/blog/support/
I will label this issue as a question and close it, but let's not jump from a channel to channel in the middle of the problem - let's continue here. In the end, if there is a bug you/we/I could open a new issue with a short and precise description.

**Comment by temka1234** [comment]
Problem solved, thanks!

**Comment by jlecordier** [comment]
Hi, I would like to access `hasData`, `showNoData` and `hideNoData`, because when async loading is done, when I use `hideLoading`, if there is no data, the "no data message" is not displayed, so I need to manually use `showNoData`

**Comment by jlecordier** [comment]
Changing the noData label to an empty string seems more like a hack to me than a proper use of the module.

And I don't want to have both noData message and loading message at the same time not to confuse users

**Comment by jlecordier** [comment]
I could solve my problem by first using `chart.showLoading`, then using `series.setData([])`

**Comment by ivankokan** [comment]
> Hi [@temka1234](https://github.com/temka1234)
> 
> TS definitions are not the same as the public API. Here are more details and an example: [#16236 (comment)](https://github.com/highcharts/highcharts/issues/16236#issuecomment-915289645)
> 
> showNoData is an internal function of Highcharts code and it is not a part of the public API: https://api.highcharts.com/class-reference/Highcharts.Chart
> 
> If there is a need for a prop to be a part of public API please let us know the reason why it should be added. The public API is intended for general usage and not for extending Highcharts functionality, so not all properties are a part of the public API.

Hi @KacperMadej. My understanding was that importing modules would enrich the type definitions, e.g. that `showNoData` method would be there for `Chart` interface. Are you saying that it is not the case for the particular `showNoData` method, or not in general (interfaces would not change at all with any imported module)?

Of course, when it comes to the `showNoData` method, one can always do this
```typescript
(chart as any).showNoData("No data");
```

**Comment by KacperMadej** [comment]
Hi @ivankokan 

The latter is true. Interfaces would not change as the .d.ts is build for all products and modules.
Casting to `any` is valid workaround with a note that if you are using code outside of the public API and docs then it might change in any of the next releases without prior notice and will not be considered a breaking-change. For example, the name of any internal function could change.

If you are working on a fixed code version accessing internal code will be stable and you could extend type definitions with additional typing (could be based on the internal types visible in this GitHub repository) to avoid casting to `any`. [Extending Highcharts Typing documentation](https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-declarations#extending-highcharts-typing) covers how to do it.
