### ISSUE TITLE
Stock-Tools: Annotation "crooked5" has generic langKey "crookedLine"

### ISSUE THREAD

**Issue by robocop98** [highcharts/highcharts#16318]
#### Expected behaviour
I'd expect stock-tools.js to set up the crooked5 Annotation with `langKey: "crooked5"`, like e.g. crooked3 does.
This way it would be more specific for translation of the Annotation names.

Not sure if it is a bug (like copy&paste issue) or intended as is. If intended, please feel free to decline my request. It is for sure no big deal to use it as is.

#### Actual behaviour
stock-tools.js defines the generic `langKey: "crookedLine"` for "crooked5"

#### Live demo with steps to reproduce
n/a

#### Product version
Highstocks 9.2.2

#### Affected browser(s)
n/a

**Comment by raf18seb** [comment]
Hi @robocop98, thanks for reporting the issue. Sure, it should be corrected!
