### ISSUE TITLE
Button All rangeSelector from default array of configuration objects, don't work properly.

### ISSUE THREAD

**Issue by hihajdus** [highcharts/highcharts#16319]
#### Expected behaviour
The rangeSelector button All should show all range after click all second time.

#### Actual behaviour
Button All rangeSelector from default array of configuration objects, don't work properly for view all range.
Didn't show all range after double click.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/8wfzot5g/](https://jsfiddle.net/BlackLabel/8wfzot5g/)

![stock](https://user-images.githubusercontent.com/22296099/132862086-c5b156cb-dde5-47a4-84cc-f3d47d4029ae.gif)

#### Product version

Highstock JS v9.2.2 (2021-08-24)
The problem doesn't occur with versions up to 9.1 and earlier.
#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Internal note:
Doesn't show on a large chart. Fixed width always shows the problem: https://jsfiddle.net/BlackLabel/8wfzot5g/1/

**Comment by karolkolodziej** [comment]
_Internal note:_
Disabling `dataGrouping` solves the flicking. I guess the debug should start from this.
Demo: https://jsfiddle.net/BlackLabel/2uL7qeoh/

**Comment by karolkolodziej** [comment]
_Internal note:_
Direct cause: https://github.com/highcharts/highcharts/pull/16241
