### ISSUE TITLE
Setting the height of an org chart's nodes greater than 50 causes the nodes to be misaligned

### ISSUE THREAD

**Issue by MrLeebo** [highcharts/highcharts#16324]
If you set the `height` larger than 50 on your series, the layout of the org chart becomes misaligned.

```js
{
  chart: {
    inverted: true
  },
  series: [{
    type: 'organization',
    cursor: "pointer",
    height: 100,
    data: [
      { from: 1, to: 2 }, 
      { from: 1, to: 3 }
    ],
    nodes: [
      { id: 1, name: "Alice" }, 
      { id: 2, name: "Bob" }, 
      { id: 3, name: "Charlie" }
    ]
  }]
}
```

#### Expected behaviour
* The chart should adapt to nodes of different heights
* The hover/clickable region should match the node's visual dimensions

#### Actual behaviour
<img width="597" alt="Screen Shot 2021-09-10 at 2 31 54 PM" src="https://user-images.githubusercontent.com/2754163/132907466-9971e718-5da7-4b65-bfb4-36c57d4fd3a4.png">

* The top of the "Alice" node is cut off and the text label is out of balance. 
* If you hover your mouse over the space beneath the node, the cursor changes as if it's hovering over the node and the tooltip appears
* Also, (unrelated) the right border of the "Charlie" node is getting cut off

#### Live demo with steps to reproduce
https://jsfiddle.net/tura8s7k/1

* Change the height to 50 or remove the declaration and the chart appears properly, but it gets gradually worse as the height increases above 50

#### Product version
Highcharts v9.2.2

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment]
Hi @MrLeebo, thank you for reporting a bug.

**Comment by KacperMadej** [comment]
`height` is not in the API. Use [`nodeWidth`](https://api.highcharts.com/highcharts/series.organization.nodeWidth) instead.
Working demo: https://jsfiddle.net/BlackLabel/staz673y/
