### ISSUE TITLE
Custom builds don't reduce the bundle size by much

### ISSUE THREAD

**Issue by MrLeebo** [highcharts/highcharts#16323]
I'm trying to reduce the size of my web application's bundle and Highcharts is the largest dependency in the app. I followed the [documentation on creating a custom build](https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files). I wasn't noticing much of a size reduction in my own file, so I tried simplifying things by assuming the "Line Series" example from the documenation.

#### Expected behaviour
* The example master file from the documentation only bundles the Line Series chart, I would expect it to have a remarkable reduction in file size.

```ts
// lineseries.src.ts
'use strict';
import Highcharts from '../Core/Globals.js';
import SVGRenderer from '../Core/Renderer/SVG/SVGRenderer.js';
import Chart from '../Core/Chart/Chart.js';
import LineSeries from '../Series/Line/LineSeries.js';
const exports: AnyRecord = Highcharts;
exports.Renderer = SVGRenderer;
exports.SVGRenderer = SVGRenderer;
exports.Chart = Chart;
exports.chart = Chart.chart;
exports.LineSeries = LineSeries;
export default exports;
```

#### Actual behaviour
(For simplicity, I'm using the compiled source file sizes, because the minified/gzipped sizes should be proportional to that.)

* This file (lineseries.src.js) compiles to a whopping 1.7mb out of the baseline (highcharts.src.js) 2.1mb. So even if we bundle one chart type, the best we can achieve is a ~20% reduction in bundle size? Is that correct?

#### Live demo with steps to reproduce
https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files

1. Copy the master file into the ts/masters/ folder
2. Run `npx gulp scripts`
3. Inspect the file size of the output file in the code/ folder

#### Product version
Highcharts 9.2.2

#### Affected browser(s)
N/A

**Comment by bre1470** [comment]
Yes, this is correct. At the moment our package assembling allows only file-scoped tree shaking. We are heading for named exports, so that tree shaking becomes more effective, but this takes time.
We still need to prepare a lot of extensions and series for that and then we have to change the building pipeline. We like to be done with preparations by end of this year. Working on the new building pipeline will start right after that.

**Comment by MrLeebo** [comment]
That's reasonable. Is there anything I can do to help?

**Comment by bre1470** [comment]
It would be interesting to hear, what functionality you need in your bundle. Something like:
- Axis type:
- Series type:
- Accessibility: yes/no
- Animation: yes/no
- Boost: yes/no
- DataLabels: yes/no
- Exporting: yes/no
- Legend: yes/no
- Tooltip: yes/no
Some of these are hard dependencies and a reason for the size of the core bundle.

**Comment by MrLeebo** [comment]
I'll try to answer as best I can:

- Axis type: Linear
- Series types: Line, Column, Bar, Bubbles, Organization Chart, Pie
- Accessibility: It has never been an explicit requirement, but it would pain me to completely leave accessibility users behind because that perpetuates them being 2nd class users
- Animation: Yes
- Boost: No
- DataLabels: Yes
- Exporting: Yes, but only for one chart
- Legend: Yes, but it's typically a custom template anyway
- Tooltip: Yes, also custom templates usually

We do generate PDF exports of our report pages, so it would be a nice-to-have if there was a convenient way to swap over to a "for print" module would be really convenient, e.g. disabling accessibility, animations, exporting, tooltips all together.

**Comment by bre1470** [comment]
Thank you for the swift feedback. Regarding the package size you make use of most core components, so the bundle size will probably not shrink much more in the future.
Though the PDF use-case is a good example for improvements. When a static chart is needed, it would be helpful to skip animations, pointer, tooltip, etc to limit just on rendering. We plan some refactoring after the tree-shaking to decouple functionality more, but it is hard to tell, what will be possible.
