### ISSUE TITLE
Combination of relativeXValue and draggableX causes extreme movements across the x-axis when dragging

### ISSUE THREAD

**Issue by lfse-slafleur** [highcharts/highcharts#16328]
#### Expected behaviour
When dragging a point along the x-axis, I expect the point to follow my mouse cursor.

#### Actual behaviour
The point jumps to another coordinate on the x-axis where it continues to mimick the movement of the cursor. 

#### Live demo with steps to reproduce

https://jsfiddle.net/hkmtLcbg/

Set both `plotOptions.series.dragDrop.draggableX` and `series.relativeXValue` to `true`.

#### Product version

Highcharts 9.2.0 and up.

#### Affected browser(s)
Firefox, Edge, Chrome

**Comment by raf18seb** [comment]
Hi @TNO-SlaFleur, thank you for reporting the issue.

Bisected to https://github.com/highcharts/highcharts/commit/f524cfc3816df2d7748f5ff1dc55243385036a6a
Worked fine in 9.1.2, broken since 9.2.0.
