### ISSUE TITLE
Series outline color is not applied on 3D charts

### ISSUE THREAD

**Issue by amruta1eq** [highcharts/highcharts#16333]
#### Expected behaviour
When we set borderColor and borderWidth in series property on 3D charts - 3D  bar, 3D column, etc -> series outline color should be seen applied on chart.

#### Actual behaviour
Series outline color is not applied on 3D charts

#### Live demo with steps to reproduce
v8.2.2 : https://jsfiddle.net/zqdxf2vb/ and v9.2.2 : https://jsfiddle.net/zqdxf2vb/1/

#### Product version
v8.2.2 and v9.2.2

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi @amruta1eq!

For 3d series, you should use the [series.edgeWidth](https://api.highcharts.com/highcharts/series.column.edgeWidth) and [series.edgeColor](https://api.highcharts.com/highcharts/series.column.edgeColor) instead.
