### ISSUE TITLE
Hi @oysteinmoseng ,

### ISSUE THREAD

**Issue by rishuSrivastava11hcl** [highcharts/highcharts#16331]
Hi @oysteinmoseng ,

As per above ask "Can you please provide information about which props(property) we need to set to add legend name inside bar chart aria label." 
Could you please provide some reference on same?

_Originally posted by @rishuSrivastava11hcl in https://github.com/highcharts/highcharts/issues/14515#issuecomment-918062889_

**Comment by oysteinmoseng** [comment]
Answered in #14515.

**Comment by oysteinmoseng** [comment]
See #14515.
