### ISSUE TITLE
Highcharts 9.2.2 : Reset Zoom button is shown inspite of setting resetZoomButton theme visibility as hidden

### ISSUE THREAD

**Issue by amruta1eq** [highcharts/highcharts#16334]
#### Expected behaviour
When we set resetZoomButton theme visibility as hidden, "Reset Zoom" button should not be shown on xy zoom of the chart.

#### Actual behaviour
"Reset Zoom" button is seen on zoom action in v9.2.2 although hidden property is set. It works correctly on v8.2.2

#### Live demo with steps to reproduce
v8.2.2 : https://jsfiddle.net/40drvqup/ and v9.2.2 : https://jsfiddle.net/40drvqup/1

#### Product version
v9.2.2

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @amruta1eq 

Thank you for reporting the problem.

The option works when set in style - demo: https://jsfiddle.net/BlackLabel/mk5xtdcp/
```js
Highcharts.chart('container', {
  chart: {
    zoomType: 'xy',
    resetZoomButton: {
      theme: {
        style: {
          visibility: 'hidden'
        }
      }
    }
  },
...
```
