### ISSUE TITLE
The gaps between the dates displayed in the xAxis are not consistent

### ISSUE THREAD

**Issue by lehmannvalerie** [highcharts/highcharts#16344]
#### Live demo with steps to reproduce
https://jsfiddle.net/oqjyd6wt/1/
please change the size of the chart => when wider, at some point, you can see that there are bigger gaps between the xAxis-dates

#### Product version
9.2.2

#### Affected browser(s)
At least Firefox and Chrome

**Comment by KacperMadej** [comment]
Hi @lehmannvalerie 

Thank you for reporting the problem,

By default Highcharts Stock is using ordinal xAxis - all points are placed with equal distance regardless of actual x values. This is forcing datetime type xAxis to render ticks not consistently with gaps of different sizes, but the placement is based on allowed time [units](https://api.highcharts.com/highstock/xAxis.units) and using available [formats](https://api.highcharts.com/highstock/xAxis.dateTimeLabelFormats).

You could control behavior using the above two options and tick placement itself through tick-related options like [tickPositioner](https://api.highcharts.com/highstock/xAxis.tickPositioner).

Another way to resolve this is to [force](https://api.highcharts.com/highstock/series.area.dataGrouping.forced) dataGrouping and grouped points will be placed equally on equally spaced datetime xAxis ticks. Demo: https://jsfiddle.net/BlackLabel/u8mj4gpL/
