### ISSUE TITLE
Tools: gulp filesize eats last stash when no edits

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#16358]
#### Expected behaviour
When there are no changes compared to HEAD, the script should stop running with a friendly message.

#### Actual behaviour
When there are no changes, a new stash is not created. However, the script continues to the point where it applies _and deletes_ the last stash. 

#### Live demo with steps to reproduce
1. Create a bogus stash, or at least ake sure your last stash is not important.
2. Make sure the working tree is clean.
3. Run `gulp filesize`

**Comment by goransle** [comment]
Should have been closed when https://github.com/highcharts/highcharts/pull/16374 was merged
