### ISSUE TITLE
Add calendar quarters to the available units in data grouping

### ISSUE THREAD

**Issue by genevadev** [highcharts/highcharts#16350]
# Description of the feature
It is common in finance to report based on quarters. At the moment you can group by months and set the multiple to 3 but it won't align with the calendar quarters

1. Q1 is Jan 1st to March 31st 
2. Q2 is April 1st to June 30th
3. Q3 is July 1st to Sept 31st
4. Q4 is Oct 1st to Dec 31st

# Library related to the feature
Highcharts Stock

**Comment by karolkolodziej** [comment]
Could you please share a demo where the groups `won't align with the calendar quarters`?
I tried different approaches and combinations and it always works for me.

Demo: https://jsfiddle.net/BlackLabel/gdmbaso1/
