### ISSUE TITLE
xAxis breaks make OHLC/CandleStick series overlap.

### ISSUE THREAD

**Issue by stenTT** [highcharts/highcharts#16368]
#### Expected behaviour
No overlapping of individual candlesticks/ohlc points.

#### Actual behaviour
OHLC or CandeStick seriespoints are overlapping when making use of xAxis breaks to skip weekends.

#### Live demo with steps to reproduce
https://jsfiddle.net/stenTT/Lxa0pmvo/25/

Uncomment the xAxis breaks in this jsfiddle to get the series to overlap.

#### Product version
Highstock JS v9.2.2 (2021-08-24)

#### Affected browser(s)
Firefox

**Comment by KacperMadej** [comment]
Hi @stenTT 

Thank you for reporting the problem.

_Internal note:_
Looks like even just the presence of the breaks option is changing how series and axis are rendered.
Demo with two charts diffing only with having or not the option (breaks) set: https://jsfiddle.net/BlackLabel/L7w49qn1/

**Comment by pawelfus** [comment]
Broken since v5.0.7. Most likely related issue: #5979 (this needs a bisect)

The same as in #5979, [Highcharts + broken-axis](https://jsfiddle.net/BlackLabel/L7w49qn1/1/) works fine, which suggests Ordinal involvement

**Comment by raf18seb** [comment]
It was broken before v5.0.7 too (different width, but still broken), so it looks like it's always been broken. Unable to bisect version <5.

Debug could be started in the `beforeSetTickPositions` method or by searching for a `hasBreaks` flag.
