### ISSUE TITLE
series.update throws error on mouseOver event when data grouping set

### ISSUE THREAD

**Issue by bm64** [highcharts/highcharts#16366]
#### Expected behaviour
User should be able to update series properties with series.update on mouseOver event.

#### Actual behaviour
When data grouping set, updating series properties on mouseOver throws error: `Uncaught TypeError: Cannot read properties of null (reading 'linkedParent')`

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/d31kyt0u/
steps to reproduce: 
1. hover the series
2. check the console for error

#### Product version
Highstock 9.2.2

#### Affected browser(s)
N/A

**Comment by KacperMadej** [comment]
Hover state adds a class name that could be used to change the colors.

Workaround for OHLC (the real case reported via tech support): https://jsfiddle.net/BlackLabel/d31kyt0u/1/
Workaround for Line: https://jsfiddle.net/BlackLabel/d31kyt0u/2/
