### ISSUE TITLE
Chart Editor 

### ISSUE THREAD

**Issue by Srinath516** [highcharts/highcharts#16369]
Is there an option to integrate Highcharts Editor to our appliaction and customize it?
Also, is it possible to add more chart options in chart editor (should be able to create all types of charts using chart editor)?

**Comment by raf18seb** [comment]
Hi @Srinath516! GitHub is our issues/features tracker only. If you have a question, please contact us on one of our dedicated support channels. More info: https://www.highcharts.com/blog/support/
I'm closing the ticket here, thanks for understanding.
