### ISSUE TITLE
update series / addPoint doesn't work for parallelCoordinates 

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#16380]
#### Expected behaviour

The point should be added to the existing series or the series should be updated with new data. 

#### Actual behaviour

The error occurs in the console.

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/1chyvL9m/

**Comment by raf18seb** [comment]
Thanks for reporting this issue, @Basts!

In the current implementation, the chart is creating the parallel axes only on chart init. This is dictated by performance: a parallel chart, in general, is used with a lot of data. Watching changes in the dataset (number of categories etc.) would cost quite a lot of performance and we assumed it would be easier and faster to recreate the chart when we really need it.

Demo: https://jsfiddle.net/BlackLabel/w8ontb4s/

Closing as not a bug.

**Comment by raf18seb** [comment]
Actually, we can tag it as a feature request and think about adding this functionality. There might be use cases for using parallel coordinates with a small amount of data.

**Comment by pawelfus** [comment]
Internal note:
It could be a good idea to add parallelCoordinates + polar chart demo to [docs](https://www.highcharts.com/docs/chart-and-series-types/parallel-coordinates-chart).

**Comment by maho2nd** [comment]
+1
