### ISSUE TITLE
highcharts stock Because the data is not standard, the distribution of X axis is not uniform·

### ISSUE THREAD

**Issue by mydb666** [highcharts/highcharts#16383]
![image](https://user-images.githubusercontent.com/76982510/134278533-5dffbee0-2db0-42a0-b00d-7c0a35273cf7.png)

![image](https://user-images.githubusercontent.com/76982510/134292161-1b04783f-83e6-4b90-ae02-e41d73c34d40.png)

Because the weekly data is irregular
I want the X-axis to be evenly distributed

![image](https://user-images.githubusercontent.com/76982510/134278649-2d13e969-b487-445e-b3c3-d596e8af15bd.png)
The annual is evenly distributed

**Comment by raf18seb** [comment]
Hi @mydb666, GitHub is our bugs/features tracker only. With support questions, please contact us on our dedicated support channels. More info: https://www.highcharts.com/blog/support/

ps. https://api.highcharts.com/highstock/xAxis.ordinal
