### ISSUE TITLE
'colorByPoint' does not exist in type 'PlotSunburstLevelsOptions'

### ISSUE THREAD

**Issue by dionathanCordova** [highcharts/highcharts#16399]
#### Actual behaviour
I have some trouble on Sunburst using typescript, the error is 'colorByPoint' does not exist in type 'PlotSunburstLevelsOptions'.

#### Live demo with steps to reproduce
![image](https://user-images.githubusercontent.com/17915601/134567337-7f8e8c63-4a3b-40c6-accc-0935ad79104d.png)

#### Product version example
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/sunburst

**Comment by KacperMadej** [comment]
Hi @dionathanCordova 

Thank you for reporting the problem.

Workaround: JS code works fine so for now you could cast to `any` to avoid the error in TS

_Internal note:_
The feature works and is used in the linked demo, but the docs and TS definitions are missing.

**Comment by dionathanCordova** [comment]
Thanks, for now I'm going to use "any" typing to avoid this error.

Thanks for answering.
