### ISSUE TITLE
Kaplan Meier Plots

### ISSUE THREAD

**Issue by mazimohiuddin** [highcharts/highcharts#16401]
Hi all,

Our goal is to generate a standard kaplan meier (KM) plot that is typically done for survival analysis using data in a typical event-based duration format: 
colA (time to event in days), colB (1=event, 0 = censored), colC (grouping variable)

The highchart R package seems to have some of this functionality implemented but I'm not sure if this module can be used as a library without a separate server with an R session.
https://rdrr.io/cran/highcharter/man/hchart.survfit.html

Being able to compute median survival times with 95% confidence intervals would be awesome as well as generating a p-value and hazard ratios (similar to coxph in R) when comparing two groups. R does this really well but we were hoping there was a pre-built solution that we could use that is compatible with a stand-alone angularjs webapp.

Thanks!

Best,
Edik

**Comment by KacperMadej** [comment]
Thank you for submitting the feature request.

At this moment you would have to provide the logic for the custom series plot data calculation by processing the raw/input data and creating/outputting the KM data to be plotted as a series.

**Comment by mazimohiuddin** [comment]
Hi,

I am copying my data scientist on this email. He will be able to comment about the logic for the KM plots.

Let’s keep this conversation moving forward to come up with a solution.

Thank you.

Regards,
Mazi
