### ISSUE TITLE
gantt  xAxis  remove  top bar

### ISSUE THREAD

**Issue by maleSun** [highcharts/highcharts#16408]
1.How to delete gantt  chart xAxis time bar 
![IMG_20210927_110545](https://user-images.githubusercontent.com/35056649/134844818-923d957c-4c7b-4c71-a362-507b52b463d9.jpg)

2.  How to  set gantt  chart  yAxis  label  width，the  title not  auto width
![IMG_20210927_122134](https://user-images.githubusercontent.com/35056649/134845058-beb29217-55a1-4c08-8ecf-6104d4f45e53.jpg)

**Comment by raf18seb** [comment]
Hi @maleSun!
GitHub is our bugs/features tracker only. With a support questions, please contact us on one of ours dedicated support channels.
More info: https://www.highcharts.com/blog/support/
https://github.com/highcharts/highcharts/blob/master/repo-guidelines.md#reporting-issues
