### ISSUE TITLE
SMA's value is wrong, it should use index 3, which is 'close', instead of default 0, which is 'open'

### ISSUE THREAD

**Issue by lhzw** [highcharts/highcharts#16415]
#### Expected behaviour
Correct sma value, the same as python's and the security software's.

#### Actual behaviour
```
In [1]: import json 

In [2]: import requests

In [3]: r = requests.get('https://demo-live-data.highcharts.com/aapl-ohlcv.json')

In [4]: r.json()
In [5]: d = r.json()
In [7]: sum = 0

In [8]: for i in d[-14:]:
   ...:     sum += i[4]
   ...: 

In [10]: sum / 14
Out[10]: 146.98857142857142

The sma(14) on the graph is: 147.8929

In [17]: sum = 0

In [18]: for i in d[-15:]:
    ...:     sum += i[4]
    ...:

In [19]: sum / 15
Out[19]: 147.53

sma(15) on the graph is: 148.4987.
```
Later I wrote a small function to see which data was hs's ma using, and found it used the 'open' value:
```
In [21]: def ma(cnt, idx):
    ...:     sum = 0
    ...:     for i in d[-cnt:]:
    ...:         sum += i[idx]
    ...:     avg = sum / cnt
    ...:     print(avg)
    ...:     return avg
    ...:

In [22]: ma(15, 4)
147.53
Out[22]: 147.53

In [23]: ma(15, 3)
146.40666666666667
Out[23]: 146.40666666666667

In [24]: ma(15, 2)
149.29866666666663
Out[24]: 149.29866666666663

In [25]: ma(15, 1)
148.49866666666668
Out[25]: 148.49866666666668

In [26]: ma(14, 1)                                                                                                                                          
147.89285714285714
Out[26]: 147.89285714285714
```

#### Live demo with steps to reproduce

https://www.highcharts.com/demo/stock/sma-volume-by-price/dark-unica
--> "Edit in codepen"
Modify the "week" in the datagrouping to "day", easy to check it.

#### Product version
highstock 7.1.2 and 9.2.2 both have this problem.
I checked the SMA indicator in the repository, and found it used the 'open' as the default, but we should use the 'close' value as default.

```
https://github.com/highcharts/highcharts/blob/master/ts/Stock/Indicators/SMA/SMAIndicator.ts
        params: {
            /**
             * The point index which indicator calculations will base. For
             * example using OHLC data, index=2 means the indicator will be
             * calculated using Low values.
             */
            index: 0,
            /**
             * The base period for indicator calculations. This is the number of
             * data points which are taken into account for the indicator
             * calculations.
             */
            period: 14
        }
    } as SMAOptions);
```
#### Affected browser(s)
Google chrome 93.

**Comment by lhzw** [comment]
I can use the option of course, but it's not a problem whether I use the option or not, it's the default behavior of the sma or ema, or the others, ema's default behavior is correct, in everyone's expectation.
And I only found the 'period' option, didn't see the 'index' when I tried to learn how to use this indicator. Generally we only specified the 'period' to these indicators.
I thought it used 'close', until recently I found it was not, it shocked me a lot. We (and the security softwares) always used 'close' to calculate SMA, EMA, MACD, etc.

> https://www.investopedia.com/terms/s/sma.asp
> What Is Simple Moving Average (SMA)?
> A simple moving average (SMA) calculates the average of a selected range of prices, usually closing prices, by the number of periods in that range.
> 
> https://en.wikipedia.org/wiki/MACD
> The MACD indicator [2](or "oscillator") is a collection of three time series calculated from historical price data, most often the closing price.

**Comment by raf18seb** [comment]
@lhzw,

We rethought this behavior and, after all, we agree with you - we should provide SMA that is calculated on `close` value by default. We'll correct it soon.

Thanks!
