### ISSUE TITLE
Bubble chart not animated

### ISSUE THREAD

**Issue by antikh** [highcharts/highcharts#16422]
#### Expected behaviour
When I updates series of bubble chart they should be animated. Now they animated only if explicitly set series mark symbol. If I not set it animation not happens.

#### Actual behaviour
The bubbles jump to their new positions without being animated

#### Live demo with steps to reproduce
http://jsfiddle.net/antikh/6b8efjtr/

#### Product version
http://github.highcharts.com/master/highcharts.js
http://github.highcharts.com/master/highcharts-more.js

#### Affected browser(s)
Only tested in Chrome

**Comment by raf18seb** [comment]
Hi @antikh, thank you for reporting a bug.
