### ISSUE TITLE
Since 9.1.1 setting tooltip directly to false produces error

### ISSUE THREAD

**Issue by DKhalil** [highcharts/highcharts#16423]
#### Expected behaviour
Up until 9.1.1 setting `tooltip: false` just disabled the tooltip

#### Actual behaviour
I get this error message:
`Cannot create property 'userOptions' on boolean 'false'`

#### Live demo with steps to reproduce
https://jsfiddle.net/oyLwc2x7/

#### Product version
Highcharts 9.1.1

**Comment by raf18seb** [comment]
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/16201
