### ISSUE TITLE
No marker is displayed on a polar chart with parallel coordinates 

### ISSUE THREAD

**Issue by warbix** [highcharts/highcharts#16427]
#### Expected behaviour
All my serie markers are displayed when the property:  `series.marker:{enabled:true}` is set.

#### Actual behaviour
With a polar chart **with** parallel-coordinates (via the module), no markers is displayed.
Setting to false either the polar property or the parallel coordinates makes the markers available.

#### Live demo with steps to reproduce
http://jsfiddle.net/a0r6owLp/

#### Product version
Highchart 8.2.0 & 9.2.2 (haven't test any other version)

**Comment by raf18seb** [comment]
Hi @warbix, thanks for reporting a bug.

Worked fine in 8.0.0, broken since 8.0.1. Unable to bisect.
