### ISSUE TITLE
Series of scatter plot don't show under certain circumstances.

### ISSUE THREAD

**Issue by Humaots** [highcharts/highcharts#16431]
#### Expected behaviour
Series can be shown.

#### Actual behaviour
Series don't show up.
If I change the height of chart or max of yAxis, the series can be shown.

#### Live demo with steps to reproduce
https://jsfiddle.net/q7vxj860/6/

#### Product version
Highcharts JS v9.2.2

#### Affected browser(s)
Chrome (didn't test on other browsers)

**Comment by KacperMadej** [comment]
Hi @Humaots 

Thank you for reporting the problem.

Hotfix/workaround: https://jsfiddle.net/BlackLabel/qwmybLa6/

_Internal note:_
Floating-point rounding problem could be resolved by adding correctFloat for ` sign * (val - (localMin as any)) * localA` in  
https://github.com/highcharts/highcharts/blob/e6f30d4a21be004f5ea124098f46d2783343cce5/ts/Core/Axis/Axis.ts#L867-L877
