### ISSUE TITLE
"Collapsed: true" property is being ignored when using setData(array) function for the Highchrat Gantt

### ISSUE THREAD

**Issue by rameshpantam** [highcharts/highcharts#16434]
#### Expected behaviour
When Collapsed: true property used in the data, the item on the gantt chart should be collpased.

#### Actual behaviour
When binding the data array to gantt chart through setData function, even though the data has Collapsed: true property, the chart does not show the record collapsed. 

#### Live demo with steps to reproduce
Below example showing sample data with "Collapsed: true" but  when setData function used, the actual item is not collapsed on the chart.
https://jsfiddle.net/KandyMan/hjdb86w0/1/

#### Product version
Highcharts Gantt JS v9.2.1 (2021-08-19)

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @rameshpantam ,

Thank you for reporting the problem.

_Internal note:_
Looks like related to https://github.com/highcharts/highcharts/issues/9980
