### ISSUE TITLE
Ticks missing while scrolling grid axis.

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#16439]
#### Expected behaviour
Show all ticks after scrolling.

#### Actual behaviour
After scrolling quickly the grid axis, some ticks are missing.
Might be related to #16061
![Screenshot 2021-10-04 at 09 56 38](https://user-images.githubusercontent.com/57004120/135814537-fc326054-5409-491b-9be8-c3d21ff0bcb8.png)
 
FYI: @khlieng 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/vow3zx5j/

#### Product version
Highcharts Gantt JS v9.2.2 (2021-08-24)

#### Affected browser(s)
All

**Comment by keerthisuresh** [comment]
Hi, 

Can I get an approximate date by when this will be resolved? 

Thank you very much

**Comment by KacperMadej** [comment]
There is no ETA for the fix yet. We should have more info later this week.
