### ISSUE TITLE
xAxis formatter used with zooming in xrange series

### ISSUE THREAD

**Issue by zougui** [highcharts/highcharts#16440]
Please have a look on the very simple JSFiddle page : https://jsfiddle.net/hmfcsb1d/1/

-	The xAxis displays only 5 ticks
-	When we zoom, the xAxis formatter doesn’t change to display hours.

I notice that when an xrange serie has more than one bar, the formatter is no more correct.

I tried to split my bars in several series and all seem to be correct : 
-	One tick for one day
-	After zooming, hours display correctly
But we don’t want to generate as many series as we have bars.

Please let’s see at : https://jsfiddle.net/hmfcsb1d/2/

Is it a bug in datetime xAxis for xrange series when more than one point is specified ?

Results wanted :
-	Declare several bars for several xrange series in our chart
-	Display hours after zooming

---------------

First support's response :

I'm not sure if that is a bug... It works like this from version 6.x.x.
The issue is replicable in an ordinary chart with line series: https://jsfiddle.net/BlackLabel/3t0vu85f/

Could you please report that issue on or GH where we could discuss it with our developers?

**Comment by KacperMadej** [comment]
Hi @zougui ,

Thank you for reporting the problem.

By default, ticks are not calculated for ranges lower than minimal points distance in the axis series. Adding a second point sets minimal points distance. This happens because otherwise, you might end up zooming into a time range that has ticks and labels in the time axis that are not related to the series data at all.

As I understand, in your case this is the desired effect, so as a workaround, you could add a hidden scatter series to get dense tick placement after zoom in. Demo: https://jsfiddle.net/BlackLabel/k3znpgcb/

**Comment by zougui** [comment]
Thank you for your answer.

The behaviour is as expected by adding an hidden serie.

You can close the ticket.

Cordialement,
Sylvain Guignard

De : Kacper Madej ***@***.***>
Envoyé : lundi 4 octobre 2021 17:56
À : highcharts/highcharts ***@***.***>
Cc : GUIGNARD Sylvain ***@***.***>; Mention ***@***.***>
Objet : Re: [highcharts/highcharts] xAxis formatter used with zooming in xrange series (#16440)


Hi @zougui<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzougui&data=04%7C01%7Csguignard%40clariteam.com%7Cdc511388ac9442a5d9ff08d9874f7865%7C781a058062f946d3aaf7426e30caa39d%7C0%7C0%7C637689597672848098%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f9zbttalupch29w%2BkZwyWFauePcllr%2BtxLnLvFvCXCY%3D&reserved=0> ,

Thank you for reporting the problem.

By default, ticks are not calculated for ranges lower than minimal points distance in the axis series. Adding a second point sets minimal points distance. This happens because otherwise, you might end up zooming into a time range that has ticks and labels in the time axis that are not related to the series data at all.

As I understand, in your case this is the desired effect, so as a workaround, you could add a hidden scatter series to get dense tick placement after zoom in. Demo: https://jsfiddle.net/BlackLabel/k3znpgcb/<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjsfiddle.net%2FBlackLabel%2Fk3znpgcb%2F&data=04%7C01%7Csguignard%40clariteam.com%7Cdc511388ac9442a5d9ff08d9874f7865%7C781a058062f946d3aaf7426e30caa39d%7C0%7C0%7C637689597672848098%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fvJAu34Mc4HN7%2BV6%2Fbv%2FhOp1PBNjmIU6EkPV8q94ME4%3D&reserved=0>

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhighcharts%2Fhighcharts%2Fissues%2F16440%23issuecomment-933622720&data=04%7C01%7Csguignard%40clariteam.com%7Cdc511388ac9442a5d9ff08d9874f7865%7C781a058062f946d3aaf7426e30caa39d%7C0%7C0%7C637689597672858092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Er9MFwQPqvPZJ6gYqLFZ5Ib0A0WKE7qZ%2FNGHWhY1SI8%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA67GGMBDB7YE7NWHXY73A3UFHFBFANCNFSM5FIYP3UA&data=04%7C01%7Csguignard%40clariteam.com%7Cdc511388ac9442a5d9ff08d9874f7865%7C781a058062f946d3aaf7426e30caa39d%7C0%7C0%7C637689597672858092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=stRDqK98fHa%2FeYVZaZz1V6nl3ykcnLqv%2Bz9D%2BRESMQ8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csguignard%40clariteam.com%7Cdc511388ac9442a5d9ff08d9874f7865%7C781a058062f946d3aaf7426e30caa39d%7C0%7C0%7C637689597672868080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8wbWePFe3EGWOkU42TYz1ICKGgkKvPB%2Fp%2B72RAL1W30%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csguignard%40clariteam.com%7Cdc511388ac9442a5d9ff08d9874f7865%7C781a058062f946d3aaf7426e30caa39d%7C0%7C0%7C637689597672868080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FGRY%2F%2FL2dZaDqkUpbzbGGfeALizoUpwXuRex36%2FN8BI%3D&reserved=0>.
