### ISSUE TITLE
The `clip` option is not respected in `chart.update` call

### ISSUE THREAD

**Issue by mrdavidjcole** [highcharts/highcharts#16455]
#### Expected behaviour

[The `clip` option ](https://api.highcharts.com/highcharts/series.line.clip)should take effect when included in the options object passed to `chart.update`.

#### Actual behaviour

`clip` seems to be ignored

#### Live demo with steps to reproduce

https://jsfiddle.net/kenchidave/kn87fhse/11/

To reproduce, just click the "Update" button above the chart. That will call `chart.update` with a new set of options, including `clip: false`, which will be ignored.

#### Product version
Highcharts 9.2.2

#### Affected browser(s)

Tested in Chrome 95.0.4638.32 and 94.0.4606.71, Safari 15, Firefox 94.0b1... seems pretty universal.

**Comment by kamil-musialowski** [comment]
Fixed since `v9.3.0`, closing ticket.

9.3.0 OP demo: https://jsfiddle.net/BlackLabel/m2v43qne/
