### ISSUE TITLE
Highcharts 9 throws a 'c is undefined' error when returning to the original series if you first zoom in on the x-axis before drilling down into additional details

### ISSUE THREAD

**Issue by ryanewtaylor** [highcharts/highcharts#16479]
#### Expected behaviour

When clicking "back to <series>" the chart should return the the respective series at the previous extent without error.

#### Actual behaviour

Highcharts 9 throws a 'c is undefined' error when returning to the original series if you first zoom in on the x-axis before drilling down into additional details.

```
Uncaught TypeError: c is undefined
    visibilitySetter highcharts.src.js:10798
    attr highcharts.src.js:9380
    I highcharts.src.js:1316
    attr highcharts.src.js:9358
    show highcharts.src.js:10520
    drillUp drilldown.src.js:744
    drillUpButton drilldown.src.js:641
    button highcharts.src.js:12912
    fireEventOnWrappedOrUnwrappedElement accessibility.src.js:868
    proxyMouseEventsForButton accessibility.src.js:1054
```

*This error does not happen in Highcharts 8.*

#### Live demo with steps to reproduce

1. Open demo: https://codepen.io/iamrewt/pen/jOwxYOy
2. Zoom in on the x-axis
3. Click one of the total_b, total_c, or total_d columns
4. Click "back to <series>"

#### Product version

Highcharts 9

*This error does not happen in Highcharts 8.*

#### Affected browser(s)

Firefox, Chrome. Not tested in Edge.

**Comment by ryanewtaylor** [comment]
@raf18seb , do you know when this bug may be scheduled for a fix. This is preventing us from migrating from v8 to v9. We are currently licensed for v9.

**Comment by raf18seb** [comment]
@ryanewtaylor  Thank you for bumping this up, we will discuss this ticket and prioritize if possible. We'll provide more info soon.

**Comment by ryanewtaylor** [comment]
I see this has been fixed, but I do not see it included in the release notes here: https://www.highcharts.com/blog/changelog/. Has this fix been incorporated into a public release?
