### ISSUE TITLE
Clicking on edge of 3D Pie Chart has Inconsistent Behavior

### ISSUE THREAD

**Issue by PyroSA** [highcharts/highcharts#16474]
#### Expected behaviour
Clicking on 3D Pie Chart Edge should act like a click on the surface itself.

#### Actual behaviour
Inconsistent - seems to depend on where the cursor came from.
Could do one of:
- Select Correct Segment
- Nothing
- Select Wrong Segment

#### Live demo with steps to reproduce
https://www.highcharts.com/docs/chart-concepts/3d-charts#3d-pie
http://jsfiddle.net/ued470wz/
Click on the edge...
![edge-click-0](https://user-images.githubusercontent.com/3801259/136466492-5e752639-f728-4120-b805-5d1fbf8f7cfd.gif)
![edge-click-1](https://user-images.githubusercontent.com/3801259/136466494-0eda6bac-c1b7-49c9-a8dd-bf5b3abc82fc.gif)
![edge-click-2](https://user-images.githubusercontent.com/3801259/136466495-3e22ba19-f2e2-4cd5-b1e7-f38fe1d46b24.gif)

#### Product version
Highcharts 9.1.2

#### Affected browser(s)
Google Chrome, Edge, Others?

**Comment by PyroSA** [comment]
@KacperMadej I'll see if I can get that into our project - Thanks 👍

**Comment by KacperMadej** [comment]
In general, there is a logic for ensuring that in Highcharts parts, so it could be utilized like here: http://jsfiddle.net/BlackLabel/uxt410z7/1/

Generalized template:
```js
  (function(H) {
    var _modules = H ? H._modules : {};

    function _registerModule(obj, path, args, fn) {
      if (!obj.hasOwnProperty(path)) {
        obj[path] = fn.apply(null, args);
      }
    }
    _registerModule(_modules,
		'Custom/3d-pie-fix', // unique name of the code part
		[_modules['Core/Series/SeriesRegistry.js'], _modules['Core/Utilities.js']], // load some other parts
		function(SeriesRegistry, U) { // args are the loaded parts

      // your code goes here
			
			// return something to have it accessible
			// to be loaded like SeriesRegistry in the example
    });
  }(Highcharts));
```
