### ISSUE TITLE
Passing improper types to series should trigger a warning

### ISSUE THREAD

**Issue by igorpejic** [highcharts/highcharts#16486]
#### Expected behaviour

When an Object is by mistake passed to `series` (instead of an array) it would be useful to receive a warning as a developer.

Silently failing to render ignoring the values passed, causes confusion especially in cases when the re-render is done quickly after (e.g., in React).

The main problem is that the [`update` method](https://api.highcharts.com/class-reference/Highcharts.Chart#update) accepts an object, while the `init` method does not.

Users of this library would benefit from seeing such a warning.

This bug is affecting people and, in my opinion, leading them to debug in the wrong direction such as in this thread: https://github.com/highcharts/highcharts-react/issues/121

#### Actual behaviour

No warning is dispatched which makes it harder to debug what is wrong.

#### Live demo with steps to reproduce

https://stackblitz.com/edit/react-qhmcck?file=index.js

1. Load and observe no data is rendered
2. Click on button which causes a re-render and observe the data is now rendered even though the series argument passed is the same as in the initialization step.

#### Product version
highcharts 9.2.2
highcharts-react 3.0.0

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi @igorpejic, thanks for creating the ticket!

I'm not sure whether we should throw warnings whenever the user uses any chart's option incorrectly.
The API clearly says that the `series` should be an array of objects:
![image](https://user-images.githubusercontent.com/23310742/137297338-c9dc3546-fdfd-465b-a8c1-8a4de858a6c8.png)

We could add a warning here, but there are also thousands of other options/properties that should be defined in a specific format and this is what the API is for - to show the users how to use those properties correctly.

I'm not sure why the `series` worked fine when defined as an object in the React wrapper (I know that confused you and led to unexpected problems), but you shouldn't define it as an object in the first place (it should be defined as an array of objects).

**Comment by igorpejic** [comment]
Hi @raf18seb thank you for the response.

> I'm not sure why the series worked fine when defined as an object in the React wrapper 

Please take a look at the [example](https://stackblitz.com/edit/react-qhmcck?file=index.js) I posted. Passing an object to series renders it correctly the second time (in the example: after clicking on the button) because [Highcarts.update](https://api.highcharts.com/class-reference/Highcharts.Chart#update) is used instead of the first time when it is not used.

> I'm not sure whether we should throw warnings whenever the user uses any chart's option incorrectly.

In principle I agree with this, but not when series can be an array and an object depending if [`update`](https://github.com/highcharts/highcharts-react/blob/f7f9efcabec44f60269aecd767aefa149541d1de/src/HighchartsReact.js#L56) or [`initialization`](https://github.com/highcharts/highcharts-react/blob/f7f9efcabec44f60269aecd767aefa149541d1de/src/HighchartsReact.js#L43) of Highcarts are used.

I suppose it is just unfortunate how this error manifests to React users when the component gets rendered twice and in this particular case the library silently failing did not help at all. 

> The API clearly says that the series should be an array of objects:
image

You are right. It was an unlucky mistake.
