### ISSUE TITLE
Highcharts styledMode export not working in Safari

### ISSUE THREAD

**Issue by vcward** [highcharts/highcharts#16483]
Apologies if this has already been reported. Haven't been able to find any other reference to it.  The exports in charts where `styledMode` is true do not seem to work correctly in the latest version of Safari.

#### Expected behaviour
When using `styledMode`, the chart export should maintain custom colors set in stylesheet.

#### Actual behaviour
Works fine in Chrome and Firefox, but, in Safari, the chart exports as an all black image.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/css/colors/
Using one of the highcharts demos, the export in the above demo works in Firefox and Chrome. However the PNG, JPEG, PDF, and SVG options export an all black image in Safari.
If the `styledMode` property is set to false, the export works in all 3 browsers with highcharts' default colors.

#### Product version
Highcharts JS v9.2.2

#### Affected browser(s)
Safari 15.0

**Comment by matthew-b-shaw** [comment]
Any update on this?

**Comment by raf18seb** [comment]
Hi @matthew-b-shaw, we don't have ETA for this issue yet.

**Comment by svensigmond** [comment]
@raf18seb this seems to work since Highcharts 10.2. Any chance this has been ninja patched?

**Comment by vcward** [comment]
Looks like it was fixed in May (https://github.com/highcharts/highcharts/pull/17250). 👍
