### ISSUE TITLE
Highstock: series.addPoint() bug when there is no data in a second series

### ISSUE THREAD

**Issue by OskarMatysiak** [highcharts/highcharts#16492]
#### Behavior

If in the second series is no data and property `showInNavigator` is setting to `true` the animation on series.addPoint() doesn't work.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/u4cz1woa/

#### Product version
9.0.0+

**Comment by raf18seb** [comment]
Hi @OskarMatysiak, thanks for reporting the issue!

Simplified demo: https://jsfiddle.net/BlackLabel/wfkn5dqr/

Working fine in 6.1.4, broken since 6.2.0.
Regression after https://github.com/highcharts/highcharts/pull/9107/commits/7bf433607a12d7884a35a26d8a7241931f78e460

**Comment by pawelfus** [comment]
**Workaround:**

Demo: https://jsfiddle.net/BlackLabel/u4cz1woa/3/

Plugin:

```js
(function(H) {
  H.wrap(
    H.Navigator.prototype,
    'getBaseSeriesMin',
    function(proceed, currentMin) {
      return this.baseSeries.reduce(
        function(min, series) {
          // (#10193)
          return Math.min(min, series.xData && series.xData.length ? series.xData[0] : min);
        },
        currentMin
      );
    }

  );
})(Highcharts);
```
