### ISSUE TITLE
Legend scroll into view not working as expected when accessibility is enabled and animation is disabled.

### ISSUE THREAD

**Issue by pvsleeper** [highcharts/highcharts#16496]
#### Expected behaviour
When using the keyboard to focus the legend, the focused series should scroll into view, even when animation is disabled.

#### Actual behaviour
The focused series in the legend does not reliably scroll into view when animation is disabled, making it unclear where the focus currently lies. It however behaves correctly when animation is enabled. 

#### Live demo with steps to reproduce
https://jsfiddle.net/rvukL8w7/28/

#### Product version
9.2.2

#### Affected browser(s)
Google Chrome, Edge

**Comment by oysteinmoseng** [comment]
@pvsleeper @raf18seb I don't seem to be able to reproduce this issue. Following the steps in the jsFiddle, tabbing back to the legend without animation enabled still scrolls the legend to the top for me. Can either of you reproduce the issue reliably?

**Comment by pvsleeper** [comment]
Hi @oysteinmoseng - I just checked my jsFiddle again - if I fix the version of Highcharts to 9.2.2 the issue is still there, but by using the latest version, its working as expected, so I am guessing its was fixed. Thank you!

**Comment by oysteinmoseng** [comment]
Great, closing this for now then. Feel free to comment to reopen at a later stage if needed.
