### ISSUE TITLE
Custom Context Button Image leaves off place shadow when hovered.

### ISSUE THREAD

**Issue by BurntMoney** [highcharts/highcharts#16501]
When using the ability to provide a custom image for the context button, I can hover the image, and see an off place shadow.

#### Expected behaviour
When hovering a custom image for a context button, the shadow is either around the image, or doesn't show at all.

#### Actual behaviour
When hovering a custom image for a context button, a shadow appears that is a noticeable amount of pixels off.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/Lwcmpe87/

Hover over context menu button

**Comment by bre1470** [comment]
It looks like the API documentation has been fixed in the master. Changes will go online with the next release.
