### ISSUE TITLE
Docs AST

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#16521]
#### Expected behaviour
Add to the documentation a list of `allowedAttributes`,`allowedReferences` and `allowedTags`.

#### Live demo with steps to reproduce
https://api.highcharts.com/class-reference/Highcharts.AST#.allowedAttributes

**Comment by bre1470** [comment]
I am not sure, how the issue can be solved. Do you like to see more examples? Should we list the default values (70! tags)? Please elaborate.

**Comment by karolkolodziej** [comment]
I thought about listing them in jsdoc or adding a reference to the [code](https://github.com/highcharts/highcharts/blob/f12510b19595b64728cb61c0f1e2f1517fa49b17/ts/Core/Renderer/HTML/AST.ts#L114-L185)

**Comment by bre1470** [comment]
We should link between docs and class reference at least, but where to put defaults is difficult to decide. Code linking is fragile, so maybe add a new doc.

@TorsteinHonsi
Should we and if how should we integrate all the defaults of AST?
- https://api.highcharts.com/class-reference/Highcharts.AST
- https://www.highcharts.com/docs/chart-concepts/security

**Comment by TorsteinHonsi** [comment]
I think this belongs in the API
