### ISSUE TITLE
"Arrow Up" and "Arrow down" move focus out of Legend area when there is only one Legend

### ISSUE THREAD

**Issue by XiLiuRoy** [highcharts/highcharts#16520]
#### Expected behaviour
When using keyboard and there is only **one** legend, focus should stay on a legend unless "Tab" or "Shift + Tab" keys are pressed.

#### Actual behaviour
When using keyboard and there is only **one** legend, "Arrow Up" or "Arrow down" key move focus out of legend area.

#### Live demo with steps to reproduce
1. Hit "Tab" to focus on legend
2. Hit "Arrow Up" or "Arrow Down" keys
3. Focus move outside of legend area

https://jsfiddle.net/4ksLt6gx/

#### Product version
Highcharts 9.2.2

#### Affected browser(s)
Google Chrome, Edge

**Comment by oysteinmoseng** [comment]
This is actually by design (you should get the same behavior without wrapAround enabled), but I agree that it is unintuitive with the current tab model, so we should remove it.
