### ISSUE TITLE
AST warning message 

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#16526]
#### Expected behaviour
Make the warning more explicit/descriptive where the issue lays by for example linking [the security docs.](https://www.highcharts.com/docs/chart-concepts/security)

#### Actual behaviour
When the `tagName` is not on the AST list we get a warning: 
`Highcharts warning: Invalid tagName 'lineargradient' in config`

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/hq9g3km0/

#### Product version
Highcharts JS v9.3.0 (2021-10-21)

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Instead of simply adding the URL to the error message (for both "Invalid tagName" and "Invalid attribute"), consider setting up an error code and write a more lengthy explanation of the error there. See if we can pass the `tagName` or `attribute` as a parameter.
