### ISSUE TITLE
UseHTML in data tables

### ISSUE THREAD

**Issue by kai2468** [highcharts/highcharts#16536]
#### Expected behaviour
useHTML field set on text fields should carry over to the data table as well.

#### Actual behaviour
HTML tags are being shown in the data table header.

#### Live demo with steps to reproduce
1) Set useHTML on title and add a bold tag to the text value
2) Display data table from the export menu

Demo:
https://jsfiddle.net/fxgz17jw/

#### Product version
Latest

**Comment by kluvin** [comment]
Hi @raf18seb! Can you say anything about timelines on this? This bug is somewhat important to us, as it impacts nearly all our data tables.

If it's not prioritized, I would like to step up to help :)

**Comment by raf18seb** [comment]
Hi @kluvin,

unfortunately, we don't have ETA for this ticket yet.
What do you think about this workaround? (using the `exporting.tableCaption` and making it bold (or applying any other styles) using CSS): https://jsfiddle.net/BlackLabel/htgwk324/

```js
exporting: {
    showTable: true,
    tableCaption: 'Solar Employment Growth by Sector, 2010-2016'
},
```

```css
.highcharts-table-caption {
	font-weight: bold;
}
```

**Comment by kluvin** [comment]
The mention of `exporting.tableCaption` is useful, although we need to strip arbitrary HTML from the title, which I expect is close to what Highcharts might do eventually. Preserving formatting is not necessary or desired.

Nevertheless, I appreciate the fast reply!

**Comment by raf18seb** [comment]
@kluvin,

Sorry but we didn't find a simple workaround for building a proper tree from the text with tags in the export table.

> Preserving formatting is not necessary or desired.

If tag formatting is not required, then a simple string stripping should be enough: https://jsfiddle.net/BlackLabel/8qz4nmw9/
