### ISSUE TITLE
[Accessibility] Toggle legend in pie chart using keyboard only works the first time

### ISSUE THREAD

**Issue by bjornri** [highcharts/highcharts#16545]
#### Expected behaviour
Repeatedly pressing enter/space key should toggle the focused legend in Pie chart.

#### Actual behaviour
It only works the first time, then you need to refocus the legend before you can toggle again.

#### Live demo with steps to reproduce
https://jsfiddle.net/ej0ynb71/

1. Click "focus frame" to move focus to the iframe with the chart. 
2. Press tab until you reach the legend. 
3. Press enter to toggle one of the items. Observe that the item is toggled and the legend looks like its in focus however the arrow keys dont work anymore.
4. Press enter one more time to toggle the item back on.
5. Observe nothing happend.

#### Product version
Highcharts 9.3.0

#### Affected browser(s)
Chrome/Firefox

**Comment by oysteinmoseng** [comment]
More likely related to #16467, it seems the proxy elements are being recreated causing focus to be lost
