### ISSUE TITLE
No map on exported Highmaps 9.3

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#16552]
#### Expected behaviour
Working as expected in version 9.2: https://jsfiddle.net/BlackLabel/38e6mjk1/

#### Actual behaviour
When highmaps is downloaded as png, jpeg, pdf and svg, there is an empty canvas where the highmap should be. Everything else (such as title, legend etc.) is present, just not the map itself.

#### Live demo with steps to reproduce
1. Open jsfiddle: https://jsfiddle.net/BlackLabel/50hfy3ds/
2. Open context menu
3. Click on 'Download PNG image'

#### Product version
Highmaps 9.3

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Fixed on master - https://jsfiddle.net/BlackLabel/50hfy3ds/1/
Closing as resolved. The fix will be published in the next release.

**Comment by Ayushk93** [comment]
When new release will be published? as I'm getting same error DevTools failed to load source map: Could not load content for https://code.highcharts.com/9.3.1/lib/svg2pdf.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE in version 9.3.1 also.

**Comment by raf18seb** [comment]
@Ayushk93 v9.3.1 was published yesterday. The above demo is working fine in v9.3.1.
Do you still have any problems with exporting maps to PNG? If yes, could you provide a jsFiddle demo showing the issue?
