### ISSUE TITLE
Duplicated week numbers in the x axis 

### ISSUE THREAD

**Issue by SMH110** [highcharts/highcharts#16550]
Hi,

#### Expected behaviour
Unique week numbers in the x axis 

#### Actual behaviour
Duplicated week numbers in the x axis 

**Live Demo**
https://jsfiddle.net/fkdacgs8/7/
![image](https://user-images.githubusercontent.com/16171515/139030537-8b43dfd0-32f9-48b7-a620-6e51b555e31d.png)

#### Product version
Highcharts Gantt latest 

#### Affected browser(s)
All

**Comment by SMH110** [comment]
Hi, 
Any update on this?
Thanks

**Comment by raf18seb** [comment]
Hi @SMH110, we'll add this ticket to our flow board (means that it should be prioritized over most tickets).
