### ISSUE TITLE
Bug (Typescript): TooltipFormatterContextObject.x is declared as number but is assigned a string

### ISSUE THREAD

**Issue by BistroStu** [highcharts/highcharts#16565]
#### Expected behaviour
TooltipFormatterContextObject.x should be declared string because that is the type assigned to it.
I would be happy to contribute a fix that improves type safety.

#### Actual behaviour
TooltipFormatterContextObject.x is declared as number in the Typescript declarations and in the documentation.

TooltipFormatterContextObject.x is assigned Point.PointLabelObject.x which is assigned Point.category* which is declared as string.

(* If a Point has no category then it is assigned the number Point.x, but that should be converted toString to be consistent with the type declaration of Point.category)

Tooltip.ts:
```
            textConfig = {
                x: point.category, // string!
                y: point.y
            } as any;
            textConfig.points = pointConfig as any;

        // single point tooltip
        } else {
            textConfig = point.getLabelConfig() as any;
        }
        this.len = pointConfig.length; // #6128
        const text: (boolean|string) = (formatter as any).call(textConfig, tooltip);
```
```
namespace Tooltip {
    export interface FormatterCallbackFunction {
        (
            this: FormatterContextObject,
            tooltip: Tooltip
        ): (false|string|Array<string>);
    }
    export interface FormatterContextObject {
        color: ColorType;
        colorIndex?: number;
        key: number;
        percentage?: number;
        point: Point;
        points?: Array<FormatterContextObject>;
        series: Series;
        total?: number;
        x: number;
        y: number;
    }
```
Point.ts:
```
    public getLabelConfig(): Point.PointLabelObject {
        return {
            x: this.category, // string!
            y: this.y,
```

#### Live demo with steps to reproduce
In the following fiddle, most tooltips are broken because this.x does not have a toFixed method, except for Feb because its category is undefined.
https://jsfiddle.net/96mLwf82/1

#### Product version
Highcharts 9.3

#### Affected browser(s)
n/a

**Comment by BistroStu** [comment]
What do you think of these three possible solutions:

Declare x as string
- makes sense and easy to use
- when there is no category string for a point, convert its numeric x value to string
- control over formatting is lost in conversion
- may cause runtime errors in untyped code
- may cause compilation errors in existing typed code (which is ok)

Declare x as string|number
- simple solution but not a great outcome
- hard to document
- won't cause runtime errors
- may cause compilation errors in existing typed code (which is ok)

Declare x as number and add TooltipFormatterContextObject.category: string
- x would always be Point.x, which could be useful in some scenarios
- category would be the category string if defined
- if there is no category, it could be undefined or x converted to string
- may cause runtime errors or poorly formatted tooltips in existing code
- unlikely to cause compilation errors
- makes sense - consistent with other interfaces

**Comment by raf18seb** [comment]
Hi @BistroStu! We'll investigate this issue soon.
FYI @bre1470 if you could take a look when you're back.

Similar ticket: https://github.com/highcharts/highcharts/issues/16822

**Comment by BistroStu** [comment]
Hi @raf18seb,
Since you mentioned #16822 I went a bit deeper on this issue, addressing some of the underlying type problems in a new pull request #16837. No tests were broken by this change. There is still some work to do on it, so let me know if you would like me to continue. Specifically, I have not changed any of the exported interfaces because that depends on the answer to my previous question.

**Comment by raf18seb** [comment]
@BistroStu thanks for the PR!
We'll take a look at it when our TypeScript ninja is back from the Christmas vacations next week :)

**Comment by bre1470** [comment]
Hi @BistroStu,

Thank you for the PR. Unfortunately it does not solve the TypeScript issues in the NPM package. Our API documentation and TypeScript definitions are generated from source doclets. The source code, modified in your PR, is independent from that.

---

I took a look into the issue. It is hard to have a fix covering all needs. Playing around with a type union always breaks here and there type tests. For example:
```ts
export type TooltipFormatterCallbackFunction = (this: TooltipFormatterContextObject, tooltip: Tooltip) => (false|string|Array<(string|null|undefined)>|null|undefined);
export type TooltipFormatterContextObject = (TooltipFormatterPointContextObject|TooltipFormatterSharedContextObject);
export interface TooltipFormatterPointContextObject {
    color: (ColorString|GradientColorObject|PatternObject);
    colorIndex?: number;
    key: number;
    percentage?: number;
    point: Point;
    points: undefined;
    series: Series;
    total?: number;
    x: number;
    y: number;
}
export interface TooltipFormatterSharedContextObject {
    point: undefined;
    points: Array<TooltipFormatterPointContextObject>;
    series: undefined;
    x: string;
    y: number;
}
```
This approach results in `this.point` becoming optional and `this.x` becoming a mixed type of `number|string`. It does not improve the situation for the majority of users.

---

I think that the solution with the least impact on existing implementations is the introduction of a new `this.category` property for the shared formatter context. So something like:

```ts
export interface TooltipFormatterContextObject {
    category?: string;
    color: (ColorString|GradientColorObject|PatternObject);
    colorIndex?: number;
    key: number;
    percentage?: number;
    point: Point;
    points: (Array<TooltipFormatterPointContextObject>|undefined);
    series: Series;
    total?: number;
    x: number;
    y: number;
}
```

This solves this issue with minimal workaround and at the same time keeps the quirky typing for backwards compatibility.

**Comment by BistroStu** [comment]
Hi @bre1470,

I think you chose the best of the three options I put forward, but I don't agree with your solution for the TooltipFormatterContextObject interface. I will explain why.

There are three type systems in place:
- the doclet types which generate documentation and NPM type declarations (documented types)
- the Typescript compiler types which are used to compile the Typescript code (ts types)
- the actual types in use (implementation types)

(Usually the ts types and implementation types would be forced by the compiler to match one another, but in the Highcharts codebase the extensive use of `(___ as any)` and other type casting has allowed some significant differences to sneak in. That's what my pull request was trying to address.)

Your suggestion protects all Highcharts users from implementation type changes that would break existing code at runtime. I agree that is of highest importance for a minor release. You have also protected typescript users from documented type changes that could cause compile-time errors and extra maintenance. That is important too, but there is a third thing you have not protected users from and that is type mismatches that could lead to runtime errors in production.

Most typescript users would prefer to fix compile-time errors during development rather than risk future runtime errors in production. That's why they choose typescript. For this reason, it is more important to make the documented types match the implementation types than to keep the documented types consistent over time. 

I believe the following would more closely match the implemented types:

``` ts
export interface TooltipFormatterContextObject {
    category?: string;
    color?: (ColorString|GradientColorObject|PatternObject);
    colorIndex?: number;
    key?: number;
    percentage?: number;
    point?: Point;
    points?: (Array<TooltipFormatterPointContextObject>|undefined);
    series?: Series;
    total?: number;
    x: number | string;
    y: number;
}
```
But it would be even better to have a union type that properly represented the two alternative forms that this interface can take. It is important to declare the interface in one of those ways so the typescript compiler can protect against runtime errors when categories are added or removed or when changing shared and split tooltip options. It will also save developers the time and frustration of discovering type mismatches and re-casting them, which can prevent the compiler from guarding against runtime errors if the implementation types ever change in the future. I take your point about union types being problematic. Would it be acceptable to declare the Highcharts.TooltipFormatterCallbackFunction interface with a union parameter type instead of changing TooltipFormatterContextObject to a union type?

**Comment by bre1470** [comment]
After checking your mentioned `any` casts it becomes clear that the type of `context.x` is simply wrong. It never becomes a number in my tests. So I dismissed the idea with the new property and instead use `PointLabelObject` as the core of the tooltip context.

**Comment by bre1470** [comment]
@BistroStu, about your last question:
>  Would it be acceptable to declare the Highcharts.TooltipFormatterCallbackFunction interface with a union parameter type instead of changing TooltipFormatterContextObject to a union type?

It looks like we can actually get around any union type without a trade-off. Let me know if the [PR](https://github.com/highcharts/highcharts/pull/16856) is working for you. Once more thank you reporting the issue in detail and your proposal.

**Comment by BistroStu** [comment]
@bre1470, context.x can definitely be a number. If you don't provide xAxis categories or if one of the categories is undefined, then context.x is a number for all or one of the points. See https://jsfiddle.net/9t63gewy/
> `text.x` is simply wrong. It never becomes a number in my tests. So I dismissed the idea with the new property and instead use `PointLabe`

The reason is, context.x is assigned the value of Point.category, which is set on ts/core/series/series.ts line 2303:
```ts
            point.category = (
                categories &&
                typeof (categories as any)[point.x as any] !== 'undefined' ?
                    (categories as any)[point.x as any] :
                    point.x
            );

```
Point.category is typed string but it is a number under the conditions mentioned above. Once again, casting a variable "as any" will prevent Typescript from providing any kind of type safety.

**Comment by bre1470** [comment]
@BistroStu Thank you for the feedback.

**Comment by BistroStu** [comment]
Hi @bre1470, my original problem was that I had to cast this.x as string in my TooltipFormatterCallbackFunction and your PR does solve that. Thank you.
