### ISSUE TITLE
[9.3.0] Typescript - `visible` property of SeriesOptionsType

### ISSUE THREAD

**Issue by cexbrayat** [highcharts/highcharts#16572]
#### Expected behaviour

In v9.2.2, the following code compiles properly.

```ts
import { Options } from 'highcharts';

function hideAllSeries(options: Options) {
    options.series!.forEach(serie => serie.visible = false)
}
```

#### Actual behaviour

In v9.3.0, it fails to compile. See this [Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeTDYEB2BnOBfOAMyghDgHIALYAc0oGNKBDWbcgbgChPCBXTeuixxqAEwCmAQQA20gMriowcdgAUENBhwAuFJqzYAlIk5wzcDUJwA6bIuXYAhNcLQAok0aq7S8XAC8AHxwPsrWAG7A2MAARtJ+-kRM0naGnHhAA) for reproduction.

Is this intended or a regression in the typings?

```
 Property 'visible' does not exist on type 'SeriesOptionsType'.
  Property 'visible' does not exist on type 'SeriesCandlestickOptions'.

35           serie.visible = false;
```

#### Live demo with steps to reproduce
[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeTDYEB2BnOBfOAMyghDgHIALYAc0oGNKBDWbcgbgChPCBXTeuixxqAEwCmAQQA20gMriowcdgAUENBhwAuFJqzYAlIk5wzcDUJwA6bIuXYAhNcLQAok0aq7S8XAC8AHxwPsrWAG7A2MAARtJ+-kRM0naGnHhAA)

#### Product version
v9.3.0

**Comment by KacperMadej** [comment]
Hi @cexbrayat 

Thank you for reporting the problem,

_Internal note:_
This looks like a bug related to TS definitions @bre1470 

In `highcharts.d.ts` there is a strangely looking `candlestick?: (object|PlotCandlestickOptions);` where other series types look like this `bullet?: PlotBulletOptions;`.

Not sure if this is the reason but `PlotCandlestickOptions` do not have a complete list of all options - e.g. the reported `visible` is missing as if the options from ancestors (probably not the correct term) were not merged in. Comparision below:

![image](https://user-images.githubusercontent.com/8960408/140506502-c640e600-f281-4743-9ba3-6cdb37635887.png)
 
![image](https://user-images.githubusercontent.com/8960408/140506557-400bdbf2-82ed-489c-82e7-deeb46cc22a8.png)

The visible difference is `accessibility`, but there is much more. `interface PlotCandlestickOptions` is too short - lacks options that should be inherited. A close and valid option to compare it with is `PlotBulletOptions` - just a few options above in `highcharts.d.ts`.

**Comment by bre1470** [comment]
@KacperMadej That is strange. Thank you for the investigation, I will take a look.

**Comment by veloek** [comment]
We are having trouble regarding this as well. The issue seems to be further up the inheritance tree though, as `PlotOhlcOptions` is also lacking properties. From highcharts.src.d.ts:
```
export interface PlotOhlcOptions {
    dataGrouping?: PlotOhlcDataGroupingOptions;
    dragDrop?: PlotOhlcDragDropOptions;
}
```

**Comment by veloek** [comment]
@bre1470 Any progress on this one? We're unable to update the Highcharts package until this type issue is resolved.

**Comment by Whyseverythingtaken** [comment]
I have the same issue @veloek. In addition to `dataGrouping`, definitions for `tooltip` are also missing there. I get the following TS error.

`'tooltip' does not exist in type 'SeriesCandlestickOptions'`
