### ISSUE TITLE
Gantt Scrolling with axis settings min/max/scrollbar breaks the chart

### ISSUE THREAD

**Issue by dragoshzava** [highcharts/highcharts#16576]
#### Expected behaviour
Gantt Scrolling should work when setting axis min/max/scrollbar.

#### Actual behaviour
Gantt Scrolling with parent in data breaks and does not keep the set amount.
Gantt with no parent in data works.

#### Live demo with steps to reproduce
https://jsfiddle.net/Resems/0a4bLp2k/2/

#### Product version
9.3.0 ( Latest ) 
8.2+

#### Affected browser(s)
All

#### Attached Video
https://user-images.githubusercontent.com/3819194/139835979-3932212d-37cf-443e-b542-15397c3eefbb.mp4

#### Related Open ticket
The issue is that this was reported in 2020, and until now it was not solved
https://github.com/highcharts/highcharts/issues/13898

#### Workaround/Eta
Was wondering if there is any workaround or ETA for this issue, or even if it is going to be fixed.
Depending on the answer we have to take a decision to implement gantt or how to implement it, so would be nice to have a plan.

Thank you.

**Comment by raf18seb** [comment]
Hi @dragoshzava!

If the issue is already reported in another ticket, please continue the conversation there.
