### ISSUE TITLE
Seek Marker-Cluster unminified version if available

### ISSUE THREAD

**Issue by Krunal-Gosalia** [highcharts/highcharts#16571]
- I have already tried searching for the un-minified with full variable names but no luck. 

Would be great if someone can point me out the full-version of 'marker-cluster' js. Tried link from highchart page for 'marker-cluster' module but not found https://api.highcharts.com/highcharts/code.highcharts.com/modules/marker-clusters.js

Thanks in advance!

**Comment by raf18seb** [comment]
Correct URL: https://code.highcharts.com/modules/marker-clusters.js
