### ISSUE TITLE
Gantt, updating yAxis max doesn't work after using scroll ( yAxis scrollbar min/max )

### ISSUE THREAD

**Issue by dragoshzava** [highcharts/highcharts#16586]
#### Expected behaviour
It should update the max amount, despite if the scroll was used or not.

#### Actual behaviour
It works on initial load, or until you scroll.
After the scroll is used, it does not update anymore

#### Live demo with steps to reproduce
https://jsfiddle.net/Resems/0a4bLp2k/4/

#### Product version
9.3.0

#### Affected browser(s)
N/A

#### Attached video
https://user-images.githubusercontent.com/3819194/140049845-cb8b43d4-9923-45d6-982d-8ba1cbc3c029.mp4

**Comment by raf18seb** [comment]
Hi @dragoshzava, thank you for reporting the issue.
