### ISSUE TITLE
Map with overlaid pie charts has cropped pies charts.

### ISSUE THREAD

**Issue by magdalena-gut** [highcharts/highcharts#16588]
#### Expected behaviour
Full pie charts visible. 
It seems to be related to series clipping because setting `clip` to `false` fixes the problem.

#### Actual behaviour
The pie charts are cropped on the top.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/maps/map-pies

#### Product version
Highcharts 9.3.0

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! I did a quick fix for this in the demos so that we get it right for the upcoming release.
