### ISSUE TITLE
Map drilldown animation is not working correctly

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#16601]
#### Expected behaviour
The animation should work like in the 9.2.2 version when drilling down and drilling up independently on drilldown level.

#### Actual behaviour
Let's discuss the map drill down with level 1, level 2 and level 3.

1. In version 9.2.2, the animation was working fine for:
- level 1 -> level 2 (drilldown)
- level 2 -> level 3 (drilldown)
- level 2 -> level 1 (drillup)
but wasn't working correctly for:
- level 3 -> level 2 (drillup)

2. Since version 9.3.0, the animation is different. It's working fine enough for:
- level 1 -> level 2 (drilldown)
- level 2 -> level 3 (drilldown)
but isn't working correctly for:
- level 2 -> level 1 (drillup)
- level 3 -> level 2 (drillup)

#### Live demo with steps to reproduce
v9.2.2: https://jsfiddle.net/BlackLabel/o4qsu76L/
v9.3.0: https://jsfiddle.net/BlackLabel/49rjb08h/

**Comment by TorsteinHonsi** [comment]
With built-in projection we should be able to just zoom in, then add the new series on top of the map. So when drilling from USA to Texas, the main map would first zoom to Texas, then then Texas map would be loaded on top of it. This may be a new implementation of drilldown, but it may also be that it is best to set it up like a separate demo, like lazy-loading of maps.
