### ISSUE TITLE
PPO - Percentage Price Oscillator show Signal Line and PPO Histogram

### ISSUE THREAD

**Issue by dangthinh104** [highcharts/highcharts#16605]
Dear All

I am begin in HighChart, I wanna show signal line and Histogram in chart with PPO
 - My expect such as picture below

![2021-11-07 21_07_00-PPO - Percentage Price Oscillator Chart](https://user-images.githubusercontent.com/33454713/140649389-cd909092-54e5-4b59-b712-b54bbf221ded.png)

- My code: https://jsfiddle.net/dangthinh104/yoh897vd/8/
Thank you for help me.

@TorsteinHonsi

**Comment by raf18seb** [comment]
Hi @dangthinh104, thanks for choosing Highcharts!

GitHub is our bugs/features tracker only, but it seems you have a standard support question, so could you contact us on one of our dedicated support channels?
More info: https://www.highcharts.com/blog/support/

Thanks in advance!

**Comment by dangthinh104** [comment]
Thank you @raf18seb 
I also make question on https://www.highcharts.com/forum/viewtopic.php?f=12&t=47690

But not answer
Regards

**Comment by raf18seb** [comment]
@dangthinh104 you'll get the answer within 24h (today), it's early morning in Europe :)

**Comment by raf18seb** [comment]
@dangthinh104 you'll get the answer within 24h (today), it's early morning in Europe ;)

**Comment by dangthinh104** [comment]
@raf18seb So many thank you if have a solution for us
