### ISSUE TITLE
Date parsing inconsistency with Chrome

### ISSUE THREAD

**Issue by kluvin** [highcharts/highcharts#16610]
With periodical data of the format "dd/mm/yyyy", Chrome does not always infer the proper date format, whereas other browsers work fine.  If one removes the first row (i.e "01.11.1980,7") the dates does parse correctly.

#### Expected behavior
The date format is parsed as "dd/mm/yyyy"

#### Actual behavior
The date format is parsed as "mm/dd/yyyy"

#### Live demo with steps to reproduce
https://jsfiddle.net/76yzb3x0/

#### Product version
Highcharts 9.3.1

#### Affected browser(s)
Google Chrome 95(.0.4638.69) and similar Chrome based browsers

**Comment by raf18seb** [comment]
Hi @kluvin, thanks for creating the ticket.

What do you mean by saying "other browsers work fine"?
Edge behaves the same as Chrome. Firefox is not able to parse `dd/mm/yyyy` date because this format doesn't match [specification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#date_time_string_format).

Highcharts parses `mm/dd/yyyy` date into `mm-dd-yyyy` format.
Please, test what values are returned in the console in both Firefox and Chrome for:
`Date.parse("01-12-1980")`
`Date.parse("12-01-1980")`

**Comment by kluvin** [comment]
Hi @raf18seb 

By affected browsers I mean Chromium (or V8) derivatives, and by other browsers I mean JavaScriptCore and Spidermonkey derivatives.

The parses the data as desired in "dd/mm/yyyy" format, this behavior is inconsistent, and Chromium is acting up. Precisely, Chromium marks 12 successive days in January, whereas other browsers marks one day for each of the 12 months.

Chrome yields:

```js
Date.parse("01-12-1980") // 316479600000
Date.parse("12-01-1980") // 344473200000
```

Firefox yields `NaN` for both.

**Comment by raf18seb** [comment]
@kluvin
Not sure whether I understood you well (correct me if I'm wrong), but yes, Firefox returns wrong values so it's Firefox's fault (not Highcharts').
By the `Date.parse()` documentation, you should provide the data in a format that works in all browsers.

**Comment by kluvin** [comment]
@raf18seb 
Firefox would parse correctly if the parsed date is either `YYYY-MM-DD`, `DD/MM/YYYY` or `MM/DD/YYYY`, as a sidenote.

We would expect the behavior here to be such that two different date-formats can not be interpreted. If Highcharts returned an error that we could yield to our users, since the format is ambiguous, that would be great!

Another very strange behavior experienced with this data is that when excluding the initial value in this data, the dates are suddenly parsed differently on Chrome. If Chrome parsed the dates correctly by the format, I would not expect such a detail to influence the parsing results.

I am not sure what policies Highcharts have on keeping consistent with respect to this, but it is not ideal for us to have charts silently fail to parse dates consistently across browsers.

We are currently using `data.dateFormat` to ensure consistent behavior. If that is the suggested and only solution, then the issue may be closed, though some feedback from Highcharts is still preferable if the date-format is ambiguous.

Have a good weekend (soon)!
~ Martin
