### ISSUE TITLE
to configure  yAxis of tickAmount incompatible

### ISSUE THREAD

**Issue by mydb666** [highcharts/highcharts#16615]
natural      tickAmount ：5
![image](https://user-images.githubusercontent.com/76982510/140882905-c0746d42-3cdc-44c2-991a-7a833b8ee97d.png)

error    tickAmount ：10
![image](https://user-images.githubusercontent.com/76982510/140883134-a691777c-1169-4c18-97b2-bfbd2e0c2c6d.png)

expect  The line of the y-axis should be longer and not flush

**Comment by raf18seb** [comment]
Hi @mydb666, thanks for using Highcharts!

GitHub is our bugs and features tracker only and it seems like you have a support question. Could you contact us on one of our dedicated support channels? Thanks in advance!
More info: https://www.highcharts.com/blog/support/
