### ISSUE TITLE
yAxis labels cut off if custom font family applied.

### ISSUE THREAD

**Issue by huangbinjie** [highcharts/highcharts#16628]
#### Expected behaviour

yAxis labels don't be cut off

#### Actual behaviour

yAxis labels cut off about 2px, if you delete the font-family line, it will be ok.

#### Live demo with steps to reproduce

https://jsfiddle.net/corol_666/qo57fnLw/12/

#### Product version

latest

#### Affected browser(s)

chrome

**Comment by raf18seb** [comment]
Hi @huangbinjie, thanks for creating the ticket!

What browser are you using? Could you provide some screenshots showing the issue?

It looks fine for me on both newest Chrome (v96.0.4664.45) and Firefox (94.0.1), Windows 10
With font:
![image](https://user-images.githubusercontent.com/23310742/142005234-0df113a5-53aa-4e89-b335-481038edd0bb.png)


Without font: 
![image](https://user-images.githubusercontent.com/23310742/142005308-3031f633-22f4-4063-ad62-9ecaa0fefea9.png)

**Comment by huangbinjie** [comment]
@raf18seb hi, thanks for your response. You can reproduce my case on a computer of PingFang SC font.

With font:
![image](https://user-images.githubusercontent.com/7148809/142122005-f185406d-d0ba-406d-9a0a-50d8c8d199ee.png)

Without font:
![image](https://user-images.githubusercontent.com/7148809/142122258-f8a74db8-0a73-4cf4-a699-943b500b5dce.png)

**Comment by raf18seb** [comment]
@huangbinjie could you provide a demo (online or local) with the font applied? I'm not able to reproduce the issue.
This is one of the ways of applying a custom font: https://jsfiddle.net/BlackLabel/my5zfjga/

**Comment by huangbinjie** [comment]
@raf18seb I'm also not able to reproduce it on windows. I found a weird behavior, that is calling `this.label.getBBox().width` and `this.label.element.getBBox().width` during event `afterGetLabelPosition`, the second one is not the same as the first.
So, I can fix it by:

```
Highcharts.addEvent(Highcharts.Tick, 'afterGetLabelPosition', function(e) {
  e.pos.x += this.label.element.getBBox().width - this.label.getBBox().width
})
```

Is it a normal way to workaround?

**Comment by KacperMadej** [comment]
A standard solution for dynamically loaded font family is to either wait with creating a chart for the font to be loaded or update the chart with the new font-family option after the font is loaded. This is a normal situation when not all required resources are loaded - wait or update when all resources are loaded. If you are loading the font via Google's WebFont the code could look like:

```
WebFont.load({
    google: {
      families: ['Roboto']
    },
    active: function() {
      chart.update({
        chart: {
          style: {
            fontFamily: "Roboto"
          }
        }
      });
    }
  });
```
(the example is for `'Roboto'` font family, but you could change the name to your font, and will work the same)

This is not a bug and if you don't have any further comments or questions I would like to close the issue as resolved.

**Comment by huangbinjie** [comment]
@KacperMadej thanks for your help. This might be a font issue of PingFang, but not a bug. You can close it freely.

**Comment by huangbinjie** [comment]
@KacperMadej hi, could you open my [jsfiddle](https://jsfiddle.net/corol_666/qo57fnLw/12/) on macOS? Which have preinstalled PingFang font, and you may reproduce my issue.

**Comment by KacperMadej** [comment]
The problem seems to be in the font. As a workaround you could set spacigLeft to ~3px - demo: https://jsfiddle.net/BlackLabel/9fdqvmcx/
