### ISSUE TITLE
stackLabels disappear and lose their correct position in the bar graph when enabling scrollablePlotArea with minHeight

### ISSUE THREAD

**Issue by lucas-camara-sysmap** [highcharts/highcharts#16638]
#### Expected behaviour

stackLabels aligned to each bar.

#### Actual behaviour

stackLabels of the first bars are hidden in the html and lose the vertical position reference.

#### Live demo with steps to reproduce

https://jsfiddle.net/u2rpsq6c/1/

#### Product version

Highcharts JS v9.3.0

#### Affected browser(s)

Chrome

**Comment by KacperMadej** [comment]
Hi @lucas-camara-sysmap 

Thank you for reporting the problem.

_Internal note:_
Minima demo: https://jsfiddle.net/BlackLabel/bv6L97nj/

**Comment by pawellysy** [comment]
closing as a duplicate of https://github.com/highcharts/highcharts/issues/12133
