### ISSUE TITLE
How can I improve the performance and speed up my react app with multiple tabs

### ISSUE THREAD

**Issue by samounaz** [highcharts/highcharts#16635]
Hello,
I have a react application with multiple tabs, in each tab we can add one or multiple highcharts. Once we reach the third tab, the application becomes very slow, took more than 15 seconds to do actions like adding new tab, deleting tab, adding or removing highcharts. I'm already using react functions in purpose of optimisation like memo, useMemo, useCallback, ... 

So I'm wondering if there is a way to configure or optimise the highcharts in order to not slow down my react app. Because, I noticed that the more I add new tabs and especially highcharts in each tab, the more the application becomes slower.

**Comment by KacperMadej** [comment]
For technical support please see https://www.highcharts.com/blog/support/
