### ISSUE TITLE
Gantt, multiple series with axis grid categories, is not displaying the categories at all.

### ISSUE THREAD

**Issue by dragoshzava** [highcharts/highcharts#16637]
#### Expected behaviour
To have names correctly displayed either by using formatter, or format, despite how many series the chart has.

#### Actual behaviour
Does not displays names when using grid.categories.

#### Live demo with steps to reproduce
https://jsfiddle.net/Resems/7wkL31d0/1/

#### Screenshot
![image](https://user-images.githubusercontent.com/3819194/141297934-9cf41714-3a75-4895-b5b3-424994358b5c.png)

#### Product version
9.3.0

#### Affected browser(s)
N/A

**Comment by KacperMadej** [comment]
Hi @dragoshzava ,

Thank you for reporting the problem.

Only the first series is used to add `point` reference to the formatter function context (or the first argument of that function - both are the same object).

_Internal note:_
Hardcoded series[0] in `Core/Axis/GridAxis.ts`'s `onTickLabelFormat` (1162):
https://github.com/highcharts/highcharts/blob/d29fd2a95ed8e14d8a21fc28d8808c27885919d8/ts/Core/Axis/GridAxis.ts#L1150-L1186
