### ISSUE TITLE
Question: different cursor style for each pie segment 

### ISSUE THREAD

**Issue by heivo** [highcharts/highcharts#16645]
Hi, I want to render a pie chart where only certain pie segments have a pointer cursor. Is this possible without using styled mode?

Thanks in advance!

**Comment by KacperMadej** [comment]
Hi @heivo 

For other communication that bug reporting and feature request please contact technical support with a live demo of the chart you already have or with the code that you have already tried - https://www.highcharts.com/blog/support/
