### ISSUE TITLE
Gantt, yAxis categories, with labels width, don't stick to the set width.

### ISSUE THREAD

**Issue by dragoshzava** [highcharts/highcharts#16649]
#### Expected behaviour
Categories should stick to the set width, despite label length.
Categories should stick to the set width on scroll as well.
Layout shifting should not happen during scroll, if the width is set.

#### Actual behaviour
In case the label is bigger, the style width gets applied.
In case the label is smaller, the width of the category/axis gets smaller until it fits the label.
In case of scroll, the width is variable.

#### Live demo with steps to reproduce
https://jsfiddle.net/Resems/pha4sekj/ - categories with width
https://jsfiddle.net/Resems/vgoq834z/ - scrolling with set label width

#### Product version
9.3.0+

#### Affected browser(s)
N/A

**Comment by KacperMadej** [comment]
Hi @dragoshzava 

Thank you for reporting the problem.
