### ISSUE TITLE
Not exporting custom svg icons from fairsharing.org server

### ISSUE THREAD

**Issue by hoseinmirian** [highcharts/highcharts#16659]
#### Expected behaviour
export svg icon markers from https://beta.fairsharing.org/assets/records/reporting_guideline.svg

#### Actual behaviour
highcart shows them in the graph but when exporting them, it does not export them correctly and export question mark instead of the actual icons. 
following thread we discussed with your technical team link:
https://www.highcharts.com/forum/viewtopic.php?f=9&t=47527&p=171944#p171944

#### Live demo with steps to reproduce

https://codesandbox.io/s/highcharts-vue-demo-forked-hmz2r?file=/src/components/Chart.vue:3238-3334

#### Product version

    "highcharts": "9.0.1",
    "highcharts-vue": "1.3.5",

#### Affected browser(s)
In Safari only it export the graph so please use that to check export problem. 
In firefox and chrome does not export but it loads the icon in the page.

**Comment by hoseinmirian** [comment]
also this is the Nginx config in our server:
server {
  listen 443 ssl http2;
  server_name beta.fairsharing.org;

  ssl_certificate /etc/ssl/fairsharing/fullchain.pem;
  ssl_certificate_key /etc/ssl/fairsharing/privkey.pem;

  charset utf-8;
  root    /var/www/fairsharing/dist;
  index   index.html;
  # The application is running in history mode...
  location / {
      root /var/www/fairsharing/dist;
      try_files $uri $uri/ /index.html;
  }
  error_log  /var/log/nginx/fairsharing-error.log;
  access_log /var/log/nginx/fairsharing-access.log;
}

**Comment by raf18seb** [comment]
Hi @hoseinmirian, thank you for creating the ticket.

It seems like a server configuration problem. The exporting is working fine with svg icon from a different server: https://jsfiddle.net/BlackLabel/pynth07o
![chart (53)](https://user-images.githubusercontent.com/23310742/142620556-546a9808-c218-4e3d-91e4-11c7955e5d8f.png)
/

**Comment by hoseinmirian** [comment]
"Do you have any idea as to what sort of configuration problem that might be? We are not aware of any, and can load images without issue from that server (e.g. https://beta.fairsharing.org/assets/records/db-icon.svg)."
