### ISSUE TITLE
A word p is missing in the document。

### ISSUE THREAD

**Issue by qxdcxy** [highcharts/highcharts#16652]
#### Expected behaviour
plotOptions.pie.depth: // 定义 3D 饼图的厚度
![1871636975041_ pic_hd](https://user-images.githubusercontent.com/49777418/141773033-7aef6e4c-3027-45c4-bde8-3bf09a770163.jpg)

https://www.highcharts.com.cn/docs/basic-3d-charts

#### Actual behaviour
lotOptions.pie.depth: // 定义 3D 饼图的厚度

**Comment by KacperMadej** [comment]
Hi @qxdcxy 

Thank you for reporting the problem.

In the Highcharts docs this shows correctly - https://www.highcharts.com/docs/chart-concepts/3d-charts#3d-pie

There is an issue with the website you have linked and that website is not managed through this github - please contact the website maintainers.
