### ISSUE TITLE
vulnerability issue reported in snyk scan

### ISSUE THREAD

**Issue by nambianandu** [highcharts/highcharts#16650]
Hi Team, 
Any plan to release a fix for the vulnerability reported in snyk scan for version 8.2.2.
https://snyk.io/test/npm/highcharts/8.2.2

#### Product version
8.2.2

**Comment by KacperMadej** [comment]
Hi @nambianandu 

No, no plans for v8 update - this was fixed in v9.0.0.
Remediation: Upgrade to highcharts@9.0.0.

More info and details: https://github.com/highcharts/highcharts/security/advisories/GHSA-8j65-4pcq-xq95
