### ISSUE TITLE
Support Trusted Types

### ISSUE THREAD

**Issue by ecktom** [highcharts/highcharts#16667]
#### Expected behaviour
Enabling [Trusted Types](https://web.dev/trusted-types/) should work without issues

#### Actual behaviour
When [Trusted Types](https://web.dev/trusted-types/) is enabled on a website, following lines causes Trusted Types violation due to string assignment to a dangerous sink (`DOMParser().parseFromString`).

`This document requires ‘TrustedHTML’ assignment` error is thrown due to https://github.com/highcharts/highcharts/blob/master/ts/Core/Renderer/HTML/AST.ts#L44

This could be prevented by changing those lines to something like (untested):
```
if (window.trustedTypes) {
  let staticPolicy = window.trustedTypes.createPolicy("highcharts", { createHTML: (input) => input }, true);
  return Boolean(new DOMParser().parseFromString(staticPolicy.createHTML(''), 'text/html'));
} else {
  return Boolean(new DOMParser().parseFromString('', 'text/html'));
}
```

Note:
Any input other than `''` should be sanitized like `createHTML: (input) => DOMPurify.sanitize(input)`

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! I'll look into this tomorrow.
