### ISSUE TITLE
Categories on column chart aren't updating correctly after scrolling

### ISSUE THREAD

**Issue by sunnySinghD** [highcharts/highcharts#16661]
#### Expected behaviour
If we update the chart and reduce the number of categories and data, the chart should redraw and only display those categories.

#### Actual behaviour
The chart is updated correctly if we don't click the scrollbar. If we scroll, the number of categories does not change correctly and the labels are replaced with numbers. 

If we had ten categories and reduce the options down to two, there will still be ten columns. be eight categories 

#### Live demo with steps to reproduce
[demo here](https://jsfiddle.net/ssinghdaha/f6o8gtke)
The data is updated after a few seconds, click the scrollbar before it updates to recreate the issue.
If you click the scrollbar before it changes you should see it updates incorrectly (chart continues to display original number of columns with numbers for labels).
If you don't click the scrollbar before it changes you should see it work correctly (chart is updated to display three columns).

#### Product version

Highstock JS v9.3.1 (2021-11-05)

#### Affected browser(s)
Tested on firefox, chrome

**Comment by raf18seb** [comment]
Hi @sunnySinghD! Thanks for creating the ticket.

This is correct behavior. What the scrollbar is actually doing, when you click it and move, is setting the xAxis' extremes. When you click it, it sets the `xAxis.min` to 0 and `xAxis.max` to 15.
Then, you are updating the chart, but the current extremes stay. You have only 3 categories defined, so all other labels are numbers. Everything is working as expected.

This can be reproduced without scrollbar by setting min and max: https://jsfiddle.net/BlackLabel/2cwg0obr/

To reset the extremes when updating, set them to `null`: https://jsfiddle.net/BlackLabel/74pLrf6o/

Closing as resolved.

**Comment by raf18seb** [comment]
@sunnySinghD,

sorry, my bad. I was very close, except the scrollbar doesn't set `xAxis.min` and `xAxis.max` on options, but scrollbar fires `xAxis.setExtremes(min, max)` and the values are set on `xAxis.userMin` and `xAxis.userMax`.

So clearing `userMin` and `userMax` will work with a scrollbar: https://jsfiddle.net/BlackLabel/y96ugze4/

**Comment by sunnySinghD** [comment]
Sorry for the delayed response, but this addressed my issue. Thanks for your help.
