### ISSUE TITLE
Stock chart with GUI (indicators) cannot compatible with rangeSelector datagrouping

### ISSUE THREAD

**Issue by finlabhk** [highcharts/highcharts#16670]
I am newbie in using HighStocks and Javascript. I am not sure whether it is actually a bug. What I actually do is copy the example of "Stock chart with GUI" and add a rangeSelector datagrouping function for grouping daily data into weekly and monthly data.

#### Expected behaviour

The indicators will be recalculated if the data type is changed. For example, if the data is on daily basis, the indicator should use the daily data for calculation. After the data is changed into monthly basis, the indicator should be recalculated based on monthly data.

#### Actual behaviour
Some indicators, such as ema, can function as expected.
But some indicators, such as sma, bb, cannot function well. For example, SMA on daily data is used. If I change to weekly data by clicking "week" button, all curves are missing. Only the sma is shown if I click the "week" button again. The original price data is missing.

#### Live demo with steps to reproduce
https://jsfiddle.net/xmtjqLvw/

#### Product version

Highcharts Stock v9.3.1 (should be)

#### Affected browser(s)
Chrome 94

**Comment by raf18seb** [comment]
Hi @finlabhk, thank you for reporting the issue. Seems like a bug.

**Comment by pawelfus** [comment]
**Workaround:**

Demo: https://jsfiddle.net/BlackLabel/b4ph8g2L/

Plugin:
```js
(function(H) {
  H.wrap(
    H.seriesTypes.sma.prototype,
    'recalculateValues',
    function(proceed, ...args) {

      if (this.linkedParent && this.linkedParent.options) {
        proceed.apply(this, args);
      }
    }
  );
})(Highcharts);
```

*Internal note:*
Most likely it's a regression. Recently we have changed the event to recalculate indicator on `afterLinkSeries` event. `series.update()` fires this event before series init (so there's no access to properties like `xData` etc).
