### ISSUE TITLE
NavigationBindings: Cannot create a custom button

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#16675]
#### Expected behaviour
When creating the button as SVG shape it should work normally. 

#### Actual behaviour
There is an error, which is called by `bindings.button.className.indexOf('highcharts-disabled-btn') === -1`

#### Live demo with steps to reproduce

https://jsfiddle.net/BlackLabel/by126xor/
Click on the button next to the exporting button

#### Product version
v9.3.1

#### Affected browser(s)
all

**Comment by pawellysy** [comment]
Hi @OldBuddy, currently we didn't schedule any work for that yet.
We also didn't find any workaround yet. We will move this feature to the inbox. Thanks!

**Comment by OldBuddy** [comment]
@pawellysy can I submit PR?

**Comment by pawellysy** [comment]
@OldBuddy Sure, go for it!
