### ISSUE TITLE
yAxis.maxPadding wrong default value (API)

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#16672]
The API says that the default `yAxis.maxPadding` value is `0.01`, but it's `0.05`.
https://api.highcharts.com/highcharts/yAxis.maxPadding

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/u73qyw65/

#### Product version
Highcharts 9.3.1

**Comment by bre1470** [comment]
Thanks! It has eventually been fixed.
