### ISSUE TITLE
Regression: Highcharts consumes user styles on lists

### ISSUE THREAD

**Issue by kluvin** [highcharts/highcharts#16679]
Highcharts attaches bullet points to `ul` -- find `div.highcharts-a11y-proxy-group:nth-child(2) > ul:nth-child(1)`. The accessibility module in particular introduced the regression.

#### Expected behaviour
No bullet points. Downgrade to 9.1.2 to see this effect.

#### Actual behaviour
Bullet points.

#### Live demo with steps to reproduce
https://jsfiddle.net/kluvin/drowq61L/5/

#### Product version
Highcharts 9.2.0 -> Current

#### Affected browser(s)
Chrome, Firefox

**Comment by oysteinmoseng** [comment]
Thanks Martin for the report! Fixed, and should be part of the next official release.

Temporary workaround could be to set the following in your CSS:
```css
.highcharts-a11y-proxy-group li {
  list-style: none;
}
```
