### ISSUE TITLE
Points are visible outside of plotArea range in polar charts

### ISSUE THREAD

**Issue by m-h-b-tu** [highcharts/highcharts#16671]
This is similar to the closed issue #7381 but for polar charts.

### Expected behaviour
Points shouldn't be rendered, when their x,y values aren't included in the actual ranges of axes. If using column type, visible columns shouldn't be covered.

#### Actual behaviour
Points are visible, even if their values don't belong to the axes ranges. If using column type, visible columns are covered by columns outside the range.

#### Live demo with steps to reproduce
https://jsfiddle.net/z2Lxdno0/

#### Affected browser(s)
All browsers

**Comment by raf18seb** [comment]
Hi @m-h-b-tu, thank you for reporting the issue.

`Internal note:`
Demo showing the line and column versions: https://jsfiddle.net/BlackLabel/60pmLkgy/
v9.3.1 (and earlier)
