### ISSUE TITLE
Legend in Highchart is splitted in 2 rows

### ISSUE THREAD

**Issue by amparorll** [highcharts/highcharts#16705]
#### Expected behaviour
Have legend in only 1 row

#### Actual behaviour
It's spliting the legend in 2 rows.
I have a Pie Chart, and the thing is that the legend text is composed by the name of the serie + the numeric value
I want align the name to the left and the numeric value to the right
something like that
* Property                                     24.4%
* Historical Values                         1.8%
* Whatever 1.7%

What I want is align the numeric values in the right, that's why I've tried to do it with columns, but I'm new with the highchart and I don't get the expected result...
If someone could help me I would appreciate it

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/legend/labelformatter/

**Comment by raf18seb** [comment]
Hi @amparorll!

GH is our bugs/features tracker only. With any support questions, please contact us on our other dedicated support channels.
More info: https://www.highcharts.com/blog/support/
Thank you in advance!
