### ISSUE TITLE
Sankey/Dependency Wheel: unselect event not triggered for Node on click.

### ISSUE THREAD

**Issue by tanmayshah95** [highcharts/highcharts#16718]
#### Expected behaviour
Only one Node/point should be shown as selected at a time. When next node/point is selected, unselect event should be triggered for previously selected node. Behavior should be similar to link selection.

#### Actual behaviour
Node stay selected even when other nodes are clicked. Unselect event is not triggered for previously selected node. This behavior works properly for links. Also selected flag is false and point is not returned in getSelectedPoints() after selection.

#### Live demo with steps to reproduce
https://jsfiddle.net/tanmayshah95/czb5pj9k/
- Added unselect event, which is only triggered for links. 
- Get selected Points button added to get no. of selected points, returns 0 for multiple nodes selection.

#### Product version
latest version

#### Affected browser(s)
Chrome, Edge

**Comment by raf18seb** [comment]
Hi @tanmayshah95, thank you for reporting the issue.

`internal note:`
The `chart.getSelectedPoints` method returns points only (without nodes). Not sure whether it's intended.

Workaround: https://jsfiddle.net/BlackLabel/hbL9km51/
Workaround snippet:
```js
(function(H) {
  H.Series.prototype.getPointsCollection = function() {
    const allNodes = [];

    this.nodeColumns.forEach(nodeColumn => {
      nodeColumn.forEach(node => {
        allNodes.push(node);
      });
    });

    return ((this.hasGroupedData ? this.points : this.data) || []).concat(allNodes);
  };
})(Highcharts)
```
