### ISSUE TITLE
geojson chart not rendering in 9.3.2

### ISSUE THREAD

**Issue by smorovic** [highcharts/highcharts#16725]
#### Expected behaviour
Geojson polygon and chart axes are visible. Legend is shown.
Happened with any geojson tried so far.

#### Actual behaviour
Polygon and chart axes are blank. Only legend is shown.

#### Live demo with steps to reproduce

demo example showing geojson (highcharts / highmaps 9.2.2)
https://codepen.io/smorovic/pen/vYeYqVj

Broken instance with highcharts 9.3.2
https://codepen.io/smorovic/pen/YzrzmBo

JS and HTML are identical, the only difference is highmaps version imported in settings

#### Product version
Highcharts (Highmaps) 9.3.2
Same issue is present from 9.3.0

#### Affected browser(s)
Tested in Chrome (Version 96.0.4664.45 (Official Build) (64-bit)) and Seamonkey (2.53.10).
Does not seem to be browser specific.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting and sorry for the late reply!

Due to the refactoring in Highcharts Maps, maps no longer use axes, and in order to use map geometries, you must use the `mapChart` factory:

```js
Highcharts.mapChart('geojsonChart', options);
```

**Comment by smorovic** [comment]
Thanks, indeed that works!
