### ISSUE TITLE
Totals label missing when a group of series is merged

### ISSUE THREAD

**Issue by gretacodes** [highcharts/highcharts#16738]
#### Expected behaviour
We have a Chart A (Stacked Bar Char) and Chart B (Area Chart) and we have a functionality that merges these two charts together. Chart A has a label which shows the totals for the column, while Chart B has no totals applied to it. When we merge these 2 charts together, the end result is a chart which has no total value label displayed due to the totals value being a global setting. 

We want to have an ability to show a total value label for the merged chart if one of the children charts (i.e Chart A) has a totals label applied to it. 
Total values is a global setting but we want totals for one group of series to be shown. 

#### Actual behaviour
No totals are shown when Chart A and Chart B are merged in together.

Can you please advise us on the best way to achieve this? 

#### Product Version
highcharts-9.1.2

**Comment by raf18seb** [comment]
Hi @gretacodes, thank you for creating a ticket!

If you think this is a Highcharts core bug, then could you please reproduce it in a live demo? jsFiddle would be perfect.

If this is a support question, then please contact us on our dedicated support channels (GitHub is our bugs/features tracker only).
More info: https://www.highcharts.com/blog/support/
Thanks!

**Comment by gretacodes** [comment]
Hello, I have managed to find a solution to fix this issue! Thanks
