### ISSUE TITLE
Zooming in bubble charts

### ISSUE THREAD

**Issue by iacii** [highcharts/highcharts#1673]
Zooming a small region of a bubble chart results in the y-axis disappearing along with the bubbles.

This can be seen in the Highcharts example: http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/bubble/
Zooming in on the cluster of five bubbles in the top left corner of the chart should reproduce the error.

**Comment by harfyt** [comment]
Hello.
Another issue in the same concept is that zooming in an area that includes a part of a bubble but not its center makes the bubble disappear. 
It can be reproduced in the above jsfiddle of @iacii 
![image](https://user-images.githubusercontent.com/2162094/49439379-86fcc600-f7c9-11e8-84e8-6c9e63ddf103.png)

**Comment by pawelfus** [comment]
Hi @harfyt 

Thanks for reporting the issue! I'm not convinced if it's a bug. When you zoom, you zoom on xAxis and yAxis. For example, in your screenshot you zoom xAxis in range <~66, ~69>. Bubble has radius (in pixels) around 28pixels. When you zoom in that range, bubble is outside the zoomed range. See attached screenshot:

![screen shot 2018-12-05 at 12 39 29](https://user-images.githubusercontent.com/1453926/49511230-dce57280-f88a-11e8-9245-9a9866d7ec8e.png)

**Comment by harfyt** [comment]
Hi @pawelfus.

Thanks for answering.

So, if I get it right, the zoomed area is correct, but then why the radius of the bubble is changing?
Is that something should be happening by design? And if so, is there an option to stop shrinking bubbles on zoom in?

**Comment by pawelfus** [comment]
@harfyt - bubble size is the same:

![screen shot 2018-12-06 at 12 49 25](https://user-images.githubusercontent.com/1453926/49583520-c86fab80-f958-11e8-8c88-544d5526e288.png)

Radius of the bubble doesn't have any connection with x/y extremes. It has separate options, for example:

- [`maxSize`](https://api.highcharts.com/highcharts/series.bubble.maxSize)
- [`minSize`](https://api.highcharts.com/highcharts/series.bubble.minSize)
- [`sizeBy`](https://api.highcharts.com/highcharts/series.bubble.sizeBy)
- [`sizeByAbsoluteValue`](https://api.highcharts.com/highcharts/series.bubble.sizeByAbsoluteValue)
- [`zMin`](https://api.highcharts.com/highcharts/series.bubble.zMin)
- [`zMax`](https://api.highcharts.com/highcharts/series.bubble.zMax)

As far as I understand you, you expect to see part of the a big bubble after zooming, which is not the case for `bubble` series. See similar issue #9527 - and let me know if I miss something.

**Comment by harfyt** [comment]
> As far as I understand you, you expect to see part of the a big bubble after zooming, which is not the case for bubble series. 
Thank you,  this is exactly my point. 
I'll try to play with the options associated with bubble size.
