### ISSUE TITLE
Columns are misaligned when multiple x axes.

### ISSUE THREAD

**Issue by bm64** [highcharts/highcharts#16747]
#### Expected behaviour
Columns should be aligned correctly with multiple x axes.

#### Actual behaviour
Columns are misaligned when chart config includes multiple x axes.
Most likely related to #15503.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/hfgbcs7n/

#### Product version
Highcharts 9.3.2

#### Affected browser(s)
N/A

#### Workarounds 
1. Disable grouping https://jsfiddle.net/BlackLabel/kh3892ao/
2. For charts where grouping is required, declare new series type https://jsfiddle.net/BlackLabel/9ngwv0x8/

**Comment by rishi416** [comment]
Hi, 
 
What's the ETA for fix of this issue? I need the fix as this is affecting another chart.

In https://jsfiddle.net/rishi416/c1a5mt7f/29/ , I've used the workaround. I need to show the totals of each stack on top using stackLabels option for y axis. It's working for the first group of categories with xAxis: 0, but not for other groups xAxis - 1/2. If I remove the workaround and use type 'column" for all series', then the stack sums are visible but they're not aligned and all appear on top of first xAxis category group . Fiddle without workaround https://jsfiddle.net/rishi416/c1a5mt7f/34/ .

It appears stackLabels prop is tied with the chart type and its being affected by this issue.

**Comment by raf18seb** [comment]
Hi @rishi416, unfortunately, we don't have ETA for this fix yet. I'll investigate further and provide more information soon.

**Comment by raf18seb** [comment]
@rishi416, thank you for your patience.
When it comes to the issue with stackLabels not respecting the `xAxis.left`, here is a workaround: https://jsfiddle.net/BlackLabel/n4gf8vjo/ (I disabled dataLabels to clearly see stackLabels).

I reported a stackLabels placement bug in a separate ticket: https://github.com/highcharts/highcharts/issues/16764


https://github.com/highcharts/highcharts/issues/16764
