### ISSUE TITLE
Corrupted text rendering on axis 

### ISSUE THREAD

**Issue by MiroLiska** [highcharts/highcharts#16740]
#### Expected behaviour
The axis text should be always rendered properly.

#### Actual behaviour
The axis text is sometimes rendered improperly. This occurs when the chart container has a specific exact size.

#### Live demo with steps to reproduce
see at http://jsfiddle.net/u1g2pqc3 
![image](https://user-images.githubusercontent.com/23024867/144393931-1e9a2549-6f61-4a53-9933-3aee451f5401.png)

when the chart is just one pixel higher (or even lower!), then is the axis label rendered properly:
![image](https://user-images.githubusercontent.com/23024867/144394164-7f1bd66d-21ae-4232-bdd7-ec28a44d3b1e.png)

#### Product version
Reproduced with 8.0.4 and the version currently available on code.highcharts.com

#### Affected browser(s)
Edge, Chrome and Firefox, all on Windows 10

**Comment by KacperMadej** [comment]
Hi @MiroLiska 

This looks like a font rendering issue and it could be recreated without Highcharts - in an SVG with rotated text.
Demo: http://jsfiddle.net/BlackLabel/rp43m1wf/
![image](https://user-images.githubusercontent.com/8960408/145011587-c218073d-da95-478b-8528-8a059574a429.png)

`font-size:12px` looks good, so this could be used as a workaround. Demo: http://jsfiddle.net/BlackLabel/rp43m1wf/2/

IMO this doesn't look like something that we could (and should) fix.
@MiroLiska - have you reported this problem as a general issue to the authors of the browsers? Could we close this issue? Do you have any comments?

**Comment by MiroLiska** [comment]
Hello Kacper

Indeed, you are right, it is some SVG drawing glitch. Do you have any idea where to report such an issue?
You can close this issue, of course, this is definitively not a HighCharts problem.

Best regards

Miro

**Comment by KacperMadej** [comment]
For Chromium (should cover Chrome and Edge): https://bugs.chromium.org/p/chromium/issues/list
For Firefox: https://bugzilla.mozilla.org/home

I am closing the issue but if you have any more comments or questions please let us know.
