### ISSUE TITLE
Annotation doesn't trigger showPopup event when labelOptions.useHTML set to true

### ISSUE THREAD

**Issue by bm64** [highcharts/highcharts#16744]
#### Expected behaviour
Click on fibonacci annotation should trigger showPopup event when `labelOptions.useHTML` is set to `true`.

#### Actual behaviour
Click on fibonacci annotation doesn't trigger showPopup event when `labelOptions.useHTML` is `true`.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/ywbvkqau/
Steps:
- set `useHTML` value to true
- click on fibonacci annotation

#### Product version
- Highcharts 9.3.2
- Worked fine in Highcharts 8.0.4
- Broken since 8.1.0 most likely by #13109

**Comment by raf18seb** [comment]
Hi @bm64, thanks for reporting!

`Internal note:`
It's working fine when clicking on text elements (event is added on texts`:
https://github.com/highcharts/highcharts/blob/cf81cfa7f16e08bd6c3f2663509bc7b1eb91fde6/ts/Extensions/Annotations/Mixins/EventEmitterMixin.ts#L116-L123
