### ISSUE TITLE
candlestick is blurred on edges because of decimals in path

### ISSUE THREAD

**Issue by anoosurf** [highcharts/highcharts#16775]
#### Expected behaviour
the candlesticks are blurred on edges because highcharts is generating the rectangle as a 'path' along with decimals .. whereas in columns it is very crisp because it uses SVG 'rect'. 

#### Actual behaviour
to have crispness the candlesticks body needs to be generated via SVG rect
![image](https://user-images.githubusercontent.com/4696146/145510522-315fa177-662c-4b00-85a7-431098981078.png)

#### Live demo with steps to reproduce
take any of your candlestick chart demos

#### Product version
9.3.2

**Comment by raf18seb** [comment]
Hi @anoosurf,

The candlestick is not really a rect, but it has additional lines.
You can also use [series.crisp](https://api.highcharts.com/highstock/series.candlestick.crisp)
