### ISSUE TITLE
TopoJSON demo doesn't work

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#16778]
#### Behaviour
Fails for demos like:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/mapview/center-zoom
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/mapview/get-view
(maybe more)

Works on the master branch, so this is already fixed, just waiting for the next release.
Example: https://jsfiddle.net/BlackLabel/6h3t8epk/

(I'm adding this issue in case any similar problems will be reported.)

**Comment by TorsteinHonsi** [comment]
Damn, I didn't think of that... JSFiddle obviously loads from master. We will convert most samples over to TopoJSON over time, so until the feature is official, it would probably be best to create a whole new folder for them in samples. Then after release we just copy all the files over.
