### ISSUE TITLE
Highmaps - `joinBy` is not respected in series update

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#16782]
#### Expected behaviour
Workaround with an empty point on init: https://jsfiddle.net/BlackLabel/j3vb21qm/

#### Actual behaviour
Points are not matched by `hc-key`.

#### Live demo with steps to reproduce
1. Open jsfiddle: https://jsfiddle.net/BlackLabel/j2qrk1pL/
2. Wait one second
3. Check the most right-bottom point - it is Hessen and should be Bayern

#### Product version
Highmaps 9.3

#### Affected browser(s)
All

_Internal note:_
Regression bug since Highmaps 9.3

**Comment by raf18seb** [comment]
`Internal note:`
Works fine with Poland which has the same number of features: https://jsfiddle.net/BlackLabel/dcLr3m26/
It was working fine before 9.3.0 (e.g. 9.2.2), but there was a strange points animation that shouldn't be there. So the case might be that there was something wrong even before 9.3

**Comment by KacperMadej** [comment]
@raf18seb Not really working for PL if the data is not ordered as the map data - https://jsfiddle.net/BlackLabel/dcLr3m26/1/ - switched first 2 points in data and there is a visible switch between Łódzkie and Mazowieckie (pl-ld, pl-mz - in the center).
