### ISSUE TITLE
Annotation line changes its angle when dragging.

### ISSUE THREAD

**Issue by bm64** [highcharts/highcharts#16784]
#### Expected behaviour
Annotation angle should remain the same when dragging.

#### Actual behaviour
Annotation angle changes when dragging.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/o5ewf4cq/1/

1. Drag the annotation.

#### Product version
Highcharts Stock 9.3.2
#### Affected browser(s)
N/A

#### Workaround
Set `xAxis.ordinal` to `false`.

**Comment by magdalena-gut** [comment]
The issue occurs also for the line series while zooming, when `zoomType` set to `xy'` or `x`.  

Demo: https://jsfiddle.net/BlackLabel/nmjspytb/

**Comment by jackytanjq** [comment]
Hello,
Is there any expected timeline to solve this issue?
The ordinal position must be enabled in my application, therefore the workaround could not be used.

I have the same issue but only when the Annotation line is using the `Additions.prototype.getExtendedPositions`.
[https://jsfiddle.net/jackytanjq/8w9g3v7p/1/](https://jsfiddle.net/jackytanjq/8w9g3v7p/1/)

Attached GIF to show the issue:
![Highcharts_InfiniteLine_wFakeData_RightExtreme](https://github.com/highcharts/highcharts/assets/7489622/119f2b82-a683-4804-a8b1-5270e4b5efc0)
![Highcharts_InfiniteLine_wFakeData_LeftExtreme](https://github.com/highcharts/highcharts/assets/7489622/a686207e-36e7-434f-825b-d84fbd0f3dd8)

Kindly assist.
Thank you
