### ISSUE TITLE
negative values missing in logarithmic mode

### ISSUE THREAD

**Issue by yaelx** [highcharts/highcharts#16785]
#### Expected behaviour
show negative values in stacked column chart even in logarithmic scale.
When toggling a series that has y values < 0, log scale hides them. When toggling back to linear scale the hidden points should be visible again.

#### Actual behaviour
negative values disappear when going from linear to logarithmic. in addition when going back to linear the negative value that were seen in linear scale before - disappear and are not part of the chart. 
I have used as part of options.yAxis: 
`      custom: {
        allowNegativeLog: true,
      },` and also tried to set allowNegativeLog: true as separate property in options.yAxis. It was working before several weeks and stopped working suddenly. 

This ticket might be treated as a continuation of #15721.

#### Live demo with steps to reproduce

https://jsfiddle.net/10j7hw8a/2/
Click on the log button to set to log scale, and click again to set to linear - it looks different from original chart in linear scale.

#### Product version
9.3.2

#### Affected browser(s)
all

**Comment by raf18seb** [comment]
Hi @yaelx, thank you for reporting the issue.

Simplified demo: https://jsfiddle.net/BlackLabel/tcaygk5d/
Workaround: when coming back to `linear` yAxis, set [series.threshold](https://api.highcharts.com/highcharts/series.column.threshold) to 0: https://jsfiddle.net/BlackLabel/2dstgnvo/

For using negative logarithm scale, you can use this extension, see demo: https://jsfiddle.net/BlackLabel/z4vut9og/

**Comment by yaelx** [comment]
Thank you, it worked out.

**Comment by raf18seb** [comment]
Let me please reopen this ticket. It's working fine with a workaround, but... it's still just a workaround for a bug that needs to be fixed.
