### ISSUE TITLE
[Highmaps] PDF of exported maps doesn't open in Adobe Reader

### ISSUE THREAD

**Issue by biancacamargomachado** [highcharts/highcharts#16798]
#### Expected behaviour
The PDF should be compatible with Adobe Reader and it should open there as it opens in the browser.

#### Actual behaviour
When using `offlineExport + Highmaps` it shows the following error: 
```
"An error exists on this page. Acrobat may not display the page correctly. Please contact the person who created the PDF document to correct the problem".
```

![image](https://user-images.githubusercontent.com/40609384/146373899-5020827b-fec4-4a32-b488-6bcc62ef9f41.png)

#### Live demo with steps to reproduce
I've found this demo that shows the problem: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/category-map/
(from this similar issue: https://github.com/highcharts/highcharts/issues/9039)

#### Product version

Highcharts:  9.3.2
Highmaps:  9.3.2 

#### Affected browser(s)
Chrome, Firefox, Edge

**Comment by raf18seb** [comment]
Hi @biancacamargomachado!

Let's reopen the old ticket and close this one as a duplicate.
