### ISSUE TITLE
With scrollbar, when you export only content within the visual range, how to solve it?And the tabel content is sometimes not shown

### ISSUE THREAD

**Issue by szwc** [highcharts/highcharts#16795]
#### Expected behaviour

Click on all, hoping to export all the content
#### Actual behaviour
Now export only content within the visual range

**Comment by raf18seb** [comment]
Hi @szwc!

Could you please explain your problem more precisely?
If this is a support nature question, then please contact us on one of ours dedicated support channels: https://www.highcharts.com/blog/support/
GitHub is our bugs/features tracker only.

**Comment by szwc** [comment]
> Hi @szwc!
> 
> Could you please explain your problem more precisely? If this is a support nature question, then please contact us on one of ours dedicated support channels: https://www.highcharts.com/blog/support/ GitHub is our bugs/features tracker only.

**Comment by szwc** [comment]
> Hi @szwc!
> 
> Could you please explain your problem more precisely? If this is a support nature question, then please contact us on one of ours dedicated support channels: https://www.highcharts.com/blog/support/ GitHub is our bugs/features tracker only.

Sorry hi @circleci-mu for not responding to you in time, my code is next,
When scrolling quickly, the left table is incomplete, such as the border is lost,
With the scrollbar added, can the picture contain all the things when it is exported?Currently the exported pictures contain only content within the visual scope.

<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Highcharts Gantt Example</title>

		<style type="text/css">
#container {
    max-width: 1200px;
    min-width: 800px;
    height: 900px;
    margin: 1em auto;
}
.scrolling-container {
	overflow-x: auto;
	-webkit-overflow-scrolling: touch;
}

		</style>
	</head>
	<body>

<script src="https://cdn.highcharts.com.cn/gantt/highcharts-gantt.js"></script>
    <script src="https://cdn.highcharts.com.cn/highcharts/modules/exporting.js"></script>
    <script src="https://cdn.highcharts.com.cn/highstock/modules/stock.js"></script>
    


	<div id="container"></div>




		<script type="text/javascript">
Highcharts.ganttChart('container', {
    exporting: {
        chartOptions: { // specific options for the exported image
            plotOptions: {
                series: {
                    dataLabels: {
                        enabled: true
                    }
                }
            }
        },
        // fallbackToExportServer: false
    },
    chart:{
        // scrollablePlotArea: {
        //     minHeight: 1200,
        //     // minWidth:0,
        //     // scrollPositionX:100,
        //     scrollPositionY:1,
        //     opacity:0.5
        // },
        // marginRight: 0
    },
    title: {
        text: 'Gantt Chart with Highstock Navigation'
    },
    yAxis: {
        // uniqueNames: true,
        type: 'category',


            title: {
                text: null
            },
            min: 0,
            max: 8,
            scrollbar: {
                enabled: true,
                showFull:true
            },
            tickLength: 0,
            visible:true,
            grid: {
            enabled: true,
            // borderColor: 'rgba(0,0,0,0.3)',
            borderColor: 'black',
            borderWidth: 1,
            columns: [{
                title: {
                    text: 'Project'
                },
                labels: {
                    format: '{point.name}'
                }
            }, {
                title: {
                    text: 'Assignee'
                },
                labels: {
                    format: '{point.assignee}'
                }
            },{
                title: {
                    text: 'Est. days'
                },
                labels: {
                    formatter: function () {
                        var point = this.point,
                            days = (1000 * 60 * 60 * 24),
                            number = (point.x2 - point.x) / days;
                        return Math.round(number * 100) / 100;
                    }
                }
            }, {
                labels: {
                    format: '{point.start:%e. %b}'
                },
                title: {
                    text: 'Start date'
                }
            }, {
                title: {
                    text: 'End date'
                },
                offset: 30,
                labels: {
                    format: '{point.end:%e. %b}'
                }
            }]
        }
    },
    xAxis:{
        labels:{
            formatter:function(){
                let date = new Date(this.value)
                let month = date.getMonth()+1
                let day = date.getDate()
                month = month<10?'0'+month:month
                day = day<10?'0'+day:day
                return month+''+day
            },
            // format:'{%m%d}'
        },
        // dateTimeLabelFormat: {
        //     date:"%m%d"
        // }
    },
    navigator: {
        enabled: true,
        series: {
            type: 'gantt',
            pointPlacement: 0.5,
            pointPadding: 0.25
        },
        yAxis: {
            min: 0,
            max: 10,
            reversed: false,
            categories: []
        }
    },
    scrollbar: {
        enabled: true
    },
    rangeSelector: {
        enabled: true,
        selected: 0
    },
    series: [{
        name: 'Project 1',
        data: [{
            start: Date.UTC(2017, 11, 1),
            end: Date.UTC(2018, 1, 2),
            completed: 0.95,
            name: 'Prototyping',
            assignee: 'Richards',
            y:0
        }, {
            start: Date.UTC(2018, 1, 2),
            end: Date.UTC(2018, 11, 5),
            completed: 0.5,
            name: 'Development',
            assignee: 'Richards',
            y:1
        }, {
            start: Date.UTC(2018, 11, 8),
            end: Date.UTC(2018, 11, 9),
            completed: 0.15,
            name: 'Testing',
            assignee: 'Richards',
            y:2
        }, {
            start: Date.UTC(2018, 11, 9),
            end: Date.UTC(2018, 11, 19),
            completed: {
                amount: 0.3,
                fill: '#fa0'
            },
            name: 'Development',
            assignee: 'Richards',
            y:3
        }, {
            start: Date.UTC(2018, 11, 10),
            end: Date.UTC(2018, 11, 23),
            name: 'Testing',
            assignee: 'Richards',
            y:4
        }, {
            start: Date.UTC(2018, 11, 25, 8),
            end: Date.UTC(2018, 11, 25, 16),
            name: 'Release',
            assignee: 'Richards',
            y:5
        },
        {
            start: Date.UTC(2020, 11, 25),
            end: Date.UTC(2020, 11, 30),
            name: 'first',
            assignee: 'sdfsas',
            y:6
        },
        {
            start: Date.UTC(2021, 01, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'second',
            assignee: 'asdfgfgwr',
            y:7
        },
        {
            start: Date.UTC(2021, 01, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'three',
            assignee: 'sssdfasf',
            y:8
        },
        {
            start: Date.UTC(2021, 01, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'four',
            assignee: 'Rihjfdchards',
            y:9
        },
        {
            start: Date.UTC(2021, 01, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'five',
            assignee: 'csesfs',
            y:10
        },
        {
            start: Date.UTC(2021, 01, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'six',
            assignee: 'asdss',
            y:11
        },{
            start: Date.UTC(2021, 01, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'jjojs',
            assignee: 'jjojs',
            y:12
        }
        ,{
            start: Date.UTC(2021, 01, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'dsfsdf',
            assignee: 'dsfsdf',
            y:13
        },{
            start: Date.UTC(2021, 01, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'asdvs',
            assignee: 'asdvs',
            y:14
        },{
            start: Date.UTC(2021, 11, 25),
            end: Date.UTC(2022, 01, 22),
            name: 'abc',
            assignee: 'abc',
            y:15
        },{
            start: Date.UTC(2020, 03, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'cafrrs',
            assignee: 'cafrrs',
            y:16
        },{
            start: Date.UTC(2020, 03, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'cafrrs',
            assignee: 'cafrrs',
            y:17
        },{
            start: Date.UTC(2020, 03, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'cafrrs',
            assignee: 'cafrrs',
            y:18
        },{
            start: Date.UTC(2020, 03, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'cafrrs',
            assignee: 'cafrrs',
            y:19
        },{
            start: Date.UTC(2020, 03, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'cafrrs',
            assignee: 'cafrrs',
            y:20
        },{
            start: Date.UTC(2020, 03, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'cafrrs',
            assignee: 'cafrrs',
            y:21
        },{
            start: Date.UTC(2020, 03, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'cafrrs',
            assignee: 'cafrrs',
            y:22
        },{
            start: Date.UTC(2020, 03, 25),
            end: Date.UTC(2021, 02, 22),
            name: 'cafrrs',
            assignee: 'cafrrs',
            y:23
        }
        ]
    }]
});

		</script>
	</body>
</html>
<img width="960" alt="lost" src="https://user-images.githubusercontent.com/22705781/147549657-906db71c-c580-4699-8698-5e0355da92e3.png">

**Comment by raf18seb** [comment]
Hi @szwc, thank you for providing more info.

To export the whole chart, you can set `yAxis.min` and `yAxis.max` in the exporting options, see demo: https://jsfiddle.net/BlackLabel/e47yp8ch/

When it comes to disappearing borders, I would consider it as a bug.
