### ISSUE TITLE
Border Radius for Radial bar / column Chart

### ISSUE THREAD

**Issue by dhanashrivitara** [highcharts/highcharts#16799]
There should be feature that border radius should be add in Radial Bar/Column Chart , as we can apply it on bar or column chart but not in cicular series 
![image](https://user-images.githubusercontent.com/81235677/146404405-2ea6b61b-1547-4cd9-a4f7-f103b3929e48.png)

as in the image can change the borderwidth and color need to apply border radius.

**Comment by raf18seb** [comment]
Hi @dhanashrivitara, thank you for creating the ticket!

I agree this is not implemented in the `polar` and `inverted` column chart (radial bar), but imho it should be - there's no official info that `borderRadius` doesn't work with a radial chart.
I would consider it as a bug, but I'll leave a `Type: Feature Request` tag too.
