### ISSUE TITLE
Unable to control ONLY legend text color using legend.itemHiddenStyle.color

### ISSUE THREAD

**Issue by longmatthewh** [highcharts/highcharts#16819]
#### Expected behaviour
Not sure if this is a bug or a feature request, but I'd like to be able to utilize `legend.itemHiddenStyle.color` to customize the color of the legend item text ONLY and not both the text and the symbol color. The goal is to be able to create an alternative visual representation of the series hidden state that doesn't include changing the color of either the item text or symbol to grey.

#### Actual behaviour
Say I set the following `itemHiddenStyle`:
```
    legend: {
      itemHiddenStyle:{
      	color:"pink"
      }
    }	
```	
When I click on any of the series in the chat, both the legend item text and symbol color change to pink.

#### Live demo with steps to reproduce
https://jsfiddle.net/longmatthewh/dj5v36rk/5/

#### Product version
Highcharts JS v9.3.2

#### Affected browser(s)
At least Chrome

**Comment by raf18seb** [comment]
Hi @longmatthewh, thanks for creating the ticket!

it's not a bug for sure, it's intended behavior.
It can be easily changed in the core code in the `Highcharts.Legend.prototype.colorizeItem` method, just replace
```js
symbolColor = visible ?
        (item.color || hiddenColor) :
        hiddenColor,
```

with

```js
symbolColor = item.color,
```

Demo: https://jsfiddle.net/BlackLabel/cm3nv4fo/

Of course, if this ticket gets more votes (thumbs up), we will add an option to the API that will allow this without interfering with the core code.

**Comment by longmatthewh** [comment]
Thanks for the reply @raf18seb !
