### ISSUE TITLE
TooltipFormatterContextObject has wrong type for "point"

### ISSUE THREAD

**Issue by willyboy** [highcharts/highcharts#16822]
#### Expected behaviour
The TooltipFormatterContextObject should type the point property as TooltipPositionerPointObject not Point. The plotY and plotX properties are available on TooltipPositionerPointObject but not on Point. plotY and plotX are available when you log this property.

#### Actual behaviour
TooltipFormatterContextObject.point says there's no plotY/X but there is. 

#### Product version

Highcharts 9.3.2
#### Affected browser(s)
N/A

**Comment by raf18seb** [comment]
Hi @willyboy, thank you for reporting a problem.

**Comment by BistroStu** [comment]
The Highcharts exported types are a facade over the top of the actual objects being used which can be cast "as any" many times in their lifetime. Those properties may be present on TooltipFormatterContextObject.point but they are not intended to be used in that context, so I would ignore them. Having "bonus" properties is not ideal but if all of the documented properties are present and correctly typed then I don't think this is an issue.

Here is a demonstration of how the internal types can differ from the published/exported ones:

"ts/core/series/pont.ts" line 1557:
interface Point extends PointLike {
    // merge extensions with point class
}

"ts/series/line/linepoint.d.ts" line 29:
declare module '../../Core/Series/PointLike' {
    interface PointLike {
        category?: string;
        clientX?: number;
        dist?: number;
        distX?: number;
        hasImage?: boolean;
        index: number;
        isInside?: boolean;
        low?: number;
        negative?: boolean;
        options: PointOptions;
        plotX?: number;
        plotY?: number;
        stackTotal?: number;
        stackY?: (number|null);
        yBottom?: number;
        zone?: SeriesZonesOptions;
    }
}

**Comment by bre1470** [comment]
Hi @willyboy,

I am not able to confirm, that it is a `TooltipPositionerPointObject`. `isHeader` property is missing. It is also not clear, why `plotX` and `plotY` are required in a text formatting context, when `x` and `y` are present. Could you please give an example and details about your use case?

Maybe the `Highcharts.TooltipPositionerCallbackFunction` and the `positioner` option fits better your needs.

**Comment by willyboy** [comment]
@bre1470 It looks like we're using plotY/X to add an arrow to a custom tooltip that points to the point the person is hovered over. At the edges of the chart, the position of the tooltip changes and so the position of the arrow within the tooltip needs to change based on where the point is plotted at.
