### ISSUE TITLE
Color coding for markers in timeline charts

### ISSUE THREAD

**Issue by karthikdechiraju-plivo** [highcharts/highcharts#16826]
Currently, in timeline charts, we are able to provide only one color to the marker circles with **fillColor** inside **marker** object. 
`
series: [
            lineColor: "#ffc100",
            marker: {
                symbol: "circle",
                fillColor: "#e97162",
            },
]
`

Currently, it is just taking a string as a value for **fillColor**. If we want to mark the circles with different colors wrt. data, there is no possibility. Can you add this feature that enables assigning different colors to different markers based on data? Please add a scope to give a function that executes for every object of the data array. Something like this

`
series: [
            lineColor: "#ffc100",
            marker: {
                symbol: "circle",
                fillColor: (data) => {
                     // return color codes based on  data 
                },
            },
]
`

**Comment by DJTechnoo** [comment]
Hi, thank you for the feature request!

Here are two workarounds to achieve this
1) Demo using a wrapper: https://jsfiddle.net/BlackLabel/jngbm4wL/ 
2) Demo using the `load()` event: https://jsfiddle.net/BlackLabel/rw7fhdcy/

The options in the `marker` have been extended with `fillColorFun()` which can return colors based on the data.
