### ISSUE TITLE
Organizational - chart need help

### ISSUE THREAD

**Issue by nithin-neewee** [highcharts/highcharts#16829]
How can I add a dropdown value and when the dropdown value is changed the data also should change in the organization chart.

https://codepen.io/mushigh/pen/gJEZxm

please help as the documentation is very difficult in understanding for the first time working in the high chart.

**Comment by raf18seb** [comment]
Hi @nithin-neewee! Thank you for using Highcharts and creating the ticket.

You can find a similar question with a sample answer here on our official Forum: https://www.highcharts.com/forum/viewtopic.php?f=9&t=23981

GitHub is our bugs and features tracker only, so in case of any further questions, please contact us on our dedicated support channels. Thanks for understanding!
More info: https://www.highcharts.com/blog/support/
