### ISSUE TITLE
Typescript: HighCharts.Point doesn't expose shapeArgs

### ISSUE THREAD

**Issue by longmatthewh** [highcharts/highcharts#16824]
#### Expected behaviour
When using Typescript, I should be able to access shapeArgs on a HighCharts.Point object, as follows:
```
const foo = (pointLabel:Highcharts.PointLabelObject): void => {
     const shape = pointLabel.point.shapeArgs;
     //do something cool with shape
}
```

#### Actual behaviour
In order to access shapeArgs on a HighCharts.Point object, I have to cast it as any:
```
const foo = (pointLabel:Highcharts.PointLabelObject): void => {
     const shape = (pointLabel.point as any).shapeArgs;
     //do something cool with shape
}
```

#### Live demo with steps to reproduce
https://jsfiddle.net/longmatthewh/pxstdvz1/7/

#### Product version
Highcharts JS v9.3.2

#### Affected browser(s)
N/A

**Comment by raf18seb** [comment]
Hi @longmatthewh, thanks for reporting the issue!

FYI @bre1470
