### ISSUE TITLE
Need help on the when select from dropdown - change data

### ISSUE THREAD

**Issue by nithin-neewee** [highcharts/highcharts#16828]
html - part

<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/sankey.js"></script>
<script src="https://code.highcharts.com/modules/organization.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js">

</script>
<div id="container"></div>

 <select class="form-control" id="myselectoptions">
        <option value="1">Dat1</option>
        <option value="2">Dat2</option>

    </select>

 
please help when changing the options dropdown - if its Dat1 reflect array_1 value if its Dat2 reflect array_2 value

let array_1 =   [
        ["Director", "SPDS"],
         ["Director", "TC10"],
          ["Director", "TC9"],
         ["Director", "TC7"],
        ["Director", "ESU"],
        ["Director", "CDS"],
        ["Director", "OTMS"],
        ["SPDS", "ESB"],
        ["ESU", "DSSB"],
        ["ESU", "EESB"],
        ["ESU", "TSB"],
        ["ESU", "SSB"],
        ["Director", "NAS"],
        ["ESB", "EEAS"],
        ["EEAS", "TC-10 Temp"],
         ["EEAS", "Tc-3 Temp"],
        
        
      ],
        
        let array_2 = [
           ["Director", "SPDS"],
         ["Director", "TC10"],
          ["Director", "TC9"],
         ["Director", "TC7"],
        ]

        function name () {
          let chartValue;
          chartValue = array_2
          alert(chartValue)
        }

        
Highcharts.chart("container", {
  chart: {
    height: 600,
    inverted: true
  },
  
  

  title: {
    useHTML: true,
    text: "FEM Lumps Nations"
  },
  accessibility: {
    typeDescription:
      "The organizational chart displays hierarchically the different departments of the United Nations statistics division."
  },
  series: [
    {
      type: "organization",
      name: "United Nations",
      keys: ["from", "to"],
     data:chartValue,
     
      levels: [
        {
          level: 0,
          color: "silver",
          dataLabels: {
            color: "black"
          },
          height: 25
        },
        {
          level: 1,
          color: "silver",
          dataLabels: {
            color: "black"
          },
          height: 25
        },
        {
          level: 2,
          dataLabels: {
            color: "black"
          },
          height: 25
        },
        {
          level: 4,
          dataLabels: {
            color: "black"
          },
          height: 25
        }
      ],
      nodes: [
        {
          id: "Director",
          title: null,
          name: "FEM Lump",
          color: "#419dc0",
          info: "Director",
        events: {
            click: function() {
              alert('catalogue');
            }
          }
           
        },
          {
          className: "title",
          id: "TC10",
          title: null,
          name: "TC - 10 Temperature",
          layout: "hanging",
          color: "#41c0a4",
          
        },
         {
          className: "title",
          id: "TC9",
          title: null,
          name: "TC - 9 Temperature",
          layout: "hanging",
          color: "#41c0a4",
           
        },
        {
          className: "title",
          id: "ESU",
          title: null,
          name: "TC - 8 Temperature",
          layout: "hanging",
          color: "#41c0a4",
           
        },
        {
          className: "title",
          id: "TC7",
          title: null,
          name: "TC - 7 Temperature",
          layout: "hanging",
          color: "#41c0a4",
           
        },
         {
          className: "title",
          id: "KILN",
          title: null,
          name: "Kiln ",
          layout: "hanging",
          color: "#41c0a4",
           
        },
        {
          id: "SPDS",
          title: null,
          name: "KOH Temperature",
          image: null,
          layout: "hanging",
          color: "#41c0a4",
         
        },
        {
          id: "CDS",
          title: null,
          name: "TC-9 Temperature",
          layout: "hanging",
          color: "#41c0a4",
          
        },
        {
          id: "OTMS",
          title: null,
          name: "TC-7 Temperature",
          layout: "hanging",
          color: "#41c0a4",
          
        },
        {
          id: "ESB",
          title: null,
          name: "Moisture in Injection coal",
          column: 2,
          layout: "hanging",
          color: "#abd734",
          info: "Economics Statistics Branch"
        },
        {
          id: "NAS",
          title: null,
          name: "PAB Air Flow",
          layout: "hanging",
          color: "#beef3a",
          info: "National Accounts Section"
        },
        {
          id: "EEAS",
          title: null,
          name: "Improper Coal Injection Pattern",
           
          layout: "hanging",
          color: "#beef3a",
          info: "Environmental Economic Accounts Section"
        },
        {
          id: "DSSB",
          name: "Moisture in Injection Coal",
          column: 2,
          layout: "hanging",
          color: "#34abd7",
          info: "Demographic and Social Statistics Branch"
        },
        {
          id: "DSS",
          name: "Demographic Stats",
          layout: "hanging",
          color: "#3abeef",
          info: "Demographic Statistics Section"
        },
        {
          id: "SHSS",
          name: "Social & Housing Stats",
          layout: "hanging",
          color: "#3abeef",
          info: "Social and Housing Statistics Section"
        },
        {
          id: "EESB",
          name: "Ore Feed Rate",
          column: 2,
          layout: "hanging",
          color: "#d734ab",
          info: "Environment and Energy Statistics Branch"
        },
         
        
        {
          id: "TSB",
          name: "Feed Coal Feed Rate",
          column: 2,
          layout: "hanging",
          color: "#d76034",
          info: "Trade Statistics Branch"
        },
        {
          id: "IMTSS",
          name: "Merchandise Trade Stats",
          layout: "hanging",
          color: "#ef6b3a",
          info: "International Merchandise Trade Statistics Section"
        },
        {
          id: "SITSS",
          name: "Stats of Trade",
          layout: "hanging",
          color: "#ef6b3a",
          info: "Statistics of International Trade in Services Section"
        },
        {
          id: "SSB",
          name: "Stats Services",
          column: 2,
          layout: "hanging",
          color: "#d7b234",
          info: "Statistical Services Branch"
        },
        {
          id: "GDSU",
          name: "Global Data Services",
          layout: "hanging",
          color: "#efc63a",
          info: "Global Data Services Unit"
        },
        {
          id: "SDS",
          name: "Stats Dissemination",
          layout: "hanging",
          color: "#efc63a",
          info: "Statistical Dissemination Section"
        },
        {
          id: "SGCU",
          name: "Geographic Conferences",
          layout: "hanging",
          color: "#efc63a",
          info: "Statistical and Geographic Conferences Unit"
        }
      ],
      colorByPoint: false,
      color: "#007ad0",
      dataLabels: {
        color: "white"
      },
      borderColor: "white",
      nodeWidth: 45,
      nodePadding: 2
    }
  ],

  tooltip: {
    outside: true,
    formatter: function () {
      return this.point.info;
    }
  },

    
    
  exporting: {
    allowHTML: true,
    sourceWidth: 800,
    sourceHeight: 600
  }

});
catalogue:''
column:''

**Comment by raf18seb** [comment]
Answered here: https://github.com/highcharts/highcharts/issues/16829
