### ISSUE TITLE
the area chart with time does not fill the area 

### ISSUE THREAD

**Issue by ikkosatrio** [highcharts/highcharts#16838]
#### Expected behaviour
i try this demo http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-time-series

#### Actual behaviour
i when i try to my local, the result is like this
![image](https://user-images.githubusercontent.com/17069028/147623036-c2e70c47-a13c-41ab-8fc1-976bf6646304.png)

i only copy & paste from demo, nothing is replaced

**Comment by raf18seb** [comment]
Hi @ikkosatrio! Thank you for reporting the issue.

Could you provide more info and the exact steps you made so I can reproduce your issue?
Did you set up a local server or you're just opening a simple `.html` file?

**Comment by ikkosatrio** [comment]
> Hi @ikkosatrio! Thank you for reporting the issue.
> 
> Could you provide more info and the exact steps you made so I can reproduce your issue? Did you set up a local server or you're just opening a simple `.html` file?

yeah i just simple add the JS and simple container html like this 

**JS :** 
$.getJSON(
    'https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/usdeur.json',
    function (data) {

        Highcharts.chart('container', {
            chart: {
                zoomType: 'x'
            },
            title: {
                text: 'USD to EUR exchange rate over time'
            },
            subtitle: {
                text: document.ontouchstart === undefined ?
                    'Click and drag in the plot area to zoom in' : 'Pinch the chart to zoom in'
            },
            xAxis: {
                type: 'datetime'
            },
            yAxis: {
                title: {
                    text: 'Exchange rate'
                }
            },
            legend: {
                enabled: false
            },
            plotOptions: {
                area: {
                    fillColor: {
                        linearGradient: {
                            x1: 0,
                            y1: 0,
                            x2: 0,
                            y2: 1
                        },
                        stops: [
                            [0, Highcharts.getOptions().colors[0]],
                            [1, Highcharts.color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                        ]
                    },
                    marker: {
                        radius: 2
                    },
                    lineWidth: 1,
                    states: {
                        hover: {
                            lineWidth: 1
                        }
                    },
                    threshold: null
                }
            },

            series: [{
                type: 'area',
                name: 'USD to EUR',
                data: data
            }]
        });
    }
);


**HTML :**

<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Kwh Meter (Monitoring Mode)</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Kwh</a></li>
            <li class="breadcrumb-item"><a href="{{ route('kwh.meter.index') }}">Meter</a></li>
            <li class="breadcrumb-item"><a href="{{ route('kwh.meter.monitoring') }}">Monitoring Mode</a></li>
            <li class="breadcrumb-item active">Detail Monitoring</li>
          </ol>
        </div>
      </div>
    </div>
</section>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1">
            <label>Tanggal data :</label>
        </div>
        <div class="col-md-3">
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text"><i class="far fa-clock"></i></span>
              </div>
              <input type="text" class="form-control float-right" id="reservationtime">
            </div>
            
        </div>
        <div class="col-md-6"></div>
        <div class="col-md-2">
            <button onclick="reloadFilter()" class="btn btn-success">Submit</button>
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-md-12">
            <figure class="highcharts-figure">
                <div id="container"></div>

            </figure>
        </div>
    </div>


</div>

**Comment by raf18seb** [comment]
@ikkosatrio did you make sure that you imported Highcharts modules? Like this:
```html
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
````

This is the whole content of my local HTML file and it's working fine:
```html
<!doctype html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <script src="https://code.highcharts.com/modules/data.js"></script>

</head>

<body>
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Kwh Meter (Monitoring Mode)</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Kwh</a></li>
            <li class="breadcrumb-item"><a href="{{ route('kwh.meter.index') }}">Meter</a></li>
            <li class="breadcrumb-item"><a href="{{ route('kwh.meter.monitoring') }}">Monitoring Mode</a></li>
            <li class="breadcrumb-item active">Detail Monitoring</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-1">
        <label>Tanggal data :</label>
      </div>
      <div class="col-md-3">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="far fa-clock"></i></span>
          </div>
          <input type="text" class="form-control float-right" id="reservationtime">
        </div>
        <!-- /.input group -->
      </div>
      <div class="col-md-6"></div>
      <div class="col-md-2">
        <button onclick="reloadFilter()" class="btn btn-success">Submit</button>
      </div>
    </div>
    <br>
    <br>
    <div class="row">
      <div class="col-md-12">
        <figure class="highcharts-figure">
          <div id="container"></div>

        </figure>
      </div>
    </div>
  </div>
</body>
<script>
  Highcharts.getJSON(
    'https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/usdeur.json',
    function (data) {
      Highcharts.chart('container', {
        chart: {
          zoomType: 'x'
        },
        title: {
          text: 'USD to EUR exchange rate over time'
        },
        subtitle: {
          text: document.ontouchstart === undefined ?
            'Click and drag in the plot area to zoom in' : 'Pinch the chart to zoom in'
        },
        xAxis: {
          type: 'datetime'
        },
        yAxis: {
          title: {
            text: 'Exchange rate'
          }
        },
        legend: {
          enabled: false
        },
        plotOptions: {
          area: {
            fillColor: {
              linearGradient: {
                x1: 0,
                y1: 0,
                x2: 0,
                y2: 1
              },
              stops: [
                [0, Highcharts.getOptions().colors[0]],
                [1, Highcharts.color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
              ]
            },
            marker: {
              radius: 2
            },
            lineWidth: 1,
            states: {
              hover: {
                lineWidth: 1
              }
            },
            threshold: null
          }
        },

        series: [{
          type: 'area',
          name: 'USD to EUR',
          data: data
        }]
      })
    });
</script>
````

**Comment by ikkosatrio** [comment]
@raf18seb i already import all highcharts module, and i also use laravel mix to load the modules
![image](https://user-images.githubusercontent.com/17069028/147796742-ef4ed2c6-e944-40c4-9c43-cd433f5407e1.png)

**Comment by raf18seb** [comment]
I think your problem is not strictly related to the Highcharts library, but more related to your config and other tech stacks you're using. I'm sorry, but without a live demo, I won't be able to help you.

For now, I consider it as **not** a Highcharts bug, so please let me close this ticket here (GH is our bugs/features tracker only).
In case you need further assistance with Highcharts, please contact us on our dedicated support channels: https://www.highcharts.com/blog/support/

In case you're sure that this is actually a problem with our library, then feel free to reopen the ticket and provide a full description of the problem so we can reproduce it and confirm.
