### ISSUE TITLE
Highstock's Slow Stochastic indicator missing %D line when both CL and HL are 0

### ISSUE THREAD

**Issue by jackytanjq** [highcharts/highcharts#16841]
#### Expected behaviour
The division of the CL and HL needs to be validated to prevent NaN value.

I have tested adding the line `K = K || 0;` to solve the issue temporarily in this function `StochasticIndicator.prototype.getValues`.
```
for (i = periodK - 1; i < yValLen; i++) {
  slicedY = yVal.slice(i - periodK + 1, i + 1);
  // Calculate %K
  extremes = AU.getArrayExtremes(slicedY, low, high);
  LL = extremes[0]; // Lowest low in %K periods
  CL = yVal[i][close] - LL;
  HL = extremes[1] - LL;
  K = CL / HL * 100;
  K = K || 0; // Added to solve the issue where the CL (Current Close - Lowest Low) / HL (Highest High - Lowest Low) is equal to NaN because both values are 0
  xData.push(xVal[i]);
...
```

#### Actual behaviour
The %D line went missing because the end result is NaN after the division.

Based on the screenshot below during debugging:
![Highcharts_Stock_SlowStochastic_%D_missing](https://user-images.githubusercontent.com/7489622/147740599-a43ad368-6ae7-4b38-a19b-b1de9f4ecb3b.png)

- CL: 0.59 - 0.59 = 0
- HL: 0.59 - 0.59 = 0
- CL / HL = NaN

#### Live demo with steps to reproduce
[https://jsfiddle.net/jackytanjq/sceym2Lo/2/](https://jsfiddle.net/jackytanjq/sceym2Lo/2/)
Kindly refer to the datetime starting from 22-Dec-2021 at 03:55, to find the missing %D line and value in the Slow Stochastic.

#### Product version
Highcharts Stock v9.3.2

#### Affected browser(s)
N/A

**Comment by raf18seb** [comment]
Hi @jackytanjq, thank you for reporting a bug!
