### ISSUE TITLE
Variwide legend per point

### ISSUE THREAD

**Issue by sakshi1eQ** [highcharts/highcharts#16848]
#### Expected behaviour

In case of Variwide chart, when colorByPoint and showInLegend properties are set true, the legend should show bin colors and respective labels in legend too, as it works for Pie chart.

#### Actual behaviour

Currently, the bin colors and labels are not shown in legend. A single entity in legend is shown.

#### Live demo with steps to reproduce
Expected behavior like Pie chart, jsFiddle: https://jsfiddle.net/sakshiKorade/omz2cr0t/
Actual behavior of Variwide chart, jsFiddle: https://jsfiddle.net/sakshiKorade/et7gb3os/31/

#### Product version
All

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi @sakshi1eQ, thank you for creating the ticket.

Unfortunately, only a pie chart supports legend by point at this moment.

You could borrow the logic from the pie series and this is what you'd get: https://jsfiddle.net/BlackLabel/mhkbjngz/
But there's still an empty gap on the xAxis where the point is hidden.

You could also write your own custom logic for cutting and setting the data, but this is far from a perfect solution: https://jsfiddle.net/BlackLabel/myp8hxkr/

I'm tagging as a feature request for now. Please, add a thumbs up if you want this feature to be added to Highcharts.
