### ISSUE TITLE
HighCharts.Series doesn't expose color, legendItem, legendSymbol

### ISSUE THREAD

**Issue by longmatthewh** [highcharts/highcharts#16846]
#### Expected behaviour
When using Typescript, I should be able to access color, legendItem, legendSymbol on a HighCharts.Series object, as follows:
```
const foo = (series:Highcharts.Series): void => {
     const legendItemElement:Element = series.legendItem.element;
     const legendSymbolElement:Element = series.legendSymbol.element;
     const seriesColor:string = series.color;

     //do something cool with color, legendItem, legendSymbol
}
```

#### Actual behaviour
In order to access color, legendItem, legendSymbol on a HighCharts.Series object, I have to cast it as any:
```
const foo = (series:Highcharts.Series): void => {
     const legendItemElement:Element = (series as any).legendItem.element;
     const legendSymbolElement:Element = (series as any).legendSymbol.element;
     const seriesColor:string = (series as any).color;

     //do something cool with color, legendItem, legendSymbol
}
```

I think color is a bit different, where if I cast the Series object as a specific type of PlotColumnOptions object I can get access to it, but maybe there's a better way. I don't know of any alternative, though, to getting access to legendSymbol or legendItem.

#### Live demo with steps to reproduce
https://jsfiddle.net/longmatthewh/jfpdso2t/63/

#### Product version
Highcharts JS v9.3.2

#### Affected browser(s)
N/A

**Comment by KacperMadej** [comment]
Hi @longmatthewh 

Without a code sample, it is hard to say for sure how you could resolve your problem.

This doesn't look like a bug report. You should contact technical support with your problem - https://www.highcharts.com/blog/support/

The public API is documented here - https://api.highcharts.com/class-reference/Highcharts.Series
If you are trying to access properties or methods outside of the public API then you will have to extend TS definitions or cast to `any` to avoid TS errors.

**Comment by longmatthewh** [comment]
@KacperMadej I've added as JSFiddle link to https://jsfiddle.net/longmatthewh/jfpdso2t/63/

**Comment by bre1470** [comment]
It might be useful to have some refactoring of legend properties on point and series beforehand. Then it would become much safer to expose legend properties in declarations and API based on a new `LegendAdditionsObject ` interface. So basically have:
```ts
interface LegendAdditionsObject {
    item: SVGElement,
    line: SVGElement,
    symbol: SVGElement
}
interface PointLike {
    legend?: LegendAdditionsObject
}
interface SeriesLike {
    legend?: LegendAdditionsObject
}
```
Do you have any opinion, @TorsteinHonsi?

**Comment by TorsteinHonsi** [comment]
@bre1470 I agree
