### ISSUE TITLE
Highcharts.Chart.hasCartesianSeries does not exist in TypeScript definitions

### ISSUE THREAD

**Issue by bennycode** [highcharts/highcharts#16855]
#### Expected behaviour

No compiler error when accessing `chart.hasCartesianSeries`.

Description:

I have logged the properties of my `Highcharts.Chart` instance and got to see the following properties:

```
'_cursor',
'_labelPanes',
'angular',
'axes',
'axisOffset',
'bounds',
'callback',
'caption',
'chartBackground',
'chartHeight',
'chartWidth',
'clipBox',
'clipOffset',
'clipRect',
'colorCounter',
'container',
'containerWidth',
'credits',
'eventOptions',
'extraBottomMargin',
'extraTopMargin',
'fixedRange',
'hasCartesianSeries',
'hasLoaded',
'hasRendered',
'hcEvents',
'index',
'inverted',
'isDirtyBox',
'isResizing',
'labelCollectors',
'legend',
'margin',
'marginBottom',
'marginRight',
'navigator',
'numberFormatter',
'options',
'plotBackground',
'plotBorder',
'plotBorderWidth',
'plotBox',
'plotHeight',
'plotLeft',
'plotSizeX',
'plotSizeY',
'plotTop',
'plotWidth',
'pointCount',
'pointer',
'polar',
'rangeSelector',
'renderer',
'renderTo',
'scrollableDirty',
'scrollbar',
'scroller',
'series',
'seriesGroup',
'sharedClips',
'spacing',
'spacingBox',
'styledMode',
'subtitle',
'symbolCounter',
'time',
'title',
'titleOffset',
'tooltip',
'unbindReflow',
'userOptions',
'xAxis',
'yAxis'
```

Unfortunately, not all of them seem to be exposed in the `highcharts.d.ts` file. For example: I am unable to access the `hasCartesianSeries` property using TypeScript:

```ts
import Highcharts from 'highcharts';

function test(chart: Highcharts.Chart): void {
  // TS2339: Property 'hasCartesianSeries' does not exist on type 'Chart'.
  console.log(chart.hasCartesianSeries);
}
```

#### Actual behaviour

TS compiler error when accessing `chart.hasCartesianSeries`.

#### Product version

Highcharts v9.3.2

#### Affected browser(s)

All

**Comment by KacperMadej** [comment]
Hi @bennycode 

Thank you for reporting the problem.

API TS definitions are public and are not fully describing all available properties as some of those are private and might be unstable - would cause a breaking change when changed. In case you need to access some properties that are not documented in the public API you could cast to `any` to avoid TS errors or [extend TS definitions](https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-declarations#extending-highcharts-in-typescript).

`hasCartesianSeries` is internal property - why do you need to access it? Maybe the same result could be achieved via some public API properties.

**Comment by bennycode** [comment]
Thanks @KacperMadej for your response and taking care of my issue. I used `hasCartesianSeries` as an example. The property I am interested in is `navigator` because I want to do this:

```ts
chart.navigator.series.find((s: Series) => s.name === 'Navigator 1').setData(chartData.data);
```

Is there a way to access `navigator` without the need to cast `chart` to `any`?

**Comment by bennycode** [comment]
Hi @pawelfus and thanks for your feedback!

Just to confirm, is this equivalent?

```ts
 chart.navigator.series.find((s: Series) => s.name === 'Navigator 1').setData(chartData.data);
```

→

```ts
chart.get('Navigator 1').update(chartData.data);
```

**Comment by raf18seb** [comment]
Hi @bennycode,

```js
chart.get('Navigator 1'); // undefined
```
The above will return `undefined` unless you define `id` on the navigator series. The `chart.get()` method is looking for `id` only, not series' name.

Farther on, when you manage to get the series, you can't use the `update` method like this:
```js
series.update(chartData.data);
```

You should either update it this way:
```js
series.update({ data: chartData.data });
```

or (recommended way) you should use the `series.setData()` method:
```js
series.setData(chartData.data);
```
