### ISSUE TITLE
PlotBbParamsOptions.standardDeviation missing in highcharts v9.3.2 typings

### ISSUE THREAD

**Issue by bennycode** [highcharts/highcharts#16857]
#### Expected behaviour

No TS compiler error when setting a `standardDeviation` for BollingerBands.

Example:

```ts
      {
        type: 'bb' as const,
        linkedTo: 'candleChart',
        yAxis: 0,
        color: 'grey',
        params: {
          standardDeviation: 2,
          period: 20,
          index: 3,
        },
        dataGrouping: {
          enabled: false,
        },
      }
```

#### Actual behaviour

The `highcharts.d.ts` file of highcharts v9.3.2 doesn't recognize `standardDeviation` anymore. It is simply missing from `interface PlotBbParamsOptions`. This was working fine with highcharts v9.1.2.

**Screenshot:**

![image](https://user-images.githubusercontent.com/469989/148248000-9df297cd-1ad3-4d0b-9ea6-58df761fea5c.png)

#### Live demo with steps to reproduce

The JS unit tests actually include a `standardDeviation` setting:

- https://github.com/highcharts/highcharts/blob/v9.3.2/samples/unit-tests/indicator-bb/recalculations/demo.js#L15-L22

#### Product version

- highcharts v9.3.2

#### Affected browser(s)

- TS source code is affected

**Comment by KacperMadej** [comment]
Hi @bennycode 

Thank you for reporting the problem.

_Internal note:_
TS definitions are not built correctly from the file.

`standardDeviation` is missing (as reported above), but also other options do not have correctly show default values:
- [period](https://api.highcharts.com/highstock/series.bb.params.period) shows as `14` while in code it is `20`:
https://github.com/highcharts/highcharts/blob/f918e912006432bc0e389cbbe46e3b6e0b499b6c/ts/Stock/Indicators/BB/BBIndicator.ts#L125

- [marker.endalbed](https://api.highcharts.com/highstock/series.bb.marker.enabled) shows as `false` while in code is `undefined `
https://github.com/highcharts/highcharts/blob/f918e912006432bc0e389cbbe46e3b6e0b499b6c/ts/Stock/Indicators/BB/BBIndicator.ts#L171

Maybe there are others that I missed - a double check is advised.

**Comment by bennycode** [comment]
@KacperMadej any news on this? It's still broken in v10.

**Comment by bre1470** [comment]
@raf18seb As I understand is this issue about the API options (jsdoc), not our internal interfaces.

Regarding our code: The `any` casts should be fixed to improve stability, as the internal typing is not working at the moment.
