### ISSUE TITLE
Difference between dataLabels.color and dataLabels.style.color

### ISSUE THREAD

**Issue by OldBuddy** [highcharts/highcharts#16872]
There are 2 options to set data labels color:

- https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.color

- and color property here: https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.style

Can you update docs to see how they are different? Or maybe better to stay with a single option?

**Comment by raf18seb** [comment]
Hi @OldBuddy!

I haven't found any differences between those two. The code responsible for picking a color is here:
https://github.com/highcharts/highcharts/blob/a0fe07fbd97a279e877fd77d66746cd6ea49816d/ts/Core/Series/DataLabel.ts#L576-L586

So, if the `dataLabels.color` is defined, this one is taken. If it's not defined, then `dataLabels.style.color` is taken if defined. If not defined (by default it's `'contrast'`, but you can set `dataLabels.style.color: undefined`), then the `series.color` is taken etc.

**Comment by OldBuddy** [comment]
@raf18seb, great! Is this priority described somewhere? Turned out we have `dataLabels.color` defined in default options, but actual series are using`dataLabels.style.color`, which has lower priority.

**Comment by raf18seb** [comment]
We don't have it described, but I think we should. Good point. Thank you for pointing this out!

**Comment by bre1470** [comment]
It looks like `dataLabels.color` has become a fallback: https://jsfiddle.net/bre1470/cp4o9230/1/

@TorsteinHonsi
- Can we deprecate `dataLabels.color` in favor of `dataLabels.style.color`?
- Or should we explain the priorities in the docs?

**Comment by TorsteinHonsi** [comment]
@bre1470 I think we should deprecate `dataLabels.color`. 

This `pick` statement goes back to at least v2 of Highcharts, but I can't see that it has any meaning using either one or the other. In v1 there was some functionality of setting `dataLabels.color: 'auto'`, but doing so now only renders black text.
