### ISSUE TITLE
Polar chart - datalabels inside

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1688]
Parameter inside (for datalabels) seems to not working for polar chart: 

Example: http://jsfiddle.net/deurk/BeVyt/2/

**Comment by PaulDalek** [comment]
+1

**Comment by Izothep** [comment]
+1

**Comment by idanhen** [comment]
+1

**Comment by mthangagiri** [comment]
Facing the same problem, inside parameter not working in funnel chart.

**Comment by kevinkanelooker** [comment]
+1 for funnels

**Comment by KacperMadej** [comment]
Funnel and pyramid issue with dataLables not working with `inside` option is here: https://github.com/highcharts/highcharts/issues/10036

This issue should be only about polar chart.
Here's a working demo for the polar chart with dataLaels.inside set to true problem: https://jsfiddle.net/BlackLabel/avsr52pe/

**Comment by mateuszkornecki** [comment]
+1
