### ISSUE TITLE
IE specific: chart doesn't plot and script error is shown if provided data label is empty string with space " "

### ISSUE THREAD

**Issue by tanmayshah95** [highcharts/highcharts#16890]
#### Expected behaviour
Chart should render properly in IE without script errors. 
using trim() is workaround, but seems issue should be handled OOTB.

#### Actual behaviour
Chart throws script errors in IE if provided data label is " " i.e. empty string with space

"TypeError: Unable to get property 'childNodes' of undefined or null reference
   at AST.prototype.parseMarkup (https://code.highcharts.com/highcharts.src.js:8093:17)

It seems doc.body is undefined as DOMParser generates HTMLDocument without body in IE

#### Live demo with steps to reproduce
[https://jsbin.com/nesekex/1/edit?html,js,console,output](https://jsbin.com/nesekex/1/edit?html,js,console,output)

#### Product version
latest version

#### Affected browser(s)
IE11

**Comment by raf18seb** [comment]
Hi @tanmayshah95, thank you for reporting a bug!
