### ISSUE TITLE
Boost: tooltip doesn't work for multiple columnrange points with the same x

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#16893]
#### Expected behaviour
Tooltip works for all the points

#### Actual behaviour
Tooltip works only for the first point of all the points that have the same `x` in data.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/vncadzke/

#### Product version
Highcharts 9.3.2

`Internal note:` this flag stops adding points with the same x: https://github.com/highcharts/highcharts/blob/8c15ecb4b92232ea63bc57830afcc1f21e70048d/ts/Extensions/Boost/BoostInit.ts#L130-L131
But even if we build a tree with all the points, it's still hard to find a correct point because it's looking for `x`, `y` or `xy` position (`findNearestPointBy`) for `low` or `high` value, but the whole column rect that mouse is hovering over needs to be found.
There's no workaround at this moment for this.

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: https://jsfiddle.net/highcharts/k4bxoht5/
