### ISSUE TITLE
Animation not supported on stacked areas

### ISSUE THREAD

**Issue by maorcc** [highcharts/highcharts#169]
Series.addPoint() causes the graph to flush in v2.1.1

See using v2.1.1:
http://jsfiddle.net/maorcc/atZef/2/

See using v2.0.5:
http://jsfiddle.net/maorcc/pzTUw/2/

**Comment by leilanim** [comment]
Is there a reason why the committed fix in the No Segments branch is not included in the official version?

**Comment by highslide-software** [comment]
Yes, the no-segments is a work in progress. We haven't implemented
areaspline stacking yet.​

**Comment by leilanim** [comment]
Thanks for the response. I was actually referring to your implementation for the animation for stacked areas. The stacked area animations are still broken as of the latest release version, but when I reference the nosegments branch, animations work fine. See below:

With latest release version:
http://jsfiddle.net/zsxfkqor/

With nosegments version:
http://jsfiddle.net/zsxfkqor/1/

**Comment by highslide-software** [comment]
Okay, but the answer is still that we need to wait for the no-segments, because the fix is based on that code base.
