### ISSUE TITLE
Transform a chart into image format due to highcharts async function disabled. 

### ISSUE THREAD

**Issue by cherishsim** [highcharts/highcharts#16900]
Could help me to modify this script so that it could display in image format?

$("#mc_report_pdf").highcharts({
            chart: {
                type: 'column',
                height: 450,
                marginTop: 35,
                style: {
                    fontFamily: 'Raleway'
                }
            },
            exporting: {
                url: export.highcharts.com,
                enabled: false,
                allowHTML: true
            },
            title: {
                text: ""
            },
            plotOptions: {
                column: {
                    colorByPoint: true,
                    groupPadding: 0,
                    pointPadding: 0.15,
                    dataLabels: {
                        enabled: true,
                        allowOverlap: true,
                        useHTML: true,
                        align: "center",
                        verticalAlign: "top",
                        y: -35,
                        crop: false,
                        overflow: 'none',
                        formatter: function () {
                            return "<span>" + Highcharts.numberFormat(this.y, 0) + '<small style="font-size:9pt;color:#A5A5A5;">%</small></span>';
                        },
                        style: {
                            textShadow: false,
                            textOutline: false,
                            fontSize: '17pt',
                            fontWeight: 700,
                            color: "#666"
                        }
                    }
    
                }
            },
            colors: _.map(dataSeries, "color"),
            credits: {
                enabled: false
            },
            xAxis: {
                categories: _.map(dataSeries, "name"),
                title: {
                    text: reportData.name,
                    style: {
                        fontSize: '10px',
                        fontWeight: 600,
                        color: "#edba02"
                    }
                },
                labels: {
                    style: {
                        fontSize: '8px',
                        fontWeight: 600
                    }
                }
            },
            yAxis: {
                min: 0,
                max: yMax,
                title: {
                    text: 'Some Text Here',
                    style: {
                        fontSize: '10px',
                        fontWeight: 600,
                        color: "#edba02"
                    }
                },
                labels: {
                    formatter: function () {
                        return Highcharts.numberFormat(this.value, 0, ',') + '%';
                    },
                    style: {
                        fontSize: '8px',
                        fontWeight: 600
                    }
                }
            },
            legend: {
                enabled: false,
            },
            tooltip: {
                enabled: false
            },
            noData: {
                style: {
                    fontWeight: 'bold',
                    fontSize: '16px',
                    color: 'red',
                }
            },
            series: [{
                name: '',
                data: _.map(dataSeries, "value")
            }],
        }, function(){
            $scope.mc_processing = false;
            
        });

**Comment by raf18seb** [comment]
Hi @cherishsim,

GH is our issues/features tracker only. With questions, please contact us on one of our support channels (for example Forum, StackOverflow, email, Skype).
More info: https://www.highcharts.com/blog/support/
