### ISSUE TITLE
addAnnotation stripping HTML attributes?

### ISSUE THREAD

**Issue by ldodds** [highcharts/highcharts#16908]
I'm upgrading some charts from version 7.2.1 to 9.3.2.

We add annotations to our chart via the `addAnnotations` call. The text for the annotations is HTML and we have the `userHTML` option set.

The annotation text is a link containing an icon:

```
<a href="..."><i class="fas fa-xxx" data-toggle="tooltip" data-placement="right" title="..."></a>
```

The `data-toggle` and `data-placement` attributes are used to format a Bootstrap popover for the annotation. This works fine on 7.2.1 but fails on 9.3.2.

In the new code there are JS console warnings:

```
Highcharts warning: Invalid attribute 'data-toggle' in config
Highcharts warning: Invalid attribute 'data-placement' in config
```

These 2 attributes are stripped from the HTML fragment before adding them. So then our code to activate the bootstrap popover fails as the `data-toggle` attribute isn't available to the JQuery selector.

Otherwise the annotation appears correctly.

I can possibly look at other ways to trigger the popover, but wondered if this was intended behaviour (and why) or if there's a way to whitelist specific attributes?

**Comment by raf18seb** [comment]
Hi @ldodds! Thanks for contacting us with your question.

With questions like this, you should contact us on one of our dedicated support channel (Forum, StackOverflow, email, Skype). GitHub is a bugs/features tracker only.
More info: https://www.highcharts.com/blog/support/
Let me close this question ticket here on GitHub.

As the answer is simple, I'll cover it here, but in any further questions please use other channels listed above.

You can white list your custom attributes by adding them to the `allowedAttrubutes` array:
```js
Highcharts.AST.allowedAttributes.push('data-toggle');
Highcharts.AST.allowedAttributes.push('data-placement');
```

More info: https://www.highcharts.com/docs/chart-concepts/security
