### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by max36895** [highcharts/highcharts#16913]
#### Expected behaviour
No high CPU load

#### Actual behaviour
High CPU load with fast mouse movement on the demo for example

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/line-basic

#### Product version
v-9.3.2

#### Affected browser(s)
all

**Comment by raf18seb** [comment]
Hi @max36895, thank you for creating a ticket!

Do you mean that performance should be improved when fast mouse hovering over the chart?

**Comment by max36895** [comment]
Нi @raf18seb 
Yes, or to make it possible to open the hint deferred.
Since the high load is most likely related precisely to the calculation of the position for the hint and its display
