### ISSUE TITLE
After reset zoom can't zoom properly

### ISSUE THREAD

**Issue by IgorFIE** [highcharts/highcharts#16910]
#### Expected behaviour
Given:
I set a chart to zoom in `xy`.
And I have my own `tickPositions`

When:
When I zoom I want to remove my tick positions and let highcharts use it's own settings resizing the intervals on it's own.
When I reset I should put back my own definitions.

Then:
If I zoom again (second time) I should be able to zoom and remove my own tick positions and let highcharts calculate it's own settings.

#### Actual behaviour
I can't zoom correctly the second time it doesn't remove my own `tickPositions`.
It seems that updating the `tickPositions` doesn't force the `setExtremes()` and even if I force to call the `setExtremes()` it doesn't fix the issue.

#### Live demo with steps to reproduce
https://jsfiddle.net/panintelligence/t8knzyu2/4/
![Peek 2022-01-21 17-54](https://user-images.githubusercontent.com/17085338/150576510-91dbba07-27ec-48a9-80cc-e7bc7a89e070.gif)

**Comment by raf18seb** [comment]
Hi @IgorFIE, thank you for reporting a bug!

Looks like a regression after https://github.com/highcharts/highcharts/commit/6ec3abf7a2c4ebc687f833cd2e0ec18a955cc60c

Workaround: clear the `axis.extKey` property after redrawing the chart: https://jsfiddle.net/BlackLabel/zkhp3yL2/
