### ISSUE TITLE
ShowInNavigator prevents live updates with addPoint

### ISSUE THREAD

**Issue by geowarin-sg** [highcharts/highcharts#16924]
#### Expected behaviour

Live data should work with navigator activated on any series in the graph.

#### Actual behaviour

When a second series is set to `showInNavigator` in highstock, live data of the first series get stuck.

#### Live demo with steps to reproduce

https://jsfiddle.net/y129zufk/1/

#### Product version
Latest

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @geowarin-sg 

Thank you for reporting the problem.

It looks like the navigator series will take the second series data anyway.
The first series that gets a new point will be tracked, as reported in the first comment, but in case a comparison could be useful see:
https://jsfiddle.net/BlackLabel/k9me3jos/1/
https://jsfiddle.net/BlackLabel/k9me3jos/
