### ISSUE TITLE
Null data animated to lines on show/hide series

### ISSUE THREAD

**Issue by soetji** [highcharts/highcharts#16925]
#### Expected behaviour
No lines on null data

#### Actual behaviour
Lines connecting non-null data

#### Live demo with steps to reproduce
https://jsfiddle.net/soetji/ousj7w0v/

Click on the Show/Hide Series button at the bottom

#### Product version
Highcharts,  v9.3.2

#### Affected browser(s)
Chrome, Firefox

**Comment by KacperMadej** [comment]
Hi @soetji ,

Thank you for reporting the problem.

Minimal demo: https://jsfiddle.net/BlackLabel/Lhxr43pt/
Steps: toggle 3rd series (orange) in the legend - on show the other series are animated in a strange way

**Comment by soetji** [comment]
Any plan for fixing this?

**Comment by karolkolodziej** [comment]
Hi @soetji! 
Thank you for bringing our attention once again to this issue.
We are going to discuss it internally and will keep you posted!
