### ISSUE TITLE
Current price label (price-indicator) does not work with multiple axis

### ISSUE THREAD

**Issue by pjm17971** [highcharts/highcharts#16940]
#### Expected behaviour

If you have say four axis, two on the right, two on the left, corresponding to 4 series, then the current price indicator would show correctly on the axis corresponding to that series.

#### Actual behaviour

The price indicators show on the same axis on the right, and same axis on the left. See this screenshot from our client:

<img width="415" alt="Screen Shot 2022-01-31 at 11 13 15 AM" src="https://user-images.githubusercontent.com/1288813/151858129-1a77264c-bbb2-4c8f-9b97-e24670826f3e.png">

#### Live demo with steps to reproduce

Can't create at this time

#### Product version

    "highcharts": "^9.1.1",
    "highcharts-react-official": "^3.0.0",

#### Affected browser(s)

All

**Comment by raf18seb** [comment]
Hi @pjm17971, thanks for reporting a problem! I agree, a label could be placed directly over an axis. The current behavior is inconsistent.

Demo: https://jsfiddle.net/BlackLabel/vc4myfsn/

**Comment by pjm17971** [comment]
@raf18seb @mfilipiec Yeah, kind of like that. Thanks for the jsfiddle. Here's a fork of that to show what's wrong more closely:
https://jsfiddle.net/sxp5n43L/1/

**Comment by pawelfus** [comment]
*Internal note:*
It's not directly caused by the Price indicator, but by the logic shared by Price Indicator and Crosshair: https://jsfiddle.net/BlackLabel/tvgzsL3k/1/

**Comment by pjm17971** [comment]
This is awesome! Thank you for fixing.
