### ISSUE TITLE
When using tooltip.outside, tooltip gets misaligned

### ISSUE THREAD

**Issue by rizzotto** [highcharts/highcharts#16944]
#### Expected behavior
Tooltip should not get misaligned when using `outside: true` property

#### Actual behavior
Tooltip is not aligned properly when using the outside prop

#### Live demo with steps to reproduce
Check the demo example https://jsfiddle.net/rizzotto/urhkswtj/ and set the property `outside` to `true`

![tooltip](https://user-images.githubusercontent.com/43299202/151977345-9a7988eb-5c8f-4b2e-aba0-666399272597.gif)

**Comment by raf18seb** [comment]
Hi @rizzotto, thank you for reporting a bug!

`Internal note:`
The tooltip's position is not being corrected by `tooltip.distance` in the `tooltip.updatePosition()` method when `tooltip.outside` is `true`.

Workaround: correct the position with this `pos.x -= this.distance / 2;`
Demo: https://jsfiddle.net/BlackLabel/yfxp9hkL/

**Comment by rizzotto** [comment]
Hey @raf18seb thanks for answering, also the Y is misaligned.

Do you have an ETA for this one?

Thanks!

**Comment by raf18seb** [comment]
We are preparing for the v10 release now, so no specific ETA for this bug, sorry. I'll put it into our development flow (`Inbox` tag).
If you're our licensed customer, please contact us at support@highcharts.com with your license ID, then we'll try to speed it up.

**Comment by TorsteinHonsi** [comment]
The connection to `distance` in the OP demo is probably a coincidence. Instead, I think it's about the chart's position in the page. The positioner is not corrected for the chart position.

* When the body has a 0 margin, [the position is correct](https://jsfiddle.net/highcharts/13jxnq29/1/).
* When the body has another margin, [the position is off by that margin](https://jsfiddle.net/highcharts/13jxnq29/2/)
* In a [real-life web page, it is off](https://jsfiddle.net/highcharts/13jxnq29/3/).

### Workaround
```js
        positioner(labelWidth, labelHeight, point) {
        	const chartPosition = this.chart.pointer.getChartPosition();
            return {
                x: chartPosition.left + point.plotX + this.chart.plotLeft - labelWidth / 2,
                y: chartPosition.top + this.chart.plotTop - 20,
            }
        },
```
[View it live on jsFiddle](https://jsfiddle.net/highcharts/13jxnq29/4/)
