### ISSUE TITLE
When using deep-copys to avoid data mutation during update, tooltip priority is no longer respected

### ISSUE THREAD

**Issue by jdalrymple** [highcharts/highcharts#16941]
#### Expected behaviour
When using deep copies to bypass the mutation issues (#4259 ) when performing an update on a series, tooltip configuration on a series should still take priority over the tooltip configuration on the chart or the plotOptions as defined [here](https://github.com/highcharts/highcharts/blob/12540607569b99467d91c447e23eb1d3b869e16d/samples/unit-tests/tooltip/options-order/demo.js)

#### Actual behaviour
Only the plotOptions or chart tooltip configuration is used.

#### Live demo with steps to reproduce

[Example](https://jsfiddle.net/pm58d2to/1/) of it working property i.e without the update logic/deep-copy, but with data mutated

[Example](https://jsfiddle.net/pm58d2to/2/) with the deep copy not working, but without data mutation

#### Product version
Highcharts 9.3.2 & Highchartjs npm pkg

#### Affected browser(s)
Firefox/Chrome

**Comment by raf18seb** [comment]
Hi @jdalrymple! Looking forward to see a failure example!

**Comment by jdalrymple** [comment]
Should be good now!

**Comment by raf18seb** [comment]
Hi again!

This is not a Highcharts issue, but a limitation of `JSON.stringify()` method, see [this section](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description).
Especially this:
```
undefined, Functions, and Symbols are not valid JSON values...
```

More info: https://www.google.com/search?q=JSON.parse%28JSON.stringify%28%29%29+bad+practice

It's working fine when you restore a function that `JSON.stringify()` removed: https://jsfiddle.net/BlackLabel/e5t8pbkc/

Closing as not related to Highcharts.

**Comment by raf18seb** [comment]
ps. you don't have to make a deep copy of the `series` array.
`series.data` is enough: https://jsfiddle.net/BlackLabel/zjefxv39/

**Comment by jdalrymple** [comment]
Thank you! I was racking my brain about this for way too long
