### ISSUE TITLE
"Cannot convert undefined or null to object" When Updating Venn Diagram

### ISSUE THREAD

**Issue by cmoihub** [highcharts/highcharts#16946]
#### Expected behaviour

https://user-images.githubusercontent.com/10642539/152056608-8f42a51d-f298-44d4-8a9c-f90f392a88d6.mov

#### Actual behaviour

https://user-images.githubusercontent.com/10642539/152056795-3c3ca567-4b39-4e6c-9663-0a0879eca576.mov

![image](https://user-images.githubusercontent.com/10642539/152055558-36a6f1fa-1095-4243-a88c-3c29958cefc9.png)

Effectively sometimes the way our data is sent, the highcharts library ends up rendering a euler diagram/combo of euler+venn rather than a venn diagram, if this happens on initial load it’s okay but going from venn to euler is problematic

The bug occurs at lines 623-624 in venn.src.js
`// animate only runs complete callback if something was animated.
  if (Object.keys(animatableAttribs).length) {
      graphic.animate(animatableAttribs, void 0, function () {
          destroy_1();
      });
  }`
![image](https://user-images.githubusercontent.com/10642539/152054769-c69c3fdf-ceb7-4c7c-8ef5-c634dcd7a5dd.png)

The animatableAttribs should exist before continuing

#### Live demo with steps to reproduce
[Click to view Live Demo](https://codesandbox.io/s/exciting-bush-oswu5)

#### Product version
`"highcharts": "^9.3.2",
    "highcharts-react-official": "^3.1.0",`

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hello @cmoihub, thanks for reporting this bug!

Simplified demo: https://jsfiddle.net/BlackLabel/9b1p5vkn/81/
`internal note:`
The Venn diagram seems to sometimes create the points, that don't have the shapeArgs field.

Workaround: 
Before calling the `draw` method, create empty `animatebleAttribs` object. This prevents throwing the error.
https://jsfiddle.net/BlackLabel/9b1p5vkn/82/

**Comment by cmoihub** [comment]
Thanks a million!

**Comment by Eslam3bed** [comment]
I have expeianced the same thing, however, I managed to resolve the issue with initializing the `keys` prop inside the `venn` options

```js
    plotOptions: {
      venn: {
        keys: [],
      },
      series: {
        cursor: 'pointer',
        point: {
          events: {
            click: function () {
              const self = this as any;
              onAreaClicked(self);
              self.select?.();
            },

          }
        }
      }
    },
...
```

**Comment by aaduane** [comment]
Would it be possible to provide an example of the empty `animatebleAttribs` object workaround but using React hooks and the the official Highcharts-React wrapper? It's not obvious to me how to do it in React. 

Here is an example of the `venn: { keys: [] }` workaround with the Highcharts-React wrapper if that helps: https://codesandbox.io/s/highcharts-reactt-5hvve1?file=/demo.jsx
