### ISSUE TITLE
On Gantt with subtasks not possible to add a milestone to the same row as an item

### ISSUE THREAD

**Issue by NordicLight** [highcharts/highcharts#16943]
#### Expected behaviour
It shall be possible to put the milestone on the same line as a gantt item or on a separate line using gantt subtasks (working fine without subtasks)

#### Actual behaviour
The milestone is always ending up on a separate line

#### Live demo with steps to reproduce 
Based on your subtask gantt demo
https://jsfiddle.net/7agyqmev/1/

#### Product version
9.3.2

#### Affected browser(s)
Tested on chrome but should be the same on all

#### Picture
The milestone on row 6 should be on row 0
<img width="658" alt="Screenshot 2022-02-01 at 12 01 21" src="https://user-images.githubusercontent.com/9700899/151957538-5b2af074-c74e-4d4d-b2dc-6c8bab91484b.png">

**Comment by raf18seb** [comment]
Hi @NordicLight! Thanks for creating the ticket.

> The milestone on row 6 should be on row 0
You can achieve it by defining milestones as a first point in the `series.data` array, see demo: https://jsfiddle.net/BlackLabel/o7fkav82/

You can also place a gantt point and a milestone in the same row by defining a common name for both of them and setting `yAxis.uniqueNames: true`, see demo: https://jsfiddle.net/BlackLabel/xq768zfu/

Please let me know if all your requirements are covered now. If yes, or if you have no more bugs to report, I would like to close the ticket.

**Comment by NordicLight** [comment]
Thank you for your promptly replay!

We want the milestone to be on the same row as a gantt bar. Your second proposed solution is only working placing the milestone on the first row. 

https://jsfiddle.net/r9md8b5h/

As an example we want the "Requirement" milestone to be on line 2 togheter with the "Requirement" bar. But the solution should be generic so should be possible to add milestones to any bar.
<img width="628" alt="Screenshot 2022-02-02 at 13 17 35" src="https://user-images.githubusercontent.com/9700899/152152439-755985b4-e3ba-4878-9461-4bcbd038fb09.png">

**Comment by NordicLight** [comment]
Any update on this. It looks like a bug.

**Comment by NordicLight** [comment]
Ok got it! 

Missed the parent property obvious... However since the milestone name is the same as the bar name. It just felt natural for me that the parent would be also the same so did not think of that testing. You can close the issue Thx!

**Comment by raf18seb** [comment]
@NordicLight you can use `series.dataLabels.formatter`, see demo: https://jsfiddle.net/BlackLabel/4s7tkova/

GitHub is our bugs/features tracker only, so if you have any other support questions (they are not bugs), then please contact us on one of our dedicated support channels.
More info: https://www.highcharts.com/blog/support/

Let me close the ticket here as we agree this is not a bug.
