### ISSUE TITLE
Problem with the mapbubble series API documentation.

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#16958]
#### Expected behaviour
Proper operation of the API in accordance with the implementation of TS.

#### Actual behaviour
There are significant differences in the API documentation compared to what the TS files contain:
<img width="670" alt="1" src="https://user-images.githubusercontent.com/39968065/152501608-5d4989ec-f897-400e-8e6e-1b6c13ce5743.png">

Take a look at the animationLimit property, which is set to 500 in the code and 250 in the API:
https://api.highcharts.com/highmaps/plotOptions.mapbubble.animationLimit

Same with joinBy - it doesn't appear for mapbubble in code, but appears as joinBy by default in API: 'hc-key' ( #16750 ). tooltip.pointFormat is set but does not appear in the API.

#### Product version
v9.3.3

**Comment by KacperMadej** [comment]
_Internal note:_
Copy all options from the bubble series to avoid adding bubble series in Highcharts Maps.
