### ISSUE TITLE
GUI opening on both charts

### ISSUE THREAD

**Issue by danieldavidraj** [highcharts/highcharts#16959]
When clicked on the indicators button
![image](https://user-images.githubusercontent.com/59305023/152375413-8526d36e-48a2-4bb4-9469-4bf599d6066c.png)
of one chart, the GUI opens for both the charts.

![image](https://user-images.githubusercontent.com/59305023/152375345-dcddd99d-13c5-490a-9cb5-9d6cf714c5eb.png)

Stackblitz link: https://stackblitz.com/edit/angular-ivy-rk2gar?file=src/app/relprice/relprice.component.ts

**Comment by karolkolodziej** [comment]
Hi! Thank you for reporting such behaviour.

Simplified demo: https://jsfiddle.net/BlackLabel/pLthkyvn/

_Internal note:_
Looks like not only a popup is opening on both charts but the same issue is with annotations, changing series type etc.
Additionally, it seems that the chart doesn't get the difference and treats toolbars equally.
Part of the `NavigationBindings.ts` file: 
``` TS
        // Handle multiple containers with the same class names:
        ([] as Array<HTMLElement>).forEach.call(bindingsContainer, function (
            subContainer: HTMLElement
        ): void {
            navigation.eventsToUnbind.push(
                addEvent(subContainer, 'click', function (
                    event: PointerEvent
                ): void {
                    const bindings = navigation.getButtonEvents(
                        subContainer,
                        event
                    );

                    if (
                        bindings &&
                        bindings.button.className
                            .indexOf('highcharts-disabled-btn') === -1
                    ) {
                        navigation.bindingsButtonClick(
                            bindings.button,
                            bindings.events,
                            event
                        );
                    }
                })
            );
        });
```

**Comment by pawelfus** [comment]
Hi @danieldavidraj 

Thanks for reporting the issue! This is expected behaviour, when both containers have the same classname for bindings. Please set different [`navigation.bindingsClassName`](https://api.highcharts.com/highstock/navigation.bindingsClassName) for both charts, for example: https://stackblitz.com/edit/angular-ivy-xffwdf?file=src%2Fapp%2Fcandlestick%2Fcandlestick.component.ts
