### ISSUE TITLE
Cannot combine `sunburst` with other series types

### ISSUE THREAD

**Issue by dfenerski** [highcharts/highcharts#16951]
I am creating a variation of combination charts. I have not had any problems until I've tried to use the `sunburst` type in combination with a `column` or `line` type.

The chart is completely broken if left with "original configuration" : `series:[{type:'column', ...}, {type: 'sunburst', ...}]`.

There is a slight improvement (chart not broken but `yAxis` is not rendered) If I add additional `xAxis`, and then add the sunburst series dynamically, with the options of  `xAxis: 1` (the index of the newly added mock axis)(this is displayed in the fiddle).

The chart displays properly if the `sunburst` is added first, and the the rest of the series.

http://jsfiddle.net/a1t2fj07/36/

Highcharts 9.*
Chrome 98

All 3 of the mentioned situations are easy to reproduce in the fiddle.

Thanks in advance!

**Comment by raf18seb** [comment]
Hi @dfenerski, thank you for your reporting a bug!

Workaround: 
```js
(function(H) {
  H.addEvent(H.Series, 'afterBindAxes', function() {
    if (!this.yAxis.options.title) {
      this.yAxis.options.title = {
        style: {}
      };
    }
  });
})(Highcharts)

Demo with a workaround: https://jsfiddle.net/BlackLabel/cwxthjp2/ (remember to add `point.value` to your data)
```

`Internal note:` the error occurs because the title is being deleted here: https://github.com/highcharts/highcharts/blob/4c8da32e726cc5e0cd7efc87542d7437e04194b9/ts/Series/Treemap/TreemapComposition.ts#L58

**Comment by dfenerski** [comment]
Thanks for the quick response @raf18seb !

I believe this does not fix the issue completely, please refer to this properly configured chart: [fiddle](https://jsfiddle.net/9u4hm37b/3/).

In the fiddle you provided, the `y-Axis` labels/values are still not shown as they usually would [here](http://jsfiddle.net/eyr2dcps/1/); although it is better than the one I provided, where the sunburst is not rendered at all.

I am a bit lost here between the different cases, but this is my understanding so far:

- broken normal state, proper configuration; (fix seems to have no effect): https://jsfiddle.net/9u4hm37b/5/
- sunburst not rendered state, no y-Axis labels: http://jsfiddle.net/a1t2fj07/36/
- no y-Axis labels; dynamic insertion of x-Axis and sunburst needed, otherwise breaks(why is this needed?): https://jsfiddle.net/BlackLabel/cwxthjp2/ 
- working state; i am unable to do this in a fiddle; i am able only locally, on the project i work on. basically I add some other series after I've added the sunburst; when I do this in the fiddle the additional series is not displayed unless I apply your fix. (http://jsfiddle.net/rkb5cjv1/10/)

Thank you again in advance for the support and sorry for the trouble!

Looking forward to clarifying this.

**Comment by raf18seb** [comment]
@dfenerski,

> the y-Axis labels/values are still not shown as they usually would

Yes, this is only a workaround.
A real problem is that the axes for sunburst are hidden by this code: https://github.com/highcharts/highcharts/blob/4c8da32e726cc5e0cd7efc87542d7437e04194b9/ts/Series/Treemap/TreemapComposition.ts#L38-L72

Because this is "event" (`addEvent`), it's not possible to edit this code in a live demo in jsFiddle, that's why I provided a workaround that is handling error only and makes the sunburst chart work, but this workaround indeed isn't solving all the problems.

On my local machine, I can edit the core code directly and with a few lines commented:
![image](https://user-images.githubusercontent.com/23310742/152351687-afbf4d21-acd4-4f62-a599-2ca31c8c1499.png)

The chart and axes look much better: 
![image](https://user-images.githubusercontent.com/23310742/152351783-e1eb0175-e7d9-4d4b-b42c-5b3820bb4821.png)


To avoid all those problems, it is recommended to display a sunburst on separate xAxis and yAxis like in this demo: https://jsfiddle.net/BlackLabel/hyokcj3L/
Is this what you've been trying to achieve?

**Comment by dfenerski** [comment]
Yes! Thank you.

I could not find a sample in the forums or in stackoverflow demonstrating combination between sunburst and other series types, so I decided to give it a shot myself. The number categories 
![image](https://user-images.githubusercontent.com/48520530/152352858-20856e55-d8c8-4606-ba1e-e6353cb1033d.png)
pointed me to add a mock `xAxis` and bind the sunburst to it, I didn't do the same to the yAxis. This first fiddle is what I was looking for.

I don't get the `TreeMap` source code and why the default behavior isn't enough but I will try to analyse it when I have the time.

Interestingly adding another series after the sunburst in my local project also achieves the desired effect, although your fiddle is superior.

I consider the problem solved, so I believe this issue can be closed?

Thanks again

BR

**Comment by dfenerski** [comment]
Hello again, @raf18seb

I am haunted by this scenario yet again,  with a little bit different configuration, so again, I turn to you and this github issue.

The config is basically the same, but for the main measure we choose type `bar`, [sample](https://jsfiddle.net/81nem4b5/2/).
There is some kind of rendering problem again, visible also in the fiddle, but much more in the project I work on. Here's a pic:
![image](https://user-images.githubusercontent.com/48520530/162063040-529a76e7-3847-4e1e-9328-e90aba7a2957.png)

The sunburst is not visible at all! It should be in the top right corner, the text '1.26M' is basically in the middle of the sunburst(title, moved with css to be in the center).

I will be very happy for any kind of help or hints.

Thanks in advance!

**Comment by pawellysy** [comment]
Hello @dfenerski.
The `bar` series type inverts the chart, which causes the issue. Check out this demo: https://jsfiddle.net/BlackLabel/9b1p5vkn/154/

The position of the sunburst chart is wrongly calculated here, which is the same result, which happens in your chart config. 
I will open this as a new bug.
