### ISSUE TITLE
radialGradient on pie chart issue when resizing

### ISSUE THREAD

**Issue by AdamPD** [highcharts/highcharts#1695]
Taking for example the official jsFiddle for the radialGradient on the pie chart:

http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pie-gradient/

When significantly resizing the browser window, the radial gradient disappears.  It appears that the radial gradient has a fixed position/size and that setSize doesn't correctly resize the gradient definition on window resize (or a direct call to setSize).

This is Chrome Version 26.0.1410.43 m on Windows 7.  I have tested on other browsers with SVG capabilities and it fails also.

**Comment by oysteinmoseng** [comment]
This seems to be working as expected with current code.
