### ISSUE TITLE
When a series has zero data and we zoom in navigator, it does not follow live updates

### ISSUE THREAD

**Issue by geowarin-sg** [highcharts/highcharts#16967]
The use case is a live graph where some series have data points at the beginning and some will have data later during the lifespan of the application.

It is possible to drag the navigator to the right end side to make it "follow" (meaning auto include new points).

#### Expected behaviour

When we drag the left handle of the navigator to zoom in, the navigator should follow live updates (the right handle stays stuck to the right end of the navigator).
However, if you zoom in while one of the series has 0 points, it will not work.

#### Actual behaviour

The navigator does not follow when it is used to zoom when ONE of multiple series receiving updates has empty data.
This only happens with `addPoint()` and not with `update()`.

#### Live demo with steps to reproduce

https://jsfiddle.net/mvz2rxo6/

In this live demo, you can observe that you have different behaviours when you use the navigator before the 5 seconds mark (when the second series receive a point) VS when you use it after it has at least one point.

#### Product version
latest

#### Affected browser(s)
all

**Comment by pawellysy** [comment]
Hello @geowarin-sg,


I don't really understand what is your goal here. What Do you mean by `zoom in while one of the series has 0 points`?
You can't zoom while both series have 0 points, and I don't see any difference, between the behavior when there are multiple series vs when there is only one series. 

Could you please try to explain exactly the reproduction steps, and provide some description, of how the navigator should be working in your opinion, and what are the differences between your expected and actual behavior? 

Apart from that, this is how the navigator should work. When the navigator is set to show the lowest or highest value, it sticks to the extremes. If the range selected by the navigator is not stretched to max (or min) value, it keeps current extremes.

**Comment by geowarin-sg** [comment]
The repro steps are in the jsfiddle.
When ONE series has zero data points, the navigator bugs if it is used to zoom in.

**Comment by geowarin-sg** [comment]
The navigator automatically follows new points when:
- All series have been initialized with at least one data point
- You do not zoom

So I assume this is a bug

**Comment by geowarin-sg** [comment]
The use case is a live graph where some series have data points at the beginning and some will have data later during the lifespan of the application.
We have different behaviors for the navigator when it is used before all series have at least one point VS when some have empty data.

**Comment by geowarin-sg** [comment]
@pawellysy @KacperMadej I've provided all the details I could and updated the original comment.

**Comment by pawellysy** [comment]
Ok, Thanks for the clarification!
 I get it now. This seems to be a bug. 

`internal note`

`navigator.stockToMax` is wrongly calculated here: https://github.com/highcharts/highcharts/blob/de78e654982f999e017f0b1f5f513101b2a86c98/ts/Core/Navigator.ts#L2593-L2595

**Comment by pawelfus** [comment]
Fixed since v10 (tested OP's demo).
In case of any issues, please let us know
