### ISSUE TITLE
IE11 - The line chart renders outside of the plotArea.

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#16965]
#### Expected behaviour
All chart should be rendered inside the plotArea.

#### Actual behaviour

![XMCFQcB0gVfHJLUuvW6k3s75ZkYH63wKXg](https://user-images.githubusercontent.com/26306846/152640923-25169175-068a-4328-b237-fd054de022b6.png)

Some part of the chart is outside the plotArea.
#### Live demo with steps to reproduce
https://jsfiddle.net/aouhmwb2/4/

#### Product version
Highcharts v9.3.1.

#### Affected browser(s)
IE11

**Comment by raf18seb** [comment]
Hi, thanks for reporting!

Seems like a problem with series clipping. Unfortunately, I'm now able to reproduce it in my IE11 (Windows 10, 19043.1466)
![image](https://user-images.githubusercontent.com/23310742/152847341-a268c70e-2f58-48a4-861f-5ea66743cba5.png)

Please, provide more info about the Highcharts version used, update your Windows, and, if the issue still occurs, provide the exact steps to reproduce.

**Comment by KacperMadej** [comment]
@raf18seb - please try this -> [testIE11.zip](https://github.com/highcharts/highcharts/files/8048353/testIE11.zip)
It shows as reported for me in IE11 mode in Edge.

**Comment by raf18seb** [comment]
Confirmed, it fails when the xAxis' extremes are set.

Probably regression after this PR https://github.com/highcharts/highcharts/pull/16341
It's not in a changelog, but the date 2021-09-17 fits because the problem occurs since v9.3.0 which was released 2021-10-21.

Simplified code:
```html
<!doctype html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://code.highcharts.com/highcharts.js"></script>

</head>

<body>
    <div id="container"></div>

    <script>

        Highcharts.chart('container', {

            xAxis: {
                min: 3
            },

            series: [{
                data: [4, 6, 4, 3, 4, 5, 6, 4, 3, 4, 3, 2, 3, 4]
            }]
        });

    </script>
</body>

</html>
```

[IE11ClipBug.zip](https://github.com/highcharts/highcharts/files/8068807/IE11ClipBug.zip)
