### ISSUE TITLE
BrokenAxis and toValue() outside the current range

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#16960]
#### Expected behaviour
Correct value from `toValue()` when calling with a pixel value outside plotting area

#### Actual behaviour
Value is returned as if the axis would not use breaks.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/ny3azspf/

Simplified:  https://jsfiddle.net/BlackLabel/ny3azspf/1/ 

Check the console for the results and comments for the expected results

Subtask of #13898

**Comment by TorsteinHonsi** [comment]
@pawelfus I am trying to break down the problem to a simpler demo without scrollbars. This is what I came up with: https://jsfiddle.net/highcharts/3tenz06j/ . It seems to be correct unless the value for 300px. Is it representative?

**Comment by pawelfus** [comment]
Updated the main demo to this one: https://jsfiddle.net/BlackLabel/ny3azspf/1/ (removed scrollbar, Stock etc.)

In your example, this is the case (`xAxis.max` is set): https://jsfiddle.net/BlackLabel/yq6dwr01/
And the same demo, without max: https://jsfiddle.net/BlackLabel/yq6dwr01/1/ - we can observe the change between 200px -> 201px (value jumps from 200 to 300). When extremes are set, it's returning continuous slope
