### ISSUE TITLE
Difference between Line and Area chart data type formatting

### ISSUE THREAD

**Issue by livevsonline** [highcharts/highcharts#16966]
Im trying to convert my stockhighchart from 'Line' type to 'Area' type due to the fillColor gradients

#### Expected behaviour (Line version)
![image](https://user-images.githubusercontent.com/39704356/152760500-ba3ca2a0-4692-4996-b1e6-75146d159d67.png)

#### Actual behaviour (Area version)
![image](https://user-images.githubusercontent.com/39704356/152760440-f492ecc0-3241-4dd6-9e29-27345a95e1a7.png)

However when i use Area chart, the formatting of the data looks way different than the linechart formatting? i would like the data to be displayed like the linechart, but keep the fillColor/gradients as the Area chart type has, whats the difference between just toggling the "Line" and "Area" chart?

The active code is too long to post here, i hope someone have a quick answer

#### Live demo with steps to reproduce
Too long with too much data

#### Product version
Highstock 9.3.2

**Comment by pawellysy** [comment]
Hello @livevsonline.
The difference in those charts is that the area chart makes the yAxis start from 0, whereas the line chart adjusts both min and max values of the yAxis. What you can do, is manually set the min value of the yAxis, like here: https://jsfiddle.net/BlackLabel/Lsb0etnx/

For the future GitHub is an issue tracking tool, with similar questions please contact us via our official support channels, which are listed here: https://www.highcharts.com/blog/support/

**Comment by livevsonline** [comment]
> e yAxis

Okay I'm sorry for the inconvenience, is there a natural formula i can use to get the same result as the Line chart?
