### ISSUE TITLE
Control point for rectangle annotation is missing when adding annotation through GUI

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#16970]
#### Expected behaviour
Allow changing the size of the rectangle by the control point.

#### Actual behaviour
The control point to resize the rectangle is missing.

#### Live demo with steps to reproduce
Add rectangle annotation and try changing its size.
https://jsfiddle.net/BlackLabel/nhgbetpv/

#### Product version
Fails from 9.3.0

#### Affected browser(s)
ALL

**Comment by raf18seb** [comment]
Bisected to https://github.com/highcharts/highcharts/commit/f2d3f7a03679e743674e54ea1e498effb1ee093f

**Comment by jackytanjq** [comment]
Hello,
Can I know if there is a solution for this while waiting for this fix an upcoming update?

**Comment by pawellysy** [comment]
Hello @jackytanjq!

Here is the workaround: https://jsfiddle.net/BlackLabel/nhgbetpv/3/

**Comment by jackytanjq** [comment]
Hello pawellysy,
Thank you for the prompt workaround, just tested and the rectangle can now be resized again.
