### ISSUE TITLE
Gantt Chart - Interactive Gantt hangs the browser with fastAvoid dependency type

### ISSUE THREAD

**Issue by NordicLight** [highcharts/highcharts#16990]
#### Expected behaviour
Browser should not hang

#### Actual behaviour
It hangs dragging the bar to the milestone if the milestone is on the same row as the bar (not happening on dependency type simpleConnect)

<img width="706" alt="Screenshot 2022-02-14 at 02 06 23" src="https://user-images.githubusercontent.com/9700899/153784329-4e7cf2f1-67d4-4e10-8c84-0a4c97d2c621.png">

<img width="600" alt="Screenshot 2022-02-14 at 02 14 56" src="https://user-images.githubusercontent.com/9700899/153784661-a28b42cf-f508-4df2-b46c-5779e3c83659.png">

#### Live demo with steps to reproduce
https://jsfiddle.net/pmzrxLs2/14/

#### Product version
v9.3.3

#### Affected browser(s)
Tested on Chrome

**Comment by NordicLight** [comment]
Unfortunately the workaround is not ok if you have a milestone on the same row as a bar. Please see below the initial bug report we raised but closed since fastAvoid fixed that problem.

https://github.com/highcharts/highcharts/issues/16989

**Comment by pawellysy** [comment]
@NordicLight Sorry, but this piece of code is really hard to debug and there is no workaround I could provide. Unfortunately, the best way is to avoid using this pathfinding algorithm for now.

**Comment by NordicLight** [comment]
ok thx for trying..  The workaround we have implemented is to use simpleConnect if the milestone has a dependency to a bar on the same row. And for all other dependencies fastAvoid. 

Our general feedback is also that the fastAvoid could be a bit better done. Sometimes the dependencies lines are a bit strange.
