### ISSUE TITLE
Timeseries chart with ordinal abscissa: crosshair label formatter gets wrong time values after max ordinal position

### ISSUE THREAD

**Issue by robocop98** [highcharts/highcharts#16996]
#### Expected behaviour

While hovering a stockchart (timeseries chart), the crosshair label formatter values should always

- have the same times seen at the abscissa (and tooltip)
- increase when hovering from left to right (old to new time)

#### Actual behaviour

Crosshair label formatter value are only correct until reaching the last data point (max ordinal position) on the right side.
When hovering beyond the last point, its time value flips back to past times.

Findings (not sure if those are all correct):

- `xAxis.ordinal: true` seems to be main culprit, with `xAxis.ordinal: false` the time values are correct
- `dataGrouping` seems to play a role, as the wrong values smell like "correct value minus dataGrouping unit (e.g. 1 day)
- at the same time the crosshair values are wrong, the tooltip/point values (not part of fiddle demo) are still correct
- the following settings give the extra space beyond the last point: `endOnTick: false`, `startOnTick: false`, some volume-ish column series needs to be available

#### Live demo with steps to reproduce

https://jsfiddle.net/edcbok9z/13/

Please zoom in with navigator to see all individual days on the right side,

then hover to left side of last point (correct date, 14.02.),
![Screenshot_2022-02-15_08-13-09](https://user-images.githubusercontent.com/39035397/154015373-1d7ae8b2-ada3-43b0-8e5b-4eb5044f13b3.png)

then further to right side, beyond the last point (incorrect date, 1 day back, 13.02.)
![Screenshot_2022-02-15_08-13-24](https://user-images.githubusercontent.com/39035397/154015394-fe14bb74-1d76-4d6c-aeb0-4e2a4af61a01.png)

#### Product version
Issue found in Highstock 9.3.1 - 9.3.3

#### Affected browser(s)
Tested in Chrome, Firefox, but seems not to matter

Might be related to https://github.com/highcharts/highcharts/issues/3825 ?

**Comment by pawelfus** [comment]
*Internal note:*
Simplified even more: https://jsfiddle.net/BlackLabel/x8bnf7yw/ (
It's a bug in `toValue()` method in OrdinalAxis. Just a guess, but it seems `lin2val()` is fails here:
https://github.com/highcharts/highcharts/blob/3148e12674a6d2c404cdc8dd692e4f484e1ce1b5/ts/Core/Axis/OrdinalAxis.ts#L509-L524

In the example above (in the moment of writing this comment):
- `positions.length = 19`
- `index = 18.x`
- `return lastPositionsValue + slope * (index - positionsLength);` -> `index - positionsLength` -> `18.x - 19` -> we get nagative value which will return a value below the `lastPositionsValue`
