### ISSUE TITLE
Treemap Header width customization

### ISSUE THREAD

**Issue by thoratpratik** [highcharts/highcharts#16999]
I am building treemap using Highcharts Treemap in which I have sector categories. Categories are displayed properly but I want the width of category to be 100%(IT, Chemical etc in JSFiddle). Currently I can only position it left/right/centre.

JsFilddle Link - https://jsfiddle.net/gvb70cwj/1/

sector name should be appear as below (highlighted in yellow  e.g - IT , Chemical,Pharma )
<img width="1140" alt="Screenshot 2022-02-11 at 4 59 35 PM" src="https://user-images.githubusercontent.com/67839489/154042085-929ef155-fb06-4934-9595-dc9b16c315f1.png">

**Comment by raf18seb** [comment]
Hi @thoratpratik, thanks for writing to us!

GitHub is our bugs and features tracker only. With any support questions, please contact us on one of our dedicated support channels.
More info: https://www.highcharts.com/blog/support/
Thanks for understanding!
