### ISSUE TITLE
AxisSetExtremesEventObject.rangeSelectorButton  does not exist in TypeScript definitions

### ISSUE THREAD

**Issue by bennycode** [highcharts/highcharts#17005]
#### Expected behaviour

I want to access the `rangeSelectorButton` property from the `afterSetExtremes` callback event in TypeScript:

```ts
const [options, setOptions] = useState<Highcharts.Options>({
  xAxis: {
    events: {
      afterSetExtremes: event => {
        console.log(event.rangeSelectorButton);
      }
    }
  }
});
```

I need to access the `rangeSelectorButton` in order to get the range (1m, 1h, ...) that has been selected.

#### Actual behaviour

> TS2339: Property 'rangeSelectorButton' does not exist on type 'AxisSetExtremesEventObject'.

#### Product version

Highcharts v9.3.3

#### Affected browser(s)

All

**Comment by pawellysy** [comment]
Hello @bennycode!
Thanks for reporting this issue!


#### Workaround:
Create your own interface which extends `Highcharts.AxisSetExtremesEventObject`, and add `rangeSelectorButton` as a conditional property like this: 


```ts
interface rangeSelectorButtonProperties{
    text: string
    title: string
    type: string
    _offsetMax: number
    _offsetMin: number
    _range: number
}
interface ExtendedAxisSetExtremesEventObject extends Highcharts.AxisSetExtremesEventObject {
    rangeSelectorButton?: rangeSelectorButtonProperties;
}
```

then you can use it in options like this: 
```ts
 xAxis: {
            events: {
                afterSetExtremes: function (event: ExtendedAxisSetExtremesEventObject) {
                    console.log(event.rangeSelectorButton);
                }
            }
        },
```

**Comment by bre1470** [comment]
One should be able to get the range directly from the axis itself as the event fires after `afterSetExtremes`.

**Comment by bre1470** [comment]
Example to determine the selected range of days: https://jsfiddle.net/bre1470/9cp3wugx/

**Comment by chyzwar** [comment]
Type definitions were fixed in latest version :?

**Comment by chyzwar** [comment]
Problem still exists in 10.3.2
