### ISSUE TITLE
Highmaps crash if rerendering while updating the series and animating

### ISSUE THREAD

**Issue by zoltan-makranczi-anaplan** [highcharts/highcharts#17011]
#### Expected behaviour
The map / maps don't crash on updates while the animation is going.
We wouldn't like to turn the animation off.
The reason behind using the `key` is that otherwise some props aren't updating. See [this sandbox](https://codesandbox.io/s/hc-map-all-charts-not-updating-iqk00s?file=/src/App.js) for ref - but raising that as a separate issue.

#### Actual behaviour
```
TypeError
Cannot read properties of undefined (reading 'setAttribute')
```
And the maps fail to render till the next full page reload.

#### Live demo with steps to reproduce
https://codesandbox.io/s/hc-map-update-while-rerender-break-54trnm?file=/src/App.js

#### Product version
Some examples:
* highcharts@9.3.3 & highcharts-react-official@3.1.0
* highcharts@9.3.2 & highcharts-react-official@3.0.0
* and probably more

#### Affected browser(s)
All

This issue has been mentioned here as well:
https://www.highcharts.com/forum/viewtopic.php?f=14&t=47883&p=172728&hilit=animation#p172728

**Comment by raf18seb** [comment]
Hi @zoltan-makranczi-anaplan, thank you for creating a ticket.

I was able to reproduce a problem without React: http://jsfiddle.net/BlackLabel/d6sj5o9h/
However, the problem doesn't occur on master: http://jsfiddle.net/BlackLabel/6jekz137/

Let's wait for the v10 release (will be released in 2 weeks) and we'll test it in React with the newest Highcharts.

**Comment by KacperMadej** [comment]
Unable to recreate in v10.
Closing as resolved.
