### ISSUE TITLE
Toggling allAreas on a map doesn't update the map as expected

### ISSUE THREAD

**Issue by zoltan-makranczi-anaplan** [highcharts/highcharts#17012]
#### Expected behaviour
Setting `allAreas` through the react wrapper should reflect the correct behaviour.
true: render all available areas.
false: render just the areas where there's data associated.
Forcing re-renders are needed to correctly see the state, but that leads to other problems (the whole map breaking - [ref](https://github.com/highcharts/highcharts/issues/17011))

#### Actual behaviour
Toggling `allAreas` has no effect, and subsequent toggles have the exact opposite effect.
Forcibly rerendering (using the `key` ) works, but breaks the map if it happens during an animation.

#### Live demo with steps to reproduce
https://codesandbox.io/s/hc-map-all-charts-not-updating-iqk00s?file=/src/App.js

#### Product version
* highcharts@9.3.3 & highcharts-react-official@3.1.0
* highcharts@9.3.2 & highcharts-react-official@3.0.0
* probably more

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi @zoltan-makranczi-anaplan, thank you for reporting a bug.

Works on master, but there's another problem - mapView bounds are opposite: https://jsfiddle.net/BlackLabel/r7djL0fe/

**Comment by KacperMadej** [comment]
_Internal note:_
Try dragging the map after an update to see the desired result.

**Comment by raf18seb** [comment]
Workaround: run `chart.mapView.fitToBounds()` after redraw: https://jsfiddle.net/BlackLabel/r7djL0fe/1/

**Comment by zoltan-makranczi-zenitech** [comment]
Hi there,

Thanks for looking into this!
The existence of a workaround is great news; depending on the ETA of the fix we might use that as option B till the code is released.

Approximately when do you think the fix will become available in a stable version?

Thank you!

**Comment by pawellysy** [comment]
Hi @zoltan-makranczi-anaplan! As you can see, we are already preparing the fix, and when the above PR will be merged, the fix will be included in the next official release. It is difficult to say when it will be. I will try to let you know when the next release will be scheduled :)
