### ISSUE TITLE
Flag pointing at high or close price

### ISSUE THREAD

**Issue by williamwongys** [highcharts/highcharts#17027]
# Description of the feature
Currently, flag for candlestick chart points at close price.  I would like buy flag to point at low price and  appear below and sell flag to point at high price and appear above.  In this way, the chart will look neater in buy low sell high strategy.   In current implementation, all flags will appear above the bar.

**Comment by karolkolodziej** [comment]
Hi! Thank you for contacting us!
We have such feature. 
You can control the flag position by the `onKey` property as described in the API linked below.

API: https://api.highcharts.com/highstock/series.flags.onKey
Demo: https://jsfiddle.net/BlackLabel/ywk56n42/
