### ISSUE TITLE
Is this possible in highchart ?  (Image attached)

### ISSUE THREAD

**Issue by saswat3115** [highcharts/highcharts#17026]
![image](https://user-images.githubusercontent.com/14299682/155096539-8adc5770-8f59-4010-b878-e43b235b295b.png)

**Comment by raf18seb** [comment]
Hi @saswat3115, thanks for writing to us.

GitHub is our bugs/features tracker only. With any support questions, please contact our support engineers on one of our dedicated support channels. More info: https://www.highcharts.com/blog/support/
