### ISSUE TITLE
mouseOver error when passing undefined to config.plotOptions.series.events

### ISSUE THREAD

**Issue by eplatek-safyr** [highcharts/highcharts#17034]
#### Expected behaviour

the library should remove the events key or replace it with an empty object if `undefined` is passed to `config.plotOptions.series.events`

#### Actual behaviour

The event handler on mouseOver doesn't manage the case where events is undefined

#### Live demo with steps to reproduce
[Example here](https://codesandbox.io/s/goofy-burnell-pm39oc)

#### Affected browser(s)
any

**Comment by raf18seb** [comment]
Hi @eplatek-safyr, thanks for writing to us!

The API says that the `plotOptions.series.events` should be an object: https://api.highcharts.com/highcharts/plotOptions.series.events

Could you please tell us what is a real use-case for setting them to `undefined`? Why can't you use an empty object?
Don't get me wrong - the API is correct and it works when you use an empty object `{}` instead of `undefined` and I don't see any reason why it should be changed. Maybe I'm missing something?

**Comment by eplatek-safyr** [comment]
In my use case I set the events object conditionnally. So when my condition is met, I set an event handler, otherwise I used to put undefined, as the typescript definition allows it (which is the point of my PR). But now I'm using empty object and it solves my problem.

The point I'm taking here is that the library could handle the options management. In my opinion a choice should be made between either:
- Update the typings definition to forbid events to be undefined (which will be difficult because not defining the key is equivalent to provide undefined value to the key)
- Allow undefined in the events field, and remove the key when undefined is set in this key
- Throw early when undefined is passed to the events key

The second option seems the most user friendly as it doesn't break any of the API definition. I mean, because a legal usage of the plotOptions definition is to not use the key, it seems like passing undefined to it is equivalent, and that was confusing to me because typescript was allowing me this usage.

Furthermore I found the issue only once I saw that some users had performance drops and the tooltip not displaying because the mouseOver event was not expecting events to be undefined. I didn't check the code but I think that when the options are loaded in highcharts library, if the key events is not present, it is replaced with an empty object, otherwise it uses the provided value. So maybe this specific case could fullfill the typescript definition allowing undefined, and fix the issue at the same time

**Comment by raf18seb** [comment]
Thanks! Ok, now I see that it's indeed optional in TypeScript (`undefined` is allowed). So either `undefined` events should be allowed (as you suggested), or our TypeScript should be improved.

`Internal note:`
Adding both "bug" and "TypeScript" tags, but it does not necessarily mean it's a TypeScript bug (not decided yet).

**Comment by bre1470** [comment]
This works as intended. It is an option, therefore optional. Optional always allows `undefined`, which means that the option will not change. If you do like to unset events, please set an empty object as this:
```ts
{
    events: (myVariable || {}),
}
```
