### ISSUE TITLE
On the drill down in tree map charts, is it possible to show the prior label name on the chart? 

### ISSUE THREAD

**Issue by javahuang1995** [highcharts/highcharts#17035]
#### Expected behaviour
Show the prior label name on the tree map chart's head position if user drill down.

#### Actual behaviour
Not showing the prior label if user drill down.

**Comment by pawellysy** [comment]
Hello, @javahuang1995 thanks for contacting us with your question!
Github is our bug/feature tracker tool. For support questions like this one, please contact us via our official support channels. More info here: https://www.highcharts.com/blog/support/
Thanks for understanding!

**Comment by javahuang1995** [comment]
thanks!!
