### ISSUE TITLE
OrdinalAxis: panning to the left is broken in full view

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#17042]
#### Expected behaviour
When the xAxis is spanned to full range and you try to pan the chart to the left, nothing should happen

#### Actual behaviour
The extremes change to the smallest range near max values.

#### Live demo with steps to reproduce

hold the mouse button down and move the mouse to the right, like you would like to see smaller values of the xAxis.
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui

#### Product version
v9.3.3.
#### Affected browser(s)
all

**Comment by karolkolodziej** [comment]
Internal note:
- bisected to commit [9724220c](https://github.com/highslide-software/highcharts.com/commit/9724220cdc6fd65c1837598422adf030f4df8aa5)
- works well in version 9.3.0
- works with line series

Simplified demo: https://jsfiddle.net/BlackLabel/xzv02Lys/
