### ISSUE TITLE
Long title overlaps subtitle

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1704]
In case when we have long title, then subtitle is overlapped. 

Example: http://jsfiddle.net/KfMxN/51/

**Comment by dmacoritto** [comment]
I am running into that issue as well, why is this topic closed?

**Comment by karolkolodziej** [comment]
Hi @dmacoritto!

Could you please update [the demo](https://jsfiddle.net/BlackLabel/vq485unw/) with your config so the issue is replicable?
I was not able to achieve it.
