### ISSUE TITLE
Docs: `addPlotLine` and `addPlotBand` methods are missing

### ISSUE THREAD

**Issue by bm64** [highcharts/highcharts#17052]
#### Expected behaviour
Docs should include information about `addPlotLine` and `addPlotBand` methods.

#### Actual behaviour
Docs are missing information about `addPlotLine` and `addPlotBand` methods.
Link: https://api.highcharts.com/highcharts/Axis.addPlotBand,
https://api.highcharts.com/highcharts/Axis.addPlotLine

**Comment by ochristensen** [comment]
related: removePlotline and removePlotBand are also undocumented

**Comment by cnighswonger** [comment]
This was reported by me over a year ago. [See here.](https://www.highcharts.com/forum/viewtopic.php?t=48231)

And it still does not appear to be in the docs. Maybe Highcharts needs to hire a document manager? 😄

**Comment by TorsteinHonsi** [comment]
I think this is actually more a docs bug than an enhancement. We already have the doclet, probably something in the documentation build is failing: https://github.com/highcharts/highcharts/blob/b1242b98a0cab0a6a72ac67ed95ddbe636618f9a/ts/Core/Axis/PlotLineOrBand/PlotLineOrBandAxis.ts#L177-L191

**Comment by cnighswonger** [comment]
Thanks @TorsteinHonsi 

You all are awesome! 👍
