### ISSUE TITLE
Enabling the boost module for networkgraphs

### ISSUE THREAD

**Issue by okohll** [highcharts/highcharts#17060]
# Description of the feature
The boost module improves rendering performance, but does not yet work with the network graphs module. Is it feasible that it could do so?

Currently, if the number of nodes is in the high hundreds, animation rendering can slow down to the point of a second or so per frame, meaning waiting minutes for a diagram to settle down to something that is comprehensible.

Even on smaller datasets, Highcharts network rendering is relatively slow and jerky - compare

https://www.highcharts.com/demo/network-graph

to the smoothness of D3:

http://projects.flowingdata.com/tut/interactive_network_demo/

Highcharts is easier to use because it is a higher level library, but this is an issue, as other people have reported: https://www.highcharts.com/forum/viewtopic.php?t=43756

# Library related to the feature
Highcharts Network Graphs, Highcharts Boost

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by okohll** [comment]
As a workaround, I notice that if labels are disabled in the example https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/network-graph, animation speeds up considerably.

Is it possible to initially disable labels and programatically enable them a few seconds later, on a Javascript timeout?

I can't see any way to do so in the API docs.

**Comment by pawellysy** [comment]
Hi @okohll, thanks for creating the issue!
As you noticed, rendering of the `dataLabels` is a bit expensive, and disabling it smoothens the animation.
The workaround that you proposed also seems fine and can be easily achieved. Here is the demo, where dataLabels are enabled after 4 seconds: https://jsfiddle.net/BlackLabel/zdbsf154/

This topic of adding a boost module to `networkgraph` series was considered, but for now, it is suspended.

There were some example demos, e.g. this: https://jsfiddle.net/BlackLabel/ryj5p0oa/1/
as well as draft PR with example changes: https://github.com/highcharts/highcharts/pull/15731

Let me know if the workaround works for you, and in case of any further questions feel free to contact us again!
The issue will remain open, and we will see in the future if this will be implemented.
Thanks again!

**Comment by okohll** [comment]
It's been a while but thanks for that reply @pawellysy, there's lots of useful info in there.

I must admit I can't get the delayed labels working on mine, it seems to want to re-start the whole rendering from scratch when you call update. However, it's not massively urgent, I can come back and try again another time.

One other thing I did manage to get working was that we have a particular network graph that's loaded whenever a particular page in our application is opened. However, it's a static preview so doesn't need to be re-calculated each time and doesn't need to be interactive. So what I did is the first time it's calculated, save its DOM to memory with jQuery.clone(). Then if it's loaded again, just append that DOM to the container, which is a lot faster.

**Comment by pawellysy** [comment]
If you have any troubles with getting it to work feel free to contact us via our dedicated support channels, which are listed here: https://www.highcharts.com/blog/support/ Our support engineers will be more than happy to help. Your second workaround sounds reasonable, if you don't need any live/responsive charts, this will do just great. Another thing could be just exporting the chart to SVG and serving the chart as a picture instead of the DOM element. 
Thanks for the comments!
