### ISSUE TITLE
API for Technical Indicators module

### ISSUE THREAD

**Issue by jackytanjq** [highcharts/highcharts#17072]
# Description of the feature

To have an API for the Technical Indicators module.
This is to allow server side service(s) to receive identical technical indicator's data as in the client's web browser's chart.

# Library related to the feature
Highcharts Stock

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by pawellysy** [comment]
Hi @jackytanjq, thanks for creating a ticket!
