### ISSUE TITLE
HC Map - unnecessary animation +wrong animation direction

### ISSUE THREAD

**Issue by Berti94** [highcharts/highcharts#17079]
#### Expected behaviour: 
- animation is expected to start from the center
- map is not re-animated if changing properties that don't justify re-animation (like datalabels on/off, datalabels color, etc)

#### Actual behaviour:
- wrong animation direction (animation starts from the left side)
- toggle data label causes re-animation
- toggle tooltips causes re-animation

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/w7pr5xmd/

**Comment by raf18seb** [comment]
Hi @Berti94,

Thank you for creating the ticket!

Actually, it can be controlled by the `animation` option, see the example docs:
https://api.highcharts.com/class-reference/Highcharts.Chart#update
https://api.highcharts.com/class-reference/Highcharts.Series#update
https://api.highcharts.com/class-reference/Highcharts.Chart#redraw

Demo: https://jsfiddle.net/BlackLabel/dtp6n1e2/

Closing as resolved but feel free to reopen or ask any further questions.
