### ISSUE TITLE
Highchart Line panning behavior problem.

### ISSUE THREAD

**Issue by ezat-dev** [highcharts/highcharts#17074]
#### Expected behaviour
Zoom by dragging on the Line Chart,
I tried to move left and right by setting panning to shift.

#### Actual behaviour
However, if you click and move instead of moving left and right, the graph is narrowed in that direction.

#### Live demo with steps to reproduce

**Example when tested with HighChart sample data.**
https://jsfiddle.net/smile02/3jgwdvy8/

**This is an example made with the data you want to apply.**
https://jsfiddle.net/smile02/v3hm1o8x/1/

#### Product version

Highchart v9.3.3
#### Affected browser(s)
chrome

**Comment by pawellysy** [comment]
Hello @ezat-dev, thanks for creating a ticket!

I can't reproduce your issue, everything seems to be working fine.
Could you describe reproduction steps more thoroughly?

https://jsfiddle.net/BlackLabel/Ld942bym/

How I tried to reproduce this bug: 
dragged the mouse while holding the mouse button pressed -> The part of chart was selected and zoomed.
dragged the mouse while holding the mouse button **and shift button** pressed -> The plot area was panned

https://user-images.githubusercontent.com/26306846/157724496-9cacbbb7-7046-42a5-b3ad-bed3d5419a02.mov


PS: Just to be absolutely sure, I hope you do understand that setting the `panKey: 'shift'` means, that you need to hold the shift button pressed to perform a panning?

API Reference: https://api.highcharts.com/highcharts/chart.panKey

**Comment by pawellysy** [comment]
Hi, thanks for the clarification!
I managed to reproduce this behavior.
Simplified demo: https://jsfiddle.net/BlackLabel/7rqaouhd/2/

`Internal Note`
The panning does not work properly when tickAmount is defined.

#### Workaround
Set ticks in some other way, and don't use tick amount
