### ISSUE TITLE
StockTools does not work under shadowDOM encapsulation

### ISSUE THREAD

**Issue by testfrontwebfg** [highcharts/highcharts#17083]
#### Expected behavior
StockTools should be able to run under a shadowDOM encapsulation.

#### Actual behaviour
It currently displays the toolbar. It works perfectly with any tooltip and selector but does not allow to add of any tool menu indicators or markers.

#### Live demo with steps to reproduce
![image](https://user-images.githubusercontent.com/67052293/158120650-c743535e-79b9-4385-a178-5d8eed356960.png)

https://jsfiddle.net/alvaro_diez/ho3sam1v/4/

#### Product version
v.10.0.0

#### Affected browser(s)
Tested on Chrome Version 99.0.4844.51 (Official Build) (64 bit)

Thanks in advance

Regards!

**Comment by karolkolodziej** [comment]
Thank you for reporting that issue!

Simplified demo: https://jsfiddle.net/BlackLabel/zfa7hkLn/
Demo without shadowDOM: https://jsfiddle.net/BlackLabel/w3vh74qx/

_Internal note:_
In `NavigationBindings` module, the `getElementsByClassName` doesn't return proper `container`.
https://github.com/highcharts/highcharts/blob/ba7d7b250f60d2bd44e8edf409713ddb161b5f98/ts/Extensions/Annotations/NavigationBindings.ts#L368-L371

**Comment by testfrontwebfg** [comment]
Do we know anything about this issue?
Thanks in advance!

**Comment by testfrontwebfg** [comment]
Thanks @pawellysy, much appreciated!
