### ISSUE TITLE
HTML comments break tooltip formatter with bypassHTMLFiltering flag on

### ISSUE THREAD

**Issue by joeveiga** [highcharts/highcharts#17089]
I have a use case were tooltips' HTML content is automatically generated by a tool (angular compiler). The content includes custom HTML element tags, so I need `bypassHTMLFiltering` on. However, this is causing comments in the autogenerated content to break the application. FYI, these comments are generated by the tool and I can't just remove them. This worked fine before upgrading to v10 (from v8).
Thanks.

```ts
// NOTE: if we don't bypass filtering then comments work as expected
Highcharts.AST.bypassHTMLFiltering = true;

Highcharts.chart('container', {
    xAxis: {
    	categories: ['Apples', 'Pears', 'Bananas', 'Oranges']
    },
    series: [{
        data: [1, 4, 3, 5],
        type: 'column'
    }],
    
    tooltip: {
      useHTML: true,
      formatter: () => `
        <!-- this comment DOES NOT break the tooltip -->
        <div>
          <!-- this one DOES break the tooltip -->
          Tooltip content!
        </div>
      `,
    },
});
```

#### Expected behaviour

Custom `tooltip.formatter` function works as expected (it parsed the comments successfully in version 8 of the library).

#### Actual behaviour

Exception is thrown:
```
Uncaught DOMException: Failed to execute 'createElementNS' on 'Document': The qualified name provided ('#comment') contains the invalid name-start character '#'.
    at https://code.highcharts.com/highcharts.js:59:79
    at Array.forEach (<anonymous>)
    at e (https://code.highcharts.com/highcharts.js:58:404)
    at https://code.highcharts.com/highcharts.js:59:338
    at Array.forEach (<anonymous>)
    at e (https://code.highcharts.com/highcharts.js:58:404)
    at h.addToDOM (https://code.highcharts.com/highcharts.js:59:466)
    at Function.h.setElementHTML (https://code.highcharts.com/highcharts.js:58:331)
    at a.h.textSetter (https://code.highcharts.com/highcharts.js:155:3)
    at a.<anonymous> (https://code.highcharts.com/highcharts.js:76:248)
```

#### Live demo with steps to reproduce

https://jsfiddle.net/k7vxy1j9/4/

Hover over the series to show the tooltip.

#### Product version

`"highcharts": "^10.0.0"`

#### Affected browser(s)
Chrome Version 99.0.4844.51 (Official Build) (x86_64)

**Comment by raf18seb** [comment]
Hi @joeveiga, thanks for reporting the issue!

Seems like a `#comment` is one of the invalid tag names.
A simple workaround would be to exclude it from creating by `createElementNS` just the same as `#text` is excluded: https://jsfiddle.net/BlackLabel/yubot81n/

**Comment by joeveiga** [comment]
Thank you @raf18seb!
Since it looks like a straightforward fix, are there plans to include it in a future release 🙏 ? The workaround, well, works :), but I'd rather not have my own version of `AST.prototype.addToDOM` (specially since, so far, version 8 is working fine).

**Comment by raf18seb** [comment]
Hi @joeveiga,

of course. We don't have ETA for fixing it yet, but it will be added eventually to the core.
However, note that this fix might not be feasible and final - we might come up on something better than filtering `#comment` or other tags with `#`.
Also be aware that, with the above solution, the comment will not be added to DOM.

**Comment by joeveiga** [comment]
Hey @raf18seb that's great, thanks! Yeah I understand, I'll keep an eye on it 👍 . As far as removing the comments, that wouldn't affect my particular usecase, but if there's a way to keep them that'd be ideal. Maybe the user had their reasons to add them (perhaps some runtime tool needs them for whatever reason 🤷 ). I think that should be an even less common edge case though. Anyways, thank you! And let me know how I can help.
