### ISSUE TITLE
Regarding Graph

### ISSUE THREAD

**Issue by teraiyamayurcontact** [highcharts/highcharts#17088]

**Comment by raf18seb** [comment]
Hi @teraiyamayurcontact,

thank you for writing to us. GitHub is our bugs and features tracker only. With any support questions, please contact us on our dedicated support channels listed here: https://www.highcharts.com/blog/support/
More info: https://github.com/highcharts/highcharts/blob/master/repo-guidelines.md#reporting-issues

When contacting our support engineers, please provide info about what feature exactly you'd like to have from the above demo (is it about rendering images or zones?).

Thank you for understanding.
