### ISSUE TITLE
mapline geometry-based data on a non-TopoJSON

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#17086]
#### Expected behaviour

The mapline should be rendered as it works with the TopoJSON map: https://jsfiddle.net/BlackLabel/cuqax7zk/

#### Actual behaviour

The mapline series doesn't appear: https://jsfiddle.net/BlackLabel/bwtf4arL/

**Comment by raf18seb** [comment]
Hi @Basts, thanks for reporting!

Tagging as a bug. An obvious workaround for now would be to use a new recommended TopoJSON map instead of GeoJSON.

**Comment by KacperMadej** [comment]
When using a non-TopoJSON with geometry types other than 'Point' the coordinates need to be using the same units as the coordinates used to create the underlying map.
Demo: https://jsfiddle.net/BlackLabel/bwtf4arL/5/

**Comment by raf18seb** [comment]
Thanks! Closing as resolved then.
