### ISSUE TITLE
some gridlines and crosshairs are partially rendered using highstock

### ISSUE THREAD

**Issue by ochristensen** [highcharts/highcharts#17097]
#### Expected behaviour
gridlines and crosshairs render consistently using Highstock
Highcharts works: https://jsfiddle.net/zenzizen/e5fy3aup/87/

#### Actual behaviour
https://jsfiddle.net/zenzizen/e5fy3aup/86/
Some gridlines have "gaps"/are blank as are crosshairs

#### Live demo with steps to reproduce
Associating a series with the axes seems to fix it.  I personally think that because there's no data, the gridlines shouldn't be there nor should the crosshairs (ie the ones with no data should render no gridlines nor crosshair.)

#### Product version
Latest

#### Affected browser(s)
Chrome at least, probably others

**Comment by karolkolodziej** [comment]
Let's consider the following cases:
1. Importing `highcharts` and using `chart` constructor: https://jsfiddle.net/BlackLabel/azhm172d/
2. Importing `highstock` and using `chart` constructor: https://jsfiddle.net/BlackLabel/09zLst1v/
3. Importing `highstock` and using `stockChart` constructor: https://jsfiddle.net/BlackLabel/smnp45uy/

Which of these in your opinion is the correct behaviour?
Each of these might be reasonably explained but I would like to see your point of view.

**Comment by ochristensen** [comment]
I did not consider the mixing and matching in the examples I used! 😊 

1. is at least consistent (and all I'm really looking for); gridlines and crosshair lines render in all quadrants
2. and 3. are both inconsistent - the upper left and lower right, despite having the same data (none), render differently.

I will need to continue to import highstock though because I'll eventually need to implement zooming and scrolling

**Comment by karolkolodziej** [comment]
Stock Chart creates separate panes for each pair of axes and this behaviour in my opinion is correct.

However, in my opinion, there should be no difference between charts no matter which module `highcharts/highstock` you are using. But let's seek advice from @pawelfus

**Comment by ochristensen** [comment]
yes - to be clear I don't really care what the end behavior is - but they should be consistent across highcharts/highstock and, more importantly, within the same chart

**Comment by karolkolodziej** [comment]
_Internal note:_
I think we should start by investigating further this issue and determine why there is a difference in `chart(...` between   `highcharts/highstock` module being used.
