### ISSUE TITLE
Bubble, series didn't show after drilldown.

### ISSUE THREAD

**Issue by hihajdus** [highcharts/highcharts#17096]
#### Expected behaviour
Series should be showing after drilldown.
https://jsfiddle.net/BlackLabel/behLmrox/

#### Actual behaviour
Series didn't show after drilldown, starting from v9.3.0 to up.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/behLmrox/1/

#### Product version
Highcharts [v9.3.0](https://github.com/highcharts/highcharts/releases/tag/v9.3.0)

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
`Internal note:`
 bisected to commit 004e63849840d944d79326831ee409e49ffe93e2
