### ISSUE TITLE
Stockchart mouse scroll to zoom

### ISSUE THREAD

**Issue by williamwongys** [highcharts/highcharts#17090]
In most stock chart application, zooming can be achieved using mouse scroll, i.e., by scrolling the mouse, more or less bars will be shown within the same window. 

[https://www.highcharts.com/forum/viewtopic.php?f=12&t=48321](url)

**Comment by pawellysy** [comment]
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/16658
