### ISSUE TITLE
Export issue of transparent gradient in styled mode

### ISSUE THREAD

**Issue by RostVY** [highcharts/highcharts#17093]
I have area chart in styled mode with semi-transparent gradient color of series.

I use offline exporting, but issue is reproducible in both modes - online and offline.

**Steps to reproduce:**

- Export chart as SVG, PNG and PDF

#### Expected behaviour
Exported image/PDF looks the same as chart in browser

#### Actual behaviour
Exported chart has black background instead of transparent gradient

#### Live demo with steps to reproduce
My implementation is very similar to the one of your examples and can be reproduced there:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/css/gradient/

#### Product version
10.0.0

#### Affected browser(s)
Chrome on Windows

**Comment by pawellysy** [comment]
Hi, @RostVY Thanks for creating an issue!
Similar to #17101 the same Workaround applies: Add `stop-color` and `stop-opacity` to the known `AST` tags. 
Additionally, you have to specify those tags for both gradients in defs. 

Check the following demo: https://jsfiddle.net/BlackLabel/2c5vdjo6/4/

`Internal Note`

The fix should probably be about extracting the gradient CSS styles and implementing them to `defs` .

**Comment by RostVY** [comment]
I have checked demo - PDF does not have gradient :(
![image](https://user-images.githubusercontent.com/428140/158874341-e850b8f2-dea7-48c8-b2d6-9cac1ec377b8.png)

**Comment by pawellysy** [comment]
The PDF exporting seems to be connected to bug with export server: https://github.com/highcharts/node-export-server/issues/328

**Comment by RostVY** [comment]
I believe it's not just server, because issue is also reproducible in offline mode using jspdf.

**Comment by pawellysy** [comment]
@RostVY this is why it is not connected to the main highcharts Package. You can continue the discussion in the thread shared above. 

PS: If the bug is reproducible without highcharts, then it is highly probable, that this bug is not connected to highcharts, but the external library. Thanks for the information!

PS2: Currently we are in the process of testing/releasing a new export server version. After the release, we will check all the bugs, if they were fixed together with the new release.

**Comment by TorsteinHonsi** [comment]
The demo is actually not set up well - it puts the colors inline. In accordance with `styledMode` practice, the stops should have class names and the colors be defined in CSS. See https://jsfiddle.net/highcharts/jpsv43kL/ .

The problem now is that the stop colors are not exported. I think this is resolved by Pawel's comment:

> The fix should probably be about extracting the gradient CSS styles and implementing them to defs . Another option would be to delete this line so that defs options aren't omitted by export server:
