### ISSUE TITLE
Weird ticks computing when min and max set

### ISSUE THREAD

**Issue by ThomasK0lasa** [highcharts/highcharts#17098]
#### Expected behaviour
To set ticks same as without min and max.

#### Actual behaviour
Wrong tick computation. The value for min and max are same as in data serie, but the ticks rendered are different then without the setting of min and max.

#### Live demo with steps to reproduce
Check out the demo. You can see that y axis max tick is computed as 200 and you have large white space in chart. But when You comment out the max and min lines You will have proper max and min.  This happens only for certain numbers so I think some recalculations are wrong.
[https://jsfiddle.net/2mn8yd0k/2/](https://jsfiddle.net/2mn8yd0k/2/)

#### Product version
Highcharts JS v10.0.0 (2022-03-07)

#### Affected browser(s)
Chrome  99.0.4844.51

**Comment by karolkolodziej** [comment]
Thank you for reporting that issue but it is not a bug. 

As you might read in the [yAxis.max API documentation](https://api.highcharts.com/highcharts/yAxis.max):
- If the `endOnTick: true` (which is by default true) the axis max might not be exactly as you set it but it might be slightly rounded up.
- Additionally, in your example, the `tickAmount` is set which forces the chart to recalculate the extremes to evenly distribute the ticks thus max value is even bigger than what you declared.

After changing these two properties chart behaves as intended.
Demo: https://jsfiddle.net/BlackLabel/o0jn8a5m/

**Comment by ThomasK0lasa** [comment]
This is a bug. You didn't analyse the example enough. The slightly rounding - rounding 106.52 to 200? You can't treat this as good calculation.
When You remove the min and max and Highcharts will take the same min and max but from data serie. You get 106.52 rounded up to 120. And this is slightly rounded.
https://jsfiddle.net/muo4pa9c/

Also in the first example if You change the max from 106.52 to 112 You will get the 120 result and not 200.
https://jsfiddle.net/muo4pa9c/1/

So yes, this is a bug with calculating the max.

**Comment by ThomasK0lasa** [comment]
Also the endOnTick and changing tickAmount is not acceptable in my case (the way Your chart is displayed is unwanted). It's a bug with calculation for ONLY specific numbers. I will create this issue again if You won't reconsider this.

**Comment by ThomasK0lasa** [comment]
How can You treat rounding 100.52 to 200 not a bug?
https://jsfiddle.net/9yheb2wz/21/
