### ISSUE TITLE
lineWidth hover state for the mapLine series

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#17105]
# Description of the feature
Adding the interact capability/setting the `lineWidth` for the mapLine series from the `states.hover`.
https://api.highcharts.com/highmaps/series.mapline.states.hover

# Library related to the feature
Highcharts Map

# Live example for the feature
https://jsfiddle.net/BlackLabel/Lo6cbks1/

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by TorsteinHonsi** [comment]
Also, it is not documented (even though it works in normal state): Instead [borderWidth](https://api.highcharts.com/highmaps/plotOptions.mapline.borderWidth) is documented by inheritance from map, although it doesn't work.
