### ISSUE TITLE
Boost not showing zones properly for multiple series

### ISSUE THREAD

**Issue by TiankaiChen** [highcharts/highcharts#17108]
#### Expected behaviour
When boosting with multiple series, zone colours should show up properly

#### Actual behaviour
When boosting with multiple series, only the first series with zones is plotted. When deactivating and activating other series by clicking on the legend, it will cause the other series to show up (only for a few series). When trying the same for a chart with 400 series, activating and deactivating the series via the legend didn't do anything. 

#### Live demo with steps to reproduce
Created a simple demo with 3 series with 3 zones each.
(https://jsfiddle.net/xmw2ptba/)

#### Affected browser(s)
Chrome

**Comment by pawellysy** [comment]
Hello, @TiankaiChen Thanks for reporting this issue!

Simplified demo: https://jsfiddle.net/BlackLabel/qbpagmrv/1/

**Comment by SugarLin** [comment]
Hi, is there any workaround for this issue? This is still happening in Highcharts version 10.
When one or more series has zones defined in chart options, the chart will render only first series initially. But it renders correctly when resize the browser or any other action on the chart.

**Comment by raf18seb** [comment]
Simplified even more, new showcase: https://jsfiddle.net/BlackLabel/vLmfxteh/

Workaround (change the chart's size on load): https://jsfiddle.net/BlackLabel/ks6p3ocw/
```js
chart: {
    events: {
        load() {
            this.setSize(1);
            this.setSize(null);
        }
    }
},
```

@SugarLin unfortunately, we don't have a solution for it at this moment. We'll try to prioritize this ticket in the nearest future.

**Comment by markzolotoy** [comment]
Any resolution for that bug? This is a MAJOR disappointment in the product. After almost a year of development this bug is a dealbreaker. We cannot release a product without coloring series into different colors. And we cannot stop using Boost since we are rendering up to 15 millions of datapoints.

**Comment by markzolotoy** [comment]
And the provided workaround only works for the initial load. Is there any workaround for the case when series are added at the runtime?

**Comment by hubertkozik** [comment]
Hi @markzolotoy! From what I found, this issue has been fixed in Highcharts v11.2.0 more specifically by this commit: 1a6e1952a497c7ab2f79f331adba8de795f35746 Here's the Pull Request: https://github.com/highcharts/highcharts/pull/19504

You can check the demo with usage of the latest Highcharts: https://jsfiddle.net/BlackLabel/gywr176f/ zones are properly added for multiple series when using the boost module.

**Comment by meteor91** [comment]
@hubertkozik there are gradient in chart lines in your example when some zone start and end. Looks not like as expected

**Comment by hubertkozik** [comment]
Hi @meteor91! This is a desired default behaviour, gradient should be seen on the line after setting zones with the usage of the boost module.

**Comment by meteor91** [comment]
@hubertkozik is it possible to remove color gradient between two zones? If there is no markers between zones it's unclear where it starts or ends

example without markers: https://jsfiddle.net/x7r6mvs9/

**Comment by hubertkozik** [comment]
@meteor91 We use GitHub as a tool for bugs/feature request tracking and your question is strictly a support question. Feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
