### ISSUE TITLE
API docs not building consistently

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#17106]
Some options are added correctly (showing with correct default values) like 
https://github.com/highcharts/highcharts/blob/028c553b32bf5c4b04e7c2474dc30b90e4cbae42/ts/Series/Map/MapSeries.ts#L170-L179

while others do not. `animation` should be `false` on `plotOptions.map`
https://github.com/highcharts/highcharts/blob/028c553b32bf5c4b04e7c2474dc30b90e4cbae42/ts/Series/Map/MapSeries.ts#L181

but it shows as an object:
https://api.highcharts.com/highmaps/plotOptions.map.animation
```js
animation:{
  defer:0
  duration:1000
}
```

[`plotOptions.map.dataLabels.formatter`](https://api.highcharts.com/highmaps/plotOptions.map.dataLabels.formatter) in code looks like
https://github.com/highcharts/highcharts/blob/028c553b32bf5c4b04e7c2474dc30b90e4cbae42/ts/Series/Map/MapSeries.ts#L183-L190

but in the API docs is `undefined`.

**Comment by raf18seb** [comment]
A similar ticket where default values in code are different from what API says: https://github.com/highcharts/highcharts/issues/16857

**Comment by bre1470** [comment]
Default values will not inherit because we then have lot of faulty defaults. If values are not in the following code line, they have to be defined with `@default` in a leading doclet above. When it comes to types, define it if you expect a narrowed version of the inheritance.

**Comment by bre1470** [comment]
@KacperMadej I am now looking ones more into it.

Tests her show that the parse is detecting everything as expected.
So I wonder if this is something about the API documentation.
Do you expect to `plotOptions.map.animation` to not be available, or is the rendering of the navigation tree the issue?

To the second part: Formatter code has to be set in a doclet with `@default`. It will not be extracted.
`undefined` is the default for non-primitives.

**Comment by KacperMadej** [comment]
The animation value is built correctly locally and thank you for explaining the second part.
All is good or clear - closing as resolved.
