### ISSUE TITLE
Update method doesn't update network graph series

### ISSUE THREAD

**Issue by bm64** [highcharts/highcharts#17115]
#### Expected behaviour
Update method should update network graph series

#### Actual behaviour
Update method doesn't update network graph series

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/x6mqw4ho/

#### Product version
Works correctly in 8.2.2. Most likely broken since 9.0.0
https://jsfiddle.net/BlackLabel/2jhf8ydc/

#### Affected browser(s)
N/A

**Comment by raf18seb** [comment]
Hi @bm64, thanks for reporting!

`Internal note:`
Unable to bisect.
Workaround: update nodes manually: https://jsfiddle.net/BlackLabel/ywo49ze7/
