### ISSUE TITLE
Mapbubble series disappears when doing setData with updatePoints: false

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#17112]
#### Expected behaviour
setData working correctly: https://jsfiddle.net/BlackLabel/5r4skban/

#### Actual behaviour
setData with `updatePoints: false` flag isn't working (points are destroyed and created without graphics): https://jsfiddle.net/BlackLabel/hcrqyx34/

#### Product version
Highcharts Maps 10.0.0
Worked fine in 9.2.2, broken since 9.3.0

**Comment by KacperMadej** [comment]
To skip arguments `undefined` or `void 0` are working fine while `null` is not - https://jsfiddle.net/BlackLabel/hcrqyx34/1/
Alternatively, call `chart.redraw` after the changes without redraw.
