### ISSUE TITLE
Stack labels on graphs - when legend is on the right & there are negative values, stack labels include the legend width when trying to align themselves

### ISSUE THREAD

**Issue by KurveLauren** [highcharts/highcharts#17116]
#### Expected behaviour
I should see my labels aligned at the end of each bar

#### Actual behaviour
When the legend is on the right and there are values that are negative, the stack labels seem to include the legend width when trying to align themselves, which is causing so much space on the right of the smaller bars and the labels don't show for the largest one.

#### Live demo with steps to reproduce
http://jsfiddle.net/guwefdac/2/

#### Product version
Highcharts v8.2 & v10

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hi KurveLauden, thanks for reporting a bug!

simplified demo: https://jsfiddle.net/BlackLabel/ckrw7spt/2/

`Internal Note`

The position of the label is wrongly calculated here: https://github.com/highcharts/highcharts/blob/1fe90eb38bf5508116c69b1848791f2c75e56738/ts/Extensions/Stacking.ts#L382
