### ISSUE TITLE
resetZoomButton text aliment issue

### ISSUE THREAD

**Issue by webdevnerdstuff** [highcharts/highcharts#17127]
#### Expected behaviour
The text should be in the center of the button.

#### Actual behaviour
The text is aligned at the bottom of the button and looks like its misaligned. This will vary from computer to computer. It should be consistent no matter what computer, browser, or zoom level being used.

#### Live demo with steps to reproduce
[HighCharts Own Demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/zoombysingletouch)

#### Product version
9.3.3 & 10.0.0 (two that I checked)

#### Affected browser(s)
Chrome Version 99.0.4844.83 (Official Build) (x86_64)

All of the following screenshots were at 100% zoom level.

For me:
![image](https://user-images.githubusercontent.com/14927668/160029822-a5c0573f-c361-49c5-98fa-e770a8bff159.png)

I had a friend also check and for her it was top aligned
![image](https://user-images.githubusercontent.com/14927668/160028612-7ce314fa-9364-4126-8cdf-d1423bd697f1.png)

Then checked with another friend, and for him it looked correct.

**Comment by pawellysy** [comment]
Hello @webdevnerdstuff, thanks for reporting a bug!
Could you provide some further details, like an OS type, its version? 
On my computer (macOS Monterey 12.2.1, Chrome Version 99.0.4844.51 (Official Build) (x86_64)) The reset button seems fine.

**Comment by webdevnerdstuff** [comment]
@pawellysy I'm on Mac OS 10.15.7 (19H1615). My friend who I got that second screenshot from is on Windows 11. My friend where it look correct is on Window 10.
