### ISSUE TITLE
X axis tick labels are seen overlapping, if it contains more than one word.

### ISSUE THREAD

**Issue by PurvaK17** [highcharts/highcharts#17123]
#### Expected behaviour
X axis tick labels should not overlap, if it contains more than one word.

#### Actual behaviour
X axis tick labels are seen overlapping, if it contains more than one word.

#### Live demo with steps to reproduce
https://jsfiddle.net/v8ma0kxo/

#### Affected browser(s)
Safari

**Comment by pawellysy** [comment]
Hi, @PurvaK17 thanks for reporting a bug!
