### ISSUE TITLE
NavigationButtonOptions no longer has verticalAlign property

### ISSUE THREAD

**Issue by mjchang** [highcharts/highcharts#17138]
#### Expected behaviour
Highchart Option's `navigation.buttonOptions` **type** should have `verticalAlign property`

#### Actual behaviour
Highchart Option's `navigation.buttonOptions` **type** no longer has `verticalAlign` property. However, this is still a valid property as demonstrated by this [fiddle](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/navigation/buttonoptions-verticalalign/). This property got removed from the typings in v9.3.0 - it was still working in v9.2.2.

#### Live demo with steps to reproduce
The following jsfiddle still works the move the navigation menu to the bottom yet the typescript typings don't support it
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/navigation/buttonoptions-verticalalign/

#### Product version

Highcharts v10

#### Affected browser(s)
N/A

**Comment by pawellysy** [comment]
Hello @mjchang, thank you for reporting the bug. 
This option is also missing from the API: https://api.highcharts.com/highcharts/navigation.buttonOptions

`Internal Note`

Probably all of the options listed below are available through API: https://github.com/highcharts/highcharts/blob/53b04dca4c74d0092f691ce36a3c9a7a6ddeba90/ts/Extensions/Exporting/ExportingOptions.d.ts#L62-L86

Needs to be checked and also added to the API and TS typings.
