### ISSUE TITLE
Venn: Uncaught TypeError Cannot read properties of undefined

### ISSUE THREAD

**Issue by abhitalks** [highcharts/highcharts#17142]
#### Expected behaviour

Simple Venn diagram with no overlaps should show as discrete circles. 

Live working demo: https://jsfiddle.net/abhitalks/tf9z24ur/

#### Actual behaviour

Simple Venn diagram exactly the same as above, but with three data points throws a console error:

```
venn.js:24 Uncaught TypeError: Cannot read properties of undefined (reading '<_insert first string in set_>')
    at b.reduce.loss (venn.js:24:85)
    at Array.reduce (<anonymous>)
    at venn.js:24:36
    at Array.forEach (<anonymous>)
    at Object.layoutGreedyVenn (venn.js:23:502)
    at Function.f.layout (venn.js:31:347)
    at f.translate (venn.js:35:81)
    at highcharts.js:393:509
    at Array.forEach (<anonymous>)
    at a.renderSeries (highcharts.js:393:487)
```

#### Live demo with steps to reproduce

template used [^1]

Demo to repro with console error: https://jsfiddle.net/abhitalks/sbyc0auf/

#### Product version

Latest from CDN: `https://code.highcharts.com/...`

#### Affected browser(s)
Chrome Version 99.0.4844.84, 
Edge Version 99.0.1150.55.

On Firefox v92.0.1 the console error is: `Uncaught TypeError: h is undefined H venn.src.js:1115`

Other browsers, not tested.

[^1]: (based on official Venn template here: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/venn-diagram)

**Comment by pawellysy** [comment]
Hello @abhitalks, thanks for reporting a bug!

**Comment by raf18seb** [comment]
Simplified demo: https://jsfiddle.net/BlackLabel/48j02nrs/
