### ISSUE TITLE
Highchart synchronization graph zoom

### ISSUE THREAD

**Issue by ksgowthamks** [highcharts/highcharts#17152]
We have 3 graphs added to the chart list. 
1st and 3rd graph has daily data, so it has the single data point per day(x axis)
2nd graph has the minute wise data, so its has many data points per day

**while applying zoom it's zooming based on the data points currently. But we need based on the drag area date range.**

**Could you suggest us the solution?**

Reference screenshots:
Before zoom
<img width="629" alt="image" src="https://user-images.githubusercontent.com/7108320/161523513-e9f8781f-cc4f-4d0e-8ebc-3efe4aae47f1.png">

After zoom (here zoom applied from 30th Mar 20.00 to 31st 05.00 )
<img width="623" alt="image" src="https://user-images.githubusercontent.com/7108320/161523677-ba84091e-da36-4777-b1fd-cd68934b0658.png">

**Comment by karolkolodziej** [comment]
Thank you for contacting us.
We use GitHub to track bugs and feature requests. 
Your issue however looks like a typical support question.
Please prepare a demo with your issue in some online code editor and use [one of the available support channels ](https://www.highcharts.com/blog/support/)where our support engineers are going to help you with that.
