### ISSUE TITLE
Axis.update() causes a later Axis.remove() to cause chart.yAxis and chart.options.yAxis to get out of sync

### ISSUE THREAD

**Issue by nebain** [highcharts/highcharts#1715]
In the same vein as issue #1706, calling Axis.update() and then Axis.remove() causes chart.yAxis to get out of sync with chart.options.yAxis.

http://jsfiddle.net/AqpW9/3/

Do the following:
1. Remove y0 (removes y0 axis)
2. Grid y1 (updates y1 axis to add grid lines)
3. Remove y1
Now, chart.yAxis is left with y2, but chart.options.yAxis is left with y1.

**Comment by pawelfus** [comment]
+1
