### ISSUE TITLE
Ho can I give priority to one plot over another

### ISSUE THREAD

**Issue by chaxul** [highcharts/highcharts#17166]
#### Expected behaviour
there ate two plots with same value so plot-1 is covered by plot-2. I want plot-2 to be at top and plot-1 at bottom.

Can someone help me no this how can I give priority to plot-2 over plot-1. I want to show plot-2 at top or highlighted. 

#### Actual behaviour
Plot-2 is being covered by plot-1.

**Comment by pawellysy** [comment]
Hello @chaxul, thanks for contacting us with your question!
We use GitHub to track bugs and feature requests.
Your issue however looks like a typical support question.
Please prepare a demo with your issue in some online code editor and use [one of the available support channels ](https://www.highcharts.com/blog/support/)where our support engineers are going to help you with that.

PS: Did you check the series.zIndex option? https://jsfiddle.net/BlackLabel/9b1p5vkn/153/

**Comment by chaxul** [comment]
Thanks for this. Z-Index solved my issue.
