### ISSUE TITLE
Navigator handles are not moving 

### ISSUE THREAD

**Issue by tallam85** [highcharts/highcharts#1716]
Hi,

close navigator handles together and click scroll bar right/left corner to move the handles this case handles are not moving please look into the below link.....

http://jsfiddle.net/SjMyv/1/

![Navigator Handles](https://f.cloud.github.com/assets/1013702/372023/047ab8a0-a350-11e2-86d2-2cfa77a866ae.png)

**Comment by PaulDalek** [comment]
#### Behaviour
Problem still persists. Now clicking left or right arrow, when handles are very close to each other results in only one move in corresponding direction.

#### Live demos
http://jsfiddle.net/z04cf8dr/ - the newest version (v5.0.7)
http://jsfiddle.net/z04cf8dr/1/ - last working version (v4.2.5)

**Comment by EmileIndik** [comment]
Hi @KacperMadej,

Any idea about when this might get fixed?

Thank you!

**Comment by pawelfus** [comment]
**Workaround:**

Set `scrollbar.step` to higher value, for example `1`, demo: http://jsfiddle.net/z04cf8dr/6/
