### ISSUE TITLE
dragMinX not working properly in Gantt chart. Items disappear when dragging beyond dragMinX.

### ISSUE THREAD

**Issue by DavGer** [highcharts/highcharts#17163]
#### Expected behaviour
The drag/drop action should move the block to the minimum permitted `dragMinX ` position.

#### Actual behaviour
The drag/drop action beyond the `dragMinX ` position makes the items disappear.

#### Live demo with steps to reproduce
https://jsfiddle.net/mh65bnj2/
Drag the items to the left of the chart.

#### Product version
Latest Stable (see fiddle)

#### Affected browser(s)
Chrome 100.0.4896.60, Edge 100.0.1185.29, (Firefox not tested)

So if you go to the fiddle and drag any of the items to the left (beyond the `dragMinX ` value 2024-1-1) you can see that the items disappear. I am currently experiencing this issue so I made the fiddle to see if this issue occurs in a minimal version of the chart and it does.

Maybe I am missing some parameter to make it work but I suspect that setting `dragMinX ` should be enough.

**Comment by pawellysy** [comment]
Hello @DavGer, thanks for reporting a bug!
