### ISSUE TITLE
Wrong amount of points for series.type = 'flags' when series.cropThreshold is set to 0

### ISSUE THREAD

**Issue by jackytanjq** [highcharts/highcharts#17176]
#### Expected behaviour
The number of points for the series.type = 'flags' changes based on the chart's current extremes (viewable) range.

#### Actual behaviour
No change in the points array size for series.type = 'flags' when series.cropThreshold is set to 0.

This causes another issue while attempting to draw an annotation _(eg. rectangleAnnotation)_ when the chart can be panned and has a flag outside the current extremes.
Because the X-axis coordinates returned by this function will be outside of the chart and Highcharts will end the drawing:
this.chart.pointer.getCoordinates(e)

#### Live demo with steps to reproduce

[https://jsfiddle.net/jackytanjq/8w61dyxr/1/](https://jsfiddle.net/jackytanjq/8w61dyxr/1/)
Steps: 
(i) Zoom into 1 of the flags _(Eg. From X-axis's value of 8 to 12 to view flag 2)_
(ii) Click on the button 'Log series.points.length' to see how many points are recognized by the chart.
(iii) Click on the button 'Set cropThreshold to 0'.
(iv) Click on the button 'Log series.points.length' to see how many points are recognized by the chart after the change.

#### Product version

Highcharts Stock.

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @jackytanjq 

This is expected behaviour. Scatter and Flag series don't have `cropThreshold` support (if it's listed in API, then it's a bug in API).

> This causes another issue while attempting to draw an annotation (eg. rectangleAnnotation) when the chart can be panned and has a flag outside the current extremes.

Could you please recreate this issue in jsFiddle? We will check this.

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/os63vntg/
Snippet:
```js
Highcharts.seriesTypes.flags.prototype.sorted = true
```

*Internal note:*
The issue is not related to Stock, nor to the Flag series. It's a general result of series with internal flag `sorted = false`: https://jsfiddle.net/jackytanjq/8w61dyxr/1/

**Comment by jackytanjq** [comment]
Hello @pawelfus ,

> This causes another issue while attempting to draw an annotation (eg. rectangleAnnotation) when the chart can be panned and has a flag outside the current extremes.

Kindly find the demo and the steps to replicate it below:
Demo: [https://jsfiddle.net/jackytanjq/6bn907za/](https://jsfiddle.net/jackytanjq/6bn907za/)
Steps:
(1) When zoomed all the way out with the 1st and last flag visible.
The drawings are working as intended.
(2) Change the chart's min max extremes by zooming into the last flag.
Unable to draw anything, as the drawing will be canceled on clicking the chart.
(3) Change the chart's min max extremes to the 1st flag.
The drawings are working as intended.
