### ISSUE TITLE
MapBubble incorrect type for joinBy option

### ISSUE THREAD

**Issue by EliMiX** [highcharts/highcharts#17189]
#### Expected behaviour
MapBubble series' joinBy option should have the type set as (string[]|string) like the rest of the series (e.g MapPoint)

#### Actual behaviour
joinBy in MapBubble options is defined as 'string'

#### Product version
10.0.0

#### Affected browser(s)
N/A

**Comment by raf18seb** [comment]
Hi @EliMiX, thanks for reporting!

The `string` type wasn't inherited because it was taken from a default value defined on a `mapbubble` series.
A simple doclet like the one below should be enough to fix it.
```js
/**
 * @type      {string|Array<string>}
 */
joinBy: 'hc-key',
```
