### ISSUE TITLE
chart.getCSV() doesn't add empty cells at the end of the row

### ISSUE THREAD

**Issue by mik-the-deutsch-dev** [highcharts/highcharts#17186]
`chart.getCSV()`  doesn't add empty cells at the end of the row. Although according to the CSV specification `"Within the header and each record, there may be one or more fields, separated by commas.  Each line should contain the same number of fields throughout the file."` Taken from [rfc4180](https://datatracker.ietf.org/doc/html/rfc4180#section-2). So there should be the same number of delimiters in every row. 

Most CSV parsers do still open the CSV like this. But this thing causes some trouble for the simple solutions, e.g. when you do not want to explicitly ask the user about the delimiter used, but to detect it automatically. If you cannot expect that a CSV has the same number of columns within every row, this adds more errors.

Imagine we have 2 series of points:

    A = [ [1, 0.1], [2, 0.2], [3,0.3] ]
    B = [ [2, 0.5], [4, 1.0] ]  

#### Expected behavior (expected CSV output)
- all rows have equal number of cells  
    
      x,A,B
      1,0.1,
      2,0.2,0.5
      3,0.3,
      4,,1.0

#### Actual behavior

- rows with `x=1` and `x=3` have 2 cells, other rows have 3 cells  

      x,A,B
      1,0.1
      2,0.2,0.5
      3,0.3
      4,,1.0

#### Live demo with steps to reproduce
- [https://jsfiddle.net/odjute63/1/](https://jsfiddle.net/odjute63/1/)

#### Product version
Highcharts 10.0.0 (latest)

#### Affected browser(s)
- all, but it is not a browser-dependent issue

**Comment by raf18seb** [comment]
Hi @mik-the-deutsch-dev, thanks for reporting the issue!

I agree, this should be treated as a bug.

For example, when the only points with `x: 4` is in the second series, then the SVG row has 3 cells: https://jsfiddle.net/BlackLabel/ftgsxpke/

But when we move that point to the first series, the same row has only 2 cells: https://jsfiddle.net/BlackLabel/v6qz20k8/

As a workaround, you can preprocess your data and add null points: https://jsfiddle.net/BlackLabel/xs70yp8k/

**Comment by mik-the-deutsch-dev** [comment]
Hi @raf18seb , thank you for quick response and for confirming the issue!

Yeah, your additional examples clearly show, that the problem exists only for the rows with empty cells at the end. Empty cells that are located between non-empty cells are created correctly.

Also thanks for the workaround. Unfortunately I have millions of points and my series are not categorized. X values are decimal numbers. So running a such a preprocessing for them will require too much work. But CSV export is not a key feature of the app, of course.

I've also created [a PR](https://github.com/highcharts/highcharts/pull/17195) with a quick fix. However, I am not 100% sure if such a solution is reliable for all use cases (but the tests succeeded 😃 )

**Comment by mik-the-deutsch-dev** [comment]
Thanks for an update!
