### ISSUE TITLE
series.linkedto - not all series are updated together with the series they are linked to

### ISSUE THREAD

**Issue by magdalena-gut** [highcharts/highcharts#17190]
#### Expected behaviour
All series linked to the updated series are updated as well.

#### Actual behaviour
The following demo shows three series. The first one - ohlc is updated by adding points. The are two other series:
- ppo linked to the ohlc,
- ema linked to the ppo.

Issue: the ppo series receives new points like the first, updated series which is linked to, whereas ema series does not.

**Demo:**
https://jsfiddle.net/BlackLabel/5jy97g3u/

#### Product version
Highstock v10.0.0 

#### Affected browser(s)
N/A

**Comment by pawelfus** [comment]
*Internal note:*
Indicators are bound to `updatedData` event. It seems that `indicator` series does not fire `updatedData` event when data is recalculated.

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/t7qd5v8j/

Plugin:
```js
(function(H) {
  H.wrap(
    H.seriesTypes.sma.prototype,
    'recalculateValues',
    function(proceed) {
      const ret = proceed.apply(this, Array.prototype.slice.call(arguments, 1));

      this.isDirtyData = true;

      return ret;
    }
  )
})(Highcharts);
```

*Internal note:*
Check why indicators set `isDirtyData` to false (bisect) and run tests
