### ISSUE TITLE
Chart.Height incorrectly implemented as double

### ISSUE THREAD

**Issue by Matt-Roberts-mondaq** [highcharts/highcharts#17196]
#### Expected behaviour
[Highsoft.Web.Mvc.Charts.Chart.Height](https://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_chart.html#a29a13af61c3741c5d1b0152efc29b9a8) is implemented as a double, where it should be implemented as a string. This would follow the implementation of Width being a string (and WidthNumber being a double) and would allow the use of % in the height value, for example.

#### Actual behaviour
Both Chart.Height and Chart.HeightNumber are doubles, meaning the developer only has the option of giving a number for their chart height.

**Comment by pawellysy** [comment]
Hi! @Matt-Roberts-mondaq thanks, thanks for reporting the issue.

FYI @brofixo

**Comment by brofixo** [comment]
@Matt-Roberts-mondaq 

It's a bug. 
It will be fixed with next release.
