### ISSUE TITLE
Enable zooming for organization chart

### ISSUE THREAD

**Issue by markzolotoy** [highcharts/highcharts#17193]
# Description of the feature
Select a group of nodes and replace cuurent view with the result of selection.

**Comment by raf18seb** [comment]
Hi @markzolotoy,

The organization chart has no axes, so standard zooming will not work.
I think something similar could be achieved using the [series.setData](https://api.highcharts.com/class-reference/Highcharts.Series#setData) method (find all points within a selection, filter data and set it).

**Comment by markzolotoy** [comment]
Standard or not, able to select multiple nodes and look into their relationship using maximum os available space is a good feature.
