### ISSUE TITLE
Legacy Documentation

### ISSUE THREAD

**Issue by ronaldroe** [highcharts/highcharts#17202]
Hello, sorry for deleting the template. There really wasn't a template that made sense to use for this.

I'm working on an older code base, and it uses version 6.1.2. Updating to a new highcharts version is not an option at the moment.

I'm just looking to view the documentation for that version. I've tried the Wayback Machine, but it fails to load the actual docs. Is there a standalone or maybe a guide I can use for that older documentation? Or maybe a point off in the right direction for what you all used back then (mid-2011) for your documentation parsing?

Thank you.

**Comment by pawellysy** [comment]
Hello, @ronaldroe thanks for your question! 
Sorry, but we are using GitHub as a bug/feature tracking tool. For support questions, please contact us via the available support channels, which are listed here: https://www.highcharts.com/blog/support/
Thank you for understanding!


PS: Check out this forum thread, where everything is explained: https://www.highcharts.com/forum/viewtopic.php?f=9&t=45461

**Comment by ronaldroe** [comment]
@pawellysy Thank you. That linked worked. I will go to the forum if I have further questions
