### ISSUE TITLE
ScrollablePlotArea minHeight is not responsive in vertical Bar in highcharts-react

### ISSUE THREAD

**Issue by tkforce** [highcharts/highcharts#17203]
#### Expected behaviour
Both JS and React version of HC should be responsive to height changes and fill up the parent element. 

#### Actual behaviour
Only JS version is able to adjust according to height changes while React version is not.

#### Live demo with steps to reproduce

JS `highcharts` version:
https://jsfiddle.net/3yncsv2z/1/
React `highcharts-react-official` version
https://codesandbox.io/s/elated-jones-i5y7qo
#### Product version

Latest version

#### Affected browser(s)
Chrome, FF, Safari

**Comment by pawellysy** [comment]
Hello @tkforce, thanks for reporting the issue. 
When you are creating the chart in the react using Highcharts react wrapper, the wrapper additionally creates one more div element, which has its own style. You have to apply the `height: 100%` property to this div as well if you want it to have the same effect as in the vanilla js version. 

You can use the `container-props` property, which you can pass to the `<Highcharts-react>` component.

API Reference: https://github.com/highcharts/highcharts-react#options-details

Here is a Live demo: 
https://codesandbox.io/s/nifty-fire-yfu2f2
