### ISSUE TITLE
`chart.update` method is unable to update chart options correctly

### ISSUE THREAD

**Issue by rdp1414** [highcharts/highcharts#17204]
We have 2 sets of chart options:
1. `singleYAxisConfig` - It contains multiple series (3 series) on a single yAxis.
2. `multiYAxesConfig` - It contains multiple yAxes (2 yAxes - `primary` on left-side and `secondary` on right-side) and one series plotted per yAxis.

Now,
1. Suppose chart is initially rendered with `multiYAxesConfig` and upon a button click (click on `singleYAxis` button), intent is to switch to and show `singleYAxisConfig` using `chart.update(singleYAxisConfig)` method - See [fiddle1](https://jsfiddle.net/ktbwL2zj/):
    * Expected: It is expected that chart will show `singleYAxisConfig`.
    * Actual: But neither the 3rd series is shown (which is a part of `singleYAxisConfig`) and spurious multiple yAxes with titles are shown (which are not a part of `singleYAxisConfig`).
2. Vice-versa. chart is initially rendered with `singleYAxisConfig` and when trying to update to `multiYAxesConfig`  using `chart.update(multiYAxesConfig)` method (upon clicking on `multiYAxes` button) - See [fiddle2](https://jsfiddle.net/tvs1ah6n/):
    * Expected: It is expected that chart will show `multiYAxesConfig`.
    * Actual: But it neither shows multiple yAxes (actually it doesn't shows any yAxis) nor series which are part of `multiYAxesConfig`.

#### Product version
Highcharts `v10.0.0`

#### Affected browser(s)
Chrome

**Comment by rdp1414** [comment]
Thanks @karolkolodziej,

Your solution worked. Then I was wondering if it worked, then why not updating (reset + update which is more relevant to our use-cases) chart using methodology mentioned https://github.com/highcharts/highcharts/issues/14969#issuecomment-772399417 here works fine - See [fiddle](https://jsfiddle.net/ux3546fg/1/). It satisfies all 3 conditions you mentioned - enable `oneToOne`, `id` to each series and an explicit `yAxis` for `singleYAxisConfig`? The bug is - going from multiYAxes to singleYAxis works well but again coming back to multiYAxes shows wrong series data.

**Comment by rdp1414** [comment]
Also @karolkolodziej, can you please give some more insights about how, what `chart.currentOptions` does, its utility as it is not a public function as mentioned by @TorsteinHonsi, so, couldn't find any docs for it?

**Comment by karolkolodziej** [comment]
As Torstein previously mentioned, the `currentOptions` method is internal for the Responsive module and might not serve other purposes.
You can check how it works in the code [here](https://github.com/highcharts/highcharts/blob/9120a02cb32a0c0740c5e1f7eba2c9e3fe8f8f04/ts/Core/Responsive.ts#L171).

Additionally, I'm not sure why you would like to use the `resetAndUpdate` and add that extra complexity. 
Is there any reason why you would like to make it that way?

**Comment by rdp1414** [comment]
Hello @karolkolodziej,

> Additionally, I'm not sure why you would like to use the resetAndUpdate and add that extra complexity.
Is there any reason why you would like to make it that way?

1. Our use case: We use highcharts in a react-like 'declarative' way i.e. right now we are at a state say `multiYAxesConfig`, and user wants to update (without wanting to say any traces of previous state) to a new state say , then simply doing `chart.update(singleYAxisConfig)` doesn't quite work - See [fiddle](https://jsfiddle.net/079zrs8e/1/).
2. Among many issues the biggest is issue is things like `yAxis.title` and `title` don't get updated. To get around this we need to modify `singleYAxisConfig` to explicitly have certain properties as `null` i.e. `title.text: ''` and `yAxis.title.text: ''`. Now, doing is this is not possible for complex `configs`.
3. The title and yAxis.title updates correctly with `resetAndUpdate` - See [fiddle](https://jsfiddle.net/6dvq97pc/1/). Still this approach has other issues - To solve those issues I logged this bug report.
4. resetAndUpdate approach:
    1. Reset: Update the chart from current state to a blank slate.
    2. Update: Now, from that blank state update chart to the next desired state.
5. Now, destroying the original chart (unmounting and destroying) and creating a new chart (mounting and creating back from scratch) for every single update was working but causing many performance and lag issues. We were previously using this approach only. To solve those performance issues we logged https://github.com/highcharts/highcharts/issues/14969 issue and @TorsteinHonsi suggested that resetAndUpdate approach, which we have been using since then. But now new issues have surfaced up causing us to log this report to seek for a more robust and declarative way of doing resetAndUpdate.

**Comment by TorsteinHonsi** [comment]
Hi again @rdp1414, I found that the changing of the data series is caused by the series first being updated to the `undoOptions`, then to the new data. I have not completely figured out what happens, but I think that since we're creating new series (with new id's), we should just remove them from the `undoOptions` and reset the series once. Also, resetting `colorCounter` and similar is a good idea.

Those changes produce this function:
```js
let undoOptions = null;
// Suggested at https://github.com/highcharts/highcharts/issues/14969#issuecomment-772399417
const resetAndUpdate = (chart, options) => {
  // First undo the previous options
  if (undoOptions) {
    chart.collectionsWithUpdate.forEach(coll => delete undoOptions[coll]);
    
    chart.pointCount = chart.colorCounter = chart.symbolCounter = 0;
    chart.update(undoOptions, false, true);
  }
  // Prepare for next run
  undoOptions = chart.currentOptions(options);

  // Update
  chart.update(options, false, true);
  chart.redraw();
}
```

[See it live on jsFiddle](https://jsfiddle.net/highcharts/rsfodgp8/)

I hope this helps, and please let me know if there are remaining problems. 

I am not sure whether we should include this reset functionality in the core, or if so, what it should look like.

**Comment by rdp1414** [comment]
Hello @TorsteinHonsi,

Thanks for suggesting the solution. It seems to work. Just one question - What does `chart.collectionsWithUpdate` property store? I saw it returned an array of `['xAxis', 'yAxis', 'series', 'colorAxis']`.

**Comment by TorsteinHonsi** [comment]
The `collectionsWithUpdate` stores the properties affected by [oneToOne](https://api.highcharts.com/class-reference/Highcharts.Chart#update:~:text=redraw%20the%20chart.-,oneToOne,options%20will%20be%20matched%20by%20id%2C%20and%20the%20remaining%20ones%20removed.,-animation) in an update.

**Comment by rdp1414** [comment]
Hello @TorsteinHonsi,
[This will be slightly long update]

1. You suggested the solution in your last update which works correctly in fiddle - See [fiddle1](https://jsfiddle.net/o6049nb8/).
2. Unfortunately, in our project it is not feasible to create an empty chart and then update it with the initial config. 
```
const chart = Highcharts.chart('container', {});
resetAndUpdate(chart, multiYAxesConfig);
```
3. Our pre-processing, etc requires the initial config to be created in one go like `const chart = Highcharts.chart('container', multiYAxesConfig)`. Now the question is to how to get the initial undoOptions for the initial config is solved like below - See [fiddle3](https://jsfiddle.net/nLhswz9q/).
```
const empptyChart = Highcharts.chart('empty-chart', {});
undoOptions = empptyChart.currentOptions(multiYAxesConfig);
console.log('initial undoOptions', undoOptions);

const chart = Highcharts.chart('container', multiYAxesConfig);
```
4. Unfortunately, the above also doesn't work in our project; it works in fiddle.
5. But in the above technique, if `chart.collectionsWithUpdate.forEach(coll => delete undoOptions[coll])` is replaces by `chart.collectionsWithUpdate.forEach(coll => (undoOptions[coll]=[]))`, things work perfectly in our project - See [fiddle5](https://jsfiddle.net/dh46zr8u/).  I wanted to know why this could have happened?
6. The reason why we didn't go ahead with this solution is because it is not necessary that `coll` property is of `array-type`. `coll` is generally `xAxis`, `yAxis`, `series` - that is why it often works. But when `coll` is of `object-type` or some other type, then this will fail.
8. I think the overall update technique which is followed here is:
    a. Chart is in config1.
    b. Move chart to clean slate by `chart.update(undoOptions)`.
    c. Now, from clean slate, update chart to config2 by `chart.update(config2)`.
9. Now, when `delete coll` approach is followed, I see chart is not correctly moved to clean slate in step b - See [fiddle9](https://jsfiddle.net/nLhswz9q/1/). Blank chart is not seen.
10. And, when `coll=[]` approach is followed, I see chart is correctly moved to clean slate in step b - See [fiddle10](https://jsfiddle.net/dh46zr8u/2/). Blank chart is seen.
11. Maybe this is the reason that clean slate is not achieved causing updating to work incorrectly explaining point3 and point5.

Maybe someone with internal knowledge of highcharts can help to suggest something to the entire situation above.

**Comment by rdp1414** [comment]
1 more question:
Suppose, we have an empty chart `const chart = Highcharts.chart('contaier', {})`. Now, what is the significance of the object returned by `chart.currentOptions(config)`? Does it mean that what ever will be returned, if that will be applied to a chart whose current config is `config`, then it will take it back to empty chart state? Or something else?

**Comment by karolkolodziej** [comment]
@rdp1414 How about creating a chart with one go like:
```
const chart = Highcharts.chart('container', multiYAxesConfig)
```
 and adding the callback function to get the options
```TS
const chart = Highcharts.chart('container', multiYAxesConfig, function(){
  undoOptions = this.currentOptions(this.options);
});
```
Wouldn't that solve all your issues? Is that possible in your use case?
Demo: https://jsfiddle.net/BlackLabel/9k3szdpj/

**Comment by rdp1414** [comment]
Hello @TorsteinHonsi ,

The solution which you provided [here](https://github.com/highcharts/highcharts/issues/17204#issuecomment-1153741225) is raising error when we upgraded highcharts to `v11` - See screenshot 
![image](https://github.com/highcharts/highcharts/assets/48443806/b11332d6-0b2b-416a-8b70-b85cfc307191)

> Hi again @rdp1414, I found that the changing of the data series is caused by the series first being updated to the `undoOptions`, then to the new data. I have not completely figured out what happens, but I think that since we're creating new series (with new id's), we should just remove them from the `undoOptions` and reset the series once. Also, resetting `colorCounter` and similar is a good idea.
> 
> Those changes produce this function:
> 
> [See it live on jsFiddle](https://jsfiddle.net/highcharts/rsfodgp8/)
> 
> I hope this helps, and please let me know if there are remaining problems.
> 
> I am not sure whether we should include this reset functionality in the core, or if so, what it should look like.

In the above demo fiddle which you shared, there also the same error is raised in console - See screenshot 
![image](https://github.com/highcharts/highcharts/assets/48443806/1b9dbc94-fb69-43b6-9f64-5f375d30dfc0).

We use this particular function is used to render our charts, and our charts are not rendering only with `v11`. UX changes can be still dealt with, but chart not getting rendered is a stopper. The same above fiddle works correctly with `v10` - See [fiddle](https://jsfiddle.net/24Lad1cv/).

**Comment by TorsteinHonsi** [comment]
Hi,

I think this is a case when you should use the new `getOptions` function. See https://jsfiddle.net/highcharts/dfvrykbu/ .
