### ISSUE TITLE
StockChart set rangeSelector: enabled: false, navigator Left a small gap

### ISSUE THREAD

**Issue by Caesar454905970** [highcharts/highcharts#17212]
$.getJSON('https://data.jianshukeji.com/stock/history/000001', function (data) {
	if(data.code !== 1) {
		alert('读取股票数据失败！');
		return false;
	}
	data = data.data;
	// 去掉多余的数据
	Highcharts.each(data, function(d) {
		d.length = 2;
	});
	Highcharts.stockChart('container', {
		rangeSelector: {
			enabled: false
		},
		title: {
			text: '平安银行历史股价'
		},
		plotOptions: {
			series: {
				showInLegend: true
			}
		},
		xAxis: {
			min:data[0][0],
			max:data[0][0]+10000000000,
		},
		tooltip: {
			split: false,
			shared: true
		},
		series: [{
			// type: 'line',
			id: '000001',
			name: '平安银行',
			data: data
		}]
	});
});
![image](https://user-images.githubusercontent.com/67094278/164986211-ef37faf5-45d3-48eb-9f66-25a49204affc.png)

**Comment by pawellysy** [comment]
hello, @Caesar454905970, thanks for creating the issue. 
I am not quite sure what you mean. What small gap do you mean? 
I tried to reproduce both charts with and without the  `rangeSelector`, and they both look the same to me.
https://jsfiddle.net/BlackLabel/023ckqjL/

Could you please try to reproduce your example in the demo I shared above?

**Comment by Caesar454905970** [comment]
> 你好，@Caesar454905970，感谢您创建问题。 我不太确定你的意思。你的意思是什么小差距？ 我尝试重现带有和不带有 的图表 `rangeSelector`，它们在我看来都是一样的。 https://jsfiddle.net/BlackLabel/023ckqjL/
> 
> 您能否尝试在我上面分享的演示中重现您的示例？

**Comment by Caesar454905970** [comment]
thank you! ;
https://jsfiddle.net/Caesar454905970/pew9fhd4/3/;
I can drag it to the left by default;I don't think he's far left
My screen is 1920*1080;scaling is 100%;

**Comment by Caesar454905970** [comment]
@pawellysy

**Comment by pawellysy** [comment]
@Caesar454905970, why did you close the ticket? Is it no longer viable for me to look at? 
Apart from that, I don't quite understand what you mean by 'it' and 'he' in the message above. Do you refer to the navigator handles?
Sorry, but I don't see much difference between the example I shared and yours. Could you pinpoint the differences, please?

**Comment by Caesar454905970** [comment]
In my case,scrollbar can drag it to the left;
but,The effect I want is the starting point and cannot move to the left;
![vsxkk-luuml](https://user-images.githubusercontent.com/67094278/165249862-531885f3-84c6-4e81-8ad3-9fd6ffdab51e.gif)

**Comment by Caesar454905970** [comment]
@pawellysy

**Comment by Caesar454905970** [comment]
@pawellysy,Sorry, I made a mistake,I turned it back on,My answer is up there

**Comment by pawellysy** [comment]
Hi, @Caesar454905970 sorry that I took so long to reply. 
simplified demo: https://jsfiddle.net/BlackLabel/odsqvp8x/4/


`Internal Note:`

The `dataMin` property of the navigator xAxis is wrongly calculated at the first render.
#### Workaround: 
You can call `chart.reflow()` after the chart is loaded to make the chart calculate the `dataMin` value of the Navigator axis one more time.
https://jsfiddle.net/BlackLabel/odsqvp8x/5/

**Comment by kamil-musialowski** [comment]
_Internal note:_ Possible regression, last good tag - **v9.0.1**, first bad tag - **v9.1.0**. 
Unfortunately, I wasn't able to bisect it due to some git bisect and utils bisect problems.
