### ISSUE TITLE
stockChart navigator can not Locate to the starting point,I can pull him to the left

### ISSUE THREAD

**Issue by Caesar454905970** [highcharts/highcharts#17226]
![jifhs-s57o3](https://user-images.githubusercontent.com/67094278/165710845-8f11d45c-2678-4360-9d1d-c95f3005e3ea.gif)

Here's my example:
https://jsfiddle.net/Caesar454905970/pew9fhd4/5/

I can't place the starting point very well

**Comment by pawellysy** [comment]
Hello @Caesar454905970 , thanks for reporting this issue. We are still working on the issue, that you reported here: https://github.com/highcharts/highcharts/issues/17212, so I will close this issue as a Duplicate. Sorry for the inconvenience.
