### ISSUE TITLE
Needle in gauge chart not getting plotted properly

### ISSUE THREAD

**Issue by tanmayshah95** [highcharts/highcharts#17225]
#### Expected behaviour
Needle/Pointer should be properly visible for all values with diff combinations of start and end angles.

#### Actual behaviour
For values close to last tick and some angle combinations, dial pointer/needle is not visible properly.
After animation, half or full needle is not visible based on angles.
in attached fiddle, verify half needle seems to be hidden after animation.

#### Live demo with steps to reproduce
https://jsfiddle.net/tanmayshah95/r6a5j8ok/1/

#### Product version
latest

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hi, @tanmayshah95 thanks for reporting the bug!
Simplified demo: https://jsfiddle.net/BlackLabel/8sm7w04d/
