### ISSUE TITLE
Odd looking maps when series shadow is applied

### ISSUE THREAD

**Issue by goransle** [highcharts/highcharts#17232]
#### Expected behaviour
Maps should be easily readable with the sand-signika theme

#### Actual behaviour
The maps have a almost 3D effect that sometimes obscures data.
![image](https://user-images.githubusercontent.com/7478772/165927902-e903c53a-e28a-4d89-8c37-781deca73c29.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/goransle/es7j65gb/
See more at https://www.highcharts.com/demo/maps/sand-signika

#### Product version
Highmaps v10+, 9.3.3 seems unaffected

#### Affected browser(s)
Chrome, Safari, Firefox

**Comment by raf18seb** [comment]
Hi @goransle, thanks for reporting the issue!

It's caused by the `series.shadow` property.

Minimal demo: https://jsfiddle.net/BlackLabel/m49w18ob/
