### ISSUE TITLE
Highmaps panning on Y axis is inverted when using SVG paths as basemap

### ISSUE THREAD

**Issue by lionel87** [highcharts/highcharts#17238]
#### Expected behaviour
When I drag my zoomed map upwards the map should move upwards. When I drag downwars it should move downwards.
Like on any map service, eg Google Maps or previous versions of Highmaps.

#### Actual behaviour
When I drag my zoomed map upwards the map moving downwards. Inverted to the mouse movement.

The issue is only occuring when I use SVG paths to display the map.
For me the last known working version was 8.2.2.

#### Live demo with steps to reproduce
https://jsfiddle.net/82oyfr7k/

1. Zoom in
2. Start panning on Y axis

#### Product version
10.1.0

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi @lionel87, thank you for reporting a bug!

`Internal note:`
Might be related to https://github.com/highcharts/highcharts/issues/16810
Worked fine in 9.2.2, broken since 9.3.0

**Comment by kamil-musialowski** [comment]
_Internal note:_ `chart.panning.type` doesn't work in 9.3.0 and above.
