### ISSUE TITLE
scrollablePlotArea should work in both directions simultaneously 

### ISSUE THREAD

**Issue by ochristensen** [highcharts/highcharts#17233]
# Description of the feature
[scrollablePlotArea](https://api.highcharts.com/highcharts/chart.scrollablePlotArea) currently only supports scrolling the plot in one direction; it would be immensely more useful if it supported both.

# Library related to the feature
Highcharts / Highcharts Stock

- An example of what happens currently if both scrollablePlotArea.minHeight and scrollablePlotArea.minWidth are set simultaneously: https://jsfiddle.net/zenzizen/3c8nav2p/1/
- The trigger for this request: https://www.highcharts.com/forum/viewtopic.php?f=12&t=48537
----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by pawellysy** [comment]
Hello @ochristensen, thanks for creating the feature request!

**Comment by ParkerPosy** [comment]
@pawellysy what would it take to go about implementing this in a local override?

**Comment by pawellysy** [comment]
Hi @ParkerPosy, unfortunately, it is a bit complicated piece of code, and it is hard to provide a drop-in fix for a given feature. You'll have to wait until it will be officially developed and added to the main package. Sorry for the inconvenience!
