### ISSUE TITLE
Wrong definition of ExportingBeforePrintCallbackFunction

### ISSUE THREAD

**Issue by amiram** [highcharts/highcharts#17245]
According to API reference [here](https://api.highcharts.com/class-reference/Highcharts#.ExportingBeforePrintCallbackFunction) and typescript definition, beforePrint event gets two arguments, `chart` and `event`.
When running, I get one argument with `preventDefault`, `target` (the chart) and `type`.

#### Live demo with steps to reproduce
https://jsfiddle.net/kqsx8rbh/
Add a `console.log(arguments)` inside beforePrint

#### Product version
10.1.0

**Comment by pawellysy** [comment]
Hello @amiram, thanks for reporting this issue!
