### ISSUE TITLE
Drilldown chart throws an error and does not return to the original series when drilling up when zooming in before drilling down

### ISSUE THREAD

**Issue by ryanewtaylor** [highcharts/highcharts#17247]
#### Expected behaviour

When drilling up the chart should return to the original series and not throw an error.

#### Actual behaviour

When drilling up the chart does not return to the original series and throws the following error.

```
Uncaught TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at x (highcharts.src.js:1545:17)
    at k.destroy (highcharts.src.js:11364:17)
    at a.<anonymous> (drilldown.src.js:2237:40)
    at highcharts.src.js:1654:25
    at Array.forEach (<anonymous>)
    at z (highcharts.src.js:1651:17)
    at a.g.drillUp (drilldown.src.js:1681:21)
    at a.<anonymous> (drilldown.src.js:1792:17)
    at highcharts.src.js:1654:25
```

#### Live demo with steps to reproduce

To reproduce from the demo below

1. Open https://jsfiddle.net/iamrewt/18q9xamf/42/ in Chrome or Firefox
2. Open developer tools
3. Zoom in to the chart
4. Click any point
5. Click "TOP SERIES NAME" in the upper left corner to drill up
6. The chart will cease to return to the original series and throw the error shown above

#### Product version

Highcharts 10, Highstock 10

#### Affected browser(s)

Chrome, Firefox. Not tested in Edge.

#### Other notes

This appears to work in Highcharts 8 and is preventing us from migrating to Highcharts 10. Previously, we were blocked on this upgrade due to #16479 .

**Comment by pawellysy** [comment]
Hello @ryanewtaylor, Thanks for reporting this issue. 

The bug occurred in v9.0.0 and worked fine in v8.2.2, but it seems that the behavior changed after adding breadcrumbs. 

#### Workaround: 

Make sure that the element exists. 
https://jsfiddle.net/BlackLabel/sfux1t39/2/

**Comment by ryanewtaylor** [comment]
Thanks @pawellysy we'll try the workaround in our live environment. If that works, this will suffice until an official fix is in place. Should I continue watching this thread for updates on a patch?

**Comment by pawellysy** [comment]
@ryanewtaylor, let me know if the workaround works. If not, we will try to come up with something else. Yes, everything related to this issue will be posted in this thread.

**Comment by mkdudeja** [comment]
@[pawellysy](https://github.com/pawellysy) Thanks for the solution. It's working expected.

Waiting for the fixed to be merged.

Thanks
