### ISSUE TITLE
IE11 point drilldown doesn't work

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#17244]
#### Expected behaviour
When clicking on the column the point drilldown should kick in.

#### Actual behaviour
The point drilldown does not work for IE11

#### Live demo with steps to reproduce
Official drilldown demo: https://www.highcharts.com/demo/column-drilldown

#### Product version
v10.0.0
(worked in v7)
#### Affected browser(s)
IE11

**Comment by jpingree** [comment]
Please note this also doesn't work in Edge (IE Mode).
