### ISSUE TITLE
Highcharts renders invalid width and height into <g ...>...</g> elements

### ISSUE THREAD

**Issue by pgr1973** [highcharts/highcharts#17246]
#### Expected behaviour
Highcharts should render valid HTML

#### Actual behaviour
in some cases width/height attributes are rendered into `<g>`-elements, whch invalidates the html, and prevents a page to pass a11y-tests

#### Live demo with steps to reproduce
https://jsfiddle.net/pgr1973/7spq3enb/33/

When investigating the demo, right-click onto for instance the first red-colored bar and select "inspect".
Then you are shown the first <rect ..
The element containing it is this (invalid) one:

`<g class="highcharts-series highcharts-series-0 highcharts-bar-series highcharts-tracker" data-z-index="0.1" opacity="1" transform="translate(997,288) rotate(90) scale(-1,1) scale(1 1)" clip-path="url(#highcharts-nivremp-5-)" width="901" height="198" aria-hidden="false" role="group" tabindex="-1" aria-label="AAA, bar series 1 of 2 with 3 bars. X axis, categories." style="outline: none;">...`

The width and height attributes that highcharts renders into it are invalid html, which prevents the chart to be accessible.

This also applies to the second group-element (the one for the blue bars):
`<g class="highcharts-series highcharts-series-1 highcharts-bar-series highcharts-tracker" data-z-index="0.1" opacity="1" transform="translate(997,288) rotate(90) scale(-1,1) scale(1 1)" clip-path="url(#highcharts-nivremp-5-)" width="901" height="198" aria-hidden="false" role="group" tabindex="-1" aria-label="BBB, bar series 2 of 2 with 3 bars. X axis, categories." style="outline: none;">...`

Again invalid width/height attributes in the `<g>...</g>`

#### Product version
Highcharts ^10.0.0

#### Affected browser(s)
All

**Comment by oysteinmoseng** [comment]
So the issue here is that `width` and `height` are not allowed attributes of SVG `g` elements.

These elements are not usually added, but here is a minimal demo showing a case where they are: https://jsfiddle.net/L730fqtc/

It seems that it has to be a `bar` series - not `column`, and that the responsive rule has to be active.
