### ISSUE TITLE
Polygon for point selection

### ISSUE THREAD

**Issue by markzolotoy** [highcharts/highcharts#17241]
We are using a desktop product that has a polygon for point selection. Is that possible to do in Highcharts?

**Comment by pawellysy** [comment]
Hello, @markzolotoy  thanks for your question!
Sorry, but we are using GitHub as a bug/feature tracking tool. For support questions, please contact us via the available support channels, which are listed here: https://www.highcharts.com/blog/support/
Thank you for understanding!
