### ISSUE TITLE
Series Color is not updating in item series charts

### ISSUE THREAD

**Issue by SanjanaPriya** [highcharts/highcharts#17257]
In item series chart, on changing a data point's color, only the legend's symbol and connector's colors have changed.

JS Fiddle Reference :  https://jsfiddle.net/zmcr48q7/1/

**Comment by raf18seb** [comment]
Hi @SanjanaPriya, thank you for reporting a bug!

Simplified demo: https://jsfiddle.net/BlackLabel/xypcb1s6/
