### ISSUE TITLE
The linked series is not updated after the series it is linking to has been updated

### ISSUE THREAD

**Issue by chanr1th** [highcharts/highcharts#17255]
This problem may be caused by the `dataGrouping` in my custom `rangeSelector.buttons`
If I disable this `rangeSelector.buttons`, it is working fine.
But I cannot disable it, because I need to group weekly data.

#### Expected behaviour
The linked series must update following the series it is linking to.

#### Actual behaviour
The linked series is not update after the series it is linking to has been updated.

#### Live demo with steps to reproduce
https://jsfiddle.net/chanr1th/2xes7czh/22
Changing the symbol selection between "Apple" and "Half Apple" to see the defect

#### Product version
Highstock JS v10.1.0

#### Affected browser(s)
All browsers

**Comment by pawellysy** [comment]
Hello @chanr1th, thanks for reporting a bug. 
Simplified demo: https://jsfiddle.net/BlackLabel/y3posc8a/3/

### Workaround:
Update the indicator series as well with empty data. https://jsfiddle.net/BlackLabel/y3posc8a/4/

`Internal Note` 
The issue is probably connected to the `dataGrouping`.
