### ISSUE TITLE
/docs/maps/create-custom-maps - jsfiddle broken example

### ISSUE THREAD

**Issue by SendBeesToMars** [highcharts/highcharts#17253]
#### Expected behaviour
https://github.com/highcharts/highcharts/blob/master/docs/maps/create-custom-maps.md
at step 15 an example jsfiddle is presented: [jsfiddle.net/highcharts/TUy7x/1/](https://jsfiddle.net/highcharts/TUy7x/1/) running the fiddle would render the map

#### Actual behaviour
error: "<a class='gotoLine' href='#56:21'>56:21</a> Uncaught TypeError: $(...).highcharts is not a function"

#### Affected browser(s)
Chrome Version 100.0.4896.127 (Official Build) (64-bit)

**Comment by pawellysy** [comment]
Hello @SendBeesToMars, thanks for reporting the bug!

**Comment by raf18seb** [comment]
Workaround: change `http` to `https` in the `highmaps.js` source url https://jsfiddle.net/BlackLabel/ca9rmknf/

**Comment by mfilipiec** [comment]
@TorsteinHonsi has made changes so I think this can be closed.
