### ISSUE TITLE
y-axis exception when using addPoint

### ISSUE THREAD

**Issue by 4blacktea** [highcharts/highcharts#17278]
When making the series.addPoint method add a task with an id attribute to gantt, two identical tasks are created.
`
series.addPoint({
                start: start,
                //end: start + day,
                end: start + day * parseInt(coast),
                dependency: dependency ? dependency.id : undef,
                name: name,
                id: name
            });
`

![image](https://user-images.githubusercontent.com/81417218/167647569-949358ba-218b-47de-a30b-bc9f355ee3e6.png)

**Comment by pawellysy** [comment]
Hello, @4blacktea thanks for reporting the issue!
Could you share the example demo, where the issue is reproduced?
