### ISSUE TITLE
Heatmap colors don't have enough contrast

### ISSUE THREAD

**Issue by brunouber** [highcharts/highcharts#17273]
[Click to see a demo](https://codepen.io/brunouber/pen/vYdGGJb).

We've an heatmap like the one linked above.
We use `#CAE3DF`,  `#B5BFCD`, `#9F9EBC`, `#8B7FAC`, `#76609B`, `#61478C`, and `#4F2F7D` as background color, and do not set any data label color, so that as stated in the documentation, highcharts can use the color with maximum contrast.

We saw that highcharts uses Black text only for the first two colors `#CAE3DF`, and `#B5BFCD` - but it would have been better to use Black also on `#9F9EBC` and `#8B7FAC`.

<img width="444" alt="heatmap" src="https://user-images.githubusercontent.com/55399398/167415468-b49b8a52-e678-4a78-8aa3-1202c1b06413.png">

We used [this tool](https://contrast-grid.eightshapes.com/?version=1.1.0&background-colors=%23cae3df%2C%20Heatmap%20bg%201%0D%0A%23b5bfcd%2C%20Heatmap%20bg%202%0D%0A%239f9ebc%2C%20Heatmap%20bg%203%0D%0A%238b7fac%2C%20Heatmap%20bg%204%0D%0A%2376609b%2C%20Heatmap%20bg%205%0D%0A%2361478c%2C%20Heatmap%20bg%206%0D%0A%234f2f7d%2C%20Heatmap%20bg%207%0D%0A%0D%0A&foreground-colors=%23000%2C%20Heatmap%20label%0D%0A%23000%2C%20Heatmap%20label%0D%0A%23ffffff%2C%20Heatmap%20label%20%0D%0A%23ffffff%2C%20Heatmap%20label%20%0D%0A%23ffffff%2C%20Heatmap%20label%20%0D%0A%23ffffff%2C%20Heatmap%20label%20%0D%0A%23ffffff%2C%20Heatmap%20label%20&es-color-form__tile-size=compact&es-color-form__show-contrast=aaa&es-color-form__show-contrast=aa&es-color-form__show-contrast=aa18&es-color-form__show-contrast=dnp) to grade the color contrast.

**Comment by pawellysy** [comment]
Hello @brunouber, thanks for creating this issue.
The contrast color is chosen based on our internal function, which implementation you can find here: https://github.com/highcharts/highcharts/blob/12fb8dea0edb01e0395072851fd2d131d9b98cc3/ts/Core/Renderer/SVG/SVGRenderer.ts#L613-L637

As you can see, the coefficients were set to fit most of the cases, but can easily be adjusted for each case. Here is an example of how you can do it: https://jsfiddle.net/BlackLabel/guLd2nmy/4/

Also one of the prior discussions about `getContrast` function: #6216

I think that currently, this function does a pretty good job of choosing the correct contrast, so I will set the label `type: undecided`. 
What do you think @TorsteinHonsi?

**Comment by TorsteinHonsi** [comment]
We can probably tune the contrast algorithm more. In the other issue, I mentioned [dynamic weighting](https://github.com/highcharts/highcharts/issues/6216), but it doesn't seem that we went through with it. 

@pawellysy It would be interesting to dynamically generate a [color table](https://stackoverflow.com/questions/31612232/color-table-algorithm) with coverage of both hue, brightness and saturation, and see how our contrast function handles it. It may be that there are edge cases where we could improve.

**Comment by pawellysy** [comment]
Here is the demo of the color table: https://jsfiddle.net/BlackLabel/g7tq01np/7/
Most choices seem fine to me 🤔 

Maybe we should train [someone(something) to adjust the coefficient for us](https://www.youtube.com/watch?v=KtPpoMThKUs)? 😅

**Comment by TorsteinHonsi** [comment]
@pawellysy Awesome! That's a great help.  If we remove the `textOutline`, we get a better impression on how the text contrasts against its background: https://jsfiddle.net/highcharts/vcL9z1gd/ . Because the `textOutline` is black for white text and white for black text.

I agree some more of the labels should be black.

**Comment by TorsteinHonsi** [comment]
Here's an implementation of the `getContrast` function, using the W3C's _relative luminance_. It provides better contrast in my opinion: https://jsfiddle.net/highcharts/vcL9z1gd/1/

@oysteinmoseng In its current state, I used 0.45 as the threshold.

`return l > 0.45 ? '#000000' : '#FFFFFF'`

But as seen in the fiddle, arguably a lower threshold would provide better readability (in practice, more black text). Do you know how low we can set this  without violating the required 4.5:1 contrast?

**Comment by oysteinmoseng** [comment]
@TorsteinHonsi Because WCAG uses the same relative luminance for its contrast computation we could simply calculate that (see https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html#contrast-ratiodef)

Untested, but probably something like this:
```js
const useWhite = (whiteLuminance + 0.05) / (colorLuminance + 0.05) >
    (colorLuminance + 0.05) / (blackLuminance + 0.05);
```

Instead of using a fixed threshold we would then always pick the most contrasting of white or black.

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng If my eyes and monitor are correctly calibrated, this looks very good: https://jsfiddle.net/highcharts/vcL9z1gd/2/

PS:
> Seems the relative luminance of black might be 0
Yes. Used the 0.05 in the fiddle above.

**Comment by oysteinmoseng** [comment]
Looks great here too!
