### ISSUE TITLE
Bubble chart image symbols not scaled when point z value is below minimum

### ISSUE THREAD

**Issue by cebamps** [highcharts/highcharts#17281]
#### Expected behaviour
When a point in a bubble series is out of the zMin/zMax range for the series and uses an image symbol (`symbol: "url(...)"`), it should be skipped or displayed at a small size.
![Screenshot 2022-05-11 at 09 29 04](https://user-images.githubusercontent.com/12797742/167798579-8d3ce836-b078-435e-89be-a94894698b04.png)

#### Actual behaviour
The image is instead rendered at the wrong size and in the wrong place.
![Screenshot 2022-05-11 at 09 29 12](https://user-images.githubusercontent.com/12797742/167798599-76f28538-a579-4cc2-8652-dafd0f396637.png)

This error also appears in the console:
> Unexpected value NaN parsing y attribute.

Combined with #17280, points in bubble charts can easily fall out of range and trigger this bug if one of the series has a minimum z value of 0.

#### Live demo with steps to reproduce
https://jsfiddle.net/6v2a1ow4/

#### Product version
Highcharts v10.1.0

#### Affected browser(s)
Firefox, Chrome

**Comment by raf18seb** [comment]
Hi @cebamps, thank you for creating the ticket.

Workaround:
If `point.plotY` is not calculated, set it a fake value anyway: https://jsfiddle.net/BlackLabel/gtvjc2bd/

`Internal note:`
In the `translateBubble` method, `point.plotY` is not calculated (and this is good for both symbol as URL or a normal marker). Somewhere later, the normal symbol marker is handled correctly, whereas the URL symbol is not.
