### ISSUE TITLE
Piechart series shadow is not applied on update

### ISSUE THREAD

**Issue by Leonidas51** [highcharts/highcharts#17288]
#### Expected behaviour

When using `chart.update` to update series, new shadow should be applied to them from the options argument (if present).

#### Actual behaviour

Shadow is not applied.

#### Live demo with steps to reproduce
https://codepen.io/ElStaino/pen/NWyRjvm?editors=1011
Click on 'Update Chart' button.

#### Product version
Highcharts JS v10.1.0

#### Affected browser(s)
Google Chrome Version 100.0.4896.88 (Official Build) (x86_64)

**Comment by pawellysy** [comment]
Hello @Leonidas51, thanks for reporting this bug!
Simplified demo: https://jsfiddle.net/BlackLabel/g6xmskrd/

**Comment by raf18seb** [comment]
It's because `shadowGroup` is not preserved.

Workaround and a potential fix: preserve `shadowGroup`, line 30: https://jsfiddle.net/BlackLabel/vpLnh3w2/
