### ISSUE TITLE
Maps, remove point: point is not removed from the series.points array

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#17297]
#### Expected behaviour
Let's discuss a map chart with 3 data points. After `point.remove()` I expect the `series.points` array to be length of 2.

#### Actual behaviour
After `point.remove()`, the removed point's reference is still in the `series.points` array. The `series.points.length` is still 3

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/2udxkv3j/

#### Product version
Highcharts Maps 10.0.0 (worked fine in 9.3.3)
Regression after https://github.com/highcharts/highcharts/commit/91f9740ba172a3e48caac5963b1f7b6a66a645df

@TorsteinHonsi was that intended? (I think no)

**Comment by TorsteinHonsi** [comment]
@raf18seb Without digging deep in - no, I can't see that it was intended. Especially since these points are not tied up to `mapData`, they are just standalone lon/lat points.
