### ISSUE TITLE
I title of a pie chart disappears when the series has 2 data points and an update method is used

### ISSUE THREAD

**Issue by msshw** [highcharts/highcharts#17290]
#### Expected behaviour
The title is rendered when `chart.update` method is used and the series has only 2 data points

#### Actual behaviour
The title disappears when `chart.update` method is used and the series has only 2 data points. When another data point with a `null` value is added, the title gets rendered.

#### Live demo with steps to reproduce
Unfortunately, I couldn't reproduce it on JSFiddle

#### The initial config
``` js
...
       title: {
          floating: true,
          text: ` `,
          useHtml: true,
          verticalAlign: 'middle',
        },
        series: [
          {
            data: [
              {
                name: 'Slice 1',
                y: that.point1,
              },
              {
                name: 'Slice 2',
                y: that.point2
                },
            ],
          },
        ],
...
```

#### The update method 
``` js
...
       chart.update({
          title: {
            text: `<span class="title">€${total}</span>`,
          },
          series: {
            data: [
              {
                y: this.point1,
              },
              {
                y: this.point2,
              },
            ],
          },
        });
...
```
![image](https://user-images.githubusercontent.com/28812187/168251418-d7ef00de-bbe7-42e0-bd57-8562447f8962.png)

#### The update method with an extra data point
``` js
...
       chart.update({
          title: {
            text: `<span class="title">€${total}</span>`,
          },
          series: {
            data: [
              {
                y: this.point1,
              },
              {
                y: this.point2,
              },
              {
                y: null,
              },
            ],
          },
        });
...
```
![image](https://user-images.githubusercontent.com/28812187/168251038-622fcc55-fd3e-423a-b7ca-ffd672045da4.png)

#### Product version

`nuxt-highcharts@2.0.4` with `highcharts@10.0.0` on board

**Comment by pawellysy** [comment]
Hello @msshw thank you for reporting this issue.
I tried to reproduce this behaviour, but everything is working on my end: https://jsfiddle.net/BlackLabel/qm2dbspf/

Could you try to reproduce this behavior on the online editor (e.g. edit the demo above)?

Thanks!

**Comment by msshw** [comment]
Hey @pawellysy 

Thank you for trying to reproduce the issue. I can confirm, that the title is shown on the first load. The issue happens once the series data gets updated dynamically. In this case the title disappears in my case.

Unfortunately, I couldn't reproduce the bug in JSFiddle, it works there as expected.

I will close the issue.
