### ISSUE TITLE
Polar chart in Blazor

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#17292]
This question has been moved here from the Highcharts repo: https://github.com/highcharts/highcharts/issues/15553
All comments/questions from @EWChina999 have been merged and moved below:

Please share more examples for polar plots , scatter plot, thanks

I added
```
Chart=new Chart
    {
        Polar=true
    },
```
and
```
Credits = new Credits
    {
        Enabled = false
    },
Chart = new Chart
    {
        Polar = true
    },
```

And each of them does not work, please help me, thanks

this plot was made in asp.net with jQuery+HighCharts + ASP.NET form
![image](https://user-images.githubusercontent.com/23310742/168064761-48961e3d-cec0-4fbb-bd09-c244b164b46c.png)

If you can add "click event" to select one point , that is perfect. The below is what I did with jQuery

```<script type="text/javascript"> function chartselection(chartindex) { var chart = $('#container' + chartindex).highcharts(); var selectedPoints = chart.getSelectedPoints(); var selectedPointsStr = ""; selectedPoints.push(this); // now it's got all the points $.each(selectedPoints, function (i, value) { try { selectedPointsStr += value.category + "," + value.series.name + ";"; } catch (err) { } }); selectedPointsStr = selectedPointsStr.replace('undefined,', ''); if (selectedPointsStr.length > 0) { selectedPointsStr = selectedPointsStr.substring(0, selectedPointsStr.length - 1); } var xSelection = document.getElementById('<%= HiddenFieldChartSelection.ClientID%>'); xSelection.value = selectedPointsStr; if (selectedPointsStr.length > 0) { __doPostBack('DrillSelectedPoints', chartindex + "$" + selectedPointsStr); } } </script>```

I have no idea how to upload my files into github. Will try . I will introduce a little background. We often use Highcharts to make various charts , for example use scatter charts to show a product failure rate trend charts . If we want to see details for a specific point we select to drill down further . Need to use var selectedPoints = chart.getSelectedPoints() and use these selectedPoints to generate another charts , for example Polar charts to show the defect pattern of the failed product .
I coudn't upload zip files, please see the word file ( HighCharts Github.docx). Sorry for such a mess.
[getSelectedPoints.txt](https://github.com/highcharts/highcharts/files/8677506/getSelectedPoints.txt)
[HighCharts Gihub.docx](https://github.com/highcharts/highcharts/files/8677508/HighCharts.Gihub.docx)
[Page-Polar.txt](https://github.com/highcharts/highcharts/files/8677511/Page-Polar.txt)
[Page-Scatter.txt](https://github.com/highcharts/highcharts/files/8677512/Page-Scatter.txt)

3 more files. I take it from HTML source code , it will have HightCharts Javascript with data.
I put original html page into zip file and pull it into word file

[Script-Highcharts-Polar.txt](https://github.com/highcharts/highcharts/files/8677962/Script-Highcharts-Polar.txt)
[Script-Highcharts-scatter.txt](https://github.com/highcharts/highcharts/files/8677976/Script-Highcharts-scatter.txt)
[HighCharts Gihub with Zipfile.docx](https://github.com/highcharts/highcharts/files/8678505/HighCharts.Gihub.with.Zipfile.docx)

**Comment by brofixo** [comment]
@EWChina999, [PolarSample2.zip](https://github.com/highcharts/highcharts/files/8744835/PolarSample2.zip)

**Comment by EWChina999** [comment]
> @EWChina999, [PolarSample2.zip](https://github.com/highcharts/highcharts/files/8744835/PolarSample2.zip)

Thanks for your excellent help. I tried , it works . 
Another function is about zoom . I added the below code , it does not work
Chart = new Highsoft.Web.Mvc.Charts.Chart
          {
              Polar = true,
             ZoomType =ChartZoomType.Xy
          },
But in line chart, your another sample, I added Zoom function, it works perfectly
            Chart = new Highsoft.Web.Mvc.Charts.Chart
          {
              ZoomType =ChartZoomType.Xy
          },           
![image](https://user-images.githubusercontent.com/104311689/169730014-f741e52f-6c8b-4c69-963f-f5dca9e10179.png)

**Comment by brofixo** [comment]
@EWChina999, this feature is during development https://github.com/highcharts/highcharts/pull/16992

**Comment by EWChina999** [comment]
> @EWChina999, this feature is during development #16992

Please kindly also add a feature - an option we can set to change Clockwise to  Counterclockwise  during your development of Polar zoom . Now we can change Pan StartAngle =-270 and EndAngle=90 to achieve Counterclockwise and 0 is East

**Comment by brofixo** [comment]
> Please kindly also add a feature - an option we can set to change Clockwise to Counterclockwise during your development of Polar zoom . Now we can change Pan StartAngle =-270 and EndAngle=90 to achieve Counterclockwise and 0 is East

@raf18seb feature request

**Comment by raf18seb** [comment]
Hi @EWChina999, could you explain your request more precisely? Is it related to our polar zoom development? If yes, you can comment and talk about it in the above #16992 directly with the developers responsible for that feature.

**Comment by EWChina999** [comment]
> Hi @EWChina999, could you explain your request more precisely? Is it related to our polar zoom development? If yes, you can comment and talk about it in the above #16992 directly with the developers responsible for that feature.

@raf18seb , thanks. I added my request for new feature in the above https://github.com/highcharts/highcharts/pull/16992
