### ISSUE TITLE
Zooming and panning with non-overlaid Y axes does not work as expected

### ISSUE THREAD

**Issue by ochristensen** [highcharts/highcharts#17295]
#### Expected behaviour
Zoom and pan should be independent per axis.

#### Actual behaviour
Zooming one axis zooms all others.  Panning flat out doesn't work (presumably because one of the axes has data associated with it that is already all in view and panning shouldn't go further.)  Extremes can clearly be assigned per axis, as all axes begin with unique ranges based on the data for their associated series - it's unexpected that a change in extremes via zoom doesn't work the same way.

#### Live demo with steps to reproduce
https://jsfiddle.net/zenzizen/nm8xpv3g/8/

#### Product version

latest

#### Affected browser(s)
all probably

**Comment by raf18seb** [comment]
Hi @ochristensen, thanks for creating the ticket!

I'm not sure if I understood you correctly. I simplified your demo and recorded a GIF showing strange behavior. Sometimes when I'm zooming the first (top) yAxis, panning moves only that one yAxis. But sometimes when I do the same, panning moves both axes. See a GIF below.
Is this what you are reporting?

Simplified demo: https://jsfiddle.net/BlackLabel/9re3k408/

![panning-multiple-panes](https://user-images.githubusercontent.com/23310742/168595953-62d824c9-826e-4b6a-b2a3-fd9e74e10677.gif)

**Comment by ochristensen** [comment]
Apologies for the delayed reply.
1) Zooming on one axis shouldn't affect others.  Extremes are _per-axis_ so I don't think zooming one (changing the extremes) should have any effect on others.  In your gif the bottom y-axis extremes should _never_ change when you zoom in the top one.
2) Panning should only affect the panning axis/axes.  Again, we are looking to change the extremes for a single axis or single x-y axis pair.  It shouldn't pan an unrelated axis.  In your gif, the Y-axes should _never_ pan together.
