### ISSUE TITLE
Gantt Chart Expand Collapse action - removing the bar

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/highcharts#17309]
#### Expected behaviour
Initial load of Gantt chart works fine as expected. On click of a parent node to collapse / expand, it should collapse and on expand it should come to the initial view

#### Actual behaviour
Initial load of Gantt chart works fine as expected. On click of a parent node to collapse / expand, one of the the bars disappears in the case when there are 2 bars
Fiddle is here
https://jsfiddle.net/sreejithga/y2894ovj/3/
#### Live demo with steps to reproduce

https://jsfiddle.net/sreejithga/y2894ovj/3/

Click on Strategic Project, chart collapses as expected but the outer bar in all lines disappeared and on expand also its gone. 
#### Product version

Highcharts Gantt JS v10.1.0 (2022-04-29)

#### Affected browser(s)
Chrome

Please help us resolve this issue,

Thanks

**Comment by karolkolodziej** [comment]
If you declare points start and end correctly as numbers, you don't have this issue. See in [the demo](https://jsfiddle.net/BlackLabel/u7m9d2x1/).

But if you would like to add background to each level you can do it differently. Please refer to [this forum thread](https://www.highcharts.com/forum/viewtopic.php?t=45275).

For future reference, please contact our [support team](https://www.highcharts.com/blog/support/) first. 
We mostly use GitHub to track the bugs and this doesn't look like one.

**Comment by Sreejithga** [comment]
Thanks @karolkolodziej  for your response.

"If you declare points start and end correctly as numbers" - Kindly tell me where I've got the numbers wrong. The start and end assigned with nulls - I've removed those lines, still the issue persists.

                    "start": null,
                    "end": null,

Also in your example you do not have the second bar at the parent level as I've in my fiddle.

Would you mind telling the exact issue in my fiddle, so that we get the expected result.

Thanking you in advance and thanks again for responding to the ticket.

**Comment by karolkolodziej** [comment]
The tree structure is generated based on the provided data and each point should have a unique ID.
In your case you have two points with the same ID thus the tree isn't generated properly.
