### ISSUE TITLE
Stock Tools - issue with saving height of parallel channel to localStorage

### ISSUE THREAD

**Issue by hubertkozik** [highcharts/highcharts#17305]
#### Expected behaviour

The height of the parallel channel should be overwritten in localStorage if it is changed.

#### Actual behaviour

The height of the parallel channel is saved in localStorage only if the parallel channel is created from scratch. If the user modifies the height and saves it again, the new height is not saved.
However, updating and saving other control points (e.g. position) works fine.

![parallelChanelBug](https://user-images.githubusercontent.com/62724907/168979265-51618161-74cb-4142-ab20-fe1efb367678.gif)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8zgva10f/

1. Add a parallel channel to the chart.
2. Save the chart in local storage using the stock button.
3. Refresh the page to get a blank chart and click the button "Restore annotation".
4. Select the parallel channel and change its height using the control button (middle one).
5. Save the chart again.
6. Refresh the page and restore again - the height of the parallel channel is not being saved, when other positions are saved correctly.

#### Product version
Highcharts Stock v10.1.0

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/8zgva10f/2/

Plugin:
```js
(function(H) {
  H.wrap(
    H._modules['Extensions/Annotations/Types/Tunnel.js'].prototype,
    'translateHeight',
    function(proceed, ...args) {
      proceed.apply(this, args);

      this.userOptions.typeOptions.height = this.options.typeOptions.height;
    }

  );
})(Highcharts);
```
