### ISSUE TITLE
Exporting: Print in Safari browser doesn't work as expected 

### ISSUE THREAD

**Issue by hubertkozik** [highcharts/highcharts#17311]
#### Expected behaviour

Calling the _chart.print()_ method will always print the chart and show the chart in preview.

#### Actual behaviour

If I call the _chart.print()_ method for the first time the popup with printer settings shows up and everything works correctly. If I close this popup using the 'Cancel' button and call the method _chart.print()_ again the different popup shows up with text: "This webpage is trying to print. Do you want to print this webpage?" When I click the 'Print' button the printer settings show up and I don't see the chart in the preview window.

![safari_bug](https://user-images.githubusercontent.com/62724907/169325421-0ca72e91-c0f7-4fdc-9e0c-5d87b9acb97f.gif)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/nxkzb07w/
1. Click the button 'Print chart' to call _chart.print()_ method.
2. Click the 'Cancel' button in the printer settings popup.
3. Click the 'Print chart' button again - a different popup shows up.
4. Click the 'Print' button - the preview doesn't contain the chart.

#### Product version
Highcharts v10.1.0 (probably previous too)

#### Affected browser(s)
Safari 15.2 - probably not the only version

**Comment by karolkolodziej** [comment]
Thank you for reporting the issue!
