### ISSUE TITLE
alignThreshold + stacking doesn't work

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#17314]
#### Expected behaviour
The series should be rendered in the correct place.

#### Actual behaviour
The Series are behaving as if they would be stacking even though they are on separate axes.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/9b1p5vkn/169/

#### Product version
v10.1.0
#### Affected browser(s)
all

#### Workaround

call `chart.redraw()` in the load event: 
https://jsfiddle.net/BlackLabel/9b1p5vkn/170/

**Comment by sierrodc** [comment]
Even with the workaround, when you hide/show a serie using the legend the issue reappears.

**Comment by NathanManning** [comment]
Any movement on this? I need the legend clicking ability and have data dynamically loaded via other UI elements and can't call just a single redraw() after load.

**Comment by pawellysy** [comment]
Hi @NathanManning, thanks for your input, we will move this task higher in the prioritization board 👍

**Comment by NathanManning** [comment]
@circleci-mu Is there a typical cadence to these types of tickets?

**Comment by sierrodc** [comment]
Not completely sure, but after updating Highchart to version 10.3.2, it seems that the issue is disappeared.
@NathanManning can you also check if this is true for you?

**Comment by pawellysy** [comment]
@sierrodc here it is still broken: https://jsfiddle.net/BlackLabel/9b1p5vkn/344/

**Comment by sierrodc** [comment]
@pawellysy: you are right, same issue here: https://codepen.io/sierrodc/pen/eYVvWmL?editors=1111

**Comment by NathanManning** [comment]
@sierrodc still happening for me. See the fiddle in my OP: https://jsfiddle.net/spyx4c2a/1/

Unless I'm missing something. That fiddle uses <script src="https://code.highcharts.com/highcharts.js"></script> which links to "Highcharts JS v10.3.2 (2022-11-28)".

**Comment by NathanManning** [comment]
This is blocking a production feature. Do they typically get picked up quicker if we go through customer care?

**Comment by pawellysy** [comment]
Hello @NathanManning, We are starting development on this bug. You can track the progress in this thread, or in linked PR. Thanks!

**Comment by NathanManning** [comment]
@TorsteinHonsi , when will this get published to a new npm version?

**Comment by TorsteinHonsi** [comment]
@NathanManning We are planning a release within two weeks from now.

**Comment by NathanManning** [comment]
@TorsteinHonsi @circleci-mu Incredible timing on 10.3.3!! Just in time for our launch. Thanks for all the hard work.
