### ISSUE TITLE
Enable horizontal scaling of nodes for organization chart when not inverted

### ISSUE THREAD

**Issue by nevalain** [highcharts/highcharts#17328]
#### Expected behaviour
When organization chart (inverted: false) is shrunk horizontally (or there are more levels/hanging) the nodes should scale down to the available space.

Maybe nodeWidth could be relative to "standard width" ( "standard width" = available space divided by levels+max(hanging))?
[https://api.highcharts.com/highcharts/plotOptions.organization.nodeWidth](https://api.highcharts.com/highcharts/plotOptions.organization.nodeWidth)

#### Actual behaviour
When organization chart (inverted: false) is shrunk horizontally the node are not scaled and they overlap.

#### Live demo with steps to reproduce
[https://jsfiddle.net/43bnzmjq/](https://jsfiddle.net/43bnzmjq/)

**Comment by pawellysy** [comment]
Hello @nevalain, thanks for contacting us with your idea!
I think this is a viable enhancement to implement in the Organization chart. Here is the simplified demo: https://jsfiddle.net/BlackLabel/ra4c9mov/1/

**Comment by nevalain** [comment]
Hi! This would still be an important development for us. It is necessary that the organization chart would automatically scale and fit because our information (organization structure) can be changed by the user. New treegraph works better for some cases (e.g multiple top level nodes), but it has it's own issues and organization chart can shows more information in boxes.

**Comment by nevalain** [comment]
Hi! (Accidentally marked done. I just wanted co comment that this issue should stay open) This would still be an important development for us. It is necessary that the organization chart would automatically scale and fit because our information (organization structure) can be changed by the user. New treegraph works better for some cases (e.g multiple top level nodes), but it has it's own issues and organization chart can shows more information in boxes.

**Comment by TorsteinHonsi** [comment]
@nevalain I experimented with allowing `nodeWidth: 'auto'`, which also requires us to add a new option `nodePaddingLongitudinal` because the distance can no longer be calculated from the `nodeWidth`. You can see a preview at https://jsfiddle.net/highcharts/uwpbv4qh/ .

**Comment by TorsteinHonsi** [comment]
@nevalin Now also supported for treegraph. How is this working for you? https://jsfiddle.net/highcharts/t3b2j6ps/

**Comment by nevalain** [comment]
@TorsteinHonsi : This works very well! Thank you very much!

**Comment by TorsteinHonsi** [comment]
@nevalain Thanks for the feedback!

It's a setting, both pixels and percentages should work. I think 30 is a sensible default for org charts, because it leaves enough rooms for the links to be clearly visible: https://jsfiddle.net/highcharts/uwpbv4qh/1/

But you can optionally set it to a percentage: https://jsfiddle.net/highcharts/uwpbv4qh/2/

**Comment by nevalain** [comment]
You're right! Works very well! Thanks!
