### ISSUE TITLE
Heatmap as triangular matrix

### ISSUE THREAD

**Issue by Tanja000** [highcharts/highcharts#17326]
Dear Ladies and Gentlemen,

First of all: I love highchart and it's amazing possibilities and easy usage. Thanks a lot!

I recently used this feature: https://www.highcharts.com/docs/chart-and-series-types/heatmap

Would it be possible to have the matrix heatmap as a triangular matrix? In my case there is a symmetry where the diagonal symmetry axis goes from left buttom to right top.

I would be glad to get an answer. Thanks a lot in advance!

Have a great day,
Tanja

**Comment by pawellysy** [comment]
Hello @Tanja000! This could be a part of the tilemap series: highcharts.com/demo/maps/honeycomb-usa

The tilemap series type inherits from the heatmap, and introduces other shape types, like: `square`, `hexagon`, `circle`, `diamond`. 
This could be another shape type. Thanks!
