### ISSUE TITLE
Tooltip drawn on top of flag when Y axis is reversed

### ISSUE THREAD

**Issue by cebamps** [highcharts/highcharts#17322]
#### Expected behaviour
Tooltips should not be drawn on top of the flag they point at (similar issue to #13780).

(Ideally for my use case, the tooltip should be drawn above the flag regardless of the Y axis being reversed.)

#### Actual behaviour
Instead of being drawn right above the top of the flag (as they are when the Y axis is not reversed), the tooltip is drawn right *under* the top of the flag, resulting in an overlap:
![Screenshot 2022-05-25 at 10 56 05](https://user-images.githubusercontent.com/12797742/170223573-fabf9b47-f7a2-4b6c-940a-6dad514646a5.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/Lx27wg35/

#### Product version
Highstock v10.1.0

#### Affected browser(s)
Firefox, Chrome

**Comment by karolkolodziej** [comment]
Thank you for reporting the issue.

Works correctly in v.9.2.2.
Demo: https://jsfiddle.net/BlackLabel/7v4c6rw1/
