### ISSUE TITLE
Add a function to get the selected points in Blazor

### ISSUE THREAD

**Issue by EWChina999** [highcharts/highcharts#17321]
With jQuery, we can get the selected points by a click on the line charts . Then we can generate another charts with the data point the user clicks on. the sample for jQuery is https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-allowpointselect-line/ 

Could you add this feature in Blazor? 
I googled the whole internet , found one website of ECharts has one feature .  http://blazor-echarts.5izhy.cn/line/index . My project is using HighCharts, could you do me a favor and add it .

**Comment by brofixo** [comment]
@EWChina999 , this feature already exists - AllowPointSelect property.
For example for line series: https://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_line_series.html#a49f7bacf4417b7507b8164bd8c31806e
or 
https://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_plot_options_series.html

**Comment by EWChina999** [comment]
@brofixo, how to really use this feature in Blazor is a bigger headache for me. Could you add  more feature demos ( for examples: GetSelectedPointed(), tooltip ) into your demo sample  (https://github.com/highcharts/highcharts/issues/15553)?  I clicked the page https://dotnet.highcharts.com/class-reference/Highcharts.Chart#getSelectedPoints , the returned page content is "404 - File or directory not found" . I searched the whole internet , did not find one example code to use it in donet and Blazor .  There are many examples of HighCharts special features usage cases in Javascript , but few cases in Donet and Blazor . just simply showing a chart in donet /Blazor is easy, how to have more interactives in Blazor / VUE3 like the ways we did in normal Javascript is more attractive . Really appreciate your help.

**Comment by EWChina999** [comment]
I fixed it in VUE3 .Here are codes : 

 <highcharts class="chart" :options="chartOptions" :updateArgs="updateArgs" ref="chart01"></highcharts>
<div>
                <p>Here are the Selected points </p>
                <p>{{ pointcl }}</p>
            </div>
            <div>
                <button @click="getclickdata">getclickdata</button>
               
            </div>

export default {
  data () {
    return {
      title: '',
        numNum: Number,
      pointcl:'3',
      durationOptions: [0, 500, 1000, 2000],
      points: [10, 0, 8, 2, 6, 4, 5, 5],
      chartType: 'Spline',
      seriesColor: '#6fcd98',
      colorInputIsSupported: null,
      animationDuration: 1000,
        updateArgs: [true, true, { duration: 1000 }],     
      chartOptions: {
        chart: {
              type: 'spline',
            zoomType: 'Xy'
          },  
          plotOptions: {
              series: {
                  allowPointSelect: true
              }          },
        title: {
          text: 'Sin chart'
          },      
          series: [{  
          data: [10, 0, 8, 2, 6, 4, 5, 5],
          color: '#6fcd98'
        }]
      }
    }
  },
  created () {
    let i = document.createElement('input')
    i.setAttribute('type', 'color');
      (i.type === 'color') ? this.colorInputIsSupported = false : this.colorInputIsSupported = true
        },
  methods: {
           getclickdata(){
                let pointcs = this.$refs.chart01.chart.getSelectedPoints();
          console.log(pointcs);
          this.pointcl = pointcs[0].category

                        }
             },
  watch: {

@brofixo , could you give key sample codes in Blazor , thanks.

**Comment by brofixo** [comment]
@EWChina999 , let me know if you need anything more or please close tickets.
