### ISSUE TITLE
Barchart :  Some data are missing when there are more y axis

### ISSUE THREAD

**Issue by mohits-moodys** [highcharts/highcharts#17349]
#### Expected behaviour
 The barchart should display all data even when we have more data.

#### Actual behaviour

When there are more number of data, the library automatically removes the lower values.
#### Live demo with steps to reproduce
https://jsfiddle.net/mohitsharma_moodys/8ejfyszk/2/

**Comment by karolkolodziej** [comment]
When you have more data on a small chart each point is getting smaller and harder to track.
Thus you might get an expresion that something is missing but actually all points are on the chart please check this on the demo below. 
In the console you can find that the first point is calculated and have a graphic representation.
Demo: https://jsfiddle.net/BlackLabel/sx94ktfj/

With such dense data consider using some tools that makes chart more readable like: 
- [Zoom](https://api.highcharts.com/highcharts/chart.zoomType)
- [scrollablePlotArea](https://api.highcharts.com/highcharts/chart.scrollablePlotArea)
