### ISSUE TITLE
Dependency wheel CSV export includes unwanted data

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts#17348]
#### Expected behaviour

Dependency wheel CSV export should include `from` `to` and `weight` data only

#### Actual behaviour

A dependency wheel CSV export includes all series data as specified by `keys` and additionally a `Category` data line, which is invisible in the chart itself. If you have a 'color' key, then the export includes that, too:

<img width="973" alt="csv-export-sample-screenshot" src="https://user-images.githubusercontent.com/12996815/171432316-17c363ee-f18c-44d5-b5ee-5c4f64dbcc87.png">

If `keys` are set, there should be a way to specify which keys should actually get exported to CSV, and which keys shouldn't.

#### Live demo with steps to reproduce

https://jsfiddle.net/totalidea/cysj1ueb/2/

#### Product version

Current version

#### Affected browser(s)

NA

**Comment by karolkolodziej** [comment]
I added an array to the series config called `keysToExport`. 
Based on that and the wrap of `getDataRows` method, data for export is being prepared based on the `keysToExport`.
This works for the CSV and also for the data table below the chart.

Demo: https://jsfiddle.net/BlackLabel/3Ly1q9jt/
