### ISSUE TITLE
HighCharts Series Space

### ISSUE THREAD

**Issue by pdelbert** [highcharts/highcharts#17356]
#### Expected behaviour
Want to remove the gap between those charts area series

Any idea?.
 
#### Live demo
https://jsfiddle.net/dczv0u53/13/

**Comment by karolkolodziej** [comment]
There are a few solutions to that. 
One of them is using the `broken-axis` module and creating breaks as shown in the demo below.

Demo: https://jsfiddle.net/BlackLabel/fv18ae6j/

For future reference, we use GitHub to track bugs and feature requests so with questions like this, please contact our support team through available [support channels.](https://www.highcharts.com/blog/support/)
