### ISSUE TITLE
animationLimit not working on initial animation of chart

### ISSUE THREAD

**Issue by hubertkozik** [highcharts/highcharts#17351]
#### Expected behaviour

If I set an _animationLimit_ to some value, all animations will not be shown if the number of points is greater than this value.

#### Actual behaviour

If I set an _animationLimit_ to some value, then the initial animation is shown, but if I update the series, then the animation is not shown. API says: "there is a limit that shuts down initial animation by default when the total number of points in the chart is too high. " which is not correct with actual behaviour. @TorsteinHonsi is that an expected behaviour and I am wrong?

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/deoy2a3f/

1) First the chart is loaded with animation.
2) After two seconds there is an update and the animation is not shown.

#### Product version
Highcharts v10.1.0

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
@hubertkozik It's the docs that are outdated. I believe that some time in the past, the column series' initial animation ran an animation on each column individually, which would be increasingly jaggy with an increasing number of points. 

Currently, however, the animation runs on the whole group's translation, so the number of points doesn't have so much to say. But when updating the data, each point has to be updated to its new value, so in that case `animationLimit` takes effect. We need to reflect this in the API description.
