### ISSUE TITLE
Sticky tracking doesn't work for charts with polar=true config

### ISSUE THREAD

**Issue by parthshah51999** [highcharts/highcharts#17359]
#### Expected behaviour
Sticky tracking works exactly as expected when polar = false, but not when polar = true

#### Actual behaviour
Sticky tracking should work with chart having config polar = true

Reference: https://www.highcharts.com/forum/viewtopic.php?t=45216

#### Live demo with steps to reproduce
 https://jsfiddle.net/patonomatic/a5bmw0se/6 (polar) vs https://jsfiddle.net/patonomatic/a5bmw0se/9 (non-polar)

#### Product version
Highcharts - 9.3.3

**Comment by raf18seb** [comment]
Hi @parthshah51999, thank you for reporting a bug.

`Internal note:`
Worked fine in 8.0.0, broken since 8.0.1. I was unable to bisect, but it is **possible** that it is regression after this PR https://github.com/highcharts/highcharts/pull/12774
