### ISSUE TITLE
Tooltip not working correctly after window resize and scrollablePlotArea must be enabled

### ISSUE THREAD

**Issue by JoeyLi-1** [highcharts/highcharts#17352]
#### Expected behaviour
Tooltip works fine. Look like this.
![image](https://user-images.githubusercontent.com/20162464/171610456-8a99e92b-f471-4a11-961d-96ff57e24e2b.png)

#### Actual behaviour
Tooltip missing.
![image](https://user-images.githubusercontent.com/20162464/171610559-73a9ea37-a5a1-4dd9-b3ee-d3177947ce6f.png)

#### Live demo with steps to reproduce
[](https://jsfiddle.net/sLhw8n3p/)

Repo steps:
1 click button "small";
2 open console to force redrew;
3 minimize the console panel
4 click button “large”;
5 open console to force redrew;
6 minimize the console panel
7 you can see part of the tooltip disappeared.  
(Seems only V-Scrollbar could cause this issue)

This demo is similar but not exactly same as our case. In our case, after resize the window, some of the tooltip disappear totally. And if 
 you set a positioner callback function, some tooltip will trigger that function while others don`t. The "top" property of the missing tooltip will be "-9999px".

#### Product version

v10.1.0

#### Affected browser(s)
I just tested it on chrome.

PS: I am new to JSFiddle, Just copy the code here in case the demo not working.
HTML:
`<meta name="viewport" content="width=device-width, initial-scale=1" />
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>

<div id="container"></div>
<button onclick="onLarge()">
Large
</button>
<button onclick="onSmall()">
Small
</button>
`

JS:
`function onLarge() {
$('#container').css("height","400px")
}
function onSmall() {
$('#container').css("height","190px")
}`

chart: {
        type: 'spline',
        scrollablePlotArea: {
            minHeight: 200,
            scrollPositionX: 1
        }
    },

I Just change a little bit of the official demo. 
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea

Thank you for your time!

**Comment by karolkolodziej** [comment]
Thank you for reporting that issue.
Simplified demo: https://jsfiddle.net/BlackLabel/buqezt6n/

_Internal note:_
This condition in the tooltip `refresh` method is failing and resulting in hiding that tooltip.
https://github.com/highcharts/highcharts/blob/0146821d369ddc8af5db75afb8fb5257185673c9/ts/Core/Tooltip.ts#L1112-L1117
The direct cause of that behavior is visible in `isInsidePlot` where incorrect `scrollablePlotBox` is taken.

**We should investigate how the `scrollablePlotBox` is being set after `reflow`.**

**Comment by karolkolodziej** [comment]
Edit:
Bisected to commit 9b58c8a9ef
Works well in v9.0.1 and lower
