### ISSUE TITLE
Logarithmic yAxis with custom tickPositioner is showing exponential values in label

### ISSUE THREAD

**Issue by subhabrata2017** [highcharts/highcharts#17364]
#### Expected behaviour
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/29191626/172389498-953f591f-abd3-488d-b1af-77a21ccf716d.png">

#### Actual behaviour
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/29191626/172389078-77b364e4-024a-400a-9380-eed9821358c1.png">

#### Live demo with steps to reproduce
template: https://jsfiddle.net/Subhabrata/h59e7qc1/12/

#### Product version
v10.1.0

#### Affected browser(s)
In all browsers

**Comment by pawellysy** [comment]
Hello @subhabrata2017, thanks for reporting the issue. 
Could you elaborate more on what is happening, and what you want the effect to be? Thanks!

**Comment by pawellysy** [comment]
Thanks for the explanation. 
It is a bit confusing, but the logarithmic axis works this way and this is intended.
When you are defining the tickPositions, each position's value is later calculated as 10^(tickPositions value).
This makes the values to be different. What you can do, is to take precoutions from this behavior, and if the axis is logarithmic, calculate the tick positions as log(desiredValue).

I know it is a bit tangled explanation, but I hope it makes sense. 

Here is the workaround: 
https://jsfiddle.net/BlackLabel/mtchvedw/1/


Of course it should be mentioned in the API, that it works this way, so we will add it. Thanks again!

**Comment by raf18seb** [comment]
Hi, it's already mentioned for `tickInterval`: https://api.highcharts.com/highcharts/yAxis.tickInterval
If you add more info for `xAxis.tickPositioner` then why not to add the same info for `xAxis.tickPositions`, `xAxis.type` and more other related properties?

At least let's wait for additional feedback from users. If this is only a one-time situation, then I think that the info in `tickInterval` is enough. If this ticket gets more votes or comments, then we should add it in more places (when voting, please add info where you'd like to add the info).
