### ISSUE TITLE
Axis labels' "step" not respected when using formatter

### ISSUE THREAD

**Issue by totszwai** [highcharts/highcharts#17366]
#### Expected behaviour
When using `xAxis.labels.formatter` it should still respect the `xAxis.labels.step` attribute. Right now it is ignored.

```
    xAxis: {
        labels: {
            step: 1,	// Expected it to honor the step setting provided
            formatter: function () {...}
        }
    },
```

The `step` attribute only works when using with `xAxis.labels.categories`.

#### Actual behaviour

```
    xAxis: {
        labels: {
            step: 1,	// <== IGNORED
            formatter: function () {...}
        }
    },
```

#### Live demo with steps to reproduce
https://jsfiddle.net/totszwai/41az5wm8/

#### Product version
Latest

**Comment by pawellysy** [comment]
Hello @totszwai, thanks for contacting us!
Are you sure this is not working? As you can read [in the api](https://api.highcharts.com/highcharts/xAxis.labels.step) that step option shows only every n'th label on the axis.
When I set the step: 2 every other label is shown. In your example, you set it to 1, which means, that it should show all labels. 

Here is how the chart looks when i set the step: 2

![image](https://user-images.githubusercontent.com/26306846/172569553-d4c832a2-359b-4c9a-88d8-56efad09668c.png)

**Comment by totszwai** [comment]
What the... when I was in that fiddle, it wasn't showing.

**Comment by totszwai** [comment]
Actually, is on bar chart.
![image](https://user-images.githubusercontent.com/4440365/172664265-dc1b884b-48b5-479b-b773-93f417aded80.png)

**Comment by raf18seb** [comment]
Hi @totszwai,

The `step` property shows only every n'th label of all the ticks.
For example, when you have 10 ticks and you set `xAxis.labels.steps: 2`, then only 5 labels are shown. **But you need to have 10 ticks first.**

In your above bar demo, you have only 3 ticks so with `xAxis.labels.step: 1` all 3 labels are shown. If you'd like to have more labels, you need more ticks, so what you're looking for is actually the `xAxis.tickInterval` property (and you don't need `steps` at all), see demo: https://jsfiddle.net/BlackLabel/dt9rjezk/

Is that what you were looking for? If yes, then please let us know so we can close the ticket as resolved.

**Comment by totszwai** [comment]
My bad, sorry about that and thanks @raf18seb !
