### ISSUE TITLE
The candle chart part of highstock shows the date part and the time

### ISSUE THREAD

**Issue by LQS5858** [highcharts/highcharts#17367]
#### Expected behaviour
Highstock's candle chart xAxis all show dates

#### Live demo with steps to reproduce

http://jsfiddle.net/Ricardo_lqs/qhjxwpyb/10/

#### Product version

Highstock  10.1.0

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/28332210/172528509-ffd71bec-73b1-431f-8ebc-05edc6a06b3a.png">

**Comment by pawellysy** [comment]
Hello @LQS5858, thanks for contacting us!
Could you elaborate more, about what is wrong with the chart, and what is the desired behavior?
I am not quite sure if I see any problem here. Thanks!

**Comment by pawellysy** [comment]
Why don't you set the yAxis labels using the time module and formatter function like in this example? Wouldn't it work for you? http://jsfiddle.net/BlackLabel/dguL0k5a/

**Comment by LQS5858** [comment]
> Why don't you set the yAxis labels using the time module and formatter function like in this example? Wouldn't it work for you? http://jsfiddle.net/BlackLabel/dguL0k5a/

Hello @pawellysy   OK，Thank you
