### ISSUE TITLE
Date granularity range option for stock chart to show any data for any time for the entire date range selected

### ISSUE THREAD

**Issue by keithmdragon** [highcharts/highcharts#17369]
# Description of the feature
It would be nice to have an option to "snap" the date range for the stock chart to the full day, so that the from date is always 0 hours, 0 seconds, and the end date is always 23 hours, 59 seconds. The issue is that it is confusing to the user when he picks a date range and sometimes the first or last data point is missing from the chart, especially if they are trying to produce marketing material or calculate period differences. In our case there is just one data point per day, but this could be useful regardless of the data frequency. Setting the range in the navigator, date range inputs, or api should all enforce this. 

# Library related to the feature
Highcharts Stock

**Comment by raf18seb** [comment]
Hi @keithmdragon, thanks for creating a feature request ticket!

Could you provide more information so we can visualize that? Maybe a live demo with a chart you already have, or a mock image, or at least a sample data we can base.
Any additional info or a specific use case described would be welcome.

**Comment by keithmdragon** [comment]
Hi Rafał,

this request was based on some support i was getting from Karol Kołodziej, i'm not sure if you have access to our email exchange?

the issue can be demonstrated on this demo. having the time included in the date range helps visualize what is happening. by default the time is not shown.

Live demo: https://jsfiddle.net/BlackLabel/m493g81j/ 

Using the navigator change to the 6th of May.  
As you can see on the screenshot below there are some additional hours added to that range. 
And since the point is precisely at 00:00 it won't be visible.

![image](https://user-images.githubusercontent.com/12547077/173147709-4fec45d0-2a31-457b-9ef4-0a99861051cf.png)
 
so, what i would like to see is just the date in the date range tool and for the beginning date to always be time 00, and the ending date to always be 23 hours and 59 min and 59 seconds, so that all data on both the beginning and ending day is shown.  the issue is that the user doesn't see the time, only the date, and assumes that the data for beginning and ending days will be included, but it isn't if the time of day doesn't include it.

thanks
Keith
