### ISSUE TITLE
Solidgaguge throws Error: <rect> attribute height: A negative value is not valid when pane is reversed .

### ISSUE THREAD

**Issue by magdalena-gut** [highcharts/highcharts#17361]
#### Actual behaviour
When `pane.startAngle` value is higher than `pane.endAngle`, the `pane `is gone and chart throws the following error:
`<rect> attribute height: A negative value is not valid.`

#### Demo
https://jsfiddle.net/BlackLabel/81bpnyoc/

#### Workaround
Setting `series.clip` to false solves the problem of disappearing `pane`, but the error still exists.

#### Last working version:
9.2.2

**Comment by karolkolodziej** [comment]
Thank you for reporting the issue. 

_Internal note:_
Unable to dissect but I suspect this [commit](https://github.com/highcharts/highcharts/commit/9ce5028229e89479232fe1cd2c64f2fd9db53b38) might be the source.
In the `setAxisSize` method in the `RadialAxis.ts` file, the `axis.len` is calculated incorrectly which influence how the series clip in the `setClip` method is rendered.

**Comment by hubertkozik** [comment]
I found, that bug still exists in the latest version of Highcharts v10.2.1 - demo: https://jsfiddle.net/BlackLabel/dvrp5zq2/ 
Workaround with `clip: false` is valid, because if this is set, the series is not disappearing, but there is still an error in the console.

**Comment by pawellysy** [comment]
FYI @karolkolodziej
