### ISSUE TITLE
Marker on dumbbell series is not applied to the legend

### ISSUE THREAD

**Issue by hubertkozik** [highcharts/highcharts#17388]
#### Expected behaviour

If I set a `marker.symbol` to e.g. `square` the same marker as on the chart will be shown on the legend.

#### Actual behaviour

If I set a `marker.symbol` to e.g. `square` the marker is shown only on the chart, not on the legend.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/Lak3pwdt/

#### Product version
Highcharts v10.1.0

Workaround: 
Override the `dumbbell.prototype.drawLegendSymbol` method with the one working.

Live demo with a workaround:
https://jsfiddle.net/BlackLabel/yhwmxndr/

**Comment by hubertkozik** [comment]
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/7771.
It won't be fixed to a dumbbell (and all area-based series) - explained in the ticket above.

For anyone interested, the official solution is to use the workaround provided above.

**Comment by BKSelvakumaranK** [comment]
I got the solution.
I have created Marker on dumbbell series is  applied to the legend.
 legend: {
      	useHTML: true,
      	labelFormatter: function () {
           var symbol,text;
           if(this.name=='Appraiser 1')
           {
           		symbol='<span class="squaremarker" ></span>';
           		text='<span>'+this.name+'</span>';
           }
           else if(this.name=='Appraiser 2')
           {
           		symbol='<span class="circlemarker"></span>';
              text='<span class="markercircletext">'+this.name+'</span>';
           }
           else if(this.name=='Appraiser 3')
           {
      				symbol='<div class="diamondmarker"></div>' ;
        			text='<span class="markerdiamondtext">'+this.name+'</span>';
           }
           
           return `${symbol} &nbsp; ${text}`; 
      	},
    },[](url)
