### ISSUE TITLE
Bar chart resize renders 0 value bars

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#17387]
#### Expected behaviour
Bars with `y: 0` should not be visible at all.

#### Actual behaviour
Bars with `y: 0` are rendered on some specific window widths.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8nh9jtac/
1. Run the demo and observe the first bar render on `chart.width: 911`
2. Change the `chart.width` to `900` and the bars are not rendered.

#### Product version
Highcharts v10.1.0 (current)
#### Affected browser(s)
All browsers

**Comment by raf18seb** [comment]
@TorsteinHonsi would you consider this as a bug?

The column's height is calculated here:
https://github.com/highcharts/highcharts/blob/06c568db48e463c7a760ee0818ff85334b0c9e48/ts/Series/Column/ColumnSeries.ts#L911

And after crisping the height is 1 where, in my humble opinion, it should be 0.
