### ISSUE TITLE
Boosted area graph renders blank graph if setExtremes is called on the yAxis in load event

### ISSUE THREAD

**Issue by ochristensen** [highcharts/highcharts#17385]
#### Expected behaviour
yAxis setExtremes on a normally stacked area graph in the load event should work.

#### Actual behaviour
this is a very strange bug as it usually renders fine on the first render; refreshing immediately causes the graph to go blank.  when the graph renders blank.  i can still mouse over and get tooltip information for the data - just the lines and markers are invisible.  the navigator correctly shows the data.  in my real app I see the blank graph from the first render.

removing `plotOptions.area.stacking` or `chart.events.load` fixes it. there is a previous bug on area graph with a log-scaled y-axis with stacking set to normal, that I'm unsure if it's related: https://github.com/highcharts/highcharts/issues/16850

adjusting the navigator range causes the graph to immediately render correctly

#### Live demo with steps to reproduce

https://jsfiddle.net/zenzizen/nq3cxhau/1/

#### Product version

latest

#### Affected browser(s)
chrome at least

**Comment by karolkolodziej** [comment]
Thank you @ochristensen  for reporting this issue.

From what I can see, `stacking` doesn't affect the output- [demo](https://jsfiddle.net/BlackLabel/gmcvoun0/).
However for some reason when you use `setExtremes` and the `navigator` is visible the chart doesn't show data properly -[demo](https://jsfiddle.net/BlackLabel/8ckqaL5m/).

To work around it, you can use the `reflow` method in the chart callback function-[ demo.](https://jsfiddle.net/BlackLabel/vLz09t1b/)
Or you can use v9.3.3- [demo.](https://jsfiddle.net/BlackLabel/5tg4pj7u/)

_Internal note:_
Bisected to commit cbe13786e7b4cf005b6bb8de50172ade6947b1b1
Local tests show that removing `areaspline` from the `boostables` solves the issue (not a permanent and not correct solution).
