### ISSUE TITLE
custom events should probably be namespaced/prefixed

### ISSUE THREAD

**Issue by brendanblackwood** [highcharts/highcharts#1738]
Custom events on objects should probably be namespaced or prefixed in some way to keep them from being handled by non-highcharts handlers. Specifically, the 'resize' event is a native event name. It's not uncommon to have plugins in jQuery that bind special event handlers to native events which nearly always expect a DOM element. 

An example of this is firing 'resize' on the chart object: http://jsfiddle.net/5HQTw/

I'm using Ben Alman's resize plugin to do resizing throughout my application, which binds to the resize event. A quick fix was just to alter the plugin to check if the element in question is a DOM element, but this will probably happen for other people in other plugins that add to native events.

**Comment by oysteinmoseng** [comment]
This is still a relevant suggestion. We could prefix internal events, and have a layer that automatically prefixes the handlers specified by users.
