### ISSUE TITLE
Linear axis labels : overlapped labels aren't being hidden (fixed tickInterval, nowrap, no rotation, textOverflow: none)

### ISSUE THREAD

**Issue by lekarsenten** [highcharts/highcharts#17396]
#### Expected behaviour
Overlapped labels are hidden after rendering

#### Actual behaviour
Overlapped labels aren't hidden.

#### Goal
Show unmodified full text labels (every month) without overlapping (by hiding them)

#### Live demo with steps to reproduce
[https://jsfiddle.net/4mr7e9hk/2/](https://jsfiddle.net/4mr7e9hk/2/)

#### Product version
4.0.4 is almost good.
9.0.1 and latest have issue.

#### Affected browser(s)
From IE9 to Chrome 102

#### Thoughts/propositions
1. Seems like we shouldn't set width at the end of `Tick.prototype.handleOverflow` (here):
```javascript
if (textWidth) {
    if (tick.shortenLabel) {
        tick.shortenLabel();
    }
    else {
        css.width = Math.floor(textWidth) + 'px';
        if (!(labelOptions.style || {}).textOverflow) {
            css.textOverflow = 'ellipsis';
        }
        label.css(css);
    }
}
```
if `textOverflow === 'none'` and `whiteSpace==='nowrap'`.
2. Seems like animation affecting `Chart.prototype.hideOverlappingLabels`. After resize (via chart.setSize), if tick label isn't new but is hidden, it's opacity will be animated from 0 to 1. `hideOverlappingLabels` may fire before animation end which leads to non-hiding label.
3. `Tick.prototype.handleOverflow` with `textOverflow === 'none'` and `whiteSpace==='nowrap'` doesn't move overshoot label properly. This is because it rely on slot size which isn't relevant for label with such properties.

**Comment by pawellysy** [comment]
Hello @lekarsenten, Thanks for creating the issue.


Indeed the labels are not hidden and overlap each other. I am wondering, why you want to have the tick positions be so dense? The tickPositions can be calculated manually or automatically so that they are evenly spread and adjusted to the correct label for your needs. 

As a workaround, I would propose to use a higher value of the tick interval, or just use some other option to set the tick Positions (e.g. [tickPixelInterval](https://api.highcharts.com/highcharts/xAxis.tickPixelInterval), or [step](https://api.highcharts.com/highcharts/xAxis.labels.step)). You can base on one of our docs articles on how to adjust the ticks in any axis: https://support.highcharts.com/a/solutions/articles/44002324219

Let me know if that works for you!

**Comment by pawellysy** [comment]
@lekarsenten, if you want the positions of the tick to be recalculated, you can use the [tickPositioner](https://api.highcharts.com/highcharts/xAxis.tickPositioner) option, to manually calculate the positions.

For further dialogue, please contact us via existing [support channels](https://www.highcharts.com/blog/support/), where our support engineers will help you to adjust the chart to your needs. 


In regards to your current implementation, I think that you manually turn off all our ways of handling overlapping labels. There are numerous ways of setting the axis' tick positions, and I think that you can easily use one of them, so in my opinion, it is a bug. 

What do you think guys think @TorsteinHonsi, @raf18seb?

**Comment by lekarsenten** [comment]
@raf18seb thank you for demo from different perspective. `staggerLines` indeed does work strange in some cases. 
Still, what do you think about (non-) setting width when `textOverflow === 'none'`?
https://github.com/highcharts/highcharts/blob/0445ee1f58f0b6e475dc00c71500dc6e7f86f335/ts/Core/Axis/Tick.ts#L734-L737

**Comment by TorsteinHonsi** [comment]
In addition to the thoughts above, I'd like to shoot in that we use a different logic for `allowOverlap` on data labels. Here's how it looks when applied to the axis labels: https://jsfiddle.net/highcharts/mtgj1ox8/

But apart from that, I don't see how it is useful in this case. It would be better to leave it to `tickPixelInterval`: https://jsfiddle.net/highcharts/mtgj1ox8/1/
