### ISSUE TITLE
Duplicate rendering of datetime axis labels 

### ISSUE THREAD

**Issue by benelliott** [highcharts/highcharts#17393]
#### Expected behaviour

Datetime axis labels should always be rendered once.

#### Actual behaviour

In some situations, a duplicate set of unpositioned axis labels will be rendered in the top-left corner of the chart.

#### Live demo with steps to reproduce

Reproduction (based on Highcharts demo): https://codepen.io/benelliott/pen/QWQYZpJ

Screenshot of the extraneous labels:

![screenshot-codepen io-2022 06 15-12_43_46](https://user-images.githubusercontent.com/4996462/173830342-4ccff111-5193-4200-9a63-d260890b14eb.png)

Screenshot showing the extraneous label nodes in DevTools (unpositioned labels in red, positioned labels in blue):

![Capture](https://user-images.githubusercontent.com/4996462/173830363-20e4b654-c87d-4c4d-980a-ab5a9b3ec350.PNG)

(Note my monitor resolution is 1920x1200 and browser window size is 1920x1067).

The reproduction does the following:

- Plot a datetime series whose x-axis values span less than a year (so that the tick intervals are less trivial)
- Update the series' data (with the exact same datapoints) to trigger a redraw

If you are to resize the window to some arbitrary size and then size it back to the original size, the ticks will be different to the initial render. So I think the cause of the bug is that the axis' tick positions are recomputed before the data change/redraw step, but the ticks and labels are not themselves redrawn. When the data is changed and the chart redraws, the axis recalculates its tick positions and sees that they are unchanged from the previous (unrendered) values, so the axis is not correctly redrawn.

I think the fix would be to refine the logic around marking the axis as dirty if its tick positions have changed.

#### Product version
Highcharts 10.1.0

#### Affected browser(s)
Chrome 102 on Windows 10
Firefox 101 on Windows 10

**Comment by benelliott** [comment]
This could be somewhat related to https://github.com/highcharts/highcharts/issues/14597, but I think it's slightly different as it's related to dirty logic and not font size calculations. The workaround of manually marking the axis as dirty before calling a redraw does help though:

```
    chart.xAxis[0].forceRedraw = chart.xAxis[0].isDirty = true;
```

**Comment by karolkolodziej** [comment]
Thank you @benelliott for reporting that issue.

Setting data to the same as it is already set isn't entirely correct. Please see that this issue is not visible if:
- Initially, the data is set to an empty array then you set the data- [demo](https://jsfiddle.net/BlackLabel/j329nbwz/)
- Initial data is (at least slightly) different than the one you are setting later- [demo](https://jsfiddle.net/BlackLabel/nv7qpzys/)

But if you have to make it that way, please set the `updatePoints` argument in the `setData` method ([API](https://api.highcharts.com/class-reference/Highcharts.Series#setData)) to false- [demo](https://jsfiddle.net/BlackLabel/3a5vz2od/)

Closing it as not a bug.

**Comment by karolkolodziej** [comment]
I went through all that once again and I think You are right and it is a bug.
Also, I managed to simplify it even more- [demo](https://jsfiddle.net/BlackLabel/6eaf0mjz/).

As a workaround, you can set the `updatePoints` to `false` or force the chart to rerender.

_Internal note:_
After updating only the y value of a single point there are some issues:
- Additional axis label on the top left corner
- Axis isn't rerendered/recalculated which probably causes the series to be not clipped properly. (this isn't an issue for line series)

Needs further investigation.

**Comment by benelliott** [comment]
Thanks @karolkolodziej for looking into it.

**Comment by benelliott** [comment]
I did a bit of bisecting and I think that the bug was introduced between v4.0.4 and v4.1.0, by 7f6a1bd5. You can see this here: https://codepen.io/benelliott/pen/rNdVNbv

**Comment by karolkolodziej** [comment]
Thank you @benelliott for investigating the issue!

**Comment by benelliott** [comment]
bump

**Comment by benelliott** [comment]
bump
