### ISSUE TITLE
Using highcharts-android in jetpack compose

### ISSUE THREAD

**Issue by VahidGarousi** [highcharts/highcharts#17406]
Hello, I hope you are well
I have trouble with this library in compose
can you help me?

Please download and run the attached project
The result you will see is that the chart is not displayed

[My Application.zip](https://github.com/highcharts/highcharts/files/8935257/My.Application.zip)

**Comment by pawellysy** [comment]
Hello @VahidGarousi, thanks for contacting us with your question!

Unfortunately, we use GitHub as a bug/feature request tracking tool. For these types of questions please, contact us via support channels [which are listed here](https://www.highcharts.com/blog/support/)

Thanks for understanding!

PS: This is a general highcharts repository. For the highcharts-android wrapper, we have a separate repository here: https://github.com/highcharts/highcharts-android
