### ISSUE TITLE
Zoom breaks with datagrouping disabled and boost in some data sets

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#17405]
#### Expected behaviour
Zoom should work fine

#### Actual behaviour
I have observed a few different behaviours:
- Works fine for some data sets
- For me, it just hangs the page in both chrome and firefox
- For my colleague, it works in chrome but adds some spurious line corrupting the chart in firefox

#### Live demo with steps to reproduce
https://jsfiddle.net/4z5caq9p/ - This uses a specific data set that is generated via the following python code:

```python
import numpy as np
x0 = np.arange(1650500000, 1650590000, 1)
y0 = np.sin(x0/1000/2/np.pi)
x1 = np.arange(1650500000, 1650590000, 10)
y1 = np.sin(x1/1000/2/np.pi + np.pi/8)
```

#### Product version
Highstock 10.1.0

#### Affected browser(s)
Chrome, Firefox

**Comment by pawellysy** [comment]
Hello @govinda18, thanks for creating this ticket!

Simplified demo: https://jsfiddle.net/BlackLabel/493zLkav/2/

It seems broken on firefox but works fine for me on chrome.
Bug on firefox:

https://user-images.githubusercontent.com/26306846/174327158-9453ec14-e0c5-4e35-bac5-30a2ab394abf.mov

**Comment by MavEtJu** [comment]
Is this the same as issue [#17182?]

**Comment by pawellysy** [comment]
Hi @MavEtJu, These two bugs might be connected. They both are about boost on firefox, and the behaviour is similar. Thanks for pointing this out!

**Comment by TorsteinHonsi** [comment]
Hi @govinda18, I think we're dealing with two issues.

In the OP, the browser hangs in the ordinal axis logic. If we set `xAxis.ordinal` to false, it does not hang: https://jsfiddle.net/highcharts/so9tpad0/

The other issue I agree is the same as #17182, so let's deal with that separately.

**Comment by karolkolodziej** [comment]
_Internal note:_
From what I can see the loop is being caused by this piece:

https://github.com/highcharts/highcharts/blob/0d1e4c36c3189ec1c618ccde141d8675eb91f1cf/ts/Extensions/Boost/WGLRenderer.ts#L907-L937

And the `toPixels` method leads to `val2lin` which needs further debugging.
This issue doesn't occur with the column series.
