### ISSUE TITLE
Gantt chart cannot handle large data

### ISSUE THREAD

**Issue by pkExec** [highcharts/highcharts#17415]
#### Expected behaviour
Gantt chart should be able to handle large amounts of data (e.g. > 10.000).

#### Actual behaviour
Browser chokes (Script unresponsive messages, browser slow after rendering, browser may crash, etc).

#### Live demo with steps to reproduce
https://jsfiddle.net/j1mq8tyL/

If you cannot load fiddle, these are the settings used:

```
let subitems=[];
let start = new Date().getTime();
let end = start+1000*60*60;
for (let i=0;i<500;i++){
	subitems.push({
  	start: start,
    end: end,
    name: "item"+i
  });
  start=end;
  end=start+(1000*60*60);
}
let series=[];
for (let j=0;j<100;j++){
	series.push({
        name: 's_'+j,
        data: JSON.parse(JSON.stringify(subitems))
       });
}
Highcharts.ganttChart('container', {
  
    series: series,
    chart: {
                zoomType: 'x',
                panning: {
                    enabled: true,
                    type: 'x',
                },
                panKey: 'shift',
   }
});
console.log('chart done');
```
Feel free to modify i/j parameters to your liking.
#### Product version
Highcharts Gantt JS v10.1.0 (2022-04-29)

#### Affected browser(s)
All

#### Related info:
https://www.highcharts.com/forum/viewtopic.php?t=42013
https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/37673773-gantt-boost

#### Personal notes:
This is a show-stopper for Gantt chart for any serious data volume.

**Comment by karolkolodziej** [comment]
Thank you @pkExec for reporting this issue.
Indeed rendering so many points in Gantt takes some time.

**Comment by cakkypamucm** [comment]
1) Any news about suppose fix date?
2) Is possible workaround exist?

**Comment by karolkolodziej** [comment]
1. There is no ETA for this ticket.
2. Also there is no workaround for now. You only can try to improve performance by disabling some of the visual effects like shadows, animations etc.
3. We don't have such a demo but we have methods that will make it possible to do it. Please contact our [support team](https://www.highcharts.com/blog/support/) they will help you achieve this.

**Comment by pkExec** [comment]
@cakkypamucm It's a structural implementation decision that cripples Highcharts Gantts, the visual effects have nothing to do with the root of the problem. I'm afraid this module needs a complete rewrite from scratch. Compare it to other high-performing Gantt JS libraries, and you'll see where the problem lies. My advise is don't waste time on this until it's rewritten, because it won't scale at all. As I said, it's a show-stopper.

**Comment by cakkypamucm** [comment]
> @cakkypamucm It's a structural implementation decision that cripples Highcharts Gantts, the visual effects have nothing to do with the root of the problem. I'm afraid this module needs a complete rewrite from scratch. Compare it to other high-performing Gantt JS libraries, and you'll see where the problem lies. My advise is don't waste time on this until it's rewritten, because it won't scale at all. As I said, it's a show-stopper.

@pkExec, thanks for answer!
Sorry, if off topic:
1) Which high-performing Gantt JS libraries do you mean? (including proprietary/paid ones) 
_// I tried (several years ago) [DHTMLX Gantt](https://dhtmlx.com/docs/products/dhtmlxGantt/) - poor settings and [anygantt](https://www.anychart.com/en/products/anygantt/overview/) - very-very buggy!_ 
2) Do you know any gantt libs on canvas? (including proprietary/paid ones)
3) Is it easy to configure these libs? Do they have large number of settings and well documented, intuitive API, like Highcharts? (I really like Highcharts, they give you very pleasant DX. But Highcharts Gannt out-of-the-box has many issues (like this one or [vertical scrollbar](https://stackoverflow.com/a/67738868))

**Comment by karolkolodziej** [comment]
@cakkypamucm 
2. No that should be all for now you disable it in order to increase performance.
3. StackOverflow or forum should work.
