### ISSUE TITLE
gridLine and axis line do not align

### ISSUE THREAD

**Issue by Ningster** [highcharts/highcharts#17412]
#### Expected behaviour
The first and the last gridLine should be aligned to the axis line.
<img width="189" alt="image" src="https://user-images.githubusercontent.com/8133907/174702686-13d22feb-352b-4677-bcaf-442f437b70b5.png">

#### Actual behaviour
The first/last gridLine is beyond/beneath the axis line.
<img width="173" alt="image" src="https://user-images.githubusercontent.com/8133907/174702708-f8fce97b-a5fb-4ff4-8b4a-03be937002c1.png">

#### Live demo with steps to reproduce
https://jsfiddle.net/curarning/xs3fgj12/16/

#### Product version
Highcharts JS v10.1.0 (2022-04-29)

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Thank you @Ningster  for reporting the issue.

To be honest we have not considered using such wide lines.
For smaller values line 2 or 3 this issue isn't so visible.

**_Workaround:_**
If you are going to use it that way, you can always manually increase the size of the axis line.
Demo: https://jsfiddle.net/BlackLabel/gvt46h0u/

**Comment by Ningster** [comment]
OK, I'll use the workaround. Thanks for the reply.
