### ISSUE TITLE
ContinuosLineSeries and ContinuosAreaSeries

### ISSUE THREAD

**Issue by Epomops** [highcharts/highcharts#17422]
Hello,

a useful and interesting possibility would be to add non-discrete series (for example sin, cos, log, ...) in conjunction, typically, with standard series.

Today it is possible to obtain the results in various ways, in particular by creating a fairly dense dummy dataset and possibly modifying it in case of zoom in.

However, the result is artificial and poorly performing. It would be really fantastic to have native series in this direction, which optimize the number of points to be drawn according to the size of the graph, the zoom level, the interaction with the mouse pointer ....

A "continuous series" could be defined by the generating function and possibly by other parameters such as XMin, XMax.

More complex but equally intriguing would be the possibility of defining parametric functions, a sort of continuous version of the scatter series.

A thousand thanks,
marcello.

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by raf18seb** [comment]
Hi @Marcelluszebra, thank you for creating a feature request ticket! Let's wait for more votes and gather more feedback.
