### ISSUE TITLE
SVG export: "required attribute "d" not specified" when plot line is out of axis range

### ISSUE THREAD

**Issue by giorgio130** [highcharts/highcharts#17431]
#### Expected behaviour
SVG export should produce a valid SVG document.

#### Actual behaviour
Exporting an area chart with a plot line outside the visible area is producing an invalid SVG.

#### Live demo with steps to reproduce
https://jsfiddle.net/m7s8wfha
Use button "Download SVG vector image"
Validate the SVG on https://validator.w3.org/check

The "path" node related to the plot line is added to the svg, but is missing required attribute "d".

![my-blog-vistor-count-for](https://user-images.githubusercontent.com/355228/175257060-2a7d09ba-0208-4287-b19f-167ff33c0113.svg)

#### Product version
v10.1.0 and lower versions

#### Affected browser(s)
Any

**Comment by raf18seb** [comment]
Hi @giorgio130, thank you for reporting the problem.

Indeed, when the plotLine is out of the plotarea, the SVG element is created but the `d` attribute is not added.
Workaround: add a simple `"M 0 0"` path if the returned path is `null`:
```js
(function(H) {
  H.wrap(H.Axis.prototype, 'getPlotLinePath', function(proceed, options) {
    return proceed.apply(this, Array.prototype.slice.call(arguments, 1)) || 'M 0 0';
  });
}(Highcharts))
```

**Comment by giorgio130** [comment]
Hi @raf18seb , thanks a lot for this workaround. It seems to be working fine for our use-case.
