### ISSUE TITLE
Highstock.NET RangeSelectorButton Not Working When Count = 1

### ISSUE THREAD

**Issue by fceci90** [highcharts/highcharts#17434]
#### Expected behaviour
Working with a Highstock .NET multiple line series chart.
When a RangeSelectorButton Count is set to 1, I expect to see it in the JavaScript rendered on the page. When these buttons are clicked, I expect the chart to be filtered to display the proper time range. 

#### Actual behaviour
Of the multiple buttons on my chart, three have a count equal to 1; 1 month, ytd, and 1 year. None of them have "count": 1 rendered in the JavaScript. However, the YTD button still works. When 1 month or 1 year buttons are pressed, all data is shown.

This is an excerpt of the JavaScript rendered on the page:
`"rangeSelector":{"allButtonsEnabled":true,"inputEnabled":false,"selected":4.0,"buttons":[{"text":"1m","type":"month","title":"View 1 month"},{"title":"View 3 months","count":3.0,"type":"month","text":"3m"},{"title":"View 6 months","count":6.0,"type":"month","text":"6m"},{"text":"YTD","type":"ytd","title":"View year to date"},{"text":"1y","type":"year","title":"View 1 year"},{"title":"View 3 years","count":3.0,"type":"year","text":"3y"},{"title":"View 5 years","count":5.0,"type":"year","text":"5y"},{"text":"All","type":"all","title":"View all"}]}`

#### Live demo with steps to reproduce
I do not have a live demo. I attempted to make one on dotnetfiddle.net, but the solution was unable to reference Highsoft even though the nuget package was included. If you need more information, please reach out.

#### Product version

Nuget Packages:
Highsoft.Highcharts 10.1.0.1
Highsoft.Highstock 10.1.0.1

JavaScript files are the latest ones at this time:
src="https://code.highcharts.com/stock/highstock.js" Highstock JS v10.1.0 (2022-04-29)
src="https://code.highcharts.com/stock/modules/exporting.js"  Highcharts JS v10.1.0 (2022-04-29)

#### Affected browser(s)
All that I've tested:
Microsoft Edge version 102.0.1245.44 (Official build) (64-bit)
Google Chrome version 103.0.5060.53 (Official Build) (64-bit)
Mozilla Firefox version 101.0.1 (64-bit)
Mozilla Firefox Developer Edition version 102.0b9 (64-bit)

#### Other Comments
This seems to be related to the same issue affecting other properties such as Legend, discussed in issue number 16043 here: https://github.com/highcharts/highcharts/issues/16043

**Comment by fceci90** [comment]
@raf18seb It does seem to be .NET related only. In the example jsFiddle link you provided, when I add "count": 1.0 to 1 month, YTD, and 1 Year time frame buttons the chart works as intended. Currently we are using Highcharts with AngularJS and it works properly there as well. (We are migrating off of AngularJS to a .NET implementation).

This is the same result with issue number 16043. I can add 
legend: {
    enabled: true
 },
 to the configuration in the jsFiddle and it works fine using JavaScript, and it also works in my current implementation using AngularJS.

**Comment by brofixo** [comment]
@fceci90 By default Count = 1 and you won't see that in JS but it should work correctly (https://api.highcharts.com/highstock/rangeSelector.buttons.count).
