### ISSUE TITLE
Pie chart Sub-title is overlapped on the Title when Title and Sub-title both are allign to "center" and verticalAlign to "bottom" 

### ISSUE THREAD

**Issue by Ajijulhoque** [highcharts/highcharts#17456]
#### Expected behaviour
Sub-title shouldn't overlap on top of the Title; when Title and Sub-title both are allign to "center" and verticalAlign to "bottom".
Title and Sub-title 

#### Actual behaviour
Pie chart Sub-title is overlapped on the Title; when Title and Sub-title both are allign to "center" and verticalAlign to "bottom" 

#### Live demo with steps to reproduce
https://jsfiddle.net/Ajijul/rokpu8e2/73/

#### Product version
Highcharts JS v10.1.0 (2022-04-29)

#### Affected browser(s)
All the browsers.

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by raf18seb** [comment]
Hi @Ajijulhoque,

This is the expected behavior. When `verticalAlign` is set, the title behaves the same as if `floating` is set to `true`, see docs: https://api.highcharts.com/highcharts/title.verticalAlign

> The vertical alignment of the title. Can be one of "top", "middle" and "bottom". When a value is given, the title behaves as if [floating](https://api.highcharts.com/highcharts/title.floating) were true.

**Comment by Ajijulhoque** [comment]
Hi @raf18seb,
Thank you for your reply. So you are saying that; Sub-title overlapped on the title is expected behavior when "vertialAlign" = "middle".
I'm using Highchart in my application where users can choose Title and Sub-title positions. If user selects "vertialAlign" = "middle" for Title and Sub-title; Sub-Title gets overlapped on Title as mentioned in [https://jsfiddle.net/Ajijul/rokpu8e2/73/](url) and also screenshot high-lights the overlapping issue.
![image](https://user-images.githubusercontent.com/22919251/177142786-b8baa132-852d-4848-a059-e555858eb8c6.png)

User expects Sub-title shouldn't be overlapped with the Title as it appears when "vertialAlign" = "top".
![image](https://user-images.githubusercontent.com/22919251/177145223-337d6fa0-7d6c-46e1-9b77-fef0411801c1.png)

Please suggest me some solution for it.

**Comment by raf18seb** [comment]
@Ajijulhoque,
Yes, at this moment (as the API says) this is expected behavior - we haven't added the overlapping logic for title and subtitle for different `verticalAlign` options.
This can be treated as a feature request if you want this logic to be added in the future.

At this moment, the only thing I can propose is to allow users to set additional `title.y` and `title.x` values in the additional input, see demo: https://jsfiddle.net/BlackLabel/sucf2kmo/ (y: -30)

**Comment by Ajijulhoque** [comment]
Hi @raf18seb,
Thank you for accepting it as a feature request.

**Comment by Ajijulhoque** [comment]
Hi @raf18seb,
When can we expect delivery of this feature?

**Comment by raf18seb** [comment]
Hi @Ajijulhoque,

The standard procedure is to wait for other users to vote for this feature (by adding a thumbs up as I did at the very top of this conversation). When we see more users interested, then we consider adding it to the core.
Unfortunately, we don't have ETA for it yet.
