### ISSUE TITLE
pointPlacement not working properly in column charts when using the navigator

### ISSUE THREAD

**Issue by janitza-anjakr** [highcharts/highcharts#17460]
Hi there!

To compare multiple time periods, we group our columns with the pointPadding and pointPlacement property. This works mostly great, but sometimes while using the navigator, the columns are misplaced. There is clearly a connection with the number of data points of each series in the selected x range.
In the jsfiddle, we implemented some buttons to adjust the max property of the x axes. Setting xMax to 2 or 11, everything is fine. But setting xMax nearly to 0, the column groups are placed closer and closer to one another. Setting xMax to 0.025, the columns are even placed above on another, which makes it hard to see anything. Suprisingly, setting xMax exactly to 0, everything is fine again.

JSFiddle: https://jsfiddle.net/ckeim/dyLfg94s/106/

**Comment by raf18seb** [comment]
Hi @janitza-anjakr,
Thank you for contacting us with your issue.

Does setting the `plotOptions.series.pointRange` to 1 solves your issue?
https://api.highcharts.com/highcharts/plotOptions.column.pointRange

Demo: https://jsfiddle.net/BlackLabel/r3z6sdfg/

**Comment by janitza-anjakr** [comment]
Hi raf18seb, we tried it out and it works like a charm. This solves our issue. Thank you very much!

**Comment by raf18seb** [comment]
Closing as resolved.
