### ISSUE TITLE
Draggable3D.js library returning a 404

### ISSUE THREAD

**Issue by rbnfsh** [highcharts/highcharts#17474]
#### Expected behaviour
being able to drag and re-orient 3D charts

#### Actual behaviour
no dragging on any 3D charts

**Comment by pawellysy** [comment]
Hi @rbnfsh, Thanks for creating this issue!
We have no module as `draggable3D.js`. I guess you are reporting the feature request? 
If so, please use the `feature-request` template next time :)

Let me know if this is the case! Thanks!

**Comment by rbnfsh** [comment]
My apologies - I was using this instance and it changed filenames...
https://github.com/paulo-raca/highcharts-draggable-3d
