### ISSUE TITLE
Spiderweb Shared Tooltip not rendering

### ISSUE THREAD

**Issue by rw-jchartis** [highcharts/highcharts#17472]
#### Expected behaviour
Shared Tooltip should render multiple datapoints for the respective variable.

#### Actual behaviour
Tooltip does not render at all and the following error is thrown in the console.

![highcharts_spiderweb](https://user-images.githubusercontent.com/103261038/177546262-99e3dbd0-8b4d-4420-9ebe-122592735a44.PNG)

#### Live demo with steps to reproduce

Shared tool tip is no longer working on the demo provided via the Highcharts website. Just hover over a datapoint and you will see the tool tip does not render.
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/polar-spider

#### Product version

Latest version from https://code.highcharts.com

#### Affected browser(s)
Chrome, Firefox, IE.

**Comment by pawellysy** [comment]
Thanks  @rw-jchartis for reporting this issue!
It's a regression, which popped up in the latest version v10.2.0.


`internal note`
Bisected to 14d5a98828db189ab6b83d37e95ed69b68d837c8

FYI @bre1470

**Comment by raf18seb** [comment]
The problem is with a `this` context which should be a polar composition instead of series.
Possible culprit: https://github.com/highcharts/highcharts/blob/e23cfb716e5af7265b27683e4440ccea8e6043f5/ts/Series/PolarComposition.ts#L147-L151

Workaround (pass a correct context): https://jsfiddle.net/BlackLabel/x64hetLn/

**Comment by pawellysy** [comment]
Hi @GabrieleT0, The workaround is posted in the previous post: https://jsfiddle.net/BlackLabel/x64hetLn/

**Comment by GabrieleT0** [comment]
> Hi @GabrieleT0, The workaround is posted in the previous post: https://jsfiddle.net/BlackLabel/x64hetLn/

Thank you so much.

**Comment by jsokol** [comment]
Any idea when this bug fix will go live?  We would prefer not to implement the aforementioned workaround if this will be updated sooner, rather than later.  Thanks.

**Comment by pawellysy** [comment]
Hi @jsokol, We are currently during the vacation period, so all of the fixes/releases are currently on hold. For now, you need to use the workaround. Sorry for the inconvenience :(

**Comment by jsokol** [comment]
> Hi @jsokol, We are currently during the vacation period, so all of the fixes/releases are currently on hold. For now, you need to use the workaround. Sorry for the inconvenience :(

Totally understand you guys being on vacation and I'm not pushing for an immediate fix.  I guess what I'm trying to figure out is when you'll be off vacation and fixes/releases are no longer on hold so this can be addressed?  Are we talking days? 
 Weeks?  Months?  What kind of priority will this be given when you are back?  Thanks.

**Comment by pawellysy** [comment]
@jsokol, the fix is already in review, so in terms of development, there is not much to take into consideration. It is a matter of the date of the next release, which I would expect to be near the end of August.

**Comment by jsokol** [comment]
> @jsokol, the fix is already in review, so in terms of development, there is not much to take into consideration. It is a matter of the date of the next release, which I would expect to be near the end of August.

This helps a ton!  Thank you!
