### ISSUE TITLE
How to create custom highcharts file, errors encountered.

### ISSUE THREAD

**Issue by K-Thompson** [highcharts/highcharts#17488]
Following the documentation for [how to create custom highcharts file](https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files).

#### Expected behaviour

At this step:

Open the unpacked folder highcharts-master in a command line or terminal and run **npm install** to install any required dependencies. 

I expect no errors.

#### Actual behaviour

However, on Windows 10, I get many errors. I've tried executing NPM install from VS Code's Bash terminal and Powershell terminal. I've also tried it from the Windows command prompt. **The package installation fails completely**.

Here are samples of the errors:

```
C:\wwwroot\highcharts10\highcharts-master>npm install
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated lolex@6.0.0: lolex has been renamed to @sinonjs/fake-timers. No API changes made. Please use the new package instead
```

And some more:

```
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\wwwroot\highcharts10\highcharts-master\node_modules\node-expat
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.10.0 | win32 | x64
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
```

#### Live demo with steps to reproduce

N/A.

#### Product version

Highcharts v10.2

#### Affected browser(s)

N/A.

**Other points, questions:**

1. Is the package install not supported on Windows?
2. Or are there other prerequisites? 

I also deleted the package.lock file and tried the install again. Same results.

**Comment by K-Thompson** [comment]
Some more details. On a hunch, I removed the following lines from package.json's dev dependencies:


```
    "@highcharts/highcharts-documentation-generators": "github:highcharts/highcharts-documentation-generators#v0.5.33",
    "@highcharts/highcharts-utils": "github:highcharts/highcharts-utils#v1.0.1",
    "highcharts-assembler": "github:highcharts/highcharts-assembler#v1.4.1",
    "highcharts-declarations-generator": "github:highcharts/highcharts-declarations-generator#v1.1.20",
    "highsoft-websearch": "github:highcharts/highsoft-websearch#v0.0.3"
```

Running NPM installed, installed the other dev dependencies with only some minor warnings about deprecated packages.

But "@highcharts/map-collection": "^2.0.0" failed to install:

```
> highcharts@10.2.0 prepare
> husky install

fatal: not a git repository (or any of the parent directories): .git
```


**Are there rights issues involved to access these Highcharts repositories?**

After this, running **NPM run test**, produces these results:

```
> highcharts@10.2.0 test
> npx gulp test-ts --force && npx gulp test --force --speak

Error: Cannot find module 'highcharts-assembler/src/build.js'

```

**Comment by pawellysy** [comment]
Hi @K-Thompson, thanks for reporting this issue. 

I went through the reproduction steps, that you provided and everything worked in order for me. 
Downloading zip is the same thing as cloning the repository, and running the following steps on the master branch, which is constantly being developed. We run our development on Mac as well as on Windows, so this is not a case of the OS. 

Could you specify what node version you are using? 
The dedicated node version right now is `v16.13.0` with npm version `v8.1.0`

@raf18seb are there any additional steps Windows users must perform before building the Highcharts repository? (Judging by error message e.g. installing Python)

**Comment by K-Thompson** [comment]
Thanks, @pawellysy for your very prompt reply.

I'm running stable, slightly newer versions of Node and NPM.

$ npm --version
8.11.0

$ node --version
v16.16.0

I had seen that error about Python missing, but I took the documentation literally

`Open the unpacked folder highcharts-master in a command line or terminal and run npm install to install any **required dependencies**`

so I didn't attempt to install it earlier.  I've now **installed Python**, and it's on the Windows path:

MINGW64 /c/wwwroot/highcharts10/highcharts-master
$ py --version
Python 3.10.5

I deleted the prior highcharts-master folder. I restarted Windows and then cleaned out the temp folder for good measure.

Opened a Bash shell in highcharts-master and ran NPM install.

I still get below errors (this time, this is the complete output). Hopefully, the problem isn't with the newer versions of Node/NPM from what you are using.

(see my note after these errors)

```
MINGW64 /c/wwwroot/highcharts10/highcharts-master
$ npm install
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated lolex@6.0.0: lolex has been renamed to @sinonjs/fake-timers. No API changes made. Please use the new package instead
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\wwwroot\highcharts10\highcharts-master\node_modules\node-expat
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.16.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.5 found at "C:\Program Files\Python310\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.16.0/node-v16.16.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.16.0/node-v16.16.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.16.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v16.16.0/win-x86/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.16.0/win-x64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.16.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.16.0/SHASUMS256.txt
npm ERR! gyp http 404 https://nodejs.org/download/release/v16.16.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.16.0/win-x64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.16.0/win-x86/node.lib
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\kthom\AppData\Roaming\nvm\v16.16.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\kthom\AppData\Roaming\nvm\v16.16.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\kthom\AppData\Roaming\nvm\v16.16.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
npm ERR! gyp ERR! stack     at C:\Users\kthom\AppData\Roaming\nvm\v16.16.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Users\kthom\AppData\Roaming\nvm\v16.16.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm ERR! gyp ERR! stack     at C:\Users\kthom\AppData\Roaming\nvm\v16.16.0\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\kthom\AppData\Roaming\nvm\v16.16.0\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kthom\\AppData\\Roaming\\nvm\\v16.16.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\wwwroot\highcharts10\highcharts-master\node_modules\node-expat
npm ERR! gyp ERR! node -v v16.16.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

```

I'm just seeing this:

**npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio**

I see there is a free version called [Visual Studio Community](https://visualstudio.microsoft.com/vs/community/#:~:text=09%2D08%3A00-,Visual%20Studio%20Community,web%20applications%20and%20cloud%20services.). I'm going to save this comment so as not to lose the above documentation. I'll download VS, install, reboot. And we'll see what happens.

**Comment by K-Thompson** [comment]
Visual Studio fixed the errors. I still get the errors about deprecated packages.

To confirm the package installation, I ran the below NPM scripts. 

`test`
`ts-compile:test`

Both reported some warnings.

Ts-compile:test reported this error:

```
C:\wwwroot\highcharts10\highcharts-master>npm run ts-compile:test

> highcharts@10.2.0 ts-compile:test
> npx tsc -p test && npx tsc -p samples

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
test/test-controller.ts:35:42 - error TS2503: Cannot find namespace 'Highcharts'.
```

So I'm not sure yet if I'm going to be able to build minified ES6 modules successfully or not. But I'll give it a go over the next day or so.

**Comment by pawellysy** [comment]
Try running `npx gulp scripts` command, to see if the package builds. If this command runs without problems, everything is in order. Thanks for the thorough reproduction and fixing steps, we might consider putting it in the documentation, since these are important things to note.

**Comment by K-Thompson** [comment]
From the Bash terminal in VS code:

```
$ npx gulp scripts --force
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
[05:38:00] Local modules not found in C:\wwwroot\highcharts10
[05:38:00] Try running: npm install
```

However, from the CMD terminal:

`npx gulp scripts --force`

completed without any issues.

When I tried without the `--force` flag, I had this message:

`Source code has not been modified since the last successful run`

I'm not going to bother figuring out why this does not work from the Bash terminal. I only mention it in case this comes up again, and so folks know it's possible for build to fail in one terminal and not the other.

(Personally, I would mention that Python and Visual Studio are required to install the packages. It would have saved me two days. Yes, I did see the message about Python being missing, but when the docs say that the process installs all dependencies, I took them at their word, which sent me down other rabbit holes looking for the problem. Further, without both Python and VS, there were so many error messages including ones about moved NPM modules that there were a lot of rabbit holes to go down!)

Thanks for the initial confirmation that the process was supported on Windows. Just knowing that helped a lot.

I think this can be closed.

**Comment by pawellysy** [comment]
Good to hear, that you managed to get this working. I will leave this issue open until the docs are updated. Thanks again!

**Comment by K-Thompson** [comment]
Ok, since that's the case, continuing with the [example](https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files)

For `custom.src.ts`, I copied the example code as-is.

I modified the HTML slightly (added DOCTYPE, modified HEAD):

```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>

<body>
	<div id="container"></div>
	<script type="module">
		import Highcharts from './custom.src.js';
		Highcharts.chart('container', {
			series: [{
				type: 'line',
				data: [1, 32, 42]
			}]
		});
	</script>
</body>

</html>
```

Copied custom.src.js, as instructed, and tried the page in Chrome v103.

I get this error:
        
`       Uncaught SyntaxError: The requested module './custom.src.js' does not provide an export named 'default' (at chart.html:14:10)`


When I try the "classic manner" load, the chart is generated just fine.
        

**To resolve the issue of loading a module, I had to change the script tag to use this file:**

`import Highcharts from './es-modules/masters/custom.src.js`



That's fine, but it does not get me to where I need to be. I still need a bundle, not individual module files.

I have been able to successfully create a Highcharts bundle using Rollup, following the documentation suggestion to use example in 

`ts\masters\highcharts.src.ts`

As I said, the bundle works, but, the issue I'm still having is when I follow the importing of the bundle with: 

`import 'https://code.highcharts.com/es-modules/masters/highcharts-3d.src.js';`

And try to load the chart, I get this error:

`Pie3DPoint.js:29 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at Pie3DPoint.js:29:47`


Which is this code:

```
import SeriesRegistry from '../../Core/Series/SeriesRegistry.js';
var PiePoint = SeriesRegistry.seriesTypes.pie.prototype.pointClass;
```

Looking at this `SeriesRegistry.seriesTypes` in the debugger, the only seriesTypes defined is `column`.

I started to look at the code but I saw the other day several comments about some code being deprecated.

Not sure if I'm screwing up, or Rollup is, or if there's a problem with the source itself (still using some deprecated code?). Strange though that the bundle does work but the downstream dependency on the bundle does not.

**Comment by bre1470** [comment]
Thank you for the feedback!

- The original problem is caused by a missing python installation, required by `node-gyp`.
- With your last problem the system can sometimes choke over modules that are not fully ESM compatible. In these cases you have to import `es-modules/masters` files _in order_. For example import `highcharts` master before `highcharts-3d` master. Both `highcharts-3d` and `highcharts-more` do not work on their own.
