### ISSUE TITLE
Tooltip shows Unix millis instead of a formatted timestamp

### ISSUE THREAD

**Issue by ejain** [highcharts/highcharts#1748]
Looks like Highcharts can't figure out how to format the timestamp in the tooltip in a time series with a single data point; the tooltip ends up showing the Unix millis.

http://jsfiddle.net/r9TzZ/

**Comment by oysteinmoseng** [comment]
This is still relevant with current code. It would make sense to format any value on a datetime axis as a date in the tooltip.

**Comment by kamilkulig** [comment]
Similar problem occurs in this demo: https://jsfiddle.net/BlackLabel/7xqvk62p/ Tooltip's header is formatted incorrectly if any of the points has the `name` proerty set. Everything works fine if all points have no name: https://jsfiddle.net/BlackLabel/5n3vLtu9/
