### ISSUE TITLE
Invisible issue for line after chart width with zones.

### ISSUE THREAD

**Issue by altmshfkgudtjr** [highcharts/highcharts#17481]
That problem occurs on charts with long data that have [`zones`](https://api.highcharts.com/highstock/plotOptions.series.zones).
I searched for existing issues, but couldn't find any similar cases. 😢

I also tested the [`cropThreshold`](https://api.highcharts.com/highcharts/series.line.cropThreshold) attribute, but there was no change.

<br />

#### Actual behaviour

**[With `zones` - JsFiddle](https://jsfiddle.net/qpnb25fj/4/)**

<img width="500" alt="image" src="https://user-images.githubusercontent.com/47492535/177948713-99d7e6e7-22d4-42aa-b16e-e3265fa694b8.png">

**[Without `zones` - JsFiddle](https://jsfiddle.net/qpnb25fj/5/)**

<img width="500" alt="image" src="https://user-images.githubusercontent.com/47492535/177948622-ab7bb9eb-a606-45fa-b48c-3b6b44fa48ae.png">

<br />

#### Expected behaviour

The line `<path>` must also be connected to the point that exists after scrollWidth. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/47492535/177950590-8f2d1668-84ee-4ffa-8ded-394302993615.png">

<br />

#### Product version
`Highcharts 10.1.0`

<br />

#### Affected browser(s)
`Chrome 103.0.5060`

**Comment by karolkolodziej** [comment]
Hi @altmshfkgudtjr!
Thank you for reporting that issue.

**Comment by altmshfkgudtjr** [comment]
Oooh it works for me.

Thanks for the quick fix! Long live the high chart!

**Comment by pawellysy** [comment]
hi @altmshfkgudtjr, we keep issues open, until we merge the attached PR. We do that to know that the bug is fixed on master and won't happen in the next release. I will reopen this issue
