### ISSUE TITLE
Question: is Org Chart already supported?

### ISSUE THREAD

**Issue by oferRounds** [highcharts/highcharts#17497]
Hi! Following this [issue](https://github.com/highcharts/highcharts/issues), I wanted to ask if Org Chart support is already live? I looked on the website and docs, but couldn’t find it
Thank you!
Ofer

**Comment by raf18seb** [comment]
Hi @oferRounds, yes it's supported, see an official demo: https://www.highcharts.com/demo/organization-chart
and docs: https://www.highcharts.com/docs/chart-and-series-types/organization-chart

GitHub is our issues/features tracker only so please contact us on dedicated support channels with similar questions. Thanks in advance!
https://www.highcharts.com/blog/support/
