### ISSUE TITLE
Long chart titles for charts are not wrapped/truncated

### ISSUE THREAD

**Issue by nickelser** [highcharts/highcharts#175]
See http://jsfiddle.net/ebuTs/2555/ for an example.

**Comment by alwinaugustin** [comment]
I am getting this issue when title is at the bottom for donut charts

**Comment by highslide-software** [comment]
Demo please?

**Comment by harshilbpatel** [comment]
Title wraps when using in the top. but when using verticalAlign: 'bottom'  for title, subtitle, credits. all get truncated:  modified jsfiddle here: http://jsfiddle.net/54EGT/16/

please allow wrapping of the title, subtitle  and credits when verticalAlign: 'bottom' is set.

**Comment by pawelfus** [comment]
Hi @harshilbpatel - please take a look: #5598

**Comment by karolinakuzniewicz** [comment]
Having the same problem. Ideal will be that the title length may affect on plot area e.g. if the tittle is very long, the plot area is smaller to fit in chart dimensions. Right now using `floating` is not helpful and a very long title overlaps on plot area.
