### ISSUE TITLE
Screen tearing on the streamgraph demo

### ISSUE THREAD

**Issue by alexmherrmann** [highcharts/highcharts#17509]
#### Expected behaviour
No screen tearing on streamgraph

#### Actual behaviour
There's screen tearing on the streamgraph demo

#### Live demo with steps to reproduce
https://user-images.githubusercontent.com/9485711/179044255-e341831b-361e-47b2-9e74-66dcc0bb3130.mp4

#### Product version
On the website demo @ https://www.highcharts.com/demo/streamgraph

#### Affected browser(s)
Chrome 103 running on a macbook pro with the M1 pro.

**Comment by karolkolodziej** [comment]
Thank you @alexmherrmann for reporting that issue.
I can reproduce it with similar hardware however this issue is only visible on the build-in Retina display. 
On external displays, everything works as expected.
Also opening the same demo in jsfiddle, does not result in tearing.

**Comment by alexmherrmann** [comment]
I noticed that when I moved it to my monitor too. Thanks for the reply. Feel free to close the issue if you believe no further action is necessary.
