### ISSUE TITLE
BowTie Chart

### ISSUE THREAD

**Issue by DanielTrefzer** [highcharts/highcharts#17506]
Dear Highcharts Team, 

we would like to have a chart type BowTie.

the origin of this chart is Risk Management. 
This Wiki explains the  basic idea: https://en.wikipedia.org/wiki/Bow-tie_diagram

Thanks

**Comment by pawellysy** [comment]
Hi @DanielTrefzer, thanks for creating this feature request!

**Comment by raf18seb** [comment]
Hi @DanielTrefzer,

I did a quick research and it came out that the BowTie chart is a general name for visualization the risk management which can be visualized in many different ways.
Could you provide a little bit more detailed specification?

For now, a similar chart can be achieved in Highcharts with less or more custom coding. See some of our official examples:
- a general example of drawing: https://www.highcharts.com/demo/renderer
- and the Organization chart which can be used as a base: https://www.highcharts.com/demo/organization-chart

**Comment by DanielTrefzer** [comment]
Hi @raf18seb 
thanks for your reply. 
We did collect some ideas and did also have a closer look into your examples. 

The org chart is a "nearly fit" approach but has some  cases that we can not cover. 
The Drawing will work but of course is not a default chart type. 


We think about it like this: 
We need a view different shapes for event, barrier, threat and consequence. (See picture) ahead

Also the possibility to click on it to have a "Context Menu" approach. 

We are also available for a online call. 

We think it will enhance the library towards more "special" charts like sankey or waterfall. 

Daniel
![image](https://user-images.githubusercontent.com/72071505/182181579-ab748351-a784-44c6-8986-bfb509ded6b5.png)

**Comment by raf18seb** [comment]
Hi @DanielTrefzer, thank you for more information.

> The Drawing will work but of course is not a default chart type.

Yes, you're right, it would require a lot of work and is only a simple showcase. Not useful in this case.

> We need a view different shapes for event, barrier, threat and consequence. (See picture) ahead
Also the possibility to click on it to have a "Context Menu" approach.

It seems like a very big customization of the Organization series. We don't provide those features at this moment.

The standard procedure at this stage is to wait for more users' votes. If this feature request gets popular, we will consider adding it to the library.
