### ISSUE TITLE
Passing Negative value to funnel/pyramid chart create unexpted result

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [highcharts/highcharts#17514]
#### Expected behaviour
Either negative value should be shown in chart or should not include in chart

#### Actual behaviour
When negative value is passed it affecting how other data is render in chart, and some of data are not getting render in chart

#### Live demo with steps to reproduce
1. Add Negative value in data object

https://jsfiddle.net/BlackLabel/z06t7pvw/

#### Product version
Highcharts 10.2.0

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hi @vyshnavmk-lumel, thanks for reporting this issue!
Indeed The funnel series should handle the case when the negative value of the point is passed. At the moment, I would advise just filtering out the negative points on the input. We will try to handle it on the Highcharts side too. Thanks!

**Comment by vyshnavmk-lumel** [comment]
Hi @pawellysy thanks for the replay, Just want to confirm this also, that funnel/pyramid chart does not render negative value?

**Comment by pawellysy** [comment]
@vyshnavmk-lumel, that's correct. The funnel chart should not render the negative values, but it isn't handled at the moment. We will keep this issue open, and the fix will be about handling this case. Thanks again for the report!
