### ISSUE TITLE
Including export module with scrolling breaks when returning from print action.

### ISSUE THREAD

**Issue by wasimanitoba** [highcharts/highcharts#17513]
#### Expected behaviour
- Include export module with scrollable chart
- Choose 'print' from the context menu, then cancel
- The chart labels and chart elements should return to their original position
- The highcharts-fixed-position div element should remain inside the highcharts-scrollable-area div element. 

#### Actual behaviour
- Upon cancelling the highcharts-fixed-position div element is no longer inside the highcharts-scrollable-area div element, which is now empty. 
- This causes the chart elements to move around on the page, moving very far from their original position in some cases and sometimes being hidden behind other chart elements.

Using the provided example fiddle for scrollable area, we can see the first chart on the left is the normal appearance, the chart in the middle is how the print preview appears and the chart on the right is after closing the print dialog.

The labels and menu appear in the middle of the chart for the print preview:

![image](https://user-images.githubusercontent.com/29640351/179336752-7734fc75-96e4-4592-bfdf-8bc7e690f383.png)

The labels and menu are still in the wrong place after ending the print preview, even covering part of the chart:
![image](https://user-images.githubusercontent.com/29640351/179336729-629f4940-6acc-48c0-87dc-45aaae45a5f2.png)

#### Live demo with steps to reproduce

https://jsfiddle.net/47kc6ajx/

#### Product version
Latest version

#### Affected browser(s)
Chrome, Firefox

**Comment by raf18seb** [comment]
Hi @wasimanitoba, thank you for reporting the issue.
