### ISSUE TITLE
Weird lines when use browser zoom on Safari

### ISSUE THREAD

**Issue by OstapBO** [highcharts/highcharts#17529]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/60663015/180009808-7a81bfa0-9534-49ce-a89c-1d7961596c63.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/60663015/180009716-ecf5d383-92ad-42e6-a9d3-5b3e9e87c55e.png)
![image](https://user-images.githubusercontent.com/60663015/180014666-c29a012d-23de-4f08-8efc-57627e117f36.png)

#### Live demo with steps to reproduce
Device - Macbook Pro 13

Safari - when playing with browser zoom - weird lines appear. I can see them when zoom percentage = 150%.
In Chrome don't see issue.
https://jsfiddle.net/jwgy4L5s/7/

#### Product version
"highcharts": "^10.2.0",
"highcharts-react-official": "^3.1.0"

#### Affected browser(s)
macOS v12.4, Safari 15.5

**Comment by pawellysy** [comment]
Thanks, @OstapBO, for reporting this issue!

Simplified demo: https://jsfiddle.net/BlackLabel/nsgz5yp6/

**Comment by OstapBO** [comment]
@pawellysy thanks for taking care!
Do you have any news so far ?
