### ISSUE TITLE
Inactive state does not apply correctly when boost is enabled

### ISSUE THREAD

**Issue by ParkerPosy** [highcharts/highcharts#17521]
#### Expected behaviour
Boost should work the same as non-boost:
    - The Halo should not have an opacity change applied to it
    - When hovering over a series in the legend or in the chart the other series should be transparent

#### Actual behaviour
The halo gets the opacity style applied to it instead of the non-hovered series.

Looks to have been broken since 9.1.1, 9.1.0 works as expected.

#### Live demo with steps to reproduce
Working in 9.1.0: https://jsfiddle.net/ParkerPosy/8g4s5wkb/
Broken in 9.1.1: https://jsfiddle.net/ParkerPosy/3rqt9s72/

#### Product version
Highcharts, Highstock

**Comment by ParkerPosy** [comment]
Working in 9.1.0: https://jsfiddle.net/ParkerPosy/8g4s5wkb/
Broken in 9.1.1: https://jsfiddle.net/ParkerPosy/3rqt9s72/

**Comment by raf18seb** [comment]
Hi @ParkerPosy,

When loading additional modules, always make sure that you load them in the same version as the core.
So, instead of
```
<script src="https://code.highcharts.com/stock/9.1.0/highstock.js"></script>
<script src="https://code.highcharts.com/modules/boost.js"></script>
```
use
```
<script src="https://code.highcharts.com/stock/9.1.0/highstock.js"></script>
<script src="https://code.highcharts.com/stock/9.1.0/modules/boost.js"></script>
```

It works fine when you match versions.

ps. I was surprised that it was working fine without any errors in the console for 9.1.1 when it shouldn't.

Closing as resolved, but feel free to ask/comment in case of any further questions/concerns.

**Comment by ParkerPosy** [comment]
@raf18seb I'm not sure that it is working as expected. 

If you comment out boost here, you'll see that the behavior changes, and hovering over a series makes the other series transparent. Instead, when boosted, the opacity change is applied to the halo that surrounds the point. You'll see that when boost is commented out, the halo is darker. I would expect boost to work the same. https://jsfiddle.net/ParkerPosy/3rqt9s72/

**Comment by raf18seb** [comment]
@ParkerPosy,

Thanks for clarifying! I can see the problem now.

Simplified demo: https://jsfiddle.net/BlackLabel/49g31bat/
It works the same in 9.1.0, 9.1.1 and the current 10.2.0 version.

In the non-boosted chart, the inactive state should change the opacity of the non-hovered series.
In the boosted chart, the inactive state shouldn't work at all. Instead, it changes the halo opacity of the hovered series.
