### ISSUE TITLE
Sankey nodes height 

### ISSUE THREAD

**Issue by ioanachi** [highcharts/highcharts#17532]
Hello, 

I am using sankey diagram and I have some issue with the height of the nodes. 
I am trying to find a way to modify the height of the nodes without them fusing in the vertical axes or remaining huge spaces between the nodes on the same column
All the links have the same weight that is 5 and for the nodes if I don't specify the height some of them are very high - 
![sankeyH](https://user-images.githubusercontent.com/30567873/180182584-c51c8ee8-8f07-42c9-bcb2-7081095bd732.JPG)
If I specify the height for all the nodes then there is space between the nodes on the same column 
![sankeyH2](https://user-images.githubusercontent.com/30567873/180184150-3c5f3c17-31b3-49de-bd64-0b4f54018888.JPG)
If I increase the height too much the nodes fuse together vertically
![sankey3](https://user-images.githubusercontent.com/30567873/180194000-ea07c40d-3611-4cff-99dc-e98a93e44c17.JPG)

I use   
  highcharts version10.2.0
   highcharts-react-official version 3.1.0

Thank you!

**Comment by pawellysy** [comment]
Hi @ioanachi, thanks for contacting us with your question!

GitHub is our issues/features tracker, so please get in touch with us on dedicated support channels with this kind of question. Thanks!
https://www.highcharts.com/blog/support/
