### ISSUE TITLE
Error when calling reflow to resize for print

### ISSUE THREAD

**Issue by hassa** [highcharts/highcharts#17533]
We are trying to reflow charts during print. Everything works as expected when printing via File -> Print or cmd+p, but using a button that triggers `window.print()` causes the error below.

#### Expected behaviour
`chart.reflow()` runs normally and the chart resizes.

#### Actual behaviour
The following error occurs:

```
highcharts.js:60 Uncaught Error: Failed to execute 'invoke' on 'CreateHTMLCallback': The provided callback is no longer runnable.  
    at q.parseMarkup (highcharts.js:60:463)
    at new q (highcharts.js:58:15)
    at d.buildSVG (highcharts.js:121:254)
    at I.buildText (highcharts.js:135:263)
    at f.css (highcharts.js:81:335)
    at f.<anonymous> (highcharts.js:379:259)
    at Array.forEach (<anonymous>)
    at f.layOutTitles (highcharts.js:379:50)
    at f.setSize (highcharts.js:388:437)
    at Number.<anonymous> (highcharts.js:387:96)
```

#### Live demo with steps to reproduce
Click the Print button and you'll see the error in the console (in Chrome's console - I can't get the Fiddle console to show the error for some reason)

You'll also notice that the chart does not reflow to fit the print size.

http://jsfiddle.net/t0pn9c27/

#### Product version
Highcharts JS v10.2.0 (2022-07-05)

#### Affected browser(s)
Chrome (at least, did not check other browsers yet)

**Comment by raf18seb** [comment]
Hi @hassa,

We recommend using our `chart.print` method for printing the chart. You can set the `width` and `height` in the `chart.events.beforePrint` and `chart.events.afterPrint` callbacks, see demo: https://jsfiddle.net/BlackLabel/hr2vu7my/
Is this solution enough for you?

**Comment by hassa** [comment]
@raf18seb the chart we're printing is part of a page with many other charts, so it makes sense to print it as one report.

Is the issue I reported a none-issue/expected behaviour?

**Comment by raf18seb** [comment]
@hassa seems like it's a Chromium bug reported [here](https://bugs.chromium.org/p/chromium/issues/detail?id=956832) and [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1101344).

**Comment by hassa** [comment]
@raf18seb clear - thank you. I'll close this issue.

**Comment by Techn1x** [comment]
Just making sure to link the long-running main thread on this issue, in case people come across this and want more highcharts-specific details 
https://github.com/highcharts/highcharts/issues/16931
