### ISSUE TITLE
Venn Diagram: Make the circle sizes proportional to a reference value

### ISSUE THREAD

**Issue by ysbun** [highcharts/highcharts#17535]
Hello,

I would like to create two Venn diagrams to compare some indicators A and B to **the same indicator X**.

• Demo of comparing A to X: https://jsfiddle.net/ysbun/9uoajwft/
```
Highcharts.chart('container', {
    series: [{
        type: 'venn',
        name: 'Comparison',
        data: [{
            sets: ['X'],
            value: 5040050,
            name: 'X indicator'
        }, {
            sets: ['A'],
            value: 8409984,
            name: 'A indicator'
        }, {
            sets: ['X', 'A'],
            value: 4712512,
            name: 'Intersection'
        }]
    }],
    title: {
        text: 'Venn proportional size'
    }
});
```

• Demo of comparing B to X: https://jsfiddle.net/ysbun/g8h47boL/
```
Highcharts.chart('container', {
    series: [{
        type: 'venn',
        name: 'Comparison',
        data: [{
            sets: ['X'],
            value: 5040050,
            name: 'X indicator'
        }, {
            sets: ['B'],
            value: 2308224,
            name: 'B indicator'
        }, {
            sets: ['X', 'B'],
            value: 147236,
            name: 'Intersection'
        }]
    }],
    title: {
        text: 'Venn proportional size'
    }
});
```

Even though the indicator **X has the same value** in both examples, **the size** of the circle that represents X **is completely different**; this suggests that the chart uses a different scale.

It would be nice if it could be possible to make the scale relative to the value of the indicator X so that the circle representing it is always **the same size across all comparison charts**?

Thank you!

**Comment by raf18seb** [comment]
Hi @ysbun, thank you for contacting us with your issue.

> this suggests that the chart uses a different scale

Yes, you're right. The X sets indeed have the same values, but they are different when compared to other values.

Consider these demos: https://jsfiddle.net/BlackLabel/rLcwo0ht/ and https://jsfiddle.net/BlackLabel/3m7uyv8a/
X columns have the same value of `y: 10`, but their heights are totally different and depend on the yAxis' max:
![image](https://user-images.githubusercontent.com/23310742/180744829-41b121aa-f9f4-4a63-b0eb-d3ead176ba4c.png)

vs

![image](https://user-images.githubusercontent.com/23310742/180744886-d3ed23e6-9525-4f6c-bb24-209585973486.png)

On standard graphs, the scale can be set very easily by setting mentioned `yAxis.max`. On our Venn chart, there are no axes so I don't think it's possible at this moment.

Can be considered as a feature request so I'm leaving the ticket open.
