### ISSUE TITLE
Weird truncation/ellipsis rule for xAxis labels in horizontal bar chart

### ISSUE THREAD

**Issue by tkforce** [highcharts/highcharts#17530]
#### Expected behaviour
Truncation for xAxis labels should only happens when it reach the edge of the label area.
 
#### Actual behaviour
When the width of the chart is limited, some of the xAxis labels are being truncated even when they haven't reached the edge.

![截圖 2022-07-21 16 14 57](https://user-images.githubusercontent.com/7017984/180164836-1e60a09e-e151-4f68-ac4f-0eb4aa63ffbf.png)

#### Live demo with steps to reproduce

Please shrink the view port of this live example to see the bug in action.
https://codesandbox.io/s/vigilant-christian-i4cpy5?file=/src/App.js

**Comment by raf18seb** [comment]
Hi @tkforce, thank you for reporting this behavior.

As a workaround, what about using `style.textOverflow: 'ellipsis'`? https://jsfiddle.net/BlackLabel/dhkwy3pe/
