### ISSUE TITLE
Unable to exit boost when series contains null points.

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#17547]
#### Expected behaviour
When there are fewer points than `boostThreshold` chart should exit the boost module.

#### Actual behaviour
When one series contains null points, and after zooming and having fewer visible points than the `boostThreshold` the chart is still boosted.
When the null series is not visible on the chart the issue is not visible.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/no0txe2c/

#### Product version
Highcharts JS v10.2.0 (2022-07-05)

#### Affected browser(s)
All

**Comment by bre1470** [comment]
Which version was the last version this was working? I am down until v9.0.0 and it is never switching back to non-boost after zoom.

**Comment by karolkolodziej** [comment]
I think it has never worked correctly. I check multiple versions and I didn't find one working.

**Comment by bre1470** [comment]
Thanks for testing further. 👍

**Comment by bre1470** [comment]
After playing around I found a workaround. Settings the chart option results in the desired effect:
```
	boost: {
		allowForce: false
	}
```
https://jsfiddle.net/bre1470/4z3pmfnv/17/

**Comment by bre1470** [comment]
Related: https://github.com/highcharts/highcharts/issues/8164
