### ISSUE TITLE
can not change z-index of svg in highcharts

### ISSUE THREAD

**Issue by nq0w72G** [highcharts/highcharts#17540]
I have a requirement to change  icon above the line chart,however i can not find a way to fix it .
I use renderer.path to draw the icon(because the icon color should be the same with line color),then they want the icon above the line and  below the tooltip.i can not find any way to resolve that. 
I tried to set toFront() of the renderer.path method,but it still not working

**Comment by pawellysy** [comment]
Hello @nq0w72G, thanks for contacting us with your question.
Our GitHub channel is treated as bug/feature tracking tool. For these kinds of questions, please contact us via dedicated support channels, which you can find here: https://www.highcharts.com/blog/support/ 
Thanks for understanding!
