### ISSUE TITLE
Setting useUTC to false can lead to broken min value in Y axis

### ISSUE THREAD

**Issue by antoine-roth** [highcharts/highcharts#17548]
#### Expected behaviour
When having duration (in milliseconds) on the Y axis, if I
- set `type: "datetime"` (to have proper tick duration spacing values)
- set `useUTC: false`

With a set of durations >= 0, I would expect to have a min value = 0.

#### Actual behaviour

![Screenshot 2022-08-01 at 10 34 43](https://user-images.githubusercontent.com/44068556/182108000-35214285-f23e-41d2-99fa-b54fa9997e22.png)

Even with only positive Y values, the first stick value displayed in the chart can be negative and seems to depend on the timezone (the first tick is the value of the timezone offset)

=> I already tried setting a `yAxis.min` to 0
=> I already tried setting `time.timezoneOffset` to 0

#### Live demo with steps to reproduce

https://jsfiddle.net/antoineroth/13meyxw0/40/

=> you might need to use the dev tools to force the navigator timezone ("Europe/Paris" or "Asia/Kolkata" for example)

#### Product version
Using the latest in the jsfiddle  (Highcharts JS v10.2.0 (2022-07-05) at the time I'm writing this)

#### Affected browser(s)
Google Chrome for my case, but probably all.

**Comment by raf18seb** [comment]
Hi @antoine-roth, thank you for reporting this.

Simplified demo: https://jsfiddle.net/BlackLabel/qdr02hwo/
