### ISSUE TITLE
Exporting in Firefox with Styled Mode: wrong font size

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#17557]
Like in the title. Export to any file (PNG, JPEG...): https://jsfiddle.net/BlackLabel/q1e8xwdz/
![chart(6)](https://user-images.githubusercontent.com/23310742/182585726-6c3b855f-33ad-4f5d-a13b-bd7d7add7eec.png)

#### Product version
10.2.0

#### Affected browser(s)
Firefox 103.0 and Firefox 103.1

**Comment by svensigmond** [comment]
Be aware it is not just the font-size that is wrong, but the set font is also ignored.

**Comment by TorsteinHonsi** [comment]
It's a regression since v10.1.0, bisected to d088df6f31fb074638a191423917159e5e7aeec6
