### ISSUE TITLE
[Gantt] Wrong dropdowns are opened or closed if they have identical names

### ISSUE THREAD

**Issue by oserrabassa-onclick** [highcharts/highcharts#17552]
#### Expected behaviour
Whenever you click the dropdown text label, the proper dropdown that has been interacted with, should collapse or expand.

#### Actual behaviour
Depending on the dropdowns that you have interacted with, differents situations will happen.
The arrow icon is working as expected, only the text label is causing issues.

#### Live demo with steps to reproduce
https://jsfiddle.net/owLpbaxs/4/

There are multiple reproducible bugs but they are all probably related to the same issue.

For example:
1. Close and open upper Level 2 dropdown
2. Click upper Level 3 dropdown (bottom Level 3 dropdown is the one that actually closes)

Another bug:
1. Close and open bottom Level 2 dropdown
2. Click upper Level 2 dropdown (clicking it does nothing)

#### Hotfix
https://jsfiddle.net/1teg5v86/
Having unique names for all the dropdowns fixes the problem
However, it seems that there are differences in how the click events on the icon and the text label work.
This makes me believe that the dropdown text label click events work by checking the clicked text against the gantt series.
Since there are multiple names that match with the clicked text, the program messes up which dropdown has actually been clicked.
This would easily explain why there are some very weird dropdown interactions but this is not for guaranteed, it is just a hunch.
If that is the case, rather than checking for the clicked text, it should check for the id, which is probably what the icon click event does.

#### Product version
HighCharts Gantt 10.2.0 (can be seen in the JSFiddle)

#### Affected browser(s)
Issue was tested and reproduced in both Chrome and Firefox.
Very likely this is not related to browser software.

**Comment by pawellysy** [comment]
Thanks @oserrabassa-onclick, for creating this ticket!
