### ISSUE TITLE
Type definitions for `PieSeries` not public

### ISSUE THREAD

**Issue by dfenerski** [highcharts/highcharts#17551]
#### Expected behaviour
To be able to see and use these, a common use case is to call a method from a predefined series; in the docs there are many examples with this.

#### Actual behaviour
`seriesTypes`, `PieSeries` are not public

Am I missing something? It would be great to have these. 

Thanks for the info in advance!
----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by raf18seb** [comment]
Hi @dfenerski, could you provide more details? I think you forgot to attach something. Especially this sentence is very unclear:

> To be able to see and use these

**Comment by dfenerski** [comment]
![image](https://user-images.githubusercontent.com/48520530/182408764-f4aa6254-9cb2-4241-9328-ec67cd82956b.png)
There is nothing to import from `highcharts` with regards to `seriesTypes` or the `PieSeries`. In the official docs, there is a `mappie` example chart, whose renderer calls the pie one. Without access to the typedefs of those, one has to to what I did in the pic.

**Comment by raf18seb** [comment]
Thank you for clarifying! I added the feature request tag.

ps. `mappie` demo is no longer supported and removed from our docs, see [changelog](https://www.highcharts.com/blog/changelog/#highcharts-v10.2.0) and `series-on-point` feature: [mappie demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/map-pies)

**Comment by dfenerski** [comment]
Out of curiosity, why did support got dropped for the `mappie` and what do you mean by this? Is it just removed from the docs or is the official sample no longer working and discouraged from using? Because I've noticed after v9.2 it breaks..

**Comment by raf18seb** [comment]
> I think without types for seriesTypes, chart type extension is more cumbersome in general, not only for a deprecated mappie and this IMO is critical.

@bre1470 `seriesTypes` is deprecated, isn't it?
Should new series be created using class and `registerSeriesType()`?
Like this: https://jsfiddle.net/BlackLabel/fwcLatyj/

> Out of curiosity, why did support got dropped for the mappie? and what do you mean by this

Maybe I wasn't clear enough, sorry for that. We still support mappie demo, but we added a new feature "Series on point" so now it's easier to create a demo with pies on the map without creating a new series type.

> Is it just removed from the docs or is the official sample no longer working and discouraged from using?

The demo has been replaced and we encourage using a new "Series on point" feature. However, the old demo should work correctly as well.

**Comment by bre1470** [comment]
@raf18seb Yes, it is deprecated. Your example looks correct for the current situation, though this should not be something official or as a workaround.

@dfenerski
We will add `Series.types` and `Series.registerType` with the next release. `Highcharts.seriesTypes` and `Highcharts.seriesType` will be kept for backward compatibility.
