### ISSUE TITLE
AST policy conflict in chrome when mixing classic and ESM in Chrome

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#17567]
#### Expected behaviour

Draws charts of `highcharts/studies/series-table` sample with `highcharts-utils`

#### Actual behaviour

Breaks during chart init with `highcharts-utils`. JSFiddle is not breaking so it might be, that utils is playing with the container before the ESM-based demo has a chance.

#### Live demo with steps to reproduce
https://github.com/highcharts/highcharts/tree/chrome-ast-conflict

#### Product version
master

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
Fixed by https://github.com/highcharts/highcharts-utils/commit/8bbc72fef3923102714b2c63c048df1e09f92e75 . 

Implementers must allow duplicates in their web page CSP rule if they want mixed Highcharts setups.
