### ISSUE TITLE
.NET Docs ColumnSeriesDataLables Wrong Property Name

### ISSUE THREAD

**Issue by fceci90** [highcharts/highcharts#17560]
#### Expected behaviour
When setting a custom color for a data label, Highcarts draws the label with maximum contrast with a text outline. To override this, the text outline property needs to be set to none inside the dataLabels.style option.

The .NET docs say that the property name is text-outline so doing `Style = new System.Collections.Hashtable{ { "text-outline", "none"} }` should work.

#### Actual behaviour
This does not work. Looking at the JS docs, I see there that the property is called textOutline instead. Using textOutline in .NET Highcarts works. `Style = new System.Collections.Hashtable{ { "textOutline", "none"} }`

#### Proposed fix
In the [color property ColumnSeriesDataLabels documentation](https://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_column_series_data_labels.html#a8c3648d68d1201cb8546512130fbd109) please update "text-outline" to "textOutline" both times it appears.

I looked at the color property of the [LineSereisDataLables documenation](https://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_line_series_data_labels.html#a12b00fb2816403977aad0dfc95f93e48) and I see the same issue exists. Not sure if the Color property can be fixed once and applied to all Classes in the documentation. Otherwise the documentation would have to be updated for all series types that have data labels. 

Here is the [JS Documentation](https://api.highcharts.com/highcharts/series.column.dataLabels.style) for reference.

#### Live demo with steps to reproduce

The following example is a line chart using JavaScript Highcharts, but the same incorrect naming of the text outline property produces the same issue since data labels are allowed on multiple chart types.
https://codepen.io/FittyFrank/pen/NWYYGbp

#### Product version

Highcharts .NET 10.2.0.1

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi @fceci90, thank you for reporting a docs bug!

FYI @brofixo
