### ISSUE TITLE
custom stock tools button not deselecting after click

### ISSUE THREAD

**Issue by dborc610** [highcharts/highcharts#17569]
### Expected behavior
clicking the custom stock tool button should act like a toggle ( just like show annotation button)

### Actual behavior
clicking the custom stock tool button will activate log scale, then will require 2 clicks to activate linear scale. Will then require 2 clicks to activate log scale.

### Live demo with steps to reproduce

[jsFiddle demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/blog/lin-log-switch)

The 'Dynamically switch between linear and log axis scale using Stock Tools GUI' [demo ](https://www.highcharts.com/blog/tutorials/dynamically-switch-between-linear-and-log-axis-scale-using-stock-tools-gui/) requires two clicks in order to perform scale switch. I believe this is because the button isn't being deselected till the next click event. 

#### Product version
HighStock 10.2

### Affected browser(s)
I've only testing on Google Chrome

**Comment by pawellysy** [comment]
Hello @dborc610, thanks for reporting this issue! Indeed this is a bug in our official demo.
Here is a correct version: https://jsfiddle.net/BlackLabel/4qvL7fkz/

Instead of manually deleting the CSS class, we should fire `deselectButton` event. We will fix it asap! Thanks again.
