### ISSUE TITLE
Plan vs Actual 

### ISSUE THREAD

**Issue by gitgnaans** [highcharts/highcharts#17562]
##Expected behavior
We need the chart for Plan Vs Actual. (like comparison chart)
plan start and end date VS actual start and end date.
 -----------
    -------------

##Actual behavior
We have Plan start and end date or actual start and end date chart

**Comment by pawellysy** [comment]
Hello @gitgnaans, thanks for contacting us with your question.
Our GitHub channel is treated as bug/feature tracking tool. For these kinds of questions, please contact us via dedicated support channels, which you can find here: https://www.highcharts.com/blog/support/
Thanks for understanding!
