### ISSUE TITLE
Polar chart change y-axis centre for a series

### ISSUE THREAD

**Issue by SyedTayyab** [highcharts/highcharts#17575]
Hi, 

I am creating a polar column chart showing both positive and negative values. I want to move the centre of y axis to a line away from centre and display positive values pointing outwards and negative values pointing inwards as shown in attached picture. How, can I achieve this?

<img width="256" alt="sc1" src="https://user-images.githubusercontent.com/8201438/183259068-de3a943c-06ce-4476-b20e-42967e85280d.png">

----

`Note:`
This feature is about rendering negative columns (like in the image above) in a polar chart.

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by raf18seb** [comment]
Hi @SyedTayyab, thanks for writing to us.

I'm afraid creating polar column chart with negative values is not possible at this moment in Highcharts.
I'm tagging this idea as a feature request.

In case of any further questions, please contact our support engineers on one of our dedicated support channels listed here: https://www.highcharts.com/blog/support/ (GitHub is our bugs/features tracker only)

**Comment by SyedTayyab** [comment]
> Hi @SyedTayyab, thanks for writing to us.
> 
> I'm afraid creating a polar column chart with negative values is not possible at this moment using a standard Highcharts API and it goes beyond the standard scope of customization. I'm tagging this idea as a feature request.
> 
> In case of any further questions, please contact our support engineers on one of our dedicated support channels listed here: https://www.highcharts.com/blog/support/ (GitHub is our bugs/features tracker only)

Hi, 

Thanks for clarifying. I got it. 👍
