### ISSUE TITLE
Keybord navigation with scroll

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#17578]
#### Actual behaviour
- After selecting an item in the legend the keyboard navigation (tab/shift tab) breaks and scrolls to the top of the page.
- Selecting an item in the legend re-enables the data table after hiding.

#### Live demo with steps to reproduce
https://jsfiddle.net/FFSteve/k9z8q7go/18/

#### Product version
 Highcharts JS v10.2.0 (2022-07-05)

#### Affected browser(s)
All

**Comment by oysteinmoseng** [comment]
> Selecting an item in the legend re-enables the data table after hiding.

This is unrelated to a11y and happens because `showTable: true` adds a `viewData()` call on every render, so the table will be re-shown even if you resize the page.

I will add a PR for the a11y-related problem for now, and we can discuss how to go from there.
