### ISSUE TITLE
Incorrect demo for disabled markers in API-doc

### ISSUE THREAD

**Issue by LB0ge** [highcharts/highcharts#17574]
#### Expected behaviour
[API-doc for markers](https://api.highcharts.com/highcharts/plotOptions.series.marker) includes two demo-links for the enabled-option:
[Disabled markers](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-marker-enabled/)
[Disabled in normal state but enabled on hover](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-marker-enabled-false/)
The disabled marker demo should have markers disabled at all times, also on hover.

#### Actual behaviour
The demos are identical. The disabled markers demo has markers enabled on hover.

#### Live demo with steps to reproduce

Demo that works (markers disabled at all times): [https://jsfiddle.net/6509ucya/](https://jsfiddle.net/6509ucya/)

#### Product version
Highcharts v10.2.0

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hi @LB0ge, thanks for reporting this bug!
