### ISSUE TITLE
yaxis.floor causes a crash with empty data

### ISSUE THREAD

**Issue by teemulankila** [highcharts/highcharts#17577]
#### Expected behaviour
Should not crash

#### Actual behaviour
Crashes

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/yaxis/floor-ceiling/
Alter the above demo by replacing the data
`data: [0, 1, 0, 2, 3, 5, 8, 5, 15, 14, 25, 54]`
with
`data: []`

#### Product version
At least current latest highchart and highstock (v10.2.0)

#### Affected browser(s)
Does not seem to be browser specific bug

**Comment by raf18seb** [comment]
Hi @teemulankila, thank you for reporting the issue!

Simplified demo: https://jsfiddle.net/BlackLabel/pbd02jyw/

It's a regression after https://github.com/highcharts/highcharts/commit/3eff118e8176e904c857e290bfff0228c6ec3fa9

Workaround: in the `H.normalizeTickInterval` method make sure that `tickInterval` is not `NaN`: https://jsfiddle.net/BlackLabel/jk8vnc1b/
(workaround needs to be added before `highcharts.js` module)

**Comment by jakubjanuchta** [comment]
Fixed along other issues in #17690, v10.3.0
