### ISSUE TITLE
Lines in Line chart disappearing upon hover

### ISSUE THREAD

**Issue by tsmanesh** [highcharts/highcharts#17571]
#### Expected behaviour
1. with out disappearing upon hover 

#### Actual behaviour

1. flickering/ disappearing upon hover 

#### Live demo with steps to reproduce

- 

Uploading Screen Recording 2022-08-05 at 3.43.42 PM.mov…

#### Affected browser(s)
Chrome

**Comment by pawellysy** [comment]
Hi @tsmanesh, I'm afraid you didn't share any demo and screen recording. Could you try to share them one more time? Without those pieces of information, we can't reproduce the issue. Thanks!

**Comment by tsmanesh** [comment]
cc : @

https://user-images.githubusercontent.com/103098233/183073799-a3464ac1-13e6-4034-8283-e921c8bdf386.mov

**Comment by pawellysy** [comment]
I'm sorry, but without the demo/ your configuration it is hard for us to find the reason why you have given problems. Could you share the demo as well?

**Comment by tsmanesh** [comment]
@pawellysy 

Please check below configuration for above line chart
https://jsfiddle.net/p5ua91xs/

Here issue will see in if u expand this line chart in window browser then only it will flicker other wise it will show excepted behaviour.

**Comment by pawellysy** [comment]
Hi @tsmanesh, I still can't really reproduce the issue on my machine.
Could you try to give me a more thorough explanation of the reproduction steps?
Here is what I did: 
- Opened demo above
- Hovered on the lines
Everything works in order there. 

Also, you shared the config file, which has 13k lines, where some of them isn't included in the API. Are you using these config objects at all? I don't really have the capacity to go through all config. 

Some example options, that are not included in the API are: `chart.props`, `series.data.rawXValues`, `series.data.rawYValues` and some other. Thanks!

**Comment by Eslam-Yahya** [comment]
@pawellysy I have the same issue, Would you please try @tsmanesh fiddle on a (chrome, mac)?

**Comment by pawellysy** [comment]
@Eslam-Yahya, as I said in the previous comment, I can't reproduce the issue on my machine. 
Could you share another demo, where the issue is also reproduced? From what I saw, there is a huge config, where some of the options have no impact. Could try sharing a minimal demo? Thanks!

**Comment by KacperMadej** [comment]
Unable to recreate: Windows 11
- Chrome (current) Version 108.0.5359.125 (Official Build) (64-bit)
- Firefox (current) 108.0.1
- Edge (current) Version 108.0.1462.54 (Official build) (64-bit)

**Comment by tsmanesh** [comment]
@pawellysy 
Now  we are able to reproduce flicker issue in  below  fiddle  and please check below  attached loom provided  repro steps.
`https://jsfiddle.net/u5gjywdc/7/`


Note : Issue  we are  seeing in Chrome browser other browser working as excepted  
Verified in firefox browser  working fine.

https://www.loom.com/share/9f7caff85492448e8586f8ba31809f29

**Comment by pawellysy** [comment]
On my machine everything is working correctly, but a bit slow. The reasons might be that the jsfiddle isn't the best tool for handling massive configs and that you are rendering about 850*50 points.  For such datasets, we advise using the boost module: https://jsfiddle.net/BlackLabel/29Lg6bw1/ 
Which seems to solve the problem. 

You can read more here:
[article about boost module](https://www.highcharts.com/tutorials/highcharts-high-performance-boost-module/)
[general article about performance](https://www.highcharts.com/docs/getting-started/frequently-asked-questions#how-can-i-get-the-best-performance-out-of-highcharts)

If you have any more questions, feel free to contact us via [our dedicated support channels](https://www.highcharts.com/blog/support/).
