### ISSUE TITLE
Enabled not working with plotOptions using Highcharts

### ISSUE THREAD

**Issue by Chitralekha-Hassan** [highcharts/highcharts#17587]
Bug or Feature Request?
It seem like a error.

Description
There's already ''enabled'' used in the code but for some reason its not working. I am using a line chart with Highcharts and want the lines to be highlighted while fading out the others. Here is the code, do let me know what possibly can be the error.
const plotOptions = {
series: {
stickyTracking: false,
states: {
inactive: {
enabled: true,
}
}
}
};

Also there's a link below to the example which I am trying to achieve in my code.

How to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-states-inactive-disabled

Some other similar examples :
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-selected/
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/series-select/

Live demo demonstrating bug
Versions
React JSX Highcharts version:
Highcharts version:
React version:

**Comment by karolkolodziej** [comment]
Let me first clarify one thing. 
If you have two series (Series 1 and Series 2) on the chart and you hover over one (Series 1) then this series state is set to `hover` and the other series (Series 2 in this case) is set to `inactive`.
So if set: 
```
    plotOptions: {
        series: {
            states: {
                inactive: {
                    enabled: true
                }
            }
        }
    },
```
This means the second series (Series 2) is doing to be faded while you hover over Series 1 which is exactly what you've described- [demo](https://jsfiddle.net/BlackLabel/qojxpmnc/).

In my opinion, everything works as expected. Could you please explain what am I missing here?

**Comment by karolkolodziej** [comment]
I think I'm not following. As you can see in the screenshot below if I hover over the black series, the blue one is faded.
Isn't it what you have been looking for?
![image](https://user-images.githubusercontent.com/57004120/184822854-69f965b8-b03c-4584-a706-b51ff061e67a.png)

**Comment by Chitralekha-Hassan** [comment]
Yes you are right. I am trying to recreate this but I am not able to.

**Comment by Chitralekha-Hassan** [comment]
I have a line chart with multiple lines using Highcharts. So my question is: Is there way in Highcharts or a feature  to highlight a line while the other line fades like this (https://jsfiddle.net/BlackLabel/qojxpmnc/) 
Do let me know. Thanks

**Comment by raf18seb** [comment]
@Chitralekha-Hassan which Highcharts version are you using? The "inactive state" feature was added to Highcharts in version 7.1.0.
If it's not working for you, then
- either you're using an older version of Highcharts
- or there's something wrong with your config

Unfortunately, we are not able to help you when you're providing working demos. If you want us to find a problem, you need to send the original demo (not working).

**Comment by Chitralekha-Hassan** [comment]
The highcharts version is 8.1.0 and about the demo I'll try to attach that in a while.

**Comment by pawellysy** [comment]
Closing - No reproduction steps
