### ISSUE TITLE
OffsetVertical and offsetHorizontal fully implemented in Organization chart? (offset deprecated?)

### ISSUE THREAD

**Issue by nevalain** [highcharts/highcharts#17594]
I am asking is OffsetVertical and offsetHorizontal fully implemented in Organization chart?

To my understanding they should be implemented in Organization chart?
[https://api.highcharts.com/highcharts/series.organization.nodes.offsetHorizontal](https://api.highcharts.com/highcharts/series.organization.nodes.offsetHorizontal )

Sorry. I am pretty useless with code!

#### Expected behaviour

OffsetVertical and offsetHorizontal can be used in Organization chart.

#### Actual behaviour

I see no reference of offsetVertical and offsetHorizontal in code here:
[https://code.highcharts.com/modules/organization.js](https://code.highcharts.com/modules/organization.js)

#### Live demo with steps to reproduce

Shareholders is offset and it is working, board is not:
[https://jsfiddle.net/vcon76qa/](https://jsfiddle.net/vcon76qa/)

#### Product version

Highcharts, v10.2.0 (2022-07-05)

#### Affected browser(s)

All

**Comment by pawellysy** [comment]
hi @nevalain, thank you for reporting this issue!
You're right, there is something wrong with the `offsetVertical` option. It does not work for inverted charts. For now, you can use the deprecated `offset` option.
