### ISSUE TITLE
Gantt Chart to show Quarters

### ISSUE THREAD

**Issue by NordicLight** [highcharts/highcharts#17597]
We have a customer solution using highchart gantt as a roadmap. Now there is a customer request to show only quarters which is not supported. This is a very basic feature for a gantt chart and please see below simple picture as an example. Is it possible to implement that?

![highcharts quarter](https://user-images.githubusercontent.com/9700899/184369434-cbee9c23-3a61-4922-89c8-69391c67769e.PNG)

**Comment by pawellysy** [comment]
Hi @NordicLight, thanks for suggesting this feature!

Currently, you can almost achieve it with some crafty wraps and API configuration. https://jsfiddle.net/BlackLabel/gbwheayL/

**Comment by NordicLight** [comment]
Hi!

Thank the the quick turnaround. Indeed some magic in your wrapper... Did try to port that to a interactive gantt chart but it is not working unless you hardcode min and max which is not possible for a interactive use case.

As discussed this is a very basic feature for a gantt roadmap so any idea if this can be implemented?

https://jsfiddle.net/e5ucong2/

Regards
Johan

**Comment by pawellysy** [comment]
I've found a better way. Check this demo: https://jsfiddle.net/BlackLabel/6zonjv13/2/

You can just set the month interval, and whenever the unit is month and count is 3, you can set the formatter function to return string containing the `Q<number>` like in the demo. Does it work for you?

**Comment by NordicLight** [comment]
Hi,

Greate much closer but not fully there.

The use case for a gantt quarter roadmap is to show only quarters in the timeline. Your current improve solution shows only month by number if the time range is to low. I can understand that there is a min range that you need to have to show only quarters. So have set below example to 420 days but altough that limitation the quarters are not forced unless you drag out the time to > 2.5 years.

Example - interactive gantt
https://jsfiddle.net/ndhqmfxe/2/

![highchart_wrong](https://user-images.githubusercontent.com/9700899/184815993-43ee0690-98e3-4b6c-9471-8b068177a741.PNG)

Regards
Johan

**Comment by NordicLight** [comment]
Hi again,

Did play around with your example and did modify it to fullfill our needs. Pleaes see below for the working example as an interactive gantt. I want to thank you for super great support!

https://jsfiddle.net/ndhqmfxe/4/
![highcart_workaround](https://user-images.githubusercontent.com/9700899/184817187-4c2474c8-3021-427f-a728-342605ab2ef8.PNG)


Regads
Johan

**Comment by pawellysy** [comment]
Good to hear! Since there is an option to achieve this behavior from API, I will close the ticket now. Thanks!
