### ISSUE TITLE
New series type: conversion column/funnel series

### ISSUE THREAD

**Issue by luizsculz** [highcharts/highcharts#17598]
Hello everyone, I would like to order (pleaseee :D ) two new graphics templates that are very useful in sales and marketing,
(conversion bar chart and conversion funnel chart), basically they are the current bar and funnel charts, but with arrows between the bars, where it would be possible to inform the percentage of conversion between the steps, I made several attempts to generate them with the canvas (chart.renderer.image and chart.renderer.text), but it didn't look good, I believe these two graphics would be a good improvement for the library
**I will add an example URL and some images:** (the decision of the best layout is up to you)
https://www.holistics.io/blog/improved-conversion-funnel/

<img width="873" alt="exemplo_1" src="https://user-images.githubusercontent.com/2709453/184379837-b498aaf9-bd9e-4242-8c53-7eec2c5acef6.png">

<img width="972" alt="exemplo_2" src="https://user-images.githubusercontent.com/2709453/184379844-b213a314-34d8-4d79-bdf5-184282254dcf.png">

<img width="470" alt="exemplo_3" src="https://user-images.githubusercontent.com/2709453/184379845-7cec1c0b-cbd2-4352-adc5-e68e1ab659ae.png">

![exemplo_4](https://user-images.githubusercontent.com/2709453/184379848-b98fd9fe-680a-40a4-bc3c-ce5f49b6bdcb.jpg)

![exemplo_5](https://user-images.githubusercontent.com/2709453/184379850-b3afc032-4c69-48a7-880c-82017b754fac.png)

<img width="470" alt="exemplo_6" src="https://user-images.githubusercontent.com/2709453/184379851-f9bcd371-eef0-48ff-b74f-ed24f5a49f85.png">

Thank you very much for your attention!!!

**Comment by pawellysy** [comment]
HI @luizsculz, thanks for creating the ticket! 
You could try to adjust each series with either dataLabels or annotations module. The example is here: https://jsfiddle.net/BlackLabel/9b1p5vkn/220/

I will also change the name of the ticket to be more descriptive.

If you contact us via our [dedicated support channels](https://www.highcharts.com/blog/support/), our support engineers will try to adjust your chart to your needs!

**Comment by pawellysy** [comment]
As I said above, reach out to us via available support channels, where our support engineers will help you with that case. Thanks for your understanding!
