### ISSUE TITLE
Always have a darkgray color scrollbar on iOS when I configure the scrollablePlotArea

### ISSUE THREAD

**Issue by AAChartModel** [highcharts/highcharts#17591]
#### Expected behaviour
Highcharts have no darkgray color scrollbar when I configure the `scrollablePlotArea` and scroll the it.

#### Actual behaviour
when I configure the `scrollablePlotArea` and scroll the it,  and then I **open the chrome DevTools** or **use it in iOS**, Highcharts have a darkgray color scrollbar on the bottom.
<img width="1140" alt="截屏2022-08-11 上午7 53 45" src="https://user-images.githubusercontent.com/16357599/184042821-87011e3c-f3ec-4353-8f89-7a1226f2199d.png">

#### Live demo with steps to reproduce

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>第一个 Highcharts 图表</title>
</head>
<body>

<p> just test html</p>

 <style>*{
                -webkit-user-select: none;
                user-select: none;
                
                .highcharts-scrolling::scrollbar {
                    width: 100;
                    color: red;
                }
            }
                </style>


    <!-- 图表容器 DOM -->
    <div id="container" style="width:100%;height:400px;"></div>
      <!-- 引入 highcharts.js -->
    <script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>

    
<div id="app">
  <h1>Hello, world!</h1>
</div>

    <script>
        // 图表配置
        var options = {
            chart: {
                type: 'column',  
                scrollablePlotArea:{
                    minWidth:8496,
                    opacity:0.6,
                },             
            },
            title: {
                text: '我的第一个图表'                 // 标题
            },
            xAxis: {
                categories: ['苹果', '香蕉', '橙子']   // x 轴分类
            },
            yAxis: {
                title: {
                    text: '吃水果个数'                // y 轴标题
                }
            },
            series: [{                              // 数据列
                name: '小明',                        // 数据列名
                data: [1, 0, 4]                     // 数据
            }, {
                name: '小红',
                data: [5, 7, 3]
            }]
        };
        // 图表初始化函数
         Highcharts.chart('container', options);

    </script>
 
</body>
</html>
```

#### Product version

The latest 10.1.0 or 10.2.0

#### Affected browser(s)

Chrome and iOS Safari

**Comment by pawellysy** [comment]
Hello @AAChartModel, thanks for reaching out to us with this issue!
I'm not quite sure if I understand you correctly. The steps to reproduce the issue are the following:
- Open this demo on IOS chrome -> https://jsfiddle.net/BlackLabel/9b1p5vkn/221/
- Open dev tools on IOS chrome
- Move the screen and see, that the scroll bar has a color?

I am not quite sure which part is wrong. The darkgray color of the scrollbar is expected as well as the fact, that the scrollbar is visible. I am not also sure, how to open the dev tools on IOS chrome. Could you add some more reproduction steps, and check if the demo I shared is correct to reproduce the issue? Thanks!

**Comment by AAChartModel** [comment]
Thanks for your reply.


>  Open this demo on IOS chrome -> https://jsfiddle.net/BlackLabel/9b1p5vkn/221/


Just as you answerd above, In the chart example with `scrollablePlotArea`, If you scroll the chart to right or left , you can see the dark gray scrollbar at the bottom. 

However, the scrollbar is **not** very suitable for me.  I want the dark gray scrollbar be `invisible`. it mean that I **don not** want the dark scrollbar show at the bottom. is it possible to **hide** the scrollbar when I configured the  `scrollablePlotArea` for the chart options.

For example, If you add a simple property named "scrollbarEnalbed" or "scrollbarHidden" for  `scrollablePlotArea` object in `Highchart options` API. That is would be great. Of course, If there is another easy way to hide the scrollbar, That is would be nice Too.

**Comment by AAChartModel** [comment]
> and then I open the chrome DevTools or use it in iOS


Sorry for the ambitious comments.

With the live code just as I post above. I mean the scroll will show at the bottom in these two situation as follow:

* iOS Safari (or WKWebView)
* Mac desktop browser Chrome (Open the DevTools)

**Comment by pawellysy** [comment]
Ok, I understand now. The scrollbar is a part of the HTML overflow option and can be styled using CSS. You need to enable the [styledMode](https://api.highcharts.com/highcharts/chart.styledMode) first. here is an example how to do this: https://jsfiddle.net/BlackLabel/pLmsjf01/1/
(check the CSS tab)

This is not connected to highcharts though. Here is the example article on how to style the scrollbar: https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp

For any further help, please reach out to us via our support channels: https://www.highcharts.com/blog/support/
Thanks!
