### ISSUE TITLE
Gradient texture on highmaps

### ISSUE THREAD

**Issue by SyedTayyab** [highcharts/highcharts#17612]
I'm creating a map chart using highmaps and want to add gradient texture on continents as shown in the attached image. Is this possible?
![map](https://user-images.githubusercontent.com/8201438/184941702-a60c2ce2-74b8-4309-8ed1-07bc67757464.jpg)

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by raf18seb** [comment]
Hi @SyedTayyab,

I'm not sure what "gradient texture" exactly would you like to use.
You can add a gradient to a specific map point like in this demo: https://jsfiddle.net/BlackLabel/9t3ovaw5/
But if you would like to group some points, you would have to generate your own custom map or do some tricks like e.g. using underlying fake series.

I'll leave this ticket open and mark it as a feature request. If you have any further questions, please contact us on one of our dedicated support channels listed here: https://www.highcharts.com/blog/support/ (GH is our bugs/features tracker only)

**Comment by magdalena-gut** [comment]
Hi @SyedTayyab, you can also consider using `pattern-fill` module, which allows you to use the image as a filling. 
More information about the module: https://www.highcharts.com/docs/chart-design-and-style/pattern-fills

Demo:
https://jsfiddle.net/BlackLabel/7wqk2uh4/

**Comment by SyedTayyab** [comment]
@magdalena-gut Thanks a lot
