### ISSUE TITLE
Not all series lines are displayed on ios

### ISSUE THREAD

**Issue by 99899899998** [highcharts/highcharts#17623]
#### Expected behaviour
I hope the series lines are normal display

#### Actual behaviour
On the ios, some of the charts series line  are hide，but it normal display when you touch it; some of the charts are normal.
On the android ，all are normal.

like this: 
ios:
![微信图片_20220819093349](https://user-images.githubusercontent.com/45654766/185528899-2f5a2b5e-4f75-40ce-a67c-13fbe7f9869e.jpg)

android: 
![微信图片_20220819093353](https://user-images.githubusercontent.com/45654766/185528918-686150d5-376f-4359-a888-58753a07fbb6.jpg)

I don't know if there's any `options`.
I cannot provide the demos because of data privacy issues.
Hope to the replay，thanks.

**Comment by karolkolodziej** [comment]
Hi @99899899998! 
I understand that you can't share your data but could you please at least share your chart's config with some mock data that I could recreate on my own?

**Comment by pawellysy** [comment]
Closing - No reproduction steps
