### ISSUE TITLE
how to remove xAxis label of crosshair on highstock

### ISSUE THREAD

**Issue by kingofday** [highcharts/highcharts#17628]
#### after mouse hover on chart, xAxis label appear over its labels and i want to remove it

[example](https://jsfiddle.net/kingofday/n8yLo21u/5/)
related question in stackoverflow:

[stachoverflow](https://stackoverflow.com/questions/73434374/remove-xaxis-label-of-vertical-crosshair-in-highchart-highstock)

**Comment by pawellysy** [comment]
Hi @kingofday, thanks for contacting us with your question! Sorry, but we treat GitHub as a bug/feature tracker tool, and your question is neither. We do have dedicated support channels, where we answer the questions like yours (one of them is StackOverflow. [Here is the list](https://www.highcharts.com/blog/support/)) so please, wait for our support engineers to answer you there. Thank you for understanding!
