### ISSUE TITLE
Disabling connections between dataPoints in the navigator

### ISSUE THREAD

**Issue by LGiesberger** [highcharts/highcharts#17621]
Not so much an issue of any sort, more a question/inquiry.

Two different types of data can be loaded into our chart, this will either have more stable numbers, such as between 0 and 100, where it forms a smooth line, or it has either a 0 or a 1, as you can imagine it doesn't look great, especially if there are a lot of dataPoints, it would also be better for us if there would be no connecting lines between these dataPoints since it doesn't actually mean anything relevant to our users, and it clusters together and becomes unreadable.

The 0 - 1 series is a column type and the other is a line type.

I want to know if it's possible to disable the connections between dataPoints inside of the navigator.

**Comment by pawellysy** [comment]
Hi @LGiesberger, thanks for contacting us with your question.
Our GitHub channel is treated as a bug/feature tracking tool. For these kinds of questions, please get in touch with us via dedicated support channels, which you can find here: https://www.highcharts.com/blog/support/.

Our support engineers will be more than happy to help you, to tweak the chart's configuration too much your needs. 
Thanks for understanding!
