### ISSUE TITLE
Changing themes dynamically

### ISSUE THREAD

**Issue by hubertkozik** [highcharts/highcharts#17635]
#### Expected behaviour
Chart themes should be changed dynamically.

#### Actual behaviour
The chart theme is probably loaded and fires only once, which blocks the possibility to change the theme dynamically, e.g. after a button click.

#### Live demo with steps to reproduce
https://codesandbox.io/s/highcharts-react-demo-forked-7pbqnh
1. Light theme (SandSignika) is loaded on start.
2. Click the button "Change theme".
3. Dark theme (DarkUnica) is applied to the chart.
4. Click the button "Change theme" again".
5. Nothing happened.

#### Product version
Highcharts v10.2.0

#### Working product version
Highcharts v7.0.0
Demo: https://codesandbox.io/s/highcharts-react-demo-forked-5q3w3v

#### Possible workaround
Use manual invocation of a local method `apply` of theme, e.g. 
`Highcharts["_modules"]["Extensions/Themes/DarkUnica.js"].apply();`
Demo: https://codesandbox.io/s/highcharts-react-demo-forked-cichpn

**Comment by raf18seb** [comment]
I think this should be reported on React wrapper's repo. First of all, from the above demos: is the `react-css-theme-switcher` our official thing?

In pure Highcharts (without React), there's no official way for updating themes. [As the docs say](https://www.highcharts.com/docs/chart-design-and-style/themes): ```A Highcharts theme is a set of pre-defined options that are applied as default Highcharts options before each chart is instantiated.```
This means that themes can be applied only before chart's initialization (by using `H.setOptions()` method that changes the default options).
Any other themes changes should be either handled by changing the default options and initializing the chart again: https://jsfiddle.net/BlackLabel/cd5rqgk6/
or should be changed by the `chart.update()` method: https://jsfiddle.net/BlackLabel/9vnuhet6/

So, from the pure JS Highcharts point of view: this is not a bug and the correct behaviors are described in my above jsFiddle demos ☝️ 

@ppotaczek how should it work in React? Could you take a look at the above codesandbox demos?

**Comment by ppotaczek** [comment]
> I think this should be reported on React wrapper's repo.

I don't agree, this is only a Highcharts matter and it is related to the way how Highcharts modules work.

Let's simplify things a bit:

```
import Highcharts from 'highcharts';
import SandSignika from "highcharts/themes/sand-signika";
import DarkUnica from "highcharts/themes/dark-unica";

SandSignika(Highcharts);
DarkUnica(Highcharts);
```

We have two themes loaded and applied `DarkUnica`. To change the current theme back to `SandSignika` we can call:
- `Highcharts["_modules"]["Extensions/Themes/SandSignika.js"].apply();`
- `Highcharts.setOptions(Highcharts["_modules"]["Extensions/Themes/SandSignika.js"].options);`

Calling: `SandSignika(Highcharts);` again in Highcharts v7.0.0 was enough to change a theme, but according to the new way of registering modules it's not. 

```
    function _registerModule(obj, path, args, fn) {
        if (!obj.hasOwnProperty(path)) {
            obj[path] = fn.apply(null, args);
            ...
        }
    }
```

Maybe we should reconsider that and treat theme modules in other way?

**Comment by TorsteinHonsi** [comment]
Themes in Highcharts ultimately is just a fancy way of saying custom default options. These global options are set by `Highcharts.setOptions` prior to creating charts, which will make it a bit cumbersome to change dynamically because all chart instances are affected.

I'm not saying it would be impossible, and we already have a similar mechanism in the responsive module, where all previous states of each chart are saved, then restored when new conditions are no longer valid.

However, for dynamic themes I highly recommend using `chart.styledMode` and let CSS take care of the theming. Then we get everything for free - handling of CSS variables, dark mode / light mode, animated updates (transitions) etc. See https://www.highcharts.com/blog/products/highcharts/dark-mode-in-highcharts/ for inspiration.

**Comment by volatile-static** [comment]
If you are using `highcharts-vue`, just add attribute `key` to watch the changing of theme and reload the chart.
Like this:
```vue
<Chart
        constructor-type="chart"
        ref="chart"
        :options="options"
        :key="theme"
    ></Chart>
```

**Comment by Shyam-Chen** [comment]
```vue
<!-- Chart.vue -->
<script lang="ts" setup>
import { ref, watch } from 'vue';
import { useDark } from '@vueuse/core';
import highcharts from 'highcharts';
import { Chart as HighChart } from 'highcharts-vue';
import merge from 'lodash/merge';

defineProps<{
  options?: highcharts.Options | any;
}>();

const isDark = useDark();

const theme = ref({});

const initialOptions = {
  accessibility: {
    enabled: false,
  },
  credits: {
    enabled: false,
  },
};

watch(
  () => isDark.value,
  () => {
    if (isDark.value) {
      theme.value = {
        ...initialOptions,
        chart: {
          backgroundColor: '#1e293b',
        },
        xAxis: {
          labels: {
            style: {
              color: '#cbd5e1',
            },
          },
        },
        yAxis: {
          labels: {
            style: {
              color: '#cbd5e1',
            },
          },
          title: {
            style: {
              color: '#cbd5e1',
            },
          },
        },
        legend: {
          itemStyle: {
            color: '#94a3b8',
          },
          itemHoverStyle: {
            color: '#e2e8f0',
          },
        },
      };
    } else {
      theme.value = {
        ...initialOptions,
        chart: {
          backgroundColor: '#ffffff',
        },
        xAxis: {
          labels: {
            style: {
              color: '#666666',
            },
          },
        },
        yAxis: {
          labels: {
            style: {
              color: '#666666',
            },
          },
          title: {
            style: {
              color: '#666666',
            },
          },
        },
        legend: {
          itemStyle: {
            color: '#333333',
          },
          itemHoverStyle: {
            color: '#000000',
          },
        },
      };
    }
  },
  { immediate: true },
);
</script>

<template>
  <HighChart v-bind="$attrs" :highcharts="highcharts" :options="merge(options, theme)" />
</template>
```
