### ISSUE TITLE
Rendering issue of line chart in Chrome.

### ISSUE THREAD

**Issue by JuhiSharma2** [highcharts/highcharts#17631]
#### Expected behaviour
The Line chart should be coming proper with the data .

#### Actual behaviour
The line chart has elongated line which does not render data properly and it gets rendered properly after second refresh..This issues is only faced in Chrome and no other [[browser]]() is 
<img width="830" alt="Screenshot 2022-08-23 at 10 02 55 AM" src="https://user-images.githubusercontent.com/111729812/186070724-4d9f157c-7e3a-47ca-b786-37967ea12b9a.png">
affected, every other loads the charts well .

#### Live demo with steps to reproduce
<img width="815" alt="Correct image" src="https://user-images.githubusercontent.com/111729812/186070807-48f717b3-e6f6-4c01-9213-71e713057ee1.png">

#### Product version
<"@carbon/charts": "0.55.0",
    "@carbon/charts-react": "0.55.0",
 -->

#### Affected browser(s)
Chrome only

**Comment by raf18seb** [comment]
Hi @JuhiSharma2, thanks for contacting us!

Are you sure you're reporting a bug on the right repository? We're Highcharts, not Carbon charts :)

**Comment by JuhiSharma2** [comment]
Oh, Sorry for the wrong report. 
Sorry to bother you.
