### ISSUE TITLE
Compare multiple series don't start in the same point on yAxis when zoomed to 6m, 3m, 1m

### ISSUE THREAD

**Issue by ksutin** [highcharts/highcharts#17637]
#### Expected behaviour
Expected to always start compared lines from the same point on yAxis, not just at YTD, 1y, All.

#### Actual behaviour
When multiple lines with 1+yr daily data points compared 
```
plotOptions: {
      series: {
                compare: 'percent',
            }
}
```
zooming in to 1m, 3m, 6m makes the lines start in different points on yAxis, so you can't really compare them.
![image](https://user-images.githubusercontent.com/33686777/186224453-4da0d32e-e58a-4d56-b565-46baf74049af.png)

#### Live demo with steps to reproduce

This example is modified from Highstock Demo by increasing the chart height to 700 px: 
https://jsfiddle.net/ksutine/q0fu6yxe/4/

#### Affected browser(s)
This behavior happens in Chrome, Firefox, Safari, Brave, using either JavaScript (see jsfiddle), or .Net.

**Comment by pawellysy** [comment]
Hi @ksutin! Thanks for reporting this issue!
The current behavior happens, because the `rangeSelector` finds the exact interval, which sometimes makes the effect, that the `xAxis.min` value doesn't match any point. The First point is positioned outside of the current extremes, which makes the effect, that the lines don't match. I would say, that your problem might be a useful enhancement.

 @pawelfus, what do you think?

**Comment by ksutin** [comment]
Hi @pawelysy, 
What would be an approach to always have the lines to start from the same point when zoomed in to various ranges?
Thank you

**Comment by pawellysy** [comment]
Hi again! After some investigation, I forgot that we already have a few options to adjust how compare is behaving.
You can use the option [compareStart](https://api.highcharts.com/highstock/series.line.compareStart) which allows you to set the first point to be compared. Check out this demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/series-comparestart/

Unfortunately, there is not really a better way to do it. If you have any more questions feel free to contact us via our available support channels. https://www.highcharts.com/blog/support/
Thanks!

**Comment by ksutin** [comment]
Thanks so much, @pawelysy. Adding `compareStart: true` in plotOptions.series worked for me. Here's updated fiddle: https://jsfiddle.net/ksutine/q0fu6yxe/5/
