### ISSUE TITLE
bubblemap doesn't seem to work with inset maps like us-all-territories.topo.json

### ISSUE THREAD

**Issue by damontgomery** [highcharts/highcharts#17643]
#### Expected behaviour

If I use a bubblemap with areas that are inset like Alaska, I should see the bubbles.

#### Actual behaviour

The bubbles are never added.

There are no SVG paths, the `graphics` property is missing on the points so they can't be moved, it seems like they are just skipped. Can't zoom out far enough to check if it tried to place a bubble where Alaska would be without the inset, but because of the other issues, I don't think it has.

#### Live demo with steps to reproduce

https://codepen.io/damontgomeryphase2/pen/MWVRdyg

#### Product version
Current versions as of today. See the demo.

#### Affected browser(s)

Tested on Chrome.

#### Example

![Map_bubble](https://user-images.githubusercontent.com/397902/186536507-8cd3b6b1-3b27-4b2e-a9ee-405521074530.jpg)

#### Code sample

```javascript
(async () => {

  const topology = await fetch(
    'https://code.highcharts.com/mapdata/countries/us/custom/us-all-territories.topo.json'
  ).then(response => response.json());

  Highcharts.mapChart('container', {
    chart: {
      map: topology
    },

    series: [
      {
        name: 'Empty to show lines',
      }, {
        type: 'mapbubble',
        name: 'Example',
        data: [
          ['us-ak', 10],
          ['us-hi', 10],
          ['us-ca', 10],
        ],
      }
    ]
  });
})();
```

This shows how California shows correctly, but Hawaii and Alaska do not.

The only difference I can see is that in the data, these are in insets.

Alaska is a multi polygon, but so is Texas and that works too.

Non-bubble maps work fine. I've used gradients and series colors and they work with Alaska fine.

**Comment by raf18seb** [comment]
Hi @damontgomery, thank you for reporting a bug!

Indeed, the mapbubble point's position is calculated based on the wrong inset.
Here is a workaround (works only for the US map (where insets have `'us-'` prefix): https://jsfiddle.net/BlackLabel/zteLbpcq/

```js
// Find inset on which mapbubble/mappoint point should be calculated
// Workaround works only for US map (where insets have an id with 'us-' prefix)
const inset = mapView.insets.find(inset => inset.id === ('us-' + p.name.toLowerCase()));

// Establish plotX and plotY
var plotCoords = (inset || mapView).projectedUnitsToPixels({
    x: x,
    y: y
});
```

**Comment by damontgomery** [comment]
Thanks, @raf18seb.

So, to use this work around you posted, we should essentially overwrite the original function and then we can use `mapbubble` as expected?

I think that seems reasonable. Thanks for the demo!

I wonder if there would be an option for mapbubble series to provide a mapping function to find insets. Or if it could take the approach `series-on-point` takes with the pie charts. I'm not familiar with the code much outside of implementing the charts on this site the past few days.

I'll have to think it over for our use case. I've gone forward with the pie chart work around and one thing that is nice about that one is that we can use pie charts later if-needed.

Thanks again!

**Comment by raf18seb** [comment]
@damontgomery,

> I wonder if there would be an option for mapbubble series to provide a mapping function to find insets.

Could you elaborate? What would you like this option to look like? Isn't automatic finding (the one in my jsFiddle above) enough? (this ticket is tagged as a bug which means that it will be fixed)

> Or if it could take the approach series-on-point takes with the pie charts. I'm not familiar with the code much outside of implementing the charts on this site the past few days.

I wouldn't mix it with `series-on-point` as it's a totally separate feature.

**Comment by damontgomery** [comment]
Thanks for the update.

As I understood, it sounded like it may be difficult to know what inset the point was in. You added a mapping of point -> inset that works for that one map data file. So, I thought if this was difficult to generalize, there could be an option to provide your own point -> inset ID function which the bubble map would use.

My reason for mentioning `series-on-point` is that series-on-point seems to do this already and can figure out where the inset is. But, I'm not familiar with any of the code, just using it as an end-user.

Thanks again and hope that helps. It sounds like you all have a path forward and there are two work arounds in this thread which hopefully helps anyone else until the bug is fixed.
