### ISSUE TITLE
NaN values and data grouping cause tick and series rendering issues

### ISSUE THREAD

**Issue by cebamps** [highcharts/highcharts#17652]
#### Expected behaviour
NaN values in the series data should be tolerated to some extent. (With behaviour matching that of missing data (`null`), I suppose.)

#### Actual behaviour
When missing data is represented as NaN and when data grouping is enabled, there are sometimes unusual glitches that cause axis ticks to appear in the wrong place. The computed axis ranges also do not seem to respect this missing data. Compare:

**Expected:** This series has one point per day; the last 6 days have a `y` value of `null`:
![Screenshot 2022-08-25 at 17 32 59](https://user-images.githubusercontent.com/12797742/186708100-8a6d7397-9783-4ca8-8448-39da85703768.png)

**Issue:** Same as above, with `NaN` instead of `null`:
![Screenshot 2022-08-25 at 17 33 07](https://user-images.githubusercontent.com/12797742/186708106-9eecd949-eb74-426a-a038-7eec2cee1eb4.png)

This shows the two issues I mention:
* The line extends all the way to the end of the axis range, instead of showing a gap for the missing data.
* A tick for August 17 is shown on August 12. This is possibly what this issue was intending to report:  #15321

The glitch depends on how many NaNs are at the end of the series. With 2 days of NaNs instead of 6, the last tick is also wrong, though that stands out less:
![Screenshot 2022-08-25 at 17 43 46](https://user-images.githubusercontent.com/12797742/186710350-d6a9cc36-220e-4cf0-978a-f4162fda56e9.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/kLxra076/

#### Product version
Highstock 10.2.0

#### Affected browser(s)
Firefox, Chrome

**Comment by pawellysy** [comment]
Hi @cebamps, thanks for reporting this issue.
[What API says](https://api.highcharts.com/highstock/series.line.data.y): available values are `null`, and `number`. 
By definition `NaN` values are invalid number values, and we decided not to support them. If you want to handle such behavior, run a map function over a dataset:
```js
data.map(value => Highcharts.isNumber(value) ? value : null)
```
