### ISSUE TITLE
Clicking on date selector jumps to top of page

### ISSUE THREAD

**Issue by DaanVanDeVelde** [highcharts/highcharts#17656]
#### Expected behaviour
Clicking on the date selector opens it up.

#### Actual behaviour
Clicking on the date selector opens it up, but also jumps to the top of the page.

#### Live demo with steps to reproduce
https://jsfiddle.net/p6uwjbac/5/

https://user-images.githubusercontent.com/111854200/186850893-14fdd4e8-c4bd-45b6-a038-1e896cd1b8d1.mp4

#### Product version
Highstock 10.2

#### Affected browser(s)
All browsers, but i can only reproduce it when going on browserstack and setting Windows 8 as my OS (what our client uses)

**Comment by pawellysy** [comment]
Hello @DaanVanDeVelde, thanks for reporting this issue!
The demo you shared does not reproduce the issue. Could you share some more reproduction steps as well as a demo, where the issue is reproduced? Thanks!

**Comment by DaanVanDeVelde** [comment]
Hi @pawellysy , I can't seem to reproduce it in a jsfiddle, but i can resolve the issue by disabling this transition-duration css property. I don't know if it rings a bell?
![image](https://user-images.githubusercontent.com/111854200/187453308-8841fcc0-f8a4-4953-ab15-c19973c11d2f.png)

**Comment by pawellysy** [comment]
Unfortunately, this is not a part of our CSS package. I've checked Windows 11 - Chrome and MacOSv12.4 and chrome, and both work fine. To sum it up, we are unable to recreate your problem. Could you share the OS, and browser details, like version and type?
Thanks!

**Comment by DaanVanDeVelde** [comment]
Our client uses windows 8, Chrome 104, but it has been happening on older versions as well. I have windows 11 as well and can't reproduce it on my device. Will consult our frontend developer to see if we can pinpoint the cause.
