### ISSUE TITLE
I can not put marker above plotband

### ISSUE THREAD

**Issue by nq0w72G** [highcharts/highcharts#17666]
In my project, plotband is default above custom marker symbol icon, however i would like custom marker symbol icon above plotband and plotline, but i can not implement that

**Comment by pawellysy** [comment]
Hi @nq0w72G , thanks for contacting us with your question.
Our GitHub channel is treated as a bug/feature tracking tool. For these kinds of questions, please get in touch with us via dedicated support channels, which you can find here: https://www.highcharts.com/blog/support/.

Our support engineers will be more than happy to help you, to tweak the chart's configuration too much your needs.
Thanks for understanding!
