### ISSUE TITLE
how to set xy area background ?

### ISSUE THREAD

**Issue by jingyuLin1999** [highcharts/highcharts#17667]
#### Expected behaviour

![image](https://user-images.githubusercontent.com/30433062/187168727-48089c9f-a9ca-49ca-ba61-fc588d643087.png)

**Comment by raf18seb** [comment]
@jingyuLin1999 isn't it what you're looking for? https://www.highcharts.com/blog/tutorials/drawing-plotbands-with-limits-using-annotations-part-1/
