### ISSUE TITLE
ichimoku cloud

### ISSUE THREAD

**Issue by maddrid** [highcharts/highcharts#17664]
#### Expected behaviour
Cloud to match other providers

#### Actual behaviour
 Cloud do not match

#### Product version
Highstock JS v10.2.0 (2022-07-05)

 All technical indicators for Highcharts Stock

#### 
![ick](https://user-images.githubusercontent.com/5124319/187094033-6be9ef43-0e63-4770-b0a0-85cea172feac.png)
![ick2](https://user-images.githubusercontent.com/5124319/187094038-a8eb3d6d-f673-43ac-bcbe-73c42e2245e5.png)

**Comment by pawellysy** [comment]
Hi @maddrid, thanks for reaching out to us with your issue.
Could you please share the dataSet, that you used, and maybe create a live demo, where the issue is reproduced? 
Could you also please share other providers' details, so that we could compare both values? 
Thanks!

**Comment by maddrid** [comment]
Hi .
 [ https://jsfiddle.net/9jryzdca/](url)    js fiddle  with 19 Aug  last day of data.  (utc time )
  as for reference 
  [https://www.tradingview.com/chart/?symbol=FTX%3ASOLUSD](url) 
[https://ftx.com/trade/SOL/USD](url)

**Comment by pawellysy** [comment]
Thanks for the links!
I was wondering if you might have some reference for the IKH indicator, where I might find a formula so that I could check our implementation.

**Comment by maddrid** [comment]
Hi  @pawellysy .
 [https://jsfiddle.net/9jryzdca/ ](url)
 on this fiddle there is a  sample of  78 000 -5 min candles  from ftx exchange api .( tested, and retested,, on my setup match 100 % with    sol/usd ftx charts ) you can use it as set of data to compare  the output of the cloud
  the formula used by tradingview for ichimoku is  in pine script 
 ```javascript
//@version=5
indicator(title="Ichimoku Cloud", shorttitle="Ichimoku", overlay=true)
conversionPeriods = input.int(9, minval=1, title="Conversion Line Length")
basePeriods = input.int(26, minval=1, title="Base Line Length")
laggingSpan2Periods = input.int(52, minval=1, title="Leading Span B Length")
displacement = input.int(26, minval=1, title="Lagging Span")
donchian(len) => math.avg(ta.lowest(len), ta.highest(len))
conversionLine = donchian(conversionPeriods)
baseLine = donchian(basePeriods)
leadLine1 = math.avg(conversionLine, baseLine)
leadLine2 = donchian(laggingSpan2Periods)
plot(conversionLine, color=#2962FF, title="Conversion Line")
plot(baseLine, color=#B71C1C, title="Base Line")
plot(close, offset = -displacement + 1, color=#43A047, title="Lagging Span")
p1 = plot(leadLine1, offset = displacement - 1, color=#A5D6A7,
	 title="Leading Span A")
p2 = plot(leadLine2, offset = displacement - 1, color=#EF9A9A,
	 title="Leading Span B")
fill(p1, p2, color = leadLine1 > leadLine2 ? color.rgb(67, 160, 71, 90) : color.rgb(244, 67, 54, 90))
```
  source code can be viewed as  shown in  picture ( search indicator,set for curent chart, view  source ) on advanced chart
![Untitled](https://user-images.githubusercontent.com/5124319/187752200-b8e4cddd-71e8-48db-a033-aa4890c4f06b.png)  
 thanks for your time !

**Comment by pawellysy** [comment]
So, from what we noticed, the thing is, we have a correct algorithm, but somehow we messed up a bit the positions of each line. 

`Internal Note`

in this method: 👇 https://github.com/highcharts/highcharts/blob/b6f2d51707d2fe001131cb6ca7f0b98a780ec93c/ts/Stock/Indicators/IKH/IKHIndicator.ts#L814

Each time the `IKH[i + period]` should be converted to `IKH[i + period - 1]` and `IKH[i + 2 * period]` to `IKH[i + 2 * period -2]`


Workaround demo: http://jsfiddle.net/BlackLabel/bwgno6jh/29/

Let me know if that works correctly! Thanks!

**Comment by maddrid** [comment]
100 %  the cloud match 👍  one little thing with the chikou span , but  looking at other ick ,implementations  may differ ,  i guess the difference it's in the  interpretation of  candle where  start counting.
![ick](https://user-images.githubusercontent.com/5124319/188243575-790c3fb4-8c61-4cc4-afad-2f81b19d7b83.png)
![ick2](https://user-images.githubusercontent.com/5124319/188243585-68f661f9-cbe4-4a88-9ec3-0b51b323a601.png)
![ick3](https://user-images.githubusercontent.com/5124319/188243741-cbe6487b-42f0-46b0-9d53-1ba36d2ce348.png)
![ick4](https://user-images.githubusercontent.com/5124319/188244162-31eb160f-ca0e-4824-97a7-95fb405c9c48.png)

**Comment by pawellysy** [comment]
Thanks for investigating the issue so thoroughly! For now, please use a workaround, but we hope to fix this calculation error soon.
