### ISSUE TITLE
text and border are not aligned for sunburst chart since Highcharts v10.2.1

### ISSUE THREAD

**Issue by stramin** [highcharts/highcharts#17677]
Until version v10.2.0 I was able to write `<br/>` to create a new line for sunburst labels, yesterday it begun to separate text and border in different lines.

#### Expected behaviour
Text and border labels should line up in the same position when I write `<br/>`.

#### Actual behaviour
Text and border are separated in 2 different positions
![image](https://user-images.githubusercontent.com/17409281/187478366-c0b33366-b2b8-405b-9153-628433268041.png)

#### Live demo with steps to reproduce
template: https://jsfiddle.net/stramin/d6geqtbp/

#### Product version
Highcharts v10.2.0

#### Affected browser(s)
Chrome V 104

**Comment by karolkolodziej** [comment]
Thank you @stramin for reporting that issue.

It looks like a regression after https://github.com/highcharts/highcharts/commit/b3d627e9d3cbd45ce7f9c45ceb17216e5a217e25 FYI @TorsteinHonsi 

For now, you can use the previous (10.2.0) version- [demo](https://jsfiddle.net/BlackLabel/sf13owem/).
Or set the `useHTML` for the data label- [demo](https://jsfiddle.net/BlackLabel/pgh3yj5c/).

**Comment by stramin** [comment]
Thank you so much for your help and giving me these options, for now I am using CSS text-shadow, the result is not as good as before, but it works while we wait for a fix.
