### ISSUE TITLE
Chart redraw exception with invisible series due to skipped extremes calculation

### ISSUE THREAD

**Issue by TimoRoth** [highcharts/highcharts#17678]
#### Expected behaviour
When (re)drawing a chart with an invisible series, it should not throw an error.

#### Actual behaviour
If you have a Series which is invisible, without a max or min set, HighCharts will throw an error on redraw:
`Uncaught TypeError: can't access property "length", tickPositions is undefined`.

The error happens in this line:
https://github.com/highcharts/highcharts/blob/06e510915541b2215f65be7535076a8599448107/ts/Core/Axis/Axis.ts#L2057

This happens because for hidden series, the extremes are never calculated, which over a bunch of corners leads to above failure.

I could fix this issue in my deployment by just always making the following condition true:
https://github.com/highcharts/highcharts/blob/06e510915541b2215f65be7535076a8599448107/ts/Core/Axis/Axis.ts#L705

#### Live demo with steps to reproduce
https://jsfiddle.net/BtbN/1bm86c4g/12/

Initially, this will throw the mentioned error.
Commenting in the `ignoreHiddenSeries: false` option makes it works fine, as it makes above condition pass, and calculate the extremes, which ultimately leads to tickPositions not being undefined.

#### Product version
Latest HighCharts at time of writing: 10.2.1

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
Thank you @TimoRoth for reporting that!

_Internal note:_ 
Bisected to: https://github.com/highcharts/highcharts/commit/3eff118e8176e904c857e290bfff0228c6ec3fa9 FYI @TorsteinHonsi 
Works well in v10.0.0- [demo](https://jsfiddle.net/BlackLabel/f18zupvk/).

**Comment by TorsteinHonsi** [comment]
#### Minimal demo
https://jsfiddle.net/highcharts/91426cor/
