### ISSUE TITLE
Not able to load highcharts-more.js using require.js

### ISSUE THREAD

**Issue by KoustubhK18** [highcharts/highcharts#17674]
#### Expected behaviour
highcharts-more.js should get loaded and Spiderweb chart should get displayed since "polar:true" option is passed in charts of Highchart.

#### Actual behaviour
highcharts-more.js does not load and line-chart should gets displayed.

#### Live demo with steps to reproduce
[Demo](https://codesandbox.io/embed/static-forked-qfudrt)

#### Product version
Highcharts.8.2.2

#### Affected browser(s)
Chrome

Could you please let me know if this is the correct way to load highcharts-more file using require.js or is there any other way?

Thanks for your help,
Koustubh

**Comment by js-yo** [comment]
demo: https://codesandbox.io/s/static-forked-tykett?file=/js/index.js
documentions: https://github.com/highcharts/highcharts#load-highcharts-from-the-cdn-as-an-amd-module
