### ISSUE TITLE
When useHTML and stickOnContact set, tooltip freezes sometimes.

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#17685]
#### Expected behaviour
Smooth tooltip refreshing.

#### Actual behaviour
When `useHTML` and `stickOnContact` set to true, tooltip freezes sometimes while hovering over chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/txavf7ec/
![1](https://user-images.githubusercontent.com/57004120/187847724-1aba432f-abd7-4477-97af-bb574181228f.gif)

#### Product version
 Highcharts JS v10.2.1 (2022-08-29)

#### Affected browser(s)
All

**Comment by OliverDamsbjerg** [comment]
Is there an estimation of when this might be looked at? It happens a lot more in our project compared to the example shown and it's confusing a lot of people here.

**Comment by bre1470** [comment]
Turning `useHTML` off makes it work flawless. The issue starts with v9.2.0.

**Comment by el-davo** [comment]
Is anyone aware of a workaround other than turning off HTML? Unfortunately we need this turned on as it is a custom tooltip

**Comment by hryhorii-kharchenko-digis** [comment]
Unfortunately, the proposed workaround of disabling "useHTML" option doesn't satisfy our goals, since we display an HTML table inside of the tooltip. We also cannot turn off "stickOnContact" option, because we use a link inside of the tooltip.

Is there any other workaround we could use?

**Comment by tsahilevi** [comment]
This makes the whole use of rich tooltips on charts unusable and a workaround of using only text isn't really a workaround...
It would be great if this can be properly prioritized and addressed. For us, we will need to evaluate our use of highcharts

**Comment by TorsteinHonsi** [comment]
Thank you for your patience! I created a draft PR but it requires some validation. Please check out the OP chart with the fix applied here: http://jsfiddle.net/highcharts/0ubatfdr/

**Comment by TorsteinHonsi** [comment]
@hryhorii-kharchenko-digis and @tsahilevi we now have something we believe will fix the issue. But to be absolutely sure, it would be great if you test it in your actual implementation. You can load https://github.highcharts.com/047bc85/highcharts.js .

**Comment by TorsteinHonsi** [comment]
Okay, since I didn't hear anymore I assume it works well and merge the PR.

**Comment by hryhorii-kharchenko-digis** [comment]
Sorry, I found what now seems to be an unrelated bug while testing on our setup and was busy trying to create a reproducible demo.

Your fix in question seems to work for our use-case. But I accidentally noticed that it breaks "outside" option, which was working before. When you hover on the tooltip it disappears completely.

Before fix with "outside": true 
http://jsfiddle.net/bzhg0vjo/2/

After fix with "outside": true
http://jsfiddle.net/Ljxd37cf/

**Comment by hryhorii-kharchenko-digis** [comment]
@TorsteinHonsi
Just to make sure you would notice: the approved solution might have a bug with the "outside" option. I've provided demos in the comment above.

**Comment by el-davo** [comment]
Hi @TorsteinHonsi I notice this issue is closed but the fix is not deployed to npm registry. Is it possible for the fix to be deployed there?. We are using npm for dependency management so its not a trivial thing to use the file available on master

**Comment by pawellysy** [comment]
@el-davo, it will be included in the next official release, which should take place soon. Thanks for your patience!
