### ISSUE TITLE
Add custom arguments to points in chart

### ISSUE THREAD

**Issue by Usbac** [highcharts/highcharts#17694]
# Description of the feature
Add arguments to a point, which can be used in callback events (like the ones used in `plotOptions.series.point.events.click`).

It would be good to have the option to give to each point in the chart custom arguments or data, which then can be used in elements like callbacks.

One use case is a page showing both a chart made in Highcharts and a listing showing the same data but in a different format (made with pure HTML/CSS/JS). Clicking one point in the Highcharts chart highlights the row it references in the list.

# Library related to the feature
Highcharts Stock

cc @AnnDKan @rpm73 @OskarHumnicki

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by pawellysy** [comment]
Hello @Usbac, this feature is already available. Just use this property: https://api.highcharts.com/highcharts/series.line.data.custom
