### ISSUE TITLE
[iOS] Wrapper

### ISSUE THREAD

**Issue by SolorzanoJose** [highcharts/highcharts#17695]
Hello, the website says there is a mobile wrapper for highcharts but I can't seem to find it anywhere?

**Comment by js-yo** [comment]
* github repo: https://github.com/highcharts/highcharts-ios
* api: https://api.highcharts.com/ios/highcharts/

**Comment by pawellysy** [comment]
@SolorzanoJose, thanks for reaching out to us! Those links are correct. If you need any more information, feel free to reach out to us via our dedicated support channels: https://www.highcharts.com/blog/support/


@js-yo thanks for the prompt response!
