### ISSUE TITLE
Weeknumber in dateFormat function

### ISSUE THREAD

**Issue by alexp83** [highcharts/highcharts#177]
Can you add the weeknumber in the dateFormat function? php's date function uses "W" for it. At the moment in the code there is

// Week (none implemented) (line 1340)

Thanks,

Alex

**Comment by KacperMadej** [comment]
Week number could be added as seen in [this demo](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/global/dateformats/) and as explained in [Highcharts.dateFormats](https://api.highcharts.com/class-reference/Highcharts.html#.dateFormats) API reference.

Using dateFromats you can defined custom date formats.
