### ISSUE TITLE
XAxis Labels, after point update and chart redraw, labels are mispositioned.

### ISSUE THREAD

**Issue by dragoshzava** [highcharts/highcharts#17705]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/3819194/188835929-fb094f09-a17f-42bf-ad5e-f71cc02e572d.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/3819194/188835969-cfefe6ab-7979-42a5-a385-e262c2204da8.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/Resems/gc6oxmps/

#### Live demo working ( when the point update redraw is true, and then chart redraw is called, everything is fine )
https://jsfiddle.net/Resems/gc6oxmps/1/

#### Product version
Latest 

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hello @dragoshzava,
Thanks for reporting the issue! We will treat it as a bug, but I have a few comments on your example, where you can avoid such a problem. 
In my opinion, your code is a bit messy. First, as we can read in our documentation, the category axis type is used to display the categorical data. In your example, your "categories" are more of a DateTime type, so you could try using it instead. The easiest way would be parsing the name of each point to be read as a js timestamp value. Why don't you try this approach?

So drop-in workaround would be calling `chart.reflow()` after a redraw. 
https://jsfiddle.net/BlackLabel/bLwzcgk0/1/
