### ISSUE TITLE
Regression: chart.Options.resetZoomButton is no longer typed on Highcharts.Options

### ISSUE THREAD

**Issue by wjaspers** [highcharts/highcharts#17703]
#### Expected behaviour
Defining chart options with `resetZoomButton` compiles.

Example working code:
```
chartOptions: Highcharts.Options = {
   chart: {
       resetZoomButton: {
           position: { ... }
       }
   }
} as Highcharts.Options;
```

#### Actual behaviour
When defining a chart with `resetZoomButton` options, the typing is now missing and a compilation error occurs.

Example code:
```
chartOptions: Highcharts.Options = {
   chart: {
       resetZoomButton: {
           position: { ... }
       }
   }
}
```

```
Error: src/app/my-component/my-component.ts:8:13 - error TS2322: Type '{ backgroundColor: string; resetZoomButton: { position: { x: number; }; }; spacingTop: number; spacingBottom: number; type: string; zoomType: string; }' is not assignable to type 'ChartOptions'.
  Object literal may only specify known properties, and 'resetZoomButton' does not exist in type 'ChartOptions'.

  38             resetZoomButton: {
                ~~~~~~~~~~~~~~~~~~
  39                 position: {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 65                 },
    ~~~~~~~~~~~~~~~~~~
 66             },
    ~~~~~~~~~~~~~

  node_modules/highcharts/highcharts.d.ts:17442:5
    17442     chart?: ChartOptions;
              ~~~~~
    The expected type comes from property 'chart' which is declared here on type 'Options'
```

#### Product version
Affected version 10.2.1
Last known good version 10.2.0

#### Affected browser(s)
Any

**Comment by pawellysy** [comment]
Probably regression after: https://github.com/highcharts/highcharts/pull/17215
FYI @hihajdus

**Comment by pawellysy** [comment]
We should keep the backward compatibility, so if some option is moved elsewhere, some charts that used to work with the old options should still have an option to work currently. What do you think @TorsteinHonsi?

**Comment by TorsteinHonsi** [comment]
@pawellysy [According to the API](https://api.highcharts.com/highcharts/chart.resetZoomButton), `chart.resetZoomButton` is _deprecated_, not removed.

That means it should be part of the type definitions. Is there a bug in how deprecated options are represented in `highcharts.d.ts`? FYI @bre1470 .

**Comment by bre1470** [comment]
Deprecated options are not exposed in the definitions.

**Comment by Waterstraal** [comment]
I'm having this exact same issue for `zoomType`: 

`Object literal may only specify known properties, and 'zoomType' does not exist in type 'ChartOptions'.`

It's deprecated in the [docs](https://api.highcharts.com/highcharts/chart.zoomType), but the declaration is removed in 10.2.1. (It was still there in 10.2.0).

This change was introduced in the latest _patch_ release. A patch release should not have breaking changes. Could you withdraw this release until this is resolved? 

Also, I don't see any mention of what to use instead. I would expect an alternative to be mentioned alongside the deprecation. 

Thank you

**Comment by pawellysy** [comment]
Hello @Waterstraal, thanks for reaching out to us. We did zooming options refactor, which you can find here: https://github.com/highcharts/highcharts/pull/17215
This PR changed all options, which were referring to zooming, to be referenced by [chart.zooming](https://api.highcharts.com/highcharts/chart.zooming). Of course, all of the previous options should only be deprecated but still work. We will add a new references to the new options in the API as well. Thanks for pointing this out!


`Internal note`
 add the reference to the new options in the API as well.
