### ISSUE TITLE
Variwide Graphs do not adhere to the min/max with no padding

### ISSUE THREAD

**Issue by caradec-CEM** [highcharts/highcharts#17717]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/111604654/189190794-d198171e-a4d4-47e0-8021-ff94fb7ac1ac.png)
Given the settings in the JSFiddle, this graph should start and end exactly at 0.

#### Actual behaviour
The graph has extra padding around the data.

#### Live demo with steps to reproduce
https://jsfiddle.net/q09s5mur/33/

#### Product version
Highcharts 7.2.2
highcharts-react-official 2.2.2

#### Affected browser(s)
Chrome

**Comment by pawellysy** [comment]
Hello @caradec-CEM, 
This is the desired behavior. As you can [read in our API](https://api.highcharts.com/highcharts/series.variwide.pointPlacement): 

> In a column chart, when pointPlacement is "on", the point will not create any padding of the X axis. In a polar column chart this means that the first column points directly north. If the pointPlacement is "between", the columns will be laid out between ticks. This is useful for example for visualising an amount between two points in time or in a certain sector of a polar chart.

Setting this option to 'on' solves the issue. https://jsfiddle.net/BlackLabel/rn32ogmp/1/

Please, before treating something as a bug, first reach out to our support engineers who are more than happy to help, to customize the chart to your needs.  Here is the link to our available support channels: https://www.highcharts.com/blog/support/
Thanks!
