### ISSUE TITLE
Client side export with custom buttons

### ISSUE THREAD

**Issue by pcjn** [highcharts/highcharts#17718]
#### Expected behaviour
When using client side export with custom buttons in Angular, no request should be sent to export.highcharts.com.

#### Actual behaviour
The request to export.highcharts.com is still made, even if I set exporting.fallbackToExportServer to false (but it should work without it also, right?)

#### Live demo with steps to reproduce

[stackblitz](https://stackblitz.com/edit/angular-chart-export-eiibor?file=src/app/app.component.ts)

#### Product version
  highcharts: 7.2.2
  Angular: 11.2.14

#### Affected browser(s)

Chrome 105.0.5195.102

**Comment by pcjn** [comment]
I have also tried using the exportChartLocal function with fallbackToExportServer: 
```
chart.exportChartLocal(
        {
          type: type,
          filename: name,
          fallbackToExportServer: false,
         }
...
```
but when I add fallbackToExportServer, it results in Error: Highcharts error #28: www.highcharts.com/errors/28/ (even though the charts I'm using are pretty basic).
My question: is it possible in Angular to export offline using an external button ? I haven't found an example with Angular.

**Comment by KacperMadej** [comment]
Hi @pcjn 

I have tried the button after Not Working text ("Export as csv") and it works fine for me, so I am not sure how should I use your demo.

Exporting module should be loaded first, so like:
```js
HC_exporting(Highcharts);
HC_offlineExporting(Highcharts);
```

You have written in the bug report that v7 is to be used but this is not the case for your demo that is using v8. Why are you using Highcharts version 8? There might be an already fixed bug in the older code so it would be better to use the current version.

offline-export module is redefining exporting buttons with new functions like:
```js
            menuItemDefinitions: {
                downloadPNG: {
                    textKey: 'downloadPNG',
                    onclick: function () {
                        this.exportChartLocal();
                    }
                },
                downloadJPEG: {
                    textKey: 'downloadJPEG',
                    onclick: function () {
                        this.exportChartLocal({
                            type: 'image/jpeg'
                        });
                    }
                },
                downloadSVG: {
                    textKey: 'downloadSVG',
                    onclick: function () {
                        this.exportChartLocal({
                            type: 'image/svg+xml'
                        });
                    }
                },
                downloadPDF: {
                    textKey: 'downloadPDF',
                    onclick: function () {
                        this.exportChartLocal({
                            type: 'application/pdf'
                        });
                    }
                }
            }
```
so if you want to export via function call in a local mode you should call these functions instead of `exportChart`.

I have changed the modules loading order and the below code is working fine for me (Chrome/Win11):
```js
        this.lineChart.chart.exportChartLocal({
          type: 'image/png',
          filename: 'line-chart',
        });
```

Could you update your demo and add more details (based on my questions in this comment)?

**Comment by pcjn** [comment]
Hi @KacperMadej,
Thank you for your response.

I have updated the [demo](https://stackblitz.com/edit/angular-chart-export-eiibor?file=src%2Fapp%2Fapp.component.ts) with highcharts v9.3.3 and used exportChartLocal function, but the problem persists. 

My problem is that when I use offline exporting, the request to https://export.highcharts.com/ is still made.
![highchartsRequest](https://user-images.githubusercontent.com/26898529/190362918-53baee96-1e34-4162-97bd-909cc5d8d2f1.PNG)

Yes, the export is still working, but the reason why I'm using offline export module is so that the request to export.highcharts.com isn't made.
Should this offline export work in Angular? I've seen plenty examples with offline exports in JS working correctly (no request to highcharts made).

**Comment by pcjn** [comment]
Hi,

I have tried on a different environment and it works (except that version 7.2.2 doesn't export pdf, as per documentation). So the problem was on my side.

Thank you.
