### ISSUE TITLE
Hight chart graph not visible

### ISSUE THREAD

**Issue by AkashBawa** [highcharts/highcharts#17710]
Hi,

I am setting up highhart-export-server but it does not give any graph instead it only shows the chart title.  Here is the screen shot
![Screenshot](https://user-images.githubusercontent.com/40368346/189092178-c43b17b5-e5e4-4454-b52e-3a9a3a20f557.png)

Expected behavior: here is the screenshot of my required output.

![required_chart](https://user-images.githubusercontent.com/40368346/189092590-3db0f42c-b9a9-420a-9131-8b83daf8664b.png)

I am using highcharts-export-server with node + AWS lambda.  I also run node node_modules\highcharts-export-server\build.js command . 

Please help here as soon as possible.

Thanks

**Comment by pawellysy** [comment]
Hi @AkashBawa,
Our GitHub channel is treated as a bug/feature tracking tool. For these kinds of questions, please get in touch with us via dedicated support channels, which you can find here: https://www.highcharts.com/blog/support/.

Our support engineers will be more than happy to help you, to tweak the chart's configuration too much your needs.
Thanks for understanding!
