### ISSUE TITLE
Change the datalebel of heatmap on double click

### ISSUE THREAD

**Issue by vishalpawar048** [highcharts/highcharts#17724]
# Description of the feature

We want a heatmap to show weekly expenditure in our product's analytics dashboard. We need an inline editing feature to change some of the spendings in the coming weeks for particular days. We can edit the heatmap labels from external input but it would be really easy and convenient for the user to just double-click on the cell and edit the value (dataLebel).

I am not sure if we can achieve this in the existing heatmap version 10.2.1. I tried to use <input type="text" /> tag but it didn't work.

# Library related to the feature
Highcharts heatmap

**Comment by pawellysy** [comment]
Hi @vishalpawar048, you can use the https://www.npmjs.com/package/highcharts-custom-events, for dblclick and show some HTML or SVG element to hover over the chart to insert the value there. If you need any more help, please reach out to us via our available support channels, which are listed here: https://www.highcharts.com/blog/support/
Thanks!
