### ISSUE TITLE
[colorAxis] [crosshair] [arrow] with paged legend colorAxis hovering renders very small crosshair(arrow)

### ISSUE THREAD

**Issue by lekarsenten** [highcharts/highcharts#17723]
#### Expected behaviour
Size of colorAxis arrow remains constant/arrow is visible while hovering on point.

#### Actual behaviour
If legend contains colorAxis and legend has pagination, colorAxis crosshair (arrow) appearing on point hover is very small.

#### Live demo with steps to reproduce
[https://jsfiddle.net/9efhnadc/](https://jsfiddle.net/9efhnadc/)
(basically colorAxis example with smaller chart and additional axes) 

#### Product version
Latest Highcharts (10.2.1)

#### Affected browser(s)
Tested on Chrome 105.0

CSS classes for quick look: `highcharts-crosshair highcharts-crosshair-thin highcharts-coloraxis-marker`
Reason apparently is in clip-path for legend pagination

Any workarounds?

**Comment by karolkolodziej** [comment]
You can add that `crosshair` to a group that is "higher" in the DOM and won't be clipped by this `clip-path`.

Workaround: https://jsfiddle.net/BlackLabel/L3gf9n1k/

**Comment by lekarsenten** [comment]
@karolkolodziej thank you, this should be sufficient for now.
