### ISSUE TITLE
Gantt doesn't work while using array of arrays as a data

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#17738]
#### Actual behaviour
While using an array of arrays (instead of an array of objects), the Gantt allows only one point. If we try to add more, the chart doesn't load up and it throws `indexOf is not a function` error.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5t97fr0c/

Uncomment the 6th line to see the error.

#### Product version
Highcharts Gantt v10.2.1 (latest)

**Comment by karolkolodziej** [comment]
_Internal note:_
See the PR that added `keys` support for Gantt: https://github.com/highcharts/highcharts/pull/14026

**Comment by bhandurejitu** [comment]
any update on this?

**Comment by karolkolodziej** [comment]
Yes, the PR that is linked only works for a single array. What I meant is that the fix should be concentrated on changing that.

Besides that, there has been no change.

**Comment by bhandurejitu** [comment]
@karolkolodziej 
which one series of data work fast for any chart the array of objects or unstructured data?

**Comment by bhandurejitu** [comment]
if I pass unstructured data then it will take time to process or it will work normally like the array of object data?

**Comment by karolkolodziej** [comment]
@bhandurejitu If you declare data as an array of arrays it is going to be faster than objects but still with reasonable amount of data (~5k points) the difference should not be that noticible.

**Comment by bhandurejitu** [comment]
> @bhandurejitu If you declare data as an array of arrays it is going to be faster than objects but still with reasonable amount of data (~5k points) the difference should not be that noticible.

with unstructured data also?

**Comment by millieqiu** [comment]
Hi, I still face the same problem on version Highcharts 11.4.6
is there any update on this?

**Comment by hubertkozik** [comment]
Hi @millieqiu! Thank you for pointing out this issue. I've added it to our backlog, you will get notifications here when the work will be started.
