### ISSUE TITLE
bug(regression): StockChart displaying datetime in incorrect order on Axis when using min and max ranges

### ISSUE THREAD

**Issue by tidusjar** [highcharts/highcharts#17730]
#### Expected behaviour
The chart should render the xAxis date time correctly and in the correct order:
Example on Highcharts 9.1.2
![image](https://user-images.githubusercontent.com/6642220/190231937-1b14122e-b203-4fb2-8728-f8e4efdf2baf.png)

#### Actual behaviour
The date time is in an incorrect order when using the xAxis min and max values, See the 24th Aug is before the 23rd Aug.

This seems to have been introduced in `v9.2.0`, it is working as expected on `v9.1.2`
![image](https://user-images.githubusercontent.com/6642220/190232016-59d8a4e7-da7b-49bc-bdef-9f5609930c29.png)

#### Live demo with steps to reproduce
https://codesandbox.io/s/angular-forked-7kzen5?file=/src/app/app.component.ts

#### Product version
HighStock 10.2.1

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
Thank you @tidusjar for reporting that.

Changes were introduced in v.9.2.0 where the `ordinal` logic was changed, however, I was not able to bisect.
Thus it needs further investigation.

As a workaround you can:
- disable the `ordinal` for the xAxis- [demo](https://jsfiddle.net/BlackLabel/f26a3tup/)
- do not set the extremes or set them to be within the data range- [demo](https://jsfiddle.net/BlackLabel/a7z8v63f/)

**Comment by tidusjar** [comment]
Thanks for the reply, 

I think that keeping `ordinal` set to `true` need to happen as we do not want to show whitespace, but you raise a good point. If `ordinal` is set to true we probably don't need to set the date range as the chart should automatically work out the date ranges and fill the chart?
