### ISSUE TITLE
bug: not able to hide data table from highchart export option when it's rendered below a table with thead

### ISSUE THREAD

**Issue by ganeshps17** [highcharts/highcharts#17731]
#### Expected behaviour

User should be able to open and hide data-table from highcharts export option

![image](https://user-images.githubusercontent.com/87961350/190334175-0ee2a9ea-b365-48ae-96c1-310ec6ee1404.png)

#### Actual behaviour

Error occurs when clicking view data table option from export and user is not able to hide the data table

****Note: This error only occurs when the highcharts is rendered below a table with thead.**** 

https://github.com/highcharts/highcharts/pull/17154/files#diff-cef6e25630962677be4a94d5ecb5a257df6355c123f2306b4389afd50c8c0456R490

#### Live demo with steps to reproduce

1. Click on Highcharts export button
2. Select View Data Table
3. The below mentioned error occurs and user is not able to hide the data table

http://jsfiddle.net/eujv2tnp/

Error Log:
core.mjs:6494 ERROR TypeError: b.closest is not a function
    at export-data.js:16:493
    at NodeList.forEach (<anonymous>)
    at f.<anonymous> (export-data.js:16:457)
    at highcharts.js:18:251
    at Array.forEach (<anonymous>)
    at x (highcharts.js:18:229)
    at d.toggleDataTable (export-data.js:30:29)
    at f.onclick (export-data.js:31:296)
    at HTMLLIElement.onclick [as __zone_symbol__ON_PROPERTYclick] (exporting.js:32:57)
    at HTMLLIElement.wrapFn (zone.js:766:1)

StackOverflow Ref:
https://stackoverflow.com/questions/73233524/highcharts-error-when-loading-data-table-throw-export-module#comment129361311_73233524

#### Product version

Highcharts [v10.2.0] (https://github.com/highcharts/highcharts/releases/tag/v10.2.0)
PR this change was brought in:- 
https://github.com/highcharts/highcharts/pull/17154

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hello @ganeshps17, thanks for reporting this bug!

Workaround: http://jsfiddle.net/BlackLabel/e9a3o0xL/1/

FYI @karolkolodziej

**Comment by madepiet** [comment]
fixed on master: https://jsfiddle.net/BlackLabel/wjk9Lqvu/
