### ISSUE TITLE
Highcharts Stock updating stock tools in a pure JS environment

### ISSUE THREAD

**Issue by leo4707** [highcharts/highcharts#17741]
#### Expected behaviour
The gui buttons should work normally(stocktools gui buttons are not default), when using setState to update data in option.

#### Actual behaviour
The gui buttons cannot work(stocktools gui buttons are not default), when using setState to update data in option.

#### Live demo with steps to reproduce
https://codesandbox.io/s/elated-euler-6jo71k?file=/src/App.js

#### Product version
"highcharts": "^10.2.1",
"highcharts-react-official": "^3.1.0"

**Comment by karolkolodziej** [comment]
Thank you @ueuuop8591  for reporting the issue.

[JS Demo](https://jsfiddle.net/BlackLabel/z3jehapg/)

**Comment by khlieng** [comment]
Regression since 10.2.1, also happens if you hide and show the stock tools on https://www.highcharts.com/demo/stock/stock-tools-gui
