### ISSUE TITLE
Timeline charts are hogging CPU for more than 350 data points.

### ISSUE THREAD

**Issue by jainprashul** [highcharts/highcharts#17743]
#### Actual behaviour
Timeline charts are hogging CPU for more than 350 points. Atleast it should around the common use case of around 1000 points. 
The Boost module still not work with timeline graph as well.

#### Product version

Highchart 9.3.3
Edge 12
#### Affected browser(s)
Chrome 105

**Comment by pawellysy** [comment]
Hello @jainprashul, thanks for reporting this issue!
I don't really understand what you mean by 'hogging CPU'. Could you share the live demo, and explain that issue more thoroughly?

**Comment by pawellysy** [comment]
Closing - No reproduction steps
