### ISSUE TITLE
searchPoint finds wrong point when series is visible: false

### ISSUE THREAD

**Issue by ziebelje** [highcharts/highcharts#17756]
#### Expected behaviour
See demo below.

#### Actual behaviour
See demo below.

#### Live demo with steps to reproduce
https://jsfiddle.net/b1vp4a6u/1/

I have modified the official fiddle to duplicate each series, enabled the legend, and enabled zooming.

The initial speed value is 13.8km/h.
![image](https://user-images.githubusercontent.com/3288812/191396148-a9f05da9-359b-45ba-b2a3-23ad0e650653.png)

If you leave both series enabled, you can zoom anywhere on the charts and everything is fine:
![image](https://user-images.githubusercontent.com/3288812/191396158-ab3192db-0fca-4169-b35b-3db1e03545f2.png)

Reset the zoom, then disable the first series:
![image](https://user-images.githubusercontent.com/3288812/191396192-a4c577c6-4626-41f5-b72a-26a4f8d270f3.png)

Now zoom in somewhere:
![image](https://user-images.githubusercontent.com/3288812/191396205-8b542e0d-2682-49d8-9bfd-00fbf8ceb04b.png)

The value returned from searchPoint is incorrect when the series you call it on is visible: false. Instead of finding a point according to the zoomed extents of the chart, it uses the full x-range.

#### Product version
Highcharts v10.2.1

#### Affected browser(s)
Firefox 104.0.2 (64-bit) (at minimum; probably others)

**Comment by karolkolodziej** [comment]
Hi @ziebelje, thank you for contacting us!

When we created that demo we didn't consider having multiple series on a single chart which is why we hardcoded from which series the points should be searched.
```JS
        // Get the hovered point
        point = chart.series[0].searchPoint(event, true);
```
Please modify the piece of code from the snippet above to handle multiple series on the chart- [demo](https://jsfiddle.net/BlackLabel/j63muf5r/).
