### ISSUE TITLE
With multiple axis and 'centerInCategory: true', columns are rendered one over another instead of being aligned side by side, without any way to control this

### ISSUE THREAD

**Issue by vitaliy-kretsul** [highcharts/highcharts#17764]
#### Expected behaviour
Columns nicely aligned side by side no matter if they belong to different yAxis (or a special api setting to control this behavior)

#### Actual behaviour
Columns are rendered one over another if they belong to different yAxis (without any way to control this)

#### Live demo with steps to reproduce
https://jsfiddle.net/Cortez/m83gbhta/

#### Product version
Highcharts v10.2.1

#### Affected browser(s)
Google Chrome 105.0.5195.125

**Comment by karolkolodziej** [comment]
Hi @vitaliy-kretsul!

Please slightly change the point placement for each series with the `pointPlacement` property ([API](https://api.highcharts.com/highcharts/series.column.pointPlacement)).
You can use numerical values to move one series to the left and another to the right- [demo](https://jsfiddle.net/BlackLabel/nms9pgj5/).

**Comment by vitaliy-kretsul** [comment]
@karolkolodziej 
Thank you very much for your advice!
However this works fine only for very specific static use cases, like the one in demo provided (when there is only one series per one yAxis, containing only one column per each x value). For more complex (and especially dynamic) cases this will require some complex logics to calculate `pointPlacement` value, taking into account how many series there are per yAxis and how many columns there are per x value, and that some points might be empty or null,  and `pointWidth` value etc:
https://jsfiddle.net/Cortez/e1cgy059/
It will be hard to manage all this. Especially when data is loaded dynamically into chart and it is not possible to predict the exact data structure.
I think 'centerInCategory' option should center all columns, regardless of which yAxis they belong to. Or maybe have some additional option for that.

What do you think?
Thanks!

**Comment by karolkolodziej** [comment]
You are right! In the case of multiple dynamic series, it might be more difficult to calculate that shift value.

Altho the `centerInCategory` property was designed to handle null columns, it might also handle your case- multiple columns on different yAxes with possible null values.

**Comment by vitaliy-kretsul** [comment]
@karolkolodziej 
We ended our conversation on somewhat undefined point. So, what is the future perspective for this issue? Is it going to be implemented? Or is it under review? What influences this decision?
Thanks!

**Comment by vitaliy-kretsul** [comment]
@TorsteinHonsi 
Many thanks for your work!
I've checked fix provided and it seem to have some problems: https://jsfiddle.net/Cortez/Lxuyjgw0/
As you can see, I added one more series to primary yAxis and now columns are overlapping once again. So the fix doesn't seem to take into account additional series.

**Comment by TorsteinHonsi** [comment]
Ouch. We also see another problem with two series. If we hide Series 3, the February column is not centered: https://jsfiddle.net/highcharts/3hsg0kco/

**Comment by vitaliy-kretsul** [comment]
@TorsteinHonsi After our last messages no one opened this ticket again. So I guess that might be the reason why no one has looked into this issue since then.

**Comment by TorsteinHonsi** [comment]
Sorry for that @vitaliy-kretsul! I'll open it again.
