### ISSUE TITLE
Stacking areaspline charts break if x-axis values don't exactly align

### ISSUE THREAD

**Issue by SimonKernthaler** [highcharts/highcharts#17775]
#### Expected behaviour
Our product collects data samples as timeseries and allows our customers to display charts of the results. Due to the nature of polling external devices the sample times don't always align exactly.

If the customer chooses a stacking areaspline chart to show the data I expect the areas to appear on top of each other.

#### Actual behaviour

If the X-values don't align exactly then the chart rendering breaks. There is a hole in the lower area and the points from the upper series 'fall in' to the hole. 

#### Live demo with steps to reproduce
https://jsfiddle.net/skernthaler/mxf0sbcy/3/

The jsfiddle demonstrates this issue. There are two series displayed as a stacking areaspline chart. If either one of the series is displayed on its own then there is an unbroken area. If both series are displayed then Series 2 has a hole between 15:56 and 16:06. Series 1, instead of sitting on top of the area for Series 2 is shown above the axis and is missing between 16:01 and 16:06.

I raised this with the support team and they advised me to raise a ticket here.

#### Product version
Originally observed on Highcharts 10.1.10

#### Affected browser(s)
all

**Comment by karolkolodziej** [comment]
Thank you @SimonKernthaler for contacting us.

Stacks are created based on the `x` values and they have to match.
I'm not sure how the stacking should work in your case. Base od what it should be stacked?


As a workaround, you can consider using [dataGrouping](https://api.highcharts.com/highstock/series.line.dataGrouping) from the stock- [demo](https://jsfiddle.net/BlackLabel/7Lqk46xd/).

**Comment by SimonKernthaler** [comment]
Hi Karol,

Since it is a stacking area chart based on timeseries samples the expectation is that the areas stack, not just the individual samples.

The chart is continuous and there is a computed value for every possible x-value for Series 1 and for every x-value for Series 2. So I would expect the following:


  *   If I have series A made up of a number of samples joined to make an area I can show A(x) - this is how a single area chart appears. The data being represented are continuous and the points are just the samples that we have of that continuous series.
  *   If I then stack series B on top of series A described by B(x) I expect the values of B to appear at A(x) + B(x) for all values of x whether or not A has a sample at a given x.

I see that the dataGrouping does prevent the chart from breaking, although I am reluctant to change data, even for display purposes.
If a sample is taken at 15:02 it should really appear at 15:02, not 15:00. It may be sufficient for an interim fix though.

Simon

**Comment by karolkolodziej** [comment]
> If I have series A made up of a number of samples joined to make an area I can show A(x) - this is how a single area chart appears. The data being represented are continuous and the points are just the samples that we have of that continuous series.

This basic example is understood.

>  If I then stack series B on top of series A described by B(x) I expect the values of B to appear at A(x) + B(x) for all values of x whether or not A has a sample at a given x.

What if there is no A(x) and B(x) exists? I don't understand how it should be handled?

**Comment by SimonKernthaler** [comment]
When you plot a line chart from samples you are calculating a continuous value from discrete data points. The line is the nominal value of A(x) for all x, not just where the samples exist. Obviously when I choose the line smoothing algorithm I get different results, but that is accepted. So to calculate the line you already have a value for A for all x not just where the samples are.

So if :

  *   fa(x) is a continuous function derived from a set of samples A(x), and
  *   fb(x) is a continuous function derived from a set of samples B(x),
  *   when I display a stacked representation fab(x) I expect that to be the sum of the fa(x) and fb(x) continuous functions - so fab(x) = fa(x) + fb(x) for all x. Regardless of where the samples for A(x) and B(x) appear.
  *   I don't expect to be limited to a function derived from S(x) = A(x) + B(x) where the samples of A and B coincide in x.

So if I am stacking two continuous functions based on discrete data points I am expecting for the result to be the sum of the derived continuous functions rather than a function derived from the summed data points.
