### ISSUE TITLE
stackLabels bug

### ISSUE THREAD

**Issue by Yu-tsun** [highcharts/highcharts#17776]
#### Expected behaviour

both side has stackLabels

#### Actual behaviour

only right side has stackLabels

#### Live demo with steps to reproduce

https://jsfiddle.net/catleopard/295oz8t0/1/

#### Product version

Highcharts

#### Affected browser(s)

Chrome

**Comment by karolkolodziej** [comment]
Thank you @Yu-tsun for reporting this.

However, a similar issue has already been reported- https://github.com/highcharts/highcharts/issues/17116.
There is even a suggested fix for that issue.

Closing this as a duplicate.
