### ISSUE TITLE
hightcharts stock range navigator with date / cursor

### ISSUE THREAD

**Issue by maximedotair** [highcharts/highcharts#17786]
I would like to know if it is possible or complicated to add a focus cursor on a specific date inside the navigator area of a stock hightchart (see screenshots)

The idea is that the user can move the cursor in the limit of the zone and that we can display the month, the week, the date, or the precise hour on which the cursor is focused, and to set up an event with each movement of the cursor, modification of the current date 

Sincerely,
Maxime Ramos
![cursor-hightcharts](https://user-images.githubusercontent.com/827372/192485402-36939bc4-a9da-4895-9859-3ae464fd481c.png)

**Comment by karolkolodziej** [comment]
Hi @maximedotair!

Could you please elaborate and share steps/cases when the cursor (crosshair I presume) should be visible?

**Comment by maximedotair** [comment]
Hi @karolkolodziej 

I need to move the cursor to focus a state of my portfolio with precision at a specific date, the idea is to be able to have on the charts the data and flags according to the zoom linked to the navigator, but underneath I want to display complete information linked to a specific day, the one on which the cursor is focused 

here is a more complete example : 
underneath you can see the information of my portfolio linked to this specific date 

![2](https://user-images.githubusercontent.com/827372/192742309-f38e44d8-6035-4a78-b703-961ec01955f0.jpg)

**Comment by karolkolodziej** [comment]
Are we talking about this?
![image](https://user-images.githubusercontent.com/57004120/192991456-d91c4089-3159-4559-b59a-c26a2c91cd3c.png)

**Comment by maximedotair** [comment]
> Are we talking about this? ![image](https://user-images.githubusercontent.com/57004120/192991456-d91c4089-3159-4559-b59a-c26a2c91cd3c.png)

Yes ! this cursor

**Comment by karolkolodziej** [comment]
If I understood you correctly you can achieve it by adding some custom rendering mechanism on each point mouse over/out.

Demo: https://jsfiddle.net/BlackLabel/bmex0qrd/

**Comment by maximedotair** [comment]
Hello,
My idea is a little bit different, the red cursor is independent, and you can move it all along the period even outside the range, it allows to focus on a precise point of the graph period

here is an example : 

https://www.loom.com/share/354f0694855a4cad97a83618d235cfcf

I managed to do this by cheating with scss and react, it would be nice to be able to use it as a plugin or an element in addition, I think it can be used to focus on a date separately from the focus on the chart

**Comment by karolkolodziej** [comment]
I apologize for the misunderstanding! 

Thank you for the clarification 👍
