### ISSUE TITLE
ES6 module for ScatterSeries doesn't work

### ISSUE THREAD

**Issue by petterw03** [highcharts/highcharts#17780]
#### Expected behaviour

You should be able to import the ES6 module for ScatterSeries in the same way as a LineSeries.

#### Actual behaviour

When importing, you get the error `Uncaught TypeError: Class extends value undefined is not a constructor or null`.

#### Live demo with steps to reproduce
https://jsfiddle.net/tbyzgevu/

#### Product version
Highcharts 10.2.1

#### Affected browser(s)

Probably all

**Comment by karolkolodziej** [comment]
Hi! Thank you @petterw03 for contacting us.

The scatter series relies on series such as Line and Column thus you have to also import them in order to have a `scatter` series- [demo](https://jsfiddle.net/BlackLabel/9docnh32/).
