### ISSUE TITLE
Drag and drop feature in split packed bubble chart stopped working after update

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#17785]
After the **10.2.1** update, drag and drop functionality is no longer working in our demos for split packed bubble charts.

Last working version - **10.2.0**

#### Live demo with steps to reproduce
Click on any point and try to drag it
https://jsfiddle.net/BlackLabel/eo9xbcrk/

#### Product version
Highcharts 10.2.1
Highcharts More 10.2.1

**Comment by karolkolodziej** [comment]
Bisected to https://github.com/highcharts/highcharts/commit/31a08d3e13929046911ecb79c0c1c0fe91bb2a1c FYI @bre1470
