### ISSUE TITLE
How to add a column next to name inside the gantt chart

### ISSUE THREAD

**Issue by almas-786** [highcharts/highcharts#17788]
I need to have an add extra column at the same level where i need to show more information for user in Gantt chart.

Also facing 1000 only record cap for gantt chart i do have the license where should i apply that now.

**Comment by karolkolodziej** [comment]
Hi @almas-786 

Our GitHub channel is treated as a bug/feature tracking tool. For these kinds of questions, please get in touch with us via dedicated support channels, which you can find here: https://www.highcharts.com/blog/support/.

Our support engineers will be more than happy to help you if only you can provide them with more information about your use example.
