### ISSUE TITLE
Web server is returning an unknown error - error code 520

### ISSUE THREAD

**Issue by AmitSinhaSDG** [highcharts/highcharts#17783]
#### Expected behaviour
When exporting and image from a chart it should export the image if that chart.

#### Actual behaviour
When exporting and image from a chart takes me on the reported page.

We have an OEM license of HighChart too.

#### Product version
![520](https://user-images.githubusercontent.com/114430632/192442807-c184439e-c4a3-4618-8070-a7eb103c1509.png)

#### Affected browser(s)
Any

**Comment by karolkolodziej** [comment]
Hi @AmitSinhaSDG.

Could you please create an online demo with your config so we can test that on our own?

**Comment by karolkolodziej** [comment]
From what I can see, it looks like your data is too big.

In cases like this, we recommend using your own export server instead of `http://exporting.highcharts.com/`

Read more: https://www.highcharts.com/docs/export-module/setting-up-the-server
