### ISSUE TITLE
Gantt short task (e.g. 1 day task) not visible when total duration of timespan is long (e.g. 1,5 years)

### ISSUE THREAD

**Issue by nevalain** [highcharts/highcharts#17795]
#### Expected behaviour
Gantt short duration task (e.g. 1 day task) would be somewhat visible when zoomed out with navigator (e.g. hairline would remain visible)

#### Actual behaviour
Gantt short task (e.g. 1 day task) are not visible when zoomed out with navigator (e.g. hairline). Only empty 

This happens to us with 1 day events when showing 1,5 years of gantt so this is an issue when there are many remaining "empty rows".

I tried to use series.marker.enabled and series.marker.enabledThreshold, but did not get them to work.

Workaround would be to use milestones, but this would become complicated since durations, zoom levels and resolutions (widths) change.

#### Live demo with steps to reproduce
Here is a demo where Requirements should not be visible. (Adjust max: today.getTime() + (_**400**_ * day) if needed)
EDIT: It seems that when I resize the width of the fiddle's iframe the "Requirements" become visible when iframe is quite narrow. Pl. see attached pictures.

[https://jsfiddle.net/fabhg9zx/](https://jsfiddle.net/fabhg9zx/)

#### Product version
Highcharts v10.2.1

#### Affected browser(s)
Chrome
![2022-09-30 12_21_21-Subtasks - JSFiddle - Code Playground](https://user-images.githubusercontent.com/17066001/193238710-ffff3335-dfcd-4c68-8b6a-97d68971d41b.png)
![2022-09-30 12_22_02-Subtasks - JSFiddle - Code Playground](https://user-images.githubusercontent.com/17066001/193238742-4db13858-4b2d-42c4-9c8c-0ded70c3f4c1.png)

**Comment by karolkolodziej** [comment]
Hi @nevalain!

Could you please update your demo? This URL is pointing to something else.

**Comment by nevalain** [comment]
Hi @karolkolodziej 

Updated the link to the fiddle.

**Comment by nevalain** [comment]
Hi! 

The [minPointLength](https://api.highcharts.com/gantt/series.gantt.minPointLength) is solution to this problem.

Thanks!
