### ISSUE TITLE
Highchart Stock - Y Axis showLastLabel key's default value seems not `true`

### ISSUE THREAD

**Issue by dev-song** [highcharts/highcharts#17803]
#### Expected behaviour
As API documentation stated, the last label for Y Axis on Highcharts Stock should be displayed for default
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/52951039/193166818-05b25c75-480c-44c8-b49f-a0e6817e4f45.png">

#### Actual behaviour
The last label for Y Axis on Highcharts Stock is not displayed until assigning `true` value to `showLastLabel` key explicitly

#### Live demo with steps to reproduce
https://codesandbox.io/s/632wx6

#### Product version
Highcharts 10.2.1

#### Affected browser(s)
Google Chrome, Version 105.0.5195.125 (Official Build) (x86_64)

**Comment by karolkolodziej** [comment]
Thank you @dev-song for reporting that!

@pawelfus could you please tell me which should be a default for which axis?
