### ISSUE TITLE
Rename of term 'dummy' in code / css 

### ISSUE THREAD

**Issue by rivkier** [highcharts/highcharts#17801]
# Rename usage of term 'dummy' in code / css 
In recent years large organizations have updated naming conventions to incorporate cultural sensitivity in naming.  One example is github which has been migrating branch naming from 'master' to 'main'. https://sfconservancy.org/news/2020/jun/23/gitbranchname/

As part of a large organization, and licensed commercial user of highcharts, our tech team has been flagged recently by our release team which has started to do scans of our builds and content for use of offensive language.  The word 'dummy' has been flagged, and upon further investigation we discovered that it was coming from a class used by the highcharts accessibility component.  The request is to rename this term.

https://github.com/highcharts/highcharts/blob/5fe7292566c8a75de3cbd60b4c9e7b483582e8d1/ts/Accessibility/Components/SeriesComponent/SeriesDescriber.ts#L137

# Opt in flag
Considering that updating this classname may cause a breaking change to existing consumers, adding a configuration to explicitly opt in can also be considered.

**Comment by oysteinmoseng** [comment]
Hi @rivkier, thanks for bringing this to our attention. We will rename the relevant CSS classes.

**Comment by rivkier** [comment]
Thanks for fixing so quickly!

Any idea when we can see this in the next release?
