### ISSUE TITLE
xAxis.max is not working as expected

### ISSUE THREAD

**Issue by sathish151198** [highcharts/highcharts#17805]
#### Expected behaviour
Max number of Data series to be displayed in xaxis is determined using xAxis.max. For Eg: If we give xAxis.max as 3, maximum of 3 data series to be displayed.

#### Actual behaviour

If we give xAxis.max as 3, maximum of 4 data series is getting displayed. For xAxis.max to be 4, 5 data series is getting displayed.

#### Live demo with steps to reproduce

[Demo-link](https://jsfiddle.net/sathish1511/npstqLoc/)

#### Product version

Highcharts v9.1.2

#### Affected browser(s)
Version 106.0.5249.62 (Official Build) (64-bit)

**Comment by pawellysy** [comment]
@sathish151198, the max and min properties of the axis set, what are the axis boundaries, not the amount of data displayed.
https://jsfiddle.net/4Ldc0s1t/

For further support, please reach out to us via our available support channels, which are listed here: https://www.highcharts.com/blog/support/
Thanks!

**Comment by pawellysy** [comment]
not
