### ISSUE TITLE
Chart tooltip content is not proper visible after applying text spacing 

### ISSUE THREAD

**Issue by RubyZ10** [highcharts/highcharts#17811]
#### Expected behaviour
 After applying text spacing, chart tooltip content should be properly visible.

#### Actual behaviour
 After applying text spacing, chart tooltip content is not properly visible.

Normal screen
![image](https://user-images.githubusercontent.com/76190371/193346076-768f1ef5-4877-49be-8ba8-3d806e633def.png)

After applying text spacing
![image](https://user-images.githubusercontent.com/76190371/193346138-b9ff89b0-4a55-4e5d-a306-a1ec649afefd.png)

**Comment by pawellysy** [comment]
Hello @RubyZ10, thanks for reporting this issue!
Could you share the live demo, where the issue is reproduced?

**Comment by RubyZ10** [comment]
Hi @pawellysy thanks for taking a look at the issue, I cannot repro the bug any more. closing the issue. Thanks!
