### ISSUE TITLE
Styled mode line chart series className not applied to shared tooltip

### ISSUE THREAD

**Issue by fhoeben** [highcharts/highcharts#17815]
#### Expected behaviour
Given I have a line chart, in styled mode, with a shared tooltip
When I apply a className to my series
Then I expect that className to be applied to the tooltip element for that series
<img width="271" alt="Screenshot 2022-10-03 at 12 25 51" src="https://user-images.githubusercontent.com/5467859/193555898-2c922b3e-875a-4a89-87dd-8e00c73e0b9b.png">

#### Actual behaviour
The className specified is not added to the values for the series in the tooltip

#### Live demo with steps to reproduce
https://codepen.io/fhoeben/pen/WNJyeNQ

<img width="448" alt="Screenshot 2022-10-03 at 12 20 34" src="https://user-images.githubusercontent.com/5467859/193555211-c70a84f4-e507-457e-934c-07e72a0f72b1.png">

The line colours have been configured, these are applied to the labels but not to the tooltip. The tooltip elements do not have the `weight` or `bmi` class specified to their series
<img width="614" alt="Screenshot 2022-10-03 at 12 23 17" src="https://user-images.githubusercontent.com/5467859/193555405-77f7b08f-c208-4920-a5fb-d20c29cf7a0e.png">

#### Product version
 Highcharts JS v10.2.1 (2022-08-29)

#### Affected browser(s)
all

**Comment by karolkolodziej** [comment]
Hi @fhoeben!

I agree the class name and new colors should be reflected in the tooltip while using the `styledMode`.

As a workaround, you can use other CSS selectors to change those colors- [demo](https://jsfiddle.net/BlackLabel/cy90b1mp/).

Similar to: https://github.com/highcharts/highcharts/issues/17346

**Comment by TorsteinHonsi** [comment]
@fhoeben The safest *workaround* (and how coloring is intended to work), is to use the [colorIndex](https://api.highcharts.com/highcharts/series.line.colorIndex) option to handle your color-to-series mapping.
