### ISSUE TITLE
highcharts.d.ts doesn't provide type for `Highcharts.seriesTypes`

### ISSUE THREAD

**Issue by kaguya3222** [highcharts/highcharts#17816]
#### Expected behavior
highcharts.d.ts should provide type definition for `seriesTypes` field.

#### Actual behaviour
highcharts.d.ts doesn't provide type definition for `seriesTypes` field.

#### Live demo with steps to reproduce
[Demo](https://codesandbox.io/s/stupefied-driscoll-ng08i2?file=/src/index.ts)

#### Product version
Highcharts: 10.2.1

#### Affected browser(s)
All

**Comment by kaguya3222** [comment]
Also wanna provide a context and issues that I'm trying to solve. I want to change the legend marker that is being rendered for certain chart series (screenshot below)
![image](https://user-images.githubusercontent.com/55194394/193563824-e3ce7769-914d-4732-b191-0a99668b7656.png)


I found this answer: https://www.highcharts.com/forum/viewtopic.php?f=9&t=48943#p177498

The suggested solution is: `Highcharts.seriesTypes.line.prototype.drawLegendSymbol = Highcharts.seriesTypes.column.prototype.drawLegendSymbol;`

I use Typescript for my project and when I write this line:
`Highcharts.seriesTypes` i get an error.

**Comment by pawellysy** [comment]
Hello @kaguya3222, thanks for reporting this issue. 
The `seriesTypes` is an internal property, which is used inside a core. The example above is just a workaround.
@bre1470 What do you think?

**Comment by bre1470** [comment]
`Highcharts.seriesTypes` exists for backward compatibility and is deprecated. [`Highcharts.Series.types`](https://api.highcharts.com/class-reference/Highcharts.Series#.types) should be used instead.

We need to update demos to reflect this.

**Comment by bonniegrubbs** [comment]
For some reason I'm seeing `Property 'drawLegendSymbol' does not exist on type 'Series'` when trying to do use `Highcharts.Series.types` in the way mentioned above.

**Comment by karolkolodziej** [comment]
The `drawLegendSymbol` is a private method thus it won't be available on any interface. 
You can extend and add to the existing one to avoid TS errors.
