### ISSUE TITLE
General docs, Colors: not working demo

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#17821]
The first demo on this website isn't working with the newest version of Highcharts: https://www.highcharts.com/docs/chart-design-and-style/colors

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/zy1epj3o/

#### Product version
10.2.1

**Comment by karolkolodziej** [comment]
Working demo: https://jsfiddle.net/BlackLabel/8n3a60z9/

Maybe we should add this demo to our samples?
