### ISSUE TITLE
0 value labels in Line Chart on second y-axis is rendered outside of chart-plot-area

### ISSUE THREAD

**Issue by RageCrezz** [highcharts/highcharts#17829]
#### Expected behaviour
Expecting some space between the 0 labels and the legend on the top left corner.

#### Actual behaviour
The space between the legend and the chart's 0 labels does not appear.
![image](https://user-images.githubusercontent.com/14924264/194070383-570b6cf5-38c3-4e12-b9e0-a0849cf4c4e1.png)

It appears that this is happening due to the labels being rendered outside of the chart plot area. Thus it collides with other elements:
![image](https://user-images.githubusercontent.com/14924264/194072497-897bb99d-31bf-4602-a0fe-bc220a62e9d7.png)

#### Live demo with steps to reproduce
[JSFiddle Link](https://jsfiddle.net/q534w7a0/8/)

#### Product version
Highcharts ~9.2.0

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Thank you @RageCrezz for contacting us.

By default, the [crop](https://api.highcharts.com/highcharts/series.column.dataLabels.crop) property is set to true which moves the label inside the plot area and the spacing between title/subtitle is preserved- [demo](https://jsfiddle.net/BlackLabel/okj6u1v4/).

If you intentionally set crop to false, you have to compensate those margins on your own- [demo](https://jsfiddle.net/BlackLabel/urxfw3vd/).
