### ISSUE TITLE
column chart minPointWidth

### ISSUE THREAD

**Issue by KarmaBlackshaw** [highcharts/highcharts#17831]
# Description of the feature
Would it be viable to have a minPointWidth option? Currently there is only [pointWidth](https://api.highcharts.com/highcharts/plotOptions.column.pointWidth) and [maxPointWidth](https://api.highcharts.com/highcharts/plotOptions.column.maxPointWidth) option

# Library related to the feature
Highcharts Column

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by karolkolodziej** [comment]
Thank you @KarmaBlackshaw for sharing this idea.

Right now your point width is calculated as shown in the code snippet below.
You can control it by for example setting the [pointPadding](https://api.highcharts.com/highcharts/plotOptions.column.pointPadding) property.

https://github.com/highcharts/highcharts/blob/efe6f1bc19225e11c839ca14c2fb6bbd617f5d84/ts/Series/Column/ColumnSeries.ts#L685-L696

In the meantime, could you please describe a scenario where this might be useful?
