### ISSUE TITLE
Gantt chart: Connecting lines will not be fully deleted/redrawn on Drag'nDrop

### ISSUE THREAD

**Issue by aktiWeb** [highcharts/highcharts#17833]
#### Expected behaviour
All connecting lines will be redrawn after drag n' drop

#### Actual behaviour
If more than one connecting lines are defined, only the last defined line will be redrawn/removed on d&d. All other lines are still visible.
![grafik](https://user-images.githubusercontent.com/7749582/194280174-54282c8d-0682-49e2-b60c-fde35f07e1bd.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/dmt3fypL/9/

#### Product version
Highcharts Gantt JS v10.2.1 (2022-08-29)

#### Affected browser(s)
FF 102.3.0esr (64-Bit)
Chrome 102.0.5200.0
Edge 106.0.1370.34

**Comment by karolkolodziej** [comment]
Hi @aktiWeb!
Thank you for reporting that issue.

An obvious workaround would be using only one connector per point- [demo](https://jsfiddle.net/BlackLabel/3qmed7k2/).
