### ISSUE TITLE
Some Axis methods are not visible in docs for Axis Class

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#17847]
#### Expected behaviour
Since jsdoc is already created for methods like `addPlotLine`, `addPlotBand`, etc. in `PlotLineOrBandAxis.ts`, these methods should be visible in [API](https://api.highcharts.com/class-reference/Highcharts.Axis).

#### Product version
Highcharts v10.2.1 (latest)

**Comment by bre1470** [comment]
Thanks for the report. This requires some changes to the composition as these function should not be placed directly on the axis instance, but in a sub-instance like `Axis.plotter.addBand` and `Axis.plotter.addLine`.

**Comment by karolkolodziej** [comment]
Similar issue is reported here: https://github.com/highcharts/highcharts/issues/17052

**Comment by bre1470** [comment]
This has been fixed with #17052
