### ISSUE TITLE
When collapsed series will be hidden, the chart is buggy

### ISSUE THREAD

**Issue by Crizzly57** [highcharts/highcharts#17850]
#### Expected behaviour
Collapsed series should hide.

#### Actual behaviour
Series which should be hiden, will be remove/hidden. But the other series are then buggy.

#### Live demo with steps to reproduce
https://jsfiddle.net/fmgw2z35/20/

#### Product version
Highcharts JS 10.2.1

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hello @Crizzly57, thanks for reaching out to us!
I don't really understand what the problem is. Could you simplify a demo, and explain the reproduction steps more thoroughly, so that I could see exactly, what is the problem?
Thanks!

**Comment by Crizzly57** [comment]
Hi, 

here is a simplified demo. 
https://jsfiddle.net/p9w1nsde/11/

If you click the button, then the series one will be hidden. But then the series two gets buggy.
The reason for that is, that the series are collapsed.

**Comment by pawellysy** [comment]
@Crizzly57, Thanks for a great minimal demo. This is a bug.
There are some problems with the way, that the gridAxis handles the breaks and toggling. As a workaround, you can try updating the whole data, instead of changing visibility, because with the initial data, the chart is loaded correctly.
