### ISSUE TITLE
Horizontal scroll bar is hidden

### ISSUE THREAD

**Issue by sathish151198** [highcharts/highcharts#17857]
#### Expected behaviour
Horizontal Scroll bar should be displayed

#### Actual behaviour
Horizontal scroll bar is hidden

#### Live demo with steps to reproduce
[Live Demo](https://jsfiddle.net/sathish1511/0vhwcenm/26/)

#### Product version
Highcharts v9.1.2

#### Affected browser(s)
Version 106.0.5249.62 (Official Build) (64-bit)

**Comment by pawellysy** [comment]
Hi @sathish151198, thanks for contacting us with your question.

This is not a bug. The scrollbar is a part of the stock module. If you want to use it, you have to import it by including the script tag like in this example: https://jsfiddle.net/BlackLabel/0ea6t1mr/

Please, consider contacting us via our [available support channels](https://www.highcharts.com/blog/support/), where our support engineers are more than happy to help you with any problems.
