### ISSUE TITLE
Encountered intrinsic limit for series in wind barb gragh

### ISSUE THREAD

**Issue by manuelep** [highcharts/highcharts#17851]
#### Actual behaviour
It seams series with a length higher than 1000 are not supported

#### Live demo with steps to reproduce
Go to the [live example linked in documentazion](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/windbarb-series) and substitute the data definition as follows:

```js
data_length = 1000
const data = Array.from(Array(data_length).keys()).map(()=>[Math.random()*5, Math.floor(Math.random() * (360 - 0) + 0)])
```
if you use a `data_length` value of 1001 or higher you will get this error:

```
Uncaught TypeError: Cannot set properties of undefined (setting '0')
    at a.setData (highcharts.src.js:36738:41)
    at a.init (highcharts.src.js:36016:21)
    at d.init (windbarb.src.js:401:17)
    at a.initSeries (highcharts.src.js:30602:21)
    at highcharts.src.js:32271:21
    at Array.forEach (<anonymous>)
    at a.firstRender (highcharts.src.js:32268:17)
    at a.<anonymous> (highcharts.src.js:30580:21)
    at E (highcharts.src.js:1660:17)
    at a.init (highcharts.src.js:30445:17)
```

#### Affected browser(s)
at least Crome 106.0.5249.119 (Official build) (64 bit)

#### Adopted workaround waiting a better solution or the issue closing

```js
const random = (min, max) => Math.floor(Math.random() * (max - min)) + min;
const series_excess = data.length-1000;
if ( series_excess>0 ) {
    for (let i = 0; i < series_excess; i++) {
        data.splice(random(1, wind_data.length-1), 1)
    }
};
```

**Comment by pawellysy** [comment]
Thanks @manuelep for reporting this bug. 

`internal note`
This issue is connected to turboTreshold parsing the data in the wrong way. For windbarb there is no yData array defined. 
However, this amount of points for windbarb series is a bit of a corner case, because it is not readable.
 This issue probably exists for all series, which do not support values in [x, y] format, like networkgraph, sankey, etc. 

Workaround:
Set turboThreshold to Infinity: https://jsfiddle.net/BlackLabel/wnd7khg6/1/

**Comment by manuelep** [comment]
> Thanks @manuelep for reporting this bug.
> 
> `internal note` This issue is connected to turboTreshold parsing the data in the wrong way. For windbarb there is no yData array defined. However, this amount of points for windbarb series is a bit of a corner case, because it is not readable. This issue probably exists for all series, which do not support values in [x, y] format, like networkgraph, sankey, etc.
> 
> Workaround: Set turboThreshold to Infinity: https://jsfiddle.net/BlackLabel/wnd7khg6/1/

Thanks your workaround worked better ;-)
