### ISSUE TITLE
Link in HTML tooltip is wrongly encoded

### ISSUE THREAD

**Issue by brunouber** [highcharts/highcharts#17855]
I created a chart that uses HTML tooltip (`useHTML: true`), and renders a link within the tooltip.
The link's HREF is built dynamically depending on several factors, that I can't really control.
Eg. https://example.com/page?val1=a&not_val2=b

#### Expected behaviour

The link's HREF is rendered as `https://example.com/page?val1=a&not_val2=b`.

#### Actual behaviour

The link's HREF is rendered as `https://example.com/page?val1=a¬_val2=b`.

That is the substring `&not_val2` is rendered as `¬_val2`

#### Live demo with steps to reproduce

https://jsfiddle.net/brunour/jq4L2opu/10/

For some reason, that is not relevant to this issue, on jsfiddle I can't get the link to work (that is, to navigate on the URL when clicked), but you can see the HREF is wrong through the inspector, and the image below.

<img width="399" alt="image" src="https://user-images.githubusercontent.com/55399398/196198845-1b7554c6-79e4-499c-8fb0-247c92eaa451.png">

#### Product version

Highcharts 10.2.1 (latest) , 10.1.0.
Didn't test with others.

#### Affected browser(s)

Chrome, Firefox (likely all the others).

**Comment by raf18seb** [comment]
Hi @brunouber!

This is a general browser problem, not related to Highcharts.
See a similar question with an answer on StackOverflow: https://stackoverflow.com/questions/14761418/browser-mis-interpreting-not-in-url

> The link's HREF is built dynamically depending on several factors, that I can't really control.
You should be able to find a way to control it somehow, either when it's being sent or after you get it (parse string before feeding Highcharts with it).
