### ISSUE TITLE
Chart configured with **scrollablePlotArea**, on scroll does not show the tooltip for hovered point.

### ISSUE THREAD

**Issue by LearnGrowAndShare** [highcharts/highcharts#17860]
#### Expected behaviour
Chart configured with **scrollablePlotArea**, on scroll should show the tooltip for hovered point.

#### Actual behaviour
Chart configured with **scrollablePlotArea**, on scroll does not show the tooltip for hovered point.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea-vertical

Video - 
https://user-images.githubusercontent.com/12616063/196499321-f48aeb94-a777-4162-9160-ecfd7621ccff.mp4

Here in video, if we notice..
1. On hover on **Gantt chart**  shows the tooltip.
2. From 00:02 to 00:06, On scroll if mouse is moved the tooltip appears,
3. After 00:06, if mouse is not moved the tooltip is not shown.. In video at 00:10 hovered on **Venn Diagram** , notice the tooltip not shown..

In code, looks like we do see code to hide the non visible point ,
-> https://github.com/highcharts/highcharts/blob/master/ts/Core/Tooltip.ts#L1470 
-> https://github.com/highcharts/highcharts/blob/3d90559fb1bce70439245d199c32ac52e95ee33a/ts/Core/Chart/Chart.ts#L784

Is it  possible to override this, to enable showing tooltip for all the point? 

#### Product version

 Highcharts JS v10.2.1 (2022-08-29)

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi, thank you for reporting the issue.

Simplified demo: https://jsfiddle.net/BlackLabel/w4s7uyce/
When scrolling, the tooltip is shown every 2nd scroll.

It's related to [this ticket](https://github.com/highcharts/highcharts/issues/12416), possible duplicate. Fix from [this PR](https://github.com/highcharts/highcharts/pull/16002) fixes it.
@TorsteinHonsi could you take a look at the above PR?

**Comment by TorsteinHonsi** [comment]
Closing as duplicate, the fix for #16002 will handle this.
