### ISSUE TITLE
Accessibility issue : Voice Over + Firefox : Cursor is not able move out of Pie Chart by clicking CTRL + OPT + Left or Right Arrows

### ISSUE THREAD

**Issue by nestornorton** [highcharts/highcharts#17864]
#### Expected behaviour
User should able to move forward or backward by clicking ctrl + option  + arrow(left/right) in and out of pie chart reading.

#### Actual behaviour
Once user enters into pie chart reading, user is not able to move to the next element by clicking ctrl + option + (left/right) arrow buttons in Firefox.

#### Live demo with steps to reproduce

https://www.highcharts.com/demo/accessible-pie

#### Product version

Tested in 9.0.2 and Highcharts version in https://www.highcharts.com/demo/accessible-pie.

#### Affected browser(s)

Firefox. This issue does not exist using Voice Over in Chrome.

Firefox Video Demo: https://user-images.githubusercontent.com/21298390/196797954-b95d0e27-f720-4c0f-a11f-884c246158ab.mov
Chrome Video Demo: https://user-images.githubusercontent.com/21298390/196796636-c17d9eb2-7fc9-4beb-b774-3ddb2ba6ebdd.mov

**Comment by oysteinmoseng** [comment]
@nestornorton Hi, thanks for reporting. VoiceOver seems to struggle with Firefox when it comes to SVG accessibility. This is not an issue related to Highcharts, and can be reproduced with plain SVG examples as well. I am not sure if this is an issue with Firefox or with VoiceOver, though. Closing here for now, as there doesn't seem to be much we can do on our end.
