### ISSUE TITLE
stickyTracking: false

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#1786]
Example: http://jsfiddle.net/YCpcm/

Steps to reproduce:
1) Hover one of points
2) Hover another, close to first one, point (important - don't let your tooltip disappear!)
3) Move mouse away from points - tooltip is still visible and will work as with stickyTracking: true

**Comment by KacperMadej** [comment]
Unable to recreate in version 6.1.4.
Closing as resolved.
