### ISSUE TITLE
Setting zoomType in update broke in version 10.2.1

### ISSUE THREAD

**Issue by veloek** [highcharts/highcharts#17861]
#### Expected behaviour
The zoomType is updated and zoom is enabled.

#### Actual behaviour
The update doesn't seem to have any effect.

#### Live demo with steps to reproduce
https://jsfiddle.net/3b1eqpkw/

#### Product version
10.2.1

#### Affected browser(s)
All? Only tested in chromium based browsers.

I understand that zoomType is now deprecated in favor of zooming (and switching to that property is a workaround), but this is a regression nonetheless.

**Comment by raf18seb** [comment]
Hi @veloek, thank you for reporting the issue.

@hihajdus could you take a look at it?

**Comment by PadWorks** [comment]
@hihajdus I do not want to annoy, but would have to know approximately until when the problem is fixed?

**Comment by hihajdus** [comment]
Hi, 
It looks like the deprecated options do not get to the userOptions when options are updated.

For now, I throw a workaround with new options `chart.zooming.type`.
https://jsfiddle.net/BlackLabel/ryjwfm27/

**Comment by veloek** [comment]
@hihajdus Yes, that's basically what I wrote in the bug report. Any clue as to what broke in version 10.2.1?

**Comment by sahin52** [comment]
is zoomType only deprecated or completely removed? In Typescript, it is giving zoomType does not exist error. But it should not be missing, it is only deprecated
