### ISSUE TITLE
Highcharts boost mode does not render multiple series when calling setExtremes on load

### ISSUE THREAD

**Issue by alrahemtulla** [highcharts/highcharts#17863]
#### Expected behaviour
Restoring zoom state (setExtremes) on load should render boosted overlay scatter series on first load

#### Actual behaviour
Zoom state is applied, but series is not being rendered on first load.

#### Live demo with steps to reproduce
Call setExtremes on either axis while in load and use multiple series with boost mode. This works if there is only one series, but not multiple.
https://jsfiddle.net/Lgfc9o30/

This seems like a similar bug to:  https://github.com/highcharts/highcharts/issues/12554

#### Product version
Latest on https://code.highcharts.com/highcharts.js

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hello @alrahemtulla, thanks for reporting the bug!
`Internal note` might be an issue with cropping

**Comment by alrahemtulla** [comment]
Hey @pawellysy, are there any updates regarding this bug?
