### ISSUE TITLE
gauge chart label alignment overlaps some ticks

### ISSUE THREAD

**Issue by runfaj** [highcharts/highcharts#17869]
Copying most the info from here, which also has some additional details: https://www.highcharts.com/forum/viewtopic.php?f=9&t=49675

#### Problem

![image](https://user-images.githubusercontent.com/3292053/196985776-9172e41e-6946-4045-ad77-1b6efe0e1ad7.png)

You can see the ticks are overlapping. The distance attribute also doesn't help here at the moment because it is calculated based on radius rather than the actual axis line. It is almost like the radius for the chart and the radius for the axis are calculating from two completely different circle centers.

Repro: https://jsfiddle.net/0vdmba47/

#### Expected result

![image](https://user-images.githubusercontent.com/3292053/196986010-4fc2efcc-dbf1-4dcb-9730-de931f5520e4.png)

There is a slight work-around using an additional load event positioner mentioned in the linked article above, but since this axis alignment issue is not a problem for other chart types, I believe this is a bug. Thkat work-around also is very limited and doesn't work in a number of various scenarios.

#### Product version
highcharts 10.2.1

#### Affected browser(s)
any - mostly have tested via chrome latest

**Comment by runfaj** [comment]
Slight update after a lot of testing out various options and custom positioning. I found that setting label position and the event load _kind of_ works:
```
      events: {
        load() {
          const { yAxis } = this;
          const labels = Object.values(yAxis[0].ticks);
          const centerLabel = labels[Math.ceil(labels.length / 2) - 1].label;

          centerLabel.attr({ x: centerLabel.xy.x + 13 });
        },
      },

...

      align: null,
      distance: 26,
      x: -13,
```
However, you can see some labels align fine and others are still really wonky
<img width="725" alt="image" src="https://user-images.githubusercontent.com/3292053/197040712-ff08ebbc-9a4f-4ecd-86ae-677e4b4c12c4.png">

This becomes especially apparent when you've got longer labels present
<img width="749" alt="image" src="https://user-images.githubusercontent.com/3292053/197040847-a6b0f031-51d2-48cf-870b-415c4819db6d.png">

However, some labels even completely disappear when you've got certain scenarios:
<img width="736" alt="image" src="https://user-images.githubusercontent.com/3292053/197040956-48848b0e-50f8-4f17-9b08-d329422ae63f.png">

In this example, the max is 12000, the min is 2, and the data value is 5000. For some reason, highcharts just completely gets rid of the low label. Here's a fiddle where it even hides the two end labels for some reason. https://jsfiddle.net/kj6evhpu/

**Comment by karolkolodziej** [comment]
Hi @runfaj!

Indeed the workaround might not work correctly with responsive design and some other cases but for now, for this specific use case, it looks like a valid solution.

Internal note:
The `gauge` series should be considered as another series to implement the auto-alignment- see: https://github.com/highcharts/highcharts/pull/16853

**Comment by runfaj** [comment]
@karolkolodziej Yes, unfortunately our use case for charts involves highly dynamic data and sizing for our users, so a one-off case doesn't work. I'm eager to find a solution (you can probably tell by my multiple comments above 😅 ) because we are migrating from amcharts to highcharts and this is one of the blockers preventing any release. Let me know if there's any additional details I can provide or help with!

**Comment by karolkolodziej** [comment]
How about aligning axis labels through API `align: 'left'` and then for each quarter moving them in the load event?
You can replace the hardcoded `100` in that condition with something more meaningful in case of dynamic data.

Demo: https://jsfiddle.net/BlackLabel/1s4q9Loh/

**Comment by runfaj** [comment]
@karolkolodziej I think that will work - nearly! I modified a bit to account for the center label and bigger ranges of values. However, I found one scenario where the center label just disappears: https://jsfiddle.net/runfaj/cnxh5u42/3/. Any ideas on how to prevent that?

**Comment by karolkolodziej** [comment]
Initially, (before all these translations) labels are too wide and they simply overlap each other.
In order to disable that please set the `allowOverlap` to true- [demo](https://jsfiddle.net/BlackLabel/j0zusrbL/).

**Comment by runfaj** [comment]
Ah, figured it was something simple - this solution will work! Thanks for your help walking through this. I'm hoping sometime in the future, this functionality will be baked into highcharts positioning, but at least a workaround is present now!
