### ISSUE TITLE
Add the flags/arrow to different series

### ISSUE THREAD

**Issue by YanSatsuk** [highcharts/highcharts#17879]
# Description of the feature
Hi. Right now we can't add the flags/arrows annotations to different series. The flag/arrow is added only for one series doesn't matter where we clicked on the chart area. Please add the ability to add the flags/arrows to any series on the same y axis.
![image](https://user-images.githubusercontent.com/5408782/197531011-3cf5d97f-94eb-41e6-9e14-1cec453707c1.png)
https://jsfiddle.net/4dr1eaxm/

# Library related to the feature
Highcharts / Highcharts Stock / Annotations

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by karolkolodziej** [comment]
Hi @YanSatsuk!
Thank you for sharing this idea!
