### ISSUE TITLE
Exporting datagrouping data

### ISSUE THREAD

**Issue by Noppey** [highcharts/highcharts#17874]
# Description of the feature
Exporting to csv will always result in an export of the raw data. It would be great to provide a boolean option that would allow to export the visible (grouped) data.

# Library related to the feature
Highcharts Stock

**Comment by Noppey** [comment]
Any indication if this will be implemented?

**Comment by pawellysy** [comment]
Hi @Noppey, this issue is going through its normal route of privatization. Currently, we are waiting for more " 👍 " reactions, as an indicator, that this feature is popular, and then it might be added to our backlog. There is a low priority for this ticket at the moment.
