### ISSUE TITLE
Updating cursor though plotOptions does not update each series

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#17878]
#### Expected behaviour
When updating the series `cursor` through the `plotOptions` each series should have that property as it is with `color`.

#### Actual behaviour
When updating the series `cursor` through the `plotOptions` only the first series has updated cursor.
This is not the case when you have column and line but is when having column and scatter.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/qofx0uhg/

#### Product version
Highcharts JS v10.2.1 (2022-08-29)

#### Affected browser(s)
All

**Comment by Noppey** [comment]
Is there any indication when this bug is going to be resolved? It's quite an annoying bug in our application as it's unclear to customers when they can click through to zoom in.

**Comment by MarkusBarstad** [comment]
Hey @Noppey apologies for not having solved this yet! 

I will get someone with more experience to look into it, for the time being there is a (somewhat laborious) workaround you can use, at least going by the fiddle you posted. It involves simply recreating the series which does not accurately receives the updated cursor with the same desired settings as the old, but after updating `plotOptions`: https://jsfiddle.net/mkb93/3tgk7Lcs/

_Internal note:_
Logging each series shows that they do indeed receive the cursor-options, but the style-attribute of the series' HTML-objects shows that only one of them receives the cursor-style. The initial setting of the cursor works for both series, it is when it is already set that the bug occurs (which can be seen by removing the initial settings of `plotOptions` in the OP fiddle)

**Comment by Noppey** [comment]
I understand the workaround, but I don't like the additional complexity in our usecase (not the jsfiddle).
Is it possible to get the bug assigned to someone who has the ability to solve it?

**Comment by TorsteinHonsi** [comment]
Thank you for your patience @Noppey !

Until the next maintenance is released, there's a more modular drop-in workaround you can use, instead of rewriting your logic. Then after release this can be removed (or not):

```js
// Drop-in workaround for #17878
Highcharts.addEvent(Highcharts.seriesTypes.column, 'afterUpdate', function(options) {
    if (this.options.cursor) {
        this.trackerGroups.forEach(key => {
            if (this[key]) {
                this[key].attr({
                    'style': `cursor: ${this.options.cursor}`
                });
            }
        });
    }
});
```

View it [live on jsFiddle](https://jsfiddle.net/highcharts/ozax2Lk8/).
```

**Comment by karolkolodziej** [comment]
From what I can see ([demo](https://jsfiddle.net/BlackLabel/g0L75xjb/)), it works exactly the same in stock.

**Comment by Noppey** [comment]
My typescript compiler complained that seriesTypes was not a property. But the javascript works as you've mentioned:

```
Highcharts.addEvent((Highcharts as any).seriesTypes.column, 'afterUpdate', function (options) {
    if (this.options.cursor) {
        this.trackerGroups.forEach(key => {
            if (this[key]) {
                this[key].attr({
                    'style': `cursor: ${this.options.cursor}`
                });
            }
        });
    }
});
```

**Comment by karolkolodziej** [comment]
The `seriesTypes` is an internal property thus TS complains.
