### ISSUE TITLE
Timeline Supports Custom X plots

### ISSUE THREAD

**Issue by igniscyan** [highcharts/highcharts#17871]
# Description of the feature
Auto-format timeline to support any linear X value. Should be able to provide any numerical X values to the data array, and have plots autofit line to scaled width. 

# Library related to the feature
HighCharts

# Related requests?
No duplicates

**Comment by pawellysy** [comment]
Hello @igniscyan, thanks for your input!
I don't really understand what kind of linear X Value you have in mind. could you provide some screenshots, or a demo, where you could describe the input that you would like to provide as well as the desired output, that is plotted on the chart? Thanks!

**Comment by igniscyan** [comment]
> Hello @igniscyan, thanks for your input! I don't really understand what kind of linear X Value you have in mind. could you provide some screenshots, or a demo, where you could describe the input that you would like to provide as well as the desired output, that is plotted on the chart? Thanks!

Thanks for the reply! For my team's use case, we're trying to plot video timestamps on a timeline rather than something in datetime format. Ideally, example input would be time in seconds, IE: 

```javascript
    data: [{
    x: 30
    name: 'Event occurs for 60 seconds',
    label: 'etc',
    description: 'etc'
}, {
    x: 90,
    name: 'End 60 second event',
    label: 'etc',
    description: 'etc'
}]
```


The output on the chart would be the time presented in minute:second format on the X-axis, so 0:30 and 1:30 respectively for the two data points above. 

Let me know if this still needs some more clarification!

**Comment by pawellysy** [comment]
Hi again!
This is our timeline chart: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series-timeline/datetime-axis


So from what I understand, you want the same chart, but with different time formatting? If so, you just need to use one of our formatter functions/properties like in the following demo: https://jsfiddle.net/BlackLabel/two36c4L/

Here is the API reference to the time object: https://api.highcharts.com/class-reference/Highcharts.Time#dateFormat
Is this what you had in mind?

**Comment by igniscyan** [comment]
@pawellysy Thank you so much! This is exactly I was looking for, and it appears I was picking at the wrong set of docs when trying to figure this out. 

The last follow-up question I have, is it possible to group/bar x axis points? For example, if I wanted to plot a range rather than an individual minute/second time.

Ex.) data[1] takes place from 1:15-1:25. 

I'm not seeing this anywhere mentioned in the timeline series docs

**Comment by pawellysy** [comment]
Well, the timeline series focuses on visualizing the moments in time as points, not time intervals. To have a workaround you can use the plotBand with label like in the example below, or use different series type e.g. [X-Range](https://www.highcharts.com/demo/x-range)
https://jsfiddle.net/BlackLabel/two36c4L/1/
https://api.highcharts.com/highcharts/xAxis.plotBands.label

For the record: We use GitHub as a bug/feature tracking tool. For questions like this, please reach out to us via our [available support channels](https://www.highcharts.com/blog/support/), where our support engineers are more than happy to help you with tweaking the chart's configuration to your need.
