### ISSUE TITLE
PlotLine labels do not appear when using align right with textAlign left

### ISSUE THREAD

**Issue by Techn1x** [highcharts/highcharts#17888]
#### Expected behaviour
PlotLine label text is in DOM
PlotLine label appears to the right of the chart

#### Actual behaviour

PlotLine label text is not in DOM
PlotLine label is not appearing anywhere

#### Live demo with steps to reproduce
* Add a y-axis plotline label, with `align: 'right'` and `textAlign: 'left'`
* plotline label does not appear
* will appear if you set `useHTML: true`, or use a different the textAlign value

Demo with a working plotline label, and a missing plotline label
https://jsfiddle.net/br8ag2np/

#### Product version
Highcharts 10.2.1

**Comment by karolkolodziej** [comment]
Hi @Techn1x and thank you for reporting that!

_Internal note:_
This issue was introduced in the 9.2.0 by this PR: https://github.com/highcharts/highcharts/pull/15837

_Workaround:_
I prepared a small workaround that calculates the min width of the label- [demo](https://jsfiddle.net/BlackLabel/cL4hm593/).

**Comment by Techn1x** [comment]
Thanks for the workaround! The other workaround is `useHTML: true` but only if the text being used is known safe, which may not be the case for everybody

**Comment by karolkolodziej** [comment]
A better workaround that calculates the exact width of the label- [demo](https://jsfiddle.net/BlackLabel/xj65rmnt/).

**Comment by Techn1x** [comment]
Thanks! For anyone ending up on this thread, the fix was included in Highcharts 10.3.3
