### ISSUE TITLE
When inverting a chart, the marker symbol is rotated

### ISSUE THREAD

**Issue by htveit** [highcharts/highcharts#17880]
#### Expected behaviour
When inverting a chart, the marker symbol is not rotated

#### Actual behaviour
When inverting a chart, the marker symbol is not rotated

#### Live demo with steps to reproduce
The following example shows the problem. Notice that the legend shows the triangle up icon, whereas the chart itself shows the triangle rotated 90 degrees. 

https://codepen.io/htveit/pen/oNyvKqX

#### Product version
Highcharts latest (v 10.2.1)

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hello @htveit, thanks for reporting this issue!
Here is workaround: https://jsfiddle.net/BlackLabel/9b1p5vkn/326/

**Comment by kluvin** [comment]
Hi,

I don't know what legend.rotation does, nor is it [documented](https://api.highcharts.com/highcharts/legend). So we safely removed that.

`legend.legendSymbol` has also been moved to `legend.legendItem.symbol`

With these modifications in place the workaround has the desired effect, thanks!
