### ISSUE TITLE
XAxis Labels are overlapping inside the visual

### ISSUE THREAD

**Issue by sathish151198** [highcharts/highcharts#17889]
#### Expected behaviour
XAxis labels should not overlap inside the visual when the chart is inverted and xAxis label rotation is -180 in Waterfall Chart.

#### Actual behaviour
XAxis Labels are overlapping inside the visual

#### Live demo with steps to reproduce

[Demo link](https://jsfiddle.net/sathish1511/z7oa5dmq/15/)

#### Product version
Highcharts v9.1.2
#### Affected browser(s)
Version 106.0.5249.62 (Official Build) (64-bit)

**Comment by karolkolodziej** [comment]
Hi @sathish151198 and thank you for contacting us!

I am not sure if this should be classified as a bug because it looks like an edge case that could be easily worked around.
You can do that by simply setting the negative `x` value for the axis labels- [demo](https://jsfiddle.net/BlackLabel/vcfhqyrj/).

**Comment by sathish151198** [comment]
> Hi @sathish151198 and thank you for contacting us!
> 
> I am not sure if this should be classified as a bug because it looks like an edge case that could be easily worked around. You can do that by simply setting the negative `x` value for the axis labels- [demo](https://jsfiddle.net/BlackLabel/vcfhqyrj/).

Hi @karolkolodziej , Thanks a lot for your suggestion. I tried in our visual and it works fine, expect when we change the axis label density to "First and Last".[Demo link for First N Last overlap issue](https://jsfiddle.net/sathish1511/qLtk7gj1/7/).

Please suggest your thoughts on how we can handle this edge case.

**Comment by karolkolodziej** [comment]
Please set the label `aling: 'left'` and add a margin to the chart in order to prepare space for those labels- [demo](https://jsfiddle.net/BlackLabel/o3ybLxf4/).

**Comment by sathish151198** [comment]
> Please set the label `aling: 'left'` and add a margin to the chart in order to prepare space for those labels- [demo](https://jsfiddle.net/BlackLabel/o3ybLxf4/).

Thanks @karolkolodziej !!
