### ISSUE TITLE
Stockchart show's wrong date, when displaying more than round about 1773 points per line

### ISSUE THREAD

**Issue by checkmaldierethorik** [highcharts/highcharts#17898]
#### Expected behaviour
First date in the chart is the 2007-05-02, when showing "All"
Date-Filter (.highcharts-label highcharts-range-input) goes from May 2, 2007 to Oct 20, 2022

#### Actual behaviour
First date in the chart is the 2007-04-30, when showing "All"
Date-Filter (.highcharts-label highcharts-range-input) goes from Apr 30, 2007 to Oct 20, 2022

but the first timestamp given is 1178056800000 (GMT: Tuesday, 1. May 2007 22:00:00)

#### Hint
after applying a filter via the navigator, in order to show less point (e.g. start until middle of 2008), the date shown via Tooltip is correct again (Tusesday, May 1, 22:00). The Date-Filter still shows "Apr 30, 2007"

Overall i want to draw to lines of data with each 3899 dates

#### Live demo with steps to reproduce
https://dev.softwerft.com/softwerft/highchartstest/

#### Product version
10.2.1

#### Affected browser(s)
Chrome, Firefox, other not tested

**Comment by pawellysy** [comment]
Hello @checkmaldierethorik, thanks for reaching out to us. I don't really understand what is the issue here. You provide the data, and the first point is shown incorrectly, is that right? When investigating the chart, you provided, I can't see anything wrong there. Could you share your configuration in the jsfiddle, where I can see exactly what the data is, and how did you configure the chart? Here is the basic config, where you can start: https://jsfiddle.net/BlackLabel/bwgno6jh/31/

Thanks!

**Comment by pawellysy** [comment]
Closing - no reproduction steps

**Comment by checkmaldierethorik** [comment]
I found a workaround to fix my problem, also i am not sure anymore, if it is an actual problem, or related to the given data, what does not have dates and values for each and every single day of the past few years. In addition it only happened, when using `type: 'ytd'` for a button in the "rangeSelector"-section.

Before rendering the chart, the first day of the current selection (for example first day of this year) is being calculated.
Afterwards an offset between the first given date (greater or equal than mentioned day) and the previously given date of series gets calculated and used for the attribute "offsetMin" of the button `type: 'ytd'`.


```
let offsetYTD = 0;
const currentYear = new Date().getFullYear();
const firstdayofthisyear = parseInt(new Date(currentYear, 0, 1)/1);
let found = 0;
for(var i = 0; i<LineChart.length;i++)
{
		if(LineChart[i][0]>=firstdayofthisyear)
                {
		        found = i;
			break;
		}
}
if(found > 1){
   const daybefore = new Date(LineChart[found-1][0]);
   offsetYTD = LineChart[found][0] - LineChart[found-1][0];
   let offsetYTDinDays = offsetYTD / 3600 / 1000 / 24;
   var c = 0;
   for(var iter = 0; iter <offsetYTDinDays; iter++)
   {
       var myday = (daybefore.getDay()+iter) % 7 ;
       if(myday == 0 || myday == 6)
       {
	    c++;
       }	
   }
  var onedayless = 24 * 3600 * 1000;
  var diff = onedayless * c;
  offsetYTD = (offsetYTD - diff) * -1;
						
}
```
