### ISSUE TITLE
X-Range Series with multiple bars partially overlapping show tooltip of 1 bar only

### ISSUE THREAD

**Issue by 9mdaniel** [highcharts/highcharts#17894]
Hi Support Team,

I am trying to get partially overlapping xRange bars tooltip to show bar specific information on hover:

#### Expected behaviour
I have 3 horizontal bars with the same width. Hover on one of the Xrange bar, the tooltip should display correct information(bar color, etc) specific to the bar hovered on.
Also all bars should have a different/unique colors.

#### Actual behaviour
Hovering on any 1 of the bars, the tooltip just show information for only 1 bar e.g. 1 color - blue
In the fiddle 2 bars show in blue color and 1 in pink

#### Live demo with steps to reproduce
https://jsfiddle.net/L4vuzsth/26/

#### Product version
Latest

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hi @9mdaniel, thanks for contacting us with your question.
Our GitHub channel is treated as a bug/feature tracking tool. For these kinds of questions, please get in touch with us via dedicated support channels, which you can find here: https://www.highcharts.com/blog/support/.

Our support engineers will be more than happy to help you, to tweak the chart's configuration too much your needs.
Thanks for understanding!
