### ISSUE TITLE
Datalabels in bar graph gets clipped 

### ISSUE THREAD

**Issue by poonammimani** [highcharts/highcharts#1789]
Hi,
Please take a look at this fiddle - http://jsfiddle.net/poonamd/2zNmE/

The datalabel for Sept with value 235.4 gets clipped on the right side. The issue gets fixed if the chart size is increased in width.
I have also attached a screen shot which shows the clipping in red.
![untitled](https://f.cloud.github.com/assets/3950949/448639/54644482-b253-11e2-8a6b-43e13d7377bd.png)

Is there a way I can fix this?

**Comment by pawelfus** [comment]
Solved by the commit above.
