### ISSUE TITLE
Timeline series does not work correctly with stock chart.

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#17890]
#### Expected behaviour
Show the timeline series without errors.

#### Actual behaviour
When using `stockChart` constructor to create a `timeline` series there is an error in the console.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/g1nv24or/

#### Product version
Broken since v9.2.0 hover I was not able to bisect 

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
_Internal note:_

From what I can see disabling the `ordinal` serves as a workaround.
It looks like some methods and values are missing from the `fakeSeries` object: 
https://github.com/highcharts/highcharts/blob/8f64136eb0bc699784ca41df2ac2105230591b76/ts/Core/Axis/OrdinalAxis.ts#L1263-L1270

____

After adding this to the `fakeSeries`:
```TS
getVisibilityMap: Series.types.timeline.prototype.getVisibilityMap,
data: series.data,
yData: series.yData
```
it works flawlessly but I'm not sure if we should extend that object with so many unrelated methods/properties.

_____
What do you think @pawelfus? 
Should we add that or create some more robust solution for other series that might have similar issues?

**Comment by pawelfus** [comment]
I'm fine with just adding missing properties. Perhaps the test is wrong: shall we create a chart with all possible series types (from `H.seriesTypes` registry) and see if any of them raises an error? Then, we could add all the missing props and rely on this test in the future (no more regressions).

An alternative could be we create fakeSeries from a copy of a series of a specific type (`series = new seriesTypes[type]()`), not just a plain object (`series = { ... }`). With this solution, my only concern is performance though.

I'm open to any other solutions, so we don't have to maintain this every once in a while.

**Comment by pawelfus** [comment]
Unstale

**Comment by pawelfus** [comment]
Let's fix it, by just adding missing props
