### ISSUE TITLE
Build the Highcharts Server application for Java -- font installation

### ISSUE THREAD

**Issue by aravinuthala** [highcharts/highcharts#1790]
In the installation for export server in java it is not clear on how to install the fonts. 

Remember to install necessary fonts on the server. Install them on the server, The application will pick them up after installation.

Can you please elaborate on this. Where should be the fonts installed ? In the tomcat server? if not in what location? 

thanks,

**Comment by KacperMadej** [comment]
Moved to correct repository - https://github.com/highcharts/highcharts-export-server/issues/55
