### ISSUE TITLE
What happen with dist repo, she is clean

### ISSUE THREAD

**Issue by melrose13-69** [highcharts/highcharts#17904]
https://github.com/highcharts/highcharts-dist

Dist repo was cleaned

**Comment by TorsteinHonsi** [comment]
Thanks for notifying, I will investigate

**Comment by TorsteinHonsi** [comment]
It goes back to https://github.com/highcharts/highcharts/commit/7196c1dfcb1cb58f809721ea7d8418fe4e4ca235 . Fix coming up ASAP.

**Comment by TorsteinHonsi** [comment]
Okay, we're rolling again https://www.npmjs.com/package/highcharts 😅

**Comment by kamil-musialowski** [comment]
@TorsteinHonsi Could you also checking the bower package? Seems that the latest one is still empty.

**Comment by TorsteinHonsi** [comment]
@kamil-musialowski Fixed now. Apparently the latest tag from the `highcharts-dist` repo was not pushed to GitHub.

**Comment by NielsHolt** [comment]
Hi @kamil-musialowski and @TorsteinHonsi 

Thanks - it is working as expected :-)
