### ISSUE TITLE
StackLabels formatter in stacked waterfall chart

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#17902]
Formatter should have correct properties values. At this moment, it is not possible to create a simple, conditional formatter like `this.x === 3`, since console logging the `x` values throws only 0.

#### Live demo with steps to reproduce
Open up the console and see `this.x` values.
https://jsfiddle.net/BlackLabel/p8u6be1a/

#### Product version
Highcharts + Highcharts More 10.2.1 (latest)

**Comment by karolkolodziej** [comment]
Thank you @kamil-musialowski for reporting that issue.

_Internal note:_
While creating the `dummyStackItem` 4th argument (which is `x` value), is set to zero.
https://github.com/highcharts/highcharts/blob/503f93db91f2047f7182cde5b467319f0e343d69/ts/Core/Axis/WaterfallAxis.ts#L140-L146

It should be changed to something meaningful later inisde the `objectEach` where it can be extracted probably as `key`:
```TS
            // Render each waterfall stack total
            objectEach(waterfallStacks, function (type): void {
                objectEach(type, function (
                    stackItem: StacksItemObject,
                    key: string
                ): void {
                    dummyStackItem.total = stackItem.stackTotal;
                    dummyStackItem.x = +key;
```

**Comment by pawellysy** [comment]
Not that simple @karolkolodziej 😅, requires further debugging because the dummyStackItem is created outside the loop. I will remove the `good for beginners` tag.
