### ISSUE TITLE
Gantt Highcharts incorrect headers value on edge dates.

### ISSUE THREAD

**Issue by Xavier9922** [highcharts/highcharts#17906]
#### Expected behaviour
Navigation in Gantt Highcharts must provide a correct title for the X axis all the time. If a long or short period is selected by user the parent year/month or week must be available all the time 

#### Actual behaviour
When a date very close of its final period (week, month or year) is selected, headers not always show the correct value.
Case one: June 26, 2018 to Dec 25, 2018
![image](https://user-images.githubusercontent.com/31014611/199125527-4aa3d781-a7e4-4a3e-be5d-2484552c1945.png)
Case two: Dec 20, 2018 to Dec 25, 2018
![image](https://user-images.githubusercontent.com/31014611/199125729-de4aa307-1b7f-4f12-ae22-884cf62059aa.png)

#### Live demo with steps to reproduce
1) Go to Highcharts with navigation https://www.highcharts.com/demo/gantt/with-navigation 
2) On the date filter selector use (a) June 26, 2018 to Dec 25, 2018 and (b) Dec 20, 2018 to Dec 25, 2018

#### Product version
Highcharts v10.3.X

#### Affected browser(s)
Chrome, Firefox, Edge

**Comment by karolkolodziej** [comment]
Thank you @Xavier9922 for reporting this.

Internal note: 
Might be related to https://github.com/highcharts/highcharts/issues/11899
