### ISSUE TITLE
String literal option types loosened in 10.3.0

### ISSUE THREAD

**Issue by benelliott** [highcharts/highcharts#17919]
#### Expected behaviour

A lot of string literal types in the TypeScript typings as at 10.2.1, like `stacking?: OptionsStackingValue;` or `step?: OptionsStepValue;` have been widened to `string` as of 10.3.0. This is a regression that reduces compile-time type safety, since invalid configs like `step: 'foo'` will no longer throw a compile time error.

#### Actual behaviour

Types should be as narrow as possible to maximise type safety.

#### Live demo with steps to reproduce

N/A

#### Product version

Broken in highcharts.d.ts @ 10.3.0/10.3.1/master (see https://github.com/highcharts/highcharts-dist/blob/master/highcharts.d.ts);
previously working in highcharts.d.ts @ 10.2.1 and below (see https://github.com/highcharts/highcharts-dist/blob/v10.2.1/highcharts.d.ts) 

#### Affected browser(s)

N/A

**Comment by karolkolodziej** [comment]
Thank you @benelliott for reporting that!

@bre1470 could you please investigate that?
The definitions are correct in the options:
https://github.com/highcharts/highcharts/blob/503f93db91f2047f7182cde5b467319f0e343d69/ts/Core/Axis/Stacking/StackingOptions.d.ts#L43
