### ISSUE TITLE
Global chart styles overwritten by defaults

### ISSUE THREAD

**Issue by KamilKubik** [highcharts/highcharts#17917]
#### Expected behaviour
Defined global chart style `fontSize` shouldn't be overwritten by a default value (all text elements).

#### Actual behaviour
Defined global chart style `fontSize` is overwritten by a default value (all text elements).

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/odm53zwt/

#### Product version
Highcharts v10.3.1

#### Workaround
Added defined `fontSize` property into condition (Changed line 7).
https://jsfiddle.net/BlackLabel/c9spjtfr/

**Comment by karolkolodziej** [comment]
Thank you!

From what I can see this extension of `applyDescription` is sufficient and all other text elements are correct- [demo](https://jsfiddle.net/BlackLabel/nsobft4p/).

Internal note:
Each of these elements (title, subtitle, axes, legend) should be included in the test that needs to be added to the fix.

**Comment by TorsteinHonsi** [comment]
I don't think we should treat it as a bug... We see the same in the legend, the tooltip, the axis label, the data labels. The point is that these elements have their own `fontSize` set. 

Furthermore, the same relationship applies to other CSS properties that have more specific settings per type of element, for example `color` : https://jsfiddle.net/highcharts/1yae46m3/
