### ISSUE TITLE
Tooltip doesn't display on nodes from version 10.3.0

### ISSUE THREAD

**Issue by KamilKubik** [highcharts/highcharts#17926]
#### Expected behaviour
The tooltip should display on hovering the nodes.

#### Actual behaviour
The tooltip doesn't display on hovering the nodes (broken sankey module).

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/hfgmkxqo/

#### Product version
v10.3.0+

**Comment by karolkolodziej** [comment]
Bisected to https://github.com/highcharts/highcharts/commit/2a332890a7ba53737caa9b7dbc3271a3782fe78f
FYI @pawellysy
