### ISSUE TITLE
Tooltip sometimes not shown for highlighted point in scatter plot - 10.3.1

### ISSUE THREAD

**Issue by el-davo** [highcharts/highcharts#17929]
#### Expected behaviour

Tooltip should always show for the highlighted point in scatter plot

#### Actual behaviour

Sometimes the tooltip is not shown for the highlighted point in scatter plot

#### Live demo with steps to reproduce
https://stackblitz.com/edit/angular-12-highcharts-znufna?file=src/app/app.component.ts

To reproduce move your mouse from point to point, notice that sometimes the highlighted point will result in no tooltip shown

![screen](https://user-images.githubusercontent.com/11195158/199698781-f6b60264-7a25-4b8f-ba77-af077db1ac36.gif)

#### Product version
Highcharts 10.3.1

*Note* this worked fine on version 9.1.1

#### Affected browser(s)
Chrome Version 107.0.5304.88
Firefox 106.0.3 (64-bit)

**Comment by karolkolodziej** [comment]
Thank you @el-davo for reporting the issue.

From what I can see, this behavior starts from v9.1.0 but I was unable to bisect to a specific commit.

As a workaround, you can decrease the hideDelay time so that the tooltip is rerendered on each point hover- [demo](https://jsfiddle.net/BlackLabel/d3p4shcL/).

**Comment by el-davo** [comment]
Hi @karolkolodziej The demo you posted still seems to have the same issue. Sometimes the tooltip doesn't show up when I hover over a point.

**Comment by karolkolodziej** [comment]
You are right @el-davo.
After some testing, I was able to reproduce that issue even with `hideDelay: 0`

As another workaround, you can use the `line` series instead of `scatter` with disabled lines- [demo](https://jsfiddle.net/BlackLabel/v3nk5bjz/).

**Comment by el-davo** [comment]
Hi @karolkolodziej The suggested workaround is a bit of a hack and causes a few other problems for us as we are trying to use a line chart as a scatter plot. When you add many more points as would be on our production environment this becomes a bit messy. However thanks for looking into the issue. Though we may need to wait for an official fix for the scatter plot

**Comment by karolkolodziej** [comment]
Internal note:
When I dived deeper it looks like the `isInsidePlot` method returns false if you hover over the upper part of the marker.
I will try to adjust this method.
