### ISSUE TITLE
Projection explorer gets cut off when embedded in the docs

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#17928]
#### Expected behaviour
[The projection explorer demo in the docs](https://www.highcharts.com/docs/maps/mapview-and-projection#projection) looking good like in [the full sample view](https://www.highcharts.com/samples/maps/mapview/projection-explorer).

#### Actual behaviour
Often the text is cut off so not all the info is accessible.

#### Live demo with steps to reproduce
Extremes case when no description is visible at all. The left side is the full text. The right side is the general documentation site with that text completely cut off (Insets is the next docs chapter after the embedded explorer).
![image](https://user-images.githubusercontent.com/8960408/199696572-3a898047-d059-425b-a88b-ca5be192b1b6.png)

#### Product version
Documentation (+Highcharts Maps)

**Comment by hubertkozik** [comment]
Closed as completed in [#17950](https://github.com/highcharts/highcharts/pull/17950).
