### ISSUE TITLE
World map zooms in too much with single pinch even if there a limit on zoom 

### ISSUE THREAD

**Issue by SyedTayyab99** [highcharts/highcharts#17925]
#### Expected behaviour
We have disabled zoom in with pinch and added only buttons to zoom in. Technically pinch should have no effect on the chart. 

#### Actual behaviour
Zooming in with button and then pinching zooms the chart in or out so much that it all the regions disappear. It is shown in the video here: https://www.veed.io/view/b6ce7fa0-b899-4664-a524-e652442a67ef?sharingWidget=true

#### Affected browser(s)
IPAD webview

**Comment by SyedTayyab99** [comment]
Here is the error that i'm getting in the console. 
<img width="1728" alt="Screenshot 2022-11-04 at 5 35 04 PM" src="https://user-images.githubusercontent.com/21062011/199986479-6163e286-351d-46a0-89eb-fa2ebc3ca0ed.png">

**Comment by KacperMadej** [comment]
Hi @SyedTayyab99 

Thank you for reporting the problem.

> We have disabled zoom in with pinch and added only buttons to zoom in.

Please add the minimal chart configuration that needs to be used to recreate the problem and how you have set up the chart to work as you have described.

There is some other information missing:
Please add details about the browser and the hardware used - versions are missing.
Please add the Highcharts Maps version that you are using to get the errors.

Additional question:
Are you able to change the Highcharts library to the source version? (.src.js ending instead of the .js you use based on the error screenshot). The error message would then point to a debuggable code - not minified.

**Comment by SyedTayyab99** [comment]
Hi Kacper, 

Thank you so much for your response. I have replaced the .js files with .src.js versions. Also I am attaching an archive which you can unzip and run in the browser to check. All you would need to do would be to run it on a browser on an IPAD (problem happens with both chrome and safari). In order to regenerate quickly, please zoom once using the button and then click on any region, place one finger on the popup and the other on the other on an empty area. Then move your fingers quickly to the left and the issue will be reproduced. 

Alternatively, if you pinch and tap on multiple areas quickly on the chart after zooming, same thing will happen. Highmaps version being used here is v10.3.1. As for hardware and browser, it's happening on multiple versions of browsers and IPADs including the latest ones. 

Regards,
[Archive.zip](https://github.com/highcharts/highcharts/files/9964278/Archive.zip)

**Comment by KacperMadej** [comment]
Thank you for the code.

Here's a (not optimal but slightly simplified) live demo: https://jsfiddle.net/BlackLabel/dqem489t/5/

After the map is lost the mapView.center values are both NaN. This might not be the final source but still, something that should be fixed.

This bug will be investigated and we will try to resolve this as soon as possible. There is no workaround available at this moment. I am not able to recreate the problem without your custom jQuery-related code so this could be something that is causing the problem.

**Comment by SyedTayyab99** [comment]
Hi Kacper, 

Thank you for your response. So, I removed the custom jquery code and commented out even the inclusion of jquery. Then I replaced my custom map file with the world map regions file from highcharts and checked the issue. It appeared again. 

I'm attaching the new archive for your reference. 
[region-map_new.zip](https://github.com/highcharts/highcharts/files/9989147/region-map_new.zip)

**Comment by SyedTayyab99** [comment]
Hi Kacper, 

Any good news on this yet?

**Comment by r1fter** [comment]
Hello, i have encountered the same issue. Sadly, I can't provide my code, but steps to reproduce are the same - zoom, click, pinch. Even if mapNavigation param is false, the bug is still repoduces

**Comment by SyedTayyab99** [comment]
Hi, my project is stuck on this issue :( Can you please provide an ETA on the resolution?

**Comment by mabuhaddah** [comment]
Dears @magdalena-gut @KacperMadej
TO WHOM IS CONCERN

Kindly, we need to know the **due date** to resolve world map zooms issue, so we kindly request you to share update so far as the issue self-assigned on @magdalena-gut 13 days ago!
Your swift action is highlight appreciated

Thanks,

**Comment by KacperMadej** [comment]
We are working on resolving the problem. We were able to recreate the problem in a more stable way on an actual device (not emulated) with enabled debugging. Currently, we do not have a possible fix for you to test and verify. ETA for the fix is within the next week or two. Assignment to an issue is not the same as constantly working on the issue so the amount of days anyone is assigned doesn't reflect the work - it should only let everyone interested know that someone is investigating the issue or is responsible for the issue.

@SyedTayyab99 @mabuhaddah 
Are you interested in a workaround that could be applied to the current code instead of waiting for the fix to be published? This would be a temporary solution, that should be used mainly for testing. If yes, then you might be able to access the fix sooner then in the next release after this issue will be successfully closed.

**Comment by SyedTayyab99** [comment]
> We are working on resolving the problem. We were able to recreate the problem in a more stable way on an actual device (not emulated) with enabled debugging. Currently, we do not have a possible fix for you to test and verify. ETA for the fix is within the next week or two. Assignment to an issue is not the same as constantly working on the issue so the amount of days anyone is assigned doesn't reflect the work - it should only let everyone interested know that someone is investigating the issue or is responsible for the issue.
> 
> @SyedTayyab99 @mabuhaddah Are you interested in a workaround that could be applied to the current code instead of waiting for the fix to be published? This would be a temporary solution, that should be used mainly for testing. If yes, then you might be able to access the fix sooner then in the next release after this issue will be successfully closed.

@KacperMadej Thank you so much for providing us with the update. Yes, It would be really great, If a work around could be provided that we can use in the meantime. Please share that with me and i'll implement it in my code

**Comment by r1fter** [comment]
@KacperMadej Hello, please also inform me about a workaround. I got stuck on this issue too.

**Comment by mabuhaddah** [comment]
@KacperMadej 
Kindly be noted that **we are waiting to share the details of workaround solution**, your swift action is appreciated.

**Comment by mabuhaddah** [comment]
@KacperMadej 
Hi
Any update?

**Comment by KacperMadej** [comment]
There will be an infirmation update later today.

**Comment by magdalena-gut** [comment]
Hi @SyedTayyab99 @mabuhaddah @r1fter ,

As a temporary workaround, you can use the following plugin:

```
(function(H) {
   const MapView = H.MapView,
     addEvent = H.addEvent;

   function clamp(value, min, max) {
     return value > min ? value < max ? value : max : min;
   }

   var worldSize = 400.979322;
   var tileSize = 256;
   // Compute the zoom from given bounds and the size of the playing field. Used in
   // two places, hence the local function.
   var zoomFromBounds = function(b,
     playingField) {
     var width = playingField.width,
       height = playingField.height,
       scaleToField = Math.max((b.x2 - b.x1) / (width / tileSize), (b.y2 - b.y1) / (height / tileSize));
     return Math.log(worldSize / scaleToField) / Math.log(2);
   };

   //----------------------------

   MapView.prototype.setUpEvents = function() {
     var _this = this;
     var chart = this.chart;
     // Set up panning for maps. In orthographic projections the globe will
     // rotate, otherwise adjust the map center.
     var mouseDownCenterProjected;
     var mouseDownKey;
     var mouseDownRotation;
     var onPan = function(e) {
       var pinchDown = chart.pointer.pinchDown,
         projection = _this.projection;
       var mouseDownX = chart.mouseDownX,
         mouseDownY = chart.mouseDownY;
       if (pinchDown.length === 1) {
         mouseDownX = pinchDown[0].chartX;
         mouseDownY = pinchDown[0].chartY;
       }

       if (typeof mouseDownX === 'number' &&
         typeof mouseDownY === 'number') {
         var key = "" + mouseDownX + ",".concat(mouseDownY),
           _a = e.originalEvent,
           chartX = _a.chartX,
           chartY = _a.chartY;

         // Reset starting position
         if (key !== mouseDownKey) {
           mouseDownKey = key;
           mouseDownCenterProjected = _this.projection
             .forward(_this.center);
           mouseDownRotation = (_this.projection.options.rotation || [0, 0]).slice();
         }
         // Get the natural zoom level of the projection itself when
         // zoomed to view the full world
         var worldBounds = projection.def && projection.def.bounds,
           worldZoom = (worldBounds &&
             zoomFromBounds(worldBounds,
               _this.playingField)) || -Infinity;
         // Panning rotates the globe
         if (projection.options.name === 'Orthographic' &&
           // ... but don't rotate if we're loading only a part of the
           // world
           (_this.minZoom || Infinity) < worldZoom * 1.1) {
           // Empirical ratio where the globe rotates roughly the same
           // speed as moving the pointer across the center of the
           // projection
           var ratio = 440 / (_this.getScale() * Math.min(chart.plotWidth,
             chart.plotHeight));
           if (mouseDownRotation) {
             var lon = (mouseDownX - chartX) * ratio -
               mouseDownRotation[0],
               lat = clamp(-mouseDownRotation[1] -
                 (mouseDownY - chartY) * ratio, -80, 80),
               zoom = _this.zoom;
             _this.update({
               projection: {
                 rotation: [-lon, -lat]
               }
             }, false);
             _this.zoom = zoom;
             chart.redraw(false);
           }
         } else if (chartX && chartY) { // #17925 Skip NaN values
           var scale = _this.getScale();
           var newCenter = _this.projection.inverse([
             mouseDownCenterProjected[0] +
             (mouseDownX - chartX) / scale,
             mouseDownCenterProjected[1] -
             (mouseDownY - chartY) / scale
           ]);
           _this.setView(newCenter, void 0, true, false);
         }
         e.preventDefault();
       }
     };
     addEvent(chart, 'pan', onPan);
     addEvent(chart, 'touchpan', onPan);
     // Perform the map zoom by selection
     addEvent(chart, 'selection', function(evt) {
       // Zoom in
       if (!evt.resetSelection) {
         var x = evt.x - chart.plotLeft;
         var y = evt.y - chart.plotTop;
         var _a = _this.pixelsToProjectedUnits({
             x: x,
             y: y
           }),
           y1 = _a.y,
           x1 = _a.x;
         var _b = _this.pixelsToProjectedUnits({
             x: x + evt.width,
             y: y + evt.height
           }),
           y2 = _b.y,
           x2 = _b.x;
         _this.fitToBounds({
             x1: x1,
             y1: y1,
             x2: x2,
             y2: y2
           }, void 0, true, evt.originalEvent.touches ?
           // On touch zoom, don't animate, since we're already in
           // transformed zoom preview
           false :
           // On mouse zoom, obey the chart-level animation
           void 0);
         // Only for mouse. Touch users can pinch out.
         if (!/^touch/.test((evt.originalEvent.type))) {
           chart.showResetZoom();
         }
         evt.preventDefault();
         // Reset zoom
       } else {
         _this.zoomBy();
       }
     });
   };
 }(Highcharts));
```
**Demo:**
https://jsfiddle.net/BlackLabel/8xmhkoL7/

Take note, this workaround can be used only in case  `enableTouchZoom` is disabled.

We will keep you updated on the progress of this issue.

**Comment by SyedTayyab99** [comment]
> Hi @SyedTayyab99 @mabuhaddah @r1fter ,
> 
> As a temporary workaround, you can use the following plugin:
> 
> ```
> (function(H) {
>    const MapView = H.MapView,
>      addEvent = H.addEvent;
> 
>    function clamp(value, min, max) {
>      return value > min ? value < max ? value : max : min;
>    }
> 
>    var worldSize = 400.979322;
>    var tileSize = 256;
>    // Compute the zoom from given bounds and the size of the playing field. Used in
>    // two places, hence the local function.
>    var zoomFromBounds = function(b,
>      playingField) {
>      var width = playingField.width,
>        height = playingField.height,
>        scaleToField = Math.max((b.x2 - b.x1) / (width / tileSize), (b.y2 - b.y1) / (height / tileSize));
>      return Math.log(worldSize / scaleToField) / Math.log(2);
>    };
> 
>    //----------------------------
> 
>    MapView.prototype.setUpEvents = function() {
>      var _this = this;
>      var chart = this.chart;
>      // Set up panning for maps. In orthographic projections the globe will
>      // rotate, otherwise adjust the map center.
>      var mouseDownCenterProjected;
>      var mouseDownKey;
>      var mouseDownRotation;
>      var onPan = function(e) {
>        var pinchDown = chart.pointer.pinchDown,
>          projection = _this.projection;
>        var mouseDownX = chart.mouseDownX,
>          mouseDownY = chart.mouseDownY;
>        if (pinchDown.length === 1) {
>          mouseDownX = pinchDown[0].chartX;
>          mouseDownY = pinchDown[0].chartY;
>        }
> 
>        if (typeof mouseDownX === 'number' &&
>          typeof mouseDownY === 'number') {
>          var key = "" + mouseDownX + ",".concat(mouseDownY),
>            _a = e.originalEvent,
>            chartX = _a.chartX,
>            chartY = _a.chartY;
> 
>          // Reset starting position
>          if (key !== mouseDownKey) {
>            mouseDownKey = key;
>            mouseDownCenterProjected = _this.projection
>              .forward(_this.center);
>            mouseDownRotation = (_this.projection.options.rotation || [0, 0]).slice();
>          }
>          // Get the natural zoom level of the projection itself when
>          // zoomed to view the full world
>          var worldBounds = projection.def && projection.def.bounds,
>            worldZoom = (worldBounds &&
>              zoomFromBounds(worldBounds,
>                _this.playingField)) || -Infinity;
>          // Panning rotates the globe
>          if (projection.options.name === 'Orthographic' &&
>            // ... but don't rotate if we're loading only a part of the
>            // world
>            (_this.minZoom || Infinity) < worldZoom * 1.1) {
>            // Empirical ratio where the globe rotates roughly the same
>            // speed as moving the pointer across the center of the
>            // projection
>            var ratio = 440 / (_this.getScale() * Math.min(chart.plotWidth,
>              chart.plotHeight));
>            if (mouseDownRotation) {
>              var lon = (mouseDownX - chartX) * ratio -
>                mouseDownRotation[0],
>                lat = clamp(-mouseDownRotation[1] -
>                  (mouseDownY - chartY) * ratio, -80, 80),
>                zoom = _this.zoom;
>              _this.update({
>                projection: {
>                  rotation: [-lon, -lat]
>                }
>              }, false);
>              _this.zoom = zoom;
>              chart.redraw(false);
>            }
>          } else if (chartX && chartY) { // #17925 Skip NaN values
>            var scale = _this.getScale();
>            var newCenter = _this.projection.inverse([
>              mouseDownCenterProjected[0] +
>              (mouseDownX - chartX) / scale,
>              mouseDownCenterProjected[1] -
>              (mouseDownY - chartY) / scale
>            ]);
>            _this.setView(newCenter, void 0, true, false);
>          }
>          e.preventDefault();
>        }
>      };
>      addEvent(chart, 'pan', onPan);
>      addEvent(chart, 'touchpan', onPan);
>      // Perform the map zoom by selection
>      addEvent(chart, 'selection', function(evt) {
>        // Zoom in
>        if (!evt.resetSelection) {
>          var x = evt.x - chart.plotLeft;
>          var y = evt.y - chart.plotTop;
>          var _a = _this.pixelsToProjectedUnits({
>              x: x,
>              y: y
>            }),
>            y1 = _a.y,
>            x1 = _a.x;
>          var _b = _this.pixelsToProjectedUnits({
>              x: x + evt.width,
>              y: y + evt.height
>            }),
>            y2 = _b.y,
>            x2 = _b.x;
>          _this.fitToBounds({
>              x1: x1,
>              y1: y1,
>              x2: x2,
>              y2: y2
>            }, void 0, true, evt.originalEvent.touches ?
>            // On touch zoom, don't animate, since we're already in
>            // transformed zoom preview
>            false :
>            // On mouse zoom, obey the chart-level animation
>            void 0);
>          // Only for mouse. Touch users can pinch out.
>          if (!/^touch/.test((evt.originalEvent.type))) {
>            chart.showResetZoom();
>          }
>          evt.preventDefault();
>          // Reset zoom
>        } else {
>          _this.zoomBy();
>        }
>      });
>    };
>  }(Highcharts));
> ```
> 
> **Demo:** https://jsfiddle.net/BlackLabel/8xmhkoL7/
> 
> Take note, this workaround can be used only in case `enableTouchZoom` is disabled.
> 
> We will keep you updated on the progress of this issue.

HI @magdalena-gut,

Thank you so much for providing the workaround. It works GREAT! Will be looking forward to the fix in next release, however, for now this is working awesome.

**Comment by raf18seb** [comment]
@circleci-mu you know better
