### ISSUE TITLE
Unable to render fontawesome icons in sankey

### ISSUE THREAD

**Issue by gsharath** [highcharts/highcharts#17922]
#### Expected behaviour
When using fontawesome icons, they should be rendered in sankey charts.

#### Actual behaviour
font awesome icons are not displayed.

#### Live demo with steps to reproduce

I am looking for something similar  to [This one ]( https://github.com/highcharts/highcharts/issues/14573 ) for a sankey chart which I am not able to figure out.
I am using a sankey chart, added nodeFormatter and formatter which returns a markup ( used a React component and returned a markup out of it). Adding an fontawesome icon isn't showing up here.

Below is what I have tried.
https://codesandbox.io/s/highcharts-react-demo-forked-ipn787

#### Product version
Highcharts

**Comment by gsharath** [comment]
I missed adding useHTML prop and that the reason, icon isnt working.
But still unable to add a component for subtitle

**Comment by karolkolodziej** [comment]
Yes adding `useHTML` to the series data labels config solves the issue- [demo](https://codesandbox.io/s/highcharts-react-demo-forked-2lgx8s).

For future reference, we treat GitHub as a feature/bug tracking tool, and your question could be solved by our support team. With this kind of question, please reach out to us via[ our available support channels](https://www.highcharts.com/blog/support/), where our support engineers will help you with that.
