### ISSUE TITLE
Windbarbs graph with keyed array with seems to require specific names

### ISSUE THREAD

**Issue by siggemannen** [highcharts/highcharts#17939]
#### Expected behaviour
Hello. I'm using json coming from third party in form of "keyed" data array: 

```javascript
"data": [{"Period": 2022052212, "Value":10, "Value2": 20}] 
```
to generate windbarb graphs.

Unfortunately it seems to only accept array in form of:

```javascript
"data": [{
        "x": 2022052212,
        "value": 10,
        "direction": 20
      }]
```

I thought i could use the "keys" attribute to teach it like: 

```javascript
"keys": ["x", "value", "direction"]
```
 but this has no effect.
For various reasons it's not easy to change the array i'm getting

#### Actual behaviour

No error nor graph is displayed if my array keys aren't named exactly x, value, direction.
Keys attribute doesn't seem to have any effect either

#### Live demo with steps to reproduce
https://jsfiddle.net/t0jb3ayg/1/

#### Product version
Highcharts from https://code.highcharts.com/highcharts.js

#### Affected browser(s)

I use Chrome but probably same in all browsers

**Comment by karolkolodziej** [comment]
Hi @siggemannen!

The `keys` work only if the data is declared as an array of arrays, see a quote from [API docs:](https://api.highcharts.com/highcharts/series.windbarb.keys)
_An array specifying which option maps to which key in the **data point array**._ 

If you slightly process that data you can use the `keys` property- [demo](https://jsfiddle.net/BlackLabel/L8nsu69a/)

**Comment by siggemannen** [comment]
Hi, and thanks for the quick answer. I see, it would be nice if it could work the way i tried but i understand that it's not!
I managed to work around the issue by changing the array the hard way.

Thanks a lot!
