### ISSUE TITLE
Column Chart Bar not grouped in correct X category when using Explicit (x, y) data values

### ISSUE THREAD

**Issue by MasterCash** [highcharts/highcharts#17930]
#### Expected behaviour
when using both (x, y) values when creating a column chart for the data, bars are correctly grouped with their x value (aka category)

#### Actual behaviour
If you have a data set with labels (x, y) where one x category is missing in the middle of the series, the following data points are shifted over to the previous category instead of there being a blank in that category. 

In the following image, the 2021 x value is in the 2020 category instead of the 2021.

![image](https://user-images.githubusercontent.com/13630698/199826315-c1b93a19-5aa5-4d54-a848-230cf283e27f.png)

note: If using numerical values for x axis instead of category values (strings) it works as expected.

#### Live demo with steps to reproduce
[example: https://jsfiddle.net/48ywndro/9/](https://jsfiddle.net/48ywndro/9/)

#### Product version
Highcharts - 10.2.0

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Hi @MasterCash.

Please do not hardcode the axis `categories`. If they are declared, the first value from the data point `x/name` is ignored.

Instead set only the `type: 'category'` and let the chart calculate where each point should be located- [demo](https://jsfiddle.net/BlackLabel/358mz02d/).
