### ISSUE TITLE
Data label does not render even when there is space for it

### ISSUE THREAD

**Issue by frycz** [highcharts/highcharts#17936]
#### Expected behaviour

A data label should render if there is space for it. In this case, there is space below the data point where the label could appear. Would it make sense?

A label rendered above the point:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/6745392/199979668-7a9d8f70-9f52-4818-aa4e-1f1551b272fc.png">

No label rendered above, but there is space bellow the point:
<img width="246" alt="image" src="https://user-images.githubusercontent.com/6745392/199979841-92deb1ab-704e-4a18-8119-6847e7ec2cee.png">

#### Actual behaviour

A data label is not rendered.

#### Live demo with steps to reproduce

https://jsfiddle.net/p8uv5tgs/ - label rendered
https://jsfiddle.net/svj13npe/2/ - label not rendered

#### Product version

The demo runs on 10.3.1, the issue exists on 9.x.x as well.

#### Affected browser(s)

Tested on Chrome 106.0.5249.103 (Official Build) (arm64)

**Comment by karolkolodziej** [comment]
Hi @frycz 

Unfortunately, currently, we do not provide any collision detection mechanism that could evenly distribute the labels across series- [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/15960472-collision-detection-for-data-labels).

However, you can manually, by setting the `y` property set the data labels position- [demo](https://jsfiddle.net/BlackLabel/eszqgfum/).

**Comment by frycz** [comment]
Ok, thanks @karolkolodziej 👍
