### ISSUE TITLE
Range Selector not showing

### ISSUE THREAD

**Issue by ad3293** [highcharts/highcharts#17931]
Since Monday, my range selector setting stopped working. I include highcharts import in my setup. Do I need to import anything else ?

**Comment by pawellysy** [comment]
Hello @ad3293, thanks for reaching out to us. 
Could you please include the demo, where your issue is reproduced? Here is an example: https://jsfiddle.net/BlackLabel/bwgno6jh/34/

**Comment by pawellysy** [comment]
Closing - No reproduction steps provided
