### ISSUE TITLE
Drilldown xAxis labels underline

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#17933]
#### Actual behaviour
After drilling down on first xAxis category "Chrome", first three `xAxis.labels` are underlined. 
This error occurs on `chart.width` < 430px.

#### Internal note
Possible regression, last working version **9.3.3**.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/rwhp1cbj/
Click on "Chrome" and observe the first three labels after drilldown.

#### Product version
Highcharts 10.3.1
modules/drilldown 10.3.1

**Comment by hubertkozik** [comment]
A possible fix is to set more detailed `xAxis.labels.style` options:
```
xAxis: {
	labels: {
		style: {
			'text-decoration': 'none',
			'font-weight': 'normal'
		}
	}
  }
```

 Demo with a workaround: https://jsfiddle.net/BlackLabel/897yxdjv/
