### ISSUE TITLE
.NET Highcharts Formatters Don't Work in Hashtable

### ISSUE THREAD

**Issue by fceci90** [highcharts/highcharts#17942]
#### Expected behaviour
Formatters should map to a JavaScript function.
Formatter = "formatterFunctionName"
or within a Hashtable
`{ 
  { "formatter", "formatterFunctionName" }
}`

#### Actual behaviour
For instances where the formatter property is within a Hashtable, like the PlotOptions.PlotOptionsPie.DataLabels, this does not work.
Documentation page for pie chart data labels: https://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_plot_options_pie.html#a3fbdebfe3784b703b078b3eee73f38aa
Error Message: Uncaught TypeError: (b[(a.formatPrefix + "Formatter")] || b.formatter).call is not a function

Reference to JS docs which show all DataLabels properties, including Formatter: https://api.highcharts.com/highcharts/plotOptions.pie.dataLabels

#### Live demo with steps to reproduce
Not sure how to reproduce a demo using .NET. These are my PlotOptions settings:
`PlotOptions = new Highsoft.Web.Mvc.Charts.PlotOptions
        {
            Pie = new Highsoft.Web.Mvc.Charts.PlotOptionsPie
            {
                DataLabels = new System.Collections.Hashtable
                {
                    { "enabled", true },
                    { "distance", -75 },
                    { "formatter", "mktCapPieLabelFormatter" }
                },
                ShowInLegend = true
            }
        }`

**Comment by magdalena-gut** [comment]
FYI @brofixo
