### ISSUE TITLE
Display of shared tooltip incorrect when using `reversedStacks`

### ISSUE THREAD

**Issue by robinroestenburg** [highcharts/highcharts#17948]
#### Expected behaviour
When using a shared tooltip in a stacked bar chart that is using the `reversedStacks` option on the `yAxis`, I expect the tooltip to be displayed at the end of the bar (if there is room). This expected behavior would be similar to how the shared tooltip is displayed when not using the `reversedStacks` option.

#### Actual behaviour
The shared tooltip is displayed in the middle of the bar, making it difficult to view the data:

<img width="912" alt="Screenshot 2022-11-07 at 20 29 14" src="https://user-images.githubusercontent.com/693266/200397707-75190c15-9b17-4307-ac88-8c2f19362eab.png">

For comparison, the behaviour when not using the `reversedStacks` option:

<img width="908" alt="Screenshot 2022-11-07 at 20 28 38" src="https://user-images.githubusercontent.com/693266/200397596-137b0afb-bd14-4411-8165-5da9a1d79d47.png">

Using the `{ legend: { reversed: true } }` as a workaround works, but I can't use that because our series are ordered by size/number of results. Something like: '1', '2', '3', 'Other'.

#### Live demo with steps to reproduce
https://jsfiddle.net/5y6mcjp9/

#### Product version
Reproducible on Highcharts, master.

#### Affected browser(s)
I don't think the browser is of influence, but I was able to reproduce it on:
- Microsoft Edge: 107.0.1418.28 (Official build) (arm64)
- Safari: 15.6.1 (17613.3.9.1.16)

**Comment by pawellysy** [comment]
hi @robinroestenburg, thanks for reporting a bug!
you can use the tooltip.positioner as a workaround, to set the position of the tooltip manually: https://jsfiddle.net/BlackLabel/7f6bac8x/3/
