### ISSUE TITLE
Create zoom feature for Organization chart

### ISSUE THREAD

**Issue by QlNaga** [highcharts/highcharts#17949]
Hello Highchart Dev Team ! 
I would like to request a new feature for Organization Chart : Zoom in/Zoom Out for large Org Chart

# Description of the feature
I am actually working on a completly automatic way to produce Org chart with data i find with C# (ASP.NET MVC) : i "build" classes based on your documentation, fill with data, convert to Json and display the result. 

On some data, the result could return a chart with more than 20 nodes (also depend if inverted or not, the number of children along the tree, etc), one after another. For the user, it would be interesting to zoom out and have a global appreciation of the structure of the result WITHOUT drilldown.

Bonus : could it be possible to enable the zoom in code and tap a key (ctrl for exemple) to zoom in/out ?

Note : i also work on "calucating" the height and width of the chart depending on the content.

Exemple : https://jsfiddle.net/48kb17mo/ (in advance : pardon my French)

Thanks you so much ! 
Quentin P

# Library related to the feature
Highchart Organization
Highchart Sankey

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by bm64** [comment]
Thanks @QlNaga for sharing the idea! Feature request for zoom in organization chart has already been created: #17193
I'm closing this one as a duplicate, but feel free to continue discussion in the original ticket.
