### ISSUE TITLE
`nullColor` propertie on `Heatmap` does not work if `Highcharts.PatternObject` given

### ISSUE THREAD

**Issue by optyler** [highcharts/highcharts#17956]
#### Expected behaviour
per the documentation, `heatmap` charts can have a nullColor propertie which can contain a color String, a color pattern or a color gradient.

#### Actual behaviour
It works great for color string and gradient, but not with pattern. 
I tried multiple syntax, in `plotOptions.heatmap` or `plotOptions.series` but nothing works.

#### Live demo with steps to reproduce
https://jsfiddle.net/optyler/8h312bpa/

#### Product version
```
"@highcharts/map-collection": "^2.0.1",
"highcharts": "^10.2.1",
"highcharts-react-official": "^3.1.0",
```

Tested on Chrome Version 105.0.5195.125

**Comment by karolkolodziej** [comment]
Hi @optyler!

In order to make it work please import the `pattern-fill` module- [demo](https://jsfiddle.net/BlackLabel/k4z927uc/).

**Comment by optyler** [comment]
well, sorry for the inconvenience, since the Gradient works, I never thought it could be a model, my bad. 
 
Thanks for your time, you can close this :D
