### ISSUE TITLE
Data label disappears on hover

### ISSUE THREAD

**Issue by kluvin** [highcharts/highcharts#17957]
#### Expected behaviour
Data label persist on hover

#### Actual behaviour
Data label disappears on hover

#### Live demo with steps to reproduce
https://jsfiddle.net/qhwz90nL/

Removing off the `marker.enabled: false` bit, the issue is resolved.
https://jsfiddle.net/qhwz90nL/1/

#### Product version
Presumably originating in the Accessibility module.
Introduced in 10.3.0 and seen in later versions

#### Affected browser(s)
FF, Chrome

**Comment by karolkolodziej** [comment]
Hi @kluvin and thank you for reporting that issue!

_Internal note:_
Bisected to commit: https://github.com/highcharts/highcharts/commit/ac1f55bcd0fbe42c92ff1ea7f80bfaaf622da8ab
FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Ouch. We should prioritize this. @karolkolodziej will you have a look? We need to figure out what `series.options.inactiveOtherPoints` has to do with this and why the offending commit broke it.

**Comment by TorsteinHonsi** [comment]
@karolkolodziej I just tried re-adding this:

```
if (
                    series.options.inactiveOtherPoints &&
                    isNumber(opacity)
                ) {
                
```

Actually I can't see any consequence on the map that I was testing when removing the `inactiveOtherPoints` check. So I suggest just adding that condition back to what it was, and making sure we have a regression test for #17957.
