### ISSUE TITLE
scrollablePlotArea mask opacity with breadcrumbs and zIndex 

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#17963]
#### Expected behaviour
Highcharts scrollbar and breadcrumbs should be on top of `scrollablePlotArea` mask.

#### Actual behaviour
![image](https://user-images.githubusercontent.com/105275628/201307255-f5bc0eaf-3198-4f41-b030-92cd11ad1ef7.png)
![image](https://user-images.githubusercontent.com/105275628/201307286-66c5a7d0-eeaf-4e03-b0bc-09b31b400969.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/fnt5u0eh/

#### Product version
Highcharts + drilldown 10.3.1 (latest)

#### Affected browser(s)
Due to the styling, the scrollbar issue might be visible only in Windows.

**Comment by karolkolodziej** [comment]
The `breadcrumbs` class should be added to the `fixedSelectors`- [demo](https://jsfiddle.net/BlackLabel/x2qtdm7L/).
