### ISSUE TITLE
Gantt modules missing from highcharts-dist

### ISSUE THREAD

**Issue by cnrudd** [highcharts/highcharts#17979]
I cannot fine these modules:
https://code.highcharts.com/gantt/modules/exporting.js
https://code.highcharts.com/gantt/modules/exporting.src.js
https://code.highcharts.com/gantt/modules/gantt.js
https://code.highcharts.com/gantt/modules/gantt.src.js
https://code.highcharts.com/gantt/modules/grid-axis.js
https://code.highcharts.com/gantt/modules/grid-axis.src.js
https://code.highcharts.com/gantt/modules/pathfinder.js
https://code.highcharts.com/gantt/modules/pathfinder.src.js
https://code.highcharts.com/gantt/modules/pattern-fill.js
https://code.highcharts.com/gantt/modules/pattern-fill.src.js
https://code.highcharts.com/gantt/modules/static-scale.js
https://code.highcharts.com/gantt/modules/static-scale.src.js
https://code.highcharts.com/gantt/modules/treegrid.js
https://code.highcharts.com/gantt/modules/treegrid.src.js

in [highcharts-dist](https://github.com/highcharts/highcharts-dist)

I am putting a gantt chart into a react app.  I can get the chart to work, but the exporting menu is not available.
I think I need this file:
https://code.highcharts.com/gantt/modules/exporting.js
to be included in the highcharts npm package.  The exporting.js file that is already in the npm package does not appear to be used by the gantt chart code.

Thank you!
Colin

**Comment by karolkolodziej** [comment]
Hi @cnrudd!

Could you please tell me which version are you using?

**Comment by karolkolodziej** [comment]
We are going to investigate that but in the meantime, you can use the exporting module from the root folder like:
https://code.highcharts.com/modules/exporting.js

**Comment by cnrudd** [comment]
We were using v9.3.0.   Upgrading to v10.3.1 resolved the issue and allowed exporting the Gantt chart with https://code.highcharts.com/modules/exporting.js

Thank  you!
