### ISSUE TITLE
Dumbbell resize bug

### ISSUE THREAD

**Issue by Vazonik** [highcharts/highcharts#17975]
#### Expected behaviour
When shrinking the window in the x-axis and then returning to its previous size, the chart also returns to its original state, the way it's displayed doesn't change.

#### Actual behaviour
When shrinking the window in the x-axis until the points on the chart disappear, returning to the previous size of the window causes the chart not to return to its original state. Displays incorrectly, points are still invisible.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/kvL340fa/

Steps:
1. Shrink the window with a chart to the minimum width.
2. Expand the window to its original width.

#### Product version
Highcharts v10.3.1 + Highcharts More + Dumbbell

**Comment by karolkolodziej** [comment]
Hi @Vazonik thank you for reporting that!

Internal note: 
Bisected to commit: https://github.com/highcharts/highcharts/commit/b84e453a78317fb0df03d63fe86db8f463120de5

Workaround:
Broken since v10.3.0 so you can use the previous version- [demo](https://jsfiddle.net/BlackLabel/kbfh7pd8/).

**Comment by bm64** [comment]
Resolved by #18104
