### ISSUE TITLE
Cannot read properties of undefined (reading 'x') when using chart.update

### ISSUE THREAD

**Issue by hasanagh** [highcharts/highcharts#17989]
#### Expected behavior
Chart updates with the new series

#### Actual behavior
Error is being thrown: Cannot read properties of undefined (reading 'x') 

#### Live demo with steps to reproduce
https://jsfiddle.net/hanext/ahoxg9p4/27/

1. Enter the fiddle
2. Click on the Click me button
3. Check the error in the console and in the browser console
4. The second series is not being rendered
5. This only happens when updating the chart, drawing with this config initially works

#### Product version

Latest
#### Affected browser(s)
ALL

**Comment by pawellysy** [comment]
Thanks @hasanagh, for creating this issue. 
Could you please try simplifying the demo?
You shared the demo, where 5000 lines of config, and it is really time-consuming to seek, what the difference between those 2 configs is. Thanks@

**Comment by pawellysy** [comment]
Hi @hasanagh, thanks for your input. By deleting some parts of the config, you can simplify the demo, to find which lines of code are responsible for throwing the error. 
Here is my simplified demo: https://jsfiddle.net/BlackLabel/c4n6q12h/2/

`Internal Note`
The cause of the error is updating the chart and giving 2 series the same id, whereas they have nothing in common.
#### Workaround
The workaround is to either delete the IDs or be precise to give them different IDs, like here: https://jsfiddle.net/BlackLabel/c4n6q12h/3/
