### ISSUE TITLE
Onclick in Highchart Organization chart doesn't work

### ISSUE THREAD

**Issue by doddyjonathan360** [highcharts/highcharts#17980]
#### Issue
Onclick in Highchart Organization chart doesn't work.
Michał Filipiec (Highcharts Developer) has confirmed in the thread below that it's a regression bug, "in version 10.2.1 click works fine"
https://www.highcharts.com/forum/viewtopic.php?f=9&t=44824

#### Live demo with steps to reproduce
Demo: https://jsfiddle.net/BlackLabel/350na8qp/

**Comment by pawellysy** [comment]
Bisected to 2a332890a7ba53737caa9b7dbc3271a3782fe78f
