### ISSUE TITLE
Tooltip `xDateFormatter` option

### ISSUE THREAD

**Issue by ravindUwU** [highcharts/highcharts#17981]
# Description of the feature

A `tooltip.xDateFormatter` option that allows formatting timestamps with a non-[`dateFormat`](https://api.highcharts.com/class-reference/Highcharts.Time#dateFormat) format, in addition to the [`tooltip.xDateFormat`](https://api.highcharts.com/highcharts/tooltip.xDateFormat) option.

This would be analogous to,
- [`tooltip.pointFormat`](https://api.highcharts.com/highcharts/tooltip.pointFormat) and [`tooltip.pointFormatter`](https://api.highcharts.com/highcharts/tooltip.pointFormatter).
- [`tooltip.nullFormat`](https://api.highcharts.com/highcharts/tooltip.nullFormat) and [`tooltip.nullFormatter`](https://api.highcharts.com/highcharts/tooltip.nullFormatter).

# Library related to the feature

Highcharts

# API example

`xDateFormatter` could be a `(this: Point, timestamp: number) => string`, and used as 👇,

```typescript
import * as Highcharts from 'highcharts';
import { DateTime } from 'luxon';

options: Highcharts.Options = {
	// ...
	tooltip: {
		// Instead of a fixed format 👇
		xDateFormat: '%Y/%m/%d, %l:%M %P',

		// Delegate formatting to a different library (Luxon, in this case) 👇
		xDateFormatter(timestamp) {
			return DateTime.fromMillis(timestamp).toLocaleString(DateTime.DATETIME_SHORT);
		},
	},
};
```

**Comment by pawellysy** [comment]
Thanks for creating this feature request!
As a workaround, you can use both methods mentioned above, where you can format the date the same way you described.
