### ISSUE TITLE
Docs: series.scatter.data.dataLabels is declared as object but also accepts an array

### ISSUE THREAD

**Issue by people-ware** [highcharts/highcharts#17988]
#### Expected behaviour

As mentioned the input is the same as for plotOptions.series.dataLabels. But the "{" in the properties overview indicates that for series.scatter.data.dataLabels only a single object specifying a single label is allowed.

#### Actual behaviour

series.scatter.data.dataLabels is displayed as "[{" in the properties menu.

#### Product version
10

![image](https://user-images.githubusercontent.com/10436633/202419394-52f50659-1b96-431c-9df4-35640bf7810f.png)

**Comment by pawellysy** [comment]
Thanks for reporting this issue @Hubel!
