### ISSUE TITLE
Linecap combined with dashStyle not working

### ISSUE THREAD

**Issue by KamilKubik** [highcharts/highcharts#17998]
#### Expected behaviour
`series.linecap` property should be applied when `series.dashStyle` property is declared.

#### Actual behaviour
`series.linecap` property isn't applied when `series.dashStyle` property is declared.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/jpt2wrx7/

#### Product version
Highcharts v10.3.1

**Comment by karolkolodziej** [comment]
Those two properties coexist in SVG ([demo](https://jsfiddle.net/BlackLabel/etf78wab/)) and I don't see any reason why it should in the Highcharts.

Workaround:
Wrap applied to the `drawGraph`method- [demo](https://jsfiddle.net/BlackLabel/u0b586a4/).

Internal note:
The `else if` should be split into the `if`.
https://github.com/highcharts/highcharts/blob/3f396d86856212cec7252b27278d8928435a21c5/ts/Series/Line/LineSeries.ts#L169-L174

**Comment by MarkusBarstad** [comment]
Quick question @karolkolodziej: Should the legend-symbol be rounded in case of rounded linecap?

**Comment by karolkolodziej** [comment]
IMO legend should reflect the series so answering your question yes it should have also a rounded linecap.
@TorsteinHonsi what is your opinion?

**Comment by TorsteinHonsi** [comment]
Yes I think it should, ideally. Let's try to code it and see how it looks.
