### ISSUE TITLE
Controlpoint positioner wrong behaviour on measure annotation selectType x

### ISSUE THREAD

**Issue by htvildeEccoit** [highcharts/highcharts#17995]
#### Expected behaviour
Using the measure annotation, with selectType "x", should place the controlpoints midway between y-axis.max and y-axis.min, accounting for non-zero start of y-axis.

Meaning for a chart with y-axis of 60<->10 the controlpoints should be placed at y=35 (y=dY/2+y0)

Annotation is of "measure" type and selectType is "x".

#### Actual behaviour
Controlpoints for measure annotation and selectype "x" does not account for y-axis that is not 0, and follows the formula y=dY/2 for placement. 
Meaning for a chart with y-axis of 60<->10 the controlpoints are placed at y=25
Behavior holds true for chart that stretches between negative and positive y-numbers

![Example_02](https://user-images.githubusercontent.com/118511771/202653901-c855a805-f098-4c46-88e4-7a1e9c8828b4.png)
![Example_01](https://user-images.githubusercontent.com/118511771/202653911-cb150a92-df5f-4239-98c5-08c156402e71.png)

#### Live demo with steps to reproduce
[Example using positive numbers:](https://jsfiddle.net/jobbTvilde/es7tgcak/16/)
[Example using negative to positive numbers](https://jsfiddle.net/jobbTvilde/u8vhz1sr/12/)

#### Product version
Highcharts JS v10.3.1, Annotations module &  Annotation advanced module 

Similar behaviour in 
 Highcharts JS v8.0.4, Annotations module &  Annotation advanced module

#### Affected browser(s)
Both versions tested in :
Brave v1.45.127 w/ chromium 107.0.5304.110
Chrome v107.0.5304.107 (32-bit)
Chromium browser v 88.0.4324.190

Both fiddles are opened in
Firefox v 106.0.5 (64-bit)

**Comment by pawellysy** [comment]
Hi @htvildeEccoit, thanks for reaching out to us!
indeed there is a bug, with a really simple solution. 
https://github.com/highcharts/highcharts/blob/3f396d86856212cec7252b27278d8928435a21c5/ts/Extensions/Annotations/Types/Measure.ts#L1079

Replace `-` with `+` :) 

Workaround Demo: https://jsfiddle.net/BlackLabel/7kL1zjhw/

**Comment by htvildeEccoit** [comment]
Hello @pawellysy , thanks for the reply. The fix works as intended, much appreciated!

Have a nice day.
