### ISSUE TITLE
Add curve effect to Funnel chart, in horizontal and vertical modes

### ISSUE THREAD

**Issue by stemarie** [highcharts/highcharts#18006]
Searched forums and StackOverflow and didn't find

The funnel chart currently only supports very straight lines and doesn't look very well - we would like to introduce a curve effect on the sides to make it more aesthetic.

![image](https://user-images.githubusercontent.com/1579907/203107381-0113d4d6-621c-4b7d-99ad-b81d8f09449f.png)

**Comment by pawellysy** [comment]
Hi @stemarie, thanks for sharing this idea!
