### ISSUE TITLE
Vertical line with gradient is not displayed

### ISSUE THREAD

**Issue by Vazonik** [highcharts/highcharts#18000]
#### Expected behaviour
A line coloured with a gradient displays correctly regardless of its direction.

#### Actual behaviour
A line coloured with a gradient is not displayed if it is perfectly vertical.
The inclination of the line by an imperceptible amount makes it display correctly.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/sgpw9ayu/

#### Product version
Highcharts v10.3.1

**Comment by bm64** [comment]
Closing as a duplicate of #1677. Related feature request #17029.
