### ISSUE TITLE
Chart with boost crash

### ISSUE THREAD

**Issue by affenuclear** [highcharts/highcharts#18003]
#### Expected behaviour
The chart shouldn't crash, bars should remain visible

#### Actual behaviour
Chart goes blank, data disappears

#### Live demo with steps to reproduce
When I load up this chart :
https://jsfiddle.net/nucnuc/v9Lxb52j/3/

and I follow these steps:

1- In the legend, unselect "series1", select it again
2- In the legend, unselect "series boost", select it again
3- Zoom in getting all bars
4- Repeat step 1 and 2

#### Product version
8.3.2 and above

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Hi @affenuclear, thank you for reporting that issue.

[Simplified demo](https://jsfiddle.net/BlackLabel/qbm5vsz0/)
