### ISSUE TITLE
Highcharts annotations not working

### ISSUE THREAD

**Issue by itfuzzy72622** [highcharts/highcharts#18002]
I create the javascipt for highcharts using a PHP program. This should display a chart with 2 rows of data, where one row should display some annotations. Unfortunately the annotations aren't visible. I checked the code up and down many times but without detecting any problems.
Could you give a hint, what's going wrong? I would highly appreciate a tip to solve the problem.

The attched file contains a complete html-file with the embedded javascript for highcharts
[page_nok.zip](https://github.com/highcharts/highcharts-react/files/10050236/page_nok.zip)

**Comment by pawellysy** [comment]
Hello @itfuzzy72622, thanks for reaching out to us!
Sorry to inform you, but We use GitHub as a bug/feature tracking tool. For questions like this, please reach out to us via our [available support channels](https://www.highcharts.com/blog/support/), where our support engineers are more than happy to help you with tweaking the chart's configuration to your need.
