### ISSUE TITLE
Tooltip `stickOnContact` doesn't work with `outside` (v10.3.0+ regression)

### ISSUE THREAD

**Issue by Vazonik** [highcharts/highcharts#18014]
#### Expected behaviour
Tooltip with `stickOnContact: true` should not disappear when hovered even if `outside: true` is enabled.

#### Actual behaviour
Since v10.3.0 an outside tooltip disappears while hovering despite using `stickOnContact`.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/xkqu4tzh/

#### Product version
Highcharts v10.3.0+
[Regression, it was working until v10.2.1]

**Comment by bm64** [comment]
Thanks @Vazonik for reporting! 
Internal note: unable to bisect.

**Comment by hubertkozik** [comment]
This issue is resolved in the latest version of Highcharts (v11). 

Demo without the issue on the latest version: https://jsfiddle.net/BlackLabel/vhnrcjsa/

Closing as completed.
