### ISSUE TITLE
gridline: clipping issue in stock

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#18025]
#### Expected behaviour
![1](https://user-images.githubusercontent.com/39968065/203793560-dd1829fc-7260-4b2a-bf9c-4ee6bbd02522.png)

#### Actual behaviour
We are currently unable to remove the red line from the gridline options: 
https://api.highcharts.com/highstock/xAxis.gridLineWidth

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8znmf1ew/

#### Workaround: 
https://jsfiddle.net/BlackLabel/c0swz1mL/

#### Product version
v10.3.1

**Comment by pawellysy** [comment]
`Internal note`

When drawing the gridLine using the `getPlotLinePath` method, the option: `acrossPanes: false` should be set here  👇 

https://github.com/highcharts/highcharts/blob/e553b9742bf2cd2d01609d9435c543496146bd51/ts/Core/Axis/Tick.ts#L914-L921
