### ISSUE TITLE
Export Data module hits error finding "th" elements in web component/shadow DOM

### ISSUE THREAD

**Issue by troyvassalotti** [highcharts/highcharts#18021]
#### Expected behaviour

Showing the data table using the Export Data module renders a table of currently viewed data below the chart, with clickable table headers to sort the table.

#### Actual behaviour

Clicking "View data table" renders a table below the chart, but the error `Uncaught TypeError: document.querySelectorAll(...)[0] is undefined`. Table headers are unable to be clicked and sorted. The option to "Hide data table" is not available.

#### Live demo with steps to reproduce

https://codepen.io/troyvassalotti/pen/dyKmmpK

1. Open the export menu
2. Click View data table
3. Observe the console for error

I looked around and I have a feeling it's because in `onChartAfterViewData()` in `export-data.js`, it uses `document.querySelectorAll` to define `row`,  which doesn't return any nodes inside the shadow root. Locally, changing `row = document.querySelectorAll('thead')[0].querySelectorAll('tr')[0]` to `row = dataTableDiv.querySelectorAll('thead')[0].querySelectorAll('tr')[0]` appeared to fix my issue,

#### Product version

Highcharts@10.3.1

#### Affected browser(s)

Chrome. Firefox (unable to verify with others).

**Comment by bm64** [comment]
Hello @troyvassalotti and thanks for reporting the issue! 
You’re right, it doesn’t work because document.querySelectorAll can’t access elements that belongs to the Shadow DOM created by Web Component. Your solution is also on point and here is a demo with your workaround: https://codepen.io/mateusz_bernacik/pen/NWzMVZE

**Comment by troyvassalotti** [comment]
Thanks @bm64, I appreciate the help! Since the fix is a small change and I noticed the "Good for beginners" label, I opened a PR with it implemented: https://github.com/highcharts/highcharts/pull/18034. Your example should help me out in the meantime.
