### ISSUE TITLE
Tooltip outside the plot area still not working

### ISSUE THREAD

**Issue by bydga** [highcharts/highcharts#1803]
I've found several issues about this, however it is still not resolved for me. I have a following chart: http://jsfiddle.net/jnnYN/ (vastly simplified to show the issue only), two pies outside the main plot area where some colums are. The tooltip renders to the plotarea while it should be aligned near the pie. Sometimes, the tooltip blinks at a correct position but on another mouse move it goes to the wrong position.

**Comment by oysteinmoseng** [comment]
Seems to work as expected with current code.
