### ISSUE TITLE
The title annotation x,y coordinates does not update

### ISSUE THREAD

**Issue by YanSatsuk** [highcharts/highcharts#18039]
#### Expected behaviour
When we moved the title annotation we need to get the actual x,y coordinates in the afterUpdate method.

#### Actual behaviour
We always get the initial x,y values. Other annotations return the actual coordinates.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/z2ofwd61/

#### Product version
Highcharts 10.3.2, Higcharts-annotations module

#### Affected browser(s)
chrome

**Comment by pawellysy** [comment]
Hi @YanSatsuk thanks for reaching out to us!
I'm afraid that this is not a bug. As you can see in this demo: https://jsfiddle.net/BlackLabel/z2ofwd61/7/
Dragging of the label does not move the point, that it is attached to. but using the x, and y properties of the label you are able to read the pixel translation of the label.
In case of any further problems feel free to reach out to us via [our support channels!](https://www.highcharts.com/blog/support/)
