### ISSUE TITLE
highcharts 10.3.2 + es-modules breaks Angular projects (`Cannot find name 'AnyRecord'`)

### ISSUE THREAD

**Issue by nunoarruda** [highcharts/highcharts#18042]
#### Expected behaviour
Successful compilation

#### Actual behaviour
Compilation fails

```bash
Error: node_modules/highcharts/es-modules/masters/highcharts.src.d.ts:9:18 - error TS2304: Cannot find name 'AnyRecord'.

9 declare const G: AnyRecord;
                   ~~~~~~~~~




** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✖ Failed to compile.
```
<img width="858" alt="Screenshot 2022-11-28 at 14 47 34" src="https://user-images.githubusercontent.com/1189149/204330152-76024b9d-de4f-4504-a313-d95d735b8841.png">

#### Live demo with steps to reproduce
Could not reproduce it with a StackBlitz demo so I'm attaching an Angular project instead: [demo-app.zip](https://github.com/highcharts/highcharts/files/10105651/demo-app.zip)

To run the demo app open it's folder on a terminal/command line, run `npm install` and run `npx ng serve -o`.

#### Product version
highcharts 10.3.2

#### Affected browser(s)
All

**Comment by bre1470** [comment]
Hello, @nunoarruda!
Thank you for the issue report. We will work on a fix.,
In the meantime you can add the following to one of your project files:
```ts
declare global {
    type AnyRecord = Record<string, any>;
}
```
Unfortunately this is not enough to fix the ESM types in the distribution, but should let you compile the project at least.
