### ISSUE TITLE
Error on a options3d <path> attribute d.

### ISSUE THREAD

**Issue by hihajdus** [highcharts/highcharts#18040]
#### Actual behaviour
Showing error with [chart.options3d](https://api.highcharts.com/highcharts/chart.options3d): 
`Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "L 497.8188798271…"`.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/9hou017s/

#### Product version
Highcharts JS v10.2.1 (2022-08-29)

#### Affected browser(s)
All

_Internal note:_
https://github.com/highcharts/highcharts/blob/b45c79feb49462293b161147799372f0e6310ea6/ts/Core/Renderer/SVG/SVGElement.ts#L1343-L1349

**Comment by hubertkozik** [comment]
Closing as completed same as duplicate: https://github.com/highcharts/highcharts/issues/19912
