### ISSUE TITLE
Gantt: missing labels when resizing width.

### ISSUE THREAD

**Issue by hihajdus** [highcharts/highcharts#18058]
#### Expected behaviour
Labels should be showing after resizing from small to large width.

#### Actual behaviour
Labels not showing after resizing from small to large width.
<img width="781" alt="Screen Shot 2022-11-30 at 12 05 51 PM" src="https://user-images.githubusercontent.com/22296099/204780371-432d4f4a-721b-4a0c-99c4-b51406ec9617.png">

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5k180f7d/

#### Product version
v10.3.2 (2022-11-28)

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
As a workaround, you can fire the `chart.redraw` method after an update- [demo](https://jsfiddle.net/BlackLabel/vnd87q4r/).
