### ISSUE TITLE
Unexpected chart visual when updating twice with the same config

### ISSUE THREAD

**Issue by hasanagh** [highcharts/highcharts#18051]
#### Expected behavior
Chart updates with the same series

#### Actual behavior
If you click on 'click me' twice which updates with the same config. you will see a different chart and when you click more you will see the line disappearing and appearing.

#### Live demo with steps to reproduce
https://jsfiddle.net/hanext/tg4bu931/31/

1. Enter the fiddle
2. Click on the Click me button
3. Notice the chart (correct visualization)
4. Click on the Click me button again
5. you will notice that the visualization changes to a wrong one, while it should have remained the same

I can see that it has to do with the old config but couldn't know what exactly.

#### Product version

Latest
#### Affected browser(s)
ALL

**Comment by karolkolodziej** [comment]
Hi @hasanagh thank you for contacting us!

In order to use the `oneToOne`  ([API](https://api.highcharts.com/class-reference/Highcharts.Chart#update)) properly, you have to declare the id for each series- [demo](https://jsfiddle.net/BlackLabel/tosj812u/).
