### ISSUE TITLE
Gantt: Disappearing data after collapsed

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#18050]
#### Expected behaviour
Having the series visible after collapsing the side menu like when the chart was first rendered.
![1](https://user-images.githubusercontent.com/39968065/204513191-452b4c7c-e151-481a-a3bf-c080eb330dda.png)

#### Actual behaviour
After expanding and collapsing, this part of the data disappears:
![2](https://user-images.githubusercontent.com/39968065/204513558-62b82960-6e0d-47df-b78b-c202b75d7af1.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/vz46y0ku/

#### Product version
v10.3.2

**Comment by karolkolodziej** [comment]
Your data config is not correct. 
There cannot be two points with the same `id`.
**`id` must be unique.**

[Working demo.](https://jsfiddle.net/BlackLabel/fz5jb2t4/)
