### ISSUE TITLE
-1 on xAxis when legends filtered out

### ISSUE THREAD

**Issue by AhmetG-Rev** [highcharts/highcharts#18066]
#### Expected behaviour
When Legend filter is used, x and y axis should be readjusted automaticaly.

#### Actual behaviour
"-1" appears on the xAxis. [-1 on xAxis](https://i.stack.imgur.com/kOlnp.png)
https://stackoverflow.com/questions/74628650/highcharts-1-on-xaxis-when-legends-filtered-out?noredirect=1#comment131732957_74628650

#### Live demo with steps to reproduce

https://jsfiddle.net/ag_test/pe9t4vxu/1/
- add a new data series to the chart (by clicking the add series button) 
- filter out the old series by clicking the legends of them.

#### Product version

 Highcharts JS v10.3.2

#### Affected browser(s)
Chrome 108.0.5359.71

**Comment by bm64** [comment]
Hello @AhmetG-Rev and thanks for reporting the issue.
It seems that the issue occurs only if the least numerous series have less than six points.

**Workaround:** 
Set `xAxis.minRange` value to be less or equal to the number of points in least numerous series: https://jsfiddle.net/BlackLabel/r9hLe150/
