### ISSUE TITLE
V11 design upgrade

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#18068]
Tick off checkboxes when the feature is ready to merge, but **do not merge** (as that will break all visual tests).

### Facelift
 - [x] General visual improvements from the design process - [PR](https://github.com/highcharts/highcharts/pull/18649)
   - [x] Palette
   - [x] Dark mode palette
   - [x] Map navigation buttons
   - [x] Map navigation buttons - try out a shape on top, [like the context menu button](https://github.com/highcharts/highcharts/blob/22fdafa152a5d10ccb9e6e194101c5ca3b04b770/ts/Extensions/Exporting/Exporting.ts#L437-L463)
   - [x] Navigator and scrollbars
   - [x] Test hover effect on choropleth, including solid border and drop shadow. Conclusion: Better to keep the choropleth color and add a darker border. Shadow doesn't work well due to box clipping.
   - [x] Try bigger color dot in tooltip
   - [x] Discuss rounded corners on other series types by default. Heatmap, treemap, sunburst?
   - [x] Test animating halo on pie slice hover
 - [x] Compatibility pack. Create a sample with how to use the legacy design.
 - [x] After the general design upgrade, go over all font sizes and round off strange font sizes (like 0.6375em) that were uses only for visual test compliance).
 - [x] Relative font size - [PR](https://github.com/highcharts/highcharts/pull/18562)
 - [x] Axis labels distance option. Currently it is hard coded to 8. [PR](https://github.com/highcharts/highcharts/pull/18646).
 - [x] Pie data labels connectors as per suggestion - [PR](https://github.com/highcharts/highcharts/pull/18575)
 - [x] Customizable rounded corners - [PR](https://github.com/highcharts/highcharts/pull/17796)
 - [x] Drop shadows - remove the legacy shadow and use SVG filter for all cases - [PR](https://github.com/highcharts/highcharts/pull/18640)

### Some minor visual changes to remember while we're at it, breaking all the visual tests
 - [x] Default datetime formats as per internal Slack discussion and [issue](https://github.com/highcharts/highcharts/issues/18576) - [PR](https://github.com/highcharts/highcharts/pull/18702)
 - [x] Hover animation (like `area-basic`). The series go so quickly into inactive, it looks like it doesn't animate.
 - [x] The pie data labels' [hard-coded number 10 pixels](https://github.com/highcharts/highcharts/blob/28f023a604cbe0efdf1d6fcfb1c4d534fbe9ed5a/ts/Series/Pie/PieDataLabel.ts#L420-L425) must be replaced by the label's actual measure.
 - [x] Legend symbol vertical position should scale with font size
 - [x] Always `linejoin: 'round'` on maps
 - [x] Retain accessible color contrast and use strikethrough on legend items for disabled elements - [PR](https://github.com/highcharts/highcharts/pull/18704)

**Comment by getzeroedin** [comment]
Hi @TorsteinHonsi,  we are a long time OEM client of Highcharts.  We've been struggling with clients who complain about the "dated" look of our charts and graphs .. they are compare us to Tableau, PowerBI, etc.  and finding those tools to provide more visually appealling charts and graphs .. Is this enhancement designed to solve that issue and bring Highcharts up to the same UI level?  Thank you

**Comment by TorsteinHonsi** [comment]
@getzeroedin Yes, that's the idea. 

But I must also emphasize that it is only the _default_ design that will get an overhaul. You can pretty much apply whatever style and look you want to Highcharts, and we expect clients to apply their own styling and company profile to the charts.

**Comment by TorsteinHonsi** [comment]
@getzeroedin In order for us to get a better idea, would you mind emailing me some screenshots of your design?
