### ISSUE TITLE
Pinch to zoom stops working after interacting with legend or title

### ISSUE THREAD

**Issue by ludvikbrodl** [highcharts/highcharts#18062]
#### Expected behaviour

The pinch to zoom should keep working as normal even after clicking on other elements on the chart.

#### Actual behaviour

The pinch to zoom stops working until the chart is double tapped

#### Live demo with steps to reproduce

http://jsfiddle.net/hL7ebz5q/6/

Reproduceable on atleast
* Android 13 Samsung S21 G5 - chrome 107.0.5304.105 and firefox 107.1.0
* Android 9 Samsung Galaxy S8 - chrome 107.0.5304.141

1) Open the jsfiddle on android,
2) Single click the title or toggle the dataline by clicking the legend item twice.
3) Try to zoom with pinch
4) No zoom is applied after the pinch is released
5) double tap inside the chart
6) pinch to zoom now works again as intended
7) click on the chart title or the legenditem twice
8) the zoom stops working again

#### Product version
https://github.highcharts.com/master/highcharts.js
and
10.3.2
#### Affected browser(s)
* Android 13 Samsung S21 G5 - chrome 107.0.5304.105 and firefox 107.1.0
* Android 9 Samsung Galaxy S8 - chrome 107.0.5304.141
* Tested on 2 Iphones, neither experience this bug in chrome or safari.

**Comment by raf18seb** [comment]
Hi @ludvikbrodl, thank you for reporting the issue!
Confirmed on S22 Ultra, Chrome 108.0.5359.61 (working fine on iPhone)

`Internal note:`
Works fine on Android in v10.2.1, broken since 10.3.0 (of course, unable to bisect on mobile)

**Comment by jacob-haskins** [comment]
This is also happening for me. Is there a workaround or fix in the works?

**Comment by karolkolodziej** [comment]
Thanks @jacob-haskins  for bringing our attention to this issue! In the upcoming weeks, we are going to take a closer look at this issue.
We will keep you posted 😉

**Comment by hubertkozik** [comment]
`Internal note:`
Bisected to eafc0873453de2df9f3ae13152708908f9e94b3b.

**Comment by hubertkozik** [comment]
Hello guys!
I have prepared a workaround for that issue. You can check it in the demo below. If you want to use it in your project now, just copy-paste the IIFE function with the plugin.

**Live demo:** https://jsfiddle.net/BlackLabel/qo0wrz6s/

**Comment by jacob-haskins** [comment]
There's an odd issue when using the proposed workaround. I'm noticing on Android, after the chart loads, the first pinch to zoom in will redraw the data to its original position, but pinching to zoom afterwards works properly.
