### ISSUE TITLE
Axis label overlaps Axis title on font change. 

### ISSUE THREAD

**Issue by JorgeSivil** [highcharts/highcharts#18063]
#### Expected behaviour

Label size will be considered on font family change, and adjustments will be made to prevent overlap with axis title.

#### Actual behaviour

Upon font change, the axis labels are overlapping the axis title. This does not happen **At least on Firefox** if the chart is drawn initially with that font (i.e. loading the chart with the target font from the start, calculates correctly and there's no overlap).  (check screenshots).

I did notice that upon changing the data table that we have (i.e changing a value) the font is re-calculated correctly.
The workaround for this was to change the "key" upon font change. However headless browser view (to take screenshots), since it is Chrome, the issue remained. Workaround for this was to do call page.reload()

#### Live demo with steps to reproduce
https://jsfiddle.net/x0ob8tL4/

#### Product version

 "highcharts": {
      "version": "10.2.1",
      "resolved": "https://registry.npmjs.org/highcharts/-/highcharts-10.2.1.tgz",
      "integrity": "sha512-4QwLQwWc0XdBHXc2Uy6IJisAUir+sgQIMyFqYZc3BD9iFSFUdllLkRyoed6y33aPb73LAMZE2qLB5SuLqFE/fg=="
    },
    "highcharts-react-official": {
      "version": "3.1.0",
      "resolved": "https://registry.npmjs.org/highcharts-react-official/-/highcharts-react-official-3.1.0.tgz",
      "integrity": "sha512-CkWJHrVMOc6CT8KFu1dR+a0w5OxCVKKgZUNWtEi5TmR0xqBDIDe+RyM652MAN/jBYppxMo6TCUVlRObCyWAn0Q==",
      "requires": {}
    },

#### Affected browser(s)

Firefox, Chrome

Chrome Initial render:

![image](https://user-images.githubusercontent.com/12187148/204874861-b3691ca0-4dfc-4be1-b1dc-9e5ddbbb9be0.png)

Chrome After toggle:

![image](https://user-images.githubusercontent.com/12187148/204874905-22fee478-c01b-4bd8-a878-c866c45ab97f.png)

Firefox Initial render:

![image](https://user-images.githubusercontent.com/12187148/204874960-348ab5c0-6b69-4a3a-9b76-213934b6cc83.png)

Firefox after toggle:

![image](https://user-images.githubusercontent.com/12187148/204874993-7b42dd85-75fd-4c2f-9a39-4575a71c776c.png)

**Comment by bm64** [comment]
Hello @JorgeSivil and thanks for reporting the issue.

It seems that getBBox method ignores loaded fonts and uses old cached values. You can use following plugin to make getBBox ignore cache: https://jsfiddle.net/BlackLabel/32gpt8L1/. Click toggle button at least twice to see results. 

Insufficient space after first render is a different issue, most likely related to #16628. In order to calculate required space correctly for axis labels and chart's text in general, you need to make sure that font resources are fully loaded beforehand.
