### ISSUE TITLE
enhancement of input range selector

### ISSUE THREAD

**Issue by krp12345** [highcharts/highcharts#18076]
https://www.highcharts.com/demo/stock/basic-line

If you check date picker in input range in above link, there are two fields, from date and to date.

If I select a date in TO DATE field in date picker, then the date is **exclusive** not **inclusive**.
if you select 23 November in TO date then data of 23 November is not shown.

So, I want to make TO DATE field inclusive. If I enter 23 November 2022 in TO date then data of 23 November 2022 should be visible in chart.

I tried **inputDateParser** callback, but event is not getting called when I select the date from date picker widget.
Let me know if further details required.

Is there any other API options then please share. Otherwise, new API option can be added, **toDateExclude** which can be boolean.

**Comment by pawellysy** [comment]
Hello @krp12345, thanks for suggesting this improvement.
@pawelfus how do you think, should it work this way?

**Comment by krp12345** [comment]
Right now, I want a fix this issue in my project. Is there any work around to solve this?

**Comment by krp12345** [comment]
Meanwhile I will think on high ideally API should be to solve such issue.

**Comment by pawellysy** [comment]
On second thought, When I think about it, the range selector describes what should be the max value displayed on the axis. 
Think about it his way: If you want the range selector to display values from 1 to 5, do you expect the value 5.5 to be visible? In my opinion no. This is the same thing here. The range selector selects the max value to be given date midnight, so when you set the range from e.g. 1 January 2022 to 10 January 2022, the date 10 January 2022 12:00, which in fact is 10,5 January won't be displayed. We need some time to think this through.

**Comment by pawelfus** [comment]
It seems `inputDateParser` indeed is not called when the date picker is enabled. I'm not sure if this is expected behaviour, seems so, but perhaps @khlieng has some insights.

Anyway, here is a workaround:

Demo: https://jsfiddle.net/BlackLabel/e0a1ns7t/

Plugin:
```js
Highcharts.wrap(
  Highcharts.RangeSelector.prototype,
  'getInputValue',
  function(proceed, name) {
    const input = name === 'min' ? this.minInput : this.maxInput;
    const options = this.chart.options.rangeSelector;
    const time = this.chart.time;

    if (input) {
      return (
        options.inputDateParser ||
        this.defaultInputDateParser
      )(input.value, time.useUTC, time, name);
    }
    return 0;
  }
)
```

Usage example:
```js
  Highcharts.stockChart('container', {
    rangeSelector: {
      selected: 1,

      inputDateParser: function(value, useUTC, time, name) {
        value = value.split(/[-]/);
        return name === 'max' ?
          Date.UTC(
            parseInt(value[0], 10),
            parseInt(value[1], 10) - 1,
            parseInt(value[2], 10),
            // add 23:59:59.999 to end date:
            23,
            59,
            59,
            999
          ) :
          Date.UTC(
            parseInt(value[0], 10),
            parseInt(value[1], 10) - 1,
            parseInt(value[2], 10)
          )
      }
    },
```
