### ISSUE TITLE
modules/draggable-points no longer works with mappoints

### ISSUE THREAD

**Issue by MightyPork** [highcharts/highcharts#18074]
#### Expected behaviour

Dragging map points.

It worked, I used it in my app and there's a demo someone posted to StackOverlow. I think it broke with version 10.

#### Actual behaviour

Mappoints can't be dragged. There is no error.

#### Live demo with steps to reproduce

https://jsfiddle.net/BlackLabel/0cq3a9h4/1/

#### Product version

latest from CDN, Highmaps JS v10.3.2 (2022-11-28)

#### Affected browser(s)

confirmed firefox and vivaldi

**Comment by bm64** [comment]
Hello @MightyPork and thanks for contacting us with the issue. 
It seems that it is broken since v9.3.0.

_Internal note:_
Unable to bisect.
