### ISSUE TITLE
How to scale and resuse Highcharts code

### ISSUE THREAD

**Issue by tjuandev** [highcharts/highcharts#18072]
Strategies to scale Highcharts code. I work at a Dashboard for the enegry production industry, and they have hundreds of different charts types, and the main challenge is to scale it well, improving chart reusability and so on. I wonder if you can help me sending insights to deal with this problem.

**Comment by pawellysy** [comment]
Hi @tjuandev, Sorry to inform you, but We use GitHub as a bug/feature tracking tool, and your question refers to none of that. For further information, please reach out to us either via our sales department which you can get by emailing us  sales@highsoft.com or if you have some technical questions, you can contact us [available support channels](https://www.highcharts.com/blog/support/), where our support engineers are more than happy to help you with tweaking the chart's configuration to your needs. Thanks!
