### ISSUE TITLE
Vertical axis tick (incorrectly) changes when the chart is updated

### ISSUE THREAD

**Issue by matthewzach-wk** [highcharts/highcharts#18086]
#### Expected behaviour
Tick marks on vertical axis should calculate the same way whether its a create vs an update

#### Actual behaviour
The vertical axis tick interval dynamically and incorrectly changes when the chart is updated. This issue only presents itself when:

- The legend is on top or bottom
- There are 2 axises
- The axis max value and step size are set to auto

#### Live demo with steps to reproduce
https://jsfiddle.net/wsrgq3u8/5/

See video example. Tick marks calculated different upon update.

https://user-images.githubusercontent.com/50838432/205689351-1292d362-1bfd-41ec-ba11-7e4ed181643d.mov

#### Product version
v10.x
v9.x
v6.x

**Comment by karolkolodziej** [comment]
Hi @matthewzach-wk, thank you for reporting this issue.

Indeed, even without changing the config after redrawing ticks are different - [simplified demo.](https://jsfiddle.net/BlackLabel/mcd0h31t/)

_Internal note:_ 
The issue is only visible with multiple axes.
