### ISSUE TITLE
Heatmap labels scaling

### ISSUE THREAD

**Issue by MaxPiccinno** [highcharts/highcharts#18081]
#### Expected behaviour
When using a Heatmap chart with dynamic numeric y-axis categories, I expect labels to be show correctly, or at least coherently trimmed when the rows are too many for chart's height.

#### Actual behaviour
When the maximum number of rows is exceeded, if both the first and last numeric labels are even or odd, only even/odd labels are shown. The bug presents when the first label is even and the last is odd, or viceversa: the last labels get truncated and the length of categories array is shown in its place.

#### Live demo with steps to reproduce
[Live demo](https://jsfiddle.net/g3o6ycqe/6/)

The demo shows an example with an odd starting label and an even ending label

#### Product version
Highcharts v10

#### Affected browser(s)
Chrome, Firefox, Safari

**Comment by pawellysy** [comment]
Hello, @MaxPiccinno thanks for contacting us. 
In my opinion, everything works correctly. The `category` axis type is for displaying some categories, which are not numerical, but some values, where order does not matter. ([READ MORE HERE](https://www.highcharts.com/docs/chart-concepts/axes#what-axis-type-should-i-use))

For this type, I'd use regular numerical axis type, and change the labels with `axis.labels.format` https://jsfiddle.net/BlackLabel/sgytw2vL/

For any more questions feel free to contact us [via our support channels](https://www.highcharts.com/blog/support/), where our support engineers will help you to tweak the chart's config to match your preferences.
