### ISSUE TITLE
Scatter chart is heavy on the latest Safari version

### ISSUE THREAD

**Issue by ayumin0109** [highcharts/highcharts#18089]
#### Expected behaviour
Scatter chart works fine with about 500 or more data points on the latest Safari version.

#### Actual behaviour
Scatter chart drawing and scaling is heavy on the latest version of Safari.
Chrome, Firefox and Microsoft Edge don't have this issue.
This issue occurs when drawing about 500 or more data points.
I noticed this issue on November 1, 2022.

#### Live demo with steps to reproduce
https://jsfiddle.net/ps51q4wy/3/

#### Product version
Highcharts version 9.0.1

#### Affected browser(s)
Safari 16.1(17614.2.9.1.13, 17614)

**Comment by karolkolodziej** [comment]
Hi @ayumin0109, thank you for contacting us.

I also can see that issue in Version 15.5 (17613.2.7.1.8) altho I'm not sure if that is related to Highcharts.
In my opinion, this has to do with how Safari handles SVG elements.

As an improvement, you can disable labels- [demo](https://jsfiddle.net/BlackLabel/1sxyvcjz/).

**Comment by karolkolodziej** [comment]
In my opinion, that is the Safari issue and should be solved there
As you can see in this demo where there is no Highcharts calculation the rendering takes a lot of time in that browser- [demo](https://jsfiddle.net/BlackLabel/pn79xda0/).

**Comment by ayumin0109** [comment]
I’m sorry for the late reply.
Thank you for your demo.
I'll contact Safari.
