### ISSUE TITLE
Heikin-Ashi wrong candles color

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#18088]
#### Expected behaviour
Candles with close lower than open should be colored as red (or any "down color").

#### Actual behaviour
Some candles have their color mixed.

#### Live demo with steps to reproduce
Take a look at the Nov 7 candle
https://jsfiddle.net/BlackLabel/Lj5whnuc/

#### Product version
Highstock + Heikin-Ashi 10.3.2 (latest)

**Comment by karolkolodziej** [comment]
_Internal note:_ 
The wrong color is set here:
https://github.com/highcharts/highcharts/blob/9ab8a3ce769736033078e1c9e8015fb011679b5d/ts/Series/Candlestick/CandlestickSeries.ts#L106-L107
Also, way the color is set needs to be checked:
https://github.com/highcharts/highcharts/blob/9ab8a3ce769736033078e1c9e8015fb011679b5d/ts/Series/Candlestick/CandlestickSeries.ts#L102

Demo: https://jsfiddle.net/BlackLabel/un2aft0x/

**Comment by Dhan3777** [comment]
@karolkolodziej @kamil-musialowski is this fixed ?

**Comment by karolkolodziej** [comment]
@Dhan3777 it is not fixed yet but we will take a look at that soon!

**Comment by Dhan3777** [comment]
@karolkolodziej @kamil-musialowski 
Hi, is fix released for this?

**Comment by karolkolodziej** [comment]
The issue is fixed and available on the `master` branch right now.
Within a couple of weeks, we are going to release a new version with that fix.

**Comment by Dhan3777** [comment]
@karolkolodziej is it fixed and available ? can't find in V10.3.3 CHANGE LOGS

**Comment by kamil-musialowski** [comment]
@Dhan3777 Sure, it is fixed and ready to use. But since it's a Highstock bugfix, you need to look at the Highcharts Stock changelog - https://www.highcharts.com/changelog/#highcharts-stock-v10.3.3

**Comment by Dhan3777** [comment]
@kamil-musialowski thank you.
