### ISSUE TITLE
Area range chart: zoom in to see markers then reset zoom crash the chart

### ISSUE THREAD

**Issue by Ptitpim** [highcharts/highcharts#18080]
#### Expected behaviour

Zooming in then zooming out in an area range chart should not cause chart crash.

#### Actual behaviour

I have this issue in my React project and I've discovered that this issue can be reproduced in the official [Highcharts demo page](https://www.highcharts.com/demo/arearange) and in the [jsfiddle demo](https://jsfiddle.net/0dhkmgwa/).

In an **area range chart** with a large series of points, **the markers should not appear, it's important** (example on: [Highcharts demo page](https://www.highcharts.com/demo/arearange))

![arearange_display](https://user-images.githubusercontent.com/174432/205310916-8f1b4065-1471-4491-b0d0-f1556faeb89b.png)

select a part of the chart to **zoom in until you show the markers** (blue points):

![zoomed](https://user-images.githubusercontent.com/174432/205311748-918672cc-1d83-47b8-98e3-f82b5eb991fa.png)

then **click the "Reset zoom" button** on the top right corner to zoom out.
At this step no problem, but if you try to select again a part of the chart to zoom in, or in my case if I navigate to an other application page (through React Router), you will have **errors in the Devtools console**, like:

```
highcharts.src.js:9858 Uncaught TypeError: Cannot read properties of undefined (reading 'isSVG')
    at a.destroy (highcharts.src.js:9858:38)
    at highcharts.src.js:25846:35
    at Array.forEach (<anonymous>)
    at k.destroyElements (highcharts.src.js:25845:17)
    at a.generatePoints (highcharts.src.js:37220:29)
    at a.translate (highcharts.src.js:37409:17)
    at a.redraw (highcharts.src.js:38396:17)
    at highcharts.src.js:30939:25
    at Array.forEach (<anonymous>)
    at a.redraw (highcharts.src.js:30937:17)
```

and then if you move your mouse over the chart, you will have **tons of errors in the console**, like:

```
highcharts.src.js:9104 Uncaught TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at a._defaultSetter (highcharts.src.js:9104:17)
    at a.<anonymous> (highcharts.src.js:9547:29)
    at I (highcharts.src.js:1309:21)
    at a.attr (highcharts.src.js:9525:21)
    at a.removeClass (highcharts.src.js:10322:24)
    at k.setState (highcharts.src.js:26581:25)
    at b.setState (highcharts-more.src.js:585:17)
    at highcharts.src.js:28233:29
    at Array.forEach (<anonymous>)
    at a.runPointActions (highcharts.src.js:28231:21)
```

#### Live demo with steps to reproduce

You can reproduce in the [Highcharts demo page](https://www.highcharts.com/demo/arearange) or in the [jsfiddle demo](https://jsfiddle.net/0dhkmgwa/) or in the codepen example page.

The fact that you have to display a chart with a lot of points (so Highcharts don't display marker tiny points) is important. If you try with a short series of points, Highcharts will display markers, then you can zoom in and zoom out, you will not encounter this issue.

#### Product version

- highcharts: 10.3.2
- highcharts-react-official: 3.1.0
- react 17.0.2
- react-dom: 17.0.2

#### Affected browser(s)

Chrome 107.0.5304.110 (Build officiel) (arm64) for this demo screenshots, but others browsers like Firefox are affected.

**Comment by bm64** [comment]
Hello @Ptitpim and thanks for reporting the issue.

_Internal note:_ 
Bisected to: b84e453a78317fb0df03d63fe86db8f463120de5
FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Thanks! Will you investigate, @bm64 ?
