### ISSUE TITLE
stemColor missing from online API Reference

### ISSUE THREAD

**Issue by GaryGen** [highcharts/highcharts#18094]
#### Expected behaviour
series.boxplot supports stemColor, but this is not listed in the online API Reference

#### Live demo with steps to reproduce
https://api.highcharts.com/highcharts/series.boxplot
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/box-plot-styling/

#### Product version
Highcharts 10.3.2

**Comment by pawellysy** [comment]
Hello @GaryGen, Thanks for reporting this issue!
