### ISSUE TITLE
Duplicate empty labels rendered.

### ISSUE THREAD

**Issue by henning-kvinnesland** [highcharts/highcharts#18096]
#### Expected behaviour

Only my specified custom-rendered labels should be visible.

#### Actual behaviour

![image](https://user-images.githubusercontent.com/39047273/206053603-00b1cf7c-14d0-47dd-80f9-11333c906353.png)
Small empty labels with no-tooltip class are added to the highcharts-container.

#### Product version
10.3.x

#### Affected browser(s)

Chrome 108.

**Comment by pawellysy** [comment]
Hello @henning-kvinnesland, thanks for creating this ticket.
Could you share jsfiddle demo, where the issue is reproduced, and elaborate on what the issue exactly is?
Thanks!

**Comment by henning-kvinnesland** [comment]
After upgrading to 10.3.x a lot of extra empty dom-elements are added. Every custom legend we render gets a little empty box beside it. Turning of custom-rendering for legends doesn't help, but downgrading does. Our project is rather huge, do you perhaps have a simple jsfiddle with some graph-data where I could start?

**Comment by henning-kvinnesland** [comment]
It magically fixed itself. Good times!
