### ISSUE TITLE
Column Chart - Specifying X value has different effect when only 1 category

### ISSUE THREAD

**Issue by dustyjewett** [highcharts/highcharts#1811]
Use Case: Overlapping the series to better correlate connected values.

Normal / Working / Expected case: (# of Categories > 1)
Setting the x value properly re-positions the column exactly as expected.

Broken Case # 1 (# of Categories == 1)
X Value no longer re-positions correctly.  In order to get the same visual representation, the offset must be reduced by an order of magnitude. 

Broken Case # 2 (# of Categories == 1 && yAxis.max == 0)
X Value is even more incorrect than before. In order to get the same visual representation, the offset must be reduced by half again. (we use yAxis.max in order to ensure that the category is centered in the chart, otherwise it's offset, as seen in BC1)

In the included fiddle, The x value has been modified to give (approximately) the same visual presentation. If you set the x value to the 'correct' value, the column renders very far off screen. 

http://jsfiddle.net/JjzCg/1/

**Comment by TorsteinHonsi** [comment]
This seems to work well with v6.1, please comment if not.
