### ISSUE TITLE
Sunburst chart: central data label width is too short

### ISSUE THREAD

**Issue by cebamps** [highcharts/highcharts#18116]
#### Expected behaviour
In the central disk of a sunburst chart, the data label width should be able to almost fill up the full diameter of that disk.

#### Actual behaviour
The central data label is too narrow.

I could also not manage to set its width manually through dataLabels style options. It is not so clear to me whether [`series.sunburst.data.dataLabels.style`](https://api.highcharts.com/highcharts/series.sunburst.data.dataLabels.style) or [`series.sunburst.levels.dataLabels.style`](https://api.highcharts.com/highcharts/series.sunburst.levels.dataLabels.style) should be able to override that width.

Here is a screenshot from the demo. Clearly, there is enough space to display "the world", but the label is constrained to roughly half of the available width:
![image](https://user-images.githubusercontent.com/12797742/206656119-58144628-774b-4a9f-b7b1-20e33435c13b.png)

From looking at the [code](https://github.com/highcharts/highcharts/blob/v10.3.2/ts/Series/Sunburst/SunburstSeries.ts#L121), the cause appears to be that rendering for this central data label follows the same logic as other non-central points. Though while the children compute their label width in reference to the radius of the point shape, the central data label can use *twice* that radius, since it is a full circle after all.

#### Live demo with steps to reproduce
https://jsfiddle.net/uj43fnp2/

#### Product version
Highcharts 10.3.2

#### Affected browser(s)
Firefox, Chrome.

**Comment by pawellysy** [comment]
Hi @cebamps, thanks for reporting a bug!
There seems to be a bug, where you can't overwrite the option for width (Apart from the fact, that it is wrongly calculated here) https://github.com/highcharts/highcharts/blob/8ebdfd9fd9d8b3391b26cf9985ae045f15251a64/ts/Series/Sunburst/SunburstSeries.ts#L202

There unfortunately, there is no possible workaround at the moment :( 
But we hope to fix this soon! Thanks again!
