### ISSUE TITLE
Series refers to many xAxis

### ISSUE THREAD

**Issue by mapapuche** [highcharts/highcharts#18118]
Hello,

We are using spline graph : https://api.highcharts.com/highcharts/series.spline.xAxis

In our code we have 2 xAxis: 
```
    xAxis: [
      {
        categories: formattedValues,
      },
      {
        categories: axisFiltered,
      },
    ],
```

My series : 
```
    series: [
      {
        name: `Satisfaction`,
        data: formattedValues,
      },
      {
        name: `Bottom`,
        data: formattedBottomValues,
      },
      {
        name: `Top`,
        data: formattedTopValues,

      },
      {
        name: `$Average`,
        data: formattedAverageValues,
      },
    ],
```

Into our series i want to refer to the 2 xAxis and not only one. In documentation it says we can refer to only one xAxis by series : 
![image](https://user-images.githubusercontent.com/64193148/206679990-f0efcc6f-3db3-4039-88f4-889bbac11d14.png)

For example in my series i would like to do that : 
```
    series: [
      {
        name: `Satisfaction`,
        data: formattedValues,
        xAxis: [0, 1]
      },
      {
        name: `Bottom`,
        data: formattedBottomValues,
        xAxis: [0, 1]
      },
      {
        name: `Top`,
        data: formattedTopValues,
       xAxis: [0, 1]
      },
      {
        name: `$Average`,
        data: formattedAverageValues,
        xAxis: [0, 1]
      },
    ],
```

But the problem is currently we are allow only to do this : 

```
    series: [
      {
        name: `Satisfaction`,
        data: formattedValues,
        xAxis: 1
      },
      {
        name: `Bottom`,
        data: formattedBottomValues,
        xAxis: 0
      },
      {
        name: `Top`,
        data: formattedTopValues,
       xAxis: 1
      },
      {
        name: `$Average`,
        data: formattedAverageValues,
        xAxis: 0
      },
    ],
```

The problem with that is, when i click on the legend to hide a serie, it will hide the xAxis associated. But me i don't want this xAxis to be hide because it's usefull for other series.

**Comment by pawellysy** [comment]
Hi @mapapuche, sorry to inform you, but we treat our GitHub as a feature/bug tracking tool. Your question will be answered in the SO thread that you created: https://stackoverflow.com/questions/74741820/hightchart-series-refers-to-many-xaxis
Thanks!
