### ISSUE TITLE
softMin causes maxPadding to be ignored for certain cases

### ISSUE THREAD

**Issue by awonihlgard** [highcharts/highcharts#18110]
#### Expected behaviour

There should be a padding between the serie maximum and the chart maximum that can be controlled with `maxPadding`

#### Actual behaviour

`maxPadding` is not respected, causing the serie to end up to close to the chart edge

#### Live demo with steps to reproduce
https://jsfiddle.net/zjx86fvm/50/

- If `softMin` is replaced with `min`, the padding is added
- If the series have a higher variance (e.g replace the first data point with 220), the padding is added

#### Product version
Highcharts 10.2.0

**Comment by karolkolodziej** [comment]
Hi @awonihlgard, thank you for reporting this issue.

_Internal note:_
The part responsible for calculating the min/max from softMin/softMax
https://github.com/highcharts/highcharts/blob/de6aa1866847947b8a8d2fc6753e48a1b997e9c7/ts/Core/Axis/Axis.ts#L1732-L1774 
is run after the part where the padding is added.

Simply reverting that order ruins some regression tests.
Needs deeper analysis.

**Comment by awonihlgard** [comment]
Any progress on this?

**Comment by karolkolodziej** [comment]
@awonihlgard We started working on that, please follow the issue to get more updates on the fix.
