### ISSUE TITLE
Borders are applied to data label even if their width is default (0)

### ISSUE THREAD

**Issue by kluvin** [highcharts/highcharts#18127]
When `plotOptions.series.dataLabels` has a `borderColor` and a `backgroundColor`. The`borderWidth` is the default, `0`.

#### Expected behaviour
Does not show borders on data labels.

#### Actual behaviour
Shows borders on data labels.

#### Live demo with steps to reproduce
MRE: https://jsfiddle.net/kluvin/2hdnsbvu/5/
With maps: https://jsfiddle.net/kluvin/m7c0nfzL/14/

#### Product version
10.3.2 -->
#### Affected browser(s)
Chrome, Firefox

**Comment by karolkolodziej** [comment]
Hi @kluvin thank you for reporting this issue!

_Internal note:_
Bisected to: https://github.com/highcharts/highcharts/commit/53521c872cd805097e9b328b37c82650c5674f42
FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Thanks! I think the best solution is just to add the default `dataLabel.borderWidth` as code, not just a free floating doclet:

```ts
        /**
         * The border width in pixels for the data label.
         *
         * @sample {highcharts} highcharts/plotoptions/series-datalabels-box/
         *         Data labels box options
         *
         * @type      {number}
         * @default   0
         * @since     2.2.1
         * @apioption plotOptions.series.dataLabels.borderWidth
         */
        borderWidth: 0,
```
