### ISSUE TITLE
Annotation dragging on windows touch devices not working

### ISSUE THREAD

**Issue by PadWorks** [highcharts/highcharts#18122]
#### Expected behaviour
Moving annotations should work on all touch devices.

#### Actual behaviour
Dragging annotations works on mobile touch devices Android and IOS based. Unfortunately, the touch events for dragging annotations on windows are ignored. (touch on notebook using google chrome)

#### Live demo with steps to reproduce
Example here: https://jsfiddle.net/BlackLabel/9s18dLjg/

#### Product version
v10.3.2

#### Affected browser(s)
Chrome on Windows

**Comment by pawellysy** [comment]
Hi @PadWorks, thank you for reporting a bug!

**Comment by PadWorks** [comment]
@pawellysy  For us, problem solving would be important. Until when is the problem fixed?

**Comment by bm64** [comment]
@PadWorks could you provide us with some additional information like browser and OS version?

**Comment by DJTechnoo** [comment]
_Internal note:_
Confirmed this isn't working for windows touch device since it was added in 7.0.0 https://jsfiddle.net/dyxgka9r/

**Comment by PadWorks** [comment]
@bm64 Platform-independent, Affects all Windows versions and Chrome-Browsers
@DJTechnoo What is the current status in this regard?

**Comment by DJTechnoo** [comment]
@PadWorks  As for the current status: we have moved it in our to-do list very recently

**Comment by hubertkozik** [comment]
Hello guys!
I have prepared a workaround for that issue. You can check it in the demo below. If you want to use it in your project now, just copy-paste the IIFE function with the plugin.

**Live demo:** https://jsfiddle.net/BlackLabel/w3krgq1t/
