### ISSUE TITLE
Strange update animation for Area Spline chart

### ISSUE THREAD

**Issue by ChrisMakrutzki** [highcharts/highcharts#18133]
#### Expected behaviour
When updating a series from one data point to multiple data points the expected area animation goes from left to right. This is already the case for updating series which previously had multiple data points.

#### Actual behaviour
The update animation for one data point to multiple is inconsistent. In this case the area animation goes from top left to bottom right.

#### Live demo with steps to reproduce
https://jsfiddle.net/ChrisMakrutzki/dyq5Lokp/32/

#### Product version
Highcharts 10.3.2

#### Affected browser(s)
All major browsers

**Comment by karolkolodziej** [comment]
Hi @ChrisMakrutzki thank you for reporting that issue!

_Internal note:_ 
When multiple points are declared (even overlapping) the animation looks like the first one- [demo](https://jsfiddle.net/BlackLabel/0rfm6ehp/).

Animation is correct for the `area` series (can be used as a workaround) - [demo](https://jsfiddle.net/BlackLabel/yo5wqv48/).
