### ISSUE TITLE
Map border width not reset after hover state change to inactive

### ISSUE THREAD

**Issue by FusionSnowball** [highcharts/highcharts#18137]
#### Expected behaviour
On a map where the borderWidth is set on hover state, the borderWidth should be set on hover and it should revert to the original width when no longer hovering over a country.

#### Actual behaviour
The hover borderWidth remains set after moving away from a country. Border colours when applied via the same method are unset when no longer hovering, the same behaviour is expected of borderWidth..  

#### Live demo with steps to reproduce
https://jsfiddle.net/n0hrswpf/8/ 

#### Product version
10.3.2 (worked in 8.2.2)

#### Affected browser(s)
Chrome 108

**Comment by hubertkozik** [comment]
Hi @FusionSnowball! Thank you for reporting this issue.

As a workaround for now you can overwrite HC core function as in the demo below (inside IIFE function).

**Demo:** https://jsfiddle.net/BlackLabel/2xg40Luf/

**Comment by KacperMadej** [comment]
There is no ETA for the fix at this moment but we are currently aiming at the closest (or the very next after it) release.
