### ISSUE TITLE
Polar char - min/max value

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1813]
When min/max values are set, and range is smaller than data points value, points are drawn out of plotarea.

http://jsfiddle.net/tvsw2/

**Comment by kzoon** [comment]
I still need to apply Torsteins workaround, each time I implement a new Highcharts version. 
Any chance of fixing this issue in the HC code itself?

**Comment by TorsteinHonsi** [comment]
Will do, thanks for your patience!
