### ISSUE TITLE
Some data labels not displayed in the polar chart

### ISSUE THREAD

**Issue by Vazonik** [highcharts/highcharts#18147]
#### Expected behaviour
All data labels displayed

#### Actual behaviour
Some data labels are not displayed in the polar chart

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/pakt9gjh/

#### Product version
Highcharts v10.3.0+
(Regression, it worked until v10.2.1)

**Comment by bm64** [comment]
Thanks @Vazonik for reporting the bug!

_Internal note:_
Bisected to 00c892ddfececd842ad2bca83cca818a719d9b7c
