### ISSUE TITLE
Column chart with categories and unsorted data does not draw all points properly 

### ISSUE THREAD

**Issue by skrtheboss** [highcharts/highcharts#18140]
#### Expected behaviour
Highcharts should render all data points, no matter the sorting.

#### Actual behaviour
Highcharts does not render all data points.

#### Live demo with steps to reproduce
https://jsfiddle.net/aq04hjw8/2/

#### Product version
10.3.2

#### Affected browser(s)
All

**Comment by bm64** [comment]
Hello @skrtheboss and thanks for reporting the issue!

**Comment by bm64** [comment]
Hello @Angelizo1 

I'm not able to recreate the issue. All points are visible here. You might want to set `findNearestPointBy: 'xy'` options to make navigation to points with same x easier: https://jsfiddle.net/BlackLabel/sduezfy8/

**Comment by Angelizo1** [comment]
Hello @bm64 

First thanks for responding.

Sorry perhaps I did not explain myself properly. What I meant to say is that they aren't visible at first glance when the mouse isn't on the graph, basically you have to hover over the line to see each point one at a time when you move around it.

But that's not the behavior I want. What I really want is for them to be displayed all the time at once, and to show me the tooltip of each one of them as I hover over them.

**Comment by Angelizo1** [comment]
@bm64  This is exactly what I want. Thanks a lot Mateusz, life saving tip : )
