### ISSUE TITLE
Embed Highcharts on a Confluence Cloud Page does not work

### ISSUE THREAD

**Issue by pascaloberle** [highcharts/highcharts#18151]
#### Expected behaviour
Chart is displayed fine on Confluence Cloud Page
#### Actual behaviour
When I try to embed a Highcharts on a Confluence Cloud Page it doesn't work and will produce such errors in the logs
![image](https://user-images.githubusercontent.com/6572717/207720056-26ff2031-b19e-4705-96e4-d1bb5e453bea.png)

#### Live demo with steps to reproduce
Access Confluence Cloud website here to see the issue live https://intheflowtrading.atlassian.net/wiki
![image](https://user-images.githubusercontent.com/6572717/207720213-8c38232f-8d4c-4b41-9457-1876cddbbf98.png)

Code used that renders well if I used it in a local .html file.
```
<!DOCTYPE html>
<html>

<head>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/data.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/stock/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const chart = Highcharts.chart('container', {
                chart: {
                    type: 'bar'
                },
                title: {
                    text: 'Fruit Consumption'
                },
                xAxis: {
                    categories: ['Apples', 'Bananas', 'Oranges']
                },
                yAxis: {
                    title: {
                        text: 'Fruit eaten'
                    }
                },
                series: [{
                    name: 'Jane',
                    data: [1, 0, 4]
                }, {
                    name: 'John',
                    data: [5, 7, 3]
                }]
            });
        });
    </script>
    <style>
        #container {
            min-width: 310px;
            max-width: 600px;
            height: 400px;
            margin: 0 auto;
        }
    </style>
</head>

<body>
    <div id="container" style="width:100%; height:400px;"></div>
</body>

</html>
```

#### Product version
Latest version from https://code.highcharts.com/

#### Affected browser(s)
Chrome, Firefox

**Comment by pascaloberle** [comment]
`<!DOCTYPE html>
<html>

<head>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/data.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/stock/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const chart = Highcharts.chart('container', {
                chart: {
                    type: 'bar'
                },
                title: {
                    text: 'Fruit Consumption'
                },
                xAxis: {
                    categories: ['Apples', 'Bananas', 'Oranges']
                },
                yAxis: {
                    title: {
                        text: 'Fruit eaten'
                    }
                },
                series: [{
                    name: 'Jane',
                    data: [1, 0, 4]
                }, {
                    name: 'John',
                    data: [5, 7, 3]
                }]
            });
        });
    </script>
    <style>
        #container {
            min-width: 310px;
            max-width: 600px;
            height: 400px;
            margin: 0 auto;
        }
    </style>
</head>

<body>
    <div id="container" style="width:100%; height:400px;"></div>
</body>

</html>`

**Comment by karolkolodziej** [comment]
Hi @pascaloberle!

Please load the script with Highcharts at the very top of the page similar to how you load other scripts and let me know if this resolves your issue.

**Comment by pascaloberle** [comment]
Hi @karolkolodziej thanks for your prompt reply on this!
Unfortunately the issue still happens even at the top of my page.
Feel free to let me know if there is anything else I could try to make the script loading, right now it just renders blanked 

Thanks again for all the help on this front 👍 
Best Regards

**Comment by karolkolodziej** [comment]
As I look into that right now there is no such error.
For me, it doesn't look like a bug, but rather a problem with implementation.
If this issue is still visible, please [contact our support team](https://www.highcharts.com/blog/support/) in order to find a solution.
