### ISSUE TITLE
Custom markers don't work with jQuery v3.6.0

### ISSUE THREAD

**Issue by SteveF311** [highcharts/highcharts#18152]
#### Expected behaviour

I reported this issue to Highcharts Support via email back in late Jan/early Feb 2022. In working with Karol Kołodziej, we weren't able to find a solution. The SVGRenderer used to generate custom markers doesn't work with jQuery v3.6.0. The proposed solution was to add SVGRenderer capability to the C# wrapper (I use the C# wrapper to build the Highcharts object, but then have to use the following JavaScript after DOM ready to replace the default Highcharts markers with alphabetical ones. For now, I'm stuck with jQuery v2.2.4 because I need custom, alphabetical markers rather than the default shapes.

    //create custom symbols in Highcharts based on markerlibrary (a0-a25 for the 26 letters of the alphabet)
    //https://api.highcharts.com/highcharts/plotOptions.series.marker.symbol
    //https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-marker-symbol/
    for (var i = 0; i < a.length; i++) {
        eval("Highcharts.SVGRenderer.prototype.symbols[b[i]] = function(x,y,w,h) { return [" + a[i] + "];}");

        if (Highcharts.VMLRenderer) {
            Highcharts.VMLRenderer.prototype.symbols[b[i]] = Highcharts.SVGRenderer.prototype.symbols[b[i]]
        }
    }

#### Actual behaviour

The legends do not contain the alphabet markers after upgrading to jQuery v3.6.0 (using Highcharts JS v9.3.2 and Highsoft.Highcharts .net v9.2.2.2).

#### Live demo with steps to reproduce

It's not possible to recreate in jsFiddle exactly because the problem is related to order of operations. When using the C# .net Highcharts wrapper, one must do any SVGRenderer work in JS. When upgrading to jQuery v3.6, the Highcharts graph is built and then the SVGRenderer code executes, which means the custom markers are not implemented. You can mimic this behavior by moving the makeAlphabetMarkers in the below fiddle to before the Highcharts code (works as expected) and then after the Highcharts code (doesn't work). We either need a solution that ensures the Highcharts code is executed after DOM ready, or we need access to the SVGRenderer in the C# wrapper so we can move that code from JS to C# (or we need Highcharts to natively support alphabetical markers and not just simple shapes).

https://jsfiddle.net/SteveF1/zkon8a5m/2/

#### Product version

Highcharts JS v9.3.2 and Highsoft.Highcharts .net v9.2.2.2

#### Affected browser(s)
Chrome, Edge

**Comment by karolkolodziej** [comment]
Hi @SteveF311!

Are you able to prepare a minimal .NET project so we can experiment and understand better what can be done?

**Comment by SteveF311** [comment]
Hi @karolkolodziej 

I spent several hours today putting together a .net project that demonstrates the issue. I'm still learning GitHub and not sure how to get the solution to you. I tried attaching a zip of the solution files, but it was 76 MB (max allowed is 25 MB). So, I deleted all the package files (you can get from NuGet using the information in the packages.config file). Please advise if there's a better way.

[HighCharts_Test.zip](https://github.com/highcharts/highcharts/files/10263557/HighCharts_Test.zip)

You can debug the HighCharts_Test.aspx file and see the problem when the head uses jQuery v3.0.0+ (and no problem when using jQuery v2.2.4). I suspect the problem is order of operations...new jQuery executes the DOM ready stuff to trigger the SVGRenderer before the C# code has created the Highcharts object, thus no markers with new jQuery. I cannot impact the order of operations until the SVGRenderer capability is exposed in the .net wrapper.

`<head runat="server">
    <title>Highcharts Test</title>
    <%--<script type="text/javascript" src="Scripts/jquery-2.2.4.min.js"></script>--%>
    <script type="text/javascript" src="Scripts/jquery-3.6.1.min.js"></script>
</head>`

**Comment by brofixo** [comment]
Hi @SteveF311,

I started analyzing your project.

Where exactly are you using jQuery, because if I comment both jQuery scripts then  both charts render anyway?

Daniel

**Comment by SteveF311** [comment]
Hi @brofixo,

We use jQuery throughout the real solution, but to create a minimal .net project, I left all but the DOM ready part out of the HIghcharts_Test.js file. We use jQuery for handling our dropdown menus, HighCharts events, jqGrid tables, etc. You'll have to either add more jQuery stuff or consider it a requirement. When I tried upgrading to jQuery v3.0+, I found the SVGRenderer no longer compatible. After going back and forth with Highcharts Support for a while, they couldn't find a solution. The only idea we came up with was to enable SVGRenderer via the .net wrapper.

Thanks,

Steve

**Comment by SteveF311** [comment]
Hi @brofixo,

Please confirm you see my above message and have no further questions. I'd like a sense of when you think you might have a solution.

Thanks,

Steve

**Comment by brofixo** [comment]
@SteveF311 I'm gonna to take care of that issue in 2 weeks from now. If you have other issues please let me know.

**Comment by TorsteinHonsi** [comment]
@SteveF311 and @brofixo I don't think this is a Highcharts issue, but rather an issue with the implementation. The fiddle, https://jsfiddle.net/SteveF1/zkon8a5m/2/, shows that everything is working from Highcharts' end. What you need to do is to find out where to run the `makeAlphabetMarkers()` code after Highcharts is loaded into the web page, but before the charts are initialized. Which is a matter of your website architecture, not Highcharts per se.

**Comment by SteveF311** [comment]
OK, but can you guys please provide input on how to do that? Is there an event in the C# wrapper where I should call makeAlphabetMarker() instead of in doc ready?

I've been doing it this way for 10 years and it wasn't an order of execution problem until jQuery v3+, so I could use some guidance. The original plan per Highcharts support (see above) was to add SVGRenderer capability to the C# wrapper.

**Comment by SteveF311** [comment]
@TorsteinHonsi @brofixo Any updates?

**Comment by brofixo** [comment]
@SteveF311 I've started working on this, so we should have a solution for this case in coming days. I'll keep you informed.

**Comment by TorsteinHonsi** [comment]
@SteveF311 As I said, it depends on you implementation. But right after the script tags is a safe bet: https://jsfiddle.net/highcharts/v3jf97c4/1/
