### ISSUE TITLE
"arearange" Series Partially Disappears on Hover

### ISSUE THREAD

**Issue by chunick** [highcharts/highcharts#18157]
#### Expected behaviour
A series should be completely visible when hovered over.

#### Actual behaviour
The series partially disappears when hovered over.

#### Live demo with steps to reproduce
https://jsfiddle.net/ogv02z7L/

![bug](https://user-images.githubusercontent.com/46545800/207917468-ff07f0a1-ffa9-4cea-ba55-015b721a4060.gif)

The issue seems to only happen under the following conditions:

- The chart type is "arearange"
- The yAxis min is 0
- The y values are very small, e.g., `2.0000000391987203e-10 `

#### Product version
Highstock JS v10.3.2

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hello @chunick, thanks for reaching out to us. Unfortunately, I see your example as a big edge case. You are creating the arearange series, which is supposed to show the difference between 2 values, and the values you defined are the same. To use correctly, use a different series type, e.g. line: https://jsfiddle.net/BlackLabel/qjL6m4dw/1/

What do you think @TorsteinHonsi?

**Comment by TorsteinHonsi** [comment]
@pawellysy I think it has to do with the very small scale of the data. But you should spend some time debugging it still, so we understand it better. If it fails deliberately, for example because JavaScript can't handle computation on this scale, we should either fix it or throw a warning.

**Comment by chunick** [comment]
@pawellysy The issue still exists if the difference between the 2 values is non-zero, but for the sake of the demo it is more noticeable when there is no shaded area (the line flickers, but not the filled section). As for the other 2 conditions to reproduce the bug, It would be nice to let the yAxis min remain configurable, and to display all values in the chart no matter how large or small.

**Comment by pawellysy** [comment]
Hi @chunick, could you share the config, where the issue is reproduced when the difference is not 0? Thanks!

**Comment by chunick** [comment]
@pawellysy Sure, here's an updated example https://jsfiddle.net/L1hmbxdc/. If I increase the line width to 3 like in the fiddle where the series type is 'line', the sections that were flashing on hover are permanently invisible.

![image](https://user-images.githubusercontent.com/46545800/209836380-bddfbddc-f13a-4234-a0b1-e7bfd606a665.png)
