### ISSUE TITLE
Export server fails

### ISSUE THREAD

**Issue by zlev-intel** [highcharts/highcharts#18154]
#### Expected behaviour
Expected to get JPG file

#### Actual behaviour
Web server is returning an unknown error Error code 520
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=export.highcharts.com) for more information.
2022-12-15 12:02:24 UTC

#### Live demo with steps to reproduce

[plots.zip](https://github.com/highcharts/highcharts/files/10236797/plots.zip)

html file invokes timer which calls the export. 

#### Affected browser(s)
All

[plots.zip](https://github.com/highcharts/highcharts/files/10236797/plots.zip)

**Comment by pawellysy** [comment]
Hello @zlev-intel, thanks for reaching out to us. 
Works for me!
Check out this demo: https://jsfiddle.net/BlackLabel/9b1p5vkn/349/

**Comment by zlev-intel** [comment]
I’M GETTING THIS:
***@***.***

Thanks,
Lev Zlotin
***@***.***
+972-4-8656740
+972-53-5207679
WIKI: https://wiki.ith.intel.com/display/AETIDC (HTTP://GOTO/AETIDC<http://goto/AETIDC> )
Yammer: https://web.yammer.com/main/org/intel.com/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiIxMDY1MzU4MjEzMTIifQ/all
HSD: https://hsdes.intel.com/appstore/gts/#/

**Comment by zlev-intel** [comment]
I still have the error 520 from cloudflare.
I see, smaller maps are working OK.
Probably there is some limitation to size?
(and more, the picture that is show on your jsfiddle is wrong, more than half of plot is not exists.

**Comment by pawellysy** [comment]
@zlev-intel, you are right, when I looked again, there is an issue: https://jsfiddle.net/BlackLabel/9b1p5vkn/412/

The resolution of your data is too big, and the export server is unable to go through all this data. 
What you can do, is check this demo with your own export server, which is a new version. You can find a detailed explanation here: https://github.com/highcharts/node-export-server

Another idea is maybe changing your dataset. Most of your points are `nulls`, so maybe there is another way of marking the extremes of the dataset (maybe with simple annotation)?

Here is an example: https://jsfiddle.net/BlackLabel/9b1p5vkn/415/

let me know if that works for you!

**Comment by zlev-intel** [comment]
I changed “exportChart” to “exportChartLocal” and it looks like as working now.
Do you know if it is working on my local machine now and not sending data to your server?


Thanks,
Lev Zlotin
***@***.***
+972-4-8656740
+972-53-5207679
WIKI: https://wiki.ith.intel.com/display/AETIDC (HTTP://GOTO/AETIDC<http://goto/AETIDC> )
Yammer: https://web.yammer.com/main/org/intel.com/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiIxMDY1MzU4MjEzMTIifQ/all
HSD: https://hsdes.intel.com/appstore/gts/#/
