### ISSUE TITLE
Navigator with reversed xAxis doesn't work properly.

### ISSUE THREAD

**Issue by Vazonik** [highcharts/highcharts#18158]
#### Expected behaviour
Using the navigator with reversed xAxis works like the non-reversed axis, only with the extremes inverted.

#### Actual behaviour
Using the navigator with reversed xAxis incorrectly sets the extremes of the chart so that the displayed data disappears and the chart becomes blank.

#### Live demo with steps to reproduce
Use the ends of the navigator to change the extremes of the chart.
https://jsfiddle.net/BlackLabel/do4jaxb7/

#### Product version
Highstock v9.2.0+
(Regression, it worked in v9.1.2)

**Comment by bm64** [comment]
@Vazonik thanks for reporting the bug!

_Workaround:_
Set ordinal option to false: https://jsfiddle.net/BlackLabel/jra8c745/

**Comment by kamil-musialowski** [comment]
Got fixed during recent Ordinal improvement. Fix available on master `github.highcharts.com`
Demo: https://jsfiddle.net/BlackLabel/bca64gvh/

@pawelfus - could you confirm please?

**Comment by pawelfus** [comment]
Confirmed, thanks!
