### ISSUE TITLE
Map SVG line width set per path not scaling on zoom

### ISSUE THREAD

**Issue by FusionSnowball** [highcharts/highcharts#18166]
#### Expected behaviour
SVG path line width should scale on zoom when defined for each line separately, as it does when the line width is set for the whole series.

#### Actual behaviour
When giving the line width for each SVG path individually, rather than for the whole series, the width doesn't scale on zoom. If the width is specified for the whole series it scales on zoom as expected. Further more, when the width is given for each path it does resize after zoom if the user views the tooltip.

#### Live demo with steps to reproduce
https://jsfiddle.net/h6jkx8y2/2/

Zoom the map and the lines representing flights from Lerwick don't change size (width set for each line) while those for London flights do (set at series level). While zoomed, hover over a Lerwick line so the tooltip appears and then move away, the line will resize when the tooltip fades. Happens in reverse when zooming back out.

#### Product version
10.3.2

#### Affected browser(s)
Chrome 108

**Comment by bm64** [comment]
Hello @FusionSnowball and thanks for reporting the bug!

**Comment by KacperMadej** [comment]
This problem will be resolved with flowmap series that will allow getting the same map with curved connections via API and out-of-the-box (no extra code for the curves). You could track [the flowmap progress](https://github.com/highcharts/highcharts/pull/17402) to know when it will be finished - at this moment it is planned to be published in the release that will happen after the PR merge.

Adding support for lineWidth for the series down to data point level should be focus of this issue and it should stay open.
Problems with mapLine:
- no lineWidth in the API for mapline series
- no lineWidth in the API for mapline series' data point
- lineWidth defined on point level is not scaling on zoom (after correct value is calculated)
- after hover ends and the line goes back to the normal state the lineWidth is not reset to the initial thickness
- the same applies to the map series type - [demo](https://jsfiddle.net/BlackLabel/8epasvxd/1/)

Related to https://github.com/highcharts/highcharts/issues/17105
