### ISSUE TITLE
zooming by using mouse scroll

### ISSUE THREAD

**Issue by nv-maya-greber** [highcharts/highcharts#18169]
zooming can be achieved using mouse scroll, i.e., by scrolling the mouse, more or less bars will be shown within the same window
in chart line not stockChart

**Comment by bm64** [comment]
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/16658

**Comment by nv-maya-greber** [comment]
@bm64 where can i see the original request and follow the progress?

**Comment by bm64** [comment]
@nv-maya-greber here is the original feature request: https://github.com/highcharts/highcharts/issues/16658
You can use that thicket to follow the progress and feel free to leave your feedback there.
