### ISSUE TITLE
Legend item at incorrect position when layout set to "proximate" and "startOnTicks" set to false

### ISSUE THREAD

**Issue by jochenschmich-aeberle** [highcharts/highcharts#18168]
#### Expected behaviour

I've defined a chart that would not `startOnTicks` (a.k.a. set to `false`) and with the legend layout set to `proximate`.
The legend item corresponding to the maximum value of all should be drawn on the same level as the first point of the series.
<img width="289" alt="image" src="https://user-images.githubusercontent.com/91872981/208427672-04606727-0ca9-4b30-9fd6-83547b30f2df.png">

#### Actual behaviour

The legend item is way off (rather drawn at the top of the chart).
The behavior seems to be a result of the current implementation of the [`proximatePositions` method in line 1057](https://github.com/highcharts/highcharts/blob/4fd6ea3d81c5821912d2c86a550af6265b4b922f/ts/Core/Legend/Legend.ts#L1057).
Instead of `if (box.pos)` the code should rather ask `if (isNumber(box.pos))` as it would otherwise leave a box with the `pos` value of `0` unhandled.
<img width="270" alt="image" src="https://user-images.githubusercontent.com/91872981/208427744-40bc7eb1-0dd9-4a93-9d91-7032532403a6.png">

Might be linked to https://github.com/highcharts/highcharts/issues/14809#issuecomment-746330827.

#### Live demo with steps to reproduce

- Live demo of the bug: https://jsfiddle.net/ohaztj64/
- Live demo with the fix included: https://jsfiddle.net/jz8vya3h/4/

#### Product version
Latest

#### Affected browser(s)
All

**Comment by bm64** [comment]
Hello @jochenschmich-aeberle!

Thanks for your detailed report and the workaround!
