### ISSUE TITLE
Highcharts OBV indicator doesn't work with empty data set

### ISSUE THREAD

**Issue by wagnerga** [highcharts/highcharts#18176]
#### Expected behaviour
I expect highcharts to be able to still render a chart with 0 data

#### Actual behaviour
Error is thrown and app crashes with console error: "TypeError: Cannot read properties of undefined (reading '3')"

#### Live demo with steps to reproduce
https://jsfiddle.net/ep053khL/5/

#### Product version
10.2.1

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Hi @wagnerga!

_Internal note:_
In the `getValues` method there should be a check if the data even exist before calculating the values.

**Comment by hubertkozik** [comment]
As a workaround for now you can overwrite an HC method. You can check the demo below (the plugin is inside the IIFE function). A similiar solution will be used in HC Indicators Core.

**Workaround demo:** https://jsfiddle.net/BlackLabel/5rjsf6h4/
