### ISSUE TITLE
Highcharts CMF indicator doesn't work with empty data set

### ISSUE THREAD

**Issue by wagnerga** [highcharts/highcharts#18178]
#### Expected behaviour
I expect highcharts to be able to still render a chart with 0 data

#### Actual behaviour
Error is thrown and app crashes

#### Live demo with steps to reproduce
https://jsfiddle.net/218svj5L/1/

#### Product version
10.2.1

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Hi @wagnerga!

This issue is similar to #18176 and should be treated equally.

_Internal note:_
It might be worth it to go through all the indicators and check if they throw any errors with an empty dataset.

**Comment by hubertkozik** [comment]
As a workaround for now you can overwrite an HC method. You can check the demo below (the plugin is inside the IIFE function). A similar solution will be used in HC Indicators Core. 

**Workaround demo:** https://jsfiddle.net/BlackLabel/5rjsf6h4/
