### ISSUE TITLE
Bubble Chart: Non-square Legend Symbol Styles Are Not Applied

### ISSUE THREAD

**Issue by arunwithasmile** [highcharts/highcharts#18177]
#### Expected behaviour
A user should be able to customise the Legend Symbols to square/rectangle/ellipse or any non-default dot symbols in Bubble Chart.

#### Actual behaviour
When a user tries to customise Legend Symbols to any non-default dot symbols in Bubble Chart, they seem to have no effect on the rendered Legends. They appear as dots always.
It appears that they're somehow tied to the point styles. i.e, opacity on bubbles shows on the Legend Symbols as well. Seems like a cool default feature. But there seems to be no option to customise if needed.

#### Live demo with steps to reproduce
https://jsfiddle.net/694m7zct/

**Steps:** Create any Bubble Chart using Highcharts and use the following Legend properties.
```
...
legend: {
  squareSymbol: false,
  symbolHeight: 10,
  symbolWidth: 17,
  symbolRadius: 5,
},
...
```

#### Product version
Highcharts JS v10.3.2 (2022-11-28)

#### Affected browser(s)
Chrome, and Firefox, among others.

**Comment by bm64** [comment]
Hello @arunwithasmile and thanks for contacting us!

As you can see in this demo: https://jsfiddle.net/BlackLabel/ksdjfent/ `symbolWidth` and `symbolHeight` change the dimensions of legend symbol. I guess that with this configuration you'd expect the circle to become an ellipse, but that is not how it works, at least at this moment. Instead those two properties increase area over which the symbol can span, and in effect the circle becomes bigger. When it comes to the symbolRadius, as you can read in the API it is only applicable for series that use a rectangle as a legend symbol: https://jsfiddle.net/BlackLabel/amwt8fox/
I don't consider it to be a bug, so I'm closing it for now, but if you have anything to add feel free to reopen it anytime.

**Comment by arunwithasmile** [comment]
Thank you for the response. I was not aware that Bubble Sort did not support squared symbols. My bad!

**Comment by hubertkozik** [comment]
Missclick in the commit's name above - ignore please :)
