### ISSUE TITLE
Gantt x axis label rows don't apply date formatting consistently

### ISSUE THREAD

**Issue by ambischof** [highcharts/highcharts#18172]
#### Expected behaviour
in gantt charts, when I change the date formats, I expect them to change everywhere

#### Actual behaviour
In gantt charts, when I change the date formats, it changes the format in the lower upper axis labels, but not the top upper axis label. (Sorry for bad terminology)

Here's a preview of what top x axis label might look like in ascii, (I can't get markdown tables to work)
```
|--------------------|
| 14:21              |     <------- 24 hour time (not following formatting)
|--------------------|
| 2:21 | 2:22 | 2:24 |     <------ 12 hour time (following formatting) 
|--------------------|
```

#### Live demo with steps to reproduce
https://jsfiddle.net/wck94guf/3/ (please pay attention to top x axis labels)

#### Product version
Highcharts and Gantt 10.2.1
Fiddle unversioned, assumed latest.

#### Affected browser(s)
discovered in chrome

**Comment by karolkolodziej** [comment]
Hi @ambischof thank you for reporting this issue!

As a workaround, you can declare the same `dateTimeLabelFormats` for each xAxis - [demo](https://jsfiddle.net/BlackLabel/j7okz4u6/).
