### ISSUE TITLE
Boost with multiple series not rendering with point colors

### ISSUE THREAD

**Issue by snoopylr** [highcharts/highcharts#18181]
#### Expected behaviour

When in Boost mode with multiple series, the chart should render the colors provided in the data points.

#### Actual behaviour

The first chart is rendered correctly with the colors, however, the second chart does not get rendered _at all_ when providing colors for individual points.

If you comment out/remove the colors in the second series, it will render properly (but with black as the color).

#### Live demo with steps to reproduce

https://jsfiddle.net/kgce453z/1/

#### Product version

Highcharts JS v10.3.2 (2022-11-28)

#### Affected browser(s)

All browsers

**Comment by bm64** [comment]
Hello @snoopylr and thanks for contacting us with your issue.

As you can see in the console there is a [Highcharts error 12](https://assets.highcharts.com/errors/12/) which says:

> In boost mode, turbo mode is always on, which means only array of numbers or two dimensional arrays are allowed.

It's the boost module limitation and it is not possible to set colour for single point like in your example. See docs: https://www.highcharts.com/docs/advanced-chart-features/boost-module#configuration-data-options
