### ISSUE TITLE
First line of legend with navigation is cut

### ISSUE THREAD

**Issue by NastyaBanko** [highcharts/highcharts#18183]
#### Expected behaviour
The line shouldn't be cut

#### Actual behaviour
The line is cut

#### Live demo with steps to reproduce

The bug exists in your demo for legends with navigation:
* link to doc: https://api.highcharts.com/highcharts/legend.navigation.style
* link to demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/legend/navigation/
you can see that circle is cut a little bit:
![127](https://user-images.githubusercontent.com/49037181/208841204-223af66a-1ffb-4567-b090-b844fe318406.PNG)

#### Product version

v10.3.2

#### Affected browser(s)
Chrome

**Comment by bm64** [comment]
Hi @NastyaBanko and thanks for reporting the bug.

As a workaround you can overwrite setOptions method and adjust legend item position: https://jsfiddle.net/BlackLabel/3kq14eb6/
