### ISSUE TITLE
setting useUTC option when Initializing a new chart doesn't work

### ISSUE THREAD

**Issue by truncs** [highcharts/highcharts#1820]
Highcharts init function merges defaultOptions and userOptions in init and assigns it to this.options but the datetime functions use this.defaultOptions to get the useUTC setting. This can be avoided by calling Highcharts.setOptions(options) explicitly but it is wrong of the datetime functions to use defaultOptions.

**Comment by TorsteinHonsi** [comment]
Highcharts now has the [time](https://api.highcharts.com/highcharts/time) options allowing to set individual time for each chart instance.
