### ISSUE TITLE
Gantt chart scroll bar not consistent

### ISSUE THREAD

**Issue by shihabkaniyarath** [highcharts/highcharts#18208]
I set up a test project for demo purpose. i collapsed items and try to scroll, the scrollbar not consistent. 
Live demo: https://jsfiddle.net/BlackLabel/f2gjtvbp/

I need to export collapsed items also, but it is not.

**Comment by karolkolodziej** [comment]
Hi @shihabkaniyarath!

We are aware of that issue, here is a similar one reported: https://github.com/highcharts/highcharts/issues/13898
Closing as a duplicate.
