### ISSUE TITLE
Bar chart race blog post

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#18202]
#### Expected behaviour
Improve the demo code and every code snippet according to the `Juru's` comment.

#### Actual behaviour
If you hit Play and stop (for example on the year 1964) you will see the population of China 165 642 440 000.
If you drag the slider to the same year (1964) you will get the correct numbers for the series 698 355 000.

#### Live demo with steps to reproduce
https://www.highcharts.com/blog/tutorials/bar-chart-race/

#### Product version
Highcharts JS v10.3.2 (2022-11-28)

#### Affected browser(s)
All

**Comment by hubertkozik** [comment]
@karolkolodziej Is this issue still possible to reproduce? This demo is now also on the main demo page (https://www.highcharts.com/demo) but I am unable to reproduce the described problem now.

**Comment by karolkolodziej** [comment]
The demo works fine because it is hosted by @mekhatria in codepen.
This issue is more about fixing the references in the code snippets.
