### ISSUE TITLE
Chart and Navigator Handle Should get accessed with keyboard (508 compliance)

### ISSUE THREAD

**Issue by casepointhighcharts** [highcharts/highcharts#18216]
https://www.highcharts.com/docs/stock/navigator

#### Expected behaviour
Chart and navigator handle should get accessible through keyboard 

#### Actual behaviour
By tabling the chart element chart and navigator did not get focused and not get accessed 

#### Live demo with steps to reproduce

https://dojo.telerik.com/obItokAg/17
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/navigator/multiple-series/

#### Product version

7.1.2

**Comment by oysteinmoseng** [comment]
Hi @casepointhighcharts, this will be prioritized after Highcharts v11, so you can expect a fix in May. Hope this works for you!

In the meantime I suggest providing an alternative way of setting the range of the chart, either using the [Range Selector](https://www.highcharts.com/docs/stock/range-selector) or something like custom HTML date inputs outside of the chart.

**Comment by casepointhighcharts** [comment]
Hi Oysteinmoseng,

Gone through Highcharts v11 [changelog](https://www.highcharts.com/blog/changelog/) I can not see this changes are still accommodated. 

Highcharts v11 
https://dojo.telerik.com/obItokAg/18

According to your development flow it is still under **[todo](https://github.com/highcharts/highcharts/projects/2?card_filter_query=18216#card-87412212)**.

Can you please let us know when this changes will get deployed ? that will be really helpful.

**Comment by oysteinmoseng** [comment]
Hi @casepointhighcharts, this is high priority and in progress now. We are releasing v11.1 soon, but it is still not clear if this work will make it into that release or be part of the next.

Once the work is merged to `master` you can pull the code from github.highcharts.com and self-host it. I hope this works for you, and apologies for the delay.

**Comment by casepointhighcharts** [comment]
_Issue has not been resolved yet please open this ticket, do let us know when we can expect this change ?_ 

https://www.highcharts.com/docs/stock/navigator

Expected behaviour
Chart and navigator handle should get accessible through keyboard

Actual behavior
By tabling the chart element chart and navigator did not get focused and not get accessed

Live demo with steps to reproduce

https://dojo.telerik.com/obItokAg/17
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/navigator/multiple-series/

With new released version (11.1.0)
https://dojo.telerik.com/@vimal_mavani/inEfAfOd

**Comment by oysteinmoseng** [comment]
Hi @casepointhighcharts, this is closed as the feature has been merged with the latest code, but is not yet released into production. There is a new Highcharts release coming this week or next, at which point it will be available in production as well. Apologies for the confusion and the wait.
