### ISSUE TITLE
Zoom doesn't work for datetime axis 

### ISSUE THREAD

**Issue by kaguya3222** [highcharts/highcharts#18237]
#### Expected behaviour
Zoom should work for datetime axis based on selected range

#### Actual behaviour
There is an empty area after zooming

#### Live demo with steps to reproduce
[Codesandbox](https://codesandbox.io/s/bitter-sunset-d9ol8n?file=/src/index.js)

#### Product version

Highcharts: 10.3.2

#### Affected browser(s)
Google Chrome 108.0.5359.124

**Comment by bm64** [comment]
Hello @kaguya3222 and thanks for contacting us.

The zoom doesn't work because data is not sorted - you can see [Highcharts error #15](https://assets.highcharts.com/errors/15/) in the console. Sort the data and zoom will work correctly: https://codesandbox.io/s/infallible-lumiere-piwfyj

**Comment by kaguya3222** [comment]
@bm64 Thank you for a quick answer! To be honest, I thought that Highcharts warning #15 was connected with the Accessibility warning. Of course, it's my bad that I didn't check the full description, but maybe it's worth adding this info in docs? Or maybe to make warning messages friendlier so they are descriptive without going to the full description? Anyway, my bad, thank you!
