### ISSUE TITLE
The first click on YTD button does not activate it

### ISSUE THREAD

**Issue by magdalena-gut** [highcharts/highcharts#18239]
#### Expected behavior
The YTD RangeSelector button should be activated after the first click.

#### Actual behavior
After the first click on the YTD button, it seems to be clicked for a moment but after that, it is back to the previous state, and the chart freezes. Only after the second click on the button, the behavior is correct.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/2qwcfuhk/

#### Product version
v10.3.2

#### Affected browser(s)
N/A

**Comment by kamil-musialowski** [comment]
The simplest definition of YTD defualt behaviour is "show the range from the 1st day of the current year up to present time". 

In the demo, we can see that once we drag the left and right handle, to set the extremes somewhere in the middle, and then we click on YTD button everything works fine.
It's even easier to observe that on a demo with larger dataset here: https://www.highcharts.com/demo/stock/flags-general

However, in the OP demo, once we click YTD after the initial chart load (without clicking anything before that) xAxis.max is not being updated with each added point.

In that case, do we still treat it as a bug @pawelfus ?
