### ISSUE TITLE
Breadcrumbs rendered in the scroll area instead of being fixed

### ISSUE THREAD

**Issue by Vazonik** [highcharts/highcharts#18249]
#### Expected behaviour
Breadcrumbs are in a fixed position, regardless of the scrolling of the chart.

#### Actual behaviour
When scrolling down the chart, the breadcrumbs also move, which makes navigation difficult.

#### Live demo with steps to reproduce
Click on the point to make the breadcrumbs appear, then scroll down.
https://jsfiddle.net/BlackLabel/ruxbn5Lm/

#### Product version
Highcharts v10.3.2

**Comment by karolkolodziej** [comment]
Fixed by: https://github.com/highcharts/highcharts/issues/17963 and already available on master- [demo](https://jsfiddle.net/BlackLabel/705j4Lgt/)

Closing as a duplicate.
