### ISSUE TITLE
How to implement internationalization of 'no data' text in highcharts with Angular 13

### ISSUE THREAD

**Issue by DuyguTemel** [highcharts/highcharts#18248]
#### Expected behaviour
`{lang: {noData: this.translate.instant('no.data.found')}})`

Expectation: for En: 'No data found' , for DE : 'Es wurden keine Daten gefunden'

#### Actual behaviour

The chart is not updated on language change event in Angular

**Comment by pawellysy** [comment]
Hello! Thanks for reaching out to us with your question!
Our GitHub channel is treated as a bug/feature tracking tool. For these kinds of questions, please get in touch with us via dedicated support channels, which you can find here: https://www.highcharts.com/blog/support/.

Our support engineers will be more than happy to help you if only you can provide them with more information about your use case.
