### ISSUE TITLE
Gantt Chart Range selector not consistent

### ISSUE THREAD

**Issue by shihabkaniyarath** [highcharts/highcharts#18251]
Hi Team,
I'm trying to check Gantt chart meet our requirements. Range selector didn't allow me to select valid date from date picker. it is going to first row date range.

![2023-01-05_15h11_01](https://user-images.githubusercontent.com/80107784/210793677-21d53660-d0e4-4f1a-981c-a789a6394af4.png)

When i select Jan 22nd. it is going to Jan 19 (first row date range). Please check on live demo
Live Demo : [Project Management - JSFiddle - Code Playground](https://jsfiddle.net/shihabkaniyarath/y0r496ct/2/)

#2 When I try to export with collapsed, collapsed items are not showing the result. And navigator showing the result

**Comment by shihabkaniyarath** [comment]
You can select 22.01, could you try to select 27.01.2023. and let me know it selected or not

**Comment by karolkolodziej** [comment]
Yes, I am not able to select the second to last available point in the selector (27.01 at this point).

_Internal note:_ 
It looks like the selector does not go through all series - only the first one.

_Workaround:_
- Disable the navigator - [demo](https://jsfiddle.net/BlackLabel/8bnqcetd/)
- At the top add a point that will cover the whole range of points - [demo](https://jsfiddle.net/BlackLabel/7L4vwkcm/)
