### ISSUE TITLE
Custom markers for pie chart connectors are not rendered in exported PDF file 

### ISSUE THREAD

**Issue by annashakhbazian** [highcharts/highcharts#18255]
#### Expected behaviour
I want to export a pdf with a pie chart that has custom SVG markers. But they disappear on rendered pdf. I use chart.exportChartLocal method for export. 
Export with a server works fine, but I would like to export it locally.  
I thought the issue might be the library that converts svg to pdf, but I tried it in https://raw.githack.com/yWorks/svg2pdf.js/master/index.html and it rendered markers fine. 

#### Actual behaviour
SVG markers are in the exported PDF.

#### Live demo with steps to reproduce
http://jsfiddle.net/anna_sh/qgxf5d86/5/

Click menu in the corner and try export to pdf

#### Product version

 10.3.2
#### Affected browser(s)
All

**Comment by bm64** [comment]
Hello @annashakhbazian and thanks for reporting the issue.
