### ISSUE TITLE
Errors with HC 10.3.2 vs 10.3.1: "attribute transform: Trailing garbage"

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#18252]
I have put in an override in my code for `Highcharts.Pointer.scaleGroups` so that, when panning/zooming on a mobile device touch screen, all SVG components in my `chart.seriesGroup` are transformed together, rather than leaving some behind.  In this respect, I have also overridden `Highcharts.PlotLineOrBand.render` (based on [this demo](https://github.com/highcharts/highcharts/issues/3321#issuecomment-278003288) from @TorsteinHonsi).

The following demos differ only in the version of highcharts being used:

https://jsfiddle.net/1c9vtrup/ (10.3.1)
https://jsfiddle.net/1c9vtrup/1/  (10.3.2)

With `10.3.1`, panning/zooming on a mobile touch screen works fine.  To simulate this in a Chome browser I am opening devtools and clicking `Toggle device toolbar` to get the mobile touchscreen device:

![image](https://user-images.githubusercontent.com/9009792/210793701-ec346e3e-d443-4ae4-a09b-718a27cfadc8.png)

I am also loading the "raw" versions of the above, without the code panels etc:

https://jsfiddle.net/1c9vtrup/show (10.3.1)
https://jsfiddle.net/1c9vtrup/1/show (10.3.2)

With `10.3.2`, I am getting a stream of errors like the following in the console, when panning:

    Error: <g> attribute transform: Trailing garbage, "translate(-91,NaN) scale(1 1)".
    Error: <g> attribute transform: Trailing garbage, "translate(-94,NaN) scale(1 1)".
    Error: <g> attribute transform: Trailing garbage, "translate(-96,NaN) scale(1 1)".

Seems like a bug in `10.3.2`?  I see that the [changelog for this version](https://www.highcharts.com/blog/changelog/#highcharts-v10.3.2) has "Refactored and simplified series group inversion logic" so it must relate to that... either it has introduced a bug, or there is a knock-on effect which means that my overrides need to be changed to account for any new behaviours?

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

I think you're right about the change in the changelog. Apparently `getPlotBox` no longer returns a `translateY` value, that's why it becomes `NaN` when you're trying to modify it. This seems to work well for me:

```js
  var myAttribs = attribs || chart.series[0].getPlotBox();
  myAttribs.translateY = myAttribs.translateY || chart.plotTop; // <=== Add this line
  myAttribs.translateX -= chart.plotLeft;
  myAttribs.translateY -= chart.plotTop;
```

https://jsfiddle.net/highcharts/7efb8kcL/1/

**Comment by drmrbrewer** [comment]
@TorsteinHonsi thanks for the explanation and workaround.

> Apparently getPlotBox no longer returns a translateY value

But why doesn't it?  I mean, [it tries to](https://github.com/highcharts/highcharts/blob/master/ts/Core/Series/Series.ts#L3311).

[Side question: do you know how to simulate a two-fingered pinch/zoom in the "phone" view of Chrome devtools, while viewing a highcharts chart?  Holding down Shift while clicking and dragging with the mouse appears to try to scale the entire window, rather than simulate a two-fingered pinch on the chart itself.]

**Comment by TorsteinHonsi** [comment]
> But why doesn't it?

I was wrong, your `myAttribs` don't come from `getPlotBox`, but from the arguments of `scaleGroups`. It goes back to `Pointer.pinchTranslateDirection` that handles x or y independently.

> Side question: do you know how to simulate a two-fingered pinch/zoom in the "phone" view of Chrome devtools

I have been wondering about that myself, but haven't found a good way

**Comment by drmrbrewer** [comment]
> your `myAttribs` don't come from `getPlotBox`, but from the arguments of `scaleGroups`

So is this really now intended behaviour (requiring your workaround) or a bug?  This is an example of `attribs` passed in to the `scaleGroups` function:

![image](https://user-images.githubusercontent.com/9009792/210983949-7da61072-dae9-411e-9305-0d63949c16dd.png)

Should any value really be `NaN` at this point?

**Comment by drmrbrewer** [comment]
@TorsteinHonsi any further thoughts on this?

**Comment by TorsteinHonsi** [comment]
@drmrbrewer 
> So is this really now intended behaviour (requiring your workaround) or a bug?

These are internal functions that you created overrides for, so we don't consider it a bug. You just have to adapt your overrides to how the internals currently work. 

Unless of course you have an example where these errors occur internally with the unmodified library?

**Comment by drmrbrewer** [comment]
Sure, I understand that it's not your concern to ensure that some unknown custom override continues to function, it's just that whenever I discover a variable in my own code that has become `NaN` it's usually an indication that I have a bug somewhere upstream (e.g. invalid input) that is either causing a problem now, or will do in future.  Maybe I just have an irrational fear of `NaN`.
