### ISSUE TITLE
Как пропускать выходные дни на оси X?

### ISSUE THREAD

**Issue by veleg** [highcharts/highcharts#18259]
#### Expected behaviour
It is necessary to skip days on the X axis that are not in the JSON file.
need:
2022-5-30
2022-5-31
2022-6-1
2022-6-2
2022-6-3
2022-6-6

#### Actual behaviour
Now a series of all days of the week is being built on the X-axis.
like now:
2022-5-30
2022-5-31
2022-6-1
2022-6-2
2022-6-3
2022-6-4
2022-6-5
2022-6-6

#### Live demo with steps to reproduce
https://jsfiddle.net/5z1b9xnp/

#### Product version
Highcharts JS v10.3.2 (2022-11-28)

**Comment by pawellysy** [comment]
Hello @veleg, thanks for reaching out to us with your question. 
Unfortunately, we are treating GitHub as a bug/feature tracking tool. With these kinds of questions please reach out to us via [our available support channels](https://www.highcharts.com/blog/support/).
Thank you for your understanding!
