### ISSUE TITLE
Single-Touch Device on Windows cannot execute free-zoom

### ISSUE THREAD

**Issue by PadWorks** [highcharts/highcharts#18269]
#### Expected behaviour
When using a Windows-based singletouch device, I expect the same operating principle as using a mouse to zoom a trend. (Tab on screen and slide diagnoal down/right)

#### Actual behaviour
When using a Windows-based singletouch device, the trend cannot be zoomed.

Perhaps the problem correlates with: https://github.com/highcharts/highcharts/issues/18122

#### Live demo with steps to reproduce
[https://jsfiddle.net/PadWorks/L5v3q0zw/](https://jsfiddle.net/PadWorks/L5v3q0zw/)

#### Product version
Highcharts JS v10.3.2 (2022-11-28)

#### Affected browser(s)
Chrome/Firefox on Windows using a single-touch device.

**Comment by bm64** [comment]
Hello @PadWorks and thanks for reporting the issue!

**Comment by PadWorks** [comment]
@bm64  For us, problem solving would be important. Until when is the problem fixed?

**Comment by hihajdus** [comment]
Hi @PadWorks, 
Since 10.2.1 Highcharts version zoom options were refactored, to enable single touch, 
the correct object looks: [chart.zooming.singleTouch](https://api.highcharts.com/highcharts/chart.zooming.singleTouch).

Demo: https://jsfiddle.net/BlackLabel/bcfhLps1/
