### ISSUE TITLE
Needed to render a "World" map chart in Angular which will render correctly(with disputed territories) depending on the timezone of the person who is accessing it?

### ISSUE THREAD

**Issue by himanshugawande** [highcharts/highcharts#18265]
Dear Team,

Currently I am using **highcharts v10.3.2, highcharts-angular v3.0.0** and implementing it in **Angular v15.0.X.**

As we can see the HighCharts Map collection currently present at "https://code.highcharts.com/mapdata/" does have various types on World Map but what we wants is, as per our use case we found it not to be showing disputed territories if viewed from some location. 

**For example, if I am viewing from India the same world map won't include disputed territories of India which might get me in trouble. Same can happen if viewed from anywhere across the globe.**

Can you help me with a solution to get **world map which will render map correctly based on the timezone of the person, who is using it**?

Thanks,
Himanshu

**Comment by KacperMadej** [comment]
Hi @himanshugawande 

This problem looks rather outside of the Highcharts Maps functionality as all the location-related code is happening before the map is created. I think this issue should be closed as not planned but lets start with a potential solution first:

It looks to me like 2 parts: 
1. getting the client location
2. loading a map based on the location

**Client location based on the IP.**
This is a general - not a Highcharts specific - issue and you could find a lot of solutions [here](https://stackoverflow.com/questions/391979/how-to-get-clients-ip-address-using-javascript).

**Load a map based on the location**
Disclaimer: The below demo is based on https://db-ip.com/api/ so in case it doesn't work for you then you could change the location provider based on the No. 1 or try again tomorrow as the free limit for that day might have been exceeded (1,000 requests per day).

Here's a demo: https://jsfiddle.net/BlackLabel/4hm6ngaL/1/

Demo info: The map title should have your country name in it. If you are outside of Europe you will see the world map or the Europe map if you are in that region.

**Comment by himanshugawande** [comment]
Thanks @KacperMadej , we understand the solution and we were opting for something similar to this. We just wanted to know whether HighChart is planning to have or already have any such collection of world map which will have disputed territories based on viewed from different varoius parts of world as it would be quite helpful for us to load the map based on it.

I have gone through the world map collection from HighChart but didn't find any of those which could suffice my needs.

**Comment by KacperMadej** [comment]
@himanshugawande 
There is no plan to introduce any limitation on which maps can or cannot be viewed from any location.
We can add new maps or edit existing ones to include all or new points of view - especially in case of a disputed territory.

If there are any maps missing (or in fact, if there are any issues with the map collection that you would like to report to help us improve the collection) please add the info in the [map collection repo](https://github.com/highcharts/map-collection-dist/issues).

How would you like to continue with this open issue here? I would suggest closing and continuing in the other repository.

**Comment by himanshugawande** [comment]
Okay, thanks.
