### ISSUE TITLE
Values in wrong order when changing data

### ISSUE THREAD

**Issue by Kisters-BS** [highcharts/highcharts#18266]
#### Expected behaviour
When changing data, it should display the values in correct order.

#### Actual behaviour
When changing data, the values are not in the correct order and highcharts returns error "Highcharts warning #15: www.highcharts.com/errors/15/" although the x values are defined in ascending order. When second data is used as initial data, it is displayed correctly, so the bug has to do something with changing the data.

#### Live demo with steps to reproduce
https://jsfiddle.net/1uk0fLyc/

#### Product version
10.3.2

#### Affected browser(s)
Firefox, edge, chrome

**Comment by pawellysy** [comment]
Hello @Kisters-BS thanks for contacting us!
The reason why this is happening is that you are changing the data with IDs defined. Each point from the new config updates the corresponding point with the same ID. This makes the data change its order. 
There are numerous workarounds: 

- Update to empty series array (No animation) https://jsfiddle.net/BlackLabel/t2964juh/
- Stop using IDs for each point, or use different IDs for the second series. https://jsfiddle.net/BlackLabel/tu14986r/


If you need more help with a given topic, don't hesitate to get in touch with us via [our available support channels.](https://www.highcharts.com/blog/support/) Thanks!

**Comment by Kisters-BS** [comment]
@pawellysy Thank you for your quick response and detailed explanation! I would like to use your first workaround but it seems to also produce this unintended behaviour. Could you please check why this is happening? When I log the chart options after the chart.update({series: []}); update, it still seems to have the populated series.

**Comment by pawellysy** [comment]
Could you please share the demo to show the way, you are logging the chart options?

**Comment by Kisters-BS** [comment]
https://jsfiddle.net/97ct3658/

**Comment by pawellysy** [comment]
hi again! Please with all this information reach out to us via our available support channels.(https://www.highcharts.com/blog/support/)

We treat github as bug/feature tracking tool. Thank you for your understanding!
