### ISSUE TITLE
MapChart or Chart doesn't have a property mapView with a MapView class

### ISSUE THREAD

**Issue by szykov** [highcharts/highcharts#18278]
#### Expected behaviour
When set extremes for worldMap chart it should zoomIn
For example:
chart.yAxis[0].setExtremes(-7686.975480799574, -7751.509535225241);
chart.xAxis[0].setExtremes(1449.334671000368, 8229.656780260837);

#### Actual behaviour
It doesn't zoomIn.

#### Live demo with steps to reproduce
http://jsfiddle.net/pawel_dalek/qhtdt7xd/

#### Product version
Latest (10.3). But it got broken since version 9.
I confirm it works on version 8.2.2

**UPDATE:** the description of the issue is not valid. Only TS typings and documentation issue. See the thread.

**Comment by karolkolodziej** [comment]
It was a part of a change in version 9.3.0. - [changelog](https://www.highcharts.com/changelog/#highcharts-maps-v9.3.0).

In the newer version please use the `setView` method as described in [the API.](https://api.highcharts.com/class-reference/Highcharts.MapView#setView)

**Comment by szykov** [comment]
> It was a part of a change in version 9.3.0. - [changelog](https://www.highcharts.com/changelog/#highcharts-maps-v9.3.0).
> 
> In the newer version please use the `setView` method as described in [the API.](https://api.highcharts.com/class-reference/Highcharts.MapView#setView)

thank you, sir. my bad.

**Comment by szykov** [comment]
@karolkolodziej btw MapChart doesn't have a property mapView with a MapView class.
https://api.highcharts.com/class-reference/Highcharts.MapView
https://api.highcharts.com/class-reference/Highcharts.Chart

I checked the typings and no references or properties.

**Comment by karolkolodziej** [comment]
Could you please elaborate? Do you mean the documentation or the TS definitions are missing?

**Comment by szykov** [comment]
@karolkolodziej <ins>both</ins>. I checked docs and I see that in **MapView** class reference it is mentioned
`On a chart instance, the map view is available as chart.mapView.`
Meanwhile, in the **Chart** class reference **mapView** is missed among 'members'

**Comment by karolkolodziej** [comment]
Yes, you are right the documentation and the TS declarations are missing.

For now, as a workaround, you can create your own interface based on the existing ones- [demo](https://stackblitz.com/edit/highcharts-angular-mappoint-lat-lon-hx2csg).

Let's treat this issue as a place for TS and API improvement :) 

FYI @KacperMadej
