### ISSUE TITLE
How can correct time display in highchart candlestick

### ISSUE THREAD

**Issue by vnxz** [highcharts/highcharts#18281]
here is my code , data fetch from laravel and display in blade file
```

  $(document).ready(function () {

    // create the chart
    $('#container').highcharts('StockChart', {

        // rangeSelector: {
        //     allButtonsEnabled: true,


        //       selected: 1
        //   },

       

        title: {
            text: 'CC Price'
        },


        series: [{
            type: 'candlestick',
           
            name: 'AAPL Stock Price',
          
            data: [

              <?php  foreach($priceall as $price) 
      
                  {?>
            
                    [ '<?php echo strtotime($price['created_at']) *1000 ; ?>' , <?php echo $price['openprice']; ?>,<?php echo $price['highprice']; ?>, <?php echo $price['lowprice']; ?> ,<?php echo $price['closeprice']; ?> ],
                
                <?php  }?>
                ] ,
          //  dataGrouping: {
          //        units: [
          //          [
          //            'week', // unit name
          //            [1] // allowed multiples
          //          ], [
          //            'month',
          //            [1, 2, 3, 4, 6]
          //          ]
          //        ]
          //      }

        


        }]



    });
});


```
the problem is time display not correct .
![Screenshot_2](https://user-images.githubusercontent.com/76085185/211865784-bc275f98-9e76-40a6-97eb-ed8324607f25.png)

![Screenshot_4](https://user-images.githubusercontent.com/76085185/211866286-d155a86f-29ac-4c6c-bab3-4915971a6714.png)
this time display error happen in every candle.

actual time are

![Screenshot_3](https://user-images.githubusercontent.com/76085185/211865807-98a17fe2-f652-4860-9a38-d1712afbe3df.png)

why this happen , how can fix

**Comment by pawellysy** [comment]
Hello @vnxz  thanks for reaching out to us!
Sorry to inform you, but We use GitHub as a bug/feature tracking tool. With questions like this, please reach out to us via our [available support channels](https://www.highcharts.com/blog/support/), where our support engineers are more than happy to help you with tweaking the chart's configuration to your need.
