### ISSUE TITLE
Border in one-slice pie

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#1828]
Examples:
3.0.1: http://jsfiddle.net/KNFJE/33/
2.3.5: http://jsfiddle.net/KNFJE/35/

Version 3.0.1 contains extra border at the beginning and et the end of that one slice.

**Comment by natee** [comment]
@stephanevanraes wonderful!

**Comment by spyro92** [comment]
The plug in is great to smooth the edges when borderWidth=0.
Any chance this will be fixed in Highcharts?

**Comment by TorsteinHonsi** [comment]
For the sake of consistency (with line series markers), I would prefer that we could set a `borderWidth: 1` and `borderColor: null` to use the same border color as the slice itself. Then we would add this to the docs as a tip for how to get rid of the antialiasing lines. 

How do you feel about that?

**Comment by TorsteinHonsi** [comment]
The implementation would be to add these lines below [this line](https://github.com/highcharts/highcharts/blob/1cea1d988/js/parts/PieSeries.js#L389):

```js
				if (!pointAttr.stroke) {
					pointAttr.stroke = pointAttr.fill;
				}
```

**Comment by spyro92** [comment]
That's seems logical :)

**Comment by aksingh** [comment]
Any update on this? This has been open for more than 6 months now.

**Comment by TorsteinHonsi** [comment]
Yes, `borderColor: null` is implemented now: http://jsfiddle.net/highcharts/NK5db/17/
