### ISSUE TITLE
Print chart preview background 

### ISSUE THREAD

**Issue by KamilKubik** [highcharts/highcharts#18291]
#### Expected behaviour
The _print chart_ preview should display a white background (transparent)

#### Actual behaviour
The _print chart_ preview doesn't display a white background (same when setting the 'white' or '#fff' as _backgroundColor_ property)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/37fu1psz/

#### Product version
Highcharts v10.3.2

#### Affected browser(s)
Firefox v108.0.2

**Comment by bm64** [comment]
Hello @KamilKubik and thanks for reporting the issue. 

I have tested the bug on Firefox v108.0.2, but it seems like the print preview works incorrectly in general, for example on other websites. Most likely the regression is on the Firefox side.
Anyway, it seems like setting `backgroundColor` to `transparent` or `none` does the trick: https://jsfiddle.net/BlackLabel/2h93pmqa/
