### ISSUE TITLE
replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData

### ISSUE THREAD

**Issue by Karaterzidi** [highcharts/highcharts#18301]
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.

To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.

Note that for performance reasons, only the first access to one of the properties is shown.

**Comment by karolkolodziej** [comment]
Hi @Karaterzidi thank you for sharing that idea!
Could you please describe where this issue is visible to you? In which situations do you get this message?

**Comment by Karaterzidi** [comment]
> Hi @Karaterzidi thank you for sharing that idea! Could you please describe where this issue is visible to you? In which situations do you get this message?

If I use Lighthouse from Google Dev tools, it appears as an issue. It is not occurs in specific cases. It occurs whenever I load the page.

**Comment by ne3nay** [comment]
> Which page are you thinking of?

https://www.highcharts.com/demo/line-basic

1. Emulate site in Google Chrome for Pixel 5 device
2. Open "Issues"
3. View "highcharts.js"
