### ISSUE TITLE
set a square marker size

### ISSUE THREAD

**Issue by 0533105038** [highcharts/highcharts#18319]
#### Expected behaviour
I use a tile map - I place points on the X-axis and Y-axis on a background image that is a map,
The data comes from a server with values of temperature and humidity and the background of the point is determined by the data.
The tileShape: 'square' (because When I made a different shape - the positions of the points were not accurate)and I want it to be a symmetrical square and not a rectangle like it comes by default,
I tried to change colsize: 0.25 - it helped a little, but why are not all the points on the map the same size - the size of some 6x4 and some 6x5 when you change the position - the size changes.
And how do I change the size of the square to be a smaller symmetrical square than the default?
![Capture](https://user-images.githubusercontent.com/122966693/213116933-62770e6d-a1d2-4059-9b10-89fdc029345e.PNG)

I changed the type to 'heatmap' and gave marker size-it didn't affect, the square has no changed.
I sent this question ang got the answer-that it is a bug.
can you fix it and tell me when you finish?
thank you.

#### Actual behaviour

The size of the squares is not symmetrical
#### Live demo with steps to reproduce

https://jsfiddle.net/9yk2f7ps/

**Comment by karolkolodziej** [comment]
Hi @0533105038,

[As you can see in the API](https://api.highcharts.com/highcharts/series.heatmap.marker) there is a property `height` and `width` for the marker and it works properly if you give a smaller number- [demo](https://jsfiddle.net/BlackLabel/e4af60yz/).

But in the `HeatmapPoint` code there is a mechanism that prevents you from adding markers that might overlap with another cell. See a part of that logic:
https://github.com/highcharts/highcharts/blob/be630bb85a986e5f7d80215251404887e8c1f3aa/ts/Series/Heatmap/HeatmapPoint.ts#L158-L192

I won't consider this a bug. 
If you would like to change that behaviour, please follow [the guidelines on how to extend Highcharts functionalities.](https://www.highcharts.com/docs/extending-highcharts/extending-highcharts)
