### ISSUE TITLE
Gantt - mouse right click triggers drag-drop

### ISSUE THREAD

**Issue by LimmaPaulus** [highcharts/highcharts#18313]
#### Expected behaviour
Mouse right click should not trigger point dragging. Dragging should be possible only while holding mouse left button.

#### Actual behaviour
Mouse right click triggers dragging. Context menu opens normally, but after right clicking chart again, point is dropped to a new location.

I'm using custom-events plugin to bind customized context menu to right click event. Currently this is not working, because right click sometimes triggers drag-drop, too.

#### Live demo with steps to reproduce

Higcharts Interactive Gantt -demo
https://www.highcharts.com/demo/gantt/interactive-gantt

Right click any data point. Browser default context menu opens. Right click any other place in chart. Point is moved.

#### Product version
HighCharts Gantt 10.3.2

#### Affected browser(s)
Chromium 109.0.5414.74 Arch Linux.
With Firefox 108.0.1 is working correctly

**Comment by bm64** [comment]
Hello @LimmaPaulus and thanks for reporting the issue.

**Comment by LimmaPaulus** [comment]
You're welcome. Can you suggest any workarounds while waiting the fix? Is there e.g. API to cancel dragging which I could call on right click event?

**Comment by bm64** [comment]
Sure. It is not possible to do from API level but you can adjust initDragDrop function from draggable-points module. Demo (see line 1433): https://jsfiddle.net/BlackLabel/8jL5wyfq/

**Comment by LimmaPaulus** [comment]
Thanks. So I copied the transpiled code directly to file named higchartsDraggablePoint.js and then import it instead of the official module

```js
import HighchartsHistogram from 'highcharts/modules/histogram-bellcurve';
import HighchartsSolidGauge from 'highcharts/modules/solid-gauge';
import HighchartsDraggablePoints from './higchartsDraggablePoints';

HighchartsDraggablePoints(Highcharts);
```

Quite hacky, but works for now. Thank you!
