### ISSUE TITLE
Venn Diagram dragDrop not functioning as per API

### ISSUE THREAD

**Issue by zachegnermh** [highcharts/highcharts#18317]
#### Expected behaviour
After enabling _series.venn.dragDrop.draggableX_, I would like to drag and drop Venn Diagram sets
 
#### Actual behaviour
As per [API](https://api.highcharts.com/highcharts/series.venn.dragDrop), _series.venn.dragDrop_ does not seem to function as expected. Setting _draggableX_ and _draggableY_ to true does not result in draggability. I have imported the necessary [module](https://code.highcharts.com/modules/draggable-points.js).

#### Live demo with steps to reproduce
[jSfiddle Link](https://jsfiddle.net/a4ngvd1f/3/)

#### Product version
"highcharts": "^10.3.2"

#### Affected browser(s)
Chrome v108.0.5359.125
Edge v109.0.1518.55

**Comment by pawellysy** [comment]
Hello @zachegnermh, thanks for reaching out to us!
I don't see how the Venn diagram could support drag and drop. This feature makes sense for series positioned with cartesian coordinates, or some natural algorithm positioning series (e.g. networkgraph, packedbubble). in this example I don't really understand the use case. 
Could you elaborate, on how do you think that this feature should work? Thanks!

**Comment by zachegnermh** [comment]
Hi @pawellysy, at the link that I had posted previously, ([https://api.highcharts.com/highcharts/series.venn.dragDrop](https://api.highcharts.com/highcharts/series.venn.dragDrop)), I was under the impression that drag and drop would work as expected. The use cases I have for this are, dragging a set into another to create a link. Or even simply, onDragStart, increase or decrease Value of set according to mouse position. Let me know if this will be possible and thank you for getting back to me.

**Comment by pawellysy** [comment]
In my opinion, this is an oversight in our documentation, where we mention that `venn.dragDrop` is supported, whereas it isn't. I don't really understand the use case, that you explained here. 

IMO this is a bug in the documentation. We should add the list of supported series and double check if the `dragDrop` option is excluded in all of the series, which are not supported. 

@TorsteinHonsi what do you think?
Should `venn` series support drag&drop?

**Comment by TorsteinHonsi** [comment]
@pawellysy Yes, it's a bug in the documentation. Venn never supported drag and drop. And I agree that we should go over all series types and check that `dragDrop` is excluded where it's not actually supported.

**Comment by zachegnermh** [comment]
@pawellysy @TorsteinHonsi Thanks for the clarification
