### ISSUE TITLE
Axis labels not getting displayed once starts updating graph

### ISSUE THREAD

**Issue by shekharshelke07** [highcharts/highcharts#18327]
I have raised a query on Highcharts official forum that axis labels not getting displayed once I start updating the graph.
_link to know the Issues:_ 
[Highcharts Forum Link](https://www.highcharts.com/forum/viewtopic.php?f=9&t=49653) 

as per the reply from Highchart's developer @mfilipiec I'm reporting this as Bug as it's not the issue with the iOS wrapper but is of the library itself.

I have also raised this on GitHub as the issue (Highchrts-iOS )
[highcharts-iOS raised issue link](https://github.com/highcharts/highcharts-ios/issues/410#issue-1535846379)

Kindly refer above links and please suggest a solution for the same.
Thank You!

**Comment by bm64** [comment]
Hello @shekharshelke07 and thanks for contacting us.

Could you describe precisely your use case so I can try to recreate that and see where's the issue?

**Comment by shekharshelke07** [comment]
Hi @bm64 ,

Thank you for your instant reply.

Below are the issues and their reproduction steps:

1. Axis labels not showing properly i.e. some labels are not getting displayed once start searching.
To reproduce this:
- Search in the text field with any single character OR tap on the 'See More Tags' button at the bottom.
- Even when searching with multiple characters the alignment of the bar gets shifted to the center.
- This is happening with filters applied, by clicking the Negative/Neutral/Positive buttons above the graph. 

2. Axis labels not getting multi-lined when the length of the label is larger.
To reproduce this:
- We can see the first label 'Staff/staff/staff/mystaff/goodstaff' not getting multi-lined which is expected due to which graph plot area gets shrunk.

you can see the above issues in the provided demo on GitHub by running code:  [Demo Link](https://github.com/shekharshelke07/Highcharts-Code-Sample.git)

3. In the Arabic language, We are not able to see percentages when we clicked on the 'See More Tags' as shown below:
 
![percentage_display_issue_onSeeMoreTagsClick (1)](https://user-images.githubusercontent.com/70220444/213905347-5c90fe42-47f3-4abd-a885-8e5122e529a3.png)

Thank you!

**Comment by karolkolodziej** [comment]
Hi! 

The thread that you started here is a bit complex and convoluted...
I tried to recreate your issue but on my end, everything works as expected- [demo](https://jsfiddle.net/BlackLabel/tph0dj9f/).

We use GitHub to track bugs and this looks more like a support issue. 
I'm not saying that there is everything ok, perhaps there is a bug somewhere but if you are not able to recreate it, my hands are tight and I will not be able to help you.


Could you please use[ the available support channels](https://www.highcharts.com/blog/support/) to first sort out the issues that are in this example?
If you find any bugs, please **use the form** (proper issue description, demo and steps to reproduce) to report them.
