### ISSUE TITLE
 When adding a point with an id attribute, gantt's point will be one more than expected

### ISSUE THREAD

**Issue by 4blacktea** [highcharts/highcharts#18321]
In the gantt diagram, when adding a point with an id attribute, the gantt point will be one more than expected. If my description is not clear, you can refer to the following figure.
![image](https://user-images.githubusercontent.com/81417218/213143394-86cccdfe-6e31-42d5-952d-7725eac9477f.png)
![image](https://user-images.githubusercontent.com/81417218/213143215-ca38324b-4f22-4a64-a8e4-30895c66157d.png)
![image](https://user-images.githubusercontent.com/81417218/213143350-a77bb84e-25ae-47b3-b0cd-1bece6eaaea1.png)

**Comment by 4blacktea** [comment]
Here is the problematic code, maybe this will help
[ganttdemo.txt](https://github.com/highcharts/highcharts/files/10444707/ganttdemo.txt)

**Comment by pawellysy** [comment]
hi @4blacktea, Thanks for reporting your problem! 
https://jsfiddle.net/BlackLabel/1u0d2qot/7/

`Internal note` 
After adding the point, the `Series.addPoint` method is called twice for some reason.

**Comment by pawellysy** [comment]
This issue was already reported here: https://github.com/highcharts/highcharts/issues/11439

**Comment by 4blacktea** [comment]
> 

Use setdata() instead of addpoint() to find the same problem. When calling setdata() for the second time, although it is not shown on the ui, there will actually be an additional node. I found a temporary solution. Before using setdata() every time, just use chart. series [0]. setData ([]) to clear it, but this is not an elegant solution. I hope to find out the underlying cause of the problem.

**Comment by pawellysy** [comment]
Thanks for additional information!
