### ISSUE TITLE
Heatmap  Single border for Selected section

### ISSUE THREAD

**Issue by vishalpawar048** [highcharts/highcharts#18356]
Hi Team,

Can we do single border for the selected consecutive cells in heatmap? [PFA.]

![image](https://user-images.githubusercontent.com/19291659/214330677-5d74d6c4-06e0-4ff2-81c3-8c4aecb0b5c7.png)

**Comment by pawellysy** [comment]
Hello @vishalpawar048, thanks for reaching out to us!
We don't support this feature right now, but this is achievable through some custom configuration. For further details, please reach out to us via [our available support channels](https://www.highcharts.com/blog/support/)
