### ISSUE TITLE
custom resetZoomTitle  not applied

### ISSUE THREAD

**Issue by equilerex** [highcharts/highcharts#18380]
#### Expected behaviour
`Highcharts.setOptions({lang: {resetZoomTitle: 'Hello'} })`
should set reset zoom button text to 'Hello'

#### Actual behaviour
Text stays at "reset zoom"

#### Live demo with steps to reproduce
 [https://jsfiddle.net/2nhgbpzc/](https://jsfiddle.net/2nhgbpzc/)

#### Product version
Highcharts JS v10.3.3 (2023-01-20)

#### Affected browser(s)
All

I believe the issue lies in  `public showResetZoom(): void {`
[on this line](https://github.com/highcharts/highcharts/blob/4eddd3f8f28277987b4ed087f5e95ba766d2c78e/ts/Core/Chart/Chart.ts#L3533)

where lang property is defined using `lang = defaultOptions.lang,` and later used as `lang.resetZoomTitle`

while looking at other instances in the same file, it should most likely be `lang = merge(defaultOptions.lang, (userOptions?.lang || {}));`
or maybe even `lang = this.options.lang` ?

**Comment by bm64** [comment]
Hello @equilerex and thanks for contacting us.

As you can read in the API about `resetZoomTitle`: 

> The tooltip title for the label appearing when a chart is zoomed.

This property allows you to set text for the label that appears when you hover reset zoom button and it seems to work correctly.

`resetZoom` is most likely what you're looking for: https://jsfiddle.net/BlackLabel/g8sxeufo/
API reference: https://api.highcharts.com/highcharts/lang.resetZoom
