### ISSUE TITLE
Animation CSS no output animation when hovering between points in some series (heatmap and map confirmed)

### ISSUE THREAD

**Issue by hihajdus** [highcharts/highcharts#18394]
#### Expected behaviour
A CSS animation should appear in the output.

https://user-images.githubusercontent.com/22296099/215152061-a3888873-01f7-47e6-98f5-03333e4fd19f.mov

#### Actual behaviour
CSS animation doesn't appear in the output for the specified data points.

https://user-images.githubusercontent.com/22296099/215152098-9d8b76e5-cb33-4f76-9765-52b4dcaf0f3e.mov

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5js701wu/

#### Product version
Highmaps

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Also happens in heatmap making this not a Maps-specific problem.
https://jsfiddle.net/BlackLabel/5js701wu/1/
