### ISSUE TITLE
"Missing name after . operator" error test failure

### ISSUE THREAD

**Issue by Brahmansh** [highcharts/highcharts#18406]
#### Expected behaviour
There should be no test failure with error 'Missing name after . operator'

#### Actual behaviour
SyntaxError: missing name after . operator

In our jsUnit Test, its throwing error 'Missing name after . operator' in Highcharts.js
We found that its complaining for lines where its using 'final' as object property.
e.g. 
labelPosition.final.x
labelPosition.final.y
labelPosition.final.x = x;
labelPosition.final.y = y;

It could be because 'final' is considered as future reserved word - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar
Or the rhino version 1.7.11 used.

But if we replace it with different syntax it FIXES the error e.g - labelPosition["final"]["x"] 

#### Product version
Highcharts 10.3.1

**Comment by pawellysy** [comment]
Hello, @Brahmansh thanks for reporting the problem! 
Could you specify what are you exactly testing and where the issue is located? Thanks!

**Comment by Brahmansh** [comment]
We downloaded highcharts and using it in our code, so when we ran unit test locally it complained about lines of code in highcharts. But to find the error you can search for above given 4 lines of code in the highcharts.src.js file. I believe its related to Piechart code.

**Comment by TorsteinHonsi** [comment]
@pawellysy Yes, go for it!

**Comment by TorsteinHonsi** [comment]
It comes from here:

https://github.com/highcharts/highcharts/blob/a741999cc36bc5a76864823bea144ba693d24d33/ts/Series/Pie/PieDataLabel.ts#L429-L430

While we're at it we need to type it to get away from the `any` cast. Also using a different word than 'final' is better than quoting it in square brackets.

**Comment by jakubSzuminski** [comment]
Issue solved here: https://github.com/highcharts/highcharts/pull/18438
