### ISSUE TITLE
Arearange - blinks (addPoint)

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1841]
Arearange blinks when point is added. 

http://jsfiddle.net/k8EKj/

**Comment by KacperMadej** [comment]
+1

**Comment by sebastianbochan** [comment]
+1

**Comment by KacperMadej** [comment]
Since 5.0.0 the animation problem is more visible.

**Comment by Izothep** [comment]
It looks that similar issue is visible in areaspline stacked charts.

Live demo: http://jsfiddle.net/BlackLabel/sr9gfumj/7/

**Comment by TorsteinHonsi** [comment]
_Internal note:_
The problem is probably caused by the area path going down to the baseline in the start and end, in turn probably caused by the cliff logic for null points: http://jsfiddle.net/highcharts/k8EKj/8/
