### ISSUE TITLE
Add y-scale logarithmic axis to Windrose chart

### ISSUE THREAD

**Issue by tkreyche** [highcharts/highcharts#18422]
The Windrose chart has an inherent flaw that is not specific to your implementation of it. But it can (probably) be resolved if you allow a y-axis log scale option. I've tried log scale on the y-axis and it throws an error. I don't see the option documented for the Windrose chart.

The problem is pretty simple: a high wind event is not (or barely) visible on the Windrose chart under the following conditions:
1) it is of relatively short duration
2) the direction of the event is not consistent with the otherwise prevailing wind 

In this case the chart "pie slice" will be extremely short and this event show up so small on the chart that it's invisible. 
It may be that the chart is more designed to show typical events, but it having a y-axis log scale would add flexibility.

One option is to show two Windrose charts side by side, with one restricting the y-axis maximum to 5% or so and not restricting the other chart's y-axis but is not ideal since it takes more real estate and may be confusing to some people.

thanks, Tom Kreyche

**Comment by TorsteinHonsi** [comment]
#### Workaround
Until the fix is released - the columns that extend to the end are 0-value columns. By replacing 0 by a very small value it should render okay.
