### ISSUE TITLE
Organization Chart link labels

### ISSUE THREAD

**Issue by xuren-sunventure** [highcharts/highcharts#18423]
I would like to add text on the "links" from one node to the next in an organization chart. I can't seem to find in the docs how to format the links with custom labels.

Thank you!

**Comment by pawellysy** [comment]
Hello @xuren-sunventure, thanks for suggesting the idea!
In future, please use our templates when reporting new issues.

**Comment by TorsteinHonsi** [comment]
@pawellysy Other node/link series support `dataLabels.nodeFormat` and/or `dataLabels.linkFormat`. For example the [sankey series](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/sankey-link-datalabels/). Maybe you can do a quick investigation on why this doesn't work with the org chart? There may be an easy fix for it.

**Comment by xuren-sunventure** [comment]
I believe likewise for Network graphs as well, thanks @TorsteinHonsi  @pawellysy !

**Comment by jakubSzuminski** [comment]
@xuren-sunventure you can use `dataLabels.linkFormat` in Network Graphs. Here's an example: https://jsfiddle.net/BlackLabel/zaefhrbo/
