### ISSUE TITLE
Column / scatter - markers different position

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1843]
Scatter markers are not positioned in the same places as other elements like columns. To introduce better please take look at example: 

http://jsfiddle.net/p3bkj/1/

Some of markers are aligned to the right edge.

**Comment by rychoo2** [comment]
Hi, Both jsfiddle examples from this issue still reveal the problem. 
I believe it should be re-opened?

**Comment by pawelfus** [comment]
It used to work in 3.0.3 version (after commit above release date), but in 3.0.4 was broken again.
[3.0.3](http://jsfiddle.net/p3bkj/14/) vs [3.0.4](http://jsfiddle.net/p3bkj/14/).

Thank you for pointing this out!

**Comment by raffaelmeier** [comment]
any news? It's really annoying, but I know, maybe it's a lot of work... (but also the workarounds are...)

**Comment by raffaelmeier** [comment]
(just wanted to reactivate this thread, hope for understanding)

**Comment by TorsteinHonsi** [comment]
It seems like things are a bit more predictable for the column series now, but scatter always uses Math.floor. The irony is that it uses Math.floor as an [old workaround for this issue](https://github.com/highcharts/highcharts/blob/v5.0.14/js/parts/Series.js#L3062).

If we work around that, and additionally assure there is a fixed size for the elements, they align perfectly: http://jsfiddle.net/highcharts/p3bkj/41/

**Comment by ppotaczek** [comment]
Hi, I came across similar problem with markers which sometimes align to the left side of column, sometimes to the center. Even after the wraper has been added markers won't align in exact center of columns.

Demo: https://jsfiddle.net/ppotaczek/ydykbakn/

![screen shot 2017-10-11 at 17 11 50](https://user-images.githubusercontent.com/22988131/31449957-8474231c-aea8-11e7-90cb-c41288451ee4.png)

**Comment by TorsteinHonsi** [comment]
@ppotaczek Since the markers have a fixed size, It would also be better to set a fixed pixel `pointWidth` for the red columns: https://jsfiddle.net/ydykbakn/1/.
