### ISSUE TITLE
Gantt Chart: Tooltip misplaced on navigator zooming

### ISSUE THREAD

**Issue by dcaudillo99** [highcharts/highcharts#18435]
#### Expected behaviour
After zooming in using the navigator, the tooltip position should be placed on the left side of the chart.

#### Actual behaviour
After zooming on a bar, the tooltip is placed outside of the chart
![ezgif com-gif-maker](https://user-images.githubusercontent.com/98132916/216401244-ff421fd2-bc10-4f31-b912-644847b1d2b5.gif)

#### Live demo with steps to reproduce

- Zoom in on the navigator
- Hover on the first bar

https://jsfiddle.net/rzhwcug7/

#### Product version
Highcharts v10.3.3 (latest)

#### Affected browser(s)
Tested  version 109.0.5414.119 (arm64)

**Comment by hihajdus** [comment]
@dcaudillo99 Thanks for reporting this issue,

As a workaround until the bug is fixed you can use an older version of Highcharts Gantt, 
the problem has been present since version 9.0.0.

https://jsfiddle.net/BlackLabel/Luockm8g/

**Comment by Xavier9922** [comment]
I don't think going back to a previous version should be defined as a workaround, v9 has it's own set of issues and reverting to this release will certainly affect multiple functionalities. It will be great to get more visibility for this issue.

**Comment by karolkolodziej** [comment]
@Xavier9922 In this case, as a workaround, you can use a custom tooltip positioner ([API](https://api.highcharts.com/highcharts/tooltip.positioner))- [demo](https://jsfiddle.net/BlackLabel/brnwqf0m/).
