### ISSUE TITLE
Add point.percentage property for solidgauge chart type

### ISSUE THREAD

**Issue by vitaliy-kretsul** [highcharts/highcharts#18433]
This property is currently supported for stacked charts or pies. It would be convenient to have it for solid gauge chart type as well, considering that displaying gauge as a percentage is a pretty common use case.

**Comment by karolkolodziej** [comment]
Hi @vitaliy-kretsul. 
Could you please elaborate on how the percentage value should be calculated for the `solidgauge` points?

In `pie` it is rather straightforward, you check the `point.value / sumOfPointsInPie` but I don't see how it should work in the `solidgauge` series.

**Comment by TorsteinHonsi** [comment]
I imagine it would make sense to calculate the percentage on the `yAxis` like this: https://jsfiddle.net/highcharts/fcwL4r9s/

This is quite simple to implement, I'll mark it good for beginners. Make sure it is implemented in the `gauge` series types, that the solid gauge inherits from.

**Comment by vitaliy-kretsul** [comment]
@karolkolodziej 
I am not sure what is the best way to calculate it, but here is what I am doing currently to get percentage: https://jsfiddle.net/Cortez/7vtx5kmn/
The 'percentage' property is present on 'point' object, but it is undefined. But for pie chart it is there, and it is very convenient to use it.

**Comment by karolkolodziej** [comment]
Thank you @vitaliy-kretsul for additional feedback!

That is what I was hoping to see, now everything is clear!

**Comment by hubertkozik** [comment]
Closing as completed in https://github.com/highcharts/highcharts/pull/18448.
