### ISSUE TITLE
Poor handling of out of range arearange series values in polar charts

### ISSUE THREAD

**Issue by cfarmerga** [highcharts/highcharts#18441]
#### Expected behaviour
In a polar chart with an arearange series, a data value for that series that extends beyond the lower limit of the axis should not actually be rendered below that lower axis limit.

#### Actual behaviour
When the arearange data value is below the axis min, then the arearange is drawn on the other side of the chart.  This causes it to look a lot like a valid value on another axis.

#### Live demo with steps to reproduce
https://jsfiddle.net/cfarmerga/cub7fa90/1/

1. The fiddle demo shows a series of 4-axis polar charts and 4-axis non-polar charts each with the same config.
2. It has an arearange series, and a single data point on the "MW" axis is lowered incrementally across each of the charts. 
3. As the value of that data goes below the MW axis minimum of 100, the value starts to look like a valid value on the "#HD" axis.
4. I think the value should not be plotted beneath the axis minimum.
5. In the non-polar example of the same chart, the behavior looks fine, since values below the axis minimum are just off the plotting surface and are not visible.
![image](https://user-images.githubusercontent.com/341051/216670748-0b4c0c56-a4ed-437e-8f0a-230af25da5e3.png)

#### Product version
10.3.3

#### Affected browser(s)
Chrome, Edge, Firefox

**Comment by bm64** [comment]
Hello @cfarmerga and thanks for reporting the bug.

Simplified demo: https://jsfiddle.net/BlackLabel/qsvLgjpe/
Demo without parallel coordinates: https://jsfiddle.net/BlackLabel/n9h2jm4o/
