### ISSUE TITLE
Moving Annotations Bug

### ISSUE THREAD

**Issue by RPRed1981** [highcharts/highcharts#18459]
#### Expected behaviour
After drawing an annotation (such as a trend line) on a chart it should be possible to edit it to change the position by clicking it and moving it with the mouse.

#### Actual behaviour
In the following situation when trying to move an annotation with a mouse the movement of the annotation doesn't track the position of the pointer:
- Set up a stock chart with a reasonably long timeseries of data
- Set the view to less than the full range - eg 1 Year
- Add an indicator - in my testing I've used SMA and EMA indicators
- Draw a simple annotation such as a line
- If you try to move this annotation it won't track the mouse

This bug only seems to appear under those specific conditions. If the technical indicator is removed or the zoom level is set to view the full timeseries then the annotation can be moved as expected.

#### Live demo with steps to reproduce
It is possible to reproduce this with the standard Stock Tools GUI example chart:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui

#### Product version
 Highstock JS v10.3.3 (2023-01-20)

#### Affected browser(s)
Firefox 109.0.1 on Fedora (64-bit)
Chromium Version 109.0.5414.74 (Official Build) Fedora Project (64-bit)

**Comment by karolkolodziej** [comment]
Hi @RPRed1981! 
Thank you for reporting the issue.

The issue was introduced in v10.3.3 by https://github.com/highcharts/highcharts/commit/5c8073585fd11f1ecfa4e9e737219952bd1fc171 - [simplified demo.](https://jsfiddle.net/BlackLabel/2s5k9vcx/)

As a workaround, you can use the previous version.

**Comment by RPRed1981** [comment]
Thanks for the quick response. I have downgraded to version 10.3.2 of the Highstock JS and confirm that this fixes the issue.

**Comment by rmasheck** [comment]
any idea on fixing this issue. we would like to  upgrade to latest version (11) but can not because this is major issue for financial clients.

**Comment by kamil-musialowski** [comment]
Hello @rmasheck, we are still actively working on fixing this issue. 

Thank you for your patience!

**Comment by pawelfus** [comment]
v11 workaround:

Demo: https://jsfiddle.net/BlackLabel/8fae0dnw/

Plugin:
```js
(function(H) {
  const OrdinalAdditions = H._modules['Core/Axis/OrdinalAxis.js'].Additions;

  OrdinalAdditions.prototype.getIndexOfPoint = function(
    val,
    ordinalArray
  ) {
    const ordinal = this,
      axis = ordinal.axis,
      firstPointVal = ordinal.positions ? ordinal.positions[0] : 0;
    let firstPointX = axis.series[0].points &&
      axis.series[0].points[0] &&
      axis.series[0].points[0].plotX ||
      axis.minPixelPadding; // #15987
    // When more series assign to axis, find the smallest one, #15987.
    if (axis.series.length > 1) {
      axis.series.forEach(function(series) {
        if (
          series.points &&
          H.defined(series.points[0]) &&
          H.defined(series.points[0].plotX) &&
          series.points[0].plotX < firstPointX
        ) {
          firstPointX = series.points[0].plotX;
        }
      });
    }
    // Distance in pixels between two points on the ordinal axis in the
    // current zoom.
    const ordinalPointPixelInterval = axis.translationSlope * (
        ordinal.slope ||
        axis.closestPointRange ||
        ordinal.overscrollPointsRange
      ),
      // toValue for the first point.
      shiftIndex = (val - firstPointX) / ordinalPointPixelInterval;

    return OrdinalAdditions.findIndexOf(
      ordinalArray,
      firstPointVal
    ) + shiftIndex;
  }
})(Highcharts);
```

Note: Plugin reverts changes after v10.3.3, meaning #17128 issue remains.

**Comment by rmasheck** [comment]
Thanks a lot for workaround. we are using workaround for *17128.. so this would be really helpful
