### ISSUE TITLE
The border of `columnrange` chart is cut off

### ISSUE THREAD

**Issue by wakkihaya** [highcharts/highcharts#18457]
Hi there! I was wondering if some of you could teach me the workaround regarding this `columnrange` chart issue.

#### Expected behaviour
`columnrange` chart with the border should be resized based on axis so its border isn't cut off.

#### Actual behaviour
The `columnrange` chart(the purple one below the pic) is cut off.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/46864179/217482296-60044d6b-b29a-4fe7-a31f-6f4c40df8fb3.png">

#### Live demo with steps to reproduce

https://jsfiddle.net/7Lrbkov1/8/

**Comment by karolkolodziej** [comment]
Hi @wakkihaya.

In cases like this, please set the series `clip` to false ([API](https://api.highcharts.com/highcharts/series.columnrange.clip))- [simplified demo.](https://jsfiddle.net/BlackLabel/o8bxLn4q/)

In your example, you have to make some space on the left to see that border -[demo](https://jsfiddle.net/BlackLabel/a76r4k9f/).

For future reference, with questions like this, please use [available support channels](https://www.highcharts.com/blog/support/) first before contacting us on GH.

**Comment by wakkihaya** [comment]
Hi @karolkolodziej !
Thank you for the quick reply! it's working now.

> For future reference, with questions like this, please use [available support channels](https://www.highcharts.com/blog/support/) first before contacting us on GH.

Sure thing
