### ISSUE TITLE
Single-button `Breadcrumbs` not working in `Treemap`

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#18458]
#### Expected behaviour
Single-button `breadcrumbs` should work in `treemap` just like in other series (`column` for example).

#### Actual behaviour
In a `treemap` chart, `drilldown.breadcrumbs` seems to be overriden and there is no way to have a single-button `breadcrumbs` like on Highcharts demo pages. It should work just like in other types of series: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/breadcrumbs/single-button

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/j5xqf6bL/

#### Product version
Highcharts 10.3

**Comment by rdp1414** [comment]
Our stakeholders are facing this problem while upgrading highcharts for `treemap` series type. I reported at [Topic#50291](https://www.highcharts.com/forum/viewtopic.php?f=9&t=50291). Is there any rough ETA for this bug-fix?

**Comment by bm64** [comment]
@rdp1414 in Tree map series, breadcrumbs options should be defined directly in series config, not in drilldown options. You can read about it in our API: https://api.highcharts.com/highcharts/series.treemap.breadcrumbs
Demo: https://jsfiddle.net/BlackLabel/c5x7sgwf/
