### ISSUE TITLE
v10.3.3 - loading JS (via local or via CDN) includes additional CDN src.js copies of the files

### ISSUE THREAD

**Issue by gerard-ninnes-cer** [highcharts/highcharts#18463]
Hi HighChart devs, apologies if this isn't the right place to report this, or if I missed a new relevant feature somewhere along the way.

I'm in the process of preparing to upgrade from v9.2.2 to v10.3.3. This is the only peculiar behaviour I noticed when testing. 

## Expected behaviour
The JS files (es5 or es6) I include via <script> tags are the ones loaded.

## Actual behaviour
As well as the specified JS files loading from the local or CDN location, _additional_ CDN copies of the files are loaded, and not always from the same set (es5 or es6).

### Example 1: Loading CDN copies of es5 JS via JS fiddle

http://jsfiddle.net/gn_cer/mL9eg1v3/40/

The below image shows what is loaded in the browser when the below JS files are specified:

```html
<script src="https://code.highcharts.com/10.3.3/es5/highcharts.js"></script>
<script src="https://code.highcharts.com/10.3.3/es5/modules/exporting.js"></script>
<script src="https://code.highcharts.com/10.3.3/es5/modules/accessibility.js"></script>
```
The effect is harder to notice via a JS fiddle seeing as everything is already coming from the CDN, but odd things in this example:
* the CDN `.src.js` copies of the above files are loaded as well.
* the es6 version of `expoting.src.js` is loaded.

<img width="152" alt="JS fiddle example" src="https://user-images.githubusercontent.com/116783094/217726986-bbfac68e-0a8c-4e7b-aee1-9bb3faed6105.png">

### Example 2: Loading local files using the new es5 specific versions**

The below image shows what is loaded in the browser when the below JS files are specified.

```html
    <script src="/vendor/highcharts-10.3.3/code/es5/highcharts.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/es5/modules/data.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/es5/modules/drilldown.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/es5/modules/sunburst.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/es5/modules/pattern-fill.js"></script> 
    <script src="/vendor/highcharts-10.3.3/code/es5/modules/exporting.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/es5/modules/export-data.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/es5/modules/boost.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/es5/modules/accessibility.js"></script>
```

Odd things in this example:
* CDN copies of all the modules are loaded _as well_ as the local copies.
* all CDN files are load as the `src.js` copies of the files, not `.js`.
* some of the CDN modules load as the es6 src.js versions.

<img width="182" alt="local inclusion es5" src="https://user-images.githubusercontent.com/116783094/217726992-cabf701e-863d-465c-97b9-ae0b965a75c3.png">

### Example 3: Loading local files using the new es6 specific versions**

The below image shows what is loaded in the browser when the below JS files are specified.

```html
    <script src="/vendor/highcharts-10.3.3/code/highcharts.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/modules/data.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/modules/drilldown.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/modules/sunburst.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/modules/pattern-fill.js"></script> 
    <script src="/vendor/highcharts-10.3.3/code/modules/exporting.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/modules/export-data.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/modules/boost.js"></script>
    <script src="/vendor/highcharts-10.3.3/code/modules/accessibility.js"></script>
```

Odd things in this example:
* CDN copies of all the modules are loaded _as well_ as the local copies.
* all CDN files are load as the `src.js` copies of the files, not `.js`.

<img width="169" alt="local inclusion es6" src="https://user-images.githubusercontent.com/116783094/217726993-e8784066-a0c1-42ee-9382-b8e03a78621c.png">

## Product version
Highcharts v10.3.3

## Affected browser(s)
I've so far only tested this in Edge v109.0.1518.78.

**Comment by karolkolodziej** [comment]
Hi @gerard-ninnes-cer! 
Thank you for describing your issue in such detail! 

As far as I can see, that is not an issue with our CDN, it looks more like the browser dev tools configuration.

I tested it on chrome but Edge should work the same. 
There is a way in the browser to map the compiled code to a more readable form for the human eye, this feature is called `JavaScrip source map`.

To disable source maps in Microsoft Edge, you can follow these steps:

1. Open Microsoft Edge and navigate to the web page you want to disable source maps for.
2. Press the F12 key or right-click on the page and select "Inspect Element" to open the F12 Developer Tools.
3. In the F12 Developer Tools, click on the "Settings" (gear) icon in the lower-right corner of the window.
4. In the "Debugging" section, uncheck the "Enable JavaScript Source Maps" option.
5. Close the F12 Developer Tools and the changes will be saved.


Please let me know if this solves your issue.

**Comment by gerard-ninnes-cer** [comment]
Hi @karolkolodziej! 
Thanks for the reply. 
I did not know that was a feature. It's great to learn about it.

That _did_ solve most of the problem, but also confused me a bit. 

Remaining questions:

* With the Edge browser setting turned on, these src.js files _do_ load when using Highcharts v9.2.2, but they load from the same source as the rest of the files (eg: local). In v10.3.3 they always load from the CDN. Is that an intended change in behaviour? 
* In v10.3.3, how come sometimes the es6 version of a module's src.js is loaded instead of the es5 version?

**Comment by bre1470** [comment]
Hi @gerard-ninnes-cer,
Please excuse the delay. We struggle to reproduce it. It could be an issue with the source maps in the `es5` branch or an issue with local cache and guessed preloading. For `.src.js`-files we actually do not provide a source map as they are the source them self.
