### ISSUE TITLE
Windows Display Scaling draws options incorrectly

### ISSUE THREAD

**Issue by melloware** [highcharts/highcharts#18470]
#### Expected behaviour
Windows Display Scaling should not change chart rendering behavior.

#### Actual behaviour

When using any chart and setting `exporting enabled:false` and `legend : maxHeight: 200` and Windows 10 display scaling we are seeing different behavior just by changing the display scaling.  At 200% the chart renders correctly and at 225% the exporting button appears and the legend is compacted.  No other changes I can make this happen just by changing the scaling.  

200% Scale displays **correctly**:
![image](https://user-images.githubusercontent.com/4399574/217834891-5abc5bd3-7d65-4b0f-8a9f-51dc11876f7d.png)

225% Scale display **incorrectly** and shows the exporting buttons if false and the legend doesn't respect max height:
![image](https://user-images.githubusercontent.com/4399574/217835039-9e1b4627-1d82-48ad-ba3f-28e4967029f8.png)

Notice in the 225% the export button now appears and the legend is crunched not respecting Max Height anymore.

![image](https://user-images.githubusercontent.com/4399574/217834617-5ea57cf7-03d3-48d6-a3da-817b94aa2d00.png)

#### Product version
HighCharts 10.3.3

#### Affected browser(s)
Firefox, Chrome, Edge

**Comment by karolkolodziej** [comment]
Hi @melloware! 

Could you please share this example so I could test this on my own?

**Comment by melloware** [comment]
OK here is a JSFiddle: https://jsfiddle.net/t7wyqrh4/14/

Try it at 100% then 175%.

I think I know the issue now but want to see what you say...

**Comment by melloware** [comment]
OK I got to the bottom of the issue.  Windows Display Scaling was triggering the "responsive" options to kick in.
