### ISSUE TITLE
Line series markers are disappearing after point update

### ISSUE THREAD

**Issue by hubertkozik** [highcharts/highcharts#18474]
#### Expected behaviour

After updating the point on its click event markers on the line series will be shown and enabled. Hovering and clicking points should be possible.

#### Actual behaviour

After updating the point from `point.events.click` event markers are disappearing. After updating the point from another place everything is working correctly.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/h7Lkn589/

1) Click on the button 'Update point' - the point has been updated and everything is working correctly.
2) Click on any point, for example - markers have disappeared and you cannot hover/click the updated point.

#### Product version
Highcharts v10.3.3

**Comment by Vazonik** [comment]
Markers disappear in a line chart by default when there are points with the same x. It has nothing to do with the update method.

Also, the line chart has the `findNearestPointBy` option set to `x`, which makes it impossible to hover over multiple points with the same x. Changing it to `xy` should make everything work as expected.

See: https://jsfiddle.net/BlackLabel/09cvj5oq/
