### ISSUE TITLE
Pre-release regression with immediate redraw

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#18478]
#### Expected behaviour
The chart should render once

#### Actual behaviour
When the container has no specific height set, the chart is rendered with 400px height, and the container triggers a resize event. Subsequently the ResizeObserver is triggered and the chart redraws.

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/h1wL2bxq/

#### Product version
Pre-release

#### Affected browser(s)
Presumably all
___

@karolkolodziej I'm assigning this to you. I probably caused it myself when I tried to simplify your proposal for #17951, but would appreciate if you had a look at it.

**Comment by TorsteinHonsi** [comment]
Proposed solution: Since this resize event happens because the SVG changes the size of the container - maybe we can avoid it by simply delaying the whole setting of the ResizeObserver until after the SVG has been inserted?

**Comment by karolkolodziej** [comment]
I went throught my PR. I spent some time exploring bd74c3465a85bc722a210fe9b99ea5f5db403ceb and it looks like the problem you are mentioning was neatly masked by `setTimeout` but it was still there.


You suggestion to move the initialization of the `ResizeObserver` seems good- do you have any particular place in mind?
As far as I can see the flow looks like this: `onload()` -> `setReflow()` -> `new ResizeObserver()`

Is there any place/event where we are certain that the size is set? 
Beacause setting fixed time in `setTimeout` doesn't look like a valid solution?

**Comment by TorsteinHonsi** [comment]
@karolkolodziej Sorry I forgot to follow up here.

On inspection, it looks like it is already done this way, it is added after the SVG is inserted:

https://github.com/highcharts/highcharts/blob/3542a8e9e14a8f26549f241633daa5f197f878de/ts/Core/Chart/Chart.ts#L2768-L2771

Can you do some more debugging and see what happens?

**Comment by TorsteinHonsi** [comment]
Still happens if the chart has an explicit height: https://jsfiddle.net/highcharts/wn51zfLe/
