### ISSUE TITLE
Annotations drag issue with IKH indicator

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#18475]
#### Expected behaviour
Annotations should follow the cursor normally when dragged, as in the Highcharts 10.3.2 or without the IKH indicator.

#### Actual behaviour
When there is an IKH indicator, dragged annotations move in an unexpected manner.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/375kd4rn/
1. Draw an annotation on the chart
2. Try to drag it

#### Product version
Highcharts 10.3.3 + StockTools

**Comment by rmasheck** [comment]
FYI -- this is happing with other indicators as well. when there is null values in y like
{x: 1615179600000, y: null}
{x: 1615266000000, y: 223.85464060541725}
if null values are removed.. then things do work

**Comment by bm64** [comment]
_Workaround:_
Use `oridinal: false`: https://jsfiddle.net/BlackLabel/az9wojkp/

_Internal note:_
Bisected to 5c8073585fd11f1ecfa4e9e737219952bd1fc171
