### ISSUE TITLE
Inline style applied when using styledMode with scrollablePlotArea

### ISSUE THREAD

**Issue by geneukum** [highcharts/highcharts#18494]
#### Expected behaviour
When using [styledMode](https://api.highcharts.com/highcharts/chart.styledMode), I would expect no presentational attributes or CSS to be applied to the chart SVG regardless of other options chosen.

#### Actual behaviour
When using [styledMode](https://api.highcharts.com/highcharts/chart.styledMode) with a chart that will have a [scrollable plot area](https://api.highcharts.com/highcharts/chart.scrollablePlotArea), the `highcharts-root` element has inline style: `style="font-family: "Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif; font-size: 12px;"`.

#### Live demo with steps to reproduce
Open https://codepen.io/gneukum1/pen/NWLWgrE on a screen small enough that a scrollablePlotArea will be used (I've set minWidth to 700px for reference).

Open the dev inspector, and locate the svg element with the class `highcharts-root` and note that it has inline styling applied. This is easier to check in the Debug Mode provided by codepen. 

#### Product version
Highcharts v10.3.2

#### Affected browser(s)
This would affect all browsers.

**Comment by bm64** [comment]
Hello @geneukum and thanks for reporting the issue.
