### ISSUE TITLE
Tooltip with useHTML and outside does not cleanup tooltip container

### ISSUE THREAD

**Issue by runfaj** [highcharts/highcharts#18490]
#### Expected behaviour

Tooltips with outside: true and useHTML: true should hide page overflow by default and also cleanup their container when the chart is not actively hovered.

#### Actual behaviour

I noticed a scroll issue bug already reported here: https://github.com/highcharts/highcharts/issues/17561. I was able to work-around that by setting a custom tooltip class that hides overflow. However, highcharts doesn't appear to remove the container after hover every time. The example straight from the docs for useHTML has this issue:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/fullhtml/

You can see if I hover quickly, then move out of the preview area, sometimes the container is left there:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/3292053/218548192-374aabe3-1117-4e2e-9b7a-1a803e7bd3e5.png">

This isn't super noticable, but when you have pages with scroll overflows and fixed positioning rules, this can cause all sorts of undesired page scrolling behavior. This also compounds with more complex charts, or multiple charts on the page.
<img width="625" alt="image" src="https://user-images.githubusercontent.com/3292053/218548450-21e34118-1fb7-4754-a730-142e878d17e3.png">

This is especially problematic on pages that shouldn't be overflowing when you've got taller tooltips, because it can cause a ton of extra whitespace scrolling on the page that isn't desired. Here's an example that seems outlandish, but does come up occasionally.
<img width="274" alt="image" src="https://user-images.githubusercontent.com/3292053/218548784-910a05ca-dcde-4e37-b36f-fa5e53361946.png">

Also for context, because of this overflow and scrolling issue, I essentially had to add the following overrides to the tooltip container to prevent a lot of layout issues I was running into.
```
max-height: 100vh!important;
overflow-y: hidden!important;
position: fixed!important;
z-index: 10000!important;
```

#### Live demo with steps to reproduce
see link above

#### Product version
highcharts 10.3.3, but happened on previous versions also

#### Affected browser(s)
any. Mostly tested in chrome

**Comment by karolkolodziej** [comment]
Hi @runfaj.

By desing we are only hiding the tooltip. It allows to nicely animate the tooltip when showing it again. Also it has some slight positive evect on performance.

But you can overwrite this behaviour- [demo](https://jsfiddle.net/BlackLabel/5wbednry/).
In that demo I added property `destroyWhenHiding` which allows to destroy the tooltip container if needed.

I consider this issue as not a bug.

**Comment by runfaj** [comment]
@karolkolodziej Thanks for the custom function example, this will work great!

**Comment by OW2code** [comment]
Hi any movement on this. Im using useHTML to add a button to the tool tip and when anything is clicked while the tooltip is open the tooltip will get stuck and the app pauses until the tooltip disappears.

Using Angular, create the tooltip in the formatter returning html with custom buttons provided by AllowableAttributes and AllowableTags

**Comment by karolkolodziej** [comment]
@OW2code Could you please contact someone form our [support team](https://www.highcharts.com/blog/support/)?
There we can explain everything and help you in your case.

**Comment by TorsteinHonsi** [comment]
I created a fix for this issue in the [PR above](https://github.com/highcharts/highcharts/pull/19498).

OP demo with the fix applied: https://jsfiddle.net/highcharts/L7j485e9/

**Comment by runfaj** [comment]
> I created a fix for this issue in the [PR above](https://github.com/highcharts/highcharts/pull/19498).
> 
> OP demo with the fix applied: https://jsfiddle.net/highcharts/L7j485e9/

@TorsteinHonsi I might be missing it, but in this fiddle, it looks like the tooltip container still exists at all times. I can see it is not getting duplicated (which is great!), but it isn't fully destroyed.
<img width="598" alt="image" src="https://github.com/highcharts/highcharts/assets/3292053/17149c7d-83c2-4f44-a795-f975bf770b71">

**Comment by TorsteinHonsi** [comment]
@runfaj The fix is not published yet, your fiddle is using the latest release from code.highcharts.com. To test the fix, you must load `https://github.highcharts.com/bugfix/18490-tooltip-outside-container/highcharts.js`.
