### ISSUE TITLE
Docs: Shadows demo on Design and style page not working

### ISSUE THREAD

**Issue by jedrzejruta** [highcharts/highcharts#18505]
On Highcharts docs page: [https://www.highcharts.com/docs/chart-design-and-style/design-and-style#shadows](url) linked demo is not working. 

#### Expected behaviour

Demo is displayed properly in jsfiddle.

#### Actual behaviour

No chart is displayed, request is blocked because Highcharts repository is loaded via HTTP.
`Mixed Content` error is output in console.

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/jYLXN/

#### Product version
Latest Highcharts version

#### Affected browser(s)

Probably most of them, tested on Edge (Chromium), Firefox, Chrome.

**Comment by bm64** [comment]
Thanks @jedrzejruta for reporting.

**Comment by Vazonik** [comment]
Fixed in #18408.
