### ISSUE TITLE
Can't update stock-tools annotation style in StockCharts with styledMode enabled

### ISSUE THREAD

**Issue by moryakovdv** [highcharts/highcharts#18504]
Hi. 
Struggling with stock-tools annotations in styled mode I noticed the editor dialog doesn't apply changes to annotation style after saving.
Pls, see my jsFiddle.

#### Expected behaviour
1. Place the circle annotation from stock-tools panel
2. Its style should be as described in css-rules ```.highcharts-annotation-shapes```
3. Open annotation style editor, change style and press 'save'
4. Annotation styles should change.

#### Actual behaviour
Styles set in editor dialog don't apply to shape.
I tried to call ```annotation.update()``` manually but with no luck.

If you comment ```chart:{styledMode:true}``` it starts to work as expected with default styles from ``` annotationsOptions```

#### Live demo with steps to reproduce
[fiddle](https://jsfiddle.net/z7gcuxs4/2/)

#### Product version
Actual from highcharts.com

#### Affected browser(s)
Probably most of them, tested on Ubuntu 20 + FF v109,  Chrominum v110

Maybe, I miss something.

Thanks in advance.

**Comment by bm64** [comment]
Hello @moryakovdv and thanks for reporting the issue.

**Comment by pawelfus** [comment]
There's one small problem with `styledMode` and EditableAnnotations. In `styledMode`, all styling options are ignored (eg. `strokeWidth: 10`). It is possible to apply config from Popup into CSS directly (that's how the workaround below works). The only problem occurs when we save&load updated annotations. The workaround below applies styles directly on elements in DOM and keeps JS config. That means it is still possible to save the chart's config in a database.

However, loading annotations back in `styledMode: true` chart means options are ignored. I suggest bypassing this by reading the config [after adding an annotation](https://api.highcharts.com/highcharts/annotations.events.add), then applying styles. It should be possible to reuse `setAnnotationCSS(annotation, options)` method from the workaround below.

An alternative workaround is to simply resign from `styledMode`

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/nowazv6m/

Plugin:
```ts
Highcharts.addEvent(
  Highcharts._modules['Extensions/Annotations/NavigationBindings.js'],
  'showPopup',
  onShowPopup,
  { order: 0 }
);

function onShowPopup(e) {
  const navigation = this;

  if (
    e.formType !== 'annotation-toolbar' &&
    this.chart &&
    this.chart.options.chart.styledMode
  ) {
    return;
  }

  const onSubmit = e.onSubmit;

  // Override submnit 
  e.onSubmit = function(popupData) {
    // Call original
    onSubmit(popupData);

    // Ignore removing annotation
    if (popupData.actionType !== 'remove') {
      let config = {};

      // Internal method to generate annotation-options
      navigation.fieldsToOptions(
        popupData.fields,
        config
      );

      // Apply CSS styles to an annotation
      setAnnotationCSS(e.annotation, config);
    }

  }
}

function setAnnotationCSS(annotation, options) {
  // Basic labels:
  if (options.labelOptions) {
    if (options.labelOptions.style) {
      annotation.labels.forEach(label =>
        label.graphic?.css(options.labelOptions.style)
      )
    }
    if (options.labelOptions.backgroundColor) {
      annotation.labels.forEach(label =>
        label.graphic?.box?.css({
          fill: options.labelOptions.backgroundColor
        })
      )
    }
  }
	
  // Basic shapes:
  if (options.shapes) {
    options.shapes.forEach((css, i) => annotation.shapes[i]?.graphic?.css(css))
  }


  if (options.typeOptions) {
    // Lines:
    if (options.typeOptions.line) {
      annotation.shapes.forEach(shape =>
        shape.graphic?.css(options.typeOptions.line)
      )
    }

    // Measure:
    if (options.typeOptions.background) {
      annotation.shapes[2]?.graphic?.css(options.typeOptions.background);
    }

    // Fibo:
    if (options.typeOptions.backgroundColors) {
      annotation.shapes
        .filter((_, i) => i % 2 === 0)
        .forEach((shape, i) =>
          shape.graphic?.css({
            fill: options.typeOptions.backgroundColors[i]
          })
        )
    }

    if (options.typeOptions.labels) {
      annotation.labels.forEach((label, i) =>
        label.graphic?.css(options.typeOptions.labels[i].style)
      )
    }

    // Pitchfork
    if (options.typeOptions.outerBackground) {
      annotation.shapes[4].graphic?.css(options.typeOptions.outerBackground)
    }

    if (options.typeOptions.innerBackground) {
      annotation.shapes[3].graphic?.css(options.typeOptions.innerBackground)
    }
  }
}
```

___
*Internal note:*
As described above, it is not implemented. The workaround is just a very basic implementation. If ever we decide to support this out of the box, then we need Options2CSS parser to bypass styledMode.

Note: At this moment it's not enough to set `styledMode = false` in the `onSubmit` method: https://jsfiddle.net/BlackLabel/f96gpnxe/

**Comment by moryakovdv** [comment]
@pawelfus, thank you very much for the response.
Of course, "not to use styledMode" is obvious solution, but I will try you plugin.

**Comment by moryakovdv** [comment]
Hello. I can confirm the suggested workaround works at least for my current task.
Thanks.
