### ISSUE TITLE
Heatmap: pointPadding with yAxis.reversed is not working correctly

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#18502]
#### Expected behaviour
Points should have a correct 10px padding in all directions like in a normal chart: https://jsfiddle.net/BlackLabel/32h6mpor/
![image](https://user-images.githubusercontent.com/23310742/218748607-a3bbbfa4-4612-4daa-96fe-ab0637389c7f.png)

#### Actual behaviour
Points have wrong pointPadding when `yAxis.reversed: true`: https://jsfiddle.net/BlackLabel/fgyzkce8/
![image](https://user-images.githubusercontent.com/23310742/218748908-d44f3bba-9a80-4218-8b3d-33900aa7994e.png)

#### Product version
Highcharts 10.3.3

Worked fine in 8.0.4, broken since 8.1.0. Unable to bisect.

**Comment by hubertkozik** [comment]
There is also a problem with setting `chart.inverted` to `true`, like in this demo: https://jsfiddle.net/BlackLabel/r2u3dgy6/ Despite setting `pointPadding` the points don't have any padding.
