### ISSUE TITLE
Highcharts drill down on Map chart is not working.

### ISSUE THREAD

**Issue by kiranpawar-gep** [highcharts/highcharts#18509]
Hi Team,

We have integrated high charts world map chart. Map is loading but drill down on map is not working.

Please find below code for your reference.

import { Injectable } from "@angular/core";
import Highcharts from "highcharts/highmaps";
import Drilldown from 'highcharts/modules/drilldown';
Drilldown(Highcharts);
import { Options } from "highcharts";
import { AbstractChartFactoryInterface } from "../interface/abstract-chart-factory.interface";

declare var require: any;
@Injectable()
export class MapChartService implements AbstractChartFactoryInterface {
  Highcharts: typeof Highcharts = Highcharts;
  minMaxTargetValues: any;
  constructor(
    private baseChartConfigService: BaseChartService,
    public _dmDataMgrSvc: DmDataModelManagerService) {
  }

  getChartConfiguration(chartConfig: IHighChartPluginConfig, webworkerSupport?: boolean): Options {
    let mapChartOptions = this.baseChartConfigService.setBaseConfiguration(chartConfig);

    const caMapData = require("@highcharts/map-collection/custom/world.geo.json");
    const caMap = Highcharts.geojson(caMapData);

    // Set a random value on map
    caMap.forEach((el: any, i) => {
      el.value = i;
      el.drilldown = el.properties["hc-key"];
    });

    mapChartOptions.chart = {
      height: (8 / 16) * 100 + "%",
      events: {
        drilldown(e) {
          const chart = this as any;
        
          //onst mapKey = "countries/ca/" + e.point.drilldown + "-all";
          //Stackbliz wont load data if you pass mapkey as variable. So I use a hard code one in this example.
          // const mapData = require(`@highcharts/map-collection/${mapKey}.geo.json`);
          const mapData = require(`@highcharts/map-collection/countries/ca/ca-on-all.geo.json`);
          const provinceData = Highcharts.geojson(mapData);
          // Set a random value on map
          provinceData.forEach((el: any, i) => {
            el.value = i;
          });

          chart.addSeriesAsDrilldown(e.point, {
            name: e.point.name,
            data: provinceData,

            dataLabels: {
              enabled: true
            }
          });

          chart.setTitle(null, { text: e.point.name });
        },
        drillup() {
          const chart = this as any;
        }
      }
    },

    mapChartOptions.title = {
      text: "Highmaps basic demo"
    },
      mapChartOptions.subtitle = {
        text:
          'Source map: <a href="http://code.highcharts.com/mapdata/custom/world.js">World, Miller projection, medium resolution</a>'
      },
      mapChartOptions.mapNavigation = {
        enabled: true,
        buttonOptions: {
          alignTo: "spacingBox"
        }
      },
      mapChartOptions.legend = {
        enabled: true
      },
      mapChartOptions.colorAxis = {
        min: 0
      },
      mapChartOptions.series = [
        {
          type: 'map',
          data: caMap
      }
        
      ],
      mapChartOptions.drilldown= {}

    return mapChartOptions;

  }

}

**Comment by bm64** [comment]
Hello @kiranpawar-gep and thanks for contacting us.

We use github as a feature request / bug tracking tool and without a reproduction of the issue we can't really do anything about that.

Please visit our other support channels where support team will help you with finding out what is the cause of the issue: https://www.highcharts.com/blog/support/
