### ISSUE TITLE
Stack labels' `verticalAlign` doesn't work for logarithmic yAxis.

### ISSUE THREAD

**Issue by Vazonik** [highcharts/highcharts#18501]
#### Expected behaviour
Setting `stackLabels.verticalAlign` in the logarithmic axis to any value works as in the regular axis.

#### Actual behaviour
Setting `stackLabels.verticalAlign` in the logarithmic axis to `bottom` or `middle` makes the labels invisible.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/fntvzh31/

#### Product version
Highcharts v10.3.3

**Comment by NathanManning** [comment]
Please make sure it works with the original data layout as well.

broken: https://jsfiddle.net/o0L9wmhu/
working: https://jsfiddle.net/m9touxh8/1/

**Comment by hubertkozik** [comment]
Hi guys! There is a problem with calculating the 0 value to pixels on logarithmic axes - I will fix in HC Core. Now, I have a workaround for that issue, which overrides an HC method. You can check the demo below (the plugin is inside the IIFE function). A similar solution will be used in HC Core.

**Workaround demos:** https://jsfiddle.net/BlackLabel/w8ck6osf/
https://jsfiddle.net/BlackLabel/m5zpf0wh/
