### ISSUE TITLE
high charts multi-charts in one when alightick=true, one y-axis will auto scale up and exceed the business meaningfull value 100%.

### ISSUE THREAD

**Issue by hahazhugithub** [highcharts/highcharts#1850]
how can we use aligntick=true  and let percentage values with decimals and max value.

**Comment by oysteinmoseng** [comment]
This should be doable with [tickPositioner](https://api.highcharts.com/highcharts/yAxis.tickPositioner): http://jsfiddle.net/h78g55hh/
