### ISSUE TITLE
Wrong symbol color in legend for negative values in area chart

### ISSUE THREAD

**Issue by roger-zacharczyk** [highcharts/highcharts#1852]
Since I can set negative values color for area chart (for example with threshold == 0) chart will have  two different colors but the legend still shows only one of them, it'll show only positive color. Legend symbol (rectangle) should be divided in two.

**Comment by TorsteinHonsi** [comment]
See http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/studies/legend-custom-symbol/ for an example of a custom legend symbol.
