### ISSUE TITLE
Highstocks: Current Price Indicator Label show the wrong point after changing chart type.

### ISSUE THREAD

**Issue by hihajdus** [highcharts/highcharts#18528]
#### Expected behaviour
Price indicator should show price form last visible point.

#### Actual behaviour
After changing chart type, current price indicator show a label for the wrong point (before last instead of last).

https://user-images.githubusercontent.com/22296099/220066853-eaed1684-79f6-4b41-8da1-409e6c7a756d.mov

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/f7sc854n/

#### Product version
Highstock JS v10.3.3 (2023-01-20)

#### Affected browser(s)
All

**Comment by kamil-musialowski** [comment]
**Workaround:** Disable dataGrouping on `plotOptions.series` level.

https://api.highcharts.com/highstock/plotOptions.series.dataGrouping.enabled

Demo: https://jsfiddle.net/BlackLabel/mo8rj9c5/
