### ISSUE TITLE
Documentation website is not functioning

### ISSUE THREAD

**Issue by fralik** [highcharts/highcharts#18521]
#### Expected behaviour
1. Go to https://www.highcharts.com/docs/index
2. Be able to click and navigate on items in the left menu (like `Getting started`, e.t.c.)

#### Actual behaviour

All links point to `https://www.highcharts.com/docs/index#!`, which leads nowhere. As a result, I could only access documentation via (external) search.

#### Affected browser(s)

Tested in Windows 11 Firefox v110.0 and Edge v110.0.1587.49

**Comment by goransle** [comment]
Thanks for letting us know. This was an issue with caching on the main javascript file, and has been resolved by our web team.
