### ISSUE TITLE
Accessibility: The default colorful chart labels don't have sufficient contrast to fulfill WCAG criteria

### ISSUE THREAD

**Issue by rezinak** [highcharts/highcharts#18522]
#### Expected behaviour
Text provides sufficient contrast. The following contrast ratios are required:

Text smaller than 18 pt (24 px), or smaller than 14 pt (19 px) if bold, must have a color contrast ratio of 4.50:1 or more with adjacent colors.

#### Actual behaviour
* The green "NVDA" text only has a contrast ratio: 3.797:1
* The turquoise "ZoomText/Fusion" text only has a contrast ratio: 3.175:1
* The orange "Other" text has a contrast ratio: 3.027:1

Users with low vision will have difficulty reading this content.

#### Live demo with steps to reproduce
https://www.idc.com/QA_test_section/accessibility-remediation/highcharts-demo1 

#### Product version
Highcharts JS v10.3.3

#### Affected browser(s)
Chrome and Mozilla, haven't looked into the others

**Comment by oysteinmoseng** [comment]
Hi, good point, we should add some logic to deal with this automatically. Marking as feature request.

It is possible to manually set these colors by setting `series.label.style.color`, either for all labels or for individual ones: https://jsfiddle.net/oysteinmoseng/jyn75uq2/

**Comment by TorsteinHonsi** [comment]
The logic connection to the series gets weakened if the label doesn't use the series color, so we would need some other way to connect them. In some case the serie lines are so close that the same label may be close to two or more graphs. A connector line back to the series line would make it absolutely clear which series the label belongs to. The [connectorNeighbourDistance](https://api.highcharts.com/highcharts/plotOptions.series.label.connectorNeighbourDistance) option should possibly handle this, but it doesn't seem to have an effect in that chart. Maybe the labels are so close they are considered on top of the graph.

**Comment by oysteinmoseng** [comment]
I was thinking one option could be to automatically darken/brighten the series color to the necessary levels. This way it would still give some visual hints through the color.

Another idea could be to include the marker in the label. That could get visually noisy, but it could be an option.
