### ISSUE TITLE
Highchart only shows the last point

### ISSUE THREAD

**Issue by rachidelaid** [highcharts/highcharts#18531]
#### Expected behaviour
I'm passing 765 points as two dimensional array. I want to show it as a line series.

#### Actual behaviour
instead it's only showing the last point.

#### Live demo with steps to reproduce

I have used the line series example but with my data: [codepen link
](https://codepen.io/e-rachid/pen/oNPbbWB)

#### Product version

because I used the example for the website I'm assuming it's the latest version of **Highstock**

#### Affected browser(s)
I have tried firefox and safari

**Comment by bm64** [comment]
Hello @rachidelaid 

It behaves like that because your data is not sorted (you can see an error [#15](https://assets.highcharts.com/errors/15/) in the console). Sort your data and the issue should be gone: https://jsfiddle.net/BlackLabel/g2xwzyj9/

**Comment by rachidelaid** [comment]
Thank you very much @bm64 it worked. I though it's already sorted.
