### ISSUE TITLE
Memoizing tooltip texts and positions crashes browser for large time ranges

### ISSUE THREAD

**Issue by alindeman** [highcharts/highcharts#1855]
Google Chrome 26, OS X 10.8
1. http://jsfiddle.net/b7b4X/1/
2. Grab (click+hold) the scroller and drag it around for a few seconds
3. Browser freezes/crashes

I'm not 100% sure, but I think the crash occurs in `setTooltipPoints` because it tries to create a huge array of points as the points are spread across a large time range. I've caught it there in the debugger a few times.

**Comment by TorsteinHonsi** [comment]
Closing this, no crashes are seen in recent versions.
