### ISSUE TITLE
Navigation page number is incorrect

### ISSUE THREAD

**Issue by alons1** [highcharts/highcharts#18574]
#### Expected behaviour
Shows 3 pages

#### Actual behaviour
Shows 2 pages
Issue does not happen with Highcharts 9

#### Live demo with steps to reproduce
https://jsfiddle.net/sectioni/xt3yz61f/20/ 

#### Product version
Highcharts 10.3.3

#### Affected browser(s)
Chrome, Firefox

**Comment by bm64** [comment]
Hello @alons1 and thanks for contacting us.

You need to slightly increase `legend.maxHeight` value and everything should work correctly: https://jsfiddle.net/BlackLabel/qo1c9hby/
