### ISSUE TITLE
Gantt Chart - Top row fixed and Dynamic Chart Height

### ISSUE THREAD

**Issue by BhavikTZ** [highcharts/highcharts#18573]
#### Expected behavior
I need scrollable chart with top header fixed and but our chart has dynamic data so we need dynamic height but if we use one of your solution our some entries are not showing. and i have range selector but it's not visible properly
https://jsfiddle.net/BlackLabel/a2dtfum8/

#### Actual behavior
Right now if i add scrollablePlotArea with minHeight our some entries are not showing, And if i add to big minHeight then some extra grid is showing, And with scrollable chart our range selector is not visible properly

#### Live demo with steps to reproduce
https://jsfiddle.net/mehulAhir/vqxrj6go/8/

**Comment by karolkolodziej** [comment]
Hi @BhavikTZ!

You can calculate that height and update it dynamically on the `load` event as you did.
Each how has the height of the `staticScale`, and the spacing and margin must be added at the top of the plot area- [demo](https://jsfiddle.net/BlackLabel/vmnpk19e/)

**Comment by karolkolodziej** [comment]
When it comes to the range selector that disappears, you can add its class name to the `fixedSelectors` array in the `moveFixedElements` method as I did in the [demo](https://jsfiddle.net/BlackLabel/1rvdb0ua/).

**Comment by BhavikTZ** [comment]
thanks. It worked
