### ISSUE TITLE
One data label not showing.

### ISSUE THREAD

**Issue by hbhatt18** [highcharts/highcharts#1859]
When I create a stack bar chart, and choose the stacked bars to be horizontally, along with the labels showing on the stacked bars, one data label is not being displayed. 

As shown in the snapshot, 
![highchartissue](https://f.cloud.github.com/assets/4491563/543472/f8b5f07e-c23b-11e2-806d-765fb3e76f6f.png)
The data label(value) is not shown on stacked bar .

If any other legend is hidden, then the data label on the stacked bar will be displayed correctly.The snapshot is given below.
![highchartissue2](https://f.cloud.github.com/assets/4491563/543488/5d12ca2e-c23c-11e2-8d9e-fefa8bda6d37.png)

After again making all the legends enable, the data label will still be displayed.Please refer to the snapshot below.
![highchartissue3](https://f.cloud.github.com/assets/4491563/543503/a86294be-c23c-11e2-8641-e992be01713c.png)
But after saving the chart, that particular data label is again not displayed on stacked bar

If the legend values are also displayed along with the legends, then the datalabel is displayed.Please refer to the attachment below.
![highchartissue4](https://f.cloud.github.com/assets/4491563/543549/ac603a98-c23d-11e2-98b3-1e1f916ac6fe.png)

**Comment by m1neral** [comment]
Same situation: http://forum.highcharts.com/highcharts-usage/barchart-datalabels-bug-t34015/

**Comment by highslide-software** [comment]
Thanks for your forum post and image. Could you post a live jsFiddle demo please? None of the fiddles above demonstrate the problem in the current version, as far as I can see.

**Comment by marbug** [comment]
Hello.
Here is a jsfiddle with missed labels for negative stack chart.
https://jsfiddle.net/marbug/Lvfmmz93/

**Comment by marbug** [comment]
P.P.S. If you resize jsfiddle windows horizontaly, then you'll see that 1.79 in the last but one line is not always hidden when it's needed (its part is shown outside line).

**Comment by TorsteinHonsi** [comment]
What chart width do you see that at? You need a [fixed chart width](https://jsfiddle.net/highcharts/Lvfmmz93/22/) to reliable replicate such things, since Highcharts adapts to the page size.

**Comment by marbug** [comment]
1) the issue with missed values in the last (i.e. 5th line) are present on screen size 1920px and less
2) on jsFiddle I see no issue with 1.79 at screen width 1920px (and width of right part is 834px or more). The issue with 1.79 appears if width of right part is resized to 686px.
2.1) Sorry for possible misunderstanding, but here http://www.highcharts.com/demo/bar-negative-stack there is no fixed width of container (i.e. it has "min-width: 310px; max-width: 800px;"). Should not highcharts handle page resize?

**Comment by marbug** [comment]
P.S. Please use "<div id="container" style="height: 400px; width: 686px"></div>" in [your jsFiddle](https://jsfiddle.net/highcharts/Lvfmmz93/22/) to see the issue

**Comment by marbug** [comment]
P.P.S. The issue is present even with width=600px, but values are too close to each other to show the issue clear.

**Comment by TorsteinHonsi** [comment]
> Should not highcharts handle page resize?

Yes it should, I'm just trying to reproduce the issue in a reliable way, which depends on the width of the chart.

> P.S. Please use <div id="container" style="height: 400px; width: 686px"></div> in your jsFiddle to see the issue with 1.79

[Updated fiddle](https://jsfiddle.net/highcharts/Lvfmmz93/24/). (You can save your own too). I still see the 1.79 data label. What browser are you using? Browser and system font handling may influence the text boxes too.
![skjermbilde 2016-11-09 kl 10 35 59](https://cloud.githubusercontent.com/assets/227836/20133568/54514ce4-a668-11e6-805d-4487bdfb9ea4.png)

**Comment by marbug** [comment]
1) I am using latest Chrome (windows/linux), latest FF (windows/linux), IE11
2) the issue with 1.79 differs from $subj: `1` is outside blue line, `.79` is inside blue line
3) 6.701 in the 5th line is not shown in latest Chrome (windows/linux), latest Firefox (windows/linux) and IE11

**Comment by marbug** [comment]
Sorry, guys. Are my words so unclear or is current issue priority too low? :)

**Comment by TorsteinHonsi** [comment]
Sorry for the late reply!

> the issue with 1.79 differs from $subj: 1 is outside blue line, .79 is inside blue line (i.e. 1.79 must be hidden - it should not be shown outside blue line)

Currently there is no rule saying that data labels should be hidden if they overflow the column they're in. They are only hidden if they collide with other labels. See for example http://jsfiddle.net/highcharts/5nzvjp6y/.

> 6.701 and 11.2 in the 5th line are not shown. But there is enough space to show 6.701 and 11.2 in the 5th line - they should be visible

In my screenshot above, 6.701 actually shows. The 11.2 label also shows in https://jsfiddle.net/highcharts/Lvfmmz93/24/, but it is black so it is hard to see it. With a white label it works better: https://jsfiddle.net/highcharts/Lvfmmz93/28/

**Comment by marbug** [comment]
Sorry, but labels are absent in Chrome, FireFox, IE11. Please take a look to ensure:
[Chrome](https://s6.postimg.org/xpu19y1xp/chrome24.png)
[Chrome](https://s6.postimg.org/thz9170i5/chrome28.png)
[FireFox](https://s6.postimg.org/cvhos47kd/ff24.png)
[FireFox](https://s6.postimg.org/4r9kndl59/ff28.png)
[IE11](https://s6.postimg.org/epuj9uukt/ie24.png)
[IE11](https://s6.postimg.org/4r9kndl59/ff28.png)
What browser are you using?

**Comment by marbug** [comment]
Sorry for no screenshots in my previous comments. Please take look at them in the last one above.

**Comment by TorsteinHonsi** [comment]
Hi, I can see it now. The issue is that the system's text bounding boxes are reported higher on Windows than on the Mac, so the layout gets a bit different. 

In your sample you set the `dataLabels.padding` to 10.6, and this makes the bounding box go outside the confined space. If you set it to a lower value the labels show: http://jsfiddle.net/Lvfmmz93/30/.

**Comment by KacperMadej** [comment]
It looks like for Windows the labels are overlapping because of different font sizes across different OS. You can avoid the problem by using a font type that is of the same size in all OS or by adjusting the padding option. This doesn't look like a bug. Please provide more info if you would like to get the issue opened.

**Comment by Rathavi** [comment]
Hi, I have the same issue, please refer https://jsfiddle.net/1s9oqdnj/. Try the step metioned in https://github.com/highcharts/highcharts/issues/1859#issue-14580811. It's look like data label is not visible in small area at load time. Can we please reopen this issue and have some solutions

**Comment by KacperMadej** [comment]
@Rathavi 
Is your chart loaded differently depending on the used browser?
Which browser (and version of it) have you used?
Which OS (and version of it) have you used?
Please add an image or precise description of what is expected and what is problematic in the chart.
