### ISSUE TITLE
Touch scroll doesn't load data points while swiped

### ISSUE THREAD

**Issue by gruuschesdevelopmenthq** [highcharts/highcharts#18602]
#### Expected behaviour
Swipe the chart left or right on a mobile device (or in developer tools in browser) and the new data points are loaded while it's swiped (finger pressed). Basically the same beahaviour as when it's panned with the mouse on a non touch device.

#### Actual behaviour
While it's swiped the new data points aren't shown. Only when the finger is not longer pressed on the screen the new data points are shown.

#### Live demo with steps to reproduce
https://jsfiddle.net/8spwnfu7/1/
Either open it with a touch device or activate developer options in your browser and simulate a touch device. In Firefox it's called "Responsive Design Mode" and then on the top in the middle you can enable or disable touch simulation.
Reload the page if touch is not working. Then scroll the data points left and right and see the new data points aren't shown while the finger / mouse is pressed.

If it's not clear what I mean just leave the touch mode and pan the chart with the mouse left and right and you'll see the new data points are shown fluently.

#### Product version
├── highcharts-react-official@3.1.0
├── highcharts@10.3.3

#### Affected browser(s)
Firefox
Chromium
Chrome
Waterfox
Duckduckgo

**Comment by bm64** [comment]
Hello @gruuschesdevelopmenthq 

Mobile zooming and panning was implemented a while ago now, back when mobile devices weren't that fast, focusing on good performance, at a cost of smooth animations etc. that could cause performance issues. Unfortunately we can't really do anything about that at this moment.

**Comment by gruuschesdevelopmenthq** [comment]
Hi @bm64 , ok I understand. Can I make a feature request out of it? Would make the UX much better since the majority of internet users are on mobile. Maybe even as an option to enable it or not.

**Comment by bm64** [comment]
@gruuschesdevelopmenthq we have ticket like that already here: https://github.com/highcharts/highcharts/issues/5270
Please leave your feedback there. In general we're aware that mobile zooming / panning is not the best experience at this moment and there is definitely a room for an improvement. Feel free to leave your feedback in the mentioned ticket, you can also take a look at few suggested workarounds, and I will discuss the topic again with the team.
