### ISSUE TITLE
YAxis updates break chart after v10.2.1

### ISSUE THREAD

**Issue by skrtheboss** [highcharts/highcharts#18619]
#### Expected behaviour
Updating yAxis config should not result in errors being logged and chart not rendering correctly. 

#### Actual behaviour
When updating yAxis an error is logged and chart breaks sometimes.

#### Live demo with steps to reproduce
Open the demo https://jsfiddle.net/xhygej1v/2/ and look at the errors being logged in the console.

Demo with 10.2.1 https://jsfiddle.net/xhygej1v/3/

After some debugging i think the problem has been caused by the changes made in [this](https://github.com/highcharts/highcharts/commit/225ec4f469258d270671fd81c41c85bb41589e7a) commit.
The logic in the ts/Core/Renderer/SVG/SVGElement.ts updateTransform has been changed from:
```javascript
    public updateTransform(): void {
        const wrapper = this,
            scaleX = wrapper.scaleX,
            scaleY = wrapper.scaleY,
            inverted = wrapper.inverted,
            rotation = wrapper.rotation,
            matrix = wrapper.matrix,
            element = wrapper.element;

        let translateX = wrapper.translateX || 0,
            translateY = wrapper.translateY || 0;

        // Flipping affects translate as adjustment for flipping around the
        // group's axis
        if (inverted) {
            translateX += wrapper.width;
            translateY += wrapper.height;
        }
```
to:
```javascript
    public updateTransform(): void {
        const {
            element,
            matrix,
            rotation = 0,
            scaleX,
            scaleY,
            translateX = 0,
            translateY = 0
        } = this;
```
This actually looks fine, except, that translateY can be NaN. Which can occur if the [animate](https://github.com/highcharts/highcharts/blob/44e193353ba0fa46891220b9d996b24b578caf79/ts/Series/Column/ColumnSeries.ts#L189) function of the ColumnSeries computes the value of the [yAxis.pos](https://github.com/highcharts/highcharts/blob/44e193353ba0fa46891220b9d996b24b578caf79/ts/Core/Axis/Axis.ts#L270) is still undefined.

May be related to #18252

#### Product version

Highcharts v10.3.3

#### Affected browser(s)
*

**Comment by pawellysy** [comment]
@skrtheboss, thank you for your input, and thorough debugging!
We will investigate if the issue is connected to this change (It probably is).

**Comment by pawellysy** [comment]
`Internal note`
Check why the `NaN` value is passed in the first place. If not possible to determine, restore the previous solution.
