### ISSUE TITLE
range selector with data grouping breaks chart when volume based indicator is used

### ISSUE THREAD

**Issue by tw2as** [highcharts/highcharts#18643]
#### Expected behaviour
On Highstocks chart user should be able to use range selector buttons with dataGrouping on a chart which includes volume and volume based indicators (e.g. OBV).

#### Actual behaviour
Volume columns and indicator disappear after clicking on range selector button. 
In console the following error is visible: _Uncaught Error: Series aapl-volume not found! Check `volumeSeriesID`._

I guess this unresolved error: https://github.com/highcharts/highcharts/issues/18409 could be caused by the same problem.

#### Live demo with steps to reproduce
https://jsfiddle.net/72dghy9z/2/

Steps to reproduce:
1. Open the demo and add OBV indicator
1. Click on any range selector button

#### Product version
Highstock - latest version (v10.3.3 at the time of reporting).
The problem seems to exist in v9.2.1 but v8.2.2 seems to work fine.

#### Affected browser(s)
Chrome, Firefox

**Comment by karolkolodziej** [comment]
@tw2as Thank you for reporting the issue!

_Workaround:_
You can reverse the order of the series you have declared- [demo](https://jsfiddle.net/BlackLabel/kpzsqobd/).
