### ISSUE TITLE
Negative radius for circle and diamond shapes in TileMap

### ISSUE THREAD

**Issue by hemanthreddyk** [highcharts/highcharts#18647]
#### Expected behaviour
When there is a single data point in the series, circle and diamond shape tiles should render on the chart with out error

#### Actual behaviour
Does not render the shape in the chart, with following error in browser console
Error: <circle> attribute r: A negative value is not valid. ("-2")

#### Live demo with steps to reproduce
https://jsfiddle.net/nwtquxfm/2/

1. Open the above link
2. Right click and go to browser console.
3. You can see the above mentioned error
4. Same error happens when tileShape is changed to diamond

#### Product version
Latest Stable

#### Affected browser(s)
All browsers

<img width="1434" alt="Screen Shot 2023-03-10 at 2 54 47 PM" src="https://user-images.githubusercontent.com/10864873/224277407-2fa0d9f5-b0f4-47f7-a755-86ad791edc69.png">

**Comment by pawellysy** [comment]
Thanks for reporting a bug @hemanthreddyk!

`Internal note`
The `colsizePx` is wrongly calculated here: https://github.com/highcharts/highcharts/blob/c0093474d740f205592e39e4c154f7f125182c69/ts/Series/Tilemap/TilemapShapes.ts#L530-L543
