### ISSUE TITLE
Annotation does not apply label height and width configuration, how to apply shape broderRadius configuration 

### ISSUE THREAD

**Issue by LearnGrowAndShare** [highcharts/highcharts#18655]
#### Expected behaviour
Both annotation should have same dimension 

#### Actual behaviour
![image](https://user-images.githubusercontent.com/12616063/224520729-bcf3a3eb-938f-431a-b191-f6efabb3bade.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/ankitkumar148/e8xrvc65/11/

**Configuration** - 
 ```
 annotations: [{
        shapes: [ {
            point: '3',
            type: 'rect',
            width: 20,
            height: 20,
            x: -10,
            y: -25
        }],
        labels: [ {
            point: '4',
              borderRadius: 2,
            borderWidth: 2,
            borderColor: 'red',
            style: {
                fontSize: '12px', 
                width: 20,
                height: 20
            },
           shape: 'rect',
           text: ' '
        }]
    }]
```

In above configuraiton,
for point 3 - Is there any configuration to add border radius to shape, just like we have for point 4 with label annotation ?
for point 4 - Is there any configuration to add width and height to label, just like we have for point 3 with shape annotation ?

#### Product version
 Highcharts JS v10.3.3 (2023-01-20)

#### Affected browser(s)
All,

**Comment by karolkolodziej** [comment]
Hi @LearnGrowAndShare!

1. Annotation for point 3 is created as an SVG rect element, thus if you have a reference to that element you can apply the `r` attribute to round the corner - [demo](https://jsfiddle.net/BlackLabel/1som9Lnh/).
2. Annotation for point 4 works similarly -[demo](https://jsfiddle.net/BlackLabel/1som9Lnh/).


For future reference, please use[ available support channels](https://www.highcharts.com/blog/support/) for questions like this. We mostly use GH for tracing the bugs and features.
