### ISSUE TITLE
[Question] destroy() takes much longer time with React 18 than React 17

### ISSUE THREAD

**Issue by HbZh** [highcharts/highcharts#18656]
#### Expected behaviour
When there are 10 highcharts (bar) loading at the same time in the page,  the series length is 10, each series contains around 12 points, the page will freeze for about 3-5 seconds when unmount those charts and show the next page state, with React 18. It only takes 1-2 seconds with React 17. 

I tried to debug with highcharts source code, seems like chart.destroy(). series.destroy() and point.destroy() takes more time than a low react version. Based on my local test, point.destroy() takes around 5~7ms with React 18 and <1ms with React 17. 

Could you provide any insights about this issue root cause? Is there any walkround to speed up the destroy phase?

#### Product version
highcharts: 10.3.3
highcharts-react-official: 3.2.0

Thanks!

**Comment by ppotaczek** [comment]
Hi @HbZh, 

Thank you for contacting us!
I've tried to reproduce the problem, but I don't see any differences between React 17 nad 18. In the both versions, unmounting 10 charts with 10 series takes about 85ms. Maybe there is some other factor in your code that reduces on performance?

React 17: https://codesandbox.io/s/highcharts-react-demo-3khpr3
React 18: https://codesandbox.io/s/highcharts-react-dem-78shyg

However, could you try to adapt the examples to show the issue?

Best regards!

**Comment by HbZh** [comment]
Hi @ppotaczek, thank you for your live demo and sorry for a late reply. My app page is a quite complicated and yes, other factors have an impact on the performance. 
Now the issue is found when chrome devConsole is open. If I closed the devConsole, the unmount looks fine. 

Anyway, thanks for your support.
