### ISSUE TITLE
Flags are displaying top on each other if we click button continuously

### ISSUE THREAD

**Issue by charan-web** [highcharts/highcharts#18669]
#### Expected behaviour
While we click on the "Dividends" button below the chart.It should display the dividends flags. while the "Dividends" button is active click on the "Sensitive Assessment" button that data flags also should appear without any disturbances or animating or does not create a more data.

It should display the data which is coming from server.

#### Actual behaviour
If we are clicking continuously on the "Sensitive Assessment" button while the "Dividends" button active , the dividends flags are appearing one top of other, its creating its own data on certain points and appearing on top of each other.

If we check the dividends flags data , the data looks properly fine

#### Live demo with steps to reproduce

https://codesandbox.io/s/elastic-sea-kksvfd?file=/src/data.js
This gif might help you reproduce:https://github.com/charan-web/Highcharts_gif/blob/main/ezgif.com-video-to-gif.gif
1) Click on the "Dividends" button and see the flags data on the chart
2) While the "Dividends" button is still active , click on the "Sensitive Assessment" button. And Observe the flags on the chart.
3) Click Continously on the "Sensitive Assessment" button while the "Dividends" is still active.And observe the dividend flags on the chart 
#### Product version

Highcharts,HighStock
     "highcharts": "^10.3.3",
    "highcharts-react-official": "^3.1.0",

#### Affected browser(s)
chrome

**Comment by bm64** [comment]
Hello @charan-web 

As you can read in our docs, chart options should be kept in the state: https://github.com/highcharts/highcharts-react#optimal-way-to-update

It is especially important when you want to update the chart or series data, otherwise you can expect similar issues.
Working demo: https://github.com/highcharts/highcharts-react#optimal-way-to-update
