### ISSUE TITLE
HighCharts.NET wrapper enum YAxisTitleAlign wrong values

### ISSUE THREAD

**Issue by clebris** [highcharts/highcharts#18684]
YAxis title alignment is not possible due to wrong values at the enum YAxisTitleAlign;

#### Expected values

```
namespace Highsoft.Web.Mvc.Stocks { 
    public enum YAxisTitleAlign { 
        Middle,
        High,
        Low
    }
}
```

#### Actual values
```
namespace Highsoft.Web.Mvc.Stocks { 
    public enum YAxisTitleAlign { 
        Middle,
        Left,
        Center,
        Right 
    }
}
```

**API Reference:**
https://api.highcharts.com/highstock/yAxis.title.align
https://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_y_axis_title.html#a91698bfb728db7f561cd8c38332f9d83

The issue occurs in XAxis as well.

**Comment by magdalena-gut** [comment]
Hi @clebris, thanks for reporting!

FYI @brofixo

**Comment by magdalena-gut** [comment]
Hi @brofixo, is there any workaround, or do we have an ETA for fixing this issue? Thanks!

**Comment by brofixo** [comment]
@clebris as the workaround you can use `YAxisTitle.CustomFields.Add("align","high") `
