### ISSUE TITLE
Prop to display the  Tool tips above the chart area(after the max value of Y axis) 

### ISSUE THREAD

**Issue by renu2121equinix** [highcharts/highcharts#18694]
Hello Team,

Currently we have a situation where we need to show show both line chart and volume chart one below the other , in this scenario the
tooltip of the chart always covers the volume chart when we hover it. Request is to get a prop were we can show the tool tip above the chart area. 

Library related to the feature
Highcharts / Highcharts Stock /

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by bm64** [comment]
Hello @renu2121equinix 

This behaviour can be achieved by using `positioner` callback: https://api.highcharts.com/highstock/tooltip.positioner
Demo: https://jsfiddle.net/BlackLabel/nfg0od3y/
