### ISSUE TITLE
Tooltip `stickOnContact: true` throws error on hover from `followPointer: false` to `true`

### ISSUE THREAD

**Issue by eriksoeb** [highcharts/highcharts#18693]
#### Works almost, for the first few seconds, but fails when doing mouseover / and inspecting tooltips
txt file uploaded must be renamed to html, then open by Chrome

#### Live demo with steps to reproduce

https://jsfiddle.net/eriksoeberg/z4fr87p5/1/
and 
similar: https://jsfiddle.net/BlackLabel/wxgyuk35/

#### Product version

latest Highmaps

#### Affected browser(s)  Chrome and edge
[map.txt](https://github.com/highcharts/highcharts/files/11009023/map.txt)

**Comment by bm64** [comment]
Hello @eriksoeb and thanks for reporting the issue.

It looks like the issue is caused by `stickOnContact: true`. As a workaround you can remove that option or set it to false (default): https://jsfiddle.net/BlackLabel/0xqkrwp2/

**Comment by eriksoeb** [comment]
helo @bm64 
https://jsfiddle.net/eriksoeberg/z4fr87p5/4/
it just takes a bit longer to reproduce the error, bit mouse over and tooltip, and especially out in the margins, then the error gets back.
btw there is also a  support ticket 21408 on this one.

**Comment by eriksoeb** [comment]
By setting **_stickOnContakt:fals, in your minimal demo,  I basically get the same information, but fewer error mesages. I am currently not sure if stickOnContact have any impact/function..

https://jsfiddle.net/o4t9skw2/

**Comment by eriksoeb** [comment]
Thanks a lot ! Great!I will look into this on monday !Erik12. apr. 2023 kl. 09:43 skrev Hubert Kozik ***@***.***>:﻿
I have prepared a workaround for that issue by overwriting one of the tooltip methods. It is inside the IIFE function. If you want to use it, just copy-paste it into your project and everything should work as intended. A similar solution will be used in HC Core.
Live demo HC Core: https://jsfiddle.net/BlackLabel/9ubg57sq/
Live demo HC Maps: https://jsfiddle.net/BlackLabel/g1atwu9o/
