### ISSUE TITLE
cannot read property' base val 'of undefined

### ISSUE THREAD

**Issue by kakadebaba** [highcharts/highcharts#18709]
Hello, I want to ask you. I used the static import method of System requirements, but an error occurred during the chart method: 'cannot read property' base val 'of undefined'. I think it may be a problem with svg because I have a title. This is really bothering me

**Comment by bm64** [comment]
Hello @kakadebaba and thanks for contacting us.

We use this channel only for bug reports and feature requests. Please visit our other support channels where our team will help you with finding out what is not working: https://www.highcharts.com/blog/support/
