### ISSUE TITLE
Incorrect value of stackY

### ISSUE THREAD

**Issue by NastyaBanko** [highcharts/highcharts#18720]
#### Expected behaviour
As I understood stackTotal is a total value of the stack, stackY is a total value from the bottom point to the specific point of the stack. So I expect that if I have stack with values (10.5, 20, 15) I will get stackTotal = 45.5 and stackY for "20" value = 10.5 + 20 = 30.5. For "15" value I should get stackY = 10.5 + 20 + 15 = 45.5

#### Actual behaviour
So sometimes for some reason I get incorrect value of stackY. It has redundant numbers

#### Live demo with steps to reproduce
I output stackTotal & stackY of the last point of the first series in console. I expect to get stackTotal = 691.6 and stackY = 691.6. But stackY = 691.5999999999999.
You could see that I'm using data values with only one digit after the decimal point, so value 691.5999999999999 is impossible.

```
Highcharts.chart('container', {
    chart: {
        type: 'column',
        events: {
            load: function() {
                console.log(this.series[0].points[2].stackTotal, "stackTotal");
                console.log(this.series[0].points[2].stackY, "stackY");
            },
        },
    },
    xAxis: {
        categories: ['Arsenal', 'Chelsea', 'Liverpool']
    },
    plotOptions: {
        column: {
            stacking: 'normal',
        }
    },
    series: [
    {
        name: "Year 1990",
        data: [63.1, 72.7, 320.2],
    },
    {
        name: "Year 2000",
        data: [81.4, 84.1, 371.4],
    },
]
});
```

template: https://jsfiddle.net/fuL6gaxh/8/

![83](https://user-images.githubusercontent.com/49037181/227155928-8b54dd3b-6089-4233-b5d9-e33cc1435248.PNG)

#### Product version

"highcharts": "9.3.3",
"highcharts-angular": "3.0.0",

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Hi @NastyaBanko!
Thank you for reporting the issue! 

Internal note: 
Add `correctFloat` to the line:
https://github.com/highcharts/highcharts/blob/2b869aed491b6559cbe576bad38b6f91c4c04e5d/ts/Core/Axis/Stacking/StackingAxis.ts#L494-L495

It would be nice to also check other scenarios and add `correctFloat` if needed.

**Comment by NastyaBanko** [comment]
Thanks for your reply! 

Also I've found that total value of pie chart has the same bug.

```
Highcharts.chart('container', {
    chart: {
        type: 'pie',
                events: {
            load: function() {
                console.log(this.series[0].total, "total");
            },
        },
    },
    series: [{data: [{y: 70.67}, {y: 14.77},  {y: 4.86}, {y: 2.63}]}]
});
```
template: https://jsfiddle.net/c5p3ogf4/20/

![84](https://user-images.githubusercontent.com/49037181/227463463-2a07dcbe-52d4-48eb-8042-f70dada89588.PNG)

**Comment by karolkolodziej** [comment]
Internal note:
Make sure that the case (☝️) is also covered in code nad tests.

**Comment by NastyaBanko** [comment]
Hi! Where I could test your fix? If I set data from my example to demo in highcharts https://www.highcharts.com/demo/column-stacked I still have the same problem https://jsfiddle.net/9d6eoxq0/1/
From what version your fix is available?

**Comment by pawellysy** [comment]
Hello @NastyaBanko, the fix is added to the master branch, which is not a part of the official release yet. 
You can test the newest version by using the code from `https://github.highcharts.com/...` where the code from master branch is deployed. 

It will be part of the next official release though, which should happen in a few weeks.

Here is your demo, with the code from master branch: https://jsfiddle.net/BlackLabel/0tehckup/2/
