### ISSUE TITLE
CSS properties override config properties

### ISSUE THREAD

**Issue by alrahemtulla** [highcharts/highcharts#18726]
#### Expected behaviour
Config properties should override CSS properties

#### Actual behaviour
Notice that when providing a `medianWidth` and `lineWidth` of 0 and a CSS property for medians of 1px, we get the median line to be 1px. If you change the highcharts version back to v10.3.1, the median line is gone as the config's properties take precedence. Going to highcharts v10.3.2/v10.3.3 is where the CSS properties draw back the median line. 

#### Live demo with steps to reproduce
https://jsfiddle.net/na16hv3c/1/

#### Product version
Highcharts v10.3.3

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
@karolkolodziej I agree it works correctly. This is how SVG works - CSS takes precedence over attributes. Besides, if we were to consistently work around this, it would be a major task, see for example `series.lineWidth` : https://jsfiddle.net/highcharts/kwarghbj/
