### ISSUE TITLE
Highstock too slow

### ISSUE THREAD

**Issue by Ninita1** [highcharts/highcharts#18729]
#### Expected behaviour
Rendering should be immediate and the response to interaction with the charts should also be fast.

#### Actual behaviour
I need to have 5 `highstock` charts with **hundreds of series** and each series has **thousands of data**.
In these charts I also have configured some events/actions, such as: `xAxis.tickPositioner`, `xAxis.events.afterSetExtremes`, `xAxis.labels.formatter`, etc.
However, rendering is very slow, interacting with the graphics is also very slow, and my entire application became also very slow with these charts.
I already tried using **boost mode** but the problem remains.
Is it normal for the charts to look like this (doesn't seem very normal to me)? Is there any way to improve this behavior?
I'm not sure but I have the impression that `momentJs `is also influencing the charts performance... or the series.marker.enable...

#### Live demo with steps to reproduce
https://jsfiddle.net/8rzedguo/3/

#### Product version
"highcharts": "10.3.2", `//and we are importing Highstock from 'highcharts/highstock.src'`
"moment": "2.29.4",
"moment-timezone": "0.5.38"

**Comment by karolkolodziej** [comment]
Hi @Ninita1!

There is a bunch of things that can be done to improve the overall performance but our GH is not a place for that.
We usually treat it as a tracker for bugs/features and this one is neither of them.

Please contact our support team through [available support changels](https://www.highcharts.com/blog/support/) and explain your concerns. I'm sure they will find a suitable solution for your case.
