### ISSUE TITLE
timezone  Europe/Paris daylight saving time 2023

### ISSUE THREAD

**Issue by abe2064** [highcharts/highcharts#18732]
#### Expected behaviour
1679846424 should be :
dimanche 26 mars 2023 18:00:24

#### Actual behaviour
dimanche 26 mars 2023 17:00:24

#### Product version
Highcharts 10.3.3

#### Affected browser(s)
firefox and probably every browser

**Comment by bm64** [comment]
Hello @abe2064

I'm in the same timezone and I've tried to recreate the issue but it seems that chart shows correct date (26.03.2023 18:00.24): https://jsfiddle.net/BlackLabel/uzj0g21v/
Could you try it again and see if it works for you?

**Comment by abe2064** [comment]
hello, @bm64 

you did not set timezone: 'Europe/Paris' in your chart.


https://jsfiddle.net/o64kzd3L/
