### ISSUE TITLE
Highstock's "Measure" annotation's labels will be missing if a newly created "Measure" annotation's labels overlaps

### ISSUE THREAD

**Issue by jackytanjq** [highcharts/highcharts#18733]
#### Expected behaviour
The newly created "Measure" annotation's labels should show if it happens to overlap with another "Measure" annotation's already existing labels.

Affected annotations:
- Measure XY
- Measure X
- Measure Y (Has no labels at all?)

#### Actual behaviour
When creating a new "Measure" annotation where the labels will overlap with another existing "Measure" annotation's label, the labels will go missing.

#### Live demo with steps to reproduce

Steps:
1. Create a new _(first)_ "Measure" annotation.
2. Create a new _(second)_ "Measure" annotation in such a way that the labels will overlap with the first "Measure" annotation.
Note: Notice that the labels will appear initially, and when the user changes the size of this annotation, the labels will disappear.

Example:
![MeasureXY_MissingLabels_OnOverlap](https://user-images.githubusercontent.com/7489622/227817763-7b667e53-21d9-42aa-ad65-9be7f2513b4c.gif)

#### Product version

Highstock JS v10.3.3 (2023-01-20)

#### Affected browser(s)
Tested on: 
- Firefox 111.0.1 
- Google Chrome 111.0.5563.111
- Microsoft Edge 110.0.1587.57

**Comment by bm64** [comment]
Hello @jackytanjq

You can show labels for overlapping Measure annotations by settings `labelOptions.allowOverlap: true`: https://jsfiddle.net/BlackLabel/jx3uk8wr/
API reference: https://api.highcharts.com/highstock/annotations.labelOptions.allowOverlap
