### ISSUE TITLE
Problems with `areaspline` series that is covered by another series

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#18744]
#### Expected behaviour
1. The `series.point.events.click` event does not trigger when the `areaspline` series is covered by another `areaspline` series.
2. When `stickyTracking = false` then the `tooltip` never shows up after hovering over a covered series. 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/h3a7pbcr/

1. Try clicking on the point on a blue series 
2. Turn off `stickyTracking` and hover over a point on a blue series 

#### Product version
Highcharts 10.3.3

**Comment by karolkolodziej** [comment]
@eyalellenbogen 
As a workaround for now you can set the class name for both series as `className: 'highcharts-tracker'` - [demo](https://jsfiddle.net/BlackLabel/npe0rct8/).

We will discuss this issue internally and will keep you posted about the potential ETA.

**Comment by TorsteinHonsi** [comment]
Another workaround is to set `trackByArea` to true. https://jsfiddle.net/highcharts/zno0d5x8/ 

I am not sure if this is a bug though. Series 1 is actually behind the area of Series 2, so it is not obvious that it should respond to clicks. But if it should, we should probably set `pointer-events: none` to the area shape.

**Comment by hubertkozik** [comment]
I've come to the same conclusion. We've got an option, which simply enables the mouse events for covered series. What do you think about adding some extra information in docs: https://api.highcharts.com/highcharts/series.area.trackByArea to fulfil this issue?

**Comment by TorsteinHonsi** [comment]
@hubertkozik I agree with that 👍

**Comment by hubertkozik** [comment]
After some research in Pull Request, this is a bug, that will be fixed.
