### ISSUE TITLE
Multiple series data updates, without redraw cause charts to break 

### ISSUE THREAD

**Issue by skrtheboss** [highcharts/highcharts#18750]
#### Expected behaviour
Updating series data multiple times without redrawing the chart, should not result in a broken chart.

#### Actual behaviour
When series data is updated without redrawing the chart in between each update call, then the chars breaks. 

#### Live demo with steps to reproduce
Last working version I found is 6.0.7:
https://jsfiddle.net/4ryjb5Lq/1/

Stopped working in 6.1.4, could not test ( 6.1.0 - 6.1.3 ):
https://jsfiddle.net/4ryjb5Lq/2/

And is still broken in 10.3.3: 
https://jsfiddle.net/4ryjb5Lq/3/

Probably related to #17989

#### Product version

Broken since 6.1.4 and still is in 10.3.3

#### Affected browser(s)
All

**Comment by bm64** [comment]
Hello @skrtheboss and thanks for reporting the issue.

Workaround from the related ticket, which is adding id property to each series, seems to also work in this case: https://jsfiddle.net/BlackLabel/z7oh2cdt/
