### ISSUE TITLE
Boost mode with properties causes loss of focus with navigator slider

### ISSUE THREAD

**Issue by alrahemtulla** [highcharts/highcharts#18754]
#### Expected behaviour
The navigation slider should not causes any errors

#### Actual behaviour
Turning on boost mode, and setting these properties
`plotOptions.area.stacking: "normal"`,
`plotOptions.series.dataGrouping.enabled: false`,
`navigator.series.stacking: "normal"`
should not cause any issues with the navigation slider

#### Live demo with steps to reproduce
https://jsfiddle.net/mf06ctkv/1/

1) Slide the navigator to show about half of the points
2) Hover over the graph to show some tooltips
3) Slide the navigator back to show the entirety of the points
4) Hover over the graph to show some tooltips
5) Slide the navigator to show about half of the points
-- The navigator no longer leaves the mouse and you will not be able to get any more tooltips
--> Notice this does not happen if you remove one of the properties that are set or turn off boost mode.

Here is the error that gets logged in the console:
![image](https://user-images.githubusercontent.com/116202323/228348797-dce2416a-717f-41fa-9be8-6514511da1d1.png)

#### Product version
Highstock v10.3.3

#### Affected browser(s)
Chrome

**Comment by bm64** [comment]
Thanks @alrahemtulla for reporting the issue.
