### ISSUE TITLE
Boost mode with properties causes no tooltips outside range and incorrect tooltips inside range

### ISSUE THREAD

**Issue by alrahemtulla** [highcharts/highcharts#18756]
#### Expected behaviour
Tooltips should show up and be correct

#### Actual behaviour
Turning on boost mode, and setting these properties
`plotOptions.area.stacking: "normal"`,
`plotOptions.series.dataGrouping.enabled: false`,
and setting min and max for xAxis
causes tooltips outside the range to not display and tooltips inside range to be at an offset

#### Live demo with steps to reproduce
https://jsfiddle.net/1hdn6jxo/

1) Slide the navigator all the way to the right (do not adjust the size of the navigator)
2) Hover over the right side of the graph (past the max range initially set for the xAxis (in this case it is 8000))

Notice that the tooltips do not show up and that an error is logged: 
![image](https://user-images.githubusercontent.com/116202323/228352322-c986eabe-db23-4f04-8178-3ebc49addb94.png)

Now the tooltips below the initially set range (in this case it is 8000) are incorrect as they are displaying an offset of where the navigator is scrolled to:
![image](https://user-images.githubusercontent.com/116202323/228352620-17cd6816-9e13-4ab7-8c34-4957c0e55071.png)

#### Product version
Highstock v10.3.3

#### Affected browser(s)
Chrome

**Comment by bm64** [comment]
Hello @alrahemtulla and thanks for reporting the issue.

**Comment by TorsteinHonsi** [comment]
#### Workaround
Set the `cropThreshold` to Infinity: series.getValidPoints
