### ISSUE TITLE
Legend is missing the last page when legend.maxHeight is smaller than 43

### ISSUE THREAD

**Issue by hakansemerci** [highcharts/highcharts#18768]
#### Expected behaviour

Legend has the 3rd page containing series 9 for small legend.maxHeight. (in the attached JSFiddle case)

#### Actual behaviour

Legend does not have the 3rd page when legend.maxHeight is less than 43.

#### Live demo with steps to reproduce
https://jsfiddle.net/386czx9f/1/

#### Product version

Highcharts v10.3.3 (to at least v8.1.1)

#### Affected browser(s)
Chrome, Safari, Firefox, Edge

**Comment by karolkolodziej** [comment]
Hi @hakansemerci! 
Thank you for reporting the issue.

_Internal note:_
Review this part of the code: https://github.com/highcharts/highcharts/blob/1c41920da5e48a7e233fc51ee803794041cd8e7e/ts/Core/Legend/Legend.ts#L1359

_Workaround:_
This case seems like an edge case, so I recommend using some other value for now.
