### ISSUE TITLE
Responsive: color axis legend symbolHeight default value

### ISSUE THREAD

**Issue by lbohac-vendavo** [highcharts/highcharts#18769]
#### Expected behaviour
When making window size smaller, multiple responsive conditions are met and it's settings are applied accordingly. When making window size larger no responsive condition is met and symbolHeight is set to its default value,

#### Actual behaviour
When I use responsive atribute to set symbolHeight according to chart height it works well, the issue occurs when no responsive condition is met and default value should be used. Instead some value of responsive setiings is used. 

#### Live demo with steps to reproduce

1. Legend height is by default 200px
2. Make window smaller in order to make chart smaller > Make it smaller until tittle says "Chart height < 200". Legend height is 80px 
3. Make window larger until title says "No responsive settings"
4. Check legend size, it remained 80px height.
[https://jsfiddle.net/7oLbw0az/5/](https://jsfiddle.net/7oLbw0az/5/)

#### Product version
Highmaps  9.2.2

#### Affected browser(s)
Chrome, Firefox

**Comment by KacperMadej** [comment]
Hi @lbohac-vendavo ,
thank you for reporting the problem.

As a workaround you could set an additional responsive rule with a copy of the default/main options.
Demo: https://jsfiddle.net/BlackLabel/b75k4hoL/1/

_Internal note:_
Explicit setting of the default `symbolHeight: 200` in the main legend options set doesn't help.
Demo: https://jsfiddle.net/BlackLabel/b75k4hoL/

This is a general coloraxis issue - not limited to Maps.
Minimal and automated demo: https://jsfiddle.net/BlackLabel/kzh1bnc6/3/

Going through the first condition of the responsive rules is required as only jumping between 200 and initial works fine.
Demo: https://jsfiddle.net/BlackLabel/kzh1bnc6/1/
