### ISSUE TITLE
Shared tooltip with two different x axis scales results in a flickering tooltip between the two

### ISSUE THREAD

**Issue by nickma42** [highcharts/highcharts#1877]
http://jsfiddle.net/VnXTX/

In this example I've got two x axes and two y axes split into two separate graphs, both x axes have a different scale so the top and bottom x axes don't match up.

With a shared tooltip this makes the tooltip flicker back and forth between the two axes regardless of which axis your mouse is actually hovering over.

I think correct behavior may be to have two different active areas for tooltips so hovering over one axis won't interact with the other.

**Comment by ajaytripathi10** [comment]
you may go through this fiddle [https://jsfiddle.net/ajaytripathi10/z8mrwhxz/](https://jsfiddle.net/ajaytripathi10/z8mrwhxz/) where you can use shared tooltip with multiple X and Y axis
