### ISSUE TITLE
API link to `series.cluster.drillToCluster` doesn't work

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#18785]
#### Actual behaviour
There's a link to `cluster.drillToCluster` from: https://api.highcharts.com/highmaps/series.mappoint.cluster.events.drillToCluster 
which does not work.

**Comment by Cedar-81** [comment]
Hi, I've been able to replicate this bug. How can I access the required link that is missing(to replace the broken one) so I can attempt to fix the issue

**Comment by karolkolodziej** [comment]
You can search for that in the whole API: https://api.highcharts.com/highmaps/series.mappoint.cluster.drillToCluster
