### ISSUE TITLE
Per-level `levelIsConstant` option is not documented or present in TypeScript types

### ISSUE THREAD

**Issue by cebamps** [highcharts/highcharts#18786]
#### Expected behaviour
Assigning a `levelIsConstant` boolean value in a single level's configuration of a sunburst plot (`PlotSunburstLevelsOptions`) should type-check and be documented. The same comment applies to tree maps, presumably.

#### Actual behaviour
* TypeScript considers this assignment an error (see demo).
* The option is not documented ([series.sunburst.levels](https://api.highcharts.com/highcharts/series.sunburst.levels)).

Despite that, the demos ([sunburst chart](https://www.highcharts.com/demo/sunburst)) and samples in the repository (see fiddle link below) make use of that per-level `levelIsConstant` option. Only the per-series setting is documented ([`series.sunburst.levelIsConstant`](https://api.highcharts.com/highcharts/series.sunburst.levelIsConstant)).

To work around the issue, I am currently using TypeScript module augmentation to patch the interface.

#### Live demo with steps to reproduce
Demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/v10.3.3/samples/highcharts/plotoptions/sunburst-levelsize
TypeScript error: [long TypeScript playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBACWAcwBYGNUENYGc4BmUEIcA5KihtnmQNxwD0jcMAnmAKa4BccAjAAYAdAGYxAKAnoIAO1zwIYGMDm9EVTDhi5hAeWWr5cALxwA3hLhwtsPpevXUnKjD4AiIYICk7q3ABfABopaxUYABtOe38wzgAPNzh3AHVoCIATOEgwAFcIrBU5OAAmQX4Adj9rYP9cXIAjcKiYx1YEpPcAZVzZBtyoBTgAd2AYVDgM4AICTihOWXhcYAAvTjhi3BJ1qIA3TgjcasCQ61w54G4+AG1Yizuwjmjk+r6BhXdTtsnCrBuAXS+bVkWBAz3cACUIBAYJ8HnAsBEIhBhgARKDAJEAFQgADkIBlnjAoLlOEDHOh3tAPJBgIs5nDvj8YFgADJYBoHdQOJmEaAgQoecy0xbCEFggKM3kETEwOatXnWMDELiwNgeOmyOYAQSg6FZC2Q4yliqUc0K1OSAD4TbzdojSXx+AA2eE1eG1Jl7Lk3N33RXWb0RJ3kr2cfYRACSuAAwmoWYs+AREedQ98g11Vs8eQG4L0xjTgPEubbFfaIo64KJBH73YrPbyc7yg3wSmm2jJkVAAEJsAAKEDpSWJpPbjgyv3ZnMOCtzxBZRVkAFkCeCwDhEVEIsd636G0ym2GI3xRGPA+GDtG4-IE8OSWTa3AM1nZwH851hi40LCz45y5WSkfAI9zHQ90wvYM4AAFl-IMr3jLBE1Ye9YIgzM1lfRV3xpOZ0AWFlkE4Us7QdZ5qyAvd4X+O5gOsQF-BgaEIhUMBX2cLBCSgAAxflBWSW0RRgHioAFTosWcbIlHyQojA2Ag4AAHgaK1hUHUVxU4AIFMYZS4GAfAlJUwThH-TTtOU45gICOggA), showing that the demo's options do not type-check.

#### Product version
Highcharts 10.3.3

#### Affected browser(s)
n/a

**Comment by karolkolodziej** [comment]
Hi @cebamps!

Thank you for taking the time to describe it so nicely for us!

As a workaround for now you can extend the existing interface with missing properties and cast each level object- [demo](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBACWAcwBYGNUENYGc4BmUEIcA5KihtnmQNxwD0jcMAnmAKa4BccAjAAYAdAGYxAKAnAAdjE5QCWdJzgAFADYQYAZQCuMgEZ6ouGABlOAN04bcAeTAxgEGbgCiAD3kyAJp184Tm9OP3wkNEwcGFxhTW19IxMzSxs7R2dXXABvCTg4DWtbAElcAGEsmCw5AH4+QwgIQuqJAF8pdEq4CCcXNz4I6mjYjL78AF44XPyo2D5p-LhUTioYPgAiIUEAUnW8uFaAGil85xhC+f3T4LW4dYB1aA1AyDA9DSxMmTgAJkF+ADse3yR32uD0hjOFymV1YNw2iWMpngAHdgDBUHBfMACAQFKF4LhgAAvVSuOC4EiqQppXDAg7HfK4BTAbh8ADasIWi1YHE4G3BSWR60ZPKxnywHIAuqKeTIsCB+XcAEqNGAi2H5LAaLQogAiUGAOoAKhAAHIQfx8GBQPScWWLdDJaAbSCyeRQDVi8VVcxYQy2Xgw735AjQECfDbZN1yYTyxWtL0hghGj2XEOLMDELiwNgbWQyBQAQSg6EsMmQGKTGZ6Ck+LruAD5qyGrNq7Xx+AA2TWLdre0HemmBjm9-LckPDjSdh1DooaUoVNxVOR8JR2e1jxZTnQkpUTjMGdGu4CeQMtjNtjQduCiQRbkFbwchg9iqd8H6zsWdLRQABCbBqBA7rWram4ZvkvgSn6AZ2OmEH5MQVRfAAspaSrrGAODaoUGj0hm-Yhs+3qvjy763l+ZHzoulTVLcNp2pR27zrupLwQhR63OsKIrGg6pMTyV43j8D4HE+TGkcxaR8AALAJBTUeUtGrqwYHyTue7sRBnGugoKhyFgyCcBerbtkqd6iYRA69lKcBYPgJZQFgbAADzxLoBhIik84OL0WReD4-i+I2sKETK+wwI0GjOGAWnLFg-hQAAYuGkZ3C2MYwClUARlxxrLHArzvJ8fTdAQcAuYYjbRsBsbxpwrQuYwVVwMA+CVdVmXCEJDVNVV9LtK0dBAA).
