### ISSUE TITLE
useHTML on dataLabels changes zIndex (so tooltip appears behind)

### ISSUE THREAD

**Issue by peterchavasse** [highcharts/highcharts#18788]
#### Expected behaviour
Tooltips should always show infront of  dataLabels

#### Actual behaviour
Data label appears on top of tooltip (even though tooltip opacity is 1)

#### Live demo with steps to reproduce
https://jsfiddle.net/pc123/t01xnzyj/14/

Hover over data label - value will show over tooltip.  

Toggle useHTML to false and behaviour reverts to expected.

We need to have useHTML to wrap the dataLabel (in our production case)

#### Product version
Highcharts JS v10.3.3

#### Affected browser(s)
Chrome (that is all I have tested)

**Comment by karolkolodziej** [comment]
Hi @peterchavasse!

It is a known issue and it is not a bug. You can read more about that here: https://github.com/highcharts/highcharts/issues/4619
