### ISSUE TITLE
Combining line and column series alters column width and xAxis range

### ISSUE THREAD

**Issue by m-rm** [highcharts/highcharts#18782]
#### Expected behaviour
- Putting data points in a line series further apart should not change the column width of a column series in the same chart
- Also it should not cause the x-axis to change and the min and max to be ignored

#### Actual behaviour
Line is 1 day long:
![grafik](https://user-images.githubusercontent.com/7124804/229562542-f7a0cc6e-406a-4393-a33a-175941a67e36.png)

Line is 10 days long (no other changes):
![grafik](https://user-images.githubusercontent.com/7124804/229562749-41492da5-7a1b-4329-aea2-d62f97d9392b.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/hwuqr7cy/ Simply change the x value of the second data point of the line series closer to the first data point to see the issue.

#### Product version
Highcharts v10.3.3

#### Affected browser(s)
Probably all (tested Firefox and Edge)

**Comment by m-rm** [comment]
I tested a bit more:

Only line series
---------------
```js
Highcharts.chart('container', {
  "series": [{
    "data": [{
      "x": 0,
      "y": 2
    }, {
      "x": 10,
      "y": 2
    }],
    "type": "line"
  }],
  "chart": {
    "height": 300
  },
  "xAxis": {
    "min": 0,
    "max": 10
  },
});
```
![grafik](https://user-images.githubusercontent.com/7124804/229763957-6d4a4ec7-2923-40f4-86e8-1d99c67ec7e5.png)
xAxis min and max are respected.

Only column series
-------------------
```js
Highcharts.chart('container', {
  "series": [{
    "data": [{
      "x": 5,
      "y": 1
    }],
    "type": "column"
  }],
  "chart": {
    "height": 300
  },
  "xAxis": {
    "min": 0,
    "max": 10
  },
});
```
![grafik](https://user-images.githubusercontent.com/7124804/229764206-fb1d7ac5-9438-4df4-a642-fb61504d6497.png)
xAxis min and max are also respected. Column width looks ok.

Both together
--------------
```js
Highcharts.chart('container', {
  "series": [{
    "data": [{
      "x": 0,
      "y": 2
    }, {
      "x": 10,
      "y": 2
    }],
    "type": "line"
  }, {
    "data": [{
      "x": 5,
      "y": 1
    }],
    "type": "column"
  }],
  "chart": {
    "height": 300
  },
  "xAxis": {
    "min": 0,
    "max": 10
  },
});
```
![grafik](https://user-images.githubusercontent.com/7124804/229764310-1d8d4385-95bd-474d-9f6d-e095de8ecf35.png)
xAxis min and max are ignored, column width is disproportionate.

I hope this illustrates the problem better.

**Comment by bm64** [comment]
Hello @m-rm and thanks for contacting us.

It behaves like that, because when pointRange for a series is not set, then column width will be calculated from the minimal distance between the points from all the series on the xAxis. API reference: https://api.highcharts.com/highcharts/series.column.pointRange

When distance between points in one of other series is too small, you can use pointRange property to adjust column width.
Demo: https://jsfiddle.net/BlackLabel/ns9bjv4o/

**Comment by m-rm** [comment]
@bm64 
Thank you. `pointRange` is working, but how do I fix the xAxis? I can use `tickInterval` to fix the ticks, but `min` and `max` still don't line up with the edge of the plot because `pointRange` introduces some kind of padding.

I have multiple charts on one page and I want the xAxis to match the other ones.
