### ISSUE TITLE
Enabling pattern fill in React

### ISSUE THREAD

**Issue by PasinduPrabhashitha** [highcharts/highcharts#18798]
Hi,

Can I know how can I enable and use pattern fill in React? I tried to use this [pattern-fill-package](https://github.com/highcharts/pattern-fill) But it seems like this has been deprecated. So how can I use this in React?

Cheers!

**Comment by pawellysy** [comment]
Hi! Thanks for contacting us, but we are treating GitHub as a bug/feature tracking tool. With those kinds of questions please reach out to us via our support channels, which are listed here: https://www.highcharts.com/blog/support/

Thanks!
