### ISSUE TITLE
Calendar input bug on Chrome / Edge 112

### ISSUE THREAD

**Issue by tw2as** [highcharts/highcharts#18813]
#### Expected behaviour
Calendar input should behave like in previous versions of Chrome / Edge (111 and earlier versions)

#### Actual behaviour
Calendar input 
![image](https://user-images.githubusercontent.com/24268626/231435716-3432c2ad-0e1e-43f1-94d9-143cf0cba7e6.png)

Please note: It could be a problem within Chrome

#### Live demo with steps to reproduce
Go to: https://www.highcharts.com/demo/stock/stock-tools-gui and click on the calendar.

#### Product version
Highstock JS v10.3.3 (2023-01-20)

#### Affected browser(s)
Chrome & Edge @ 112

**Comment by bm64** [comment]
Hello @tw2as and thanks for reporting the issue.

It seems to work fine on Safari and Firefox.

**Comment by bm64** [comment]
Workaround:
Set `min-height` property for `highcharts-range-selector` input:
`.highcharts-range-selector {
	min-height: 15px;
}`
Demo: https://jsfiddle.net/BlackLabel/tgqpkb8c/
