### ISSUE TITLE
Bar should start plotting from given base value tick and not from min value

### ISSUE THREAD

**Issue by PurvaK17** [highcharts/highcharts#18828]
#### Expected behaviour
Bar should start plotting from given tick and not from min value
![waterfall chart with base value](https://user-images.githubusercontent.com/101875334/232021891-85b019a7-8d97-4265-87ad-6da8d1811dbe.png)
As per above image, min value is 1.0 but bars start plotting from base value i.e. 2.059

#### Actual behaviour
Bars should start plotting from base value, so is there any provision to achieve this

Bar started plotting from min value i.e. 100K

#### Live demo with steps to reproduce
https://jsfiddle.net/0jrwm3vg/

#### Product version
latest version - 10.3.3

#### Affected browser(s)
Chrome, firefix

**Comment by bm64** [comment]
Hello @PurvaK17 and thanks for contacting us.

I've checked your demo and I couldn't find anything incorrect. Axis min and max allows you to adjust the range where data is being displayed and in your case, setting yAxis.min to 100k, basically means that points that are below 100k are partially cropped. I think `threshold` property is what you're looking for: https://jsfiddle.net/BlackLabel/rf2sntzw/
API reference: https://api.highcharts.com/highcharts/series.waterfall.threshold

**Comment by bm64** [comment]
@PurvaK17 as I said in my previous message, `threshold` property can be used to define value from which first point should be plotted. Here is an example based on your description: https://jsfiddle.net/BlackLabel/ahejzyrs/

If that is not what you're looking for, please visit our other support channels and describe precisely what do you want to achieve and our support team will help you with that: https://www.highcharts.com/blog/support/. When it comes to github, we use it strictly for bug reports / feature requests, and this one doesn't seem to be a bug, so I'm closing it for now.
