### ISSUE TITLE
Solid gauge with useHTML in data labels shows wrong series in tooltip

### ISSUE THREAD

**Issue by palhal** [highcharts/highcharts#18821]
#### Expected behaviour
Hovering a data label shows a tooltip for the associated series, independent of the ```dataLabels.useHTML``` option

#### Actual behaviour
Hovering a data label shows tooltip for a different series if ```useHTML = true```

#### Live demo with steps to reproduce
https://jsfiddle.net/pkhalle/x87fpbvo/

1. Hover the data label (120 km/h) and see that the tooltip shows a different series than the one associated with the label
2. Set ```useHtmlLabels = false``` and see that the bug disappears

#### Product version
Highcharts 10.3.3

#### Affected browser(s)
Chrome, Edge (at least)

**Comment by bm64** [comment]
Hello @palhal and thanks for reporting the bug. Looks like it is broken since 8.1.0: https://jsfiddle.net/BlackLabel/0t9yez2d/
