### ISSUE TITLE
When boost mode enable, last point is not accessible via hover

### ISSUE THREAD

**Issue by Slayug** [highcharts/highcharts#18856]
#### Expected behaviour
Last point of the series must be highlight when the mouse is at the right, only work when boost mode is disabled:
![image](https://user-images.githubusercontent.com/1078777/233319005-26f14ddc-1b34-47db-98b1-1f15e41855df.png)

#### Actual behaviour
When boost mode is enabled we have to zoom to reach the last point while hovering the series.
![image](https://user-images.githubusercontent.com/1078777/233319289-3c132c9b-3240-4a79-a5f9-1d1758fc2e51.png)

#### Live demo with steps to reproduce
Look after `boostThreshold` param
http://jsfiddle.net/7zg9L5n0/1/

#### Product version
 Highcharts JS v10.3.3 (2023-01-20)

#### Affected browser(s)
Tested on Chrome and Firefox

**Comment by karolkolodziej** [comment]
Hi @Slayug and thank you for reporting the issue.

Internal note: 
It looks like the `result` has the wrong `i` property which influences the point returned by the `getPoint`.
Needs further investigation.
https://github.com/highcharts/highcharts/blob/866999f10f4ddcbd423ef3a46b063fc62af8cc40/ts/Extensions/Boost/BoostSeries.ts#L1338-L1349
