### ISSUE TITLE
Updating the data of MapSeries produces bad animation

### ISSUE THREAD

**Issue by hubertkozik** [highcharts/highcharts#18857]
#### Expected behaviour
There shouldn't be any animation after updating the data of the map series.

#### Actual behaviour
There is animation after updating the data of the map series.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/296L0qvf/

1. Click the point to fire series update -> there is an animation that is bad.

#### Product version
Highmaps v10.3.3

#### Affected browser(s)
n/a

#### Workaround
https://jsfiddle.net/BlackLabel/qo6k518j/

Set the `chart.animation` to `false`.

**Comment by KamilKubik** [comment]
Another workaround to avoid disabling animations related to other functionalities is to use the `setData` method on a series: https://jsfiddle.net/BlackLabel/1e38q9kf/.
