### ISSUE TITLE
Profile plot i.e multiple timeseries in one plot

### ISSUE THREAD

**Issue by Stianta** [highcharts/highcharts#18882]
When there is multiple datapoints available along a line,
i.e. pressure along a pipeline
temperature through a heat exchanger one wants to present multiple timeseries data towards each other.
it would be great to be able to plot one vector towards another vector of points.
This of course would give a "single viewpoint", so in the case here, notice the slider for looking at different points in time.
however the most important is to just be able to view the last "current" values.

Example:

![image](https://user-images.githubusercontent.com/131871686/234555087-1e1ae835-fe1a-4e9a-8fe8-3ef0f018b4e1.png)

or looking at the temperature along a pipeline, many Temperature timeseries individual points plotted towards the position in the pipeline. to give an overview along the flowline, instead of the history of the individual sensors.

![image](https://user-images.githubusercontent.com/131871686/234555508-bc942172-c9a2-4b5e-9b94-55c422f4e581.png)

in both of these cases, each of the "points" is its own set of timeseries data
that could be also viewed like this:

![image](https://user-images.githubusercontent.com/131871686/234556067-72ff5be3-0d5b-4e53-bb04-d9a8b341c010.png)

as we are transitioning our product to cloud, we would like to be able to use HighCharts for these kinds of plots as well

**Comment by Stianta** [comment]
[ProfileDataExample.csv](https://github.com/highcharts/highcharts/files/11332030/ProfileDataExample.csv)

added example data

**Comment by pawellysy** [comment]
Hi! Thanks for reaching out to us!
Before you created this ticket, had you contacted our main support line?
 If you didn't Please contact us via [our available support channels](https://www.highcharts.com/blog/support/).

What you are asking for seems to be achievable through the simple highcharts configuration, and we treat GitHub as a bug/ feature tracking tool. I am closing the ticket for now. Thanks for understanding.
