### ISSUE TITLE
Docs: add information about connectNulls behavior for stacked area

### ISSUE THREAD

**Issue by vitaliy-kretsul** [highcharts/highcharts#18881]
From forum support I learned that _"The connectNulls option connects the extreme points between nulls by default, but when using stacking on an area chart, it has a special effect. It treats nulls similar to zeros and instead of sharply breaking the series, they interpolate to 0 for the next tick."_
I think this information should be reflected in docs.

**Comment by pawellysy** [comment]
Thanks @vitaliy-kretsul for suggestion!
