### ISSUE TITLE
Vertical line on click for tooltip should persist

### ISSUE THREAD

**Issue by rahulbadekarr** [highcharts/highcharts#18901]
# Vertical line on click for tooltip
 I am trying to give vertical line on tooltip whenever it is displayed
    on below jsfiddle ( case when I click and pointer is there it shows but I want when I leave as well it should show the vertical line and tooltip till the next click)

# Library related to the feature

# Link : https://jsfiddle.net/BlackLabel/hmk9t7s5
![image](https://user-images.githubusercontent.com/91235653/235068405-35b86b94-56ec-484a-b4cf-d30029cd3d65.png)

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by pawellysy** [comment]
Hi @rahulbadekarr, as I've seen, you got your answer on our support channel, and this is achievable with simple modification. Please don't duplicate the tickets on GitHub until you are being supported on other support channel. 
Closing as `not planned`
