### ISSUE TITLE
Plotline Should Rotate in every direction on chart,

### ISSUE THREAD

**Issue by dhanashrivitara** [highcharts/highcharts#18917]
As now plotLine can be drawn from x-axis , yaxis llike vertivcally and horizontally but it should rotate as per required direction not just 90degree  it should 45degree and etc .

![image](https://user-images.githubusercontent.com/81235677/235501602-2fe6c417-bf85-4334-9fe2-d2f5387e7cbd.png)

As example shown in image plotlien new direction that red line and also need to curve the line.

Thank You.

**Comment by dhanashrivitara** [comment]
As line like this
![image](https://user-images.githubusercontent.com/81235677/235502127-8ca6df69-869b-451f-b0f8-879f1d6d5c29.png)

And curve lines liek this
![image](https://user-images.githubusercontent.com/81235677/235502269-755f6bee-0037-4462-8434-ca21c9b98e34.png)

**Comment by pawellysy** [comment]
Hello @dhanashrivitara, these configurations are available through API. First of all, we have such demo with regression line: https://www.highcharts.com/demo/combo-regression
And all the other lines you can achieve with simple series/configurations. Please reach out to us via [our available support channels](https://www.highcharts.com/blog/support/) where our support engineers are more then happy to help you with tweaking charts to your needs. 
Closing, as a question.
