### ISSUE TITLE
Axis labels have disappeared after the change from 10.3.3 to 11.0.0.  Resolved:  the problem was that the default axis label color had changed and now matched my background color.

### ISSUE THREAD

**Issue by downhiller** [highcharts/highcharts#18915]
#### Expected behaviour

My axis labels to show

#### Actual behaviour

After the change to 11.0.0 my axis labels have disappeared.  I've reverted to 10.3.3 and they work on that.

#### Live demo with steps to reproduce

I've not time to make one today, but can in the week if this is an uncommon issue

#### Product version

Highcharts 11.0.0

#### Affected browser(s)

All that I tried - Chrome, Edge, Firefox, Opera (all on Windows 11), and also Chrome Android.

**Comment by pawellysy** [comment]
Hi @downhiller, thanks for your input. Unfortunately without any reproduction steps we are unable to investigate the issue. Could you please share the demo, where the issue is reproduced? You can start here: https://jsfiddle.net/BlackLabel/g7tq01np/2/

**Comment by downhiller** [comment]
[[393681](https://www.rootsandrain.com/rider60950/daniel-froese/results/)
](https://www.rootsandrain.com/rider60950/daniel-froese/results/)

That works on 10.3.3.  If I change it to 11.0.0 all of the axis labels disappear.

**Comment by downhiller** [comment]
https://jsfiddle.net/d0fphaeo/

**Comment by downhiller** [comment]
I've fixed this.  I can't find the information for v10, but the default color for axis labels is now #333.  I suspect that it used to be #666.  The issue here is that my chart background is.... #333.  So they disappeared, as they were suddenly the same color, #333 on #333, where before they were #666 on #333.

Trivial to fix, now that I know the issue.
