### ISSUE TITLE
Column overlapping 

### ISSUE THREAD

**Issue by nizrix** [highcharts/highcharts#18916]
**Expected behaviour**
Multi axis chart with multiple columns should be displayed thicker and one next to another.

**Actual behaviour**
In multi axis chart with more then 1 column series, the columns is very thin and overlapping each other.

**Live demo with steps to reproduce**
https://jsfiddle.net/nizrix/yvu3dot0/50/

**No special action needed.**

**Product version**
Highcharts JS v9.3.1 (2021-11-05) also checked on latest.

**Affected browser(s)**
All

**Comment by pawellysy** [comment]
Hi @nizrix, this ticket does not sound like a bug, but a simple changes in the configuration file might be able to solve your problems. Did you try reaching out to us [via our available support channels](https://www.highcharts.com/blog/support/)?

Our support engineers are more than happy to help you to tweak the chart to your needs :)

**Comment by TorsteinHonsi** [comment]
@nizrix It looks to me you want to set the [pointRange](https://api.highcharts.com/highcharts/series.column.pointRange) to one hour: https://jsfiddle.net/highcharts/74xk0cr2/

**Comment by nizrix** [comment]
Hi @TorsteinHonsi, that did the trick! many thanks!

@pawellysy, Still I cannot understand why in this case the cart didn't calculated this value by itself like in many other charts I am working with.
This is why I opened this as a bug.

Thanks for your help.

**Comment by TorsteinHonsi** [comment]
@nizrix You're welcome!

> Still I cannot understand why in this case the cart didn't calculated this value by itself like in many other charts I am working with.

The column width is based on the point range, as you saw in the previous post. The point range is by default given as the shortest distance between any two points. In your fiddle, it is one our between most of the points. But the very first point is at 12:55 hours, and the next one at 13:00. Therefore the calculated point range becomes 5 minutes, and the columns render so narrow that those two points won't overlap.
