### ISSUE TITLE
.NET Wrapper cannot create a chart using HighchartsRenderer after v11.0.0

### ISSUE THREAD

**Issue by JayHTang** [highcharts/highcharts#18912]
#### Expected behaviour
Use `HighchartsRenderer.RenderHtml()` to create a chart.

#### Actual behaviour
Got `TypeError: Highcharts.chart is not a constructor`

In `HighchartsRenderer.GetCreateChartJavascript()`, the chart is created by `stringBuilder.Append("new Highcharts.chart(\"" + _chart.Chart.RenderTo + "\",ChartOptions);");`. A chart should be created either by `Highcharts.chart()` or `new Highcharts.Chart()` for v11.0.0 update. 
 
#### Product version
Highcharts .NET v10.3.3.1

**Comment by karolkolodziej** [comment]
FYI @brofixo

**Comment by brofixo** [comment]
@JayHTang Solution has been included to the Highcharts .NET v10.3.3.2 (Which has been uploaded to the NuGet today and should be public soon) Upgrade .NET wrapper is one way to resolve it. Another way is to download the older JS library (older than v11) and attach it to your project.
