### ISSUE TITLE
Tooltip does not show if there are multiple charts and one is hidden

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#18928]
#### Actual behaviour
If there is more than one chart, and `display: none` is set for one of the charts, the tooltip shows only for the first chart.

#### Live demo with steps to reproduce
**Demo:** https://jsfiddle.net/BlackLabel/jr82ognp/
1. Switch tabs
2. Hover over a series (there's no tooltip).

#### Product version
Regression from Highcharts 11 (everything worked well for <= 10.3.3)

**Comment by TorsteinHonsi** [comment]
I think this is a duplicate of #18920. I'll have a look.
