### ISSUE TITLE
Custom GeoJSON Drillable Maps Do Not Render Correctly

### ISSUE THREAD

**Issue by wergeld** [highcharts/highcharts#18925]
I believe this is caused maybe by mapView not being set or not having a default? This has not been an issue previously and I would imagine that the lack of default mapView would break even the initial map. However, the initial map loads fine. We are using custom ArcGIS maps to handle specific state-defined areas as well as including US Territories and their sub-state areas that the HighCharts map collection does not contain.

#### Expected behaviour
Using custom GeoJSON maps created from ArcGIS clicking on a drillable map point should load another map of that region selected with higher detail. The parent and child maps are GeoJSON created from our ArcGIS system. An example would be loading the USA national map and clicking on Texas. This causes the Texas county level map to load and show data as a choropleth.

#### Actual behaviour
Using custom GeoJSON maps and clicking on Texas shows a quick animated zoom to the county level map of Texas then it immediately zooms back out to the national view with Texas broken up by counties but no choropleth. Clicking on the drill up navigation completely breaks the view of the USA map and no further action can be made in the map (no choropleth data and no clickability).
After clicking on TX:
![image](https://user-images.githubusercontent.com/133511/235675566-32d4f971-e3cd-428d-9fc0-6bd70f6f4971.png)

#### Live demo with steps to reproduce
Unbale to provide demo that works as ArcGIS maps are not available externally.
However, code is provided here:
https://jsfiddle.net/wergeld/uaowedj7/

#### Product version
HighCharts v11
HighMaps v11

#### Affected browser(s)
Chrome, Edge.

**Comment by hubertkozik** [comment]
Indeed, there is an issue with the drilldown for using GeoJSON maps. 

_Internal notes:_
**Simplified demo:** https://jsfiddle.net/BlackLabel/L8yk64zh/
In the above demo, after drilling down the zoom is badly calculated, if you click "minus" button from map navigation multiple times you can see that map is showing up.

**Comment by wergeld** [comment]
Correct,
It seems that the drill down does not "clear" to initial map and tries to render the new map in the same projection frame. I do not think it should be "zooming" down to the area. This is a completely different GeoJSON file (and could even have different projection parameters) than the National GeoJSON.

**Comment by hubertkozik** [comment]
I have prepared a workaround for that issue if you need a fix without waiting for the next release with this fix included. If you want to use it in your project just copy-paste the IIFE function.

**Workaround:** https://jsfiddle.net/BlackLabel/mLrwcj38/

Explanation: GeoJSON maps will have the default `drilldown.mapZooming` property set to `false`, because GeoJSON provided by HC cannot have fancy animation of "zooming out" while drilling-up due to lack of projection properties (lon/lat etc.)

**Comment by wergeld** [comment]
Thank you for the proposed workaround. I see it does work on the fiddle and and does work in our internal "playground". However, it does not play nice in the application using typescript and node module of highcharts instead of direct CDN libraries - throws many errors on "H.seriesTypes.map.prototype.animateDrilldown". We can wait for official fix in the core highcharts.

**Comment by wergeld** [comment]
Let me know if this should be moved to a new issue. I think this is the same issue as the behavior has not changed at all.

Tested under v11.0.1 and issue persists. Fiddle to reproduce: https://jsfiddle.net/wergeld/3djeg6ov/
Click on Florida as it has data (other states will just have null value counties).
Map does drill down to the state view of the counties then zooms back out to national view.
Click "Sample National" breadcrumb to drill back up to national view
Click on any other state - same issue occurs, but this time the Florida county-level map is visible again.
Click on "Sample National" breadcrumb to drill back up.
Click on another state and "Sample National" breadcrumb to drill back up.
Now map is empty - no longer a choropleth, just has the state outlines.
