### ISSUE TITLE
Plot line label is not centered when useHTML true and align center

### ISSUE THREAD

**Issue by jakubjanuchta** [highcharts/highcharts#18946]
#### Expected behaviour
When the `plotLines.label.useHTML` property is set to `true` and the `plotLines.label.align` is set to `center`, the plotLine label should be centered.

#### Actual behaviour
When the `plotLines.label.useHTML` property is set to `true` and the `plotLines.label.align` is set to `center`, the plotLine label is not centered.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/tvoc1rf2/

#### Product version
Highcharts v11.0.0

**Comment by pupismyname** [comment]
I'm here two years later to say this bug still exists, but explicitly setting `x: 0` alongside `useHTML: true` and `align: 'center'` seems to fix it.

https://jsfiddle.net/bgjmdhwr/
