### ISSUE TITLE
Offline JPEG export does not work with Highcharts v8.2.0 at client side exporting

### ISSUE THREAD

**Issue by Dinkarv** [highcharts/highcharts#18957]
We have a strict CSP where blob: and data: sources are not allowed for images. The highcharts exporter seems to depend on rendering blob sourced images somewhere offscreen when exporting as JPEG. As a result of our CSP this fails.

We tried using the legacy offline exporting library [highcharts-export-clientside](https://github.com/A----/highcharts-export-clientside) combined with highcharts 8.2.0.

Is there a way to make the offline exporting for JPEG work without using blob/data sourced images?

**Comment by oysteinmoseng** [comment]
Hi @Dinkarv, if neither blob nor data sources are allowed, I don't see any way for us to refer to the created image and initiate a download on the client side... You may have to rely on the export server instead - optionally [setting up your own installation](https://www.highcharts.com/docs/export-module/setting-up-the-server) of it.

Closing this for now, but if I am missing something feel free to comment and we can reopen.
