### ISSUE TITLE
options.chart.defaultSeriesType: 'scatter' without series.type renders odd lines

### ISSUE THREAD

**Issue by AuroraLS3** [highcharts/highcharts#18955]
#### Expected behaviour

Highcharts 10.3.3 renders following:
![image](https://user-images.githubusercontent.com/24460436/236611420-bbc9c54e-49b5-49a1-9897-b550452753f8.png)

#### Actual behaviour

Highcharts 11.0.0 renders:
![image](https://user-images.githubusercontent.com/24460436/236611445-981492d5-e130-4769-9009-d287561a42b1.png)

The browser console also logs Highcharts error 15 (Out-of-order data)
![image](https://user-images.githubusercontent.com/24460436/236611904-ec33a4a1-4d51-46c3-9d43-9418ca9d2893.png)

#### Live demo with steps to reproduce

https://jsfiddle.net/auzqx4fc/1/

The rendering issue and error 15 seems to go away if `type: 'scatter'` is added to the series. This suggests that defaultSeriesType is no longer being applied
![image](https://user-images.githubusercontent.com/24460436/236612007-65354c7b-7728-449b-9ff1-07f43577b1a4.png)

#### Product version

`package.json: "highcharts": "^11.0.0",`

#### Affected browser(s)

At least Firefox and Chrome

**Comment by TorsteinHonsi** [comment]
Hi, thanks for reaching out to us! 

The `chart.defaultSeriesTypes` option has been deprecated for a long time, and was removed in v11. Instead, use `chart.type`. See https://jsfiddle.net/highcharts/qcug3mnr/.
