### ISSUE TITLE
Labels don't get positioned properly after rotating them in donut chart

### ISSUE THREAD

**Issue by SyedTayyab99** [highcharts/highcharts#18958]
I have the code attached for a donut chart in which by default the labels appeared upside down for segments which are on the bottom part of the screen. I wrote a function to rotate them but now they don't appear in the middle. Even the vertical align property doesn't take effect. Please help me with this.

[donut chart.zip](https://github.com/highcharts/highcharts/files/11418651/donut.chart.zip)

**Comment by bm64** [comment]
Hello @SyedTayyab99 and thanks for contacting us. 

We use Github strictly as a bug report / feature request tracking tool and I couldn't find anything incorrect with Highcharts behaviour in the code that you provided. Please visit our other support channels where our team will help you with improving the custom rotating code or finding out another method to meet your requirements: https://www.highcharts.com/blog/support/, https://www.highcharts.com/forum/
