### ISSUE TITLE
Marker Cluster click not working for Microsoft Edge with Internet Explorer 11 Mode enabled

### ISSUE THREAD

**Issue by hubertkozik** [highcharts/highcharts#18964]
#### Expected behaviour
Clicking on a marker cluster point should allow users to zoom-in and show more points.

#### Actual behaviour
Clicking on a marker cluster point should doesn't zoom-in and show more points.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/6mtw2q8y/
Click on the marker cluster point to zoom-in and show more points.

#### Product version
Highcharts v11.0.1 (es5)

#### Last working version
Highcharts v9.3.3

#### Affected browser(s)
Microsoft Edge with Internet Explorer 11 Mode

**Comment by KacperMadej** [comment]
Unable to recreate in v11.4.6 - seems to be working now.
Closing as resolved.
