### ISSUE TITLE
Implement a feedback and reward system designed to dissuades developers from closing feature requests with dismissive responses

### ISSUE THREAD

**Issue by philipswan** [highcharts/highcharts#18962]
# Description of the feature
There's nothing more annoying that taking the time to provide feedback and then receiving a canned response that dismisses your input in a disdainful manner and and makes it pretty clear that you're feedback will be summarily ignored. This is bad for the product, because good feedback does not get added to the backlog and appropriately prioritized. It also discourages adoption of the product because customer needs are not met.

To help prevent this from happening a feedback system should be implemented. It could be modeled on a typical customer service interface, but at a minimum it would ask something like:
"How satisfied were you with this response?"
and
"What could we have done better?"

The feature should also collect statistics on how well a customer facing developer and/or their AI assistant is doing at fielding feature requests. The feedback collected could also be used to train an AI to be better at responding to questions and feedback.

# Library related to the feature
Highcharts

**Comment by TorsteinHonsi** [comment]
Thanks for your feedback! This is something we are working continuously to improve and maintain. Regarding https://github.com/highcharts/highcharts/issues/18956, which I assume you refer to specifically, can you provide more information, preferably a live demo, so we can get a better understanding on how to help you?
