### ISSUE TITLE
Data labels for Dumbell of multiple series are collecting at the same serie.

### ISSUE THREAD

**Issue by kluvin** [highcharts/highcharts#18960]
Am not sure what has changed internally here, but it looks like an issue which could be more general than just this case I observed.

Highcharts GPT was particularly useful in creating an MRE!

#### Expected behaviour
Data labels are attached to their respective series

#### Actual behaviour
All data labels are attached to the same series

You can downgrade the imported scripts from 11 to 10 to see the previous behavior.

#### Live demo with steps to reproduce
https://jsfiddle.net/kluvin/a1Lg4k75/

#### Product version
11.0.0 >
 
#### Affected browser(s)
FF, not tested in Chrome.

**Comment by bm64** [comment]
Hello @kluvin and thanks for reporting the issue.

_Internal note:_
Bisected to: 5dbf2a4d1e5e84a296311b7b859b025955a3996e
