### ISSUE TITLE
HC Maps + Drilldown module - Series are not removed after drilling into one of them

### ISSUE THREAD

**Issue by wergeld** [highcharts/highcharts#18961]
[#18925](https://github.com/highcharts/highcharts/issues/18925), map drill down was broken for GeoJSON maps.
Was first iteration of this issue.
I cannot re-open that ticket.

#### Expected behaviour
Clicking on state should drill down to sub-state area type view of data.

#### Actual behaviour
Drilldown occurs then map zooms back out to national view with sub-state delineation visible for state clicked on.
Repeated steps of this drilldown/drillup result in map data breaking.

#### Live demo with steps to reproduce
Let me know if this should be moved to a new issue. I think this is the same issue as the behavior has not changed at all.

Tested under v11.0.1 and issue persists. Fiddle to reproduce: https://jsfiddle.net/wergeld/3djeg6ov/
Click on Florida as it has data (other states will just have null value counties).
Map does drill down to the state view of the counties then zooms back out to national view.
Click "Sample National" breadcrumb to drill back up to national view
Click on any other state - same issue occurs, but this time the Florida county-level map is visible again.
Click on "Sample National" breadcrumb to drill back up.
Click on another state and "Sample National" breadcrumb to drill back up.
Now map is empty - no longer a choropleth, just has the state outlines.

#### Product version
HighMaps v11.0.1

#### Affected browser(s)
Chrome, Edge, Safari all latest versions.

**Comment by hubertkozik** [comment]
This bug is not related only to the geoJSON files, but more to the logic of how to handle multiple series while drilling.

**Simplified demo:** https://jsfiddle.net/BlackLabel/m7dw8sqc/
Click on California to drilldown to another map -> Canada not removed.

**Comment by rsrgithub** [comment]
I am also having this issue in Highchart V11. The issue could be seen in the following fiddle -

https://jsfiddle.net/mngy03uq/

**Comment by hubertkozik** [comment]
I have prepared a workaround for this issue. If you want to use it in your project with Highcharts v11.0.1 all you need to do is copy-paste the IIFE function from one of the below demos. Also, in the demo with categorized series, it is necessary to set `drilldown.mapZooming` property to `false` and disable redrawing for updating the `mapView` during the drill down.

**Simplified demo: ** https://jsfiddle.net/BlackLabel/u3k0wybo/
**Main issue demo (with geoJSONs): ** https://jsfiddle.net/BlackLabel/798jgwt6/
**Categorized demo: ** https://jsfiddle.net/BlackLabel/Ldcqu3bf/

Similiar solutions will be used in Drilldown Module for HC Maps.
