### ISSUE TITLE
Country map with dynamic font size for labels

### ISSUE THREAD

**Issue by SyedTayyab99** [highcharts/highcharts#18978]
Hi, 

Is there a way to have the font size of the country names on map be adjusted dynamically so that all of the country names in the default zoomed out state?

**Comment by mabuhaddah** [comment]
Dear @circleci-mu ,
Could you please share the expected due date to have this fix. please consider its important to have it.

Thanks,

**Comment by KacperMadej** [comment]
**Internal note:** This could be a core feature - dataLabels placement via font size adjustments.
