### ISSUE TITLE
TooltipOptions borderWidth is a string, but should be number

### ISSUE THREAD

**Issue by rbirkgit** [highcharts/highcharts#18977]
#### Expected behaviour

With latest Highcharts the TooltipOptions.borderwidth has wrong type.

#### Actual behaviour

borderWidth should be a number, like all other places.

#### Live demo with steps to reproduce

```
export interface TooltipOptions {
    borderWidth?: string;
```

#### Product version
11.0.1

**Comment by bm64** [comment]
Hello @rbirkgit and thanks for contacting us.

I've checked [v11.0.1 package](https://github.com/highcharts/highcharts/releases/tag/v11.0.1), and it looks like `borderWidth` has `number|undefined;` type. Could you tell me where precisely did you find that ts declaration?

**Comment by rbirkgit** [comment]
I am using the file `highcharts.d.ts` in:

```
  "name": "highcharts",
  "version": "11.0.1",
```

Then towards the bottom of the file you see:

```
/**
 * (Highcharts, Highstock, Highmaps, Gantt) Options for the tooltip that appears
 * when the user hovers over a series or point.
 */
export interface TooltipOptions {
.
.
    /**
     * (Highcharts, Highstock, Highmaps, Gantt) The pixel width of the tooltip
     * border. Defaults to 0 for single tooltips and 1 for split tooltips.
     *
     * In styled mode, the stroke width is set in the `.highcharts-tooltip-box`
     * class.
     */
    borderWidth?: string;
```

**Comment by bm64** [comment]
@rbirkgit now I see, thanks for clarification 👍
