### ISSUE TITLE
highcharts.d.ts is 603000 lines long and freezes editors

### ISSUE THREAD

**Issue by rbirkgit** [highcharts/highcharts#18980]
#### Expected behaviour

I expect type file to be split in smaller files and more manageable. It is over 603000 lines long and took me all night to index in IntelliJ and still afterwards my machine is basically down.

#### Actual behaviour

Split to smaller type files

#### Product version
11.0.1

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! FYI @bre1470

**Comment by zernie** [comment]
This issue totally breaks auto-complete and type-checking :(

**Comment by rbirkgit** [comment]
It makes it really hard to work with Highcharts and I tend to avoid it just for this reason. Hopefully this can be fixed.

**Comment by karolkolodziej** [comment]
Hi @rbirkgit!
Thank you for bringing our attention to this! We are investigating this issue and we are looking into possible solutions!
We will keep you posted!

**Comment by oleksandr-honcharov-simpligov** [comment]
Thanks for your fix. 
However, the problem still exists until the fix is released.
When are you planning to release a new version?

**Comment by rbirkgit** [comment]
I _LOVE_ 11.4.1 and the new type files. It's lightning fast now!

**Comment by trinhngocdiep** [comment]
From `11.4.0` to `11.4.1` is a breaking change, not a minor / bugfix release as indicated by the version number.

**Comment by bre1470** [comment]
Hello, @trinhngocdiep!
Thank you for the feedback. Your issue cannot be replicated.
Please take a look at https://github.com/bre1470/testproject-es6 for a working setup to compare.
You can change there the `tsconfig.json` to `CommonJS` and use non-ES6 imports like yours as well.
If your issue remains, please create a new issue with your `tsconfig.json` and ideally some demonstration code.

**Comment by pietmichal** [comment]
This should've been considered a breaking change.

**Comment by karolkolodziej** [comment]
@pietmichal Could you please elaborate on what should be considered a breaking change? 
Can you recreate that so we can test it?
