### ISSUE TITLE
horizontal and vertical Offsets bugged in inverted Sankey charts

### ISSUE THREAD

**Issue by allendemoura** [highcharts/highcharts#18988]
#### Expected behaviour

series.nodes.offsetVertical moves node vertically
series.nodes.offsetHorizontal moves node horizontally

#### Actual behaviour 

series.nodes.offsetVertical has no effect
series.nodes.offsetHorizontal moves node diagonally

#### Live demo with steps to reproduce
https://jsfiddle.net/nw5mq3p2/4/

#### Product version
latest

#### Affected browser(s)
all

**Comment by bm64** [comment]
Hello @semichrist and thanks for reporting the issue. Most likely it is related to https://github.com/highcharts/highcharts/issues/17594

As a workaround you can use deprecated `offset` option to move nodes horizontally in inverted chart: https://jsfiddle.net/BlackLabel/t3zwrf5g/
