### ISSUE TITLE
Legend items don't get crossed when using setVisible(), get crossed when hovered on

### ISSUE THREAD

**Issue by dimazah30** [highcharts/highcharts#18986]
#### Expected behaviour
Legend items either get crossed consistently, or don't get crossed like in the previous version of the library.

#### Actual behaviour
Legend items get crossed when hovered on.

#### Live demo with steps to reproduce
Press "Show/Hide all" , hover over legend items. http://jsfiddle.net/aLfr03ju/1/
Bug can't be reproduced in version 10.0, since there is no crossing of legend items at all  http://jsfiddle.net/aLfr03ju/2/

#### Product version
Highcharts JS v11.0.1 (2023-05-08)

#### Affected browser(s)
 Chrome Version 110.0.5481.178 (Official Build) (64-bit)

**Comment by bm64** [comment]
Hello @dimazah30 and thanks for reporting the issue.

**Comment by TorsteinHonsi** [comment]
@dimazah30 I am not a hundred percent sure I understand your issue, but are you referring to the strike-through effect of hidden series' legend item?

In that case, I already made a fix that is coming into the next release: https://jsfiddle.net/highcharts/yetp1zvs/

With the fix, the strikethrough will be visible immediately after hiding the series.
