### ISSUE TITLE
Volume by Price indicator throwing an error after updating the Ranges

### ISSUE THREAD

**Issue by jakubjanuchta** [highcharts/highcharts#18984]
#### Expected behaviour
Volume by Price indicator Ranges should update when changing the value.

#### Actual behaviour
When changing the volume by Price indicator Ranges, `Cannot read properties of undefined (reading 'length')` error is thrown and the indicator disappears.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/846xwk7m/

1) In Stock Tools, add Volume by Price Indicator with any Ranges.
2) Edit the Indicator Ranges value in Stock Tools
3) The indicator will disappear and the error will be thrown.

#### Product version
Highcharts v11.0.1

**Comment by jakubSzuminski** [comment]
I think it was solved in this PR: https://github.com/highcharts/highcharts/pull/18792

**Comment by jakubjanuchta** [comment]
Yes, [#18792](https://github.com/highcharts/highcharts/pull/18792) solves it.

**Working demo:** https://jsfiddle.net/BlackLabel/anwzem9g/
