### ISSUE TITLE
Snakey chart nodes change shape when flows weights as small

### ISSUE THREAD

**Issue by FusionSnowball** [highcharts/highcharts#18999]
#### Expected behaviour
The nodes of a sankey chart should be drawn in the same style no matter what size the flows to it are. 

#### Actual behaviour
When a node has much smaller flows to it than the other nodes in the chart it's drawn as a circle, rather than an rounded corner rectangle. It doesn't appear to be a case that it's the same shape but with a smaller height, it's distinctly round. 

#### Live demo with steps to reproduce
See node labelled renewable in this example https://jsfiddle.net/8rxjefhm/4/

#### Product version
Highcharts 11.0.1

#### Affected browser(s)
Chrome 113

**Comment by bm64** [comment]
Hello @FusionSnowball and thanks for reporting the issue!

**Comment by hubertkozik** [comment]
This issue has been resolved in https://github.com/highcharts/highcharts/issues/18956. Closing as completed.
