### ISSUE TITLE
Small flows not visible on lower resolution sankey charts

### ISSUE THREAD

**Issue by FusionSnowball** [highcharts/highcharts#19000]
#### Expected behaviour
All flows should be visible no matter their weight or the chart size

#### Actual behaviour
When flows are much smaller than the other flows in a chart and the chart size is relatively small (but still a plausible size for a real application) the small flow are not visible.

#### Live demo with steps to reproduce
See node labelled as renewable on this chart, it should display 3 small flows from it to the right - https://jsfiddle.net/8rxjefhm/5/ 

#### Product version
Highcharts 11.0.1

#### Affected browser(s)
Chrome 113

**Comment by bm64** [comment]
Hello @FusionSnowball and thanks for contacting us.

There is a `minLinkWidth` property exactly for cases like this one, which allows you to define minimal link width: https://jsfiddle.net/BlackLabel/vtaczwd8/
API reference: https://api.highcharts.com/highcharts/series.sankey.minLinkWidth
