### ISSUE TITLE
`axis.setCompare('none')` throws an error when `dataGrouping` enabled

### ISSUE THREAD

**Issue by jszuminski** [highcharts/highcharts#19001]
#### Actual behaviour
When the `dataGrouping` is enabled, `yAxis.setCompare('none')` throws an error and the series disappears.

#### Expected behavior
`yAxis.setCompare('none')` should not throw an error when the `dataGrouping: enabled` and the series should not disappear.

#### Live demo with steps to reproduce
**Demo:** https://jsfiddle.net/BlackLabel/qjrmaLt9/
Step 1: Open the console
Step 2: Click the button under the chart
The error should appear.

#### Product version
Highcharts 11

**Comment by AmoghAnantha** [comment]
Hi Jakub Szuminski
#19001
Solution: By directly setting the **compare: 'none'** in the series configuration should do the trick,
https://jsfiddle.net/ncvx8rsf/3/


Reference:
compare: stringSince 1.0.1
Compare the values of the series against the first non-null, non- zero value in the visible range. The y axis will show percentage or absolute change depending on whether compare is set to "percent" or "value". When this is applied to multiple series, it allows comparing the development of the series against each other. Adds a change field to every point object.

Defaults to undefined.
Try it
[Percent](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/series-compare-percent/)
[Value](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/series-compare-value/)
