### ISSUE TITLE
[width] how to fill full width of charts

### ISSUE THREAD

**Issue by synasapmob** [highcharts/highcharts#19010]
#### Expected behaviour
I tried to make everything but resulting doesn't expect
my question is how do I fill the entire width of the chart area?? 

#### Live demo with steps to reproduce
![Screen Shot 2023-05-17 at 15 43 58](https://github.com/highcharts/highcharts/assets/42969529/ce1d9825-e1a0-4a3b-98bf-c24babae4ff2)

**Comment by bm64** [comment]
Hello @synasapmob and thanks for contacting us.

Please recreate your chart in this demo and provide me with the link: https://jsfiddle.net/BlackLabel/u3vfpzdo/

**Comment by PeterM0101** [comment]
I tried to make fill full width of charts but failed. I have to do this one
![image](https://github.com/highcharts/highcharts/assets/103896190/4053631b-0e0c-4227-a890-fb5ffb7fac00)
But I did this one.
![image](https://github.com/highcharts/highcharts/assets/103896190/e6e38891-f770-4fdf-bb88-87f183a8d300)
How to make fill the entire width of the chart area?

**Comment by pawellysy** [comment]
Hey @synasapmob, @PeterM0101, thanks for reaching out to us. We treat GitHub as a bug/feature tracking tool, and your issues are neither. Please, reach out to us via [our available support channels](https://www.highcharts.com/blog/support/) Where our support engineers will help you to tweak your chart's configuration to better suit your needs. Thanks for the understanding!
