### ISSUE TITLE
Failed to parse source map - export-data module in Highcharts v11

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#19016]
#### Expected behaviour
Compilation without warnings as with Highcharts v10

#### Actual behaviour
6 similar warnings during compilation:

> **WARNING** in ./node_modules/highcharts/modules/export-data.js
> Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
> **Failed** to parse source map from '/.../my-app/node_modules/highcharts/modules/ [synthetic:util/polyfill] ' file: **Error**: ENOENT: no such file or directory, open '/.../my-app/node_modules/highcharts/modules/ [synthetic:util/polyfill] '

#### Live demo with steps to reproduce
1. Download and unpack project: [my-app.zip](https://github.com/highcharts/highcharts/files/11500154/my-app.zip)
2. Run `npm install`
3. Run `npm start`

#### Product version
Highcharts v11 only

#### Affected browser(s)
All

**Original issue:** https://github.com/highcharts/highcharts-react/issues/405
___
_Internal notes:_
The problem is probably caused by the below wrong `sources` definition.

Source map for export-data module in Highcharts v11:

```
{
  "version": 3,
  "file": "export-data.js.map",
  "lineCount": 39,
  "mappings": "A;;;;;;;;;aAuBA,IAAI, ...;",
  "sources": [" [synthetic:base] ", " [synthetic:util/defines] ", " [synthetic:util/defineproperty] ", " [synthetic:util/global] ", " [synthetic:util/polyfill] ", " [synthetic:es6/array/includes] ", "export-data.src.js"],
  "names": ["factory", "module", ...]
}
```

Source map for export-data module in Highcharts v10:
```
{
  "version": 3,
  "file": "export-data.js.map",
  "lineCount": 34,
  "mappings": "A;;;;;;;;;AASC,SAAS,...;",
  "sources": ["export-data.src.js"],
  "names": ["factory", "module", ...]
}
```

FYI @bre1470

**Comment by bre1470** [comment]
ES5 has the same issue. I will added it to the backlog, maybe someone finds the trigger for it.
