### ISSUE TITLE
Duplicated property "area"

### ISSUE THREAD

**Issue by clarghi** [highcharts/highcharts#19012]
#### Expected behaviour
I need that the src.js file could be minified because in my project all is minified and cannot actually add exceptions to this logic.
I have resolved replacing the deconstructing syntax with:
> const AreaSeries=SeriesRegistry.seriesTypes.area;
   const areaProto=SeriesRegistry.seriesTypes.area.prototype;

N.b. all minifications are in strict mode, I see that HC is not in strict mode. I use NUglify (latest version).

#### Actual behaviour
In Highcharts.src.js (the same in the compressed file) I see:

>  const { area: AreaSeries, area: { prototype: areaProto } } = SeriesRegistry.seriesTypes;

When in our project we bundle the file, error "duplicate property name: area".

#### Product version
11.0.1.
#### Affected browser(s)
Chrome

**Comment by pawellysy** [comment]
Hi @clarghi Thanks for reporting this issue! 

The destructuration of the variables works correctly. Take a look at this snippet: https://jsfiddle.net/BlackLabel/5vqhnwmg/1/

The reason it used to work in v10 is that we changed target version of the compiler to es6, which uses some new features in the compiled version, like destructuration, optional chaining, classes etc. 
In my opinion this is not the issue with Highcharts, I'd take a look into the minifier that you use to investigate the issue there. 

FYI @bre1470, @TorsteinHonsi. Do you guys think we should investigate this issue further?

**Comment by TorsteinHonsi** [comment]
> Do you guys think we should investigate this issue further?
@pawellysy Maybe you could take a look into the dupclicated property `area`? That looks a bit strange. But if the minifier simply doesn't support object destructuring, then we should't change anything.

### Workaround
@clarghi If the minifier doesn't support object destructuring, you can replace the Highcharts files with those loaded from the `/es5` folder. See https://www.highcharts.com/blog/post/still-supporting-ie11-action-required/

**Comment by clarghi** [comment]
NUglify supports object destructuring, but seems not with duplicated name or with assignment of a default value, e.g. 
> const { x=0, width=0 }=shapeArgs;
