### ISSUE TITLE
Highcharts v11 redraw twice (strange flickering)

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#19027]
Environment;
windows 11
angular-highcharts: 3.1.2
highcharts: 11.0.1
chrome: 113.0.5672.127

from version 11.0.0 all graphs are drawn twice
the first time only 5% of the graph is drawn, and the second time completely
like some kind of a flickering

regression: this worked correctly in version 10.3.3
tested with ms-edge and chrome browsers

maybe it's a bug in the wrapper, but as i mentioned it, works ok with 10.3.3. and latest angular wrapper

NOTE:
**if the dev console (F12) is open in the browser, then there is no flickering**

**Comment by karolkolodziej** [comment]
Hi @dick2tick!

I've tried to recreate your issue but without success, could you please edit one of the demos so the issue is visible?
As you can see only one `load` and one `render` is logged to the console.

Demo with `highcharts-angular`- https://stackblitz.com/edit/highcharts-angular-line-qri7ju
Demo in JS - https://jsfiddle.net/BlackLabel/hjb8nL3w/

**Comment by dick2tick** [comment]
try frame by frame (beginning of the video below) and you will see that the graph is drawn twice

https://github.com/highcharts/highcharts/assets/130139273/2bfea6b1-5ea0-425a-8418-b1ec3daa02c3

with v10.3.3 and the same code, the chart is drawn only once

**Comment by karolkolodziej** [comment]
I still can't see that. Could you please share your config so I can investigate it on my own?

**Comment by fordenes-praxis** [comment]
Hi guys,

I have the same problem when i upgrade from 10.3.3 to 11.
In my case i have a bar chart with a load event that change the height of the chart. Without this event, the animation shows correctly.

Here is the chart in 10.3.3. The animation shows in a single movement:
https://jsfiddle.net/eqkz4u30/1/

Here is the same chart in 11.0.1. At the beginning there is an intent of draw the chart and after milliseconds its start again:
https://jsfiddle.net/xuq2oc3a/3/

**Comment by TorsteinHonsi** [comment]
Thanks @fordenes-praxis , I can verify this. @karolkolodziej can you bisect it to a particular commit?

**Comment by TorsteinHonsi** [comment]
PS: I was about to suggest using the `static-scale.js` module to achieve the wanted result, but it actually suffers from the same issue: https://jsfiddle.net/highcharts/uf6oL52s/1/

**Comment by karolkolodziej** [comment]
@TorsteinHonsi bisected to: https://github.com/highcharts/highcharts/commit/6413d623868da59f57d4d9c82d5fa246a47f3c9e
