### ISSUE TITLE
(Enhancement) Please add source maps for minified code

### ISSUE THREAD

**Issue by kenaniah** [highcharts/highcharts#1902]
http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/ gives a quick overview for the uninitiated. 

Essentially, usage of source maps should aid in the debugging efforts of production code as one would no longer have to switch back to highcharts.src.js just to track down errors.

**Comment by dspnorman** [comment]
I'd like to add my support for this enhancement. Given that the issue has been open for nearly two years, I'm not optimistic, but hey, maybe it just got lost in the shuffle?

Auto generating a sourcemap for the minified code should be as simple as passing a flag to Closure Compiler...

**Comment by highslide-software** [comment]
To add it to code.highcharts.com and our zip packages we should
* Pass the flag to Closure Compiler in the [`compile` target](https://github.com/highslide-software/highcharts.com/blob/v4.0.4/build.xml#L614).
* For that we would need names for the map files, added in the [`minify` target](https://github.com/highslide-software/highcharts.com/blob/v4.0.4/build.xml#L652).
* In the [`dist` target](https://github.com/highslide-software/highcharts.com/blob/v4.1.4/build.xml#L903), copy the files over to distribution folders.

**Comment by Tomcat-Engineering** [comment]
+1

**Comment by jasonadt** [comment]
+1

**Comment by TorsteinHonsi** [comment]
We are working on this, in fact we are already uploading the maps to code.highcharts.com (http://code.highcharts.com/highcharts.js.map). What's left is to add the reference to the map from the minified files.

**Comment by e-cloud** [comment]
sourcemap is still unavailable now. no reference added to the minified files.

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard What's the status?

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard Anything new?

**Comment by scott-ho** [comment]
It's a 5.5 years issue. And no fix available. Does highcharts team take this seriously? For commercial users, that's really bad experience.

**Comment by scott-ho** [comment]
Thanks anyway.
