### ISSUE TITLE
Treegraph chart does not fill entire width when a few nodes are collapsed

### ISSUE THREAD

**Issue by Ritesh717** [highcharts/highcharts#19038]
When I create a tree graph with collapsed nodes, the chart does not occupy the full width of the container. This is because the chart is still taking up space for the collapsed nodes.

#### Expected behaviour
When a few nodes in a tree graph are collapsed, the chart should fill the full width of the container. If a user expands a collapsed node, the chart should scroll to the right to make room for the expanded node.

#### Actual behaviour
When a few nodes in a tree graph are collapsed, the chart does not fill the full width of the container.

#### Live demo with steps to reproduce

https://jsfiddle.net/riteshGangam/fe6sL5bq/
https://jsfiddle.net/riteshGangam/pez5du3L/35/

Without Collapsable nodes
<img width="960" alt="image" src="https://github.com/highcharts/highcharts/assets/40355220/2609dc7e-1ebe-4115-a79f-62d987ab8e12">

With collapsable nodes
<img width="959" alt="image" src="https://github.com/highcharts/highcharts/assets/40355220/778eae11-fc0d-4672-bbf7-63ebb99c8125">

#### Product version

Highcharts JS v11.0.1 (2023-05-08)
#### Affected browser(s)
Chrome

**Comment by pawellysy** [comment]
Hi @Ritesh717, thanks for your suggestion. This behaviour is working according to the design, but we might want to add some property, which will allow to do what you want to achieve 👍

**Comment by pawellysy** [comment]
Here is the workaround: https://jsfiddle.net/BlackLabel/h42f9rzg/

**Comment by Ritesh717** [comment]
Hi @pawellysy 

Thanks for the workaround you provided to fix the issue of rendering the chart with nodes collapsed. However, expanding the collapsed nodes makes it difficult to read the data. 
Is there a workaround to add a scroll option?
https://jsfiddle.net/riteshGangam/fshjxynu/1/
