### ISSUE TITLE
TS types are not compatible with exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by bensaufley** [highcharts/highcharts#19033]
This is somewhere between a feature request and a bug: it doesn't work, but `exactOptionalPropertyTypes` is a new-_ish_ flag and I know it would take some time to implement. But I definitely think there's an argument that in a scenario like the one described here, `undefined` isn't just the _absence_ of a value, it is a very specific value (in this case, creating a "disabled" state) and should be enumerated as a possible value of the property.

#### Expected behaviour

Passing a value of `undefined` to something like [`PlotColumnOptions.stacking`](https://api.highcharts.com/highcharts/plotOptions.column.stacking), which is explicitly allowed by the comment documenting the property, and is in fact the only way to achieve certain results, is accepted by TypeScript when `exactOptionalPropertyTypes` is set to true in `tsconfig.json`. Although `undefined` is the default here, `Highcharts.merge` may be used to override a non-`undefined` value back to `undefined`.

#### Actual behaviour

TypeScript rejects the value because the property is defined as optional with only a value of `OptionsStackingValue`, which means that _if a value is passed_, it must be of type `OptionsStackingValue`, but in this scenario, setting `undefined` is not a "no preference" value, it is to disable stacking, as the documentation states:

> Possible values are `undefined` to disable, `"normal"` to stack by value or `"percent"`.

#### Live demo with steps to reproduce

Look at `src/main.ts` in [this CodeSandbox](https://codesandbox.io/s/laughing-currying-679n3j?file=/src/main.ts) for TS violations

#### Product version
10.3+ (including 11, but CodeSandbox does not provide that option)

#### Affected browser(s)

none—this is TS-specific

**Comment by karolkolodziej** [comment]
@bre1470 any thoughts?

**Comment by bensaufley** [comment]
I know this obviously got stale but it seems pretty easy to resolve and IMO worth doing, especially now that `exactOptionalPropertyTypes` is not a new flag anymore.

**Comment by karolkolodziej** [comment]
Hi @bensaufley! 
Thank you for bringing our attention to this once again. 
Let me bring this to the team, and after a discussion, we'll try to address it.

**Comment by bre1470** [comment]
Hi! I like to add my opinion. An explicit `undefined` to all options will bloat the file size and the JetBrain software already struggles with our declarations. Optional in TypeScript implies `undefined` and using `undefined` as an option/value is bad design, `null` exists for that. In the mentioned use case though we made the mistake and I suggest to introduce `"disabled"` as a third default value there. Would that help?

**Comment by bensaufley** [comment]
I have some qualms with the first part of your response but they don't really matter because I agree with the latter: `undefined` as an option is probably not proper design and having a `"disabled"` default value would be both a clearer way to go, and circumvent the problem entirely. I suppose my only concern is: in how many other places does Highcharts do the same thing, and would the end result be something similar in size to just putting explicit `undefined` as an allowed value?
