### ISSUE TITLE
Download Image Problems in Force Directed Network Graph in Highcharts When enableSimulation is set to true

### ISSUE THREAD

**Issue by wangsl2018** [highcharts/highcharts#19054]
#### Expected behaviour

When enableSimulation is set to true（e.g. enableSimulation: true）, it is hoped that the image or document of  the Force Directed Network Graph can be  downloaded  normally.

`plotOptions: {
		networkgraph: {
			keys: ['from', 'to'],
			layoutAlgorithm: {
				enableSimulation: true
			}
		}
	}`

#### Actual behaviour

When I set enableSimulation to true and perform the Download operation(e.g. Download PNG image，Download JPG image，Download PDF document, Download SVG image), the downloaded image or file only contains nodes and connectors, but the text is lost.

#### Live demo with steps to reproduce
template: https://jshare.com.cn/demos/HIrD8k

#### Product version
Highcharts 11.0.1

#### Affected browser(s)
ALL

**Comment by karolkolodziej** [comment]
Hi, @wangsl2018!

You can simply disable the simulation for the export by adding the `chartOptions` -[demo](https://jsfiddle.net/BlackLabel/opkbqnxL/).
Read more in the [API documentation.](https://api.highcharts.com/highcharts/exporting.chartOptions)
