### ISSUE TITLE
Candlestick in the navigator is not displayed when points are given as objects

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1905]
Example: http://jsfiddle.net/jmfxz/

The data is not displayed as an area series in the navigator.

**Comment by steve-nD** [comment]
Two years and the problem is still not resolved?  I can confirm this problem still exist with both the Candlestick and OHLC charts.  Any ETA on a fix?

**Comment by TorsteinHonsi** [comment]
The commit above broke all OHLC and candlestick demos with array data.
