### ISSUE TITLE
highcharts.d.ts is not a module

### ISSUE THREAD

**Issue by kkesidis** [highcharts/highcharts#19063]
I upgraded Highcharts from version `10.3.2` to `11.0.1` and i have issues with typescript not recognizing the `highcharts.d.ts` as a module. I was able to reproduce this error on a newly created application, too

#### Expected behaviour
Being able to import the library on a typescript project
```ts
import Highcharts from 'highcharts'
import type {Chart, Options} from 'highcharts';
```

#### Actual behaviour
Getting an error
> File '<local path>/node_modules/highcharts/highcharts.d.ts' is not a module

I can still use the library, but typescript is not working

#### Live demo with steps to reproduce
[Github repository](https://github.com/kkesidis/highcharts-11-reproduction)

The above repository is a freshly created app using Vite and the vue-ts template

#### Product version
v11.0.x

#### Affected browser(s)
None

**Comment by karolkolodziej** [comment]
Hi @kkesidis,

In order to omit that error, You can import Highcharts from a master directory like:
```
import Highcharts from 'highcharts/es-modules/masters/highcharts.src'
```

@bre1470 any other insights?

**Comment by kkesidis** [comment]
Thank you, this works. Closing this issue, then
