### ISSUE TITLE
Error Initializing Treegraph Module in React App 

### ISSUE THREAD

**Issue by jmetzinger-edify** [highcharts/highcharts#19079]
My apologies if I'm just totally missing something and it's not actually a bug, but feel like there is not much else I can do when it comes to the importing here

#### Expected behaviour

Loading Tree Graph module and initializing should have no error. (screenshot for code)

![Screenshot 2023-06-01 at 1 49 26 PM](https://github.com/highcharts/highcharts/assets/126830762/8b8d9ddb-a2f6-4242-ae77-4cf88b69ced9)

#### Actual behaviour

Throwing an error with the message: 

![Screenshot 2023-06-01 at 1 31 06 PM](https://github.com/highcharts/highcharts/assets/126830762/9b521bf2-fc9d-42e1-acee-d437c696bf60)

I had also tried doing adding a script element importing it in the index.html and that was showing the error:

![Screenshot 2023-06-01 at 1 58 03 PM](https://github.com/highcharts/highcharts/assets/126830762/4a716849-f153-4288-9394-5584d70f6acf)

And the script element looked like so `<script src="https://code.highcharts.com/modules/treegraph.js"></script>`

#### Live demo with steps to reproduce
https://codesandbox.io/s/fancy-star-0m4jw4?file=/src/App.tsx

Just opening shows the error

#### Product version

Highcharts version 11.0.1
Highcharts React Official  3.1.0

#### Affected browser(s)

Have only tried on chrome Version 113.0.5672.126 (Official Build) (x86_64)

**Comment by bm64** [comment]
Hello @jmetzinger-edify and thanks for contacting us.

The `treegraph` series needs the `treemap` module to work properly. You've imported the module correctly, but it seems like the order of initialization might be wrong. Please check out this demo and let me know if it helps: https://codesandbox.io/s/late-browser-6t815t

**Comment by jmetzinger-edify** [comment]
@bm64 Ahh yes thank you that fixed it. Wow sorry I didn't realize the module was dependent on the treemap, I had thought like each module was it's own packaged that had everything it needed. 

Could it maybe worth looking into adding error messages more specific to this kind of issue like `treemap module init required for treegraph`? Not very important, but it's just the current error message doesn't really make me think about the treemap module (i see there's a couple references to treemap in the src code for treegraph though).  Not sure if other modules work the same as well. Would be glad to help add that if it's thought to be a good idea, thank you again!

**Comment by bm64** [comment]
@jmetzinger-edify sure, we will reconsider more specific error messages.

For future use, here are few tips that can be helpful with figuring out which module is missing:
- Look for errors in the console - in your provided demo you can see the [error 17](https://assets.highcharts.com/errors/17/?missingModuleFor=treegraph):
![image](https://github.com/highcharts/highcharts/assets/55414726/c2bf29d9-fffb-4ef8-9252-83b4c4dd21e2)
The error says which series type is missing modules
- Look for that specific series in our API to see what modules are required, for example: https://api.highcharts.com/highcharts/series.treegraph
- See our documentation: https://www.highcharts.com/docs/chart-and-series-types/treegraph-chart
