### ISSUE TITLE
Pie chart drilldown errors on V11

### ISSUE THREAD

**Issue by chrisjgilbert** [highcharts/highcharts#19075]
We have recently upgraded Highcharts from version 10 to 11 and observed an error being logged in the console when clicking to view drilldown data in a pie chart.

#### Expected behaviour
When clicking to view drilldown data in a pie chart, no errors are logged in the console.

#### Actual behaviour
When clicking to view drilldown data in a pie chart, the following error is logged in the console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'chart')
at c.select (highcharts-<fingerprint>.js:7904:19)
    at c.d (highcharts-<fingerprint>.js:7689:29)
    at e (highcharts-<fingerprint>.js:269:37)
    at c.firePointEvent (highcharts-<fingerprint>.js:7691:11)
    at F.onContainerClick (highcharts-<fingerprint>.js:8478:35)
```
Note: the error does not prevent the drilldown data from being viewed.

#### Live demo with steps to reproduce
https://jsfiddle.net/chrisgilbert/n3Lvy6pd/

#### Product version
Highcharts version 11

#### Affected browser(s)
Google Chrome Version 113.0.5672.126 (Official Build) (arm64)

**Comment by karolkolodziej** [comment]
Hi @chrisjgilbert!

As a workaround, you can disable the `allowPointSelect` -[demo](https://jsfiddle.net/BlackLabel/u0bj24p7/).

_Internal note:_
Unable to bisect but from what I can see it looks like it tries to set the state on the destroyed point.

**Comment by chrisjgilbert** [comment]
Thanks @karolkolodziej , I think that workaround will suffice for now
