### ISSUE TITLE
Datagrouping doesn't work.

### ISSUE THREAD

**Issue by aykutuz** [highcharts/highcharts#19092]
#### Expected behaviour
I expect the datagrouping work. 

#### Actual behaviour

Datagrouping doesn't work.

#### Live demo with steps to reproduce
<!DOCTYPE html>
<html>
<head>
    <title>Highcharts Data Grouping Example</title>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/data.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
</head>
<body>
    <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

    <script>
        // Generate a large number of data points
        function generateData() {
            var data = [],
                time = (new Date()).getTime(),
                i;

            for (i = -9999; i <= 0; i += 1) {
                data.push([
                    time + i * 1000,
                    Math.round(Math.random() * 100)
                ]);
            }
            return data;
        }

        Highcharts.chart('container', {
            chart: {
                zoomType: 'x'
            },
            title: {
                text: 'Data Grouping Example'
            },
            xAxis: {
                type: 'datetime'
            },
            yAxis: {
                title: {
                    text: 'Random Data'
                }
            },
            legend: {
                enabled: false
            },
            plotOptions: {
                area: {
                    marker: {
                        radius: 2
                    },
                    lineWidth: 1,
                    states: {
                        hover: {
                            lineWidth: 1
                        }
                    },
                    threshold: null
                },
                series: {
                    dataGrouping: {
                        enabled: true,
                        forced: true,
                        groupPixelWidth: 1000
                    }
                }
            },
            series: [{
                type: 'spline',
                name: 'Random data',
                data: generateData()
            }]
        });
    </script>
</body>
</html>

#### Product version
10.0

#### Affected browser(s)

Chrome

**Comment by bm64** [comment]
Hello @aykutuz and thanks for contacting us.

Data grouping feature is a part of Highcharts Stock. Try to import Highcharts stock and it should start working correctly:
`<script src="https://code.highcharts.com/stock/highstock.js"></script> `
Demo: https://jsfiddle.net/BlackLabel/h4yqurLe/
