### ISSUE TITLE
11.1.0 introduces bug in formatter, apostrophes escape input

### ISSUE THREAD

**Issue by kluvin** [highcharts/highcharts#19095]
#### Expected behaviour
`{value:%b '%y}` is equivalent to `{value:%b} '{value: %y}`

#### Actual behaviour
`{value:%b '%y}` is **not** equivalent to `{value:%b} '{value:%y}`

#### Live demo with steps to reproduce
https://jsfiddle.net/kluvin/xdpm3jnr/9/

#### Product version
introduced 11.1.0

#### Affected browser(s)
FF, probably all

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

However, I can't reproduce the issue. The only difference I see between the two expressions as that `{value:%b} '{value: %y}` renders a space between the apostrophe and the year, while `{value:%b '%y}` does not. Which is expected. This is how your fiddle looks to me:

<img width="214" alt="Skjermbilde 2023-06-06 kl  08 08 01" src="https://github.com/highcharts/highcharts/assets/227836/a930fd4d-7616-48d0-8092-5b53431d4b7b">

**Comment by kluvin** [comment]
Hi Torstein, sorry. I think I gave you the wrong Fiddle version, meaning I relied too much on autosave.

https://jsfiddle.net/kluvin/xdpm3jnr/9 produces the issue (also now referenced above)
