### ISSUE TITLE
Why the series of one state variable is getting other state variable value in highcharts

### ISSUE THREAD

**Issue by belt-basya** [highcharts/highcharts#19108]
Here, I have two state charts: Chart One and Chart Two. On the first click of the Chart One button, it renders the charts correctly. However, when I try to click on Chart Two, it doesn't work. Instead, the Chart Two series receives values from Chart One. How can I avoid this issue?

Thank you.

Codesandbox link: https://codesandbox.io/s/fast-microservice-f0clmh?file=/src/Example.tsx

If I use a direct constant variable instead of state, the error disappears. However, I need to use state. Can anyone help me solve this?

**Comment by bm64** [comment]
Hi @belt-basya 

I had to slightly modify your demo, because its original version would throw me some errors. After some adjustments everything seems to be working and the data looks correct too. Please try it and let me know if it works for you: https://codesandbox.io/s/fast-field-wddfrs

**Comment by Pradeep-upadhya** [comment]
Thank you so much for resolving this issue! Your assistance is greatly appreciated.
