### ISSUE TITLE
Mousewheel zoom module missing d.ts file

### ISSUE THREAD

**Issue by benelliott** [highcharts/highcharts#19103]
#### Expected behaviour

The mouse-wheel-zoom module should have a .d.ts type declaration file (like other modules) so that the module can be imported in TypeScript apps.

#### Actual behaviour

The file is missing.

#### Live demo with steps to reproduce

Try to import the module in a TypeScript app

#### Product version

11.1.0

#### Affected browser(s)

N/A

**Comment by karolkolodziej** [comment]
Hi @benelliott! 

You are right the `.d.ts` file is missing for that module- [demo](https://stackblitz.com/edit/highcharts-angular-line-qhbffa?file=src%2Fapp%2Fapp.component.ts). 
Thank you for reporting!

**Comment by aroylachance** [comment]
Where can we find the DTS file for the module? I have install the v11.1.0 of highcharts but I still can't found the mouse-wheel-zoom.d.ts file to import the module in my main.ts

**Comment by benelliott** [comment]
11.1.0 was released before this was fixed. There hasn't been a release including it yet.

**Comment by bhoomish-nbase2** [comment]
import MouseWheel from 'highcharts/modules/mouse-wheel-zoom';

MouseWheel(Highcharts)      --> In react JS

I got error : Uncaught TypeError: MouseWheel is not a function

can anyone help me?
