### ISSUE TITLE
TiledWebMap download PNG and JPEG don't work

### ISSUE THREAD

**Issue by mekhatria** [highcharts/highcharts#19106]
#### Expected behaviour
Getting a picture of the map

#### Actual behaviour
Blank pictures after download

#### Live demo with steps to reproduce

 [CodePen](https://www.highcharts.com/samples/maps/demo/twm-oslo-attractions?codepen)
#### Product version

HC v11.1

**Comment by karolkolodziej** [comment]
_Internal note:_
Only replicable when using **offline export**, without that works as expected- [demo](https://jsfiddle.net/BlackLabel/71td0kze/).
Fails on this if statement- `href` missing:
https://github.com/highcharts/highcharts/blob/0aafed9913777688e9bfbad249a625a0aca04227/ts/Extensions/OfflineExporting/OfflineExporting.ts#L809-L829

**Comment by TorsteinHonsi** [comment]
@karolkolodziej Actually I am not sure this is a bug. If I understand the [support table](https://www.highcharts.com/docs/export-module/client-side-export#browser-support-table) for offline-exporting correctly, exporting loading external images into the exported chart only works if the server is CORS-enabled. With the tiled web map, we don't have control over the where the tiles come from.

I think we should adress this issue by first verifying whether this is the case. Then decide what to do next. Why don't we get an error message? Why doesn't it fall back to the online export server?
