### ISSUE TITLE
Nodes in Sankey chart not connected properly when height is set too short and minLinkWidth is used

### ISSUE THREAD

**Issue by siropkin** [highcharts/highcharts#19110]
#### Expected behaviour
The Sankey chart should display all nodes and maintain proper connections between "to" nodes, regardless of the specified height and the use of minLinkWidth parameter.

#### Actual behaviour
When the height of the Sankey chart is set too short, and the minLinkWidth parameter is used, the connections between "to" nodes become disorganized and messy. Some connections may appear broken or not properly aligned.
![image](https://github.com/highcharts/highcharts/assets/39134915/9319d354-d4af-4106-aaee-51b741695584)

But if I will removeminLinkWidth  parameter or will increase chart height all nodes will work fine:
![image](https://github.com/highcharts/highcharts/assets/39134915/b7b58cad-fa2a-4189-b1d7-0e0dce3bcbcd)

#### Live demo with steps to reproduce
Please refer to the following Codepen for a live demo showcasing the bug: [Bug Demo](https://codepen.io/siropkin/pen/ZEmExyV)

Steps to reproduce:
1. Open the provided Codepen link.
2. Observe the default Sankey chart.
3. Modify the height parameter to a shorter value (e.g., decrease the value of chart: { height: ... }).
4. Set the minLinkWidth parameter to a non-zero value (e.g., modify the data array and add minLinkWidth property to some links).
5. Notice that the connections between "to" nodes are not properly aligned and may appear broken or disconnected.

#### Product version
Highcharts JS v11.1.0 (2023-06-05)

#### Affected browser(s)
Chrome Version 114.0.5735.110 (Official Build) (64-bit)

**Comment by bm64** [comment]
Hello @siropkin and thanks for reporting the issue.
