### ISSUE TITLE
The chartOptions for yAxis in responsive is unnormal

### ISSUE THREAD

**Issue by 839735495** [highcharts/highcharts#19113]
#### Expected behavior
The yAxis options should take effect for corresponding id and have no side effect for others.

#### Actual behavior
Seems the existing yAxis options are broken and the series also disappear.

#### Live demo with steps to reproduce
http://jsfiddle.net/Lkxt91be/1/
**This issue was found in 9.3.3 version. However, it works as expected in 5.0.0 version. It could be easily verified by replace the script resource from 9.3.3 to 5.0.0 (Uncomment the first line and comment the second line in live demo)**

#### Product version
9.3.3

#### Affected browser(s)
Microsoft Edge
Version 114.0.1823.37 (Official build) (64-bit)

**Comment by TorsteinHonsi** [comment]
Thanks for posting!

I am not sure it's a bug. Responsive options for collections (series and axes) are handled by [chart.update](https://api.highcharts.com/class-reference/Highcharts.Chart#update) with the `oneToOne` flag set to true. That means that "If the series have id's, the new series options will be matched by id, and the remaining ones removed.". Which in this case leads to the first y-axis, the one that holds the data series, is removed. 

The cure for that is to make sure you have two axis configurations in the responsive settings: https://jsfiddle.net/highcharts/fpm5x3gr/

**Comment by TorsteinHonsi** [comment]
@839735495 To understand more of this, I bisected the change back to https://github.com/highcharts/highcharts/commit/297dcc21fa7211d63c56c8c9c5ee9bdacdbc6d3c . It was first published in v7.1.2. With the change, the responsive logic calls `chart.update` with the `oneToOne` option enabled.

> How can I do that?

As shown yesterday, you provide an empty object for the first axis, the one you don't want to change: https://jsfiddle.net/highcharts/egm5Ljvn/

> Why the behaviors are inconsistent between using chart.update() and responsive chartOptions

But it's not inconsistent... Responsive chart options is consistent to calling `chart.update()` with the `oneToOne` parameter set to true: https://jsfiddle.net/highcharts/3u86whx2/

As a little background for the rationale on this change in v7.1.2. If responsiveness didn't use `oneToOne`, we would not be able to remove axes and series in responsive rules, only to modify or add them. With the current functionality, we can do the full lifecycle - create, update and delete.

**Comment by TorsteinHonsi** [comment]
>  In this way, consumer can choose whether to do the full lifecycle change or just want to update part of settings by using the responsive rules. Maybe it will be better?

Maybe, but I don't quite understand the benefit. With the current functionality, you also just update _part of the settings_ by responsive rules. The point is you need to `yAxis` array to match the main options, and you do that by adding an empty `{}` configuration for the first axis. Even simpler, you don't need id's at all, just make sure the responsive rule has the same number of axis configurations as the main option, so that they are reflected one to one. If an axis should not change, pass `{}`.

**Comment by TorsteinHonsi** [comment]
@839735495 Just to clarify, the responsive options are additive, which means they are dynamically _extending_ the basic options. Your use case seems to be that you have two axes where the second one only changes the title. But unless there is more to it, this is not necessary. You can have a complex configuration for your axis, then only change the title responsively. The other options will persist: https://jsfiddle.net/highcharts/a5e1jrpz/

**Comment by 839735495** [comment]
@TorsteinHonsi 
Do you know why it will cause error just like this? https://jsfiddle.net/0xay9k7s/

**Comment by TorsteinHonsi** [comment]
So `yAxis[0].tickPositions` is not set. It's probably about the timing of the callback. The responsive condition is handled before the layout is decided and tick positions are created. So you should use some other test (like the chart dimensions) to decide what title to use.

**Comment by 839735495** [comment]
@TorsteinHonsi 
In fact, the title I want to display is similar to "KB/MB/GB", depending on the ticks interval on the yAxis. If it is greater than 1K, it will be displayed as K. If it is greater than 1M, it will be displayed as M, and so on. And I use the max ticks value to divide the ticks length to get the interval.

Is there a way to achieve this in responsive?

**Comment by TorsteinHonsi** [comment]
Istead of using the responsive functionality I would add a chart render event, and update the y axis title if necessary.

**Comment by 839735495** [comment]
Got it, thanks you so much. I think we can close this issue

**Comment by TorsteinHonsi** [comment]
You're welcome :)
