### ISSUE TITLE
IE8 - pie chart exporting to PDF / gray theme

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1912]
It looks like a problem with exporing pie chart (including theme i.e gray) to PDF. 

IE 8.0.6001.18702

http://postimg.org/image/fialzljhz/606a2466/

**Comment by jon-a-nygaard** [comment]
Closing this issue due to: We are not able to reproduce it.
Should anyone have further information on this issue, please add a comment and reopen.
