### ISSUE TITLE
Bar chart with scrollablePlotArea has incorrect tooltip positioning

### ISSUE THREAD

**Issue by fidian** [highcharts/highcharts#19129]
#### Expected behaviour

Tooltips should point at the bar.

![image](https://github.com/highcharts/highcharts/assets/428348/ace0163f-68dd-490b-be2f-cf12aeede9dd)

#### Actual behaviour

Tooltip is not pointing at the bar for bars below the first viewable area.

![image](https://github.com/highcharts/highcharts/assets/428348/25c4796a-eef6-4eb9-84f9-b1ce7ee2018d)

#### Live demo with steps to reproduce

https://jsfiddle.net/9m4v3jq8/2/

Check tooltips and they work. Scroll down and tooltips beyond the visible area will be incorrect.

I believe this is because `getPlayingField()` is using only `chart.chartHeight` but should be `Math.max(chart.chartHeight, chart.plotBox.height)` or something similar.

#### Product version

Highcharts 11.1.0

#### Affected browser(s)

Chrome

**Comment by karolkolodziej** [comment]
Hi @fidian and thank you for reporting the issue!

As you can see in the [API documentation](https://api.highcharts.com/highcharts/tooltip.outside) the tooltip `outside` property needs to be set to true for the `scrollablePlotArea`.

If you set this to true or remove it, everything works as expected- [demo](https://jsfiddle.net/BlackLabel/kvw02q6p/).

**Comment by karolkolodziej** [comment]
You are actually right! We can investigate that and treat it as an enhancement 😄
