### ISSUE TITLE
centerInCategory is not working with columnpyramid type

### ISSUE THREAD

**Issue by vegaelce** [highcharts/highcharts#19127]
#### Expected behaviour

I have a chart of type colmn with null values and centerInCategory set as true.
The series are correctly centered in each category.
Changing the type of chart to columnpyramid should render the same feature.

#### Actual behaviour
When I change the type to columnpyramid, the series are not centered in the categories.

#### Live demo with steps to reproduce
https://jsfiddle.net/vegaelce/k5sLzqvu/

Click on the "Change type" button to change the type of the chart and see the result.

#### Product version
Tried with Highcharts 9.3 -> 11.1

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
Hi @vegaelce and thank you for reporting!

Internal note:
In the `columnpyramid ` the `barX` property is calculated 
https://github.com/highcharts/highcharts/blob/e9ae7f54ddf1d10c992cec7f217c6a64debf8ca9/ts/Series/ColumnPyramid/ColumnPyramidSeries.ts#L151

while the `column` series handles the `centerInCategory` property
https://github.com/highcharts/highcharts/blob/e9ae7f54ddf1d10c992cec7f217c6a64debf8ca9/ts/Series/Column/ColumnSeries.ts#L584-L590
