### ISSUE TITLE
Bar chart with scollablePlotArea has scrollbar underlay the axis label.

### ISSUE THREAD

**Issue by fidian** [highcharts/highcharts#19128]
#### Expected behaviour

The scrollbar should not be obscured.

#### Actual behaviour

Scrollbar is obscured.

#### Live demo with steps to reproduce

https://jsfiddle.net/9m4v3jq8/2/

Scroll to bottom and look at scrollbar shuttle.

![image](https://github.com/highcharts/highcharts/assets/428348/7dc94f5a-0832-48ad-a944-471b27f98548)

#### Product version

Highcharts 11.1.0

#### Affected browser(s)

Chrome

**Comment by bm64** [comment]
@fidian thanks for reporting the issue
