### ISSUE TITLE
Inaccuracy in TypeScript type defs for `PointDropEventObject` from the draggable points module

### ISSUE THREAD

**Issue by srmagura** [highcharts/highcharts#19135]
My [jsfiddle](https://jsfiddle.net/ogha2pet/) enables the draggable points module and logs the `drop` event when a point is dropped.

When a point is dropped, the `newPoint` property of the event looks like this:

```js
newPoint: {
  y: 2.1317365269459887
}
```

#### Expected behaviour

The TypeScript interface for `PointDropEventObject` should match the value at runtime, as shown above.

#### Actual behaviour

The TypeScript interface for `PointDropEventObject` says `newPoint` has type `PointDragDropObject`. This is incorrect because `PointDragDropObject` does not have a property called `y`.

#### Live demo with steps to reproduce

https://jsfiddle.net/ogha2pet/

#### Product version

Highcharts 11.1.0

#### Affected browser(s)

All. Tested in Chrome.

**Comment by karolkolodziej** [comment]
Hi @srmagura!

You are right the `PointDragDropObject` interface might be improved.

In the meantime, you can use the `target` which effectively is just a `Point`. 
There you can access more properties- [demo](https://jsfiddle.net/BlackLabel/o4g7mxpf/).
