### ISSUE TITLE
Series color changes on drillup when colorByPoint is false

### ISSUE THREAD

**Issue by jonathandixon** [highcharts/highcharts#19134]
#### Expected behaviour
When returning to the top level series after drilldown the color of the top level series should be the same as the initial color.

#### Actual behaviour
When returning to the top level series after drilldown the color of the top level series cycles to the next color. This occurs when the `colorByPoint` option is not set or `false`.

#### Live demo with steps to reproduce
https://jsfiddle.net/cxywousb/

#### Product version
Highcharts 11.1.0

#### Affected browser(s)
Chrome, Firefox, Safari

**Comment by bm64** [comment]
Hello @jonathandixon and thanks for reporting the issue.

Seems to work correctly in v11.0.1: https://jsfiddle.net/BlackLabel/e1dLfcar/

_Internal note:_
Bisected to 003fc2014abd62d55df115ac82feb21ed40c85fd
