### ISSUE TITLE
Treegraph link label displaying incorrectly when chart inverted

### ISSUE THREAD

**Issue by jakubjanuchta** [highcharts/highcharts#19139]
#### Expected behaviour
Link labels should be positioned on the links when chart is inverted.

#### Actual behaviour
Link labels are mispositioned when the chart is inverted.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/mc63ebh7/

#### Product version
Highcharts v11.1.0

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
I think we already have an issue for this. It is not only treegraph, it also applies to inverted org charts and I believe sankey.
