### ISSUE TITLE
Packed bubble chart legends name inconsistent in different highchart version (HC v10.2, HC v11)

### ISSUE THREAD

**Issue by fariaNawrine** [highcharts/highcharts#19143]
#### Expected behaviour
 in version HighChart v11 with same dataset used in HighChart v10.2 and same everything legends should show with proper name.

#### Actual behaviour
In version HighChart v10.2 its showing legends with proper name, but in version HighChart v11 with same dataset and same everything but legends are showing with default name.

#### Live demo with steps to reproduce
 HC v10.2: https://jsfiddle.net/gvo3sy2a/1/ 
 HC v11: https://jsfiddle.net/gvo3sy2a/

#### Product version
Highcharts 11

#### Affected browser(s)
Chrome, Firefox

**Comment by karolkolodziej** [comment]
Hi @fariaNawrine! Thank you for reporting!

Bisected to: https://github.com/highcharts/highcharts/commit/4999b8a3ac5b55b27412f6f5a22779a71f249285 FYI @hubertkozik
