### ISSUE TITLE
stickyTracing doesn't work well when combining line and column chart

### ISSUE THREAD

**Issue by adityapachpor978478** [highcharts/highcharts#19158]
I'm trying to add a line series in column chart, 
Even though stickyTracing is set as false, tooltip can be seen for line points when mouse enter chart area anywhere.

Expected behavior:  tooltip for column should follow cursor (current behavior), tooltip for line series should be shown only when cursor is near that point.

demo URL : https://stackblitz.com/edit/angular-d3-line-chart-demo-wvkasw?file=src%2Fapp%2Fcomponents%2Fbubble-chart%2Fbubble-chart.component.ts

**Comment by karolkolodziej** [comment]
Hi @adityapachpor978478.

As you can see in [the API docs](https://api.highcharts.com/highcharts/series.line.stickyTracking), the `stickyTracking` property is available on the series and there needs to be declared.

If you change that everything works as expected- [demo](https://stackblitz.com/edit/angular-d3-line-chart-demo-9418ze?file=src%2Fapp%2Fcomponents%2Fbubble-chart%2Fbubble-chart.component.ts),[ simplified demo](https://jsfiddle.net/BlackLabel/3zL4pef2/).
