### ISSUE TITLE
After dragging plotline how to get data of data point

### ISSUE THREAD

**Issue by rahulbadekarr** [highcharts/highcharts#19151]
Hi Team,

I am looking for Below points:

#### Can we use stock chart and implement

Demo Link : https://jsfiddle.net/BlackLabel/8t46bo75
![MicrosoftTeams-image (3)](https://github.com/highcharts/highcharts/assets/91235653/5fd3592d-643c-44a3-95fd-cb8ae4e00e01)

#### Live demo with steps to reproduce

It will be very helpful if you can help me here

Thanks

**Comment by kamil-musialowski** [comment]
Hello Rahul, we use GitHub as an bug/feature requests tracking solution only. Support questions are handled through our official support channels, which can be found here: https://www.highcharts.com/blog/support/

I have seen your message and already replied to it with a solution, therefore please do not duplicate topics across our channels as it slows down our work as we go through each ticket on every support channel one by one.

**Comment by rahulbadekarr** [comment]
sure thanks
