### ISSUE TITLE
Timeline chart points default at y: 1 even when explicitly stating y value in series data

### ISSUE THREAD

**Issue by elliot-pi** [highcharts/highcharts#19162]
#### Expected behaviour
Timeline chart points should be defaulted to y: 0 
Timeline chart points should respect the y value in the initial data series

This is especially an issue when combining charts e.g. line chart with timeline chart

#### Actual behaviour
Timeline chart data defaults to to y: 1 even when explicitly stating y: 0 in the data series

After updating the chart using chart.update({series: ...}) the stated y value is respected

![image](https://github.com/highcharts/highcharts/assets/60388605/5e64ffbc-be8f-444f-b3d6-c149fff551a1)

#### Live demo with steps to reproduce
Chart below shows the issue - I've left a commented out example of the update function 'fixing' the issue
https://jsfiddle.net/jso2nwea/40/

Highcharts ver: v11.1.0

**Comment by karolkolodziej** [comment]
Hi @elliot-pi! 
As you can see in [the API documentation for the timeline series](https://api.highcharts.com/highcharts/series.timeline.data), the `data` object doesn't allow to modify the `y` value of the series.  It was by design that it should stay in one place. 

But maybe I'm missing something and there is a case where it might be useful, could you please describe if there is such a case?

**Comment by elliot-pi** [comment]
Thanks for the response!

I got the idea of being able to edit the y value from the [docs](https://www.highcharts.com/docs/chart-and-series-types/timeline-series#other-configuring-options) -  "using the point properties, color, x, y"

Also as per the initial question's chart example, do you think its inconsistent to have the timeline point y value not set on initial load, but after using chart.update() with a timeline point y value it will be respected?

As for the use case: we're trying to combine a series chart with the timeline chart, in this case a line chart with the timeline chart and would like the events to sit along the x-axis 

https://jsfiddle.net/gnejzys4/6/ - you can see at the moment the event point sits awkwardly in the middle of the data

**Comment by karolkolodziej** [comment]
I apologise for the confusion, but the docs, in this case, are not accurate the `y` is explicitly removed from the API and there is no code to handle this property.
When it comes to the `update` you found a glitch and that is not how it should work.

Now I get what you are dealing with, have you tried annotating the chart as described in [API](https://api.highcharts.com/highcharts/annotations), please also see [the demo.](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/annotations/)

_Internal note:_
- remove `y` from the timeline documentation
- fix the demo at the end of the page

**Comment by elliot-pi** [comment]
Annotations don't really fit my use case, sorry, we're really looking to be able to have markers on the chart and click events on the x-axis 

For now I can work around it and use a Line chart series with the line disabled, but I still think it's probably worthwhile to allow the explicit changes to the `y` value on timeline points - at the moment timeline chart combined with any other chart is unusable

For instance: What happens if someone wants a[ timeline chart like this ](https://www.highcharts.com/docs/chart-and-series-types/timeline-series#alternate-labels) underneath their other date/time type chart. It would sit awkwardly at `y: 1` blocking other chart data

**Comment by karolkolodziej** [comment]
@elliot-pi I think there was no plan to use that series with any other at the same time thus we decided to set by default `y:1`.
