### ISSUE TITLE
Focus border persists even after chart loses focus

### ISSUE THREAD

**Issue by kycutler** [highcharts/highcharts#19169]
#### Expected behaviour

The focus border should disappear when the chart no longer has focus.

#### Actual behaviour

The focus border persists even when another element has focus:

![image](https://github.com/highcharts/highcharts/assets/67761731/adfc1222-a9c1-4507-87ba-a0486305446b)

#### Live demo with steps to reproduce
https://jsfiddle.net/onfe21zq/

- Click into the chart area and press Tab once to focus the first column
- Click into the input below the chart to focus that instead
- Notice that the focus border in the chart persists

#### Product version
11.1.0

#### Affected browser(s)
Edge (Chromium), haven't tested others

**Comment by karolkolodziej** [comment]
I am able to see that behaviour also on Chrome but only with the column.
When the focus is on the legend and I click the input it disappears.
