### ISSUE TITLE
Treegraph custom marker symbol error

### ISSUE THREAD

**Issue by KamilKubik** [highcharts/highcharts#19173]
#### Expected behaviour
Treegraph custom _url_ marker symbol should be properly rendered.

#### Actual behaviour
Treegraph custom _url_ marker symbol ends with a console error, the custom symbol is not rendered.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/jtv17zxu/

#### Product version
v11.1.0

**Comment by KamilKubik** [comment]
I also noticed there's a missing **marker** property on _levels_ in the API. Also, the **levels** property is defined as an object there instead of an array. In the official demo, the property is provided (level 6): https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/treegraph-chart.

**Comment by karolkolodziej** [comment]
Hi @KamilKubik!

1. You are right the custom marker was never implemented for the treegraph series but it is listed in the API.
2. The documentation for `level` is incorrectly added, needs to be an array of objects.
