### ISSUE TITLE
Unexpected behavior of annotation

### ISSUE THREAD

**Issue by adnanS2G** [highcharts/highcharts#19179]
The expected behavior should be for this annotation to remain within the plot area

When we add text annotation and drag it outside the chart and then it has been removed/Hide.

#### Live demo with steps to reproduce
(https://jsfiddle.net/BlackLabel/hmn3k12r/)

https://github.com/highcharts/highcharts/assets/135982085/a1a057b8-9d49-4656-a274-d41ff9449bc7

**Comment by karolkolodziej** [comment]
Hi @adnanS2G and thank you for reporting the issue.

Internal note:
It looks like the `if` condition linked below is falling.
https://github.com/highcharts/highcharts/blob/11fd752696aa8457a172a4e0e17b2235b95b4f6a/ts/Extensions/Annotations/EventEmitter.ts#L254-L262

This is only replicable to annotation added through GUI- [demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/annotations/gui/).
It also seems like a different `event` is passed to the `onDrag` method if the annotation is added through the code -[demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/annotations/defer/).

**Comment by adnanS2G** [comment]
Thanks, @karolkolodziej 
I feel happy to hear you guys found the issue.
can you please tell me when will this issue resolve?

**Comment by jakubSzuminski** [comment]
@adnanS2G, we're currently debugging this issue. I'll keep you posted.

**Comment by jakubSzuminski** [comment]
@adnanS2G, this behavior is caused by the `crop` property. 

Here's a **workaround:** https://jsfiddle.net/BlackLabel/127mr6hb/

Please try this out and let me know if everything works as expected.

**Comment by adnanS2G** [comment]
Thanks @jakubSzuminski ,
Without clipRect, this works fine for me as expected.

**Comment by adnanS2G** [comment]
Hi @jakubSzuminski 
I am facing another issue with the annotation.
Can you please check.
https://github.com/highcharts/highcharts/assets/135982085/790a61e5-26d2-4c63-9f17-6d54d62fb79b

**Comment by madepiet** [comment]
Hi @adnanS2G 
This looks like a separate issue that I reported here: https://github.com/highcharts/highcharts/issues/19505

@pawelfus, could you please confirm?

**Comment by pawelfus** [comment]
Confirmed @madepiet - added simplified demo in #19505
