### ISSUE TITLE
Regression: Zooming on map with selections causes selections to not show as selected

### ISSUE THREAD

**Issue by fidian** [highcharts/highcharts#19175]
#### Expected behaviour

Zooming on a map with selections will continue to highlight the selected areas on zoom. This is what was experienced with version 10.3.3.
![working-10 3 3](https://github.com/highcharts/highcharts/assets/428348/c1bef14d-c112-44ce-b1cd-1b58d7d5af8d)

Here I selected Minnesota. Next, I scrolled while on on Minnesota and South Dakota to show it working. The state stays selected, which you can see at the top of the screen capture.

#### Actual behaviour

When zooming or panning, the selected areas do not redraw correctly. When the mouse is over a selected area, that area is shown correctly. When the mouse is not, that area is drawn as though it is not selected. With with multiple selections active, only the one where the mouse is hovering will be drawn correctly.
![fail-11 0 0](https://github.com/highcharts/highcharts/assets/428348/f77cb75a-866b-4c97-baa1-83acd689bf39)

Same sort of scenario as above.

#### Live demo with steps to reproduce
https://jsfiddle.net/g3oj507x/

#### Product version
Working in Highcharts 10.3.3, failing in 11.0.0, 11.0.1, 11.1.0.

#### Affected browser(s)
Chrome.

**Comment by bm64** [comment]
Hello @fidian and thanks for reporting the issue.

_Internal note:_
Bisected to: 4d7ac17371ea3ff5f76efde6dd1a168e177b2a73 FYI @hubertkozik
