### ISSUE TITLE
Getting 2 line colours while using zones for the same X axis value.

### ISSUE THREAD

**Issue by SushanthPS** [highcharts/highcharts#19188]
#### Expected behaviour
Get a single colour instead of the line getting divided into 2 different colours

#### Actual behaviour
Line getting divided and having 2 colours.

#### Live demo with steps to reproduce

https://jsfiddle.net/g3v6ow10/18/

#### Product version

"highcharts": "^10.2.0",
"highcharts-react-official": "^3.1.0",

#### Affected browser(s)
All browsers

**Comment by bm64** [comment]
Hello @SushanthPS 

I have discussed the case with the team, and our conclusion is that this is intended and correct behaviour. This is especially visible when the line is even wider and illustrates set zones: https://jsfiddle.net/BlackLabel/s4th1mgo/

I'm closing the issue, but if there is anything you'd like to add, feel free to.
