### ISSUE TITLE
To add tooltip on Draggable plotline and time on rectangle/box

### ISSUE THREAD

**Issue by rahulbadekarr** [highcharts/highcharts#19192]
#### To add tooltip on Draggable plotline and time on rectangle/box
1) I am trying to add tooltip on this and to add date/time inside the svg
2) But when I drag the line time goes away and same can we do for tooltip

Can you please let me know

Link: [https://jsfiddle.net/7a4yew9h/1/](url)

**Comment by bm64** [comment]
Hello @rahulbadekarr 

We strictly use GitHub as a bug and feature tracker, and your ticket doesn't seem to fall under either of those categories. Please visit our [other support channels](https://www.highcharts.com/blog/support/) for assistance with implementation, for example: https://www.highcharts.com/forum/
