### ISSUE TITLE
pushUnique is not a function

### ISSUE THREAD

**Issue by ramihoudroge** [highcharts/highcharts#19199]
Hi!

I am running into two weird issues, interestingly enough this is not working only in production (it is working in my dev environment):

the highstock component not working
the exporting modules is not working
Both raise the same type of message:

```
TypeError: x.pushUnique is not a function
    at w.compose (exporting.31edbdb5.js:1:3704)
    at K.compose (exporting.31edbdb5.js:1:18605)
    at exporting.31edbdb5.js:1:19408
    at N (exporting.31edbdb5.js:1:572)
    at exporting.31edbdb5.js:1:19196
    at entry.bd4fb60f.js:12:311422
    at async Promise.all (/index 0)
    at async Proxy.mounted (entry.bd4fb60f.js:12:311506)

entry.fa511ed8.js:1 TypeError: G.pushUnique is not a function
    at k.compose (stock.5e135750.js:1:2854)
    at stock.5e135750.js:1:5793
    at _ (stock.5e135750.js:1:572)
    at stock.5e135750.js:1:5684
    at entry.fa511ed8.js:12:311422
    at async Promise.all (/index 0)
    at async Proxy.mounted (entry.fa511ed8.js:12:311506)
```

I found two other issues related to this, and both seem to point to cloudflare (https://github.com/highcharts/highcharts#18893 and https://github.com/highcharts/highcharts/issues/18902).

Would you happen to know how I can fix this ?

**Comment by TorsteinHonsi** [comment]
Hi @ramihoudroge 

This happens if you run v10 of `highcharts.js` with v11 of module files. In other words, it is likely a cache issue.

**Comment by ramihoudroge** [comment]
Thanks for taking the time to answer @TorsteinHonsi . Do you know how I can fix this ?

**Comment by TorsteinHonsi** [comment]
> I guess you meant v11 of highcharts with v10 of module files ? 

Actually not. This is how it looks: https://jsfiddle.net/highcharts/emq71dp4/

The reason for this depends on how your project is set up, you just need to make sure the files are loaded from the same version and that there is nothing left in old cache. My guess is that that your browser has cached the v10 version of Highcharts. So you should try to mitigate that by changing the file path or something.

**Comment by ramihoudroge** [comment]
Ok. Thanks for the example. For the browser issue, I tried the hard reload option of Chrome, I tried private windows, I tried other browsers, so I am not sure it is the browser cache (or I misunderstood and the actions I listed don't circumvent that issue). What do you mean by changing the filepath, which path exactly ?
Regarding my project setup, I am using Nuxt with highcharts and highchart-nuxt. I downgraded to highcharts 10.3.3 and the site loads properly, but I'd obviously like to jump onto the latest release :)

If it helps, here are exerpts from `package.json` and `nuxt.config.ts`.

```
"dependencies": {
    "@creativebulma/bulma-divider": "^1.1.0",
    "@creativebulma/bulma-tooltip": "^1.2.0",
    "@fortawesome/fontawesome-svg-core": "^6.4.0",
    "@fortawesome/free-brands-svg-icons": "^6.4.0",
    "@fortawesome/free-regular-svg-icons": "^6.4.0",
    "@fortawesome/free-solid-svg-icons": "^6.4.0",
    "@fortawesome/vue-fontawesome": "^3.0.3",
    "@pinia/nuxt": "^0.4.11",
    "bulma": "^0.9.4",
    "bulma-switch": "^2.0.4",
    "highcharts": "^10.3.3",
    "highcharts-vue": "^1.4.2",
    "luxon": "^3.3.0",
    "nuxt-highcharts": "^3.0.11",
    "pinia": "^2.1.4",
    "sass": "^1.63.4",
    "sass-loader": "^13.3.2",
    "tiny-emitter": "^2.1.0"
  },
```

```
  highcharts: {
    exporting: true
  },
  modules: [
    '@pinia/nuxt',
    'nuxt-highcharts'
  ],
```

**Comment by richardeschloss** [comment]
nuxt-highcharts is still on v10. I can consider upgrading to v11.

**Comment by ramihoudroge** [comment]
Thanks Richard, your update solves it! Ref: https://github.com/richardeschloss/nuxt-highcharts/discussions/67#discussioncomment-6275500
