### ISSUE TITLE
Datetime axis behaves badly when 'year 0' is on the axis.

### ISSUE THREAD

**Issue by mmcguinn** [highcharts/highcharts#1919]
I'll preface this by saying year zero doesn't actually exist, though that's not the issue I'm reporting here (and is probably a lot more difficult to fix cleanly).

There are two distinct behaviors that happen:
1. If year zero is on the axis and the axis goes up to at least 1900CE, 1900 is ALWAYS used as a tick regardless of the tickinterval. See http://jsfiddle.net/ESgSd/2/
2. If year zero is on the axis and the axis does not include 1900CE, the entire positive range of tick labels disappear. See http://jsfiddle.net/ESgSd/1/

I suspect the issue is due to how Date.UTC treats requests for year zero - which is to return 1900CE, causing the 'year zero' tick to get drawn as 1900.

**Comment by TorsteinHonsi** [comment]
Still valid in v6.1.0.

**Comment by fameriks** [comment]
@TorsteinHonsi our team recently has faced with this issue. We are considering to add some kind of override to this.Date so it sets full year as you mentioned but this is high risk change to our code. Could you please give latest update on this and tell some more details of potential timezone issues?
