### ISSUE TITLE
LegendItemClick event for item series

### ISSUE THREAD

**Issue by jakubjanuchta** [highcharts/highcharts#19202]
#### Expected behaviour
LegendItemClick event for item series responds on click, allows to perform any action e.g. `return false` to prevent the series hide/show.

#### Actual behaviour
LegendItemClick event for item series does not respond on click.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8zp50cyn/

#### Product version
Highcharts v11.1.0

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
@jakubjanuchta the `item` extends the `Pie` series where the `legendItemClick` is explicitly excluded.

IMO this should also be excluded from the `item` series.
