### ISSUE TITLE
Styles won't be applied to annotation label if useHTML is enabled

### ISSUE THREAD

**Issue by nlotz63** [highcharts/highcharts#19200]
#### Expected behaviour
With useHTML enabled for annotations, you should be able to apply styles to the annotation text. E.g., change the font size.

#### Actual behaviour
When useHTML is enabled, style properties are ignored. If it helps, this issue didn't exist in version 11.0.0

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/night50/nmxqszep/17/)

1. View the demo and note the size of the font is set to 28px and useHTML is false. 
2. Change useHTML to true and run.
3. Note the font is no longer rendered at 28px

#### Product version
Highcharts version 11.1.0 (the bug was not present in version 11.0.0)

#### Affected browser(s)
MS Edge, Chrome, and FireFox

**Comment by bm64** [comment]
Hello @nlotz63 and thanks for reporting the issue.

Looks like it was broken in v11.0.1. As a workaround you can set font-size using CSS: https://jsfiddle.net/BlackLabel/dt8wunag/

_Internal note:_
Bisected to 809fbbf37e321a63c73ae86e136774d056499400

**Comment by nlotz63** [comment]
Hi @bm64 , thanks for the workaround.

Noel
