### ISSUE TITLE
Cannot find module 'highcharts' or its corresponding type declarations. ts(2307)

### ISSUE THREAD

**Issue by LuckyWindsck** [highcharts/highcharts#19205]
#### Expected behaviour
Being able to find module 'highcharts' or its corresponding type declarations.

#### Actual behaviour
I used `create-vue` to create a `Vue3` project with `Vite` and `TypeScript` support.
When I try to import `highcharts` in a Vue [Single-File Components](https://vuejs.org/guide/scaling-up/sfc.html), VSCode shows me the following ts error:
> Cannot find module 'highcharts' or its corresponding type declarations. ts(2307)

#### Live demo with steps to reproduce
I made a [minimal reproducible example](https://github.com/LuckyWindsck/minimal-vue-typescript-highcharts/).

1. Clone the repository, install dependencies, and open VSCode
```sh
$ git clone https://github.com/LuckyWindsck/minimal-vue-typescript-highcharts.git
$ cd minimal-vue-typescript-highcharts
$ yarn install
$ code . # open with visual studio code
```
2. Open `src/App.vue` and hover your mouse pointer over the `'highcharts'` in `import highcharts from 'highcharts'`, then VSCode will show ts error.

![importing-highcharts-in-vue-sfc-shows-ts-error](https://github.com/highcharts/highcharts/assets/24631178/542536fd-f51a-4f1d-8618-fc9280005520)

Btw, there's no problem with other dependencies like `axios` in the minimal reproducible example.

![importing-axios-in-vue-sfc-shows-no-error](https://github.com/highcharts/highcharts/assets/24631178/89022e67-1a8b-47fa-a410-fecbadced186)

Also, this problem is only found in Vue SFC. I can import `highcharts` without any error in normal `.ts` file

![importing-highcharts-in-ts-file-shows-no-error](https://github.com/highcharts/highcharts/assets/24631178/beb28057-6c71-48fe-9457-2b7120aa217a)

##### Visual Studio Code
```sh
$ code --version
1.79.1
4cb974a7aed77a74c7813bdccd99ee0d04901215
x64
$ code --list-extensions --show-versions | grep Vue
Vue.volar@1.8.1
Vue.vscode-typescript-vue-plugin@1.8.2
```

##### Dependencies
```json
{
  "dependencies": {
    "axios": "^1.4.0",
    "highcharts": "11.1.0",
    "vue": "3.3.4"
  },
  "devDependencies": {
    "@vue/tsconfig": "0.4.0",
    "typescript": "5.0.4"
  }
}
```

#### Affected browser(s)
None

**Comment by LuckyWindsck** [comment]
Actually, I am not sure whether this is the right place to report this issue or not, but this problem is only found when I using `highcharts`.

Also, I just found a related issue (https://github.com/highcharts/highcharts/issues/19063).

According to https://github.com/highcharts/highcharts/issues/19063#issuecomment-1569647865 by @karolkolodziej, I can omit the error by:

> ```ts
> import Highcharts from 'highcharts/es-modules/masters/highcharts.src'
> ```

However, a new problem will appear as stated in https://github.com/highcharts/highcharts/issues/19063#issuecomment-1569835576.

> While the above solves the problem of (correctly) importing the entire Highcharts object into a Typescript project, we lose all type support and are unable to import specific parts of the library (e.g. `import {Chart, Options}`).

**Comment by karolkolodziej** [comment]
Hi @LuckyWindsck!

It looks like a general problem with Vue 3, we are working on it internally but we haven't found any workaround yet.
We will keep you posted!

**Comment by Adnan-kreiker** [comment]
I'm also facing this issue, any updates on it?

**Comment by jakubSzuminski** [comment]
I'm not entirely sure, but I think it might be related to this common TS/Vue issue - https://github.com/vuejs/vue-cli/issues/1198
I've solved it by creating a `shims-vue.d.ts` file in the `src` folder with the following content:
```typescript
declare module "*.vue" {
   import Vue from "vue";
   export default Vue;
}
``` 
Please try this out and let me know if it solves your problem.

**Comment by Adnan-kreiker** [comment]
@jakubSzuminski You are correct. The issue is not related to `Highcharts` but rather to the `Volar` extension.

I tried disabling it and importing `highcharts` in a typescript file and the types work as expected.

Have not found a solution for it so far.

![image](https://github.com/highcharts/highcharts/assets/81513811/c288d256-002d-4561-81ad-e247acbfbbbb)

**Comment by LuckyWindsck** [comment]
> @jakubSzuminski You are correct. The issue is not related to `Highcharts` but rather to the `Volar` extension.
> 
> I tried disabling it and importing `highcharts` in a typescript file and the types work as expected.
> 
> Have not found a solution for it so far.

Yes. As mentioned in the first comment, I have tried to import `highcharts` in a seperate `.ts` file as well and everything works. But importing `highcharts` inside a `.vue` file doesn't work.

If you disable `Volar`, then VSCode cannot recognize files with `.vue` extension.

**Comment by LuckyWindsck** [comment]
> shims-vue.d.ts

Thanks for your advice. I tried it just now but it doesn't work.

<img width="1294" alt="image" src="https://github.com/highcharts/highcharts/assets/24631178/11451062-5edd-45b6-b19c-1b6805b44e6f">

**Comment by volatile-static** [comment]
> shims-vue.d.ts

https://stackoverflow.com/questions/76662484 that workaround seems not work.

> I don't think it's strictly related to our library

But I think you should reduce the size of a d.ts file. (it's terribly big now

**Comment by volatile-static** [comment]
There's a tricky workaround: find your `node_modules\highcharts\highcharts.d.ts` in vscode and find with regular expression `\/\*(\n|.)*?\*\/` to match all comments and replace all with nothing. This can greatly reduce the file size so that volar can successfully recognize it.

**Comment by Adnan-kreiker** [comment]
@volatile-static That is very smart! The size of `highcarts.d.ts` is `22 MBs` which is more than the default maximum size that `Volar` can load. 

The fix was to increase the `Max File Size` to `30 MBs`  in `volar settings`

![image](https://github.com/highcharts/highcharts/assets/81513811/98a28082-325b-4f83-93f4-973849abab40)

**Comment by volatile-static** [comment]
@Adnan-kreiker 
> The fix was to increase the `Max File Size` to `30 MBs` in `volar settings`

Nice solution! Thank you very much!

**Comment by LuckyWindsck** [comment]
> @Adnan-kreiker: The fix was to increase the `Max File Size` to `30 MBs` in `volar settings`

Nice solution! Just want to notice you that 300,971,520 bytes is 287.029 MBs instead of 30 MBs.

<img width="556" alt="image" src="https://github.com/highcharts/highcharts/assets/24631178/9f932957-cd9c-45dc-b02d-b9b433dea6be">

**Comment by jakubSzuminski** [comment]
Thank you very much @Adnan-kreiker!

You're completely right. Volar does not detect `highcharts.d.ts` as it exceeds the default max file size. 

The current solution for VSCode is to go to: `File` -> `Preferences` -> `Settings` and change the `Vue: Max File Size` to a number above 23MB.

**Comment by LuckyWindsck** [comment]
> @volatile-static: But I think you should reduce the size of a d.ts file. (it's terribly big now

Never thought that this can cause the problem. Very smart! and I agree with that maybe we should reduce the size of a d.ts file.

**Comment by jakubSzuminski** [comment]
**FYI** @bre1470 

Maybe we could do something do decrease the size of the `.d.ts` files?

**Comment by LuckyWindsck** [comment]
Btw, I just checked the output of Vue Sematic Server, and it does report this problem.

> [volar] file size exceeded limit: file:///Users/luckywind/Documents/GitHub/LuckyWindsck/minimal-vue-typescript-highcharts/node_modules/highcharts/highcharts.d.ts (23105943 > 20971520)

<img width="1276" alt="image" src="https://github.com/highcharts/highcharts/assets/24631178/8da90d8f-798f-4c62-ac0f-1e134e3ed89a">
