### ISSUE TITLE
pointStart in plotOptions doesn't update when set alone

### ISSUE THREAD

**Issue by HRworksKra** [highcharts/highcharts#19203]
#### Expected behaviour
When setting pointStart in plotOptions I expect it to be updated when the property changes.
I want to be able to set pointStart only and not be forced to also set pointINterval in the plotOptions.

#### Actual behaviour
When *only* pointStart is set, it updates once and then never again.

Only if both pointStart and pointInterval is set it works how its supposed to work
Here is an example: https://stackblitz.com/edit/react-uu6kug?file=components%2FContainer.jsx

Looking at this old issue of yours it's supposed to work: https://github.com/highcharts/highcharts/pull/13949. But it does not.

#### Live demo with steps to reproduce

 https://stackblitz.com/edit/react-uu6kug?file=components%2FContainer.jsx

#### Product version
"highcharts": "^11.1.0",
 "highcharts-react-official": "^3.2.0",
 "react": "^17.0.2",

#### Affected browser(s)
I tested in Chrome.

**Comment by bm64** [comment]
Hi @HRworksKra and thanks for reporting the issue.
