### ISSUE TITLE
Bar Chart mobile pinch zoom problem

### ISSUE THREAD

**Issue by FTCP** [highcharts/highcharts#19217]
#### Expected behaviour
zoom to specific location in chart

#### Actual behaviour
flips the chart and makes it column (only bars, not labels)

**Comment by bm64** [comment]
Hello @FTCP and thanks for reporting the issue.

Looks like it worked fine in v10.3.1 and was broken in v10.3.2. Demo: https://jsfiddle.net/BlackLabel/sc5eb3kq/
