### ISSUE TITLE
Only Scatter tooltip is visible

### ISSUE THREAD

**Issue by rahulbadekarr** [highcharts/highcharts#19215]
Hi Team,

Link: http://jsfiddle.net/fpcgnvwm/

When I make the chart type as scatter and when I hover only scatter tooltip is visible ,

Why all other 2 chart tooltip is not visible
can you please let me know on this it will be helpfull

Thanks

**Comment by bm64** [comment]
Hello @rahulbadekarr 

I'm not sure if I understood the question correctly, but I assume that you're asking why scatter series is not included in the shared tooltip. It is intended behaviour - as you can read in our API, shared tooltip is not available for unordered series types (pie, scatter, flags etc): https://api.highcharts.com/highcharts/tooltip.shared

As a workaround you can overwrite `noSharedTooltip` property: http://jsfiddle.net/BlackLabel/8w0uegLq/

We use github strictly as a bug / feature request tracking tool, and this ticket doesn't fall to any of those categories. For any further questions please use our [other support channels](https://www.highcharts.com/blog/support/), for example forum: https://www.highcharts.com/forum/
