### ISSUE TITLE
SeriesOptionsType allowing undefined data, causes crash

### ISSUE THREAD

**Issue by ArmandRedgate** [highcharts/highcharts#19221]
#### Expected behaviour

`SeriesOptionsType` should not allow for `undefined` on property `data`, or should handle `undefined` data in some way.

#### Actual behaviour

`HighchartsReact` > `Props.options.series` is `SeriesOptionsType`.

Many types under `SeriesOptionsType`, including for example `SeriesAreaOptions`, make property `data` optional, allowing users to pass an `undefined` value to it. However, when you do provide an undefined value to it, the graph crashes.

Specifically, they crash under [Series.ts here](https://github.com/highcharts/highcharts/blob/1cf8bedbf17e77cd43dbef272c581b6cfa878c8a/ts/Core/Series/Series.ts#L1145C21-L1145C71) at

```ts
pointOptions !== (options.data as any)[pointIndex]
```

because `options.data` is `undefined` and we are trying to index it.

The error looks something like this:

```
Cannot read properties of undefined (reading '0')
```

Stack trace:

```
(anonymous) (highcharts.js:433)
a.updateData (highcharts.js:432)
a.setData (highcharts.js:435)
a.update (highcharts.js:473)
(anonymous) (highcharts.js:408)
(anonymous) (highcharts.js:407)
a.update (highcharts.js:407)
(anonymous) (highcharts-react.min.js:1)
commitHookEffectListMount (react-dom.development.js:23145)
commitLayoutEffectOnFiber (react-dom.development.js:23263)
commitLayoutMountEffects_complete (react-dom.development.js:24683)
commitLayoutEffects_begin (react-dom.development.js:24669)
commitLayoutEffects (react-dom.development.js:24607)
commitRootImpl (react-dom.development.js:26818)
commitRoot (react-dom.development.js:26677)
performSyncWorkOnRoot (react-dom.development.js:26112)
flushSyncCallbacks (react-dom.development.js:12042)
(anonymous) (react-dom.development.js:25646)
```

#### Live demo with steps to reproduce

Not sure how to make a demo of the React version of Highcharts, where we experienced this.

#### Product version

Highcharts v10.3.1

#### Affected browser(s)

Tested on Chrome, but I expect this will happen on all browsers.

**Comment by karolkolodziej** [comment]
Hi @ArmandRedgate!

I've prepared a demo with that specific Highcharts version and with `data: undefined` but I'm not able to see any issues- [demo](https://codesandbox.io/s/highcharts-react-demo-forked-xfjqkn).
Is there something I'm missing?

**Comment by ArmandRedgate** [comment]
I've played around with things on my end and found that passing undefined to data does indeed not cause any issues. I.e. I am no longer able to reproduce it.

No idea what happened. Feel free to close this ticket. I will update if it ever happens again.
