### ISSUE TITLE
Subresource integrity checks suddenly failing for files in CDN

### ISSUE THREAD

**Issue by 925dk** [highcharts/highcharts#19237]
SRI checks for .js files in the Highcharts CDN are suddenly failing, preventing browsers to load Highcharts.

For example  `https://code.highcharts.com/10.3.1/highcharts.js` used to give `sha384-k6Riv/JvByNBVwD13GkZH2B/7ikzvDHEg3ffKqi0iokPc3v2O+sejT9ABGMFwPhl`, but now gives a different hash.

Other files and versions are also affected.

Were changes made to the old code in the CDN, so it's safe to recompute SRI hash?

**Comment by karolkolodziej** [comment]
Hi @925dk!

The last modification of  `highcharts.js` was on 31st October 2022.

Can you please share:
- the hashing algorithm used to hash the content
- hash that was generated
- original file/content that you are hashing

so we can properly test that on our end.

**Comment by 925dk** [comment]
Hi @karolkolodziej,

Both algo (sha384) and hash is actually shown in the issue I created above. I do not know the content of the original file.

Now, the really odd thing, is that today (as of right now) things are seemingly back to normal (returning their original hash). Yesterday they did not. Here are 3 examples of files that all suddenly computed to new/different hash files yesterday, when I created the issue. But now they are back to normal again.

I'm of course curious if you are (accidentally?) fiddling with the old files (or if something fishy is going on).

```
<script
  src="https://code.highcharts.com/10.3.1/highcharts.js"
  integrity="sha384-k6Riv/JvByNBVwD13GkZH2B/7ikzvDHEg3ffKqi0iokPc3v2O+sejT9ABGMFwPhl"
  crossorigin="anonymous">
</script>

<script
  src="https://code.highcharts.com/10.3.1/highcharts-more.js"
  integrity="sha384-sE++I8fJ0nWrgwtwoQ9cMmDCm7nL72eC4QgHQJ+fdeblckB4ULlMuXk0UQavgH58"
  crossorigin="anonymous">
</script>

<script
  src="https://code.highcharts.com/7.0.3/highcharts.js"
  integrity="sha384-jyQTutOpzA8K1bx+oW82DJZu9W09+N5f7O0GnFbrt/tQbs1Q9FdoL9nTbw3hFSAv"
  crossorigin="anonymous">
</script>
```

**Comment by karolkolodziej** [comment]
I tested that yesterday and also if I test that today I get:
```
<script 
   src="https://code.highcharts.com/10.3.1/highcharts.js" 
   integrity="sha384-k6Riv/JvByNBVwD13GkZH2B/7ikzvDHEg3ffKqi0iokPc3v2O+sejT9ABGMFwPhl" 
   crossorigin="anonymous">
</script>
```

It's difficult for me to tell what might be wrong since I'm not able to recreate the issue.
Are you able to catch the actual difference between files?

**Comment by oysteinmoseng** [comment]
Hi @925dk - our current hypothesis is that a recent global change to our CDN config also affected the `code.highcharts.com` CDN unintentionally, by applying auto-minification of JavaScript. We can confirm that the files on origin are untouched on our side.

We have disabled the auto-minification for `code.highcharts.com` and flushed caches, so if you are still seeing different results than expected we will need to continue investigating.

If you do still get a different computed hash, it would be great if you could upload the file you are served so we can diff it against the origin to see what is going on.

**Comment by 925dk** [comment]
Great. Many thanks for clarifying that @oysteinmoseng.

Have tested a bit today from various locations, and am now getting correct (good old) files/hash values everywhere.

https://www.srihash.org currently returns a stale hash for `https://code.highcharts.com/10.3.1/highcharts.js` (but that must be their own local cache at play).

**Comment by oysteinmoseng** [comment]
Great! Closing for now then, but feel free to comment to reopen if the issue persists.
