### ISSUE TITLE
Last scatter point not visible 

### ISSUE THREAD

**Issue by krp12345** [highcharts/highcharts#19243]
Expected behaviour: 
All scatter point should be visible when chart is loaded.
Please check: 
https://www.highcharts.com/forum/viewtopic.php?f=12&t=51074&e=1&view=unread#unread

Actual behaviour:
Last scatter point is not getting visible when graph is loaded.

Affected browser: chrome, not sure about other browser.

**Comment by jakubjanuchta** [comment]
_Internal note:_
The last point gets loaded in Highcharts v9.1.2, https://jsfiddle.net/BlackLabel/owm5agry/.

**Comment by krp12345** [comment]
10.2.1 version does not show last point.


Please check : jsfiddle.net/3ecjgust

**Comment by bm64** [comment]
As it was suggested a forum, `overscroll` property can be used as a workaround: https://jsfiddle.net/BlackLabel/nc7jwbkt/

**Comment by krp12345** [comment]
As per discussion in https://www.highcharts.com/forum/viewtopic.php?f=12&t=49114&start=15

Linking https://jsfiddle.net/sLtkfh2x/ with this issue.

**Comment by pawelfus** [comment]
The last scatter point issue has been fixed and is available on the master branch: https://jsfiddle.net/BlackLabel/q42yo97h/2/ 

The second part of the issue is still unresolved: https://jsfiddle.net/BlackLabel/6ukj0t8w/1/ vs https://jsfiddle.net/BlackLabel/6ukj0t8w/

**Comment by pawellysy** [comment]
`Internal note`
This happens because the scatter points are not taken into consideration, when calculating `ordinalPositions` because of the property `takeOrdinalPosition` which is defined here: https://github.com/highcharts/highcharts/blob/master/ts/Series/Scatter/ScatterSeries.ts#L168

The line mentions #2343.
