### ISSUE TITLE
Data Labels Do Not Respect Parent Series zIndex

### ISSUE THREAD

**Issue by Mylogin-info** [highcharts/highcharts#19242]
#### Expected behaviour
I expect data labels to respect the zIndex of their parent series. When data labels from different series overlap, the labels from a series with a lower zIndex should be positioned behind the labels and marker from a series with a higher zIndex.

#### Actual behaviour
It appears that data labels are handled in their own SVG group with a separate zIndex. This leads to situations where data labels from a series with a lower zIndex are drawn on top of the markers of a series with a higher zIndex. Each series appears to be drawn independently on top of the others.

#### Live demo with steps to reproduce
You can reproduce this issue using this JSFiddle link: https://jsfiddle.net/e3gjfk71/

#### Product version
Highcharts v11

#### Affected browser(s)
The issue is observed in all browsers.

**Comment by karolkolodziej** [comment]
HI @Mylogin-info!
Apologies for the late reply.

As you described the data labels group is rendered in a separate group and that is the intended behaviour.
But you still can manipulate indexes of individual series- [demo](https://jsfiddle.net/BlackLabel/k0u51w8p/).

You also can move the labels under the series as described in [the API.](https://api.highcharts.com/highcharts/series.line.dataLabels.zIndex)

**Comment by Mylogin-info** [comment]
Hi @karolkolodziej ,

Thank you for your reply.  I'm aware of the zIndex options for series and datalabels. Unfortunately it doesn't solve my issue.

I try to explain more clearly by this example:
https://jsfiddle.net/fsa69wud/

I need the datalabels of the Jack series  to be behind the markers of the John series. Is this possible?

If it's possible for two serie is it also possible for more than two series?

**Comment by karolkolodziej** [comment]
Yes, you can control that. As you can see in [the demo](https://jsfiddle.net/BlackLabel/0fz6Lukc/) you only need to add the `zIndex` for each series individually. 
The red label from the `John` series is always on the top.

**Comment by Mylogin-info** [comment]
The left picture is how it looks now. The right what I'm trying to accomplish. Notice that the markers of higher series are (partially) hiding the datalabels of lower series.

![image](https://github.com/highcharts/highcharts/assets/16088627/9c48089d-6463-4066-a16b-1b6840cf9c9c)

**Comment by karolkolodziej** [comment]
@Mylogin-info The easiest way to do that would be using the `dataLabels` with a white background color- [demo](https://jsfiddle.net/BlackLabel/qkhva8zL/).

Let me know if I can clarify anything here ;)

**Comment by Mylogin-info** [comment]
Thank you! That is exactly what I was looking for. I overlooked that datalabels could have a background color and radius etc. and got stuck in finding a solution with markers.

Even less code with no markers, borderColor: "auto" and shape: "circle".
https://jsfiddle.net/fv05ngch/2/

Have a nice day 👍
