### ISSUE TITLE
Incorrect flag position for spline series.

### ISSUE THREAD

**Issue by Vazonik** [highcharts/highcharts#19264]
#### Expected behaviour
Flags placed on the spline series should be positioned correctly.

#### Actual behaviour
Flags on series where the line is not a straight line connecting adjacent points, but a curve, such as in the spline series, are positioned incorrectly.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/jgnqpkxd/

#### Product version
Highcharts v11.1.0

**Comment by alexeychirkov** [comment]
Hey! Which version will contain this fix? Thank you.

**Comment by Vazonik** [comment]
> Hey! Which version will contain this fix? Thank you.

Hi, @alexeychirkov! The fix is already merged into master branch, so it will appear soon in the next version. You can test it loading the code from the master build, but it's not recommended to do it in production: https://jsfiddle.net/BlackLabel/creu0qfp/
