### ISSUE TITLE
Bug in tooltip documentation

### ISSUE THREAD

**Issue by HRworksKra** [highcharts/highcharts#19279]
#### Expected behaviour
in the documentation of the tooltip (https://api.highcharts.com/highcharts/tooltip) it says **Can be one of: "callout", "circle" or "rect"**. 

#### Actual behaviour
As 'rect' didn't work for me I checked in your files (highcharts.d.ts) and it is actually "callout"|"circle"|"square". See screenshot. 
<img width="286" alt="image" src="https://github.com/highcharts/highcharts/assets/115986149/fd29be48-1bbd-44fa-ac25-519950326306">

**Comment by karolkolodziej** [comment]
Hi @HRworksKra!

Thank you for reporting the issue! 

Internal note:
It looks like there is another interface `Tooltip.ShapeValue` along with `TooltipShapeValue`.
https://github.com/highcharts/highcharts/blob/44a24ce3a7a61661506d4e78b13ebcc2b587298b/ts/Core/Tooltip.ts#L1865

This needs to be unified.
