### ISSUE TITLE
Missing data in CSV export for scatter plot

### ISSUE THREAD

**Issue by foxcodes** [highcharts/highcharts#19271]
#### Expected behaviour
All data is included in the exported CSV file

#### Actual behaviour
Some data is omitted when 2 different series have data with the same x value

#### Live demo with steps to reproduce
JSFiddle: https://jsfiddle.net/ekuLfg4y/

* Click on the export menu and Download as CSV
* Open the downloaded CSV
* Observe that only 5 rows are present rather than 8

#### Product version
11.1.0

#### Affected browser(s)
Chrome

**Comment by foxcodes** [comment]
from my investigation seems that issue stems from `ExportData.ts` line 564 where it checks for `rows[key]`. If two data series with the same `x` value are there then it overwrites the original data with the new series one.

**Comment by bm64** [comment]
Hello @foxcodes and thanks for reporting the issue.

**Comment by foxcodes** [comment]
any ETA on when the bug might be approached?

**Comment by bm64** [comment]
Hi @foxcodes. Unfortunately, we don't have an ETA yet, but I'll let you know as soon as we do.

**Comment by oysteinmoseng** [comment]
Related: https://github.com/highcharts/highcharts/issues/10743

**Comment by foxcodes** [comment]
Hi,

I can see the issue is closed and that a branch was raised, but when I get the latest version of Highcharts 11.4.0, the issue still exists and I can't see the code changes from the PR: https://github.com/highcharts/highcharts/commit/6d29948fa877df02f5a54ca1695a71758222431d?diff=unified&w=0 , being part of the code,

Can I get an update on what has happened with the issue that was reported?

**Comment by hubertkozik** [comment]
Hi @foxcodes!
I've just tested the OP demo, which was provided in first post here: https://jsfiddle.net/BlackLabel/5e7bphud/ and everything is working correctly. Exported CSV contains 8 elements, for two series (ss attached).
<img width="423" alt="image" src="https://github.com/highcharts/highcharts/assets/62724907/7799eb00-19d9-4d18-b77b-be5222d7bca1">
Can you double-check? Maybe you have some issues with the cache?

**Comment by foxcodes** [comment]
Hi @hubertkozik,

Thank you for your reply, I checked it again, and removed the overwrite we had for the `getDataRows` and I can see the fix working. 

Thank you for resolving the original issue!
