### ISSUE TITLE
Numeric pointPlacement adds x-axis padding

### ISSUE THREAD

**Issue by awonihlgard** [highcharts/highcharts#19282]
Not sure if this is a bug.

#### Expected behaviour

From the [documentation](https://api.highcharts.com/highcharts/series.column.pointPlacement):

> Since Highcharts 3.0.2, the point placement can also be numeric, where 0 is on the axis value, -0.5 is between this value and the previous, and 0.5 is between this value and the next. Unlike the textual options, numeric point placement options won't affect axis padding.

I expected this to mean that no padding will be added to the x-axis when compared to not having a column serie in the chart.

#### Actual behaviour

A numeric value for pointPlacement still results in x-axis padding being added compared to not having the column serie. The padding is however not added when using `pointPlacement: 'on'`. I would like to avoid adding any padding, while still allowing a custom placement of the columns.

#### Live demo with steps to reproduce

- Case 1: No column serie (**no padding added**). https://jsfiddle.net/3btwqjzc/1/
- Case 2: `pointPlacement: 'on'` (**no padding added**). https://jsfiddle.net/jmvzx4qc/1/
- Case 3: `pointPlacement: undefined` (**padding added**). https://jsfiddle.net/94Lwpm6o/1/
- Case 4: `pointPlacement: 0.0` (**padding added**): https://jsfiddle.net/3y71qz86/1/

#### Product version
Highcharts v11.1.0

**Comment by karolkolodziej** [comment]
Hi @awonihlgard!

According to the documentation that is a bug- [demo with each chart on one page.](https://jsfiddle.net/BlackLabel/4ftmbonL/)

The numerical `pointPlacement` should not affect the axis padding unless the documentation needs to be adjusted.
Any thoughts @TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
I think this think with the padding is best understood when setting `pointPlacement: 'between'`. If you do that, you'll see that the x-axis is extended to the right to make room for the shifted columns: 

<img width="167" alt="Skjermbilde 2023-07-07 kl  07 37 40" src="https://github.com/highcharts/highcharts/assets/227836/cd3ee434-9ba5-452c-b8a0-69cb72b17a86">

When the docs state that "numeric point placement options won't affect axis padding", it means that `pointPadding: 0` behaves like `pointPadding: undefined`. 

> I expected this to mean that no padding will be added to the x-axis when compared to not having a column serie in the chart
I think what causes this confusion is that the column themselves take up space, through the default [pointRange](https://api.highcharts.com/highcharts/series.column.pointRange). If we set that to 0, no padding is added: https://jsfiddle.net/highcharts/cdLygm06/.

**Comment by karolkolodziej** [comment]
With that said, it looks like it works exactly like you described- [an updated demo.](https://jsfiddle.net/BlackLabel/m6jhg9ro/)

With numerical `pointPlacement` there is no padding at the right whereas with `pointPlacement: 'between'` there is additional padding.
