### ISSUE TITLE
World map bug with touch functions

### ISSUE THREAD

**Issue by ibotti** [highcharts/highcharts#19305]
#### Actual behaviour

When you click in a country and  make zoom with touch funtions in mobile (Andoid) devices, sometimes the world disappear

#### Live demo with steps to reproduce

https://github.com/highcharts/highcharts/assets/17781710/f684244a-1f02-41ee-879d-7c8fc5b0766e

#### Product version
'https://code.highcharts.com/mapdata/custom/world.topo.json'
Highcharts.mapChart
highmap
#### Affected browser(s)

Android -> google Chrome

**Comment by bm64** [comment]
Hello @ibotti and thanks for reporting the issue.

**Comment by KacperMadej** [comment]
Unable to recreate. Possibly fixed. If you have a (stable) way to recreate the problem please leave a comment and the issue could be reopened.
