### ISSUE TITLE
Tooltip outside on column chart cut off

### ISSUE THREAD

**Issue by jjensenbloom** [highcharts/highcharts#19314]
#### Actual behaviour

When setting tooltip.outside to true on a column chart, the bottom of the tooltip is cutoff by 1 pixel.

#### Live demo with steps to reproduce
https://jsfiddle.net/ty3vgpnr/

#### Product version
Highcharts 11+

#### Affected browser(s)
Chrome, Firefox

**Comment by pawellysy** [comment]
Hey @jjensenbloom, thanks for reaching out to us!
Could you provide a screenshot, where I can see the issue? I've tried reproducing it myself, with no luck.

**Comment by jjensenbloom** [comment]
![image](https://github.com/highcharts/highcharts/assets/72892275/453c2eb5-3403-422b-bd90-1127b2f776f4)

![image](https://github.com/highcharts/highcharts/assets/72892275/ca1d42ba-874f-49dc-9da3-866636d37466)

It's subtle, but there is a white line underneath the arrow pointing at the column and the last pixel of the arrow is cut off.

**Comment by pawellysy** [comment]
Ok, I can see it now. Thanks for reporting this issue! As a workaround, you can use the `tooltip.positioner` method, to position the tooltip yourself, and avoid such behavior. Thanks!
