### ISSUE TITLE
Tooltip with 'outside' and 'useHTML' lingers after leaving the hover area instead of being removed.

### ISSUE THREAD

**Issue by stevethemacguy** [highcharts/highcharts#19325]
#### Expected behaviour
Leaving the chart hover area should remove the tooltip from the HTML.

#### Actual behaviour
Leaving the chart hover area does not remove the tooltip from the HTML. After hovering the tooltip and resizing the browser, the lingering tooltip causes unwanted whitespace in the outer container.

#### Live demo with steps to reproduce
http://jsfiddle.net/bhmgv7rx/

Steps to Reproduce:

1. Hover over the 2nd (right-most) chart to show a tooltip. This chart must use `outside: true` and `useHTML: true`.
2. Resize the outer container so the width is less < 500px (see the CSS media query). The charts will wrap and take up 100% width as expected.
3. Use a trackpad or mouse-wheel to scroll to the right. Extra whitespace is present on the right side of the outer container.

Steps to Reproduce (video):
https://github.com/highcharts/highcharts/assets/1767135/590e6081-f993-4a3f-9257-42e4f84d0b96

Note: There's an [existing issue](https://github.com/highcharts/highcharts/issues/18490) that seems related, but the suggested 'fix' is basically a hack. [That bug](https://github.com/highcharts/highcharts/issues/18490) (which might be fixed) is that the tooltip stays over the screen. In this bug (19325) the tooltip isn't visible on screen, but causes extra whitespace.

#### Product version
Highcharts v11.1.0 (Our app uses v10.3.3. This bug is present in both versions).

#### Affected browser(s)
Chrome, Safari, possibly others.

**Comment by karolkolodziej** [comment]
Hi @stevethemacguy! 
Thank you for bringing our attention to this issue once again! 

Perhaps this is a time when we can discuss possible solutions @TorsteinHonsi?
What do you think about:
1. When `useHTML: true` always destroys the tooltip when hiding
2. Add a flag `destroyWhenHiding` as suggested in [the demo](https://jsfiddle.net/BlackLabel/5wbednry/)
3. other?

**Comment by GoncaloCamaz** [comment]
@karolkolodziej is the destroyWhenHidding flag already available in Highcharts? 

Just to give some additional context, I am using React Portals to display the tooltips because I need to have some action buttons inside the tooltips. However, when the tooltip disappears and since I am using the outside property, the container is still there even though I don't see the tooltip. This will block me from hovering other chart points bellow the position where the tooltip was drawn.

**Comment by GoncaloCamaz** [comment]
@karolkolodziej that is indeed a good option however Im having some troubles displaying the tooltip again after destroying it. Since in your demo the example works, I might have something on my side that is not creating the tooltip again.

**Comment by karolkolodziej** [comment]
If you are able to recreate your setup in some online code editor I can take a look at what might be wrong ;)

**Comment by TorsteinHonsi** [comment]
I created a fix for this in the [above PR](https://github.com/highcharts/highcharts/pull/19498).

OP demo with the fix applied: https://jsfiddle.net/highcharts/zsmx5efu/
