### ISSUE TITLE
Inaccuracy in the type definitions for `SelectEventObject`

### ISSUE THREAD

**Issue by srmagura** [highcharts/highcharts#19326]
#### Expected behaviour

The TypeScript definitions for `SelectEventObject` should define the `preventDefault` function. This function exists at runtime, and is mentioned [here](https://api.highcharts.com/highcharts/chart.events.selection) in the API docs.

#### Actual behaviour

The TypeScript definitions for `SelectEventObject` do not define the `preventDefault` function.

Example:

```ts
const handleSelection: Highcharts.ChartSelectionCallbackFunction = (e) => {
  // TypeScript error here:
  e.preventDefault(); 
}
```

#### Product version

Highcharts 11.1.0

**Comment by karolkolodziej** [comment]
Hi @srmagura!

You are right the `preventDefault` field is missing in this interface but on the other hand, the TS forces you to use some return statements in the `selection` method. When you return `false` it works the same as `preventDefault` -[demo](https://stackblitz.com/edit/typescript-abzffq?file=index.ts).

@bre1470 your thought?

**Comment by srmagura** [comment]
@karolkolodziej, yes, I am aware you can accomplish the same thing by returning `false`. Just wanted to raise this issue because `preventDefault` is mentioned in the docs, so the TypeScript type defs should define it.
