### ISSUE TITLE
Calling setData on Map Series throws an error with pattern-fill.js

### ISSUE THREAD

**Issue by SyedTayyab99** [highcharts/highcharts#19323]
#### Expected behaviour
When series[0].setData() function is called, it should update the data of the series.

#### Actual behaviour
The call throws the following error

Uncaught TypeError: Cannot read properties of undefined (reading 'chart')
    at r.calculatePatternDimensions (pattern-fill.src.js:169:36)
    at R.<anonymous> (pattern-fill.src.js:417:21)
    at highmaps.src.js:1748:25
    at Array.forEach (<anonymous>)
    at e (highmaps.src.js:1745:17)
    at H.complexColor (highmaps.src.js:9664:17)
    at H.fillSetter (highmaps.src.js:9993:21)
    at H.<anonymous> (highmaps.src.js:9586:29)
    at C (highmaps.src.js:1413:21)
    at H.attr (highmaps.src.js:9564:21)

#### Steps to reproduce
I am attaching the files being used. On line 577, there is a call to "hchart.series[0].setData(data)" which results in error.
[live-data.zip](https://github.com/highcharts/highcharts/files/11985418/live-data.zip)

#### Product version
Latest Versions

#### Affected browser(s)
All browsers

**Comment by karolkolodziej** [comment]
Hi @SyedTayyab99!

I'm unable to recreate that locally. Will you be able to prepare a minimal demo in some online code editor?

**Comment by SyedTayyab99** [comment]
Hi @karolkolodziej Thanks a lot for your response. Let me try that

**Comment by karolkolodziej** [comment]
There is a lot of custom code in your example shared initially. It would be great if you can reduce it ;)

**Comment by SyedTayyab99** [comment]
@karolkolodziej Please check the following fiddle. Once you click on the "Reload Data" button, you'll be able to see the issue. 

https://jsfiddle.net/SyedTayyab/an4ocdsp/

Please feel free to let me know if you need anything else from my side.

**Comment by karolkolodziej** [comment]
Thank you @SyedTayyab99 for the demo.

Internal note:
[I managed to simplify it even more.](https://jsfiddle.net/BlackLabel/8shqnLdz/)
@KacperMadej @hubertkozik Could you please take a look? It seems like this line might be the issue:
https://github.com/highcharts/highcharts/blob/82e2e12989af6e0771a5c25acb0fd0840dee99a6/ts/Extensions/PatternFill.ts#L573-L579

**Comment by SyedTayyab99** [comment]
Hi @karolkolodziej please let me know if there is a work around or a patch that I can use in the meantime?

**Comment by mabuhaddah** [comment]
Dear @karolkolodziej , Hope this message finds you well.
Your kind support is highly appreciated. 
Please we need any hotfix for our issue urgently.

Thanks

**Comment by mabuhaddah** [comment]
@karolkolodziej  your quick action and feedback are highly appreciated!
