### ISSUE TITLE
Range selector 'All' button not setting the whole range when xAxis.overscroll set

### ISSUE THREAD

**Issue by jakubjanuchta** [highcharts/highcharts#19332]
#### Expected behaviour
When clicking 'All' button in range selector, the extremes of the chart should be set as the whole range of the chart, if `xAxis.overscroll` is set to any value.

#### Actual behaviour
When clicking 'All' button in range selector, the extremes of the chart are not set on the whole range, cutting some data on the left side if `xAxis.overscroll` is set to any value.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5tbwd8su/

1. Click 'All' button in range selector. The extreme on the left is not set to the end.
2. Remove the overscroll setting. The extreme on the left will be properly set.

#### Product version
Highcharts v11.1.0

#### Affected browser(s)
All

**Comment by bm64** [comment]
Hello @jakubjanuchta 

I don't think it is a bug. As we can read in [API for overscroll property](https://api.highcharts.com/highstock/xAxis.overscroll): Can be set for both main xAxis and the navigator's xAxis.
And setting the property for navigator's axis seems to do the trick: https://jsfiddle.net/BlackLabel/sqd780gw/

**Comment by krp12345** [comment]
If some developer is not working on this. then I would like to debug this and fix. I can see the source code from github as it is open source right?
