### ISSUE TITLE
Boost mode: Point is missing tooltipFormatter

### ISSUE THREAD

**Issue by Kisters-BS** [highcharts/highcharts#19338]
#### Expected behaviour
Point should have tooltipFormatter

#### Actual behaviour
Point is missing tooltipFormatter

#### Live demo with steps to reproduce
https://jsfiddle.net/5Lf2yvre/3/

#### Product version
v11.1.0

#### Affected browser(s)
All

**Comment by bm64** [comment]
Hello @Kisters-BS

You're right, in Highcharts' boost mode, point objects don't carry extra properties, including tooltipFormatter function, to ensure the best performance. Thats not a bug, it is an intended behaviour.

As a workaround, consider using `tooltip.defaultFormatter`. This should help solve your issue: https://jsfiddle.net/BlackLabel/5qareb3x/

**Comment by Kisters-BS** [comment]
Hello @bm64,

thank you for the clarification.
I could not get it working for multiple series: https://jsfiddle.net/13dr2hcb/

**Comment by bm64** [comment]
Hi @Kisters-BS 

I'm not sure if I understand your reply, provided demo seems to work fine. Is there anything else I can help you with? If so let me know what exactly do you want to achieve.

**Comment by Kisters-BS** [comment]
Hello @bm64,

it shows the series for the hovered point twice in the tooltip but it should show both series.

**Comment by bm64** [comment]
@Kisters-BS please try this one: https://jsfiddle.net/BlackLabel/f2n1vb8h/ 

With any further questions regarding this matter please visit out other [support channels](https://www.highcharts.com/blog/support/), preferably forum: https://www.highcharts.com/forum/
We use github strictly as a feature request / bug tracking tool and this ticket doesn't really fit any of these.

**Comment by Kisters-BS** [comment]
Hello @bm64,

yes that was the solution I was looking for, thank you. However, it looks rather like a workaround.

I came from a support ticket. I wasn't sure if I should continue with you or the support to find the solution.
