### ISSUE TITLE
X-range chart incorrect tooltip position

### ISSUE THREAD

**Issue by KamilKubik** [highcharts/highcharts#19343]
#### Expected behaviour
Tooltip with **yAxis.height** and **yAxis.top** properties should be positioned correctly.

#### Actual behaviour
Tooltip with **yAxis.height** and **yAxis.top** properties isn't positioned correctly (it seems to be positioned to its initial position).

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/qcugzexw/

#### Product version
v11.1.0

**Comment by bm64** [comment]
Thanks @KamilKubik for reporting.

It was working fine in v7.0.1, broken since v7.0.2. Looks like `tooltip.split` slightly help with the positioning: https://jsfiddle.net/BlackLabel/6anfpgyh/

_Internal note:_
Unable to bisect.
