### ISSUE TITLE
custum markers overlapping each other on mouse hover

### ISSUE THREAD

**Issue by okuznetsovsi** [highcharts/highcharts#19359]
#### Expected behaviour
how to make the marker "moscow" by default be placed behind the marker "tula", and also when hovering over the marker "moscow" it remains behind the marker "tula" and is partially highlighted? 
Also can consider other approaches to placing markers on the map, or you can try grouping markers, as well as other options

#### Actual behaviour
custum markers overlapping each other on mouse hover

#### Live demo with steps to reproduce
https://codesandbox.io/s/highcharts-vue-map-employees-forked-m2n7ld?file=/src/components/Chart.vue

#### Product version
Highmaps v10.3.3 (2023-01-20)

#### Affected browser(s)
all browser(s)

**Comment by pawellysy** [comment]
Hi! Thanks for reaching out to us! Sorry, but we are treating the GitHub as a bug feature tracking tool. Please wait for the answer in other support channels. Thanks!

**Comment by okuznetsovsi** [comment]
it turns out some kind of vicious circle, here "[highcharts.com](https://www.highcharts.com/forum/viewtopic.php?f=14&t=51142&sid=4bf9c23b3c90ffb325313b8dea45b4fa)" your employees informed me that there really is such a problem with custom markers, and that I correctly created a topic in github. Do you think that this is not a mistake and the functionality should work this way? Are there any plans to improve this functionality and fix the defect, and when?
