### ISSUE TITLE
navigation.bindings.fibonacci calculation vs Annotation module sample

### ISSUE THREAD

**Issue by rmasheck** [highcharts/highcharts#19367]
both calculation should be consistent. if you try the annotation module example, it uses end-start as difference (which is correct) navigation.bindings.fibonacci (Fibonacci class) should use the same formula.

Actual behavior: in stockTools' GU if you draw Fibonacci retracement --> depending on the direction it uses 0(0%) for the first click point(first candle) which is not correct.

[https://jsfiddle.net/sLn4hz1j/4/](url)

steps:
1. draw the retracement from some where from top of the chart to bottom..(opposite direction of existing one diagonal line)
2. draw from bottom to top.. 
in both direction first candle(first point) should be at 1 (100%)

version --
11.1

**Comment by bm64** [comment]
Hello @rmasheck, and sorry for the delayed response.

After discussing the issue with our team, we've concluded that a new property should be added to the Fibonacci annotation. This property will allow users to choose whether the annotation should start from 0 or 1, with the default behaviour set to start from 1.

In the meantime, as a workaround, you can override the `linkRetracementsPoints` method: https://jsfiddle.net/BlackLabel/1rz6chyg/

**Comment by rmasheck** [comment]
Thanks a lot.. also can we add diagonal support/resistance line options as well. that would be really helpful as well.. (it does show in Annotation module sample.. and its very simple to calculate..
