### ISSUE TITLE
modules: .d.ts missing for dist

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#19364]
#### Behaviour
test\typescript-lint\tsconfig.json
needs to have paths added as mentioned [here](https://github.com/highcharts/highcharts/tree/master/ts/masters#classic-typescript-declarations)

Affected modules:
- flowmap
- pictorial
- <s>mouse-wheel-zoom</s> - already [fixed](https://github.com/highcharts/highcharts/pull/19116)
- data-tools
- geoheatmap
- tiledwebmap

#### Live demo with steps to reproduce
3 instead of 5 because of the missing 2 .d.ts files on [highcharts-dist/modules](https://github.com/highcharts/highcharts-dist/tree/master/modules)

**Comment by yongshun950824** [comment]
Hi, in this [commit](https://github.com/highcharts/highcharts/commit/f6d0d444d23bd60c123523ee3f33ca177c40d35f)

I see that these two lines are added for geoheatmap:

```
"../../code/modules/geoheatmap.d.ts",
"../../code/modules/geoheatmap.src.d.ts",
```

But I checked the [highcharts-dist/modules directory](https://github.com/highcharts/highcharts-dist/tree/master/modules), there are no */ts* files for geoheatmap.

![image](https://github.com/highcharts/highcharts/assets/29250581/91d51a40-53f6-48ea-b498-0716b3abd1da)

Thus, this will lead to an error for the missing module for "geoheatmap" and cannot find the geoheatmap in "highcharts/modules"


I am wondering if this issue should be reopened or if there is any action to resolve this issue.

Thanks.
