### ISSUE TITLE
Line Chart Legend Symbol Disappeared When Using Gradient Fill

### ISSUE THREAD

**Issue by brucecui** [highcharts/highcharts#1936]
I'm trying to fill gradient color in my charts, with the sample code in the demo "http://www.highcharts.com/demo/pie-gradient". And then I found in line charts' legend, the line part of the symbol disappeared, while the markers were still visible. If I disable the markers, then there is nothing left.

Here is an example based on the code of a line chart demo: "http://jsfiddle.net/TCbE3/"

I'm using Highcharts 3.0.1, with both latest FireFox and Chrome, and this problem occurs in both.

Plz kindly help to look into this issue.

**Comment by Izothep** [comment]
+1

**Comment by Jeslopov** [comment]
nothing yet? i really need to use a gradient inside the legend but i get something like this: 

![capture](https://cloud.githubusercontent.com/assets/19694808/24772544/9269f116-1ac6-11e7-8b0a-0f3c1173f998.PNG)

i would like to set the legend icon half green and half red but the line is not there.

ideas please??

**Comment by TorsteinHonsi** [comment]
It turns out that my modifying the paths very slightly so they they are not perfectly horizontal, the gradients work as expected: http://jsfiddle.net/highcharts/TCbE3/3/

**Comment by Astimus** [comment]
+1

**Comment by balkarov** [comment]
@TorsteinHonsi hello your workaround beark `events`.
Chart does not destroy events after destroy:
https://jsfiddle.net/onqyvjz4/1/

**Comment by pawelfus** [comment]
Thanks @balkarov - event should be set on `Highcharts.Chart`, not `Highcharts.Chart.prototype`: https://jsfiddle.net/BlackLabel/t4svhxLe/

**Comment by balkarov** [comment]
@pawelfus thank you!
