### ISSUE TITLE
TreeGraph chart with collapsed levels shows initially one extra node expander with tooltip for hidden child

### ISSUE THREAD

**Issue by bigend** [highcharts/highcharts#19368]
#### Expected behaviour
When I initialize TreeGraph chart with certain levels collapsed it should render with that levels collapsed.
<img width="589" alt="image" src="https://github.com/highcharts/highcharts/assets/7856843/4c336f53-66b0-45f1-9f0e-e21a8af4b488">

#### Actual behaviour
When I initialize TreeGraph chart with certain levels collapsed it renders extra collapse node and when you hover over that node the tooltip for hidden child is shown.
<img width="589" alt="image" src="https://github.com/highcharts/highcharts/assets/7856843/ce95b910-a92f-4fb5-a30c-d970c340bd0f">

#### Live demo with steps to reproduce

https://jsfiddle.net/80kp4fwb

#### Product version

Highcharts 11.1.0

#### Affected browser(s)
Chrome, Firefox

**Comment by pawellysy** [comment]
Hi @bigend, thanks for reporting the issue!
The problem lies here: https://github.com/highcharts/highcharts/blob/6ca8dd2b4620a4bf7502d6dbf1b4adfaae4d4535/ts/Series/Treegraph/TreegraphPoint.ts#L113-L116

When initially creating the collapse button, it is not checked, if the point is visible.

**Comment by bigend** [comment]
Hi @pawellysy , thanks a lot for looking into this and for the workaround. I have checked the workaround fiddle, and it seems that there is still some minor issue. The collapse point is initially not visible, but if you try to hover over the place where it was, it appears again and it stays there, even when you move cursor away.

**Comment by pawellysy** [comment]
@bigend indeed, thanks for your input. Other idea is just not creating the button, if it is not needed, but then, when toggling the collapse status, it is already in its destined position.

https://jsfiddle.net/BlackLabel/bmnadqk9/5/

As a drop-in fix it can be used, but we will try to figure out the proper way of doing it in the core.
