### ISSUE TITLE
Quick fix: Invalid hex code in API Reference

### ISSUE THREAD

**Issue by msantmiller** [highcharts/highcharts#19376]
Hello! 👋  I am reaching out to flag a typo in the Highcharts API Reference (described below).

### Expected behavior
The list of default colors [here](https://api.highcharts.com/highcharts/colors) includes an array of valid hex codes.

### Actual behavior
The last element in the color array is missing a close quotation and is invalid (as it has 7 characters), as copied below:
[ "#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e12 ]

If users attempt to copy this array into their code, the invalid hex code will get rendered as solid black, as shown in the JS Fiddle below.

### Reproducible example
https://jsfiddle.net/msantmiller/agyfjnmx/4/

### Suggested change:
Change the default color array to:
[ "#2caffe", "#544fc5", "#00e272", "#fe6a35", "#6b8abc", "#d568fb", "#2ee0ca", "#fa4b42", "#feb56a", "#91e8e1"]

### Comments
Thank you very much for your work on Highcharts - I am a huge fan of the library and I am very grateful that it is freely available and open source!

**Comment by bm64** [comment]
Hello @msantmiller and thanks for reporting the issue.
