### ISSUE TITLE
Drilldown.animation = false causes Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by CoryKniefel** [highcharts/highcharts#19373]
#### Expected behaviour
When setting the drilldown.animation to 'false', the chart should function as expected when user attempts to drilldown. As described: https://api.highcharts.com/highmaps/drilldown 

#### Actual behaviour
The chart hangs for a few seconds and then an error is logged to console: Uncaught RangeError: Maximum call stack size exceeded

#### Live demo with steps to reproduce
https://jsfiddle.net/f1wv8ys3/6/

Notice line 139. 
* Open console 
* Click on a state in the chart
* Wait for error in console 
* Change line 139 to be true
* Save/run
* Click on a state in the chart
* Observe glorious drill-down

#### Product version

I'm seeing this in 11.1.0, the only version I've tried. 

#### Affected browser(s)
All that I've tried, which is just Edge.

**Comment by bm64** [comment]
Hello @CoryKniefel and thanks for reporting the issue.

Seems to work fine in 11.0.0 and broken since v11.0.1.

_Internal note_
Bisected to: e07b3f97fe8223670de4f7864ada29e91fa6b235 FYI @hubertkozik
