### ISSUE TITLE
Reset Zoom Button position settings are overwritten by the deprecated parameter

### ISSUE THREAD

**Issue by tararam** [highcharts/highcharts#19412]
#### Expected behaviour
In Highcharts.
According to documentation the position of Reset Zoom Button should be set as follows:
`chart: {
    zooming: {
         resetButton: {
               position: {
                   x: [customXValue],
                   y: [customYValue]
               }
`

#### Actual behaviour
The values above are overwritten by default values from now deprecated parameter: 
`chart: {
      resetZoomButton: {
           position: {
.....
      }             
`
In the source code this happens in the private function **setZoomOptions()**, as below:
`resetButton: merge(zooming.resetButton, options.resetZoomButton)`

The workaround is passing the following in the options:
`resetZoomButton: null`

#### Live demo with steps to reproduce
I don't have a live demo.

#### Product version
Works correctly in: v10.3.3
Works **Incorrectly** in: v11.1.0

#### Affected browser(s)
This is a general behaviour

**Comment by jakubSzuminski** [comment]
Thanks for reporting @tararam!

You've diagnosed the problem correctly. I've created a pull request solving this issue (https://github.com/highcharts/highcharts/pull/19416). It should be merged after code review so everything will work fine from the next release.

For now, you could stick to setting the `resetZoomButton: null` as you mentioned.
