### ISSUE TITLE
"Extending default formatter" sample code doesn't work

### ISSUE THREAD

**Issue by magnusanderson-wk** [highcharts/highcharts#19426]
#### Expected behaviour
Sample code does what it says it does

#### Actual behaviour
Sample code does nothing

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/formatter-conditional-default/
1. Add `console.log(this.point)`
2. Note that `isNull` is never true

#### Fix:
https://github.com/magnusanderson-wk/highcharts

#### Product version
highcharts 11.1.0

#### Affected browser(s)
All?

**Comment by karolkolodziej** [comment]
Hi @magnusanderson-wk!

Thank you for creating the issue and for your [workaround](https://jsfiddle.net/BlackLabel/Lpd4acnq/).
