### ISSUE TITLE
Highmaps: Russia map looks stretched for None projection type

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#19449]
#### Expected behaviour
When world map was rendered using geojsons, world map showed all countries correctly and flat on plane. It is expected that on using topojsons and not setting any projection type, flat(not curved) maps should be shown.

#### Actual behaviour
Refer the attached JS fiddle, select projection as None.(Internally it is set as undefined.) Hover on Russia map and observe that it looks stretched over Canada or other adjacent maps. Also, if we dont set any mapview.projection attribute in chart options, the country maps look curved.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/projection-explorer

#### Product version

v11.1.0

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @amruta30 

Thank you for reporting the problem.

This is by design. Under the map you find description and a part of it addresses the this issue:

> Notice the lines across the map at high latitudes. This is because the eastern tip of Russia is east of the antimeridian, and thus having longitudes close to -180 and upwards, while connected to the rest of Russia with longitudes from 180 and downwards. In cylindrical and conic projections this is mitigated by doing client-side antimeridial cutting, so that shapes spanning from one side of the plane to the other are cut in two.

Moreover, try changing lambda rotation when no projection is used to see more of this type of errors being caused by the mix of the used options.
