### ISSUE TITLE
HighchartMaps: Japan region Hyogo is misspelled as Hy?go and is not colored properly when coloring by name

### ISSUE THREAD

**Issue by maor-refaeli** [highcharts/highcharts#19454]
#### Expected behaviour
Maps: Japan's region Hyogo should be colored properly when coloring by name

#### Actual behaviour
Maps: Japan's region Hyogo is not colored.
There is a typo and the region Hyogo is saved as `Hy?go` instead of `Hyogo`

#### Live demo with steps to reproduce
https://jsfiddle.net/9tz74pvq/
Follow the instructions on line 12

#### Product version
Highmaps 2.1.0

#### Affected browser(s)
All

<img width="552" alt="Screenshot 2023-07-26 at 15 48 37" src="https://github.com/highcharts/highcharts/assets/137832153/a34b5531-57b7-4a28-b31d-a314efd43a75">

**Comment by krishnachandrasharma** [comment]
@maor-refaeli thank you!

**Comment by maor-refaeli** [comment]
https://github.com/highcharts/map-collection-dist/issues/32
