### ISSUE TITLE
Mouswheel zooming module does not respect customized xAxis range

### ISSUE THREAD

**Issue by irii** [highcharts/highcharts#19475]
#### Expected behaviour
The mouse wheel zooming should use the xAxis range instead of the data range for zooming into the the chart.

#### Actual behaviour
Currently the zooming module uses the data min/max range. This will cause a jumping behaviour between the data min/max and xAxis min/max range.

#### Live demo with steps to reproduce
https://jsfiddle.net/mb3k6dpc/

#### Product version
Highcharts/Highstock v11.1.0

#### Affected browser(s)
Edge (Windows, 115.0.1901.188 64bit)

**Comment by bm64** [comment]
Hello @irii and thanks for reporting the issue.

As a workaround, add a dummy, null point with an x value equal to the extreme value of the axis: https://jsfiddle.net/BlackLabel/pb2sdo4z/

**Comment by irii** [comment]
Hello,
are there any new informations about this issue?

Thanks.
Best regards

**Comment by sjdemartini** [comment]
I too encountered the bug around zoom breaking if "zoom is in an area where no point is visible anymore". To make sure that also gets addressed (separate from this customized xAxis range bug), I filed a new issue here: https://github.com/highcharts/highcharts/issues/19779

**Comment by jakubjanuchta** [comment]
> Hello, are there any new informations about this issue?
> 
> Thanks. Best regards

@irii 
I started working on this issue, it should be ready in 2 weeks time.

**Comment by irii** [comment]
@jakubjanuchta Thanks for fixing this issue!
BR
