### ISSUE TITLE
Typings in YAxisPlotLinesLabelOptions.formatter not correct

### ISSUE THREAD

**Issue by gaunap** [highcharts/highcharts#19480]
#### Expected behaviour
_this_ should be of a type containing all properties which are available at runtime, namely _axis_, _id_, _options_, svgElem

#### Actual behaviour
Type is PlotLineOrBand which contains _label_ and _svgElem_

#### Live demo with steps to reproduce
https://jsfiddle.net/stormtroopa/cb2tnfem/2/

#### Product version
Highstock 11.1.0

#### Affected browser(s)
affects VS Code

**Comment by karolkolodziej** [comment]
Hi @gaunap! 

Thank you for reporting this! You are right, the typing here might be improved 😉
