### ISSUE TITLE
Pie chart - Drilldown - Drilldown causing console error "cannot read properties of undefined (reading chart)"

### ISSUE THREAD

**Issue by mdcohen1993** [highcharts/highcharts#19481]
#### Expected behaviour
When in drilldown mode on a pie chart, we expect to click on the slice of the pie chart and not receive a console error.

#### Actual behaviour
When on a pie chart in drilldown mode and clicking on a pie slice, receive console error "cannot read properties of undefined (reading chart)".

This issue has been noticed by a customer approximately 2 months ago in the [Highcharts forum](https://www.highcharts.com/forum/viewtopic.php?f=9&t=50950). This bug is forcing our company to roll back to Highcarts version 10.3.3 in production.

#### Live demo with steps to reproduce
demo: https://jsfiddle.net/chrisgilbert/n3Lvy6pd/

#### Product version
Occurs in versions 11x.

#### Affected browser(s)
Firefox, Chrome, Edge

**Comment by karolkolodziej** [comment]
Hi @mdcohen1993!

This issue was reported and is already fixed: https://github.com/highcharts/highcharts/issues/19075

It should be released withing the next version.
