### ISSUE TITLE
Chart destruction is slow

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#19487]
#### Expected behaviour
Chart destruction should be fast and probably async

#### Actual behaviour
Chart destruction takes about 50ms with v10 and 16ms with v11.

The major issue here is that when using something like a tabbed layout, you would want to destroy the charts present in a tab while switching. In my usecase, the number of charts per tab can be upto 50 and the tab switch takes a significant time with a visible lag.

I would want to destroy charts asynchronously in an ideal case but using something like `setTimeout(chart.destroy, 0)` throws. While v11 is an improvement, I feel we still should have a way to defer the destruction.

#### Live demo with steps to reproduce
https://jsfiddle.net/by9h5cov/2/

#### Product version
Highstock JS v10.3.3, v11.1.0

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Hi @govinda18!

Is that what your config looks like? Aren't you using the boost module?
I'm asking because the time it takes to destroy a chart is a function of points and series amounts.
See how it works with boost- [demo](https://jsfiddle.net/BlackLabel/bvofLze1/).

Having the `destroy` as an async method is an interesting way to go!

**Comment by govinda18** [comment]
Thanks for your reply.

Interesting, I am actually already using boost module. Let me get the entire config and try creating a reproducer again. Thanks.

**Comment by govinda18** [comment]
I figured the issue at my end. I did have boostThreshold and it defaults to 5000. I had 3000 points in my series and in your demo, you have boostThreshold set to 2.

@karolkolodziej is there a recommendation on boostThreshold and the consequences if this is low such as in your demo?

**Comment by karolkolodziej** [comment]
In my example, I exaggerated a bit to make sure that the boost was enabled. 
The `boostThreshold` depends on how wide your chart might be, how dense your data is and how much computing power you have. Unfortunately, there is no one correct answer. 
But if you are saying that you can have up to 50 charts per page I would decrease this value slightly.
