### ISSUE TITLE
Boost mode with categories causes points inside plot to disappear

### ISSUE THREAD

**Issue by alrahemtulla** [highcharts/highcharts#19497]
#### Expected behaviour
Points inside the plot area should always be rendered

#### Actual behaviour
While scrolling after zoom, the points get clipped before they reach the edge of the plot.

#### Live demo with steps to reproduce
The series needs to be boosted and `xAxis.categories` must be set.

Zoom in and start scrolling horizontally. Notice that some points disappear early than we expect, and eventually most disappear before the category is off the screen.
https://jsfiddle.net/9g7Lmqph/1/

![image](https://github.com/highcharts/highcharts/assets/116202323/2fbe25ad-9a53-419f-a46d-857f58e30e3b)
![image](https://github.com/highcharts/highcharts/assets/116202323/df696154-5509-43f8-9e3f-94b5841594c6)

#### Product version
Latest

#### Affected browser(s)
All

**Comment by alrahemtulla** [comment]
Also notice that the points that DO appear near the edge of the plot, will not have tooltips.

**Comment by bm64** [comment]
Hello @alrahemtulla and thanks for reporting the issue.
