### ISSUE TITLE
R library highcharter function highchart() execute with exception the apparmor read denied for /etc/passwd and /etc/group

### ISSUE THREAD

**Issue by gujia1983** [highcharts/highcharts#19514]
#### Expected behaviour
I use the R library highcharter with ubuntu 18.04 and R 3.6.3. Recently, I upgraded to ubuntu 20.04 and R 4.3.1. And the version of library highcharter are both 0.9.4. Then I execute the function highchart() it always throw the exception that child process has died. And I checked the /var/log/kern.log and found below error:

Aug  7 08:37:50 ip-172-31-27-249 kernel: [2251703.494866] audit: type=1400 audit(1691397470.399:739): apparmor="DENIED" operation="open" profile="managedr-profile" name="/etc/passwd" pid=159930 comm="R" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Aug  7 08:37:50 ip-172-31-27-249 kernel: [2251703.494871] audit: type=1400 audit(1691397470.399:740): apparmor="DENIED" operation="open" profile="managedr-profile" name="/etc/group" pid=159930 comm="R" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

I'd like to have to solution to fix it without giving the read access for these two files /etc/passwd and /etc/group in the apparmor profile file as I did with ubuntu 18.04 and R 3.6.3.

#### Actual behaviour
If I add below two lines in my apparmor profile file it will resolve this issue. But I don't like to expose these two files to end user as it has potential risk.
/etc/passwd r,
/etc/group r,

#### Live demo with steps to reproduce

N/A

#### Product version

The version of R library highcharter are both 0.9.4. 

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment]
Hi @gujia1983!

The Highcharter wrapper is not ours thus we do not officially support it. None of our team members uses Linux. Unfortunately, we are not able to help you with this matter.

You can try to contact the wrapper's author on the official [Highcharter repo](https://github.com/jbkunst/highcharter/issues).

Best regards!
