### ISSUE TITLE
TypeError: Attempted to assign to readonly property

### ISSUE THREAD

**Issue by abaluta** [highcharts/highcharts#19516]
#### Expected behaviour

No errors

#### Actual behaviour

When the option styledMode is true
JavaScript error: TypeError: Attempted to assign to readonly property.

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/css/prefers-color-scheme
Enable or disable charts: {styledMode: true|false}

#### Product version

Highcharts

#### Affected browser(s)
Safari (Version 16.6 (18615.3.12.11.2))

#### Discussion of the error on the forum
https://www.highcharts.com/forum/viewtopic.php?f=12&t=50680&sid=9eb5202e6c8ab7f3fde9e4279f785e88

**Comment by karolkolodziej** [comment]
I can reproduce this issue only in Safari.

Looks like it was introduced in **v10.1.0** but I was unable to bissect. 
Needs further investigation.

**Comment by Samueloyeks** [comment]
I also have the same issue on safari
