### ISSUE TITLE
The tooltip box is displayed not underneath the tooltip text, two different positions

### ISSUE THREAD

**Issue by Oidlichtnwoada** [highcharts/highcharts#19534]
#### Expected behaviour
The tooltip markup is on the tooltip box

#### Actual behaviour
The two items are separated

Error: <g> attribute transform: Expected number, "translate(NaN,148)".

#### Live demo with steps to reproduce
picture in the following comment

#### Product version
Highcharts version: 11.1.0

#### Affected browser(s)
only tested on Edge

**Comment by Oidlichtnwoada** [comment]
maybe @TorsteinHonsi can help here? Could possibly affect multiple library users ...

**Comment by Oidlichtnwoada** [comment]
<img width="823" alt="259944300-bdffb058-4848-416f-a5ea-08be43d6b5e8" src="https://github.com/highcharts/highcharts/assets/42490916/4c7b197c-65e1-4f8c-8cc7-36e90ec89a03">

**Comment by bm64** [comment]
Hello @Oidlichtnwoada 

It's hard to tell just based on the image and error what causes the issue. Could you try to recreate the problem in an online IDE? You can start here: https://jsfiddle.net/BlackLabel/ewagc260/

**Comment by Oidlichtnwoada** [comment]
@bm64 I found out what the problem was, the default getPosition function of the tooltip does not return an x and y in all cases ... in some only a y value is returned, the x is missing ... this leads to this rendering error afterwards ... it would be nice if there were some default values set in case the other cases do not match ...

**Comment by Oidlichtnwoada** [comment]
I have written this custom tooltip position function:

/**
 * Place the tooltip in a chart without spilling over and not covering the point itself.
 * It uses the default implementation with some value corrections.
 * @param boxWidth width of the tooltip box.
 * @param boxHeight height of the tooltip box.
 * @param point tooltip related point.
 * @return recommended position of the tooltip.
 */
export function getTooltipPosition(
  boxWidth: number,
  boxHeight: number,
  point: Highstock.Point
): Highstock.PositionObject {
  // @ts-ignore
  const tooltipInstance = this as Highstock.Tooltip;
  const defaultPosition = tooltipInstance.getPosition(boxWidth, boxHeight, point);
  // make corrections and fill in defaults for x position
  defaultPosition.x ??= 1;
  if (defaultPosition.x === 0) defaultPosition.x = 1;
  // make corrections and fill in defaults for y position
  defaultPosition.y ??= 1;
  if (defaultPosition.y === 0) defaultPosition.y = 1;
  // return the corrected positioning object
  return defaultPosition;
}

**Comment by karolkolodziej** [comment]
That's good to hear that but is there something we can improve there? 
Could you please recreate your use case in some online code editor so we can understand it better?

**Comment by Oidlichtnwoada** [comment]
@karolkolodziej For me the problem is fixed with this addition, but when the available screen size gets small, the getPosition function just returns a y value but no x value ... there is a default position missing in this case ... just look at the convoluted if/else-constructs in the code ...
