### ISSUE TITLE
Linecap is not working for bar, area, column and pie chart

### ISSUE THREAD

**Issue by DmitryPacificAtion** [highcharts/highcharts#19545]
#### Actual behaviour
There was an example in documentation:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series-line/linecap/

But, linecaps are working for line chart. In legend that linecaps was changed to square and round accordingly. 
If we add 
```
chart: {
    	type: 'area'
    },
```
After that linecaps in legend became round and they size was changed.

#### Live demo with steps to reproduce
https://jsfiddle.net/DmytroBruslik/4kfgdvxL/1/

Also, changing type for concrete series gives nothing.
Another example:
https://jsfiddle.net/DmytroBruslik/4kfgdvxL/3/

#### Product version

"highcharts": "^10.3.3",
 "highcharts-react-official": "^3.1.0",
#### Affected browser(s)
Chrome Version 115.0.5790.171 (Official Build) (64-bit)
OS: Windows 11

**Comment by karolkolodziej** [comment]
Hi @DmitryPacificAtion! 
Thank you for bringing our attention to this.

As a workaround on the load event, you can check if the linecap is set and adjust the legend symbol accordingly- [demo](https://jsfiddle.net/BlackLabel/xfpvk4j2/).

**Comment by anujshaantruviz** [comment]
Hi @karolkolodziej 
Is there any way to add linecap on solid gauge pane?
https://stackoverflow.com/questions/76901900/how-to-make-pane-of-highchart-solidgauge-rounded

**Comment by karolkolodziej** [comment]
@anujshaantruviz We usually keep GitHub for tracking bugs and features. 
For support please use other channels like the StackOverflow.
In the meantime please try using the `rounded` property- [API](https://api.highcharts.com/highcharts/series.solidgauge.rounded).

**Comment by DmitryPacificAtion** [comment]
> Hi @DmitryPacificAtion! Thank you for bringing our attention to this.
> 
> As a workaround on the load event, you can check if the linecap is set and adjust the legend symbol accordingly- [demo](https://jsfiddle.net/BlackLabel/xfpvk4j2/).

Thanks! :)

**Comment by TorsteinHonsi** [comment]
@DmitryPacificAtion @karolkolodziej I think what you're looking for is the `legendSymbol` option: https://jsfiddle.net/highcharts/q2ao63de/ .

By default the legend symbol for area series is `rectangle`. Funny name for a circle, I know, but it's for historical reasons. The circle is actually a rectangle with a [symbolRadius](https://api.highcharts.com/highcharts/legend.symbolRadius).

**Comment by KamilKubik** [comment]
@TorsteinHonsi, after your explanation, I have to ask to make sure if we should still fix the mentioned bug and allow changing the legend symbols with the **linecap** option for other series?

**Comment by TorsteinHonsi** [comment]
As far as I can see, yes: https://jsfiddle.net/u9meg87f/

**Comment by TorsteinHonsi** [comment]
@KamilKubik I think we misunderstood each other. I don't know why I answered "yes" to your question, because I don't think this is a bug. What the PR does is to change the marker symbol, but the marker symbol has nothing to do with the line. So I think we should close this issue and the PR.
