### ISSUE TITLE
Treegraph loses root node at exporting to svg, png and etc.

### ISSUE THREAD

**Issue by artzub** [highcharts/highcharts#19552]
Good day!
Found that we lose root node at exporting to SVG, png if data is updated by both `series.setData` or `series.update`.
We have a chart with dynamically adding data [here](https://jsfiddle.net/0d8akt72/9/)

#### Expected behaviour
Expect to have a similar tree in the exported png.
![image](https://github.com/highcharts/highcharts/assets/134249/748acd28-b055-416e-b8ff-b600b39142fc)

#### Actual behaviour
Currently, the chart loses the root node at exporting to SVG or png and we have this result:
![image](https://github.com/highcharts/highcharts/assets/134249/42d27e18-e329-4f9a-b59f-54a3f0cdbeb6)

#### Live demo with steps to reproduce
https://jsfiddle.net/0d8akt72/9/

#### Product version
Highcharts: 11.1.0

#### Workaround
I did some research and found that the chart use `series.userOptions.data` in `getSVG` method.
And figured out that the collection `series.userOptions.data` is broken. Possible, it is related with [this bug](https://github.com/highcharts/highcharts/issues/19524).
But I made a workaround that fixes exporting:
```javascript
const getSVG = (H) => {
  H.wrap(H.Chart.prototype, 'getSVG', function (proceed, chartOptions) {
    this.series.forEach((series) => {
      if (series.type !== 'treegraph') {
        return;
      }

      series.userOptions.data = series.data.map((point) => ({
        ...point.options,
      }));
    });
    return proceed.call(this, chartOptions);
  });
};
```

You can uncomment a line with using the workaround in the above link or use this [link](https://jsfiddle.net/0d8akt72/10/)

**Comment by karolkolodziej** [comment]
Hi @artzub!
Thank you for investigating this and for the workaround it seems very accurate!
