### ISSUE TITLE
Drawing candlestick shadows

### ISSUE THREAD

**Issue by gashik1979** [highcharts/highcharts#19550]
In the Plot Options for the candlestick chart, there is an "upColor" property for the color of an "up" candle (when the close is higher than the open) and a "color" property for the body of the candle. However, there is no separate property for configuring the color of the candle's shadow. The "lineColor" property changes both the border color around the body and the shadow color simultaneously. Unfortunately, you cannot customize them separately.

For instance, you can use the default value "#000" for "lineColor," and on a white background, it might look nice. But if you change the background color to black and make "lineColor" white, it won't look aesthetically pleasing. 
As an example [https://prnt.sc/JWxVfsPDt3vV](url), it could be desirable to remove the border around the candle's body and make the shadows white, which would create an appealing look. However, the current settings do not allow for this customization.

**Comment by gashik1979** [comment]
Yes, sure, take a look at an example of another chart at the following link: [https://tvjsx.github.io/trading-vue-demo/](url). Here, the background is dark and the shadows of the candles match the color of the candle itself.

**Comment by karolkolodziej** [comment]
Aaaah! You meant the upper and lower wick!
There is a way to change that through [upLineColor](https://api.highcharts.com/highstock/series.candlestick.upLineColor) and [lineColor](https://api.highcharts.com/highstock/series.candlestick.lineColor)- [demo](https://jsfiddle.net/BlackLabel/ch5a09nq/).

Is that what you've been looking for?

**Comment by pawelfus** [comment]
Documentation updated 🎉
