### ISSUE TITLE
Incorrect map color pattern display

### ISSUE THREAD

**Issue by KamilKubik** [highcharts/highcharts#19551]
#### Expected behaviour
1. GeoJSON format:
- Pattern should be displayed.

2. TopoJSON format:
- Pattern shouldn't be overscaled.

#### Actual behaviour
1. GeoJSON format:
- Pattern is displayed as a normal color (no pattern visible). Looks like **regression** - works on v8.

2. TopoJSON format:
- Pattern is displayed but is overscaled.

#### Live demo with steps to reproduce
1. GeoJSON format:
- https://jsfiddle.net/BlackLabel/ox4dwqtb/

2. TopoJSON format:
- https://jsfiddle.net/BlackLabel/e6nxutbo/

#### Product version

Highmaps JS v11.1.0

**Comment by karolkolodziej** [comment]
Last working version 9.2.2
