### ISSUE TITLE
Cannot create sankey chart

### ISSUE THREAD

**Issue by aryanbhatt-clvt** [highcharts/highcharts#19564]
import React from 'react';
import Highcharts from 'highcharts';
import ReactHighcharts from 'react-highcharts';
import highchartsMore from 'highcharts/highcharts-more';
highchartsMore(Highcharts);

class SankeyChart extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            isAnimationActive: true,
        };
    };
    componentDidMount() {
        console.log("---------------------------------------------MOUNTED-------------------------------------------");
        {
            Highcharts.chart('sankey-div', {

                chart: {
                    type: "sankey",
                    renderTo: "sankey-div",
                    showAxes: true
                },
                xAxis: {
                    type: 'datetime',
                    /* tickPositions: [Date.UTC(2022, 2, 1), Date.UTC(2022, 2, 8), Date.UTC(2022, 2, 15)] */
                },
                series: [{
                    keys: ['from', 'to', 'weight', 'color'],
                    colors: ["#5E33BF",  "#5E33BF",  "#5E33BF", "#5E33BF",
                                    "#16AB03",  "#16AB03",  "#16AB03", "#16AB03",
                            "#5693F5",  "#5693F5",  "#5693F5", "#5693F5",
                            "#DD2C00",  "#DD2C00",  "#DD2C00", "#DD2C00"],
            
                data: [
                        ['Brand A', 'Brand A1', 10],
                        ['Brand A1', 'Brand A2', 7],
                        ['Brand A2', 'Brand A3', 4],
            
                        ['Brand B', 'Brand B1', 6],
                        ['Brand B1', 'Brand B2', 5],
                        ['Brand B2', 'Brand B3', 4],
            
                        ['Brand C', 'Brand C1', 5],
                        ['Brand C1', 'Brand C2', 3],
                        ['Brand C2', 'Brand C3', 2],
                        
                        ['Brand A', 'Brand B1', 1],
                        ['Brand A', 'Brand C1', 1],
                        ['Brand A', 'Dropped1', 1, "#DD2C00"],
            
                        ['Brand B', 'Dropped1', 1],
                        
                        ['Brand C', 'Brand A1', 2],
                        ['Brand C', 'Dropped1', 1, "#DD2C00"],
            
                        ['Brand A1', 'Dropped2', 1],
                        
                        ['Brand B1', 'Brand A2', 1],
                        ['Brand B1', 'Brand C2', 1],
                        ['Brand B1', 'Dropped2', 1], "#DD2C00",
                        
                        ['Brand C1', 'Brand A2', 1],
                        ['Brand C1', 'Brand B2', 1],
                        ['Brand C1', 'Dropped2', 1, "#DD2C00"],
            
                        ['Brand A2', 'Brand B3', 1],
                        ['Brand A2', 'Brand C3', 1],
                        ['Brand A2', 'Dropped3', 1, "#DD2C00"],
            
                        ['Brand B2', 'Brand A3', 1],
                        ['Brand B2', 'Brand C3', 1],
                        ['Brand B2', 'Dropped3', 1, "#DD2C00"],
            
                        ['Brand C2', 'Brand A3', 1],
                        ['Brand C2', 'Brand B3', 1],
                        ['Brand C2', 'Dropped3', 1, "#DD2C00"],
            
            ],
                    type: "sankey",
                    name: 'Sankey demo series'
                }]
            
            })
        }
    }

    componentWillReceiveProps(nextProps) {
        if (this.props.data !== nextProps.data && !isEmpty(this.props.data)) {
          this.setState({
            isAnimationActive: true
          });
        }
    }

    render() {
        console.log("*&*&(*&*(&(*&(*&*(*&");
        console.log(this.props);
        console.log(this.state);

        return (
          <div id='sankey-div'>
          </div>
        )
    };
}

export default SankeyChart;

This is the code through which I am trying to create a sankey chart but the it gives #17 error which says:

**The requested series type does not exist
This error happens when setting chart.type or series.type to a series type that isn't defined in Highcharts. A typical reason may be that the module or extension where the series type is defined isn't included.

For example in order to create an arearange series, the highcharts-more.js file must be loaded.**

I have installed most of the libraries related like:
"highcharts"
"react-highcharts"
"highcharts-react-official"
"highcharts-more"

**Comment by bm64** [comment]
Hello @aryanbhatt-clvt 

As you can read in Highcharts API, the sankey module is required to create a sankey chart:
https://api.highcharts.com/highcharts/series.sankey

Here is a demo showing how to import and initialize the module: https://codesandbox.io/s/highcharts-react-demo-forked-xtfjc8

**Comment by aryanbhatt-clvt** [comment]
What if my data has 3 unique brands, instead of brand A1, A2, A3 I will have brand A only. Same goes for brand B and C. When I apply that data the sankey chart looks something else. Is there a way to achieve this ?

**Comment by bm64** [comment]
Hi @aryanbhatt-clvt 

We primarily use GitHub for feature requests and bug tracking. For technical questions like yours, please head over to our [other support channels](https://www.highcharts.com/blog/support/), such as our forum: https://www.highcharts.com/forum/
