### ISSUE TITLE
Chart is drawn twice when loaded below responsive threshold with chart.height option

### ISSUE THREAD

**Issue by LB0ge** [highcharts/highcharts#19569]
#### Expected behaviour

Chart should be drawn only once when using the `responsive` option and changing `chart.height`.

#### Actual behaviour

Chart is drawn twice on initial load/refresh when the responsive options are active.
Seems to be a bug related to changing `chart.height` in the responsive configuration.

#### Live demo with steps to reproduce

[demo link](https://jsfiddle.net/LB0ge/L5ps9vxm/) - instructions in subtitle

#### Product version
Highcharts JS v11.1.0 (2023-06-05)

#### Affected browser(s)

All

**Comment by karolkolodziej** [comment]
Internal note:
Regression which was introduced in `v11.0.0` with the `ResizeObserver`.

**Comment by TorsteinHonsi** [comment]
[Demo with logging of the render event](https://jsfiddle.net/highcharts/wtn5xus6/)

**Comment by TorsteinHonsi** [comment]
It's fixed in the master. Demo with the fix applied: https://jsfiddle.net/highcharts/j3y5hga0/
