### ISSUE TITLE
Pie-Chart PDF Export cropped and split on 2 pages

### ISSUE THREAD

**Issue by imtron** [highcharts/highcharts#1957]
When I export a pie chart as PDF, the chart is split on 2 pages and the right part is cropped. Is there a setting to fix this and get the whole chart on 1 page?

http://jsfiddle.net/2F4na/

thanks!

**Comment by Anderman** [comment]
Problem stil exists
[zou-u-deze-organisatie-a (2).pdf](https://github.com/highcharts/highcharts/files/3899043/zou-u-deze-organisatie-a.2.pdf)

**Comment by pawelfus** [comment]
Above reported in #12510 - this issues refers to the old exporting server.
