### ISSUE TITLE
Chart cannot render if renderTo target is inside shadow DOM

### ISSUE THREAD

**Issue by aditya3434** [highcharts/highcharts#19586]
#### Expected behaviour
Chart should render inside the div with the ID 'target' 

#### Actual behaviour
Chart does not render and returns an uncaught error
<img width="700" alt="image" src="https://github.com/highcharts/highcharts/assets/56246494/383d2fb8-ae5b-42d3-80ae-f0bbba90d7c7">

#### Live demo with steps to reproduce
HTML
```
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Chart DOM example</title>
  </head>
  <body>
    <section>
      <p>
        Chart DOM example
      </p>
      <div id='main'>
      </div>
    </section>
  </body>
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <script src="https://code.highcharts.com/modules/sankey.js"></script>
  <script src="https://code.highcharts.com/modules/exporting.js"></script>
</html>
```
JS
```
// Finding div with id 'main'
const main = document.getElementById('main');

// Adding a shadow root inside 'main'
main.attachShadow({ mode: "open" });

// Adding 'target' div inside shadow root
const el = document.createElement('div');
el.id = 'target';
main.shadowRoot.appendChild(el);

// Rendering chart in 'target' div
Highcharts.chart({

    chart: {
        styledMode: true,
        renderTo: 'target'
    },

    title: {
        text: 'Styling data labels by CSS'
    },

    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr']
    },

    plotOptions: {
        series: {
            dataLabels: {
                enabled: true,
                borderRadius: 2,
                y: -10,
                shape: 'callout'
            }
        }
    },

    series: [{
        data: [{
            y: 100,
            dataLabels: {
                align: 'right',
                rotation: 45,
                shape: null
            }
        }, {
            y: 300
        }, {
            y: 500,
            dataLabels: {
                className: 'highlight'
            }
        }, {
            y: 400
        }]
    }]

});
```
CSS
```
@import "https://code.highcharts.com/css/highcharts.css";

#container {
    height: 400px;
    min-width: 300px;
    max-width: 800px;
    margin: 0 auto;
}

.highcharts-data-label-box {
    fill: #a4edba;
    stroke: gray;
    stroke-width: 1px;
}

.highcharts-data-label {
    font-weight: normal;
}

.highlight .highcharts-data-label-box {
    fill: red;
    stroke-width: 2px;
    stroke: black;
}

.highlight.highcharts-data-label text {
    font-weight: bold;
    fill: white;
}

```

#### Product version
Latest

#### Affected browser(s)
All

**Comment by mccahan** [comment]
When you pass in a string to `renderTo`, it runs `document.getElementById` which can't see into a shadow DOM.

You have a direct reference to the element in `el`, so you can justdo `renderTo: el` to pass the element directly, a la:

```js
// Finding div with id 'main'
const main = document.getElementById('main');

// Adding a shadow root inside 'main'
main.attachShadow({ mode: "open" });

// Adding 'target' div inside shadow root
const el = document.createElement('div');
el.id = 'target';
main.shadowRoot.appendChild(el);

// Rendering chart in 'target' div
Highcharts.chart({

    chart: {
        styledMode: true,
        renderTo: el,
    },

    title: {
        text: 'Styling data labels by CSS'
    },

    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr']
    },

    plotOptions: {
        series: {
            dataLabels: {
                enabled: true,
                borderRadius: 2,
                y: -10,
                shape: 'callout'
            }
        }
    },

    series: [{
        data: [{
            y: 100,
            dataLabels: {
                align: 'right',
                rotation: 45,
                shape: null
            }
        }, {
            y: 300
        }, {
            y: 500,
            dataLabels: {
                className: 'highlight'
            }
        }, {
            y: 400
        }]
    }]

});
```

**Comment by aditya3434** [comment]
> When you pass in a string to `renderTo`, it runs `document.getElementById` which can't see into a shadow DOM.
> 
> You have a direct reference to the element in `el`, so you can just do `renderTo: el` to pass the element directly, a la:
> 
> ```js
> // Finding div with id 'main'
> const main = document.getElementById('main');
> 
> // Adding a shadow root inside 'main'
> main.attachShadow({ mode: "open" });
> 
> // Adding 'target' div inside shadow root
> const el = document.createElement('div');
> el.id = 'target';
> main.shadowRoot.appendChild(el);
> 
> // Rendering chart in 'target' div
> Highcharts.chart({
> 
>     chart: {
>         styledMode: true,
>         renderTo: el,
>     },
> 
>     title: {
>         text: 'Styling data labels by CSS'
>     },
> 
>     xAxis: {
>         categories: ['Jan', 'Feb', 'Mar', 'Apr']
>     },
> 
>     plotOptions: {
>         series: {
>             dataLabels: {
>                 enabled: true,
>                 borderRadius: 2,
>                 y: -10,
>                 shape: 'callout'
>             }
>         }
>     },
> 
>     series: [{
>         data: [{
>             y: 100,
>             dataLabels: {
>                 align: 'right',
>                 rotation: 45,
>                 shape: null
>             }
>         }, {
>             y: 300
>         }, {
>             y: 500,
>             dataLabels: {
>                 className: 'highlight'
>             }
>         }, {
>             y: 400
>         }]
>     }]
> 
> });
> ```

Thanks Ryan! That worked. Closing this issue now.
