### ISSUE TITLE
Import mouse-wheel-zoom module not working with Highcharts Vue 3

### ISSUE THREAD

**Issue by aroylachance** [highcharts/highcharts#19582]
#### Expected behaviour
I can import the highcharts module mouse-wheel-zoom like so in my main.ts file:

import Highcharts from "highcharts";
import MouseWheelZoom from 'highcharts/modules/mouse-wheel-zoom'

MouseWheelZoom(Highcharts)

#### Actual behaviour
 the MouseWheelZoom import returns an error saying the module declaration can not be find and when I try to implement the mouse-wheel-zoom on my highcharts timeline chart it doesn't work.
I was able to make the mouse wheel zoom work on a timeline chart in this jsfiddle: https://jsfiddle.net/s374tycn/1/ (it seems to work fine when importing the module with a script directive)

#### Product version
Highcharts 11.1.0

**Comment by karolkolodziej** [comment]
We are in the middle of the vacation season thus I would expect a new release within a couple of weeks.
