### ISSUE TITLE
Nightly builds lagging 10 months behind

### ISSUE THREAD

**Issue by mccahan** [highcharts/highcharts#19588]
#### Expected behaviour

Should see regular builds at https://github.com/highcharts/highcharts-dist/tree/nightly, as mentioned in the docs at https://www.highcharts.com/docs/getting-started/install-from-npm#installing-nightly-builds-of-highcharts

#### Actual behaviour

Most recent commit to the branch was in December 2022.

#### Potentially-Related Issue

FYI, a user put in issue #18427 referencing a local build issue and the nightly issue, suggesting a connection. I do have a PR in https://github.com/highcharts/highcharts/pull/19587 to try to fix the local build issue, and if that user is correct it might magically fix the nightlies?

In a rare cosmic alignment event, 4 days ago[ a commit](https://github.com/highcharts/highcharts/commit/6683d0f72c17acaa85878299094b553702e04b7b) for a feature I need for a project I started building yesterday is in main, and I was having trouble getting it running anywhere without a nightly build or a functional local build.

Thanks!

**Comment by karolkolodziej** [comment]
Hi @mccahan! 

Thank you for the PR! Within a day, when everything goes live, we should know if it solves the issue with nightly builds.
In the meantime maybe @goransle has some insight knowledge and can tell if it's going to be sufficient?

**Comment by goransle** [comment]
> Hi @mccahan!
> 
> Thank you for the PR! Within a day, when everything goes live, we should know if it solves the issue with nightly builds. In the meantime maybe @goransle has some insight knowledge and can tell if it's going to be sufficient?

I went ahead and did a manual run-through of the workflow, and it looks like the fix is working. The nightly branch should now be up to date.

**Comment by karolkolodziej** [comment]
I'm going to close it for now. If you encounter any issues with it, feel free to reopen 😉

**Comment by mccahan** [comment]
Hi @karolkolodziej heads up, it appears the nightly builds still aren't occurring. The last build in the nightly branch is the manual one from @goransle. If there's a log somewhere of the failing process I'm happy to take a look and PR a fix if it's a code problem, I assume there's something on the CircleCI end?

**Comment by goransle** [comment]
> Hi @karolkolodziej heads up, it appears the nightly builds still aren't occurring. The last build in the nightly branch is the manual one from @goransle. If there's a log somewhere of the failing process I'm happy to take a look and PR a fix if it's a code problem, I assume there's something on the CircleCI end?

Thanks for the heads up. Looks like one of our build scripts (`scripts-compile`) is timing out in CircleCI. We will look into a solution.

**Comment by goransle** [comment]
After some coercion the automated nightly build is back on the [highcharts-dist](https://github.com/highcharts/highcharts-dist/tree/nightly) repo. Closing again.
