### ISSUE TITLE
[Question] Support for interactively add annotations (text), lines and shapes through a UI

### ISSUE THREAD

**Issue by nishikantparmariam** [highcharts/highcharts#19589]
Hi,
Posting this as a question, I saw that highstock has a nice GUI tool to interactively add annotations, shapes etc. - https://www.highcharts.com/demo/stock/stock-tools-gui.  (Q1 - Is there a similar GUI tool available for highchart as well?)

I also saw this plugin - http://blacklabel.github.io/annotations/ which I believe was there when annotation was not supported in highcharts. This plugin also allows to add new annotation / shapes (line, rectangle, circles) interactively through a GUI. (Q2 - Is there support for such GUI in the annotations module)

My use-case is that I want to build a GUI (simpler than highstocks GUI) that allows users to add annotations on the Chart and edit them. (Q3 - Should I write a plugin myself for building that UI (similar to above) and use the APIs provided by annotations module?)

Thanks a lot!

**Comment by karolkolodziej** [comment]
Hi @nishikantparmariam! 

1. Yes, it is possible. You only need to prepare the HTML with certain classes to get functionalities as they are in the Stock Tools- [demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/annotations/gui-buttons/).

2. That is a rather old module, now everything should be included in the official Highcharts annotation module. See the point above.

3. If you like the functionalities from the Stock Tools you don't have to. But if you need to make it more customizable, you will need to write your own version. You can [use binding ](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/annotations/bindings/)or even create your [own annotations.](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/annotations/bindings-custom-annotation/)

For future reference, we're using GH as a bug/feature tracking tool. With questions like this, please use[ available support channels.](https://www.highcharts.com/blog/support/)
