### ISSUE TITLE
Property `forExport` still not visible in the TypeScript declaration of `SVGRenderer`

### ISSUE THREAD

**Issue by emilefokkema** [highcharts/highcharts#19606]
#### Expected behaviour

For the property [`forExport`](https://github.com/highcharts/highcharts/blob/063e4643872af29c7cf7299587b3d287e710eac9/ts/Core/Renderer/SVG/SVGRenderer.ts#L208) to be visible on the TypeScript declaration for the class `SVGRenderer`

#### Actual behaviour

It is still not visible, despite #19578

#### Product version
highcharts 11.1.0

**Comment by karolkolodziej** [comment]
Hi @emilefokkema! 

Your PR was merged to the `master` brunch but it wasn't released yet.
That is the reason why you don't see any changes.

We are anticipating that the next release should be within a couple of weeks.

**Comment by emilefokkema** [comment]
@karolkolodziej No, the reason I don't see any changes is that my change in #19578 was not correct. I ran the build and saw that the desired change did not appear in the .d.ts files. #19607 is really needed to actually see the desired change in the .d.ts.

**Comment by emilefokkema** [comment]
@karolkolodziej Will you re-open this issue, or shall I create a new issue?
