### ISSUE TITLE
Disappearing breadcrumbs after setting the update flag to true

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#19616]
#### Actual behaviour
Breadcrumbs disappear after calling the chart update method.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/jtq1yaz3/

Click on the Level 2.2 node.
Click the button.
Watch how breadcrumbs disappear.

#### Product version
HC + Sunburst 11.1.0

**Comment by jakubjanuchta** [comment]
I wanted to check how does updating the chart affect other series with drilldown and I got interesting results. 

In `column with drilldown`, when you update the data after the drilldown, the breadcrumbs are intact, but the chart is updated and the new data is shown (which means that the breadcrumbs are totally misaligned with the data), see [demo](https://jsfiddle.net/BlackLabel/6somg85u/). 
To reproduce - drill down and click any of the buttons.
<img width="602" alt="image" src="https://github.com/highcharts/highcharts/assets/47400438/1accd507-e1e8-4736-82dc-0fa12c45e56f">

Moreover, on `pie with drilldown` series when we drill down, than update the chart with new data, the breadcrumbs are still intact and missaligned with the data, but if we drilldown once more after that, the pie's are drawn on each other breaking the chart, see [demo](https://jsfiddle.net/BlackLabel/vmgz432s/)

<img width="639" alt="image" src="https://github.com/highcharts/highcharts/assets/47400438/a2c4ceb8-87a4-41e5-8706-a4bdd706d882">

I think we should implement the same breadcrumbs behavior for all the drilldown series and I believe the breadcrumbs should disappear after updating the data and the series should be brought back to it's initial state before drilldown (no matter if we update with different data or the same one). 

What do you think about that @TorsteinHonsi?  If you agree, should I implement it along with this ticket or should I create another one?
