### ISSUE TITLE
property `forExport` on class `SVGRenderer` is not included in the generated .d.ts files

### ISSUE THREAD

**Issue by emilefokkema** [highcharts/highcharts#19612]
#### Expected behaviour

If I check out the code and run `npm run build`, I expect the property `forExport` of the class `SVGRenderer` to be present in the generated `code/highcharts.d.ts` file.

#### Actual behaviour

It is not.

#### Product version
Highcharts, latest.

#### Additional remarks

An attempt was made to fix this issue in #19578 , but the build output could not be checked. However, since [this commit](https://github.com/highcharts/highcharts/commit/f17638d273f121df92aab387445e038e1c8430d4), the build output could be checked. It now appeared that #19578 had not fixed the issue.

**Comment by karolkolodziej** [comment]
Apologies for the previous misunderstanding! 
Right now your PR linked to this issue looks correct 😉
