### ISSUE TITLE
Column color in drill down chart changes on drillup to top level

### ISSUE THREAD

**Issue by tillhaug** [highcharts/highcharts#19610]
#### Expected behaviour
Colors of the column the same that they initially were (works in 9.1.0, see jsfiddle) 

#### Actual behaviour
Colors change when drilling up again 

#### Live demo with steps to reproduce
Highcharts 9.1.0 working:
https://jsfiddle.net/2rsqzpt6/

Highcharts 11.1.0 not working:
https://jsfiddle.net/2rsqzpt6/1/

1) Click "Animals" Colum
2) Go back to top level 

#### Product version
Highcharts 9.1.0 - working
Highcharts 11.1.0 - not working

#### Affected browser(s)
Chrome v115

**Comment by jakubjanuchta** [comment]
This issue has been fixed by #19134. 

Working demo from master branch: https://jsfiddle.net/BlackLabel/4cfpatnb/
