### ISSUE TITLE
Highstock GUI element - spacebar prohibited in annotation label text

### ISSUE THREAD

**Issue by futuresfirstenergy** [highcharts/highcharts#19632]
#### Expected behaviour
Pressing spacebar should give space between two words in the text field of the annotation label text

#### Actual behaviour
Spacebar isn't recognized

#### Live demo with steps to reproduce
Use the demo of highstocks with GUI tools https://www.highcharts.com/demo/stock/stock-tools-gui

#### Product version
Highcharts-Stock-11.1.0

#### Affected browser(s)
All browsers.

When i looked at event listeners, removing the KEYDOWN event listener on that field which points to accessibility.src.js 3060 line - the spacebar pressing is recognised. Otherwise, spacebar pressing doesn't insert a space in the text.

**Comment by bm64** [comment]
Hello @futuresfirstenergy and thanks for reporting.

Looks like the issue occurs only if the annotation module is loaded used to work correctly in v8.0.0.
