### ISSUE TITLE
Gantt Chart grid column headers don't display correctly sometimes when there are only 1 or sometimes 2 rows

### ISSUE THREAD

**Issue by scottjreece** [highcharts/highcharts#19657]
#### Expected behaviour
Column headers should display correctly and consistently whether there is 1 row or 1000 rows

#### Actual behaviour
When there is only 1 row, and sometimes 2 or 3 rows, the column headers wrap when they shouldn't or go to ellipsis too early in the string. It appears that the code that tells the column headers how much room they have is telling them that they have much less horizontal space than they actually do.

#### Live demo with steps to reproduce
This example demonstrates the bug with 1 row: 
https://jsfiddle.net/vjrxkbhd/2/

This particular example works correctly with 2 rows that are identical to the rows in the previous example, so we can rule out changes due to the data itself: 
https://jsfiddle.net/vjrxkbhd/4/

#### Product version
Highcharts (version not specified in script tags, so latest is assumed)

#### Affected browser(s)
Chrome, Firefox, Edge, and maybe more

**Comment by bm64** [comment]
Hello @scottjreece and thanks for reporting the issue 

Looks like it used to work better in v7.0.3: https://jsfiddle.net/BlackLabel/9fz6u1dq/

**Comment by scottjreece** [comment]
Hello @bm64 , is there a timeline on this issue getting fixed in the latest version of Highcharts?

**Comment by TorsteinHonsi** [comment]
Sorry for the silence @scottjreece, I'll have a look tomorrow.
