### ISSUE TITLE
Enhancement request: percentage-based axis height (or beforeRender event)

### ISSUE THREAD

**Issue by jacobweber** [highcharts/highcharts#1966]
If you have multiple series stacked along the Y axis, it doesn't seem to be possible to define their height in terms of a percentage of the total chart height. You have to define them in pixels, which is not very useful when the chart is set to automatically reflow to its container's size.

It would be nice if you could use either absolute or relative height measurements. But if not, it would help to have an event that fires before the chart is rendered. That way you could calculate the heights in pixels yourself, relative to the updated chart height, and resize the axes accordingly. Right now, the events are all fired after rendering, so you have to render it again after changing the axes.

**Comment by shedali** [comment]
The chart seems to render the same without the resizer code, am I missing something?
