### ISSUE TITLE
mapView.setView called by drillUp method doesn't work when chart.width is set

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#19676]
#### Expected behaviour
Map view should fit to natural bounds after setting zoom to 1
https://jsfiddle.net/BlackLabel/sntrzbg1/

FYI @hubertkozik - It probably has something to do with drilldown animation

#### Product version
Maps 11.1.0

**Comment by KacperMadej** [comment]
**Workaround**: https://jsfiddle.net/BlackLabel/sntrzbg1/2/

**More context**:
The original problem is when drilling up on a map and going to a chart with the width less than the height.
Demo: https://jsfiddle.net/BlackLabel/8Lrv2bfh/1/
Steps: click Europe > drill up via the breadcrumbs > the world map doesn't show fully

**Comment by TorsteinHonsi** [comment]
Maybe I misunderstand something, but the OP behaviour seems correct to me? We are starting with no center and no zoom, so the view is adapted to the natural bounds. Then in the timeout we run `setView` with an undefined center point and an explicit zoom of 1. After which the chart correctly zooms to 1, leaving the center as it was. With logging: https://jsfiddle.net/highcharts/6kph7vbr/

**Comment by KacperMadej** [comment]
The real case found via tech support is the map drill-up. The demo in Kamil's top comment is a simplified example pointing toward the same function that runs in the `drilldown` module. The code runs as expected. The drill up results are not expected. The code in the `drilldown` module should be changed - probably to the code I suggested in the workaround but that should be tested.
