### ISSUE TITLE
Error management : threshold to zero on logarithmic axis.

### ISSUE THREAD

**Issue by guiann** [highcharts/highcharts#1968]
when using a zero value on the color threshold on logarithm axis
The line is not drawn and there is a strange error : 

Invalid value for <rect> attribute y="-Infinity" 

see it here : 
http://jsfiddle.net/zNWHj/1/

Whereas if we use 0 value on logarithm Axis I was used to receive the message :

Uncaught Highcharts error #10: www.highcharts.com/errors/10 
Can't plot zero or subzero values on a logarithmic axis.

**Comment by oysteinmoseng** [comment]
Still valid if setting negative threshold for log area: http://jsfiddle.net/zNWHj/4/
