### ISSUE TITLE
The `resetButton.position.x`/`resetButton.position.y` properties don't work

### ISSUE THREAD

**Issue by KamilKubik** [highcharts/highcharts#19700]
The issue is probably related to refactoring from an old/deprecated `resetZoomButton` property.

#### Expected behaviour
The `resetButton.position.x`/`resetButton.position.y` properties should position the reset zoom button.

#### Actual behaviour
The `resetButton.position.x`/`resetButton.position.y` properties don't position the reset zoom button.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/a0rm82h6/

#### Product version
v11.1.0

**Comment by karolkolodziej** [comment]
Thank you @KamilKubik for reporting the issue! 

Internal note:
The options are not correctly merged in `setZoomOptions` method:
https://github.com/highcharts/highcharts/blob/0a045faee69f61563ddbbefb86d435ec1975c667/ts/Core/Chart/Chart.ts#L404-L423

**Comment by KamilKubik** [comment]
I've investigated this more deeply, and it works fine on our current master version. It seems to be fixed [here](https://github.com/highcharts/highcharts/pull/18976). Could you take a look @karolkolodziej, and confirm? 😀

**Comment by karolkolodziej** [comment]
You are right it is already fixed on the master!
