### ISSUE TITLE
Boost + zoom: issues when scatter data is not sorted

### ISSUE THREAD

**Issue by jiigen3343** [highcharts/highcharts#19701]
#### Expected behaviour
the points are not rendered outside of the panel when the data is unsorted after you zoom

#### Actual behaviour
the points are rendered outside the panel after the zoom

#### Live demo with steps to reproduce
https://jsfiddle.net/39qynL0z/3/

zoom so that a few points are directly to the left of the zoom rectangle inside the area for the x scale for example:

![image](https://github.com/highcharts/highcharts/assets/47895516/4462560e-3316-4d37-a35a-8a42330f248d)

notice that points will be rendered to the left of the x scale event though they should be clipped.

if we sort the data by x values this issue goes away(in the example you can uncomment line 16 to see this)
this has significant performance issues as in production settings we are working with large data sets and many panels so the sort is very expensive.

#### Product version
I have tested it using the latest and 10.3.3

#### Affected browser(s)
chrome and safari both showed the issue have not tested other browsers

**Comment by karolkolodziej** [comment]
Hi @jiigen3343!

You are right sorting is one of the workarounds but it isn't ideal for a lot of applications.

There are a few similar issues reported about scatter in boost and limitation of this series.
Let me bring this and other issues to the team where we can talk about potential solutions.

**Comment by jiigen3343** [comment]
So I made a debug build and played around with this and found that the issue is here:

https://github.com/highcharts/highcharts/blob/8a242467029d7005341542c5bf6413a738ccdfd3/ts/Extensions/Boost/WGLRenderer.ts#L887

in the code you are using to set the isXInside, The issue you are facing is you are acting like you are rendering lines so you keep a point visible even if it is off the scale because you assume you need to connect it to a future/previous point (which is a nice optimization in the line case so not actually bad code btw). But in a scatterplot where we are just doing points this logic works against us, you should render the current point if it is in range and not look at any other points. 

overall that tight loop is attempting to handle a lot of the rendering modes causing some cross work where work for some rendering modes is bleeding into others from what I am seeing in my debug runs.

**Comment by karolkolodziej** [comment]
Thank you for the input! You are right this loop is suboptimal for the scatter series.
But for now, I don't see any easy workarounds.
