### ISSUE TITLE
`dataSorting` and `dataGrouping` options make updating series impossible.

### ISSUE THREAD

**Issue by Vazonik** [highcharts/highcharts#19715]
#### Expected behaviour
While `dataSorting` and `dataGrouping` are enabled, the `update` method for the chart and series works correctly.

#### Actual behaviour
While `dataSorting` and `dataGrouping` are enabled, the `chart.update` and `series.update` methods cause the series to not be displayed.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/tg27y3q4/

#### Product version
Highcharts v11.1.0

**Comment by nishikantparmariam** [comment]
Cross linking where it was reported for reference: https://www.highcharts.com/forum/viewtopic.php?f=9&t=51357#p188407

**Comment by karolkolodziej** [comment]
Internal note:
It looks like the `update` doesn't trigger the `sortData` method.
As a workaround, you can use the `setData` to update your series' data- [demo](https://jsfiddle.net/BlackLabel/5d8nwkhx/).
