### ISSUE TITLE
WordCloud does not work with drilldown

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#19725]
#### Actual behaviour
The `Wordcloud` series does not work with drilldown. After drilling up with breadcrumbs, the parent series is not displayed as it initially was (specifically - the yAxis labels are missing). 

#### Live demo with steps to reproduce
**Demo:** https://jsfiddle.net/BlackLabel/h51a7yw4/2/

#### Product version
Highcharts 11

#### Affected browser(s)
Chrome, probably all?

**Comment by hubertkozik** [comment]
Hi!
I have prepared a workaround for that issue. You can check it in the demo below. If you want to use it in your project now, just copy-paste the IIFE function with the plugin.

**Live demo:** https://jsfiddle.net/BlackLabel/4b2f0tko/

A similar solution will be used in the Wordcloud series code.
