### ISSUE TITLE
HighStock scollbar can't work properly

### ISSUE THREAD

**Issue by hochunang** [highcharts/highcharts#19735]
https://github.com/highcharts/highcharts/assets/54022779/8f5fca44-03c6-4dbd-bf5b-06daca4c88e9

const config = {
        chart: {
          zoomType:'x',
        },
        rangeSelector: {
          enabled: false,
        },
        title: {
          text: 'Warp Convex Concave'
        },
        xAxis: {
          // labels: {
          //   rotation: 270
          // },
          type: 'datetime'
        },
        tooltip: {
          shared: true,
          crosshairs: true,
        },
        series: null,
      };
this.WarpChart = Highcharts.stockChart('WarpChart', config);

const newSeriesOptions1 = {
  name: this.chartOptionsWarpConvexConcave.series[0].name,
  type: 'line',
  data: url3.warpConvex
};
const newSeriesOptions2 = {
  name: this.chartOptionsWarpConvexConcave.series[1].name,
  type: 'line',
  data: url3.warpConcave
};
this.WarpChart.addSeries(newSeriesOptions1);
this.WarpChart.addSeries(newSeriesOptions2);
this.WarpChart.redraw();

**Comment by hochunang** [comment]
way to reproduce https://jsfiddle.net/hochunang/fhL94ju3/3/

> highchart.scrollbar.mp4 
> const config = { chart: { zoomType:'x', }, rangeSelector: { enabled: false, }, title: { text: 'Warp Convex Concave' }, xAxis: { // labels: { // rotation: 270 // }, type: 'datetime' }, tooltip: { shared: true, crosshairs: true, }, series: null, }; this.WarpChart = Highcharts.stockChart('WarpChart', config);
> 
> const newSeriesOptions1 = { name: this.chartOptionsWarpConvexConcave.series[0].name, type: 'line', data: url3.warpConvex }; const newSeriesOptions2 = { name: this.chartOptionsWarpConvexConcave.series[1].name, type: 'line', data: url3.warpConcave }; this.WarpChart.addSeries(newSeriesOptions1); this.WarpChart.addSeries(newSeriesOptions2); this.WarpChart.redraw();

**Comment by kamil-musialowski** [comment]
Hi there, thank you for reaching out to us.

As you can see in your demo, there is an Error #15, which indicates that your data is not sorted.
Once you apply the sorted data to your demo, then scrolling works fine: https://jsfiddle.net/BlackLabel/cz5nu7dt/

**Comment by hochunang** [comment]
thank you
