### ISSUE TITLE
Center In Category + Inverted chart displays series in reverse

### ISSUE THREAD

**Issue by camcarley** [highcharts/highcharts#19730]
#### Expected behaviour
Independent of settings, series should be shown in the order of series added.

#### Actual behaviour
With inverted chart enabled, categories are shown in the correct order (ex series 1,2,3) but when 'centerInCategory' is enabled in an inverted chart, series are displayed in the opposite order (3,2,1). 

#### Live demo with steps to reproduce
1) Navigate to https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series-column/centerincategory/ , note on page load, series are displayed in the correct order 
2) Enable 'inverted' under the chart settings, and press 'Run'
The series will now be displayed in the incorrect order.

#### Product version
Highcharts v11.1.0

#### Affected browser(s)
All.

**Comment by bm64** [comment]
Hello @camcarley and thanks for reporting the issue
