### ISSUE TITLE
Zoom / Pinch out issue in Mobile browser with candlestick chart with multiple series

### ISSUE THREAD

**Issue by krupali-clavier** [highcharts/highcharts#19745]
#### Expected behaviour
We're using multiple types of charts in the same chart simultaneously. Here, the details are as follows:
- Candlestick, Lines, Column, Scatter plot, Plotlines.
All chart is working well with web-browser but not with mobile. specially for pinch out

#### Actual behaviour
   Chart view is messed when we tried to pinchout

#### Live demo with steps to reproduce
https://jsfiddle.net/qtyf5aso/1/

#### Product version
Lastest version

#### Affected browser(s)
Chrome, safari

https://github.com/highcharts/highcharts/assets/140229103/22e5f9cb-f17d-43ca-abbc-8c5748abf3f0

**Comment by karolkolodziej** [comment]
Closing as a duplicate of #19728. Let's continue our discussion there 😉
