### ISSUE TITLE
Anchor position is moved twice when having a single group in dataGrouping mode 

### ISSUE THREAD

**Issue by Manizuca** [highcharts/highcharts#19742]
#### Expected behaviour
With the attached demo, that has groups configured for 2-hour periods, the groups should be positioned at:
anchor 'start': 00:00
anchor 'middle': 01:00
anchor 'end': 02:00

#### Actual behaviour
With the attached demo, the groups are positioned at:
anchor 'start': 00:00
anchor 'middle': 02:00
anchor 'end': 04:00

This is because the anchorPoints function from ts/Core/Axis/Axis.ts will make the the change twice, first on the firstAnchor condition, and then on the lastAnchor one.

#### Live demo with steps to reproduce
https://jsfiddle.net/qfaw4tsg/1/
- This is the official demo for the anchor property, with a single group and using columns for better visibility
- Each group is for a 2 hours period.

#### Product version
Highstock [v11.1.0](https://github.com/highcharts/highcharts/releases/tag/v11.1.0)

#### Affected browser(s)
*

**Comment by karolkolodziej** [comment]
Hi @Manizuca!

Thank you for reporting the issue! 
You are right when there is only one grouped point on the chart the anchors are applied twice- [demo](https://jsfiddle.net/BlackLabel/tspwxfr5/).

Internal note:
Adjust the method here:
https://github.com/highcharts/highcharts/blob/ba88c1cfe2dc1bb6edd2de0758b6ccc0fe1b1d97/ts/Extensions/DataGrouping/DataGroupingSeriesComposition.ts#L195
