### ISSUE TITLE
Bar with negative stack - negative dataLabels appearing on positive axis

### ISSUE THREAD

**Issue by phil-boilerhouse** [highcharts/highcharts#1976]
Here's a quick example to demo the issue.

The combination of a small canvas and mixing large and small numbers in the data causes the small negative values to appear on the positive axis.

http://jsfiddle.net/72ARx/

^ This shows -0.9 and 5 on top of each other looking like 50.9.

Increasing the canvas size fixes it (change 500 to 700) in the above example fixes it, but the chart is required to be shown in a small canvas for our client.

**Comment by oysteinmoseng** [comment]
Seems to be working as expected in current Highcharts.
