### ISSUE TITLE
Scale doesn't work for PDF offline exporting

### ISSUE THREAD

**Issue by hattn125** [highcharts/highcharts#19762]
#### Actual behaviour
When I use the offline-exporting module, I noticed that: the option `exporting.scale` didn't work for PDF type. The PDF file always has width/height same as parent container, without scale.
Other types (PNG/JPEG) works properly.

#### Expected behaviour
The option `exporting.scale` should work for PDF type in offine-exporting, same as other types.

#### Live demo with steps to reproduce
[https://jsfiddle.net/37zb2h68/9/](https://jsfiddle.net/37zb2h68/9/)

#### Product version
Highcharts 10.x

#### Affected browser(s)
All browsers

**Comment by karolkolodziej** [comment]
Hi @hattn125!
Thank you for reporting the issue!

If you use the external buttons and run the `exportChart` method you are able to export it with the scale- [demo](https://jsfiddle.net/BlackLabel/pg5tcz7o/).

**Comment by hattn125** [comment]
Hi @karolkolodziej! Thank for your reply!

But it still doesn't work for PDF type in your demo.

Reproduce steps: exporting PDF type with `scale = 1` and `scale = 3`. The PDF files are totally the same.

**Comment by karolkolodziej** [comment]
I've tested my demo and if you use buttons 1 and 2 you get:
<img width="251" alt="image" src="https://github.com/highcharts/highcharts/assets/57004120/6dbd8b3d-63a5-4025-87b8-7e202ac49832">
and
<img width="254" alt="image" src="https://github.com/highcharts/highcharts/assets/57004120/ccbeab01-760b-4211-99ab-a1671fa03875">

**Comment by hattn125** [comment]
Ah you're right! The scale works fine with `chart.exportChart` in your demo. But it used the Highchart server side export.

In my case, I want to use an offline export on client side (so no data sent to Highchart), then I tried `chart.exportChartLocal`, but it seems didn't work
[My new demo](https://jsfiddle.net/atf1Ldby/4/)

I'm appreciate your support, but can you check again?

**Comment by karolkolodziej** [comment]
You are right about the `exportChartLocal`. The scale isn't properly applied when using offline export.

As a workaround you can try to declare the [sourceWidth](https://api.highcharts.com/highcharts/exporting.sourceWidth) and [sourceHeight](https://api.highcharts.com/highcharts/exporting.sourceHeight)- [demo](https://jsfiddle.net/BlackLabel/uhnmo1zj/).
With that, you can sort of manually set the scale.

**Comment by hattn125** [comment]
Yes, sourceWidth and sourceHeight are good for workaround in my case at the moment :)

Just curious: do you think there is any chance that Highchart will fix it in an offical release, instead of such workaround?

**Comment by karolkolodziej** [comment]
Let me bring it to the team and we will see what we can do 😉 
We will keep you posted!
