### ISSUE TITLE
Tooltips not rendering consistently on line charts on Chrome

### ISSUE THREAD

**Issue by heyankitpatel** [highcharts/highcharts#19770]
#### Expected behaviour
Tooltips should be rendered on the line charts for all data points

#### Actual behaviour
Only certain indeterminate data points have the tooltips whereas other have it missing. As a test, I compared it against Safari (Version 16.6 (18615.3.12.11.2)) where it works as expected

#### Live demo with steps to reproduce
https://jsfiddle.net/43qvkou6/

#### Product version
highcharts@11.1.0

#### Affected browser(s)
Chrome Version 117.0.5938.62 (Official Build) (arm64)

**Comment by bm64** [comment]
Hello @heyankitpatel

Tested on Version 117.0.5938.88 (Official Build) (arm64), but couldn't recreate the issue. Is there any chance you could upgrade the version and see if it helps?

**Comment by heyankitpatel** [comment]
@bm64 Thanks for checking this. I too cannot reproduce this on the latest Chrome version (Version 117.0.5938.132 (Official Build) (arm64)) so looks like whatever incompatibility we had with tooltips is now resolved.
