### ISSUE TITLE
crosshair element is not presented in chart html for Vue3

### ISSUE THREAD

**Issue by broken-vagrant** [highcharts/highcharts#19788]
#### Expected behaviour
crosshair should be displayed like this [vue2 demo](https://yvqr7k.csb.app/), but with identical settings it's not being displayed in [Vue3](https://t2jhxj-5173.csb.app/).

#### Actual behaviour
Click on Vue2 demo link above.

#### Live demo with steps to reproduce
Vue3: https://codesandbox.io/p/sandbox/vue3-highcharts-crosshair-issue-repro-t2jhxj?file=/src/components/Chart.vue:141,17
Vue2.6: https://codesandbox.io/s/vue2-6-highcharts-crosshair-issue-repro-yvqr7k?file=/src/components/Chart.vue

#### Product version
10.3.3

#### Affected browser(s)
Chrome v117.0.5938.89

**Comment by jakubSzuminski** [comment]
Thanks for reporting @broken-vagrant!

This does not seem to be a Highcharts-related bug. The `Highcharts.Chart` instance should not be reactive; hence, there's no need to make `chart` a `ref` object. Once you change `chart` into a _non-reactive_ variable, everything seems to work as expected.

Here's a **demo:** https://codesandbox.io/p/sandbox/vue3-highcharts-crosshair-issue-repro-forked-cfnkjg?file=/src/components/Chart.vue:19,1
