### ISSUE TITLE
Offline Exporting: dataLabels are misaligned in PDF exports

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#19782]
#### Actual behaviour
[**Demo**](https://jsfiddle.net/BlackLabel/6kL9rnqo/) officially included in a Highcharts [**article**](https://www.highcharts.com/blog/news/247-introducing-offline-pdf-exporting/) exports a chart with `dataLabels` completely misaligned. 

#### Product version
Highcharts 11, Highcharts 10

#### Affected browser(s)
Chrome, all?

**Comment by goransle** [comment]
This seems to have been resolved by https://github.com/highcharts/highcharts/pull/19815. 

JSFiddle with current master: https://jsfiddle.net/goransle/uptbowhc/

Closing this for now.
