### ISSUE TITLE
Trendline functionality issue

### ISSUE THREAD

**Issue by Chehow** [highcharts/highcharts#19793]
#### Expected behaviour
Trendline is supposed to be a straight line but it's not. 

#### Actual behaviour
![image](https://github.com/highcharts/highcharts/assets/2310826/fb748de8-80be-4fd0-948f-c1c405d29344)

#### Live demo with steps to reproduce
https://jsfiddle.net/4cwobzrv/1

#### Product version
11.1.0 (It was ok in the 10.3.3)

#### Affected browser(s)
Any borwser

**Comment by KacperMadej** [comment]
Hi @Chehow 

Thank you for reporting the regression.

**Workaround**:
Use the previously working getValues logic from the older code version - demo: https://jsfiddle.net/BlackLabel/nryq94wo/

_Internal note:_
If the sorted data is used then it is easier to see duplicates for some x values e.g. for `x: 100.1`
![image](https://github.com/highcharts/highcharts/assets/8960408/aaeac92a-9884-4306-94ae-47c7c9d8e2bc).

Bisected to https://github.com/highcharts/highcharts/pull/18771 (FYI: @kamil-musialowski )

**Comment by pawelfus** [comment]
I am not convinced if this is a regression. The older version's trendline was not a straight line with this dataset: https://jsfiddle.net/BlackLabel/hn3tc4sb/

**Workaround**:
Demo: https://jsfiddle.net/BlackLabel/sa8r17gj/

Snippet:
```js
Highcharts.seriesTypes.trendline.prototype.getValues = function(series, params) {
  const xVal = series.xData,
    yVal = series.yData,
    LR = [],
    xData = [],
    yData = [],
    xValLength = xVal.length,
    index = params.index;
  let sumX = (xValLength - 1) * xValLength / 2,
    sumY = 0,
    sumXY = 0,
    sumX2 = ((xValLength - 1) * (xValLength) * (2 * xValLength - 1)) / 6,
    alpha, i, y;
  // Get sums:
  for (i = 0; i < xValLength; i++) {
    y = Highcharts.isArray(yVal[i]) ? yVal[i][index] : yVal[i];
    sumY += y;
    sumXY += i * y;
  }
  // Get slope and offset:
  alpha = (xValLength * sumXY - sumX * sumY) /
    (xValLength * sumX2 - sumX * sumX);
  if (isNaN(alpha)) {
    alpha = 0;
  }
  const beta = (sumY - alpha * sumX) / xValLength;
  // Calculate linear regression:

  const unique = [...new Set(xVal)];

  for (i = 0; i < unique.length; i++) {
    y = alpha * i + beta;
    // Prepare arrays required for getValues() method
    LR[i] = [unique[i], y];
    xData[i] = unique[i];
    yData[i] = y;
  }
  return {
    xData: xData,
    yData: yData,
    values: LR
  };
};
```

@Chehow - could you please test the workaround and let us know if you find any issues with it?

*Internal note:*
Workaround assumes the same calculation for `mx+b` params, just the way Points are created is different. We still have to validate the result of y-values on the chart.
