### ISSUE TITLE
chart size problem when parent container is set to display:none - JSFiddle included

### ISSUE THREAD

**Issue by akousari** [highcharts/highcharts#1979]
When the parent container is not visible (display:none) and a chart is rendered in a nested div (child of the invisible parent) the chart seems to overflow and take up the remaining width of the container. 

Imagine a two column container. The chart has to render on the first column (this column is not visible yet). Second column is visible. After the chart is drawn and shown it overflows to take the remaining width of the container (overflows to second col).  

See the following JSFiddle:
http://jsfiddle.net/akousari/duH9W/

Note: Affects both highcharts and highstock

**Comment by sebastianbochan** [comment]
Seems that reflow() is not called properly.

Example: http://jsfiddle.net/2qgpk3mL/5/

Steps to reproduce: 
1 - Click on *Resize *button
2 - *Slide *to the 2nd pane
3 - Change the *width *and *height *in textboxes and *Resize *
4 - *Slide *to the 1st pane (having chart) and you can see the chart having
inappropriate dimensions.

**Comment by blogcraft** [comment]
I have this issue with High Stock http://stackoverflow.com/questions/33506240/highstock-visual-distortion-multiple-charts
chart.reflow() doesn't seem to work for me.
