### ISSUE TITLE
Range selector week button weird behavior after using the scrollbar.

### ISSUE THREAD

**Issue by jakubjanuchta** [highcharts/highcharts#19808]
#### Expected behaviour
When clicking the week button, and scrolling with the scrollbar, the week button should remain active, as the range doesn't change.

#### Actual behaviour
When clicking the week button, and scrolling with the scrollbar, the week button doesn't remain active.

When I change the data range to a smaller one, at some point, the problem doesn't occur. Moreover, I noticed that even when I change the width of the chart, the result might change, see: 

https://github.com/highcharts/highcharts/assets/47400438/f999e071-8e98-4698-a5f2-cdee415d565f

When chart width is 800, everything works correctly, but when I change it to 700, we can see that the button doesn't remain active after scrolling. 

https://jsfiddle.net/BlackLabel/w9y1u8o0/

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/sp5fLr0g/

#### Product version
Highstock v11.1.0

#### Affected browser(s)
All

**Comment by bm64** [comment]
@jakubjanuchta thanks for reporting

Seems like it has been broken since v11.1.0. As a workaround disable ordinal feature: https://jsfiddle.net/BlackLabel/72beanc6/

**Comment by kamil-musialowski** [comment]
Broken by 8ec07ac
