### ISSUE TITLE
Trendline is not a straight line

### ISSUE THREAD

**Issue by K009** [highcharts/highcharts#19809]
#### Expected behaviour
Trendline should be a straight line.

#### Actual behaviour
Trendline is not a straight line.

#### Live demo with steps to reproduce
https://jsfiddle.net/4cwobzrv/1/

#### Product version
Highcharts v11.1.0

#### Affected browser(s)
All

**Comment by bm64** [comment]
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/19793
