### ISSUE TITLE
series.setData() seems that it mutates previous data

### ISSUE THREAD

**Issue by dev-song** [highcharts/highcharts#19818]
#### Expected behaviour
Changing highchart (stock) data using `series.setData(data)` shouldn't mutate previous data

#### Actual behaviour
`series.setData(data)` seems to mutate previous data (with new data input)

#### Live demo with steps to reproduce
[CodeSandbox](https://codesandbox.io/p/sandbox/highcharts-series-setdata-issue-reproduction-3m6khc)

#### Product version
Highcharts 10.3.3

#### Affected browser(s)
Google Chrome 117.0.5938.88
Microsoft Edge 117.0.2045.35

#### Additional
I found some forum answers related to this issue like below:
[Previous Highcharts forum topic #1](https://www.highcharts.com/forum/viewtopic.php?t=33250)
[Previous Highcharts forum topic #2](https://www.highcharts.com/forum/viewtopic.php?t=33282)

Is it intended that `series.setData()` mutates previous data?
It seems it can lead to unexpected hard-to-debug behaviors.

**Comment by bm64** [comment]
Hello @dev-song 

The behavior you're experiencing is intended for performance reasons. Highcharts doesn't copy the data by default; it keeps a reference to it, which can lead to the original data being mutated.

You can prevent this by setting the allowMutatingData property to false in your Highcharts series configuration. Keep in mind that this may decrease performance, particularly with larger data sets. [Try this demo](https://codesandbox.io/p/sandbox/highcharts-series-setdata-issue-reproduction-forked-zxgtz7?file=%2Fsrc%2Fmain.ts%3A19%2C36)

API reference: https://api.highcharts.com/highstock/chart.allowMutatingData
