### ISSUE TITLE
Zoom works incorrectly when adding points dynamically and various settings.

### ISSUE THREAD

**Issue by TheAngryByrd** [highcharts/highcharts#19816]
#### Expected behaviour

Zoom expands outside current visible range

#### Actual behaviour

Zoom stays within current visible range

#### Live demo with steps to reproduce

Code: https://jsfiddle.net/z72kench/3/

1. Go to the very right edge of the chart
2. Select `1m` (may have to do this multiple times seems like another bug here)
3. Notice the range selector is set to 1 months worth of data
4. Use the zoom feature to select the left part of the chart including the edge
5. See the range has changed to something far outside the original `1m` range

https://github.com/highcharts/highcharts/assets/1490044/bd88128d-75f9-40fe-b391-c2481bebc5d2

#### Product version

- Highstock JS v11.1.0 (2023-06-05)

#### Affected browser(s)

- Windows
  - Chrome
  - Firefox
  - Edge

**Comment by bm64** [comment]
Hi @TheAngryByrd and thanks for reporting the issue.

Workaround: disable `ordinal` feature: https://jsfiddle.net/BlackLabel/k0nxjqzL/

**Comment by TheAngryByrd** [comment]
> Hi @TheAngryByrd and thanks for reporting the issue.
> 
> Workaround: disable `ordinal` feature: https://jsfiddle.net/BlackLabel/k0nxjqzL/

Thank you for the response! While this work around does fix the zoom, it's not a viable solution for us since our users do rely on the `ordinal` being enabled.

**Comment by bm64** [comment]
@TheAngryByrd 

In that case this plug-in should help: https://jsfiddle.net/BlackLabel/y5xshfve/
Additionally the issue has been granted high priority so you can expect the fix fairly soon.

**Comment by TheAngryByrd** [comment]
👋 Thanks for fixing this! 

Just so I know, what's your release process like regarding stable releases and when should I expect one of them? Thank you!

**Comment by karolkolodziej** [comment]
Hi @TheAngryByrd! We are planning to release within a couple of weeks. It should be before the end of the year 😉

**Comment by TheAngryByrd** [comment]
Awesome, thank you!

**Comment by TheAngryByrd** [comment]
👋 Happy new year! Any word on when a release will be available?
