### ISSUE TITLE
Series with the same index overlap each other on a lollipop chart with the value inverted: true

### ISSUE THREAD

**Issue by AlexanderTkachuk** [highcharts/highcharts#19826]
#### Expected behaviour
In highcharts 10.0.0, a lollipop chart with the value inverted: true had indents between series with the same values.
For example, in series 1 there was data: [[0, 67]], in series 2 there was [[0, 55]]
But on the graph there was an indent between these two connectors

#### Actual behaviour
Now connectors overlap each other.

#### Live demo with steps to reproduce
https://jsfiddle.net/68bycojd/19/

#### Product version
Highcharts version 11.1.0

#### Affected browser(s)
All

**Comment by bm64** [comment]
Hello @AlexanderTkachuk and thanks for reporting the issue.

There were some changes to Lollipop series in v10.3.3. Before that, it was possible to adjust that behaviour with `grouping` option: https://jsfiddle.net/BlackLabel/px3e21nc/ I think it would be the best to still be able to choose, so I'm labeling it as regression.

**Comment by AlexanderTkachuk** [comment]
Hi @bm64. Agree with you. I saw new field like "grouping", but if we will update highcharts version in link to 11.1.0 and add grouping: true, than lollipop will break and will not be grouping . Is this expected?

https://jsfiddle.net/upq0e5oz/5/

<img width="1232" alt="Снимок экрана 2023-09-27 в 15 26 23" src="https://github.com/highcharts/highcharts/assets/36666147/3376e7fc-f761-4f1d-a1a6-40ce40e15466">
<img width="1232" alt="Снимок экрана 2023-09-27 в 15 26 58" src="https://github.com/highcharts/highcharts/assets/36666147/59986f4f-1447-48e0-ba94-9434edf3296f">

**Comment by bm64** [comment]
Hey @AlexanderTkachuk no, this is not expected. It used to work correctly back in v10.3.2, thats why I have labelled the issue as a regression and will be fixed.

**Comment by AlexanderTkachuk** [comment]
@bm64 thanks.
