### ISSUE TITLE
Incorrect zoom with wrong x-axis value when zooming multiple times

### ISSUE THREAD

**Issue by nishikantparmariam** [highcharts/highcharts#19828]
#### Expected behaviour
When multiple zooms are done, they should occur correctly and x-axis value should lie inside the zoom performed. 

#### Actual behaviour

(Open GIF in new tab for more clarity)

![chart-zoom-issue](https://github.com/highcharts/highcharts/assets/7736252/9e784876-bf69-4bb0-867f-f34c1d14653f)

#### Live demo with steps to reproduce
Demo - https://jsfiddle.net/skwqrd9L/3/

Steps - 
- Zoom from `1:00` to `6:30`
- Then, zoom from `1:15` to `2:45`
- Then, zoom from `1:14` to `1:18` 
 
Notice that x-values are wrong, they are from `00:50` to `01:10` whereas last zoom was from `01:14`. i.e. **none of the x-values lie in the range where last zoom happened**.

Let me know if there are quick workarounds to resolve this!

#### Product version
Highcharts v10.3.3

#### Affected browser(s)
Chrome 116.0.5845.188

**Comment by bm64** [comment]
Hello @nishikantparmariam 

The issue was fixed in v11.1.0: https://jsfiddle.net/BlackLabel/kvq2pw84/
If you can't upgrade to v11.1.0, disabling `ordinal` option should help: https://jsfiddle.net/BlackLabel/huLnfma5/

**Comment by nishikantparmariam** [comment]
Thanks! This works for us till we upgrade to v11.
