### ISSUE TITLE
fillOpacity not working

### ISSUE THREAD

**Issue by jacobweber** [highcharts/highcharts#1983]
[fillOpacity](http://api.highcharts.com/highstock#plotOptions.area.fillOpacity) doesn't seem to do anything on an area chart. Even if I set it to 0, I still can't see any of the lines behind the fill area. See [this example](http://jsfiddle.net/RkJuw/1/).

**Comment by matijaSos** [comment]
+1, please do so.

**Comment by jessegavin** [comment]
> Might want to note that in the docs.

Agreed

**Comment by highslide-software** [comment]
Done, thanks for pushing!
