### ISSUE TITLE
CSV export performance issue

### ISSUE THREAD

**Issue by KamilKubik** [highcharts/highcharts#19832]
#### Expected behaviour
The CSV export should be performed almost immediately.

#### Actual behaviour
The CSV export takes approximately 5-10 seconds.

#### Live demo with steps to reproduce
Stackblitz is the only editor, where we can run the newest HC version (11.1.0) and have that amount of data without lagging the whole editor. It probably needs more investigation, and maybe it's not because of the amount but a specific data set.

https://stackblitz.com/edit/js-u8a9rx?file=package.json,chart-options.js,index.js,index.html

#### Product version
Affected from: v10.3.0
Last working: v10.2.1

Bisected to: 426f0660927742380945314cba2494dca66d70b4

**Comment by sergei-lobanov** [comment]
Any updates on this issue?

**Comment by karolkolodziej** [comment]
Hi @sergei-lobanov! You can check the progress in the PR linked above.
We will do our best to include it in the upcoming release.

**Comment by sergei-lobanov** [comment]
<<Actual behaviour
The CSV export takes approximately 5-10 seconds.

On our production env it may take 1-2 minutes to export all data from the chart to csv and before it was immediately or a few seconds.
