### ISSUE TITLE
Gantt chart display issue

### ISSUE THREAD

**Issue by truejay** [highcharts/highcharts#19845]
#### Expected behaviour
Top left corner border line should align properly.
Last row label is vertically centered similar to rest of the labels.

#### Actual behaviour
Top left corner border line does not align properly.
Last row label is not vertically centered.

#### Live demo with steps to reproduce
https://jsfiddle.net/0kope62s/

#### Product version
highcharts/modules/gantt version 11.1.0

#### Affected browser(s)
All

**Comment by bm64** [comment]
Hello @truejay and thanks for reporting the issue.
