### ISSUE TITLE
Reset zoom buttons doesn't work with x and y values

### ISSUE THREAD

**Issue by AlexanderTkachuk** [highcharts/highcharts#19847]
#### Expected behaviour
I created chart and added zoom field. Added to zooming object type, singleTouch and resetButton fields. Described resetButton like
` zooming:{
     resetButton: {
         position: {
            align: 'right',
            verticalAlign: 'top',
            y: -37,
            x: 0,
        },
        theme: {
            height: 10,
            r: 15,
            class: 'highcharts-reset-zoom-button',
        },
    }
}`
If you rely on what is written in the documentation, then a button to reset the zoom should appear and it should be shifted up by 37 pixels.

#### Actual behaviour
The button is appeared on chart but x and y fields doesn't work and button isn't shifted up by 37 pixels.

### Details
If we describe reset zoom button with field resetZoomButton it will works correctly, but resetZoomButton is deprecated and in documetation talks that we should use zooming -> resetButton field

#### Live demo with steps to reproduce
https://jsfiddle.net/sr6zuhL1/13/

#### Product version
Highcharts versio  11.1.0

#### Affected browser(s)
All

**Comment by AlexanderTkachuk** [comment]
Ignore custom: {enabled: true} field. It does not affect on works.

**Comment by bm64** [comment]
Hi @AlexanderTkachuk and thanks for reporting the issue
