### ISSUE TITLE
on mobile, the page scrolls along with tooltip drag

### ISSUE THREAD

**Issue by anoosurf** [highcharts/highcharts#19843]
hi
when we slide our finger on a highchart on touch device.. the page also scrolls if we move up down slightly even on a column chart or line chart also .. we want the page to hold steady when moving finger over a chart. how to prevent the mouse event form being propagated to the main page
any setting on this ?

**Comment by bm64** [comment]
Hi @anoosurf,

We use GitHub strictly for feature requests and bug tracking. For technical support with questions, please visit one of our [support channels](https://www.highcharts.com/blog/support/), such as the [Highcharts Forum](https://www.highcharts.com/forum/). Don't forget to include a demo example when contacting us; our support engineers will gladly assist you.
