### ISSUE TITLE
Y-Axis shows duplicate labels when y-axis label format with decimal places and highest value is 1

### ISSUE THREAD

**Issue by teka23** [highcharts/highcharts#19859]
#### Expected behaviour

It shows only 1 tick and label.

#### Actual behaviour

It shows multiple ticks and labels on y-axis

<img width="753" alt="Screenshot 2023-10-02 at 7 58 51 PM" src="https://github.com/highcharts/highcharts/assets/7036343/dfb47746-9e3d-4e9c-b8eb-0c9da00d9faa">

#### Live demo with steps to reproduce
https://jsfiddle.net/q90adzn3/1/

#### Product version
Highcharts JS v11.1.0 (2023-06-05)

#### Affected browser(s)
Google Chrome, Safari etc.

**Comment by teka23** [comment]
Probably expected behaviour https://api.highcharts.com/highstock/yAxis.allowDecimals

**Comment by bm64** [comment]
Hello @teka23 

`format` option only formats existing labels, it doesn't affect in any way number of shown ticks / grid lines / labels. When it comes to the format, values seem to be rounded correctly. The effect you're looking for can be most likely achieved using `allowDecimals` or `tickInterval` options: https://jsfiddle.net/BlackLabel/2qwn5hsu/, https://jsfiddle.net/BlackLabel/dnmpfe10/

API reference: https://api.highcharts.com/highcharts/yAxis.allowDecimals,
https://api.highcharts.com/highcharts/yAxis.tickInterval
