### ISSUE TITLE
X Axis labels are not rendered on very specific widths, but on larger/smaller they do.

### ISSUE THREAD

**Issue by dragoshzava** [highcharts/highcharts#19857]
#### Expected behaviour
Render the labels.

#### Actual behaviour
Does not

#### Live demo with steps to reproduce
Does not display labels
https://jsfiddle.net/Resems/atb5vf8j/

Does display labels 
https://jsfiddle.net/Resems/atb5vf8j/1.
https://jsfiddle.net/Resems/atb5vf8j/2/

#### Product version
Latest , v11

#### Affected browser(s)
All

Any workaround for this?

**Comment by karolkolodziej** [comment]
Hi @dragoshzava!

Thank you for reporting the issue! 

_Internal note:_
If you remove the `autoRotation` it [works](https://jsfiddle.net/BlackLabel/wpfjzm2h/). 
When even an empty array is declared if [fails](https://jsfiddle.net/BlackLabel/hawegm8c/).

**Comment by jakubjanuchta** [comment]
I have prepared a workaround for that issue. If you want to use it in your project simply copy-paste the IIFE function from the below demo.

**Live demo:** https://jsfiddle.net/BlackLabel/ag4xq19j/
