### ISSUE TITLE
Variable-width columns are unevenly spaced

### ISSUE THREAD

**Issue by dancek** [highcharts/highcharts#1986]
The column spacing algorithm assumes that all columns are of equal width. This causes uneven spacing and occasional overlapping if columns of different widths are used.

See http://codepen.io/dancek/pen/Jztkm for an example.

Note that while groupPadding can be used as a workaround, it is quite unintuitive in this case.

**Comment by oysteinmoseng** [comment]
Highcharts 6 introduced Variwide charts that should take care of this issue https://www.highcharts.com/demo/variwide
