### ISSUE TITLE
Highsoft.Web.Mvc.Charts.XAxisPlotBandsEvents.Mousemove Doesn't DeSerialize correctly

### ISSUE THREAD

**Issue by asg-contractor** [highcharts/highcharts#19887]
#### Expected behaviour
"plotBands": [{
                "to": 0.5,
                "events": {
                    "Click": "",
                    "Mousemove": "",
                    "Mouseout": "",
                    **"Mouseover": alert('test'),**
                    "CustomFields": {}
                },
                "color": "#FF0000",
                "id": "1",
                "from": -1.0
            }

#### Actual behaviour
"plotBands": [{
                "to": 0.5,
                "events": {
                    "Click": "",
                    "Mousemove": "",
                    "Mouseout": "",
                    **"Mouseover": "alert('test')",**
                    "CustomFields": {}
                },
                "color": "#FF0000",
                "id": "1",
                "from": -1.0
            }

**Comment by brofixo** [comment]
It looks good to me in v11.1.0.2.
