### ISSUE TITLE
Heatmap wrong y axis visualization with categories and a lof of data

### ISSUE THREAD

**Issue by abidibo** [highcharts/highcharts#19881]
#### Expected behaviour
I would expect the yAxis of my heatmap to just include the given categories

#### Actual behaviour
The yAxis scale continues after the categories till a value which depends on the max z value in the series

#### Live demo with steps to reproduce
[Fiddle](https://jsfiddle.net/abidibo/v8ug15x0/2/)

- look at line 649 in the javascript editor, if you change the `424.7` value with something else, for example bigger (`4244`) you'll see the yAxis change consequently.
#### Product version

Highcharts 11.1.0
#### Affected browser(s)
Chrome

**Comment by bm64** [comment]
Hello @abidibo and thanks for reporting the issue.

We are aware about the bug and currently you can set `turboThreshold: 0` property as a workaround: https://jsfiddle.net/BlackLabel/s8euhqb6/

For more information or if you want to add anything please refer to the original ticket: https://github.com/highcharts/highcharts/issues/19746

Closing as a duplicate.
