### ISSUE TITLE
StockTools rangeSelector after changing series throws an error

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#19892]
#### Expected behaviour
Range selector should work normally after changing the series type.

#### Actual behaviour
After changing the series to i.e Heikin-Aski and then clicking 1m/3m on rangeSelector chart is gone and error is shown in the console.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui

#### Product version
Stock 11.1.0

_Internal note: Check other series types after the fix._

**Comment by pawelfus** [comment]
Seems to be a regression, v10.0 works fine: https://jsfiddle.net/BlackLabel/mkvb5ohq/2/

Broken since v10.1: https://jsfiddle.net/BlackLabel/mkvb5ohq/

Needs further bisect
