### ISSUE TITLE
Two yAxis, centerInCategory, point misaligned

### ISSUE THREAD

**Issue by K009** [highcharts/highcharts#19893]
#### Expected behaviour
Points shouldn't overlap

#### Actual behaviour
Points overlap

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/L3q0z8kf/
![image](https://github.com/highcharts/highcharts/assets/18682376/def12503-3262-42fe-b319-8ce402eccf5a)

**Comment by karolkolodziej** [comment]
Simplified demo: https://jsfiddle.net/BlackLabel/mrjzwb6n/

**Comment by TorsteinHonsi** [comment]
Duplicate of #17764

Demo with fix applied: https://jsfiddle.net/highcharts/oLjh5b8u/
