### ISSUE TITLE
Japanese characters are not correctly rendered in PNG export

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#199]
Demo: http://jsfiddle.net/highcharts/XSBZa/

While Scandinavian and Arabic characters are correctly rendered, Japanese aren't. This applies only to the online Linux based service. On the Windows test server, the characters display correctly.

**Comment by Galaf** [comment]
Dead link.
How are we supposed to fix this?
I tried installing the fonts: 

sudo apt-get install fonts-takao

To no avail.

**Comment by highslide-software** [comment]
@gvaartjes Any idea?

**Comment by Galaf** [comment]
I found the problem, actually.
Sorry, I forgot to mention it.

Highcharts sets its font globally (Lucida Grande) so if you do Highcharts.setOptions to set fontFamily to a japanese-able font, then the export works. (The font must also be installed on the export server, of course).

Maybe you should mention this somewhere in the documentation, though.

**Comment by gvaartjes** [comment]
Updated the docs with the above comment.

**Comment by ams45** [comment]
@Galaf  Can you please give example of  Highcharts.setOptions to set fontFamily to a japanese-able font. Which font family worked for you?
Thank you.
