### ISSUE TITLE
Rotating polar chart moves y-axis labels

### ISSUE THREAD

**Issue by freastro** [highcharts/highcharts#1990]
Summary:
This is similar to #1942 but in regards to the y-axis. The demo that was given with the fix applied shows the position of the y-axis labels has been rotated 180 degrees.

Steps To Reproduce:
1) Go to http://jsfiddle.net/highcharts/dRMWv/2/
2) See that y-axis labels are not the same between the two charts. The top chart is rotated 180 degrees, while the bottom chart is the control group (not rotated).

Excepted Results:
The y-axis labels should be in the same position between the two charts.

Actual Results:
The y-axis labels are in different positions between the two charts. The top chart has the position rotated 180 degrees from where it should be.

**Comment by oysteinmoseng** [comment]
No longer relevant, solved by `yAxis.angle` option: http://jsfiddle.net/0djpudx2/.
