### ISSUE TITLE
3D area throws error about starting path with L

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#19912]
#### Expected behaviour
Start the paths with M (or m) and have no errors.

#### Actual behaviour
Errors and the paths are not rendered in SVG.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/highcharts/3d-area-multiple
The errors are logged into the console on the chart build.

#### Product version
Highcharts Core + 3d
v11.1.0

**Comment by hubertkozik** [comment]
As a workaround, you can set `trackByArea` for the Area 3D series to `true`.

**Workaround:** https://jsfiddle.net/BlackLabel/0r1uwtvq/

**Comment by madepiet** [comment]
**Update:**

After investigating the current master branch, it looks like the issue has been addressed. The specific changes seem to be linked to the following commit: `ca2c502b01`
