### ISSUE TITLE
RangeSelector "All" not highlighted when the selected button is not enabled

### ISSUE THREAD

**Issue by mreifman** [highcharts/highcharts#19922]
#### Expected behaviour

When the range corresponding to the `selected` button index is wider than the full dataset, the "All" button should be selected.

#### Actual behaviour

The "All" button is shown as disabled. Selecting a narrower range then brings the "All" button back to being enabled.

#### Live demo with steps to reproduce

https://jsfiddle.net/x6gqr9pt/ (modified from [this official demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/rangeselector/allbuttonsenabled-true/))

#### Product version
Highstock v11.1.0

#### Affected browser(s)

Chrome 117

**Comment by mreifman** [comment]
I considered it a bug since the chart is showing all of the data but not indicating it via a selected state on the "All" button. This behavior does kick in after changing to a narrower range and then selecting "All".

I'd prefer to not use `allButtonsEnabled` since the default behavior gives the user an indication of what's in the dataset. After the initial state in the [demo](https://jsfiddle.net/x6gqr9pt/), if you select a narrow range the button set correctly shows the available options:

![image](https://github.com/highcharts/highcharts/assets/2730338/aab79240-cb31-42eb-8220-1d8accc522eb)

**Comment by pawelfus** [comment]
Fair point @mreifman - let me classify this as a bug. We will improve this. Meanwhile, how would you solve the case, when `All` button is unavailable? Would you pick the highest possible range? Or ignore `selected` (like we do right now)?

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/8sfxc9zr/

Plugin:
```js
(function(H) {

  H.Chart.prototype.callbacks.push(function(chart) {
    const rs = chart.rangeSelector;

    if (
      rs &&
      H.defined(rs.selected) &&
      rs.buttons &&
      rs.buttons[rs.selected] &&
      // Button is not selected, range to small, change to all:
      rs.buttons[rs.selected].state !== 2
    ) {
      const allButton = rs.buttonOptions.filter(btn => btn.type === 'all')[0];

      // Do we have "All" button?
      if (allButton) {
        rs.selected = rs.buttonOptions.indexOf(allButton);
        rs.updateButtonStates();
      }
    }
  });

})(Highcharts);
```

**Comment by mreifman** [comment]
I think picking the highest possible range makes sense, on the theory that the range selector should do it's best to match the range that's displayed in the chart. Since you can eventually get to a state where the range selector's selected state correctly reflects the range (by selecting a narrower range and then a wider one) it would be ideal if the initial state of the range selector correctly reflected that as well.

Thanks!

**Comment by pawelfus** [comment]
Thank you for your feedback!
Just to be on the same page: any other button than `All` have to match the exact range (eg 1day) or be close to that range (eg 1month can be 30 or 31 days) to be highlighted. Additionally, unless there is a button selected (by a developer), we will not enforce the extreme change.
