### ISSUE TITLE
highcharts-plot-bands width smaller than highcharts-plot-background in bubble chart

### ISSUE THREAD

**Issue by Yakoub-Azzizi** [highcharts/highcharts#19940]
Hi,

We use highcharts chart all over in our Angular app, since we upgraded to highcharts 11 we noticed this issue, a bubble chart in our app does not resize properly.  The are where the highcharts-plot-bands are is smaller than the highcharts-plot-background (Not sure if this is useful info though).

You can see in the examples below (expected using the cdn for highcharts 10.3, actual using highcharts 11) than using the same series, the result is different between the 2 versions, the new version results in a smaller chart with blank area on the sides.

Is it a known issue? And is there a workaround for this?

Thanks in advance!

Yakoub

#### Expected behaviour
https://jsfiddle.net/9zjqc6v3/

#### Actual behaviour
https://jsfiddle.net/0q9hejtv/130/

#### Live demo with steps to reproduce
https://jsfiddle.net/0q9hejtv/130/

#### Product version
"highcharts": "11.1.0",
"highcharts-angular": "3.1.2",

#### Affected browser(s)
Chrome

**Comment by bm64** [comment]
Hello @Yakoub-Azzizi and thanks for reporting the issue

Looks like it used to work correctly in v11.0.1 and has been broken sice v11.1.0. Simplified demo: https://jsfiddle.net/BlackLabel/n1q3zfyj/

_Internal note:_
Bisected to 67688e8e2ecbc1f98e29f7a489d22833522f6019 FYI @hubertkozik
