### ISSUE TITLE
Broken Link in API Docs

### ISSUE THREAD

**Issue by RahulARanger** [highcharts/highcharts#19961]
#### Expected behavior
One must be able to view the declaration of any configuration mentioned in the [API](https://api.highcharts.com/highcharts/) docs when redirected through the edit icon.

#### Actual behavior
![image](https://github.com/highcharts/highcharts/assets/57987728/36be692a-3bd9-4fd1-9b37-c4e75364db4b)

After clicking on the edit icon, we would be redirected to https://github.com/highcharts/highcharts/blob/v11.1.0/ts/ers/highsoft/GitHub/highcharts/code/es-modules/Accessibility/Options/A11yDefaults.ts, which does not exist.
assuming it would be: https://github.com/highcharts/highcharts/blob/v11.1.0/ts/Accessibility/Options/A11yDefaults.ts

#### Live demo with steps to reproduce
1. Open [API Docs](https://api.highcharts.com/highcharts/)
2. For any Configuration click on the icon for its declaration.
3. You will notice we would be redirected to a route in Github that does not exist.

**Comment by karolkolodziej** [comment]
Hi @RahulARanger!

Thank you for reporting the issue! Our web team will take a closer look!

**Comment by madepiet** [comment]
Does this problem still exist? It looks like this has been fixed in the current master.

**Comment by karolkolodziej** [comment]
As far as I see it works as expected now. Closing as resolved, if it pops up once again feel free to let us know about it!

**Comment by RahulARanger** [comment]
It's working fine as expected, Thank you.
