### ISSUE TITLE
Exporting in any format a treegraph chart not all text is visible 

### ISSUE THREAD

**Issue by cr1stimuresan** [highcharts/highcharts#19962]
#### Expected behaviour
![Screenshot 2023-10-19 at 09 40 08](https://github.com/highcharts/highcharts/assets/76202240/d716065d-ec0c-468b-989b-dbd3fbfc008a)

#### Actual behaviour
![phylogenetic-language-tr (1)](https://github.com/highcharts/highcharts/assets/76202240/bf4060b6-d4fb-4017-b6cf-aa1850e3a957)

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highchart

#### Product version

highcharts@11.1.0

#### Affected browser(s)

Google Chrome

**Comment by bm64** [comment]
Hello @cr1stimuresan 

Provided demo doesn't work. Could you provide us with working example? Thanks in advance

**Comment by cr1stimuresan** [comment]
Wrong copy -> paste
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/treegraph-chart

**Comment by bm64** [comment]
@cr1stimuresan thanks for providing the demo. The some data labels are hidden in exported files, because there is not enough space to draw them without overlapping. You can force show them, by setting allowOverlap option in exporting config: https://jsfiddle.net/BlackLabel/Lgnf2sbo/

**Comment by cr1stimuresan** [comment]
> @cr1stimuresan thanks for providing the demo. Some data labels are hidden in exported files, because there is not enough space to draw them without overlapping. You can force show them, by setting allowOverlap option in exporting config: https://jsfiddle.net/BlackLabel/Lgnf2sbo/

Even if you set container height to 2000px (no overlapping on the chart) it will still produce the same image. This doesn't seem ok.

**Comment by bm64** [comment]
Try setting height in exporting options and let me know if it helps: https://jsfiddle.net/BlackLabel/4dt0o7ec/
