### ISSUE TITLE
The connector is incorrect after redraw in `pyramid` series

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#19997]
#### Actual behaviour
The connector is initially drawn correctly, but after the first chart redraw the connector starting position (or width) changes and is incorrect.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/r8c5n4j6/
1. Click the button to see that the connector width changes

#### Product version
Highcharts 11

#### Affected browser(s)
All?

**Comment by oysteinmoseng** [comment]
Is this one working as expected now? I am not able to reproduce with that demo

**Comment by karolkolodziej** [comment]
I can't reproduce it with v11.2.0 either.
@TorsteinHonsi were you able to fix it?
