### ISSUE TITLE
Range Selector missing configuration

### ISSUE THREAD

**Issue by gnfranco** [highcharts/highcharts#20003]
#### Expected behaviour
Upon selecting the 5-minute zoom option on a dynamically updated chart, the chart should consistently display the last five minutes of data, even after updates.

#### Actual behaviour
Currently, when less data than the default selected option is available, the chart defaults to displaying "All" when the page loads. When a specific option, such as five minutes, is selected, the chart resets to displaying "All" every time new data is updated.

#### Live demo with steps to reproduce
(https://bipes.pete.com.br/easymqtt2/?session=nU133G)

#### Product version
11.1.0

Steps to Reproduce:

    Load the chart with a limited dataset.
    Select the 5-minute zoom option.
    Observe the chart displaying the last five minutes of data.
    Wait for new data to be updated on the chart.
    Note that the chart resets to displaying "All" instead of retaining the selected 5-minute zoom option.

Additional Information:
This behavior is consistent across different browsers/devices, confirming that it's not specific to one platform.

**Comment by bm64** [comment]
Hi @gnfranco

Thanks for providing reproduction steps, but I'm not sure how to use them to recreate the issue in given web page. Could you reproduce the issue in this demo? https://jsfiddle.net/BlackLabel/e3vjpa6s/

**Comment by gnfranco** [comment]
I can't reproduce it on your server. But it is a problem on the aplication that is runing on my server. Could you help me to understand what are haping please?

https://bipes.pete.com.br/easymqtt2/?session=kU133G

**Comment by bm64** [comment]
@gnfranco thanks for these additional informations, that was helpful. The 1 and 5 minutes buttons don't work, because in Highcharts Stock default value for `xAxis.minRange` is `3600000` (1 hour)  and it prevents to zoom below that value. To adjust this behaviour set the minRange value to anything lower than the buttons value: https://jsfiddle.net/BlackLabel/f70jy56m/
