### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by 43Laboratories** [highcharts/highcharts#20025]

**Comment by 43Laboratories** [comment]
A feature whereby timezone can be set based on country rather than Timezone to account for automatic updating of timezones

**Comment by karolkolodziej** [comment]
Hi @43Laboratories! 

You can set the timezone with a country/city as shown in the [API documentation.](https://api.highcharts.com/highcharts/time.timezone)
In this case, you need to add an external library `moment` which manages the time.

**Comment by 43Laboratories** [comment]
> Hi @43Laboratories!
> 
> You can set the timezone with a country/city as shown in the [API documentation.](https://api.highcharts.com/highcharts/time.timezone) In this case, you need to add an external library `moment` which manages the time.

Yes my issue is Highcharts.setOptions({
    time: {
        /**
         * Use moment-timezone.js to return the timezone offset for individual
         * timestamps, used in the X axis labels and the tooltip header.
         */
        getTimezoneOffset: function (timestamp) {
            const zone = 'Europe/London'; // Set the timezone to London
            const timezoneOffset = -moment.tz(timestamp, zone).utcOffset();

            return timezoneOffset;
        }
    }
}); i set the time for my highcharts series. However the date of my series goes through from 28th October (being BST) through to 30th october (being GMT). The highcharts date time series shows only BST times. It does not account for daylight saving...

**Comment by karolkolodziej** [comment]
I may not follow. Please explain what you are trying to achieve and what is not working.

**Comment by 43Laboratories** [comment]
> I may not follow. Please explain what you are trying to achieve and what is not working.

- I have a date time series from 28th of October - 30th October.
- 28th of October is Timezone British Summer Time
- 29th of October onwards is timezone (GMT)

- the timezone for GMT is not applied to the dates after daylight saving (29th October onwards) when setting timezone as the code does above. It sets the timezone to BST for dates within the GMT timezone. This is only an issue when a series interlaps between timezones. As in my example 28th of October is BST and 29th onwards is GMT.

**Comment by 43Laboratories** [comment]
getTimezoneOffset: function (timestamp) {
            const zone = 'Europe/London'; 
            const momentTimestamp = moment.unix(timestamp); 
            const m = momentTimestamp.tz(zone);

        
            if (m.isDST()) {
              
                return m.utcOffset() + 60;
            } else {
                return m.utcOffset();
            }
        }
    }
});

Solution for Timezones with daylight saving.
