### ISSUE TITLE
Plotband labels font size issue

### ISSUE THREAD

**Issue by sakshi1eQ** [highcharts/highcharts#20065]
#### Expected behaviour
As on highcharts version 10.3.3, the plotband labels took fontSize defined in chart model. In below fiddle the font size mentioned is 6px.
 
https://jsfiddle.net/sakshiKorade/wgqb03sm/

#### Actual behaviour
As on highcharts 11.1.0, the plotband labels are not applying font size applied on chart size but a font size of "0.8em" is getting applied.

https://jsfiddle.net/sakshiKorade/wgqb03sm/3/

#### Product version
Highcharts 11.1.0

**Comment by karolkolodziej** [comment]
Hi @sakshi1eQ!

[I simplified your demo](https://jsfiddle.net/BlackLabel/1sdgkLxe/), but I'm still not able to recreate the issue.
The styling: 
```js
        "style": {
          "fontSize": "24px"
        }
```
is properly applied to the plot band label.

**Comment by sakshi1eQ** [comment]
Hi @karolkolodziej 

Applying styling of fontSize as 24px explicitly does work well. My issue is that when this styling is not applied explicitly, it is expected that the fontSize of 6px should be applied to the plot band label which is defined in chart style model.

"chart": {
    "style": {
      **"fontSize": "6px",**
      "fontFamily": "Courier",
      "textAlign": "left"
    },

I have commented the styling you applied of fontSize as 24px in your fiddle here https://jsfiddle.net/sakshiKorade/xo5vga81/1/. Please enable the developer tools and check the font size that gets applied on the plot label. It will be of 0.8em. I have shared a screenshot of the same.

Earlier, at least until version 10.3.3. plot band label would get font size of 6px defined on chart model and not 0.8 em. 

![image](https://github.com/highcharts/highcharts/assets/96778080/50046457-17a4-4b0d-b9e0-587ac5da3a51)

**Comment by karolkolodziej** [comment]
Thank you for the explanation!

[The change was introduced with the new design in v11. ](https://github.com/highcharts/highcharts/pull/18649/files#diff-caf2beb446cefc70197640639a8c71910f5617f2c6c82c741ea5f3328301f796)
Altho I'm not sure if this is a bug because you are still able to set the font size for the plot band label (see my previous comment).

The only thing which has changed is the default value- previously taken from the parent, now set explicitly. 
@TorsteinHonsi your thoughts?

**Comment by TorsteinHonsi** [comment]
I agree it is not a bug. It is mentioned in the [Upgrade notes](https://www.highcharts.com/blog/changelog/#highcharts-v11.0.0), although it might be a bit more specific and mention that the font sizes of child elements also may be affected by the change.
