### ISSUE TITLE
Disappearing chart labels with Fullwidth space and japanes on FireFox.

### ISSUE THREAD

**Issue by hirokiky** [highcharts/highcharts#2006]
Hi.

I found bug on Highcharts 3.0.2.
A label of a linechart will disappear when that label contains Fullwidth space ('　' <= this) and some Japanes, on FireFox 22.0.

Please check out this jsFiddle using FireFox:

- http://jsfiddle.net/ALDjk/

Two linecharts will be displayed, but a label correspond to blue one will not be displayed.

I thought this behavior is bug of Highcharts, and submitted this issue.

Thank you.

**Comment by jon-a-nygaard** [comment]
Closing this issue due to we are not able to reproduce it, and it has been inactive for a long time. Should anyone have further information on this issue, please add a comment and/or reopen.
