### ISSUE TITLE
Pictorial gets cut when chart width is set

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#20066]
#### Expected behaviour
Pictorial path should not be cut when there is a space available

#### Actual behaviour
Right side of the path is cut

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5y16muv9/

#### Product version
HC 11.2.0

**Comment by skuske** [comment]
Any possible workaround that actually works on any screen size?

**Comment by magdalena-gut** [comment]
Hi @skuske , as you can read in the [documentation  ](https://www.highcharts.com/docs/chart-and-series-types/pictorial):

_"The image should be provided as an SVG path and should be cropped to maintain the correct proportions."_

It's important to note that this requirement extends to the positioning within the viewBox. So you need to be sure that svg image is align to the x and y at 0 coordinates of viewBox.

By pasting your primary SVG into the [svg-path-editor](https://yqnn.github.io/svg-path-editor/) tool, you might notice that it isn't perfectly aligned within the viewBox. 

<img width="533" alt="Screenshot_1" src="https://github.com/highcharts/highcharts/assets/91164859/07838237-2398-49b0-8ab3-e808a1123ba3">

Use the TransalteX and TransalteY to adjust the SVG by -2 units:

<img width="114" alt="Screenshot_2" src="https://github.com/highcharts/highcharts/assets/91164859/da5a4ab5-10df-4762-bc63-4a3e88689323">

You'll achieve a perfectly aligned image:

<img width="497" alt="Screenshot_3" src="https://github.com/highcharts/highcharts/assets/91164859/3fb33092-760f-40b9-88a8-be6b8bfc115e">

Then copy the modified path to your paths definition:

Demo: https://jsfiddle.net/BlackLabel/u2h5r4jt/

**Comment by skuske** [comment]
@magdalena-gut 

The SVG requirements should be mentioned better in the docs and samples! Anyway, many thanks for the help!

**Comment by magdalena-gut** [comment]
> @magdalena-gut
> 
> The SVG requirements should be mentioned better in the docs and samples! Anyway, many thanks for the help!

Thank you for your feedback! I agree with it, so I have created a ticket and the improvements will be made soon. Regards!

**Comment by skuske** [comment]
@magdalena-gut 

Perfect, many thanks again for the rapid and detailed help. Much appreciated! :o)
