### ISSUE TITLE
Events click with zoom button

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2008]
Example: http://jsfiddle.net/WDAn9/1/

Steps:
1) Zoom in the chart
2) Click on Reset zoom button

I think this shouldn't open new window, when we want only to reset zoom.

**Comment by SirZach** [comment]
Your fiddle is set up so that if you click anywhere on the chart that event will fire. Not sure if that's intentional or not.

**Comment by nitin0708** [comment]
Hi
Is there any functionality for zoom in and zoom out for highchart graph.

Thanks
Nitin

**Comment by pawelfus** [comment]
@SirZach - yes, it's intentional, to set minimum example with recreated issue. It may not necessary be the real use case.

@nitin0708 - Hi, for general support, see our channels [here](http://www.highcharts.com/support). And regarding your question, see [this plugin](http://www.highcharts.com/plugin-registry/single/26/Zoom%20Out%20Selection).

**Comment by SirZach** [comment]
@pawelfus this is just a clever scheme to get page views :)

**Comment by pawelfus** [comment]
Yeah, but it's not my page, just reported to me by someone else ;) 
Anyway, good point, updated initial demo!

**Comment by nitin0708** [comment]
Thanks for reply @pawelfus , but i am trying two buttons,one for zoom in and one for zoom out the graph.

Thanks
Nitin

**Comment by yaroslav-perec** [comment]
The same problem with export button, any update on this?

**Comment by pawelfus** [comment]
Hi @yaroslav-perec 

Exporting should be fine, take a look: http://jsfiddle.net/BlackLabel/WDAn9/44/ - feel free to update my demo with your problem.

**Comment by yaroslav-perec** [comment]
Hi @pawelfus

Thanks for your reply, I have chart without title, [demo](http://jsfiddle.net/qx5thtah/)

**Comment by pawelfus** [comment]
Thanks @yaroslav-perec for the demo! 

**Workaround:**
Don't open new window when clicked on an item that has specific classes, for example for exporting button:

```javascript
      "events": {
        "click": function(e) {
          var classList = e.target.classList,
            onExportingButton = (
              classList.contains('highcharts-button-box') ||
              classList.contains('highcharts-button-symbol')
            );
          if (!onExportingButton) {
            open("http://www.google.com", "_blank");
          }
        }
      },
```

Demo: http://jsfiddle.net/BlackLabel/qx5thtah/6/

**Comment by yaroslav-perec** [comment]
@pawelfus 

Thanks for your help.
