### ISSUE TITLE
chart.zooming.mouseWheel stopped working in v 11.2.0

### ISSUE THREAD

**Issue by anoosurf** [highcharts/highcharts#20089]
chart.zooming.mouseWheel stopped working in v 11.2.0

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/mouse-wheel-zoom/enabled

**Comment by karolkolodziej** [comment]
Hi @anoosurf! 

If you set the `mouseWheel` to true and the type of zooming, everything works as expected- [demo](https://jsfiddle.net/BlackLabel/0gwn6u7f/).

```js
  chart: {
    zooming: {
      mouseWheel: true,
      type: 'x'
    }
  },
```

As you can read in the API:

> Zooming with the mouse wheel is enabled by default in Highcharts Stock. In Highcharts Core it is enabled if [chart.zooming.type](https://api.highcharts.com/highcharts/chart.zooming.type) is set.

Related PR: https://github.com/highcharts/highcharts/pull/19697
