### ISSUE TITLE
Mapbubble series wrong point on hover

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#20086]
#### Behaviour
After recent changes in bubble series, due to the lack of clientX values for the mapbubble points, point search on hover fails to deliver the correct points.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/sp1w7qyx/1/

#### Product version
Highcharts Maps v11.2.0

#### Workaround
https://jsfiddle.net/BlackLabel/sp1w7qyx/

```js
Highcharts.seriesTypes.mapbubble.prototype.kdAxisArray = [
	'plotX', 'plotY'
];

Highcharts.seriesTypes.mapbubble.prototype.searchPoint = function (e, compareX) {
                return this.searchKDTree({
                    plotX: e.chartX - this.chart.plotLeft,
                    plotY: e.chartY - this.chart.plotTop
                }, compareX, e);
            };
```

**Comment by Kitcheone** [comment]
Is there a workaround for this that can be applied with angular-highcharts? I can access the mapbubble prototype with this: `Highcharts.Series.types['mapbubble'].prototype` but that doesn't seem to have property `kdAxisArray`, or method `searchKDTree`

**Comment by karolkolodziej** [comment]
Hi @Kitcheone! 
The `Series.types['mapbubble']` is something different than the `Highcharts.seriesTypes.mapbubble`.
Please use the exact workaround suggested by Kacper. You probably will need to work around the TS because the `seriesTypes` isn't publicly available.
