### ISSUE TITLE
Disappearing graph line in webkit browsers only with lots of series data.

### ISSUE THREAD

**Issue by jsatk** [highcharts/highcharts#2009]
Link: http://jsfiddle.net/jesseatkinson/qukvL/2/

We were switching the series that was visible in the chart and re-rendering the chart. We had a lot of series. All were invisible except one. For some reason only some of them would, after their initial animation, disappear (they had no height).

I've provided an example. The visible series disappears with placed with other series data. However it completely renders perfectly fine when it's alone.

**Comment by carlcrott** [comment]
http://jsfiddle.net/rr92tg56/3/

I'm asking higcharts to do some complex things here so I'll attempt to convey what I'm trying to do:

1) I want real world datetime's associated with dynamic data.
2) I want the graph to always start at 00:00 and extend in 15-minute increments to some arbitrary # of hours ( something between 4 and 100 ).
3) When a graph is started at 10:10  I want the datapoint taken at 10:25 to be shown at the 00:15 xAxis tick, yet still have the realworld datetime associated with the datapoints series data. 

The bug I'm seeing could be related to the fact that its a huge dataset + currently the data isn't scaled for the graph resolution that's available ( IE im graphing more datapoints than can be displayed )

Essentially the graph will sporadically show + not show, even while the data is still present.

Ill update this as I simplify as I clean up my code.

Thanks all!

**Comment by carlcrott** [comment]
Simplified version that still exhibits the disappearing graph issue:

https://jsfiddle.net/zwa30h02/

**Comment by carlcrott** [comment]
And removing the tooltips + markers ( and hover states ) seem to solve the issue:

https://jsfiddle.net/zwa30h02/1/

**Comment by TorsteinHonsi** [comment]
I can see the graph in Chrome 56 on Mac...

**Comment by carlcrott** [comment]
@TorsteinHonsi Correct.  On the last jsfiddle.  However if the first 2 run for more than an hour and then you mouse-over the graphs theyll disappear.

**Comment by jsatk** [comment]
This is clearly abandoned. Closing.
