### ISSUE TITLE
Two or more `dataLabels` defined for `bullet` series are not displayed

### ISSUE THREAD

**Issue by jedrzejruta** [highcharts/highcharts#20098]
#### Expected behaviour

When setting an array of `dataLabels` for a series, all of the defined data labels should be visible.

_Per API:_ 

> Since v6.2.0, multiple data labels can be applied to each single point by defining them as an array of configs.

#### Actual behaviour

There are no data labels rendered at all in bullet chart.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/9pvr27hs/](https://jsfiddle.net/BlackLabel/9pvr27hs/)

#### Product version
Highcharts v11.2.0

**Comment by bm64** [comment]
Seems like it used to work correctly in v11.1.0: https://jsfiddle.net/BlackLabel/zw6jperb/

Workaround: set `enabled: true` for reach data label config: https://jsfiddle.net/BlackLabel/w2jhqnxo/
