### ISSUE TITLE
errorbar not visible with default 1 month zoom

### ISSUE THREAD

**Issue by gregory-clement** [highcharts/highcharts#20097]
#### Expected behaviour
The errorbar should be displayed when the page is loaded

#### Actual behaviour
The errorbar is not displayed when the page is loaded. After selecting "All" zoom level, errorbar is correctly displayed. Then, if the "1 month" zoom is selected, the errorbar is still displayed. 

If I delete 1 (or more) line of data, the bug disappears.

#### Live demo with steps to reproduce
https://jsfiddle.net/gregoryclement/eashqu81/30/

#### Product version
Highstock JS v11.2.0 (2023-10-30)

#### Affected browser(s)
Edge, Chrome, Firefox

**Comment by bm64** [comment]
Hello @gregory-clement 

Looks like it used to work correctly in v11.1.0 and has been broken since v11.2.0: https://jsfiddle.net/BlackLabel/heq6c7kf/

**Comment by pawelfus** [comment]
[Bisected to commit 52a6ede0a5](http://utils.highcharts.local/bisect/view?hash=52a6ede0a5d4d92c9a039046efad450dc69ec52b)

Recreated without Stock: https://jsfiddle.net/BlackLabel/zn5v0b9x/ 

FYI @bre1470
