### ISSUE TITLE
Highcharts NuGet package is extremely large

### ISSUE THREAD

**Issue by lahma** [highcharts/highcharts#20116]
#### Expected behaviour

Production deployment's size wouldn't be dictated by `Highcharts.dll`.

#### Actual behaviour

The `Highcharts.dll` for version `11.1.0.2` is `27,0 MB (28 356 608 bytes)`, it's been growing by release and seems quite uncontrolled. For example for version 7.2.1.1 while way too large too, it was "just" `10,6 MB (11 202 560 bytes)`.

As comparison https://www.nuget.org/packages/DotNet.Highcharts while definitely lacks features, the size of DLL is `348 KB (356 352 bytes)`.

#### Live demo with steps to reproduce

If you look at the package in package explorer it also shows that the package isn't following best practices and many of the alerts are present (red shields). If this were to be open sourced on GitHub maybe someone could help you out and improve the quality?

https://nuget.info/packages/Highsoft.Highcharts/11.1.0.2

#### Product version

11.1.0.2

**Comment by bm64** [comment]
@brofixo could you take a look at the issue?

**Comment by brofixo** [comment]
@lahma, thank you for your comment. The size of Highsoft.Highcharts package is growing because of growing number of features.

**Comment by lahma** [comment]
@brofixo this does not sound like a good explanation, this means that v11 has almost three times the features of v7? Based on logic that features equal DLL size that would mean that the linked `DotNet.Highcharts` has only 1% of the features of this library (which is not true). I think we could really do better here.

**Comment by brofixo** [comment]
This issue was partially resolved and there are no plans to change it more so far.
