### ISSUE TITLE
Polygons do not render well when data in chart is updated

### ISSUE THREAD

**Issue by MelissaVanDijk** [highcharts/highcharts#20118]
**Expected behaviour**
When updating the values of the series in the chart, the polygon series should render well.

**Actual behaviour**
When new data is loaded into the series, the polygon series are not rendered well anymore, showing holes in the rendered areas

**Live demo with steps to reproduce**
https://jsfiddle.net/rfn80jok/

This chart shows two lines and some polygons. When you click on the button "Set other data",  the data in the chart is altered and applied to the chart. After that update, the blue polygon shows holes at the bottom of the chart.

**Product version**
Highcharts v11.2.0 (2023-10-30)

**Affected browser(s)**
Chrome, Firefox, Edge (probably others too, but I have not tested that)

**Comment by karolkolodziej** [comment]
Hi @MelissaVanDijk! 

Are you sure that the way you update the data is correct? Especially the part about the `updatedData6`?
```js
function setOtherData() {      
  console.log('SET OTHER DATA');
  const updatedData0 = [...(chart.series[0].data.map(d => ({...d, y: d.y + 0.2})))];  
  const updatedData7 = [...(chart.series[7].data.map(d => ({...d, y: d.y - 0.1})))];
  const seriesData6 = chart.series[6].data;
  const updatedData6 = seriesData6.map(d => ({...d, y: d.y + 0.1, x: d.x +0.1}));
 
  chart.series[0].color = "#0000FF";
  chart.series[0].setData(updatedData0, true); 
  chart.series[2].color = "#FF0000";
  chart.series[2].setData(extraSeries.data, true);
  chart.series[6].color = "#00FFFF";
  chart.series[6].setData(updatedData6, true);
  chart.series[7].color = "#00FFFF";
  chart.series[7].setData(updatedData7, true);
}
```

**Comment by karolkolodziej** [comment]
I went through it once again and it looks like the update mechanism is fine. 
The only problem is that some of the points have a `null` value and if you add/subtract initially it might get a bit messy.
If you remove the null points, polygons move in a steady pace up- [demo](https://jsfiddle.net/BlackLabel/9btrwceq/).

**Comment by MelissaVanDijk** [comment]
Thank you for your quick reply! I realize that my fiddle sample had some flaws. So I made two new fiddle demos to reproduce this problem.

**Demo 1:**  https://jsfiddle.net/c31kfb2q/17/
In this fiddle demo, I have a chart with a line and a polygon. When you click on the button "Set other data", new data is inserted into the line and the polygon series. You will see that the polygon does not render as it should, leaving holes.

**Demo 2:** https://jsfiddle.net/c31kfb2q/16/
In this demo, the data that is inserted in demo 1 is used right from the start. This proves that the polygon data is correct and could be rendered well, if only it wasn't inserted dynamically.

Could you take another look at this?

**Comment by karolkolodziej** [comment]
1. If you have `null` points in the polygon and there is a chance the polygon will change its shape drastically, I suggest setting the `updatePoints` in the `setData` method to false- [demo](https://jsfiddle.net/BlackLabel/vpz9ymL6/).
