### ISSUE TITLE
`packedbubble` data labels misaligned when legend position is changed

### ISSUE THREAD

**Issue by jedrzejruta** [highcharts/highcharts#20120]
#### Expected behaviour

When vertical legend position changes, `dataLabels` positions are recalculated and aligned properly.
#### Actual behaviour
When vertical legend position changes, `dataLabels` position stays the same, resulting in wrong alignment.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/qcr9un6f/](https://jsfiddle.net/BlackLabel/qcr9un6f/)

If the chart width is smaller than 600px, the `dataLabels` are rendered correctly.
#### Product version
Regression, worked fine in v10.3.3, stopped working from v11.

**Comment by karolkolodziej** [comment]
Internal note:
`spacingLeft` and `marginLeft` have no effect on the labels and they are rendered correctly.

**Comment by mark-leblanc-moodys** [comment]
This issue is affecting a production release.  Is there any update?

**Comment by hubertkozik** [comment]
_Internal note:_
Bisected to f1f015249b357c32d33bf86fe4cacfed1935ca57.

**Comment by hubertkozik** [comment]
I have prepared a workaround for that issue. If you want to use it in your project simply copy-paste the IIFE function from the below demo.

**Live demo:** https://jsfiddle.net/BlackLabel/7gryhpx2/
