### ISSUE TITLE
Problem with Column Shrinkage

### ISSUE THREAD

**Issue by Satyam7Jha** [highcharts/highcharts#20127]
#### Expected behaviour
<img width="576" alt="image" src="https://github.com/highcharts/highcharts/assets/75986382/69b4a777-1ed1-466a-a181-72e552545844">

#### Actual behaviour
I observed an issue with Highcharts where Column with maxWidth: 16 don't shrink correctly over a 90-day period.
<img width="577" alt="image" src="https://github.com/highcharts/highcharts/assets/75986382/ebfed68d-095c-41fe-8bf4-c1643c4cb97b">

#### Live demo with steps to reproduce
https://codesandbox.io/s/ecstatic-mountain-wqn6qr?file=/src/App.js

#### Product version
Highcharts 
 
#### Affected browser(s)
all

**Comment by bm64** [comment]
Hello @Satyam7Jha 

If you check the console you can see that there is a [Highcharts Warning #15](https://assets.highcharts.com/errors/15/), which means that your data is not sorted. Sorting your data should resolve the issue:
https://codesandbox.io/s/frosty-browser-fxhq9h
