### ISSUE TITLE
Chart series disappeared when switcting to "Hollow candlestick"

### ISSUE THREAD

**Issue by meiir-kapassov** [highcharts/highcharts#20135]
#### Expected behaviour
The chart is successfully adapted to the new scale

#### Actual behaviour
In cases of the small scale, the chat suddenly disappears (with errors in console)

![image](https://github.com/highcharts/highcharts/assets/132430389/df18636e-7cd8-4578-b612-950dcd9df860)

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/stock/stock-tools-gui

Steps:
1. Tap “Chart type“ Button
2. Select “Hollow candlestick“ chart type
3. Start chart sizing using the navigator AND gradually decrease the scale (mostly to the right side)

#### Product version
Highstock +11.1.0

#### Affected browser(s)
Firefox, Chrome

**Comment by karolkolodziej** [comment]
Hi @meiir-kapassov!

Indeed in v11.2.0 and older, I was able to see the issue. However, with the latest master, I wasn't- [demo](https://jsfiddle.net/BlackLabel/5o47p1me/).

___
Unfortunately, I wasn't able to bisect what potentially fixed the issue but most likely it will be this PR: https://github.com/highcharts/highcharts/pull/19988
@pawelfus @kamil-musialowski can you please confirm if that is the case?

**Comment by kamil-musialowski** [comment]
Hi there, while fixing the Heikin-Ashi issue in #19988 I came across the similar problem with the HollowCandlestick, therefore I decided to also fix it there. So you are right, it is fixed, merged and available on master. It will be ready on npm and cdn with the next release.
