### ISSUE TITLE
Property 'custom' does not exist on type 'Point'

### ISSUE THREAD

**Issue by dartess** [highcharts/highcharts#20137]
#### Expected behaviour

custom on Point should be `custom?: Dictionary<any>;`

#### Actual behaviour

Property 'custom' does not exist on type 'Point'

#### Live demo with steps to reproduce

https://codesandbox.io/s/fragrant-sun-h2z8qx?file=/src/index.ts

#### Product version

highcharts@11.2.0

**Comment by bm64** [comment]
Hello @dartess 

That behaviour is intended and if you want to use custom properties in point configuration object in typescript, you need to extend existing types either with declare module: https://codesandbox.io/s/optimistic-shadow-fvgh5w
or by extending existing interface and type casting.
