### ISSUE TITLE
x-Axis layout doesn't work for column chart when series data leaves out x values

### ISSUE THREAD

**Issue by mwahnschaffe** [highcharts/highcharts#2013]
When I add two series to a column chart an leave out values (in order) the x-axis layout goes wrong:

`series: [{
                name: 'John',
                data: [[0,5],[3,2]]
            },{
                name: 'Hanna',
                data: [[0,1],[2,3]]
            }]`

http://jsfiddle.net/C4D7Q/3/

This seems to be a bug.

**Comment by oysteinmoseng** [comment]
This seems to work as expected with current code. Closing for now.
