### ISSUE TITLE
Setting draggable on error bar only works for top bar

### ISSUE THREAD

**Issue by neilcrowley-cci** [highcharts/highcharts#20146]
#### Expected behaviour
When setting draggableY on an errorbar series, only the top whisker can be dragged.

#### Actual behaviour
Both whiskers should be draggable, similiar to the boxplot chart,

#### Product version
HighCharts 11.2.0

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Hi @neilcrowley-cci!

Thank you for reporting the issue! [Here is a simple demo of the issue.](https://jsfiddle.net/BlackLabel/1gqh03zo/)

Internal note:
Issue where the box-plot was fixed, might be relevant: https://github.com/highcharts/highcharts/issues/13576

**Comment by raf18seb** [comment]
Looks like the `errorbar` series was missed when writing `draggable-points` module:
https://github.com/highcharts/highcharts/blob/12771e959aad5a428cd1d0497ecca3352142ba27/ts/Extensions/DraggablePoints/DraggablePoints.ts#L230-L272

Workaround (coppied from boxplot and improved a little):
```js
const errorbarProto = Highcharts.seriesTypes.errorbar.prototype,
  boxplotProto = Highcharts.seriesTypes.boxplot.prototype;

// Inherit from boxplot...
errorbarProto.dragDropProps = boxplotProto.dragDropProps;

// ... but remove redundant props
delete errorbarProto.dragDropProps.q1;
delete errorbarProto.dragDropProps.median;
delete errorbarProto.dragDropProps.q3;

// Correct props validation
errorbarProto.dragDropProps.low.propValidate = (val, point) => (val <= point.high);
errorbarProto.dragDropProps.high.propValidate = (val, point) => (val >= point.low);
```

Demo with a workaround: https://jsfiddle.net/BlackLabel/02uc7pd8/
