### ISSUE TITLE
Different number format in tooltip for x and y value of Scatter chart

### ISSUE THREAD

**Issue by yplakosh** [highcharts/highcharts#2014]
The format of x and y values in tooltip of Scatter chart is different. Y-axis value has comma and X-axis value does not.
Here is an example: http://jsfiddle.net/Kv778/

Is there any way to fix this issue using format options?
![screen shot 2013-07-05 at 1 09 43 pm](https://f.cloud.github.com/assets/4722300/755422/e5b5645a-e5ae-11e2-900e-85d633e27374.png)

**Comment by creativecoderr** [comment]
> I think the only way to do it using 2.3.x is with a formatter function.
> 
> ```
> tooltip: {
>   formatter: function() {
>     return Highcharts.numberFormat(this.x, 0, '.', ',') + ' cm,<br/>' + 
>            Highcharts.numberFormat(this.y, 0, '.', ',') + ' kg';
>   }
> }
> ```
> http://jsfiddle.net/Kv778/1/

Solved my issue when I was trying to use thousands separator for my data labels. Had tried the Highcharts.setOption first, but that only worked for the tool tips and not the data labels. Thanks a ton. Using latest highcharts version.

**Comment by leela-leela** [comment]
{point.y:.0f} this point casn be shown in title or subtitle part of the chart means how the code will be changed
