### ISSUE TITLE
HighCharts - Visualization issue in Pie chart

### ISSUE THREAD

**Issue by Sivasatheesh-DSRC** [highcharts/highcharts#20156]
#### Expected behaviour
We need to display the chart in proper size but

#### Actual behaviour
If I add more data, then the size of the chart gets very small

#### Live demo with steps to reproduce
[https://jsfiddle.net/w06e7gLm/](https://jsfiddle.net/w06e7gLm/)

#### Product version
Highcharts

#### Affected browser(s)
Chrome

**Comment by bm64** [comment]
Hi @Sivasatheesh-DSRC 

As I mentioned in #20158, we use github strictly for feature request / bug tracking so with any further questions regarding chart configuration please visit our other [support channels](https://www.highcharts.com/blog/support/), for example https://www.highcharts.com/forum/
