### ISSUE TITLE
Highcharts - How to place legend in the right side if the pie chart

### ISSUE THREAD

**Issue by Sivasatheesh-DSRC** [highcharts/highcharts#20158]
#### Expected behaviour
We need to place the legend item in the right side of the chart

#### Actual behaviour
Its in the bottom of the chart

#### Live demo with steps to reproduce
[https://jsfiddle.net/w06e7gLm/](https://jsfiddle.net/w06e7gLm/)

#### Product version
Highcharts

#### Affected browser(s)
Chrome

**Comment by bm64** [comment]
Hello @Sivasatheesh-DSRC 

To achieve something like that you should combine `align` and `verticalAlign` properties: https://jsfiddle.net/BlackLabel/d9uqxmt0/

We use github strictly for feature request / bug tracking so with any further questions regarding chart configuration please visit our other [support channels](https://www.highcharts.com/blog/support/), for example https://www.highcharts.com/forum/
