### ISSUE TITLE
.NET Highcharts Stacked Column Label Bug

### ISSUE THREAD

**Issue by fceci90** [highcharts/highcharts#20165]
#### Expected behaviour
When setting column plot options to show the stack total at the top of the bar and setting the data labels for each individual series to be off, I would expect to see a chart with stacked columns with only 1 data label at the top of each column whose value would be the sum of the column series values.

#### Actual behaviour
The actual behavior is a little confusing to describe as it does show stack totals at the top for all but 1 column, but all columns also include the stacked total value as a data label on the column itself. I have attached an image that first shows what the chart looks like without plot options labels showing the stacked totals (this displays correctly based on configuration options), and the second image shows what happens when I disable series data labels, and turn on plot option series to be the stack total.
![comparison-image](https://github.com/highcharts/highcharts/assets/17017116/8806058e-32fd-4c6a-b16e-def8a065f555)

#### Live demo with steps to reproduce
I created a dotnetfiddle with all the code to hopefully run the demo, but Highcharts doesn't seem to want to load. This is the link: https://dotnetfiddle.net/Q3vgmY
Here is a Codepen showing how the same configuration works properly using highcharts with JavaScript instead of .NET.
https://codepen.io/FittyFrank/pen/KKJyjWB

#### Product version

Highcharts 11.1.0.2.

#### Affected browser(s)
Same issue on every browser I tested: Edge, Chrome, FireFox (all latest stable versions).

**Comment by fceci90** [comment]
Just adding my workaround to make the chart display correctly for the time being. It removes any hidden labels in the first series of data labels which contain the stack totals. I also use CSS to hide the second series data labels. Hopefully this can provide insights into what is occurring.
$(function () {
    // unhide data labels from first series
    $('.highcharts-data-labels.highcharts-series-0')
        .children('.highcharts-data-label-hidden')
        .removeAttr('opacity')
        .removeClass('highcharts-data-label-hidden');
});

/*Hide the second series lables, bug in .net highcharts won't remove it*/
.highcharts-data-labels.highcharts-series-1 {
    display: none;
}

**Comment by karolkolodziej** [comment]
FYI @brofixo

**Comment by brofixo** [comment]
@fceci90 , 
I think you are looking for `yAxis.stackLabels` set on `true`. Don't use data labels for series and plotOptions.

**Comment by fceci90** [comment]
@brofixo Thank you! This worked perfectly. I didn't know this option existed. I was only searching the documentation for dataLabels configurations.
