### ISSUE TITLE
Y axis auto zoom does not return to initial value

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#2016]
Reduced example: 

1. Open the example: http://jsfiddle.net/hZmR8/
2. Look at the y axis range and enable the second series (initially hidden)
3. The y axis is adapted to include the new series
4. Hide series 2 again

Result: The y axis does not move
Expected: That the y axis is zoomed to the initial state
Note: Hiding and showing the first series will trigger a redraw of the y axis

**Comment by pawelfus** [comment]
Works fine since 2.1: http://jsfiddle.net/hZmR8/2/ - where [`Axis.tickAmount`](http://api.highcharts.com/highstock/yAxis.tickAmount) was introduced.
