### ISSUE TITLE
Highstock - Add option for customize navigator zoom and behavior

### ISSUE THREAD

**Issue by ninjatux** [highcharts/highcharts#2017]
I run in a situation where I want to show always a fixed zoom for my navigator without giving the user the possibility to change it. The most logical way to do so was by removing the navigator handles overwriting the drawHandle function in this way:

``` javascript
Highcharts.Scroller.prototype.drawHandle = function () {};
```

it would be useful if there will be an option that allow an user to specify the navigator initial zoom (currently I set it in the load event callback) and it's behavior on resize (allowed or not).

**Comment by pawelfus** [comment]
This is already possible in Highstock v6, to sum up:

- default range: [`xAxis.range`](https://api.highcharts.com/highstock/xAxis.range) or just [`xAxis.min`](https://api.highcharts.com/highstock/xAxis.min) and [`xAxis.max`](https://api.highcharts.com/highstock/xAxis.max)
- disabled handles: [`navigator.handles.enabled`](https://api.highcharts.com/highstock/navigator.handles.enabled)
