### ISSUE TITLE
beforeunload is triggered on download a chart

### ISSUE THREAD

**Issue by cr1stimuresan** [highcharts/highcharts#20191]
Hi,
I have a chart with download button and a form on the same page. The trigger of beforeunload on download is causing unnecessary prompts for leaving the page 

#### Expected behaviour
beforeunload event should not be triggered by exporting a chart

#### Actual behaviour
beforeunload event is triggered by exporting a chart

#### Live demo with steps to reproduce
https://jsfiddle.net/o0cx86qL/6/

#### Product version
Highcharts 11.2.0

#### Affected browser(s)
Chrome

**Comment by bm64** [comment]
Hi @cr1stimuresan and thanks for reporting the issue
