### ISSUE TITLE
Highcharts react callback is not updated after some react props was updated.

### ISSUE THREAD

**Issue by DmitryPacificAtion** [highcharts/highcharts#20196]
I'm trying to implement loader with async behavior.

I have a code:
import { DonutChart } from './donut-chart';
const ParentComponent = () => {
    const [isLoading, setIsLoading] = useState(true); // POINT#1

    useEffect(() => {
        // .... some logic to call API and load some data for a chart
        setIsLoading(false) // POINT#2
    }, []);

    return <DonutChart isLoading={isLoading} {...args} />
}

// donut-chart.jsx
// import ... from modules
highchartsMore(Highcharts);
addExportingModule(Highcharts);
addExportData(Highcharts);
accessibilityModule(Highcharts);
noDataModule(Highcharts);

const DonutChart = ({ isLoading, ...rest}) => {
const options = {...}; // some options from Highcharts API

console.log("POINT#3", isLoading);

return (
    <HighchartsReact
        highcharts={Highcharts}
        options={options}
        update={isLoading}
        callback={instance => { // POINT#4: Here could be the problem
            if (isLoading) {
                console.log('case 1', isLoading);
                instance.showLoading(getCustomLoader());
            } else {
                console.log('case 2', isLoading);
                instance.hideLoading();
            }
        }}
    />
)

getCustomLoader - is function for injecting some custom styles to animate loader. In our case this is a circle as in Material

const getCustomLoader = () => {
    const hasStyles = document.getElementById('custom-loader-styles');
    const innerStyles = '
        .custom-loader {
            width: 88px;
            height: 88px;
            animation: spin 1s linear infinite;
        }
        .custom-loader__circle {
            stroke: ${theme.ourColorForLoader};
            stroke-dasharray: 80px,200px;
            stroke-dashoffset: 0;
            animation: loaderGrow 1.4s ease-in-out infinite;
        }
        .highcharts-loading {
            z-index: 1000 !important;
            left: 0 !important;
            top: 35px !important;
            bottom: 0 !important;
            right: 0 !important;
            width: 100% !important;
            height: 100% !important;
        }
        .highcharts-loading-inner {
            top: calc(50% - 44px) !important;
        }
        
        @keyframes spin {            // <------- Important thig! We need this animation, that's why we injected that styles in DOM
            0% {
                transform: rotate(0deg);
            }
            100% {
                transform: rotate(360deg);
            }
        }
        @keyframes loaderGrow {
            0% {
                stroke-dasharray: 1px,200px;
                stroke-dashoffset: 0;
            }
            50% {
                stroke-dasharray: 100px,200px;
                stroke-dashoffset: -15px;
            }
            100% {
                stroke-dasharray: 100px,200px;
                stroke-dashoffset: -125px;
            }
        };
    const element = hasStyles || document.createElement('style');

    element.setAttribute('id', 'custom-loader-styles');
    element.innerHTML = innerStyles;
    document.head.appendChild(element);

      return '
      <svg class="custom-loader" viewBox="22 22 44 44">
          <circle class="custom-loader__circle" cx="44" cy="44" r="20.2" fill="none" stroke-width="3.6"></circle>
      </svg>
  ';
};

#### Expected behaviour
POINT#1: isLoading === true, console.log shows in POINT#3 sows true, loader is visible
POINT#2: setIsLoading was called and isLoading becames 'false'
POINT#3: console.log displays: "POINT#3", false
POINT#4: Props in DonutChart  should be updated, and callback should be updated as well. And in callback I 'case 2' should hide loader.

#### Actual behaviour
POINT#4: Props in DonutChart was updated, but callback wasn't  and 'case 1' is still showing loader.

#### Live demo with steps to reproduce
https://jsfiddle.net/BruslikDmytro/7zds3qeo/40/

#### Product version
"highcharts": "^10.3.3",
"highcharts-react-official": "^3.1.0",
"react": "^17.0.2",

#### Affected browser(s)
Chrome. Version 119.0.6045.160 (Official Build) (64-bit)

**Comment by bm64** [comment]
Hi @DmitryPacificAtion 

It looks like our support engineer has already answered your question here: https://stackoverflow.com/questions/77544051/why-callback-is-not-called-after-prop-was-updated
In short, the issue is that callback is being fired only once on chart creation. Instead you should use `useEffect` or event like `chart.render`. Also we work as a single team across all support channels, so please avoid creating duplicates. Thanks in advance!
