### ISSUE TITLE
Bug with using reversed axis in Highstocks

### ISSUE THREAD

**Issue by SujayKrishna** [highcharts/highcharts#2020]
The Navigator component on manual resizing automatically restricts the selection.
But this does not happen when we use the range selector zoom buttons on input boxes or when calling the setExtremes method on the xAxis.

Also the xAxis ticks don't seem to be working. There is only one tick (in the left corner) for most zoom levels (other than all).

Check out http://jsfiddle.net/sujay/mNbZa/ to see the issue in action.

**Comment by pawelfus** [comment]
Let me close this ticket as it described two issues:

- #4114 - reversed navigator xAxis: drag&drop (this is fixed in the dev branch: http://jsfiddle.net/mNbZa/3/ )
- #4175 - reversed ordinal xAxis: missing labels
