### ISSUE TITLE
`RangeSelector.alignElements` method gets called 3-4 times on each redraw

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#20217]
#### Expected behaviour
The elements of `RangeSelector` should be aligned once on load, and then once every redraw if necessary.

#### Actual behaviour
The method gets called 3-4 times on each redraw.

#### Live demo with steps to reproduce

Check the console on initial redraw. Then click anywhere on the chart, and see that there are multiple logs from 'alignElements' method. 
https://jsfiddle.net/BlackLabel/g7tq01np/28/

#### Product version
v11.2

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Reduced to two aligns per redraw (one to calculate the expected margins, the second to actual align). Considering this done, no unnecessary alignments happen.
