### ISSUE TITLE
Property centerInCategory not working as intended

### ISSUE THREAD

**Issue by thyagorafaell** [highcharts/highcharts#20221]
#### Expected behaviour
The use of the [centerInCategory](https://api.highcharts.com/highcharts/plotOptions.column.centerInCategory) feature is not working as same as it was in version 8.2.2.

All columns should be positioned in the center of the category, like in the fiddle: https://jsfiddle.net/thyagorafaell/5t2Lzw04/1/.

#### Actual behaviour
However, in version 11, the columns respect the reserved space to other series, so the column from the first series are rendered on the left.

#### Live demo with steps to reproduce
https://jsfiddle.net/thyagorafaell/g2v8ueoh/2/

#### Product version
11.2.0

**Comment by karolkolodziej** [comment]
Hi @thyagorafaell! 
Thank you for reporting the issue! 

Internal note:
Bisected to commit 4028d4bc38

**Comment by thyagorafaell** [comment]
Is there any snippet/workaround available to quick fix this issue?

**Comment by TorsteinHonsi** [comment]
#### Workaround
It seems like putting the line series first fixes the issue: https://jsfiddle.net/highcharts/rygLm0tn/

**Comment by karolkolodziej** [comment]
The new version with this fix should be this month.
