### ISSUE TITLE
The `point.update` method doesn't affect the point's name

### ISSUE THREAD

**Issue by KamilKubik** [highcharts/highcharts#20231]
#### Expected behaviour
The `point.update` method should update the `name` property on the point's instance.

#### Actual behaviour
The `point.update` method doesn't update the `name` property on the point's instance.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/n15oxqay/

#### Workaround
Refer to the `point.options.name` property instead.
https://jsfiddle.net/BlackLabel/03ft91gy/

#### Product version
Highmaps JS v11.2.0

**Comment by magdalena-gut** [comment]
Internal note: the issue occur independently to update method ->
https://jsfiddle.net/BlackLabel/4189b0rs/
