### ISSUE TITLE
Not connecting all the points in timestamp order sometimes when draw a line graph

### ISSUE THREAD

**Issue by sylvester05** [highcharts/highcharts#20237]
#### Expected behaviour
I have a data set ordered by timestamp, it need to draw a line graph in highcharts react.
I am using React frontend, so I am using highchartsreact.

#### Actual behaviour
As you can see a screenshot I attached, it is not connected in order of timestamp, or order of the data in data set.
![highcharts-issue](https://github.com/highcharts/highcharts/assets/109437175/d5fb2788-7427-4810-9432-5f05925bf44d)

**Comment by bm64** [comment]
Hello @sylvester05,

Please check your console for the [Highcharts Error #15](https://assets.highcharts.com/errors/15/). Highcharts expects your data to be sorted in line series. The error message in the console should confirm if this is the issue.

**Comment by sylvester05** [comment]
When I sorted the data, it worked properly, but before sorting all data is sorted, so the data before sorted is the same as the data after sorted. I added ```.sort((a, b) => {
      if (!a || !b) return 0;
      return a.x - b.x;
    })```
I am not sure why this happens.

**Comment by bm64** [comment]
@sylvester05 if adding `.sort((a, b) => { if (!a || !b) return 0; return a.x - b.x; })` helped, that means the original data wasn't sorted. Sure, I can take a look and try to figure out what causes the issue but I will need you to provide me with original data / chart config.

**Comment by sylvester05** [comment]
Thanks for your support. I was able to solve this problem by sorting the data. 👍
