### ISSUE TITLE
Highchart tooltip borderColor not working

### ISSUE THREAD

**Issue by Dhan3777** [highcharts/highcharts#20252]
#### Expected behaviour
There should be border in tooltip

#### Actual behaviour
setting borderColor is doing nothing

#### Live demo with steps to reproduce (change color and see)
https://jsfiddle.net/70ezuvrx/
#### Product version
V11.2.0. running with angular 14

**Comment by karolkolodziej** [comment]
Hi @Dhan3777!

The `borderColor` works, you only need to declare its width because by default it is set as undefined - [demo](https://jsfiddle.net/BlackLabel/9eskc8Ld/).

**Comment by TorsteinHonsi** [comment]
@karolkolodziej We changed this in v11.0. I think https://api.highcharts.com/highcharts/tooltip.borderColor should inform that  if the border color is not showing, a `borderWidth` should to be set.
