### ISSUE TITLE
API documentation: minorTicksPerMajor missing & incorrect version numbering  

### ISSUE THREAD

**Issue by htvilde-eccoit** [highcharts/highcharts#20259]
Context: Unsure if this is strictly a _bug_, but not a feature in any way. The  api[dot]highchart[dot]com did not list a specific documentation contact us way.
Submitting this to clarify for future users . Used way too long to figure out why this didn't work correctly (as it solves a lot of headache, I really wanted this to work). I am using Highcharts JS v10.2.0 (2022-07-05)
Not familiar enough with git/github to create a request with documentation bugfix.

[Related changelog: https://www.highcharts.com/changelog/#highcharts-v11.0.0](https://www.highcharts.com/changelog/#highcharts-v11.0.0) with the [feature request: https://github.com/highcharts/highcharts/issues/13338](https://github.com/highcharts/highcharts/issues/13338)

#### Expected behaviour
The correct version numbering for minorTicksPerMajor  is present for x-, y-, and z-axis in the documentation.

#### Actual behaviour
The version numbering appears **missing** for minorTicksPerMajor when reading /chart/xAxis/ and /chart/yAxis/ documentation.
The version numbering 5.0.0 appears for minorTicksPerMajor when reading /chart/zAxis/ documentation.

#### Live demo with steps to reproduce
[https://api.highcharts.com/highcharts/xAxis.minorTicksPerMajor [Visited 10:30 06/12/2013]](https://api.highcharts.com/highcharts/xAxis.minorTicksPerMajor)
![xAxis](https://github.com/highcharts/highcharts/assets/118511771/3c2c9118-47d6-4646-b333-26aa9292ec40)

[https://api.highcharts.com/highcharts/yAxis.minorTicksPerMajor [Visited 10:30 06/12/2013]](https://api.highcharts.com/highcharts/yAxis.minorTicksPerMajor)
![yAxis](https://github.com/highcharts/highcharts/assets/118511771/45a2dc04-1483-4805-8f84-090bf50b95f9)

[https://api.highcharts.com/highcharts/zAxis.minorTicksPerMajor [Visited 10:30 06/12/2013]](https://api.highcharts.com/highcharts/zAxis.minorTicksPerMajor)
![zAxis](https://github.com/highcharts/highcharts/assets/118511771/b43e5f66-1ea3-4398-a94b-4fb4deb87281)

#### Product version

Highcharts v11.2.0 - Generated from branch [master](https://github.com/highcharts/highcharts/tree/master) (commit [3ff1d0d25f](https://github.com/highcharts/highcharts/commit/3ff1d0d25f)), on Mon Oct 30 2023 15:46:29 GMT+0100 (Central European Standard Time)

#### Affected browser(s)
Not relevant, behaviour observed on chrome Version 119.0.6045.200 (Official Build) (64-bit).

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! The `minorTicksPerMajor` option was introduced in v11.0.0, but we failed to tag it accordingly. Fix coming up.
