### ISSUE TITLE
numericSymbols is typed wrong

### ISSUE THREAD

**Issue by JWahlander** [highcharts/highcharts#20272]
#### Expected behaviour
```
lang: {
   numericSymbols: null
}
```

#### Actual behaviour
Type 'null' is not assignable to type 'string[] | undefined'.ts(2322)
(property) LangOptions.numericSymbols?: string[] | undefined

**Comment by JWahlander** [comment]
@karolkolodziej  Simply since the [documentation](https://api.highcharts.com/highcharts/lang.numericSymbols) says to use `null`. [](https://api.highcharts.com/highcharts/lang.numericSymbols)

> [Metric prefixes](https://en.wikipedia.org/wiki/Metric_prefix) used to shorten high numbers in axis labels. Replacing any of the positions with null causes the full number to be written. Setting numericSymbols to null disables shortening altogether.

**Comment by TorsteinHonsi** [comment]
_Internal note_
@karolkolodziej We should fix the docs (typing) to reduce the ambiguity of the API and type definitions. If `undefined` works, then we should stick with that.
