### ISSUE TITLE
Gauge chart flickers at the beginning

### ISSUE THREAD

**Issue by gugen-otsuki** [highcharts/highcharts#20271]
#### Expected Behavior
The gauge chart (that updates every 300ms) flickers or, more precisely, the animation initiates an unnecessary number of times, as demonstrated in the provided video recording.
The problem goes away if I increase update interval.

https://github.com/highcharts/highcharts/assets/54786261/4a09fb21-541b-440f-b5d0-feee0697f6e4

Actual Behavior
Upon loading the browser, the animation executes only once instead of multiple times.

Live Demo with Steps to Reproduce
To replicate the issue, run the following JSFiddle:
[JSFiddle Demo](https://jsfiddle.net/3x1zcpma/1/)

Product Version
Version: 11.2.0

Affected Browsers
Google  Chrome 119.0.6045.200
(I did not check the behaviors with other browsers)

**Comment by karolkolodziej** [comment]
Hi @gugen-otsuki!

If you are planning on updating the chart immediately after it is rendered, I suggest disabling or decreasing the animation's duration time- [demo](https://jsfiddle.net/BlackLabel/ageyz5cu/).
```js
    ...
    series: [{
        name: 'Speed',
        animation: false,
        data: [80],
    ...
```

**Comment by gugen-otsuki** [comment]
Setting animation to false fixed the issue. Thank you so much!
