### ISSUE TITLE
When the `borderRadius` attribute value of `style` is set to a `number` type in the `label` of `plotLines`, it is invalid. It must be set to a `string` type value to take effect.

### ISSUE THREAD

**Issue by hqwlkj** [highcharts/highcharts#20289]
#### Expected behaviour
![image](https://github.com/highcharts/highcharts/assets/12181423/3b723315-90f0-4265-a0c8-7c2c0975fd0b)

#### Actual behaviour
![image](https://github.com/highcharts/highcharts/assets/12181423/a1bbc0f7-7d4d-404e-966b-4efa5af475eb)

#### Live demo with steps to reproduce

[react-starter-typescript-cttsfe](https://stackblitz.com/edit/react-starter-typescript-cttsfe?file=App.tsx)

#### Product version

"highcharts": "^11.1.0",
"highcharts-react-official": "^3.2.1",

**Comment by karolkolodziej** [comment]
Hi @hqwlkj!

That isn't specific to the `plotLine` label but is true to any text rendered with `SVGRenderer`- [demo](https://jsfiddle.net/BlackLabel/xecL0d37/). 
I wouldn't consider this a bug, what is your opinion @TorsteinHonsi?

**Comment by TorsteinHonsi** [comment]
I agree it is not a bug. This is the way HTML and CSS works - [demo](https://jsfiddle.net/highcharts/aL2npdks/). A number does nothing - `px` or `%` or other units are required.
