### ISSUE TITLE
Y-axis crosshair is not visible for 3D-column or 3D-bar chart.

### ISSUE THREAD

**Issue by saurabhkolhe999** [highcharts/highcharts#20291]
#### Expected behaviour
Both X and Y-axis crosshair should be visible when crosshairs : [true, true] is set in tooltip of 3D-column or 3D-bar chart.

#### Actual behaviour
Only X-axis crosshair is visible and not of Y-axis.

#### Live demo with steps to reproduce
Please see in below jsfiddle code, I have set crosshairs: [true, true] in toolip. When you hover on any column, only X-axis crosshair will be visible and not of Y-axis.
https://jsfiddle.net/saurabhkolhe/p8ou1q92/

#### Product version
Highcharts JS v11.2.0

#### Affected browser(s)
All browsers

**Comment by bm64** [comment]
Hello @saurabhkolhe999 and thanks for reporting the issue.

It looks like it used to work correctly in v6: https://jsfiddle.net/BlackLabel/9epj4yvk/

_Internal note:_
Unable to bisect.
