### ISSUE TITLE
Color of scatter chart gets overridden by heatmap

### ISSUE THREAD

**Issue by mbores** [highcharts/highcharts#20297]
When creating a chart that has both a heatmap and a scatter line, and the scatter line is laid over the heat map...

#### Expected behaviour
The scatter line should use the color specified in the code.

#### Actual behaviour
The scatter line's markers use colors from the heatmap's color scale

#### Live demo with steps to reproduce
[[https://jsfiddle.net/BlackLabel/spfu480q/]](https://jsfiddle.net/BlackLabel/spfu480q/)

#### Product version
Highcharts 11.2.0

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
Hi @mbores!

The heatmap has nothing to do with the scatter colour change, the `colorAxis` has. [Maybe on this demo it is easier to see.](https://jsfiddle.net/BlackLabel/f2k9bxtr/)

If you need a fixed colour for one particular series, set `colorAxis: false` for this series- [demo](https://jsfiddle.net/BlackLabel/dyh6jvme/).
Read more in t[he API](https://api.highcharts.com/highcharts/series.scatter.colorAxis).
