### ISSUE TITLE
Highcharts width exceeds container div on first load

### ISSUE THREAD

**Issue by jja-financial-com** [highcharts/highcharts#20334]
When viewing a chart in a small screen, the chart overflows and gets hidden under the vertical scrollbar. This issue is reproducible when the vertical scrollbar is not present initially and appears when the chart is fully rendered.
![image](https://github.com/highcharts/highcharts/assets/64769804/1bdb8b69-0911-435c-95a9-a3f45d667ebc)

Once a resize happens, chart redraws and the issue is fixed.
![image](https://github.com/highcharts/highcharts/assets/64769804/5a19cc2f-373c-4142-87f8-594b965bd4dc)

![image](https://github.com/highcharts/highcharts/assets/64769804/f9f81aff-d8d0-4852-a8a5-ddfc6c960217)
highcharts-container seems to be overflowing the container

This issue is actual only for small screens and works fine if scrollbar is not needed or if scrollbar is present without highcharts

#### Expected behaviour
Y axis labels should not overflow the container

#### Actual behaviour
Y axis labels seems to overflow the container

Internally in our projects, while using similar configuration, the tooltip is also overflowing outside the chart window
![image](https://github.com/highcharts/highcharts/assets/64769804/23dac25e-208e-4126-aa41-e08ed1f6472c)

#### Live demo with steps to reproduce
https://jsfiddle.net/jijojames18/0rdf9sha/52/

#### Product version
Highstock v11.2.0

#### Affected browser(s)
All major browsers

**Comment by bm64** [comment]
Hello @jja-financial-com and thanks for reporting the issue.

Looks like it used to work correctly in v10.3.3 and has been broken since v11: https://jsfiddle.net/BlackLabel/0gv5Lx2c/

**Comment by jja-financial-com** [comment]
> Hello @jja-financial-com and thanks for reporting the issue.
> 
> Looks like it used to work correctly in v10.3.3 and has been broken since v11: https://jsfiddle.net/BlackLabel/0gv5Lx2c/

Yes seems like it. We upgraded from 9.3.3 to v11 last month and this issue started from then

**Comment by bm64** [comment]
Actually, it looks like the issue is reproducible without Highcharts Stock; here is the simplified demo: https://jsfiddle.net/BlackLabel/w59ex4da/

**Comment by bm64** [comment]
@jja-financial-com 

It looks like v11.3 fixed the issue, at least on my end. Could you confirm if it works correctly now?

**Comment by jja-financial-com** [comment]
> @jja-financial-com
> 
> It looks like v11.3 fixed the issue, at least on my end. Could you confirm if it works correctly now?

We will upgrade the library and check 
Thanks @bm64

**Comment by jja-financial-com** [comment]
@bm64 
We can still reproduce this after upgrading to 11.3.0. This is also still reproducible in the jsfiddle

**Comment by bm64** [comment]
@jja-financial-com I've tried to recreate the issue with the original jsfiddle, but the labels work correctly on my end: https://jsfiddle.net/BlackLabel/kwmf45t3/
Could you provide me with more information about the problem?

**Comment by jja-financial-com** [comment]
In the fiddle https://jsfiddle.net/jijojames18/0rdf9sha/52/, when it is first loaded the y axis labels is not fully visible 
![image](https://github.com/highcharts/highcharts/assets/64769804/34744efb-8971-459e-9366-4111da824703)
On resizing the window, labels align correctly
![image](https://github.com/highcharts/highcharts/assets/64769804/d51bbb4e-5a77-4196-a01e-5da76898e027)

**Comment by TorsteinHonsi** [comment]
@bm64 @jja-financial-com Are you guys on the same browser and/or system? Windows and Mac may deal with this differently.

**Comment by jja-financial-com** [comment]
I am using Brave browser on windows

**Comment by bm64** [comment]
Just have tested it on Windows Chrome and Brave and can confirm that the issue occurs there. However it seems to work fine on Windows Microsoft Edge and macOS in general.

**Comment by KacperMadej** [comment]
@jja-financial-com 
If when creating the chart changes the page layout and causes its recalculation (like adding a visible scrollbar that on Windows reduces container's width by default) I suggest reconsidering the page layout to avoid this problem or call `this.setSize(void 0, void 0, false);` in the chart's load event (so it runs only once instead of calling `chart.reflow` on `redraw` because that even runs more frequently).
Your demo modified: https://jsfiddle.net/BlackLabel/hqt9j1po/1/
Please let me know how this works for you as a workaround.
