### ISSUE TITLE
Highcharts Tooltip not able to align to custom react tooltip

### ISSUE THREAD

**Issue by Satyam7Jha** [highcharts/highcharts#20348]
Here Custom tooltip injected via react portal into element created by tooltip's formetter() function.Everything works great until I dynamicaly change height of tooltip content . Highchart tooltip simply does not aligned after height is changed.

#### Expected behaviour
Tooltip should be aligned properly

#### Actual behaviour
it is only aligned when we hover second time on toolitp

#### Live demo with steps to reproduce
https://codesandbox.io/p/sandbox/highcharts-custom-tooltip-forked-mytdxy?file=%2Ffeatures%2FHighchartsTooltip.ts%3A84%2C35

https://github.com/highcharts/highcharts/assets/75986382/3f056c79-0d3d-4aea-8241-920086d3e4c4

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
Hi @Satyam7Jha! 

It looks like the attributes you are trying to manually set are causing the issues. Please see:
```ts
      tooltip.label.box.attr({
        height: textEl.offsetHeight + 12,
        width: textEl.offsetWidth + 16,
      });

      tooltip.label.attr({
        height: textEl.offsetHeight,
        width: textEl.offsetWidth,
      });
```

From what I can see, setting only attributes to the `box` seems sufficient.
Could you please check the lines mentioned above and see if all are necessary?

**Comment by Satyam7Jha** [comment]
Hey i followed this blog : https://www.highcharts.com/forum/viewtopic.php?t=49412
here in last comment they shared the example

**Comment by Satyam7Jha** [comment]
I will be very helpful if you update the codesand box to fix the tooltip position issue. Thanks
https://codesandbox.io/p/sandbox/highcharts-custom-tooltip-forked-mytdxy?file=%2Ffeatures%2FHighchartsTooltip.ts

**Comment by karolkolodziej** [comment]
@Satyam7Jha as far as I see, you've already removed the troublesome part of the `HighchartsTooltip`.
How does that work for you?

**Comment by Satyam7Jha** [comment]
it still there 😞 
<img width="1754" alt="image" src="https://github.com/highcharts/highcharts/assets/75986382/2c1546e3-c2fb-41e6-92f6-29748e8a074b">

**Comment by karolkolodziej** [comment]
Hmm, that is kind of strange... Have you tried changing it locally? It seems like the codesandbox is playing tricks...

**Comment by Satyam7Jha** [comment]
yes , i am getting same behaviour in local.

**Comment by Satyam7Jha** [comment]
So here we are updating width and height, is there a way to update the position as well respect to new injected tooltip,
by seeing it looks like position is one render cycle behind, cause if you hover on tooltip again tooltip is aligned properly then.

**Comment by karolkolodziej** [comment]
From Highcharts perspective it doesn't look like a bug. 
[It looks like you've created a similar question on the React wrapper](https://github.com/highcharts/highcharts-react/issues/447)- please continue the discussion there because it seems to be Portal related issue. 
I'm sure someone from the React team will answer you shortly- I'm going to close this issue for now.
