### ISSUE TITLE
`yAxis.stackLabels.textAlign` does not work with `yAxis.stackLabels.rotation`

### ISSUE THREAD

**Issue by magnusanderson-wk** [highcharts/highcharts#20346]
#### Expected behaviour
The rotation's anchor should be about the anchor for the textAlign.

#### Actual behaviour
The rotation's anchor is around the center of the text, wherever that ends up being placed pre-rotation

Here is an example:
https://jsfiddle.net/magnusandersonwk/f8wtqzj7/4/
The first chart has no rotation and functions as expected
The second chart has rotation and otherwise is identical to the first, showing the broken behavior
The third chart has one label aligned correctly with explicit `x,y` values to demonstrate. Note this is not a viable workaround as all the other labels have their positions screwed up as a result.

#### Product version
11.1.2

**Comment by bm64** [comment]
Hi @magnusanderson-wk and thanks for reporting the issue

**Comment by Tzarao** [comment]
@magnusanderson-wk just a quick note, removing `textAlign: "left"` will center in better, but it does still overlap with the column

**Comment by magnusanderson-wk** [comment]
Yes, if you remove `textAlign` then the bug regarding `textAlign` does not present itself. I would like to use that property, though.

**Comment by oysteinmoseng** [comment]
Internal note: Stack labels should generally work like data labels, if they don't we are doing something wrong.

**Comment by magnusanderson-wk** [comment]
If I write a PR to fix this, would it be merged? I work for a large highcharts customer (Workiva) and we need this feature

**Comment by TorsteinHonsi** [comment]
@magnusanderson-wk If you have a fix for it, we'll consider merging it, provided that it meets our quality standards. Under any circumstance, we are happy for ideas pointing us towards the right solution.

**Comment by TorsteinHonsi** [comment]
PS: I found this to work:
```diff
diff --git a/ts/Core/Axis/Stacking/StackItem.ts b/ts/Core/Axis/Stacking/StackItem.ts
index 188567d9cc..e1f0a93032 100644
--- a/ts/Core/Axis/Stacking/StackItem.ts
+++ b/ts/Core/Axis/Stacking/StackItem.ts
@@ -318,7 +318,11 @@ class StackItem {
                 x: label.alignAttr.x,
                 y: label.alignAttr.y,
                 rotation: options.rotation,
-                rotationOriginX: labelBox.width / 2,
+                rotationOriginX: labelBox.width * {
+                    left: 0,
+                    center: 0.5,
+                    right: 1
+                }[options.textAlign || 'center'],
                 rotationOriginY: labelBox.height / 2
             });
 
```

**Comment by TorsteinHonsi** [comment]
@magnusanderson-wk I just created a PR, https://github.com/highcharts/highcharts/pull/20604, it is better that we create it so it has permission to run through all our CI. I'd be happy if you test it and provide feedback.
