### ISSUE TITLE
2 task bars on a series in gantt chart with 2 columns in y-axis

### ISSUE THREAD

**Issue by EdwinKBiju** [highcharts/highcharts#20343]
#### Expected behaviour

Dear Team,

Actually gantt chart is displaying correctly, but y-axis values is not showing. In my case Y-axis is having 2 columns. How to get Y-axis values in each row in gantt chart using Highcharts

Here I'm attaching JS Fiddle for your reference. https://jsfiddle.net/prjLd1oq/

Mention : @karolkolodziej,

Please give me solution for the same.

Best Regards,
Edwin K Biju

**Comment by bm64** [comment]
Hello @EdwinKBiju 

In this configuration with two task bars you might need to use `formatter`: https://jsfiddle.net/BlackLabel/gvfau4bc/

Let me know if it was what you were looking for.

**Comment by EdwinKBiju** [comment]
Hello @bm64,

Thank you so much for your reply and it is working fine.
And need one more support in this, is it possible to add one more column in y-axis and split each row of column into two.

![image](https://github.com/highcharts/highcharts/assets/94607782/eab28e21-d757-44ef-9509-74ac9cb1f222)

Please find the attached image for your reference.

Please give me one solution for that.

Best Regards,
Edwin

**Comment by bm64** [comment]
Hello @EdwinKBiju,

Unfortunately, the layout you described is currently not supported in the Gantt chart. However, I've created a feature request for it https://github.com/highcharts/highcharts/issues/20367. Feel free to leave your feedback if you wish to describe your use case in more detail.
