### ISSUE TITLE
Annual Wheel with Highchart?

### ISSUE THREAD

**Issue by soka1964** [highcharts/highcharts#20344]
![image](https://github.com/highcharts/highcharts/assets/75725157/1fbd7012-39e0-499d-9fd8-f9a5b15d8a3b)
I want to create a Annual Wheel like the one I have attached. Is that possible with Highchart sunBurst or other?

Regards,
Søren

**Comment by bm64** [comment]
Hello @soka1964 

Yes, something like that should be possible to create with sunburst series. Here is an example demo: https://jsfiddle.net/BlackLabel/mrLabs7v/
We use github strictly for feature request / bug tracking, so we can't really help with the configuration here, but feel free to reach out our other [support channels ](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with configuration.
