### ISSUE TITLE
max and min threshold for line

### ISSUE THREAD

**Issue by jtmkrueger** [highcharts/highcharts#2035]
Pretty sure this is going to be a feature request.

I'd like to be able to have a max and min threshold (preferably for each point) and be able to select the threshold colors for each and still have a 'within threshold' color. 

Is this possible with a line graph (or any graph, as I could hack an area to kinda look like a line...)? 

The documentation for this feature is non-existent on the website, and the only example I could find was the [jsfiddle that popped up with the beta announcement](http://jsfiddle.net/highcharts/YWVHx/). I've started looking through the source, but don't see anything obvious.

**Comment by oysteinmoseng** [comment]
Closing this as solved, since we now have series.zones: https://api.highcharts.com/highcharts/plotOptions.series.zones.
