### ISSUE TITLE
Navigator xAxis plot lines show unexpected behaviour with scrollablePlotArea - Highcharts Gantt

### ISSUE THREAD

**Issue by Lameach** [highcharts/highcharts#20354]
#### Expected behaviour

Plot line added to navigator's xAxis via `chart.navigator.xAxis.addPlotLine` or by updating xAxis options (`xAxis.update({ plotLines: ... })`) should be visible in navigator when scrollablePlotArea is enabled.

#### Actual behaviour

The plot line is hidden under the navigator pane and part of it is visible at the bottom of the chart, and its height is bigger than it should be.

#### Live demo with steps to reproduce

https://jsfiddle.net/Lameach/m1ch2jge/1/

Scroll to the bottom of the chart with an error in the live demo to see the erroring plot line.

**Comment by bm64** [comment]
Hello @Lameach and thanks for reporting the issue.
