### ISSUE TITLE
Piechart; Automatically inserted empty tspans in datalabel and tooltip create unwanted line breaks

### ISSUE THREAD

**Issue by HRworksMaw** [highcharts/highcharts#20375]
#### Expected behaviour
No unrequested line breaks in return-string of the formatter of datalabel and tooltip in a piechart, when these return-strings are (very) long. 

#### Actual behaviour
In a piechart, at a certain screensize and with (very) long return-strings, 'tspans' are inserted into the formatter-return-string. These create unwanted line breaks.

<img width="501" alt="2_line_breaks" src="https://github.com/highcharts/highcharts/assets/149704003/8735a3ba-9413-4dc3-899c-a0cd9b515518">

#### Live demo with steps to reproduce
https://jsfiddle.net/Ldmk96cn/3/
(Minimize screensize to see 1 or more line breaks inserted into the datalabel - minimize even more to also see the breaks in the tooltips)

#### Product version
Highcharts 11.2.0

#### Affected browser(s)
Chrome, Firefox

**Comment by TorsteinHonsi** [comment]
Hi,

You can add `whiteSpace: 'nowrap'` to prevent that: https://jsfiddle.net/highcharts/9k31muhp/

**Comment by HRworksMaw** [comment]
Thank you for the quick reply! We are testing this solution since it seems it doesn't solve all our (ideal) requirements (i.e. above all prevent the shrinking of the chart as much as possible to maintain a high readability).

Nevertheless, also with adding `whiteSpace: 'nowrap'` to the tooltip, the unwanted line breaks / white space in the tooltip persist. Do you have any solution for this? 

Here another screenshot with `whiteSpace: 'nowrap'` added to the tooltip for illustration:
![tooltip_line-breaks](https://github.com/highcharts/highcharts/assets/149704003/f9bc5a66-7943-43a6-a11f-bffb3b101e1f)

**Comment by TorsteinHonsi** [comment]
You're welcome! I can't seem to reproduce the tooltip empty lines in [my fiddle](https://jsfiddle.net/highcharts/9k31muhp/). Can you help me? Any particular text or tooltip width that is required?

**Comment by HRworksMaw** [comment]
I had tried to reproduce the tooltip-issue in jsfiddle but unfortunately unsuccessfully (when minimizing the window the chart went out of view and therefore the tooltip was not visible anymore), that's why I sent the screenshot. 

With stackblitz it seems to be more feasible: https://stackblitz.com/edit/stackblitz-starters-bmuw17?file=src%2Findex.tsx 

Here, the chart also will disappear partly when minimizing the window - but if you hover over it you will see that in the tooltip there appear line breaks (which lead to empty lines). 
![tooltip_line-breaks_stackblitz](https://github.com/highcharts/highcharts/assets/149704003/5a872e03-6aa1-49c3-a9fc-b047f06b1745)

**Comment by karolkolodziej** [comment]
Hi @HRworksMaw! 
I've tried different combinations of chart width and still, I'm not able to recreate that.
Could you please help get the same result? Any particular steps?

**Comment by karolkolodziej** [comment]
@HRworksMaw thank you for the explanation, I didn't go this narrow. Now I'm able to recreate it.

Internal note:
The space is added here:
https://github.com/highcharts/highcharts/blob/631a053a404f49f05298aafd898829c6be976fa0/ts/Core/Renderer/SVG/TextBuilder.ts#L341
But for some reason the `whiteSpace: 'nowrap'` is ignored here.

**Comment by magdalena-gut** [comment]
I analyzed this issue, and it doesn't seem to be a bug. The `tooltip` is responsible for overall styling and content control, while `series.tooltip` focuses on series-specific content tweaks. Since the `style` option isn't available in `[series.tooltip](https://api.highcharts.com/highcharts/plotOptions.series.tooltip)`, styles need to be set in the main `[tooltip](https://api.highcharts.com/highcharts/tooltip.style)` configuration. That's why the `no-wrap` wasn't applied—styles aren't read from `series.tooltip`. 

Here's the updated demo: https://jsfiddle.net/BlackLabel/3k1yp4xr/. 
@HRworksMaw, please confirm if it's working correctly on your end now.

**Comment by HRworksMaw** [comment]
@magdalena-gut Thank you very much for looking into this! We applied your solution and it works for us - thank you!!

**Comment by magdalena-gut** [comment]
Great to hear! You're welcome!
