### ISSUE TITLE
Cannot change XRange series color

### ISSUE THREAD

**Issue by oleksiy-liulin** [highcharts/highcharts#20394]
#### Expected behaviour
User should have possibility to change color of a XRange series.

#### Actual behaviour
User cannot change color of a XRange series (while the border color is changed properly).

#### Live demo with steps to reproduce
https://jsfiddle.net/vrms6ytw/
1. run demo (series is created with pink color and red border)
2. press Update button (doing this user wants to change series color to lime with green border but only border color is changed)

#### Product version
Highcharts 11.x

#### Affected browser(s)
Chrome, Edge

**Comment by bm64** [comment]
Hello @oleksiy-liulin and thanks for reporting the issue.

As a workaround you can use and update `colors` array: https://jsfiddle.net/BlackLabel/tdys4uq2/
