### ISSUE TITLE
Dragging networkgraph nodes causes stretching instead of shifting

### ISSUE THREAD

**Issue by magdalena-gut** [highcharts/highcharts#20405]
#### Actual behaviour
Dragging one of the nodes (such as the 'A' node in the following example) causes the node to stretch v10.2.1 https://jsfiddle.net/BlackLabel/f9ne7g4x/

#### Expected behaviour 
Dragging the nodes should make the nodes move as follows:
v10.2.0 https://jsfiddle.net/BlackLabel/h0u893ae/

#### Last correct version
v10.2.0

Not sure if that was intended. Unable to bisect.

**Comment by karolkolodziej** [comment]
Internal note:
Bisected to: https://github.com/highcharts/highcharts/commit/bcfd51fb17c0d73856906c5692107d3513c825ce

**Comment by oysteinmoseng** [comment]
Internal note: Bisected to refactor of `forEach` to `for ... of` - so probably just looping over something we shouldn't
