### ISSUE TITLE
lowColor is available on the dumbbell series options, but doesn't appear in the api documentation or typescript type definitions

### ISSUE THREAD

**Issue by ryanewtaylor** [highcharts/highcharts#20403]
#### Expected behaviour

1. lowColor should be specified on the [dumbbell series documentation](https://api.highcharts.com/highstock/series.dumbbell)
1. lowColor should be specified on the TypeScript type SeriesDumbbellOptions

#### Actual behaviour

1. It is not documented as being available on the series object
2. When applying lowColor on the series, we get the a typescript error despite [lowColor being available on the DumbbellSeries type](https://github.com/highcharts/highcharts/blob/master/ts/Series/Dumbbell/DumbbellSeries.ts#L113)
    
    > Object literal may only specify known properties, and 'lowColor' does not exist in type 'SeriesDumbbellOptions'.ts(2322) 

    The following code demonstrates this

    ```typescript
    const chart = Highcharts.chart({
      chart: {
        type: "dumbbell",
      },
      title: {
        text: "Fruit Consumption",
      },
      xAxis: {
        categories: ["Apples", "Bananas", "Oranges"],
      },
      yAxis: {
        title: {
          text: "Fruit eaten",
        },
      },
      series: [
        {
          type: "dumbbell",
          name: "Jane",
          // 👇 Object literal may only specify known properties, and 'lowColor' does not exist in type 'SeriesDumbbellOptions'
          lowColor: "red", 
          data: [{ name: "thing", low: 1, high: 5 }],
        },
      ],
    });
    ```

   By casting the series object `as any` the type error goes away and the desired color is applied, but I then lose all type safety.

#### Live demo with steps to reproduce

JavaScript example

https://codepen.io/iamrewt/pen/zYbBWvK

#### Product version

- Highstock v11.2.0

#### Affected browser(s)

N/A. This is with regards to the documentation and typescript types.

**Comment by karolkolodziej** [comment]
Hi @ryanewtaylor!
 
Thank you for reporting the issue! You are right it should be added to the `dumbbell` API documentation.

**Comment by ryanewtaylor** [comment]
@karolkolodziej, the TypeScript type for lowColor on the serries is also missing forcing me to cast it as any to avoid compiler warnings. Would this GitHub issue cover both cases?

**Comment by jedrzejruta** [comment]
@ryanewtaylor as a workaround, you can use the `lowMarker.fillColor` [property](https://api.highcharts.com/highcharts/series.dumbbell.lowMarker.fillColor), which provides the type safety and has the same result: [https://stackblitz.com/edit/typescript-v7bvof?file=index.ts](https://stackblitz.com/edit/typescript-v7bvof?file=index.ts)

It is quite confusing, as in the docs it is stated that alternatively, the lower dot color can be changed by `series.lowColor`: [https://www.highcharts.com/docs/chart-and-series-types/dumbbell-series](https://www.highcharts.com/docs/chart-and-series-types/dumbbell-series) whereas the primary choice should still be the `lowMarker`. Any thoughts on this @TorsteinHonsi?

**Comment by TorsteinHonsi** [comment]
Yes I agree, a bit confusing. I am not too familiar with it, but I would assume that the higher-level options `color` and `lowColor`, should be prefered. And the `marker` and `lowMarker` options should be used only when a specific marker setting is required?

**Comment by jedrzejruta** [comment]
> I think it should be changed to:
> color series.color - color for the upper dot.
> lowColor series.lowColor - color for the lower dot.

I believe it shouldn't be changed, since the `series.color` changes not only the upper dot color, but also the line connecting dots.

**Comment by magdalena-gut** [comment]
> > I think it should be changed to:
> > color series.color - color for the upper dot.
> > lowColor series.lowColor - color for the lower dot.
> 
> I believe it shouldn't be changed, since the `series.color` changes not only the upper dot color, but also the line connecting dots.

You're right. Just like we discussed, I've modified docs slightly.
