### ISSUE TITLE
Zoom range lost after scrolling

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#2041]
1. Open http://jsfiddle.net/shypwang/svZkp/
2. Grab the middle of the selected area in the navigator and move it to the left

Result: The '3m' buttons is no longer pressed and the dates in the input boxes sometimes differs from 3 months
Expected: That the range of 3 months stays when panning

**Comment by vodanh109** [comment]
http://jsfiddle.net/htusopum/
Hi, I still met this issue when using back button on scrollbar or drag the scrollbar button. And sometimes the scrollbar is freezed, and cannot scroll anymore. It worked again when I switch to another selector then switch back again
