### ISSUE TITLE
Highstock not updated

### ISSUE THREAD

**Issue by kai2468** [highcharts/highcharts#20419]
#### Expected behaviour
Highstock (https://code.highcharts.com/stock/highstock.js) updated to 11.3 like all the rest of the Highcharts files. This is causing issues if you have a stock chart and a map on the same page. The map will not load because of the mismatching version. 

#### Actual behaviour
Its still on 11.2.

#### Live demo with steps to reproduce
https://jsfiddle.net/b5m4e91h/1/

When I hard code both to use 11.3, the stock chart and map both render fine.

#### Product version
Latest

**Comment by karolkolodziej** [comment]
Hi @kai2468! 

There might have been some cache issues when we released 11.3.0.

Could you please check now and confirm if you still see the issue? 
I've fiddled with your demo and everything works as expected for me.

**Comment by kai2468** [comment]
Hi, still not working over here. Opening https://code.highcharts.com/stock/highstock.js still shows 11.2 for me, tried on another device too just in case it was caching and same issue there as well.

https://jsfiddle.net/j4xtwgyq/ - Can see both a stock chart and a map when I hard code to 11.3
https://jsfiddle.net/b5m4e91h/1/ - Can only see a stock chart without hardcoding.

**Comment by karolkolodziej** [comment]
We've flushed the cache on our end, please try again.

**Comment by kai2468** [comment]
Perfect, looks to be working now. Thanks :)
