### ISSUE TITLE
Property 'cumulativeSum' does not exist on type 'Point'.

### ISSUE THREAD

**Issue by dartess** [highcharts/highcharts#20424]
#### Expected behaviour

`Point` interface can include `cumulativeSum`

#### Actual behaviour

`Property 'cumulativeSum' does not exist on type 'Point'.`

#### Live demo with steps to reproduce

https://stackblitz.com/edit/typescript-y5ykdm?file=index.ts

#### Product version

`"highcharts": "11.3.0"`

`highcharts/highstock`

**Comment by TCampbellSL** [comment]
Hi, I am happy to take on this issue!

**Comment by dartess** [comment]
> that are mostly being used internally

Are there public ways to get the cumulative amount in the tooltip formatter callback? If cumulativeSum is not public, its use will be dangerous for me.

**Comment by bm64** [comment]
@dartess As I said, solution with extending interface or declare module is intended way to handle such issues and you don't need to worry about using it. It applies to many other properties and more about this you can read in our official documentation here: https://github.com/highcharts/highcharts-angular?tab=readme-ov-file#property-xxx-does-not-exist-on-type-yyy
