### ISSUE TITLE
Zones API is broken in 11.13.0

### ISSUE THREAD

**Issue by OVO-Josh** [highcharts/highcharts#20426]
#### Expected behaviour
The zones API allows you to set the colour of your bars based on the data. For example the following code produces light green bars if the bar has a value below 0 or dark if above:

`zones: [
          {
            value: 0,
            color: '#B6D727',
          },
          { color: '#43B65A' },
        ],`

#### Actual behaviour
In v11.13.0 this now does not work and all bars have a random colour. If I downgrade back to v11.12.0 it works correctly again.

#### Product version

Highcharts v11.13.0

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Can you provide a live demo of this? I tried to reproduce it here, but the code you provided works as intended: https://jsfiddle.net/highcharts/etb3k258/

**Comment by jakubSzuminski** [comment]
@TorsteinHonsi I believe that there's a difference in behavior between `v11.2.0` and `v11.3.0` in this demo: https://jsfiddle.net/gb09soaj/

**Comment by TorsteinHonsi** [comment]
### Simplified demo
https://jsfiddle.net/highcharts/v2zkpxa5/
