### ISSUE TITLE
v11.3.0: regression with Point constructor

### ISSUE THREAD

**Issue by cexbrayat** [highcharts/highcharts#20439]
#### Expected behaviour
```
const point = new Highcharts.Point();
```

should not throw

#### Actual behaviour

Using v11.3.0, this throws with:

```
TypeError: Cannot read properties of undefined (reading 'options')
          at C.applyOptions (node_modules/highcharts/highcharts.js:8:126824)
          at new C (node_modules/highcharts/highcharts.js:8:129878)
``` 

#### Live demo with steps to reproduce

https://jsfiddle.net/12whdv8t/

Switch version to v11.2, and there are no errors.

#### Product version

v11.3.0

**Comment by karolkolodziej** [comment]
Hi @cexbrayat! 

Thank you for reporting the issue! 
Could you please explain what is the use case of this code? 
Why would you create a Point instance without any arguments?

_Internal note:_ 
1. Bisected to: https://github.com/highcharts/highcharts/commit/7683a28396b6097f563d0cae26706148f54e3ca7
2. Is it safe to assert `public series!: Series;`?
3. It looks like we still have the documentation for `init` that was removed: [init API](https://api.highcharts.com/class-reference/Highcharts.Point#init).
4. Point constructor documentation is missing: [Point API.](https://api.highcharts.com/class-reference/Highcharts.Point)

**Comment by cexbrayat** [comment]
Hi @karolkolodziej 
Thanks you for your anwser.

This is in testing code where we manually build points and spy on some of their methods, something like:
```ts
      const point = new Point();
      spyOn(point, 'setState');
```

**Comment by karolkolodziej** [comment]
Thanks for the explanation! 
I guess you could add arguments to the `Point` constructor with missing elements- [demo](https://jsfiddle.net/BlackLabel/ra4nf8j1/).
```js
const point = new Highcharts.Point({
  chart: {
    options: {
      chart: {
        colorCount: 0
      }
    }
  },
  autoIncrement: function() {},
  options: {}
});
```
It should be sufficient for the sake of the test.
