### ISSUE TITLE
Map zoom

### ISSUE THREAD

**Issue by OClaeys** [highcharts/highcharts#20441]
we have a problem with the legend and the zoom for maps with version 11.1 which also appears in v11.3

for example, I click on a variable in the legend. Once I zoomed on the map, this variable reappeared.
https://www.highcharts.com/demo/maps/data-class-ranges
=> ex: I click on the green "10 -30", after zooming, the green reappears while "10-30" is still crossed out

can you tell me when this feature will be available again?

**Comment by karolkolodziej** [comment]
@OClaeys  thank you for reporting the issue! 

_Internal note:_ 
When the `colorAxis` legend item is deselected and if you zoom in the fill appears once again- [simplified demo](https://jsfiddle.net/BlackLabel/gcn3fevm/).
It looks like the `setView` method is the problem here.

**Comment by karolkolodziej** [comment]
It has stopped working in v11.0.0- unable to bisect.

**Comment by KacperMadej** [comment]
_Internal debugging note:_
The visibility seems to be wrongly reverted in here:

https://github.com/highcharts/highcharts/blob/a07e4cdfd6564762ae24c2f6669e780d1c5bf4ab/ts/Series/Map/MapSeries.ts#L982-L984
