### ISSUE TITLE
DataGrid: disabling headers also disables cells

### ISSUE THREAD

**Issue by stitot** [highcharts/highcharts#20445]
#### Expected behaviour
`dataGridOptions.columnHeaders.enabled: false` should only disable headers

#### Actual behaviour
Disables headers AND all datacells, leaving the entire grid empty

#### Live demo with steps to reproduce
[https://jsfiddle.net/stitot/mpcyte7q/8/](https://jsfiddle.net/stitot/mpcyte7q/8/)

#### Product version
Dashboards v1.2.0
DataGrid v1.2.1

#### Affected browser(s)
Chrome 120.0.6099.216
Safari 17.2.1

**Comment by karolkolodziej** [comment]
Hi @stitot! 

You are right it is an obvious bug. As far as I see it works that way from the get-go.
