### ISSUE TITLE
Zones break area series when navigator enabled

### ISSUE THREAD

**Issue by jakubjanuchta** [highcharts/highcharts#20440]
#### Expected behaviour
Zones display correctly for area series when navigator enabled

#### Actual behaviour
Zones break area series when navigator enabled

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/tu4afLh8/

#### Product version
Highcharts v11.3.0

#### Last working version
Highcharts v11.2.0

#### Affected browser(s)
All

**Comment by robinvanpoppel** [comment]
We were also hitting this with an area chart. Disabling the navigator works, but we rolled back to 11.2.0. Thanks for reporting @jakubjanuchta .

**Comment by hubertkozik** [comment]
A workaround for that issue is to disable zones for series in a navigator.

**Live demo with a workaround:** https://jsfiddle.net/BlackLabel/4tr5qgso/
