### ISSUE TITLE
[IE8 exporting] xAxis labels overflowing

### ISSUE THREAD

**Issue by rcichy** [highcharts/highcharts#2044]
When exporting in FF xAxis labels break into two lines which is ok.
In IE8 labels stay in one line and in some cases they are unreadable.

http://jsfiddle.net/yafinee/U5VSC/

**Comment by cvasseng** [comment]
Hi! We're doing a bit of spring cleaning, and closing old issues. If you're still experiencing issues with this, please feel free to open a new issue! Thanks!
