### ISSUE TITLE
How can I create this type of combination chart using Highcharts

### ISSUE THREAD

**Issue by niralivasoya** [highcharts/highcharts#20453]
#### Expected behaviour

I want to implement the combinational chart like the below chart. 

#### Actual behaviour
<img width="474" alt="image" src="https://github.com/highcharts/highcharts/assets/32123446/965e82f5-ba6b-4b20-a9be-2b87fbc49778">

#### Product version

```
  "highcharts": "^11.1.0",
  "highcharts-react-official": "^3.2.1",
```
 
Can someone please share some reference links to create a box-plot with a scattered combination chart? Thanks in Advance

**Comment by TorsteinHonsi** [comment]
Sure, here it is: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series-scatter/jitter-boxplot/
