### ISSUE TITLE
Wrong symbol position when setting `legend.symbolHeight`.

### ISSUE THREAD

**Issue by jakubjanuchta** [highcharts/highcharts#20450]
#### Expected behaviour
When setting `legend.symbolHeight`, the symbol should be positioned correctly.

#### Actual behaviour
When setting `legend.symbolHeight`, the symbol is misaligned vertically

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/s4ypzf6h/

#### Product version
Highcharts v11.3.0

#### Last working version
Highcharts v11.2.0

#### Affected browser(s)
All

_Internal note:_
Bisected to: https://github.com/highcharts/highcharts/commit/2cf9a4c2f58d7c2b12bb92ff2ea16b8e566cc574

**Comment by KacperMadej** [comment]
**Workaround**: use `symbolWidth` - https://jsfiddle.net/BlackLabel/s4ypzf6h/35/

**Comment by hubertkozik** [comment]
I am not sure, if we should treat it as a bug, or as a wrong configuration. For example this demo: https://jsfiddle.net/BlackLabel/Lb89tfm6/ shows, that the `symbolHeight` works correctly. Can I ask you your opinion @TorsteinHonsi? Should we change the vertical position of line legend symbol?

**Comment by TorsteinHonsi** [comment]
I don't think it's a bug. Technically, with that high symbol height, the line and marker are vertically centered inside the symbol. If anything, we could have some kind of baseline or vertical align option, but I don't think that is necessary at this point, unless this is a real problem for users.

**Comment by hubertkozik** [comment]
Thank you. Let's close this ticket for now. If anyone faces that problem we will reopen.
