### ISSUE TITLE
`legend.symbolHeight` and `legend.symbolWidth` do not control colorAxis size. 

### ISSUE THREAD

**Issue by jakubjanuchta** [highcharts/highcharts#20451]
#### Expected behaviour
When setting `legend.symbolHeight` or `legend.symbolWidth`, colorAxis size changes if `colorAxis.width` or `colorAxis.height` not set.

#### Actual behaviour
When setting `legend.symbolHeight` or `legend.symbolWidth`, colorAxis size does not change.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/La5hpx4y/

#### Product version
Highcharts v11.3.0

#### Last working version
Highcharts v11.2.0

#### Affected browser(s)
All

_Internal note:_
Bisected to: https://github.com/highcharts/highcharts/commit/8e17374ec550fd6eed5eaf9f83f351287c4f6085

**Comment by jakubjanuchta** [comment]
**Workaround:** Use [colorAxis.height](https://api.highcharts.com/highcharts/colorAxis.height) and [colorAxis.width](https://api.highcharts.com/highcharts/colorAxis.width) instead. 

**Demo:** https://jsfiddle.net/BlackLabel/n01w2exq/

**Comment by oysteinmoseng** [comment]
@hubertkozik Assigning this to you, can discuss in team if needed
