### ISSUE TITLE
Map scales incorrectly when zoomed in

### ISSUE THREAD

**Issue by jomar-honsi** [highcharts/highcharts#20460]
#### Expected behaviour
After zooming in one would expect the border coordinates of the map to be preserved when resizing the browser window.

#### Actual behaviour
The border coordinates narrows towards the centre when making the window smaller

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/maps/twm-providers

- Observe original state: spanning from Alaska to Japan (appx.)
- Zoom in until Doha is invisible
- Shrink browser window to appx. Spain to eastern Turkey
- Zoom out max and observe that maps doesn't rescale to origin

#### Product version
Highcharts Maps v11.3.0

#### Affected browser(s)
Chrome 120.0.6099.224
Edge 120.0.2210.133

**Comment by oysteinmoseng** [comment]
I can't seem to reproduce this, any more specific steps/screenshots to help @jomar-honsi?

**Comment by jomar-honsi** [comment]
> I can't seem to reproduce this, any more specific steps/screenshots to help @jomar-honsi?

@oysteinmoseng please see updated "steps to reproduce".

**Comment by hubertkozik** [comment]
I am also unable to reproduce the bug. Closing as not a bug.

![map_zoom](https://github.com/highcharts/highcharts/assets/62724907/cab92ada-29b4-4992-b64e-bd39b1a19eb0)
