### ISSUE TITLE
Importing highcharts ESM and typescript

### ISSUE THREAD

**Issue by rbirkgit** [highcharts/highcharts#20462]
#### Expected behaviour

To be able to import HIghcharts with ESM and typescript types

#### Actual behaviour

I get error about missing types

#### Live demo with steps to reproduce

I have this code:
```
import * as Highcharts from 'highcharts';
import { Chart } from 'highcharts';
```

I tried converting it to ESM:

```
import { default as Highcharts } from 'highcharts/es-modules/masters/highcharts.src';
import Chart from 'highcharts/es-modules/Core/Chart/Chart.js';
```

But this gets an error:
`TS7016: Could not find a declaration file for module highcharts/es-modules/Core/Chart/Chart.js`

#### Product version
Highcharts 11.2.0

**Comment by karolkolodziej** [comment]
Hi @rbirkgit! 

You can import ESM Highcharts with TS but only from the `masters` like:
```ts
import Highcharts from 'highcharts/es-modules/masters/highcharts';
```
As far as I know, it is like this by the design- @bre1470 any comments?

**Comment by bre1470** [comment]
Correct, at the moment only masters should be used.

**Comment by rbirkgit** [comment]
I am confused. So how do you use it if you can only access Highchart object? How do you get all the other types?

**Comment by rbirkgit** [comment]
Also, how do you convert this to ESM?

```
import more from 'highcharts/highcharts-more';
import boost from 'highcharts/modules/boost';
import noData from 'highcharts/modules/no-data-to-display';
import solidGauge from 'highcharts/modules/solid-gauge';
```

I tried doing this but get errors:

```
import more from 'highcharts/es-modules/masters/highcharts-more.src';
import boost from 'highcharts/es-modules/masters/modules/boost.src';
import noData from 'highcharts/es-modules/masters/modules/no-data-to-display.src';
import solidGauge from 'highcharts/es-modules/masters/modules/solid-gauge.src';
```
`./projects/lib/src/lib/hcmp-lib.module.ts:36:10-15 - Error: export 'default' (imported as 'boost') was not found in 'highcharts/es-modules/masters/modules/boost.src' (module has no exports)`

**Comment by bre1470** [comment]
TypeScript sources are not equal to ESM source. TypeScript supports ESM mix with certain options in tsconfig.json, but ESM requires always JS files as references. As soon as you reference a Highcharts module, the Highcharts namespace contains the necessary types. This only works with the masters. A list of all types (excluding options) can be found on this [API page](https://api.highcharts.com/class-reference/Highcharts).

If you like to have typing in ESM then you should combine TypeScript with a bundler. Here is an [example setup](https://github.com/bre1470/testproject-es6) with Webpack. We will update our documentation to highlight the differences between a Vanilla ESM and TypeScript ESM.

**Comment by rbirkgit** [comment]
Thanks. I think I got it working. So you no longer need to manually load the modules. Just import `solid-gauge.src` etc. And for types like `Chart` you just use `Highcharts.Chart` instead of importing them separately as we used to do.

It's really hard to know as my editor, IntelliJ, cannot handle the huge type file that comes with Highcharts. You get no type support in the editor and have to guess that you type or use a property or type correctly.

**Comment by bre1470** [comment]
You can try to [increase the memory heap](https://www.jetbrains.com/help/idea/increasing-memory-heap.html) in IntelliJ, as it is limited to just 1 GB by default. Especially when working with multiple tabs this becomes insufficient.

**Comment by rbirkgit** [comment]
I played with the esm modules, but not sure it did it right. I have a simple solid gauge with these imports. This is an Angular app.

```
import Highcharts from 'highcharts/es-modules/masters/highcharts.src';
import 'highcharts/es-modules/masters/highcharts-more.src';
import 'highcharts/es-modules/masters/modules/solid-gauge.src';
```

Then I ran webpack bundle analyzer. It seems it includes more than expected and much bigger than we had before with using the standard import.

![image](https://github.com/highcharts/highcharts/assets/6342391/49a2ffd0-a742-4ed7-ad64-7fd84863eed2)

**Comment by rbirkgit** [comment]
I did a little more testing on this and my above observation is not quite correct.

In my small app I compared the size of the main bundle (parsed size) with standard import and ESM import. It went from 2.7MB to 2.55MB.

In our bigger app, it stayed the same (6.46MB). Size didn't change. That part was surprising to me. At least the size didn't grow :)

**Comment by bre1470** [comment]
Thank you for the feedback. We are working on improving the tree shaking results and ESM experience. Unfortunately the internal setup is not yet ready to produce useful declarations for all ESM files.

**Comment by fanfan1993** [comment]
look at me ,  I did  a little testing  on this,

 ESM import
import Highcharts from 'highcharts/es-modules/masters/highcharts.src';
<img width="791" alt="Pasted Graphic 1" src="https://github.com/highcharts/highcharts/assets/19665990/5f2359ac-4311-4ffe-8197-1d430a9591c8">
only 155.1KB  ()
But   main bundle (parsed size) 
<img width="863" alt="Pasted Graphic 2" src="https://github.com/highcharts/highcharts/assets/19665990/bad77e0a-9891-4596-8cfc-cac42e9f231b">
so ,  year

**Comment by nawlbergs** [comment]
So... im trying to trim some of this fat in my angular project... and here's the only two scenarios I can get running:
Heres my source-map-explorer results:
```ts
// non esm   376.22 KB  (280 highcharts.js, 92 highcharts-more.js)
import * as highcharts from 'highcharts';
import HC_more from 'highcharts/highcharts-more';
HC_more(highcharts);
import HC_solidgauge from 'highcharts/modules/solid-gauge';
HC_solidgauge(highcharts);
```

```ts
// esm 737.65 kb  (280 highcharts.js, 361 es-modules)
import highcharts from 'highcharts/es-modules/masters/highcharts.src';
import 'highcharts/es-modules/masters/highcharts-more.src';
import 'highcharts/es-modules/masters/modules/solid-gauge.src';
```
No idea what Im doing wrong... but this seems wrong. 

I really only want 3 or 4 charts (line, gauge, bar and pie).. and I would like to apply global settings if possible aka `Highcharts.setOptions(...)`

**Comment by bre1470** [comment]
Hello, @nawlbergs!

For questions about angular and its integration, please check and create issues in https://github.com/highcharts/highcharts-angular/issues.

For a regular setup, one can create a custom bundle to have more fine control of the bundle: https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-packages

In your case, it would look similar to the following and results in ~190 kB:

```ts
/**
 * @license Highcharts JS v@product.version@ (@product.date@)
 * @module highcharts/highcharts
 *
 * (c) 2009-2024 Highcharts AS
 *
 * License: www.highcharts.com/license
 */

'use strict';

import Highcharts from '../Core/Globals.js';
import SVGRenderer from '../Core/Renderer/SVG/SVGRenderer.js';
import Chart from '../Core/Chart/Chart.js';
import BarSeries from '../Series/Bar/BarSeries.js';
import GaugeSeries from '../Series/Gauge/GaugeSeries.js';
import LineSeries from '../Series/Line/LineSeries.js';
import PieSeries from '../Series/Pie/PieSeries.js';

const exports: Record<string, any> = Highcharts;

exports.Renderer = SVGRenderer;
exports.SVGRenderer = SVGRenderer;
exports.Chart = Chart;
exports.chart = Chart.chart;
exports.BarSeries = BarSeries;
exports.GaugeSeries = GaugeSeries;
exports.LineSeries = LineSeries;
exports.PieSeries = PieSeries;

export default Highcharts;

// See https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-packages
```

**Comment by bre1470** [comment]
I will close this issue for now, as the [example project](https://github.com/bre1470/testproject-es6) shows how to set up Highcharts with ESM and TypeScript.
