### ISSUE TITLE
Scatter animation broken when marker is disabled for spline

### ISSUE THREAD

**Issue by MiloszMarcinkowski** [highcharts/highcharts#20473]
#### Expected behaviour
Scatter charts animation is visible when marker is disabled for spline charts.

#### Actual behaviour
Scatter charts animation is invisible when marker is disabled for spline charts. The issue is present when spline and scatter charts are drawn together. The workaround is setting different animation duration between scatter and spline charts. 

#### Live demo with steps to reproduce
https://jsfiddle.net/92gL3s8o/

#### Product version
from 9.3.0 onwards (works in previous versions ex. 9.2.2)

**Comment by karolkolodziej** [comment]
Hi @MiloszMarcinkowski! 

Thank you for reporting the issue and providing [the workaround.](https://jsfiddle.net/BlackLabel/c418tsa3/)

_Internal note:_
Bisected to: https://github.com/highcharts/highcharts/commit/99495fcd91c29ba22f8a6e4505142f541d3d03e0
