### ISSUE TITLE
All Exports Given Default "chart" Filename

### ISSUE THREAD

**Issue by andrewhathaway** [highcharts/highcharts#20472]
#### Expected behaviour

When a custom filename is given in a request, the returned filename should match the given filename.

#### Actual behaviour

Filenames being returned as the default `chart` filename, including when using the Highcharts `exportChart` API 

#### Reproduction steps

Example: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/exporting/filename/

<img width="305" alt="image" src="https://github.com/highcharts/node-export-server/assets/1188830/b98ca364-5dee-4aa0-808e-149de324899b">

#### Notes

All posted that in the [Node Export Server repo](https://github.com/highcharts/node-export-server/issues/470) if that was the place to share this. Please close this ticket if this isn't the best space for it :)

**Comment by karolkolodziej** [comment]
Hi @andrewhathaway! 

This issue is most likely already resolved, see more details here: https://github.com/highcharts/highcharts/issues/20370

If it still doesn't work please continue the discussion on the export server repo.
