### ISSUE TITLE
dataLabels overlapping zoom in/zoom out - buttons

### ISSUE THREAD

**Issue by marvin19** [highcharts/highcharts#20476]
#### Expected behaviour
I would expect buttons to overlap `dataLabel`

#### Actual behaviour
`dataLabel` is overlapping buttons. 
![Screenshot 2024-01-19 at 10 57 10](https://github.com/highcharts/highcharts/assets/14174575/2328df49-cba3-46df-9430-0d000dce642c)
![Screenshot 2024-01-19 at 10 57 25](https://github.com/highcharts/highcharts/assets/14174575/3d7c86ec-2d4c-4005-9347-ae2094c36247)

#### Live demo with steps to reproduce
It is reproducible in several demos with datalabels and the zoom buttons, here is an example:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/eu-capitals-temp

#### Affected browser(s)
Chrome, Safari

**Comment by karolkolodziej** [comment]
As a workaround, you can set this in the callback- [demo](https://jsfiddle.net/BlackLabel/d1v0tbpz/).
```ts
this.mapNavigation.navButtonsGroup.toFront()
```

**Comment by oysteinmoseng** [comment]
Internal note: Just fix by z-index for now.
