### ISSUE TITLE
Not possible to completely change theme 

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#2048]
1. Open http://jsfiddle.net/GLMzf/
2. Change the theme by clicking the buttons

Result: The newly selected theme will merge with the existing one and the effect is that the old one won't be completely removed. Example is tooltip background after selecting theme1 and then theme2.

Expected: That there is a way to completely replace the existing theme. For example with a resetOptions() api call that would remove all custom options.

**Comment by oysteinmoseng** [comment]
This is still a relevant issue with current code. We have no way to reset options set with `setOptions`.
