### ISSUE TITLE
highchart stock chart yAxis crosshair label is not fully displayed in mobile terminal

### ISSUE THREAD

**Issue by soeasyjx** [highcharts/highcharts#20482]
#### Expected behaviour

It is desirable to provide a property that sets the offset of the reticle

For example
```js
 yAxis: {
        opposite: false,
        crosshair: {
          label: {
            enabled: true,
            style: {
              fontSize: "0.55467rem"
            }
          },
         offset:10
        },
}
```

#### Actual behaviour

Do not know what method can be used to set its offset conveniently and quickly, so as to solve the problem of being covered

#### Product version
11.3.0

#### Example figure
<img width="391" alt="image" src="https://github.com/highcharts/highcharts/assets/17918538/451f7350-18ee-480b-b2a5-bac8569f5c5b">

**Comment by induratized** [comment]
try reducing the `chart.width`

<img width="1310" alt="image" src="https://github.com/highcharts/highcharts/assets/6311837/8dc59788-2847-4f96-bcd9-a8880f1551d3">

**Comment by soeasyjx** [comment]
> 尝试将`chart.width` 下图中的宽度减小到超过窗口宽度并且十字准线标签溢出
> 
> [jsfiddle](https://jsfiddle.net/1725vk4x/2/)
> 
> <img alt="图像" width="1310" src="https://private-user-images.githubusercontent.com/6311837/298974302-8dc59788-2847-4f96-bcd9-a8880f1551d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNDAwMzEsIm5iZiI6MTcwNjMzOTczMSwicGF0aCI6Ii82MzExODM3LzI5ODk3NDMwMi04ZGM1OTc4OC0yODQ3LTRmOTYtYmNkOS1hODg4MGYxNTUxZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjdUMDcxNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWJmNjA3MmVhYmNmNzE0MjNiMWMyZjIzOTBlZWI4NDhjZTg1Y2ZjOTU3N2Y4ODI1ZmIwMTVlMjE0YzNjODFlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uxuxqYwEP-EQHxmjgkowzqLT8Zh4GoYPOSnW04CxAzQ">

It doesn't do anything

**Comment by soeasyjx** [comment]
yAxis.crosshair.label

 I don't see any support for styling transform at the moment. Is there any solution

**Comment by soeasyjx** [comment]
> try reducing the `chart.width` I inflated the width in the chart below to more than window width and the crosshair label overflowed
> 
> [jsfiddle](https://jsfiddle.net/1725vk4x/2/)
> 
> <img alt="image" width="1310" src="https://private-user-images.githubusercontent.com/6311837/298974302-8dc59788-2847-4f96-bcd9-a8880f1551d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MzYzOTMsIm5iZiI6MTcwNjQzNjA5MywicGF0aCI6Ii82MzExODM3LzI5ODk3NDMwMi04ZGM1OTc4OC0yODQ3LTRmOTYtYmNkOS1hODg4MGYxNTUxZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMTAwMTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWY4Mjg0MTFlNmJhNGJjN2E5NDNmYjNhMmMyZDE1NmI4NWRjMzFlMzFjODJmYmIyZDFmNGVmZWM2N2JjOGU3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e2qLgbLQsTizIcLzH-jy3bWe_2nfCz9AI-CZa4X0G6Y">

I use chart.width = document.documentElement. ClientWidth / 2 is the same result, did not solve my problem, urgent

**Comment by hubertkozik** [comment]
Hi @soeasyjx!
You can set the `yAxis.offset` to a number, twice as big as your `yAxis.crosshair.labels.padding` option. Please, take a look at the demo below.

**Live demo:** https://jsfiddle.net/BlackLabel/9trf25ua/
**API Reference:** https://api.highcharts.com/highstock/yAxis.offset

Could you let me know if it meets your requirements?
