### ISSUE TITLE
Data labels do line break only after resize in treegraph with styledMode

### ISSUE THREAD

**Issue by selevt** [highcharts/highcharts#20499]
#### Expected behaviour
When loading the chart, the data labels have line breaks were needed to fit in the marker.

#### Actual behaviour
The labels are in one line and line breaks are only applied once resizing the chart.

On load:
![image](https://github.com/highcharts/highcharts/assets/202473/10902194-5e7b-46d1-bb00-f6efbc65b4a9)

After resizing the window:
![image](https://github.com/highcharts/highcharts/assets/202473/11bc4736-2323-423b-a802-2fadc4f78d5e)

#### Live demo with steps to reproduce
https://jsfiddle.net/0h1Le3ou/19/
It does seem to not be completely consistent - sometimes on load of the fiddle it'll already have the line break. But saving the fiddle, so only the preview is reloaded without the full page puts it into one line consistently.

Resize the window -> labels will have line breaks

#### Product version
11.3.0

#### Affected browser(s)
Firefox, Chrome

**Comment by hubertkozik** [comment]
Hello @selevt!

Indeed, it looks, like a bug. Data labels shouldn't change after a small window resize relative to their initial load.

As one workaround, you can set `dataLabels.style.textOverflow` to `undefined`: https://jsfiddle.net/BlackLabel/wn1zx0o9/

Also, as a second workaround, I've prepared a custom plugin for that issue. If you want to use it in your project, then just copy-paste the IIFE function from the below demo.
**Live demo with a workaround:** https://jsfiddle.net/BlackLabel/6jz0vatw/
