### ISSUE TITLE
Bar overlap xAxis title 

### ISSUE THREAD

**Issue by tyumen-777** [highcharts/highcharts#20495]
#### Expected behaviour
There should be space for xAxis title

#### Actual behaviour
Bars overlap xAxis title

#### Live demo with steps to reproduce
https://jsfiddle.net/1Lksgjuf/1/

#### Product version

"highcharts": "11.1.0"

#### Affected browser(s)
All

![image](https://github.com/highcharts/highcharts/assets/75023241/4a1ab018-24bc-421a-ba8c-8bfc43d0470f)

**Comment by bm64** [comment]
Hello @tyumen-777 

That behavior is intended, and it seems to be a result of chart misconfiguration. Properties like title offset and x are intended for absolute positioning of the title, independent of other elements. Additionally, there is no algorithm to detect collisions between the series and the title. I'm not certain of the exact results you're aiming for, but consider using axis.maxPadding to reserve space for the title: https://jsfiddle.net/BlackLabel/376dskov/

**Comment by tyumen-777** [comment]
But this doesn't work on stacked columns

**Comment by tyumen-777** [comment]
@bm64 https://jsfiddle.net/0sy9oeub/2/ check this fiddle

**Comment by bm64** [comment]
In this case `chart.marginRight` property can be used to created extra space for the title: https://jsfiddle.net/BlackLabel/e6abfuhq/
We use github only for feature requests and bug tracking so with any further questions about chart configuration please contact us on out other support channels: https://www.highcharts.com/blog/support/
For example Highcharts Forum: https://www.highcharts.com/forum/
