### ISSUE TITLE
Zone  for stacked chart is not working

### ISSUE THREAD

**Issue by tyumen-777** [highcharts/highcharts#20514]
#### Expected behaviour
Zone should be dashed 

#### Actual behaviour
Zone is solid

#### Live demo with steps to reproduce
https://jsfiddle.net/7j0euwnh/

#### Product version
"highcharts": "11.1.0",

#### Affected browser(s)
All

![image](https://github.com/highcharts/highcharts/assets/75023241/c163dc79-bb63-4efd-bfc7-6ac4ea9a5d0c)
it should be something like this

**Comment by karolkolodziej** [comment]
Hi @tyumen-777!

When using `value` you need to specify the number on the axis from which it should be applied- [api](https://api.highcharts.com/highcharts/series.line.zones.value). 
[See it in the demo.](https://jsfiddle.net/BlackLabel/9d5bsvgh/)

PS.
You can use the datetime axis to handle the values more easily.
