### ISSUE TITLE
Makers still visible after hide series using boost

### ISSUE THREAD

**Issue by thyagorafaell** [highcharts/highcharts#20525]
#### Expected behavior
In a line chart with boost enabled, when we hide a series by clicking on its legend item, both the line and its markers should be hidden.

#### Actual behavior
Only the line is hidden; the markers remain visible.

#### Live demo with steps to reproduce
- Render a line with two series and boost enabled
- Zoom to a small part of the chart
- Click on a legend item to hide a series
- Live demo: https://jsfiddle.net/thyagorafaell/069Lx8vz/17/

![zoom-marker-boost](https://github.com/highcharts/highcharts/assets/3964505/acdcbaef-0e2a-43c8-a4dd-f31a44deff35)

#### Product version
11.3.0

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
Hi @thyagorafaell!

Thank you for reporting the issue! 
It was introduced in v10.2.1.

_Internal note:_
Bisected to: https://github.com/highcharts/highcharts/commit/63a119577339f4c28406b5da2142f7b6b6577028

**Comment by hubertkozik** [comment]
As a workaround, you can control the marker visibility by updating the hidden/showed series in `series.events.hide` and `series.events.show`.

**Workaround:** https://jsfiddle.net/BlackLabel/9a7k0zg1/

**Comment by thyagorafaell** [comment]
The workaround did not resolve the problem because if I zoom in on the chart, hide a series, reset the zoom, and reset the series, the markers would be shown in the boosted chart.

![hc-markers-still-visible-after-hide-series-using-boost](https://github.com/highcharts/highcharts/assets/3964505/0d1243ca-f0f2-445f-bb13-c1ea1ed7e675)

However, I could figure out another way to handle this scenario: https://jsfiddle.net/thyagorafaell/0y3mxqkr/3/.
