### ISSUE TITLE
Range selector one day button is not working as expected

### ISSUE THREAD

**Issue by nishikantparmariam** [highcharts/highcharts#20520]
#### Expected behaviour
Clicking a one day range selector button should zoom chart to show only last one day.

#### Actual behaviour
Chart is showing data for last 5 days instead of last 1 day upon clicking the one day button - 
![chart-1d-range-selector-issue](https://github.com/highcharts/highcharts/assets/7736252/b5b5686c-a740-4548-b166-a3089d62e1df)

#### Live demo with steps to reproduce
Reproducer - **https://jsfiddle.net/a15ymn74/1/**

#### Product version
Highcharts v10.3.3

#### Affected browser(s)
Tried on Chrome v120.0.6099.225

**Comment by kamil-musialowski** [comment]
Hi there! 

That could be due to the fact that the [xAxis.minRange](https://api.highcharts.com/highstock/xAxis.minRange) property is kicking in. Set it to a lower value, (i.e one day, or even 1) and everything should be fine.

https://jsfiddle.net/BlackLabel/4d9zqxe7/

**Comment by nishikantparmariam** [comment]
Thanks for the solution! Follow-up: Still, upon selecting it shows two days in the chart, how to resolve this?

**Comment by bm64** [comment]
@nishikantparmariam With the current configuration, the 1D button is supposed to show 24 hour data and it seems to look correctly. Please try this demo, select the range and see the console: https://jsfiddle.net/BlackLabel/6yhstcf3/
Could you provide me with more information about what you what to achieve? Maybe that way I will be able to suggest a solution.

**Comment by nishikantparmariam** [comment]
Currently we see that 28 and 29 both dates are shown for 1 day - 

![image](https://github.com/highcharts/highcharts/assets/7736252/73abc4c0-3c0f-4753-a834-320ff5968033)

It there a way to only show 29 data point because that's the last 1 day.

**Comment by bm64** [comment]
@nishikantparmariam please try to reduce `axis.minRange` and use `offsetMin`: https://jsfiddle.net/BlackLabel/4d9zqxe7/1/

**Comment by nishikantparmariam** [comment]
This works! Thanks a lot.
