### ISSUE TITLE
When using addPoint on a networkchart, the color and radius of my node are not set

### ISSUE THREAD

**Issue by ugoQ** [highcharts/highcharts#20534]
You can try this here (click anywhere on the chart, it makes a node "Naboo" appear but the node is blue like the others, with a small radius):

https://jsfiddle.net/67fyxn1j/2/

I am using an `addPoint` for the node, and one for the link:
```
chart.series[0].addPoint({
  color: '#ff7777',
  marker: {
    radius: 50,
    lineWidth: 1,
  },
  id: 'Naboo',
});
```
You can see that the color of the link is OK. It looks like the link is linked to a new node, but that's not the node I am trying to add.
Thanks in advance for any help.

**Comment by hubertkozik** [comment]
Hi @ugoQ!

It looks like everything related to the radius of nodes in `network graph` series works correctly. To change radius of a node, you should update `series.nodes` array, like in this demo: https://jsfiddle.net/BlackLabel/r4adtubh/
**API Reference:** https://api.highcharts.com/highcharts/series.networkgraph.nodes

We use GitHub as a tool for bugs/feature request tracking and your question is strictly a support question. Feel free to reach out to our other [support channels ](https://www.highcharts.com/blog/support/), where our support engineers will help you with the configuration of your chart.
