### ISSUE TITLE
Is it possible to have one fixed node in networkgraph ?

### ISSUE THREAD

**Issue by ugoQ** [highcharts/highcharts#20533]
I am trying to use this sort of method to get one fixed node in my networkgraph, but like in the jsfiddle, while the intended node is fixed, the others are grouped in one position :
https://jsfiddle.net/BlackLabel/kzwhna2q/

I am using highcharts 10.3.3 and highcharts-react-official 3.2.0.

**Comment by hubertkozik** [comment]
Hi @ugoQ!
We use GitHub as a tool for bugs/feature request tracking and your question is strictly a support question. Feel free to reach out to our other [support channels ](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
