### ISSUE TITLE
centerInCategory does not work for stacked charts with null values in series.data

### ISSUE THREAD

**Issue by AlexKichkailo** [highcharts/highcharts#20550]
#### Expected behavior
According to https://github.com/highcharts/highcharts/pull/12846, when centerInCategory is set to true, nulls are ignored and the stacks are centered in the category.

#### Actual behavior
When there are null values in series data, centerInCategory does not have any effect.

#### Live demo with steps to reproduce
 template: https://jsfiddle.net/c5pwszov/93/ 

#### Product version
Highcharts v11.3.0

#### Affected browser(s)
All

**Comment by jedrzejruta** [comment]
Regression introduced in Highcharts v11.2.0, unable to bisect.

**Comment by hubertkozik** [comment]
Bisected to: 4bcc16de4e0fb84eceabeeb38da62b760720e9a7.

**Comment by hubertkozik** [comment]
I've prepared a workaround for that issue. If you want to use it in your project just copy-paste the IIFE function from one of the below demos.

**OP demo with a workaround:** https://jsfiddle.net/BlackLabel/es29q7an/
**Simplified demo with a workaround:** https://jsfiddle.net/BlackLabel/cL1rmtyo/

**Comment by AlexKichkailo** [comment]
Thank you for the quick response. Downgrading to 11.1 fixes the issue with centering. I noticed that while the columns are centered, they are still thin and there is plenty of room between the categories. It seems that the chart still counts nulls when calculating column width.  Settings https://api.highcharts.com/highcharts/plotOptions.column.pointWidth makes it even worse because the columns overlap. Is this another bug?

**Comment by hubertkozik** [comment]
@AlexKichkailo I am not sure if we should treat the width of the centered columns as a bug. Let's take a look at this demo:  https://jsfiddle.net/BlackLabel/8hv2faxo/ It could be misunderstood if one of the columns is wider than the others. 

Besides that, you can freely change the width of one column, by setting `pointWidth` on the point, like here: https://jsfiddle.net/BlackLabel/xzdL7h4g/

**Comment by AlexKichkailo** [comment]
> @AlexKichkailo I am not sure if we should treat the width of the centered columns as a bug. Let's take a look at this demo: https://jsfiddle.net/BlackLabel/8hv2faxo/ It could be misunderstood if one of the columns is wider than the others.
> 
> Besides that, you can freely change the width of one column, by setting `pointWidth` on the point, like here: https://jsfiddle.net/BlackLabel/xzdL7h4g/

Thanks for your reply. I need all columns to be wider, not just one. Here is a sample chart that I am trying to improve: https://jsfiddle.net/pmtf4oq1/18/ If I set pointWidth to all series, the columns overlap. The same thing happens if I use pointWidth in your sample: https://jsfiddle.net/hcvba7ms/21/ 

What makes me think that null values are still used in calculating column width is that the columns are the same regardless of the `centerInCategory` setting.

**Comment by hubertkozik** [comment]
Hi @AlexKichkailo!

Even, if you disable `centerInCategory` and `stacking` options, like in this demo: https://jsfiddle.net/BlackLabel/h8ox7qdk/ columns are overlapping. This is not a bug, if the`pointWidth` is not set, it is being calculated based on available space, but when you set it explicitly `pointWidth` property, it is not possible anymore, which can lead to overlapping issues.

At this moment, the only issue, which is 100% certain is the issue with `centerInCategory` and `stacking` options.

**Comment by EianWright** [comment]
The workaround is not working for me. Here is a demo: [https://jsfiddle.net/av7tx2dk/](https://jsfiddle.net/av7tx2dk/). This works (without any workaround) in 11.1.0.

**Comment by Shane-Krystal** [comment]
We have an issue also on our Graph, centerInCategory is not working when we used version 11 and up. 
We need to use version 11, to fix the accessibility issues in our Graph.

Details in our Graph: 
Our Graph has a complex design. We have 15 series column. 
It has five(5) Energy usage rates, every rate has previous two years, previous one year, and current year data. 
CenterInCategory is working in version 10 and below on our Graph, but we have accessibility issues. 

Demo for the first three columns in our Graph: https://jsfiddle.net/shanecatulay/jf9ub03e/6/
Demo for the twelve(12) columns in our Graph https://jsfiddle.net/shanecatulay/3uz0br58/24/

Can you please help me on this issue?

**Comment by TorsteinHonsi** [comment]
We now have a PR for a fix.

@EianWright 's demo with the fix applied:
* https://jsfiddle.net/av7tx2dk/

@Shane-Krystal 's demos with the fix applied:
* https://jsfiddle.net/highcharts/9k7npyqh/
* https://jsfiddle.net/highcharts/srv968gf/

**Comment by EianWright** [comment]
When can we expect this fix to be released?

**Comment by hubertkozik** [comment]
@EianWright the fix should be included in the next release of Highcharts.

**Comment by Shane-Krystal** [comment]
@TorsteinHonsi  how can I implement the fixed on our Project. 
Do I need to the code here "https://github.highcharts.com/00b77b51cdbf5916a3ef03d3d8ea7a0578b89496/highcharts.js" on highcharts.js modules?

**Comment by TorsteinHonsi** [comment]
@Shane-Krystal The fix is part of Highcharts v12.0.x

**Comment by Shane-Krystal** [comment]
@TorsteinHonsi do you already have a release date for HighCharts version 12?

**Comment by hubertkozik** [comment]
@Shane-Krystal Highcharts v12.0.2 was released 2024-12-04: https://www.highcharts.com/changelog/
