### ISSUE TITLE
HTML component title update fails when caption is used

### ISSUE THREAD

**Issue by jomar-honsi** [highcharts/highcharts#20559]
#### Expected behaviour

Expect to see the effect of a programatic update of the HTML component title.

#### Actual behaviour

- If a caption is used the title is not updated by the `component.update()` call
- If a caption is not used the title update works as expected

#### Live demo with steps to reproduce
https://jsfiddle.net/jomar_honsi/uay7mhL8/126/

- Click the update button and observe that the title does not change as expected
- Remove dashboards.css and repeat
- Observe that the updated title elements get added successively
- Comment out the references to captions in lines 14 and 29
- Observe that the title is updated correctly

#### Product version
Dashboards 1.3.0
Highcharts 11.3.0

#### Affected browser(s)
Chrome, Edge

**Comment by karolkolodziej** [comment]
It looks like it has already been solved on master. 
I've just added regression tests.
