### ISSUE TITLE
Using Title in HTML component hides the caption

### ISSUE THREAD

**Issue by jomar-honsi** [highcharts/highcharts#20557]
#### Expected behaviour
Title and caption should be visible at the same time.

#### Actual behaviour
Setting title hides the caption.

#### Live demo with steps to reproduce
https://jsfiddle.net/jomar_honsi/08a429bj/42/

- Observe that the caption is visible
- Uncomment line 17
- Observe that the caption is hidden

The caption exists in the DOM also when it is not visible:
![image](https://github.com/highcharts/highcharts/assets/3593847/3aea8e68-42ce-4726-b826-49a70c1400ec)

#### Product version
Highcharts Dashboard 1.3.0
Highcharts 11.3.0

#### Affected browser(s)
Chrome, Edge

**Comment by karolkolodziej** [comment]
It is because the main content gets a fixed height as an inline styling:
![image](https://github.com/highcharts/highcharts/assets/57004120/f40433b7-0c77-4a04-86fa-708077d8738a)
[Simplified demo.](https://jsfiddle.net/BlackLabel/2huwq9b5/)
