### ISSUE TITLE
Bubble chart with navigator

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2055]
Example: http://jsfiddle.net/dhmWC/3/

Use navigator and observe effects. First bubble is translated after first use of navigator, then most right bubble is missing sometimes.

**Comment by KacperMadej** [comment]
**Workaround:** set navigator series type to `'bubble'`. Demos:
- http://jsfiddle.net/dhmWC/4/
- http://jsfiddle.net/aws9pp94/2/
