### ISSUE TITLE
Chart destroy after point hover - Cannot destructure property 'chart' of 'series'

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#20572]
#### Expected behaviour
Works as expected in Highcharts v11.2.0: https://jsfiddle.net/BlackLabel/xnukpa2d/

#### Actual behaviour
Error: `Uncaught TypeError: Cannot destructure property 'chart' of 'series' as it is undefined.`

#### Live demo with steps to reproduce
1. Open jsfiddle: https://jsfiddle.net/BlackLabel/bqcz3nw0/
2. Check the browser console

#### Product version
Highcharts + Highcharts More v11.3.0

#### Affected browser(s)
All

Originally reported on the `highcharts-rect` repository: https://github.com/highcharts/highcharts-react/issues/455

**Comment by hubertkozik** [comment]
Another demo with reproduced issue: https://jsfiddle.net/BlackLabel/ghe9rnbx/

**Comment by hubertkozik** [comment]
_Internal note:_
Bisected to: fa1cf6b24cd08748849d55718b469ff36056bab4

**Comment by hubertkozik** [comment]
Workaround for that issue: 
`(function(H) {
	H.wrap(H.Point.prototype, 'pos', function (proceed) {
    if (!this.destroyed) {
    	return proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    }
});
})(Highcharts);`

Below are some demos with applied workaround. If you want to use this workaround in your project with Highcharts v11.3.0 simply copy-paste the plugin (IIFE function).

**Demos:** https://jsfiddle.net/BlackLabel/wz9o15nt/
https://jsfiddle.net/BlackLabel/otqdz231/
