### ISSUE TITLE
Border broken at the bottom of bubbles for bubble chart

### ISSUE THREAD

**Issue by tjn-financial-com** [highcharts/highcharts#20585]
#### Expected behaviour
Bubbles should have a border around them without any break. (stroke-width: 1px)

#### Actual behaviour
The bubble border has a small break(gap) at the bottom.
![image](https://github.com/highcharts/highcharts/assets/59470487/b79f9eb4-8141-4f03-b1ba-3a7888805817)

#### Live demo with steps to reproduce
https://jsfiddle.net/cu1kvyfL/

#### Product version
Highcharts JS v11.3.0

#### Affected browser(s)
Chrome

**Comment by bm64** [comment]
Hello @tjn-financial-com 

I tested the demo but couldn't reproduce the issue. Can you please provide more details like your system, browser, and browser version? Thanks in advance.

**Comment by tjn-financial-com** [comment]
Hi @bm64 ,

I'm using Windows 10 Enterprise,
Browser: Chrome Version 121.0.6167.162

Please note that the issue is not visible if you hover the bubble.
![image](https://github.com/highcharts/highcharts/assets/59470487/4fbc89f2-dbe4-4879-993f-051513bba04b)

Thank you!

**Comment by bm64** [comment]
@tjn-financial-com, thanks! Does this issue occur only when the browser is zoomed in or out? I was able to recreate it only at 90% zoom.

**Comment by tjn-financial-com** [comment]
@bm64, it happens without any zoom. 
![image](https://github.com/highcharts/highcharts/assets/59470487/f0c48374-2f76-49f7-aade-604db6e452ca)

Thanks!

**Comment by bm64** [comment]
@tjn-financial-com you're right, this happens also on a default zoom. Thanks for all those informations. You could try increasing `marker.lineWidth` just slightly, it seems to do the trick on my end: https://jsfiddle.net/BlackLabel/h26z71bk/

**Comment by tjn-financial-com** [comment]
@bm64 , thanks for the suggestion. I tried setting `stroke-width: 1.1px ` for `.highcharts-point` since I use `styledMode` and it worked.

**Comment by TorsteinHonsi** [comment]
#### Simplified demo
Reduced to the renderer, this gap appears when the symbol is not rounded and the x value is _n_.5: https://jsfiddle.net/highcharts/2jawqr90/

0.49 or 0.51 do not present the problem. Likewise the diameter must be an integer, or very close to it, for the problem to arise.
