### ISSUE TITLE
Concatenation of CSS classes not including spaces for (xAxis) plotlines

### ISSUE THREAD

**Issue by cascornelissen** [highcharts/highcharts#20586]
#### Expected behaviour
When adding a plotline with a custom CSS class the classnames get concatenated correctly, i.e. with a space between them.

#### Actual behaviour
When adding a plotline with a custom CSS class the classnames get concatenated without a space between them.

#### Live demo with steps to reproduce
1. Go to https://jsfiddle.net/8aLtqe9z/
2. Inspect the plotline label and notice the following

<img width="316" alt="image" src="https://github.com/highcharts/highcharts/assets/1304939/dcfb8077-8200-4517-b9e2-6f27cfcd45ec">

```diff
-class="highcharts-plot-line-labeltest"
+class="highcharts-plot-line-label test"
```

#### Product version
Highcharts 11.3.0

#### Affected browser(s)
N/A

**Comment by cascornelissen** [comment]
Including a space in the option works as a workaround:

```diff
-                className: 'test'
+                className: ' test'
```

**Comment by bm64** [comment]
Hello @cascornelissen and thanks for reporting the issue.

It looks like it used to work correctly in v11.2.0: https://jsfiddle.net/BlackLabel/87ogfmvw/

Bisected to: a3ea688b99b38726918e3d50b2949a1829a0c7c7
