### ISSUE TITLE
Export hides lines when using zones

### ISSUE THREAD

**Issue by enersis-pst** [highcharts/highcharts#20602]
#### Expected behaviour
Chart will still be the same after exporting the chart
![image](https://github.com/highcharts/highcharts/assets/76100214/5ae15f0d-c17f-468e-a472-17fd7a0d43e2)

#### Actual behaviour
inside chart the lines which have zones will be hidden after exporting it
![image](https://github.com/highcharts/highcharts/assets/76100214/739d2323-400e-4ba4-ac79-d4757c0aa9f4)

#### Live demo with steps to reproduce
https://jsfiddle.net/nxbgdhvj/3/
use the export button and export as any type (for example png)
the lines are than not shown

#### Product version
latest

#### Affected browser(s)
chrome

**Comment by enersis-pst** [comment]
looks like zone objects will be cleaned 
before
![image](https://github.com/highcharts/highcharts/assets/76100214/e592d855-c4a7-418b-8f2b-c21cfa0245fe)

after
![image](https://github.com/highcharts/highcharts/assets/76100214/0c85dfdd-854e-4ccc-9170-3d2a097694db)

**Comment by enersis-pst** [comment]
someone describe the same problem here https://www.highcharts.com/forum/viewtopic.php?f=9&t=47401

**Comment by jakubSzuminski** [comment]
Works well with 11.2.0: https://jsfiddle.net/BlackLabel/3fyjL2eh/
Seems to have been broken with 11.3.0: https://jsfiddle.net/BlackLabel/gjpom8cz/

**Comment by jakubSzuminski** [comment]
Fixed with: https://github.com/highcharts/highcharts/pull/20558
Here's a demo from `master`: https://jsfiddle.net/cuetrbfw/
