### ISSUE TITLE
Add public.api.ts

### ISSUE THREAD

**Issue by andrei4ik1997** [highcharts/highcharts#20616]
Please add public.api.ts file to the root of the library in which all functions will be exported. This is needed for the new ESBuild builder on Angular.
Builder does not accept paths with slashes(for example highcharts/highmaps)

**Comment by kirill-borisyonok** [comment]
I have the same problem

**Comment by karolkolodziej** [comment]
Hi @andrei4ik1997! 

I've created a fresh project with Angular 17 and I've followed [this documentation.](https://angular.io/guide/esbuild)

I added Highcharts to my `app.component.ts` like:
```ts
import Highcharts from 'highcharts/es-modules/masters/highcharts.src.js';
```
and my `angular.json` looks like this:
```json
        "build": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "outputPath": "dist/angular-17-issue",
            "index": "src/index.html",
            "browser": "src/main.ts",
            "polyfills": [
              "zone.js"
            ],
            "tsConfig": "tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          },
          ...
```

With this config, I'm not able to recreate it:
```bash
🎲 >ng build

Initial Chunk Files   | Names         |  Raw Size | Estimated Transfer Size
main-MWKZVL6Z.js      | main          | 429.44 kB |               130.21 kB
polyfills-RX4V3J3S.js | polyfills     |  33.01 kB |                10.68 kB
styles-5INURTSO.css   | styles        |   0 bytes |                 0 bytes

                      | Initial Total | 462.45 kB |               140.88 kB

Application bundle generation complete. [3.404 seconds]
```

Could you please walk me through where the issue is and how I can recreate it?

**Comment by kirill-borisyonok** [comment]
I am using native federation in my application. 
https://www.npmjs.com/package/@angular-architects/native-federation

we also use polyfil es-module-shims. https://www.npmjs.com/package/es-module-shims

<img width="474" alt="Снимок экрана 2024-02-13 в 11 32 06" src="https://github.com/highcharts/highcharts/assets/79683603/d4603025-df29-42e8-9001-0cf5ddbe1b87">
![Uploading Снимок экрана 2024-02-13 в 11.33.07.png…]()

**Comment by karolkolodziej** [comment]
I'm not familiar with these packages but it looks like they complain about the named export.
You can only find it in the `masters/` directory. 

Have you tried importing it like this:
```ts
import gantt from 'highcharts/es-modules/masters/highcharts-gantt.src.js;
```
With that, you don' have to import `highcharts`.

**Comment by kirill-borisyonok** [comment]
I tried all import options, but none of them work.
always throws an error "does not provide an export named 'default'".

**Comment by karolkolodziej** [comment]
It's strange because each one from `masters/` has it- [see](https://code.highcharts.com/es-modules/masters/highcharts.src.js).

@bre1470 any idea?

**Comment by kirill-borisyonok** [comment]
@andrei4ik1997 wrote a good solution.
https://github.com/highcharts/highcharts/issues/20616#issue-2130929529

**Comment by karolkolodziej** [comment]
I've tested that with the new Angular builder and it works fine.
@andrei4ik1997 Could you please tell me what your setup looks like? Do you also use the `native-federation`?

**Comment by bre1470** [comment]
@karolkolodziej It might be a conflict with the declarations based on the JSDoc doclets. Declarations do not include the default export, because this is not part of the classic masters with global namespace.

**Comment by andrei4ik1997** [comment]
@karolkolodziej Yes, I also use native-federation and angular-highcharts(https://www.npmjs.com/package/angular-highcharts). I'll create a test application later to test this problem

**Comment by kirill-borisyonok** [comment]
https://stackblitz.com/edit/stackblitz-starters-aptkaf?file=README.md
an example of the highcharts problem is located in the projects/mfe1/src/app/app.component.ts (app.component.) folder

**Comment by andrei4ik1997** [comment]
> https://stackblitz.com/edit/stackblitz-starters-aptkaf?file=README.md an example of the highcharts problem is located in the projects/mfe1/src/app/app.component.ts (app.component.) folder
> 
> you can also see the project here: https://github.com/kirill-borisyonok/highcharts-issue
> 
> @karolkolodziej check, please
@kirill-borisyonok  Thanks for reproducing the error. @karolkolodzie @bre1470 I have a similar situation.
I also managed to find a solution from @omishyn ( https://github.com/omishyn/om-angular-highcharts/tree/main ) It copies modules to the external layer using nf-copy.js . But I think this is a dirty solution. Maybe there is a better solution?

**Comment by bre1470** [comment]
I did some investigation into mentioned project setups, and I noticed Highcharts imports that are not quite right. As mentioned earlier in this discussion:

- The main product bundles have to be imported as namespace `import * as Highcharts from...`,

- While modules are imported with their default `import Data from...` or `import { default as Data } from...`.

- Also only one product bundle should be imported, while the other products should be imported as modules.

The latter can be seen in the npm package `angular-highcharts`. Maybe try the official npm package `highcharts-angular`; or does the official package have to contain the requested `public.api.ts` to make it work?

**Comment by kirill-borisyonok** [comment]
[bre1470](https://github.com/bre1470)

what do you mean by "Also only one product bundle should be imported, while the other products should be imported as modules."
Can you give an example?

**Comment by bre1470** [comment]
@kirill-borisyonok These [import statements](https://github.com/cebor/angular-highcharts/blob/master/projects/angular-highcharts/src/lib/chart.service.ts#L10-L13) might become problematic.

**Comment by andrei4ik1997** [comment]
@bre1470  I'll try this solution and come back with feedback. Thank you very much

**Comment by andrei4ik1997** [comment]
@bre1470 @karolkolodziej  Hi, after investgate and many attempts, I came to the conclusion that the Angular Esbuilder swears at import via / . 
import Highcharts from 'highcharts'; It runs fine because the root folder contains a file with the same name as the library (highcharts.ts) and we don’t have to use the highcharts/highcharts import.
But as soon as I start using import Highcharts from 'highcharts/highcharts' (although this is the same as import Highcharts from 'highcharts') the builder starts not understanding this import path and throws an error
Therefore, I ask you to add the file to the root of the library public-api.ts or index.ts which exports all modules and charts from itself
index.ts examle   `export * from './highcharts'
export * from './highcharts-3d'
export * from './highcharts-gantt'
export * from './highcharts-more'
export * from './highmaps'
export * from './highstock'
export * from './modules'`

**Comment by bre1470** [comment]
@karolkolodziej Looks like this is something for the highcharts-angular wrapper to deal with.

**Comment by karolkolodziej** [comment]
@andrei4ik1997 

Could you please describe it once again in the [highcharts-angular repo](https://github.com/highcharts/highcharts-angular)
We can continue the discussion there.

**Comment by kirill-borisyonok** [comment]
@karolkolodziej maybe something has changed on this issue?
