### ISSUE TITLE
Any way to assign id attribute to annotation shapes.

### ISSUE THREAD

**Issue by LearnGrowAndShare** [highcharts/highcharts#20617]
#### Expected behaviour
Should be able to extend **ControllablePath.attrsMap**   to support **id** addition on shape.

The rendered graphic for annotation should have "id" attribute.

```
<g class="highcharts-annotation-shapes" clip-path="url(#highcharts-q95bdm8-2-)">

    <rect x="421" y="117" width="20" id="test-circle" height="20" fill="rgba(0, 0, 0, 0.75)" stroke="rgba(0, 0, 0, 0.75)" stroke-width="1"></rect>

<circle cx="123" cy="197" r="10"  id="test-rect"  stroke="rgba(0, 0, 0, 0.75)" stroke-width="1" fill="rgba(0, 0, 0, 0.75)"></circle>
</g>
```
#### Actual behaviour

```
<g class="highcharts-annotation-shapes" clip-path="url(#highcharts-q95bdm8-2-)">

<rect x="421" y="117" width="20" height="20" fill="rgba(0, 0, 0, 0.75)" stroke="rgba(0, 0, 0, 0.75)" stroke-width="1"></rect>

<circle cx="123" cy="197" r="10" stroke="rgba(0, 0, 0, 0.75)" stroke-width="1" fill="rgba(0, 0, 0, 0.75)"></circle>
</g>
```

**Below is my analysis**
1. In option "id" is set top "test"
<img width="631" alt="Screenshot 2024-02-13 at 3 28 22 PM" src="https://github.com/highcharts/highcharts/assets/12616063/da8692be-0475-4e89-a29b-de21e07738da">

2. Here the map does not contain "id"
<img width="692" alt="Screenshot 2024-02-13 at 3 28 45 PM" src="https://github.com/highcharts/highcharts/assets/12616063/f70be93a-cd1b-4ffc-a30c-fecec9c0da38">

3. Here the map after processing does not contains.
<img width="628" alt="Screenshot 2024-02-13 at 3 35 40 PM" src="https://github.com/highcharts/highcharts/assets/12616063/93072503-736c-47ad-92a2-51641ccf91b2">

4. Manually setting the id after processing.

<img width="522" alt="Screenshot 2024-02-13 at 3 35 58 PM" src="https://github.com/highcharts/highcharts/assets/12616063/d43b22a2-e2a8-45fb-ba68-65267a128364">

5. We can see the id attribute assigned..
<img width="682" alt="Screenshot 2024-02-13 at 3 36 17 PM" src="https://github.com/highcharts/highcharts/assets/12616063/822002d7-a5ef-4941-80a5-166cf9408049">

Due to Below static map, it does not have **id**,  so we are not able to assign id, even though annotationShapeOptions id is added.

    /**
     * A map object which allows to map options attributes to element attributes
     *
     * @name Highcharts.AnnotationControllablePath.attrsMap
     * @type {Highcharts.Dictionary<string>}
     */
    public static attrsMap = {
        dashStyle: 'dashstyle',
        strokeWidth: 'stroke-width',
        stroke: 'stroke',
        fill: 'fill',
        zIndex: 'zIndex'
    };

#### Live demo with steps to reproduce
https://jsfiddle.net/2dt6L035/

#### Product version
Latest

#### Affected browser(s)
All.

**Comment by hubertkozik** [comment]
Hi @LearnGrowAndShare!
The annotation id can be set to one annotation, just like it is described in API docs: https://api.highcharts.com/highcharts/annotations.id You cannot set the id to a specific shape in the annotation.

Here's a demo with set id to one annotation: https://jsfiddle.net/BlackLabel/L428row0/ then it can be removed by e.g. `removeAnnotation` method.
