### ISSUE TITLE
Change plotBand label position on mouseover

### ISSUE THREAD

**Issue by cmalbuquerque** [highcharts/highcharts#20610]
#### Actual behaviour

Hi, I am trying to change the label position of plotBands on mouseover to the pointer position but it seems the position is not update correctly. 

```
updatedBand.events = {
      mouseover: function (event) {
        const toPixels = this.axis.toPixels(updatedBand.to),
          chartYPos = this.axis.chart.container.getBoundingClientRect().top,
          relativeYPos = event.clientY - toPixels - chartYPos;
        this.label.y = relativeYPos;
        this.label.element.style.display="block";
      },
      mouseout: function (event) {
        this.label.element.style.display="none";
      }
    };
```

I am also updating the visibility of plotBand label in order to only show the label when mouse is over the plotBand. What is happening is that label is show/hide correctly on mouseover/mouseout events. However, the update of y position is not working... label continues to shows in the default position. 

#### Expected behaviour

I am expecting the label position should be the mouseover point.

#### Product version
Highcharts 10.3.3

**Comment by bm64** [comment]
Hello @cmalbuquerque and thanks for reaching us out. 

You can achieve this by getting a reference to the label and changing it's x position, for example with [`attr`](https://api.highcharts.com/class-reference/Highcharts.SVGElement#attr) method https://jsfiddle.net/BlackLabel/wef8d3kz/

We use github strictly for feature requests and bug tracking, so without any further questions about this topic or chart configuration, please reach us on our other support channels: https://www.highcharts.com/blog/support/
