### ISSUE TITLE
Autorotation is not working in Highcharts Gantt

### ISSUE THREAD

**Issue by Ashish0401philips** [highcharts/highcharts#20629]
In documentation, autorotation is mentioned but it is not working in Gantt chart

**Comment by hubertkozik** [comment]
Hi @Ashish0401philips!
Thank you for contributing to Highcharts!

Axis labels rotation and autorotation are not working if you are using a grid in Highcharts Gantt. I wouldn't treat it as a bug, but an overlook in our documentation. In my opinion, the the autorotation and rotation descriptions there should be a mention, that rotation is not working for the enabled grid feature.
