### ISSUE TITLE
Scatter with Boost shows incorrect values in tooltip

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#20621]
#### Actual behaviour
Tooltip shows incorrect x/y values for ceratin points in boosted charts.

#### Live demo with steps to reproduce
Hover over the points in top right corner:
https://jsfiddle.net/BlackLabel/ou9y2wr1/

#### Product version
HC Core 11.3.0 + Boost

#### Internal note
Last working version 11.2.0, broken in 11.3.0
Bisected to 6136c18

**Comment by MarkusBarstad** [comment]
Strange. When I change the data a bit it seems to function 🤔 : https://jsfiddle.net/mkb93/owgx48fr/2/

**Comment by Eskils** [comment]
When the number of points exceeds `cropThreshold`, the points are filtered by whether they are inside the range of the axes and put into `processedXData` and `processedYData`. This means that there are multiple mismatching sources for the points.

In BoostSeries.ts: 
- `processPoints` fetches its points from `processedXData` (filtered)
- `addKDPoint` fetches its points from the series `xData` (unfiltered)
- `getPoint` fetches its points from `series.options.data` (unfiltered)

If the number of filtered and unfiltered points are unequal, the tooltip displays the incorrect values.

Simplified sample demonstrating the issue: https://jsfiddle.net/vr60gspo/
