### ISSUE TITLE
Drilling down to leaf node in Treemap series

### ISSUE THREAD

**Issue by nishikantparmariam** [highcharts/highcharts#20624]
# Description of the feature

Coming from [this conversation](https://www.highcharts.com/forum/viewtopic.php?p=191051#p191051) before, logging this as a feature request to improve the UI/UX of Treemaps. Features - 

### 1. Drilling down to leaf node

  Clicking on a leaf node should drill down to occupy entire space i.e. only the clicked leaf node should be visible and we should also allow user to display custom details for that leaf node.

  In Highcharts, with https://jsfiddle.net/BlackLabel/koL2bfns/ solution, clicking on A1.1 is not drilling down fully to A1.1 but to its parent - 
  ![drilldown-treemap](https://github.com/highcharts/highcharts/assets/7736252/85cea510-098a-45d1-91e2-27ad518e644b)

  Whereas in [plotly's treemap](https://plotly.com/python/treemaps/) the desired behavior can be observed - 
   
  ![drilldown-treemap-plotly](https://github.com/highcharts/highcharts/assets/7736252/a425d43e-63e7-4a7b-ac65-042a63b67512)

# Library related to the feature
Highcharts

**Comment by bm64** [comment]
Hello @nishikantparmariam and thanks for sharing the ideas!

**Comment by hubertkozik** [comment]
Completed in https://github.com/highcharts/highcharts/pull/21102.
