### ISSUE TITLE
Gantt header shows a random date/number when changing the tickInterval

### ISSUE THREAD

**Issue by jokeeras** [highcharts/highcharts#20620]
#### Expected behaviour
When changing the `tickInterval` into a smaller interval from a bigger one there should be no random label that shows up. We should see only an empty header if we don't have enough space for the ticks.

#### Actual behaviour
When changing the `tickInterval` into a smaller interval from a bigger one a random date/number appears in the header. 

#### Live demo with steps to reproduce
1. Open the page and see the header has a random date/number
2. Change `tickInterval: 1000 * 60 * 60 * 24 * 1` into `tickInterval: 1000 * 60 * 60 * 24 * 365`
3. The headers labels appear normal
4. Change it back to the smaller interval and see the random date/number that appears
[CodeSandobox](https://codesandbox.io/p/sandbox/gantt-simple-click-forked-98crnc?file=%2Fsrc%2FApp.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr6aiyjr00073b6kzjrqtj8a%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr6aiyjr00033b6kxw8yqv7g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr6aiyjr00043b6kjg2jqx0b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr6aiyjr00063b6keqo7g3h3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr6aiyjr00033b6kxw8yqv7g%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6aiyjr00023b6koyjs6s3e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr6aiyjr00033b6kxw8yqv7g%2522%252C%2522activeTabId%2522%253A%2522clr6aiyjr00023b6koyjs6s3e%2522%257D%252C%2522clr6aiyjr00063b6keqo7g3h3%2522%253A%257B%2522id%2522%253A%2522clr6aiyjr00063b6keqo7g3h3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6aiyjr00053b6ko8rad3s3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr6aiyjr00053b6ko8rad3s3%2522%257D%252C%2522clr6aiyjr00043b6kjg2jqx0b%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr6aiyjr00043b6kjg2jqx0b%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

#### Product version
Highcharts: 10.3.3
Highcharts-react-official: 3.0.0

#### Affected browser(s)
Chrome

PS: Is there a workaround to don't show that random date/number?

**Comment by hubertkozik** [comment]
Hi @jokeeras!
Thank you for contributing to Highcharts Library.

I am not sure if the described behaviour is a bug. For me, it is a bad configuration of the chart. I've reproduced your chart configuration in vanilla JS, you can find it below. It is impossible to show every tick as a day between almost 17 years of the data, that's why the chart is showing only one tick for minimal value from the data. This is not a random date, this is a format of the minimal date from your data. If you want to change it you can use `labels.format` and set it to the desired date format, according to the documentation.

**Live demo:** https://jsfiddle.net/BlackLabel/2jgreLt6/
**API Reference:** https://api.highcharts.com/gantt/xAxis.labels.format
https://api.highcharts.com/class-reference/Highcharts.Time#dateFormat

**Comment by jokeeras** [comment]
Hello @hubertkozik,
I don't have a problem with the ticks disappearing because that is when we don't have the space. But that smallest value that appears only when the other ticks disappear I would say is a bug because we can't detect when this happens from our side and show a custom label for that. Ideally it should be an empty label when the ticks are to many and disappear.

So that random value is this smallest value from our settings here:
dateTimeLabelFormats: `hour: { list: ["%H:%M", "%H"] }, -> this value is shown
 day: { list: ["%A, %e. %B", "%a, %e. %b", "%E"] },
 week: { list: ["Week %W", "W%W"] },
 month: { list: ["%B", "%b", "%o"] },
 year: { list: ["%Y"] }`

**Comment by hubertkozik** [comment]
@jokeeras you are right, these value comes from `dateTimeLabelFormats`, but there is a way to show a custom label if you need it. You can create your custom `xAxis.labels.formatter` function, which will return a custom text for specific conditions and a default label for normal conditions. Please, check the demo below to see an example.

**Live demo:** https://jsfiddle.net/BlackLabel/ftgj2pe8/
