### ISSUE TITLE
 RangeSelector's buttons don't update on click when in dropdown mode

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#20644]
#### Expected behaviour
When selecting a new period, the button should update the text.

#### Actual behaviour
The button's label never changes.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/npfqLthm/

Select some period in the RangeSelector's dropdown
Result: The text never changes.

Regression since https://github.com/highcharts/highcharts/pull/20248
#### Product version
v11.3

#### Affected browser(s)
all

**Comment by kamil-musialowski** [comment]
Simplified demo: https://jsfiddle.net/BlackLabel/cme5jrga/

Dropdown button is not clickable when stock tools are visible. Remove the module or hide them with the little arrow click.

**Comment by pawellysy** [comment]
Closed by #20601
