### ISSUE TITLE
Keyboard trap on rangeSelector dropdown

### ISSUE THREAD

**Issue by marvin19** [highcharts/highcharts#20662]
#### Expected behaviour
To be able to use tab-key in chart and interact with dropdown rangeSelector

#### Actual behaviour
After rangeSelector dropdown is focused, I am not able to tab to next element and focus indicator is stuck. Backwards tabbing seems fine. 

#### Live demo with steps to reproduce
https://jsfiddle.net/maritavindedal/8j71zLkq/

#### Product version
Highcharts Stock

**Comment by vimalmavanicasepoint** [comment]
@marvin19 
I'm reaching out to request an update on the above issue, Would you mind providing insights into its current status and the anticipated timeline for resolution?
Thank You sincerely for your assistance.

**Comment by marvin19** [comment]
@vimalmavanicasepoint 
We plan to take closer look at this issue next week.
