### ISSUE TITLE
Series data options with keys does not update correctly.

### ISSUE THREAD

**Issue by ddragula** [highcharts/highcharts#20687]
#### Expected behaviour
After using `series.update` with new data and keys, the chart updates to the same state as if this data had been provided in the options from the very beginning.

#### Actual behaviour
After using `series.update` with new data and keys, the chart does not update correctly.

#### Live demo with steps to reproduce
Waterfall chart: https://jsfiddle.net/BlackLabel/nfoajx5e/
Setting the keys up front  makes it work better, but the y-axis is still wrongly calculated: https://jsfiddle.net/highcharts/51ngvf9x/
Similarly, in a vanilla column chart, the keys are not correctly handled, and the y-axis takes the wrong column into consideration: https://jsfiddle.net/highcharts/0meLgkzv/.

If we do it in two steps, it works: https://jsfiddle.net/highcharts/0meLgkzv/1/

#### Product version
Highcharts v11.3.0
The visible change occurred in version [v8.2.2](https://www.highcharts.com/blog/changelog/#highcharts-v8.2.2), but it seems that before it yAxis was not calculated well in this case either - [demo](https://jsfiddle.net/BlackLabel/mbvaLged/).

**Comment by nekkon** [comment]
Having the same issue

**Comment by TorsteinHonsi** [comment]
Minimal demo: https://jsfiddle.net/highcharts/u7qknc3y/
