### ISSUE TITLE
Dashboards: The settings dialog for a cell stays visible after being closed

### ISSUE THREAD

**Issue by stitot** [highcharts/highcharts#20689]
Reported by potential customer

#### Expected behaviour
The “Settings” dialog is no longer visible, UI is in the same state as it was before the dialog was
opened.

#### Actual behaviour
The “Settings” dialog scrolls out of the viewport, but the dashboard now overflows horizontally,
allowing the user to scroll the “Settings” dialog back into view.

#### Steps to reproduce
Enable edit mode via the “burger menu” on the top right.
- Select any cell by clicking on it.
- Open the “Settings” dialog by clicking on the cog wheel icon.
- Close the dialog again by clicking “Cancel”.

#### Product version
Observed at https://www.highcharts.com/demo

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
![image](https://github.com/highcharts/highcharts/assets/57004120/7c17ef33-a76f-45f9-975c-f3cb9de367d9)

**Comment by karolkolodziej** [comment]
resolved by: https://github.com/highcharts/highcharts/pull/20791
