### ISSUE TITLE
Docs demo for stock tools' clipped

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#20715]
#### Expected behaviour
Able to see all the GUI elements and the full height of the demo.

#### Actual behaviour
![image](https://github.com/highcharts/highcharts/assets/8960408/5fc20ed5-7fe0-45a1-9c92-b70b3201513d)

#### Live demo with steps to reproduce
https://www.highcharts.com/docs/stock/stock-tools

#### Product version
Docs for Highcharts Stock

**Comment by pawelfus** [comment]
Note: Increase the height of the iframe to 800px
