### ISSUE TITLE
Mouse wheel zoom functionality not working

### ISSUE THREAD

**Issue by magdalena-gut** [highcharts/highcharts#20724]
#### Actual behaviour
The mouse wheel stopped working after the update to version 11.2.0.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/gorz896a/

#### Last working version
v11.1.0

#### Bisected to:
https://github.com/highcharts/highcharts/commit/9360ca8eef784c8b9cd4238b0e0c5f302be5578e

**Comment by TorsteinHonsi** [comment]
Looks like the fix did just what it was supposed to do, right? 

https://github.com/highcharts/highcharts/issues/19692

**Comment by magdalena-gut** [comment]
Indeed, my oversight sorry!

**Comment by magdalena-gut** [comment]
Marking this issue as not a bug.
