### ISSUE TITLE
Can not remove chart with areasplinerange series while hovering

### ISSUE THREAD

**Issue by KaisZaoualiWincher** [highcharts/highcharts#20722]
#### Expected behaviour

Removing chart with areasplinerange series while hovering should be performed with no issues

#### Actual behaviour

Removing chart with areasplinerange series while hovering is throwing error: `Cannot read properties of undefined (reading 'chart')`

![image](https://github.com/highcharts/highcharts/assets/129404933/96403ffd-352e-400e-8cf9-25dc0d236ac9)

#### Live demo with steps to reproduce

https://codesandbox.io/p/sandbox/highcharts-99yys8

While hovering on the chart series, you need to press any key (which should hide the chart). Make sure you are selecting the preview (i.e. you can inspect the rendered chart to make sure the pressed key will have an impact on the chart)

#### Product version

"highcharts": "11.3.0",
"highcharts-react-official": "3.2.1"

#### Affected browser(s)

Google chrome

**Comment by hubertkozik** [comment]
Hi @KaisZaoualiWincher!
I've just tested the chart config you provided and I cannot see any issues. I've changed the state to hide and show the chart on key press. I'm attaching a GIF below.
**Live demo:** https://codesandbox.io/p/sandbox/highcharts-forked-x6v7s3
![not_a_bug](https://github.com/highcharts/highcharts/assets/62724907/1e862a83-8bf7-48d4-a19b-92df3b05308a)

**Comment by hubertkozik** [comment]
Thanks @PinkChampagne17!
I've reproduced and recreated the demo in vanilla JS: https://jsfiddle.net/BlackLabel/ghe9rnbx/

This issue is already reported here: https://github.com/highcharts/highcharts/issues/20572 You can track the progress there. I am closing this one as a duplicate.
