### ISSUE TITLE
Performance degradation with 11.3.0 version

### ISSUE THREAD

**Issue by bferreira** [highcharts/highcharts#20720]
#### Expected behaviour
We expect the performance of the first render of the chart and zoom not to change from 11.2.0

#### Actual behaviour
It takes longer to render with 11.3.0 than in the previous version 11.2.0

#### Live demo with steps to reproduce
https://jsfiddle.net/7w6cgz5n
if you switch between the 2 versions of highcharts, the performance difference is clear.

#### Product version
Highcharts 11.3.0

#### Affected browser(s)
Chrome and Safari at least

**Comment by hubertkozik** [comment]
Hi @bferreira! Indeed, there is a regression in the performance of those two charts between v11.2.0 and v11.3.0.

**Demo v11.2.0:**  https://jsfiddle.net/BlackLabel/v16ef70d/ **time around 2000 ms**
**Demo v11.3.0:** https://jsfiddle.net/BlackLabel/ufxa73w1/ **time around 4300 ms**

Internal note:
Bisected to cc3dc571848c243a1c78a2224b4a299cc421c5aa.

**Comment by bferreira** [comment]
Awesome work 🎉
