### ISSUE TITLE
Illegal fallback instead of custom error in offline-exporting (CSP behaviour)

### ISSUE THREAD

**Issue by PadWorks** [highcharts/highcharts#20741]
#### Expected behaviour
If I define FallbackToExportServer = false and give the corresponding custom error message, I actually expect that when CSP is active, the call to https://code.highcharts.com/11.3.0/lib/jspdf.js and corresponding *svg2pdf.js will be intercepted and fail with the corresponding error message .

Based on the two issues #12553  and #7697 , the libURL attribute should be defined in this case (according to the documentation this would be undefined, in fact it is the corresponding link). I would have expected that deactivating the fallback server would intercept all external calls in this context.

What should also be mentioned is that the two libraries are already loaded dynamically as a bundle and would be available on the site. However, since they are bundled, it is not possible to put the libURL directly on the script (and it makes no sense to reload the libraries each time).

Either I don't understand the definition of the attributes, or the API documentation is not complete in this regard.

#### Actual behaviour
A crosssite call is made to the external *jspdf.js and *svg2pdf.js library even though FallbackToExportServer = false.

#### Live demo with steps to reproduce
https://jsfiddle.net/PadWorks/hceuoqjt/4/

#### Product version
11.3.0

#### Affected browser(s)
Google Chrome

**Comment by karolkolodziej** [comment]
Hi @PadWorks! 

I think I know what your issue is but there is probably one misconception. 
You are saying that:
> should also be mentioned is that the two libraries are already loaded dynamically as a bundle and would be available on the site. 

But as you can read in[ our documentation:
](https://www.highcharts.com/docs/export-module/client-side-export)
```
By default, the module will load these file from our server on demand, but the URL can be changed using the
[exporting.libURL](https://api.highcharts.com/highcharts/exporting.libURL) option. 
If the scripts have already been loaded by the page, Highcharts will not load them again. 
Note that even when loading these files, no chart data is sent to our server.
```

Not every time there is a need to load these two libraries thus we only load them on demand but no chart data is being sent anywhere. 
If you want to avoid the callbacks when exporting you can load manually load this module as shown in[ the demo.](https://jsfiddle.net/BlackLabel/pgzy0q9k/)

**Comment by PadWorks** [comment]
Hi @karolkolodziej 

Thanks for your feedback, the problem has been resolved. The order in the bundle was incorrect, in this case the jspdf and svg2pdf must be loaded before the highcharts scripts.

The whole thing was a little confusing because I couldn't find the init part in the highcharts-code and on the lines in the code of the offline-exporting module which trows the exception, the script is always loaded directly and no attempt is made to find the local library again.
