### ISSUE TITLE
Optimized output of charts for printing

### ISSUE THREAD

**Issue by apeiniger** [highcharts/highcharts#2074]
We often have the effect that we are printing Highcharts objects for example inside a PDF document. In this case there is of course no access to mouse hover effects and this make it sometimes hard to read.

One solution would now be to turn on data values, but this usually leads to many overlapping text labels.

Would there be a chance of an automated algorithm that for example only puts data labels at certain "important" points like peaks? This would make it much easier to read it on paper.

**Comment by oysteinmoseng** [comment]
This is still relevant. Perhaps it could be a module/plugin?

**Comment by pawelfus** [comment]
Just in case: [`series.line.data.labelrank`](https://api.highcharts.com/highcharts/series.line.data.labelrank) - if we can simply define rank for each label (e.g. peaks) then it's done.
