### ISSUE TITLE
Range selector dropdown label does not update in responsive view

### ISSUE THREAD

**Issue by xPaw** [highcharts/highcharts#20740]
#### Expected behaviour
When selecting a different option the dropdown, the button label should update:
![image](https://github.com/highcharts/highcharts/assets/613331/f4611c27-5d41-4bb6-9136-882230985125)

#### Actual behaviour
Tapping a different option in the select dropdown does not update the label.

Removing fixed width from the example and resizing the window shows that the correct labels exist, because it updates when the viewport resizes from buttons to the dropdown variant.

`highcharts-button-pressed` class correctly switches, but it looks like the `visibility` attribute does not.

#### Live demo with steps to reproduce
https://jsfiddle.net/kqrpgeya/

#### Product version
v11.3.0 

#### Affected browser(s)
Chrome, Firefox

**Comment by hubertkozik** [comment]
Hi @xPaw!
Sadly, this is a regression. In Highcharts v11.2.0 everything was working fine.

_Internal note:_
Bisected to 59f5b17ac90c13e3194fa72c9705f0c4769e930c FYI @pawellysy

**Comment by pawellysy** [comment]
Already reported here: https://github.com/highcharts/highcharts/issues/20644

Closing as a duplicate
