### ISSUE TITLE
Better Svelte integration 

### ISSUE THREAD

**Issue by 3goats** [highcharts/highcharts#20755]
Hi, we're are starting to make more use of SvelteKit as a general solution for building dashboard and reports. From what I can see there doesn't seem to be a well documented best practise for adding Highcharts to Svelte. Are there any plans to provide any out of the box Highcharts components or is there a documented best practice we can use ?

**Comment by hubertkozik** [comment]
Hi @3goats!

There is already a Svelte integration Feature Request here: https://github.com/highcharts/highcharts/issues/13481 so I am closing this one as a duplicate, but as you can read in the mentioned ticket, we're considering a Svelte wrapper and would like to understand your needs better. Could you reach out to us through [support@highcharts.com](mailto:support@highcharts.com) so we can schedule a meeting to discuss this?
