### ISSUE TITLE
this.total in tooltip formatter doesn't sum right in bars chart which contains negative values

### ISSUE THREAD

**Issue by OlivierDev** [highcharts/highcharts#2076]
I am trying to draw a bar charts which contains 2 stacked series.
I have got an issue when I customize the tooltip formatter : this.total value doesn't sum right when there is negative values.

jsfiddle :
http://jsfiddle.net/CDQYF/

I am using Highcharts 3.0.2 with Chrome 28.0.1500.71.

**Comment by oysteinmoseng** [comment]
Should we have an option for this?
