### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by shashikiran797** [highcharts/highcharts#20771]
I have a bar chart.

And sometimes, when rendering the chart, I see an error message.
Error does not happen everytime:
`Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')`

Upon debugging, I found that, it is called in `bindAxes` method.
Error is thrown only when `series.axisTypes` has `colorAxis` in it and the `chart` object does not have `colorAxis` field

Error is thrown here:
`series.axisTypes = ['xAxis', 'yAxis', 'colorAxis']`
`(chart as any)[coll].forEach`
where `coll = 'colorAxis'` 

```
    /**
     * Set the xAxis and yAxis properties of cartesian series, and register
     * the series in the `axis.series` array.
     *
     * @private
     * @function Highcharts.Series#bindAxes
     */
    public bindAxes(): void {
        const series = this,
            seriesOptions = series.options,
            chart = series.chart;
        let axisOptions;

        fireEvent(this, 'bindAxes', null as any, function (): void {

            // repeat for xAxis and yAxis
            (series.axisTypes || []).forEach(function (coll: string): void {
                // loop through the chart's axis objects
                (chart as any)[coll].forEach(function (axis: Axis): void {
                    axisOptions = axis.options;
```

Can someone please help me 
* how to solve this issue?
* Explain 
How the `axisTypes` is derived?
How the `chart.colorAxis` is populated?
When `bindAxes` is called?

#### Expected behaviour
Should not throw error

#### Actual behaviour
Throwing error:
`Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')`

#### Product version

10.3.1

**Comment by hubertkozik** [comment]
Hi @shashikiran797!
I was trying to reproduce your issue, but everything is working correctly - please check the demo below.
**Demo:** https://jsfiddle.net/BlackLabel/vkg542yq/

Can you reproduce the issue in the online editor?

**Comment by hubertkozik** [comment]
`axisTypes` is an internal property for series, which is used to set, which axes types can be used for this kind of series. There is no documentation for this option, it is used internally.

`colorAxis` is populated in many places, but it is added to `axisTypes` here: https://github.com/highcharts/highcharts/blob/88128dab4b2d95ada26ab8b4c2b5823901519a7e/ts/Core/Axis/Color/ColorAxisComposition.ts#L308 As I said before, it is also an internal method, not official one to use by the users.

`bindAxes` is called internally during the series initialization. This method is also only for internal use, not official.

**Comment by shashikiran797** [comment]
What inputs do I need to pass to make sure `axisTypes` does not contain `colorAxis`?
In my case, the issue happens only when the axisTypes for the series has colorAxis in it.

**Comment by shashikiran797** [comment]
@hubertkozik 
I have raised a pull request with the fix for the problem I am facing.

**Comment by hubertkozik** [comment]
@shashikiran797 We are not able to understand the issue fully without reproducing the problem in the online editor, e.g. JSFiddle. As I asked you before, can you reproduce the issue in the online editor? You can use this demo for a start: https://jsfiddle.net/BlackLabel/vkg542yq/

**Comment by TorsteinHonsi** [comment]
@hubertkozik I think we can apply @shashikiran797 's changes safely. I added some type safety and will post a PR with the improved typing including the suggested fix.

**Comment by shashikiran797** [comment]
@TorsteinHonsi 
@hubertkozik 

When can I expect this change to be available for use from npm?
Will this change be applied on any patch version?

**Comment by hubertkozik** [comment]
The change will be included in the next release of Highcharts. We do not have any specific ETA for the next release at this moment, as Highcharts v11.4.0 was released yesterday. Until that, you can copy-paste the IIFE function from this demo: https://jsfiddle.net/BlackLabel/wsfo7e1u/ as a plugin to your project.
