### ISSUE TITLE
Selection event x-axis min and max values are incorrect in column chart

### ISSUE THREAD

**Issue by ollivihervuori** [highcharts/highcharts#20784]
In the column chart, the selection event x-axis min and max values sometimes don't correspond with the selection.

The issue can be replicated with this demo: https://jsfiddle.net/otxkfrpu/

Replication steps: Make a rectangle selection (i.e., mouse button down, move mouse, and mouse button up) starting in x-axis halfway between 3 and 4 and ending to halfway between 4 and 5. In this case, the x-min is expected to be around 3.5 and x-max around 4.5.

The issue started in 11.4.0, and with the previous version (11.3.0) the behavior is correct, as shown by this demo: https://jsfiddle.net/9uL2at1z/

Issue replicated with Chrome and Firefox.

Chart settings where the issue appears:

```
Highcharts.chart('container', {
  "chart": {
    "zooming": {
      "type": "xy"
    },
    "events": {
      selection: evt => {
        document.getElementById("xmin").textContent = "X min: " + evt.xAxis[0].min;
        document.getElementById("xmax").textContent = "X max: " + evt.xAxis[0].max;
        return false;
      }
    }
  },
  "series": [
    {
      "type": "column",
      "data": [
        {
          "x": 3,
          "y": 1
        },
        {
          "x": 4,
          "y": 2
        },
        {
          "x": 5,
          "y": 3
        }
      ]
    }
  ]
});
```

**Comment by hubertkozik** [comment]
Hi @ollivihervuori!

Thank you for reporting the issue. This is regression, no specific workaround for that moment.

_Internal note:_
Bisected to 16bbb070cc137b85f7e32dde54672d30efa98176 FYI @TorsteinHonsi.
