### ISSUE TITLE
Still an error when trying to show a tooltip on a plotline

### ISSUE THREAD

**Issue by charmbv** [highcharts/highcharts#20799]
#### Expected behaviour

See also issue #20516 but that doesn't solve the problem.

I'm using the following code to handle the `mouseover` and `mouseout` events on a plotline to display a tooltip:

```
chart.yAxis[0].addPlotLine({
  ...,
  events: {
    mouseover: function (event: any) {
      console.log(this);
      return MyComponent.prototype.showTargetPlotLineTooltip(this, event);
    },
    mouseout: function (event: any) {
      console.log(this);
      return MyComponent.prototype.hideTargetPlotLineTooltip(this, event);
    },
  },
});
```

Running the code I would expect to see a tooltip appear when I hover over a plotline.

#### Actual behaviour

The tooltip is not shown but I see the following error in the console:

```
applyOptions highcharts.js:8
S highcharts.js:8
showTargetPlotLineTooltip entitlement-payout-graph.component.ts:687
mouseover entitlement-payout-graph.component.ts:620
render highcharts.js:8
```

As said in the previous issue it works with v11.1.0.

#### Product version

Highcharts v11.4.0, Highcharts-Angular v4.0.0

#### Affected browser(s)

Firefox, Chrome, Edge.

**Comment by hubertkozik** [comment]
Hi @charmbv!

The mentioned issue is not fixed. The context of the plotline mouseover/mouseout functions is not passed correctly.

_Internal note:_
There are differences between minified and non-minified code. Please, check the demos below. FYI @MarkusBarstad `console.log` is giving different objects `(this)`.

**Minified:** https://jsfiddle.net/BlackLabel/5cLuqgr4/
**Non-minified (src version):** https://jsfiddle.net/BlackLabel/o97suLkg/

I think it is related to the usage of the arrow function, which is transpiled to a normal function, and the context is changed: https://github.com/highcharts/highcharts/blob/9656b080fca13c678e8535efcd22db0cf01a5e20/ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts#L242

**Comment by hubertkozik** [comment]
@charmbv, I think I got a cache issue last time, when I was debugging your case because now everything is working correctly.

Can you create a demo with the reproduced issue in some online editor?

**Comment by charmbv** [comment]
I will try to create a sample application. Will post a link here when I have something.

**Comment by charmbv** [comment]
As usual, when trying to create a sample project it "suddenly" works. However, I still get an error that I can't figure out how to solve. I'm using the following code (adapted from https://jsfiddle.net/BlackLabel/3k216ywa/) to show the tooltip at the place of the event:

```
private showPlotLineTooltip(plotLine: any, event: any) {
  const series: Highcharts.Series = plotLine.axis.series[0];
  const chart: Highcharts.Chart = series.chart;
  const tooltip: Highcharts.Tooltip = chart.tooltip;
  const point: Highcharts.Point = new Highcharts.Point().init(series, {
    value: plotLine.options.value,
  });
  const normalizedEvent: any = chart.pointer.normalize(event);

  (point as any).tooltipPos = [
    normalizedEvent.chartX - chart.plotLeft,
    normalizedEvent.chartY - chart.plotTop,
  ];
  (point as any).showPlotLineTooltip = plotLine.options.showPlotLineTooltip;

  tooltip.refresh(point as any);
  }
```

This works when using Highcharts 11.2.0 but fails with 11.4.0 on the `new Highcharts.Point().init(...)` line. Any idea on how to fix this?

**Comment by hubertkozik** [comment]
@charmbv, you are trying to create a dummy point by using `init` method, which is not supported now in Highcharts, you can check the Pull Request here: https://github.com/highcharts/highcharts/pull/20286

Now, you should create the dummy point as a normal constructor. This is not a bug, it is intended. Feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
