### ISSUE TITLE
Plotlines with HTML labels render incorrectly (11.4.0 regression)

### ISSUE THREAD

**Issue by cascornelissen** [highcharts/highcharts#20792]
#### Expected behaviour
Plotlines with HTML labels have their labels rendered next to the plotline

#### Actual behaviour
The label is rendered all the way to the right, see screenshot:
<img width="849" alt="image" src="https://github.com/highcharts/highcharts/assets/1304939/cc721753-b059-4c51-a440-198abdd6a176">

#### Live demo with steps to reproduce
https://jsfiddle.net/txsLuny9/1/

#### Product version
Highcharts 11.4.0, we were not seeing this in 11.2.0, not sure about 11.3.0.

#### Affected browser(s)
Noticed in Firefox, reproducible in Chrome

**Comment by karolkolodziej** [comment]
Hi @cascornelissen! 

Thank you for reporting the issue! 

Internal note: 
Bisected to https://github.com/highcharts/highcharts/commit/9d051e7dcf7c973cacaf44976ed014483ea3110e
Also, https://github.com/highcharts/highcharts/commit/94395652e90a79b372f6d5a89039351d5cf3af63 looks suspicious.
FYI @TorsteinHonsi @hubertkozik
