### ISSUE TITLE
Non nested component settings in Dashboards

### ISSUE THREAD

**Issue by liorheber** [highcharts/highcharts#20793]
# Description of the feature
Currently when configuring the sidebar with component settings, even if I have only one input in a group, it's still nested.
It would be great is we could configure inputs to be outside a group instead flat on the sidebar instead of in a group.

# Library related to the feature
Highcharts Dashboards

**Comment by karolkolodziej** [comment]
Hi @liorheber! 

Thank you for sharing the idea!
