### ISSUE TITLE
Solid gauge `yAxis` options not applied with `setOptions`

### ISSUE THREAD

**Issue by palhal** [highcharts/highcharts#20804]
When type is set to `solidgauge`, specific `yAxis` options are not applied with `Highcharts.setOptions`. They are however applied if using the `chart` function.

This was working in 11.2.0, but broke in 11.3.0.

At least these options are affected (there might be others as well):

- yAxis.tickLength
- yAxis.minorTickLength
- yAxis.labels.distance

#### Expected behaviour
The gauge should be rendered in the same way regardless of whether you use the `setOptions` or `chart` functions.

#### Actual behaviour
Gauge is not rendered in the same way.

#### Live demo with steps to reproduce
1. Open this jsfiddle: https://jsfiddle.net/pkhalle/cy7mp2j5/
3. Observe the gauge's appearance
4. Change the imported Highcharts version to 11.3.0
5. Re-run the fiddle and observe the appearance has changed

#### Product version
Highcharts 11.3.0+

**Comment by hubertkozik** [comment]
Hi @palhal!

Indeed, this is a regression. There should be a possibility to set y-axis options through `setOptions` method. As a workaround you can set them in chart configuration object, like here: https://jsfiddle.net/BlackLabel/ta5ugm03/

_Internal note:_
Bisected to: 999f29cce6386948e471e0756754cd0e48e01f88.
