### ISSUE TITLE
Bad scale re-sizing and hidden labels in log scale with flat data 

### ISSUE THREAD

**Issue by vitchyr** [highcharts/highcharts#2080]
Using highstock: http://jsfiddle.net/bJhgm/9/

Bad scale re-sizing:
1.  Click Series One to close it
The remaining series is crammed to the bottom of the screen, and there is only one y-axis label.

Hidden Labels:
The y-axis labels sometimes disappear. This happens at random when turning the series on/off. There seems to be no specific set of commands that cause this to happen.

**Comment by oysteinmoseng** [comment]
Seems to work as expected with current version.
