### ISSUE TITLE
Dependency Wheel persisting highlighted state

### ISSUE THREAD

**Issue by brunouber** [highcharts/highcharts#20810]
# Description of the feature

<img width="544" alt="image" src="https://github.com/highcharts/highcharts/assets/55399398/42e68937-784b-47a3-a464-bbe9d81187bc">

In the Dependency Wheel ([example](https://www.highcharts.com/docs/chart-and-series-types/dependency-wheel)) chart when user hovers an arc, all the line in/out that arc are highlighted.

Is there a way to keep this highlighted state even after the user leaves the chart area?
Eg. User clicks on the arc, all the dependencies of that are get highlighted and remain in this state as long the user clicks on another arc (or outside the chart area, or press Escape key).

**Comment by karolkolodziej** [comment]
Hi @brunouber!

Yes you can have something like this, we have the [allowPointSelect](https://api.highcharts.com/highcharts/series.dependencywheel.allowPointSelect) property and the [point events](https://api.highcharts.com/highcharts/series.dependencywheel.point.events) which you can use to create this kind of behaviour. 
Please give it a go and[ contact our support team](https://www.highcharts.com/blog/support/) if you struggle with it.
