### ISSUE TITLE
`pointFormat` wrong timezone displayed when used with `#if` or `#unless`

### ISSUE THREAD

**Issue by jedrzejruta** [highcharts/highcharts#20816]
#### Expected behaviour

The tooltip date should be displayed according to given timezone.

#### Actual behaviour
The tooltip date is displayed according to system timezone, disregarding given timezone.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/Lzayofu7/](https://jsfiddle.net/BlackLabel/Lzayofu7/)
Remove the `#if` statement, and the date will be displayed correctly.

#### Product version
Regression introduced in Highcharts v11.1.0

**Comment by hubertkozik** [comment]
This issue is reproducible also for Highcharts with line series: https://jsfiddle.net/BlackLabel/4z5qb09L/ not only Gantt.
