### ISSUE TITLE
Issues with Dashboards climate demo

### ISSUE THREAD

**Issue by jomar-honsi** [highcharts/highcharts#20823]
#### Expected behaviour
1. Data grid cells to be fully visible also for mobile devices.
2. The "city chart" should provide the correct units on the Y axis. It doesn't make sense to denote "Days with rain" as Celsius.
3. Consistent localization.
4. All charts to clearly indicate which year is shown.
5. The KPI to show the first data in the grid
6. The chart and map tooltips should disappear when the cursor is outside the parent component.

#### Actual behaviour

1. Data grid content messy as the browser window shrinks
2. Temperature and number of rainy days on the same axis (unit inconsistency).
3. The demo now uses a mix of UTC dates and Norwegian (e.g. "1. Apr.")
4. Only the grid display complete time info
5. KPI and map currently display the last data in the grid
6. Tooltips stick even with cursor outside Dash component.

#### Proposed fixes

1. Use a smaller front for the date column (for mobile devices)
2. Checkbox to determine whether to display temperatures or other data (or show temperatures only).
3. Use the same localization in data grid and chart.
4. Use chart title (or subTitle) to display the data range.
5. Use first data in grid for KPI and map (see weather demo).
6. Hide tooltips when not directly hovered over.

#### Suggested improvements

1. Is days with ice really that interesting? (most places on the map don't have any icy days).
2. In the chart: show minimum temperature instead of rainy days
3. If rainy days to be shown at all: it is better to use a column chart.
4. Add a title to all charts (important for mobile views)

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/dashboards/climate

#### Product version
Highcharts 11.4,
Dashboards 1.3.1

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
5. I don't see any benefits over displaying the first element over the last- let's level it as it is for now.
6. When the cursor is outside of the chart, the tooltip is hidden.
