### ISSUE TITLE
Phantomjs server parameters cannot be set using the java api

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#2082]
The parameters that control pool-size and timeouts etc are located in app-convert.properties. If you want a specific pool-size you modify the file and rebuild the jar.

**Enhancement**: Add a way to override these settings when creating the SVGConverter to avoid having to rebuild jar after changing config property. This would be useful when deploying the highcharts-convert.jar on different platforms that should use different settings.

Something like this:

```
int poolSize = 4;
SVGConverter c = new SVGConverter(poolSize, other settings...);
```

**Comment by oysteinmoseng** [comment]
No longer relevant with current Node based export server.
