### ISSUE TITLE
Pie Chart Titles

### ISSUE THREAD

**Issue by marquesmps** [highcharts/highcharts#2083]
This is an enhancement request. It would be great to have Pie Chart Titles. If I want to generate multiple pie charts dynamically there is no easy way to put a title in each of them. 
There is a related request here: http://highcharts.uservoice.com/forums/55896-general/suggestions/3073133-pie-title but the solution doesn't prevent collisions between the pie slice labels and the pie title. Also the title positioning is not perfect.

**Comment by oysteinmoseng** [comment]
This is still relevant.
