### ISSUE TITLE
Dashboards: zones[].color not working

### ISSUE THREAD

**Issue by stitot** [highcharts/highcharts#20833]
#### Expected behaviour
When specifying color for a zone in a column chart I expect those columns to be correct color, as in Core.

#### Actual behaviour
Specified color is not rendered as expected when using same config in Dashboards

#### Live demo with steps to reproduce
Working example in Core: https://jsfiddle.net/zopjft5e/
Non-working example in Dashboards: https://jsfiddle.net/0hL1cps9/

#### Product version
Latest

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
@stitot It also works with dashboards, but you must remember that all charts in Dashboards use the `styledMode` by default.
JS: 
```js
zones: [{
    value: 0, // Values less than 0
    color: '#ff0000',
    className: 'zone-below-zero'
}],
```
CSS:
```css
.highcharts-graph.zone-below-zero {
  stroke: #ff0000;
}
```
If you declare the class for the zone it works- [demo](https://jsfiddle.net/BlackLabel/kzqdpsga/).

**Comment by stitot** [comment]
Hm, I would expect it to work when I set styledMode to false (see https://jsfiddle.net/0hL1cps9/)

**Comment by karolkolodziej** [comment]
And it does, you only need to remove the `highcharts.css` import. Otherwise, it is going to overwrite the styling- [demo](https://jsfiddle.net/BlackLabel/qan4x7os/).

**Comment by stitot** [comment]
Oh, I see. Hm, not overly satisfied with how that works and/or is documented. Let's think about it.

**Comment by stitot** [comment]
As a developer I would expect that a rather explicit config (`styledMode: false`) would take precedence over any included CSS that affects style. Could in theory be handled by removing the CSS reference from the DOM, or by not adding classnames to output (if that what's happen), but I guess this have further implications that eludes me.
