### ISSUE TITLE
Point level events not working for charts in 11.4.0

### ISSUE THREAD

**Issue by sidrak19** [highcharts/highcharts#20851]
#### Expected behaviour

Till `v11.3.0`, we could define events at the point level in a series, and those events would be triggered.

```
series: [{
  ...
  data: [
    ...
    {
      x: 1,
      y: 5,
      events: {
      	mouseOver: () => {console.log('hovered over point')},
      },
    },
    ... 
  ],
```
Hover over the point at x=1 in https://jsfiddle.net/Lu3rpt1k/, it logs a message in the console.

#### Actual behaviour

Since `v11.4.0`, the point level events are no longer triggered.

Hover over the point at x=1 in https://jsfiddle.net/yLqhgmdn/, it no longer logs a message in the console.

#### Live demo with steps to reproduce
https://jsfiddle.net/yLqhgmdn/

#### Product version
Highcharts version: `11.4.0`

#### Affected browser(s)
--

**Comment by sidrak19** [comment]
Might be related to https://github.com/highcharts/highcharts/issues/20435

**Comment by bm64** [comment]
Hello @sidrak19 and thanks for reporting the issue.

As a workaround, you can use for example `addEvent` method: https://jsfiddle.net/BlackLabel/ktcae6zq/

_Internal note:_
Bisected to: b848e77 FYI @hubertkozik
