### ISSUE TITLE
Touch panning with one finger not possible in 11.4.0 when combining line and scatter chart

### ISSUE THREAD

**Issue by gruuschesdevelopmenthq** [highcharts/highcharts#20858]
#### Expected behaviour
Panning on mobile devices with one finger is possible when followTouchMove is set to false and chart series 1 is line and series 2 is scatter.

#### Actual behaviour
Two fingers needed for panning.

#### Live demo with steps to reproduce
https://jsfiddle.net/wy8orsnv/14/

#### Product version
    "highcharts": "^11.4.0",
    "highcharts-react-official": "^3.2.1",

#### Affected browser(s)
Firefox 123.1.0 (mobile)
Safari (mobile)

-------
I upgraded from 11.3.0 to 11.4.0 and now the one finger panning isn't working anymore.

edit: my initial description was wrong, I figured out later. It seems like the problem is when using scatter charts in combination with line charts. I updated the live demo.
to use line on it's on is working, also scatter on it's own is working. but not together.
the same demo is no issue in 11.3.0.

Open the demo, open dev tools, click on touch simulation and reload the demo again. Pinch zoom into the chart and try to move left and right with the touch simulation - it's not working.

**Comment by hubertkozik** [comment]
Hi @gruuschesdevelopmenthq!

I've just added `zooming.type: 'x'` to your demo to enable zoom and check the panning of the zoomed-in chart and everything is working correctly on Safari (iPhone mobile). `zooming.type` is by default set to `undefined`, so to enable zoom fully you should also set the type of zoom. Can you double-check if everything is working correctly on your side?

**Live demo:** https://jsfiddle.net/BlackLabel/y59sfpnd

**Comment by gruuschesdevelopmenthq** [comment]
Hi @hubertkozik ,
I noticed something while creating the as-is demo. You have added zooming.type: 'x', but this activates zooming with the mouse pointer, i.e. zooming with clicking and dragging. this is a behavior that i have intentionally deactivated, as i only want to activate zooming with the mouse wheel (or pinch zoom on mobile), and clicking and dragging is intended for moving through the chart. Setting a panning key is not an option in terms of UX.
i'm still working on my demo, but i'd be interested to know if you can enable panning with a finger on mobile devices without setting zooming.type: 'x' in your demo.

**Comment by hubertkozik** [comment]
Thanks for more details @gruuschesdevelopmenthq.
If you want to disable zooming with mouse pointer, but keep zooming with mouse wheel and pinch zoom on mobile you can set `zooming.pinchType` to desired value (according to documentation).

**Live demo:** https://jsfiddle.net/BlackLabel/mx8h61ow/
**API Reference:** https://api.highcharts.com/highcharts/chart.zooming.pinchType

I still don't see any bug here. With correct configuration panning with one finger is possible and working correctly.

**Comment by gruuschesdevelopmenthq** [comment]
Hi @hubertkozik ,
in my setup it's not working like in your demo and I'm unable to recreate the demo in the same way as my webapp is unfortunately.
I will still try to get the demo working and recreate the issue but meanwhile I found this issue which sounds pretty similar to my problem: https://github.com/highcharts/highcharts/issues/20877

So it looks like there is currently no workaround available and I will stay on 11.3.0 in that case.

**Comment by pawelfus** [comment]
Hello @gruuschesdevelopmenthq - the new release is out, could you try it out and let us know the results? Are you able to recreate the original issue in this ticket?

**Comment by gruuschesdevelopmenthq** [comment]
Hi @hubertkozik ,
thank you, yes it looks like the issue is resolved, the one finger panning is working great on my devices!
I couldn't recreate my project in jsfiddle but the examples in the issue 20877 showcased the behavior I was experiencing.
However, it works great now and also the whole experience on mobile devices is a lot improved, it feels great using it on mobile devices now!
