### ISSUE TITLE
xAxis crosshair labels rendered in wrong position

### ISSUE THREAD

**Issue by gohyinhao** [highcharts/highcharts#20856]
#### Expected behaviour
crosshair label to be rendered in correct position on the x-axis

#### Actual behaviour
when hovering on the right half of the chart, position of the crosshair label is wrong

<img width="674" alt="image" src="https://github.com/highcharts/highcharts/assets/46367449/1c6dbddd-5518-4b34-bd24-cc0f8cbeaadb">

#### Live demo with steps to reproduce
add the following to chart config
```
xAxis: {
  type: 'datetime',
  crosshair: {
    label: {
      enabled: true,
    },
  },
}
```
`area` chart: https://jsfiddle.net/d54e2xzc/3/
`columnrange` chart: https://jsfiddle.net/ud5vkqhj/10/

#### Product version
highstock v11.4.0. did not see this issue in v11.1.0

#### Affected browser(s)
- chrome v121.0.6167.139
- firefox v123.0.1

did not check other browsers

**Comment by kennygoff** [comment]
Same issue but a slight variation: With a border set on the label the border also is broken and cuts across the entire chart.

<img width="683" alt="Broken border" src="https://github.com/highcharts/highcharts/assets/1051880/327d4097-3bf6-4e2a-a8a4-9f6f6e609b84">

Forked fiddle: https://jsfiddle.net/kennygoff/f5mnjuzt/2/

```
xAxis: {
  type: 'datetime',
  crosshair: {
    label: {
      enabled: true,
      borderColor: '#000000',
      borderWidth: 1,
    },
  },
}
```

**Comment by TorsteinHonsi** [comment]
Simplified demo: https://jsfiddle.net/highcharts/sb68cfaz/
