### ISSUE TITLE
Gantt chart fix timeline headers getting deresorted while scrolling down

### ISSUE THREAD

**Issue by subramanyarak** [highcharts/highcharts#20861]
#### Expected behaviour
On Enabling Scroller the Height should not Fluctuate

#### Actual behaviour
on enabling scroller in yAxis & on scrolling height is fluctuating

#### Live demo with steps to reproduce
[](https://jsfiddle.net/9jz4tb7v/42/)
first  collapse all first parent and than on scroll chart height is fluctuating and and not behaving as it should be after collapsoing all first level parent than scroll and than expand one parent than on scroll complete chart got distorted
#### Product version

10.2
#### Affected browser(s)
Chrome

**Comment by bm64** [comment]
Hello @subramanyarak 

Could you try to recreate the issue in this demo? https://jsfiddle.net/BlackLabel/zgwp2scd/
Thanks in advance

**Comment by subramanyarak** [comment]
Hello @bm64 


Please Find the link of demo recreated 
https://jsfiddle.net/zan12fqw/

Steps to reproduce: 

1. Please collapse all the parent columns
2. Try to scroll down the gantt's Yaxis it will be Desorted

Please help us to fix the same
