### ISSUE TITLE
RangeSelector 2Y button disabled

### ISSUE THREAD

**Issue by manish813** [highcharts/highcharts#20883]
#### Expected behaviour
I have data from March 13 2022 to march 12 2024 . The range  2Y should be enabled as it has 2y worth of data

#### Actual behaviour
2Y button is disabled

#### Live demo with steps to reproduce
https://jsfiddle.net/manishnaik813/35L7cpmq/1/

#### Product version
^8.2.0

#### Affected browser(s)
All browsers

**Comment by bm64** [comment]
Hi @manish813 

In the provided data set, there are 729 days in range 1647151200000 - 1710219600000, which is less than 2 years. 
2 years equal 730 or 731 days, considering a leap year.
Add just one day and see the 2Y button working: https://jsfiddle.net/manishnaik813/35L7cpmq/1/

Additionally, please note the Highcharts error 15 in the console, which means your data is unsorted.

**Comment by manish813** [comment]
Noticed now there was an hour difference because of which it was disabled. By considering only date I was able to make it work. Thanks @bm64
