### ISSUE TITLE
inline custom css variables are removed from the tooltip's formatter

### ISSUE THREAD

**Issue by roigiladi** [highcharts/highcharts#20880]
Hey, I'm trying to upgrade from 9.0.1 to latest (11.4.0) and faced the same issue reported here #17593 

here is a reproduction: https://codepen.io/rgong/pen/LYvxOmr 

1. i'm using `useHTML: true` and trying to apply a background color dynamically to the column tooltip's based on the series color
2. here i used v.9.0.1 which works correctly with custom variables, once you replace the script to use the latest version it doesn't work anymore

https://github.com/highcharts/highcharts/assets/110896135/25eca601-9a2c-4347-9124-3f014aff87ad

was this intentional or a regression? is there any workaround?

thanks!

**Comment by hubertkozik** [comment]
Thank you @roigiladi!
In that case, it would be better to reopen the mentioned issue, which was categorized by our bot as stale.

Closing this one as a duplicate.
