### ISSUE TITLE
Missing `hover` and `click` events after drilling down the map

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#20886]
#### Actual behaviour

Steps to reproduce the issue:
1. A user is able to drill down any country from the map by clicking its data label, e.g **Denmark** on the demo below
2. After drilling down and getting back up to the first level it's no longer possible to hover the country & drill down by clicking the data label. 

#### Live demo with steps to reproduce

https://www.highcharts.com/demo/maps/map-drilldown-preloaded

#### Product version
v11.4.0

#### Affected browser(s)
Chrome v122.0.6261.129

**Comment by hubertkozik** [comment]
_Internal note:_
The problem is related to `highcharts-tracker` class, which is not added to `series.dataLabelsGroup`.

Workaround: https://jsfiddle.net/BlackLabel/7bacgt63/
