### ISSUE TITLE
Axis label is not getting translated as per selected lang.

### ISSUE THREAD

**Issue by satyam20satyam** [highcharts/highcharts#20893]
Axis label is not getting translated as per selected lang.

I am passing below body into the request

{
  "options": {
  "lang": {
    "thousandsSep": ",",
    "month": [
      " 1 月",
      " 2 月",
      " 3 月",
      " 4 月",
      " 5 月",
      " 6 月",
      " 7 月",
      " 8 月",
      " 9 月",
      " 10 月",
      " 11 月",
      " 12 月"
    ],
    "shortMonths": [
      " 1 月",
      " 2 月",
      " 3 月",
      " 4 月",
      " 5 月",
      " 6 月",
      " 7 月",
      " 8 月",
      " 9 月",
      " 10 月",
      " 11 月",
      " 12 月"
    ],
    "weekdays": [
      "星期日",
      " 星期一",
      " 星期二",
      " 星期三",
      " 星期四",
      " 星期五",
      " 星期六"
    ],
    "shortWeekdays": [
      "周日",
      " 周一",
      " 周二",
      " 周三",
      " 周四",
      " 周五",
      " 周六"
    ],
    "decimalPoint": "."
  },
  "chart": {
    "type": "area"
  },
  "title": {
    "text": "设备总体趋势",
    "useHTML": true,
    "align": "center",
    "style": {
      "color": "#333333",
      "fontSize": "16px",
      "fontFamily": "Roboto",
      "fontWeight": "bold",
      "textTransform": "CAPITALIZE"
    }
  },
  "yAxis": {
    "lineWidth": 0,
    "allowDecimals": false,
    "title": {
      "enabled": false
    },
    "opposite": true,
    "labels": {
      "format": "{value}"
    }
  },
  "xAxis": {
    "type": "datetime",
    "tickPixelInterval": 1,
    "dateTimeLabelFormats": {
      "hour": "%I <br> %p",
      "day": "%e <br> %b",
      "month": "%b <br> %Y"
    },
    "lineWidth": 1,
    "lineColor": "#C0C0C0",
    "tickLength": 1,
    "tickWidth": 1
  },
  "legend": {
    "align": "center",
    "verticalAlign": "bottom",
    "layout": "horizontal",
    "symbolWidth": 4,
    "itemDistance": 30,
    "symbolPadding": 10,
    "symbolRadius": 0,
    "itemStyle": {
      "color": "#000000",
      "fontWeight": "normal",
      "fontFamily": "Roboto"
    }
  },
  "plotOptions": {
    "area": {
      "stacking": "normal",
      "lineColor": "#666666",
      "lineWidth": 1,
      "borderRadius": 0,
      "marker": {
        "lineWidth": 1,
        "lineColor": "#666666"
      },
      "events": {}
    }
  },
  "series": [
    {
      "name": "现场推测",
      "data": [
        [
          1677628800000,
          15968
        ],
        [
          1680307200000,
          16026
        ],
        [
          1682899200000,
          15801
        ],
        [
          1685577600000,
          15773
        ],
        [
          1688169600000,
          15821
        ],
        [
          1690848000000,
          9167
        ],
        [
          1693526400000,
          9251
        ],
        [
          1696118400000,
          9278
        ],
        [
          1698796800000,
          9302
        ],
        [
          1701388800000,
          9300
        ],
        [
          1704067200000,
          9400
        ],
        [
          1706745600000,
          9608
        ]
      ],
      "color": "#66FFFF",
      "marker": {
        "symbol": "square",
        "radius": 4
      }
    },
    {
      "name": "入站到客户",
      "data": [
        [
          1677628800000,
          16
        ],
        [
          1680307200000,
          0
        ],
        [
          1682899200000,
          47
        ],
        [
          1685577600000,
          30
        ],
        [
          1688169600000,
          10
        ],
        [
          1690848000000,
          28
        ],
        [
          1693526400000,
          15
        ],
        [
          1696118400000,
          34
        ],
        [
          1698796800000,
          28
        ],
        [
          1701388800000,
          0
        ],
        [
          1704067200000,
          33
        ],
        [
          1706745600000,
          31
        ]
      ],
      "color": "#E66268",
      "marker": {
        "symbol": "square",
        "radius": 4
      }
    },
    {
      "name": "操作中",
      "data": [
        [
          1677628800000,
          16
        ],
        [
          1680307200000,
          10
        ],
        [
          1682899200000,
          0
        ],
        [
          1685577600000,
          0
        ],
        [
          1688169600000,
          0
        ],
        [
          1690848000000,
          4
        ],
        [
          1693526400000,
          5
        ],
        [
          1696118400000,
          7
        ],
        [
          1698796800000,
          5
        ],
        [
          1701388800000,
          7
        ],
        [
          1704067200000,
          6
        ],
        [
          1706745600000,
          6
        ]
      ],
      "color": "#005A82",
      "marker": {
        "symbol": "square",
        "radius": 4
      }
    },
    {
      "name": "维修中",
      "data": [
        [
          1677628800000,
          96
        ],
        [
          1680307200000,
          110
        ],
        [
          1682899200000,
          47
        ],
        [
          1685577600000,
          76
        ],
        [
          1688169600000,
          93
        ],
        [
          1690848000000,
          103
        ],
        [
          1693526400000,
          151
        ],
        [
          1696118400000,
          70
        ],
        [
          1698796800000,
          91
        ],
        [
          1701388800000,
          122
        ],
        [
          1704067200000,
          75
        ],
        [
          1706745600000,
          97
        ]
      ],
      "color": "#333333",
      "marker": {
        "symbol": "square",
        "radius": 4
      }
    }
  ],
  "tooltip": {
    "shared": true,
    "dateTimeLabelFormats": {
      "hour": "%I %p",
      "day": "%b %e, %Y ",
      "month": "%b %Y"
    },
    "useHTML": true,
    "borderWidth": 1,
    "borderColor": "#007CB0",
    "style": {
      "padding": 5
    }
  }
}
}

#### Expected behaviour
Axis is not getting translated

![image](https://github.com/highcharts/highcharts/assets/35398589/d89ea494-9787-435f-bd75-03580f0c2415)

#### Actual behaviour
Axis should get translated

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

The `lang` object should be set with `setOptions`, and `lang.month` should be `lang.months`. See https://jsfiddle.net/highcharts/k3uyr8s5/.
