### ISSUE TITLE
Labels of X-Axis missing after drilldown

### ISSUE THREAD

**Issue by mawro453** [highcharts/highcharts#20920]
#### Expected behaviour
After drilling down and up the labels of the values should be shown instead of the values themselves.

Seems to be a similar issue to https://github.com/highcharts/highcharts/issues/19936

#### Actual behaviour
After drilling down and drilling up in a chart with many values, the last labels on the X-Axis are not showing the label (only the value).

Example from the demo below:
![image](https://github.com/highcharts/highcharts/assets/47977719/57d3f1d2-295d-4016-b3d6-4eb6e2343c1c)

Even though the category is initially defined as 'B69' and 'B72", after drilling to this series we only get the values '69' and '71'.

#### Live demo with steps to reproduce
Demo: https://jsfiddle.net/kfvrqxs9/18/

Steps:
- Drilling into "Gesamt" and "A1"
- Drilling back to "Gesamt"

#### Product version
- Highcharts 11.4.0

#### Affected browser(s)
- Tested with Chrome and Firefox, probably all browsers

**Comment by hubertkozik** [comment]
Hi @mawro453! Thanks for reporting the bug. This bug existed even in Highcharts v7, so it's with us for a long time. 

_Internal note:_
It is reproduced only when x-axis type is set to `category`: https://jsfiddle.net/BlackLabel/wh3djbo9/

**Comment by mawro453** [comment]
Thank you for addressing the issue. It's reassuring to know that the problem has been acknowledged. I've discovered a similar issue documented on GitHub [Issue #11561](https://github.com/highcharts/highcharts/issues/11561) which provides a workaround (using `cropThreshold`). I've implemented this workaround in my case and can confirm that it resolves the problem.

You can find a demo showcasing the workaround [here](https://jsfiddle.net/k8ymqcnj/2/). If anyone else encounters this issue, they might find this workaround helpful.

Thank you for your attention to this matter.

**Comment by hubertkozik** [comment]
Thank you @mawro453 for more information! I didn't find that ticket before. It looks, like this one is a duplicate, so let's close and continue the discussion in the old ticket.
