### ISSUE TITLE
Use exportChartLocal to export pdf Chinese garbled code

### ISSUE THREAD

**Issue by BblythePan** [highcharts/highcharts#20927]
I'm using 'exportChartLocal' to export 'application/pdf', but the Chinese in the pdf is garbled? How should this problem be solved
#### Actual behaviour

![test](https://github.com/highcharts/highcharts/assets/165253635/208c2d5c-7148-4326-8ac1-0c2cef798b25)

#### Live demo with steps to reproduce
https://jsfiddle.net/okh0y2cm/3/

**Comment by hubertkozik** [comment]
Hi @BblythePan.
This is not a bug. You should load your custom fonts using `exporting.pdfFont` (https://api.highcharts.com/highcharts/exporting.pdfFont).

We use GitHub as a tool for bugs/feature request tracking and your question is strictly a support question. Feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
