### ISSUE TITLE
Layout module not found

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#20929]
#### Expected behaviour
Compile without any error.

#### Actual behaviour
When following [documentation on how to create a dashboard with React](https://www.highcharts.com/docs/dashboards/dashboards-with-react) I get the error:
```
ERROR in ./node_modules/@highcharts/dashboards/modules/layout.js
Module not found: Error: Can't resolve 'dashboards' in '../node_modules/@highcharts/dashboards/modules'
```
My `tsconfig.json`:
```
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  ```

#### Workaround
When importing all from ESM, everything works without compilation errors.
```ts
import Highcharts from 'highcharts/es-modules/masters/highcharts.src';
import DataGrid from '@highcharts/dashboards/es-modules/masters/datagrid.src';
import Dashboards from '@highcharts/dashboards/es-modules/masters/dashboards.src';
import '@highcharts/dashboards/es-modules/masters/modules/layout.src';

Dashboards.HighchartsPlugin.custom.connectHighcharts(Highcharts);
Dashboards.DataGridPlugin.custom.connectDataGrid(DataGrid);

Dashboards.PluginHandler.addPlugin(Dashboards.HighchartsPlugin);
Dashboards.PluginHandler.addPlugin(Dashboards.DataGridPlugin);
```
#### Live demo with steps to reproduce
I'm only able to reproduce it locally. 

#### Product version
Highcharts Dashboards v2.0.0 (2024-03-13)

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
I could only recreate that with webpack and the React app created with CRA (the one compiled with Vite works fine). 
It looks like a webpack configuration issue.
However, adding this to the `webpack.confing.js` file fixed the issue:
```js
module.exports = {
    resolve: {
        modules: ['.', 'node_modules']
    }
};
```

Closing this for now as an issue not related to Dashboards.

**Comment by Nick-dv** [comment]
You can recreate it by creating a new vue application and implementing the most basic highcharts dashboard example.
Or jsfiddle: https://jsfiddle.net/amhf59dc/

@karolkolodziej this issue is closed as not planned, but a hacky fix shouldn't be the required for a paid product

**Comment by Nick-dv** [comment]
You can recreate it by creating a new vue application and implementing the most basic highcharts dashboard example.
Or jsfiddle: https://jsfiddle.net/amhf59dc/

@karolkolodziej this issue is closed as not planned, will it be fixed eventually? You shouldn't have to find a github issue to find a workaround for a bug
