### ISSUE TITLE
Error when using Navigator, axis inverted and boostThreshold

### ISSUE THREAD

**Issue by DarkSun812** [highcharts/highcharts#20936]
#### Expected behaviour
By using activate the inverted option with the boost module running and adding the browser it should show me the data

#### Actual behaviour
The data is printed but is not seen in the graph, it is as if a white box was on the data but there is no component on top, it seems that it does not render well
![Captura de pantalla 2024-04-01 160821](https://github.com/highcharts/highcharts/assets/53269346/609e1113-037f-46a5-8365-7eee6c893f70)

#### Live demo with steps to reproduce
Create a chart, include the series with the boost module, activate the inverted option of the chart and activate the navigator
 https://jsfiddle.net/5m0zcwj4/

#### Product version
"highcharts": "^11.4.0",
"highcharts-boost": "^0.1.7",

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Hi @DarkSun812 and thank you for reporting the issue! 

Internal note:
Last working version `11.1.0`. 
Bisected to: https://github.com/highcharts/highcharts/commit/2609a58dd894639004ff0d17c36269e2e1482f8a
FYI @kamil-musialowski

**Comment by DarkSun812** [comment]
> Hi @DarkSun812 and thank you for reporting the issue!
> 
> Internal note:
 Last working version `11.1.0`. Bisected to: [2609a58](https://github.com/highcharts/highcharts/commit/2609a58dd894639004ff0d17c36269e2e1482f8a) FYI @kamil-musialowski

How can I request a new functionality in the navigator options?

**Comment by karolkolodziej** [comment]
@DarkSun812 Please use [the feature request form here on GH](https://github.com/highcharts/highcharts/issues/new?assignees=&labels=Type%3A+Feature+Request&projects=&template=feature_request.md&title=) if you want to ask for additional functionalities.
