### ISSUE TITLE
Issue with flamechart in Vue

### ISSUE THREAD

**Issue by jjaramillom** [highcharts/highcharts#20945]
I wasn't sure where to open the issue, so I also opened one in [highcharts-vue](https://github.com/highcharts/highcharts-vue/issues/261)
#### Expected behaviour

A chart with the provided data 
![image](https://github.com/highcharts/highcharts/assets/31043682/7a747f85-a3f6-40cb-aa6f-24579426d190)

#### Actual behaviour
No chart. If I inspect the HTML elements I see an `<svg/>` element but with no actual content.
![image](https://github.com/highcharts/highcharts/assets/31043682/c28af2f3-2319-46d4-b382-2cc7a5a0439a)

#### Live demo with steps to reproduce
[Working version with vanilla JS](https://codepen.io/jjaramillom/pen/poBpKgM?editors=0010)
[Failing version with Vue](https://codesandbox.io/p/sandbox/cranky-haze-8vh89r?file=%2Fpackage.json%3A12%2C21)

#### Product version
Highcharts 11.4.0

#### Affected browser(s)

Chrome

**Comment by jszuminski** [comment]
Thanks for reporting!

I've answered your topic on the highcharts-vue repository here: https://github.com/highcharts/highcharts-vue/issues/261

Let's continue our discussion there.
