### ISSUE TITLE
Center track line when using tick amount

### ISSUE THREAD

**Issue by liemnguyenthanh** [highcharts/highcharts#20955]
#### Expected behaviour
Hi everyone. I am beginner.
when i using `tickAmount`  in `yAxis`
i wanna track line is center

#### Live demo with steps to reproduce
https://jsfiddle.net/d3vo6efm/20/

**Comment by bm64** [comment]
Hello @liemnguyenthanh, and thank you for reaching out to us.

We use GitHub strictly for feature requests and bug tracking. For any questions regarding chart configuration, please contact us through our other [support channels](https://www.highcharts.com/blog/support/), such as the [Highcharts Forum](https://www.highcharts.com/forum/). When creating a new ticket there, please provide clearer description of what you want to achieve, preferably with some illustration. Thanks in advance.
