### ISSUE TITLE
`SeriesLineOptions` & `SeriesColumnOptions` types missing in 11.4.1

### ISSUE THREAD

**Issue by denchen** [highcharts/highcharts#20956]
Starting in **11.4.1**, the types `Highcharts.SeriesColumnOptions` and `Highcharts.SeriesLineOptions` are missing. I've verified that they still exist in **11.4.0**.

#### Live demo with steps to reproduce
```typescript
const series: Array<
  | Highcharts.SeriesAreaOptions
  | Highcharts.SeriesColumnOptions
  | Highcharts.SeriesLineOptions
  | Highcharts.SeriesSplineOptions
> = [];
```

Typescript errors:
```
'"/Users/denchen/git/ui/node_modules/highcharts/highcharts"' has no exported member named 'SeriesColumnOptions'. Did you mean 'SeriesCmfOptions'?
'"/Users/denchen/git/ui/node_modules/highcharts/highcharts"' has no exported member named 'SeriesLineOptions'. Did you mean 'SeriesSplineOptions'?
```

#### Product version
11.4.1

**Comment by karolkolodziej** [comment]
Hi @denchen! 

Can you please walk me through how to recreate that? 
I've tried with the latest version and I don't get any errors-[ see the demo.](https://stackblitz.com/edit/highcharts-angular-line-4kzier?file=src%2Fapp%2Fapp.component.ts,node_modules%2Fhighcharts%2Foptions%2Fcolumn.d.ts)

As you can see this interface exists here with `v11.4.1`
![image](https://github.com/highcharts/highcharts/assets/57004120/0dd0caa4-de45-412b-b2ce-81786d757fbd)

**Comment by denchen** [comment]
Yeah, I see that exact line in `node_modules/highcharts/highcharts.d.ts` on **11.4.0**, but I don't see it on **11.4.1**

For **11.4.0**, the file size is:
```
$ ls -l node_modules/highcharts/highcharts.d.ts
-rw-r--r--  1 denchen  staff  23029484 Apr  5 00:25 node_modules/highcharts/highcharts.d.ts
```

For **11.4.1**, the file size is:
```
$ npm install highcharts@11.4.1 --save-dev

changed 1 package, and audited 2376 packages in 2s
16 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ ls -l node_modules/highcharts/highcharts.d.ts
-rw-r--r--  1 denchen  staff  3735521 Apr  5 00:28 node_modules/highcharts/highcharts.d.ts
```

So around 1/7th the size.

**Comment by karolkolodziej** [comment]
Since we've split the `.d.ts` files (see: https://github.com/highcharts/highcharts/pull/20727) that is probably correct. 

Can you please help me recreate that? 
Probably the `tsconfig` and the way you import and resolve modules matter.

**Comment by denchen** [comment]
> Since we've split the .d.ts files (see: https://github.com/highcharts/highcharts/pull/20727) that is probably correct.

Okay, this led me to figure out how to to get it working by basically having to explicitly import the `SeriesLineOptions` and `SeriesColumnOptions` types:

```typescript
import type { SeriesColumnOptions, SeriesLineOptions } from 'highcharts';

const series: Array<
  | Highcharts.SeriesAreaOptions
  | SeriesColumnOptions
  | SeriesLineOptions
  | Highcharts.SeriesSplineOptions
> = [];
```

Though this works, I'm not sure why I have to explicitly import those particular types when I could use the globally available `Highcharts` to use `SeriesAreaOptions` & `SeriesSplineOptions`. In fact, I'm not even sure why / how a global `Highcharts` is available since I don't have anything explicit in my `tsconfig.json` to do so.

**Comment by rbirkgit** [comment]
I updated to 11.4.1 and our project now gets error missing `Highcharts.SeriesPieOptions`

We used to only need to import
```
import Highcharts from 'highcharts/es-modules/masters/highcharts.src';
```

Not sure what to import now. I cannot find it defined anywhere in the es-modules folder.

**Comment by bre1470** [comment]
These types are not expected to be missing. Maybe your editor needs to reload the project.

You can try to import to explicitly set types to the `Highcharts` namespace:
```ts
import 'highcharts/options/pie.src';
```

Alternative might be to access the type via registry:
```ts
type SeriesPieOptions = Highcharts.SeriesOptionsRegistry['SeriesPieOptions'];
```

If none solution is working, please share your project configuration, so we can try to replicate the issue.

**Comment by bre1470** [comment]
@denchen 
> In fact, I'm not even sure why / how a global Highcharts is available since I don't have anything explicit in my tsconfig.json to do so.

The import of the Highcharts master creates a global namespace of itself for shared typing between multiple modules. This is just for easier access of types, but not necessarily available during runtime. It is recommended to access types via regular imports with named members.

**Comment by rbirkgit** [comment]
We get error on compile, so it's not an editor issue.

All we have is this import (to use ESM)
```
import Highcharts from 'highcharts/es-modules/masters/highcharts.src';
```

Then in our code:
```
export const DONUT_CHART_SERIES_BASE: Highcharts.SeriesPieOptions = {
  type: 'pie',
  data: []
};
```

This is the error:
```
Error: apps/accounts-and-resources/src/app/accounts-and-resources/highcharts.constants.ts:52:50 - error TS2724: '"D:/Git/cloud-ui/node_modules/highcharts/highcharts"' has no exported member named 'SeriesPieOptions'. Did you mean 'SeriesOptions'?

      52 export const DONUT_CHART_SERIES_BASE: Highcharts.SeriesPieOptions = {
                                                          ~~~~~~~~~~~~~~~~



```

**Comment by hubertkozik** [comment]
Thank you all. From what I can see all of the issues here are resolved. Closing as not a bug for now.
