### ISSUE TITLE
Tooltip not destroyed

### ISSUE THREAD

**Issue by markoberholzer-es** [highcharts/highcharts#20969]
#### Expected behaviour
Tooltip should always be destroyed when a mouse out event occurs.

#### Actual behaviour
On slower clients, tooltips may not be destroyed if the user moves the mouse rapidly across multiple charts.

#### Live demo with steps to reproduce
JsFiddle: [JSFiddle Demo](https://jsfiddle.net/snoopliving/2mkeocqh/)
Video: [Tooltip Demo Video](https://github.com/highcharts/highcharts/assets/64533830/48688a00-63b8-4e2c-958d-736efcbb63ac)

1. Open DevTools
2. Select Performance
3. Set CPU to 6x Slowdown (easier to reproduce)
4. Move mouse quickly a couple of times over all charts and then move it out of the canvas ex. devtools

#### Product version
Most likely the problem started to occur since after upgrading from 11.1.0 to 11.2.0 (newest version is affected as well)

**Comment by hubertkozik** [comment]
Hi @markoberholzer-es!

Indeed, I would treat it as a bug, because the tooltip should be destroyed after the delay time.

_Internal note:_
I tried to bisect, but there are too many issues in compiling between version 11.1.0 and 11.2.0.

**Comment by markoberholzer-es** [comment]
@hubertkozik - thx for your feedback and digging into that topic!

**Comment by MarkusBarstad** [comment]
Just a note on the example fiddle, @markoberholzer-es ; 

The charts in the fiddle seem to overlap in area. When I add some space between the charts plot areas (I used the `margin` css property) I am not able to reproduce the bug anymore.

Could this be the culprit?

**Comment by h3mpti** [comment]
> Just a note on the example fiddle, @markoberholzer-es ;
> 
> The charts in the fiddle seem to overlap in area. When I add some space between the charts plot areas (I used the `margin` css property) I am not able to reproduce the bug anymore.
> 
> Could this be the culprit?

Hi there, thanks for the feedback. Maybe it’s a workaround, but the behavior changed with the versions, so this is an undocumented breaking change with no real reason IMHO (and unfortunately that doesn’t seem to be the only case). An official fix/documented solution would be really appreciated.
