### ISSUE TITLE
Suport for multiple Pies

### ISSUE THREAD

**Issue by aemonge** [highcharts/highcharts#2096]
Enabling automatic sizing to fit container to multiple pies.

http://jsfiddle.net/u7FQS/4/

That is quite accurate but if you disable data from the legend, it wont affect all of the pies. Also the center variable it's isn't automatically calculated.

So if my data has two grids it should split 1/2 horizontally if it has four pies it should split 1/2 horizontal and 1/2 vertical... etc

**Comment by oysteinmoseng** [comment]
This can be done by setting center values as `%`. Example: http://jsfiddle.net/hmz4xxq9/

**Comment by aemonge** [comment]
You my friend, have been awarded with a [necromancer](https://stackoverflow.com/help/badges/17/necromancer) badge :)
