### ISSUE TITLE
Synchronization of connector values editing between components does not work correctly for connectors with modifier.

### ISSUE THREAD

**Issue by vazonik** [highcharts/highcharts#20968]
#### Expected behaviour
When the value of a cell in the datagrid is changed, the corresponding point in the synchronized component also changes according to the new value.

#### Actual behaviour
Changing the value in cell causes the point to disappear even if the condition in the modifier should be met.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/3hcke8zf/

Edit any cell in the `Iron` column in the datagrid.

#### Product version
Dashboards v2.0.0

**Comment by jomar-honsi** [comment]
The problem seems to be in the RangeModifier, function modifyTable(). Modifying an already modified table doesn't work as expected, because the row indexes of the original and the modified table are inconsistent.

**Comment by jomar-honsi** [comment]
Proposed solution.

Add an option to DataTable for creating a "virtual" (invisible) column that contains the rowIds.

This allows re-use of the existing DataTable logic and we can get away with few little changes to the code. The rowId's are accessible by referencing the "virtual" columns (must have a unique name).
