### ISSUE TITLE
Map changes January 2024: Norwegian County and municipalities

### ISSUE THREAD

**Issue by htveit** [highcharts/highcharts#20971]
There are new county and municipality classifications in Norway from January 2024
Can you please update the Norwegian maps with the new classifications

Counties:
https://www.ssb.no/klass/klassifikasjoner/104/endringer
Current map: https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/no/no-all

Municipalities:
https://www.ssb.no/klass/klassifikasjoner/131/endringer
Current map: https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/no/no-all-all

**Comment by hubertkozik** [comment]
Hi @htveit! The issue is already reported on `map-collection-dist` repository: https://github.com/highcharts/map-collection-dist/issues/133

Closing this one as a duplicate.
