### ISSUE TITLE
`decimalPoint` / `thousandsSep` not applied properly for `tooltip` and `dataLabels` when using `format` and `{point.y}`

### ISSUE THREAD

**Issue by alexboss** [highcharts/highcharts#20973]
#### Expected behaviour
`decimalPoint` / `thousandsSep` correctly applied for `tooltip` and `dataLabels` when no `format` is used, but also when using `format` and `{point.y}`.

#### Actual behaviour
✔️ `decimalPoint` / `thousandsSep` correctly applied for `tooltip` when no format used
See https://jsfiddle.net/0sjcxdyq/1/

❌ `decimalPoint` / `thousandsSep` not applied for `tooltip` when using `{point.y}`.
❌ `decimalPoint` / `thousandsSep` not applied for `dataLabels` when using `{point.y}`.
See https://jsfiddle.net/0sjcxdyq/2/

✔️ `decimalPoint` applied for `dataLabels` when using `{point.y:.1f}`.
❌ `thousandsSep` not applied for `dataLabels` when using `{point.y:.1f}`.
https://jsfiddle.net/0sjcxdyq/3/

#### Live demo with steps to reproduce
See links in actual behaviour.

#### Product version
Highcharts 11.4.1

#### Affected browser(s)
Tested on FF, but probably affecting all browsers

**Comment by bm64** [comment]
Hello @alexboss and thanks for reaching us.

As you can read in [our docs](https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting), in case where you need to format your tooltip or data labels and use Highcharts formatting, you should use `formatter` callbacks along with `numberFormat` and `dateFormat` methods. See the example: https://jsfiddle.net/BlackLabel/e2dh8157/

**Comment by alexboss** [comment]
Thank you for your feedback @bm64 .
Indeed, it works well using the formatter callback, the only problem is that we are using pure JSON to configure the chart and our parser would complain it's not valid JSON because of the formatter.
Anyway, we'll deal and live with it.
Best regards.
