### ISSUE TITLE
Range Selector dropdown doesn't open in Gantt chart

### ISSUE THREAD

**Issue by bm64** [highcharts/highcharts#20970]
#### Expected behaviour
Range Selector dropdown should open upon clicking, displaying the available ranges.

#### Actual behaviour
Range Selector dropdown does not open upon clicking.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/yn9hrv3u/

#### Product version
Highcharts Gantt v11.3.0 and newer (used to work correctly in v11.2.0)

#### Affected browser(s)
All

_Bisected to:_ https://github.com/highcharts/highcharts/commit/59f5b17ac90c13e3194fa72c9705f0c4769e930c FYI @pawellysy

**Comment by pawellysy** [comment]
Gets fixed by #20601.

**Comment by nurbek-mirai** [comment]
I don't think this is fixed, see: https://jsfiddle.net/egoja9hu/1/

**Comment by bm64** [comment]
Hi @nurbek-mirai 

The issue exists only when scrollablePlotArea is working. See: https://jsfiddle.net/BlackLabel/skv08nrg/ Therefore, the problem is most likely caused by another factor, so I have created another ticked: https://github.com/highcharts/highcharts/issues/21393
