### ISSUE TITLE
Problem with legend navigation when having many legends items

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#2098]
When having many legend items some of them won't get displayed correctly after scrolling down the list. 
![1](https://f.cloud.github.com/assets/5147078/900577/e416d3ee-fb67-11e2-9d04-93d0edf329ec.JPG)
![2](https://f.cloud.github.com/assets/5147078/900578/e4218d70-fb67-11e2-91cb-2b6befdaa548.JPG)

Setting padding to 0 doesn't help (and it looks worse!).
![3](https://f.cloud.github.com/assets/5147078/900587/24e2d602-fb68-11e2-8571-5a456ff2455e.JPG)

Example:
http://jsfiddle.net/highcharts/Hzh79/6/

The problem is that the pages are only added by pixels, so in some cases the divide between two pages will fall exactly in one item.

This could be solved in setting not maxHeight but the count of rows displayed (what isnt correct anyway - as some items can span over multiple rows).

But it should be checked whether an legend item falls completely inside the visible page - and hide the rest. And when scrolling down you have to start with next legend items from the top (same distance to top-border).

**Comment by andrewQwer** [comment]
We have the same issue on version 7.2.0, last items are cut off some times. Removing your fix for #2617 solves the problem, as we are ok to have more pages but all items visible rather than half visible row.

**Comment by VadimDyliko** [comment]
Here it is the screenshot of this issue:
https://ibb.co/m9bzDNz

**Comment by pawelfus** [comment]
Hi @VadimDyliko, @andrewQwer 

Please provide live demo of the issue, thanks!

**Comment by VadimDyliko** [comment]
Hi @pawelfus, 
Thank you for your quick response. Here it is live demo of the issue:  http://jsfiddle.net/VadimDyliko/xf5monaz/6/

**Comment by pawelfus** [comment]
Thanks for the demo! By default, we allow legend to reserve max half of the chart's height and it seems the values you use for symbol/item don't match reserved space. You can control when legend turns the pagination on using [`legend.maxHeight`](https://api.highcharts.com/highcharts/legend.maxHeight) option. Here is simple math to show n-lines without overflowing items: http://jsfiddle.net/BlackLabel/h6Lb0n2m/

```js
    legend: {
      layout: 'horizontal',
      borderWidth: 0,
      symbolHeight: symbolHeight,
      symbolWidth: 16,
      symbolRadius: 8,
      itemMarginTop: itemMarginTop,
      maxHeight: 6 * (symbolHeight + itemMarginTop)
    },
```

**Comment by VadimDyliko** [comment]
@pawelfus, thanks for the advice, but we have dynamically height and width of the chart container and it can be different count of entry's, so this solutions won't work for us. There is the same issue if it will be more entry's. http://jsfiddle.net/VadimDyliko/5rohma1s/

**Comment by pawelfus** [comment]
Let me report this a separate ticket: https://github.com/highcharts/highcharts/issues/12282 - could you try my workaround and let us results? Thanks!

**Comment by VadimDyliko** [comment]
Ок. I need some time to check it. Thanks!
