### ISSUE TITLE
Highcharts.SeriesPieOptions is missing with 11.4.1

### ISSUE THREAD

**Issue by rbirkgit** [highcharts/highcharts#20986]
#### Expected behaviour
No error building

#### Actual behaviour
We updated HIghcharts from 11.4.0 to 11.4.1 and with that we started getting error that `Highcharts.SeriesPieOptions` is not defined.

#### Live demo with steps to reproduce
This is how we import Highcharts with 11.4.0
```
import Highcharts from 'highcharts/es-modules/masters/highcharts.src';
```

#### Product version
11.4.1

**Comment by rbirkgit** [comment]
We get error on compile, so it's not an editor issue.

All we have is this import (to use ESM)
```
import Highcharts from 'highcharts/es-modules/masters/highcharts.src';
```

Then in our code:
```
export const DONUT_CHART_SERIES_BASE: Highcharts.SeriesPieOptions = {
  type: 'pie',
  data: []
};
```

This is the error:
```
Error: apps/accounts-and-resources/src/app/accounts-and-resources/highcharts.constants.ts:52:50 - error TS2724: '"D:/Git/cloud-ui/node_modules/highcharts/highcharts"' has no exported member named 'SeriesPieOptions'. Did you mean 'SeriesOptions'?

      52 export const DONUT_CHART_SERIES_BASE: Highcharts.SeriesPieOptions = {
                                                          ~~~~~~~~~~~~~~~~



```

**Comment by bre1470** [comment]
Hello @rbirkgit,

Thank you for the details. I need more information to have a chance of reproducing the issue.

Please provide the content of all `tsconfig.json`, the building command, and additional configuration files related to it.

You can also take a look at this working project https://github.com/bre1470/testproject-es6 and compare it with your configuration.

**Comment by rbirkgit** [comment]
Thanks for the short sample. I all works fine there (adding our code). I now see what is going on. 

Our code imported Highcharts in the main file. Then imported data from a model file. That model file didn't import Highcharts. It somehow worked anyway for most code and types including other series. But not the `SeriesPieOptions `. Go figure.

Adding the import of Highcharts at the top of the model file, the code compiles now without workarounds.

**Comment by rbirkgit** [comment]
I should be all set. Thanks for quick help!

**Comment by bre1470** [comment]
Thank you for sharing your solution. Wonderful that it works now. I will close the issue as solved. Feel free to comment further if needed.

Internal:  FYI @hubertkozik .

**Comment by hamfastgamgee** [comment]
I just ran into this.  It seems like SeriesPieOptions is not working if you also import highcharts-more.  If you are using only base Highcharts, the type is present.
