### ISSUE TITLE
New annotation position not respected after moving, copying and reexporting

### ISSUE THREAD

**Issue by ppcmetrics-thp** [highcharts/highcharts#20988]
#### Expected behaviour
The new position of the annotation must be respected on a new download/copy process.

#### Actual behaviour
- download or copy the chart -> annotation position as expected
- move the annotation
- download or copy the chart -> annotation position NOT as expected, resp. stays on the previous position

You can move the annotation initially before the first download/copy -> annotation positions are as expected. But on a further export after an additional change the positions are like the once from the first export.

#### Live demo with steps to reproduce
https://jsfiddle.net/4Lvc63e9/ (from #12789, but uses the latest code from https://code.highcharts.com/)

#### Product version
latest

#### Affected browser(s)
Chrome

**Comment by ppcmetrics-thp** [comment]
I could fix it by adding following lines to [Exporting.ts#L1216](https://github.com/highcharts/highcharts/blob/master/ts/Extensions/Exporting/Exporting.ts#L1216):
```php
const chartHeightFactor = chart.chartHeight / options.exporting.sourceHeight;
const chartWidthFactor = chart.chartWidth / options.exporting.sourceWidth;
options.annotations.forEach((annotation, index) => {
    if (
        typeof annotation.labels[0] !== 'undefined' &&
        typeof chart.annotations[index]?.labels[0]?.options !== 'undefined'
    )
    annotation.labels[0].x = chart.annotations[index].labels[0].options.x * chartWidthFactor;
    annotation.labels[0].y = chart.annotations[index].labels[0].options.y * chartHeightFactor;
});
```

Since I don't think this is the right place in the code, I waited to submit a pull request.

**Comment by karolkolodziej** [comment]
Hi @ppcmetrics-thp! 
Thank you for reporting the issue! 

Your suggestion seems to be valid, thank you for that!

**Comment by ppcmetrics-thp** [comment]
Hi @karolkolodziej , but is this really the right place to fix the bug? Isn't there an update function in the annotation module which needs to be fixed instead of the export function?

**Comment by ppcmetrics-thp** [comment]
@karolkolodziej  I'm getting following error in VS Code:
`Property 'annotations' does not exist on type 'ChartComposition'.ts(2339)`  
This error comes from the line:  
`typeof chart.annotations[index]?.labels[0]?.options !== 'undefined'`

I suppose this error would fail the defined GitHub actions. Can you show me please how I can avoid this error?

**Comment by ppcmetrics-thp** [comment]
Thank you for the fix!
