### ISSUE TITLE
Customizing Navigator Button Style and Retrieving Last Selected Button Details

### ISSUE THREAD

**Issue by MuhammedHarisMKS** [highcharts/highcharts#20996]
### **Description**
My current focus is on customizing the button style and retrieving details of the last selected button within the Highcharts navigator. These enhancements will significantly improve user interaction with our charts.

### **Feature Details**

> **Customizing Button Style:**

- Allow users to customize the appearance of navigator buttons (e.g., color, shape, size).
- Provide options to match the button style with the overall theme of the chart or application.
- Enhance visual consistency and aesthetics.

> **Retrieving Last Selected Button Details:**

- When a user clicks a navigator button (e.g., zoom in, zoom out), capture and store information about the selected button.
- This information can be useful for analytics, tracking user behavior, and improving navigation within the chart.

### **Benefits and Impact**

> **Enhanced User Experience:**

- Customizable button styles make the interface more user-friendly.
- Retrieving last selected button details allows users to understand their navigation history.

> **Improved Chart Interaction:**

- Users can quickly identify the current view based on the last selected button.
- Developers can analyze user preferences and optimize button placement.

### **Alternatives**
Currently, there are no alternatives for customizing button styles or retrieving last selected button details within the Highcharts navigator.
### **Consequences**
If this feature is 

> **not implemented:**

- Users may find the default button style less appealing.
- Tracking user interactions may be challenging without button details.

### **Sample Image**

![Screenshot 2024-04-08 162109](https://github.com/highcharts/highcharts/assets/166785213/913a1713-79d9-4d78-a914-0b7fb6e90912)

**Comment by hubertkozik** [comment]
Hi @MuhammedHarisMKS! The described feature is already implemented and you can easily use it to style the chart with your requirements. Please, check the links below to see some examples. To style the selected buttons, you can use `buttonTheme.states.select` option.

**Live demo:** https://jsfiddle.net/BlackLabel/Ly3xrum6/
**API Reference:** https://api.highcharts.com/highstock/rangeSelector.buttonTheme

There's also a possibility to style your chart with CSS using styled mode: https://www.highcharts.com/docs/chart-design-and-style/style-by-css 

If you need some help with Highcharts configuration feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.

**Comment by MuhammedHarisMKS** [comment]
Hi @hubertkozik,

Thank you for your quick response. I appreciate the resources you've provided, but I've already tried the method you described and it's not working as expected in my project. Let me clarify my requirements:

1. I want to call APIs on every button click. This part is already implemented and working fine.
2. At the same time, I want to pass the **_`selected`_** value of the last clicked button. Unfortunately, this isn't working.
3. I'm using the exporting button in my project and would like to replace the button text label with icons (png/jpeg).

I hope this clarifies my situation. Any further guidance would be greatly appreciated.

**Comment by hubertkozik** [comment]
@MuhammedHarisMKS, your requirements are already possible in Highcharts, so there is no need to create a Feature Request ticket. We use GitHub as a tool for bugs/feature request tracking and your question is strictly a support question. Feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.

**Comment by MuhammedHarisMKS** [comment]
@hubertkozik I have already contacted them. They suggested creating a feature request in git (3ed point). That's why we created this ticket here.

**Comment by hubertkozik** [comment]
@MuhammedHarisMKS I'm really sorry, someone has misled you. You can change the exporting context menu to show icons like your design requires. Here's the API reference: https://api.highcharts.com/highcharts/exporting.buttons.contextButton.text

And there you can find a demo, which is perfect for your requirements - [Icon using CSS font in text](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/exporting/buttons-text-usehtml/).

**Comment by MuhammedHarisMKS** [comment]
@hubertkozik Thank you for your quick response.

**Comment by MuhammedHarisMKS** [comment]
@hubertkozik Iam able to add icons in my project. But not able to change their height and width. 

> Code Sample 

` exporting: {
      buttons: {
        contextButton: {
          enabled: false,
        },
        lineButton: {
          symbol: "url(src/LineIcon.png)",
          width: 30,
          height: 30,
          onclick: function () {},
          theme: {
            fill: "transparent", // makes the background transparent
            "stroke-width": 1, // adjust as needed
            stroke: "none",
            r: 8,
            style: {
              color: "#cfa04f",
              fontWeight: "bold",
              "border-bottom": "3px solid #cfa04f", // adjust as needed
            },
            states: {
              hover: {},
              select: {
                fill: "#cfa04f",
                style: {
                  color: "white",
                },
              },
            },
          },
        },
        ohlcButton: {
          symbol: "url(src/OHLCIcon.png)",
          width: 30,
          height: 30,
          onclick: function () {},
          theme: {
            fill: "none", // makes the background transparent
            "stroke-width": 1, // adjust as needed
            stroke: "none",
            r: 8,
            style: {
              color: "#cfa04f",
              fontWeight: "bold",
              "border-bottom": "3px solid #cfa04f", // adjust as needed
            },
            states: {
              hover: {},
              select: {
                fill: "#cfa04f",
                style: {
                  color: "white",
                },
              },
            },
          },
        },
      },
    },`

> Sample Image 

![Screenshot 2024-04-17 112209](https://github.com/highcharts/highcharts/assets/166785213/2bd1c12e-b5e6-42d2-80da-4a0be12f4915)

How can I change height and width. Also I tried `symbolWidth: 30,  symbolHeight: 30,` .

**Comment by hubertkozik** [comment]
@MuhammedHarisMKS You can set the `symbolSize`. Please, in case of any next configuration questions write to us through one of our Support channels. We use GitHub as a tool for bugs/feature request tracking.
