### ISSUE TITLE
Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by coligomed-rverma** [highcharts/highcharts#21020]
#### Issue

I am using Highchart with Highchart React, and using the column chart, I am passing all the data and the data is also an array every time, but still, I am getting this undefined error in sentry.

Here is the screenshot of stack trace, please some look into this issue.

![image](https://github.com/highcharts/highcharts/assets/135992336/0653d1bf-9921-4c96-a25d-209ee6a19b91)

Below is the chart option that I am passing
```
{
  chart: {
    height: 132,
    type: "column",
  },
  title: {
    text: undefined,
  },
  legend: { enabled: false },
  xAxis: {
    categories: ["Jan', "Feb", ....],
    title: undefined,
    labels: {
      style: {
        textOverflow: "none",
      },
    },
  },
  yAxis: {
    gridLineWidth: 1,
    gridLineDashStyle: "Dash",
    title: undefined,
    opposite: true,
    tickInterval: 50,
  },
  tooltip: {
    enabled: true,
    backgroundColor: "#fff",
    borderRadius: 6,
    xDateFormat: "%b", // for full format use "%e %b %Y %l:%M %p",
  },
  credits: {
    enabled: false,
  },
  exporting: {
    enabled: false,
  },
series: [
      {
        name: "7 Days",
        color: colors.primary,
        data: data7Days,
      },
      {
        name: "14 Days",
        color: colors.success.main,
        data: data14Days,
      },
    ],
}
```
**Note** data7Days and data14Days are always an array

#### Product version
```
"highcharts": "^9.3.3",
"highcharts-react-official": "^3.1.0",
 ```

**Comment by bm64** [comment]
Hello @coligomed-rverma 

Thank you for providing the Sentry logs, but I need a reproducible example to identify and resolve the issue. Please use this demo template: https://stackblitz.com/edit/react-bg2pca?file=index.js

**Comment by coligomed-rverma** [comment]
> Hello @coligomed-rverma
> 
> Thank you for providing the Sentry logs, but I need a reproducible example to identify and resolve the issue. Please use this demo template: https://stackblitz.com/edit/react-bg2pca?file=index.js

Here is the template https://stackblitz.com/edit/react-s3c1qx?file=index.js, though this does not give an error here. This is just happening randomly and happening in prod. 

Actually, I have a data range changer dropdown, and when it is changed we call API to fetch new data. Then only the undefined error occurred. And this is happening in production only not in dev. So not sure why this error it there. 

Please help me out, thanks.

**Comment by bm64** [comment]
Hello @coligomed-rverma 

Unfortunately without being able to reproduce the issue, I won’t be able to help. The configuration appears correct and it likely isn’t a bug, but rather some misconfiguration. My advice would be to ensure the fetched data actually exists. Perhaps the new chart options are being set before the data arrives. Try adding statements to check if the fetched data exists; if not, return some hardcoded data. This should help isolate the issue.
