### ISSUE TITLE
Calling chart.update() with rangeSelector buttons after removing series causes javascript error

### ISSUE THREAD

**Issue by marklofdahl** [highcharts/highcharts#21043]
#### Expected behaviour
Removing all series and then calling chart.update() with rangeSelector buttons should not cause a javascript error.

#### Actual behaviour
Removing all series and then calling chart.update() with rangeSelector buttons causes a javascript error.

The following code is run, but chart.navigator.baseSeries[0].xAxis is undefined.

                    if (chart.navigator && chart.navigator.baseSeries[0]) {
                        chart.navigator.baseSeries[0].xAxis.options.range = void 0;
                    }

Sometimes my code will reuse a chart object by removing series, updating settings, and adding new series. This is no longer working in this case.

#### Live demo with steps to reproduce
https://jsfiddle.net/marklofdahl/0e9g6smv

#### Product version
Doesn't work in Highcharts Stock 11.3 and later
Works in Highcharts Stock 11.2 and earlier

#### Affected browser(s)
All

**Comment by hubertkozik** [comment]
Hi @marklofdahl! You are right, it's a regression. Below you can find a demo with a workaround until the fix is applied to future releases of Highcharts. If you want to use it in your project simply copy-paste the IIFE function.

**Workaround:** https://jsfiddle.net/BlackLabel/vqmjf7eu/

_Internal note:_
Bisected to: 7da7044e184d943246951a72ad46a79869d56e80.

**Comment by pawelfus** [comment]
Alternative workaround:
Use `useToOne` option in [`chart.update(options, redraw, oneToOne)`](https://api.highcharts.com/class-reference/Highcharts.Chart#update) instead of manually removing series. Demo: https://jsfiddle.net/BlackLabel/frowpu97/ 

Snippet:
```js
  chart.update({
    rangeSelector: {
      buttons: [{
        count: 6,
        text: '6m',
        type: "month"
      }, {
        text: 'All',
        type: "all"
      }]
    },
    series: [series]
  }, true, true);
```

**Comment by kamil-musialowski** [comment]
Internal note: Problem was not with the `rangeSelector` but with the navigator itself (`baseSeries` removal logic).
