### ISSUE TITLE
In Bar chart remove spaces between bars belong to same category for which data is null

### ISSUE THREAD

**Issue by bhuvangu** [highcharts/highcharts#2105]
http://jsfiddle.net/QnU9e/1/

The space between blue bar and green bar in C1 should not be there or should be configurable

![chart](https://f.cloud.github.com/assets/1015086/911464/7b4cc8b4-fdec-11e2-8c6c-98d0157b5676.jpeg)

**Comment by inoamicro** [comment]
@highslide-software: is column placement still not configurable when there are categories with null data? Any ideas on how to get around @bhuvangu exact same issue? Thank you both!

**Comment by highslide-software** [comment]
@inoamicro No, it will still leave a space for the null column. The placement of the columns is based on the number of series, it does not look at the number of points in each category.

**Comment by cibdev** [comment]
Did someone found a solution for this ? I have the same issue

**Comment by pawelfus** [comment]
Check [`column.centerInCategory`](https://api.highcharts.com/highcharts/series.column.centerInCategory) option @cibdev

**Comment by cibdev** [comment]
Thanks! That is almost what i was looking for. On this [example](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series-column/centerincategory/)
, do you know if it possible to change the width of the may column to fit the white spaces between april-may and may-june ?

**Comment by pawelfus** [comment]
Hi @cibdev - if you have any further questions, please contact our support team :) We use GitHub issues for bug reports.

**Comment by anupamaaustralia** [comment]
column.centerInCategory was very useful, thanks for that. @cibdev, did you even find a way to reduce the width of the May column? That is exactly what I am looking to do now on my side. Thanks.

**Comment by raf18seb** [comment]
It's not possible with the current implementation of `centerInCategory`.
