### ISSUE TITLE
Pie: no dataLabels causes different drawing

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2106]
when setting `dataLabels.enabled` to `false` on a pie serie, it is drawn different (and wrong?).
http://jsfiddle.net/W4EEg/3/
http://jsfiddle.net/W4EEg/4/

**Comment by oysteinmoseng** [comment]
Seems to work as expected in current version, even with original fiddle.

**Comment by iweindesmedt** [comment]
original fiddle (2nd one) still shows the bug, but in highchart-latest its fixed. great!
