### ISSUE TITLE
Stock tool buttons active class issue

### ISSUE THREAD

**Issue by codeWarriors-pro** [highcharts/highcharts#21064]
#### Expected behaviour
On one click, the state should toggle with the functionality

#### Actual behaviour
Functionality toggles but button's active state doesn't. It changes after 2 clicks on button and on 3rd click it doesn't enable but functionality gets enabled.

https://github.com/highcharts/highcharts/assets/114612630/4d59d7c3-46c7-40bb-96c0-ed138fe9e1ed

**Comment by bm64** [comment]
Hello @codeWarriors-pro and thanks for reporting the issue.

Seems like it used to work correctly in v10.2.0: https://jsfiddle.net/BlackLabel/5dfbgx6c/

_Internal note:_ 
Unable to bisect.

**Comment by codeWarriors-pro** [comment]
Thanks @bm64 

When I can expect this to be resolved?

**Comment by bm64** [comment]
Hi @codeWarriors-pro 

Currently I can't provide any ETA for the fix, but tomorrow after planning I should be able to provide more information. Thanks for your patience.
