### ISSUE TITLE
Keep tooltip open on hover

### ISSUE THREAD

**Issue by lpillayib** [highcharts/highcharts#21072]
Hi!
Low vision users often magnify the pages significantly and require scrolling to view everything. They require the element to be visible on the screen when the mouse pointer is hovering over it.
I need to keep the tooltip open if the mouse is hovering over it. When the mouse pointer leaves the tooltip, the tooltip of the point where the mouse is would open.
The default behavior of the tooltips would be the same, only difference being that it does not close/change when the mouse pointer hovers over it.
If someone is willing to take this up, it would greatly improve the accessibility of the charts.

**Product version**
"highcharts": "^8.1.2",

**Affected browser(s)**
N/A

**Comment by karolkolodziej** [comment]
Hi @lpillayib! 

This functionality seems to have already been implemented for tooltips, wherein they persistently remain open as long as the mouse pointer is hovering over them.

Could you please elaborate or show when it doesn't work?

**Comment by TorsteinHonsi** [comment]
Maybe [stickOnContact](https://api.highcharts.com/highcharts/tooltip.stickOnContact) is relevant?

**Comment by lpillayib** [comment]
@TorsteinHonsi  @karolkolodziej  It worked, thank you!
