### ISSUE TITLE
Highchart map issue 

### ISSUE THREAD

**Issue by yasirrose** [highcharts/highcharts#21075]
Dear Highcharts Support Team,

I hope this message finds you well. We are currently using Highcharts for our project and have been impressed with its capabilities in visualizing geographical data.

We have a requirement to display Puerto Rico (PR) as a separate state on the USA map within our application. However, we noticed that Puerto Rico is not included in the default map data provided by Highcharts.

**Comment by hubertkozik** [comment]
Hi @yasirrose! Puerto Rico maps are available in our Highcharts Map Collection. You can find all maps here: https://code.highcharts.com/mapdata/

Puerto Rico admin1: https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/pr/pr-all
Puerto Rico admin2: https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/pr/pr-all-all

**Comment by yasirrose** [comment]
I'm using the map from 'https://www.highcharts.com/demo/maps/map-drilldown', but the Puerto Rico (PR) state is not shown on this map. I've also included the PR code in the data, but it's still not added to the map. Can you please provide a solution for this issue?

![image](https://github.com/highcharts/highcharts/assets/5586359/d5567ee5-21b7-432b-bf61-1b25ecbf35a6)

**Comment by hubertkozik** [comment]
@yasirrose Here's the Highcharts Map Chart with two topologies: https://jsfiddle.net/BlackLabel/9oj8qen3/

We use GitHub as a tool for bugs/feature request tracking and your question is strictly a support question. Feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
