### ISSUE TITLE
Wrong date - occurs when you select Zoom "All"

### ISSUE THREAD

**Issue by NEGgrup** [highcharts/highcharts#21078]
#### Expected behaviour
Samme dato på eldste verdi uavhengig om man bruker zoom All eller zoom 1y for så og scrolle seg til eldste verdi. Verdien ses i tooltip

The same date on the oldest value regardless of whether you use zoom All or zoom 1y to then scroll to the oldest value. The value can be seen in the tooltip

#### Actual behaviour
Viser feil dato i starten av grafen, altså de eldste verdiene, Dette oppstår når man velger Zoom "All". Viser riktig dato eks, om man bruker Zoom "1Y" og bruker scrollbar for å komme til eldste dato.

Shows the wrong date at the start of the graph, i.e. the oldest values, This occurs when you select Zoom "All". Shows the correct date, for example, if you use Zoom "1Y" and use the scrollbar to get to the oldest date.

#### Live demo with steps to reproduce
[891499](https://jsfiddle.net/Erling_Ryger/4dgbvL0n/3/)

#### Product version
<script src="https://code.highcharts.com/stock/highstock.js"></script>
<script src="https://code.highcharts.com/stock/modules/exporting.js"></script>
<script src="https://code.highcharts.com/stock/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

#### Affected browser(s)
Chrome

**Comment by bm64** [comment]
Hello @NEGgrup 

This is not a bug - the difference in dates is caused by data grouping feature. More about data grouping you can read here: https://www.highcharts.com/docs/stock/data-grouping

There is a `firstAnchor` options which most likely can solve your problem. Try setting its value to `firstPoint`: https://jsfiddle.net/BlackLabel/6endqm94/

**Comment by NEGgrup** [comment]
Hei

Perfect 😊

Thanks..

Med vennlig hilsen

Erling Ryger

Mob: +47 480 36 911
Web: www.neg.no<http://www.neg.no/>

Fra: Mateusz Bernacik ***@***.***>
Sendt: mandag 29. april 2024 00:21
Til: highcharts/highcharts ***@***.***>
Kopi: Erling Ryger ***@***.***>; Mention ***@***.***>
Emne: Re: [highcharts/highcharts] Wrong date - occurs when you select Zoom "All" (Issue #21078)


Hello @NEGgrup<https://github.com/NEGgrup>

This is not a bug - the difference in dates is caused by data grouping feature. More about data grouping you can read here: https://www.highcharts.com/docs/stock/data-grouping

There is a firstAnchor options which most likely can solve your problem. Try setting its value to firstPoint: https://jsfiddle.net/BlackLabel/6endqm94/
