### ISSUE TITLE
Initialized column width for "linear" and "reversed" x axis ignores settings

### ISSUE THREAD

**Issue by lsmli** [highcharts/highcharts#21074]
#### Expected behaviour
If xAxis.type is "linear", column width should match my settings and stay consistent regardless of the order in which I pass in my datapoints. 

#### Actual behaviour
If xAxis.type is "linear" but the series.data is passed from high to low x value, the column width does not respect the "pointPadding" setting at all and column widths appear too wide. Once I reverse the dataset, column width becomes much thinner and respects the settings. 
The calculation for column width should be consistent regardless of the order of the data passed in series.data

#### Live demo with steps to reproduce
https://stackblitz.com/edit/react-starter-typescript-9dtsrt?file=App.tsx

#### Product version
"highcharts": "11.4.1"
"highcharts-react-official": "3.2.1"

#### Affected browser(s)
All browsers

**Comment by karolkolodziej** [comment]
Hi @lsmli! 

As one of our support engineers explained there is no need to reverse the data and the axis simultaneously.
Setting only the axis does the job - [demo](https://jsfiddle.net/BlackLabel/zL41mk6p/).
