### ISSUE TITLE
Setting chart size does not work when switching from boost to standard mode

### ISSUE THREAD

**Issue by benochr** [highcharts/highcharts#21106]
#### Expected behaviour
`setSize` keeps working when switching from boost mode to standard mode.

#### Actual behaviour
When we switch from boost mode to standard mode, `setSize` does not work anymore. A part of the plotted series is invisible.

![image](https://github.com/highcharts/highcharts/assets/4375262/a460b2e8-4eb5-4400-99c0-fe4c66f54b00)

#### Live demo with steps to reproduce
https://jsfiddle.net/w0gL1poh/51/

1. Start in standard mode, play around with the size (increase, decrease, reset), everything works as expected
2. Toggle on boost mode, play around with the size (increase, decrease, reset), everything works as expected
3. Toggle off boost mode, decrease size works as expected, increase size does not work, only part of the series is shown

It seems as if the (initial) size (at the time you disable boost mode) is the max size and you cannot increase width or height beyond this size.

#### Product version
Highcharts v11.4.1

#### Affected browser(s)
Version 124.0.6367.119 (Official Build) (arm64)

**Comment by bm64** [comment]
Hello @benochr and thanks for reporting the issue.

Looks like it used to work correctly in v11.3.0 and has been broken since v11.4.0: https://jsfiddle.net/BlackLabel/43ydsw7h/

_Internal note:_ 
Bisected to: 55e51615f1f0752e4a3231eb289643516c572a5c

**Comment by benochr** [comment]
Hello @bm64

Do you have any idea when this will be solved? We reverted back to v11.3.0, but cannot upgrade until this is fixed.

**Comment by hubertkozik** [comment]
Hi @benochr! I've put this ticket as a high priority in our backlog. We will investigate it soon :)
