### ISSUE TITLE
Line vs. Pie: different behaviour on color:undefined

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2111]
behaviour when setting a data point's ```color``` to ```undefined```:
- Pie: color is not drawn immediately but when hovering the slice a few times
- Line (and others I suppose, not tested): color is drawn immediately

http://jsfiddle.net/W4EEg/7/

tested in all recent major browsers.

**Comment by sebastianbochan** [comment]
Works fine since 4.2.1
