### ISSUE TITLE
Special characters appear to break string label format

### ISSUE THREAD

**Issue by bensaufley** [highcharts/highcharts#21124]
#### Expected behaviour
Passing in either a UTF-8 character like `’` (left single quote) or the escape equivalent `\u2019` into a label format template (`{value:%b ’%y}`) renders labels properly, with value substitution

#### Actual behaviour
Labels render as template string

#### Live demo with steps to reproduce
https://codepen.io/bensaufley-the-animator/pen/ExJqzgE?editors=0010

#### Product version
Noticed this after an update to Highcharts v11. Reproduced in at least latest version, 11.4.1

#### Affected browser(s)
Reproduced in latest versions of Chrome, Firefox, Safari and Edge on MacOS Sonoma.

#### Notes

It looks like this is avoidable _at least in my case_ by breaking up the templates: `{value:%b} \u2019{value:%y}`; but including the apostrophe inline did work in 10.3, so this may be a regression?

**Comment by hubertkozik** [comment]
Hi @bensaufley! You're right, it seems to me, that it is a regression.

As a workaround, you can set a normal apostrophe instead of the escape equivalent: https://jsfiddle.net/BlackLabel/zxrsmy1n/

_Internal note:_
Bisected to: 7477088fb1bce0e29a36c3026b4f80b337993d40
