### ISSUE TITLE
Inverted chart with bubble series look out of place

### ISSUE THREAD

**Issue by Marcevalmon** [highcharts/highcharts#21125]
Recently, we updated Highcharts from version 9 to 11.

There's a scenario where we have a bar chart that has a scatter series, so in version 9, the chart is displayed properly, but in version 11, the visualization looks broken.

#### Expected behaviour

![Screenshot 2024-05-06 10 38 46 AM](https://github.com/highcharts/highcharts/assets/12143145/b1e2ad71-62d6-4c45-a620-556b5f7dc940)

#### Actual behaviour

![Screenshot 2024-05-06 10 38 53 AM](https://github.com/highcharts/highcharts/assets/12143145/8c7490d6-a732-45a8-8bad-3b20479fbfc2)

#### Live demo with steps to reproduce
[Higcharts 9](https://jsfiddle.net/w6jkfpuo/1/)
[highcharts 11 (Scatter broken)](https://jsfiddle.net/g73ayhkj/)

#### Product version
11.2.0

Is there something I'm missing, or is this a bug?

Thanks

**Comment by bm64** [comment]
Hi @Marcevalmon and thanks for reporting the issue. 

It looks like it used to work correctly back in v9.3.3 and has been broken since v10.0.0

_Internal note:_ 
Bisected to: eded2848bc7dee832333e38e7d770accd28ae711
