### ISSUE TITLE
Exported image containes rectangles instead of characters.

### ISSUE THREAD

**Issue by miralee77** [highcharts/highcharts#21137]
#### Expected behaviour
![스크린샷 2024-05-08 104111](https://github.com/highcharts/highcharts/assets/114647601/3eb1ee03-5e3c-48f2-bb58-037a88a73ebb)

**Comment by hubertkozik** [comment]
Hi @miralee77! This looks like a limitation of public Export server accessible via https://export.highcharts.com/

If you would like to use different fonts for different languages you can set up your own Export server, docs: https://github.com/highcharts/node-export-server?tab=readme-ov-file#install and choose and install correct font: https://github.com/highcharts/node-export-server?tab=readme-ov-file#installing-fonts
