### ISSUE TITLE
Election demo popup modal not working in fullscreen mode

### ISSUE THREAD

**Issue by jedrzejruta** [highcharts/highcharts#21139]
#### Expected behaviour
Popup opens after clicking on any state in fullscreeen mode

#### Actual behaviour
Popups don't appear after clicking on each state when in fullscreen mode, after exiting they are stacked up in bottom-right corner of the demo.

#### Live demo with steps to reproduce
Enter fullscreen mode and click on any state.
[https://www.highcharts.com/demo/maps/data-class-two-ranges](https://www.highcharts.com/demo/maps/data-class-two-ranges)

**Comment by hubertkozik** [comment]
_Internal note:_
My proposal: JQuery should be removed from that demo and the custom popup should be implemented in vanilla JS.
