### ISSUE TITLE
Animation False Does Not Affect mouse-wheel-zoom

### ISSUE THREAD

**Issue by fehmisener** [highcharts/highcharts#21143]
#### Expected behaviour

When I set `animation: false` in my config, I expect no animations while zooming in and out with the mouse wheel.

#### Actual behaviour
![bug](https://github.com/highcharts/highcharts/assets/58306766/31f2a059-282a-4884-bf90-15b3d3160d98)

#### Live demo with steps to reproduce

Can be seen in my application when uploading a CSV file. https://github.com/fehmisener/dataviz-explorer
Note: In the code I didn't set `animation: false`, to observe this situation, it needs to be changed

#### Product version

Highcharts

**Comment by hubertkozik** [comment]
Hi @fehmisener! 

I've created a simple demo with a mouse wheel zooming module. As you can see after setting `chart.animation` to `false` there is no animation after zooming into using mouse wheel.

**Live demo:** https://jsfiddle.net/BlackLabel/ra5kwdbq/
**API Reference:** https://api.highcharts.com/highcharts/chart.animation

Your project contains a lot of code, so could you please recreate a simple demo with reproduced issue?

**Comment by fehmisener** [comment]
> Hi @fehmisener!
> 
> I've created a simple demo with a mouse wheel zooming module. As you can see after setting `chart.animation` to `false` there is no animation after zooming into using mouse wheel.
> 
> **Live demo:** https://jsfiddle.net/BlackLabel/ra5kwdbq/ **API Reference:** https://api.highcharts.com/highcharts/chart.animation
> 
> Your project contains a lot of code, so could you please recreate a simple demo with reproduced issue?

Hey,

You can see the example scenario below. I found this demo in the [official API documentation](https://api.highcharts.com/highcharts/boost) and just added the boost module (with animation false).

Live Demo: https://jsfiddle.net/eLhp7nfr/7/

Thanks a lot!

**Comment by hubertkozik** [comment]
@fehmisener, there is no option like `animation`, which can be set in the root level of the Highcharts chart configuration object. To disable the animation used in mouse-wheel zoom you should set the `chart.animation` option to `false`.

**Live demo:** https://jsfiddle.net/BlackLabel/h6g0xkm7/
**API Reference:** https://api.highcharts.com/highcharts/chart.animation

Closing this one as a support question. We use GitHub as a tool for bugs/feature request tracking and your question is strictly a support question. Feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
