### ISSUE TITLE
Packedbubble breaks on update data

### ISSUE THREAD

**Issue by jordibaliellas** [highcharts/highcharts#21145]
#### Expected behaviour
When I change the state of the options I expect the chart to do not break just update the chart with the new options.

#### Actual behaviour
after some rerenders it breaks, completly random, some times it takes 3 clicks other times 5, so it's impossible for us to see the issue.

#### Live demo with steps to reproduce
Here the link:

templete: [codesandbox](https://codesandbox.io/p/devbox/wandering-cache-gvjnyq?workspaceId=9510fb79-72bf-4225-aaac-5c84332f4475&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvz4z0rb00073b6lury5b3x2%2522%252C%2522sizes%2522%253A%255B68.00747198007471%252C31.992528019925288%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvz4z0rb00033b6l24pw46jc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvz4z0rb00053b6l3d74q8l9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvz4z0rb00063b6lr9hn0ahd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvz4z0rb00033b6l24pw46jc%2522%253A%257B%2522id%2522%253A%2522clvz4z0rb00033b6l24pw46jc%2522%252C%2522activeTabId%2522%253A%2522clvzaqv7k04cu3b6jjfpdqn01%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvz4z0rb00023b6lyo24302d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A39%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A39%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Flib%252Futils.ts%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2876%252C%2522endLineNumber%2522%253A2876%252C%2522startColumn%2522%253A0%252C%2522endColumn%2522%253A0%257D%255D%252C%2522id%2522%253A%2522clvzaqv7k04cu3b6jjfpdqn01%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clvz4z0rb00063b6lr9hn0ahd%2522%253A%257B%2522id%2522%253A%2522clvz4z0rb00063b6lr9hn0ahd%2522%252C%2522activeTabId%2522%253A%2522clvz51xf700ab3b6jhnuxlw0q%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clvz51xf700ab3b6jhnuxlw0q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clvz4z0rb00053b6l3d74q8l9%2522%253A%257B%2522id%2522%253A%2522clvz4z0rb00053b6l3d74q8l9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvz4z0rb00043b6ly2g4tp49%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clvz4z0rb00043b6ly2g4tp49%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

To reproduce, you need to first click one of the buttons to remove the visibility of one series and then click some bubbles and start doing resizing, it crashes random...

here a video (I have the video with more quality but github doesn't allow me to update it, hope it's enough):

https://github.com/highcharts/highcharts/assets/30524396/da121bc2-4530-4925-9697-7d6b2f8ab79c

#### Product version
Highcharts

#### Affected browser(s)

Chrome Version 124.0.6367.156 (Official Build) (arm64)

**Comment by hubertkozik** [comment]
Hi @jordibaliellas! The console errors are related to your project's wrong configuration. I don't see any bugs there. You are using _useEffect_ hook, which is triggered when the series is changed, and by clicking you change the series and trigger the _useEffect_ hook. You can see, that if you comment out the part of the code with click event: https://codesandbox.io/p/devbox/naughty-frog-8nmm95?file=%2Fapp%2Fhooks%2Fbubble.hook.tsx%3A31%2C47&workspaceId=07b5692a-7c9d-48a7-b810-62e1833b90d4 everything is working correctly.

**Comment by jordibaliellas** [comment]
@hubertkozik hi, the link isn't working not sure if it's shared properly. 

What do you mean by commenting the code? I want to keep the functionality about clicking bubbles it generates new data, what's the problem with that?

thank you!

**Comment by jordi-baliellas-moodys** [comment]
Here is another video reproducing the error, there is no logic in the application, just updating the chartOptions status as the documentation recommends. Can this ticket be reopened? Thanks.


https://github.com/highcharts/highcharts/assets/136327523/2d856d8e-104e-4ce0-a94d-07cfb2747476

**Comment by hubertkozik** [comment]
You've set in `useEffect` as a second argument `series` variable, so after clicking and updating the chart you are firing the `setChartOptions` state method again. Also, you should pass only options, which you want to update via set state method. To toggle series visibility it is better to use a native `setVisible` method: https://api.highcharts.com/class-reference/Highcharts.Series#setVisible

Feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
