### ISSUE TITLE
[Cooperation] Introduction of VTable - Collaboration Opportunity #19894

### ISSUE THREAD

**Issue by fangsmile** [highcharts/highcharts#21147]
Hello,

I am the developer behind the [vtable](https://visactor.io/vtable) table component. We have observed the exceptional performance of Highcharts in the field of data visualization and believe that vtable could bring the following clear benefits to your platform:

  Enhanced Data Presentation: vtable could offer advanced data grid functionalities to complement Highcharts' capabilities.
  Improved User Experience: Integration with vtable could provide users with a smoother and more interactive experience when working with data.
  Broadened User Reach: A collaboration could help both parties to attract a larger audience interested in data visualization and analysis.

We are interested in discussing how these benefits could be realized and how we might find a mutually beneficial way to collaborate.

Please let us know if you are interested and when you might be available for further discussion.

Thank you for your time and consideration.

**Comment by hubertkozik** [comment]
We use GitHub as a tool for bugs/feature request tracking and your question is not related to this topic. If you will need help with Highcharts configuration feel free to reach out to our [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
