### ISSUE TITLE
Chart doesn't render properly when the height is very large

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#21165]
#### Expected behaviour

Should work as in case of lower height.

#### Actual behaviour

Points & yAxis stop rendering at some point.

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/uo9dnebs/

![Zrzut ekranu 2024-05-15 o 11 22 09](https://github.com/highcharts/highcharts/assets/38281922/2f3c0111-0cf6-4945-a606-8a9daf033521)

**Comment by oysteinmoseng** [comment]
Looks like the axis label positions are capped at 100000, probably some logic somewhere to keep it within a "reasonable" range.

https://github.com/highcharts/highcharts/blob/d880fe762df5434442bf4a3da2ca8f331b9edce9/ts/Core/Axis/Tick.ts#L497
https://github.com/highcharts/highcharts/blob/b1fcbf788c63f655cb29d1e7f872a353edb1aaf1/ts/Core/Axis/Axis.ts#L1043
https://github.com/highcharts/highcharts/blob/b1fcbf788c63f655cb29d1e7f872a353edb1aaf1/ts/Core/Series/Series.ts#L2157

Can probably just increase the value to `1e8` or `1e9` without any issues, but let's test.
