### ISSUE TITLE
[Bar chart]: Second x-axis has some width issue, although it has the same gridLineWidth

### ISSUE THREAD

**Issue by niralivasoya** [highcharts/highcharts#21164]
#### Expected behaviour
All x-axis should be the same width.

#### Actual behaviour
For some reason, only the second x-axis grid line looks different, looks like it is thicker than other grid lines

#### Live demo with steps to reproduce
This is my options code:
```
import Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import { useMemo } from 'react';

const HorizontalStackedBarChart = () => {
    const options = useMemo(() => {
        return {
            chart: {
                type: 'bar',
            },
            credits: {
                enabled: false,
            },
            xAxis: {
                categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                credits: {
                    enabled: false,
                },
                labels: {
                    style: {
                        color: 'pink',
                    },
                },
                gridLineWidth: 1, // Set grid line width for all x-axes
                gridLineColor: '#EEEEED',
            },
            yAxis: {
                title: {
                    text: '', // This hides the title for the y-axis
                },
                gridLineWidth: 1,
                gridLineColor: '#EEEEED',
            },
            title: {
                text: 'Building Recovery (tonne)',
                margin: 30,
                style: {
                    fontSize: '14px',
                    color: '#5D5C56',
                    fontWeight: 600,
                },
                align: 'left',
            },
            legend: {
                reversed: true,
                itemStyle: {
                    color: '#3E3D39',
                    fontWeight: 600,
                },
                itemDistance: 5,
                align: 'left',
                itemWidth: 160,
            },
            plotOptions: {
                series: {
                    stacking: 'normal',
                    dataLabels: {
                        enabled: false,
                    },
                },
            },
            series: [
                {
                    data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
                },
            ],
        };
    }, []);

    return (
        <div>
            <HighchartsReact highcharts={Highcharts} options={options} />
        </div>
    );
};

export default HorizontalStackedBarChart;
```

It generates this result. Even though I set the same gridLineWidth for all x-axis, the second line looks a bit thicker than others.

<img width="649" alt="image" src="https://github.com/highcharts/highcharts/assets/32123446/012b031c-9025-4423-9915-d535658d2744">

#### Product version
Current Highcharts version:

<img width="291" alt="image" src="https://github.com/highcharts/highcharts/assets/32123446/7eb41dc2-abd4-4b99-92ce-b57e3075ff7e">

#### Affected browser(s)
I am using Chrome and Brave browsers. 

Can somebody please help me fix this issue? Thanks.

**Comment by bm64** [comment]
Hello @niralivasoya 

I tried to recreate the issue on my end with the same Highcharts version but everything seems to work correctly in Chrome. Could you check if the issue occurs in [this demo](https://stackblitz.com/edit/react-o2mjtw?file=index.js,package.json,style.css)? If it doesn't occur, the issue is most likely caused by changes in your project, perhaps related to CSS or other custom configurations.

**Comment by niralivasoya** [comment]
@bm64 Thank you for your response. Strangely, I have used the same code with the same configurations. what could be the possible causes for this behaviour?

**Comment by bm64** [comment]
@niralivasoya

Sorry for the late response. As I mentioned, I'd check for CSS rules that could impact the chart. Without a reproduction, I can't identify the cause. If the issue occurs in your project could you create a simplified version of the project on GitHub for debugging?

**Comment by niralivasoya** [comment]
@bm64 I debugged on my side, added customized CSS and fixed this issue. Thanks for your support and all your help. I appreciate it. 👍🏻
