### ISSUE TITLE
Packedbubble: Can't update data if series is hidden

### ISSUE THREAD

**Issue by K009** [highcharts/highcharts#21177]
#### Expected behaviour
Error shouldn't pop up.

#### Actual behaviour
We got an error in the console: `TypeError: Cannot read properties of undefined (reading 'layout')`

#### Live demo with steps to reproduce
1. Click legend item
2. Click twice update data button
3. Check your console to find the error

https://jsfiddle.net/BlackLabel/cbwhsj1e/

#### Product version
11.4.1

**Comment by bm64** [comment]
_Internal note:_
Used to work correctly in v10.3.3 and has been broken since v11.
Bisected to: 8debba7ad1762325a815d44ba9633456bb3e4f09

**Comment by MarkusBarstad** [comment]
Supplied demo works in chrome and firefox here 🤔
