### ISSUE TITLE
Incorrect months label for last days of month

### ISSUE THREAD

**Issue by whscullin** [highcharts/highcharts#21191]
#### Expected behaviour

When the data is a series of dates, one day from each month, the month label should reflect the month of the date.

#### Actual behaviour

If the day from each month is the last day of the month, the month label shows the value of the subsequent month. For instance

```
data: [
        { x: new Date('01-31-2024'), y: 6.4},
        { x: new Date('02-29-2024'), y: 6.3},
        { x: new Date('03-31-2024'), y: 5.4},
        { x: new Date('04-30-2024'), y: 4.4},
      ],
```

Produces

![image](https://github.com/highcharts/highcharts/assets/2958002/1ef7b87e-5dbb-4f55-bed8-559eac3f7e30)

01-31-2024 is labeled "February", 04-30-2024 is labeled May.

#### Live demo with steps to reproduce
[https://jsfiddle.net/mae1phb0/](https://jsfiddle.net/mae1phb0/)

#### Product version

Highcharts 11.4.1

#### Affected browser(s)

All

**Comment by bm64** [comment]
Hi @whscullin 

Our support team has already addressed the issue on freshdesk support channel. Please avoid creating duplicated and continue the discussion there.
