### ISSUE TITLE
Issue with updating stacking order using series[i].update({index:0})

### ISSUE THREAD

**Issue by mikegodber** [highcharts/highcharts#2119]
You can see this issue here: http://jsfiddle.net/TEZCp/1/

I want to be able to allow users to control the stacking order of the graph elements. I have found a way to do this using the series.update() method passing in a new index.

This works nicely in most cases but if you try to set any of the series elements to the zero index it moves them to position 1 instead. Subsequent moves will then go to index 2, then index 3, etc

Thanks for your help

Mike

**Comment by oysteinmoseng** [comment]
This appears to still be relevant with current code.
