### ISSUE TITLE
Unable to run eslint for Dashboards

### ISSUE THREAD

**Issue by jomar-honsi** [highcharts/highcharts#21199]
#### Expected behaviour
The pre-commit hook executes _eslint_ on `ts/Dashboards` or `ts/Datagrid`

#### Actual behaviour
The pre-commit hooks exits with the following error message:

#### Steps to reproduce

- Make a minor modification to any of the files in `ts/Dashboards` or or `ts/Datagrid`
- Observe the following error message:

`cd ts/Dashboards && npx eslint:
The filename, directory name, or volume label syntax is incorrect.
husky - pre-commit hook exited with code 1 (error)
`
Preliminary investigations reveal that the issue is the command 'cd ts/Dashboards', as defined in the file 'package.json', lines 138 to 143.

>     "./ts/Dashboards/**/*.ts": [
>       "cd ts/Dashboards && npx eslint"
>     ],
>     "./ts/DataGrid/**/*.ts": [
>       "cd ts/DataGrid && npx eslint"
>     ]

The issue seems to be limited to the Windows development platform and the implementation of Git bash:
 `GNU bash, version 5.2.21(1)-release (x86_64-pc-msys)
`

**Comment by karolkolodziej** [comment]
_Internal note:_
Only visible on Windows.

**Comment by karolkolodziej** [comment]
Closing for now as it only effects specific Windows.
