### ISSUE TITLE
There is an issue with `tickmarkOffset` and rendering code for axis tickmarks

### ISSUE THREAD

**Issue by magnusanderson-wk** [highcharts/highcharts#21207]
#### Expected behaviour
```
    /**
     * Put everything in place (note this is shitty documentation also)
     *
     * @private
     * @param {number} index
     *
     * @param {boolean} [old]
     * Use old coordinates to prepare an animation into new position
     *
     * @param {number} [opacity]
     */
    render(index, old, opacity) {
      const tick = this, axis = tick.axis, horiz = axis.horiz, pos = tick.pos, tickmarkOffset = pick11(tick.tickmarkOffset, axis.tickmarkOffset), xy = tick.getPosition(horiz, pos, tickmarkOffset, old), x = xy.x, y = xy.y, axisStart = axis.pos, axisEnd = axisStart + axis.len, reverseCrisp = horiz && x === axisEnd || !horiz && y === axisStart ? -1 : 1, pxPos = horiz ? x : y;

      // NEW CODE HERE ———————————————————————————————————————
      let labelOpacity = pick11(
        opacity,
        tick.label && tick.label.newOpacity,
        // #15528
        1
      );
      let labelxy = tick.getPosition(horiz, pos, 0, old), labelX = xy.x, labelY = xy.y;
      let labelPos = correctFloat2(horiz ? labelX : labelY);
      if (!axis.chart.polar && tick.isNew && (labelPos < axisStart || labelPos - tickmarkOffset > axisEnd)) {
        labelOpacity = 0;
      }
      // END NEW CODE ———————————————————————————————————————

      if (!axis.chart.polar && tick.isNew && (correctFloat2(pxPos) < axisStart || pxPos - tickmarkOffset > axisEnd)) {
        opacity = 0;
      }
      opacity = pick11(opacity, 1);
      this.isActive = true;
      this.renderGridLine(old, opacity, reverseCrisp);
      this.renderMark(xy, opacity, reverseCrisp);
      this.renderLabel(xy, old, labelOpacity, index);
      tick.isNew = false;
      fireEvent4(this, "afterRender");
    }
```

#### Actual behaviour
```
    /**
     * Put everything in place
     *
     * @private
     * @param {number} index
     *
     * @param {boolean} [old]
     * Use old coordinates to prepare an animation into new position
     *
     * @param {number} [opacity]
     */
    render(index, old, opacity) {
      const tick = this, axis = tick.axis, horiz = axis.horiz, pos = tick.pos, tickmarkOffset = pick11(tick.tickmarkOffset, axis.tickmarkOffset), xy = tick.getPosition(horiz, pos, tickmarkOffset, old), x = xy.x, y = xy.y, axisStart = axis.pos, axisEnd = axisStart + axis.len, reverseCrisp = horiz && x === axisEnd || !horiz && y === axisStart ? -1 : 1, pxPos = horiz ? x : y;
      if (!axis.chart.polar && tick.isNew && (correctFloat2(pxPos) < axisStart || pxPos - tickmarkOffset > axisEnd)) {
        // opacity = 0;
      }
      const labelOpacity = pick11(
        opacity,
        tick.label && tick.label.newOpacity,
        // #15528
        1
      );
      opacity = pick11(opacity, 1);
      this.isActive = true;
      this.renderGridLine(old, opacity, reverseCrisp);
      this.renderMark(xy, opacity, reverseCrisp);
      this.renderLabel(xy, old, labelOpacity, index);
      tick.isNew = false;
      fireEvent4(this, "afterRender");
    }
```

I think this was introduced in a recent version, we are investigating an upgrade from 11.1 to 11.4 and the final label when using a tickmarkOffset (due to `tickmarkPlacement === 'between'`) is not rendered.

**Comment by magnusanderson-wk** [comment]
Another strange thing going on here is that `correctFloat` is called sometimes but not always on `pxPos`

**Comment by magnusanderson-wk** [comment]
Our build system messes up some function names, but I'm sure you can understand what is happening. This is rendering axis ticks

**Comment by magnusanderson-wk** [comment]
Note that this given code preserves behavior of choosing a passed-in opacity as the label opacity over anything else except if the label is off-screen (currently, if the tick is off-screen it will make the label invisible even if the label should be visible)

So if you restructure things, think about what you're doing I guess

**Comment by hubertkozik** [comment]
Hi @magnusanderson-wk. I am not sure what is not working on your side. Can you prepare a simple demo with the reproduced issue in an online editor that I could work on? You can start here: https://jsfiddle.net/BlackLabel/nyvmjzou/

**Comment by magnusanderson-wk** [comment]
https://jsfiddle.net/magnusandersonwk/rqnz3j9u/12/

**Comment by magnusanderson-wk** [comment]
Compare to 11.1 which has its own issues: https://jsfiddle.net/magnusandersonwk/rqnz3j9u/13/

The code above addresses those I think, though (as it improves a bugfix between 11.1 and 11.4)

**Comment by hubertkozik** [comment]
All of the x-axis labels are visible in your demos: 
<img width="882" alt="image" src="https://github.com/highcharts/highcharts/assets/62724907/e8ae3560-fb14-48c4-a092-4c4c08279a95">
Can you say and maybe create an image or gif of what is exactly wrong in the demo you have provided?

**Comment by magnusanderson-wk** [comment]
1. Notice that in current highcharts, the y axis label `Dec` does not render: https://jsfiddle.net/magnusandersonwk/rqnz3j9u/12/
2. Notice that in highcharts 11.1, that label did render: https://jsfiddle.net/magnusandersonwk/rqnz3j9u/13/
3. Notice that in highcharts 11.1, below `Dec` there is an extra axis tick rendering which is a bug
4. Notice that in current highcharts, that tick is not present because it was fixed
5. Notice that with the provided code, both bugs are fixed: https://jsfiddle.net/magnusandersonwk/rqnz3j9u/19/

I will admit I made some error copying my fix into this github issue, as I ran into trouble setting up step 5 for you. So use the code in that jsfiddle

**Comment by hubertkozik** [comment]
@magnusanderson-wk the issue you are facing is related to `min`/`max` values, which you set on x-axis. You are using categories, and you set those values and decimals, the correct usage in this case is to use integer value, like here: https://jsfiddle.net/BlackLabel/jw1t8L3s/ and everything will work correctly. I don't see any bug here, it looks to me, like a misconfiguration.

**Comment by magnusanderson-wk** [comment]
I don't see the point of this not being changed? While it might be the case that it is a strange use case, it makes more sense with an area chart which is the reason we implemented this behavior in the first case: https://jsfiddle.net/magnusandersonwk/rqnz3j9u/21/

We are currently stuck supporting this and will have to maintain this change ourselves if not merged upstream. That in itself is not a great reason to merge this, but if you just read the code, it does seem like the code doesn't work as intended because it is hiding an in-bounds label for a tickmark that is out of bounds, with the label in-bounds.

There is nothing in the documentation that suggests that min/max should be integers on x-axis. In fact, [it sounds like it can be decimal](https://api.highcharts.com/highcharts/xAxis.min) because there is mention of rounding it down.
