### ISSUE TITLE
Offline PDF Export: Fails on sunburst

### ISSUE THREAD

**Issue by mdnpascual** [highcharts/highcharts#21205]
#### Expected behaviour

Receive a PDF download

#### Actual behaviour

No PDF Download and an error appears: 
```Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.```

#### Live demo with steps to reproduce
https://jsfiddle.net/vndtqshr/1/

#### Product version
Highcharts 11.4.2

#### Affected browser(s)
Chrome 124.0.6367.210
Edge 125.0.2535.51

**Comment by karolkolodziej** [comment]
Hi @mdnpascual!
Thank you for reporting the issue! 

Internal note:
[Simplified demo](https://jsfiddle.net/BlackLabel/4oyq1j2h/)
Introduced with: https://github.com/highcharts/highcharts/pull/19131
