### ISSUE TITLE
Shifting Chart without loosing points

### ISSUE THREAD

**Issue by Charissima** [highcharts/highcharts#2121]
I want to shift a chart in another way than addPoint does. You can see what I mean in my JSFIDDLE: http://jsfiddle.net/Charissima/TEEdw/3/ 
When the chart has filled the container and the next point is added, it shifts to the left without loosing the first point.

It works fine, but sometimes I can see the chart swapping a little bit. And even worth: when running over a longer time the chart gets lost. It still works, you can see it shifting and updating y in the upper right corner, but the chart is not visible any more. Even the navigator is empty.

So my question is: Is there a better and smarter way to shift the chart this way?

**Comment by KacperMadej** [comment]
Unable to recreate using version 6.1.4.
Closing as resolved.
If you would like to see this issue reopened please add more info in a comment below.
