### ISSUE TITLE
Multiple resize axis demo seems incorrect

### ISSUE THREAD

**Issue by royalone** [highcharts/highcharts#21220]
The [One resizer controlling multiple axes](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/yaxis/resize-multiple-axes) demo linked in the docs at [highstock/yAxis.resize.controlledAxis](https://api.highcharts.com/highstock/yAxis.resize.controlledAxis) seems broken to me.

#### Expected behaviour
Dragging the axis resizer will grow/shrink the panes, keeping AAPL & CCI on the top, and RSI & ATR on the bottom

#### Actual behaviour
AAPL seems to become detached and falls down below with the bottom panes 

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/yaxis/resize-multiple-axes

#### Product version
currently seems to be 
- Highstock JS v11.4.3
- Drag-panes module v11.4.3

#### Affected browser(s)
Edge Version 125.0.2535.51 (Official build) (64-bit)

**Comment by bm64** [comment]
Hi @royalone and thanks for reporting

It used to work correctly in v11.1.0 and has been broken since v11.2.0: https://jsfiddle.net/BlackLabel/g92mw7hd/
The issue can be recreated without Highcharts Stock.

_Internal note:_
Unable to bisect

**Comment by MSturges** [comment]
Any updates?

**Comment by hubertkozik** [comment]
@MSturges The ticket is prioritized at the top of our backlog. The work should start soon :)
