### ISSUE TITLE
Heatmap with datetime axis does not render

### ISSUE THREAD

**Issue by MarkusBarstad** [highcharts/highcharts#21224]
#### Expected behaviour
Datetime axis should work with the heatmap

#### Actual behaviour
When using datetime axis, the heatmap will not render

#### Live demo with steps to reproduce
https://jsfiddle.net/Lg67qv0n/11/

#### Product version
Highcharts v11.4.3

#### Affected browser(s)
Chrome, Firefox

**Comment by hubertkozik** [comment]
The provided demo with steps to reproduce is wrongly configured. If you want to use heatmap with _datetime_ axis and the data should start from a specific date point you should set `colsize` and add a third value to the data object, like in this demo: https://jsfiddle.net/BlackLabel/awcunkhf/
**API Reference:** https://api.highcharts.com/highcharts/series.heatmap.colsize

If you don't want to start from specific date point you can remove x value from data object and set a desired _pointStart_ value: https://jsfiddle.net/BlackLabel/37u4r8sL/
**API Reference:** https://api.highcharts.com/highcharts/series.heatmap.data
