### ISSUE TITLE
Docs: Update links to Google API to v4

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#21236]
#### Expected behaviour
References to v3 should be replaced with URL to docs in v4, for example, visit: https://api.highcharts.com/dashboards/typedoc/interfaces/Data_Connectors_GoogleSheetsConnectorOptions.GoogleSheetsConnectorOptions-1.html and find `The key for a Google Spreadsheet to load. See [general information on GS](https://developers.google.com/gdata/samples/spreadsheet_sample).` - 

#### Actual behaviour
We are redirecting users to old API. It could be more pleasant experience to be redirected to the right place, instead of searching on my own.

#### Product version
Highcharts Dashboards

**Comment by jedrzejruta** [comment]
@pawelfus From what I see in the @jomar-honsi has updated the docs with a link to the general Google Sheets [overview](https://developers.google.com/sheets/api/guides/concepts).

In my opinion it still doesn't point the user to where the API key can be found. I'd suggest either adding a link to the 3rd party guide, that's already included on Highcharts data module [API](https://api.highcharts.com/highcharts/data.googleAPIKey) or direct link to a less-general URL on Google's [documentation](https://developers.google.com/sheets/api/quickstart/js#create_an_api_key).

**Comment by ddragula** [comment]
>or direct link to a less-general URL on Google's [documentation](https://developers.google.com/sheets/api/quickstart/js#create_an_api_key).

Let's do it, @jedrzejruta. 😄
