### ISSUE TITLE
Boxplot with two data series is NOT rendered correctly

### ISSUE THREAD

**Issue by janjurca** [highcharts/highcharts#21245]
#### Expected behaviour
Expected to render two boxplots next to each other.

#### Actual behaviour
Boxplots are rendered disjointed frome their min/max parts and one over the other

#### Live demo with steps to reproduce
https://jsfiddle.net/Lzwovy7q/

#### Product version
Last NOT affected version is 11.4.0, present since then

#### Affected browser(s)
Chrome, Firefox, Safary (others not tested)

**Comment by hubertkozik** [comment]
Thank you for reporting the bug.

_Internal note:_
Bisected to 87ae3b30c71846cb11550897a8856491d1834d5d.
