### ISSUE TITLE
Highcharts Standalone Navigator height property is not working properly

### ISSUE THREAD

**Issue by ducolares** [highcharts/highcharts#21268]
#### Expected behaviour
Standalone navigator height property to change the size of navigator.

#### Actual behaviour
When setting the standalone navigator height for a value higher then 70px, the navigator partially hidden.

#### Live demo with steps to reproduce

https://codepen.io/ducolares/pen/zYQwNdW 

#### Product version

 Highcharts JS v11.4.3 (2024-05-22)
 Standalone navigator module

#### Affected browser(s)
Chrome

**Comment by bm64** [comment]
Hello @ducolares and thanks for reporting the issue.
