### ISSUE TITLE
Dashboards to use 'additive' option for RangeModifier

### ISSUE THREAD

**Issue by jomar-honsi** [highcharts/highcharts#21286]
#### Expected behaviour

DataGrid with RangeModifier to work with default range modifier options.

#### Actual behaviour

Rows disappear from the table when editing a cell. 

#### Problem description

When a range modfier is used with Dashboards the issue is solved by adding the option `additive: true`. To judge by the unit tests for DataTable with RangeModifier this seems to be expected.

#### Suggested solution
Dashboards to use `additive: true` by default.

#### Product version
Dashboards v 2.1

**Comment by jomar-honsi** [comment]
The benefit is minimal. Suggest we drop it.

**Comment by karolkolodziej** [comment]
Let's close this for now until the issue resurfaces again.
