### ISSUE TITLE
`tooltip.split` causes tooltip to animate from upper left corner when hovering line series, then scatter series

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#21281]
#### Expected behaviour
No animation or animation from the previous position

#### Actual behaviour
Unnecessary/wrong animation of the tooltip when moving from line series to scatter series
![tooltip](https://github.com/highcharts/highcharts/assets/1453926/a6a411d8-9a5c-448f-839f-11a7e9f45dad)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/c2u0687o/

#### Product version
Highcharts 11.4.2+, v11.4.1 works fine, demo: https://jsfiddle.net/BlackLabel/c2u0687o/2/ - needs a bisect

**Comment by hubertkozik** [comment]
I can reproduce this problem even in Highcharts v9.3.0 but only the first time of tooltip renders: https://jsfiddle.net/BlackLabel/ns859h2w/
![tooltip_anim_bug](https://github.com/highcharts/highcharts/assets/62724907/da978209-065e-41d1-b141-05bf09d55f4c)

So it looks to me, that the last working version is Highcharts v9.2.2.

**Comment by pawelfus** [comment]
It seems it depends on which series you start hovering. If you hover the scatter series first, then it's a regression from v11.4.2. The hovering line series first causes the error to be visible since v9.3.0+. Indeed, nice catch!
