### ISSUE TITLE
Typescript defination for tooltip is incorrect in v11.4

### ISSUE THREAD

**Issue by LearnGrowAndShare** [highcharts/highcharts#21302]
#### Expected behaviour

export class Tooltip {
    /**
     * Tooltip of a chart.  
     *
     * @param chart
     *        The chart instance.
     *
     * @param options
     *        Tooltip options.
     */
    constructor(chart: Chart, options: TooltipOptions,         pointer: Pointer);

As the code present at https://github.com/highcharts/highcharts/blob/v11.4.3/ts/Core/Tooltip.ts#L134, 
It should have 3 parameter in it.

#### Actual behaviour

The actual code has 3 parameter in constructor whereas the type defination for tooltip have only 2 paramter, which blocks the new / duplicate object creation for tooltip.

export class Tooltip {
    /**
     * Tooltip of a chart.  
     *
     * @param chart
     *        The chart instance.
     *
     * @param options
     *        Tooltip options.
     */
    **constructor(chart: Chart, options: TooltipOptions);**

![image](https://github.com/highcharts/highcharts/assets/12616063/aa0497ac-8f85-4c6a-ba97-90272d0d4de7)
 

#### Product version
11.4.3

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
Hi @LearnGrowAndShare! 
You are right thank you for pointing that out.

A description of the third argument is needed here: 
https://github.com/highcharts/highcharts/blob/a471046711cd4eecc598888c392c33a7b925efed/ts/Core/Tooltip.ts#L114-L125

**Comment by LearnGrowAndShare** [comment]
Is there any plan for the release for this.. as a work around i have added post install script to fix this..
