### ISSUE TITLE
Reversed xAxis doesn't work when chart is inverted

### ISSUE THREAD

**Issue by magdalena-gut** [highcharts/highcharts#21308]
#### Actual behavior
The xAxis is not reversed when the chart is set to inverted. The yAxis works correctly.

#### Demos:
Chart not inverted & xAxis reversed (Months are from Dec to Jan):
[link](https://jsfiddle.net/BlackLabel/wm4d3k1o/)

Chart inverted & xAxis reversed (Months should also be from Dec to Jan but are not):
[link](https://jsfiddle.net/BlackLabel/5oavzpwe/)

#### Product version
v11.4.3

**Comment by karolkolodziej** [comment]
When the chart is `inverted` and xAxis `reversed` the order of the labels on the axis stays the same which is true.
But as you can see on the chart the series is reversed so the value for `Dec` is `54.4` for both of them.
Is that right?

**Comment by energizerHim** [comment]
It would be better to review the code more carefully and test it step by step.
