### ISSUE TITLE
How to add some custom buttons and elements above the chart in fullscreen mode? 

### ISSUE THREAD

**Issue by alirezameftahi71** [highcharts/highcharts#21312]
How to add some custom buttons and elements above the chart in fullscreen mode? 
I have a div, that has buttons, select menus and etc above my chart. These controls interact with the chart. I want to have this div-bar at the top of the chart even on fullscreen mode. 
Is there any way?

**Comment by karolkolodziej** [comment]
Hi @alirezameftahi71! 

Please refer to[ the StackOverflow question.](https://stackoverflow.com/questions/70902811/highcharts-custom-button-styling-off-on-full-screen)

We use GitHub for bug/feature tracking-  so if you have questions like this, please get in touch with [our support team.](https://www.highcharts.com/blog/support/)

**Comment by alirezameftahi71** [comment]
@karolkolodziej Created the post on SO
https://stackoverflow.com/questions/78620290/how-to-add-a-fully-custom-html-section-to-the-fullscreen-mode-of-highcharts
