### ISSUE TITLE
When panning, the reset zoom button appears

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#21319]
#### Expected behaviour
When panning, the reset zoom button appears.

#### Actual behaviour
Only when and `ordinal` is disabled. 
The reset zoom button should not be visible when panning.
![image](https://github.com/highcharts/highcharts/assets/57004120/4710279d-0a9f-4d11-975b-c262d9296a7b)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/n4g37veh/
1. Zoom with scroll
2. Pan

#### Product version
Regression was introduced in version 11.4.0. 
Unable to bisect.

#### Affected browser(s)
All

**Comment by kamil-musialowski** [comment]
Most likely caused by this refactor: https://github.com/highcharts/highcharts/pull/20077
Precisely, by changes in `Chart.ts`
