### ISSUE TITLE
A shadow appears when hover an inverted bubble

### ISSUE THREAD

**Issue by YanSatsuk** [highcharts/highcharts#21315]
![image](https://github.com/highcharts/highcharts/assets/5408782/c9e4a185-29d1-476e-aed8-bd84f5534cd7)

https://jsfiddle.net/8dn3cxoq/

Highcharts JS v11.4.3

**Comment by bm64** [comment]
Hello @YanSatsuk and thanks for reporting.

It used to work correctly back in v10.3.2: https://jsfiddle.net/BlackLabel/8rpf4zhk/

Most likely broken by https://github.com/highcharts/highcharts/commit/eded2848bc7dee832333e38e7d770accd28ae711 and related to https://github.com/highcharts/highcharts/issues/21125, https://github.com/highcharts/highcharts/pull/21162
