### ISSUE TITLE
Polar charts not generating on Vue

### ISSUE THREAD

**Issue by KevinMMontalvo** [highcharts/highcharts#21318]
#### Expected behaviour
![Screenshot_7](https://github.com/highcharts/highcharts/assets/23621563/8c9e9d98-f7be-4d2f-870a-a1f893f3020b)

#### Actual behaviour
![Screenshot_6](https://github.com/highcharts/highcharts/assets/23621563/c16a52ff-520c-4885-a0c8-e72318c88d25)

#### Live demo with steps to reproduce
[[](https://jsfiddle.net/k4bLmg6d/10/)](https://jsfiddle.net/k4bLmg6d/10/)

#### Product version
"highcharts": "11.4.0",
"highcharts-vue": "2.0.1",
"vue": "3.4.27"

**Comment by karolkolodziej** [comment]
Hi @KevinMMontalvo!

The polar series is not part of the main highcharts bundle. To make it work please import the `highcharts-more` module.
```html
<script src="https://code.highcharts.com/highcharts-more.js"></script>
````

[Demo](https://jsfiddle.net/BlackLabel/5p213s4m/)

**Comment by KevinMMontalvo** [comment]
For another person who want to implement Highcharts more into Vue 3 CLI project 

you should setup like this

```
import VueHighcharts from 'highcharts-vue';
import Highcharts from 'highcharts/highcharts';
import HighchartsMore  from 'highcharts/highcharts-more';

HighchartsMore(Highcharts)
app.use(VueHighcharts, {Highcharts});
```

on template like this

`<highcharts :options="chartOptions"></highcharts>`
