### ISSUE TITLE
Live data updates prevents panning the chart and affects zoom

### ISSUE THREAD

**Issue by KseniaD0x0** [highcharts/highcharts#21316]
#### Expected behaviour
Live data updates do not change behavior for zoom in/out and pan with drag. Chart can be dragged to see past data. Zoom with mouse wheel works consistently.

#### Actual behaviour
When updating bar is within the currently viewed data zoom cycles and pan does not work. Attaching the video with issue shown along with the fiddle (which is basically live data demo). At first half of the video I am trying to drag the chart around, but it is not moving when updating data is within the view. At the second half I am constantly zooming out and zoom just cycles.

#### Live demo with steps to reproduce
[Fiddle](https://jsfiddle.net/stealkvas/p3x5hnyj/1/)

#### Product version
Highstock 11.4.0

#### Affected browser(s)
Tested in Edge, Chrome (latest).

https://github.com/highcharts/highcharts/assets/172513211/5e2e6cce-ff4b-4a01-944c-747fd8ef50a4

**Comment by bm64** [comment]
Hi @KseniaD0x0 and thanks for reporting the issue.

Looks like it used to work correctly back in v7: https://jsfiddle.net/BlackLabel/cr8mwyuf/

**Comment by KseniaD0x0** [comment]
Seems like working better, but still when panning for a short distance (especially when dragging from the part where last bar is), the chart is shaking and not moving.

**Comment by kamil-musialowski** [comment]
Minimal demo: https://jsfiddle.net/BlackLabel/bhp4ck5w/

Workaround: set `xAxis.ordinal` to false or remove the `xAxis.overscroll` https://jsfiddle.net/BlackLabel/u63q9wsv/

**Comment by KseniaD0x0** [comment]
Disabling ordinal for xAxis cannot be used as workaround in our case. 
How to substitute overscroll behavior? So that it would be possible to pan into the future?
