### ISSUE TITLE
Pie chart overlapping and crossing labels

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#21336]
#### Expected behaviour
Labels should never overlap, connectors should never cross

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/jk63cm1w/

#### Product version
v11.4.3

![Skjermbilde 2024-06-17 kl  13 46 17](https://github.com/highcharts/highcharts/assets/227836/eff5751f-0b05-4be6-850d-370d6539954d)

**Comment by hubertkozik** [comment]
Looks like a regression between v10.3.3 and v11.0.0. Works correctly in v10.3.3: https://jsfiddle.net/BlackLabel/4m0hd8wn/

_Internal note:_
Bisected to 5beefb15e44d60b1078d4ae5af98d51c5c6b600b.

**Comment by TorsteinHonsi** [comment]
@hubertkozik The overlapping did not occur in v10.3.3, but the labels were still crossing. So at least partly this issue is older.
