### ISSUE TITLE
Can't create a draggable Gantt Chart using Vue2

### ISSUE THREAD

**Issue by Kyvex** [highcharts/highcharts#21351]
#### Expected behaviour
I'm wanting to create a Gantt Chart that has draggable values so I can position them at different times throughout the day.

#### Actual behaviour
For some reason when I add the `dragDrop` object to the `plotOptions` I get no drag capability at all.

#### Product version
HighCharts 9.2.1 through NPM

#### Affected browser(s)
Chrome, Firefox, Safari

**Comment by hubertkozik** [comment]
Hi @Kyvex! I've created a demo in Vue2 and draggable points in Highcharts Gantt: https://codesandbox.io/p/sandbox/bold-johnson-wwg37p

As you can see, everything is working correctly. If you need help with the Highcharts configuration you feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
