### ISSUE TITLE
AngularJs Dynamic creating charts style undefined

### ISSUE THREAD

**Issue by raff77** [highcharts/highcharts#2138]
Ln 341 of highstock.src.js 

Error: Uncaught TypeError: Cannot read property 'style' of undefined

Element is undefined as Highcharts is initialised before the the click up action propagated through the dom. It appears to add a mouse up action onto the document which iterates over a hash of elements, which can be undefined. A test should be added here is element is undefined or an alternative found.

Adding a one millisecond timeout to my code to fixed it but not ideal. Stopping the event bubbling did not fix it.

**Comment by jon-a-nygaard** [comment]
Closing this issue due to: We are not able to reproduce it, please provide a live demo of the issue. To do this you can use [JSFiddle](https://jsfiddle.net)

Should anyone have further information on this issue, please add a comment and reopen.
