### ISSUE TITLE
Series.data.slice + Series.setData to remove datapoints breaks chart

### ISSUE THREAD

**Issue by tordvv** [highcharts/highcharts#21396]
I have found a bug where when using series.data.slice in combination with series.setdata to remove datapoints from a series, the chart breaks.

Chart with points:
![Screenshot 2024-06-25 at 09 46 28](https://github.com/highcharts/highcharts/assets/49265903/81726795-5280-4311-87d3-ed2a33cca376)

Chart after attempting to remove the last point three times:
![Screenshot 2024-06-25 at 09 49 39](https://github.com/highcharts/highcharts/assets/49265903/870bd733-9354-4a7b-b481-6d3e1fe3bcae)

Chart after adding 3 points again:
![Screenshot 2024-06-25 at 09 51 13](https://github.com/highcharts/highcharts/assets/49265903/e8d7e27f-62dd-417f-be45-aa4d099df265)

Errors thrown(hundreds):
![Screenshot 2024-06-25 at 09 57 47](https://github.com/highcharts/highcharts/assets/49265903/a674eb82-abbf-47c2-8a33-6bdcfe43c353)

#### Expected behaviour
Last datapoint should be removed every time the "remove point" button is pressed.

#### Actual behaviour
First time the datapoint is removed, but the chart starts throwing errors, and markers break. Removing more than one point breaks chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/tordvv/Lu8f3n4q/78/

Follow steps in description

#### Product version
Highcharts 11.4.3

#### Affected browser(s)
Tested in Chrome

**Comment by hubertkozik** [comment]
Hi @tordvv! This is not a bug, you are passing the wrong `data` object as the first argument of the `setData` method. As you can read here: https://api.highcharts.com/class-reference/Highcharts.Series#setData first argument `data` takes an array of data in the same format as described under `series.{type}.data` for the given series type, for example, a line series would take data in the form described under [series.line.data](https://api.highcharts.com/highcharts/series.line.data).

Live demo: https://jsfiddle.net/BlackLabel/uthvo4ny/
