### ISSUE TITLE
The integer "0" parsed from an HTML table as a chart label breaks the chart 

### ISSUE THREAD

**Issue by derekprior** [highcharts/highcharts#2139]
Consider the question, "How many hours of TV did you watch last week?" with one possible answer of "0". If you use highcharts to parse response data from an HTML table and generate a chart, the chart will break. I suspect this is due to the falsey-ness of the number 0.

You can see a [minimal reproduction of this issue](http://jsfiddle.net/PB3Z6/), which simply changes the default highcharts example for table parsing by changing the first table row to have the heading "0". 

I was able to work around this by passing a `parsed` callback that does this (coffeescript):

``` coffeescript
parsed: (columns) ->
  columns[0] = _.map columns[0], (value) ->
    if value != null
      value.toString()
  columns[0].isNumeric = false
```

The string "0" is also falsey but this works; Maybe falsey-ness isn't the entire story here.

Yes, the label "0" is a poor choice: "0 Hours" would be much better, but sometimes these things are out of our control.

**Comment by oysteinmoseng** [comment]
This issue is still relevant with the latest code.
