### ISSUE TITLE
Issue with hovering over overlapping bubbles with sticky tracking disabled.

### ISSUE THREAD

**Issue by ddragula** [highcharts/highcharts#21405]
#### Expected behaviour
If sticky tracking is disabled, I expect that the bubble that the mouse is actually on will be hovered.

#### Actual behaviour
Sometimes a bubble that is close to the mouse pointer is hovered, but not the one over which the mouse actually is.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/nL20xoae/

#### Product version
Highcharts v11.4.3
Last working version: v11.1.0

#### Workaround
Custom events with `enableMouseTracking` disabled:
https://jsfiddle.net/BlackLabel/1cL68x2d/

**Comment by ddragula** [comment]
Failed to bisect, but it looks like the same commit also broke the prioritization of which point should be considered 'higher' in terms of interaction priority.

**See the demo:** https://jsfiddle.net/BlackLabel/xdtyzcna/

Notice that one of the bubbles is inside a larger bubble. Try to hover it. The larger bubble takes all the 'attention' and it seems to me that the correct action would be for the smaller one to always be prioritized.

**Comment by dianasalsa** [comment]
Unfortunately the suggested workaround using custom events is not usable in instances where Highcharts is integrated as part of a larger software solution. In our case that solution is _cplace_ and there it is only possible to generate config objects that are serializable to JSON. As such any event functions are simply discarded and not applied in the browser.

Therefore it would be really helpful if whatever change causes this bug could be reverted ASAP, as it breaks the behavior of our existing charts.

**Comment by hubertkozik** [comment]
Related ticket: https://github.com/highcharts/highcharts/issues/18940

**Comment by ddragula** [comment]
@hubertkozik It looks similar, but it seems to be something else. That bugfix that is already on master didn't fix both bugs I mentioned here.

**Comment by slaven3kopic** [comment]
Any news on this?

**Comment by hubertkozik** [comment]
@slaven3kopic as you can see, the work on fixing this issue has started :)
