### ISSUE TITLE
HTML labels can not be positioned by %, only by px

### ISSUE THREAD

**Issue by kriswillis** [highcharts/highcharts#2140]
When overlaying labels on a chart using percentages for positioning, it appears as though it is converted to a pixel value by replacing the % symbol with "px". Positioning with pixels becomes an issue when the chart is resized and the labels are not repositioned accordingly.

Example: http://jsfiddle.net/v64zp/

**Comment by oysteinmoseng** [comment]
This is still valid

**Comment by TorsteinHonsi** [comment]
The top-level [labels](https://api.highcharts.com/highcharts/labels) are now deprecated. Use [annotations](https://api.highcharts.com/highcharts/annotations) instead.
