### ISSUE TITLE
Treemap levelIsConstant: false is unsupported when data uses color: hexcode instead of color: name

### ISSUE THREAD

**Issue by aly-tq** [highcharts/highcharts#21418]
#### Expected behaviour
Using hex codes should be no different than using color names for treemap color behavior. 

Using the setting  `levelIsConstant: false` I expect that the first level of the treemap will be one color, the color of the root parent. 

This works:
```
data: [
          {
            id: 'id_1',
            name: 'A',
            value: 10,
            color: 'purple'
          },
          ...
          ]
```

This does not work:
```
data: [
          {
            id: 'id_1',
            name: 'A',
            value: 10,
            color: '#800080'
          },
          ...
          ]
```

#### Actual behaviour
When using the hex code, I see the colors of the children, not the parent.
https://jsfiddle.net/ahudson28/4hy67dcr/2/

This does not work:
```
data: [
          {
            id: 'id_1',
            name: 'A',
            value: 10,
            color: '#800080'
          },
          ...
          ]
```

#### Live demo with steps to reproduce
This works (all purple, no hex code): https://jsfiddle.net/ahudson28/Leu8d6py/1/
This does not work (not all purple, because I used a hex code) https://jsfiddle.net/ahudson28/4hy67dcr/2/

#### Product version
"highcharts": "^11.2.0",
"highcharts-react-official": "^3.2.1",

#### Affected browser(s)
Chrome 
Version 125.0.6422.142 (Official Build) (arm64)

**Comment by hubertkozik** [comment]
Hi @aly-tq! This is not a bug, the `series.opacity` is by default set to 0.15, that's why the purple color is not visible while using the hex codes. If you would like to see every colors please set opacity to 1.

**Live demo:** https://jsfiddle.net/BlackLabel/o2wa5zLq/
**API Reference:** https://api.highcharts.com/highcharts/series.treemap.opacity
