### ISSUE TITLE
Show Aggregated Dates of Time Series Chart in Tooltip

### ISSUE THREAD

**Issue by AMVamsi** [highcharts/highcharts#21415]
#### Expected behaviour

All aggregated Dates to be displayed in the tooltips when hovered or atleast option to get all the aggregated Dates from highcharts instance to display the  dates in range on the tooltip.

<img width="729" alt="img3" src="https://github.com/highcharts/highcharts/assets/52754565/077a8dd7-653a-4b71-a349-cccad95e6033">

#### Actual behaviour

Currently, the Highcharts instance only gives option to show the aggregated values, but not the specific range of Dates that were aggregated. On inspection found that highcharts instance is only giving the date of the first value of the aggregated set of value dates.

<img width="682" alt="img2" src="https://github.com/highcharts/highcharts/assets/52754565/4170e0ef-ec6b-4a43-8905-032520cc20aa">

#### Live demo with steps to reproduce

https://jsfiddle.net/dzusc0ph/

#### Product version
Highstock JS v9.1.2 
Highcharts JS v9.1.2 
 
#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Hi @AMVamsi! 

If you take a look at [a simpler demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/data-grouping/), you can see that in the tooltip there is information from when the group starts:
![image](https://github.com/highcharts/highcharts/assets/57004120/2b722e5c-ed99-4491-a975-415c5c73fd08)


You can modify it by writing your own `formatter`, and [more information in the API.](https://api.highcharts.com/highstock/tooltip.formatter)
