### ISSUE TITLE
Highstock connectNulls:false does not work for many points

### ISSUE THREAD

**Issue by auoiuiouio** [highcharts/highcharts#2142]
connectNulls:false doesn’t work when there is two kinds of plots (i.e. line and column) having many points. Here is an example that has nulls... you can see how it dips down to zero where the null values are: 
http://jsfiddle.net/efvQp/3/

This example shows gap when there is null values. In this example points are lesser than the above example hence we get gap when there is null values.
http://jsfiddle.net/efvQp/6/

Note: If I use highchart instead of highstock in the first example gap is shown where there is null
http://jsfiddle.net/efvQp/5/

I cannot use highchart since I need navigator and highchart doesn’t have navigator option. Please look into this issue as early as possible.

**Comment by jon-a-nygaard** [comment]
From [this example](http://jsfiddle.net/efvQp/3/) it seems that the issue has been fixed in at least the current version 4.2.5. If that is incorrect, and the issue still exists, please comment and/reopen.
