### ISSUE TITLE
Multiple KPI Gauge loses shape when values approach maxima

### ISSUE THREAD

**Issue by GerhardusC** [highcharts/highcharts#21429]
### Description

The multiple KPI gauge loses its shape when one or more values approach at least 98% of the maximum value per band.

#### Expected behaviour

It is expected that when the value of a multiple KPI band is at or above the maximum configured value, that it creates a uniform full gauge as in the image.

![Screenshot from 2024-07-01 09-14-06](https://github.com/highcharts/highcharts/assets/133974851/cc01ad7c-dd92-47e5-9703-a19aa1818904)

#### Actual behaviour

What actually happens is that the graph will lose its shape when the values get close to and become bigger than the maximum configured value per band.

![Screenshot from 2024-07-01 09-22-32](https://github.com/highcharts/highcharts/assets/133974851/ded502a1-73f5-4a63-9e3c-55bdd97bd79b)

##### Live demos

In this minimal fiddle below, which follows the official instructions on how to create a multiple KPI chart, you can see a very slight descrepency in the distances between the bands of the multiple KPI.
https://jsfiddle.net/bc9d0rm7/

In this slightly more involved example which provides a button to toggle the issue occurring in the Highcharts-React-Official wrapper, the issue is shown slightly more clearly when you click the button to increase the values close to their maxima.
https://stackblitz.com/edit/vitejs-vite-c6xser?file=src%2FGraph.tsx

##### Steps to reproduce

1. Create multiple KPI chart from the instructions here: https://www.highcharts.com/demo/highcharts/gauge-multiple-kpi
2. Set a series `y` value equal to or greater than 98% of the configured y-axis maximum.

#### Product version
highcharts: 11.4.0
highcharts-react-official: 3.2.1

#### Affected browser(s)

Firefox and Chrome at least.

**Comment by karolkolodziej** [comment]
Hi @GerhardusC! 
Thank you for reporting the issue.

It is connected with how the `rounded` option works- [simplified demo.](https://jsfiddle.net/hgfzurnd/)

_Internal note:_
The last working version `v11.4.1`, unable to bisect.

**Comment by hubertkozik** [comment]
_Internal note:_
Bisected to cd4bfe2d13a4d90e1e8484e5a94d2e0280449bca.
