### ISSUE TITLE
Gridline appears on spaced area - Highstock

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2144]
When moving navigator, it seems grid and xaxis label showing on chart's margin
1. http://jsfiddle.net/highcharts/wguGr/
2. Grid lines and labels appear to the left of the plot area.

Related topic: http://forum.highcharts.com/highstock-usage/version-1-3-4-overlaps-gridline-and-xaxis-label-t27444/
Quick view demo: http://jsfiddle.net/highcharts/cUCzE/

![error](https://f.cloud.github.com/assets/227836/967918/b104903a-058b-11e3-86a9-aed70f18592b.jpg)

**Comment by sebastianbochan** [comment]
Sometimes, only labels are out of area.

Example: http://jsfiddle.net/2p3p7nrp/2/
Set 2014-10-16 in the FROM input.

**Comment by curavista** [comment]
So this is still a valid bug ?

**Comment by TorsteinHonsi** [comment]
Apparently not, unless you have a live demo to prove it?

**Comment by pawelfus** [comment]
Closing as resolved. If anyone will be able to reproduce the issue, please reopen this ticket.

**Comment by mateuszkornecki** [comment]
I think it might be a similar issue.
Grid lines and ticks are appearing outside of the plot area. 
The problem occurs only with `datatime`.

After setting up `xAxis.ordinal : false` everything is working correctly. 

![Zrzut ekranu 2019-11-19 o 11 23 45](https://user-images.githubusercontent.com/50931078/69140929-d5cb6a80-0ac3-11ea-804d-67a2fec41691.png)
Simplified demo: [Stock chart with custom GUI - JSFiddle](https://jsfiddle.net/BlackLabel/2jfat6v0/)
Related topic: https://www.highcharts.com/forum/viewtopic.php?f=12&t=42891#p151023

**Comment by KacperMadej** [comment]
Looks like the problem is back since v6.2.0
6.2.0 - with the problem - http://jsfiddle.net/BlackLabel/6xa0htv7/
6.1.4 - no problem - http://jsfiddle.net/BlackLabel/6xa0htv7/1/

(a reference for the above comment demo - no problem in 6.1.4 - https://jsfiddle.net/BlackLabel/2jfat6v0/1/)
