### ISSUE TITLE
11.4.4 version produces a breaking changes by removing `legendItemClick`.

### ISSUE THREAD

**Issue by VictorPuigcerver** [highcharts/highcharts#21445]
#### Expected behaviour

Rollback breaking change produced by removing `legendItemClick`.

#### Actual behaviour

Using highcharts with typescript. The problem resides on the types.

HighCharts data: 
```
{
  chart: {
    type: 'empty',
  },
  exporting: {
    enabled: false,
  },
  title: {
    align: 'left',
    text: 'title',
    useHTML: true,
    style: {
      'font-style': 'normal',
      'font-weight': '400',
      'font-size': '16px',
      color: '#64666A',
    },
  },
  xAxis: {
    categories: [],
  },
  yAxis: {
    min: -750000,
    max: 700000,
    title: { text: '' },
  },
  plotOptions: {
    column: {
      borderColor: '#ffffff',
      borderRadius: 20,
    },
    series: {
      pointStart: 0,
      states: {
        hover: {
          enabled: false,
        },
      },
      events: {
        legendItemClick: function () {
          return false;
        },
      },
    },
    areaspline: {
      fillOpacity: 0.3,
      lineWidth: 2,
      threshold: null,
    },
  },
  tooltip: {
    formatter: function () {
      return false;
    },
  },
  credits: {
    enabled: false,
  },
  series: [
    {
      type: 'column',
      name: 'A',
      data: [],
      color: '#97C25F',
      pointWidth: 16,
    },
    {
      type: 'column',
      name: 'B',
      data: [],
      color: '#DE6F4C',
      pointWidth: 16,
    },
    {
      type: 'areaspline',
      name: 'C',
      color: '#E6E6E6',
      lineColor: '#F8D03B',
      fillColor: 'rgba(253, 239, 186, 0.5)',
      data: [],
      marker: {
        lineWidth: 0,
        lineColor: '#E6E6E6',
        fillColor: 'rgba(230, 230, 230, 1)',
      },
    },
  ],
};
```

With the attached data, the chart was working using previous patch version 11.4.3.
With the latest 11.4.4 version produces a breaking changes because `legendItemClick` has been removed, not deprecated as related on the latest changelog entry:

"Introduced new event and option [legend.events.itemClick](https://api.highcharts.com/highcharts/legend.events.itemClick), deprecated events.legendItemClick. See [#3957](https://github.com/highcharts/highcharts/issues/3957)."

#### Product version
Highcharts 11.4.4

**Comment by hubertkozik** [comment]
Hi @VictorPuigcerver! I've prepared a demo based on your chart config and I added an alert to the `legendItemClick` event.

**Live demo:** https://jsfiddle.net/BlackLabel/zth5grf1/

After clicking on the legend item, the alert is shown correctly. As you can see this event is not removed and is working correctly.

**Comment by VictorPuigcerver** [comment]
> Hi @VictorPuigcerver! I've prepared a demo based on your chart config and I added an alert to the `legendItemClick` event.
> 
> **Live demo:** https://jsfiddle.net/BlackLabel/zth5grf1/
> 
> After clicking on the legend item, the alert is shown correctly. As you can see this event is not removed and is working correctly.

Hi @hubertkozik ! I forgot to mention that the problem resides on types, when using highcharts with typescript, type restriction can be bypassed but it is not the way.

**Comment by alexkrautmann** [comment]
I can confirm the type is not available in 11.4.4. A Renovate PR that updates highcharts from 11.4.3 to 11.4.4 breaks in CI because of the missing type.

```
error TS2353: Object literal may only specify known properties, and 'legendItemClick' does not exist in type 'SeriesEventsOptionsObject'.
```

**Comment by skuske** [comment]
From my point of view, this deprecation makes it very complicated to access series properties from a legend click, see https://github.com/highcharts/highcharts-ios/issues/445

**Comment by hubertkozik** [comment]
@skuske you can get the series object from the `event` object, to be more precise `event.legendItem`: https://jsfiddle.net/BlackLabel/ea015wgx/

It is called `legendItem`, because the legend item can be a series, point (e.g. from pie series), or BubbleLegend item.

**API Reference:** https://api.highcharts.com/highcharts/legend.events.itemClick

**Comment by skuske** [comment]
@hubertkozik 

Many thanks, Hubert. That works and really helps a lot! Much appreciated!
