### ISSUE TITLE
Organization chart: Not able to customize the node UI with expected width

### ISSUE THREAD

**Issue by mohdmujahithali** [highcharts/highcharts#21466]
## Expected behaviour
Able to customize the node UI with expected width

## Actual behaviour
**Not Able** to customize the node UI with expected width. 

In the below attached screenshot, 
- Gray color border - highchart node wrapper.
- Green color border - customized new UI html.  (customized UI is getting render inside the highchart node wrapper)
<br/>

> **Screenshot-1**
>
> <img width="934" alt="image" src="https://github.com/highcharts/highcharts/assets/106740250/0cf1da1e-bd94-4762-8e6b-4f5a928bc813">
> <br/> <br/> 
> 
> **Note**:
> When having smaller number of nodes (5 to 8) in a single row, customized UI is showing correctly inside the highchart node wrapper.

> **Screenshot-2**
>
> <img width="923" alt="image" src="https://github.com/highcharts/highcharts/assets/106740250/539ac156-fdeb-4714-a707-8c0d872967a8">
> <br/> <br/> 
>
> **Issue**:
> When having larger number of nodes in a single row, then customized UI is **getting cut-off** inside the highchart node wrapper.

using classname & css styles, able to update the width & height of the customized UI. but **not able to change the width of the actual node wrapper (gray color border)**

**Now, need to update the width of highchart node wrapper (gray color border node)**

## Live demo with steps to reproduce
demo url - https://cz7jy5.csb.app/

## Product version
"highcharts": "^11.4.4",
"highcharts-react-official": "^3.2.1",

## Affected browser(s)
chrome & any

## Note
Not sure, this is a bug or not. I tried all the possible options from this https://api.highcharts.com/highcharts/series.organization
Kindly guide me, suppose if I missed any config or options

**Comment by mohdmujahithali** [comment]
@karolkolodziej Any update on this issue?

**Comment by karolkolodziej** [comment]
Hi @mohdmujahithali! 
Huge apologies but for some unknown reason this ticket got overlooked which I'm really sorry for.

When it comes to your demo if you declare a fixed node size you have to tell the chart to have the same. You can do it by:
- set the [nodeWidth](https://api.highcharts.com/highcharts/series.organization.nodeWidth)
- declare the [height](https://api.highcharts.com/highcharts/series.organization.nodes.height) for each node 

PS. In the inverted chart, the height is the width and the other way around.

[See in the demo for the first node](https://jsfiddle.net/BlackLabel/jfs5kqpg/)
