### ISSUE TITLE
Treemap zoom and pan feature

### ISSUE THREAD

**Issue by princ09** [highcharts/highcharts#21467]
#### Expected behaviour
I was trying to implement a treemap, but due to huge difference in values and huge amount of data, there are lots of small bins at the bottom of Right hand side of Highchart.

I don't want to drilldown the data because there is no grouping and it's not what we need.
We need to zoom using mouse wheel and ctrl +/- to small bins at bottom right and display the labels which were not visible because of small size.
Also when zoom we would like to pan using mouse.

#### Actual behaviour
There is no zoom and pan feature in treemap.

**Comment by hubertkozik** [comment]
Hi @princ09! Zooming in Treemap is currently not implemented, you can find a related ticket here: https://github.com/highcharts/highcharts/issues/4106

Currently, we are implementing a new feature to the Treemap series, it is a grouping of small leaf nodes, you can find more about it here: https://github.com/highcharts/highcharts/issues/20692 Do you think it will meet your requirements? If you have any comments, feel free to add them to the mentioned topic.

**Comment by princ09** [comment]
Hi @hubertkozik ,
I checked the proposed solution for small leaf nodes. It sounds good for some users but for me, it's more of like workaround for zooming.
Basically, you will be introducing a group for small nodes if it crosses a thresold value.
But this solution rises another problems like what will be thresold size? it's difficult to find out one because there are many deciding factors like different devices, screen size, container width etc. 

I do understand in SVG based chart it's difficult to provide zoom and pan. so let me know if it's going to be planned in future or not.
Till then I found [echarts treemap](https://echarts.apache.org/examples/en/editor.html?c=treemap-drill-down&lang=ts) which provides exactly what I need.

**Comment by hubertkozik** [comment]
The threshold will be a number of square pixels, if the node is smaller than the set value, it will be grouped.

I understand your thoughts about the possibility of zooming in Treemap series, let's keep the discussion in the mentioned ticket to avoid duplicates.

**Comment by princ09** [comment]
Hi @hubertkozik ,

I tried echarts treemap, they have zoom and pan feature but lacks so many basic functionalities like support for html in dataLabel etc and community support.

hence I purpose this feature again,
please have a look into this [TradingView Heatmap](https://in.tradingview.com/heatmap/stock/#%7B%22dataSource%22%3A%22CNX500%22%2C%22blockColor%22%3A%22change%22%2C%22blockSize%22%3A%22market_cap_basic%22%2C%22grouping%22%3A%22no_group%22%7D) this link illustrates very nicely what I am trying to achieve and shows the practical application of it.

**Comment by hubertkozik** [comment]
@princ09 The GitHub ticket intended for Treemap zooming is this one: https://github.com/highcharts/highcharts/issues/4106 This ticket is open and added to our backlog. If you have any thoughts, feel free to leave them in https://github.com/highcharts/highcharts/issues/4106.
