### ISSUE TITLE
Latest version can't be downloaded 11.4.5

### ISSUE THREAD

**Issue by pilootchoum** [highcharts/highcharts#21465]
#### Expected behaviour
Being able to update current highchart version to the latest one as it is available on npm
https://www.npmjs.com/package/highcharts/v/11.4.5

#### Actual behaviour
Can't download latest version during npm install

<img width="688" alt="image" src="https://github.com/highcharts/highcharts/assets/1533159/fa7c5ee3-d26c-4d4b-8c21-4fb6f690b591">

**Comment by pilootchoum** [comment]
Looks like this commit https://github.com/highcharts/highcharts/commit/04407d36749946b3732687f708f00e7effdf4369
fixed it

**Comment by bm64** [comment]
Hi @pilootchoum 

Tested it on my end too and seems to work correctly now. Thanks for reporting though.
