### ISSUE TITLE
The min and max in the afterSetExtremesEvent is inaccurate when zooming in a BarChart

### ISSUE THREAD

**Issue by lingyufei** [highcharts/highcharts#21461]
When I zoom in on the BarChart, the min and max I get are inaccurate. 

Please check the image I attached. I parse the min and max in the afterSetExtremesEvent and display it in the subtitle.

When I zoom in on a Barchart, the min and max are inconsistent with the data displayed on the x-axis.

For example, the min I got is [Jun, 28 1:59], but the min of the x-axis in the chart is much earlier than it.

<img width="1222" alt="image" src="https://github.com/highcharts/highcharts/assets/49775184/62242ae1-347b-4f65-8cd3-f2c36fa4cf95">

**Comment by karolkolodziej** [comment]
Hi @lingyufei!

Could you please share the demo you refer to?

**Comment by lingyufei** [comment]
Please try this: [https://jsfiddle.net/fayel/2szp6to4/7/](https://jsfiddle.net/fayel/2szp6to4/7/)
And zoom into the middle of the chart. The zommed in min and max time is not right.
<img width="1154" alt="image" src="https://github.com/highcharts/highcharts/assets/49775184/57f23320-9f21-4c09-bdc6-3ce2d9460477">

**Comment by karolkolodziej** [comment]
@lingyufei The `column` series is a bit specific because in cases like this, it visually reserves some of the space to render the column. 
If you compare it to the line series, everything is more intuitive and there are no shifts- [see in the demo.](https://jsfiddle.net/9npeau7z/)
