### ISSUE TITLE
In the Chrome browser, the drill-up button in the treemap chart is positioned inaccurately.

### ISSUE THREAD

**Issue by rakseong** [highcharts/highcharts#21469]
#### Expected behaviour

In a treemap chart using drilldown, the position of the button to move to the upper level remains fixed when repeatedly moving between lower and upper levels.

#### Actual behaviour

The position of the button to move to the upper level is not fixed.

#### Live demo with steps to reproduce

Highcharts Demos > Heat and tree maps > Large tree map
https://www.highcharts.com/demo/highcharts/treemap-large-dataset

This bug appears to occur only in the Chrome browser.

#### Product version

highcharts: v11.3.0
highcharts-react-official: v3.2.1 

#### Affected browser(s)

chrome : 126.0.6478.61 (Official Build) (arm64)

**Comment by karolkolodziej** [comment]
Hi @rakseong!

A similar issue has been reported here: https://github.com/highcharts/highcharts/issues/21344

As far as I see it is already fixed and in `Chrome 126.0.6478.127 (Official Build) (arm64)` I don't see the issue anymore.
