### ISSUE TITLE
Not able to plot mapppoint while using geoJSON world

### ISSUE THREAD

**Issue by Ashish0401philips** [highcharts/highcharts#21471]
When I am using topoJson for world, then I am able to see the mappoints plotted, but when I am using geoJson, then I am only able to see the map and not the points.
Can anyone please share a working demo if it's possible

**Comment by hubertkozik** [comment]
Hi @Ashish0401philips! Here are demos:

- MapPoint Series on TopoJSON map: https://jsfiddle.net/BlackLabel/r52a8uc6/
- MapPoint Series on GeoJSON map: https://jsfiddle.net/BlackLabel/dmcxh7ke/

We use GitHub as a tool for bugs/feature request tracking and your question is strictly a support question. Feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.

**Comment by Ashish0401philips** [comment]
Thanks @hubertkozik . Will surely use the support channels from next time
