### ISSUE TITLE
Migrating to 11.4.5 result error Module not found: Error: Can't resolve 'highcharts-more' in '.../node_modules/highcharts/modules'

### ISSUE THREAD

**Issue by Tallyb** [highcharts/highcharts#21470]
#### Expected behaviour
patch version should be backward compatible

#### Actual behaviour
error in ./node_modules/highcharts/modules/solid-gauge.js  
error Module not found: Error: Can't resolve 'highcharts-more' in '.../node_modules/highcharts/modules'

we did not manage to upgrade highcharts since 11.4.1. typing issues, resolution issue and more.

**Comment by atharva94** [comment]
Faced the same issue, maybe the highcharts-more is not present in the new version, you can either install it separately 
using `npm install highcharts-more` or don't use caret or tilt if you are using a lower version of highcharts.

**Comment by pricopz** [comment]
Hi, I have the same issue with angular 4.0 and highcharts 11.4.5

**Comment by ujjwal-iqlect** [comment]
I'm also facing same issue with highcharts 11.4.5 and react 18.2.0 and nextjs 13.4.12. Most likely the issue is that it is trying to find highcharts-more.js file `highcharts/modules` directory. However, the file is actually located in the `highcharts` directory.

**Comment by Artemeey** [comment]
Error occered in version 11.4.4, after migrate from 11.4.3

highcharts/highcharts-more changed to highcharts-more: https://github.com/highcharts/highcharts/commit/13534ee8ae9487b4ba6ab63ba5d30f5700ee174b#diff-c056debc7a1bacd4a023d4f0f7be0dd2ac01632acd1681ebce0177f0339b54dd

see 2 files:
- https://unpkg.com/highcharts@11.4.4/highcharts-more.js: highcharts-more defined as highcharts/highcharts-more
- https://unpkg.com/highcharts@11.4.4/modules/solid-gauge.js: but loaded as highcharts-more, not as highcharts/highcharts-more

**Comment by TorsteinHonsi** [comment]
Sorry for the inconvenience! We just released v11.4.6 which corrects this issue.
