### ISSUE TITLE
Organization chart: Need a feature to accept the onClick event for customized node UI element

### ISSUE THREAD

**Issue by mohdmujahithali** [highcharts/highcharts#21486]
## Description of the feature
I can able to customize the node UI. But its not allow to have custom event handler for the same.

currently, click event handler are accomplished using the "events" prop only. This events handler getting called, wherever clicked in the node.

In my case, I need a click event only for the specific portion of the node alone. Not for the entire node UI. 
i.e) In my customized UI, I am having the info icon image. I need a click event handler only for this info icon image.
also, there is another icon image to show the team details in a modal popup. 

So, adding this feature request ticket to accommodate the event handler for the specific UI element alone

`plotOptions: {
        organization: {
          colorByPoint: false,
          color: "#ffF",
          nodeWidth: infoCardHeight,
          dataLabels: {
            nodeFormatter: function () {
              const { name } = this.point;
              return renderCustomNode({ name });
            },
          },
          events: {
            click: function (event) {
              const { id } = event.point as Highcharts.SankeyNodeObject;
              updateSelectedNodeLinks(id);
            },
          },
        },
      },`

## Library related to the feature
Highcharts

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by karolkolodziej** [comment]
Hi @mohdmujahithali! 

In this case please use the point click events. You can the `event.taget` to check where the user clicked and based on that react accordingly- [see in the demo.](https://jsfiddle.net/8b4a5wq3/)

In case of any other questions related to that please contact our [support team.](https://www.highcharts.com/blog/support/)
