### ISSUE TITLE
Deleted annotation is present in exported image

### ISSUE THREAD

**Issue by nishikantparmariam** [highcharts/highcharts#21507]
#### Expected behaviour
If annotation has been removed using `chart.removeAnnotation`, it should not be part of downloaded PNG.

#### Actual behaviour
Annotation even if deleted is part of downloaded PNG if an `annotation.update` was called on it before deletion.

#### Live demo with steps to reproduce

**https://jsfiddle.net/w7tz1jde/**

Steps - 

- Click on `Add annotation` button
- Click anywhere on plot area to add the annotation
- Click `Change font color` button to change annotation's color
- Click `Delete Annotation` button to delete the annotation

So far everything works as expected, but now download the chart as PNG using icon on top-right and see that downloaded image still has deleted annotation.

Weirdly it works if `Change font color` wasn't clicked in between i.e. annotation was added and deleted. Now deleted annotation is not part of downloaded PNG as expected. Having an update seems to introduce a bug.

Can you please help us with workaround plugin or something similar to solve this issue?

#### Product version
Latest

#### Affected browser(s)
Tried on Chrome

**Comment by bm64** [comment]
Hi @nishikantparmariam and thanks for reporting the issue

**Comment by nishikantparmariam** [comment]
Thanks for the reply @bm64, while this is fixed in Highcharts, is there a workaround/solution we can use?

**Comment by pawelfus** [comment]
**Workaround:**

Demo: https://jsfiddle.net/BlackLabel/edramfnp/

Plugin:
```ts
(function(H) {
  H.addEvent(
    H.Annotation,
    'afterUpdate',
    function(e) {
      const chart = this.chart,
        idx = chart.annotations.indexOf(this);

      if (
        idx >= 0 &&
        this.options !== this.chart.options.annotations[idx]
      ) {
        this.chart.options.annotations[idx] = this.options;

      }
    }
  );
})(Highcharts);
```

*Internal note:*
We store the wrong reference in the chart config after the annotation update. We should store what is created in init:

https://github.com/highcharts/highcharts/blob/935bde11483ce7168ce6ecd2ad173835eb5f4d8e/ts/Extensions/Annotations/Annotation.ts#L871-L872

Should be ` ... = this.options`, not `= options`.
