### ISSUE TITLE
Donut Chart: Issue with Data plotting

### ISSUE THREAD

**Issue by niralivasoya** [highcharts/highcharts#21502]
#### Expected behaviour

Is there any way to create a donut chart like this? I tried [this example](https://www.highcharts.com/demo/highcharts/pie-donut) but was unable to end up like this.
<img width="545" alt="image" src="https://github.com/highcharts/highcharts/assets/32123446/77047f61-9194-4a0e-891a-b15cc1095143">

I want to show the total category percentage when we hover over the outer layer, is it possible to show the outer layer for the main category as shown in this image?
<img width="193" alt="image" src="https://github.com/highcharts/highcharts/assets/32123446/fd0d1643-eecf-4897-93dd-762457a62bd7">

I want to display subcategory data as shown in the image. Could someone please help me structure the series data to achieve this chart?

Is there any code example or any suggestion for this type of chart? Thanks

**Comment by karolkolodziej** [comment]
Hi @niralivasoya!

Yes, this is possible you only need to create two series with different inner sizes- [see in the demo.](https://jsfiddle.net/st9Lkdcw/1/)

For future reference with questions like this please contact [our support team](https://www.highcharts.com/blog/support/) first.

**Comment by niralivasoya** [comment]
@karolkolodziej, Sure. Thanks for your help. Appreciate it.
