### ISSUE TITLE
Mapline is hidden when drawing from LA to taiwan

### ISSUE THREAD

**Issue by tuanlam0201** [highcharts/highcharts#21503]
![Screenshot from 2024-07-09 16-15-52](https://github.com/highcharts/highcharts/assets/163503189/3eab614e-0899-4d70-af62-bd797fc14330)
![Screenshot from 2024-07-09 16-16-01](https://github.com/highcharts/highcharts/assets/163503189/d7440a97-f27b-4158-b60a-c996f31b9579)

**Comment by tuanlam0201** [comment]
{
    chart: {
      map: props.mapData,
      height: props.height,
    },
    title: {
      text: '',
    },
    plotOptions: {
      mapline: {
        nullColor: props.theme.palette.error.main,
      },
      mappoint: {
        marker: {
          fillColor: props.theme.palette.error.main,
          lineWidth: 1,
          symbol: 'mapmarker',
          radius: 8,
        },
      },
    },
    mapView: {
      projection: {
        name: 'WebMercator',
      },
      center: [0, 40],
      zoom: 1,
    },
    mapNavigation: {
      enabled: true,
      buttonOptions: {
        verticalAlign: 'bottom',
      },
    },
    xAxis: {
      lineWidth: 0,
      tickWidth: 0,
      labels: {
        enabled: false,
      },
    },
    yAxis: {
      lineWidth: 0,
      tickWidth: 0,
      labels: {
        enabled: false,
      },
    },
    legend: {
      enabled: false,
    },
    series: [
      {
        type: 'map',
        data: [
          ['us', 10],
          ['tw', 20],
        ],
        joinBy: 'hc-key',
        name: 'Map Data',
        states: {
          hover: {
            color: props.theme.palette.primary.main,
          },
        },
        color: props.theme.palette.primary.main,
        dataLabels: {
          enabled: false,
          format: '{point.name}',
        },
      },
      {
        type: 'mappoint',
        name: 'State',
        dataLabels: {
          enabled: true,
          y: -30,
          format: `
        <div style="color: #fff">
        <span style="color: inherit; display: block; margin-bottom: 5px">{point.name}</span>
        <span style="color: inherit; display: block; margin-bottom: 5px">VERITIV</span>
        <span style="color: inherit; display: block; margin-bottom: 5px">9330 Nw 110th Avenue, Miami, Fl 33178, USA</span>
        </div>
        `,
          backgroundColor: props.theme.palette.commonBlackStatesMain.main,
          borderRadius: 4,
          padding: 8,
          useHTML: true,
        },
        data: [
          {
            lon: 121.59,
            lat: 25.10,
            name: 'Amsterdam',
          },
          {
            lon: -118.24,
            lat: 34.05,
            name: 'LA',
          },
        ],
      },
      {
        type: 'mapline',
        dashStyle: 'Dash',
        lineWidth: 2,
        data: [
          {
            geometry: {
              type: "LineString",
              coordinates: [
                [121.59, 25.10],
                [-118.24, 34.05],
              ],
            },
          },
        ],
      },
    ],
  };

**Comment by hubertkozik** [comment]
Hi @tuanlam0201! This is not a bug, this is desired behaviour, by design. This is because the MapLine is drawn in the shortest possible way and it gets cut by the antimeridian. In cylindrical and conic projections this is mitigated by doing client-side antimeridial cutting so that shapes spanning from one side of the plane to the other are cut in two.

You can change the `lambda` in rotation options to see, the line is drawn correctly: https://jsfiddle.net/BlackLabel/o61ehLf8/
