### ISSUE TITLE
chart.getAxes() is poorly named

### ISSUE THREAD

**Issue by cnighswonger** [highcharts/highcharts#21519]
[chart.getAxes()](https://github.com/highcharts/highcharts/blob/b68f6f3458ab9e3b51bf7d4e528663874868c0a1/ts/Core/Chart/Chart.ts#L1051) is poorly named. Just before the definition of this method, we have `chart.get()` which correctly indicates that the method 'gets' something and returns it to the caller. One would reasonably assume that `getAxes `would 'get' a list of current axes and return it to the caller.

The comments are also confusing as it is implied that calling this creates a single axis: `Create the Axis instances based on the config options.` Whereas the name implies multiple axes are involved.

Perhaps a few minutes work with sed could resolve this. Maybe it could be renamed to `addAxes` or `addAxis` depending on if the action is singular or plural.

And that would free up `chart.getAxes()` to be defined to return a list of current axes which would be quite useful.

**Comment by hubertkozik** [comment]
Hi @cnighswonger! [chart.getAxes()](https://github.com/highcharts/highcharts/blob/b68f6f3458ab9e3b51bf7d4e528663874868c0a1/ts/Core/Chart/Chart.ts#L1051) is not an official method, it is used only internally in Highcharts. You can check, that this method is not documented here: https://api.highcharts.com/class-reference/Highcharts.Chart in our official docs.

However, the name of this method can be changed, we will investigate it and decide what to do. FYI @TorsteinHonsi @oysteinmoseng

**Comment by cnighswonger** [comment]
Good day @hubertkozik . I realize that this method is not an official method and was aware that there is no documentation for it.

However, the name should be freed up due to the facts that:

- It is clearly confusing.
- It should be available for use in an enhancement which would provide the aforementioned method.

**Comment by TorsteinHonsi** [comment]
@hubertkozik Yes I think @cnighswonger has a good point. The name `getAxes` also indicates that it returns something, which it doesn't. I think `createAxes` would be a more descriptive name. The events `getAxes` and `afterGetAxes` should then be updated accordingly.

**Comment by cnighswonger** [comment]
A big thanks to all who worked on this to make it happen. Its a pretty small change in the scope of things, but anything which clarifies makes life easier in the long run.

Thanks as well for a great product!
