### ISSUE TITLE
Infinite chart resize (reflow)

### ISSUE THREAD

**Issue by KamilKubik** [highcharts/highcharts#21510]
#### Expected behaviour
The chart shouldn't resize infinitely.

#### Actual behaviour
The chart resizes infinitely.

#### Live demo with steps to reproduce
1. Set the `height: '100%'` on the container div,
2. Create an outer container with the following styles: `height: '100%', display: flex, flex-direction: column`,
3. Insert a div without explicit height style between the container and the chart,
4. Resize the width of the container, and the chart will start to self-resize its height infinitely.

**Demo**: https://jsfiddle.net/BlackLabel/u205ewpL/

**Note**: It seems there's an issue with the [reflow](https://github.com/highcharts/highcharts/blob/master/ts/Core/Chart/Chart.ts#L1768) method.

#### Workarounds:

- Remove the overlapping div between the container and the chart.
- Remove the html/body `height: '100%'` style.
- Set the [chart.reflow](https://api.highcharts.com/highcharts/chart.reflow) property to `false`.
- Use the [chart.setSize](https://api.highcharts.com/class-reference/Highcharts.Chart#setSize) method manually. 

#### Product version
Highcharts JS v11.4.6

**Comment by hubertkozik** [comment]
This issue is reproducible even in Highcharts v8.0.0: https://jsfiddle.net/BlackLabel/u205ewpL/6/ If you resize the window, the chart height will grow.

Looks, that it is **NOT** connected to a similar issue: https://github.com/highcharts/highcharts/issues/21188
