### ISSUE TITLE
`headerFormat` use `{point.point.name}` syntax but `pointFormat` use `{point.name}` syntax

### ISSUE THREAD

**Issue by JulienBacquart** [highcharts/highcharts#21514]
In some specific cases, to access an attribute of a point in the `headerFormat` you need to use the `point.point.name` syntax while in the `pointFormat` use the `point.name` syntax.
I was not able to identify why in some case  `point.name` works for `headerFormat` and sometime it doesn't, the fact the tooltip is shared doesn't seem to change anything.

This works:
```Javascript
tooltip: {
      headerFormat: "{point.point.name}<br />",
      pointFormat: "{point.name}<br />",
      shared: false,
},
```

This doesn't works:
```Javascript
tooltip: {
      headerFormat: "{point.name}<br />",
      pointFormat: "{point.name}<br />",
      shared: false,
},
```
```Javascript
tooltip: {
      headerFormat: "{point.point.name}<br />",
      pointFormat: "{point.point.name}<br />",
      shared: false,
},
``` 

Demo: 
https://jsfiddle.net/noLry2ek/

This is an extremely confusing behavior.
See: https://stackoverflow.com/questions/70436408/cant-access-custom-point-variable-inside-highcharts-tooltip-headerformat

An issue #4281 was already opened and closed on the subject, with a commit to add a sentence to the doc, which is not part of the doc today anymore.
Personally, seeing how this behavior is counter-intuitive (a.k.a you will tear your hair out when you run into it), I think it deserves more than a sentence buried in the doc.

**Comment by karolkolodziej** [comment]
Hi @JulienBacquart! 
Thank you for pointing that out. Indeed it might be confusing sometimes.

Internal note:
Do we need to pass `point: labelConfig` whereas `labelConfig` is most likely the point? 
The only thing that worries me is backwards compatibility if we change that.
https://github.com/highcharts/highcharts/blob/b68f6f3458ab9e3b51bf7d4e528663874868c0a1/ts/Core/Tooltip.ts#L1713-L1716
