### ISSUE TITLE
Hover state of errorbar is not working

### ISSUE THREAD

**Issue by DiogoDoreto** [highcharts/highcharts#2152]
Hello!

I need to execute an action when the user clicks on each element of the chart, but the errorbar is too thin and too hard to click. So I tried to make it thicker on hover, but this is not working.

Here is a demo of the hover problem: http://jsfiddle.net/PqMyg/

Thanks!

**Comment by pawelfus** [comment]
Errorbar series doesn't have `lineWidth` property for hover state, see [API](http://api.highcharts.com/highcharts#plotOptions.errorbar.states.hover).

**Comment by sebastianbochan** [comment]
_Workaround:_
- use `customEvents.js` module and declare `series.events.click` action.

Demo:
- http://jsfiddle.net/BlackLabel/4etjqxmm/
