### ISSUE TITLE
Improve responsiveness for plot band labels

### ISSUE THREAD

**Issue by htveit** [highcharts/highcharts#21521]
It would be great if Highcharts could enhance the responsiveness for overlapping labels on plot bands.

#### Expected behaviour
Show ellipsis with an option to display more information on hover, similar to the approach Highcharts uses when labels overlap.

#### Actual behaviour
Plot band labels overlap on small devices. 

<img width="392" alt="Screenshot 2024-07-11 at 09 16 48" src="https://github.com/highcharts/highcharts/assets/42646002/9bfd3599-09b4-41fe-b46f-60b2b619099d">

#### Live demo with steps to reproduce
See https://codepen.io/htveit/full/dyBPgBP on a mobile device

#### Product version
Highcharts v 11

#### Affected browser(s)
All

**Comment by bm64** [comment]
Hi @htveit, thanks for sharing your idea. Related ticket: https://github.com/highcharts/highcharts/issues/2023
