### ISSUE TITLE
Numbers on axis labels

### ISSUE THREAD

**Issue by DemetrioG** [highcharts/highcharts#21530]
#### Details
- I have bubble chart with text values on xAxis. But chart extremes returning not existent numeric values. Can you check if this is a wrong implementation or HC bug?

#### Expected behaviour
- Axis rendered without numbers

#### Actual behaviour
- Axis rendered with numbers on extremes

![image](https://github.com/highcharts/highcharts/assets/79758394/13ec0aa6-69c4-4942-bc74-b95735ab0c9e)

#### Live demo with steps to reproduce
- https://codesandbox.io/p/sandbox/spring-cookies-6wmrdw?file=%2Fsrc%2FExample.tsx

- **Note**: if don't see the numbers, resize codesandbox preview tab. 

#### Product version
- Highcharts - 11.3.0

#### Affected browser(s)
- Google Chrome

**Comment by bm64** [comment]
Hello @DemetrioG and thanks for reporting the issue.

The issue occurs only at certain chart widths. See simplified demo:
Working: https://jsfiddle.net/BlackLabel/7w02c9t1/
Not working: https://jsfiddle.net/BlackLabel/87jq350f/

**Comment by DemetrioG** [comment]
Thanks @bm64! Has any workaround for this?

**Comment by bm64** [comment]
Hi @DemetrioG 
Please try this plugin and see if it helps: https://jsfiddle.net/BlackLabel/3ybLzsmj/

_Internal note_
Bisecte to:  https://github.com/highcharts/highcharts/commit/0879bd1e32487a441ee40dcfb859a26a12b02a6e
Also related to: https://github.com/highcharts/highcharts/pull/21005

**Comment by kaz1ngton** [comment]
Hi @bm64 

If you remove width property and reduce size of window, bug is still there 

![image](https://github.com/user-attachments/assets/b850f2f0-4c5e-43ef-8a28-86afa60c07c3)

**Comment by bm64** [comment]
@kaz1ngton

You're right, the workaround doesn't cover all cases. Tick calculations are complex with many factors that impact them. Unfortunately, you'll need to wait for the fix.

**Comment by david-molnar-oculai** [comment]
Why is this closed? It doesn't seem to be fixed. The merged PR for the fix was only for the bubble series, but the bug appears also on others as well. Could you please reopen?

**Comment by karolkolodziej** [comment]
@david-molnar-oculai This issue is fixed on the `master` branch but it hasn't been released yet.
It will be included in v12 which is right around the corner.

**Comment by david-molnar-oculai** [comment]
Thanks for the answer. Do you have the PR which fixed it?

**Comment by karolkolodziej** [comment]
Yes, this one fixed the issue: https://github.com/highcharts/highcharts/pull/21672

**Comment by david-molnar-oculai** [comment]
@karolkolodziej isn't that only for the BubbleSeries? Or am I missing something?

**Comment by MarkusBarstad** [comment]
@david-molnar-oculai could you post an example where this happens for any other series? 🤔
