### ISSUE TITLE
Highcharts map shows tooltip after series hidden by clicking on legend

### ISSUE THREAD

**Issue by RW-JMacCreery** [highcharts/highcharts#21547]
#### Expected behaviour
When a map point series on Highchart Maps is hidden by clicking on its legend, the series' tooltips should not show when hovering over where the map points have been hidden. 

#### Actual behaviour
When a map point series on Highchart Maps is hidden by clicking on its legend, the series' tooltips is showing in Chrome and Edge. However, it does not show when using Firefox. Safari hasn't been tested. 

#### Live demo with steps to reproduce

jsfiddle.net/mkzpnLfc/
This can be seen by looking at the map points in the JSFiddle, then hiding the A series, then moving your mouse back near where those points were. 

#### Product version
Highmaps JS v11.4.6 (2024-07-08)

#### Affected browser(s)
Chrome & Edge (Safari unknown, not happening in Firefox)

**Comment by RW-JMacCreery** [comment]
Here's the JSFiddle:

**Comment by RW-JMacCreery** [comment]
Here's most of hte line to JSFiddle. Please add the https:  and //
jsfiddle.net/mkzpnLfc/

**Comment by hubertkozik** [comment]
Hi @RW-JMacCreery! This issue has the same rootcause as https://github.com/highcharts/highcharts/issues/21501. The workaround for now is to set `pointer-events` to `auto` with important flag: https://jsfiddle.net/BlackLabel/fyc2n36m/
