### ISSUE TITLE
Map drilldown breaks when colorAxis min and max values are set to specific range. 

### ISSUE THREAD

**Issue by esszed** [highcharts/highcharts#21546]
#### Expected behaviour
Drilldown drills correctly to the unit no matter the mix/max range. 

#### Actual behaviour
When range is set (atleast in this demo) to range with min/max difference of 4 ( 0 and 4, 1 and 5, 4 and 8 etc) the drilldown breaks visually and afterApplyDrilldown is never called. No errors appear in console.  If set to difference of 5 it works correctly again.

#### Live demo with steps to reproduce
[jsfiddle](https://jsfiddle.net/esszed/2d0Lk37q/5/)

To reproduce set colorAxis min/max range to any difference of 4 (setting max to 4 without setting min also reproduces the issue) 

#### Product version
Highmaps JS v11.4.6 (2024-07-08)

#### Affected browser(s)
Chrome, firefox tested

**Comment by hubertkozik** [comment]
Hi @esszed! Thank you for reporting the regression. The other workaround can be disabling the animation of drilldown: https://jsfiddle.net/BlackLabel/f0kvtb3y/

_Internal note:_
Bisected to e07b3f97fe8223670de4f7864ada29e91fa6b235.
