### ISSUE TITLE
Cursor on specific data points

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2155]
it would be nice to configure the `cursor` on a specific data point.
e.g. a certain pie slice

**Comment by NickolasLapp** [comment]
+1 for this enhancement. Adding cursor option to points would be a nice addition.

**Comment by TorsteinHonsi** [comment]
In Highcharts 5 it can be fixed by the new `className` option: http://jsfiddle.net/highcharts/wfcNS/6/

**Comment by NickolasLapp** [comment]
Thanks for your quick reply! that'll work nicely.

**Comment by mir3z** [comment]
> In Highcharts 5 it can be fixed by the new className option: http://jsfiddle.net/highcharts/wfcNS/6/

Unfortunate className property can be applied only to a data point. What if I'd like to have pointer cursor on that red "halo" circle as well?

![image](https://user-images.githubusercontent.com/1816692/35116687-99a0ed56-fc8c-11e7-9b2a-63877b3916af.png)

**Comment by SaeedZhiany** [comment]
@TorsteinHonsi 
This is an old issue, there is a obstacle for adding this feature for every data points?
