### ISSUE TITLE
Can't load es-modules version of highcharts-more due to CORS

### ISSUE THREAD

**Issue by shaunakv1** [highcharts/highcharts#21567]
#### Expected behaviour
I am using ECMA 6 modules [as described](https://www.highcharts.com/docs/getting-started/installation-with-esm) but I get CORS errors. Exactly same as described in this following issue but it was closed

https://github.com/highcharts/highcharts/issues/15437

#### Actual behaviour

![image](https://github.com/user-attachments/assets/fb2483dd-6ef5-4840-b586-26359e4ea1b0)

Here's how I import the modules: 

```js
//main.js
import Highcharts from 'https://code.highcharts.com/es-modules/masters/highcharts.src.js';
import 'https://code.highcharts.com/es-modules/masters/highcharts-more.src.js';
import 'https://code.highcharts.com/es-modules/masters/modules/accessibility.src.js';
import { theme } from '../chart-theme.js';
import { Map } from '../map.js';
```

```html
<script src="js/main.js" type="module"></script>
```

**Comment by hubertkozik** [comment]
Hi @shaunakv1! You are facing HTTP error 429: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429 Too Many Requests. We are rate-limiting the number of requests to prevent large traffic on the network. You've probably done too many requests in a short time from your application. To prevent this situation you can e.g. load the files from your server: https://www.highcharts.com/docs/getting-started/installation
