### ISSUE TITLE
Tooltip in 3D Pie

### ISSUE THREAD

**Issue by si-rg-frontend** [highcharts/highcharts#21569]
#### Expected behaviour
Should show a tooltip of datalabel on hover of a slice in 3d Pie Chart

#### Actual behaviour
nothing happens when we hover on a slice

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/highcharts/3d-pie

#### Product version
HighCharts 11.4.6

#### Affected browser(s)
All

**Comment by hubertkozik** [comment]
Hi @si-rg-frontend! This issue has the same rootcause as https://github.com/highcharts/highcharts/issues/21501. The workaround for now is to set `pointer-events` to `auto` with important flag: https://jsfiddle.net/BlackLabel/fyc2n36m/

It will be fixed in the next release of Highcharts.

**Comment by si-rg-frontend** [comment]
@hubertkozik Hi!, thanks
