### ISSUE TITLE
Animation setting does not apply when hiding a tooltip

### ISSUE THREAD

**Issue by tdorie** [highcharts/highcharts#2156]
Setting animation: false on the toolTip object does not affect the fadeOut call that is made when hiding the tooltip. 

The call to fadeOut causes an error with Jquery 1.7 on IE 8 when mousing away from a tooltip (Object doesn't support property or method "removeAttribute")

**Comment by cvasseng** [comment]
Hi! We're doing a bit of spring cleaning, and closing old issues. If you're still experiencing issues with this, please feel free to open a new issue! Thanks!
