### ISSUE TITLE
Drag navigation zoom bar is difficult when is vertical

### ISSUE THREAD

**Issue by micaderito** [highcharts/highcharts#21575]
#### Expected behaviour
Drag navigation zoom bar should be easier like in column chart with horizontal navigation bar. The drag icon appear when you hover in any place of the navigation bar

https://github.com/user-attachments/assets/82751370-f9e1-44aa-98a7-84cb09133ad9

#### Actual behaviour
When we have a bar chart with vertical navigation bar, drag icon appear only if you hover in the first half of the bar, making difficult to the user to drag the bar

https://github.com/user-attachments/assets/6c661642-2926-41eb-bda6-8f081bd5ebab

Is there any solution for that issue? Thanks!

#### Live demo with steps to reproduce
[Live demo](https://jsfiddle.net/j0oaf5xm/1/)

#### Product version
Highcharts latest version

**Comment by karolkolodziej** [comment]
Hi @micaderito! 
Thank you for reporting the issue.

Internal note:
Bisected to commit ce54038006

**Comment by hubertkozik** [comment]
This issue has the same rootcause as https://github.com/highcharts/highcharts/issues/21501. The workaround for now is to set pointer-events to auto with important flag: https://jsfiddle.net/BlackLabel/q063v59u/

**Comment by hubertkozik** [comment]
Closing as completed in https://github.com/highcharts/highcharts/issues/21656.
