### ISSUE TITLE
Drilldown event on chart fires multiple Times on stacked column series #2989

### ISSUE THREAD

**Issue by mikeg2580** [highcharts/highcharts#21570]
Has there been any fixes for this? https://github.com/highcharts/highcharts/issues/2989

The proposed solution below does not work for me since !e.points is false on both drilldown occurrences and e.point looks the same on both occurrences as well.

if (!e.points || e.points[0] == e.point) {
......
}

I am using a stacked column chart.

**Comment by hubertkozik** [comment]
Hi @mikeg2580! Let's go ahead and talk about the topic mentioned since it looks like a duplicate.

**Comment by mikeg2580** [comment]
I tried to reproduce it in jsfiddle but I cant. I am using react. Not sure if that is where it may be occurring. I did notice that on your stack column you only have one column per stack. Here is what mines looks like.

image
When I click any of the columns I get the event fired twice with the same point
