### ISSUE TITLE
PhantomJS running as server is missing parameters for content-type. 

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#2159]
Content-type is now determined by specifying the _outfile_ parameter.

`outfile: chart.jpg`

will result in returning a 64bit string representation of a _JPG_ image. 

more logical is to specify a content-type parameter. This won't work for PDF files. They have to be outputted to a file. See also [this](https://github.com/highslide-software/highcharts.com/issues/2137) related issue

**Comment by oysteinmoseng** [comment]
We now have content type support, closing this.
