### ISSUE TITLE
Regression in rendering legends with small fontsizes between highcharts 11.1 and 11.4

### ISSUE THREAD

**Issue by magnusanderson-wk** [highcharts/highcharts#21605]
#### Expected behaviour
Legend text rendering is centered with the text

#### Actual behaviour
Legend symbols shift downwards slightly with small `symbolHeight`

This is a regression introduced when the `LegendSymbol.LineItem`'s `verticalCenter` started being computed based on `symbolHeight` instead of `legend.fontMetrics.b`.

#### Live demo with steps to reproduce
current: https://jsfiddle.net/magnusandersonwk/b06t2gnL/63/
11.1: https://jsfiddle.net/magnusandersonwk/ae96gcdz/28/ 

another example:
current: https://jsfiddle.net/magnusandersonwk/b06t2gnL/59/
11.1: https://jsfiddle.net/magnusandersonwk/ae96gcdz/25/

This fiddle contains 11.4 but a fix which makes the rendering correct. There is just one line of code that needs to be updated.
https://jsfiddle.net/magnusandersonwk/b06t2gnL/54/

#### Product version
Highcharts 11.4
regression from
Highcharts 11.1

#### Affected browser(s)
Chrome
(probably others)

**Comment by karolkolodziej** [comment]
Hi @magnusanderson-wk! 

Thank you for reporting the issue.
@TorsteinHonsi you introduced this change with #20265, could you please tell if it was deliberate?

**Comment by TorsteinHonsi** [comment]
> TorsteinHonsi you introduced this change with https://github.com/highcharts/highcharts/pull/20265, could you please tell if it was deliberate?

@karolkolodziej Yes it was deliberate, but I don't remember the fail case. I thought it was when using larger fonts, but this too got worse after the change: https://jsfiddle.net/highcharts/3qd82sar/

I guess we just need to change it back in a draft PR and see what the visual diffs come up with.
