### ISSUE TITLE
Recursion issue with DataGrid dashboard

### ISSUE THREAD

**Issue by Maxime712** [highcharts/highcharts#21615]
With Highcharts Dashboards version 2.2.0, 
when using dataGridOptions: { useHTML: true } and scrolling, the table content gets repeated.

![Capture1](https://github.com/user-attachments/assets/a7c5d176-2af7-4434-9155-e93d4b7c95f9)

**Comment by Maxime712** [comment]
This is the code https://jsfiddle.net/vo9j24tb/

**Comment by karolkolodziej** [comment]
Hi @Maxime712!
Thank you for reporting the issue. Please set the PR with the fix.
