### ISSUE TITLE
annotations symbol and marker not working properly

### ISSUE THREAD

**Issue by FCNealVillangca** [highcharts/highcharts#21620]
#### Expected behaviour
annotation points supposed to have 10 radius square on start and end of the line and it was supposed to run a console.log in annotations.events.drag
docs: https://api.highcharts.com/highstock/annotations.events.drag
code: 
```
events: {
    drag: (e) => {
        console.log("asdfsdaf");
    },
},
```

#### Actual behaviour
But there symbol is not visible and the drag event listener is not working

#### Live demo with steps to reproduce
here I reproduce the code
[](https://jsfiddle.net/fcnavillangca/y3qphmsw/3/)

#### Product version
Im using Highstock charts

#### Affected browser(s)
Version 127.0.6533.89 (Official Build) (64-bit)

**Comment by hubertkozik** [comment]
Hi @FCNealVillangca! This issue has the same rootcause as https://github.com/highcharts/highcharts/issues/21501. The workaround for now is to set `pointer-events` to `auto` with important flag.

The fix is already merged into master branch, closing as a duplicate.

**Comment by FCNealVillangca** [comment]
> Hi @FCNealVillangca! This issue has the same rootcause as #21501. The workaround for now is to set `pointer-events` to `auto` with important flag.
> 
> The fix is already merged into master branch, closing as a duplicate.

thank you been in documentation for days :D

**Comment by hubertkozik** [comment]
@FCNealVillangca, can I ask you for some code to reproduce your issue with the symbol circle?

**Comment by hubertkozik** [comment]
@FCNealVillangca I was trying to reproduce your issue here: https://jsfiddle.net/BlackLabel/Lgztmys4/ based on official demos from here: https://api.highcharts.com/highstock/annotations and it looks to me, that everything is working correctly. The key is to use `setControlPointsVisibility` method.

**Comment by FCNealVillangca** [comment]
> @FCNealVillangca I was trying to reproduce your issue here: https://jsfiddle.net/BlackLabel/Lgztmys4/ based on official demos from here: https://api.highcharts.com/highstock/annotations and it looks to me, that everything is working correctly. The key is to use `setControlPointsVisibility` method.

thanks it works already.
