### ISSUE TITLE
discrepancy in the API documentation regarding type of the fontSize option

### ISSUE THREAD

**Issue by AndrzejBuleczka** [highcharts/highcharts#21624]
#### Expected behaviour

API documentation should properly explain, that for the fontSize option user can provide number which is then interpreted as the number of pixels, or any standard fontSize unit in the string, eg. '12px', '1em', '80%'

#### Actual behaviour
API documentation states that user can assign number and default setting is '0.8em', no other details provided:
![image](https://github.com/user-attachments/assets/9bd1b77b-10a1-42a5-b7a6-4ac3492100a6)

#### Live demo with steps to reproduce

https://jsfiddle.net/g2yLcpqm/
Showcase with different ways of setting fontSize in the comment

#### Product version

Highcharts 11.4.6

**Comment by tnafele** [comment]
If title is set to _useHTML_, fontSize as a number is ignored and only string values with a unit will have an effect.

Please check https://jsfiddle.net/s2q0kvhL/

You should either change the documentation accordingly if this is intended. Or correct the API.

**Comment by karolkolodziej** [comment]
Hi! Thank you both for starting this discussion.

We have two things here:
1. The documentation could be more precise on how the `fontSize` could be declared.
2. The way numbers are set in the `fontSize` differs between `SVGElement` and the `HTMLElement`- see how the `css()` method is implemented.

**Comment by Eskils** [comment]
Decided to add support for number as a fontSize when useHTML is true.

The documentation for fontSize will be changed so that the type shows `number, string`.
