### ISSUE TITLE
Stacking column - tooltip occurs after hiding series

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#21638]
#### Expected behaviour

No series visible, no tooltip, like in previous versions:

Demo: https://jsfiddle.net/BlackLabel/2y0smpen/

#### Actual behaviour

The tooltip occurs even if the series is hidden.

#### Live demo with steps to reproduce

steps to reproduce: hide all series with legend and hover on the point - the tooltip shows up

Demo: https://jsfiddle.net/BlackLabel/8dmszy2t/

**Comment by hubertkozik** [comment]
This issue has the same rootcause as https://github.com/highcharts/highcharts/issues/21501. The workaround for now is to set pointer-events to auto with important flag: https://jsfiddle.net/BlackLabel/o6ycqbp2/

The fix is already merged into master branch, closing as a duplicate.
