### ISSUE TITLE
Hidden Range Selector Dropdown Prevents Click on Range Selector Button in Chrome

### ISSUE THREAD

**Issue by sire-sam** [highcharts/highcharts#21633]
#### Expected behaviour

In a stock chart with a set of `rangeSelector.buttons`, I should be able to click on the first item to change the range, without the hidden "Range Selector Dropdown" obstructing the buttons.

#### Actual behaviour

In a stock chart with a set of `rangeSelector.buttons`, I cannot click on the first item to change the range because the hidden "Range Selector Dropdown" partially covers these buttons.

This issue is easier to observe if the `lang.rangeSelectorZoom` option is set to `undefined`.

#### Live demo with steps to reproduce
**Live demo**:  https://jsfiddle.net/bufnp3yL/36/

- In a Chrome browser _(see Affected Browser(s))_
- Try to click on the "Day" option of the Range Selector on the left side of the button.
- The click event is not triggered.
- Inspect with developer tools.
- Observe that an hidden element with the text "Week ▾" covers the button.

This element seems to be the dropdown variant of the "RangeSelector". 
Its wrapper has an attribute `visibility="hidden"`, which makes the element remain in the layout while being visibly hidden..

#### Product version
**Highstock**: `11.4.6`

#### Affected browser(s)
Google Chrome (Mac Os): Version 127.0.6533.100 (Official Build) (arm64)

(No issue in  Mac Os with Safari 17.4.1, or Firefox 128.0.3)

**Comment by bm64** [comment]
Hello @sire-sam and thanks for reporting the issue.

It looks like it used to work correctly in v11.4.3: https://jsfiddle.net/BlackLabel/9rmq7t61/

_Internal note:_
Bisected to: ce54038006395214dba5c3d71bd35f66cefc432f

**Comment by bm64** [comment]
@sire-sam actually it looks like it has been already fixed with https://github.com/highcharts/highcharts/pull/21531. The fix will be available with new Highcharts version.

**Comment by sire-sam** [comment]
Thank you for the quick response and for looking into this issue. 
I'm glad to hear that it's already been addressed with #21531. 

Looking forward to the next Highcharts release! 🎉
