### ISSUE TITLE
Discrepancy in the API documentation regarding yAxis: startOnTick default

### ISSUE THREAD

**Issue by tnafele** [highcharts/highcharts#21636]
#### Expected behaviour
The API documentation says the default for yAxis: _startOnTick_ is **enabled**.  But it's disabled by default.
(It's only enabled  by default for the **x**Axis.)

#### Actual behaviour
![Screenshot from 2024-08-07 16-09-35](https://github.com/user-attachments/assets/0e9c5316-9f81-4586-af08-5d3ff2df62c2)

#### Product version
Latest

**Comment by hubertkozik** [comment]
Hello!

Option `startOnTick` for the x-axis is set to `false` by default and it is correctly stated here: https://api.highcharts.com/highcharts/xAxis.startOnTick 
> Defaults to `false`.

Option `startOnTick` for the y-axis is set to `true` by default and it is correctly stated here: https://api.highcharts.com/highcharts/yAxis.startOnTick 
> Defaults to `true`.

The only inconsistency I can see is the name of the demo "False by default", but after checking the demo you can see, that the demo is about the x-axis.

 Maybe I am missing something, can you check it one more time if everything looks correct to you @tnafele?

**Comment by tnafele** [comment]
Oh, sorry you'r absolutely right!

I got confused because of a statement in a very old API documentation where it says for yAxis: _False by default, true on X axis._ But this statements belongs to the example chart link, not the option itself.

I'm migrating charts from V4 to V11 and I'm looking for the reason why the y-axis has different tick intervals with V11 in some cases...

**Comment by hubertkozik** [comment]
Sure thing @tnafele! If you need any help feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your charts.
