### ISSUE TITLE
Tooltips broken in 3D charts

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#21639]
Tooltips appear to be broken in 3D charts since 11.4.4. Worked in 11.4.3.

Live demo:
https://jsfiddle.net/oysteinmoseng/1sr026m8/2/

**Comment by hubertkozik** [comment]
This issue has the same rootcause as https://github.com/highcharts/highcharts/issues/21501. The workaround for now is to set pointer-events to auto with important flag: https://jsfiddle.net/BlackLabel/0exa3t16/

The fix is already merged into master branch, closing as a duplicate.
