### ISSUE TITLE
Typescript errors in version 11.4.6 , although code is running

### ISSUE THREAD

**Issue by abhidatta0** [highcharts/highcharts#21632]
#### Expected behaviour
No typescript errors

#### Actual behaviour
Shows typescript errors
Argument of type '{ chart: { type: string; }; title: { text: string; }; xAxis: { categories: string[]; }; yAxis: { title: { text: string; }; }; series: { name: string; data: number[]; }[]; }' is not assignable to parameter of type 'ChartCallbackFunction'.
      Object literal may only specify known properties, and 'chart' does not exist in type 'ChartCallbackFunction'.

#### Live demo with steps to reproduce
https://codesandbox.io/p/sandbox/goofy-volhard-v68927?file=%2Fsrc%2FBarChart.tsx%3A18%2C11

#### Product version
11.4.6

**Comment by hubertkozik** [comment]
Hi @abhidatta0! Sadly, your demo is not working due to permissions to access it, but I was trying to reproduce your problem here: https://codesandbox.io/p/sandbox/chart-ts-forked-irfxvj?file=%2Fsrc%2Fchart.tsx%3A152%2C41-152%2C66 and everything is working correctly. Can you check the permissions to your demo?

**Comment by abhidatta0** [comment]
I am trying to use highcharts package only without the highcharts-react .
I have made the codesandbox public now

**Comment by hubertkozik** [comment]
@abhidatta0 To get rid of the TypeScript error from your demo you should declare, that you are passing `Highcharts.Options`, like in this demo: https://codesandbox.io/p/sandbox/goofy-volhard-forked-6lprk4?file=%2Fsrc%2FBarChart.tsx%3A22%2C13 There is no bug for me.

In general, our official React integration was created to facilitate work on applications created in React. It allows you to use options with the use of a framework that significantly resembles the syntax of the code available from the Highcharts API. Of course, this is a code from the latest version of Highcharts and it is being executed under the hood. So this is the idea of our integrations, they are supported and constantly developed. You can learn more here: https://github.com/highcharts/highcharts-react

Of course, you can create applications without using our integration but then you lose many options and functions that are already available, you have to write it yourself actually as if you were creating your own wrapper, like in this case, but it all depends on your needs.
