### ISSUE TITLE
Missing values entries for some properties in `tree.json`

### ISSUE THREAD

**Issue by MikolajMichalczak** [highcharts/highcharts#21644]
#### Actual behaviour
Properties in `tree.json` that can accept different string values (e.g. `item.layout`: `"horizontal"` or `"vertical"`) should have their possible values explicitly listed in the `values` section . However, some properties only have these values mentioned in `description`.

#### Product version
Highchart v11.4.6

**Comment by karolkolodziej** [comment]
Hi @MikolajMichalczak We appreciate your feedback! 

You are right the typing could be more precise here: 
https://github.com/highcharts/highcharts/blob/7180a490cc94d7bcb96ba6288f4ee3bf4f23397a/ts/Series/Item/ItemSeriesOptions.d.ts#L175-L184

Changing it to: `layout?: 'horizontal'|'vertical';` should be enough. 

_Internal note:_
Identify similar cases and update the typing.
