### ISSUE TITLE
legend.labelFormatter should be called when series's visibility changes

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2165]
http://jsfiddle.net/W4EEg/12/

Toggle the series in the legend to see what I mean. The user maybe wants to change the color of the serie's name in the legend when toggled. This could be achieved if the `labelFormatter` is called when the serie toggles. That way, depending on the current serie's state (e.g. `this.visible`), an other string can be returned.

(`itemHiddenStyle` does not work in this case)

**Comment by pawelfus** [comment]
I agree, it suppose to work the same way as for pie chart: http://jsfiddle.net/W4EEg/24/
