### ISSUE TITLE
Doesn't work redraw of handles of navigator when we use url

### ISSUE THREAD

**Issue by FedichkinDenis** [highcharts/highcharts#21660]
#### Expected behaviour
When in navigator for handles set url of symbols after redraw there is not error

#### Actual behaviour
When in navigator for handles set url of symbols after redraw there is error `TypeError: Cannot read properties of undefined (reading 'call')`

#### Live demo with steps to reproduce
https://jsfiddle.net/GFDenis/o971fsr8/6/ - need press button "click me" for call redraw

#### Product version
Highstock v11.4.6

#### Affected browser(s)
Any browser for example Chrome

**Comment by pawellysy** [comment]
Hello @FedichkinDenis thanks for reporting the bug!

After a recent refactoring to improve the speed of updates of Stock modules we introduced this regression.
Related PR(https://github.com/highcharts/highcharts/pull/21194)

`Internal Note` 
The logic for rendering elements should take into consideration that the navigator can use symbols from the URL.
The relevant part of code: https://github.com/highcharts/highcharts/blob/master/ts/Stock/Navigator/Navigator.ts#L520
FYI @kamil-musialowski  :)

**Comment by kamil-musialowski** [comment]
Thanks for reporting the issue! I will release a pull request with a fix soon. In the meantime, @FedichkinDenis could you please try this workaround? Basically disable the navigator first, and then enable it with updated options. Of course, after PR gets merged there is no need to use the workaround.

```js
  btn.addEventListener("click", () => {
    chart.update({
      navigator: {
        enabled: false
      }
    }, false)
    chart.update({
      navigator: {
      	enabled: true,
        handles: {
          lineWidth: 3
        }
      }
    });
  });
```
