### ISSUE TITLE
plotLines.events demo not working

### ISSUE THREAD

**Issue by eczajk1** [highcharts/highcharts#21665]
#### Expected behaviour

`plotLines.events` callbacks should work.

#### Actual behaviour

They do not work.

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/plotlines-events/

This is the demo linked from the Highcharts website: https://api.highcharts.com/highcharts/xAxis.plotLines

#### Product version
Highcharts

**Comment by eczajk1** [comment]
Similar (related?) issue with `plotBands.events`: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/plotbands-events/

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! It was last working in v11.4.3.

**Comment by TorsteinHonsi** [comment]
@eczajk1 Actually it works for me with the latest release, v11.4.7. Can you confirm?  https://jsfiddle.net/highcharts/fhk1bnqw/

**Comment by hubertkozik** [comment]
@TorsteinHonsi This issue was fixed in this PR: https://github.com/highcharts/highcharts/pull/21531
