### ISSUE TITLE
Pivot Points Cause Annotation Tools to Shift and Disappear When Moved

### ISSUE THREAD

**Issue by tatiana-TS-BG** [highcharts/highcharts#21689]
#### Expected behaviour
When applying Pivot Points to a chart and using the drawing tools, the drawings should follow the cursor precisely without any offset. Furthermore, when trying to move a selected drawing, it should remain visible and move according to the cursor movement.

#### Actual behaviour
After applying Pivot Points to the chart and using drawing tools, the drawings appear shifted and do not follow the cursor accurately. Additionally, when attempting to move a selected drawing, the drawing disappears instead of moving as expected.

#### Live demo with steps to reproduce
[fiddle](https://jsfiddle.net/stealkvas/a4wrt01j/1/)

Steps to reproduce:

1. Load the chart in the provided fiddle.
2. Apply Pivot Points to the chart.
3. Select a drawing tool.
4. Start drawing on the chart – notice that the drawings are shifted and do not follow the cursor correctly.
5. Select the drawing and try to move it – the drawing disappears instead of moving.

https://github.com/user-attachments/assets/e37c8668-6b23-4e63-a62f-6fc395fc272f

**Comment by bm64** [comment]
Hi @tatiana-TS-BG thanks for reporting the issue.

As a workaround, you can set `ordinal: false` for xAxis: https://jsfiddle.net/BlackLabel/uv4po5rz/

**Comment by tatiana-TS-BG** [comment]
Hello @bm64! Yes, I see that it works correctly with `ordinal: false`, but unfortunately that doesn't fit our needs. We specifically need `ordinal` to be set to `true`.

Do you know of any other way this issue could be resolved?

**Comment by pawelfus** [comment]
@bm64 this seems to be a regression: https://jsfiddle.net/BlackLabel/nqmcw703/ (v9 works fine) - could you please bisect it? Thank you.

**Comment by bm64** [comment]
@pawelfus it looks like it used to work correctly in v10.3.2: https://jsfiddle.net/BlackLabel/067qnkaw/
Bisected to: 5c8073585fd11f1ecfa4e9e737219952bd1fc171

**Comment by pawelfus** [comment]
Something strange happens here. For the bisection resulting commit, I would expect the old workaround https://github.com/highcharts/highcharts/issues/18459#issuecomment-1551424002 to solve the problem. It does solve until 11.2.x versions, example: https://jsfiddle.net/BlackLabel/108jmhup/

All 11.3.x and 11.4.x are affected by something else. We will take a closer look in the upcoming weeks.

**Alternative workaround:**
Use v11.2.x version with the workaround: https://jsfiddle.net/BlackLabel/108jmhup/
