### ISSUE TITLE
pinchType is ignored

### ISSUE THREAD

**Issue by JohannesRudolph** [highcharts/highcharts#2168]
I was surprised to discover that the pinchType setting has no effect. I have some charts where I want to selectively disable pinching. I need the selection behavior, so I keep zoomType = x and prevent zooming in the selection event handler. 

Unfortunately, it seems impossible to set zoomType=x and pinchType='' and achieve the desired effect:

http://jsfiddle.net/j26fU/1/

On a side note, I have looked through the code and it seems I couldn't find any place where pinchType was actively checked/used to decide something!

**Comment by gregjacobs** [comment]
Just having the same issue. I have a chart that should only be panned in the 'x' direction, but not pinched. 

Says `pinchType` is available from v3.0, but I don't see it anywhere in the source code as well. Am I missing something?
