### ISSUE TITLE
when tooltip.outside is true then if hover then we are getting the scroll and tooltip is not visible fully

### ISSUE THREAD

**Issue by Mehafooz** [highcharts/highcharts#21698]
#### Expected behaviour
  we should not get scroll and see the full tooltip

#### Actual behaviour
getting scroll

#### Live demo with steps to reproduce

https://jsfiddle.net/kluvin/xthgz2jk/9

#### Product version

"highcharts": "^11.3.0"

#### Affected browser(s)
all

**Comment by karolkolodziej** [comment]
Hi! Thank you @Mehafooz for reporting the issue.

_Internal note:_
Last working version 10.3.3
Bisected to https://github.com/highcharts/highcharts/commit/df47f0d72e5ac6d2f625eba82c70f0aff2c1cf2a

**Comment by Mehafooz** [comment]
Hi @karolkolodziej , Any workaround available until it is fixed natively

**Comment by karolkolodziej** [comment]
Setting the SVG width explicitly does the trick- [demo](https://jsfiddle.net/mk6pct8s/) 
```css
.highcharts-tooltip-container svg {
  width: 100%;
}
```

**Comment by Mehafooz** [comment]
This issue still exists even with the latest highcharts version.

**Comment by hubertkozik** [comment]
Hi @Mehafooz! This issue has been fully fixed since Highcharts v12.0.0: https://jsfiddle.net/BlackLabel/hodyetk7/ The scroll is not appearing and the tooltip is squished into the visible area. Are you sure you are using the latest version of Highcharts? Maybe you have discovered a different bug?

**Comment by Mehafooz** [comment]
Hi @hubertkozik , In my local im using the html tooltip by enabling the useHtml true, using that im able to see the issue in my local, i will try to reproduce the issue in the jsfiddle .
