### ISSUE TITLE
Scatter patterns/ custom color outlining in 3-D Bar charts.

### ISSUE THREAD

**Issue by uditkumar09** [highcharts/highcharts#21716]
Hi,

We are testing implementation of your API into our application and we need to implement scatter patterns in the 3-D bar charts/ Border lining representation of bar charts, like in the image below:
![Highcharts-requirement](https://github.com/user-attachments/assets/b7466151-d7d7-4404-8384-c899759c8f31)

Can you suggest possibility for these conditional scatter patterns/Border lining bar charts in the HighCharts API?

Also which purchase plan will provide for my application with all the above and 3-D chart Tooltip feature?

Finally,  Are all chart options in the screenshots included under SaaS - Highcharts core License? What is your recommendation?

**Comment by karolkolodziej** [comment]
Hi @uditkumar09! 
Thank you for reaching out. This topic has been discussed on the forum: [link](https://www.highcharts.com/forum/viewtopic.php?p=194246#p194246). Please continue the discussion there.

GitHub is typically reserved for bug reports and feature requests. If you encounter an issue or have a feature suggestion, feel free to open a new ticket.
