### ISSUE TITLE
Map with Marker Clusters can have clusters moved to incorrect location when zooming

### ISSUE THREAD

**Issue by CallumES** [highcharts/highcharts#21728]
We have noticed that the marker clusters on a map can move locations (to an incorrect location) when zooming in and out. This was originally logged as https://support.highcharts.com/support/tickets/25624 from which I have been guided to log a ticket here after a Support Engineer confirmed that they could replicate.

https://github.com/user-attachments/assets/9f7ac1e6-25a2-4e5f-aee0-0cc306f60697

Please see the attached video that has been replicated on one of your examples: https://www.highcharts.com/demo/maps/marker-clusters?redirect-to-jsfiddle 

#### Expected behaviour
Marker clusters retain position when zooming in and out

#### Actual behaviour
Marker clusters change position incorrectly when zooming in and out and move to areas of the map that they should not be located at.

#### Live demo with steps to reproduce
See attached video or can be replicated on https://www.highcharts.com/demo/maps/marker-clusters?redirect-to-jsfiddle 

#### Product version
HighCharts Maps, latest version as per HighCharts website

#### Affected browser(s)
Chrome

**Comment by hubertkozik** [comment]
Hi @CallumES! I can recreate this bug even in Highcharts Maps v10.0.0 when native support for TopoJSON was introduced. Let's treat it as a bug, not a regression.
