### ISSUE TITLE
Minor ticks distribution failure for multiple axes.

### ISSUE THREAD

**Issue by ddragula** [highcharts/highcharts#21734]
#### Actual behaviour
When minor ticks are enabled on both axes, they are misaligned and do not match even in cases where they absolutely should (same extremes on both axes).

#### Live demo with steps to reproduce
The same extremes: https://jsfiddle.net/BlackLabel/fda8vqyL/
The same extremes with `allowDecimals`: https://jsfiddle.net/BlackLabel/38ghz4sa/
Different extremes, the same `minorTicksPerMajor`: https://jsfiddle.net/BlackLabel/4edwq3zf/

#### Product version
Highcharts v11.4.7

Failed to bisect, last working version: `v10.0.0`

**Comment by TorsteinHonsi** [comment]
Simplified to one axis with a `tickAmount`: https://jsfiddle.net/highcharts/mbgy2wpn/
Bisected to https://github.com/highcharts/highcharts/commit/445c8dd78f4e451e53f1adb2f8ce096e83aa5ba2
