### ISSUE TITLE
Click events called when releasing the mouse after a drag when multiple charts are rendered on the same page

### ISSUE THREAD

**Issue by jcrang** [highcharts/highcharts#21745]
Click events are called when releasing the mouse after a drag. This only occurs when multiple charts are rendered on the same page.

#### Expected behaviour

- Click event is not called after a drag over the chart area

#### Actual behaviour

- Click event is called after a drag over the chart area

#### Live demo with steps to reproduce

1. Mouse down in either chart area
2. Move the mouse pointer within the same chart
3. Release the mouse

https://jsfiddle.net/pcv7ng2L/

#### Product version

Highcharts 11.4.7 and later. Highcharts 11.4.6 and earlier are unaffected.

#### Affected browser(s)

Reproduced in Chrome 128.0.6613.85 and Firefox 129.0.2

**Comment by hubertkozik** [comment]
Hi @jcrang! Thank you for reporting the issue.

I have created a workaround for this problem until it will be fixed natively: https://jsfiddle.net/BlackLabel/pbkgowj2/ If you want to use it in your project you can copy-paste the IIFE plugin.

_Internal note_
Bisected to 9c02941e079639640fbfad25ff27af5405ad5058.

**Comment by jcrang** [comment]
The IIFE has fixed the problem for me. Happy for you to close this issue as resolved.

Thanks for such a quick fix and the workaround!
