### ISSUE TITLE
Plotlines are not showing up properly when tickAmount is set

### ISSUE THREAD

**Issue by hor1903** [highcharts/highcharts#21751]
#### Expected behaviour
Show Plotlines at all values, when tickAmount is set
![image](https://github.com/user-attachments/assets/2da352b0-f8e6-4cb0-8ff9-66bedb870da1)

#### Actual behaviour
Plotlines are shown properly at all values between two ten steps, but not at the ten steps. See fiddle for detailed info

![image](https://github.com/user-attachments/assets/c143bb3c-cc6d-49f6-947b-98d2be099396)

#### Live demo with steps to reproduce

https://jsfiddle.net/hor1903/5cy2n1a6/17/
Comment out line 36, to see the plotlines at 49 and 50. If line 36 is present, the plotline at 50 wont show up.

#### Product version

Checked at 11.2.0 and 11.4.8

#### Affected browser(s)
Edge

**Comment by hubertkozik** [comment]
Hi @hor1903! In the demo you have provided the plot line is hidden behind the y-axis grid line. If you check the API docs you can see, that y-axis grid z-index is by default set to `1`: https://api.highcharts.com/highcharts/yAxis.gridZIndex and plot line z-index is set to `undefined`: https://api.highcharts.com/highcharts/yAxis.plotLines.zIndex

If you declare a z-index for plot line everything works as expected: https://jsfiddle.net/BlackLabel/rho5cpvs/
