### ISSUE TITLE
incomplete changelogs

### ISSUE THREAD

**Issue by DanielRuf** [highcharts/highcharts#21754]
It seems changelog entries are missing, for example at https://github.com/highcharts/highcharts/blob/master/changelog/highcharts/11.4.8.md

 But PRs like https://github.com/highcharts/highcharts/pull/21737 have no labels, so the generation doesn't pick them up.
 
 There are probably more PRs, which slipped through the changelog generation due to the pr-log filter logic: https://github.com/highcharts/highcharts/pulls?q=is%3Apr+no%3Alabel+is%3Aclosed

**Comment by hubertkozik** [comment]
Hi @DanielRuf! Thank you for reporting the problem. We will run the changelog generator one more time with updated labels in those specific PRs :)
