### ISSUE TITLE
"geoheatmap" series disappear after enable interpolation

### ISSUE THREAD

**Issue by zhangmengjie-amy** [highcharts/highcharts#21771]
#### Expected behaviour
After I set interpolation enabled to true, the "geoheatmap" series will display with blur style.

#### Actual behaviour

when I set the interpolation enabled to false, the series can display but no blur style,
but the "geoheatmap" series disappear after enable the interpolation

#### Live demo with steps to reproduce
![image](https://github.com/user-attachments/assets/ca11b1fd-29d5-4762-8618-d9cf83dd133f)
https://codesandbox.io/p/sandbox/45zycf?file=%2Fsrc%2FApp.js%3A41%2C9

#### Product version
11.4.8

#### Affected browser(s)
google

**Comment by hubertkozik** [comment]
Hi @zhangmengjie-amy! Sadly, I don't have permission to check your demo, can you share it one more time?

**Comment by zhangmengjie-amy** [comment]
Hi, I set the permission to public, please load it again.

**Comment by zhangmengjie-amy** [comment]
> Hi @zhangmengjie-amy! Sadly, I don't have permission to check your demo, can you share it one more time?

Hi, I set the permission to public, please load it again.

**Comment by hubertkozik** [comment]
@zhangmengjie-amy, thank you for the demo. The problem relies in the data used in GeoHeatmap series, the data should be set as a "grid" accordingly to `rowSize` and `colSize` options: https://api.highcharts.com/highmaps/series.geoheatmap.rowsize You can find an example of "grid" in your demos e.g.: https://www.highcharts.com/demo/maps/geoheatmap-orthographic

If you change the data, everything is working correctly: [https://codesandbox.io/p/sandbox/heatmap-forked-75hcq9?workspaceId=07b5692a-7c9d-48a7-b810-62e1833b90d4](https://codesandbox.io/p/sandbox/heatmap-forked-75hcq9?workspaceId=07b5692a-7c9d-48a7-b810-62e1833b90d4&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0m5efuh00073b6jwuwhhe6r%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0m5efuh00033b6j1fvzfuuw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0m5efuh00043b6j5uiql7yz%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0m5efuh00063b6jkiirnbcb%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0m5efuh00033b6j1fvzfuuw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0m5efuh00023b6j32j32nm2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A23%252C%2522startColumn%2522%253A70%252C%2522endLineNumber%2522%253A23%252C%2522endColumn%2522%253A70%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0m5efuh00033b6j1fvzfuuw%2522%252C%2522activeTabId%2522%253A%2522cm0m5efuh00023b6j32j32nm2%2522%257D%252C%2522cm0m5efuh00063b6jkiirnbcb%2522%253A%257B%2522id%2522%253A%2522cm0m5efuh00063b6jkiirnbcb%2522%252C%2522activeTabId%2522%253A%2522cm0nntjxi000v3b6jaelqfxpb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0m5efuh00053b6jb60v74be%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm0nntjxi000v3b6jaelqfxpb%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0m5efuh00043b6j5uiql7yz%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0m5efuh00043b6j5uiql7yz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

I don't see a bug here, to me it's just a misconfiguration of the chart.
