### ISSUE TITLE
Tick-length difference in Highcharts version 11.4.1

### ISSUE THREAD

**Issue by aditya3434** [highcharts/highcharts#21770]
I have a particular chart that gives tick-length 1 on render in Highcharts 10.3.3. However, in version 11.4.1, the tick-length becomes 2, creating a lot of whitespace. Although I can explicitly set the tick-length as 1, I would rather have a more generic solution to revert the tick-length calculation method to what it was in version 10.3.3, as this is affecting other charts in the project as well.

#### Live demo with steps to reproduce
[jsFiddle demo](https://jsfiddle.net/ht3ruem2/9/)

![Animation](https://github.com/user-attachments/assets/6c0aab21-ba2e-44da-b0f4-d4ef90db3838)

#### Product version
Highcharts v11.4.1

**Comment by hubertkozik** [comment]
Hi @aditya3434!

In Highcharts v11.0.0 we introduced a design facelift with many minor visual changes and in Highcharts v11.3.0 we added new option [chart.axisLayoutRuns](https://api.highcharts.com/highcharts/chart.axisLayoutRuns). It allows opting in for more predictable axis tick and label layout, at the cost of performance. Those two changes are impacting the look of your chart. 

There is no solution to revert this logic, you can control the interval of the axis ticks by using [`tickIntreval` option](https://api.highcharts.com/highcharts/yAxis.tickInterval), like in this demo: https://jsfiddle.net/BlackLabel/78s3145g/

**Comment by aditya3434** [comment]
Hi @hubertkozik!

Thanks for the quick response! It seems like the calculated tick length is very sensitive to the data displayed in the chart. This example can just be considered as an edge case.
