### ISSUE TITLE
Chart.reflow() not working for me.

### ISSUE THREAD

**Issue by sharmankita** [highcharts/highcharts#21788]
Hi Can anyone help me with this. I recently have update highcharts version from 9th to 11 everything was almost working fine except one thing that is reflow().

My requirement is my dashboards are resizable so once any div gets resized charts are not getting resized.. reflow is not working. is i m using resize chart is getting adjusted but legends and chart title are not changing as per the responsive array.

**Comment by hubertkozik** [comment]
Hi @sharmankita! We use GitHub as a tool for bugs/feature request tracking and your question is strictly a support question. Feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
