### ISSUE TITLE
Series are hiding when i click it on the legend

### ISSUE THREAD

**Issue by Mehafooz** [highcharts/highcharts#21791]
#### Expected behaviour
when i click on the legend , i dont what the series to hide

#### Actual behaviour
series is hiding

#### Live demo with steps to reproduce
https://jsfiddle.net/ko7vy8b9/

#### Product version
Highcharts:11.3.0

#### Affected browser(s)
all

**Comment by Mehafooz** [comment]
i want to do some other operations when i click the series in the legend  instead of hiding the legend, is there any workaround for it.

**Comment by hubertkozik** [comment]
Hi @Mehafooz! As you can read in our documentation: https://www.highcharts.com/docs/chart-concepts/legend 

> Series can be disabled and enabled from the legend.

This is a desired behaviour and it is not a bug. If you want to fire some custom logic after clicking you can use `legend.events.itemClick` callback function.

**Live demo:** https://jsfiddle.net/BlackLabel/guLxa49q/
**API Reference:** https://api.highcharts.com/highcharts/legend.events.itemClick

We use GitHub as a tool for bugs/feature request tracking and your question is strictly a support question. Feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
