### ISSUE TITLE
Highcharts pointwidth is rounded off to ceil value

### ISSUE THREAD

**Issue by technikhil314** [highcharts/highcharts#21804]
#### Expected behaviour
The custom passed pointwidth should be respected as passed value with decimal precision

#### Actual behaviour
Currently the point width is rounded of to its ceil value

#### Live demo with steps to reproduce
https://jsfiddle.net/d6boyk0u/

> Here the value of pointWidth I want is 180.05 as its most fit value with minimum gap in bars without overlaps. But since its ceiled that bars are overlapping. 

#### Product version
Latest

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
Hi! Thank you for reaching out with this.

As far as I see this behaviour is deliberate and is designed to make the columns smooth see.
The dimensions are calculated here: 
https://github.com/highcharts/highcharts/blob/d6f1c2778d4f73cff7425d3fdaa2408a81d853fa/ts/Series/Column/ColumnSeries.ts#L611-L619

With this method:
https://github.com/highcharts/highcharts/blob/d6f1c2778d4f73cff7425d3fdaa2408a81d853fa/ts/Series/Column/ColumnSeries.ts#L345-L368

_Internal note:_
[Demo with logs](https://jsfiddle.net/cqj3udt7/)
[Also `crisp` doesn't solve the issue](https://jsfiddle.net/j83bLs1z/)
@TorsteinHonsi Any opinion?

**Comment by technikhil314** [comment]
When I changed these lines 
from
https://github.com/highcharts/highcharts/blob/7170f922796bd196225faf36c8c622125ebab37d/ts/Series/Column/ColumnSeries.ts#L500C8-L502
to 
https://github.com/technikhil314/highcharts/blob/master/ts/Series/Column/ColumnSeries.ts#L500C8-L502

it got fixed. Obviously need to add check for crisp option too. Please let me know your thoghts. @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
@technikhil314 That seems like the right spot! Arguably the width could still be subject to crisping even if `pointWidth` is set, but we definitely need the check for `options.crisp`. @karolkolodziej ☝️

**Comment by technikhil314** [comment]
yeah will change the condition to `options.pointPadding && defined(this.options.pointWidth) && !this.options.crisp`. I believe that should work. Let me know.

**Comment by technikhil314** [comment]
@TorsteinHonsi We are still using v7.2.2. Just wanted to know if (and how) this can be released as next patch for 7.2.2?

**Comment by TorsteinHonsi** [comment]
That is a very old version, I strongly recommend you upgrade.

If not, you can probably apply a drop-in fix, something like this:
https://jsfiddle.net/highcharts/dz31wa7m/

**Comment by technikhil314** [comment]
yeah it's old. hence was wondering if such releases even happen or not. sure let me take it up with my team to see what is feasible for us. thanks a ton for quick acknowledgement on issue,prompt replies and equally quick merge on the PR.

**Comment by technikhil314** [comment]
hey @TorsteinHonsi when shall we expect next release?? we need this fix as we are ready to upgrade to v11. is there any tantetive date you can share that would great. thanks.

**Comment by TorsteinHonsi** [comment]
@technikhil314 We will run a new release within a few weeks. However, you can also run the drop-in fix on the current version.
