### ISSUE TITLE
When plotOptions.line.dataGrouping is enabled, connectNulls:false does not work

### ISSUE THREAD

**Issue by auoiuiouio** [highcharts/highcharts#2180]
connectNulls:false doesn’t work when there is two kinds of plots (i.e. line and column) having many points and plotOptions.line.dataGrouping is enabled. Here is an example that has nulls... you can see how it dips down to zero where the null values are present:
http://jsfiddle.net/efvQp/3/

This example shows gap when there is null values, when plotOptions.line.dataGrouping is disabled. 
http://jsfiddle.net/efvQp/7/

**Comment by ttelfer** [comment]
I can also confirm dataGrouping caused issues with nulls not being rendered properly. Once dataGrouping was disabled the problem disappeared.

**Comment by sebastianbochan** [comment]
Hi @ttelfer 
Thank you for the reporting.
