### ISSUE TITLE
Zooming in X direction in scatter chart with boost mode does not show the correct points

### ISSUE THREAD

**Issue by Saayanel** [highcharts/highcharts#21815]
#### Conditions
Scatter chart with boost mode enabled, and **at least 300 points**

#### Expected behaviour

When zooming in X direction, the points showed should be the ones included in the zoom range

#### Actual behaviour
The points showed are always the first points of the serie

#### Live demo with steps to reproduce
[https://jsfiddle.net/nfkbudm6/4/](https://jsfiddle.net/nfkbudm6/4/)

1. Zoom between the range 40-60 in the X axis
2. Mouse over the points to show the tooltip
3. The points displayed are not in the range 40-60, they are the first points of the serie

#### Product version
**11.4.8**
Bug is not present in 11.2.0, and is present in 11.3.0

**Comment by karolkolodziej** [comment]
Hi @Saayanel! 
Thank you for reporting the issue.

Internal note:
Bisected to: https://github.com/highcharts/highcharts/commit/bdb042fd71e1c8bc23f92db5cb3ca0dc7daea14b

**Comment by Saayanel** [comment]
Maybe related to #20621

**Comment by karolkolodziej** [comment]
Hi @manoj-voonna. Thank you for the additional context.
