### ISSUE TITLE
When chart is in styledMode, tooltip has transparent background and dataLabels bleed through

### ISSUE THREAD

**Issue by a688** [highcharts/highcharts#21829]
#### Expected behaviour
Tooltip should have solid background just like it does in non styled mode

#### Actual behaviour
Tooltip has transparent background

#### Live demo with steps to reproduce
https://codepen.io/Joshua-Lonberger/pen/BagEzev

#### Product version
Current (linking directly to https://code.highcharts.com/ files in demo)

#### Affected browser(s)
Chrome/Edge

**Comment by karolkolodziej** [comment]
Hi @a688! 

This is because some of the elements are still rendered with SVG despite the `useHTML`. 
To fix this, please set the [tooltip.outside ](https://api.highcharts.com/highcharts/tooltip.outside)to true- [demo](https://jsfiddle.net/BlackLabel/vrua9dec/1/).
