### ISSUE TITLE
Gantt chart with xAxis min/max and navigator/scrollbar jumps when dragging items

### ISSUE THREAD

**Issue by ebencollins** [highcharts/highcharts#21825]
#### Expected behaviour
Dragging an item does not affect the extremes unless dragged off the side.

#### Actual behaviour
Any dragging interaction with any of the items sets the zoom extremes to match the data.

#### Live demo with steps to reproduce
Create an interactive Gantt chart, set `xAxis.min` to be lower than the first data point, and enable either the navigator or scrollbar. Interact with (drag) any point and observe that the extremes have changed to match the data.

Note: the same thing happens if `xAxis.max` is set to a value larger than the latest point. There is no issue if both scrollbar and navigator are disabled.

https://jsfiddle.net/2s7rzqo8/

https://github.com/user-attachments/assets/adda6f7c-b22c-4aea-aec8-47629d29aff6

https://github.com/user-attachments/assets/62ca8fbf-1258-4904-861b-f29a8af1788a

#### Product version
v11.4.8

#### Affected browser(s)
Confirmed with Chrome 126, Firefox 127

**Comment by karolkolodziej** [comment]
Hi @ebencollins! 
Thank you for reporting the issue.

A similar one was already reported here: https://github.com/highcharts/highcharts/issues/14314
I will close this for now as a duplicate, but if you have anything to add please do it under the older issue. 
I know the status is `won't fix` but I will bring this once again to the team an we will discuss what is possible.
