### ISSUE TITLE
Rebbon Chart 

### ISSUE THREAD

**Issue by sumitsp7** [highcharts/highcharts#21843]
provide Rebbon chart , it is very useful .

----
![Screenshot 2024-09-13 160651](https://github.com/user-attachments/assets/24202d73-a531-4a4f-9cd1-f8a64daf4dc5)

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by karolkolodziej** [comment]
Have you tried using the `sankey` series- [see the demo.](https://www.highcharts.com/demo/highcharts/sankey-diagram)
It looks identical, with a bit of styling you can achieve that.

**Comment by sumitsp7** [comment]
i have tried but not getting result which i want.. can you provide demo for that how can i achive it ?

**Comment by karolkolodziej** [comment]
We usually use GH for bug and feature requests. With a bit of customization, I believe this could be achieved without bigger code modifications.
Please get in touch with [our support team](https://www.highcharts.com/blog/support/)- they will help you achieve it.
