### ISSUE TITLE
Boost does not work with Treemap since 11.3.0

### ISSUE THREAD

**Issue by jszuminski** [highcharts/highcharts#21863]
#### Expected behaviour
Boost should work with Treemap as in 11.2.0 and other previous versions: https://jsfiddle.net/vn3m6L7f/

#### Actual behaviour
In our docs (https://www.highcharts.com/docs/advanced-chart-features/boost-module), at the bottom of the page there is a link to a sample with Treemap: https://www.highcharts.com/samples/highcharts/boost/treemap which does not work since 11.3.0.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/078gv2zj/

#### Product version
Since Highcharts 11.3.0

***Internal note***: Bisected to https://github.com/highcharts/highcharts/commit/a67ba29717127638d1e1c742b16bcb6f50e25986 FYI @bre1470

**Comment by bre1470** [comment]
Thank you for the report. It looks like line 1431 in the bisects BoostSeries has to exclude treemap. Or `scatterProcessData` needs a fix.
