### ISSUE TITLE
Measure Annotation:  Issue with rendering the border on stocktools

### ISSUE THREAD

**Issue by umeshdewanganctr** [highcharts/highcharts#21884]
#### Expected behaviour
1. Border/Stroke should render for all sides.
2. Left, right, top and bottom of the stroke width should be consistent
![Screenshot 2024-09-20 163317](https://github.com/user-attachments/assets/2b918023-3b6a-4d07-85cc-08b24bbfcd69)

#### Actual behaviour
1. Border/Stroke is not rendering for left side. Check the attached screenshot
2. Inconsistent stroke width for horizontal and vertical sides
![Screenshot 2024-09-20 163850](https://github.com/user-attachments/assets/c79c9326-1fe3-4730-8fd1-88db2a48f992)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/0p4zuy82/

#### Product version
Highstock JS v11.4.8 (2024-08-29)

#### Affected browser(s)
All Browers chrome, edge etc.

**Comment by bm64** [comment]
Hi @umeshdewanganctr,

Thanks for reporting the issue. It will be prioritized and should be fixed within the next few weeks. Meanwhile, here's a workaround you can use: https://jsfiddle.net/BlackLabel/yc98p61n/

**Comment by umeshdewanganctr** [comment]
Thanks, @bm64, for providing the workaround! It’s really helpful.
