### ISSUE TITLE
Parallel coordinates + scrollable plot area not working as in 11.1.0

### ISSUE THREAD

**Issue by jiigen3343** [highcharts/highcharts#21890]
#### Expected behavior
So I am not 100% sure this is a bug or feature request, but historically we have used the width property of the parallel axis to ensure a certain amount of space between the parallel axis in combination with scrollable plot area to handle some of the parallel coordinate plots in our app that have a considerable number of axes (it is not uncommon to have 50-100 axes in the data sets being plotted).

we would combine that with an override for the move fixed elements that looks like: https://jsfiddle.net/BlackLabel/0kfqa58s/ (which was suggested to a coworker of mine from a forum post here: (https://www.highcharts.com/forum/viewtopic.php?f=9&t=42115&p=147659&hilit=parallel#p147659) to allow smooth scrolling of the parallel coordinates plot axis labels.

this seems to work in the current version we are using 11.1.0 but as we are attempting to upgrade to 11.4.X we have noticed that the width setting no longer changes the placement of the axis lines but still affects the labels. so we are unclear what we should be doing.

#### Actual behavior
the width setting no longer changes the placement of the axes lines but does change the location of the axis labels.

#### Live demo with steps to reproduce
current version demo: https://jsfiddle.net/sk302y8g/1/
11.1.0 version: https://jsfiddle.net/sg3wkqhx/1/

note I did not include our label module mentioned above in this reproduction but that is still working the way we intend if you would like me to combine the demos please let me know.

#### Product version
11.4.X

#### Affected browser(s)
tested in Chrome latest and Safari latest

**Comment by hubertkozik** [comment]
Hi @jiigen3343! Thank you for reporting the issue. It looks like a regression.

The last working version is Highcharts v11.3.0.

_Internal note_
Bisected to 3d934e0404f0cd3bc822eb867b8a5c6f08e988cd.
