### ISSUE TITLE
Negative UTC offsets with minutes (like -09:30) is calculated wrong

### ISSUE THREAD

**Issue by jessevdp** [highcharts/highcharts#21900]
I think there is a bug on the following line:

https://github.com/highcharts/highcharts/blob/b8592a5a4cfdce5283b9e867aae11e2fbfbd0bcb/ts/Core/Time.ts#L433

## Negative offset that is not round (`-09:30`)

```js
const timestamp = new Date(Date.UTC(2024, 9, 25, 4, 20, 00, 000));
const format = new Intl.DateTimeFormat('en', {
    timeZone: '-09:30',
    timeZoneName: 'shortOffset',
})

const [date, gmt, hours, colon, minutes = 0] = format.format(timestamp)
  	.split(/(GMT|:)/)
  	.map(Number)

console.log(hours)
// -> -9
console.log(minutes)
// -> 30
console.log(minutes / 60)
// -> 0.5
console.log(-(hours + minutes / 60))
// = - ( -9 + 0.5 )
// -> 8.5
```

## Positive offset that is not round (`+09:30`)

```js
const timestamp = new Date(Date.UTC(2024, 9, 25, 4, 20, 00, 000));
const format = new Intl.DateTimeFormat('en', {
    timeZone: '+09:30',
    timeZoneName: 'shortOffset',
})

const [date, gmt, hours, colon, minutes = 0] = format.format(timestamp)
  	.split(/(GMT|:)/)
  	.map(Number)

console.log(hours)
// -> 9
console.log(minutes)
// -> 30
console.log(minutes / 60)
// -> 0.5
console.log(-(hours + minutes / 60))
// = - ( 9 + 0.5 )
// -> -9.5
```

## Conclusion

Shouldn't the 1st case (`"-09:30"`) result in a value for offset of `9.5`?
The minutes are added to the hours when they should be subtracted. (Because we're dealing with a negative offset.)

**Comment by jessevdp** [comment]
I’ve given this some more thought. The issue here is that in parsing the hours and minute offsets separately the minus sign is attached to the hour and not applied to the minutes.

```
"-09:30"
"-09", "30"
-9, 30
```

If we parse out the “is this a negative or positive offset” separately, we would get something like:

```js
let [sign, hours, minutes] = ["-", 9, 30]
let isNegativeOffset = sign == "-"

if (isNegativeOffset) {
  hours = hours * -1
  minutes = minutes * -1
}

let offset = -( hours + ( minutes / 60 ) )
// -( -9 + ( -30 / 60 ) ) = 9.5
```

**Comment by karolkolodziej** [comment]
Hi @jessevdp! 
Thank you very much for such a detailed explanation- It makes a lot of sense.

FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
I agree, here's an example of the bug with the current release: https://jsfiddle.net/highcharts/vytk0w4b/

Fortunately, this seems to be fixed along with the great Time refactor of the upcoming version 12: https://jsfiddle.net/highcharts/vytk0w4b/2/

**Comment by jessevdp** [comment]
I’m glad my explanation was helpful 😄
