### ISSUE TITLE
Bug: Time series with lots of data draw an extra line in the graph

### ISSUE THREAD

**Issue by hakontro** [highcharts/highcharts#21908]
#### Expected behaviour
Show a line plot

#### Actual behaviour
The line plot has a final data point placed in the middle of the graph, that shouldn't be there
![image](https://github.com/user-attachments/assets/712c80d0-23c1-4d9f-b587-f30693f13162)
![image](https://github.com/user-attachments/assets/49710ea4-d38c-435d-82d1-d1b018dc6056)

#### Product version
"highcharts": "^11.4.6",
"highcharts-react-official": "^3.2.1",
Line Chart

#### Affected browser(s)
Firefox, Chrome

As described! Has this been seen before, is there something I can do to avoid it?

**Comment by karolkolodziej** [comment]
Hi @hakontro! 

Are you sure about the data integrity and its order? Don't you have any errors in the console?
At first glance, it looks like the data is not in order.

**Comment by hakontro** [comment]
No, you're right, it's not. Thanks, and apologies, closing this.
