### ISSUE TITLE
`ResetZoomButton` does not dissapear when programatically you reset zoom

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#21907]
#### Expected behaviour
The zoom button should disappear, when you reset zoom other way then clicking the button.

#### Actual behaviour
The reset zoom persists, even when the extremes are set back to the default values.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/wyh06x38/1/

1. Zoom with drag.
2. Click HTML button below the chart.

Result -> The extremes are back to default values, but resetZoomButton is still visible

#### Product version
v11.4.8

#### Affected browser(s)
all

**Comment by KacperMadej** [comment]
**Workaround:** use [`chart.zoomOut`](https://api.highcharts.com/class-reference/Highcharts.Chart#zoomOut) - https://jsfiddle.net/BlackLabel/wyh06x38/3/

**Comment by KacperMadej** [comment]
Using `zoomOut` linked and demonstrated above is the recommended way of handling the case described in this issue.
Closing as answered question. However, if you disagree please leave a comment and this issue could be reopened.
