### ISSUE TITLE
Data generator for MQTT

### ISSUE THREAD

**Issue by jomar-honsi** [highcharts/highcharts#21912]
# Description of the feature
For the _Dashboards MQTT connector tutorial/demo_ there is need for software that generates data. The SW has already been developed so this request pertains to the following:

- To which _repo and directory_ should this SW be committed ? (at the moment it is a single HTML web page).
- For ease of use it would be an advantage to deploy it on a Highsoft server.

Note: the data generator does not rely on any Highcharts components.

**Comment by goransle** [comment]
@TorsteinHonsi any thoughts? Could potentially just be in `samples/` somewhere while it is a HTML-based tool.

**Comment by jomar-honsi** [comment]
It is a single HTML file with embedded JS that generates random data. So the file itself is static but ... 
![image](https://github.com/user-attachments/assets/4ee17bde-0e93-44d7-aa3b-10f7909bddca)

**Comment by oysteinmoseng** [comment]
@jomar-honsi Is this a mini-application customers should have access to, or can we just run the JS in the background on a server to post data every 5 seconds constantly?

**Comment by jomar-honsi** [comment]
@oysteinmoseng it could be both, but it would be easier to administrate if we run the JS in the background.

**Comment by jomar-honsi** [comment]
It works! I have also requsted access to https://github.com/highcharts/live-data-generator where the script is stored.
