### ISSUE TITLE
boost module not effective with stacked area chart

### ISSUE THREAD

**Issue by AndrzejBuleczka** [highcharts/highcharts#21911]
#### Expected behaviour
Rendering the chart and showing/hiding particular series in a stack chart should perform as well as not stacked charts with boost module enabled

#### Actual behaviour
Stacked area chart with many series and many points in it performs slowly when hiding/showing particular series with boost module enabled; non-stacked charts perform much better

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/ukqap16y/
Click on a few series in a legend to toggle visibility and note the time

Possible workaround - simulate stacking 
**Live demo with a workaround:** https://jsfiddle.net/BlackLabel/m9bv5ztx/

#### Product version
Highcharts Core

**Comment by hubertkozik** [comment]
One of Boost Module's current limitations is that we do not support stacking.

Official information can be found here, under **Caveats** header: https://www.highcharts.com/docs/advanced-chart-features/boost-module
> Stacking, and negative colors are not supported.
