### ISSUE TITLE
Zoom with bubbles with ordinal set to true doesn't pick the correct date range

### ISSUE THREAD

**Issue by ck-coatue** [highcharts/highcharts#21916]
#### Expected behaviour

1. Create a large line chart with many years of data and bubbles, range selector set to YTD and ordinal set to true.

2. Zoom by dragging a selection on the chart while it's on YTD (or any date range that's much smaller than the whole dataset).

3. The chart should zoom to the correct date range (e.g. if YTD is 2024, the date range should be within 2024).

#### Actual behaviour

It picks a totally different date range (generally around where the bubbles begin, so if your bubble data starts in 2015, that's where the date range will be.

#### Live demo with steps to reproduce

https://jsfiddle.net/khoomeister/hLsuejmo/1/

#### Product version

Highcharts Stock & More 11.4.8

#### Affected browser(s)

I'm using Chrome 129.

Might be related to https://github.com/highcharts/highcharts/issues/17128

**Comment by pawellysy** [comment]
Hey @ck-coatue, thanks for reporting a bug!

We already noticed that one, and it will be fixed by #21876.

Here is the workaround: https://jsfiddle.net/BlackLabel/h54dop8f/

**Comment by ck-coatue** [comment]
Thanks @pawellysy!  I tried the workaround.  It is more accurate, but still fairly inaccurate when you zoom in on large date ranges.

For example, if you open the workaround jsfiddle (i.e. https://jsfiddle.net/BlackLabel/h54dop8f/) and try the following:

1. Select "All" date range.
2. Put cursor inside the chart and note the starting date by the tooltip bubble.
3. Drag a selection to zoom.  The bigger the date range, the more inaccurate the start date is.

For example, if I start dragging on approx. 1 Jan 2012 and drag 2 years forward to approx. 1 Jan 2014, the resulting date range might start at 1 Mar 2012 or even further away from that.
