### ISSUE TITLE
Marker width/height ignored with custom symbol, and enabled false, with dense lines

### ISSUE THREAD

**Issue by veermaniperen** [highcharts/highcharts#21924]
#### Expected behaviour
The markers should have the size that have been configured.

#### Actual behaviour
The markers size as if no custom width/height were configured

#### Live demo with steps to reproduce
Here is a fiddle that shows the problem:

https://jsfiddle.net/eg1q2dfc/

It contains 2 series, close to each other. Each with a custom symbol for the marker, and a width/height (that have intentionally been set quite big). The "enabled" is set to false, causing the markers to disappear if the graph is "too crowded".

When running the graph you will notice that the markers to not appear (correct). When you hover over a maker, it does appear (correct), however in the wrong size!

#### Product version

Highcharts JS v11.4.8 (2024-08-29), but this also fails in v10.2.3

#### Affected browser(s)
Chrome and Edge (other not tested, but presumably all browsers are affected).

**Comment by hubertkozik** [comment]
Hello @veermaniperen! I don't see it as a bug, but a wrongly configured chart. You can see the marker because it is enabled with default values in the hover state.

If you disable the marker on the hover state everything works as you expect: https://jsfiddle.net/BlackLabel/euamkc6w/

**Comment by hubertkozik** [comment]
@veermaniperen Thank you for the explanation one more time! I misunderstood it yesterday :) 

The problem is, that marker options are not passed to the state marker. As an apology, I prepared a workaround for you until it is fixed natively. Here's the demo: https://jsfiddle.net/BlackLabel/cwd5eyag/
You can copy-paste the plugin if you want to use it in your project.

**Comment by veermaniperen** [comment]
@hubertkozik No apologies necessary, I guess my initial report could have been a little clearer ;-).

Thank you for your help and your time. We appreciate the workaround!
