### ISSUE TITLE
Lollipop chart has separated crosshair for series

### ISSUE THREAD

**Issue by AlexanderTkachuk** [highcharts/highcharts#21932]
#### Expected behaviour
I have a Lollipop chart with two data series. When I hover over the first group of data, the crosshair that appears should overlap both series 1 and series 2

#### Actual behaviour
At the moment, when I hover over the data, the crosshair appears separately for each series

#### Live demo with steps to reproduce
https://jsfiddle.net/rxtLmsnu/23/

#### Product version
Package: HighchartsLollipop from 'highcharts/modules/lollipop'
Version: "highcharts": "^11.4.6"

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
Hi @AlexanderTkachuk!

I added a more visible crosshair and I can see it for series- [demo](https://jsfiddle.net/BlackLabel/8m27nka5/).
Could you please elaborate on where the issue is?

**Comment by AlexanderTkachuk** [comment]
> Hi @AlexanderTkachuk!
> 
> I added a more visible crosshair and I can see it for series- [demo](https://jsfiddle.net/BlackLabel/8m27nka5/). Could you please elaborate on where the issue is?

Hi. Thanks for the quick response.
I would like to know if it is possible to make a common crosshair for two lines (series) at once?
For example, we have a common tooltip for two lines (series), but for some reason the crosshair is separate. Is this a bug or is it bug and is it possible to make it common?

**Comment by karolkolodziej** [comment]
The crosshair is for individual points and this is correct behaviour. 
Could you please explain how one crosshair should be displayed if there are multiple points in one group?

**Comment by AlexanderTkachuk** [comment]
> The crosshair is for individual points and this is correct behaviour. Could you please explain how one crosshair should be displayed if there are multiple points in one group?

Is it possible to create a behavior such that when I hover over one of the groups I will have a common  crosshair?
<img width="455" alt="Screenshot 2024-10-03 at 11 25 13" src="https://github.com/user-attachments/assets/14c797cd-1791-4c64-a925-9ca10faca34f">

Just like a common tooltip for two groups at once

**Comment by karolkolodziej** [comment]
Crosshair isn't ideal for this type of functionality. You can use the point `mouseOver` to render a custom rectangle below the group of points like in [the demo.](https://jsfiddle.net/BlackLabel/f4yh1jws/)
If you have questions related to the implementation, please reach out to [our support team.](https://www.highcharts.com/blog/support/)

**Comment by AlexanderTkachuk** [comment]
> Crosshair isn't ideal for this type of functionality. You can use the point `mouseOver` to render a custom rectangle below the group of points like in [the demo.](https://jsfiddle.net/BlackLabel/f4yh1jws/) If you have questions related to the implementation, please reach out to [our support team.](https://www.highcharts.com/blog/support/)

I took a look at your demo and this is what I need. Thanks a lot!
