### ISSUE TITLE
The `rangeSelector.buttonPosition.align` option does not work correctly since v11.3.0.

### ISSUE THREAD

**Issue by ddragula** [highcharts/highcharts#21945]
#### Expected behaviour
Setting [rangeSelector.buttonPosition.align](https://api.highcharts.com/highstock/rangeSelector.buttonPosition.align) to `right` correctly positions the button on the right and maintains responsiveness.

#### Actual behaviour
Setting the [rangeSelector.buttonPosition.align](https://api.highcharts.com/highstock/rangeSelector.buttonPosition.align) option to `right` causes the button to be moved slightly to the right, but incorrectly and does not respond to changing the chart width.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/Lwvf0snz/

#### Product version
Doesn't work since v11.3.0, the last working version is v10.2.0.

**Comment by aditya3434** [comment]
Hey @pawelfus! Thanks for the quick response! The plugin fix works and now the dropdown is being displayed correctly.

However, there is still one minor issue. Our charts are also resizable. Resizing the chart doesn't seem to be affecting the dropdown position. This is happening on v11.4.8 but works correctly in v10.3.3. You can test the issue in the jsFiddle given below.

jsFiddle link : https://jsfiddle.net/0bka4Lfm/1/

Is there a way to modify the plugin fix so it deals with these cases also?

**Comment by aditya3434** [comment]
@pawelfus Thanks for the fix! It works perfectly now.
