### ISSUE TITLE
X Axis labels formatter isn't rendering first tag with non-breaking space

### ISSUE THREAD

**Issue by liepa** [highcharts/highcharts#21950]
#### Expected behaviour
When adding `<span>&nbsp;</span>` in the beginning of `xAxis.labels.formatter` it should be rendered in SVG as `<tspan>&nbsp;</tspan>`.

#### Actual behaviour
It is not rendered in SVG. But if you add the same span with non-breaking space after some other tag with content, it is rendered.

#### Live demo with steps to reproduce
https://jsfiddle.net/8cjtfeo3/
1. Open Developer tools
2. Inspect in one of the X Axis labels
3. You will see that the first empty span is not rendered, but the last one is rendered

#### Product version
Highcharts Core v11.4.8

#### Affected browser(s)
N/A

**Comment by hubertkozik** [comment]
Hi @liepa! Texts and labels in Highcharts are given in HTML, but as the HTML is parsed and rendered in SVG, only a subset is supported. `&nbsp;` is not an HTML element, but a special character that represents a non-breaking space and is treated in a similar way as HTML elements in Highcharts. To render it correctly you should set `useHTML` flag to `true`.

**Live demo:** https://jsfiddle.net/BlackLabel/gev8yLh0/
**Docs:** https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#html
