### ISSUE TITLE
Highstock: Point placement between causes error with timestamps in column chart 

### ISSUE THREAD

**Issue by jonohrt** [highcharts/highcharts#2195]
The demo is here:
http://jsfiddle.net/psS8X/9/

I'm seeing the following error in the console when the pointPlacement is set to 'between' and type is 'column':
Error: Invalid value for <rect> attribute width="NaN" highstock.js:9
Error: Invalid value for <rect> attribute x="NaN" highstock.js:9
Error: Invalid value for <rect> attribute width="NaN" highstock.js:9
Error: Invalid value for <rect> attribute x="NaN" highstock.js:9
Error: Invalid value for <rect> attribute width="NaN" 

This works fine when pointPlacement is set to 'on'. I haven't been able to pin down the exact cause of the error, all the timestamp fields are unique and there doesn't seem to be any single data item causing this. If you delete a few items in the dataset you may or may not see this error, it seems somewhat sporadic. 

This issue also seems to be linked to the range selector. If the issue is not present on first load, clicking on the range selector will trigger the problem. Removing the range selector will eliminate the issue.

**Comment by jon-a-nygaard** [comment]
Closing this issue due to we are not able to reproduce it, and it has been inactive for a long time. Should anyone have further information on this issue, please add a comment and/or reopen.
