### ISSUE TITLE
I am experiencing an issue with the scaling of bubble sizes in a bubble chart

### ISSUE THREAD

**Issue by riyasat-ali** [highcharts/highcharts#21964]
Hello Highcharts Community,

I am experiencing an issue with the scaling of bubble sizes in a bubble chart. Specifically, the smallest bubble does not scale correctly relative to the other bubbles based on the data provided.

**Comment by karolkolodziej** [comment]
Hi @riyasat-ali! 
Could you please share more details of your use case? Ideally, you could share a simplified demo with your code.

**Comment by riyasat-ali** [comment]
Yes, sure,
In a bubble chart where the sizes are linked to a column, the smallest size is scaled much smaller than the other bubbles. I have reproduced the issue-
In the attached image Bubble chart size 1.jpeg the sizes are (from left to right): 600, 500, 400, 300

In the attached image Bubble chart size 2.jpeg the sizes are: 600, 500, 400, 400


![Bubble chart size 1](https://github.com/user-attachments/assets/43d571a4-557f-422c-a3a3-b5642e160102)
![Bubble image size 2](https://github.com/user-attachments/assets/546550f6-1141-4071-b07c-b3cc8513e4fd)

**Comment by karolkolodziej** [comment]
Please try using [sizeByAbsoluteValue](https://api.highcharts.com/highcharts/series.bubble.sizeByAbsoluteValue). With that, you will get bubbles of the same size in both charts- [demo](https://jsfiddle.net/BlackLabel/8nufgcqb/).
