### ISSUE TITLE
Legend overlaps rangeSelector

### ISSUE THREAD

**Issue by shypwang** [highcharts/highcharts#2196]
When legend verticalAlign is bottom or middle, and there are many legend items, the legend overlaps rangeSelector.
http://jsbin.com/EVenUBa/9/

When legend verticalAlign is top, the legend overlaps rangeSelector.
http://jsbin.com/EVenUBa/4/

**Comment by sebastianbochan** [comment]
Since 4.2.1 inputs are hidden when there is not free space.
