### ISSUE TITLE
Zoom issue in Dashboards climate demo

### ISSUE THREAD

**Issue by jomar-honsi** [highcharts/highcharts#21982]
#### Expected behaviour
The map in the climate demo to zoom in when clicking +.

#### Actual behaviour

- The map does not zoom but points disappear (Tokyo, Dublin, Sydney)
- When zooming out all points reappear but labels are hidden
- When zooming out a second time the point labels reappear

Note: Similar map components in the Live Weather demo and the Climate All demo work.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/dashboards/climate

#### Product version
Dashboards 3.0

#### Affected browser(s)
Windows 11 (Chrome 130, Edge 130), seems to depend on browser settings.

**Comment by karolkolodziej** [comment]
I've tested it on a Mac and none of it is visible. However, when I use Windows 11 and Chrome 129 on the Browserstack I'm able to reproduce the issue. 
@hubertkozik are you aware of any similar issues with maps on Windows?

**Comment by jomar-honsi** [comment]
On Ubuntu/Chrome all is well. Since the climate-all sample works, it should be fairly easy to spot the problem. @karolkolodziej I can have a look at it.

**Comment by jomar-honsi** [comment]
Windows11/Firefox works fine.

**Comment by jomar-honsi** [comment]
Issue created in core: https://github.com/highcharts/highcharts/issues/22144

**Comment by jomar-honsi** [comment]
Workaround: turn off animation in the map's chart options.

**Comment by jomar-honsi** [comment]
Inttroducing a workaround until #22144 is fixed.
