### ISSUE TITLE
Incorrect chart redrawing after resize in IE

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2199]
Open it in Internet Explorer 9.0 (I did not test with other versions) and enable document mode to IE 7.0.

1) Press Step 1 button, thus resizing the chart to 1000x400
2) Press step 2 , resizing to 350x400 (it will look horrible, but I can accept it, since the chart size is really too small)
3) Press Step 3  - resizing again to 1000x400. The damage is done -  the labels are wrapped and are overlapping  with the legend:
4) Legend is not displayed correct.

**Comment by KacperMadej** [comment]
Looks like the demo is missing. The case is very old. Closing as unable to recreate.

If anyone could recreate the problem, please post a live demo and the issue could be reopened.
