### ISSUE TITLE
Axis labels are getting duplicated in dom for every resize (highcharts-grouped-categories)

### ISSUE THREAD

**Issue by nithin4048-1** [highcharts/highcharts#22003]
#### Expected behaviour
When we resize, axis labels shouldn't be duplicated in dom

#### Actual behaviour
Axis labels are getting duplicated in dom for every resize. It is keep growing without any limits. Issue is replicable when nesting is enabled via highcharts-grouped-categories

#### Live demo with steps to reproduce
template: https://jsfiddle.net/82abwekd/ 

#### Product version
"highcharts": "^11.4.1",
"highcharts-grouped-categories": "^1.3.2",

#### Affected browser(s)
Chrome

From the below attached image, you can see `test-label` axis label has more than one instance in dom.
![image](https://github.com/user-attachments/assets/17f4d251-718b-4af4-8a58-0bc7ced8a069)

Here is the behavior after few resize, the labels are getting duplicated and keep goes on.
![image](https://github.com/user-attachments/assets/08b81b32-ced7-47e1-b5ed-be788970e8b8)

**How we are affected due to this issue:**
We have some cases where we need to switch the axis labels between original label and modified label. Here we will show the modified label as axis label and show the original label as tooltip. Due to this multiple duplicated labels, we are unable to show the tooltip when we hover on it as the dom is occupied with the latest duplicated label (not allowing mouseover event).

**Comment by bm64** [comment]
Hi @nithin4048-1 and thanks for reaching us out with the issue.

I have created a copy of this issue in the grouped categories repository, where it belongs. Feel free to follow it for any updates: https://github.com/blacklabel/grouped_categories/issues/223
