### ISSUE TITLE
Long axis labels is not retaining its original height (highcharts-grouped-categories)

### ISSUE THREAD

**Issue by nithin4048-1** [highcharts/highcharts#22004]
#### Expected behaviour
When we have long axis labels, even after multiple resize it should always have the correct height instead of more height

#### Actual behaviour
When we have long axis labels (rendered as non-rotated label), reduce the chart size by resizing it then it will become a rotated label. Now again increase the chart size by resizing it again, we could notice that it is not retaining its initial height (Taking more height for the x-axis labels). Issue is replicable when nesting is enabled via highcharts-grouped-categories

#### Live demo with steps to reproduce
template: https://jsfiddle.net/82abwekd/1/

#### Product version
"highcharts": "^11.4.1",
"highcharts-grouped-categories": "^1.3.2",

#### Affected browser(s)
Chrome

**Steps to reproduce:**
**1. Initial onload with more space for chart, so axis labels can render normally (non-rotated):**
![image](https://github.com/user-attachments/assets/9ec08c0c-c34b-4ade-9959-82d5d9fdd4b7)

**2. Do a resize by reducing the chart size, so labels will be rotated:**
![image](https://github.com/user-attachments/assets/336fee9b-2d4d-48f6-84a2-d8d1a8081e6c)

**3. Go back to the initial size to retain the non-rotated labels:**
![image](https://github.com/user-attachments/assets/2e085af8-27e5-4552-aa3f-24ea80e3a443)

Here we noticed huge space which should not be the case. It should render same as like initial case

**Comment by bm64** [comment]
Hi @nithin4048-1 

I have created a copy of the issue in the grouped categories repository: https://github.com/blacklabel/grouped_categories/issues/224
