### ISSUE TITLE
Applying dark theme makes tooltip unreadable

### ISSUE THREAD

**Issue by jelle-it** [highcharts/highcharts#22019]
#### Expected behaviour
When i set dark-theme on a chart I expect the tooltip to also follow this styling.

#### Actual behaviour
The tooltip doesn't follow this styling and shows black on black.

#### Live demo with steps to reproduce
On this page it works:
https://www.highcharts.com/docs/dashboards/light-dark-theme
But on the referenced fiddle and playground it breaks:
[https://jsfiddle.net/api/post/library/pure/
https://codepen.io/pen](https://www.highcharts.com/samples/dashboards/demo/light-dark-theme?codepen)
https://www.highcharts.com/samples/dashboards/demo/light-dark-theme?codepen

I am using it in vue so the code that triggers the darkmode is:
```vue
<highcharts
  :options="options"
  :ref="`${chartName}`"
  :class="isDark ? 'highcharts-dark' : 'highcharts-light'"
/>
```

#### Product version
"highcharts": "^11.4.8"
"highcharts-vue": "^2.0.1"

#### Affected browser(s)
(Vivaldi on mac)

#### notices

From what i found is that on the text element there is inline styling setting color and fill to rgb(51,51,51)
Now I found this test:
https://github.com/highcharts/highcharts/blob/662335826a5ea1380296c66af196eb36b3238c75/samples/unit-tests/tooltip/split/demo.js#L57

This overrides the color, so even if i set tooltip in options and give it a color its not showing.

I fixed it myself by doing this:
```css
g.highcharts-tooltip text {
  fill: var(--highcharts-neutral-color-100) !important;
}
```

**Comment by jelle-it** [comment]
Ok, that works. Thank you for your time.

I think this should be put in the docs.
https://www.highcharts.com/docs/dashboards/light-dark-theme

**Comment by karolkolodziej** [comment]
Fair point! We will add this
