### ISSUE TITLE
Error when removing last point in column series, Highstock

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#2202]
Getting "Uncaught TypeError: Cannot read property 'x' of undefined" when removing last point in column series. 

See http://jsfiddle.net/Db3UL/ - press button twice.

**Comment by highslide-software** [comment]
Accidentally closed

**Comment by pawelfus** [comment]
Works fine in 4.2.5+ versions: http://jsfiddle.net/Db3UL/1/ (there is an error after trying removing the third point, but actually there are only two points in the data).
