### ISSUE TITLE
Can't disable treemap label animations 

### ISSUE THREAD

**Issue by royalone** [highcharts/highcharts#22034]
#### Expected behaviour
setting `animation: false` while setting up treemap series should turn off animation for the cells and the labels as well

#### Actual behaviour
On data update, cells don't animate, but labels still do
Have also tried setting animation:false to additional places like `series.dataLabels`, and within `series.levels` with no luck

#### Live demo with steps to reproduce
Demo will update data after 2 seconds, and labels will animate to their new positions:
https://jsfiddle.net/mejarupw/25/

#### Product version
modules treemap & heatmap 
current (v11.4.8)

#### Affected browser(s)
Edge current (129)

**Comment by hubertkozik** [comment]
Hi @royalone! You can disable animation by setting `chart.animation` to `false`: https://jsfiddle.net/BlackLabel/pkoLa2dx/

Based on API docs, there is not supported option `dataLabels.animation.enabled`: https://api.highcharts.com/highcharts/series.treemap.dataLabels.animation Do you think we should fix it @TorsteinHonsi?

**Comment by TorsteinHonsi** [comment]
> Do you think we should fix it

@hubertkozik I don't think we need that kind of detail control over the animation. 

In the [OP demo](https://jsfiddle.net/mejarupw/25/), `series.animation` is set to false. However, this only affects the initial animation, which for a treemap is false by default, so actually it does nothing.

I expected both the rectangles and the data labels to animate on update. So if anything, I would be curious to know why the rectangles animate in this case.

But all-in-all, `chart.animation` is the setting that controls animation of elements on chart updates, also including other components like axes, labels, titles, legend etc.

**Comment by royalone** [comment]
Ok thanks guys. Using `chart.animation` obviously does what I need it to do, so I guess it wasn't really an issue and I just misunderstood

**Comment by hubertkozik** [comment]
Thank you for your response. Let's close this ticket then.
