### ISSUE TITLE
Errorbar - shadow after animation

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2203]
Take loot at the first bar, shadow stays after animation:

Example: http://jsfiddle.net/smyun/

http://tinypic.com/view.php?pic=2d8kqqo&s=5

HC 3.0.5
Chrome: the newest stable release

**Comment by pawelfus** [comment]
Looks fine in Highcharts v4.1.6 and Chrome 43.0+

**Comment by sebastianbochan** [comment]
Works properly since Highcharts 4.1.6.
