### ISSUE TITLE
Gantt chart: y-axis labels disappearing when scrolling with navigator

### ISSUE THREAD

**Issue by dkhuntrods** [highcharts/highcharts#22047]
#### Expected behaviour
Y-axis labels should remain visible

#### Actual behaviour
Labels disappear when using the navigator to scroll

#### Live demo with steps to reproduce
https://codesandbox.io/p/sandbox/angry-babbage-8r26fp

1. Reduce the size of the navigator scroll bar so it is less than the full width of the chart
2. Drag the scroll bar towards the y axis labels

https://github.com/user-attachments/assets/dbc5511e-5643-47ef-8316-414a63893af0

#### Product version
Highcharts Gantt, version 11.4.8

#### Affected browser(s)
Chrome, Safari

**Comment by karolkolodziej** [comment]
Hi @dkhuntrods! 

It looks like this issue is resolved on the master, see in [the demo.](https://jsfiddle.net/t6ecafmp/)
The fix should be included in the next release.
