### ISSUE TITLE
Dashboard Datagrid Formatting Broken

### ISSUE THREAD

**Issue by bombadil444** [highcharts/highcharts#22043]
### Issue
At some point in the past few weeks Datagrid formatting within dashboards have been broken. Issue can be seen in the demos on the offical highcharts react dashboards docs page: https://www.highcharts.com/docs/dashboards/dashboards-with-react

Noticed this happened in my project seemingly **without updating any dependencies or code**.

---------------
### Example

basic live example:
https://stackblitz.com/edit/stackblitz-starters-xn8e17?file=src%2FApp.tsx

<img width="541" alt="image" src="https://github.com/user-attachments/assets/0a2fa6c8-1781-4775-bbe8-f637efcf6538">

---------------

### Expected Behaviour
Datagrids should be displayed properly as tables

### Steps to reproduce
Setup any datagrid in a react dashboard. It will not be formatted as expected

**Comment by karolkolodziej** [comment]
Hi @bombadil444! 

We've just released the new version of Dashboards and DataGrid and we made a few breaking changes in the structure and class names. 
If you still want to use version 2.x.x please make sure you're also using the styling for this version.
```css
@import url('https://code.highcharts.com/dashboards/2.0.0/css/datagrid.css');
```
Or you can update the `@highcharts/dashboards` and use the latest styling. 

_Internal note:_
Under this issue let's fix the demos for different frameworks.

**Comment by bombadil444** [comment]
Thanks @karolkolodziej - updating to that url has fixed it for me.

Moving forward are there any recommended ways to avoid breaking styling changes from happening to a codebase that hasn't been updated?

For example I need a way to ensure that the styles behind these other urls are not automatically updated to avoid bugs being introduced into my production system:
- https://code.highcharts.com/css/highcharts.css
- https://code.highcharts.com/dashboards/css/dashboards.css

**Comment by karolkolodziej** [comment]
To avoid that please make sure the version is specified in the URL like this: 
`https://code.highcharts.com/dashboards/2.0.0/css/dashboards.css`
`https://code.highcharts.com/10.0.0/css/highcharts.css`
