### ISSUE TITLE
On initial zoom, Reset Zoom button will render behind data labels

### ISSUE THREAD

**Issue by mtbdml** [highcharts/highcharts#22048]
#### Expected behaviour
After we perform the first zoom in and the reset zoom button overlaps a data label, we expect the reset zoom button to render over top of the data label

#### Actual behaviour
After we perform the first zoom in and the reset zoom button overlaps a data label, the button is rendered behind the data label and mouse click events are captured by the data label and not the reset zoom button. After clicking the Reset Zoom button, the behavior will be as expected.

#### Live demo with steps to reproduce
https://jsfiddle.net/dpb4n0wL

Zoom in so that the Reset Zoom button overlaps a data label. You should see the Reset Zoom button render behind the data label. Clicking on the data label with the reset zoom button underneath does not reset the zoom.

_Only occurs on the first zoom, after you click reset zoom then the behavior is expected. If your first zoom does not overlap a data label then you'll need to refresh the page_

#### Product version
Highcharts core 11.4.7, 11.4.8

#### Affected browser(s)
Chrome latest

#### Possibly related
https://github.com/highcharts/highcharts/issues/21995

**Comment by hubertkozik** [comment]
Hi @mtbdml! Thank you for reporting the ticket. I wouldn't treat it as a bug. Highcharts uses SVG to render its charts, and the way SVG elements are drawn is based on the order they are added to the DOM. In SVG, elements are drawn in the order they appear in the markup, meaning that elements defined later will be rendered on top of those defined earlier.

During first render boost module is enabled, so the data labels are not drawn, but after zooming to small area the boost is disabled, so the data labels are being drawn above the previous elements, to ensure, that reset zoom button will be visible correctly you can set `chart.zooming.resetButton.theme.zIndex` option to some bigger number, like in the demo below.

**Live demo:** https://jsfiddle.net/BlackLabel/uvkwp2as/
**API Reference:** https://api.highcharts.com/highcharts/chart.zooming.resetButton.theme.zIndex
