### ISSUE TITLE
Missing Chart Redraw in Highsoft.Highcharts .Net Blazor

### ISSUE THREAD

**Issue by LorenzPurple** [highcharts/highcharts#22050]
Looks like there is no way to request a chart redraw from a blazor application
(actually using : Highsoft.Highcharts .NET / Blazor Version 11.4.6.4)

It's needed as in @code area, it's possible to add new LineSeriesData (example),
and the chart tag should be called for redraw(), to avoid rendering again all the container DIV/HTML.

The case is :
- chart data is already populated with many thousands of LineSeriesData
- new LineSeriesData is appended to Series from server-side
- chart should be refreshed, to allow dynamic redraw

Tried something like this from razor component :
        StateHasChanged();
        await JSRuntime.InvokeVoidAsync("FunctionRedraw");

and in JS file:
        function FunctionRedraw() {
            chart.redraw();
            console.log("redraw");
        }

How can this be achieved ? 
There is some missing function in the .net package ?

**Comment by hubertkozik** [comment]
Hello @LorenzPurple! In our .NET integration, there is no equivalent to the `redraw` method, so the only option is to re-render the chart. If you are particularly keen on invoking this method, you can do so in JavaScript.
