### ISSUE TITLE
Highstock.NET - Lang/RangeSelectorZoom not working

### ISSUE THREAD

**Issue by hermesramos** [highcharts/highcharts#22057]
#### Expected behaviour
When setting the text of Lang/RangeSelectorZoom to string.Empty, it should reflect in the chart.

#### Actual behaviour
The chart still shows the word 'Zoom', instead of hiding it.

#### Live demo with steps to reproduce

```
        var chart = new Highstock
        {
            ID = "test",
            Lang = new() { RangeSelectorZoom = string.Empty }

```
#### Product version
Highstock.net

#### Affected browser(s)
@brofixo

**Comment by hermesramos** [comment]
The js appears to be generated correctly, although the chart is not updating the RangeSelectorZoom text.

**Comment by brofixo** [comment]
@hermesramos ,

It looks like this shoul work. Did you try for different string value?
What version do you have?

**Comment by hermesramos** [comment]
@brofixo,

The reason it's not working is because Highstock uses a different property than Highchart. Highstock uses [rangeSelector.labelStyle](https://api.highcharts.com/highstock/rangeSelector.labelStyle) instead of RangeSelectorZoom.

I don't think there is support to labelStyle property in Highstock.net

**Comment by brofixo** [comment]
Actually it is: (`RangeSelector.labelStyle`](https://dotnet.highcharts.com/Help/Highstock/html/class_highsoft_1_1_web_1_1_mvc_1_1_stocks_1_1_range_selector.html#a61fe38d302a622c6d822cbca643dcc8b)

**Comment by hermesramos** [comment]
Thank you.
