### ISSUE TITLE
Highstock.NET - Not possible to disable Crosshair

### ISSUE THREAD

**Issue by hermesramos** [highcharts/highcharts#22058]
#### Expected behaviour
"To disable crosshair you just need to set this property to false.". The .NET object doesn't accept false.

Source: https://www.highcharts.com/forum/viewtopic.php?t=46055#:~:text=To%20disable%20crosshair%20you%20just,enabled%20property%20to%20false.

#### Actual behaviour
Option to disable the crosshair.

#### Product version
Highstock.net

#### Affected browser(s)
@brofixo

**Comment by brofixo** [comment]
@hermesramos,

Setting up `XAxis.CrosshairBool` should do the work. 
https://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_x_axis.html#ad07c97efd8d2464f3cf00a2e167fb715

Let me know if that helped.

**Comment by hermesramos** [comment]
Thank you.
