### ISSUE TITLE
Area series is going out of plot area in 3d view, if max value is provided in options

### ISSUE THREAD

**Issue by PurvaK17** [highcharts/highcharts#22070]
#### Expected behaviour
Area series should not go outside plot area.

#### Actual behaviour
Area series is going out of plot area in 3d view, if max value is provided in xaxis options

#### Live demo with steps to reproduce
https://jsfiddle.net/jhzbaxwy/2/

#### Product version
Reproducible on latest version

**Comment by karolkolodziej** [comment]
Hi @PurvaK17! 
Thank you for pointing that out but you reported a similar issue: https://github.com/highcharts/highcharts/issues/21865

I'm going to close this one as a duplicate. Feel free to comment on the original one.
