### ISSUE TITLE
Tooltip with `outside: true` renders outside the viewport - still not fixed

### ISSUE THREAD

**Issue by ItaiYosephi** [highcharts/highcharts#22088]
I opend an [issue](https://github.com/highcharts/highcharts/issues/21255) few months ago, it was closed with a [pr](https://github.com/highcharts/highcharts/pull/21371), but the issue still persists: https://github.com/highcharts/highcharts/issues/21255#issuecomment-2401475409

#### Expected behaviour
Tooltip should not overflow the viewport

#### Actual behaviour
Tooltip sometimes renders outside the viewport (causes scrollbar to appear)

#### Live demo with steps to reproduce
https://codepen.io/itaiyos/pen/RwmKqoN

This started in version 11.0.0

Related issue:
https://github.com/highcharts/highcharts/issues/21255
https://github.com/highcharts/highcharts/issues/21158

#### Product version
11.0.0-11.4.8

https://github.com/highcharts/highcharts/assets/40234776/877a94e6-e218-4324-8be5-e3888f5ec576

**Comment by karolkolodziej** [comment]
Hi @ItaiYosephi! 
Thank you for once again bringing our attention to this issue.

I was able to recreate it, but it wasn't consistent. After resizing the window to a smaller size, it happens more often.  
![image](https://github.com/user-attachments/assets/92089f4b-1125-47d2-924b-b6d555099ca5)

We will investigate it further, FYI @MarkusBarstad

**Comment by mosherc** [comment]
I can also reproduce this. Would not expect to lose positioning logic just because it's rendered outside.
