### ISSUE TITLE
Title: Treemap Legend Filtering Performance Issue with Large Datasets

### ISSUE THREAD

**Issue by amit-tsubery-sp** [highcharts/highcharts#22107]
Description:
I'm experiencing a significant performance issue when interacting with the legend of a treemap chart that contains a large dataset (around 150 nodes). When I click on a legend item to filter the data, the chart takes around 30 seconds to update, which is a noticeable delay.

#### Expected behavior
When filtering via the legend, the chart should update relatively quickly (within a few seconds) regardless of the dataset size. Or maybe add loading somehow

#### Actual behavior
When a legend item is clicked, the chart takes approximately 30 seconds to filter and render the updated treemap, severely impacting user experience.

#### Live demo with steps to reproduce
https://jsfiddle.net/p0hu2kw3/5/

#### Product version
		"highcharts": "11.4.8",
		"highcharts-angular": "4.0.1",

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
Hi @amit-tsubery-sp!
Thank you for pointing that out.

A significant portion of the time spent rerendering when clicking on legend takes place in treemaps' `drawPoints` method. 
If `dataLabels` and `animation` is disabled it gets better- [demo](https://jsfiddle.net/BlackLabel/6sevnrfo/).

**Comment by amit-tsubery-sp** [comment]
@karolkolodziej I'm wondering if I like this approach.
Do you think I can make this legend the only display? And not as a button?

**Comment by karolkolodziej** [comment]
@amit-tsubery-sp 
You can "disable" the click on the legend by overwriting the [itemClick](https://api.highcharts.com/highcharts/legend.events.itemClick) event, see description in API.

**Comment by amit-tsubery-sp** [comment]
@karolkolodziej Great. It is working fantastic
