### ISSUE TITLE
rangeSelector doesn't render when initial series is empty, and doesn't update when series changes

### ISSUE THREAD

**Issue by jacobweber** [highcharts/highcharts#2210]
I'm trying to load data asynchronously with HighStock 1.3.5.  This used to work on 1.3.2. Now when I initially set the series data to an empty array, it doesn't render the rangeSelector. And when I update the data, it still doesn't render the rangeSelector.

Example: http://jsfiddle.net/PAWMf/

Another issue is that if I DO provide some initial data, and then change it asynchronously, the rangeSelector doesn't update to reflect the new data. It still shows the original date range, and the disabled buttons don't become enabled.

(You can use the same example, but change the initial data from [] to [1,2,3,4,5].)

**Comment by pawelfus** [comment]
All examples in this ticket work: 

- http://jsfiddle.net/CgAnW/63/
- http://jsfiddle.net/PAWMf/6/

I am not sure about missing range selector, when chart is initialized without data. It could give wrong impression, that user can change something on the chart, but chart is empty after all.

**Comment by sebastianbochan** [comment]
I agree with Pawel, that elements should not be draw when series is missing.

@TorsteinHonsi should we still consider this case as a bug?

**Comment by TorsteinHonsi** [comment]
I'm not sure - either way goes I suppose. If it shows on empty data, we need to make sure all buttons are disabled at least.
