### ISSUE TITLE
Unable to dynamically change layoutAlgorithm.splitSeries for packedbuble series

### ISSUE THREAD

**Issue by AndrzejBuleczka** [highcharts/highcharts#22108]
#### Expected behaviour
It's possible to change the splitSeries value for packedbubble series type layout algorithm.

#### Actual behaviour
Attempts to toggle the splitSeries value break; either there is no change after redraw and console.error is logged, or the parentBubbles does not dissapear - it changes if we intialize the option as 'true' or 'false'

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/3z4dvLat/
1) open developer tools, and click the toggle button 2-3 times;
2) change the setting in plotOptions to splitSeries: false and click toggle button again few times

#### Product version
Highcharts Core

#### Affected browser(s)
all

**Comment by hubertkozik** [comment]
This issue has the same rootcause as https://github.com/highcharts/highcharts/issues/21972. `layoutAlgorithm.splitSeries` does not work on series-level object. Closing as a duplicate.
