### ISSUE TITLE
Navigator not working after 11.4.2 when using xrange

### ISSUE THREAD

**Issue by zaffalon** [highcharts/highcharts#22127]
#### Expected behaviour

The navigator is expected to move the chart position when moving the navigator for xrange charts.

#### Actual behaviour

When the navigator moves, it shows an empty chart after version 11.4.2.

#### Live demo with steps to reproduce
https://jsfiddle.net/zaffalon/dut90ze7/5/
Move the navigator to see, and you will see the labels changing and not showing data.
Change to version 11.4.0, and you will see it working as expected.

#### Product version
Version 11.4.2

**Comment by karolkolodziej** [comment]
Hi @zaffalon! 
This issue has been already fixed on the master- [see the demo.](https://jsfiddle.net/BlackLabel/syqr7w50/)
The fix should be included in the next release.
