### ISSUE TITLE
Labels font size requires string

### ISSUE THREAD

**Issue by sinnbeck** [highcharts/highcharts#22124]
#### Expected behaviour
When setting labels font size the API docs says it supports a number. But that does not work in firefox. For it to work, you need to set it to '12px' for instance. It does work in chrome

https://api.highcharts.com/highcharts/xAxis.labels.style.fontSize

#### Actual behaviour
I would expect that it works the same in both browsers, and that it follows the API docs.

#### Live demo with steps to reproduce
https://jsfiddle.net/tkmv5wz3/

#### Product version
Latest

#### Affected browser(s)
Firefox

**Comment by karolkolodziej** [comment]
Hi @sinnbeck! 
Thank you for reporting the issue.

_Internal note:_
In Firefox the `getStyle` method for `font-size` returns an empty string when the font declared only with a number without the unit.
This value is later on used in the `buildSVG` function.
https://github.com/highcharts/highcharts/blob/cea30ab31e703f713fbb569ab5a1bfae00bc2c4f/ts/Core/Renderer/SVG/SVGElement.ts#L1673-L1677
