### ISSUE TITLE
Highmaps: Shapes hide on hover when map is plotted using custom SVG data

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#22162]
#### Expected behaviour
Shapes should not hide on hover.

#### Actual behaviour
Custom svg data is converted to mapData using utility: https://highcharts.github.io/map-from-svg/ 
All the shapes are rendered correctly initially. However on hovering the inner rectangles are hidden.

#### Live demo with steps to reproduce
https://jsfiddle.net/a2hx0q1b/

#### Product version
All

#### Affected browser(s)
All

**Comment by hubertkozik** [comment]
Hi @amruta30! It does not look like a bug. The shapes from the custom SVG data you have provided in the demo cover each other, so it's a correct behaviour, that after hovering one the rest is hidden to show the hovered one fully. You can check, for example, maps from [Highcharts Map-Colleciton](https://code.highcharts.com/mapdata/), that there are no shapes that cover any. If you don't want your custom SVG rects to cover others, then you should prepare SVG data with gaps for those smaller rects.
