### ISSUE TITLE
Shadow is applied only to the first zone with zones enabled

### ISSUE THREAD

**Issue by jedrzejruta** [highcharts/highcharts#22169]
#### Expected behaviour
Shadow is applied to whole series.

#### Actual behaviour
Shadow is applied only to the first zone.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/pouqyeg0/](https://jsfiddle.net/BlackLabel/pouqyeg0/)

#### Product version
Regression introduced in Highcharts v11.0.0

**Comment by hubertkozik** [comment]
_Internal note_
Bisected to 237a4f4349f84f7198176c9bb0b56b4c52e81aeb.
