### ISSUE TITLE
yAxis max value is calculated incorrectly for scatterplot with multiple series when using boost module

### ISSUE THREAD

**Issue by HendrikThePendric** [highcharts/highcharts#22183]
#### Background

- We found this bug after upgrading Highcharts from v10 to v11. In v10 this is working correctly, so this is a regression in v11.
- After the v11 upgrade the yAxis has the correct range without the boost module, but when the boost module is added the yAxis range is incorrect.

#### Expected behaviour

For scatterplots with multiple series and many data points the max value of the yAxis should be calculated based on the series with the largest range, as in the image below (where the boost module is not enabled):

<img width="845" alt="without_boost_mode" src="https://github.com/user-attachments/assets/603988b9-2adc-4274-9550-e16ab726f5e9">

#### Actual behaviour

The yAxis max is calculated based on the series with the most data-points, but with a smallest range, as in the image below (with boost module enabled):

<img width="839" alt="with_boost_mode" src="https://github.com/user-attachments/assets/616ae4ce-42c9-4204-a8ec-51126ef7bb6a">

#### Live demo with steps to reproduce

1. Open this jsFiddle to see the chart with the boost module enabled, and observer the yAxis only goes up to 1400: https://jsfiddle.net/vdjsep39/2/
2. Compare to this jsFiddle where the yAxis is scaled correctly to 5000: https://jsfiddle.net/djcx10Lh/1/

#### Product version

Highcharts Core 11.4.8
With Highcharts boost module (also on 11.4.8)

#### Affected browser(s)

All

**Comment by HendrikThePendric** [comment]
We've realised that as a workaround we could use a single scatterplot series and style each individual data point. But this approach has some downsides in terms of memory usage and pre-processing of the data. Furthermore, since this is a breaking change not mentioned in the changelog, we still consider this to be a bug and prefer to await a resolution before upgrading to v11.

**Comment by hubertkozik** [comment]
The regression was introduced in Highcharts v11.4.0. The last working version is Highcharts v11.3.0.

_Internal note_
Bisected to 74cd4c8555921e7700638edaa79bb199f46d837f.
