### ISSUE TITLE
Incorrect zooming state when zones are present

### ISSUE THREAD

**Issue by nishikantparmariam** [highcharts/highcharts#22188]
_(This is blocking our upgrade from Highcharts 10.3.3 to 11)_

#### Expected behaviour
Zooming should work as expected to render selected part of the series.

#### Actual behaviour

In below GIF, we can notice a weird white area (discontinuity) on the left and a single point when we zoom. This seems to happen only when `series.line.zones` are used. Tried for both `line` and `area` series types:
![left-area-missing-zones](https://github.com/user-attachments/assets/2c36fd5e-e7cb-4b7e-a777-9a54de981e43)

#### Live demo with steps to reproduce
https://jsfiddle.net/1awpsd39/

#### Product version
Highcharts

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Fails since v11.3.0, bisected to 704d326db5dd7aac3f378c8f6fad5ac0c6f26f4b. 

Zones clipping was refactored between v11.2 and v11.3

**Comment by nishikantparmariam** [comment]
Hi @TorsteinHonsi, while the issue of discontinuity in left has been fixed with provided plugin in https://github.com/highcharts/highcharts/pull/22191#issue-2678116691, I do see a darker area upon zooming in area chart. This happens only when `series[0].zones` is used and `xAxis[0].type` is set to category: 

https://jsfiddle.net/r7gumjv2/

![darker-area](https://github.com/user-attachments/assets/0e43a335-5725-4066-8653-9c577dff6d8a)

**Comment by TorsteinHonsi** [comment]
Here's the patched fix: https://jsfiddle.net/highcharts/c92xtsyn/

The change was similar to the one in the minimum end: 
`      const axisMax = axis.getExtremes().max + (axis.minPointOffset || 0),`
