### ISSUE TITLE
The chart export feature is giving CORS issue

### ISSUE THREAD

**Issue by Neha44hz** [highcharts/highcharts#22184]
#### Expected behaviour
The png, jpg and pdf files should get exported

#### Actual behaviour
The highchart export url is giving cors issue

**Comment by bm64** [comment]
Hi @Neha44hz and thank you for reaching out.

There is already a ticket for this issue in the export server repository. I’ll be closing this one as a duplicate. Please follow the original ticket for updates on the issue: https://github.com/highcharts/node-export-server/issues/602
