### ISSUE TITLE
Pie/donut charts with multiple series do not share center/radius

### ISSUE THREAD

**Issue by DNarum** [highcharts/highcharts#2221]
Series in pie charts are drawn independent of each other. If settings or values for one of the series' labels cause the series to be drawn off-center or with a different size, this will not affect any of the other series.

An extreme case can be seen at http://jsfiddle.net/n9GCE/
More commonly, the chart will just be slightly off, as seen in http://jsfiddle.net/LXtE4/2

I would expect the size and center of the chart to be determined based upon information from all the series.

**Comment by thiagosbrito** [comment]
You just have to change the plotOptions.

$(function () {
        $('#container').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: {
                text: 'Browser market shares at a specific website, 2010'
            },
            tooltip: {
        	    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    center: ['50%','50%'],
                    dataLabels: {
                        enabled: true,
                        color: '#000000',
                        connectorColor: '#000000',
                        distance: 20,
                        
                        formatter: function() {
                            return '<b>'+ this.point.name +'</b>: '+ this.percentage +' %';
                        }
                    }
                }
            },
            series: [{
                type: 'pie',
                name: 'Browser share',
                data: [
                    ['Firefox',   10],
                    ['IE',       20],
                    ['Chrome', 30],       
                    ['Safari',    40]                    
                ],
                 
                innerSize: "70%",
                outerSize: "100%"
            },{
                type: 'pie',
                name: 'Browser share',
                data: [
                    ['Firefox',   20-1e-6],
                    ['IE',       30+1e-6],
                    ['Chrome', 10],       
                    ['Safari',    40] 
                ],
                innerSize: "50%",
                outerSize: "100%"

            }]
        });
    });
