### ISSUE TITLE
Bright colors overlapping the light colors if drilldown is enabled

### ISSUE THREAD

**Issue by balunandam** [highcharts/highcharts#22226]
#### Expected behaviour
The child color should not be visible upfront when the user is at parent level.

#### Actual behaviour
When drilldown is enabled with parent and child data, if the user is at parent level with a light color, the child data with bright colors is visible at parent level.

#### Live demo with steps to reproduce
https://jsfiddle.net/g9rxsk4w/12/

step:1 Observe the child colors if user is at parent level.
Step:2 Drilldown to usa and observe the child colors.
Step: 3 Drillup to USA and observe the parent color, the actual color is not applied to parent. Child colors are overlapping the parent colors at parent level

#### Product version
Highcharts JS v11.4.8, v11.1.0

#### Affected browser(s)
Google chrome, Microsoft Edge

**Comment by hubertkozik** [comment]
Hi @balunandam! The behaviour you are describing is not a bug. By default `treemap.opacity` is set to `0/15`, you can check in the API here: https://api.highcharts.com/highcharts/series.treemap.opacity

Parent color is actually visible, but it's opacity is set to a low value so you can see through. If you set the opacity to 1, you can see the parent color without transparency: https://jsfiddle.net/BlackLabel/6q7hvk5x/

**Comment by balunandam** [comment]
Hello, hubertkozik, when hovering over the parent, we can see the children. Do we have any configuration to change that behavior? https://jsfiddle.net/BlackLabel/6q7hvk5x/

**Comment by hubertkozik** [comment]
The API shows that the `opacity` is set to 0.75 for the hover state. You can change it to 1.

**Live demo:** https://jsfiddle.net/BlackLabel/4kpx27gn/
**API Reference:** https://api.highcharts.com/highcharts/series.treemap.states.hover.opacity

If you need help with your chart configuration feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
