### ISSUE TITLE
Enhancement: manually call reflow method

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2224]
Make the `reflow` method available.
If you want to reflow all charts, you have to do something like `window.HighchartsAdapter.fireEvent(window, 'resize')`. But because of the timeout, the charts are not redrawn immediately.

Maybe something like `Highcharts.reflow()`.

**Comment by McNetic** [comment]
The fix will not work with mootools (see #805).

**Comment by pawelfus** [comment]
Why not? There is checking for `event` in case of mootools.

**Comment by McNetic** [comment]
Sorry, i expressed unclear. Afaics (as of #805), mootools does not provide e in case of window.resize event. The fix disables Timeout when e is missing, so it should be a regression with mootools, because the timeout will never be set then.

**Comment by hayd** [comment]
It seems that the above `reflowNow` no longer works since `HighchartsAdapter` is not available. ?

**Comment by pawelfus** [comment]
There's no method like `reflowNow()` but `reflow()`, see [API](http://api.highcharts.com/highcharts#Chart.reflow).

**Comment by mohaideenisync** [comment]
reflow() is not happening by default even if i set reflow:true also (Angularjs)

**Comment by pawelfus** [comment]
Could you create jsFiddle with the issue? We will check this.
