### ISSUE TITLE
Can't resolve 'highcharts' in 'Insert your folder here' - Module not found

### ISSUE THREAD

**Issue by Freshenext** [highcharts/highcharts#22243]
#### Description
Hi. After updating from Highcharts v11.4.8 to v12.0.0, the module resolution system is failing. The primary issue appears to be with how modules are being resolved internally.

Here is the proof:
![image](https://github.com/user-attachments/assets/f303a7ff-d0b6-4515-b891-c87f80cc157f)

Even ESLINT knows a problem was introduced.
![image](https://github.com/user-attachments/assets/4b85eca5-478b-4f9c-a4e6-8cba721893d1)

The exporting module still tries to resolve 'highcharts' from within node_modules/highcharts/modules, leading to the same resolution error. Multiple workaround attempts failed:

Using ES modules path
Using bundled version
Using different import patterns
Trying to use relative paths

#### Expected behaviour
Module resolution should work as it did in v11.4.8
Importing both core and additional modules should resolve correctly

#### Actual behaviour
It looks like something changed in the deployment that affected how modules (?) are built, causing the app to not detect the latest version.

When I rollback to 11.4.8, everything works fine again. 

#### Product version

12.0.0

#### ENV

Node.js environment
Create React App (CRA)
No custom webpack config (standard CRA setup)
ESLint reports import resolution issues
Package Manager: npm

**Comment by weiyanggod** [comment]
I also had the same problem

**Comment by TorsteinHonsi** [comment]
Thank you for reporting, we'll look into this!

**Comment by vkbansal** [comment]
I am also facing the same issue. It's happening because, the `main` entry in `package.json` refers `highcharts.js`, where as there is no file with this name present in the package. The file name present in package is `highcharts.src.js`.

Similarly `types` is refering to `highcharts.d.ts`, but there is no such file.

Hope this helps.

**Comment by TorsteinHonsi** [comment]
Absolutely @vkbansal, thanks for your help!

**Comment by TorsteinHonsi** [comment]
This is fixed now with v12.0.1, thank you for your patience!

**Comment by TorsteinHonsi** [comment]
@mesfahanisimscale Yes, the npm package loads from the `highcharts-dist` repo. So the diff in question is https://github.com/highcharts/highcharts-dist/compare/v12.0.0...v12.0.1 .

**Comment by mesfahanisimscale** [comment]
I see, thanks for clarification. 
Looks like it's not longer needed to "wrap" Highcharts in the factory method exported by `highcharts/modules/export-data` (as shown in the first message in this issue), it's enough to simply import it as such:
```
import 'highcharts/modules/export-data'
```
Is that correct?

**Comment by hubertkozik** [comment]
Hi @mesfahanisimscale! Yes, that's right. You don't need to call the module factories.

Here's a related comment and ticket: https://github.com/highcharts/highcharts/issues/22251#issuecomment-2507396579
