### ISSUE TITLE
highcharts-more uncaught error breaks graphs on a HTML page

### ISSUE THREAD

**Issue by Swaakie** [highcharts/highcharts#22252]
#### Expected behaviour
Converted a ipynb file to HTML with nbconvert and the graphs show up in the generated HTML file while using a mix of area/line/column & arearanges graphs

#### Actual behaviour
Converted a ipynb file to HTML with nbconvert but the graphs disappear when the HTML file is generated. This only happens when I use arearanges in the report which adds the highcharts-more.js. Removing the arearanges fixes the report as it doesn't use the highcharts-more.js without them.

#### Live demo with steps to reproduce
![image](https://github.com/user-attachments/assets/5301ad03-366b-422a-b29f-c52d7e8fe5b8)

#### Product version
from 12.0.0 >= 

#### Affected browser(s)
Chrome, Firefox, Edge

**Comment by karolkolodziej** [comment]
Hi @Swaakie! 
I don't have experience with the Jupyter Notebook and without looking at the code might be difficult to say what is wrong.

But out of the top of my head in v12 you don't have to call the module factories- simply import the module you need without calling it `import more from 'highcharts/highcharts-more';`.
You can give it a try and if it doesn't work please share more detail of your setup and code if possible.

**Comment by Swaakie** [comment]
Hey @karolkolodziej, thanks for your response!

So what I use is highcharts for Python in JupyterLab to generate the graphs. I'm able to display the graphs I create in the output of the ipynb file, which usually also works when converting the output file to a HTML file using nbconvert. The converted file then uses the highcharts.js package to display the interactive graphs in the HTML file:
![image](https://github.com/user-attachments/assets/12db2b9d-0393-40dc-8a49-119cb0e10e74)

When I use the AreaRangeSeries `from highcharts_core.options.series.area import LineSeries,AreaSeries,AreaRangeSeries`  it will automatically include highcharts-more.js to the output file, but it seems there is an issue with loading the highcharts-more.js which makes the graphs using the AreaRangeSeries (combination of line & arearange) not show up when it's included. Removing the AreaRangeSeries also removes highcharts-more.js and the line graph shows up.

It seems the Uncaught error in the web browser (In my initial message) makes it so that the AreaRangeSeries cannot be displayed. This only happend after V12 as well.

**Comment by Swaakie** [comment]
It's fixed now in 12.0.2
