### ISSUE TITLE
V12 modules don't work with highstock and highmaps

### ISSUE THREAD

**Issue by anajavi** [highcharts/highcharts#22258]
#### Expected behaviour
Adding modules should work the same for highstock and highmaps as highcharts.

```js
import * as Highcharts from 'highcharts/highstock';
import 'highcharts/modules/histogram-bellcurve';
```

#### Actual behaviour

When using highstock the module does not apply and error is shown, for example:
```
Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=bellcurve
- missingModuleFor: bellcurve
```

This was working in v11.

#### Live demo with steps to reproduce
[demo](https://stackblitz.com/edit/react-starter-typescript-a9am1a?file=package.json,App.tsx)

#### Product version
Highstock and Highmaps 12

#### Affected browser(s)
- Chrome 131
- Safari 18.1.1

**Comment by bre1470** [comment]
Hello @anajavi!

Thank you for the new report. This seems to be an issue with ESM references, unsure if this comes from the new UMD pattern or from the React integration.

⚠️ The following pattern as a **workaround** will break compatibility with previous Highcharts versions:

```js
import React, { useRef } from 'react';
import 'highcharts/highstock';
import Highcharts from 'highcharts/modules/histogram-bellcurve';
import HighchartsReact from 'highcharts-react-official';
```

Import only the namespace of the last Highcharts bundle, which includes all previous bundles. The previous ("local") imports of the Highcharts namespace do not get extended as with the module functions.

**Comment by bre1470** [comment]
@TorsteinHonsi This is probably a general issue with UMD bundles and leads to some discussion points:
* Make ESM master variant mandatory for React?
* Continue with factory functions to extend the local imported namespace?
* Introduce a plugin system instead of using webpack?

**Comment by bre1470** [comment]
💡 The following workaround is favourable for an ESM-compatible setup:
```
import React, { useRef } from 'react';
import Highcharts from 'highcharts/es-modules/masters/highstock.src';
import 'highcharts/es-modules/masters/modules/histogram-bellcurve.src';
import HighchartsReact from 'highcharts-react-official';
```

**Comment by DiegoCardoso** [comment]
I would like to add that this issue can be noticed without the React package as can be seen here (https://stackblitz.com/edit/vitejs-vite-zjsuuh?file=src%2Fmain.js).

**Comment by anajavi** [comment]
I found this problem while doing PR to react-jsx-highcharts: https://github.com/whawker/react-jsx-highcharts/pull/391

The highstock and highmaps tests started to output warnings about accessibility module not loaded.

So not using react-highcharts-official either.

**Comment by TorsteinHonsi** [comment]
### Workaround
The `highstock.js`, `highmaps.js` and `highcharts-gantt.js` bundles all have a module counterpart that works as an addition to `highcharts.js`. Since this bug only applies to the secondary bundles, not the `highcharts.js` bundle, we can simply load `highcharts.js` + module. This allows us to load minified files, and we don't need the counter-intuitive trick of returning Highcharts from the last module loaded. Tested with the [StackBlitz above](https://github.com/highcharts/highcharts/issues/22258#issuecomment-2511011209).

```js
import Highcharts from 'highcharts/highcharts';
import 'highcharts/modules/stock';
import 'highcharts/modules/exporting';
```
