### ISSUE TITLE
Range selector buttons are no longer responsive in v12

### ISSUE THREAD

**Issue by xPaw** [highcharts/highcharts#22262]
#### Expected behaviour
Show dropdown for buttons on small width

#### Actual behaviour
All buttons are shown and they overflow. There is an invisible dropdown that is overlayed on top of the buttons.

I don't think the select is supposed to be positioned like this:
![image](https://github.com/user-attachments/assets/c4856a1c-c906-431a-90e0-10a8c0b1274c)

On my real site when I tried to update, the select wasnt even on the left, but was actually covering one of the buttons:
![image](https://github.com/user-attachments/assets/81f54009-d355-4893-8473-47a82a860494)

#### Live demo with steps to reproduce
https://jsfiddle.net/d91foj76/

#### Product version
Highcharts stock 12.0.1

#### Affected browser(s)
Chrome 131

**Comment by bm64** [comment]
Hello @xPaw and thanks for reporting the issue.

**Comment by xPaw** [comment]
@TorsteinHonsi I don't think this was fixed in 12.1.0, it's still not responsive: https://jsfiddle.net/u75me2sb/

**Comment by TorsteinHonsi** [comment]
Bisected to 3aab9a40bdcd87b7b382d08c7d1e954363f5392c . @pawellysy FYI

**Comment by TorsteinHonsi** [comment]
@pawellysy On further inspection, I think the issue appears after merging https://github.com/highcharts/highcharts/pull/21989. Which makes more sense.
