### ISSUE TITLE
Sync/Align Charts (and sizes)

### ISSUE THREAD

**Issue by hansgru** [highcharts/highcharts#2226]
Hi,

Especially for the PieCharts more than one chart needs to be displayed on the screen.
The automatic calculation of label and size is very useful since data varies greatly and hard-coded values would render ugly.

The only problem is that this automatic calculation is for each chart individually :(. It would be very helpful if there were some "sync" or "connect" functionality that would allow to calculate for all charts that are "connected" a common size.

regards.

**Comment by oysteinmoseng** [comment]
Enhanced sync between charts is still relevant, and perhaps this case should also be considered for dashboards. Multiple pie series in the same chart seems like a common use case.
