### ISSUE TITLE
Adding a component to a new row does not deactivate highlight on new row

### ISSUE THREAD

**Issue by Farrisi** [highcharts/highcharts#22271]
#### Expected behaviour
When an edit context is active, adding a new component to a new row will deactivate the highlight on the old row

#### Actual behaviour
When an edit context is active, adding a new component does not deactivate the highlight on the previous row. The previous row is still highlighted.

#### Live demo with steps to reproduce
https://www.highcharts.com/samples/dashboards/edit-mode/ctx-enabled?jsfiddle

1. Enter edit mode
2. Click one of the components
3. Add a panel to a new row
4. Click 'Confirm'
5. Observe that the pervious row is still highlighted 

#### Product version
Dashboards v3.0.0

#### Affected browser(s)
tested in Chrome

**Comment by karolkolodziej** [comment]
Hi @Farrisi! 
Thank you for reporting the issue.

Internal note:
When adding a component to a new row the highlight isn't correct:
![image](https://github.com/user-attachments/assets/af4e0488-a196-4824-90ee-b20e63102901)
