### ISSUE TITLE
[bug] Waterfall breaks if more than one intermediateSum is used :(.

### ISSUE THREAD

**Issue by hansgru** [highcharts/highcharts#2227]
Waterfall breaks if more than one `intermediateSum` is used, rendering the chart useless :(.

Based on your public example: http://www.highcharts.com/demo/waterfall
I just added an intermediary sum:

``` JavaScript
...
            }, {
                name: 'Fixed Costs',
                y: -342000
            }, {
                name: '2nd Sum',
                isIntermediateSum: true,
                color: Highcharts.getOptions().colors[1]
            }, {
                name: 'Variable Costs',
                y: -233000
            }, {
...
```

![waterfall_bug](https://f.cloud.github.com/assets/5159511/1085536/5ccdf890-15d4-11e3-9b58-4cf645959e0a.png)

**Comment by Taxman972** [comment]
I think there is another problem not with multiple `isIntermediateSum` when multiple `isSum` works.

![highcharts demo - jsfiddle](https://user-images.githubusercontent.com/14277043/43958811-04627f5e-9cad-11e8-8d7b-8a5b202cc467.png)


[Fiddle](https://jsfiddle.net/core972/8tnv0o6f/)

**Comment by KacperMadej** [comment]
Hi @Taxman972 

Please describe what the problem you have is about. Chart looks good - intermediate sum is summing values from start or previous intermediate sum.
If you are not sure that the behavior of a chart is a bug then contact support first - https://www.highcharts.com/support
