### ISSUE TITLE
Time.timezone option doesn't correctly set timezone when undefined 

### ISSUE THREAD

**Issue by NickCoombe1** [highcharts/highcharts#22277]
#### Expected behaviour
Setting timezone as undefined should pull the local timezone from the browser as specified in the [docs](https://api.highcharts.com/highcharts/time.timezone). 

#### Actual behaviour
When setting timezone to undefined the dates on the graph default to UTC and don't adhere to the browser default.

#### Live demo with steps to reproduce

https://jsfiddle.net/me8chLbt/18/

#### Product version

Highcharts Core v12.01

#### Affected browser(s)
Chrome Version 131.0.6778.86 (Official Build) (64-bit)

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Looks like indeed the `timezone` setting doesn't behave like announced. It should _default_ to UTC, but when explicitly set to `undefined`, it should use local time.

#### Workaround
Set `time.useUTC` to false. https://jsfiddle.net/highcharts/rdoLqz8m/
