### ISSUE TITLE
HighchartsSankey issue in v12

### ISSUE THREAD

**Issue by arunmmanoharan** [highcharts/highcharts#22280]
#### Expected behaviour
Should compile
#### Actual behaviour
  HighchartsSankey(Highcharts);
  ^
TypeError: (0 , import_sankey.default) is not a function

#### Product version
v12.0

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

This is not a bug though, it is mentioned in the changelog under Upgrade notes:

> When importing Highcharts as a node module, additional modules no longer requires initialization. See [comment on GitHub](https://github.com/highcharts/highcharts/issues/22251#issuecomment-2507396579).

Basically, you should be able to just remove that line, and Sankey charts will work as before.
