### ISSUE TITLE
Pie chart data labels draw outside of the canvas

### ISSUE THREAD

**Issue by pplante** [highcharts/highcharts#223]
The pie chart is not taking into account the length of the data label when trying to position it, so they often render partially outside of the canvas.  I was able to use margins on the chart to give myself enough padding, but this isn't the way to fix it,

**Comment by shanSyapse** [comment]
I have the same issue with  donut chart, labels are extending out side the chart.

**Comment by highslide-software** [comment]
This case shows how labels are clipped: http://jsfiddle.net/highcharts/7okk430t/

**Comment by highslide-software** [comment]
I have worked on this and explored logic to add ellipsis to overflowing data labels. It currently works well on static charts, but breaks on dynamically resizing or updating the chart.

A live demo can be seen at http://jsfiddle.net/highcharts/7okk430t/1/.

.. and here's the diff:

```diff
diff --git a/js/parts/DataLabels.js b/js/parts/DataLabels.js
index c72fabf..a7222c5 100644
--- a/js/parts/DataLabels.js
+++ b/js/parts/DataLabels.js
@@ -619,13 +619,41 @@ if (seriesTypes.pie) {
 	 * fall within the plot area.
 	 */
 	seriesTypes.pie.prototype.placeDataLabels = function () {
+
+		var chart = this.chart,
+			spacing = chart.spacing;
 		each(this.points, function (point) {
 			var dataLabel = point.dataLabel,
-				_pos;
+				_pos,
+				overflow,
+				ellipsis;
 
 			if (dataLabel && point.visible) {
 				_pos = dataLabel._pos;
 				if (_pos) {
+					
+					if (dataLabel._attr.align === 'right') {
+						overflow = _pos.x - dataLabel.width;
+						if (overflow < spacing[3]) {
+							ellipsis = true;
+						}
+					}
+
+					if (dataLabel._attr.align === 'left') {
+						overflow = chart.chartWidth - _pos.x - dataLabel.width - spacing[1] - spacing[3];
+						if (overflow < spacing[1]) {
+							ellipsis = true;
+						}
+					}
+
+					if (ellipsis) {
+						dataLabel._attr.width = dataLabel.width + overflow;
+						dataLabel.css({
+							width: dataLabel._attr.width + PX,
+							textOverflow: 'ellipsis'
+						});
+					}
+
 					dataLabel.attr(dataLabel._attr);
 					dataLabel[dataLabel.moved ? 'animate' : 'attr'](_pos);
 					dataLabel.moved = true;
diff --git a/js/parts/SvgRenderer.js b/js/parts/SvgRenderer.js
index 1f8b71d..fcc629d 100644
--- a/js/parts/SvgRenderer.js
+++ b/js/parts/SvgRenderer.js
@@ -10,7 +10,7 @@ SVGElement.prototype = {
 	opacity: 1,
 	// For labels, these CSS properties are applied to the <text> node directly
 	textProps: ['fontSize', 'fontWeight', 'fontFamily', 'fontStyle', 'color', 
-		'lineHeight', 'width', 'textDecoration', 'textShadow'],
+		'lineHeight', 'width', 'textDecoration', 'textOverflow', 'textShadow'],
 	
 	/**
 	 * Initialize the SVG renderer
```

**Comment by chitwant82** [comment]
I tried the javascript from here and get following:

Uncaught TypeError: $(...).resizable is not a function

**Comment by highslide-software** [comment]
The `resizable` method requires jQuery UI.

**Comment by chitwant82** [comment]
Ah... imported these 2 and works fine now, thanks!

<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

**Comment by BrianLaughlan** [comment]
I also have data labels cutting off. 

+1 for the ellipsis solution to be implemented into high charts.

**Comment by Floriferous** [comment]
Why is this issue closed? It was started in 2011, but I still have this problem in 2017.

**Comment by carlosmorantes** [comment]
This is still happening 
![e](https://cloud.githubusercontent.com/assets/12380268/22883148/08a1a12c-f1ef-11e6-89b2-6afd8a69f2ee.jpg)

**Comment by LuigiMaestrelli** [comment]
I'm using the version 5.0.11
And it is still happening on the donut chart.

![donutchart size](https://cloud.githubusercontent.com/assets/5038871/25745125/c850270a-3173-11e7-8836-eadc745dcd18.PNG)
