### ISSUE TITLE
highcharts Accessibility Module not working on v12 update

### ISSUE THREAD

**Issue by kennethbigler** [highcharts/highcharts#22300]
#### Expected behaviour

I expected to be able to include the accessibility module for highcharts under the new major. The code I was using to include it was like this:

``` jsx
import * as Highcharts from "highcharts";
import highchartsAccessibility from "highcharts/modules/accessibility";
import HighchartsReact from "highcharts-react-official";
...
highchartsAccessibility(Highcharts); // initiate accessibility module
...
return (
  <figure style={{ margin: 0, width: "100%" }}>
    <HighchartsReact highcharts={Highcharts} options={options} />
  </figure>
);
```

#### Actual behaviour

I am getting: `TypeError: (0 , default) is not a function` on this line:

``` jsx
highchartsAccessibility(Highcharts); // initiate accessibility module
```

#### Product version

highcharts/modules/accessibility for version 12.0.2

#### Affected browser(s)

All

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! This is a deliberate change as noted in the Upgrade notes of the [changelog](https://www.highcharts.com/blog/changelog/).

The factory function is no longer needed, so you can remove this line:
`highchartsAccessibility(Highcharts); // initiate accessibility module`

**Comment by thedanchez** [comment]
> Thanks for reporting! This is a deliberate change as noted in the Upgrade notes of the [changelog](https://www.highcharts.com/blog/changelog/).
> 
> The factory function is no longer needed, so you can remove this line: `highchartsAccessibility(Highcharts); // initiate accessibility module`

So how does accessibility get set on Highcharts v12?

```tsx
import Highcharts from "highcharts/esm/highcharts";
import Accessibility from "highcharts/modules/accessibility";

Accessibility(Highcharts); // this crashes for me like the OP posted
```

Is the expectation that we just configure the `accessibility` options for the chart? What's the minimum values to be set? I always see this warning on my UI:

![Image](https://github.com/user-attachments/assets/1e4e1d4e-8257-4535-8373-e6e8b60646bf)

Also, if this is true for accessibility, is the same true for the exporting module as well?

**Comment by thedanchez** [comment]
@TorsteinHonsi moreover, I could not find what you were referring to in the Highcharts changelog. Can you point to which release notes that change was made for?

**Comment by thedanchez** [comment]
> [@TorsteinHonsi](https://github.com/TorsteinHonsi) moreover, I could not find what you were referring to in the Highcharts changelog. Can you point to which release notes that change was made for?

Nevermind, I just found it: https://www.highcharts.com/docs/getting-started/version-12
