### ISSUE TITLE
Stacked Area - Step - Datetime Issue

### ISSUE THREAD

**Issue by mark007** [highcharts/highcharts#2230]
Hi,

We are using a stacked area chart, with the step option set to true, and with specific datetime stamps on each point. We think there is an issue when using this combination of highchart options but want to get confirmation of this.

Please see the below jsfiddle.
http://jsfiddle.net/aeREv/

We have two sets of data in our series to illustrate the issue. Each set has two date / values. At one point in the graph we expect the value from Asia (100) to overlap with Africa (10) and so expect to see the stacked chart reach a value of 110 for a section of the chart, but at no point do we see this.

We don't have exactly matching dates / times and we won't in our final product so are wondering is this an issue with highcharts, or something thats not supported? Why is 110 never reached at any point in the chart?

Regards,
Mark

**Comment by KacperMadej** [comment]
For proper stacking please set the same x values (matching times) for both data sets. Demo: http://jsfiddle.net/aeREv/2/ 

Stacking for not matching data sets is not supported - you could suggest this as an enhancement idea on Highcharts' [userVoice](https://highcharts.uservoice.com/).
