### ISSUE TITLE
Chart tooltip header not showing depending on xDateFormat

### ISSUE THREAD

**Issue by 0ip** [highcharts/highcharts#22316]
#### Expected behaviour
Changes to the `xDateFormat` string/format shouldn't affect the tooltip header showing or not.

For example `xDateFormat: '%a %d.%m.%y'` properly shows as:
![image](https://github.com/user-attachments/assets/aafd380a-cc80-4250-9c88-b2a2930372f0)

#### Actual behaviour

However, with `xDateFormat: '%a %d.%m.%y %H:%M'` (only time formatting added), the tooltip header disappears/doesn't work anymore:
![image](https://github.com/user-attachments/assets/9e744247-0202-4e82-a282-55871c4b737d)

So, setting the `xDateFormat` to a certain string/format, apparently a format including time, has the consequence of the tooltip header not appearing anymore. 

See the minimal example: jsfiddle: https://jsfiddle.net/0g5y8jzu/

```
Highcharts.chart('container', {

    xAxis: {
        type: 'datetime'
    },

    tooltip: {
        xDateFormat: '%a %d.%m.%y %H:%M',
        headerFormat: '<span>{point.key}</span><br>',
        pointFormat: `<b>{point.y}</b> <small>°C</small> `,
        useHTML: true,
        shared: true
    },

    plotOptions: {
        series: {
            pointStart: '2012-01-01',
            pointInterval: 24 * 3600 * 1000
        }
    },

    series: [{
        data: [
            29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1,
            95.6, 54.4
        ]
    }, {
        data: [
            29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1,
            95.6, 54.4
        ].reverse()
    }]
});
```

#### Live demo with steps to reproduce
https://jsfiddle.net/0g5y8jzu/

#### Product version
Highcharts 12.0.2

#### Affected browser(s)
Chrome

**Comment by hubertkozik** [comment]
Hi @0ip! To fix your problem you should set the first letter of `point.key` in `headerFormat` as uppercase. You can it, by using the built-in `ucfirst` method.

**Live demo:** https://jsfiddle.net/BlackLabel/Ldqzp56c/
**Changelog:** https://www.highcharts.com/changelog/#highcharts-v12.0.0

I don't know if this is a bug or if this behaviour should be documented. Can I ask for your opinion @TorsteinHonsi?

**Comment by TorsteinHonsi** [comment]
@hubertkozik Definitely looks like a bug to me, though I haven't dug into it.

**Comment by TorsteinHonsi** [comment]
I think I've got it. Will wrap it up tomorrow.

```diff
diff --git a/ts/Core/Tooltip.ts b/ts/Core/Tooltip.ts
index d64680c1d7..212c8bd56b 100644
--- a/ts/Core/Tooltip.ts
+++ b/ts/Core/Tooltip.ts
@@ -1730,8 +1730,14 @@ class Tooltip {
                 (point.tooltipDateKeys || ['key']).forEach(
                     (key: string): void => {
                         formatString = formatString.replace(
-                            new RegExp('point\\.' + key + '([ \\)}])', ''),
-                            `(point.${key}:${xDateFormat as string})$1`
+                            new RegExp('( |{)point\\.' + key + '([ \\)}])', ''),
+                            (match, cap1: string, cap2: string): string =>
+                                // Add parantheses only if this is a function
+                                // argument (#22316)
+                                (cap1 === '{' ? cap1 : ' (') +
+                                `point.${key}:${xDateFormat as string}` +
+                                (cap1 === '{' ? '' : ')') +
+                                cap2
                         );
                     }
                 );
```
