### ISSUE TITLE
V12 regression: Adding custom datetimeformat garbles tooltip

### ISSUE THREAD

**Issue by anajavi** [highcharts/highcharts#22329]
#### Expected behaviour
Adding a custom dateformat function that returns something that begins with '+' returns `01.01.2012 00:01:16 +0100`on v11.
```js
Highcharts.dateFormats.O = function (timestamp) {
	return "+0100"
};
```

#### Actual behaviour

In v12 the output becomes `{ucfirst "01.01.2012 00:01:16 +0100"}`

#### Live demo with steps to reproduce
https://jsfiddle.net/5pvawgte/

#### Product version
Highcharts 12.0.2

#### Affected browser(s)
Chrome 131

**Comment by anajavi** [comment]
This is related to a previous feature request:
https://github.com/highcharts/highcharts/issues/20834

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! A fix is on its way.
