### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by ssimnv** [highcharts/highcharts#22347]
Hi guys,
We update Highcharts from 11.4.8 to 12.0.2 and got error: TypeError: Cannot destructure property 'animObject' of 'n(...)' as it is undefined. 

Seems like it happens after importing module 'highcharts/modules/pattern-fill';

Stack trace: lang object to defined the noData label

```
{
   noData: {
      useHTML: true
   },
   land: {
      noData: 'Label'
   }
}
```

**Comment by hubertkozik** [comment]
Hi @ssimnv! I've testes this demo: https://jsfiddle.net/BlackLabel/doz9kjwL/ and everything works correctly. Can you send a demo with a reproduced issue?

**Comment by ssimnv** [comment]
It seems the case, that imported module can't find Highcharts instance in new import way. 
In case we are using angular-highcharts library

**Comment by hubertkozik** [comment]
Here's the demo of Highcharts with `patten-fill` and `no-data-to-display` modules using `highcharts-angular` integration: https://stackblitz.com/edit/highcharts-angular-line-959pdkzx?file=src%2Fapp%2Fapp.component.ts

Everything seems to work correctly. If you are still having problems, please recreate the issue in the online editor.
