### ISSUE TITLE
Zooming Breaks the x-positioning of columns 

### ISSUE THREAD

**Issue by skawaguchi** [highcharts/highcharts#2234]
Example on jsFiddle:
http://jsfiddle.net/skawaguchi/6J5UH/
1. Zoom in and out (by clicking Reset Zoom) until you see step 2
2. The columns and labels get mashed together so that they're overlapping and pushed to either the left or right.

**Comment by oysteinmoseng** [comment]
Closing this, as not able to reproduce.
