### ISSUE TITLE
Stock chart area fill from baseline

### ISSUE THREAD

**Issue by x1c0** [highcharts/highcharts#22362]
Hello, 

I spend some hours trying to do this using highcharts and I can't make it, is this possible?

<img width="978" alt="image" src="https://github.com/user-attachments/assets/889b4475-ee03-493e-b1cc-1d48eaad551f" />

I got this far: https://jsfiddle.net/zsw4qtr5/19/

I would just like to show the red area here:
<img width="762" alt="image" src="https://github.com/user-attachments/assets/e39112d3-7993-4811-9dc6-db146c719711" />

Thank you in advance!

**Comment by hubertkozik** [comment]
Hi @x1c0! Yes, the chart from your screenshot can be configured in Highcharts: https://jsfiddle.net/BlackLabel/25xoc1vs/

We use GitHub as a tool for bugs/feature request tracking and your question is strictly a support question. Feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
