### ISSUE TITLE
tooltip header becomes undefined when hovering over a point for the second time

### ISSUE THREAD

**Issue by VitorTS** [highcharts/highcharts#22368]
#### Expected behaviour
Tooptip header stays the same

#### Actual behaviour

https://github.com/user-attachments/assets/bd8646b9-98ba-4b05-97ef-928b766de96f

This seems to happen because in [this line](https://github.com/highcharts/highcharts/blame/4f19139ad22660f66ee320d14807ef757b4a1495/ts/Extensions/DataGrouping/DataGrouping.ts#L154) the value for `point.key` gets overwritten from `1727740800000` to `October 2024` then on the second run it tries to format `October 2024` but fails:

first tooltip hover:
<img width="582" alt="Screenshot 2024-12-13 at 12 07 50" src="https://github.com/user-attachments/assets/e181d4dc-2b1e-42f4-a239-f401cebc26e2" />

second tooltip hover:
<img width="582" alt="Screenshot 2024-12-13 at 12 08 22" src="https://github.com/user-attachments/assets/75a87c1f-613e-45ec-9d3c-330b700c5e3b" />

#### Product version
highcharts@12.0.2

#### Affected browser(s)
chrome

**Comment by bferreira** [comment]
We are also seeing this when using the xDateFormat property

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!
I'm closing this as #22371 is the same issue but with live reproduction steps.
