### ISSUE TITLE
Require show degree in the polar chart like this, as per the image

### ISSUE THREAD

**Issue by deepak626k** [highcharts/highcharts#22391]
#### Expected behaviour
<img width="412" alt="image" src="https://github.com/user-attachments/assets/6c4ca357-980c-4802-a3ac-a7724c2f1e7e" />

We want the polar circle to represent angle like this. Please assist here.
0, 22.5 45, 67.5, 90,112.5,135, 157.5 to cover full circle

#### Actual behaviour
<img width="461" alt="image" src="https://github.com/user-attachments/assets/803fb0a1-0074-4000-a6a3-cc9f34769de0" />

#### Live demo with steps to reproduce

export const basicChartOptions: Highcharts.Options = {
  chart: {
    polar: true,
    backgroundColor: '#F5F7FA',
    marginTop: 20,
  },
  title: {
    text: '',
  },
  pane: {
    startAngle: 90,
    endAngle: 360 + 22.5,
  } as PaneOptions,
  xAxis: {
    labels: {
      format: '{value}°',
    },
    tickPositions: [0, 22.5, 45, 67.5, 90, 112.5, 135, 157.5],
    reversed: true,
  },

  yAxis: {
    min: 0,
  },
  tooltip: {
    formatter(this: TooltipFormatterContextObject) {
      const opt = this.point.options as SeriesData
      return `${opt?.y?.toString()}D`
    },
  },
  legend: {
    margin: 10,
  },
  credits: {
    enabled: false,
  },
  plotOptions: {
    series: {
      pointStart: 0,
      pointInterval: 45,
    },
    column: {
      pointPadding: 0,
      groupPadding: 0,
    },
  },
  series: [
    {
      type: 'scatter',
      name: 'Astigmatism in D',
      data: [
        [0, 12], // At 0 degrees, value 12
        [15, 11], // At 15 degrees, value 11
        [30, 10], // At 30 degrees, value 10
        [45, 8], // At 45 degrees, value 8
        [60, 6], // At 60 degrees, value 6
        [75, 5], // At 75 degrees, value 5
        [90, 4], // At 90 degrees, value 4
        [105, 3], // At 105 degrees, value 3
        [120, 5], // At 120 degrees, value 5
        [135, 7], // At 135 degrees, value 7
        [150, 7], // At 150 degrees, value 7
        [165, 6], // At 165 degrees, value 6
        [180, 3], // At 180 degrees, value 3
      ],
      pointPlacement: 'between',
    },
  ],
  exporting: {
    enabled: false,
  },
}

**Comment by hubertkozik** [comment]
Hi! My colleague has answered you already here: https://github.com/highcharts/highcharts/issues/22382#issuecomment-2551165873 Please, do not duplicate the topics. Also, we use GitHub as a tool for bugs/feature request tracking and your question is strictly a support question. Feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
