### ISSUE TITLE
Reset zoom button test is mis-aligned

### ISSUE THREAD

**Issue by charlie-ashford** [highcharts/highcharts#22394]
#### Actual: Text is mis-aligned
![55503d5a5dc70dd12b1517cc8e0e4466](https://github.com/user-attachments/assets/7a7e0986-a84e-4f14-bb59-05e7fa4a6157)

#### Product version
Highcharts  

#### Affected browser(s)
Chrome, I cannot check others

#### Code
Reset zoom button code starts on line 882: https://github.com/charlie-ashford/mrbeastGraph/blob/main/index.html#L882

**Comment by karolkolodziej** [comment]
Hi @charlie-ashford! 
Thank you for reporting.

_Internal note:_
[Simplified demo](https://jsfiddle.net/za36715t/)
Bisected to: https://github.com/highcharts/highcharts/commit/03f90af2a84e1278e7c915a07dde768b0eb1ffdd
@TorsteinHonsi
