### ISSUE TITLE
Highcharts Errors Preventing Chart Rendering

### ISSUE THREAD

**Issue by notRiyad** [highcharts/highcharts#22423]
#### Expected behaviour
Charts should load successfully using fetched data from an SQL database. This functionality has been operational since September. The issue is unrelated to library import methods or sources.

#### Actual behaviour
After recent modifications to the current version of the application, numerous Highcharts errors are displayed in the console, preventing the charts from rendering. To restore functionality, I must revert to an older Highcharts version by replacing:
**<script src="https://code.highcharts.com/highcharts.js"></script>** with **<script src="https://code.highcharts.com/12.1.0/highcharts.js"></script>**

Additionally, I cannot access the Highcharts forum for support as it states I am banned, despite never having posted or accessed the forum previously.

Console Errors
Below are examples of the errors encountered:

Uncaught TypeError: Cannot read properties of null (reading 'closest')

Location: highcharts.js:8:898, highcharts.js:8:1778, highcharts.js:9:272787.
highcharts-3d.js:9 Uncaught TypeError: Cannot read properties of undefined (reading 'Color')

Location: highcharts-3d.js:9:804, highcharts-3d.js:9:964.
exporting.js:11 Uncaught TypeError: Cannot read properties of undefined (reading 'AST')

Location: exporting.js:11:441, exporting.js:11:465.
export-data.js:12 Uncaught TypeError: Cannot read properties of undefined (reading 'AST')

Location: export-data.js:12:397, export-data.js:12:402.
accessibility.js:12 Uncaught TypeError: Cannot read properties of undefined (reading 'Templating')

Location: accessibility.js:12:929, accessibility.js:12:1137.
sunburst.js:10 Uncaught TypeError: Cannot read properties of undefined (reading 'Templating')

Location: sunburst.js:10:649, sunburst.js:10:752.
sankey.js:11 Uncaught TypeError: Cannot read properties of undefined (reading 'SeriesRegistry')

Location: sankey.js:11:579, sankey.js:11:657.
dependency-wheel.js:12 Uncaught TypeError: Cannot read properties of undefined (reading 'SeriesRegistry')

Location: dependency-wheel.js:12:503, dependency-wheel.js:12:543.
networkgraph.js:11 Uncaught TypeError: Cannot read properties of undefined (reading 'SVGElement')

Location: networkgraph.js:11:495, networkgraph.js:11:535.

#### Product version
Highcharts Core, latest version (presumably 12.1.1 or newer).

#### Affected browser(s)
Google Chrome

**Comment by nickautomatic** [comment]
Just wanted to add that this is not just you: I'm experiencing the same issues with v12.1.1 (same console errors, chart not rendering), and have also had to roll back to v12.1.0 to fix it.

**Comment by tsulli** [comment]
We are also experiencing the same errors with the update to 12.1.1

**Comment by notRiyad** [comment]
I have read this correctly:
![image](https://github.com/user-attachments/assets/27d6d0dd-b0d0-4a38-af93-141084a5645c)

However, i tried to comment the module scripts and left only the main highchart import however it doesn't work. Any insight ?

Example:
<script src="https://code.highcharts.com/highcharts.js"></script>

**Comment by russ-schumacher** [comment]
Similar errors here, and similarly reverting to 12.1.0 got things working again.

**Comment by pgrennin** [comment]
for me the problematic code was.   
<script src="https://code.highcharts.com/stock/highstock.js"></script>

I had to import highstock as a module and revert version like this: 
<script src="https://code.highcharts.com/12.1.0/highcharts.js"></script>
<script src="https://code.highcharts.com/12.1.0/modules/stock.js"></script>

**Comment by btelliot** [comment]
Similar errors here.  I need to revert to a previous version of highcharts.

**Comment by vanjabucic** [comment]
error points to `pageLang` rework:
https://github.com/highcharts/highcharts/commit/8f9c8fdbad45debc668e49f8cb50233622f0a397#diff-7634d0afcacba29f99d533afd48ea47264f268b3bc293ba8682f4adc5bf21bdeR208

**Comment by jleahy2** [comment]
> for me the problematic code was. `<script src="https://code.highcharts.com/stock/highstock.js"></script>`
> 
> I had to import highstock as a module and revert version like this: `<script src="https://code.highcharts.com/12.1.0/highcharts.js"></script>` `<script src="https://code.highcharts.com/12.1.0/modules/stock.js"></script>`

Yup, rolling back and locking to 12.1.0 fixed it for me too.  Thanks for this.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, and I'm very sorry for the inconvenience! The error comes from trying to access `document.body` before it was defined. It happens when loading Highcharts v12.1.1 from the `head` section of the page. Unfortunately all our tests, samples and demos loads Highcharts from the `body`. Fix coming up with v12.1.2 within an hour.

#### Workaround
Revert to 12.1.0, or move the `script` tags to the body.

**Comment by TorsteinHonsi** [comment]
Version 12.1.2 is out now.
