### ISSUE TITLE
`mouseout` event fired on `mousemove` on `chart.container`

### ISSUE THREAD

**Issue by nishikantparmariam** [highcharts/highcharts#22436]
#### Expected behaviour
My use-case is to perform an action when mouse is moved out of the chart container. For this I've attached a `mouseout` event listener on `chart.container`.

#### Actual behaviour

It turns out that while moving mouse over the chart, the callback is being triggered. May be some element in the overlay tooltip is causing browser to think that mouse is outside the `chart.container` ?

#### Live demo with steps to reproduce
Reproducer: **https://jsfiddle.net/xca4o8jz/**

![mouseout-event](https://github.com/user-attachments/assets/bd318c94-6158-46a5-90ef-b877ce3c5a97)

#### Product version
Highcharts 10.3.3

#### Affected browser(s)
Chrome and Firefox

---

Would be really helpful if you can provide a workaround for this.

**Comment by hubertkozik** [comment]
Hi @nishikantparmariam! Based on my knowledge and MDN documentation: https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseout_event this is the correct behaviour:

> The mouseout event is fired at an [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element) when a pointing device (usually a mouse) is used to move the cursor so that it is no longer contained within the element or one of its children.

You are attaching a `mouseout` event to the container element, which contains SVG as its children and that SVG includes many elements (groups, paths etc), which cause the `mouseout` event to fire.

If you would like to fire some logic after leaving the container element you should use `mouseleave` event. `mouseleave` and `mouseout` are similar but differ in that `mouseleave` does not bubble and `mouseout` does.

**Live demo:** https://jsfiddle.net/BlackLabel/kyd4t5sq/

Let us know if that was what you were looking for.

**Comment by hubertkozik** [comment]
Great to hear! I'll close this issue for now :)
