### ISSUE TITLE
Option to remove visual gaps for missing data points in column charts

### ISSUE THREAD

**Issue by The-Lone-Druid** [highcharts/highcharts#22447]
**Description:**

Currently, when using a column chart with multiple series, if a data point is missing for a specific series and category (e.g., "Formica Navigation" missing data for July and Aug '24 in the provided example), Highcharts leave a visual gap in the chart. This accurately represents the missing data but can sometimes create an undesired visual effect, especially when comparing multiple series with varying data availability.

**Request:**

Is it possible to provide an option to remove these visual gaps and "shift" the remaining columns to create a continuous flow? This would visually close the gaps where data is missing while maintaining the integrity of the x-axis categories.

![image](https://github.com/user-attachments/assets/b25ecdef-2021-4529-bc23-ce30fbd985b0)

**Comment by hubertkozik** [comment]
Hi @The-Lone-Druid! I think you are looking for `centerInCategory` option, already implemented in Highcharts: https://api.highcharts.com/highcharts/plotOptions.column.centerInCategory

We use GitHub as a tool for bugs/feature request tracking and your question is strictly a support question. Feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart
