### ISSUE TITLE
Polar chart alternateGrid Color along X axis does not work as expected

### ISSUE THREAD

**Issue by starquake** [highcharts/highcharts#2248]
See: http://jsfiddle.net/jvisser/NeHFt/

Here's a polar chart with an alternateGridColor set for both the X and Y axis. The alternateGridColor for X axis does not work as expected. I think the expected result would be that the entire Category A is Red and the entire Category B is white.

**Comment by pawelfus** [comment]
I'm not sure about the height - should this be configurable, for example by `height`? We don't have such option for standard bands. I guess xAxis band should end in the center.

**Comment by highslide-software** [comment]
> I'm not sure about the height - should this be configurable, for example by height?

I think this is inherited from the plot band logic, which gives it a default `innerSize`. But I'm not sure if it is possible to override it in case of alternative grid colors.
