### ISSUE TITLE
make colors array correspond to the serie index

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2254]
example (pseudocode):

```
new chart {
    colors: [red, green, blue]
}
```

Now, when adding a serie with `.addSeries()`, the color of this serie is `red`.
Remove that serie and add a new serie, now this serie is `green`.
I think it would be more logical for this serie to be `red` again.

So, no matter when a serie is added or removed, I would vote for the serie to have the corresponding color from the colors array.

**Comment by oysteinmoseng** [comment]
This is still relevant as an enhancement. 

Can it also be expanded to work for automatic series naming? Adding two series, removing the first one, and then adding a new series results in both series being named "Series 2". While there are still 2 series in the chart, the name of the first series has not changed, and as such it might be more intuitive to always increase the number.
