### ISSUE TITLE
Reopen issue #1100 - Max/Min Padding not working with Navigator 

### ISSUE THREAD

**Issue by calvinhu** [highcharts/highcharts#2263]
Hi, I was wondering if you could take another look at [Issue #1100](https://github.com/highslide-software/highcharts.com/issues/1100). I think it's similar to my issue.

The error I'm encountering is that I wish to set some initial padding on the Navigator such that the range selector bar doesn't cover the first and last points. I tried to set some padding in navigator > xAxis > minPadding/maxPadding, but it's not having an effect.

Here's a JSFiddle of the problem:
http://jsfiddle.net/w2aKK/29/

Let me know if you need any additional information.
Thanks!

**Comment by oysteinmoseng** [comment]
This is still relevant, `min/maxPadding` on Navigator seems to not have any effect. The workaround seems to function well, so perhaps we should add it to the code now? http://jsfiddle.net/w2aKK/36/

**Comment by sebastianbochan** [comment]
You an apply the o`overscroll` parameter instead of maxPadding.

Demo:
- http://jsfiddle.net/BlackLabel/a96rjusv/
