### ISSUE TITLE
setTitle on hidden chart -> titles overlap (when useHTML)

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2267]
http://jsfiddle.net/W4EEg/13/

only applies when `useHTML` is on

**Comment by oysteinmoseng** [comment]
This is still relevant. One way to solve it could be to check for `display: none` on container, and move the container offscreen for rendering, before changing it back to `display: none`.

**Comment by TorsteinHonsi** [comment]
Updated *workaround*:

Use the thorougher `chart.update` intead of the cheaper `chart.setTitle`: http://jsfiddle.net/W4EEg/35/
