### ISSUE TITLE
Navigator series is drawn outside navigator area when 'yAxis:{max}' is set

### ISSUE THREAD

**Issue by bvandenberg** [highcharts/highcharts#2271]
Is would be preferable when the chart is clipped to the navigator area when a max y-value is set for the navigator series. Please see attached image. 

![highstock-clip](https://f.cloud.github.com/assets/5312938/1179574/afd6a20c-21d8-11e3-8455-eb36ae990161.PNG)

**Comment by sebastianbochan** [comment]
Fixed since 4.0.0.
