### ISSUE TITLE
Ignore mouse tracking when mousebutton is pressed

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2274]
When dragging other elements over a chart or taking screenshots (selecting an area while hovering the chart), I think the expected behaviour is that the chart doesn't respond to the mouse over events.

**Comment by oysteinmoseng** [comment]
This is still a relevant suggestion. I think the most flexible way to handle it would be to pass along button information in the event, but still fire it. That way, the implementer can decide whether or not to ignore the event for mousedowns.
