### ISSUE TITLE
animation for addPoint does not work if only one point

### ISSUE THREAD

**Issue by jardakotesovec** [highcharts/highcharts#2278]
If there is initially only one point and second is added via addPoint - it ignores animation. It works fine with more points.
Example:
http://jsfiddle.net/VEwfF

**Comment by KacperMadej** [comment]
Working fine since version 4.2.6 - http://jsfiddle.net/VEwfF/3/
and with the current version (5.0.10) - http://jsfiddle.net/VEwfF/4/

Please reopen in case of regression.
