### ISSUE TITLE
High Chart disappears when hover on it

### ISSUE THREAD

**Issue by fatimasherin** [highcharts/highcharts#2307]
Hi,

We are a company who has license for highcharts. The charts were working fine until chrome version 28.0.1500.95 but now (chrome Version 29.0.1547.76 m) when we hover on the chart it disappears the parts we hover. This started happening after chrome version 28.0.1500.95.

 
I have attached some images for you to get a clear idea about the bug underneath.
Please look in to it ASAP.

![chrome_version_28 0 1500 95](https://f.cloud.github.com/assets/5591424/1251230/8e1189bc-2b1e-11e3-9d94-54b67bfd5788.PNG)

![chrome_version_29 0 1547 76 m](https://f.cloud.github.com/assets/5591424/1251231/932ba040-2b1e-11e3-8d20-9e192bac2138.PNG)

Thank you.

**Comment by sebastianbochan** [comment]
Closed due to missing demo.
