### ISSUE TITLE
Non-stacked waterfall

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2321]
Well, it just doesn't work. 
Example: http://jsfiddle.net/AFjAG/16/

**Comment by j4m3s** [comment]
Really pleased this is fixed, thank you!  We need to group differently though so it's three waterfalls on the same chart (see https://www.finanscapes.com/RT/Plan/Product/Overview.html?SelectProduct=15819&PublishedPlan=ehexe040 for our current workaround).  

It would be much nicer to use a proper waterfall chart, but putting the series data into an array (as we do for grouping column charts) doesn't work.  I don't get an error either (see http://jsfiddle.net/ecmjktq3/2/).

I've trawled the docs including the waterfall plotOptions but can't find out whether what I'm doing is simply not supported.  (btw the stacking: false option does have an effect on waterfall charts but isn't documented).
