### ISSUE TITLE
Disappearance dataLabel from the chart 

### ISSUE THREAD

**Issue by kuflash** [highcharts/highcharts#2329]
Good day! There was such a problem. Here is the graph:

http://jsfiddle.net/kuflash/LM7KB/2/

Inside the column displays the value of this schedule. With styles I leveled it to the bottom.

We schedule a restriction on the y to a maximum of 30 units. And if the graphics will be done better that the maximum value, the internal label disappears. Here is an example of exceeding the maximum zancheniya:

http://jsfiddle.net/kuflash/LM7KB/3/

How can I solve this problem?

**Comment by sebastianbochan** [comment]
Works correct since 4.0.0.
