### ISSUE TITLE
exporting-server: pdf exports overwrite each other

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#2332]
This is related to #2331. When converting a pdf, you get a link to a file and not the file itself, for example "c:/dev/chart.pdf". You then have to read that file as soon as you possibly can because the next export will use the same name and overwrite the other. 

If running on a busy server it may happen that the wrong pdf is sent back to the user. Ideally the exported file would not touch disk at all. At least not when doing a synchronous call (which the api is doing).

**Comment by oysteinmoseng** [comment]
This is still relevant. Demo: http://jsfiddle.net/s98bzn8g/.

@cvasseng Is this considered a bug, or just misuse?

**Comment by cvasseng** [comment]
There's an undocumented POST argument - `filename` - that can be used to override the default name. One solution could be to set that to a `uuid` (or a `chart.title` + `id` combo) in the export module.

**Comment by cvasseng** [comment]
Scratch that - the issue is what gert mentioned above, not the names of the file.

**Comment by oysteinmoseng** [comment]
Aha, in that case we would presumably have to fix this in the export module of Highcharts
