### ISSUE TITLE
exporting-server: Remove jQuery dependecy

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#2334]
The script highcharts-convert.js that runs in phantomjs to convert charts loads jQuery. T

This could probably be removed now that we have a standalone framework. jQuery is currently used to find elements by class and id and to load scripts.

**Comment by TorsteinHonsi** [comment]
@gvaartjet This is an old one... What's the status?

**Comment by TorsteinHonsi** [comment]
@gvaartjes

**Comment by gvaartjes** [comment]
Status = It has never been prioritized

Relatively small work, like Erik said, if we use the standalone-framework it's only used for finding elements.

We could update it, according the plans we have for the standalone framework.

**Comment by TorsteinHonsi** [comment]
Okay, so when we release HC 4.2 we can remove jQuery? Or do we use it for other tasks?

**Comment by gvaartjes** [comment]
- It's only used for querying DOM elements. 
- But it's not related to release of 4.2. in my opinion. 
- It's a enhancement

**Comment by TorsteinHonsi** [comment]
It's a controlled environment, so I guess we should use pure JS to query the DOM.

**Comment by gvaartjes** [comment]
https://github.com/highcharts/highcharts-export-server/commit/3a04c48448f167a32b78e2fb729f9d90b6f1d036
