### ISSUE TITLE
The changelog #2301 questions

### ISSUE THREAD

**Issue by timoyan** [highcharts/highcharts#2344]
Hi,  「Worked around InkScape bug where the hidden empty tooltip would display as a square in exported SVG. Closes #2301.」 
 I use the new Highchart version, but It seems like still exit when you open the SVG with the Inkscape.  
And I try the funnel, pie and line three type charts and I find only line chart works well. 
 I guess it may be the legend cause this problem…..  
Thanks for your help.

File Download: 
https://www.dropbox.com/s/f6srff52kewf5f7/pie.svg

**Comment by KacperMadej** [comment]
Unable to recreate using current Highcharts and InkScape.
Please provide more info and the issue could be reopened.
