### ISSUE TITLE
Tooltip gets obfuscated by html labels

### ISSUE THREAD

**Issue by stoffie** [highcharts/highcharts#2347]
http://jsfiddle.net/LLExL/1936/

As you can see from the fiddle, using the given configuration, when the tooltip is displayed, links on the left side of the graph do not fade out, as the rest of the graphic object under the tooltip do.
Tested using ff 24.0 and chromium Version 28.0

Thank you for your time

**Comment by oysteinmoseng** [comment]
This is still relevant.

Should we consider automatically using an HTML tooltip when user specifies HTML labels?
