### ISSUE TITLE
Why did `inputBoxStyle` get deprecated?

### ISSUE THREAD

**Issue by ashclarke** [highcharts/highcharts#2353]
This [property](http://api.highcharts.com/highstock#rangeSelector.inputBoxStyle) says has been deprecated since 1.2.5.

I'd like to know if there is a replacement coming, because now, if a date format is set for the inputs, an issue occurs where the text overflows the boxes that are supposed to contain it. It also happens when [modifying](http://jsfiddle.net/ZFCja/1/) the default fiddle.

Here is an example of my implementation (similar to the modified fiddle):

![image](https://f.cloud.github.com/assets/963023/1315701/6e237912-328a-11e3-8c5d-3ab5c863839d.png)

**Comment by externuz** [comment]
So, what about inputBoxBackgroundColor ?

**Comment by highslide-software** [comment]
You can do it by CSS: http://jsfiddle.net/highcharts/ZFCja/7/

**Comment by externuz** [comment]
How can I do it? There is no backgroundColor change in example.

**Comment by highslide-software** [comment]
What browser are you using? This is what I see in Chrome:

![skjermbilde 2015-10-01 kl 10 41 45](https://cloud.githubusercontent.com/assets/227836/10216410/17dc7b22-6829-11e5-95ee-dabf16f32ae4.png)
