### ISSUE TITLE
Rendering issue with Safari after updating pie charts

### ISSUE THREAD

**Issue by ehinter** [highcharts/highcharts#2356]
I think this issue may be related to this:

https://github.com/highslide-software/highcharts.com/issues/1208

But I'm using the latest Highcharts (3.0.6) and still seing a similar problem. Basically if I have a pie chart in Safari that gets updated frequently using "setData", at some point the chart will fail to render properly. I've reproduced in a fiddle (you may have to wait a bit for it to happen, but eventually on one of the updates the chart will render strangely). 

http://jsfiddle.net/JmUw9/2/

I'm running Safari 6.0.5 (8536.30.1) on Mountain Lion and I can't see this behavior on other browsers.

**Comment by oysteinmoseng** [comment]
Seems to work as expected with current code on current Safari. Closing for now. Feel free to reopen if still relevant.
