### ISSUE TITLE
X axis plot bands disappear when zooming in so that the plot band from dateis no longer visible

### ISSUE THREAD

**Issue by mikegodber** [highcharts/highcharts#2361]
This issue occurs with column series where a point placement of "between" is used, see here for the issue:

http://jsfiddle.net/uSYyy/2/

I have tried in the latest versions of chrome and firefox.

**Comment by ebett** [comment]
My fix
 redraw: () =>{
           let e =this.chart.chart.xAxis[0].plotLinesAndBands[0].svgElem.element;
            e.setAttribute('visibility', 'visible')
          }
