### ISSUE TITLE
Polar chart - resizing 

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2366]
Rings are not related with others and some of them are out of chart.

Updated fiddle: http://jsfiddle.net/tempest549/2aWJb/3/

Try to resize window

**Comment by nhitchins** [comment]
+1
Also running into this issue

**Comment by KacperMadej** [comment]
Still an issue in version 6.1.3
Demo: http://jsfiddle.net/BlackLabel/1bzxr0Lw/
After update the orphaned ring is between ticks labelled 25 and 50.

**Comment by KacperMadej** [comment]
A solution here could be to allow rendering plot lines that will have zero width and height.

Pros:
- resolves problem with not updated `d`
- allows animation when going from something to nothing and back

Suspected con:
- fix reverts some changes of this commit: https://github.com/highcharts/highcharts/commit/6cfa2d198cb4a88c13a135bba63b547f7ff434ae
However, after testing in IE8 columns are looking good, so it doesn't look like breaking anything.
There are some errors throws, but are not related to this change and are already reported.
