### ISSUE TITLE
hideDelay on dynamic chart

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2377]
The hideDelay paramaters works well in static chart like here: http://jsfiddle.net/w3KKP/ but when we use addPoint, then tooltip doens't disappear.

http://jsfiddle.net/highcharts/LAFb9/

[Edited: simplified example]

**Comment by pawelfus** [comment]
Behaviour changed since v5 (at least), demo: http://jsfiddle.net/BlackLabel/LAFb9/2/
