### ISSUE TITLE
Html entity (special chars) issue

### ISSUE THREAD

**Issue by vimar** [highcharts/highcharts#2379]
Hi,

the default formatter render correctly html special chars such as < > except in one condition, a < used into "tooltip" : http://jsfiddle.net/Sleipne/fZTLW/1/

The xAxis is correct, but the tooltip (when mouse is hover the bar) containing data is broken.
We need to transform it as = &amp;lt;6% internally in order to make it working

**Comment by pawanvjadhav** [comment]
Just a thought , can't you resolve this if you set innerText instead of innerHtml in your SVGRenderer.html method ? 
wrapper.textSetter = function (value) {
                if (value !== element.innerHTML) {
                    delete this.bBox;
                }
                element.innerText = this.textStr = value;
                wrapper.htmlUpdateTransform();
            };

**Comment by ipip2005** [comment]
Any updates? Without useHTML: true, seems there is no way to show `&lt;` and `&gt;` at all. This might be an edge case, but it just looks like a bug when user input &lt; but shows left bracket instead.

**Comment by TorsteinHonsi** [comment]
So you want to show `&lt;` literally on the chart? See how it works today: http://jsfiddle.net/jwmq7/
