### ISSUE TITLE
Highstock - no tooltip formatter, point remains highlighted on mouseOut

### ISSUE THREAD

**Issue by sh1989** [highcharts/highcharts#2383]
Steps to reproduce:
- Create a highstock chart with one series of data
- Turn off the hover tooltip with: "formatter: function() { return false; }"

When hovering over points, you will see that a point changes to its highlighted state. When you mouse out the chart, the highlighted point remains highlighted. This behaviour differs to the default, where a point is deselected on mouse out.

Tested in Chrome and Firefox
See: http://jsfiddle.net/LLExL/1972/

**Comment by oysteinmoseng** [comment]
Seems to be fixed in the current version.
