### ISSUE TITLE
Multiple series compared by percent not indexing from 0%

### ISSUE THREAD

**Issue by jkotchoff** [highcharts/highcharts#2386]
1. Start with this example: http://jsfiddle.net/X6pXW/1/
2. Click the '6M', 'YTD' or 'All' timeframe buttons

Result: The series are no longer both indexed from 0%.
Expected: Both lines should show a percentage change of 0% at the beginning of the timeline.

**Comment by pawelfus** [comment]
Implemented in Highstock v6 by [`compareStart`](https://api.highcharts.com/highstock/plotOptions.series.compareStart) option: http://jsfiddle.net/BlackLabel/X6pXW/3/
