### ISSUE TITLE
Provide pre-formatted dates in custom tooltip formatter

### ISSUE THREAD

**Issue by ejain** [highcharts/highcharts#2392]
Highcharts does a great job auto-formatting dates both on the x-axis and in tooltips. Unfortunately I need a custom function to format my y-values, and /plotOptions/line/tooltip/pointFormat accepts only a format string and not a function, so I have to set /tooltip/formatter instead. From the formatter function, I can't get hold of the formatted date (e.g. Oct'13 or 20. Oct) as shown on the x axis (point.key), only the raw millis value.

http://jsfiddle.net/9Fke4/

**Comment by andremleblanc** [comment]
:+1:

**Comment by TorsteinHonsi** [comment]
Here's how to tap into the header formatter with Highcharts 4.2.1:
```js
            formatter: function() {
            	var tooltip = this.series.chart.tooltip,
                	item = this.point.getLabelConfig(),
					header = this.series.chart.tooltip.tooltipFooterHeaderFormatter(item);

                return header + this.y;
            }
```
[View it live on jsFiddle](http://jsfiddle.net/highcharts/9Fke4/8/).
