### ISSUE TITLE
Highcharts - Setting margin on title with subtitle does not put space between subtitle and plot area

### ISSUE THREAD

**Issue by millsb** [highcharts/highcharts#2397]
According to the API for the `margin` option under `title`:

> "The margin between the title and the plot area, or if a subtitle is present, the margin between the subtitle and the plot area. Defaults to 15."

The [provided example using a subtitle](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/title/margin-subtitle/) shows the space clearly between title and subtitle, and not between subtitle and plot area.

**Comment by jessegavin** [comment]
Fixing this bug (or implementing subtitle margin) would solve a lot of problems for me.

**Comment by zwakhall** [comment]
@jessegavin I tried your solution, but it doesn't change anything. Am I doing something wrong?

**Comment by jessegavin** [comment]
@zwakhall Which solution? My Pull request? or the `paddingBottom` solution?

**Comment by zwakhall** [comment]
@jessegavin I tried the paddingBottom solution.

**Comment by jessegavin** [comment]
Are you using `x`, `y`, `floating` properties on subtitle? If so, might not work.

Here's a working example. http://jsfiddle.net/0znorsd4/

**Comment by zwakhall** [comment]
@jessegavin Indeed I had some floating properties on the subtitle. I removed them, but it's still not working.

Although... I work with Firefox (33). I checked Chrome and there it works! Unfortunately this does not seem to be a generic solution. Thanks a lot for your help anyway.

**Comment by jessegavin** [comment]
Bugger. Thanks for the feedback about Firefox.

**Comment by multiviouskalogram** [comment]
I'm late on this, but doesn't Highcharts use svg to render the title by default? If you did opt to use html, the style options will respect more CSS rules such as padding. Just figured this out myself...
see: `useHTML: true`
based off the fiddle from @jessegavin 
http://jsfiddle.net/hould/40tsw35z/
