### ISSUE TITLE
Graph not rendered in Firefox when base tag is present.

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#24]
Reported at http://highslide.com/forum/viewtopic.php?f=9&t=6878

Notes 2012-01-03:
Demo: http://jsfiddle.net/highcharts/TuMwJ/26/

The problem is that internal URL references in SVG, to gradients and clip objects, are influenced by the base tag.

It also applies to Chrome. There doesn't seem to exist a better workaround than adding the full URI to the reference.

**Comment by TorsteinHonsi** [comment]
#### Status for this issue as of 2018

The cleaning of `window.location.href` and re-entering into the DOM is causing us problems with Checkmarx validation. Checked if this workaround with adding the full path to the internal pointers is still needed, and it turns out Safari (11.1) is the only modern browser requiring it. Chrome as of v54 and Firefox as of v52 do not need it.

**Comment by manojambati** [comment]
@TorsteinHonsi ,

Highcharts scattercharts graph click event on the points not working in firefox (latest version) when the html **<base>** tag is present. 
When <base> is removed getting the click event alert and it's working fine with or without **<base>** in other browsers.

https://jsfiddle.net/manojambati/ac1vbkeh/

**Comment by pawelfus** [comment]
Hi @manojambati - I think it's already reported here: #10283 - could you confirm? Thanks!

**Comment by manojambati** [comment]
@pawelfus yes it is the issue I reported in highcharts forum yesterday
