### ISSUE TITLE
negativeColor not in tooltip

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2400]
when hovering a point where the `negativeColor` is applied, the color in the tooltip of that serie is still the 'normal' color.
not sure if this is a bug or a feature.

**Comment by alobakov** [comment]
This does not appear to work in Styled mode when colorIndex and negativeColor are used for the series.
The highcharts-tooltip-box gets a highcharts-color-X class set based on the specified colorIndex, whether or not the given point has a negative value.
In addition, the highcharts-tooltip-box has no highcharts-negative class set, thereby making it impossible to style negative value tooltip boxes using a negative-specific CSS selector.

**Comment by pawelfus** [comment]
You are right @alobakov - it's a bug, reported as #7638

**Comment by alobakov** [comment]
Awesome! - Thank you.
