### ISSUE TITLE
Rangeselecor bug - FF 24

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2411]
Problem appears only in FF (24.0)

Steps to reproduce:
- move left handle to the right
- move right handle to the left
- drag range
- click on the left arrow
- as a result range moves to the right direction, instead of left

http://jsfiddle.net/L3t4s/9/

**Comment by oysteinmoseng** [comment]
Seems to work fine with current code and FF version. Closing for now. Feel free to reopen if still relevant.
