### ISSUE TITLE
Wrong gradient colors

### ISSUE THREAD

**Issue by eteubert** [highcharts/highcharts#2412]
Hi,

Example fiddle: http://jsfiddle.net/LLExL/2003/
The image shows: `rgb(200,200,255) != rgb(204,195,255)`

![screen shot 2013-10-29 at 12 34 01 2](https://f.cloud.github.com/assets/235918/1427616/68a370e2-408f-11e3-87df-0bd64b1cea15.png)

This happens *only* in Safari 7.0 on one of my 3 monitors: the internal Macbook Air (13-inch, Mid 2012) display. The colors are fine on the external displays. I am also unable to reproduce the bug in Chrome (30). Everything on Mac OS X Mavericks.

/update: I just realize it might be an issue of the ColorSnap tool and not related to highcharts at all. Feel free to close the issue if you think so too ;)

**Comment by pawelfus** [comment]
I think so too ;)
