### ISSUE TITLE
Labels fail with RTL text direction for divs

### ISSUE THREAD

**Issue by IVIR3zaM** [highcharts/highcharts#2423]
if direction of divs tags be RTL, lables are tumultuous in FireFox 25 and almost all versions of google Chrome. sample: http://jsfiddle.net/IVIR3zaM/MTb2L/
please see with FireFox 25, in FireFox 24 it is ok.
thanks

**Comment by oysteinmoseng** [comment]
Still an issue. `useHTML` workaround for labels and tooltip works.
