### ISSUE TITLE
zoom not precise using categories

### ISSUE THREAD

**Issue by jardakotesovec** [highcharts/highcharts#2424]
Simple example with categories:
http://jsfiddle.net/72gA7/1/

Simple example without categories:
http://jsfiddle.net/q63r5/1/

With categories it does not zoom (using mouse) exact range as is selected. For example - I dont include January dot and it still visible after zooming. 

Without categories it works correctly.

**Comment by kernc** [comment]
This is no longer an issue. With above fiddles, even with categories, the extremes are set to selection boundaries.

**Comment by TorsteinHonsi** [comment]
Great, thanks for the update!
