### ISSUE TITLE
Tooltip and xAxis dateTime label format not matching.

### ISSUE THREAD

**Issue by igctech** [highcharts/highcharts#2432]
For some reason the labels are computing different dates based on my data.

Here is an example of what I mean.
http://jsfiddle.net/95LX7/

If you notice the x-axis data point says May '13 but the tooltip says April 2013.

How can I get these consistent with each other.

**Comment by gowthambalashanmugam** [comment]
Any updates on above issue. i am gated with that. How to get exact date in xaxis and tooltip

**Comment by pawelfus** [comment]
Please, recreate issue in jsFiddle, we will take a look. Above issue is closed as not a bug in our library.
