### ISSUE TITLE
HighStock Chart 1.3.4 - Apple iPad issue tapping chart legend items

### ISSUE THREAD

**Issue by Ricbert** [highcharts/highcharts#2452]
When tapping items in the chart legend using an apple iPad with either iOS 6 or iOS 7, the response from the chart legend is inconsistent.
1. The legend item  (and consequently the associated chart item) toggle off and then immediately back on.
2. The legend item does not toggle off at all. A double or triple tap sometimes toggles it off.

With multiple taps, the legend item updates very slowly, flashing on, and off.

**Comment by waazes** [comment]
@skoryky could you be more specific?

**Comment by skoryky** [comment]
@waazes, what would you like me to elaborate about?

**Comment by waazes** [comment]
@skoryky, well i'm facing the exact same problem. I'm using Ionic framework (what uses fastclick) and i'd like to achieve the same result you described earlier. Could you by any chance give us a working example of this please? For example in fiddle or codepen.
I would really appreciate it.

Thanks,
K

**Comment by skoryky** [comment]
Did you try adapting the code I shared in my post from 9/16/2014?

**Comment by waazes** [comment]
@skoryky, I tried to create something like that but it didnt work.

**Comment by skoryky** [comment]
If you set up a JSFiddle, I'm happy to take a look.

**Comment by haio** [comment]
@skoryky great! it works for me

**Comment by DcSea** [comment]
@skoryky great! it works for me
and, you are so beautiful~
