### ISSUE TITLE
Problems with Highcharts exporting server: Encoding and quality

### ISSUE THREAD

**Issue by mungerj** [highcharts/highcharts#2454]
Note: I asked a question on StackOverflow, and the following issue was confirmed by another user (wergeld): http://stackoverflow.com/questions/19979916/problems-with-highcharts-exporting-server-encoding-and-quality

Problem: We are using our own export server to export charts from Highcharts. We followed the steps detailed on Highcharts website. We're using the second option, the export server based on Java and PhantomJS (1.9.2) on a Windows 2008r2 server, with Tomcat 6 and Java RE 1.7.0.45.

We're using Highcharts 3.07 and the corresponding export server.

Our export server works, but we are faced with 2 important problems:

1: Accentuated characters are displayed as squares on the exported charts. Everything is in UTF-8 on the HTML page from where charts are exported. When using export.highcharts.com as the exporting server, we don't have this problem.

2: Text on exported charts is blurry and has jagged edges. Again, when using export.highcharts.com as the exporting server, we don't have this problem.

Both problems can be seen by comparing the attached pics. The first one was exported using export.highcharts.com, and the second one using our exporting server. Note: the text problem isn't too obvious in the attached pics since they are reduced, but it is quite obvious at a better resolution.

![chart 30](https://f.cloud.github.com/assets/2229193/1543671/32bba4b2-4d5b-11e3-8207-00d42b264c80.png)

![chart 29](https://f.cloud.github.com/assets/2229193/1543677/453b7aea-4d5b-11e3-83e8-55f26a4f04a9.png)

We're using this jsFiddle for testing: http://jsfiddle.net/jmunger/99wkv/2/

**Comment by joedborg** [comment]
I get the same issue from within a Docker container, so I presume it is a missing library.  The thing is, I've installed every library is says to in the help.

**Comment by heqiang421** [comment]
i met same problem.i can't solve it?how to...
