### ISSUE TITLE
Highcharts setExtremes for datetime axis is not right

### ISSUE THREAD

**Issue by ibash** [highcharts/highcharts#2461]
Steps:
Open this fiddle: http://jsfiddle.net/P4NGt/1/
Click setExtremes

Expected:
The yellow bars (showing where the extremes were set) are at the far left and far right of the chart

Actual:
Despite setExtremes being called to a certain position, the bounds of the chart are well beyond the extremes

![screen shot 2013-11-15 at 12 09 20 pm](https://f.cloud.github.com/assets/204566/1553324/e4968266-4e31-11e3-874b-916196ab228b.png)

**Comment by kzoon** [comment]
I ran into this problem, simply by using zoom.

Consider this fiddle: http://jsfiddle.net/kzoon/2frz5j66/9/

Select March, and you get part of Februari and April in the bargain. Same goes for other zoom selections you make. 

I think that zoom should show the exact categories that the user selects.

**Comment by pawelfus** [comment]
Huh, with categories it is a bit tricky. Have you considered to set `minRange` to 0.5? Like this: http://jsfiddle.net/2frz5j66/12/

Some property like `roundExtremes` would be nice - something to work with `startOnTick` and `endOnTick` maybe? Like here: http://jsfiddle.net/2frz5j66/13/ (just with zoom to only one category)

**Comment by kzoon** [comment]
Using minRange 0.5 works with 1 zoomed column not with 2 or more. I guess I should have included a reference to this support forum link: http://forum.highcharts.com/highcharts-usage/too-many-columns-minrange-1-t33768/
