### ISSUE TITLE
Exporting: Default to no backend requirement

### ISSUE THREAD

**Issue by marcalj** [highcharts/highcharts#2464]
Would be more useful to use client-side chart export. Your server will appreciate this ;)

Here's my solution in a stackoverflow question:
http://stackoverflow.com/questions/15642145/highcharts-and-canvg-scaling-issue/20049435#20049435

Live demo:
http://jsfiddle.net/marcalj/EsPud/7/

So no backend required for exporting as image!

**Comment by oysteinmoseng** [comment]
Closing this, since we now have [client side export](https://www.highcharts.com/docs/export-module/client-side-export) officially supported.
