### ISSUE TITLE
PhantomJS serverside rendering from JSON to SVG not displaying images 

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#2478]
The images are there in the exported SVG, but they have a width of 0px

This is due to the onload event wasn't fired in SVGRenderer on this [line](https://github.com/highslide-software/highcharts.com/blob/d7fd36867226a31eab0268a11cecfe733f4d15ff/js/parts/SvgRenderer.js#L1770)

at the time the page.evaluate function returned with the SVG from the html document. At this time the SVG images were not updated by the event.

**Comment by oysteinmoseng** [comment]
Closing as this seems to work fine with the current export server.
