### ISSUE TITLE
Different padding on legend items in different browsers

### ISSUE THREAD

**Issue by moppa** [highcharts/highcharts#2479]
Hi

I created a test graph and viewed it both in Firefox and in Chrome. I notice a big difference in the size of the legend between the browsers. Firefox seem to add more padding to each legend item, or it does not adhere to some setting that has been made. This results in big differences on smaller graphs between browsers.

![Legend padding](https://f.cloud.github.com/assets/682231/1611478/3ac1bf5c-55ad-11e3-99dc-ebc7e3c0c15f.png)

http://jsfiddle.net/moppa/cMXyG/18/

**Comment by KacperMadej** [comment]
Unable to recreate using Highcharts version 7.0.3.
The font looks the same on IE11 / Firefox / Chrome:
![legend-font-same](https://user-images.githubusercontent.com/8960408/54876983-efbf8b00-4e18-11e9-9dc1-606344bbc14e.jpg)

Closing as unable to recreate.
Additional info: if a font is not rendered the same across different browsers and operating systems, then you could look for a font that doesn't have this problem - this font rendering is beyond Highcharts chart options.
