### ISSUE TITLE
columnrange should show range with negativeColor when range is negative

### ISSUE THREAD

**Issue by davhdavh** [highcharts/highcharts#2486]
https://github.com/highslide-software/highcharts.com/blob/master/js/parts-more/ColumnRangeSeries.js

at line 43, add:

if (height < 0) {
  height = -height;
  y = point.plotY;
  point.color = pick(point.color, options.negativeColor, options.negativeFillColor);
}

**Comment by oysteinmoseng** [comment]
Closing as this has been implemented: http://jsfiddle.net/L3az9kj9/
The range will show as negative if any part of the range is below the threshold.
