### ISSUE TITLE
Checkboxes do not show in legend in IE 11

### ISSUE THREAD

**Issue by rmayo** [highcharts/highcharts#2487]
The following jsFiddle is taken from the highcharts API (with the master.js referenced to make sure the highcharts code is up to date).

Notice that the checkboxes don't actually show up in IE 11.

http://jsfiddle.net/2YHge/

**Comment by cvasseng** [comment]
Hi! We're doing a bit of spring cleaning, and closing old issues. If you're still experiencing issues with this, please feel free to open a new issue! Thanks!
