### ISSUE TITLE
xAxis jumps up for all-0 column chart with minPointLength set

### ISSUE THREAD

**Issue by vrajesh-fx** [highcharts/highcharts#2493]
Hi,
When all the values of a column chart are zero, with minPointLength set, then xAxis jumps up. See demo here: http://jsfiddle.net/X2qaW/

Another user pointed this issue in stakoverflow here ( http://stackoverflow.com/questions/16706633/0-value-column-chart-highchart) but i think he missed mentioning that it only happens when all values of the column chart are 0 (atleast within the range selected)

Thanks

**Comment by oysteinmoseng** [comment]
This is still relevant with current code.
