### ISSUE TITLE
After zooming, hover state marker is not moved

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#2500]
http://jsfiddle.net/highcharts/76BuG/1/
1. Drag-zoom an area, and make sure the active hovered point is inside that area
2. When releasing the mouse, make sure not to move it.
3. The hover-point marker is in its previous position although the actual point and the tooltip has moved.

This also applies to touch zooming.

**Comment by soumyarbohidar** [comment]
Any fix version you would like to mention Torstein. I use "highcharts": "6.0.7" and able to reproduce this issue.

**Comment by pawelfus** [comment]
Hi @soumyarbohidar 
Could you recreate issue in jsFiddle? v6.0.7 looks fine: http://jsfiddle.net/BlackLabel/phayoz63/ 
Thanks!

**Comment by soumyarbohidar** [comment]
> Hi @soumyarbohidar
> Could you recreate issue in jsFiddle? v6.0.7 looks fine: http://jsfiddle.net/BlackLabel/phayoz63/
> Thanks!

I have updated the fiddle. I could not able to reproduce the error as i am able to fix it  just a configuration change. I forgot to add the below option highlighted in bold and italic. Thanks for your quick response.

marker: {
	**_enabled: true,_**
	states: {
	        hover: {
		       enabled: false
		},
		select: {
			enabled: true,
		        radius: 7,
			fillColor: undefined,
			lineWidth: 0
		}
	}
}

**Comment by pawelfus** [comment]
No problem, thanks for sharing the potential fix!

**Comment by ashwiniIot** [comment]
I am also facing the same issue, I wanna show marker points when I zoomed in on the line chart and when reset zoom it will show a normal line without markers.i set cropThreshold inside series  cropThreshold: 10000,

 xAxis: {
      // type: 'linear',
      // tickInterval: 24 * 3600,
      crosshair: true,
      labels: {
        autoRotation: false,
        formatter: xAxisFormatter,
      },
      events: {
        afterSetExtremes(event) {
          const enabled = event.min !== undefined;
          chart?.series[0].update({
            marker: {
              enabled,
            },
          });
        },
      },
    },

**Comment by pawelfus** [comment]
@ashwiniIot this issue was reported for versions before 6.0.7, later bug was fixed. Are you sure you are facing the same issue? Original issue seems to be fixed: http://jsfiddle.net/BlackLabel/oghnmpew/1/

And this is your event callback working fine: http://jsfiddle.net/BlackLabel/oghnmpew/ (note change `event.min` -> `event.dataMin`).

In case of similar problems, please contact our support team first: https://www.highcharts.com/blog/support/
