### ISSUE TITLE
lineColor on Flag series not implemented

### ISSUE THREAD

**Issue by nick** [highcharts/highcharts#2511]
This does not appear to be working: http://jsfiddle.net/3ARNg/

Expected behavior: The color of the border of the flag should be Black.
Actual behavior: The color of the border of the flag is Green.

As documented here http://api.highcharts.com/highstock#plotOptions.flags.lineColor

**Comment by pawelfus** [comment]
**Workaround:**

Enable lineColor in point attributes: 

    Highcharts.seriesTypes.flags.prototype.pointAttrToOptions.stroke = 'lineColor';

Demo: http://jsfiddle.net/3ARNg/1/

**Comment by pawelfus** [comment]
Works in the current version, demo: http://jsfiddle.net/czp9c7jy/1/
