### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#2519]
"handlersgive" at http://api.highcharts.com/highstock#Series
"seriesproperty" at http://api.highcharts.com/highstock#Series
"associateddto" at http://api.highcharts.com/highstock#Axis

**Comment by dandv** [comment]
@oysteinmoseng / @gvaartjes : another typo at https://www.highcharts.com/docs/chart-design-and-style/style-by-css

    The classic mode is still unaltered an available

**Comment by dandv** [comment]
At http://api.highcharts.com/highcharts/Chart.addSeries, "When adding data at the same time as the chart is **initiated**" -> `initialized`

**Comment by sebastianbochan** [comment]
Thank you for reporting! 
@jon-a-nygaard

**Comment by oysteinmoseng** [comment]
@dandv @jon-a-nygaard @sebastianbochan Fixed.

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng Remember the new API runs off JSDoc comments ;)

**Comment by dandv** [comment]
Another typo at https://www.highcharts.com/docs/chart-and-series-types/chart-types: `meaningfull`

**Comment by dandv** [comment]
At https://www.highcharts.com/docs/chart-and-series-types/scatter-chart: "A scatter chart draw a single point"

**Comment by dandv** [comment]
"these properties may be overridden my more specific rules" at https://www.highcharts.com/docs/chart-design-and-style/style-by-css

**Comment by sebastianbochan** [comment]
Thank you for the reporting.

@oysteinmoseng

**Comment by oysteinmoseng** [comment]
Fixed.

**Comment by dandv** [comment]
Found a broken link at https://www.highcharts.com/docs/working-with-data/data-intro - `series.data` links to https://api.highcharts.com/highcharts/#series.data, rather than (probably) https://api.highcharts.com/highcharts/series.line.data.

**Comment by jon-a-nygaard** [comment]
Thanks @dandv! I have corrected the link so it should work properly now.

**Comment by jon-a-nygaard** [comment]
@KacperMadej Yes, I agree. I found that it was caused by Google Tag Manager, so we decided to turn it off. The link looks better again.

Thanks for letting me know about it :)

**Comment by dandv** [comment]
At https://www.highcharts.com/docs/advanced-chart-features/annotations-and-fibonacci-retracements,

* "Annotation[s] can be built"
* "annotation structure::"
* "and **S**ix rectangular backgrounds "

**Comment by dandv** [comment]
At https://www.highcharts.com/docs/advanced-chart-features/boost-module, "[I]f set to `true`"

**Comment by jon-a-nygaard** [comment]
Fixed. Thanks again @dandv!

**Comment by dandv** [comment]
At https://api.highcharts.com/class-reference/Highcharts.Point.html#Point: "instaniate".

**Comment by jon-a-nygaard** [comment]
Fixed in https://github.com/highcharts/highcharts/commit/dcfa338f2706548ecee458de3b7388af84d3a8d1, api will be updated with the next maintenance release. Thanks @dandv.

**Comment by dandv** [comment]
At https://www.highcharts.com/docs/advanced-chart-features/freeform-drawing, "instanciate" should be "instantiate", and both links in the "The drawing API is documented in detail" paragraph are broken.

**Comment by jon-a-nygaard** [comment]
Fixed. Thanks @dandv, your contributions are very much appreciated! 👏

**Comment by dandv** [comment]
At https://api.highcharts.com/class-reference/Highcharts.Series.html#addPoint,

> series.If it is an array

**Comment by dandv** [comment]
A few more: "initiation" -> initialization

https://github.com/highcharts/highcharts/search?q=initiation

**Comment by sebastianbochan** [comment]
FYI @jon-a-nygaard  @oysteinmoseng

**Comment by jon-a-nygaard** [comment]
Thanks! 👍 I will look into fixing these during today.

**Comment by jon-a-nygaard** [comment]
The [PR with the fixes](https://github.com/highcharts/highcharts/pull/9955) is currently in review and is expected to be included in the next maintenance release.

Thanks again for the feedback.
