### ISSUE TITLE
Point destroy increases memory consumption (retained size)

### ISSUE THREAD

**Issue by hkskoglund** [highcharts/highcharts#2521]
I've tested the point destroy functionality in http://jsfiddle.net/hkskoglund/LzE6V/, ref. Highcharts.src. https://github.com/highslide-software/highcharts.com/blob/master/js/highcharts.src.js#L12631 

```
for (prop in point)
  point[prop] = null;
```

This will introduce new properties on the Point object shadowing the inherited properites/functions from the Point.prototype.(In addition a overhead is most likely introduced by creating more "hidden classes" in v8.)

Devtools "Memory Profile"/heap snapshot of Point constructor (in Chrome canary v33)

Situation 1: Before destroy

  3 points: shallow size = 156, retained size = 452
  1 single point : shallow size = 52, retained size = 200

Situation 2: After destroy 

  3 points: shallow size = 76, retained size = 1668
  1 single point : shallow size = 12, retained size = 808

For a single point there's a drop of  40 bytes in shallow size, but  retained size has increased 608 bytes (200 -> 808).

So destroy will increase memory consumption juding by the increased retained size.

I've tested on 50000 points in http://jsfiddle.net/hkskoglund/SWdL8/ and it generates a increasing stepwise chart (Timeline/Memory view) with a very noticeable increase during setData([]). Luckily GC will release all the memory, but maybe take longer timer than necessary if retained size was kept low as in situation 1. Screenshot of timeline; ![Timeline](https://drive.google.com/file/d/0B45ATdu5qGEbMmxaQno0cWFXTXc/edit?usp=sharing)

It seems like a bug.

**Comment by oysteinmoseng** [comment]
This is still relevant. We should be able to run a `hasOwnProperty` check with no issues here.

@TorsteinHonsi Thoughts?
