### ISSUE TITLE
Using axis type 'category' requires to have same values for all series

### ISSUE THREAD

**Issue by mstahv** [highcharts/highcharts#2522]
With the current 'category' axis type the behaviour is bit cumbersome for users. The documentation says that that categories are taken from the first series. Still names are also read from subsequent series, but points x value is still always the index of the point (or explicit value).

Code example to demonstrate issue

http://jsfiddle.net/2gFMw/

My suggestion is to preprocess data without x values in category mode and calculate actual x value based on "name" property. I prototyped the solution here:
https://github.com/mstahv/highcharts.com/commit/c4b7f5953ccf0e2e43fcdd29a3ecc67f29f90b98

You will probably want rewrite the patch in a manner that suits better into your architecture. Logic most likely belongs to Axis.

Allowing this might not be the best idea performance wise (error 15 gets throw with the fix), but for most cases I think it wouldn't matter.

Original Vaadin Charts issue that brought this up:
http://dev.vaadin.com/ticket/13050

**Comment by cxytomo** [comment]
It doesn't work for me. I don't want to use categories given to compatible with all types of charts

**Comment by betsyruns** [comment]
is there an updated exporting.js that works with this modified version of highcharts?

**Comment by scottnursten** [comment]
I'm still experiencing this using Highcharts 4.2.5. I'm adding different length series to an existing chart from AJAX and the later series overwrite from left instead of aligning on matching category names...

Did this get implemented into Highcharts? If so, is there anything I need to do to align values by 'name'? Any ideas?

**Comment by scottnursten** [comment]
@TorsteinHonsi - dudeman... as a paying customer, this is something that I really need working ASAP. Is there anything I can do to get this functionality into my Highcharts with you guys. I can see this hasn't been implemented in 4.2.5 and I was wondering where it is on the roadmap / how I can get this working...

Any help greatly appreciated!

**Comment by TorsteinHonsi** [comment]
I committed a fix for this now. It has been tested for regressions and I expect it to survive until the next maintenance release. Please run http://github.highcharts.com/highcharts.js to test.
