### ISSUE TITLE
Firefox (25.0 and 26.0) hangs 

### ISSUE THREAD

**Issue by pinturic** [highcharts/highcharts#2526]
It seams that this example is hanging firefox (versions 25.0 and 26.0) only on Mac while Windows and Linux versions seam not to be affected by this problem.

http://jsfiddle.net/LH4La/

try changing the height in the "color" sections to another value different from 1 (i.e. 22) and then back to 1:

```
  "color": {
        "fillId": "21587-red",
        "pattern": "https://bugreports.qt-project.org/secure/attachment/30178/topbottom1pixel.png",
        "width": 36,
        "height": 1,
        "offset": 0
}
```

**Comment by oysteinmoseng** [comment]
Closing as does not seem to be an issue with latest code and Firefox.
