### ISSUE TITLE
Legend displayed over tooltip with useHTML

### ISSUE THREAD

**Issue by DmitryLakhteen** [highcharts/highcharts#2528]
If it is used "useHTML: true", the legend is shown on top of the tooltip when it overlaps with the tooltip. Documentation says "The downsides are that it will always be laid out on top of all other SVG content, and that it is not rendered the same way in exported charts.". But if I set "useHTML: true" for tooltip (and tooltip also set on top) nothing changes.

Example: http://jsfiddle.net/Sqw9M/2/

**Comment by Vangi** [comment]
I also face the same problem and I can reproduce it very easy: http://jsfiddle.net/Vangi/2boq6xfg/ (just look at the tooltip for 'May', 'Jun' and 'Jul').

Is there a workaround or any idea when it will be fixed?

P.S. The link http://www.highcharts.com/docs/chart-concepts/label-and-string-formatting is broken.

**Comment by pawelfus** [comment]
Proper URL: http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting

**Comment by highslide-software** [comment]
One possibility is to use a full HTML tooltip, if you can live with the
missing chevron pointing to the data point.​

**Comment by tevfik6** [comment]
It seems like this is a quite old issue that I just had it as well. 

I was able to hack it using CSS (without losing the chevron pointer). I've updated the all the examples shared here.
http://jsfiddle.net/tevfik/wqxu4srr/
http://jsfiddle.net/tevfik/b9pfzeec/
http://jsfiddle.net/tevfik/u5rs541h/

For whom looking for a solution this problem, hope this will be helpful.
Tev.

**Comment by Ramyani** [comment]
Hi,
I am still facing the same issue when I am using floating legend with custom image.
http://jsfiddle.net/g2j344z4/

I have tried with the z-index by enabling useHTML for both legend and tooltip. But still the legend image is coming top of the tooltip.
http://jsfiddle.net/g2j344z4/2/

Is there any solution for this?

**Comment by tevfik6** [comment]
Hi @Ramyani 
z-index wouldn't work.
Try this: http://jsfiddle.net/g2j344z4/3/

Tev.

**Comment by VivianWeb** [comment]
Hi 
If I set useHTML: true, but I don't want to change tooltip background. 
http://jsfiddle.net/g2j344z4/3/   
Is there any solution to solve the problem without resetting background-color?

**Comment by pawelfus** [comment]
Hi @VivianWeb 

Please read the following: https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting

As described, since v6.1.1 you can use `tooltip.outside`. Otherwise, you need to redefine tooltips' background. 

Is there any particular reason why you don't want to reset the background color? It seems to be pretty easy: http://jsfiddle.net/BlackLabel/2uomszLq/ - thanks!

**Comment by VivianWeb** [comment]
Hi @pawelfus 

Thanks for your reply.
I have also tried to use tooltip.outside, but our project doesn't allow tooltip to display outside of the chart. (if it is aligned to the chart,it will be better). Is there any way to let the tooltip align to the chart other than the page?

And our company doesn't allow to reset the tootip's background color of few charts ,to keep all kinds of chart coincident.

**Comment by pawelfus** [comment]
> And our company doesn't allow to reset the tootip's background color of few charts ,to keep all kinds of chart coincident.

Could you elaborate? Styles can be set inline, just like an option, take a look: http://jsfiddle.net/BlackLabel/ybmhtdzq/

**Comment by VivianWeb** [comment]
> > And our company doesn't allow to reset the tootip's background color of few charts ,to keep all kinds of chart coincident.
> 
> Could you elaborate? Styles can be set inline, just like an option, take a look: http://jsfiddle.net/BlackLabel/ybmhtdzq/

Thanks for your help.
We finally decide to use tooltip.outside: true.
Your reply helps much.
