### ISSUE TITLE
On mobile device, Panning should not change axis scaling

### ISSUE THREAD

**Issue by leebing505** [highcharts/highcharts#2535]
On mobile devices, setting scaleType to 'x' or 'xy' make chart scale works not properly in conditions, here is the code:

http://jsfiddle.net/pQ5EC/16/

review steps:

1.Zoom in to a smaller view;
2.Panning any direction
3.X Axis scaling changed whenever you panned.

**Comment by dukewan** [comment]
I have the same problem. 

1. open 

  http://fengdengjie.zn2plus.com/price/index.php?label=BPULP4

  in your phone browser.

2. pan the chart to the left, when you pan to 6-29 9:00am, the chart will automatically scale up!!!

I think the problem must be the irregular time data, the data doesn't conatin 6-28.

What should I do?
