### ISSUE TITLE
Performance optimization for large plots (10k+ items): SVGElement.animate() loop with no animation options

### ISSUE THREAD

**Issue by dlopuch** [highcharts/highcharts#2541]
Been tracking down performance bottlenecks for large scatterplots (10k+ items), and found a good optimization point.  Don't have an exact solution, but I can point you right at the bottleneck.

The problem arises when you do an update (eg Axis.update()) against a large scatterplot.  With that many elements, you definitely should have all your animations off.  I've found that even with animations off, a significant amount of time is being spent in an animation subroutine, specifically calling `$(el).stop();` against every datapoint, which is technically unnecessary and rather expensive when you're jquery-selecting 10k+ elements.

The problematic stack is:
![screen shot 2013-12-17 at 5 28 02 pm](https://f.cloud.github.com/assets/1427329/1770158/ab5cbc84-6783-11e3-9f96-23c5dad85bbe.png)

Fiddle to reproduce this: http://jsfiddle.net/hWM74/

In the fiddle, the chart renders the first time in 10-15 sec, an alert lets you know the update is about to be called, then it takes another 5 seconds to do the update.  If you randomly pause your debugger during this update (let's call this "Monte Carlo Performance Instrumentation" ;), more often than not you'll end up at the top of the above `$(el).stop();` stack.

SVGElement.animate() (highcharts.src.js:2039) indicates this `$(el).stop();` call is being done to stop any in-progress animations (#607).  Makes sense, but there should be a way to avoid this call completely if you know you've never had any animation on, thus increasing interactivity performance for large scatterplots.

**Comment by oysteinmoseng** [comment]
Closing this, as we now have [boost](https://www.highcharts.com/docs/advanced-chart-features/boost-module) and also the original fiddle renders fairly fast with no further optimizations.
