### ISSUE TITLE
disable zoom on iPad

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2555]
If we disable zoomType and pinchType, but need to panning, then it doesn't work.

Example: http://jsfiddle.net/9dKy4/12/
iPad, iOS7

**Comment by gregjacobs** [comment]
+1. Same problem here. Seem to be unable to get a chart to pan while disabling pinch-to-zoom. Please fix.

**Comment by sebastiankruk** [comment]
+1 pinchType doesn't even seem to be implemented

**Comment by gizmocuz** [comment]
+1, is this being looked at?

**Comment by kabaehr** [comment]
Hello, this bug still seems to be an issue... would be great if you could fix it.

Or is there any other solution to achieve panning but disable (pinch) zooming?

**Comment by sebastianbochan** [comment]
**Internal note**
The probelm is still valid in iOS 12 and HC7.1.2

**Comment by AregShahbazian** [comment]
The problem is still there, after 6 years.
When `zoomType` and `pinchType` are set to `null`, all works well on desktop, but on touch-screen devices the panning (scrolling through the chart) doesn't work.
