### ISSUE TITLE
Moving right-hand slider of navigator causes zooming on chart with xAxis.max > series data

### ISSUE THREAD

**Issue by tomlogic** [highcharts/highcharts#2561]
Reproduce with [this fiddle](http://jsfiddle.net/j6GFq/4/).  After chart renders, grab the right-hand slider and move to the left, and then all the way back to the right.  Upon hitting the right limit, the graph zooms.

This behavior doesn't exist with the left-hand slider.  It is also not present if you swap the order of the series data (a possible workaround to the issue).

**Comment by pawelfus** [comment]
It works fine since 1.3.10.
