### ISSUE TITLE
Unable to get property '0' of undefined or null reference

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#2562]
Unable to get property '0' of undefined or null reference
on highstock.js line 169 (positionItem function) 
on highstock.js line 180 (d undefined) 

Happening only on IE (using v.11), works ok on chrome.
This happend on a routine on document ready when I removed all series of the chart.

Hope this helps.

**Comment by jon-a-nygaard** [comment]
@ghost Are you still getting this error? I have tried your fiddle with emulation of IE11 in Edge, but did not pick up any errors there. I would therefore like to know if this is still a problem before I investigate any further.
