### ISSUE TITLE
funnel - datalabels crop

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2564]
Datalabels are cutted, also when crop / overflow parameters are used.

http://jsfiddle.net/d4zGF/542/

**Comment by maloner** [comment]
Hi.  Any update on this bug?

**Comment by sebastianbochan** [comment]
Workaround: increase spacingRight parameter.

Example: http://jsfiddle.net/d4zGF/1287/

**Comment by josh-schlick** [comment]
The workaround stopped working in version 5.0.12.  Still works in version 5.0.11

**Comment by pawelfus** [comment]
Thank you for letting us know! 

Additional workaround for 5.0.12: http://jsfiddle.net/d4zGF/1513/

```javascript
(function(H) {
  H.wrap(H.seriesTypes.funnel.prototype, 'placeDataLabels', function(p) {
    H.each(this.points, function(point) {
      if (point.dataLabel) {
        point.dataLabel.sideOverflow = null;
      }
    });
    p.apply(this, Array.prototype.slice.call(arguments, 1));
  });
})(Highcharts);
```
