### ISSUE TITLE
Not displaying time labels with fixed x axis

### ISSUE THREAD

**Issue by cels** [highcharts/highcharts#2566]
Charts with only one single data point in a timeline do not display the timestamp in the tooltip, only the date.
This is ok in most cases as the point is centred and the exact time is displayed on the x-axis as a tick.

But when having an x-axis with a fixed range it is pretty cumbersome or impossible to determine the exact timestamp.

Sure this could be bypassed by using the `xDateFormat` field of `tooltip` but that would disable the default behaviour in all other cases:
>The format for the date in the tooltip header if the X axis is a datetime axis.
>The default is a best guess based on the smallest distance between points in the chart.

**Comment by pawelfus** [comment]
Sorry for a late reply!
Please, share example with the issue. I am not sure what do you mean by fixed xAxis. Do you mean min-max extremes are fixed? 

In your case, you should be using `tooltip.formatter` to determine when should be returned timestamp and when datetime.

**Comment by cels** [comment]
Hi,

I'm sorry, I totally forgot everything about that issue...

As far as I remember:
-you have a chart with fixed range on the x-axis and this axis has the type of date/time
-with **multiple** data points in the chart the tooltips display the date **and** time of each data point
-with only **one** data point in the chart the tooltip of this point display **only** the date and time was missing

But I have to admit that I haven't used highcharts for almost two years now so I absolutely do not know whether this issue is still there and/or reproducible, sorry.

I think this issue should be closed.

Happy new year! ;)
