### ISSUE TITLE
Enhancement: Add mousemove to chart.events

### ISSUE THREAD

**Issue by zevero** [highcharts/highcharts#2588]
Please add mousemove support for chart.events. Currently only 'click' (and others) are supported.

I have several charts aligned over each other and want to have a plotLine (i.e. crosshair) on all charts simultaneously:

```
    chart: {
       type: 'spline',
       zoomType: 'xy',    
       events: {
          click: function (e) {
            for(var i=0;i<Highcharts.charts.length;i++){
              Highcharts.charts[i].xAxis[0].removePlotLine();
              Highcharts.charts[i].xAxis[0].addPlotLine({
                color: 'red',
                dashStyle: 'dot',
                width: 2,
                value: e.xAxis[0].value
              });
            }
          }
        }
    }
```

I would prefere 'mouseover' over 'click' so that the user finds this feature more easily

**Comment by jfoshee** [comment]
This approach requires using `pointer.normalize()` which does not seem to be part of the public API... Is this safe to use going forward? If so, it would be nice for it to be added to the the docs and TypeDefinitions (which are already of very high quality). 
Thanks for the code samples, @TorsteinHonsi @zevero

**Comment by TorsteinHonsi** [comment]
Yes, `pointer.normalize` will be safe to use to get the `chartX` and `chartY` positions.
