### ISSUE TITLE
onMouseOver of hoverPoints not defined as a function

### ISSUE THREAD

**Issue by sh1989** [highcharts/highcharts#2594]
Updating a chart series with the call setData( data, false ) will cause the following exception to be raised should a user mouse over the chart, until the next chart.redraw() call is made:
Property 'onMouseOver' of object #<Object> is not a function

The following code is where the exception occurs: runPointActions:
if (point && point !== hoverPoint) {
    point.onMouseOver(e);
}

This does not take into consideration the fact that a destroyed object is not null - instead all of its properties are set to null.

Possibly related to, but certainly not fixed by #540.

Reproducible at: http://jsfiddle.net/GUJrx/

**Comment by luc-codingdutchmen** [comment]
Using the latest version of highcharts (4.1.1), I have the exact same problem. Also, the demo at http://jsfiddle.net/GUJrx/ does not appear to work. Can this issue be reopened?
