### ISSUE TITLE
Series.update - column animation

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2595]
Example: http://jsfiddle.net/elie_saliba/7WMgx/1/

When changing to other types than column, animations is applied. For column animation is missing.

**Comment by pawelfus** [comment]
Now only column series does animate.. ;)

**Comment by sebastianbochan** [comment]
+1

**Comment by TorsteinHonsi** [comment]
@sebastianbochan There are two different problems described here. What is your requirement for the +1?

**Comment by sebastianbochan** [comment]
I mean that the animation is not triggered, when we update to line / area.

**Comment by TorsteinHonsi** [comment]
It seems to fail since 1141548, but even before that the line and area animation was not smooth.

**Comment by pawelfus** [comment]
That's correct - first, issue was missing column animation. Later, only columns animate, not the other types. It would be great to have all animations regarding type of series.
