### ISSUE TITLE
Drilldown with more series

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2604]
Example: http://jsfiddle.net/6zYmJ/1/

When trying to drilldown one of columns, I would expect to see only that column in separate columns, but second series isn't removed. 

On the other hand - when clicked on a category name, I would expect to drilldown both columns into separate column.

**Comment by alissondiel** [comment]
i make a multi series with multi columns drilldrown see: https://jsfiddle.net/alissondiel/zbhbvkuy/
