### ISSUE TITLE
Highcharts causes chrome 32+ page crash

### ISSUE THREAD

**Issue by HERC82** [highcharts/highcharts#2608]
Since i've passed to chrome 32 ( from 31 ) occurs this strange page crash when i render datalabels.
![aaa](https://f.cloud.github.com/assets/6178657/1931329/6ae5e198-7ebd-11e3-84cc-4c5efe62d5a4.png)
Here's the jsfiddle
http://jsfiddle.net/L8Q8q/

**Comment by lujiajing1126** [comment]
Still could be reproduced on LeTV with Chrome 36 (TV/Table) version

**Comment by KacperMadej** [comment]
Unable to recreate on Chrome 68+
Closing as resolved, but if you can recreate the issue then please leave a comment with more info and the issue could be reopened.
