### ISSUE TITLE
maxHeight legend - wrong number of pages

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2617]
Examples:
- 3.0.7: http://jsfiddle.net/GF4s9/1/
- 3.0.9: http://jsfiddle.net/GF4s9/

Introduced most probably by: #2098

**Comment by pawelfus** [comment]
It still happens in 4.x versions, example: http://jsfiddle.net/ucg5aawj/1/

**Comment by TorsteinHonsi** [comment]
What environment are you in? On Chrome/Mac I see no navigation at all: 

![skjermbilde 2015-11-26 kl 13 10 36](https://cloud.githubusercontent.com/assets/227836/11422802/367df898-943f-11e5-8e1e-a8ac453e74ac.png)

**Comment by pawelfus** [comment]
It was on W7 - pagination was available. On the osx indeed, it looks the same way as you posted. Interesting.

Anyway, simple adding more points (4 to be exact), we can get issue on osx too: http://jsfiddle.net/ucg5aawj/3/

**Comment by TorsteinHonsi** [comment]
> Interesting, probably font rendering difference between os.

Yes, In Windows the reported text bounding box height is greater, which has some consequences.

**Comment by sebastianbochan** [comment]
+1, additional example: http://jsfiddle.net/crhjao2v/

**Comment by jaganathan** [comment]
+1

**Comment by brannislav** [comment]
+1

**Comment by brannislav** [comment]
+1

**Comment by TorsteinHonsi** [comment]
The [fix above](https://github.com/highcharts/highcharts/commit/0cc353ef74c23df166c471134653cc7c53668096) works on both cases, http://jsfiddle.net/ucg5aawj/1/ on Windows/Edge and http://jsfiddle.net/ucg5aawj/3/ on Mac/Chrome.

**Comment by viethien** [comment]
Did you fix this bug in version 7, I had same issue with version 6?

**Comment by viethien** [comment]
> +1, additional example: http://jsfiddle.net/crhjao2v/

Do you have solution for your case @sebastianbochan ?

**Comment by sebastianbochan** [comment]
Hi @viethien,
When I run my demo (http://jsfiddle.net/BlackLabel/j2u45wvs/) with v6.0 and v7.0 Im observing excatly the same functionality and layout.

Could you update my demo with your simplified code for the further debugging?

**Comment by VadimDyliko** [comment]
Hi, @TorsteinHonsi
We have the issue like #2098  last items are cut off some times. this has happened after switching the version to 7.2.0. This issue connecting with your fix #2617. Here it is the screenshot of this issue:
https://ibb.co/m9bzDNz

**Comment by pawelfus** [comment]
Hi @VadimDyliko 

Please provide live of the issue, thanks!

**Comment by VadimDyliko** [comment]
Hi @pawelfus, 
Thank you for your quick response. Here it is live demo of the issue:  http://jsfiddle.net/VadimDyliko/xf5monaz/6/
