### ISSUE TITLE
Reset zoom not back to default position

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2620]
Reproduction steps:
1. goto http://jsfiddle.net/2aH98/
2. Zoom chart by selection on chart
3. Chart is zoomed, its fine
4. zoom again
5. click on reset zoom
6. chart back to previous position on "default view".

**Comment by pawelfus** [comment]
"Reset zoom" button resets only zoom on `yAxis`. For xAxis, use navigator to change extremes. For example, when setting only `zoomType: "x"`, you will not get the reset zoom button: http://jsfiddle.net/2aH98/1/
