### ISSUE TITLE
Tooltip become misaligned when using useHTML & on touchscreens (swiping up and down)

### ISSUE THREAD

**Issue by ozymandias547** [highcharts/highcharts#2626]
This bug is hard to reproduce.  Go to http://jsfiddle.net/LLExL/2342/ on an iPad or iPhone.  Scroll down to the Highchart pie chart, and start tapping repeatedly bringing up the tooltip.  If you tap and flick the scrolling up and down enough, the tooltip label and background become misaligned.

![image 2](https://f.cloud.github.com/assets/2013007/1976677/be6a3b50-838d-11e3-9e7f-b8160ab7cbf2.png)

This only happens when you use the tooltip useHTML configuration.

**Comment by sebastianbochan** [comment]
It looks like since 4.x problem is fixed. If it will be reproducible in current version, please reopen the ticket.
