### ISSUE TITLE
Setting series lineWidth to 1 incurs significant performance hit

### ISSUE THREAD

**Issue by racoleman** [highcharts/highcharts#2627]
It seems that setting series lineWidth to 1 instead of the default of 2 causes rendering to take significantly longer, at least in Google Chrome (32).

Apologies for no jsfiddle; I couldn't find a way to load a suitably large data set without it choking.

Steps to Reproduce:
- Create a spline graph with a large data set (I had ~100 series with ~170 points each)
- Open the Chrome Developer tools settings, enable "Force accelerated compositing" and "Enable continuous page repainting"
- Load the graph and observe the paint time
- Change the series lineWidth to 1 and refresh
- Observe the paint time

In my test case, the paint time roughly doubled. While lineWidth 1 seems to have been slower going back at least as far as version 3.0.1, it became significantly worse somewhere between 3.0.5 and 3.0.6 (I was unable to test 3.0.5).

**Comment by jon-a-nygaard** [comment]
Closing this issue due to pending a reply, and it is considered inactive. Should anyone have any further information about this issue, please comment and/or reopen.
