### ISSUE TITLE
HighStock disregard rangeSelector and selected date range after redraw

### ISSUE THREAD

**Issue by featalion** [highcharts/highcharts#2644]
Goal is to place dynamic `plotBands` on `xAxis`.
jsfiddle: http://jsfiddle.net/QcLYW/2/

Issues:
- Re-enable button in `rangeSelector` which is `selected` (in configuration)
- If date range is in the past, `redraw()` will forward visible date range to newest data

This happens because of `chart.xAxis[0].update({...}, false)` is called. When I am using `addPlotBand()` and `removePlotBand()` it does not happen. But as I want to place number of new bands instead of old, using those functions is not handy.

Thanks in advance!

**Comment by pawelfus** [comment]
Works fine in 4.2.x versions: http://jsfiddle.net/QcLYW/4/
