### ISSUE TITLE
Reset zoom in a line chart don't work

### ISSUE THREAD

**Issue by supermerill** [highcharts/highcharts#2655]
Hello
I pick your demo line chart demo http://www.highcharts.com/demo/line-basic
and i enable zooming: http://jsfiddle.net/gGKGG/

then, i test the function, so i zoom, zoom, zoom (like a fool) and push the reset button.

I found two bugs:
- sometimes (often) the reset button reset the legend but not the lines. (see pic)
  ![hightchartzoombug](https://f.cloud.github.com/assets/6536403/2031268/71c38e0a-8900-11e3-9a7e-4083632bedb6.png)
- sometimes, our mouse is struck with the selection area even if we released the mouse button.

**Comment by jparmarmt** [comment]
I m using Highcharts JS v4.0.3. 
After save chart as image doing zooming on line chart, line gets disappears.

**Comment by highslide-software** [comment]
Not a problem [here](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/zoomtype-x/)...

Can you set up a live demo?
