### ISSUE TITLE
Tooltip positioning on IE10.

### ISSUE THREAD

**Issue by gim-m** [highcharts/highcharts#2657]
I just hit an issue I wanted to report.  I'm rendering a list of multiple chart (separate SVGs) in a long list.  On IE we were seeing empty floating boxes (users thought they were checkboxes).  They were in fact the highchart tooltips.

I've worked around the problem by patching the highcharts source to shift the tooltip -10000 pixels instead of the -999px.

Around line 8723 in version 1.3.9:

this.label = chart.renderer.label('', 0, 0, options.shape, null, null, options.useHTML, null, 'tooltip')
			.attr({
				padding: padding,
				fill: options.backgroundColor,
				'stroke-width': borderWidth,
				r: options.borderRadius,
				zIndex: 8
			})
			.css(style)
			.css({ padding: 0 }) // Remove it from VML, the padding is applied as an attribute instead (#1117)
			.add()
			.attr({ y: -10000 }); // #2301

![highchartstooltipbug](https://f.cloud.github.com/assets/3241971/2035803/5a2538fe-893f-11e3-86a0-f11851deea61.png)
![highchartstooltipbug-devtools](https://f.cloud.github.com/assets/3241971/2035819/79a998fa-893f-11e3-9c29-fda504f20127.png)

**Comment by mlazowik** [comment]
Why is this still open? Seems to have been resolved for a long time now: https://github.com/highcharts/highcharts/commit/30afab08ac5b61111725b58a86ff1ab3e02908d7

**Comment by pawelfus** [comment]
You are right, thank you for pointing this out!
