### ISSUE TITLE
Forcing display of certain data points for large data sets

### ISSUE THREAD

**Issue by nmk** [highcharts/highcharts#2658]
When displaying a data set with a large number of points Highcharts leaves out some of the points. This can be seen in the following demo:

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/data-grouping/

When you select the "All" view, the first point in the graph is the one for April 5th, despite there being data for April 1st as well.

![zoomed-out](https://f.cloud.github.com/assets/39269/2038786/76dd8b2c-8994-11e3-9ace-6ce7b8abc2ba.png)

![zoomed-in](https://f.cloud.github.com/assets/39269/2038791/818f9826-8994-11e3-91f3-df5d4559d39a.png)

Is there a way to force Highcharts to always display the first and last data points and apply the pruning algorithm to the rest?

**Comment by oysteinmoseng** [comment]
Seems to be working as expected with current code.
