### ISSUE TITLE
Polar chart points below the Y Axis minimum are at the wrong location

### ISSUE THREAD

**Issue by starquake** [highcharts/highcharts#2660]
As you can see the point is drawn on the wrong side of the center.

http://jsfiddle.net/jvisser/v6RJ7/

I'm uncertain on where it should be put. Maybe ignore the point altogether?

**Comment by oysteinmoseng** [comment]
This is still relevant. I would expect points outside of axis range not to be visible.

**Comment by TorsteinHonsi** [comment]
I think the only semi-sensible way to handle this would be to treat them as `null` points, similar to what we're doing with zero or subzero points on a logarithmic axis: http://jsfiddle.net/3nrsxkv7/
