### ISSUE TITLE
Tooltip xDateFormat not working with plain date objects

### ISSUE THREAD

**Issue by nrdmn01** [highcharts/highcharts#2664]
xDateFormat is not taken into account when adding a point e.g. as 
series.addPoint({x: new Date("2014-01-31"), y: 5});

However, it seems that it will work if we explicitly supply the date in milliseconds, for example by calling getTime().

http://jsfiddle.net/T8LDC/1/

**Comment by abudri** [comment]
@TorsteinHonsi Hi!  I was wondering, I'm trying to use Highcharts in a Rails app, but we need the datetime data on the y-axis.  Is yDateFormat possible too, giving we give the date in milliseconds? It's not working for our tooltip pointformat for some some reason.  We are using LazyHighCharts for rails

**Comment by sebastianbochan** [comment]
@abudri,
You can use datime and format labels by https://api.highcharts.com/highcharts/yAxis.dateTimeLabelFormats.

**Demo:**
- https://jsfiddle.net/BlackLabel/o2fmcgaq/
