### ISSUE TITLE
Uncaught illegal access from a delete in Tick.addLabel

### ISSUE THREAD

**Issue by guiann** [highcharts/highcharts#2698]
It's not a huge matter since it doesn't occur very often and most of the time it's not visible to the end user but I've got some 'Uncaught illegal access' at : 

highstock-1.3.9.src.js:4067
extend.htmlCss

It occurs each time while drawing the chart after a 'Axis.setExtreme' call.

**Comment by jon-a-nygaard** [comment]
Closing this issue due to we are not able to reproduce it, and it has been inactive for a long time. Should anyone have further information on this issue, please add a comment and/or reopen.
