### ISSUE TITLE
data label bubble outside

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#2705]
if I use inside:false on data labels on a bubble chart, the placement of the datalabels is erratic. See  http://jsfiddle.net/kzoon/HPp63/2/
- by default data labels are rendered on top, half through the bubble
- align and verticalAlign: i would expect verticalAlign:'bottom' to render the label below the bubble and align:'left' to the left of the bubble.
- larger fontsize (20) and y:-10 give strange data label position on the first bubble(value 87)

**Comment by oysteinmoseng** [comment]
This is still relevant, and current behavior seems a bit unintuitive.
