### ISSUE TITLE
Updating the Legend Title does not update the Legend width

### ISSUE THREAD

**Issue by dejongch** [highcharts/highcharts#2706]
If you change the title of the legend of a created chart the width of the legend does not resize to reflect this change. Both the redraw and reflow functions do no update the width. The only way to update the width is to use setSize

http://jsfiddle.net/cc9Xe/

**Comment by chubbard** [comment]
The second bit of code was very helpful.

**Comment by talmobi** [comment]
Perfect!

**Comment by TorsteinHonsi** [comment]
Note that Legend.update is now an official part of the API, so you don't need the snippet above.
