### ISSUE TITLE
Tooltip does not always calculate width correctly

### ISSUE THREAD

**Issue by fitango** [highcharts/highcharts#2715]
I have here two bugs, one which I can reproduce, and one which I cannot. The bugs are very similar in nature. Fixing the first bug could help solve the issue of the second, as they are similar.

Bug 1 with steps to reproduce:
Use latest highcharts 3.0.9
Add a chart with 314x177 in size.
Add to the chart and add a tooltip formatter which returns "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaa aa", and/or 'aaaaaaaaaaa aaaaaaaaaaaa aaaaaaaaaaa aaaaaaaaaaa aaaaa'
The result will be that the tooltip extends past the visible area in the window. In the case of one long word, it should be cropped; in the case of multiple long words, it should break. It is not really feasible to solve this from the user side, since the width of the tooltip is not settable and this is difficult code to write.

I am really reporting this because it is related to a second bug below.

Bug2:
Browser: Chrome
Browser Version: 32.0.1700.107
Platform: Windows

Highcharts Version: "3.0.6"

A tester reported this bug where the text extends past the tooltip. It does not reproduce on my Ubuntu linux system and I cannot reproduce it at all.

![unnamed](https://f.cloud.github.com/assets/6707721/2188297/9dcc4dea-9803-11e3-8c88-d4574af9240b.jpg)

**Comment by sebastianbochan** [comment]
Reopen if problem will appear.
