### ISSUE TITLE
Dateformat difference ie8 / chrome

### ISSUE THREAD

**Issue by motormuis** [highcharts/highcharts#2717]
Hi,

Using useUTC false and formatting some time in milliseconds shows a difference between ie8 and chrome: http://jsfiddle.net/mHS5b/1/embedded/result result in the console. On my local pc the diff is 8 hours. Any workaround appreciated.

highcharts 3.0.9

regards,
rico

**Comment by pawelfus** [comment]
Just tested:

Indeed I can see two different dates: 

- **IE8**: LOG: Saturday, Feb 15, 21:36:41, 2014
- **Chrome**: Sunday, Feb 16, 06:36:41, 2014

But I had wrong timezone set for my windows machine. After setting the same timezones in windows and osx, the result is exactly the same:


- **IE8**: LOG: Sunday, Feb 16, 06:36:41, 2014
- **Chrome**: Sunday, Feb 16, 06:36:41, 2014

I guess, you had the same issue.
