### ISSUE TITLE
Forcing display of first and last point when graph is zoomed in

### ISSUE THREAD

**Issue by JulienHenchoz** [highcharts/highcharts#2725]
When graph is zoomed, the first and last point do not match the dates in the date selector.

Example : http://jsfiddle.net/8PPwL/3/
To reproduce the problem, zoom from 6 Sept. 1999 to 10 Oct. 2000.
The first displayed point is 9 sept. 1999 and last point is 8 oct. 2000. This should not happen, since 06.09.1999 and 10.10.2000 have valid points.

Edit : I found out that the behaviour is different whether you edit the date in the date selector or if you move using the range selector. To reproduce the problem above you have to move to these dates using the range selector.

![first_last_point_of_graph_-_jsfiddle-2](https://f.cloud.github.com/assets/888157/2219493/4fc434ce-9a41-11e3-8085-f68f7f9ed1e7.png)

I see that similar issues have been discussed recently in #2658 and #2533 and partly resolved when viewing the whole graph (zoom = "All"), but the problem remains when zoomed in.

Is there a way to force the display of the first and last point when zoomed in ?

**Comment by pawelfus** [comment]
+1

@highslide-software - do you need an another demo? I can setup, I think.

**Comment by sebastianbochan** [comment]
+1

**Comment by jon-a-nygaard** [comment]
@pawelfus Are you still able to set up a demo for this one?

**Comment by pawelfus** [comment]
@jon-a-nygaard - it's sill possible to reproduce the issue using the second demo by @JulienHenchoz  : http://jsfiddle.net/8PPwL/5/

**Comment by jon-a-nygaard** [comment]
@pawelfus Thanks, but I have tried that without any luck.
The steps I used was:
1. Open the fiddle http://jsfiddle.net/8PPwL/5/
2. Click inside the From selector and type in 1999-11-17
3. Press Tab
4. Click inside the To selector and type in 2000-10-11
5. Press enter
The chart zoomes to the correct data set and it behaves as I would expect.

**Comment by pawelfus** [comment]
In my opinion it also behaves correctly, but: 

> If you range from Nov. 17 1999 to Oct. 11 2000 (these points actually exist in the original data), you'll see that the first point and last point are 22 Nov. and 9 Oct.

DataGrouping is set to week unit, so points reflect that. The point of the issue is that extremes from range selector inputs should apply not only to extremes, but also to points on a given range (graph should start and end with a point, not part of a line).

**Comment by jon-a-nygaard** [comment]
Thanks @pawelfus , quite sure that I get the issue now.

But how should this work if the datagrouping is set to 1 week, and the selected range is not an even number of weeks. It would in my opinion be impossible to make the chart both start and end on a point.

@TorsteinHonsi What do you think about this, is it something that seems achievable?
