### ISSUE TITLE
Errorbar - datalabels

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2770]
Datalabels seem to not be displayed on the errorbar chart.

http://jsfiddle.net/f8sB9/2/

**Comment by Andriy-Kulak** [comment]
@TorsteinHonsi how would I be able to show the dataLabel for the top of the errorBar? by default, it either shows the bottom dataLabel or both. I just need to show the top one. Thanks!

**Comment by TorsteinHonsi** [comment]
It's a bit ugly, but you can hide the lower labels by simply moving them outside the chart: http://jsfiddle.net/highcharts/f8sB9/7/

**Comment by pawelfus** [comment]
Alternatively, use `formatter`, and render only high label: http://jsfiddle.net/BlackLabel/445o3v32/ (note: it uses internal options: `this.point.plotY` and `this.point._plotY` which may change between versions)
