### ISSUE TITLE
tick label values very wrong on log axis on multi-axis chart

### ISSUE THREAD

**Issue by ctkemper** [highcharts/highcharts#2772]
Open this fiddle in IE11 : http://jsfiddle.net/Yx2eb/3
Note exception thrown by axis.defaultLabelFormatter()

This fiddle shows how problem is affected by min/maxPadding on yAxis: http://jsfiddle.net/LAW6R/

**Comment by pawelfus** [comment]
Fixed since 4.1.0: http://jsfiddle.net/Yx2eb/6/
