### ISSUE TITLE
Series Colors inverted on export when use "index"

### ISSUE THREAD

**Issue by nicoz85** [highcharts/highcharts#2777]
I have an issue when using index on series.
When i export as PDF, the series colors are inverted.

See example: http://jsfiddle.net/KQ6Uk/2/
Export it as PDF.

Version tested: v3.0.9

**Comment by KacperMadej** [comment]
[Working](http://jsfiddle.net/KQ6Uk/129/) since version 4.2.2 (http://jsfiddle.net/KQ6Uk/128/)
