### ISSUE TITLE
Functions missing from gauge Axis

### ISSUE THREAD

**Issue by hpihkala** [highcharts/highcharts#2779]
Hi,

Gauge chart axis objects do not seem to have many of the functions listed in the API docs, for example get/setExtremes(), addPlotBand(), etc.

Best regards,
Henri

**Comment by jon-a-nygaard** [comment]
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.
