### ISSUE TITLE
Rotated xAxis labels cropped

### ISSUE THREAD

**Issue by nicolaszohar** [highcharts/highcharts#2791]
When xAxis contains long rotated label, sometimes, if those labels are too long, they are cropped.

See example: http://jsfiddle.net/cQ6pC/

Is it possible to auto set left margin to avoid cropping (maybe like "crop" param in dataLabels) ?
Thanks

**Comment by KacperMadej** [comment]
Without forced margins preventing default logic from working and without forced rotation from labels options (chart has labels rotated like that by default) it works fine in version 6.1.4.

Closing as resolved.
If you have more info please add a comment and the issue could be reopened.
