### ISSUE TITLE
yAxis categories with tickmarkPlacement

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2792]
Connected to #1784

Compare:
- 3.0.7:  http://jsfiddle.net/mrLPn/
- 3.0.8+: http://jsfiddle.net/mrLPn/2/

Using tickmarkPlacement will translate column higher. 

Possible workaround: set strict `min:0.5` and `startOnTick: false`, example: http://jsfiddle.net/mrLPn/3/

**Comment by DavidLeeding** [comment]
Any chance the underlying problem for this issue could be reviewed for the next Highcharts update? It would be nice not to rely on workarounds, one of which doesn't work perfectly in 4.1.3. Thanks!

**Comment by highslide-software** [comment]
Technically the current behaviour is correct - consider this example: http://jsfiddle.net/highcharts/e8uuajf8/.

The first marker is 0, which is the first category, "Good". So the marker sits correctly in the middle of the category, regardless of the `tickmarkPlacement` setting. The plot area is extended up and down with 0.5 units to make room for the categories. 

Now if we make the series a column, we get the [unwanted behaviour](http://jsfiddle.net/highcharts/e8uuajf8/1/). The columns start at 0 as they should, and the plot area starts at -0.5 as it should, but it is not necessarily what we want. So we end up with a workaround: http://jsfiddle.net/highcharts/e8uuajf8/2/.

**Comment by DavidLeeding** [comment]
Thanks your your clear explanation!
