### ISSUE TITLE
Legend items cropped on top when paginate

### ISSUE THREAD

**Issue by nicoz85** [highcharts/highcharts#2793]
See example: http://jsfiddle.net/R8G3H/

Regression issue in v3.0.10

**Comment by pawelfus** [comment]
Last working version: http://jsfiddle.net/R8G3H/2/ (3.0.7)
Broken in (3.0.8): http://jsfiddle.net/R8G3H/3/

Responsible [commit](https://github.com/highslide-software/highcharts.com/commit/71acfa6).

**Comment by pawelfus** [comment]
@highslide-software : Any specific reasons to subtract 5 in [this](https://github.com/highslide-software/highcharts.com/blob/master/js/parts/Legend.js#L31) line? After removing that part, it works properly. Comment isn't really helping ;)

**Comment by sebastianbochan** [comment]
Fixed since HC v5.0.7.

Demo:
- http://jsfiddle.net/jt7fo7ee/
