### ISSUE TITLE
whiskerLength in pixels

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2801]
Well, it just doesn't work. It's always calculated as percent value:

```
whiskerLength = parseInt(series.options.whiskerLength, 10) / 100;
```

There should be match for pixels value (either by setting '10px', or just a number) and another for percent ( e.g. '10%' ).

Demo: http://jsfiddle.net/2MDGt/

**Comment by pawelfus** [comment]
Improved testes for the fix above in [this commit](https://github.com/highslide-software/highcharts.com/commit/a6cbc5c333e43ddbe93d6a6d6e74738b361ab7c70.

**Comment by KacperMadej** [comment]
Failed to auto close due to extra `:`
Tested and works fine. Closing as resolved
