### ISSUE TITLE
Polar chart - print elements

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2804]
It looks like a possibly bug, because a slices are overlap in the scenario when we have different axis.

http://jsfiddle.net/P2LS8/9/ current HC
http://jsfiddle.net/P2LS8/8/ HC 3.0.2

**Comment by pawelfus** [comment]
**Workaround:**

Set `chart.alignTicks` to false, demo: http://jsfiddle.net/P2LS8/11/

**Comment by KacperMadej** [comment]
Looks like resolved and working fine in version 6.1.4.
Closing as resolved.
