### ISSUE TITLE
[Bug] the gradient disappear in polarchart after F5 refresh

### ISSUE THREAD

**Issue by huangnoah** [highcharts/highcharts#2809]
1. link to http://demo.vaadin.com/charts/#Spiderweb, you may see the gradient in Spiderweb chart
2. then link to [#PolarChart] link, you should see the gradient
3. F5 refresh, the gradient disapper in PolarChart

please try more times (#PolarChart, #Spiderweb, or #WindRose)

**Comment by oysteinmoseng** [comment]
Closing this as does not seem relevant anymore. Feel free to reopen if still an issue.
