### ISSUE TITLE
Column width with different pointRange series

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2822]
Compare:

- http://jsfiddle.net/vA2H9/8/ (1.3.0)
- http://jsfiddle.net/vA2H9/9/ (1.3.10)

When zooming (by navigator) in 1.3.10 we will get the same result as in 1.3.0, but when navigator is set to show all points ('All' in rangeSelector), we will have wrong width. 

Problem is with last series which has only part of data. If setting manually null points, then it works fine: http://jsfiddle.net/vA2H9/10/

**Comment by sebastianbochan** [comment]
+1

**Comment by highslide-software** [comment]
Simplified: http://jsfiddle.net/highcharts/vA2H9/12/

**Comment by highslide-software** [comment]
It happens in the `setAxisTranslation` method where the larger pointRange is taken for the layout. I have tried for a while, but haven't found a good solution. 

One workaround would be to specify a `pointRange` option for both series.
