### ISSUE TITLE
Heatmap unexpected event

### ISSUE THREAD

**Issue by GreenRover** [highcharts/highcharts#2833]
Hi, i found the legendItemClick configuration on an unexpected and undocumented position:

http://jsfiddle.net/25MyN/21/

IT works great like it work now.
But i expected it with   plotOptions.heatmap.events

**Comment by pawelfus** [comment]
I think it's a bad idea: `colorAxis` can be shared between multiple series, it is a separate object, so doesn't belong to any series. Rather series are connected to that axis.
