### ISSUE TITLE
zoom drag doesn't release when chart in iframe

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2849]
http://jsfiddle.net/LLExL/2531/

click and drag to zoom, you cannot release the area to do the zoom.

**Comment by iweindesmedt** [comment]
I fixed this by overwriting ```setDOMEvents```:
```
Highcharts.Pointer.prototype.setDOMEvents = function () {
	var pointer = this,
		container = pointer.chart.container
		containerDocument = container.ownerDocument
	;

	container.onmousedown = function (e) {
		pointer.onContainerMouseDown(e);
	};
	container.onmousemove = function (e) {
		pointer.onContainerMouseMove(e);
	};
	container.onclick = function (e) {
		pointer.onContainerClick(e);
	};
	HighchartsAdapter.addEvent(container, 'mouseleave', pointer.onContainerMouseLeave);
	
	if (!containerDocument.HighchartsHasMouseUp) {
		HighchartsAdapter.addEvent(containerDocument, 'mouseup', pointer.onDocumentMouseUp);
	}
	if (containerDocument.ontouchstart !== UNDEFINED) {
		container.ontouchstart = function (e) {
			pointer.onContainerTouchStart(e);
		};
		container.ontouchmove = function (e) {
			pointer.onContainerTouchMove(e);
		};
		if (!containerDocument.HighchartsHasMouseUp) {
			HighchartsAdapter.addEvent(containerDocument, 'touchend', pointer.onDocumentTouchEnd);
		}
	}
	
	if(!containerDocument.HighchartsHasMouseUp){
		containerDocument.HighchartsHasMouseUp = true;
	}
	
};
```

So instead of checking the total chart count in the (parent) document, it check if the current document has the listeners. This works stable now, for both charts in the iframe, as those in the parent window.

Probably there are other parts of the code affected by the same issue.

**Comment by yplakosh** [comment]
Can fix for this issue be incorporated in the main code line? 

We would like to have it in original code and not to customize it each time we upgrade to the latest version of Highcharts.

**Comment by salehmosleh** [comment]
@iweindesmedt ,HighchartsAdapter does not exists !

**Comment by salehmosleh** [comment]
@TorsteinHonsi , i can not find below codes in `highcharts.js`. i use `highcharts.js` instead of `highcharts.src.js`.

>         // Display an error if the renderTo is wrong
>         if (!renderTo) {
>             error(13, true);
>         }

**Comment by pawelfus** [comment]
Namespace `HighchartsAdapter` doesn't exist, use simply `Highcharts`.
