### ISSUE TITLE
iOS tooltip jumps to previous point

### ISSUE THREAD

**Issue by iansullivan88** [highcharts/highcharts#2870]
If multiple points are selected in quick succession on the iPad, the tooltip jumps back to the previously selected point. This can be seen in the basic fiddle:

http://jsfiddle.net/highcharts/llexl/

This happens even if animation is disabled.

**Comment by marcinmatczuk** [comment]
Bump.
Is this still an issue? I observe exactly same behaviour when using Highcharts via iOS wrapper in mobile application - i.e. the tooltip jumps back to previously selected point.

I'm not opening an issue `highcharts-ios` as it seems to be purely related to JS.

**Comment by pawelfus** [comment]
Hi @marcinmatczuk 

The demo above is broken - could you recreate issue in jsfiddle? We will check this, thanks!

**Comment by sebastianbochan** [comment]
Closed due to inactivity.

**Comment by marcinmatczuk** [comment]
@pawelfus, @sebastianbochan, I'd like to have this issue re-opened, as I've reproduced it on iOS demo   app, HighFit, developed by Highcharts iOS team - see the corresponding bug report: [#168](https://github.com/highcharts/highcharts-ios/issues/168)

You can download all the changes to app and video demonstrating the issue from dropbox: https://www.dropbox.com/s/7m85y90ulss145f/highcharts-ios-issues-168.zip?dl=0

**Comment by pawelfus** [comment]
Thanks @marcinmatczuk for the heads up! Just tested JS version on Safari+iOS 12.2 and it works fine: https://jsfiddle.net/BlackLabel/3v5mbwn9/show (and v7.0.3: https://jsfiddle.net/BlackLabel/3v5mbwn9/1/show ). Tested also your changes on iOS 12.1, we are still unable to recreate this:

![ios121](https://user-images.githubusercontent.com/1453926/55478589-58c6b000-561c-11e9-81a5-3c546df698d7.gif)

(sorry for the quality of gif, here is full movie:  [ios121.mov.zip](https://github.com/highcharts/highcharts/files/3038584/ios121.mov.zip))

**Comment by marcinmatczuk** [comment]
Thanks for quick update, @pawelfus.

Is your test for "JS version on Safari+iOS 12.2" with Highcharts 7.1? 
I'll retest on my side once iOS framework is updated to 7.1 and post my findings here.
