### ISSUE TITLE
Columns lose their color if there's too many data points (regression)

### ISSUE THREAD

**Issue by drakej** [highcharts/highcharts#2892]
I noticed after upgrading from 3.0.9 to 3.0.10 that column charts with a large number of data points will lose their color. I'm not exactly sure what the threshold is and unfortunately I can't hunt down the actual cause but I did notice that the SVG rect tags that used to include the fill attribute lack it just by change the version.

I have two JSFiddle examples below. both use identical data and configuration options. The only difference is the first one runs 3.0.10 and all of the columns are colored black. The second one runs 3.0.9 and the expected color is applied.

http://jsfiddle.net/Cym44/2/

http://jsfiddle.net/Cym44/1/

**Comment by pitybea** [comment]
any one has the same issue with the latest version?

**Comment by sebastianbochan** [comment]
Hi @pitybea
When I run the demo: http://jsfiddle.net/46u4wpdn/ with the newest Highcharts, all is rendered properly. Could you update my demo with your code for the further debugging?

**Comment by pitybea** [comment]
Hi @sebastianbochan 
I made this example from demos
If the size of the array is 20, all points will be rendered red, and if the size of the array is 200, all points will do not have color.

http://jsfiddle.net/z0zysrn7/8/

**Comment by sebastianbochan** [comment]
By default, markers are draw when there is enough space. If not, then are hidden. You can overwrite this functionality by settion marker.enabled as true.

Demo:
- http://jsfiddle.net/8r288ad8/

Related issues:
- https://github.com/highcharts/highcharts/issues/3635
- https://github.com/highcharts/highcharts/issues/5099

**Comment by pitybea** [comment]
@sebastianbochan thank you so much! this perfectly solved my problem
