### ISSUE TITLE
point.update() error

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2894]
Example: http://jsfiddle.net/TXjb8/

Click any of buttons, and observe error in console.

Similar issue we have when try to export our demo: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/dynamic-update/ - just enable exporting.

The possible workaround is to set turboThreshold: 0, but with a lot of points exporting hangs out browser, so in the most cases won't work.

**Comment by sebastianbochan** [comment]
+1
