### ISSUE TITLE
Highchart falsely assumes that axis title is always farther than axis labels

### ISSUE THREAD

**Issue by michalrn** [highcharts/highcharts#2895]
When axis title is moved near axis (offset=0 or margin=-X), then axis labels do not affect margin calculation and are cropped.

http://jsfiddle.net/LLExL/2577/
The problem is, that axis labels (values) do not fit.
One can fix this by either disabling the yAxis title, or commenting out the offset.

**Comment by oysteinmoseng** [comment]
This seems to work as expected with current code.
