### ISSUE TITLE
Highstock problem with liveRedraw=true on touch devices(iOS ,Android)

### ISSUE THREAD

**Issue by vovinh** [highcharts/highcharts#2896]
Version : Highstock JS v1.3.10
I want to use liveRedraw feature of Highstock on a touch device(tested on Samsung GS3 and Iphone iOS7.1). Unfortunately, setting liveRedraw=true doesn't seem to function properly. The graph is not updated/redrawn while my finger is moving. 
Example : http://jsfiddle.net/vinhvo/f86d2/
In the example, chart is only redrawn when I lift my finger.

So, I had a look at Highstock source code (highstock.src.js) and came up with my fixes as follow:

``` JavaScript
 onContainerTouchMove: function (e) {  
           if (/*e.touches.length === 1 || */e.touches.length === 2) {  
                this.pinch(e);  
           }  
      }  
```

``` JavaScript
if (hasTouch) {  
                container.ontouchstart = function (e) {  
                     pointer.onContainerTouchStart(e);  
                     pointer.onContainerMouseDown(e);  
                };  
                container.ontouchmove = function (e) {  
                     pointer.onContainerTouchMove(e);  
                     pointer.onContainerMouseMove(e);  
                };  
                addEvent(doc, 'touchend', pointer.onDocumentTouchEnd);  
           }  

```

``` JavaScript
    if (chart.mouseIsDown === 'mousedown' || chart.mouseIsDown === 'touchstart') {
            this.drag(e);
        } 
```

**Comment by krazibitBD** [comment]
@TorsteinHonsi,  Any reason why the dragging/livedraw not available on touch?

**Comment by pawelfus** [comment]
I think this may be connected to the fact that old mobile devices had low-end hardware. It's hard to guess if a given device can run smoothly with liveRedraw. 

But it's only about default value for `scrollbar.liveRedraw`. You can enable it, please take a look: http://jsfiddle.net/kev2w4rx/2/show/ - you can use scrollbar and see how chart adapts to the new extremes.

I think the main issue for @vovinh is `scrollbar.enabled = false`. Well, `liveRedraw` can not work without scrollbar.

Maybe you mean `panning` not `scrollbar.liveRedraw`? If that's the case you can compare how smooth are extremes changing by scrollbar vs panning (two fingers).
