### ISSUE TITLE
Datalabels - null point

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2899]
In case when we have null point, datalabel is not printed. This situation doens't allow us to use formatter and return i.e customised datalabel for null points.

Example: http://jsfiddle.net/7nNqG/4/

**Comment by pawelfus** [comment]
+1

**Comment by saad749** [comment]
Any update on this? The most specific cases where this is much needed is the column charts and the bar charts, where the custom label can be displayed above the x-Axis(for column) / y-Axis(for bar).

There was this workaround with earlier versions, but it is failing now:
http://stackoverflow.com/questions/28830042/show-n-a-in-datalabels-when-value-is-null-highcharts

**Comment by pawelfus** [comment]
There is a simple workaround for this case, demo: http://jsfiddle.net/7nNqG/13/

In short, each point can provide information about label content, and for null points we can set 0 value. Then using `dataLabels.format: '{point.options.something}'` we can get those labels. Of course, it's not a perfect solution as `minPointWidth` can not be used in that case.

**Comment by saad749** [comment]
Thank you, it needs some more pre processing for nulls than this method: http://stackoverflow.com/questions/42327573/column-chart-show-datalabel-for-null-values-highcharts

but is much more flexible and no need to manually position the data labels.

**Comment by richellyitalo** [comment]
Thanks @pawelfus. Works to me!
