### ISSUE TITLE
pointPlacement - issue

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2902]
In case when we use series and one empty, pointPlacement doens work if we use navigator: 

http://jsfiddle.net/hLN2r/2/

**Comment by KacperMadej** [comment]
Looks like working fine now - pointPlacement is based on pointRange and that is (if not set) based on axis. The xAxis is oridnal, but range changes while dragging the navigator so ratio pixel to pointRange changes too.

Closing for now, can reopen if more info will be provided.
