### ISSUE TITLE
dataGrouping.approximation isn't checked properly

### ISSUE THREAD

**Issue by Sicaine** [highcharts/highcharts#2914]
Hey,

you can add wrong values in dataGrouping.approximation. If you add avg instead of average it will throw an error.

In Highstock.src.js:18452 is not checked if the index (and therefore the approximation type) exists:

approximationFn = typeof approximation === 'function' ? approximation : approximations[approximation],

Not sure how you handle input validation.

**Comment by pawelfus** [comment]
Demo: http://jsfiddle.net/6xdAX/4/

**Comment by KacperMadej** [comment]
@TorsteinHonsi  Should this type of error in configuration be treated as in case of trying to apply a series type that is not found, so Highcharts error in console with a link to a web site with more explanation? Alternatively we could silently use default series type approximation, but this might confuse users.

Similar problem is when trying to set marker symbol to a symbol that is not defined - [demo](http://jsfiddle.net/xeoxovh7/).

**Comment by TorsteinHonsi** [comment]
@KacperMadej. I agree both of them are bugs.Perhaps the simplest and best option is to gracefully fall back to the default approximation and symbol? Implementers will see that they don't get the result they want, and will not run the risk of throwing errors to end users. And the fallback in most cases will be acceptible.
