### ISSUE TITLE
Last label on X-Axis overlaps because of alignment

### ISSUE THREAD

**Issue by fitango** [highcharts/highcharts#2931]
As seen in this JS fiddle example, http://jsfiddle.net/j7tsx/3/, the last label overlaps with the second to last label. This is with the latest code from code.highcharts.com. In an older version of Highcharts, 3.0.9, the label moves off to the right and is cut off one letter: http://jsfiddle.net/xsF4W/2/. This behavior is preferable to us in appearance.

You will notice that a bug on the Y-Axis encourages us to upgrade to the latest version where it is fixed. A immediate fix followed by an ideal fix would be appreciated. Maybe there is a setting that will fix this behavior until it can be fixed in a later version?

**Comment by KacperMadej** [comment]
The demos are not working or no longer showing the problem.
Closing as an old issue that is unable to be recreated, but if you have a demo or more info about the case and would like to see this issue reopened please leave a comment.
