### ISSUE TITLE
Highstock title fontsize using theme not being applied

### ISSUE THREAD

**Issue by garybrain** [highcharts/highcharts#2944]
Hi, I noticed that the Highstock (v4 master) title font-size is not being applied when using a theme.

Following contains a theme, with highchart and highstock charts and the highstock title is not being applied it stays at the default 16px.

http://jsfiddle.net/B6EV7/1/

Browsers : 
Chrome 34,9,1847
IE 10
FF 28.0

G.

**Comment by ashclarke** [comment]
We use setOptions to set global defaults, and merge in individual options for specific chart changes. Even then it still doesn't work.
