### ISSUE TITLE
highcharts issue while zooming and resizing

### ISSUE THREAD

**Issue by roshanbhakta** [highcharts/highcharts#2949]
when i zoom the highchart and resize it back. the charts overrides the content which i had at back. so while resizing its not reading the with from the js file which you have created. can you please help me to solve this issue?

**Comment by jon-a-nygaard** [comment]
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.
