### ISSUE TITLE
Zooming by mouse in Firefox 5 is not always working

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#295]
Steps to reproduce:
1. Open http://jsfiddle.net/highcharts/Mscva/ with Firefox 5
2. Zoom by mouse. About 50% of the time, the drag operation is prohibited.

**Comment by tetraDB** [comment]
// issue #295, dragging not always working in Firefox
if (e.preventDefault) { e.preventDefault(); }

This is not a good solution (at least for IE11) as it will prevent other (non highcharts) element receiving mousdown related events such as blur when mousedown the chart area.

i.e. I have a custom dropdown above the chart. When open, I rely on a blur event to close the items. If I use the chart area, via mousedown, to trigger the blur, the event is stopped by this line and as a result the dropdown items remain visible.

**Comment by pawelfus** [comment]
See #4606 - let me know if my workaround works for you.
