### ISSUE TITLE
Gauge with setExtremes

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2956]
Demo: http://jsfiddle.net/Exmvm/1/

In console we can see error from Highcharts:

```
Error: Problem parsing d="M .... Z"
```

**Comment by KacperMadej** [comment]
Currently (version 6.1.0) there's no error, but animation still doesn't look good.

_Internal note:_ path is animated while the element could be rendered similar to a pie slice / solid gauge / arc.
