### ISSUE TITLE
Highstock - Last column changes size and displays fake data with dataGrouping enabled

### ISSUE THREAD

**Issue by gizioo** [highcharts/highcharts#2957]
Here is the fiddle:
http://jsfiddle.net/6E27G/
1. Try extending the selected range until the data groups into months.
2. Move the scrollbar around and watch the last column change size and value

**Comment by kamilkulig** [comment]
+1

**Comment by shameersn** [comment]
+1

**Comment by pratapgowda007** [comment]
+1 i am also facing the same issue

**Comment by pawelfus** [comment]
Related ticket: #5344 and PR: #8049

Working OP demo: http://jsfiddle.net/BlackLabel/6E27G/2/

Closing as duplicate of #5344
