### ISSUE TITLE
halo not transparent when explicit color

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2960]
http://jsfiddle.net/LLExL/2680/

i think it would be expected that the halo is transparent

**Comment by oysteinmoseng** [comment]
Seems to be working as expected now (http://jsfiddle.net/LLExL/12425), though I don't remember us adding support for this anywhere @TorsteinHonsi? Looks like `fill-opacity` is added to the halo, which seems to do the job well, even with named fills.
