### ISSUE TITLE
Tooltip with 'useHTML' and 'opacity' don't hide when mouse leave the chart

### ISSUE THREAD

**Issue by nicoz85** [highcharts/highcharts#2961]
Since v4.0.0 and still present in v4.0.1 -> Regression

When the mouse leave the chart area after displaying a tooltip, the tooltip become blank but don't disapear.

I identified that this bug appears when both attributes below are used:

```
tooltip : {
    useHTML: true,
    style : { opacity: 0.9 }
}
```
Example: http://jsfiddle.net/X6hfC/

**Comment by pawelfus** [comment]
Fixed since 4.1.0: http://jsfiddle.net/X6hfC/7/
