### ISSUE TITLE
3d pie chart - border

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2985]
The border is skipped, when we use 3d pie chart.

2d: http://jsfiddle.net/qRvn2/4/
3d: http://jsfiddle.net/qRvn2/

**Comment by ourarash** [comment]
this bug still exists:
http://jsfiddle.net/n7rb6458/

**Comment by pawelfus** [comment]
Hi @ourarash 

This option is now `edgeWidth` and `edgeColor`: http://jsfiddle.net/BlackLabel/qRvn2/22/

You can also set more borders in CSS: http://jsfiddle.net/BlackLabel/qRvn2/25/
