### ISSUE TITLE
Drilldown event on chart fires multiple Times on stacked column series

### ISSUE THREAD

**Issue by FLoibl** [highcharts/highcharts#2989]
Can someone explain to me the rationale behind calling the doDrilldown method on every point when clicking on the Axis labels? 
This causes the "drilldown" Event in the Chart to fire multiple times, 
which is kind of bad when drilling down asynchronously.

```
tickLabel
                    .addClass('highcharts-drilldown-axis-label')
                    .css(chart.options.drilldown.activeAxisLabelStyle)
                    .on('click', function () {
                        each(tickLabel.ddPoints, function (point) {
                            if (point.doDrilldown) {
                                point.doDrilldown(true);
                            }
                        });
                        chart.applyDrilldown();
                    });
```

**Comment by stefanodcIT** [comment]
The problem continue to be present with every version of drilldown that i could find.
No way to solve the multiple drilldown event fired when we have multiple series in a single drilldown category?

Thanks.

**Comment by pzgz** [comment]
Yes, getting this issue too, when there are more than one series, and trying to drilldown from label will fire the drilldown event twice, and then it will caused the `Uncaught TypeError: Cannot read property 'xAxis' of null` error.

**Comment by FLoibl** [comment]
IIRC i "fixed" it with sth similar to @mestremuten's Patch but this code was just for a prototype which never went into production.

**Comment by TorsteinHonsi** [comment]
It is supposed to fire the drilldown event for each point. See http://api.highcharts.com/highcharts/chart.events.drilldown. 

Would it help if we added a `drilldownall` event that fires after all the points have drilled down, analogous to [drillupall](http://api.highcharts.com/highcharts/chart.events.drillupall)?

**Comment by pzgz** [comment]
@TorsteinHonsi Sounds promising, looks like we can simply use `drilldownall` event if we don't care which series was clicked when drilldown from both chart point or category.

**Comment by pzgz** [comment]
For workaround, I used `points` and `point` of the drilldown event parameter, only execute the procedure only for two situations:

- `points` is `false`, means click on chart point
- `point` is equal to `points[0]`, means click on chart category, by this, the event procedure will only be executed once if click on category

Such as following:

```
if (!e.points || e.points[0] == e.point) {
    ......
}
```

**Comment by goralpl** [comment]
@pzgz @TorsteinHonsi 

Has there been an update to the drilldown.js to include a drilldownall event?

**Comment by gtoups** [comment]
> 
> 
> For workaround, I used `points` and `point` of the drilldown event parameter, only execute the procedure only for two situations:
> 
>     * `points` is `false`, means click on chart point
> 
>     * `point` is equal to `points[0]`, means click on chart category, by this, the event procedure will only be executed once if click on category
> 
> 
> Such as following:
> 
> ```
> if (!e.points || e.points[0] == e.point) {
>     ......
> }
> ```

Thanks for the workaround!

**Comment by sansmash** [comment]
> For workaround, I used `points` and `point` of the drilldown event parameter, only execute the procedure only for two situations:
> 
> * `points` is `false`, means click on chart point
> * `point` is equal to `points[0]`, means click on chart category, by this, the event procedure will only be executed once if click on category
> 
> Such as following:
> 
> ```
> if (!e.points || e.points[0] == e.point) {
>     ......
> }
> ```

Any suggestion on handling the same in drillup? Since point, points in drillup event?

**Comment by pawelfus** [comment]
Hi @sansmash 

We have [`chart.events.drillupall`](https://api.highcharts.com/highcharts/chart.events.drillupall) event. We don't have `drilldownall`

**Comment by sansmash** [comment]
> Hi @sansmash
> 
> We have [`chart.events.drillupall`](https://api.highcharts.com/highcharts/chart.events.drillupall) event. We don't have `drilldownall`

That worked! Thank you.

**Comment by mikeg2580** [comment]
Has there been any fixes for this?

The proposed solution below does not work for me since !e.points is false on both drilldown occurrences and e.point looks the same on both occurrences as well.

I am using a stacked column chart.

if (!e.points || e.points[0] == e.point) {
    ......
}

**Comment by hubertkozik** [comment]
@mikeg2580, can I ask you to provide a demo with a reproduction of the problem? I tried to reproduce it here: https://jsfiddle.net/BlackLabel/0yz5f6o2/ but with the provided workaround everything seems to work correctly.

**Comment by mikeg2580** [comment]
I tried to reproduce it in jsfiddle but I cant. I am using react. Not sure if that is where it may be occurring. I did notice that on your stack column you only have one column per stack. Here is what mines looks like.

<img width="1645" alt="image" src="https://github.com/user-attachments/assets/fac5bd55-1a79-45aa-a911-97b2b2bce113">

When I click any of the columns I get the event fired twice with the same point

**Comment by hubertkozik** [comment]
@mikeg2580 even with multiple stacks, like here: https://jsfiddle.net/BlackLabel/4wbysvu9/ the provided workaround works correctly. I feel, that your issue can be fixed with the proper configuration of the chart and we use GitHub as a tool for bugs/feature request tracking. Can you reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart?
