### ISSUE TITLE
solidgauge : circle donut increases if value exceeds max range

### ISSUE THREAD

**Issue by siddhant4u** [highcharts/highcharts#2997]
if in official example you change data value to say 250 you will see the effect

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/gauge-solid/

It behaves weird if you change value to 400 and comes back to right shape (semi circle) if value is 3800.

![image](https://cloud.githubusercontent.com/assets/6794324/2852657/92e450b2-d138-11e3-8b97-7b332f0243f6.png)

Edit: 
Fail case: http://jsfiddle.net/highcharts/EkE2K/

**Comment by derekm** [comment]
This issue has been closed, but commit 85e3f47 has not been merged to a release. Is this an oversight? I'm evaluating your product in a new commercial project, and I would like to be able to set overshoot on solidgauge chart types. Thanks!

**Comment by highslide-software** [comment]
You're right, it was left in the bugfix branch. Now it's merged into the master, so it will be part of the next maintenance.
