### ISSUE TITLE
Plotbands added via options have wrong zIndex when using alternateGridColor

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#300]
Plotbands and alternateGridColor seems to get mixed when they are added in the options object.
When added after the chart has been created the plotbands are in correct position.

Example:
http://jsfiddle.net/z3PKa/
Forum thread:
http://highslide.com/forum/viewtopic.php?f=9&t=11175

**Comment by oysteinmoseng** [comment]
Still relevant, but easily fixed by adding a zIndex property to the plot bands.

**Comment by KacperMadej** [comment]
By default plotBands are placed under the alternating grid and if you want to have the plotBands placed over the grid then use documented API options - [plotBands.zIndex](https://api.highcharts.com/highcharts/xAxis.plotBands.zIndex).

The doesn't seems to be a bug in here when using version 6.1.4 and if the case is unclear please leave a comment and we could improve documentation with requested info. Closing for now.
