### ISSUE TITLE
3d hidden surface removal is not correct

### ISSUE THREAD

**Issue by gmathijssen** [highcharts/highcharts#3019]
http://jsfiddle.net/93Ym8/
The black columns are in front of the blue ones all the time

**Comment by Infeligo** [comment]
Here is a similar problem:
http://jsfiddle.net/Infeligo/a8apvufk/

Note Series 1 second value column.

**Comment by Izothep** [comment]
This issue looks to be resolved through 6f84253

demo: http://jsfiddle.net/93Ym8/1/
