### ISSUE TITLE
Line disconnect for irregular datetime series

### ISSUE THREAD

**Issue by infacq** [highcharts/highcharts#3043]
I'm looking into the missing point example. However I could not get if irregular date time series present

**Comment by r-havelka** [comment]
@TorsteinHonsi Is it possible to use the `gapSize` option with highcharts 3D charts? I have been playing around a little bit with it but haven't found any documentation on it.

**Comment by pawelfus** [comment]
Hi @r-havelka 

It works the same way for Highstock + Highcharts 3D, take a look: http://jsfiddle.net/BlackLabel/VwkHu/118/

**Comment by r-havelka** [comment]
@pawelfus thank you for the example. After having literally the same code between your example and the jsfiddle I had been working with, I realized I had my imports wrong. 
I had: 
````
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
````

But what I needed was :
````
<script src="http://code.highcharts.com/stock/highstock.js"></script>
<script src="http://code.highcharts.com/stock/highcharts-3d.js"></script>
````

**Comment by dandv** [comment]
@TorsteinHonsi: random question about that winter snow sample, why does it claim it's "Winter 2014-2016" but all dates are from the 70's? :)
