### ISSUE TITLE
Highstock 2.0.1 Tooltips no longer align with columns

### ISSUE THREAD

**Issue by julieknoll** [highcharts/highcharts#3056]
On column charts, the tooltips are sometimes not aligned with their column after zooming.

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/column/

Zoom to 3 months and hover over the first column, the tooltip pointer is placed on the second column.

Zoom to 1 year and hover over the second-to-last column, then hover over the third-to-last column, the tooltip pointer is placed between the zoom columns. This seems to change after moving the mouse to the left and right.

Tested in firefox and safari.

**Comment by dorian07s** [comment]
Hi, 
I'm working with Highchart 4.1.8 and this bug still exists.
Exemple : http://jsfiddle.net/doRian07S/hgpfby2m/
Tested in Chrome 38.

**Comment by pawelfus** [comment]
I think you wanted to refer #2379 ticket, not this one. See example with workaround: http://jsfiddle.net/hgpfby2m/2/
