### ISSUE TITLE
Calling setSize() after series.update breaks plot area

### ISSUE THREAD

**Issue by nhitchins** [highcharts/highcharts#3064]
The original issue referred to in #3057 still occurs after a call to series.update.
http://jsfiddle.net/ggUgw/2/

easy to reproduce: zoom in via selection or the navigator chart (which needs to call series.update in my use case), then resize the chart.

**Comment by KacperMadej** [comment]
Works fine now (version 6.1.0).
Please provide more info and the issue could be reopened.
