### ISSUE TITLE
Align for rotated dataLabels

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3070]
Example: http://jsfiddle.net/V88xT/

`align` and `verticalAlign` aren't used, when we have set `rotation`.

**Comment by Dams591** [comment]
Hey There,
I'm trying to do the same have rotated label that start at the beginning. Any idea on how to do that ?
Thanks.

**Comment by TorsteinHonsi** [comment]
Hi, this wasn't possible until now, but I implemented a fix for it. See http://jsfiddle.net/highcharts/V88xT/3/. 

The fix will be part of the next maintenance release within a few weeks.

**Comment by Dams591** [comment]
Amazing thank you !!!

**Comment by 888ba8** [comment]
Hi, @TorsteinHonsi there seems to be a similar problem with the Gantt highcharts? https://www.highcharts.com/forum/viewtopic.php?f=19&t=45637

**Comment by pawelfus** [comment]
You are right @888ba8 - it seems `align` does not work with the `rotation` option. Created separate ticket for that: #14862 - thank you for pointing this out!
