### ISSUE TITLE
Internet explorer has stopped working When I print preview my web page that has highchart 

### ISSUE THREAD

**Issue by mguney78** [highcharts/highcharts#3078]
Hi,
When I print preview a web page that I used highchart component, I encountered an error that is "Internet explorer   has stopped working...". This problem is only happening when print preview. At the moment I am using IE 11. IE 9 version is working properly. I don't know how it works in IE 11 ver.
I am waiting for your help as soon as possible

Best Regards,
Mustafa

**Comment by KacperMadej** [comment]
Unable to recreate without a live demo.
Please add a live demo if you can recreate the problem and the issue could be reopened.
