### ISSUE TITLE
Out of memory issue with secondary Y axis with many points, all with same Y value

### ISSUE THREAD

**Issue by axeluhl** [highcharts/highcharts#3079]
It seems I ran into an issue with a secondary Y axis that has approximately 100 points, all of which have the same Y value. I'm using the Moxie GWT wrapper. The code that configures the Y axis looks like this:

        chart.getYAxis(1).setOpposite(true).setAxisTitleText("Speed (kts)")
            .setStartOnTick(false).setGridLineWidth(0).setMinorGridLineWidth(0);

As soon as I change one point to use a different Y value, everything works as expected. Also, if I set the extremes, or only the min Y value, things are fine.

Can anyone reproduce this? It seems a grave bug to me. It exists in 4.0.1 and all the way down to 2.x versions.

**Comment by jon-a-nygaard** [comment]
Closing this issue due to we are not able to reproduce it, and it has been inactive for a long time. Should anyone have further information on this issue, please add a comment and/or reopen.
