### ISSUE TITLE
Horizontal Axis.title.x / y property

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3081]
We are able to set x/y for titles, as long as axis is vertical, otherwise it's omitted. Example: http://jsfiddle.net/9Nb7k/5/

In `getTitlePosition` we have code, responsible for such behavior: 

```
    return {
        x: horiz ?
            alongAxis : //horizontal doesn't use axisTitleOptions.x
            offAxis + (opposite ? this.width : 0) + offset +
                (axisTitleOptions.x || 0), // x
        y: horiz ?
            offAxis - (opposite ? this.height : 0) + offset :  //horizontal doesn't use axisTitleOptions.x
            alongAxis + (axisTitleOptions.y || 0) // y
    };
```

Simple workaround is to add this: http://jsfiddle.net/9Nb7k/4/

I know it's not documented feature, but it would be nice to have it working properly for both axes, and documented in API.

**Comment by KacperMadej** [comment]
Working fine in version 6.1.4
Closing as resolved
