### ISSUE TITLE
Exporting with global fonts

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3087]
Example: http://jsfiddle.net/7f94w/10/

Workaround is the same as here #1562 - update options in load event: http://jsfiddle.net/7f94w/12/

**Comment by jaysunwalter123** [comment]
Two years later and I appear to be having this issue with Tahoma. It renders the font fine while editing but saves out all fonts as some other serif font.

Is there a solution to this? Right now I'm having to take screenshots to get the correct font rendering. Thanks.

**Comment by TorsteinHonsi** [comment]
@gvaartjes @larsac07

**Comment by gvaartjes** [comment]
Sorry for the late reply @jaysunwalter123 . Confirming wrong font on outputting the chart. See https://jsfiddle.net/bf4jxw4t/
@larsac07

**Comment by jaysunwalter123** [comment]
@gvaartjes I've noticed the same happens with a couple of the fonts. I think Lucida was also not being output. Thanks.

**Comment by skorunka** [comment]
+1

**Comment by larsac07** [comment]
Should be fixed now. The 'Tahoma' fontFamily was missing, and was added.

@jaysunwalter123 'Lucida Grande' is there, but I don't think 'Lucida' exists as a global fontFamily value. At least, it doesn't exist on OS X or Windows.

**Comment by mhand7** [comment]
Can we have "Open Sans" font to the exporting server too ?

**Comment by TorsteinHonsi** [comment]
@larsac07

**Comment by planetofwebdesign** [comment]
How to apply font family when exporting offline ?

**Comment by KacperMadej** [comment]
Please contact support with more info using any other support channel. We keep github for bugs.
https://www.highcharts.com/support
