### ISSUE TITLE
setSize breaks multiple axis

### ISSUE THREAD

**Issue by jdries** [highcharts/highcharts#3092]
JSFiddle: http://jsfiddle.net/Rhu7V/
I create a chart, then resize it, then add another axis together with a series. The layout is now broken. Comment out the setSize call to see the desired result.

This issue occurs with highstock 2.0.1 (currently the latest version), but was also there in earlier versions. I use the latest version of chrome, but not sure if it is browser dependent.

Bad layout:
![image](https://cloud.githubusercontent.com/assets/5937096/3067211/65e1d7ca-e280-11e3-982f-594d1053634b.png)

Good layout:
![image](https://cloud.githubusercontent.com/assets/5937096/3067228/93a51208-e280-11e3-9a05-fb1d93190c3d.png)

**Comment by pawelfus** [comment]
Fixed since 5.x: http://jsfiddle.net/BlackLabel/Rhu7V/8/
