### ISSUE TITLE
Some elements are not garbage collected after chart.destroy() 

### ISSUE THREAD

**Issue by kfnzero** [highcharts/highcharts#3105]
Hi guys,

I'm checking the timeline with simple highchart pie sample and it's seems like elements keep growing after chart.destroy().
This is my test code http://jsfiddle.net/9PRyG/3/ 
When I repeat to create and destroy, u can see the memory usage keep growing.
![1](https://cloud.githubusercontent.com/assets/7721865/3102159/bf7b705a-e642-11e3-9aa1-83c82d0619e6.png)
Another picture, u can notice that there still have something remains after chart.destroy().
![2](https://cloud.githubusercontent.com/assets/7721865/3102160/c1b7b220-e642-11e3-9f95-10d6a8d909af.png)

My test steps is simple.
1. click create button.
2. click destroy button.
repeat step 1 and 2.

Thank you.

**Comment by arjunasuresh3** [comment]
+1

**Comment by pawelfus** [comment]
Maybe in 2016 that was an issue, but either it was fixed or in the original tests GC didn't do the job. Now it works fine, automated demo: http://jsfiddle.net/9PRyG/6/

Screenshot:
![screen shot 2018-03-30 at 15 44 33](https://user-images.githubusercontent.com/1453926/38139866-8ba51a06-3431-11e8-92ed-5bc7bdbc008b.png)
