### ISSUE TITLE
Highstock - data series get clipped off when container div expands

### ISSUE THREAD

**Issue by DavidBanksNZ** [highcharts/highcharts#3111]
I am trying to build a highstock chart with multiple panels to display weather data, but am having some problems when the container div expands (I am trying to make a responsive website).

Here is a jsfiddle. http://jsfiddle.net/kUdsz/5/
When the chart is drawn, resize the width of the result panel and see what happens to the column series - it gets clipped off.

In this other fiddle http://jsfiddle.net/kUdsz/4/, the chart is resized using setSize() method straight after being rendered. In that case, both column and line series are clipped off.

**Comment by pawelfus** [comment]
The second issue still exists. Version 4.2.6.
