### ISSUE TITLE
Compare for candlestick

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3112]
Example: http://jsfiddle.net/53QeS/

Click the button to set comparisson, series disappears.

**Comment by sebastianbochan** [comment]
+1

**Comment by highslide-software** [comment]
In compare mode for lines and columns, all values are compared against the first (earliest) value in the series. How should we do this with OHLC and candlestick? Compare against the _close_ value of the first point, or something else?

**Comment by soargon** [comment]
+1

**Comment by mldahl** [comment]
Close probably makes the most sense.  You could look at amCharts implementation.

https://www.amcharts.com/demos/stock-comparing-external-data/
