### ISSUE TITLE
Drilldown after seres.setData

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3114]
Demo: http://jsfiddle.net/2JVyZ/

Steps to reproduce:
- hover one of slices
- wait for setting new data
- click on a slice - nothing happen

Expected: drilldown on that slice. Click event is recognized even when we have already hovered element (test case: http://jsfiddle.net/QUa63/2/ ).

**Comment by baha2jo** [comment]
Hi ,,

I have the same issue and i used the event you wrote but nothing changed ,, can you please help me ?!

**Comment by KacperMadej** [comment]
Works fine now (version 6.1.0).
Please provide more info and the issue could be reopened.
