### ISSUE TITLE
Flag on first point

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3119]
Example: http://jsfiddle.net/ELqyd/

First flag isn't rendered, second one works fine.

**Comment by sebastianbochan** [comment]
+1

**Comment by halfstrik** [comment]
+1

**Comment by sebastianbochan** [comment]
Seems that problem still exists when we have to flag series.

Example: http://jsfiddle.net/t3j2anLk/5/ 
When single flag serie: http://jsfiddle.net/t3j2anLk/6/

**Comment by bharathd** [comment]
After using  minPadding: 0.01 and last point is not displaying

**Comment by bharathd** [comment]
after using minPadding: 0.01, it is displaying first point but when we scroll the navigator then it is not visible

**Comment by pawelfus** [comment]
Works fine with 5.0.0+ : http://jsfiddle.net/t3j2anLk/8/
