### ISSUE TITLE
negativeColor disappears when adding Point to a series

### ISSUE THREAD

**Issue by axe100** [highcharts/highcharts#3127]
I have a problem when I add points animated to a series that are under the threshold. Also I change the threshold of the series with every new added point.
The weird thing is that the negativeColor disappears for a short moment if I do so.
Please  look at this fiddle : http://jsfiddle.net/vdZk3/1/

I have two questions:
1.  How can I solve problem with the disappearing negativeColor. Is this a bug?
2.  Can I animate the threshold changed in the series.update(…) method?

**Comment by KacperMadej** [comment]
1 - unable to recreate using v7.0.2, so I will close the issue as resolved
2 - this features is not supported and the right place for enhancement suggestions is UserVoice where the most popular ideas are getting implemented, https://highcharts.uservoice.com/forums/55896-general
