### ISSUE TITLE
Bar chart & DataLabels. Buggy vertical alignment under height constraint

### ISSUE THREAD

**Issue by WydD** [highcharts/highcharts#3129]
When applying a height constraint that is too high, the first data label is poorly aligned.
http://jsfiddle.net/A52eu/

Things I've tried:
- Setting y therefore has a weird behaviour (opposite direction)
- Setting pointPadding and groupPadding (which I have in the product I'm developing) does not change anything

My suggestion is that this bug appears whenever the bbox of the datalabel is higher than the standard bar height.

Thanks

**Comment by kzoon** [comment]
I just got a complaint from a customer which touches this problem. 
See http://jsfiddle.net/2nh9udoz/2/
I can't use the datalabels.overflow work around, because that will push data labels out of view on the right hand side: http://jsfiddle.net/2nh9udoz/1/

A solution would be more than welcome...

**Comment by highslide-software** [comment]
@kzoon In your case the problem isn't with the invisible label padding, it is obvious that there is no room for the text. You could fix it by adding some chart margin: http://jsfiddle.net/highcharts/2nh9udoz/3/

**Comment by kzoon** [comment]
Torstein,
My fiddle is a simplified version of the real-life problem. I can't use fixed value for marginRight because:
- I allow my end user to enable/disable the legend. When he enables the legend, marginRight pushes the legend on to the plot area. See http://jsfiddle.net/2nh9udoz/4/
- The length of the data label can vary with different data. There is no safe value for marginRight, that will fit all circumstances.

I think the problem in http://jsfiddle.net/2nh9udoz/2/ is the 2 pixels that are unaccounted for that you mentioned in your earlier post.

**Comment by highslide-software** [comment]
According to the screenshot below, it is more than two pixels, it is all of the label to the right of the 100 grid line. In my opinion, the current Highcharts default is the best choice here - it moves the whole label on top of the bar.

Where would you expect us to put the label in this case? 

![skjermbilde 2015-11-13 kl 14 25 17](https://cloud.githubusercontent.com/assets/227836/11146890/6aad1e64-8a12-11e5-8b95-ef4210f761e9.png)

**Comment by kzoon** [comment]
You misunderstood me: 

I WANT to use justify an I'm perfectly happy with Highcharts behaviour at the right hand side.

My problem is the placement of the January and December labels: http://jsfiddle.net/2nh9udoz/2/
These are a few (2?) pixels off.

**Comment by highslide-software** [comment]
> You misunderstood me

Yes, a precise description, perhaps with a sketch, would help.

In the screenshot below, see how it looks for me in Chrome. Firefox, Safari and IE10 also look the same to me. I can't see anything wrong with the January or December labels. Please show me how you see it and what's wrong. Thank you for your patience. 
![skjermbilde 2015-11-16 kl 14 33 56](https://cloud.githubusercontent.com/assets/227836/11182958/21f007ea-8c6f-11e5-8a80-425cb95e2e28.png)

**Comment by kzoon** [comment]
This is a screenshot from Chrome (Version 46.0.2490.86 m)
![capture](https://cloud.githubusercontent.com/assets/1461707/11183516/6ff7b9e4-8c72-11e5-898c-0028fca41068.PNG)
As you can see the 54.4 for december is too high and January 29.9 is just a tiny bit too low (when compared to Aprils 29.2)

I will try to whip up a fiddle where the problem is more pronounced

**Comment by kzoon** [comment]
I think it boils down to a render issue for the Lucida Grande font on Windows machines. They doen't have Lucida Grande, so the font falls back to Lucida Sans Unicode ( font family: "Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif;). I have had may render issues with Lucida Sans Unicode, and it looks like this is just another one. 

If I change font to Arial, my problem disappears: 
http://jsfiddle.net/kzoon/2nh9udoz/6/

![capture](https://cloud.githubusercontent.com/assets/1461707/11184094/f5a37ca6-8c75-11e5-9ac4-bcf3acbae387.PNG)

**Comment by highslide-software** [comment]
Okay, I can reproduce in in Chrome on Windows.

**Comment by highslide-software** [comment]
Thanks for the pointer. Apparently the text bounding box is greater for Lucida Sans Unicode than for Lucida Grande. When I change [this line](https://github.com/highslide-software/highcharts.com/blob/v4.1.9/js/parts/SvgRenderer.js#L793) to the following, it works. I'll check this further, we should find a more generic solution to the problem. 

`if (styles && styles.fontSize === '11px' && height.toPrecision(2) === '17') {`
