### ISSUE TITLE
3d chart + zooming issue

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3131]
When we scroll, selection event is triggered. Additionally, zoom seems to be incorrect, becasue column is out of area.

http://jsfiddle.net/5cxEu/1/

**Comment by pawelfus** [comment]
Another example when using `setExtremes()` in the chart: http://jsfiddle.net/aoook7ha/

**Comment by sebastianbochan** [comment]
Related example is cutting inverted bars, http://jsfiddle.net/Akixi/jzkrxovc/

**Comment by sebastianbochan** [comment]
Fixed since v4.1
