### ISSUE TITLE
Request: Set stroke color to fill color when stroke-width is 0

### ISSUE THREAD

**Issue by romeromark** [highcharts/highcharts#3134]
This issue is tangentially related to issue 2892. In a column chart, if the columns' widths become really small the stroke overtakes the entire column leaving no fill. This occurs even when borderWidth is set to 0. My understanding is that HighCharts has to set a stroke-width of 0.01 if a width of 0 is specified to overcome rendering bugs.

I would suggest that in the case that the user specifies a borderWidth of 0, and does not explicitly specify a borderColor the borderColor should be automatically set to the series color. This would achieve the behavior that the user desires when a column becomes really small. I know that the user could do this by specifying a borderColor and series color but if the user wanted to use dynamic colors this would not be possible.

I have come up with a quick (albeit probably not ideal) patch for HighStock 2.0.1. The two lines of code were added in the init function of the ColumnSeries class.

```
--- highstock.src.orig.js   2014-04-24 03:26:17.000000000 -0500
+++ highstock.src.js    2014-06-04 16:11:48.000000000 -0500
@@ -15252,20 +15252,23 @@
        // point is substracted from previous (#1910)

    /**
     * Initialize the series
     */
    init: function () {
        Series.prototype.init.apply(this, arguments);

        var series = this,
            chart = series.chart;
+        
+        if (series.options.borderWidth == 0)
+            series.options.borderColor = pick(series.userOptions.borderColor, series.color);

        // if the series is added dynamically, force redraw of other
        // series affected by a new column
        if (chart.hasRendered) {
            each(chart.series, function (otherSeries) {
                if (otherSeries.type === series.type) {
                    otherSeries.isDirty = true;
                }
            });
        }
```

Here are some screenshots of the issue:

Before Patch:
Zoomed in with larger columns
![before-patch-zoom](https://cloud.githubusercontent.com/assets/7805865/3188389/2289db5a-ecba-11e3-89c3-7a74176e0913.png)

Zoomed Out
![before-patch](https://cloud.githubusercontent.com/assets/7805865/3188394/276d1588-ecba-11e3-945e-984b8a427631.png)

After Patch:
Zoomed Out
![after-patch](https://cloud.githubusercontent.com/assets/7805865/3188398/2e2bf27c-ecba-11e3-9ed3-0fa711556267.png)

**Comment by KacperMadej** [comment]
By default border with is reduced to zero if columns are small, so it works fine now (v6.1.1).
http://jsfiddle.net/BlackLabel/u8wxznb9/

Closing as this seems to be resolved, but if you have more info and would like for this case to be reopened then please let us know.
