### ISSUE TITLE
Tooltip is displayed outside the plot area

### ISSUE THREAD

**Issue by magnushavgry** [highcharts/highcharts#3138]
Since Highcharts v4.0.0 the tooltip can be displayed outside the plot area (depending on the distance between the point and the plot border) thus potentially overlapping the yAxis labels, the chart title, the export button etc.

v3.0.10: http://jsfiddle.net/Dnnm3/
v4.0.0: http://jsfiddle.net/Dnnm3/1/

It could be a deliberate change (I can't find a changelog on v4) but I don't believe it's an improvement. The "bug" is present in the latest version from the GitHub repo as well.

**Comment by SajagTiwari** [comment]
i got solution for the same problem at below site
http://ahumbleopinion.com/customizing-highcharts-tooltip-positioning/
