### ISSUE TITLE
Overlapping columns

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3157]
Example: http://jsfiddle.net/6xdAX/1/

Columns for February are overlapping March. Expected result is to see columns next to each other.

**Comment by pawelfus** [comment]
4.1.7: Now columns don't overlap, however distance between groups is different: http://jsfiddle.net/6xdAX/2/

I'm not sure how this should be handled at all: months have different number of days, so width of the column should vary? 

Anyway, with ordinal axis, it works fine: http://jsfiddle.net/6xdAX/3/

**Comment by KacperMadej** [comment]
Distance between groups is different due to data used.
For columns with different widths see [variwide](https://www.highcharts.com/docs/chart-and-series-types/variwide-chart).

Please provide more info and the issue could be reopened.
