### ISSUE TITLE
Line width too thin along lower bound

### ISSUE THREAD

**Issue by TrevorBurnham** [highcharts/highcharts#3160]
Example: http://jsfiddle.net/TrevorBurnham/zYtRS/1/

![screen shot 2014-06-12 at 4 54 57 pm](https://cloud.githubusercontent.com/assets/224895/3263553/7fa0a0e4-f273-11e3-8a9f-8f0cb0625c27.png)

Notice that the lines connecting the first few points (where the value equals the `min` of the y-axis) are thinner than the lines in the rest of the chart. Reproduced in both Highcharts 3.0.9 and Highcharts 4.0.1.

**Comment by mattmaci** [comment]
-5 doesn't always work for me either. I agree with Trevor - this is a real issue and should be re-opened.

**Comment by TorsteinHonsi** [comment]
Perhaps we should adjust the clip area when we set the axis.offset option, so that in this case you could set `offset: 1` to move the clipping out of the way.

Anyway, a more general workaround is to set the clip box's height higher by overriding `setChartSize`: 
```js
Highcharts.wrap(Highcharts.Chart.prototype, 'setChartSize', function (proceed) {
	proceed.apply(this, [].slice.call(arguments, 1));
	this.clipBox.height += 1;
});
```
[View it live](http://jsfiddle.net/highcharts/zYtRS/4/).

**Comment by micapam** [comment]
^ This worked for me @TorsteinHonsi, thanks! As I was working with percentages and had slightly thicker lines on my charts I needed to offset both top and bottom, like so: 

```
Highcharts.wrap(Highcharts.Chart.prototype, 'setChartSize', function (proceed) {
  proceed.apply(this, [].slice.call(arguments, 1));
  this.clipBox.height += 6;
  this.clipBox.y -= 3;
});
```

BTW, your jsfiddle is broken - highcharts.js depends on an invalid host, presumably pointing to a host your localsubnet :)

**Comment by TorsteinHonsi** [comment]
> highcharts.js depends on an invalid host, presumably pointing to a host your localsubnet :)

Sorry for that, I do that all the time...

**Comment by TorsteinHonsi** [comment]
With the commit above, all you have to do is to set the axis offset: http://jsfiddle.net/highcharts/zYtRS/8/

It will be part of the next maintenance release.

**Comment by TorsteinHonsi** [comment]
This fix was reverted as it broke other stuff.

**Comment by TorsteinHonsi** [comment]
#### Workaround
Another workaround is to add the `graph` to the `series.markerGroup`, which is not clipped, instead of the `series.group`: http://jsfiddle.net/highcharts/zYtRS/11/.

The downside is that the content isn't clipped when zooming the axes. Try to zoom in on the demo.

**Comment by trevorgehman** [comment]
Any progress on fixing this issue without needing a workaround?

**Comment by sebastianbochan** [comment]
Hi @TrevorBurnham,
Please let me know if you use our official [Vue wrapper](https://github.com/highcharts/highcharts-vue) or something different.

**Comment by trevorgehman** [comment]
> Hi @TrevorBurnham,
> Please let me know if you use our official [Vue wrapper](https://github.com/highcharts/highcharts-vue) or something different.

I assume you meant to tag me. I'm using the official Vue wrapper.

**Comment by sebastianbochan** [comment]
I have passed your issue to our Vue developer. He will contact with you as soon as possible.

**Comment by Denyllon** [comment]
Hello @TrevorBurnham 

I prepared the example for you, which shows how you can apply above workaround into your Vue app, so please refer to it.

Live example: https://codesandbox.io/s/highcharts-vue-demo-ygmr6

Kind regards!

**Comment by trevorgehman** [comment]
Just to followup on this, I think this solution solves this issue:

https://github.com/highcharts/highcharts/issues/8235#issuecomment-384964783

**Comment by pawelfus** [comment]
Yes, `series.clip` should resolve that issue. Is that an acceptable solution for now and should we close the ticket @TrevorBurnham @trevorgehman ?

**Comment by trevorgehman** [comment]
Yes I think this solves my issue @pawelfus

**Comment by TrevorBurnham** [comment]
🙆‍♂ Thanks!

**Comment by aryan-acc1** [comment]
Hi, could you please provide some more info about what workflows the proposed work around of wrapping `setChartSize` breaks, as mentioned in https://github.com/highcharts/highcharts/issues/23684#issuecomment-3405336333 ?
Thank you!
