### ISSUE TITLE
Issue with highstock async example and disabled buttons

### ISSUE THREAD

**Issue by andrewboni** [highcharts/highcharts#3168]
I'm trying to adapt the [1.7 million point async example](http://www.highcharts.com/stock/demo/lazy-loading) for my purposes, but running into an issue with the button range selectors being disabled.

The buttons aren't disabled in the above example because of this line (I think):

```javascript
	// Add a null value for the end date
	data = [].concat(data, [[Date.UTC(2011, 9, 14, 19, 59), null, null, null, null]]);
```

I have a multi-series Highstock chart with thousands of data points, and am doing the following (as per the example):
```coffeescript
    $scope.dataSource = [].concat($scope.dataSource[0].data, [[1318622340000, null]])
```

But my buttons are still disabled:
![screenshot 2014-06-17 13 41 45](https://cloud.githubusercontent.com/assets/255026/3306309/d11db854-f65f-11e3-823b-15f8ef168030.png)

What's the best way to make the buttons clickable so that I can use `afterSetExtremes` to fetch data from the server for the new date range?

**Comment by pawelfus** [comment]
It's some old topic, but the answer is to set [`rangeSelector.allButtonsEnabled)`](http://api.highcharts.com/highstock/rangeSelector.allButtonsEnabled).
