### ISSUE TITLE
[Highstock] Scroller moves when chart extremes change, even if user is currently dragging

### ISSUE THREAD

**Issue by SmithPR** [highcharts/highcharts#3171]
[**Demo Fiddle**](http://jsfiddle.net/Cu47r/4/)

When scroller.liveRedraw is set to false, the Stock chart navigator 'snaps' to a previous position if the chart extremes change while the user is dragging it, leading to a frustrating experience.

**Root cause:**
Function **afterSetExtremesHandlerScroller** currently makes the scroller re-render when extremes change, regardless of whether or not the user is currently dragging the scroller.  

**Proposed fix:**
Adding a check for the booleans **scroller.grabbedLeft**, **scroller.grabbedRight**, and **scroller.grabbedCenter** would fix this bug.

_See [line 21336](https://github.com/highslide-software/highcharts.com/blob/master/js/highstock.src.js#L21336) of highstock.src.js or [line 22](https://github.com/highslide-software/highcharts.com/blob/master/js/parts/StockNavigation.js#L22) of stockNavigation.js_

**Comment by pawelfus** [comment]
It works fine in versions at least 4.2.0+ Demo: http://jsfiddle.net/Cu47r/6/
