### ISSUE TITLE
Resizing area chart while drawing results in incomplete fill

### ISSUE THREAD

**Issue by jacobweber** [highcharts/highcharts#3172]
If a HighStock area chart is resized before it's finished drawing, the area ends up not filling the chart.

To see an example, open this fiddle (http://jsfiddle.net/vXt4w/2/) and resize it so the width of the Result section is as narrow as possible. Run it, and during the two seconds before it draw the chart, slowly increase the width of the Result section.

Once the chart is displayed, you'll see that the area doesn't take up the full width of the chart:

![image](https://cloud.githubusercontent.com/assets/542988/3321768/62933642-f73c-11e3-9f1c-3a800de1647d.png)

The same thing happens with version 2.0.1 and the latest version from the master branch.

**Comment by pawelfus** [comment]
It should be already fixed, could you confirm?

**Comment by jacobweber** [comment]
Seems to be working in the above test on Chrome 44.0.2403.155 for Mac....haven't tried it elsewhere.

**Comment by pawelfus** [comment]
It should be working, please reopen if there is another case when it fails.
