### ISSUE TITLE
usage of win.jQuery prevents proper usage of multiple jQuery versions

### ISSUE THREAD

**Issue by matiskiba** [highcharts/highcharts#3173]
Hello,

In highcharts.js, there is a usage of win.jQuery in the adapter initialization, instead of simply using jQuery.
This prevents using multiple jQuery versions. I see no reason to use win.jQuery instead of jQuery. Could you change it?

Thank you in advance,
Mati Skiba

**Comment by pawelfus** [comment]
Closing, reason: jQuery dependancy was removed in v4.2.
