### ISSUE TITLE
Incorrect render on page zoom

### ISSUE THREAD

**Issue by ioncreature** [highcharts/highcharts#3174]
http://jsfiddle.net/bJhgm/11/

Try to zoom out - graph will render incorrect.
When I set `plotOptions.series.animation = true` it works fine.

Thanks, Alexander.

**Comment by kernc** [comment]
Seems to scale correctly on Firefox 38 and Chromium 48.

**Comment by KacperMadej** [comment]
Unable to recreate using version 6.1.4.
Closing as resolved, but if you are able to recreate the issue please leave a comment with more info and the issue could be reopened.
