### ISSUE TITLE
Force height for an Angular gauge

### ISSUE THREAD

**Issue by lagonnebula** [highcharts/highcharts#3177]
Hello,

Here is my example : 
http://jsfiddle.net/yxq8T/

I want to put a width to my "demi" gauge mode. The issue is that the height is automaticly calculated to have a full circle gauge. And when you define a height, the gauge is resized in width.

Is there any solution about this ?

**Comment by KacperMadej** [comment]
Related options are demonstrated in this demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/gauge-vu-meter/

Closing as resolved.
