### ISSUE TITLE
Datalabels, pie chart IE8

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3179]
In case when we set a widht of datalabels, then (in ie8) labels from 2 half are printed incorrect (too much space from connectr).

http://jsfiddle.net/4Fd8X/7/

**Comment by KacperMadej** [comment]
Looks like the problem is not visible when using Highcharts v7.0.3

![3179-ie8](https://user-images.githubusercontent.com/8960408/53735045-0613a000-3e86-11e9-928a-f36b0979d1d3.jpg)

Closing as resolved
