### ISSUE TITLE
Column, bar being cut off on chart resize

### ISSUE THREAD

**Issue by havgry** [highcharts/highcharts#3181]
When resizing the chart beyond its orginal size columns and bars are being filled corresponding to the original plot area instead of the new plot area.

![highcharts resize bug](https://cloud.githubusercontent.com/assets/3898396/3348262/e0a8c522-f91e-11e3-92de-3253884fdd6e.png)

http://jsfiddle.net/MYh5H/

I'm not sure what's happening (and why) but it seems the plot clippaths aren't being properly resized. Hiding those seems to fix the issue, but I'm sure they are there for a reason: http://jsfiddle.net/MYh5H/1/

The issue is likely related to #3172. If I hide the clippaths on that fiddle the issue is fixed but the animation of the serie is broken.

**Comment by amr1tv1rd1** [comment]
Hi there, I am facing the same issue. After drilling down a bar, when user goes back to original chart (bars) they are being cut off similarly in the image above displayed. Any work around for it ?

**Comment by sebastianbochan** [comment]
@amr1tv1rd1 when I run the example: http://jsfiddle.net/y5erce9L/ problem does not appear. Could you update my demo with your code for the further debugging?

**Comment by amr1tv1rd1** [comment]
@sebastianbochan , thanks for looking into it. Issue was resolved by setting "animation:false". Here is the question on [stack](https://stackoverflow.com/questions/41777317/highcharts-bars-are-half-missing-after-drillup)
