### ISSUE TITLE
No support for Highmaps in Standalone Framework?

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#3188]
I'm using a large project that has Angular already implemented.  I'd rather not bloat the project, and currently implementing jQuery as a hot fix will break certain features.

I need to create a Highmap in Angular without the use of jQuery.  Every example I can find online uses the `$('#id).highcharts('Map, {});` jQuery syntax.  When I try to adjust it to angular.element, I end up getting an error along the lines of undefined not begin a function.

I found some resources that use the standalone framework and create a `new Highcharts.Chart` but that will only appear to draw a chart for me, not a map; and when I specify a `chart: type: 'map'` I'll get an error of '"he requested series type does not exist".  A guess at trying `Highcharts.Map` also didn't work.

Here's a brief demo:
http://jsbin.com/rudiz/1/edit?html,js,console

**Comment by dylanbhughes** [comment]
highslide-software you're my hero
