### ISSUE TITLE
Chrome crash: area zoom with vertical dashline

### ISSUE THREAD

**Issue by villeingman** [highcharts/highcharts#3201]
Hey, 
Mac Chrome crashes with "Aw, snap" message when running the following chart and zooming in "quickly". 

  $(function () {
    $('#container').highcharts(
        { "chart": { "type": "scatter", "zoomType": "xy", "borderWidth": 0 }, "title": { "text": "" }, "xAxis": { "title": { "text": "Distance" }, "lineColor": "#CCCCCC", "axisIndex": 0 }, "yAxis": { "min": 0, "max": 20, "title": { "text": "X-Axis" }, "axisIndex": 0 }, "legend": { "layout": "vertical", "align": "right", "verticalAlign": "top", "x": -10.0, "y": 100.0, "borderWidth": 0 }, "credits": { "enabled": false }, "series": [ { "data": [ [ 0, 0 ], [ 0, 20 ] ], "name": "VerticalLine", "visible": true, "marker": { "enabled": false }, "dashStyle": "ShortDot", "showInLegend": true, "enableMouseTracking": false, "color": "#660066", "type": "line" } ], "exporting": { "enabled": false } 
        });  });

See running example here: http://jsfiddle.net/9YM6H/

I'm running Mac Chrome Version 35.0.1916.153.

**Comment by alvarezguille** [comment]
Hi,

I've been testing the mentioned commit eb5906ddea6422774d8357805ea21354f023dc6e and the example in previous post and if I add an horizontal line it can still be reproduced.

This is the working example using the patch or latest release which includes the patch 4.1.1
* Using 4.1.1: http://jsfiddle.net/9wku48nd/
* Using patch: http://jsfiddle.net/htdocwa5/

This is the modified example that fails in both versions:
* Using 4.1.1: http://jsfiddle.net/wsfcuu1o/
* Using patch: http://jsfiddle.net/x06jfgg1/

I'm testing in chrome 40 for windows
