### ISSUE TITLE
Highcharts data module and HTML table change distribution column

### ISSUE THREAD

**Issue by sameerjoshi** [highcharts/highcharts#3210]
I am using Highcharts with its data module (http://code.highcharts.com/modules/data.js) to create a data visualization and chart using HTML table.

My table consists of mixed columns with string - for distribution and numbers for values. The table is something as follows: -

![alnuu](https://cloud.githubusercontent.com/assets/1140446/3429155/049581aa-004f-11e4-9579-c354ea57571d.png)

Now, with the given HTML table, I want the user to be able to select the distribution column based on which the series in the charts are plotted. In the sense when the Product column is selected, the graph would appear something like

![dqamj](https://cloud.githubusercontent.com/assets/1140446/3429158/0d1909b4-004f-11e4-92b1-905971851a58.png)

And if the Category column is selected it would be something like

![ck5kv](https://cloud.githubusercontent.com/assets/1140446/3429159/12e5ee66-004f-11e4-821e-c2ef6a1ec59a.png)

Essentially in this example, the labels in the X-Axis are changed. Although, there are cases when the graph itself would change when the distribution changed.

Progress So Far: -

I have managed to find out that there is a start column and end column which can be defined based on which the distribution column and the values can be identified. Although, this does not traverse the whole table to get the exact results.

I used the following code (Available on http://jsfiddle.net/3Ezjj/) for making the distribution column as Category and the next column as the value: -

```
$(function () {
    $('#container').highcharts({
        data: {
            table: document.getElementById('datatable'),
            startColumn: 0,
            endColumn: 1
        },
        chart: {
            type: 'column'
        },
        title: {
            text: 'Data extracted from a HTML table in the page'
        },
        yAxis: {
            allowDecimals: false,
            title: {
                text: 'Units'
            }
        },
        tooltip: {
            formatter: function() {
                return '<b>'+ this.series.name +'</b><br/>'+
                    this.point.y +' '+ this.point.name.toLowerCase();
            }
        }
    });
});
```

I would really appreciate any help.

Thanks in advance!

**Comment by AshishMishraSmartChip** [comment]
I m getting an error (highchart method not defined)
