### ISSUE TITLE
maxPadding incompatible with logarithmic axis

### ISSUE THREAD

**Issue by SamiRom** [highcharts/highcharts#3223]
The code to reproduce this bug is available at: http://jsfiddle.net/LLExL/3052/

With highcharts 3.0.2, it works fine.
Starting with version 3.0.3 onwards till the current 4.0.1 release, there are actually two bugs:
1. when the maxPadding is commented out, the graph stops prematurely.
2. With maxPadding=0, there is no line.
When the 'type: "logarithmic"' is commented out, everything works fine (but it's not logarithmic :( ).

**Comment by jon-a-nygaard** [comment]
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.
