### ISSUE TITLE
reflow() not compatible with setSize() 

### ISSUE THREAD

**Issue by kohnmd** [highcharts/highcharts#3237]
When `setSize()` is called on a chart giving it an exact height and width, calling the `reflow()` method no longer works to make the chart fill it container; the chart stays at the size defined in the `setSize()` call when subsequent `reflow()`' calls are made. There are cases when a user might want to set the chart to an exact size, then after a container animation have the chart reflow to fill that container.

http://codepen.io/kohnmd/pen/kFtir/

**Comment by pawelfus** [comment]
Well, simple workaround may be to set `chart.hasUserSize` to false. Example: http://codepen.io/anon/pen/JdWyEV

**Comment by m-a-l-p** [comment]
Hi,

Is there any fix for this issue? i'm using highcharts in angularJS2 and whenever the parentComp is resized a function is called to resize the childComp's chart but using this workaround doesn't resolve the issue :(

**START code snippet**
      this.chart.setSize(width,height);
      this.chart.hasUserSize  = false;
      this.chart.reflow(); //this.chart is of type HighchartsChartObject
**END code snippet**


![chart-reflow-issue](https://cloud.githubusercontent.com/assets/18435069/19586806/a04edaee-978b-11e6-8572-a5323e304a59.PNG)

Many thanks,
Toni

**Comment by pawelfus** [comment]
Hi @m-a-l-p - could you recreate issue in jsFiddle? Maybe you have set fixed width/height in pixels for a pane?

**Comment by m-a-l-p** [comment]
Hi @pawelfus, many thanks for the feedback.

Recreating the jsFiddle is a bit troublesome so i check the gauge configuration and i think you hit the issue right on the mark. I set the pane size to 190% to reduce the space on top of my half circle gauge and that was the problem.

Now that i have that fixed i have to find another way to remove the big space above my half-circle gauge -_-"

I know that it's no longer related to this issues but would you know any fix or work around to remove the big space on top of a half-circle gauge? or any link where this issue comes up? I would understand if you don't provide an answer.

Many thanks :)

**Comment by pawelfus** [comment]
Hmm.. it depends how your gauge is configured. This is kind of a default setting I expect to see: http://jsfiddle.net/pcryLu3s/1/ So maybe you have `center` configured: http://jsfiddle.net/pcryLu3s/2/ ?

**Comment by m-a-l-p** [comment]
Hi @pawelfus,

You're right on the mark again! Many thanks!

Seems like solidgauge always reserved the space for the other half which is something that I have to find a way to limit. Can the removal of extra spaces be only achieved by overriding highcharts css?

Many thanks!

**Comment by pawelfus** [comment]
Hmm.. I would change a bit how center+size is calculated according to options, for example: http://jsfiddle.net/k3nef98u/

Snippet: 

    (function(H) {
      H.wrap(H.CenteredSeriesMixin, 'getCenter', function(p) {
        var chart = this.chart,
          options = this.options,
          maxSize,
          center = p.apply(this, Array.prototype.slice.call(arguments, 1));

        // Specific case for angular when we have half-gauge in fact:
        if (Math.abs(options.startAngle) === Math.abs(options.endAngle) && chart.series[0].angular) {
          // Only if height is higher:
          if (chart.plotWidth > chart.plotHeight) {
            maxSize = chart.plotWidth > chart.plotHeight * 2 ? chart.plotHeight * 2 : chart.plotWidth;
            center[1] = H.relativeLength(options.center[1], maxSize);
            center[2] = H.relativeLength(options.size, maxSize);
          }
        }

        return center;
      });
    })(Highcharts);

The only hard thing here it to determine when we have half-gauge, but you can customize first if-else to fit your needs.

**Comment by TorsteinHonsi** [comment]
> The only hard thing here it to determine when we have half-gauge

It is only a function of the `startAngle` and `endAngle`, so you can compute as a function of those. Something that involves Math.sin of the start and end angle. but not smaller. Here's a suggestion, it should adapt to changes in startAngle and endAngle: http://jsfiddle.net/highcharts/k3nef98u/1/

**Comment by DarkFruits** [comment]
Hi,
The workaround using `chart.hasUserSize = false` does no longer work. This can also be tested in the fiddle by @pawelfus
> http://codepen.io/anon/pen/JdWyEV

Is there an updated solution?

**Comment by KacperMadej** [comment]
You could try this:

```js
    $('#reflow-chart').click(function () {
        var chart = $('#container').highcharts();
        if (chart.reflowTimeout) {
          Highcharts.clearTimeout(chart.reflowTimeout);
        }
        chart.setSize(undefined, undefined, false);
    });
    $('#setsize-chart').click(function () {
        var chart = $('#container').highcharts();
        chart.setSize(300, 300, false);
        chart.options.chart.width = null;
        chart.options.chart.height = null;
    });
```
https://codepen.io/Blacklabel/pen/PeLayP

Currently `chart.options.chart.width` and `chart.options.chart.height` are used to calculate `hasUserSize`.

**Comment by DarkFruits** [comment]
Setting `chart.options.chart.width` and `chart.options.chart.height` to `null` did the trick.
Thank you!
