### ISSUE TITLE
Shared tooltip shows values of next category when 3D column displayed from some angle

### ISSUE THREAD

**Issue by zydecx** [highcharts/highcharts#3242]
When hovering over the first-some categories, the tooltip displayes value of the next category. As you adjust the angle of view to some point, i.g. alpha=10, beta=-4, it just becomes normal. You can see the example in the following fiddle:

http://jsfiddle.net/WF9YT/1/

**Comment by KacperMadej** [comment]
Unable to recreate when using v7.0.2
Closing as resolved
