### ISSUE TITLE
Resize After Adding Series Prevents Stacking

### ISSUE THREAD

**Issue by jtfairbank** [highcharts/highcharts#3246]
http://jsfiddle.net/Fa3K5/2/

For a stacked bar chart: after the chart loads, if I update the series then resize the chart the stacking option is ignored.  Note that this only happens with a delayed drawing / redraw.

Tested on Chrome 35, Firefox 28, and Safari 6.1, with the latest version of HighCharts.

**Comment by pawelfus** [comment]
Workaround: http://jsfiddle.net/Fa3K5/3/ - before redrawing chart, recalculate stacks:

                this.yAxis[0].resetStacks();
                this.yAxis[0].buildStacks();

                this.redraw();
