### ISSUE TITLE
BorderWidth for one column

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3249]
Compare:
- 3.x: http://jsfiddle.net/4kqgf/3/
- 4.x: http://jsfiddle.net/4kqgf/4/

Possible workaround: http://jsfiddle.net/WBY26/4/

Culprit: https://github.com/highslide-software/highcharts.com/blob/master/js/highcharts.src.js#L15466

`series.borderWidth` is always defined. Probably `userOptions` should be used, not `options`.

**Comment by pawelfus** [comment]
*Internal note:*
Tricky part is that we can't set `stroke-width` in `pointAttrArray`, because that would require setting default `borderWidth` for column options. In fact, this is not the problem, but it becomes problematic when we have high density for columns, and we disable border [here](https://github.com/highslide-software/highcharts.com/blob/937fb9e4884687ab5e37097d58f33aca126b285d/js/parts/ColumnSeries.js#L153) - default `borderWidth` for column will always prevent this.

**Comment by kzoon** [comment]
Looks like this issue was solved with the introduction of Highcharts 5

**Comment by pawelfus** [comment]
Thank you!
