### ISSUE TITLE
Bar chart - incorrect length of bar

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3251]
Example: http://jsfiddle.net/Pk34e/3/

Bar (30) value seems to be not correct renderered. BorderWidth doesnt solve an issue. Problem appears only in the Chrome (35.0.1916.153).

**Comment by highslide-software** [comment]
It may also be that the gridline is inconsistently rounded, but fixing that would also break all the tests, and it is pretty risky an has a long history of issues. It is pretty stable now, so perhaps we shouldn't touch it for now.

**Comment by sebastianbochan** [comment]
The problem seems to not be still valid. Reopen if will appear again.
