### ISSUE TITLE
Axis scales vary despite same data

### ISSUE THREAD

**Issue by caedev** [highcharts/highcharts#3253]
See http://jsfiddle.net/V4X3n/2/

On load the left axis is (0,1250) and the right is (0,125).
Un-tick red and green and then re-tick.
Now left is (0, 1500) and right is (0, 150) despite the data being the same as before.

Would be much better if the axis ranges were determined the same, irrespective of order in which series are hidden and shown.

**Comment by pawelfus** [comment]
Works fine in 4.1.7, could you confirm?

**Comment by acorncom** [comment]
Looks like this issue should be closed

**Comment by TorsteinHonsi** [comment]
Thanks!
