### ISSUE TITLE
Highstock navigator totally breaks when x-axis is reversed

### ISSUE THREAD

**Issue by tahajahangir** [highcharts/highcharts#3256]
http://jsfiddle.net/9B2gM/

navigator is rendered correctly (and changes correctly when clicking on 1y/ytd/...) but date range cannot be changed with navigator itself (clicking or dragging navigator handles)

**Comment by iiissbartek** [comment]
I have the same problem

**Comment by pawelfus** [comment]
The same issue as #4114, closing as a duplicate.
