### ISSUE TITLE
Download builder - add a url to identify and regenerate/modify build

### ISSUE THREAD

**Issue by ba55ie** [highcharts/highcharts#3257]
It would be very convenient if if the generated file contains a URL which enables a user to identify and regenerate and/or modify a custom build.

Modernizr offers this service:
http://modernizr.com/download/#-fontface-draganddrop-svg-shiv-cssclasses-teststyles-testprop-testallprops-hasevent-prefixes-domprefixes

**Comment by Ba55ie** [comment]
Vote here! :)

http://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/6214420-download-builder-add-a-url-to-identify-and-regen
