### ISSUE TITLE
Tooltip formatter doesn't work with followPointer property

### ISSUE THREAD

**Issue by ittennull** [highcharts/highcharts#3258]
When there are both properties set at the same time the tooltip is not shown

```
followPointer:true,
formatter: function() {...}
```

Example
http://jsfiddle.net/wLvsp/

**Comment by hbayyavarapu** [comment]
I am facing the same issue, line chart in highstocks doesn't render tooltip with followPointer set to true. 
Is it fixed in version highstocks v2.0.4
