### ISSUE TITLE
Panning breaks with reversed logarithmic axis

### ISSUE THREAD

**Issue by autochthe** [highcharts/highcharts#3278]
Panning breaks on axes with {type:'logarithmic', reversed: true}.  If you comment out one of these properties, panning works as normal (but of course the axis is not reversed logarithmic).

Here is a fiddle demonstrating the issue:
http://jsfiddle.net/wXNxW/

**Comment by Drumstix42** [comment]
This issue still exists today. Even if you don't use logarithmic. Notice as soon as you Pan with **reversed** enabled, that it will zoom in. In addition, the RESET zoom button is not displayed.
