### ISSUE TITLE
Error with minPointLength and stacked negative values in column chart

### ISSUE THREAD

**Issue by 0Rudy0** [highcharts/highcharts#3280]
If there are negative values in column and they are stacked, if any of those values is 0 and minPointLength greater than 0, that point will expand up (plus) instead down (minus) and other values in stack won't be aligned properly.

I made an example on jsfiddle where you can see the described problem
http://jsfiddle.net/r3gjQ/
Try changing minPointLength to 0 and back to 20 to see what happens

**Comment by KacperMadej** [comment]
Issue with negative values was resolved here: https://github.com/highcharts/highcharts/issues/7046

Stacking and minPointLength makes no sense as data is not readable and misleading.

If you would like to see this issue reopened please leave a comment with more info about the issue.
