### ISSUE TITLE
Label superposition

### ISSUE THREAD

**Issue by lagonnebula** [highcharts/highcharts#3296]
Hello,

Here is an example : 
http://jsfiddle.net/BL55s/

Here i have a problem some label are under other. I don't want to delete all the label of a serie. 
So can i check each label of each series and move a label ( or hide) when he collide with another one ? 

I imagined to analyse HTML dom and get all the label with the highcharts-data-labels class but it's hard to implement and not necessary available for vml or canvas in case for compatibilities.

**Comment by mcr222** [comment]
Couldn't it use some sort of pie's logic with labels? In a pie a labels never overlap, instead they are moved so that they fit in the chart's canvas. In bars instead of moving them they just shouldn't be painted when overlapping. 
Just saying!

**Comment by highslide-software** [comment]
Actually we're working on this feature for Highcharts 4.1. Currently only works per series, but it should also work across series and with stack labels. See [the single-series demo](http://jsfiddle.net/highcharts/bp1hadr9/).

**Comment by sebastianbochan** [comment]
Meantime, you can adapt this solution: http://jsfiddle.net/menXU/6/

**Comment by mcr222** [comment]
Very cool thanks!

**Comment by KacperMadej** [comment]
Data labels collision detection works across series - resolved.
Doesn't work for stack labels - duplicate (of #7007).
