### ISSUE TITLE
IE8 / jQuery UI 1.8 - Mouse moves not working

### ISSUE THREAD

**Issue by justinethier** [highcharts/highcharts#330]
As noted in this thread: http://highslide.com/forum/viewtopic.php?f=9&t=10912&p=51929#p51929

In IE8 charts inside of jquery dialogs with jqueryui css 1.8+ won't allow zooming. If the css is 1.7 the zooming works. If ie8 is in compatibility mode it works. I believe ie9 has the same issue. Jquery ui css 1.8 and 1.7 work in both chrome and firefox.

Here is an example of jquery ui css 1.7. All browser I've tested can zoom. http://jsfiddle.net/UkpZ8/17/
Here is an example of jquery ui css 1.8. Won't zoom in ie8. http://jsfiddle.net/UkpZ8/26

**Comment by KacperMadej** [comment]
Works fine with jQuery 1.8.2, so this could have been a jQuery issue.
Closing as resolved.
