### ISSUE TITLE
Highstocks: Live chart without navigator and history

### ISSUE THREAD

**Issue by somdoron** [highcharts/highcharts#3302]
I'm trying to create live chart without navigator and history, it just doesn't.

http://jsfiddle.net/fLZM9/

Thanks

**Comment by RKelln** [comment]
Disabling navigator prevents live data updates from working correctly (at least through series.AddPoint()). The points appear to be redrawn (there is an odd animation), and they are added to the end, but the scrolling does not 'autoscroll' even when at the right end.

This is very important to be able to use highstock with live data.

For example here is the js fiddle example of live data with only `navigator: {enabled: false }` added:
http://jsfiddle.net/08znt0dx/

**Comment by vickychijwani** [comment]
+1 for this. My users often want to see just the live chart, without all the bells and whistles, and still be able to zoom / pan around if needed. The scrollbar without the navigator preview is ideal for this use-case.

**Comment by pawelfus** [comment]
Work better in 4.2.5: http://jsfiddle.net/2z3gfuf1/

**Comment by pawelfus** [comment]
And 4.2.6 looks like fixed, demo: http://jsfiddle.net/2z3gfuf1/2/
@vickychijwani, @RKelln and @somdoron - what do you think?

**Comment by vickychijwani** [comment]
@pawelfus looks good!
