### ISSUE TITLE
Highmaps: no FIPS code in state county maps

### ISSUE THREAD

**Issue by andyinabox** [highcharts/highcharts#3305]
It would be extremely helpful on state maps if the individual county properties included a "fips" key that contained the full 5-digit FIPS code. The 3-digit FIPS county code is included in various properties, but always accompanied by the postal code like "us-ny-013." 

This means that if I only have the FIPS code in my data (which is fairly common from my experience, because it allows you to reference both state and county in a standardized way), **I still need to cross-reference the state 2-digit FIPS code with the state postal code** to reference the correct county in the map data.

A common use case is using the `joinBy` configuration option for Highmaps. This would be easy if there was a FIPS code in the map data, I could do something like `joinBy: 'fips'`assuming I also have a "fips" key in my data. But right now I will have figure out which postal code matches the FIPS code that I have, then generate a new code that matches one of the properties in the map file (like "hc-key") This extra step would be unnecessary if I just had a full FIPS code in the map data.

Thanks!

**Comment by orenmagen100** [comment]
This still doesn't work for the UK. Changing "joinBy: 'hc-key' " to "joinBy: 'fips'"  breaks the united kingdom map and leaves only a few states inside.
