### ISSUE TITLE
Piechart tooltips are removed when shared=true

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#331]
1. Create a pie chart with a few values
2. Set the tooltip shared option to true

```
tooltip: {
        shared: true
}
```

Result: The tooltip no longer work

Example: http://jsfiddle.net/Kt6w4/

**Comment by TheDayWalker** [comment]
but 'tooltip - shared : true' option doesn't work ....

**Comment by highslide-software** [comment]
It works here: http://jsfiddle.net/highcharts/Kt6w4/3/

**Comment by TheDayWalker** [comment]
I mean... we use 'shared : true' option when we want to see all points tooltip at once. right? but in pie chart it cannot be

**Comment by highslide-software** [comment]
A shared tooltip means you want to see all points of the same X value, across multiple series, in the same tooltip. Pies slices don't have X values, and each slice's tooltip will always be shown one by one.
