### ISSUE TITLE
When I use timezoneOffset on a datetime chart, showFirstLabel:false does is ignored

### ISSUE THREAD

**Issue by glennmicallef** [highcharts/highcharts#3316]
http://jsfiddle.net/glennmicallef/ea7SR/

Kindly check out the link above. Whenever I use timezoneOffset on a datetime chart, the option showFirstLabel:false is ignored for some reason. If you eliminate timezoneOffset from the fiddle above it works correctly.

I am using this example from Chrome on Windows 7. The timezone is UTC+2

**Comment by KacperMadej** [comment]
[Working since v.4.1.0](http://jsfiddle.net/ea7SR/2/).
