### ISSUE TITLE
Highstock: datetime stacked area with missing values

### ISSUE THREAD

**Issue by m4rk0Kruz** [highcharts/highcharts#3327]
A datetime stacked area with missing values causes bad rendering using the last version of highstock:

http://jsfiddle.net/m4rk0Kruz/k835P/

There were a similar issue:

https://github.com/highslide-software/highcharts.com/issues/1991

**Comment by FabianChanton** [comment]
Another example:  http://jsfiddle.net/xq8c6h07/16/

**Comment by m4rk0Kruz** [comment]
In this example http://jsfiddle.net/m4rk0Kruz/k835P/ it still shows a gap when C series is first disabled, showing this:

![image](https://cloud.githubusercontent.com/assets/7913927/11881064/132ac740-a4ca-11e5-8972-4146ede47933.png)

**Comment by TorsteinHonsi** [comment]
With the `nosegments` it works well: http://jsfiddle.net/highcharts/k835P/3/

**Comment by markalroberts** [comment]
+1 - am hitting this where there aren't associated pointed in each of the series - if I don't stack, then it works fine.

With stacking:

![image](https://cloud.githubusercontent.com/assets/1908518/16013340/f6c60798-3184-11e6-9875-82daacb986b5.png)

Without stacking:

![image](https://cloud.githubusercontent.com/assets/1908518/16013435/4a8281c2-3185-11e6-8b59-25e9cafc3635.png)

**Comment by goodmorninggoaway** [comment]
+1

**Comment by PaulDalek** [comment]
+1

**Comment by jbsalles** [comment]
+1
