### ISSUE TITLE
HighStock slider and stack labels with large data sets

### ISSUE THREAD

**Issue by calexanderbynum** [highcharts/highcharts#3332]
use this example
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/stock/members/series-setdata/

but with the following script instead.

Just converted it to column and added stack labels and enabled stacking.

The chart.yAxis.columns object gets corrupted with large data sets.  I have had it happen with as few as 66 items.

    $(function () {
      $('#container').highcharts('StockChart', {

        rangeSelector: {
            selected: 1
        },
        plotOptions: {
            column:{
                stacking: 'normal'
            }},
        yAxis: {
        stackLabels : {
				enabled : true,
            useHTML : true}
        },
        series: [{
            type: 'column',
            name: 'MSFT',
            data: MSFT
        }]
    });

      $('#button').click(function () {
        var chart = $('#container').highcharts();
        chart.series[0].setData(ADBE);
        this.disabled = true;
      });
    });

**Comment by pawelfus** [comment]
Still valid in 2.1.8: http://jsfiddle.net/peqq08fj/ - not it's caused by `useHTML` flag. Looks like connected to  #1960

**Comment by pawelfus** [comment]
Works fine since v4.2.2: http://jsfiddle.net/4hng50z4/
