### ISSUE TITLE
Hiding/Unhiding multiple series together

### ISSUE THREAD

**Issue by yukon-sergey** [highcharts/highcharts#3341]
Hi,

I was trying to trigger click event on multiple series in the legend bar whenever a specific series is clicked. For instance, by hiding `Series A` I want `Series B` to be hidden as well, and by unhiding `Series A` I want `Series B` to be unhidden.

However, when mixed with multiple series and lots of data points, it just doesn't always work. For instance, I have prepared this isolated demo that reproduces this behaviour: http://jsfiddle.net/yukonsergey/gezy7yu0/

Just click on `Series 1` to hide it together with `Flags` and then try to unhide `Series 1` and you should see that while `Flags` do get unhidden, `Series 1` is not.

Is it related to my data or is it Highstock bug? I'm not sure, but I'm afraid I'm stuck with it and need your help.

Please advise

**Comment by digitalvapor** [comment]
`linkedTo` is very handy, but I've found that when two series are mutually linked, there is a recursion issue. that is, 

```
id: 'A'
linkedTo: 'B'
showInLegend: true
```

and

```
id: 'B'
linkedTo: 'A'
showInLegend: true
```

will exceed the stack size. I suppose manually showing/hiding is fine, just an fyi :) ty.
