### ISSUE TITLE
addPoint() with shift and ordinal xAxis

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3356]
Example: http://jsfiddle.net/8fdyagfc/38/

Steps:
- click 'Add series', 'setData' and 'update'
- click 5M
- wait a while, then try to see left most points

In result you can zoom in place where points used to be, but now are shifted. After new addPoint() our zoom level is changed  to see last points, but we again can go back (for a second) to see point which doesn't exist.

**Comment by nikashitsa** [comment]
:+1:  should be fixed
