### ISSUE TITLE
How to get  the data about map  point ?

### ISSUE THREAD

**Issue by antypang** [highcharts/highcharts#3365]
For example： New York 40°43’0”N,74°0’0”W ，How to convert map x y ?

**Comment by cxytomo** [comment]
Thank you for supporting this feature. I'm recently working on adding mappoint manually. I encountered many problems. And I fixed it.  Here are references for those when want to do the same thing. 

[how to fix Highcharts error #22 Map does not support latitude/longitude](http://stackoverflow.com/questions/29036951/displaying-points-and-drilldown-data-in-highmaps) answered by Halvor Strand

[my blog post](http://tomo.logdown.com/posts/732251-highmaps-and-longitude-conversions), "crs" value from Highmap collection map data contans space which need to be trim.

**Comment by oysteinmoseng** [comment]
@cxytomo: Thank you for your comments. We have decided to introduce a new option `chart.mapTransforms` that should make things a bit more flexible with regards to lat/lon support for custom maps. Drilldown support with different transforms for different levels is something we should also look into.

**Comment by cxytomo** [comment]
@oysteinmoseng hi,do you have option that directly transform lat/lon to coordinates regarding of viewport or canvas?  I want to cast a html5 canvas over highmap and dynamically display halo animation in city that come from server with lat/lon. The coordinates that transformed from **fromLatLonToPoint** are very large and may be negative.

**Comment by oysteinmoseng** [comment]
@cxytomo: The [toPixels](http://api.highcharts.com/highmaps#Axis.toPixels) function will convert from axis value (which is what you get from `fromLatLonToPoint`) to pixel value within chart.

**Comment by cxytomo** [comment]
@oysteinmoseng Thank you. I'll try.

**Comment by oysteinmoseng** [comment]
@cxytomo: You can manually trigger the hover effect and tooltip by calling `point.onMouseOver()` and
`chart.tooltip.refresh(point)`, and use `chart.tooltip.hide()` to hide the tooltip. But you have to figure out which point is being hovered over. Have you considered using the [Highcharts.Renderer](http://www.highcharts.com/docs/advanced-chart-features/freeform-drawing) to make your halo? Then it would be part of the chart SVG instead of a canvas.

**Comment by cxytomo** [comment]
@oysteinmoseng I will be thrilled if I can use pure svg. toPixels works exactly what I want. And I will try Highcharts.Renderer. you've been most helpful. Thank you!

**Comment by cxytomo** [comment]
@oysteinmoseng check this[ jsfiddle](http://jsfiddle.net/qpsjrtbg/). What I want is the circle stay right where it is and gradually scale up. But it seems it scale according to the left top corner.

**Comment by oysteinmoseng** [comment]
@cxytomo: Should be doable, I suggest you contact support@highcharts.com for further assistance to keep this thread about lat/lon issues.

**Comment by cxytomo** [comment]
@oysteinmoseng I got help from highsoft support. Below are two demos that will help those who encounter the same problem. Many thanks to highsoft Kacper Madej.
[1]. [Halo animation](http://jsfiddle.net/sbtohvtw/) using [Highcharts.Renderer](http://api.highcharts.com/highcharts#Renderer) + css3 animation
[2]. [How to remove the added circle](http://jsfiddle.net/sbtohvtw/1/).

**Comment by hgoraya** [comment]
@cxytomo can you please share your halo animation example with lat/long coordinates,

**Comment by cxytomo** [comment]
Here is a post from my blog. Hope that'll be helpful. post-link([http://www.tomo.im/2016/05/12/highmaps-and-longitude-conversions/](http://www.tomo.im/2016/05/12/highmaps-and-longitude-conversions/))
