### ISSUE TITLE
ColumnRange tooltip position

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3372]
Example: http://jsfiddle.net/0xr8698y/1/

When we have multiple series with grouping, tooltip is placed between columns. We should remove arrow or fix tooltip position.

**Comment by dylan-oxide** [comment]
Hi,

I am finding that in v4.1.10 the tooltip is still appearing in the middle of the column.

I created a fiddle using the demo js from to verify
https://github.com/highcharts/highcharts/commit/806c00ac9a308c054f6b5a97f145876cd2cbcd31
http://jsfiddle.net/L06pbwwe/

Has there been a regression?

**Comment by pawelfus** [comment]
Sorry, fix is available currently only on the bugfix branch: http://jsfiddle.net/L06pbwwe/3/

**Comment by dylan-oxide** [comment]
Thanks for the fix, appreciate it :+1:
