### ISSUE TITLE
Bug in the candlestick for BlackBerry 10

### ISSUE THREAD

**Issue by leandroal** [highcharts/highcharts#3376]
Bug report of the candlestick graphic 
We just found that the Highcharts library has an incompatibility with the Blackberry browser, when we try to show a candlestick graphic and the difference between the max and the minimal height is tending to zero on a column, appears a line toward the left superior corner. As show in the following images (from the http://www.highcharts.com/stock/demo/candlestick ) this error only happens in the blackberry Z10 browser.

Blackberry browser
![image](https://cloud.githubusercontent.com/assets/1322483/4002954/e7fb005a-2971-11e4-9f64-1ca09ab4cca1.png)

**Comment by KacperMadej** [comment]
The browser is not supported - https://www.highcharts.com/docs/getting-started/compatibility

If you would like to suggest enhancement idea then please use userVoice to create new suggestion or vote for already existing ideas. The most popular ideas are getting implemented.
https://highcharts.uservoice.com/forums/55896-general
