### ISSUE TITLE
Wrong rendering on Chrome 37

### ISSUE THREAD

**Issue by ivanfioravanti** [highcharts/highcharts#3394]
Rendering of Highcharts in some cases (multiple layers?) is broken in Chrome 37. It's related to the layer squashing implementaiton. If you enable this flag it will work again chrome://flags/#disable_layer_squashing

**Comment by KacperMadej** [comment]
Looks like Chrome version bug. Works fine now. Unable to recreate, please provide more info if you want this issue to be reopened.
