### ISSUE TITLE
pointPlacement with stackedLabels

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3399]
Example: http://jsfiddle.net/1ktmb2d2/

StackLabels aren't translated like columns.

**Comment by synace** [comment]
Work-around: create an additional series prior to the series, with a dataLabel: https://jsfiddle.net/vL8sL3v7/

**Comment by karolkolodziej** [comment]
Hi, @cary-sas.
Can you please tell me which version are you using? Can you please show this issue in the demo?
