### ISSUE TITLE
Axis labels are not hidden when deactivating a series if both min and max are set on the axis

### ISSUE THREAD

**Issue by janjus** [highcharts/highcharts#3403]
See http://jsfiddle.net/dotjdk/uj9og7d2/

When you click the legend for Series 2 to hide it, the labels of the secondary yAxis are not hidden as expected.

If you remove either of the min and max properties on the axis, the axis labels are hidden when the series is hidden as expected.

Tested in Chrome Version 36.0.1985.143 m

**Comment by houmark** [comment]
This also happens for me? Any chance of a fix?
