### ISSUE TITLE
No license info or file.

### ISSUE THREAD

**Issue by webmaven** [highcharts/highcharts#3405]
The package lacks a standard LICENSE or COPYING file describing the open source license under which it is being offered to users.

**Comment by fulldecent** [comment]
+1

**Comment by omouse** [comment]
the package.json doesn't even mention a license either; :+1:

**Comment by sebastianbochan** [comment]
The license.txt is available in the repo. 

Package.json also contains reference to licences file.

Reopen if something is incorrect.
