### ISSUE TITLE
Drilldown with maps

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3407]
Example: http://jsfiddle.net/y49cL3wx/

Steps:
- click on California
- click on drill up button

Some of states are missing.

**Comment by oscarfh** [comment]
Sorry guys, this is still happening. The same example applies 
http://jsfiddle.net/ke7zcasL/9/

If you open firebug, you will see:
TypeError: point.graphic is undefined highmaps.js (Zeile 17368, Spalte 4)
