### ISSUE TITLE
Error when adding/shifting data to a hidden series

### ISSUE THREAD

**Issue by mm-gmbd** [highcharts/highcharts#3420]
I'm adding data dynamically to multiple series on a chart. The same interval is used for all series. I'd like to add points until each series has a certain number of points, so I've added a length check to each series to shift the points if, say, there are more than 15 points on that specific series.

If a series is toggled off from the legend, and then later toggled back on, much of the data that should've been shifted off has been left in the series, and it throws off the entire graph.

Post to stackoverflow: http://stackoverflow.com/questions/25727867/highcharts-error-when-add-and-shift-data-to-hidden-series
JSFiddle: http://jsfiddle.net/mmuelle4/c00cLfs5/

UPDATE: Just to clarify, the issue that seems to be occurring is that when points are added to a hidden series, "series.data.length" is not updated, causing the error.

**Comment by sacarro** [comment]
If you call a series.redraw() after you are done with your series.addPoint(), it seems to update that count, if you can take that performance hit.

**Comment by KacperMadej** [comment]
Resolved as technical support case on StackOverflow - https://stackoverflow.com/questions/25727867/highcharts-error-when-add-and-shift-data-to-hidden-series
