### ISSUE TITLE
yAxis.getExtremes() 

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3422]
Example: http://jsfiddle.net/c81vaz3y/2/

Click on button, you will see that dataMin isn't proper. Value for dataMin is taken from one point before extremes.

**Comment by sebastianbochan** [comment]
dataMax seems to also be wrong:

Example:
 - http://jsfiddle.net/46cqpLa0/

**Comment by Izothep** [comment]
+1

**Comment by evgeniy-logvinov** [comment]
I have the same issue

**Comment by pawellysy** [comment]
Hello @evgeniy-logvinov, could you share the demo, where the issue is reproduced?
