### ISSUE TITLE
Heatmap on canvas - series.update()

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3426]
Example: http://jsfiddle.net/urz7oc5r/3/

Each time we call `series.update()` previous canvas isn't destroyed.

Workaround: just remove canvas in `series.destroy()`:

```
    H.wrap(H.seriesTypes.heatmap.prototype, 'destroy', function (destroy) {
        if (this.ctx) {
            this.ctx.canvas.parentNode.removeChild(this.ctx.canvas);
            this.ctx = null;
        }
    });
```

Example: http://jsfiddle.net/urz7oc5r/4/

**Comment by KacperMadej** [comment]
Works fine when code is based on new demo - https://jsfiddle.net/BlackLabel/55j8qwdn/

Please provide more info and the issue could be reopened.
