### ISSUE TITLE
HeatMap cell color disappears in IE when only a single cell.

### ISSUE THREAD

**Issue by jalmy** [highcharts/highcharts#3427]
I have created an example of the issue.  It only appears to be a problem in IE.  When there is only a single cell in the heat map the cell color disappears when the user hovers with the mouse.

http://jsfiddle.net/4a8xzc47/1/

**Comment by pawelfus** [comment]
Which IE version? Tested with IE8 and IE10 - works fine with 4.1.8. Could you confirm?
