### ISSUE TITLE
Missplaced tooltip

### ISSUE THREAD

**Issue by ferllings** [highcharts/highcharts#3428]
Hello 
On every graph, the tooltip is displayed only if the mouse is placed few centimeters on his left.
![graph](https://cloud.githubusercontent.com/assets/2118130/4232084/7a69d566-3998-11e4-90a9-989cfefed17c.png)
The graph is an div, position:absolute.

 Let me know if this issue has been reported before.

**Comment by KacperMadej** [comment]
Unable to recreate the problem. Please provide a demo showing the problem and the issue could be reopened.
