### ISSUE TITLE
Allow overriding `Highchart.dateFormat`

### ISSUE THREAD

**Issue by pajooh** [highcharts/highcharts#3435]
like #3284 , isn't it ok to make ```dateFormat``` overridable?
i see that ```global.date``` is added for almost the same task, but it requires the exact ```date``` like object.
possibility of customizing the ```dateFormat``` is more like it!

**Comment by pawelfus** [comment]
Since 5.0.0 it's possible to overwrite `Highcharts.dateFormat` method: http://jsfiddle.net/8ryp068j/
