### ISSUE TITLE
Heatmap not working with Highstock

### ISSUE THREAD

**Issue by chevin99** [highcharts/highcharts#3438]
A heatmap displays improperly when using Highstock, but displays properly using Highcharts.  

http://jsfiddle.net/kadams/cwz7sx8u/

**Comment by burakkp** [comment]
I have a same problem.

I want to use heatmap with range selector but I implemented highstock then I get a error like:

> Uncaught TypeError: (0 , _highstock2.default) is not a function

**Comment by pawelfus** [comment]
Hi @burakkp - could  you recreate issue in jsFiddle? Thanks!

**Comment by jon-a-nygaard** [comment]
I tried to recreate the issue with a very basic example, but in this case it seems to work fine https://jsfiddle.net/jon_a_nygaard/290yvm5r/1/

**Comment by burakkp** [comment]
> I tried to recreate the issue with a very basic example, but in this case it seems to work fine https://jsfiddle.net/jon_a_nygaard/290yvm5r/1/

I am using with React. I am adding in like this: 
import highstock from "highcharts/highstock";

 I get a error.

**Comment by sebastianbochan** [comment]
Do you use our official react-wrapper? 
Could you replicate your example as live demo i.e? It will allow us to debug.

**Comment by burakkp** [comment]
> Do you use our official react-wrapper?
> Could you replicate your example as live demo i.e? It will allow us to debug.

Thank you. I fixed. I was implementing wrong path.
