### ISSUE TITLE
Highstock navigator wrong extremes with multiple series

### ISSUE THREAD

**Issue by saydoganreidin** [highcharts/highcharts#3439]
![highstockrangeselectorbug](https://cloud.githubusercontent.com/assets/6853377/4286502/bb8d6570-3d95-11e4-820c-5e1ba7ac80fb.png)

After changing the position of the navigator doesn't show anymore on the other series.
![highstockbug](https://cloud.githubusercontent.com/assets/6853377/4286607/6d798e84-3d97-11e4-95bd-f991f520120b.png)

Sampe Code:
http://jsfiddle.net/x8y2csvs/1/

**Comment by pawelfus** [comment]
Works fine in 5.0.0, where [`series.showInNavigator`](http://api.highcharts.com/highstock/plotOptions.series.showInNavigator) was introduced: http://jsfiddle.net/bs4pddk3/
