### ISSUE TITLE
setData in Highmaps with multiple regions

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3440]
Examples:
- setData: http://jsfiddle.net/js7vu66a/3/
- addPoint: http://jsfiddle.net/js7vu66a/5/

Note: Map is using multiple regions with the same/similar coordinates.

**Comment by KacperMadej** [comment]
This type of map is not supported.
Regions cannot overlap each other - this will create a problem with hover: http://jsfiddle.net/BlackLabel/js7vu66a/10/

Please provide more info and the issue could be reopened.
