### ISSUE TITLE
Issue when putting panning on 'xy'

### ISSUE THREAD

**Issue by yvesvanbouwel** [highcharts/highcharts#3448]
Dear developers,

In the highcarts javascript code, for the panning functionality when zoomed, I see support for a 'xy' option value.  

But when I put the panning option to 'xy', zoom in on a part of the chart and try panning around with the shift key, the values on the y-axis get screwed up/disappear and my chart contents disappears completely. http://jsfiddle.net/yvesvb/pnp0bkeu/

Am I doing something wrong or if it's a bug, is there some kind of workaround?

Kind regards

**Comment by pawelfus** [comment]
`chart.panning` option should be set to `true | false` as described in the [API](http://api.highcharts.com/highcharts#chart.panning). In fact, `xy` is supported, but only for Highmaps.

**Comment by sebastianbochan** [comment]
+1
