### ISSUE TITLE
Android zoom `xy` and tooltip

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3450]
Example: http://jsfiddle.net/4vqr5rqv/

Steps:

- zoom in
- try to tap on some points

It's hard to get tooltip, because panning is applied which automatically hides tooltip.

**Comment by buddyp450** [comment]
Also arrived at this post having issues with zoomType x on a typical line chart.

**Comment by pawelfus** [comment]
+1

**Comment by luiscvalmeida** [comment]
+1

**Comment by sebastianbochan** [comment]
+1

**Comment by G0A** [comment]
+1

**Comment by TorsteinHonsi** [comment]
See fiddle with the fix applied: http://jsfiddle.net/highcharts/4vqr5rqv/1/, or http://jsfiddle.net/highcharts/4vqr5rqv/1/show to test on Android.
