### ISSUE TITLE
Flag move upper on hover

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3456]
1) http://jsfiddle.net/caLmsjro/
2) Hover on C
3) As a resule, C flag moves upper

Chrome: 37.0.2062.120

**Comment by Dorious** [comment]
Try this, because I see that the issue is still not resolved:
http://jsfiddle.net/caLmsjro/1/

In short on mouseOver I redraw the point. Does the job.

**Comment by KacperMadej** [comment]
This is a feature that was introduced as [fix](https://github.com/highcharts/highcharts/commit/136055fa4245550a69b1d6b0cf6f276ea0fd95c9) for issue #1924. There is option no to control it - if you would like to have control over this you could wrap the deafult `drawTracker` function of flag series ([demo for disabling](http://jsfiddle.net/caLmsjro/2/)) or suggest the idea for the new feature in [userVoice](http://highcharts.uservoice.com/forums/55896-general).
