### ISSUE TITLE
Highstock Redraw Issue

### ISSUE THREAD

**Issue by raff77** [highcharts/highcharts#3459]
Hi guys,

I have an Angular, Bootstrap project using Highstock. We are adding a tabbed UI for the charts and are finding a redraw issue when the tab is switched to display a Highstock chart. A Highchart chart redraws fine.

We are calling the reflow() function when the tab has finished rendering so the container has width and height.

Can't replicate in a Fibble thus far, will update here when we do.

As you can see from the screen grabs the chart is full width of the container; just the area that doesn't  reflow. You can see the points are drawn.

![highstock](https://cloud.githubusercontent.com/assets/20372/4407416/0e5e6d72-44ca-11e4-9759-c8b750634233.png)
![highstock2](https://cloud.githubusercontent.com/assets/20372/4407415/0e56f7a4-44ca-11e4-9b8c-8e52c6d77527.png)
![highstock3](https://cloud.githubusercontent.com/assets/20372/4407414/0e543a6e-44ca-11e4-992b-556da93e9d87.png)
![highstock4](https://cloud.githubusercontent.com/assets/20372/4407417/0e66f3de-44ca-11e4-944e-45e0f769d3e5.png)

**Comment by pawelfus** [comment]
Please, reopen this ticket if bug will show up again.
