### ISSUE TITLE
Heatmap vertical legend overlapped

### ISSUE THREAD

**Issue by zigfred** [highcharts/highcharts#3463]
Legend labels out of legend box when legend has border
http://jsfiddle.net/zigfred/21undnfn/

**Comment by pawelfus** [comment]
+1

**Comment by TorsteinHonsi** [comment]
_Internal note_:

We can access the label offset in the `ColorAxis.getOffset` function as `this.chart.axisOffset[this.side]`, but the problem is that this runs after the `drawLegendSymbol` function so we can't use it unless we reorganize a bit.

**Comment by dennismadsen** [comment]
+1

**Comment by TorsteinHonsi** [comment]
It is manually set by the `labelPadding` option: http://jsfiddle.net/highcharts/21undnfn/4/
