### ISSUE TITLE
Calculated dataGrouping unit for a series does not consider legend size when initially rendering chart

### ISSUE THREAD

**Issue by zps938** [highcharts/highcharts#3466]
I am using a Highstock Chart with a legend on the right. When the chart initially renders, the dataGrouping unit is set to 2 minutes. When disabling the series through the legend, and then enabling it again, the dataGrouping unit changes to 5 minutes. After digging through the Highstock code I was able to determine that the plotSizeX includes the legend width on the first render, but excludes the legend width when adding/showing series after the initial chart load.

I created a jsfiddle to replicate the issue: http://jsfiddle.net/fcoog91c/2/
Note that the initial dataGrouping unit is 10 minutes, and after disabling/enabling the series through the legend, the dataGrouping unit changes to 15 minutes. I used random numbers so you can clearly see the line change after the dataGrouping unit change.

**Comment by pawelfus** [comment]
Fixed as per comment above.
