### ISSUE TITLE
The height of pyramid and funnel!

### ISSUE THREAD

**Issue by hexun831012** [highcharts/highcharts#3467]
The height property does not work properly. It crop the graphs but no shrink it which I expected. The same result happens in both pyramid and funnel charts.

I update the jsfiddle at http://jsfiddle.net/4pkq5v0h/1/

Thanks for your reply.

**Comment by pawelfus** [comment]
I'm not sure if this is a bug, since you didn't set separate `neckHeight`: http://jsfiddle.net/4pkq5v0h/4/
The value is strange, though..

**Comment by sebastianbochan** [comment]
Fixed since HC v4.2.7.
