### ISSUE TITLE
Pie render after hiding legend

### ISSUE THREAD

**Issue by MrEcko** [highcharts/highcharts#3470]
Setting the legend options to enabled=false will cause an error when calling render on the chart.
I traced it to the colorizeItem function  where  instead of hiddenColor=legend.itemHiddenStyle.color it works with hiddenColor=legend.options.itemHiddenStyle.color .
Cheers

**Comment by pawelfus** [comment]
Since v5 we can update chart elements imply calling `chart.update(newOptions)`, demo: http://jsfiddle.net/BlackLabel/2dyke9pj/4/
