### ISSUE TITLE
What is this property on the marker and how to remove it?

### ISSUE THREAD

**Issue by stoplion** [highcharts/highcharts#3476]
![image](https://cloud.githubusercontent.com/assets/231343/4464420/9274e980-48d3-11e4-945e-a398525e0e04.png)
![image](https://cloud.githubusercontent.com/assets/231343/4464426/958e6e3e-48d3-11e4-8576-459b9288d2a9.png)

```
plotOptions: {
    series: {
      marker: {
        fillColor: "#26b4af",
        states: {
          hover: {
            fillColor: "#26b4af",
            lineColor: "#26b4af",
            lineWidth: 0,
            lineWidthPlus: 0,
            radius: 0,
            radiusPlus: 0
          }
        }
      }
    }
```

What is this mysterious translucent halo that surrounds the marker and how does one remove it?
[According the docs](http://api.highcharts.com/highcharts#series.data.marker.states.hover) the properties of this marker all above, but as you can see from the screen shot none of those have any effect on it.

Edit
Funny enough the property I believe is called `halo`. But adding..

```
halo: {
  opacity: 0
}
```

Inside the hover state of marker does not remove it.

**Comment by aspiesergosign** [comment]
Agree. And it's confusing that the halo can be only set for hover... but not initially... :-/

**Comment by TorsteinHonsi** [comment]
> I feel this is confusing because the halo seems like a unit of the marker and it's strange that one would have to style it outside of that.

There are cases where there is a halo and not a marker, for example on pie series. That's why we couldn't make it a marker property.
