### ISSUE TITLE
Highstocks Enter-Key in DatePicker not working (Internet Explorer 8-11)

### ISSUE THREAD

**Issue by berlam** [highcharts/highcharts#3477]
Currently it is not possible in Internet Explorer to refresh the chart with a keypress on "enter" while in top right date range picker to let the chart rerender.
Chrome and Firefox work as expected and refresh the chart. 

Demo:
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/stock/rangeselector/styling/

**Comment by sebastianbochan** [comment]
+1

**Comment by jon-a-nygaard** [comment]
Seems that IE does not fire the onchange event when enter is pressed. Working on a fix where the Rangeselector is listening to keypress and looking for enter.
