### ISSUE TITLE
Relative sizing in Bubblechart is wrong

### ISSUE THREAD

**Issue by cruising** [highcharts/highcharts#3480]
It appears that the smallest bubble is always tiny without regard to the size of the other elements.
Please consider this fiddle: http://jsfiddle.net/huq6uwuz/

There should be three sizes: 99, 100, 101 but the one representing 99 is way smaller than the difference between the 100 and 101 circle would suggest.

**Comment by GeorgeLordsOfCastle** [comment]
The bug still remains!
Using "width" it's only less evident than using "area".
The smallest bubble is showed in a wrong proportion.

http://jsfiddle.net/9cqu7a3q/
Remove and add the third series to understand what I mean.
