### ISSUE TITLE
Tooltip doesn't want to show after adding a point

### ISSUE THREAD

**Issue by slawekkolodziej** [highcharts/highcharts#349]
In live data chart, just after adding a point tooltip locks and doesn't want to show until you move the mouse out of the series and hover it again. See: http://jsfiddle.net/4bVWT/ try to move the coursor through points.

**Comment by donnietarrosa** [comment]
at what version of highcharts does this issue fixed?

**Comment by pawelfus** [comment]
According to the [change-log](http://www.highcharts.com/documentation/changelog) it's fixed since 1.1.6 in Highstock.

**Comment by donnietarrosa** [comment]
We are currently encountering problem with the highcharts area spline in which the tooltip quickly disappears and the points are not animating if the mouse hovers on. we are using highcharts 2.3.3 along with YUI in IE.

**Comment by highslide-software** [comment]
See https://github.com/highslide-software/highcharts.com/issues/1067#issuecomment-71761821

**Comment by ruferson** [comment]
We are encountering the same problem with a spline chart, only when there are 2 or more series at once, and updating on real time (with only 1 series the tooltip keeps following the point we hovered previously). We use "highcharts-react-official": "3.0.0" and 	"highcharts": "9.3.2".

**Comment by karolkolodziej** [comment]
@ruferson Could you please share a demo with your example? I'm wondering how you perform that update
