### ISSUE TITLE
Spacing 0 causes clipping

### ISSUE THREAD

**Issue by NiGhTTraX** [highcharts/highcharts#3490]
![image](https://cloud.githubusercontent.com/assets/485061/4518443/820faeb4-4c8d-11e4-8bd6-a6663a7446dc.png)

![image](https://cloud.githubusercontent.com/assets/485061/4518453/27bee5f0-4c8e-11e4-90ec-f38efdd8817c.png)

This occurs when:
- spacing is set to 0,
- chart title is disabled.

If all the series have `showInLegend: false`, the X axis is not clipped.

If the chart title is not disabled, the Y axis is not clipped

Demo here http://jsbin.com/gevoc/1/edit

**Comment by sebastianbochan** [comment]
The problem is still valid for yAxis. The legend works properly in 6.1.

**Comment by NiGhTTraX** [comment]
Closing this as I haven't used highcharts in a long time.
