### ISSUE TITLE
Highstock 2.0.4: Cannot have a Flag without a title, defaults to the letter A

### ISSUE THREAD

**Issue by mikegodber** [highcharts/highcharts#3493]
Hi,

I am displaying flags with custom icons on a chart and I do not want to display a letter, or text, on the chart, only on hover. I have for a while used title:' ' to get rid of the letter since using null or '' defaults to an A character. 

With the space character it seemed to work fine, although I have just had some reports of troubles in IE and looking into it IE9, IE10 & IE11 all fail to display the hover when no letter is displayed. I have a right click event that also does not work since there does not seem to be a hit area anywhere.

It looks like the only work around I have at the moment is use a dot or underscore and position it so it doesn't look terrible.

See here for a fiddle: http://jsfiddle.net/x35wckdj/

Any help would be much appreciated

Mike

**Comment by sortik** [comment]
I solved this problem with these two options useHTML:true, and then title : '&nbsp;',

**Comment by KacperMadej** [comment]
I have checked the demo for IE8 - IE11 and all flags are being displayed correctly - first is empty, second has letter A (default flag title), third has _. If the problem is still possible to recreate please create a demo and the issue will be reopened.
