### ISSUE TITLE
chart receive click event when click on export context menue without a chart title

### ISSUE THREAD

**Issue by AWoelfel** [highcharts/highcharts#3495]
Using a chart without a title, the chart.events.click event (to view a bigger version of the chart in our case) and the exporting menu (default or custom buttons) the chart.events.click event is fired when clicking on the exporting menu button.

can be reproduced here => http://jsfiddle.net/Loecd2p8/1/

**Comment by KacperMadej** [comment]
Still an issue in version 6.1.3
