### ISSUE TITLE
Highcharts data labels overlapping columns

### ISSUE THREAD

**Issue by SrikanthDesu** [highcharts/highcharts#3498]
Hi,

We are using highcharts version 2.0.5 
Highcharts data labels are overlapping with columns. We have tried setting "crop" and "overflow" attributes. These are not working with my version of highcharts. 

How we can fix this issue in 2.0.5 version ?

**Comment by oysteinmoseng** [comment]
Highcharts now prevents overlapping of datalabels out of the box, so closing this.
