### ISSUE TITLE
Datalabels styling options changed by formatter have no effect

### ISSUE THREAD

**Issue by dlopuch** [highcharts/highcharts#3502]
Although [undocumented](http://api.highcharts.com/highcharts#plotOptions.series.dataLabels.formatter), the data labels formatter [gets passed the data labels options object](https://github.com/highslide-software/highcharts.com/blob/v4.0.4/js/parts/DataLabels.js#L80).

This is very helpful if the labels formatter wants to change some of the styling options on a point-by-point or on a per-render basis.  For example, in [this fiddle](http://jsfiddle.net/Lt340byn/5/), we (try to) change the label size based on the chart render size every time you resize the window.  You can imagine the formatter wanting to change other style, alignment, color, etc. options.

Unfortunately, the data labels options are not re-applied after the data labels formatter runs.  Submitting a proposed PR solution that just re-arranges where some of the data labels operations are done.

**Comment by dlopuch** [comment]
Any thoughts on this one?  Been a couple of months.  Updated the PR to work against latest.

**Comment by highslide-software** [comment]
As pointed out above, if only the font-size is case, you can add it inline. You don't even have to use HTML: http://jsfiddle.net/Lt340byn/8/ .
