### ISSUE TITLE
top parameter hides flags on xaxis

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3517]
When we get rid of top parameter in yAxis, flags appear.

Example: http://jsfiddle.net/Ln3hLmgn/2/

**Comment by pawelfus** [comment]
Workaround:

Add dummy `yAxis` and connect to the series (demo: http://jsfiddle.net/Ln3hLmgn/6/) : 


            yAxis: [{
                title: {
                    text: 'Exchange rate'
                },
                top: '72%',
				height: '28%',
            }, {
                // dummy Axis
        	}],

And flags connection:

            series: [{
                name: 'USD to EUR',
                data: data,
                id: 'dataseries',
                tooltip: {
                    valueDecimals: 4
                }
            }, {
               	yAxis: 1, // use separate Axis
                type: 'flags',
                name: 'Flags on axis',
                data: [{
                    x: Date.UTC(2015, 4, 1),
                    title: 'On axis'
                }, {
                    x: Date.UTC(2015, 5, 1),
                    title: 'On axis'
                }],
                shape: 'squarepin'
            }]

**Comment by KacperMadej** [comment]
+1
