### ISSUE TITLE
Inactive tooltip overlays charts in page longer than 9999px

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#3532]
When page is longer than 9999px then empty tooltip boxes start appearing on the page. It appears their position is translated to (0,-9999) so when a page extends longer they are no longer hidden from view.

Example: http://jsfiddle.net/meku/5vvdwL20/

The empty white tooltip squares actually belong to the charts near the bottom of the page.

**Comment by pawelfus** [comment]
Connected to #3542

**Workaround:**  http://jsfiddle.net/5vvdwL20/3/

Snippet: 

    (function (H, HA) {
        H.wrap(H.Tooltip.prototype, 'init', function (p, c, o) {
            p.call(this, c, o);
            this.label.hide();
        });
        
        
        H.wrap(H.SVGElement.prototype, 'hide', function (p, inherit) {
            if (this.div) {
                HA.animate(this.div, {
                    opacity: 1
                }, {
                 	duration: 0   
                });
            }
            return p.call(this, inherit);
        });
        
        
        H.wrap(H.SVGElement.prototype, 'show', function (p, inherit) {
            if (this.div) {
                HA.animate(this.div, {
                    opacity: 1
                }, {
                 	duration: 1   
                });
            }
            return p.call(this, inherit);
        });

        H.wrap(H.SVGElement.prototype, 'fadeOut', function (p, duration) {
            var elemWrapper = this;
            elemWrapper.animate({
                opacity: 0
            }, {
                duration: H.pick(duration, 150),
                complete: function () {
                    elemWrapper.hide(); // #3088, assuming we're only using this for tooltips
                }
            });
            if (elemWrapper.div) {
                HA.animate(elemWrapper.div, {
                    opacity: 0
                }, {
                    duration: H.pick(duration, 150)
                });
            }
        });
    })(Highcharts, HighchartsAdapter)

**Comment by highslide-software** [comment]
Can't we just du this the brute-force way and set tooltip y to -99999 instead of -9999?

**Comment by pawelfus** [comment]
Is there sam limitation in SVG for `y` position? If not, why not use `-Number.MAX_VALUE` ?

**Comment by highslide-software** [comment]
It's probably okay. You can test it in different browsers and see.

**Comment by DavidKDeutsch** [comment]
I see this issue was never closed; has the fix not made it into an official release yet?

**Comment by TorsteinHonsi** [comment]
Fixed by c97123f65da030c0d6a7d75acbdaf81be7580d11, badly named
