### ISSUE TITLE
Halo does not disappear on hiding series (mobile)

### ISSUE THREAD

**Issue by Vincenttbk** [highcharts/highcharts#3533]
Hi,

I've encounter a graphical bug on highcharts when I am integrating highcharts with mobile. You can use the demo chart provided in highcharts (http://www.highcharts.com/demo) to replicate the problem. I have used the line chart example within the page to replicate the issue

Replication steps:
1. Select a point on the chart and allow one of the tooltip from any of the series to appear.
2. After the tooltip is shown, disable any other series(other than the one selected) by tapping on the legend
3. Disable the series that you have selected earlier on, the dot will remain there.
4. Repeat a few times, and you can see the result as follows:

![screen shot 2014-10-23 at 10 10 17 am](https://cloud.githubusercontent.com/assets/6511112/4747282/ca7d7030-5a59-11e4-930a-4876840317a9.png)

Hope can find a solution to fix this issue.

**Comment by adamncsu** [comment]
This issue can be reproduced on desktop, when you have a floating legend.

([demo](http://jsfiddle.net/6p9z0Lwe/))
1. Hover over a point on Series 2
2. Move to the legend while the point is still highlighted
3. Hide Series 1
4. While the chart is animating, mouse out of the chart
5. Halo element is now stuck on the canvas, even if you disable Series 2

**Comment by sebastianbochan** [comment]
+1

**Comment by pawelfus** [comment]
Works fine in 5.0.9
