### ISSUE TITLE
3D Pie with Drilldown: Animation Broken or not supported?

### ISSUE THREAD

**Issue by quickstep25** [highcharts/highcharts#3534]
## 3D Pie with Drilldown: Animation Broken or not supported?

When enabling animation for a 3D pie drilldown, the animation breaks and makes the chart no longer usable.

I have tested this in the latest Firefox, Chrome Canary, Safari builds by using the drilldown example in the demos. http://jsfiddle.net/quickstep25/yhqqo2wv/

The animation doesn't start when you first click a slice to drilldown and it also breaks when you try to return to the parent series.  Here is the screenshot of the result when using the "Back to series" button.  

![image](https://cloud.githubusercontent.com/assets/3681250/4749916/c140f00a-5a8b-11e4-846f-9cfd86e02dfa.png)

**Comment by augun** [comment]
Hi quickstep25,
Were you able to find a solution/workaround to this problem? 
Thank you in advance.

**Comment by quickstep25** [comment]
No, I have not.  I've considered using another charting library to fit the needs of my application, but have not ruled out using HighCharts, I just no longer use any 3D objects in that library.  At least until support is provided or a fix in place.

**Comment by stephanevanraes** [comment]
When drilling up a function called 'fadeIn' is called on the elements that have to be shown again, however, this method is not defined on a 3d-arc, as a consequence the slices remain hidden. A simple solution would be to define a fadeIn function and have it do the same as the show method. 
http://jsfiddle.net/0mdfp0n5/1/
With that fix, the slices will be visible again, you will however not have the 'fading' effect.

**Comment by augun** [comment]
I have a similar workaround with custom drilldown/drillup, where I do  chart.addSeriesAsDrilldown, just wanted to check if there are better solutions, as mine returns some errors to console, like   
Cannot read property 'xAxis' of null
Cannot read property 'drilldown' of undefined. 

What is a bit problematic with the fix you provided, is that animation effect of drillup/drilldown is lost in such case.

**Comment by quickstep25** [comment]
@stephanevanraes :+1: 
Adding your fadeIn function fixes the problem, slices are visible when clicking the "return drilldown" button.    Thank you for looking into the issue.  I'll let you close this issue when you see fit.

**Comment by thuvt** [comment]
Hi There,

From your solution at http://jsfiddle.net/0mdfp0n5/1/ , we still see a bug losing the real color when drilling down 2nd level or 3rd level. Every pies have the same color until mousing over the pie.
Please advise if you have any idea with this.

Thank you very much!

**Comment by mscpr** [comment]
I understand that this bug has not been fixed, as I am experiencing it on my 3d, drilldown pie charts. I am using Highcharts 4.1.5.

**Comment by subhasispatra** [comment]
I have same drilldown issue. The drill up is not rendering graph properly. Can someone help me on this? Thanks in advance. I need 3d with drill down option.
http://jsfiddle.net/subhasispatra/np0bn3ps/

**Comment by jpla2005** [comment]
I have the same problem. Using the suggested fix works but some times I don't see the real colors on second step until mouse over slices.

**Comment by m1dst** [comment]
One year on and still the problem persists in the main library.  Surely we can get an official fix for this rolled in?

**Comment by highslide-software** [comment]
Problematic case: http://jsfiddle.net/highcharts/9ncyksfy/

**Comment by KacperMadej** [comment]
The problem is still visible. Hover on animation while drilldown is happening causes slices to freeze in the middle of the animation.

Demo: http://jsfiddle.net/BlackLabel/9ncyksfy/3/

**Comment by KacperMadej** [comment]
Regression caused by https://github.com/highcharts/highcharts/commit/222eae0
