### ISSUE TITLE
highcharts : Destroy chart in zoom afterSetExtremes event

### ISSUE THREAD

**Issue by ronanquillevere** [highcharts/highcharts#3535]
Hello,

Use case:
We have created some kind of drill-down functionnality in our application, based on highcharts zoom feature. After zooming in our chart, we get the min and max values. Based on those, we recompute a new data set (with more details) for that period on our backend. Then we want to destroy the current chart and display a new one with the new data. We cannot use use redraw as we display new plotbands etc. This works fine, except we get a crash after destroying the first chart. 

Seems that the unselection process done when zooming still tries to finish whereas the chart was destroyed.

We tried to delay de destroy(), this will suppress the javascript error but in that case, the highcharts natural zoom occurs before the chart is destroyed then replaced. This is not acceptable in terms of user experience. 

Details : 
Fiddle to reproduce : http://jsfiddle.net/hyoycmvj/3/
Error message : Uncaught TypeError: Cannot read property 'destroy' of null 
Line 9406 - v4.04 : this.selectionMarker = this.selectionMarker.destroy();

Regards

**Comment by pawelfus** [comment]
Works fine since v6.0.5: http://jsfiddle.net/BlackLabel/hyoycmvj/6/
