### ISSUE TITLE
Exporting button zIndex

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3540]
When using Highmaps and exporting, after zoom, we render button below map shapes: http://jsfiddle.net/pw51rvyp/1/

Workaround is to grab buttons to the front of svg in callback: 

```
            setTimeout(function() {
                if(chart.exportSVGElements) {
                    $.each(chart.exportSVGElements, function(i, element) {
                        element.toFront();
                    })
                }
            }, 1);
```

**Comment by digitalvapor** [comment]
as I understand it, some svg elements are layered in the order they are drawn. is it possible to set the z-index in the highchart options.

for example, set the export button to never go below a curser tooltip which could make things unclickable.

**Comment by CWSites** [comment]
This is still an issue, any update on when it will be fixed?

**Comment by TorsteinHonsi** [comment]
I can't see the issue with http://jsfiddle.net/pw51rvyp/1/?

**Comment by pawelfus** [comment]
It works fine since 4.2.2+ - it should be closed.
Compare: http://jsfiddle.net/pw51rvyp/2/ vs http://jsfiddle.net/pw51rvyp/3/
