### ISSUE TITLE
linkedTo undefined when update

### ISSUE THREAD

**Issue by lminuzzi** [highcharts/highcharts#3547]
I created a checkbox for hide and show the company column.
In the toggle function I compared stackKey == 'columnEmpresa'. so when I will uncheck the "Compare" check, the column with stack="Empresa" will hide this column. The problem is that when I check again the "Compare" check, the column doesn't show, because the stackKey is undefined.
If replace stackKey == 'columnEmpresa' to stackKey != 'columnMinha área' it works.
Considering that have only two stackKey, for stack 'Empresa', the comparison stackKey == 'columnEmpresa' is the same result as stackKey != 'columnMinha área'. (line 94 in jsfiddle)

jsfiddle: http://jsfiddle.net/lminuzzi/r7w8e4ua/
Browser: Mozila Firefox 32.0.3

**Comment by pawelfus** [comment]
Why do you use inner property `stackKey` instead of `series.options.stack` ? See working demo: http://jsfiddle.net/r7w8e4ua/1/

**Comment by jon-a-nygaard** [comment]
Closing this issue due to pending a reply, and it is considered inactive. Should anyone have further information about the issue, please comment and/or reopen.
