### ISSUE TITLE
Issue with Line Graphs in Chrome

### ISSUE THREAD

**Issue by dejongch** [highcharts/highcharts#3550]
I found that if you set a graph or the parent of a graph to have visibility hidden after a line graph has been drawn in chrome when you remove the visibility hidden the lines are missing until you hover over them.

http://jsfiddle.net/wmtmpmuy/

**Comment by ehinter** [comment]
Here's another CSS workaround if you don't want to use the * selector. Set the SVG to use 'display:none'

http://jsfiddle.net/qax0w4r5/1/

**Comment by KacperMadej** [comment]
Unable to recreate, please provide more info if you want this issue to be reopened.
