### ISSUE TITLE
xAxis DateTime in Scatter Plot should convert Tooltip

### ISSUE THREAD

**Issue by klexas** [highcharts/highcharts#3552]
When you have defined the xAxis as a 'dateTime' type the tooltip should be aware of this as the 'point.x' value and convert it to the DateTime format.

http://jsfiddle.net/egf4vbfL/6/

As you can see the X-Axis is correct in that it uses the Time rage however when you view the default tooltip you get the epoch time.

I know you can format this using 'point.key' etc but it is not expected behavior.

**Comment by chevalierc** [comment]
I second klexas's comment about the tooltip.

**Comment by WhiteBearSpirit** [comment]
And still no change. Do developers have any particular reason to leave formatting like that?

**Comment by bharatnagdev** [comment]
It has been a while is there any update or workaround?

**Comment by pawelfus** [comment]
Solution is simple, see: https://github.com/highcharts/highcharts/issues/3552#issuecomment-61230443 - set `pointFormat` with required formatting for x-value. Alternatively, you can use `tooltip.pointFormatter` or `tooltip.formatter`.

**Comment by bharatnagdev** [comment]
i think i was not clear with what i want to actually achieve when i said change the tooltip format.
here is the [link](https://cloud.highcharts.com/create?q=VC7oDQYbc)
steps to reproduce :
->select chart type as scatter from scatterbubble chart
and also attaching an image where the highlighted area is what i want to modify actually
![highcharts cloud](https://user-images.githubusercontent.com/43880269/46567701-dd2dc400-c954-11e8-93f6-3b6ee9ec69e5.png)

**Comment by pawelfus** [comment]
In Advanced -> Custom code tab you can set format:

```javascript
Highcharts.merge(true, options, {
    tooltip: {
    	headerFormat: '{point.key}'
    }
});
```

**Comment by bharatnagdev** [comment]
Thanks @pawelfus it worked.

**Comment by bharatnagdev** [comment]
Hi @pawelfus 
Tried to implement the code and it returned an error 'chart object.merge' is not a function
any suggestions what's wrong in it?

**Comment by sebastianbochan** [comment]
Hi @bharatnagdev 
Did you place the code in the section: 
![zrzut ekranu 2018-10-16 o 10 00 03](https://user-images.githubusercontent.com/2115686/47001239-46b68b00-d12a-11e8-9593-388d3245efa0.png)

When I run the console I do not see the error. Could you confirm that it still appears? If yes, which browser do you use?

**Comment by pawelfus** [comment]
@bharatnagdev 

So you are not looking for a Highcharts Cloud solution? In that case please provide **full description** of the issue. At this moment we can only guess what is wrong, for example you use outdated typescript/flow definitions. Additionally, please provide a live demo. Note that solutions for Highcharts Cloud are different from simply using Highcharts library...

**Comment by bharatnagdev** [comment]
Hi @pawelfus 
i shared the Highcharts cloud link for the explanation of issue i am facing.
here is the [link](https://jsfiddle.net/4uwf8bcq/) 
![desktop screenshot](https://user-images.githubusercontent.com/43880269/47011627-0671ff80-d160-11e8-994e-96da3e41790a.png)

**Comment by pawelfus** [comment]
In your case @bharatnagdev  simply set `headerFormat` in options for series or for tooltip, like any other option. Demo: https://jsfiddle.net/BlackLabel/4uwf8bcq/4/

**Comment by bharatnagdev** [comment]
Thanks @pawelfus finally it worked.
