### ISSUE TITLE
9.5m instead of 9,500k

### ISSUE THREAD

**Issue by lapidus** [highcharts/highcharts#3556]
Why is labeling on y axis printed with the "k" suffix instead of "m" when the data is in the millions range?

9 500 000 => 9,500k instead of 9,5m

**Comment by KacperMadej** [comment]
Resolved through the commit https://github.com/highcharts/highcharts/commit/a1eae171d303618929721e24d8efc9cefad2fe48

Demos:
http://jsfiddle.net/BlackLabel/eqr9068p/
http://jsfiddle.net/BlackLabel/y28hfkgh/8/

The currently implemented logic requires ticks interval to be larger than or equal to magnitude currently checked - 1000 when trying to set 'k', 1 000 000 when trying to set 'M', etc.
