### ISSUE TITLE
Range selector buttons are not resized when long texts are used

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#356]
1. In StockChart, customize the range selector buttons with longer text.
2. The frame around the buttons is not made bigger to hold the new text.

Expected: The button frame to be big enough to hold the text

Example: http://jsfiddle.net/xTxWz/

**Comment by alapiere** [comment]
doesn't work with large text , like "From the beginning" instead of "All" -> the filled background width is shorter than the text ..

**Comment by pawelfus** [comment]
Thanks @alapiere ! Reported as a separate bug: #12163
