### ISSUE TITLE
Pie percentage in legend with hidden slice

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3560]
Example: http://jsfiddle.net/j2japnhp/1/

In legend, we have two different results, however the datasets are exactly the same. Looks like percentage for legend is used according to visible slices, not all of them.

**Comment by oysteinmoseng** [comment]
Did we decide that this was by design?

**Comment by pawelfus** [comment]
I don't think it's a bug anymore, we have `pie.ignoreHiddenPoint` to control how legend behaves: http://jsfiddle.net/j2japnhp/17/

**Comment by pawelfus** [comment]
I may be wrong - pie is rendered with reserved space for a hidden slice, which not necessary is the expected result.
