### ISSUE TITLE
Pie innerSize: unexpected behaviour when defined as string

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#3562]
When the innerSize option is defined in pixels but written as a string, the value is not parsed correctly: http://jsfiddle.net/jd10efL7/

**Comment by stephanevanraes** [comment]
API : **"The diameter of the pie relative to the plot area. Can be a percentage or pixel value. Pixel values are given as integers."**

In the case of
```javascript
 size: "20"
````
should this be interpreted as pixels or percentages?

**Comment by highslide-software** [comment]
Those are integers in a string, so it is pixels.
