### ISSUE TITLE
Highstock: RangeSelector - ButtonPosition improvement request

### ISSUE THREAD

**Issue by acorncom** [highcharts/highcharts#3565]
Hello, I'm interested in positioning the rangeselector on a Highstock graph.  I found the below issue that added base support, which allows a base level setup for things:
https://github.com/highslide-software/highcharts.com/issues/3395

Interesting note: the docs available at Highchart.com don't mention the new `buttonPosition` option - http://api.highcharts.com/highstock#rangeSelector.buttonTheme)

But I'm interested in positioning the entire range selector on the right side (right-justified actually) as seen in this jsFiddle:
http://jsfiddle.net/7fmcgchL/

and that doesn't seem to be possible yet.  Could we get more complete positioning support?  The ability to specify `right: 10px` as we can do in other places would be ideal.

Thanks!

**Comment by Solruu** [comment]
Hi,

As said in a previous request (https://github.com/highslide-software/highcharts.com/issues/3395), it seems that the "buttonPosition" option on rangeSelectors has been included in the changelog, but I couldn't find it in the highstock.src.js file (v 2.0.4)...

Any clue about what might have occur ?

Thanks

**Comment by pawelfus** [comment]
`buttonPosition` are available but undocumented.

**Comment by TorsteinHonsi** [comment]
Added.
