### ISSUE TITLE
NaN point value makes series disappear

### ISSUE THREAD

**Issue by albhilazo** [highcharts/highcharts#3571]
Didn't find any report on this issue so here it goes.
http://jsfiddle.net/993ee7cx/
If an area or line series has a point with 'NaN' value, the whole line disappears. In the previous example you can see the points, but for series with hundreds of points you can only see the tooltip.
http://jsfiddle.net/993ee7cx/1/

Null values seem to be controlled, but since [Error #14](http://www.highcharts.com/errors/14) recommends the use of 'parseFloat()' and [it returns NaN for null values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat#Description) it can be a problem for DB retrieved data.

For the time being I went around it with a simple check
```
seriesdata.push({
    'data': [ ( (isNaN(parseFloat(stringval))) ? null : parseFloat(stringval) ) ]
});
```

**Comment by filmor** [comment]
It makes a lot of sense to add this check. We are using highcharts with typed arrays which can contain NaNs. The current buggy handling of NaN values leads to an additional conversion into a js array which costs us far more performance than this simple check would. Maybe you could make it configurable?

**Comment by epa** [comment]
Could I add a 'me too' to this.  The bug is that if NaN appears in the data then the series is drawn in invisible ink.  You can still hover over it with the mouse but the line isn't shown.  This really doesn't make any sense; by all means fail if NaNs are given but not in this weird way which isn't immediately visible.  (If there are ten series on the chart and one of them becomes invisible without warning...)

**Comment by epa** [comment]
Thanks!

**Comment by albhilazo** [comment]
Thanks!

**Comment by TorsteinHonsi** [comment]
You're welcome!

**Comment by cnrudd** [comment]
Thanks for fixing.  I've tested the fix.

There is one edge case that is does not appear to be fixed:  a NaN at the very first point of a timeseries will still cause the whole timeseries to disappear.

Not a big deal for us, but it seems like it might be worth mentioning.

**Comment by pawelfus** [comment]
Thank you for pointing this out! Live demo: http://jsfiddle.net/993ee7cx/2/

*Internal note:*
Extremes for series are `NaN` in this case, [here](https://github.com/highcharts/highcharts/blob/2bba08ffe0ac1f90062885a1fd5856aae5229e05/js/parts/Series.js#L686) we should also use `isNumber()` instead of comparing with `null` and `undefined`.

**Comment by grovesNL** [comment]
@TorsteinHonsi Similarly to `NaN`, what's the expected behavior for `Infinity`/`-Infinity`? I can't find anything in the documentation about it, and it seems relevant to this issue. I can open a new issue if you'd like.

**Comment by TorsteinHonsi** [comment]
Interesting question... `Infinity` and `-Infinity` are numbers, but we can't plot the on the Y axis, so maybe they should be treated as invalid values. It is quite simple to work around that by modifying the `Highcharts.isNumber` function:

```js
H.isNumber = function (n) {
	return typeof n === 'number' && !isNaN(n) && n !== Infinity && n !== -Infinity;
};
```

On the other hand, `Number.MAX_VALUE` is actually a number that can be plotted, but currently Highcharts chokes on it and displays an empty chart.

**Comment by grovesNL** [comment]
Yeah, I'm not sure what users would expect to happen in these cases either. I guess treating them as invalid and filtering out the points is the most straightforward solution (there is also [`Number.isFinite`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite) in some browsers).

**Comment by sebastianbochan** [comment]
@TorsteinHonsi maybe we should also add the support for NaN as string?
