### ISSUE TITLE
Problems with panning on iOS 8.1

### ISSUE THREAD

**Issue by Keksov** [highcharts/highcharts#3581]
Consider the following setup (http://jsfiddle.net/trfdp7hq/) -

> ```
>    chart : {
>        pinchType : 'x'
>        , zoomType : ''
>        , panning : true
>    } 
> ```
1. Panning works, but every move (touch the graph by one finger and drag it to the left or right) changes zoom level - "Reset zoom" button appears on the chart and it causes some mess with extremes min-max values. The other problem is that you may touch and drag the graph past the available data range - it breaks extremes min-max too. In contrast on PC it's not possible to click and drag the graph to the left out of data range, so "Reset zoom" button never appears if zoomType = ''
2. If we change our setup like pinchType : '' then panning stops working at all. Even navigator's slider window can't be dragged - you may move it only by clicking on some other point along x-axis

Similar bugs: #2555, #2903,

**Comment by spyro92** [comment]
Any updates on this issue?

Panning still seems to be broken - using an iPhone 6 Plus on iOS 9.0.2

**Comment by sebastianbochan** [comment]
+1 
Extra demo: http://jsfiddle.net/bpy0xfd9/1/

iOS 9.0.1

**Comment by tienuit** [comment]
open highcharts.src.js and edit:
```
// Zoom status
this.zoomX = zoomX = /x/.test(zoomType);
this.zoomY = zoomY = /y/.test(zoomType);
this.zoomHor = (zoomX && !inverted) || (zoomY && inverted);
this.zoomVert = (zoomY && !inverted) || (zoomX && inverted);
this.panHor = chartOptions.panning; //add this line
this.hasZoom = zoomX || zoomY;
```

```
pinchTranslate: function (pinchDown, touches, transform, selectionMarker, clip, lastValidTouch) {
            if (this.zoomHor || this.pinchHor || this.panHor) { //edit this line
                this.pinchTranslateDirection(true, pinchDown, touches, transform, selectionMarker, clip, lastValidTouch);
            }
            if (this.zoomVert || this.pinchVert) {
                this.pinchTranslateDirection(false, pinchDown, touches, transform, selectionMarker, clip, lastValidTouch);
            }
        },
```
And panning will work, no need  pinchType, zoomType on chart options

**Comment by ashish-developer-php** [comment]
Any update on this issue?

Panning still not working. I tried @tienuit solution as well but it's not working.

**Comment by TorsteinHonsi** [comment]
It seems to be working correctly to me. In order to enable single-finger panning, you need to set `tooltip.followTouchMove` to false as documented in [chart.panning](http://api.highcharts.com/highcharts/chart.panning).

**Comment by ashish-developer-php** [comment]
@TorsteinHonsi  Unfortunately it's not working. I don't want zoom functionality. It should pan in mobile devices same way it does on dekstop browsers. 
Please take a look at the fiddle to see output -
https://jsfiddle.net/Ashish_developer/c1ec6tf0/1/show/

Code location -
https://jsfiddle.net/Ashish_developer/c1ec6tf0/1/

It's working fine on desktop browsers. Is there any way to have same behavior on mobile phones.

**Comment by anupai** [comment]
i'm also facing the same issue. I need only panning and no zooming. 
chart options which i'm using is 
`pinchType: 'none',
				panning: true,
				resetZoomButton: {
					theme: {
						display: 'none'
					}
				}`

Its working fine in desktop but its not working in mobile phones. Please suggest how to fix this issue.

**Comment by pawelfus** [comment]
It looks broken when `zoomType` is not set. As long as user first zooms in, then swipes to pan, it works fine:

- almost fine: http://jsfiddle.net/xbedrpts/1/
- broken: http://jsfiddle.net/xbedrpts/
