### ISSUE TITLE
API request: errors as events

### ISSUE THREAD

**Issue by dlopuch** [highcharts/highcharts#3590]
Currently if Highcharts encounters an error, it throws an exception with a message like: `Uncaught Highcharts error #19: www.highcharts.com/errors/19`

The only way to react to these afaik is by wrapping your Highcharts constructor in a try/catch.  This poses some problems:
- try/catch blocks are generally not optimizable by the browser engine.  For example, it's a known [performance killer in V8](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#2-unsupported-syntax). Charts that may sometimes produce error 19, for example, you would want as many optimizations to trigger as possible.
- duplication of error handlers.  Need to include same error handlers in constructor AND on things like data series updates
- clunky pattern... javascript generally favors callback approaches.  For example, not clear where to put the try/catch if the error happens as a result of an asynchronous event.

For these reasons, an "error" event would be quite useful.  Highcharts can always fall back to throwing the error if no callback passed/bound.

**Comment by Izothep** [comment]
+1

**Comment by alecsGarza** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Thanks for your patience! 

Since HC5 this is much easier, but we took a slightly different approach than adding an event. Instead, you can set your error handler directly on the `Highcharts` object. See demo: http://jsfiddle.net/highcharts/e67jb9tu/.

**Comment by julsbreakdown** [comment]
@TorsteinHonsi 
In the case of multiple charts, how would you access the actual chart that is causing the error?
Thank you

**Comment by ppotaczek** [comment]
Hi @julsbreakdown,

Unfortunately, we do not have access to the chart that is causing the error in `Highcharts.error` method. For now you can only use `Highcharts.charts`. We plan to expand the functionality of `error` method and add the context for most errors in Highcharts 7.0: 

https://www.highcharts.com/documentation/roadmap

**Comment by KacperMadej** [comment]
The feature is added to Highcharts version 7.0.0, but API docs are not complete - https://api.highcharts.com/class-reference/Highcharts#.error doesn't cover third argument @ppotaczek
