### ISSUE TITLE
How to handle data gaps in StockChart

### ISSUE THREAD

**Issue by lienbcn** [highcharts/highcharts#3591]
http://jsfiddle.net/wz9tprfm/2/

The problem I have is that the data gaps are not filled with anything and it jumps directly from one side to the other, even though the gap covers a lot of time. Is it possible to join the gaps with either a line or an empty section in order to keep the x (time) axis with the same lineal scale during all the chart?

Thanks

**Comment by dandv** [comment]
Typos in the support page, "our support engineer monitor the forum"

**Comment by sebastianbochan** [comment]
Hi @dandv,
Thank you for reporting.
It looks like a jsfiddle issue, fixed demo: http://jsfiddle.net/BlackLabel/3dcr51ko/
