### ISSUE TITLE
Highstock: when showing series with visible: false - range selectors are not visible

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#3592]
In Highstock:

I have series that has visible set to false.
jsFiddle: http://jsfiddle.net/4qm13gzt/3/
1. Click legend
2. No range seectors

Only after some manipulations (changing range through zoom or panning) range selectors are becoming visible.

**Comment by pawelfus** [comment]
Fixed since 2.1.8: http://jsfiddle.net/4qm13gzt/5/
