### ISSUE TITLE
highstock 4 doesn't redraw properly, if series-pane height grows

### ISSUE THREAD

**Issue by andruscha** [highcharts/highcharts#3595]
when several series are divided in more than one pane, highstock cannot redraw the whole series-line, if the pane height grows. The new area of that pane remains empty.

Please look at http://jsfiddle.net/Lytc3Lgt/7/ and hit the button 'resize panes' to see what i mean.

In highstock 3.xx everything went ok.

**Comment by pawelfus** [comment]
Works fine since 2.1.9: http://jsfiddle.net/Lytc3Lgt/10/
