### ISSUE TITLE
Map bubble with data labels wrong when scale changing by mouse wheel 

### ISSUE THREAD

**Issue by elpofigisto** [highcharts/highcharts#3599]
When I try to increase map scale using mouse wheel i get such map view:
In Chrome, Safari and IE10 map isn't updated properly, not all bubbles are loaded, only numbers, user can't move the map to the left sometimes
In Firefox one move of mouse wheel results in blank area insted of the map, though '+' and '-' buttons work fine.
Screenshot on dropbox: https://www.dropbox.com/s/s34dn2c3eha18wg/Screenshot%20from%202014-11-19%2016%3A43%3A10.png?dl=0

**Comment by jon-a-nygaard** [comment]
Closing this issue since we are not able reproduce it, and it has become inactive for a long time. Should anyone have any information about this issue, please comment and/or reopen.
