### ISSUE TITLE
Tooltip's background is not applied.

### ISSUE THREAD

**Issue by ipreachable** [highcharts/highcharts#3605]
Set tooltip.followPointer.true, and xaxis.labels.useHtml true.
Then xaxis labels are displayed on top of the tooltip.

See: 
http://jsfiddle.net/tbsnqjdg/2/

![screenshot from 2014-11-21 11 22 34](https://cloud.githubusercontent.com/assets/1289958/5136743/da7a084e-7170-11e4-90b5-166064013d7b.png)

P.S. 
Please do not say set useHtml false :) #3596

**Comment by marcalj** [comment]
This problem doesn't appear on pie charts with HTML on data labels... :S

**Comment by pawelfus** [comment]
I think it does, see: http://jsfiddle.net/tbsnqjdg/6/
