### ISSUE TITLE
dataLabels is offset when verticalAlign is bottom or middle

### ISSUE THREAD

**Issue by hotienvu** [highcharts/highcharts#3606]
http://jsfiddle.net/0Lueanqw/

There seems to be a problem when initialising the DOM elements. The replicated element and actual element are not in the same position. This results in the wrong BBox height and the label is shifted
up quite a bit.
To see the problem, set a breakpoint in updateBoxSize in highstock.js

**Comment by pawelfus** [comment]
Isn't this caused by padding? When setting `dataLabels.padding = 0` dataLabel should touch the marker (http://jsfiddle.net/0Lueanqw/6/). Or maybe it is connected to the browser and OS?

**Comment by jon-a-nygaard** [comment]
Closing this issue due to it is pending a reply, and it is considered inactive. If anyone should have any further information, please comment and/or reopen.
