### ISSUE TITLE
Column range, with negative color applied only on the negative part of a bar

### ISSUE THREAD

**Issue by bitliner** [highcharts/highcharts#3609]
Is it possible to have a columnrange chart, with negativeColor property, such that a bar that has a negative and positive part can have 2 colors: one for the positive part of the bars, the other one for the negative part of the bars (negativeColor)

**Comment by pawelfus** [comment]
For a standard column-type that would be useful too, for example using `zones` feature:

- http://jsfiddle.net/8es33s68/
