### ISSUE TITLE
undocumented plotOptions.column.states.select

### ISSUE THREAD

**Issue by jehiah** [highcharts/highcharts#3611]
`plotOptions.column.states.select` is currently undocumented (I would expect documentation [here](http://api.highcharts.com/highcharts#plotOptions.column.states.select) but only `hover` state for columns is documented), yet it appears to be the only way to style the selected state when `plotOptions.column.allowPointSelect` is set to `true`.

http://jsfiddle.net/mj723fp1/ shows that this parameter does in fact work for styling selected state.

I was tipped off to this via http://stackoverflow.com/questions/14604571/highchart-set-fill-color

**Comment by KacperMadej** [comment]
+1
