### ISSUE TITLE
Highcharts tooltip  hidden delay when useHTML is true

### ISSUE THREAD

**Issue by natee** [highcharts/highcharts#3612]
When the 'useHTML' in 'tooltip' was set to 'true',the tooltip border(svg path) disappears a little faster than the inner text.

example:http://jsfiddle.net/tb26383y/

In source code line 8018,you use fadeOut(),so it will delay the tooltip's hide behavior.When I change it to fadeOut(10),it will be ok.

```js
this.hideTimer = setTimeout(function () {
    tooltip.label.fadeOut();
    tooltip.isHidden = true;
}, pick(delay, this.options.hideDelay, 500));
```

**Comment by pawelfus** [comment]
Works fine since 4.2.0: http://jsfiddle.net/tb26383y/8/
