### ISSUE TITLE
Polar chart - cropped labels

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3614]
Example: http://jsfiddle.net/7s9teo9o/6/

When `staggerLines` is set, `xAxis.labels` are cropped. Workaround is to remove `staggerLines` or set width for labels directly. However, the best solution is to provide logic similar to pie chart - where plotting area is decreased to fit dataLabels.

**Comment by sebastianbochan** [comment]
Fixed since 4.1.0
