### ISSUE TITLE
category null breaks tooltip

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#3615]
When setting a category to null, the tooltip is renderered incorrectly:
http://jsfiddle.net/stephanevanraes/eje34nhc/

related, directly on the renderer itself: http://jsfiddle.net/highcharts/8N3Sz/15/

**Comment by pawelfus** [comment]
I assume it works fine (at the second demo).

**Comment by khlieng** [comment]
Fixed since 5.0.10.
