### ISSUE TITLE
Release to NPM

### ISSUE THREAD

**Issue by kimmobrunfeldt** [highcharts/highcharts#3616]
Release Highcharts to NPM so that it can be used with Browserify.

There is already a third party project which does this: https://github.com/soldair/highcharts-browserify but it is up to the third party developer to update the Highchart release in their repo

**Comment by lee-40square** [comment]
+1 We're building a big aviation management ERP system and every single package we need is handled through NPM except this one. Would really appreciate it. Also, since it's already on Bower should be a quick issue to resolve. ;-)

**Comment by aldendaniels** [comment]
+1

**Comment by stevewillard** [comment]
+1

**Comment by highslide-software** [comment]
The Highcharts-realease repo is not registered at NPM. See https://www.npmjs.com/package/highcharts-release.

**Comment by aldendaniels** [comment]
> The Highcharts-realease repo is **not** registered at NPM

Typo?

> https://www.npmjs.com/package/highcharts-release

Looks great! Will new versions be regularly published going forwards?

**Comment by highslide-software** [comment]
Sorry, I meant to say __now__.

Yes, it will be updated.

**Comment by aldendaniels** [comment]
@highslide-software - thanks!

So I just gave this a try. Two issues - maybe I'm missing something?
 1. Looks like the built files don't define exports?
 2. An attempt to load a minimal example via Browserify fails. 

Minimal example code:
```javascript
var Highcharts = require('highcharts-release/highcharts.src');
console.log(Highcharts);
```

Resulting Error:

![screen shot 2015-05-18 at 1 41 19 pm](https://cloud.githubusercontent.com/assets/4658558/7680122/af0674a2-fd63-11e4-95aa-f6a6e163210d.png)


![screen shot 2015-05-18 at 1 41 33 pm](https://cloud.githubusercontent.com/assets/4658558/7680124/b271504e-fd63-11e4-8554-957aaed18026.png)

**Comment by highslide-software** [comment]
Highcharts is not yet AMD compatible, but we're working on it for the next release.

@jon-a-nygaard Can you have a look at the possibility of adding module exports on top of the existing Highcharts code? Also, the error message above probably comes from the missing adapter, so we should require the standalone adapter unless jQuery is defined.

**Comment by aldendaniels** [comment]
@highslide-software - The original issue was 

> Release Highcharts to NPM so that it can be used with Browserify

For this use-case, [CommonJS](https://github.com/highslide-software/highcharts.com/issues/3616#issuecomment-103021323) exports - not AMD - is what's needed. I'd suggest leaving this issue open until CommonJS exports are added, as pushing the repo to NPM without exports doesn't accomplish this goal.

And one more suggestion - it's recommended to define a [main script](https://docs.npmjs.com/files/package.json#main) in `package.json`.

**Comment by stevewillard** [comment]
Also, I noticed that this does not include Highstocks. Is there any chance it could be added to this package, or maybe a highstocks-release NPM package as well?

**Comment by highslide-software** [comment]
@stevewillard I tried to publish the highstock-release repo to NPM as well, but the name is already taken. We'll contact the owner.

**Comment by jon-a-nygaard** [comment]
One possible solution to use Highcharts with Browserify is the following:
```javascript
var jQuery = window.jQuery = require("jQuery"); // Adds jQuery onto window so that Highcharts can pick it up

require("highcharts-release/highcharts"); // Adds standard Highcharts to the window
require("highcharts-release/highcharts-more"); // Adds more functionality
require("highcharts-release/highcharts-3d"); // Adds 3D functionality

jQuery(function () {
    jQuery("#container").highcharts({
        // Your chart options
    });
});
```

**Comment by dylang** [comment]
@highslide-software When package names are taken the npm team recommends emailing email the author and cc support@npmjs.com. The npm team is very responsive and cooperative.

More info: https://www.npmjs.com/policies/disputes

**Comment by highslide-software** [comment]
Thanks @dylandg. I sent an email to the owner two days ago, and sent another one now with a copy to NPM.

**Comment by highslide-software** [comment]
... and now the `highstock-release` repo is ours!

**Comment by ConAntonakos** [comment]
Fantastic news. Thank you, Torstein!

**Comment by stevewillard** [comment]
Would like to echo what @aldendaniels said: Would it be possible to add CommonJS support/exports to highcharts-release/highstock/release? I'm trying to load Highstocks with Webpack, but because the highstock.js does not export the Highcharts variable, it doesn't seem to work, and I'm not sure exactly what else is needed.

Currently I'm relying on https://github.com/crealogix/highcharts-commonjs but:
1. This is an old version
2. It does not include Highstocks

Any help loading Highstocks via Webpack would be greatly appreciated.

**Comment by highslide-software** [comment]
@jon-a-nygaard Would it help if we simply append this to the `highstock.js` file? Something like this: 
```js
if (typeof module === 'object') {
   module.exports = Highcharts;
}
```

**Comment by jon-a-nygaard** [comment]
@highslide-software Yes that would be sufficient, but jQuery also checks if module.exports is an object, like this:
```javascript
if ( typeof module === "object" && typeof module.exports === "object" )
```

**Comment by highslide-software** [comment]
Implementation plan for CommonJS support (edit if necessary)
* Add module exports like above.
* Throw an error (readable in the console) if none of jQuery or the Standalone Framework are not loaded. This error must first be implemented in the core (see http://jsfiddle.net/highcharts/c4fz4vno/ that doesn't give a good explanation today), then the Highcharts.error method must be hijacked to print readable descriptions to the NPM user.

**Comment by stevewillard** [comment]
Awesome -- that would be amazing. Also, not sure if it helps, but the highcharts-commonjs repo above contains a diff of the changes the author made:

https://github.com/crealogix/highcharts-commonjs/blob/master/src/highcharts.src.js.diff

Might be helpful to identify what needs to be added.

**Comment by aldendaniels** [comment]
@highslide-software - Requiring that jQuery or the Standalone Framework be defined on `window` isn't ideal for NPM users. 

As I understand it, you'd Ideally publish multiple packages to NPM:

```
highcharts-release-core
higcharts-release
 |_ highcharts-release-core
highcharts-release-jquery (includes jQuery adapter)
 |_ highcharts-release-core
 |_ jquery
highcharts-release-mootools (includes Mootools adapter)
 |_ highcharts-release-core
 |_ mootools
```

Where dependencies are declared using [peerDependencies](https://docs.npmjs.com/files/package.json#peerdependencies).

This way if I include `higcharts-release-jquery` and some library I'm using needs `highcharts-release`, things should work seamlessly as both will get the same copy of `highcharts-release-core`.

Thoughts?

**Comment by aldendaniels** [comment]
Any news on this?

**Comment by stevewillard** [comment]
I was able to work around this issue by installing "highstock-release": "2.1.7" through NPM and then using "exports-loader" through Webpack.

I have an a few Webpack aliases:
```
"highcharts" : "highstock-release/highstock.src.js",
"highcharts-more" : "highstock-release/highcharts-more.src.js",
```

And finally the require in my modules looks like this:
```
var Highcharts = require("exports?Highcharts!highcharts");
```

Not ideal, but it's been working well so far.

**Comment by aldendaniels** [comment]
@stevewillard - Thanks! This work-around is working for me

**Comment by tomkur** [comment]
:+1:

**Comment by megapctr** [comment]
+1 :disappointed:

**Comment by highslide-software** [comment]
Some news regarding this issue. We are currently working on preparing Highcharts for loading with npm and use with browserify. We have eliminated global variables (`window`, `document`), and supply the adapter as a parameter. So far it looks like we are heading for something like this:

#### Install when jQuery is available globally
```js
// Load Highcharts
var highcharts = require("highcharts-release");

// Load a module or theme
require("highcharts-release/modules/exporting")(highcharts);
```

#### Install with no dependencies
```js
// Load the framework and Highcharts. Framework is passed as a parameter.
var hcFramework = require("highcharts-release/adapters/standalone-framework"),
    highcharts = require("highcharts-release")(hcFramework);

// Load a module or theme
require("highcharts-release/modules/exporting")();
```

What do you think of this structure?

**Comment by megapctr** [comment]
Looks neat! For jQuery plugin, I would love to see something similar to what [perfectScrollbar](https://github.com/noraesae/perfect-scrollbar) does:

```
var $ = require('jquery');
require('perfect-scrollbar/jquery')($);  // Initialize $.perfectScrollbar
```

**Comment by highslide-software** [comment]
@megapctr Good point, then we won't have to rely on jQuery being set globally.

**Comment by TorsteinHonsi** [comment]
Now available on https://www.npmjs.com/package/highcharts

**Comment by ragefuljoe** [comment]
can someone provide example of loading highcharts + exporting.js with webpack? I'm trying to do this but Highcharts is still not found.

`import hcFramework from 'highcharts-release/adapters/standalone-framework';
import Highcharts from "highcharts-release/highcharts";`

**Comment by TorsteinHonsi** [comment]
See http://www.highcharts.com/component/content/article/2-news/188-highcharts-optimized-for-npm, there's a webpack example.
