### ISSUE TITLE
"spline" chart rotated: tooltip not displayed correctly

### ISSUE THREAD

**Issue by zalby88** [highcharts/highcharts#3617]
Dear support,

I have to rotate the chart container using these CSS commands: "transform: rotate(90deg);", "-webkit-transform: rotate(90deg);" (Chrome) or "-moz-transform: rotate(90deg);" (Firefox). When I do this with a "spline" chart, the chart is correctly displayed, but the tooltip click and hover doesn't work properly anymore: by clicking some values, others become selected.

Below you can find some JSFiddle examples (basically variations of the original demos on the official website):

[Firefox]
http://jsfiddle.net/zalby88/612vw2ja/1/ 

[Chrome]
http://jsfiddle.net/zalby88/8bfwugr3/

[General]
http://jsfiddle.net/zalby88/2r5kgkcy/

Thank you in advance.

Kind Regards,
Alberto Lazzarin

**Comment by pawelfus** [comment]
Additional demo: https://jsfiddle.net/zzytest/pazLhv91/4 (click callback is not fired in most cases).
