### ISSUE TITLE
Bubble zThreshold depends on largest z value

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3619]
Lets compare two examples: 
- http://jsfiddle.net/psbtd6bL/1/
- http://jsfiddle.net/psbtd6bL/2/

**Comment by KacperMadej** [comment]
Resolved since version 4.1.8: http://jsfiddle.net/BlackLabel/psbtd6bL/3/
Working fine in the current (6.0.3) version: http://jsfiddle.net/BlackLabel/psbtd6bL/4/
