### ISSUE TITLE
addSeries does not affect output of Chart.options

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#3628]
addSeries does not affect options structure for the chart (output of Chatr.options) 
(but addAxis will change chart's options)

Example: http://jsfiddle.net/y90zta5f/1/
Steps:
- click "Add seris"
- click second button
  Series in options is not updated.

**Comment by pawelfus** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Note that in Highcharts 5, there is a `legend.update` method. In addition, you can call `chart.update({ legend: { enabled: false }});` and similar for all option sets.

There is, in general, some discrepancies today on how the current options are stored. We could need a `Chart.getCurrentOptions` function, similar to what we are doing in the export server today. Maybe we should just refactor and expose it from there. On the other hand, we might not need it with HC5.
