### ISSUE TITLE
tooltip shows for columns that are hidden due to axis minimum

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#3630]
http://jsfiddle.net/stephanevanraes/xuso3w99/2/

When setting a minimum on the y-axis, some columns are hidden but still show their tooltip because the column will be rendered with a height expanding down from the minimum (as if it as a threshold)

This is caused by the getThreshold function  in Axis

**Comment by pawelfus** [comment]
Closing as demo doesn't work and user deleted the account. If someone has reliable step, please reopen ticket.
