### ISSUE TITLE
switchRowsAndColumns - chart does not render or series names do not get mapped

### ISSUE THREAD

**Issue by razem-io** [highcharts/highcharts#3642]
Hello,

I have the following issue. When I use the option `switchRowsAndColumns : true` my chart does not show up anymore. I then added the following option `startColumn : 1` and the chart is rendered again. However I loose the series names and they get replaced by the default ones. Is this kind of behaviour expected? I am very new to highcharts perhaps I am missing something.

I added an example to jsfiddle which reproduces my issue:
http://jsfiddle.net/gdkmnw0b/ 

Thank you for any help regarding this topic!

**Comment by KacperMadej** [comment]
Resolved since version 4.1.0: http://jsfiddle.net/BlackLabel/gdkmnw0b/1/
Working fine when using current (6.0.3) version: http://jsfiddle.net/BlackLabel/gdkmnw0b/2/
