### ISSUE TITLE
Chart breaks across page with absolute position

### ISSUE THREAD

**Issue by tollus** [highcharts/highcharts#3646]
Hi,

I'm trying to create a printable version of a report which includes some highcharts charts. When a chart is cut between pages it seems it tries to display the chart on the next page instead of the start of the div on the previous page.  There's a screenshot below, since I'm not sure how to explain it.

Here's the js fiddle: http://jsfiddle.net/LLExL/3769/ (though with the framing on jsfiddle, even on the view only page, you'll need to cut out the code yourself into a blank page and print from there, otherwise jsfiddle messes with the printing)

I've tested in Google Chrome 39.0.2171.71. (Mac)

And the screenshot of the print:
![image](https://cloud.githubusercontent.com/assets/1820386/5378537/ce1398c6-8058-11e4-8af5-2fe25342d1e4.png)

Is there a workaround? Is this an error on Chrome or something in highcharts?

In Firefox, it seems to print "fine", though the chart at the bottom seems to be missing about half the chart.
![image](https://cloud.githubusercontent.com/assets/1820386/5378600/3f9aa07a-8059-11e4-904f-9c7c7e400b6c.png)

Thanks!

**Comment by KacperMadej** [comment]
We are trying to keep GitHub issue only for bugs, so for technical support questions, please use any other support channel: https://www.highcharts.com/support
