### ISSUE TITLE
Stacked bar - reversedStacks - prints minPointLength

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3651]
As in the topic, when we set reversedStacks i.e as false, then minPointLength is triggered.

Example: http://jsfiddle.net/7hka75vw/3/

**Comment by KacperMadej** [comment]
Resolved since version 4.2.4: http://jsfiddle.net/BlackLabel/7hka75vw/5/
Working in the current (6.0.3): http://jsfiddle.net/BlackLabel/7hka75vw/6/
