### ISSUE TITLE
HighMap and HighStock 2.0.4 is not working

### ISSUE THREAD

**Issue by espekkaya** [highcharts/highcharts#3656]
When adding highstock and highmap js file into same page, it was broken.

I wanted to use version of highstock 2.0.4

Here is js error : Uncaught TypeError: Cannot read property 'length' of undefined

see there : http://jsfiddle.net/WzVkV/82/

**Comment by QuentinFchx** [comment]
[highslide-software/highstock-release](https://github.com/highslide-software/highstock-release) has not been updated for 3 months.
As it contains a compatibility issues it would be nice if a release could occur...
@highslide-software Is it possible to bump the version ?
