### ISSUE TITLE
Datalabels - incorrect position, when all values are zero

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3658]
Lets compare two charts in the example
- http://jsfiddle.net/tytzxk47/

**Comment by Narasimha969** [comment]
In my project I have different kinds of charts. But I want to implement the above overwrite function for only stacked bar. How do I achieve it?

**Comment by pawelfus** [comment]
You can set on this one specific axis with stacked bars an option, for example: 

    yAxis: {
      myAlignment: true
    }

Then in wrap, check this param:

    Highcharts.wrap(Highcharts.Axis.prototype, 'setTickPositions', function(proceed, secondPass) {
      proceed.call(this, secondPass);
      if (this.tickPositions.length === 1 && this.options.myAlignment) {
        this.min = 0;
        this.max *= 2;
      }
    });
