### ISSUE TITLE
followTouchMove/zoomType/pinchType in HighStock (with possible fixes)

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#3666]
(only tested on iOS 8)

I think the first issue is that HighStock pans the chart when pinching with 1 finger, even if panning is disabled:
http://jiolo.be/pinch-1.html (no jsfiddle as I can't properly reproduce it there)
the StockChart (upper chart) moves as if it is panning
the Chart (lower chart) doesn't move as expected

Fixed this by wrapping `self.scaleGroups(transform, clip);` (at the bottom of highstock's `Pointer.prototype.pinch`) inside `if(2 === touchesLength){}`, but I don't know if this is the correct way. Also I set `pinchType: ''`, why is `'x'` the default in HighStock?
fixed demo: http://jiolo.be/pinch-1-fix.html

Now `followTouchMove` works, but not if `zoomType` is set
http://jiolo.be/pinch-2.html

Fixed this by changing `this.hasZoom = this.hasZoom || this.pinchHor || this.pinchVert;` to `this.hasZoom = this.pinchHor || this.pinchVert;` in `wrap(Pointer.prototype, 'init',...` (somewhere at the bottom of highstock.js). I think the correct approach would be to have a `hasPinch` and check that  instead of `hasZoom` in pinch operations.
fixed demo:  http://jiolo.be/pinch-2-fix.html

The following issues might be related:
#3581 (and its related issues)
#3450

**Comment by gregjacobs** [comment]
+1
