### ISSUE TITLE
tooltip doesn't hide on touch device

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#3667]
http://www.highcharts.com/demo
I think this is not a feature and that `hideDelay` should be respected on touch devices as well.

**Comment by KacperMadej** [comment]
[API reference](https://api.highcharts.com/highcharts/tooltip.hideDelay) says:

> The number of milliseconds to wait until the tooltip is hidden when **mouse out** from a point or chart.

So this works as documented. If you would like to suggest an enhancement idea then please use [UserVoice](https://highcharts.uservoice.com/forums/55896-general) - the most popular ideas are getting implemented.
