### ISSUE TITLE
Chart.redraw() in drillup event on grouped and stacked bar chart throws error

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#3671]
Chart.redraw() in drillup event on grouped and stacked bar chart throws error

jsFiddle: http://jsfiddle.net/cquc4xzL/10/

A: (works in 5.0.12+)
1. Click green bar
2. Click '< Back to Things3'
3. Green bar is no longer long (however tooltip shows set value)

B: (works in 5.0.12+)
1. Rerun fiddle
2. Click blue or black bar
3. Click '< Back ...'
4. Green bar is no longer visible and chart throws error:
"Uncaught TypeError: Cannot read property '0' of undefined - highcharts.src.js:13154"

C: (doesn't work in 5.0.12+)
1. Rerun fiddle
2. Click blue or black bar
3. Click '< Back ...'
4. Click on any bar -> drilldown doesn't work

Same with github version of higcharts and drilldown module, and additionally colors of bars are changing after drillup - http://jsfiddle.net/cquc4xzL/11/

Possible workaround:
Turn off animation :( and put setSize in setTimeout - http://jsfiddle.net/cquc4xzL/9/

**Comment by pawelfus** [comment]
Works fine in 5.0.0: http://jsfiddle.net/8jbo172g/

**Comment by navido** [comment]
@pawelfus: for me it does not work in your example, when you try to click the bar instead of the xAxis label.

**Comment by pawelfus** [comment]
I tried again A and B scenarios and both looks fine. Are there other, necessary steps to reproduce the issue?

**Comment by navido** [comment]
The issue is, that in scenario A after the drillup no longer the bars are clickable for drilldown. just the label 
![gif](https://user-images.githubusercontent.com/10881929/28126462-d54f6452-6729-11e7-992e-5b7a307eb8c6.gif)

**Comment by pawelfus** [comment]
You are right, thank you! I will update the main ticket.
