### ISSUE TITLE
Navigation button text misaligned

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#3684]
+/- text on the zoom buttons is off by about 1 pixel to the right.
Centering algorithm might need a slight tweak to move the text "+" and "-" up one pixel and to the left one pixel.

Relevant part of highmaps.src.js:

```
    // Empirical values found by comparing font size and bounding box height.
    // Applies to the default font family. http://jsfiddle.net/highcharts/7xvn7/
    var lineHeight = fontSize < 24 ? fontSize + 4 : mathRound(fontSize * 1.2),
        baseline = mathRound(lineHeight * 0.8);

    return {
        h: lineHeight,
        b: baseline,
        f: fontSize
    };
```

**Comment by springjben** [comment]
Does this fix the zoom buttons being slightly too high?

**Comment by pawelfus** [comment]
Hi @springjben - could you post an example of the issue? Details (os and a browser) and a live demo (jsfiddle) would be great.

**Comment by sebastianbochan** [comment]
Closed due to inactivity.

Please reopen, when stable live demo will be available.
