### ISSUE TITLE
Bug: Lazy loading disables buttons if Navigator is disabled

### ISSUE THREAD

**Issue by DanielFragaBR** [highcharts/highcharts#3700]
I noticed that if I use lazy loading and disable Navigator at the same time, the range buttons will be disabled as users press them. Try to disable navigator here:

http://jsfiddle.net/jro8cgm5/

And press 1h, then 1day ;)

**Comment by tuankiet65** [comment]
I'm bumping this issue up as this bug is still there after over one year https://jsfiddle.net/jro8cgm5/1/

**Comment by oysteinmoseng** [comment]
Discussion continued on #5478.
