### ISSUE TITLE
Spider web - incorrect labels in IE9 with specific characters

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3704]
Lets compare:
- http://jsfiddle.net/ky79s2fj/10/ incorrect
- http://jsfiddle.net/ky79s2fj/9/ correct

IE (Version 9.0.8112.16421)

**Comment by highslide-software** [comment]
#### Workaround
In general, `useHTML` will fix bidi text problems. See [Internationalization](http://www.highcharts.com/docs/advanced-chart-features/internationalization) in our docs. See it [demonstrated in jsFiddle](http://jsfiddle.net/ky79s2fj/11/).
