### ISSUE TITLE
Multiple xAxis disappear on zoom and reset zoom

### ISSUE THREAD

**Issue by egig** [highcharts/highcharts#3716]
http://jsfiddle.net/hz0xkkr1/1

I need to create grouped xAxis label like described on my question: http://stackoverflow.com/questions/27857297/highcharts-custom-xaxis-label (if someone know the solution that would be great, I really apreciate that, but its not what I want to report now). Then probably I will just use what I created on the fiddle, but the second line is disapper when I zoom and reset zoom.

**Comment by pawelfus** [comment]
I think `linkedTo` option is what you rather should use. I guess that after zooming in/out chart checks out second xAxis for extremes, and finds out that none of series is connected to that axis (and no points to be displayed), so simply hide labels. So either use `linkedTo` option (http://jsfiddle.net/hz0xkkr1/3/) or just use `afterSetExtremes` and set new extremes for the second axis.
