### ISSUE TITLE
Scrolling bug when displaying only one category at a time

### ISSUE THREAD

**Issue by Sphinxxxx** [highcharts/highcharts#3718]
Let's say you have a column chart with a lot of dataseries, so you apply scrolling to display only one category at a time. Fiddle: http://jsfiddle.net/JE7C9/11/

Now if you try to scroll, you'll see that the scrollable area becomes *really* long, and it's impossible to find anything other than the first and last category.

**Comment by highslide-software** [comment]
Note: The scrollbar is a Highstock feature, so it is designed for scrolling datetime axes. That's probably why it fails at translating a categorized axis.

**Comment by stephanevanraes** [comment]
The problem with the very small handler in the scrollbar seems to be fixed in the latest master branch already. However, because of the nature of the categories scrolling to them looks strange.
In this fiddle you find a small piece of code that will allow you to scroll smoothly through the categories:
http://jsfiddle.net/stephanevanraes/JE7C9/12/

**Comment by Sphinxxxx** [comment]
Thanks! That latest version seems to fix much of the problem, and your code is a nice trick to know about.

However, I prefer continuous/"live" scrolling, so I removed your function at the top. Now there is another problem: If you start scrolling, you can't scroll as far as the last category (you'll only see half the bars there), and you can't scroll all the way back to the first one (you'll only see half the bars there as well):

http://jsfiddle.net/JE7C9/13/

Again, this is only a problem if you set min/max to only show one category at a time. Show two or more categories, and the problem goes away.

**Comment by pawelfus** [comment]
Works fine since 4.x: http://jsfiddle.net/JE7C9/14/
