### ISSUE TITLE
Highstock: setData in afterSetExtremes not working sometimes

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#3722]
Changing data in afterSetExtremes event is not triggered until third change of extremes.

http://jsfiddle.net/bq32a2fh/17/

1. Click any zoom button -> no data
2. Click any other zoom button -> still no data
3. Click any other zoom button -> finally data point is showing

**Comment by highslide-software** [comment]
But it seems you are adding the points outside the zoomed area? If I add a point on May 9th it is within the new zoomed range and it always shows: http://jsfiddle.net/highcharts/bq32a2fh/18/

**Comment by KacperMadej** [comment]
Yes, thank you - that was the problem here.
