### ISSUE TITLE
Tooltip.dateTimeLabelFormats without dataGrouping for millisecond

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3734]
Example: http://jsfiddle.net/qhgfpjqL/10/

As we can se, wrong `dateTimeLabelFormat` is used (year, instead of millisecond). Only happens in master branch (actual version: http://jsfiddle.net/qhgfpjqL/9/).

**Comment by highslide-software** [comment]
Seems to work well now, perhaps after today's fix for #3654. Agreed?

**Comment by pawelfus** [comment]
I don't think so, let's take a closer look:

        tooltip: {
            dateTimeLabelFormats: {
                millisecond:"MS: %A, %b %e, %H:%M:%S.%L",
                year:"YEAR: %A, %b %e, %H:%M:%S.%L"
            }
        },

Our data is ms-based so I would expect to see `MS:` in tooltip, meanwhile I get `YEAR:`. In actual, stable version, I can see `DG: MS:`, so it takes format from `dataGrouping.dateTimeLabelFormats` array, even when we have disabled dataGrouping.

**Comment by GeoffreyOfficial** [comment]
Hi, I am the author of the bug report on the forum ... I'm waiting for an answer, but didn't see one, so please, can you fix that issue ?
Geoffrey

**Comment by jon-a-nygaard** [comment]
This seems to be fixed in at least the current version 4.2.5. When I open this example http://jsfiddle.net/qhgfpjqL/10/ I get the millisecond format in the tooltip.

If this by any chance is incorrect, and the issue still exists, please comment and/or reopen.
