### ISSUE TITLE
hard to scroll when use zoom in or zoom out on mobile device.

### ISSUE THREAD

**Issue by xueqingxiao** [highcharts/highcharts#3738]
can any body kindly take a look.

**Comment by highslide-software** [comment]
Is this a bug report? In that case it needs to be more specific...

For general tech support, please see www.highcharts.com/support.

**Comment by xueqingxiao** [comment]
@highslide-software Yeah, it's a bug. it's not mobile friendly.

**Comment by jon-a-nygaard** [comment]
@xueqingxiao Please provide more information, and preferably a live demo so that we can understand the issue. Otherwise we can not help you.

**Comment by xueqingxiao** [comment]
@jon-a-nygaard Just close it, it was solved.
