### ISSUE TITLE
RangeSelector inputs MS format

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3739]
Example: http://jsfiddle.net/qhgfpjqL/14/

And image, for better description: 
![screen shot 2015-01-21 at 12 25 32 pm](https://cloud.githubusercontent.com/assets/1453926/5835423/af32a998-a168-11e4-9e17-01c7663a9914.png)

Of course there should be `01s000ms`.

**Comment by highslide-software** [comment]
This is not really a fix, but the last point in your demo had an x value of 999.9 milli seconds, hence the last value was rounded up. So it comes down to a problem of sub-millisecond date formatting. 

Broken down to `dateFormat`: http://jsfiddle.net/highcharts/qhgfpjqL/16/

Add the last point and it looks better: http://jsfiddle.net/highcharts/qhgfpjqL/15/

**Comment by pawelfus** [comment]
Indeed, that's the real reason. Maybe `dateFormatter` should simply round values? There may be similar case when full date will be funny: http://jsfiddle.net/qhgfpjqL/20/ However, rounding doesn't sound like real solution. 

I'm not sure if we can force users to use only integer timestamps..

**Comment by highslide-software** [comment]
Yes, probably doing Math.round or parseInt on the incoming argument to dateFormatter would do it.

**Comment by KacperMadej** [comment]
If
`'L': pad(Math.round(timestamp % 1000), 3)`
could be replaced with
`'L': pad(Math.floor(timestamp % 1000), 3)`
then `%L` will display only full units (milliseconds) as any other date and time format.

This also allow resolving sub-millisecond precision with custom `Highcharts.dateFormats`.
Demo: http://jsfiddle.net/BlackLabel/qhgfpjqL/39/

**Comment by TorsteinHonsi** [comment]
Makes sense!
