### ISSUE TITLE
Export Fails on touch devices with zoom: 'xy' enabled

### ISSUE THREAD

**Issue by JeremyBYU** [highcharts/highcharts#3748]
Can not export with touch enabled zooming on mobile phone or tablet. Only tested with android devices (nexus 4 and nexus 7).  The desktop application works just fine however with a mouse.
The specific setting is
```
chart: {
        zoomType: "xy"
    },
```
It seems to me that the export menu overlaps the chart but only "zoom commands" are captured when trying to touch export options.

Here is the jsfiddle showing the issue.  This a direct fork of the official demo jsfiddle with only this zoom setting added (open link with phone or tablet and attempt to export):  
http://jsfiddle.net/o1xd5520/1/

**Comment by highslide-software** [comment]
What version of Android is this? I tested it on an Android Virtual Device version 4.1.2, but downloading to JPEG seems to work. It complains about an SD card missing, but that indicates that the actual download went well I guess.

Also tested on iOS without errors.

**Comment by sebastianbochan** [comment]
Tested on the mobile phone (Android 5.0.1), works properly.

**Comment by JeremyBYU** [comment]
Strange,  might be my something with my devices or jsfiddle.
I'm using android 5.02 (chrome as the browser). I'll try to dig into it more later.

Thanks

**Comment by jon-a-nygaard** [comment]
Closing this issue due to we are not able to reproduce it, and it has been inactive for a long time. Should anyone have further information on this issue, please add a comment and/or reopen.
