### ISSUE TITLE
Can't click/see tooltip on points behind other series area

### ISSUE THREAD

**Issue by mcr222** [highcharts/highcharts#3760]
http://jsfiddle.net/Ld7vxxns/3/
As you can see points of the blue line can't be selected, and neither the tooltip is shown.

I would suggest that even though points may be behind areas, they always become accessible. Like what can be achieved if you select the first point (which is partially outside the black area in my case) and you then go to other points on the same line. It can be seen that the point is selected although behind the black area. This would allow clicking on them even though they are behind the area.

**Comment by highslide-software** [comment]
Actually this will change with Highcharts 4.1, where the tooltip positioning is determined by a kd-tree nearest neighbour search. See http://jsfiddle.net/highcharts/Ld7vxxns/4/. 

@stephanevanraes FYI.

**Comment by mcr222** [comment]
It works well for the tooltip, thanks.
But still is impossible to click on those points behind: http://jsfiddle.net/Ld7vxxns/5/

**Comment by pawelfus** [comment]
As workaround (for SVG), you can set `pointer-events` in CSS: 

    .highcharts-series path { 
        pointer-events: visibleStroke; 
    }

[Demo](http://jsfiddle.net/Ld7vxxns/6/).
