### ISSUE TITLE
Chrome (40) rendering bug on line chart when using Highstocks 2.0.4

### ISSUE THREAD

**Issue by crzrcn** [highcharts/highcharts#3761]
Graphs occasionally render with random horizontal lines that do not map to the data. Zooming in and out of the graph makes it disappear.

Only happens in Chrome. Not even on Chromium. Still happens when layer squashing is disabled.

Is this the same bug as discussed in #3394, #3550?

![screen shot 2015-01-28 at 8 05 09 pm](https://cloud.githubusercontent.com/assets/1812608/5952315/42438c8c-a729-11e4-91bf-19e8d99e5276.png)
![screen shot 2015-01-28 at 8 05 23 pm](https://cloud.githubusercontent.com/assets/1812608/5952317/43ee5206-a729-11e4-8a21-ef1d9faa7b4b.png)

**Comment by KacperMadej** [comment]
Unable to recreate, please provide more info if you want this issue to be reopened.
