### ISSUE TITLE
Highmaps zoom-in not working when coordinates are small values

### ISSUE THREAD

**Issue by rococtz** [highcharts/highcharts#3762]
**Issue:**
Zooming in not working for custom shapes with small value coordinates.

**Steps:**
1. Go to this JSFiddle: http://jsfiddle.net/hz34r530/
2. Try to zoom in; it's not working even though map navigation is enabled.

**Possible workaround:**
Increase the value of the coordinates and it will work. For e.g: if coordinates are 0.5, increase them to 5000 as per this JSFiddle where zoom-in is working: http://jsfiddle.net/hz34r530/

**Comment by pawelfus** [comment]
It looks like problem with `Axis.minRange` option. Easier workaround is to set minRanges: http://jsfiddle.net/hz34r530/5/

**Comment by rococtz** [comment]
Great workaround, thanks!
