### ISSUE TITLE
Upon series update index option is deleted/reset

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#3768]
Upon series update index option is deleted/reset

fiddle: http://jsfiddle.net/m5drpdfg/

**Comment by polarathene** [comment]
Why are you setting indexes like that? If you set index provide proper order from 0? Try not setting indexes at all if you don't need to control order.
http://jsfiddle.net/m5drpdfg/2

Refer to demo: http://jsfiddle.net/o4u985Lh/
