### ISSUE TITLE
Zooming issue in Waterfall chart

### ISSUE THREAD

**Issue by ajitkamathge** [highcharts/highcharts#3772]
The bars on Waterfall chart disappear on zooming (sometimes on first zoom). 
Following is the fiddle for the same:
http://jsfiddle.net/5a89kg6c/

Attached below screenshots for the same.

![chart_onload](https://cloud.githubusercontent.com/assets/10776605/5981579/1ef24bb8-a870-11e4-9728-be9591b9eecb.jpg)
![chart_zoom1_selectarea](https://cloud.githubusercontent.com/assets/10776605/5981580/22a29c18-a870-11e4-9783-998b369a43a1.jpg)
![chart_zoom2_selectarea](https://cloud.githubusercontent.com/assets/10776605/5981584/288e5540-a870-11e4-8098-ae776e6d5548.jpg)
![chart_zoom2_issue](https://cloud.githubusercontent.com/assets/10776605/5981587/2d911046-a870-11e4-9519-d1431de9cdbb.jpg)

**Comment by polarathene** [comment]
The bar still exists, it's just being resized/positioned incorrectly. To whomever looks into this bug, while you can pan along x, you cannot pan along y.

As a workaround, like with the scatter issue you're having, you can add to your yAxis settings `tickInterval:250000` Which sort of defeats the purpose of the zoom I guess, doesn't seem to break it. I tried a lower value of 50k and some zooms would break it still.

**Comment by sebastianbochan** [comment]
Fixed since HC v.4.2.7
