### ISSUE TITLE
Reversed yAxis and Candlestick 

### ISSUE THREAD

**Issue by maximenicot74** [highcharts/highcharts#3777]
I've just found a weird behavior when using Candlesticks type chart and reversed axis.
http://jsfiddle.net/2beba86d/

The line representing upper and lower shadow is drawn over the body while it should be beneath.

Thanks.

**Comment by pawelfus** [comment]
**Workaround:**
Swap `plotY` with `yBottom` before rendering points:

Demo: http://jsfiddle.net/j782t0rf/

Code:

    (function(H) {
      function swapPlot(point) {
        var temp = point.yBottom;

        point.yBottom = point.plotY;
        point.plotY = temp;
      }
      H.wrap(H.seriesTypes.candlestick.prototype, 'drawPoints', function(proceed) {
        if (this.yAxis.reversed) {
          H.each(this.points, swapPlot)
        }

        proceed.apply(this, Array.prototype.slice.call(arguments, 1));
      });
    })(Highcharts);

**Comment by maximenicot74** [comment]
Hi Pawelfus,

This method used to work until Highstock v5.0.10
From 5.0.11, and now with Highstock 6, candles don't render correctly.

Just follow your demo link from your answer - it uses the cdn version of highstock and the issue is visible on it.

Kind regards.

**Comment by pawelfus** [comment]
Hi @maximenicot74 

Thank you for the heads up!

```javascript
  (function(H) {
    function swapPlot(point) {
      var temp = point.yBottom;
      point.yBottom = point.plotHigh;
      point.plotHigh = temp;
    }
    H.wrap(H.seriesTypes.candlestick.prototype, 'drawPoints', function(proceed) {
      if (this.yAxis.reversed) {
        H.each(this.points, swapPlot)
      }

      proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    });
  })(Highcharts);
```

Demo: http://jsfiddle.net/BlackLabel/j782t0rf/24/

**Comment by maximenicot74** [comment]
Thanks @pawelfus for your fast answer.
Everything works great now.
