### ISSUE TITLE
Export chart in Android 4.4 stock browser not working 

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#3791]
This bug exists for a very long time and haven't been fixed yet. See also: https://code.google.com/p/android/issues/detail?id=1780

It has something to do with downloads which are not direct (which has a longer timespan) are being passed over to the android download manager. We find a lot of reports of things going wrong here.

**Comment by mdomnita** [comment]
Still have this problem in Android 4.4.2. with Highcharts JS v5.0.7
https://drive.google.com/file/d/0Bze0qDNAsVnodloxdzVTSEZ0Qmc/view?usp=sharing
It works in all browsers and in Chrome for Android but not in the stock browser. I keep getting an "Unsuccesful download" message.
