### ISSUE TITLE
Markers is not visible after sorting lines

### ISSUE THREAD

**Issue by kuflash** [highcharts/highcharts#3794]
If we have two types charts on one container (column and line), and will change z-order series, markers for line type is not visible. For example: [click here](http://jsfiddle.net/kuflash/xjgRY/9/). First click on the first button, and then the second. Markers with intersecting column is not visible.

**Comment by kuflash** [comment]
Solved the problem as follows: http://jsfiddle.net/kuflash/xjgRY/10/

**Comment by pawelfus** [comment]
I'm not sure if this is even a bug. Just markers are in a different group, so you need to mov ethat group to front too.

Instead of playing around with groups, you can update series `zIndex` options: http://jsfiddle.net/xjgRY/12/

Of course, `toFront()` method has much better performance.
