### ISSUE TITLE
Slow rendering(navigator, tooltip) with multiple series in zoom "All"

### ISSUE THREAD

**Issue by miladjafary** [highcharts/highcharts#3796]
Hi. 

In highstock zoom "All" , when you have more than 10 series , rendering of series, tooltip and navigator is too slow with a lag, specially in high resolution such as 1920*1080  or in any wide screen. 
Also tooltip container become long and it hidden in chart container.

See example in wide screen: 
http://jsfiddle.net/xj498cbz/
![untitled](https://cloud.githubusercontent.com/assets/2297968/6091110/75fe3f3e-aeb0-11e4-8870-068480e81ea3.png)

**Comment by Jmales** [comment]
Did you solve this?

**Comment by miladjafary** [comment]
No. I did not.
I only limit the  duration of chart insted of limiting series.

**Comment by pawelfus** [comment]
Hi @miladjafary  and @Jmales 

My apologies for not answering this ticket on time. If the performance is an issue, then I suggest to try boost module, please take a look: http://jsfiddle.net/xj498cbz/1/

Regarding tooltip, please check #5784 ticket.

**Comment by Jmales** [comment]
@pawelfus Ty for the answer. One question though: I'm using highcharts 5.0.9. Is boost.js already integrated or do I still need to manually import it?

**Comment by pawelfus** [comment]
Boost is a module, so you need to download and import it. Note: it's still in the beta so it has limitations (see comment in the file: http://code.highcharts.com/stock/5.0.9/modules/boost.src.js ).

**Comment by KacperMadej** [comment]
This issue doesn't look like a bug.
Performance tips could be found in here: https://www.highcharts.com/docs/getting-started/frequently-asked-questions#optimize-performance
