### ISSUE TITLE
When mapNavigation.enabled=true, Series.setData() messes up the zoom 

### ISSUE THREAD

**Issue by christophfranke** [highcharts/highcharts#3798]
When using setData and map navigation is enabled, the zoom gets messed up after setting the data, and often it is not possible to navigate the zoom center anymore after the update.
A reproduction can be found here: http://jsfiddle.net/ker8y3cg/
My current workaround can be found here: http://jsfiddle.net/hksh4nd7/

**Comment by KacperMadej** [comment]
Unable to recreate using version 6.1.4.
Closing as resolved.
