### ISSUE TITLE
3d scatter - data labels on right edge at some angles move unexpectedly

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#3808]
In 3d scatter dataLabels on right edge (x axis max) at some angles (alpha, beta) move unexpectedly out of its designated places. It looks like something is blocking them from going near bottom and right edge.
Example: http://jsfiddle.net/0fqmoqwa/

As a workaround you can set crop and overflow to false.
Example: http://jsfiddle.net/0fqmoqwa/1/

Maybe crop and overflow should be disabled for 3d ?

**Comment by toothbrush7777777** [comment]
Related: try changing the angle and moving the mouse around on https://jsfiddle.net/8ghqms11/1/. It seems to randomly select an item if you don't hover over one.

**Comment by KacperMadej** [comment]
Working fine when using Highcharts version 7.0.0.
Closing as resolved.
