### ISSUE TITLE
Inconsistent Usage of thousandsSep on yAxis Labels

### ISSUE THREAD

**Issue by wergeld** [highcharts/highcharts#3811]
Looking at the defaultLabelFormatter() in highcharts.src.js there is an issue where the thousandsSep character is not used unless the value for an axis with no metrix suffix is over 10000. If we add a thousandsSep to items that are over 1000 and with a suffix (k, M, G, etc) why not add it to axis label values the same way?
Code:

```
        if (ret === UNDEFINED) {
            if (mathAbs(value) >= 10000) { // add thousands separators
                ret = numberFormat(value, 0);

            } else { // small numbers
                ret = numberFormat(value, -1, UNDEFINED, ''); // #2466
            }
        }
```

Representative jsFiddle:
http://jsfiddle.net/se1k7L7j/

**Comment by highslide-software** [comment]
Because real-world cases show that numbers between 1000 and 10 000 in an axis typically deals with years. But there could probably be an option for it.

**Comment by wergeld** [comment]
Could this be an optional parameter? I had tried to over-ride the numeric formatting by using the yAxis.label but that also removes any scale suffix (g, k, M, etc):
```
labels: {
        formatter: function () {
            return Highcharts.numberFormat(this.value,0,'.',',');
        },
        style: {
            color: '#000080',
            fontSize: '9px',
            fontWeight: 'bold'
        }
    }
```

Additionally it looks like under latest 4.1 that the labels are now using a single space for thousands separator:
http://jsfiddle.net/se1k7L7j/1/

See the bottom yAxis.

**Comment by highslide-software** [comment]
> Additionally it looks like under latest 4.1 that the labels are now using a single space for thousands separator

Yes, that's a deliberate change because it is ISO standard, and is acceptable in both Anglo-American and continental European cultures.

**Comment by wergeld** [comment]
I talked with our BA and we would definitely like the ability to optionally set a thousandsSep and decimal point character.

**Comment by KacperMadej** [comment]
BTW: API looks incorrect - http://api.highcharts.com/highcharts#Highcharts.numberFormat.

In last dot:
"thousandsSep: String
The thousands separator. Defaults to "," or to the string specified globally in options.lang.thousandsSep."

There should be:
... Defaults to " " ...

**Comment by highslide-software** [comment]
> I talked with our BA and we would definitely like the ability to optionally set a thousandsSep and decimal point character.

Yes of course, this has always been optional through the lang object: http://api.highcharts.com/highcharts#lang.thousandsSep . The only thing that is new is the default value.

**Comment by wergeld** [comment]
> Yes of course, this has always been optional through the lang object: http://api.highcharts.com/highcharts#lang.thousandsSep . The only thing that is new is the default value.

Yes, we have applied this. Does not take affect on yAxis less than 10k values still. This is what we would like to make optional. See http://jsfiddle.net/se1k7L7j/2/.

**Comment by jodigiordano** [comment]
What's the status of this issue?
Is there a workaround to this problem with the new releases?
Thanks!

**Comment by TorsteinHonsi** [comment]
Yes, you can call the `defaultLabelFormatter` so that you don't have to do all the hard work, then only modify it for your special case: http://jsfiddle.net/highcharts/efg5sgxd/

**Comment by jodigiordano** [comment]
Thanks a lot for the reply and the fiddle, that's exactly what I was looking for. :+1:
