### ISSUE TITLE
Different gauge center for Windows 7 Firefox & Chrome with *some* plugin installed and without

### ISSUE THREAD

**Issue by jornvandebeek** [highcharts/highcharts#3829]
We are seeing a peculiar difference in the centering of the gauge datalabel between Firefox or Chrome under windows 7 with some undetermined plugin installed and without. The list of plugins in Chrome and Firefox is roughly:
Java
Office
Flash
Silverlight
Adobe PDF Reader
Lastpass Native Plugin

Both in Firefox and Chrome, individually disabling every plugin does not prevent the issue from appearing, yet the Firefox safe mode does prevent the issue from appearing. Chrome's `--disable-plugins` command line option however does not prevent the issue from appearing. A fresh Browserstack Chrome or Firefox on windows 7 does not show the issue.
- Under Windows 7 with
  - Firefox 35 with the plugins installed
  - Chrome with the plugins installed

Incorrect positioning:

![gauge_error](https://cloud.githubusercontent.com/assets/123905/6227281/de6c6af6-b69d-11e4-88ed-5a3721ec4e68.png)
- Under Windows 7 with
  - Firefox 35 with plugins in safe mode, Fresh Chrome or Firefox in a Browserstack session
- Under OSX
  - Firefox 35 or Chrome without plugins

Correct positioning:

![gauge_correct](https://cloud.githubusercontent.com/assets/123905/6227295/133f4730-b69e-11e4-8f63-fcb8e25a84e6.png)

I have created a [jsfiddle](http://jsfiddle.net/p43f0xag/) containing a copy the problematic chart. I hope that, as a workaround for our case, choosing a semi circle donut 'pie' chart will not reproduce the issue. 

```
{
    "chart": {
        "type": "solidgauge",
        "height": 175
    },
    "credits": {
        "enabled": false
    },
    "title": {
        "text": null
    },
    "pane": {
        "center": [
            "50%",
            "85%"
        ],
        "size": "100%",
        "startAngle": -90,
        "endAngle": 90,
        "background": {
            "backgroundColor": "#EEE",
            "innerRadius": "60%",
            "outerRadius": "100%",
            "shape": "arc"
        }
    },
    "yAxis": {
        "min": 0,
        "max": 100,
        "stops": [
            [
                1,
                "#BBBBBB"
            ]
        ],
        "lineWidth": 0,
        "minorTickInterval": null,
        "tickPixelInterval": 200,
        "tickWidth": 0,
        "title": {
            "y": -60,
            "text": "Overeenstemming <br/> <span style=\"color: #F04124\"> dag </span> met <span style=\"color: #028ebb\"> vorige dag </span>"
        },
        "labels": {
            "y": 10,
            "distance": -15
        }
    },
    "plotOptions": {
        "solidgauge": {
            "dataLabels": {
                "y": -25,
                "borderWidth": 0,
                "useHTML": true
            }
        }
    },
    "series": [
        {
            "name": "Overeenstemming",
            "data": [
                0
            ],
            "dataLabels": {
                "format": "<div style='text-align:center'><span style='font-size: 1.6em'>{y} %</span></br>geen/klein</div>"
            },
            "tooltip": {
                "valueSuffix": " %"
            }
        }
    ]
}
```

**Comment by KacperMadej** [comment]
Please try the code without the `y: -25` for dataLabels.
http://jsfiddle.net/p43f0xag/1/

I am unable to recreate the problem and the case is rather old, so please provide more info and a way to recreate the problem and the issue will be reopened.

**Comment by jornvandebeek** [comment]
Reproducing this issue was a long shot even when it first occurred. My hope was that someone would recognise the issue and could provide some guidance. The machines on which the issue occurred have been upgraded and the issue has not occurred since. Thank you for taking time to look at older issues.
