### ISSUE TITLE
Styles of an HTML xAxis label are not properly updated during a drilldown

### ISSUE THREAD

**Issue by wojcikstefan** [highcharts/highcharts#3849]
See: http://jsfiddle.net/pypaq94t/22/

After you drill down, you'll see that the xAxis labels are still bold and underlined, even though they're not drillable. The issue exists only for HTML labels, so I suspect that the `SVGElement#htmlCss` method doesn't clean up the styles properly.

Can you look into it?

**Comment by highslide-software** [comment]
The difference between SVG and HTML is that in SVG, we apply _all_ the styles, while in HTML, only the ones defined in the style option are reset.

The workaround is to explicitly define a font weight and text decoration for the labels: http://jsfiddle.net/highcharts/pypaq94t/26/

**Comment by wojcikstefan** [comment]
I'd argue that the experience should be consistent regardless of whether you're using SVG or HTML, but I can live with the workaround. Feel free to close this one.

**Comment by highslide-software** [comment]
Accidentally closed

**Comment by makeover** [comment]
I experience the same issue when using activeAxisLabelStyle and the workaround doesnt help.

**Comment by sebastianbochan** [comment]
Hi @makeover,
When I run the demo: http://jsfiddle.net/BlackLabel/7z4m36s1/ I was not able to reproduce the issue. Could you update my code with yours for the further debugging? Do you use the newest highcharts 6.1.1?

**Comment by makeover** [comment]
My project is using Highcharts 6.1.1. My other package "angular2-highcharts" did however depend on Highcharts 5. I've updated your example using my own data structure, but was not able to reproduce the behaviour with either version: http://jsfiddle.net/7z4m36s1/45/

**Comment by sebastianbochan** [comment]
For the further debugging we need to have isolated, simplified demo which will allow us replicate the issue.
