### ISSUE TITLE
CSV files are not being escaped properly.

### ISSUE THREAD

**Issue by workergnome** [highcharts/highcharts#3850]
CSV files that contain quoted strings are not being escaped—this means that quotation marks, line feeds, etc. within a cell don't work properly.  [RFC 4180](http://tools.ietf.org/html/rfc4180) is the (semi-official) standard for CSV files, and describes escaping.

See:
http://jsfiddle.net/wfcbhe7g/

**Comment by samwisehawkins** [comment]
I also have the same issue

**Comment by TorsteinHonsi** [comment]
The built-in CSV parser has its limitations. Here's how you can use an external parser like Papa Parse: http://jsfiddle.net/highcharts/u59176h4/

**Comment by samwisehawkins** [comment]
Thanks.

**Comment by TorsteinHonsi** [comment]
This is now working in the `csv-rewrite` branch: http://jsfiddle.net/highcharts/wfcbhe7g/4/

This branch basically adds more sophisticated CSV parsing to the data module, and will be merged into the master in Q2 2017.
