### ISSUE TITLE
xAxis.labels.maxStaggerLines is not working in 4.1.x

### ISSUE THREAD

**Issue by miyajan** [highcharts/highcharts#3853]
http://api.highcharts.com/highcharts#xAxis.labels.maxStaggerLines
There is described the default value is set to 5 and it works until 4.0.3. However, it is not working in 4.1.x. I need maxStaggerLines rather than autoRotation.

4.0.3
http://jsfiddle.net/6dws4pdr/

4.1.0
http://jsfiddle.net/xyz4kvpq/

**Comment by highslide-software** [comment]
The `maxStaggerLines` option is deprecated.

The rationale behind this decision is that auto rotation and label removing scales much better than stagger lines. Consider [this example](http://jsfiddle.net/highcharts/pnvwLux6/2/), and see how this was rendered in [the old version](http://jsfiddle.net/highcharts/pnvwLux6/3/).

And to avoid bloating Highcharts with lots of parallel functionality, we removed the logic behind maxStaggerLines. We may consider reimplementing it as a plugin though, if it is something that enough users ask for.

**Comment by BJTerry** [comment]
With maxStaggerLines not working, and autorotation not currently implemented, Highmaps currently has no good solution to the overlapping labels problem.

**Comment by linusrachlis** [comment]
May I suggest that, if a feature is removed, you use the word 'removed' rather than 'deprecated'? 'Deprecated' means it is available but discouraged, whereas this feature seems to be unavailable.

**Comment by KacperMadej** [comment]
To better track how many votes the enhancement idea has the issue was moved to userVoice:
https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/35658868-maxstaggerlines-reimplementing-it-as-a-plugin

When the idea will get more votes then it will be addressed properly and this issue might get reopened.
