### ISSUE TITLE
Line series are rendering incorrectly with multiple xAxis in 4.1.x

### ISSUE THREAD

**Issue by gtimti** [highcharts/highcharts#3854]
http://jsfiddle.net/djLopfan/1/

Using tickInterval in one of xAxis squeezes line series up to half of whole chart area.

**Comment by highslide-software** [comment]
We made changes in how axes are aligned with 4.1. Try using `xAxis.tickAmount` to control alignment.

**Comment by gtimti** [comment]
tickInterval definitely works well and tickAmount doesn't resolve the issue. The problem is line ends in the middle of chart. The previous version of highcharts (4.0.x) scales xAxis to align with last point value. 

Here is how it works in 4.0.x
http://jsfiddle.net/djLopfan/2/

**Comment by highslide-software** [comment]
Does `alignTicks: false` work for you? http://jsfiddle.net/highcharts/djLopfan/3/

**Comment by gtimti** [comment]
Works like a charm! Thank you a lot!

**Comment by stephanevanraes** [comment]
I think this should be considered a bug
4.1.x http://jsfiddle.net/7msn6gmx/1/

**Comment by gtimti** [comment]
As @highslide-software mentioned to align series with axis you should have `alignTicks: false` in chart config. Also it is  a well-documented option in http://api.highcharts.com/highcharts#chart.alignTicks

http://jsfiddle.net/7msn6gmx/2/

**Comment by jaypoulz** [comment]
I would like to add that having multiple x-axes causes strange behavior when setting extremes.
See here for an example: http://jsfiddle.net/jaypoulz/Ld2k9vmp/

The strange part is that it is still possible to manipulate the minimum, but the max gets locked in place, and will no longer respond to chart axis options like range.

While setting alignTicks to false does indeed solve all of these problems, I think it should be at least noted in the documentation for max, setExtremes, range, (and whatever else may be affected) that the default alignment of ticks may override these options for multiple axes.
