### ISSUE TITLE
Bubble datalabels inside - IE9

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3858]
Example: http://jsfiddle.net/b6xhmeju/3/

IE 9.0.8112.16421

![zrzut ekranu 2015-02-19 o 15 44 33](https://cloud.githubusercontent.com/assets/2115686/6268581/41cff34a-b84e-11e4-9509-d9a11a0d2aa8.png)

**Comment by KacperMadej** [comment]
Looks good in version 6.1.3

![3858](https://user-images.githubusercontent.com/8960408/45487876-e9f93680-b75f-11e8-859b-f5ab4554d614.png)
