### ISSUE TITLE
Bubble chart with logarithmic scales: not working

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#3861]
Example: http://jsfiddle.net/kk3mr1eo/1/

Another example can be demo with added logarithmic options.
http://jsfiddle.net/kk3mr1eo/

**Comment by fourmisz** [comment]
Me as well...

I think it is a bug in Bubble chart.

http://jsfiddle.net/Fusher/FtdYf/2/

In this example, it uses `tickPositions` property to display bubble chart correctly. 

I don't know why.

**Comment by highslide-software** [comment]
With the partial fix at least the bubbles show, but the padding isn't computed correctly. The workaround is to set the `minPadding` and `maxPadding` manually: http://jsfiddle.net/highcharts/kk3mr1eo/2/
