### ISSUE TITLE
Data Labels are not rendering for column charts when series are shown/hidden

### ISSUE THREAD

**Issue by Naros** [highcharts/highcharts#3866]
I have a chart where it has 2 series of data but the columns in the column chart are close enough together that the plotOptions.column.dataLabels.allowOverlap causes the second column for each x-axis category to not draw it's label.  The problem is when I hide Series1, the data labels that were hidden due to overlap = false for Series2 are not made visible.

When enabling/hiding series data and allowOverlap = false, data labels should be recalculated to determine whether they're visible or not so that when hiding series information, the rendered chart remains consist by showing labels that are possible.

**Comment by highslide-software** [comment]
Demo: http://jsfiddle.net/highcharts/bwx7bfj6/

**Comment by cosycode** [comment]
I have the impression, that this problem has been somehow reintroduced.

**Comment by cosycode** [comment]
The last unit test (that for now skips) fails: https://github.com/highcharts/highcharts/commit/ea8a11d1d444071b351f007471299410123eb689
