### ISSUE TITLE
Highcharts causes accessibility problems on iOS8 using VoiceOver

### ISSUE THREAD

**Issue by keeganstreet** [highcharts/highcharts#3869]
When I add Highcharts to a webpage, VoiceOver users can no longer select radio buttons on the page. Highcharts is breaking other parts of the webpage which would otherwise be accessible.

Defect occurs with Highcharts 4.1.1 and 3.0.10 but not 2.3.5. Defect occurs on iOS 8.1.1 but not iOS 7.

Video demonstration of defect:
http://www.screencast.com/t/5NmNICSOf

Just to make things more confusing, the defect appears to change its behaviour on each page load, depending on how I interacted with the page on the previous page load. Video demo: http://www.screencast.com/t/I7l77Qbn

Defect demo:
http://jsbin.com/joleku/2

Example of defect not occurring with Highcharts 2.3.5:
http://jsbin.com/fibeko/2

If I call the Highcharts destroy() method the radio buttons start working again.

**Comment by oysteinmoseng** [comment]
Is this still an issue with latest Highcharts? It seems almost like a VoiceOver bug, given that VoiceOver receives the event (and even announces that it is clicking the button).

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
