### ISSUE TITLE
After updating ColorAxis, exporting still uses old configs

### ISSUE THREAD

**Issue by paulo-raca** [highcharts/highcharts#3874]
http://jsfiddle.net/th3q9hbt/
Reproduction: 
- Click the button => Chart color changes, axis range changes
- Click on export => Exported image uses original colors and axis range.

**Comment by pawelfus** [comment]
Works fine in 4.1.8: http://jsfiddle.net/th3q9hbt/1/

**Comment by pawelfus** [comment]
Sorry, just realized that extremes issue remain, only colors are updated (stops).

**Comment by sebastianbochan** [comment]
Looks like more complex issue with the axis options. 

Example: http://jsfiddle.net/1b724roy/
