### ISSUE TITLE
specific plotOptions should have priority over "series" plotOptions

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#3881]
http://jsfiddle.net/pwUC7/65/
I would expect the color to be blue, not red

**Comment by Izothep** [comment]
+1

**Comment by Resin01** [comment]
+1

**Comment by choudhary001** [comment]
+1

**Comment by sebastianbochan** [comment]
+1

**Comment by raf18seb** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Thanks for your patience, this should be fixed now. Reported cases with the fix applied:

* http://jsfiddle.net/highcharts/j7c4m2ue/3/
* http://jsfiddle.net/highcharts/34zLocr0/
* http://jsfiddle.net/highcharts/unw4bt0j/
* http://jsfiddle.net/highcharts/vaw41dup/
* http://jsfiddle.net/highcharts/ghLsvrzm/ (actually a different issue)
