### ISSUE TITLE
Boxplot disabled stem lines show back up after tooltip hover

### ISSUE THREAD

**Issue by stephenanders** [highcharts/highcharts#3884]
Example: http://jsfiddle.net/cdzzhqzs/

I wanted a BoxPlot without Whiskers or Stems.  I took the standard "box plot styling" example and modified the boxPlot options to set `whiskerLength: 0`, and `stemWidth: 0`.  Initial render looks right to me, but on hover, the stem lines appear (whiskers stay hidden).

**Comment by charron** [comment]
As a workaround for the moment, you can use very small but non-zero lengths.
Example: http://jsfiddle.net/5y0nhsqd/

**Comment by pawelfus** [comment]
The easiest workaround is to set `stemWidth: "0"` as a string. That will disable line. 

*Internal note:*
`stroke-width: 0` removes the stroke [here](https://github.com/highslide-software/highcharts.com/blob/master/js/parts/SvgRenderer.js#L1162) - it looks like stroke=0 suppose to remove that attribute..

**Comment by highslide-software** [comment]
The base cause is that a stroke is set on the `point.graphic` during hover, and since point.graphic in this case is a group, it is inherited by the stem path which doesn't have that attribute.
