### ISSUE TITLE
yAxis tickInterval is not working

### ISSUE THREAD

**Issue by nagesh-salunke** [highcharts/highcharts#3885]
I set yAxis tickInterval to 5. But it is taking it as 15 ?
Example : http://jsfiddle.net/jcacu6x3/

**Comment by highslide-software** [comment]
This behaviour is new in Highcharts 4.1, as a replacement for the old [error 19](http://www.highcharts.com/errors/19).

From the API:
> If the tickInterval is too dense for labels to be drawn, Highcharts may remove ticks.

If you disable the labels or set a smaller font size, all ticks are preserved: http://jsfiddle.net/jcacu6x3/2/.

It may be argued however that we should preserve the tick marks and grid lines and remove only the labels themselves in your case.
