### ISSUE TITLE
Highcharts when zoom with css Firefox

### ISSUE THREAD

**Issue by unutoiul** [highcharts/highcharts#3892]
When you zoom a chart with css the points when you rollover they don't fit.

zoom:reset doens't exist in firefox...any idea?

Thanks,
Lucas

**Comment by KacperMadej** [comment]
About the `zoom`:

> This feature is non-standard and is not on a standards track.

Source: https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

Use `transform: scale()` instead and refer to this issue: https://github.com/highcharts/highcharts/issues/2405
