### ISSUE TITLE
Tooltip for closely packed stacked columns

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3893]
Examples:
- http://jsfiddle.net/837k3z5j/1/ (defaults `groupPadding` - some space between columns)
- http://jsfiddle.net/837k3z5j/2/ (`groupPadding` set to 0)

Just hover left most dark column, then hover next one. Tooltip won't show up/refresh. Hovering light blue columns works a bit better.

**Comment by stephanevanraes** [comment]
Offending commit: aafde78

**Comment by pawelfus** [comment]
Works better in 4.1.8: http://jsfiddle.net/837k3z5j/4/ - but still tooltip can show tooltip for wrong bar, this is caused by `pointPlacement` most probably (without option - works fine!).

**Comment by pawelfus** [comment]
Fixed in v6.0.2: http://jsfiddle.net/BlackLabel/837k3z5j/5/ (in #7242 issue).
