### ISSUE TITLE
Tooltip vanishes instantly after touch event 

### ISSUE THREAD

**Issue by buddyp450** [highcharts/highcharts#3905]
#3666
#3450

In reference to the above issues, I was able to resolve my problem by simply commenting out the following block in the pinch function.

``` javascript
if ((hasZoom || followTouchMove) && !fireClickEvent) {
    e.preventDefault();
}
```

As a result however, the tooltip was exhibiting some strange behavior when resetting the zoom - it would change to a different point. To rectify this side-effect I simply disabled allowing tooltip movement altogether (it's a nice-to-have where-as the zoom and tooltip are required for my project).

In the reset function:

``` javascript
reset: function (allowMove, delay) {
        var pointer = this,
            chart = pointer.chart,
            hoverSeries = chart.hoverSeries,
            hoverPoint = chart.hoverPoint,
            tooltip = chart.tooltip,
            tooltipPoints = tooltip && tooltip.shared ? chart.hoverPoints : hoverPoint;

        // Narrow in allowMove
        allowMove = allowMove && tooltip && tooltipPoints;

        // Check if the points have moved outside the plot area, #1003
        if (allowMove && splat(tooltipPoints)[0].plotX === UNDEFINED) {
              allowMove = false;
        }

        //  Never allow tooltip to move - my change
        allowMove = false;

        ...
```

Don't ask me why this fixes things. ;)

I hope this sheds some light for highcharts to resolve the root of the problem.

**Comment by dreamershl** [comment]
The issue is because the haszoom flag will be true when the chart option "pinchType" isn't null. Although the document state the default value is 'null' for the "pinchType". In fact, the code set the default value as 'x'. Once you set the chart option as

      panning        : false,
      pinchType      : null

followTouchMove can works as expected.
