### ISSUE TITLE
Rendering logic is broken for datalabels

### ISSUE THREAD

**Issue by smithk58** [highcharts/highcharts#3906]
Similar to #3889

There still appears to be some cases where datalabels aren't being shown for no apparent reason.

Here's a JSFiddle: http://jsfiddle.net/rbz4u3wq/2/

**Comment by highslide-software** [comment]
Setting the `dataLabels.padding` to 0 makes it more tolerant regarding collision: http://jsfiddle.net/highcharts/rbz4u3wq/3/

**Comment by jon-a-nygaard** [comment]
Closing this issue due to it is pending a reply, and has been inactive for a long time. Should anyone have any further information on the issue, please comment and/or reopen.
