### ISSUE TITLE
Highmap : change chart type from other to map

### ISSUE THREAD

**Issue by natee** [highcharts/highcharts#3924]
In my case, chart options 'yAxis' is an [array] for the double axis chart.
When I change the chart from column to map,the map.src.js 'yAxis' wasn't an array,so this may effect the chart axis.

here is a simple demo http://jsfiddle.net/z4d05zra/3/

this demo shows when change chart type,the axis has problem,actually, the yaxis was reversed too.

line 2186 , I change it to below to match my case.

``` js
yAxis: [merge(hiddenAxis, { reversed: true })]
```

**Comment by KacperMadej** [comment]
Looks like bad merge / copy of options - working demo: http://jsfiddle.net/BlackLabel/z4d05zra/4/

Please provide more info and the issue could be reopened.
