### ISSUE TITLE
colorAxis.update doesn't change chart.options.colorAxis

### ISSUE THREAD

**Issue by perkyguy** [highcharts/highcharts#3936]
Found while trying to export a heat map after changing the settings. I had submitted a 
[SO Question](http://stackoverflow.com/questions/28748542/highcharts-export-after-updating-coloraxis), then found the answer after digging around a little. 

Line 15467 of highcharts.src.js assumes `chart.options[this.coll]` is an array. However, `chart.options.colorAxis` is not an array, thus the options never get updated during the update call. 

As I mention in the SO answer, this can be fixed if a conditional is thrown in which updates either the indexed object or the object itself.

[Initial Issue jsfiddle](http://jsfiddle.net/garrettascott/rje8y2sw/)

**Comment by KacperMadej** [comment]
+1

Adding `'colorAxis'` to [the array in chart update function](https://github.com/highcharts/highcharts/blob/e323678fbbf645e351357c1a4e15f24c0124bbaf/js/parts/Dynamics.js#L286) seems to be resolving the problem.
