### ISSUE TITLE
3D scatter - points' zIndexes

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3949]
Example: http://jsfiddle.net/Lj7ujLkg/2/

In the tooltip you can observe zIndexes of the points. However, when playing around with the angles, it may happen that blue scatter point will be plotted behind the red one.

**Comment by stephanevanraes** [comment]
Yes, but it seems logical to me, the z coordinate is higher and therefore the blue point is behind the red one.

**Comment by pawelfus** [comment]
Changing z-coordinate doesn't change how is this displayed. Attached screenshots: 
![screen shot 2015-03-09 at 2 05 53 pm](https://cloud.githubusercontent.com/assets/1453926/6555372/9662be9a-c665-11e4-943f-3f8992a36734.png)

![screen shot 2015-03-09 at 2 05 39 pm](https://cloud.githubusercontent.com/assets/1453926/6555367/8d9722ce-c665-11e4-8d29-37b8dafcc899.png)

**Comment by sebastianbochan** [comment]
+1

**Comment by sebastianbochan** [comment]
Fixed since 4.2
