### ISSUE TITLE
Draggable point icons vanish when X values approach equality

### ISSUE THREAD

**Issue by bazineta** [highcharts/highcharts#3953]
In the 4.1.2 release, using the draggable points demo:

http://jsfiddle.net/highcharts/AyUbx/

And modifying Series 3 to have the property:

```
draggableX: true
```

All point icons in the series vanish when dragging a point such that it's nearly the same as the X value of the point next to it.  All point icons return when moving the point a moderate distance away from an adjacent point.

This issue does not occur in the 4.0.4 release.

**Comment by highslide-software** [comment]
It's a consequence of the dynamic (best guess) setting for `marker.enabled`. If points become too dense, we hide the markers: http://jsfiddle.net/highcharts/27a362ch/. 

To avoid it, set the `marker.enabled` option to `true` explicitly: http://jsfiddle.net/highcharts/27a362ch/1/

**Comment by bazineta** [comment]
Setting marker.enabled to true does resolve the issue for us under 4.1.2, thanks.

**Comment by KacperMadej** [comment]
Doesn't look like a but and it's about the plugin that has it's own repository for bug reporting, so if you would like to reopen please open an issue there - https://github.com/highcharts/draggable-points/issues
