### ISSUE TITLE
colorAxis with dataClasses does not allow legendItemClick

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#3957]
Example: http://jsfiddle.net/rh8t755d/

Clicking on legend items does not trigger legendItemClick event.

**Comment by stephanevanraes** [comment]
This is because legendItemClick is defined on the series, while the colorAxis is not related to any series.

**Comment by the-codepunker** [comment]
Any ideas how one could code around this ?

**Comment by KacperMadej** [comment]
@the-codepunker Here's a workaround - added wrapper for legend item `setVisible` function that runs on each legend item click and is generated in `getDataClassLegendSymbols` of `ColorAxis.prototype`.

Demo: http://jsfiddle.net/bf77wcuw/

**Comment by KamilKubik** [comment]
unstale

**Comment by KamilKubik** [comment]
unstale

The issue is still relevant (v11.2.0).

**Comment by KacperMadej** [comment]
The issue is for the color axis and is not limited to Highcharts Maps.
Demo showing the problem: https://jsfiddle.net/BlackLabel/q9x7fdw6/
(with the previous workaround in the top comment block in the JS code tab)
