### ISSUE TITLE
Chart: Area chart in stacking mode with step: 'right' stacks based on left point of lower series, not right

### ISSUE THREAD

**Issue by jorupp** [highcharts/highcharts#3958]
Example: http://jsfiddle.net/r92tezrn/1/

Look at the first area block rendered for Series 1 - it's top is set correctly (based on the right point), but it's bottom is not (it's based on the left point for the lower series, not the right point).

**Comment by pawelfus** [comment]
Another test case: http://jsfiddle.net/LLh1g7h5/2/ (`step: "center"`).

**Comment by gunjanmodi** [comment]
@pawelfus :

I can see that you have fixed this issue. However, while testing the fiddle http://jsfiddle.net/LLh1g7h5/2/, I am still reproducing the problem. Is this fix moved in production code?

**Comment by pawelfus** [comment]
Sorry for a late answer! It is fixed on the bugfix branch: http://jsfiddle.net/LLh1g7h5/4/

**Comment by gunjanmodi** [comment]
Thanks for the update.
