### ISSUE TITLE
Highstock: bubble type series does not work

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#3961]
Error: "Uncaught TypeError: Cannot read property 'reversed' of undefined"

Example: http://jsfiddle.net/TvAw2/1/

It was OK in 2.0.4 - http://jsfiddle.net/TvAw2/2/

**Comment by stephanevanraes** [comment]
Note: this only happens in Highstock, not in Highcharts.

**Comment by cpell** [comment]
If it helps at all, I'm using the latest highstock 2.1.4/highcharts-more 4.1.4 and not seeing this issue so not all instances are affected

**Comment by cpell** [comment]
If it helps at all, I'm using the latest highstock 2.1.4/highcharts-more 4.1.4 and not seeing this issue so it seems not all instances are affected

**Comment by highslide-software** [comment]
Debug info: It fails when zoneAxis is `z`. For some reason Highcharts basic doesn't go into that code in the first place.

**Comment by stephanevanraes** [comment]
Should *bubbleSeries* have the zoneAxis set to `z` ?
