### ISSUE TITLE
tickAmount - serie is not centered

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3965]
Let's compare:
- http://jsfiddle.net/rb9p6b6t/1/
- http://jsfiddle.net/rb9p6b6t/2/

When we set tickAmount I think that serie should be in the middle, like in the first example.

**Comment by jflambert** [comment]
This issue is affecting me. As a workaround I wrote code that detects min==max values and forces min-- and max++ for the xAxis ticks.

**Comment by pawelfus** [comment]
Another workaround is to set `minRange` option instead, for example: http://jsfiddle.net/rb9p6b6t/3/
