### ISSUE TITLE
pie datalables: unwanted textshadow when setting a hex color

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#4010]
fiddle: http://jsfiddle.net/stephanevanraes/mmgf8tkg/

When setting the color for a datalabel using hex or rgba, a disturbing textshadow appears, this does not happen when you use named colors.

**Comment by highslide-software** [comment]
As of Highcharts 4.1, all data labels have a default text-shadow of '0 0 6px contrast, 0 0 3px contrast', where contrast is a pseudo color handled by Highcharts as a contrast to the text color. A brighter text color results in a black shadow, and a lighter text color results in a white shadow. 

This default behaviour was implemented as a response to poor readability in user generated charts that we observed.

However, the behaviour doesn't work well on medium-colored text, for instance on gray text that will receive a black semi-transparent background. [This fiddle](http://jsfiddle.net/highcharts/43soe9m1/2/) demonstrated how it works.

One proposal for a better default behaviour is to apply the shadow only to blackish and whitish text, thereby leaving the mid tones without a shadow. Here's a demo where the [opacity is lowered in the mid range](http://jsfiddle.net/highcharts/43soe9m1/3/). But this also has zones of blurry text. And gray text on gray background is of course unreadable.

Another observation is that a closer text shadow, with a radius of 2px or 1px, creates a sharper and in most cases more readable text.

**Comment by rinatio** [comment]
@TorsteinHonsi is there an option to disable this behavior [jsfiddle](http://jsfiddle.net/rinatio/sqr0Lrcg/)?

**Comment by TorsteinHonsi** [comment]
Yes of course, it is the `textShadow` CSS rule that applies. It can be set to `none`. http://jsfiddle.net/highcharts/sqr0Lrcg/1/

**Comment by rinatio** [comment]
@TorsteinHonsi thank you!

**Comment by inverts** [comment]
This does not appear to work anymore, looking at the JSFiddle above and trying it on my own as well.

**Comment by TorsteinHonsi** [comment]
Thanks. FYI, `textOutline` is mentioned at http://api.highcharts.com/highcharts/plotOptions.series.dataLabels.style, but not explained. I'll add more explanation.

**Comment by pawelfus** [comment]
Closing as docs are up-to-date.
