### ISSUE TITLE
[HighStock] Point.update in an OHLC chart breaks all kinds of things (jsFiddle available)

### ISSUE THREAD

**Issue by ddotlic** [highcharts/highcharts#4012]
Hi,

I took your basic OHLC jsFiddle and added a couple of tiny experiments (note I'm using latest as of today full source version of HighStock):
- A button which updates last bar's close value
- A button which then does the same thing every second

The jsFiddle is here: http://jsfiddle.net/qg9puv95/6/

I noticed the following issues:
1. When I use `Point.update` with first arg as object (code commented out), there's a crash with `cannot read property info of undefined`, please see point 4 for the consequences
2. When I use `Point.update` with first arg as array, nothing crashes visibly (no errors in JS console) but again same silly side-effects (again, see point 4) manifest
3. Regardless of `Point.update` "overload", only the first call appears to have any visual effect - the close value is updated, but the line representing it isn't (except once) - try it
4. The consequence of calling `Point.update` (even if just once) is that one cannot use the range part of the scroll bar any more, once you start resizing the range you cannot stop (mouse appears to be captured permanently)

This is hopefully something silly that you can easily fix. Thanks!

**Comment by pawelfus** [comment]
Workaround: disable `turboThreshold`, see: http://jsfiddle.net/qg9puv95/7/

**Comment by ddotlic** [comment]
Appers to be working fine, thanks for the pointer.

@pawelfus  Out of curiosity, how did you come up with the workaround?

**Comment by pawelfus** [comment]
Sorry, somehow I didn't receive notification. Regarding workaround, see: #2894 ;)
