### ISSUE TITLE
column stacking applied on seperate axes

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#4024]
Columns appear to be stacked even if they are on different xAxes: http://jsfiddle.net/0d5mysLy/

**Comment by highslide-software** [comment]
We currently check if they are on the same Y axis. We should probably do the X axis check in the same place.

**Comment by pawelfus** [comment]
Maybe instead of checking on xAxis, and creating there logic, we could add to the stack-keys xAxis index/id? Like `pick(series.options.xAxis , 0)`? So the whole logic will remain as is, just keys will distinct different x-axes.

**Comment by highslide-software** [comment]
Yes that's a good idea. Will you try that and check for regressions?

**Comment by pawelfus** [comment]
After fixing, I realized that stack labels are still rendered at the wrong place (on the 'left' axis). To fix that, I added reference in StackItem: `this.xAxis`, so when positioning stackLabels, x-position is taken from a correct xAxis.
