### ISSUE TITLE
Highstock: multiple column(range) series are compressed in middle of plot area

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4029]
Example: http://jsfiddle.net/79q5c6bk/1/

Series have too much space on both sides. It applies to column, columnrange, bar.

As a workaround it is possible to set pointRange.
Example: http://jsfiddle.net/79q5c6bk/5/

**Comment by pawelfus** [comment]
Another workaround: disable `ordinal` option: http://jsfiddle.net/79q5c6bk/6/

**Comment by TorsteinHonsi** [comment]
Duplicate of #2822
