### ISSUE TITLE
getBBox() returns same values when using multiple texts that has the same string.

### ISSUE THREAD

**Issue by yeoupooh** [highcharts/highcharts#4032]
I'm a newbie to Highcharts and SVG. So I am not sure this issue comes from SVG or Highcharts.

Here are an example and my workarounds.

http://jsfiddle.net/yeoupooh/y94706w4/

**Comment by pawelfus** [comment]
I think I posted the same issue, but I can't find it, though. 
Anyway, bounding boxes are cached (looks like caching method is changed in 4.1.x), so workaround is to force calculation: `element.getBBox(true);`, demo: http://jsfiddle.net/y94706w4/4/

**Comment by highslide-software** [comment]
Also, in your particular case you should probably use a label. See http://api.highcharts.com/highcharts#Renderer.text. Or even data labels, which can be styled and positioned the same way.

**Comment by yeoupooh** [comment]
Thank you guys for your quick responses.

Both solutions are helpful. For a label, I've updated the example in http://jsfiddle.net/yeoupooh/n80y9sev/.

**Comment by KacperMadej** [comment]
Currently the only difference is in x, y position. To be sure that the bbox is not loaded from cache please use getBBox with first argument set to true, as Paweł suggested. The current logic is not giving any errors to the core functions and provides better overall performance to a chart.

Please provide more info and the issue will reopen.
