### ISSUE TITLE
Double firing of event when tapping on pie chart legends on Android

### ISSUE THREAD

**Issue by bli** [highcharts/highcharts#4038]
Please refer to this jsfiddle:
http://jsfiddle.net/wjko6kr9/show

Open this in Android, pinch on the legends to zoom in a little bit and then tap on one of the legends to hide/show the pie slices. You will find sometimes (about 80% of the time) the legend is hidden and then shown again (or shown and then hidden again). It looks like the touch event is triggered twice sometimes. In my app, it's even worse, you don't need to zoom in to see this issue.

This does not happened in iOS though.

Also, if I take out the Legend.itemStyle.width option (see http://jsfiddle.net/wjko6kr9/1/show), the problem seems to be gone.

**Comment by KacperMadej** [comment]
Working fine in Highcharts v7.0.0.
Closing as resolved.
