### ISSUE TITLE
Highstock: addPoint to column series hides other column series

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4042]
Example based on demo: http://jsfiddle.net/3fmjvejb/1/

It applies also to other column originated series types.
Example with candlestick and flags:
http://jsfiddle.net/3fmjvejb/

If dataGrouping is disabled other problem is visible.
Example: http://jsfiddle.net/3fmjvejb/2/
Steps:
1. press Add button
2. press 6m on range selector

**Comment by HaiderAtPlero** [comment]
#4040 could be related? It's a showstopper!

**Comment by highslide-software** [comment]
The closing commit had to be reverted because it broke another, and more common, operation.

1. Open http://jsfiddle.net/6hpqpc7m/
2. Click "Day".
3. Fix the commit above active, the initial, weekly data grouping was stuck even when showing this short timespan.

**Comment by pawelfus** [comment]
Works fine since 4.2.7: http://jsfiddle.net/3fmjvejb/3/
