### ISSUE TITLE
Unable to click points of line chart in IE8/9

### ISSUE THREAD

**Issue by dwaynemb** [highcharts/highcharts#4045]
When loading the demo http://www.highcharts.com/demo/line-ajax in IE8 or IE9, the points of the chart are not clickable, but moving the cursor just outside the point, it changes and does allow click.

When loading this same chart in jsfiddle using the Edit In jsfiddle button at the bottom of the page, the points are clickable.

**Comment by KacperMadej** [comment]
Works fine now (version 6.1.1). Closing as resolved.

In case you still can recreate the problem please provide more details about the problem and it could be reopened.
