### ISSUE TITLE
Line and Area chart is not drawn if a second serie is of type ‘column’

### ISSUE THREAD

**Issue by Mathannus** [highcharts/highcharts#4054]
I have a problem with showing a second “Volume” graph of type column in my stock chart.
The problem is that when I try to change the type of the main chart and the volume graph is not displayed then the chart is not rendered at all if the type is “line” or “area”. “candlestick” and “ohlc” types are rendered correctly. This issue occurs in the stock chart version 2.1.4 but not in 2.0.4.

I have created a fiddle for this: http://jsfiddle.net/8pwbpg3r/6/

Please fix this if it is a bug or provide a workaround.

Thanks in advance,
Mathias Hannus

**Comment by highslide-software** [comment]
The data you provide is arrays of x, o, h, l, c values which is not recognized for line or area charts. See the [series-update](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/stock/members/series-update/) demo for how to provide data for different types.

**Comment by Mathannus** [comment]
Hi Torstein,
Thank you for the feedback. Applying your suggested modifications and turning off the turbotreshold doesn't help.
Here is the updated fiddle with the data manipulation added:
http://jsfiddle.net/8pwbpg3r/9/

If you uncomment the line 82 you will notice that the chart will not be drawn anymore.

Kind Regards,
Mathias

**Comment by pawelfus** [comment]
Simplified example: http://jsfiddle.net/z79hbocr/3/

Steps:

- click on line 
- click on column

Or:

- click on column
- click on line

Important thing is that `dataGrouping` should be in use.

**Comment by pawelfus** [comment]
Works fine since v5, demo: http://jsfiddle.net/BlackLabel/z79hbocr/6/
