### ISSUE TITLE
map.js missing from modules/ in highstock-release

### ISSUE THREAD

**Issue by jwhitmarsh** [highcharts/highcharts#4057]
Shouldn't it be [here](https://github.com/highslide-software/highstock-release/tree/master/modules)?

**Comment by sebastianbochan** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Strictly speaking, no... It belongs to the Highmaps product, but the map.js file from a given Highmaps version can be used together with the same Highstock version. 

Or you can use the `highcharts-dist` repo that contains Highcharts, Highstock and Highmaps side by side: https://github.com/highcharts/highcharts-dist/tree/master/modules .
