### ISSUE TITLE
Date time issue on Y-axis for bar type chart

### ISSUE THREAD

**Issue by ranoy** [highcharts/highcharts#4066]
Hi, 
 I have made this fiddle http://jsfiddle.net/py0m72uh/  . 
My issue is that even though the value for take-off is 09:35 it is being rendered after 18:00 for some strange reason.Though If I change the chart type to column and remove the series stacking property ,it seems to render fine . http://jsfiddle.net/py0m72uh/2/ .
Thanks,
Regards,

**Comment by highslide-software** [comment]
That's what stacking does - if you stack two columns on top of each other, each with a value of 1, the second one will stop at 2. See http://jsfiddle.net/py0m72uh/3/. 

Perhaps you should consider a columnrange chart instead?

**Comment by jon-a-nygaard** [comment]
Closing this issue due to pending a reply, and it is considered inactive.
