### ISSUE TITLE
Title's useHTML uses percents as pixels

### ISSUE THREAD

**Issue by borys-p** [highcharts/highcharts#4072]
I'm trying to force the title to wrap at around 90% of total chart width - in browser **and when exported** (which makes the external CSS styling not possible).

Unfortunately:

`title: { style: {
 'text-align': 'center',
 'width': '90%'
 } }`

Is parsed as "90" (px).

Example:
http://jsfiddle.net/fhmorgkg/2/

**Comment by KacperMadej** [comment]
When using title with `useHTML: true` use inline style instead of style for full HTML support.
Demo: http://jsfiddle.net/BlackLabel/edo6ty78/

Closing as resolved, but if you have more info about the problem the issue could be reopened.
