### ISSUE TITLE
dataLabels height vary between IE11 and Chrom/Firefox. Browser inconsistency.

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4090]
Example: http://jsfiddle.net/znygrc3a/7/

In IE11 dataLabels are placed in vertical center of bar, but in Chrome or Firefox they are placed closer to top of bars. Setting dataLabels.y carries over the difference - centering in Chrome decenters in IE11.

**Comment by highslide-software** [comment]
It is related to how the browsers or OS's report text bounding boxes. Consider [this fiddle][http://jsfiddle.net/highcharts/knmkvcab/).

* Chrome on Mac reports 15 pixels height. In the original demo, data labels are correctly centered.
* IE11 on Windows reports 18.44 pixels height. In the original demo, data labels are correctly centered.
* Chrome on Windows reports 18 pixels height. In the original demo, data labels are *not* centered.

**Comment by pawelfus** [comment]
Ok, do you have some suggestion for the workaround?

**Comment by highslide-software** [comment]
I'm afraid you wer going to ask that... :)

**Comment by pawelfus** [comment]
Yeah, I guess do :) 
As temporary workaround (SVG based) we can play around with `alignment-baseline` instead of bbox. Demo: http://jsfiddle.net/znygrc3a/11/

**Comment by highslide-software** [comment]
There's a workaround for similar issues in IE on https://github.com/highslide-software/highcharts.com/blob/v4.1.4/js/parts/SvgRenderer.js#L771.

If we make that more general, it will also apply to Chrome on Windows: 
```js
if (styles && styles.fontSize === '11px' && mathRound(height) === 17) {
```

I'm not sure how Firefox fits in though. It seems to report 15, but I can't see that it is closer to the top like you reported in the original post.

**Comment by pawelfus** [comment]
Hard to guess, as you said - on OSX it works fine (Chrome+FF tested). On Windows works the same way in IE, but may vary on Chrome+FF. 
For example FF on W7 (testing [your fiddle](http://jsfiddle.net/highcharts/knmkvcab/) displays 20.
