### ISSUE TITLE
HighStocks chart printing is resetting our EventSource connection

### ISSUE THREAD

**Issue by arnabk** [highcharts/highcharts#4105]
When I click on PNG, JPEG, PDF, SVG, I see that our EventSource connection is reset.
URL - https://www.binary.com/charting/livechart?l=EN#R_100:10min

![image](https://cloud.githubusercontent.com/assets/446864/7173275/c82d3464-e3b1-11e4-8f69-859f1a525b3b.png)

You can see that everytime I clicked on Export, it post something into export server, but it also reset the EventSource connection.

Print and CSV export does not reset the EventSource connection.

**Comment by highslide-software** [comment]
What is EventSource? Can you break this down to a Highcharts API problem?
