### ISSUE TITLE
Treemap zoomType does not work properly

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/highcharts#4106]
Example: http://jsfiddle.net/5ecv9jp9/1/
Using pinch zoom on point FL7 shows the bug clearly.

**Comment by jon-a-nygaard** [comment]
+1

**Comment by ppatliakevych** [comment]
Hello everyone! Has this bug been fixed already?

**Comment by pawellysy** [comment]
unstale

**Comment by hubertkozik** [comment]
Zooming of the Treemap series should work also with mouse-wheel zoom.

**Comment by princ09** [comment]
@hubertkozik can you please provide a demo for zooming of the treemap with mouse-wheel zoom?

**Comment by hubertkozik** [comment]
@princ09 This enhancement (zooming in Treemap series) is currently not implemented in Highcharts.
