### ISSUE TITLE
Highstock: point.update() with grouping alters data of point (and causes error#15)

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4109]
Error 15 (unsorted data) is caused by calling point.update() for grouped series.

Example: http://jsfiddle.net/5gdq2c0w/1/
Steps:
1. Click 'update point' button
2. Notice error in console
3. Zoom in to beginning of the x axis
4. Updated point now has different x and y values

**Comment by sebastianbochan** [comment]
+1

**Comment by rcazangi** [comment]
Any workarounds for this issue?

**Comment by TorsteinHonsi** [comment]
The commit above adds a warning on trying to update a grouped point, and prevents the following data errors. 

However it doesn't allow setting the marker properties, as they are connected to the raw point. Here's an attempt at setting data to raw points, though it only seems to take effect for the navigator series...: http://jsfiddle.net/5gdq2c0w/2/
