### ISSUE TITLE
Funnel - legend

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4113]
Seems that parameters like
- floating
- itemWidth

don't work. 

Example: http://jsfiddle.net/7q4931ex/3/

**Comment by pawelfus** [comment]
I think that params work, but legend doesn't resize plotted funnel. 

Extra issue: click on the "Invoice sent" series in the legend. Label for "Requested price list" moves down and overlaps "Invoice sent" label. Better to see in 4.1.5 version: http://jsfiddle.net/7q4931ex/4/ Setting `ignoreHiddenPoint` to false works around the issue: http://jsfiddle.net/7q4931ex/5/ 

Maybe just `ignoreHiddenPoint` doesn't work as expected when set to `true`?

**Comment by KacperMadej** [comment]
Working fine in current (6.1.0) version, so closing for now and can reopen if more info will be provided.
