### ISSUE TITLE
Autogenerated series names incorrect when using index.

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#4119]
http://jsfiddle.net/3myny924/1/

Both series have the same name, instead of being called _Series 1_ and _Series 2_.

**Comment by KacperMadej** [comment]
@TorsteinHonsi Should names change and be dynamic for dynamic changes in code?
I would say yes, but I want to be sure.
Example: http://jsfiddle.net/BlackLabel/u210jwq5/
