### ISSUE TITLE
serie.remove() not removing nodes correctly?

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#4121]
I noticed that nodes are not immediately getting removed when calling `remove()` on a serie.

I tried to reproduce it with this:
- open http://jsfiddle.net/pwUC7/82/ in Chrome
- wait for the page to load, then open the inspector and click record in the Timeline tab within 5 seconds
- when the chart is empty, stop recording, you'll see something like this:
  ![a](https://cloud.githubusercontent.com/assets/812033/7252985/98cb6592-e839-11e4-893f-4194d9dc8eea.png)

Clearly the nodes are not removed, but when forcing a garbage collect cycle, they are, so I don't think this is a big issue, but maybe worth looking into.

**Comment by KacperMadej** [comment]
Looks like garbage collector runs when it feels like it should run and all is fine.
Adding 20 series and removing them 50 times looks like in the below image:

![4121](https://user-images.githubusercontent.com/8960408/47031286-d4689980-d16f-11e8-92a3-23466111ba7c.jpg)

http://jsfiddle.net/BlackLabel/rcohLz7s/1/

Closing for now, but feel free to reopen in case this will become a problem.
