### ISSUE TITLE
Incorrect mouseOver event

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4122]
Example: http://jsfiddle.net/axfchau7/1/
Steps:
1. Open browser console
2. Enter plot area  from right side, over blue area (Series 1)
3. Move mouse pointer up and down in blue area (from over 40 to under 20 on y axis)
4. In console you can see that mouseOver is triggered for Series 1 and Series 2
mouseOver should be triggered only once - on entering of blue area, but moseOver for another series is being triggered while muse is not over that area

**Comment by highslide-software** [comment]
It happens since d228fa0, where the tooltip logic was changed to find the closest data point regardless of series, instead of only on the hovered series.

**Comment by pawelfus** [comment]
Works fine since 4.2.7: http://jsfiddle.net/hyrLjy2s/
