### ISSUE TITLE
First too long axis label gets wrongly fitted after drilldown

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4127]
Example: http://jsfiddle.net/f7y0xnmd/

Expected result: http://jsfiddle.net/Lvxqjqap/

Resize or forced redraw fixes the problem if called with delay.
Example: http://jsfiddle.net/tv6p2549/2/

**Comment by KacperMadej** [comment]
+1

Workaround doesn't fix chart for exporting, so when trying to export a chart labels will be overlapped.
**Another example:** http://jsfiddle.net/afddm8gm/
**Steps:** drill into Animals > labels are overlapping in chart and in exported chart

**Comment by Skaronator** [comment]
This issue is still not fixed.

If you change the size of the browser window it'll re-render the graph with correct lables. Probably only need to re-render the graph after switching to drilldown?

**Comment by Skaronator** [comment]
seems fixed?

**Comment by sebastianbochan** [comment]
It looks like works partially. The issue still occures during exporting (overlapping xAxis labels).

**Comment by KacperMadej** [comment]
Looks good on current (6.0.3) version - demo: http://jsfiddle.net/BlackLabel/f7y0xnmd/1/
Please add more info and a live demo showing the problem if you would like to get the issue reopened.
