### ISSUE TITLE
Highstock v2.0.4 set the passed in option's series as NULL

### ISSUE THREAD

**Issue by dreamershl** [highcharts/highcharts#4129]
In the StockChart constructor, the options.series will be temporarily set as NULL. But it is set directly in the passed in options object. While the restoring is done on the cloned one. So the original option object series attribute will be NULL after creating the chart instance.

    Highcharts.StockChart = function (options, callback) {
                              ...
                              options.series = null;
	                      options = merge(...);
                              options.series = seriesOptions;

**Comment by PhilTheAir** [comment]
I noticed this problem, too,,,

**Comment by pawelfus** [comment]
Duplicate of #636
