### ISSUE TITLE
Different positions of tick and gridline after zoom

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4131]
Example: http://jsfiddle.net/03jtab0o/23/
Try to zoom anywhere and observe right top corner.

**Comment by mihaienescu1** [comment]
Also, a more descriptive document attached here : https://docs.google.com/document/u/0/d/1ZDvrw0tJiLI3gjhgJlVTjSX5YzevFKDENW5fTDiSGMY/edit

**Comment by KacperMadej** [comment]
Unable to recreate using Highcharts version 7.0.2
Closing as resolved
