### ISSUE TITLE
Top ErrorBar label drops to the lower line after window is resized

### ISSUE THREAD

**Issue by williamfox4** [highcharts/highcharts#4133]
http://jsfiddle.net/highcharts/f8sB9/3/ 

When you resize the browser window, the label from the top of the errorbar drops down and sits above the lower line instead of remaining above the upper line. 

![before](https://cloud.githubusercontent.com/assets/12097202/7316302/a408718a-ea6d-11e4-998d-b4311534db66.png)
![after](https://cloud.githubusercontent.com/assets/12097202/7316301/a3fec0a4-ea6d-11e4-9ecb-d0058f253cbe.png)

Tested using the lastest release on here, in IE, FF & Chrome - All produce the same issue. 
May be related to, or as a result of #2770

**Comment by pawelfus** [comment]
Works fine since 4.1.7: http://jsfiddle.net/f8sB9/5/ - could you confirm?

**Comment by williamfox4** [comment]
The fiddle still reproduces the same issue I'm afraid. 
If you resize the result window to be smaller than the chart so that the redraw is triggered then you will be able to see.

**Comment by TorsteinHonsi** [comment]
Interestingly, the columnrange and arearange do this correctly. Even when we borrow the `alignDataLabel` method from column, error bar fails.
