### ISSUE TITLE
In Chrome variants chart must be touched 2 times to display the first tooltip

### ISSUE THREAD

**Issue by pwujek** [highcharts/highcharts#4145]
# Problem

Whenever a chart is drawn or refreshed in versions of Chrome where touch is enabled 2 touches are required to display the first tooltip.

How to view the problem on desktop Chrome (note: problem also occurs with Android Chrome):
# Setup
- Set location URL to: **http://www.highcharts.com/demo/line-basic**
- Enter 'Developer Mode' (by pressing F12)
- Toggle device mode ON.
- Choose Device **Google Nexus 7**
- Check _Emulation_ - _Sensors_ - _Emulate touch screen_ (cursor when over chart should now be a large dot)
# Test
- Touch once on line chart
- Observe that no tooltip has been displayed
- Touch a second time on line chart
- Observe that a tooltip will display
# Expected Behaviour

Every first touch should cause a tooltip to be displayed

**Comment by KacperMadej** [comment]
Looks like the same issue is reported as #6817 and has more comments, so let's close this as a duplicate.
If the issues are different please leave a comment with more info and this issue will be reopened.
