### ISSUE TITLE
Odd axis range choices when tickAmount used

### ISSUE THREAD

**Issue by mikegodber** [highcharts/highcharts#4159]
Hi,

I am not sure if this is a bug or not but I seem to get some odd axis range choices if I set a tickAmount, This can be seen here: http://jsfiddle.net/wefLtq9x/1/ were the range is set to 0-5000 when the max value is 2386. It quite often seems that half my charts are empty.

Another example is the following, also with a tick amount of 11.

![oddaxis](https://cloud.githubusercontent.com/assets/5088624/7471315/68a92dc4-f31d-11e4-86c0-230669974ce7.png)

Regards,

Mike

**Comment by pawelfus** [comment]
You can simply set `maxPadding`, for example: http://jsfiddle.net/wefLtq9x/2/ - `maxPadding` is set to 0.

**Comment by mikegodber** [comment]
Ok, thanks. I hadn't seen that option before. Whilst it helps it still results in the graph range doubling if you go a fraction over the current max, http://jsfiddle.net/wefLtq9x/4/

Maybe it needs a preferredTickAmount or some why of saying, about 11 ticks, or a tickDensity. 

As I write this I notice there is a tickPixelInterval which might suit my needs.

**Comment by KacperMadej** [comment]
Looks improved in version 6.1.4.
Closing as resolved.
If you have more info about the issue please leave a comment and the issue could be reopened.
