### ISSUE TITLE
dataLabels in 3D chart are placed incorrectly 

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4160]
Looks like alpha and beta of chart's options3d are not influencing position of dataLabels.
Example: http://jsfiddle.net/oubz3c4j/
Simple example: http://jsfiddle.net/oubz3c4j/1/

**Comment by stephanevanraes** [comment]
Note: Highcharts-3D does not currently support bar charts.

**Comment by highslide-software** [comment]
@stephanevanraes : Can you edit the .is3d() method so that it always returns false when the chart is inverted? Also, it should be noted in the docs.

**Comment by highslide-software** [comment]
Repoening this. Disabling 3d altogether was not necessary. See #4280.

**Comment by sebastianbochan** [comment]
+1

**Comment by KacperMadej** [comment]
@terraze Solution here was to disable, so this will not resolve the issue or you could disable 3d manually through option. Adding bar type series for 3d chart is an enhancement suggestion you are looking for. For such cases we are recommending adding a new or vote for an existing idea in our userVoice. The most popular ideas are getting implemented. https://highcharts.uservoice.com/forums/55896-general

**Comment by KacperMadej** [comment]
Closing as a duplicate of #5508
