### ISSUE TITLE
the new Options series.keys does't work in highmaps

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#4162]
the new Option [series.keys](http://api.highcharts.com/highcharts#plotOptions.series.keys) does not work in highmaps.

### 1. use normal data

```
var data = [{
  "hc-key": "cn-3664",
  "value": 0
},
{
  "hc-key": "cn-sh",
  "value": 1
},
{
  "hc-key": "cn-zj",
  "value": 2
},
{
  "hc-key": "cn-ha",
  "value": 3
},
{
  "hc-key": "cn-xz",
  "value": 4
}]
```

it run ok. 

###  2. use series.keys

```
var data = [
   ["cn-xz", 6],
  ["cn-hu", 9] 
  // ...
]

// ...
series : [{
    data : data,
    keys:['hc-key', 'value'],
    mapData: Highcharts.maps['countries/cn/cn-all'],
    joinBy: 'hc-key',
    // ...
}]
```

it does't work.

**Comment by zhy1stgg** [comment]
for highcharts changelog page, find this message : 

>Highmaps 1.1.5 (2015-04-13)

>Most changes listed under Highcharts 4.1.5 above also apply to Highmaps 1.1.5.

does  highmaps do not supported series.keys ?

**Comment by highslide-software** [comment]
At first glance I thought it was only the `joinBy` option that failed, but it turns out other options are also affected: http://jsfiddle.net/highcharts/ex6y26st/
