### ISSUE TITLE
Include exporting-server on highstock-release

### ISSUE THREAD

**Issue by utdemir** [highcharts/highcharts#4172]
Including `exporting-server/phantomjs/highcharts-convert.js` on `high{charts,stock,maps}-release` repository will be useful.

**Comment by RemiAWE** [comment]
+1

**Comment by TorsteinHonsi** [comment]
First of all, the `high*-release` repos are soon to be deprecated, and are now replaced by `highcharts` on npm as the official package.

We have just moved the export server over to a new repo, but we could of course ship the convert file with the distribution anyway.

@gvaartjes What do you think?

**Comment by gvaartjes** [comment]
What's the benefit with moving it to the highcharts repository? What's the use case here?

I would like to keep it separate from the Highcharts (js) repo and have it in it's own dedicated repository. We should also tag the highcharts-export-server repo to keep it in line with the highcharts repository. That's something I didn't think of when splitting it up.

**Comment by gvaartjes** [comment]
Last time I was too quick with my answer, sorry. I realize now it's about the *-release repos. I don't mind if it's added there, if our customers are asking for it.

@TorsteinHonsi What's the final status for the release repo's after considering the issues we had with Bower users?

**Comment by TorsteinHonsi** [comment]
The `highcharts-realese` repo is renamed `highcharts-dist`, and contains Highcharts, Highstock and Highmaps side by side with the same versioning.

The `highstock-release` and `highmaps-release` repos will be marked deprecated and the users adviced to use the `highcharts-dist` repo, available under the name `highcharts` on both Bower and npm.
