### ISSUE TITLE
Highstock: reversed x axis - problem with ticks

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4175]
Only first tick is placed if x axis is zoomed in.
Example: http://jsfiddle.net/tt9chsxu/

**Comment by pawelfus** [comment]
Works fine with non-ordinal axis: http://jsfiddle.net/tt9chsxu/1/

**Comment by sebastianbochan** [comment]
This is related with the reversed xAxis parameter, if disabled, all works well.
