### ISSUE TITLE
A Chart with all 0 datapoints ignores Min: 0 and startOnTick: true

### ISSUE THREAD

**Issue by dejongch** [highcharts/highcharts#4176]
http://jsfiddle.net/5st3qxh4/

If all the data on a graph happens to be 0 it the 0 line tick will always be in the middle. I understand that the graph doesn't know what sort of range to have but if Min for the y-axis is set to 0 then 0 should be at the x-axis especially when startOnTick is set to true.

**Comment by highslide-software** [comment]
This logic is defined at https://github.com/highslide-software/highcharts.com/blob/v4.1.5/js/parts/Axis.js#L1091.

What you are suggesting, also probably makes more sense in column or area charts where the threshold is 0, see for example http://jsfiddle.net/highcharts/5st3qxh4/2/.

See http://jsfiddle.net/highcharts/5st3qxh4/1/ for a way to drop in and make it behave like you want. 

The question is when we would expect the single tick to drop to the baseline.
* When a threshold exists?
* When only `min` is defined but not `max`?
* When `startOnTick` is defined? What if `endOnTick` is defined also?
* Other conditions?

**Comment by jon-a-nygaard** [comment]
Closing this issue since it is considered inactive, and pending a reply. Should anyone have further information about the issue, please give us a comment.
