### ISSUE TITLE
When using `dataClasses`, the `to` and `from` conditions aren't reflected in legend correctly

### ISSUE THREAD

**Issue by bkfunk** [highcharts/highcharts#4178]
It appears that the `to` and `from` conditions use less-than-or-equal and greater-than-or-equal tests:

```
if ((from === UNDEFINED || value >= from) && (to === UNDEFINED || value <= to)) {
```

But when one is unspecified, the legend says "<" or ">". For example, if `to: 5` and `from` is not set, the lowest category will be labeled "< 5" rather than "<= 5".

It would also be helpful if the documentation made it explicit that the range is closed on both ends, and thus that a value exactly on the edge will (I'm assuming) be classified in the last matching category in the array.

**Comment by KacperMadej** [comment]
The following info could be added to the docs:

> Range of each dataClass is closed on both ends, but will but will be overridden by next dataClass.

Demos:
1. http://jsfiddle.net/BlackLabel/n0xdrjzd/1/
Canad (value 4) and Brazil (23) both in the green zone.

2. http://jsfiddle.net/BlackLabel/n0xdrjzd/2/
The green zone overridden by the red zone - nothing is green.
