### ISSUE TITLE
allow disabling highcharts crisp feature for phantomjs svg and pdf export

### ISSUE THREAD

**Issue by level420** [highcharts/highcharts#4179]
As discussed in #3988 the highcharts crisp feature rounds the output to the nearest pixel.

This feature limits output accuracy using phantomjs for scalable output formats like svg and pdf, as it inhibits sub pixel calculations on some chart features (e.g. columns).

To verify this use the following fiddle http://jsfiddle.net/0mL030wj/3/ and export the chart as a svg graphics. Scale the graphics up and observe the different column gaps in the chart.

**Comment by highslide-software** [comment]
I'm not sure whether to implement this in the core, but here's a patch that you can try out. To enable it, set `crispEdges` to false in the series (or plotOptions.column) config.

```diff
diff --git a/js/parts/ColumnSeries.js b/js/parts/ColumnSeries.js
index 6518906..8242e99 100644
--- a/js/parts/ColumnSeries.js
+++ b/js/parts/ColumnSeries.js
@@ -161,6 +161,7 @@ var ColumnSeries = extendClass(Series, {
 			pointWidth = metrics.width,
 			seriesBarW = series.barW = mathMax(pointWidth, 1 + 2 * borderWidth), // postprocessed for border width
 			pointXOffset = series.pointXOffset = metrics.offset,
+			crispEdges = options.crispEdges !== false,
 			xCrisp = -(borderWidth % 2 ? 0.5 : 0),
 			yCrisp = borderWidth % 2 ? 0.5 : 1;
 
@@ -171,10 +172,14 @@ var ColumnSeries = extendClass(Series, {
 			}
 		}
 
+		if (!crispEdges) {
+			xCrisp = yCrisp = 0;
+		}
+
 		// When the pointPadding is 0, we want the columns to be packed tightly, so we allow individual
 		// columns to have individual sizes. When pointPadding is greater, we strive for equal-width
 		// columns (#2694).
-		if (options.pointPadding) {
+		if (options.pointPadding && !crispEdges) {
 			seriesBarW = mathCeil(seriesBarW);
 		}
 
@@ -199,9 +204,9 @@ var ColumnSeries = extendClass(Series, {
 					barH = minPointLength;
 					up = (!yAxis.reversed && !point.negative) || (yAxis.reversed && point.negative);
 					barY =
-						mathRound(mathAbs(barY - translatedThreshold) > minPointLength ? // stacked
+						mathAbs(barY - translatedThreshold) > minPointLength ? // stacked
 							yBottom - minPointLength : // keep position
-							translatedThreshold - (up ? minPointLength : 0)); // #1485, #4051
+							translatedThreshold - (up ? minPointLength : 0); // #1485, #4051
 				}
 			}
 
@@ -210,13 +215,17 @@ var ColumnSeries = extendClass(Series, {
 			point.pointWidth = pointWidth;
 
 			// Round off to obtain crisp edges and avoid overlapping with neighbours (#2694)
-			right = mathRound(barX + barW) + xCrisp;
-			barX = mathRound(barX) + xCrisp;
-			barW = right - barX;
+			if (crispEdges) {
+				right = mathRound(barX + barW) + xCrisp;
+				barX = mathRound(barX) + xCrisp;
+				barW = right - barX;
+			}
 
 			fromTop = mathAbs(barY) < 0.5;
-			bottom = mathMin(mathRound(barY + barH) + yCrisp, 9e4); // #3575
-			barY = mathRound(barY) + yCrisp;
+			bottom = mathMin((crispEdges ? mathRound(barY + barH) : barY + barH) + yCrisp, 9e4); // #3575
+			if (crispEdges) {
+				barY = mathRound(barY) + yCrisp;
+			}
 			barH = bottom - barY;
 
 			// Top edges are exceptions
```

**Comment by level420** [comment]
Thank you for the patch Thorstein. I'll test it today and report back.

Do you have a raw (file) version of you patch? That would be great!

**Comment by level420** [comment]
Hi Thorstein

The patch works as expected! Thanks allot!

But PLEASE, PLEASE add it to core, because it IS relevant if creating PDF (or SVG) output with accurate calculated bar distances especially in high resolution printing.

Regards
Dietrich

**Comment by level420** [comment]
Hi Torstein!

Any decisions on this subject? As said before this patch is VERY helpfull in creating accurate bar charts in SVG and PDF-Files.

Regards
Dietrich

**Comment by level420** [comment]
@highslide-software did you made any decision on implementing this in the core? It would be very helpfull!!!!

Regares
Dietrich

**Comment by level420** [comment]
Hi Torstein!

I wanted to ask again regarding the state of this issue. As stated before this would help us a lot!

Regards
Dietrich

**Comment by level420** [comment]
Hi Torstein!

I'm regularly asking for this issue, as it would help us a lot.

Should I close this issue and create a new one which may gain more attention?

Regards
Dietrich

**Comment by level420** [comment]
Accidently closed and reopened as new issue #4270.

**Comment by level420** [comment]
Hi Torstein!

I'm regularly asking for this issue, as it would help us a lot.

Regards
Dietrich

**Comment by level420** [comment]
@Torstein: please have look into this issue! 

Your supposed patch solves the issue of inaccurate bar charts in pdf and svg output and does not change the default behaviour!

It would be extremly helpfull having this feature implemented in the distro!

Best regards
Dietrich

**Comment by level420** [comment]
@Torstein: as time passes I want to ask if it would be possible to have this patch in master.

Thank your for your help.

Best regards
Dietrich

**Comment by highslide-software** [comment]
As per the commit above, I refactored this as a preparation for Highcharts 5. Now you can disable crisping through an override: 
```js
Highcharts.wrap(Highcharts.seriesTypes.column.prototype, 'crispCol', function (proceed, x, y, width, height) {
    if (this.chart.renderer.forExport) {
        return {
            x: x, 
            y: y,
            width: width,
            height: height
        };
    } else {
        return proceed.call(this, x, y, width, height);
    }
});
```
[View it live on jsFiddle](http://jsfiddle.net/highcharts/ux5d75h1/).

**Comment by level420** [comment]
That's great! Thank you!

But does this also work if I'm sending this to the phantomjs rendering service as a json file?

Best regards
Dietrich

**Comment by level420** [comment]
My testcase in a fiddle using your fiddle:

http://jsfiddle.net/ux5d75h1/2/

**Comment by highslide-software** [comment]
> But does this also work if I'm sending this to the phantomjs rendering service as a json file?

That won't work yet, because the export server runs 4.1.8, and we haven't added an option to turn off crisping.

**Comment by level420** [comment]
OK. That's clear that it does not work with 4.1.8. 

But as soon as higcharts 5 is out: Will it work if I send a json file to the phantomjs rendering service?

Best regards
Dietrich
