### ISSUE TITLE
pieseries uses wrong centerpoint

### ISSUE THREAD

**Issue by lorgan3** [highcharts/highcharts#4182]
In our case the point.startR can be 0. The or check then causes the r value to be `series.center[3] / 2`. This gives the following error because series.center is undefined at this point: Uncaught TypeError: Cannot read property '3' of undefined. Found on Google Chrome.

Line 16561 (highcharts v4.1.5 (2015-04-13))

``` javascript
                    graphic.attr({
                        r: point.startR || (series.center[3] / 2), // animate from inner radius (#779)
                        start: startAngleRad,
                        end: startAngleRad
                    });
```

**Comment by highslide-software** [comment]
The `point.startR` property is only used in solid gauges. Can you reproduce the failing chart in a live jsFiddle?

**Comment by hurdad** [comment]
i have this same issue, using highstock.js with solid guage. I had to comment out the series.center[3].

**Comment by highslide-software** [comment]
Here's a solid gauge with Highstock http://jsfiddle.net/highcharts/qvnawedw/. Can you demonstrate the issue based on this fiddle?

**Comment by jon-a-nygaard** [comment]
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Comment by les2** [comment]
cc @rwwagner90

**Comment by les2** [comment]
> Here's a solid gauge with Highstock http://jsfiddle.net/highcharts/qvnawedw/. Can you demonstrate the issue based on this fiddle?

@TorsteinHonsi please see this fiddle: http://jsfiddle.net/gen5gcua/1/

<img width="1104" alt="screen shot 2018-03-23 at 4 31 19 pm" src="https://user-images.githubusercontent.com/1066080/37852085-a600409e-2eb7-11e8-893e-56b37ac53afa.png">

**Comment by pawelfus** [comment]
Hi @les2 

Thank you for the example! 

Simplified demo: http://jsfiddle.net/BlackLabel/gen5gcua/10/

As long as we set `radius: "0%"` this issue occurs. Actually, why `innerRadius` is higher than `radius`? If we swap these options it works perfectly fine: http://jsfiddle.net/BlackLabel/gen5gcua/12/

**Comment by dmitrygorbenko** [comment]
hi guys,
any progress on this ?
I can add more information on my case, if you want.
Can record a video, etc.

thanks,
Dima

**Comment by pawelfus** [comment]
Hi @dmitrygorbenko 

Thanks! No progress, but could you answer my question above? Why setting `innerRadius` > `radius`? It looks like misconfiguration causes the issue.

**Comment by PaulDalek** [comment]
This is already fixed on master (the `r` is chosen by using `pick(point.startR, (series.center && series.center[3] / 2))`), so the next release will be free of this issue. Also, always remember to set `radius` with a higher value than `innerRadius` in order to ensure correct functioning.

**Comment by sachinmishra-gep** [comment]
Hi @PaulDalek ,

Could you please tell us the version number and values to be set for radius and innerRadius ?

**Comment by sebastianbochan** [comment]
The next release should be available within next weeks. Please stay on track with your github and newsletter.

**Comment by sachinmishra-gep** [comment]
Thank you @sebastianbochan for the update.meanwhile could you please tell us the same beta version of the same package to test on dev environment.

**Comment by sebastianbochan** [comment]
You can use the master branch as a dev-test (ref: https://github.highcharts.com/highcharts.src.js)

**Comment by sachinmishra-gep** [comment]
is it possible to test with npm package as well ?

**Comment by bre1470** [comment]
@sachinmishra-gep 
This will be possible sometime in the future. The pending issue can be found here: https://github.com/highcharts/highcharts/issues/11166

**Comment by sachinmishra-gep** [comment]
Upgradation to Highcharts@8.0.0 will fix the issue
