### ISSUE TITLE
Can't pan to the axis end  in bubble charts

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#4185]
When you zoom in a bubble chart and then pan, you can't pan the bubbles into view that are near the end (or beginning) of the axis scale.

See this example http://jsfiddle.net/kzoon/j4nccj2h/

**Comment by pawelfus** [comment]
Not a perfect workaround, but I would try to set `poinRange`: http://jsfiddle.net/j4nccj2h/1/ - the only problem is to set proper `pointRange` which may depend on the data set.
