### ISSUE TITLE
Highstock: setting data with different time range breaks navigator

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4187]
Example: http://jsfiddle.net/768g9do9/3/
Steps: 
1. press "data3" (data1 + data2)
2. press "data2" (x axis is not how it supposed to be)
3. press "data1" - error in console "Error: Invalid negative value for <rect> attribute width="-43920366" " and navigator is broken

**Comment by pawelfus** [comment]
Works fine in 4.2.5 and 4.2.6 versions: http://jsfiddle.net/768g9do9/6/
