### ISSUE TITLE
Multiple yAxis with label align left not working

### ISSUE THREAD

**Issue by balticSD** [highcharts/highcharts#4191]
Hi,

it is not possible to have two axis on one side with labels align left.
Label are overlapping axis title.

Sample: http://jsfiddle.net/balticsd/osmckc86/

The left align of the second yaxis (2.) should respect the full width (title, line, labels) of the first one (1.):
![highchart](https://cloud.githubusercontent.com/assets/8436300/7644795/9f5a6510-faaa-11e4-8d16-0370a1192058.png)

Like with default label alignment:
![highchart2](https://cloud.githubusercontent.com/assets/8436300/7644875/44d4e712-faac-11e4-8176-b94bef0ae17f.png)

**Comment by highslide-software** [comment]
When you set align left, you effectively place the labels inside the plot area, as you can see from the Y axis line. When computing the layout, we are looking for whatever is more to the left of the labels or the plot area.

**Comment by balticSD** [comment]
Hi Torstein,
but what can I do now to align the chart labels in a proper way but on the right side?

**Comment by highslide-software** [comment]
One option is to go for the default behaviour:  http://jsfiddle.net/highcharts/osmckc86/4/

Otherwise, to allow the inner axis to draw its labels inside the plot area, you can align only that axis to the left: http://jsfiddle.net/highcharts/osmckc86/5/
