### ISSUE TITLE
Highstock: xAxis with break changes columns width

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4193]
Example: http://jsfiddle.net/ycL16q9f/
(compare with unchanged: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/candlestick-and-volume/)

Steps: 1. zoom in fully - columns are as very thin.
Also: if you zoom out fully (All button) - this is visible too.

**Comment by sebastianbochan** [comment]
It looks like an issue, when breaks is applied. Without that you can set pointRange.

http://jsfiddle.net/ycL16q9f/1/

**Comment by priikone** [comment]
Here's another example of the problem http://jsfiddle.net/ve1kzjav/.  Zoom the navigator in and out and you'll see how the candlestick scale changes.

**Comment by KacperMadej** [comment]
It looks like some ordinal logic is applied when breaks are set. Workaround could be to hide breaks from the wrapped beforeSetTickPositions from [OrdinalAxis part](https://github.com/highcharts/highcharts/blob/master/js/parts/OrdinalAxis.js).

Demo: http://jsfiddle.net/BlackLabel/ve1kzjav/1/
