### ISSUE TITLE
Enhance the the flags support for HighStock

### ISSUE THREAD

**Issue by mlvn23** [highcharts/highcharts#4199]
Would it be possible to enhance the flags support for HighStock? 

The main use-case is to show the buy and sell signals, or possibly a commentary. Typically, these are shown as up / down arrows, circles, etc, and when you hover your mouse, it would show some detail like when it was bought, how many shares, current profit, the buy or sell reason, etc. You only need to indicate the bar where you want it attached, and whether you want to show on the high, low, open, the close, or specific price with a fixed pixel offset (adjusting for ohlc vs line chart). The flags is typically shown above the high or below the low, but it's also useful to show on the side of the bar to indicate at what price you entered or exited.

Right now, I've implemented this using a scatter chart on top of a candlestick chart, but it feels like a hack.

Some examples:

[WealthLab Buy and Sell Signals](http://www.leveragefx.com/images/forex-software/currency-indexes-on.png)

[TradingView commentary](https://www.tradingview.com/chart/?symbol=AAPL)

[TradeStation ShowMe](http://markplex.com/wordpress/wp-content/uploads/2011/10/program3-1.jpg)

**Comment by KacperMadej** [comment]
This seems to be doable out of the box with Highstock and `flags` series.
Demo: http://jsfiddle.net/kwzL1k7g/

**Comment by mlvn23** [comment]
@KacperMadej try it on OHLC or Candlestick.

**Comment by KacperMadej** [comment]
@mlvn23 It looks fine with candlestick - http://jsfiddle.net/pjnmLbsq/1/
Maybe you could add an image for the expected chart, so we could be on the same page?

**Comment by mlvn23** [comment]
@KacperMadej You can check out the "WealthLab Buy and Sell Signals" in the original post. The buy signals are usually below the LOW and the sell signals are usually ABOVE the high in financial charting applications. Here's another example from [TradeStation](http://www.usingeasylanguage.com/wp-content/uploads/2015/01/3-10-2015-6-35-43-PM.jpg).

I tried work-around it by adding and subtracting a percentage from the high and the low, but that doesn't work because a stock price can be $1 or $32,000, so the offset can vary wildly. I think what we need is an offset based on pixels and not values.

**Comment by KacperMadej** [comment]
@mlvn23 It should be possible to use [onKey](http://api.highcharts.com/highstock/series%3Cflags%3E.onKey) option and set it to `low`. It is not possible and it looks like a bug, so I opened another issue: https://github.com/highcharts/highcharts/issues/6478

That option will resolve this problem, so if there is nothing more in this issue then we could close it and continue on the new one - a more specific one. Is that good with you @mlvn23 ?

**Comment by mlvn23** [comment]
Ok, the working example looks good!
