### ISSUE TITLE
Setting 'useUTC' option when using highcharts-convert.js

### ISSUE THREAD

**Issue by pchaganti** [highcharts/highcharts#4206]
Is there anyway to set useUTC with highcharts-convert.js? This is a global option and there does not seem anyway to set it when rendering using convert and phantomjs.

thanks!

**Comment by KacperMadej** [comment]
The legacy Java + PhantomJS Highcharts Export Server is no longer maintained. Please check out our new NodeJS based export server - https://github.com/highcharts/node-export-server
