### ISSUE TITLE
The min thumb is updated when the max thumb is moved

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#421]
Date range slider moves its min ext value 1 day less

After loading, if you move the max extreme, the min extreme automatically is subtracted by one day.
This occurs just the first time you move the max extreme, then it gets stable.

Example: http://www.highcharts.com/stock/demo/
Forum thread: http://highslide.com/forum/viewtopic.php?f=12&t=12115

**Comment by oysteinmoseng** [comment]
Does not seem to be an issue in latest: https://jsfiddle.net/hbvtb5x4/
