### ISSUE TITLE
Treemap: border set for data point is overlapping other points

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4211]
Border set for data point is overlapping other points and zIndex of points is changing because of hovering over points.
Example: http://jsfiddle.net/kzoon/p9cgg9pe/3/

**Comment by highslide-software** [comment]
Highcharts tree maps are designed to put the hovered square on top, in order to have the border above other borders. This is clear with another example: http://jsfiddle.net/p9cgg9pe/6/.

@jon-a-nygaard Maybe we should disable individual borderWidth settings on points?

**Comment by jon-a-nygaard** [comment]
@highslide-software  It would simplify and avoid some visual problems if all points had the same borderWidth. But that would also mean that we should disable it for the levels options also.

A more complicated option, which in a way is also more correct, is to include the borderWidth into the calculation of the plotting area of each point.

**Comment by highslide-software** [comment]
> But that would also mean that we should disable it for the levels options also.

I don't think so, because as long as all visible points in the view have the same borderWidth, it's okay. The problems starts when there are points with different border widths visible at the same time at the same level.
