### ISSUE TITLE
Highstock does not support inverted

### ISSUE THREAD

**Issue by smallyard** [highcharts/highcharts#4218]
I'll be grateful for that you can add this feature.

**Comment by highslide-software** [comment]
What would an inverted stock chart look like? A [Google search](https://www.google.no/search?q=inverted+stock+chart&espv=2&biw=1920&bih=1105&source=lnms&tbm=isch&sa=X&ei=DNVeVcS0JoPjywPU5oKABA&ved=0CAYQ_AUoAQ) gives no meaningful results.

**Comment by qu4ntyl** [comment]
I guess liuhongqiang means the "reciprocal" of the chart as in:

http://stockcharts.com/articles/mailbag/2013/05/how-can-i-create-an-inverse-chart-.html
http://stockcharts.com/articles/dont_ignore_this_chart/2009/02/what-did-the-vix-know-and-when-did-it-know-it.html

Where the stock price is simply inverted (1/p_t) for visualisation purposes.

**Comment by highslide-software** [comment]
Oh, in that case you can just add another series with inverted y values... http://jsfiddle.net/highcharts/rnj9b41y/

**Comment by highslide-software** [comment]
@liuhongqiang Does that answer your request?

**Comment by liuhongqiang** [comment]
@highslide-software @qu4ntyl  I'm sorry, this is not what I want. I mean it just like bar chart , exchange x,y axis.

**Comment by KacperMadej** [comment]
Since scrollbars and navigator are possible for vertical axes this there shouldn't be any problems - http://www.highcharts.com/news/224-scrollbars-for-any-axis/
