### ISSUE TITLE
Marker images are inverted when chart.inverted == true

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#422]
If the chart uses image markers at the same time as being inverted, then the images share the inverted coordinate system with the chart.
Expected: the images should not be inverted, but instead treated in the same way labels are (being positioned but not inverted)

Example: http://jsfiddle.net/Nqn7s/
Forum thread: http://highslide.com/forum/viewtopic.php?f=9&t=12071

**Comment by oysteinmoseng** [comment]
Still relevant with current version http://jsfiddle.net/xz4esbys/
