### ISSUE TITLE
Highcharts.dateFormats not documented in Highstock reference

### ISSUE THREAD

**Issue by vickychijwani** [highcharts/highcharts#4228]
Highcharts doc link: http://api.highcharts.com/highcharts#Highcharts.dateFormats

This option isn't documented in the [Highstock API reference](http://api.highcharts.com/highstock), please add it. Thanks!

**Comment by pawelfus** [comment]
Restructured API has proper reference to `dateFormats`: https://api.highcharts.com/class-reference/Highcharts.html#.dateFormats
