### ISSUE TITLE
when using panning, xAxis'[min, max] be incorrect

### ISSUE THREAD

**Issue by 1984weed** [highcharts/highcharts#4230]
It appears that panning axis.min and axis.max evaluate lower then actual value sometimes, when highchart with specific options.

``` javascript
      rangeSelector : {
                selected : 1
            },
            xAxis: {
                startOnTick: true,
                endOnTick: true,
                tickPositioner: function(min, max){
                    var range = max - min;
                    return [min + range/10, max - range/10]
                }
            },
           plotOptions:{
                series:{
                    dataGrouping:{
                        enabled: false
                    }
                }
            },

            series : [{
                name : 'AAPL',
                data : data,
                tooltip: {
                    valueDecimals: 2
                }
            }],
          navigator: {
                enabled: false
            }
```

I have set up a simple test http://jsfiddle.net/4tnL209t/1/
The more paning chart many times, the fewer display data.

Please check it.

**Comment by pawelfus** [comment]
`startOnTick` and `endOnTick` are not supported in Highstock with navigator (as I know). According to the [docs](http://api.highcharts.com/highstock#xAxis.startOnTick): 

> In Highstock, startOnTick is always false when the navigator is enabled, to prevent jumpy scrolling. Defaults to false.

Looks like is not always set to false? 

Extra internal note: looks like `endOnTick` is missing similar description as `startOnTick`?

**Comment by 1984weed** [comment]
thanks
I understand your answer. But in this case, I set ```navigator:{ enabled false}```. to HighStock.

Should  ```endOnTick``` and ```startOnTick``` be always set to false?
In any case I want to write down [options reference](http://api.highcharts.com/highstock) what HighStock doesn't work with ```navigator:{ enabled false}```, ```tickPositioner```　and ```endOnTick: true``` and ```startOnTick: true```

**Comment by KacperMadej** [comment]
`Should endOnTick and startOnTick be always set to false?`
Yes, when scrolling is enabled those options should be set to `false'.

This is not a bug.
For technical support please contact [Highcharts technical support](https://www.highcharts.com/support).
