### ISSUE TITLE
Exporting button overlaps title

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#4231]
Example: http://jsfiddle.net/tssybksL/3/

When using custom text or bigger image for a button, it overlaps the title.

**Comment by gugahoi** [comment]
I just found a similar problem the only difference being I have multiple buttons and on long titles they overlap. Were you able to find a solution for this?

**Comment by highslide-software** [comment]
As a suboptimal workaround, you could set a fixed width for the title. See http://jsfiddle.net/highcharts/tssybksL/4/. 

The problematic line is [here], where a constant number is substracted to make room for the context button. 

```js
			autoWidth = this.spacingBox.width - 44; // 44 makes room for default context button
```
Another problem is that if we set a lower width, the text is not centered.

**Comment by gugahoi** [comment]
Thanks @highslide-software. Let me then throw a further complication in the mix:

I am using charts within a dashboard layout where they can be re-sized. Can I then use a percentage as the title's width? Say I only want it to take half the width across the top?
