### ISSUE TITLE
dataLabel's allowOverlap does not work with useHTML: true

### ISSUE THREAD

**Issue by aberenyi** [highcharts/highcharts#4236]
Hi there,

It looks like the awesome [`allowOverlap`](http://api.highcharts.com/highcharts#plotOptions.area.dataLabels.allowOverlap) feature does not work if `useHTML` is set to `true`.

I'm using (a patched) font-awesome to display rotated arrows (16 point compass) as labels (via a `formatter` function).

[Fiddle](http://jsfiddle.net/aberenyi/73h4wc87/) (based on [this](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/plotoptions/series-datalabels-allowoverlap-false/)).

Is this by design? If not, is there any solution to solve this?

Cheers

**Comment by pawelfus** [comment]
Fixed in 4.1.8: http://jsfiddle.net/73h4wc87/2/ - could you confirm?

**Comment by sebastianbochan** [comment]
Missing fiddles, reopen when problem will come.
