### ISSUE TITLE
undefined color point into tooltip when we use zone in series charts

### ISSUE THREAD

**Issue by ncoquelet** [highcharts/highcharts#4238]
Hi,

I have a small issue with the default behaviour of zones settings on series charts.

Zones settings can be used to change the color of the line. We use it to highlight a range period in the chart by changing the color inside the zone. (our chart always display all period).

If i don't set explicitly a color of a specific zone, defaut color used is the serie color. That's what i want !
But in tooltip, the color isn't correct. Always black.

In debug, into tooltip.formatter() function, this.points[].point.color is undefined, like fillColor
If I force the color inside zone settings, all works fine !

See http://jsfiddle.net/5yq09gr5/1/

Thanks

**Comment by pawelfus** [comment]
Works fine in 4.1.10: http://jsfiddle.net/v9v86g8g/
