### ISSUE TITLE
Drilldown button crash

### ISSUE THREAD

**Issue by karlamagallanes** [highcharts/highcharts#4239]
When you have Data with and without drilldown. 
If you click on the hyperlink label to drilldown a Data array without  drilldown it paints a button without text.

if you press this button it shows a error on js.

here's an example: http://jsfiddle.net/karlamagallanes/edkbrrt1/2/
 (remove "Series with drilldown", click on "Fruits" category"  now click the small square on the upright corner) (see js errors on  your web browser console)

This only happen on IE on compatibility mode.. (and other graphical issues)

to fix this i modify the src of drilldown.js to validate if the botton has text:

```
h.prototype.showDrillUpButton = function () {
    var b = this,
    a = this.getDrilldownBackText(),
    c = b.options.drilldown.drillUpButton,
    e,
    f;
    **if (a) {**
        this.drillUpButton ? this.drillUpButton.attr({
            text : a
        }).align() : (f = (e = c.theme) && e.states, this.drillUpButton = this.renderer.button(a, null, null, function () {
                    b.drillUp()
                }, e, f && f.hover, f && f.select).attr({
                    align : c.position.align,
                    zIndex : 9
                }).add().align(c.position, !1, c.relativeTo || "plotBox"))
    **}**
};
```

**Comment by KacperMadej** [comment]
Unable to recreate the problem.

Please provide more info and the issue could be reopened.
