### ISSUE TITLE
Long Legend Labels overflow into the chart

### ISSUE THREAD

**Issue by anshbansal** [highcharts/highcharts#4242]
This is happening for
-> Highcharts JS v4.0.1
-> Google Chrome Version 43.0.2357.65 unknown (64-bit)
-> Ubunutu 14.04

I am using the following options for line series.
legend: {
                align: 'right',
                verticalAlign: 'top',
                layout: 'vertical'
            },

When the legend labels are long then they overflow into the chart. And over the title also.

example of Long label -> "When the legend labels are long then"

**Comment by Johnb21** [comment]
What is the desired functionality for long legend items on a vertical layout? Would you expect them to have wrapping? Would the desired outcome be something like:

```
When the leg
end labels ar
e long then
```

**Comment by anshbansal** [comment]
Wrapping is fine. Perhaps by words? That should not look weird then. Something like below.

When the legend 
labels are long 
then

Makes sense?

**Comment by pawelfus** [comment]
I would simply set max width for that item - to avoid rendering very long series name on a small chart. For example text can have 200px width and chart will be only 150px, so in that case there wouldn't be enough space for the plotting area at all. 

Example: http://jsfiddle.net/wup2k6v1/

        legend: {
            align: 'right',
            verticalAlign: 'top',
            layout: 'vertical',
            itemStyle: {
                width: "100px"   
            }
        },

**Comment by anshbansal** [comment]
That looks good.
