### ISSUE TITLE
Add an option of straight connector for pie chart

### ISSUE THREAD

**Issue by shanSyapse** [highcharts/highcharts#4269]
I know that we have a softConnector option. For certain pie chart with limited data type, a straight line is more preferred by designers.
It seems like an easy feature improvement, as long as highcharts provide an options, that allows  removing these two following lines(removing the break point) from the path:

https://github.com/highslide-software/highcharts-release/blob/master/highcharts.src.js#L17447-L17448

**Comment by pawelfus** [comment]
Small plugin to edit that connector-path: http://jsfiddle.net/49hq2sm4/

Snippet:

    (function (H) {
        H.wrap(H.seriesTypes.pie.prototype, "drawDataLabels", function (p) {
            var x_offset = 5,
                y_offset = 12;
            
            p.call(this);

            H.each(this.points, function (p) {
                if (p.dataLabel && p.connector) {
                    console.log(p.dataLabel._pos);
                    p.connector.attr({
                        d: [
                            "M",
                            p.dataLabel._pos.x + (p.labelPos[6] === "left" ? -x_offset : x_offset),
                            p.dataLabel._pos.y + y_offset,
                            "L",
                            p.labelPos[4],
                            p.labelPos[5]
                        ]
                    });
                }
            });
        });
    })(Highcharts)

**Comment by ryanyun** [comment]
@pawelfus your plugin for straight connectors works great when the charts load once, but do you know how to make it work when the charts appear when they are visible in viewport?

In other words, do you know how to make the connectors straight in conjunction with this plugin: http://jsfiddle.net/highcharts/8YVUb/ ?

Thanks 😄

**Comment by jeerbl** [comment]
I think the `softConnector` option was made for this. See [this fiddle](http://jsfiddle.net/jb8ct0zh/1/) and [the documentation](https://api.highcharts.com/highcharts/series.pie.dataLabels.softConnector).

**Comment by kamilkulig** [comment]
Support for straight connectors was added in v7.0.0 (due to #8476).
