### ISSUE TITLE
container.ontouchmove will only be fired once under android

### ISSUE THREAD

**Issue by kaoshijuan** [highcharts/highcharts#4273]
if the browser is under android, the touchmove event will only be fired onced until another touchstart event begins.

to fix this problem, maybe you should add one line code:
e.preventDefault(); 
after the code :   pointer.onContainerTouchMove(e);

**Comment by kaoshijuan** [comment]
how about this problem ???

**Comment by pawelfus** [comment]
Duplicate of #4606
