### ISSUE TITLE
Highstock: Logarithmic + series.compare "percent"

### ISSUE THREAD

**Issue by axelnormand** [highcharts/highcharts#4276]
Hello

How might i do a logarithmic line chart with rebasing (ie series.compare as "percent")?
My jsfiddle works when you comment out the plotOptions.series.compare: "percent"

http://jsfiddle.net/axelnormand/mw8w8ea8/

Many thanks

**Comment by highslide-software** [comment]
I don't know... In a compare series, the first value will always be 0, and you will also often have negative values. How would you show that with a log axis?

**Comment by pawelfus** [comment]
It can be done, when improving built-in `log2lin` and `lin2log` functions, like this:

    function log2lin(num) {
	if(num == 0) {
		return 0;
	} else if(num < 0) {
		return -math.log(math.abs(num)) / math.LN10;;
	} else {
		return math.log(num) / math.LN10;
	}
    }
    function lin2log(num) {
	if(num == 0) {
		return 0;
	} else if(num < 0) {
		return -math.pow(10, math.abs(num));
	} else {
		return math.pow(10, num);
	}	 
    }

Methods are not accessible from the outside, so code editing would be necessary. 

Next step would be to remove limitations from the core, when throwing error 10. For Highcharts 4.1.6 it would be:

- [line 7329](https://github.com/highslide-software/highcharts.com/blob/974947dcccbadba334882c6d46adb7a3443e4426/js/highcharts.src.js#L7329]
- [line 13673](https://github.com/highslide-software/highcharts.com/blob/974947dcccbadba334882c6d46adb7a3443e4426/js/highcharts.src.js#L13673)

And remove condition for log axis here:

- [line 13612](https://github.com/highslide-software/highcharts.com/blob/974947dcccbadba334882c6d46adb7a3443e4426/js/highcharts.src.js#L13612) (after the second `&&`)

**Comment by highslide-software** [comment]
Thanks @pawelfus!. Patch here:
```diff
diff --git a/js/parts/Axis.js b/js/parts/Axis.js
index 0988198..a4ebb2d 100644
--- a/js/parts/Axis.js
+++ b/js/parts/Axis.js
@@ -912,9 +912,6 @@ Axis.prototype = {
 		}
 
 		if (isLog) {
-			if (!secondPass && mathMin(axis.min, pick(axis.dataMin, axis.min)) <= 0) { // #978
-				error(10, 1); // Can't plot negative values on log axis
-			}
 			axis.min = correctFloat(log2lin(axis.min)); // correctFloat cures #934
 			axis.max = correctFloat(log2lin(axis.max));
 		}
diff --git a/js/parts/Series.js b/js/parts/Series.js
index b653709..a798b6c 100644
--- a/js/parts/Series.js
+++ b/js/parts/Series.js
@@ -690,7 +690,7 @@ Series.prototype = {
 
 			// For points within the visible range, including the first point outside the
 			// visible range, consider y extremes
-			validValue = y !== null && y !== UNDEFINED && (!yAxis.isLog || (y.length || y > 0));
+			validValue = y !== null && y !== UNDEFINED;
 			withinRange = this.getExtremesFromAll || this.options.getExtremesFromAll || this.cropped ||
 				((xData[i + 1] || x) >= xMin &&	(xData[i - 1] || x) <= xMax);
 
@@ -750,12 +750,6 @@ Series.prototype = {
 				pointStack,
 				stackValues;
 
-			// Discard disallowed y values for log axes (#3434)
-			if (yAxis.isLog && yValue !== null && yValue <= 0) {
-				point.y = yValue = null;
-				error(10);
-			}
-
 			// Get the plotX translation
 			point.plotX = plotX = mathMin(mathMax(-1e5, xAxis.translate(xValue, 0, 0, 0, 1, pointPlacement, this.type === 'flags')), 1e5); // #3923
 
diff --git a/js/parts/Utilities.js b/js/parts/Utilities.js
index 60f5a2a..d8d07ca 100644
--- a/js/parts/Utilities.js
+++ b/js/parts/Utilities.js
@@ -110,10 +110,22 @@ function isNumber(n) {
 }
 
 function log2lin(num) {
-	return math.log(num) / math.LN10;
+  if(num == 0) {
+    return 0;
+  } else if(num < 0) {
+    return -math.log(math.abs(num)) / math.LN10;;
+  } else {
+    return math.log(num) / math.LN10;
+  }
 }
 function lin2log(num) {
-	return math.pow(10, num);
+  if(num == 0) {
+    return 0;
+  } else if(num < 0) {
+    return -math.pow(10, math.abs(num));
+  } else {
+    return math.pow(10, num);
+  }  
 }
 
 /**
```

The original post's chart now looks like this:
![chart 11](https://cloud.githubusercontent.com/assets/227836/8207316/fa4453c6-1500-11e5-82bd-8ffd82ffbb39.png)

The problem (which is not technical, but more theoretical), is that the axis is not logarithmic anymore. In a logarithmic axis, each full tick is a tenth of the previous. So in the image, we start at 100 000, next tick down is 10 000, then 1000, 100 and 10. Then we would expect the next ticks down to be 1, 0.1, 0.01, 0.001 etc. A logarithmic axis will never reach zero.

**Comment by highslide-software** [comment]
... And a couple of useful resources:
* [GraphPad's note on the same issue](http://www.graphpad.com/guides/prism/6/user-guide/index.htm?logarithmic_axes_cannot_contai.htm). The tick formatting hack can probably be used in Highcharts too.
* [Log axes in Excel](https://support.office.com/en-nz/article/Change-the-scale-of-the-vertical-value-axis-in-a-chart-0bca495a-d4b8-45ae-8819-b38372736146). "NOTE   A logarithmic scale cannot be used for negative values or zero."

**Comment by axelnormand** [comment]
Thank you so much everyone! Will be trying this out very soon

**Comment by axelnormand** [comment]
Per chance is this (ie log scale with rebasing) now possible in the latest highcharts release?
Many thanks for all the replies previously.
