### ISSUE TITLE
tooltip appears in Chrome not in Firefox

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4277]
Tooltip doens't appear in the newest Firefox for point with small value.

Example: http://jsfiddle.net/me3bqv8n/

**Comment by pawelfus** [comment]
Two possible workarounds:

- set `tooltip.shared = true`: http://jsfiddle.net/me3bqv8n/1/
- set `series.minPointLength = 10+`: http://jsfiddle.net/me3bqv8n/2/

**Comment by sebastianbochan** [comment]
+1
