### ISSUE TITLE
Tooltip headerFormat substitution doesn't work in 3D scatter 

### ISSUE THREAD

**Issue by happylynx** [highcharts/highcharts#4281]
Issue demo: http://jsfiddle.net/crk9v6tk/, it's altered example from http://www.highcharts.com/demo/3d-scatter-draggable. My result (in Firefox 38):
![3d_scatter](https://cloud.githubusercontent.com/assets/8846779/8149027/2d7e05fe-12b6-11e5-9301-815133a27c5f.png)

Substitution of `{point.color}` and `{point.foo}` in following example fails.

```
tooltip: {
    headerFormat: 'header color: <span style="color: {point.color}">\u2588</span>, foo: {point.foo}<br/>'
}
```

**Comment by highslide-software** [comment]
It's not only in 3d, it can be simplified to this: http://jsfiddle.net/highcharts/crk9v6tk/3/

Since the tooltip can show multiple points (through the _shared_ option), the actual point is nested one level below. So this works: 

```js
tooltip: {
    headerFormat: 'header color: <span style="color: {point.point.color}">\u2588</span>, foo: {point.point.foo}<br/>'
}
```

**Comment by KacperMadej** [comment]
This could be resolved though adding a simple comment for [`headerFormat`](https://api.highcharts.com/highcharts/tooltip.headerFormat).

There's already this:

> The HTML of the tooltip header line. Variables are enclosed by curly brackets. Available variables are point.key, series.name, series.color and other members from the point and series objects. The point.key variable contains the category name, x value or datetime string depending on the type of axis. For datetime axes, the point.key date format can be set using tooltip.xDateFormat.

Adding below could resolve the issue:

> To access the original point use `point.point`.
