### ISSUE TITLE
Stack chart : Y Axis stack label behavior when data is null

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#4294]
Please check below url:

Y Axis stack label is shown as 0 when stacked value are null.

http://jsfiddle.net/pawanvjadhav/42gu66eg/1/

I think, we should not display 0, it tells values of stacked series for category "feb" is are 0 . We should display empty stack label.

**Comment by pawelfus** [comment]
I think there was opposite issue reported - that null points should display stack label anyway.. 
I would simply remove null points, and use `[x, y]` format for points. Then Highcharts will not generate that label, see: http://jsfiddle.net/42gu66eg/2/

**Comment by pawanvjadhav** [comment]
If i have to integrate this change, i have to change whole highchart dataset creation logic.

I think, showing zero may mislead the person who is analyzing. When you plot chart for sales, showing zero will be different meaning.

Cant we make this configurable? Like, connectNulls property

**Comment by highslide-software** [comment]
There seems to be a history here - in 3.0.1, the null totals were not rendered. Then in 7994fa2, the `stackLabels` format option was introduced, and null unintentionally rendered as 0. Later on, the stack.total actually became 0, so in the current release we can't see that the stack has nulls.

In short, this in not intentional. In my opinion it should be optional.

**Comment by highslide-software** [comment]
#### Workaround
Use the `stackLabels.formatter` to inspect for null values.
```js
                formatter: function () {
                    var hasNulls,
                        point,
                        series = this.axis.chart.series;
                    for (point in this.points) {
                        if (this.points.hasOwnProperty(point)) {
                            point = point.split(',');
                            point = series[point[0]].options.data[point[1]];
                            if (point === null) {
                                hasNulls = true;
                                break;
                            }
                        }
                    }
                    return hasNulls ? 'N/A' : this.total;
                }
```
[View it live on jsFiddle](http://jsfiddle.net/highcharts/42gu66eg/3/).

**Comment by highslide-software** [comment]
This patch adds a flag, `hasNulls` to the stack, and picks it up in the default formatter in compliance with how it is done on data labels. Now if you want to print something else, you can use the formatter. Does this seem okay for you? One other thing we need to test is that the hasNulls flag is updated on dynamically modifying the data.

```diff
diff --git a/js/parts/Axis.js b/js/parts/Axis.js
index 0988198..47ea5c0 100644
--- a/js/parts/Axis.js
+++ b/js/parts/Axis.js
@@ -134,7 +134,7 @@ Axis.prototype = {
 			//textAlign: dynamic,
 			//rotation: 0,
 			formatter: function () {
-				return Highcharts.numberFormat(this.total, -1);
+				return this.hasNulls ? '' : Highcharts.numberFormat(this.total, -1);
 			},
 			style: merge(defaultPlotOptions.line.dataLabels.style, { color: '#000000' })
 		}
diff --git a/js/parts/Stacking.js b/js/parts/Stacking.js
index ef16043..987c8df 100644
--- a/js/parts/Stacking.js
+++ b/js/parts/Stacking.js
@@ -253,6 +253,9 @@ Series.prototype.setStackedPoints = function () {
 		stack.points[pointKey].push(stack.cum);
 		stackedYData[i] = stack.cum;
 
+		if (y === null) {
+			stack.hasNulls = true;
+		}
 	}
 
 	if (stacking === 'percent') {
```

**Comment by pawanvjadhav** [comment]
Yes this will help. If i get flexiblity as, what to show when all values are null. As few people says, N/A, 0, Empty.


Are you going to add this in your release?

**Comment by pawanvjadhav** [comment]
Any update?

**Comment by highslide-software** [comment]
> If i get flexiblity as, what to show when all values are null. As few people says, N/A, 0, Empty.

Yes, you'll get that through the formatter. We're not sure yet whether to implement it. We also need to consider what to do when we have some valid data points and some null. 

Under any circumstance, you can use the workaround.

**Comment by highslide-software** [comment]
Updated diff: https://gist.github.com/highslide-software/a9759e7b54af718ca396

**Comment by nauris-m** [comment]
is there any workaround for this or any changes in newer versions (i'm using 602) ? I'd like to show stacked label as 'n/a' when data is null. above mentioned solutions are not really working. Thanks!

**Comment by pawelfus** [comment]
You can use [`annotations`](https://api.highcharts.com/highcharts/annotations.labels) module and render an annotation in that empty place: http://jsfiddle.net/BlackLabel/x2hpvd1m/

```
    annotations: [{
      labels: [{
        point: {
          x: 1,
          y: 0,
          xAxis: 0,
          yAxis: 0
        },
        text: 'N/A'
      }]
    }],
```

First you need to check if any x-stack has empty elements of course.
