### ISSUE TITLE
Solidgauge: yAxis update with minColor, maxColor or stops options do not update series color

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4300]
Example with minColor and maxColor: http://jsfiddle.net/ctpuzk42/

Example with stops: http://jsfiddle.net/ctpuzk42/1/

**Comment by pawelfus** [comment]
**Workaround**:

Bind axes again after updating axis:


        chart.yAxis[0].update({
            minColor: '#00ff00',
            maxColor: '#0000ff'
        }, false); //redraw = false -> performance
        chart.series[0].data[0].update(4, false); //redraw = false -> performance
        chart.series[0].bindAxes(); // workaround
        chart.redraw(true); //animation = true

And demos: 

- http://jsfiddle.net/ctpuzk42/2/
- http://jsfiddle.net/ctpuzk42/3/

**Comment by flc85** [comment]
Why if i put:
yAxis: {
            min: 0,
            max: 30,
i see 25 in the gauge

**Comment by pawelfus** [comment]
Hi @flc85,

For support questions, please check [this](http://www.highcharts.com/support).

**Comment by KacperMadej** [comment]
Works fine when using Highcharts version 7.1.2.
Closing as resolved.
