### ISSUE TITLE
Interactive legend and Y Axis scale calculation

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#4306]
if we dont set max property of Y Axis and if we hide all series plotted on that Y Axis using iteractive legend, highchart automatically hides Y axis. Same doesn't happen when we set max property of Y Axis and if we hides all series plotted on that Y Axis using interactive legend.

Any reason for keeping this difference?

**Comment by pawelfus** [comment]
See #705 ticket.

**Comment by pawanvjadhav** [comment]
Ok got it.

 are you going to add this as configuration?

**Comment by pawanvjadhav** [comment]
Any comment / update?

**Comment by KacperMadej** [comment]
Closing as a duplicate of #705
