### ISSUE TITLE
rangeSelector doesn't respect UTC setting

### ISSUE THREAD

**Issue by four43** [highcharts/highcharts#433]
The rangeSelector seems to select the range - local time offset. I'm using UTC: true and offsetting my data server-side before sending my data to the chart. For example, if I set the date to today. It will set it to 5AM this morning. The expected result is 12AM today, since the data is already localized.

**Comment by kakoni** [comment]
Getting into this old issue;
```
if (!defaultOptions.global.useUTC) {
  value = value + new Date().getTimezoneOffset() * 60 * 1000;
}
```
Doesnt take into account that TimezoneOffset differs during the year(daylight savings...)
Example (using moment)
```
moment.tz.zone('Europe/Helsinki').offset(1403465838805)
-180
moment.tz.zone('Europe/Helsinki').offset(1388563200000)
-120
```

So you would need something like
```
value = value + moment.tz.zone(SUPPLIED).offset(value) * 60 * 1000;
```

**Comment by adamwehmann** [comment]
@TorsteinHonsi... 

Following up @kakoni's comment, when:

```
global: {
  useUTC: false
}
```

then
```
rangeSelector: {
  inputDateFormat: '%Y-%m-%d',
  inputEditDateFormat: '%Y-%m-%d',
  inputDateParser: function (value) {
    var temp_date = new Date(value);
    var temp_utc = temp_date.valueOf();
    temp_utc = temp_utc + (temp_date.getTimezoneOffset() - new Date().getTimezoneOffset()) * 60 * 1000;
    return temp_utc;
  }
}
```

seems to be a currently necessary workaround for DST.
