### ISSUE TITLE
Cateogry type axis - zooming into below set min

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4332]
When type of axis is category it is possible to zoom below axis' min.
Min is set to 0. When zooming in via selecting shape of height about 1.5 of category height at the bottom of a chart (start at middle of 'b' category - level with label - and end at the bottom), min (axis extreme) is being set to -0.5

Example: http://jsfiddle.net/6xfsfc2y/

Label '-1' is visible in zoomed-in chart, still visible in zoomed-out and out side of y axis.

Partial workaround: set min to 0.01 - http://jsfiddle.net/6xfsfc2y/1/

**Comment by pawelfus** [comment]
`min: 0.01` works, but not always, see:

![screen shot 2015-07-21 at 4 07 55 pm](https://cloud.githubusercontent.com/assets/1453926/8802600/d19834b0-2fc2-11e5-8d65-89c5b25c46be.png)

Another workaround is to use `tickPositioner`: http://jsfiddle.net/6xfsfc2y/2/

            tickPositioner: function (min, max) {
                var interval = 1,
                    ticks = [];

                min = Math.max(Math.floor(min), 0);
                ticks.push(min);
                
                while (min < max) {
                    min += interval;
                    ticks.push(min);
                }
                return ticks;
            }
