### ISSUE TITLE
Waterfall - minPointLength doens't work

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4338]
Example: http://jsfiddle.net/8j7L5ufj/1/

**Comment by iddofontijn** [comment]
When will this fix be released?

**Comment by TorsteinHonsi** [comment]
It is now merged into the master, will be released with the next maintenance.

**Comment by iddofontijn** [comment]
There still seems to be a problem with negative values: http://jsfiddle.net/8j7L5ufj/4/
When a negative point uses the minPointLength, it adds up to the total bar height.

**Comment by pawelfus** [comment]
Thank you for pointing this out!

**Comment by znevrly** [comment]
Hi, any update with this? Thank you much.
