### ISSUE TITLE
xAxis update breaks, set's xAxis ordinal to false

### ISSUE THREAD

**Issue by grzesiekgs** [highcharts/highcharts#4342]
1. Click "update ordinal" - xAxis.ordinal changes to true
2. Click "update breaks" - empty array of breaks is applied, xAxis.ordinal changes to false ( or at least it looks like that )

Also happens when trying to set both in one update.

http://jsfiddle.net/ycL16q9f/9/

Edit : Also happens with Highstock 2.1.5

**Comment by sebastianbochan** [comment]
Better demo: http://jsfiddle.net/ycL16q9f/12/

**Comment by sebastianbochan** [comment]
+1

**Comment by highslide-software** [comment]
Currently this is deliberate. As seen in [this code block](https://github.com/highslide-software/highcharts.com/blob/v4.1.7/js/modules/broken-axis.src.js#L95-L98), axes are made non-ordinal when breaks are applied.
