### ISSUE TITLE
JSFiddle API examples no longer work

### ISSUE THREAD

**Issue by tomascassidy** [highcharts/highcharts#4352]
The JSFiddle API examples are referencing files on http://code.highcharts.com.  JSFiddle now only serves content over HTTPS which is causing the fiddles to fail as recent browser versions block loading mixed active content (http resources on a https page).

The JSFiddle examples all need to be updated to reference https://code.highcharts.com.

I've also noticed that https://code.highcharts.com fails to load http://www.highcharts.com/joomla/templates/highsoft_colorful/css/template.css, and also shows a browser console warning for http://www.highcharts.com/templates/highsoft_colorful/images/logo.svg due to the mixed active content.  All URLs for https://www.highcharts.com appear to be redirecting back to http://www.highcharts.com so that would need to be addressed too in order to load those assets from https://code.highcharts.com.

**Comment by highslide-software** [comment]
> JSFiddle now only serves content over HTTPS

I can't reproduce that. When I go to the API and click the link, I am taken to HTTP content: http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/alignticks-true/

**Comment by tomascassidy** [comment]
Hmmm. Could be the HTTPS-Everywhere browser extension switching it for me. I'll have to do some testing on that.

**Comment by highslide-software** [comment]
Thanks. Though I see an increasing amount of fiddles from users are using https, so there is something going on. Maybe those users all have that browser extension.

**Comment by tomascassidy** [comment]
I also noticed that a Google search for "jsfiddle" shows the HTTPS url as the top result so that might also contribute to what you're seeing.

**Comment by highslide-software** [comment]
Yes that may be the case.

As an internal note, we also need to change other links in the samples if we do this. Some links to CDNs like Google API or code.jquery.com probably support protocol agnostic links already, but www.highcharts.com does not, so we need to add support for HTTPS there.

**Comment by tomascassidy** [comment]
I can confirm that the HTTPS-Everywhere browser extension is doing the automatic redirection from HTTP to HTTPS for jsfiddle.  Disabling the browser extension prevents the redirect happening.

**Comment by highslide-software** [comment]
Thanks

**Comment by jon-a-nygaard** [comment]
All  the files in our demos are now served over https

**Comment by jwfx** [comment]
With HTTPS now becoming default in Browsers like Chrome this became an issue again.

https://www.highcharts.com/docs/chart-concepts/series

All links here point to the http version of jsfiddle which is causing chrome to show the following error in the jsfiddle render window: 
"Chrome detected unusual code on this page and blocked it to protect your personal information (for example, passwords, phone numbers, and credit cards)."

If the URL is changed to https://jsfiddle.... everything starts working fine.

**Comment by jon-a-nygaard** [comment]
@jwfx Thanks for reporting! I have fixed the links on https://www.highcharts.com/docs/chart-concepts/series

Will see if I can find a way to detect the remaining references to http url's.

**Comment by jwfx** [comment]
@jon-a-nygaard 
Any chance you could also look at all jsfiddle links from https://api.highcharts.com/highcharts/ ?
They are suffering from the same problem.
