### ISSUE TITLE
In IE8, the click event of series chart's point doesn't work

### ISSUE THREAD

**Issue by smallyard** [highcharts/highcharts#4363]
In IE8, the click event of  bubble chart's point don't work.
version:4.1.7

**Comment by pawelfus** [comment]
Demo: http://jsfiddle.net/aasuo16n/3/

Workaround: disable halo effect: http://jsfiddle.net/aasuo16n/6/

**Comment by pawelfus** [comment]
It's general issue, not connected to the series type, but halo effect only: http://jsfiddle.net/aasuo16n/9/

**Comment by liuhongqiang** [comment]
@pawelfus Thank you very much.
