### ISSUE TITLE
Highstock select point issue

### ISSUE THREAD

**Issue by AlexKovalevych** [highcharts/highcharts#4367]
I need to be able to select points at the highstock, but when selected point loses focus - it returns to default state.

http://jsfiddle.net/7jywwsbg/

**Comment by AlexKovalevych** [comment]
It seems like select styles are not applied to the point for some reason, instead point has no style at all.

**Comment by highslide-software** [comment]
#### Workaround
Enable markers in normal state, and optionally give them a small radius to hide them: http://jsfiddle.net/highcharts/7jywwsbg/2/

**Comment by AlexKovalevych** [comment]
Thank you for your temp solution.
