### ISSUE TITLE
Incorrect column 3d when reversedStacks enabled

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4369]
Example: http://jsfiddle.net/k0rfv8bw/6/

Without reversedStacks, chart is printed properly.

**Comment by highslide-software** [comment]
Actually there's a Z index problem also without reversedStacks. The oranges are drawn on top of the pears.

**Comment by pawelfus** [comment]
Screenshot for overlapping bars (without reversedStacks):
![screen shot 2015-07-20 at 10 19 56 am](https://cloud.githubusercontent.com/assets/1453926/8772073/ea96e06a-2ec8-11e5-9d15-28a65ca039d2.png)

I think this is more complicated problem - right now, each series is stored in a different group, while we need to have distinct zIndexes within the same series for bars **and** within different groups. I'm not sure if SVG is capable of doing that without changing logic to render each of the bars separately.

**Comment by pawelfus** [comment]
I would consider creating separate ticket for overlapping columns.

**Comment by highslide-software** [comment]
> I'm not sure if SVG is capable of doing that without changing logic to
render each of the bars separately.​

It probably means we would have to split up the series groups.

**Comment by sebastianbochan** [comment]
+1

**Comment by pawelfus** [comment]
After merging this commit and adding the one from #3737 - above issues show up again. Master branch: http://jsfiddle.net/k0rfv8bw/12/

**Comment by pawelfus** [comment]
I wasn't able to reproduce use case, when [these lines](https://github.com/highcharts/highcharts/blob/a36cfefc797de2dd8dcbacda6d32afe2ffdce5fe/js/parts-3d/Column.js#L116-L118) are necessary (tested on: http://jsfiddle.net/k0rfv8bw/13/ ). @TorsteinHonsi do you have one?

**Comment by sebastianbochan** [comment]
Seems that inverted charts are not printed properly: http://jsfiddle.net/Akixi/agw1e5Ls/

**Comment by ShoresOfNowhere** [comment]
I add my example to this bug:

http://www.faromed.it/_hcbugs/BadSeriesZindex.htm

As you can see, botth on the right and on the left of the chart the stacking of serier in a single bar AND the stacking of bars on each other are badly wrong...

**Comment by ShoresOfNowhere** [comment]
Sorry, might I ask when this bug will be resolved?

**Comment by Izothep** [comment]
This issue looks to be resolved through 6f84253

demos:
http://jsfiddle.net/k0rfv8bw/14/

http://jsfiddle.net/agw1e5Ls/4/

**Comment by ShoresOfNowhere** [comment]
Mmm, so this is fixed in highcharts 5.x, but will the fix be ported also on 4.2.7?

A client of mine has that version's license, and is experiencing the bug...

**Comment by Izothep** [comment]
Hi!

It should be possible to wrap prototype 3d functions so you will be able to add this functionality in Highcharts 4.2.7 version:

very simple example how this wrap may work:
http://jsfiddle.net/68ney7ya/

**Comment by ShoresOfNowhere** [comment]
I think this bug is NOT resolved even in the latest github master version:

This is the chart rendered with 4.2.7:

https://www.faromed.it/_hcbugs/BadSeriesZindex_v4.htm

This is the chart rendered with the latest github master:

https://www.faromed.it/_hcbugs/BadSeriesZindex.htm

If you wait a minute for the chart to load, you'll see that while on the left side the newer version does a better job, on the right one there are still plenty of absurd z-index errors...

Any indication of when will this be solved?

**Comment by Izothep** [comment]
Hi!

Thank you for your message and for live example showing your issue. We will analyse this problem and try to find a fix for your current problem related to column zIndex.

**Comment by ShoresOfNowhere** [comment]
Bug is still present in 7.1.1...

**Comment by Izothep** [comment]
Thank you for the message and please take my apologies for waiting so long. I am reopening this issue.

**Internal**: The problem with current zIndex issue for such wide screen looks to be related with current zIndexing approach, where point-camera distance in specific dimension multiplied by dimension-related factor sum up into the final zIndex.
