### ISSUE TITLE
Exporting context button does not close when clicked.

### ISSUE THREAD

**Issue by WilliamBaldwinIII** [highcharts/highcharts#4377]
After opening the exporting context button, it does not close when clicked as would be expected. I have a fix!

If we add the line of code: 

``` js
// Hide it on clicking on the context menu button again.
addEvent(menu, 'click', hide);
```

on line 527 right after 

``` js
// Hide it on clicking or touching outside the menu (#2258, #2335, #2407)
addEvent(document, 'mouseup', docMouseUpHandler);
addEvent(chart, 'destroy', function () {
    removeEvent(document, 'mouseup', docMouseUpHandler);
});
```

in the contextMenu function of exporting.js, it fixes the issue.

**Comment by gvaartjes** [comment]
Please explain what you're expecting to be default behaviour.

Now it supposed to close when:
1. You pressed a menu item, like 'Download as PNG'
2. When you click outside the export menu

If this isn't the case please report also your browser + version

**Comment by WilliamBaldwinIII** [comment]
I would expect default behavior to be closing when I click on the context button again.

For example, in Google Chrome, if we click the context button at the top right, the menu opens. If we click it again, the menu closes.

**Comment by gvaartjes** [comment]
Ok, I see your point. Thanks

**Comment by gvaartjes** [comment]
Add an eventhandler to the button, when the user clicks the export context button the menu is expected to disappear.

**Comment by aviramga** [comment]
I still have this issue so I guess this wasnt fixed yet :)
Is there a workaround for now?

**Comment by pawelfus** [comment]
Yes, this issue is still open.

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/06nbf9uw/

Plugin:
```javascript
(function(H) {
  H.wrap(H.Chart.prototype, 'contextMenu', function(proceed, className) {
    var chart = this,
      name = 'cache-' + className,
      menu = chart[name],
      isNew = !menu;

    // Call default method:
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));

    menu = chart[name];

    // Add event only once:
    if (isNew && menu) {

      chart.exportEvents.push(
        H.addEvent(menu, 'click', function() {
          var menu = chart['cache-highcharts-contextmenu'];
          if (menu && chart.openMenu) {
            // Hide context menu:
            chart.openMenu = false;
            H.css(menu, {
              display: 'none'
            });
          }
        })
      );
    }
  });
})(Highcharts);
```
