### ISSUE TITLE
addSeries not working for Map

### ISSUE THREAD

**Issue by pajooh** [highcharts/highcharts#4379]
[jsfiddle](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/maps/members/chart-addseries/)

**Comment by pawelfus** [comment]
Workaround: initialize chart with series array: http://jsfiddle.net/cx457uxt/

**Comment by pajooh** [comment]
@pawelfus thank you, but the provided workaround is not working.
@gvaartjes even the provided jsfiddle is not working, did you checked it?!

**Comment by pawelfus** [comment]
Well, it works for me. Just click on the button?

**Comment by pajooh** [comment]
clicking the button just updates the legend (adding labels for 1, 10, 100 and 1k), nothing more
I tested both in firefox and chrome.

**Comment by pawelfus** [comment]
Ok, works fine for both, FF and Chrome, on OSX. 
Works fine on Chrome, on Windows 7.
Workaround doesn't work in Firefox on Windows 7.

**Comment by pajooh** [comment]
I'm using a Linux box, both of FF/Chrome doesn't work

**Comment by highslide-software** [comment]
Tested the original fiddle it works correctly on the following systems:
* Firefox 35 on Windows 7
* Firefox 38 on Ubuntu 15.04
* Firefox 39 on Ubuntu 15.04
* Chrome 44 Beta on Ubuntu 15.04

**Comment by sebastianbochan** [comment]
Closing this issue since it is pending a reply. Should anyone have further information on the issue, please give us a comment.
