### ISSUE TITLE
rangeSelector shows more data than expected (with workaround)

### ISSUE THREAD

**Issue by rninne** [highcharts/highcharts#4380]
Issue: http://jsfiddle.net/5kr6y5k5/1/

When working with monthly data, the range selector ofter shows n + 1 periods. Using the example above click on 1m. You will see 2 months of data shown. The same is true when selecting 1y. 13 months of data are shown.

If you click on 6m however it works (at least for the period ending at march 2016) I believe this has to do with daylight savings, if you look at the value in the range selector input box you will see **Sep 1 2015 01:00:00.000**. If this value was correct for UTC it should be **Sep 1 2015 00:00:00.000** and you would also see september in the graph. I believe the UTC issue is what also causes https://github.com/highslide-software/highcharts.com/issues/4147

Workaround: http://jsfiddle.net/5kr6y5k5/3/

While the workaround works well for months in the middle of the xAxis, it doesn't work very well at the edges of the xAxis (who want's to just see one month anyway?).

Changed section of RangeSelector.clickButton

``` javascript
// Apply range
if (type === 'month' || type === 'year') {
    timeName = { month: 'Month', year: 'FullYear'}[type];
    date.setUTCHours(0);
    date.setUTCMinutes(0);
    date.setUTCSeconds(0);
    date.setUTCMilliseconds(0);
    date.setDate(1);
    newMax = date.getTime();
    count--;
    if(type === 'year')
        count = count == 0 ? 1 : count;
    date['set' + timeName](date['get' + timeName]() - count);
    date.setUTCHours(0);
    date.setUTCMinutes(0);
    date.setUTCSeconds(0);
    date.setUTCMilliseconds(0);
    newMin = date.getTime();

    dataMin = pick(dataMin, Number.MIN_VALUE);
    if (isNaN(newMin) || newMin < dataMin) {
        newMin = dataMin;
        newMax = mathMin(newMin + range, dataMax);
    } else {
        range = newMax - newMin;
    }

// Fixed times like minutes, hours, days
} else if (range) {
```

**Comment by pawelfus** [comment]
I'm not sure if this is bug, but probably it would be a good idea to be the first point exclusive within the range. 

Another workaround will be to play around with values for range selector buttons: http://jsfiddle.net/5kr6y5k5/4/

**Comment by rninne** [comment]
There are still some issues with your proposed workaround.
![screen shot 2015-07-13 at 6 29 44 pm](https://cloud.githubusercontent.com/assets/1142677/8645728/33072814-298d-11e5-978d-94c612e2248d.JPG)
![screen shot 2015-07-13 at 6 31 16 pm](https://cloud.githubusercontent.com/assets/1142677/8645742/6376a420-298d-11e5-84d9-ebf9eb99c243.JPG)

I guess I'm expecting when there is only monthly data (or when the month buttons are used), that the range selector will *snap* to the month ticks, and not show half periods.

Think there is definitely a UTC / daylight savings issue here regardless as I'm seeing **Oct 1 2015 01:00:00.000** in the range input when I load that fiddle and click 6m (screenshot 1) only showing 5 months.

**Comment by gvaartjes** [comment]
I simplified the demo on JSFiddle, see http://jsfiddle.net/mdess0qx/

Selecting __6m__ in the range selector shows 7 months of data instead of 6.

**Comment by rninne** [comment]
@gvaartjes just be aware that that fiddle works fine for me! So I'm my suspicions are mounting that it's a timezone thing. I'm in AEST.

![screen shot 2015-07-13 at 11 36 03 pm](https://cloud.githubusercontent.com/assets/1142677/8650756/1fef7fd0-29b8-11e5-91d7-ac0a1ca89af1.JPG)

**Comment by gvaartjes** [comment]
Thanks!

**Comment by highslide-software** [comment]
The explanation to this behaviour is that the column points have a specific timestamp for X value, which is exactly at midnight in the given month. In http://jsfiddle.net/5kr6y5k5/1/, when you press the 1M button, the X axis shows points between 2015-02-01 00:00:00 and 2015-03-01 00:00:00, which is of course one month. The only problem is that there are actually two columns within that range, both the one for February and the one for March.

If we look at the same demo with a line series instead, it probably makes more sense: http://jsfiddle.net/highcharts/5kr6y5k5/5/.

**Comment by rninne** [comment]
Hi Torstein,

Thanks for the example and explanation, I understand. It's just not what I was expecting. I guess I was expecting that when the frequencies of the range button and the series match, then the range selector would use (and possibly "snap" to) those units. e.g. Monthly data selecting 3m only shows 3 data points and snaps the range selector to the start and end of those months. I realise that this may be a limitation on how the range selector does things, as it deals in milliseconds however the time between my points no longer matters, I not concerned about days or milliseconds.

> when you press the 1M button, the X axis shows points between 2015-02-01 00:00:00 and 2015-03-01 00:00:00

This is probably a philosophical question but shouldn't the x axis then show points between 2015-02-01 00:00:00 and 2015-02-28 23:59:59:999 when you press the 1M button?

How can we explain the differences in points @gvaartjes and I were seeing on the same example? He would see 6 points, I would see 7. Is it indeed a timezone issue?

Thanks!

**Comment by highslide-software** [comment]
> This is probably a philosophical question

That's a good way of describing it :) But when the last point is March and you click 1M, you would expect that February is not included, so basically you don't want to include the point that sits exactly on the axis minimum.

I experimented with doing this in the cropData method, but it has unwanted results for 1M and 6M: http://jsfiddle.net/highcharts/5kr6y5k5/6/

**Comment by giko45** [comment]
(function (H) {
    H.wrap(H.Axis.prototype, 'getExtremes', function (proceed) {

        xExtremes = proceed.apply(this, Array.prototype.slice.call(arguments, 1));
        if (this.coll === "xAxis" && this.series[0].hasGroupedData) {
        	var u = this.series[0].currentDataGrouping.unitRange;
                xExtremes.min = xExtremes.min-u;
                xExtremes.max = xExtremes.max+u*2;

        }
        return xExtremes;
    });
}(Highcharts));

**Comment by giko45** [comment]
sorry ds'nt work, need to hack highstock.js processData

            if (xAxis) {
                xExtremes = xAxis.getExtremes(); // corrected for log axis (#3053)
//ADDED-->
                if (series.hasGroupedData) {
                    var u = series.currentDataGrouping.unitRange;
                    min = xExtremes.min -u;
                    max = xExtremes.max +u*2 ;
                }
//<---ADDED
            }

**Comment by srivatsavap** [comment]
Please let me know workaround in angular as black.

**Comment by srivatsavap** [comment]
Please let me know workaround in angular as black.

**Comment by sebastianbochan** [comment]
Hi @srivatsavap,
Please let me know if which HC wrapper do you use in angular?

**Comment by srivatsavap** [comment]
http://jsfiddle.net/highcharts/5kr6y5k5/6/

**Comment by sebastianbochan** [comment]
Hi @srivatsavap 
Please let me know which angular-wrapper do you use? I mean our tool https://www.npmjs.com/package/angular-highcharts, highcharts-ng or any different.

**Comment by sebastianbochan** [comment]
Hi @srivatsavap,
Could you supply us a valuable feedback with answer for our questions?

**Comment by sebastianbochan** [comment]
Closed due to inactivity. Please reopen if any further details will be available.
