### ISSUE TITLE
Heatmap sometimes get an extra category for category axis that isn't part of the dataset

### ISSUE THREAD

**Issue by kivle** [highcharts/highcharts#4385]
Reproduced here:

http://jsfiddle.net/kivle/61343dsm/

The category "22" does not exist anywhere in the dataset, and isn't part of the category array for the y-axis. The "22" category disappears if you change the height/width to for instance 700x800.

**Comment by pawelfus** [comment]
Do we need to use specific browser Looks fine on Chrome + OSX: 

![screen shot 2015-07-13 at 3 27 03 pm](https://cloud.githubusercontent.com/assets/1453926/8650535/a5b0f562-2973-11e5-86fb-d3195853c502.png)

**Comment by kivle** [comment]
Very strange. I'm on Chrome on Windows, and it looks like this:

![image](https://cloud.githubusercontent.com/assets/1041049/8650587/15a3a6bc-2974-11e5-9480-dda4cd49f78b.png)

I've also reproduced the same problem in IE.

**Comment by sebastianbochan** [comment]
Workaround:
Use tickPositioner to return ticks. 

Example: http://jsfiddle.net/61343dsm/4/

Internal note: For replication, you need zoom in and then zoom out.

**Comment by kivle** [comment]
Thanks for the workaround! This looks much better. I'll implement it in our application.

**Comment by pawelfus** [comment]
Universal test case: http://jsfiddle.net/38pvL4cb/9/ - issue comes from categorized yAxis, not from the heatmap itself.

**Comment by pawelfus** [comment]
Just checked the root of the problem: it's cased by different default option for yAxis and xAxis: `endOnTick`. Solved demo: http://jsfiddle.net/61343dsm/5/
