### ISSUE TITLE
Shims for globals

### ISSUE THREAD

**Issue by joshhornby** [highcharts/highcharts#4389]
I am trying to use this amazing library in a React isomorphic application, I am getting errors that document isn't defined. 

This package attempts to solve the issue https://github.com/jessegavin/highstock-module Is this something that could be pulled in to the main repo?

Could also be related to https://github.com/highslide-software/highcharts.com/issues/3616

**Comment by gvaartjes** [comment]
Thanks will we look into it.  Please take into account a bit longer response time, due to this vacation period

**Comment by joshhornby** [comment]
@gvaartjes Any update on this?

**Comment by highslide-software** [comment]
@jon-a-nygaard Can you check this out?

**Comment by TorsteinHonsi** [comment]
With Highcharts 4.2, coming up this week, you can pass in the window object as an argument to require. This allows sending in for example a `jsdom` window.

The following code will not throw errors, but it won't actually produce SVG content either:
```js
var jsdom = require('jsdom');


var doc = jsdom.jsdom('<!doctype html><html><body><div id="container"></div></body></html>');
var win = doc.defaultView;

var Highcharts = require('./js/highcharts.src')(win);

require('./js/modules/exporting.src')(Highcharts);


Highcharts.chart('container', {
	series: [{
		data: [1, 3, 2, 4]
	}]
});
```
