### ISSUE TITLE
Shared tooltip ordering of series doesn't reverse with axis swap, but bars do

### ISSUE THREAD

**Issue by smithk58** [highcharts/highcharts#4394]
This might be intentional, but it seems nonsensical so I thought I would bring it up in case it was just overlooked.

When you swap x/y axis in highcharts it orders the bars by index, starting closest to the origin. However, it doesn't follow this logic for a shared tooltip on a swapped axis chart.

This results in odd cases like this http://jsfiddle.net/0wgLtpLv/2/ (bar) or http://jsfiddle.net/0wgLtpLv/3/ (inverted column), where the tooltip looks backwards when compared to the actual data set you're hovering over. If the bars are ordered that way, shouldn't the tooltip be ordered like that as well? Or shouldn't there at least be an option for their 'direction' to match?

**Comment by pawelfus** [comment]
Another example: http://jsfiddle.net/0wgLtpLv/4/ 
Workaround: reverse points in tooltip, when `tooltip.reversed` is set:  http://jsfiddle.net/0wgLtpLv/5/

Snippet:

    (function(H) {
        H.wrap(H.Tooltip.prototype, "refresh", function(c, p, e) {
            if(this.options.reversed && this.options.shared) {
                p.reverse();
            }
            c.call(this, p, e);
        });
    })(Highcharts);

**Comment by smithk58** [comment]
Awesome - thanks for the workaround! 

I'll leave this open, since I still think something like this should be in the regular API. If the devs disagree they're welcome to close this though.

**Comment by highslide-software** [comment]
This is also complicated by other things like stacking, negative values, negative stacks etcetera, also in line and area charts. Perhaps the most solid solution would be to (optionally) sort by the point's rendered position, regardless of reversing and inverting?

```js
    Highcharts.wrap(Highcharts.Tooltip.prototype, 'bodyFormatter', function (proceed, items) {
        var operator = this.chart.inverted ? 'x' : 'y';
        items.sort(function (a, b) {

            return b.point.shapeArgs[operator] - a.point.shapeArgs[operator]; 
        });
        return proceed.call(this, items);
    });
```
