### ISSUE TITLE
3d column: Incorrect data labels position 

### ISSUE THREAD

**Issue by Bazzy84** [highcharts/highcharts#4400]
Example: http://jsfiddle.net/jLv90xm3/
Labels on last bar are overlapped.

**Comment by jon-a-nygaard** [comment]
Thank you for reporting, we will look into this issue. Due to vacations, you should expect some longer response time than usual.

**Comment by pawelfus** [comment]
Workaround:
Set `dataLabels.overflow` to false, see: http://jsfiddle.net/jLv90xm3/5/

**Comment by jon-a-nygaard** [comment]
This issue seems to have been fixed since 4.1.8, [as shown by this example](http://jsfiddle.net/jLv90xm3/6/). Should this be wrong, please comment and reopen this issue.
