### ISSUE TITLE
negativeColor with drilldown apply wrong colors for series in drilldown

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4402]
When point is painted with negative color, then drilling down into it will force all points to be filled with that negative color of parent series.

Example with bars: http://jsfiddle.net/03heofhn/1/

Setting color for drilldown series helps for other seris but column based ones.
Only after mouse hover color will change to proper one, but in tooltip dot is colored wrongly.
http://jsfiddle.net/2x58sha7/

Workaround - trigger hover for all points after drilldown.

**Comment by pawelfus** [comment]
Connected issue: #4359

**Comment by KacperMadej** [comment]
Working since version 4.1.8.
