### ISSUE TITLE
What is the code license?

### ISSUE THREAD

**Issue by avinassh** [highcharts/highcharts#4405]
I want to contribute, but I couldn't find any license in the repo.

**Comment by jon-a-nygaard** [comment]
Hi, the code is licensed under the Creative Commons Attribution-NonCommercial 3.0 Unported License.
You can read all about the license by following [this link](http://creativecommons.org/licenses/by-nc/3.0/)

**Comment by karmir** [comment]
Highcharts is product of company called Highsoft, is commercial business developping and maintaining. For commercial purposeses see:  http://shop.highsoft.com/highcharts.html

Do contributes belong to Highsoft ?

**Comment by avinassh** [comment]
@jon-a-nygaard firstly, CC is not really a license for open source code and secondly, the license should be present in the repository.

**Comment by jon-a-nygaard** [comment]
@karmir 
__Do contributes belong to Highsoft?__
I can not give a sure answer to your question at the moment, but I will do. Some of our people who know the legal better are on vacation, but will be back next week.

@avinassh:
__CC is not really a license for open source code:__
Yes you are correct, and Highcharts is not open source either. It is just open, as in you are free to edit and modify the code, as long as your following the terms in the license. 

__The license should be present in the repository:__
Thank you for the comment, I agree that it should be present in the repository. I will discuss this with my technical chief, and see if we can add it as soon as possible.

**Comment by highslide-software** [comment]
> The license should be present in the repository

We are working on a license resume to put in the repo

**Comment by eschutho** [comment]
+1 Some companies will not allow usage of this package until the license has been posted on the repo, so I'm anxiously waiting for your update. Thank you

**Comment by TorsteinHonsi** [comment]
See https://github.com/highcharts/highcharts/blob/master/license.txt

**Comment by eschutho** [comment]
@TorsteinHonsi Do you plan on adding one to the npm package?

**Comment by KacperMadej** [comment]
License for the NPM package is added - it's a link to the shop website where you can find more info about license. https://github.com/highcharts/highcharts-dist/blob/8442d9458294b52c7042ae24e8883e739fc08d89/package.json#L22

**Comment by dalbani** [comment]
Thanks for the clarification! 👍
