### ISSUE TITLE
Point.update() with drilldown: true move the series to the right

### ISSUE THREAD

**Issue by mylainos** [highcharts/highcharts#4416]
Here the jsFiddle : http://jsfiddle.net/tjjnzfun/1/
When you click on the button and you aren't in the sub categories, only the first serie is updated (that's normal) but it is redrawn with a gap.
And when all the series are updated, it's well like here http://jsfiddle.net/tjjnzfun/2/.
I think the problem is the names of the categories which don't fit

**Comment by Mylainos** [comment]
Ok it's just a problem of size and margin

**Comment by jon-a-nygaard** [comment]
Hi @Mylainos, did you get it to work or do you still experience problems?

**Comment by Mylainos** [comment]
Hi @jon-a-nygaard, it work if the size of the container is much larger than the chart.

**Comment by highslide-software** [comment]
Simplified demo: http://jsfiddle.net/tjjnzfun/3/

It seems to have to do with the styling of axis labels according to `activeAxisLabelStyle` setting. Commenting out [this line](https://github.com/highslide-software/highcharts.com/blob/v4.1.7/js/modules/drilldown.src.js#L610) makes the issue go away. 

But the deeper problem is that we should never get two translations at the same time in the same chart, and `drilldown: true` shouldn't make any difference when only updating a point.
