### ISSUE TITLE
HighCharts error #10 with null values on logarithmic X axis

### ISSUE THREAD

**Issue by dugokontov** [highcharts/highcharts#4425]
This issue is similar to one that is closed: #3434. Anytime I set **x-axis** to logarithmic and add a point with values `null`, I got this error.

Here is minimal code to reproduce bug: http://jsfiddle.net/ev6m66my/.

I can reproduce this with version `4.1.7`.

As I sidenote, it is possible to evade this bug, if only `y` value is set to null, and x to some random number. Issue with this is that this `x` value is used to calculate `x` axis. You can see it here: http://jsfiddle.net/ev6m66my/1/

**Comment by highslide-software** [comment]
Since `x: null` is the same as a non-existing point, it should simply be omitted from the Highcharts configuration: http://jsfiddle.net/ev6m66my/2/.

**Comment by dugokontov** [comment]
@highslide-software: If you do that, than you can't break line: http://jsfiddle.net/ev6m66my/4/

**Comment by highslide-software** [comment]
You create a line break by adding a point where y is `null`. The x value still needs to be defined. See http://jsfiddle.net/highcharts/ev6m66my/5/.

**Comment by highslide-software** [comment]
... but in order for the axis extremes to be correct, you use an X value that is inside the break.

**Comment by dugokontov** [comment]
You are repeating what I said as a sidenote in OP (:

Anyway, if you think this is not a bug, feel free to close it. I still think either `x` should be allowed to be `null` or be ignored when `y` is `null`, because of charts that are dynamically created (you have to add custom code to watch for this case, and sets x to some existing value).

Best regards! You rock!
