### ISSUE TITLE
Highstock: navigator doesn't zoom completly when using setData 

### ISSUE THREAD

**Issue by pitermarx** [highcharts/highcharts#4426]
When using serie.setData the navigator does not show the full range

![missingbitonrangeselector](https://cloud.githubusercontent.com/assets/3081298/8983526/e7146758-36c2-11e5-9ec5-51036aef1c1e.PNG)

Example with code: http://jsfiddle.net/pitermarx/s6xnnbhj/

All the points are shown on the chart but the navigator has a gap

**Comment by pawelfus** [comment]
Workaround: set extremes after setting new data: http://jsfiddle.net/s6xnnbhj/6/

**Comment by pawelfus** [comment]
*Internal note:*

`afterSetExtremesHandlerScroller` from `StockNavigation.js` is called twice on each set data. for some reasons (?) at last working moment, it is called three time. Each next redraw calls `afterSetExtremesHandlerScroller` only once. 

Looks like connected to setting extremes [here](https://github.com/highslide-software/highcharts.com/blob/f6eb0e34f2f82704b170afbfd6fc49458400e025/js/parts/Scroller.js#L322). When commenting out that line, case above works fine? Rather suggestion for further debugging, than a real solution, I guess.

**Comment by pawelfus** [comment]
Works fine with 4.2.5+ versions: http://jsfiddle.net/rL9mpamm/
