### ISSUE TITLE
Highcharts global options polution (axis)

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#4437]
Hi, 

It seems that when calling Highcharts.setOptions with an object that has y/xaxis settings, and later on calling on highcharts instance addAxis - the axis is added to the global options and therefor pollutes future charts .
please review: http://jsfiddle.net/onemenny/shk8q2qb/
notice that after clicking the add axis button, the global options holds 2 yaxis instead of one

Please advice

**Comment by highslide-software** [comment]
I think the yAxis option needs to be a single object when used in setOptions. 

How does it affect future charts?

**Comment by onemenny** [comment]
For any charts we have a logic that gets the yaxis index (something like: check if there are more than 1 yaxis and return the proper index). so if the global gets polluted, newly (future) chart get's into yaxis hell. 

> I think the yAxis option needs to be a single object when used in setOptions. 

i don't see the difference, since we use multiple yaxis i do want the option to set it globally as an array. otherwise i think that it should act like a defaults object to newly created axsis. in any case this is not clear from your documentation.

**Comment by highslide-software** [comment]
We could break down the arrays in the setOptions method, but it would create overhead, so it would be simpler just to mention this in the docs. 

See http://jsfiddle.net/shk8q2qb/1/ for a drop-in fix.

**Comment by onemenny** [comment]
The fiddle doesn't work but i see your point. of course this is has implications if you set many yaxis in the global options. so you can have a default for each yaxis index. 

my initial thought was that the global option should never be polluted even if the axis are arrays - they should just represent the defaults for new charts created. 

anyway, documentation changes for now seems to be good enough   - this goes for every option represented by array?
