### ISSUE TITLE
Highstock: adding series to empty chart after clicking rangeSelector button

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4446]
If rangeSelector button is clicked (other than already selected), then after adding new series to empty chart it won't be rendered properly. (GitHub version is additionally throwing errors)

Example: http://jsfiddle.net/ytvx7nhs/
Steps: 
1. Click add series - all works fine.
2. Rerun the example
3. Click rangeSelector button (e.g. 6m)
4. Click add series - main series invislbe, no scrollbar, etc.
5. Click rangeSelector button to fix the chart

**Comment by pawelfus** [comment]
*Internal note:*
Default Highstock chart works fine now (we can not select any button), unless we set `rangeSelector.allButtonsEnabled` to true: http://jsfiddle.net/ytvx7nhs/1/
