### ISSUE TITLE
Shared tooltip is shown in 3d column chart on export button mouse over

### ISSUE THREAD

**Issue by kingoleg** [highcharts/highcharts#4454]
jsfiddle: http://jsfiddle.net/n6ho9x83/1/

If you use shared tooltip, when you move mouse over export button, tooltip for the last column is shown.

Actually, it look like there is no place in 3d column chart where tooltip is hidden

**Comment by highslide-software** [comment]
_Internal note_
It is because in 3D charts, the logic that determines whether the mouse is inside the plot area, is overridden: https://github.com/highslide-software/highcharts.com/blob/v4.1.7/js/parts-3d/Chart.js#L10-L11

This is because 3D columns and others are not restricted by the plot area.
