### ISSUE TITLE
mouseOver/mouseOut events for points do not always work properly

### ISSUE THREAD

**Issue by justanotherjones** [highcharts/highcharts#4474]
I'm running into issues with `mouseOver`/`mouseOut` events for points.

When datapoints from two series are close together, the events do not always behave properly. In this fiddle, you can see that the datapoint 27 does not always receive the proper events: http://jsfiddle.net/3x65cbyx/

The situation is worsened by disabling the tooltip. For a chart with a single point, it only ever receives one single `mouseOver` event: http://jsfiddle.net/qvr4z3tr/
For charts with multiple datapoints, mousing over a point, then out of the chart area, then back to the same point does not work properly: http://jsfiddle.net/k7jk9eos/

**Comment by pawelfus** [comment]
All demos work fine in 5.0.0, for example: http://jsfiddle.net/k7jk9eos/1/
