### ISSUE TITLE
Shared tooltip with floating legend bug

### ISSUE THREAD

**Issue by kingoleg** [highcharts/highcharts#4480]
jsfiddle: http://jsfiddle.net/1ktLsfyy/

WID:
1. Click "Jane" on legend
2. Move mouse around
3. Try to click "Jane" again

WIS:
Tooltip is over legend. Unable to click on legend

WIE:
Tooltip is over legend, or tooltip can be hidden by time, or by pressing escape key, or max x is enough to show tooltip below legend

**Comment by pawelfus** [comment]
Related issue #4375

**Comment by KacperMadej** [comment]
Resolved sine version 4.1.9.
Demo for 4.1.9: http://jsfiddle.net/1ktLsfyy/1/
Demo for current version: http://jsfiddle.net/1ktLsfyy/2/
