### ISSUE TITLE
Exporting - arabic labels incorrect wrapped

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4489]
Example: http://jsfiddle.net/eqnpLx6q/2/ 

Setting width, doesn't solve issue.

**Comment by highslide-software** [comment]
Normalized demo with a fixed width: http://jsfiddle.net/highcharts/eqnpLx6q/4/

**Comment by highslide-software** [comment]
#### Workaround
A valid workaround seems to be to use HTML on the axis labels. And in order for the export to work we need to use the new experimental `exporting.allowHTML` setting.
[View it live on jsFiddle](http://jsfiddle.net/highcharts/eqnpLx6q/5/).
