### ISSUE TITLE
Tooltips for stacked columns are buggy

### ISSUE THREAD

**Issue by historicbruno** [highcharts/highcharts#4493]
For our app, we have stacked column charts with some thin segments, like this: http://jsfiddle.net/gh8g2zu9/

I like that default tooltip style, but the problem is if the mouse cursor goes into the tooltip, it won't update which data is being hovered. That happens by moving the mouse upward from below the tooltip, especially near the center where the callout touches the chart. It creates a bigger problem with small segments that get entirely covered by the tooltip.

I know there are workarounds like using `shared` tooltips, `followPointer`, or `positioner`, but honestly these don't look nearly as good. And `followPointer` comes with its own similar bugs, like "floating" away from the columns and looking quite strange.

**Comment by pawelfus** [comment]
In other words, issue (ticket title didn't describe it) is that tooltip should pass on events to elements below? 

*Internal note:*
Works fine in other types, like area: http://jsfiddle.net/gh8g2zu9/1/ Most probably caused by different tracking elements, where in column, we check for rect events (+dataLabels when necessary).

**Comment by historicbruno** [comment]
That is correct, and indeed it works for some other chart types.

**Comment by highslide-software** [comment]
The difference between the area and the column implementation is that on the area, the tooltip is tracked by the mouse coordinates, whereas on the column, it is tracked by the `rect` elements themselves. It looks like we can enable the coordinate procedure also for column charts by removing a flag, `directTouch`. The downside is that the tooltip is now shown on the nearest Y value, which is not necessarily the column that we are hovering. How does this work for you?

http://jsfiddle.net/highcharts/gh8g2zu9/2/

**Comment by pawelfus** [comment]
Tested also on Firefox - no errors.
However, when zooming in, graph is empty.

**Comment by historicbruno** [comment]
It's quite an improvement! I can see the values of the smallest segments in the columns, which is important in our app, we have no control over how narrow or wide each might be. I think the tradeoff is acceptable in our use case, the behavior is consistent and logical.

**Comment by historicbruno** [comment]
Hmm, I see what you mean about the tooltip not necessarily hovering over the expected column. We do have a chart with columns stacked close together and the workaround makes the tooltip fairly useless in that case. So while it works in the presented JS fiddle case, it doesn't work for multiple series.

**Comment by KacperMadej** [comment]
Unable to recreate the issue in version 6.1.4.
In case you still have the problem please post a comment with details about the issue and it could be reopened.
