### ISSUE TITLE
Double-styled line on border of zones

### ISSUE THREAD

**Issue by MichaelSagalovich** [highcharts/highcharts#4503]
Actual behavior: I think this fiddle http://jsfiddle.net/5LnacLzy/ is quite descriptive, so please let me know if more details are required. I saw this in Chrome, but assume it is common for all browsers.

Expected behavior: The line should have a style of one of the zones. 
Additionally, documentation needs to be updated so that it is clear which zone such lines belong to (upper or lower). Current text does not specify that clearly: "value: Number
The value up to where the zone extends, if undefined the zones stretches to the last value in the series. Defaults to undefined." (http://api.highcharts.com/highcharts#plotOptions.area.zones.value)

**Comment by MichaelSagalovich** [comment]
funny but today my fiddle is not working at all...

**Comment by highslide-software** [comment]
I'm not quite sure what to do with this - zones are currently implemented by clipping rectangles. The two zones shift at value 0 exactly, so if the line is wide, you will get the shift in the middle of the line. If we were to do this differently, I guess we would have to analyze segments of the line to find out which segments belong to which zone.

**Comment by MichaelSagalovich** [comment]
That's what I imagined, and I understand why the other implementation could be complicated. However, you can also imagine how unexpected this behavior is. In my sample, I made the line really wide, but in real life the line can be 2px wide, and it is still noticeable that the upper part of the line differs from the lower, if the line is at the border of the zones. Moreover, the line could even be a bit upper or lower than the actual border, and still have two styles - it is clear why so. I wish I could advise what can be done to fix this easily, but I cannot. Still, I consider this a bug, as the behavior is definitely not expected.

**Comment by Llorx** [comment]
I think that @TorsteinHonsi idea can be a nice addition to fix this.

Also, maybe there could be a way to add segments to zones, instead of using an analyzer. Something like adding an option to a point (or between points, or something like that) to force segments between points to be on different zones.

Like special formatting for segments I guess.
