### ISSUE TITLE
Uncaught TypeError: Cannot read property 'chartX' of null

### ISSUE THREAD

**Issue by thientran1707** [highcharts/highcharts#4505]
I see this error when I use highcharts with my project. Despite the fact that it does not affect anything. I just want to know what's wrong with this. This is the settings for the chart

    var socialMap = new Highcharts.Map({
      chart: {
        renderTo: socialRadarNode,
        borderWidth: 1,
        backgroundColor: "#E4F1FE"
      },
      credits: {
        enabled: false
      },
      title: {
        text: 'Social Radar'
      },
      tooltip: {
        crosshairs: [{
          zIndex: 5,
          dashStyle: 'dot',
          snap: false,
          color: 'white'
        },
        {
          zIndex: 5,
          dashStyle: 'dot',
          snap: false,
          color: 'white'
        }]
      },
      mapNavigation: {
        enabled: true
      },
      series: [{
        name: 'Basemap',
        mapData: mapData,
        borderColor: '#606060',
        nullColor: 'white',
        showInLegend: false
      },
      {
        name: 'Republican States',
        mapData: mapData,
        data: republicSates,
        joinBy: ['postal-code', 'code'],
        color: '#D91E18',
        tooltip: {
          pointFormat: '{point.name}'
        },
        allAreas: false
      },
      {
        name: 'Democrat States',
        mapData: mapData,
        data: democratStates,
        joinBy: ['postal-code', 'code'],
        color: '#446CB3',
        tooltip: {
          pointFormat: '{point.name}'
        },
        allAreas: false
      },
      {
        name: 'Mindexed States',
        mapData: mapData,
        data: mixedStates,
        joinBy: ['postal-code', 'code'],
        color: '#BF55EC',
        tooltip: {
          pointFormat: '{point.name}'
        },
        allAreas: false
      }]
    });

**Comment by pawelfus** [comment]
Tried to reproduce your issue, but for me it works fine: http://jsfiddle.net/gqq7cfob/1/
Could you update my jsFiddle to get issue reproduced?

**Comment by pawelfus** [comment]
Commit above is a typo in the ticket number..

**Comment by thientran1707** [comment]
hi, is the problem fixed?

**Comment by thientran1707** [comment]
hi, still do not understand why sometimes the error appears, but sometimes it does not

**Comment by pawelfus** [comment]
Maybe you have sometimes corrupted data? It looks like connected to the data since my demo doesn't throw error at all. Or maybe is connected to specific width for the chart?

**Comment by thientran1707** [comment]
it happens when I try to zoom the chart. Maybe I will try with the width of chart

**Comment by MiChAeLoKGB** [comment]
I have same problem. In that JS fiddle it happens when you put your cursor over Norway or Iceland and start zooming. On my bubble map its happening whenever I hover over bubble and use scroll wheel to zoom.

**Comment by pawelfus** [comment]
Right, thank you for pointing this out. Steps:

1) Double click on the chart to zoom in.
2) Drag&drop the chart when  hovering one of the filled shapes

We can observe errors in the console and crosshair has wrong position:

> Uncaught TypeError: Cannot read property 'chartX' of null 

![maps_2](https://cloud.githubusercontent.com/assets/1453926/13177394/1982a3ca-d719-11e5-8a56-0a35b85b16a8.gif)

**Comment by tomascassidy** [comment]
The [api docs](http://api.highcharts.com/highmaps#tooltip.crosshairs) say that the crosshair configuration has moved to the Axis object since Highmaps 1.1.

http://jsfiddle.net/gqq7cfob/2/
