### ISSUE TITLE
Scatter chart 3D Issue

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#4507]
Scatter chart 3D with X and Y only. is working properly on Highchart 3D 4.1.5. 

If you replace Highchart 3d 4.1.5 with latest release 4.1.8, points are not plotting.

Please check below URL:
URL with Highchart 3d 4.1.5
http://jsfiddle.net/pawanvjadhav/wymdqecq/3/

URL with Highchart 3d 4.1.8
http://jsfiddle.net/pawanvjadhav/wymdqecq/4/

**Comment by pawelfus** [comment]
Responsible [commit](https://github.com/highslide-software/highcharts.com/commit/6cd30bd).

**Comment by pawelfus** [comment]
I'm not sure if this is a bug. I don't see `z` property for points. Is this intentional? See working demo: http://jsfiddle.net/wymdqecq/6/

**Comment by pawanvjadhav** [comment]
Yes, this is intentionaly. We dont have Z axis value. We have to just display it as 3D. Just like we do it for Bar, Column charts. Actully this working fine on 4.1.5.

**Comment by pawanvjadhav** [comment]
Are you going to fix this?

**Comment by pawelfus** [comment]
Sure. I have just one question, compare results:

- 4.1.5: 
![screen shot 2015-08-27 at 11 36 39 am](https://cloud.githubusercontent.com/assets/1453926/9517381/f6a164e8-4caf-11e5-91e7-856ad70ece19.png)
- bugfix:
![screen shot 2015-08-27 at 11 38 29 am](https://cloud.githubusercontent.com/assets/1453926/9517425/35e15bd6-4cb0-11e5-8f38-5cc6af928efe.png)

In 4.1.5 extremes were miscalculated too, but we didn't hide scatter points which were outside the extremes - issue with point outside extremes were fixed in 4.1.6, but extremes remain miscalculated. 

In the bugfix screenshot, extremes are calculated properly, and points are placed in the middle of the chart (see bottom frame - gridline with `z = 0`). What do you think? It's better to render points on the front frame (like 4.1.5) or in the middle of chart (bugfix)? I think it's easier for user to read values when can project point on each of the axes.

**Comment by pawanvjadhav** [comment]
I think, 4.1.5 is right.

In the screenshot of bugfix, it feels that, there is a Z Axis and its value is 0
So user may ask, what i have plotted on Z.

**Comment by pawelfus** [comment]
Because that would be true - if point doesn't have set `z` then it would be set to `0`. Similar how it works for `x` - if not set, then it's incremented by `pointInterval`.

**Comment by pawanvjadhav** [comment]
Ok. I think, it should work similar to Bar / Column 3d.

**Comment by pawelfus** [comment]
I will hold one with fixing this bug, @highslide-software - what do you think? zAxis should behave the same way as other ones, or we can allow zAxis to have NaN for extremes and we should just improve checking for `isInside`?

**Comment by salunkenagesh14** [comment]
@pawelfus @pawanvjadhav 
What about plotting points on the last frame If z values are NAN/ z values not present.

See this : http://jsfiddle.net/wymdqecq/7/ 
With different beta angle, still there will be a problem of user having a perception of possible z metrics.

Scatter 3D without a z axis is like showing 2D points inside the box/ on a single frame i.e. on a wall with box.
Your thoughts on this ?

**Comment by highslide-software** [comment]
I would expect them to be plotted at z=0. 

But there is a deeper problem - the scatter 3d chart redefines the scatter series type in [https://github.com/highslide-software/highcharts.com/blob/v4.1.8/js/parts-3d/Scatter.js#L54-L59](these lines). Ideally, each series type in Highcharts should have its own data definition, but scatter is an exception. In 2d, the data is [x, y], while in 3d it expects [x, y, z]. One solution would be that we added a `scatter3d` series type, but then we would break a lot of existing functionality. So I guess we should just fix the missing z problem for now.

**Comment by pawelfus** [comment]
I think this doesn't apply only to scatter series, let's see: http://jsfiddle.net/wymdqecq/8/ - columns are rendered on the front frame. I think it should be consistent between series. Though part: column series doesn't really consider `z` value.

Also, note that it's not about the format (`[x, y]` vs `[x, y, z]`) but not set option `z` when using `{}` object notation. 

Wouldn't be enough to wrap `applyOptions` for scatter series' point? Simple example: http://jsfiddle.net/wymdqecq/10/

**Comment by pawanvjadhav** [comment]
Are we moving towards for scatter 3d we should have Zaxis ?

**Comment by highslide-software** [comment]
Yes, I think that an undefined z value should behave like 0, just like columns.

> Wouldn't be enough to wrap applyOptions for scatter series' point? Simple example: http://jsfiddle.net/wymdqecq/10/

Yes, that's good. 

> Also, note that it's not about the format ([x, y] vs [x, y, z]) but not set option z when using {} object notation.

I know, but it's related. So in this case, the data is actually 2d, so the user could use a 2d scatter chart in 3d view.

**Comment by pawanvjadhav** [comment]
@salunkenagesh14 I have seen this problem when we set beta to 90. It should plot points within frame. Not getting why points are outside of frame.
Plotting points on last frame looks good option: I think, result will come similar to @pawelfus :bugfix image.

**Comment by pawanvjadhav** [comment]
sorry, by mistake i clicked on close and comment.

**Comment by pawelfus** [comment]
@pawanvjadhav - regarding labels on zAxis: 

> There we dont need to specify Z axis. as we dont have requirement of Z Axis. We have to just show it as 3D.

We can hide labels when necessary, see: http://jsfiddle.net/wymdqecq/12/

**Comment by pawelfus** [comment]
@salunkenagesh14 - regarding frame: 

> What about plotting points on the last frame If z values are NAN/ z values not present.

It's not a bad idea. With the implementation mentioned above it can be achieved by setting min and max for zAxis, like this: http://jsfiddle.net/wymdqecq/13/ -what do you think?

**Comment by pawanvjadhav** [comment]
@pawelfus looks good to me.

**Comment by salunkenagesh14** [comment]
@pawelfus Yes. When number of points grow to large extent. Plotting on last frame makes sense to be able to analyze.
See the difference between http://jsfiddle.net/wymdqecq/15/ and  http://jsfiddle.net/wymdqecq/17/

**Comment by pawelfus** [comment]
Just a reminder: we are only talking about the case when points don't have `z` value set.

**Comment by sebastianbochan** [comment]
Seems that problem still appears. 

Demo: http://jsfiddle.net/8mzdse8p/

**Comment by pawelfus** [comment]
+1

**Comment by sebastianbochan** [comment]
+1

**Comment by pawelfus** [comment]
**Workaround:**
http://jsfiddle.net/wymdqecq/10/

**Comment by TorsteinHonsi** [comment]
@pawelfus Will you fix it?

**Comment by pawelfus** [comment]
Fixed on bugfix branch: http://jsfiddle.net/eub7pz6a/

Where points are rendered (front or back frame), can be controlled by setting `zAxis.min` and `zAxis.max`:

- http://jsfiddle.net/eub7pz6a/1/
- http://jsfiddle.net/eub7pz6a/2/

**Comment by KacperMadej** [comment]
+1
