### ISSUE TITLE
Invalid computed y-axis range

### ISSUE THREAD

**Issue by mitar** [highcharts/highcharts#4523]
[See example](http://jsfiddle.net/zdkn6u8w/4/). Based on data (maximum value is 99221.0824224914) I would assume that y-axis scale would go from 0 to 100k. But it goes to 200k.

Even more interesting it is that if I click on a legend to hide the series and then click again to show it again, it reappears with range to 125k. Better, but still not perfect. Setting y-axis `minPadding` to 0 does not fix it, it is still 12k after hide/show. Setting `endOnTick` to `false` removes the whole problem, but this is not what I would like. I would like `endOnTick` to be enabled.

![edit_fiddle_-_jsfiddle_-_2015-08-30_14 33 41](https://cloud.githubusercontent.com/assets/585279/9569566/20f633d8-4f24-11e5-85c7-bdffad5fc258.png)

**Comment by pawelfus** [comment]
It's caused by `maxPadding`, not `minPadding`, see: http://jsfiddle.net/zdkn6u8w/6/
For future questions, please use forum/e-mail/SO.

**Comment by mitar** [comment]
But why is different when it renders the first time, and then when I hide and show it back in the legend? This is a bug!

**Comment by mitar** [comment]
`maxPadding` should not make it add two ticks extra!

**Comment by pawelfus** [comment]
Indeed, somehow I missed your info about two extra ticks - sorry for that!
However, this is still not a bug - it's caused for adding second yAxis and not setting `alignTicks` to false. In that case, Highcharts are setting the same number of ticks on the axes which increase number of ticks for some of them. See working demo: http://jsfiddle.net/zdkn6u8w/9/

By the way, why are you adding extra yAxis to the navigator? There already is one yAxis with id: `navigator-y-axis`. Using two axes with the same ID make cause another problems.

**Comment by mitar** [comment]
Hm, interesting. I always assumed I am adding y-axis only to the navigator and that this should not influence the main chart.

> By the way, why are you adding extra yAxis to the navigator?

Oh, I am doing this because I want multiple series in the navigator. I read this is not officially supported by highcharts, but the workaround I saw was that you add a y-axis for the navigator as well. So in my code I start with empty navigator and series:

```javascript
            'navigator': {
                'enabled': true,
                'adaptToUpdatedData': false,
                'series': {
                    'id': 'navigator',
                    'data': []
                }
            },
            'yAxis': [],
            'series': []
```

And then for each series I want to draw on this empty chart, I add y-axis:

```javascript
                yAxis = chart.addAxis({
                    'id': 'y-axis-' + axisTitle,
                    'title': {
                        'text': axisTitle
                    },
                    'showEmpty': false
                });
```

And add series itself:

```javascript
                    chart.addSeries({
                        'id': 'main-' + streamId,
                        'name': streamTitle,
                        'yAxis': yAxis.options.id,
                        'type': 'line',
                        'data': streamData
                    });
```

And add a series to the navigator:

```javascript
                    var navigator = chart.get('navigator');
                    chart.addAxis(_.extend({}, navigator.yAxis.options, {
                        'id': 'navigator-y-axis-' + streamId
                    }));
                    chart.addSeries(_.extend({}, navigator.options, {
                        'id': 'navigator-' + streamId,
                        'yAxis': 'navigator-y-axis-' + streamId,
                        'data': streamData
                    }));
```

(Real [code is a bit different](https://github.com/wlanslovenija/django-datastream/blob/master/django_datastream/static/datastream/js/datastream.js), for example, we redraw only at the end and disable redrawing for each of those calls.)

I am adding separate y-axis for navigator for each series so that the series is always stretched over the whole navigator height. Compare [this example](http://jsfiddle.net/highcharts/SD4XN/) (without extra y-axis) with [this one](http://jsfiddle.net/SD4XN/376/) (I prefer this one because it focuses on changes of each series in navigator, easier to navigate).

But the issue now is that while I would want for ticks to be aligned in the main area, it seems I do not want y-axis from navigator to influence those ticks? But `alignTicks` is per whole chart, not per set of y-axis?

> There already is one yAxis with id: navigator-y-axis. Using two axes with the same ID make cause another problems.

This was just a consequence of an example. Otherwise I make sure this does not happen.

**Comment by pawelfus** [comment]
Ok, so let's rename that issue: in fact problem is that `alignTicks` should apply only for axes at the same place (top+left position) - and this is how checking works [here](https://github.com/highslide-software/highcharts.com/blob/master/js/parts/Axis.js#L1169). Probably fails because of the workaround for multiple navigator axes..

However, to make it work, please set `Axis.pane` option, see: http://jsfiddle.net/zdkn6u8w/16/ - it's not documented well, but should resolve the issue above.

**Comment by mitar** [comment]
Oh, thanks. This looks reasonable.

**Comment by mitar** [comment]
Oh, I discovered that there is another similar issue. I have charts where I have series with both line and events data which uses flags type. And adding a y-axis for events data (even if it is empty) changes the displayed y-axis.

http://jsfiddle.net/0g2qpogd/2/

![edit_fiddle_-_jsfiddle_-_2015-09-02_22 51 08](https://cloud.githubusercontent.com/assets/585279/9651407/31b2f8a2-51c5-11e5-82fd-b070691d1d07.png)

![edit_fiddle_-_jsfiddle_-_2015-09-02_22 51 32](https://cloud.githubusercontent.com/assets/585279/9651409/34c3b36a-51c5-11e5-9f02-370ef0ec1816.png)

So it seems also adding additional y-axis for flags (so no real data on y-axis) makes things move around. Adding additional pane solves the problem as well. Really neat.

It is interesting that the issue happens only if I add series and axis asynchronously inside `setTimeout` (in reality it is loaded from the server with ajax). No idea why.

**Comment by mitar** [comment]
I don't see anywhere in the code why `pane: [{}, {}],` would be necessary.

**Comment by pawelfus** [comment]
See #4442 - I reopened just that issue.

**Comment by mitar** [comment]
OK, I have found out that the "pane" workaround does not work well if I have multiple series on a chart. See [example](http://jsfiddle.net/0g2qpogd/3/). It is really interesting. If you run it, you will see that the chart has y-axis all the way up to 800, instead to 600 or something:

![edit_fiddle_-_jsfiddle_-_2015-09-05_21 54 33](https://cloud.githubusercontent.com/assets/585279/9702561/b5948eec-5418-11e5-9d58-2b67d105ac22.png)

But when I hide foo1 (so smaller series) by clicking on its label in the legend, y-axis fixes itself:

![edit_fiddle_-_jsfiddle_-_2015-09-05_21 55 42](https://cloud.githubusercontent.com/assets/585279/9702570/df98fcbe-5418-11e5-860d-397ca798a7c5.png)

When I show foo1 again, now y-axis is correct:

![edit_fiddle_-_jsfiddle_-_2015-09-05_21 56 24](https://cloud.githubusercontent.com/assets/585279/9702573/f6ded7ae-5418-11e5-9a0a-846f51e4025d.png)

So this is clearly a bug. How to make it render correct y-axis from the very beginning?

(BTW, also observe how navigator's series are offset down a bit, so they are drawn outside the navigator itself.)

Also interesting is that I had to put initial navigator y-axis into another pane for some other cases. So I am using now four y-axis panes, 0 for initial navigator y-axis, then 1 for series, 2 for flags, and 3 for other navigator y-axis for multiple series.

**Comment by mitar** [comment]
And everything is connected with adding series to navigator. If I do not add anything to the navigator, then main pane y-axis is perfect. See [example](http://jsfiddle.net/0g2qpogd/4/).

**Comment by pawelfus** [comment]
Just an update: http://jsfiddle.net/0g2qpogd/5/ - it looks better with the current 5.0.x versions, but still initially calculated extremes for yAxes is different than after hiding&showing any of the series.

**Comment by pawelfus** [comment]
**Workaround:**
Set `chart.legend.display = true`, before calling `chart.redraw()`.

The problem is we calculate available space according to the options, and in the first render, legend is not visible (no series in the chart). Demo: http://jsfiddle.net/L8bshLhu/2/

*Internal note:*
In the first render we do check if the height/width of the plotting area drastically changed, and then we call `chart.getMargins()` once again. In redraw we need to do the same (call it twice under some conditions, or just call it twice always). But it's a questionable solution:

```javascript
chart.getMargins(); // #4523

if (hasCartesianSeries) {
	// set axes scales
	each(axes, function (axis) {
		axis.updateNames();
		axis.setScale();
	});
}

chart.getMargins(); // #3098
```

**Comment by pratheekka** [comment]
Hi , 
I am facing a similar issue where both the Y-axes max value is 1 but the chart is drawn to 1.4 or 1.25. 
I tried passing max value as 1 for both Y-axes, but still highstocks is drawing till 1.25 0r 1.4.

I would like to restrict the Y-axis max value to max data plot or rounded up value to nearest value.

**Comment by pawelfus** [comment]
Could you recreate issue in jsFiddle? Thanks!

**Comment by sapan0511** [comment]
Please find the js fiddle : 

https://jsfiddle.net/sapan0511/y4h008nk/17/

As you can see the max value is 1 and 4 but still chart is drawn till 1.6 and 5.2 respectively. Can you please provide any help regarding the issue.

**Comment by sebastianbochan** [comment]
@sapan0511 
Highcharts aligns ticks between yAxis, by default. You can disable it by [alignTicks](http://api.highcharts.com/highcharts/chart.alignTicks) parameter.

Fixed demo:
- https://jsfiddle.net/tzr14u43/

**Comment by sapan0511** [comment]
But if we do that chart y axis looks messy and it is not easily readable. This is the scenario when there is very less data it might happen that chart will have lot of series.Due to this reason I want alignTicks parameter to be true.

**Comment by pawelfus** [comment]
I would use tickPositioner in this case, for example: https://jsfiddle.net/hzhq3p90/

**Comment by sapan0511** [comment]
Hi , 

The data is not static as shown in fiddle , there will be case when there will be data with max value as lets say 100k(min)to 600k(max) or the value might go to -1(min) to 100k(max)  . So it will become very cumbersome to set ticks for data that will vary.

**Comment by pawelfus** [comment]
It is just an example, `interval` can be calculated for example displaying always 10 ticks: https://jsfiddle.net/hzhq3p90/1/ (`Highcharts.correctFloat()` is a utility to fix rounding numeric errors in JS, e.g. 0.1 + 0.2 = 0.30000000004).
