### ISSUE TITLE
Changing axis is incorrectly adjusting yAxis extremes

### ISSUE THREAD

**Issue by garystubbings** [highcharts/highcharts#4535]
An issue was present in 4.1.5 whereby the axis extremes were incorrectly calculated and adjusted, this has been resolved in 4.1.8 for most cases, however, it is still present when you change series axis.

See http://jsfiddle.net/w3gqh3rk/ 
Compare version 4.0.0 with 4.1.8

**Comment by highslide-software** [comment]
When multiple axes are used, Highcharts first finds the best tickAmount and uses that for both axes. When only one axis is used, the tick amount is more flexible because it doesn't have to recurse over series.

**Comment by garystubbings** [comment]
In the jsfiddle provided the tick amount should not change when the axis is switched. If you switch to an older version you will notice it was not previously issue. In addition, if you switch everything to the opposite axis (second yAxis) instead then the extremes are different. See http://jsfiddle.net/w3gqh3rk/ in contrast to http://jsfiddle.net/srw9tjs4/1/

**Comment by highslide-software** [comment]
> If you switch to an older version you will notice it was not previously as issue.

Older versions recursed over the axes, which was slower.

**Comment by Brendalfly** [comment]
I've noticed this issue as well, basically the scale on the y-axis should be the same for both series[0].yAxis == 0 || series[0].yAxis == 1. When yAxis == 1 the scale on the axis is incorrect resulting in unneeded whitespace at the top of the chart.
