### ISSUE TITLE
Update from scatter to line - incorrect extremes

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4540]
When we update serie from scatter to line, extremes changes incorrecly, but after second update, all is displayed properly.

Example:
- http://jsfiddle.net/8Sg8K/446/

Calling setExtremes seems to not solve this issue
- http://jsfiddle.net/8Sg8K/448/

**Comment by pawelfus** [comment]
I would say that scatter series is rendered wrong - like `ordinal` option doesn't work for that type.

If current result for scatter is expected one, then set `xAxis.ordinal` to false, see: http://jsfiddle.net/8Sg8K/449/

**Comment by pawelfus** [comment]
#2342 issues looks like connected, so workaround to make updating work properly:

            Highcharts.Series.prototype.takeOrdinalPosition = false;

Demo: http://jsfiddle.net/8Sg8K/450/
