### ISSUE TITLE
Can not update point in hidden series in highcharts

### ISSUE THREAD

**Issue by nicecp** [highcharts/highcharts#4542]
I have some series in the highcharts,few of them is hidden , I can add new point to a hidden series,but can't update the Y value of a point.Once the hidden series is visible,it shows the old Y value,I don't know the reasons and can't figure out it myself,my version is  Highcharts JS v4.0.3 (2014-07-03).thx a lot.

**Comment by pawelfus** [comment]
Just tested: http://jsfiddle.net/b9cqstt1/ - could you update my example to reproduce issue? Thanks!

**Comment by nicecp** [comment]
I tested the example , and found the problem though I still can't solve it...
my example code is like this:

    $("#b").click(function() {
        $('#container').highcharts().series[0].addPoint(['New',100],true,true);
        alert($('#container').highcharts().series[0].data.length);
       	$('#container').highcharts().series[0].data[0].update(Math.random() * 100);
    });

I need to know the index of  the point in a series so I use series.data.length to get length then check whether there is a point which its x equals to a given value.If it exists then update the point!
But when the series hidden, I found the length is becoming smaller after adding a new point  as if no point has added to the series .And when the series is visible I can see the new point I have added.So its really strange, and it really confused me many days...
Really appreciate for your help.

**Comment by pawelfus** [comment]
It looks like `series.generatePoints()` isn't called (or rather is called only for pie type). So points are not generated (only removed by shift), which in result makes shorted `series.data` array. Workaround: 

    (function (H) {
        H.wrap(H.Series.prototype, 'addPoint', function (p) {
            p.apply(this, Array.prototype.slice.call(arguments, 1));
            this.generatePoints();
            this.isDirty = true;
            this.isDirtyData = true;
            // optional redraw:
            if(arguments[2]) {
				this.chart.redraw();
            }
        });
    })(Highcharts)

And working demo: http://jsfiddle.net/ux74929j/2/

*Internal note:*
I understand, that sometimes adding/updating data even for a hidden series may be required (like data feed from the outside, which can not be controlled), however in performance terms, it's better to not create points which don't exist. Probably it's worth some tests how much performance we will lose when using e.g. 50k of points - without adding anything to the DOM maybe it won't hurt performance so much. Or maybe connect that to `turboThreshold`? When above, don't create points for a hidden series, but create in any other case?

**Comment by nicecp** [comment]
I add the points to a buffer. When the series is visible doing adding/updating, then shift the old one . It really works.The points won't more than 5k, so I think it's OK in my script.
Maybe this will be improved in the next version :P.And hope this question is helpful for others like me.
