### ISSUE TITLE
error while calling setData() on hidden series

### ISSUE THREAD

**Issue by azza0091** [highcharts/highcharts#4544]
I have a chart with some hidden series which needs to be updated periodically.
When I call the setData() function on any hidden series, it sets empty data instead of the data I specify in the parameter.
Looking at the changelog, this looks similar to issue #3702 which is supposed to be solved since version 4.1.0, but I'm using 4.1.8 and I'm still having that problem (of course I tried also version 4.1.0, but the bug is always present)

**Comment by azza0091** [comment]
I attach a fiddle to better explain my issue
https://jsfiddle.net/ux74929j/

**Comment by pawelfus** [comment]
Looks like issue connected to #4542, in short:  not called `series.generatePoints()` for a hidden series. Workaround: http://jsfiddle.net/ux74929j/4/ and snippet: 

    (function (H) {
        H.wrap(H.Series.prototype, 'setData', function (p) {
            p.apply(this, Array.prototype.slice.call(arguments, 1));
            this.processData();
            this.generatePoints();
            this.isDirty = true;
            this.isDirtyData = true;
            // optional redraw:
            if(arguments[2]) {
				this.chart.redraw();
            }
        });
    })(Highcharts)

The same thing to concern: performance for huge number of points, where points are not rendered, but are stored in the memory.

**Comment by azza0091** [comment]
thanks a lot for the workaround, it works great.
For performance issues you are right, but in my case I don't have so many points, let's say max 5 series of 1000 points. By now everything is fast and I don't experience any lag
