### ISSUE TITLE
hide series from legend in pie chart

### ISSUE THREAD

**Issue by azza0091** [highcharts/highcharts#4545]
I have some hidden series in my charts that I'm using to keep trace of some data, but that I want to be hidden to the user (both in the chart and in the legend).
On all chart types (except pie chart) I'm able to do this by setting the parameters "visible" and "showInLegend" to false on these series.
The structure of pie charts, however, is different as it requires to add a single series which have, in the "series.data" option, the name and values of my categories. If I set "visible" and "showInLegend" to the main series of course I will hide the whole legend. Instead, I would like to hide the single categories that I don't want to show, but the "series.data" option does not support any attribute to set "showInLegend" to false for that data only. Any ideas on how could I accomplish this or if this feature could be added in future releases?

**Comment by pawelfus** [comment]
Indeed, right now pie chart can have all slices in legend or disabled legend. To achieve the same, why don't you just remove slices which you don't want to display? To manage them later you can use `addPoint()` or `point.remove()`.

**Comment by azza0091** [comment]
actually I would like to have some information to be stored in an hidden slice, and if I remove the slice I would lose that.
Is there any chance that this feature could be added in future releases?

**Comment by pawelfus** [comment]
Ok, but why do you need that information stored in Highcharts chart? Wouldn't be better to keep business logic outside the charting library? 

I think it can be added. More common case (I think) is to disable user option to hide some of the slices (like always visible slice, without legend item).

**Comment by azza0091** [comment]
I know that in a pie chart this may not have much sense, but I do this in other chart types and I just want to have a common structure between different chart types.
Basically I add an hidden series in which each point is a boolean value which tells me if that point needs to be updated. Periodically I perform a refresh and, for each series, I update only the points where the hidden series contains "1".

**Comment by hiteshsarsava** [comment]
I want same requirement. Still not solved this ? @TorsteinHonsi
