### ISSUE TITLE
3d scatter draggable demo rotated by 180 deg. doesn't hover proper points

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4552]
Demo: http://www.highcharts.com/demo/3d-scatter-draggable
Steps:
1. Rotate 180 deg. in horizontal axis
2. Hover over points
3. Hovered points are not the one under the cursor, but on the other side instead.

**Comment by highslide-software** [comment]
Looks like either the k-d-tree is not using the z dimension correctly, or the k-d-points are not translated to 2D before applying. Alternatively, we shouldn't use k-d-tree at all for 3d.

**Comment by pawelfus** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/wzfes2yj/1/

Note that you now have to hover the point directly to read the tooltip, because we disabled the k-d-tree. An alternative fix may be to fix the tree to use projected coordinates.
