### ISSUE TITLE
Requesting an export with a filename containing commas fails in Chrome

### ISSUE THREAD

**Issue by okonet** [highcharts/highcharts#4555]
Trying to call `chart.exportChart` with `filename` containing commas fails and Chrome displays `ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION` error.

This seems to only happen in Chrome, but I'm not sure if it is a Chromium bug.

**Comment by okonet** [comment]
Well, this is a reported issue but it seems to be a propriate behavior: https://code.google.com/p/chromium/issues/detail?id=103618#c5

**Comment by highslide-software** [comment]
Currently we do not do any filtering at all on the filename, so you must make sure it consists of valid characters.

**Comment by karellm** [comment]
I had this issue. I think it should be either documented or handled by highcharts.
