### ISSUE TITLE
Highstock: initial animation is disabled for series when data is grouped and 'All' rangeSelector is selected

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4563]
In Highstock: if series' data is grouped and 'All' rangeSelector is selected, then initial animation for series is disabled and setting animation to true doesn't change it.

Example: http://jsfiddle.net/22ur8s0u/
Top chart - data is grouped - no initial animation.
Bottom chart - data is not grouped - animation.

Workaround - disable dataGrouping: http://jsfiddle.net/22ur8s0u/1/

**Comment by pawelfus** [comment]
Looks like exactly the same reason as in #4288 ticket - the same `redraw()` is called because of different union extremes and initial extremes on the series.

**Comment by pawelfus** [comment]
Works in 4.2.5
