### ISSUE TITLE
HTML Tooltip Drifts in IE 10

### ISSUE THREAD

**Issue by iansullivan88** [highcharts/highcharts#4565]
The HTML tooltip drifts in IE 10. I have enabled the useHTML property on one of the demos to show this:

http://jsfiddle.net/cvsn5ps9/

When the tooltip is at the right of the chart, there is no right padding in the tooltip but it is fine when the tooltip is at the left (see attached screenshot)

![highcharts-tooltip](https://cloud.githubusercontent.com/assets/7151163/9818263/8b0e2abc-589f-11e5-8b16-6f20cfbbfa38.png)

I know in this example the issue looks really trivial but in the chart I am making I have a lot more content in the tooltip that eventually spills out of the container as the tooltip moves along the chart.

The tooltip works fine in Chrome.

Regards
Ian

**Comment by highslide-software** [comment]
I tried this in IE10, but it doesn't fail on my machine...

@pawelfus Can you reproduce this?

**Comment by pawelfus** [comment]
Works fine, tested with IE10 (v10.0.9200.16384) on W8.

**Comment by iansullivan88** [comment]
Very strange, I just tried on another version of IE:

Not working on Windows 7 IE 10.0.9200.17457
Working on Windows 8 IE 10 10.0.9200.17492

If you are using JSFiddle, increasing the width of the result pane will make the bug more obvious.

**Comment by jon-a-nygaard** [comment]
Closing this issue due to we are not able to reproduce it, and it has been inactive for a long time. Should anyone have further information on this issue, please add a comment and/or reopen.
