### ISSUE TITLE
Resizing window containing heatmap shows colorAxis undefined error

### ISSUE THREAD

**Issue by MicheleMannino** [highcharts/highcharts#4566]
Resizing window containing `heatmap` shows this console error:

`heatmap.js:511` - Cannot read property '0' of undefined

As showed below, it seems to be an invalid access of `getAllItems` function to undefined `colorAxis`:

`colorAxis = this.chart.colorAxis[0];`

Highstock version used `2.1.7`

**Comment by pawelfus** [comment]
Could you setup jsfiddle with this issue? Just tested and works fine, see: http://jsfiddle.net/rfcvugrw/

**Comment by MicheleMannino** [comment]
Here it is: http://jsfiddle.net/rfcvugrw/1/

In my use case, I'm using Backbone.js and require.js. Only when resizing the window I've got the problem showed.
Could it be due to Highchart load timing?

**Comment by highslide-software** [comment]
I still can't see a JS error in your demo, using Chrome...

**Comment by FlavioMH** [comment]
I have the same behavior in my application.
Michele did you find a workaround to solve the issue?

**Comment by TorsteinHonsi** [comment]
@FlavioMH Perhaps you are able to show set up a live reproduction so we can locate and fix the issue?

**Comment by MicheleMannino** [comment]
Right now we are using "highstock-release": "2.1.7" and it is **no more** reproducible.
Perhaps was a problem due to require module system...

**Comment by FlavioMH** [comment]
I am not able to provide you a live reproduction, but I can try to explain the issue and when I get it.
I create 2 bar chart and then a heatmap one. First 2 are immediately created, while heatmap chart is created after following function:
`require(['../HighCharts/modules/heatmap'], function(hm)...) `
When I try to call:
`chart.setSize($(chart.renderTo).width(), $(chart.renderTo).height())`
on the first 2 I have following error in heatmap.js:
`Cannot read property '0' of undefined`
If I destroy and recreate first 2, then I can call:
`chart.setSize($(chart.renderTo).width(), $(chart.renderTo).height())`
without problems.
And this is how I solved out with a workaround: I first call:
`require(['../HighCharts/modules/heatmap'], function(hm)...) `
on the top of all. Then I continue with other charts creation.

I don't know if it can help you.

Thanks in advance.

**Comment by MPiccinato** [comment]
I know this is an old issue but the suggestion by @FlavioMH helped me fix my issue. It wasn't ideal since I ended up having to load up the heatmap in a spot I didn't really want to.

In my case I had a `solid-gauge` module being loaded before the `heatmap` module. Switching the order to put the `heatmap` first fixed this.
