### ISSUE TITLE
Chart - rounded corners are ignored when exporting

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4567]
Seems that borderRadius is ignored. 

Example: http://jsfiddle.net/d4ss486y/1/

**Comment by pawelfus** [comment]
It looks like it is set on a purpose [here](https://github.com/highslide-software/highcharts.com/blob/master/js/modules/exporting.src.js#L380).

Workaround: 

    (function (H) {
        H.wrap(H.Chart.prototype, "getSVGForExport", function (p, options, chartOptions) {
            var chartExportingOptions = this.options.exporting;

            return this.getSVG(H.merge(
            //{ chart: { borderRadius: 0 } },
            chartExportingOptions.chartOptions,
            chartOptions, {
                exporting: {
                    sourceWidth: (options && options.sourceWidth) || chartExportingOptions.sourceWidth,
                    sourceHeight: (options && options.sourceHeight) || chartExportingOptions.sourceHeight
                }
            }));
        });
    })(Highcharts)

Demo: http://jsfiddle.net/d4ss486y/2/

**Comment by highslide-software** [comment]
In earlier versions of Highcharts the border was rounded by default, which did not look good on the default exported PNG, so we removed it in export.

**Comment by KacperMadej** [comment]
To have the `borderRadius` option saved for the exported chart just make sure it's placed in `exporting.chartOptions.chart` options of the chart. Demo: http://jsfiddle.net/BlackLabel/teh01kh3/
