### ISSUE TITLE
numberFormat and toFixed() - wrong rounding

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4573]
Highcharts.numberFormat return wrong number (incorrect rounding) because it is using toFixed().

Example: http://jsfiddle.net/0yjd97up/

In this case Math.round(this.y*1e4)/1e4 will work, but it is not correct in other cases. Source of the problem is binary floating point math.

**Comment by pawelfus** [comment]
*Internal note:*

It should work like described [here](https://github.com/kvz/phpjs/blob/master/functions/strings/number_format.js#L35-L36).

**Comment by pawelfus** [comment]
It breaks this case: http://jsfiddle.net/cxst6qsk/1/ (vs current: http://jsfiddle.net/cxst6qsk/2/)

Example is a minified version of our waterfall demo, and issue is caused by using `pointFormat` with param: `{point.y:,.2f}`.

**Comment by pawelfus** [comment]
Thanks! Much better, but there is still a case when it fails: http://jsfiddle.net/cxst6qsk/3/ (only master branch)
