### ISSUE TITLE
highcharts-convert.js in server-mode hangs when invalid data is supplied

### ISSUE THREAD

**Issue by micw** [highcharts/highcharts#4574]
When the convert server is called with invalid data that causes an error while rendering the charts, the rendering process terminates but the webserver-response is left open and no status is written. That causes the connection to hang until it times out.

Example:
curl http://127.0.0.1:10003 -H "Content-Type: application/json" -X POST -d "{\"infile\":\"{data:[29.9,71.5,106.4]}\",\"type\":\"svg\"}"

Causes:
- The request to wait for a response that never is sent
- An error in the logs:
TypeError: 'undefined' is not an object (evaluating '$('div.highcharts-container')[0].innerHTML')

  phantomjs://webpage.evaluate():127
  phantomjs://webpage.evaluate():132
  phantomjs://webpage.evaluate():132
TypeError: 'null' is not an object (evaluating 'svg.imgUrls')

  /opt/highcharts-4.1.8/exporting-server/phantomjs/highcharts-convert.js:261
  /opt/highcharts-4.1.8/exporting-server/phantomjs/highcharts-convert.js:548
  :/modules/webpage.js:281

Solution: Pass some function to render() that handles all kind of fatal errors like this one that sends an error message and closes the reponse properly

**Comment by gvaartjes** [comment]
Hi,

Thanks fro reporting this, I'll take a look and see how we can address this issue

Gert

**Comment by gvaartjes** [comment]
Closed by commit in highcharts-export-server repository; See https://github.com/highcharts/highcharts-export-server/commit/fb0f4ec30fa517464812c07a9a9740e823508a0e
