### ISSUE TITLE
3d scatter - tooltip's pointFormat is applied only from a series

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4576]
`pointFormat` for scatter in 3d is applied only if it is set in `series.tooltip`.

`pointFormat` in `plotOptions.series`, `plotOptions.scatter` or `tooltip` is not being applied.

Example: http://jsfiddle.net/Lk16tshq/

**Comment by pawelfus** [comment]
*Internal note:*

I see a couple of solutions here:

- use `setOptions()`, but this will overwrite if user set `pointFormat` using `setOptions`.. : 


		Highcharts.wrap(Highcharts.seriesTypes.scatter.prototype, 'init', function (proceed, chart, options) {
			if (chart.is3d()) {
				// add a third coordinate
				this.axisTypes = ['xAxis', 'yAxis', 'zAxis'];
				this.pointArrayMap = ['x', 'y', 'z'];
				this.parallelArrays = ['x', 'y', 'z'];

				// #4576
				Highcharts.setOptions({
					plotOptions: {
						scatter: {
							tooltip: {
								pointFormat: 'x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>z: <b>{point.z}</b><br/>'
							}
						}
					}
				})
			}

			return proceed.apply(this, [chart, options]);
		});

- manually set `pointFormat`, but the way it looks.. :


		Highcharts.wrap(Highcharts.seriesTypes.scatter.prototype, 'init', function (proceed, chart, options) {
			var result,
				default3dScatterTooltip,
				userOptions = chart.userOptions,
				plotOptions = userOptions && userOptions.plotOptions,
				tooltipOptions = userOptions && userOptions.tooltip,
				scatterOptions = plotOptions && plotOptions.scatter,
				seriesOptions = plotOptions && plotOptions.series;

			if (chart.is3d()) {
				// add a third coordinate
				this.axisTypes = ['xAxis', 'yAxis', 'zAxis'];
				this.pointArrayMap = ['x', 'y', 'z'];
				this.parallelArrays = ['x', 'y', 'z'];
			}

			result = proceed.apply(this, [chart, options]);

			if (chart.is3d()) {
				// Set a new default tooltip formatter
				default3dScatterTooltip = 'x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>z: <b>{point.z}</b><br/>';
					
				this.tooltipOptions.pointFormat = pick(
					this.userOptions.tooltip && this.userOptions.tooltip.pointFormat,
					scatterOptions && scatterOptions.tooltip && scatterOptions.tooltip.pointFormat,
					seriesOptions && seriesOptions.tooltip && seriesOptions.tooltip.pointFormat,
					tooltipOptions && tooltipOptions.pointFormat,
					default3dScatterTooltip
				);
			
			}
			return result;
		});

- in `Intro.js` (or create separate file? and there) add `setOptions` to change default `pointFormat` - that should eliminate issue from the first solution (overwriting user options)

- resign from setting `pointFormat`in scatter-3d

**Comment by highslide-software** [comment]
Another reason why scatter3d should be a separate series type. We should strongly consider this for Highcharts 5 even though it breaks the current 3D charts. But the way it is now, it is the only series type with conditional data definition, tooltip etc.

**Comment by pawelfus** [comment]
Indeed, separate series type would resolve that issue (and probably make easier-to-fix another issues).

**Comment by pawelfus** [comment]
It's fixed in v6:

- all options are not ignored
- use `plotOptions.scatter3d` to define options for scatter in 3D

Demo: http://jsfiddle.net/Lk16tshq/2/
