### ISSUE TITLE
Columnrange - disabled border prints lines between cols.

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4577]
Example: http://jsfiddle.net/5c2jqsho/3/

I guess that is related with rounding x/y values and crisp (https://github.com/highslide-software/highcharts.com/issues/2694)

**Comment by pawelfus** [comment]
Workaround: http://jsfiddle.net/5c2jqsho/4/

Set in CSS: 

    .highcharts-series {
      shape-rendering: crispEdges
    }

*Internal note:*
Shouldn't `height` and `y` of the bar be integer value, not floating point?

**Comment by highslide-software** [comment]
> Shouldn't height and y of the bar be integer value, not floating point?

Yes, I would expect that.

**Comment by pawelfus** [comment]
Just checked, rounding values won't resolve issue, let's see: 
![screen shot 2015-09-17 at 3 44 19 pm](https://cloud.githubusercontent.com/assets/1453926/9934655/fcf2a88a-5d52-11e5-8a99-95e610d69ad7.png)

- first bar doesn't start on the grid line
- last bar (or second one?) is a bit misplaced 

Bars are directly one after another, so there should not be any space between them. It is probably the same issue as for tightly packed columns: #2690 ?

**Comment by highslide-software** [comment]
Yes it's more complicated than just rounding. For inspiration (or demotivation alternatively), take a look at [this passage](https://github.com/highslide-software/highcharts.com/blob/v4.1.8/js/parts/ColumnSeries.js#L165-L173) in the column series. It has to be rounded up or down depending on whether the chart is inverted, and also depending on SVG or VML.
