### ISSUE TITLE
datetime axis with minor ticks

### ISSUE THREAD

**Issue by luiza-cicone** [highcharts/highcharts#4579]
I have the following column chart with a datetime x axis : [http://jsfiddle.net/yz8ekedp/](http://jsfiddle.net/yz8ekedp/)

When I have minorTickInterval defined and startOnTick to true, even if the min value is on a tick, the min is rounded down to a minor tick. Maybe linked to [#1498](https://github.com/highslide-software/highcharts.com/issues/1498).

Difference with previous versions [http://jsfiddle.net/y3z0dj0j/1/](http://jsfiddle.net/y3z0dj0j/1/)

**Comment by highslide-software** [comment]
It's a regression in 4.1.8, caused by 1b09fe7.

Simplified demo: http://jsfiddle.net/highcharts/yz8ekedp/3/

**Comment by pawelfus** [comment]
Works fine in 5.0.8+ demo: http://jsfiddle.net/rrLb6tnj/
