### ISSUE TITLE
Inconsistent shared tooltip positioning when the chart is inverted.

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#4581]
When inverted is false, the tooltip is positioned next to the mouse pointer. However when the chart is inverted it is being positioned elsewhere. I think positioning the tooltip next to the pointer makes sense in both cases.

http://jsfiddle.net/Lvkfghtn/

**Comment by pawelfus** [comment]
Workaround:

Set `followPointer: true`, see: http://jsfiddle.net/Lvkfghtn/1/

**Comment by Rashaine** [comment]
Thanks for the workaround but the behavior seen in the non-inverted case is more desired. That is, the x position is always the same per category but the y position follows the mouse pointer.

**Comment by highslide-software** [comment]
The code in question is at https://github.com/highslide-software/highcharts.com/blob/v4.1.8/js/parts/Tooltip.js#L177-L180, where we can see that the Y direction has logic that is missing for X.
