### ISSUE TITLE
lineWidth ignored when exporting

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4583]
Looks like lineWidth is ignored when we use getSVG or use exporting.

Examples: 
- http://jsfiddle.net/7r8wut2j/
- http://jsfiddle.net/su0ngL4q/

**Comment by highslide-software** [comment]
_Internal note:_
It probably falls into a category of bugs where we have problems with the inheritance chain from plotOptions into series, especially when exporting because the additional chartOptions add to the complexity.

**Comment by mlbreit** [comment]
Thanks for the info, I was the one who brought this up on stackoverflow. Is there another way in the current version to achieve the same effect when calling getSVG? My onscreen charts look great, we just need a thicker line graph on export so people can read the printed version.

**Comment by pawelfus** [comment]
Workaround may be to to update series in `load` event for `chartOptions.chart` see: http://jsfiddle.net/7r8wut2j/1/

Snippet:

        exporting: {
            chartOptions: {
                chart: {
                    events: {
                        load: function () {
                            this.series[0].update({
                                lineColor: 'red',
                                lineWidth: 10
                            });
                        }
                    }
                }
            }
        },

**Comment by mlbreit** [comment]
Awesome, pawefus. I was able to smoosh that into getSVG and get it working. 

Snippet:
```var chart = $('#patient-chart').highcharts();
            var svg = chart.getSVG({
                chart: {
                    width: 1200,
                    height: 660,
                    events: {
                        load: function () {
                            this.series[0].update({
                                lineWidth: 10
                            });
                        }
                    }
                }
            });
```

**Comment by sebastianbochan** [comment]
Works since HC 4.2.2.

Reopen if problem will come again.
