### ISSUE TITLE
Loading and No data to display are overlapped.

### ISSUE THREAD

**Issue by fizerkhan** [highcharts/highcharts#4588]
I uses option of `loading: true` to show the message of `Loading` while fetching the data. I also uses `no-data-to-display.js` module to display a message for pie chart. 

But `no data to display` is message shown along with `Loading` message. Can we hide `no data to display` message while loading?

**Comment by pawelfus** [comment]
That snippet should do the thing:

        chart: {
            events: {
             	load: function() {
                 	this.showLoading(); // show loading message
                    this.hideNoData();  // hide no data message
                }
            }  
        },

But for some reasons it doesn't work: http://jsfiddle.net/594ntok2/ Looks like `chart.events.load` is called **before** event added this way: `H.addEvent(chart, 'load', handleNoData);` (from no-data-to-display.js module).

**Comment by jandillmann** [comment]
Is there a workaround for this? Having both messages shown overlapping doesn't make much sense…

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng

**Comment by oysteinmoseng** [comment]
@jandillmann: The most "politically correct" workaround is perhaps to override `chart.hasData` to return `true` once data is being loaded. Alternatively, you can override `chart.showNoData` to do nothing. Remember to restore the old functions when loading has finished if you still want the no-data message to appear (e.g. when hiding series). Demo: http://jsfiddle.net/594ntok2/1/.

**Comment by TorsteinHonsi** [comment]
Is this still valid? Can't reproduce it.

**Comment by oysteinmoseng** [comment]
@TorsteinHonsi Seems valid, see [master demo](http://jsfiddle.net/594ntok2/13/) vs [bugfix demo](http://jsfiddle.net/594ntok2/14/).

**Comment by oysteinmoseng** [comment]
Note that `Chart.hasData` should return `chart.loadingShown`, not `false`. That fix-commit seems to just delete the return statement, but the actual code line in `bugfix` is `chart.loadingShown; // #4588. None of the series have data, but don't show message if we are loading.`

**Comment by scottadmi** [comment]
This solution does not seem to address the case in which the graph is initially displayed empty (with the no data message), and the chart showLoading() is subsequently called (to indicate data refresh is being attempted) - in which case neither or "load" or "redraw" event are fired to reassess this message.

**Comment by KacperMadej** [comment]
@scottadmi Could you provide a live demo for the case?

**Comment by scottadmi** [comment]
The second chart demonstrates this case. In our real usage, we poll for the presence of data at certain intervals, but show the user "loading" during these attempts so they are aware which creates the odd effect in the second pane if there was no data initially.

http://jsfiddle.net/bjooth9q/

**Comment by KacperMadej** [comment]
In this case before showing the loading info you could hide the no-data label - http://jsfiddle.net/bjooth9q/3/ This doesn't require redrawing of a chart.

**Comment by ehernandez-vi** [comment]
Morning guys, I'm already facing the issue, I have tried a lot of things, even, I hide the 'No data to display' through css meanwhile the data is fetched, it worked for the first time, but after I refreshed the page, it did not work.

There is a fix for this?

TY

**Comment by raf18seb** [comment]
Hi @ehernandez-vi! The original issue from this ticket is fixed. It seems you have a problem that may not necessarily be a bug.
With questions/problems like this, you should contact our support engineers on one of our dedicated support channels (GitHub is our bugs/features tracker only).
More info: https://www.highcharts.com/blog/support/

If you are sure that this is a Highcharts core bug, then please provide a live demo with the exact steps to reproduce and a description of an excepted behavior.

**Comment by jlecordier** [comment]
> In this case before showing the loading info you could hide the no-data label - http://jsfiddle.net/bjooth9q/3/ This doesn't require redrawing of a chart.

`chart.hideNoData` is not available in the public API : see #16314

**Comment by jlecordier** [comment]
I could solve my problem by first using `chart.showLoading`, then using `series.setData([])`
