### ISSUE TITLE
Navigator is unable to update series data

### ISSUE THREAD

**Issue by bharathd** [highcharts/highcharts#4589]
Hi
when scroll the navigator how series data is hiding .
http://jsfiddle.net/9010889853/0azqvs9g/
please let me solving-- i have tried with baseseries and adaptToUpdatedData both are not working.

dhanpalbharath456@gmail.com
regards,
Bharath

**Comment by pawelfus** [comment]
By default, navigator uses first series in `series` array as base. Have you tried to set *separate* data for navigator? But not the one you have (where data is not sorted and doesn't cover full range), but something like this: http://jsfiddle.net/0azqvs9g/3/

**Comment by pawelfus** [comment]
I assume it works for you? I'm closing this ticket then. Please, reopen it if I'm wrong.
