### ISSUE TITLE
HighStock range selector drag event is not working on mobile device

### ISSUE THREAD

**Issue by jianbo** [highcharts/highcharts#4590]
I want to display stock chart on my hybrid app, everything works fine except the drag event for the range selector at the bottom, I tested using the demo app, http://www.highcharts.com/stock/demo/basic-line. Using Chrome browser developer tool, turning on the mobile device mode and enable the touch screen event, the drag slider is not working.

**Comment by jianbo** [comment]
http://i.stack.imgur.com/MFlq0.png

**Comment by highslide-software** [comment]
On the real thing it works, just tested with iOS 9 and Safari... Chrome developer tools is not completely reliable for emulating touch devices.

**Comment by jianbo** [comment]
forgot to mention it doesn't work on my Android 4.4.2 s4 in my Ionic app, but it works on my Android Chrome browser. Could this be a Ionic issue? or the specific UIWebView version? Reason I posted here is because the result of the Chrome developer emulator is identical to my mobile app.

**Comment by jon-a-nygaard** [comment]
Closing this issue since we are both unable to reproduce, and it is considered inactive. Should anyone have further information on this issue, please add a comment and/or reopen.
