### ISSUE TITLE
Extremes for bubble series

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#4592]
Example: http://jsfiddle.net/oxy8ya9h/1/

Click several times first button - eventually you will see blank plotting area. 
Click several times second button - it never happens.

In short, workaround is to always sort data ascending, or set `yAxis.minRange`. 

_Internal note:_
Should bubble series work like scatter (so order for points doesn't matter)? In that case, after debugging, [this block](https://github.com/highslide-software/highcharts.com/blob/8c154994b61633a11dfe6ec11dbf971f7f6da311/js/parts-more/BubbleSeries.js#L328-L336) should be improved. Right now it happens that `max < min` which is wrong. So either swap min and max after block, or improve logic there. If we have `max < min` then `tickInterval` is negative which in results cause `tickInterval = 0`. 
Or bubble series requires ascending order of points? In that case, error in JS console is missing.

**Comment by highslide-software** [comment]
It should work like scatter, point ordering shouldn't matter.

**Comment by pawelfus** [comment]
Ok, I think this is more general problem, or rather two-in-one issue. 

1) `beforePadding` posted above indeed could swap min and max to fix empty chart, however: 
2) negative `tickInterval` remains. As the result, consider demo: http://jsfiddle.net/oxy8ya9h/2/ - click several times on `setData` and at one of updates some of the markers will be rendered outside the plotting area (below or above the yAxis extremes). 

First issue is easy, simple `if` would resolve it, but perhaps fixing second issue may resolve first issue - it sounds wrong that `min` is higher than `max`.

**Comment by pawelfus** [comment]
Second issue looks like the same as  #3770.

**Comment by pawelfus** [comment]
Fixed since v4.2 demo: http://jsfiddle.net/BlackLabel/oxy8ya9h/7/
