### ISSUE TITLE
Highstock IE8 type mismatched

### ISSUE THREAD

**Issue by xdestiny** [highcharts/highcharts#4593]
An old issue has reappeared it seems. Version 2.1.4 up to 2.1.8 have this problem in IE8, IE7 and versions after 8 do not have the problem.

After some investigating I found that when you change the tickColor to null, IE8 will not draw the chart and fire more errors when hovering over the area where the chart should have been shown.

This all relates to setting the tickColor to null and this part of the Highstock system

```
setAttr: function (key, value) {
    if (docMode8) { // IE8 setAttribute bug
        this.element[key] = value;
    } else {
        this.element.setAttribute(key, value);
    }
},
```

The key is 'strokecolor' and the value is null when the error happens. 

This obviously can be solved by setting a tickWidth of 0 instead of removing the color. So, this has no high priority, just wanted to let you know.

**Comment by pawelfus** [comment]
Any specific reason to set `tickColor` to null? According to the [docs](http://api.highcharts.com/highcharts#xAxis.tickColor) - color should be set, not null (neither `NaN`, `true`, `false` etc.).

**Comment by xdestiny** [comment]
This probably happened because chart > backgroundColor is removed by setting it to null and this has been adapted here on error. I don't think it necessarily needs a fix in the Highcharts sources. Maybe just make it clearer in the docs that colors should not be set to null. Maybe just this issue is needed to document the behavior for generations to come. For the most part, it's just interesting that only IE8 stops drawing the chart and no other browser, not even IE7, cares about this.

**Comment by yohanleafheart** [comment]
Just to add something more here, I've got this same issue on IE8, and it was fixed by not setting the backgroundColor of the chart to NULL. So there is something funk happening on this case.

(Yeah, IE8, goddammit stupid clients)
