### ISSUE TITLE
Range selector button in dynamic chart alternates between selected / unselected states

### ISSUE THREAD

**Issue by vickychijwani** [highcharts/highcharts#4598]
Demo: http://jsfiddle.net/rrekfs6r/ (forked from http://www.highcharts.com/stock/demo/dynamic-update)
Browser: Google Chrome 45

Open the demo above and look at the "5M" range selector button. Notice how it flickers continuously between the "selected" and "unselected" states. Setting the axis extremes to a value that matches a range selector option (like 5 minutes in the demo) and then updating the chart dynamically causes this.

**Comment by pawelfus** [comment]
Workaround: Instead of setting extremes by `axis.setExtremes()` in load event use `rangeSelector.selected` option: http://jsfiddle.net/rrekfs6r/1/

**Comment by vickychijwani** [comment]
@pawelfus but the `rangeSelector.selected` option cannot be set after the chart has been created, can it? Or am I missing something?

**Comment by pawelfus** [comment]
You are correct, we can't set `selected` option in run time. However, we can force button to be clicked, this way: 

        chart.rangeSelector.clickButton(1, true);  // selected = 1, that means second button

Demo: http://jsfiddle.net/rrekfs6r/3/

For my comment above - I wasn't sure what was the purpose of calling `setExtremes()` in load event, while you can set `selected` simply.

**Comment by vickychijwani** [comment]
The reason I'm calling `setExtremes()` instead of using `rangeSelector.selected`, is because I'm saving the extremes selected by the user (which they may have done by either clicking one of the range selector buttons or by dragging the navigator handles) and then using them later when the chart is restored, in which case I would like the appropriate range selector button, if any, to be shown as selected. Does that make sense?

**Comment by pawelfus** [comment]
Thank you for the explanation, I was curious about the case. I think this workaround should be the easiest for your case: 


                    var extremes = this.xAxis[0].getExtremes();
                    this.fixedRange = 5*60*1000; // set range
                    this.xAxis[0].setExtremes(extremes.dataMax - 5*60*1000, extremes.dataMax, true);

See demo: http://jsfiddle.net/rrekfs6r/4/

**Comment by vickychijwani** [comment]
That *almost* works, except when I set `fixedRange` again the previous button remains selected. Any ideas how to prevent that?
Demo: http://jsfiddle.net/rrekfs6r/5/

**Comment by pawelfus** [comment]
Ok, but is that real case? You wait x-seconds to set extremes in your case? If that's the case, then I think it would be better to use previous workaround:

     chart.rangeSelector.clickButton(1, true);  // selected = 1, that means second button

**Comment by pawelfus** [comment]
*Internal notes:*

Two things here:

- `selected` variable should be nullified [here](https://github.com/highslide-software/highcharts.com/blob/d2526e3e609cf5c34e9b2632e4d53cf169e2254c/js/parts/RangeSelector.js#L318) (simple `selected = null` should be enough)
- `afterSetExtremes` event is added in `load` [here](https://github.com/highslide-software/highcharts.com/blob/d2526e3e609cf5c34e9b2632e4d53cf169e2254c/js/parts/RangeSelector.js#L285) , **but** order of the events is: `chart.events.load`, then event added by `addEvent(....)`. Looks like the same issue as #4588

**Comment by sebastianbochan** [comment]
Fixed since 2.1.10.

Reopen if problem will come again.
