### ISSUE TITLE
max works different for 0 and 1 yAxises

### ISSUE THREAD

**Issue by kingoleg** [highcharts/highcharts#4607]
Hi,

I try to setup max for yAxis. If I use it for 0 yAxis - it works OK http://jsfiddle.net/9a59t0h9/1/ (max = 50)
But is I setup for 1 yAxis - it ignores http://jsfiddle.net/9a59t0h9/2/ (max = 80)

And both yAxis uses the same max.

I want both yAxises max are independent and are exactly the same value I set.

Regards,
Oleg

**Comment by pawelfus** [comment]
It should be fixed on the master branch, see: http://jsfiddle.net/9a59t0h9/3/

Regarding exatly the same value you set, consider setting `alignTicks` to false, see [API](http://api.highcharts.com/highcharts#chart.alignTicks).
