### ISSUE TITLE
Boost modules - inverted charts

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#4608]
Examples:
- http://jsfiddle.net/mp1qpfxo/
- http://jsfiddle.net/e4xkehjq/

Area shape is not visible and scatter series is missing part of the points. Additionally both series highlight wrong points on mouseover.

**Comment by highslide-software** [comment]
After today's commit the the markers of the scatter chart are placed correctly, and the k-d-tree finds the right point. Remaining issues:
* Hover marker is placed wrong
* Area series threshold is wrong.

**Comment by Rashaine** [comment]
Any update on this? Here is an alternate example. https://jsfiddle.net/t38t1e2e/

**Comment by kamilkulig** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Apparently inverted charts are partly implemented in the Boost, but not complete.

**Comment by wKavey** [comment]
Was any additional work ever made on this? Having the known issue where my hover markers are displayed incorrectly when using boost and an inverted chart.

**Comment by sebastianbochan** [comment]
Hi @wKavey,
Could you post your live demo for the further debugging?

**Comment by pawelfus** [comment]
Simplified demo:
http://jsfiddle.net/BlackLabel/cu780oxk/

**Workaround:**
Demo: http://jsfiddle.net/BlackLabel/ckv6f0j1/

Code: 
```js
// For inverted series, we need to swap X-Y values before running base methods
Highcharts.wrap(Highcharts.Point.prototype, 'haloPath', function(proceed) {
  var halo,
    point = this,
    series = point.series,
    chart = series.chart,
    plotX = point.plotX,
    plotY = point.plotY,
    inverted = chart.inverted;

  if (series.isSeriesBoosting && inverted) {
    point.plotX = series.yAxis.len - plotY;
    point.plotY = series.xAxis.len - plotX;
  }

  halo = proceed.apply(this, Array.prototype.slice.call(arguments, 1));

  if (series.isSeriesBoosting && inverted) {
    point.plotX = plotX;
    point.plotY = plotY;
  }

  return halo;
});

Highcharts.wrap(Highcharts.Series.prototype, 'markerAttribs', function(proceed, point) {
  var attribs,
    series = this,
    chart = series.chart,
    plotX = point.plotX,
    plotY = point.plotY,
    inverted = chart.inverted;

  if (series.isSeriesBoosting && inverted) {
    point.plotX = series.yAxis.len - plotY;
    point.plotY = series.xAxis.len - plotX;
  }

  attribs = proceed.apply(this, Array.prototype.slice.call(arguments, 1));

  if (series.isSeriesBoosting && inverted) {
    point.plotX = plotX;
    point.plotY = plotY;
  }

  return attribs;
});
```
