### ISSUE TITLE
It's difficult to override the hover look of legend items

### ISSUE THREAD

**Issue by tonypan** [highcharts/highcharts#4612]
Currently the legend items' appearance on hover is controlled by Javascript (in js/parts/Interaction.js):

``` javascript
extend(Legend.prototype, {
   ...
    (useHTML ? legendItem : item.legendGroup).on('mouseover', function () {
            ...
            legendItem.css(legend.options.itemHoverStyle);
        })
        .on('mouseout', function () {
            legendItem.css(item.visible ? itemStyle : itemHiddenStyle);
                        ...
```

This makes it awkward to customize the hover appearance, since the style applied by `.css()` is likely to take precedence (`!important` may work, but is bad practice). For example, the developer may want it so that the legend item _stays_ greyed out on hover (currently the legend becomes black on hover).

Beside the lack of extensibility, it's also undesirable to implement hover styles using JavaScript (CSS readily provides the `::hover` selector).

Possible fixes:
1. (JS+CSS) Could you change to `.toggleClass()` (and make the necessary CSS changes) so that the developer can easily override the hover style?
2. (CSS-only) Could you use `::hover` instead of `mouseover`/`mouseout`?

**Comment by highslide-software** [comment]
In Highcharts 5 we are changing all this to use pure HTML. See [an early preview at jsFiddle](http://jsfiddle.net/highcharts/86cqwopx/2/).

> Beside the lack of extensibility, it's also undesirable to implement hover styles using JavaScript (CSS readily provides the ::hover selector).

The rationale for this is that a) it needs to be compatible with oldIE VML browsers, and b) for automate tasks, one single API is simpler than separation of SVG and CSS. Highcharts 5 will split into two flavors, one keeping VML support and a uniform API, and the other splitting SVG and CSS as much as possible.

**Comment by tonypan** [comment]
@highslide-software Thanks for the explanation!
