### ISSUE TITLE
Exporting: 413 Request Entity Too Large

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4614]
When trying to export big map with large amount of data (world-palestine-highres with population data in mapbubble series) exporting returns `413 Request Entity Too Large`.

Example: http://jsfiddle.net/5mzd6dh2/

Workaround: use custom exporting server with increased size limit in nginx.conf

**Comment by pawelfus** [comment]
+1

**Comment by highslide-software** [comment]
#### Workaround
In modern browsers, you can use the offline-exporting.js module: http://jsfiddle.net/highcharts/5mzd6dh2/1/

**Comment by gvaartjes** [comment]
Hi @KacperMadej , we're moved to nginx that's right! I didn't think of this setting this option.

thx for pointing out. 

+10

**Comment by TorsteinHonsi** [comment]
To work around the issues, you may also try using [data grouping](http://api.highcharts.com/highstock#plotOptions.series.dataGrouping) or the [boost module](http://www.highcharts.com/articles/2-news/175-highcharts-performance-boost).

**Comment by raeenh2002** [comment]
Thanks but they are of no use for the exporting part. I am processing 8GB of data and I'm already grouping so many chunks of data into one, still it is so big to export. And I want atleast a 300dpi print image, which means something like a 3300px * 5100px image. It is something like the picture below. It just lacks the resolution.

![8](https://cloud.githubusercontent.com/assets/11270783/13460329/ecdd07e2-e047-11e5-8f58-aa15fbdfeb88.jpg)

**Comment by gvaartjes** [comment]
@raeenh2002 
I would then recommend to use our PhantomJS script from the command line. Read more about this here: http://www.highcharts.com/docs/export-module/render-charts-serverside
It has never been tested against 8GB, though

**Comment by gvaartjes** [comment]
Request entity has been increased on the server (Dec 29th 2015), closing issue now

**Comment by nebulousdog** [comment]
@gvaartjes what is the new limit? I still sometimes get this issue. That said though, we havent had opportunity to upgrade to newest Highcharts yet.

**Comment by gvaartjes** [comment]
@nebulousdog This is an old thread dealing with our old exporting server running Java. We moved over to a NodeJS/NGinx server. The setting you're talking about is something we have to set on our servers running the exporting service to prevent misuse. It has nothing to do with running an older Highcharts version.
@cvasseng Can you tell Tommy what's the current limit is?

**Comment by cvasseng** [comment]
The limit is 2MB on the node server.

**Comment by nebulousdog** [comment]
thanks!

**Comment by andreyfomin** [comment]
Is the any example now to export a map from node.js app as pdf. I can't find it.

**Comment by KacperMadej** [comment]
_Internal note:_ the above comment is continued on the correct repo: https://github.com/highcharts/node-export-server/issues/183

**Comment by hamzaayoub159** [comment]
> Hi @KacperMadej , we're moved to nginx that's right! I didn't think of this setting this option.
> 
> thx for pointing out.
> 
> +10

hi can you please tell about nginx config how you managed to do it
