### ISSUE TITLE
Point update - marker color not applied

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4622]
Example: 
http://jsfiddle.net/yPT73/1/

Seems that is related with https://github.com/highslide-software/highcharts.com/issues/4267

**Comment by dawidgorus** [comment]
+1

**Comment by sebastianbochan** [comment]
Doesn't work since 4.1.8 (in 4.1.7 is fine).

Extra demo: http://jsfiddle.net/yb5f6rsL/4/

**Comment by sebastianbochan** [comment]
Fixed in the master branch.
Ref: http://jsfiddle.net/yb5f6rsL/5/

**Comment by sebastianbochan** [comment]
Seems that problem is still with pie chart: 

http://jsfiddle.net/59ss9nm2/2/

**Comment by pawelfus** [comment]
Fixed on the bugfix branch, probably connected to #4704.

See: http://jsfiddle.net/59ss9nm2/4/

**Comment by dawidgorus** [comment]
I've found one more bug, update color works on pie slice, but color doesn't change in legend

http://jsfiddle.net/59ss9nm2/7/

**Comment by pawelfus** [comment]
Thanks!

**Comment by KacperMadej** [comment]
The issue is also present when using funnel or pyramid - http://jsfiddle.net/f1xbvgxw/2/

**Comment by pawelfus** [comment]
*Internal note:*

1) Legend item isn't updated. In fact, `colorizeItem()` is called only when creating item (or when hiding/showing series/slice).

2) Funnel - indeed, still broken (the same fix as for other series should be applied), also issue with legend item exists: http://jsfiddle.net/f1xbvgxw/3/

**Comment by TorsteinHonsi** [comment]
Continue on #4759

**Comment by Audhut** [comment]
this issue still persists on xRange chart where i am changing the color on  point click event.
I am using 
pointEvent.point..update({ color: "pink", pointWidth: 40 }, true, false);
pointEvent.point.series.redraw();

however one observation is that if i click on another point, then the color of the first point changes

**Comment by pawelfus** [comment]
Hi @Audhut 

Could you provide a live demo of the issue? The basic demo seems to be fine: https://jsfiddle.net/BlackLabel/puwk6arg/ Thanks!
