### ISSUE TITLE
Titles overlapping each other when exporting multiple charts.

### ISSUE THREAD

**Issue by villekivela** [highcharts/highcharts#4623]
This happens when both
title: { useHTML: true }
and
exporting: { allowHTML: true }

![chart 1](https://cloud.githubusercontent.com/assets/5814559/10278536/bcf6ae08-6b66-11e5-9edf-317f8daab379.png)

Here's jsFiddle http://jsfiddle.net/gd7bB/2271/

**Comment by highslide-software** [comment]
This is a bug in the snippet that concatenates SVG for the multiple charts, not Highcharts itself. The problem is that the SVG content of subsequent charts is translated, but the HTML content is not.

**Comment by highslide-software** [comment]
It is a problem with the snippet shared at http://www.highcharts.com/docs/getting-started/frequently-asked-questions#export-multiple, but not with Highcharts itself. 

The problem in the snippet is that the SVG content is added to groups and translated for subsequent charts, but this does not apply to HTML content.
