### ISSUE TITLE
Highstock: Grouped data doesn't include additional data

### ISSUE THREAD

**Issue by igitur** [highcharts/highcharts#4628]
Please refer to https://jsfiddle.net/igitur/6pLej7x6/2/

I'm using a Highstock chart and the data series is an array of objects, each containing `x`, `y` and `some_other` properties. For a low number of items (e.g. set `max_items` to 100), the tooltip correctly displays `some_other` property in the tooltip. However, for large values of `max_items` (e.g. 999), the data is grouped and the `some_other` property doesn't appear in `series.points`, hence the tooltip doesn't render the `some_other` property.

I believe the line https://github.com/highslide-software/highcharts.com/blob/master/js/parts/Series.js#L653 is the culprit:
`				points[i] = (new pointClass()).init(series, [processedXData[i]].concat(splat(processedYData[i])));` It doesn't reuse the additional properties. I'm unsure how to fix this myself.

**Comment by highslide-software** [comment]
Yes, when the points are grouped, they are not used at all. Instead, new group points are generated from the group X and the Y data according to the approximation setting. 

A possible solution could be to provide a `groupMap`, a parallel array sitting on the series, which would contain information about each group point and what original point indexes the group exists of. Or better, this could be stored directly on the group point. Then your tooltip formatter could read that and get the original points from `series.options.data`.

What do you think about that?

**Comment by TorsteinHonsi** [comment]
Since 777525f6ef58, the group information is found in `Point.dataGroup`.
