### ISSUE TITLE
Candlestick - allowPointSelect works only for couple points

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4635]
It looks like that select state is applied only for  "blue" candles.

Example:
- http://jsfiddle.net/b1q62cey/

**Comment by highslide-software** [comment]
Simplified demo: http://jsfiddle.net/highcharts/b1q62cey/1/

It has now been fixed in the candidate for HC5: http://jsfiddle.net/highcharts/b1q62cey/2/

**Comment by sebastianbochan** [comment]
Fixed since HS v5.0
