### ISSUE TITLE
Puffin browser - missing compatibility when data is huge

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4636]
Run http://www.highcharts.com/demo or http://www.highcharts.com/stock/demo in Puffin browser (iOS or Android) and observe that some charts are not printed properly. Example: http://www.highcharts.com/demo/line-time-series

iOS 9.0 and Android 5.1.1

Internal note: Im aware of that this browser is not included in our compatibility webpage, but maybe is simple solution to support this browser too.

**Comment by KacperMadej** [comment]
Working fine in Highcharts v7.0.0.
Tested on Android 7.0.
Closing as resolved.
