### ISSUE TITLE
Firefox 3.6: point markers not visible since 4.1.0

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4643]
Example: http://jsfiddle.net/1sz31swt/8/

Screenshots for 4.1.0 - working: https://www.browserstack.com/screenshots/6b4cbe182f6b3481f85756e0ee7b428921c4b933

4.1.1 - not working: https://www.browserstack.com/screenshots/c90aa8b4a8ec591ae18d14adceb5cef97a640f05

Also tested 4.1.9, 4.1.8 and version from github's master - not working.

**Comment by highslide-software** [comment]
It can be reproduced also with the simplest of fiddles, http://jsfiddle.net/highcharts/llexl/.

It appears to be a problem with the clipping of the marker group after animation. Disabling animation on the series fixes it.
