### ISSUE TITLE
Angular Gauge Pane.size issue for 100%

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#4644]
See what happens when we set Pane.size : 100%
http://jsfiddle.net/pawanvjadhav/7y5gn58n/

Gauge goes beyond plot.

**Comment by KacperMadej** [comment]
Only backgrounds that have more than 100% of radius are outside, so all seems fine.
Example: http://jsfiddle.net/7y5gn58n/1/

For general support questions, use a stackoverflow / forum or email.
