### ISSUE TITLE
Please allow buttons without tooltips in exporting module

### ISSUE THREAD

**Issue by jhegeman** [highcharts/highcharts#4647]
Dear Highcharters,

First of all a big thank you for this sweet tool! The 'issue' I have is a very minor one, really. If one defines a custom button using the exporting module (see this fiddle: http://jsfiddle.net/jcyu7amm/1/), the tooltip will show 'undefined'. I know one can tweak this adding to the lang settings, but in this case I would prefer not having any tooltip at all. Would it be possible to just check for 'undefined' and in that case show no tooltip, please?

Best regards,
Jeroen

**Comment by pawelfus** [comment]
Probably adding checking [here](https://github.com/highslide-software/highcharts.com/blob/a9caa833525d959c6b2732b1b2c5bf79165b34f8/js/modules/exporting.src.js#L675) would be enough, like this: 

				title: pick(chart.options.lang[btnOptions._titleKey], ''),

Sample: http://jsfiddle.net/jcyu7amm/2/

**Comment by highslide-software** [comment]
@pawelfus Yes, that's fine!

**Comment by pawelfus** [comment]
I see a lot of changes with date for the product - something changed in ant build file?

**Comment by highslide-software** [comment]
Yes, the gulp file adds the current date. See [this line](https://github.com/highslide-software/highcharts.com/blob/bc7434ca86719995339c13f5c7778863c61c3663/gulpfile.js#L307-L310). My though was that it would help users to see exactly when the file in development was built, but on the down side it creates a lot of garbage in the commits, so I'm not sure if it's a good idea. At least it should only apply to the files actually changed in the commit.
