### ISSUE TITLE
SVG image is not exporting with height and width from renderer.

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#4653]
When we are adding SVG image to our chart, the width and height parameters from renderer are not consider when we want to export chart to PNG, PDF or JPEG image. It is working only for exporting as SVG vector image.

Here is our chart: 
![chart](https://cloud.githubusercontent.com/assets/15050812/10450454/aeb24b92-719a-11e5-984d-4d95b912ae1b.png)

And here is export as PNG:
![chart 7](https://cloud.githubusercontent.com/assets/15050812/10450470/c87cf16c-719a-11e5-9b91-13b293414c6d.png)

Below I am sending live example:
http://jsfiddle.net/izothep/sLp4vbcj/2/

**Comment by highslide-software** [comment]
Chrome renders the exported SVG correctly, so apparently PhantomJS has a problem with doing the same on the server. Another note is that it works correctly when a PNG image is included in the chart: http://jsfiddle.net/highcharts/sLp4vbcj/3/.
