### ISSUE TITLE
Input is not escaped

### ISSUE THREAD

**Issue by jorn86** [highcharts/highcharts#4654]
Strings that should be HTML-escaped in my series, are included verbatim. For example, if I have an axis label, or series datapoint with the text `'t<e>st & &times;'`, it is rendered as `'tst & &times;'`. That means some, but not all replacing is happening: the 'tag' which absolutely _must_ be escaped, is not, but is instead ignored / removed. The text, behaves even weirder: The `&` is rendered normally, so it is unclear what happens, and the HTML entity _is_ escaped, to `&amp;times;`. Please fix the inconsistency between how the tag is rendered, and how the HTML entities are rendered.

**Comment by highslide-software** [comment]
For your information, Highcharts converts a subset of HTML into SVG text. This is performed in the [https://github.com/highslide-software/highcharts.com/blob/v4.1.9/js/parts/SvgRenderer.js#L1358](buildText) method.

**Comment by jorn86** [comment]
OK. Is it documented somewhere how text is converted, and/or can I change that behavior?

**Comment by highslide-software** [comment]
In my test it replaces the tag, but not the entity. See http://jsfiddle.net/highcharts/439hnd2d/. As you see we do replace the HTML entities for `<` and `>`, because those are known. 

Otherwise you should just be able to spell out the characters in UTF8: http://jsfiddle.net/highcharts/439hnd2d/1/

**Comment by ffdybuster** [comment]
A related question: how does escaping works in series names? `&lt;` and `&gt;` are automatically replaced with `<` and `>`, but `&amp;` is not replaced with `&`. On the other hand, `<i>` is treated as a HTML tag.  So if I want to display a string which a user can enter, I have to change `<` and `>` to `&lt;` and `&gt;`, respectively, but I cannot do anything to `&` -- but then, if the user entered `&lt;`, that will be converted to `<` in the output. So it seems there is no way to let Highcharts reproduce the user input. Or did I miss something?

**Comment by ffdybuster** [comment]
Found a solution myself: for series names displayed in the legend, set `legend:{useHTML:true}` and then use usual HTML escaping rules for the series names.
