### ISSUE TITLE
 text overflow for the chart axis title and legend item

### ISSUE THREAD

**Issue by saurabhshah404** [highcharts/highcharts#4658]
Could not handle text overflow for the chart axis title , legend item  and series label
- Legend items: http://jsfiddle.net/highcharts/95qL6qq9/3/
- Axis title: http://jsfiddle.net/highcharts/hb0ncnng/1/
- Series Label: http://jsfiddle.net/saurabheq/10bo79q1/

---

Admin edit: added fixed width to demos

**Comment by pawelfus** [comment]
Notes:

- Axis title: it should be `xAxis.title.style` not `xAxis.style`. When setting fixed width for the title, it works properly: http://jsfiddle.net/hb0ncnng/2/ (maybe we can assume that `xAxis.title` width should be less than `container-width`/`xAxis.width`?)
- Legend items: the same as above, it works with fixed width: http://jsfiddle.net/95qL6qq9/4/ - again, maybe we should consider max width for the legend item to be the same as container-width? So apply wrapping or ellipsis (depending on the user options)
- Series data labels: current [`dataLabels.overflow`](http://api.highcharts.com/highcharts#plotOptions.series.dataLabels.overflow) works in a different way. It should be `dataLabels.style.textOverflow`. Once again, we need to set `dataLabels.style.width` to use `ellipsis`. I'm not sure how could this handled without fixed width. Maybe use `point.closestPointRangePX` as width, when `style.width` is not set explicitly.

**Comment by saurabhshahpune** [comment]
1) for Axis title need to consider xAxis.width
2) container width can be considered for legend.
3) yes, you may be right for this.

**Comment by kzoon** [comment]
I think the proposed solution for the text overflow in legend would also solve my problem:
See http://jsfiddle.net/6mfz777v/3/
In that example I could set itemStyle width, but then I need to take into account the space needed for symbol and padding. It would be useful if HighCharts could calculate a max width for legend items. Any plans to implement that solution in the near future?
