### ISSUE TITLE
Column Satcked chart - Bar's color opacity not comes to 1 after drillup

### ISSUE THREAD

**Issue by screamy** [highcharts/highcharts#4667]
Steps to reproduce:
1) Example http://jsfiddle.net/qm1oL7vj/2/
2) Click on any bar
3) Click on back button
4) As a result one color is lighter than it should be

Details:
- highcharts.js +  adapters/standalone-framework.js
- browser - Chrome 46.0.2490.71

![screenshot 2015-10-15 16 50 14](https://cloud.githubusercontent.com/assets/664702/10515665/286a8602-735d-11e5-9ef2-57d52c52b862.png)

**Comment by sebastianbochan** [comment]
+1

**Comment by sebastianbochan** [comment]
Workaround: disable animations.

Example: http://jsfiddle.net/qm1oL7vj/3/

**Comment by screamy** [comment]
Animation it's like a nice to have option.
One workaround is to set opacity to 1 manually: http://jsfiddle.net/qm1oL7vj/4/
But as a result we lose animation for opacity

**Comment by highslide-software** [comment]
It's an issue with the Standalone Framework - using jQuery it doesn't happen.

**Comment by pawelfus** [comment]
Standalone minified demo: http://jsfiddle.net/zwfqqyps/1/ - looks like second animation doesn't trigger `stop()` to finish previous animation.

**Comment by pawelfus** [comment]
Just a guess, before removing timer [here](https://github.com/highslide-software/highcharts.com/blob/master/js/adapters/standalone-framework.src.js#L601) we should call it (`timer(true)`) first? So previous animation will be finished.

**Comment by highslide-software** [comment]
Okay, if it works with other cases of stop then feel free to commit it.

**Comment by pawelfus** [comment]
Huh, no it's not. It works correctly with basic example I prepared, but with original test case (with drilldown) cause... Maximum Stack error. It looks like two connected, but different issues.

**Comment by sebastianbochan** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Fails since bdb9dd2
