### ISSUE TITLE
Zones - markers' fill for positive values 

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#4670]
Demo: http://jsfiddle.net/pq47vrbh/

Only orange (negative - I guess) markers have proper fill.

**Comment by pawelfus** [comment]
Connected to #3636.

The main question is what should have higher priority on hover? Zone-color or `point.states.hover.color`?

**Comment by maschwenk** [comment]
It seems to me that zone-color is more intuitive but maybe only overridden when point.states.hover.color is actually user defined. Is that possible?

**Comment by highslide-software** [comment]
I agree with @maschwenk . `point.states.hover.color` is not defined by default.

**Comment by goodforenergy** [comment]
Would love this fix, will it make it into the next release?

**Comment by TorsteinHonsi** [comment]
It will now, thanks for writing!

**Comment by goodforenergy** [comment]
Thanks! :)

**Comment by goodforenergy** [comment]
Hi all. Is it expected that column type charts still get series fill on hover, even when zones are specified (as seen [here](http://jsfiddle.net/29a0hmx3/))? I was hoping they'd behave like their [line marker counterparts](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/series/color-zones-simple/).

If not, is there a way to override the default behaviour to achieve this?

**Comment by pawelfus** [comment]
It's issue with `brightness` which sets a color for a point (even when udefined - color is inherited from series). For workaround, set `colorByPoint: true`, demo: http://jsfiddle.net/29a0hmx3/1/

**Comment by goodforenergy** [comment]
@pawelfus wonderful, thanks! Is that an issue you'd like me to raise, or expected behaviour?

**Comment by obar** [comment]
It looks like I'm still seeing this issue when points are dense enough for markers to be hidden because of overlap (large radius, wide display). `hover` state shows red markers for both of these points in this modified demo: http://jsfiddle.net/ncchm8v1/

Should this issue be reopened or is this a different one?
