### ISSUE TITLE
Flags overlap when they are close  date to each other

### ISSUE THREAD

**Issue by bharathd** [highcharts/highcharts#4674]
flags are overlapping with close date.so how to  avoid such kind of  issue
Below is sample
http://jsfiddle.net/JppHN/7/

**Comment by pawelfus** [comment]
As stated in #4692: for now, `stackDistance` supports only when two flags are **exactly** in the same place (the same `x`-value). 

As for workaround, consider using plugin for flags grouping, see: http://www.highcharts.com/plugin-registry/single/41/flags-grouping

**Comment by bharathd** [comment]
After using flags grouping also still facing overlapping issue.can u please solve the issue in the below url 
http://jsfiddle.net/JppHN/7/

**Comment by pawelfus** [comment]
Sure, here is an example: http://jsfiddle.net/JppHN/8/ - 

**Note:**
You need to set more `flagsGrouping.groupings` options, my jsFiddle is just an example.

**Comment by niketh90** [comment]
Hi

Can this plugin be modified to stack the flags one above the other instead of grouping it and not being shown on the chart.

**Comment by bharathd** [comment]
overlapping issue is solved but when we scroll the navigator still i can see the overlapping .As niketh suggested can we make the flags one above the other?

**Comment by pawelfus** [comment]
Hmm.. plugin's name is "Flags grouping", so I guess it won't do what you described (note: I'm not the author of that plugin).

**Comment by bharathd** [comment]
I can understand that if any alternate solution is there let me know. anyone is working on this issue(highchart team) because this overlapping causing a serious problem ,which is dependent on the individual flag information.
Due to overlap i am unable to fetch the data.

**Comment by pawelfus** [comment]
Connected [UserVoice](http://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/7303396-prevent-flags-overlap) idea.

**Comment by pawelfus** [comment]
I created simple snippet plugin-style, which detects label collision and increments label position. See plugin in action: http://jsfiddle.net/p037jdyj/

Code:

    (function (H) {
        function collide(a, b) {
            return !(b.x > a.x + a.width || b.x + b.width < a.x || b.y > a.y + a.height || b.y + b.height < a.y);
        }

        H.wrap(H.seriesTypes.flags.prototype, 'drawPoints', function (p) {
            var series = this,
                chart = series.chart,
                overlap = true,
                counter = 0,
                index,
                offset = series.options.stackDistance,
                currentBBox,
                compareBBox,
                compareSeries;

            p.call(this);

            while (overlap && counter < 100) { // as long as flags do overlap, move them. Extra limiter up to 100 iterations.
                overlap = false;
                H.each(series.points, function (currentPoint) {
                    if (currentPoint.graphic) { // only existing point with label

                        index = 0;
                        currentBBox = {
                            x: currentPoint.graphic.translateX,
                            y: currentPoint.graphic.translateY,
                            width: currentPoint.graphic.width,
                            height: currentPoint.graphic.height
                        };

                        for (; series.index - index >= 0; index++) { // compare only with previous series

                            compareSeries = chart.series[index];

                            if (compareSeries.options.type === "flags") { // only flag type seires

                                H.each(compareSeries.points, function (comparePoint) { // compare current label with all others
                                    if (compareSeries === series && comparePoint.index >= currentPoint.index ) {
                                    	return; // perf
                                    }
                                    
                                    if (comparePoint.graphic) { // only existing point with label
                                        
                                        compareBBox = {
                                            x: comparePoint.graphic.translateX,
                                            y: comparePoint.graphic.translateY,
                                            width: comparePoint.graphic.width,
                                            height: comparePoint.graphic.height
                                        };

                                        if (collide(currentBBox, compareBBox)) { // when collide, move current label to top
                                            overlap = true;
                                            currentPoint.graphic.attr({
                                                y: currentPoint.graphic.attr("y") - offset,
                                                anchorY: currentPoint.plotY
                                            });
                                            currentPoint.tooltipPos[1] -= offset;
                                        }
                                    }
                                });
                            }
                        }
                    }
                });
                counter++;
            }
        });
    })(Highcharts)

Let me know how it works for you!

**Comment by prettycode** [comment]
This worked great for me--thanks!

**Comment by mykbaker** [comment]
This issue is 1.5 years old, any update on a built in fix? This is not really an enhancement but a bug fix since the flags are unusable if they overlap.

**Comment by niketh90** [comment]
Any updates on flag overlap fix?

**Comment by TorsteinHonsi** [comment]
@pawelfus

**Comment by TorsteinHonsi** [comment]
I applied the `Highcharts.distribute` algorithm to distribute the stacks along the X axis. See the change in action here: http://jsfiddle.net/highcharts/vu89r1fo/1/ .

**Comment by kuerbiskern** [comment]
The change works very well when having only some flags, well done. 

However, charts with a lot of flags become unusable, see http://jsfiddle.net/o4hpdnct/ 
Before change 57c8107, flags overlapped and i needed to zoom to see them, but it looked okay and worked very well. Now, flags are distributed only in x (they do not stack) and spread along the whole screen. 

Is there an option to modify or turn this flag-distribution behavior off 
(e.g.below a certain zoom level, or set a certain distribution limits)

Thanks

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestion, yes of course we need an option to toggle this. Added the option called `allowOverlapX` that defaults to `false`. See http://jsfiddle.net/o4hpdnct/1/.

**Comment by kamalprakhar** [comment]
@TorsteinHonsi `allowOverlapX` doesn't seem to be working for different flag series.

**Comment by TorsteinHonsi** [comment]
@kamalprakhar That's right. See https://jsfiddle.net/highcharts/fbaxvnw2/ . @pawelfus  FYI.

**Comment by pawelfus** [comment]
Thank you for the heads up!

**Experimental feature:**

Demo: https://jsfiddle.net/BlackLabel/wp3fLdhs/

Known limitations (should be solved before publishing official support):
- [ ] - it doesn't work with multiple panes, ALL flags are treated equally (might not be a problem at all, since usually there is only one xAxis, but multiple yAxes)
- [ ] - it does not disable the initial functionality, we can observe extra animation upon initial load

*Internal note:*
Implementation is exactly the same, as the existing one, just taken out from Series level, and moved to a Chart level (thus can work with all Flag series on the chart). Just like DataLabels distribution works.

Plugin:
```ts
(function (H) {
  H.addEvent(H.Chart.prototype, "render", function () {
    const boxesMap = {};
    const allPoints = [];

    // First gather flags:
    for (const series of this.series || []) {
      if (
        series.visible &&
        series.is("flags") &&
        series.options.allowOverlapX === false
      ) {
        for (const point of series.points) {
          if (point.visible) {
            allPoints.push(point);
            const shape = point.options.shape || series.options.shape;
            if (!boxesMap[point.plotX]) {
              boxesMap[point.plotX] = {
                align: shape !== "flag" ? 0.5 : 0,
                size: point.graphic.width || 0,
                target: point.plotX,
                anchorX: point.plotX,
              };
            } else {
              boxesMap[point.plotX].size = Math.max(
                boxesMap[point.plotX].size,
                point.graphic.width || 0,
              );
            }
          }
        }
      }
    }

    // Now distribute:

    // Handle X-dimension overlapping
    let maxDistance = 100;
    const boxes = [];

    H.objectEach(boxesMap, function (box) {
      box.plotX = box.anchorX;
      boxes.push(box);
      maxDistance = Math.max(box.size, maxDistance);
    });
    

    // If necessary (for overlapping or long labels)  distribute it
    // depending on the label width or a hardcoded value, #16041.
    H.distribute(
      boxes,
      this.inverted ? this.yAxis[0].len : this.xAxis[0].len,
      maxDistance,
    );
    
    for (const point of allPoints) {
      const plotX = point.plotX,
        graphic = point.graphic,
        box = graphic && boxesMap[plotX];

      if (box && graphic) {
        // Hide flag when its box position is not specified
        // (#8573, #9299)
        if (!H.defined(box.pos)) {
          graphic.hide().isNew = true;
        } else {
          graphic[graphic.isNew ? "attr" : "animate"]({
            x: box.pos + (box.align || 0) * box.size,
            anchorX: point.anchorX,
          }).show().isNew = false;
        }
      }
    }
  });
})(Highcharts);
```
