### ISSUE TITLE
Mouse event on wrong point

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#4679]
Demo: http://jsfiddle.net/bsrnhuna/

Steps:

- mouse over green series
- mouse over sun
- click on sun - nothing happens

If we hover directly sun (without hovering other spline series) - we can proper click. 

I think we should follow the order of the z-indexes when it comes to mouse events. It is more intuitive to get click event on top most SVG shape. 

Probably connected to the way we search for the closest point to the mouse and we already have some hovered series.

**Comment by pawelfus** [comment]
**Workaround:**

Bind click event to `plotOptions.series` and filter out unnecessary click events: http://jsfiddle.net/bsrnhuna/2/

**Comment by pawelfus** [comment]
Better example: http://jsfiddle.net/bsrnhuna/3/ - with enabled tooltip, we can see what exactly happens: 

- tooltip can show "green" tooltip even when hovering "sun" series - when we click in such case, event is not called, because in our terms, we are hovering green point' series
- works better on master branch (4.1.9-modified), but still can happen

**Comment by sebastianbochan** [comment]
+1

**Comment by pawelfus** [comment]
Problem comes from [this line](https://github.com/highcharts/highcharts/blob/7e24fad4dfc6aa1057e6a5e25220196b52357910/js/parts/Pointer.js#L174). In fact there should be `<=`, because series with higher indexes are rendered on top of previous series. However, that still may be problem if we get setting like this:

    series: [{
       data: [ ... ],
       index: 0,
       zIndex: 5
    }, {
       data: [ ... ],
       index: 1,
       zIndex: 1
    }]

Since `zIndex` is not set in Series class, we should make this checking:

              if (typeof p[dist] === 'number' && (p[dist] < distance[k] || (p[dist] === distance[k] && pick(p.series.options.zIndex, 1) >= pick(kdpoint[k].series.options.zIndex, 1))) ) {
                distance[k] = p[dist];
                kdpoint[k] = p;
              }

And we get little `if`-monster. Maybe we should set default `series.zIndex` (like `1` etc.) @TorsteinHonsi ?

**Comment by trpriel** [comment]
Seems like a very simple fix. 
Is this going to be deployed in the version?

**Comment by onemenny** [comment]
We face the same issue to, The code is already here can this be pushed forward?

**Comment by TorsteinHonsi** [comment]
* Simplified: http://jsfiddle.net/highcharts/thte3ffx/
* Simplified with `zIndex`: http://jsfiddle.net/highcharts/thte3ffx/1/

In both cases we would expect the tooltip to show Series 2 in the crossing point, because it is higher in Z index.
