### ISSUE TITLE
Pie Title useHTML:true causes unwished extra space

### ISSUE THREAD

**Issue by mapodev** [highcharts/highcharts#4688]
Using highchart for pies with option useHTML:true for title causes extra space in my highchart between the title and chart itself. This only happens for the pie chart, whenever using useHTML in true mode, when I turn it off to false then there is no such disaster. And it only happens when loading it for the first time, on refresh the chart is shown the right way.

This image is when useHTML on true and loading it the first time, there is space between the title and the pie chart.

![usehtmltrue](https://cloud.githubusercontent.com/assets/9727382/10735380/f62dad8c-7c07-11e5-9ab6-fd4cfe1dd486.png)

After refresh, it looks right.

![usehtmlfalse](https://cloud.githubusercontent.com/assets/9727382/10735382/f80ef41c-7c07-11e5-9f98-4e912ae02503.png)

But I need the useHTML mode switched to true. So how can be this resolved.

**Comment by pawelfus** [comment]
Could you setup live demo (e.g. jsFiddle)? Just tested, works fine: http://jsfiddle.net/uw3j3s6x/

**Comment by mapodev** [comment]
Yes, this JSFiddle http://jsfiddle.net/4n2eotn4/1/ is the same option json but it doesn't show the effect which I have on my side.

**Comment by pawelfus** [comment]
Could you upgrade Highcharts to 4.1.9 version? It may be bug in on of the old versions.

**Comment by mapodev** [comment]
Already did, no changes.

**Comment by sebastianbochan** [comment]
It seems to working fine since v4.2.7.

Reopen if problem will come again.
