### ISSUE TITLE
Dragging causes pie slices to disappear in IE7

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#47]
Report: http://highslide.com/forum/viewtopic.php?f=9&t=7089
Demo: http://jsfiddle.net/highcharts/KSAfE/13/

When using IE7 or IE8 compat, place your mouse cursor over one of the pie slices so that the tooltip pops up. Then, while the tooltip is shown, left-click and hold to drag the chart to another spot. When you drop the box, the slices below the tooltip will disappear.

**Comment by KacperMadej** [comment]
Still valid in 5.0.7 when dragging by pie slices

**Comment by KacperMadej** [comment]
The problem appears only in case the third party sortable widget is used. It's possible to resolve the issue through calling chart / series update that will force redraw the shapes.
```js
  $('#sortable').sortable({
    stop: function() {
        pieChart.update({
            series: [{}]
        });
    }
  });
```

This seems to be a more a technical support case than a bug.
Closing as possible to be resolved with provided code, but this issue could be reopened if you have more comments and info about the problem.
