### ISSUE TITLE
JavaScript typed array for data series support

### ISSUE THREAD

**Issue by max0x7ba** [highcharts/highcharts#4705]
Sometimes data series come as JavaScript typed arrays, for example, `Int32Array`. 

Highcharts as of version 4.1.9 does not seem to support such arrays and I need to call `Array.from(int32array)` before passing it to Highcharts.

It would be nice if Highcharts supported JavaScript typed arrays natively.

**Comment by sebastianbochan** [comment]
Fixed since v5.0.11.

Demo:
- http://jsfiddle.net/k4dkx0cz/
