### ISSUE TITLE
Font issues in High bar chart in document mode IE8 and ie7 in mvc

### ISSUE THREAD

**Issue by niteshparihar5** [highcharts/highcharts#4707]
![highchartissues](https://cloud.githubusercontent.com/assets/14329667/10878933/f60b103c-8176-11e5-82f7-3593139ca044.png)
Hi Support Team,

I am getting font issues in High bar chart in document mode IE8 and IE7 in ASP.NET MVC.
Please help me for the same.

THanks 
![highchartissues](https://cloud.githubusercontent.com/assets/14329667/10878933/f60b103c-8176-11e5-82f7-3593139ca044.png)

Nitesh Kumar

**Comment by pawelfus** [comment]
Your image isn't loaded, could you upload it once again? 
Also, could you setup jsFiddle demo with that issue (note: **/show** at the end of jsFiddle would be necessary to make it work in IE7/8).

**Comment by pawelfus** [comment]
Note: Looke like a duplicate of #663.
