### ISSUE TITLE
Pie Chart adds duplicate slice on redraw

### ISSUE THREAD

**Issue by sa101** [highcharts/highcharts#4711]
In my case I am updating the Pie Chart with new data and doing a redraw once all the update to data is done. The problem happens when I remove a point from the existing data as the new data doesn't have that point anymore, and also update the remaining points with new value, upon redraw the Pie Chart shows a duplicate slice to fill the space for the removed point. Check the jsFiddle http://jsfiddle.net/sa101/25ajh3tt/ , when you click the Remove Slice the pie updates with a duplicate slice.

**Comment by pawelfus** [comment]
How about using simple `setData()` instead of updating each point, one-by-one? See: http://jsfiddle.net/25ajh3tt/4/

**Comment by sa101** [comment]
Yes I tried that but the problem is that I do not get the animation or the smooth transition in that case which is important for my case. But if I update the point one by one and then do redraw the smooth transition works. Sorry I forgot to mention that the animation is a must have for me.

**Comment by pawelfus** [comment]
Then how about removing points, and later using `setData()`? See: http://jsfiddle.net/25ajh3tt/5/

**Comment by pawelfus** [comment]
Huh, simple `redraw=true` for `point.remove(true, false)` works around the issue in some easy way :) See: http://jsfiddle.net/25ajh3tt/9/

**Comment by pawelfus** [comment]
*Internal note:*

`remove` don't update points's index's, so later, when updating points, we update wrong points. `point.index` is set in `generatePoints()` method, now the question: should we call `generatePoints()` in `point.remove()` or rather simply loop over all existing points and update it's indexes?

**Comment by sa101** [comment]
Thanks for the workaround, that's what I figured too. So at this point I don't have any more update on this, but does it matters if we keep this issue open or close it ?

**Comment by pawelfus** [comment]
Let's keep it open until will be fixed :)

**Comment by sebastianbochan** [comment]
Fixed since v5.0.
