### ISSUE TITLE
IE8 / IE11 - missing points 

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4714]
In case when we set 8190 points then chart is printed, but when more, points are missing (like 8193). Looks like problem with path, because scatter (without lineWidth) works properly.

Examples:
- http://jsfiddle.net/74p0vo4e/6/
- http://jsfiddle.net/74p0vo4e/7/

**Comment by highslide-software** [comment]
Did you reproduce this on IE9 and IE10 as well? My IE11 VM isn't working currently, so I couldn't reproduce.

**Comment by KacperMadej** [comment]
IE9, IE10, IE11 - are working fine.
IE8 - showing the error.
