### ISSUE TITLE
Print action - one state is white instead color

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4715]
Example: 
- http://www.highcharts.com/maps/demo/data-class-two-ranges

Click ctrl+p / cmd + p and then you can observe that Kentucky state is white, instead of red.

**Comment by highslide-software** [comment]
Appears in Chrome. Firefox is okay.

**Comment by sebastianbochan** [comment]
Looks like fixed since 4.2.1, reopen when problem will come again.
