### ISSUE TITLE
chart.getSelectedPoints is updated after point.events.select

### ISSUE THREAD

**Issue by zevero** [highcharts/highcharts#4717]
See here:
http://jsfiddle.net/r117bk5d/

Shift click on several points
-> the last point is not reported to be selected

Normal click on another point
-> all shift-clicked points are reported, but not the new one

**Comment by GoodVibesDevelopment** [comment]
Hey, i also have this problem.

As a workaround you can surround getting selected points with `setTimeout` function. Here is a fiddle: http://jsfiddle.net/b39j7jkx/

**Comment by zevero** [comment]
This is already old ... everything seems to work now.
I do not see any setTimeout in your fiddle. There seems to be no difference in code to my fiddle.

**Comment by GoodVibesDevelopment** [comment]
Im using version 5.0.14 and there problem exists. Sorry for fiddle, thats the correct one: http://jsfiddle.net/GoodVibesDev/wd79cmo7/1/

**Comment by zevero** [comment]
ok ... but I think there is still no need to reopen this thread as it works in 6.x ... and you found your workaround.
