### ISSUE TITLE
Dynamic update with dataGrouping corrupts the chart

### ISSUE THREAD

**Issue by priikone** [highcharts/highcharts#4728]
Based on the original dynamic Highstock demo, here's a fiddle (http://jsfiddle.net/b4cacv2f/) that updates the chart dynamically every 50 milliseconds with 5 minute dataGrouping.  Run the test for around 5-6 seconds and you'll see how the chart goes totally bonkers.  If the dataGrouping is removed everything appears to work fine.

Noticed this while doing a stock chart which is updated with live trade data.  In my testing I'm using candlesticks but the behavior appears to be identical to what the fiddle above has.

I've noticed also similar problems when the addPoint() is done with shift and the chart is zoomed in. The shift appears to happen in some strange fashion. My guess is that each live update (which has a millisecond resolution and can come in in irregular intervals) actually shifts the navigator by the dataGrouping unit (like 5 minutes) or by one data-point in the group causing the chart to run out of data points after a couple minutes... Dunno if it's related. I can create a separate issue for that if needed.

Also notice my thread at forums http://forum.highcharts.com/post120232.html where I'm discussing other issues with addPoint() and dataGrouping.

**Comment by priikone** [comment]
I've noticed also similar problems when the addPoint() is done with shift and the chart is zoomed in.  The shift appears to happen in some strange fashion.  My guess is that each live update (which has a millisecond resolution and can come in in irregular intervals) actually shifts the navigator by the dataGrouping unit (like 5 minutes) causing the chart to run out of data points after a couple minutes... Dunno if it's related.  I can create a separate issue for that if needed.

**Comment by priikone** [comment]
I've noticed that the latest version doesn't go crazy anymore, but it's still easy to trigger it by moving the navigator; pull the navigator left, then pull it again all the way to right, and the chart goes crazy again.

**Comment by pawelfus** [comment]
Ok, it's not a bug. This is result of rendering only 1min range, with dataGrouping 5min. Once dataGrouping kicks in we don't see all points. 

Either range should be increased (to e.g. 5min) or dataGrouping should be set for 1min too: http://jsfiddle.net/BlackLabel/b4cacv2f/9/
