### ISSUE TITLE
Firefox / Edge bug with a big data rendering (highstock)  

### ISSUE THREAD

**Issue by l-liava-l** [highcharts/highcharts#4731]
Hi!
I use Highstock JS v2.1.9 (2015-10-07) for the visualization of the hash rate and blocks. 
But I have a problem with big volumes of data (sometimes more then 4mb). 
Bug only in Firefox and Edge.

For example (loading will be started automatically, so wait): 
http://www.a-xbt.com/#/stat/1CjPR7Z5ZSyWk6WtXvSFgkptmpoi4UM9BC 

As can you see chart is not drawn. 

Probably have to divide into pieces. :(

**Comment by highslide-software** [comment]
Sounds like you are loading a huge number of data points - have you tried using the [Boost module](http://www.highcharts.com/component/content/article/2-news/175-highcharts-performance-boost)?

**Comment by jon-a-nygaard** [comment]
Closing this as it is pending a reply. Should anyone have further information on the issue, please give us a comment.
