### ISSUE TITLE
Plot lines added with addPlotBandOrLine are destroyed on axis.update

### ISSUE THREAD

**Issue by cmmartin** [highcharts/highcharts#4733]
If you add a plot line (or band) using `axis.addPlotBandOrLine` and then call update on that axis, the added plot line will be destroyed despite not being overwritten. This is only an issue with `addPlotBandOrLine` and not when adding the plot line as a user option or with simply `addPlotLine`. 

Here is an example...

https://jsfiddle.net/123eb08s/

I think `axis.update` probably merges the userOptions with the new options and re-creates the axis. For whatever reason, plot lines added with `addPlotBandOrLine` never make it into the userOptions for the axis, so they are lost on update

**Comment by pawelfus** [comment]
Why do you use `addPlotBandOrLine()`, not `addPlotLine()` or `addPlotBand()`?

It doesn't work in your case, because you use that method with just one argument, while required is also type, for example:

    addPlotBandOrLine(options, `plotLines`);
    addPlotBandOrLine(options, `plotBands`);

**Comment by TorsteinHonsi** [comment]
`addPlotBandOrLine` is not a documented API method.
