### ISSUE TITLE
PDF export: chart doesn't fit on one page

### ISSUE THREAD

**Issue by ffdybuster** [highcharts/highcharts#4735]
I've a problem with Highcharts PDF export. Minimal example JSON input: 

``` .json
{"series":[{"data":[[0,0],[1,1]]}]}
```

The PDF is split up into two pages, where the chart exceeds the width of the page and parts of the chart end up on the second page:
![chart-pdf-output](https://cloud.githubusercontent.com/assets/12152708/11121627/3eadd562-8957-11e5-8ce1-35d90db8f25d.png)

I can fix this by re-adding the two lines

``` .js
clipwidth = clipwidth * dpiCorrection;
clipheight = clipheight * dpiCorrection;
```

removed in e839a6c879953434017af719e7f8abf5def8e0a9; after that, the graph fits nicely (and completely) on one PDF page.

I've tested this with phantomjs 1.9.0 and Ubuntu 14.04, as well as phantomjs 1.9.8 and Debian 7 (in a docker container); the behaviour is identical in both cases.

**Comment by highslide-software** [comment]
@gvaartjes Alraedy fixed in e839a6c879953434017af719e7f8abf5def8e0a9?

**Comment by ffdybuster** [comment]
That commit removed the lines; without these lines, the output is wrong for me. With these lines re-added, it works fine.

**Comment by gvaartjes** [comment]
We have to test this. The question is, if we might have brokne backwards compatibility for phantomjs 1.9, when we upgraded to phantomjs 2.0.
