### ISSUE TITLE
Opposite xAxis labels overlap the chart

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#474]
In this example: http://jsfiddle.net/kzoon/KYcgF/ the x axis is configured with `opposite: true` and the labels span two lines. The second line overlap the chart iteself.

Expected: That the axis layout is large enough to hold wrapped lines if there are any.

**Comment by pawelfus** [comment]
Works fine with autoRotation feature. Also when disabled: http://jsfiddle.net/KYcgF/42/

**Comment by Izothep** [comment]
The problem is still present for labels with more than two lines on axis. 
http://jsfiddle.net/KYcgF/49/

As a workaround I have written simple function for translating labels:
http://jsfiddle.net/KYcgF/48/

**Comment by jbgarr** [comment]
+1

I'm still seeing this issue with labels that are more than two lines long. Also @Izothep it seems your solution is not working, at least not in the js fiddle you linked to.

Any help here would be appreciated.
