### ISSUE TITLE
lots of undocumented functions in highcharts.js API

### ISSUE THREAD

**Issue by tonylukasavage** [highcharts/highcharts#4741]
Had it not been for perusing the source code first, I would have re-implemented the existing `translate()` and `rotate()` functions on `SVGElement`. Upon realizing these functions existed on those objects, I found that there's a number of functions on `SVGElement` and other objects that are not present in the [API docs](http://api.highcharts.com/highcharts) but are available programmatically.

Is there a reason these functions are undocumented, or is this a bug?

**Comment by KacperMadej** [comment]
Not documented features are for internal use. If a feature / function / option is not a part of API then it might be changed without prior notification after any next version release, so if you want to use the undocumented features make sure to check if nothing has changed after updating to a newer version. Not a bug.
