### ISSUE TITLE
x|yAxis.visible : false is ignored on the export module

### ISSUE THREAD

**Issue by d0x** [highcharts/highcharts#4745]
Hi, the x|yAxis.visiblity attribute is ignored on the export server.

When the following configuration is send through the `options` parameter, the visiblity will be ignored.

    {
      "chart" : {
        "type" : "bar"
      },
      "series" : [ {
        "name" : "Foo",
        "data" : [ 0.9535 ]
      } ],
      "xAxis" : {
        "visible" : false
      },
      "yAxis" : {
        "visible" : false
      }
    }

You can test this with this link:

http://export.highcharts.com/?options={%22chart%22:{%22type%22:%22bar%22},%22series%22:[{%22name%22:%22Foo%22,%22data%22:[0.9535]}],%22xAxis%22:{%22visible%22:false},%22yAxis%22:{%22visible%22:false}}

**Comment by highslide-software** [comment]
@gvaartjes: The export server is still running 4.1.8...

**Comment by gvaartjes** [comment]
This will be updated asap!

Best regards,

Gert
Highsoft

**Comment by d0x** [comment]
Thanks for giving feedback.

Good luck ;D

**Comment by gvaartjes** [comment]
Hi, our server is updated with 4.1.9. I verified the visibility feature is working now

It took a liitle longer time than usual, due to moving the export-server to another repository: https://github.com/highcharts/highcharts-export-server

Thanks for your patience,

Gert
