### ISSUE TITLE
Extremely high cpu usage on Mac

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#475]
This is a performance bug that appears in firefox/chrome/safari on Mac.
The example below have three charts with 1000 points each and updating each second by shifting in one point.

On windows and running chrome the cpu usage roughly stays at 2-4% (depending on hardware of course) but on Mac it stays constanly on 100% not even able to do finish the update in time.

http://jsfiddle.net/highcharts/979n2/23/

**Comment by oysteinmoseng** [comment]
Closing, as it seems to behave as expected on Mac now. Feel free to reopen if issues are still found.
