### ISSUE TITLE
Treemap: Inconsistent data label behavior

### ISSUE THREAD

**Issue by andrei-picus-hs** [highcharts/highcharts#4751]
Data labels are rendered inconsistently between resizing a treemap and rendering it fresh.

![treemap](https://cloud.githubusercontent.com/assets/12442713/11238015/a9ac8c80-8deb-11e5-8194-b169081d42d9.gif)

**Comment by pawelfus** [comment]
Could you setup jsFiddle demo with that issue? We will check this.

**Comment by andrei-picus-hs** [comment]
@pawelfus http://jsfiddle.net/sz0esszz/

**Comment by pawelfus** [comment]
Thanks!

*Internal note:*
Compare: http://jsfiddle.net/sz0esszz/2/ (after click) vs http://jsfiddle.net/sz0esszz/3/ - both examples get the same width (470px), but the first one is missing labels.

**Comment by jon-a-nygaard** [comment]
This issue will be fixed in the upcoming maintenance release. For those in need of a workaround take a look below.

__Workaround__
Open the `treemap.src.js` source file in a text editor. Locate the `drawDataLabels` function around line 612. Find and replace the following code snippet:
```javascript
// replace this
if (point.shapeArgs) {
	options.style.width = point.shapeArgs.width;
}

// with this
if (point.shapeArgs) {
	options.style.width = point.shapeArgs.width;
	if (point.dataLabel) {
		point.dataLabel.css({ width: point.shapeArgs.width + 'px' });
	}
}
```
