### ISSUE TITLE
Point update cases misaligining crosshair when dragged

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4752]
When we move point up/down then crosshair is not in the same place, but "jump" between different x value.

Reproduction steps:
1. Open http://jsfiddle.net/utnz2b9e/39/
2. Drag the last point up and down

**Comment by BradGoldsberry1** [comment]
Any word on this?

**Comment by sebastianbochan** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Sorry for the delay!

@sebastianbochan The provided demo doesn't have a plotband or point update...

**Comment by pawelfus** [comment]
It's not plotBand, it's crosshair. Try to drag&drop last point in the second series.

**Comment by BradGoldsberry1** [comment]
The behavior can be seen when dragging a blue point on the right side of the chart. When dragging, the crosshair flickers back and forth between that point and the x-value of the last non-null data point of the other series. In addition, the tooltip flickers and makes it hard to look at.

**Comment by TorsteinHonsi** [comment]
It may also be a bug with the draggable-points plugin.

**Comment by pawelfus** [comment]
I think it may be a bit general issue, see: http://jsfiddle.net/utnz2b9e/45/  (hover updating point and move mouse without leaving the category).
![update](https://cloud.githubusercontent.com/assets/1453926/11931477/97f84f3a-a7ed-11e5-8d88-517370fad73a.gif)

**Comment by Izothep** [comment]
+1
