### ISSUE TITLE
Scrollbar and AxisType:Datetime : After how many items scroll should come

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#4753]
Is it possible to control after how many points scroll bar should come?
See below URL :

http://jsfiddle.net/pawanvjadhav/Lrtpdm18/

In case of Number and String values on X axis, i achieve this using max attribute of x axis. How can i achieve this in case of DateTime axis.

http://jsfiddle.net/pawanvjadhav/3twcwb34/1/

I am not sure whether this way is right or wrong? Is there any better solution.

**Comment by pawanvjadhav** [comment]
any updates or comments?

**Comment by pawelfus** [comment]
You can achieve the same using.. `max` on datetime, still. See: http://jsfiddle.net/Lrtpdm18/2/ 

Note: `x` for datetime axis should be timestamp. 

For support questions, please use our forum/email: http://www.highcharts.com/support

**Comment by pawanvjadhav** [comment]
but in this way, i need to have information about values. 
Can i configure like if number of ticks are more than 10, show scroll bar

**Comment by pawelfus** [comment]
Of course, take a look: http://jsfiddle.net/Lrtpdm18/3/ - add several points to enable the scrollbar: http://jsfiddle.net/Lrtpdm18/4/

**Comment by mosijava** [comment]
it's a pity that we should use highstock and can't use highcharts to achieve this. :-(
for someone like me who lives in a country with very low salary purchasing another 1400$ is more than expensive.

**Comment by pawelfus** [comment]
Hi @mosijava 
If you have Highcharts license, then it's not necessary to buy another one for Highstock - instead you can upgrade your license to Highstock. Highstock license contains Highcharts product too. Please contact our sales department: https://shop.highsoft.com/contact
