### ISSUE TITLE
Add jQuery dependency in the exported bower.json file

### ISSUE THREAD

**Issue by filmor** [highcharts/highcharts#4755]
The .bower.json file that accompanies the release should contain a dependency on jQuery so that bower install that one automatically.

I have the particular issue that I'm trying to generate a sensible .js-file ordering from the bower.json files which fails at times in case of highcharts because, not listing any dependencies, it may be loaded before jQuery.

Is there a reason to not list the dependency?

**Comment by highslide-software** [comment]
Highcharts can either run jQuery or the Standalone Framework. In cases where you don't use jQuery for other things on your page, it is recommended to use the Standalone Framework, as it is only 2k. So adding jQuery as a dependency is perhaps not the right approach for those who don't need it.

**Comment by filmor** [comment]
But since the Standalone Framework's javascript file is not recorded in the `bower.json` this will still fail. Could you provide two releases to bower, one depending on the standalone framework and the other using jQuery?

**Comment by TorsteinHonsi** [comment]
I think the best approach would be to just demonstrate this in the installation docs for bower.

**Comment by TorsteinHonsi** [comment]
With Highcharts 4.2 there is no need for a framework or adapter.
