### ISSUE TITLE
[Regression] Point.update doesn't apply point attribute changes in highstock versions >= 4.1.8

### ISSUE THREAD

**Issue by brandonjacob** [highcharts/highcharts#4759]
The Point.update function no longer seems to apply point attribute changes unless a subsequent action is taken (e.g. such as hovering over the data points). This worked fine in highcharts 4.1.7.

The regression is present in highcharts releases >= 4.1.8. It also seems to be a problem in the current master branch. Refer to http://jsfiddle.net/yeud3j26/13/

It seems like variants of this problem have been flagged in multiple earlier bug reports since 4.1.8 was released:
https://github.com/highslide-software/highcharts.com/issues/4267
https://github.com/highslide-software/highcharts.com/issues/2484
https://github.com/highslide-software/highcharts.com/issues/4666

Of interest, it looks like this commit to the Dynamics.js file (https://github.com/highslide-software/highcharts.com/commit/bfa69365117ee8af7319c5f33d9821be15abf898) was responsible for causing the initial regression because it no longer applies the point attributes during a redraw().  The commit message is very brief so it's hard to understand why this commit was most appropriate to resolve an issue with 'animation on updating map colors'.

It looks like several patches have been committed to fix some of the aforementioned issues but it's not clear to me whether point.update problems have been completely addressed nor which commits we would need to cherry pick from your bug branches against 4.1.9. I'm concerned that this specific issue does not seem to be have been addressed in your Master branch.

**Comment by brandonjacob** [comment]
Reverting the change to the Dynamics.js file from commit https://github.com/highslide-software/highcharts.com/commit/bfa69365117ee8af7319c5f33d9821be15abf898 fixes this issue for us in highcharts 4.1.9. 

I realize this is probably not the right fix for your master branch because you had a reason for applying that commit in the first place (fixing map color animation). In our case, we don't leverage your mapping module so reverting this commit seems appropriate in the short-term until a subsequent highcharts release fixes this properly.

**Comment by pawelfus** [comment]
I was pretty sure when fixing #4666, I went over all series types. Looks like I missed general series class. Fixed, see bugfix branch: http://jsfiddle.net/yeud3j26/14/

**Comment by brandonjacob** [comment]
Thank you. That was very quick!

Assuming commit 2a6cd3c finds its way into your next stable release, we will revert our short-term hack when we upgrade.

**Comment by pawelfus** [comment]
Thanks! Let's keep open this issue until will be merged into the master.
