### ISSUE TITLE
Unable to drill down in the case of  plotband or series label set over data point.

### ISSUE THREAD

**Issue by saurabhshah404** [highcharts/highcharts#4762]
Set plot-band or data-label over chart data-point (setting z-index in the case of plot-band) ,does not  generate any event for that point.
i.e http://jsfiddle.net/YWVHx/465/

**Comment by pawelfus** [comment]
Well, this is how SVG works, as I know - similar to positioning two absolute divs ovelapping: only the one with higher z-index will get events. 

You can disable all pointer events on the plotBand in load/redraw event, see: http://jsfiddle.net/YWVHx/467/

    function removeEventsFromPlotBands() {
        var chart = this;

        $.each(chart.axes, function (i, axis) {
            $.each(axis.plotLinesAndBands, function (j, band) {
                if (band.svgElem) {
                    band.svgElem.attr({
                        'pointer-events': 'none'
                    });
                }
            });
        });
    }

And events:

                events: {
                    load: removeEventsFromPlotBands,
                    redraw: removeEventsFromPlotBands,
                }

**Comment by saurabhshahpune** [comment]
Thanks, and how about data-label ? need to do same fix if data-label overlaps i.e Line chart

**Comment by pawelfus** [comment]
Which dataLabel? From the series? I'm not sure about the case - could you setup jsFiddle again?

**Comment by saurabhshahpune** [comment]
Here i try to show alert popup on event click for data-point.
http://jsfiddle.net/saurabheq/o64a81dq/

**Comment by pawelfus** [comment]
For dataLabel, you can set this even in CSS: http://jsfiddle.net/o64a81dq/1/
