### ISSUE TITLE
PDF Export not scaling correctly on PhantomJS

### ISSUE THREAD

**Issue by findoo** [highcharts/highcharts#4764]
Using the instructions provided here - http://www.highcharts.com/docs/export-module/setting-up-the-server, we have created a java + phantomJS export server. All exports seem to work fine except from PDF exports - which renders the chart too small for the document. See JSFiddle http://jsfiddle.net/tj9bzr21/ - our server is running Debian 8.2, with the latest version of PhantomJS, and the latest version of the export-server code from this repository. 

We have also tried doing the same thing on Windows - with the same issue. 

This could be a scaling issue related to https://github.com/ariya/phantomjs/issues/12685

**Comment by highslide-software** [comment]
@gvaartjes FYI

**Comment by gvaartjes** [comment]
Hi, 

The latest version of PhantomJS is 2.0?  I'm asking because the install packages are not officially released. Thought the latest version of the export-server is compatible with version 2.0.

**Comment by findoo** [comment]
@gvaartjes PhantomJS 2.0 was released on January 23 2015, and it's the latest release - http://phantomjs.org/releases.html

**Comment by gvaartjes** [comment]
Hi, Not for Debian... that's why I asked. Maybe you were still on 1.9. So you compiled phantomjs yourself on Debian, or did you use a package from somebody else?

**Comment by gvaartjes** [comment]
Possible related to closed issue #3982

**Comment by jaapz** [comment]
@gvaartjes with javascript packages you are generally better off installing from NPM, because debian repositories tend to lag behind on new releases (by design). Which is good if you want a really stable server or desktop environment, but not so good if you want to make up-to-date software.

The newest phantomjs package can be found here: https://www.npmjs.com/package/phantomjs2

**Comment by gvaartjes** [comment]
@jaapz Phantomjs is not javascript. It's a excutable. The NPM package wraps this executable.

**Comment by jaapz** [comment]
Yes, so? It's still a very convenient way to install phantomjs, especially in javascript projects.

**Comment by findoo** [comment]
@gvaartjes On debian we have compiled it from source yes - however when we tested it on windows we used the official provided executable (with the same results).

**Comment by gvaartjes** [comment]
@findoo thx!

**Comment by oysteinmoseng** [comment]
Appears to be a DPI issue. Added a correction factor setting. For Windows, setting it to 72/96 seems to work. See commit highcharts/highcharts-export-server@daa452ca85d9526f338da8dc1aa23ed5235bd947
