### ISSUE TITLE
Pie chart select function cannot be cancelled

### ISSUE THREAD

**Issue by mikegodber** [highcharts/highcharts#4766]
Hi,

There seems to be an issue with the pie chart point select function. If you return false to cancel the operation then the segment moves to the selected position and then cannot be deselected. This can be seen in a simple example here:

http://jsfiddle.net/duu5hys4/

Regards,

Mike

**Comment by mikegodber** [comment]
As a temporary fix I am calling the Point.slice() method before returning false:

```javascript
select: function(event) {
     if(this.id == "cancel"){
        this.slice(false);
        return false;
    }
}
```

**Comment by TorsteinHonsi** [comment]
The root issue probably lies [on these lines](https://github.com/highcharts/highcharts/blob/v4.1.9/js/parts/PieSeries.js#L59-L64) where the point is sliced before the custom event is handled, so the selection is aborted but the slicing is not.

```js
		// add event listener for select
		toggleSlice = function (e) {
			point.slice(e.type === 'select');
		};
		addEvent(point, 'select', toggleSlice);
		addEvent(point, 'unselect', toggleSlice);
```

Ideally this should be handled in drawPoints or setState, where the slice would get translated attributes based on its state. In HC5 this would be easier.
