### ISSUE TITLE
Live candestick update messes up the chart and navigator

### ISSUE THREAD

**Issue by priikone** [highcharts/highcharts#4767]
See this fiddle: http://jsfiddle.net/382gxxjc/5/.  The purpose of this fiddle is to demonstrate typical live minute bar stock chart at the beginning of a trading day.

It's supposed to do the following:
1. Add new point to Mon October 17 15:30 2011 UTC, the following Monday where the data ended in Friday (data from original Highstock intraday chart).
2. Update that point once a second
3. Add a new point after every minute

What happens are the following:
1. The chart is moved to the new point, but despite ordinal: true by default, the chart shows the gap between Friday and Monday.
2. The last point update is kind of strange, it's slightly outside the y axis and doesn't show the candle completely.
3. The navigator goes kinda crazy, it's as if it's not updating to the correct timestamp.  Try navigating to see the effect.  Also, press the right arrow in the scrollbar for interesting effect.

If you wait long enough (more than couple minutes) you can see that sometimes it starts to work "correctly" again, the gap is removed and zoom about works ok.

I was expecting to see:
1. The new candle added on Monday 15:30, but the Friday still visible (ordinal: true).
2. The navigator extremes "expand" into the new data point.

Note that I'm specifically not using breaks because of https://github.com/highslide-software/highcharts.com/issues/4193.

**Comment by priikone** [comment]
Updated fiddle: http://jsfiddle.net/382gxxjc/6/ with getExtremes + setExtremes when adding the new point seem to fix the ordinal thingy, so that the gap is removed automatically, but the zoom still goes crazy...

**Comment by TorsteinHonsi** [comment]
Added a button for more granular debugging: http://jsfiddle.net/highcharts/382gxxjc/8/
