### ISSUE TITLE
Colors do not change when treemap data changes

### ISSUE THREAD

**Issue by mahlonbook** [highcharts/highcharts#4772]
1) Create a treemap and set the color of each point
2) Update the series and set different values and colors for each point
3) The updated points use the new values, but they use the old colors

Fiddle: http://jsfiddle.net/cc0tx046/

4) If you hover over the updated points, then the color changes to the new color

**Comment by pawelfus** [comment]
It should be already fixed on the master branch, take a look: http://jsfiddle.net/cc0tx046/1/

**Comment by mahlonbook** [comment]
Confirmed it's fixed in the master branch, thank you!
