### ISSUE TITLE
data labels are visible outside plot area after zoom when setting dataLabels.rotation

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#4779]
Data labels are visible outside plot area after zooming,when you set dataLabels.rotation

example:
http://jsfiddle.net/izothep/za52bk5L/6/

![example](https://cloud.githubusercontent.com/assets/15050812/11470835/47dd6b1c-9761-11e5-8cff-8c6821675c38.jpg)

**Comment by TorsteinHonsi** [comment]
It comes down to [this line](https://github.com/highcharts/highcharts/blob/v4.1.9/js/parts/DataLabels.js#L196).
`if (options.rotation) { // Fancy box alignment isn't supported for rotated text`

But to be honest, the crop feature isn't covered by "fancy box alignment", so we should be able to simple test if the label is inside or not.

**Comment by erbrito** [comment]
Do you have plans to fix this issue? By when are you thinking it will be released a fix.
