### ISSUE TITLE
Column borders after changing extremes of y axis.

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#4781]
After changing extremes of y Axis (by setting min and max values or setExtremes() function) column is still having border on the side of threshold. Because of that it looks like it is ending at different point that it should.

example:
http://jsfiddle.net/izothep/x31oay29/3/

**Comment by TorsteinHonsi** [comment]
Simplified: http://jsfiddle.net/highcharts/x31oay29/5/

The issue happens because Axis.getThreshold returns 0 when the actual result is outside the axis extremes. Subsequently, ColumnSeries.translate thinks the column actually ends at axis.max, and the border spills over.
