### ISSUE TITLE
Legend image symbol - width/height not applied

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4782]
Example:
- http://jsfiddle.net/mq1a7qsh/1/

Looks like size is not applied for image markers.

**Comment by TorsteinHonsi** [comment]
The `symbolWidth` setting has a wider meaning, it also applies to the marker line inside the legend.

The correct way of setting the width and height of an image marker symbol is in the marker config itself: http://jsfiddle.net/highcharts/mq1a7qsh/2/.

But this also doesn't affect the legend marker. Would you('r client) be happy if we implement this, or do you require specific handling of the marker in the plot versus the legend?

**Comment by pawelfus** [comment]
I think it should work the same way as for classic marker - the same radius/width/height as in the series. 

Of course, it would be nice feature: set different size of the marker in the legend.

**Comment by Miguel5tuxD** [comment]
> The `symbolWidth` setting has a wider meaning, it also applies to the marker line inside the legend.
> 
> The correct way of setting the width and height of an image marker symbol is in the marker config itself: http://jsfiddle.net/highcharts/mq1a7qsh/2/.
> 
> But this also doesn't affect the legend marker. Would you('r client) be happy if we implement this, or do you require specific handling of the marker in the plot versus the legend?

if I had a vector with many IconUrls just to set on the symbol ? how can I do it ?

**Comment by pawelfus** [comment]
Hi @Miguel5tuxD 

Vector series doesn't have marker in legend, however you can use separate series with the marker of your choice that is rendered in legend. Then the vector series can be linked to this main series taking over legend's on/off feature, take a look: https://jsfiddle.net/BlackLabel/2Lmw6rhj/

See more about `linkedTo` in API: https://api.highcharts.com/highcharts/series.line.linkedTo
