### ISSUE TITLE
Scatter Chart - Negative color isn't working if more than 1000 points.

### ISSUE THREAD

**Issue by Dams591** [highcharts/highcharts#4783]
Hi There,

I believe you have an issue with negative color on a series.
I have a scatter chart with one series containing more than 1000 data points and I have specified     negativeColor to be 'rgba(249,149,83,1)'.
As you can see on the following link the series will stay in its default color:

http://jsfiddle.net/Ldv1u0zL/

However if you removed some data the negative color will appears for values lower than 0

http://jsfiddle.net/Ldv1u0zL/6/

I've made some tests: negative value color works with 938 data points (couples of x and y) but not with 1188.
Is there a workaround here ? Am I doing things badly ? 

Thank you,
Looking forward hearing back from you.

**Comment by pawelfus** [comment]
This is caused by `turboThreshold` option. You can disable it by setting `turboThresold: 0`: http://jsfiddle.net/Ldv1u0zL/7/

**Comment by Dams591** [comment]
Amazing ! Thank you sir, I'm closing this issue.
