### ISSUE TITLE
Crop threshold affects zoomed data

### ISSUE THREAD

**Issue by hendecasyllabic** [highcharts/highcharts#4785]
using: HighCharts v4.1.6

situation: render a highcharts column chart with > 50 data points using a datetime x axis
zoom into the data 
date ticks appear without their columns of data

expect that when zooming in and showing less than the cropthreshold then all data points should be displayed

Before Zoom
![beforezoom](https://cloud.githubusercontent.com/assets/1337256/11497449/063e92c0-9811-11e5-8c38-762a001c524e.png)

After Zoom
![afterzoom1](https://cloud.githubusercontent.com/assets/1337256/11497520/75445e70-9811-11e5-81fb-0a0be4815e75.png)
![afterzoom2](https://cloud.githubusercontent.com/assets/1337256/11497521/754a0c08-9811-11e5-8e89-4eeab7a7289f.png)

**Comment by TorsteinHonsi** [comment]
I'm not able to reproduce this now, please see http://jsfiddle.net/highcharts/4h9ce1kn/. Make your changes to the fiddle and post back.

**Comment by hendecasyllabic** [comment]
If you change the array to > 50 e.g. 51 then you can see the issue.

http://jsfiddle.net/hendecasyllabic/4h9ce1kn/2/

**Comment by TorsteinHonsi** [comment]
Thanks. With latest version: http://jsfiddle.net/highcharts/4h9ce1kn/3/

**Comment by mihitha** [comment]
Is this has been resolved? I'm having exact same problem. I'm using timestamp as X axis. when "cropThreshold<number of data", zoom will not work.

**Comment by TorsteinHonsi** [comment]
Live demo please? It works here: http://jsfiddle.net/highcharts/uqos3t9a/

**Comment by mihitha** [comment]
Sorry about late reply.
Live Demo
https://jsfiddle.net/mihitha/ghm1q1zh/

**Comment by TorsteinHonsi** [comment]
You've got [error 15](http://www.highcharts.com/errors/15)'s in your console. Reversing your data set does the trick: https://jsfiddle.net/highcharts/ghm1q1zh/7/

**Comment by mihitha** [comment]
Thanks a lot for that. I did able to fix it.

**Comment by alvarezguille** [comment]
Is there any known workaround for this issue?
thanks!

**Comment by pawelfus** [comment]
Instead of `cropThreshdold = series.data.length + 1`, you can set `cropThreshold: Inifity`, demo: http://jsfiddle.net/3asc7pbv/1/
