### ISSUE TITLE
Y Axis Tick Labels disappears for Tick label Angle 270 and Axis title is empty

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#4786]
If we set : Y Axis tick label angle 270 and Axis title empty, 
Y axis tick label disappears

Here is the JSFiddle:

http://jsfiddle.net/pawanvjadhav/ntwm29p7/1/

**Comment by pawelfus** [comment]
Fixed on the master branch: http://jsfiddle.net/ntwm29p7/2/
