### ISSUE TITLE
Range selector displays wrong start date

### ISSUE THREAD

**Issue by ericvincent83** [highcharts/highcharts#4788]
Using the official [JSFiddle](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/stock/rangeselector/enabled/) and switching the **enable function to true**, I can see that the beginning date is set to 22 Sept 2003 while the first date in the [data sample](https://www.highcharts.com/samples/data/usdeur.js) is 24 Sept 2003

I also noticed that if I reduced the amount of data in the sample (removing every entry later than 31 dec 2008), the start date comes back to the expected one (24 Sept 2003) 

Should we not have some consistency between the sample date range and the displayed date range ?

**Comment by TorsteinHonsi** [comment]
What you see is the data grouped into weeks:

![skjermbilde 2015-12-01 kl 15 38 55](https://cloud.githubusercontent.com/assets/227836/11503619/bd4c18ea-9841-11e5-90a7-2ac75016221d.png)

To get the unaltered data points, disable data grouping: http://jsfiddle.net/highcharts/njjp5y4d/
