### ISSUE TITLE
Exporting: IE unable to open http://export.highcharts.com/

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4790]
Unable to open http://export.highcharts.com/ using IE (tested versions 11 and 8) - "This page can't be displayed".

**Comment by dennisse** [comment]
I'm seeing the same error on a standalone export server I just set up.

IE11 somehow panics, and displays a DNS-error. It seems to work in every other browser.

I followed these instructions on Ubuntu 14.04: http://www.highcharts.com/docs/export-module/setting-up-the-server (using the correct versions of the software that the documentation asks for - not old packages from the Ubuntu repo).

**Comment by gvaartjes** [comment]
This will probably fixed by redirecting to a full URL instead of a relative url. We have to test this

**Comment by gvaartjes** [comment]
Fixed by: https://github.com/highcharts/highcharts-export-server/commit/32be3d2c00fe0d346b2eb040816431790c6ded68

note: We moved to another repository for the export server

Thanks for reporting,

Gert
Highsoft
