### ISSUE TITLE
fillColor in Custom SVG Markers stopped working in Highstock v2.1.8

### ISSUE THREAD

**Issue by dub4u** [highcharts/highcharts#4791]
http://jsfiddle.net/cpL73p47/16/ has a series with custom SVG markers (arrows). The marker's fillColor is supposed to be red when the value of the series is bigger than 100, green otherwise. It works as expected in Highstock v2.1.7 but it breaks in Highstock v2.1.8 as can be seen in http://jsfiddle.net/cpL73p47/17/ where the red color is only applied to the marker AFTER hovering over a point with the mouse.

**Comment by TorsteinHonsi** [comment]
@pawelfus Is this related to the point updates?

**Comment by pawelfus** [comment]
It's fixed on the bugfix branch: http://jsfiddle.net/cpL73p47/18/ - reference: #4759
