### ISSUE TITLE
Marker Label and Series Data label Cut issue

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#4793]
If we add Plot Line with Value near to Y axis scale max, Plot line label text is not displayed properly. This happens even with Series Data label, If column value is near to Y axis scale Max.

Please check below URL:
http://jsfiddle.net/pawanvjadhav/dxpfb8ws/

I tried to set maxPadding and spacingTop, but i think, setting this is just workaround not a generic solution. If we increase the font of Plot line label, then we have to again play with maxPadding and SpacingTop

**Comment by pawanvjadhav** [comment]
any updates or comments?

**Comment by pawelfus** [comment]
Just tested for `series.dataLabels`, works fine: http://jsfiddle.net/dxpfb8ws/1/

For the plotLine label - do you refer cut-off label? Would the solution like `overflow: "justify"` for dataLabels work for you?

**Comment by pawanvjadhav** [comment]
i am referring to cut-off label..299 
overflow : justify is not working

**Comment by TorsteinHonsi** [comment]
Plot line and plot band labels currently don't have any logic at all to stay within the plot area or to avoid collision, like data labels do. The best option for implementing this may be to share the datalabel logic and options set, but it would require some refactoring.
