### ISSUE TITLE
Stacked Areas rendering Problem if time stamps do not match

### ISSUE THREAD

**Issue by FabianChanton** [highcharts/highcharts#4796]
We have a problem where stacked areas don't get rendered correctly, if the time stamps don't match. You can see the problem at http://jsfiddle.net/xq8c6h07/16/ (strange peaks inside the black area)

The blue series has a resolution of 5 minutes.
The black series starts with a resolution of 5 minutes but the values near the end are stored with a resolution of only 15 minutes.

This seems somewhat similar to #2069 but I think this may be a different problem as there are no "null" values involved.

Regards

Fabian

**Comment by pawelfus** [comment]
I think you missed this issue: #3327 ;)

**Comment by FabianChanton** [comment]
Oh, sorry,  I really did :)
I'll post my example there.
