### ISSUE TITLE
allowDecimals on axis doesn't work if all data points are the same

### ISSUE THREAD

**Issue by grahamfowles** [highcharts/highcharts#4797]
When you set the option allowDecimals: false on an axis it will not work if all the data points have the same value

see http://jsfiddle.net/kumj95vv/ for demo

**Comment by pawelfus** [comment]
Ok, what would you like to display in such case? You can configure this by setting `minRange`, see: http://jsfiddle.net/kumj95vv/1/

**Comment by grahamfowles** [comment]
OK the minRange works so thanks for that.  Still I don't think it's very intuitive.  If you don't have minRange set but you set allowDecimals to false then I would expect it to still round the numbers

**Comment by TorsteinHonsi** [comment]
If we just display a tick at 30 and display the 29.999... points on it, we will lose information on the scale. 29.99999999 is not the same as 30, and we don't know if the difference is relevant.

An alternative default display `allowDecimals` is false could be to show ticks for the two closest integers, 29 and 30.

**Comment by grahamfowles** [comment]
IMHO if we needed to tell the difference between 29.99999999 and 30 then we wouldn't be setting allowDecimals to false.  The tick should be set at the closest integer with the data point slightly above/below it
