### ISSUE TITLE
Column series on multiple axes with and without grouping render wrong

### ISSUE THREAD

**Issue by hkostia** [highcharts/highcharts#4799]
http://jsfiddle.net/s6s29sk6/1/

Click Columns button to render 3 columns in a group in one x-axis and 1 column in another x-axis without grouping => The serie on the x-axis with one column is not shown properly (it is rendering the 1 column serie partly outside the chart)

Everything works properly if:
- There's only one column with grouping true and one or more columns with grouping false (First column button)
- Line series used instead of column series for the grouped series (Lines button)

**Comment by pawelfus** [comment]
Funny fact: if last series is set as the first one then it works properly: http://jsfiddle.net/s6s29sk6/2/ - looks like `grouping: false` doesn't work properly when any previous series have this option enabled.  Something in `getColumnMetrics` is wrong, I guess.

Minified demo: http://jsfiddle.net/s6s29sk6/3/

Extra issue: `alignTicks` creates more ticks on the xAxis than required.

**Comment by TorsteinHonsi** [comment]
Another, simpler, demo: http://jsfiddle.net/ocmjo5r6/
