### ISSUE TITLE
IE10 with Document Mode IE 8 Standards: page zoom influences transformed text

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4800]
In IE10 with Document Mode IE 8 Standards.
1. Login to http://jsfiddle.net
2. Click on link Create 
3. Create a sample with code from this demo: http://jsfiddle.net/KacperMadej/bo9nx47r/
4. Click run
5. Go to http://jsfiddle.net/draft/
6. Change document to IE 8 Standards. May be you need to add Trusted site for http://jsfiddle.net in the case the text is not display as vertical.

![livedemo](https://cloud.githubusercontent.com/assets/8960408/11590242/24f972e0-9a8f-11e5-8624-4c39257a65a8.png)
1. Zoom in(ctrl + "+") => The vertical text is disappear.

(Through browser menu I set zoom to 104% to show that higher zoom will influence more text placed further from top left corner. Notice also xAxis categories.)
![zoom104](https://cloud.githubusercontent.com/assets/8960408/11590265/46274a14-9a8f-11e5-8870-f2ccbe9dc3fd.jpg)

Related forum topic: http://forum.highcharts.com/highcharts-usage/vertical-label-is-disappear-when-zoom-in-t34399/

**Comment by TorsteinHonsi** [comment]
Tagged this a bug, but VML rendering is generally very unstable, and when combined with compatibility settings and newer features like page zoom it is a minefield of bugs. Native VML browsers, IE6, 7 and 8, don't have page zoom.
