### ISSUE TITLE
hi, when tooltip shared is true question

### ISSUE THREAD

**Issue by fegg** [highcharts/highcharts#4803]
my english is cheap, so, I  use two picture to express means.

tooltip: {
   share: false
}

![share false](http://i12.tietuku.com/f5511ddfc2890b5f.png)

tooltip : {
   useHTML: true,
   shared: true
}

![share true](http://i12.tietuku.com/0ef02e22c5ae02bc.png)

I want to when share is true, plot can like share is false.   only select current hover's plot.

my english is not well....my means is ok ?

**Comment by pawelfus** [comment]
Hello!

We use GitHub as bug tracker. For support questions, send us e-mail with details, please: http://www.highcharts.com/support
