### ISSUE TITLE
Highcharts Boost: fireEvent is not a function

### ISSUE THREAD

**Issue by vodun** [highcharts/highcharts#4804]
Error example in http://jsfiddle.net/caLe0366/3/
When using boost.src.js then got error: "Uncaught TypeError: fireEvent is not a function".

**Comment by pawelfus** [comment]
You are using mismatching versions of Boost and Highstock, see working demo: http://jsfiddle.net/caLe0366/4/

**Comment by vodun** [comment]
Thanks! Now it's work  fine.
But in this page http://www.highcharts.com/component/content/article/2-news/175-highcharts-performance-boost using too wrong path.

**Comment by pawelfus** [comment]
Oh, thank you!

**Comment by TorsteinHonsi** [comment]
Thanks, the website is updated now.
