### ISSUE TITLE
Document Point#visible for pie charts

### ISSUE THREAD

**Issue by campersau** [highcharts/highcharts#4808]
The [API documentation](http://api.highcharts.com/highcharts#series<pie>.data) is missing the [Point#visible](https://github.com/highcharts/highcharts/blob/master/js/parts/Point.js#L246) property.

Even though [Series#ignoreHiddenPoint](http://api.highcharts.com/highcharts#series<pie>.ignoreHiddenPoint) is documented.

**Comment by TorsteinHonsi** [comment]
The _option_ is documented at http://api.highcharts.com/highcharts#plotOptions.pie.visible, but the _Point property_ is not documented. With series.ignoreHiddenPoint you are referring to the option too. 

Under any circumstance, I have added the Point.visible property to the API now.
