### ISSUE TITLE
Thousands separator not working

### ISSUE THREAD

**Issue by grantopher** [highcharts/highcharts#4809]
I am unable to get the thousands separator to function as is stated in the documentation. In fact, even the  Highcharts example doesn't work as expected. Here is my use case: 
` format: '<center><div class="chart-label-title">{point.name}</div><br><b>${point.y:,.0f}</b></center>',`
in the same page I have the exact same chart with working thousands place and then a non working thousands place, its almost random whether or not the comma will show up.
Here is the documentation I am referencing: [Highcharts Docs](http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting)
And finally here is the broken code example that is linked in the documentation: [Example](http://jsfiddle.net/highcharts/rmTWS/)

**Comment by KacperMadej** [comment]
In the Docs that you are referencing is an information: **Note that even though a dot and a comma symbolizes the decimal point and the thousands separator respectively, how it is actually rendered depends on the [language settings](http://api.highcharts.com/highcharts#lang).** In [this part of API reference](http://api.highcharts.com/highcharts#lang.thousandsSep) you can find out that default `thousandsSep` is a single space, so everything is working as explained in Docs and set in options. If you change `thousandsSep`, then it will be applied in tooltip. Example: http://jsfiddle.net/rmTWS/567/

**Comment by sssisodia93** [comment]
bca

**Comment by sssisodia93** [comment]
<script>alert('abc')</script>
