### ISSUE TITLE
Using the stacking option with the "area" series type plots additional vertices

### ISSUE THREAD

**Issue by garystubbings** [highcharts/highcharts#4810]
When you have the series type set to "area" with stacking "normal" it appears to replace any null values in the data with a plot value of zero. However, if you change the type to "areaspline" it behaves correctly.

See http://jsfiddle.net/8o35v0hm/

**Comment by pawelfus** [comment]
See #2069 - part for areaspline is not fixed yet.

I'm closing this ticket as duplicate of #2069.
