### ISSUE TITLE
Treemap - incorrect datalabels when drilldown

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4812]
It looks like datalables are printed incorrectly.
1) http://jsfiddle.net/az7e22zn/
2) drilldown into Africa
3) In the bottom section you can observe Eastern Mediterranean datalabel "from previous level".

Problem appears since HC 4.1.10

**Comment by pawelfus** [comment]
*Internal note:*

Fails since 6e4cea1bd25f67d58efddbbb84324714c2ac9011

**Comment by jon-a-nygaard** [comment]
In this case when looking at [DataLabels.js on line 722-729](https://github.com/highcharts/highcharts/blob/master/js/parts/DataLabels.js#L722-L729), the overshoot is exactly the same as the height of alignTo. Making the resulting height equal 0. Perhaps a check for if the height > 0 is needed?

But also in [DataLabels.js on line 62](https://github.com/highcharts/highcharts/blob/master/js/parts/DataLabels.js#L62) it appears to be a validation which is letting undefined values pass as valid. Would it be a good solution to change the validation as below, or can point.y be anything but null?
```javascript
// From this
point.y !== null
// To something like this
typeof point.y === 'number' && !isNaN(point.y)
```

**Comment by jon-a-nygaard** [comment]
Fixed in a previous commit.

**Comment by Izothep** [comment]
It looks like it is not working since 4.1.8
http://jsfiddle.net/tw9wLshu/2/

Here is working example from 4.1.8
http://jsfiddle.net/tw9wLshu/1/

**Comment by sebastianbochan** [comment]
+1

**Comment by jon-a-nygaard** [comment]
Hmm, quite sure we fixed this. Will have a look at it today.

**Comment by sebastianbochan** [comment]
+1

**Comment by jonoterc** [comment]
+1

**Comment by jon-a-nygaard** [comment]
This issue will be fixed in the upcoming maintenance release. For those in need of a workaround have a look below.

__Workaround__
Open your version of the `treemap.src.js` in a text editor. Navigate to the `setPointValues` function, around line 310. Replace the following code snippet:
```javascript
// Replace this conditional statement
if (values) {

// With this conditional statement
if (values && node.visible) {
```

**Comment by sebastianbochan** [comment]
Seems that issue appears again in a similar scenario.

Demo: 
http://jsfiddle.net/sdkxwznk/

Steps:
1. Click on the Africa
2. In the bottom there is wrong shadow / datalabel

**Comment by TorsteinHonsi** [comment]
Opened new issue
