### ISSUE TITLE
Mapline is filled after hover/mouseover. 

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#4813]
In Highmaps mapline is filled after hover. When mouse leaves the mapline it still stays filled.

example:
http://jsfiddle.net/izothep/2yunqjey/9/
To recreate the issue hover the line.

The same problem exists in Highcharts demos:
http://www.highcharts.com/maps/demo/mapline-mappoint

This issue is not present when tested with versions of Highmaps older then 1.1.9: 

working example with 1.1.8. version:
http://jsfiddle.net/2yunqjey/11/

**Comment by TorsteinHonsi** [comment]
Fails since c1aaaed

**Comment by pawelfus** [comment]
Right. I have question before fixing/reverting: do we have any specific reason for setting `fill` for mapline series? See: https://github.com/highcharts/highcharts/blob/0e3824372b2a82c70dd081157de84dceef9013b3/js/parts-map/MapLineSeries.js#L14

**Comment by TorsteinHonsi** [comment]
It is probably because in a mapline, the color value sets the stroke, so the stroke reflects the point value. That allows us to set a static fill. And [it's documented](http://api.highcharts.com/highmaps#plotOptions.mapline.fillColor), so I guess we must keep backwards compatibility.

**Comment by pawelfus** [comment]
Ok, so by default, on mouseOver should we fill the path or it suppose to work as in 1.1.8 version (on hover, only stroke get highlighted)?

**Comment by TorsteinHonsi** [comment]
The fill color is static, so it shouldn't change on mouse over/out.

**Comment by jbkunst** [comment]
Hi everyone! Thank so much for highcharts!

I use the highstock.src with the fix to avoid the fill in maplines, but breaks when I want to make the combo chart (pie chart into a barchart) the error in the console is:

```
Uncaught TypeError: Cannot read property 'val2lin' of undefined
```

Hope it helps.

**Comment by TorsteinHonsi** [comment]
@jbkunst It is probably unrelated to this fix. [This fiddle](http://jsfiddle.net/highcharts/12o8f4dp/) shows the combo chart with `highstock.js` pulled from the master branch, where this fix is present.

**Comment by jbkunst** [comment]
@TorsteinHonsi  Yep, you're right. I guess I miss something.

Sorry and thanks again!

**Comment by TorsteinHonsi** [comment]
Reverted the fix, as it broke the test for #3636.

**Comment by pawelfus** [comment]
Hmm.. interesting. Just tested bugfix branch: http://jsfiddle.net/2yunqjey/18/ - works fine. the same when running test on bugfix.

**Comment by afreeland** [comment]
Awesome catch @pawelfus ... I just downloaded Highmaps 4.2.4 and was seeing this same type of issue.  Removed the `fill` as in your example and now its working.

![mapline_glitch](https://cloud.githubusercontent.com/assets/3135030/14832448/5eb5558a-0bc8-11e6-9ef3-c2796c4fed34.PNG)


Thankful to get past this issue =)

**Comment by TorsteinHonsi** [comment]
Works correctly since v5.0.0.
