### ISSUE TITLE
3.0.10 tag gone?

### ISSUE THREAD

**Issue by eah13** [highcharts/highcharts#4814]
It looks like the 3.0.10 tag and release were deleted? https://github.com/highcharts/highcharts/tags?after=highmaps-v1.0.2 This is making our automated build process fail.

**Comment by fpedroza** [comment]
Here too :-(

**Comment by eah13** [comment]
@fpedroza (and anyone else using this release): a workaround is to manually edit your bower.json to have this on the highcharts line:

```
"highcharts": "git@github.com:highcharts/highcharts.git#78d0d883a13dda43b972c23ff3e3f54349d93024",
```
Or fork the repo and tag it yourself. Or use the highstock tag that's for the same commit. Or upgrade. 

We'll probably just upgrade once I get a chance to check the changelog but definitely bad news that someone randomly deleted a tag. If it happens again we'll definitely start pulling from our own fork since someone's got the lethal combo of an itchy delete finger and commit access.

**Comment by TorsteinHonsi** [comment]
I have no idea why or when that tag disappeared, or if it ever was there, but under any circumstance I added it now: https://github.com/highcharts/highcharts/tree/v3.0.10.

**Comment by fpedroza** [comment]
We clean our cache and re-pull our libs, including this one, with our CI builds so it was there.
