### ISSUE TITLE
Treemap: Legend values get overlapped on Color axis

### ISSUE THREAD

**Issue by dmitrygorbenko** [highcharts/highcharts#4816]
Hi guys,

I have an issue with color axis in treemap chart in case colorValue (in series/data) has big value.
You can take a look at this issue here:
http://jsfiddle.net/DimaGorbenko/6yx121Lm/
(tested on latest 4.1.10 release)

Here is what I get:
![legend](https://cloud.githubusercontent.com/assets/1971759/11662782/2c2acce4-9de1-11e5-9407-f43d770bb720.png)

Thanks,
Dima

**Comment by pawelfus** [comment]
Workaround: set higher `tickPixelInterval` (by default = 72): http://jsfiddle.net/f6t935v9/

**Comment by dmitrygorbenko** [comment]
Hi, thanks for taking a look at this issue.
It may help in some cases, but not in each:

http://jsfiddle.net/DimaGorbenko/6yx121Lm/2/

I just changed value of colorValue and labels got overlapped.

Is there some algo which takes into account width of the labels ?

Thanks,
Dima

**Comment by dmitrygorbenko** [comment]
Can we open this bug again (because its fix has been reverted) ?

**Comment by TorsteinHonsi** [comment]
@dmitrygorbenko Sorry for the late reply! It was reverted because it caused resgressions in other places.

**Comment by TorsteinHonsi** [comment]
@dmitrygorbenko Sorry for the late reply! It was reverted because it caused resgressions in other places. Most of the map tests failed because the color axis labels were moved.

**Comment by znevrly** [comment]
Hi, any update with this? Thank you.

**Comment by znevrly** [comment]
It's awesome how you guys are reacting to bugs since 5.x release. How about this one tough nut? 👍

**Comment by TorsteinHonsi** [comment]
Thanks! Adding a new fix now. The only problem with the previous one was that it changed the default `tickPixelInterval`, so a lot of samples changed, though they were not actually wrong.
