### ISSUE TITLE
CommonJS, adapter confusion

### ISSUE THREAD

**Issue by bazineta** [highcharts/highcharts#4817]
Pleased to see CommonJS support this morning.  I'm confused, however, regarding the implementation.  In the examples, one sees:

```
var jQuery = require('jquery'),
    Highcharts = require('highcharts/lib/highstock')(jQuery);
```

However, in the Highstock code, we have:
```
   // Load adapter if HighchartsAdapter or jQuery is set on the window.
    Highcharts.loadAdapter(win.HighchartsAdapter || win.jQuery);
```

I am not sure then how the example relates to the actual code, which still seems to be looking for either of two globals, neither of which is defined.  As a quick and dirty, changing this line to:

```
Highcharts.loadAdapter(require('jquery'));
```

Allow things to work for me with our Webpack setup.

**Comment by bouk** [comment]
For me I actually had to assign the HighchartsAdapter to the global namespace before loading Highcharts, because "Highcharts module to hide overlapping data labels. This module is included in Highcharts." (can't view it on github because file is too big) loads the various helper functions like `each` and `addEvent` during the execution of Highcharts, so if the adapter isn't already initialized those variables will be undefined.

It should be referencing the current values in the Highcharts object instead of copying them over. 

@jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
@bazineta, @bouk
Thanks for reporting the issue, we are currently working on a solution.

**One proposed solution is:**
We are considering making the standalone framework a part of the Highcharts file, and remove the jQuery adapter. Then Highcharts will no longer be dependent upon an adapter or jQuery, which results in a simpler syntax.
Loading Highcharts with npm would as simple as:
```javascript
var Highcharts = require('highcharts');
var chart = new Highcharts.Chart(...);
```

The downside is that the Highcharts file will increase with approximately 1kB, for those who would still use jQuery in their project.

Any opinions on this are greatly appreciated.

**Comment by bouk** [comment]
@jon-a-nygaard removing the concept of adapters is probably the best move, would make the code less complicated too. Thanks for the reply!

**Comment by bazineta** [comment]
I think that at this point in the state of the JS world, either you've already moved to a bundler of some kind, or you're never going to.  Not a lot of middle ground there IMO.  I think the two reasonable choices here are to either make the main script require the adapter itself, or to incorporate the adapter.

For those who have moved to a bundler, either choice is fine; 1K isn't a big deal either way, and it's simpler if it's just incorporated.  For those who never will move, the second choice is the only option they have; these folks are pretty much still banging the rocks together to make sparks.

We use Marionette.js quite extensively here, and the solution there is to publish two versions; one a CommonJS setup with externalized dependencies that can be swapped out as desired by the developer, the other a completely bundled script will all dependencies included.  Makes sense there, as the dependencies are large and complex.  Here, however, your externals are quite small, and I'd think that depending on something you don't control for such a small code footprint to be a false economy, so if it were me I'd just bundle it.

**Comment by TorsteinHonsi** [comment]
> Here, however, your externals are quite small, and I'd think that
depending on something you don't control for such a small code footprint to
be a false economy, so if it were me I'd just bundle it.

Yes, I agree.

> the solution there is to publish two versions; one a CommonJS setup with
externalized dependencies that can be swapped out as desired by the
developer, the other a completely bundled script will all dependencies
included

We are considering a solution like that for Highcharts 5. Right now you are
loading logic for column charts even if you only draw a line chart, for
data labels if you don't use them etc. We're considering a structure like
the one you can see in the Download Builder at www.highcharts.com/download,
except with a programmatic interface using module loaders. But of course at
the same time preserving the current structure with highcharts.js,
highcharts-more.js etc. for those who need that.


​

**Comment by TorsteinHonsi** [comment]
Highcharts 4.2 comes with no adapter/framework dependency.
