### ISSUE TITLE
Docs: incorect link, because export server has moved

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4819]
In here: http://www.highcharts.com/docs/export-module/render-charts-serverside

1st text section:
Link to `highcharts-convert.js` - probably should be changed to same link as the one working, placed at the bottom of the page - https://github.com/highcharts/highcharts-export-server/tree/master/phantomjs/highcharts-convert.js (or to https://github.com/highcharts/highcharts-export-server/blob/master/phantomjs/highcharts-convert.js)

**Comment by gvaartjes** [comment]
Thx Kacper! Fixed now
