### ISSUE TITLE
Highmaps ignores credits in Highcharts.setOptions()

### ISSUE THREAD

**Issue by tomascassidy** [highcharts/highcharts#4821]
Example fiddles:

Working for Highcharts: http://jsfiddle.net/mzgs62hz/
Doesn't work for Highmaps: http://jsfiddle.net/okjaxy5c/

In both fiddles, I've just added in a call to

```javascript
Highcharts.setOptions({
  credits: {
    text: 'test credits'
  }
});
```

On the Highcharts chart the credits text changes to `test credits`, while on the Highmaps chart the credits text stays as `Highcharts (C) Natural Earth`.

**Comment by pawelfus** [comment]
Indeed, it looks like checking in the Highmaps module should be a bit improved [here](https://github.com/highcharts/highcharts/blob/807729348c3a5dce45061345846d0c31199414f6/js/parts-map/GeoJSON.js#L199-L213).

**Comment by oysteinmoseng** [comment]
Highmaps overwrites credits with the map credits if the chart credits == default credits. Since Highcharts.setOptions redefines the default, Highmaps assumes that the credits should be overwritten.

**Comment by oysteinmoseng** [comment]
The problem has now been "moved" by introducing `credits.mapText` and `credits.mapTextFull` options that contain format strings. These are now concatenated with `credits.text`. Using `setOptions` on these new options will still fail, so turning off map source credits will have to be done on a per-chart basis. `setOptions` will now work with `credits.text`, however.

**Comment by oysteinmoseng** [comment]
`setOptions` now works with the new options as well, thanks to @TorsteinHonsi!

**Comment by slavede** [comment]
This issue happens again with 7+ version http://jsfiddle.net/krm00Lre/

**Comment by pawelfus** [comment]
Hi @slavede 

This issue specifically targets Highmaps and Credits, not Highstock and Legend. Regarding Highstock & Legend, we have a separate ticket, please take a look: #8357
