### ISSUE TITLE
Combination of StockChart, stacking and negativeColor causes errors in console

### ISSUE THREAD

**Issue by karolx** [highcharts/highcharts#4823]
Enabling *stacking* and *negativeColor* at the same time for column *StockChart* causes errors:

```
Error: Invalid value for <rect> attribute y="NaN"
Error: Invalid value for <rect> attribute height="NaN"
```

The chart itself seems to look as expected.

Repro:
http://jsfiddle.net/r49r23n5/

Tested on OSX and Ubuntu in Chrome 47.0.2526.73

**Comment by pawelfus** [comment]
The issue comes from navigator - columns are missing.

*Internal note:*
Interesting is that `Highcharts.charts[0].yAxis[1].getExtremes()` returns a lot of `NaN`'s, so later `applyZones()` method fails with creating clips. Should we use `stacking` in the navigator anyway?
