### ISSUE TITLE
Incorrect tooltip when scatter is inside boxplot

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4824]
As in the topic.

Example:
- http://jsfiddle.net/44yuL8fd/

**Comment by pawelfus** [comment]
**Workaround:**
Use shared tooltip (`tooltip.shared = true`), example: http://jsfiddle.net/44yuL8fd/2/

**Comment by pawelfus** [comment]
Works fine in versions 4.2.2+: http://jsfiddle.net/44yuL8fd/4/
