### ISSUE TITLE
yAxis floats when all values are 0

### ISSUE THREAD

**Issue by reneklootwijk** [highcharts/highcharts#4825]
In version 4.1.8 one could bind the 0 values to the xAxis by setting:
 min:0, 
 minRange: <some value>

In version 4.1.10 the 0 values will appear in the middle of the axis.

**Comment by pawelfus** [comment]
You don't have to set `min` anymore, take a look: http://jsfiddle.net/0cqcuz88/

**Comment by reneklootwijk** [comment]
Yep, works for me!
