### ISSUE TITLE
Highcharts vs Highcharts-Release breaks bower applications.

### ISSUE THREAD

**Issue by berhoden** [highcharts/highcharts#4826]
We were depending on the highcharts component via bower (v4.1.6) which used to have the modules directory as well as the highcharts.js file. Now this only is available in the highcharts-release bower component. This will break any apps dependent on the highcharts component. Switching the bower dependency to highcharts-release fixes this. Just an FYI for the community.

**Comment by pmacmillan** [comment]
See #4815

**Comment by thewarpaint** [comment]
tl;dr: in `bower.json`, change:

```json
{
  "dependencies": {
    "highcharts": "4.x.y"
  }
}
```

to

```json
{
  "dependencies": {
    "highcharts-release": "4.x.y"
  }
}
```

**Comment by KacperMadej** [comment]
Here's the install from Bower docs: https://www.highcharts.com/docs/getting-started/install-from-bower

Please provide more info and the issue could be reopened.
