### ISSUE TITLE
External CSS not passed to export server

### ISSUE THREAD

**Issue by grzesiekgs** [highcharts/highcharts#4830]
http://jsfiddle.net/u29vu2bd/9/

In given example, the first part of text ( everything before '(' ), has to be visible ( up to 3 lines of text ).
Everything else is being cut with text-overflow: ellipsis.

As you can see, the chart is working just as it should, but exported image is not rendered in proper way - while exporting.sourceWidth is defined, line doesn't break as it should.

**Comment by pawelfus** [comment]
The problem is that CSS styles are not send to the exporting server - those are defined in a separate files, so exporting server doesn't know about them. In other words, setting styles inline in the formatter will get you proper result: http://jsfiddle.net/u29vu2bd/11/

**Comment by TorsteinHonsi** [comment]
Highcharts 5 will include a solution to inline all interpreted styles and include them in the export.
