### ISSUE TITLE
Boost - markers - line/scatter

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4831]
Looks like different behaviour between versions, when we consider using markers.

Let's compare:
4.1.5 http://jsfiddle.net/dpdmL0oy/
4.1.10 http://jsfiddle.net/0tsgtbf7/1/

In the first scenario markers are printed, but in second shape looks like different.

**Comment by pawelfus** [comment]
I may be wrong, but.. first boost was released with 4.1.8? See: https://code.highcharts.com/4.1.8/modules/boost.js vs https://code.highcharts.com/4.1.7/modules/boost.js

Anyway, shouldn't be there line series instead of scatter? See: http://jsfiddle.net/0tsgtbf7/2/

**Comment by sebastianbochan** [comment]
Definately you are right, anyway I checked that after few zooms markers appear properly.
