### ISSUE TITLE
Use requestAnimationFrame for animations

### ISSUE THREAD

**Issue by vickychijwani** [highcharts/highcharts#4833]
I've been reading about [`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame), and it looks like it could really help dynamic Highcharts performance if redraws were scheduled using it instead of immediate / `setTimeout` calls. At first glance this also doesn't seem too difficult, something like:

```js
// before
chart.redraw();   // or axis.redraw(), series.redraw(), etc...

// after
requestAnimationFrame(function () { chart.redraw() }); // use polyfill to fallback to setTimeout
```

Browser support is [great across modern browsers](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame#Browser_compatibility). A polyfill that falls back to `setTimeout` is [available](https://github.com/chrisdickinson/raf). It is possible I'm misunderstanding this API, in which case please correct me.

**Comment by vickychijwani** [comment]
After experimenting a bit by myself (by wrapping `Chart#redraw` to trigger it via rAF), it doesn't look like it will help redraw performance significantly. But still, there is another obvious application of rAF: to make chart animations smoother. This is not something I personally need, because I've turned off all animations, but I imagine those using animations would be interested.

**Comment by pawelfus** [comment]
Sure, feel free to vote for it, on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/2501204-use-requestanimationframe-instead-of-settimeout)

**Comment by vickychijwani** [comment]
@pawelfus Thanks for digging that up! Closing this Github issue since it's already tracked in UserVoice.
