### ISSUE TITLE
3D column dataLabels alignment issue

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#4834]
Using beta parameter in 3D column chart is leading to missalignment of dataLabels. DataLabels are positioned in regard to size of whole chart, when chart is resizing to smaller width dataLabels are moving and finally they can be in the right position.

example: http://jsfiddle.net/2ty5ex58/13/

**Comment by KacperMadej** [comment]
Looks like tooltip is misplaced too.

**Comment by jon-a-nygaard** [comment]
Closing this since it is a duplicate of #4160. Please follow the referenced issue to see comments and updates on the issue.
