### ISSUE TITLE
Chart "Loading" text and images are not centered correctly

### ISSUE THREAD

**Issue by bstanleycm** [highcharts/highcharts#4835]
When the showLoading() method is called, "Loading..." appears on the chart.  Instead of centering on the entire chart div (including the space for x/y labels), the loading text should be centered on the chart graphic itself.  See attached image... "loading..." should be centered on the cross-hairs.

![capture](https://cloud.githubusercontent.com/assets/1598844/11751577/470beeb6-9fef-11e5-965a-ea9f30cab5c9.JPG)

**Comment by pawelfus** [comment]
Could you setup live demo with that issue? For me it works fine: http://jsfiddle.net/g8bgj56r/

**Comment by jon-a-nygaard** [comment]
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.
