### ISSUE TITLE
Markers not showing on Highstock column chart

### ISSUE THREAD

**Issue by nhitchins** [highcharts/highcharts#4836]
Markers are no longer being displayed on highstock column charts.

Example: http://jsfiddle.net/6na2odpq/

**Comment by pawelfus** [comment]
I'm sorry, in which version column series supported markers? Just tested version 2.2.0 (Highcharts 2012-02-16): http://jsfiddle.net/6na2odpq/1/ - still, no markers. 

Column series in general doesn't support markers (?), there is no such property in our [API](http://api.highcharts.com/highcharts#plotOptions.column).

PS: Your jsFiddle uses Highcharts, not Highstock.

**Comment by nhitchins** [comment]
Thanks for the clarification. For some reason I thought the old highstock column charts supported markers. Your highstock API does show the markers property: http://api.highcharts.com/highstock#plotOptions.column.marker

**Comment by TorsteinHonsi** [comment]
Thanks for notifying @nhitchins, the docs were wrong. I have removed it now.
