### ISSUE TITLE
report error when both use highcharts and highmaps and angularjs

### ISSUE THREAD

**Issue by hank-hong** [highcharts/highcharts#4837]
The process will report error when using highcharts, highmaps and angularjs. I followed the guide to import the js: highcharts.js, maps.js and highcharts-ng.js， but the process will always report the folllowing error : 
TypeError: Cannot set property '..../customer-map' of undefined

And the charts or maps don't work.

**Comment by pawelfus** [comment]
Hello,
This is our bug tracker. For support questions, please our [support-channels](http://www.highcharts.com/support) (like e-mail, or post the problem on the forum).
