### ISSUE TITLE
Export: plotOptions in additionalOptions are not applied to series

### ISSUE THREAD

**Issue by jlowcs** [highcharts/highcharts#4838]
When I export a chart with override styles, some of those are not applied.

For instance, I display my charts with a dark theme, but I want to export them using a light theme. So my dataLabels must change from a light color to a dark color. To do that, I assumed that the following `additionalOptions` were enough:

``` javascript
  plotOptions: {
    spline: {
      dataLabels: {
        style: {
          color: 'black'
        }
      }
    }
  }
```

It doesn't work, the labels are still in a light color. Why? because the `getSVG`function doesn't apply the `plotOptions` to my chart's series.

I think a solution would be to change the following code (from `exporting.src.js`):

``` javascript
seriesOptions = merge(serie.options, {
  animation: false, // turn off animation
  enableMouseTracking: false,
  showCheckbox: false,
  visible: serie.visible
});
```

...into:

```
seriesOptions = merge(merge(serie.options, options.plotOptions[serie.type] || {}), {
  animation: false, // turn off animation
  enableMouseTracking: false,
  showCheckbox: false,
  visible: serie.visible
});
```

Thoughts?

**Comment by pawelfus** [comment]
Yes, that's issue with merging options for exporting. See comment for the same issue: #4583.

**Comment by jlowcs** [comment]
Thanks!

FYI, my solution is working, but introduces other issues.

**Comment by pawelfus** [comment]
Probably, the best solution would be tu use `userOptions` instead, something like this:

    seriesOptions = merge(serie.userOptions, options.plotOptions[serie.type] || {}, serie.options, {
      animation: false, // turn off animation
      enableMouseTracking: false,
      showCheckbox: false,
      visible: serie.visible
    });

But again, that will raise issues with options set by updating.

**Comment by KacperMadej** [comment]
Working fine since version 4.2.2 - http://jsfiddle.net/erry26rx/5/
and is still working with the current version - http://jsfiddle.net/erry26rx/6/

Please reopen in case of regression.
