### ISSUE TITLE
Unable to select less than 6 months

### ISSUE THREAD

**Issue by findoo** [highcharts/highcharts#4839]
We've found that with some data sets, the range selector will not allow the selection of any period less than 6 months. 

We would expect that if it was possible to view a 6 month period, then 1 month and 3 month would be enabled - as the corresponding time range exists on the x-axis. 

Setting the "allButtonsEnabled" value on the rangeSelector enables those buttons, however does not yield the expected time range when pressed either. 

JSFiddle - http://jsfiddle.net/4qww3o1o/

![chart](https://cloud.githubusercontent.com/assets/3541918/11779430/f3589e48-a252-11e5-9e73-ae7e1e8d52ec.png)

**Comment by pawelfus** [comment]
This is caused by `minRange` on xAxis. You can change that, for example by setting 1day, demo for you: http://jsfiddle.net/4qww3o1o/1/

**Comment by findoo** [comment]
@pawelfus That's perfect, thanks for your help.

**Comment by findoo** [comment]
That's perfect, thanks for your help.
