### ISSUE TITLE
Credits title bug

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#4840]
Hello,
There is a bug related to credits title. When you hover over title it shows title "undefined". Please see attached image:
![highcharts_title_bug](https://cloud.githubusercontent.com/assets/2900934/11781400/ae1dd906-a27a-11e5-92fe-5cffae1d4682.png)
Best regards, Pavel

**Comment by pawelfus** [comment]
Hi Pavel,
Could you setup some live demo so we can debug this? I mean, demo pages work fine: http://www.highcharts.com/demo/line-basic

**Comment by pliasetski** [comment]
Hi,
It doesn't work well on main page (chart at first slide): http://www.highcharts.com/
Thanks

**Comment by pawelfus** [comment]
Thanks!

jsFiddle demo: http://jsfiddle.net/26r8c9qk/ - it happens only when map.js file is included.

*Internal note:*
Comes from wrapped `showCredits` method.

**Comment by pliasetski** [comment]
Thanks,
But what should I do in this case. In my app both chart and map are included.

**Comment by pawelfus** [comment]
You can disable or change that, see: http://jsfiddle.net/26r8c9qk/1/

This line will change/disable title:

    Highcharts.Chart.prototype.mapCreditsFull = '';

**Comment by pliasetski** [comment]
Thank you very much,

But I'm interesting if there a way to show in the credits title the same content as in credits title.
For example if I have two charts in the page with different credits data I couldn't set Highcharts.Chart.prototype.mapCreditsFull = '';" because this title will apply on two charts at the same time.

Best regards

**Comment by pawelfus** [comment]
I see. In that case, you can use `chart.events.load` to change that title, for example: http://jsfiddle.net/26r8c9qk/4/

```js
  Highcharts.Chart.prototype.mapCreditsFull = '';

  $('#container').highcharts({
    chart: {
      events: {
        load: function() {
          if (this.credits) {
            this.credits.attr({
              title: 'my title!'
            });
          }
        }
      }
    },
    ...
  });

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng Another one with the wrapped showCredits. Can probably be fixed together with the other one.
