### ISSUE TITLE
3d chart - grouping param

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4841]
Example: http://jsfiddle.net/jpc8Lr2s/1/

In 3D stacked column & bar charts, a different "grouping" property value is
required to make the chart render properly.
For example in order to render 3D stacked column charts properly,
plotOptions.column.grouping must be set true, whereas in 3D stacked bar
charts plotOptions.bar.grouping must be set false instead.

**Comment by pawelfus** [comment]
I would say we have here four cases:

- `grouping: false` and `reversedStacks: true`: works fine: http://jsfiddle.net/jpc8Lr2s/2/
- `grouping: true` and `reversedStacks: true`: bar chart doesn't work: http://jsfiddle.net/jpc8Lr2s/3/
- `grouping: false` and `reversedStacks: false`: both samples don't work: http://jsfiddle.net/jpc8Lr2s/4/
- `grouping: false` and `reversedStacks: true`: works fine: http://jsfiddle.net/jpc8Lr2s/5/

**Comment by Izothep** [comment]
Resolved through 6f84253 

demos:
http://jsfiddle.net/jpc8Lr2s/8/

http://jsfiddle.net/jpc8Lr2s/9/

http://jsfiddle.net/jpc8Lr2s/10/

http://jsfiddle.net/jpc8Lr2s/11/
