### ISSUE TITLE
Legend items misaligned when image included

### ISSUE THREAD

**Issue by maxbarry** [highcharts/highcharts#4845]
If a legend item includes an image, or is taller than one line, there is no way to make the legend line align with the text.

http://jsfiddle.net/rjaL8Lrp/1/

**Comment by pawelfus** [comment]
You can simply set `line-height` in the CSS. See: http://jsfiddle.net/rjaL8Lrp/2/ For questions, could you use our forum/mail support? We are trying to keep github issues as bug tracker.

**Comment by maxbarry** [comment]
That is even more badly misaligned! Apologies if it's not a bug, but I have investigated and it really does seem impossible to middle-align legend items.

**Comment by TorsteinHonsi** [comment]
Some CSS trickery should do it. Setting  a negative top margin for instance: http://jsfiddle.net/highcharts/rjaL8Lrp/3/

**Comment by maxbarry** [comment]
Sorry, I'm not expressing myself very well! You are correct that you can use CSS trickery to individually set the size and position of legend items (or anything else) in HTML. This is necessary to work around the fact that Highcharts can't vertically center legend items.

I thought this lack of vertical alignment was a deficiency, hence this bug report. I'm not asking for help finding workarounds, which I realize can be made to work (although have their own problems, especially when you don't know the height of each legend item in advance).
