### ISSUE TITLE
3D chart gets disorientate after apllying view distance and scroll-bar together

### ISSUE THREAD

**Issue by saurabhshah404** [highcharts/highcharts#4847]
3-d chart gets disorientate after apllying view distance and scroll-bar together

 http://jsfiddle.net/saurabheq/pxh1c04e/2/
 http://jsfiddle.net/saurabheq/pxh1c04e/6/
http://jsfiddle.net/saurabheq/pxh1c04e/3/

also scrollbar get's overlapped

**Comment by pawelfus** [comment]
Works fine with master and bugfix branch: http://jsfiddle.net/pxh1c04e/8/

*Internal note:*
I am not sure about this case: http://jsfiddle.net/pxh1c04e/7/ (the same in the current release and master branch) - looks like 5px distance is to low (to close?), to see 3D without artefacts.
