### ISSUE TITLE
Tooltip: Line and scatter - tooltip for line series is not displayed.

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4848]
The problem is visible since 4.1.10 (not visible in 4.1.9).
If there are series of type line (or spline, area, etc.) and scatter, then tooltip is displayed only for scatter.
Example: http://jsfiddle.net/j3ujrp7t/2/

Workaround - set shared for tooltip to true.

**Comment by pawelfus** [comment]
Fails since https://github.com/highcharts/highcharts/commit/4392d1c.

**Comment by pawelfus** [comment]
Works fine since 4.2.2: http://jsfiddle.net/j3ujrp7t/5/
