### ISSUE TITLE
plotBand that is partially visible have full gradient color

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4849]
Gradient color is applied only to visible part of a plotBand. If a plotBand has set `to` to 140, then shouldn't linearGradient end on 140 of yAxis instead of visible part of a plotBand?

Example: http://jsfiddle.net/h0x45b65/1/ - click the button to change yAxis extremes

**Comment by TorsteinHonsi** [comment]
Yes you're probably right. At least, if it did, it would facilitate a reliable correlation between stops and axis values.

The problem now is that the plot band rectangle actually doesn't extend outside the plot area.

**Comment by drmrbrewer** [comment]
Why was this closed?  Seems to make sense to be able to set gradient fill within a plot band and be sure that it will look right, regardless of how much of the band is visible.  I'm facing this problem now.

**Comment by sebastianbochan** [comment]
Hi @drmrbrewer,
I apologize for inconvenience. We use auto-closer bot for the oldest issues. Im reopening the issue.

**Comment by drmrbrewer** [comment]
@sebastianbochan this issues seems to be linked to (maybe is a duplicate of) https://github.com/highcharts/highcharts/issues/6257

**Comment by pawelfus** [comment]
Yes, it's the same. Closing this in favour of #6257 - we have more details in #6257.
