### ISSUE TITLE
standalone-framework is missing from CDN

### ISSUE THREAD

**Issue by KundanGaira** [highcharts/highcharts#4850]
If someone is using a direct link to
http://code.highcharts.com/adapters/standalone-framework.js

Then there are lots of issue with highchart, due to dependency on the above file.

**Comment by TorsteinHonsi** [comment]
Since Highcharts 4.2, Highcharts doesn't use an adapter. You need to make sure the adapter version matches the Highcharts version.

**Comment by TorsteinHonsi** [comment]
Demo: http://jsfiddle.net/highcharts/751oozp1/
