### ISSUE TITLE
chart content disappeared after setExtremes

### ISSUE THREAD

**Issue by edwin-nz** [highcharts/highcharts#4851]
I'm experiencing an issue where the chart content will become invisible after calling setExtremes.
This occurs when the following conditions are met:
1. there are more than 1000 data points in the chart series
2. the chart contains data points with specified color: eg. { color: 'red', y: 5}
3. a colored data point (described in #1) is located just before setExtremes's min value. 
eg. if the 99th point of the chart data is a colored point, calling setExtremes(100, 200) will cause the chart content to disappear

here's the jsfiddle demo:
http://jsfiddle.net/edwinliu/0b9rs0je/7/

ps. this has been tested with http://github.highcharts.com/master/highcharts.js and the issue still occurs

**Comment by pawelfus** [comment]
Hello,

If you have more than 1000 points, you should set `turboThreshold` (or disable it). See working demo: http://jsfiddle.net/0b9rs0je/8/

**Comment by edwin-nz** [comment]
Cool thanks for your help, much appreciated.
