### ISSUE TITLE
Checkbox in legend: outside legend's border

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4853]
When layout of legend is default ('horizontal') checkbox in legend might be placed outside legend's border.
Example: http://jsfiddle.net/kq12wtsa/

**Comment by pawelfus** [comment]
Broken since 4.0.0: http://jsfiddle.net/kq12wtsa/1/

**Comment by pawelfus** [comment]
**Workaround:**
Set `legend.itemDistance: 8` as in Highcharts 3, demo: http://jsfiddle.net/kq12wtsa/2/
