### ISSUE TITLE
Checkbox in legend: overlap tooltip and dataLabels

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4854]
Checkbox overlay tooltip and dataLabels, unlike rest of a legend.
Example: http://jsfiddle.net/our7wjjz/

**Comment by pawelfus** [comment]
Well, checkbox is rendered in HTML, but the chart is SVG. HTML is on top of SVG, so that's the reason. I'm not sure if we can somehow avoid that. 

Just a thought - replace current checkbox with SVG's implementation for checkboxes?

**Comment by TorsteinHonsi** [comment]
> Just a thought - replace current checkbox with SVG's implementation for checkboxes?

That would work. It may not add too much to the filesize either, if anything at all. It would be just a rectangle and a path on top of it, then event handlers.

**Comment by pawelfus** [comment]
Yes, of course. However I'm a bit worried about the compatibility: currently users may use CSS on checkboxes, and that change will break that use case. Also, we would need to add option like `showCheckboxStyle` to allow styling the checkboxes (fill, color, background and states: hover/selected).

**Comment by TorsteinHonsi** [comment]
Yes, you're right. It's perhaps best to leave it like it is, at least until HC5.

**Comment by KacperMadej** [comment]
The checkbox is in HTML and if you want to have tooltip over it then tooltip needs to be a full-HTML tooltip and have higher z index.

If this is not a valid solution for you pleas open an enhancement idea on userVoice: https://highcharts.uservoice.com/forums/55896-general
The most popular ideas are getting implemented.
