### ISSUE TITLE
zooming doesn't work in Tree Map with Color Axis

### ISSUE THREAD

**Issue by dmitrygorbenko** [highcharts/highcharts#4856]
Hi,

I created my demo based on your demo of tree map with color axis where I enabled zooming:
https://jsfiddle.net/DimaGorbenko/mrjnLxao/
it has version 4.2.0.

Zooming seems like is broken since 4.1.9.
Here is a working version with 4.1.8: http://jsfiddle.net/DimaGorbenko/mrjnLxao/2/
Here is a not working version with 4.1.9: http://jsfiddle.net/DimaGorbenko/mrjnLxao/3/

( I tired to search for similar bug but didn't find it, so I created this new one )

Thanks
Dima

**Comment by pawelfus** [comment]
Fails since https://github.com/highcharts/highcharts/commit/53f13b3

**Comment by fclmman** [comment]
hi! Are there any news about this issue. We are looking for a tree map solution and highcharts were the bust, but zoom issue stops us.

**Comment by jon-a-nygaard** [comment]
@fclmman For now there is unfortunately no update on this issue. We have an option [allowDrillToNode ](http://api.highcharts.com/highcharts#plotOptions.treemap.allowDrillToNode) which might suit your needs.

**Comment by fclmman** [comment]
@jon-a-nygaard thank you for responding, we will look into allowDrillToNode option, but what we really want to know is will this functionality, zooming i mean, be available in the future, and how soon, if it will?
Thank you in advance.

**Comment by jon-a-nygaard** [comment]
@fclmman This issue will be fixed in the upcoming maintenance release. If you are in need of a workaround before the release, you can try out the one below.

__Workaround__
Open the module `treemap.src.js` and look for the following code in the translate function around line 591.
```javascript
// Replace this code
val = this.nodeMap[this.rootNode].pointValues;
this.xAxis.setExtremes(val.x, val.x + val.width, false);
this.yAxis.setExtremes(val.y, val.y + val.height, false);
this.xAxis.setScale();
this.yAxis.setScale();

// With this code
if (this.options.allowDrillToNode) {
	val = this.nodeMap[this.rootNode].pointValues;
	this.xAxis.setExtremes(val.x, val.x + val.width, false);
	this.yAxis.setExtremes(val.y, val.y + val.height, false);
	this.xAxis.setScale();
	this.yAxis.setScale();
}
```
