### ISSUE TITLE
Error when creating a chart without chart options and highcharts-3d is loaded.

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4857]
If highcharts-3d is loaded and a chart is set without any chart` section in options, then an error is thrown and the chart is not created.

`Uncaught TypeError: Cannot read property 'options3d' of undefined`

Example: http://jsfiddle.net/3zoutr62/
Uncomment 3rd line to fix, but adding `chart:{},` - a workaround.

The problem seems to not appear in bugfix branch of Highcharts: http://jsfiddle.net/3zoutr62/1/

**Comment by pawelfus** [comment]
Not any more - just merged bugfix to 4.2.0. It used to work on bugfix, because it was an old version. In old versions, when creating chart by `$(container)` was added `chart.renderTo` option, so `chart` existed. Since 4.2.0, `chart` in option can be not defined, so we should check this too.
