### ISSUE TITLE
Bubble chart tooltip doesn't get destroy/disable when mouse out from a point and remain inside chart area

### ISSUE THREAD

**Issue by saurabhshah404** [highcharts/highcharts#4858]
Bubble chart tooltip doesn't get destroy/disabled when mouse out from a point and remain inside chart area,

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/bubble/

http://jsfiddle.net/saurabheq/30wogpm6/1/

**Comment by pawelfus** [comment]
Minified demo: http://jsfiddle.net/30wogpm6/2/

**Comment by natee** [comment]
Fixed demo: http://jsfiddle.net/30wogpm6/4/

Highcharts v4.2.0 , all bubble charts (mapbubble,bubble..) will have this issue.
It was 'stickyTracking' was set to 'true' by some reason.
