### ISSUE TITLE
offline export with fallbackToExportServer: false => no indication that the export has failed

### ISSUE THREAD

**Issue by jlowcs** [highcharts/highcharts#4859]
When calling ```chart.exportChartLocal(...)```with ```fallbackToExportServer: false```, I expect an exception to be thrown when the export fails.

After reading the code (```offline-exporting.src.js```), I realize it's not possible because the ```'Fallback to export server disabled'``` exception is thrown inside an ```img.onerror``` function.

Therefore, I suggest adding at least an error callback, so that the app can warn the user that the export cannot be done in his browser.

It would be even better to have ```exportChartLocal``` return a promise, but that would mean including a promise library with Highcharts...

On top of that, still in ```offline-exporting.src.js```, ```finallyCallback``` is not called when the exception is thrown. ```finallyCallback``` should probably be in a ```finally``` block.

I can submit a PR if you tell me how you would like it to work.

**Comment by oysteinmoseng** [comment]
Good point on the `finally` callback. Will fix.

In which case did you encounter the `'Fallback to export server disabled'` exception not firing (see [support table](http://www.highcharts.com/docs/export-module/client-side-export))? Could you set up a quick jsFiddle for testing?

**Comment by jlowcs** [comment]
It happened with an older version of Firefox. I thought it was FF v39, but it doesn't make sense when looking at your support table. Probably an even older version then.

In any case, the point of that error is to know that the client side export cannot be done on the current browser, so it would be nice for that error to be retrievable in the app that is using the offline export module.

**Comment by oysteinmoseng** [comment]
Added an `exporting.error` option where a callback can be defined. If the function is defined, the exception is not thrown.
