### ISSUE TITLE
Highmaps: simplified constructor not working

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4860]
Accordingly to [this article](http://www.highcharts.com/component/content/article/2-news/198-highcharts-drops-adapters): *Highcharts.Chart, Highcharts.StockChart and* ***Highcharts.Map****, now have a lowercase counterpart*, so `Highcharts.map(a,b,c)` should work, but it doesn't.

Example: http://jsfiddle.net/Ldcvst2x/

Also, and maybe this should be a separate issue, doesn't `lowercase` mean that **stockchart** should work instead of **stockChart**  as a simplified constructor ?

**Comment by TorsteinHonsi** [comment]
Sorry about that, I should have listed the constructors. It's `chart`, `stockChart` and `mapChart` respectively. To be precise it is lowercase first letter. And in the case of `Map` => `mapChart`, the problem was that `Highcharts.map` already means something else.

I have updated the article now.
