### ISSUE TITLE
offline export : img.crossOrigin = 'Anonymous' fails on older versions of Firefox

### ISSUE THREAD

**Issue by jlowcs** [highcharts/highcharts#4861]
Tested with FF v39: ```img.crossOrigin = 'Anonymous'``` results on a failed export (```img.onerror``` is called).

Why this option ?

**Comment by oysteinmoseng** [comment]
The property is set because of CORS issues with drawing to canvas in some browsers. Will look into not setting it for older FF.

Would you happen to have a jsFiddle demo for testing?

**Comment by jlowcs** [comment]
It was a PNG export without CORS.

**Comment by oysteinmoseng** [comment]
I revamped the logic to now always try without `crossOrigin='Anonymous'` first, and then retry with the property set if it fails with security errors.

**Comment by jlowcs** [comment]
:+1:
