### ISSUE TITLE
4.2.0: `fillOpacity` is now influenced by opacity of `color` (arearange and areasplinerange)

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#4862]
Compare previous behaviour (pre 4.2.0):
http://jsfiddle.net/drmrbrewer/xL7urpn1/

with new behaviour (4.2.0) -- all I have done is update the highcharts version:
http://jsfiddle.net/drmrbrewer/xL7urpn1/1/

In the new behaviour, the `fillOpacity` seems to be affected by the fact that there is an `opacity` defined by `color`.  In the old behaviour, `fillOpacity` was taken at face value.

So with the new behaviour, even when you set a `fillOpacity` of 1.0, you might not actually get an opaque fill:
http://jsfiddle.net/drmrbrewer/xL7urpn1/2/

Is this intentional?  It doesn't seem logical to me.  Certainly it's broken the appearance of my charts, and I don't know whether I should be updating my chart options to deal with this, or wait for a fix.

**Comment by TorsteinHonsi** [comment]
The change we did was to set `fill-opacity` separate from `fill`. This allows the `fillOpacity` setting to also apply to named colors like red, blue or green, which is an improvement. 

So if you uses both an rgba color and a fill opacity, the results will now be different. In my opinion this is an improvement, and it makes sense that you you set a chart color of `rgba(0, 0, 0, 0.5)` and a fillOpacity of 0.5, the resulting opacity should be 0.25.

Were there any use cases in 4.1 where you would have an rgba color and a different fillOpacity?

**Comment by drmrbrewer** [comment]
Yes I do have a use case which is broken by the new behaviour.  I need to have a visible fill but an invisible line.  Or at least a fill that is more prominent than the line.  This is surely no longer possible with the new behaviour, since you cannot have a fill with a higher opacity than its associated line?

And I don't understand why `fillOpacity` cannot be made to work with named colours without this change.  If you have a 'red' line and your `fillOpacity` is 0.5 then you just fill with `red` at an opacity of 0.5?

**Comment by TorsteinHonsi** [comment]
> I need to have a visible fill but an invisible line. Or at least a fill that is more prominent than the line.

Then you can use the `lineColor` option. http://jsfiddle.net/highcharts/h2kg6p44/1/

> If you have a red line and your fillOpacity is 0.5 then you just fill with red at an opacity of 0.5?

Yes, that's why we did the change in 4.2. In 4.1 it didn't work: http://jsfiddle.net/highcharts/h2kg6p44/

**Comment by drmrbrewer** [comment]
So it looks like the closest I'm going to get to this (old):

http://jsfiddle.net/drmrbrewer/h2kg6p44/2/

is something like this:

http://jsfiddle.net/drmrbrewer/h2kg6p44/3/

The difference is that the series colour has full opacity in 4.2.0.

No other way of replicating the previous behaviour completely, based on the above example?

**Comment by drmrbrewer** [comment]
And regarding the non-working fillOpacity with a named colour, my point was that couldn't you just update the code to make it work?  Where color is `red` and `fillOpacity` is 0.5, red equates to `rgb(255, 0, 0)` and it's easy then to take account of the `fillOpacity` correctly: `rgb(255, 0, 0, 0,5)`.

**Comment by TorsteinHonsi** [comment]
If you set the fillOpacity to 1 and instead just set lineColor etc, the legend takes the opacity of the `color` property: http://jsfiddle.net/highcharts/h2kg6p44/5/

> you know that red equates to rgb(255, 0, 0)

Yes, you and I know that, but users frequently enter named colors and expect it to work seamlessly. We could fix that in Highcharts by adding a map from named colors to rgb values, but that would be a bloat.

**Comment by drmrbrewer** [comment]
Fair points, thanks.
