### ISSUE TITLE
Spider Chart - Tooltip not displayed in some cases if PointPlacement option is on

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#4865]
Spider Chart - Tooltip not displayed in some cases if PointPlacement option is on

Open below URL, To see tooltip : Mouse over on Point : Business  Analyst and Target series : 2M.

https://jsfiddle.net/pawanvjadhav/kckd9ywt/

On Mouse over, it always shows to tooltip of Point : Business  Analyst and Salary : 49300 even if you mouse over on Target series

**Comment by pawelfus** [comment]
Fails since 4392d1c

@TorsteinHonsi - could you revert commits for #4645 ? I will simply try to find a better solution for #4645 and we could close this and #3919 tickets. I think I will write tests for all tickets anyway, to prevent this happen again in the future.

**Comment by TorsteinHonsi** [comment]
It has been done. 0ca4f6aadc222b.
