### ISSUE TITLE
Axis.breaks for columnrange series

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#4868]
Example: http://jsfiddle.net/xw8mvegv/16/

`pointBreakColumn` method is not called at all. Most probably caused by using `low` and `high` for columnrange series and using `y` as `low` value.

**Comment by vijibalas** [comment]
am using an in inverted 'columnrange' as in http://jsfiddle.net/xw8mvegv/13/
The fix put in should work for inverted charts too.

**Comment by vijibalas** [comment]
@TorsteinHonsi Would appreciate if you would let us know if there is a workaround for this issue. pointbreakcolumn does not seem to be called for an inverted 'columnrange' chart. Appreciate any help. Thank you!

**Comment by pawelfus** [comment]
`inverted` type doesn't matter in this case.

*Internal note:*
Two things here:

- broken-axis module, should be added before highcharts-more. Otherwise, wrapper on `wrap(H.seriesTypes.column.prototype, 'drawPoints', drawPointsWrapped);` won't be applied (columnrange series inherits draw points from column). This should be put in the docs I think. Of course, we can wrap `wrap(H.seriesTypes.columnrange.prototype, 'drawPoints', drawPointsWrapped);`, but in case broken-axis module is added before, we wrap `drawPoints` twice. Any thoughts?
- it is fixed by adding `high` property for checking, but what about other series, for example `candlestick` - does it even make sense?

**Comment by vijibalas** [comment]
@pawelfus i see a reference and a commit saying this is fixed. Which version of highstock and higcharts do i pick to get this fixed ? Is it released to general public yet?
Thanks,

**Comment by TorsteinHonsi** [comment]
@pawelfus 
> Any thoughts?

I would say adding it to the docs is enough for now, unless we find some other place we can plug in. What I find missing sometimes in the `wrap` function, is the ability to set the priority of the wrapped functions. Like in this case, we would like a certain order, regardless of what source code order.

> it is fixed by adding `high` property for checking

What about getting properties from the `pointArrayMap`?

**Comment by pawelfus** [comment]
> What about getting properties from the `pointArrayMap?

Yes, I was thinking about this. We would need a bit to change the logic - `pointArrayMap` doesn't contain info about axis (`xAxis` vs `yAxis`) and `x` value. I think, that moving [this part](https://github.com/highcharts/highcharts/blob/0e364aa4dcf69fff06c313d47a6157233bd528df/js/modules/broken-axis.src.js#L308-L326) as separate function with two args (property_name and axis) would resolve that without duplicating the same part for `xAxis` and `yAxis`.

**Comment by TorsteinHonsi** [comment]
Okay, go for it and we'll see where it leads.​

**Comment by vijibalas** [comment]
when will the fix version of highstock/highcharts be available ?

**Comment by TorsteinHonsi** [comment]
It is now merged into the master, and will be released within some weeks. Until then, you may apply the fix to the latest version. See how to [apply a fix](https://github.com/highcharts/highcharts/blob/master/repo-guidelines.md#apply-a-fix).
