### ISSUE TITLE
No `shortWeekdays` in language object

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#4871]
In the language object (http://api.highcharts.com/highcharts#lang) we have `months` and the shortened equivalent `shortMonths`.  

On the other hand, we have `weekdays` without any shortened equivalent `shortWeekdays`.

Would be nice to have the ability to specify `shortWeekdays`?

**Comment by TorsteinHonsi** [comment]
Before we added `shortMonths`, we recommended using `lang.months[i].substr(0, 3)` in the formatter, but it turned out some languages didn't use 3 letter short codes for all months.

Is the same issue the case for weekdays, or can you use a solution like that?

**Comment by drmrbrewer** [comment]
I'm currently just using `%a` in the `Highcharts.dateFormat` functrion (http://api.highcharts.com/highcharts#Highcharts.dateFormat) and it probably works fine for most languages (there are a few provided by users here: http://stackoverflow.com/questions/7419358/highcharts-datetime-localization).

But I strongly suspect that there will be some languages for which it doesn't work so well.  And since you have `shortMonths` already it seems logical to have the ability to specify `shortWeekdays` too.

For example, looking at the Turkish language (http://stackoverflow.com/a/23963583/4070848) I suspect that the first two weekdays in the array will get confused when abbreviated (and the last two for that matter).

**Comment by TorsteinHonsi** [comment]
One option is to add your own definition for  `%a` and `shortWeekdays` using the [dateFormats API](http://api.highcharts.com/highcharts#Highcharts.dateFormats):

```js
Highcharts.dateFormats = {
    a: function(timestamp) {
        var date = new Date(timestamp),
            day = date.getUTCDay() === 0 ? 7 : date.getUTCDay();
        return Highcharts.getOptions().lang.shortWeekdays[day - 1];
    }
}
```

[View on jsFiddle](http://jsfiddle.net/highcharts/btnee5ad/).

**Comment by drmrbrewer** [comment]
+1

Except that the language object uses weeks that start on a Sunday, so I think it should be something more like:

http://jsfiddle.net/drmrbrewer/btnee5ad/1/

    Highcharts.dateFormats = {
        a: function(timestamp) {
            var date = new Date(timestamp),
                day = date.getUTCDay();
            return Highcharts.getOptions().lang.shortWeekdays[day];
        }
    }


    Highcharts.setOptions({
        lang: {
            shortWeekdays: ['Sun', 'Mån', 'Tys', 'Ons', 'Tors', 'Fre', 'Laur']
        }
    })

**Comment by drmrbrewer** [comment]
Further Q: how to make the example behave sensible (fall back on previous behaviour) if there is not `shortWeekdays` array defined, as in the following (which produces no chart):

http://jsfiddle.net/drmrbrewer/btnee5ad/2/

**Comment by drmrbrewer** [comment]
So in answer to my question above, I've been looking at the highcharts code and have come up with:

    Highcharts.dateFormats = {
        a: function(timestamp) {
            var date = new Date(timestamp),
                day = date.getUTCDay(),
                weekdays = Highcharts.getOptions().lang.weekdays,
                shortWeekdays = Highcharts.getOptions().lang.shortWeekdays;
            return shortWeekdays === undefined ? weekdays[day].substr(0, 3) : shortWeekdays[day];
        }
    };

I do note, however, that `date` is declared in the source as:

    var date = new Date(timestamp - getTZOffset(timestamp));

I've tried to access `getTZOffset()` in my code but couldn't; is there a way of properly adjusting for TZ in the new function definition, to make it consistent with the original?

**Comment by TorsteinHonsi** [comment]
See http://jsfiddle.net/highcharts/0pLuzmq5/ for demo with the fix applied.
