### ISSUE TITLE
Exporting module language problem

### ISSUE THREAD

**Issue by anderson-fachini** [highcharts/highcharts#4875]
HI,

I created custom messages (using Highcharts.setOptions) for the 'context menu' of exporting module, but they don't work.

I checked de code and found that the problem occurs because the extend function is called passing the parameters in the inverse order.

https://github.com/highcharts/highcharts/blob/master/lib/modules/exporting.src.js#L50

**Comment by pawelfus** [comment]
Hello,

We are trying to keep github tickets as bugs reports. For support questions, please use our forum or contact with us via mail ([support](http://www.highcharts.com/support)).

**Comment by anderson-fachini** [comment]
Ok, but it's a bug...

Simulation: http://jsfiddle.net/9j7vv1ov/

I found that this issue occurs because of this:

```javascript
        // wrong parameters order
	extend(defaultOptions.lang, {
		printChart: 'Print chart',
		downloadPNG: 'Download PNG image',
		downloadJPEG: 'Download JPEG image',
		downloadPDF: 'Download PDF document',
		downloadSVG: 'Download SVG vector image',
		contextButtonTitle: 'Chart context menu'
	});
```

and can be fixed with this:

```javascript
       // correct parameters order
	extend({
		printChart: 'Print chart',
		downloadPNG: 'Download PNG image',
		downloadJPEG: 'Download JPEG image',
		downloadPDF: 'Download PDF document',
		downloadSVG: 'Download SVG vector image',
		contextButtonTitle: 'Chart context menu'
	}, defaultOptions.lang);
```

**Comment by pawelfus** [comment]
Options don't work because it should be under `lang` property, like this: http://jsfiddle.net/9j7vv1ov/1/

**Comment by anderson-fachini** [comment]
Sorry.. the problem was: the file where I put the custom messages was loaded after the exports module, so the module override my messages.

Thanks for reply.
