### ISSUE TITLE
bar/ inverted columns with 0 values are visible after setting width

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#4877]
When using bar/ inverted column chart with 0 values, sometimes the column is visible with 1px width and sometimes it is not visible at all. It looks to be connected with chart.width and chart.spacingLeft parameters. 

example:
http://jsfiddle.net/qzj06ngk/5/

After changing width value from odd to even number, the columns are no longer visible. 

I didn't observe this problem when using data with non-zero values

**Comment by pawelfus** [comment]
Fails since https://github.com/highcharts/highcharts/commit/e83cef9
