### ISSUE TITLE
how to redrew the chart with options.data.table=domTable

### ISSUE THREAD

**Issue by 12343954** [highcharts/highcharts#4878]
when domTable changed , how to redrew the chart ?

here is my code : 
http://admin.koooke.com/systemManage/statistics.aspx

but i don't wanna re-execute the ‘init’ code

thank you so much !

**Comment by pawelfus** [comment]
`data.js` module doesn't observe changes in the data source. Instead, when updating table, update series too. For example: 

```js
    Highcharts.data({
        table: 'datatable',
        afterComplete: function(dataOptions) {
          $.each(dataOptions.series, function(i, series) {
            chart.series[i].setData(series.data, false);
          });
          chart.redraw();
        }
      },
      chart.options);

Live demo for you: http://jsfiddle.net/3wc9tyh7/


*Internal note:*
Maybe it's a good idea to add similar example to the demos?

**Comment by 12343954** [comment]
oh，unbelievable！Highcharts should have this function！

i ll try, thank you so much ! @pawelfus

**Comment by TorsteinHonsi** [comment]
Yes it's definately something to consider for the data module. Here's a more generic approach: http://jsfiddle.net/highcharts/3wc9tyh7/2/.

It could be made even more seemless by listening to DOM changes through the modern browsers' MutationObserver API. Additionally, a native implementation should have the same for `csv` data and possible spreadsheets too. But then we need to pass the data to the update, as there is no DOM to listen to.

**Comment by 12343954** [comment]
thank you so much ! @TorsteinHonsi 

when domTable changed, call the api "updateFromData" to redrew. 
that's what i want.

greate work , man !           :)

**Comment by TorsteinHonsi** [comment]
You're welcome!

**Comment by zhy1stgg** [comment]
@pawelfus  Nice, it's a  a good idea to add similar example to the demos
