### ISSUE TITLE
How to display custom lengend label and symbol

### ISSUE THREAD

**Issue by nhoctanker** [highcharts/highcharts#4879]
Hello ,
Dear sir, i want custom my lengend like image
http://prntscr.com/9jbt40
Symbol on top
Label lengend bottom
How to do that?
Sorry my english so bad

**Comment by pawelfus** [comment]
Hello,

We are trying to use github tickets as bugs. For support questions, please contact with us using our forum/email. See [support](http://www.highcharts.com/support) info.
