### ISSUE TITLE
Drill Up (Back) Button  is not  i18n'ed (translated)

### ISSUE THREAD

**Issue by dmitrygorbenko** [highcharts/highcharts#4880]
Hi guys,

I found what in module "treemap" the button "Back" is not translated.
File: treemap.src.js
Function: showDrillUpButton
Code: backText = (name || '< Back'),
Link: https://github.com/highcharts/highcharts/blob/master/js/modules/treemap.src.js#L800

I guess it should be translated with some config key like
http://api.highcharts.com/highcharts#lang.drillUpText
which is not used at all right now (and this is another bug).

thanks,
Dima

**Comment by pawelfus** [comment]
Hmm.. what exactly is wrong with using `drillUpText`? See: http://jsfiddle.net/x7evuxna/

**Comment by dmitrygorbenko** [comment]
I knew you would raise this question :)
The issue with text "< Back" -- it's not i18n'ed.
In our application then we drill-down we see "< Back" text in that button.
Word "Back" is not translated in this case and there is no way from config to control it.

Does it make sense ?

**Comment by KacperMadej** [comment]
Back button (drillUpButton) in treemap's drilldown can be set in series options.

    series: [{
      type: 'treemap',
      allowDrillToNode: true,
      drillUpButton: {
      	text: '<< Terug naar'
      },

Example: http://jsfiddle.net/x5369gwv/

*Internal note:*
If that is a correct behavior, then shouldn't this be mentioned in API or Docs?

**Comment by TorsteinHonsi** [comment]
The `lang.drillUpText` key is used with the drilldown module, but not with treemaps. 

The treemap drilling is actually a different implementation than the drilldown module, and unfortunately we couldn't come up with a more distinctive name. 

@jon-a-nygaard Proper docs should be added, and we need to consider a `lang` option.

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi: One solution could be to use lang.drillUpText for treemaps as well, but there could be a conflict if someone would use both drillDown and drillToNode in the same chart.

I will add the drillUpButton to the api under the treemap plotOptions.

**Comment by TorsteinHonsi** [comment]
> One solution could be to use lang.drillUpText for treemaps as well, but there could be a conflict if someone would use both drillDown and drillToNode in the same chart.

Yes, we need different text keys. It is already unfortunate that we use the same word for two different concepts.
