### ISSUE TITLE
dataLabels with useHTML: true - throws error in Firefox

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4881]
In Firefox (Win7). When there are about 400 or more data points and dataLabels are enabled and useHTML is set to true, then the error is thrown after chart is loaded:

```
too much recursion
```

referring to [this line of code](https://github.com/highcharts/highcharts/blob/master/js/highcharts.src.js#L660)

Example: http://jsfiddle.net/uvzj19be/1/

**Comment by sebastianbochan** [comment]
Problem not appears in macOSX.

**Comment by dawid84** [comment]
I can confirm this is occurring in Firefox on Win 7. And separately from the jsfiddle in our project running 5.0.3

**Comment by pawelfus** [comment]
The same issue on:

> Windows 10 Pro, Version 10.0.16299.248
> Firefox 58.0.2 (64-bit)

Works fine on osx.

**Comment by TorsteinHonsi** [comment]
Referring to this `wrap` statement, apparently it wraps multiple times:

https://github.com/highcharts/highcharts/blob/722bec52880c9d846861b6e4aefc54f5634442ad/js/parts/Html.js#L256-L268
