### ISSUE TITLE
plotLines & plotBands could not be seen without z-index value set for 3D chart after applying "frame" options

### ISSUE THREAD

**Issue by saurabhshahpune** [highcharts/highcharts#4889]
plotLines & plotBands could not be seen without z-index value set for 3D chart, after applying "frame" options for 3D,i.e options3d

http://jsfiddle.net/watgb6fn/1/  
http://jsfiddle.net/watgb6fn/  (zIndex set to 1)

so is it always expected to set z-index for plotLine & plotBand  ?

**Comment by pawelfus** [comment]
*Internal note:*
It looks like even when we have negative zIndex for frames, it will still render those groups/elements after elements without zIndex. I think we can apply default zIndex [here](https://github.com/highcharts/highcharts/blob/3eff6bf8b1298f95799665f3d560b0ead6d20148/js/parts/PlotLineOrBand.js#L78-L80): 

    attribs.zIndex = pick(zIndex, 1);

**Comment by TorsteinHonsi** [comment]
Excellent, if it works and passes tests, then go for it.
