### ISSUE TITLE
event.originalEvent removed, can no longer determine modifier keys

### ISSUE THREAD

**Issue by woodlandhunter** [highcharts/highcharts#4890]
It seems that the orignalEvent attribute was removed in this commit [https://github.com/highcharts/highcharts/commit/305f57fcd9b5ee766a05dde48f00027d1f753beb]

I was using this in the `selection` event to determine whether the user was holding shift down.

Is this an oversight? Is there another way to determine modifier key state?

Thanks.

**Comment by TorsteinHonsi** [comment]
As we're no longer using framework adapters, there's no need to keep track of the originalEvent, since the event argument itself is the original. So instead of reading `e.originalEvent.shiftKey`, it's now safe to read `e.shiftKey`.

**Comment by woodlandhunter** [comment]
Please see:

http://jsfiddle.net/gszaq2my/

It's using `master`, and on the selection event, there's no shiftKey attribute.

Apologies for not including an example upfront.
