### ISSUE TITLE
3d pie chart 

### ISSUE THREAD

**Issue by saurabhshahpune** [highcharts/highcharts#4891]
For 3D pie chart, after i disable all legends, i can see bar/line remains on the plot,what it represents?   

can refer this ; http://jsfiddle.net/FKKz9/129/

**Comment by pawelfus** [comment]
Fails since fc48e8e

**Comment by TorsteinHonsi** [comment]
Some investigation shows that the [hide function](https://github.com/highcharts/highcharts/blob/v4.2.1/js/parts-3d/SVGRenderer.js#L397-L404) is called, but for some reason the `visibility` attribute of the elements is not actually updated.

**Comment by warrenhusband** [comment]
still not working in 4.2.3. if you hide all but one series (or all the series), the final series still has a sliver showing. 
![screen shot 2016-02-19 at 11 23 50 am](https://cloud.githubusercontent.com/assets/5167072/13183210/5a79dea2-d6fb-11e5-8790-79da306a0150.png)

i've tested on my own sites as well as in js fiddle on the highcharts examples.

**Comment by TorsteinHonsi** [comment]
Sorry, the fix didn't make it into the master branch. It has been merged now, and will be part of next maintenance release.
