### ISSUE TITLE
Dynamically updated data in highstock goes wrong when there is a few num of series.

### ISSUE THREAD

**Issue by zhenglingfei** [highcharts/highcharts#4892]
I changed the series num to lower amount like 200 or 100 , the navigator seems work not properly?
Demo in :
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/dynamic-update/
I changed 999 to 200 it goes wrong~

**Comment by pawelfus** [comment]
Fails since d8705c1 
Demo: http://jsfiddle.net/22jm4g92/

**Comment by TorsteinHonsi** [comment]
Are you working on this @pawelfus ?

**Comment by pawelfus** [comment]
I assign tickets to myself when starting works on the ticket, so no I'm not. I just made simple checking for new tickets in case those are fixed on the master branch and/or are regressions.

**Comment by TorsteinHonsi** [comment]
> I assign tickets to myself when starting works on the ticket
Excellent

**Comment by zhenglingfei** [comment]
Opps, is that bug still existed? #4701 seems already fixed in 4.1 and set turboThreshold to 0 seems not working. Thanks for support.

**Comment by pawelfus** [comment]
Note: it works on the master branch: http://jsfiddle.net/22jm4g92/1/
