### ISSUE TITLE
Line chart click event has error "this" scope

### ISSUE THREAD

**Issue by RisingWonderland** [highcharts/highcharts#4893]
Please see this example: http://jsfiddle.net/5a5pq0u2/

Try to click the different points on the two lines, but on the same x-axis range. Then check the console, the two point's click event has the same  "this" scope.

Current version: 4.2.1

**Comment by pawelfus** [comment]
This is bug in the current version - already fixed on the master branch: http://jsfiddle.net/5a5pq0u2/1/
