### ISSUE TITLE
line chart with null value in series reports unsorted data error 15

### ISSUE THREAD

**Issue by skwakman** [highcharts/highcharts#4894]
We're trying to render a line charts with gaps in the line. To do this, we added null values in the series data. The chart is rendered correctly, however it reports a highcharts error 15 (unsorted data) in the console.

See fiddle: http://jsfiddle.net/Kmandr/54v32w9u/

**Comment by pawelfus** [comment]
The problem is missing `x` value for that null point. In the case above it works, but imagine data like: 

    [ [10, 10], [15, 10], [121, 10], null, [300, 10] ]

What `x` value should be applied for a null point? I think you should add this `x` value, take a look: http://jsfiddle.net/54v32w9u/1/

**Comment by skwakman** [comment]
Ah adding a value for x works, yeah makes sense. Thanks!
