### ISSUE TITLE
Sometimes the scrollbar does not appear when using multiple x axis

### ISSUE THREAD

**Issue by pghilardi** [highcharts/highcharts#4895]
Steps to reproduce:

1) Create 4 x axis.
2) Add a series only to the second x axis (not to the first x axis).

The scrollbar will not appear, because highcharts listens only for events on the xAxis[0].

``` javascript
addEvent(chart.xAxis[0], 'afterSetExtremes', afterSetExtremesHandlerScroller)
```

**Comment by pawelfus** [comment]
Demo: http://jsfiddle.net/177jhj01/
