### ISSUE TITLE
Wrong series index returning on line click  (used to work, official demo doesn't work any more either)

### ISSUE THREAD

**Issue by somuchcoffee** [highcharts/highcharts#4896]
I've done this in the past without any issues, but for some reason it's stopped working properly with the latest versions of highstock/highchart.

Per the docs...
http://api.highcharts.com/highstock#series<line>.events.click

The official example doesn't work, clicking the MSFT line returns ADBE:
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/stock/plotoptions/series-events-click/

If you switch it back to Highstock 2.1.6, it works properly:
http://jsfiddle.net/8cfdjc3x/1/

Why did this stop working properly, and how can we fix it - or what's a work around?

**Comment by somuchcoffee** [comment]
It returns the series with the lowest index. For example, if i have 10 series and I show any random one it will return the correct index. But if you make any more than 1 visible, it only returns the lowest index.

**Comment by somuchcoffee** [comment]
The last version it works properly in is: 2.1.9 

As of 2.1.10 this it's broken

**Comment by TorsteinHonsi** [comment]
@pawelfus Is this another case of the k-d-tree bug?

**Comment by TorsteinHonsi** [comment]
> Is this another case of the k-d-tree bug?

Apparently it is. It works in the latest development code: http://jsfiddle.net/highcharts/u15vj38g/
