### ISSUE TITLE
Should series data x support string ?

### ISSUE THREAD

**Issue by yutingzhao1991** [highcharts/highcharts#4897]
like this:

```
[{
  x: '2015-01-01',
  y: 2123
}, {
  x: '2016-01-02',
  y: 2421
}]
```

x is a date string，not a point time，so datetime type not the perfect solution.

**Comment by TorsteinHonsi** [comment]
You can use a category axis and point name if you don't want to run a datetime axis: http://jsfiddle.net/highcharts/4uqvz31d/
