### ISSUE TITLE
Column starts under set threshold if top for yAxis is set

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4898]
In a chart with `top` set for yAxis, columns start under 0 (default threshold).
Example: http://jsfiddle.net/e782nu7s/

**Comment by TorsteinHonsi** [comment]
The `yAxis.height` is 100% by default. Consequently, when setting the top to 1%, the Y axis will extend 1% below the plot area. Instead, the height should be set to 99%. http://jsfiddle.net/highcharts/e782nu7s/2/.

**Comment by KacperMadej** [comment]
With height of `70%` and top of `3%` the problem is visible in:
- Win7/Chrome with height of conteiner set to 400px - http://jsfiddle.net/ma6ds0s5/
- Win7/IE11 with height of 401px - http://jsfiddle.net/ma6ds0s5/1/

Related or maybe even the same as #4899

**Comment by TorsteinHonsi** [comment]
I can see it too, on Chrome/Mac. Simplified to Highcharts: http://jsfiddle.net/highcharts/ma6ds0s5/2/

It is probably a rounding issue.

**Comment by geoff604** [comment]
@TorsteinHonsi  Hi, I'm wondering how this fixes this bug, as you only added some commented lines of code? Will these lines be uncommented in a separate checkin? Thanks, Geoff

**Comment by TorsteinHonsi** [comment]
Sorry for that, looks like a mistake. Additional commit coming up.

**Comment by geoff604** [comment]
No worries, thanks for the fix :)
