### ISSUE TITLE
plotLine not visible for some height or top setting for yAxis

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4899]
Height example: http://jsfiddle.net/sme9ah03/
Top example: http://jsfiddle.net/sme9ah03/1/
Without setting - plotLine visible: http://jsfiddle.net/sme9ah03/2/

**Comment by TorsteinHonsi** [comment]
In the height example, the plot line is visible on my machine, which seems correct.

In the Top example, you have set the `top` to 2%, but the height is still default at `100%`. Consequently, the zero plane is 2% below the plot area, and the plot line is hidden, which seems to me to be the correct behaviour. If we compensate by setting the `height` to 98% it is drawn as predicted: http://jsfiddle.net/highcharts/sme9ah03/3/

**Comment by KacperMadej** [comment]
Height example shows error (plot line not visible) when using:
OSX 10.11.1 / Firefox (43.0.4),
Win7 / Chrome (47.0.2526.106 m),
Win7 / IE 11

Setting height to `36%` makes error visible in other browsers (OSX/Chrome, Win7/FF).
Example: http://jsfiddle.net/sme9ah03/4/

**Comment by pawelfus** [comment]
Quite interesting, tested on W7&Chrome:

- `height: 401px`:
![400](https://cloud.githubusercontent.com/assets/1453926/12172072/dfd7d2a8-b54e-11e5-8add-153bfa180613.png)

- `height: 400px`: 
![401](https://cloud.githubusercontent.com/assets/1453926/12172073/e201b148-b54e-11e5-99ff-999f31f0c34d.png)

**Comment by TorsteinHonsi** [comment]
It probably has to do with rounding
