### ISSUE TITLE
How to change the language for already rendered chart?

### ISSUE THREAD

**Issue by amit1911** [highcharts/highcharts#4901]

**Comment by amit1911** [comment]
I am having problem changing the language for the text in chart when the user changes the language.
For example - suppose the current language for my web application is english and then i render the graph in english. Now if the user changes the language from english to german, how can i change the text in the chart from english to german without replotting/redrawing the chart. I am trying to change the 'resetZoom' when the user switches the language.

**Comment by sebastianbochan** [comment]
Hi, you've posted to our issue tracker.
For general tech support, please see www.highcharts.com/support.
