### ISSUE TITLE
Extra data unavailable during grouping data

### ISSUE THREAD

**Issue by rvanlaak** [highcharts/highcharts#4903]
We have a `StockChart` and add data on the xAxis of the type `datetime`. There are four series on the chart, and there are some problems related to the grouping. 

There are four series (with `dataGrouping.approximation` set to `sum`) on which all data points looks like this:

    {
        x: Date.UTC({{ date|date('Y') }}, {{ date|date('m') - 1 }}, {{ date|date('d') }}),
        y: {{ data.words }},
        pages: {{ data.pages }}
    }

When no grouping is applied (default state), the `tooltip.pointFormat` nicely shows the y-value and the pages for each serie:  

```js
pointFormat: '<span style="color:{series.color}">{series.name}</span>: <b>{point.y:,.0f}</b> Pages: <b>{point.pages:,.0f}</b><br/>'
``` 

1. When `rangeSelector.selected` is set to of the `rangeSelector.buttons` then the grouping doesn't work anymore. How can we enable the grouping by default, and let the tooltips keep working?
2. When the grouping is applied (by clicking one of the `dataGrouping` buttons) the y-values are nicely summed up but the `pages` isn't anymore. Can the extra data be marked to also be grouped?
3. We also want the `point.pages` data to be summed up, so we also can show that in the tooltip. We tried this using a custom `formatter` but the summed data points don't have any of the additional data. How can we show the custom data in the tooltip when the data is grouped?

```php
tooltip: {
    formatter: function() {
        console.log(this.points);
    }
},
```

**Comment by TorsteinHonsi** [comment]
Thanks for writing, but keep in mind this is our issue tracker, not general tech support. Please see www.highcharts.com/support for the appropriate channels.

PS: custom point attributes aren't grouped. One idea could be that you have a linked series for the pages, and reflect the values in the tooltip formatter.

**Comment by rvanlaak** [comment]
@TorsteinHonsi 1. looks like a clear bug to me :+1: 

I agree the other two are feature requests.

**Comment by TorsteinHonsi** [comment]
Yes, by the description it sounds like a bug. Can you provide a demo? It is working in our own cases, take for example the [default line sample](http://jsfiddle.net/highcharts/xuz4fukf/), where it is grouped by weeks when you set `rangeSelector.selected` to the _All_ button.
