### ISSUE TITLE
Pie config with both innerSize and size produces labels overlap on reflow

### ISSUE THREAD

**Issue by ecris87** [highcharts/highcharts#4905]
Setting both _innerSize_ and _size_ options in highcharts config for "pie" type chart causes a labels overlap issue when expanding the chart to a larger size, then collapsing to the original size. Depending on expanded size, labels either overlap the chart or overflow outside the container when a larger width is given.

Example here: http://jsfiddle.net/zzyeqjuk/

**Comment by TorsteinHonsi** [comment]
Note: It happens regardless of `innerSize`.
