### ISSUE TITLE
During a selection, if mouse hovers over a 2nd chart before mouse is released selection is not completed

### ISSUE THREAD

**Issue by woodlandhunter** [highcharts/highcharts#4906]
Here's a fiddle that can be used to reproduce the issue:

https://jsfiddle.net/ffstvons/

It appears hoverChartIndex is reset when the mouse enters the second chart and `pointer.drop()` is only called for the second chart inside [onDocumentMouseUp](https://github.com/highcharts/highcharts/blob/master/lib/highcharts.src.js#L10399)

Possible solutions:

- Use `selectionChartIndex` or similar to track a chart with an active selection and call `pointer.drop()` for this chart too.
- Check the `charts` array for any chart that has a `chart.pointer.selectionMarker` object and call `pointer.drop()` for the charts that do.

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard Another possible solution is to call `drop` when the `hoverChartIndex` changes in the `onDocumentMouseMove` function.

**Comment by woodlandhunter** [comment]
Unless I misunderstand, I don't think the effect would be good. It  sounds like it will cause a drop before you let go of the mouse button.

e.g. user drags too far over the 2nd chart (I have 2 charts next to each other) and then tries to drag back to try to make the selection smaller... whoops it already dropped...

Thanks for your quick reply

**Comment by jon-a-nygaard** [comment]
This issue is fixed in the next maintenance release (> 4.2.1).

**Alternative fix for those in need:**
Open the source files of highcharts, highstock and highmaps and search for the method onContainerMouseMove and replace following sections
```javascript
// Replace this
hoverChartIndex = chart.index;

// With this
if (!defined(hoverChartIndex) || !charts[hoverChartIndex].mouseIsDown) {
    hoverChartIndex = chart.index;
}
```

**Comment by mhwlng** [comment]
I updated to 4.2.2 and now when I move the mouse over a highstock chart that as PlotBands

I get 

Unable to get property 'mouseIsDown' of undefined or null reference

in the abeve mentioned part.

If I get rid of the PlotBands, there is no error

**Comment by mhwlng** [comment]
This causes an exception error when loading a chart for a second time  
report_chart.destroy();
report_chart = new Highcharts.Chart(chart_data);


in Highstock JS v4.2.2 (2016-02-04)

chart.destroy contains :
charts[chart.index] = UNDEFINED;

chart.init contains :
chart.index = charts.length;
charts.push(chart);

so the charts array keeps growing all the time.

first time:
charts[0] = something
hoverChartIndex = 0  -> no problem

second time:
charts[0] = UNDEFINED
charts[1] = something
hoverChartIndex = 0  -> causes exception charts[0].mouseIsDown undefined

you could replace in charts.destroy :
charts.splice(chart.index, 1);

this also gets rid of the problem :

if (!defined(hoverChartIndex) || !defined(charts[hoverChartIndex]) || !charts[hoverChartIndex].mouseIsDown) {
  hoverChartIndex = chart.index;
}

**Comment by TorsteinHonsi** [comment]
We don't want to splice the charts array, because it will destroy references to charts by index. See http://api.highcharts.com/highcharts#Highcharts.charts.

Will this fix work?
```js
		if (!defined(hoverChartIndex) || !charts[hoverChartIndex] || !charts[hoverChartIndex].mouseIsDown) {
			hoverChartIndex = chart.index;
		}
```

**Comment by mhwlng** [comment]
yes, that gets rid of the exception error...

The charts array still keeps growing, every time you do :
report_chart.destroy();
report_chart = new Highcharts.Chart(chart_data);

**Comment by TorsteinHonsi** [comment]
> The charts array still keeps growing, every time you do :

Yes, that's intensional.

**Comment by mhwlng** [comment]
ok
