### ISSUE TITLE
Zooming in on a Highstock chart with dataGrouping only renders line segments between visible points

### ISSUE THREAD

**Issue by mturley** [highcharts/highcharts#4907]
I have found what I believe to be a bug in highstock.  I am working on a chart with a datetime x-axis containing irregular time-series data (with long gaps) and dataGrouping set to forced: true.  I have found that when I zoom in on the chart, I don't see a cropped version of the larger series line, instead all I see are the points visible in the zoom range and line segments connecting them.  And if I zoom to a range that contains no points, the line completely disappears!

I've reproduced the issue with a simple single-series line graph here:  http://jsfiddle.net/nj8rk1nj/2/

The default zoom in that fiddle shows a line extending from the point in the middle up to the right, but it should also show the line extending offscreen to the left towards the last point.  If you click Zoom: All, you can see that it renders normally, and if you zoom and move around you'll see the inconsistent behavior.  I would expect the rendered line to always look like a larger version of the selected area in the navigator below, but it does not.

I'm aware that disabling dataGrouping will eliminate the issue, but I need dataGrouping enabled for my real use case since I have a very high density of data on the x-axis for a column series on the same axis, and I need the columns to be wide enough to see at larger zoom ranges.  I removed the column series from this example for simplicity, that's just the reason for requiring dataGrouping to be forced on this line series.

I'm posting this here because I believe it is a bug, but I would also appreciate any support I can get to work around this issue!  This is my first time participating in the highcharts community, let me know if I should post this elsewhere.

**Comment by TorsteinHonsi** [comment]
Thanks for your report, I agree this is a bug.

> I would expect the rendered line to always look like a larger version of the selected area in the navigator below, but it does not.

Yes, but only if the grouping is exactly the same, for example if you have explicitly set the `dataGrouping.units`: http://jsfiddle.net/highcharts/nj8rk1nj/3/

**Comment by TorsteinHonsi** [comment]
_Internal note_:

In the `groupData` function, we run a loop to start with the first point within the X axis range:
```
	// Start with the first point within the X axis range (#2696)
	for (i = 0; i <= dataLength; i++) {
		if (xData[i] >= groupPositions[0]) {
			break;
		}
	}
```
This is problematic because we need the points outside on the left to be grouped too, but if we decrease i by 1 to include the last point outside, it places the point at the edge (grouped position) instead of the actual data point.

**Comment by mturley** [comment]
Thanks for the quick response!  Do you have any advice about how I might be able to work around this in the meantime?  I was considering using two separate x-axes, one for the line series with datagrouping disabled and one for the column series with datagrouping enabled.  But I think this would cause strange issues with my tooltip, and I think there must be a better way.
