### ISSUE TITLE
also about the data order

### ISSUE THREAD

**Issue by rubyisapm** [highcharts/highcharts#4908]
I have data ordered max to min, instead of min to max. The highcharts can render the chart correctly, but it gave me a warning like 'Highcharts error #15: www.highcharts.com/errors/15'. Is it necessary to reverse the array data or just ignore the warning? If can, I don't want to reverse the order because I'll use the data for other use. Thanks for your help.

**Comment by pawelfus** [comment]
Hello,
This is our bug tracker, for questions, please contact with us directly using email or on our forum. See [support details](http://www.highcharts.com/support).

Thanks!
