### ISSUE TITLE
Point range in series object is missing - HC 4.2+

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4909]
The point range value in series object is missing since 4.2.0 version and is kept only in xAxis. 

Examples:
4.2.1
http://jsfiddle.net/56saqhL7/

4.1.8
http://jsfiddle.net/56saqhL7/1/

**Comment by TorsteinHonsi** [comment]
What's the use case? Point range is only an internal property used for laying out the axis, it is not part of the API (not to be confused with `series.options.pointRange`, the option that influences on the rendered pointRange).

**Comment by sebastianbochan** [comment]
Generally it was a request from user, who asked why we changed that and point to report that issue.

**Comment by TorsteinHonsi** [comment]
Okay, maybe he can use `series.options.pointRange`, or `series.closestPointRange`.
