### ISSUE TITLE
xAxis labels style width not honored unless labels wrap

### ISSUE THREAD

**Issue by toliwaga** [highcharts/highcharts#491]
Although issue #197 was closed, the width setting for xAxis label style for bar charts is ignored once the requested width exceeds the size of the longest label.

The 197 test case can still be used to verify this (no difference between charts if width set to 250px or 300px)

Test case: http://jsfiddle.net/highcharts/h74cE/7/

Why should I care? because I want to create two charts and ensure that they look the same (have the same relative width bar and label components.) Unless there is some other way to do this. All the same, it seems like width should be honored...

**Comment by m1neral** [comment]
Are there any new ways to set axis.labels of categories?
I need to align several bar charts with range different length of categories...  
http://jsfiddle.net/oetuos9m/1/
