### ISSUE TITLE
Pie config data labels style overrided in export chart are not applied

### ISSUE THREAD

**Issue by andreibleotu** [highcharts/highcharts#4912]
Overriding pie data labels style in export mode or in exportChart are not applied. In turn the previous data labels style is used.
This happens for both image or pdf export.
Note: dataLabels - backgroundColor for export is applied, also overrided data labels style for other chart types works

Example here :
in exporting options http://jsfiddle.net/LLExL/5577/ 
in exportChart http://jsfiddle.net/LLExL/5579/

**Comment by pawelfus** [comment]
Looks similar to #1562

**Comment by andreibleotu** [comment]
yes, too bad that style is not fixed

**Comment by ValentinH** [comment]
:+1:  Same problem here, this is quite annoying.

**Comment by ValentinH** [comment]
@TorsteinHonsi Thanks for working on this issue.

However, I've just tested your changes and it seems that it didn't fully resolve the issue.
Check this demo: http://jsfiddle.net/7remk430/  : 
At first, the data labels are not displayed on purpose but should be displayed in exports, but this still does not work unless I'm doing it wrong.

**Comment by ValentinH** [comment]
Tested and verified the fix. :+1:  Thanks

**Comment by TorsteinHonsi** [comment]
You're welcome!
