### ISSUE TITLE
Regression in calculating chart size

### ISSUE THREAD

**Issue by liorbentov** [highcharts/highcharts#4913]
There was a regression in the latest release (4.2.1) of Highcharts, in calculating the chart size.

Previously, the padding of the container was subtracted from it's width and height.
Now the padding is not considered...

This has caused a regression in the chart size calculation in our application. Is this intentional and if not - can it be fixed in the next release?

**Comment by TorsteinHonsi** [comment]
Previously we used jQuery to detect the box size, unless you used the Standalone Framework. Now we don't have a framework anymore, so we use the `window.getComputedStyle` API. 

In what browser are you experiencing the problem? I set up s demo at http://jsfiddle.net/highcharts/9Lvvyvbk/ and tried it in Chrome, Firefox, Safari and Edge, and they all render it correctly.

**Comment by snkashis** [comment]
Yeah I'm seeing the same behavior as well.

**Comment by TorsteinHonsi** [comment]
@snkashis @liorbentov Can you show us a live reproduction?

**Comment by snkashis** [comment]
@TorsteinHonsi can i email you to share details? no public repro available

**Comment by TorsteinHonsi** [comment]
Sure, send an email to support@highcharts.com and someone will help you isolate it.

**Comment by hugomrdias** [comment]
@TorsteinHonsi check this example http://jsfiddle.net/m8rvtr07/

**Comment by TorsteinHonsi** [comment]
Currently Highcharts uses `getComputedStyle` to get the width of the container element. It seems that it is safer to get the offsetWidth of the element and substract the left and right padding, so the `getStyle` method would look like this:
```js
/**
 * Internal method to return CSS value for given element and property
 */
getStyle = function (el, prop) {

	var ret;
	if (prop === 'width') {
		return el.offsetWidth - getStyle(el, 'padding-left') - getStyle(el, 'padding-right');
	} else if (prop === 'height') {
		return el.offsetHeight - getStyle(el, 'padding-top') - getStyle(el, 'padding-bottom');
	}
	
	style = win.getComputedStyle(el, undefined);
	return style && pInt(style.getPropertyValue(prop));
};
```

This seems to work regardless of the `box-sizing` setting, but I haven't been able to test in IE yet.

**Comment by hugomrdias** [comment]
you should use scrollWidth
check this example 

https://jsbin.com/zimori/edit?css,js,console,output

**Comment by TorsteinHonsi** [comment]
Test case: http://jsfiddle.net/highcharts/gaaoeaae/

Highcharts 4.1 rendered this without scrollbars.
