### ISSUE TITLE
Boost module - Cannot read property 'style' of null

### ISSUE THREAD

**Issue by hkostia** [highcharts/highcharts#4914]
https://jsfiddle.net/dbeaxfsv/2/

```
Uncaught TypeError: Cannot read property 'style' of null
(anonymous function) @ boost.src.js:501
eachAsync @ boost.src.js:83
(anonymous function) @ boost.src.js:80
```

This happens if there's an update to the chart soon after the chart has been initialized and drawing has started.

Tested with latest master and v4.2.1.

**Comment by jon-a-nygaard** [comment]
@hkostia Thanks for reporting this issue. The error was caused because the loadingDiv was destroyed async, when it was expected to exist during the redraw. 

This issue is fixed in the next maintenance release (> 4.2.1), or you can gather the latest boost module from this repository.
