### ISSUE TITLE
highchart multiple series appearance 

### ISSUE THREAD

**Issue by saurabhshahpune** [highcharts/highcharts#4915]
If i have 2 or more series to plot the chart,one of them is of the type 3D (i.e column,bar etc) and  further second series is of the type 2D (i.e line,scatter etc),here i want to pull up that second series in front postion,over the 3D type series(i.e column),Then how to decide z-index factor( z-index value ) to achieve this scenario?  

http://jsfiddle.net/chLckgwx/  (here z-index set by trial basis.)

**Comment by pawelfus** [comment]
Just to confirm - this is the chart you want to see, right? 

In general, `zIndex` for column series depends on the number of column series and, if enabled, stacking/grouping. For each series, maximum index in series increases by 10. For example, when using 5 column series on the chart, then your series should have `zIndex: 5*10+1` (number_of_series * 10 + 1). 

Note: we are using github tickets as bug reports, not support questions. For general/technical questions please, use our forum or contact with use using email.
