### ISSUE TITLE
Point.update with no change to y value, in load event, when exporting is hiding the point.

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4916]
If in a load event of a chart is a point.update that do not have y, then when exporting the point gets a new value - probably a null.
Example: http://jsfiddle.net/9mtLykpn/1/
Steps: 1. export the chart - exported image lacks column with the red dataLabel

Was working in 4.1.9 - http://jsfiddle.net/9mtLykpn/

**Comment by pawelfus** [comment]
**Workaround:**

Set `y` value explicit: http://jsfiddle.net/9mtLykpn/2/

    chart: {
      type: 'bar',
      events: {
        load: function() {
          this.series[0].points[3].update({
          	y: this.series[0].points[3].y,
            dataLabels: {
              color: 'red'
            }
          }, true, false);
        }
      }
    },

**Comment by sergevic** [comment]
Reported issue also valid for line chart with xAxis type 'datetime'.
Above workaround have to be done for x value as well, otherwise changed points start drawing in 1970 year (before/after screenshot http://take.ms/NMx9S)
Reproduced issue: http://jsfiddle.net/rorhpneb (highchart v 5.0.7)
