### ISSUE TITLE
Click event issue on HighStock 4.2 when use addSeries

### ISSUE THREAD

**Issue by alisabzevari** [highcharts/highcharts#4919]
When you add series by `chart.addSeries`, click on every series results running event handler of first series!
See this fiddle: http://jsfiddle.net/alisabzevari/dr0wtrha/

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, it's fixed in the master: http://jsfiddle.net/highcharts/dr0wtrha/1/.
