### ISSUE TITLE
ignoreHiddenSeries causes column wrong position and width after legendItemClick

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4921]
Example: http://jsfiddle.net/uct6eqga/
Steps: 
1. hide both series via legend
2. show the black series via legend
3. show the blue series via legend
4. the black series is overlapping the blue one - is not adjusted

Might be related to #943.

**Comment by TorsteinHonsi** [comment]
Debugging hints: Look in the ColumnSeries `getMetrics` function. The columns are not supposed to go full width when the ignoreHiddenSeries is false, it is supposed to reserve space for any hidden series.
