### ISSUE TITLE
Areasplinerange not printed when compare parameter

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4922]
From some reasons, when compare parameter is set, then yBottom is NaN and shape is not printed.

Example:
- http://jsfiddle.net/3b8hvdxm/

Without comparing:
- http://jsfiddle.net/yf5ncwtg/

**Comment by TorsteinHonsi** [comment]
Debugging hints: Look for the `setCompare` and `modifyValue` functions in StockChart.js. Additionally, `yBottom` is probably set in the `translate` function of AreaRange.js.

**Comment by arnabk** [comment]
This is a blocker for us. Any update?

**Comment by TorsteinHonsi** [comment]
Sorry for the delay. See the fix in action at http://jsfiddle.net/highcharts/3b8hvdxm/1/. Does this work for you?

**Comment by arnabk** [comment]
Looks like its fixed. When is it going to show up https://github.com/highcharts/highstock-release

**Comment by TorsteinHonsi** [comment]
We have release cycles of 1-2 months. Next release is due within some weeks.
