### ISSUE TITLE
Highstock: addPoint does't update series in navigator if dataGrouping is not applied

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4923]
Example: http://jsfiddle.net/7x7e0paz/
(Created as from [the demo](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/dynamic-update/) by reducing number of points)

Workaround - force dataGrouping for navigator's series: http://jsfiddle.net/7x7e0paz/1/

**Comment by sebastianbochan** [comment]
Workaround: call addPoint on navigator series.

Example: http://jsfiddle.net/hd1rz3uk/
