### ISSUE TITLE
Crosshair only work for one y axis

### ISSUE THREAD

**Issue by pghilardi** [highcharts/highcharts#4927]
On normal or inverted charts, the crosshair only works for one of the y axis (I think that is the last one). As I have only one x axis, to the x axis it is working.

**Comment by KacperMadej** [comment]
Could you post live example, like jsFiddle? How to recreate the problem?

**Comment by pghilardi** [comment]
Sure! 

Fiddle: http://jsfiddle.net/af9qv8am/

**Comment by KacperMadej** [comment]
Thank you for the fiddle. Indeed looks like a bug.
Simple example: http://jsfiddle.net/5jfd99tp/

Might be related to #2888
