### ISSUE TITLE
difficult to click pointer to drilldown in IE8

### ISSUE THREAD

**Issue by cxytomo** [highcharts/highcharts#4929]
When I click point on line chart, it's hard to drilldown in IE8.

After I set cursor to pointer, I found out that I'm not actually clicking on the point.
Pointers offset quite a distance. See my pic for more information. (I cann't keep the cursor on when making screenshot, so I just take a picture).

![473121475038244538](https://cloud.githubusercontent.com/assets/2089688/12348013/5c8064dc-bb9e-11e5-918e-c342ddb3078b.jpg)

Is there a way deal with it?

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! It seems that the click events aren't captured at all on the point markers and halo, only on the graph line. Also, the pointer cursor is not applied to the halo and the marker.

Simplified reproduction steps.
1. Open http://jsfiddle.net/highcharts/1bpjv419/show in IE8
2. Click on the point marker or halo. 
3. Expected message in console, but the event doesn't trigger.
4. Click on the graph line, the event now triggers correctly
