### ISSUE TITLE
Display overlapping ranges stacked instead of overlapping

### ISSUE THREAD

**Issue by felixfbecker** [highcharts/highcharts#4930]
I need to generate columnrange charts with categories on the Y axis and datetime on the X axis. There are multiple ranges per category. Sometimes, two ranges overlap in the same category, like this:
```js
data: [
    [0, Date.parse('Sun, 17 Jan 2016 16:00:00 GMT'), Date.parse('Sun, 17 Jan 2016 17:00:00 GMT')],
    [0, Date.parse('Sun, 17 Jan 2016 16:30:00 GMT'), Date.parse('Sun, 17 Jan 2016 17:30:00 GMT')]
]
```
As you can see, one range goes from 16:00 to 17:00, and the other goes from 16:30 to 17:30, in the same category and the same series.
Currently, these get rendered overlapped: https://jsfiddle.net/felixfbecker/18mst6dj/3/
![chart](https://cloud.githubusercontent.com/assets/10532611/12378571/45176a16-bd42-11e5-9a16-7a82b3ef3e03.png)

I need those to display more like this (quick Illustrator mockup):

![chart- 1](https://cloud.githubusercontent.com/assets/10532611/12378565/ed691ae4-bd41-11e5-8767-d08c3977b021.png)

So they dont get overlapped but are shown stacked, but still in the same category. Is there any way to achieve this?

**Comment by TorsteinHonsi** [comment]
Hi Felix, please see www.highcharts.com/support for the appropriate channels for tech support. GitHub Issues is for bug tracking.

**Comment by felixfbecker** [comment]
Sorry for the inconvenience.

**Comment by felixfbecker** [comment]
In case someone stumbles upon this, I found the answer in the forums: http://forum.highcharts.com/post120037.html

**Comment by satya472** [comment]
hi @felixfbecker 
Currently we are running into similar issue and came across this post. http://forum.highcharts.com/post120037.html link is not working any more. Can you please help me if you have any other link for this issue or any guidance on this is highly appreciated.

Thank you
