### ISSUE TITLE
tooltipRefresh event missing on chart object in v4.2.0

### ISSUE THREAD

**Issue by late-warrior** [highcharts/highcharts#4931]
We are relying on the 'tooltipRefresh' event on the chart object to support a custom tooltip. However since the v4.2.0 release, this no longer works.   

```
        $(chart).on('tooltipRefresh', function(event) {
                event.preventDefault();
                event.stopPropagation();
                $('#display').text(event.text);
        });
```

[Fiddle](http://jsfiddle.net/xbhvyzg8/2/)

What is the correct way to do this ?  I see this option is undocumented, so must have been internal.

I have noticed the same problem in [highstock-browserify](https://www.npmjs.com/package/highstock-browserify) - I think this has got to do with the way things are bundled.

**Comment by pawelfus** [comment]
How about using [`tooltip.formatter`](http://api.highcharts.com/highcharts#tooltip.formatter) instead? In general, you should return string in formatter, but you can return `false` to prevent displaying tooltip, but still, you can use generated string in any way you want to: http://jsfiddle.net/yqbm38x0/

**Comment by TorsteinHonsi** [comment]
@late-warrior Your issue stems from the the fact that Highcharts 4.2 no longer uses jQuery for event handling, so you can't use jQuery to assign events anymore. You should use Pawel's solution, or alternatively assign the event like this:

 ```js
Highcharts.addEvent(chart, 'tooltipRefresh', function (event) {...
```
