### ISSUE TITLE
Stock chart will not update when shifting with multiple graphs

### ISSUE THREAD

**Issue by G-Kevin** [highcharts/highcharts#4935]
When having a multiple line stock chart and adding a point with shift-parameter set to true, highstock will stop updating the chart and throws error:

    Uncaught TypeError: Cannot read property 'series' of undefined

Code:

    $(function() {
        $('#my_chart').highcharts('StockChart', {
            chart: {
                enabled: false,
                borderWidth: 0,
                marginBottom: 25
            },
            rangeSelector: {
                enabled: false,
                plotOptions: {
                    series: {
                        animation: true
                    }
                },
                selected: 1
            },
            scrollbar: {
                enabled: false
            },
            title: {
                enabled: false
            },
            tooltip: {
                enabled: false
            },
            exporting: {
                enabled: false
            },
            legend: {
                enabled: false
            },
            credits: {
                enabled: false
            },
            animation: {
                enabled: false
            },
            navigator: {
                enabled: false
            },
            yAxis: {
                ordinal: false,
                max: 400,
                min: 0,
                title: {
                    text: 'Values in %'
                },
                plotLines: [{
                    color: 'red',
                    width: 0.5,
                    value: 100,
                    dashStyle: 'LongDash',
                    label: {
                        text: '100',
                        align: 'right',
                        y: -1,
                        x: 0
                    }
                }, {
                    color: 'lightgrey',
                    width: 0.5,
                    value: 200,
                    dashStyle: 'LongDash',
                    label: {
                        text: '200',
                        align: 'right',
                        y: -1,
                        x: 0
                    }
                }, {
                    color: 'lightgrey',
                    width: 0.5,
                    value: 300,
                    dashStyle: 'LongDash',
                    label: {
                        text: '300',
                        align: 'right',
                        y: -1,
                        x: 0
                    }
                }, {
                    color: 'lightgrey',
                    width: 0.5,
                    value: 0,
                    dashStyle: 'LongDash',
                    label: {
                        text: '0',
                        align: 'right',
                        y: -1,
                        x: 0
                    }
                }]
            },
            plotOptions: {
                animation: false,
                series: {
                    animation: false
                },
                line: {
                    animation: false
                }
            },
            series: [{
                name: '',
                Data: [],
                tooltip: {
                    valueDecimals: 2
                },
                animation: false,
                lineColor: '#0033FF'
            }, {
                name: '',
                Data: [],
                tooltip: {
                    valueDecimals: 2
                },
                animation: false,
                lineColor: '#0033FF'
            }, {
                name: '',
                Data: [],
                tooltip: {
                    valueDecimals: 2
                },
                animation: false,
                lineColor: '#088A08'
            }]
        });
    });

{now filling some data here}

    var xaxis = new Date().getTime() + new Date().getTimezoneOffset();
    $('#my_chart').highcharts().series[0].addPoint([xaxis, (1500)], true, true);
    $('#my_chart').highcharts().series[1].addPoint([xaxis, (1300)], true, true);
    $('#my_chart').highcharts().series[2].addPoint([xaxis, (1100)], true, true);

--> Uncaught TypeError: Cannot read property 'series' of undefined

This will not happen when you replace the variable with the date generation itself:

    $('#my_chart').highcharts().series[0].addPoint([new Date().getTime() + new Date().getTimezoneOffset(), (1500)], true, true);
    $('#my_chart').highcharts().series[1].addPoint([new Date().getTime() + new Date().getTimezoneOffset(), (1300)], true, true);
    $('#my_chart').highcharts().series[2].addPoint([new Date().getTime() + new Date().getTimezoneOffset(), (1100)], true, true);

But this will force the graphs to have different start points.
The error will also not show up if you only have one graph inside the char or shift is set to false.

It looks like the error is thrown at highstock.src.js:16250 (latest version):

    if (data.length === points.length) {

points.length is null here.

**Comment by TorsteinHonsi** [comment]
I tried to replicate this at http://jsfiddle.net/highcharts/d7ow2sfz/, but I can't see the error. 

First of all, there are some errors in your configuration, but excessive settings doesn't matter. Just make sure that if you want to set data initially, the option is `data`, not `Data`. 

The behaviour, except for the error message, is as expected. When you add one point to an empty series and you have the shift setting `true`, the same point will be shifted out, leaving the series empty as before. As an analogy, if you have 10 points and add one point with shift, the oldest point will be removed. So you always end up with the same amount of points as you had, even when it is 0.

Closing this now, please reopen if you have new information.

**Comment by gizpiel** [comment]
I'd like to add some important things to know about this issue because G-Kevin is a workmate of mine and i know about the details.
We call addPoint in a loop and first with shift = false. If we reach a given amount of loops we switch shift to true. But it doesnt shift because an exception will be trown : Uncaught TypeError: Cannot read property 'length' of null  @highstock.js line 16250 where the points object is null. We have a second chart but with just one series and it shifts without this behavior.
Please let us know if you need more input to determine this behavior.

**Comment by TorsteinHonsi** [comment]
> Please let us know if you need more input to determine this behavior.

Yes, it would be great if you manage to modify http://jsfiddle.net/highcharts/bmv0gd1c/ so that it displays the error message. It uses exactly the code you pasted above.

**Comment by G-Kevin** [comment]
Hi,

I updated your fiddle with parts of our code:
http://jsfiddle.net/bmv0gd1c/1/

This behaviour does not appear when shifting after 10 or 100 passes, but does after 1000.

**Comment by TorsteinHonsi** [comment]
So you see the error message when the fiddle has run for minutes and the number of points exceed 1000?

**Comment by G-Kevin** [comment]
Yes, that's it.

**Comment by TorsteinHonsi** [comment]
I still haven't figured out what was the real reason for the issue, partly because I wasn't able to set up a test that worked without running 1000 iterations. So I put in a test the prevents the error, and it seems to work okay now.

**Comment by G-Kevin** [comment]
I haven't figured out the real reason as well, but this bug did not appear with small numbers of passes like 10 or 100.

Tested this with latest version and it works fine by now. Thank you for your commit! :+1:
