### ISSUE TITLE
Boxplot - null points cause incorrect legend behaviour

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4939]
Steps to reproduce: 
1. http://jsfiddle.net/jvufyfrf/
2. Click on the Series 2
3. As a result both series are hidden.

This is caused by null points inside array, when we have all values, legend works properly: 
http://jsfiddle.net/2gb8k75r/

**Comment by pawelfus** [comment]
*Internal note:*
I think [this checking](https://github.com/highcharts/highcharts/blob/282820805edb030e8035f8d406b8722ac1c00e24/js/parts/Series.js#L674) is wrong. There should be `defined(y[j])`. 

*Extra note:*
Why not using `defined(y) && (!yAxis.isLog || (y.length || y > 0))` also [here](https://github.com/highcharts/highcharts/blob/282820805edb030e8035f8d406b8722ac1c00e24/js/parts/Series.js#L665).

**Comment by TorsteinHonsi** [comment]
For the records, it is bad practice adding nulls to make the series start at a later X value. Instead, you should either

* Add X values: http://jsfiddle.net/highcharts/jvufyfrf/3/, or
* Add a `pointStart` setting: http://jsfiddle.net/highcharts/jvufyfrf/4/

**Comment by TorsteinHonsi** [comment]
@pawelfus I'm a bit concerned that using `defined` will have performance impacts, since this is an operation that is carried of several times for each point.

**Comment by pawelfus** [comment]
Of course, it will double the checks (comparison against `null` vs comparison against `null` and `undefined`). Maybe creating proper `yData` would be a way to go? Right now, when simple `null` is set as a point, then generated array (for boxplot) is `[null, undefined, undefined, undefined, undefined]`, while should be `[null, null, null, null, null]` (I think?). 

In that case, we need to improve logic [here](https://github.com/highcharts/highcharts/blob/282820805edb030e8035f8d406b8722ac1c00e24/js/parts/Point.js#L79).

Like this:

    each(pointArrayMap, function (key) {
        ret[key] = options;
    });

**Comment by TorsteinHonsi** [comment]
Ouch, another performance sensitive test that has wide effect... If we don't find a more boxplot specific solution I suggest we leave it for now, as there are good workarounds.

**Comment by wergeld** [comment]
I would also like to add that there is an issue if only one point is null valued in the array. In [this](http://jsfiddle.net/wergeld/hbzdjabq/) example notice that in data2 series the "high" point is null and the rest of that data element does not show. If you change the null point to the "low" value then it doesnt render the low point but it also does not render the high point.
