### ISSUE TITLE
Globals in modules/canvas-tools

### ISSUE THREAD

**Issue by felixfbecker** [highcharts/highcharts#4940]
In opposite to all other modules, [modules/canvas-tools](https://github.com/highcharts/highcharts/blob/master/lib/modules/canvas-tools.src.js) doesn't export anything and instead puts `RGBColor` and `canvg` in the global scope, then patches a global Highcharts object. Would it be possible to
 - make this "module" follow the other modules and export a function that takes Highcharts object
 - remove the RGBColor and canvg modules, and instead depend on them from their original repositories, either through NPM or Git submodules?
 - at least split RGBColor and canvg into seperate files or put them in a closure if you really need to bundle them, so the module actually only exports a module and does not export global variables

**Comment by felixfbecker** [comment]
Ok I found out that this is [lazy-loaded](http://api.highcharts.com/highcharts#global.canvasToolsURL) so I guess having CommonJS support for this is hard. It's just that [highcharts-export-clientside](https://github.com/A----/highcharts-export-clientside) depends on this directly

**Comment by TorsteinHonsi** [comment]
Yes, the canvas tools are lazy loaded, and only in case of Android 2.x, which is almost never the case anymore.

Are you aware that we have [built-in support for offline export](http://www.highcharts.com/docs/export-module/client-side-export)? If so, is there any specific feature that you are missing from our own module that you find in the [highcharts-export-clientside](https://github.com/A----/highcharts-export-clientside) package?

**Comment by felixfbecker** [comment]
@TorsteinHonsi Thanks for your response. I was not aware of this - just wasted a huge amount of time trying to improve that module.

**Comment by TorsteinHonsi** [comment]
> I was not aware of this - just wasted a huge amount of time trying to improve that module.

That's too bad. I just filed an issue on their site and asked them kindly to inform that this functionality is now natively supported in Highcharts. Feel free to upvote it.
