### ISSUE TITLE
Unable to change border color of a data point in mapbubble

### ISSUE THREAD

**Issue by fjsuarez** [highcharts/highcharts#4941]
I'm setting the color of a data point in a series to a different color, and while the fill color does change, the border color (or stroke) on hover does not. It reverts back to the color of the series.

See the following codepen:
http://codepen.io/fjsuarez/pen/xZpgOW

I've searched the API documentation and I don't think there is an option for this.

I even tried using `series.states.hover.borderColor` to change the border color of the entire series on hover to no effect.

**Comment by TorsteinHonsi** [comment]
The appropriate settings are in the `marker` config object. It seems to be missing from the Highmaps API, but you'll find it documented in [Highcharts bubble](http://api.highcharts.com/highcharts#plotOptions.bubble.marker). [View Codepen](http://codepen.io/anon/pen/yeppBv?editors=001)

**Comment by fjsuarez** [comment]
Thanks for the answer! I wouldn't have guessed it is actually the marker for that graph. My followup question is if you can change this for an individual data point.

**Comment by KacperMadej** [comment]
For general tech support, please see www.highcharts.com/support.

Yes, color and marker setting can be applied per data point - [demo](http://codepen.io/anon/pen/VeyXrg?editors=001)

**Comment by fjsuarez** [comment]
Sorry for using the wrong channel. I didn't think it was support since it was not documented. Thanks again!

**Comment by KacperMadej** [comment]
Docs are not yet fixed, so I guess the issue should stay open.

**Comment by kyleleeli** [comment]
how about the column type chart? no effect by setting data's marker property.

**Comment by TorsteinHonsi** [comment]
Columns don't have a marker property collection: http://api.highcharts.com/highcharts/series%3Ccolumn%3E.data

**Comment by pawelfus** [comment]
Markers are defined now in Mapbubble series too: https://api.highcharts.com/highmaps/series.mapbubble.marker
