### ISSUE TITLE
chart.pointer.normalize() doenst consider div left offset.

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4943]
Seems that chart.pointer.normalize() miss the div offset.
Example: http://jsfiddle.net/q05mc3qs/1/

**Workaround**: use offset() to extract "left" distance and add to pageX.
Example: http://jsfiddle.net/03wehnex/

**Comment by TorsteinHonsi** [comment]
Actually it's not a problem with `normalize()` , it is just that when the charts are side by side, we need to get the chart coordinates from the chart we are actually hovering. See http://jsfiddle.net/highcharts/q05mc3qs/2/.

**Comment by sebastianbochan** [comment]
I agree, but what points me to report was the chartPosition variable and I thought that it should also consider div position.

**Comment by TorsteinHonsi** [comment]
Yes it does, but in the sample it didn't look on the chart you were hovering, it just looks for each chart in general.

**Comment by sebastianbochan** [comment]
Ok thanks.
