### ISSUE TITLE
afterSetExtremes event fires after chart load

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#4944]
When chart has two series, if second series has smaller min or bigger max than first series, afterSetExtremes event is fired on chart load. 

example:
http://jsfiddle.net/p9wjssxt/7/

Problem occurs from 6ec3abf

**Comment by nicolascine** [comment]
+1

**Comment by goodmorninggoaway** [comment]
Also seeing this issue.

**Comment by KacperMadej** [comment]
Fixed since 4.2.5 and currently is working fine.
Demo: http://jsfiddle.net/p9wjssxt/11/
