### ISSUE TITLE
Solid gauge value not recentering on font size change 

### ISSUE THREAD

**Issue by mconner** [highcharts/highcharts#4945]
I'm trying to get get a solid gauge with a value that scales, based on the font size of the container, as described in https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/2258241-implement-dynamic-font-size.
However, when the font size is changed, the gauge value is not re-centered until a new value is set.
Here's a jsFiddle:  http://jsfiddle.net/te9gz3y6/3/
I've tried updating with a fake value, which works renders correctly, and then restoring it to the real value, which reverts back to where it was. (I'm guessing the size is being cached for the value, and is incorrect when the container size changes.)

Update:  Looking at getBBox in highcharts.src.js, it looks like the cache key for the value is:
 "439 898,0,3em,"   

 // Properties that affect bounding box
                cacheKey = ['', rotation || 0, styles && styles.fontSize, element.style.width].join(',');

So it uses the fontSize, but it is set to 3em, and the actual size will vary, depending on the font-size of the container.  Not sure how to fix that.

**Comment by TorsteinHonsi** [comment]
I tried running it without a cache, but even then it doesn't seem that the data label is redrawn.

One workaround would be to re-initiate the chart: http://jsfiddle.net/highcharts/te9gz3y6/4/

**Comment by SvenJunga** [comment]
+1

The proposed workaround is not applicable for me because I'm using the highcharts export server.

**Comment by TorsteinHonsi** [comment]
Another workaround is to mark the series dirty and clear the cache:
```js
	chart.series[0].isDirty = true;
        chart.renderer.cache = {};
        chart.renderer.cacheKeys.length = 0;
```
[View it live](http://jsfiddle.net/highcharts/te9gz3y6/6/).
