### ISSUE TITLE
Mobile scrolling

### ISSUE THREAD

**Issue by aderito7** [highcharts/highcharts#4947]
I am having trouble with a line chart not scrolling left or right on Chrome's emulators and Android/iOS devices. It works just fine when in Chrome browser. There is no real error being logged to the console and when inspecting element on iOS I see the chart is getting translated, so maybe it is just not updating.

**Comment by TorsteinHonsi** [comment]
Live demo please?

**Comment by aderito7** [comment]
I will try and reproduce it for you. The code base is large, I hope i solve the issue in the process. What I do suspect is that is interference from fast click or angular touch, but Ibwill get right to it. It really perplexes me

**Comment by aderito7** [comment]
After playing around we finally got the chart to work by removing animations. Still can't reproduce the error by only extracting relevant parts of the app because it is part of a huge code base.

**Comment by aderito7** [comment]
After playing around we finally got the chart to work by removing animations. Still can't reproduce the error by only extracting relevant parts of the app because it is part of a huge code base.
