### ISSUE TITLE
Float Bars

### ISSUE THREAD

**Issue by viandanteoscuro** [highcharts/highcharts#4949]
Hi,

I need to make a graph like this:

![floatbars014](https://cloud.githubusercontent.com/assets/4235079/12506798/b75c28fc-c0f1-11e5-8013-6904bd1f8366.png)

It's possible? How?

Thanks

Massimo

**Comment by zhy1stgg** [comment]
there are two demos may can help you

* http://www.highcharts.com/demo/columnrange
* http://www.highcharts.com/demo/column-placement

**Comment by sebastianbochan** [comment]
For general support questions please contact with us by emai / forum / stackoverflow. Further information here: http://www.highcharts.com/support
