### ISSUE TITLE
Incorrect stacked bars

### ISSUE THREAD

**Issue by JMens1** [highcharts/highcharts#4950]
In the jsfiddle example below  you see three stacklabels that overflow the stacked bar. 

Changing the setting reversedStacks to 'true' fixes the problem: The labels still are rendered at the exact same position; however the stacked bar is reduced in size which results in a neat layout.

It seems me incorrect that the size of the stacked bar changes when only reversing the stack order. 

http://jsfiddle.net/wewu0os9/7/

**Comment by TorsteinHonsi** [comment]
I agree that the placement of the stack labels shouldn't be affected by whether the stack is reversed or not.

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng Entry point: https://github.com/highcharts/highcharts/blob/master/js/parts/StackItem.js#L79-L111

**Comment by oysteinmoseng** [comment]
This is actually a duplicate of #1776, since the issue is with the use of `minPointLength`. We recommend to minimize the setting of `minPointLength` as a workaround, or look into the other solutions posted on that issue.
