### ISSUE TITLE
bug build x axis using getTimezoneOffset

### ISSUE THREAD

**Issue by hugomrdias** [highcharts/highcharts#4951]
When building the x axis, getTimezoneOffset method is called with a strange timestamp, but when building datalabels or tooltips everything seems ok.

example for DST change in 'Europe/Lisbon':
http://jsbin.com/seralet/14/edit?js,console

problem:
x axis has day 25 twice and tooltips and datalabels show the correct datetime

**Comment by TorsteinHonsi** [comment]
What happens is that the tick for the 26th is actually placed one hour too early (24h after the last tick), so the date becomes wrong. You see that clearly from this screenshot. Also note that both the tick placement and the point placement is correct, the only problem is that we would expect the tick to be at midnight.

![skjermbilde 2016-01-25 kl 12 09 22](https://cloud.githubusercontent.com/assets/227836/12549277/80db9098-c35c-11e5-9ae7-30897a59cc09.png)

**Comment by VilmaRamos** [comment]
Now the result is as I was expecting but trying to achieve the same result using only the ```pointStart ``` and ```pointInterval``` properties didn't work. The following example illustrates the problem:  http://jsbin.com/tojakel/2/edit?html,js,output .
Is it possible to define the point intervals using an irregular time interval? Maybe something like: 

```
series: {
    pointStart: 1445641200000,
    pointInterval: 1,
    pointIntervalUnit: 'day'
}
```

**Comment by TorsteinHonsi** [comment]
Good point! The current defination of `pointIntervalUnit` only covers `month` and `year`, but in order to cover DST crossover it should also cover `day`.

**Comment by TorsteinHonsi** [comment]
Since it is unrelated to the axis label placement, I added an issue at #4958.

**Comment by pawelfus** [comment]
It's still a little buggy: http://jsfiddle.net/1mtv71bx/

On the xAxis we can see 6. Nov twice: once at 00:00 and later at 23:00. All next daily higherRanks are translated by 1h to the left.

**Comment by TorsteinHonsi** [comment]
_Internal note_
The problem lies in [these lines](https://github.com/highcharts/highcharts/blob/v5.0.0/js/parts/DateTimeAxis.js#L113-L117) that don't take into consideration that the axis can cross over DST even if the interval is smaller than days and weeks.
