### ISSUE TITLE
When initializing highchart-exports with buttons: false, destroying the chart results in error

### ISSUE THREAD

**Issue by TikiTDO** [highcharts/highcharts#4952]
I have a scenario where I dynamically display or remove a chart based on other parameters. In my use case I need export functionality, but do not make use of the provided context buttons. When I remove the chart it complains about an undefined reference in the exports destroy function.

This function assumes that exportSVGElements and exportDivElements exist, and are arrays, which is not true when buttons: false is configured. I have worked around these issues in my code by setting these values to empty arrays before destroying, but would like to see it fixed in the main project as well.

**Comment by pawelfus** [comment]
Works for me, take a look: http://jsfiddle.net/1tvncf1j/

Remember: to disable exporting, set `exporting.enabled` flag to `false`. Not `exporting: false`.

**Comment by TikiTDO** [comment]
That's not quite my use case. See this: http://jsfiddle.net/1tvncf1j/1/ and click Create Chart with the console open.

**Comment by pawelfus** [comment]
Still, it's misconfigured option: `buttons: false`. `buttons` is a container for buttons, don't set `false` there: http://jsfiddle.net/1tvncf1j/2/

**Comment by TikiTDO** [comment]
I had tried that option much earlier in the development cycle, but ran into some sort of problem elsewhere in the app. Unfortunately that was in early December a full dev cycle back, so I can't recall what it was. 

In any case, if this is just me using an options in a non-standard way I'll close this issue. If I ever hit on whatever it was that caused me to use it in the first place I'll report that.
