### ISSUE TITLE
sum in waterfall chart is not calculated correctly

### ISSUE THREAD

**Issue by iddofontijn** [highcharts/highcharts#4954]
See this [jsfiddle](http://jsfiddle.net/5rayxrew/1/).

Somehow 0.0000000000002 is added to the sum. I've also seen a case where this amount is extracted from the sum.

**Comment by pawelfus** [comment]
This is issue with floating point numbers in JS, for example run in the console:
 
     0.4 - 0.3

It will return:

    0.10000000000000003

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard We have an internal function called `correctFloat` for this purpose. Check out how we have used it in the past, then apply it for example on the waterfall sum. Check out intermediateSum also.
