### ISSUE TITLE
Export button behind Crosshairs in chart with no Title

### ISSUE THREAD

**Issue by sjoris** [highcharts/highcharts#4955]
When the chart has no title, the Export button is drawn IN the chart. But with the Crosshairs enabled, the Export button stops working and the hover function of the Crosshairs get priority, so exporting the chart will be impossible.

I tested this jsFiddle in Firefox 41, Chrome 47 and IE 11.

http://jsfiddle.net/bxjqp239/

**Comment by TorsteinHonsi** [comment]
Preliminary workaround: Move the button using DOM scripting: http://jsfiddle.net/highcharts/bxjqp239/1/
