### ISSUE TITLE
How can I render a dynamic number of charts?

### ISSUE THREAD

**Issue by Jozkee** [highcharts/highcharts#4956]
I was trying this:

JS:
```js

$scope.chartsArray = [];
for (var j = 0; j <= i; j++) { //i its the amount of charts to display
    document.getElementById("charts").innerHTML += '<div class="col-md-6" id="chart-' + j + '"></div>';
    var tmp = new Highcharts.Chart({
        series: [1,2,3,4],
        chart: { type: 'column', renderTo: 'chart-' + j },
    });
    $scope.chartsArray.push(tmp);
}
```

HTML:

    <div id="charts" class="col-md-12" >  </div>

But only the last chart rendered works fine. The other charts don't show the series and don't repond to events.
I'm on AngularJS and rendering them on a modal.

**Comment by pawelfus** [comment]
Hi Jozkee,

This is our bug tracker - regarding support questions, could you contact us via email, or post your issue on the forum? 

Thank you!
Paweł
