### ISSUE TITLE
500 Internal Server Error when exporting

### ISSUE THREAD

**Issue by ricardojlpinto** [highcharts/highcharts#4959]
Hi,

When exporting an chart with more than 1 series, the http://export.highcharts.com/ is generating an '500 Internal Server Error when exporting' .
You test it here: http://www.highcharts.com/demo/line-ajax and try exporting to JPEG / PNG / PDF or SVG.

Best,

![screen shot 2016-01-26 at 3 10 36 pm](https://cloud.githubusercontent.com/assets/7307560/12584361/0e97b316-c43f-11e5-845e-c51c79d5bde1.png)

**Comment by drag0** [comment]
I noticed that too. Probably their export server is down.

**Comment by zuoRambo** [comment]
Maybe the server was gone to Mars during that moment, ^_^ 
Now it's 👌.

**Comment by gvaartjes** [comment]
Thanks for reporting, the export server was suffering from heavy traffic. We have taken measures to prevent the server from going down. 

Gert Vaartjes

**Comment by Frank004** [comment]
im having this problem but with only one of my charts in production.
