### ISSUE TITLE
Flags are not being show near to the x axis with inverted chart

### ISSUE THREAD

**Issue by pghilardi** [highcharts/highcharts#4960]
Flags on x axis works for normal charts, but not for inverted charts. The flag is placed far from the x axis.

Example: http://jsfiddle.net/sH777/323/

**Comment by oysteinmoseng** [comment]
The reason this is not supported currently is that Flags series are a Highstock feature, and Highstock charts are never inverted. We see the issue, though, and obviously there are use cases for this in normal Highcharts as well.

It will technically require quite some work to make these flags function correctly on inverted charts, as the whole SVG group is being flipped and mirrored, leading not only to wrong positioning, but also mirrored text inside the flags.

**Comment by pghilardi** [comment]
I think that inverted charts should be better supported by Highstock. Exists a plan to proper support of inverted charts on Highstock? Actually I am using Highcharts with the inverted option enabled and importing highstock.js to enable data grouping.

We have a use case that has time on x axis and multiple y axis with one series by y axis.

**Comment by TorsteinHonsi** [comment]
I gave it another try and see that we can simply disable the invertion of the marker group by adding this override to the FlagSeries prototype:

```js
	/**
	 * Don't invert the flag marker group (#4960)
	 */
	invertGroups: noop,
```

And since flags already misbehave in inverted charts, we're not breaking anything. @oysteinmoseng now you should be able to fix this by just getting the coordinates right.
