### ISSUE TITLE
Flags tooltip appears in wrong position when using inverted chart

### ISSUE THREAD

**Issue by pghilardi** [highcharts/highcharts#4961]
The chart is inverted. The flag tooltip appears near to the y axis as if the chart isn't inverted.

Example: http://jsfiddle.net/sH777/325/

**Comment by pghilardi** [comment]
Workaround is to use the configuration 'followPointer' in the tooltip configuration.

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng Go in at [this line](https://github.com/highcharts/highcharts/blob/v4.2.1/js/parts/FlagsSeries.js#L227) and do something similar to the [column chart tooltip position](https://github.com/highcharts/highcharts/blob/v4.2.1/js/parts/ColumnSeries.js#L247-L250).
