### ISSUE TITLE
contributing guide?

### ISSUE THREAD

**Issue by benhalverson** [highcharts/highcharts#4962]
Do you have one? 
If not where are the easy issues that I can fix?
I'd like to contribute, but as someone new to OSS I'm not sure who is working on what.
I just started at financial tech company and we use highcharts so I figure it would be fun to help out when I can.

**Comment by TorsteinHonsi** [comment]
Thanks Ben!

> If not where are the easy issues that I can fix?

The easy ones are fixed immediately :) We don't have a contributing guide currently. As it is a commercial project, there are some legal issues with accepting pull requests. But we always appreciate feedback and ideas regarding fixing issues.
