### ISSUE TITLE
Missing plotband when range is small

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4964]
In case when we have i.e two plotbands, one of them is missing. 

Example: http://jsfiddle.net/a30rcj24/

_Internal note_
We can observe two different behaviours in HS / HC
1) In HC - there are two paths, but one of them has the same x values, so is "hidden". 
2) In HS - there is single path, but second is not printed

Maybe in that scenario we consider to print that plotband as 1px, instead of round to the same x / skip path?

**Comment by TorsteinHonsi** [comment]
> Maybe in that scenario we consider to print that plotband as 1px, instead of round to the same x / skip path?

Yes, I think we need to do that, since it doesn't have a stroke.

**Comment by bryan-ash** [comment]
I can confirm that 89d37b71efe fixes this issue.

Unfortunately the label for the plotBand is not rendered because `path.flat = path.toString() === toPath.toString()` is evaluated before the adjustment.

**Comment by bryan-ash** [comment]
@TorsteinHonsi I just realized this issue, and suggested patch, are from last February, not this year!

Are there any plans to move forward on this?
