### ISSUE TITLE
Replacing Highcharts Server

### ISSUE THREAD

**Issue by nfantone** [highcharts/highcharts#4965]
`README.md` states that:

> For NPM users, please note that this module replaces the previous Highcharts Server module.

But I fail to see how that works. [highcharts-server](https://github.com/frisb/highcharts-server) has a single `.render` method on its API that expects `chartOptions` and outputs a Base64 string. That's it.

How can I achieve that exact same behaviour, server-side, running on Node, using _this_ module?

**Comment by TorsteinHonsi** [comment]
You can't. What we meant is that the NPM module that previously was available from https://www.npmjs.com/package/highcharts, is now moved to https://www.npmjs.com/package/highcharts-server. So if that was what you were using, you should update your build scripts to use highcharts-server.

**Comment by nfantone** [comment]
This is rather confusing, @TorsteinHonsi. By doing something like this, you have broken all npm projects depending on the previous module - including the one I've been working on.

**Comment by TorsteinHonsi** [comment]
What happened was that a third party, non related company used the NPM package name "highcharts" for one of their projects, which is a server implementation to our product, Highcharts. So when we, the owner of the Highcharts product, wanted to publish Highcharts under the only logic name on NPM, we approached them and asked them to kindly step away, which they did.

This is common in the package manager world, and is a consequence of the open structure where everybody can start using any package name.

**Comment by nfantone** [comment]
> This is common in the package manager world

It's not, really. Packages don't just change names and get replaced by totally different projects over the night. You could have chosen any other name in the whole world for your `npm` publication (what about [highcharts-js](https://www.npmjs.com/package/highcharts-js)? That name is _not_ taken). If this were a recurrent thing, products and already working applications around the globe would just need to keep manual tracking of where their dependencies. I can picture lots of CI failed builds.

Didn't you people know that [every change breaks someones workflow](https://xkcd.com/1172/)?

**Comment by TorsteinHonsi** [comment]
I don't want to quarrel about this, but NPM on their disputes page has a typical scenario that accurately describes the situation we were in: 

> Joe writes a JavaScript module foo, which is not node-specific. Joe doesn't use node at all. Bob wants to use foo in node, so he wraps it in an npm module. Some time later, Joe starts using node, and wants to take over management of his program.

Furthermore, our users expected the NPM package called "highcharts" to point to the official library, not a third-party wrapper.

**Comment by nfantone** [comment]
Wanting to "take over management" does not imply "completely replace a module with some other that does not relate to the original". You didn't take over management, you swapped projects altogether. 

You are not Joe.

It's fine, really. I don't want to quarrel anymore either. Just wanted to state that what you did is _not_ common, is ill advised and imprudent. Also, *I am a highcharts user* and I didn't expect the npm module to point anywhere else.

Thanks for your patience.

**Comment by nfantone** [comment]
For everyone reaching this issue led by the warning for NPM users [in the README.md](https://github.com/highcharts/highcharts/blob/master/readme.md), I've published the PhantomJS implementation of the [highcharts-export-server](https://github.com/highcharts/highcharts-export-server) as a standalone, independenr NPM module:

https://github.com/highcharts/highcharts-export-server

**Comment by TorsteinHonsi** [comment]
Okay, thanks for contributing, and I'm sorry for the inconvenience.

**Comment by nfantone** [comment]
@TorsteinHonsi You are welcome.
