### ISSUE TITLE
why use the latest version ,but in android 4.0 mobile column tooltip can not shown

### ISSUE THREAD

**Issue by claire1028** [highcharts/highcharts#4966]
I set  followTouchMove:true，and  followPointer: true,  but not work

**Comment by oysteinmoseng** [comment]
As I understand you, the tooltip is not following the pointer on touch in Android 4.0? So this demo does not work? http://jsfiddle.net/74rae9hv

Which browser are you using? Default Android browser?

**Comment by sebastianbochan** [comment]
I was able to replicate that issue in native android browser (4.0.4). Indeed when Im moving finger over screen, toolitp is not refhreshed / moved as well. In the Mobiel Chrome all seems to working fine (andorid 4.0.4, 4.2.2, 5.1.1)
