### ISSUE TITLE
Highstock API typos and mistakes

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4968]
There are some mistakes in Highstock API:

1. [plotOptions.series.dataGrouping.enabled](http://api.highcharts.com/highstock#plotOptions.series.dataGrouping.enabled) - ***Defaults to true.*** twice.

2. [plotOptions.series.dataGrouping.forced](http://api.highcharts.com/highstock#plotOptions.series.dataGrouping.forced) - ***Defaults to false.*** twice.

3. [plotOptions.series.dataGrouping.groupPixelWidth](http://api.highcharts.com/highstock#plotOptions.series.dataGrouping.groupPixelWidth) - ***Defaults to 2.*** twice.

And this is everywhere where `dataGrouping` is in API.

**Comment by TorsteinHonsi** [comment]
Thanks, fixed.

**Comment by KacperMadej** [comment]
@TorsteinHonsi Thank you. 

Another issue:
Highstock API lacks [`getExtremesFromAll`](http://api.highcharts.com/highcharts#plotOptions.series.getExtremesFromAll) documentation.

**Comment by TorsteinHonsi** [comment]
Thanks, fixed.
