### ISSUE TITLE
formatter in highstock navigator does not work. 

### ISSUE THREAD

**Issue by sammiwei** [highcharts/highcharts#4972]
I am trying to display a non-date xAxis as the navigator's xAxis. I dont think I can use the formatter to get it working. It is set by default to ignore the formatter as it is only for date based stock chart?
This should be a feature request for the highchart to have the navigator but now navigator is only for stock. 
Here is my working in progress jsfiddle:
http://jsfiddle.net/6ovq7nbn/
let me know if you know a work around way.
Thanks.

**Comment by pawelfus** [comment]
The problem is where you set formatter. It should be:

    navigator: {
      xAxis: {
        labels: {
          formatter: function () { ... }
        }
      }
    }

(not in the styles object).

Demo: http://jsfiddle.net/ma50685a/3/

**Comment by pawelfus** [comment]
The problem is where you set formatter. It should be:

    navigator: {
      xAxis: {
        labels: {
          formatter: function () { ... }
        }
      }
    }

(not in the styles object).

Demo: http://jsfiddle.net/ma50685a/3/
