### ISSUE TITLE
Overlapping labels on yAxis

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#4973]
In this specific scenario: http://jsfiddle.net/dqkjrd7k/6/ - last two labels overlaps (`600` and `800`).

Most probably, calculation fails because of setting specific font family and font size.

**Comment by TorsteinHonsi** [comment]
It does have something to do with the fonts. In the [handleOverflow function](https://github.com/highcharts/highcharts/blob/v4.2.1/js/parts/Tick.js#L135-L140), the `labelWidth` reported is too low. If I disable the bounding box cache by commenting out [this line](https://github.com/highcharts/highcharts/blob/master/js/parts/SvgRenderer.js#L752), an ellpsis is added. But not the ellipsis is too big, which I guess is a different issue.
