### ISSUE TITLE
Line graph is not showing lines.

### ISSUE THREAD

**Issue by babukumarg** [highcharts/highcharts#4974]
Hi,

My line chart had four axes and close to 9000 points for each axis and the chart is not showing any lines. If I zoom in then I see the lines. Here is the [link to jsFiddle](http://jsfiddle.net/a6qpbfnj/) to reproduce the issue. I see this issue in Chrome and Firefox.

**Comment by pawelfus** [comment]
Hi,

You have a lot of points, so rendering 9000 of points on a small chart (e.g. 900pixels) in SVG is not the best idea (it's gonna kill the performance). Then how about using boost.js? Something like this: http://jsfiddle.net/a6qpbfnj/3/


*Internal note:*
Fails in [this line](https://github.com/highcharts/highcharts/blob/4eb0d312351356fa2af9a86df8f02f1d02b78a9e/js/parts/SvgRenderer.js#L1064). Maybe string is too long (218 600 characters), to properly parse?

**Comment by babukumarg** [comment]
Including boost.js solved my issue.

Thanks.
