### ISSUE TITLE
Unable to highlight with border when clicked on windrose column.

### ISSUE THREAD

**Issue by Ramkumar2411** [highcharts/highcharts#4975]
Code link: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/polar-wind-rose/

When user sets _plotOptions.series.allowPointSelect: 'true'_ property for Windrose widget, windrose column is displayed in gray color when user clicks on it. However, windrose column border is not highlighted as below: 
 
 ![windorse_withcode](https://cloud.githubusercontent.com/assets/14074230/12679121/65f3b62e-c6c8-11e5-8e98-4f40e7d4b8fd.png)

Here, green colored windrose column is grayed after clicking on it.

Expected Output: 
Windrose column color should not get changed and only border for that particular column should get highlighted.

**Comment by TorsteinHonsi** [comment]
Thanks for writing,

It's only a matter of changing the default options. When you click the point, the point state is set to `state.select` and takes the according option. See http://jsfiddle.net/highcharts/dh5pL5r8/.
