### ISSUE TITLE
connectNulls breaks flags

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4978]
As in the topic, connectNulls options hides flags.

Example: 
- http://jsfiddle.net/hqfpk571/

In the master branch (bug-fix as well), seems to be fixed, but in the console we have errors in path. 

Example:
- http://jsfiddle.net/dmu99ykk/

**Comment by TorsteinHonsi** [comment]
Since the issue in the header is resolved, this one simplifies the remaining issue of `connectNulls` with a series starting with `null`:  http://jsfiddle.net/dmu99ykk/1/
