### ISSUE TITLE
Stacking bar chart with negative value

### ISSUE THREAD

**Issue by natee** [highcharts/highcharts#4979]
eg: http://jsfiddle.net/ck9c4n8x/

Negative value looks to be wrong.
Column chart has the same problem.

**Comment by pawelfus** [comment]
Could you explain how should this be rendered? For example want two bars, both with value == 100%? 

I mean, percent stacking doesn't sound reasonable for negative values. Similar to negative values in the pie chart. That kind of charts display percentage of the whole value, with requirement that points/slices are all positives.

**Comment by TorsteinHonsi** [comment]
When we add another set of points, it renders like it is supposed to do: http://jsfiddle.net/ck9c4n8x/1/. The positive side is supposed to land at 60%, while the negative is supposed to land at -40%.

For some reason, with only one stack it fails.

**Comment by efletch** [comment]
I've also encountered this issue. Only happens with one set of points. Two or more sets of points and everything works as expected. One the one set version the negative value appears to be the value and not the percent.

One series: http://jsfiddle.net/trrbn84h/1/
Two series: http://jsfiddle.net/qa3ae6gp/

**Comment by pawelfus** [comment]
*Internal note:*
Responsible commit: 8d8cbee

**Comment by efletch** [comment]
@pawelfus awesome! Thank you for the quick fix! When will this be available in a release version? We are currently running on 4.2.5 but would love to update and get this fix 😄

**Comment by efletch** [comment]
Any idea on when this will be included in a release version of highcharts? I updated to 5.0.0 which looks great but unfortunately did not resolve the issue. It looks like you've committed the fix on the /hc4 branch. Are there plans to merge this with master and apply the fix to 5.0.0?

**Comment by TorsteinHonsi** [comment]
Hi, yes the fix is merged into Highcharts 5, and will be available in v5.0.1, shipping this week probably.

**Comment by efletch** [comment]
Great thanks!

**Comment by efletch** [comment]
Updated to 5.0.2 and the fix is working beautifully! Thanks!
