### ISSUE TITLE
Highmaps: series dashStyle property didn't work on IE

### ISSUE THREAD

**Issue by PohlodSlavik** [highcharts/highcharts#4981]
Map borders always 'solid' in IE regardless of corresponding value of series dashStyle propery.
This example will have dashed borders on Chrome/Firefox etc. and solid borders in IE(I have reproduced this using IE11). 
http://jsfiddle.net/zqh4jyff/

**Comment by oysteinmoseng** [comment]
Issue is that stroke-width is set to "inherit" in IE in order to not scale when map is zoomed, but that fails for computing dash strokes on this line: https://github.com/highcharts/highcharts/blob/master/js/parts/SvgRenderer.js#L1086

**Comment by PohlodSlavik** [comment]
Could you please tell what is the status of this issue?

**Comment by TorsteinHonsi** [comment]
@PohlodSlavik Sorry for the delay!

@oysteinmoseng or @PohlodSlavik: The license on my Windows machine expired, so I only tested the fix on Chrome with emulated vectorEffect un-support. Can you verify that this now works on Windows IE? Use [this fiddle](http://jsfiddle.net/highcharts/zqh4jyff/4/) to test.

**Comment by PohlodSlavik** [comment]
@TorsteinHonsi Now it looks better, but when I'm trying to scale map in IE - dashes scales also.
Here is a screenshot how it looks in IE and Chrome: http://screencast.com/t/FuFHsIau
Looks like IE doesn't support `vector-effect="non-scaling-stroke"`
Can this be fixed somehow?

**Comment by TorsteinHonsi** [comment]
> Looks like IE doesn't support vector-effect="non-scaling-stroke"

That's correct, it's why it went wrong in the first place. I think we
should leave it like this - the alternative is to add the stroke width to
every area, but it will cause a performance drop on zooming.

**Comment by PohlodSlavik** [comment]
Maybe we could somehow catch when scale is changed and adjust `stroke-dasharray`(only in IE)? 
For example if map scale is 2 - set `stroke-dasharray="2,1.5"` instead of `stroke-dasharray="4,3" `.
I'm not sure that is the good idea but it might works.
