### ISSUE TITLE
I wonder if there's a way to show differences in line the charts in case of big numbers.

### ISSUE THREAD

**Issue by Karlen92** [highcharts/highcharts#4983]
For example , in the line chart with y values 5555557,55555578 , 55555579,...., the point is,  that they are very close  to each other , and highchart shows my line as constant line, but i need to show that small changes, how can do that ?
Thanks in advance.

**Comment by pawelfus** [comment]
Hello Karlen,

For support questions, please contact with us using e-mail, or post your question on our forum. See more details [here](http://www.highcharts.com/support).
