### ISSUE TITLE
Tooltip is jiggling on arearange when followPointer is set to true

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#4984]
Tooltip is jiggling on arearange after followPointer is set to true. Example of this behaviour:
http://jsfiddle.net/2a67qog8/4/

![animation](https://cloud.githubusercontent.com/assets/15050812/12722264/62fb6474-c904-11e5-9c32-b954f31d81c0.gif)

It looks to be connected with value of arearange, when min is bigger than 0 everything works fine, probably connected with standard behaviour for tooltip at arearange:
http://jsfiddle.net/2a67qog8/5/

Edit: Highcharts have the same problem as Highstock with this behaviour:
http://jsfiddle.net/2a67qog8/6/

As a workaround it is possible to use tooltip.positioner for placing tooltip.
example: http://jsfiddle.net/2a67qog8/8/

**Comment by TorsteinHonsi** [comment]
_Internal note:_

When the tooltip is shared, it is supposed to follow the mouse's y position.

**Comment by jon-a-nygaard** [comment]
It appears to be with the preferFarSide logic in `Tooltip.getPosition()`
```javascript
preferFarSide = pick(point.ttBelow, (chart.inverted && !point.negative) || (!chart.inverted && point.negative))
```
The jiggling happens in this case when point.negative is true. Which seems to be the correct logic and behaviour. So not sure if this is a "bug" anymore.

Also to note, I believe a potential simplification of this logic could be:
```javascript
preferFarSide = pick(point.ttBelow, !chart.inverted === !!point.negative);
```

**Comment by pawelfus** [comment]
Since we have `followPointer` set to true, then `preferFarSide` shouldn't be used at all?

**Comment by jon-a-nygaard** [comment]
@pawelfus: I am thinking the same, when I set preferFarSide explicitly to false then it is behaving how I expected it.

**Comment by TorsteinHonsi** [comment]
This just in: The issue can also be seen on vanilla line charts, briefly when hovering over the negative point: http://jsfiddle.net/highcharts/zv5nc6xd/
