### ISSUE TITLE
Multiple YAxis scale margin not added: Single Point and series type : Line

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#4986]
Check below url :
http://jsfiddle.net/pawanvjadhav/yutdjcva/

I feel, highchart should add extra point  as margin for Temperature axis.
When there is single point and if you have Line series, highchart draws only one point. But i think, this behavior is not good when you have two axes.

**Comment by pawelfus** [comment]
Well, this is general problem - what scale should be used on yAxis with just one point, which is not column type (or rather, doesn't have `threshold` option). 

Anyway, you can achieve such result by setting `yAxis.minRange`, which will try to render point in the middle of the graph: http://jsfiddle.net/yutdjcva/1/

**Comment by pawanvjadhav** [comment]
You are right...But we can't control data...if data has single point and user has selected Line/Scatter to show , we have to render it.  In this case, it shouldn't render point on X Axis, its not readable. It should add margin.

minRange : yes this is one of the option, which we have tested.
But I want to use auto scale calculation behavior of highchart, if i set minRange and if data get changed in feature then again i have to recalculate and reset it..for end user this is not a good option

**Comment by pawelfus** [comment]
How about calculating possible `minRange` when rendering chart? For example: http://jsfiddle.net/yutdjcva/3/ - so `minRange` will be set only when you have specific series type (`line`, `spline`, `scatter` ?) and only one point. In all other cases nothing will be changed.

**Comment by pawanvjadhav** [comment]
@pawelfus Ok..Not sure, this needs to be tested for multiple series on a Yaxis.

I feel, This needs to be fixed in highchart lib.

**Comment by pawelfus** [comment]
It's just my personal opinion, but this is one of cases, when one can call it `bug` and another one will say that current solution is correct one. There was exactly the same situation, just with one yAxis instead of multiple of them. That's why I am trying to find some workaround for this issue.

**Comment by pawanvjadhav** [comment]
For one yaxis, i think, highchart behavior is right.

**Comment by pawanvjadhav** [comment]
Have you resolved this issue?

**Comment by TorsteinHonsi** [comment]
No, we haven't decided it's a bug either. Perhaps the right way to go about it would be to add an option for it.
