### ISSUE TITLE
Date on y-axis: Chart height issue

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#4987]
Hi,

I have a date-time series plotted on y-axis.
Chart with height 358px: http://jsfiddle.net/tejaspchordiya/6oz3075d/52/

When I decrease height of chart, the lower bound of y-axis changes and bars are not scaled properly.
Chart with height 357px: http://jsfiddle.net/tejaspchordiya/6oz3075d/51/

Expected result: Even though the chart height is decreased, lower bound of y-axis should be unchanged.

**Comment by pawanvjadhav** [comment]
Highchart shouldn't space between bar and axis.

**Comment by pawelfus** [comment]
Should I use specific browser, or do I miss something? Screenshots:
![screen shot 2016-02-02 at 13 14 46](https://cloud.githubusercontent.com/assets/1453926/12749151/0cd14bee-c9af-11e5-8606-21e3b97d1c16.png)
![screen shot 2016-02-02 at 13 14 53](https://cloud.githubusercontent.com/assets/1453926/12749152/0cd5a02c-c9af-11e5-926d-adf79c0cf1bc.png)

**Comment by tejaspchordiya** [comment]
I am using Chrome. I don't think this is browser specific issue.

This issue can be reproduced by decreasing height of the chart. Try to play with the chart's height.

Chart with height 357px: http://jsfiddle.net/tejaspchordiya/6oz3075d/51/
In this fiddle, use interactive legend, the chart is rendered properly second time, that is, space between bar and axis is removed.

**Comment by tejaspchordiya** [comment]
By mistakenly, closed the issue, thus, is reopening the same.

**Comment by pawelfus** [comment]
My screenshots are from Chrome (357px vs 358px) - I don't see any gap between columns and axis? Tried other sizes (355, 356, 359), but I don't think checking pixel by pixels is a way to reproduce issue. Maybe try to set fixed width (if that changes anything).

**Comment by historicbruno** [comment]
Strange, in Firefox 43 both charts have that gap, while in Chrome 48 (Windows) and IE 11 only the second chart has the gap.

**Comment by pawanvjadhav** [comment]
We could reproduce it easily,
Our configuration:
Chrome : 47.0.2526.111 m
Windows 7 Profession 64bit

**Comment by TorsteinHonsi** [comment]
I was able to replicate it on the Mac with height 340 pixels

![skjermbilde 2016-02-03 kl 09 13 15](https://cloud.githubusercontent.com/assets/227836/12776455/624d139e-ca56-11e5-9224-b9228b2c4058.png)

What happens is that the columns start at the default threshold, which is 0. On a datetime axis that translates to January 1st, 1970. And per the default Y axis setting for [startOnTick](http://api.highcharts.com#yAxis.startOnTick), the Y axis adds padding. This fix is to set `startOnTick` to false. http://jsfiddle.net/6oz3075d/54/.

**Comment by pawelfus** [comment]
Oh, I see it now! 

Another solution may be to set `series.threshold`  to null, for example: http://jsfiddle.net/6oz3075d/55/ - it looks even better, because we can distinct different values between columns. Unless, we want to yAxis in 1970.
