### ISSUE TITLE
Highstock ignores navigation,scrollbar and rangeSelector in Highcharts.setOptions() 

### ISSUE THREAD

**Issue by c0n3j0** [highcharts/highcharts#4988]
Example fiddles:

http://jsfiddle.net/7dpxmgeb/

**Comment by pawelfus** [comment]
Thank you for reporting this issue!

*Internal note:*
We are forcing that options in the constructor [here](https://github.com/highcharts/highcharts/blob/16bcfc9a918b8c485d92bc7194bb5dc04718357d/js/parts/StockChart.js#L71)

Maybe we should use different variable for storing default options for Highstock (and Highmaps)?
