### ISSUE TITLE
getSVG function produces invalid SVG

### ISSUE THREAD

**Issue by TomasZorvan** [highcharts/highcharts#4989]
I need to get SVG of my highchart but the final SVG is not valid according to W3C validator. Im validating it against SVG 1.1 standard. Hovever there is just one error: 
**there is no attribute "strokeWidth"
… width="825" height="625" strokeWidth="0" fill="#FFFFFF" class=" highcharts-ba…**

But I use this SVG in another plugin which accepts only valid SVG.

Is there some standard option to make this SVG valid? I can do it using say XSLT but it's unnecessary overhead for the application.

Thanks for any help.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, it's a bug, it should be filtered out or never set on the element in the first place. 

Until we release a fix, you can work around it with this snippet:
```js
Highcharts.wrap(Highcharts.Chart.prototype, 'sanitizeSVG', function (proceed, svg) {
    svg = proceed.call(this, svg);
    return svg.replace(/strokeWidth="[^"]+"/g, '')
});
```

[View it live on jsFiddle](http://jsfiddle.net/u0w588yf/).

**Comment by TomasZorvan** [comment]
Thanks a lot, very helpful.
