### ISSUE TITLE
Missing API reference in the zip file (Highcharts 4.2.1)

### ISSUE THREAD

**Issue by mekhatria** [highcharts/highcharts#4991]
Zip file (Highcharts 4.2.1)  doesn't include API reference.
BTW it works on Highstock-4.2.1 and Highmaps-4.2.1

**Comment by gvaartjes** [comment]
We updated the build routines

**Comment by gvaartjes** [comment]
New maintenance release is to be released within days. This will contain the offline api in the zip file
