### ISSUE TITLE
LegendItemClick event object different in 4.2.1 and 4.1.8

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4996]
Lets run the example: http://jsfiddle.net/dt6x0xjy/10/ with HC 4.1.8 and 4.2.1. It looks like some objects are missing in the newest branch.

**Comment by TorsteinHonsi** [comment]
Yes, Highcharts 4.1 ran events through jQuery, while Highcharts 4.2 runs without a framework, equivalent to running the Standalone Framework in 4.1. So what you see in 4.1 is a jQuery event.

If there are specific event properties that may be useful, please add comments, and we'll consider including them.
