### ISSUE TITLE
Series Shadow (highcharts 4.2.2)

### ISSUE THREAD

**Issue by FenixGit** [highcharts/highcharts#4999]
Hello,

Please, verify the shadow properties of the series. 

http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/plotoptions/series-shadow/

It is generating error: "Uncaught TypeError: Cannot read property 'setAttribute' of undefined" when moving the mouse over the chart.

Thanks

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

It's a regression, it fails since 267eaad.
