### ISSUE TITLE
Rotation: -90  of DataLabels is not showing the label (highcharts 4.2.2)

### ISSUE THREAD

**Issue by FenixGit** [highcharts/highcharts#5000]
Hi,

The label is not showing when rotation: -95 and the column is smaller than the label. In the previous version  shows.

The version of https://cloud.highcharts.com/charts it works.

Add the rotation: -90 in the demo below:
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/column-drilldown/

Thanks

**Comment by TorsteinHonsi** [comment]
After fixing #4779, Highcharts now hides rotated data labels if they render outside the plot area.

With v4.2.1, rotating the labels caused them to overflow: http://jsfiddle.net/highcharts/d6nmu55g/.

With v4.2.2, you have (at least) two options:
* Set the `crop` option to `false`: http://jsfiddle.net/highcharts/d6nmu55g/1/
* Set the `align` option to `left`: http://jsfiddle.net/highcharts/d6nmu55g/2/. This results in the top label to be hidden though, so you may want to set `yAxis.maxPadding` higher as well.

**Comment by FenixGit** [comment]
Thank you
