### ISSUE TITLE
highcharts.js v4.2.2 'mouseIsDown' undefined 

### ISSUE THREAD

**Issue by LithMage** [highcharts/highcharts#5003]
Hi,

as of 4.2.2 highcharts.js throws

> Uncaught TypeError: Cannot read property 'mouseIsDown' of undefined

if the chart is reloaded.

**Comment by sebastianbochan** [comment]
Demo: http://jsfiddle.net/kz03adpt/

**Comment by pawelfus** [comment]
Fixed on master: http://jsfiddle.net/kz03adpt/1/

**Comment by TorsteinHonsi** [comment]
Duplicate of #4998
