### ISSUE TITLE
Tooltip javascript error on 4.2.2 release

### ISSUE THREAD

**Issue by xavadu** [highcharts/highcharts#5007]
Hello,

Sorry i don't have the time to reproduce the error at this moment later a lot of lost hours looking for a strange issue that started for nowhere.. 

I realize that it was because the version upgrade from 4.2.1 to 4.2.2 which was launched yesterday.

All works fine but when i go with the mouse to a data point in an area chart (i didn't test on oter kind of chart) i have this error on the console: _Uncaught_ TypeError: Cannot set property 'd' of null_ (the error is copy from the Chrome console but the issue is also in other browsers).

The problem is on that function:
```
        dSetter: function (value, key, element) {
            if (value && value.join) { // join path
                value = value.join(' ');
            }
            if (/(NaN| {2}|^$)/.test(value)) {
                value = 'M 0 0';
            }
            element.setAttribute(key, value);

            this[key] = value; // <--- here
        },

```

What i can see is that later some iteration and maybe no the last iteration, the error is throw. The iteration start to happen when the user enter to the graph and the crosshair select a data point and the tooltip should be displayed.

I am using highstock without any custom configuration for the pluggin.
If i can help in some other way, i will have more time on the weekend, just let it written. 

Cheers.

**Comment by TorsteinHonsi** [comment]
I'm afraid I can't help you without a live reproduction, please start out with [this fiddle](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/intraday-area/) and see if you can change it into something that breaks.

**Comment by orestisioakeimidis** [comment]
Hi,

I am also getting an error after 4.2.2 regarding the tooltip. The error is the following:

Uncaught TypeError: Cannot read property 'mouseIsDown' of undefined
    ab.onContainerMouseMove @ highstock.js:185
    b.onmousemove @ highstock.js:187

It happens if I hover over an empty graph first and then in every other graph.

**Comment by pawelfus** [comment]
Could you try our master branch? It should be already fixed: `http://github.highcharts.com/highcharts.src.js`

**Comment by xavadu** [comment]
I can't reproduce it in jsfile, it works fine with own mock data inclusive. Maybe it is a conflict with one of the following frontend libraries we are using:

```
    "angular": "~1.4.4",
    "angular-animate": "~1.4.4",
    "angular-bootstrap": "~0.13.3",
    "angular-i18n": "~1.4.4",
    "angular-resource": "~1.4.4",
    "angular-responsive": "xavadu/angular-responsive",
    "angular-sanitize": "~1.4.4",
    "angular-touch": "~1.4.4",
    "animate.css": "~3.4.0",
    "bootstrap": "~3.3.1",
    "jquery.cookie": "~1.4.1",
    "ladda": "~0.9.2",
    "material-design-preloader": "~1.1.1",
    "zeroclipboard": "~2.2.0",
```

I still have the issue with master:

(gif) http://i.imgur.com/rEmy0LL.gifv

**Comment by pawelfus** [comment]
Could you attach full stack error with using **non-minified** version of Highstock? I ask for a full info, because `dSetter` function is called by different objects, so it is not enough to replicate and debug.  

Thanks!

**Comment by danielkman** [comment]
+1

**Comment by xavadu** [comment]
Hi, sorry for the delay to answer 

I was trying to isolate highstock to sent you the full stack error when i found the issue. The problem happen when you set _"use strict";_ mode. 

For 4.2.1 it works good, but for 4.2.2 and 4.2.3 this error happen:

```
Uncaught TypeError: Cannot set property 'd' of null
SVGElement.dSetter @ highstock.src.js:3138
SVGElement.updateShadows @ highstock.src.js:2407
SVGElement.attr @ highstock.src.js:2373
SVGElement.symbolAttr @ highstock.src.js:2453
SVGElement.attr @ highstock.src.js:2357
updateBoxSize @ highstock.src.js:4527
wrapper.textSetter @ highstock.src.js:4640
SVGElement.attr @ highstock.src.js:2369
Tooltip.refresh @ highstock.src.js:9825
Pointer.runPointActions @ highstock.src.js:10170
Pointer.onContainerMouseMove @ highstock.src.js:10564
container.onmousemove @ highstock.src.js:10651
```

**Comment by TorsteinHonsi** [comment]
Can you reproduce it live?

> The problem happen when you set "use strict"; mode.

Where is that? Are you enclosing the Highcharts code in a string function?

**Comment by xavadu** [comment]
We use _grunt_ as javascript task runner and we concat all the libraries and our own source code in one file, which after is minify too. 

To have a good quality code and trying to avoid possible bug, we set javascript to use _strict mode_, it force to the developer to use good practice on coding.. 

To do it, one line is added at the begining of the source: 

```
"use strict";
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
https://stackoverflow.com/questions/1335851/what-does-use-strict-do-in-javascript-and-what-is-the-reasoning-behind-it

**Comment by TorsteinHonsi** [comment]
Got it! Reproduction for developers: 

1. In the local Highcharts project, at the top of Globals.js, add `'use strict'`.
2. Open http://jsfiddle.net/3srde55r/, that loads Highstock from the local project.
3. Hover one of the columns.

**Comment by xavadu** [comment]
great, thanks
