### ISSUE TITLE
[highstock]Navigator draw function fails on gaps

### ISSUE THREAD

**Issue by corby** [highcharts/highcharts#5008]
highstock.src.js: Line 20065

The index is going out of bounds.  Note that you are starting on the last array element and immediately trying to get the point element after the last array element.

Stack:
Uncaught TypeError: Cannot read property 'x' of undefined
Series.gappedPath @ highstock.src.js:20065
Series.drawGraph @ highstock.src.js:14906
Series.render @ highstock.src.js:15188
(anonymous function) @ highstock.src.js:24317obj.
(anonymous function) @ highstock.src.js:670
Series.redraw @ highstock.src.js:15270
(anonymous function) @ highstock.src.js:12126
each @ highstock.src.js:1158
Chart.redraw @ highstock.src.js:12123
Chart.setSize @ highstock.src.js:12662
<<my function>>

Code:
```js
        if (gapSize) {

            // extension for ordinal breaks
            i = points.length - 1;
            while (i--) {
                if (points[i + 1].x - points[i].x > xAxis.closestPointRange * gapSize) {
                    points.splice( // insert after this one
                        i + 1,
                        0,
                        { isNull: true }
                    );
                }
            }
        }
```

**Comment by corby** [comment]
NOTE: rolling back to 4.2.1 solved the problem

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, but I was not able to test this. I threw in a test anyway, making sure that the while loop doesn't run if the points length is 0. It would be appreciated if you can  alter http://jsfiddle.net/highcharts/2saxhar4/ to demonstrate the issue.
