### ISSUE TITLE
Highmaps: zooming by mouse wheel doesn't works correctly since v4.2.0

### ISSUE THREAD

**Issue by PohlodSlavik** [highcharts/highcharts#5011]
In case when page with chart(map) contains scrollbars, zooming map by scrolling triggers not only map zooming but page scrolling too.
For example: http://jsfiddle.net/91dhg2bp/  
or even here: http://www.highcharts.com/maps/demo/all-maps
This issue reproduces in all browsers.
Also I have noticed that it worked well till v4.2.0.

**Comment by TorsteinHonsi** [comment]
Initial thoughts: In Highcharts 4.2, the jQuery adapter was removed ant replaced by the Standalone Framework. It may be that the same issue happened previous to 4.2, but only with the Standalone Framework. Event handling and box size detection changed.

**Comment by Dams591** [comment]
Hi Guys,
I see this was fixed in April 12, however we are still facing the issue running highcharts (and highmaps) v4.2.5.
Anything I should do to make it work ? 
Thank you.

**Comment by oysteinmoseng** [comment]
@Dams591: The fix has not yet been merged into the master branch, but if you load Highmaps from the bugfix branch on GitHub you should see it work (`http://github.highcharts.com/bugfix/highmaps.js`).
