### ISSUE TITLE
Highmaps: setData does not consistently change the data

### ISSUE THREAD

**Issue by OmarShehata** [highcharts/highcharts#5012]
Running: 

`$('#container').highcharts().series[0].setData(data);`

Multiple times (with different data sets) does not seem to work. It seems to get stuck after switching once. 
[jsFiddle](http://jsfiddle.net/omarshe7ta/m93r6dsr/40/)

- The buttons at the top switch between two data sets (positive and negative)
- You can switch once, but then it seems to get stuck
- Clearing the data always seems to work (by setting it to an empty data set)

**Comment by pawelfus** [comment]
It is issue with using the same reference. Highmaps will modify the reference values, when calling `setData()`. Instead you can use copy of your data array, for example using `$.extend(true, [], data)`. 

Working demo: http://jsfiddle.net/m93r6dsr/41/

**Comment by OmarShehata** [comment]
Ooh, I see! It's also mentioned in the documentation for setData. My bad! Thank you for the insight!
