### ISSUE TITLE
HighChart price line disappears

### ISSUE THREAD

**Issue by leongaban** [highcharts/highcharts#5013]
Happens on chart with Line and multiple Area Graphs (up to 3) disappears when resizing, disappears when adding or removing Area Graphs.

http://stackoverflow.com/questions/35256197/why-does-my-line-graph-disappear-in-highcharts-chart

**Comment by pawelfus** [comment]
Could you setup live demo (like jsFiddle)? There is a lot of unrelated code to the Highcharts lib, which will be hard for debugging (and it is using angular wrapper as I can see). Two quick thoughts what may be the reason:

- check if you didn't set anywhere [`gapSize`](http://api.highcharts.com/highstock#plotOptions.area.gapSize). If you did, set it to 0.
- set [`xAxis.ordinal](http://api.highcharts.com/highstock#xAxis.ordinal) to false

**Comment by TorsteinHonsi** [comment]
Also check out my fix for #5008, it may be the same issue.

**Comment by leongaban** [comment]
Closing this, just realized we are using `highcharts-ng` After noticing the version numbers didn't match. Also I am able to get the price line to stay now. What I did in our version was when Area graph buttons where clicked, call our `displayChart` which re-creates `vs.chartConfig` instead of just updating the `setExtremes`.

**Comment by TorsteinHonsi** [comment]
Okay, glad to hear it worked out!​
