### ISSUE TITLE
Custom call to Chart.exportChart() don't support offline exporting

### ISSUE THREAD

**Issue by xavadu** [highcharts/highcharts#5017]
Hello,

We realize that if we want to hide the exporting menu and use a custom button calling to _Chart.exportChart() _ it doesn't work. 

_Chart.exportChart() _ use the server side exporting also if _exporting.fallbackToExportServer_ is set to false.

Reproducible here: http://jsfiddle.net/vfdtvrkn/

You can see the POST to highchart server on the console if a button is pressed, but not if the export is made from the built-in export menu.

Cheers.

**Comment by xavadu** [comment]
Reading the offline-exporting i realize that to do a offline export is necessary to call to _exportChartLocal()_ instead _exportChart()_.

Maybe the API and documentation should be update adding _exportChartLocal()_ information.

**Comment by TorsteinHonsi** [comment]
Thanks for pointing this out. It is now [added to the API](http://api.highcharts.com/highcharts#Chart.exportChartLocal).
