### ISSUE TITLE
tickPositions values override min/max for yAxis

### ISSUE THREAD

**Issue by LFT** [highcharts/highcharts#5020]
There is a problem with the way tickPositions (and tickPositioner return as well) are handled on the yAxis.

If you specify ticks that are smaller than the max and larger than the min, the axis will have a min/max value equal to the min/max value of the ticks.
This behavior is specific to the yAxis. The xAxis works correctly in this regard.

Fiddle showing the behavior for both axis : http://jsfiddle.net/L8h2ppLh/2/
I'd expect the display to be the same in both case, minus the tick that aren't specified in tickPosition.

This seems to behave this way across all browsers.

**Comment by TorsteinHonsi** [comment]
The difference between the X and Y axes is the default value for startOnTick and endOnTick. See http://jsfiddle.net/highcharts/L8h2ppLh/3/

**Comment by LFT** [comment]
My bad, didn't notice those options were different for the two axes.
Thanx for the answer!
