### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined in map.js

### ISSUE THREAD

**Issue by yudarik** [highcharts/highcharts#5021]
Hi Guys,
The last release 4.2.3 has a bug on map.js (highmaps) module...
I'm using this module as part of the highcharts main library, not separately as I don't use all the feature Highmaps allows.

Here is JS error stack i get:
TypeError: Cannot read property 'indexOf' of undefined
    at Ka (eval at <anonymous> (http://localhost:8080/assets/js/vendor.js:1622:2), <anonymous>:11:385)
    at Object.Highcharts.geojson (eval at <anonymous> (http://localhost:8080/assets/js/pub-1b317cb9bc128796e394.js:1119:2), <anonymous>:2082:39)
    at Object.seriesTypes.map.merge.setData (eval at <anonymous> (http://localhost:8080/assets/js/pub-1b317cb9bc128796e394.js:1119:2), <anonymous>:1339:42)
    at Object.Q.init (eval at <anonymous> (http://localhost:8080/assets/js/vendor.js:1622:2)

I've tried to downgrade to release 4.2.0 and it seems that this issue does not reproduced there.

**Comment by sebastianbochan** [comment]
Please recreate your example as live demo, cause highcharts.js with map.js seems to working fine here: http://jsfiddle.net/xcyd7cna/. Errors not appears.

**Comment by jon-a-nygaard** [comment]
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Comment by chrillewoodz** [comment]
I also get this when using Angular, going completely mental over this. Can't figure out what the hell it's missing..

**Comment by jon-a-nygaard** [comment]
@chrillewoodz Could you provide us with some kind of example that shows this issue. Also please let us know which version of Highcharts you are using and other libraries that you are using it with.

**Comment by chrillewoodz** [comment]
I found the issue, the error comes when `chartType: 'map'` is missing from the config object. Adding it gets rid of the error and loads the map perfectly.

**Comment by chrillewoodz** [comment]
My last comment is false, as that only applied to a specific angular module I was using. Now I'm trying to instantiate a map chart but I get the same error, I've looked in the source code and on line 2097 in the `map.src.js` file you do this:

 ```series.chart.mapCredits = format(series.chart.options.credits.mapText, { geojson: geojson }); ```

`series.chart.options.credits.mapText` seems to be the problem here as it appears to become undefined. This is my config:

```
    highcharts.config = {
      chart: {
        type: 'map'
      },
      plotOptions: {
        series: {
          stickyTracking: false,
      		events: {
      			click: function (e) {
      				this.chart.myTooltip.refresh(e.point, e);
      			}
      		}
        },
        pie: {
          cursor: 'pointer',
          dataLabels: {
            enabled: true,
  		formatter: function() {
  		return this.series.isLabelsVisible ? this.y : '';
  	}
          },
          showInLegend: true
        },
        line: {
  	cursor: 'pointer',
          dataLabels: {
            enabled: true
          }
        },
        area: {
  	cursor: 'pointer',
  	dataLabels: {
            enabled: true,
            formatter: function() {
              return this.series.isLabelsVisible ? this.y : '';
            }
          }
        },
        areaspline: {
  	cursor: 'pointer',
  	dataLabels: {
            enabled: true,
            formatter: function() {
              return this.series.isLabelsVisible ? this.y : '';
            }
          }
        },
        column: {
          stacking: false,
  	 cursor: 'pointer',
  	 dataLabels: {
            enabled: true,
            formatter: function() {
              return this.series.isLabelsVisible ? this.y : '';
            }
          }
        },
        map: {
          mapData: Highcharts.maps['custom/world'],
          joinBy: ['name'],
          cursor: 'pointer',
          dataLabels: {
            enabled: true
          }
        }
      },
      exporting: {
        buttons: {
          contextButton: {
            enabled: false
          }
        }
      },
  	toggleModify: false,
      title: {
        text: ''
      },
      xAxis: {
        categories: null,
  	labels: {
          format: graph.span === 0 && graph.isTime && graph.childTarget === null ? '{value:%Y-%m-%d}' : '{value}'
        }
      },
      yAxis: {
        title: {
          text: ''
        },
        labels: {}
      },
      series: null,
      credits: {
        enabled: false
      }
    };
```

Can you please help me with this? It's driving me completely insane.

**Comment by jon-a-nygaard** [comment]
@chrillewoodz We do not have an official Angular extension for Highcharts, and are therefore not responsible for its maintenance or api. You will have to talk to the author and/or maintainers of the extension you are using to fix this issue.

**Comment by ndao** [comment]
@chrillewoodz, which part of the config did you add mapText & mapTextFull to?

**Comment by jon-a-nygaard** [comment]
@chrillewoodz and @ndao Sorry, my mistake. The `mapText` and `mapTextFull` are fairly new options and was not documented properly. I will look into this properly right away.

**Comment by jon-a-nygaard** [comment]
@ndao @chrillewoodz Can one of you provide a live example for this? For instance using [JSFiddle](https://jsfiddle.net/)

It will help me understand what actually happens.

**Comment by chrillewoodz** [comment]
@jon-a-nygaard It's rather simple so you won't really need a fiddle, simply create a new chart using `new Highcharts.Map(config)` and in your `credits` property in the `config` object just leave out `mapText` and `mapTextFull` and you will receive this error. It's when you call `format()` and passing these two properties in the source code which they become undefined if you haven't defined them in your own config.

**Comment by ndao** [comment]
what @chrillewoodz said. My Highmaps version is JS v4.2.5 (2016-05-06)
i realized the [demo](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/maps/demo/all-maps/) doesn't have this issue. Demo version is v4.2.6 (2016-08-02)

**Comment by jon-a-nygaard** [comment]
@chrillewoodz  I followed your description but I do not get any errors. Except when I set `mapText` to undefined explicitly, which I will fix.
[Here is a Gist](https://gist.github.com/jon-a-nygaard/61ac58ad02b18747b3a9cd30386f7526) which shows my setup which I tested on Node.js using Highmaps v4.2.5, bundled with Browserify.
I also tried the same in a [JSFiddle](http://jsfiddle.net/jon_a_nygaard/uo2z19at/2/)

**Comment by ndao** [comment]
@jon-a-nygaard try using the NPM module. I reproduced it [here](http://requirebin.com/?gist=eaed48cd139c47af5aad39bea3e532b7)

**Comment by monica11** [comment]
@jon-a-nygaard  @ndao Are you able to figure out the problem? I am also getting an issue similar to this one. This is the error I am getting. Can anyone help ?
```
Subscriber.js:227 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at highcharts.js:42
    at Array.forEach (<anonymous>)
    at q (highcharts.js:26)
    at J.colorGradient (highcharts.js:42)
    at J.fillSetter (highcharts.js:59)
    at J.attr (highcharts.js:45)
    at u.Legend.colorizeItem (highcharts.js:201)
    at u.Legend.renderItem (highcharts.js:205)
    at highcharts.js:209
    at Array.forEach (<anonymous>)
```

**Comment by pawelfus** [comment]
Hi @monica11, your issue seems to be not related to the main issue. It looks like an issue with gradients on the chart - could you recreate your issue in jsFiddle?

@ndao - I just tested the demo your posted (it's based on Highcharts v5) and it works fine, could you confirm?

**Comment by monica11** [comment]
@pawelfus Yes. I have solved the issue. It was related to the gradient.  Thanks for your help.

**Comment by nivethaKumar** [comment]
> help

how you fix this one? i have this same issue

**Comment by nivethaKumar** [comment]
> > help
> 
> @monica11 
how you fix this one? i have this same issue
