### ISSUE TITLE
Dates on x-axis are ignored

### ISSUE THREAD

**Issue by andreaspalsson** [highcharts/highcharts#5022]
After the update to 4.2.3 type:"datetime" on the x-axis seems to be broken. They just increment new Date(0) with one tick for each data value instead of using the date provided in the data array.

http://jsfiddle.net/k58r7x76/1/

Changing back to 4.2.2 solves the issue.
http://jsfiddle.net/1mut8dvu/1/

**Comment by pawelfus** [comment]
Looks like duplicate of #5010 - x-values should be numbers: http://jsfiddle.net/k58r7x76/3/

**Comment by andreaspalsson** [comment]
Ok, so the bug was that it worked before. Might be just me but when I see support for type datetime I would expect it to be able to handle a JavaScript date or even be able to parse a string on the correct date format. But thanks for the help.

**Comment by TorsteinHonsi** [comment]
> Ok, so the bug was that it worked before.

Yes, but only partially, like the case in #5010 shows. But it is interesting that in worked in your case, and that the tooltip even preserved the full date format. It works by accident because Date objects produce timestamps when cast to numbers.

**Comment by joallard** [comment]
Wow that behavior is completely ridiculous.

**Comment by TorsteinHonsi** [comment]
> Wow that behavior is astoundingly ridiculous.

I don't know your humor, but I take that as sarcastic for "I would expect the X axis to accept Date objects for X values under any circumstance".

I'll see what I can do...

**Comment by joallard** [comment]
Indeed; sorry for assuming you knew my humor, I tend to do that sometimes. Kudos on making that into a fix!

**Comment by TorsteinHonsi** [comment]
You're welcome :)
