### ISSUE TITLE
Default for solidgauge linecap is round

### ISSUE THREAD

**Issue by frontsideair** [highcharts/highcharts#5024]
[The docs](http://api.highcharts.com/highcharts#plotOptions.solidgauge.linecap) for solid gauge is not consistent with code. It says the default value for this is `square`, but it's actually `round`. See [fiddle](http://jsfiddle.net/4ceus7xz/).

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, you're right! Fixed now.
