### ISSUE TITLE
xAxis minRange doesn't work with async loading

### ISSUE THREAD

**Issue by xavadu** [highcharts/highcharts#5026]
Hello,

Note:I was looking if it was reported previously, i didn't find it.

[_xAxis.minRange_](http://api.highcharts.com/highstock#xAxis.minRange) doesn't work with async loading when you do zoom by 'mouse selection' (it mean to select a part of the graph to zoom it)

To reproduce it i used a jsfiddle demo, i added a minRange of one day, on the range button it is okay, but you can see that is possible to zoom and zoom in until reach the hours on the xAxis. The minRange option is ignored, also the default (_The default minRange for the x axis is five times the smallest interval between any of the data points_ ) is ignored if not option is set for minRange  respectively.

http://jsfiddle.net/u4zfvu5z/

In the demo, at least it is hourly data, but in our case, per example, we have daily data and when it is zoom in to hourly, the graph isn't plot:

![selection_003](https://cloud.githubusercontent.com/assets/1382820/12944080/52129af0-cfe5-11e5-8db5-f4a0520c8873.png)

![screenshot from 2016-02-10 10-50-33](https://cloud.githubusercontent.com/assets/1382820/12944086/56c405b6-cfe5-11e5-8563-0b9e11a663cf.png)

Thanks.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

I tried to reproduce this in a controlled way, see http://jsfiddle.net/highcharts/u4zfvu5z/1/.

In the demo I try to programmatically zoom in on one hour, but the axis extremes are set to 08:00 to 20:00 the same day. On an ordinal axis, only the X values holding data is shown, so this is to be expected when the `minRange` is one day.

If we set `xAxis.ordinal` to false, we see the full day in the X axis extremes: http://jsfiddle.net/highcharts/u4zfvu5z/5/.

Please update the fiddle if you have extra information for reproducing the issue.

**Comment by pawelfus** [comment]
I tried the same issue with one month:  http://jsfiddle.net/u4zfvu5z/4/ - it works properly too. 

I recognize similar issues with missing line. In most cases the issue was caused by setting `gapSize` too high and that cause missing line (points do exist, but line is not rendered).

**Comment by xavadu** [comment]
@TorsteinHonsi I see your jsfiddle example which works, but there are some difference with our case: You have hourly update in this example. 

Can you provide a _from-sql.php _ script which only provideaily or greater (monthly, year..) values? on that case maybe we can reproduce that the plot line isn't drawn.

In a second place, which now i realize that could be something different, if you set one day of _minRange_ and you have only daily data (each point is for one day at 00:00:00 hour), you are not expecting to see the hours (...20:00, 20:30, 21:00...) on the xAxis. The same in the example if @pawelfus , if you have only monthly points (one point by month, per example first day of the month at 00:00:00 hour, you are not expecting to see the days in the xAxis. I know that it can be quite tricky and maybe a different issue.

**Comment by pawelfus** [comment]
> In a second place, which now i realize that could be something different, if you set one day of *minRange* and you have only daily data (each point is for one day at 00:00:00 hour), you are not expecting to see the hours (...20:00, 20:30, 21:00...) on the xAxis. 

Correct me if I am wrong, but at your zoom level, you have only one point and `minRange` to one day, so you expect only one label on xAxis (directly under the point)? Data in my example is based on **minutes**, but `minRange` is set to **1 month**, to show it works.

I guess this is the case: http://jsfiddle.net/u4zfvu5z/6/ - but in my opinion, `minRange` shouldn't be the same as granularity. I mean, do you really intend to render just one point for user? I think that `minRange` should be one unit higher (minutes->hours, days->weeks, months->years etc.) than granularity.

**Comment by xavadu** [comment]
I agree that the _minRange_ should to be set one unit higher, I did it before with 5 days when testing, and wasn't working like expected then i open this issue, but for sure i did something wrong, i tried it again and works fine!!

Is just a pity that the plot isn't covering all the graph, _xAxis.ordinal_ is set to _true_ (default), but the _mnRange_ functionality is okay! 

![selection_004](https://cloud.githubusercontent.com/assets/1382820/13107894/450988a6-d570-11e5-88c6-3a75b3cc72ec.png)


Thanks for the time
