### ISSUE TITLE
When using Pattern graphs, charts are not showing in IE8

### ISSUE THREAD

**Issue by VartikaGarg** [highcharts/highcharts#5027]
All charts/graphs are using pattern files.
When I am trying to view these charts in IE8, nothing comes.
It is working fine with IE11.

It should work on IE8 & IE9 also.
Clients are using IE8 & IE9.

**Comment by sebastianbochan** [comment]
This is related with non supporting SVG elements by IE8. You need to create pattern as image and then use it. This is described in docs of pattern extension. http://www.highcharts.com/plugin-registry/single/9/Pattern-Fill (chapter: Version1, oldIE compatble)

**Comment by VartikaGarg** [comment]
And with IE9? Is it supported there?

There are no fixed number of patterns that I have to use in my graphs.
My graph might have 8 patterns or 9 or more or less.

In that case, how can we make it work on IE9?

**Comment by VartikaGarg** [comment]
Any updates?

**Comment by pawelfus** [comment]
IE9 should natively work. If it doesn't work for you, then could you recreate issue on jsFiddle?

**Comment by TorsteinHonsi** [comment]
Closing this, please reopen if you have a live reproduction in IE9.
