### ISSUE TITLE
4.2.3 still causing runtime errors after 4.2.2

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#5029]
https://github.com/highcharts/highcharts/issues/4998

![screen shot 2016-02-10 at 15 58 10](https://cloud.githubusercontent.com/assets/1677449/12949346/fc5783c0-d00f-11e5-85f1-727d3d59e92f.png)

**Comment by TorsteinHonsi** [comment]
It's a different issue from the other one. It should be fixed by the commit above. 

Still, can you help us reproduce it in jsFiddle so that we can fix the root cause and set up a regression test?
