### ISSUE TITLE
Highcharts export menubutton to be shown as download button as it was in earlier version of exporting module.

### ISSUE THREAD

**Issue by Nidso** [highcharts/highcharts#5031]
How to get the earlier version download button in place of current menu button in highcharts exporting.

**Comment by TorsteinHonsi** [comment]
We have a compatibility module for the old Highcharts 2 look. See http://jsfiddle.net/highcharts/a4syLsgf/.

For the future, please note that this is our bug tracker. For general tech support, please see www.highcharts.com/support.
