### ISSUE TITLE
Issue is if we don't have data for 2016 year it's should display blank canvas not the previous year 2015 data.

### ISSUE THREAD

**Issue by rakeshongithub** [highcharts/highcharts#5033]
YTD - Year to date refers to the period extending from the beginning of the year to the present. Highchart YTD showing previous year data if data is not available for current YTD. Can we fix the YTD for current Year to Date instead going previous year.

**Comment by pawelfus** [comment]
Hi,

Thank you for reporting this! I think you are right, typically `YTD` means 1st of January of the **current** year to the **current** date. Current solution renders 1st of Jan of the **last point's** year to that **last point**. 

I think that button `YTD` should be disabled when datasets don't contain at least one point with the current year.

However, I am not sure about the cases when user wants `YTD` for the dataset, for example rendering specific two years of data: http://jsfiddle.net/0tLmg7j0/2/

**Comment by rakeshongithub** [comment]
Can you suggest how to disable the `YTD` button if at least one point with the current year is not available. And one more issue, in my case I need to show `YTD` as default selector. So can we show blank canvas in that case.

**Comment by pawelfus** [comment]
You can achieve blank space on the right side by setting `xAxis.max` with `xAxis.ordinal`, see example: http://jsfiddle.net/0tLmg7j0/3/

I am not sure how disabled `YTD` button should work when you need blank space when button is selected? Here is an example how to wrap `updateButtonStates` from prototype and update `YTD` button: http://jsfiddle.net/0tLmg7j0/5/
