### ISSUE TITLE
Highmaps: series shadow width option didn't work properly on IE

### ISSUE THREAD

**Issue by PohlodSlavik** [highcharts/highcharts#5035]
Map series shadow scales when map is zoomed on IE.
http://jsfiddle.net/zqh4jyff/3/
This example works correctly in Chrome and Firefox, but on IE yellow shadows scales when map is zoomed.

**Comment by jon-a-nygaard** [comment]
Thanks for reporting. We will have a look at this as soon as possible.

__Internal note: could not relate this issue to a specific version. Seems to have existed from the first version__

**Comment by oysteinmoseng** [comment]
Internal note: 
IE does not support `vector-effect="non-scaling-stroke"` which is used in other browsers. For ordinary points this is solved by setting `stroke-width="inherit"` and updating the group `stroke-width` after zooming.
