### ISSUE TITLE
Legend has paging when exporting

### ISSUE THREAD

**Issue by beniwtv** [highcharts/highcharts#5036]
Hi,

When you export a Pie chart with a lot of Items in the legend, paging is applied there, just as if it was a normal chart displayed on the page. Unfortunately, graphics are non-interactive :P.

I did not see any option of turning that off (for exporting or in the legend API), so I am reporting th

(See screenshoot).
![bug](https://cloud.githubusercontent.com/assets/1401072/13012734/bfd14398-d1ac-11e5-842f-498b6dd6a319.png)

**Comment by jon-a-nygaard** [comment]
Thanks for reporting. We will have a look at it as soon as possible.

_Internal note: There should be an option like legend.navigation.enabled so that we can disable navigation in exporting. The legend navigation could perhaps also be disabled by default during exporting, as a good practice._

**Comment by TorsteinHonsi** [comment]
Simply disabling the navigation has problems too, since the legend will take over the entire chart area, and items will start falling out of the image.

A possible workaround is to use a plugin that adapts the chart height to make room for the legend: http://www.highcharts.com/plugin-registry/single/8/Adapt-Chart-To-Legend.

**Comment by foxprorawks** [comment]
I tried the possible workaround, but it caused problems when exporting.

![chart 1](https://cloud.githubusercontent.com/assets/16322155/13495614/b4c2dc90-e143-11e5-92bf-578e81652faf.jpeg)

**Comment by TorsteinHonsi** [comment]
I added an enabled option like initially requested here. With the new option, you can combine it with a specific chart height for exporting, see http://jsfiddle.net/highcharts/nvuu1hjg/.

It's not perfect, since you need to hard-code (or preprocess) in order to set the exported chart height, but it works at least for this case.

**Comment by foxprorawks** [comment]
In my case, the legend is below the chart - I'm not sure how I can determine the height of the chart in order to hard code it.  Will this work for me?

**Comment by TorsteinHonsi** [comment]
Yes, in fact this also works without enabling the legend. Simply by increasing the chart height in export, the legend no longer needs navigation. I guess there's no good way to determine the chart height - you can do something based on the series names, how many series are there and how long are the names etc. It will be an approximation, but perhaps good enough.

**Comment by beniwtv** [comment]
The option is good, however, without Highcharts auto-calculating the height it's possibly not enough. 
We would need to somehow calculate this ourselves, but that might be inacurrate, and thus not enough for an enterprise application that users access.

**Comment by TorsteinHonsi** [comment]
I see. Actually the chart height adapt plugin should work here. You should be able to use that in export only. If you share a jsFiddle of one of your typical charts, I'd be happy to work on it.

**Comment by foxprorawks** [comment]
Hi - when will enabled option be included in the official release?

**Comment by TorsteinHonsi** [comment]
We will publish a maintenance release within a few weeks.

**Comment by foxprorawks** [comment]
Thanks.

**Comment by bouri-mounir** [comment]
I also have the same issue, any news about the fix ?

**Comment by TorsteinHonsi** [comment]
Yes, in the latest release you can [disable the legend navigation](http://api.highcharts.com/highcharts#legend.navigation.enabled) for export. Also, the simple fix is to just set a [greater height in export](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/legend/navigation-enabled-false/).

**Comment by bouri-mounir** [comment]
Thank you, this issue is fixed on export but it still persists when we print a chart.
What should I do ?

**Comment by TorsteinHonsi** [comment]
Good point! You can use the `beforePrint` and `afterPrint` events for that. See http://jsfiddle.net/highcharts/unz7Letj/.

**Comment by bouri-mounir** [comment]
I tried to modify navigation value but it does not work , it's work only on afterPrint event ...
http://jsfiddle.net/unz7Letj/1/

**Comment by TorsteinHonsi** [comment]
I'm afraid the legend can't be updated like that. Is there a specific reason why you can't set the height like I showed above? Without a greater height the legend will be clipped anyway, so it won't be readable.

**Comment by bouri-mounir** [comment]
It works fine for me if I change the legend maxHeight on beforePrint event instead of disabling legend navigation. 
https://jsfiddle.net/bouri/pypuy4dg/1/
Thank you.

**Comment by znevrly** [comment]
Hi,
this is annoying issue, more like a bug than improvement. It will be great to fix it in some Highcharts 5.x version. Thank you a lot!

**Comment by TorsteinHonsi** [comment]
You're aware of the simple option of setting [a greater height in export](http://jsfiddle.net/xd2utwp6/)?

```js
        // In export, increase the chart height to disable navigation
        exporting: {
            chartOptions: {
                chart: {
                    height: 600
                }
            }
        }
```

**Comment by beniwtv** [comment]
Yes, we know this option exists, but this is not a satisfactory solution. It is more of a hack bound to cause problems later.

Depending on the data, we have more or less options in the legend. So, we would need to somehow calculate the height depending on how many options there are at a given time.

This is not accurate, as we do not have a lot of internal SVG data and information that HighCharts itself has. For example, the height may depend on what font you use, how the browser renders it, new versions of HighCharts doing things differently, etc...

Unless HighCharts makes sure the Legend text box is always the same height - in which case the question would be: "How do we know? Is there an API to query for this?".

**Comment by TorsteinHonsi** [comment]
I believe the [adapt chart height to legend](www.highcharts.com/plugin-registry/single/8/Adapt-Chart-To-Legend) plugin answers this question. Actually this is a perfect use case for it. I did a patch and added a demo with [enabling it only for export](http://jsfiddle.net/highcharts/rpq4qkd9/).

Now the remaining issue is that the computed height is too large: http://jsfiddle.net/highcharts/rpq4qkd9/2/. I think that's because the total legend height is added to the total chart height. Will work on a fix in the plugin.

**Comment by beniwtv** [comment]
Awesome! That already looks very promising.

**Comment by TorsteinHonsi** [comment]
Thanks! The remaining issue is fixed now: https://github.com/highcharts/adapt-chart-to-legend/issues/10. 

Live demo at http://jsfiddle.net/highcharts/rpq4qkd9/3/

**Comment by beniwtv** [comment]
Awesome! Thank you very much! Our customers are going to be very happy!

**Comment by beniwtv** [comment]
So I can report this now works flawlessly.

**Comment by TorsteinHonsi** [comment]
Wonderful!

**Comment by tailorsira** [comment]
@TorsteinHonsi  How can I use this plugin in react project? what should I write import ? from 'highcharts-adapt-chart-to-legend', thanks for your contribute.

**Comment by TorsteinHonsi** [comment]
I'm not sure if it is on npm - but you can just add this snippet somewhere in your project: https://rawgit.com/highcharts/adapt-chart-to-legend/master/adapt-chart-to-legend.js

**Comment by tailorsira** [comment]
@TorsteinHonsi  Thanks ,Yeah, I put your code segment in the render function of my react component, it works very well the when the first time render, but the legend disappeared in the later times render, I haven't found the solution, so where should I put this plugins code? `class ShowCharts extends Component {
  merge = (a, b) => {
    if (b.length > a.length) {
      const t = a
      a = b
      b = t
    }
    return a.map((item, index) => item + (b[index] || 0))
  }
  render() {
    (function (H) {

     const wrap=function(a,f,l){
      var q=a[f];
      a[f]=function(){
        var a=Array.prototype.slice.call(arguments),
        u=arguments,
        d=this;
        d.proceed=function(){
          q.apply(d, arguments.length?arguments:u)
        };
        a.unshift(q);
        a=l.apply(this,a);
        d.proceed=null;
        return a
        }
      }

      wrap(H.Legend.prototype, 'render', function (proceed) {
        var chart = this.chart,
          translateY,
          addedHeight;
        proceed.call(this);
        if (this.options.adjustChartSize) { // #7

          addedHeight = this.legendHeight;
          if (!chart.originalChartHeight) {
            chart.originalChartHeight = chart.chartHeight;
          }

          if (this.options.align === 'left' || this.options.align === 'right') {
            addedHeight = Math.max(this.group.translateY + this.legendHeight - chart.originalChartHeight, 0);

            // Move the legend down
          } else if (this.options.verticalAlign === 'bottom') {
            translateY = this.group.attr('translateY') + this.legendHeight;
            this.group.attr('translateY', translateY);
            if (this.group.alignAttr) {
              this.group.alignAttr.translateY = translateY;
            }
          }
          if (addedHeight) {
            //   // Adapt chart metrics
            chart.chartHeight = chart.originalChartHeight + addedHeight;
            chart.marginBottom += addedHeight;

            //   // Set the DOM element heights
            chart.container.style.height = chart.chartHeight + 'px';
            h = chart.container.style.height
            chart.renderer.boxWrapper.attr('height', chart.chartHeight); // #7

            var boxedElement = chart.renderer.box.clientWidth ? chart.renderer.box /*IE*/ : chart.renderer.box.parentElement /*FF*/ ;
            var viewBox = "0 0 " + boxedElement.clientWidth + " " + boxedElement.clientHeight;
            chart.renderer.boxWrapper.attr('viewBox', viewBox);
          }
          this.positionCheckboxes();
        }
      });
    }(Highcharts))
    const totalData = this.props.data
    const preData = totalData.filter(obj => obj.Values !== null)
    const dateFormat = 'YYYY-MM-DD HH:mm:ss'
    const startTime = this.props.startTime
    const endTime = this.props.endTime
    Highcharts.setOptions({
      global: {
        useUTC: false,
      },
      credits: {
        enabled: false
      },
      xAxis: [{
        // crosshair: true,
        type: 'datetime',
        dateTimeLabelFormats: {
          hour: '%H:%M',
        },
        // max: endTime.valueOf(),
        max: endTime * 1000,
        tickInterval: 300 * 1000
      }],
      plotOptions: {
        series: {
          pointStart: startTime * 1000,
        },
      },
      tooltip: {
        xDateFormat: '%Y-%m-%d %H:%M:%S',
        shared: true
      },
      legend: {
        layout: 'vertical',
        borderWidth: 0,
        adjustChartSize: true,
        navigation: {
          enabled: false
        },
        // maxHeight: '60',
        labelFormatter: function() {
          const data = this.yData
          const len = data.length
          const max = Math.max(...data)
          const min = Math.min(...data)
          const last = data[len - 1]
          const sum = data.reduce((pre, cur) => cur += pre)
          const avg = (sum / len).toFixed(3)
          return `${this.name} <span style="color:#DB7093"> last ${last}</span>  <span style="color:#FF00FF"> min ${min} </span> <span style="color:#9932CC"> max ${max}</span> <span style="color:#DC143C"> avg ${avg} </span>`
        },
      },
    })
    const selectedView = this.props.title
    let view
    // handle data according to selected view
    if (selectedView === 'Endpoint') {
      const len = preData.length
      const object = {}
      for (let i = 0; i < len; i += 1) {
        const item = preData[i]
        if (!object[item.counter]) {
          object[item.counter] = []
          object[item.counter].push(item)
        } else {
          object[item.counter].push(item)
        }
      }
      const endpointsdata = object
      // show endpoint view
      view = (
        Object.keys(endpointsdata).map((item) => {
          const title = item
          // data = [
          // {name:'endpoint1', data: [[t,v], [t,v]...]},
          // {name:'endpoint2', data: [[t,v], [t,v]...]},
          // ...
          // ]
          const data = endpointsdata[item].map((obj) => {
            const newObj = { name: '', data: [] }
            newObj.name = obj.endpoint
            newObj.data = obj.Values.map((x) => {
              const array = []
              array.push(x.timestamp * 1000, x.value)
              return array
            })
            return newObj
          })
          // calculate sum
          if (this.props.isSum) {
            // sumData = [
            // [[t,v], [t,v]...],
            // [[t,v], [t,v]...],
            // ...
            // ]
            const sumData = data.map((obj) => {
              const value = obj.data
              return value
            })
            // finalSumData = [
            // [v, v, ...]
            // [v, v, ...]
            // ...
            // ]
            const finalSumData = sumData.map((itemArray) => {
              const d = itemArray.map((j) => {
                const re = j[1]
                return re
              })
              return d
            })
            // sum = [sum1, sum2, ...]
            const sum = finalSumData.reduce((acc, curValue) => this.merge(acc, curValue), [])
            // primaryData = [
            // [[t,v], [t,v]...],
            // [[t,v], [t,v]...],
            // ...
            // ]
            const primaryData = data.map((o) => {
              const newArray = o.data
              return newArray
            })
            // change [sum1, sum2, ...] to [[timestamp1, sum1], [timestamp2, sum2], ...]
            const result = sum.map((curValue, index) => {
              const newArr = []
              newArr.push(primaryData[0][index][0], curValue)
              return newArr
            })
            // add sum
            data.push({ name: 'sum', data: result })
          }
          const options = {
            title: {
              text: title,
            },
            series: data,
            // series: [],
          }
          return (<div className="charts"><LazyLoad height={h}><Chart container={'chart'} options={options} /></LazyLoad></div>)
        })
      )
    }
    else if (selectedView === 'Counter') {
      const len = preData.length
      const object = {}
      for (let i = 0; i < len; i += 1) {
        const item = preData[i]
        if (!object[item.endpoint]) {
          object[item.endpoint] = []
          object[item.endpoint].push(item)
        } else {
          object[item.endpoint].push(item)
        }
      }
      const countersdata = object
      // show counter view
      view = (
        Object.keys(countersdata).map((item) => {
          const title = item
          const data = countersdata[item].map((obj) => {
            const newObj = { name: '', data: [] }
            newObj.name = obj.counter
            newObj.data = obj.Values.map((x) => {
              const array = []
              array.push(x.timestamp * 1000, x.value)
              return array
            })
            return newObj
          })
          if (this.props.isSum) {
            const sumData = data.map((obj) => {
              const value = obj.data
              return value
            })
            const finalSumData = sumData.map((itemArray) => {
              const d = itemArray.map((j) => {
                const re = j[1]
                return re
              })
              return d
            })
            const sum = finalSumData.reduce((acc, curValue) => this.merge(acc, curValue), [])
            const primaryData = data.map((o) => {
              const newArray = o.data
              return newArray
            })
            const result = sum.map((curValue, index) => {
              const newArr = []
              newArr.push(primaryData[0][index][0], curValue)
              return newArr
            })
            data.push({ name: 'sum', data: result })
          }
          const options = {
            title: {
              text: title,
            },
            series: data,
          }
          return (<div className="charts"><LazyLoad height={h}><Chart container={'chart'} options={options} /></LazyLoad></div>)
        })
      )
    } else {
      const data = preData.map((obj) => {
        const newObj = { name: '', data: [] }
        newObj.name = obj.endpoint + ' | ' + obj.counter
        newObj.data = obj.Values.map((item) => {
          const newArr = []
          newArr.push(item.timestamp * 1000, item.value)
          return newArr
        })
        return newObj
      })
      if (this.props.isSum) {
        const sumData = data.map((obj) => {
          const value = obj.data
          return value
        })
        const finalSumData = sumData.map((itemArray) => {
          const d = itemArray.map((j) => {
            const re = j[1]
            return re
          })
          return d
        })
        const sum = finalSumData.reduce((acc, curValue) => this.merge(acc, curValue), [])
        const primaryData = data.map((o) => {
          const newArray = o.data
          return newArray
        })
        const result = sum.map((curValue, index) => {
          const newArr = []
          newArr.push(primaryData[0][index][0], curValue)
          return newArr
        })
        data.push({ name: 'sum', data: result })
      }
      const options = {
        title: {
          text: '组合视角',
        },
        series: data,
      }
      view = (<div className="charts"><Chart container={'chart'} options={options} /></div>)
    }

    return (
      <div className="charts-container">
        {
          view
        }
      </div>
    )
  }
}`

**Comment by pawelfus** [comment]
This should be included as a plugin, for example a separate file. I mean this should be called only once, when Highcharts library is loaded.
