### ISSUE TITLE
HIghcharts legend title styling is not working

### ISSUE THREAD

**Issue by kranthit873** [highcharts/highcharts#5037]
@nicoder I am not able to style legend title alone. I want to display legend title to center and I am not able to do it through normal styling process. I want to move benchmark months(legend title) to center.

![legendtitloestyle](https://cloud.githubusercontent.com/assets/17203045/13014914/c78db2d2-d17b-11e5-9f07-b374491c22ee.JPG)

**Comment by oysteinmoseng** [comment]
A possible (approximate) workaround: https://jsfiddle.net/5wegjmcz/

**Comment by tavuntu** [comment]
Works for me, a simple style property should do the trick though, I'm with @kranthit873

**Comment by TorsteinHonsi** [comment]
The problem is that in SVG, you can't position text with CSS like you do in HTML, so we need to do JavaScript logic at some point.

**Comment by tavuntu** [comment]
I see, thanks for the info
