### ISSUE TITLE
legendItemClick's event object has different structure from jQuery's event object

### ISSUE THREAD

**Issue by nanatiris** [highcharts/highcharts#5038]
This is the documentation for **legendItemClick** function:
> ... One parameter, event, is passed to the function. This contains common event information based on jQuery...

However, the latest version of Highcharts (4.2.3) doesn't seem to have the similar structure as the event object of jQuery anymore. It was before (was using 4.0.1 previously). This change has triggered a bizarre effect on my use case - I created a custom function which should open a color picker upon click. Instead, what happened was there were two click events happening on a single mouse click (which in effect closes the color picker on the 2nd "_click_").

I did noticed that inside the new event object, there is a _`browserEvent`_ which contains the jQuery event. So in order to have a workaround for my use case, i did a stopPropagation() using the browserEvent object. 

I'm pretty sure that there could be a reason for the change but I just wanted to suggest that the documentation should be updated as well for clarification.

Anyway, thanks for the great plugin! :+1:

**Comment by oysteinmoseng** [comment]
Hi, thanks for reporting. This is probably due to the recent move to use the Highcharts Standalone Framework as default.

Does calling `event.preventDefault()` help in your case? It might be a cleaner solution than digging into the specific `browserEvent`.

**Comment by nanatiris** [comment]
I created a jsFiddle that replicates my use case to show the issue: http://jsfiddle.net/6c19cuxp/1/

`e.preventDefault()` only stopped the default function when clicking legends - which is hiding chart series. It seems that the browser doesn't treat the first event as a click because the event from Highcharts has a type `legendItemClick`. Hence, a 2nd event happens (which will be browser event for the click) causing it to hide the color picker. Uncommenting line 19 will fix the issue.

I hope this helps. Thank you!

**Comment by TorsteinHonsi** [comment]
I think I'm missing something here, when I add a log in the top of the event handler, it seems like it only fires once: http://jsfiddle.net/highcharts/6c19cuxp/2/

What causes the hide/show of the chartSpectrum?

**Comment by nanatiris** [comment]
@TorsteinHonsi I'm sorry for the confusion. You are right, the `legendItemClick` event will only fire once. But because its event object is not similar to the jQuery's event object, the browser fires its own click event _(this is just my guess)._ The chart spectrum hides when it gets unfocused and in this case, an unfocusing event happens because of the 2nd event (it is a click outside the spectrum). The two events fired on a single click is noticeable when you use a debugger and put a breakpoint on the hide() function of the spectrum plugin (Line 665 of spectrum.js). Thanks!

**Comment by TorsteinHonsi** [comment]
Yes, i see that the hide function runs twice, but the `legendItemClick` only fires once... So this is probably not a Highcharts bug?

**Comment by nanatiris** [comment]
I agree, it is not a Highcharts bug.. What I was originally pointing out is that there is a change in the event object structure of `legendItemClick` but the API documentation wasn't updated (at least at the time that I posted this issue). Now I see that it has changed, so i'll go ahead and close this issue :-) 

Regarding the use case I have, i have shared it just in case people are searching for issues related to the legendItemClick and hopefully, the workaround I have will be helpful to them. 

Thank you.

**Comment by TorsteinHonsi** [comment]
Okay, thanks for sharing!
