### ISSUE TITLE
Horrible performance due to “Recalculate Style” and “Layout” (reproduced jsfiddle!)

### ISSUE THREAD

**Issue by ktravelet** [highcharts/highcharts#5039]
Update
Repro:
1. Take the data from: https://jsfiddle.net/j54rdqto/
2. Paste it into the textbox here: https://jsfiddle.net/6gbcdb4L/5/
3. click graph

When looking in the chrome "timeline" during the rendering there are 1000's of:

"recalculate style (highcharts.js:52)"
"layout (highcharts.js:52)"
Every once in a while I'll find a graph that doesnt have either of those and the performance is amazing. Also for what ever reason Safari doesnt seem to have any performance issues.

I'm using the following options for highcharts and also tried the boost.js with no success.

```
console.time('Creating Initial Graph');
            // Create Graphs
            $('#cpuGraph').highcharts({

                chart: {
                    type: 'line',
                    //zoomType: 'x',
                    animation: false,
                    shadow: false
                },
                plotOptions: {
                    line: {
                        enableMouseTracking: true,
                        dataLabels: {
                            enabled: false
                        },
                        animation: false,
                        marker: {
                            enabled: false
                        },
                        turboThreshold: 100
                    }
                },
                tooltip: {
                    animation: false,
                    crosshairs: true,
                    shared: true,
                    valueSuffix: '%',
                    backgroundColor: null,
                    borderWidth: 0,
                    shadow: false,
                    useHTML: true,
                    style: {
                        padding: 0
                    }
                },
                xAxis: {
                    categories: times
                },
                yAxis: {
                    max: 100,
                    min: 0
                },
                title: {
                    text: 'Trimmed Highcharts drawing points'
                },

                subtitle: {
                    text: 'Using the experimental Highcharts Boost module'
                }



            });
            console.timeEnd('Creating Initial Graph');

            console.time('Converting Data Array to Chart Object');
            var newSeries = [];
            for ( i = 0; i < servers.length; i++) {
                var seria = {};
                seria['name'] = servers[i];
                seria['data'] = cpuArray[i];
                newSeries.push(seria);
            }
            console.timeEnd('Converting Data Array to Chart Object');

            console.time('Creating chart variable');
            var chart = $('#cpuGraph').highcharts();
            console.timeEnd('Creating chart variable');

            console.time('Adding All Chart Objects to Chart');
            $.each(newSeries, function(i){
                console.time("Adding series: " + i);
                chart.addSeries(newSeries[i], false);
                console.timeEnd("Adding series: " + i);
            });

            chart.redraw();
            console.timeEnd('Adding All Chart Objects to Chart');
```

Typical timings:

```
:232 Creating Initial Graph: 778.805ms
:242 Converting Data Array to Chart Object: 0.029ms
:252 Adding series: 0: 1.698ms
:252 Adding series: 1: 0.412ms
:252 Adding series: 2: 0.227ms
:252 Adding series: 3: 0.188ms
:252 Adding series: 4: 0.140ms
:252 Adding series: 5: 0.123ms
:252 Adding series: 6: 0.110ms
:254 Adding All Chart Objects to Chart: 3.374ms
:258 Redraw chart with all objects: 9084.491ms
```

**Comment by ktravelet** [comment]
Also Safari works flawlessly with no performance issues for rendering or interactions after the render.  

Also with Chrome, even after its rendered, is very sluggish with the interactions.

**Comment by pawelfus** [comment]
Hi, 

Thanks for reporting! When I try your demo it is killing my browser (Chrome ;) ). After checking your options, I realized you are using `categories` while your data is rather datetime based. In that case, create points as `point = [timestamp, value]` and set `xAxis.type` to `datetime`. I just made simple test case, where `categories` are removed, and instead formatter is rendering correct labels on the linear axis. After enabling `boost.js` it renders the chart. I assume the issue with my machine. 

I decided to create the chart with all options at once, not using `addSeries()`, here is the result: https://jsfiddle.net/6gbcdb4L/7/

It renders the chart in less than 3sec on my old machine. Could you check that and let us know about the result?

**Comment by jon-a-nygaard** [comment]
@pawelfus Hi Pawel, I think you are linking to the wrong version of your fiddle. The version nr 7 still uses addSeries().

**Comment by pawelfus** [comment]
That's correct, I updated the demo in the meantime ;)

**Comment by jon-a-nygaard** [comment]
I noticed, it works much better, but I do still get 10000-20000ms on creating the chart in Chrome. Do not see why.

**Comment by ktravelet** [comment]
Hey guys!  Thanks a ton for the help. I think I have to use add series as there wont ever be the same amount of series when a user inputs data.  Otherwise those tips are definitely helping on my side for performance.

@jon-a-nygaard can you see if the newest fiddle helps? Version 11.

for some reason removing the data from the text area dramatically improves performance.

**Comment by jon-a-nygaard** [comment]
The version 11 is working great when I try it. Results are listed below:
```
Creating Initial Graph: 0.060ms
Converting Data Array to Chart Object: 0.039ms
Creating chart variable: 0.001ms
Adding series: 0: 0.012ms
Adding series: 1: 0.006ms
Adding series: 2: 0.002ms
Adding series: 3: 0.001ms
Adding series: 4: 0.002ms
Adding series: 5: 0.001ms
Adding series: 6: 0.002ms
Adding All Chart Objects to Chart: 0.368ms
Create chart with all objects: 313.240ms
```
>I think I have to use add series as there wont ever be the same amount of series when a user inputs data.

@ktravelet My advise is that you should only use the addSeries when your chart is updated with new data you did not have access to before you created the chart. Your "Append" action would be a suitable case for the use of addSeries.

It seems that you guys have solved this issue, so I will be closing it. Just reopen it if I am mistaken.
