### ISSUE TITLE
ItemMarginTop and ItemMarginBottom not working in highcharts 2.1.2 for Legend Items

### ISSUE THREAD

**Issue by udhaya1983** [highcharts/highcharts#5040]
ItemMarginTop and ItemMarginBottom not working in highcharts 2.1.2 for Legend Items. I want to have a space a between each item, but on using ItemMarginTop and ItemMarginBottom it is not working

**Comment by pawelfus** [comment]
Hi,

[`itemMarginTop`](http://api.highcharts.com/highcharts#legend.itemMarginTop) and [`itemMarginBottom`](http://api.highcharts.com/highcharts#legend.itemMarginBottom) options were introduced in 2.2.0 version (on the right side you can find info: `Since: 2.2.0`), so this is not available in 2.1.x.
