### ISSUE TITLE
Highchart colors keep changing

### ISSUE THREAD

**Issue by arsinawaz** [highcharts/highcharts#5042]
Hi all,

I am using highcharts and the colors keeps changing when i refresh the chart with different data. Here is my theme object:

         Highcharts.theme = {
				colors: [
					// Main Colours
					/* '#1E73AA', '#C44441', '#55BF3B', '#7A5992',
					'#009AB2', '#F08736', '#8EAACF', '#CE7057', '#737373' */
					'#2691d9','#cf6563','#79cf63','#9d81b1','#33e4ff','#f39b58','#a6bcd9','#d78a75','#a6a6a6'
			   ],
				legend: {
					itemStyle: {
						font: '9pt Trebuchet MS, Verdana, sans-serif',
						color: 'black'
					},
					itemHoverStyle:{
						color: 'gray'
					}   
				},
				lang: {
					decimalPoint: ',',
					thousandsSep: ' '
				}
			};

			// Apply the theme:
			Highcharts.setOptions(Highcharts.theme);

It chooses the colors from the which i have provided but it keeps choosing dynamically. Is it possible to make it choose first color for first series and second color for second series and respectively.

Many thanks in advance.

**Comment by jon-a-nygaard** [comment]
@arsinawaz: Hi, I am not able to reproduce your issue. In my [example](http://jsfiddle.net/jon_a_nygaard/bjkjzmnv/) it will select the first color for the first series, and second for the second series, and so on. This is default Highcharts behaviour, which I believe is what you wish to accomplish.

Could you provide a live demo of your issue? [JSFiddle](https://jsfiddle.net/) works great for this purpose.

**Comment by arsinawaz** [comment]
@jon-a-nygaard  thankyou for the quick reply, i have tried to reproduce the issue but it seems that the issue is in the angular directive which i am using. Thanks.
