### ISSUE TITLE
defaultLabelFormatter Weird Behavior

### ISSUE THREAD

**Issue by jcbowman** [highcharts/highcharts#5044]
It looks like the defaultLabelFormatter will choose a single numeric symbol for an axis and continue to use that symbol for every value leading to odd situations where you end up with 1500K as a value on the axis. This could be abbreviated further as 1.5 M.

We've overridden the default formatter in our codebase to always put the most concise label on the axis as possible. Is there any interest in making the default formatter also work like that?

**Comment by jon-a-nygaard** [comment]
Hi @jcbowman,
Thanks for reporting. Could you provide us with a live example of what you are describing? It would be much appreciated. [JSFiddle](https://jsfiddle.net/) works great for this purpose.

**Comment by pawelfus** [comment]
I think this is the case: http://jsfiddle.net/m3dxjx8g/
Most probably expected [here](https://github.com/highcharts/highcharts/blob/e767da738d3677ffdd40b11ff4312b39d0e56717/js/parts/Axis.js#L391-L392).

However, I am not sure if we should change that logic. Currently there is an option [`yAxis.labels.formatter`](http://api.highcharts.com/highcharts#yAxis.labels.formatter) which can be used in case when default logic is not what one may require.

**Comment by TorsteinHonsi** [comment]
I guess it's a matter of preferences. Arguable, it is more readable when all the labels use the same abbreviation.

**Comment by jcbowman** [comment]
@pawelfus Thanks for providing an example - that's exactly the scenario I was describing. 

I think it's just a matter of preference as well. I just know that we received feedback from multiple groups within our organization that they would prefer more concise labels as I described. If you guy decide that you want the more concise labels let me know and I'll work on a pull request.

**Comment by TorsteinHonsi** [comment]
@jcbowman Did you expect mixed abbreviations like in the screenshot below, or would you expect all abbreviations to be M? In either case, it should be quite simple to implement.

![skjermbilde 2016-02-29 kl 10 28 46](https://cloud.githubusercontent.com/assets/227836/13390561/6f0ff104-decf-11e5-822c-5325808e5fb3.png)
