### ISSUE TITLE
Exporting - incorrect arabic text

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5047]
Example:
- http://jsfiddle.net/ma56u5g8/ 

1-  Internet Explorer, Version  11.0.9600.18015
        The issue in IE when I export to SVG the data labels are distorted

2- Google Chrome, Version 48.0.2564.103 m
        The issue in Chrome when I export to SVG the arabic word (التشغيل) is split into two Syllables (التشغي) and (ل).

3- Firefox, Version 43.0.4
        The issue in Firefox when I export to SVG the data labels are distorted

**Comment by TorsteinHonsi** [comment]
#### Workaround

Try setting `exporting.allowHTML`: http://jsfiddle.net/highcharts/ma56u5g8/7/

**Comment by moalshalabi** [comment]
I have checked the workarounds and I still have issues with them, please find below my feedback regarding each issue using different browsers: 

1- Internet Explorer: The issue in IE when I export to SVG the data labels are distorted, please check the attached file.

2- Firefox: The issue in Firefox when I export to SVG the data labels are distorted.

**Comment by larsac07** [comment]
> 1- Internet Explorer: The issue in IE when I export to SVG the data labels are distorted, please check the attached file.
@moalshalabi: Which file?

**Comment by larsac07** [comment]
> 3- Firefox, Version 43.0.4
The issue in Firefox when I export to SVG the data labels are distorted

@sebastianbochan How do you mean distorted? I see that the title and extra label are put too high, and that the lower right data label is wildly misplaced, but I can't reproduce any distortion. Below screenshot illustrate findings in online export to SVG, where the SVG is displayed in Firefox 43:
<img width="960" alt="screen shot 2016-09-20 at 14 46 46" src="https://cloud.githubusercontent.com/assets/5434502/18670642/38a3a10c-7f41-11e6-9816-c52f2c9231e9.png">

**Comment by sebastianbochan** [comment]
Chrome: 53.0.2785.116 
![zrzut ekranu 2016-09-20 o 14 54 54](https://cloud.githubusercontent.com/assets/2115686/18670889/3733baae-7f42-11e6-9f0b-50581cfa4ccd.png)

IE 11.103.14393.0 (win10): 
![zrzut ekranu 2016-09-20 o 14 55 14](https://cloud.githubusercontent.com/assets/2115686/18670901/41928476-7f42-11e6-9b6e-ae785f3076d6.png)

You can observe different size and misaligned / spacing in the top datalabel. Regarding to the right label, in my IE11 works correct.

**Comment by sebastianbochan** [comment]
+1

**Comment by larsac07** [comment]
@sebastianbochan Is the example image for FF 47.0.1 generated with @TorsteinHonsi's workaround? I get an entirely different issue with the right label not being visible at all:


<img width="626" alt="screen shot 2016-11-10 at 16 00 02" src="https://cloud.githubusercontent.com/assets/5434502/20181522/d3095846-a75e-11e6-8e96-c2bfe424a54a.png">

**Comment by larsac07** [comment]
Seems that the problem with the workaround from @TorsteinHonsi is that the generated `<foreignObject>` which contains the HTML labels is given a width and height of 200, which works in Chrome, but makes the `position: absolute`'ed label be rendered outside the `<foreignObject>` and therefore invisible in Firefox.

The fix should set the width and height of the `<foreignObject>` to the same as the parent `<svg>`

**Comment by larsac07** [comment]
When it comes to the original problem: If `useHTML` is applied to any labels, and their formats use html tags, what happens is that HTML is added outside the SVG.

To include that content in a standalone SVG file we would either have to:

1. Force `exporting.allowHTML` to include the HTML elements, or
2. Force removal of `useHTML` and strip the labels of html-tags

**Comment by larsac07** [comment]
Regarding the rightmost label in FF: The issue can be simulated without exporting by opening http://jsfiddle.net/larsac07/5hwagpqp/ (with HTML tags) or http://jsfiddle.net/larsac07/jbeL5age/ (without HTML tags) in Firefox, which are the same as the [original example](http://jsfiddle.net/ma56u5g8/), except `useHTML` is removed.

The problem seems to be with Highcharts label rendering.
