### ISSUE TITLE
Zoom Y stops working with a Y axis that has tickPosition or tickPositioner set

### ISSUE THREAD

**Issue by dejongch** [highcharts/highcharts#5049]
http://jsfiddle.net/3tbsLtab/

The X zooming still seems to work fine in these cases.

**Comment by jon-a-nygaard** [comment]
Thanks for reporting. We will have a look at this as soon as possible.

**Comment by pawelfus** [comment]
Just a quick thought: http://jsfiddle.net/3tbsLtab/1/ - personally, I like the way current `tickPositioner` works. It allows to modify extremes, like using `minRange` or `min/maxPadding` with better flexibility: http://jsfiddle.net/3tbsLtab/2/

**Comment by dejongch** [comment]
tickPositioner is probably fine as it is since it has flexibility. I think my issue is that there tickPosition on the Y and just the fact the X and the Y behave differently.

**Comment by jon-a-nygaard** [comment]
I agree, zooming should behave the same on both axes (when `zoomType `is xy), whether or not the `tickPositioner `or the `tickPositions `is used.
