### ISSUE TITLE
series.setData causes SVG error in highmaps

### ISSUE THREAD

**Issue by ranair** [highcharts/highcharts#5050]
If map is created and data added immediately using setData, It causes bunch of errors in console log.
Sample error:

 *Error: Invalid value for <path> attribute d="M 13.083870967741936 270.0354838709677 L 14.090322580645163 270.17926267281103 14.30599078341014 270.5387096774193 13.299539170506913 270.39493087557605 12.508755760368665 269.89170506912444 12.07741935483871 269.9635944700461 11.502304147465438 269.38847926267283 12.364976958525347 269.2447004608295 13.083870967741936 270.0354838709677 Z 13.083870967741936 270.0354838709677 Z 13.083870967741936 270.0354838709677 Z"*

This seem to happen in chorme, not in firefox.
Here is the code snippet.
Steps to reproduce:
Go to world with Palestine highres: map collection form Highmaps doc.
http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/custom/world-palestine-highres

Replace the java script the one below.
Run and look at the JS console in chrome:
```js
$(function () {
  // Initiate the chart
    $('#container').highcharts('Map', {

        title : {
            text : 'Highmaps basic demo'
        },

        mapNavigation: {
            enabled: true,
            buttonOptions: {
                verticalAlign: 'bottom'
            }
        },

        colorAxis: {
            min: 0
        },

        series : [{
            data : null,
            mapData: Highcharts.maps['custom/world-palestine-highres'],
            joinBy: 'hc-key',
            name: 'Random data',
            states: {
                hover: {
                    color: '#BADA55'
                }
            },
            dataLabels: {
                enabled: true,
                format: '{point.name}'
            }
        }]
    });
});
$(function () {
    var data = [
        {
            "hc-key": "us",
            "value": 1000
        },
        {
            "hc-key": "in",
            "value": 10000
        },
    ];

    // Initiate the chart
    $('#container').highcharts().series[0].setData(data);
});
```

**Comment by jon-a-nygaard** [comment]
Thanks for reporting. We will have a look at this as soon as possible.

**Comment by pawelfus** [comment]
Looks like connected to #3440

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi and @oysteinmoseng remember to check if the issue that Pawel referenced can be closed by this fix :wink:

**Comment by oysteinmoseng** [comment]
@jon-a-nygaard: Unfortunately it seems to be unrelated
