### ISSUE TITLE
$(window).resize() not work after 4.2.1

### ISSUE THREAD

**Issue by yutingzhao1991** [highcharts/highcharts#5051]
Sometimes I want trigger highcharts chart resize, such as : [highcharts-hidden-charts-dont-get-re-size-properly](http://stackoverflow.com/questions/16216722/highcharts-hidden-charts-dont-get-re-size-properly) , before version 4.2.1 I use `$(window).resize()` , But It did not work now.

**Comment by oysteinmoseng** [comment]
We have a method `Chart.reflow()` for this: http://api.highcharts.com/highcharts#Chart.reflow. Assuming the container div gets resized, calling this method should resize the chart to the div.

**Comment by envision** [comment]
I'm having this same problem.

@oysteinmoseng as we have so many charts in our app and instantiated at lower scope level, is there are way to reflow all chart instances at once?

http://stackoverflow.com/questions/39641532/highcharts-reflow-all-charts-at-once-trigger-resize-event-in-angular

**Comment by oysteinmoseng** [comment]
@envision Yes, the [Highcharts.charts](http://api.highcharts.com/highcharts/Highcharts.charts) array contains all charts on the page. You could loop over it and call reflow on each defined element.
