### ISSUE TITLE
3d - multiple yAxis - issue with overlapping and offset

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5052]
Example: http://jsfiddle.net/scottszb1987/2m4q95df/3/

The problem is that labels overlap. To solve the problem we can use offset / labels x parameters but then, distances seem to be still incorrect.

Examples: 
- http://jsfiddle.net/653wzLa3/
- http://jsfiddle.net/pzt81skx/

**Comment by pawelfus** [comment]
Last working version was 4.0.4: http://jsfiddle.net/2m4q95df/4/

Responsible commit: cfb97399d63255705e76ead6a8e27eb55c3c48d3
Related ticket: #3788

**Comment by sdom** [comment]
+1

Related example: https://jsfiddle.net/uc3w2zpb/1/
It seems to be related with provided data - inserting higher values moves the yAxis to the right

**Comment by TorsteinHonsi** [comment]
Looks like #3788 is not a bug after all, the labels are supposed to sit just to the right of the tick marks. And the fix is nonsense, it looks at yAxis.transA which depends on the magnitude of the data. So I'm just removing the fix.
