### ISSUE TITLE
Image in custom button in exporting.buttons disables chart's responsiveness

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5053]
**Problem:** If in `exporting.buttons.customButton.symbol` image is used, then chart doesn't reflow its container after window resize. Also:
- redraw event in `chart.events.redraw` is not triggered after window resize.
- load event is not triggered
- callback runs twice

**Example:** http://jsfiddle.net/aya7yecs/1/

**Steps:** see browser console and resize a window

**Fails since:** https://github.com/highcharts/highcharts/commit/f2300c9

**Workaround:** [Use Highcharts v.4.2.1](http://jsfiddle.net/aya7yecs/2/)

**Comment by pawelfus** [comment]
Another test-case for using images, broken since 4.2.2: https://jsfiddle.net/wzgh39nk/2/ 

Recreate chart and navigator will be missing.

**Comment by TorsteinHonsi** [comment]
Pawel's test case can be simplified to http://jsfiddle.net/highcharts/uy6L3nfo/. 

*Steps*:
1. Run with the console open, and observe that callback and load run sucsessfully.
2. Click Build again. This time, callback and load don't run.
3. Comment out the symbol marker and repeat the steps, now the functions run as expected.
