### ISSUE TITLE
Incomplete Chart after rebuild with url marker

### ISSUE THREAD

**Issue by marcogruhl** [highcharts/highcharts#5054]
Hi,

with version 4 of Highstock there is an issue with rebuilding the chart and series markers. I prepared a little fiddle: http://jsfiddle.net/am4orpbd/ to showcase it.

The upper chart uses url marker and doesn't show the range selector after rebuild the chart (with the button in between)
The lower chart WITHOUT url marker works as expected.

regards,
marco

**Comment by jon-a-nygaard** [comment]
Thanks for reporting, we will look into this as soon as possible.

**Comment by pawelfus** [comment]
Works fine in 4.2.1: http://jsfiddle.net/am4orpbd/1/

Looks like connected to #5053 (loading image in the chart).

**Comment by pawelfus** [comment]
Works fine since 4.2.4
