### ISSUE TITLE
HighStock drawing data at "Daylight saving time" end time issue

### ISSUE THREAD

**Issue by JoryOne** [highcharts/highcharts#5057]
Hi,
Now We've got an issue, Some countries use daylight saving time, like Berlin(UTC+1:00), in this country, Daylight Saving time  ends on Sunday,October 30,every year at 3:00 AM,The clock will set to go back 1 hour at that time, that is to say, after time 2:59:59 is not 3:00:00, but will be 2:00:00, In HighStock  x-Axis, we will see two o’clock, but we know the old 2 o’clock is in Daylight Saving Time.

In my code of highStock config, x-Axis type property is “datetime”
HighStock Version :2.1.7.

Bug 1: Daylight Saving Time  end time will cause Chrome to crash,(this bug have been solved in Version 2.1.8, #4477),now the browser not crash ,but will using 
very long time  to drawing the chart when refresh the browser.
Bug 2:  The new data drawing at the old 2 o’clock but the new 2 o’clock, you can see this bug in the attachment #4477

**Comment by oysteinmoseng** [comment]
Thank you for reporting. Are you able to provide a jsFiddle example showing the issue? The issue #4477 does not seem to have anything to do with daylight savings time?

**Comment by JoryOne** [comment]
Hi,
JsFiddle :  http://jsfiddle.net/jm00xbgn/

If you want to reproduce the bug, please set  time zone to  Berlin(UTC+1:00), then change the time to the last hour of Daylight Saving Day,  2:59:00 ,10/30/2016 ,  wait 1 minute, you will find  the time will 
 in this country, October 30,every year at 3:00 AM,The clock will set to go back 1 hour:2:00:00, but you know this 2 o'clock is in Standard  Time, then open  Chrome debug page, set a break point at line 9252:   tickPositions.push(time);
In the console print  "minDate" and  "Date(minDate)", you will see "minDate" is: Sun Oct 30 2016 02:00:00 GMT+0200 (Central Europe Daylight Time)
but "Date(minDate)"
"Sun Oct 30 2016 02:03:01 GMT+0100 (Central Europe Standard Time)", do you think minDate is Daylight Time is right? after all this 2 o'clock is in Standard Time, and you will find tickPositions    length is too long . This is the Bug 1 root cause, (This Demo have some different from my actual code, but by my debug,I found the root cause at there)

And for Bug2, I had fixed it, the root cause is in mine code.

**Comment by JoryOne** [comment]
BTW, after you open Chrome debug page, please refresh the page.

**Comment by JoryOne** [comment]
The file is "highstock.src.js"   :  line 9252     tickPositions.push(time);
