### ISSUE TITLE
DateFormat for %e not consistent with php strftime

### ISSUE THREAD

**Issue by maniax89** [highcharts/highcharts#5060]
The documentation states that the date formatting engine used in highcharts is based off of a subset of PHP's strftime:

From docs at http://api.highcharts.com/highcharts#Highcharts.dateFormat
> The format is a subset of the formats for PHP's strftime function.

However, on http://php.net/manual/en/function.strftime.php it states the the ``%e`` format should return a:
> Day of the month, with a space preceding single digits.

It seems there is an inconsistency here. Doesn't seem like a huge issue but as you can see from this [fiddle](http://jsfiddle.net/1ck9zfve/1/) the single days are _not_ space-padded. Could we either

- Modify the documentation to reflect this inconsistency or
- Update the code to implement it as documented

I found this when trying to use the same date formats in a rails project in addition to highcharts. Rails implements the ``%e`` format with spaces padding single days. I am considering just writing a custom dateFormat to do this but wanted to reference this issue in case it is fixed in some way.

Great project though! Very easy to use.

**Comment by oysteinmoseng** [comment]
Thanks for reporting, we should be consistent here.
