### ISSUE TITLE
Highmaps: Map Collection does not have world map with disputed areas

### ISSUE THREAD

**Issue by GaneshBChandgude** [highcharts/highcharts#5061]
The world map provided in Map Collection does not show disputed areas of countries. It would be really helpful if the disputed area of Jammu & Kashmir state is shown as part of India in world.json

India with Jammu & Kashmir:
[http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/in/custom/in-all-disputed](url)

World Map with a part of Jammu and Kashmir missing from India:
[http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/custom/world-lowres](url)

**Comment by oysteinmoseng** [comment]
Thank you for your suggestion, but this site is intended for bug reports only. For feature requests - including new maps - please post your comments at https://highcharts.uservoice.com.

**Comment by oysteinmoseng** [comment]
Reopening as we have since added a world map with Palestine areas (http://jsfiddle.net/gh/get/library/pure/highslide-software/highcharts.com/tree/master/samples/mapdata/custom/world-palestine), and we probably want to do the same for India.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#4

**Comment by ajitrishabh** [comment]
@oysteinmoseng  what is the status on disputed area of india map in world map.
as the indian customer are not happy if they see Jammu & Kashmir are not a part in india in world map.
see the image below.
or else let me know how i can add there area in to india map coordinates

![image](https://user-images.githubusercontent.com/7721618/84490361-b050b900-acc0-11ea-9543-77bca20b1dbd.png)

**Comment by oysteinmoseng** [comment]
@ajitrishabh Please refer to the new issue: https://github.com/highcharts/map-collection-dist/issues/4
