### ISSUE TITLE
Firefox 44.0.2 problem with renderer.image if image was scaled

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5062]
Using renderer.image in Firefox 44.0.2 is causing some problems. Rendered image looks bad in comparison with the same image added via HTML img tag. It looks like this is connected with firefox smooth method. 

If image in img tag is having option image-rendering: optimizespeed, it looks like both of images have quality issues. 

I have not observed this issue in other browsers.
Here is an example from Google Chrome:
![comparison](https://cloud.githubusercontent.com/assets/15050812/13180588/62634026-d729-11e5-99b8-2e8c4f077d5b.png)

And here from Firefox 44.0.2
![comparison firefox](https://cloud.githubusercontent.com/assets/15050812/13180651/9d33eeda-d729-11e5-8213-283b5317e516.png)

**Comment by TorsteinHonsi** [comment]
Confirmed, Firefox draws the image without resampling: http://jsfiddle.net/highcharts/u8b5dhpf/

**Comment by TorsteinHonsi** [comment]
The logical thing to do according to [SVG docs](https://www.w3.org/TR/SVG/painting.html#ImageRenderingProperty), would be to set `image-rendering` to `optimizeQuality`. But it doesn't help: http://jsfiddle.net/u8b5dhpf/1/.

**Comment by KacperMadej** [comment]
The issue is still visible. Firefox version 62.0.3
Demo: http://jsfiddle.net/BlackLabel/u8b5dhpf/6/

Is this a browser issue with SVG and images?
No Highcharts demo: http://jsfiddle.net/BlackLabel/u8b5dhpf/7/
