### ISSUE TITLE
Solid gauge tooltip doesn't display hoverd series info for the first time

### ISSUE THREAD

**Issue by erita** [highcharts/highcharts#5063]
The problem occurs at your demo demo page http://www.highcharts.com/demo/gauge-activity .

Hover the graph for the first time at series 'Exercise' or 'Stand', tooltip display 'Move' information.
This problem does not occurred hover 'Move' for the first time or next time hover graph after occurred problem and mouse out that series.
Why tooltip doesn't display right info only first time ?

**Comment by jon-a-nygaard** [comment]
Thanks for reporting. We will have a look at this as soon as possible.

_Internal Note: Somehow the first series is always displayed in the tooltip on the first hover._
