### ISSUE TITLE
xAxis.crosshair.snap option missing from Highmaps API documentation

### ISSUE THREAD

**Issue by tomascassidy** [highcharts/highcharts#5064]
The Highcharts API documentation includes the [Axis.crosshair.snap](http://api.highcharts.com/highcharts#xAxis.crosshair.snap) option, but this is missing from the equivalent [Highmaps API documentation](http://api.highcharts.com/highmaps#xAxis.crosshair).

**Comment by jon-a-nygaard** [comment]
Thanks for letting us know, will fix this as soon as possible.

**Comment by TorsteinHonsi** [comment]
Fixed, thanks!
