### ISSUE TITLE
Advanced lat/long demo has incorrect crosshair configuration

### ISSUE THREAD

**Issue by tomascassidy** [highcharts/highcharts#5065]
The [api docs](http://api.highcharts.com/highmaps#tooltip.crosshairs) state that crosshair configuration has moved to the Axis object, but [this demo](http://www.highcharts.com/maps/demo/latlon-advanced) still applies it to the tooltip object.

**Comment by jon-a-nygaard** [comment]
Thanks for letting us know, we will fix this as soon as possible.
