### ISSUE TITLE
How to create such pie chart/ donut chart in highchart? - help

### ISSUE THREAD

**Issue by video-internal** [highcharts/highcharts#5067]
Hi Pawel,

I have just begun working on highchart and stuck very badly.I have posted question on stackoverflow also. Can anyone please help me?

http://stackoverflow.com/questions/35540685/how-to-create-such-pie-chart-donut-chart-in-highchart

I will be very thankful if anyone can help me with these 2 questions.

**Comment by pawelfus** [comment]
Hi @video-internal ,

We use github as our bug tracker. A little more patience, someone will answer you soon :)

Best Regards,
Paweł Fus

**Comment by video-internal** [comment]
Hi Pawel,

Sorry. I didn't know that. Someone has indeed answer me. But, I have few queries on which I am also working. If possible, can you please look at stackoverflow or highchart forum? I would be very thankful to you.
