### ISSUE TITLE
Bar chart printinting issue in MozilIa FireFox 40.0.3 and IE8

### ISSUE THREAD

**Issue by thario** [highcharts/highcharts#5069]
When printing a bar chart with a lot of values (more than 100), after the page break nothing is getting printed in the paper with FireFox 40.0.3 browser. And also in IE8 for the same chart in the printed page the xAxis label and data labels are invincible (I think the label are rendered with white color). 
I am using HighCharts 4.2.1
here is the jsfiddle :  http://jsfiddle.net/utLob9jh/3/
here the result:   http://fiddle.jshell.net/utLob9jh/3/show/

**Comment by oysteinmoseng** [comment]
Is this an issue with PDF export, or are you printing the webpage directly from the browser?

**Comment by thario** [comment]
I am printing the webpage directly from the browser

**Comment by thario** [comment]
@oysteinmoseng have you had any chance of looking into this issue, it is time critical.

**Comment by oysteinmoseng** [comment]
Using our [export module](http://jsfiddle.net/utLob9jh/4/) PDF export seems to be working fine.

If the browser is cutting off the SVG element when printing a page, I'm afraid there is nothing we can really do about that. It would be a bug in the browser.
