### ISSUE TITLE
highcharts prevent container being resized

### ISSUE THREAD

**Issue by rubyisapm** [highcharts/highcharts#5070]
I use flex layout in my project, the chart's container is one of the subs of the flex container. Like as following:

```
<div id="flexContainer">
  <div id="firstSub">
  //another container
  </div>
  <div id="chartContainer">
  // chart's container
  </div>

</div>
```

On the page, user can resize the firstSub. 
The problem is:
If the chart hasn't been rendered when resizing the firstSub, the chartContainer would follow the operation, but if the chat has been rendered when resizing the firstSub, the chartContainer wouldn't follow the operation. Like the chart prevents its container being resized( like it says: don't touch me!－_－!!)

**Comment by oysteinmoseng** [comment]
Could you reproduce this issue in a jsFiddle demo?

**Comment by TorsteinHonsi** [comment]
Also see #4649

**Comment by rubyisapm** [comment]
https://jsfiddle.net/rubyisapm/L5ftoctr/

**Comment by rubyisapm** [comment]
https://jsfiddle.net/rubyisapm/L5ftoctr/          
This is the demo, you can click the button, you would find that the chart won't resize itself and seems like it prevent the left div to change the size. Thank you for your time.

**Comment by TorsteinHonsi** [comment]
By setting the width of the container and the SVG, as well as calling `chart.reflow` after your modification, it seems to work: https://jsfiddle.net/highcharts/L5ftoctr/3/

**Comment by rubyisapm** [comment]
Thank you so much for helping me out. @TorsteinHonsi :-)

**Comment by rubyisapm** [comment]
Another problem, poor me!! See here: https://jsfiddle.net/rubyisapm/L5ftoctr/5/  

first, hide the right container
after that, resize the left div
then, show the right container

you'll find the chart can't adapt the change. Even through I added the $(window).resize(), it didn't work either. Thank you

**Comment by TorsteinHonsi** [comment]
Does it help if you run `chart.reflow()`?

**Comment by rubyisapm** [comment]
No, it doesn't work. But I found another way to fix it: I set the iframe's width from 100% to 99.9%, and it would trigger the iframe to resize itself, then the chart could reflow correctly. But if the chart is rendered in the main window, I'm afraid there hasn't no way I can think out to fix by now.

**Comment by sebastianbochan** [comment]
You can try to call the setSize() method, which extracts width from container. 
https://jsfiddle.net/da7cnfxe/
