### ISSUE TITLE
highchart - slicedoffset on mouseover-mouseout getting stuck

### ISSUE THREAD

**Issue by video-internal** [highcharts/highcharts#5072]
Hi,
1. I have used mouse over - mouse out events for slicing out pie chart in high chart. But sometimes, those events gets stuck and even after mouse out, slicedoffset isn't removed.

This occurs if you do mouseover-mouseout in speed and over two consecutive slices from left to right or vice-versa.
1. If apply distance to individual level-1 series datalabel then it doesn't get apply but if I use distance - common for all level-1 datalabel then it is working correctly.
2. Level-1 series data label - HIGH, CRITICAL and MODERATE aren't shown in one div structure. Two of them are shown in g - text - tspan tag n other one is shown as div- span. If you observe it using developer tool then can see this thing. Is there any specific reason behind this issue?

Fiddle - http://jsfiddle.net/3v3xfh6e/9/

Can you help me for these issues?

**Comment by TorsteinHonsi** [comment]
Thanks for the report! Please keep in mind that this is our bug tracker, so for general support please see www.highcharts.com/support.

Your point 1 seems to be a bug. @jon-a-nygaard It seems that the mouseout/over isn't triggered when moving directly from one slice to another slice's data label. Try to reduce the demo by removing redundant configuration. Pie series has `trackerGroups: ['group', 'dataLabelsGroup']`, so it should treat the data labels as trackers.

**Comment by video-internal** [comment]
@TorsteinHonsi  - Could you please elaborate what I should do to avoid this issue?

**Comment by TorsteinHonsi** [comment]
Yes, we are handling it as a bug, so my colleage will try to find a fix. Apart from that I am afraid I can't think of a workaround.

**Comment by pawelfus** [comment]
I think this is caused by `useHTML` in dataLabels. When removed it works fine: http://jsfiddle.net/3v3xfh6e/13/

In that case it would a duplicate of #3398

**Comment by video-internal** [comment]
@pawelfus - I think you are right. I have removed default height from span because I can't remove useHTML:true and effect is working correctly. Here is the fiddle:

http://jsfiddle.net/3v3xfh6e/14/
