### ISSUE TITLE
Polar chart - setting yAxis extremes

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#5073]
Examples: 
- http://jsfiddle.net/jawq31bh/5/
- http://jsfiddle.net/jawq31bh/4/

It would be great to have clip-path for series, so line won't sneak out of the plotting area.

**Comment by TorsteinHonsi** [comment]
_Internal note_:

It would be equivalent to the clipping rectangle of normal cartesian charts.

**Comment by KacperMadej** [comment]
Unable to recreate using version 6.1.4.
Closing as implemented and resolved.
