### ISSUE TITLE
Click event with shared tooltip

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#5074]
Example: http://jsfiddle.net/47p2zajL/2/

Try to click on "Jane" series. It works fine, when not using shared tooltip. 

Responsbile commit: 38d142a

**Comment by zorab47** [comment]
I'm seeing this issue too. It appears to only interfere with click events when points from the two series are overlapping. When that occurs only the "higher" (or first defined) series receives the event.

**Comment by pawelfus** [comment]
Works fine since 4.2.4: http://jsfiddle.net/47p2zajL/4/

@zorab47 - I think the way it works make sense (just like any HTML elements: when two of them overlaps, then only one with higher z-index gets events?). If you think the logic should be changed, I guess you should create a separate issue.
