### ISSUE TITLE
Data labels with useHTML - display is not deferred

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5075]
**Problem:** dataLabels are visible from before initial animation and then they blink.
This is visible when `dataLabels` have `useHTML: true` and pie has set `size`

**Example:** http://jsfiddle.net/ayw4ajzg/

**Comment by TorsteinHonsi** [comment]
It's not only pies: http://jsfiddle.net/highcharts/ayw4ajzg/1/

**Comment by video-internal** [comment]
Should I just use highcharts.js and exporting.js latest versions and this issue will be solved. Am I right?

**Comment by TorsteinHonsi** [comment]
​No, the fix hasn't been published yet, just pushed to the repo. See
https://github.com/highcharts/highcharts/blob/master/repo-guidelines.md#apply-a-fix
.

**Comment by video-internal** [comment]
I'm not able to open http://i-tools.org/diff 

can anyone help me?

**Comment by TorsteinHonsi** [comment]
Okay, the easy way is: 
1. Open your copy of highcharts.src.js v4.2.3 in a text editor.
2. Open https://github.com/highcharts/highcharts/commit/81e9bbfcec8e52e49910e679497b1de6666b49d2, and see what has changed in highcharts.src.js. 
3. Perform those changes to your copy of highcharts.src.js.

**Comment by video-internal** [comment]
@TorsteinHonsi  - I'm using highcharts.js so I can't see anything like htmlGroup

I have used this version - https://code.highcharts.com/highcharts.js

**Comment by TorsteinHonsi** [comment]
Then you must use https://code.highcharts.com/highcharts.src.js and optionally go to the [Closure Compiler web service](https://closure-compiler.appspot.com/) to compile it.

**Comment by video-internal** [comment]
@TorsteinHonsi - I used that version of js fie and found where I have to enter that patch, but I'm unable to compile the file using the web service you provided. I just get something went wrong page.

I just copied and pasted whole js file after editing there

**Comment by TorsteinHonsi** [comment]
I think you need to host it online and point the closure compiler to the location - it's all explained on the compiler web service.

**Comment by video-internal** [comment]
@TorsteinHonsi - thank you for help
