### ISSUE TITLE
Logarithmic inverted yAxis

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#5076]
Example: http://jsfiddle.net/qrjq4s50/4/

(Or for a "live" demo, remove `min-width` and resize browser to be at least 2560px - then we will get an error: `Error: Invalid value for <text> attribute x="-Infinity"`).

Happens because `getLogTickPositions` calculates tick at `0` position. 

**Workaround:**
Use `yAxis.tickPositioner` and clean up that `0`/`-Infinity` tick: http://jsfiddle.net/qrjq4s50/5/

**Comment by TorsteinHonsi** [comment]
It's also not specific to inverted axis, but to the length of the axis. 

More simplified: http://jsfiddle.net/highcharts/qrjq4s50/6/

**Comment by TorsteinHonsi** [comment]
In the `getLogTickPositions` function, the Y axis falls into case 3, which seems wrong for this axis. If we remove the first, `-Infinity` tick, the tick layout still feels wrong. It should have been case 2 layout. Maybe we need to consider the length of the axis as well as the interval.

**Comment by KacperMadej** [comment]
Unable to recreate using version 6.1.4.
Closing as resolved.
