### ISSUE TITLE
Point markers not visibly selected after zooming

### ISSUE THREAD

**Issue by kernc** [highcharts/highcharts#5077]
1. Have two scatter plot series, one small (100 points), one large (1000 points).
2. Select some points from each series (with accumulation by holding Shift).
3. Rectangle-zoom to the area that contains the selected points from both series.

BUG: Observe how only the scatter points of the _smaller_ series retain their selection style (stroke and fill).

Instead, all series' points should remain selected.

http://jsfiddle.net/b7gg8a35/1/

It appears the points still remain selected (`chart.getSelectedPoints().length` reports the initial, correct size of the selection), only their fill and stroke styles are reset.

**Comment by kernc** [comment]
Ok, setting `plotOptions.series.turboThreshold=0` [did it](http://jsfiddle.net/b7gg8a35/2/). This is still an issue, though, as the example inputs series' data in basic x–y form, so according to [documentation](http://api.highcharts.com/highcharts#plotOptions.series.turboThreshold), `turboThreshold` should play no effect. What is documented seems to not be all `turboThreshold` does.

**Comment by pawelfus** [comment]
Thank you for reporting. 

You are right, we have second checking for `turboThreshold` [here](https://github.com/highcharts/highcharts/blob/1aacf2433fb94b1658300616fd442f82b774f9c5/js/parts/Series.js#L1093). 

**Internal note:**
Can we reuse `hasPointSpecificOptions` option? I mean, in `Point.select` we can set this flag to `true` - as I can see it is done for a `heatmap` already.

**Comment by TorsteinHonsi** [comment]
Yes, that should be safe.

**Comment by KacperMadej** [comment]
Unable to recreate using version 6.1.4.
Closing as resolved.
