### ISSUE TITLE
DataGrouping smoothed without points

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#5078]
Demo: http://jsfiddle.net/wakrnxyf/

Click on "Year" then on "Month". We get error in js console:

> Uncaught TypeError: Cannot read property 'info' of undefined

Connected to `smoothed` option here: https://github.com/highcharts/highcharts/blob/1aacf2433fb94b1658300616fd442f82b774f9c5/js/parts/DataGrouping.js#L313

In short, `groupedXData.length` is equal to zero, so `groupedXData[i]` will add point to the array with index = `-1`. Maybe there should be `i = Math.max(groupedXData.length - 1, 0);` or something similar.

**Comment by TorsteinHonsi** [comment]
> Maybe there should be i = Math.max(groupedXData.length - 1, 0); or something similar.

Yes, or `if (groupedXData.length) {`, I'll leave it up to the assignee to find the most efficient variety.

**Comment by TorsteinHonsi** [comment]
@pawelfus, Øystein is snowed under, can you handle this?

**Comment by pawelfus** [comment]
Somehow I missed this topic. It works in the current version, should we anyway change this? @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
If it works, don't touch it :)
