### ISSUE TITLE
Problem with Highcharts axis titles on IE8 since 4.2.2 release

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5079]
Since 4.2.2 release of Highcharts, some charts are not rendered correctly when using IE8. 
The issue is connected with lack of axis titles. For an example of this issue you can use chart from Highcharts demos.

Here you can see chart in Google Chrome browser:
![image](https://cloud.githubusercontent.com/assets/15050812/13323665/c109402a-dbda-11e5-956c-597e0a74795d.png)

And here is chart from IE8:

![image](https://cloud.githubusercontent.com/assets/15050812/13323619/9248c86e-dbda-11e5-8c9e-cb57e91b13b7.png)

Inside the example from IE8 the title of yAxis is not visible

**Comment by TorsteinHonsi** [comment]
Fails since 8456723

**Comment by TorsteinHonsi** [comment]
Minimal demo: http://jsfiddle.net/highcharts/jzepxsns/show
