### ISSUE TITLE
Highmaps issue in rendering a particular region

### ISSUE THREAD

**Issue by maheshjag** [highcharts/highcharts#5081]
See this: https://jsfiddle.net/maheshjagadeesan/odL28j0z/

The chart options used here were captured from our application, and the mapData was generated in an identical manner in both cases. The only difference in the series data was that Australian Capital Territory was moved around (in variable y, it was at the top of the list, and in variable x, it was not).

Notice that the Australian Capital Territory region is shown (bottom right of the chart, small orange-coloured area within the blue).

If you uncomment the line starting with 

    var y = 

you'll notice that the ACT region has vanished!

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

Unfortunately I can't see the problem, I can't see anything in the bottom right area, and there is no line starting with `var y =`...

**Comment by maheshjag** [comment]
Sorry, my fault - I was playing around in the Fiddle after posting it here!

You should see the line I was referring to in my comment above, around lines 373/374.

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng Apparently our map data is missing a hole in New South Wales. Is that a bug, or is it required to put enclaves on top of the surrounding area?

Interestingly, it seems we've got it right for Lesotho/South Africa: http://jsfiddle.net/highcharts/zv1dujmp/

**Comment by maheshjag** [comment]
@TorsteinHonsi @oysteinmoseng I don't know if this will help, but we observe this issue in our application only when we supply ACT as the first item in the series data. If it's moved to anything other than the first, there's no issue whatsoever.

**Comment by TorsteinHonsi** [comment]
@maheshjag Yes, the items are drawn back to front, and since there is no "hole" in the New South Wales item, it hides the ACT enclave.

**Comment by oysteinmoseng** [comment]
This is not really a bug, but an issue with the mapdata as @TorsteinHonsi mentions. Our [mapdata](http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/au/au-all) for Australia has a "hole" for the capital territory, so you could try using that instead.
