### ISSUE TITLE
Error generating code (Builder) when adding Heatmap

### ISSUE THREAD

**Issue by josecanciani** [highcharts/highcharts#5084]
Hello. I'm using the Builder to generate my js file. When I add the Heatmap module, the generated JS has errors (and thus the compiled version cannot be generated).

Builder options:

Core
* Core
Features
* HTML
* Stacking
* Data labels
Dynamics and Interactions
* Tooltip
* Touch
* Dynamics
Charts and Series types
* Line
* Area
* Bar
* Pie
* Gauge
* Funnel
Modules
* Exporting
* No data to display
* Solid Gauge
* Headmap => THIS IS WHAT BREAKS IT

Thanks,
Jose

**Comment by TorsteinHonsi** [comment]
_Internal note:_

In the assembled file, the heatmap loaded is v4.1.9, so something is not updated. When fixing this, add the missing file(s) to the website repo, but also check the `copy-to-download-builder` script to make sure that it doesn't happen again.

**Comment by jon-a-nygaard** [comment]
@josecanciani Thanks for reporting, the download builder should work as expected now. Please let us know if you experience any other issues with it.

_Internal Note: In parts.js the Heatmap intro file was named as Intro, causing the builder to look for a not existing file. The correct name was HeatmapIntro._

**Comment by josecanciani** [comment]
Thanks! I'll let you know if I found something else, but for now, closed! :)
