### ISSUE TITLE
Tooltip shows for invisible points

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5085]
Steps to reproduce:
1) http://jsfiddle.net/70bpbaj2/
2) move handles to have timeframe between 03.10.2013 and 06.11.2013
3) Tooltp appears for invisible points

notes: 
- call setExtremes / use inputs show values properly

![scre](https://cloud.githubusercontent.com/assets/2115686/13424818/4c2a2f7c-dfa3-11e5-8faf-fc6cc6407664.png)

**Comment by TorsteinHonsi** [comment]
Normalized, programmatically zooming in: http://jsfiddle.net/highcharts/70bpbaj2/2/

**Comment by sebastianbochan** [comment]
+1

**Comment by TorsteinHonsi** [comment]
More simplified. Tooltip is reachable for point on x = 5: http://jsfiddle.net/highcharts/4Lxeb480/

**Comment by pawelfus** [comment]
How about doing the same for y-dim? Related issue: #3916.

**Comment by bozhkoms** [comment]
Thanks for the fix! In which release version of Highstock it would be available, in the next one or maybe later?

**Comment by TorsteinHonsi** [comment]
It will be available in the next release.
