### ISSUE TITLE
xAxis labels overlapping when added via addSeries

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5086]
Hi,

When chart is having one series, added via Chart.addSeries(), it looks like labels are overlapping if they are long (instead of using ellipsis). When this series will be added inside chart options, everything works fine. You can find examples below:

Here is an example how chart looks after adding series by Chart.addSeries:
![image](https://cloud.githubusercontent.com/assets/15050812/13427991/cb0f20c2-dfb7-11e5-9f32-7fbb6fa08b62.png)

jsFiddle example:
http://jsfiddle.net/cune5qs5/12/

Here is an example how chart looks if series is inside chart.options:
![image](https://cloud.githubusercontent.com/assets/15050812/13428043/2d37a7a6-dfb8-11e5-9cd4-bb559d3706e4.png)

jsFiddle example:
http://jsfiddle.net/cune5qs5/13/

Update: It looks like this problem is present since 4.1.0 version of Highcharts. In version 4.0.4 functionallity is different, but it looks like overlapping is correctly detected.

Kind regards.

**Comment by tregoning** [comment]
Wow that was fast!

**Comment by TorsteinHonsi** [comment]
You're welcome!
