### ISSUE TITLE
Y' Axis - not able to set axis values to be constant

### ISSUE THREAD

**Issue by manju4ever** [highcharts/highcharts#5089]
I have created a multiple axes (Y-axes) graph, indicating different counts. So i want to reduce the extra lines being shown.

![high_chart_multi_axes](https://cloud.githubusercontent.com/assets/9355984/13439279/caff4f20-e012-11e5-921b-605187e7a651.png)

**Comment by TorsteinHonsi** [comment]
Thanks for writing! Please note that this is our bug tracker. For general tech support, see www.highcharts.com/support.
