### ISSUE TITLE
Callback to modify or override Boost point rendering

### ISSUE THREAD

**Issue by brian428** [highcharts/highcharts#5090]
Here's a proposed enhancement: accept a callback that can override how points are rendered when using the Boost module. Currently, there's no way to affect the drawing of individual points (changing color, size, etc.).

Locally, I've added an optional callback that allows for this. If it returns false, the default point render is skipped. I did this by modifying the Boost module to add the following:

``` javascript
// boost.src.js, line 479
// Pass any additional point data to drawPoint()
var pointData = null;
if( Array.isArray( d ) && d.length == 3 ) {
  pointData = d[ 2 ];
}
drawPoint(clientX, plotY, yBottom, pointData);
```

``` javascript
// boost.src.js, line 316
// If the point render function is present, call it to determine whether to proceed.
if( typeof series.options.boostPointRenderFn !== 'function' ) ||
    ( ( typeof series.options.boostPointRenderFn === 'function' )
      && ( series.options.boostPointRenderFn( series, ctx, clientX, plotY, r, pointData ) === true )
    )
) {
  cvsMarker(ctx, clientX, plotY, r);
}
```

This would need to be added to the other branches of drawPoint(). For now, I'm only using a scatter chart so drawing the marker was the only spot where this was needed.

This allows me to run logic in the scope of the callback, and have access to the data object backing the point, so that I can alter the way it appears. (e.g. highlighting selected points and so on).

Thoughts?

**Comment by TorsteinHonsi** [comment]
It doesn't seem to slow down the rendering too much, my quick tests indicates about 200ms on the 1M scatter demo. 

Have you tried simply adding a cvsDrawPoint method to the Scatter prototype?

**Comment by brian428** [comment]
Sorry, do you mean adding my own wrapped cvsMarker() function? I think there are two issues with that:

1. Ideally this customized point rendering would be doable on a chart-by-chart basis. If I wrap the prototype method, that basically changes it for all subsequently created charts.
2. I still wouldn't have access to the additional data object for the point. Only the clientX and plotY are currently passed to cvsMarker(). In my case, I need access to the additional data associated with the point. (e.g. so I can check to see if it has a property "selected" that is set to true).

Does that make sense? Or am I misunderstanding what you're asking?

**Comment by TorsteinHonsi** [comment]
Yes it makes sense. We need to implement this in a way that doesn't cost rendering time.

**Comment by brian428** [comment]
Agreed. This was just my quick and dirty attempt to do what I needed to do. If you can optimize it, that's even better. For what it's worth, I haven't seen any real impact on render time so far.
