### ISSUE TITLE
Sychronize two highcharts series/xAxis with different years (leap year)

### ISSUE THREAD

**Issue by bernhardkern** [highcharts/highcharts#5091]
**Feature Request/Enhancement:**

It would be very nice to have an option to add a **gap for non-leap-year series on the 29th of Feb**.

_You can see the problem i the following fiddle:_
https://jsfiddle.net/bernhard_kern/85s2fm5a/3/.

It is not possible to display the series directly below each other, because one timeseries has one (or more, depending on the granularity) more data point at the 29th of february. It would be nice if I had the possibility to add a gap for all values which would be on the 29th of february. At the fiddle you can look at first and second of march-> The values of the same date are not below each other.

_Bad Workaround_: Merge all data to a leap year and use only one x-Axis and several series.

**Comment by pawelfus** [comment]
Thank you for suggestion! 

Related [question](http://stackoverflow.com/questions/35748588/can-i-sychronize-two-highcharts-series-with-different-years-leap-year) on stackoverflow.

**Comment by KacperMadej** [comment]
It's possible to add a gap using breaks - requires `broken-axis` module or Highstock. Demo: https://jsfiddle.net/BlackLabel/85s2fm5a/15/

This seems to be doing exactly as the enhancement requirements, so I'm closing this issue.
In case of new info the issue can be reopened, but in general for enhancements please use [userVoice](https://highcharts.uservoice.com/forums/55896-general).
