### ISSUE TITLE
Highstocks - Time shows instead of date at beginning of x-axis for large datasets

### ISSUE THREAD

**Issue by adrianwilson** [highcharts/highcharts#5092]
For larger data sets in highstocks, the x-axis will start with the time instead of date. Below is the js fiddle. The fiddle view needs to be expanded horizontally from it's default size.

https://jsfiddle.net/adrianinc/LLw497fj/10/

![chart](https://cloud.githubusercontent.com/assets/665000/13477914/c8716cec-e08b-11e5-865d-f6e56201c244.PNG)

**Comment by TorsteinHonsi** [comment]
A fixed width is needed for reliable reproduction: https://jsfiddle.net/highcharts/LLw497fj/11/

Anyway, Highstock doesn't distinguish between date and time, it is just different levels of granularity on a datetime axis. 

What you probably want to do is to use the [xAxis.datetimeLabelFormats](http://api.highcharts.com/highstock#xAxis.dateTimeLabelFormats) option to control how it is printed: https://jsfiddle.net/highcharts/LLw497fj/12/

**Comment by adrianwilson** [comment]
Adding markup to the date time format worked perfectly, since the date displays consistently with xAxis labels without time. That would be a handy update to the documentation. Thanks for your help!

**Comment by TorsteinHonsi** [comment]
> That would be a handy update to the documentation. Thanks for your help!

Great! As a user, where would you expect to find this information?

**Comment by adrianwilson** [comment]
While it's on the fiddle example, it would be great to add it to the documentation itself, thanks! http://api.highcharts.com/highstock#xAxis.dateTimeLabelFormats

**Comment by TorsteinHonsi** [comment]
Thanks for the suggestion, I've updated the text at [xAxis.dateTimeLabelFormate](http://api.highcharts.com/highstock#xAxis.dateTimeLabelFormats).
