### ISSUE TITLE
xAxis.tickPositions system/browser hang

### ISSUE THREAD

**Issue by Theriault** [highcharts/highcharts#5093]
System hangs when hiding a series using xAxis.tickPositions.

Reproducible in Chrome (48.0.2564.97 m) and Edge (25).

Toggle the visibility of the series:

http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/xaxis/tickpositions-tickpositioner/

**Comment by pawelfus** [comment]
It is not a problem with `xAxis.tickPositions` but example with `yAxis.tickPositioner`. When hiding series, `this.dataMin` and `this.dataMax` are nulls, so `for()` goes crazy. 

Here is updated demo, which works fine: http://jsfiddle.net/h8muLku7/2/
