### ISSUE TITLE
Highchart Chart.event.click

### ISSUE THREAD

**Issue by ishandeb** [highcharts/highcharts#5096]
Hi,
I am using highchart for my Windows Phone Application using phonegap.
But when I am clicking on the region of the chart.
Then: **event.currentTarget.hoverPoints is returning null.**
I have given my code below.
`click: function (event) {                    
                    if (event.currentTarget.hoverPoints.length > 1) {
}}`

Could any one help me how to find the current target series and their category.
Thanks in advance.

**Comment by TorsteinHonsi** [comment]
Thanks for writing! This is our bug tracker, for general tech support please see www.highcharts.com/support.
