### ISSUE TITLE
Series are affecting each other in line/spline charts

### ISSUE THREAD

**Issue by zeman** [highcharts/highcharts#5100]
Using version 4.2.3

We have spline charts with multiple series and when turning a series on and off via the legend a few of the points in another data series will change. Not all the points change, often just couple and then they are rendered in the wrong position. Turning off all the other series then corrects the issue and the chart is rendered correctly. There appears to be some interaction between the series when there's multiple series on one chart.

Example chart with two data series, note the spikes in Chrome
<img width="1466" alt="screen shot 2016-03-05 at 11 33 20 am" src="https://cloud.githubusercontent.com/assets/204268/13543594/8b6dfd72-e2d1-11e5-9f72-260d892a4052.png">

Clicking on the legend and turning off Safari affects the Chrome data and it no longer has the tall spikes.
<img width="1460" alt="screen shot 2016-03-05 at 11 33 34 am" src="https://cloud.githubusercontent.com/assets/204268/13543600/a1eb0aae-e2d1-11e5-8bf9-8a9cc97c7949.png">

It turns out the spikes are misrepresenting the actual Chrome data passed to the chart. Here you see a tooltip where the main value "113" is pulled from the x axis itself, but it's being rendered well above 200 when there's two series on the chart.
<img width="1453" alt="screen shot 2016-03-05 at 11 33 48 am" src="https://cloud.githubusercontent.com/assets/204268/13543651/08049db4-e2d2-11e5-8629-dede40f3e90b.png">

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! Can you provide a live demo? You can copy some data and set is up based on [jsFiddle](http://jsfiddle.net/highcharts/llexl/).

**Comment by zeman** [comment]
Here's a live example:

https://speedcurve.com/demo/responsive/?s=299&u=907&r=eu-west-1&d=30&m=speedindex&share=39tfnozeq94p1o0hndk1kpbg4vb7cg

In the top chart toggle the Apple iPad series on/off via the legend and you'll see that a couple of points in the Firefox series animates up and down.

**Comment by TorsteinHonsi** [comment]
Thanks for the demo! I'm trying to reproduce it in a controled environment so that I can circle down the issue, but this is the best I can do: http://jsfiddle.net/highcharts/pqap2ywu/

Do you have any idea what can be changed in the fiddle in order to provoke the bug?

**Comment by zeman** [comment]
Closing. This turned out to be a bug on our end where we were setting stacking to "normal" on a spine.
