### ISSUE TITLE
Click not listened after Point.update on pie slice

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#5101]
In my example I have a point click listener that updates the clicked point and when chart is a pie this doesn't seem to work two times in a row for the same slice without moving the mouse out of the it.
[Pie Example](http://jsfiddle.net/alvarezg/5Lmmbmwy/)
The same listener seems to be working for a column chart:
[Column Example](http://jsfiddle.net/alvarezg/95863b0m/)
Is there something wrong with the pie example? Is there any known workaround for the pie example?

Thanks in advance

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/5Lmmbmwy/1/

**Comment by alvarezguille** [comment]
Great! Thanks for the quick response!

**Comment by alvarezguille** [comment]
I've been testing it and looks like the fix doesn't work when tooltip is disabled
http://jsfiddle.net/alvarezg/5Lmmbmwy/2/
Tried to use different mouse tracking config and wasn't lucky.
Can this be re-opened? Or should I open a new issue?
Thanks!
