### ISSUE TITLE
Cut marker after scroll in iOS

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5104]
Steps:
1. Open http://jsfiddle.net/79w77ea4/ in iOS (9.x)
2. Scroll page
3. Observe that marker on the xAxis is cut.

**Comment by TorsteinHonsi** [comment]
I can sett it in the URL above. When loading http://jsfiddle.net/79w77ea4/show alone (without the jsFiddle chrome), it is harder to replicate, but replicatable sometimes after pinch-zooming in and out and scrolling. Most likely it is an SVG rendering bug in the browser.
