### ISSUE TITLE
Support ISO-3166-2 for regions

### ISSUE THREAD

**Issue by gregorypratt** [highcharts/highcharts#5105]
We currently have geo data that we want to map to countries and regions of countries.

We use the ISO-31662-2 https://en.wikipedia.org/wiki/ISO_3166-2:US (United States example) International Standard and this works for countries.

When it comes to regions (states, counties etc) Highmaps don't supply map data with ISO-3166-2 identifiers that we can join against.

Could Highmaps please support https://en.wikipedia.org/wiki/ISO_3166-2 ?

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng Comments?

**Comment by oysteinmoseng** [comment]
We try to supply ISO codes where these are available in our source data, but we do not have this for all countries. You could vote for inclusion of codes for particular countries on our UserVoice forum (https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api), and we can prioritize adding the codes manually to the most requested areas.

**Comment by sventech** [comment]
Has Highmaps been updated to the latest Natural Earth 3.0 from January 2015? It appears there's a fix for this issue...
https://github.com/nvkelso/natural-earth-vector/pull/128

**Comment by oysteinmoseng** [comment]
@sventech Yes, the source data from NE is the most recent. Unfortunately the fix was not exhaustive.

**Comment by timmipetit** [comment]
Any updates on this?

**Comment by oysteinmoseng** [comment]
@timmipetit There have been no updates from NaturalEarth yet. If you are looking for ISO codes for a particular country we might be able to add it manually.

**Comment by timmipetit** [comment]
Thanks for the reply @oysteinmoseng. If it would be possible to add ISO codes for Belgium we woud be helped a lot :)

**Comment by oysteinmoseng** [comment]
@timmipetit We will be releasing a new version of the Map Collection soon. We'll try to get ISO codes for Belgium included in this.

**Comment by timmipetit** [comment]
That would be awesome! :) Is there any specific way to receive update-information about the Map Collection? Is it in some way bundled with Highcharts/Highmaps?

**Comment by oysteinmoseng** [comment]
@timmipetit We don't currently have a system for subscribing to notifications about the map collection, but if you follow us on Twitter we will certainly mention it there.

**Comment by Coemgen4** [comment]
Any update about this issue ?
Have the ISO-3166-2 for admin0, admin1 and admin2 will be amazing !

**Comment by oysteinmoseng** [comment]
@Coemgen4 We are still adding ISO codes manually on a per-country basis, as we don't yet have a good source for all regions with this data. Do you have any specific countries/areas in mind?

**Comment by Coemgen4** [comment]
Yes, for France et Belgium ;).
On this repo https://github.com/benkeen/country-region-data, there is ISO codes but just for the first level, admin1

**Comment by oysteinmoseng** [comment]
@Coemgen4 We will try to add ISO codes for admin1 for France and Belgium for the next version. Admin2 might take longer, but if we find a good source we might be able to include this as well. Thanks for the resource link!

**Comment by Coemgen4** [comment]
Thanks, it will be very appreciated !
I'm looking for a good source for admin2 level, I will share with you if I find something.

**Comment by MrNghia123** [comment]
We need ISO codes support for Vietnam regions too.

**Comment by sebastianbochan** [comment]
@oysteinmoseng do we have ISO for Vietnam?

**Comment by oysteinmoseng** [comment]
@sebastianbochan @MrNghia123 We do not currently have ISO codes for Vietnam regions, but you might get away with using `hc-a2`, alternatively replacing the properties that are wrong manually. I'll add it to the list of codes to add.

**Comment by PaulDalek** [comment]
Here are the maps of all mentioned countries with added/corrected ISO-3166-2 codes:
- France: https://jsfiddle.net/kx370fgL/
- Belgium: https://jsfiddle.net/18eyawzk/
- Vietnam: https://jsfiddle.net/6rw3cz02/

Internal note:
In some maps iso-3166-2 property is updated and in some added.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#5
