### ISSUE TITLE
Synchronized charts demo doesn't work in Firefox

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5106]
**The demo:** http://www.highcharts.com/demo/synchronized-charts

**An error in Firefox;** `TypeError: e is undefined`
(after mouseover multiple charts)

**The error refers to:** [this line of code](https://github.com/highcharts/highcharts/blob/1aacf2433fb94b1658300616fd442f82b774f9c5/js/highcharts.src.js#L10036)

**Possible fix:** Do not override the event and use code like in this demo:
http://jsfiddle.net/c70kLtrm/

**Comment by TorsteinHonsi** [comment]
Thanks for the fix @KacperMadej !

I'll upload the fix to the webpage.
