### ISSUE TITLE
Highchart not working if JSON parameter has quotes

### ISSUE THREAD

**Issue by naveengopi** [highcharts/highcharts#5107]
I am trying to use PieChart in my application. The integration of an example code of highchart went smoothly and chart was working fine in my app. The problem begins when I send the JSON response from the backend. 

My front end example code looks like this

```js
$scope.chartConfig = {
			.... config code goes here
            series: [{
                name: 'Brands',
                colorByPoint: true,
                data: [{
                    name: 'Chrome',
                    y: 24.03,
                    sliced: true,
                    selected: true
                }]
            }] 
			};
```

This works perfectly fine! Now when i send the data from the backend as a JSON response(see below) to the frontend it fails. The data part of JSON has quotes for the "name", "y", "sliced" parameter etc. This is making the rendering fail I assume. Is there any workaround for this and is this a bug with highchart?
	
```js			
data:[{
         "name":"Test label",
          "y":2,"sliced":true,"selected":true
	}]}
```

**Comment by TorsteinHonsi** [comment]
This shouldn't be a problem. Whether the property names are quoted or not, doesn't matter in JavaScript. However, you must make sure that the actual `y` values (numbers) are not in quotes.

PS: For general tech support, please see www.highcharts.com/support.
