### ISSUE TITLE
Tick labels hidden because of missing rotation attribute

### ISSUE THREAD

**Issue by lemonbutter** [highcharts/highcharts#5108]
The function getLabelPosition returns NaN for the y position when the label.rotation is undefined.
```javascript
if (!defined(yOffset)) {
    yOffset = axis.side === 2 ? rotCorr.y + 8 :// #3140, #3140
        yOffset = mathCos(label.rotation* deg2rad) * (rotCorr.y - label.getBBox(false, 0).height / 2);
}
```
I don't know why the label hasn't set the rotation attribute. It occurs when I have an own tickPositioner function. Unfortunately I have no fiddle, maybe I can make one later, when I have time.

It is a second yAxis with percentage values, I calculate the tickPosition so that the axis has another zero point and they are better distributed.

Highstock 4.2.3

**Comment by pawelfus** [comment]
Thank you for reporting. Unfortunately, it works for me, please take a look: http://jsfiddle.net/0av3bdvq/ - if you could update the jsFiddle above with your `tickPositioner` that would be great. Maybe the issue is somewhere in the that `tickPositioner` logic. I am not sure about:

> I calculate the tickPosition so that the axis has another zero point and they are better distributed.

What do you mean by another zero point? Maybe you create two the same tick marks and that is the reason of that error (two tick-positions with exactly the same value?). Something like this: http://jsfiddle.net/0av3bdvq/1/ ?

**Comment by lemonbutter** [comment]
I had the time to create a fiddle. But I also couldn't reproduce it in there.
Maybe you have an Idea what could go wrong.

The pval is the previous value, in our charts it's recalculated when the extremes changes.
Normally it would be the last point of the previous exchange day.

http://jsfiddle.net/0av3bdvq/3

**Comment by pawelfus** [comment]
Perhaps it's related to the data? For example, there may be the case, when `pVal = 0`and method

    function getRVal(pval, val) {
      return (val - pval) / pval;
    }

fails?

**Comment by lemonbutter** [comment]
I had again some time. You are right with the division trough zero. But i think this isn't the problem.
Equities don't drop to zero.
I have updated the fiddle: http://jsfiddle.net/0av3bdvq/9
We also do some updates when setExtremes is called, also we call the setExtremes when the chart callback is called.
But I still can't reproduce it in the fiddle. But maybe you have an idea if my approach to update the tickpositions is right or not.

**Comment by pawelfus** [comment]
You shouldn't update `axis.tickPositions` manually, you should use [`yAxis.tickPositioner`](http://api.highcharts.com/highcharts#yAxis.tickPositioner), like in your first demos.

**Comment by lemonbutter** [comment]
Okay I will try to cleanup my code, maybe your hint will solve the problem I have.
Thanks for the support.
