### ISSUE TITLE
tickInterval of 1 can lead to "infinite" loop

### ISSUE THREAD

**Issue by leonyu** [highcharts/highcharts#5110]
`tickInterval` of 1 can lead to "infinite" loop when dealing with large ranges. While this is an user error, it should be capped by some default `maxTickAmount` because it was impossible to debug as the browser would crash. 

If there is a use case for high `tickAmount`, perhaps have a limit set in global config that can be overwritten if user intentionally wants it.

**Comment by TorsteinHonsi** [comment]
Thanks for the suggestion! We removed [error 19](http://www.highcharts.com/errors/19) when we went over to a smarter handling of ticks in v4.1. But as you say, the user can still do this by accident, so we should have some kind of cap.
