### ISSUE TITLE
Returning false from event handlers doesn't cancel default function

### ISSUE THREAD

**Issue by markmsmith** [highcharts/highcharts#5112]
In the docs it says that you can return false from an event handler to cancel the default action (such as select for a click when allowPointSelect is enabled):
[plotOptions.series.point.events.click](http://api.highcharts.com/highcharts#plotOptions.series.point.events.click)
However, on modern browsers this doesn't work, with the default action always running.  

Demo fiddle: http://jsfiddle.net/markmsmith/kLuzcvx4/  
Environment:
  Chrome  48.0.2564.116 (64-bit)  
  Firefox 40.0 and 45.0
  Mac OS X Yosemite 10.10.5

It looks like on modern browsers like Chrome and Firefox, the Event's field `defaultPrevented` is a read only property, so when the native `preventDefault()` is overwritten [here](https://github.com/highcharts/highcharts/blob/master/js/highcharts.src.js#L1316), we can no longer set that field to true [here](https://github.com/highcharts/highcharts/blob/master/js/highcharts.src.js#L1305).  I'd suggest wrapping line 1316 with an if check, only adding preventDefault() if there isn't one already.  Only adding a synthetic `preventDefault()` when there isn't a native one may also mean you can get rid of the try/catch wrapping code that was done for issue #615

**Comment by pawelfus** [comment]
Thank you for reporting. You are right, this is broken since Highcharts includes our adapter ([release note](http://www.highcharts.com/articles/2-news/198-highcharts-drops-adapters)). It works fine with Highcharts + jQuery ( versions < 4.2.0 ): http://jsfiddle.net/r1bLaLgo/
