### ISSUE TITLE
Inconsistent hover/click behavior for overlapping points (tooltip.shared: false)

### ISSUE THREAD

**Issue by arnodirlam** [highcharts/highcharts#5114]
I've made a line graph with clickable points.

**Problem**: When multiple points overlap at a coordinate, the hover and click behavior is quite inconsistent. When the cursor is close to the points, the points are sometimes still hovered/clickable (easier if they are not on the same coordinate but close). When the cursor is directly on these points, no point is hovered/clickable at all.

**Demo**: http://jsfiddle.net/dondarone/3ufy0x8c/
Try to click directly in the middle on either: New York/London, March (same coordinate); Berlin/London, April (close)

**Expected**: It should always hover/click the point with the highest (series) index.

**Side notes:**
I'm aware that shared tooltip gives me that behavior. However, I don't want a shared tooltip over all series.
Ideally, there'd have a shared tooltip only for the points overlapping at this coordinate (as suggested on [UserVoice](http://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/9523164-uniquely-display-multiple-points-at-the-same-coord)), but that would be a feature request, and I think here we have a bug.
As opposed to some other issues already posted (#4698 and #5074), I'm not getting a click for the point with the highest index - which is actually what I want.

**Comment by pawelfus** [comment]
Thank you for reporting this. I think #4679 is connected also - the suggested solution there may also fix this bug.

**Comment by arnodirlam** [comment]
Thank you for the quick reply.
Yep, I can confirm that the code snippet you posted over there, combined with assigning index and zIndex to each series solves the issue entirely.
Thanks for the good work! :+1: Would be glad if this was part of the next release!

**Comment by pawelfus** [comment]
Closing as #4679 is closed too. Please reopen if you think something is still broken.
