### ISSUE TITLE
large heatmap turns black if too many data points are given

### ISSUE THREAD

**Issue by markusp72** [highcharts/highcharts#5115]
see this fidle for a large heatmap:

http://jsfiddle.net/5z0s55n2/1/

All heatmap data points are shown in black (tested in FF 45.0 and Chrome  49.0.2623.87 m).

If you remove a single data point, the heatmap is shown correctly (in blue colors).

How can this be avoided? Acutally, I would like to show much more data...

**Comment by pawelfus** [comment]
Hi, 

Thank you for reporting this. This is known issue: #3765 . 

Try to use workaround, by setting `turboThreshod: 0`, demo: http://jsfiddle.net/5z0s55n2/2/

**Comment by markusp72** [comment]
ok, thanks.
