### ISSUE TITLE
Chart does not resize when using WebComponents

### ISSUE THREAD

**Issue by MKuenzi** [highcharts/highcharts#5117]
I can reproduce in Firefox and IE 11.
http://jsfiddle.net/tvxkrh4s/

If you look at the original JS Fiddle, the chart will resize and shrink with the window resize. As soon as WebComponents.js is loaded, it will no longer do so.

On line 12663 when you are using the WebComponents polyfill, target is neither window nor document.

` if (!chart.hasUserSize && !chart.isPrinting && width && height && (target === win || target === doc)) { // #1093
`
One possible solution would be to change the OR check to include target.window && target.window === window.  

`if (!chart.hasUserSize && !chart.isPrinting && width && height && (target === win || target === doc || target.window && target.window === window)) { // #1093`

Thanks,
Mike

**Comment by TorsteinHonsi** [comment]
As I understand it, the WebComponents library modifies the event arguments. In general it is not Highcharts' job to work around issues with third party libraries, so it would be better if you use a workaround. To start, here's how you can go in and modify the event arguments for the `reflow` function:

```js
Highcharts.wrap(Highcharts.Chart.prototype, 'reflow', function (proceed, e) {
	console.log(e.target, window);
    // Here you can reassign e.target
    proceed.call(this, e);
});
```
http://jsfiddle.net/tvxkrh4s/2/
