### ISSUE TITLE
Polar chart bubble series data label positioning erratic.

### ISSUE THREAD

**Issue by adamshapiro0** [highcharts/highcharts#5119]
I cannot seem to get data labels to be positioned in a deterministic location relative to the values themselves when using a bubble series on a polar chart. The horizontal coordinate on the chart appears to align with the center of the bubble, but the vertical coordinate seems to vary randomly between points (i.e., the label always appears some unexpected amount above the center of the bubble but centered correctly horizontally).

See the following example: http://jsfiddle.net/gyb8hvd3/ (modified from the polar series example - http://jsfiddle.net/highcharts/z9nyR/).

Adjusting the `y` offset appears to affect all labels equally but doesn't address the problem. I have tried setting `inside` to `true` and `false` and in both cases the labels are incorrectly positioned, but with different offsets.

For reference I included a line series as well (invisible by default). The labels appear in the correct locations for the line.

Edit:
I'm using Chrome 49.0.2623.87 (on OS X) and tested with the current version of highcharts (4.2.3). I also tested it on Safari and got the same results.

**Comment by pawelfus** [comment]
**Workaround:**

Change `alignDataLabels` to use default alignment:

    Highcharts.seriesTypes.bubble.prototype.alignDataLabel = Highcharts.Series.prototype.alignDataLabel;

Demo: http://jsfiddle.net/megczkdz/
