### ISSUE TITLE
i18n && lang problem

### ISSUE THREAD

**Issue by xfight0** [highcharts/highcharts#5120]
Hello, everybody.
I am from China, I want to replace these english 'zoom', 'from', 'to' and so on by Chinese,  but can't use lang option replace them.
 Is there another way? 
```
        lang:{
           contextButtonTitle:"图表导出菜单",
           decimalPoint:".",
           downloadJPEG:"下载JPEG图片",
           downloadPDF:"下载PDF文件",
           downloadPNG:"下载PNG文件",
           downloadSVG:"下载SVG文件",
           drillUpText:"返回 {series.name}",
           loading:"加载中",
           months:["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
           noData:"没有数据",
           numericSymbols: [ "千" , "兆" , "G" , "T" , "P" , "E"],
           printChart:"打印图表",
           resetZoom:"恢复缩放",
           resetZoomTitle:"恢复图表",
           shortMonths: ["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
           weekdays: ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六","星期天"]
        }
```

**Comment by pawelfus** [comment]
Hello, thank you for reporting. Could you explain why you can't use `lang` option to change that? It is listed in our Highstock API and should work: http://api.highcharts.com/highstock#lang

Note, this is our bug tracker, for support related issue, please contact with us on forum or directly using email.

**Comment by xfight0** [comment]
@pawelfus , thank you for the answer 
I can't change some word like 'to', 'from', 'zoom' by the lang option. 
![highcharts-i18n](https://cloud.githubusercontent.com/assets/5730147/13768824/f8ddefee-eab4-11e5-8159-fccfd1e254ce.png)

**Comment by TorsteinHonsi** [comment]
It's the [lang.rangeSelectorZoom](http://api.highcharts.com/highstock#lang.rangeSelectorFrom), `rangeSelectorFrom` and `rangeSelectorTo` options.

**Comment by xfight0** [comment]
@TorsteinHonsi :sweat_smile: Thank you

**Comment by c0ze** [comment]
Hello there, sorry for digging this up, but it seems these were removed from `lang` with `6.1` release.

Any idea where these went ? Or how am I supposed to localize these texts ? Thanks !

**Comment by TorsteinHonsi** [comment]
They're in the Highstock API: https://api.highcharts.com/highstock/lang.rangeSelectorFrom

This link above goes to the Highcharts API, I will fix that for future reference.
