### ISSUE TITLE
highslide js/css not available in npm version

### ISSUE THREAD

**Issue by ragefuljoe** [highcharts/highcharts#5122]
Highslide does not seem to be packaged in the npm version. Is there a separate npm for highslide? I was going to just push a copy of the files onto npm but wanted to check if that already existed first.

also, still trying to get this to work in a webpack/requirejs setup

thanks

**Comment by TorsteinHonsi** [comment]
Hi, Highslide is not a part of Highcharts, so it is not available in the npm package. There is currently no official package for Highslide.
