### ISSUE TITLE
xAxis labels overlapping on redraw() when using xAxis.labels.format

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5124]
Hi,

When using xAxis.labels.format, chart have problem with overlapping labels on redraw. 

Here you can find an example of  this issue:
http://jsfiddle.net/ded8shzg/5/

To recreate the issue click on the Reflow button.

Here you can see chart after load:
![image](https://cloud.githubusercontent.com/assets/15050812/13784667/6b2a7516-ead0-11e5-9a68-385e2fd94088.png)

and after redraw:
![image](https://cloud.githubusercontent.com/assets/15050812/13784689/7d889440-ead0-11e5-8793-97841f7699ee.png)

It looks like labels have also problem with their position when hide and show series:
![image](https://cloud.githubusercontent.com/assets/15050812/13784736/ae37df1a-ead0-11e5-97bc-0c36d4b1e58b.png)

Here I have found topic that may be connected with this issue:
https://github.com/highcharts/highcharts/issues/4070

Kind regards.

**Comment by TorsteinHonsi** [comment]
Reverted this fix, it had unforeseen consequences. The problem seems to be that the second time (on redraw), the label width and ellsipsis is already set in the `renderUnsquish` function, so it is not handled correctly.
