### ISSUE TITLE
Stacked Barchart do not allow  to set custom labels!

### ISSUE THREAD

**Issue by rrpatil761** [highcharts/highcharts#5125]
Please check this demo :  http://jsfiddle.net/jm463mwr/1/

       formatter: function() {
            if (this.series.options.myLabels) {
              return "XXX: " + this.series.options.myLabels[this.point.x];
            }
          }

This function is not working here :(

**Comment by TorsteinHonsi** [comment]
Thanks for writing, but please note that this is our bug tracker. See www.highcharts.com/support for where to post general tech questions.

Your demo is not finished, it doesn't show a chart at all. Here is something that actually runs: http://jsfiddle.net/highcharts/jm463mwr/4/
