### ISSUE TITLE
Incorrect bars display on changing zoom

### ISSUE THREAD

**Issue by Dimgoncharov** [highcharts/highcharts#5127]
**Issue:** On different zooming (larger/smaller time range) bars values differ a lot.
**Example:**  http://jsfiddle.net/devror/zg5hycb2/3/
http://grabilla.com/06310-2b3fad3a-704d-4664-9fbb-226b37b3f856.png
http://grabilla.com/06310-3dc2a972-7818-491c-bc6a-94e7c21581d4.png
Sample video: http://grabilla.com/06310-450fcdd4-a5b4-4ff4-9353-913de756ff11.html#
**Expected result:** Bar values should be equal to line values
http://grabilla.com/06310-fc9e00dd-c06e-4d2c-9814-25e8793bb9e5.html#

**Comment by TorsteinHonsi** [comment]
What happens is that [dataGrouping](http://api.highcharts.com/highstock#plotOptions.column.dataGrouping) kicks in. On a column series, individual data points are summed as per the default [approximation](http://api.highcharts.com/highstock#plotOptions.column.dataGrouping.approximation) setting. For line series, the default approximation is `average`.
