### ISSUE TITLE
getXDateFormat not handling 23 hour days during DST crossover

### ISSUE THREAD

**Issue by pawl-rs** [highcharts/highcharts#5128]
There may be a bug here: https://github.com/highcharts/highcharts/blob/8c3610970f7d4733dcaa4f729b3337b5c3bb54d2/js/parts/Tooltip.js#L454-L458

It figures out what the units the labels should be based on whether the "closestPointRange". "closestPointRange" is like it sounds, it's the range between the two closest points on the chart. Since switching to DST gives us a 23 hour day, it thinks the "closestPointRange" isn't quite a day, so it uses hour labels.

To fix it, I ended up overriding getXDateFormat here: https://gist.github.com/pawl-rs/2f34ecfb23146cbcaf85

However, this won't work for everyone, because some people may want to look at 23 hour ranges.

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestion!

Live demo: http://jsfiddle.net/highcharts/uh5vqpyb/
