### ISSUE TITLE
export truncates/removes individual bars from series via random selection

### ISSUE THREAD

**Issue by arvel** [highcharts/highcharts#5129]
I am exporting a chart that has a long series with lots of bars. When I export it, some of the series are missing.  The process by which the series are removed seems to be somewhat random.

The following is a test mockup of the scenario (hence 0 bars on the right).

Here is the chart on the web:
<img width="834" alt="screenshot 2016-03-16 17 06 55" src="https://cloud.githubusercontent.com/assets/202785/13832540/587360b6-eb9a-11e5-9970-b692ee62f377.png">

Here is the exported version of the same above chart:
![energysavingsbybuildingtotaltodate_2016-03-17 3](https://cloud.githubusercontent.com/assets/202785/13832542/5f6f1cca-eb9a-11e5-8b53-9d902d1c1de0.png)

What do I need to do to get it to include all of the series? Is there a padding setting somewhere that would fix this?

**Comment by KacperMadej** [comment]
Hi, you've posted to our issue tracker.
For general tech support, please see www.highcharts.com/support and please provide a live example with code causing the problem, e.g. in JSFiddle.

**Comment by arvel** [comment]
Sorry, looked like a bug to me.  I'll set up the fiddle and contact via support
