### ISSUE TITLE
Problem with resetZoom button when tooltip useHTML is set to true

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5130]
Hi,

When tooltip useHTML is set to true and tooltip is over resetZoom button, it is not possible to click on resetZoom button. Here you can find an example of this issue:

http://jsfiddle.net/ugofh1b1/2/

To recreate issue zoom over the chart and try to click resetZoom button when tooltip is over it. 

It looks like as a workaround it is possible to set tooltip pointer-events to none:
http://jsfiddle.net/ugofh1b1/1/

Kind regards.

**Comment by TorsteinHonsi** [comment]
Thanks for the workaround! 

As stated in http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#html, setting any element option to `useHTML` causes it to cover underlying SVG elements.

**Comment by siropkin** [comment]
If you are looking for another workaround then you can find this solution useful.
It fixes the tooltip x position in case the chart is zoomed.
Feedbacks are welcome.

![Demo](https://media.giphy.com/media/VAc9QkIV8Hwk59cOCs/giphy.gif)

(react code example)
```
<Tooltip
  ...
  positioner={function (tooltipWidth) {
	// eslint-disable-next-line prefer-rest-params,prefer-spread
	const position = this.getPosition.apply(this, arguments);
	const { chart } = this;
	const { userMin, userMax } = chart?.xAxis?.[0] || {};
	const zoomed = !!(userMin || userMax);
	if (zoomed) {
	  const resetZoomButtonPositionX = chart.plotWidth - chart.resetZoomButton.width - chart.resetZoomButton.alignOptions.x;
	  const maxTooltipPositionX = resetZoomButtonPositionX - tooltipWidth / 2;
	  position.x = Math.min(position.x, maxTooltipPositionX);
	}
	return position;
  }}
 ...
```

**Comment by raf18seb** [comment]
Thanks @siropkin!

However, this problem is no longer visible in v10.0.0, so closing as resolved.
