### ISSUE TITLE
Zooming results in lines that appear to be evenly spaced, but the labels indicate otherwise

### ISSUE THREAD

**Issue by gtoups** [highcharts/highcharts#5131]
When using zoom, the graph lines appear evenly spaced, but the labels are not evenly distributed. The resulting graph points are also not on the corresponding line.

![hichartsbug](https://cloud.githubusercontent.com/assets/17907677/13850697/17fa4bc8-ec29-11e5-81dd-22a243006f5f.png)

See JSFiddle: http://jsfiddle.net/ms47u297/

**Comment by TorsteinHonsi** [comment]
You deliberately set the Y axis labels to have no decimals, so 83, 88 and 93 ticks are actually showing 82.5, 87.5 and 92.5 respectively.
 
`return Highcharts.numberFormat(this.value, 0) + '%';`

It is probably better that you only add the percentage unit and let Highcharts handle the number of decimals: http://jsfiddle.net/highcharts/ms47u297/1/
