### ISSUE TITLE
no animation on mapline update with >= 17(?) points

### ISSUE THREAD

**Issue by laurahelde** [highcharts/highcharts#5132]
I am using Highcharts' animation capability to show paths extending from origin points to destination points over time. This is working fine until I get too many lines on the map, and then there is no animation.

To demonstrate this, I've put 16 lines on a map that extend to random destinations over a 10-second time period: http://jsfiddle.net/evqk9565/. Now change `numLinesToAdd = 16` at the top to `numLinesToAdd = 17`, and you'll see the transition is no longer animated. Any help or workarounds for this?

(A note about this fiddle, I'm aware that the best practice is to update the points with redraw set to false, then redraw the entire map with my desired duration after the loop, but when I do it that way I don't see the animation even with <= 16 lines, so for this demo I did it the other way.)

**Comment by TorsteinHonsi** [comment]
Thanks for writing, and the cool idea!

A note about your note - actually it works also when running a common redraw, but there is still the change in behaviour when changing from 16 to 17 items: http://jsfiddle.net/highcharts/evqk9565/1/

**Comment by TorsteinHonsi** [comment]
Got it, it was the [animationLimit](http://api.highcharts.com/highmaps#plotOptions.series.animationLimit) that kicked in. It is designed to protect you from slow animation, but in this case it was not necessary. See http://jsfiddle.net/highcharts/evqk9565/2/.

**Comment by laurahelde** [comment]
Ah, thank you, I missed that option! (And I don't know what I did wrong with the redraw, that's actually how I'm doing it in my real code and it works fine there, so I must have just done something dumb in the fiddle.) Working great now.
