### ISSUE TITLE
Datalabels disappearing when browser resized, with defer enabled

### ISSUE THREAD

**Issue by findoo** [highcharts/highcharts#5133]
With the defer option enabled on data labels, the label disappears when the browser is resized. The labels do still appear when the chart is exported though.

There is no way to get the label back without re-rendering. 

![Issue](http://i.imgur.com/2G2NcmK.gif)
See JSFiddle: http://jsfiddle.net/ky6u072u/ (defer option added to http://www.highcharts.com/demo/bar-basic)

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Normalized demo: http://jsfiddle.net/highcharts/ky6u072u/1/. Note that the issue does not occur when `defer` is not defined in the config, even though it defaults to `true`
