### ISSUE TITLE
Pie: dataLabel animation makes label "arrive" from out of chart on align flip

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5134]
In case, e.g. legend item click, dataLabel will change it's alignment - will flip from one side of connector to another, then animation is strange - label arrives from out side of the chart instead of small possition change.

**Demo:** http://jsfiddle.net/std01rpx/

**Steps:** click orange point in legend -> black slice's dataLabel flips

Not-so-good workaround: disable animation - http://jsfiddle.net/std01rpx/1/

**Comment by TorsteinHonsi** [comment]
Fails since ec5d496
