### ISSUE TITLE
Legend symbols for inverted chart are not inverted

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5135]
This might be a problem for symbols that might be confused (e.g. `triangle` and `triangle-down`) when inverted.
If someone color-blind tries to make sense of the symbols and can't differentiate by color alone.

Workaround: do not use symbols that are easy to confuse

**Comment by KacperMadej** [comment]
Working correctly in 6.1.4.
Closing as resolved.

**Comment by BistroStu** [comment]
I'm still finding this to be a problem. If you go to the sample code https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-marker-symbol/ and add chart: {inverted:true} to the options, the markers are rotated 90° in the chart but not in the legend. I would expect the same rotation in both the chart and legend.
I'm using custom svg markers so my workaround is to assign a different marker (rotated 90°) on the individual points to the series, but I'd love not to have to do that.

**Comment by pawelfus** [comment]
Thanks for the demo! Let me reopen the issue.

Demo: https://jsfiddle.net/BlackLabel/coqtxr51/

**Comment by KacperMadej** [comment]
Duplicate of #422
