### ISSUE TITLE
Boost module not rendering when mouse interaction while loading 

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#5137]
While rendering the chart, if the user interacts (mouse move + tooltip) the chart never renders.
See here: http://jsfiddle.net/onemenny/o12f70ea/
1. click the button 
2. immediately move the mouse repeatedly over the chart 
3. the chart never renders 

if you do the same without the mouse move the chart renders

**Comment by pawelfus** [comment]
Thank you for reporting. You are right, it looks buggy, in the console, we can observe errors:

> highcharts.src.js:9770 Uncaught TypeError: Cannot read property 'followPointer' of undefined

And:

> highcharts.src.js:19064 Uncaught TypeError: Cannot read property 'hoverPoints' of undefined

**Comment by TorsteinHonsi** [comment]
#### Workaround

Here's a drop-in fix that you can use until the next release is out: http://jsfiddle.net/highcharts/o12f70ea/1/

**Comment by onemenny** [comment]
Thank you
