### ISSUE TITLE
tooltip never gets hidden

### ISSUE THREAD

**Issue by b0ric** [highcharts/highcharts#5138]
Hi guys!

Check demo here: http://jsfiddle.net/615uLfzm/ 
(for Chrome or Firefox, because of fancy data generator)
Move cursor to the graph, so that tooltip comes up. And now, whenever you're moving out of the graph, or the point floats away - tooltip isn't going to hide.

But, in case you specify 'hideDelay' that is small enough
`
    tooltip: {
      hideDelay: 50
    }
`
you'll see that tooltip will hide away.

I guess that tooltip's hideTimer get's cancelled somehow during long timeouts and this leads to such behavior.

**Comment by pawelfus** [comment]
Thank you for reporting.

Works better on the master branch: http://jsfiddle.net/615uLfzm/1/ (it is possible to hide tooltip when moving mouse out of the chart up/down).

**Comment by b0ric** [comment]
yep, true
with bottom movement everything is okey, but if I move mouse up to quickly, tooltip won't hide

**Comment by pawelfus** [comment]
Now I think that issue may not necessary come from Highcharts lib: http://jsfiddle.net/615uLfzm/3/ -  it works fine (to the top too). But with the previous demo, we can reach different iframe, without calling `mouseout` for the chart/container. @b0ric - does the current (5.0.4) version work fine for you in the real use case?
