### ISSUE TITLE
bug when use stack in dynamic data series

### ISSUE THREAD

**Issue by tankiJong** [highcharts/highcharts#5139]
jsfiddle demo here:

http://jsfiddle.net/tankijong/crvdp0ey/1/

When use area stack chart, all things works well. When dynamicly loading data, the chart works well, too.

But if the `Stacking` option is applied on dynamic data chart. The **fill area will be broken** when there are **more than one series**.

**Comment by pawelfus** [comment]
Duplicate of #2285

**Comment by tankiJong** [comment]
@pawelfus  this isn't same as #2285 .  The x values are the same. The key point is that though the area is filled but strange.

**Comment by pawelfus** [comment]
You are right, apologies for my mistake! :) 

Reopening ticket, looks connected to #169.

**Comment by TorsteinHonsi** [comment]
It has something to do with calculating the bottom series graph before the second one is added.

#### Workaround:
Call `addPoint` with the redraw flag set to false, then do `chart.redraw()` after. http://jsfiddle.net/highcharts/crvdp0ey/2/.

**Comment by tankiJong** [comment]
@TorsteinHonsi  Yes, that works well! I tried to find the solution in the docs but failed. I think familiar example may be given in the doc.
