### ISSUE TITLE
solidgauge endPoint shifted to the lower in IE11

### ISSUE THREAD

**Issue by erita** [highcharts/highcharts#5140]
solidgauge endpoint shifted to the lower compared with startPoint.
I confirmed this problem only IE.

this is Fiddle http://jsfiddle.net/rgx0rjg8/1/

**Comment by TorsteinHonsi** [comment]
It's a consequence of buggy and inconsistent handling of `stroke-linecap` in the browsers.

Instead of setting a wide border width to achieve wide solid gauges, the width should be achieved by setting a `size` and `innerSize` setting: http://jsfiddle.net/highcharts/rgx0rjg8/2/
