### ISSUE TITLE
Offline export - IE Edge 

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5142]
In case when the paramater fallbackToExportServer is false, then error in the console appears. But when is true, nothing happen.

![error](https://cloud.githubusercontent.com/assets/2115686/13957488/f31c4dce-f04c-11e5-8613-4499769bfddd.jpg)

**Comment by TorsteinHonsi** [comment]
According to the [compatibility table](http://www.highcharts.com/docs/export-module/client-side-export), it works in IE11. We should test and add Edge to the table.

**Comment by oysteinmoseng** [comment]
Fixed now in bugfix branch, Edge should now behave like IE10 and IE11, falling back to export server for embedded images, and working otherwise. See commits 192194199ab4070a4b33038d9e5e689ade090f0a and 81df230495ea6c556ec954e95c0885186484ee6e.

**Comment by KacperMadej** [comment]
@oysteinmoseng Would it be possible to either 'force' an export and ignore any image data, or to remove any added images on export and replace them afterwards in case fall back to export server is disabled?

**Comment by oysteinmoseng** [comment]
@KacperMadej I could add an option to remove the image elements from the SVG DOM and run the export, but I have a feeling this is a pretty specific request that should maybe be handled as a workaround only? You would have to wrap or overwrite `chart.exportChartLocal`.

@TorsteinHonsi Comments? We could add a `forceOfflineExport` option or similar?

**Comment by TorsteinHonsi** [comment]
What about returning something from the error or callback to signalize that we want to proceed? Otherwise I agree that if it is not a common request we should just provide a workaround.

**Comment by oysteinmoseng** [comment]
Returning a "proceed anyway" code from the callback seems like a great solution, as it will allow for a warning message or other additional logic before forcing. Leaving this issue open as an enhancement for now, as this is a bit of work to implement.
