### ISSUE TITLE
Percent bar renders badly when data includes nulls

### ISSUE THREAD

**Issue by thaggie** [highcharts/highcharts#5144]
If one of the values in the data is null the stacking breaks:

<img width="602" alt="screen shot 2016-03-22 at 10 33 45 am" src="https://cloud.githubusercontent.com/assets/327611/13961235/f36afdf4-f018-11e5-97a1-d75bdfbaa8b6.png">

If the null is set to zero it renders fine.

Config:
```
{
    "chart": {
        "type": "bar",
        "height": 160
    },
    "title": { "text": null },
    "legend": { "enabled": true },
    "yAxis": {
        "title": { "text": null },
        "labels": { "enabled": false }
    },
    "xAxis": {
        "categories": [ "France", "Spain" ]
    },
    "credits": { "enabled": false },
    "plotOptions": {
        "series": {
            "stacking": "percent",
            "animation": false
        },
        "bar": {
            "dataLabels": { "enabled": false }
        }
    },
    "series": [
        {
            "name": "Bananas",
            "data": [ 4000, null ]
        },
        {
            "name": "Pears",
            "data": [ 4000, 5000 ]
        }
    ]
}
```

**Comment by pawelfus** [comment]
Thank you for reporting this. Minified, live, example: http://jsfiddle.net/zxauv885/

*Internal note:*
It looks like we shouldn't add `stackedYData[i]` in case where `y === null` [here](https://github.com/highcharts/highcharts/blob/1aacf2433fb94b1658300616fd442f82b774f9c5/js/parts/Stacking.js#L340-L343). For example:

	if (y !== null) {
		stack.points[pointKey].push(stack.cum);
		stackedYData[i] = stack.cum;
	}
