### ISSUE TITLE
Bluerred data label mixing drilldown with column chart

### ISSUE THREAD

**Issue by marcelbonnet** [highcharts/highcharts#5145]
When coding a Column Chart with Drilldown:

The main chart rendered blurred black colored data labels. But when they are clicked, the next columns (the drilled down columns that are opened) are perfect (white color, no blur, very readble). I found a workaround declaring:

`.highcharts-drilldown-data-label text { 
color: #FFFFFF !important; 
text-shadow: 0 0 0px white !important; 
fill: white !important 
}`

Try to remove the selector above and check the result: https://jsfiddle.net/marcelbonnet/pjb5dw9q/1/

Repeated with:
Chrome 28
Chrome 48
Firefox 45

Reffers to: http://stackoverflow.com/questions/35962853/highcharts-column-with-drilldown-results-in-blurred-data-label-in-main-chart-ex

**Comment by pawelfus** [comment]
I am not sure if this is bug. You can change `[activeDataLabelStyle](http://api.highcharts.com/highcharts#drilldown.activeDataLabelStyle)` options. For example: https://jsfiddle.net/pjb5dw9q/5/

**Comment by marcelbonnet** [comment]
Thanks, I think you're right.  http://api.highcharts.com/highcharts#drilldown.activeDataLabelStyle with another color really solves that problem and still invating user to interaction.
