### ISSUE TITLE
Column with zero value visible while shouldn't

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5146]
**Problem:** Columns with y value of zero are visible while shouldn't be. The issue is obervable when data points are packed tightly into a chart and points have only negative and zero y values.

**Demo:** http://jsfiddle.net/9m886gye/

**Workaround:** set `borderWidth: 1` - columns will not be visible, but they are still there.

**Comment by TorsteinHonsi** [comment]
__Simplified demo:__ http://jsfiddle.net/highcharts/9m886gye/1/

__Demo with fix applied:__ http://jsfiddle.net/highcharts/9m886gye/2/
