### ISSUE TITLE
Grouped points - cannot update 

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5147]
In case when we have grouped data and call update() on this point, then error #15 is returned and data flips.

http://jsfiddle.net/dLcw7fd7/

**Comment by TorsteinHonsi** [comment]
Reliable demo: http://jsfiddle.net/highcharts/dLcw7fd7/1/

(Data grouping depends on the chart width, so we must make sure to have a fixed width for those demos)

**Comment by TorsteinHonsi** [comment]
The basic problem is that we can't call update on grouped points. In this case, if we set the color to red, the next case the chart is zoomed or panned, the points may be re-grouped and the color is lost.

So the question is what we should do with the update function. If we leave it as it is, the user can check [whether the data is grouped](http://jsfiddle.net/highcharts/dLcw7fd7/3/) first. But that doesn't change the fact that the result is unexpected. Perhaps we should disable `update` on these points, or throw a proper error.

**Comment by pawelfus** [comment]
I think, if we could implement [this solution](https://github.com/highcharts/highcharts/issues/4628) we will be one step closer to a nice solution, where `update()` on a grouped point will modify only the original data points (`series.options.data`) and then just recalculate current point. 

In general, information which points are used in the grouped point would be great. Not necessary copy of the points, just references (indexes?) to the original data should be enough. We have something similar [here](http://demo.blacklabel.pl/) (drag&drop point inside "Zoom view" window") - with "manually" searching for a corresponding group of points.

**Comment by TorsteinHonsi** [comment]
Thanks for your input Pawel, I have implemented a new Point property, `dataGroup`. So we're one step closer: http://jsfiddle.net/highcharts/dLcw7fd7/4/.

> If a point object is created by data grouping, it doesn't reflect actual points in the raw data. In this case, the `dataGroup` property holds information that points back to the raw data:
> 
> `dataGroup.start` is the index of the first raw data point in the group.
> `dataGroup.length` is the amount of points in the group.

**Comment by sebastianbochan** [comment]
+1

**Comment by pawelfus** [comment]
At this moment we throw error 24: https://www.highcharts.com/errors/24

I think it's better, so people won't accidentally bulk update points. If it's expected, then `setData()` should be used.
