### ISSUE TITLE
context menu options still selected on iPad

### ISSUE THREAD

**Issue by anderson-fachini** [highcharts/highcharts#5151]
When I touch any option to download the charts, a page is open with the chart.
If I return to the last page and try do download the chart again, the latest options that I use still selected (with blue background).

I simulated the problem only iPad with Safari (Chrome works well) on iOS 9.2.1.

Print with the problem.
![img_0262](https://cloud.githubusercontent.com/assets/7707758/14028161/df23dbdc-f1d9-11e5-9ec3-2d162862808e.PNG)

**Comment by pawelfus** [comment]
Thank you for reporting. You are right, it happens also on Safari + iOS 9.1
