### ISSUE TITLE
Synchronized Charts not showing shared tooltips

### ISSUE THREAD

**Issue by jessonjoy** [highcharts/highcharts#5152]
Hello,

I have 3 synchronized stacked line charts with multiple lines on each chart on dual axis. I want the tooltip to show up on all 3 charts with all the lines datapoin for that particular x-axis point when I hover over any chart. Right now, I get a null pointer error and have to comment out the 

`chart.tooltip.refresh(point)` code. However, the tooltips isnt shared any more. When I comment out the 

`tootip : {shared : true}` on the chart level object, the tooltips seem to be synchronized however only the first line's data is shown. The other lines do not show on the tooltip. 

Please find an example fiddle below modified using the demo fiddle.

http://jsfiddle.net/jesson/w1cv0bgq/

Appreciate any help on this. I searched for similar issues but I couldn't find any.

Best,

Jesson

**Comment by pawelfus** [comment]
Hi, 

When using shared tooltip, you should pass on all points to `refresh` method as an array, for example:

     chart.tooltip.refresh([point_1, point_2, point_3]);

For questions, please use our other [support channels](http://www.highcharts.com/support). We use github as but-tracker.

**Comment by jessonjoy** [comment]
This works. Thanks for your help. Going forward, I'll look into the support site for help. Thanks!

**Comment by scipper** [comment]
@jessonjoy what was your final solution? something like `chart.tooltip.refresh([this.series.data]);` ?

**Comment by pawelfus** [comment]
Something like this: http://jsfiddle.net/BlackLabel/w1cv0bgq/157/

```javascript
   $('#container').bind('mousemove touchmove touchstart', function (e) {
        var chart,
            point,
            i,
            event;
            
        // points container
        var points = [];

        for (i = 0; i < Highcharts.charts.length; i = i + 1) {
            chart = Highcharts.charts[i];
            event = chart.pointer.normalize(e.originalEvent); // Find coordinates within the chart
            point = chart.series[0].searchPoint(event, true); // Get the hovered point

            if (point) {
                point.onMouseOver(); // Show the hover marker

                // store points: 
                points.push(point);

                chart.xAxis[0].drawCrosshair(event, point); // Show the crosshair
            }
        }
        
        // use refresh([point_1, point_2, ... ]);
        chart.tooltip.refresh(points); // Show the tooltip
        
    });
```
