### ISSUE TITLE
We can not set y axis lables as range!

### ISSUE THREAD

**Issue by rrpatil761** [highcharts/highcharts#5154]
http://jsfiddle.net/ypkzm9gz/

given example I am trying to set y axis labels as  ["1-10","10-20","20-30","30-40","40-50","50-60",........] and bar data depends on these range.

**Comment by rrpatil761** [comment]
http://jsfiddle.net/ypkzm9gz/1/

**Comment by pawelfus** [comment]
Hello,

Thank you for contacting us. For questions, please use our other [support channels](http://www.highcharts.com/support). 

I think, I have already answered you on [stackoverflow](http://stackoverflow.com/questions/36216409/is-supportablerange-type-graph-in-highchart/36218633#36218633).
