### ISSUE TITLE
highstock average question

### ISSUE THREAD

**Issue by pmjhonwang** [highcharts/highcharts#5155]
![image](https://cloud.githubusercontent.com/assets/1998455/14041002/fe7b1a30-f2a7-11e5-9572-82be8b00155b.png)

![image](https://cloud.githubusercontent.com/assets/1998455/14041013/0f909070-f2a8-11e5-93ec-3a1ef99143aa.png)

the same data 
wrong label 
5minte per pointer data of  about one year
how to closed auto average?

**Comment by pawelfus** [comment]
Hi,

Thanks you for contacting us. For questions, please contact with us by email/forum, see [details](http://www.highcharts.com/support).

And to answer your question: this is caused by [`dataGrouping`](http://www.highcharts.com/docs/advanced-chart-features/data-grouping).

**Comment by pmjhonwang** [comment]
3q very much
