### ISSUE TITLE
Time stamps overlapping 

### ISSUE THREAD

**Issue by nkuzma** [highcharts/highcharts#5163]
Hi everyone,

I noticed that when there are two huge numbers next to each other on the 'axis x', they are overlapping.

Please check the attached picture.

![screenshot_40](https://cloud.githubusercontent.com/assets/18162026/14135491/e46614e2-f65d-11e5-87c7-17bc0d5655aa.png)

Nenad

**Comment by pawelfus** [comment]
Hi,

Thank you for reporting. Could you recreate issue on jsFiddle? We will check this. I think it may be the same/similar issue as #5124 or #1416.

**Comment by jon-a-nygaard** [comment]
Closing this issue since we are unable to reproduce, and it is pending a reply. Should anyone have further information on the issue, please comment and reopen.

**Comment by sanjaykanani** [comment]
getting same issue.
http://jsfiddle.net/o04fh8kq/1/ 

> load and select any zoom button.
![overlap](https://user-images.githubusercontent.com/29813892/28909870-ef264056-7847-11e7-985d-5fa936f5dee9.png)

**Comment by KacperMadej** [comment]
Thank you for the demo @sanjaykanani 

Here's a minimal and automated demo: http://jsfiddle.net/t4kqfmrq/

**Comment by jon-a-nygaard** [comment]
Sorry, did not see the comment above. Closing this again.

**Comment by TorsteinHonsi** [comment]
I had to revert this fix, it broke reversed axes and 3d axes. I think a real solution would be to extend the overlapping-datalabels logic to also handle axis labels.
