### ISSUE TITLE
z depth issue with stacking and multiple series in 3d columns

### ISSUE THREAD

**Issue by rennyv** [highcharts/highcharts#5166]
The zdepth is not being calculated properly when you have multiple series that are side-by-side.

http://jsfiddle.net/rennysv/5rntpmw7/1/

Similar to the issue: #4934

**Comment by TorsteinHonsi** [comment]
Reliable demo with fixed width: http://jsfiddle.net/highcharts/5rntpmw7/2/

**Comment by Izothep** [comment]
This issue looks to be resolved through 6f84253

demos:
http://jsfiddle.net/5rntpmw7/3/
http://jsfiddle.net/5rntpmw7/4/
