### ISSUE TITLE
timezone options per chart rather than global

### ISSUE THREAD

**Issue by nhitchins** [highcharts/highcharts#5168]
It would be really useful if there was a chart.setOptions method to apply the useUTC, timezoneOffset & getTimezoneOffset options per chart instance instead of globally. Alternatively allow for these options to be specified in the object passed to the chart constructor. This would also resolve #4206

**Comment by TorsteinHonsi** [comment]
I think this will be quite easy to implement with Highcharts 5, then we ca just set the time methods on the Chart object instead of on Highcharts global object.

**Comment by DavidKDeutsch** [comment]
Any idea of the probability that this feature will make it into an upcoming release? I do not see it mentioned at http://www.highcharts.com/support/roadmap, and I see there is no milestone associated with this issue. I currently have to keep a locally modified copy of Highcharts to accomplish this, which is of course not optimal.

**Comment by TorsteinHonsi** [comment]
I've added the v5.0.0 to it.

**Comment by suganya-suvadi** [comment]
> I've added the v5.0.0 to it.

 Is this available in v5.0.0? I could not find anything related in changelogs.

And thanks for the enhancement; we are dealing with numerous charts of different timezones on the same page and the global options wreck havoc in it!

**Comment by ddavydov** [comment]
Would be great to see this feature implemented, thanks!

**Comment by jbgarr** [comment]
Any updates on this? The project I'm working on requires this level of control as well. We have many different charts that will have different timezones, so the ability to set the timezone option on a per chart basis is a must for us.

**Comment by TorsteinHonsi** [comment]
I did some experiments with this now. One thing we need to resolve internally is how to use `Highcharts.dateFormat`, as it uses the global Highcharts.Date object internally. One possibility is to pass over the chart's Date object, but we should still make sure that the Highcharts.dateFormat function runs as is has done before when calling it outside a chart context.

**Comment by jbgarr** [comment]
@TorsteinHonsi Thanks for the update. So this is still currently under development, right? I was a bit thrown off by your comment on Jul 25, 2016 stating that it was added in v5.0.0. If it is still a work in progress, any idea on when it might make it into a release?

Even more importantly for me at this point, any suggestions for working with multiple charts in an application that all have different timezones? Is there anything I can do now that will show the charts in a different timezone? Luckily at this point the charts do not appear on the same page. Is my only option to continually update the global timezone setting? Thanks for any suggestions you can provide!

**Comment by jbgarr** [comment]
Sorry to spam this thread, but is there any proposed workaround until this feature is released? I'm facing an issue where I chart data for thousands of different items (only one at a time at this point), but is my only option at this point to update the global timezone setting each time a new item is selected and charted?

**Comment by ispringer** [comment]
What we do on pages where we need to have some charts using local time and other charts using UTC is to manually format all the date/times using axis label formatters etc. We use moment.js to do the formatting.

For example:

```
xAxis: {
    type: "datetime",
    lineColor: 'rgba(0, 0, 0, 1.0)',
    minorTickLength: 0,
    tickLength: 0,
    lineWidth: 0,
    labels: {
        formatter: function() {
            var ONE_WEEK = 604800000;
            var thisChart = this.chart;

            if (thisChart.xAxis[0].max - thisChart.xAxis[0].min < ONE_WEEK) {
                return moment(this.value).format("M/D h:mmA");
            } else {
                return moment(this.value).format("MMM DD hA");
            }
        },
        style: {
            fontSize: '10px'
        }
    },
    events: {
        setExtremes: syncChartZoom
    },
    crosshair: false,
    minPadding: -0.05
}
```

Obviously, we'd much rather let Highcharts do the formatting based on a simple date/time format option, so I hope Highcharts will address this issue.

**Comment by eladchen** [comment]
Sorry if this is not the place to ask. But has there been any progress in this regard?

**Comment by TorsteinHonsi** [comment]
Some progress has been made in coupling the time logic to the chart, but without much visible results... http://jsfiddle.net/0f4w484v/

**Comment by tomsommer** [comment]
+1

**Comment by sebastianbochan** [comment]
+1

**Comment by PaulDalek** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Thank you for your patience, this feature is now implemented. It involved quite a bit of refactoring since the whole concept of `global` time options is now obsolete. Since time options now can be set per chart, all relevant options were removed to a new `time` config object that can be set either globally by `Highcharts.setOptions`, or for each chart instance.

The time options in `global` will still work for backwards compliance, but are marked deprecated.

The `dateFormat` function is moved to `chart.time.dateFormat`. All internal use of `dateFormat` and string formatters are now pointing to the chart context dateFormat. The legacy `Highcharts.dateFormat` function reflects only the global time settings, not the new individual chart settings.

The time settings can be changed in run time using `chart.update`.

See it live on jsFiddle: http://jsfiddle.net/highcharts/tahpjw84/

**Comment by ciarancourtney** [comment]
I presume timezone per series is not supported?

**Comment by TorsteinHonsi** [comment]
That's right, timezone per series is not supported out of the box. One approach to achieve it though would be to add all the times as UTC, then use formatters (mainly `tooltip.formatter`) to display the time in each specific series' timezone.

**Comment by brendadev** [comment]
@TorsteinHonsi per your latest answer, how would I use `tooltip.formatter` to display the timezone of each specific series

**Comment by sebastianbochan** [comment]
@brendadev 
In the formatter you can use condition to detecting series and call `Highcharts.time`with requested timezone to have information about offsets. Finally, use `Highchart.dateFormat` to return date in user-friendly format.

**Demo:**
- http://jsfiddle.net/BlackLabel/h54cy0o6/

**Comment by brendadev** [comment]
@sebastianbochan thanks so much for the response, I am still using v4.0.4 and I am still having issues where a user from `Los_Angeles` has a timestamp `2018-06-19 13:19:52.000Z` and the settings below plot `20:19:52`, instead of `6:19:52`.

```
formatter: function() {
    var x, time;
    time = new Highcharts.setOptions({
        global: {
            timezone: _that.timeZone,
            timezoneOffset: _that.offset
        }
    }, this);
    x = this.x - time.global.timezoneOffset;
    return  '<b>' + this.series.name + '</b><br/>' + Highcharts.dateFormat('%m/%d %H:%M:%S', x) + ' - ' + Highcharts.numberFormat(this.y, 2) + ' ' + toolTipUnits;
}
```

**Comment by wrabit** [comment]
Is there any reasons why applying `time.timezoneOffset` to the global object is effecting both xAxis labels AND series data timestamps (as desired). But applying it on a per chart instance is only affecting xAxis labels - the points are staying on UTC.

**Comment by KacperMadej** [comment]
@wrabit 
This might be some backwards compatibility issue - hard to be sure without a live demo. If something doesn't work as it should and if you are not only looking for a reason please let me know and add a live demo.

We are using the GitHub issues as a bug tracker and for feature requests. Your comment looks more like a technical support question so in case you are looking for tech support see https://www.highcharts.com/blog/support/
