### ISSUE TITLE
Custom Log Scale Transformation

### ISSUE THREAD

**Issue by aaronogan** [highcharts/highcharts#5171]
We'd like to be able to provide a custom implementation for log transformations but the transformation methods are private utility functions (lin2log/log2lin).  Would it be possible to make these more easily customizable?

Is this something that you'd be willing to include in your road map?  Even if you may not be able to prioritize this, we may be able to spend the time to implement this ourselves, but we don't want to maintain a forked copy indefinitely.

Thanks!

**Comment by TorsteinHonsi** [comment]
Yes, good point. We would eventually go there with Highcharts 5, but I'll do this refactoring now so that you can get started. In the upcoming commit, the lin2log/log2lin functions are moved to the Axis prototype.

**Comment by aaronogan** [comment]
Thanks very much for the responsiveness!  Do you know when this might be released?

Our custom transformation can handle values <= 0 so I think we'll still need to override a couple methods where error 10 is fired.

**Comment by TorsteinHonsi** [comment]
You're welcome! A new maintenance release will be out in a few weeks.
