### ISSUE TITLE
zone sets marker color of next zone

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#5177]
The color setting of a zone is applied to the marker color after the zone has ended ( by adding a zone with no color setting).

See http://jsfiddle.net/kzoon/d00cL1zk/2/

Line color and dashing are reset after July, but the markers are still red.

**Comment by KacperMadej** [comment]
Thank you reporting the issue, but it doesn't seem to be a bug.

You are not setting `value` for the zone - then color to the last value is set.
[API reference](http://api.highcharts.com/highcharts#series<line>.zones.value): 

> The value up to where the zone extends, if undefined the zones stretches to the last value in the series.

If you set `value`, then chart is working differently - http://jsfiddle.net/d00cL1zk/3/

**Comment by kzoon** [comment]
Kacper,

Can you please reopen this issue. There is obviously something wrong:

dashStyle: 'dot' reverts to default
color:'red' does not

Either both stop, or none of them

Koos

**Comment by TorsteinHonsi** [comment]
Hi Koos,

The thing is that when `value` is not set, the zone will extend to the end of the axis. In this case it will lead to the dashed line being overwritten by a new blue line, but the markers are already tied to the zone, so they will be red. Add an area to the mix, and you'll see that the areas are overlaid too: http://jsfiddle.net/highcharts/d00cL1zk/4/.

I'm not sure whether to call it a bug, to me it seems like a misconfiguration.

**Comment by kzoon** [comment]
Torstein,

I think I misread the documentation and misinterpreted example http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/series/color-zones-dashstyle-dot/

I can make my fiddle do what I wanted it to do (change the line between June and July): http://jsfiddle.net/kzoon/d00cL1zk/5/

I think it would be nice if I could set a startValue for a zone, so I wouldn't need a dummy zone to start with. But I agree that there is no bug here.

 I

**Comment by Akash497** [comment]
Can anyone help 
I retrieve data from excel in html table and I want show the data into highcharts so guide how I can do these

**Comment by KacperMadej** [comment]
@Akash497 
Hi, you've posted to our issue tracker.
For general tech support, please see www.highcharts.com/support.
Data module can load chart data from HTML table - http://www.highcharts.com/docs/working-with-data/data-module

**Comment by Akash497** [comment]
But here they use .csv file and I want to use .xlxs file so guide me

**Comment by Akash497** [comment]
And the another example where html table is static or predefined and I want display highcharts where data retrieve from database or excel file .xlxs and display highcharts

**Comment by TorsteinHonsi** [comment]
Please stop posting those off topic comments in this _issue report_ and follow the directions @KacperMadej gave you.
