### ISSUE TITLE
Series larger than turboThreshold cannot have nulls

### ISSUE THREAD

**Issue by jmfernandez** [highcharts/highcharts#5179]
I have realized (at least) with `spline` series which contain nulls that, when they are longer than the `turboThreshold`, fires in Google Chrome next error:

> TypeError: Cannot read property '0' of null

which corresponds to [this line](https://github.com/highcharts/highcharts/blob/98edc5bed2205591ed23281b41b585e41cf456be/lib/highcharts.src.js#L13950). So I guess some minimal null check or exception handling should be introduced here.

In the meanwhile, the workaround is setting `turboThreshold` to 0 for these series

**Comment by KacperMadej** [comment]
Could you post a live example, like jsFiddle? Nulls are longer than turboThreshold or data? I tried both, but all seems to be working just fine - http://jsfiddle.net/2k0chfg6/

**Comment by jmfernandez** [comment]
This series, http://jsfiddle.net/jmfernandez/3rocq36g/1/, with nulls (the whole point is null) and more elements than turboThreshold does not work.

This series, http://jsfiddle.net/jmfernandez/5aye8tcb/1/, with nulls (the whole point is null) and less elements than turboThreshold, does work.

**Comment by TorsteinHonsi** [comment]
I don't think it's actually a bug. Since you are also skipping the x value, Highcharts wouldn't know where to place the point anyway. If you provide the x and set y to null, it works: http://jsfiddle.net/highcharts/3rocq36g/2/

**Comment by jmfernandez** [comment]
Yes, I realized about that when I saw @KacperMadej example, but I wanted to show you the scenario where I found the issue.

In my humble opinion, Highcharts behaviour should be coherent, either always complaining about whole null point, or always allowing it, as it currently works when series is shorter than turboThreshold but not when it is longer.

**Comment by TorsteinHonsi** [comment]
I can definately relate to that. Just for the records, it is currently in accordance with the docs:

> When a series contains a data array that is longer than this, only one dimensional arrays of numbers, or two dimensional arrays with x and y values are allowed. Also, only the first point is tested, and the rest are assumed to be the same format. This saves expensive data checking and indexing in long series.

By testing only the first point, we establish that we are working on array configurations, so thereafter null points must be defined as `[x, null]`.
