### ISSUE TITLE
Highmaps API docs are missing Map() constructor.

### ISSUE THREAD

**Issue by brian428** [highcharts/highcharts#5180]
The Highmaps API docs don't include the Highcharts.Map() constructor. It includes Highcharts.Chart(), but this doesn't seem to work. Since this omission is confusing, I'd say Map() should be added (in fact, it probably should replace Chart(), yes?).

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, it's added now: http://api.highcharts.com/highmaps#Highcharts.Map
