### ISSUE TITLE
Problem using data-grouping with gaps

### ISSUE THREAD

**Issue by Ivan-Perez** [highcharts/highcharts#5181]
Hello!

I want to make some charts using some data which has some gaps. So I've set the value to `null` where a gap should be displayed. The chart looks like the following image:

![no-data-grouping](https://cloud.githubusercontent.com/assets/3533970/14273573/f3b328f6-fb0b-11e5-8c4e-c3820a7e1442.png)

Which seems correct. Then, I have enabled data grouping in my charts. But after enabling data grouping (`plotOptions.series.dataGrouping.enabled = true`) the gap has disappeared, and a line connecting the two points appears:

![data-grouping](https://cloud.githubusercontent.com/assets/3533970/14273572/f3b11156-fb0b-11e5-8c84-01b5a9a2274b.png)

I was looking in the library why does the problem occur and I found that changing a comparison in the data grouping function, my problem got solved. Look at [/js/parts/DataGrouping.js#L101](https://github.com/highcharts/highcharts/blob/master/js/parts/DataGrouping.js#L101). If I change that comparison to be an OR instead of AND, the gap appears correctly.

I don't know why is this happening and if such correction is even correct - or if there is something I'm missing. Maybe returning `null` instead of `undefined` in such functions has a special meaning, that would explain why changing the comparison works for me.

Thanks for your help!

**Comment by TorsteinHonsi** [comment]
If there are any non-null values within each group, our algorithm is supposed to return a value, so the line in question is correct. But I am not sure why the grouping algorithm finds the many null groups in between that stretch. 

Anyway, by setting a `gapSize` you achieve what you want: http://jsfiddle.net/highcharts/9p7vek7L/.

**Comment by Ivan-Perez** [comment]
OK, thank you, using `gapSize` my issue gets solved :+1: 

Anyway, I've created a jsfiddle with the data I was using, so you can decide if that line was correct or shouldn't appear: https://jsfiddle.net/yo59yvn8/2/ As you can see there is no data on that interval, therefore I think it shouldn't appear even without using `gapSize`.
