### ISSUE TITLE
Cannot set property 'd' of null

### ISSUE THREAD

**Issue by ulrik59** [highcharts/highcharts#5182]
Hi,

I am using `Rollup` bundler which is like `Browserify` or` Webpack` for `Highcharts` (I use the plugin `rollup-plugin-commonjs`).
I was previously using without problems `Highcharts` with `RequireJS`.
But with `Rollup` I have this weird issue : 
![capture du 2016-04-05 15-36-59](https://cloud.githubusercontent.com/assets/6003644/14283618/57ed893c-fb44-11e5-9c18-dad05173e7e5.png)

Apparently this is in `highcharts.src.js` line 3136 : 
![capture du 2016-04-05 15-40-20](https://cloud.githubusercontent.com/assets/6003644/14283721/babbd4b0-fb44-11e5-9553-b58d5a68de04.png)

It seems that the context is lost and `this` is null.
The bugs is present in Highcharts 4.2.3 and 4.2.2 but it doesn't seem present in 4.2.1.

Thanks in advance !

**Comment by pawelfus** [comment]
Thank you for reporting. Anything special you need to do to see that error? Or maybe it shows up when initializing chart? I see a lot of errors, so I guess it's connected somehow to the tooltip (mouseover), or other user-actions. 

Live demo would be great, se we can debug it with a full stack. Also, could you try our master branch? http://github.highcharts.com/highcharts.src.js

**Comment by ulrik59** [comment]
I just test your master branch and the problem disappear. I supposed you have already fixed this bug.
Unfortunately, using your master branch, another problem appear when clicking on a point element : 
![capture du 2016-04-05 16-47-50](https://cloud.githubusercontent.com/assets/6003644/14286081/2a94e462-fb4e-11e5-8a5d-b9c2b335e626.png)

The bug is apparently line 1303 in your [http://github.highcharts.com/highcharts.src.js](http://github.highcharts.com/highcharts.src.js) file.
![capture du 2016-04-05 16-50-58](https://cloud.githubusercontent.com/assets/6003644/14286256/bd4ef0d6-fb4e-11e5-8dd2-739f79a5aa02.png)

I don't have time to do a jsfiddle for now if that's necessary. I'll try to do one soon.

**Comment by ulrik59** [comment]
All is resolved in 4.2.4. Thank you !
