### ISSUE TITLE
Not able to fix tickInterval while loading dynamic data in x-range series. 

### ISSUE THREAD

**Issue by nigamg** [highcharts/highcharts#5184]
Hi, 
I am struggling to get x-range series working with dynamic. My x-range series starts for a fiscal year, while loading dynamic data, tick intervals always get changed due to auto scaling. So for one data set, show intervals may Jan, Feb, Mar,.....Dec and for other, it is only Jan, Jun, Dec. How can I fixed it in datatime series where I can display month all the time.

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

Having said that, you probably want to set [xAxis.tickInterval](http://api.highcharts.com/highcharts#xAxis.tickInterval) to something like `30 * 24 * 36e5`.
