### ISSUE TITLE
Grid line overlaps plotLine

### ISSUE THREAD

**Issue by nitoloz** [highcharts/highcharts#5185]
I am using highcharts to draw a line chart with multiple horizontal plot lines on it, but I am facing an issue that sometimes the grid line overlaps the plot lines. The could be easily reproduces when the plot height is quite small and there are about 4-5 horizontal grid lines.
I have faced the similar issue working with D3.js and solved it by adding plot line after grid lines, so the plot line would overlap grid line if they have the same coordinates.

Here are some images with clarification:
The plot line (is hidden under grid line):
![highcharts_1](https://cloud.githubusercontent.com/assets/7154361/14310698/06b0365c-fbec-11e5-9879-0046b297b5e0.png)
The grid line, that overlaps plot line:
![highcharts_2](https://cloud.githubusercontent.com/assets/7154361/14310705/10c36f10-fbec-11e5-822b-4c8cfbe623b0.png)
The plot line is visible if I remove 1 of grid lines (note: there are only 4 grid lines instead of 5 in elements):
![highcharts_3](https://cloud.githubusercontent.com/assets/7154361/14310739/434f64f2-fbec-11e5-8ba9-6acfe1331767.png)

**Comment by pawelfus** [comment]
Hi,

Thank you for contacting us. You can change [`zIndex`](http://api.highcharts.com/highcharts#yAxis.plotLines.zIndex) of a plotLine.

Compare:

- `zIndex: 1`: http://jsfiddle.net/vcz3hq92/
- without `zIndex`: http://jsfiddle.net/vcz3hq92/1/

**Comment by nitoloz** [comment]
@pawelfus thanks a lot!
This helped
