### ISSUE TITLE
Data grouping and sparse data sets not working properly

### ISSUE THREAD

**Issue by slozier** [highcharts/highcharts#5188]
I'm having issues getting sparse data sets to display properly when plotting a non-sparse data set on the same graph. It appears to be an issue with data grouping which ends up losing important information.

For example, if I have a data set [[0,0],[999,0],[1000,1],[1001,0],[2000,0]] I would expect something with a spike in the middle, but that is not what occurs. (I also noticed that the data grouping appears to be affected by the order of the series.)

Sample code: https://jsfiddle.net/cvox4v8z/

**Comment by pawelfus** [comment]
I think this may be connected to #4874 (also issue with order of series and different dataGrouping applied).
