### ISSUE TITLE
Different marker position in other browsers

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5189]
The movements are little, but appears.

Example:
- http://jsfiddle.net/6wprcdu6/

![2016-04-07 12 41 34-01](https://cloud.githubusercontent.com/assets/2115686/14345614/3bbe7274-fcae-11e5-90cd-4a80b78b35a0.jpg)

**Comment by TorsteinHonsi** [comment]
It may be because of different handling of subpixel positions inside an iframe. Do you see the same issue when not running inside an iframe, like http://jsfiddle.net/6wprcdu6/show?

**Comment by jon-a-nygaard** [comment]
Closing this since it is pending a reply and considered inactive.
