### ISSUE TITLE
Different marker position in other browsers

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5190]
The movements are little, but appear.

Example:
- http://jsfiddle.net/6wprcdu6/

![2016-04-07 12 41 34-01](https://cloud.githubusercontent.com/assets/2115686/14345614/3bbe7274-fcae-11e5-90cd-4a80b78b35a0.jpg)

**Comment by pawelfus** [comment]
Duplicate of #5189.
