### ISSUE TITLE
Multi line title issue

### ISSUE THREAD

**Issue by shilmypx** [highcharts/highcharts#5191]
Buggy rendering of multi-line titles and descriptions (text overlaps the graphics), any CSS or javascript solutions to solve this issue?

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Did you forget to add the steps to reproduce? In [this basic demo](http://jsfiddle.net/highcharts/gvehsjvm/) the title doesn't overlap the plot area. Can you modify the demo to demonstrate your issue?

**Comment by shilmypx** [comment]
It does not work if I want to break the line wherever I want but later I figured out using <br> inside the title text it is possible and working fine. Thanks
