### ISSUE TITLE
Series disappears after zoom

### ISSUE THREAD

**Issue by xSirrioNx** [highcharts/highcharts#5194]
Hi!
I'm not sure that it is a bug, but then i try to zoom in series are disappeare.
May be this is because of many Null points in data array...
[JsFiddle](http://jsfiddle.net/nj8rk1nj/7/)

**Comment by KacperMadej** [comment]
Hi, you've posted to our issue tracker.
For general tech support, please see www.highcharts.com/support.

When data is grouped than, nulls are summed with non-nulls and points are visible. When zoomed in nulls are not connected with points with non-null values, so you could enable markers(1) or set connectNulls to true(2).

Examples:
1) http://jsfiddle.net/apuup0qa/1/ (accurate to data)
2) http://jsfiddle.net/apuup0qa/ (looks better)

**Comment by xSirrioNx** [comment]
KacperMadej, thank u for answer!
