### ISSUE TITLE
motion.js exporting incorrect chart state

### ISSUE THREAD

**Issue by pkfranz** [highcharts/highcharts#5196]
See Highcharts official example: http://jsfiddle.net/larsac07/pbezw72b/?utm_source=website&utm_medium=embed&utm_campaign=pbezw72b

Highcharts/maps built with the motion.js as a separate include break the exporting functionality for PNG/JPEG/GIF/JPEG.  No matter what state is selected on the play-controls, the exporting function always saves the _final state_ of the chart.

Printing does _correctly_ export the selected state, but glitches the play controls after export.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, I moved this issue to https://github.com/larsac07/Motion-Highcharts-Plugin/issues/6.
