### ISSUE TITLE
Pie chart is not align properly when dispalyed in bootstrap carousel

### ISSUE THREAD

**Issue by damianszczepanik** [highcharts/highcharts#5198]
I have three pie charts combined together into bootstrap carousel. When displaying then on wide screen some charts are not centered. I found than when problematic chart is displayed alone in carousel it looks fine. Changing the order of charts does not solve the problem

![pie](https://cloud.githubusercontent.com/assets/9612911/14406478/f240b0a6-fea8-11e5-85f9-a26ce730e91f.png)

Code: https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/resources/templates/pages/featuresOverview.vm

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
