### ISSUE TITLE
Chart.addAxis() offsets any previous yAxis to the right

### ISSUE THREAD

**Issue by kernc** [highcharts/highcharts#5199]
Whenever `chart.addAxis()` is called dynamically to construct a new y-axis, all the previous axes (including navigator) are offset some amount to the right, specifically the `.highcharts-yaxis-title` and `.highcharts-yaxis-title > path` (axis line) and `.highcharts-yaxis-labels` and `.highcharts-navigator` seem to have their respecitive default x-offsets reapplied to their current x-offsets.

Demo: https://jsfiddle.net/q00k2kwh/

**Comment by pawelfus** [comment]
Hi, I think you want to set [`yAxis.offset = 0`](http://api.highcharts.com/highstock#yAxis.offset), take a look: https://jsfiddle.net/q00k2kwh/5/

**Comment by kernc** [comment]
Indeed, thanks! But why does it come to this? The documentation says `offset` defaults to 0 anyway, and I don't override this anywhere. You sure there isn't something odd going on in `addAxis()`?

**Comment by TorsteinHonsi** [comment]
New axes make room for other axes on the same side. As seen in the [Highstock pane demo](http://www.highcharts.com/stock/demo/candlestick-and-volume), we need to set `offset` to 0 to prevent this.

Boiled down to the essence, this simple demo shows it: http://jsfiddle.net/highcharts/d5pLrh7u/.

An enhancement here would be to check for the `top`, `left`, `height` and `width` options. If those are different between two axes, they belong to different "panes", and don't need to adjust to eachother. 

@jon-a-nygaard Can you have a look at this? Perhaps we can add this test without too much effort and extra code. Entry point: `Axis.getOffset()`.

**Comment by kernc** [comment]
Ah, I understand, they make adjustments for axes line, title, and labels. I think adding a note to the docs is a less intervening option and is less likely to have any unexpected adverse effects. Thank you both.

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi: I had a look and it is completely doable, but a bit cumbersome in my opinion. Easy way in is to loop all the axes and compare them the way you mentioned. But this would be done every time 'getOffset' is called. Potentially a lot of work for something little.

Also when the axes pass the test and offset is set to 0, the tick labels would have to be adjusted to avoid collision. Visible in this example: http://jsfiddle.net/f40ktgvv/1/

What do you think, should I invest more in this solution?

**Comment by kernc** [comment]
FWIW, I think a note in the docs is fine. If anything, perhaps also in the section for `Chart.addAxis()`.

**Comment by jon-a-nygaard** [comment]
A short note has been added to [offset](http://api.highcharts.com/highcharts#xAxis.offset) and [addAxis](http://api.highcharts.com/highcharts#Chart.addAxis).

@kernc Thank you for the comments, we highly appreciate all user feedback.
