### ISSUE TITLE
Flag series placement

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#5200]
Issue on the master branch, fails since: https://github.com/highcharts/highcharts/commit/cc46d69

Example: http://jsfiddle.net/u1aa7g36/

**Comment by TorsteinHonsi** [comment]
Thanks, I can't see anything wrong with the fiddle. I think I fixed it yesterday with a217ce9957b.

**Comment by pawelfus** [comment]
That's right, now it works fine.
