### ISSUE TITLE
Highmaps: mapline's lineWidth ignored in IE11

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5201]
lineWidth setting is not working in IE11 - `stroke-width="inherit"` is used while Chrome is having `stroke-width="30"` - as set in options.

Example: http://jsfiddle.net/5fgvbnvx/

**Comment by TorsteinHonsi** [comment]
IE sets the stroke width on the parent group while the others set it on each individual element. It's because of how the `vector-effect` attribute is used in zooming. @oysteinmoseng something may be wrong with how this duality works.

**Comment by KacperMadej** [comment]
The fix is looking good on IE11, Edge, Firefox and Chrome on Windows 10.
