### ISSUE TITLE
Highmaps : hover state disabled issue

### ISSUE THREAD

**Issue by zbMax74** [highcharts/highcharts#5202]
Hi there,

If you disable the hover state in the options, it remains a glitter on the area when the mouse is leaving it. Issue reproduced here:
https://jsfiddle.net/9ew0khuj/

Thanks.

**Comment by TorsteinHonsi** [comment]
The issue is still present, but the fix is no longer valid for HC5.

**Comment by TorsteinHonsi** [comment]
FYI @oysteinmoseng I threw out the baby and the bathwater and everything by removing the animation logic in maps. It is now handled on a lower level, equal to column and column-derived series.
