### ISSUE TITLE
Heatmap - colors change when legend is disabled

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5205]
Let's compare two examples:
- http://jsfiddle.net/h27zx8my/
- http://jsfiddle.net/vLtc1tz6/

Colors seems to be applied incorrectly.

**Comment by KacperMadej** [comment]
**Workaround:** 
- set tickPositions for colorAxis - http://jsfiddle.net/vLtc1tz6/1/
- or set to false startOnTick and endOnTick for colorAxis - http://jsfiddle.net/vLtc1tz6/2/

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng Looks like Axis padding is not applied when the color axis is not visible (in the legend). Check what's going on and we'll discuss.
