### ISSUE TITLE
plotOptions borderWidth doesn't check type of argument

### ISSUE THREAD

**Issue by afresh1** [highcharts/highcharts#5207]
Due to some obfuscation, we ran into an issue in Safari where we accidentally set `borderWidth: true` instead of `borderWidth: 1`.  This surprisingly seemed to mostly work, but in Safari the graph contents would intermittently disappear and if you open the javascript console it show 'Error: Invalid value for <rect> attribute width="NaN"'.

It would be preferable if we got an error from Highcharts saying that borderWidth must be a number.

We could only reproduce this in Safari and only if the "Web Inspector" is closed.  

On my test machine, [this fiddle will trigger the issue within a few minutes of running](http://jsfiddle.net/4Lt4gL4x/).

This is in Safari 9.1 (1060.5.17.4) on several recent versions of OS-X including 10.10.5.

**Comment by TorsteinHonsi** [comment]
There are various cases where bad configuration settings will cause unpredicted things to happen, so it is a greater question whether we should type check and verify all settings against the types specified in the API. Type checking of all hundreds of options would mean overhead in terms of code weight and performance.

**Comment by afresh1** [comment]
Someone at work suggested possibly a "strict mode" you could enable that would run these checks in a test environment but that could be disabled in production.

**Comment by TorsteinHonsi** [comment]
Yes, that could be a middle way.

**Comment by pawelfus** [comment]
Connected [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/3474234-provide-a-typescript-version-for-your-javascript) idea. I think it can be generated from API JSON?
