### ISSUE TITLE
Set style of markers for column, pie

### ISSUE THREAD

**Issue by kernc** [highcharts/highcharts#5208]
Feature request: Please make available styling the markers (i.e. `plotOptions.series.marker.states.*`)  of column and pie series (effectively their patches).
Neither `hover` nor `selected` styles work, and although your API's search recommends
`plotOptions.column.states.hover.marker` as a valid key, there seems to be no content behind it.

**Comment by TorsteinHonsi** [comment]
Hi,

It seems like a bug in our API that the search box suggests `plotOptions.column.states.hover.marker`, although that option doesn't actually exist.

Also, the `color` and `borderColor` can be set for the hover state, which wasn't documented. I've added those now. See http://jsfiddle.net/highcharts/fw27yger/ for live demo.

**Comment by kernc** [comment]
Thanks, `color` and `borderColor` seem to work also with `plotOptions.column.states.select`.

**Comment by pawelfus** [comment]
Fixed in docs since v5.
