### ISSUE TITLE
HighCharts- Enabled scrollbar prev & next always.

### ISSUE THREAD

**Issue by donotopen47** [highcharts/highcharts#5213]
I have enabled scroll bar for my charts & I want to enabled next & prev  always as I have to make an ajax call after scroll is reached at the end. please suggest me a solution.

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

**Comment by donotopen47** [comment]
Thankyou Honsi.............
