### ISSUE TITLE
Column chart `setData`, changing color of points does not work

### ISSUE THREAD

**Issue by hjnilsson** [highcharts/highcharts#5214]
#### Expected behaviour
Calling setData with a new data array, that does not have color set should revert all points to the series color.

The documentation says:

> Note that this method throws away all points and creates new ones. For updating the values of existing points, use Point.update() instead.

I would expect this to mean, that if I do not set a certain property, it should revert to the default value from the series. 

#### Actual behaviour
The Points retain the color (and other properties) they have set previously.

Either the documentation should state that properties set on point's are retained, or not setting a property should cause it to revert to the default value.

#### Live demo of the issue
http://jsfiddle.net/boz035te/

#### Workaround
The issue is easily worked-around by explicitly setting `color` on every point.

**Comment by pawelfus** [comment]
It's not really a bug, since Highcharts 3.0.10, there is an additional param: `updatePoints`, which updates points if number of them is the same. Setting this to `false`, gives to the expected behaviour: http://jsfiddle.net/boz035te/1/

[API](http://api.highcharts.com/highcharts#Series.setData).

**Comment by hjnilsson** [comment]
That option is not the same, because it removes animation (which changing the `color` property on the point allows).

**Comment by pawelfus** [comment]
That's the point of `updatePoints`, right? Remove old points, and create new ones (when set to `false`). When it's set to `true` it will update points, so old colors will remain. There's also no animation when number of points is different than the original data: http://jsfiddle.net/boz035te/2/ 

In short, points are animated when are updated. When points are updated, then old config object remains.

**Comment by hjnilsson** [comment]
Yes, but the function description says: "Note that this method throws away all points and creates new ones. For updating the values of existing points, use Point.update() instead", this is not consistent with the default behaviour.

The documentation should be updated to reflect the actual behaviour. (Or the change the default to  updatePoints: false so it matches with what the function does).

**Comment by TorsteinHonsi** [comment]
If you want to reset the color in the red point, you can pass `color: null`. 
http://jsfiddle.net/highcharts/boz035te/3/

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestions for the documentation, it has been updated now.
