### ISSUE TITLE
Formatter for x values

### ISSUE THREAD

**Issue by likwifi** [highcharts/highcharts#5216]
#### Actual behaviour
chart x values are not passed to Highcharts.numberFormat
#### Live demo of the issue
http://jsfiddle.net/LrLx1oLd/

**Comment by jon-a-nygaard** [comment]
Hi @likwifi, which numbers are you looking to format, e.g. axis labels, tooltip, or datalabels?
If it is the tooltip you should use the `tooltip.pointFormat`, it uses a Python syntax for number formatting, like so: http://jsfiddle.net/highcharts/jLz6b7sy/

**Comment by likwifi** [comment]
Hi @jon-a-nygaard 
![bug](https://cloud.githubusercontent.com/assets/1791670/14559315/dc635166-0318-11e6-89f1-8d3f71a75ad2.png)


please refer to screenshot y value is not passed from Highcharts.numberFormat method

**Comment by jon-a-nygaard** [comment]
Yes, the numberFormat is not intended to be used like that, all numbers in Highcharts are not necessarily passed through it, it is more of a utility function. 
As I mentioned previously the tooltip.pointFormat will probably solve your issue.
I believe this example shows what you want to achieve: http://jsfiddle.net/9dfuez6z/

**Comment by likwifi** [comment]
@jon-a-nygaard I'm using more advanced formatter method for values. and simple tooltip.pointFormat with fixed decimal points will not work for me.
In my understanding all values should be passed through numberformat method, otherwise what was reason for defining it?

**Comment by jon-a-nygaard** [comment]
@likwifi My apologies as I have misunderstood the issue. Your intended use of the numberFormat is completely correct. 

But it is not certain that the x value should be passed to the numberFormat by default, and I am currently investigating which is the correct behavior.
Meanwhile you can enforce it into the numberFormat, by suffixing it with a format in pointFormat: http://jsfiddle.net/zavz7b9f/1/

**Comment by jon-a-nygaard** [comment]
This issue will be fixed in the next maintenance release. For those in a need of a immediate fix can use the workaround mentioned in the previous comment.

**Comment by jon-a-nygaard** [comment]
X values should not be passed through the `numberFormat` by default. This is because it should not be affected by valuePrefix or valueSuffix. For advanced formatting then the formatter function is recommended.
