### ISSUE TITLE
performance problem with formatter method for data label with large data

### ISSUE THREAD

**Issue by hamed-mahdizadeh** [highcharts/highcharts#5227]
Hi
I have a performance problem in plotOptions>Series>datalabel>formatter of highstock with large data. If I use a few simple condition for adding datalable to special points, it takes a long time for drawing chart so I tried to use update method of groupedData in redraw event to add datalable for special points but if I pass false to update method for disabling redraw I will face with error #15 and if I set redraw parameter of update method to true I will face another error (probably for recursive endless call of redraw method).

**Comment by hamed-mahdizadeh** [comment]
Performance problem solved by using turboThreshold: 2000

**Comment by TorsteinHonsi** [comment]
Thanks for reporting. In http://jsfiddle.net/highcharts/5kybt9ku/, I see it lags a bit. I think it is the mere number of points that slows it down. Some of data labels are hidden anyway. One possible solution could be to increase the `dataGrouping.groupPixelWidth`.
