### ISSUE TITLE
Title of opposite yAxis renders outside of plot with align 'high' at bar chart.

### ISSUE THREAD

**Issue by LiomSV** [highcharts/highcharts#5230]
Adding of opposite option to yAxis of bar chart makes title to render outside of plot.

#### Live demo of the issue
http://jsfiddle.net/5jbzyv3m/

**Comment by jon-a-nygaard** [comment]
@LiomSV  Thank you for reporting. I am currently working on this and will come back to you when I know some more.

**Comment by jon-a-nygaard** [comment]
_Internal note: axis title has attribute text-anchor="start" when it probably should be "end"_

**Comment by jon-a-nygaard** [comment]
@LiomSV Apparently `opposite: true` and `align:high` will set `textAlign` to left. I am not yet sure if this is correct behavior for a horizontal axis, but you can avoid this issue by setting `textAlign` to desired alignment. [Example of textAlign set to right](http://jsfiddle.net/jon_a_nygaard/x183shfk/1/)

**Comment by LiomSV** [comment]
It's acceptably solution. Thank you for quick response.

**Comment by jon-a-nygaard** [comment]
@LiomSV Your'e welcome, glad I could be of help.
