### ISSUE TITLE
Border in between slices without border on outside radius of pie?

### ISSUE THREAD

**Issue by shonatodc** [highcharts/highcharts#5233]
I've spent quite a bit of time googling and ripping through the API and couldn't find anything on how to add borders just in between slices, without a border on the radius of the pie?

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

To answer your question, I'm afraid this is currently not possible, since the sliced are one single SVG shape, and the stroke applies to the full path.

**Comment by shonatodc** [comment]
Ah, thank you. Keep up the good work.
