### ISSUE TITLE
Data not showing in Scatter plot

### ISSUE THREAD

**Issue by cima007** [highcharts/highcharts#5234]
#### Expected behaviour
Show a scatter plot with data 

#### Actual behaviour
The graph is sending a message of no data, but there actually is data

#### Live demo of the issue
https://jsfiddle.net/cima007/k80Lcf19/4/
if you click the first serie it will show the whole data.

#### Affected browser(s)
Tried only in chrome

#### Solution
I found that when the first data point (x) of a serie has a value of NULL, the whole graph doesn't show anything, when i correct this in the php code (replacing null for a 0), it worked like always.

hope it helps someone :)

**Comment by jon-a-nygaard** [comment]
@cima007 Hi, could you provide a [JSFiddle](https://jsfiddle.net/) of your issue? It will be of great help for debugging.

**Comment by TorsteinHonsi** [comment]
I tried reproducing based on your description at http://jsfiddle.net/highcharts/yLqs279d/, can you modify this to demonstrate your issue?

**Comment by jon-a-nygaard** [comment]
@cima007 Nevermind, I understand the issue now, it can be seen in this example: http://jsfiddle.net/jon_a_nygaard/58gxxhsn/

**Comment by jon-a-nygaard** [comment]
@cima007 x values can not have the value null, it is not considered as valid. But x values can be undefined, then it will be automatically incremented. This information was missing from our API and we will update it to avoid uncertainty around how it behaves.

We would also like to ask if you consider this behavior to be correct, or should `x=null` be handled different in your opinion?

**Comment by cima007** [comment]
Thanks for the quick reply.
I updated my comment with the live demo.
The x value should not be null, but i have seen a lot of databases that are far from the ideal behavior in a variety of industries.
I had the opportunity to ask experts in data science ([C. Hidalgo](https://www.media.mit.edu/people/hidalgo), [R. Baeza ](https://users.dcc.uchile.cl/~rbaeza/spanish.html) ) and they say, that you should always graph your data (whatever you have) as soon as possible. So you can work in the constant improvement of the records, for a better understanding of the reality.

With that in mind, i think that when i have a null point in a scatter plot, the graph should tell me there is something wrong with that point in particular, (a message or highlight). Which lets the user find out where does that mistake comes from, even if x and y are null.

Obviously it's an ideal, i love highcharts and the way it works, but like any program ther is space for improvement :)

**Comment by TorsteinHonsi** [comment]
I second that. The chart shouldn't break even though we have an invalid value.
