### ISSUE TITLE
setData fails

### ISSUE THREAD

**Issue by aledand** [highcharts/highcharts#5235]
#### Expected behaviour
clicking "+" (top,left button) series is updated

#### Actual behaviour
series disappear at all

#### Live demo of the issue
http://jsfiddle.net/aledand/7kqLyrht/46/

#### Steps to reproduce the behaviour
click "+" (top,left button)
to prove is not a problem with external call, ucomment the setData in the chart event click handler and will be seen the same behaviour

#### Affected browser(s)
IE, Chrome, FF

**Comment by jon-a-nygaard** [comment]
@aledand Hi, it seems you are trying to pass the data in a string format, which is not going well. Remove the single quotes and your code is working well, [like in this example](http://jsfiddle.net/jon_a_nygaard/ou9c8t7u/)

**Comment by aledand** [comment]
sorry, a stupid mistake in the example, I've not seen it because leading to the same problem I'm having since last highcharts update. I do not succeed to reproduce in jsfiddle :-( 

.... in my site a piece of code is used at load time and it works, the same called a second time by interval breaks the polar chart. If I change from polar to normal columns the issue disappear. Can I link here my site ?

thanks a lot in any case

**Comment by jon-a-nygaard** [comment]
No worries. We prefer of course if you are able to reproduce it in jsfiddle, but I can have a look at your site to see if I notice something.

**Comment by aledand** [comment]
thx

http://aledand.net/wp/ ... sorry in Italian

it fetches wind data from a db via a PHP script, and shows every 120 sec the updates on polar and line charts. 

after the first load, which works fine, the same "requestData()" function raise an error at setData reporting "InvalidCharacterError: String contains an invalid character". 

before recent April update itwas working fine.

**Comment by jon-a-nygaard** [comment]
I have not found anything specific yet, but I see that your site reports a few errors that you should have a look at.

1.  Highcharts error 16 means that you are loading more than one instance of Highcharts. The files are for instance `http://code.highcharts.com/highcharts.js?ver=1.0` and `http://code.highcharts.com/highcharts.js` You should remove one of these files
2. Highcharts error 15 means that your data is not sorted, and one of your charts expects it to be.

These issues might be the cause of your issue, and if not then fixing them anyway will improve your site performance and help with debugging this issue.

**Comment by aledand** [comment]
probably I've been now able to reproduce on jsfiddle, or better to make it evident.

http://jsfiddle.net/aledand/7kqLyrht/

first time you press the button the chart updates regularly and the subtitle is updated with 'post redraw', 
second time you click the post redraw does not appear showing that redraw fails and stop the script.
another effect is that the second and third columns are never resided to sync with the changed axis.

**Comment by aledand** [comment]
![image](https://cloud.githubusercontent.com/assets/16290271/14715532/766d2276-07e9-11e6-8e03-1675f2e6d281.png)

problem seems to be about element:path for what is attempted to update an undefined attribute

**Comment by jon-a-nygaard** [comment]
@aledand It seems this is related to the issue #5220. It has been fixed in the bugfix branch which means that it will be fixed in the next maintenance release.

Until then, as a workaround you can use the `highcharts-more.js` from our bugfix branch, like in [this example](http://jsfiddle.net/jon_a_nygaard/bLbqh5w2/)

Or if you would like to avoid using a file which is under development, then you can edit your own `highcharts-more.src.js` and apply the changes done to it in [this commit](https://github.com/highcharts/highcharts/commit/c8ec101a88fd10de0711c28fc945b0f5454f79fe#diff-fdbd2a6ce6f75249c38c16a65ef3f5a1R2604)
