### ISSUE TITLE
Last visible point not always hoverable

### ISSUE THREAD

**Issue by sirxemic** [highcharts/highcharts#5236]
#### Expected behaviour
All visible points should be hoverable. E.g. I want the marker line and tooltip to update when I move close to the last visible point.

#### Actual behaviour
In the test case it doesn't happen when the chart is wide. However, when it's less wide, it works fine.

#### Live demo of the issue
http://jsfiddle.net/qxpn4kbs/

#### Affected browser(s)
Tested in Chrome 49.0.2623.112m and Firefox 45.0.2

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! An interesting observation is that if you make the chart 999px or 1001px wide the last point is included, but with 1000px is it not. This indicates rounding issues.
