### ISSUE TITLE
Radial (polar) heatmap

### ISSUE THREAD

**Issue by kernc** [highcharts/highcharts#5239]
#### Expected behaviour

I would expect to get a polar (radial) heatmap with the following config:

``` js
chart: {
   type: 'heatmap',
   polar: true
}
```
#### Actual behaviour

Instead, I can fake the polar heatmap with a stacked, polar column chart (demo) or a multi-layer pie chart, where I have to specify my own colors and where I lose the neat, interactive legend.
#### Live demo

https://jsfiddle.net/avxg2za9/1/
#### Additional info

[Radial (discrete) heatmaps are quite popular](https://www.google.com/search?tbm=isch&q=%28radial+OR+polar%29+heatmap), particularly also for time series data, where the concentric circles liken the time spiral. If adding `polar: true` transformation is a fairly simple endeavor, please add it to heatmap. With some guidance, I can give it a try.

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestion! I think this should be feasible by tapping into the same logic that turns columns into arcs. I set up a boilerplate at http://jsfiddle.net/highcharts/o9e60vnp/, but something with the geometry is wrong. You could start from this if you want to give it a try.

**Comment by laurahelde** [comment]
I would love this too! Have either of you continued to work on it at all?

**Comment by pawelfus** [comment]
It looks like a problem with `colorAxis`: http://jsfiddle.net/o9e60vnp/1/ - in fact it looks like a stacked-column chart: http://jsfiddle.net/tmxoynk1/ (just values should be exactly the same )

**Comment by tnrn9b** [comment]
Here are some options that get closer to what you want: 
https://codepen.io/TommyTank/pen/dRQQBb
http://jsfiddle.net/tommytank_mu/rn5d8dz0/1/

**Comment by pawelfus** [comment]
Get a chance to work on it a bit:

- it looks like geometry is wrong because is applied twice

Examples:
- categorized axes: http://jsfiddle.net/BlackLabel/kxznatLf/
- linear axes: http://jsfiddle.net/BlackLabel/kxznatLf/2/

There is still issue with points in the center (triangle-like) - size should be probably doubled
