### ISSUE TITLE
Polar chart with panning enabled freezes browser

### ISSUE THREAD

**Issue by kernc** [highcharts/highcharts#5240]
#### Steps to reproduce the behaviour

I have a polar stacked column chart with panning enabled (for whatever reason).

``` js
chart: {
    type: column,
    polar: true,
    panning: true
}
```

When I click and drag the resulting chart around, the browser freezes.
#### Expected behaviour

On click + drag, in this case, regardless of the panning flag, none.
#### Actual behaviour

The browser hangs, spinning inside [this while loop](https://github.com/highcharts/highcharts/blob/9f720a14631f06af07edfde974aaaf92bfe061cd/js/parts/Axis.js#L643). The problem seems to be `this.max` set to and propagated as some arbitrary large (1e7+) value.
#### Live demo of the issue

Click the chart + drag it around a bit. Try a couple of times. WARNING: Even if you _Stop the script_, your browser might hang.

https://jsfiddle.net/avxg2za9/
#### Affected browser(s)

Firefox 38 ESR.

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng We don't have logic to capture panning movement in a polar coordinate system, so we may as well disable it.

**Comment by TorsteinHonsi** [comment]
The issue doesn't happen in v5.0.11.
