### ISSUE TITLE
Selection event is not fired after chart is rebuild several times

### ISSUE THREAD

**Issue by nitoloz** [highcharts/highcharts#5242]
#### Background
I am using Highcharts line plot with a single line on it and nothing else. In my application there are some cases when chart is rebuild with the same data as it was build previously due to many things like filters and etc. The problem is that when I rebuild a chart with the same data multiple times the selection stops working. I am sure that I am using 'xy' zoomType.

#### Expected behaviour
The selection event is thrown when the chart is selected. 
User is able to select the area using mouse click - mouse drag - mouse drop

#### Actual behaviour
The selection event is not thrown.
User is not able to mark the selected area using the selection rectangle.
The behavior is following: 
- mouse down
- mouse move (everything is OK, selection rectangle appears)
- mouse up (Fail. Selection rectangle is not fixed and selection event is not thrown). The selection rectangle remains moving being fixed at the starting point only.
If I press mouse again the selection rectangle starts being drawn from the point where the click was made and it is impossible to remove it anymore.

#### Steps to reproduce the behaviour
Unfortunately I can not give exact steps to reproduce without my app, but it should be smth like:
- Create chart
- Recreate the same chart with the same data
- Try to select
- Verify the selection event is not thrown

#### Affected browser(s)
Chrome Version 49.0.2623.112 m

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! Unfortunately I am not able to reproduce the issue. Can you modify [this demo](http://jsfiddle.net/highcharts/qaps4y9g/) in order to show the bug?

**Comment by nitoloz** [comment]
Dear @TorsteinHonsi 

Thank you for a quick response!
Unfortunately I can not reproduce this bug outside my application as well, so I just hoped that you have already faced some similar problems or know what may cause such an issue, because this seems to be charts related.

Andrey

**Comment by pawelfus** [comment]
@nitoloz : you probably have errors in JS console. Have you checked them?

**Comment by nitoloz** [comment]
@pawelfus no, there are no errors. even not a warning

**Comment by pawelfus** [comment]
Without live demo we can only guess what is wrong. I remember similar issue, but there were errors in console, so we could figure out some workaround at least. Are you sure you have latest (4.2.4) version of Highcharts? Also, could you try our master branch ( http://github.highcharts.com/highcharts.src.js ) ?

**Comment by nitoloz** [comment]
Dear @pawelfus @TorsteinHonsi 

Sorry for a delay and thank you for the latest release, it fixed the problem described.

Best regards,
Andrey
