### ISSUE TITLE
Axis label overlap on broken axis

### ISSUE THREAD

**Issue by nchampenois** [highcharts/highcharts#5243]
When using broken axis, date is well broken on axis, but label is displayed, so it overlaps :

http://jsfiddle.net/3n87r3Lk/

**Comment by TorsteinHonsi** [comment]
Normalized demo, without datetime axis: http://jsfiddle.net/highcharts/3n87r3Lk/1/

**Comment by TorsteinHonsi** [comment]
#### Workaround

Tap into the logic used to prevent overlap on data labels: http://jsfiddle.net/highcharts/3n87r3Lk/2/

**Comment by nchampenois** [comment]
Thanks for your quick fix, but in your example break is from 100 to 199, so it should show 200 on x axis, but there it shows 100, and not 200

**Comment by TorsteinHonsi** [comment]
I would say that's a matter of preferance, but it seems you can prefer the last of the two colliding labels by reversing the incoming array: http://jsfiddle.net/highcharts/3n87r3Lk/6/
