### ISSUE TITLE
The series path is out of clippath when use history.push()

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5244]
#### Actual behaviour

The line serie is out of clippath.
#### Live demo of the issue

http://jsfiddle.net/2Ls0Lmdf/
#### Steps to reproduce the behaviour
1. Click the switch button
2. Move handle 
3. Line serie is out of clippath.
   ![zrzut ekranu 2016-04-25 o 15 03 38](https://cloud.githubusercontent.com/assets/2115686/14784647/ea6d7d78-0af6-11e6-9b06-34d21c794060.png)
#### Affected browser(s)

All browsers

**Comment by KacperMadej** [comment]
Smaller demo: http://jsfiddle.net/53ya64x8/

**Comment by TorsteinHonsi** [comment]
No-click, normalized demo: http://jsfiddle.net/highcharts/53ya64x8/1/

**Comment by TorsteinHonsi** [comment]
It happens because in the clipping is applied through an internal pointer to a definition. Because of various, internal pointers are [given absolute URLs](https://github.com/highcharts/highcharts/blob/v4.2.4/js/parts/SvgRenderer.js#L1269-L1275) based on `window.location.href`.

When we call `history.push()`, the href is changed, so the internal pointers become wrong. See http://jsfiddle.net/highcharts/53ya64x8/2/. 

#### Workaround
Update local pointers after running `history.pushState`: 

```js
function afterHistoryPush(chart) {
	if (chart.renderer.url !== window.location.href) {
    
    	// Get all elements with a URL clip-path
    	var elements = chart.container
        	.querySelectorAll('[clip-path*="' + chart.renderer.url + '"]');
        elements = [].slice.call(elements);
        
        // Update the clip-path with the new location.href
        elements.forEach(function (element) {
            element.setAttribute(
                'clip-path',
                element
                .getAttribute('clip-path')
                .replace(chart.renderer.url, window.location.href)
            );
        });
        
        // Update renderer.url
        chart.renderer.url = window.location.href;
    }
}
```

[View it live on jsFiddle](http://jsfiddle.net/highcharts/53ya64x8/3/).

**Comment by bozhkoms** [comment]
It works, thank you very much!

**Comment by KacperMadej** [comment]
Similar issue is caused by Angular's [routing](https://angular.io/guide/router).
Related issue - https://github.com/highcharts/highcharts-angular/issues/102

**Comment by KacperMadej** [comment]
A further activity occurs.

**Comment by pawelfus** [comment]
*Internal note:*
Test the `popstate` event. Make sure that correct URLs are compared (check how `renderer.url` is being defined). Then test all reported cases (gradient, clip-paths, filters, patterns).

**Comment by goransle** [comment]
So it seems the `popstate` event only fires on navigation (such as `history.back()`), not on the state changing.

I assume this means we will have to add a check for a state changes in the core. Any thoughts @TorsteinHonsi?
