### ISSUE TITLE
many of the plotOptions:scatter options not working on current version

### ISSUE THREAD

**Issue by keithmdragon** [highcharts/highcharts#5245]
#### Expected behaviour
ability to specify allowPointSelect, select and hover options for scatter.

also, how do i specify that i want the fill color to be the color of the point? what if i have specified the color for individual points in the series (same series)

#### Actual behaviour
they are being ignored. they work if i change "plotOptions: scatter" to "plotOptions: series"

#### Live demo of the issue
http://jsfiddle.net/kdragon/1d4sz5xs/

#### Steps to reproduce the behaviour
run and click points

#### Affected browser(s)
chrome

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

First, your series isn't a scatter series, it is a line series. Second, variables are not passed within the fillColor or other color options. See http://jsfiddle.net/highcharts/1d4sz5xs/2/.

**Comment by keithmdragon** [comment]
Hi Torstein,

sorry, my mistake, i always think scatter type when i see markers.

so, the only issue i have now, is i need to use a point's custom fillColor for hover / select. is this possible? i have a chart that instead of doing separate series, i am manually setting the point's fillColors. when i try the same technique that works with separate series, it picks up the series color (blue). i tried setting the series' color to null, but that didn't work.

here is my fiddle: http://jsfiddle.net/kdragon/1d4sz5xs/6/

you may want to comment out draggable.js, i got other issues with this, but created a separate bug for that: https://github.com/highcharts/draggable-points/issues/48

Thanks!!!
Keith

**Comment by sebastianbochan** [comment]
+1
