### ISSUE TITLE
Highmaps: Legend for Dummy Series not working in case of ColorAxis

### ISSUE THREAD

**Issue by GaneshBChandgude** [highcharts/highcharts#5247]
I have data of countries and respective numeric values. For example if I want to represent countrywise sales and highlight countries having sales above threshold value.
I have set red color for countries with sales above threshold, while blue color for countries with normal sales. I have added dummy series with color "red" to get its legend item, which works correct when colorAxis is not defined, but fails in case of colorAxis.

Actual behaviour:
In case of Color Axis, only coloraxis is being shown in legend. 
Demo on this issue: http://jsfiddle.net/djrrmk79/32/

When coloraxis is not enabled, it shows both legend items - Sales(Blue) and sales above threshold value(Red).
Demo:  http://jsfiddle.net/djrrmk79/29/

Expected behaviour:
In case of Color Axis, the sales above threshold should be shown as Legend item(Red).

Is there any way to achieve this?

**Comment by jon-a-nygaard** [comment]
@GaneshBChandgude Hi, is it this you want to achieve? http://jsfiddle.net/5xkc7pga/

**Comment by GaneshBChandgude** [comment]
Hi, 
I want a scalar color axis showing gradient and not colorAxis.dataClasses. 
http://jsfiddle.net/djrrmk79/32/
In the above JS fiddle i want red rectangle box as legend item in legend along with scalar color axis showing gradient.

**Comment by jon-a-nygaard** [comment]
You can disconnect a series from the colorAxis by setting [series.colorAxis](http://api.highcharts.com/highmaps#plotOptions.series.colorAxis) to false, like in this example: http://jsfiddle.net/djrrmk79/32/

**Comment by GaneshBChandgude** [comment]
This solution helped. Thank you!
