### ISSUE TITLE
Tooltip not appears, when we use polygon in 3d

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5248]
#### Actual behaviour

Tooltip not appears, when we use polygon in 3d
#### Live demo of the issue

http://jsfiddle.net/z1u6r8qn/
#### Steps to reproduce the behaviour
1. Run the demo
2. Hover on any edge / point
#### Affected browser(s)

All browsers

**Comment by pawelfus** [comment]
Note: 
3D currently support only Column, Scatter and Pie series types. See [docs](http://www.highcharts.com/docs/chart-concepts/3d-charts).

Demo: http://jsfiddle.net/z1u6r8qn/1/ (in the original example, `z` value was missing). Polygon is rendered as 2D simply. 

Not a solution, but as workaround, you can use [Contour](http://www.highcharts.com/plugin-registry/single/35/contour) plugin: http://jsfiddle.net/yw56rtus/

**Comment by sebastianbochan** [comment]
+1
