### ISSUE TITLE
IE10: column chart - columns are not visible

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5250]
#### Behaviour
Columns are not visible in IE10 while using HC v. 4.2.4.
After redraw columns are visible.

#### Live demo of the issue
http://jsfiddle.net/vwj84f53/

#### Affected browser(s)
IE10

**Comment by TorsteinHonsi** [comment]
@KacperMadej Can you investigate this and see when the issue appeared, and if possible suggest a solution? I had to uninstall my IE10 test machine due to hard disk space...

**Comment by zhy1stgg** [comment]
I have the same problem on IE10.
