### ISSUE TITLE
Font-Awesome integration export not working for above \uf1e2

### ISSUE THREAD

**Issue by fghamsary** [highcharts/highcharts#5251]
#### Expected behaviour
Export normally like other icons, but it won't.

#### Actual behaviour
It doesn't show anything at all in export.

#### Live demo of the issue

This is your own test:
http://jsfiddle.net/highcharts/2A7Zf/
I just changed the version of Font-Awesome and used another character, it's viewing as it should, just not exporting! You can find the new version here:
http://jsfiddle.net/fghamsary/3ay29m9e/

#### Steps to reproduce the behaviour
Just use a character above unicode \uf1e2 from Font-Awesome and you'll have the same problem.

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Probably we have an older version of FontAwesome installed on our export server. We'll check it out.

**Comment by fghamsary** [comment]
Thanks a lot for your kind reply, but a question doesn't it use the CSS that I injected to get the font?
In getSVG function I added the font in the SVG.

**Comment by gvaartjes** [comment]
No, it uses the fonts installed on the server, because we don't wait for the async download of the font through css. 
But we still need to specify it in the SVG for the download of a single SVG.

We'll update the font soon

**Comment by fghamsary** [comment]
Thanks a lot in the mean time, I found another solution for our problem. I imported the glyph that are not defined in the SVG itself, before sending to your server, and it works :)
Thanks anyhow. You can check the result here:
http://jsfiddle.net/fghamsary/3ay29m9e/

**Comment by TorsteinHonsi** [comment]
That's a nice solution, thanks for sharing!

**Comment by fghamsary** [comment]
The server is updated, thanks :+1:
