### ISSUE TITLE
Long graph title overlaps export button when export button has associated text

### ISSUE THREAD

**Issue by gfairchild** [highcharts/highcharts#5252]
#### Expected behavior
I expect the graph title to do one of two things:

1. It could automatically wrap.
1. It could allow me to specify padding. I tried to provide `spacingRight` in a `style` section, but that didn't do anything.

#### Actual behavior
As demonstrated in the screenshot below, the title overlaps the export icon:

<img width="691" alt="screen shot 2016-04-26 at 12 47 40 pm" src="https://cloud.githubusercontent.com/assets/2835900/14830269/21775e9a-0bad-11e6-88e4-4386cce5d315.png">

#### Live demo of the issue
https://jsfiddle.net/gbo5xamx/6/

#### Steps to reproduce the behavior
Add clarifying text to the export button and have a long graph title.

#### Affected browser(s)
* Firefox 45.0.2
* Chrome 50.0.2661.86
* Safari 9.1

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestions, this has been considered for a while, and this is a good fail case. We've added new options, `title.paddingLeft` and `title.paddingRight`.

Demos with the fix applied
* [Simplified](http://jsfiddle.net/highcharts/kd6z57o4/)
* [Original demo](http://jsfiddle.net/highcharts/gbo5xamx/7/)

**Comment by gfairchild** [comment]
That looks fantastic! Thanks for being so quick to fix that. I look forward to 4.2.5.

**Comment by TorsteinHonsi** [comment]
You're welcome!

**Comment by vinayakw21** [comment]
Facing same issue when 
title: {
      text: 'Norovirus: Washington, D.C., District of Columbia, United States of America (2011)',
     },
    opposite: true,

<img width="960" alt="pro" src="https://github.com/highcharts/highcharts/assets/38237840/e4c02020-04d7-4f5c-aa23-387cf6b8ea87">

**Comment by karolkolodziej** [comment]
@vinayakw21 Could you please create a demo with your code so I can work on your case directly because I was not able to recreate that- [demo](https://jsfiddle.net/BlackLabel/of9u0hs2/)?
