### ISSUE TITLE
VerticalAlign works incorrect in the heatmap

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5254]
#### Expected behaviour
Datalabels should be vertically aligned.

#### Actual behaviour
Labels oscillate about middle point

#### Live demo of the issue
http://jsfiddle.net/L0brzonp/

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! The fix will be part of the next maintenance release.

### Workaround
Until the fixed release, a simple fix is to borrow the `alignDataLabel` function from the column prototype:
```js
	Highcharts.seriesTypes.heatmap.prototype.alignDataLabel = Highcharts.seriesTypes.column.prototype.alignDataLabel;
```

[View it live on jsFiddle](http://jsfiddle.net/highcharts/L0brzonp/1/).
