### ISSUE TITLE
IE11: CSS using attribute selectors with attr of width

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5255]
#### Behaviour

When there is CSS setting using attribute selectors with attr of width the issue is visible. It doesn't matter what CSS setting it is as long as attr is width.
`a[width] {}`

When using Highcharts - initial animation is gone, series suddenly appears after animation time.
Demo: http://jsfiddle.net/1nxzxzqp/1/

When using Highstock - series in navigator and in main plot area are not visible. 
Demo: http://jsfiddle.net/1nxzxzqp/
Only markers are visible - http://jsfiddle.net/1nxzxzqp/2/
#### Affected browser(s)

IE11, Edge
#### Workaround

Disabling animation for series seems to help - http://jsfiddle.net/1nxzxzqp/3/

**Comment by TorsteinHonsi** [comment]
Ouch. Reminds me of IE < 9 layout bugs. Edge is also affected.

**Comment by pawelfus** [comment]
**Possible workaround:**

Animate `scaleX` instead of `width`: http://jsfiddle.net/nd9pzwsL/

Snippet: 


    (function(H) {
      H.wrap(H.Series.prototype, 'animate', function(p, init) {
        var series = this,
          chart = series.chart,
          clipRect,
          animation = series.options.animation,
          sharedClipKey;
        if (init) {
          p.call(this, init);
        } else {
          sharedClipKey = this.sharedClipKey;
          clipRect = chart[sharedClipKey];
          if (clipRect) {
            clipRect.attr({
              width: chart.plotSizeX,
              scaleX: 0.001
            }).animate({
              scaleX: 1
            }, animation);
          }
          if (chart[sharedClipKey + 'm']) {
            chart[sharedClipKey + 'm'].attr({
              width: chart.plotSizeX + 99,
              scaleX: 0.001
            }).animate({
              scaleX: 1
            }, animation);
          }

          // Delete this function to allow it only once
          series.animate = null;
        }
      });
    })(Highcharts);

**Comment by KacperMadej** [comment]
+1
Additional issue caused by the same CSS:

Background size is not getting bigger when it should (after a resize) because of the css (`a[width]{}`). 

Demo: http://jsfiddle.net/r04sdc7u/

Steps:
1. start with a small chart
2. make it bigger
3. background of the chart is not wide enough

![chart_ie11_css](https://cloud.githubusercontent.com/assets/8960408/18869482/d289621e-84ac-11e6-85a2-18b64738a927.png)

Affected browsers:
IE11

I am also experiencing an issue that sees to be related to this problem and makes IE11 ignore changes in clip path after a resize. So far I am unable to recreate the problem in an isolated demo.

**Comment by cheoalvarez** [comment]
Great to see that this issue has already been reported. We reported this same issue in the forum and were directed here 

https://forum.highcharts.com/highstock-usage/bug-in-ie-with-highstock-css-attribute-selector-t39032/

We discovered this with our use of angular-material library along with highstock. Our current workaround has been to .reflow() the charts immediately after they're created. I'm curious if there is an ETA for a fix

cc @leogdsl

**Comment by TorsteinHonsi** [comment]
The workaround with the scale could work, but ideally we would find a fix that targets only the affected browsers, to minimize the risk of adding bugs. I tried removing the attribute and setting the width as a CSS style instead, but nothing changed.

**Comment by cheoalvarez** [comment]
Hi all , wanted to check-in on this, is there any ETA for a fix? We are still using .reflow() as a temporary fix but it's adding ~0.5 sec to chart load time which our clients have been reporting in their regression testing after upgrade. Thank you

**Comment by TorsteinHonsi** [comment]
I wouldn't recommend reflowing all charts after generation - just for the performance reason. It is overkill just to disable animation. Instead, just disable animation on all levels:
```js
  if (Highcharts.isMS) {
    Highcharts.setOptions({
      chart: {
        animation: false
      },
      plotOptions: {
        series: {
          animation: false
        }
      }
    });
  }
```

[View live demo](http://jsfiddle.net/1nxzxzqp/7/).

**Comment by TorsteinHonsi** [comment]
I've been debugging this for two hours now, when the solution can in from the side... It turns out that a commit I did on the working branch for HC6 fixes this by coincidence: https://github.com/highcharts/highcharts/commit/8b596ad3f.

What it does is that in the initial animation of the series, it animates `x` as well as the `width`. And that is enough to make IE happy.
