### ISSUE TITLE
Tooltip height incorrect if content starts with line break

### ISSUE THREAD

**Issue by nipehe** [highcharts/highcharts#5261]
#### Expected behaviour
Formatter either strips line breaks from the start of the string OR displays tooltips with enough height.

#### Actual behaviour
Line breaks at the start of a tooltip formatter cause the displayed text to have a line break at the beginning (as specified) but tooltip bubble height is too low, causing overflow.

#### Live demo of the issue
http://jsfiddle.net/j840waqa/

#### Steps to reproduce the behaviour
1. Add a tooltip formatter with at least one `<br>` tag at the beginning

#### Affected browser(s)
Chrome 49, Firefox 38, IE11

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! 

#### Minimal demo
The bug applies to all labels: http://jsfiddle.net/highcharts/ery8vzfa/
