### ISSUE TITLE
Highstock: Custom series attributes are lost by Highstock chart when series length is big

### ISSUE THREAD

**Issue by Coderdreams** [highcharts/highcharts#5263]
#### Expected behaviour
I have a few markers and extra data on my points, and they work fine when the points are less than around 400.

#### Actual behaviour
When the points hit a count around 500 or more, the markers and extra data are not shown.

#### Live demo of the issue
http://jsfiddle.net/yhLn550v/1/

#### Steps to reproduce the behaviour
The live demo as it is will show no markers in the graph. Lower this variable:
      var pointCount = 500;
to 400 or 300, or less, to see the markers working correctly.

#### Affected browser(s)
Reproduced it in Chrome Version 49.0.2623.112 (64-bit) and Firefox 45.0.2

**Comment by Coderdreams** [comment]
Just a cue, this problem is not reproducible using Highcharts instead of Highstock.

**Comment by TorsteinHonsi** [comment]
Thanks for writing! Individual point options get lost when data grouping kicks in, so in your case you probably want to disable data grouping: http://jsfiddle.net/highcharts/yhLn550v/2/.

**Comment by Coderdreams** [comment]
Thank you! Maybe you guys want to update the documentation to describe this behaviour?:

http://api.highcharts.com/highstock#tooltip.formatter

It took me quite some time to find out what was happening, and this documentation isn't mentioning dataGrouping at all.
Cheers!

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestion! I've updated the docs to mention data grouping.

**Comment by Coderdreams** [comment]
That's awesome, the community will surely appreciate it.

BTW, you have a typo in: avaiable

Thank you
