### ISSUE TITLE
Spline animation issue for multiple series

### ISSUE THREAD

**Issue by jerryjoseph-net** [highcharts/highcharts#5271]
In the [spline updating each second demo](http://www.highcharts.com/demo/dynamic-update), the animation is supposed to work even when there is more than one series.

But when I add a second series the markers get disconnected from the lines resulting in a strange animation. 

https://jsfiddle.net/LLExL/6112/

**Comment by TorsteinHonsi** [comment]
Running two `addPoint` calls with the `redraw` parameter set to false, will cause the chart to redraw twice, thereby stopping the first animation. 

The recommended behaviour is to call addPoint with redraw set to false, then to a chart.redraw after: https://jsfiddle.net/highcharts/LLExL/6115/
