### ISSUE TITLE
Stacked area fill glitches if y-axis threshold is negative and a data point is exactly y=0

### ISSUE THREAD

**Issue by DuncanColvin** [highcharts/highcharts#5280]
#### Expected behaviour

The area fills should stack on top of each other as they normally do.

#### Actual behaviour

In a chart with a negative y-axis threshold: if an area fill has a data point lying exactly on y=0 then the series stacked on top of it will place its corresponding data point all the way to the bottom of the chart.  This results in incorrect stacking of the area fills.

#### Live demo of the issue
http://jsfiddle.net/eu8gh0uu/

#### Steps to reproduce the behaviour

1 - Have two stacked area filled series.
2 - Give the bottom series one data point exactly on zero (the other data points can all be positive or any mixture of positive and negative)
3 - Give both series a negative y-axis threshold (less than the lowest negative number from step 2).

#### Affected browser(s)

Chrome, firefox, IE 11

**Comment by pawelfus** [comment]
Thank you for reporting!

*Internal note:*
Issue comes from [this place](https://github.com/highcharts/highcharts/blob/2b8287999b4310fb51a9b25069dc05a1068b428b/js/parts/Series.js#L750). Value is equal 0, so do `stackThreshold`.

**Comment by TorsteinHonsi** [comment]
#### Simplified demo
http://jsfiddle.net/eu8gh0uu/3/
