### ISSUE TITLE
Shared tooltip updating constantly on mousemove

### ISSUE THREAD

**Issue by slozier** [highcharts/highcharts#5281]
#### Expected behaviour

I would expect the tooltip to only update when the mouse focuses on a new point.
#### Actual behaviour

Except when moving the cursor around the last series defined in the series array, the tooltip is constantly updated.
#### Live demo of the issue

http://jsfiddle.net/52rsoe38/
#### Steps to reproduce the behaviour

Move the cursor around vertically in the top/bottom third of the graph, the tooltip updates constantly. Move the cursor around in the middle third of the graph, the tooltip only updates when switching to a new point.
#### Possible fix

I suspect the issue is due to having `1` instead of `0` in the following code:

```
this.prevKDPoint = kdpoint[1];
```

see https://github.com/highcharts/highcharts/blob/484f8dacafd9cc041b0594fac44229a056544f59/js/parts/Pointer.js#L213

**Comment by slozier** [comment]
Just a followup on my possible fix, if I change `1` with `0` I run into another issue with the tooltip and hover points not being updated properly, this appears to be due to `kdpoint[0]` having been removed from `kdpoints`:
https://github.com/highcharts/highcharts/blob/484f8dacafd9cc041b0594fac44229a056544f59/js/parts/Pointer.js#L195

**Comment by pawelfus** [comment]
Responsible commit: 38d142a

Connected to #5074

**Comment by pawelfus** [comment]
*Internal note:*
Issue comes from [this line](https://github.com/highcharts/highcharts/commit/6a12772f343c368a3f6b5cb3add93be3b04a6538#diff-5d3aad1ab4221eaad4e4ba17c165d2a7L10365) - where we check only `kdpoint[0]`, but in shared tooltip, we should also compare `kdpoint[1]`. Instead of making this `if()` statement a monster,  I decided to add a new flag.

**Comment by slozier** [comment]
This appears to resolve the issue though it would be nice to still get an update when the "hover" changes from one series to another. Should I create a separate issue?

**Comment by pawelfus** [comment]
I am not sure if we should change default behaviour, it used to work that way: http://jsfiddle.net/52rsoe38/2/ 

If you want to distinct series changes in hover state, I suggest to use `plotOptions.series.events.mouverOver` event: http://jsfiddle.net/52rsoe38/3/

**Comment by slozier** [comment]
I guess it's true that a regression fix shouldn't include a change in behaviour.

Perhaps I'm not seeing it but is there an API I can use to force a tooltip update using the `plotOptions.series.events.mouverOver` event? I had been using the broken behaviour to update the tooltip and highlight the value of the series vertically closest to the cursor.

**Comment by pawelfus** [comment]
Could you show an example? I don't think there will be a solution with using only official API methods. Have your considered using non-shared tooltip, and search for the points? Something like this: http://jsfiddle.net/52rsoe38/4/

To answer your question: you can update tooltip using `tooltip.refresh([point, point, point, ... , point]);`.

**Comment by slozier** [comment]
Thanks for the help @pawelfus.

Looks like you're right, I'm using point.dist to get the closest point and it's not part of the official API: http://jsfiddle.net/52rsoe38/5/

With non-shared tooltip I lose the hover on the other series so I don't think that will work... I will have to think some more about how to proceed.

Side note: in the bugfix branch there appears to be a difference in how the hover state of a series is set depending on if the tooltip is shared or not.

**Comment by vytautas-pranskunas-** [comment]
Any progress on this?

**Comment by TorsteinHonsi** [comment]
@pawelfus

**Comment by pawelfus** [comment]
The original issue works fine on the dev-runRointActions branch: http://jsfiddle.net/52rsoe38/7/ - so when we merge it, then we can close this issue.

**Comment by pawelfus** [comment]
Works fine in 5.0.9.
