### ISSUE TITLE
Date xAxis labels no longer work in 4.2.4

### ISSUE THREAD

**Issue by raulchedrese** [highcharts/highcharts#5282]
#### Expected behaviour

In 4.2.3 a chart with a string date (e.g. "2016-05-06") in the 'x' attribute of a 'data' object is allowed and the chart renders properly.
#### Actual behaviour

In 4.2.4 the same chart doesn't render at all and doesn't show an error.
#### Live demo of the issue

http://jsfiddle.net/nhg3bomq/
#### Steps to reproduce the behaviour

Use a string date (e.g. "2016-05-06") in the 'x' attribute of a series' 'data' object
#### Affected browser(s)

Chrome, Safari, Firefox

**Comment by TorsteinHonsi** [comment]
Using strings as `x` values is a misconfiguration according to http://api.highcharts.com/highcharts#series<line>.data.x, which states the `x` should be a number. 

But failing completely is a bit drastic, I'll see what goes wrong.

**Comment by TorsteinHonsi** [comment]
Fails since bd0f08e, fixing another case where `x` was not a number.

**Comment by TorsteinHonsi** [comment]
Looks like we will not have a fix in place for next maintenance under any circumstance, so I advice that you remove these x values. Even prior to v4.2.4, they didn't have any effect.
