### ISSUE TITLE
Have you examples/tutorials in implementing highcharts with React/ES6

### ISSUE THREAD

**Issue by be-next-hotdog** [highcharts/highcharts#5284]
Hi, everyone,
As topic, I'm looking for several examples to perform this implementation.
Thx for help ;)

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

For your specific question, see have a look at http://www.highcharts.com/blog/192-use-highcharts-to-create-charts-in-react.

**Comment by be-next-hotdog** [comment]
I did read already this blog before, but it seems as if that il's been a longtime that you haven't updated your implementation solution. Check it plz !

Thx.

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng

**Comment by oysteinmoseng** [comment]
@jon-a-nygaard

**Comment by be-next-hotdog** [comment]
Why we closed this issue ? 
I still don't get the answer ...    (=  =)!

**Comment by oysteinmoseng** [comment]
@be-next-hotdog Please contact our [technical support](http://www.highcharts.com/support) for your specific case, as this website is reserved for bug tracking.
