### ISSUE TITLE
Postal Codes for some states "null" for India geojson

### ISSUE THREAD

**Issue by sgrg93** [highcharts/highcharts#5285]
The "postal-code" attribute for some states like Gujarat, etc. are null for India geojson provided by HighCharts. Where can I find such geojson having complete information?

**Comment by oysteinmoseng** [comment]
We will be adding this in a future update to our map collection, but for now you could edit our maps directly and add the correct data yourself. GeoJSON is a text format, and could be edited in a text editor, or you can follow our more complex [GIS tutorial](http://www.highcharts.com/docs/maps/custom-geojson-maps).
