### ISSUE TITLE
When axis labels are aligned left, space reserveSpace option is no longer respected.

### ISSUE THREAD

**Issue by eggers** [highcharts/highcharts#5286]
#### Expected behaviour

Labels should take the same space whether `align: "left"` or `align: "center"` is used
#### Actual behaviour

When labels are aligned left (xAxis labels on a bar chart), space is no longer reserved for the labels.
#### Live demo of the issue

http://jsfiddle.net/w315zkaf/
#### Steps to reproduce the behaviour

Modify the sample bar chart, just addinging: `labels: {align: 'left'}` to the xAxis options.

**Comment by eggers** [comment]
My jsfiddle sample wasn't added: http://jsfiddle.net/w315zkaf/

**Comment by Cliffhanger0** [comment]
I'm also experiencing this same issue. HighCharts StackBar has serious bugs with labels due to the x-axis being on the left side.

**Comment by TorsteinHonsi** [comment]
The rationale is that Highcharts assumes you want to put the labels inside, like this: http://jsfiddle.net/highcharts/w315zkaf/2/ . 

That looks good on a value axis, not so good on a category axis with a stacked bar. 

We need to modify the [reserveSpace](http://api.highcharts.com/highcharts/xAxis.labels.reserveSpace) option. Currently it can be set to `false` to ignore the space of the label, but it should also be possible to set it to `true` to force the axis to reserve space, regardless of alignment. Then the default value should be `null`, which will be the current behaviour, a best guess based on alignment.

**Comment by Izothep** [comment]
+1

**Comment by TorsteinHonsi** [comment]
It's fixed now, but allowing the `reserveSpace` option to be set to `true` explicitly. See the fix applied at http://jsfiddle.net/highcharts/w315zkaf/5/.

This will be part of v6.0.4, shipping within a few days.
