### ISSUE TITLE
Unsnapped Crosshair Disappear on Chart Update

### ISSUE THREAD

**Issue by RolandBanguiran** [highcharts/highcharts#5287]
#### Expected behaviour
When I set `crosshair:{snap:false}` and hover mouse on the chart, crosshair line and label should not disappear on `chart.update()`.

#### Actual behaviour
Disappear every time chart updates.

#### Live demo of the issue
http://jsfiddle.net/RolandBanguiran/y93Lv5xx/

#### Steps to reproduce the behaviour
Just hover the mouse on the chart and remain in one area for a while. Notice that when chart is updated, the vertical crosshair disappear.

#### Affected browser(s)
Able to reproduced on Chrome, IE, and Firefox

**Comment by pawelfus** [comment]
*Internal note:*
We can not simply remove `axis.hideCrosshair();` part, because chart can be resized with a visible crosshair. That's why we need to update path anyway.
