### ISSUE TITLE
Switching from line to area results broken gradient fill

### ISSUE THREAD

**Issue by dmitrykvochkin** [highcharts/highcharts#5289]
#### Expected behaviour

Gradient should start on xAxis
#### Actual behaviour

Gradients is drawn from "low" value
#### Live demo of the issue

http://jsfiddle.net/fww1fdhc/
#### Steps to reproduce the behaviour

1 - Create candlestick chart
2 - Switch to "line"
3 - Switch to "area"
#### Affected browser(s)

Tested on chrome.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! Actually this applies to all area charts where a `low` property is set in the point config

#### Simplified demo
http://jsfiddle.net/8LcozwrL/

**Comment by akovac** [comment]
+1

**Comment by TorsteinHonsi** [comment]
I'm not sure how safe it is to remove support for the `point.low` option on area series. Though it is not documented, users may be using it.

A **workaround** would be to remove the `low` property on all area series points:

```js
Highcharts.wrap(Highcharts.seriesTypes.area.prototype, 'generatePoints', function (proceed) {
    proceed.call(this);
	Highcharts.each(this.points, function (point) {
    	point.low = undefined;
    });
});
```
[View live demo](http://jsfiddle.net/highcharts/8LcozwrL/3/).
