### ISSUE TITLE
Panning doesn't work fine with broken axis

### ISSUE THREAD

**Issue by Sipike** [highcharts/highcharts#5290]
#### Expected behaviour

Panning works correctly after zooming to a break (broken axis).
#### Actual behaviour

Panning doesn't work fine with broken axis.
If I reached a break at the right side of the diagram and panning back, diagram is zooming instead of panning.
#### Live demo of the issue

https://jsfiddle.net/Sipike/s6c3nmab/1/
#### Steps to reproduce the behaviour
- Zoom in
- Pan left to right (while you reach one of the break)
- Pan back
  (Only at the right side of the diagram)
#### Affected browser(s)

Chromium Version 49.0.2623.108 Ubuntu 16.04 (64-bit)

**Comment by KacperMadej** [comment]
Simplified demo: http://jsfiddle.net/yc7yz61z/
