### ISSUE TITLE
When specifying 'width' and 'left' on an y axis, values that extrapolate the minimum invade other chart areas

### ISSUE THREAD

**Issue by pghilardi** [highcharts/highcharts#5291]
#### Expected behaviour

When I'm using 'left' and 'width' on a y axis, values that extrapolate the minimum axis value invade the axis labels. This doesn't occurs with the maximum value.

![alt text](http://s32.postimg.org/ejpd5n6dh/expected.png)
#### Actual behaviour

http://jsfiddle.net/jedo014t/2/
#### Live demo of the issue

http://jsfiddle.net/jedo014t/2/
#### Steps to reproduce the behaviour

Use 'width' and 'left' with values that extrapolate the minimum value.
#### Affected browser(s)

It happens on Chrome and Qt Web Kit.

**Comment by pawelfus** [comment]
Hi @pghilardi,

My apologies for a late reply. It works fine in Highstock, so we can reuse the same logic in Highcharts. Workaround: http://jsfiddle.net/jedo014t/3/

    var H = Highcharts;
    H.wrap(H.Series.prototype, 'render', function(proceed) {
      // Only do this on stock charts (#2939), and only if the series type handles clipping
      // in the animate method (#2975).
      if (this.xAxis) {

        // First render, initial clip box
        if (!this.clipBox && this.animate) {
          this.clipBox = H.merge(this.chart.clipBox);
          this.clipBox.width = this.xAxis.len;
          this.clipBox.height = this.yAxis.len;

          // On redrawing, resizing etc, update the clip rectangle
        } else if (this.chart[this.sharedClipKey]) {
          H.stop(this.chart[this.sharedClipKey]); // #2998
          this.chart[this.sharedClipKey].attr({
            width: this.xAxis.len,
            height: this.yAxis.len
          });
        }
      }
      proceed.call(this);
    });

*Internal note:*
Test against #2939.

**Comment by sebastianbochan** [comment]
Extra demo:
   - http://jsfiddle.net/ryavjhwf/
