### ISSUE TITLE
"Markers-Only" Series Displays Line When Hovered

### ISSUE THREAD

**Issue by RolandBanguiran** [highcharts/highcharts#5292]
#### Expected behaviour
Should not show line when hovered.

#### Actual behaviour
Line is showing.

#### Live demo of the issue
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/markers-only/

#### Steps to reproduce the behaviour
Hover into the series.

#### Affected browser(s)
All browsers.

**Comment by TorsteinHonsi** [comment]
The setting responsible for displaying the line is [states.hover.lineWidthPlus](http://api.highcharts.com/highstock#plotOptions.series.states.hover.lineWidthPlus).

To disable the line in hover too, set it to 0: http://jsfiddle.net/6edsbymp/.

However I agree it can be confusing when you try to disable the line.

**Comment by RolandBanguiran** [comment]
Thanks Torstein. No more line when hovered.
