### ISSUE TITLE
Unwated animation of series when they get updated

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5294]
#### Expected behaviour

Points should be shifted without changing their values multiple times.

#### Actual behaviour

Series is getting squeezed after new point is added and back to normal shape.

#### Live demo of the issue
http://jsfiddle.net/sxkrtgL1/

Looks like the problems is caused by dataGrouping, because there is no issue if dataGrouping is disabled - http://jsfiddle.net/sxkrtgL1/1/

**Comment by CrazyFunker** [comment]
Please notice that the navigation bar is experiencing the same problem, regardless of the dataGrouping enabled or not.

**Comment by TorsteinHonsi** [comment]
Normalized demo: http://jsfiddle.net/highcharts/sxkrtgL1/2/

**Comment by KacperMadej** [comment]
+ 1

**Comment by KacperMadej** [comment]
Another demo (however, this might not be the same issue):
http://www.highcharts.com/stock/demo/dynamic-update

Steps:
1. move navigator's selection to middle of x axis to see the line twist in place

**Comment by TorsteinHonsi** [comment]
Thanks Kacper, it's the same issue. The problem is that `shift` is set to 1 when adding a point, but the logic doesn't take data grouping or shifting extremes into account. We need a new functionality that is aware of the actual x values of the graph.

**Comment by TorsteinHonsi** [comment]
#### Workaround

This issue was introduced with Highstock 4.2.5. Before that we didn't even support animation on addPoint in Highstock. To go back to how it was, just set the animation parameter to false: http://jsfiddle.net/highcharts/sxkrtgL1/4/.

**Comment by TorsteinHonsi** [comment]
_Note to self:_
The commit above also introduces support for animating the graph sideways not only when running `addPoint`, but also when zooming. It can be seen in the [basic Highstock sample](http://jsfiddle.net/pvL8sr8a/) by dragging the scrollbar to the middle, then click the right scrollbar button. What is missing now is support for animating in other direction, when clicking the left scrollbar button. It must be implemented in the `initPath` function.
