### ISSUE TITLE
Chart jumps after redraw()

### ISSUE THREAD

**Issue by lolsoftware** [highcharts/highcharts#5299]
#### Expected behaviour

Redrawing the map using API should not cause the map to "jump".
#### Actual behaviour

If you zoom into the chart using scrollbar or double click, and then redraw the chart using API, the chart jumps a bit to the left or to the right. The farther from the center of the chart you zoom, the bigger the jump is.

There seems to be a workaround: if you use drag&drop to move the visible part of the map, and then you zoom and redraw, there will be no jump. However if you zoom out completely, then zoom in, the issue starts happening again.
#### Live demo of the issue

http://jsfiddle.net/dkcg7k6t/1/
#### Steps to reproduce the behaviour
1. Zoom into the chart using scrollbar or double click
2. Hit the "redraw" link below the chart
#### Affected browser(s)

Chrome 49, FF 45, IE 11

**Comment by lolsoftware** [comment]
What fixes the issue is commenting out the following line in highmaps.src.js:

/**
Redraw the axis to reflect changes in the data or axis extremes
 */
redraw: function () {

	if (this.visible) {
		// render the axis
		//this.render(); //<--commenting out this line causes the issue not to occur anymore

		// move plot lines and bands
		each(this.plotLinesAndBands, function (plotLine) {
			plotLine.render();
		});
	}

	// mark associated series as dirty and ready for redraw
	each(this.series, function (series) {
		series.isDirty = true;
	});

}

**Comment by lolsoftware** [comment]
Obviously, commenting out this highmaps.src.js line is just a workaround, and not the actual solution...

**Comment by TorsteinHonsi** [comment]
Seems to be fixed now.
