### ISSUE TITLE
Data disappeared after zoom with multiple yAxis

### ISSUE THREAD

**Issue by orestisioakeimidis** [highcharts/highcharts#5300]
#### Expected behaviour
Expect to see the data when zooming on a specific area.

#### Actual behaviour
Data of the zoomed area is disappeared.

#### Live demo of the issue

[http://jsfiddle.net/nc8easdd/](http://jsfiddle.net/nc8easdd/)

#### Steps to reproduce the behaviour
Zoom on the right side of the chart and you will notice that the data is disappeared. The labels of the first yAxis are disappeared as well at the beginning.

#### Affected browser(s)
Chrome 50, FF 46

**Comment by sebastianbochan** [comment]
The issue is caused by multiple yAxis. When we set single one, all works properly.

**Comment by orestisioakeimidis** [comment]
Unfortunately I need to use the multiple yAxis, because of the stacking. Without multiple axis and stacking enabled, the series are displayed on top of each other. Using multiple axis they are displayed on front of each other, which is the desired result.

Is there a way to use multiple yAxis and linkedTo property together?

[http://jsfiddle.net/yd2bkqp4/](http://jsfiddle.net/yd2bkqp4/)

Thanks!

**Comment by TorsteinHonsi** [comment]
You can create separate stacks through the [series.stack](http://api.highcharts.com/highcharts#series<column>.stack) option: http://jsfiddle.net/highcharts/yd2bkqp4/1/

**Comment by orestisioakeimidis** [comment]
That fixed it! Thank you!

**Comment by TorsteinHonsi** [comment]
You're welcome!
