### ISSUE TITLE
Modifications to an arearange's outline path get overwritten after toggling visibility

### ISSUE THREAD

**Issue by luuuke** [highcharts/highcharts#5303]
#### Expected behaviour

Outline of the series will flush to the edges after toggling visibility of a series off and on: The path keeps the edits to the d-attribute made during the redraw.
#### Actual behaviour

Outline gets drawn normally, changes to its path are not showing.
#### Live demo of the issue

http://jsfiddle.net/z9sahwp9/
Concerns specifically the temperature series. This does not affect the area, just the outline, even though the animation is a bit jerky.
#### Steps to reproduce the behaviour

Toggle visibilty of either temperature or rain, observe changes to outline of temperature series.
#### Affected browser(s)

Firefox 42.0
Safari 9.0.1 (on OS X)

**Comment by TorsteinHonsi** [comment]
First of all, a better approach for your modification would be to extend the `drawGraph` method, so that you don't have to depend on events in the chart configuration itself:

http://jsfiddle.net/highcharts/z9sahwp9/1/

But the same thing happens. It looks like it may be related to clipping.

**Comment by TorsteinHonsi** [comment]
So what you are trying to do is to make the `step: center` option fill the full category, right? It is something we should consider a native implementation of...

**Comment by pawelfus** [comment]
How about wrapping `translate` and simply modifying `plotX` ? Like this:

    Highcharts.wrap(Highcharts.seriesTypes.arearange.prototype, 'translate', function(proceed) {
      var series = this,
        chart = this.chart;

      proceed.call(this);

      this.points[0].plotX = 0;
      this.points[this.points.length - 1].plotX = this.xAxis.width;
    });


Live demo: http://jsfiddle.net/z9sahwp9/2/

**Comment by luuuke** [comment]
@TorsteinHonsi Exactly, that's what I'm trying to do. A native implementation would be great, without extension to the edges it looks fairly weird even though the logic behind not extending it is justified (no data for the outside spaces? -> no graph). Making it an option will satify both options.

The implementation from @pawelfus works great, though, and is waaay cleaner (Thanks a bunch!). I'll adopt it and would most definitely appreciate a native implementation.

**Comment by luuuke** [comment]
@pawelfus I just noticed in your solution that the second and second last section are unproportionally big, the first and last unproportionally small compared to the center sections. I wasn't able to properly resolve this yet, could you have another look at it?

**Comment by pawelfus** [comment]
@luuuke - which sections? Could you show an example? This is how chart is rendered on my machine:
![screen shot 2016-05-20 at 10 59 53](https://cloud.githubusercontent.com/assets/1453926/15422694/0bc214de-1e7a-11e6-8318-e4c77cb433e4.png)

**Comment by luuuke** [comment]
@pawelfus Sorry for being unclear. The image should bring the point across now, notice the unequal widths of each specific day in the red band.
<img width="694" alt="highcharts_transform_unequal" src="https://cloud.githubusercontent.com/assets/4431868/15456311/73b3f83e-206c-11e6-8a1c-84ba0a691f53.png">

**Comment by pawelfus** [comment]
Thank you for the details. My solution was a bad idea - modifying `plotX` changes how path is calculated. I would rather stick to @TorsteinHonsi solution. 

The only issue there I think comes from an animation, when disabled works fine: http://jsfiddle.net/z9sahwp9/3/

**Comment by luuuke** [comment]
I understand, thanks for your correspondence. 
Even though disabling the animation would be an 'okay' solution, I'd have to disable animation on all graphs on the page to keep a consistent feeling, which isn't an option, as they really make the whole experience way more pleasing. 
Once I need it working perfectly fine I'll try to come up with a native solution, unless you found the bug which causes this issue or even made extension to the edge native.
