### ISSUE TITLE
Tooltip not displayed for small columns

### ISSUE THREAD

**Issue by jonathanchrisp** [highcharts/highcharts#5304]
#### Expected behaviour

I would expect labels to appear on hover for all points on the chart if volume e.g. 1 and above.
#### Actual behaviour

If you have a chart which has high volumes and points on the chart which only have a value of one the label doesn't appear on hover.
#### Live demo of the issue / Steps to reproduce the behaviour

I found this use to work for older versions please see below:

2.3.5 - http://jsfiddle.net/jonathanchrisp/6o71cm8y/1/ - works
3.0.0 - http://jsfiddle.net/jonathanchrisp/6zv02c0g/1/ - works
4.2.3 - http://jsfiddle.net/jonathanchrisp/8eeLmf6L/ - had issue
4.2.5 - http://jsfiddle.net/jonathanchrisp/wkehj788/1/ - had issue

However, after testing multiple versions and how you construct the chart........... it turns out it's simply down to the margin style that you can set on the highcharts element. If you set `margin: 0 auto` the labels with low volumes will not appear:

with margin style:  http://jsfiddle.net/jonathanchrisp/wkehj788/3/ - issue
without margin style: http://jsfiddle.net/jonathanchrisp/wkehj788/4/ - works

I'm not entirely sure how you could fix this other than to advise users not to do this but I thought it was worth raising. Please note in my jsfiddles above I have dataLabels set to false. If set to true it will work:

http://jsfiddle.net/jonathanchrisp/wkehj788/5/
- There appears to be another issue here, not all data labels values appear. Sorry!! 😢 
#### Affected browser(s)

Found on Chrome Version 50.0.2661.94

**Comment by TorsteinHonsi** [comment]
The problem is that the bar is so small it rounds off to 0 width. Possible workarounds include:

* Use a shared tooltip: http://jsfiddle.net/highcharts/wkehj788/6/
* Set `minPointLength` to 1: http://jsfiddle.net/highcharts/wkehj788/7/
