### ISSUE TITLE
Axis.getExtremes max doesn't equal dataMax

### ISSUE THREAD

**Issue by hkostia** [highcharts/highcharts#5305]
#### Expected behaviour
http://api.highcharts.com/highcharts#Axis.getExtremes states that if max is not set and maxPadding is 0, then getExtremes max should be equal to dataMax

#### Actual behaviour
max doesn't equal to dataMax

#### Live demo of the issue
https://jsfiddle.net/8hu8hd2m/

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! The docs did not mention that the `endOnTick` option also affects the `max`. This information is added now. [Your fiddle, modified](https://jsfiddle.net/highcharts/8hu8hd2m/1/).
