### ISSUE TITLE
Seeing strange behaviour when updating the series data

### ISSUE THREAD

**Issue by Umaaz** [highcharts/highcharts#5309]
#### Expected behaviour

The data for the series updates correctly.
#### Actual behaviour

A series is dropped, and the colour for a series changes half way through the graph.

If you start the demo there are 4 series displayed on the graph. Once the first update is called a series is dropped and one series changes colour. Usually the blue series starts to become Orange.
#### Live demo of the issue

http://jsfiddle.net/bdonnell/Lm34Ltjn/1/
#### Steps to reproduce the behaviour

Restart the demo.
#### Affected browser(s)

Firefox, Chrome, IE.

**Comment by TorsteinHonsi** [comment]
It has to do with the `index` option. If you remove the indexes, it works: http://jsfiddle.net/highcharts/Lm34Ltjn/2/

**Comment by Umaaz** [comment]
Thanks. Unfortunately I need to use the index feature to control the order of the series. As indicated by the docs http://api.highcharts.com/highstock#series%3Cline%3E.index.

I have been able to work around the problem by assigning an id to the series and using the get method to retrieve the series. Then update the data.

While investigating the problem it seems that the issue is related to the fact that the navigator series is inside the array that is returned when you call chart.series. Maybe an API route that only returns the series for the chart (and not the navigator) would be appropriate here?

**Comment by pawelfus** [comment]
Actually, navigator series is also a series, where we can set data, remove point etc. so I think it should be there. 

> Maybe an API route that only returns the series for the chart (and not the navigator) would be appropriate here?
It's not part of the API, but you can get series connected to the specific xAxis/yAxis: `chart.xAxis[index].series`. Navigator has it's own xAxis and yAxis, so you will get only filtered data.

In general, I would suggest to set `navigator.series.index` when changing order of series by index, for example: http://jsfiddle.net/Lm34Ltjn/4/ - it works fine.
