### ISSUE TITLE
Polygon series should not consider the global "stacking" property

### ISSUE THREAD

**Issue by xyzisinus** [highcharts/highcharts#5310]
#### Expected behaviour

My chart is set for columnrange with "stacking: normal".  But I also have some polygon series'.  The stacking property, no matter what it is, should not affect the polygons.

#### Actual behaviour

With the global stacking property as "normal", the polygons are rendered incorrectly (see jsfiddle example below).

#### Live demo of the issue

https://jsfiddle.net/xyzisinus/dwcthrn7/5/

The workaround is to remove the global stacking setting and put "stacking: normal" into every columnrange series.  Then the polygon will render correctly.  See

https://jsfiddle.net/xyzisinus/dwcthrn7/7/

#### Steps to reproduce the behaviour

Just run the demo.

#### Affected browser(s)

Observed browsers: Firefox and Chrome.

**Comment by TorsteinHonsi** [comment]
> The workaround is to remove the global stacking setting and put "stacking: normal" into every columnrange series.

You don't need to set it on every item, instead use the general `plotOptions.bar` option set (I assume when you say "columnrange" it is just a mistake)  : https://jsfiddle.net/highcharts/dwcthrn7/10/

**Comment by TorsteinHonsi** [comment]
On second thought I'm not sure this is a bug... You have actually set `stacking` to `normal` for all series in the chart, and all the polygon series is is to obey. So you should either set stacking to the bars only (like my previous comment), or set it [explicitly to false](https://jsfiddle.net/highcharts/dwcthrn7/11/) on the polygon series.

**Comment by xyzisinus** [comment]
First of all, I want to thank you VERY MUCH for making such wonderful tools and letting non-profit projects to use for free.  Here I share with you a screencast (http://everest.pdl.cmu.edu/downloads/global_scheduling.mov) which is built using your tools. It is the prototype of a visualization tool intended for Hadoop's resource manager (data center job scheduler/planner).   High-chart comes with fine documentation, many handy examples, very few bugs, and great performance.  

But allow me to differ on this particular bug.  Any interface invariably harbors ambiguity, such as in the case of the stacking property for polygons.  To manage ambiguity, the implementation should deliver the output that surprises the user the least.  Since stacking for polygons is not meaningful, the user does NOT expect the global setting of stacking to affect polygons.  Therefore, the implementation should choose to ignore the stacking property or give a warning.

**Comment by xyzisinus** [comment]
By the way, although setting chart type to "bar" is the right choice for the demo code, I do need "columnrange" for my project, as the screenshot I've shared with you should show.
