### ISSUE TITLE
Stacked bar with 'percent' stacking doesn't render series on the right

### ISSUE THREAD

**Issue by vladimir-kazan** [highcharts/highcharts#5312]
#### Expected behaviour

Series with assigned _minPointLength_ should be rendered on the right side of stacked bar with _stacking = 'percent'_.
#### Actual behaviour

Now series with zero and assigned _minPointLength_ are rendered only on the left side, in the middle, but not on the right side.
#### Live demo of the issue

Demo: https://jsfiddle.net/VladimirK/fqkL7xqs/
#### Steps to reproduce the behaviour

<img width="615" alt="stackedbarrightside" src="https://cloud.githubusercontent.com/assets/3514422/15192295/9dddcb40-17c9-11e6-9d1b-d88dc1f35b95.png">
#### Affected browser(s)

All browsers

**Comment by TorsteinHonsi** [comment]
What happens is probably that the `minPointLength` option makes the column appear from the actual value and up. And since the actual stacked value in this case is 100%, it renders outside the plot area. We can see that if we increase the `max` a bit: https://jsfiddle.net/highcharts/fqkL7xqs/19/
