### ISSUE TITLE
tooltip for polygon series is blocked by columnrange series

### ISSUE THREAD

**Issue by xyzisinus** [highcharts/highcharts#5313]
#### Expected behaviour

My chart is mainly columnrange.  But I also have polygon series'.  I expect polygon tooltip to appear when hovering on the object.
#### Actual behaviour

When there are columnrange series', polygon's tooltip does not show.  But when all columnrange series are removed, polygon's tooltip shows up.
#### Live demo of the issue

https://jsfiddle.net/xyzisinus/st6tLdue/1/

The following is the case after all columnrange series' have been removed.  The tooltip works.

https://jsfiddle.net/xyzisinus/st6tLdue/2/
#### Steps to reproduce the behaviour

Run the demo and hover on the polygon.  The tooltip will not show.
#### Affected browser(s)

Observed in Firefox and Chrome.

**Comment by TorsteinHonsi** [comment]
_Internal note_:

Polygon is closesly related to scatter series. The same happens to scatter series, except we ar able to see the tooltip if we [hover the markers directly](https://jsfiddle.net/highcharts/st6tLdue/3/). Except in the polygon we don't have markers at all.

**Comment by jon-a-nygaard** [comment]
_Internal note: [Simplified demo](http://jsfiddle.net/jon_a_nygaard/11L4vwx2/2/)._

**Comment by xyzisinus** [comment]
This issue has been resolved with the most recent highcharts version.  Hence I'm closing it.
