### ISSUE TITLE
Highstock addPoint animation wrong sometimes

### ISSUE THREAD

**Issue by borisyankov** [highcharts/highcharts#5314]
#### Expected behaviour
When calling addPoint on a series and animation is enabled, it visually moves to the left

#### Actual behaviour
The line 'morphs' into the new values - each point moves vertically to represent the new value

#### Steps to reproduce the behaviour
This happens only sometimes, in more complicated code I have

**Comment by TorsteinHonsi** [comment]
Duplicate of #5294
