### ISSUE TITLE
Axis update toggling ordinal breaks width of columns and ticks

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5316]
#### Expected behaviour

After updating axis with different ordinal setting chart should work as a chart build with that changed option.

#### Actual behaviour

Width of columns is no longer calculated correctly and ticks are tightly packed only in middle of axis.

#### Live demo of the issue
http://jsfiddle.net/70mf3kvb/

#### Steps to reproduce the behaviour
(ordinal is changed in callback)
1. Press '1m' button on rangeSelector

**Comment by marcinmaruszewski** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Simplified demo: http://jsfiddle.net/highcharts/70mf3kvb/1/

**Comment by marcinmaruszewski** [comment]
@TorsteinHonsi , thank You!
