### ISSUE TITLE
Multiple Y-axis ticks without labels and title text

### ISSUE THREAD

**Issue by hkostia** [highcharts/highcharts#5317]
#### Expected behaviour

Either show all ticks by moving tick position based on previous ticks or show only the last tick by rendering all ticks in the same place.
#### Actual behaviour

It shows only the first and last axis ticks. This works OK when there are one or two axises.
#### Live demo of the issue

http://jsfiddle.net/znvmhnck/1/

**Comment by pawelfus** [comment]
Workaround:

Use [`axis.offset`](http://api.highcharts.com/highcharts#yAxis.offset) option to manually position axes: http://jsfiddle.net/znvmhnck/2/
