### ISSUE TITLE
update series data then redraw cause javascript error 

### ISSUE THREAD

**Issue by ftao** [highcharts/highcharts#5318]
#### Expected behaviour

update the series by remove first point , update last point , add a new point , then redraw. 
should draw the chart correctly . 
#### Actual behaviour

throw error 

```
Uncaught TypeError: Cannot read property '0' of undefined"  highcharts.src.js:14451
Series.translate   highcharts.src.js:14451 
extendClass.translate highcharts.src.js:17178  
Series.redraw  highcharts.src.js:15454 
(anonymous function)  highcharts.src.js:12274 
each  highcharts.src.js:1163 
Chart.redraw highcharts.src.js:12271 
```
#### Live demo of the issue

https://jsfiddle.net/tpu0fwpe/2/
#### Steps to reproduce the behaviour

see demo
#### Affected browser(s)

tested on firefox / chrome   on mac

**Comment by TorsteinHonsi** [comment]
The error comes from an empty stackValues, set, but the underlying issue seems to be that we generate two instances for the point on x = 2, while we should only have one.

**Comment by pawelfus** [comment]
**Note:**

If we remove point **and** redraw chart, then it works fine: https://jsfiddle.net/tpu0fwpe/3/ - I think the issue comes with unsynchronised arrays `series.points` and `series.options.data` (another workaround may be to call `series.generatePoints()`: https://jsfiddle.net/tpu0fwpe/4/ ).
