### ISSUE TITLE
After Exporting Chart in PNG, text is changing to small Rectangles

### ISSUE THREAD

**Issue by MJHT05** [highcharts/highcharts#5320]
While Exporting Chart in PNG, Thai language ie., การใช้จ่ายรวม เหรียญสหรัฐ text is changing to small Rectangles.
Whereas it renders correctly in chart.
Please help.

**Comment by TorsteinHonsi** [comment]
#### Live demo
http://jsfiddle.net/highcharts/xhw5n8bt/

It seems the Thai character set is missing from our export server.

**Comment by gvaartjes** [comment]
Thai fonts are set to my knowledge, but maybe not this one specifically. Which character set specifically is used?

**Comment by MJHT05** [comment]
Below are the exact text for Korean and thai language.

ค่าใช่จ่ายทั้งหมด USD 4,290.60 MM ของ USD 4,290.60 MM

총지출 USD 4,290.60 MM 의 USD 4,290.60 MM

**Comment by MJHT05** [comment]
Guys, this issue can be resolved or not.
Please keep me in loop and update your status.

**Comment by TorsteinHonsi** [comment]
Thanks for your patience, we're working on it.

**Comment by gvaartjes** [comment]
@christhai 

Can you double check the fonts loaded for the export server? And test it for the above provided JSFiddle?

**Comment by christhai** [comment]
I do not find Thai character in our Fonts folder actually.
Korean language is working.

**Comment by MJHT05** [comment]
If you Guys will fix this bug, when its gonna available in production(or Live).

**Comment by MJHT05** [comment]
Guys any Update.

**Comment by gvaartjes** [comment]
@christhai
Please add the missing fonts then, and build a new export-server

**Comment by christhai** [comment]
I have added the relevant font. Hopefully it will be available soon.

**Comment by MJHT05** [comment]
Can you give us approximately time, so that i can update to my team too.

**Comment by christhai** [comment]
@MJHT05  It is working now, may you have a check.  Thanks for your patience

**Comment by TorsteinHonsi** [comment]
I confirm it's working.

**Comment by MJHT05** [comment]
Yes its working Fine Now. Thanks for your quick response and support. :D
