### ISSUE TITLE
Support shifting line to the right (backward) in line chart

### ISSUE THREAD

**Issue by ohgo** [highcharts/highcharts#5321]
#### Expected behaviour

Data points and line should move in sync when shifting the chart to the right (i.e. to previous period).
#### Actual behaviour

The data points move first and then the line is redrawn afterwards.
#### Live demo of the issue

http://jsfiddle.net/Ohgo/7nvtu2xx/1/
#### Steps to reproduce the behaviour

Shifting forward is supported well:
chart.series[0].addPoint([x, y], true, true);

Shifting backward is not natively supported and could be implemented with this workaround, but the data points and the line will not move in sync:
chart.series[0].removePoint(currentLastPos, false);
chart.series[0].addPoint([x, y], true, false);

**Comment by jerryjoseph-net** [comment]
Yes I too faced this issue. The shift parameter for AddParameter() works only when adding new points to the right side of the series but not to the left side.

**Comment by TorsteinHonsi** [comment]
Related to #5294, wrong animation when adding points with data grouping. We will look into creating a more generic implementation for animating sideways.
