### ISSUE TITLE
Column series with HTML data labels breaks after some updates

### ISSUE THREAD

**Issue by hkostia** [highcharts/highcharts#5327]
#### Expected behaviour

Adding more data periodically to column series with HTML datalabels and redrawing chart should work.
#### Actual behaviour

After some chart redraws this happens:

```
VM191 highcharts.src.js:663 Uncaught RangeError: Maximum call stack size exceeded
obj.(anonymous function) @ VM191 highcharts.src.js:663
(anonymous function) @ VM191 highcharts.src.js:4955
obj.(anonymous function) @ VM191 highcharts.src.js:663
(anonymous function) @ VM191 highcharts.src.js:4955
obj.(anonymous function) @ VM191 highcharts.src.js:663
(anonymous function) @ VM191 highcharts.src.js:4955
obj.(anonymous function) @ VM191 highcharts.src.js:663
(anonymous function) @ VM191 highcharts.src.js:4955
obj.(anonymous function) @ VM191 highcharts.src.js:663
(anonymous function) @ VM191 highcharts.src.js:4955
```
#### Live demo with steps to reproduce

http://jsfiddle.net/nyqku1d0/4/
#### Affected browser(s)

At least Chrome and Firefox

**Comment by TorsteinHonsi** [comment]
I can confirm this. It seems to always crash after 83 iterations. 

However, the recommended way to add points is to use the [addPoint function](http://api.highcharts.com/highcharts#Series.addPoint). It also happens to not fail: http://jsfiddle.net/nyqku1d0/5/.

**Comment by TorsteinHonsi** [comment]
This always fails after 83 iterations: http://jsfiddle.net/nyqku1d0/6/
