### ISSUE TITLE
Npm install - centOS error

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5328]
#### Actual behaviour
[root@ip-172-31-10-64 highcharts]# npm install highcharts
npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "highcharts"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ENOSELF

npm ERR! Refusing to install highcharts as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!    <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!    /home/centos/ice/node_modules/highcharts/npm-debug.log

Problem appears also with --save argument.

npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "highcharts" "--save"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ENOSELF

npm ERR! Refusing to install highcharts as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!    <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!    /home/centos/ice/node_modules/highcharts/npm-debug.log

Problem doesnt appear under MacOSX.

**Comment by jon-a-nygaard** [comment]
It is because the directory has the same name as the npm package which the user is trying to install. NPM can not handle these cases. So the project directory can not be named "highcharts" if Highcharts is a dependency of the project.
