### ISSUE TITLE
Highstock: dataGrouping with xAxis having ordinal option set to false leaves extra empty space on xAxis

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5329]
#### Expected behaviour

The same chart as a one with appoximated data.
#### Actual behaviour

Empty space or right side - as if ungouped data were placed on xAxis.
#### Live demo with steps to reproduce

Minimal example: http://jsfiddle.net/4owLxnew/1/

Example with expected chart to compare: http://jsfiddle.net/4owLxnew/2/

**Comment by TorsteinHonsi** [comment]
This is a feature by design because it allows us to change the data grouping on the main series without changing the range. Take for example [this demo](http://jsfiddle.net/4owLxnew/3/) where the range stays constant.
