### ISSUE TITLE
Gauge Chart Select State not working

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#5331]
#### Expected behaviour

For Gauge Chart, the color of the needle should change on hover or select state based on options given.
#### Actual behaviour

Hover and select states for Gauge chart is not working. What exactly does hover/select states do for gauge chart? Can we set formatting options (like changing color, width, etc.) for needle or for the dial?
#### Live demo with steps to reproduce

http://jsfiddle.net/2egpa8eb/
#### Affected browser(s)

Chrome

**Comment by jon-a-nygaard** [comment]
@sgrg93 Sorry to say, but states are currently not supported for gauge series.
