### ISSUE TITLE
Renderer's button method is undocumented

### ISSUE THREAD

**Issue by envision** [highcharts/highcharts#5335]
I can't find documentation for rendering a button?

http://api.highcharts.com/highcharts#Renderer
http://api.highcharts.com/highstock#Renderer

This snippet is working though:

	var myFunction = function(chart) {
		alert(chart);
	};

	chart.renderer.button('Reset zoom', null, null, function() { myFunction(chart); }, {
		zIndex: 20
	}).attr({
		align: 'right',
		title: 'Reset zoom level 1:1'
	}).add(chart.zoomGroupButton).align({
		align: 'right',
		x: -10,
		y: 10
	}, false, null);

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, it's added now.

**Comment by SaraniyaaShrii** [comment]
button (String str, Number x, Number y, Function callback, Object normalState, Object hoverState, Object pressedState, Object disabledState, String shape)
Creates a button in the given location.

Parameters
str: String
The text or HTML to draw
x: Number
The x position of the button's left side.
y: Number
The y position of the button's top side.
callback: Function
The function to execute on button click or touch.
normalState: Object
SVG attributes for the normal state.
hoverState: Object
SVG attributes for the hovered state.
pressedState: Object
SVG attributes for the pressed state.
disabledState: Object
SVG attributes for the disabled state.
shape: String
The shape of the button's border/background, if any. Defaults to rect.

Returns: Element
