### ISSUE TITLE
Data module - null value in first line, breaks the chart

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5336]
#### Actual behaviour
Highcharts returns an error #14 only when null value is in the first line.

#### Live demo with steps to reproduce
http://jsfiddle.net/cbv3Ldag/ - working
http://jsfiddle.net/o05xgf3y/ - not working

#### Affected browser(s)
All browsers

**Comment by TorsteinHonsi** [comment]
When you enter "null" in the table, Highcharts will parse it as a string. In order to insert null values, you need to leave an empty space: http://jsfiddle.net/highcharts/o05xgf3y/3/.
