### ISSUE TITLE
Customizing IsIntermediate Sum property logic

### ISSUE THREAD

**Issue by sgsmittal** [highcharts/highcharts#5338]
Can anyone please help me to learn that how to customize logic for IsInermediateSum property?

Actually I have to draw waterfall chart in which multiple properties should start from 0.
So, I have tried multiple ways but found that only using IsIntermediateSum or Sum property this can be achieved.

But these are calculated properties and I don't need that logic for doing sum so I have to by pass that.

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
