### ISSUE TITLE
Overflow ellipsis not working if height is too high

### ISSUE THREAD

**Issue by Pawamoy** [highcharts/highcharts#5339]
#### Expected behaviour
Long categories names should be truncated with '...' added at the end. This should be done by default since one of the latest version. Trying to reproduce this on a jsfiddle it seems that the bug occurs when the chart height is too high. On this particular example at least, the bug occurs when the height is over 641.

#### Actual behaviour
No ellipsis is appended and the full text is displayed, pushing the chart outside the valid width and therefore not displaying it.

#### Live demo with steps to reproduce
https://jsfiddle.net/Pawamoy/zvxpad0c/

#### Affected browser(s)
Firefox, I did not try on others

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! The overlow also depends on the width of the chart. I tried different widths ranging from 400px to 800px, but could not see the problem. Can you set a fixed width that reliably reproduces the problem?

**Comment by Pawamoy** [comment]
Indeed I tried with different fixed width and here are the working width/height combinations:

- height < 642
- 642 <= height <= 662 and width < 277
- 663 <= height <= 683 and width < 177
- 684 <= height <= 704 and width < 142

I tried on different screen resolutions, and nothing changes. I also tried to resize the part where the chart is drawn in JSFiddle but again, nothing changes.

It seems that is also depends on the number of elements in the series data: removing the 10 extra items (25 categories, previously 35 items), now I have these working combinations:

- height < 503 and width < 277
- 503 <= height <= 523 and width < 177
- 524 <= height <= 544 and width < 142

It really gets confusing hahaha :dizzy: :question: :boom: :facepunch: :skull: 

Just so you know, here is a screenshot of what I get: 
![capture du 2016-05-26 11-31-30](https://cloud.githubusercontent.com/assets/3999221/15572580/bba6d1d4-2341-11e6-8766-a46c3b09129e.png)

(And a screenshot of what I should get)
![capture du 2016-05-26 11-32-04](https://cloud.githubusercontent.com/assets/3999221/15572592/ccfe0074-2341-11e6-9037-9f2b2f83acc8.png)

**Comment by Pawamoy** [comment]
I just tried on Google Chrome and I can reproduce the bug but with slightly different values:
- height <= 300 and witdth <= 277: chart displayed but no truncating and no ellipsis for labels (I just see the end of the labels, the rest is cut, going out of the area on the left)

**Comment by TorsteinHonsi** [comment]
* In Google Chrome on Mac, this fiddle fails with a height of 400: https://jsfiddle.net/highcharts/zvxpad0c/3/. The same configuration works with the height set to 600: https://jsfiddle.net/highcharts/zvxpad0c/4/.
* Simplified demo: https://jsfiddle.net/highcharts/zvxpad0c/2/

**Comment by TorsteinHonsi** [comment]
I fixed this for your case, but the issue may be deeper. It seems to be a general problem that ellipsis is not applied if the categories are high enough to allow two or more lines of text. In this case, when the text consists of one large word, we will neither get ellipsis or word wrap.

**Comment by Pawamoy** [comment]
Oh yes it reminds me of an issue I was having with large words, and actually I never solved it: in a HTML div, when text is too long, we can use CSS word-wrap, but then if the text is one large word, it doesn't work, so you have to use word-break, but then, normal text isn't wrapped anymore but broken, cutting words in the middle!! So you have to wrap/cut your text from the backend, but how do you know the width of the div in advance...

Anyway, thank you for your time and for solving this :heart_decoration:
