### ISSUE TITLE
Color Axis Tick Labels are hidden when a big "staggerLines" value is provided

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#5340]
#### Expected behaviour

If Color Axis tick labels "staggerLines" value is given such that it goes out of plot area, map should be re-rendered to accommodate the labels so that they are not hidden.
#### Actual behaviour

Color Axis Tick Labels hide if staggerLines value is given a large number. This problem also occurs in case tick labels are long and orientation is set to vertical.
#### Live demo with steps to reproduce

http://jsfiddle.net/11kv1cgp/
#### Affected browser(s)

Chrome

**Comment by TorsteinHonsi** [comment]
In your demo, you have set `labels.step` to 3, and the color axis shows 1, skips 10 and 100, then shows 1k. This is correct as far as I can see. Am I missing something?

**Comment by sgrg93** [comment]
I guess I was wrong. I meant "staggerLines" and not "step" (I've updated issue, description and jsfiddle). When staggerLines option is given a large number, data labels go out of plot area.

**Comment by TorsteinHonsi** [comment]
Thanks for the update. This is related to #3463. The problem is that the color axis box doesn't take the actual label size into account.

**Comment by KacperMadej** [comment]
+1
