### ISSUE TITLE
Docs - minPadding / maxPadding 

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5341]
I think that we should explain minPadding / maxPadding working description in more details. I mean that is a little bit unclear, because these parameters do not work in Highstock, when we have enabled navigator etc.

**Comment by khoomeister** [comment]
hey @sebastianbochan, minPadding in highstock seems to work fine here (http://jsfiddle.net/khoomeister/pLcf2tmj/4/).  Could you elaborate?

**Comment by pawelfus** [comment]
The issue refers to xAxis, not yAxis. Demo with the issue: http://jsfiddle.net/hjk2qcjk/

**Comment by TorsteinHonsi** [comment]
Can you propose the new wording?​

**Comment by pawelfus** [comment]
It's already in the docs:

- https://api.highcharts.com/highstock/xAxis.endOnTick
> In Highstock, endOnTick is always false when the navigator is enabled, to prevent jumpy scrolling.


- https://api.highcharts.com/highstock/xAxis.startOnTick
> In Highstock, startOnTick is always false when the navigator is enabled, to prevent jumpy scrolling.
