### ISSUE TITLE
Column value changes on zooming or scrolling when data grouping is active

### ISSUE THREAD

**Issue by ernestbofill** [highcharts/highcharts#5344]
#### Expected behaviour

The value of a column is independent to the xAxis zooming
#### Actual behaviour

When zooming or scrolling using the navigator the height of the columns on the extremes changes. For example the value for 'March' goes down from 2293 to 1380.

We don't think the value should be affected by the zooming and regard this as a bug.
#### Live demo with steps to reproduce

http://jsfiddle.net/s3kp9esL/2/
1. Zoom or scroll and notice the height of columns changes.
#### Affected browser(s)

Not browser specific

**Comment by TorsteinHonsi** [comment]
The data grouping looks at the data within the zoomed range, so as we zoom or scroll, the groups on the edge will change.

In order to resolve this, the data grouping logic would also have to look at data outside the defined date range.

**Comment by ernestbofill** [comment]
Yes, I think an option to change this behavior should be added because in most cases - when there is data grouping - it doesn't make sense that a column reflects only a fraction of the data for that group.
