### ISSUE TITLE
How to load highmaps with jspm / system.js when using system (not commonjs)

### ISSUE THREAD

**Issue by born2net** [highcharts/highcharts#5345]
So this snippet works great when I use commonjs in my config.js

```
import * as Ng2Highcharts from 'highcharts/modules/map';
var hc:any = Ng2Highcharts;
hc(Highcharts);
```
but as soon as I switch to system, the maps won't load

```
SystemJS.config({
    transpiler: "plugin-typescript",
    typescriptOptions: {
        "module": "system", // <---------------- CHANGED TO SYSTEM
        "emitDecoratorMetadata": true,
        "tsconfig": true,
        "sourceMap": true
    },
    ...
```

Now I did notice that if I use commomjs, the Ng2Highcharts and hc are functions as you can see below on the alerts:

![fuc](https://cloud.githubusercontent.com/assets/5090936/15555745/f26fe28c-227e-11e6-88f5-f2bdce32a15e.png)

but when I switch to 'system' they become [Objects] (essentially modules) so how do I import so I can pass in the hc(Highcharts); ?

TX

Sean

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
