### ISSUE TITLE
Needs to support a property in waterfall chart to start columns in between of the series from 0 y-axis. 

### ISSUE THREAD

**Issue by sgsmittal** [highcharts/highcharts#5346]
Highchart waterfall chart only support isSum and isIntermediateSum property. 
But this intermediateSum property ignores y axis value.

and low property does not work with highchart waterfall series.

so, if there will be any such property using which columns in between the waterfall series can be started from 0 y axis then that will be great.

Some thing like below screenshot where there are multiple columns in grey starting from 0 y-axis in between but they are not intermediate sum in actual.

![pasted image at 2016_04_08 09_44 am](https://cloud.githubusercontent.com/assets/3319467/15573205/e769e844-2362-11e6-9708-0b3909415885.png)

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

To answer your question, it looks like the `isSum` option resolves what you're trying to do: http://jsfiddle.net/highcharts/qkq9jz84/.
