### ISSUE TITLE
Area chart x-axis overlapping values

### ISSUE THREAD

**Issue by abilash1205** [highcharts/highcharts#5347]
![areachart](https://cloud.githubusercontent.com/assets/19603112/15598768/f6599fb4-23fa-11e6-8fe4-34fe2bc3c97e.jpg)
#### Expected behaviour
In Chart '1750' value of x-axis all categories are zero ,When mouse over it show only last categories value only but i need all value

#### Live demo with steps to reproduce
https://jsfiddle.net/Subbaraju/gyw0ydx2/1/

**Comment by TorsteinHonsi** [comment]
You should probably use a shared tooltip: https://jsfiddle.net/highcharts/gyw0ydx2/2/

**Comment by abilash1205** [comment]
my requirement every series data show  in different popup,but in your example all data showing in one popup only

**Comment by TorsteinHonsi** [comment]
Do you mean you want multiple tooltips (popups) visible at the same time, one pointing at each point? Maybe you can use the experimental [tooltip.split](https://jsfiddle.net/gyw0ydx2/4/) plugin?

**Comment by abilash1205** [comment]
Its looking good,but some time tooltip not displaying when i move mouse
fast right to left more than two time after that tooltip is not displaying
it taking time to display

**Comment by abilash1205** [comment]
When i stop the name: 'Africa', 'Europe', 'America', 'Oceania' in chart but
it till displaying ,i attached image for your references

**Comment by TorsteinHonsi** [comment]
It happened when hiding one of the series. [Try now](https://jsfiddle.net/highcharts/gyw0ydx2/5/).

**Comment by abilash1205** [comment]
Awesome,but some times tooltip not displaying when i move mouse fast right
to left

**Comment by TorsteinHonsi** [comment]
I think I forgot to `cleartTimeout` on hiding the tooltip. [Try now](https://jsfiddle.net/highcharts/gyw0ydx2/6/).

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi can we close this issue?

**Comment by TorsteinHonsi** [comment]
Yes, it's not actually a bug.
