### ISSUE TITLE
Series type "arearange" error when "trackByArea" Option is Disabled

### ISSUE THREAD

**Issue by RolandBanguiran** [highcharts/highcharts#5348]
#### Expected behaviour
Setting "trackByArea" option should not cause error.
`plotOptions:{arearange:{trackByArea: false}}`

#### Actual behaviour
Currently causing console error.

#### Live demo with steps to reproduce
Open Developer Tools' console and run below JSFiddle.
https://jsfiddle.net/RolandBanguiran/n63oxcck/

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Simplified demo: https://jsfiddle.net/highcharts/n63oxcck/1/
