### ISSUE TITLE
3D pie doesn't resize after redraw

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5350]
#### Expected behaviour
Pie should adjust it's size after chart's size change.

#### Actual behaviour
Pie size is not changed.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/3d-pie/

Change size of a chart and a pie will not be re-sized.

Related issue: #5349 

#### More info
Was working in 4.2.3 version of highcharts-3d
http://jsfiddle.net/mgn30ztq/

Fails since: https://github.com/highslide-software/highcharts.com/commit/4e3f57b

**Comment by stpoa** [comment]
It doesn't seem to work again in current version:
http://jsfiddle.net/z0fmw3qw/1/

Works in 4.2.7
http://jsfiddle.net/z0fmw3qw/

**Comment by TorsteinHonsi** [comment]
It's fixed in the master, will be working again from v5.0.1.
