### ISSUE TITLE
 valueSuffix and valueDecimals ignored in the treemap

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5352]
#### Actual behaviour
 valueSuffix and valueDecimals ignored in the treemap

#### Live demo with steps to reproduce
http://jsfiddle.net/secxd4oq/

**Comment by ngehlert** [comment]
any update on when this will be implemented?

**Comment by jon-a-nygaard** [comment]
@ngehlert The fix will be implemented in the next maintenance release which will be after the summer vacation. In the mean time, as a workaround you can edit your `treemap.src.js` with the changes found in  [this commit](https://github.com/highcharts/highcharts/commit/d07bbf41be32898b4f89c80f911984fd53e4e917)
