### ISSUE TITLE
Shared tooltip breaking solidgauge

### ISSUE THREAD

**Issue by yohannbalawender** [highcharts/highcharts#5354]
#### Expected behaviour
Show solidgauge tooltip when hovering its single point.
Coming from a bad usage, a "shared":true option is set for the tooltip.

#### Actual behaviour
No tooltip is shown.
JS error is thrown in .runPointActions().

Even if setting here a "shared" option has no sense, I guess Highcharts shouldn't break.

#### Live demo with steps to reproduce
https://jsfiddle.net/rpy438k6/

#### Affected browser(s)
Chrome - 50.0.2661.102 m

**Comment by yohannbalawender** [comment]
Finally it's not just that easy.

I still want the "shared" option in tooltip in order to display tooltip each time my mouse enters in solidgauge chart.

**Comment by jon-a-nygaard** [comment]
Hi @yohannbalawender 

We are disabling the shared tooltip on solidgauge because as you said it makes no sense. But you can achieve what you want by doing something like this: https://jsfiddle.net/rpy438k6/1/

**Comment by yohannbalawender** [comment]
Hi @jon-a-nygaard 

Yes that was my first though, but finally I've found it convenient.

Anyway your solution seems to fit my needs.

Thanks !
