### ISSUE TITLE
Highcharts: Toggle color of Pie Chart section - When few sections are sliced and few are not sliced

### ISSUE THREAD

**Issue by GaneshBChandgude** [highcharts/highcharts#5360]
Thank you for the suggestion in #5357 

#### Expected behaviour
On clicking/selecting, the sliced piechart sections should change color and remain sliced, while the piechart sections that are not sliced should change color without slicing out.

#### Actual behaviour
In the below JS Fiddle, refer "Jan" and "Mar". In case Jan and Mar is clicked/selected, the selected section gets sliced as true, even though it is set as false.

#### Live demo with steps to reproduce
https://jsfiddle.net/j2t0gdjt/14/

Is there any way to achieve this?

**Comment by jon-a-nygaard** [comment]
Hi @GaneshBChandgude 
A possible way to solve your issue is to [call preventDefault on the point click event](https://jsfiddle.net/jon_a_nygaard/tkez057n/).

Let me know if the example above works for you.

**Comment by jon-a-nygaard** [comment]
Hi @GaneshBChandgude 
A possible solution is to [ovveride the `pointClass.init` for the pie series](https://jsfiddle.net/jon_a_nygaard/j2t0gdjt/16/) to avoid adding toggleSlice to the select and unselect events.

**Comment by jon-a-nygaard** [comment]
Perhaps a better way is to [override the `slice` function for the pie series to do nothing](https://jsfiddle.net/jon_a_nygaard/8Loqekf9/).

Let me know if any of the solutions is suitable.

**Comment by GaneshBChandgude** [comment]
Thank you. Overridding the slice function for pie series helped.

Also no need of unselect() in plotOptions.point.events.
https://jsfiddle.net/amrutaJgtp/8Loqekf9/1/

Thanks for the solution! :)
