### ISSUE TITLE
Hide marker point before  addPoint animation is finished

### ISSUE THREAD

**Issue by yeluoqiuzhi** [highcharts/highcharts#5364]
#### Expected behaviour

I expect hiding the marker point until animation was finished
#### Actual behaviour

marker point show first, then animation begin
#### Live demo with steps to reproduce

here is an example, thank you very much.
[add point example](https://jsfiddle.net/yeluoqiuzhi/w25Lp0ux/1/)

**Comment by TorsteinHonsi** [comment]
_Internal note:_
The new points are not generated in `addPoint`, so we can't go in there in order to delay the display. We could mark the configuration options with something like `added`, then do the delay in `drawPoints`.

**Comment by yeluoqiuzhi** [comment]
where is the drawPoints?I can't find it

**Comment by TorsteinHonsi** [comment]
It's internal, you'll find it in the source code. But this is not part of the API, the information was just meant as an internal note to our developers.

**Comment by yeluoqiuzhi** [comment]
I know it.Thank you very much
