### ISSUE TITLE
Zoom options partially disabled until first interaction with the chart

### ISSUE THREAD

**Issue by rafaeljegundo** [highcharts/highcharts#5365]
#### Expected behaviour

We have an highstock chart where data is added gradually. To cover different use cases, the data-sets are added in different granularities for different periods, but into the same series. We use the zoom selector, and we would expect it to have enabled the different zoom options as data is added into the chart.

#### Actual behaviour

After the first data set arrives, the first two options `1h` & `8h` are enabled, and all the others disabled. The zoom buttons only became full enabled after we explicitly interact with the chart, like using one of the options available.

#### Live demo with steps to reproduce

http://jsfiddle.net/eesd0fro/6/

#### Affected browser(s)

The problem seems to exist in both chrome & firefox. I haven't yet tested it in other browsers.

Let me know if I can help in any way to help sort this out quicker.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! Your demo is quite complicated so I tried to create a minimal demo based on your description: http://jsfiddle.net/highcharts/eesd0fro/7/.

It starts with 2 months of data, waits for 2 seconds, then adds a full year. But the range selector buttons are successfully enabled when the full year is added. Can you isolate the issue based on my demo?

**Comment by jon-a-nygaard** [comment]
Closing this since we can not isolate the issue, and it is pending a reply. Should anyone have further information about the issue, please comment and reopen.
