### ISSUE TITLE
Treemap legend lables overlapping

### ISSUE THREAD

**Issue by behnaaz** [highcharts/highcharts#5369]
#### Expected behaviour
Legend labels overlap
#### Actual behaviour
Drop the overlapping labels
#### Live demo with steps to reproduce
http://jsfiddle.net/behnaz/xcrcfh8n/3/

**Comment by pawelfus** [comment]
You can increase `tickInterval`, for example: http://jsfiddle.net/xcrcfh8n/4/ or `tickPixelInterval`: http://jsfiddle.net/xcrcfh8n/8/
If you have fixed width for the char, you can also change colorAxis' width, using `legend.symbolWidth`: http://jsfiddle.net/xcrcfh8n/5/

Example with fixed width: http://jsfiddle.net/xcrcfh8n/7/ - when changing width to 507px for the second chart, labels are rotated as expected.

**Comment by jon-a-nygaard** [comment]
_Internal note: [simplified demo](http://jsfiddle.net/jon_a_nygaard/oe989s4u/)_

**Comment by behnaaz** [comment]
Thanks for your quick response. I have some concerns regarding the provided solutions:
1) My data is dynamic, that means I need to calculate a proper **tickInterval** or **tickPixelInterval** which can be tricky. I need to divide the distance between my **min** and **max** values to an (arbitrary chosen) number (i.e. 20) to get the **tickInterval**. Still I can not be sure if the labels won't overlap because for different set of input my labels can be of different size.
IMHO, highcharts should be in charge of picking a good **tickInterval**.

**Comment by jon-a-nygaard** [comment]
@behnaaz If you remove `tickInterval` from the option set, then Highcharts will calculate it for you. Like in this example: http://jsfiddle.net/jon_a_nygaard/xcrcfh8n/12/

**Comment by behnaaz** [comment]
Thanks @jon-a-nygaard! The reason to set the tickInterval was to force the colors look similar when legend is turned on or off. If there is a way to get consistent colors with or without legends I don't need to set tickInterval. Is there a solution for it?

**Comment by jon-a-nygaard** [comment]
Closing this issue as I will not consider it a bug.
The issue with different colors when the legend is enabled or disabled is reported in #5371. Therefore continuing further discussion about this case in there.
