### ISSUE TITLE
Additional point information not available in tooltip.headerFormat

### ISSUE THREAD

**Issue by barmyard** [highcharts/highcharts#5370]
#### Expected behaviour

tooltip.headerFormat should have access to all members of a point (according to: http://api.highcharts.com/highcharts#plotOptions.bar.tooltip.headerFormat).
#### Actual behaviour

Accessing members of point in headerFormat returns null, pointFormat works fine though. 
#### Live demo with steps to reproduce

http://jsfiddle.net/ntxevmxb/
As you can see, the {point.year} works in pointFormat, but doesn't in headerFormat.
A current workaround I am using is this:
`headerFormat: '<span style="font-size:10px">{point.key}',
 pointFormat: '({point.year}) </span><table><tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
            footerFormat: '</table>',`
#### Affected browser(s)

All of them

**Comment by TorsteinHonsi** [comment]
The `point` in the headerFormatter is actually a label configuration object, which itself has a property that links to the point.

#### Workaround
You can get the point properties by entering `point.point.year`. [View it live](http://jsfiddle.net/highcharts/ntxevmxb/2/).
