### ISSUE TITLE
Treemap showing different colors when legend is on or off

### ISSUE THREAD

**Issue by behnaaz** [highcharts/highcharts#5371]
#### Expected behaviour
Turning legend -> enabled to **true** or **false** should result in similar color ranges.

#### Actual behaviour
The colors are noticeably different when legend is shown or is hidden.

#### Live demo with steps to reproduce
http://jsfiddle.net/xcrcfh8n/8/

**Comment by jon-a-nygaard** [comment]
_Internal Note: [simplified example](http://jsfiddle.net/uf11x9L8/3/)_

**Comment by jon-a-nygaard** [comment]
This is a duplicate and has been fixed in our bugfix branch. Take a look at #5205 for more information.
Also this example here shows that it works after that commit: http://jsfiddle.net/uf11x9L8/6/
