### ISSUE TITLE
Color Axis stops are not accurate with startOn- & endOnTick

### ISSUE THREAD

**Issue by behnaaz** [highcharts/highcharts#5372]
#### Expected behaviour

The color for the value 0 to be white.
#### Actual behaviour

The color for the value 0 is pinkish. It also differs based on different set of data values.
#### Live demo with steps to reproduce

http://jsfiddle.net/xcrcfh8n/4/

**Comment by jon-a-nygaard** [comment]
Hi @behnaaz 
The steps are affected by `startOnTick` and `endOnTick`, set them to false and I believe it works as you would expect: http://jsfiddle.net/jon_a_nygaard/xcrcfh8n/13/

**Comment by behnaaz** [comment]
Thanks for response jon-a-nygaard.
Setting startOnTick and endOnTick to false fixes this issue, but then the labels on the ends won't show. In some cases like http://jsfiddle.net/behnaz/xcrcfh8n/14/ in the red part there is no labels anymore.

**Comment by TorsteinHonsi** [comment]
In addition to `startOnTick` and `endOnTick`, note that the stop values relate to the actual color axis extremes. A handy enhancement here would be to be able to set the stop as an _axis_ value.

**Comment by behnaaz** [comment]
@TorsteinHonsi would you mind showing an example?

**Comment by TorsteinHonsi** [comment]
> A handy enhancement here would be to be able to set the stop as an axis value.

Currently we don't have that feature, but what I meant was that it would be handy if we could set a color to a specific _value_, instead of a relative fraction along the gradient. For example, if [this fiddle](http://jsfiddle.net/behnaz/xcrcfh8n/14/), it would be easier if we could just say that the 0 value should be white. Something like this:

```js
      "stops": [
        [0, "#FF0000"],
        {
           value: 0,
           color: "#ffffff"
        ],
        [1, "#00FF00"]
      ]
```

**Comment by jon-a-nygaard** [comment]
@behnaaz Since you already know the axis min and max, then we can do some calculations to avoid using `startOnTick` and `endOnTick` and still get the labels on the end. I believe this solution could be what you are looking for: http://jsfiddle.net/jon_a_nygaard/3pg4qy20/2/

**Comment by jon-a-nygaard** [comment]
_Internal Note: had it not been for the min and max is not yet set when `initStops` is called, then it would be pretty easy to convert the stops of object format to the array format used already. However `setScale` is not yet called which means either the initStop or the convertion will have to be done later._

**Comment by jon-a-nygaard** [comment]
_Internal Note: it is also not possible to initialize stops after getSeriesExtremes because Legend.getAllItems also uses stops and it is called before we know the axis extremes._
