### ISSUE TITLE
Shared tooltip with columnrange series?

### ISSUE THREAD

**Issue by envision** [highcharts/highcharts#5373]
How can we have columnrange series values added to shared tooltip with custom formatter function?

	tooltip: {
		shared: true,
		formatter: function () {
			var s = '<b>' + Highcharts.dateFormat(dateFormatString, this.x) + '</b>',
				metric = 'BPM';
			$.each(this.points, function () {
				s += '<br/><span style="color:'+ this.series.color +';font-size:22px;">\u25CF</span> ' + this.series.name + ' <b>' + Highcharts.numberFormat(this.y, 0) + '</b> ' + metric;
			});
			return s;
		}
	},

**Comment by jon-a-nygaard** [comment]
Hi @envision 

Your tooltip works as I would have expected: http://jsfiddle.net/v2khq0c9/

But it is difficult to really understand what you are trying to achieve. Could you provide us with a live demo using [JSFiddle](http://jsfiddle.net) and explain a bit more about your goal?

**Comment by TorsteinHonsi** [comment]
@envision I assume you're looking for `point.low` and `point.high`? http://jsfiddle.net/highcharts/v2khq0c9/1/

Also for general tech support, please see www.highcharts.com/support.
