### ISSUE TITLE
Chart not resizing correctly when container's "margin-left" increases

### ISSUE THREAD

**Issue by radsolution** [highcharts/highcharts#5375]
If the .css("margin-left") is reduced from 300px to 0px, the Chart draws correctly at the larger size.
If it is then increased back to 300px, the Chart should re-draw as before.

What actually happens is that the Chart area remains extended,
and part of its content gets drawn outside it's container.

The affected element appears to be:
`<div class="highcharts-container" id="highcharts-0"...</div>`

For Bar charts, the result is that the bars extend outside the container.
For Pie Charts, the result is that the Legend gets drawn outside the container.

Relevant CSS, HTML and JQuery code:

```
div.panel-main {
    padding: 10px;
    margin-left: 300px;
}

<div class="panel-main">
.... // more nested <div> elements
     <div id="chart" class="chart"> // Chart drawn here

$(".panel-main").css("margin-left", "0px"); // extend size to the left - works OK

$(".panel-main").css("margin-left", "300px"); // shrink back to original size - doesn't reduce width.

```
Tested in Google Chrome.

**Comment by pawelfus** [comment]
Hi, 

Thank you for reporting, however I think this is not a bug. Note, that chart listens only `window.resize` event. When changing dimensions of the container manually, you should also call `chart.reflow()`. See [API](http://api.highcharts.com/highcharts#Chart.reflow).

**Comment by radsolution** [comment]
Actually, whilst re-factoring the code,
I discovered that the issue only occurred when the resizing to 300px occurred in the JQuery
`.on("click", "td", function () { }`
event-handler which had been registered after the TD elements were created,
in the JQuery $.ajax success: handler function.

Moving the resizing into a JQuery element click event handler (which is simply defined in a <script> block) for a different element type (<SPAN>) resolves the issue.

Sample code is available, if you wish to examine or test it...

**Comment by radsolution** [comment]
Moving the resizing into a JQuery element click event handler (which is simply defined in a <script> block) for a different element type (<SPAN>) resolves the issue.

Sample code is available, if you wish to examine or test it...
