### ISSUE TITLE
xAxis.Title.Style.fontSize dont get string value

### ISSUE THREAD

**Issue by chalexIAC** [highcharts/highcharts#5376]
for xAxis .Title.Style.fontSize I can set  string value, e.g. '150%' or 'x-large'. It works fine for style of yAxis,  Legend,  toolTip. But doesn't work for xAxis.

i got at log this: highcharts.js:60 Error: <text> attribute y: Expected length, "NaN".O._defaultSetter @ highcharts.js:60

example:
http://jsfiddle.net/fzxqa9ay/1/

**Comment by jon-a-nygaard** [comment]
_Internal Note: the issue occurs in [`Axis.getTitlePosition` on L2004](https://github.com/highcharts/highcharts/blob/master/js/parts/Axis.js#L2004)_
