### ISSUE TITLE
Spline appears behind 3d column in combo chart

### ISSUE THREAD

**Issue by sntran** [highcharts/highcharts#5377]
#### Expected behaviour

A combo chart with a 3d column series and a spline series (in that order) should render the spline closer to the screen.
#### Actual behaviour

The spline is rendered behind the columns.
#### Live demo with steps to reproduce

http://jsfiddle.net/2fgjqqdp/
#### Affected browser(s)

Chrome 50.0.2661.94 (64-bit) on Mac OS X

**Comment by jon-a-nygaard** [comment]
Unfortunately the spline series is not 3d compatible and thus it will not work properly together with the 3d column. The [scatter series with a lineWidth](http://jsfiddle.net/jon_a_nygaard/2fgjqqdp/1/) can mimic a line series, but it seems the columns does not respond to z-values, so it does not get you any further.

Apologies for the late reply.
