### ISSUE TITLE
Issue with JSON date display on axis since new version

### ISSUE THREAD

**Issue by seb49** [highcharts/highcharts#5378]
Hello,

I have an issue with xAxis label with date since last version. 

Here you can see my sample of code which work with 4.2.2 version : http://jsfiddle.net/60e1tjk4/
with same code but with last version of HighChart (http://jsfiddle.net/8fLhy5ag/) label disappear

Data come from an ASP.NET application, dates are in JSON format, so I deserialize them with 
`eval('new' + dateStr.replace(/\//g, ' '));`

Regards

**Comment by oysteinmoseng** [comment]
Thanks for reporting. This seems to be a duplicate of #5302 which is fixed in master. Running your example against master seems to work: http://jsfiddle.net/8fLhy5ag/3/.
