### ISSUE TITLE
Zooming on column chart with pointPlacement: 'between' adds unwanted range without ticks

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5379]
#### Expected behaviour

Zooming to set range.
#### Actual behaviour

Zooming to bigger range and no ticks on extra range.
#### Live demo with steps to reproduce

http://jsfiddle.net/m9usea0d/1/
setExtremes will run automatically, but same behavior when zooming manually.

**Comment by TorsteinHonsi** [comment]
Normally pointPlacement: 'between' would be used with a tickInterval that is the same as the point interval. For example with daily trade volumes, we would expect ticks to be one each day. The problem arises when the tick interval is more granular than the point interval.
