### ISSUE TITLE
Scrollbar buttons are repositioned with a delay

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#5381]
#### Expected behaviour

When updating size of the navigator's xAxis, buttons should repositioned after change.
#### Actual behaviour

Observe left scrollbar button.

![scroller](https://cloud.githubusercontent.com/assets/1453926/15818268/bc7cbb3e-2bdc-11e6-9afe-9ed6e715bd7f.gif)
#### Live demo with steps to reproduce

 In this case, we can see error when labels change it's width:

http://jsfiddle.net/jotgsr95/

**Comment by jon-a-nygaard** [comment]
_Internal Note: another way to reproduce the error is to drag the navigator to one end and beyond, then you will see a heavy flickering._
