### ISSUE TITLE
searchPoint returns the wrong point for a left or right step line serie

### ISSUE THREAD

**Issue by fgalgau** [highcharts/highcharts#5382]
#### Expected behaviour
- When applied to a left step line serie it should always return a serie's point at the left side of the mouse position and never a point found at the right side relative to mouse position
- When applied to a right step line serie it should always return a serie's point at the right side of the mouse position and never a point found at the left side relative to mouse position
#### Live demo with steps to reproduce

http://jsfiddle.net/apnca9d0/
#### Affected browser(s)
- all

**Comment by pawelfus** [comment]
Not a perfect workaround, but it will work with evenly distributed data: 

    (function(H) {
      H.wrap(H.Series.prototype, 'searchKDTree', function(proceed, point, compareX) {
        var sign = this.options.step === 'left' ? -1 : this.options.step === 'right' ? 1 : 0;

        point.clientX += sign * this.closestPointRangePx / 2;

        return proceed.call(this, point, compareX);
      });
    })(Highcharts);

Demo: http://jsfiddle.net/3cv57n90/

**Comment by Izothep** [comment]
+1

**Comment by KacperMadej** [comment]
A bigger workaround and it will work for poorly distributed data: https://jsfiddle.net/truoq7bh/10/

*Relevant code parts:*
*line 45*: `!(series.directTouch || (series.options.step && series.options.step.length < 6))`
(to show tooltip for points outside of visible range - e.g. when zooming in middle of a line. 'center' has 6 letters and 'left' or 'right' - less)
*line 64-66*: check for step 'left' or 'right'
*line 73-75*: increase distance greatly, so points or wrong side will be less likely to be found
