### ISSUE TITLE
Wrong barchart highlighting when using shared tooltips and pointPlacement

### ISSUE THREAD

**Issue by lorgan3** [highcharts/highcharts#5383]
#### Expected behaviour
Hovering over a bar should show the tooltip for that bar and only highlight that one.

#### Actual behaviour
When hovering over the lower part of the bar, the tooltip is displayed for the wrong bar and 2 bars are highlighed.
http://i.imgur.com/2up2BRY.png

#### Live demo with steps to reproduce
Hover over the lower half of a bar.

http://jsfiddle.net/LLExL/6171/

#### Affected browser(s)
Tested in Chrome and Firefox (on linux)

**Comment by jon-a-nygaard** [comment]
_Internal Note: [simplified demo](http://jsfiddle.net/jon_a_nygaard/LLExL/6173/)_

**Comment by colgreen** [comment]
FYI I've submitted a fix pull request, here:

https://github.com/highcharts/highcharts/pull/5601
