### ISSUE TITLE
Export issue

### ISSUE THREAD

**Issue by Josephdias92** [highcharts/highcharts#5384]
#### Expected behaviour
i rendered some elements on the chart using chart.renderer.label and added some font icon to it.
but i dont want to export this elements. 
when i export it, it shows boxes 
#### Actual behaviour
screen shot before export 
![screenshot from 2016-06-07 11-01-31](https://cloud.githubusercontent.com/assets/5546877/15847243/e846d068-2ca1-11e6-85dd-77064d61658c.png)

image after export 
![chart 9](https://cloud.githubusercontent.com/assets/5546877/15847203/a5838e92-2ca1-11e6-9818-6eeea147b1eb.png)

**Comment by pawelfus** [comment]
Could you show some code? In callback (or load event), you can use: `if (!chart.options.chart.forExport) { /* render items */ }` 

For questions, please use our forum or contact us directly by email, [more info](http://www.highcharts.com/support).

**Comment by jon-a-nygaard** [comment]
@pawelfus Forgot to assign myselft to the case. I am working on a drop in workaround for this case using `getChartHTML`.

**Comment by pawelfus** [comment]
@jon-a-nygaard How will you recognise which elements added by `renderer` should be in exporting and which should not be? It's quite common to exporting only part of the rendered elements from a chart.

**Comment by jon-a-nygaard** [comment]
@pawelfus @Josephdias92 By adding a class or an id to the element which we can look for, then we can [ovveride getChartHtml to filter them out](http://jsfiddle.net/jon_a_nygaard/a90wtjs0/).

**Comment by jon-a-nygaard** [comment]
Slight syntactical improvement using Highcharts.each http://jsfiddle.net/jon_a_nygaard/a90wtjs0/3/

**Comment by Josephdias92** [comment]
@jon-a-nygaard thanks :) i just tried this but it dint work.

this is how im trying to add the element.
              tagIcon_css['font-size'] = '24px';
              tagIcon_css['font-family'] = 'icomoon';
              chart.tagIcon = chart.renderer.label(
                  '<span title="Tag Data" class="icon-tag2"></span>',
                  chart.plotWidth + 20, 10
                )
                .css(tagIcon_css)
                .attr({
                  zIndex: 3,
                  title: 'Tag Data',
                  class: 'hidden-export'
                })
                .on('click', function(e) {
                }).add();

**Comment by jon-a-nygaard** [comment]
@Josephdias92 Could you provide us with a live demo, it would be really helpful for debugging. [JSFiddle](http://jsfiddle.net)  is great for this purpose.
