### ISSUE TITLE
OHLC live chart issue

### ISSUE THREAD

**Issue by 4p00rv** [highcharts/highcharts#5385]
#### Expected behaviour
If the latest OHLC bar is not in the view, adding a new OHLC data for OHLC type chart should create a bar which looks like the following pic
![Imgur](http://i.imgur.com/9Vl3kqy.png?1)
#### Actual behaviour
If the bar is not in the view and user is looking at historical data, the OHLC bar creates an extra `close` (-) for it. The output looks something like this (look at the last bar):
![Imgur](http://i.imgur.com/Q2wk4N7.png?1)
#### Live demo with steps to reproduce

Link to live demo: https://jsfiddle.net/gh/get/jquery/1.9.1/4p00rv/highcharts-ohlc-bug/tree/master/src

Steps to reproduce:
- when the chart loads, using the navigator move to some data in history. (The last bar shouldn't be visible).
- Wait for 15-30s until a new bar is added.
- Move to the latest bar. You will notice that the bar is not as expected.

#### Affected browser(s)
All

**Comment by oysteinmoseng** [comment]
The main issue seems to be that you are trying to update points that are not visible using `series.data`, which as documented [here](http://api.highcharts.com/highstock#Series.data) only contains data for the visible points. This causes Highstock to throw error 15. For details on how to update invisible points without errors, take a look at [this question](http://stackoverflow.com/questions/33977806/how-to-update-data-point-in-highcharts-which-is-not-in-the-visible-range).

**Comment by 4p00rv** [comment]
@oysteinmoseng I tried using `series.options.data` to try and update the latest bar, but it doesn't work for OHLC type data.
Here's a fiddle for the test:
https://jsfiddle.net/gh/get/jquery/1.9.1/4p00rv/highcharts-ohlc-bug/tree/master/src

**Comment by oysteinmoseng** [comment]
@4p00rv: It [should work](http://jsfiddle.net/rw37qdck/) for OHLC charts as well, however seemingly only if the point being updated has not been drawn yet. If this is a problem you could update using `series.setData`. It will be less efficient, but has optimizations that makes it less heavy than it sounds for this type of operations. There might be a workaround by hacking around with the internal states @TorsteinHonsi?

**Comment by 4p00rv** [comment]
@oysteinmoseng actually it is a real time update so I can't predict the close time. I have updated [my fiddle](https://jsfiddle.net/gh/get/jquery/1.9.1/4p00rv/highcharts-ohlc-bug/tree/master/src) to use `series.setData`. It seems like for the first bar it goes haywire, but works fine for the following ticks. Although it would be better if it can work just like a line chart.

**Comment by 4p00rv** [comment]
@oysteinmoseng @TorsteinHonsi Can any one of you please suggest a workaround? I still think that it is bug, can you please update this issue if you think so too?
