### ISSUE TITLE
Markers hide automatically in areaspline chart

### ISSUE THREAD

**Issue by sushantbajra** [highcharts/highcharts#5387]
I did a lot of digging but still I cant tell what cause this problem. The marker in the chart disappears automatically and shows up in hover. 

```
plotOptions: {
            areaspline: {
              fillOpacity: 1
            },
            series: {
              tooltip: {
               dateTimeLabelFormats: {
                second:"%A, %b %e, %H:%M:%S"
              }
            },
            marker: {
              fillColor: '#3D84B1',
              lineWidth: 2,
              lineColor: 'white',
              radius: 6

            }
          }
        },

```

The above code is made short for brevity.

This is  what the graph looks like when the markers automatically gets hidden.

![withoutpoints](https://cloud.githubusercontent.com/assets/16317096/15852997/fc1aa076-2cc2-11e6-9986-1d2e578654ca.png)

This is how it looks like with the markers.

![withpoints](https://cloud.githubusercontent.com/assets/16317096/15853012/0fbacfb6-2cc3-11e6-85e0-4551bd6d865e.png)

**Comment by pawelfus** [comment]
Hi,

This is caused by option `marker.enabled = null`, from [API](http://api.highcharts.com/highcharts#plotOptions.area.marker.enabled): 

> If null, the markers are hidden when the data is dense, and shown for more widespread data points. Defaults to null.

**Comment by sushantbajra** [comment]
@pawelfus  the graph only receives 10 points maximum.

**Comment by jon-a-nygaard** [comment]
@sushantbajra For simplicity could you provide us with a live demo of your issue? [JSFiddle](http://jsfiddle.net) works well for this purpose.

**Comment by subashkc** [comment]
@jon-a-nygaard Unfortunately the problem only arises randomly, so it is hard to give a fiddle for it

**Comment by pawelfus** [comment]
@sushantbajra 10 points can be enough: it depends on data granularity and distribution. For example:

    data: [ [0,1], [0.1, 2], [2000, 3] ] 

Will also hide markers. Compare examples: http://jsfiddle.net/sz0esszz/16/

When I see your first screenshot, I assume that two last points are very close, or even the same `x` is set - that may be the culprit.

**Comment by subashkc** [comment]
@pawelfus sometimes the points appear normally in my local system but they go missing in the production server, any ideas what might cause this ?

**Comment by pawelfus** [comment]
@subashkc As I said above - marker points visibility depends on distribution of the points. Check your data displayed on the chart. Issue may come from duplicated points.

Anyway, as I said in the very beginning, you can force markers to be displayed: `plotOptions.series.marker.enabled = true`. 

Extra note: 
In the first message, there is error with settings: `plotOptions.marker` doesn't exist, it should be `plotOptions.series.marker` or `plotOptions.areaspline.marker`.

**Comment by sushantbajra** [comment]
@pawelfus you were right. The points were hidden because we did a little miscalculation while converting date and that caused some points to clutter.
