### ISSUE TITLE
Forced dataGrouping is crashing browser even with very few datapoints

### ISSUE THREAD

**Issue by sp4m** [highcharts/highcharts#5388]
We have a setup where we allow the user to select a specific dataGrouping. This is done by using `dataGrouping.forced` and dynamically limiting `dataGrouping.units` to the selected unit. This is working nicely with the larger units such as days and months, however, smaller units like second and millisecond pose huge performance issues. Down below under reproduction steps I've linked a JSFiddle with only two datapoints.

I haven't yet looked into the code but my best guess is that some processing logic is taking place for each possible point (500,000 in this case - the number of seconds between the two points) even though the vast majority of those points actually do not end up being drawn in the chart. Is this assumption correct? Could this be considered a bug or is it simply a performance implication of the way dataGrouping is working in Highstock?

It's working fine with the boost.js module (which is awesome by they way but doesn't currently seem stable enough for production).

#### Expected behaviour
No browser crash, I guess.

#### Actual behaviour
Very slow render (depending on the distance between the datapoints) and in most cases the browser becomes unresponsive/crashes. 

#### Live demo with steps to reproduce
Change unit to `second` instead of `minute` (I'm purposely not including a direct link to a setup which crashes the browser): http://jsfiddle.net/hfatxg26/

#### Affected browser(s)
Seemingly all.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! We were doing an `Array.shift` when we didn't have to, which is expensive. See the [demo with the fix](http://jsfiddle.net/highcharts/hfatxg26/1/).
