### ISSUE TITLE
Highstock navigator series won't be updated after update series or addPoint  in some cases

### ISSUE THREAD

**Issue by Vivihung** [highcharts/highcharts#5390]
#### Expected behaviour
Series in navigator will be updated after I update existed series or add more data points to the existed series. And user can use navigator to navigate to any time range based on the existed series.

#### Actual behaviour
Series in navigator is not updated after update series or add more data points. (But chart itself is rendered correctly)
When user interact with navigator, there's no way to navigate back to 6/3-6/4 x time range in my live demo, for example.

#### Note
This bug cannot be repro in simple Highstock chart.
Please refer to my live demo link, it happened in that specific configuration.

#### Live demo with steps to reproduce
http://jsfiddle.net/Vivien/68L5zxqa/

#### Affected browser(s)
Chrome, IE 11, Edge
(Only listed browser that I have tested, but I suspect it affected ALL browsers)

**Comment by TorsteinHonsi** [comment]
@pawelfus Is the support team able to reproduce and isolate the bug in jsFiddle?

**Comment by pawelfus** [comment]
@TorsteinHonsi Sure, this is issue with binding series to the navigator. Compare results:

- series initialized: http://jsfiddle.net/68L5zxqa/5/ 
![screen shot 2016-06-08 at 11 54 22](https://cloud.githubusercontent.com/assets/1453926/15890508/344e110a-2d70-11e6-94e5-6aa59eb38cd3.png)

- series added by `addSeries`: http://jsfiddle.net/68L5zxqa/7/
![screen shot 2016-06-08 at 11 54 03](https://cloud.githubusercontent.com/assets/1453926/15890506/307d4582-2d70-11e6-8477-ea6a2c1c5f29.png)

**Comment by pawelfus** [comment]
As for issue itself, `updatedData` event is not added, so workaround can be: http://jsfiddle.net/68L5zxqa/8/


    setTimeout(function() {
      var chunk1 = getChunk();

      console.log('timeout1');
      chunk1.forEach(function(series) {
        chart.addSeries(series, false);
      });

      Highcharts.addEvent(chart.series[0], 'updatedData', chart.scroller.updatedDataHandler);

      Highcharts.addEvent(chart.series[0].xAxis, 'foundExtremes', function() {
        if (chart.series[0].xAxis) {
          chart.scroller.modifyBaseAxisExtremes();
        }
      });

      chart.redraw();

      chart.xAxis[0].setExtremes();
      timeout2();
    }, 1000);

**Comment by Vivihung** [comment]
Thanks for the workaround. I'll try it.
It looks like can be repro, should we remove "Cant reproduce" labels?

**Comment by pawelfus** [comment]
*Internal note:*
@TorsteinHonsi && @oysteinmoseng : I decided to refactor code a bit: now data-events are added in two methods, so we don't have to jump around the code to see what really happens there. I think this also could be useful when implementing multiple series in a navigator - one method to add and one to remove events for all series. Of course, I may be wrong.

**Comment by pawelfus** [comment]
*Internal note:*
I realized that scope was different when I changed methods. Two commits to fix the issue above, sorry for the inconvenience.
