### ISSUE TITLE
Navigator maskInside don't show cursor style

### ISSUE THREAD

**Issue by maximenicot74** [highcharts/highcharts#5392]
Hi there,

I've just noticed that when switching the maskInside property of navigator's options to "false", the cursor style is not displayed, neither on the filled area nor on the not filled one.

https://jsfiddle.net/sr0jkyn8/

What I've seen by inspecting the rendering div is that with this setting, there is no `<rect>` for the zoomed area (indeed, the mask is outside) and so I supposed that's why no style can be applied for the cursor in this area.

Is this a voluntary feature ?

It would be great if a cursor style were applied for the area between the handles, and even more if we could customize the inside and outside area.

Regards.

**Comment by maximenicot74** [comment]
Hi,
Any feedback about this issue ?

**Comment by pawelfus** [comment]
Works fine since v5.0.7, demo: https://jsfiddle.net/sr0jkyn8/3/
