### ISSUE TITLE
Labels rotation doesn't work with exporting and useHTML

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5393]
Hi,

It looks like chart labels are not rotated with exported charts. The charts are exported correctly only to svg file.

Here you can see the normal chart:
![chart](https://cloud.githubusercontent.com/assets/15050812/15934075/70d16710-2e62-11e6-84e0-91436f55495f.PNG)

And here you can find exported version of this chart:
![chart 12](https://cloud.githubusercontent.com/assets/15050812/15933969/1ee6dc5a-2e62-11e6-8860-334fbffebd12.png)
chart:

Here you can see live example showing this issue:
http://jsfiddle.net/rfhx5ca9/4/

To reproduce the issue export chart as PNG.

**Comment by pawelfus** [comment]
*Internal note:* 
Issue is visible only when setting `useHTML: true`, working demo: http://jsfiddle.net/rfhx5ca9/5/

**Comment by jon-a-nygaard** [comment]
_Internal Notice: The result from getSVGForExport renders correctly when copy pasted into a svg file. Which explains why svg works correctly. It seems that there could be a bug in the Highcharts version that is running on the export server._

**Comment by jon-a-nygaard** [comment]
This issue happens because [PhantomJS does not support CSS transforms](https://github.com/ariya/phantomjs/issues/12779). Tested with PhantomJS 2.1.1.

__Test case:__
Copy paste this svg content into a new file, lets say `test.svg`.
```
<svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" xmlns="http://www.w3.org/2000/svg" width="600" height="400">
    <text x="100" text-anchor="middle" transform="translate(0,0) rotate(270 28.09375 184)" y="200">SVG Label</text>
    <foreignObject x="0" y="0" width="200" height="200">
        <body xmlns="http://www.w3.org/1999/xhtml">
            <span style="position: absolute; left: 300px; top: 100px; transform: rotate(90deg); transform-origin: 0% 11px 0px;" transform="translate(0,0) rotate(90 0 0)">HTML Label</span>
        </body>
    </foreignObject>
</svg>
```
Copy and paste the content of this phantomscript into a new file, lets say `test.js`
```javascript
var page = require('webpage').create();
console.log('Started')
page.open('./test.svg', function (status) {
	console.log('Open')
	if (status === 'success') {
		page.render('example.png');
	}
	phantom.exit(1);
});
```
Run the command `phantomjs test.js` and check out the `example.png` afterwards.

**Comment by jon-a-nygaard** [comment]
This is something that only affects the export server and should therefore be solved there.
@oysteinmoseng It works with prefixing all transform attributes to -webkit-transform.

**Comment by jon-a-nygaard** [comment]
Related to: https://github.com/highcharts/highcharts/issues/4648

**Comment by jon-a-nygaard** [comment]
@oysteinmoseng Is there a link to a commit which fixes this issue, or perhaps some details on why it is closed? :smile:

**Comment by oysteinmoseng** [comment]
Actually this should probably not be closed, @gvaartjes has done some work on export server and it now works for me locally, but I don't have details. Still does not work in production.

**Comment by KacperMadej** [comment]
+1

**Comment by PaulDalek** [comment]
+1

**Comment by jon-a-nygaard** [comment]
@cvasseng could you confirm if this issue still exists in the new export server?

**Comment by sebastianbochan** [comment]
@jon-a-nygaard the issue is still valid (export to any format).

**Comment by bergur** [comment]
+1

**Comment by KacperMadej** [comment]
**Workaround**:
rotate via CSS - demo: http://jsfiddle.net/BlackLabel/95pmtj83/
