### ISSUE TITLE
Dynamic update of tooltip options is not supported

### ISSUE THREAD

**Issue by myagoo** [highcharts/highcharts#5394]
I would like to update some options on tooltip after the chart have been instantiated, like its formater or its shared property for example.
I tried ```chart.options.tooltip.shared = !chart.options.tooltip.shared``` but it does not work. Is there any solution to this issue ?

**Comment by jon-a-nygaard** [comment]
@myagoo You can destroy the old tooltip and instantiate a new tooltip with your updated options like in this example http://jsfiddle.net/jon_a_nygaard/xv27tprz/

**Comment by myagoo** [comment]
Thanks for your help, really appreciated :)

**Comment by TorsteinHonsi** [comment]
FYI, In Highcharts 5 (currently under development), we have a `Tooltip.update` function: http://jsfiddle.net/xv27tprz/1/
