### ISSUE TITLE
Highstock global animation - on first redraw

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#5395]
#### Actual behaviour

When chart is initialized, `globalAnimation` is not set. After first redraw (any redraw, for example drag&drop navigator), `globalAnimation` is set to false, we don't get fancy animation of navigator anymore. 

#### Live demo with steps to reproduce
Simply resize navigator using left/right handles.

http://jsfiddle.net/68tgahbg/

#### Debug
Looks like issue comes from [this commit](https://github.com/highcharts/highcharts/commit/6ca62eff3f7f3d962b2c2fdf6817d8907216c48d#diff-694278219be2847f60a26eb52ca25b27L327). Where line `xAxis.setExtremes(unionExtremes.dataMin, unionExtremes.dataMax, true, false);` used to set `globalAnimation` to false.

The problem is more visible with new Scrollbar, where all items can animate, so using `rangeSelector.selected` also adds an animation. 

Possible solution for new Scrollbar: set `scrollbar.rendered` flag after first `setRange` method (instead of `position`). However, it won't resolve issue with animation in the first redraw.

**Comment by TorsteinHonsi** [comment]
See the live demo: http://jsfiddle.net/68tgahbg/1/

I rethought the whole animation functionality with this commit. With the new commit, any _click_ action on the navigator, scrollbar or range selector should run with animation, but any _drag_ action should not use animation.

Currently the animation is subject to changes in the chart.animation option. A possible improvement would be to add separate animation objects for the rangeSelector and navigator objects.

What do you think @pawelfus ?

**Comment by pawelfus** [comment]
That's nice. 
I think, there will be report in a future about inconsistent animation for rangeSelector buttons and line series: click `6m` -> smooth transition of the line, click `3m` -> path is redrawn without any animation. The same issue when clicking on the navigator: sometimes we get nice animation, and sometimes it's just updated. I guess this may be connected to the number of points? It may be not connected to this ticket, though.

**Comment by TorsteinHonsi** [comment]
> I think, there will be report in a future about inconsistent animation

Absolutely. It is connected to #5294 that emerged after enabling animation on stock charts updates in the first place. What we need is a rewrite of the shift/pathAnim logic so that the series will animate correctly sideways regardless of how many points were added or removed. I've started to think about how it should be done, and will try to have it in place before the next maintenance release.

**Comment by pawelfus** [comment]
I remember, in old version of Highcharts, an issue with animating path with different lengths in SVG. I ended up with adding dummy `L 0 0` by `attr()`, then animating a line to a proper shape. That may be the case anymore (animation is not based on jQuery anymore).

**Comment by TorsteinHonsi** [comment]
I think that's not a problem now, anyway animating between paths of different lengths does work now.
