### ISSUE TITLE
Contrast color is not applied on datalabels - drilldown

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5396]
#### Expected behaviour
Contrast color applied on datalabels

#### Actual behaviour
Black datalabels in column

#### Live demo with steps to reproduce
http://jsfiddle.net/7u7hxbay/

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi: I noticed that the activeDataLabelStyle has a default color of `#0d233a`, will it not be a better default if we switch it to `contrast`?

**Comment by steakchaser** [comment]
The title references drilldown labels, but in the example and in my testing `contrast` also does NOT work on top-level `dataLabels`:  http://jsfiddle.net/tjmoretto/k3anu2sh/

**Comment by pawelfus** [comment]
Hi @steakchaser 

To get contrast working, [`dataLabels.inside`](http://api.highcharts.com/highcharts#plotOptions.column.dataLabels.inside) needs to be set to true (or [`dataLabels.distance`](http://api.highcharts.com/highcharts#plotOptions.pie.dataLabels.distance) < 0 for a pie chart). Then you can set [`dataLabels.verticalAlign: "top"`](http://api.highcharts.com/highcharts#plotOptions.column.dataLabels.verticalAlign) to position labels below the top edge of column. Example for you: http://jsfiddle.net/h4eaaeg9/

**Comment by steakchaser** [comment]
@pawelfus thanks!  Confirmed that it also works in my application chart(s).
