### ISSUE TITLE
Wrong position of text in data labels on errorbar chart after resizing chart block

### ISSUE THREAD

**Issue by alex1kirch** [highcharts/highcharts#5399]
#### Expected behaviour
Position of text in data labels stay correct on errorbar chart after resizing chart block

#### Actual behaviour
Position of text in data labels becomes incorrect after after resizing chart block.

#### Live demo with steps to reproduce

jsfiddle.net/g31xhhh9/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Duplicate of #4133.
