### ISSUE TITLE
Combine two locations in Highmaps

### ISSUE THREAD

**Issue by abielpaltao** [highcharts/highcharts#5400]
I got 2 locations x, y. Is it possible to group it together to form 1 location via jQuery/Highmaps options? I am aware that this is possible through vector graphics software like Inkscape (source: http://www.highcharts.com/docs/maps/custom-maps).

**Comment by oysteinmoseng** [comment]
This forum is generally reserved for issue reporting, for other support questions please take a look at our [support page](http://www.highcharts.com/support) to best get the help you need. With that being said, if you wish to draw multiple points/geometries and treat them as one, the easiest might be to use a map series (map series can have multiple polygons per point).
