### ISSUE TITLE
Data labels align with rotation don't work on bar chart

### ISSUE THREAD

**Issue by legalum** [highcharts/highcharts#5401]
Example : It's not possible to set the data labels to the left when i use a rotation

On the fiddle :
`rotation : 0` --> works as expected
`rotation : 90` --> doesn't work ( label stays to the middle )

http://jsfiddle.net/MrSaccharose/V88xT/5/

**Comment by jon-a-nygaard** [comment]
_Internal note: Logic behind this issue lies in [DataLabels on L205-226](https://github.com/highcharts/highcharts/blob/master/js/parts/DataLabels.js#L205-L226). How come the align affects both y and x values, while verticalAlign affect only y values? Would expect align to only affect x value._

**Comment by Dams591** [comment]
Hey Guys,
Was actually wondering if you had an ETA for that or if you would know a workaround ? 
Thanks a lot.

**Comment by sebastianbochan** [comment]
@jon-a-nygaard +1

**Comment by pawelfus** [comment]
**Workaround:**
Change x-position of the label, snippet:

```javascript
Highcharts.addEvent(Highcharts.seriesTypes.bar, 'afterDrawDataLabels', function() {
  var padding = 4; // +4/-4 pixels for "padding"

  if (this.options.dataLabels.alignToMin) {
    Highcharts.each(this.points, function(point) {

      if (point.dataLabel) {
        point.dataLabel.animate({
          x: this.yAxis.toPixels(
            Highcharts.pick(this.options.threshold, 0),
            true
          ) +
          (point.negative ? -point.dataLabel.getBBox().width - padding : padding)
        })
      }
    }, this);
  }
});
```

Snippet adds new option called `dataLabel.alignToMin`, demo: http://jsfiddle.net/BlackLabel/7z1309y2/
