### ISSUE TITLE
PlotLine click event does only fire when clicking directly on the plotLine

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#5402]
If the mouse is with 10-20 px radius from an actual series, plotLine click event will not fire. 

See http://jsfiddle.net/o7ug4qq6/1/ - if you try to click the plot line close to the actual series line, the click event will not fire. It should not matter that you clicked the series, or near the series, as long as the mouse is over the plot line the event should fire.  

Same bug for mouseenter and mouseout events

**Comment by pawelfus** [comment]
It's caused by tracker for line series, see: http://jsfiddle.net/o7ug4qq6/3/ 

**Workaround:**
This tracker size can be changed by setting [`tooltip.snap`](http://api.highcharts.com/highcharts/tooltip.snap), demo: http://jsfiddle.net/o7ug4qq6/4/
