### ISSUE TITLE
When showing single datapoint, Y-axis gridline values are not as expected

### ISSUE THREAD

**Issue by extremeandy** [highcharts/highcharts#5404]
#### Expected behaviour

When there are multiple Y-axes with a single datapoint per series, the Y-axis gridlines should:
1. Have values rounded off to sensible values (e.g. 0, 5, 10, 15, rather than 0.1234, 5.1234, 10.1234, 15.1234)
2. Have intervals that are chosen relative to the magnitude of the datapoint Y-values (e.g. a value of 2.39 should result in intervals of 0, 5, 10, 15 rather than 2.39, 102.39, 202.39, 302.39)
#### Actual behaviour
1. Values are not always rounded
2. Intervals are not always relative to the magnitude of the datapoint Y-values
#### Live demo with steps to reproduce
1. View this [jsfiddle](http://jsfiddle.net/nx0caoug/)
2. Observe that the secondary Y-axis values are not rounded, and intervals are not useful
#### Workaround

If there is only a single value, set config.yAxis.min = 0 if value >= 0, or yAxis.max = 0 if value < 0.

[Workaround jsfiddle](http://jsfiddle.net/osjygap1/)

**Comment by jon-a-nygaard** [comment]
My opinion is that a yAxis with a single point should behave the same wether or not there a more than one yAxis. E.g. in [this example](http://jsfiddle.net/jon_a_nygaard/nx0caoug/2/) the first yAxis should behave the same in both charts (which they do not).

But I also think that when a yAxis has only a single point, 
`min: 0` would be a good default. Like in [this example](http://jsfiddle.net/jon_a_nygaard/umpo2p9f/1/)

What do you say @TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
As long as we have only a single value, we know nothing of the magnitude. We can't assume that the value relates to 0 in any way. That's why we only draw the [single tick mark and grid line](http://jsfiddle.net/umpo2p9f/2/).

Now if we know that the value relates to 0, we have the threshold option that is meant for this situation. The only problem is it doesn't work directly, it only works when the series is area: http://jsfiddle.net/umpo2p9f/3/

**Comment by pawelfus** [comment]
Just a small note: the issue is also connected to `alignTicks` option. When using just one axis, then point is centered on the chart: http://jsfiddle.net/umpo2p9f/4/

In general, a good workaround is to use `yAxis.minRange`, demo: http://jsfiddle.net/umpo2p9f/5/ and http://jsfiddle.net/nx0caoug/4/
