### ISSUE TITLE
HighMaps: Incorrect Map Properties in map collection provided by HighCharts

### ISSUE THREAD

**Issue by GaneshBChandgude** [highcharts/highcharts#5405]
#### Expected behaviour

For World Map, 
    iso-a2 corresponds to ISO 3166-1 alpha-1 standard
    iso-a3 corresponds to ISO 3166-1 alpha-2 standard

For Country Maps,
    hc-key corresponds to ISO 3166-2 standard (for most countries)

Won't it be better to add a proper iso 3166-2 attribute for country maps? Or instead correct the current hc-keys and postal codes for country maps?
#### Actual behaviour

Many geojsons provided at http://code.highcharts.com/mapdata/ contain incorrect map properties.

Example:
For United Kingdom map, postal codes for many divisions are null. Moreover, the hc-keys for the divisions are not standard. For Anglesey, hc-key is gb-ay which should be gb-agy. For Orkney, hc-key is gb-3270 which should be gb-ork and postal code for the same should be ORK. Refer https://en.wikipedia.org/wiki/ISO_3166-2:GB

For India, Gujarat's hc-key is incorrectly shown as in-2984 which should have been in-gj, and postal code is null, which should have been GJ. Refer https://en.wikipedia.org/wiki/ISO_3166-2:IN

**Comment by oysteinmoseng** [comment]
This is a known issue, related to #5105.

The properties added to the maps depend on our source data, which for many areas are lacking. As mentioned in the other issue, you can vote for changes to individual areas on our [UserVoice forum](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api).

Which properties are available and an explanation of `hc-key` (it's not always ISO based) can be found [here](http://www.highcharts.com/docs/maps/map-collection) ("Map Properties" section).

**Comment by sventech** [comment]
We've been collecting the latest ISO3166-2 region data for this open source project (MIT):
https://github.com/benkeen/country-region-data -- you could use that to update your maps, at least in cases where you have the correct regions.

**Comment by oysteinmoseng** [comment]
@sventech Thank you for that, that looks very useful!

**Comment by kamilkulig** [comment]
**Demo** with new filed `iso-3166-2` added to GB map: http://jsfiddle.net/BlackLabel/95fwj7dy/

_Internal note:_ 
Values of ISO 3166-2 added to source and included as property in output map.

**Comment by kamilkulig** [comment]
Demo with new filed `iso-3166-2` added to **India** map: http://jsfiddle.net/BlackLabel/95fwj7dy/

_Internal note:_
Values of ISO 3166-2 added to source and included as property in output map.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#6
