### ISSUE TITLE
Scatter rendering Issue

### ISSUE THREAD

**Issue by panickerr** [highcharts/highcharts#5407]
#### Expected behaviour
I have two scatters along with a column chart(vertical) and wanted all three labels to be present 

#### Actual behaviour
The max score is :100; and only the column and one of the scatter value gets rendered. Also i noticed that when the value of the lesser scatter is above 95 its showing, but as soon as it cross the 95 mark it doesnt show the label. But this issue is not happening with the bar graph(horizontal) where both the labels are being shown in most of the test cases

Here in case of the value 96 when i toggle the column chart the value of 96% appears but when the column chart is present it doesnt. 
![85](https://cloud.githubusercontent.com/assets/11805862/16112035/20371446-33d3-11e6-81b4-32f38c6525a2.PNG)
![95](https://cloud.githubusercontent.com/assets/11805862/16112038/2041483a-33d3-11e6-8b86-6317a152b711.PNG)
![96don](https://cloud.githubusercontent.com/assets/11805862/16112036/203e1b92-33d3-11e6-9ad6-4684bdba72ce.PNG)
![97](https://cloud.githubusercontent.com/assets/11805862/16112037/203f68f8-33d3-11e6-8264-7fa1d1b942b9.PNG)

#### Live demo with steps to reproduce

The code for the datalabels for scatter is given below
` scatter: {
                        dataLabels: {
                            enabled: true,
                            align: 'left',
                            x: 5,
                            y: 12,
                              format: '{y}%',
                            marker: {
                                radius: 8,
                                fillColor: 'blue',
                            },
                            style: {
                                fontWeight: 'normal'
                            }
                        }, tooltip: {
                            pointFormat: '<b> </b><br> {point.y}%'
                        }
                    },  `

#### Affected browser(s)
Chrome, Firefox

**Comment by jon-a-nygaard** [comment]
Hi @panickerr 
I think you are looking for something like [this example](http://jsfiddle.net/jon_a_nygaard/hscyczt7/2/) 

Highcharts has an option [dataLabels.allowOverlap](http://api.highcharts.com/highcharts#plotOptions.series.dataLabels.allowOverlap) option which will make the data labels visible even when they collide.

**Comment by panickerr** [comment]
Thanks @jon-a-nygaard ,
The issue got solved. i just had to use 'allowOverlap: true' from the code.
