### ISSUE TITLE
Unable to update marker properties for a point when in turbo mode.

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5409]
#### Behaviour
Unable to update marker properties for a point when in turbo mode.
If turboThreshold is exceeded and a chart runs in turbo mode, then Point.update() is not updating marker. Only halo color changes and tooltip's border color.

#### Live demo with steps to reproduce
http://jsfiddle.net/74w3gsf6/1/

**Comment by TorsteinHonsi** [comment]
The idea of turbo mode is to save processing speed by not allowing complex configuration for individual points. Instead, only pure data values are allowed. [This line](https://github.com/highcharts/highcharts/blob/v4.2.5/js/parts/Series.js#L1107) in the getAttribs method prevents the new settings from being applied.
