### ISSUE TITLE
IE11: Exported PNG/JPG of chart is blank

### ISSUE THREAD

**Issue by mjsteichen** [highcharts/highcharts#5410]
#### Expected behaviour
Exported png/jpg in IE11 contains plot, including images axis labels, when using offline exporting module (we don't have the option of falling back to the export server for the project I'm working on).

#### Actual behaviour
Exported png/jpg is blank.

#### Live demo with steps to reproduce
http://jsfiddle.net/msteichen/d79qht46/1/

Download as png or jpg and open exported file. (downloading as SVG works as expected).

#### Affected browser(s)
IE11

**Comment by TorsteinHonsi** [comment]
According to http://www.highcharts.com/docs/export-module/client-side-export the combination of inline images and IE11 gives a "suboptimal image" which I can confirm. 

@oysteinmoseng In this case where the image is utterly useless, should we throw an error or fall back to the export server?

**Comment by oysteinmoseng** [comment]
@TorsteinHonsi: Sounds like a plan. We'll probably have to do browser detection, though. If I remember correctly, the canvas functions return successfully despite the useless image.

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi @oysteinmoseng I forgot to mention this, but I tried the same fiddle and removed the images, then it still did not work for png, but it worked for jpg.
Windows 10 and IE 11

**Comment by oysteinmoseng** [comment]
@jon-a-nygaard: Weird, the code for PNG and JPEG should be identical except for a parameter to the canvas converting function. I'm pretty sure IE11 PNG used to work in Windows 7. I'll look into it.

We should probably also provide an example of a hook where the user can do his own browser detection or whatever, and force a fallback.

**Comment by aaronogan** [comment]
In our particular case, we're not able to fall back to the export server (and we're also trying to avoid setting up our own export server).

It seems that the problem could be stemming from the usage of blob.  Could we use an alternative such as [this](https://gist.github.com/gustavohenke/9073132) that uses [XMLSerializer.serializeToString()](https://developer.mozilla.org/en-US/docs/Web/API/XMLSerializer)?

**Comment by oysteinmoseng** [comment]
IE is acting really weird here. As an example: Running Windows 7 and IE11, attempting to export to either PNG or JPEG (without embedded images) will fail on the first try, but subsequent exports are fine. Running Windows 10 with IE11, PNG export always fails, and JPEG always succeeds.

I've tried falling back to various data URIs as well as using XMLSerializer and Base64 objects, but so far no luck. Will continue to investigate.

The gist you linked to, @aaronogan, also mentions potential issues with namespaces in the SVG, but those do not seem to apply to IE11, at least in our case.

It's worth mentioning that Edge (13) always fails, but at least gracefully falls back to the export server.

**Comment by oysteinmoseng** [comment]
Found that most of our issues with IE11 are caused by an evasive bug in the browser where the image load handler is sometimes called before the image is actually ready. Deferring the load handler with a small timeout seems to remedy the issue. 

Also found that Edge has a bug where it capitalizes several SVG attribute names (`fill="red"` becomes `FILL="red"`), which appears to mess up things across the board. I got downloading to work by using CanVG, but because of this bug the rendering is all wrong.

Can't promise that I can get all of these browsers to accept embedded images, but at least for normal charts we should have a working fix over the weekend, and graceful fallback to the export server.

**Comment by aaronogan** [comment]
Thanks for the update.  We feel your pain on this one.  And appreciate that you're looking into it.

Do you have a link to information about the bug about the load handler firing too soon?  Not sure that we observed that behavior in IE 11 on Windows 10.

**Comment by oysteinmoseng** [comment]
@aaronogan: It seems to be an intermittent bug, and mostly related to SVG drawing. Some related info [here](https://connect.microsoft.com/IE/feedback/details/1725171/ie11-canvas-drawimage-method-intermittent-failure-when-called-via-image-onload-callback) and [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4411619/).

**Comment by oysteinmoseng** [comment]
IE11 now works for charts without embedded images. Same with Edge, assuming newest version of CanVG is loaded (just load before calling the offline-exporting functions, and the script will use the preloaded canvg).

IE10, IE11 and Edge all fail for embedded images, producing a blank image result. Will look into this further. If tricky, we might resort to just falling back to the export server for these cases.

Note that export to SVG works in all cases.

**Comment by oysteinmoseng** [comment]
Could not get IE/Edge to work with embedded images and PNG/JPEG, so for now we will have to resort to falling back to the export server. At least now we are throwing an exception properly, and charts without embedded images should be working.

**Comment by jon-a-nygaard** [comment]
@oysteinmoseng Do you have a link to the commit which fixes this? :smile:

**Comment by oysteinmoseng** [comment]
@jon-a-nygaard The two commits above, or mainly commit 1921941.

**Comment by jon-a-nygaard** [comment]
@oysteinmoseng Sorry, somehow I did not notice them.
