### ISSUE TITLE
Highstock: pointRange is lost if another series is added dynamically

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5413]
#### Behaviour

pointRange is lost for the series if another series is added dynamically
#### Live demo with steps to reproduce

http://jsfiddle.net/g7es8169/1/

**Comment by TorsteinHonsi** [comment]
It's related to `xAxis.ordinal`, when it is set to false the point range is static: http://jsfiddle.net/highcharts/g7es8169/2/

**Comment by pawelfus** [comment]
*Internal note:*
It's connected to the `xAxis.ordinalSlope` (used in `getColumnMetrics` method), which is calculated from all series. Maybe calculating this per `pane` (?) would be a better solution.
