### ISSUE TITLE
Plot line does not render, and remain hidden when using grid lines

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#5415]
Some plot lines does not get rendered and remain hidden although they exists in the DOM. This seems to happens when a grid line is over a plot line. Please see here: http://jsfiddle.net/onemenny/surf77u2/1/ 

If you comment line 86 (gridLineWidth: 1) and click "add plot line" button you will see 2 lines, when you uncomment you see only 1 line. It seems that the problem is more consist in Chrome than in FF

**Comment by pawelfus** [comment]
It's caused by default value for `zIndex` for plotLines. You can simply change `zIndex`, see: http://jsfiddle.net/surf77u2/2/

**Comment by onemenny** [comment]
Great!!
