### ISSUE TITLE
Connecting NULLS in polar line chart

### ISSUE THREAD

**Issue by sdom** [highcharts/highcharts#5416]
#### Behaviour
For chart type line - polar - when the first point in data array is NULL the first and the last point are not connected with the line. The points (first and last) are connected if the last point in data is NULL.

#### Live demo with steps to reproduce
http://jsfiddle.net/xfvjg7np/5/

#### Affected browser(s)
All

**Comment by jon-a-nygaard** [comment]
For this and similar cases we can consider adding a utility function based on [Array.prototype.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find). Have a look at [this commit](https://github.com/highcharts/highcharts/commit/65432b7103b6ba93a7184d114df22773b0a09f58) to see how it can be done.

**Comment by jon-a-nygaard** [comment]
Closing this as it is fixed in b80ceef
