### ISSUE TITLE
Strange responsiveness issue for very long category name

### ISSUE THREAD

**Issue by ipip2005** [highcharts/highcharts#5417]
#### Expected behaviour
smoothly responsive

#### Actual behaviour
the columns disappear. only show text.

#### Live demo with steps to reproduce
http://jsfiddle.net/regz93p9/1/
drag the left edge of the sub-window that contains the chart **`a little bit`** to trigger chart reflow.

#### Affected browser(s)
chrome tested

**Comment by ipip2005** [comment]
![image](https://cloud.githubusercontent.com/assets/7711735/16201111/bb79d962-3742-11e6-9278-c323c69ad164.png)

**Comment by TorsteinHonsi** [comment]
Simplified and normalized demo: http://jsfiddle.net/highcharts/regz93p9/2/

The labels are wrong both before and after resize. Before resize they overlap with the legend, and after resize they squeeze the plot area together.

Also note that it just happens with `useHTML: true`.

**Comment by TorsteinHonsi** [comment]
It's a regression, fails since https://github.com/highslide-software/highcharts.com/commit/e1fcb65 and Highcharts v4.2.2.
