### ISSUE TITLE
Grid lines ticker or misaligned when multiple yAxis have grid lines enabled 

### ISSUE THREAD

**Issue by ernestbofill** [highcharts/highcharts#5420]
#### Expected behaviour

All grid lines have the same thickness
#### Actual behaviour

Grid lines sometimes become thicker when there are multiple yAxis with grid lines enabled. Resizing the chart container vertically will occasionally produce this behavior
https://i.gyazo.com/5e4b842c638343296a315fbba5160561.png
#### Live demo with steps to reproduce

http://jsfiddle.net/z3b8znbv/1/

With the current container height of 610px the top line is thicker than the rest. Some other heights produce the same effect and some don't

**Comment by pawelfus** [comment]
This is how it looks on osx+chrome:

![screen shot 2016-06-21 at 14 50 52](https://cloud.githubusercontent.com/assets/1453926/16229985/9ac214d2-37bf-11e6-8514-d0fda3e59908.png)

**Comment by ernestbofill** [comment]
This is on Chrome + Windows 10
https://gyazo.com/1a08577d0a2dd44ac8a2e67f395b5797

I don't want to disable any `gridLinesWidth` because on the legend series can be shown or hidden and if the axis that has grid lines has no visible series then there will be no grid lines at all.

`chart.alignTicks` is already true by default on the example I provided.

It seems this could be a browser/platform specific issue.

Thanks!

**Comment by TorsteinHonsi** [comment]
We're basically seeing more than one grid line on top of each other.

> It seems this could be a browser/platform specific issue.

Yes that may be. It may be that the lines are not pixel-perfect on top of each other. I suspect that page zoom may also play a role, maybe the pixels don't draw one-to-one on the screen pixels.

**Comment by TorsteinHonsi** [comment]
> I don't want to disable any gridLinesWidth because on the legend series can be shown or hidden and if the axis that has grid lines has no visible series then there will be no grid lines at all.

Maybe we should add an option that when `chart.alignTicks` is true, only the first visible series' grid lines are show. And it would be dynamic so that as long as there is a visible axis, there are grid lines.

**Comment by ernestbofill** [comment]
I think that would solve it. We would like that option

**Comment by Dzumali** [comment]
Hi @TorsteinHonsi - What's the status for this request that Ernest has ask for? We still have this issue.
