### ISSUE TITLE
Highcharts not displayed in iOS devices inside Lightning Framework in Salesforce1 app.

### ISSUE THREAD

**Issue by aravindqb** [highcharts/highcharts#5421]
Hi all,

I'm using Highcharts to represent some data inside Lightning framework in the Salesforce1 app. But the graph is not at all being displayed in iOS devices. (_used strict mode_).
The parent div enclosing the Highcarts is displayed, but the charts are not displayed. The graph is rendering properly in Android devices.

Also, while testing in the browser simulator (here, I'm using Chrome, its coming, but when you open the same on device, it's not coming at all)

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
