### ISSUE TITLE
HighMaps resets custom hover colour on zoom

### ISSUE THREAD

**Issue by deep42** [highcharts/highcharts#5422]
#### Expected behaviour

When defining a different hover colour for specific points, the chart should keep that colour at all times.
#### Actual behaviour

When zooming (or any event that triggers redrawing the chart), it reverts to the initial colour
#### Live demo with steps to reproduce

http://jsfiddle.net/bz2em9x5/
1. Hover over USA or Russia - pink
2. Zoom in
3. Hover over USA or Russia - yellow as the rest
#### Affected browser(s)

All

**Comment by deep42** [comment]
Redneck workaround:

```
function hoverHack() {
    points[157].pointAttr.hover.fill = 'pink';
    points[202].pointAttr.hover.fill = 'pink';
}
```
...
```
chart: {
    events: {
        redraw: hoverHack
    }
}
```

http://jsfiddle.net/rat5m59u/

**Comment by sebastianbochan** [comment]
_Internal note_
Currently there are no option to set hover state per particular point (in other series too)
