### ISSUE TITLE
Crosshairs overlapping

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#5424]
Hi,
#### Behaviour:

It seems that in line chart, in Highstock the number of yAxis affects the number of times crosshair is drawn, while in Highcharts it doesn’t matter how many yAxis there are, the crosshair is drawn only once. Beside of this, 'multiplied crosshairs' in first case overlaps each other, giving the impression that crosshair’s color is darker, please take a look at this example: http://jsfiddle.net/d_paul/bfL2nzk9/2/. Although it occurs only when crosshair’s width is set to 1. Changing this to higher value makes ‘crosshairs’ don’t overlap and crosshair’s color is displayed correctly.

Best regards.

**Comment by pawelfus** [comment]
Thank you for reporting. Indeed, issue comes only from Highstock, where extra logic is added to support multiple panes. 

*Internal note:*
`uniqueAxis` [here](https://github.com/highcharts/highcharts/blob/4f8e87ae93be673a13e538431250cd0fc5b64a09/js/parts/StockChart.js#L224) most probably should compare not only object, but also position of the axis. If `axis.pos` and `axis.len` are the same, then leave axis out of the scope. 

Example for generated paths Highcharts vs Highstock: http://jsfiddle.net/yu3encs3/

**Comment by jon-a-nygaard** [comment]
@PaulDalek @pawelfus Tried to locate this issue, but was not able to do so. Does this issue still exist?

**Comment by pawelfus** [comment]
Yes, it does, compare:
- Highcharts: http://jsfiddle.net/bfL2nzk9/4/
- Highstock: http://jsfiddle.net/bfL2nzk9/5/
