### ISSUE TITLE
Hovereffect showing only once

### ISSUE THREAD

**Issue by Newan** [highcharts/highcharts#5428]
If I hover the cursor over a datapoint, the desired hover-effect is being shown - so far so good.
If the cursor now leaves the datapoint (which results in the hover-effect not being shown furthermore) and returns to that same datapoint whithout touching another one(!), the hover-effect is missing and instead just a line is shown.

Animated Gif for understand:
![highchartshoverbug](https://cloud.githubusercontent.com/assets/3693094/16295804/20a86424-3929-11e6-959a-29cf4b0c90ab.gif)

#### Live demo with steps to reproduce
http://jsfiddle.net/2x78fg7n/

#### Affected browser(s)
Testing in FireFox 47.0

**Comment by pawelfus** [comment]
It works fine when tooltip is enabled (http://jsfiddle.net/8bbp5b9v/ vs http://jsfiddle.net/8bbp5b9v/2/), so as for workaround, we can enable tooltip, and in formatter return false: http://jsfiddle.net/8bbp5b9v/3/

      tooltip: {
        enabled: true,
        formatter: function () {
        	return false;
        }
      },

**Comment by Newan** [comment]
Of course but then you combine it with the workaround "Tooltipp only on click" the solution fails:

http://jsfiddle.net/8bbp5b9v/4/

**Comment by jon-a-nygaard** [comment]
Thanks for reporting this issue will be fixed in the next maintenance release. For those in need of a workaround have a look below.

__Workaround__ 
Open your src file in a text editor and locate the following line of code inside the 'reset* function:
```javascript
reset: function (allowMove, delay) {
...
// Replace this line
pointer.hoverX = chart.hoverPoints = chart.hoverPoint = null;

// With this line
pointer.hoverX = pointer.prevKDPoint = chart.hoverPoints = chart.hoverPoint = null;
...
}
```
