### ISSUE TITLE
tickInterval is no use in multiple y-axis

### ISSUE THREAD

**Issue by billzt** [highcharts/highcharts#5433]
#### Expected behaviour
A column chart with two y-axis, each is set with min, max, and tickInterval

``` javascript
                yAxis: [{
                    max: 5000,
                    min: 0,
                    tickInterval: 1000,
                    startOnTick: false,
                    endOnTick: false,
                    title: {
                        text: 'YAxis A'
                    }
                }, {
                    max: 75,
                    min: 0,
                    tickInterval: 15,
                    startOnTick: false,
                    endOnTick: false,
                    title: {
                        text: 'YAxis B'
                    },
                    opposite: true,
                }],
```

I want 
Y Axis A to be: 0 1k 2k 3k 4k 5k
Y Axis B to be: 0 15 30 45 60 75

#### Actual behaviour
The chart render with wrong tickIntervals.
Y Axis A to be: 0 2k 4k 6k
Y Axis B to be: 0 30 60 90

#### Live demo with steps to reproduce
https://jsfiddle.net/9updvx2n/1/

How shoud I do to get my wished tickIntervals?

**Comment by pawelfus** [comment]
Hi,
Thank you for your report. This is caused by [`chart.alignTicks`](http://api.highcharts.com/highcharts#chart.alignTicks). When setting to false, it works as you expect: https://jsfiddle.net/9updvx2n/2/

However, I agree, it looks strange, that ticks are removed from both axes.

**Comment by billzt** [comment]
After add alignTicks: false, it has been fixed.
