### ISSUE TITLE
Highcharts Scatter graph,tooltip not working.

### ISSUE THREAD

**Issue by rajivmandal** [highcharts/highcharts#5434]
In highcharts scatter graph tooltip,display dynamic value just like point.x:10.
I want to display point.name:a

Code:

    var readingarray = [];
    var listobj = JSON.parse(data[0].Value);
    for (i = 0; i < listobj.length; i++) {
      var eacharray = [];
      eacharray.push(parseFloat(listobj[i].CorrectedReading.toFixed(2)));
      eacharray.push(parseFloat(listobj[i].ReadingVOutput.toFixed(2)));
      readingarray.push({
        x: parseFloat(listobj[i].x.toFixed(2)),
        y: parseFloat(listobj[i].y.toFixed(2)),
        NAME: listobj[i].name
      });
    }
    $('#container').highcharts({
      chart: {
        type: 'scatter',
        zoomType: 'xy'
      },
      title: {
        text: 'Test Chart -'
      },
      subtitle: {
        text: Test
      },
      xAxis: {
        title: {
          enabled: true,
          text: 'X'
        },
        startOnTick: true,
        endOnTick: true,
        showLastLabel: true
      },
      yAxis: {
        title: {
          text: 'Y'
        }
      },
      plotOptions: {
        scatter: {
          marker: {
            radius: 5,
            states: {
              hover: {
                enabled: true,
                lineColor: 'rgb(100,100,100)'
              }
            }
          },
          states: {
            hover: {
              marker: {
                enabled: false
              }
            }
          },
          tooltip: {
            shared: false,
            crosshairs: true,
            formatter: function() {
                return 'Branch: <b>' + this.series.name +
                  '</b><br/>Platform: ' + this.point.x + ' <br> name ' + this.point.name;
              }
              //headerFormat: '<b>{series.name}</b><br>',
              //pointFormat: '{point.x} , {point.y} '
          }
        }
      },
      series: [{
        name: 'NAME',
        color: 'rgba(96,169,223, .5)',
        data: readingarray
      }]
    });

**Comment by pawelfus** [comment]
Hi,

This is our bug tracker, for questions, please use our forum or contact with us via email. You can find more info here: http://www.highcharts.com/support

Thanks,
Paweł
