### ISSUE TITLE
phantomjs export highcharts in server, some data labels not shown in column chart image

### ISSUE THREAD

**Issue by yanshuai** [highcharts/highcharts#5435]
Hi, I use phantomjs to export highcharts to image in server, but I found that some data labels  not shown in column chart, for example:
![image](http://www.sartisty.name/img/highcharts_bug.png)

How can I make all the data labels showing in the image?

**Comment by pawelfus** [comment]
Hi, you can set [`series.dataLabels.allowOverlap`](http://api.highcharts.com/highcharts#plotOptions.series.dataLabels.allowOverlap) to `true`.
