### ISSUE TITLE
Angular gauge steps with floating point

### ISSUE THREAD

**Issue by davit-abgaryan** [highcharts/highcharts#5436]
Set the minimum to 0.5, maximum to 6.5 and the label step to 2
#### Expected behaviour
Steps: 0.5, 2.5, 4.5, 6.5

#### Actual behaviour
Steps: 1, 3, 5

#### Live demo with steps to reproduce
http://jsfiddle.net/17eb1q9d/

#### Affected browser(s)
*

**Comment by pawelfus** [comment]
Hi,

Thank you for reporting the issue. [`labels.step`](http://api.highcharts.com/highcharts#xAxis.labels.step) determines which labels are rendered, not interval between labels. I think you want to use [`tickPositions`](http://api.highcharts.com/highcharts#xAxis.tickPositions): http://jsfiddle.net/17eb1q9d/1/
