### ISSUE TITLE
Ticks are not being aligned with data points on a line graph with xAxis being 'datetime'

### ISSUE THREAD

**Issue by plamens** [highcharts/highcharts#5437]
We have a line chart with the xAxis being the timestamp and the yAxis - some random value. 
The timestamps of the data points are 20000 ms apart. 

#### Expected behaviour

All ticks should be aligned with the data points on the lines (even when zooming in).

#### Actual behaviour

The graph shows the ticks 30000 ms apart, misaligned with the timestamps of the data points.
Also, zooming on the graph displays ticks 15000 ms apart even though a value of 20000 has been specified as a 'minTickInterval' for the xAxis.

#### Live demo with steps to reproduce
http://jsfiddle.net/jLvax2dz/1/

#### Affected browser(s)
We tested on Firefox and Chrome, but it doesn't appear to be something browser-specific

**Comment by pawelfus** [comment]
Hi,

Thank you for reporting. To achieve one tick per point, you can use [`xAxis.tickPositioner`](http://api.highcharts.com/highcharts#xAxis.tickPositioner). It's a bit tricky:

      xAxis: {
        type: 'datetime',
        minTickInterval: 20000,
        tickPositioner: function(min, max) {
          var ticks = this.series[0].processedXData.slice();

          ticks.info = this.tickPositions.info; // use proper format for la

          return ticks;
        }
      },

But it works: http://jsfiddle.net/tuo9ybjb/

**Comment by plamens** [comment]
Thanks for the prompt response!

The provided JsFiddle was just an illustration of the problem. In reality there are more data points (say around 200) and in that case the proposed solution isn't working fine. The problem is that it shows one tick per data point which is too dense. 

For instance: http://jsfiddle.net/tuo9ybjb/2/

Implementing a tickPositioner that skips some of the data points would be hard because we would have to take into account the width of the labels and the width of the chart (e.g. when resizing). This kind of tick positioning that skips some of the data points is already provided by the library. Is there a way to get this working without rewriting that functionality?

**Comment by pawelfus** [comment]
Hi @plamens,

My apologies for a late reply. I agree it may be tricky to calculate all bounding boxes etc. In that case, you can use [`xAxis.units`](http://api.highcharts.com/highcharts#xAxis.units). For example: http://jsfiddle.net/jLvax2dz/2/
