### ISSUE TITLE
Borders are not acting properly on Pie chart with 3D enabled

### ISSUE THREAD

**Issue by shangzb87** [highcharts/highcharts#5438]
#### Expected behaviour

In pie chart, with 3D enabled
1. when `series[].borderColor` is set and `series[].borderWidth` is set to a number that bigger than 0, display a border around the pie and each slice; when `series[].borderWidth` is set to 0 or null, do not display a border around the pie.
2. while setting up `data[].borderColor` and `data[].borderWidth` for each individual slice (each object in `series[].data`), each slice display its individual border effect. 
#### Actual behaviour
1. With `series[].borderColor` set, not matter the `series[].borderWidth` is set or not, the border is displayed anyway; no matter how much is the `series[].borderWidth`, the border width is also displayed `1`.
2. With `data[].borderColor` and `data[].borderWidth` set, there is not effect at all for the border.
#### Live demo with steps to reproduce

https://jsfiddle.net/scottszb1987/jzfrfzfd/
#### Affected browser(s)

Chrome

**Comment by pawelfus** [comment]
Hi,

Thank you for reporting! Could you tell me where did you find information about `data[].borderColor` and `data[].borderWidth` for a pie chart? I don't see anything like that in [API](http://api.highcharts.com/highcharts#series<pie>.data).

In 3D, we have `series.edgeWidth` and `series.edgeColor`, which looks like undocumented in API (it's the same as for column). See working demo: https://jsfiddle.net/53042mpr/

And `edgeWidth` by default it's 1px, and `edgeColor` is the same as point color (that also explains why changing `edgeColor` is enough to get a border).

**Comment by scottszb1987** [comment]
Thanks a lot! That does solve my curious! 

By the way, the `data[].borderColor` and `data[].borderWidth` were not found anywhere but experimented and somehow worked in 2D pie chart. I was expecting the same behaviour in 3D mode.

Unfortunately, seems there are not `edgeWidth` and `edgeColor` api for `data[]`, we could only set the `edge` for the whole pie chart. Is there any workaround to configure the `edgeWidth` and `edgeColor` individually for each slice?

**Comment by pawelfus** [comment]
You are right, there's no `edgeWidth`/`edgeColor` for individual points: [related code](https://github.com/highcharts/highcharts/blob/46fe6c373b1dc69fa78cff6bf887594a1d077c08/js/parts-3d/Pie.js#L62-L81).

Workaround is possible, but will be tricky:

- include `highcharts.js` 
- include `workaround.js`
- include `highcharts-3d.js`

It's important to include `highcharts-3d` after the workaround. Otherwise `3D` will overwrite our workaround.

And for the workaround, please take a look: https://jsfiddle.net/h7pk7vnj/ 

Snippet:

    (function (H) {
      H.wrap(H.seriesTypes.pie.prototype, 'drawPoints', function (p) {
        var chart = this.chart;

        if (chart.is3d()) {
          H.each(this.data, function (point) {
            point.pointAttr[''].stroke = point.options.borderColor;
            point.pointAttr['']['stroke-width'] = point.options.borderWidth;
          });
        }

        p.apply(this, [].slice.call(arguments, 1));
      });
    })(Highcharts);

**Comment by pawelfus** [comment]
`series.edgeWidth` and `series.edgeColor` are documented now, closing the issue.
