### ISSUE TITLE
SAFARI: Tooltip text is not being shown

### ISSUE THREAD

**Issue by qingweibinary** [highcharts/highcharts#5439]
#### Expected behaviour
Tooltip text should be shown as below (in Chrome)

<img width="1189" alt="screen shot 2016-06-28 at 3 37 35 pm" src="https://cloud.githubusercontent.com/assets/14971922/16407442/48c72a8c-3d46-11e6-8a85-a6325855ff08.png">

#### Actual behaviour
Text is not shown, as below (in Safari)

<img width="1191" alt="screen shot 2016-06-28 at 3 32 08 pm" src="https://cloud.githubusercontent.com/assets/14971922/16407460/6aef238a-3d46-11e6-9853-59bdbd21e3ce.png">

#### Live demo with steps to reproduce

Not able to reproduce in jsfiddle.

#### Affected browser(s)
Safari

Any help are appreciated

**Comment by pawelfus** [comment]
Hi,

Thank you for contacting us. It's hard to guess what is wrong with just screenshots and debugging is out of the question :) For support questions, please contact with us directly or us our forum, more details [here](http://www.highcharts.com/support).

If you can not recreate issue on jsfiddle, then I would guess it's related to your CSS or you perhaps your are using old version of Highcharts.

Thanks,
Paweł

**Comment by qingweibinary** [comment]
Thanks, for the record

I tried override the default css using tooltip.css api, as suggested, and it works.

Probably Safari treat CSS differently than chrome.
