### ISSUE TITLE
xAxis.title will not align properly

### ISSUE THREAD

**Issue by WimWWimW** [highcharts/highcharts#5440]
#### Expected behaviour
The title of the xAxis is expected to align according the instructions given by title: {align: 'xxx',}

#### Actual behaviour

- whatever value of xxx, the title aligns Left
- if align is left out entirely, the title aligns Center

#### Live demo with steps to reproduce

$(function () {
    $('#container').highcharts({
        chart: {
            plotBorderWidth: 1,
            marginLeft: 80
        },
        xAxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        title: {
            text: 'Title aligned right',
            align: 'right',
            x: 70
               },        
         },

        series: [{
            data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
        }]
    });
});

**Comment by pawelfus** [comment]
Hi,

Thank you for reporting your issue. The problem is that [`xAxis.title.align`](http://api.highcharts.com/highcharts#xAxis.title.align) doesn't have an option like `"right"`. From API:

> Alignment of the title relative to the axis values. Possible values are "low", "middle" or "high". Defaults to middle.
