### ISSUE TITLE
Clippaths wrong size - markers aren't visible

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5442]
#### Actual behaviour
Clippaths wrong size - markers aren't visible

#### Live demo with steps to reproduce
1. Demo http://jsfiddle.net/nrbfteby/
2. Click update
3. Click Resize
4. Markers aren't visible

**Comment by jon-a-nygaard** [comment]
This seems to have something to do with the customEvents.js, as you can see from the following example it works as exepcted when that script is commented out: http://jsfiddle.net/nrbfteby/2/

**Comment by sebastianbochan** [comment]
@jon-a-nygaard  Im not sure, let's analyse better demo: http://jsfiddle.net/rommd1eo/

**Comment by jon-a-nygaard** [comment]
@sebastianbochan Thanks, will look into what happens in the code. It seems that wether the animation is enabled or not has no impact on the outcome. As long as animation is updated on the series this issue appears.

**Comment by jon-a-nygaard** [comment]
_Internal Note: this happens only with the last point, [example](http://jsfiddle.net/rommd1eo/5/)

**Comment by jon-a-nygaard** [comment]
According to `git bisect` the first bad commit which broke this functionality is 1351db5218b042c1979dd1716f1687ffa67a9525

Seen in [this example](http://jsfiddle.net/rommd1eo/6/)
