### ISSUE TITLE
Legend width is to big when legend.x have negative values

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5443]
Hi,

Highcharts should reduce width of legend if legend has align:right and is shifted right. 

Right now it looks that sometimes legend has wrong width and when legend is shifted, some items may be outside the chart. 

Here you can find an example of this issue from StackOverflow topic:
https://jsfiddle.net/paLoxcy3/

I think that the problem is because of Legend.renderItem method:
https://github.com/highcharts/highcharts/blob/master/js/highcharts.src.js#L11533

Here you can find an example with possible workaround:
https://jsfiddle.net/paLoxcy3/2/

Best regards.

**Comment by iandickety** [comment]
+1. Thanks for helping me out on SO and saving me the time for filing this bug!

**Comment by jon-a-nygaard** [comment]
Thanks for reporting, we will fix this as soon as possible.

_Internal Note: [simplified demo](https://jsfiddle.net/paLoxcy3/3/)_
