### ISSUE TITLE
Swedish county "Örebro" is misspelled as "Orebro"

### ISSUE THREAD

**Issue by jimhau** [highcharts/highcharts#5445]
#### Expected behaviour

County name should be "Örebro"
#### Actual behaviour

County name is "Orebro"
#### Live demo with steps to reproduce

http://jsfiddle.net/f49ub5cp/
Hover county "Örebro", the label shows "Orebro"
#### Affected browser(s)

All

**Comment by oysteinmoseng** [comment]
Thank you for reporting, as Norwegians we should be able to get this right! The issue will be fixed in the next release of the map collection. If you need it fixed right away, you can edit the map files yourself using any text editor.

**Comment by jimhau** [comment]
Great! We only use the names for tooltips, so we did this:

```
var pointNameReplaceMents = [{
	oldName: "Orebro",
	newName: "Örebro"
}];
//and then:
pointFormatter: function () {
	var pointName = this.name;

	for (var i = 0; i < pointNameReplaceMents.length; i++)
		if (pointNameReplaceMents[i].oldName === pointName)
			return pointNameReplaceMents[i].newName;
	return pointName;
}
```

**Comment by KacperMadej** [comment]
Here's a demo with the map file updated (the problematic region has darker blue color): http://jsfiddle.net/BlackLabel/f49ub5cp/2/

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#7
