### ISSUE TITLE
Highstock: linked axis has wrong align for labels

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5449]
#### Expected behaviour

Labels on grid lines, inside plot area, because it's the same as with single axis:
http://jsfiddle.net/2cypn1m1/1/
#### Actual behaviour

Labels outside until any update on yAxis.
http://jsfiddle.net/2cypn1m1/2/
#### Live demo with steps to reproduce

http://jsfiddle.net/2cypn1m1/2/
1. Press the button under the chart
2. labels aligned as they should be, but they are not like that at the start
#### Workaround

Set labels settings:

```
    labels: {
      align: 'right',
      x: 0
    }
```

http://jsfiddle.net/2cypn1m1/3/

**Comment by pawelfus** [comment]
*Internal note:*

[This wrapper](https://github.com/highcharts/highcharts/blob/46fe6c373b1dc69fa78cff6bf887594a1d077c08/js/parts/StockChart.js#L144-L166) is responsible for the issue. It used to work in 2.1.6: http://jsfiddle.net/2cypn1m1/7/ (but the first example here is broken ;) http://jsfiddle.net/2cypn1m1/8/ ). After update, `panes[key]` -> `panes[undefined,undefined]` exists, so we don't go there. Shouldn't we clean up the `chart._labelPanes` array when destroying an axis? It may be tricky with current key (top+height is not enough to determine if property should be deleted).

**Comment by TorsteinHonsi** [comment]
> Shouldn't we clean up the chart._labelPanes array when destroying an axis?

Yes, probably.

**Comment by KacperMadej** [comment]
Working correctly since version 5.0.0
Demo: http://jsfiddle.net/2cypn1m1/9/
Possibly related issue: #6071
