### ISSUE TITLE
Custom id for highcharts container

### ISSUE THREAD

**Issue by bpote** [highcharts/highcharts#5450]
#### Expected behaviour

I should be able to specify the container ID some way whenever I render charts. Right now, it creates container as below:

``` html
<div class="highcharts-container" id="highcharts-8">
<!-- chart contents -->
</div>
```

It would be great if we would be able to specify this id via some configuration eg.

```
container: {id: "custom-id"}
```
#### Actual behaviour

Right now, I can not seem to control the `id` of the container.

I could not find any documentation so I assume this is not possible as of now.
#### My use case

Note: I need this in a react based SPA where I've one of the components which renders three different graphs in render():

```
<ReactHighStock config={this.state.config} />
<ReactHighStock config={this.state.config} />
<ReactHighmaps config={this.state.config} />
```

The issue is the last one(ReactHighmaps) almost always gets same ID for clip-path as the ID of the container of first ReactHighStock which I believe is because when the html is generated for each of them, they are independently generated but when they are actually rendered and `clip-path="url(#highcharts-8)">` is operated on later on. On the entire DOM, two elements would have `highcharts-8` as ID and the first one is used for clip-path. Alternative suggestions are welcome but ID would be good feature to have.

**Comment by Brightergy-BrishaPote** [comment]
I used a workaround which looks something like below:
```javascript
setContainerId(e) {
  $(this.container).attr('id', 'highcharts-series');
}
//...
chart: {
  events: {
    load: this.setContainerId
  }
}
```

**Comment by oysteinmoseng** [comment]
`clip-path` of one chart having the same ìd` as the container of another chart sounds like a bug. Are you able to reproduce this in a jsFiddle demo?

Apart from that I think it makes good sense to be able to specify a custom ìd`.
