### ISSUE TITLE
Bar chart Truncation issue

### ISSUE THREAD

**Issue by panickerr** [highcharts/highcharts#5452]
#### Expected behaviour
The text in the bar graph should split into two lines and shall display all the given characters in the label

#### Actual behaviour
The labels are getting truncated after a very less word limit and thus making the graph less user friendly.

#### Affected browser(s)
Firefox, chrome

Here as you can see there is enough space between the graphs for the second line to appear but sadly it doesnt.  Im not using any variables to restrict the length of the labels.
![truncation](https://cloud.githubusercontent.com/assets/11805862/16483658/01363602-3ed3-11e6-82e5-1af9c2db445f.PNG)

PS: i even tried using a label formatter but it did not work
`labelFormatter: function() {
                                        var words = this.name.split(/[\s]+/);
                                        var numWordsPerLine = 6;
                                        var str = [];

                                        for (var word in words) {
                                            if (word > 0 && word % numWordsPerLine == 0)
                                                str.push('<br>');

                                             str.push(words[word]);
                                        }

                                        return str.join(' ');
                                },`

**Comment by panickerr** [comment]
Hi @TorsteinHonsi ,
Please have a look into this fix as its causing a lot issues with my graphs.

**Comment by pawelfus** [comment]
Hi @panickerr 

Thank you for reporting the issue. Could you recreate the issue on jsFiddle? We will check this. Without live demo, it's hard to fix any issue. I tried to recreate this, but it works fine. Please take a look: http://jsfiddle.net/nau9rw4a/

**Comment by panickerr** [comment]
Hi @pawelfus ,
Thank you for responding to the query i had put up. I have recreated the code in the below fiddle but interestingly it is not getting truncated there. I really would like to know why its getting truncated in the version that i'm running. If you happen to know any previous issues related to this issue i would really appreciate if you let me know. 


http://jsfiddle.net/panickerr/6b07axq0/

**Comment by pawelfus** [comment]
Could you compare versions? Current version is 4.2.5 (your and mine fiddles use this version).

**Comment by panickerr** [comment]
I will check that and revert back tmrw. thanks @pawelfus

**Comment by panickerr** [comment]
@pawelfus  My version is  "version": "v4.2.3". The main concern that i have is that the other graphs( stacked graphs, multiple bar graphs, column graphs) are all showing the full legend name. Can you just find out if there was some bug in 4.2.3 which was fixed in 4.2.5 which was causing bar charts to render in this way .

**Comment by pawelfus** [comment]
There was a change how labels on xAxis (inverted chart) should behave, see demo with 4.2.3 version: http://jsfiddle.net/6b07axq0/5/

In the current release, labels are wrapped.

**Comment by panickerr** [comment]
Thanks a lot @pawelfus . This was one of the major issues i had. Now its working as i updated the whole highcharts to 4.2.5
