### ISSUE TITLE
HighStock - laggy first navigator dragging

### ISSUE THREAD

**Issue by vipera** [highcharts/highcharts#5453]
#### Expected behaviour
Dragging the navigator handles should be smooth when liveRedraw is not enabled.

#### Actual behaviour

I'm using the latest master of HighStock. When I disable the navigator scrollbar with `scrollbar: false` or disable liveRedraw, an initial drag of the navigator handles results in laggy behaviour (doesn't seem to be fixable by setting animation: false). Interestingly, after moving the bars even slightly, the drag behaviour works completely smoothly.

This seems to be related to #5395. I'm unsure whether that issue describes the same problem - in any case, this problem has persisted after that issue was closed.

#### Live demo with steps to reproduce

http://jsfiddle.net/68tgahbg/

Simply setting:
```javascript
scrollbar: {
  enabled: false,
  liveRedraw: false
}
```
or
```javascript
scrollbar: false
```
seems to be enough to trigger the problem.
#### Affected browser(s)

Firefox 47, Chromium 50, Chrome

Thanks for the help!

**Comment by TorsteinHonsi** [comment]
Another, probably related, issue is that dragging the scrollbar doesn't affect the navigator when `liveRedraw` is off. See http://jsfiddle.net/highcharts/68tgahbg/3/.
