### ISSUE TITLE
series.data is updated incorrectly after removing all points and adding a point

### ISSUE THREAD

**Issue by meduza777** [highcharts/highcharts#5454]
1. remove all points from serie one by one (no redraw) 
2. add a point to chart (no redraw)
#### Expected behaviour

after removing points i expect series[0].data.length to be 0 
after adding a point i expect series[0].data.length to be 1
#### Actual behaviour

after removing points series[0].data.length is 0 (as expected)
after adding a point series[0].data.length is still 0 
#### Live demo with steps to reproduce

https://jsfiddle.net/wya237o7/

series[0].data.length becomes 1 only after redrawing a chart. 
if i remove only one or several points, then after adding a point with chart.series[0].addPoint, series[0].data is updated with new point as expected

**Comment by pawelfus** [comment]
Thank you for reporting. 

> if i remove only one or several points, then after adding a point with chart.series[0].addPoint, series[0].data is updated with new point as expected

I have tried to reproduce the case you mentioned: https://jsfiddle.net/wya237o7/1/ - for me it always reports points **without** added points. Could you create an example for that case?

If you want to see, which points actually are in the series, use `series.options.data`, not `series.data`:  https://jsfiddle.net/wya237o7/2/

**Comment by oysteinmoseng** [comment]
Not sure if this is really a bug or if series.data is working as intended here? By design series.data should only contain visible points.
