### ISSUE TITLE
Incorrect flag placement in two-panel HighStock

### ISSUE THREAD

**Issue by luuuke** [highcharts/highcharts#5457]
#### Expected behaviour

Flag gets placed on the lower panel's column.
#### Actual behaviour

Flag is placed too high, i.e. in the upper panel. It seems like the Y position is calculated mostly correctly, only the height of the upper panel does not get considered.
#### Live demo with steps to reproduce

http://jsfiddle.net/q9n74L34/2/

**Comment by pawelfus** [comment]
Hi @luuuke 

Thank you for reporting the issue!

The problem is that `series<flag>.yAxis` is not specified. When setting `onSeries`, we don't copy reference to axes (but we should, I think). 

Simple solution is to synchronize `series<flag>.yAxis` and `series<column>.yAxis`: http://jsfiddle.net/q9n74L34/3/

**Comment by luuuke** [comment]
Thanks for the explanation! Totally makes sense now. 

I didn't quite catch that in the docs, most likely the reason being that "onSeries" immediately suggests that it gets drawn on that very series (and thereby using that series' yAxis). A small hint linking to the "yAxis"-option in the description could maybe clarify this.

**Comment by pawelfus** [comment]
I agree with you, let's keep this ticket open.

**Comment by jacknkandy** [comment]
@luuuke @pawelfus Same boat here. I had added my flag series, and set the "onSeries", made sure I set the correct IDs, but the flag series was still defaulting to the first series I double checked the documentation and I thought the same as @luuuke.

Now that I found this it makes sense, Cheers! +1 to a note in the docs.

**Comment by TorsteinHonsi** [comment]
Minimal demo with static data: http://jsfiddle.net/highcharts/q9n74L34/4/

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/q9n74L34/5/
