### ISSUE TITLE
Highcharts 5 with jQuery UI Resizable

### ISSUE THREAD

**Issue by tomascassidy** [highcharts/highcharts#5458]
I copied the demo from http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/members/chart-setsize-jquery-resizable/ and modified it to use Highcharts 5 js/css.

#### Expected behaviour
The chart should resize properly when resized to be larger than the original chart height.

#### Actual behaviour
The chart doesn't resize properly when resized to be larger than the original chart height.

#### Live demo with steps to reproduce
https://jsfiddle.net/c8avfdbc/3/

#### Affected browser(s)
Chromium 50.0.2661.102 Ubuntu 16.04 (64-bit)
Firefox 47.0 Ubuntu 16.04 (64-bit)

Is there a different recommended way to implement chart resizing with Highcharts 5?

**Comment by oysteinmoseng** [comment]
Thanks for reporting, we are still working on getting HC5 stable. Resizing should eventually work just as well as in HC4 out of the box, so this is to be considered a bug.
