### ISSUE TITLE
Highstock - synchronized tooltips on several charts

### ISSUE THREAD

**Issue by vipera** [highcharts/highcharts#5461]
I'm looking into synchronizing several Stock charts with the same tooltip/crosshair behaviour, using the latest Stockcharts master (445f2b74aff1f82b09fee0d9f37eda16aeace4be).

#### Expected behaviour
Tooltips and crosshairs synchronize on mouse move/drag over three Stock charts.

#### Actual behaviour

I get the following error in the console when hovering over a chart, and the tooltips don't work properly:

highstock.js:172: `Uncaught TypeError: Cannot read property 'category' of undefined`

#### Live demo with steps to reproduce
I based my code on the [official Highcharts synchronized charts demo](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/synchronized-charts/), which shows synchronization of three charts.

Including Highstock, adding 'StockChart' to the constructor and leaving most of the other code the same doesn't seem to be enough ([fiddle](http://jsfiddle.net/hh90ps4c/)).

It's possible I'm not doing something right, but I expected the options to remain the same. A solution is disabling shared tooltips (thereby skipping over that line) but I would like to keep shared tooltips because of my custom tooltip formatter.

Thanks :)

**Comment by pawelfus** [comment]
Hi @vipera 

This is caused by `tooltip.shared` option. In Highstock, by defaults `shared` is set to `true`, which means `tooltip.refresh()` should take an **array of points**, while in Highcharts, `shared` is set to `false`, so as an argument should be passed **only one point**. 

Here is fixed demo for you: http://jsfiddle.net/hh90ps4c/1/

**Comment by vipera** [comment]
Hi @pawelfus,

I wasn't aware of this difference. Passing an array of points to refresh will probably be the way to go then :)

Thanks for your time!

**Comment by michelde** [comment]
Hi @pawelfus ,

I'm on the same problem working. You fixed demo isn't working anymore. When trying to refresh the tooltip an error is thrown: Uncaught TypeError: Cannot read property 'category' of undefined.

Is this related to a new version of highstocks?

Cheers,
Michel

**Comment by pawelfus** [comment]
Hi @michelde 

You are right, this is related to the new version of Highstock. In Highstock v6 new option, `split`, was added and enabled by default. Disable it and we will get working demo: http://jsfiddle.net/BlackLabel/hh90ps4c/28/

**Comment by reimen3512** [comment]
Hi @michelde 
I#m working on a similar chart and try to work with highstock. But I can't see any chart on your demos.
Can you help?
Reiner

**Comment by raf18seb** [comment]
Hi @reimen3512,

Here is a working demo (updated data URL): https://jsfiddle.net/BlackLabel/mrx2t48c/
