### ISSUE TITLE
Uncaught TypeError: Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by maxnemo** [highcharts/highcharts#5462]
http://screenshot.ru/3743ea8b153b7385bcc31d6fda91de31.png
http://screenshot.ru/937ab864201ae0c08987d6d1b4044597.png
what is the error?

**Comment by tomascassidy** [comment]
Have you tried using the non-minified script files?  That will allow you to set breakpoints in the browser script debugger.

**Comment by pawelfus** [comment]
Hi @maxnemo 

Thank you for reporting. Could you recreate issue on jsFiddle? We will check the issue.

**Comment by jon-a-nygaard** [comment]
Closing this issue since we are unable to reproduce, and it is pending a reply. Should anyone have further information on the issue, please comment and reopen.
