### ISSUE TITLE
Hover marker flickers on shared tooltip, if remove points in one place and redraw in another

### ISSUE THREAD

**Issue by meduza777** [highcharts/highcharts#5465]
open demo, hover cursor over path - marker flickers - appears and then disappears
set tooltip shared to false - works as expected
#### Live demo with steps to reproduce

http://jsfiddle.net/6mr0ujdL/

**Comment by oysteinmoseng** [comment]
Thank you for reporting this. For some reason I was not able to reproduce it well with a [simplified example](http://jsfiddle.net/vf8Lezjc/).

**Comment by pawelfus** [comment]
@oysteinmoseng : demo fro you: http://jsfiddle.net/vf8Lezjc/1/ - this is caused by `series. stateMarkerGraphic`, which is generated on demand, when markers are disabled. In the original demo, markers are hidden, because of auto-disabling markers for high density of points.
