### ISSUE TITLE
Point markers from outside the displayed range are not animated correctly

### ISSUE THREAD

**Issue by ingokegel** [highcharts/highcharts#5466]
#### Expected behaviour

When the y-axis in a line chart is set to auto-scale, point markers that were previously outside the displayed range should be animated together with the line
#### Actual behaviour

The points are moved immediately to the new location and only the line is animated. Further changes in the scale of the y-axis show the correct behavior.
#### Live demo with steps to reproduce

http://jsfiddle.net/gL4jcs37/
Click on "Auto" to auto-scale the y-axis and show the wrong behavior.
Click on "Zoom" and then again on "Auto" to show that the second time it works correctly.
#### Affected browser(s)

Chrome, Firefox, ...

**Comment by oysteinmoseng** [comment]
Thank you for reporting. Presumably this happens because the markers have not been drawn before when you do the initial auto-scale, and so they are drawn directly in the new location.
