### ISSUE TITLE
Incorrect placement of data labels (with distance attribute) when pie is sliced

### ISSUE THREAD

**Issue by sgrg93** [highcharts/highcharts#5468]
#### Expected behaviour
The "distance" attribute of data labels should work correctly irrespective of whether the pie is sliced or not. 

#### Actual behaviour
If the pie is sliced, the data labels with "distance" attribute is not placed correctly

#### Live demo with steps to reproduce
http://jsfiddle.net/k94x958d/1/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @sgrg93,

Thank you for reporting the issue. This is already reported as #3267
