### ISSUE TITLE
3D chart resize issue

### ISSUE THREAD

**Issue by davit-abgaryan** [highcharts/highcharts#5469]
Resize browser window or parent of 3d chart
#### Expected behaviour
Keep it's view

#### Actual behaviour
Chart is devided by parts
Screenshot: http://i.imgur.com/AjmrWJb.png

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/3d-pie/

#### Affected browser(s)
Chrome is tested

**Comment by pawelfus** [comment]
Hi @davit-abgaryan 

Thank you for reporting the issue! It is already fixed on the master branch: http://jsfiddle.net/e1nvv0va/ and will be included in the next release.
