### ISSUE TITLE
Grid lines are missing if highstock.js is imported instead of highcharts.js when axis height is string

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#5470]
After doing some tests I noticed that the issue only happens when the axis height is set as string.

#### Expected behaviour
I'd expect same behavior with highstock.js as with highcharts.js

#### Actual behaviour
Grid lines are missing if highstock.js is imported

#### Live demo with steps to reproduce
Example with highcharts: http://jsfiddle.net/alvarezg/w4spc1yg/
Example with highstock: http://jsfiddle.net/alvarezg/rbx4rrdr/

**Comment by pawelfus** [comment]
Hi @alvarezguille 

Thank you for reporting the issue. I'm not convinced if this is a bug. According to the [API](http://api.highcharts.com/highstock#yAxis.height) - `height` should be Number for pixels or a String for percentage value (e.g. `"100%"`). I think this is a coincidence it works in Highcharts.

**Comment by alvarezguille** [comment]
Thanks for the answer @pawelfus !
I wasn't able to find yaxis `height` in [Highcharts API](http://api.highcharts.com/highcharts#yAxis), but now I can see it in Highstock API. I still somehow expected to find same coincidences and behavior in Highcharts and Highstock.
I will try to fix how how these properties are serialized to json on my side.
