### ISSUE TITLE
Zooming a small selection up to the edge, zooms both x and y when zoomtype = x

### ISSUE THREAD

**Issue by emergingdzns** [highcharts/highcharts#5471]
For more detailed explanation see the SO question: 
http://stackoverflow.com/questions/38229578/in-highcharts-zooming-a-small-selection-up-to-the-edge-zooms-both-x-and-y-when

#### Expected behaviour
With chart option zoomtype set to `x`...
When you have a series of data along a time based x axis but select a small portion near the edge of the chart (either end) that has one or two data points in the selection, the graph should zoom in on the x-axis spreading out the time range selected across the width of the graph.

#### Actual behaviour
Upon selecting the xaxis range of time (again a small area near the edge of the graph and extending up to the end of the graph) when it zooms, it zooms both x and y, so existing data points inside the selection often get moved outside of the visible graph range and the y gridlines also slide up and out indicating the the y axis is also zoomed as if only the bottom corner of the graph was selected.

#### Live demo with steps to reproduce
https://jsfiddle.net/emergingdzns/8dfuga09/

Simply run the demo and then select a small portion on the right side, just encompassing the last data point bubble. See the screenshots attached for an example.

![image](https://cloud.githubusercontent.com/assets/1018133/16629412/6c9c6c04-436a-11e6-99a5-08bf0b0dea1a.png)
![image](https://cloud.githubusercontent.com/assets/1018133/16629420/752255d2-436a-11e6-97f7-8897594d944c.png)

#### Affected browser(s)
All browsers I've tested in (Chrome, FF and Safari on Mac)

**Comment by pawelfus** [comment]
Hi @emergingdzns 

Thank you for reporting the issue. It is already fixed on our bugfix branch, please take a look: http://jsfiddle.net/0f0wfkva/

*Internal note:*
I think this issue is connected to #4592.
