### ISSUE TITLE
Pie Chart Data Labels "distance" attribute does not work properly for 3D pie 

### ISSUE THREAD

**Issue by sgrg93** [highcharts/highcharts#5474]
#### Expected behaviour
Distance attribute of data labels should work correctly for 3D pie and ring charts

#### Actual behaviour
The "distance" attribute does not work properly for 3D pie/ring charts. The labels overlap over one another.

#### Live demo with steps to reproduce
http://jsfiddle.net/vsj9ybg8/

#### Affected browser(s)
Chrome

**Comment by oysteinmoseng** [comment]
Thank you for reporting this. It seems like the position calculation just does not factor in the 3D angles properly, as with `alpha: 0` it looks fine.

**Comment by pawelfus** [comment]
Duplicate of #3259
