### ISSUE TITLE
Axis label ellipsis ignores align setting

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#5475]
#### Expected behaviour

The maximum length of axis labels that are aligned left can is always determined by the width of the  plotarea.
#### Actual behaviour

When marginLeft is set on the chart, the maximum length of axis labels is determined by marginLeft
#### Live demo with steps to reproduce

http://jsfiddle.net/u8uye96a/2/
#### Affected browser(s)

All browsers

**Comment by pawelfus** [comment]
Hi @kzoon 

Thank you for reporting. Have you tried to use `spacingLeft` as a workaround? Something like this: http://jsfiddle.net/u8uye96a/3/

**Comment by kzoon** [comment]
Good workaround. I didn't need the fixed left margin anyway, but I thought you might want to be alerted to this (slight) issue :-)

**Comment by pawelfus** [comment]
Of course, you are right! :) Thank you once again.

**Comment by kzoon** [comment]
This issue is actually solved
