### ISSUE TITLE
Crosshair - cannot read property plotX - Highstock

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5477]
#### Actual behaviour
Error: 
highstock.js:429 Uncaught TypeError: Cannot read property 'plotX' of undefined 

#### Live demo with steps to reproduce
http://jsfiddle.net/mobdd57s/

**Comment by pawelfus** [comment]
**Workaround:** 
Set `crosshair.snap` to false. It changes behaviour, though. Demo: http://jsfiddle.net/p1kjwqw8/
