### ISSUE TITLE
Highstock range selector buttons don't work when chart is async loaded and navigator is disabled

### ISSUE THREAD

**Issue by tuankiet65** [highcharts/highcharts#5478]
This is a duplicate of #3700 but as it is very old (over one year ago) I'm making a new one instead.
#### Expected behaviour

When a Highstock chart is async loaded, range selector buttons should work regardless of navigator settings (whether it's enabled or not)
#### Actual behaviour

When the navigator is disabled, clicking on range selector buttons cause them to grey out (disabled). The scroll bar below also doesn't work as expected.
#### Live demo with steps to reproduce

https://jsfiddle.net/7nnm2esq/3/
This is the same code as the Highchart async load example, the only difference is that I disabled the navigator. 

To reproduce: just click on the range selector buttons (any button would do, in my case click on 1h has immediate effect) and observe that the buttons are greyed out and the scroll bar doesn't work as expected

Video demonstrating the issue:
[Screencast from 07-12-2016 04:14:33 PM.webm.zip](https://github.com/highcharts/highcharts/files/358949/Screencast.from.07-12-2016.04.14.33.PM.webm.zip)
#### Affected browser(s)

Chromium 51.0.2704.106 (64 bit, Arch Linux)
Firefox 47.0.1 (64 bit, Arch Linux)

**Comment by oysteinmoseng** [comment]
Thank you for bringing the issue to light again, we'll take a look as soon as possible.

**Comment by tuankiet65** [comment]
May I have some news on this issue?

**Comment by TorsteinHonsi** [comment]
I think the problem is that if you disable the navigator, Highstock doesn't have any information about the available data range, so the `getUnionExtremes` function returns only the part that is loaded in the main view. You can see that in http://jsfiddle.net/highcharts/7nnm2esq/5/, and compare to what is logged in the console when you enable the navigator. 

When the navigator is enabled, the function always returns the min and max of the navigator data series.

A viable workaround may be to hide the navigator's graphic elements rather than disabling it, so that its logic can work in the background: http://jsfiddle.net/highcharts/7nnm2esq/6/

**Comment by tuankiet65** [comment]
That's a nice workaround I think, thanks for suggesting that.
A bit irrelevant, but is there a way to set the navigator's series after initialization? I prefer initializing the chart first with empty data, then showLoading() and load the data after that using setData() (so that the user would see the loading screen) rather than loading all the data first and then initialize the chart (the user wouldn't see anything before the data is loaded)

**Comment by oysteinmoseng** [comment]
@tuankiet65: If I understand you correctly, as long as [adaptToUpdatedData](http://api.highcharts.com/highstock#navigator.adaptToUpdatedData) is `true`(default), the navigator series will update to reflect the data you set on the base series.

**Comment by HMSteve** [comment]
Came accross the same issue today:  Buttons to zoom out becoming disabled when clicking a button to zoom in and the navigator is disabled. Is there an official solution/fix for the use case with range selector but no navigator? Thanks.

**Comment by pawelfus** [comment]
Hi @HMSteve 

There's no fix at this moment, only workaround posted above: https://github.com/highcharts/highcharts/issues/5478#issuecomment-237475028 :

> A viable workaround may be to hide the navigator's graphic elements rather than disabling it, so that its logic can work in the background: http://jsfiddle.net/highcharts/7nnm2esq/6/

**Comment by HMSteve** [comment]
Thanks, Pawel. To make it work for more than one series even if not all series are displayed, I had to add plotOptions.series.showInNavigator: true. 
For some reason I also had to set navigator.adaptToUpdatedData: true. Static data is loaded using csvURL.
