### ISSUE TITLE
Data Grouping not working for AreaSplineRange

### ISSUE THREAD

**Issue by ecegeek** [highcharts/highcharts#5479]
#### Expected behaviour

Data should be grouped as configured for area spline range series.
#### Actual behaviour

For area spline range series, the series is no longer rendered once the data is grouped.  Not seeing this issue for other series types.
#### Live demo with steps to reproduce

https://jsfiddle.net/ecegeek/jtosjrqy/
In the fiddle above, notice that the series isn't drawn in the chart (though the navigator does render just fine).  If you uncomment `enabled: false`, the series is rendered.  Its also not due to `force: true` because you can comment that out and resize the browser small enough for it to trigger grouping and the series will disappear.
#### Affected browser(s)

Reproduced with:
Chrome 51.0.2704.106
Firefox 47.0.1
Safari 8.0.7

**Comment by pawelfus** [comment]
Hi @ecegeek 

Thank you for contacting us. The problem is with `approximation: "average"` option ([API](http://api.highcharts.com/highstock#plotOptions.series.dataGrouping.approximation)). See working demo: https://jsfiddle.net/nLv974cm/ . 

`"average"` returns one-dimensional array (linear points), while `-range` types requires `high` and `low` values. That's the reason why Highcharts can not render `arearange` using that type of approximation.

**Comment by oysteinmoseng** [comment]
Should the `average` algorithm return 2 averages, one for `low` and one for `high` in range charts?

**Comment by pawelfus** [comment]
I think so, or at least this is what documentation suggests. `average` is a default value for line-types, but it doesn't say it works only for a line type series:

> Defaults to average for line-type series, sum for columns, range for range series and ohlc for OHLC and candlestick.

I guess the same issue we will have for `"sum"` approximation.

**Comment by ecegeek** [comment]
Thanks @pawelfus and @oysteinmoseng.  I'll switch to "range" approximation for now as a workaround.  Ideally, I'd like to be able to use "average" in the future, as I think range may be a bit misleading for the particular data I'm trying to show.

**Comment by pawelfus** [comment]
@ecegeek 
You can always create your own approximation, for example "average" for range series is that simple: https://jsfiddle.net/Lyf6vzev/

        series: [{
            type: 'areasplinerange',
            data: data,
            dataGrouping: {
                //enabled: false,
                forced: true,
                approximation: function (low, high) {
                	return [avg(low), avg(high)];
                },
                units: [
                    ['minute', [1, 2]],
                    ['hour', [1]],
                    ['day', [1]],
                    ['month', [1]]
                ]
            }
        }]

And `avg` method:

    function avg(arr) {
    	var sum =  arr.reduce(function (s, res) {
				return s + res;
			}, 0);
            
      return sum / arr.length;
    }

**Comment by ecegeek** [comment]
Perfect!  Thanks @pawelfus .

**Comment by envision** [comment]
Agreed, approximation setting 'average' should work with range series' or at least there should be an option for called 'rangeaverage' or 'averagerange' (a real killer name).

The current only option 'range' gives you the variation range which is much different data than the average range.

@pawelfus snippet works though!

**Comment by envision** [comment]
Actually on some cases with that snippet the array given to the avg function may have length 0, so here's tweaked version:

	function avg(arr) {
		if (arr.length === 0) { return null; }
		var sum =  arr.reduce(function (s, res) {
			return s + res;
		}, 0);
		return sum / arr.length;
	}

**Comment by KacperMadej** [comment]
The above commit @TorsteinHonsi , should you decide to accept it, should be reflected in the `docs` as it adds to the approximations array a new build in option - `averages` (same as the `average`, but for series with multiple y plot values). This option is also planned to be utilized by the technical indicators module.
