### ISSUE TITLE
minPadding not honoured when hitting "all" zoom

### ISSUE THREAD

**Issue by phpBBSEO** [highcharts/highcharts#548]
Using Highstock, hitting "all" in the zoom navigation should result in seeing what was first loaded in the following example :
http://jsfiddle.net/GtXUq/

minPadding seems assumed zero on full zoom. It would seems to me rager logical if minPadding would always be honoured when changing the zoom.

**Comment by TorsteinHonsi** [comment]
Still valid with Highstock v6.1.0. Set `xAxis.ordinal` to `false` to make it more clear: http://jsfiddle.net/highcharts/GtXUq/3/.
