### ISSUE TITLE
Show 0k in min value of solid gauge

### ISSUE THREAD

**Issue by carlososiel** [highcharts/highcharts#5480]
#### Expected behaviour
Show only the 0 value, not with k appended in the min value of graph

#### Actual behaviour
Show 0k in min value and not use k metrics for value when the max value % 100 != 0(example: 3880 for 3880) and when the % 100 is 0 show the value with correct metric(ex: 3.8k for 3800)

#### Live demo with steps to reproduce
http://jsfiddle.net/carlososiel/y3pvke9s/

#### Affected browser(s)
Chrome 51, Firefox 47

**Comment by pawelfus** [comment]
Hi @carlososiel 

You can use [`yAxis.labels.formatter`](http://api.highcharts.com/highcharts#xAxis.labels.formatter) to achieve what you need, please take a look: http://jsfiddle.net/cve6f69e/1/

Of course, you can apply your logic in the formatter (`if (this.axis.max % 100 !== 0) { ... } else { ... }`).

**Comment by carlososiel** [comment]
Hi @pawelfus, thanks for your answer, this is a way to solved this issue, but i think that is a bug the 0 value not should show k letter in min value

**Comment by pawelfus** [comment]
Let me reopen this ticket then, we will discuss this.

**Comment by TorsteinHonsi** [comment]
Agreed. Minimal example: http://jsfiddle.net/highcharts/7tajx4mj/
