### ISSUE TITLE
GeoJSON Transform object iteration error

### ISSUE THREAD

**Issue by shoaibmerchant** [highcharts/highcharts#5482]
Hi, apologies I skipped the issue template because it didnt make any sense for this issue.

I was trying to understand the longitude-latitude transformation for geojson where you have used proj4js and I found this glitch

I might have missed something but this for block
https://github.com/highcharts/highcharts/blob/25e4b0a7b2298faa9fc9c0b23eb95e46d4a9bd6e/lib/modules/map.src.js#L1337

should have been

``` js
for (transformKey in mapTransforms) {
       var transform = mapTransforms[transformKey];
    if (mapTransforms.hasOwnProperty(transformKey) && transform.rotation) {
          transform.cosAngle = Math.cos(transform.rotation);
          transform.sinAngle = Math.sin(transform.rotation);
       }
}
```

**Comment by oysteinmoseng** [comment]
Great catch, thanks for reporting!

**Comment by shoaibmerchant** [comment]
No problem :+1:
