### ISSUE TITLE
Wrong data on downloaded image after setCompare, no actual data visible

### ISSUE THREAD

**Issue by marcin3e** [highcharts/highcharts#5485]
#### Expected behaviour
After change "Set compare" to Percent
Download PNG image file with the currently visible graph (e.g percent on Axis)

#### Actual behaviour
Download PNG file without actual data (e.g no percent on Axis, line plot data not changed)

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/stock/members/axis-setcompare/

Steps:
1. Click on "Chart context menu"
2. Click on "Download PNG image" - ok data on graph image
3. Click on "Percent" in bottom section of "Set compare:"
4. Click on "Chart context menu"
5. Click on "Download PNG image" - incorrect data on graph image (the same image as point 2)

#### Affected browser(s)
Chrome, FireFox, IE

**Comment by oysteinmoseng** [comment]
@gvaartjes: Is the export server running an older version of Highcharts? There used to be a bug with this that we fixed.

**Comment by pawelfus** [comment]
**Workaround:**

After using `setCompare()`, store new comparison in `series.userOptions.compare` too. Demo: http://jsfiddle.net/4skj0fm8/

Snippet:

    $('button.compare').click(function() {
      var chart = $('#container').highcharts(),
          compare = $(this).data().compare;

      chart.yAxis[0].setCompare(compare);

      $.each(chart.yAxis[0].series, function(i, series) {
        series.userOptions.compare = compare;
      });
    });

**Comment by marcin3e** [comment]
@pawelfus Thank you very much, given the solution helped
