### ISSUE TITLE
Series threshold 'null' ignored when area chart contains only negative values.

### ISSUE THREAD

**Issue by nhitchins** [highcharts/highcharts#5486]
Series threshold value of 'null' is (sometimes) ignored when applying fill to an area chart for negative values.

Demo:
http://jsfiddle.net/t4tq4601/

Click the test button below the chart to change the series data. You'll notice the fill is being applied as if the threshold value was 0 instead of null.

**Comment by pawelfus** [comment]
Related issue: #4233 

@nhitchins - could you try the workaround posted by Kacper?

**Comment by oysteinmoseng** [comment]
Kacper's workaround seems to help: http://jsfiddle.net/t4tq4601/2/

**Comment by nhitchins** [comment]
Yes, the workaround does help for now. Thanks
