### ISSUE TITLE
Highcharts - rangeSelector 3M is not responding after selecting 7Y

### ISSUE THREAD

**Issue by Thilaga14** [highcharts/highcharts#5489]
#### Expected behaviour
3M should be clickable and see the results

#### Actual behaviour
3M is not responding

#### Live demo with steps to reproduce
http://jsfiddle.net/nhb1812d/2/

Steps to reproduce : 

- Click on 3M (working fine)
- Click on 7Y(working fine)
- Click on 3M (not working)

**Comment by oysteinmoseng** [comment]
Thank you for reporting. The range selector is definitely acting weird when dataGrouping is defined on the buttons, also seen in other scenarios.

http://jsfiddle.net/nhb1812d/4/ (click the 3M button)

**Comment by TorsteinHonsi** [comment]
It's a regression in v4.2.5, seems to be related to the #2266 refactoring.
