### ISSUE TITLE
Plotband borderColor

### ISSUE THREAD

**Issue by allanmacmillan4** [highcharts/highcharts#5490]
#### Expected behaviour
When setting a rgba() color for the plotBand.borderColor it would not ignore the alpha

#### Actual behaviour
The alpha is ignored and the rgb() color is drawn instead

#### Live demo with steps to reproduce
http://jsfiddle.net/2vmcktbo/

#### Affected browser(s)
Chrome & IE (I would assume other broswers too)

**Comment by pawelfus** [comment]
Hi @allanmacmillan4 

Thank you for reporting! I am not sure if this is a Highcharts bug, consider this example: http://jsfiddle.net/2vmcktbo/1/ - in SVG border is applied with stroke with alpha, but stroke is also part of the shape itself with fill property, which cause two colors overlap each other (stroke+fill).

**Comment by allanmacmillan4** [comment]
Very true, I hadn't realised this.  Thanks
