### ISSUE TITLE
Axis.getExtremes() return invalid dataMin value

### ISSUE THREAD

**Issue by kpau** [highcharts/highcharts#5493]
#### Live demo with steps to reproduce
http://jsfiddle.net/dot7ebrx/2/

Create chart with two series, legend and range selector.
The second series doesn't have data for the entire range, for which the first one has (e.g. the first has data for 01.01.2000 - 05.01.2000, the second has for 02.01.2000 - 04.01.2000).
Hide the first (longer) series using the legend. The selected range is changed, so only the second series are visible on the plot (we can also see that in the navigator).
Click 'All' from the range selector. The chart plot doesn't change, but the navigator is updated so the whole range is selected (including the first series).
Click getExtremes() button, which calls `chart.xAxis[0].getExtremes();` and prints the result in the console.
_Note: The demo generates random Y data on each run, but for every run I made the issue was reproduced._

#### Actual behaviour
dataMin equals 01.01.2000 - the start date for the first series (which are hidden).
dataMax equals 04.01.2000 - the end date for the second series (which are the only visible series).

#### Expected behaviour
Either one of the two:
- dataMin and dataMax equals 01.01.2000 and 05.01.2000 - the first and the last date from the first series (uses all series to calculate the min/max data).
- dataMin and dataMax equals 02.01.2000 and 04.01.2000 - the first and the last date from the second series (uses only the visible series to calculate the min/max data).

The current documentation of [Axis.getExtremes()](http://api.highcharts.com/highstock#Axis.getExtremes) doesn't specify which is the expected behavior, although in the other cases, it uses only the visible series to calculate min/max.

#### Affected browser(s)
OS: Windows 8.1 (64-bit)

Google Chrome 51.0.2704.103 m (64-bit)
Firefox Developer edition 49.0a2 (2016-07-12)
Internet Explorer 11.0.9600.18283

**Comment by pawelfus** [comment]
Hi @kpau, thank you for reporting! I agree, it's strange to get minimum from all series, and maximum from only visible series. This is most probably caused by `dataGrouping`, when disabled it works fine: http://jsfiddle.net/dot7ebrx/3/ (imho only visible series should return extremes).

*Internal note:*
Most probably, minimum is set [here](https://github.com/highcharts/highcharts/blob/445f2b74aff1f82b09fee0d9f37eda16aeace4be/js/parts/DataGrouping.js#L338) which cause the issue above.
