### ISSUE TITLE
Line chart not extending to both sides of chart

### ISSUE THREAD

**Issue by TSchnaars** [highcharts/highcharts#5494]
#### Expected behaviour
Line chart to reach both sides of the chart

#### Actual behaviour
<img width="910" alt="screen shot 2016-07-15 at 9 44 39 am" src="https://cloud.githubusercontent.com/assets/10532203/16877717/928d74e4-4a77-11e6-9604-797593722de4.png">

#### Live demo with steps to reproduce

This is a non-working example. Its not working because of my data set, but you can at least see the code I am working with.
http://jsfiddle.net/LLExL/6359/

#### Affected browser(s)
Chrome & FF

Thanks!

**Comment by oysteinmoseng** [comment]
Hi, this is expected behavior. Try setting `pointPlacement` to `on` to remove the padding: http://jsfiddle.net/LLExL/6364/.
