### ISSUE TITLE
Shared tooltips not showing all data all the time

### ISSUE THREAD

**Issue by rustedgrail** [highcharts/highcharts#5495]
#### Expected behaviour
The shared tooltip should show all the points for a given X

#### Actual behaviour
The clientX is very slightly off, so the equality comparison removes some of the data. This happens for some points on some graphs, but it happens consistently for those points and graphs.

kdpoints[i].clientX
711.1666666666667
kdpoint[1].clientX
711.16666666667
https://github.com/highcharts/highcharts/blob/master/js/highcharts.src.js#L10357

#### Related to
#4645

#### Live demo with steps to reproduce
https://jsfiddle.net/23a7Ls9n/3/

#### Affected browser(s)
Chrome, haven't checked any other browser

**Comment by rustedgrail** [comment]
We've seen that, for the categories we checked, kdpoints[i].plotX === kdpoints[1].plotX.

**Comment by pawelfus** [comment]
Hi @rustedgrail 

Thank you for reporting the issue! Interesting fact (or a **workaround**): if you remove `pointPlacement: 0.0` it works fine: https://jsfiddle.net/23a7Ls9n/8/

*Internal note:*
Minimized example: https://jsfiddle.net/n81k7ee5/
