### ISSUE TITLE
Pyramid locate issue

### ISSUE THREAD

**Issue by scottszb1987** [highcharts/highcharts#5500]
#### Expected behaviour
With
```
series[].center = ["25%", "-25%"];
...
plotOptions.series.width = "50%";
plotOptions.series.height = "50%;
```
The pyramid should be placed at the bottom left of the plotting area, with datalabels displayed correctly.

#### Actual behaviour
The datalabels isn't following the pyramid well with the position changing.
With `series[].center = ["25%", "-25%"];`, the pyramid is placed correctly, but the datalabels are not displayed at all.

#### Live demo with steps to reproduce
https://jsfiddle.net/scottszb1987/z3wqLft2/

#### Affected browser(s)
Chrome

**Comment by oysteinmoseng** [comment]
Thanks for reporting. Possible workaround: set dataLabels `distance: 0`. https://jsfiddle.net/z3wqLft2/1/
