### ISSUE TITLE
setExtremes not working when having multiple series with big data differences

### ISSUE THREAD

**Issue by trpriel** [highcharts/highcharts#5501]
#### Expected behaviour
When having 2 series that have values that are significantly different (one in the hundreds and one in the millions). When using setExtremes with a small number for the minimum (in the added example 300). I expect that now the Y-Axis will start at 300 and cover the first series that does not have a value over 300. 

#### Actual behaviour
Nothing happens. You only see change when putting a bigger number in the setExtremes (11111100000 in the added example)

#### Live demo with steps to reproduce
Example with setExtremes that does not work (press the setExtrems button): [http://jsfiddle.net/62rb4g93/](url)
Example with setExtremes that does work (press the setExtrems button): [http://jsfiddle.net/g1x4zp81/](url)

#### Affected browser(s)
Tested on Chrome version 51

**Comment by oysteinmoseng** [comment]
Hi, when `axis.startOnTick` and `axis.endOnTick` are true, the extremes are rounded off to the nearest tick. See the API [here](http://api.highcharts.com/highcharts#Axis.setExtremes). Without these options, the first series will be covered: http://jsfiddle.net/62rb4g93/1/.

**Comment by trpriel** [comment]
@oysteinmoseng in your example the series is still not covered (you can see it on the bottom) and only the markers are gone.

**Comment by oysteinmoseng** [comment]
@trpriel Yes, you would have to set minimum high enough to cover the thickness of the line. Example: http://jsfiddle.net/62rb4g93/2/.

I think this makes sense, but we can reopen this as an enhancement and discuss it if you think this is unexpected behavior?
