### ISSUE TITLE
Legend doesn't show at pie type of chart

### ISSUE THREAD

**Issue by chalexIAC** [highcharts/highcharts#5502]
#### Expected behaviour
use:
legend: {enabled: true}

should be legend

#### Actual behaviour
legend doesn't appear

#### Live demo with steps to reproduce
http://jsfiddle.net/m8htxvpp/
#### Affected browser(s)

chrome

**Comment by pawelfus** [comment]
Hi @chalexIAC 

Thank you for reporting. However, this is not a but, since Highcharts 2.1, pie charts are disabled in a legend by [`pie.showInLegend`](http://api.highcharts.com/highcharts#plotOptions.pie.showInLegend) option.

**Comment by chalexIAC** [comment]
oh yeah! sorry!

**Comment by pawelfus** [comment]
Not a problem!
