### ISSUE TITLE
Override dataLabels.formatter not working

### ISSUE THREAD

**Issue by Taxman972** [highcharts/highcharts#5503]
Hi,

According to the api : "Options for all series in a chart are given in the plotOptions.series object. Then options for all series of a specific type are given in the plotOptions of that type"

But it's not working with `dataLabels.formatter`.

Here a fiddle http://jsfiddle.net/1wy3z9k0/

Tested on Firefox 46 and Chrome

**Comment by pawelfus** [comment]
Hi @Taxman972 

Thank you for reporting the issue. This is known issue with priority between `plotOptions.series` and `plotOptions.[series-type]`. See #3881.
