### ISSUE TITLE
Download Image in https in Firefox latest broken

### ISSUE THREAD

**Issue by josephzidell** [highcharts/highcharts#5504]
When using https, the download image functionality isn't working. https://jsfiddle.net/highcharts/llexl/
#### Expected behaviour
The image or pdf downloads.

#### Actual behaviour
In my application, using v3.0.9, we're getting a Security Warning http://imgur.com/qCCnzEs
Using your standard jsFiddle with the latest master, nothing happens.

#### Live demo with steps to reproduce
* Visit https://jsfiddle.net/highcharts/llexl/
* Try to download the chart in any format.

#### Affected browser(s)
Firefox 47.0.1 Windows 10

#### My fix
My proposed fix is to change `url:"http://export.highcharts.com/"` to `url:"//export.highcharts.com/"` in js/modules/exporting.js

**Comment by jon-a-nygaard** [comment]
@josephzidell Thanks for reporting. While waiting for the maintenance release, which will contain a fix for this issue, you can set the option [exporting.url](http://api.highcharts.com/highcharts#exporting.url) to your desired url, like in [this example](https://jsfiddle.net/LLExL/6366/)

**Comment by josephzidell** [comment]
Thanks for the quick response. We'll use the workaround for now.

**Comment by jon-a-nygaard** [comment]
Reopening the issue, since the fix has not yet been merged into the master branch. :smile:
