### ISSUE TITLE
Issue for gauge MAX value

### ISSUE THREAD

**Issue by daekss** [highcharts/highcharts#5505]
Hi Guys,

I'm facing an odd behaviour when i try to put the MAX value for the gauge options. In the most of cases the max value doesn't display at the correct place. To fix that, i need to try a lot of numbers untill one fix the position.

I'm talking about this max value:
yAxis: {
            min: 0,
            max: 7000,
            title: {
                text: ''
            }
        }
![gauge](https://cloud.githubusercontent.com/assets/15525025/16927112/4d7229ee-4d02-11e6-8535-7df349432187.png)

I have attached the imagem with my problem. Am I doing something wrong ? My value Max will be a dynamic number, so i can't just put a number that fix this problem. 

Thank you!

**Comment by jon-a-nygaard** [comment]
@daekss What you can do is to set your own custom [yAxis.tickPositioner](http://api.highcharts.com/highcharts#yAxis.tickPositioner) which returns two tick positions, the min and max value of the yAxis. I believe what you are looking for is a solution like in [this example] (http://jsfiddle.net/3w9gtcxy/1/)

**Comment by daekss** [comment]
@jon-a-nygaard thank you man! that worked!
