### ISSUE TITLE
Datalabels misplacing on 3D bar chart.

### ISSUE THREAD

**Issue by shangzb87** [highcharts/highcharts#5508]
#### Expected behaviour

When dataLabels.enabled is set to true, the dataLabels should be displayed properly.
#### Actual behaviour

The dataLabels are displayed incorrectly.
#### Live demo with steps to reproduce

https://jsfiddle.net/scottszb1987/n603jpt4/
#### Affected browser(s)

Chrome

**Comment by jon-a-nygaard** [comment]
@scottszb1987 Thanks for reporting. We will try to fix this as soon as possible.

Most likely related to #4160.

_Internal Note: It seems that an [inverted 3D-column uses a different positioning algorithm](https://jsfiddle.net/n603jpt4/1/), which positions the data labels even more wrong. They should probably use the same algorithm._

**Comment by Izothep** [comment]
+1

**Comment by darbelaez** [comment]
Hi - any updates on when we can expect a fix for this issue? thanks!

![3d](https://user-images.githubusercontent.com/6105269/47456023-66405a00-d7a1-11e8-9411-bd81d4497210.PNG)

**Comment by KacperMadej** [comment]
_Internal note:_ Planned for version 7 as https://github.com/highcharts/highcharts/blob/762c6f2d87fea4442b4c9a116ce6dbff669a0a47/js/parts-3d/Column.js#L343-L350

**Comment by jon-a-nygaard** [comment]
I changed the label from bug to enhancement, since 3D bar series is not officially supported in Highcharts.
