### ISSUE TITLE
xAxis title overlap with yAxis title

### ISSUE THREAD

**Issue by ipip2005** [highcharts/highcharts#5510]
#### Expected behaviour

limitted, or better, cut the text and suffix with '...'
#### Actual behaviour

titles overlapped, and cannot see the begin or end of the text.
#### Live demo with steps to reproduce

http://jsfiddle.net/fvfh05zw/
#### Affected browser(s)

all

**Comment by pawelfus** [comment]
Hi @ipip2005,

Thank you for reaching us. However, I'm not sure what do you mean, please take a look:
![screen shot 2016-07-20 at 10 25 38](https://cloud.githubusercontent.com/assets/1453926/16979993/560ccbe6-4e64-11e6-933a-80e034f9fe49.png)

This is know chart is rendered in Chrome (osx).

**Comment by ipip2005** [comment]
Sorry about that, I just updated the link, the previous link is not saved.

**Comment by ipip2005** [comment]
![image](https://cloud.githubusercontent.com/assets/7711735/17014415/16fc4bf4-4f57-11e6-8eff-4fb44e5853d0.png)
This the chart which I suppose has issue

**Comment by TorsteinHonsi** [comment]
We can probably just add the length of the axis as the width of the text [after the text is generated](https://github.com/highcharts/highcharts/blob/v4.2.5/js/parts/Axis.js#L1896). Potential problems are breaks in the title or different rotation. 

See the drop-in fix here: http://jsfiddle.net/fvfh05zw/1/

**Comment by ipip2005** [comment]
Could you check out this? http://jsfiddle.net/fvfh05zw/4/
useHTML: true is critical for us because of encoding requirements

**Comment by TorsteinHonsi** [comment]
It looks like the width isn't applied unless there is a space inside. So you can append a space: http://jsfiddle.net/highcharts/fvfh05zw/5/

**Comment by ipip2005** [comment]
This looks good. But if I decrease the chart width, and increase the width back to origin, the issue happened again.

**Comment by ipip2005** [comment]
Here decrease and increase should be done by manually stretching the frame

**Comment by TorsteinHonsi** [comment]
Looks like it expands and contracts every second time. Strange...
