### ISSUE TITLE
Highcharts Stock - RangeSelector results are not consistent - 3M showing 5 months data

### ISSUE THREAD

**Issue by Thilaga14** [highcharts/highcharts#5512]
#### Expected behaviour
range selector results should be consistent

#### Actual behaviour
range selector results are not consistent

#### Live demo with steps to reproduce
http://jsfiddle.net/cyjs868p/3/ - Working fine (3M shows 4 months data. Apr - Jul which is normal)
http://jsfiddle.net/cyjs868p/2/ - Not working properly (Issue 3M shows 5 months data. Mar - Jul)

**Comment by pawelfus** [comment]
Hi @Thilaga14 

This is caused by [`minRange`](http://api.highcharts.com/highcharts#xAxis.minRange). You can change that value, for example to two weeks, demo: http://jsfiddle.net/cyjs868p/5/

**Comment by Thilaga14** [comment]
Yes. It is working now. Thanks
