### ISSUE TITLE
Map Collection - Telangana missing from the India Maps

### ISSUE THREAD

**Issue by andrewr88** [highcharts/highcharts#5514]
#### Expected behaviour

Telangana should be present on the India Maps

#### Actual behaviour

Telangana is not present

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/in/in-all
http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/in/custom/in-all-andaman-and-nicobar
http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/in/custom/in-all-disputed

#### Affected browser(s)

All

**Comment by oysteinmoseng** [comment]
Closed as duplicate of #3277.
