### ISSUE TITLE
Axis tickInterval ignored when creating dual axis chart

### ISSUE THREAD

**Issue by lionel87** [highcharts/highcharts#5515]
#### Expected behaviour
In the jsfiddle demo, the Y axis should be drawn with 20 unit tick interval. (first example)

#### Actual behaviour
The Y axes are drawn with an automatically calculated 80 and 160 unit tick interval. (first example)
If you link the axis, the tick interval will work on the first one, but the second one is still incorrect. In this case the `max` property also ignored. (second example)

#### Live demo with steps to reproduce
http://jsfiddle.net/cs0z6gas/
http://jsfiddle.net/cs0z6gas/1/ (with linked axis)

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Thanks for reporting. This is the consequence of the alignTick option being true by default. See http://jsfiddle.net/cs0z6gas/2/.

I have added this information to the documentation of `tickInterval`.
