### ISSUE TITLE
Stacking percent in Bar chart

### ISSUE THREAD

**Issue by panickerr** [highcharts/highcharts#5516]
#### Expected behaviour
If the max is 100 and the value if 60 then i need the 60 to be in a particular color and rest 40 to be in a different color.
![high](https://cloud.githubusercontent.com/assets/11805862/17015279/eaca8772-4f46-11e6-9d71-d5c30dce427d.PNG)

#### Actual behaviour
When i give stacking:percent then im not getting the result

**Comment by pawelfus** [comment]
Hi @panickerr 

Percentage [`bar.stacking`](http://api.highcharts.com/highcharts#plotOptions.bar.stacking) works as described in the [docs](http://www.highcharts.com/docs/advanced-chart-features/stacking-charts). In your case, I suggest to use two series: one with original values, and second one with values to sum up to 100, for example: http://jsfiddle.net/L87cogck/
