### ISSUE TITLE
Tooltip hover and pointPlacement "between" - strange hover boundaries on chart

### ISSUE THREAD

**Issue by ry8806** [highcharts/highcharts#5518]
#### Expected behaviour
Setting up a chart with shared tooltip, 2 types of series (both with point placement = "between"). When hovering over the data points will show you the correct tooltip for the point on the xAxis.

#### Actual behaviour
When hovering on the middle of the data point, the correct tooltip is shown. However, moving the mouse to the right, still within the same data point, shows the next series' (to the right) tooltip information.

#### Live demo with steps to reproduce
Demo: http://jsfiddle.net/scpupcLr/
Steps to reproduce - hover over a bar and move the mouse from one side of the bar to the other

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Simplified demo: http://jsfiddle.net/highcharts/scpupcLr/2/

We would expect the points for the same X value to display in the same tooltip regardless of `pointPlacement`.

**Comment by TorsteinHonsi** [comment]
By setting the pointPlacement to between and xAxis.tickmarkPlacement to "on" you effectively move all the points and axis markers a half unit to the right, and the tooltip tracking doesn't adjust. Are you sure you're not looking for a [regular category setup](http://jsfiddle.net/highcharts/scpupcLr/3/)?

**Comment by ry8806** [comment]
@TorsteinHonsi Unfortunately not, in my real chart (not the simplified example above) each tick represents the start/end of a year, we are using the "between" pointPlacement to show monetary values for that year (as the value spans the whole 12 months - and is not just a value at a point in time e.g. start/end of the year).

I would have expected the tooltip tracking to adjust in this case, by the half a unit you quoted above.

**Comment by jon-a-nygaard** [comment]
Related issue #5383

**Comment by colgreen** [comment]
FYI I've submitted a fix pull request, here:

https://github.com/highcharts/highcharts/pull/5601
