### ISSUE TITLE
Cuboid animation is broken when faces get visible/hidden due to angle

### ISSUE THREAD

**Issue by paulo-raca** [highcharts/highcharts#5521]
#### Expected behaviour

During an animation, each face should become visible when I reach an angle < 90º and should morph nicely to it's final perspective
#### Actual behaviour

If I transition from "looking from the left" to "Looking from the right", the left facet morphs into the right one (looks weird)

If I transition from "looking from center" to "Looking from the right", the right face appears without animation 
#### Live demo with steps to reproduce

Both issues are visible clicking "rotate" on this fiddle
http://jsfiddle.net/paulo_raca/79sx038h/

**Comment by TorsteinHonsi** [comment]
It's the same with the top faces too.

**Comment by pawelfus** [comment]
It's caused by using only three faces in the [cuboid](https://github.com/highcharts/highcharts/blob/v4.2.5/js/parts-3d/SVGRenderer.js#L88-L90). These shapes are animated into the new positions. I guess implementing all other faces is a way to go?
