### ISSUE TITLE
On a 3D chart, the first call to chart.redraw() changes the size of the chart

### ISSUE THREAD

**Issue by paulo-raca** [highcharts/highcharts#5522]
#### Expected behaviour
Chart remais the same size after redraw

#### Actual behaviour
The chart change size (A bit) after redraw() is called for the first time

#### Live demo with steps to reproduce
http://jsfiddle.net/paulo_raca/2xbjmcov/

Apparently this issue doesn't happen with `fitToPlot: false`

**Comment by TorsteinHonsi** [comment]
@pawelfus Any idea?

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi On first render when the [getMargin is run the plotLeft, plotRight, plotTop, plotBottom is different](https://github.com/highcharts/highcharts/blob/master/js/parts-3d/Chart.js#L22-L25) from in the redraw, causing a different calculated value of `scale3d`. [The scale is later used in the perspective method](https://github.com/highcharts/highcharts/blob/master/js/parts-3d/Math.js#L94-L96) which scales down the all coordinates to fit into the plotting area,

**Comment by TorsteinHonsi** [comment]
Okay it's probably because the labels aren't rendered yet then, so we don't know the exact size of the plot area.

**Comment by paulo-raca** [comment]
Thanks!
