### ISSUE TITLE
marker radius with string value 

### ISSUE THREAD

**Issue by cbaket** [highcharts/highcharts#5523]
#### Expected behaviour
Throw an error or work correctly

#### Actual behaviour
If you set the marker radius as a string, it does not work correctly.
Works, but has too big marker when the mouse is on a point

#### Live demo with steps to reproduce
http://jsfiddle.net/cbaket/920vydfr/ 

#### Affected browser(s)
all

**Comment by jon-a-nygaard** [comment]
Thanks for reporting, in the upcoming maintenance release `radius` and `radiusPlus` will be converted to numbers before calculation to ensure correct outcome.
