### ISSUE TITLE
Area with missing points (nulls) are filled, if series is on 2nd YAxis

### ISSUE THREAD

**Issue by tregoning** [highcharts/highcharts#5524]
#### Expected behaviour

Nulls in an area chart should _not_ be filled like in here:
http://jsfiddle.net/5hf1bvpe/
#### Actual behaviour

But if said series is on the 2nd yAxis (and there is a series in the 1st yAxis) nulls are filled:
http://jsfiddle.net/g14b5693/
#### Live demo with steps to reproduce

http://jsfiddle.net/g14b5693/
#### Affected browser(s)

All

**Comment by jon-a-nygaard** [comment]
Commit which broke this functionality: https://github.com/highcharts/highcharts/commit/9e74c8c85fe9dd59b941d1ccc28d9d62e75ac3a2
