### ISSUE TITLE
Pie chart looks not good for all zero data

### ISSUE THREAD

**Issue by ipip2005** [highcharts/highcharts#5526]
Hi, we levarage pie chart with authoring experience. So if user make all the values empty, it will looks weird. I mean, not so pro.
#### Expected behaviour

We haven't figured out yet. But probably rendering all zero data like they are equal positive like this:
![image](https://cloud.githubusercontent.com/assets/7711735/17092073/7a476586-5272-11e6-8b8f-21e96ddcd6f5.png)
or an empty circle, means there is no usable data.
It's just weird for me to have no circle in pie chart.
#### Actual behaviour

![image](https://cloud.githubusercontent.com/assets/7711735/17092049/48f95d54-5272-11e6-8459-f5f9670c9c04.png)
#### Live demo with steps to reproduce

http://jsfiddle.net/highcharts/Qgn59/
#### Affected browser(s)

all

**Comment by TorsteinHonsi** [comment]
If we changed it it would have to be optional at least. Many existing users would regard the equal positives a bug. The current display is correct in the sense that the data labels and connectors are there, since 0 is actually a value. In contrast to a pie with [all nulls](http://jsfiddle.net/highcharts/Qgn59/9/). 

Another way of dealing with this could be to add a circle to indicate the outline of the pie when empty: http://jsfiddle.net/highcharts/Qgn59/10/

**Comment by jon-a-nygaard** [comment]
Closing this issue since we consider it not a bug, and it is pending a reply. Should anyone have further information on the issue, please give us a comment.

**Comment by ipip2005** [comment]
It's cool we have such workaround. But it needs overwriting the prototype function,
To not confuse in-production users, maybe we can add this as an option in pie chart.
For example: `showPlaceholderForEmptyPie`? Than the default value will be `false`. In my case, I will set it to true.

**Comment by dhruv-m-patel** [comment]
Maybe not a really great solution, but I am using a donut chart and did this trick:

```
let nonzeroDataPoints = dataPoints;
const dataPointsSum = _.sumBy(dataPoints, data => data.y); // data is an array of datapoints here with y values maybe set to all zeros
if (dataPointsSum === 0) {
   nonzeroDataPoints = [{ y: 1, color: '#DDDDDD', name: 'foo' }];
   tooltip.pointFormat = '<tr><td> 0 </td></tr>';
}

Highcharts.chart('container', {
  chart: {
    ...
    type: 'pie',
    ...
  },
  series: {
    ...
    data: nonzeroDataPoints
    ...
  }
})
```

Works for me as it renders charts as expected to keep it consistent. This required me to also modify tooltip a little bit to show zeros when tooltip appears.

**Comment by wxu-aa** [comment]
Could we support this feature as optional? I think it's a wide requirement from many users ^^

...Well I'm just too lazy to do some hacking code in my production😂

But I still hope we can support this feature soon 🍻

**Comment by TorsteinHonsi** [comment]
It has meen merged into the master now, will be part of the next release. See http://jsfiddle.net/highcharts/vqrxhwc3/

**Comment by jychiao** [comment]
Is there a way to turn this feature off with API options?

**Comment by pawelfus** [comment]
It should be possible to change color to transparent, according to API: https://api.highcharts.com/highcharts/series.pie.color but seems to be broken: https://jsfiddle.net/BlackLabel/rxkLspbg/

Alternative is to set `borderWidth: 0`, but that will render 1px slices in the middle: https://jsfiddle.net/BlackLabel/rxkLspbg/1/

Workaround:
Manually change the color. 
Demo: https://jsfiddle.net/BlackLabel/rxkLspbg/2/
Snippet: 
```js
  chart: {
    events: {
      render: function() {
        this.series.forEach(
          s =>
            s.options.type === 'pie' &&
            s.graph &&
            s.graph.attr({
              stroke: 'transparent'
            })
        );
      }
    }
  },
```

Created ticket for that issue: #13672 - thanks for pointing this out @jychiao !
