### ISSUE TITLE
Polar chart and arearange series not working

### ISSUE THREAD

**Issue by killzoner** [highcharts/highcharts#5528]
Hi,

I was trying to make polar chart and arearange series working together. I couldn't get anything good until i found this issue : https://github.com/highcharts/highcharts/issues/3419, marked as solved.

The example seems not to be working anymore : http://jsfiddle.net/highcharts/30q95we5/1/

![capture](https://cloud.githubusercontent.com/assets/3322938/17094917/4b0334dc-5252-11e6-9615-815a8a1f3ccf.PNG)

Playing with versions, i saw that it's broken since v4.2.2 (here is the working version in v4.2.1 : http://jsfiddle.net/fchj8yr6/)

![capture2](https://cloud.githubusercontent.com/assets/3322938/17094925/55159bc2-5252-11e6-81c8-684c89cd74b5.PNG)

Thanks for the great work

**Comment by ManYang** [comment]
I take a look at the code a little with comparison of fixed version. The is something I found may help for the fix.
First, for the seriesTypes.arearange class, in the getGraphPath function, there is pointShim obj, if we comment out highAreaPoints.push(pointShim); and highPoints.push(pointShim); the mess is disappear and draw the inner layer of the graph, looks like:
<img width="419" alt="screen shot 2016-08-02 at 1 01 58 pm" src="https://cloud.githubusercontent.com/assets/2164458/17337594/66b360e8-58b1-11e6-8db1-81a9693f795f.png">

Second,the linePath = [].concat(lowerPath, higherPath) looks like just get the bottom line,  higherPath come from highPoints but in the class there is no function assign value to highpoint, looks the highpoint come from somewhere else.

**Comment by TorsteinHonsi** [comment]
Thanks for your inputs!

**Comment by TorsteinHonsi** [comment]
Related: #3419. 

It broke with the great null-stack refactoring.

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/30q95we5/3/

**Comment by killzoner** [comment]
Well done, thanks!
