### ISSUE TITLE
X Axis tick not rendered in case time axis and units configured and single tick

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#5529]
#### Expected behaviour

X Axis tick should get render in all cases
#### Actual behaviour

Observeation is, When  we set x axis type as datetime , unit is set to create interval of 7 days and if we have only one tick.  X axis tick is not rendered.
#### Live demo with steps to reproduce

http://jsfiddle.net/460nbwxg/1/
#### Affected browser(s)

All

**Comment by pawanvjadhav** [comment]
I tried to set units as below , still it is not working:
"units": [
        ["week", [1]],
        ["month", [1, 3, 6]],
        ["year", null]
      ]

But if i set units as below, it is working:
"units": [
        ["day",[1,7]],
        ["week", [1]],
        ["month", [1, 3, 6]],
        ["year", null]
      ]


I want to show data weekly, why should i set day in units?

**Comment by salunkenagesh14** [comment]
As per the documentation

the definition of unit is specified as

> Units: Array
Datetime axis only. An array determining what time intervals the ticks are allowed to fall on. Each array item is an array where the first value is the time unit and the second value another array of **allowed multiples**

When allowed multiples are specified and the tick do not match allowed multiples, I feel the current implementation is doing good over here.

**Now how this can be considered :**
There are multiple ways to solve this

1) Allowing a special case for single tick
>  Which eventually makes a wrong behavior for users not expecting a tick because it's not a multiple of given unit.

2) Adding a property for ignoring units if you have only single data/Or some custom case and want to anyway show it.
> This case makes sure existing behavior is intact for other users.
 I hope this can be achieved by adding a custom condition  [here](https://github.com/highcharts/highcharts/blob/master/js/highcharts.src.js#L9519)
We can reset the multiples accordingly to default.

**Comment by pawanvjadhav** [comment]
Actually highchart is generating tick label.
Check svg element of axis.
I think, x coordinates are not calculated for this case.

**Comment by pawanvjadhav** [comment]
X coordinated not calculated properly for  text element. Thats what i feel

**Comment by pawanvjadhav** [comment]
@KacperMadej  : Copy pasted your reply below :
The issue is the same as the one you have submitted. Please see the info provided by another github user. You are forcing tick in a position outside of the visible x axis range through units option of the axis settings.

Another solution, other than the mentioned info in the github issue, is to use tickPositioner and provide custom array of ticks - it might be based on this.tickPositions array that has 'info' property used for datetime.

API reference for more info and a demo: http://api.highcharts.com/highcharts#xAxis.tickPositioner

Kind Regards,
Kacper Madej
