### ISSUE TITLE
Publish Highcharts 5 Alpha on npm

### ISSUE THREAD

**Issue by borisyankov** [highcharts/highcharts#5530]
Please, publish Highcharts 5 Alpha on npm.
When it is Alpha/Beta/RC it can both exist to be tried out and latest update will not update to it.

I am in dire need of all the improvements added, and am willing to test and provide feedback.

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi Perhaps we could publish one tagged as `v5.0.0-alpha` or something?
