### ISSUE TITLE
dataLabel didn't show in spline chart

### ISSUE THREAD

**Issue by yeluoqiuzhi** [highcharts/highcharts#5532]
#### Expected behaviour

highcharts should show dataLabels in spline chart

#### Actual behaviour

highcharts didn't show dataLabels in spline chart

#### Live demo with steps to reproduce

<http://jsfiddle.net/yeluoqiuzhi/uLdsvtgL/2/>

**Comment by TorsteinHonsi** [comment]
You enabled data labels for `plotOptions.line`, but not for `plotOptions.spline`. If you want them to appear for all series types, you can use `plotOptions.series`: http://jsfiddle.net/highcharts/uLdsvtgL/3/
