### ISSUE TITLE
highlight wrong series when hovering one of lines in multiple line chart

### ISSUE THREAD

**Issue by amanda7783** [highcharts/highcharts#5533]
http://jsfiddle.net/gr4uygj7/
![image](https://cloud.githubusercontent.com/assets/9457743/17128804/e8bac2d6-5341-11e6-9f2d-f9084b029b4f.png
![image](https://cloud.githubusercontent.com/assets/9457743/17128858/25d00780-5342-11e6-9ef5-3d6f5daa7d8b.png)

when i move mouse on the below section of  "mapr" series  , the "supply chain" series will be highlighted which is not focus correct

and my customers always ask me to fix this kind of issue, so can you guys help on this?

**Comment by TorsteinHonsi** [comment]
Highcharts overlays invisible tracker objects in order for the mouse to highlight the graph even if it's not directly on it. You can [see that here](http://jsfiddle.net/highcharts/gr4uygj7/2/).

You can make it more distinct by setting a lower [tooltip.snap](http://api.highcharts.com/highcharts#tooltip.snap) option, [for example to 3](http://api.highcharts.com/highcharts#tooltip.snap). Will that resolve your problem?

**Comment by sbuendia** [comment]
tooltip.snap doesn't solve the issue. Regardless of the tooltip.snap option, the issue is that hovering over a particular line (serie) it triggers the highlighting and tooltip on a different line (serie).

**Comment by pawelfus** [comment]
*Internal note:* Fails since d228fa0

**Comment by TorsteinHonsi** [comment]
Ah... So it actually triggers the closest point. But it seems counter-intuitive that it happens right when we enter the tracker of another series.

**Comment by pawelfus** [comment]
It looks like, we can observe x-value in this demo: http://jsfiddle.net/39dye84d/
