### ISSUE TITLE
Highcharts convert: data labels duplicated

### ISSUE THREAD

**Issue by iannewson** [highcharts/highcharts#5537]
When using Highcharts-convert to render a pie chart, the data labels are becoming duplicated. This only happens when rendering using PhantomJS; it's fine in the browser.

Here's a link to a JSFiddle which works correctly:

https://jsfiddle.net/j2nb72L7/1/

Here's an image which shows the problem with the rendered output from PhantomJS:

https://drive.google.com/a/xibis.com/file/d/0B-mqMIMqm_XHWGRTNmQ1RGZPTGc/view?usp=sharing

I'm using highcharts v4.2.5, highcharts convert v3.0.1 and PhantomJS v1.9.7.

**Comment by iannewson** [comment]
This issue appears to have been fixed by upgrading PhantomJS to v2.1

**Comment by TorsteinHonsi** [comment]
> This issue appears to have been fixed by upgrading PhantomJS to v2.1

Thanks!

**Comment by TorsteinHonsi** [comment]
@gvaartjes Maybe upgrading PhantomJS to v2.1 also resolves the HTML scaling issue?

**Comment by gvaartjes** [comment]
@TorsteinHonsi @havardge Yes we'll test this next week.

**Comment by gvaartjes** [comment]
referencing issue #5393, this issue is also waiting on phantomjs 2.1
