### ISSUE TITLE
pieChart: generated shadow goes to wrong position.

### ISSUE THREAD

**Issue by fengyue1013** [highcharts/highcharts#5538]
When pie chart title is set to the empty string and mouse is hovered to the chart, the generated shadow goes to wrong position (goes upper to my observation).

#### Live demo with steps to reproduce
http://jsfiddle.net/ub5e92ua/1/

1. At the initial state, hover the mouse to the chart, the generated shadow is in the right position.
2. Click Botton "Empty the Title, Then Shadows Are Broken", again hover the mouse to the chart, the generated shadow goes to a upper position.
3. Click Botton "Set the Title, Then Shadows Work Well", the shadow is right.

**Comment by TorsteinHonsi** [comment]
Simplified demo: http://jsfiddle.net/highcharts/ub5e92ua/3/

I believe the root cause/issue is that the pie is not redrawn when the plot box resizes.

**Comment by fengyue1013** [comment]
Thank you very much. 
The bug is fixed with your help
