### ISSUE TITLE
Stockchart with live updated data render bug

### ISSUE THREAD

**Issue by polyclick** [highcharts/highcharts#5539]
#### Expected behaviour
When you have a spline chart that gets updated using (external) live data and you drag the navigator away from its original starting position (ie: in de middle of the navigator bar), the chart has a weird rendering bug.

#### Live demo with steps to reproduce
http://jsfiddle.net/qs46kqz6/
-> make sure you drag the navigator to a position somewhere in the middle and watch the graph do weird stuff ;)

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Duplicate of #5294.
