### ISSUE TITLE
Tooltip not appearing on polygon when there's a flag series

### ISSUE THREAD

**Issue by sersou83** [highcharts/highcharts#5540]
#### Expected behaviour
Tooltip should appear on every series (unless you strictly define it not to)

#### Actual behaviour
When you add a flag series to the chart where you have a polygon the tooltip for the polygon stops showing. It seems to me that even the polygon itself stop to be recognized, because if you add an event listner to the polygin (let's say click) it is not triggered after you add a flag series

#### Live demo with steps to reproduce
http://jsfiddle.net/sL377du8/2/

In this example the tooltip and the click event are not triggered, but if you remove the flage series (http://jsfiddle.net/sL377du8/3/) then everything works perfect.

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Fixed in the master branch, see http://jsfiddle.net/highcharts/sL377du8/4/.

The fix will be released next week with v4.2.6.
