### ISSUE TITLE
Problems with pointIntervalUnit: day, gapSize: 1 and useUTC: false over days with time switch

### ISSUE THREAD

**Issue by luuuke** [highcharts/highcharts#5541]
#### Prerequisites
`useUTC: false` set for HighStock.
(+ being in a timezone with time switches; I am in CET while testing this, change to daylight savings time is at 27.3.16, 2:00 → 3:00)

#### Description
When using `pointIntervalUnit: 'day'` + `pointInterval: 1` (1) the graph is drawn the same way like for 
`pointIntervalUnit: undefined` + `pointInterval: 24*60*60*1000` (2) (except for an hour lag for switches to e.g. daylight saving time). 
But when introducing `gapSize: 1` the graph with `pointIntervalUnit: 'day'` (3) will be *very* short and only span over the day with the time switch to the next day. The one with `pointIntervalUnit: undefined` (4) will be fine. This only happens when a time switch is in the visible area.
A workaround to avoid this can be achieved by using e.g. `gapSize: 1 + 1/24 + 0.01` if the time switch differences are only ± 1 hour.

![Image of problem](https://cloud.githubusercontent.com/assets/4431868/17173366/c1fe9f78-53fa-11e6-887b-003f57a768fc.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/1kyfr3bf/

**Comment by TorsteinHonsi** [comment]
Actually, [gapSize](http://api.highcharts.com/highstock#plotOptions.series.gapSize) works like it is described in this case.

A gapSize of 1 means that for any points which distance is greater than the two closest pair of points, a gap is inserted. 

In this case, the distance between the two closest points is 23 hours, at the point of the DST crossover. Which causes all other 24h days to become gaps. If you want missing days to show as gaps, you should probably set `gapSize` to something like 1.5: http://jsfiddle.net/highcharts/1kyfr3bf/4/

**Comment by luuuke** [comment]
Makes sense, thanks for answering. 
In my opinion a day with a DST crossover should be treated equally to a usual day, it lacks an hour, but that shouldn't change anything, as a graph with `pointIntervalUnit: day` (seemingly) doesn't care about hours. On the other hand it's pretty much an edge case and can be easily alleviated by changing `gapSize` to something slightly bigger than the maximum ratio of "hours on a usual day" to "hours on a crossover day".

Just wanted to quickly bring this up and read your reasoning on this topic, I hope I didn't come off as pedantic.
