### ISSUE TITLE
[q] is there any option that turns off repeating of items in legend when pagination is on?

### ISSUE THREAD

**Issue by ZuBB** [highcharts/highcharts#5542]
See following screens (I made it based on next demo http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/legend/navigation/)

![2016-07-27-140308_3840x1080_scrot](https://cloud.githubusercontent.com/assets/597016/17173406/5e7900ac-5403-11e6-88f5-ecf0f57d8d6d.png)

![2016-07-27-140300_3840x1080_scrot](https://cloud.githubusercontent.com/assets/597016/17173407/5e7a1ff0-5403-11e6-8a83-cc3c8b8635f0.png)

item **Johan** is present for both pages. I understand that is was done intentionally to keep context but would be nice to have option to turn it off

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi What do you think? It seems that this should not be too difficult to implement, just an option to tell if `handleOverflow` should use `y` or `lastY`

**Comment by TorsteinHonsi** [comment]
> I understand that is was done intentionally to keep context but would be nice to have option to turn it off

Actually I think it works this way because `Jóhan´s` bounding box is clipped off (we don't see it because it is cut below the baseline).
