### ISSUE TITLE
Highcharts show "No data to display" after I set extremes out of my chart data range

### ISSUE THREAD

**Issue by nitoloz** [highcharts/highcharts#5543]
#### Expected behaviour
The chart should be empty without any message after I set extremes out of my chart data range, because there is still some data present.

#### Actual behaviour
I have multiples line chart that have same x range(union of all x ranges), but have data in different x ranges and when I zoom some of them it turns out that others have the data zoomed out. As far as I am using setExtrees for x axis zooming I apply it to the chart every time I zoom and it there is no data in the current zoom interval chart displays "No data to display", while there is some data out of the zoomed interval. 

#### Affected browser(s)
Chrome

Probably there is some workaround or it is a bug that No data to display is shown on a line chart after zooming?
**NOTE**: I am using no-data-to-display plugin.
**UPD**:
After some investigation I have found that no data message is displayed if the following function return true:
`
        hasData: function () {
            return this.hasVisibleSeries || (defined(this.min) && defined(this.max) && !!this.tickPositions);
        },`

According to this function it seems to be correct that in case all data is zoomed out no data message is displayed, but I don't think this feature is a common one, is it?

**Comment by nitoloz** [comment]
By the way setting extremes for Y axis does not ives the same result - "No data to display" message is not displayed, so it looks like an X axis bug.

**Comment by nitoloz** [comment]
@TorsteinHonsi could you please clarify the issue mentioned above?
Unfortunately I am not able to reproduce it in [jsfiddle](http://jsfiddle.net/0gr20drc/1/), because calling setExtremes with 4 parameters(min, max,  redraw, animation) does not work, however I am able to call it within my application. I use typescript and typings provided by [definetelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/highcharts), where interface with 4 parameters is defined.
Do you know what may cause an appearance of "No data to display" message after calling setExtremes with 4 parameters?

**Comment by TorsteinHonsi** [comment]
Can you look into that @oysteinmoseng ?

**Comment by nitoloz** [comment]
UPDATE @TorsteinHonsi @oysteinmoseng 
I have updated jsfiddle, so now one of charts shows "No data to display" after I zoom in using setExtremes function.
Please find  [UPDATED JSFIDDLE](http://jsfiddle.net/0gr20drc/2/) 

I believe it is an error and chart should not show "No data to display" if teh data was zoomed out, because it has data to display, but it is currently invisible.

**Comment by oysteinmoseng** [comment]
This is by design, but you can circumvent the behavior by adding the following code:
```
Highcharts.Series.prototype.hasData = function () {
  return this.visible && !!this.points.length;
}
```
[Example](http://jsfiddle.net/0gr20drc/4/)

**Comment by nitoloz** [comment]
Thank you @oysteinmoseng for the provided example!
Unfortunately I am using typescript with [typings](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/highcharts) and there is no Series property in Highcharts object.
Is it probably possible to overwrite hasData method using chart configuration?

**Comment by oysteinmoseng** [comment]
@nitoloz Unfortunately not, but I guess you could modify the no-data-to-display.js file directly and load your own version of it.

**Comment by nitoloz** [comment]
@oysteinmoseng, thank you, I will hopefully use this approach
