### ISSUE TITLE
Disable heatmap legend

### ISSUE THREAD

**Issue by PrimozGodec** [highcharts/highcharts#5544]
This is maybe not issue, but I can not find the way how to solve it. 

#### Expected behaviour

I have chart with heatmap and scatter. I want to hide legend from heatmap (color gradient legend), but I want to keep legend for scatter.

#### Actual behaviour

I can not find way to do this the only way I found is to hide whole legend. 

#### Live demo with steps to reproduce

http://jsfiddle.net/9mL8x9bc/2/
This demo contains booth in the legend, but I want to keep only legend for series 1

#### Affected browser(s)

Any

**Comment by jon-a-nygaard** [comment]
@PrimozGodec Currently it is not possible to hide only the colorAxis. You will have to eiter disable the legend altogether or show the colorAxis.

@TorsteinHonsi We should probably add an option `colorAxis.showInLegend` or what do you think?

**Comment by PrimozGodec** [comment]
Thanks it would be nice make that option. :) 

For others who will try to find solution for that, currently I am using solution from this discussion http://stackoverflow.com/questions/38634998/highcharts-remove-only-legend-for-coloraxis-keep-legend-for-series?noredirect=1#comment64659491_38634998

**Comment by TorsteinHonsi** [comment]
Adding a new option, `showInLegend`, is a good and consistent solution I think. Will you take care of it @jon-a-nygaard ?

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi Yes, I will create a suggestion.
