### ISSUE TITLE
How to unhide Plotline label on mouseover?

### ISSUE THREAD

**Issue by leongaban** [highcharts/highcharts#5545]
#### Expected behaviour
When mousing over plotline, event fires and changes the styling of the text label to `display:block` which should show the label.

#### Actual behaviour
When mousing over plotline, event fires and the styling does change on the `this` object, yet the label is still hidden.

#### Live demo with steps to reproduce
http://jsfiddle.net/leongaban/n36y336z/21/

Related stackoverflow: http://stackoverflow.com/questions/38616712/how-to-hide-highchart-plotline-label-until-mouseover

`
  $(function() {
      var $report = $('#report');

      $('#container').highcharts({
        xAxis: {
          plotLines: [{ // mark the weekend
            color: 'rgba(254,235,236,0.5)',
            from: Date.UTC(2010, 0, 2),
            to: Date.UTC(2010, 0, 3),
            zIndex: 1,
            label: {
            		useHTML: true,
                text: '<div class="targetLabel"><span>Event</span><br/><span style="font-weight: bold; padding-top: 5px;">' + '75' + '</span></div>',
                align: 'center',
              //text: 'Event',
              //align: 'left',
              style: {
              	display: 'none',
                color: '#000'
              }
            },
            events: {
              click: function(e) {
                console.log('clicked event')
              },
              mouseover: function(e) {
                console.log('hovering over plotline', this)
                this.label.styles.display = 'block';
                //this.options.label.display = 'block';
                this.options.label.style.display = 'block';
                console.log(' display:',this)
              },
              mouseout: function(e) {

              }
            }
          }],
          tickInterval: 24 * 3600 * 1000,
          // one day
          type: 'datetime'
        },

        series: [{
          data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4],
          pointStart: Date.UTC(2010, 0, 1),
          pointInterval: 24 * 3600 * 1000
        }]
      });
    });
`

#### Affected browser(s)
All

**Comment by jon-a-nygaard** [comment]
@leongaban You should use [Element.css](http://api.highcharts.com/highcharts#Element.css) to update style properties dynamically.
As an example; setting display block on your label can be done like this:
```javascript
this.label.css({
    display: 'block'
});
```

**Comment by leongaban** [comment]
Was answered on stackoverflow!
