### ISSUE TITLE
Weird behavior of legend when map and heatmap included. 

### ISSUE THREAD

**Issue by PrimozGodec** [highcharts/highcharts#5546]
#### Expected behaviour

Legend with no extra space. 

#### Actual behaviour

Legend has weird behavior when booth heatmap and map included. In case from jsfiddle legend has slider what is usual for too high legends in other case legend has too much extra space on top. 

#### Live demo with steps to reproduce
![screenshot from 2016-07-27 18-54-31](https://cloud.githubusercontent.com/assets/6421558/17184281/afcd40bc-542b-11e6-9728-71bd3e851cbb.png)

http://jsfiddle.net/9mL8x9bc/3/

#### Affected browser(s)

Any

**Comment by PrimozGodec** [comment]
It seems that booth map and heatmap generates the legend and this is the reason for the empty space on the top. 
Dose map.js contains all features that heatmap.js contains? Then we can remove heatmap, but I am not sure in that. In my example map.js has everything but I am not the only one using it as a part of our project.

**Comment by jon-a-nygaard** [comment]
@PrimozGodec Yes, `map.js` contains the complete functionality of `heatmap.js` and loading both of them is not advised. Removing `heatmap.js` from your project is what you should do.

**Comment by PrimozGodec** [comment]
Thank for your response. :)
