### ISSUE TITLE
Highstock spline series with null values draws null as zero when transitioning between null and value

### ISSUE THREAD

**Issue by envision** [highcharts/highcharts#5547]
This is a chart which is updated in 10s intervals for adding new datapoints which are at about 2s intervals.

Here is a time span that has only null values for the green and blue lines. Strangely only the blue line exhibits buggy behavior (green line has higher zIndex)... So that when real values are updated, the line is drawn from zero to the new value. 

![zeroval](https://cloud.githubusercontent.com/assets/1790545/17186538/5a0bb6c8-543e-11e6-85ab-e9c4117e2e4d.jpg)

Here is dataset which has first null values and the first real values (format: ts, green, blue, orange):

    [[1469642289,null,null,18],[1469642291,null,null,19],[1469642293,null,null,25],[1469642295,56,6,20],[1469642297,56,6,23]]

I'm having same behavior when real values are dropped to nulls again.

connectNulls parameter is false.

**Comment by envision** [comment]
Version 2.2.5 / 4.2.5.

**Comment by jon-a-nygaard** [comment]
@envision Hi, I am not able to reproduce your issue from the description, could you provide us with a live demo? [JSFiddle](https://jsfiddle.net/) is great for this purpose.

**Comment by envision** [comment]
Made a demonstration and then found out there was one Math.round() done also on null values, which returns 0.

I didn't notice this because those consecutive 0's was not drawn all the way... That is weird, that seems like a bug? It's not apparent on the previous screenshot but here is a new one:

![noalltheway](https://cloud.githubusercontent.com/assets/1790545/17419973/bd3b0ec2-5aa8-11e6-8f59-bb2541a47c94.jpg)

However I couldn't replicate that issue...tried here https://jsfiddle.net/envisio/fvgct21a/1/

**Comment by jon-a-nygaard** [comment]
@envision Sorry, but without a replication there is not much I can do. From the look of your images it seems that you should double check that your data is correct.

> Made a demonstration and then found out there was one Math.round() done also on null values, which returns 0.

Are you reffering to your own code or Highcharts? In case this is happening in the Highcharts code, could you tell me where it is located?

**Comment by envision** [comment]
@jon-a-nygaard yes I understand, I couldn't replicate it but data seems fine.

My earlier mistake was with my own code, there was erroneously rounding for decimal value which was also null at time. It was only for that blue series. But I didn't notice it earlier because the line behaved weirdly. As you can see from the latest picture the blue zero line isn't there for the whole length. Though it is possible it was caused by something I had missed.

Am closing this ticket, sorry for wasting our time!

**Comment by jon-a-nygaard** [comment]
@envision No need to apologize, too bad I could not help you with this. Let me know if you should find out some more. :smile:
