### ISSUE TITLE
Highstock panning with pointPlacement on break xAxis range

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5549]
#### Expected behaviour

When set range and pointPlacement on/between during moving the chart range should be constant.
#### Actual behaviour

Setting pointPlacement on/between breaks set range and makes the range smaller.
It works fine with pointPlacement null
#### Live demo with steps to reproduce

https://jsfiddle.net/9ceg37y5/2/
Move the chart to the left/right

Edit: Behavior when pointPlacement between is set is also incorrect.

**Comment by Nickesh** [comment]
The same applies to Highcharts.

With `pointPlacement: 'on'` panning also causes zooming.
Example: http://jsfiddle.net/3otx15e6/

Using `pointPlacement: 'between'` turn off panning completely.
Example: http://jsfiddle.net/a7nf5ys0/

**Comment by Nickesh** [comment]
Update: I've just checked current behavior. Using `on` or `between` always causes panning to the right edge of the data range.

Are there any chances for a fix?

**Comment by pawelfus** [comment]
Hi @Nickesh 

Thank you for the details. It looks like `on` and `between` are broken, but the same values as numbers (0, and 0.5) works fine, demos: http://jsfiddle.net/BlackLabel/a7nf5ys0/1/ and http://jsfiddle.net/BlackLabel/a7nf5ys0/2/

It looks like somewhere we are missing translation `on` -> 0, and `between` -> 0.5.
