### ISSUE TITLE
Change color dynamically

### ISSUE THREAD

**Issue by lgBatista** [highcharts/highcharts#5550]
#### Expected behaviour
On click a slice of a pie chart, change the actual color to another color declared on the item

#### Actual behaviour
The color changes but when mouse leave the slice it back to initial color and when the mouse enter on ir again the color appears

#### Live demo with steps to reproduce
https://jsfiddle.net/mtkyL82a/

#### Affected browser(s)
Tested on chrome 51.0.2704.103 and firefox 47.0.1

**Comment by ManYang** [comment]
I modified your code a little and it works now. [https://jsfiddle.net/yanlingyin/mtkyL82a/1/](url)

**Comment by jon-a-nygaard** [comment]
@lgBatista The solution from @ManYang is correct, but you can also make it a [little shorter](https://jsfiddle.net/jon_a_nygaard/mtkyL82a/3/).
