### ISSUE TITLE
stickyTracking / trackByArea doesn't work when the tooltip has already appeared

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5553]
#### Expected behaviour
With disabled stickyTracking and trackByArea options for an area chart, the tooltip fires when the point is hovered.

#### Actual behaviour
Expected behaviour occurs when the tooltip has not been fired yet. If the tooltip is shown and the cursor is moving around the area then it causes that the tooltip jumps around the points.

#### Live demo with steps to reproduce
http://jsfiddle.net/z50ypuos/
Move the cursor inside the area - the tooltip doesn't show up unless the point is close.
Move the cursor inside the area when the tooltip is already shown up - the tooltip fires even when the point is "not close". It seems that tracking area is much bigger in this case.

**Comment by TorsteinHonsi** [comment]
The bug is that the tooltip doesn't hide if we leave the graph on to the area. It only hides if we leave the graph to the other side.

**Comment by pawelfus** [comment]
*Internal note:*
Test was added accidentally in 683370a10986de4a1a339bcd6e7ee986f065b6a3 commit.

**Comment by pawelfus** [comment]
@TorsteinHonsi I am open if you have an idea for a test. I can test `onTrackerMouseOut` method with a fake event, but it doesn't really make sense..
