### ISSUE TITLE
Incorrect bar chart row heights on initial display

### ISSUE THREAD

**Issue by max0x7ba** [highcharts/highcharts#5554]
I have a bar chart with categories on X axis.
There are three data series, two of them are stacked.
I would like to have each bar row to be of exactly the same height.
What happens is that when the chart is first displayed the heights of the first and the last bar rows are incorrect, see the picture.
After I click any of the legend labels to hide/show series the heights of the row become correct.
Why does it not display bar rows of correct height when first displayed please?
#### Expected behaviour

Each bar row to be of exactly the same height.
#### Actual behaviour

When the chart is first displayed the heights of the first and the last bar rows are incorrect, see the picture:

![wrong-xticks](https://cloud.githubusercontent.com/assets/765202/17303331/256dfd94-5818-11e6-8455-a6b67624b12d.png)
#### Live demo with steps to reproduce

Here is the chart options I use:

``` javascript
    {
        chart: {
            plotBackgroundColor: '#202020',
            type: 'bar',
            height: rowGroup.length * 14,
            spacingBottom: 0,
            spacingTop: 0,
            spacingLeft: 0,
            spacingRight: 0
        },
        plotOptions: {
            bar: {
                borderWidth: 0
            }
        },
        title: {
            text: null
        },
        subtitle: {
            text: null
        },
        xAxis: {
            gridLineWidth: 0,
            alternateGridColor: 'black',
            tickPositions: series.labels.map((value, valueIdx) => valueIdx),
            tickPosition: 'inside',
            startOnTick: true,
            endOnTick: true,
            categories: series.labels,
            labels: {
                enabled: false
            },
            title: {
                text: null
            }
        },
        yAxis: {
            gridLineWidth: 0,
            labels: {
                enabled: false
            },
            title: {
                text: null
            }
        },
        series: [
            {
                name: 'Position',
                color: 'Gold',
                id: 'positions',
                data: series.positions
            },
            {
                stack: 'open',
                stacking: 'normal',
                name: 'Open Buy',
                color: 'rgba(255,160,122,.5)',
                id: 'openBuys',
                data: series.openBuys
            },
            {
                stack: 'open',
                stacking: 'normal',
                name: 'Open Sell',
                color: 'rgba(173,216,230,.5)',
                id: 'openSells',
                data: series.openSells
            }
        ],
        tooltip: {
            shared: true
        },
        legend: {
            floating: true,
            verticalAlign: 'top',
            align: 'right',
            itemStyle: {
                color: 'gray'
            }
        }
    }
```
#### Affected browser(s)

Google Chrome for Linux, Chrome/52.0.2743.82.

**Comment by TorsteinHonsi** [comment]
Thanks for writing. Your image doesn't show, but this is what I got after trying to reproduce: http://jsfiddle.net/highcharts/oe0b17dp/1/. Can you share more information to make it reproduce?

**Comment by max0x7ba** [comment]
Hi @TorsteinHonsi,

I managed to reproduced it: https://jsfiddle.net/max0x7ba/ez3u6o2g/

The size of the chart is correct, 28px. There are two bar rows, each must be of height 14.

The first tick ends at y=3, the second tick starts at y=3 and ends at y=25. 

Whereas I expect the first tick to start at y=0 and end at y=13 and the second one start at 14 and end on y=27.

**Comment by pawelfus** [comment]
*Workaround:*
Setting `xAxis.height` resolved the issue: https://jsfiddle.net/yxnepgxj/

**Comment by max0x7ba** [comment]
@pawelfus It does fix it nicely, thank you.

**Comment by TorsteinHonsi** [comment]
Further simplification: https://jsfiddle.net/highcharts/ez3u6o2g/4/

Also, removing `xAxis.endOnTick` (or setting it to false) fixes the problem. In fact, using `endOnTick` with a category axis shouldn't be necessary, as it will always show full categories. Am I wrong @max0x7ba ?

**Comment by max0x7ba** [comment]
@TorsteinHonsi 

Your example still exhibits the issue: the bar heights are not equal.

I have removed `xAxis.endOnTick` and `xAxis.startOnTick` and the issue still persists  https://jsfiddle.net/max0x7ba/jj2nof4j/ 

(I originally only added these option to try to work around the issue).

**Comment by TorsteinHonsi** [comment]
In what browser do you see that? I can't see it in your latest fiddle or in https://jsfiddle.net/highcharts/a6spaeo4/1/ (default colors).

**Comment by max0x7ba** [comment]
@TorsteinHonsi I use Google Chrome 52 on Fedora 22.

Full agent string: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36

**Comment by igaidai4uk** [comment]
I have similar case, initially the chart is rendered like this:

<img width="939" alt="screenshot 2017-01-26 00 33 29" src="https://cloud.githubusercontent.com/assets/2185483/22313928/5eaf434c-e35f-11e6-90e0-a174aa0397b2.png">

But as soon as I interact with navigator, it updates all the bars correctly.

**Comment by TorsteinHonsi** [comment]
Live demo @igaidai4uk ?
