### ISSUE TITLE
Data point click event breaks after zoom on a mobile (touch screen)

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5555]
#### Behaviour

If click event is set in a point data object, then after a zoom on a touch screen the click event is not being fired.
#### Live demo with steps to reproduce

http://jsfiddle.net/jhhe9g6c/3/
0. Run on mobile / touch screen
1. Click top point => alert
2. Zoom into top point
3. Click top point => no alert
4. Zoom out using the button
5. Click top point => no alert

If click event for point on series level is set then all is working fine.
http://jsfiddle.net/jhhe9g6c/2/
#### Affected browser(s)

Tested on Chrome on Android 6.0

**Comment by sebastianbochan** [comment]
Workaround:
   - use customEvents plugin: http://jsfiddle.net/115p9svm/

**Comment by vlsg** [comment]
Another work-around is to put the event at the series->point level, which is what KacperMadej helped me to do, but it took several days of hunting around and finally working with Kacper to figure out why it wasn't working and what I could do to fix it, so the fact that the bug there is all did cause some problems.  I hope if someone stumbles upon this bug report, it might save someone additional hastle by applying either Sebastian's workaround or just setting the event function on series -> point.

**Comment by TorsteinHonsi** [comment]
@KacperMadej I suspect it may have to do with the [feature that avoids scrolling](https://github.com/highcharts/highcharts/blob/v4.2.6/js/parts/TouchPointer.js#L114-L116) the chart until we have touched with two fingers (to prevent capturing finger scrolling in long pages). Can you check that?

**Comment by KacperMadej** [comment]
@TorsteinHonsi I have disabled that if-check and event is fired, but zooming using two finders (pinch) zooms into web page and zooms into a chart. Demo: http://jsfiddle.net/ssptbLja/

**Comment by sebastianbochan** [comment]
It looks like and issue also in the drilldown module.

Example:
  - http://jsfiddle.net/uk6jw5jm/

Steps:
1) pinch
2) reset zoom
3) click on column, drilldown is not triggered

Looks like workaround with wrapping pinch function, does not work properly.

Example:
   - http://jsfiddle.net/zybye2bL/

**Comment by sebastianbochan** [comment]
+1

**Comment by gatapia** [comment]
+1 drilldown does not work after zooming. see: http://jsfiddle.net/jerLxmuc/ which is a copy of the current columns with drilldown demo with zoomType: 'y'

**Comment by KacperMadej** [comment]
@gatapia Please provide steps required to recreate the problem. I am able to drill down after a zoom in the demo you have provided.
