### ISSUE TITLE
Error on Highstock version 4.2.6

### ISSUE THREAD

**Issue by sersou83** [highcharts/highcharts#5556]
#### Actual behaviour
In the console I see this error:
highstock.js:59 Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "z".dSetter @ highstock.js:59

#### Live demo with steps to reproduce
http://jsfiddle.net/sL377du8/6/

See console
#### Affected browser(s)
All

**Comment by acshef** [comment]
It's because the `data` attribute for your "Tiredness" polygon is an empty array. As a workaround, use `[0]` instead of `[]`

**Comment by sersou83** [comment]
@acshef Thank you very much for that tip, wasn't aware of it.

**Comment by pawelfus** [comment]
Minified example: http://jsfiddle.net/cpcmpp4x/
