### ISSUE TITLE
The property visible:false of xAxis/yAxis is not work

### ISSUE THREAD

**Issue by joe223** [highcharts/highcharts#5557]
### highcharts version 4.1.4
link [http://cdn.hcharts.cn/highcharts/4.1.4/highcharts.js](http://cdn.hcharts.cn/highcharts/4.1.4/highcharts.js)
#### Expected behaviour
The yAxis should be hidden 

#### Actual behaviour
Still show

#### Live demo with steps to reproduce

[http://jsfiddle.net/heyin223/ksoewcod/1/](http://jsfiddle.net/heyin223/ksoewcod/1/)

#### Affected browser(s)

chrome 51.0.2704.106 (64-bit)

**Comment by pawelfus** [comment]
Hi @joe223 ,

Thank you for reaching us. The problem is that `yAxis.visible` was implemented in 4.1.9 version, as described in the [API](http://api.highcharts.com/highcharts#xAxis.visible). Version 4.1.4 doesn't support that param.

**Comment by joe223** [comment]
@pawelfus Thank you so much, It is my mistake. I did not notice that words.
