### ISSUE TITLE
Can't find plotOptions.series.states.select in API reference

### ISSUE THREAD

**Issue by rafis** [highcharts/highcharts#5558]
This `color` option works, i.e. when I click section in pie chart it highlightes with this color:

```
    plotOptions: {
        series: {
            states: {
                select: {
                    color: '#ccc'
                }
            }
        }
    }
```

I'm trying to find other options what `plotOptions.series.states.select` might have, and I type in search input of [API reference](http://api.highcharts.com/highcharts) `states.select.color`, but can't find it.

**Comment by pawelfus** [comment]
It looks like `select.color` is available only for Highmaps:

https://github.com/highcharts/highcharts/blob/92a37d22bb990234406472b1a4f8fdc560bd6c6b/js/parts/Series.js#L2140-L2151

**Comment by pawelfus** [comment]
Fixed: https://api.highcharts.com/highcharts/plotOptions.series.states.select
