### ISSUE TITLE
Normalization of data for percentage values on the yAxis

### ISSUE THREAD

**Issue by charpour** [highcharts/highcharts#5559]
#### Description
Our chart displays percentages on the yAxis, and when a given value exceeds 95, the yAxis displays a value of 120. 120 is not a valid percentage value in our case. We want to limit the max label shown on the y axis, but keep the normalization of the labels if the values in the chart are lower. If we set a yAxis `max` value of 100 then the normalization doesn't work and the scale is always from 0 to 100.

Can we get the normalization working along with setting the `max` value on the yAxis?

**Comment by pawelfus** [comment]
Hi @charpour 

I think you want to use [`yAxis.ceiling`](http://api.highcharts.com/highcharts#yAxis.ceiling). Could you try it?

**Comment by charpour** [comment]
That has worked! Thank you very much.
