### ISSUE TITLE
When heatmap and map modules loaded legend items get a bigger margin

### ISSUE THREAD

**Issue by lionel87** [highcharts/highcharts#5561]
#### Expected behaviour

When heatmap and map modules both included don't change items margin.
#### Actual behaviour

When the heatmap and the map module both loaded the legend items gets way too much margins around them when using with colorAxis/dataClasses.

Able to "fix" it in config: set legend.itemMarginTop to -5, but does not work when you don't know if both or only one module is loaded.
#### Live demo with steps to reproduce

Only map module loaded (good): http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/maps/demo/data-class-ranges/
Map and Heatmap module loaded (bad): http://jsfiddle.net/fvn3qz8v/
#### Affected browser(s)

All

**Comment by TorsteinHonsi** [comment]
#### Workaround
There's no need to load `modules/heatmap.js`, it is already included in `highmaps.js`.
