### ISSUE TITLE
Treemaps with zero value fail

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#5563]
This is a regression with Highcharts 4.2.6.

#### Actual behaviour
JS error when adding treemap points with value 0. 

#### Live demo with steps to reproduce
http://jsfiddle.net/highcharts/1hj84pts/

#### Affected browser(s)
All

**Comment by nikithaachhini** [comment]
Hi @TorsteinHonsi  even I have the same issue. I see that you've fixed and closed it. Is it merged in the repo and updated? So that I can have the updated library in my project.

**Comment by TorsteinHonsi** [comment]
It is merged to the master in this repo, but if you're referring to the npm module, it is not yet published there. It will be part of the next maintenance release.

**Comment by nikithaachhini** [comment]
Okay thank you. Once it is published then probably the cdn for high charts would also be updated.

**Comment by TorsteinHonsi** [comment]
Yes it will. You can see our changelog page or subscribe to our email
notifications about new releases.​

**Comment by nikithaachhini** [comment]
Sure..will do. Thank you once again.
