### ISSUE TITLE
Columns with Drilldown broken after 4.2.6 upgrade

### ISSUE THREAD

**Issue by Katwood** [highcharts/highcharts#5565]
#### Expected behaviour
When users click on the columns to trigger a drilldown event, specific categories within that column should repopulate the X-axis. For example, if the column represented the kinds of vegetables people liked to eat, clicking on the column should fire an event when the various types of vegetables are listed.

#### Actual behaviour
When a user clicks on a column to fire a drilldown, the X-axis will repopulate with categories that are not a subset of the original column. To expand on the above example, the "Favorite Vegetables" column would now include all the original vegetables, plus a fruits and grains from other columns where people listed their favorite types of fruits and grains to eat.

#### Live demo with steps to reproduce
My errors seemed to be happening on the green column on the Columns with Drilldown chart, but the same issue seems to be happening here on the blue column when I use IE. The error occurs in the orange column in Chrome and Firefox.
https://jsfiddle.net/katwood/dp4az7v0/

The issue seems to be resolved when I inserted the scripts 
"https://code.highcharts.com/4.2.5/highcharts.js" and "https://code.highcharts.com/4.2.5/modules/drilldown.js"
into the page. While this fix is very effective (currently being used in the live version of my site: http://sonoma.edu/aa/ra/quick-facts/index.html), I would like to continue to run the latest versions of Highcharts without having to build in code to revert the page to an older version.

#### Affected browser(s)
IE, Firefox, Chrome

**Comment by morganfree** [comment]
Simplified demo: http://jsfiddle.net/zs6hmv8n/ -> drilldown and drillup
Names in axis.names are added on every drilldown and the old names (for different levels) are preserved.

Related to the comit https://github.com/highcharts/highcharts/commit/f3f805f4305f0a31b088c4acd25c4fe487adb0a3 and issue https://github.com/highcharts/highcharts/issues/2522

Possible workaround is resetting axis.names on drilldown/drillup:

    (function (H) {
    	H.wrap(H.Chart.prototype, 'drillUp', function (p) {
      	H.each(this.xAxis, function (axis) {
        	axis.names = [];
        });
        p.call(this);
      });
    })(Highcharts)


    chart: {
           events: {
              drilldown: function () {
              	Highcharts.each(this.xAxis, function (axis) {
                	axis.names = [];
                });
              }
            }
        }

http://jsfiddle.net/zs6hmv8n/1/

**Comment by TorsteinHonsi** [comment]
The deeper, more general problem here is that the names array is not kept updated with changes in the data series, like when removing a series: http://jsfiddle.net/L7dscdjf/.

In order to fix that, we would probably have to refactor the logic so that whenever the data updates, the names are re-indexed.

**Comment by TorsteinHonsi** [comment]
Reverted the fix above, as it broke some other tests. It needs a bit more work.
