### ISSUE TITLE
pointIntervalUnit day breaks when using more than 1000 data points

### ISSUE THREAD

**Issue by marcoschulte** [highcharts/highcharts#5568]
#### Expected behaviour
Using more than 1000 data points renders the date on the x axis correctly.

#### Actual behaviour
When using more than 1000 data points, the datetime on the x axis is interpreted as milliseconds.

#### Live demo with steps to reproduce
http://jsfiddle.net/c0emnc2h/

**Comment by pawelfus** [comment]
Hi @marcoschulte 

Thank you for reporting the issue. As **workaround**, you can disable [`series.turboThreshold`](http://api.highcharts.com/highcharts#plotOptions.series.turboThreshold). Demo: http://jsfiddle.net/c0emnc2h/1/
