### ISSUE TITLE
Plotbands and plotlines added dynamically using addPlotBandOrLine() are not exported

### ISSUE THREAD

**Issue by lgroschen** [highcharts/highcharts#5573]
#### Expected behaviour
I'm not sure how supported this is since I kind of found it by stumbling around in the API, but when using the command:
`chart.yAxis[0].addPlotBandOrLine()`

The plotLine (or Band) displays correctly and when exported will display the Line when the button is toggled on.

#### Actual behaviour
The .addPlotBandOrLine() displays correctly, but when exported in any format the Line is missing.

Similar problem fixed for addPlot():
https://github.com/highcharts/highcharts/issues/1114

#### Fiddle example
This example shows that addPlot() is shown correctly when exporting (the commented out section in the addBands function), but when using the addPlotBandOrLine() the exported image or pdf has no line:
https://jsfiddle.net/lgroschen/7he9wkeu/1/

#### Affected browser(s)
Chrome, Firefox, others?

**Comment by sebastianbochan** [comment]
During export, initial options of chart are copied and send to the exporting server. In the case that you add something dynamically (like plotBand) then chart does not include that. The solution is apply plotBand in the exporting.chartOptions.chart.events.load event. 

Example:
    - https://jsfiddle.net/x7uxbogj/

For general support, please use email / stackoverflow / forum.
