### ISSUE TITLE
{point.y:,.0f} Comma format fiddle doesn't work

### ISSUE THREAD

**Issue by lusa** [highcharts/highcharts#5574]
#### Expected behaviour
This tooltip format string- {point.y:,.0f}  is supposed to result in tooltips formatted with commas in it. 

#### Actual behaviour
As you can see from a fiddle linked from the documentation, there is no comma, instead, a space is between the numbers on the tooltip.
http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting

#### Live demo with steps to reproduce
http://jsfiddle.net/highcharts/rmTWS/

**Comment by pawelfus** [comment]
Hi @lusa ,

This is caused by:

> Note that even though a dot and a comma symbolizes the decimal point and the thousands separator respectively, how it is actually rendered depends on the language settings.

It's only a symbol, not the actual separator. That means, from [API](http://api.highcharts.com/highcharts#lang.thousandsSep), we should set `,` in options: 

    Highcharts.setOptions({
      lang: {
        thousandsSep: ','
      }
    });

Demo: http://jsfiddle.net/rmTWS/791/

**Comment by Umartahir93** [comment]
Hello. Is there anyway to put comma separator without using thousandsSep?

**Comment by sebastianbochan** [comment]
Hi @Umartahir93,
This is our bugtracker, so for general [support](http://www.highcharts.com/support) question please use forum / stackoverflow or forum.

ps. you can use [tooltip.formatter](https://api.highcharts.com/highcharts/tooltip.formatter) and return value in requested [format](https://api.highcharts.com/class-reference/Highcharts#.numberFormat).
