### ISSUE TITLE
Animation while adding a new point

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#5577]
#### Expected behaviour

Is there a way to have similar animation to updating point animation while adding a new point?
#### Live demo with steps to reproduce

http://jsfiddle.net/jbfjkfpu/1/

**Comment by Izothep** [comment]
Hello Paul,

I think that the real question is - how do we expect this animation to work. When we will look into  standard cases of using addPoint, we are often changing extremes on our xAxis. Adding this animation may not be the best idea - I am not sure if these animations will look good together. 

In case of adding point without changing extremes of xAxis, I think that better idea would be to use animation similar to Point.update(). 

As a very simple workaround you can wrap addPoint function and call Point.update() from this function. 

Look at this example: http://jsfiddle.net/e0qxfLtt/20/

**Comment by PaulDalek** [comment]
Hi Izothep,

Thank you for your fast answer. The Point.update() animation is exactly what I was thinking of. I used it in this example: http://jsfiddle.net/jbfjkfpu/2/ and think that these two animations combined together look good (with or without changing range of axis).
