### ISSUE TITLE
treemap

### ISSUE THREAD

**Issue by TurboAsteroid** [highcharts/highcharts#5578]
#### Expected behaviour
Must work

#### Actual behaviour
Don`t work

#### Live demo with steps to reproduce
4.2.6 bug http://jsfiddle.net/yju6omh3/3/
4.2.5 its ok http://jsfiddle.net/yju6omh3/4/

#### Affected browser(s)
all browser(s)

**Comment by jon-a-nygaard** [comment]
Duplicate of #5563. Please follow the mentioned issue number for more information and updates.
