### ISSUE TITLE
datalabels - verticalAlign align not applied for wide bar 

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5579]
Let's analyze two charts:
1) http://jsfiddle.net/LLbto3m2/ - verticalAlign (top or bottom) is noticable
2) http://jsfiddle.net/8u3jchLs/ -  verticalAlign (top or bottom) seems to working randomly and differences between two states are almost not noticable

**Comment by TorsteinHonsi** [comment]
Vertical align = "top" means that the top of the label is aligned to the top of the box.
Vertical align = "bottom" means that the bottom of the label is aligned to the bottom of the box.

See http://jsfiddle.net/highcharts/LLbto3m2/1/. Drag the slider to see how it is connected. Take special note of how a label is aligned on a 1px bar, which is counter intuitive to some.

**Comment by sebastianbochan** [comment]
Great demo, thanks!
