### ISSUE TITLE
chart with pane background setting, after destroy and recreate again duplicate old pane background in DOM 

### ISSUE THREAD

**Issue by dawidgorus** [highcharts/highcharts#5580]
#### Expected behaviour

After chart destory all elements in chart div container is removed - This is OK
After rendering chart again with the same settings chart is created as new
#### Actual behaviour

after destroying all elements are cleared from div container, but after creating chart again with the same settings, chart is created with duplicate pane backgrounds. 
After repeating this process the number of pane background are added to those from destroyed chart
#### Live demo with steps to reproduce

http://jsfiddle.net/pkZ9N/15/
#### Affected browser(s)

IE 11, Chrome 52

**Comment by sebastianbochan** [comment]
The problem is caused by using references to options, instead of new options object. To fix the issue, you should use $.extend() and create a copy of options object.

Fixed demo:
   - http://jsfiddle.net/ds957oag/

For general support questions, please use email / stackoverflow / forum. More information: http://highcharts.com/support

**Comment by pawelfus** [comment]
I think this is a bug: `xAxis.plotBands` array gets a new plotBand everytime chart is generated: http://jsfiddle.net/t8s94d4t/

**Comment by dawidgorus** [comment]
I found it when set pane background color with alfa, after redraw chart the background came darker.

**Comment by dawidgorus** [comment]
any sings of fixing this issue

**Comment by sebastianbochan** [comment]
+1

**Comment by dawidgorus** [comment]
any sings of fixing this issue +3

**Comment by dawidgorus** [comment]
Sorry, looks like this issue is fixed in current version.
Thanks for that. Issue can be closed 
check with http://jsfiddle.net/t8s94d4t/
