### ISSUE TITLE
Navigator doesn't work after remove all series and add series

### ISSUE THREAD

**Issue by Vivihung** [highcharts/highcharts#5581]
#### Expected behaviour

User should be able to navigator to zoom in/out chart.
#### Actual behaviour

If chart's series is added AFTER chart creation, 
once the chart's series has been removed and add new series, navigator doesn't work.
And setExtremes event seems not fired (or the event handler is missing)
#### Live demo with steps to reproduce

http://jsfiddle.net/Vivien/k3xxy5mk/

Note: Please click on "Re-add series" button TWICE to repro the bug.
#### Affected browser(s)

IE 11, Chrome, Edge

**Comment by pawelfus** [comment]
The issue caused by manually removing navigator series. If we let Highstock remove that series, then it works fine (at least v.5.0.7), demo: http://jsfiddle.net/k3xxy5mk/6/

**Comment by Vivihung** [comment]
Thanks! I checked your demo.
If we use different set of series data after remove series, will the navigator series been updated to the later one?

**Comment by pawelfus** [comment]
Of course, that will work. Demo: http://jsfiddle.net/k3xxy5mk/7/

Hint: You can also display all series in the navigator: http://jsfiddle.net/k3xxy5mk/8/
