### ISSUE TITLE
Enhancement: support non numeric values in dataGrouping.approximation

### ISSUE THREAD

**Issue by laopunk** [highcharts/highcharts#5582]
#### Expected behaviour
I would like the Custom aggregate method to not be limited to numeric but rather accept any kind of values, objects in particular.
Context:
In my case, I need to calculate the NPS score from the dataset, this is not a value that can be averaged and therefore requires a custom aggregate. But this calculation requires 3 values (promoters, detractors and total) which are in series.data points, but is not being sent to the approximation method

#### Actual behaviour
Only accepts a flat numerical array, as per documentation
http://api.highcharts.com/highstock#series<area>.dataGrouping.approximation

#### Live demo with steps to reproduce
http://jsfiddle.net/ob0ad9ee/

#### Affected browser(s)
All, not browser related

**Comment by TorsteinHonsi** [comment]
This can be resolved without breaking backwards compatibility by adding information about the current data being grouped. 

I committed a small change at https://github.com/highcharts/highcharts/commit/b435fba0ea250ea17c69cdaf4c7d6c2eefd6ec0e.

See demo at http://jsfiddle.net/highcharts/rvrw3kw9/. In your fiddle, the data format is wrong, you need to provide x and y on the object config, then you can set your custom options on the same object. Now you can access the data group's raw data: http://jsfiddle.net/highcharts/ob0ad9ee/1/

**Comment by laopunk** [comment]
That works indeed really well, thank you @TorsteinHonsi  !

A documentation update would be a good thing for others to know this is now possible :-)
And finally, could this change be pushed to highcharts-dist and npm ?

Thanks,
David

**Comment by TorsteinHonsi** [comment]
> And finally, could this change be pushed to highcharts-dist and npm ?

Yes, it will be pushed with the next release, probably 4.2.7.

> A documentation update would be a good thing for others to know this is now possible :-)

... and added to the docs when released.

> Thanks,

You're welcome!
