### ISSUE TITLE
Link in tooltip in IE11 is not working

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5584]
#### Behaviour

Link in tooltip in IE11 on Windows 7 is not working
#### Live demo with steps to reproduce

http://jsfiddle.net/3zejuctb/1/
Hover over the top stack and click on a first link.
#### Affected browser(s)

IE11 in Windows 7 (IE 11.0.9600.18426)

(it works in IE11 in Windows 10 (IE 11.545.10586.0), but link is changing rapidly style from visited to not-visited when hovering over a tooltip)

**Comment by TorsteinHonsi** [comment]
Seems like a browser layout bug, especially since it's working in Win10.
