### ISSUE TITLE
V4.2.6 3D Pie with Drilldown, 2nd chart not using whole Pie

### ISSUE THREAD

**Issue by jaydub36** [highcharts/highcharts#5585]
#### Expected behaviour
When clicking on a 3D enabled Pie section with drilldown, the 2nd level Pie should be the size of the whole Pie.

#### Actual behaviour
2nd level is only using the space of the slice from the original Pie.

#### Live demo with steps to reproduce
http://jsfiddle.net/2msvbf9g/2/

click any slice, disable 3D to see expected behavior

#### Affected browser(s)
IE11, Chrome, Firefox are what I can test and all have issue

**Comment by pawelfus** [comment]
Hi @jaydub36, thank you for reporting the issue. It is already fixed on the master branch, please take a look: http://jsfiddle.net/2msvbf9g/3/

**Comment by jaydub36** [comment]
Sorry, I didn’t think to point all the js files at the master branch.

Thanks for you quick response!


Jason Whitmire
Software Developer Consultant, Targeting GPD

Experian Marketing Services
955 American Ln, Schaumburg, IL 60173
T 224.698.8278
Web<http://e.experian-ems.com/a/hBSnlo$B8efpWB82x9KNsffDKtk/ems> | Blog<http://e.experian-ems.com/a/hBSnlo$B8efpWB82x9KNsffDKtk/mktfwd1> | Twitter<http://e.experian-ems.com/a/hBSnlo$B8efpWB82x9KNsffDKtk/tw> | Facebook<http://e.experian-ems.com/a/hBSnlo$B8efpWB82x9KNsffDKtk/fb2> | Linkedin<http://e.experian-ems.com/a/hBSnlo$B8efpWB82x9KNsffDKtk/ln1>
