### ISSUE TITLE
Why highmaps drilled down not working for srilanka data?

### ISSUE THREAD

**Issue by sajeetharan** [highcharts/highcharts#5586]
#### Expected behaviour

It should drilled down to the actual province and get the districts inside of it

#### Actual behaviour

It does not actually work, it says Failed loading!

#### Live demo with steps to reproduce
 http://fiddle.jshell.net/sebastianbadea/xdqp021q/

**Comment by oysteinmoseng** [comment]
Your demo is using Google Maps, and in our [official async drilldown demo](http://www.highcharts.com/maps/demo/all-maps) this seems to work. Closing for now, if you are able to reproduce it we can reopen.

**Comment by sajeetharan** [comment]
Here is the link http://jsfiddle.net/sajeetharan/uokcypbb/1/

**Comment by oysteinmoseng** [comment]
@sajeetharan Unfortunately we do not provide any district maps for Sri Lanka, so you would have to use [custom maps](http://www.highcharts.com/docs/maps/custom-geojson-maps) to achieve this. See [here](http://code.highcharts.com/mapdata) for a list of the maps we provide
