### ISSUE TITLE
3dpie chart serious drilldown bug

### ISSUE THREAD

**Issue by rathoregee** [highcharts/highcharts#5587]
#### Expected behaviour
On drill down it should show complete pie chart.
#### Actual behaviour
On drill down it is showing pie chart slice.
#### Live demo with steps to reproduce
https://jsfiddle.net/rathore_gee/cfsaffr5/
#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @rathoregee, 

Thank you for reporting. It is already fixed on our master branch, please take a look: http://jsfiddle.net/cfsaffr5/1/
