### ISSUE TITLE
'500 Internal Server Error when exporting' same as  #4959

### ISSUE THREAD

**Issue by Frank004** [highcharts/highcharts#5588]
#### Expected behaviour
export the chart in PDF,JPEG, PNG format

#### Actual behaviour
 Same as Issue #4959
![0e97b316-c43f-11e5-845e-c51c79d5bde1](https://cloud.githubusercontent.com/assets/7242689/17682597/8c1f0f44-631a-11e6-8efa-76309573d07a.png)
 http://export.highcharts.com/ is generating an '500 Internal Server Error when exporting' .
#### Live demo with steps to reproduce
 http://www.highcharts.com/demo/line-ajax 
any export get the error

**Comment by damseldeebi** [comment]
Hi,

I'm facing the issue now. Can confirm with the following fiddle. 
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/members/chart-exportchart-filename/

**Comment by mubashar-entertainerme** [comment]
Hi Support,
We are facing same problem, getting '500 Intertal Server Error' on exporting chart! could you please share the solution?
Thanks

**Comment by stefanray** [comment]
Also seeing the issue here.

**Comment by Frank004** [comment]
**A quick fix  for the moment so your clients down melt down** 

Add this to the layout application:
`<script src="http://code.highcharts.com/modules/offline-exporting.js"></script>
`


Add this to the js for each chart as a option:
This will make client side png and jpg
```
            exporting: {
            chartOptions: { // specific options for the exported image
                plotOptions: {
                    series: {
                        dataLabels: {
                            enabled: true
                        }
                    }
                }
            },
            scale: 3,
            fallbackToExportServer: true
        },
```

**Comment by Frank004** [comment]
The server are working again check and let me know so I can close this issue

**Comment by stefanray** [comment]
yes it's back working for me.

**Comment by mubashar-entertainerme** [comment]
Yes, its back now!

--
With Thanks,
Mubashar Ehsan
API Project Manager

P.O. Box 502202, Dubai Media City,
Arjaan Rotana Office Tower, Office #508,
Dubai, UAE

T +971 4 427 9575 Ext 1725
M +971 56 398 3209
F +971 4 390 8071
theentertainerme.com





Please don't print this email unless you really need to. This will preserve trees on our planet.
The information in or attached to this email is confidential and may be legally privileged. If you are not the intended recipient of this message any use, disclosure, copying, distribution or any action taken in reliance on it is prohibited and may be unlawful. All the information send and received by the originator and recipient is official correspondence and legally sustainable. If you have received this message in error, please notify the sender immediately by return email or by telephone on +971 4 390 2866 and delete this message and any copies from your computer and network. The Entertainer Fz LLC does not warrant that this email and any attachments are free from viruses and accepts no liability for any loss resulting from infected email transmissions. The Entertainer Fz LLC reserves the right to monitor all e-mail communications through its networks. Please note that any views expressed in this email may be those of the originator and do not necessarily reflect those of the The Entertainer Fz LLC
