### ISSUE TITLE
Dynamically add panes and series to gauge, Update Options on the respective Panes and series from form

### ISSUE THREAD

**Issue by chandram97** [highcharts/highcharts#5592]
I had an requirement with gauge Chart -

http://jsfiddle.net/chandram97/zw0sujo2/2/

In the above example you can see that title is printing two times, But I need single title to be displayed at the center.

So I got solution from your team that instead of creating multiple charts create single chart with multiple panes and series objects as shown in below link.

http://jsfiddle.net/chandram97/do60mz99/1/

In My charts i can have gauge or  solid gauge or both.

But now the Problem is, I want to actually add the panes and series objects dynamically . How can I add that for series I have chart.addSeries() how about pane.

Also in my charts we have enabled a toolbar where we have some form where the users can filter the options like

whether to show title
change tickamount
change mintickinterval etc

how can i update these options to a particular pane and series when I am using multiple panes and multiple series

Please help me.

**Comment by pawelfus** [comment]
Related ticket #5576 

I think solution suggested by Jon in your previous ticket is a way to go.
