### ISSUE TITLE
Shape Property is not available in pane Object

### ISSUE THREAD

**Issue by chandram97** [highcharts/highcharts#5593]
#### Expected behaviour

In solid gauge we have two shapes **arc and circle**, which we can set in pane

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/gauge-solid/

```
            `pane: [{
                startAngle: -90,
                endAngle: 90,
                background: null,
                center: ['25%', '85%'],     
                size: '140%',                   
                background: {
                    backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || '#EEE',
                    innerRadius: '60%',
                    outerRadius: '100%',
                    shape: 'arc'
                }
            }, {
                startAngle: -90,
                endAngle: 90,
                background: null,
                center: ['70%', '45%'], 
                size: '120%',                   
                background: {
                    backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || '#EEE',
                    outerRadius: '100%',
                    shape: 'circle'
                }
            }],`
```

I am trying to change the shape of the chart dynamically as below
`chart.pane[1].background.shape='arc';`
#### Actual behaviour

As per the API I do not see shape property in pane 

See the image attached 
![pane_noshape](https://cloud.githubusercontent.com/assets/20943617/17734089/b932e798-6497-11e6-9c63-8d21c2c73abd.png)

Let me know how can I change the Pane Shape dinamically

**Comment by pawelfus** [comment]
Hi @chandram97,

There's no method as `pane.update()` to update pane shape dynamically. Changing something in the chart object won't work. 

Instead you can use [`plotBands`](http://api.highcharts.com/highcharts#xAxis.plotBands), which can be added/removed on demand. Demo for you: http://jsfiddle.net/23wqj35u/

I agree, that `plotBand.shape` and `pane.background.shape` should be in the docs.

**Comment by chandram97** [comment]
Hey

**Comment by pawelfus** [comment]
I think we should keep this opened until docs will be updated.

**Comment by pawelfus** [comment]
`pane.background.shape` is available in the new API docs, [link](http://api.highcharts.com/highcharts/pane.background.shape).
