### ISSUE TITLE
ignoreHiddenPoint fails with highcharts-3d.js

### ISSUE THREAD

**Issue by PunKeel** [highcharts/highcharts#5594]
#### Behaviour
When using the pie's option `ignoreHiddenPoint` set to true, clicking on tiles should hide them from the chart, and resize the chart accordingly.

Using the same code, this behaviour fails when highcharts-3d.js is imported (not even used): the pie's part are hidden, but the chart is not resized. :( 

#### Live demo with steps to reproduce

https://jsfiddle.net/z6geeeej/ <- without -3d.js
https://jsfiddle.net/y2ntLxq3/1/ <- with -3d.js

#### Affected browser(s)
Chrome 51, FireFox

**Comment by jon-a-nygaard** [comment]
_Internal Note: [simplified demo](https://jsfiddle.net/jon_a_nygaard/z6geeeej/1/). Click on legend item to hide point. The remaining points are not resized to accustom too the available space._

**Comment by pawelfus** [comment]
It's already fixed on the master branch: http://jsfiddle.net/z6geeeej/4/
