### ISSUE TITLE
Shared tooltips aren't always activated after hovering over a bubble

### ISSUE THREAD

**Issue by khoomeister** [highcharts/highcharts#5595]
#### Expected behaviour

Hovering over the blank space of a plot area (i.e. without the mouse cursor touching any other series such as line/area) should always display a tooltip if tooltip.shared = true.

#### Actual behaviour

However after hovering over a bubble series, as long as the mouse cursor doesn't touch any other series on the same chart, shared tooltips won't activate.

My guess is this probably applies to all other unordered data series as well.

#### Live demo with steps to reproduce

http://jsfiddle.net/khoomeister/aqpw331y/6/

1. Mouseover over a bubble and observe tooltip appear.
2. Mouseout and as long as your cursor doesn't touch the line series, shared tooltips won't appear.

**Comment by TorsteinHonsi** [comment]
If you set `stickyTracking` to false on the bubble series, you get the desired result: http://jsfiddle.net/highcharts/aqpw331y/7/

**Comment by khoomeister** [comment]
Hey @TorsteinHonsi 

`stickyTracking` helped but it was still happening, albeit much less often.

I tracked it down to the use of `tooltip.useHTML`.  If that is set to true, then hovering over the bubble, then the tooltip, and then in the blank plot area without touching any other series will not activate shared tooltips.

Example: http://jsfiddle.net/khoomeister/aqpw331y/9/

**Comment by khoomeister** [comment]
Oh I see I can't reopen, did you want me to create a new issue for it?

**Comment by TorsteinHonsi** [comment]
Thanks for elaborating! It happens when we mouse over the tooltip first, then over the plot area. If we mouse out from the bubble to the plot area directly, it hides as expected.
