### ISSUE TITLE
BUG: Long title/subtitle been cut off at bottom

### ISSUE THREAD

**Issue by rs-longsheng** [highcharts/highcharts#5598]
#### Expected behaviour

The subtitle/title are shown correctly at the bottom. And exporting results are correct.
#### Actual behaviour

The subtitle/title are truncated. The exporting result are not correct.
#### Live demo with steps to reproduce

[subtitle demo](http://jsfiddle.net/cbcbxq4f/)
[title demo](http://jsfiddle.net/4d7nz4e0/)
#### Affected browser(s)

Test on chrome, highly possible that it's for all browsers.

**Comment by pawelfus** [comment]
I am not sure if this a bug, it works as described in the [API](http://api.highcharts.com/highcharts#title.verticalAlign): 

> The vertical alignment of the title. Can be one of "top", "middle" and "bottom". When a value is given, the title behaves as floating.

The key word here is "floating", I think there should be reference to [`floating`](http://api.highcharts.com/highcharts#title.floating):

> When the title is floating, the plot area will not move to make space for it. Defaults to false.

**Comment by rs-longsheng** [comment]
@pawelfus Exactly as you mentioned,

> When the title is floating, the plot area will not move to make space for it. Defaults to false.

By default floating is false, so the plot area will(**???**) move to make space for it.
I played around with my previous demos and it seems setting "floating" does not help me show a long title.

**Comment by pawelfus** [comment]
@rs-longsheng, that's correct:
> By default floating is false, so the plot area will(???) move to make space for it.

Default value is `false` but when you set `align`, that floating is enabled:
> When a value is given, the title behaves as floating.

In other words, when title has option `align`, `floating` option is forced to be true.
