### ISSUE TITLE
Highstock: YTD button is not enabled even though data starts on Jan 1st

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5600]
#### Expected behaviour
YTD button is enabled when data starts at Jan 1st
(as per definitions here: https://en.wikipedia.org/wiki/Year-to-date and here: http://www.investopedia.com/terms/y/ytd.asp)

#### Actual behaviour
YTD button is enabled when data starts before Jan 1st

#### Live demo with steps to reproduce
Should be enabled but isn't:
http://jsfiddle.net/p9mu6Ls9/

Compare with a start date before Jan 1st:
http://jsfiddle.net/p9mu6Ls9/1/

**Comment by pawelfus** [comment]
Caused by [this line](https://github.com/highcharts/highcharts/blob/2bba08ffe0ac1f90062885a1fd5856aae5229e05/js/parts/RangeSelector.js#L336).
