### ISSUE TITLE
Highstock: typing same date into inputs doesn't work even after change of extremes

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5602]
#### Behavior
Typing same date second time after different extremes has been set is not working.

#### Live demo with steps to reproduce
http://jsfiddle.net/r6nzx5rx/
1. Drag navigator to somewhere around middle of available time range.
2. Type in `To` input a date (like `2015-05-15`). Chart will adjust correctly.
3. Drag navigator to the left side (or change currently visible range any other way than via `To` input).
4. Type in `To` input the same date (like `2015-05-15`). Input is not accepted, chart is not adjusted.

#### Affected browser(s)
Probably all.
Tested:
Chrome, Firefox, IE11 - on Windows 10

**Comment by facboy** [comment]
It also seems that if you type a date into the From box, and then one into the To box, the date in the From box reverts and then can no longer be set.

**Comment by oysteinmoseng** [comment]
Fixed the issue from @facboy, but the original issue seems to remain.
