### ISSUE TITLE
Multi level drill down in highmaps

### ISSUE THREAD

**Issue by sajeetharan** [highcharts/highcharts#5604]
#### Expected behaviour
It should drill down to srilanka when we select srilanka from asian continent

#### Actual behaviour
Nothing happens

#### Live demo with steps to reproduce
http://fiddle.jshell.net/pncv2sak/6/

**Comment by sebastianbochan** [comment]
Similar to https://github.com/highcharts/highcharts/issues/5586

**Comment by Izothep** [comment]
Hi, 

I don't think it is a bug. For questions about your code you may use different lines of support, like StackOverflow or Highcharts Forum. 

I think that in your case you forgot to add drilldown parameter to your Sri Lanka point. You need to add detailed Sri Lanka map as well. Here you can find live demo how your map will work with these small corrections: http://fiddle.jshell.net/pncv2sak/9/ 

Regards.
