### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onload' of undefined

### ISSUE THREAD

**Issue by borisyankov** [highcharts/highcharts#5605]
For reason unknown an error is thrown deep in Highcharts code.

The file where it is thrown is:
https://github.com/highcharts/highcharts/blob/90b2d6569709c7c27fab48cdb3944395bdef40aa/js/parts/SvgRenderer.js

The line is on:
```
if (!ren.imgCount && charts[ren.chartIndex].onload) {
```

ren.chartIndex is 0,

charts is equal to [undefined, {some object}]

So, trying to access onload on the first element is the cause.

It is hard to isolate the code to reproduce, but if you can lead me to what could be causing it, I can try to trace it.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! Based on your information, I can see that this happens when the chart is destroyed before the image is loaded: http://jsfiddle.net/highcharts/95tcanbm/.
