### ISSUE TITLE
setExtremes removes Y-Axis when max value is lower then min value of series

### ISSUE THREAD

**Issue by trpriel** [highcharts/highcharts#5606]
#### Expected behaviour
Have a Y-Axis with empty series

#### Actual behaviour
No series and no Y-Axis

#### Live demo with steps to reproduce
http://jsfiddle.net/7e3seesa/

#### Affected browser(s)
Tested on Chrome v52

**Comment by TorsteinHonsi** [comment]
Demo with static Y axis: http://jsfiddle.net/highcharts/7e3seesa/4/

This is the expected behaviour. When all the data is above the given `max`, we don't have the information needed to compute a `min` based on the data range.
