### ISSUE TITLE
Arabic langauge - wrong rangeselector - exporting

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5608]
#### Actual behaviour

There are some issues with buttons (text out of box) and inputs (misaligned text)
#### Live demo with steps to reproduce
1. http://jsfiddle.net/1ht38aj6/
2. Export i.e to PNG
#### Affected browser(s)

All browsers

**Comment by TorsteinHonsi** [comment]
Apparently there are two issues:

*Text out of the box*
This is most likely explained by that the fonts used on screen are not available on the server. It can be prevented by using the more common Arial font: http://jsfiddle.net/1ht38aj6/1/.

*Bi-directional text problems*
The SVG implementations have various problems with rendering bi-directional text. This is often resolved by using HTML to render labels in Highcharts, but that option is currently not available for the range selector inputs. The workaround here, if you can live with the [browser support](http://www.highcharts.com/docs/export-module/client-side-export), is to use offline exporting, see http://jsfiddle.net/1ht38aj6/3/. 

#### Suggested fix
Implement `useHTML` option for the range selector inputs.
