### ISSUE TITLE
Ionic 2 and HighCharts fitting to page

### ISSUE THREAD

**Issue by oliviercherrier** [highcharts/highcharts#5609]
#### Expected behaviour

Highcharts inserted into a Ionic 2 `ion-content` (which is the basic content tag of Ionic 2) should be fit to the browser page without having to resize the page. This is mandatory to use Ionic 2 tabs and Highcharts in the same page...
#### Actual behaviour

When inserting an Highcharts in a Ionic 2 ion-content, the fitting of the Highcharts is only done after resizing the browser window.

Thanks to answer of Ionic  2 team (issue https://github.com/driftyco/ionic/issues/7823), it seems to be an issue with the css that highcharts uses for Highcharts canvas element.
#### Live demo with steps to reproduce

http://plnkr.co/edit/VplSXRKSA7iCnZ3E2zYk?p=preview
#### Affected browser(s)

At least Google Chrome

**Comment by pawelfus** [comment]
It looks like a classic issue with rendering chart in a hidden element. In that case, browser detects container width as 0px, which forces Highcharts chart to use default size (600px x 400px). See demo: http://plnkr.co/edit/HLj7UiwHIcO2wzV8v6FX?p=preview - in console you can find:

> My width is: 0

I can suggest:

- using `setTimeout()` to reflow the chart, when item is ready: http://plnkr.co/edit/R6W6IKXhkxIB9RjLwyEN?p=preview
- render chart **after** container is visible (does Ionic provide such callback?)

**Comment by oliviercherrier** [comment]
Hello @pawelfus,

thank you for your help. Very clear!!!

I am working to find the Ionic callback executed once container is visible: I show `ionViewDidEnter` (http://ionicframework.com/docs/v2/api/components/nav/NavController/) but it does not seams to be executed a bit before container is visible.

I'll keep you in touch.

**Comment by ayoubboum** [comment]
@pawelfus thanks for your solution, do you use highcharts ?

**Comment by pawelfus** [comment]
@ayoubboum you're welcome! Yes, I do. I am also one of devs.
