### ISSUE TITLE
There is no provision to rotate image around its center.

### ISSUE THREAD

**Issue by pranjalrathod01** [highcharts/highcharts#5610]
In Meteogram, I want to rotate weather symbol for some reason, after using rotation attribute it changes its position, because it does not rotate around its center. It rotates from 0,0 pixel of image,
So, if I rotate it 90 degrees its gets shifted completely to new position.

Please, Resolve this issue or provide in alternate solution.
I need it, Please help.

#### Expected behaviour
Weather Symbol should rotate around its centre

#### Actual behaviour
Weather Symbol changes its position after rotation.

**Comment by TorsteinHonsi** [comment]
You need to change the `translateX` and `translateY` attributes to compensate for the rotation. For example http://jsfiddle.net/highcharts/88vqhr92/

**Comment by pranjalrathod01** [comment]
@TorsteinHonsi , I took 90 degrees just for example. Rotation for every weather symbol can be from 0 degree to 360, anything.
Angle of rotation for every icon is different. Your solution works only for 90 degree that too same  for every icon.

**Comment by TorsteinHonsi** [comment]
It's the same approach, you need to correct translateX and translateY by various amounts. You can calculate that using Math.sin and Math.cos of your rotation.
