### ISSUE TITLE
Strange behaviour on MouseOver polygon + flag series

### ISSUE THREAD

**Issue by sersou83** [highcharts/highcharts#5611]
#### Actual behaviour

Moving the mouse over a flag series and then over a polygon series will generate the following error:
highstock.js:170 Uncaught TypeError: Cannot read property 'yAxis' of undefined

If you first move the mouse over a polygon series this error is not generated.
#### Live demo with steps to reproduce

http://jsfiddle.net/sL377du8/7/
Run the demo and move the mouse over the flag series first (make sure the mouse is not moved over the polygon serie) then move the mouse over the polygon serie, on the console you'll se the error mentioned.

Run the demo again, move the mouse freely over the chart making sure you move it first over the polygon serie will not cause any error.

Hiding the flag series and unhiding it again will generate the same error if the mouse is moved from the flag series to the polygon, this is repeatable every single time, just hide and unhide the flag series.
#### Affected browser(s)

ALL

**Comment by pawelfus** [comment]
Hi @sersou83,

Thank you for reporting the issue!

*Internal note:*
It's caused by [this line](https://github.com/highcharts/highcharts/blob/2bba08ffe0ac1f90062885a1fd5856aae5229e05/js/parts/Tooltip.js#L151) where we check `this.followPointer`, which is undefined in the first iteration.

**Comment by sersou83** [comment]
Thank you @pawelfus .
There's any workaround that you suggest?

**Comment by pawelfus** [comment]
Right, I see two possible solutions:

- use `followPointer: false`
- add short wrapper to set that option (demo: http://jsfiddle.net/sL377du8/10/ ):

        (function(H) {
          H.wrap(H.Tooltip.prototype, 'getAnchor', function (p) {
            var UNDEFINED;
            if (this.followPointer === UNDEFINED) {
              this.followPointer = true;
            }
            return p.apply(this, [].slice.call(arguments, 1));
          });
        })(Highcharts);

**Comment by pawelfus** [comment]
Okay, just realized the real culprit of the issue. Simply `flag` series doesn't have `followPointer` option. So simple solution is:

      flags: {
        tooltip: {
          followPointer: true // yeah, that fix the issue :)
        },
        cursor: 'default',
        states: {
          hover: {
            fillColor: '#FCFFC5'
          }
        }
      }

**Comment by sersou83** [comment]
Thank you @pawelfus .
I don't use `followPointer: true`  because I don't really want that behaviour on the flag series. I really want the tooltip to show on the flag series as `followPointer: false` and on the polygon series as `followPointer: true`. Is that possible?

**Comment by pawelfus** [comment]
Please, check out my previous solutions.

**Comment by sersou83** [comment]
Unfortunately none of the solutions worked.
Setting `followPointer: false` will cause this error every time.

**Comment by pawelfus** [comment]
Right, I see. How about this way: http://jsfiddle.net/sL377du8/12/

**Comment by sersou83** [comment]
That did the trick perfectly!
Thank you very much for your time!!

**Comment by KacperMadej** [comment]
The problem is more general and is possible to recreate using column and line with `tooltip.followPointer: true`.

Demo: http://jsfiddle.net/ndpz16cm/

Steps:
1. Hover the column
2. Move left onto the line
3. Error in browser console

**Comment by KacperMadej** [comment]
Fixed since version 5.0.8.
