### ISSUE TITLE
Need Scrollbar - Multiple gauge chart with Multiple Panes.

### ISSUE THREAD

**Issue by chandram97** [highcharts/highcharts#5612]
Hi Team,

I am now able to work with multiple gauge chart with Multiple Panes as per #5576. 

Now the Problem is, if I add multiple charts, I need scroll bar to show all of them.

Div width should not be increased, It should be same. All I need is scroll bar.

Below are the two issues I have

Issue 1: Can you help in getting scrollbar
Issue 2: Also I need all of them to align perfectly using center[a%, b%]. How can i calculate  that and align

Please find the JSFiddle code below

https://jsfiddle.net/chandram97/orpqycq4/2/

Please help

Thanks a lot in advance

**Comment by pawelfus** [comment]
Hi @chandram97 

My apologies, somehow I missed this issue.

For support related questions, please contact with us directly by email, see more [here](http://www.highcharts.com/support).
