### ISSUE TITLE
Inconsistent tooltip position when shared:true

### ISSUE THREAD

**Issue by pslacerda** [highcharts/highcharts#5614]
The tooltip position (or the anchor position) is incorrect and far away from the columns pointed by the cursor.  Possibly relevant code is [Tooltip.js#L134](https://github.com/highcharts/highcharts/blob/master/js/parts/Tooltip.js#L134) and possibly related to #4581.
#### Expected behaviour

Tooltip appears between the columns.
#### Actual behaviour

Tooltip appears far away from the columns. In the screenshot the first column had a mouse pointing it and has a grey rectangle hidding important stuff.
![image](https://cloud.githubusercontent.com/assets/149358/17906615/80c5a236-694e-11e6-9112-83c392ed72cb.png)
#### Live demo with steps to reproduce

http://jsfiddle.net/rsksbtr5/3/
#### Affected browser(s)
- Firefox 35.0.1
- Chrome 52.0.2743.116 m

**Comment by TorsteinHonsi** [comment]
I can't see the same behaviour in the jsfiddle... Can you reproduce it if you set a fixed size to the chart? What column do I have to hover to see the issue?

**Comment by KacperMadej** [comment]
Please reopen if needed and the problem is recreated.
