### ISSUE TITLE
Imprecise marker positioning in line charts, due to rounding issues

### ISSUE THREAD

**Issue by leyan** [highcharts/highcharts#5615]
When working with thin lines and small markers, markers are visibly offset to the left relative to the line. This is especially jarring when zooming in on exported vector files, but it can also be visible by the end user directly in the browser, when on a chart with a lot of points.

Try for example exporting a pdf from http://jsfiddle.net/sszq0tan/ and zooming in.
This gives:
 ![bhpzcdk](https://cloud.githubusercontent.com/assets/537624/17930340/fc0a4dc2-6a05-11e6-9a7e-feddbff18939.png)

After some digging, I saw this is related to the bugfix #1843 (and #4586). After removing the mathFloor added at the time, the result is much better: 
![bqcshvj](https://cloud.githubusercontent.com/assets/537624/17930341/fe3cdae2-6a05-11e6-9ede-50fd858ff0db.png)

As the initial problem does not seem related to line charts, is it possible to apply the mathFloor only under the relevant conditions, and keep the actual value for line charts?

**Comment by TorsteinHonsi** [comment]
So the marker rounding position is actually only needed whenever there's a column behind it. But there may also be other elements it should be aligned to, like grid lines etc. 

In general, I think the most appropriate fix would be to disable all forms of crisping altogether in _exported_ charts. It could be implemented as a general chart option that was true by default in export.

**Comment by leyan** [comment]
The issue is also visible when viewing directly the chart on our website, even without exporting, so I would prefer an actual solution. In our charts, the markers seem off, which is due to the slight offset to the left:
![website marker offset](https://cloud.githubusercontent.com/assets/537624/17930163/16e508f4-6a05-11e6-9273-20015099b5b4.png)

I think The most important thing is to ensure consistency between the line and the markers. I would prefer to have both at the correct exact position, but if it cannot be done, maybe have both rounded in a similar way could be feasible?
