### ISSUE TITLE
highmap doesn't  have chart type PIE?

### ISSUE THREAD

**Issue by V-Tom** [highcharts/highcharts#5616]
#### Expected behaviour

sorry:
Does highmap have the type `pie` 's chart?
if not,i should import hightchart. but why not suppose?

but i see the code on 16434 line write:
 `Override the base drawDataLabels method by pie specific functionality`
to check and define `pie` type

if i am wrong ,i am so sorry for that! please tell me how to resolve it
thanks

#### Actual behaviour

when i use highmap to render `pie` type chart , throw err 17

#### Live demo with steps to reproduce

http://jsbin.com/fofurejipu/edit?html,js,console,output

#### Affected browser(s)
Mac chrome latest

**Comment by zhy1stgg** [comment]
you can use highcharts and highmaps together by import highcharts.js and moudules/maps.js

```
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/maps/modules/map.js"></script>
```

documentation: http://www.highcharts.com/docs/getting-started/installation

**Comment by V-Tom** [comment]
It's my wrong.
Thanks a lot !
