### ISSUE TITLE
Highstock throws a exception on mouse click

### ISSUE THREAD

**Issue by borisyankov** [highcharts/highcharts#5617]
Error happens on all browsers (but is worded differently).

When clicked anywhere on the chart (not always, but often) an exception is thrown:
Cannot assign to read only property 'target' of object '#<MouseEvent>'

It happens in function fireEvent, in:
````
} else if (hcEvents) {
````
on line:
````
eventArguments.target = el;
````

The value of eventArguments is a standard MouseEvent object.

**Comment by borisyankov** [comment]
I did a custom build from the latest sources in master, and the problem disappeared.

**Comment by litera** [comment]
Here you go [repro fiddle](https://jsfiddle.net/eyv3x7k8/7/). It's not using highcharts at all, but you can see when the console throws an error while assigning to `eventInstance.target`. Highcharts is doing the same, and shouldn't. When not in strict mode, assignment doesn't do anything so it should be removed from code. But when in strict mode, code throws an error resulting in buggy apps that use Highcharts.

**Comment by pawelfus** [comment]
Hi @litera 

Thank you for the demo, we understand the issue, but we can not recreate it in Highcharts. We add target only for custom events (`chart.redraw`, `Axis.setExtremes`, etc.) which don't have `target` property and is not MouseEvent type. Please, recreate issue in jsfiddle using Highcharts, we will take a look - maybe there is a case when it's broken. Thanks!

**Comment by litera** [comment]
@pawelfus I can surely recreate the issue with highcharts when I change your minified code to (just the beginning of it)
```
/*
 Highcharts JS v4.2.4 (2016-04-14)

 (c) 2009-2016 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';
(function(C,Z){typeof module==="object"&&module...
```
So I just added the `'use strict'` at the beginning which will run Highcharts code in strict mode.

**Comment by pawelfus** [comment]
@litera it's Highcharts v4.2.4 - current version is 6.1.0. Could you update and check if the issue still exists? Thanks!

Header from v6.1.0:

```
/**
 * @license Highstock JS v6.1.0 (2018-04-13)
 *
 * (c) 2009-2016 Torstein Honsi
 *
 * License: www.highcharts.com/license
 */
'use strict';
(function (root, factory) { ....
```

**Comment by litera** [comment]
@pawelfus I've tested your highcharts stock jsfiddle which uses latest version and I've put it in strict mode , and yeah it didn't throw an error because newer versions actually only assign the `target` when it's not set. I've checked versions and versions < 5 have the problem:
```
    fireEvent = function (el, type, eventArguments, defaultFunction) {
        var e,
            hcEvents = el.hcEvents,
            events,
            len,
            i,
            fn;

        eventArguments = eventArguments || {};

        if (doc.createEvent && (el.dispatchEvent || el.fireEvent)) {
            e = doc.createEvent('Events');
            e.initEvent(type, true, true);
            e.target = el;

            extend(e, eventArguments);

            if (el.dispatchEvent) {
                el.dispatchEvent(e);
            } else {
                el.fireEvent(type, e);
            }

        } else if (hcEvents) {
        
            events = hcEvents[type] || [];
            len = events.length;

            // Attach a simple preventDefault function to skip default handler if called. 
            // The built-in defaultPrevented property is not overwritable (#5112)
            if (!eventArguments.preventDefault) {
                eventArguments.preventDefault = function () {
                    eventArguments.defaultPrevented = true;
                };
            }

            eventArguments.target = el;  // <== ERROR in strict mode
            ...
```
and version >= 5 use this
```
H.fireEvent = function(el, type, eventArguments, defaultFunction) {
            var e,
                hcEvents = el.hcEvents,
                events,
                len,
                i,
                fn;

            eventArguments = eventArguments || {};

            if (doc.createEvent && (el.dispatchEvent || el.fireEvent)) {
                e = doc.createEvent('Events');
                e.initEvent(type, true, true);
                //e.target = el;

                H.extend(e, eventArguments);

                if (el.dispatchEvent) {
                    el.dispatchEvent(e);
                } else {
                    el.fireEvent(type, e);
                }

            } else if (hcEvents) {

                events = hcEvents[type] || [];
                len = events.length;

                if (!eventArguments.target) { // We're running a custom event
                ...
```
So it only extends the event object when a custom event is being created out of a plain object instance.

**Comment by pawelfus** [comment]
That's correct. Should we close #8169 issue now?

**Comment by litera** [comment]
@pawelfus I've closed it thanks. But just for the info since I'll have to upgrade the lib. Are versions 5 and 6 compatible back to v4? Looking at changelog from 4.2.4 on it seems that mainly new features have been added, bugs killed but I don't see any breaking changes. Would you say that it should be safe to go from 4.2.4 to latest?

**Comment by pawelfus** [comment]
Yes, versions are compatible but minor things could have changed because of killed bugs. Check also `Upgrade notes` under releases (https://www.highcharts.com/documentation/changelog). If you find anything that looks strange, let us know: https://www.highcharts.com/support
