### ISSUE TITLE
Process flow with showing dataLabels breaks linked series interaction

### ISSUE THREAD

**Issue by mdhari** [highcharts/highcharts#5618]
#### Expected behaviour

- Initialize a blank highcharts chart with no series
- Add a series with a linked series (for a total of two series).
- Show the parent series, which also shows the linked series.
- Click on the parent series to show data labels.
- Click on the linked series to show it's data labels.

#### Actual behaviour

- Initialize a blank highcharts chart with no series
- Add a series with a linked series (for a total of two series).
- Show the parent series, which also shows the linked series.
- Click on the parent series to show data labels.
- **Linked series is no longer interactive. (Graph scales to indicate this)**

#### Live demo with steps to reproduce
http://jsfiddle.net/6ef9topw/

1. Click the "Step 1" button
2. Click the "Step 2" button
3. Hover over the blue and black lines to confirm interactivity via hover tooltip.
4. Left click on blue line.
5. Notice that black line is no longer clickable and the chart scales.

#### Affected browser(s)
Google Chrome 52.0.2743.116 (only targeting this currently)

**Comment by TorsteinHonsi** [comment]
@pawelfus I think this too is related to the Pointer logic. Once the first series is clicked (and Series.update has run), the tooltip for second series doesn't show. In Pointer.runPointActions, the hoverSeries is reported as 1A, even when we hover 2A. Consequently, when we click, the `hoverSeries` and `hoverPoint` are wrong, so we don't get the expected result.

**Comment by pawelfus** [comment]
*Internal note:*
In fact, issue was related to `series.visible`, which was misconfigured: param was set to false without hiding series - that cause `Pointer` to omit this 'hidden' series.
