### ISSUE TITLE
Highchart axis unicode(arabic) titles are inverted in chrome but not in firefox

### ISSUE THREAD

**Issue by Shanupa** [highcharts/highcharts#5623]
Arabic unicode character word is inverted or unordred in Chrome browser but in firefox, safari its okay. I recently found that Chrome has abandoned the SVG Fonts. I did various things but can't help with that. Please Help ....

Issue is in Chrome but not in firefox browser

Thank you

**Comment by pawelfus** [comment]
Hi @Shanupa, could you recreate issue on jsFiddle? We will take a look. Does is happen only in Highcharts, or is that a general issue with Chrome?

**Comment by sebastianbochan** [comment]
Unforunately I was not able to replicate your issue (http://jsfiddle.net/tv0scute). Could you update jsfiddle with your code?

**Comment by Shanupa** [comment]
Hi,
           Here by I have attached the screen shots where my issue occurs
and you can have the comparison with Firefox and Chrome. I am using
Highchart 2.1.7  and I have a doubt that in 4.2 your latest version is that
issue fixed? I tried to upgrade to the latest version but issues popped up
because this has many dependencies. I checked your changed log but you have
never responded neither people had reported those types of issues and
thought upgrading is not the right way to solve this. So please help me to
overcome this problem.

**Comment by Shanupa** [comment]
Hi,

Thank you very much I fixed the issue I have a problem with not setting
useHTML: true property when I set that, it worked. I compared your code and
differed it. For future this issue may come if this is not set Firefox will
work fine but Chrome will not because I recently found that Chrome has
removed SVG fonts. That's why this issue occurred. So I hope in later
versions this will be fixed because this happens if this property is not
set.

Further please tell me I want to upgrade high chart version from 2.1.7 to
4.2.  Tell me what kind of issues may come. replacing the library didn't
work. Some issues have occurred.  What are the major modifications I should
do.


Thanks,

**Comment by TorsteinHonsi** [comment]
Check out http://www.highcharts.com/docs/advanced-chart-features/internationalization about bidirectional text.

**Comment by Shanupa** [comment]
Hi,

Thank you very much  :) :)
