### ISSUE TITLE
Labels get put in the wrong order when using PhantomJS

### ISSUE THREAD

**Issue by nikentic** [highcharts/highcharts#5624]
#### Expected behaviour
This is the expected behaviour:
http://jsfiddle.net/qvsmyjho/19/

The columns should have the same values and labels in the browser as when you are using highcharts-converts.

#### Actual behaviour
This is how the output looks like.
https://i.imgur.com/WqddaeL.png

The exact same config is used for both, but the result is very different and plain wrong. The config can be found in the jsfiddle link above.

Any idea why this would happen? It's an unexpected result and I haven't been able to figure this out.

**Comment by pawelfus** [comment]
Hi @nikentic, could you make sure you are using current version of Highcharts in `highcharts-convert.js` (4.2.6)?

**Comment by nikentic** [comment]
Thanks for a quick answer @pawelfus ! I cannot seem to find it, only this one: https://github.com/highcharts/highcharts-export-server/blob/master/phantomjs/highcharts-convert.js
which specifies version 3.0.1. Can't find it here either: http://code.highcharts.com/

**Comment by nikentic** [comment]
UPDATE:

I updated both highcharts-convert and highcharts itself and it solved the problem. Thank you!

**Comment by pawelfus** [comment]
That's great! Let us know if you find any other issues :)
