### ISSUE TITLE
My Iframe dosen't display the whole chart  when i use IE Browser

### ISSUE THREAD

**Issue by khouaja** [highcharts/highcharts#5627]
#### Expected behaviour

Hi
i would like to display my coloumn chart  inside the iframe  which takes the url of my chart  as src
it works fine with chrome and firefox but not in IE 

please any workaround for this issue ?
#### Actual behaviour

when using IE 9 or 10  the chart appear but Xaxis labels are  overlapped
and when i use IE 8 or less series are not shown 
#### Live demo with steps to reproduce

attached the chrome layout against  IE LAYOUT

![ie-layout-10_9_8](https://cloud.githubusercontent.com/assets/9677991/18009916/8a0f66b2-6bae-11e6-9823-a90b73c02228.png)
![chrome-layout](https://cloud.githubusercontent.com/assets/9677991/18009929/97abab1e-6bae-11e6-82cd-2f6c31b2bcd1.png)

I use  highcharts 4.2.0
jquery-1.12.4.min.js
and creating the chart on server side  with asp.net (webforms not mVC)  and  then send html format  to the client with literal control
#### Affected browser(s)

IE

**Comment by TorsteinHonsi** [comment]
You you show us a live working demo?
