### ISSUE TITLE
Resizing chart vertically creates extra tick marks resulting in plot not sizing properly

### ISSUE THREAD

**Issue by tromgy** [highcharts/highcharts#5628]
When I resize a chart say from height of 300 to 600 I would expect everything increase proportionally, meaning the axes and plots will grow bigger but retain their relationship.

However, when resizing the chart vertically, I see that axes grow by adding new extra tick marks at the top, while plots do not grow as much as axes. This results in wasted space at the top of the chart.

Live demo with steps to reproduce:
http://jsfiddle.net/tromgy/gue1f03d/1/

Currently it has the height set to 600, and you can see the problem right away, but if you set container height to 300 px, the chart appears as it should be

Affected browser(s): Chrome, Microsoft Edge

I tried to track it down in code and it appears to lead to some problems in "adjustTickAmount"

**Comment by TorsteinHonsi** [comment]
It's a consequence of Highcharts trying to align the ticks of the two axes. You can disable that by setting `chart.alignTicks` to false, and disable grid lines on one of the axes to avoid clutter: http://jsfiddle.net/highcharts/gue1f03d/2/.
