### ISSUE TITLE
Logarithmic chart shows markers only (no line) if there are 0 values in data 

### ISSUE THREAD

**Issue by hmalekar** [highcharts/highcharts#5631]
#### Expected behaviour
Show show line and break where data is 0

#### Actual behaviour
Only markers are shown

#### Live demo with steps to reproduce
http://jsfiddle.net/39ekL6L8
 
Fiddle linked is the highcharts demo for logarithmic axis, with one of the data points made 0.

Same fiddle with version 4.2.1 works! It shows a line with a break for 0.

**Comment by jon-a-nygaard** [comment]
Thanks for reporting. We will try to fix it as  soon as possible.
