### ISSUE TITLE
No gaps in arearange or areasplinerange series

### ISSUE THREAD

**Issue by ecegeek** [highcharts/highcharts#5632]
#### Expected behaviour
Gap in series based on gapSize setting.

#### Actual behaviour
No gap for arearange or areasplinerange series types.

#### Live demo with steps to reproduce
I based off of "Setting the gap size to 2 introduces gaps for weekends in daily datasets" demo fiddle and just tweaked data to be range data and changed chart type:
http://jsfiddle.net/ecegeek/n57ogcor/
If you change type to "arearange" or "areasplinerange", no gap is shown.  Gap drawn for other series types though.

#### Affected browser(s)
Chrome 52.0.2743.116 (64-bit)
Firefox 47.0.1

**Comment by jon-a-nygaard** [comment]
Thanks for reporting.

_Internal Note: this seems to have been broken since v4.2.1_
