### ISSUE TITLE
Enhancement: Math.max, Math.min, etc. are stored in variables, but sometimes use via Math.<something>

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5633]
#### Expected behaviour
Always using mathMax instead of Math.max, etc.

#### Actual behaviour
Sometimes Math.max, Math.min, etc. are used. For example here:
https://github.com/highcharts/highcharts/blob/445f2b74aff1f82b09fee0d9f37eda16aeace4be/js/parts/Utilities.js#L971-L999
(Math.min, Math.max, Math.abs)

Math.pow is not defined yet used 10 times in Highcharts - shouldn't it be set to a variable?

**Comment by jon-a-nygaard** [comment]
@KacperMadej We are phasing out the math variables, in HC5 mathMax will be completely gone and we will use Math.max directly.

**Comment by jon-a-nygaard** [comment]
As I remember the conclusion to do so is because the Closure compiler will do this performance optimization anyway, and we will have cleaner code as a result.
