### ISSUE TITLE
Highstock flag shape urls break when upgrading from 4.2.5 to 4.2.6

### ISSUE THREAD

**Issue by acorncom** [highcharts/highcharts#5635]
#### Expected behavior
For flag series, I use a shape url to add custom icons to a chart.  I'm expecting the icon shape to show properly.

#### Actual behavior
A square box (the square shape) is displayed instead, with fill color filled in if specified

#### Live demo with steps to reproduce
Working (`v4.2.5`): http://jsfiddle.net/u2d30jqs/3/
Not working (`master`): http://jsfiddle.net/u2d30jqs/2/

#### Affected browser(s)
Chrome 52 (latest), Safari 9.1

**Comment by TorsteinHonsi** [comment]
Offending commit: https://github.com/highcharts/highcharts/commit/becec9e
