### ISSUE TITLE
Web Chart Title Export

### ISSUE THREAD

**Issue by biorhythm17** [highcharts/highcharts#5637]
Title of the chart is overlapping with the actual graph when exporting to PDF and PNG. Please help.
![cambodia_-_oecd_trade_facilitation_indicators](https://cloud.githubusercontent.com/assets/21349937/18111905/dac6dc02-6f55-11e6-8b1c-117b0161dafe.png)

**Comment by jon-a-nygaard** [comment]
@biorhythm17 Hi, I tried to replicate your case, but I did not get this issue. Can you provide us with a live demo? [JSFiddle](https://jsfiddle.net) is great for this purpose.
We will also be very thankful if you provide some information of which browser and operating system you experienced this on.
