### ISSUE TITLE
HighStock cropping part of the graph

### ISSUE THREAD

**Issue by egguy** [highcharts/highcharts#5643]
#### Expected behaviour

When the chart is zoomed at around 1 hour with column and spline data with an custom pointRange for the column, the xAxis should represent 1 hour of data in the full width of the chart.

![without-pointrange](https://cloud.githubusercontent.com/assets/186777/18126283/c411033c-6f7a-11e6-8257-f262ca615fe6.png)
#### Actual behaviour

There's  1 hour of data displayed, but at the center of the chart, the left and right part are left blank.
It only happen when a pointRange is specified on the column (on the series data, or plotOption).

![bug-line](https://cloud.githubusercontent.com/assets/186777/18126237/9476e52e-6f7a-11e6-956a-61554e8fc813.png)
#### Live demo with steps to reproduce

http://jsfiddle.net/myLLth9r/1/

Zoom to 1 hour anywhere on the chart
#### Affected browser(s)

Chromium 37.0.2062.120
Firefox recent version

**Comment by pawelfus** [comment]
Thank you for reporting!

I think this is generall issue, not only related to Highstock: http://jsfiddle.net/myLLth9r/2/

**Comment by TorsteinHonsi** [comment]
> the left and right part are left blank

These blank parts represent the padding that is half the `pointRange`. This padding is added to make room for the whole columns as per the `pointRange` setting.
