### ISSUE TITLE
Highcharts adding extra tick interval on dual axis graph

### ISSUE THREAD

**Issue by tsjoberg** [highcharts/highcharts#5644]
#### Expected behaviour

Sometimes when you have a chart that has dual axis - the default options seems to add an extra tick higher (ex. ticks are 1, 2, 3, 4 - but will add tick 5 after tickPositioner is called). If you perform redraw() or reflow the chart by sizing the window differently the ticks are then correct. Not sure if this has to do with smaller widths and/or alignTicks post processing.

#### Actual behaviour

Bad chart:

![image](https://cloud.githubusercontent.com/assets/7171881/18133473/c3ded0ea-6f68-11e6-8a0e-61460dcfd00f.png)

Expected chart after slight window resize:

![image](https://cloud.githubusercontent.com/assets/7171881/18133506/e1e8f2f0-6f68-11e6-8341-8de434f266c4.png)

#### Live demo with steps to reproduce
template: http://jsfiddle.net/nbo3tye1/

#### Affected browser(s)
All

**Comment by oysteinmoseng** [comment]
With your example I could reproduce this when resizing to a width small enough to affect chart title/subtitle height. Here is an example showing the bad behavior without resizing needed: http://jsfiddle.net/k8h6tqz2/

**Comment by TorsteinHonsi** [comment]
See http://api.highcharts.com/highcharts/chart.alignTicks
