### ISSUE TITLE
Highcharts Drilldown loading incorrect data

### ISSUE THREAD

**Issue by krishna2016git** [highcharts/highcharts#5645]
#### Expected behaviour
Able to reproduce the issue in the demo chart. Click on Internet Explorer. It loads few version details. Click on Safari. It loads few version details. When we click back on Internet explorer, its showing the versions from Safari data as well because few versions of IE and Safari versions are same.

#### Actual behaviour
It should give the actual versions data

**Comment by sebastianbochan** [comment]
Fixed in the master branch:
- http://jsfiddle.net/hm7dp7g1/
