### ISSUE TITLE
x-range study points disappearing

### ISSUE THREAD

**Issue by peterchoo** [highcharts/highcharts#5647]
#### Expected behaviour
All points where x and x2 range intersects with the viewing area.

#### Actual behaviour
Points where the x value is lower than the threshhold disappear.

#### Live demo with steps to reproduce
http://jsfiddle.net/bpqpy0ko/1/

Reduce the size of the brush/navigator (Click 1W) and move the navigator to the start of the timeline.  Then slowly move it to the right and watch the bars disappear when the left edge goes off the left of the chart area.

_Edit: I have just experimented with the data array length.  It appears that having 51 points in the array causes x < threshold to disappear: http://jsfiddle.net/bpqpy0ko/2/ - where as having 50 points doesn't: http://jsfiddle.net/bpqpy0ko/3/_

#### Affected browser(s)
Chrome, Firefox on Linux

**Comment by peterchoo** [comment]
Having done a little more digging, this looks like an issue with `cropThreshold`.

What I need to change in the x-range plugin is the function which decides whether a point should be shown or not, to add something along the lines of:

```javascript
isPointShown(point, limits) {
  return x.x < limits.max && x.x2 > limits.min;
} 
```

**Comment by pawelfus** [comment]
How about setting [`cropThreshold`](http://api.highcharts.com/highcharts/plotOptions.series.cropThreshold) ? For example: http://jsfiddle.net/bpqpy0ko/4/

**Comment by peterchoo** [comment]
`cropThreshold` would work if we knew the max dataset size, and knew it wouldn't cause any particular performance issues.  Unfortunately we are currently looking at having 10,000+ data points,a nd are worried about performance. 

As suggested by @TorsteinHonsi in his commit which closed this issue, I had already come up with a `cropData` override which searches both the `xData` and `x2Data` arrays.  This doesn't work out ideally, as if a data point with a low index has a high x2 value, and happens to be shown, then all points in between shall be rendered.

I'll keep looking for a better solution.
