### ISSUE TITLE
 How to implement the following figure

### ISSUE THREAD

**Issue by huxiaohuxiao** [highcharts/highcharts#5648]
#### How to implement the following figure？

![image](https://cloud.githubusercontent.com/assets/14835202/18165263/d9927bee-7076-11e6-9c14-e80d2ee23240.png)

thanks

**Comment by sebastianbochan** [comment]
This is our bug tracker. For support questions, please send us an email / create a topic on our forum or stackoverflow.

Further information about support: 
 - http://www.highcharts.com/support
