### ISSUE TITLE
Refresh map

### ISSUE THREAD

**Issue by AndrewKralovec** [highcharts/highcharts#5650]
#### Expected behaviour
Trying to refresh Chart

#### Actual behaviour
Chart does not refresh/change

#### Live demo with steps to reproduce
http://plnkr.co/edit/mTgMCDlK2MQu9fWTp8SC?p=info

#### Affected browser(s)
All

#### Details 

I made an angular2 application that uses the angular2-highcharts component. It works great but I want to be able to change info of the chart and render the new chart. However, the angaulr2-highcharts library and doesn't bind to initial options. The developer who made the made the wrapper library said it works the same as Highcharts  (with jquery, javascript, ect)  and I could post this question here. 
Thanks so much for taking the time to look at this.

**Comment by pawelfus** [comment]
For changing categories, use [`Axis.setCategories()`](http://api.highcharts.com/highcharts/Axis.setCategories) method. For updating Axis in general, use [`Axis.update()`](http://api.highcharts.com/highcharts/Axis.update). Highcharts lib doesn't watch the changes in the original object, so use API methods.

Demo for you: http://plnkr.co/edit/n8kle107iRR5gxWoNg4N?p=preview
