### ISSUE TITLE
Printing multiple charts not working

### ISSUE THREAD

**Issue by inad9300** [highcharts/highcharts#5651]
#### Expected behaviour
Highcharts should be able to print multiple charts as one image using the offline mode.

#### Actual behaviour
A file with the same height and a bigger width is downloaded, completely black. Alternatively, nothing happens at all (see the browsers section below).

#### Live demo with steps to reproduce

http://jsfiddle.net/highcharts/eatqca8n/ - solution proposed in http://www.highcharts.com/docs/getting-started/frequently-asked-questions#export-multiple

#### Affected browser(s)
Google Chrome - Version 53.0.2785.89 m (64-bit)
Google Chrome Canary - Version 55.0.2847.0 canary (64-bit)
Opera - 39.0
Vivaldi - 1.3.551.30 (Stable channel) (32-bit)
Microsoft Edge - 25.10586.0.0 - _In this case, nothing happens at all when clicking on the button, as oppose to downloading a black image_.

#### Unaffected browser(s)
Mozilla Firefox - 48.0.2
Internet Explorer - 11.545.10586.0

All the browsers were running on Windows 10 at the moment of testing.

**Comment by TorsteinHonsi** [comment]
It's already fixed in the master: http://jsfiddle.net/highcharts/eatqca8n/17/

**Comment by inad9300** [comment]
Any approximation of a release date?

**Comment by TorsteinHonsi** [comment]
Yes, probably within a few weeks. But you can safely use the workaround until then (an after too).

**Comment by inad9300** [comment]
Not sure about where to place that bit, but a few weeks sounds like a reasonable time to wait.

**Comment by TorsteinHonsi** [comment]
> Not sure about where to place that bit

See http://jsfiddle.net/highcharts/gd7bB/, line no 13.

**Comment by inad9300** [comment]
I have detected several more problems with the [multiple export](http://www.highcharts.com/docs/getting-started/frequently-asked-questions#export-multiple):
- It doesn't work at all for large amounts of data. I'm displaying data for a certain time interval, and as soon as I select a reasonably big one, the multiple export doesn't work. Nothing is displayed into the console. Single downloads still work. All browsers are affected.
- It doesn't support PDF format (`application/pdf` type), despite the description given in the documentation linked above. Again, all browsers are affected.

If you prefer that I create separate issues for these two problems, please let me know.

I would also like to ask if there is any plan to integrate this feature into Highcharts, as the documentation indicates that "Currently this isn't implemented in the core".

Thanks.

**Comment by TorsteinHonsi** [comment]
Hi, I have moved the sample over to a [GitHub powered location](http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/exporting/multiple-charts/) so it now becomes part of our regression test suite. 

As you can see from the new demo, I successfully added a PDF export button.

With [a little modification](http://jsfiddle.net/highcharts/tpcn00q3/) it also works with a line chart with 10k data points.

**Comment by inad9300** [comment]
Thanks a lot for the feedback! I'll try to adapt your updated examples to my case. Does the same thing work for offline exporting?

**Comment by inad9300** [comment]
OK, I see now that you just changed the type to `application/pdf`. I had tried that already, and indeed a PDF is downloaded, only that later it is impossible to open it. This happens even when all the other formats (PNG, JPEG, SVG) work just fine. It is possible to reproduce this problem applying the same type to the example using offline exporting in http://jsfiddle.net/highcharts/eatqca8n/. Chrome, Opera, Firefox... won't be able to open it; Edge will, but they are smartly treating it as an image (they point to the file from the `src` attribute of an `img` tag).

Regarding the fact that I'm unable to download charts with many points on them (>10k, sometimes >>>10k), I could test your "artificial-data-generator loop" applied to the offline example, and it seems to work nicely there (you need to wait for a while, of course, but you get an image at the end).

Coming back to my error, using Chrome Dev Tools you can tell that there is a big difference in the network activity in the two cases. If a small amount of data is involved, one can see a request starting with `blob:` going on, which returns some SVG. With that, you can download your file. On the other hand, if many data points are involved, several requests starting with `data:image/png;base64,` (regardless of the type selected) can be seen, but no prompt is displayed to the user asking for a place to put any file, and of course nothing is downloaded at all.
