### ISSUE TITLE
Update multiple series

### ISSUE THREAD

**Issue by AngryElephant** [highcharts/highcharts#5652]
Hi,

Is there any way to update multiple series at the same time ?

 I would like to give a new series array :

    [{
        name: 'serie 1',
        data: []

    },{
        name: 'serie 2',
        data: []
    }]

and that the chart redraw with the new data.

Instead for now i have to get the series length and iterate because the api allow only updates one by one :

    chart.series[1].setData([])

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
