### ISSUE TITLE
Behavior of HighMaps colors differs when legend is disabled.

### ISSUE THREAD

**Issue by hjnilsson** [highcharts/highcharts#5654]
#### Expected behaviour
ColorAxis has the same colors regardless of if legend is visible.

#### Actual behaviour
When legend is disabled, the chart gets different colors (does not seems to respect the `stops` variable?).

#### Live demo with steps to reproduce
Standard demo from Highcharts.com: http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/maps/demo/heatmap/

Same demo with `legend: { enabled: false }` added: http://jsfiddle.net/5q28Luuv/

Notice that the red is entirely gone from the chart.

#### Affected browser(s)

Tested in Safari & Chrome on OSX.

**Comment by pawelfus** [comment]
Hi @hjnilsson - thanks for reporting! Actually, this is a duplicate of #5205.
