### ISSUE TITLE
Highcharts does not spline for series with minimum values.

### ISSUE THREAD

**Issue by aatifbandey** [highcharts/highcharts#5657]
Expected behavior
For series with very less values highchart should draw series. 

 Actual behavior
i have a spline chart with upto 100 data points and many null values for time series, the max values goes upto 600K and min goes upto 1 or 2. Library doesn't draw point for minimum series.

**Comment by pawelfus** [comment]
Hi @aatifbandey,

Could you recreate issue on jsFiddle? We will check this. 

Thank

**Comment by aatifbandey** [comment]
https://jsfiddle.net/wevgdkda/

**Comment by aatifbandey** [comment]
@pawelfus there wiill be around 50k data length for each series.

**Comment by pawelfus** [comment]
Okay, but your demo works fine: https://jsfiddle.net/wevgdkda/1/ or do I miss something?

**Comment by aatifbandey** [comment]
Yes you are right i think i am missing something let me check, thanks :+1:
