### ISSUE TITLE
How to create oval shaped venn diagram using high charts

### ISSUE THREAD

**Issue by tonytomk** [highcharts/highcharts#5659]
Hi Team,

We have created 4 data set Venn diagram with highcharts, but the result is displaying as circle,
Is there any way we can make in the elliptical way/oval shaped.
tried changing marker symbol to ellipse from circle but its not working.
http://jsfiddle.net/AyqzZ/210/

any help will be appreciated.

**Comment by RaghuRangaraj** [comment]
Same here, Having the same issue in drawing ellipse. Need help on the same

**Comment by pawelfus** [comment]
Hi,

For support related questions, please contact with us directly by email, or create a new topic on our forum. More details you can find [here](http://www.highcharts.com/support).

Kind Regards,
Paweł :)
