### ISSUE TITLE
How to show Multiple labels in Highcharts Venn diagram

### ISSUE THREAD

**Issue by RaghuRangaraj** [highcharts/highcharts#5660]
#### Expected behaviour
Need to show label for intersection and union in Venn diagram, but as of now only 1 label can be shown

#### Actual behaviour
No option to show multiple label for venn diagram

#### Live demo with steps to reproduce
http://jsfiddle.net/AyqzZ/78/

Need help on the same. Thanks in advance. :)

**Comment by tonytomk** [comment]
I have tried with 4 data sets there also I am facing the same issue :(

**Comment by pawelfus** [comment]
Hi,

For support related questions, please contact with us directly by email, or create a new topic on our forum. More details you can find [here](http://www.highcharts.com/support).

Kind Regards,
Paweł
