### ISSUE TITLE
Polar chart - setExtremes - wrong points

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5664]
#### Expected behaviour

Out of range points, should be hidden
#### Actual behaviour

Point from out of range is displayed, without marker
#### Live demo with steps to reproduce

http://jsfiddle.net/highcharts/dd32s6ed/1/
#### Affected browser(s)

All browsers

**Comment by pawelfus** [comment]
Related to #5073 (yAxis extremes)

**Comment by ftcvlad** [comment]
the issue is related to Min and Max, hence setExtremes. Just setting Min/Max when polar chart is created produces same error

**Comment by TorsteinHonsi** [comment]
#### Workaround

Set the prototype `cropShoulder` property to 0 and the `cropThreshold` option to 1: http://jsfiddle.net/highcharts/dd32s6ed/3/.

#### Proposed solution
Make this happen automatically for any series in a polar chart.

**Comment by pawelfus** [comment]
Another example: http://jsfiddle.net/mma4ja10/
