### ISSUE TITLE
Adding new points quickly in spline throws errors and the chart is drawing incorrectly

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5665]
#### Actual behaviour
In a spline chart when adding new points quickly, with shifting - Highcharts throws errors.
If the chart's animation is turned off errors does not occur.

#### Live demo with steps to reproduce
http://jsfiddle.net/zuw4camL/6/

**Comment by pawelfus** [comment]
*Internal note:*
It looks like in method `addPoint(point, redraw, shift, animation)` the `animation` param is omitted. 

The culprit here is a long running animation (1sec), and updated every 0.4 sec. When changing animation in chart options, it works fine: http://jsfiddle.net/zuw4camL/8/

**Comment by pawelfus** [comment]
There's still one question:

What should we do if user adds points on a chart with interval 400, and sets duration for example to 2000?
