### ISSUE TITLE
afterAnimate event of a series not fired when boost is in play

### ISSUE THREAD

**Issue by mattwang75** [highcharts/highcharts#5666]
#### Expected behaviour
After a series is displayed, the afterAnimate event shall be be fired, whether performance boost.js module is in play or not.

#### Actual behaviour
I include boost.js in my import stack.  When the number of data points is less than 5000 (i.e. boost is not in play), my handler is invoked as expected after my series is displayed.  When the number of data points is >= 5000 (i.e. boost is in play), my handler is not called, suggesting afterAnimate event is not fired in this case.

#### Live demo with steps to reproduce
http://jsfiddle.net/junf8L8t/19/

1) Notice line 3 is currently set to produce 4999 data points.   This demonstrates afterAnimate event is fired.
2) Change line 3 to make 5000 data points.  This demonstrates afterAnimate event is *not* fired.
3) Comment out import of boost.js.  This demonstrates afterAnimate event is fired again (even though we keep it at 5000 data points).

So take all three observations together, it's pretty clear boost.js is the culprit here. 

#### Affected browser(s)
I tested in Chrome and FF.

**Comment by oysteinmoseng** [comment]
The boost module does not animate the same way as regular Highcharts, as it's not using SVG, but HTML5 canvas instead.

Instead of an `afterAnimate` event, the boost module will fire a `renderedCanvas` event after the points have been drawn. You could listen to that event for the same effect. [Example](http://jsfiddle.net/junf8L8t/20/)

**Comment by mattwang75** [comment]
Thanks for the workaround.  I understand boost is not officially released yet.  When it gets merged with core Highcharts, I hope this event won't be named differently (otherwise at least the future API doc will have to mention it).
