### ISSUE TITLE
upgrade to latest canvg with rgbcolor 1.0.0

### ISSUE THREAD

**Issue by graingert** [highcharts/highcharts#5667]
#### Expected behaviour
Higcharts is licensed under an unambiguous license

#### Actual behaviour
Higcharts is licensed under an ambiguous license

#### Live demo with steps to reproduce
```sh
git clone git@github.com:highcharts/highcharts.git
```
A wild lawyers appear and be all like: 'nope'.

#### Affected browser(s)
All

`<serious>`
rgbcolor recently switched from a 'feel free' license,  to the MIT License.
The 'feel free' license only allowed arbitrary usage (if and only if you 'felt' like it) but doesn't allow sublicensing. The MIT license does allow sublicensing.

**Also it supports CSS4 and UMD.**

https://github.com/yetzt/node-rgbcolor
https://github.com/yetzt/node-rgbcolor/pull/7
`</serious>`

**Comment by TorsteinHonsi** [comment]
We used canvg and RGBColor to support Android 2.x that was missing SVG support. Since that is not needed anymore, we have removed this in Highcharts 5, which will be out in a few weeks.

**Comment by graingert** [comment]
It's also for client side png export...

**Comment by TorsteinHonsi** [comment]
Oh, yes, that too...

@oysteinmoseng In the HC5 branch, we should stop relying on our canvastools. Instead either load updated versions of RGBColor and canvg from a CDN or host them on our own.

**Comment by oysteinmoseng** [comment]
@TorsteinHonsi 
CanVG seems to require the following files:
`rgbcolor.js` 8kB
`StackBlur.js` 18kB (we can ignore this since we don't use Blur functions)
`canvg.js` 61kB (minified)

They are all available on [GitHub](https://github.com/canvg/canvg), but I definitely vote for hosting them ourselves to avoid all kinds of 3rd party and escrow issues. Since we are talking about ca 70kB I guess it makes sense to load them on demand only. Should we add a second API option to define the path to `RGBColor.js`, and redefining the existing `canvasToolsURL` option to point to `CanVG.js`? Or we could deprecate `canvasToolsURL` and introduce a new `canvgURL` option.

**Comment by graingert** [comment]
@oysteinmoseng @TorsteinHonsi I've got a PR for browserify/webpack/commonjs users to allow them to inject whatever canvg library they choose: https://github.com/highcharts/highcharts/pull/5639

**Comment by graingert** [comment]
> They are all available on GitHub, but I definitely vote for hosting them ourselves to avoid all kinds of 3rd party and escrow issues. Since we are talking about ca 70kB I guess it makes sense to load them on demand only.

This is already the case, you just need to update your bundle

**Comment by oysteinmoseng** [comment]
@graingert Except the bundle has been removed as part of the HC5 update. Maybe we should put it back, then @TorsteinHonsi, and just kill the renderer?

**Comment by graingert** [comment]
@oysteinmoseng why was the bundle removed it's still used here: https://github.com/highcharts/highcharts/blob/master/js/modules/offline-exporting.src.js#L228

**Comment by graingert** [comment]
Also it's still in the build: https://github.com/highcharts/highcharts/blob/master/gulpfile.js#L504-L531

Is the HC5 update not in master yet?

**Comment by oysteinmoseng** [comment]
@graingert No, the HC5 update is not in master yet. As for the use in offline-exporting, in the HC5 update we linked to an older version already existing on our CDN and removed the bundle from future releases. Of course that won't work now that we'll have to update it.

**Comment by graingert** [comment]
@oysteinmoseng ah I assume that means changes to your gulpfile, can I see those changes so I can rebase https://github.com/highcharts/highcharts/pull/5642 ?

**Comment by oysteinmoseng** [comment]
@graingert 'krevje' is the HC5 branch, all changes are available there. We're revamping the whole build system, though, so not sure where this would fit in. @jon-a-nygaard, do you have any input?

**Comment by TorsteinHonsi** [comment]
If we provide a URL option for these files, I suggest we don't create the canvas-tools bundle anymore, but just serve the original versions of RGBColor and canvg from our CDN. It will make upgrading easier, and implementers can exchange them for their own versions. 

Another, possibly cleaner, way to do it is to not provide lazy-loading at all, but just to require that those files are loaded beforehand. And perhaps throw a friendly warning in the console when they're not. 

Also, we will face the same question on dependencies now that we are integrating PDF export through (modified) jsPDF and svg2pdf.js.

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng We'll discuss this across the team, no need to take action before HC5.

**Comment by graingert** [comment]
It would be great if you consider cases where users already have a module
bundler, but don't want to just put the module on .window

**Comment by graingert** [comment]
@TorsteinHonsi how does this work? What do I need to do to upgrade?

**Comment by oysteinmoseng** [comment]
@graingert If you are not using offline-exporting you won't need to make any changes, RGBColor is simply not loaded. 

If you are using the offline-exporting module, the difference is that RGBColor, CanVG and a few other dependencies are now loaded on-demand if not present on the `window` object. By default they are loaded from our CDN at [code.highcharts.com](http://code.highcharts.com), but this can be changed by setting the [exporting.libURL](http://api.highcharts.com/highcharts/exporting.libURL) option. The libraries have been updated to use the latest versions.

**Comment by graingert** [comment]
I don't want to load them on demand. I want to use webpack to load them
from my own server

**Comment by oysteinmoseng** [comment]
@graingert Right, the offline-exporting module will use the versions of RGBColor and CanVG that are present on `window` if any, so you should be able to load your own versions using webpack and set them on `window` before calling any export functions. There will then be no loading on demand.

**Comment by graingert** [comment]
I don't want to load them into window. I want to use regular commonjs

**Comment by oysteinmoseng** [comment]
@graingert I see, that's not supported at the moment. We could easily add support for loading them on the Highcharts object as well, if that helps?

**Comment by graingert** [comment]
I'd like to be able to load the offlineExporting module like:

```js
import canvg from 'canvg';
import rgbcolor from 'rgbcolor';
import offlineExporting from 'highcharts/path/to/offlineExporting';

function configureHighcharts(hc) {
  return hc.use(new OfflineExporting(canvg, rgbcolor));
}
```

So that everything is nice and pure functional

**Comment by graingert** [comment]
out of interest have you updated the canvg module on highcharts.com to the one with the MIT license?

**Comment by oysteinmoseng** [comment]
@jon-a-nygaard FYI.
@graingert Thanks for the feedback. The new RGBColor library still has a "Use it if you like it" license, it seems like only the node module has technically been dual licensed under MIT.

**Comment by graingert** [comment]
Yes, please use npm to pull in this module
