### ISSUE TITLE
Boost x-value in tooltip is incorrect

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#5672]
#### Expected behaviour

x-value in tooltip should show point with it's x-value.
#### Actual behaviour

x-value in tooltip increases when moving cursor over the chart.
#### Live demo with steps to reproduce

http://jsfiddle.net/kssc5vkp/

Hover any of points, x-value increases starting from last index. I think similar issue has been reported (and fixed) already.

**Workaround**
Use `[x, y]` structure for points, demo: http://jsfiddle.net/kssc5vkp/1/

**Comment by Izothep** [comment]
+1

**Comment by TorsteinHonsi** [comment]
This is fixed in the new GL-based Boost module. If you have the fix ready @christer perhaps you can just port it to the master and close this?
