### ISSUE TITLE
High precision width needed when computing chart width

### ISSUE THREAD

**Issue by ming-codes** [highcharts/highcharts#5673]
#### Expected behaviour

Charts should stay side by side of each other.
#### Actual behaviour

Charts are stacked on each other.
#### Live demo with steps to reproduce

http://codepen.io/lightblade/pen/amvpbb

Note that the 2 children's width add up to 1px more than the parent's width. This is why it's wrapping.
#### Affected browser(s)

Chrome

**Comment by pawelfus** [comment]
Hi @ming-codes 

Thank you for reporting. I think here we have two cases:

- border is not counted into width for flex, you don't have to use Highcharts to reproduce your issue: http://codepen.io/fsh/pen/ZpbNWA
- still, even when border is disabled it may happen: http://codepen.io/fsh/pen/wzKbKG (1001px width)
 
*Internal note:*
We can try to use `getBoundingClientRect()` (except <IE9) in `getStyle()` method - it returns subpixel info, compare results: http://codepen.io/fsh/pen/wzKbKG
