### ISSUE TITLE
Range selector instantiated after load event won't automatically update button state

### ISSUE THREAD

**Issue by khoomeister** [highcharts/highcharts#5674]
#### Expected behaviour

If one instantiates the range selector manually, the buttons' state should update (e.g. All button).

#### Actual behaviour

The buttons' state doesn't update.

#### Live demo with steps to reproduce
1. https://jsfiddle.net/khoomeister/b1orgrkc/4/
2. Click any enabled button on the range selector.
3. Notice the "All" button stays disabled.

#### Technical issue

https://github.com/highcharts/highcharts/blob/b7f2409f7dc9de3dced3e171613bc1e57462ed6a/js/parts/RangeSelector.js#L287-L299

The range selector binds events in the chart's load event.  If one instantiates the range selector manually after the chart is loaded, it won't automatically update button states.

**Comment by oysteinmoseng** [comment]
Try like [this](https://jsfiddle.net/b1orgrkc/7/).

**Comment by khoomeister** [comment]
@oysteinmoseng in my case, I need to be able to create the stock chart with the range selector disabled, and then enable it at a later stage if required.

**Comment by oysteinmoseng** [comment]
@khoomeister Would the above solution not do that for you? [Example](https://jsfiddle.net/b1orgrkc/9/).

**Comment by khoomeister** [comment]
OK that would work, it's hacky that's all.

**Comment by oysteinmoseng** [comment]
@khoomeister Highcharts 5 will introduce a `chart.update` function you can use for this. It will be released in a few weeks.

**Comment by khoomeister** [comment]
Awesome, thx @oysteinmoseng!
