### ISSUE TITLE
Feature request: Highmaps / Map chart allow interacting with null points

### ISSUE THREAD

**Issue by hjnilsson** [highcharts/highcharts#5676]
When you have a Highmaps chart with a dataset that contains null values (ie. unknown data), you cannot (from what I can tell) make it show tooltips for this data. This works extremely poorly for large maps (for example, a county map) where the user don't know all the map areas.  Look on this map for example: http://jsfiddle.net/2Lp3vuuz/1/

Tell me which the 2 states black states. Now imagine the same on a county map with 1000+ map points.

There should be some way to still show a tooltip with the name of the map point. Even if there is no data for the point.
#### Expected behaviour

Map points with `null` values should show tooltips and respect events as all other points. This could be behind a configuration option. (for example `allowInteractingWithNulls: true`). These points should also react to hover and select events.
#### Actual behaviour

You cannot enable tooltips or click events to trigger for null points in a map. Null points do not react to hover & select events.
#### Live demo with steps to reproduce

http://jsfiddle.net/2Lp3vuuz/1/

Look at the map, hover over any of the black state. The name of the state is not shown.

Click on any of the black states, and no alert appears. Clicking on the states with values makes an alert appear.
#### Workaround

You can set the value of all points with `null` to -1000 or some other magic value. Then set the axis manually, and have custom tooltip handlers that filters out the magic values.

**Comment by TorsteinHonsi** [comment]
Thanks for the suggestion! The implementation was really simple as you can see. 

The following snippet can be used to allow the same feature in v4.2.6:
```js
	Highcharts.seriesTypes.map.prototype.pointClass.prototype.onMouseOver = function (e) {
		clearTimeout(this.colorInterval);
		if (this.value !== null || this.series.options.nullInteraction) { // docs, added with "next" version
			Highcharts.Point.prototype.onMouseOver.call(this, e);
		} else { //#3401 Tooltip doesn't hide when hovering over null points
			this.series.onMouseOut(e);
		}
	}
```
[View live demo](http://jsfiddle.net/highcharts/2Lp3vuuz/2/).

Now you just have to add a [tooltip.pointFormatter](http://api.highcharts.com/highcharts/tooltip.pointFormatter) to return something meaningful for the null points.

**Comment by sebastianbochan** [comment]
It looks like option does not work since v5.0

Demo:
- http://jsfiddle.net/vc6xmsk3/

**Comment by engrmartins** [comment]
I have used the noData attribute in highcharts to display an image when there is no data, How do I achieve this on highmaps?

**Comment by pawelfus** [comment]
Did you try the same way @engrmartins ? See: https://jsfiddle.net/BlackLabel/u5tb1ezo/1/ - note that both, map and the data must be missing.
