### ISSUE TITLE
Bubble shadows doesn't rendered in right place

### ISSUE THREAD

**Issue by kayran** [highcharts/highcharts#5677]
#### Expected behaviour

The bubble shadows ever been rendered near the own bubble. 
#### Actual behaviour

Sometimes, when remove and reinsert a value of a xAxis in bubble chart, the hover shadow of the bubbles were wrong setted up, like in the image below. I think it occurs because the transition didn't terminate before the second click. It occurs when i have 2 values in xAxis and i remove and insert fast one of then.

![bug_highcharts_issue](https://cloud.githubusercontent.com/assets/474481/18439952/a1b36156-78dd-11e6-9bdd-7ff340fa325a.png)
#### Affected browser(s)

Was tested in Google Chrome

**Comment by pawelfus** [comment]
Hi @kayran - thank you for reporting. Could you setup a simple jsfiddle with this issue? We will check this.

Thanks!
Paweł

**Comment by KacperMadej** [comment]
Please reopen if needed or when the problem will be reproduced.
