### ISSUE TITLE
tooltip not show all series at first time

### ISSUE THREAD

**Issue by dumingxin** [highcharts/highcharts#5680]
#### Expected behaviour

I have three lines on one charts,tooltip can show three lines when clicked it.
#### Actual behaviour

tooltip only show one line when clicked it first time,it will show three lines when clicked it again.
#### Affected browser(s)

Android 6.0 webview

**Comment by dumingxin** [comment]
vedio address https://youtu.be/Hy_943R-92w

**Comment by pawelfus** [comment]
Hi @dumingxin and thank you for reporting the issue. Could you recreate this on jsFiddle? We need something which recreates the issue to be able to debug this. Does it happen also for browsers?

**Comment by KacperMadej** [comment]
Please reopen if needed or when the problem will be reproduced. 

Since the issue was reported tooltip and pointer code were improved - if it's not possible to create a live demo, is the problem still showing?
