### ISSUE TITLE
Highstock candlesticks update point cause candlestick stacking

### ISSUE THREAD

**Issue by qingweibinary** [highcharts/highcharts#5684]
#### Expected behaviour
when update point, new point should replace old point

#### Actual behaviour
When inspecting dom, multiple <path> keep stacking on the same position

#### Live demo with steps to reproduce
I am not able to reproduce in jsfiddle yet, I would like to know if I set some config wrongly?

Here's a screenshot

<img width="821" alt="screen shot 2016-09-14 at 11 59 54 am" src="https://cloud.githubusercontent.com/assets/14971922/18499626/2a8ef97c-7a73-11e6-8d24-24e0468594be.png">

Observe the last candle, there's mixing of red and green

My code is basically like this

```
var i = chart.series[0].data.length - 1
chart.series[0].data[i].update([time, open, high, low, close]);
```

**Comment by pawelfus** [comment]
Hi @qingweibinary,

Thank you for reporting the issue. If you can not recreate issue in jsFiddle then maybe you have old version of Highstock? Current release is 4.2.6. 

If this is not the case, then I suggest to contact with us directly by email (see [support details](http://www.highcharts.com/support)). We will try to figure out what may happen there.

Thanks,
Paweł

**Comment by qingweibinary** [comment]
@pawelfus 

I am so sorry to bother you guys, I think it's mostly my own fault, I was passing irregular data

assuming this array is the x values of each ohlc

[10, 20, 30, 40, 50, 51, 52, 53, 54]

so 50, 51, ... 54 is too close, but different, and thus highstock treat them differently and render each of it

I think this is the expected behaviour?

**Comment by pawelfus** [comment]
Yes, this is the expected behaviour for `xAxis.ordinal = false` axis. If you have points with difference = 1 on xAxis, then for a datetime xAxis it means 1ms between two points (just like it looks on your chart).
