### ISSUE TITLE
Highstock: Small bar in vertical scrollbar gets outside of visible zone.

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5686]
#### Expected behaviour
The bar that you drag should never be even partially outside of visible area.

#### Actual behaviour
It is partially outside of visible area. If it's small then it's not visible at all.

#### Live demo with steps to reproduce
http://jsfiddle.net/kd30omep/1/

1. The bar is not fully visible - it's almost not visible.

_Internal note: It looks like the issue is visible when minWidth is bigger than calculated width_
Demo: http://jsfiddle.net/kd30omep/2/

**Comment by KacperMadej** [comment]
It's also visible for horizontal scrollbar: http://jsfiddle.net/kd30omep/4/

**Comment by pawelfus** [comment]
[v4.2.5](http://jsfiddle.net/kd30omep/8/) vs [4.2.6](http://jsfiddle.net/kd30omep/7/)
