### ISSUE TITLE
labelLength is not defined

### ISSUE THREAD

**Issue by Negodyaj** [highcharts/highcharts#5687]
My charts become broken after this commit: Grid axis study: Refactored to re-use tick label length. (https://github.com/highcharts/highcharts/commit/f6559d67ce39964f8233792656fe2304e5970aab)

now I see an exception in console:
ReferenceError: labelLength is not defined

it's broken on this line:
width: (labelLength > chart.chartHeight * 0.5 ? chart.chartHeight * 0.33 : chart.chartHeight) + PX

**Comment by pawelfus** [comment]
Thanks for reporting the issue!

Please, keep in mind, that the master branch is a branch which can have bugs, so don't use direct url (http://github.highcharts.com/highcharts.js) in your sites/apps.

**Comment by Negodyaj** [comment]
And what link should I use instead?)

**Comment by oysteinmoseng** [comment]
@Negodyaj Yes, or to be even safer you can link to a specific version: http://code.highcharts.com/4.2.6/highcharts.js

**Comment by Negodyaj** [comment]
Thanks!
