### ISSUE TITLE
Drilldown and Up behaviour buggy in 4.2.6

### ISSUE THREAD

**Issue by avdaredevil** [highcharts/highcharts#5688]
**NOTE**: This bug was introduced in 4.2.6 and DID NOT exist in 4.2.5

#### Expected behaviour
Chart exists with 2 bars
Drill down into a first bar (let's call it `A_BAR`)
Dril up -> add Dynamic data

Should see 3 bars `A_Bar`, `B_Bar`, `C_Bar`

#### Actual behaviour
Actually see 6 bars `A_Bar`, `B_Bar`,`<ALL DATA FROM A_BAR splattered on level one>`,`C_Bar`

#### Live demo with steps to reproduce
Go here: https://avdaredevil.github.io/highcharts-chart/
- Scroll down to the last chart (bar chart).
- Click **_`Insects`_**
- Go back up a level
- Click the add **_`Birds`_** button
- Buggy behavior shows

#### Affected browser(s)
No idea, just tested on chrome.

**Comment by eranh** [comment]
We also experience a similar issue with 4.2.6.
After drilling-down, drilling up and then drilling down to a different bar the drill-down x-values from the previous bar are shown also for this bar in addition to its real x-values.

We rolled back to 4.2.5 until this issue is fixed.

**Comment by eranh** [comment]
The files from the pre-release version solved the issue for me, thanks.
Looking forward for the upcoming release.
