### ISSUE TITLE
Polar chart axis label does not respect `nowrap`

### ISSUE THREAD

**Issue by PowerKiKi** [highcharts/highcharts#5689]
In a polar chart with very long axis labels, I would like to control line wrapping myself, instead of default Highcharts behavior. To do so, I configure the chart with  `"xAxis.labels.style.whiteSpace": "nowrap"` as [documented here](http://api.highcharts.com/highcharts/xAxis.labels.style). And my category names include `<br>` tags as [described there](http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#html). 

#### Expected behaviour

So I expect Highcharts to render labels in SVG (not HTML) while respecting my `<br>` tags and not introducing any other line breaks. In the JSFiddle below, that means exactly three lines, similar to:

```
first first first first first first first
second second second
third third third third
```

#### Actual behaviour

But instead, the first `<br>` seems to be respected but then it seems to switch to default line breaking behavior introducing break lines wherever Highcharts sees fit. So I get something like:

```
first first first first first first first
second
second second
third third third third
```

It seems there is two wrong things. First according to my understanding of the docs, Highcharts should never introduce a line break when `nowrap` is specified. And second, even if it had to introduce line break, then it seems the one introduced is wrong as there is no reason to break the line after the first `second`, and not after the the second `second` (or the first `third` for that matter).

Removing ` "polar": true,` works as expected. And removing the `<br>` tags will render as one single very long line as expected. Removing the `nowrap` is not really an option since it's the default behavior that we wanted to avoid in the first place.

#### Live demo with steps to reproduce

http://jsfiddle.net/5m9817tx/1/

#### Affected browser(s)

Chrome, Firefox (and most likely all others)

**Comment by oysteinmoseng** [comment]
Thank you for reporting, we'll look into this as soon as possible.

**Comment by pawelfus** [comment]
It looks like default options for radial xAxis and standard xAxis are different: [`xAxis.labels.style.textOverflow`](http://api.highcharts.com/highstock/xAxis.labels.style) is not by default set to `ellipsis`.

In other words, to get the same result simply setting `textOverflow` do the thing: http://jsfiddle.net/5m9817tx/3/ (Note that disabling `textOverflow` for a classic chart outputs the same result: http://jsfiddle.net/5m9817tx/5/ )

**Comment by oysteinmoseng** [comment]
Should we set textOverflow to ellipsis by default, or is this by design for some reason?

**Comment by pawelfus** [comment]
That's a good question. As I know, `textOverflow: "ellipsis"` was added after polar extension, so maybe it's just the option is missing?

**Comment by oysteinmoseng** [comment]
@TorsteinHonsi

**Comment by PowerKiKi** [comment]
Thanks for your quick replies. I think the fixed applied is a good thing, but it does not really address the original issue. If we take into account what you said, then I'd say that when both options are used (`"style": {"whiteSpace": "nowrap", "textOverflow": "none"}`), then the expected results still should be:

```
first first first first first first first
second second second
third third third third
```

**Comment by pawelfus** [comment]
Here you can fixed version of Highcharts, please take a look: http://jsfiddle.net/5m9817tx/6/ It renders labels as you expect. It will be part of the next release.

**Comment by PowerKiKi** [comment]
Great, thank you!
