### ISSUE TITLE
Flags overlap when they are close to each other

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#569]
In this example http://jsfiddle.net/YMY7Q/1/ some flags overlap each other. The stackDistance only work if they are on the same point.

Using the piechart for example, the labels are spread out to not cover its neighbor. A similar logic would be good to have for flags as well.

If there's no room to place the side by side,  the highlighted flag should be brought to the front so that its not hidden.

**Comment by niketh90** [comment]
Anyupdate on this .Also when plotting flags of multiple series it overlaps.
