### ISSUE TITLE
Strange Export Behaviour when Tooltip not disabled 

### ISSUE THREAD

**Issue by FLoibl** [highcharts/highcharts#5691]
Hello, i noticed something very strange when updating from Highstocks 2.1.8 to Highstocks 4.2.6.
The SVG that gets sent breaks our .NET based Export Solution with a very long translate attribute.
(I guess this is to make sure the element is invisible?)

The old version sent a group with the Tooltip like so: 
`<g class="highcharts-tooltip"  style="cursor:default;padding:0;white-space:nowrap;" transform="translate(0,**-9999**)">`

Which becomes
`<g class="highcharts-tooltip" style="cursor:default;padding:0;pointer-events:none;white-space:nowrap;" transform="translate(0,**-9000000000**)">`
in the new Version.

I got the Problem fixed on my side by putting {tooltip:{enabled:false}} in my Export-Config just thought i'd notify you of this.

**Comment by oysteinmoseng** [comment]
Hi @FLoibl, thanks for notifying us. This has been fixed in the upcoming release, see #5590.

**Comment by FLoibl** [comment]
You guys are great :+1:
