### ISSUE TITLE
Stacked bar chart: duration on Y 

### ISSUE THREAD

**Issue by oliviercherrier** [highcharts/highcharts#5693]
#### Expected behaviour

Visualize duration on Y into a stacked bar chart. As http://jsfiddle.net/n1mrb8nm/1/

#### Actual behaviour

When using stacking: http://jsfiddle.net/dyr1q6zq/2/

When not using stacking, works well: http://jsfiddle.net/dyr1q6zq/3/

#### Live demo with steps to reproduce

http://jsfiddle.net/dyr1q6zq/2/

#### Affected browser(s)

Google Chrome

Thank you for your support,

Olivier.

**Comment by pawelfus** [comment]
Hi @oliviercherrier 

The problem is that you are stacking timestamps, so when you stack 40+ years of data, then result is as you can see in your demos. Instead compare hours as number of milliseconds, for example using `Date.UTC(1970, 0, 0, 1, 45)`. Here is a demo: http://jsfiddle.net/dyr1q6zq/4/

**Comment by oliviercherrier** [comment]
Hi @pawelfus 

Thank you very much for your so quick help.
Indead, specify yAxis: min was the key error! Sorry for ask you for a so stupid error.

Thank you for your help.
