### ISSUE TITLE
Highmaps regression connecting lat/lon points does nto work

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5694]
#### Expected behaviour
In mappoint series with lineWidth > 0 points become connected.
http://jsfiddle.net/joya35t3/1/

#### Actual behaviour
With lat/lon points connecting does not work. This is regression from Highmaps 4.2.5

#### Live demo with steps to reproduce
http://jsfiddle.net/joya35t3/2/

**Comment by oysteinmoseng** [comment]
Offending commit: 6bc79ba9ef4358649fd1167180d570db1f1b330c

**Comment by sebastianbochan** [comment]
Seems to not be fixed in master:http://jsfiddle.net/ncrfctmd/ and bugfix: http://jsfiddle.net/t898xq34/

**Comment by sebastianbochan** [comment]
Works in both of them.
