### ISSUE TITLE
Highmaps: API documentation issues

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5695]
#### Problems
1) `type` properties are duplicated for all series types. The second definition doesn't look good.

Example: http://api.highcharts.com/highmaps/series%3Cmapline%3E.type

2) `mappoint` API documentation looks a bit too limited in compare with other series. Something missing?

http://api.highcharts.com/highmaps/series%3Cmappoint%3E

**Comment by KacperMadej** [comment]
@TorsteinHonsi The screenshot:

![type_maps](https://cloud.githubusercontent.com/assets/8960408/18583594/cf2eface-7c0b-11e6-898a-8eb7b1a9897a.PNG)

1. `type` for a series - correct one.
2. Duplicate of a `type` property.
3. Doesn't look like a correct definition for Highmaps and a series.

**Comment by TorsteinHonsi** [comment]
@larsac07 Something is fishy. The valid series types in Highmaps is map, mapline, mapbubble, mappoint, heatmap.

**Comment by larsac07** [comment]
@KacperMadej @TorsteinHonsi I can confirm that the bug has been there for at least a year (Testing a branch from commit 53d789ee215709d71516704415d7be89e071bcd4):
![screen shot 2016-09-20 at 09 51 55](https://cloud.githubusercontent.com/assets/5434502/18661849/047fb65a-7f18-11e6-89e1-09870dfa4055.png)
The old version doesn't divide the treelist and detail view into frames, so I had to take two screenshots.

![screen shot 2016-09-20 at 09 52 06](https://cloud.githubusercontent.com/assets/5434502/18661858/0bb70b62-7f18-11e6-92b7-01b5b9f1b762.png)

Looking into it!

**Comment by larsac07** [comment]
It appears that the call to the database includes inherited children from the `series`-option, and therefore inherits the `series--type` property. Querying the database shows that the `series--type` property is the only type-property for series in all products, i.e. no series<someSeries>.type property is unique.

Filtering out all properties which satisfy `/series<.+>--type/` removes the excess duplicates which cause confusion, fixing the issue. Deploying with the change now.
