### ISSUE TITLE
Is counter-clockwise angular gauge chart supported?

### ISSUE THREAD

**Issue by sys27** [highcharts/highcharts#5696]
#### Expected behaviour
I set pane.startAngle = -120, pane.endAngle = -240 and suppose that angular chart will be rendered in reverse order (counter-clockwise). Is it possible to create counter-clockwise angular gauge chart?

#### Actual behaviour
The chart is totally broken (no ticks, strange semi-circle and etc.). You can check it in attached JSFiddle sample. Latest Highcharts sources don't render tick, but on Highcharts 4.0.4 ticks are OK.

#### Live demo with steps to reproduce
[JSFiddle Sample](http://jsfiddle.net/sys_27/v9vt16qa/)
[JSFiddle Highcharts 4.0.4](http://jsfiddle.net/sys_27/mh2k44Lx/)

#### Affected browser(s)
Tested Google Chrome 53 (Windows 10).

**Comment by TorsteinHonsi** [comment]
The pane start- and end-angle doesn't dictate the axis scale. What you want is probably a reversed yAxis: http://jsfiddle.net/highcharts/v9vt16qa/1/.

I'm closing this, please reopen if necessary.
