### ISSUE TITLE
Enhancements and Improvements (mainly around Boost module)

### ISSUE THREAD

**Issue by brian428** [highcharts/highcharts#5698]
I've been working on a very intense charting app (multiple plots that each contain tens of thousands of data points). Most of these are scatter plots, but also some Polar plots as well as a map (Highmaps). Getting things to work required a **lot** of custom plugin logic and overrides. I wanted to share a number of these enhancement ideas for consideration. This mainly applies to the Boost module, but some might also apply to the non-Boost (SVG) charts (such as a point rendering function):
- Allow X panning. The built-in Y-axis-only panning seems like a totally bizarre choice. I got this working with a lot of effort, but am not 100% confident in how I'm doing it.
- Make it easier (or document better) the ability to pass around additional data with each point. Boost expects an array of data in `[xVal,yVal]` format. After a lot of trial and error, I realized that I could use a third array item for each point to pass around an object containing all the field data associated with a given point. E.g.: `[xVal, yVal, pointData]`. Providing guidance on this or exposing a more "official" way to do this would help a lot.
- Allow customization of scatter point rendering, most likely via some sort of render function. I was forced to add a hook that could customize each rendered scatter point, including the color, size, border, border color, and so on. Adding the render function itself wasn't that hard, basically something like this wrapped around the various drawing calls within Boost:

```
// If boostRenderFn() doesn't exist or returns true, do the default drawing. Otherwise, boostRenderFn() will handle the drawing, so skip the default logic:
if( !boostRenderFn || boostRenderFn( series, ctx, stroke, clientX, plotY, r, pointData, pointIndex, "marker" ) === true ) {
  cvsMarker(ctx, clientX, plotY, r);
}
```
- While adding the render function "interceptor" was fairly easy, adding all the logic I needed to the renderFn itself was not. This function handles all of the logic I need, which includes:
  - Defaulting to the fast 1-pixel-sized points when not zoomed in (for more speed), but at a certain zoom threshold, use larger points with colored borders for easier visibility. Or, I have a "detail mode" that can be turned on, which forces larger point rendering regardless of zoom level.
  - Highlighting selected points (different color, larger size, etc.)
  - Using different point color, border color, and border thickness for each point, based on other underlying point data (to visualize points beyond just the series they belong to).
  - Hiding (not drawing) certain points based on other underlying data (such as filtering tools that apply across series).
  - Keeping track of the Canvas drawing configuration used to render the previous point, so that if it changes, a fill and/or stroke will be done. If the point config stays the same, the fill/stroke can be deferred a bit longer. (But not too long, the default stroke interval of every 1000 points can result in ugly charts because of overlapping points/borders/etc.) Unfortunately, this does slow things down. But I'm not sure there's any other way to do this, so it's a tradeoff that must be made if per-point customizations are needed.
  - If there's a better way to do this (such using multiple canvases for drawing, which are then combined?), I'd love to hear about them.
- I also added logic to invoke the boostRenderFn() at the end of each series, so that I can reset settings and state in preparation for the next series.
- Supporting Polar plots with the boost module. (Was _not_ easy. Required additional logic and calls to `axis.translate()` before calling `drawPoint()`).
- Additional chart and axis object methods to determine if chart/axis is currently zoomed, as well as the current X and Y zoom level/zoom factor.

There are probably more topics I could mention, because I've had to do a **lot** of hacking around in the library or in plugins to get closer to what we need. But I'll stop for now to see what the dev team thinks (or advice they might have) about this batch.

**Comment by oysteinmoseng** [comment]
Thank you for your feedback, Brian! The Boost module is still in a pretty early stage of development, and it's great to get a discussion going around the topic of enhancing it.

Are you able to share any of your code?

@TorsteinHonsi Should we gather this somewhere else - e.g. UserVoice, or is GitHub OK?

**Comment by brian428** [comment]
I'll see what I can find out as far as sharing the code. It was written for a client, so I'm not sure whether that would be allowed.
