### ISSUE TITLE
Highstock scrollbar always showing

### ISSUE THREAD

**Issue by marlonmleite** [highcharts/highcharts#5700]
#### Expected behaviour

Scrollbar should be shown only when you need scroller.
#### Actual behaviour

Scrollbar always showing and never hide.
#### Live demo with steps to reproduce

http://jsfiddle.net/8d4g8p22/

**Comment by pawelfus** [comment]
Set `scrollbar.showFull` to false, to disable scrollbar when it's not necessary. 

It should be added to the docs.

**Comment by marlonmleite** [comment]
Is perfect, thanks.

**Comment by pawelfus** [comment]
It's added [here](http://api.highcharts.com/highstock/scrollbar.showFull).
