### ISSUE TITLE
Crosshair labels triangles are buggy

### ISSUE THREAD

**Issue by borisyankov** [highcharts/highcharts#5702]
When crosshair labels are enabled (both X and Y axis) there are some nice triangles drawn in addition to the label's background.

The issue is that they are 'glitchy'. They blink, lag behind the label, or sometimes disappear (rarely).

While I think this is worth fixing, if there is a way to just hide the triangles, it would be a good enough solution.

**Comment by pawelfus** [comment]
Hi @borisyankov 

Could you recreate issue with anchors in jsfiddle? We will check this.

As for a workaround, you can set [`crosshair.label.shape`](http://api.highcharts.com/highstock/xAxis.crosshair.label.shape) to `"rect"`, see demo: http://jsfiddle.net/7txhnLj3/

**Comment by borisyankov** [comment]
Hi @pawelfus 
Thanks for the tip. I will just go with shape: 'rect'.

Here is an example though:
http://jsfiddle.net/7txhnLj3/1/

I just added 'snap: false'.
I think the effect depends on how many data points are there and maybe the chart size itself?
Because in the demo you can notice it by moving the mouse quickly, but it is not that annoying (barely visible). On the other hand in the chart we have it is definitely more noticable and few people made remarks about it.

**Comment by pawelfus** [comment]
Thank you for the demo!

**Comment by pawelfus** [comment]
**Workaround:**

Use bugfix branch: http://github.highcharts.com/bugfix/highstock.js, demo: http://jsfiddle.net/m1o9qn12/
