### ISSUE TITLE
Spline is not drawn with multiple series when logarithmic axis enabled.

### ISSUE THREAD

**Issue by ozanorhan** [highcharts/highcharts#5703]
#### Expected behaviour
Spline should be drawn with multiple series when logarithmic axis enabled.

#### Actual behaviour
Spline is not drawn with multiple series when logarithmic axis enabled.

#### Live demo with steps to reproduce
http://jsfiddle.net/LLExL/6535/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @ozanorhan 

Thank you for reporting the issue. As you can see in the JS console, you have an error: 

> Highcharts error #10: www.highcharts.com/errors/10

Which is:
> Can't plot zero or subzero values on a logarithmic axis

In the current version, you can not plot 0 values on a logarithmic axis. It will change in the next release, where all negative and zero values are treated as nulls, please take a look: http://jsfiddle.net/LLExL/6536/
