### ISSUE TITLE
Nested ng-repeat in table

### ISSUE THREAD

**Issue by bharathd** [highcharts/highcharts#5704]
#### Expected behaviour
i required
row1
  row1
     row 1.1
     row 1.2
row 2
  row 2
    row 2.1
    row 2.2

#### Live demo with steps to reproduce
https://plnkr.co/edit/NEpmNa6QjetrnXzdJPv7?p=preview

**Comment by bharathd** [comment]
help on this

**Comment by pawelfus** [comment]
Hi @bharathd,

I think you posted this in the wrong repo. I don't see charts in your code at all :)
