### ISSUE TITLE
Heatmap doesn't render properly with large data

### ISSUE THREAD

**Issue by akankshaaggarwal** [highcharts/highcharts#5705]
#### Expected behaviour

Heatmap should be rendering data properly even for large data

#### Actual behaviour

Extra blank rows are being shown

#### Live demo with steps to reproduce
https://jsfiddle.net/uxuqh5wc/4/

#### Affected browser(s)
All browser

**Comment by pawelfus** [comment]
Hi @akankshaaggarwal 

Thank you for reporting the issue. It is actually a duplicate of #3765. 

**Workaround:**
Set `series.turboThreshold = 0`, demo: https://jsfiddle.net/wqb0yr82/
