### ISSUE TITLE
Arearange & Areasplinerange high value is buggy when compare: percent

### ISSUE THREAD

**Issue by arthoul** [highcharts/highcharts#5706]
#### Expected behaviour
High value line should be correctly displayed

#### Actual behaviour
High value line is not correct

#### Live demo with steps to reproduce
http://jsfiddle.net/bnhj1as9/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @arthoul 

Thank you for reporting the issue!

*Internal note:*
It is even worse on the master branch: http://jsfiddle.net/bnhj1as9/1/

**Comment by pawelfus** [comment]
The commit above causes regression: http://jsfiddle.net/6rzuk09r/ (#1930).

**Comment by TorsteinHonsi** [comment]
Thanks @pawelfus
