### ISSUE TITLE
Data grouping is not working in CandleStick Chart

### ISSUE THREAD

**Issue by chandram97** [highcharts/highcharts#5707]
In CandleStick chart I am trying to implement data grouping, But it is now working for me.

When I see some of your examples in JS fiddle its working, but when I integrate in my product its not working.

Can you please let me know 

1. What are the important properties need to set for data grouping to work.
2. What are Open High Low Close, and how does they work.
3. How can I check data grouping is working or not.

Please provide me proper documentation and JS Fiddle Example.

**Comment by sebastianbochan** [comment]
This is our bug tracker. For general support questions, please use StackOverflow / forum / email. You can find further information about support here: http://www.highcharts.com/support
