### ISSUE TITLE
The column order of highcharts in type column not correct when the xAxis is datetime type.

### ISSUE THREAD

**Issue by mahaoboy** [highcharts/highcharts#5713]
#### Expected behaviour

columns in column highcharts with datetime xAxis should be ordered in datetime.
#### Actual behaviour

columns in column highcharts with datetime xAxis is not ordered in datetime correctly.
#### Live demo with steps to reproduce

http://jsfiddle.net/pn18aem2/
#### Affected browser(s)

Chrome.

![image](https://cloud.githubusercontent.com/assets/5654225/18700606/c7dfd9d4-800a-11e6-9fbc-1b5d078c274c.png)
![image](https://cloud.githubusercontent.com/assets/5654225/18700619/d4c256b8-800a-11e6-95a9-811fd12bfe1f.png)

From the screenshot, you can see the "13:03:18" is on left of "13:03:09".

**Comment by oysteinmoseng** [comment]
This seems to be due to the `grouping` option being true by default for columns. When setting it to false it works fine: http://jsfiddle.net/pn18aem2/4/.

@TorsteinHonsi What do we think about disabling grouping by default for series on datetime axes?

**Comment by mahaoboy** [comment]
@oysteinmoseng 
Thanks so much.
It fixed my problem.

**Comment by TorsteinHonsi** [comment]
It's a good point... Grouped columns generally makes more sense on category axes and causes confusion on linear or datetime axes. What if we made it true by default only for category axes, but false for linear and datetime? Any opinions @pawelfus @jon-a-nygaard ?

**Comment by pawelfus** [comment]
I think that depending on an axis type is not enough. Imagine use case where interval between all points is fixed (on a linear/datetime axis) with two series: columns will overlap (two volumes on a stockchart in 1H view). Axis type + point range may be enough. Still, a bit risky to change in a patch version.
