### ISSUE TITLE
Galesburg is not mapped correctly on Michigan.

### ISSUE THREAD

**Issue by sseif** [highcharts/highcharts#5714]
Given a coordinates pair in Galesburg, Michigan [42.2888, -85.385], it is placed way off Michigan.

Placed correctly on the map, it looks like http://www.latlong.net/c/?lat=42.288800&long=-85.385000

But when placed on Michigan's map
http://jsfiddle.net/sseif/jmb8ke5n/

Tested on: Chrome

**Comment by sebastianbochan** [comment]
_Workarounds:_ 
1: Instead of using the Michigan map, use the highest detail country-wide map of USA, and remove the states you don't want included.

Example: 
  - http://jsfiddle.net/6gpw331n/

2: Use the Michigan map, but use the lat/lon transform data from the Michigan Congressional Districts map. 

Example: 
 - http://jsfiddle.net/3btmoand/

**Comment by oysteinmoseng** [comment]
We're having some issues with lat/lon placement for our US state maps, and will look into it as soon as we have time.

**Comment by hedbeck** [comment]
@oysteinmoseng Do you have an update on this issue?

**Comment by oysteinmoseng** [comment]
@hedbeck Not yet, we are working on releasing a new version of our map collection and waiting to see if that helps with the issue. Are the workarounds not working for you?

**Comment by hedbeck** [comment]
@oysteinmoseng Thanks for your reply. We were waiting to see if it was resolved before we spent time on a workaround ourselves. Do you have a time frame for this new map collection release?

**Comment by oysteinmoseng** [comment]
@hedbeck We are having some tooling issues, but hope to have the new version out before the end of the year.

**Comment by SkiWether** [comment]
@oysteinmoseng Was this issue ever fixed? We're also having similar issues with Michigan and several other states.

**Comment by oysteinmoseng** [comment]
@SkiWether Unfortunately our tooling issues have delayed development of the map collection further. We have a workaround, and are hoping to get development going again soon, aiming for a new release in Q3 or Q4 this year.

Are the above posted workarounds for this issue not working for you? In that case we might be able to find an alternative temporary solution.

**Comment by MikeSWelch** [comment]
11 months now and this can't be fixed?

Michigan is still broken: http://jsfiddle.net/xpjpoht1/4/

Wyoming works: http://jsfiddle.net/xpjpoht1/5/

**Comment by oysteinmoseng** [comment]
@MikeSWelch We are still delayed on this. Let me know if the workarounds for this issue are not working for your use case, and we'll see if we can find a solution.

**Comment by MikeSWelch** [comment]
I fixed your map.

Your map: http://jsfiddle.net/xpjpoht1/4/

My map: http://jsfiddle.net/xpjpoht1/6/

Here's a direct link to it: https://www.dropbox.com/s/d7bbvunjixu2orm/us-mi-all.js?dl=1

Feel free to send thanks:
Paypal: mikeswelch@gmail.com
Venmo: mikeswelch@gmail.com
Bitcoin: 1KPPacyW5AMpv97XPMqz3QpLyeLAyCuRD6

**Comment by oysteinmoseng** [comment]
@MikeSWelch Good job, that seems more accurate than using the congressional transform. What are your offset numbers based on?

Example of modifying standard map with new offsets: http://jsfiddle.net/5a8Lvcd6/

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#8
