### ISSUE TITLE
Missing markers - boost

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5715]
#### Expected behaviour

All markers should be displayed
#### Actual behaviour

Markers are missing and small line is printed. Markers and markers size are ignored.
#### Live demo with steps to reproduce

Example:
- http://jsfiddle.net/pcuhdz6s/

**Comment by TorsteinHonsi** [comment]
This is one of the features that is deliberately removed to optimize speed. See https://github.com/highcharts/highcharts/blob/v4.2.7/js/modules/boost.src.js#L33.

**Comment by sandhyawy** [comment]
But it is working fine with less number of points.

**Comment by sebastianbochan** [comment]
@TorsteinHonsi is any plan to keep performance and enable all markers?

**Comment by TorsteinHonsi** [comment]
> But it is working fine with less number of points

Yes, when you zoom in to below the `boostThreshold`, it is rendered as a regular series. When your number of points exceeds the boostThreshold, we throw away markers and focus on speed. 

> @TorsteinHonsi is any plan to keep performance and enable all markers?

Performance will go down as we start drawing more complex shapes. And markers don't make sense anyway with thousands of points. The recommended setup for the OP fiddle is to use a lineWidth and keep the default hover-marker: http://jsfiddle.net/pcuhdz6s/2/

**Comment by pawelfus** [comment]
It's resolved since new boost module (available since v5.0.8): http://jsfiddle.net/BlackLabel/3u8tkbc0/1/
