### ISSUE TITLE
bower invalid-meta warning

### ISSUE THREAD

**Issue by zevero** [highcharts/highcharts#5716]
#### Expected behaviour

no warning bower invalid-meta on installation

#### Actual behaviour

there is a warning invalid-meta regarting the main field having multiple .js files

    bower install
    bower not-cached    https://github.com/highcharts/highcharts-dist.git#^4.2.7
    bower resolve       https://github.com/highcharts/highcharts-dist.git#^4.2.7
    bower checkout      highcharts#v4.2.7 
    bower invalid-meta  The "main" field has to contain only 1 file per filetype; found multiple .js files: ["highcharts.js","highcharts-more.js","modules/exporting.js"]
    bower resolved      https://github.com/highcharts/highcharts-dist.git#4.2.7
    bower install       highcharts#4.2.7

#### Fix

please fix main field to conatin only one .js file  or simply delete it

**Comment by TorsteinHonsi** [comment]
Fixed by https://github.com/highcharts/highcharts-dist/commit/6176784d3032cdd2cb875ecb22fc04284a9fca2a
