### ISSUE TITLE
Exported chart SVG contains errors when using rgba color series

### ISSUE THREAD

**Issue by mjsteichen** [highcharts/highcharts#5718]
#### Expected behaviour
Using rgba color for a series will not cause problems in the exported chart SVG.

#### Actual behaviour
Exported chart contains error `error on line 1 at column 3550: Attribute fill-opacity redefined`

If I use hex for the series' color instead of rgba, the exported SVG is fine.

#### Live demo with steps to reproduce
http://jsfiddle.net/msteichen/o4a2e7Lp/

#### Affected browser(s)
chrome, firefox

**Comment by TorsteinHonsi** [comment]
Duplicate of #5366
