### ISSUE TITLE
Unable to download highcharts-data

### ISSUE THREAD

**Issue by rohitszone** [highcharts/highcharts#5719]
#### Expected behaviour
Should download the package on npm install highcharts-data --save

#### Actual behaviour
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "highcharts-drilldown" "--save"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code E404

npm ERR! 404 no such package available : highcharts-drilldown
npm ERR! 404
npm ERR! 404 'highcharts-drilldown' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GUIWorkspace\dmh-uit-parent\dmh-uit-web\ui\npm-debug.log

**Comment by pawelfus** [comment]
Hi @rohitszone 

Thanks for contacting with us. Unfortunately `highcharts-data` package is not our package ( see collaborators [here](https://www.npmjs.com/package/highcharts-data) ).

How about using the official Highcharts [package](https://www.npmjs.com/package/highcharts)? 

    npm install highcharts --save
    
And then:

    var Highcharts = require('highcharts');
    require('highcharts/modules/data')(Highcharts);
