### ISSUE TITLE
Tooltip / Point selection issue in v4.2.7

### ISSUE THREAD

**Issue by nvindice** [highcharts/highcharts#5721]
#### Expected behaviour
With "sticky" but without "shared tooltip" option the tooltip of the nearest data point should be displayed. This worked fine until version 4.2.6.

#### Actual behaviour
Since version 4.2.7, the x-nearest point (and tooltip) is being selected, not the (x,y)-nearest point.

#### Live demo with steps to reproduce
http://jsfiddle.net/29ho1gd8/1/
Place the cursor around 6:01 am, it will always display the "Sleep"-Tooltip, even though the cursor is at the very bottom of the chart.

#### Possible reason
In [line 10424](https://github.com/highcharts/highcharts/blob/master/js/highcharts.src.js#L10424), only the x-distance is being taken into account, the code in line 10429 (desired behaviour) won't be reached normally. The comment in L10423 says "...and shared tooltip", which is not being checked.

Thank you for this great product!

**Comment by mhwlng** [comment]
f.y.i.
I had the same problem with tooltips in stockchart. Reverting to 4.2.6 fixed it.

**Comment by oysteinmoseng** [comment]
Thank you for reporting. I'm however seeing the same behavior also in 4.2.6 and 4.2.5?

**Comment by nvindice** [comment]
Interestingly, you have a point. At least for this live demo - my real world example works fine with 4.2.6, can't see the difference right now.

However, modifying [L10424 ](https://github.com/highcharts/highcharts/blob/master/js/highcharts.src.js#L10424) to check for the "shared" property fixes the problem in my real world use case as well as in the live demo: [http://jsfiddle.net/29ho1gd8/2/](http://jsfiddle.net/29ho1gd8/2/)

`#10424: if (shared && isCloserX !== 0) {`

**Comment by TorsteinHonsi** [comment]
@pawelfus Any insight?

**Comment by pawelfus** [comment]
I think there should be `&& shared`, just like OP said. Let me run tests and we will see.

**Comment by nvindice** [comment]
Thank you very much for your fast and helpful response. Is there a planned date for the next (bugfixed) release? Unfortenately, I cannot use my own (fixed but unofficial) version.

**Comment by mhwlng** [comment]
![2016-09-30_10-36-53](https://cloud.githubusercontent.com/assets/1388886/18985778/f56240ae-86f9-11e6-959b-5c2420cc47b0.png)

I have the same problem again with stockchart in v 5.0.0.0

**Comment by pawelfus** [comment]
@TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
@mhwlng The fix was made after we froze the code for v5.0.0, but we'll be out with a new maintenance release within a few weeks.

**Comment by mhwlng** [comment]
ok, thanks
I manually made the same change in v5..0.0.0 again. now it works again.
` if (isCloserX !== 0 && shared) { // #5721`
