### ISSUE TITLE
Tooltip's HTML <a> is not clickable / regression from 4.2.6

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5722]
#### Expected behaviour

In a tooltip with HTML enabled <a> tag with url is clickable and relocated to the url.
http://jsfiddle.net/fb0qssya/3/
#### Actual behaviour

Url is not clickable at all. This regression from 4.2.6.
#### Live demo with steps to reproduce

http://jsfiddle.net/fb0qssya/2/

**Comment by oysteinmoseng** [comment]
Offending commit: 41d85466e03d7028f4a107e8edd136a9c6804cf3

**Comment by TorsteinHonsi** [comment]
The workaround is to set `style.pointerEvents` to `auto`. 

I'm not sure whether to call this a bug or a feature - as you see from the offending commit it resolves another problem. The ideal solution would allow clicks mot ignore mousemove events.

**Comment by Morgs007** [comment]
#### Expected behaviour

In a tooltip with HTML enabled tag with dropdown/select to open with available dropdown options.

#### Actual behaviour

The dropdown/select doesn't open, seems disabled?

**Comment by tjhiggins** [comment]
@TorsteinHonsi That workaround does allow for clicking on links, but it does lead to undesirable behavior. I have `stickyTracking: false`, but if I hover around the tooltip if I move to close to another point it switches. http://jsfiddle.net/TJHiggins/fb0qssya/10/

Probably going to have to add some hacky extension to resolve so it doesn't switch points when hovering over a tooltip.

**Comment by khushahal-sharma** [comment]
https://github.com/highcharts/highcharts/issues/5722#issuecomment-276136511
@TorsteinHonsi,   I  am also facing this issue as mention in the above link when I  have line densely chart then want to click on tooltip link then  it opens up new tooltip so it is impossible to click on the link. Same happend  in touch devices also.

**Comment by KacperMadej** [comment]
Working correctly in v9.1.0: https://jsfiddle.net/BlackLabel/pzu634kq/1/
Closing as resolved
