### ISSUE TITLE
Version 5: Pie drilldown exception

### ISSUE THREAD

**Issue by danielwolf1** [highcharts/highcharts#5723]
#### Expected behaviour
When using Highcharts 5 and drilldown pie, after entering level 2, a JS exception occurs:
highcharts.js:29 Uncaught TypeError: Cannot read property 'match' of undefined

#### Actual behaviour
No exception occurs, labels and buttons are visible

Uncaught TypeError: Cannot read property 'match' of undefined
#### Live demo with steps to reproduce
[jsfiddle.net/14vxzeL3/](url)

#### Affected browser(s)
All

**Comment by oysteinmoseng** [comment]
Thank you for reporting this

**Comment by TorsteinHonsi** [comment]
It's fixed in the release candidate.
