### ISSUE TITLE
Incorrect tooltip position with custom css zoom level

### ISSUE THREAD

**Issue by Ansku** [highcharts/highcharts#5724]
#### Expected behaviour

Tooltip appears to the node that is being hovered regardless of zoom level.
#### Actual behaviour

If the zoom level is larger than default, tooltip appears to a node that is further to the right/down, i.e. the node that would be in that approximate position if the zoom level were default.
#### Live demo with steps to reproduce

[jsFiddle demo](http://jsfiddle.net/nyo66gqs/) [_edited_]
Inspect the highchart-container element that holds the chart
Add to the element this style: zoom: 1.4;
Hover over a node in the left side of the chart.
#### Affected browser(s)

All

**Comment by sebastianbochan** [comment]
Related topic: https://github.com/highcharts/highcharts/issues/2299

**Comment by vaikzs** [comment]
Is there a fix for this issue yet?

**Comment by TorsteinHonsi** [comment]
Here's a proposed fix that seems to work for this case, though it will probably break in more complex situations: 

http://jsfiddle.net/highcharts/nyo66gqs/1/
