### ISSUE TITLE
Import highchart boost module

### ISSUE THREAD

**Issue by davidbani** [highcharts/highcharts#5725]
I'm trying to load the boost module after Highcharts is loaded. Is this correct?

`var Highcharts = require('highcharts');`
`require('highcharts/modules/boost')(Highcharts);`

Using boost for path-to-canvas-image rendering.

[http://www.highcharts.com/news/175-highcharts-performance-boost](http://www.highcharts.com/news/175-highcharts-performance-boost)

I don't see any changes to the chart.

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
