### ISSUE TITLE
Destroy a SVG element

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#5727]
#### Behaviour
It seems that in just released version of Highcharts (v4.2.7) function responsible for destroying SVG elements (destroy() - http://api.highcharts.com/highcharts/Element.destroy) does not work. In the previous version (v4.2.6) it works fine.

#### Live demos with steps to reproduce
http://jsfiddle.net/d_paul/n1487q1t/ - v4.2.6
http://jsfiddle.net/d_paul/n1487q1t/1/ - v4.2.7

**Comment by oysteinmoseng** [comment]
Thank you for reporting this.

**Comment by oysteinmoseng** [comment]
Offending commit: c83323ab54d4d846a0ef7f76c1eb4020bef38be0

**Comment by TorsteinHonsi** [comment]
The underlying bug is that the `mouseOver` event is now fired repeatedly on moving the mouse, while it should fire only one. See http://jsfiddle.net/n1487q1t/3/.

The consequence in your code @PaulDalek is that multiple `myLabel`s are generated, but only the last one is removed on `mouseOut`.

**Comment by pawelfus** [comment]
**Workaround:**
Destroy label before creating a new one if that label exists: http://jsfiddle.net/n1487q1t/5/

**Comment by pawelfus** [comment]
*Internal note:*
Silly mistake, there's no `pointer.hoverPoint` of course. I guess an unit-test for that is unnecessary?

**Comment by TorsteinHonsi** [comment]
Yes I guess so...
