### ISSUE TITLE
Highcharts 5: Donut chart: Color assignment for childs not possible

### ISSUE THREAD

**Issue by danielwolf1** [highcharts/highcharts#5728]
#### Expected behaviour
We need proper css classes to identify level-n elements of a pie chart. The options shown in the [demo ](http://www.highcharts.com/demo/pie-donut)won't work with Version 5 as we don't have access to Highcharts.getOptions().colors anymore.

#### Actual behaviour
This is not possible anymore:

```
//The following line will return undefined in V5 as the colors are defined in JS
var colors = Highcharts.getOptions().colors,
        categories = ['MSIE', 'Firefox', 'Chrome', 'Safari', 'Opera'],
        data = [{
            y: 56.33,
           //This is not possible anymore:
           color: colors[0],
            drilldown: {
                name: 'MSIE versions',
                categories: ['MSIE 6.0', 'MSIE 7.0', 'MSIE 8.0', 'MSIE 9.0', 'MSIE 10.0', 'MSIE 11.0'],
                data: [1.06, 0.5, 17.2, 8.11, 5.33, 24.13],
                color: colors[0]
            }
```

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

Individual point coloring is covered in http://www.highcharts.com/docs/chart-design-and-style/style-by-css. See demo at http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/css/colors/.

Further differentiation between the series can be make by rules like `.highcharts-series-0 .highcharts-point.highcharts-color-0`.

**Comment by danielwolf1** [comment]
Thanks for your reply.

I think it's not a bug - but maybe a missing feature? I know how to apply further differentiation between the series but I need a generic approach like you show it on the demo page: http://www.highcharts.com/demo/pie-donut 

In Highcharts 5, the sublevels can not be distinguished from other levels. They just have the classes highcharts-color-0 to highcharts-color-n. What I need is a additional class on the sublevels which refers to the parent level in order to apply the same color there. 

[You can explore the scenario in this fiddle](http://jsfiddle.net/0rvwtx3w/)

Thanks.

**Comment by TorsteinHonsi** [comment]
Hi again, sorry, I missed the point with setting the point colors directly. I made a change so we can set each point's `pointIndex` as an option: http://jsfiddle.net/0rvwtx3w/1/.
