### ISSUE TITLE
Overlapping series and stickyTracking: false blocks overlapped markers

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#5729]
#### Expected behaviour

When hovering the marker behind the black series, able to see the tooltip.
#### Actual behaviour

When hovering the marker behind the black series, the nearest marker on the black series in hovered instead.
#### Live demo with steps to reproduce

http://jsfiddle.net/Llorx/hgbz7kg6/4/

Hover the first marker behind the black series.
#### Affected browser(s)

Any, I guess.

**Comment by pawelfus** [comment]
Hi @Llorx 

Thanks for reporting the issue! However, I'm not sure if this is a bug. Every series has a tracking shadow, which decides when to highlight series/point. 

You can observe that tracker here: http://jsfiddle.net/2tjq74te/

As you can see, these two trackers overlap. Of course, we can change the order of series, or use zIndex to get better result: http://jsfiddle.net/2tjq74te/2/ - but I don't think this is a right solution: how to determine which series should be on top.

The solution in your case is to decrease snap size, for example: http://jsfiddle.net/2tjq74te/3/ - in that way the darker series won't overlap the marker.

**Comment by Llorx** [comment]
Hm, I see how it works now. Yep, not a bug, but how Highcharts works.

Can I ask for a feature then?

When highcharts create a marker, set its zIndex to be in front of trackers, so mousevenets are prioritized when pointing directly over them. This way we can keep bold trackers without stickyTracking (as I like it) but keep the tacking system like stickyTracking when hovering markers. The intuitive flow (And most for non-computer-used people) of a marker is to show things when hovering it, regardless of the "less important" things near it.
