### ISSUE TITLE
Feature: Show all marks on hover

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#5730]
#### Expected behaviour

When hovering a series with hidden markers, having an option to show all the markers.
#### Actual behaviour

Not existent. Having to use a hack, but has bugs with overlapping series.
#### Live demo with steps to reproduce

Here the hack used: http://jsfiddle.net/Llorx/hgbz7kg6/3/

When hovering the overlapped series, a graphic glitch is happening.
#### Affected browser(s)

Any, I guess.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! It's a simple and intuitive hack that we should expect to work.

**Comment by pawelfus** [comment]
I think the main issue here is recreating series in `update()`.  After update all properties in `point` are nullified, so any reference like `point.something.somethingElse` will throw an error sooner or later. Without rewriting `update()` I don't see any easy solution for that, but I'm open for suggestions. 

**Workaround 1:**
Don't use `series.update()`, but update each point separately: http://jsfiddle.net/hgbz7kg6/7/ - however, it doesn't look good when hovering between two series (issue with using `mouseOver` as described above by @TorsteinHonsi remains - but at least we removed all of the JS errors).

**Workaround 2:**
Use internal methods to update series: http://jsfiddle.net/hgbz7kg6/9/

Snippet:

        events: {
          mouseOver: function() {
            this.options.marker.enabled = true;
            this._hasPointMarkers = true;
            this.drawPoints();
          },
          mouseOut: function() {
            this.options.marker.enabled = false;
            this.drawPoints();
          }
        }

**Comment by Llorx** [comment]
Workaround 2 works like a charm.

Note: I asked it on Stackoverflow before asking for a feature here and [@Grzegorz Blachliński](http://stackoverflow.com/users/5418042/grzegorz-blachli%C5%84ski) came with another solution that also works: http://stackoverflow.com/questions/39632979/in-highcharts-is-it-possible-to-enable-all-markers-on-hover/39639177?noredirect=1#comment66649832_39639177

**Comment by TorsteinHonsi** [comment]
Ideally we should do it like Workaround 2 internally too. The update method should be smart enough not to destroy points unless necessary. Maybe we should avoid destroying the points when the `type` is unchanged and new `data` is not set.

**Comment by pawelfus** [comment]
I agree, that would be the ideal solution. I think another condition for destroying points is when `dataGrouping` changed. I'm not sure about `marker` options (e.g. symbol changed), but this probably during tests should clarify.

**Comment by Llorx** [comment]
After some tests I've ended using Workaround 2, because I don't want to have a thousand markers being drawn altough their group is hidden. I prefer to disable marker generation and enable it when I detect enough points to not break the browser.
