### ISSUE TITLE
Highstock defect on xAxis-labels by irregular time interval in UTC

### ISSUE THREAD

**Issue by till-soptim** [highcharts/highcharts#5733]
#### Expected behaviour

this.x (tooltip-formatter) and this.value (xAxis-formatter) returns same value (in UTC).

xAxis labels should be exact    positioned under colums, when time interval is irregular.
#### Actual behaviour

this.x and this.value returns different values (see first demo).

Problem with position of xAxis labels without using a formatter (see second demo).
#### Live demo with steps to reproduce

xAxis-labels on wrong position, because different values for this.x and this.value:
http://jsfiddle.net/99tfxrg1/11/

xAxis-labels on wrong position (without formatters)
http://jsfiddle.net/99tfxrg1/12/
#### Affected browser(s)

Chrome (tested in Version 53.0)
Firefox (tested in Version 47.0.1)
Internet Explorer (tested in Version 11)

**Comment by pawelfus** [comment]
Hi @till-koppers , thank you for reporting the issue.

**Workaround:**
Use [`xAxis.tickPositioner`](http://api.highcharts.com/highstock/yAxis.tickPositioner): [demo](http://jsfiddle.net/99tfxrg1/14/).

*Internal note:*
It is a general issue with datetime axis: http://jsfiddle.net/99tfxrg1/13/

**Comment by till-koppers** [comment]
@pawelfus  
That works. Thank you for your quick response.
