### ISSUE TITLE
Categories are missing when addSeries

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5734]
#### Expected behaviour

All categories should work with a single series.
#### Actual behaviour

In the case that we use addSeries, the only first category is printed. What is interested, when we add multiple series, then categories work well.
#### Live demo with steps to reproduce

Single series: http://jsfiddle.net/0uce3vyy/
Multiple series: http://jsfiddle.net/cyr61p6t/

**Internal note**
Fails since https://github.com/highcharts/highcharts/commit/56e5280

**Comment by TorsteinHonsi** [comment]
It's somehow related to the `cropThreshold`.

#### Workaround
Increase the crop threshold: http://jsfiddle.net/highcharts/0uce3vyy/1/
