### ISSUE TITLE
Clicking near context menu doesn't close it

### ISSUE THREAD

**Issue by callumacrae** [highcharts/highcharts#5735]
#### Expected behaviour

When tapping on somewhere that isn't the context menu, the context menu should be shut
#### Actual behaviour

The context menu isn't shut unless you're tapping on something like a different button.

---

This is happening on iOS. I don't know about other mobile OS's.

The reason for this is that Highcharts is listening to `mouseenter` and `mouseleave`, and mouseleave isn't always fired on mobile - for example, tapping a heading or the page background doesn't cause it to be fired.

https://github.com/highcharts/highcharts/blob/master/js/modules/exporting.src.js#L549

Related: https://github.com/highcharts/highcharts/issues/2258

**Comment by oysteinmoseng** [comment]
Could not reproduce this on Android 6.0.1 or a virtual iPhone 6S. Which device are you using?

**Comment by sebastianbochan** [comment]
Let us know if problem appears also with our demos.

Tested demo: (http://www.highcharts.com/demo/line-basic) in the iPad (iOS 9.3.5) and was not able to reproduce.

_**Workaround**_
Use target and hide menu if click out of button / menu shape.

Example:
 - http://jsfiddle.net/qub5mrf3/

**Comment by callumacrae** [comment]
I was testing on both a real iPhone and an iPhone simulator (through xcode).

I've figured out what is causing the issue, though: `.highcharts-contextmenu` seems to be positioned by adding 24px of padding to all sides. This means that clicking _near_ the menu doesn't close it.

**Comment by oysteinmoseng** [comment]
Aha, this of course happens on all devices, including desktop browsers. Thank you for reporting.

**Comment by callumacrae** [comment]
Have just tested and this issue seems to be fixed!
