### ISSUE TITLE
Zooming in multi xAxis with crosshair snap false

### ISSUE THREAD

**Issue by hkostia** [highcharts/highcharts#5736]
#### Expected behaviour
Zooming in should reset overlay (when mouse button pressed)

#### Actual behaviour
After zoom in zoom overlay is still there
```
Uncaught TypeError: Cannot read property 'chartX' of undefined
drawCrosshair @ highcharts.src.js:9350
(anonymous function) @ highcharts.src.js:10537
each @ highcharts.src.js:1230
reset @ highcharts.src.js:10535
redraw @ highcharts.src.js:12434
zoom @ highcharts.src.js:19298
(anonymous function) @ highcharts.src.js:10753
fireEvent @ highcharts.src.js:1395
drop @ highcharts.src.js:10752
onDocumentMouseUp @ highcharts.src.js:10791
```

#### Live demo with steps to reproduce
http://jsfiddle.net/kmsya29v/1/

#### Affected browser(s)
Chrome, Firefox

**Comment by pawelfus** [comment]
Thank you for reporting the issue @hkostia. It is a regression bug, related commit: 725efc5

Works fine if: enabled snap or tooltip is not shared.

**Comment by borisyankov** [comment]
I am encountering the same bug but in different case - while dragging the series left and right.
The this.cross is not defined and the 'ifs' do not anticipate that.
