### ISSUE TITLE
How to show pie chart legend for (entire) series, not slices

### ISSUE THREAD

**Issue by grtjn** [highcharts/highcharts#5738]
If I add showLegend true to series when showing multiple series as nested donuts, I'd like to see serie names in the legend, rather than all separate slices of all series. Toggling a slices, just takes that one out, but I'd rather be able to hide an entire series with one click in the legend, like how it behaves for line, bar, column kind of charts.

I couldn't find anything in the documentation or internet that indicates this is possible. Is it possible, and if not, is there some way around?

**Comment by KacperMadej** [comment]
Hi,

If it is not a bug, please check one of the support channels. More information: http://www.highcharts.com/support

If this is a bug, please add a demo in JSFiddle and I will reopen this issue.
