### ISSUE TITLE
Spriderweb scaling issue

### ISSUE THREAD

**Issue by nandakumar8** [highcharts/highcharts#5739]
Hi All,

I am working on a project and am using Highcharts API. It's been great and a very easy to use library. I have a use case where I need to implement spiderweb chart. But the problem is I have only one series and all X axis categories have totally different scales. For example, one category is in percentage from 0 to 100 and one category has values ranging from 0 to one billion in count. 

        xAxis: {
            categories: ['Total Impressions', 'Paid Impressions', 'Blcoked Impressions', 'Fill Rate',
                    'Yield', 'Margin'],
            tickmarkPlacement: 'on',
            lineWidth: 0
        },

        series: [{
            name: 'Publihser name',
            data: [10000000, 10000, 600000, 50%, 1000, 80%],
            pointPlacement: 'on'
        }]

Since there is a lot of variation in scale,is it possible to show the ranges effectively in the same chart by using different scales across each line of the spiderweb. I want to be able to show all categories in relative scale so that one point with 15% fill rate is not shown close to zero when there are 100000 total impressions.

https://jsfiddle.net/nandakumar_pulsepoint/rr5op1ss/

Thanks and Regards,
Nandakumar Udayakumar

**Comment by oysteinmoseng** [comment]
Thank you for your feedback. We have a UserVoice request for this, see https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/6243758-i-created-a-polar-spider-graph-and-i-would-like-to.

You might be able to work around this by using multiple yAxes, depending on your needs.

**Comment by Dragon-Rider** [comment]
Hi there，

I have met the same problem.  And @oysteinmoseng seems  to misunderstand our problem. So I will explain the problem specifically.  Hope you(@oysteinmoseng)  can answer for that. Thank you :)

Here is the demo for our problem：
https://jsfiddle.net/EragonJiang/qy2b5vjc/3/

As you can see，"salses" and "development" are from 0 to 100, but others has greater ranges. So, some angles of polygon are 'sunk' :（

So, I wondered if there is any ways to make the y axis of "sales" from 0 to 100. Meanwhile, the y axis of "marketing" from 0 to 10000000.

This is one of solutions from Stackoverflow：http://stackoverflow.com/questions/16779040/highcharts-spider-chart-change-axis-ranges

But we have some data which are  ”0“，it can't work.

Looking forward to your reply ：）
 
Thanks and Regards,

Eragon Jiang

**Comment by oysteinmoseng** [comment]
@Dragon-Rider Unfortunately I do understand, we just don't have a good solution for it at the moment. One workaround, as mentioned earlier, is to use multiple axes/series: https://jsfiddle.net/qy2b5vjc/5/. I suggest voting and posting your comments on the UserVoice request linked to above, that way we can keep track of which features are most requested.

**Comment by TorsteinHonsi** [comment]
One solution could be that you gave up the data in percentages, then add a separate `raw` value that you can use in the tooltip, and possibly in data labels: https://jsfiddle.net/y7vLpj1f/

**Comment by Dragon-Rider** [comment]
Thank you for your help, guys.  I will try it :)
