### ISSUE TITLE
Reversed bar stacked labels

### ISSUE THREAD

**Issue by SteffenTallieu** [highcharts/highcharts#5742]
#### Expected behaviour
Stacked labels in reversed bar chart should be printed directly left of bars.

#### Actual behaviour
Stacked labels are invisible - they are printed behind the x axis categories.

#### Live demo with steps to reproduce
https://jsfiddle.net/v3u8w3et/19/

#### Affected browser(s)
All browsers affected

**Comment by pawelfus** [comment]
Hi @SteffenTallieu, thank you for reporting this issue. I agree, labels are misplaced in the demo above.

**Workaround:**
Not a perfect one, but at least it shows stack labesl: set `stackLabels.align = 'left'`, demo: https://jsfiddle.net/v3u8w3et/21/

**Comment by SteffenTallieu** [comment]
Thank you for your quick response @pawelfus .
Great workaround. Combining with a `x: -20`, makes it even better.
This can be closed for me.
