### ISSUE TITLE
Map hover state - wrong shape 

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5743]
#### Actual behaviour
Map hover state - wrong shape is added

#### Live demo with steps to reproduce
Example:
 - http://www.highcharts.com/maps/demo/mapline-mappoint

![maps-hover](https://cloud.githubusercontent.com/assets/2115686/18945939/ffd31d7e-862c-11e6-9105-896f77dd18a4.gif)

**Comment by pawelfus** [comment]
Duplicate of #4813.

**Comment by sebastianbochan** [comment]
Miss that ticket, sorry!
