### ISSUE TITLE
v5.0.0 sparkline tooltip issue

### ISSUE THREAD

**Issue by karantan** [highcharts/highcharts#5745]
#### Expected behaviour:
![screenshot 2016-09-29 15 03 37](https://cloud.githubusercontent.com/assets/7062631/18955041/efb8ae8a-8655-11e6-883a-a374477ef820.png)

#### Actual behaviour:

![screenshot 2016-09-29 15 04 17](https://cloud.githubusercontent.com/assets/7062631/18955053/0082a946-8656-11e6-8fae-b3985f632548.png)

#### Live demo with steps to reproduce
template: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/sparkline/

Just hover over any sparkline graph.

In previous version this worked: http://jsfiddle.net/hc12j0gp/

btw this is from your official demo site

#### Affected browser(s)
Firefox, Chrome

**Comment by KacperMadej** [comment]
It's possible to show tooltip when chart container have overflow set to visible: http://jsfiddle.net/af5fzsva/

```
.highcharts-container {
  overflow: visible !important;
}
```

**Comment by bhagwat** [comment]
Its broken in latest version 7.2.1 and even the suggested css tweaks are not working.

Live demo with reproducible issue: http://jsfiddle.net/bhagwat/q5zcx2m7/7/
Just hover over any sparkline graph to see the tooltip visibility.

**Comment by pawelfus** [comment]
Thanks for reporting this issue @bhagwat - it seems the regression is back. Could you create a new issue?

Meanwhile, you can use [`tooltip.outside`](https://api.highcharts.com/highcharts/tooltip.outside): http://jsfiddle.net/BlackLabel/Lw6ejg48/
