### ISSUE TITLE
highlighting the selected point on the highchart is displaced after switching from portrait to landscape 

### ISSUE THREAD

**Issue by AlekseyLyutiy** [highcharts/highcharts#5746]
#### Expected behaviour

if we pointing some data point on highchart, appears highlighting of the selected point. this highlighting should be on the same datapoint after switching from portrait to landscape 
#### Actual behaviour

highlighting the selected point on the highchart is displaced after switching from portrait to landscape
#### Live demo with steps to reproduce

![portrait](https://cloud.githubusercontent.com/assets/22521784/18955346/b4f7e77a-865f-11e6-81c0-4eb636327591.PNG)
![landscape](https://cloud.githubusercontent.com/assets/22521784/18955352/b805c2ac-865f-11e6-9435-226347be2f9e.PNG)
#### Affected browser(s)

mobile application, iOS and Android

Please, reply ASAP when this issue could be fixed. Thank you!

**Comment by TorsteinHonsi** [comment]
Simplified demo: http://jsfiddle.net/highcharts/gxv8bw06/

The halo is not moved.

**Comment by TorsteinHonsi** [comment]
Another, and worse, scenario is when the markers are disabled. The `Point.setState` function is never called, and neither the halo nor the `stateMarkerGraphic` are moved: http://jsfiddle.net/highcharts/gxv8bw06/1/

**Comment by TorsteinHonsi** [comment]
@AlekseyLyutiy On a real iOS device, when testing http://jsfiddle.net/highcharts/gxv8bw06/4/, I don't experience this problem.
