### ISSUE TITLE
Highcharts 5.0.0 offline api miss some options

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#5747]
Hi, while I ready your changelog of highcharts 5.0.0 and your offline api, I find some options is missed:
- [Chart.addCredits](http://api.highcharts.com/highcharts/Chart.addCredits)
- [defs](http://api.highcharts.com/highcharts/defs)

**Comment by TorsteinHonsi** [comment]
Thanks for notifying!

@larsac07 Do you think this has to do with caching of the online API? In that case, what can we add to our procedure to clear the cache before generating the offline API?

**Comment by KacperMadej** [comment]
Update:
[defs](https://api.highcharts.com/highcharts/defs) are working fine

https://api.highcharts.com/class-reference/Highcharts.Chart%23addCredits should redirect to
https://api.highcharts.com/class-reference/Highcharts.Chart#addCredits

**Comment by pawelfus** [comment]
Class reference updated, closing the issue.
