### ISSUE TITLE
Newly Getting drilldown.js:23 Uncaught TypeError: Cannot read property 'drilldown' of null

### ISSUE THREAD

**Issue by peterfranks** [highcharts/highcharts#5750]
We are pulling drilldown.js directly from code.highcharts.com, and I guess there was an update recently. Now our 2D charts no longer display, and we get this error in our browser:

drilldown.js:23 Uncaught TypeError: Cannot read property 'drilldown' of null

#### Expected behaviour
Some of our data points are null, and we expect them to simply display no dot on our resulting 2D line graph. This has been working great up until very recently.

#### Actual behaviour
I suspect this new failure is a result of us setting some of our data points to null, since data does not exist for that particular point. As a result, line 645 of drilldown.src.js gives us a null exception:

if (xData[i] === x && series.options.data[i].drilldown) {

The above line will fail when series.options.data[i] is null (as is occasionally in our data set).

If it was defined using short-circuiting as something like the following, we would not see this error (I have tested this locally with success):

if (series.options.data[i] && xData[i] === x && series.options.data[i].drilldown) {

#### Live demo with steps to reproduce
http://jsfiddle.net/hilarybray/1b0rxwkg/

Notice the second data point has a null value. The chart does not display. Now change the second data point to have a value (for example, 30). The chart displays.

#### Affected browser(s)
Chrome and Firefox at least, probably others

**Comment by TorsteinHonsi** [comment]
Fails since v4.2.7.

**Comment by alvarezguille** [comment]
@TorsteinHonsi I noticed this was fixed in 5.0.1, would it be possible to get this fix included in 4.2.x? Is there any plan for a new 4.x.x release?

**Comment by KacperMadej** [comment]
@alvarezguille Please post a live demo with the version you are using and I could prepare a wrapper workaround for you if you are interested. There's no official plan for a new 4.x.x release.

**Comment by alvarezguille** [comment]
@KacperMadej this should be enough to reproduce it, it's the "Area with missing points" demo using 4.2.7 and adding the `drilldown.js` module: http://jsfiddle.net/alvarezg/6hn7qpmz/

**Comment by KacperMadej** [comment]
@alvarezguille Here's a workaround with a wrapper that applies the fix from the issue. Demo: http://jsfiddle.net/4q8jyrvm/
