### ISSUE TITLE
HTML Tooltips have default opacity 1, instead of 0

### ISSUE THREAD

**Issue by hjnilsson** [highcharts/highcharts#5752]
#### Expected behaviour
The tooltips are invisible before a chart is hovered.

#### Actual behaviour
On initial page load, tooltips when `useHTML` is set to `true` have an opacity set inline to 1. After hovering the chart (so the tooltip is visible) and then letting the tooltip fade by removing the cursor. The tooltip will have opacity 0 (which is correct).

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/tooltip/fullhtml/

Inspect the page, the `.highcharts-tooltip` element in the DOM has an opacity set to 1. Make sure to not hover the graph before inspecting, because after the tooltip is displayed it will fade to opacity 0.

**Comment by TorsteinHonsi** [comment]
Thanks for writing! 

What are the practical implications of this? You you see the tooltip in any browser? It has `display: none` so it should be hidden away.

**Comment by hjnilsson** [comment]
I see now that this does not effect version 5.0.0 (which I did not realize had been released! :) ), version 4.2.6 does not set `display: none`.

**Comment by TorsteinHonsi** [comment]
Yes, there was a bug in 4.2.6.
