### ISSUE TITLE
highstock drag cursor height wrong when defining xAxis.offset

### ISSUE THREAD

**Issue by mhwlng** [highcharts/highcharts#5753]
![wrong](https://cloud.githubusercontent.com/assets/1388886/18989350/ccf3f4f2-870b-11e6-9a12-19087b1b3f7b.png)

You can see in the picture that the 'drag to zoom' cursor doesn't go all the way down to the x-axis.

For each line in the stock chart, I define a separate y axis:
y.offset = 0;
y.top = yoffset;
yoffset += ...;

So that the charts are stacked, as you see in the picture.

This results in the x-axis being drawn in the wrong place.
(exactly where the drag cursor ends in the picture)

So, to fix that, I move the x-axis down:
trendchart.xAxis.offset = 110;

But that has no effect on the height of the drag cursor, as you can see in the picture.

So, the problem is that xAxis.offset should be considered in the height of the drag cursor.

**Comment by pawelfus** [comment]
Thank you for reporting the issue @mhwlng !
Have you considered to use height and top as percentages? Like in our demo: http://www.highcharts.com/stock/demo/candlestick-and-volume - it works fine with zooming: http://jsfiddle.net/r71jdt8b/

**Demo for the issue:** 
http://jsfiddle.net/jb0xm15m/ - it happens in general, not only in Highstock.

**Comment by mhwlng** [comment]
I'm showing a variable number of charts. 
from 1 to around 20 and export to pdf :
[Chart - Erasmus 162455.pdf]
(https://github.com/highcharts/highcharts/files/503280/Chart.-.Erasmus.162455.pdf)

I found that difficult to do with the %

**Comment by pawelfus** [comment]
Thank for the explanation. Could you recreate your issue on jsfiddle? That way I may be able to suggest a workaround for you. It looks like you are setting options which interfere with automatic calculation for plotting area's height. My demo show issue with to big selection-marker, but your screenshot suggests quite the opposite.

**Comment by mhwlng** [comment]
something like:

http://jsfiddle.net/mr9fnws1/14/

**Comment by pawelfus** [comment]
Just a lucky guess, but maybe you have an old version of Highcharts? Could you try 4.2.7 and 5.0.0 ? Thanks!

**Comment by mhwlng** [comment]
both jsfiddle and the 'real' system use 5.0.0.0

**Comment by pawelfus** [comment]
What I think is that you don't have to use `offset` in your case at all, xAxis is placed correctly: http://jsfiddle.net/mr9fnws1/15/

Actually, setting offset produces kind of a correct behaviour: 

- all yAxes have set `top`&`height` and that options have the highest priority
- xAxis has `offset`, so it should translate all yAxes to the top, but since `top`&`height` are set, it doesn't (it would change if using percentage values)
- all other calculations use `offset`, including selection-marker so that's the result with "wrong" height

**Comment by mhwlng** [comment]
for some reason the jsfiddle doesn't behave the same as the real system.
as soon as I remove the xOffset = 110 in the real system, the x axis moves up .
I can't reproduce it in jsfiddle yet.. sorry..
![untitled](https://cloud.githubusercontent.com/assets/1388886/19040804/e9109ace-8985-11e6-9fa1-d78f1630865d.png)

**Comment by pawelfus** [comment]
It's interesting.

Anyway, I think I found a workaround for you, please take a look: http://jsfiddle.net/m41eg1ss/

Try this this small plugin to change height of the selection-marker:


    (function(H) {
      H.wrap(H.Pointer.prototype, 'drag', function(p) {
        var chart = this.chart,
          extra = chart.xAxis[0].options.offset;

        chart.plotHeight += extra;
        p.apply(this, Array.prototype.slice.call(arguments, 1));
        chart.plotHeight -= extra;

      });
    })(Highcharts)

Let me know about the results! :)

**Comment by mhwlng** [comment]
Thank you :-)

With your plugin, the zoom cursor now has the correct height !

**Comment by pawelfus** [comment]
Great to hear that!

If you could recreate issue in jsFiddle, to get the same result as in your application, it would be great. Then we can made correct changes in the core.

**Comment by mhwlng** [comment]
I have now reproduced the problem 

here the x axis is in the wrong position without the xOffset

http://jsfiddle.net/mr9fnws1/22/

the x axis problem is related to chart.marginBottom=140

I didn't have that in my previous fiddle tests

**Comment by pawelfus** [comment]
I see. Why do you need `marginBottom`? Or rather why your calculations for yAxes doesn't respect that value? Of course, you can set bigger height than necessary (e.g.: http://jsfiddle.net/jb0xm15m/2/ ) - but I don't think it's a good idea..

**Comment by mhwlng** [comment]
>  Why do you need marginBottom? 

Good question :-) 

I now removed:
xAxis.offset = 110
chart.marginBottom = 140
and also your selection-marker plugin

and now all looks ok...

Thanks for your help !

**Comment by pawelfus** [comment]
Ok, great! I'm closing the ticket since I don't think we should change the current behaviour. Feel free to reopen if you find this necessary.
