### ISSUE TITLE
Wrong navigator width when resize

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5754]
#### Expected behaviour

Navigator should adapt to width.
#### Actual behaviour

Navigator is smaller then width
#### Live demo with steps to reproduce

Example:
- http://jsfiddle.net/eod1ggr9/

Steps to reproduce:
1. Run the demo
2. Resize window and observe navigator

![navigator2](https://cloud.githubusercontent.com/assets/2115686/18990252/eabb2f8c-8710-11e6-9680-03faea35cc9d.gif)

**Comment by pawelfus** [comment]
Used to work in 4.2.4: http://jsfiddle.net/eod1ggr9/1/

**Comment by pawelfus** [comment]
**Workaround:**
Change order of series: that way navigator will get data from actual series, not from just one flag: http://jsfiddle.net/sqf7z9df/


*Internal note:*
It's caused by `minRange` [here](https://github.com/highcharts/highcharts/blob/7209320d6289c5338f12a56b6a94f5e6ca33720e/js/parts/Scroller.js#L279-L282).

**Comment by TorsteinHonsi** [comment]
In the [redraw](https://github.com/highcharts/highcharts/blob/v5.0.0/js/parts/Scroller.js#L444-L452), it should probably consider the union extremes too, like it does when it first renders the navigator.

**Comment by pawelfus** [comment]
Found the real culprit:

Navigator sets extremes on xAxis = 0 [here](https://github.com/highcharts/highcharts/blob/v5.0.0/js/parts/Scroller.js#L667). Later in `redraw` [event](https://github.com/highcharts/highcharts/blob/v5.0.0/js/parts/Scroller.js#L447) we use `series.xAxis` to redraw the navigator. However, the first series is actually connected to the xAxis = 1, which has unchanged extremes, all the time the same (0.5 - 1.5). In other words we have that case: navigator sets extremes on xAxis[0], but listens to extremes on xAxis[1]. 

I don't know what was the real idea here, but setting `xAxis[1].linkedTo = 0` resolves the issue: http://jsfiddle.net/eod1ggr9/10/
