### ISSUE TITLE
Highstock styled mode version missing

### ISSUE THREAD

**Issue by 3Ue** [highcharts/highcharts#5756]
There is no styled mode highstock.js in highcharts-dist repository under js direcotry:
https://github.com/highcharts/highcharts-dist/tree/master/js

Is this by purpose? Where is it located?

Expected bevaviour:
The file
https://code.highcharts.com/stock/js/highstock.js
should be in the directory
https://github.com/highcharts/highcharts-dist/tree/master/js

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard The following files are missing: 
* `highmaps.js`
* `highmaps.src.js`
* `highstock.js`
* `highstock.src.js`

**Comment by dandv** [comment]
Also, there are no `/js/` files listed at https://code.highcharts.com/

**Comment by TorsteinHonsi** [comment]
> Also, there are no /js/ files listed at https://code.highcharts.com/

The [files are there](https://code.highcharts.com/js/highcharts.js), but we need to update the front page listing. @jon-a-nygaard
