### ISSUE TITLE
Trigger on addSeries that includes the series object

### ISSUE THREAD

**Issue by eggers** [highcharts/highcharts#5758]
There is currently an event triggered when a series is removed, but it would be nice to have another when the series is added so that I can get access to the SeriesObject.

I considered using the chart event addSeries (see #4758), however that event is fired before the series is created so I don't have access to the series object. I think that it would be as simple as adding a new fireEvent after initializing the series. See:

```js
       addSeries: function (options, redraw, animation) {
            var series,
                chart = this;

            if (options) {
                redraw = pick(redraw, true); // defaults to true

                fireEvent(chart, 'addSeries', { options: options }, function () {
                    series = chart.initSeries(options);

                    chart.isDirtyLegend = true; // the series array is out of sync with the display
                    chart.linkSeries();
                    if (redraw) {
                        chart.redraw(animation);
                    }
                    // New Event !!!!
                    fireEvent(series, 'add');
                });
            }

            return series;
        },

```

My motivation is to live update the series, but only when the series is actually added to the chart. However, with the current events I don't have access to the series object to call `setData` or `addPoint`.

**Comment by oysteinmoseng** [comment]
Instead of listening to the addSeries event you can `wrap` the chart.addSeries function. 

Example:
```javascript
Highcharts.wrap(Highcharts.Chart.prototype, 'addSeries', function (proceed, options, redraw, animation) {
    // Before addSeries
	var series = proceed.call(this, options, false, animation);
    // After addSeries

	if (Highcharts.pick(redraw, true)) {
		this.redraw();
	}
	return series;
});
```

See http://www.highcharts.com/docs/extending-highcharts/extending-highcharts.
