### ISSUE TITLE
Deprecated closurecompiler package

### ISSUE THREAD

**Issue by brock-noah** [highcharts/highcharts#5760]
#### Expected behaviour
successful `npm install`

#### Actual behaviour
`colsurecompiler` Java failure https://github.com/dcodeIO/ClosureCompiler.js/issues/50

If admin can verify [log output](https://gist.github.com/brock-noah/6bf37d5fb37d8a3d0c53764cc61b4bce) is acceptable, will re open PR to update to `closure-compiler`
https://github.com/highcharts/highcharts/pull/5759

**Comment by jon-a-nygaard** [comment]
Thanks for reporting. We are working on switching to an up to date package of the Closure Compiler.

@TorsteinHonsi I was thinking of using the [google-closure-compiler-js](https://github.com/google/closure-compiler-js), which is a pure JS and official version. We use it on github.highcharts.com to avoid managing Java. Do you think there any reason for us not to use the pure JS version?

**Comment by TorsteinHonsi** [comment]
Not at all, go for it! Check the diff and /or file sizes of the produced files afterwards to make sure the settings are the same.
