### ISSUE TITLE
Any plans to remove the jQuery dependency?

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#5761]
Congratulations on v5!

Any plans for a lighter build that no longer depends on jQuery, and drops support for old browsers, the way Plotly works?

**Comment by TorsteinHonsi** [comment]
Thanks!

> Any plans for a lighter build that no longer depends on jQuery
Highcharts dropped the *jQuery* dependency from version 4.2.0.

> drops support for old browsers
In [styled mode](http://www.highcharts.com/docs/chart-design-and-style/style-by-css), Highcharts drops support for old browsers. If you don't want to go all the way to a full separation of SVG from CSS, you can create your own light-weight builds from [the download page](http://www.highcharts.com/download), or [create your own custom builds](http://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files).

**Comment by dandv** [comment]
> Highcharts dropped the jQuery dependency from version 4.2.0.

Oh, I hadn't realized that. I didn't see the change in [the changelog](http://www.highcharts.com/documentation/changelog), and all examples and [documentation](http://api.highcharts.com/highstock) use $ pervasively.

**Comment by TorsteinHonsi** [comment]
> all examples and documentation use $ pervasively.

Yes, they use the jQuery plugin syntax, but it's just a convenience. Anyway, we're updating all the samples now to be less jQuery-like.

**Comment by dandv** [comment]
[This]( http://www.highcharts.com/products/highstock) should also be updated:

> The highstock.js core and either the jQuery, MooTools or Prototype framework. One of these frameworks is most likely already in use in your web page.

**Comment by TorsteinHonsi** [comment]
Thanks! Fixed.
