### ISSUE TITLE
Please document afterSetExtremes

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#5762]
The [documentation for afterSetExtremes](http://api.highcharts.com/highcharts/xAxis.events.afterSetExtremes) could be improved by mentioning what exactly is passed to that function, what `.min`, `.max`, `.dataMin` and `.dataMax` mean (selected interval vs. entire series), and what the measurement unit is (milliseconds since epoch).

**Comment by TorsteinHonsi** [comment]
Fixed, thanks!

**Comment by dandv** [comment]
The documentation says

> This contains common event information based on jQuery or MooTools depending on which library is used as the base for Highcharts.

What if neither of those two are used?

**Comment by sebastianbochan** [comment]
Now, Highcharts does not require any framework for support events.

**Comment by dandv** [comment]
@sebastianbochan, OK, so [that entry](http://api.highcharts.com/highcharts/xAxis.events.afterSetExtremes) should be updated.

**Comment by TorsteinHonsi** [comment]
Thanks! The change will go online as soon as we launch our new, JSDoc-powered API.

**Comment by dandv** [comment]
Related: would be good to hyperlink minPadding, maxPadding, endOnTick and startOnTick at https://api.highcharts.com/class-reference/global.html#Extremes
