### ISSUE TITLE
Can the rangeSelector.button.type be 'hour'?

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#5763]
http://api.highcharts.com/highstock/rangeSelector and http://api.highcharts.com/highstock/rangeSelector.buttons.type don't mention `hour` as a possible type for the rangeSelector buttons.

However, the [lazy loading example](http://www.highcharts.com/stock/demo/lazy-loading) does use `type: 'hour'`.

**Comment by oysteinmoseng** [comment]
Added to docs.

**Comment by dandv** [comment]
@oysteinmoseng: thanks.

1. How about adding "hour" to the *buttons* section http://api.highcharts.com/highstock/rangeSelector as well?
2. BTW, the defaults for button appear twice there.
3. Is there a repo where we can submit PRs for docs changes?

**Comment by oysteinmoseng** [comment]
1. Done.
2. This looks wrong. @larsac07
3. Unfortunately not, but feel free to report issues here and we will look into them.

**Comment by larsac07** [comment]
Looking into duplicate buttons

**Comment by larsac07** [comment]
Removed the duplicate buttons options which was a leaf node. Same information still exists in http://api.highcharts.com/highstock/rangeSelector.buttonTheme/rangeSelector.buttons. Thanks, @dandv for notifying :)
