### ISSUE TITLE
Pie drilldowns not working since last release

### ISSUE THREAD

**Issue by QuentinPolantis** [highcharts/highcharts#5764]
Hello,

I'm currently facing a weird problem: my pie with drilldowns are not working anymore since the last 5.0 release. In order to fix this, i've to include both highchart and highstock js file while highstock was enough. Has something been removed in Highstock?

However, it is well specified in #16 error that "that the Highcharts.Chart constructor and all features of Highcharts are included in Highstock".

More specifically, the main pie is correctly drawed and the drilldowns are well initialized. The issue appears when i click on a specific pie to trigger drilldown : nothing is happening and i'm getting the following error: 
"Uncaught TypeError: Cannot read property 'options' of undefinedq.addSingleSeriesAsDrilldown @ drilldown.js:13q.addSeriesAsDrilldown @ drilldown.js:11(anonymous function) @ drilldown.js:22a.fireEvent @ highstock.js:28e.Point.doDrilldown @ drilldown.js:21(anonymous function) @ drilldown.js:24a.fireEvent @ highstock.js:28firePointEvent @ highstock.js:266onContainerClick @ highstock.js:206b.onclick @ highstock.js:207"

I guess all the browsers are affected by this issue (I've tried on Firefox and Chrome lastest release, IE 10 and Safari).

Does someone face a similar problem?

 Thanks in advance,

Quentin

**Comment by pawelfus** [comment]
Hi @QuentinPolantis 

Thank you for reporting the issue. You are right, it is broken, demo: http://jsfiddle.net/jr9fp5p0/

**Comment by QuentinPolantis** [comment]
Thank you for your speed and reliability. 

Do you know when you are gonna push these modifications on the CDN?

**Comment by TorsteinHonsi** [comment]
You're welcome! We'll probably be out with a maintenance release within a week or two.
