### ISSUE TITLE
Marker on hover with shared tooltip appears inconsistently

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5766]
#### Expected behaviour
Hovering over point causes showing the marker - even if the data is dense.
http://jsfiddle.net/2tjq74te/6/

#### Actual behaviour
With shared tooltip the marker is not always displayed over hovered point.

#### Live demo with steps to reproduce
http://jsfiddle.net/2tjq74te/7/

**Comment by pawelfus** [comment]
*Internal note:*
Fails since 27f81b87229409146a146a110b6df62d53d8c703

**Comment by idrm** [comment]
The affected marker is always the one that would normally capture the hover state were the tooltip not shared (tested in version 5.0.0).

**Comment by pawelfus** [comment]
Hi @idrm 

Thank you for your feedback. Actually, datetime axis was not important, but number of points: http://jsfiddle.net/dk6x2phu/

@TorsteinHonsi - could you review the commit above before releasing 5.0.1? It also cleans up `runPointActions` method..
