### ISSUE TITLE
Highstock: rangeSelector input is decreased by one hour

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5767]
#### Expected behaviour

Setting a date that was typed.
#### Actual behaviour

Date is decreased by 1 hour.
#### Live demo with steps to reproduce

http://jsfiddle.net/jps9ykhh/2/
1. Use `from` or `to` input and set a date that is in data range. (e.g. change hours to `05` in `from`)
2. After pressing enter the date will be decreased by 1 hour. (e.g. will give `1970/01/01/04:00:00.000`)

**Comment by pawelfus** [comment]
**Workaround:**

Use [inputDateParser](http://api.highcharts.com/highstock/rangeSelector.inputDateParser), demo: http://jsfiddle.net/chn6tjfb/

    rangeSelector: {
      inputBoxWidth: 170,
      inputDateFormat: '%Y/%m/%d/%H:%M:%S.%L',
      inputEditDateFormat: '%Y/%m/%d/%H:%M:%S.%L',
      inputDateParser: function(value) {
      	var time = value.split(/[:\.\/]/);

        return Date.UTC(
          parseInt(time[0], 10),
          parseInt(time[1], 10) - 1,
          parseInt(time[2], 10),
          parseInt(time[3], 10),
          parseInt(time[4], 10),
          parseInt(time[5], 10),
          parseInt(time[6], 10)
        );
      }
    },
