### ISSUE TITLE
Calling `setData` on a chart with `xAxis.type = category` strips dataLabels from chart

### ISSUE THREAD

**Issue by hjnilsson** [highcharts/highcharts#5768]
#### Expected behaviour
Calling `setData` on a series with a data array with more points than earlier should update the series with more points and still display the category labels.

#### Actual behaviour
The category labels are removed and replaced with the index of the series.

#### Live demo with steps to reproduce
http://jsfiddle.net/fu6xabxw/

Click the button, the dataLabels will change to the index of the point rather than the name of the point.

This broke in 4.2.7, Highcharts 4.2.6 behavior here: http://jsfiddle.net/fu6xabxw/1/

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! Related to #5720.

**Comment by hjnilsson** [comment]
Excellent, when is the next version scheduled to be released?

**Comment by TorsteinHonsi** [comment]
It will probably be out within a week or two.
