### ISSUE TITLE
Area chart with `null` value and drilldown.js imported.

### ISSUE THREAD

**Issue by Starzu** [highcharts/highcharts#5769]
#### Expected behaviour
Area chart with `null` value should display normally. 

#### Actual behaviour
Chart is broken. Take a look at the fiddle example. 

#### Live demo with steps to reproduce
http://jsfiddle.net/q77dk4mc/2/

#### Affected browser(s)
Tested on Chrome and Firefox

**Comment by oysteinmoseng** [comment]
Thank you for reporting this.

**Comment by pawelfus** [comment]
Already fixed on the master branch: http://jsfiddle.net/q77dk4mc/3/
