### ISSUE TITLE
boxplot / fillColor for a specific point does not work

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5770]
#### Expected behaviour
http://jsfiddle.net/w2mmcjd6/

#### Actual behaviour
For a boxplot series, point's fillColor does not work. This is regression from 4.2.7 version.

#### Live demo with steps to reproduce
http://jsfiddle.net/w2mmcjd6/1/

**Comment by oysteinmoseng** [comment]
Thank you for reporting this.
