### ISSUE TITLE
Enable contributors to submit documentation PRs easily

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#5771]
It would be great if documentation pages had an "edit" link that pointed to the corresponding GitHub file.

This approach has been successfully adopted by MongoDB ([example](docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/)) and InfluxDB, to cite just two examples from the charting space.

PS: the link to GitHub at the very bottom of doc pages ([example](http://www.highcharts.com/docs/chart-design-and-style/style-by-css)) is the old https://github.com/highslide-software/highcharts.com

**Comment by oysteinmoseng** [comment]
@larsac07

**Comment by TorsteinHonsi** [comment]
> It would be great if documentation pages had an "edit" link that pointed to the corresponding GitHub file.

Currently the docs are not served by GitHub, but it is something we have considered.

@larsac07 @gvaartjes What if we add one JSON(ish) file for each config object? So for example, all options for plotOptions.series.dataLabels would be contained in a single file. The files would be parsed and added to mongoDB via an update script. 

Among the pros would be full version control, revision control and ability to do PRs.

One drawback would be that we disable the visual editor which has hints for the property names, and in-the-face comparison between Highcharts, Highmaps and Highstock.

**Comment by gvaartjes** [comment]
@LindaSve93 can you fix the Github icon in highcharts.com footer?

**Comment by gvaartjes** [comment]
@TorsteinHonsi 
Why would we have drawbacks if we parse the GitHub files into MongoDB. Then we would have the same database as today.

**Comment by TorsteinHonsi** [comment]
@gvaartjes No, I am talking about the visual editor for the API, where we click the edit icons next to the options and edit Highcharts, Highstock and Highmaps side by side. Yes we will have the same database as today, but we can't make edits in the API's visual editor because it will be overridden by imported stuff from GitHub. Unless of course we make it a two-way sync. But I think that's not what we want. Perhaps better is that we add consistency checks on node/gulp, and maybe even utilities like copy to Highstock and copy to Highmaps.

Remember why we wrote the API application in the first place - the old flat file structure became bloated and hard to maintain. And making it easy for the devs to maintain the docs is super important.

**Comment by gvaartjes** [comment]
>  but we can't make edits in the API's visual editor because it will be overridden by imported stuff from GitHub.
- We could rebuild the API editor to highlight/diff differences between highcharts,stock and maps. and add links to the relevant Github files, and update them there? Would that work?
- About syncing changes, I think markdown should work
1. Markdown files on Github, for easy editing
2. Parse markdown to JSON and import to our API database. See for example this tool: https://github.com/sparkartgroup/gulp-markdown-to-json

**Comment by TorsteinHonsi** [comment]
> We could rebuild the API editor to highlight/diff differences between highcharts,stock and maps. and add links to the relevant Github files, and update them there? Would that work?

Absolutely. So the current editor basically becomes a validator. I think that's a good approach.

**Comment by larsac07** [comment]
OK, so let me clarify:

1. We move editing to a set of `configObject.md` files which are parsed to JSON, and then imported to our API database
2. We transform our existing API editor to a simple diff-tool between our High* libraries

If this is the case, I have two concerns:

1. Where and how would we store the `configObject.md` files? We would probably need to store them in a tree-structured folder system, emulating the treegrid of the API
2. How do we manage synchronization between api.highcharts.com, code.highcharts.com and github.com/highcharts/highcharts? When we update `master`, sometimes we might not be ready to update the API, because code push to code.highcharts.com is delayed, while other times we need to make immediate changes to errors in the API. For the most part, we want things to be automatic and safe, but we should also be able to make "live" changes

Consistency and quality of the MD files is also a concern, but if we use the edtior as a validator, as @TorsteinHonsi suggested, people can at least check that their edits are valid before committing.

**Comment by TorsteinHonsi** [comment]
First of all, are we sure we want to keep the files in markdown format? By keeping them in json, we can put them directly into the database, and we don't have to do any changes to today's structure. Also, I am not sure there is much value in providing the data as .md. Reading the docs from GitHub directly is not recommended, as all inherited options will be lost.

> Where and how would we store the configObject.md files? We would probably need to store them in a tree-structured folder system, emulating the treegrid of the API

Yes, that would make sense. I think we should make one file per `object` of the API. So either a flat structure:
```
plotOptions.md
plotOptions.series.md
plotOptions.series.dataLabels.md
```
or a tree structure
```
/plotOptions.md
/plotOptions
    /series.md
    /series
        /dataLabels.md
```
I think I prefer the first one...

> How do we manage synchronization

We need a script that an administrator can run after changes have been done to the source data. There are two scenarios to keep in mind: 1) Occasional changes and bug fixes between releases and 2) Major changes for each release. In case 2, we may have made a lot of API changes in a separate branch, and on release we sync all of these to the online API.

**Comment by larsac07** [comment]
@TorsteinHonsi I agree that keeping the files in JSON would be better. MD seems less optimal for a structured format. It's nicer to read, but probably more likely to contain structural typos, leading to weird parsing results.

```
some.member.name.json
some.other.member.name.json
```
is a great idea. Easier to navigate in most editors and IDEs, and easier to load into database.

**Comment by gvaartjes** [comment]
@larsac07 
Yes but it's very unpractical to edit the JSON file,  I don't think if this the most user-friendly way to let the community contributing to our documentation.

**Comment by larsac07** [comment]
@gvaartjes 
I think that is true when it comes to option descriptions:
```
{
    title: 'chart',
    description: 'Options regarding the chart area and plot area as well as general chart options.'
    options: [{
        title: 'alignTicks',
        returnType: 'Boolean',
        defaults: true,
        description: '<p>When using multiple axis, the ticks of two or more opposite axes will automatically be aligned by adding ticks to the axis or axes with the least ticks, as if <code>tickAmount</code> were specified.</p>' + 
                     '<p>This can be prevented by setting <code>alignTicks</code> to false. If the grid lines look messy, it's a good idea to hide them for the secondary axis by setting <code>gridLineWidth</code> to 0.</p>',
        demos: [
            ['True by default', 'http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/alignticks-true/'],
            ['false', 'http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/alignticks-false/']
    }, {
        title: 'animation',
        returnType: 'Boolean|Object',
        defaults: true,
        description: '<p>Set the overall animation for all chart updating. Animation can be disabled throughout the chart by setting it to false here. It can be overridden for each individual API method as a function parameter. The only animation not affected by this option is the initial series animation, see <a class="internal" ref="#plotOptions.series.animation">plotOptions.series.animation</a>.</p>' +
                     '<p>The animation can either be set as a boolean or a configuration object. If <code>true</code>, it will use the 'swing' jQuery easing and a duration of 500 ms. If used as a configuration object, the following properties are supported: </p>' +
                     '<dl>' +
                         '<dt>duration</dt>' +
                         '<dd>The duration of the animation in milliseconds.</dd>' +
                         '<dt>easing</dt>' +
                         '<dd>A string reference to an easing function set on the <code>Math</code> object. See <a href="http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-animation-easing/">the easing demo</a>.</dd>' +
                     '</dl>',
        demos: [
            ['Updating with no animation', 'http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/animation-none/'],
            ['with a longer duration', 'http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/animation-duration/'],
            ['with a jQuery UI easing', 'http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/animation-easing/']
    }, {
    ...
    }]
}
```

But look at how easy it is to introduce differences in formatting with MD:

```
# chart
Options regarding the chart area and plot area as well as general chart options.

## alignTicks
returnType: Boolean
defaults to true
When using multiple axis, the ticks of two or more opposite axes will automatically be aligned by adding ticks to the axis or axes with the least ticks, as if tickAmount were specified.

This can be prevented by setting alignTicks to false. If the grid lines look messy, it's a good idea to hide them for the secondary axis by setting gridLineWidth to 0.
Defaults to true.

## animation: Boolean|Object
Set the overall animation for all chart updating. Animation can be disabled throughout the chart by setting it to false here. It can be overridden for each individual API method as a function parameter. The only animation not affected by this option is the initial series animation, see [plotOptions.series.animation](http://api.highcharts.com/highcharts/chart#plotOptions.series.animation).

The animation can either be set as a boolean or a configuration object. If `true`, it will use the 'swing' jQuery easing and a duration of 500 ms. If used as a configuration object, the following properties are supported:

* duration - The duration of the animation in milliseconds.
* easing - A string reference to an easing function set on the `Math` object. See the [easing demo](http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-animation-easing/).

Defaults to `true`.
Try it:
[Updating with no animation](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/animation-none/), [with a longer duration](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/animation-none/), [with a jQuery UI easing](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/animation-none/).
```

I think we would have a hard time enforcing a style and format for documentation in MD, even for in-house developers.

**Comment by dandv** [comment]
The vast majority of projects on GitHub use Markdown. Interesting that it poses problems for HighCharts. Would it need a [Markdown linter](https://www.google.com/search?q=markdown+linter)?

**Comment by larsac07** [comment]
@dandv for APIs? Documentation I get, but pure API references?

**Comment by jon-a-nygaard** [comment]
API is now generated from JSDoc comments in our code, which means it is now possible to contribute to our [api.highcharts.com](https://api.highcharts.com) by submitting PR's.

The idea of having our [documentation articles](https://www.highcharts.com/docs) as markdown files on GitHub seems very interesting to me. I would be glad to investigate this alternative, if you are interested @gvaartjes and @TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
Yes we are interested. We are about to start a big revision of the docs and we need to weigh the benefit of developers feeling at home on GitHub markdown, and the marketing benefits of publishing it on Wordpress. A middle way could be to write it in markdown and publish it on WordPress through some kind of plugin. @mekhatria FYI.
