### ISSUE TITLE
Lost series state when mouseout although hover is disabled

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#5775]
#### Expected behaviour
When I set a state and don't let the chart change other states, keep it until I unset it.

#### Actual behaviour
When I mouseout the series, the state is lost.

#### Live demo with steps to reproduce
http://jsfiddle.net/QNPYP/126/

#### Affected browser(s)
Any, I guess.

**Comment by Llorx** [comment]
I have to add, I don't want to use series.update() as there are chances of having tons of data (I don't have any control over it) and each update takes some seconds to end. I prefer to use setState to change the lineWidth as it changes almost instantly.

**Comment by Llorx** [comment]
I had to do a small hack (changing the lineWidth options and toggling the state so it is applied): http://jsfiddle.net/QNPYP/127/

**Comment by oysteinmoseng** [comment]
Since `series.setState` is not a public API function, this is not really a bug.

But since you are hacking anyway, another workaround would be to wrap the mouseOut handler of the series and apply the state again there. http://jsfiddle.net/QNPYP/128/

**Comment by Llorx** [comment]
Great.

Another question (as we are talking about changing styles avoiding redraws). I'm trying to change the yAxis labels style too. The problem that I encounter is that, using only public methods, I can only change it with update(), redrawing everything too. Is there any hack to change the style, only updating its CSS attributes, without redraw? I'm checking the source code but not discovering any way of doing it without applying the styles directly to the chart. I want this, but without update:
```
chart.get(AXISID).update({
    labels: {
        style: {
            fontWeight: NEWWEIGHT
        }
    }
});
```

**Comment by TorsteinHonsi** [comment]
Hi, you can set the styles programmatically. A potential problem, as you see, is that the chart will not redraw around the new bounding boxes: http://jsfiddle.net/highcharts/9kzdaezt/

But if you only set the font-weight that shouldn't be much of a problem.
