### ISSUE TITLE
Drilldown with Highstock 5.0.0

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#5778]
#### Behaviour
The first click on the ‘Mon’ column with drilldown causes an error: ‘Cannot read property 'options' of undefined’. If the click occurs on a xAxis label, drilldown success but trying to drillup results in one of these two errors: ‘Cannot read property 'chart' of undefined’ and ‘Cannot read property 'levelNumber' of undefined’. With Highstock v4.2.7 and Highcharts v5.0.0 everything works as it should.

#### Live demos with steps to reproduce
http://jsfiddle.net/xz5kmo5u/2/ - Highstock v4.2.7
http://jsfiddle.net/xz5kmo5u/3/ - Highstock v5.0.0 (error)
http://jsfiddle.net/xz5kmo5u/4/ - Highcharts v5.0.0

**Comment by PaulDalek** [comment]
#### [EDIT]
Works with Github version.

**Comment by rschiavi** [comment]
Any chance to get more detail on how to get the github version installed, working, or what the patch/fix is to apply to the current 5.0.6 release?

**Comment by TorsteinHonsi** [comment]
v5.0.6 was released after PaulDalek's comment from 4 Oct 2016, so the fix should be in the stable release now.
