### ISSUE TITLE
Mobile devices / button zoom out does not work

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5779]
#### Actual behaviour
On mobile devices the button which resets zoom does not work. This is regression from 4.2.7 version. It might have something with the button's event handler because chart.zoomOut() works fine.

#### Live demo with steps to reproduce
https://jsfiddle.net/ajcvvc8x/7/
On a mobile device, zoom in and try to use Highcharts' zoom out button - it does not work.
Chart.zoomOut() seems to work correctly.

#### Affected browser(s)
HTC Desire 500, Android 4.1.2, Chrome
iPhone 7, iPad mini 2

**Comment by sebastianbochan** [comment]
_**Workaround**_

Catch redraw event and attach "touchstart" event to the resetZoomButton.

Example:
 - https://jsfiddle.net/k224Lrew/
