### ISSUE TITLE
Highcharts not loading to width of the parent div

### ISSUE THREAD

**Issue by panickerr** [highcharts/highcharts#5783]
#### Expected behaviour

**Chart loads in the same size as the parent.**
Have used  width: 95% and height:75vh to the div in which highchart loads
`<div id="g1" style="width: 95% ;height:75vh"  ></div>`
#### Actual behaviour

**Chart always exceeds the parent div onload.**
On landing on the page the chart when loaded is exceeding the parent div. But when i call the function again it refreshes and fits in the parentdiv. So to make sure it fits in the parent div i am forced to call the function twice while initializing in which case the first call gives a zoomed version of highcharts and the successive second load gives the version that fits in the div. 
#### Affected browser(s)

Firefox, Chrome

**Comment by pawelfus** [comment]
Hi @panickerr 

Could you recreate issue in jsFiddle? I created a simple demo: http://jsfiddle.net/7hq7nwu9/ - looks fine (latest Chrome + OSX). 

Thanks!

**Comment by JllyGrnGiant** [comment]
@pawelfus @panickerr 
I believe I am experiencing this issue as well.

If you render the chart in a JQuery Element in memory then add that element to the page there's an issue with size post v5.0.10.

Expected:
http://jsfiddle.net/5dg1ojft/2/

Actual:
http://jsfiddle.net/nws9oo9L/2/

**Comment by sebastianbochan** [comment]
**Workaround**
Call [setSize](http://api.highcharts.com/highstock/Chart.setSize) after appending container:
- http://jsfiddle.net/3z0stcfe/

**Comment by TorsteinHonsi** [comment]
This happens because in v5.0.10, the container was first moved to a temporary div in the document, then the chart rendered. In v5.0.11 we reformatted it to preserve the DOM structure but rather temporary display all elements in order to read the text bounding boxes. That's why it doesn't work correctly now, because the container is detached from the DOM all the way. 

Here's a demo without jQuery: http://jsfiddle.net/highcharts/3z0stcfe/1/

**Comment by anupbangale** [comment]
So we can resize it after rendering on the web by using.

`window.dispatchEvent(new Event('resize'));`

it worked in my case.

**Comment by GuppuBoss** [comment]
> But we can resize it after rendering on the web by using.
> `window.dispatchEvent(new Event('resize'));`
> So it will resize and redraw the graph by considering the div width.
> 
> Like:-
> 
> ```
> $('#container').highcharts({this.optionsObject});
> window.dispatchEvent(new Event('resize'));
> ```
> 
> It is something like tricky but It worked for me.

Worked for me.
added it on ngOnInit
Thanks
