### ISSUE TITLE
chart.mapTransforms is undocumented

### ISSUE THREAD

**Issue by mgol** [highcharts/highcharts#5786]
#### Expected behaviour
`chart.mapTransforms` should be documented.

#### Actual behaviour
Changelog links to http://api.highcharts.com/highcharts/chart.mapTransforms which shows `chart` docs without the `mapTransforms` option present

#### Live demo with steps to reproduce

N/A

#### Affected browser(s)
N/A

**Comment by oysteinmoseng** [comment]
I beg to differ! http://api.highcharts.com/highmaps/chart.mapTransforms

The changelog has the wrong link, though.

**Comment by TorsteinHonsi** [comment]
Changelog updated.

**Comment by mgol** [comment]
Ah, that explains it. Thanks. :)
