### ISSUE TITLE
The chart.reflow option has no effect

### ISSUE THREAD

**Issue by mgol** [highcharts/highcharts#5787]
#### Expected behaviour
`chart.reflow` should prevent the map from auto-fitting into the container on its size change

#### Actual behaviour
The docs at http://api.highcharts.com/highmaps/chart.reflow link to two fiddles that behave in the same way, contrary to the description

#### Live demo with steps to reproduce

Links are in the doc, see the "Actual behavior" section

#### Affected browser(s)
At least Chrome & Firefox, I suspect all browsers.

**Comment by oysteinmoseng** [comment]
Thanks for reporting.

This is a HC5 regression.
