### ISSUE TITLE
setData - artefacts when redraw is false

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5788]
#### Actual behaviour

Artefacts appears, when redraw flag is false
#### Live demo with steps to reproduce
1. http://jsfiddle.net/dets6joh/
2. Click on 1W
3. Artefacts appear
#### Affected browser(s)

All browsers

_**Workaround**_
- disable animation: http://jsfiddle.net/agd6p95e/
- set redraw flag as true: http://jsfiddle.net/rgk3mv70/

**Comment by oysteinmoseng** [comment]
Worked in 4.2.5. http://jsfiddle.net/dets6joh/1/

**Comment by sebastianbochan** [comment]
Animations are supported since 4.2.6, in 4.2.5 didn't exist.

**Comment by oysteinmoseng** [comment]
Duh.

**Comment by pawelfus** [comment]
Minified demo: http://jsfiddle.net/4acv8904/

Looks like something is wrong with `sixify`.

**Comment by sebastianbochan** [comment]
Next scenario:
1. http://www.highcharts.com/stock/demo/spline
2. Click fast buttons 6m and 3m

![artefacts](https://cloud.githubusercontent.com/assets/2115686/20388467/3e33a642-acc5-11e6-8ef0-ca0475e8c48d.gif)
