### ISSUE TITLE
Chart.mapZoom doesn't seem to work

### ISSUE THREAD

**Issue by mgol** [highcharts/highcharts#5791]
#### Expected behaviour
`Chart.mapZoom` should zoom the map when passed a single parameter.

#### Actual behaviour
`Chart.mapZoom` always zooms the map out completely regardless of what parameter it gets passed or if we even invoke it without parameters at all (the signature theoretically incorrect according to the docs).

#### Live demo with steps to reproduce

http://jsfiddle.net/jdffqxnL/

#### Affected browser(s)
Chrome 53, Firefox 49, probably all browsers.

**Comment by pkc112** [comment]
Hi mgol,
what i observed was the paramenter that you should pass to mapZoom(x),  

> x should be (size of chart you want / size of present chart ) not sure just rough observation
 so if you want zoom out then pass value >1 and for zoom in pass < 1

i saw you were passing 

- 1 ---> this will result in same size.

- 2 ---> works as zoom out.

- 999999 ---> may be too heavy to zoom.

- nothing ---> will take to original size.


please look at working example http://jsfiddle.net/jdffqxnL/

**Comment by oysteinmoseng** [comment]
See @pkc112's example above. The `howMuch` parameter is a fraction of current view, where less than 1 zooms in and more than 1 zooms out.

**Comment by mgol** [comment]
Thanks for the explanation. As I indicated, however, the `howMuch` parameter is specified as required so the docs should still be fixed and should describe what happens for parameter-less invocation of the method.

**Comment by oysteinmoseng** [comment]
Yes, docs should be updated now.
