### ISSUE TITLE
Styled Mode (SASS Only Partially Working)

### ISSUE THREAD

**Issue by LarryAzevedo** [highcharts/highcharts#5792]
#### Expected behaviour
I was expecting to see the line colors change and the font family change.

#### Actual behaviour
Nothing changed except the point colors.

#### Live demo with steps to reproduce
https://jsfiddle.net/larryazevedo/f184pebj/
All I did was edit the `$colors` array and added _georgia_ to `.highcharts-container`'s font-family.

#### Affected browser(s)
Firefox 49 on OS X El Capitan Version 10.11.6
Chrome 53 on OS X El Capitan Version 10.11.6
Safari 9 on OS X El Capitan Version 10.11.6

**Comment by oysteinmoseng** [comment]
You were loading the "unstyled" version of Highcharts.js, try `code.highcharts.com/js/highcharts.js` for the styled version. https://jsfiddle.net/f184pebj/5/

Also see http://www.highcharts.com/docs/chart-design-and-style/style-by-css.
