### ISSUE TITLE
Not able to use getSVG() for external use

### ISSUE THREAD

**Issue by pkc112** [highcharts/highcharts#5793]
#### Expected behaviour
on console we should get the SVG printed

#### Actual behaviour
Showing error "Cannot read property 'style' of undefined"

#### Live demo with steps to reproduce

http://jsfiddle.net/8h2dcoL9/2/

#### Affected browser(s)

Not sure

**Comment by oysteinmoseng** [comment]
`getSVG` needs to be called on an instance, try this: http://jsfiddle.net/LLExL/6573/.

**Comment by pkc112** [comment]
@oysteinmoseng can you show in my fiddle how to get SVG i am not getting it

**Comment by oysteinmoseng** [comment]
@pkc112 Here is one way, http://jsfiddle.net/8h2dcoL9/3/. I'm not familiar with the details of `highcharts-ng` though, as it is not made by us. There might be better ways to obtain an instance of the chart, but you would have to consult the `highcharts-ng` documentation for more details.

**Comment by pkc112** [comment]
@oysteinmoseng , Thanks it worked
