### ISSUE TITLE
No "addPoints" method

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#5796]
http://www.highcharts.com/docs/working-with-data/live-data mentions "addPoints", which would be a nice method to have, but only `addPoint` is documented.

**Comment by oysteinmoseng** [comment]
Thanks for the feedback. You could easily add your own addPoints method, e.g. like this: http://jsfiddle.net/g4w8zjcp/, but perhaps we should create one in Highcharts too? @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Sorry for that, it was a typo in the docs article. As Øystein indicated, you simply run addPoint in a loop and defer the redraw.
