### ISSUE TITLE
The "Resize by jQuery UI resizable" demo doesn't work

### ISSUE THREAD

**Issue by mgol** [highcharts/highcharts#5798]
#### Expected behaviour

Demos linked from the documentation should work.
#### Actual behaviour

The docs at http://api.highcharts.com/highmaps/Chart.setSize link to a fiddle where the code fails with:

```
Uncaught TypeError: $(...).resizable is not a function
```

and the map is not resizable. jQuery UI doesn't seem to be included in the page at all.
#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/maps/members/chart-setsize-jquery-resizable/
#### Affected browser(s)

All

**Comment by oysteinmoseng** [comment]
Thank you for reporting this.

**Comment by TorsteinHonsi** [comment]
It is a manifestation of [jsFiddle issue #895](https://github.com/jsfiddle/jsfiddle-issues/issues/895). We use this patterns in several demos, so we'll wait some time to see if jsFiddle fixes it before we work around it. 

To see how the demo is supposed to work, jQuery UI can be added in a script tag: http://jsfiddle.net/highcharts/8279rq80/

**Comment by pawelfus** [comment]
Fixed in jsFiddle.
