### ISSUE TITLE
Using a <span style=fontsize: ...> to increase the label size offsets their position

### ISSUE THREAD

**Issue by maxupp** [highcharts/highcharts#5799]
#### Expected behaviour
Labels should simply increase in size but maintain their alignment when increasing fontsize. At the very least they should not shift entirely.

#### Actual behaviour
Increasing label size significantly shifts the labels partially or entirely upwards out of their respective segments.

#### Live demo with steps to reproduce
http://jsfiddle.net/41ddj5jy/

#### Affected browser(s)
tested on current Chrome, IE11 and Opera, all exhibiting the same behavior

**Comment by rja71** [comment]
Hello,

I think you should addthis option in dataLabels:
`useHTML: true`
It seems to solve the problem.

Best regards,

**Comment by oysteinmoseng** [comment]
As @rja71 mentions above, `useHTML` will solve the issue. If you prefer to use SVG, you can set the [style](http://api.highcharts.com/highcharts/series%3Cline%3E.dataLabels.style) property of the labels. Example: http://jsfiddle.net/41ddj5jy/1/.
