### ISSUE TITLE
Updating series with tooltip.split causes artifacts

### ISSUE THREAD

**Issue by jschuler** [highcharts/highcharts#5801]
#### Expected behaviour
After updating series and tooltip.split is set to true, there should be no artifacts visible on the chart

#### Actual behaviour
Artifacts are visible

#### Live demo with steps to reproduce
http://jsfiddle.net/hsgfwe3v/1/

1. Hover over series, tooltip looks good
2. Click some of the toggle buttons
3. Now when hovering over the series, can see artifacts

![image](https://cloud.githubusercontent.com/assets/869106/19194138/bd92bbdc-8c7a-11e6-88c9-6f17a6002c6b.png)

#### Affected browser(s)
Seen in Chrome

**Comment by alanyjw** [comment]
I came across this issue in Highstocks too, and have tested that this fix works for both.

**Comment by alanyjw** [comment]
I came across a similar issue in Highstocks, and have tested that this fix works for both.
