### ISSUE TITLE
StyleMode: axis style are ignored 

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#5802]
CSS style are ignored on axis, instead element style are applied 
label color and size is ignored: http://jsfiddle.net/onemenny/ukn6mh6r/

**Comment by oysteinmoseng** [comment]
You are not loading the styled version of Highcharts, try loading from http://code.highcharts.com/js/highcharts.js. Example: http://jsfiddle.net/ukn6mh6r/1/. Also see our documentation on [Styled Mode](http://www.highcharts.com/docs/chart-design-and-style/style-by-css)
