### ISSUE TITLE
`Series.update({})` triggers `afterSetExtremes` for X and Y axes

### ISSUE THREAD

**Issue by w3rs** [highcharts/highcharts#5803]
#### Expected behaviour

If I understand correctly, nothing is changed with `Series.update({})` , so `afterSetExtremes` shouldn't be invoked.
#### Actual behaviour

`Series.update({})` triggers `afterSetExtremes` for X and Y axes
#### Live demo with steps to reproduce

http://jsfiddle.net/4q380fjL/
#### Affected browser(s)

Chromium

**Comment by oysteinmoseng** [comment]
Thank you for reporting this. With an empty object as argument, `series.update` will redraw the existing series from scratch, which triggers the event. Not sure if we should consider this expected behavior or not.

Do you have a specific use case where you would expect `series.update({})` to do nothing?

**Comment by w3rs** [comment]
Here is the real case (but no jsfiddle): I have `area` series with color zones, and I have function like this:

    function updateZones() {
        myAreaSeries.update({
          zones: calculateZones();
        });
    }
    ...
    new Highcharts.StockChart({
      ...
      xAxis: { events: { afterSetExtremes: updateZones } },
      chart: { events: { load: updateZones } }
    }

So after chart is loaded, `updateZones` is called, and it triggers `afterSetExtremes`, and then `updateZones` is called once again, so I end up setting zones two times without need.

Also, for my case, `myAreaSeries.update({})` triggers regrouping for all series (e.g. from daily into weekly groups), but I'm not sure I can construct reproducible example easily.

**Comment by pawelfus** [comment]
**Workaround:**

Set `axis.extKey` after axis is rendered for the first time: http://jsfiddle.net/tz3dmjuz/

Drop-in fix: 

    (function(H) {
      H.wrap(H.Axis.prototype, 'render', function(p) {
        p.apply(this, Array.prototype.slice(arguments, 1));
        this.extKey = this.min + ',' + this.max;
      });
    })(Highcharts);
