### ISSUE TITLE
how can i set candlestick chart like this?

### ISSUE THREAD

**Issue by longboy** [highcharts/highcharts#5805]
When the data is low, how to set like this?
![02](https://cloud.githubusercontent.com/assets/6941888/19229107/8fbe750e-8efd-11e6-8cff-21969a40a4eb.jpg)

code link: http://jsfiddle.net/f6dkap6g/1/

**Comment by oysteinmoseng** [comment]
Please refer to our [support forum](http://forum.highcharts.com/) or [stackoverflow](http://stackoverflow.com/questions/tagged/highcharts) for programming and configuration questions.
