### ISSUE TITLE
title change to upper char

### ISSUE THREAD

**Issue by TangHuanan** [highcharts/highcharts#5806]
#### Expected behaviour
![image](https://cloud.githubusercontent.com/assets/4714386/19229457/423ef882-8f00-11e6-8333-2c22236d73b0.png)

![image](https://cloud.githubusercontent.com/assets/4714386/19229440/1545c522-8f00-11e6-8d15-5bfad1a972a2.png)

#### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/4714386/19229389/bd69d5b4-8eff-11e6-954f-7fe6ec29e408.png)

![image](https://cloud.githubusercontent.com/assets/4714386/19229468/641efc90-8f00-11e6-8b57-6669d151f9ea.png)

I am not sure it is related to this error

#### Affected browser(s)

chrome

**Comment by oysteinmoseng** [comment]
Thank you for reporting, but in order to debug this we would need a live demo on e.g. [jsFiddle.net](http://jsfiddle.net/highcharts/llexl/) with steps to reproduce the bug.

Here is an example of setting the title style with a serif font: http://jsfiddle.net/2obhr3gc/.

**Comment by TangHuanan** [comment]
I can't reproduce in demo also, but in our production code, it is always  appeared. The code was too complex

**Comment by oysteinmoseng** [comment]
Would you be able to isolate the code that sets the font properties? Or try loading other fonts?

**Comment by TangHuanan** [comment]
Sorry, I found the root cause, it come from the grid-light.js. it is not a bug.
![image](https://cloud.githubusercontent.com/assets/4714386/19231427/81445890-8f0c-11e6-9aff-58f116eddbbb.png)
