### ISSUE TITLE
Switch from .bind()/.unbind() to .on()/.off()

### ISSUE THREAD

**Issue by mgol** [highcharts/highcharts#5808]
#### Expected behaviour
Code & samples should always use `on()`/`off()` instead of `bind()`/`unbind()`. We've deprecated the latter in jQuery 3.0 so people may exclude them easier from their custom builds.

The switch will drop support for jQuery 1.6 or older but jQuery 1.7 has been released 5 years ago and there have been 5 "major" updates since that time so this shouldn't be an issue.

#### Actual behaviour
Samples seem to use `.bind()`. See e.g. https://github.com/highcharts/highcharts/blob/9ceb2b8/samples/highcharts/chart/events-container/demo.js#L20

#### Live demo with steps to reproduce

N/A

#### Affected browser(s)
N/A

**Comment by oysteinmoseng** [comment]
Thanks for reporting.
