### ISSUE TITLE
setSize animation: resize the container immediately, animate the map change

### ISSUE THREAD

**Issue by mgol** [highcharts/highcharts#5809]
#### Expected behaviour

I'd like to be able to call `chart.setSize(null, null)` in a way that doesn't display an animation that resizes the _container_ itself but that would animate the chart position & size changes.
#### Actual behaviour

Currently calling `chart.setSize(null, null)` resizes the container together with the map inside it, causing a jarring effect of a moving edge. It's especially visible if in the zoomed-in state of a map non-focused countries are made invisible.
#### Live demo with steps to reproduce

https://jsfiddle.net/x9r7y1sz/1/
#### Affected browser(s)

All

**Comment by oysteinmoseng** [comment]
I'm not sure I understand what you are looking for. Presumably you have looked at [Point.zoomTo](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/maps/members/point-zoomto/). There would be no way to resize the chart itself without resizing the container, but you could wrap the container in another `div`?

**Comment by mgol** [comment]
See the video at https://youtu.be/rQxIWf6LG0w. Slow it down to 0.5 or 0..25 and see how the right edge looks like. The rest of the page changes immediately because of the site CSS but the end of the map is visible. I want the container to be resized immediately but without the map changing its position immediately. If I just disable the animation for `setSize` via `setSize(null, null, false)` then the map first jumps to fill the new container and only then zooms in. See https://youtu.be/9zM0df8ALsQ for what it looks like.

I want a combination of those two behaviors.

**Comment by mgol** [comment]
The code I'm invoking is basically: to zoom into a state:
```js
chart.setSize(415, 415);
point.zoomTo();
```
and then to zoom out (only this part is on videos):
```js
chart.setSize(null, null);
chart.mapZoom();
```

**Comment by TorsteinHonsi** [comment]
@mgol You're aware that the [setSize](http://api.highcharts.com/highcharts/Chart.setSize) function takes animation as the third parameter? https://jsfiddle.net/highcharts/x9r7y1sz/5/

**Comment by mgol** [comment]
It doesn't look good to me, it's essentially my second video. I don't want to see such a jump at the beginning of the zoom out process, the map itself should have all the changes animated, just its container (the rectangle in which it's contained and to which it's clipped) should be resized immediately.

**Comment by mgol** [comment]
I've added a delay for the opacity 0 -> 1 animation to make the effect less jarring but it's still not ideal (you can see the map being clipped for some time), see https://today.yougov.com/us-election/.
