### ISSUE TITLE
Wrong zone line color in area chart after setting Y extremes

### ISSUE THREAD

**Issue by nmykhailova** [highcharts/highcharts#5810]
#### Expected behaviour

The line color of the zone in the area chart is the same as the fill color.
#### Actual behaviour

The line color of the zone in the area chart is different from the fill color.
This happens only if Y axis extremes are set before data points are added. If you comment out the following line `chart.yAxis[0].setExtremes(-40, 40);`, then everything works fine. Also, the issue is not reproducible in line chart.
#### Live demo with steps to reproduce

https://jsfiddle.net/hxo25r9n/20/
#### Affected browser(s)

At least Chrome and Firefox.

**Comment by pawelfus** [comment]
**Workaround:**

Disable `redraw` ann all actions except the last one: https://jsfiddle.net/hxo25r9n/23/

**Comment by nmykhailova** [comment]
Thank you, pawelfus!

**Comment by nmykhailova** [comment]
I have one question regarding the workaround. 
In case I need to call setExtremes with `redraw ` set to `true` the first time (when , for example, no data yet available), is there a way to reset Y axis to the original state afterwards? 
I've tried   `chart.yAxis[0].setExtremes(null, null, true);` , but it does not work https://jsfiddle.net/hxo25r9n/24/.

**Comment by pawelfus** [comment]
I think that actually Highcharts are using -40/40 for extremes, see demo with disabled all `setExtremes()` calls: https://jsfiddle.net/hxo25r9n/25/ 

Compare https://jsfiddle.net/hxo25r9n/26/ with https://jsfiddle.net/hxo25r9n/28/

**Comment by nmykhailova** [comment]
Indeed, in this jsfiddle case Highcharts are using -40/40 by default and it is not necessary to set it. However, my actual usecase is a bit more complex. I need sometimes to set Y axis extremes to greater values than the calculated default values, because in the beginning only a chunk of data is loaded for the current visible X range and when the user pans/scrolls to the next X range, then a new data is requested for that range. I don't want the Y extremes to jump to different values when the user pans/scrolls, therefore I set them to the global min and max in the very beginning. First, I receive only extremes from a server, set them , then send a new request to server with the current X range and show to the user that data is loading. Afterwards I receive the data and update chart with it.
For now, my workaround is not to set Y extremes when I receive them for the first time, setting X extremes is enough to show the plot band with loading message.
Thanks for you help!
