### ISSUE TITLE
Column chart. datetime xAxis ticks are representing UTC midnight + timezoneOffset instead of midnight

### ISSUE THREAD

**Issue by Kamilius** [highcharts/highcharts#5812]
#### Expected behaviour
xAxis ticks should be aligned with column start, and represent start of day

#### Actual behaviour
xAxis ticks are not aligned with column start, and represent UTC midnight + timezone offset (in my case 03:00), screenshot attached, which visually looks like a tick, offset by small amount of pixels from respective column start.

#### Live demo with steps to reproduce
http://jsfiddle.net/x54m0jwg/1/
Try to zoom in/out to see how ticks are aligned to columns

#### Affected browser(s)
Tested in Chrome

**Comment by pawelfus** [comment]
Hi @Kamilius 

I am not sure if this is a bug, but by default Highcharts calculate ticks at 00:00:00.000 when displaying a day. When setting column to start when day actually starts (at midnight), and setting [`series.pointPlacement`](http://api.highcharts.com/highcharts/plotOptions.column.pointPlacement) to `'between'` you most probably achieve what you need: http://jsfiddle.net/1a1k70wu/

In case you can not set dates to start at midnight, you can use [`xAxis.tickPositioner`](http://api.highcharts.com/highcharts/xAxis.tickPositioner) to calculate ticks on your own.

**Comment by Kamilius** [comment]
Hi @pawelfus,
Thanks for an answer. The solution you've proposed, works only for data I've provided in previous example, but breaks when providing other dates (for me - it's 8:10AM, GMT+3). 
http://jsfiddle.net/1a1k70wu/1/

I believe I'd need to calculate all of ticks positions for each zoom level manually then, if there is no possibility to draw ticks in a way I've described, out of box...

**Comment by Kamilius** [comment]
Accomplished this in following manner: 
```js
  tickPositioner: function() {
      // timezone offset in milliseconds
      let localTimezoneOffset = new Date().getTimezoneOffset() * 60000;

      // copy tickPositions breaking reference
      let positions = [].concat(this.tickPositions);
      // copy array's has named item 'info'
      positions.info = {
        ...this.tickPositions.info,
        higherRanks: {},
      };

      // iterate over available higherRanks labels (e.x ones which are representing day start among
      // time labels), and offset them to match 00:00 time
      Object.keys(this.tickPositions.info.higherRanks).forEach((key) => {
        positions.info.higherRanks[+key + localTimezoneOffset] = this.tickPositions.info.higherRanks[key];
      });

      return positions;
    },
```

@pawelfus is there a way to move higherRank labels without use of "tickPositioner"? Because somehow this doesn't feel clean/right.

**Comment by pawelfus** [comment]
> Could you advice solution for this zoom level, so 'start of day' labels would be actually rendered on 00:00, instead of 3:00?

It should work as you described. Hard to say why there is an offset, maybe some other library modifies Date methods? But it works when you use directly `getTimezoneOffset()` in tickPositioner.. Without live demo, I can only guess what is wrong here.

> @pawelfus is there a way to move higherRank labels without use of "tickPositioner"? Because somehow this doesn't feel clean/right.

For me it is fine. Alternatively, you can [extend](http://www.highcharts.com/docs/extending-highcharts/extending-highcharts) Highcharts methods, in that case extending `getTimeTicks` may work (demo: http://jsfiddle.net/1a1k70wu/4/ ):

    (function(H) {
      H.wrap(H.Axis.prototype, 'getTimeTicks', function(proceed) {
        var localTimezoneOffset = new Date().getTimezoneOffset() * 60000,
          ticks = proceed.apply(this, Array.prototype.slice.call(arguments, 1)),
          higherRanks = ticks.info.higherRanks,
          newRanks = [];

        Object.keys(higherRanks).forEach((key) => {
          newRanks[+key + localTimezoneOffset] = higherRanks[key];
        });

        ticks.info.higherRanks = newRanks;
        return ticks;
      });
    })(Highcharts);

**Comment by Kamilius** [comment]
@pawelfus thanks for help, Pawel

**Comment by Kamilius** [comment]
@pawelfus got a similar issue for line chart. Day start labels are not being positioned on actual 00:00, but trying to represent a local day start comparing to UTC. I'm using "highstock-release": "2.1.9"
