### ISSUE TITLE
Map-from-svg.htm is not working anymore

### ISSUE THREAD

**Issue by ricardborras** [highcharts/highcharts#5813]
#### Expected behaviour

Select one preset from list in http://www.highcharts.com/studies/map-from-svg.htm and click 'load' should display a map. Also pasting a svg file should work. 

#### Actual behaviour

Clicking load does nothing. Looking at javascript console, it says:

GET http://github.highcharts.com/82c192d73/modules/data.src.js 
map-from-svg.htm:11 

GET http://github.highcharts.com/82c192d73/modules/map-parser.src.js 503 (Service Unavailable: Back-end server is at capacity)

map-from-svg.htm:51 Uncaught TypeError: Highcharts.data is not a function
drawMap @ map-from-svg.htm:51runChart @ map-from-svg.js:95runPreset @ map-from-svg.js:86(anonymous function) @ map-from-svg.js:75jQuery.event.dispatch @ jquery-1.10.1.js:5116elemData.handle @ jquery-1.10.1.js:4787
map-from-svg.htm:51 Uncaught TypeError: Highcharts.data is not a functiondrawMap @ map-from-svg.htm:51runChart @ map-from-svg.js:95jQuery.event.dispatch @ jquery-1.10.1.js:5116elemData.handle @ jquery-1.10.1.js:4787

#### Affected browser(s)

Firefox, chrome

**Comment by oysteinmoseng** [comment]
The tool still works, but we are having issues with the http://github.highcharts.com service stability. For now, try reloading the page a few times if you get errors.

**Comment by ricardborras** [comment]
Page is having errors again, tried reloading several times with no success:

Console output from chrome (similar errors in Firefox): 

map-from-svg.htm:1 Mixed Content: The page at 'https://www.highcharts.com/studies/map-from-svg.htm' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-1.10.1.js'. This request has been blocked; the content must be served over HTTPS.
map-from-svg.htm:1 Mixed Content: The page at 'https://www.highcharts.com/studies/map-from-svg.htm' was loaded over HTTPS, but requested an insecure script 'http://code.highcharts.com/maps/1.0.4/highmaps.js'. This request has been blocked; the content must be served over HTTPS.
map-from-svg.htm:1 Mixed Content: The page at 'https://www.highcharts.com/studies/map-from-svg.htm' was loaded over HTTPS, but requested an insecure script 'http://github.highcharts.com/82c192d73/modules/data.src.js'. This request has been blocked; the content must be served over HTTPS.
map-from-svg.htm:1 Mixed Content: The page at 'https://www.highcharts.com/studies/map-from-svg.htm' was loaded over HTTPS, but requested an insecure script 'http://github.highcharts.com/82c192d73/modules/map-parser.src.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by TorsteinHonsi** [comment]
@SamHoulder Can you take the updated contents of map-from-svg.htm and add to the website repo and server?
