### ISSUE TITLE
When Title Text is empty, the last Y Axis Tick Label is clipped

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#5816]
#### Expected behaviour

The last y axis tick label should not be clipped when title text is empty and font size of y axis tick labels is increased.
#### Actual behaviour

The last y axis tick label is being snipped off as font size of labels is increased.
#### Live demo with steps to reproduce

http://jsfiddle.net/8nwey9sh/
#### Affected browser(s)

All

**Comment by pawelfus** [comment]
**Workaround:**

Set [`chart.marginTop`](http://api.highcharts.com/highcharts/chart.marginTop) when increasing yAxis labels font size, demo: http://jsfiddle.net/8nwey9sh/1/

**Comment by sgrg93** [comment]
@pawelfus But in my product, I have provided a configurable UI for the user to change font size of y axis tick labels. So setting a constant marginTop attribute won't work in that case since font size will change dynamically.

**Comment by pawelfus** [comment]
I see. That's a bit more complicated, but how about using [`chart.update()`](http://api.highcharts.com/highcharts/Chart.update) to update `topMargin`?

**Comment by sgrg93** [comment]
Yes, but in this case top margin will be dependent on the font size of tick labels. And even then in some cases when top margin is changed, new tick labels appear which are clipped: http://jsfiddle.net/8nwey9sh/2/ . Isn't this a bug? Shouldn't the chart redraw its tick labels according to how much space it has without clipping them?

**Comment by pawelfus** [comment]
Just to be on the same page: I'm just trying to find a workaround for you :) I was thinking about something like this: http://jsfiddle.net/030827w0/

**Comment by TorsteinHonsi** [comment]
If we fix this, it would have to behave the same way as on a horizontal axis, where the label is moved a little bit to the left so that it falls inside the available space: http://jsfiddle.net/highcharts/8nwey9sh/4/.

On a vertical axis, we would move the label down instead of modifying the top margin.
