### ISSUE TITLE
Marker radius

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#5817]
#### Expected behaviour
`marker.radius` and `marker.states.hover.radius` should work.

#### Actual behaviour
In Highcharts 5 (it used to work in 4) radius option for markers doesn't work. Marker always has 5px radius.

#### Live demo with steps to reproduce
http://jsfiddle.net/udpmkxud/

**Comment by TorsteinHonsi** [comment]
Note that `series.marker.radius` on the _series_ level still works, it is the _point level_ marker option that fails: http://jsfiddle.net/udpmkxud/1/.
