### ISSUE TITLE
Halo is under all series instead of being under the hovered point

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5818]
#### Expected behaviour
A point's halo on hover visible on top of underlying series, like column.

#### Actual behaviour
A point's halo is under all series.

#### Live demo with steps to reproduce
http://jsfiddle.net/519vfcdr/

Steps:
1. hover first point to see that it's halo is under a column

It's also a problem with maps - halo is visible only when a point is not over a land:
http://jsfiddle.net/o2ctd5p3/

**Comment by pawelfus** [comment]
*Internal note:*
How about moving halo into the series group like in the commit above?
