### ISSUE TITLE
Incorrect xAxis crosshair width when xAxis has categories

### ISSUE THREAD

**Issue by idrm** [highcharts/highcharts#5819]
#### Expected behaviour
Setting xAxis.crosshair.width=1 for an xAxis that also has categories should make it appear as a vertical line that is 1px wide. 

#### Actual behaviour
The crosshair appears to take up the width of the segment it is in (e.g. the category's entire space on the x-axis), regardless of the crosshair width setting.

#### Live demo with steps to reproduce
http://jsfiddle.net/uap0hdrs/

#### Affected browser(s)
Chrome, Firefox

**Comment by oysteinmoseng** [comment]
Thanks for reporting. Workaround: http://jsfiddle.net/uap0hdrs/1/
