### ISSUE TITLE
Tooltip Clipped on Sparkline Demo

### ISSUE THREAD

**Issue by LarryAzevedo** [highcharts/highcharts#5820]
#### Expected behaviour
I was expecting to see the tooltip appear when hovering over the sparkline. I know this is talked about on https://github.com/highcharts/highcharts/issues/5784 but figured I would create a separate issue since this is actually happening on the Highcharts demo and should be fixed on there as well.

#### Actual behaviour
![sparklines](https://cloud.githubusercontent.com/assets/2222751/19325227/24f885e2-9093-11e6-97f7-93f040432f54.png)

#### Live demo with steps to reproduce
http://www.highcharts.com/demo/sparkline

#### Affected browser(s)
Firefox 49 on OS X El Capitan Version 10.11.6
Chrome 53 on OS X El Capitan Version 10.11.6
Safari 9 on OS X El Capitan Version 10.11.6

**Comment by pawelfus** [comment]
Thank for reporting!

I am not sure of these are the same issues: in the sparkline demo, we have `chart.style.overflow = "visible"` which used to work in 4.2.x version, but not in 5.0.x. Adding:

    .highcharts-container {
      overflow: visible !important;
    }

Resolves the issue: http://jsfiddle.net/cxn47x1r/

**Comment by TorsteinHonsi** [comment]
Duplicate #5745 .
