### ISSUE TITLE
Highstock addSeries while scrollbar disabled run out error #18

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#5821]
Live Demo: [http://jsfiddle.net/yr69w4ym/](http://jsfiddle.net/yr69w4ym/)

addSeries while scrollbar is diabled, but run out error 18, and add series failure

>The requested axis does not exist

while I resize the chart, the new series appeared.

**Comment by oysteinmoseng** [comment]
Fixed in master: http://jsfiddle.net/yr69w4ym/1/
