### ISSUE TITLE
Highstock: Wrong horizontal scaling of remaining series after hiding one serie

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#5823]
#### Expected behaviour
After clicking legend item all remaining columns should be scaling to remaining space in x axis. 

Demo with working chart using Highstock 4.2.6
http://jsfiddle.net/mwsm0nvk/

#### Actual behaviour
From version 4.2.7 columns don't scale after hiding one series, all remaining series point range is decreasing to lower value than expected.

#### Live demo with steps to reproduce
http://jsfiddle.net/3u357f8h/

May be related to:
https://github.com/highcharts/highcharts/issues/5329

**Comment by pawelfus** [comment]
Thank you for reporting. 

Demo with fixed width: http://jsfiddle.net/mwsm0nvk/1/ (it's important to see dataGrouping in use).

It's a regression after 4acf1e4.
