### ISSUE TITLE
Feature: minimum floor and ceiling

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#5824]
I want to suggest a feature. And if a workaround can be done, will be welcomed.

In addition of having a maximum floor and ceiling, add a minimum floor and ceiling that can be surpassed. Something like min-height in CSS.

It can be achieved by controlling the dataMax and dataMin in the series, but I would love an internal way of doing this, like floor and ceiling.

**Comment by TorsteinHonsi** [comment]
Thanks for the suggestion!

Corresponding UserVoice request: https://highcharts.uservoice.com/admin/forums/55896-highcharts-javascript-api/suggestions/1848953-extend-the-axis-max-property-to-act-like-css-mi

A typical use case for this is when you want the axis to reflect a percentage range between 0 and 100, but still allow values beyond this range: http://jsfiddle.net/q9f6bjfk/

**Comment by Llorx** [comment]
Woah, so fast.

Thank you!
