### ISSUE TITLE
Improvement: Do not invalidate some unchanged properties when update({OPTIONS}, false) is called

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#5829]
#### Expected behaviour

When calling series.update(), if you don't change the data in the new options, keep dataMin and dataMax.
#### Actual behaviour

When calling series.update(), although you don't modify the data, dataMin and dataMax gets invalidated. I know that when you call update(), everything gets invalidated and recalculated in the next redraw, but some times we do multiple update() without redrawing because we call one redraw after some calculations. Those calculations involves dataMin and dataMax so is a small problem here. We have to cache the info before the update() call. I know that dataMin and dataMax are the same before the update() because it is just used to change series yAxis (change multiaxis to single axis and vice versa), but keep the same data.

**Comment by pawelfus** [comment]
Related to #5730 discussion. I'm not against it, but `series.dataMin` and `series.dataMax` are rather internal only values, not part of the [Series API](http://api.highcharts.com/highcharts/Series).

**Comment by Llorx** [comment]
Hm, I see.

Can I ask then having series.getExtremes() return something? Maybe that could be part of the public API, instead of hacking around dataMin and dataMax.

**Comment by pawelfus** [comment]
I think that sounds reasonable. Actually you can wrap default method and force it to return current extremes. It is a bit tricky, because we don't want to modify `series.dataMax` and `series.dataMin` (it may broke something when using this method before `redraw()`). Here is my idea: http://jsfiddle.net/Lu65o7aL/

Plugin-style snippet:

    (function(H) {
      H.wrap(H.Series.prototype, 'getExtremes', function(proceed, yData, byUser) {
        var series = this;

        // Use a copy of the series, when called like an API method:
        if (byUser) {
          series = {
            xAxis: this.xAxis,
            yAxis: this.yAxis,
            processedXData: this.processedXData,
            processedYData: this.processedYData,
            stackedYData: this.stackedYData,
            options: this.options,
            cropped: this.cropped
          };
        }

        // Run original method, with a different context if necessary:
        proceed.apply(series, Array.prototype.slice.call(arguments, 1));

        // Return extremes:
        return {
          dataMin: this.dataMin,
          dataMax: this.dataMax
        };
      });
    })(Highcharts)
