### ISSUE TITLE
Column range chart's tooltip doesn't disappear after moving cursor to blank area

### ISSUE THREAD

**Issue by Vwings** [highcharts/highcharts#5830]
plotOptions.columnrange.mouseOut events never fired when moving cursor from columrange to blank area.
Is there any solution to hide the tooltip after moving cursor to blank area instead of moving out of the chart?

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/columnrange/

**Comment by pawelfus** [comment]
Hi @Vwings 

For support related questions, please use our forum/stackoverflow/email (more can be found [here](http://www.highcharts.com/support)).

And to answer your question: you can set [`stickyTracking`](http://api.highcharts.com/highcharts/plotOptions.columnrange.stickyTracking) to false, see demo: http://jsfiddle.net/fkgjgLrb/
