### ISSUE TITLE
Stacked Column Chart Tooltip issues in 5.0.0

### ISSUE THREAD

**Issue by patrickbrownsync** [highcharts/highcharts#5832]
#### Expected behaviour

When using point placement with a stacked column chart, shared labels should show all stacks, worked in 4.2

#### Actual behaviour

When point placement is added, stacks do not appear correctly in shared tooltip.

#### Live demo with steps to reproduce

http://jsfiddle.net/brzs1vLw/

#### Affected browser(s)

Chrome

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

I'm not sure why you use `pointPlacement`, but if your objective is to pack the columns tighter together, you should use the `pointPadding` option: http://jsfiddle.net/highcharts/brzs1vLw/1/.

Nevertheless, it is a regression.

**Comment by pawelfus** [comment]
Responsible commit: 771ce49a36924f2ea30d4b0695e6703475e56caf

**Comment by TorsteinHonsi** [comment]
Fails since v4.2.7, 5ef14ea

**Comment by pawelfus** [comment]
Not really. As an alternative, we can make [this](https://github.com/highcharts/highcharts/blob/v5.0.0/js/parts/Pointer.js#L223) less strict and involve `point.x` there, for example:

	while (i--) {
		if ((kdpoints[i].clientX !== kdpoints[0].clientX && kdpoints[i].x !== kdpoints[0].x) || kdpoints[i].series.noSharedTooltip) {
			kdpoints.splice(i, 1);
		}
	}

It will filter out cases, where clientX is different by pointPlacement, but x-values are in fact excatly the same.

**Comment by TorsteinHonsi** [comment]
It sounds like a good idea... Do we need the check for clientX at all? Can we think of situations were a test for `point.x` is not sufficient? By definition, the shared tooltip shows points of the same `x` value. The `clientX` property is used in

* Heat maps for getting the tooltip in the center (shared tooltips don't apply)
* K-d-tree for getting the closest point in x _and_ y dimensions. Shared tooltips don't apply because they only search for the closest point in the X dimension (?)

If you can't think of other problem areas I suggest we replace the comparing `clientX` with simply comparing `point.x`.

**Comment by pawelfus** [comment]
> Do we need the check for clientX at all? Can we think of situations were a test for point.x is not sufficient?
I think we should. The test for `x` only will always fail when using two (or more) separate xAxes, for example when comparing different weeks/months of the same data set: http://jsfiddle.net/jhyhn2ty/ - quite common use case for a Highstock, which is very easy to achieve with an ordinal xAxis..

> K-d-tree for getting the closest point in x and y dimensions. Shared tooltips don't apply because they only search for the closest point in the X dimension (?)

Not exactly, it finds all closest point by x-dimension as you said, but according to x+y distance we can determine which of the points is the closest one (for example click event on a tracker).

**Comment by TorsteinHonsi** [comment]
But using a shared tooltip with two X axes is wrong under any circumstances, in your sample the tooltip header shows only the date of the first point: http://jsfiddle.net/jhyhn2ty/

In this case we would at least need to get rid of the shared header.

**Comment by pawelfus** [comment]
Yes, of course - it was just a minimal example, an idea.

**Comment by TorsteinHonsi** [comment]
I think we'll give it a try with comparing x-es...
