### ISSUE TITLE
Split Tooltips: Cannot read property 'connector' of undefined

### ISSUE THREAD

**Issue by lusa** [highcharts/highcharts#5833]
#### Expected behaviour
No JS errors should be thrown when showing/hiding series with Split Tooltips. 

#### Actual behaviour
On showing and hiding series after hovering over the chart showing the split Tooltips, we see this error: `highcharts.js:188Uncaught TypeError: Cannot read property 'connector' of undefined`. 
Simply show and hide a series several times to get the error by clicking on the legend item's name. 

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/tooltip/split/

**Comment by jon-a-nygaard** [comment]
Thanks for reporting, we will try to fix it as soon as possible.

**Comment by lusa** [comment]
Thanks for the quick fix! @TorsteinHonsi when will this be released?

**Comment by jon-a-nygaard** [comment]
@lusa We're aiming to release v5.0.1 this week.
