### ISSUE TITLE
Color of null points on a map

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#5837]
#### Behaviour

Setting color for null points in styled mode through .highcharts-null-point class does not take effect on a map.
#### Live demo with steps to reproduce

http://jsfiddle.net/o6jz5svg/

**Comment by oysteinmoseng** [comment]
Workaround: http://jsfiddle.net/o6jz5svg/1/

Internal note: seems like the null point class is not set on the points.

**Comment by alvarezguille** [comment]
Should the [original live demo](http://jsfiddle.net/o6jz5svg/) from this issue work?
It's getting highmaps without a version so should be latest code.

**Comment by oysteinmoseng** [comment]
Seems like a bug, it is getting the null point class (see http://jsfiddle.net/o6jz5svg/7/), but there is an additional fill style set. Reopening.
