### ISSUE TITLE
Split tooltip ignores style

### ISSUE THREAD

**Issue by Nickesh** [highcharts/highcharts#5838]
#### Expected behaviour

Defining custom style for tooltip (http://api.highcharts.com/highcharts/tooltip.style) works regardless of `tootlip.split` option value (http://api.highcharts.com/highcharts/tooltip.split).
#### Actual behaviour

`Tooltip.style` does not work when `tooltip.split` is `true`.
#### Live demo with steps to reproduce

http://jsfiddle.net/y06o5be9/
#### Affected browser(s)

Tested on Chrome and Opera.

**Comment by pawelfus** [comment]
**Workaround:**

Use CSS styles for general split CSS options: http://jsfiddle.net/y06o5be9/3/
