### ISSUE TITLE
Bug: Highcharts throws error on mobile touch-move event

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#5839]
Happens on both Highcharts 4.2.4 & 5.0.0, tested with latest chrome on Android 

When touch & move finger highcharts throws: 
highcharts.src.js:10405 Uncaught TypeError: Cannot read property 'attr' of undefined
```javascript
 each(chart.series, function (series) {
                seriesAttribs = attribs || series.getPlotBox(); // #1701
                if (series.xAxis && series.xAxis.zoomEnabled) {
                    series.group.attr(seriesAttribs); //**** this line throws error 
                    if (series.markerGroup) {
                        series.markerGroup.attr(seriesAttribs);
                        series.markerGroup.clip(clip ? chart.clipRect : null);
                    }
                    if (series.dataLabelsGroup) {
                        series.dataLabelsGroup.attr(seriesAttribs);
                    }
                }
            });
```
series has no group attribute...
Load on your Android mobile device: https://codepen.io/onemenny/full/JRmRgp 
or see code here:  https://codepen.io/onemenny/pen/JRmRgp

Please advice

**Comment by TorsteinHonsi** [comment]
Stripped down to relevant demo: http://jsfiddle.net/highcharts/8pg0t6ps/

The problem appears when a series is added after render time with visible: false.
