### ISSUE TITLE
PinchType without ZoomType

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#5840]
#### Expected behaviour

It should be possible to disable `zoomType`, but allow `pinchType`, when chart is generated for mobile devices.
#### Actual behaviour

If `zoomType` is disabled, then `pinchType` option doesn't matter.
#### Live demo with steps to reproduce

Demo: http://jsfiddle.net/nnuhLray/ (http://jsfiddle.net/nnuhLray/show)

Edit: May be related to #2168

**Comment by TorsteinHonsi** [comment]
Absolutely agreed. I ran into this myself .
