### ISSUE TITLE
Highcharts tooltip first click issue in mobile devices

### ISSUE THREAD

**Issue by neswine** [highcharts/highcharts#5841]
#### Expected behaviour

Tooltip should appear on the first touch on point.
#### Actual behaviour

When we click on the chart for first time, the path gets highlighted without showing tooltip and then on subsequent clicks the tooltip appears. We tried with the Highcharts demo options and still the issue persists. Similarly, for checking purpose, we placed click event in the tooltip and gave a alert. It was working fine in jsFiddle. But didn't work in my mobile webView. The seen behaviour is on first click, the path gets highlighted. And then from next subsequent clicks, tooltip appears and it works fine.This behaviour is not seen on desktop devices or if the the chart is rendered in iframe tag.
#### jsFiddle

http://jsfiddle.net/2swEQ/2/
#### Tested browser(s)

Tested in these devices
iOS WebView: > 8.0, 
Device: iphone 5s, iPhone 6 and 6S
Android: > Android Kit-Kat, 
Device: Nexus, Samsung Galaxy devices

**Comment by TorsteinHonsi** [comment]
You're running a custom tooltip, so the issue probably applies more to event handling than the native Highcharts tooltip. 

Have you tried using the [solution provided at UserVoice](https://highcharts.uservoice.com/admin/forums/55896-highcharts-javascript-api/suggestions/2607304-allow-the-tooltip-to-appear-when-a-point-is-clicke?tracking_code=7650d5adf5c31e834983220c68f7ee11#/comments)?

**Comment by neswine** [comment]
Right now, we are using default tooltip. We tried building with custom tooltip but the issue still persisted. During debugging, what i saw is that,  I created a click event for the chart option and put an alert in it. The alert was triggered when I rendered the it in iframe or ran the app in desktop. But outside iframe or mobile webview, the alert was'nt triggered.

**Comment by dosaki** [comment]
Are there any plans to resolve this issue?
