### ISSUE TITLE
Scatter Plot Image/Base64 Markers Movement

### ISSUE THREAD

**Issue by thomasdclark** [highcharts/highcharts#5842]
#### Expected behaviour
Image/Base64 scatter plot markers are rendered to the chart in their correct positions and when those markers are interacted with, no movement occurs.  The legend for those markers are also displayed normally.

#### Actual behaviour
Image/Base64 scatter plot markers are rendered to the chart with a slight offset from their correct position, and when they are hovered over, they move to the position they are actually suppose to be in.  The legend for those markers also appear to be offset similarly, but does not fix itself when interacted with.

This seems similar to issue #3643 but not quite the same since this involves Image/Base64 markers rather than predefined markers.

#### Live demo with steps to reproduce
[Link to JSFiddle showing issue.](http://jsfiddle.net/v638g6ak/)  The best way to reproduce this is to just hover over the Image marker (the pink star) on the graph, and you will see it move.  Every time the chart is redrawn (ie. if one of the legend items is clicked), the marker repositions itself to its original position until it is hovered over again.

Also, the legend item for the marker is offset as well.

#### Affected browser(s)
I am using Chrome Version 53.0.2785.143

**Comment by pawelfus** [comment]
Thanks for reporting! 

It used to work in 4.x: http://jsfiddle.net/Ldguqcjk/

**Comment by TorsteinHonsi** [comment]
Simpler demo. The graphics are expected to center on the crossing lines:

http://jsfiddle.net/highcharts/jrgqggtm/
