### ISSUE TITLE
Document window.isComparing

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#5843]
https://github.com/highcharts/highcharts/blob/master/samples/stock/demo/data-grouping/demo.js#L13

**Comment by oysteinmoseng** [comment]
`window.isComparing` is only set in one of our internal testing tools, and is unrelated to Highcharts. I can see how it would be confusing to users when it's present in a demo. @TorsteinHonsi comments?

**Comment by dandv** [comment]
It was fun to Google for "window.isComparing" and find a bunch of copycat sites :)

**Comment by TorsteinHonsi** [comment]
Haha! Yes that's interesting.
