### ISSUE TITLE
resetZoom and HighStock

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#5844]
http://api.highcharts.com/highstock/lang.resetZoom documents resetZoom and resetZoomTitle, but [resetZoom](http://api.highcharts.com/highcharts/chart.resetZoomButton) doesn't work with HighStock (rangeSelector should be used instead).

Is there a way to have a resetZoom button in HighStock, or should those two properties be removed from the docs?

**Comment by pawelfus** [comment]
Hi @dandv,

Yes, there is an option to have show reset zoom button. You need to set `zoomType: 'xy'` - only zooming in on yAxis will show this button. 

See also #979 discussion.

**Comment by dandv** [comment]
Thanks @pawelfus. Maybe the [resetZoomButton](http://api.highcharts.com/highcharts/chart.resetZoomButton) page should say something about using this button with HighStock.

**Comment by pawelfus** [comment]
I think that [`chart.resetZoomButton`](http://api.highcharts.com/highstock/chart.resetZoomButton) is simply missing in Highstock docs. Of course it should contain that info.

**Comment by TorsteinHonsi** [comment]
Fixed, http://api.highcharts.com/highstock/chart.resetZoomButton

**Comment by Kamilius** [comment]
@TorsteinHonsi examples on this page are not for Highstock, but rather for Highcharts, which is confusing. Highstock needs `zoomType: 'xy';` to be able to show this button, while Highchart's OK only with 'x'. 

Also may I ask why resetZoom is only shown for `y` axis? I can't seem to find any logic in such restriction, because this forces to write custom button instead of using a native one.

**Comment by TorsteinHonsi** [comment]
> examples on this page are not for Highstock, but rather for Highcharts, which is confusing. 

Okay, I will have a look at that.

> Also may I ask why resetZoom is only shown for 'y' axis? I can't seem to find any logic in such restriction, because this forces to write custom button instead of using a native one.

It's because for the X axis, you already have the range selector, where the "All" button does the same as "Reset zoom" would have done.

**Comment by dandv** [comment]
In terms of great UX, I would prefer an "Undo zoom" option, where the user can go back to the previous zoom level, rather than from zooming in to an hourly level directly back to a view spanning multiple years.

This plugin gets close to implementing that:

http://www.highcharts.com/plugin-registry/single/26/Zoom%20Out%20Selection
