### ISSUE TITLE
Getting exception when using boost module and try to add series dynamiclly wihout data

### ISSUE THREAD

**Issue by royigoldi** [highcharts/highcharts#5845]
XCEPTION: Cannot read property 'length' of undefinedErrorHandler.handleError @ core.umd.js:3462next @ core.umd.js:6924schedulerFn @ core.umd.js:6172SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238SafeSubscriber.next @ Subscriber.ts:190Subscriber._next @ Subscriber.ts:135Subscriber.next @ Subscriber.ts:95Subject.next @ Subject.ts:61EventEmitter.emit @ core.umd.js:6164onError @ core.umd.js:6388onHandleError @ core.umd.js:6263ZoneDelegate.handleError @ zone.js:196Zone.runTask @ zone.js:128ZoneTask.invoke @ zone.js:293
core.umd.js:3467 ORIGINAL STACKTRACE:ErrorHandler.handleError @ core.umd.js:3467next @ core.umd.js:6924schedulerFn @ core.umd.js:6172SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238SafeSubscriber.next @ Subscriber.ts:190Subscriber._next @ Subscriber.ts:135Subscriber.next @ Subscriber.ts:95Subject.next @ Subject.ts:61EventEmitter.emit @ core.umd.js:6164onError @ core.umd.js:6388onHandleError @ core.umd.js:6263ZoneDelegate.handleError @ zone.js:196Zone.runTask @ zone.js:128ZoneTask.invoke @ zone.js:293
core.umd.js:3468 TypeError: Cannot read property 'length' of undefined
    at c.hasExtremes (http://localhost:3000/node_modules/highcharts/modules/boost.js:4:66)
    at c.<anonymous> (http://localhost:3000/node_modules/highcharts/modules/boost.js:3:208)
    at c.a.(anonymous function) [as setData](http://localhost:3000/node_modules/highcharts/highcharts.js:22:287)
    at c.init (http://localhost:3000/node_modules/highcharts/highcharts.js:245:8)
    at u.Chart.initSeries (http://localhost:3000/node_modules/highcharts/highcharts.js:215:21)
    at http://localhost:3000/node_modules/highcharts/highcharts.js:283:417
    at I (http://localhost:3000/node_modules/highcharts/highcharts.js:28:419)

**Comment by pawelfus** [comment]
Hi @royigoldi 

Could you recreate issue in jsFiddle? For me it works fine, please take a look: http://jsfiddle.net/15xwrer9/

Thanks!

**Comment by royigoldi** [comment]
Hi,

I do it from angular 2 application:
my Chart init:

new Highcharts.Chart({  //this is like your  $('#container').highcharts(

    title: {text: chartType + ' ' + channelName},
    subtitle: {text: 'Measurement site: '},
    xAxis: {
        type: 'number',
        title: {text: 'Wavelength (nm)'},
    },
    legend:{
        enabled : true
    },
    yAxis: {
        title: {text: 'Difference'},
        type: 'number',
    },
    chart: {
        type: 'line',
        zoomType: 'xy',
        panning: true,
        panKey: 'shift'
     },
    colors: this.spectraColorProvider.colors
    // tooltip: {
    //     useHTML:true
    // },
    // line: {
    //     animation: false
    // }

}

I wrap your chart with angular 2 component and i call to:

createNewSeries=(id:string, type:string, axisId:string = null,
additionalData:any = null)=>
{
    if (axisId) {
        this._chart.addSeries({
            id: id,
            name: id,
            type: type,
            yAxis: axisId,
            additionalData: additionalData
        }, this.redraw);
    }
    else
    {
        this._chart.addSeries({
            id: id,
            name: id,
            type: type,
        }, this.redraw);
    }
}

and got the exception


2016-10-19 13:31 GMT+03:00 Paweł Fus <notifications@github.com>:

**Comment by royigoldi** [comment]
please follow the call stack and maybe you can tell me what my problem:

![capture](https://cloud.githubusercontent.com/assets/20413250/19515899/1af9265e-9602-11e6-9f0e-c47b01717916.JPG)

Thanks,

**Comment by pawelfus** [comment]
Thanks, indeed it helped. Let me edit the title of the issue. 

It's caused by adding series, without `data: ...` property. Demo: http://jsfiddle.net/Lmmws3or/

**Workaround:**
Set at least empty `data: []`: http://jsfiddle.net/Lmmws3or/1/

**Comment by royigoldi** [comment]
Thanks, it help (-:

**Comment by pawelfus** [comment]
Issue solved since v5.0.8: http://jsfiddle.net/BlackLabel/snkbu491/1/
