### ISSUE TITLE
Rendering Points individually

### ISSUE THREAD

**Issue by AskSaikatSinha** [highcharts/highcharts#5848]
#### Expected behaviour
Chart rendering one point at a time but could not find any resource regarding individually plotting points.

#### Live demo with steps to reproduce
My codes till now: https://jsfiddle.net/opkza2ro/
Wanted the red part to render one after the another.

Please note I'm not expecting real time Chart: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/dynamic-update/

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
