### ISSUE TITLE
hideLoading doesn't work right after calling showLoading function in styled mode

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#5850]
#### Expected behaviour
Chart should hide loading overlay after calling hideLoading function.

#### Actual behaviour
Chart doesn't hide loading overlay after calling hideLoading function.

#### Live demo with steps to reproduce
Does't work:
https://jsfiddle.net/ez0m9qsq/

It works if hideLoading is wrapped in setTimeout()
https://jsfiddle.net/ez0m9qsq/1

It may be caused by using setTimeout function in showLoading function implementation.

**Comment by KacperMadej** [comment]
*Internal note:* [The setTimeout](https://github.com/highcharts/highcharts/blob/aae89f653cf98d9c2b9b1dcf2b76a424f941dc52/js/parts/Dynamics.js#L127) runs after `chart.hideLoading();` in case [there is](https://jsfiddle.net/ez0m9qsq/):

```
chart.showLoading();
chart.hideLoading();
```

**Comment by newlukai** [comment]
Thanks for opening this one.
