### ISSUE TITLE
if we create new config with new series data  chart.update(config) not updating series is this expected ? and if then which attributes can be updated using this function 

### ISSUE THREAD

**Issue by SharpieX** [highcharts/highcharts#5853]

**Comment by pawelfus** [comment]
Hi @SharpieX 

Could you show what exactly you want to update? I just tested, and it looks fine: http://jsfiddle.net/ofr8dtr8/ - feel free to update my demo and share with us so we can fix this.

**Comment by SharpieX** [comment]
Thanks For quick reply @pawelfus 
 i have updated your fiddle, for different data button i am creating config again and it should add 3 bars for each category which is not happening config object works fine if used seprately 
please have a look 
http://jsfiddle.net/ofr8dtr8/2/

**Comment by pawelfus** [comment]
Thank you for the demo!

A few things to mention here:

1.  Setting `chart.type` is not enough, when you previously set `series[index].type` - the second option has always a higher priority. 

2. Changing from `column` to `bar` doesn't change chart's orientation:  http://jsfiddle.net/ofr8dtr8/4/ - I think this classifies as a bug.

3. Number of series remains unchanged. I am not sure if [`chart.update()`](http://api.highcharts.com/highstock/Chart.update) was designed to change that. Chart doesn't have series so those are not updated, only the first one. Personally I think it's a nice-to-have feature anyway.

**Comment by SharpieX** [comment]
Thanks  for clearing point one 
and i was able to achieve that by removing all series from chart first then add series later using add chart.addSeries(), and i also think if we have an update function that should update all attributes.

**Comment by TorsteinHonsi** [comment]
According to the [docs for chart.update](http://api.highcharts.com/highcharts/Chart.update):

> A special case is configuration objects that take arrays, for example xAxis, yAxis or series. For these collections, an id option is used to map the new option set to an existing object. If an existing object of the same id is not found, the first item is updated. So for example, running chart.update with a series item without an id, will cause the existing chart's first series to be updated.
