### ISSUE TITLE
No tooltip in styled version using Google Polymer

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#5856]
#### Expected behaviour

Render tooltip after hovering over a point on a chart using Google Polymer
#### Actual behaviour

No tooltip after hovering over a point on a chart using Google Polymer, tooltip.refresh() doesn't work either.
#### Live demo with steps to reproduce

_You should use modern browser with shadow dom support for examples with google polymer_

styled mode using google polymer (no tooltip):
https://jsfiddle.net/c78bjbyp/

regular mode using google polymer (tooltip shows as expected):
https://jsfiddle.net/c78bjbyp/1

styled mode using dom without polymer (tooltip shows as expected):
https://jsfiddle.net/ag7ekLsp/

**Comment by pawelfus** [comment]
**Workaround: **

Disable build-in tooltip defs. For some reasons filter for a tooltip doesn't work. Demo: https://jsfiddle.net/b7808p2o/

Snippet: 



        defs: {
          style: {
            tagName: 'style',
            textContent: '.highcharts-tooltip {}'
          }
        },

**Comment by newlukai** [comment]
I assumed the missing tooltip is related to the implementation of the shadow effect (filter with url(<hashtag>)). Please b aware of Single Page Applications which use hash paths for navigation.

**Comment by TorsteinHonsi** [comment]
> styled mode using google polymer (no tooltip): https://jsfiddle.net/c78bjbyp/

Unfortunately I am not able to reproduce this now. The tooltip is displaying in Chrome. Firefox and Safari just display a black rectangle, I assume this is due to shadow DOM problems.

I fixed similar tooltip/styled mode problems in 62003e64411795f532b77281f041bc4b2a433142. Can you test your setup with this commit? You can load http://github.highcharts.com/62003e644/js/highcharts.src.js .

**Comment by stpoa** [comment]
It seems that it works now in chrome, it didn't work previously (i checked older version of chrome and it works as expected), so it may be caused by a bug in polymer library itself (which seems to be fixed).

**Comment by TorsteinHonsi** [comment]
Perfect, thanks for checking!
