### ISSUE TITLE
Drilldown to more than 50 - skip categories name

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5857]
#### Actual behaviour

Categories names are missing
#### Live demo with steps to reproduce

Example: 
- http://jsfiddle.net/gugjup9t/

Click into Microsoft, as a result when we have more than 50 categories, names are missing.

NameToX and setting labels.step as 1 do not solve the issue.
#### Affected browser(s)

All  browsers

**Comment by TorsteinHonsi** [comment]
Regression in v4.2.7.

**Comment by morganfree** [comment]
It looks like the demo works with set cropTreshold.
http://jsfiddle.net/gugjup9t/1/

**Comment by henrikskar** [comment]
_Internal Note_
addSeries is run before oldSeries is being removed. The drilled down points in the new series are pended to the old series.

**Comment by henrikskar** [comment]
Use the following workaround for now:

`    plotOptions: {
         series: {
             cropThreshold: 300
         }
    },`

**Comment by morganfree** [comment]
It also happens for zooming in/out. http://jsfiddle.net/franktudor/xe0furkn/
Setting cropThreshold or categories in axis fixes it. http://jsfiddle.net/xe0furkn/1/

**Comment by TorsteinHonsi** [comment]
Simplified demo: http://jsfiddle.net/highcharts/ayhL6mwz/

**Comment by pradipwalghude** [comment]
In Drill down chart,  Initially drill down point is not tappable on x-Axis but it is working when user navigate to inside series data and click on back button. Drill down related data point is tappable but respected x-Axis point is not tappable.

Could you please let us know what is wrong with our code or Is it SDK issue?

**Comment by KacperMadej** [comment]
For technical support please see https://www.highcharts.com/blog/support/
