### ISSUE TITLE
Tooltip not shown in styled version when using Bootstrap Tabs

### ISSUE THREAD

**Issue by Code-Working** [highcharts/highcharts#5859]
#### Expected behaviour

Show the tooltip in every chart.
#### Actual behaviour

If the user is on the first tag, everything is fine. When changing to another tab, tooltips are not displayed any more, independent if they are inside the tab panes or outside somewhere on the page.
#### Live demo with steps to reproduce

Fiddle with styled version: https://jsfiddle.net/n2y76k2j/
Fiddle with non-styled version: https://jsfiddle.net/wa7je4pa/
#### Affected browser(s)

Tested with Firefox 49 and Chrome 53.0.2785.143

Regards
Code.Working

**Comment by TorsteinHonsi** [comment]
As in #5856, the tooltip default filter style is causing it. Something with the references between charts causes the bug. 

#### Workaround
Add this to your style sheet (it also removes the tooltip's drop shadow):
```css
.highcharts-tooltip {
    filter: none !important;
}
```
[View live demo](https://jsfiddle.net/highcharts/n2y76k2j/2/).

**Comment by TorsteinHonsi** [comment]
#### Simplified demo
* http://jsfiddle.net/highcharts/n2y76k2j/7/

The issue happens only when `style.display` is set from JavaScript, not when applied through CSS.
