### ISSUE TITLE
Panning does not allow to go to the min/max value of the X axis

### ISSUE THREAD

**Issue by nmykhailova** [highcharts/highcharts#5863]
#### Expected behaviour

When panning to the beginning/end of the chart , the min/max data point is displayed.
#### Actual behaviour

When panning to the beginning/end of the chart , the min/max data point is missing. 
#### Live demo with steps to reproduce

Please, check jsfiddle for reproduction scenario https://jsfiddle.net/j5uy5ets/2/ . After panning to the left, no data point is displayed for year 1940. Pan back to the right and notice that the data point for year 1997 is gone (it was present initially). 
#### Affected browser(s)

At least Chrome and Firefox.

**Comment by oysteinmoseng** [comment]
Thanks for reporting.

**Comment by bbass-deloitte** [comment]
@pawelfus thanks for the update on #6649. Is there an ETA on a fix (or perhaps a hotfix) for this bug?

Thanks!
