### ISSUE TITLE
Highstock column chart - select style is missing

### ISSUE THREAD

**Issue by durga-telsiz** [highcharts/highcharts#5864]
#### Expected behaviour
I need to change the style of the column point that is selected. 

#### Actual behaviour
From documentation noted that states.select is not available for column chart. Is there any way to achieve this? Note that in my example, I set the select color to be blue. But on column click/select it turns grey.
states: {
                select: {
                  color: 'blue'
                }

#### Live demo with steps to reproduce
http://jsfiddle.net/6y38qe8u/4/

**Comment by oysteinmoseng** [comment]
This seems like a missing feature. @TorsteinHonsi? 

Workaround: Use plotOptions.series to set default state for all series (including columns). http://jsfiddle.net/6y38qe8u/8/

**Comment by pawelfus** [comment]
It also works for column type: http://jsfiddle.net/6y38qe8u/10/ - I guess it's simply missing in docs.

**Comment by oysteinmoseng** [comment]
You are right, the original fiddle has the series.states definition on top level, rather than under plotOptions.

**Comment by durga-telsiz** [comment]
Thanks @pawelfus
