### ISSUE TITLE
Horizontal scroll for legend

### ISSUE THREAD

**Issue by HackToday** [highcharts/highcharts#5865]
#### Expected behaviour

Have scroll ways, can make the legend title and value show correctly (not overlap)
#### Actual behaviour

When creating charts and addSeries, it is very diffcult to make item legend-title show correclty. If the name is long, it would overlap with value, like below:

![testone](https://cloud.githubusercontent.com/assets/10363809/19636032/24ae0b06-99f9-11e6-852c-1d8529effb11.PNG)

**Comment by oysteinmoseng** [comment]
Could you reproduce this in a live demo? This example using the "value in legend" plugin seems to handle overflows well: http://jsfiddle.net/omyqpdxj/.

**Comment by HackToday** [comment]
@oysteinmoseng  seems your example can not handle long name, for example

            data: [1, 2, 7],
            name: 'Sixth has an even longer name that certainly will overlap anything fdfdfdfdfd'

it would make whole chart display like below

![testone](https://cloud.githubusercontent.com/assets/10363809/19668814/e5621796-9a8c-11e6-9955-9b43cddd4e4c.PNG)


The issue behind that, in chart have width. and you label in such limit can not handled well, so it is needed something like scroll or other smart ways

**Comment by oysteinmoseng** [comment]
I see, this is not specific to showing value in legend, it will happen as long as you set `width` explicitly on the chart or legend: http://jsfiddle.net/omyqpdxj/1/

I suggest to make a request in our [UserVoice forum](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api) in order for this to be picked up for new features.

**Comment by TorsteinHonsi** [comment]
Note that you can set a width in the itemStyle in order to make it wrap: http://jsfiddle.net/highcharts/omyqpdxj/2/

**Comment by HackToday** [comment]
@TorsteinHonsi  Thanks. Not sure if it is the best way we can achieve.  I could have a try on our project to see if it can work friendly. Will tell you more after that.

**Comment by HackToday** [comment]
Frankly speaking, it is not good.

First, as  my chart title not simple show one item, it have something like below

```
           labelFormatter: function () {
                       return   '<span class="legend-title">'+ this.name +'</span>'
                +'<span class="legend-avg"> '+ "78" +'</span>';

           }
```

So if that, the chart would display like that:
![1111](https://cloud.githubusercontent.com/assets/10363809/19711767/a7178e60-9b6a-11e6-8c70-2933c2d64969.PNG)

It looks not good.

**Comment by MiroLiska** [comment]
Torstein, please implement ellipsis by long labels. Wrapping texts or text flying out of legend containers are not good for anyone.

**Comment by TorsteinHonsi** [comment]
There is support for ellipsis, but currently it won't combine word wrap _and_ ellipsis:
http://jsfiddle.net/highcharts/omyqpdxj/3/

**Comment by MiroLiska** [comment]
I believe your solution for ellipsis works only if the width is given as well. I do not want to specify it, I want it to be automatic, but never bigger that chart itself. see the problem here: http://jsfiddle.net/omyqpdxj/4/
I took the liberty to modify the highcharts code and come up with the a "solution" where the legend never grows outside the chart box: http://jsfiddle.net/m3y0b844/. Works however only for legends below the chart :( -  See also internal case #53942

**Comment by MiroLiska** [comment]
Hi 
I have adjusted the solution also for the legends on the right and left hand side - see http://jsfiddle.net/m3y0b844/2/

**Comment by HackToday** [comment]
But  'ellipsis' maybe not good to address issue like 

as I 

```
labelFormatter: function () {
                       return   '<span class="legend-title">'+ this.name +'</span>'
                +'<span class="legend-avg"> '+ "78" +'</span>';

           }
```


I can allow name to have ellipsis, but not for my value `78`,  Ideally scroll ways is better, and can address such issue.

**Comment by MiroLiska** [comment]
Yes, you are right, my code is not compatible with the idea of having the value in the legend. I needed in my project just the simple ellipsis in the labels and was directed to this issue which is quite similar. Anyway, the hack I am using is pretty straightforward and could be applied also to scenarios like yours.

**Comment by HackToday** [comment]
It seems we still can not solve the overlap issue ?

**Comment by TorsteinHonsi** [comment]
It now adds ellipsis if you set the `itemWidth`. Will add a commit that also responds to `width`.

**Comment by HackToday** [comment]
@TorsteinHonsi  do you mean this ?

https://jsfiddle.net/sfb0rboz/3/

**Comment by KacperMadej** [comment]
@HackToday More like:
- current version not working: https://jsfiddle.net/ds6zvsw3/1/
- master version with the fix: https://jsfiddle.net/ds6zvsw3/

**Comment by HackToday** [comment]
Thanks  @KacperMadej 

But as I said, the above solution may not solve issue like I mentioned before

> labelFormatter: function () {
                       return   '<span class="legend-title">'+ this.name +'</span>'
                +'<span class="legend-avg"> '+ "78" +'</span>';  } 

> I can allow name to have ellipsis, but not for my value 78

**Comment by HackToday** [comment]
I finally solved this issue with the hack ways, for labelFormatter use some customized html code to make value and label display correctly.
