### ISSUE TITLE
dataLabels.softConnector does nothing

### ISSUE THREAD

**Issue by wojtekmaj** [highcharts/highcharts#5868]
#### Expected behaviour

dataLabels.softConnector changing style of the connector to not softened if set to false.

#### Actual behaviour

dataLabels.softConnector is not changing style of the connector.

#### Live demo with steps to reproduce

Click on two examples included in the API under following link. Compare.
http://api.highcharts.com/highcharts/plotOptions.pie.dataLabels.softConnector

#### Affected browser(s)

All

**Comment by wojtekmaj** [comment]
Changing Highcharts version to 4.2.2 in the example makes them working correctly, so the issue is likely to be since 5.0.

**Comment by wojtekmaj** [comment]
Looks this.options.softConnector returns undefined and defaults to true in seriesTypes.pie.prototype.connectorPath.

**Comment by pawelfus** [comment]
@wojtekmaj - thank you for reporting!

*Internal note:*
No extra unit test, as we already have `pie-datalabels-softconnector-false` and `pie-datalabels-softconnector-true` tests.
