### ISSUE TITLE
Can the new version be released?

### ISSUE THREAD

**Issue by lusa** [highcharts/highcharts#5872]
Sorry for the spam, I have an issue in production that was fixed last week by one of your contributors, was told it would be released last week. Would be great to have this fixed in production. Thanks.

**Comment by oysteinmoseng** [comment]
We are aiming for release of `5.0.1` as soon as possible, most likely this week.

**Comment by jon-a-nygaard** [comment]
@lusa Hi again, sorry we did not make it to release last week, but we are very very close. Hang in there.
Related issue: #5833
