### ISSUE TITLE
bubble charts selectively hide data points if the chart is small

### ISSUE THREAD

**Issue by dbasner** [highcharts/highcharts#5873]
#### Expected behaviour
Draws bubbles for every single data point I pass it, regardless of the width/height of the containing box. Should do the same for any data point in any type of graph.

#### Actual behaviour
Hides some data points if the height of the chart is short, and when it does hide this data it does not notify the user.

#### Affected browser(s)
Google Chrome  53.0.2785.101

![scatterchartsmalldatahidden](https://cloud.githubusercontent.com/assets/6394494/19664170/383a13ae-9a0d-11e6-9975-82133a452962.PNG)
![scatterchartlargedatashown](https://cloud.githubusercontent.com/assets/6394494/19664171/383cd6e8-9a0d-11e6-91ff-675ef7ce9121.PNG)

**Comment by oysteinmoseng** [comment]
Thanks for reporting. Do you have a live demo of the issue? Our bubble chart demo seems to handle low heights without hiding: http://jsfiddle.net/oysteinmoseng/5rqoz5hr/.

**Comment by dbasner** [comment]
Here is a jsfiddle: http://jsfiddle.net/dbasner/8457ctpj/11/, change the height of the div between something like 200px and 500px and notice how it does not show all the data. Let me know if this helps or if you have any questions, thanks for the response!

**Comment by oysteinmoseng** [comment]
This seems to be an issue between `bubble.minSize` and `maxSize`. Because `maxSize` is defined in percentage, you risk it becoming smaller than `minSize` when you resize the chart. We should probably add some logic to catch these edge cases.

**Comment by dbasner** [comment]
That's a good point, I'll switch it to be consistent on my end.  Thank you for your help Øystein!
