### ISSUE TITLE
Unable to install Highchart 5.0.0

### ISSUE THREAD

**Issue by rohitszone** [highcharts/highcharts#5874]
npm install highcharts --save
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "highcharts" "--save"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Cannot read property 'localeCompare' of undefined
npm ERR!

More log from npm-debug

0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'highcharts',
1 verbose cli   '--save' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData highcharts
8 silly fetchNamedPackageData highcharts
9 silly mapToRegistry name highcharts
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://xx.it.xxx.com:4873/
12 silly mapToRegistry uri http://xx.it.xxx.com:4873/highcharts
13 verbose request uri http://xx.it.xxx.com:4873/highcharts
14 verbose request no auth needed
15 info attempt registry request try #1 at 11:39:31 AM
16 verbose request id c59884e4f8355516
17 verbose etag "8428e56d8b7b2bab88499a0d770a4c1a"
18 http request GET http://xx.it.xxx.com:4873/highcharts
19 http 304 http://xx.it.xxx.com:4873/highcharts
20 verbose headers { 'x-powered-by': 'Sinopia/1.4.0',
20 verbose headers   etag: '"8428e56d8b7b2bab88499a0d770a4c1a"',
20 verbose headers   'x-status-cat': 'http://flic.kr/p/aXY3dH',
20 verbose headers   date: 'Tue, 25 Oct 2016 00:39:31 GMT',
20 verbose headers   connection: 'keep-alive' }
21 silly get cb [ 304,
21 silly get   { 'x-powered-by': 'Sinopia/1.4.0',
21 silly get     etag: '"8428e56d8b7b2bab88499a0d770a4c1a"',
21 silly get     'x-status-cat': 'http://flic.kr/p/aXY3dH',
21 silly get     date: 'Tue, 25 Oct 2016 00:39:31 GMT',
21 silly get     connection: 'keep-alive' } ]
22 verbose etag http://xx.it.xxx.com:4873/highcharts from cache
23 verbose get saving highcharts to C:\Users\t602725\AppData\Roaming\npm-cache\jabdl3559.it.statestr.com_4873\highcharts\.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly resolveWithNewModule highcharts@5.0.0 checking installable status
37 silly cache add args [ 'highcharts', null ]
38 verbose cache add spec highcharts
39 silly cache add parsed spec Result {
39 silly cache add   raw: 'highcharts',
39 silly cache add   scope: null,
39 silly cache add   name: 'highcharts',
39 silly cache add   rawSpec: '',
39 silly cache add   spec: '*',
39 silly cache add   type: 'range' }
40 silly addNamed highcharts@*
41 verbose addNamed "*" is a valid semver range for highcharts
42 silly addNameRange { name: 'highcharts', range: '*', hasData: false }
43 silly mapToRegistry name highcharts
44 silly mapToRegistry using default registry
45 silly mapToRegistry registry http://xx.it.xxx.com:4873/
46 silly mapToRegistry uri http://xx.it.xxx.com:4873/highcharts
47 verbose addNameRange registry:http://xx.it.xxx.com:4873/highcharts not in flight; fetching
48 verbose get http://xx.it.xxx.com:4873/highcharts not expired, no request
49 silly addNameRange number 2 { name: 'highcharts', range: '*', hasData: true }
50 silly addNameRange versions [ 'highcharts',
50 silly addNameRange   [ '0.0.1',
50 silly addNameRange     '0.0.2',
50 silly addNameRange     '0.0.3',
50 silly addNameRange     '0.0.4',
50 silly addNameRange     '0.0.5',
50 silly addNameRange     '0.0.6',
50 silly addNameRange     '0.0.8',
50 silly addNameRange     '0.0.9',
50 silly addNameRange     '0.0.10',
50 silly addNameRange     '0.0.11',
50 silly addNameRange     '4.1.10',
50 silly addNameRange     '4.2.0',
50 silly addNameRange     '4.2.1',
50 silly addNameRange     '4.2.2',
50 silly addNameRange     '4.2.3',
50 silly addNameRange     '4.2.4',
50 silly addNameRange     '4.2.5',
50 silly addNameRange     '4.2.6',
50 silly addNameRange     '4.2.7',
50 silly addNameRange     '5.0.0' ] ]
51 silly addNamed highcharts@5.0.0
52 verbose addNamed "5.0.0" is a plain semver version for highcharts
53 silly cache afterAdd highcharts@5.0.0
54 verbose afterAdd C:\Users\t602725\AppData\Roaming\npm-cache\highcharts\5.0.0\package\package.json not in flight; writing
55 verbose afterAdd C:\Users\t602725\AppData\Roaming\npm-cache\highcharts\5.0.0\package\package.json written
56 verbose stack TypeError: Cannot read property 'localeCompare' of undefined
56 verbose stack     at installOrder (c:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:241:32)
56 verbose stack     at Array.sort (native)
56 verbose stack     at c:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:240:27
56 verbose stack     at cb (c:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
56 verbose stack     at resolveWithExistingModule (c:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:377:3)
56 verbose stack     at c:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:347:5
56 verbose stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
56 verbose stack     at Array.forEach (native)
56 verbose stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
56 verbose stack     at Array.forEach (native)
57 verbose cwd c:\DMH3Workspace\dmh-uit-parent\dmh-uit-web\ui
58 error Windows_NT 6.1.7601
59 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "highcharts" "--save"
60 error node v5.0.0
61 error npm  v3.3.6
62 error Cannot read property 'localeCompare' of undefined
63 error If you need help, you may report this error at:
63 error     <https://github.com/npm/npm/issues>
64 verbose exit [ 1, true ]

**Comment by jon-a-nygaard** [comment]
@rohitszone This seems to be a common issue with NPM v3.3.6, you should try to upgrade your version of NPM. More information about this can be found in the [reported issue at npm/npm](https://github.com/npm/npm/issues/10172)
