### ISSUE TITLE
Points under the floor still displayed

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#5875]
#### Expected behavior

Only the last two points should be visible.
#### Actual behavior

All points are visible.
#### Live demo with steps to reproduce

http://jsfiddle.net/9pbj65f2/1/

Changing the floor from 18 to 19 causes the demo to behave as expected. What is magic about 18 or 19?

**Comment by pawelfus** [comment]
Hi @dandv, it's caused by [`startOnTick`](http://api.highcharts.com/highstock/yAxis.startOnTick) option. When disabled, you can see the result: http://jsfiddle.net/9pbj65f2/2/

**Comment by oysteinmoseng** [comment]
Should we do something about the defaults here?
