### ISSUE TITLE
What is the status of the test suite?

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#5876]
The test suite [appears](https://github.com/highcharts/highcharts/tree/master/test) to be quite old and sparse, but I admit I have only skimmed through the code. Just curious about its status. Thanks.

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

To be specific, we have 1500 active tests and counting. See https://github.com/highcharts/highcharts/tree/master/utils#tests
