### ISSUE TITLE
Docs: link to yAxis.softMin is broken

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#5877]
At http://api.highcharts.com/highcharts/yAxis.min

**Comment by TorsteinHonsi** [comment]
Thanks! softMin is not yet released, will be soon.

**Comment by doeg** [comment]
@TorsteinHonsi Is there a way to track when `softMin` and `softMax` are released? Looking forward to it!

**Comment by doeg** [comment]
Oops, apologies -- I see that it's part of the 5.0.1 milestone, which was released on October 26th. :) Thanks!

**Comment by TorsteinHonsi** [comment]
You're welcome 👍
