### ISSUE TITLE
Docs: broken link to the Axis object

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#5879]
The link to [the Axis object](http://api.highcharts.com/highcharts/axis.object) in the first paragraph of the page is broken in:

* http://api.highcharts.com/highcharts/xAxis
* http://api.highcharts.com/highcharts/yAxis
* http://api.highcharts.com/highcharts/zAxis

Should be `/highcharts/Axis`.

**Comment by TorsteinHonsi** [comment]
Thanks!
