### ISSUE TITLE
colorAxis.update not working since 5.0.0

### ISSUE THREAD

**Issue by transpirman** [highcharts/highcharts#5881]
#### Expected behaviour
$("#container").highcharts().colorAxis[0].update({ max: newValue }) updates the colorAxis with new max value

#### Actual behaviour
the whole colorAxis text disappears

#### Live demo with steps to reproduce
http://jsfiddle.net/slorenc/01bsb417/

#### Affected browser(s)
tested on Chrome

**Comment by transpirman** [comment]
additional comment:
-----------------------
when resizing the window screen, 
the new text (with vertical bars) appears on the top left of the canvas element (so out of the legend box)

**Comment by pawelfus** [comment]
*Internal note:*

Updating an axis removes all [extra references](https://github.com/highcharts/highcharts/blob/c259259cd79586fb276eb3c8cd36278a74aa9370/js/parts/Axis.js#L2429). But updating a color axis expects [`axis.legendItem`](https://github.com/highcharts/highcharts/blob/c259259cd79586fb276eb3c8cd36278a74aa9370/js/parts-map/ColorAxis.js#L426) to exist.

**Comment by radiolips** [comment]
@TorsteinHonsi I'm still having this issue. By updating just the highmaps' colorAxis "stops" option, I'm left with only a tiny bit of an axis, as seen in this screenshot: https://www.dropbox.com/s/0vrme1v0mjina61/Screenshot%202016-11-23%2012.55.01.png?dl=0

If I remove the call to `update`, there's no problem. I'm guessing that some options are still being wiped.

**Comment by radiolips** [comment]
Just to add, this works on `v5.0.2` but breaks on `v5.0.3`.

**Comment by radiolips** [comment]
There's definitely something still being wiped. By commenting out `delete axis[n];` from this block of code:
```
                // Delete all properties and fall back to the prototype.
                for (n in axis) {
                    if (axis.hasOwnProperty(n) && inArray(n, axis.keepProps) === -1) {
                        delete axis[n];
                    }
                }
```
then my code works.
