### ISSUE TITLE
Column chart histogram showing spaces between columns

### ISSUE THREAD

**Issue by naranjja** [highcharts/highcharts#5883]
#### Expected behaviour
Column chart with `pointPadding: 0`, `borderWidth: 0`, `groupPadding: 0`, and `shadow: false` should display columns tight together with no space between them, simulating a histogram.

#### Actual behaviour
Columns are separated. This used to work in version 4.2.5 but doesn't work on version 5.0.0.

#### Live demo with steps to reproduce
https://jsfiddle.net/naranjja/8g1jrpze/

#### Affected browser(s)
Mozilla Firefox 51.0a2 (2016-10-25) (32-bit)
Google Chrome 54.0.2840.71 m (64-bit)

**Comment by sebastianbochan** [comment]
_Internal note_
Regression from 4.2.6

**Comment by TorsteinHonsi** [comment]
Something happens in v4.2.6, though I'm not sure it's a bug. See [this sample](https://jsfiddle.net/highcharts/8g1jrpze/1/), where it is clearer that each column is one category unit wide, according to the default [pointRange](http://api.highcharts.com/highcharts/plotOptions.column.pointRange).

**Comment by naranjja** [comment]
Right, it makes sense for columns to be one category unit wide, but how would you make a histogram now?

**Comment by TorsteinHonsi** [comment]
You either:

* make sure the X axis is _not_ a category axis: https://jsfiddle.net/highcharts/8g1jrpze/2/
* or specify a pointRange: https://jsfiddle.net/highcharts/8g1jrpze/3/

**Comment by TorsteinHonsi** [comment]
See also our featured Histogram sample: http://www.highcharts.com/demo/combo-histogram

**Comment by naranjja** [comment]
Thank you!
