### ISSUE TITLE
Sparkline tooltip not visible

### ISSUE THREAD

**Issue by sp-csmithhill** [highcharts/highcharts#5885]
#### Expected behaviour
When mousing over a sparkline, the tooltip should be visible. 

#### Actual behaviour
When rendered in a table, the tooltip is hidden in the cell. I don't see any options in http://api.highcharts.com/highcharts/tooltip to fix this

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/sparkline/

Mouse over sparklines

#### Affected browser(s)
Chrome, Firefox

**Comment by oysteinmoseng** [comment]
![screen shot 2016-10-26 at 15 27 03 3](https://cloud.githubusercontent.com/assets/5276642/19727914/a02887d6-9b91-11e6-9f31-67300970d357.png)
Seems to work here?

**Comment by oysteinmoseng** [comment]
Assuming it's related to fixed bug #5745 and now working in 5.0.1.
