### ISSUE TITLE
Clicking on pie chart sector during load animation causes positioning issue

### ISSUE THREAD

**Issue by JonGinty** [highcharts/highcharts#5886]
#### Expected behaviour

Chart loads and all sectors are positioned and sized correctly
#### Actual behaviour

Segment stops at position where it was clicked and will remain there until chart is reloaded.
If the segment was smaller than its full size when clicked, it will remain at that size.
#### Live demo with steps to reproduce

(this actually affects the official demo so I've linked that jsfiddle below)
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pie-basic/

Steps: click on any chart sector while chart is loading
#### Affected browser(s)

Reproduced on Chrome 53.0.2785.143 and Edge 38.14393.0.0

Apologies if this is a dupe, the quick search that I did didn't turn up anything like this

**Comment by oysteinmoseng** [comment]
Thanks for reporting this.

**Comment by TorsteinHonsi** [comment]
Even more pronounced with a slower animation: http://jsfiddle.net/highcharts/74jo5ym2/
