### ISSUE TITLE
Bubbles move to top left (almost invisble) during mouseover on bubble

### ISSUE THREAD

**Issue by laxmivipin23** [highcharts/highcharts#5887]
#### Expected behaviour
The bubbles retain their original coordinates during mouseover and tooltip appears 

#### Actual behaviour
The tool tip appears. But the bubble gets grayed out and moves to top left. If we do mouse over for each bubble all bubbles disappear

#### Live demo with steps to reproduce
Happening in my code from last 30 minutes. I checked jsfiddle to validate the same. Similar behavior is exhibited in:

I was looking at
http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/bubble-size/

#### Affected browser(s)
Firefox (This is the only browser I use)

**Comment by pawelfus** [comment]
Hi @laxmivipin23 

Thank you for reporting. This is caused by just released 5.0.1 version which causes this bug.

**Workaround:**
Set `plotOptions.bubble.marker.radius = 0`, demo: http://jsfiddle.net/9j31jrmo/
