### ISSUE TITLE
[changelog] Accordion doesn't expand for 5.0.1 bugfixes 

### ISSUE THREAD

**Issue by lusa** [highcharts/highcharts#5890]
Thanks a lot for releasing 5.0.1 and 5.0.2! I am testing these out now. Loving the point hover animations! Small bug I noticed on the changelog.. the accordion doesn't expand on 5.0.1 so we can't see all the bugfixes there: http://www.highcharts.com/documentation/changelog

**Comment by TorsteinHonsi** [comment]
Thanks! Well it actually expands the two bug fixes from v5.0.2, making it look like we want to draw attention away from the more bulky v5.0.1. Anyway, fixed now 👍
