### ISSUE TITLE
Multiple Series error in svg rendering [HighStock -> Highchart]

### ISSUE THREAD

**Issue by avdaredevil** [highcharts/highcharts#5892]
### Expected behaviour

Spline plot added multiple series, and as I append data to each series everything should run smoothly
### Actual behaviour

Huge performance hit, and these errors (in counts of hundreds):

``` javascript
highstock.js:54 Error: <path> attribute d: Expected number, "….14627380267771 C 315.0616246498…".
```
### Live demo with steps to reproduce

Go here: https://avdaredevil.github.io/highcharts-chart/
- Scroll to the first chart (spline chart).
- Enable Real-Time
- Open your dev console
- Click the center of the chart multiple times (6-7 times)
- Click `Add Data Point` a few times
- Notice all the errors

_**My Conjecture:** It is caused when the series start using the `pushData` over `addData` [API: Implementation is to type `app.$.splineChart.pushData` in your console on the page]. ie. When the series[`2..n`] shift add data rather than appending it_
### Affected browser(s)

No idea, just tested on chrome.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, but `pushData` is not a Highcharts API. Can you reproduce this issue outside your wrapper environment? The best starting point would be if you can modify [the featured sample](http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/stock/members/series-addpoint-shift/) to showcase your problem.

**Comment by LithMage** [comment]
Made an example since i am getting same (or very similar) error. It happens when you try to add data point by point and doesnt show any errors if data is loaded as one array (not in example).

In my case both data points and series are added dynamically
[JsFidle](http://jsfiddle.net/depfpegw/) just press button and look into console

**Comment by pawelfus** [comment]
Thanks @LithMage ! 

I have simplified your demo, without AJAX with random data and redrawing chart only once, after all modifications: http://jsfiddle.net/tueqcd4r/

Issue still exists. It's caused by animation, when disabled it works fine: http://jsfiddle.net/tueqcd4r/1/
