### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lang' of undefined - exporting.js

### ISSUE THREAD

**Issue by ElmiyaAgnes** [highcharts/highcharts#5893]
%script{:src => "https://code.highcharts.com/modules/exporting.js"}
This is calling an error in the web console - Uncaught TypeError: Cannot read property 'lang' of undefined

**Comment by pawelfus** [comment]
Hi @ElmiyaAgnes 

Thank you for reporting this, but could you recreate this issue in jsFiddle? Our demos looks fine, for example: http://jsfiddle.net/w7L1sn0y/

**Comment by ElmiyaAgnes** [comment]
Ya, it works fine in the demo. But I tried with adding just this script in my haml file and throwing this error in my console.

**Comment by pawelfus** [comment]
Please, contact with our [support team](http://www.highcharts.com/support) - they will help you with setting up the demo. This may not necessary be a Highcharts bug.

**Comment by ElmiyaAgnes** [comment]
Issue resolved by specifying the version.
%script{:src => "https://code.highcharts.com/4.2.2/modules/exporting.js"}
