### ISSUE TITLE
Title axis and values in the same place

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#5894]
Hello,
Y axis title overlaps values when rotation is set to 0.
#### Expected behaviour

Y axis title doesn't overlap values.
#### Actual behaviour

Y axis title overlaps values.
#### Live demo with steps to reproduce

http://jsfiddle.net/Pashe4ka/juvyuafr/
#### Affected browser(s)

Chrome 54

With best regards, Pavel Liasetski

**Comment by pawelfus** [comment]
Hi Pavel,

Thanks for reporting!
It's caused by `title.textAlign` (it is missing in the [docs](http://api.highcharts.com/highstock/yAxis.title)), which by default is set to `middle`. With disabled rotation I suggest to set this to `left`, demo: http://jsfiddle.net/4qaygLv1/

**Comment by pliasetski** [comment]
Thank you
