### ISSUE TITLE
Solidgauge - axis.update colors

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5895]
#### Actual behaviour
Error: VM356 solid-gauge.js:13 Uncaught TypeError: c.toColor is not a function

#### Live demo with steps to reproduce
1. Example: http://jsfiddle.net/wox1rwqz/
2. Click on the button
3. It causes an error: "VM356 solid-gauge.js:13 Uncaught TypeError: c.toColor is not a function"

#### Affected browser(s)
All browsers

**Comment by KieranDotCo** [comment]
Any idea when this change will be released? This is currently preventing us from upgrading to Highcharts 5.

**Comment by TorsteinHonsi** [comment]
It will be released this week or the next.

**Comment by kondalraodurgam** [comment]
![image](https://user-images.githubusercontent.com/20201281/29664906-44da2604-88ef-11e7-821e-a8c7e6c81cfd.png)


i'm also getting error message in console . i'm using highcharts

**Comment by pawelfus** [comment]
Hi @kondalraodurgam 

Could you recreate issue in jsFiddle? the original demo works fine.
