### ISSUE TITLE
tooltipRefresh event missing in v 5.0.2

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#5898]
Looks like the tooltipRefresh event was pulled out in v 5.0.2. Was this intentional? Can it be re-added?

#### Expected behaviour
tooltipRefresh should be triggered after the tooltip is refreshed as done in previous versions.

#### Actual behaviour
The tooltipRefresh event is not triggered.

#### Live demo with steps to reproduce
http://jsfiddle.net/highcharts/Ym4UA/

#### Affected browser(s)
chrome

**Comment by TorsteinHonsi** [comment]
The `tooltipRefresh` event was an internal hook that we used in the Canvas renderer for Android 2.x. We removed that in v5.0. You can achieve much of the same by extending the refresh method: http://jsfiddle.net/highcharts/Ym4UA/10/.

**Comment by Rashaine** [comment]
OK sounds good, that was my initial thought but after realizing that other people might be using the event I thought it was best to report it. I'll wrap the refresh method. Thank you.

**Comment by suganya-suvadi** [comment]
I am trying to replace usage of the event `tooltipRefresh ` by overriding tooltip's `refresh` as suggested here, after an upgrade to 5.0. 

We were using the event tooltipRefresh as follows - feeding formatter output into a custom div

```
Highstock.addEvent(chart, 'tooltipRefresh', function(event) {
         // output of the formatter was available in `event.text`. 
          $(customDiv).html(event.text);
});
```
However, with `refresh`, I am not able to get hold of formatter output -

```Highcharts.wrap(Highcharts.Tooltip.prototype, 'refresh', function(proceed, points, event) {  
              // I'd like to access formatter's output here
              // event, the mouse-over event here, does not contain it
});
```

Is there any other way to access output of formatter here?

**Comment by TorsteinHonsi** [comment]
Overriding the defaultFormatter seems to do the same trick: http://jsfiddle.net/highcharts/Ym4UA/11/

Or if you use your own tooltip.formatter, you can handle it directly from there.

**Comment by suganya-suvadi** [comment]
Used the tooltip content as required from within custom formatter; thanks for the swift help here!
