### ISSUE TITLE
Data label rendering has offset since 4.2.7 on bar charts 

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#5899]
See this fiddle (highcharts 4.2.4): http://jsfiddle.net/onemenny/2bf9cL7a/
When you minimize the chart width (increase the code pane size), the data labels of the bar charts will stand still 

Upgrade to highcharts 4.2.7/5.0.2, now when you minimize the labels disappear, it seems that the wrapping div inline style of "left" keeps changing instead of sticking to 0.

**Comment by TorsteinHonsi** [comment]
There is some custom HTML inside the labels so I'm not sure where the problem arises. Why not use the raw text directly? http://jsfiddle.net/highcharts/2bf9cL7a/2/

**Comment by onemenny** [comment]
Not wanting to sound rude - I don't want raw text  (one reason is css ellipsis) I need HTML. 
The HTML is very plain, just a div with some simple styles

**Comment by TorsteinHonsi** [comment]
Okay, fair point! 

#### Simplified demo
http://jsfiddle.net/highcharts/2bf9cL7a/5/

**Comment by TorsteinHonsi** [comment]
Regression since https://github.com/highcharts/highcharts/commit/c6eeb80
