### ISSUE TITLE
How to dynamically regenerate the Chart ?

### ISSUE THREAD

**Issue by seuaCoder** [highcharts/highcharts#5900]
#### Expected behaviour
Regenerate the chart with the new data given (new series, xAxis categories, new chart type ...). i know how to add series or update series but i want to regenerate a new chart with maybe a different type (spline, bar... ). Without reloading the page. 

#### Actual behaviour
The chart keep the same data even i regenerate it with:

highcharts.chart(name, new options)

#### Live demo with steps to reproduce

too much code, i wrapped it into a vuejs component

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
