### ISSUE TITLE
Tooltip split - ignores useHTML parameter

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5901]
#### Actual behaviour

Tooltip split - ignores useHTML parameter
#### Live demo with steps to reproduce

Example:
- http://jsfiddle.net/q5md5zp1/

Problem appears also in the styles mode.
#### Affected browser(s)

All browsers

**Comment by sebastianbochan** [comment]
_Internal note_
It seems that setting a flag `useHTML` here, 

```
owner.tt = tt = ren.label(
							null, 
							null, 
							null, 
							'callout',
							null,
							null,
							options.useHTML,
							null,
							'tooltip'
						)
```

solves the problem, but only for non-styled mode. In styled mode, pointer should be above tooltip to draw content.

**Comment by djtcin** [comment]
Seems like this issue was fixed by https://github.com/highcharts/highcharts/issues/7238

**Comment by pawelfus** [comment]
Thank you @djtcin ! Closing as duplicate.
