### ISSUE TITLE
Y axis label align

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#5902]
Hello,
Y axis label align doesn't work properly when it set to "right".
http://api.highcharts.com/highstock/yAxis.labels.align
#### Expected behaviour

Labels should align to right.
#### Actual behaviour

Labels don't align to right.
#### Live demo with steps to reproduce

http://jsfiddle.net/Pashe4ka/go8cct71/
#### Affected browser(s)

Chrome 54

**Comment by oysteinmoseng** [comment]
Seems like not enough padding is applied when using `align: 'right'`. Not specific to Highstock: http://jsfiddle.net/go8cct71/2/.

Looks fine with `align: 'left'` http://jsfiddle.net/go8cct71/3/

**Comment by TorsteinHonsi** [comment]
The joker is the [labels.x](http://api.highcharts.com/highcharts/yAxis.labels.x) option. When it is set to 0, it behaves well: http://jsfiddle.net/highcharts/go8cct71/4/.

**Comment by TorsteinHonsi** [comment]
I've updated the docs with a heads up for the `x` option: http://api.highcharts.com/highstock/yAxis.labels.align

**Comment by TorsteinHonsi** [comment]
The only possible fix for this as I can see it to implement a new option like `paddingX` or `marginX` or similar, so we can offset the label independent of its alignment.

**Comment by pliasetski** [comment]
Y axis labels workes different according to series axis postion.

Y axis labels don't overlap chart area
http://jsfiddle.net/Pashe4ka/L8Lby7rr/
http://jsfiddle.net/Pashe4ka/L8Lby7rr/1/

Y axis labels overlap chart area
http://jsfiddle.net/Pashe4ka/L8Lby7rr/2/

Is there a way to make y axis labels do not overlap in this case? -> http://jsfiddle.net/Pashe4ka/L8Lby7rr/2/

**Comment by TorsteinHonsi** [comment]
On stock charts, the default behaviour is that the first Y axis' labels overlap the plot area, while subsequent Y axis labels are drawn outside.

**Comment by TorsteinHonsi** [comment]
> Is there a way to make y axis labels do not overlap in this case? -> 

Sure, you just need to set the alignment and a suitable x offset: http://jsfiddle.net/L8Lby7rr/3/
