### ISSUE TITLE
Bubble click event not working

### ISSUE THREAD

**Issue by elmoro666** [highcharts/highcharts#5903]
#### Expected behaviour

Alert should pop up when bubble is clicked on. This worked in 4.2.4
#### Actual behaviour

Nothing happens. Event is not triggered
#### Live demo with steps to reproduce

https://jsfiddle.net/9r2o7m4w/

Change to 4.2.4 to see a working version.
#### Affected browser(s)

Tested in Chrome

**Comment by oysteinmoseng** [comment]
Thanks for reporting this.

**Comment by TorsteinHonsi** [comment]
It works in v5.0.0, fails in v5.0.1.

Fails since f8ea518

**Comment by elmoro666** [comment]
Thanks!
