### ISSUE TITLE
Navigator's height using 'chart' constructor

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#5904]
#### Expected behaviour

Series in the navigator should not be clipped.
#### Live demo with steps to reproduce

When using `stockChart` constructor everything is fine. With `chart` constructor, series in navigator is clipped.

Compare:
http://jsfiddle.net/pLf2534x/ vs http://jsfiddle.net/pLf2534x/1/

**Comment by KacperMadej** [comment]
*Internal note:* Collision with #2939. Instead of checking if a chart is a stock chart checking for a chart not being 3d should be resolving both issues.
