### ISSUE TITLE
Why timestamp is not showing as a proper date?

### ISSUE THREAD

**Issue by sajeetharan** [highcharts/highcharts#5905]
#### Expected behaviour

It should show exact date which is being shown in tooltip.
#### Actual behaviour

It shows incorrect values.
#### Live demo with steps to reproduce

http://jsfiddle.net/sajeetharan/95LX7/70/

**Comment by oysteinmoseng** [comment]
Works if you specify the format for other intervals: http://jsfiddle.net/95LX7/78/.

Not sure if this is by design? @TorsteinHonsi
Should we allow a generic date format that always applies?

**Comment by TorsteinHonsi** [comment]
This is by design. The tooltip is set up to show each _points_ datetime. The axis however, only puts ticks on interpolated values. Ticks don't necessarily correspond with points, as can be seen for example in http://www.highcharts.com/demo/line-time-series

**Comment by TorsteinHonsi** [comment]
PS: 
If you want one-to-one match between points and ticks, you can use a category axis.
