### ISSUE TITLE
Heatmap col size bug

### ISSUE THREAD

**Issue by Hesesses** [highcharts/highcharts#5907]
#### Expected behaviour
I would like to have each col as same size

#### Actual behaviour
Sometimes cols are wider than others

#### Live demo with steps to reproduce

![image](https://cloud.githubusercontent.com/assets/2721970/19848023/5fedf474-9f53-11e6-98c6-a226a451129a.png)

#### Affected browser(s)
Tested only on latest chrome

**Comment by oysteinmoseng** [comment]
Do you have a live demo of the issue on e.g. jsFiddle? Our own demo seems to be correct: http://www.highcharts.com/demo/heatmap.

**Comment by Hesesses** [comment]
http://jsfiddle.net/Hjdnw/2044/

**Comment by oysteinmoseng** [comment]
Simplified example: http://jsfiddle.net/kzybxovo/

This happens when colsize is set to be bigger than the X-interval of the data. Not sure if this should be considered a data problem or an issue with heatmaps?

**Comment by Hesesses** [comment]
Do you have any ideas how to fix this without changing the data?

**Comment by oysteinmoseng** [comment]
Not off the top of my head.. @TorsteinHonsi can you think of any workaround for this?

**Comment by TorsteinHonsi** [comment]
Interesting case... What we need is individual widths for each of the cells. I experimented with adding a `point.colsize` option in the [translate function](https://github.com/highcharts/highcharts/blob/v5.0.2/js/parts-map/HeatmapSeries.js#L86-L87), but we still can't control the position perfectly. 

```js
			var xPad = (point.colsize || options.colsize || 1) / 2,
				yPad = (point.rowsize || options.rowsize || 1) / 2,
```

Have you considered using a polygon series for this?
