### ISSUE TITLE
Missing documentation for chart.rangeSelector.clickButton

### ISSUE THREAD

**Issue by mateuspv** [highcharts/highcharts#5908]
Hi, 
Stock chart: After a while looking for how to trigger "click" in a rangeSelector button I found a solution:
```JS
chart.rangeSelector.clickButton(1, true); // where 1 is the index
```
This method seems **undocumented**
Could someone please document it(make it visible in the website api) ?

Code: https://github.com/highcharts/highcharts/blob/9526dc5bd4cb3c76e0c80862d30eab312b001900/js/parts/RangeSelector.js#L87

Thanks!

**Comment by TorsteinHonsi** [comment]
FYI there are lots of undocumented functions in the various Highcharts object, it just means that they are internal and we can't guarantee that they will remain unchanged in the future. But we should consider publishing documentation for these internals too.

@pawelfus If we had JSDoc consistently implemented we could do this low-maintenance.
