### ISSUE TITLE
Column chart legend markers circles in 5.0

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#5910]
This behavior seems to have started happening after upgrading to Highcharts 5.0.2, is this expected? If so how do I switch back to rendering rectangles for the markers?

#### Expected behaviour
Legend markers should be rectangles as they previously were in older versions.

#### Actual behaviour
After update legend markers are circles.

#### Live demo with steps to reproduce
http://jsfiddle.net/gb32bx2j/145/

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
It is expected. It's a design change for v5. You can revert it by setting `symbolRadius` to 0 like it was in v4.

**Comment by Rashaine** [comment]
Ok, thank you.
