### ISSUE TITLE
An inverted waterfall chart is not drawn correctly

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5911]
#### Expected behaviour
A waterfall chart is drawn correctly in an inverted chart with reversed axis.
`chart.inverted: false, xAxis.reversed: false, yAxis.reversed: false` ok http://jsfiddle.net/t2Lha3at/7/
`chart.inverted: false, xAxis.reversed: true, yAxis.reversed: false` ok http://jsfiddle.net/t2Lha3at/8/

#### Actual behaviour
It seems that when a chart is inverted it caused misplacing of points or connectors depending on axis reversion.

`chart.inverted: false, xAxis.reversed: false, yAxis.reversed: true` points ok, connectors misplaced http://jsfiddle.net/t2Lha3at/9/
`chart.inverted: false, xAxis.reversed: true, yAxis.reversed: true` points ok, connectors misplaced http://jsfiddle.net/t2Lha3at/10/
`chart.inverted: true, xAxis.reversed: false, yAxis.reversed: false` points misplaced, connectors ok http://jsfiddle.net/t2Lha3at/11/
`chart.inverted: true, xAxis.reversed: true, yAxis.reversed: false` points misplaced, connectors ok http://jsfiddle.net/t2Lha3at/12/
`chart.inverted: true, xAxis.reversed: false, yAxis.reversed: true` points misplaced, connectors misplaced http://jsfiddle.net/t2Lha3at/13/
`chart.inverted: true, xAxis.reversed: true, yAxis.reversed: true` points misplaced, connectors misplaced http://jsfiddle.net/t2Lha3at/14/

**Comment by oysteinmoseng** [comment]
Thank you for reporting this.

**Comment by sebastianbochan** [comment]
+1

**Comment by jacowley** [comment]
@sebastianbochan I think it worked fine in 4.2.6, but is broken in 4.2.7.

**Comment by sebastianbochan** [comment]
@jacowley You are absolutey right, my bad. I edited my last comment.

**Comment by jacowley** [comment]
@pawelfus I believe it was caused by the fix for #5646 https://github.com/highcharts/highcharts/commit/406257d2225e4933012fa63944e32817f67c12aa

**Comment by pawelfus** [comment]
Hi @jacowley - I agree, this commit is the culprit. Reverting this commit fixes issue with bars positions, but issue with reversed yAxis and connectors remains.

**Comment by pawelfus** [comment]
Demo with fix applied: http://jsfiddle.net/9bqardyp/
