### ISSUE TITLE
stickyTracking: false on bubble charts doesn't remove halo on mouseout

### ISSUE THREAD

**Issue by khoomeister** [highcharts/highcharts#5913]
#### Expected behaviour

1. Set `stickyTracking: false` on a bubble series with halo on hover.
2. Mouseover a bubble.
3. Mouseout a bubble.
4. Expect halo to vanish.

#### Actual behaviour

The halo stays around until you mouseover another bubble in the same series.

#### Live demo with steps to reproduce

https://jsfiddle.net/khoomeister/usx3usdp/1/

(if you change highcharts version to let's say 4.2.2, it works as expected)

Doco: http://api.highcharts.com/highcharts/plotOptions.bubble.stickyTracking

**Comment by TorsteinHonsi** [comment]
Fixed since #5903: http://jsfiddle.net/highcharts/usx3usdp/3/
