### ISSUE TITLE
Tooltip formatter doesn't correctly hide the tooltip in Highcharts 5.0.2 

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#5915]
#### Expected behaviour
Returning false should disable(hide) the tooltip.

#### Actual behaviour
The tooltip is shown after it is created/initialized (via getLabel()) while the isHidden bool is still set to true so the hide code short-circuits and the empty tooltip remains visible in the upper left corner of the chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/aepq5rf6/

Hover over the first data point (Jan) and note that the empty tooltip is incorrectly shown. After a valid tooltip is shown the code will function as desired.

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
It's a regression, worked in v4: http://jsfiddle.net/highcharts/aepq5rf6/1/
