### ISSUE TITLE
Highstock navigator behaviour with x Axis

### ISSUE THREAD

**Issue by shubhijain106** [highcharts/highcharts#5916]
#### Expected behaviour
I am programatically setting x Axis extremes( xAxis.setExtrmes(startval,endval )  and wish to move navigator handles (dynamically) also to reflect that range .
How can I achieve it?

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

Having said that, the navigator handles will move to the new range by default: http://jsfiddle.net/highcharts/1x9ugdmf/
