### ISSUE TITLE
TOOLTIP - snap distance not working when tooltip is shared

### ISSUE THREAD

**Issue by poolerMF** [highcharts/highcharts#5917]
#### Expected behaviour
showing tooltip by snap distance

#### Actual behaviour
snap distance not working when tooltip is shared

#### Live demo with steps to reproduce
http://jsfiddle.net/5uuux1qf/

#### Affected browser(s)
all

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! The behaviour is as intended, but it wasn't mentioned in the docs. [It is now](http://api.highcharts.com/highcharts/tooltip.snap).

When the tooltip is shared or split, we only search for the closest point along the X axis.
