### ISSUE TITLE
[Highstock-Candlestick]: Giving more candlestick data that the chart can display displays only the last candlestick

### ISSUE THREAD

**Issue by magneticcore** [highcharts/highcharts#5920]
#### Expected behaviour
if  an important quantity of candlestick data is given to the chart, and it cannot display them all in its view space, it must reduce the number of displayed candlesticks and adapte the axis x  and y consequently.

#### Actual behaviour
if  an important quantity of candlestick data is given to the chart and the chart cannot display them all because of missing space, it just displays the last candlestick. No horizontal scrollîng is possible, no zoom in/out.

#### Live demo with steps to reproduce
http://jsfiddle.net/d3dotyb0/

Please reduce horizontally the cell containing the chart to see the problem. And increase horizontally until the chart displays all candlesticks as normal.

#### Affected browser(s)
IE11, Firefox 43.0.1,Chrome 54.0.2840.71 m

**Comment by oysteinmoseng** [comment]
Thanks for reporting.

Minimal example: http://jsfiddle.net/ytppak04/

**Comment by pawelfus** [comment]
Hmm.. we have errors in js console, that data is not sorted. After correct sorting, we get proper result: http://jsfiddle.net/ytppak04/1/

**Comment by oysteinmoseng** [comment]
Aha!
