### ISSUE TITLE
Horizontal legend height

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#5921]
#### Behaviour
It seems that there is a limitation of a legend height inside of Legend.prototype.handleOverflow() function:

`if (options.layout === 'horizontal') {
    spaceHeight /= 2;
}`

that does not allow maxHeight property to be a higher value than half of the spaceHeight 

`spaceHeight = chart.spacingBox.height + (alignTop ? -optionsY : optionsY) - this.padding`

when layout is set to horizontal.

#### Live demo with steps to reproduce
https://jsfiddle.net/4zbLfz24/1/

**Comment by oysteinmoseng** [comment]
Added a suggested fix, hopefully this does not break something else.

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng We need a test too...
