### ISSUE TITLE
Highstock does not render columns correctly with linked axis

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5923]
#### Actual behaviour
In Highstock with two series (line, column) and two xAxis (Axis are linked with series 1-1, and one axis is linked to another) columns are not drawn correctly.

#### Live demo with steps to reproduce
http://jsfiddle.net/g8r4ayg9/4/

Setting column's point range http://jsfiddle.net/g8r4ayg9/5/
or changing the order of the series http://jsfiddle.net/g8r4ayg9/6/
seems to help in that case.

**Comment by oysteinmoseng** [comment]
Thank you for reporting.
