### ISSUE TITLE
Highstock: dynamically added axes on export has wrong extremes

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5924]
#### Behaviour
Axes added dynamically have different indexes than axes added from chart's config. 

Navigator yAxis is added as a last in yAxis array. If a chart is created without y axes then "navigator-y-axis" is second in yAxis array of a chart. Then new axes are added and they have higher indexes in the array.

On export [the copy is created via config](https://github.com/highcharts/highcharts/blob/master/js/modules/exporting.src.js#L339).  The "navigator-y-axis" is added as a last axis into chart's yAxis array.

[Here](https://github.com/highcharts/highcharts/blob/master/js/modules/exporting.src.js#L343-L345) the exporting module is looping over y axes from original chart - the `i`. The same variable is also used for finding axis in the `chartCopy`, but those charts have different yAxis arrays, so getExtremes is working for one axis and setExtremes is working a different one.

#### Live demo with steps to reproduce
http://jsfiddle.net/xuwxjy56/3/
1. Click the "Add series" button - axes will be added dynamically.
2. Click the "Zero Scale" button - extremes will be changed.
3. Export the chart.
4. Extremes for left-most yAxis are wrong and switched with the navigator yAxis and black series is not visible (due to the extremes that are wrongly set).

**Comment by KacperMadej** [comment]
+1

**Comment by Newan** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Handier demo: http://jsfiddle.net/highcharts/xuwxjy56/5/
