### ISSUE TITLE
Column position out of chart when using switchRowsAndColumns - it was working in 4.1.7

### ISSUE THREAD

**Issue by plusz** [highcharts/highcharts#5925]
#### Expected behaviour
All serie elements should be visible on the chart.
In 4.1.7 first serie has position:
<rect x="20.5" y="37.5" width="9" height="123" stroke="#FFFFFF" stroke-width="1" fill="#7cb5ec" rx="0" ry="0"></rect>

#### Actual behaviour
First and last element is not displayed on the chart. It looks like margin -50px fro data series.
In 5.0.2 firs serie position has negative x
<rect x="-15.5" y="37.5" width="10" height="123" fill="#7cb5ec" class="highcharts-point highcharts-color-0" stroke="#ffffff" stroke-width="1"></rect>

#### Live demo with steps to reproduce
expected (4.1.7)
http://jsfiddle.net/porzechowski/6zccpt81/

actual (5.0.2)
http://jsfiddle.net/porzechowski/301gb8t8/

#### Affected browser(s)
All. Issue is in serie calculation.

**Comment by oysteinmoseng** [comment]
Unrelated to data module, the actual data is the issue. Fails since 4.1.10. http://jsfiddle.net/aw5j4e38/
