### ISSUE TITLE
Exported to SVG charts can have the same id for clipPath and a wrong clipPath is used

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5926]
#### Behaviour
When exporting charts to SVG and then placing those SVGs into a site clipPath id is duplicated. 
IE11 and Firefox are using the first clipPath and second chart is wrongly clipped.

#### Live demo with steps to reproduce
https://jsfiddle.net/8rkkqmLf/
The two charts are exported to SVG from a simple demo with just changed height.

#### Affected browser(s)
IE11, Firefox

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi Is it possible for the svg to look within itself for the clipPath, in other words have a more specific rule to identify the clipPath?

**Comment by TorsteinHonsi** [comment]
The Highcharts object keeps track of the id's, so there will never be two items with the same id in the same page. This is handled through the [Highcharts.idCounter](https://github.com/highcharts/highcharts/blob/v5.0.2/js/parts/Globals.js#L31), and definitions will have id's like `highcharts-0`, `highcharts-1` etc. 

This system breaks if someone exports a chart from different pages and pastes the SVG into the same page. To prevent this situation we would have to extend the simple counter with a random hash that is (likely) unique to the Highcharts object on the page. Then everywere we run `idCounter++` we should instead return a slightly more complicated id, like `highcharts-oiwjd-0`.

**Comment by TorsteinHonsi** [comment]
PS: No tests added, the auto-visual tests will reveal regressions.
