### ISSUE TITLE
Resizing stock chart after load unselects range selector buttons

### ISSUE THREAD

**Issue by khoomeister** [highcharts/highcharts#5930]
#### Expected behaviour

When the chart loads and you resize a stock chart, the range selector's selected button should maintain its selection.

#### Actual behaviour

The selected button is lost.

#### Live demo with steps to reproduce

https://jsfiddle.net/khoomeister/t5yahs6s/3/

You can also remove the setTimeout, refresh and try resizing the window manually and the same issue will occur.

#### Initial code read

This line is unselecting the button:

https://github.com/highcharts/highcharts/blob/4b015d5bfbc2d19a4d574832bd2775829aeca16a/js/parts/RangeSelector.js#L332

which is getting called by the afterSetExtremes event here:

https://github.com/highcharts/highcharts/blob/4b015d5bfbc2d19a4d574832bd2775829aeca16a/js/parts/RangeSelector.js#L309

This happens only when I resize the window after the initial chart load (and before manually setting extremes).

Hope this helps!

**Comment by jon-a-nygaard** [comment]
@khoomeister Thanks for reporting, we will try to fix this as soon as possible.

_Internal Note: [Additional demo](https://jsfiddle.net/jon_a_nygaard/t5yahs6s/4/)_
