### ISSUE TITLE
YTD doesn't disable when All is clicked on the stock chart range selector

### ISSUE THREAD

**Issue by khoomeister** [highcharts/highcharts#5931]
#### Expected behaviour
https://jsfiddle.net/khoomeister/03ccu53f/3/

If I select All, YTD should be disabled.

#### Actual behaviour

If I select All, YTD remains enabled.  Furthermore, if I then select YTD, All remains enabled.

On the other hand, refresh the page and if I select YTD, All becomes disabled like it should be.

#### Live demo with steps to reproduce
https://jsfiddle.net/khoomeister/03ccu53f/3/

**Comment by jon-a-nygaard** [comment]
@khoomeister Thanks for reporting, we will work on fixing this as soon as possible.
