### ISSUE TITLE
Tooltip padding for 2 rows calculated wrong

### ISSUE THREAD

**Issue by HACKHERS** [highcharts/highcharts#5932]
#### Expected behaviour
When using pointFormat for tooltips, if you set they font size other than you set in style option. Space between 2 rows needs to be enough. (Not expecting overflow)

#### Actual behaviour
But it totally messes up. For in your own examples for activity gauge when you set the fontsize 32 you can see the problem.

#### Live demo with steps to reproduce

http://jsfiddle.net/Hackhers/h8177x85/

#### Affected browser(s)
Google Chrome

**Comment by jon-a-nygaard** [comment]
Hi @HACKHERS thanks for reporting. This seems to be something that goes wrong with calculations of `em` values. It looks like it works fine using `px` values [like this](http://jsfiddle.net/jon_a_nygaard/h8177x85/2/), which may be a possible workaround for you.

_Internal Note:_ Look into SvgRenderer.fontMetrics. [Simplified demo](http://jsfiddle.net/jon_a_nygaard/h8177x85/4/)

**Comment by HACKHERS** [comment]
Hi @jon-a-nygaard thanks for clarification, after opening issue I tried that too. It looks like much more space between serie name and point y. The example is [over here](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/gauge-activity/). Is there anyway around this ?

**Comment by TorsteinHonsi** [comment]
Demo reduced to the renderer: http://jsfiddle.net/highcharts/rw86v1jb/
