### ISSUE TITLE
Highchart Tooltip still visible when chart container has visibility hidden.

### ISSUE THREAD

**Issue by rohitszone** [highcharts/highcharts#5933]
#### Snapshots of Problem
![image](https://cloud.githubusercontent.com/assets/1780659/20045808/686a16dc-a4f8-11e6-93b8-f4eb660d7604.png)
![image](https://cloud.githubusercontent.com/assets/1780659/20045871/961690c4-a4f8-11e6-8bce-86f8e92dcb5d.png)

#### Problem explanation and root cause
Highlighted first line and last line over chrome indicates two Tabs div, the first one indicates the Chart div while the second is application specific, when I toggle the tab from first to second the first line's visibility property changes from visible to hidden however the second tab still shows the child class highcharts-tooltip, highcharts-data-labels highcharts-series-1, highcharts-data-labels highcharts-series-2, highcharts-data-labels highcharts-series-3 with their css visibility property as visible though the parent tab css property is hidden hence the labels are visible on second tab.

#### Not a correct fix !!

I tried fixing it by  
.highcharts-container *{
  visibility: inherit !important;
}

this is not the right fix as I used stacked column bar chart the click on labels on right hand corner respective stack should get hidden, however if I use the above css visibility property is overriden and stack will still be visible.

Please suggest how can I get rid of these labels.

Cheers.
#### Affected browser(s)

Chrome/IE

**Comment by jon-a-nygaard** [comment]
Hi @rohitszone could you provide us with a demo of your code? it would help a great deal in replicating the issue.

**Comment by rohitszone** [comment]
Hi Jon, It's hard for me to give you a demo as my employer/bank restricts me to share code over public forum.

Is my problem explanation clear to you ?

**Comment by jon-a-nygaard** [comment]
@rohitszone I set up demo which looks like it replicates your issue, I used Bootstrap and jQuery to create the tabs logic.
[Here's the demo](https://jsfiddle.net/jon_a_nygaard/pdc1n61e/)

Is it perhaps possible for you to use `display: block/none` in stead of `visibility: visible/hidden`. If so you would be able to avoid this issue. [Demo](https://jsfiddle.net/jon_a_nygaard/u3q7v481/)

**Comment by rohitszone** [comment]
Thank you, let me give it a try I'm using react-bootstrap Tabs, need to figure out how I can change it without impacting much of components.

I'll take sometime but will post a reply if it works.

Cheers.

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard If that is the case, it may be simple to solve it by passing the `inherit` parameter to the show function [here](https://github.com/highcharts/highcharts/blob/v5.0.2/js/parts/Tooltip.js#L461). It makes sure that the `visibility` is set to `inherit` rather than `visible`. The problem with `visible` is that it will stay visible even when the parent is hidden.

```js
			// show it
			if (tooltip.isHidden) {
				stop(label);
				label.attr({
					opacity: 1
				}).show(true); // <= pass true here
			}
```

**Comment by rohitszone** [comment]
I've fixed it using display css property.

Thanks.
