### ISSUE TITLE
Missing trailing space in legend class name

### ISSUE THREAD

**Issue by martijnpieters** [highcharts/highcharts#5934]
#### Expected behaviour
Legend should contain series' className with a trailing space.

#### Actual behaviour
The trailing space in legend class is missing. With `"className": "missing-space"` this results into the class `missing-spacehighcharts-series-0` for a legend item.

#### Live demo with steps to reproduce
http://jsfiddle.net/ue5gyq0a/

#### Affected browser(s)
All

**Comment by jon-a-nygaard** [comment]
@martijnpieters Thanks for reporting, this issue will be fixed in the next maintenance release v5.0.3. A possible workaround in the meantime is to [add your own trailing space to className](http://jsfiddle.net/jon_a_nygaard/ue5gyq0a/1/).

**Comment by martijnpieters** [comment]
I was already using that workaround, however, thanks for the suggestion!
