### ISSUE TITLE
Regression: DST with time span under a day - wrong ticks

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5935]
#### Expected behaviour
As in 5.0.0 - http://jsfiddle.net/fyk90reh/1/

#### Actual behaviour
No visible ticks (since 5.0.1) - http://jsfiddle.net/fyk90reh/2/

#### Live demo with steps to reproduce
Another demo:
5.0.0 - http://jsfiddle.net/du1gjnhk/2/
vs
current - http://jsfiddle.net/du1gjnhk/4/

**Comment by TorsteinHonsi** [comment]
Fails since 2d27725

**Comment by nbjohan** [comment]
Unfortunatly, I still have some trouble with DST in 5.0.1
At the dst switching point, a double day occurs on the x-axis. The tooltip is still functioning proplery.
However, I cannot reproduce this using a jsfiddle, so I dont know what is wrong.
http://jsfiddle.net/nbjohan/pqaaor30/3/

I don't understand what this issue changes or fixes, but do you think it could be related?
Can the browser locale settings influence the x-axis labels?


Expected result:
![dst_5 0 0](https://cloud.githubusercontent.com/assets/17319375/20829248/98ac2eac-b87b-11e6-80a9-ba2529ed7b86.png)

Actual result: 
![dst_5 0 5](https://cloud.githubusercontent.com/assets/17319375/20829256/a197f64a-b87b-11e6-9b66-235f3d78b195.png)
![5 0 1](https://cloud.githubusercontent.com/assets/17319375/20829266/a5773d70-b87b-11e6-80fb-3ea1c459f540.png)

**Comment by TorsteinHonsi** [comment]
Hi, I suppose this can occur when the lables are placed with exactly 24 hours between them, but the labels are formatted with local time. So that the data is not in sync with how the labels are formatted. But I can't tell exactly without seeing the chart live.
