### ISSUE TITLE
Heatmap in highcharts-dist is different than the module on code.highcharts.com

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5937]
#### Expected behaviour
Identical files - since version is the same.

#### Actual behaviour
There are some differences.

Maybe other files have some differences too? I have just the info about the heatmap plugin.

#### Live demo with steps to reproduce
https://github.com/highcharts/highcharts-dist/blob/master/js/modules/heatmap.src.js
vs
http://code.highcharts.com/modules/heatmap.src.js

**Comment by michaeljho** [comment]
Hello, wondering if there is an ETA for a fix? We are relying on highcharts-dist in our build process, so need to know if we need to manually add source files to our build temporarily.

**Comment by TorsteinHonsi** [comment]
You are comparing the [styled mode](http://www.highcharts.com/docs/chart-design-and-style/style-by-css) file with the classic mode file. Styled mode files are hosted in /js and /css directories.

*Styled mode:*
https://github.com/highcharts/highcharts-dist/blob/master/modules/heatmap.src.js corresponds to http://code.highcharts.com/modules/heatmap.src.js

*Non-styled mode:*
https://github.com/highcharts/highcharts-dist/blob/master/js/modules/heatmap.src.js corresponds to http://code.highcharts.com/js/modules/heatmap.src.js

**Comment by michaeljho** [comment]
I see, thank you for the info! I didn't realize there was styled mode now :)

**Comment by TorsteinHonsi** [comment]
No problem! See http://www.highcharts.com/news/236-highcharts-5-0
