### ISSUE TITLE
Using default value on yAxis label distance - align not working

### ISSUE THREAD

**Issue by HACKHERS** [highcharts/highcharts#5939]
#### Expected behaviour
If I set the value to default value I expect nothing change.

#### Actual behaviour
When I set the value to its default It makes chart "broken". In this example giving yAxis.Label.Distanceto 15(default) Labels are moving in wrong direction.  When I set the align of yAxis label to right (default) it moves when it shouldn't.

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/gauge-speedometer/
Set the yAxis Label Distance to 15. It should be like this:
http://jsfiddle.net/Hackhers/agun6Lwo/
Go to original demo again and set the yAxis Label Align to Left. It should be like this:
http://jsfiddle.net/Hackhers/agun6Lwo/2/

#### Affected browser(s)
Google Chrome

**Comment by jon-a-nygaard** [comment]
There seems to be two issues in this case.

The default behaviour for `yAxis.labels.align` appears to not match the [default set in the API](http://api.highcharts.com/highcharts/yAxis.labels.align)
When the series type is gauge the default alignment act as  `center` not `right` as stated in the API

When setting `yAxis.labels.align` to `left` it actually aligns to the right, and vice versa when setting align to `right`.

[Simplified demo](http://jsfiddle.net/jon_a_nygaard/dffvwjz7/)

@TorsteinHonsi Before I look deeper into this I would just like to confirm that:
1. is it correct that the default behaviour is `center` or should it be `right` when `series.type: gauge`? 
2. also I guess that the labels should align to the same side as set, not the opposite?

**Comment by HACKHERS** [comment]
@jon-a-nygaard 

yAxis.label.distance is not matching with [default set in API](http://api.highcharts.com/highcharts/yAxis.labels.distance) too.

**Comment by TorsteinHonsi** [comment]
> 1. is it correct that the default behaviour is center or should it be right when series.type: gauge? 

I think it's not center either. See https://github.com/highcharts/highcharts/blob/v5.0.2/js/parts-more/RadialAxis.js#L80-L85. And then there's [this line](https://github.com/highcharts/highcharts/blob/v5.0.2/js/parts-more/RadialAxis.js#L521) where the default distance is again picked to -25.

> 2. also I guess that the labels should align to the same side as set, not the opposite?

If you left-align a text to a point (x, y), the left side of the text will touch the point, so the text is actually to the right of the point.

**Comment by jon-a-nygaard** [comment]
>If you left-align a text to a point (x, y), the left side of the text will touch the point, so the text is actually to the right of the point.

@TorsteinHonsi Thanks for clarifying this.


I have now updated the API accordingly:
1. [yAxis.labels.distance](http://api.highcharts.com/highcharts/yAxis.labels.distance) defaults to -25.
2. [yAxis.labels.align](http://api.highcharts.com/highcharts/yAxis.labels.align) mentions defaults for angular and solid gauges.

A big thank you to @HACKHERS for pointing out these mistakes in our API.
