### ISSUE TITLE
xAxis category labels overlap

### ISSUE THREAD

**Issue by bala-drg** [highcharts/highcharts#5941]
#### Expected behaviour
xAxis category labels should not be overlapped

#### Actual behaviour
xAxis category labels getting overlapped

#### Live demo with steps to reproduce

http://jsfiddle.net/cjj67460/1/

**Comment by pawelfus** [comment]
Hi @bala-drg 

Thank you for reporting. However, I am not sure if this is a bug, you set `textOverflow: 'none'` which prevents from using ellipsis. When commented out that option, it works fine: http://jsfiddle.net/cjj67460/2/

**Comment by bala-drg** [comment]
Hi @pawelfus 

Thank you for your response. i need to show full text without ellipsis and at the same time it should not overlap label values

**Comment by KacperMadej** [comment]
**Workaround**: set `marginLeft` to allow more space for categories than for series plot - http://jsfiddle.net/BlackLabel/cjj67460/8/
