### ISSUE TITLE
Resize highcharts using react-grid-layout not working

### ISSUE THREAD

**Issue by ns04stars** [highcharts/highcharts#5942]
I am working in react and using highcharts with react-grid-layout to resize the elements in div. Somehow resizable feature is working for images but not with highchart. Grid.js is a file that makes ResponsiveReactGridLayout and it gets the highchart from chart.js file. Please find both files code below.

```
//Grid.js
import React, { Component } from 'react';
import {Responsive, WidthProvider} from 'react-grid-layout';
import Charts from './charts.js';

const ResponsiveReactGridLayout = WidthProvider(Responsive);

class Grid extends Component {

    render(){
        return (<div style={{borderStyle: 'groove'}}>
                <h2> Panel Header </h2>
                <ResponsiveReactGridLayout className="layout"
                                           breakpoints={{lg: 1200, md: 96, sm: 768}}
                                           cols={{lg: 5, md: 10, sm: 6}}>

                    <div key="c" data-grid={{x: 0, y: 0, w: 1, h: 3}} style={{ border:'1px solid green', borderStyle: 'groove'}}>
                        <img src="https://cdn.geckoandfly.com/wp-content/uploads/2013/03/530-smiley-face.jpg" style={{width:'inherit', height:'inherit'}} />
                    </div>
                    <div key="d" className = 'react-grid-item react-resizable'
                         data-grid={{x: 1, y: 0, w: 1, h: 3}} style={{ border:'1px solid green', borderStyle: 'groove'}}
                        >
                        <Charts style={{width:'inherit'}} id={'Chart 1'}/>
                    </div>
                    <div key="e" data-grid={{x: 2, y: 0, w: 1, h: 3}} style={{ border:'1px solid green',borderStyle: 'groove'}}>
                        <Charts style={{width:'inherit'}} id={'Chart 2'}/>
                    </div>
                    <div key="f" data-grid={{x: 3, y: 0, w: 1, h: 3}} style={{ border:'1px solid green',borderStyle: 'groove'}}>
                        <Charts style={{width:'inherit'}} id={'Chart 3'}/>
                    </div>
                </ResponsiveReactGridLayout>
            </div>
        )
    }
}
export default (Grid);


//Charts.js
import React, { Component } from 'react';
const Highcharts = require('highcharts');
class Charts extends Component{
    constructor(props){
        super(props);
        this.state = {
                data : {
                xAxis: {
                    categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
                },
                series: [{
                    data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 295.6, 454.4]
                }]
            },
            pieData: [{name: "Firefox",y: 6},{name: "MSIE",y: 4},{name: "Safari",y: 4},{name: "Opera",y: 1},{name: "Chrome",y: 7}]
        };
    }

    /**
     * Inject highcharts markup into the DOM after the rest of the component has mounted
     * @return {None}
     */
    componentDidMount() {
        // Load in any highcharts modules
        if (this.props.modules) {
            this.props.module.forEach((module) => {
                module(Highcharts);
            });
        }

        // Create the actual chart and assign reference
        const props = this.processPropsModel(this.props);
        const containerRef = `container${props.id}`;
        this.chart = new Highcharts.chart(
            containerRef,
            props.options
        );
    }

    processPropsModel(props) {
        const newProps = {};
        newProps.id = this.props.id;
        newProps.options = this.generateDefaultOptions();
        return newProps;
    }

    /**
     * Generating some default chart options for placeholding purposes
     * @return {Object}       The options to be passed into the chart
     */
    generateDefaultOptions() {
        return {

            title: {
                text: this.props.id,
                x: -20 //center
            },
            xAxis: {
                categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
            },
            yAxis: {
                title: {
                    text: null
                }
            },
            tooltip: {
                valueSuffix: '°C'
            },
            series: [{
                name: 'Tokyo',
                data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
            }]
        };
    }

    render(){
        const props = this.processPropsModel(this.props);
        return (
            <div id={`container${props.id}`}>
            </div>
        );
    }
}
export default Charts;
```

**Comment by pawelfus** [comment]
Hi @ns04stars

My apologies for a late reply. I don't see [`chart.setSize(width, height)`](http://api.highcharts.com/highstock/Chart.setSize) or [`chart.reflow()`](http://api.highcharts.com/highstock/Chart.reflow) in your code. It should be called to update chart size when container is resized. By default Highcharts adds event on `window.resize`, but there is no `div.resize` event, so you need to call it on your own. Like in [this demo](http://jsfiddle.net/gh/get/jquery/2/highcharts/highcharts/tree/master/samples/stock/members/chart-setsize/).

**Comment by sivasai081** [comment]
onLayoutChange(layout, width) {
       console.log(layout);
      chart.setSize(width, height, false);

**Comment by sivasai081** [comment]
hi @pawelfus 
 I am using the same component in react like below
`_loadSavedChart(){
       return (
          <ResponsiveReactGridLayout layouts={this.state.layout} 
            onLayoutChange={this.onLayoutChange}
            className={this.state.className}            
            rowHeight={this.state.rowHeight}
            cols={this.state.cols}
            initialLayout= {this.state.layout}
            initialWidth={this.state.initialWidth}
            width={this.state.width}
            verticalCompact={false}
            listenToWindowResize={false}
            currentBreakpoint= 'sm'
            >
          {this.state.savedChartinDashboard.map((data, i) => 
          <Paper key={i} className="c3chart" style={style.chartPaperStyle} zDepth={1}>{this._renderChart(data)}
         
           <ul className=" list-unstyled">

              <li className="dropdown" style={{position: 'absolute', top:1, right:8}}>
                  <a className="dropdown-toggle" data-toggle="dropdown" data-target="#" style={{color: 'black'}}>
                    <i className="fa fa-ellipsis-v" style={{width: '30px', height: '30px', borderRadius: '50%', textAlign: 'center', lineHeight: '30px', color: '#999', cursor: 'pointer', backgroundColor: '#eee'}}></i>
                  </a>
                  <ul className="dropdown-menu dropdown-menu-right">
                    <li><a href="javascript:void(0)"><i className="fa fa-share-alt"></i> &nbsp; share</a></li>
                    <li><a onClick={this._removeChart.bind(this, data.chartId)}><i className=" fa fa-trash"></i> &nbsp; remove</a></li>
                   
                  </ul>
              </li>
            </ul>
          
          </Paper>
          )} 
        </ResponsiveReactGridLayout> )
      }`

` generateLayout(chartCount) {
        var layout = [], y, i;
        for (i = 0; i <= chartCount - 1; i++) {
          y = Math.ceil(Math.random() * 4) + 1;
          layout[i] = {x: i * 2 % 12, y: Math.floor(i / 6) * y, w: 2, h: 13, i: i.toString()};
        }
       return {lg:layout};
    }

    

      onLayoutChange(layout, width) {
       console.log(layout);
       
       chart.setSize(width);
     }`

I am using c3 and highcharts in the conatiner which are draggable and resizable how to make use of chart.setSize method

**Comment by pawelfus** [comment]
Hi @sivasai081 

If your code doesn't work, please contact with our support team ((details)[https://www.highcharts.com/support]).

**Comment by ranafaraznaru** [comment]
guys it would be better if you add live example of highcharts  with react-grid-layout in  react functional component. i am also stuck a issue like this . after reflow method my charts width is working fine while resizing but height is not responsive.

**Comment by pawellysy** [comment]
Hi @ranafaraznaru, Could you please reach out to us via our support channels, where our support engineers will be more than happy to help you with your chart configuration! https://www.highcharts.com/blog/support/

**Comment by ranafaraznaru** [comment]
https://codesandbox.io/s/customizable-react-dashboard-with-charts-forked-bxd7gl?file=/src/DemoChart.js:1074-1083

**Comment by ranafaraznaru** [comment]
can u please check it here.

**Comment by pawellysy** [comment]
@ranafaraznaru as I've written above, could you reach out to us via our support channels?
We treat GitHub as a bug/feature tracking tool and deal with these kinds of questions on other support channels.
Thanks for your understanding!
