### ISSUE TITLE
Wrong working by 'endOnTick'

### ISSUE THREAD

**Issue by stepanO** [highcharts/highcharts#5946]
I have a problem, I want to show last label, but showed index of last label.

#### Expected behaviour
Visible last label as 'End'

#### Actual behaviour
Visible last label as '4'

#### Live demo with steps to reproduce
 Example: http://jsfiddle.net/o7yxh1ss/2/

#### Affected browser(s)
Chrome 54.0.2840.71 m

**Comment by TorsteinHonsi** [comment]
This is what I see, which is what I expect:

![skjermbilde 2016-11-09 kl 10 31 05](https://cloud.githubusercontent.com/assets/227836/20133395/aa91515e-a667-11e6-8f6e-ec1d75a9b362.png)

Is there anything more we neet to know to reproduce it? What browser and version are you using?

**Comment by stepanO** [comment]
I'm see another 

![2016-11-09 16_01_16-edit fiddle - jsfiddle](https://cloud.githubusercontent.com/assets/7386436/20139214/0fc37844-a696-11e6-87fa-9a0677d3138b.png)

**Comment by TorsteinHonsi** [comment]
> Is there anything more we neet to know to reproduce it? What browser and version are you using?

**Comment by stepanO** [comment]
It reproduced in:
- Chrome 54.0.2840.71 m, 
- Firefox 43.0.1, 45.0.1
- IE: 11

**Comment by TorsteinHonsi** [comment]
Confirmed!

On Chrome/Mac, it takes a little bit less height: http://jsfiddle.net/highcharts/o7yxh1ss/3/
