### ISSUE TITLE
Funnel and broke-axis compatibility

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#5950]
#### Actual behaviour
We get an error in js console when loading "broken-axis" before "funnel". Changing order resolves the issue, but this is a slippery slope. We either need to resolve order of wrap() methods or write a guide with correct order for modules. Guide may not be enough, I can imagine issue like: module A before B, module C before A, but (!) module module B before module C. 

#### Live demo with steps to reproduce

- http://jsfiddle.net/dko6016u/
- http://jsfiddle.net/dko6016u/1/ (fine)

**Comment by TorsteinHonsi** [comment]
Do you know what specific `wrap` call causes it? In some cases it may be better to refactor it or add event handlers.

**Comment by pawelfus** [comment]
This wrap: `wrap(H.seriesTypes.column.prototype, 'drawPoints', drawPointsWrapped);` but after debugging, it's caused by using column drawPoints method in funnel: `drawPoints: seriesTypes.column.prototype.drawPoints,`. 

`broken-axis` module assumes that column series has axes (which is correct), but `funnel` series doesn't have them, it only reuses column's prototype method. 

PS: I don't have a real use-case for it, issue arrived when testing Highcharts-editor.

**Comment by TorsteinHonsi** [comment]
Okay. Probably the broken-axis plugin should actually check for axis...

**Comment by magnushavgry** [comment]
I do see the reference to #6004 but are you guys aware that this bug breaks the funnel chart simply by using Highstock.js? It's effectively preventing us from upgrading to v5.

**Comment by pawelfus** [comment]
You are right, it used to work in 4.x versions: http://jsfiddle.net/dko6016u/4/

**Comment by magnushavgry** [comment]
Any news on this? It seems rather odd that this issue is not being addressed at all.

**Comment by pawelfus** [comment]
*Internal note:*
After all we need to check this. We can go back to 4.x solution, where `drawPoints` was not inherited from column series as an alternative, but the above makes more sense.
