### ISSUE TITLE
Highstock: documentation typos/errors

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5953]
1.
Problem: `name: """"`
Where: http://api.highcharts.com/highstock/series%3Cflags%3E.name (and other series types)

2.
Problem: *Defaults to [null]. Defaults to [null].*
Where: http://api.highcharts.com/highstock/chart.margin

3.
Problem: Additional "s in many options in lang.
Where: http://api.highcharts.com/highstock/lang

4.
Problem: Left menu - `undefined`, but description - "Defaults to an empty string."
Where: http://api.highcharts.com/highstock/lang.invalidDate

5.
Problem: No default value. Should has the same as in HC API: *Defaults to [ "Jan" , "Feb" , "Mar" , "Apr" , "May" , "Jun" , "Jul" , "Aug" , "Sep" , "Oct" , "Nov" , "Dec"]*
Where: http://api.highcharts.com/highstock/lang.shortMonths

6.
Problem: *Defaults to .* looks like something is missing.  "Defaults to an empty string." is better.
Where: http://api.highcharts.com/highstock/lang.thousandsSep
The same problem in HC: http://api.highcharts.com/highcharts/lang.thousandsSep

7.
Problem: No default value. Shouldn't be the same as other events?
Where: http://api.highcharts.com/highstock/chart.events.afterPrint

8.
Problem: Duplicated " - `html: """"`.
Where: http://api.highcharts.com/highstock/labels.items.html
Also: *Defaults to "".* is also better than *Defaults to .*, but maybe "Defaults to an empty string." is even better?

9.
Problem: Extra " - `layout: ""horizontal"`
Where: http://api.highcharts.com/highstock/legend.layout

10.
Problem: Extra "s - `""center""` and `""top""`.
Where: 
http://api.highcharts.com/highstock/xAxis.plotBands.label.align
http://api.highcharts.com/highstock/xAxis.plotBands.label.verticalAlign

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! Fixed all but these:

> Problem: Left menu - undefined, but description - "Defaults to an empty string."

Unfortunately our API currently doesn't distinguish well between `null`, `undefined` and `""`.

> Problem: Defaults to . looks like something is missing. "Defaults to an empty string." is better.

The default thousands separator is a single space. I've made that clearer in the description.
