### ISSUE TITLE
Blinking zoom selector while scrolling a chart with a disabled navigator

### ISSUE THREAD

**Issue by educasal** [highcharts/highcharts#5957]
This only happens  with charts with a disabled navigator 

#### Expected behaviour
Once a zoom selector has been pressed, it should remain selected while we use the scroll bar.  

#### Actual behaviour
The zoom selector starts blinking, switching rapidly between the bold and regular fonts.   

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/navigator-disabled/

### Steps to reproduce it
1. Click on a zoom selector, for example **3m**
2. Use the horizontal scroll bar 
3. The selected zoom selector will start blinking as you move along the chart. 
 

#### Affected browser(s)
Chrome 54.0.2840.90 (64-bit)
Firefox 49.0.2

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard You can take this into account while refactoring `updateButtonStates`.

**Comment by jon-a-nygaard** [comment]
Yes, that I will do.
Related to #5931

**Comment by jon-a-nygaard** [comment]
Fixed as of 5.0.3
