### ISSUE TITLE
Stacked columns change width when showing or hiding series

### ISSUE THREAD

**Issue by mattmacleod** [highcharts/highcharts#5959]
#### Expected behaviour

Showing or hiding series in a stacked column stock chart does not cause the width of the columns to drastically change.

#### Actual behaviour

A stacked column stock chart containing a hidden series displays extremely thin bars, ignoring ay configuration options.

#### Live demo with steps to reproduce
http://jsfiddle.net/z924q2jg/ (toggle a series to see this effect).

#### Affected browser(s)

All.

**Comment by mattmacleod** [comment]
Just to provide a bit more context on this – this appears to be a regression introduced in 4.2.7, related to changes to data grouping, though I'm not sure exactly where.

The `closestPointRange` of the axis is derived from the `closestPointRange` of all series (https://github.com/highcharts/highcharts/blob/01a4a2751e66798c18c887907e21d43b1981300b/js/parts/Axis.js#L865), even those which are not visible.

However, data grouping is skipped when a series is not visible (https://github.com/highcharts/highcharts/blob/95e39871cc0a791519568ed19a786ad976047529/js/parts/DataGrouping.js#L314).

This causes the axis' `closestPointRange` to take the value of the lowest distance in any invisible series; in cases like the attached, this causes data grouping to be essentially disabled.

I'd be happy to raise a PR to fix this, but I'm not sure if it's more appropriate to remove the conditional `!visible` in `dataGrouping.js` or explicitly skip invisible series in `Axis.js`. Or if there's another, entirely better solution!

**Comment by TorsteinHonsi** [comment]
Yes, we should filter out hidden series in the getClosest function, but also take `ignoreHiddenSeries` into acccount. See https://github.com/highcharts/highcharts/blob/01a4a2751e66798c18c887907e21d43b1981300b/js/parts/Axis.js#L504 for a typical test.
