### ISSUE TITLE
Incorrect series order in legend after removing old series and adding new ones.

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#5960]
I tracked this down to series.init (series._i = chartSeries.length - 1;) which sets the series sorting index to the length of the series, however this doesn't account for other series which already had a sorting index set above the chartSeries.length.

I also noted while trying to come up with a workaround that series.update() overrides series.options.index with series.index if no new index is provided in the update which seems weird and wrong.

#### Expected behaviour
Adding a new series should always add it as the last series unless an index is specified.

#### Actual behaviour
Adding a new series works as expected until existing series are deleted to create gaps/holes in the saved sort indices.

#### Live demo with steps to reproduce
http://jsfiddle.net/a9pnwwjp/2/

1) Remove 3 series with the remove button. 
2) Add new series with the add button and note that the first 2 series added go between series 1 and series 5, then the rest are added after series 5.

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Regarding your comment on `series.update()`, perhaps we are missing a check for existing `index` option:

```js
		// Do the merge, with some forced options
		newOptions = merge(oldOptions, {
			animation: false,
			index: pick(oldOptions.index, this.index), // <= changed here
			pointStart: this.xData[0] // when updating after addPoint
		}, { data: this.options.data }, newOptions);
```
