### ISSUE TITLE
Spline updating each second fails to render correctly when more than 1 series

### ISSUE THREAD

**Issue by iisfaq** [highcharts/highcharts#5964]
I have taken the example demo from Highcharts.com and only added an additional series so instead of a single series there is now 2 series.

#### Expected behaviour

Should behave the same as having a single series 

#### Actual behaviour

When the series point is added to the 2nd series the chart is redrawn with a large line from the first X axis point at the Y Axis location to the top of the chart and to the right the same Y Axis distance.

Errors are shown in the javascript console
![image](https://cloud.githubusercontent.com/assets/5828178/20231092/461b3550-a8c4-11e6-8ec7-6054b67a2cff.png)

highcharts.js:54 Error: <path> attribute d: Expected number, "…2.0490147302671 C 4.754902200372…".dSetter @ highcharts.js:54
highcharts.js:54 Error: <path> attribute d: Expected number, "….98925863567797 C 4.754901721171…".dSetter @ highcharts.js:54
3007console messages are not shown.
6highcharts.js:54 Error: <path> attribute d: Expected number, "….98925863567797 C 4.754901721171…".

If you have 3 series only 1 of the series shows this behavior but the scrolling is not smooth.

#### Live demo with steps to reproduce

http://jsfiddle.net/doyxgyyz/

#### Affected browser(s)

Chrome, IE

**Comment by iisfaq** [comment]
![spline](https://cloud.githubusercontent.com/assets/5828178/20231169/c96404e6-a8c4-11e6-9bd7-94eeba050904.gif)

Gif showing the issue

**Comment by TorsteinHonsi** [comment]
It's because the whole chart redraws following each call to `addPoint`, so the first animation is interrupted by a redraw. This is prevented by running `addPoint` with the redraw parameter set to false, then run `chart.redraw()` after: http://jsfiddle.net/doyxgyyz/1/.

**Comment by iisfaq** [comment]
Thanks for that I appreciate your time responding to me.
