### ISSUE TITLE
Flashing occurs on tapping legends several times

### ISSUE THREAD

**Issue by neswine** [highcharts/highcharts#5966]
#### Expected behaviour
Flashing should not occur while toggling plot point several times.

#### Actual behaviour
Flash occurs when toggling plot points fast

We are rendering highcharts in a mobile webView and we are using custom images to show plot points using highchart option. While toggling the plots fast several times, a rectangle area is shown over the chart. We have attached an gif showing this problem while flashing occurs. You can see a blue background showing up in chart. Please let us know how to resolve this issue.

#### Attachment
![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/9277989/20255429/6e0a513c-aa62-11e6-9281-f877bb739759.gif)

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Are you able to reproduce this in a live environment like jsFiddle.net?

I tried in on http://jsfiddle.net/highcharts/2bs63w4r/show/, but I can't see the flashing rectange. Tapped one of the series names quickly in succession.

**Comment by neswine** [comment]
The issue is reproducible when we render it directly in a android or iOS webView instead of rendering it in a iframe or jsFiddle. The frequency of occurrence is 1 in **10-15** taps while toggling the plots.
