### ISSUE TITLE
Chart markers doesn't display until changing the chart width

### ISSUE THREAD

**Issue by royigoldi** [highcharts/highcharts#5967]
expected: marker displayed

actual: marker doesn't appear until i increase the chart width

example:
```js
var points = 780;

var mockData = function(pointsCount){
    var data = [],
        middle = Math.round(pointsCount/2),
        initDate = 1147651200000
    ;
    for(var i=0; i<pointsCount; i++){
        var date = initDate + i*80000000;
        if(i==middle)
            data.push({
                x: date,
                y: 0,
                marker: {
                    enabled: true,
                    radius:8,
                    fillColor: 'red',
                    lineWidth:3,
                    lineColor: 'white',
                    states: {
                        hover: {
                            enabled: true,
                            radius:8,
                            fillColor: 'white',
                            lineWidth:3,
                            lineColor: 'red'
                        }
                    }
                }
            });
        data.push([date, i]);
    }
    return data;
}

        data.push([date, i]);
    }
    return data;
}

$(function() {
    
		// Create the chart
		$('#container').highcharts('StockChart', {

			title : {
				text : 'AAPL Stock Price'
			},
			
			series : [{
				name : 'AAPL',
		data : mockData(points),
				tooltip: {
					valueDecimals: 2
				}
			}]
		});
});
```

**Comment by royigoldi** [comment]
1)chart before zoom

![image](https://cloud.githubusercontent.com/assets/20413250/20256748/21929346-aa4e-11e6-9a35-ce4eaaebf403.png)
2) zoom in:
![image](https://cloud.githubusercontent.com/assets/20413250/20256779/4c4991f2-aa4e-11e6-9084-c652b1e833e1.png)
3) Reset zoom:
![image](https://cloud.githubusercontent.com/assets/20413250/20256808/684f7b82-aa4e-11e6-9b8e-946a8ee96227.png)

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

Your screenshots don't quite match your demo code, here's what I've got: http://jsfiddle.net/highcharts/zmgncuxh/

Can you update the jsFiddle and provide steps to demonstrate your issue?

**Comment by jon-a-nygaard** [comment]
Internal Note: 
[Simplified demo](http://jsfiddle.net/jon_a_nygaard/zmgncuxh/3/)
When all data is visible the `series.hasGroupedData` is true and then the point options will not be sent to `point.init`, however when the viewing a smaller set of data then the series.hasGroupedData switches to false, causing the marker to show.
It happens at [Series.js#L769-L780](https://github.com/highcharts/highcharts/blob/master/js/parts/Series.js#L769-L780)

**Comment by jon-a-nygaard** [comment]
Had a thought that we could convert the data array to an option object, and then extend it with the data options, before calling point.init. Something like this:
```javascript
pointOptions = PointClass.prototype.optionsToObject.call({ series: series }, [processedXData[i]].concat(splat(processedYData[i])));
extend(pointOptions, dataOptions[cursor]);
point = (new PointClass()).init(series, pointOptions);
point.dataGroup = series.groupMap[i];
```

But I got some strange behaviour when trying this out.

**Comment by jon-a-nygaard** [comment]
Hi @royigoldi 
I have just learned that this is in fact not a bug, and the reason why is because of data grouping. Before you zoom in then the data is grouped and only displaying one point for each group. Therefore the point with the red marker is actually not displayed at all.

I made examples for two options which avoids your problem:
[Disable data grouping](http://jsfiddle.net/jon_a_nygaard/tk6s1eu7/)
[Add a scatter point to display a marker](http://jsfiddle.net/jon_a_nygaard/f4jbwjsL/)

**Comment by royigoldi** [comment]
Hi jon-a-nygaard,

but i doesn't work with highstock, only highcharts...
data grouping is not part of it...

Thanks,
Royi

**Comment by jon-a-nygaard** [comment]
@royigoldi Could you replicate the issue using [JSFiddle](https://jsfiddle.net/). Then it will be easier for us to know exactly what is going wrong.

**Comment by royigoldi** [comment]
I was work with version 4.2.5. 
in 5.0.2 it doesn't happen.... 
Thanks

**Comment by jon-a-nygaard** [comment]
Glad to hear you solved it.
