### ISSUE TITLE
Problems with zooming on mobile devices using dynamic-master-detail example.

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#5969]
#### Expected behaviour

After zooming in on mobile device chart should zoom in and master chart should still be visible.

#### Actual behaviour
After zooming in chart zooms in but master chart disappears.

Before zooming:
![image1](https://cloud.githubusercontent.com/assets/19593179/20263152/adfe450c-aa65-11e6-9906-8f2df96863b5.PNG)

After zooming:
![image2](https://cloud.githubusercontent.com/assets/19593179/20263170/c16f617a-aa65-11e6-8c2c-a3562cb92e2e.PNG)

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/dynamic-master-detail/

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

_Internal note_:
The master chart (bottom) reponds to touch pinching, and re-scales the chart while doing so. It seems like returning false from the `selection` event is not sufficient to stop this.
