### ISSUE TITLE
Bubble chart shadows (and tooltips) gets stuck per series

### ISSUE THREAD

**Issue by Groovyle** [highcharts/highcharts#5970]
#### Expected behaviour
When having 2 or more series in the bubble chart, the shadows and tooltips should be working fine.

#### Actual behaviour
Shadows and tooltips gets stuck on an item. This happens separately between items in different series.

#### Live demo with steps to reproduce
I can reproduce it easily on the demo site:
[highcharts.com/demo/bubble-3d/](url)

Steps to reproduce:
1. Hover two items which have different colors. For example the two items (black and blue) on center top. You'd notice that the shadows stays on the bubble. Pic on the items:
![screenshot00242](https://cloud.githubusercontent.com/assets/10544685/20263689/7a4f082e-aa9a-11e6-80ff-e1103dca7f56.png)
2. If you hover on other item(s), then the shadow would move as expected, but only for that color (or series). This seems to imply that the mouseout event (or related events) triggers for each series separately. After you hover both of them, going back and forth between both items won't show/trigger the tooltip. I can guess that this happens because the state of the items are active, and so mouseenter (or related events) are not triggered.
3. Clicking on the legend of a series to hide it, for example Series 1, would hide bubbles for Series 1 (expected), but not the shadow (unexpected). Hence the title "stuck". Showing it again kinda solves it, since everything returns to their original positions. I can guess that the shadows did not get updated.

#### Affected browser(s)

* Google Chrome 54.0.2840.71 m
* Mozilla Firefox 47.0.2

My guess is that this issue is not browser-related, but rather the invocation of events. I hope that I did not miss something important. Or is this the intended behavior (which I don't believe is so)?
Cheers! Thanks for the great library!

#### The following issue might be related:
#5677 about bubble shadows.

**Comment by oysteinmoseng** [comment]
Thank you for reporting and for the thorough details, we will look into this.

**Comment by mjankovskis** [comment]
I have encounterred with the same bug, I hope that this will be fixed soon. Looks like hover out state are removing hover state from series, if hovering on other series. 
Thanks for fast response.

**Comment by pawelfus** [comment]
Works fine on the master branch: http://jsfiddle.net/77keowny/1/ - so it should be part of 5.0.3 release.

**Comment by Groovyle** [comment]
@pawelfus You're right, thanks! That jsfiddle also works fine for me.
So I guess this issue could be closed, then? We just have to wait for the official release of 5.0.3; can't really say anything, in the source file (probably dev) it is stated that the date is today.

#### Thumbs up for the quick responses, guys.

**Comment by pawelfus** [comment]
Thanks!

Master files have the last build date ;) So that means the sources were compiled today, it's not about the release date. 

Most probably within two weeks version 5.0.3 should be out.
