### ISSUE TITLE
Setting minorTickInterval = 'auto' with `setOptions` crashes the browser

### ISSUE THREAD

**Issue by sp4m** [highcharts/highcharts#5971]
#### Expected behaviour
A working chart regardless of how the `minorTickInterval` is set.

#### Actual behaviour
Either the browser crashes (Chrome) or an incomplete chart is displayed:
![image](https://cloud.githubusercontent.com/assets/3898396/20260013/098d6da2-aa58-11e6-85e7-a8e71462da66.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/m6oa5z9d/ - There are a couple of things going on here:

- `minorTickInterval` has to be set with the `setOptions` method. The error doesn't occur if the property is set as part of the chart object.
- The data points have to be very close to each other. The error doesn't occur if the second data point's `y` value is changed from 23 to 22.
- The number of decimal places definitely plays a role as well. The error doesn't occur if the first data point's `y` value is changed from 22.999999999999996 to 22.99999999999999 (last decimal place removed).

I'm aware this is an edge case that's easy to work around but I still believe something's not how it should be hence the bug report.

#### Affected browser(s)
All major browsers (but with varying results).

**Comment by TorsteinHonsi** [comment]
Thanks for writing! And you're right, all edge cases should at least be handled gracefully.

**Comment by TorsteinHonsi** [comment]
Okay, one step closer: By setting the minorTickInterval to the general yAxis object in `setOptions`, it is applied to _all_ Y axis, including the navigator, and that's where it fails.
