### ISSUE TITLE
How to know which level I select in drilldown?

### ISSUE THREAD

**Issue by TingYinHelen** [highcharts/highcharts#5973]
The data have multiple levels, I added a event listener on "drillup". Now I want to know which level I select. Or I want to know the data that I select level has.

**Comment by sebastianbochan** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

**Comment by TingYinHelen** [comment]
Ok, thanks a lot.
