### ISSUE TITLE
Stacked Area Chart Uses Undefined Clippath

### ISSUE THREAD

**Issue by ychi** [highcharts/highcharts#5974]
#### Expected behaviour
SVG elements only use ClipPaths that are defined in the <defs> tag.

#### Actual behaviour
In[ this demo](http://www.highcharts.com/demo/area-stacked), some <g> elements reference to ClipPath with id = highcharts-2 which does not exist in <defs> tag. 

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/area-stacked/

#### Affected browser(s)
It does not really affect browser rendering, but will cause problem when trying to export to PNG with transcoders such as batik.

**Comment by pawelfus** [comment]
Thanks for reporting the issue!

**Workaround:**
http://jsfiddle.net/a5kbyuvj/

Snippet:

    plotOptions: {
      series: {
        ...
        events: {
          afterAnimate: function() {
            this.markerGroup.attr({
              'clip-path': null
            });
          }
        }
      }
    },

*Internal note:*
That clip path usage comes from an animation - clip path is removed from definitions, but not from all attributes. Similar issue with disabled animation: `clip-path` is set to `none` in such case.

**Comment by KacperMadej** [comment]
Resolved since version 5.0.3 (http://jsfiddle.net/zjatrm55/)
