### ISSUE TITLE
Non-ideal wrapping of axis labels

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#5975]
#### Expected behaviour

With `textOverflow` set to `none`, axis labels wrap over multiple lines where required, to avoid overlap with the neighbouring label.  Similar for `textOverflow` set to `ellipsis` (but using an ellipsis to avoid overlap rather than wrapping).

#### Actual behaviour

Whilst wrapping/truncation does occur to avoid overlap, it doesn't seem to happen consistently, so that there are many occasions where label overlap occurs, mixed (in the same chart) where wrapping/truncation has avoided an overlap situation.

Example (from fiddle below):

![capture](https://cloud.githubusercontent.com/assets/9009792/20300393/ef77d140-ab16-11e6-92ff-996db494c678.JPG)

In the above, you can see there are some that overlap (no wrapping), and some that wrap to avoid overlapping... it's a bit of a mish-mash (to use a technical term).

#### Live demo with steps to reproduce

http://jsfiddle.net/LLcqspw3/2/

Try various widths of chart by dragging the vertical divider and hitting Run.

Similar behaviour occurs with `textOverflow` set to `ellipsis`.

#### Affected browser(s)

Chrome (but this also happens for server generated charts, so it seems not to be browser-specific)

**Comment by jon-a-nygaard** [comment]
Thanks for reporting, we will try to fix this as soon as possible.

**Comment by TorsteinHonsi** [comment]
The reason "Wed 2 January" and "Mon 7 January" are the only ones that are wrapped in the picture above, is that the characters `W` and `M` are wider than others. So that part is how we expect it.

One bug remains though, it is that labels are overlapping when they shouldn't.

**Comment by TorsteinHonsi** [comment]
Looking at the code now, I am starting to think that the `getSlotWidth` needs an overhaul. Instead of guessing the slotWidth, we could probably measure it from actual tick positions.

Here's a first draft ([view it live](http://jsfiddle.net/highcharts/LLcqspw3/3/)) 
```js
/**
 * Draft for a new getSlotWidth function.
 * @todo
 * - account for labels.options.step
 * - account for labels.options.staggerLines
 * - account for labels.options.rotation
 * - check specifically bugs mentioned in the source code
 */
Highcharts.Axis.prototype.getSlotWidth = function() {
	// Utility functions
    var each = Highcharts.each,
    	isNumber = Highcharts.isNumber;
        
    var slotWidth,
    	lastPxPos;
    each(this.tickPositions.slice(0, 5), function(pos) {
        var pxPos
        if (isNumber(pos)) {
            pxPos = this.toPixels(pos);

            if (isNumber(lastPxPos)) {
                slotWidth = Math.max(slotWidth || 0, Math.abs(pxPos - lastPxPos));
            }
            lastPxPos = pxPos;
        }
    }, this);
    return slotWidth;
};
```

**Comment by drmrbrewer** [comment]
Looks good.  What about with a custom `tickPositioner` like in my original example?  See the following, which is my original example but with your new `getSlotWidth`: http://jsfiddle.net/LLcqspw3/4/

![capture](https://cloud.githubusercontent.com/assets/9009792/20487737/8298f528-affc-11e6-889e-7b50235ea6cd.JPG)
