### ISSUE TITLE
Drilldown has error with round-corners module

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5977]
#### Live demo with steps to reproduce
Demo:
- http://jsfiddle.net/z9nstbz8/

Click on a column and observe errors in the console. 

![zrzut ekranu 2016-11-15 o 13 14 13](https://cloud.githubusercontent.com/assets/2115686/20305361/6eac2560-ab35-11e6-8a8f-7c6583a7a2f2.png)

#### Affected browser(s)
All

**_Workaround_**
Merge new series with the current point series options.

Example:
-  http://jsfiddle.net/2Lpotqvs/

**Comment by TorsteinHonsi** [comment]
This is strictly not a Highcharts issue, but a compatibility issue with the rounded-corners plugin. It probably needs to define its own animateFrom and animateTo methods to be picked up by the drilldown module. Moved to https://github.com/highcharts/rounded-corners/issues/11.
