### ISSUE TITLE
fillColor attribute of Point / Flag is not working on 5.0.2

### ISSUE THREAD

**Issue by zevero** [highcharts/highcharts#5978]
#### Expected behaviour
fillColor was working in Highcharts 4.x

#### Actual behaviour
It is ignored on 5.0.2

#### Live demo with steps to reproduce
http://jsfiddle.net/Lq29coaq/
As you can see color is still working, but fillColor is not.
It does not matter if data is static or dynamic.

#### Affected browser(s)
Chrome 54

**Comment by pawelfus** [comment]
Thank you for reporting!

It's a bug, where we check only `series.fillColor`, but not `point.fillColor` when setting color fill for a flag. It works when set on a series level: http://jsfiddle.net/Lq29coaq/1/

**Comment by zevero** [comment]
Thank you for accepting the regression. I this point.fillColor documented? I did not find it here http://api.highcharts.com/highstock/Point
or 
http://api.highcharts.com/highstock/series%3Cflags%3E.data

But it is documented here for example:
http://api.highcharts.com/highstock/series%3Carea%3E.marker

What is the difference between Point and Marker and Flag?

**Comment by pawelfus** [comment]
It should be documented in [`series<flags>.data`](http://api.highcharts.com/highstock/series%3Cflags%3E.data), like color is. 

> What is the difference between Point and Marker and Flag?

Point is the Highcharts class for a point, which has it's own API (as described in [`Highcharts.Point`](http://api.highcharts.com/highstock/Point)).

For a marker, see [docs](http://www.highcharts.com/docs/chart-concepts/series#point). 

And we don't have something like "Flag". I mean we have series with type "flag", which is just another series type (column, pie, spline, candlestick etc.).
