### ISSUE TITLE
Wrong candlestick width on xAxis with breaks

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5979]
It looks like the width of candlesticks is much different when breaks are used and when xAxis doesn't have breaks. I think that correct functionality is to have similar candlestick width for both causes.

Live demo with breaks:
http://jsfiddle.net/2s3p15Ly/4/

Live demo without breaks:
http://jsfiddle.net/2s3p15Ly/8/

For now I think that this problem may be caused by beforeSetTickPositions method.

**Comment by advapiIT** [comment]
Hello @Izothep ,
I'm the colleague of Laurent, the guy who submitted you the issue... I'm writing you since in this issue you've set the same url for bothe the jsfiddle

Thanks

**Comment by advapiIT** [comment]
Hello,
We've seen that Borsa Italiana had a working version with HighStock, please see this fiddle

http://jsfiddle.net/91j9fkco/1/

**Comment by jon-a-nygaard** [comment]
Thanks for reporting @Izothep and @advapiIT 

Internal Note:
It appears that there was a change in behaviour between versions 2.0.4 and 2.1.0

**Comment by pawelfus** [comment]
@jon - a reminder: breaks were introduced in 2.1.0 ;) That means it always was broken.

**Comment by jon-a-nygaard** [comment]
@pawelfus Thanks. I guess I did not read @Izothep `s description good enough.

**Comment by pawelfus** [comment]
*Internal note:*
Broken axis module replaces [`val2lin`](https://github.com/highcharts/highcharts/blob/73eb93384f10db265a376ae537bbcb099a6e2aa3/js/modules/broken-axis.src.js#L105) and [`lin2val`](https://github.com/highcharts/highcharts/blob/73eb93384f10db265a376ae537bbcb099a6e2aa3/js/modules/broken-axis.src.js#L125), without support for `toIndex` and `fromIndex` params. `beforeSetTickPositions()` method uses that [here](https://github.com/highcharts/highcharts/blob/73eb93384f10db265a376ae537bbcb099a6e2aa3/js/parts/OrdinalAxis.js#L290-L291).

**Comment by advapiIT** [comment]
Excuse me, any update on this?
Thanks

**Comment by TorsteinHonsi** [comment]
Simplified demo: http://jsfiddle.net/2s3p15Ly/9/.

Interestingly, it works just fine with vanilla Highcharts and the `broken-axis` module because the ordinal axis is not loaded.

**Comment by TorsteinHonsi** [comment]
@advapiIT Sorry for the late reply, holidays and all... See http://jsfiddle.net/2s3p15Ly/10/ for a demonstration of the fix.
