### ISSUE TITLE
Additional options for series are not applied in "getSVG" method.

### ISSUE THREAD

**Issue by AlexanderSokolov1** [highcharts/highcharts#5982]
#### Expected behaviour
All additional options for series and its data points are applied and result svg string contains that changes.

#### Actual behaviour
Additional options for series are ignored

#### Live demo with steps to reproduce
http://jsfiddle.net/q6fLodmk/
When you click on "View SVG" button, the series title and data is not changed.

#### Source
[In exporting.src.js file, line 323](http://github.highcharts.com/master/modules/exporting.src.js)
```
// prepare for replicating the chart
options.series = []; // <--- all additional options now removed
each(chart.series, function (serie) {
    seriesOptions = merge(serie.userOptions, { // #4912
        animation: false, // turn off animation
	enableMouseTracking: false,
	showCheckbox: false,
	visible: serie.visible
    });

    if (!seriesOptions.isInternal) { // used for the navigator series that has its own option set
        options.series.push(seriesOptions);
    }
});
```

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thank for reporting!
I agree, it looks buggy. I don't think changing data set for an exported chart is a good idea (unless you want to surprise an user ;) , but for example changing series name should be possible: http://jsfiddle.net/q6fLodmk/2/

**Comment by AlexanderSokolov1** [comment]
Thank you for replay!
In my case, I have to hide deselected legend items from export, so I use the "showInLegend" series option with the "false" value, when export.
(Also I use the "Pie" chart, where I should set "showInLegend" option for series points like here:
http://jsfiddle.net/sNzrK/.)

I agreed with you about data set (x, y, value and etc. options should not be changed), but I think, that other properties is really useful to change :-).

**Comment by pawelfus** [comment]
**Workaround:**
Change options inline, using `userOptions` in the original series object, for example: http://jsfiddle.net/q6fLodmk/3/

Snippet:

    // Set new options:
    chart.series[0].userOptions.name = "New Series Name";
    
    var svg = chart.getSVG(additionalOptions);
    document.body.innerHTML = '<div>' + svg + '</div>';
    
    // Restore option
    chart.series[0].userOptions.name = 'Series 1';

**Comment by AlexanderSokolov1** [comment]
Yeah, workaround is a nice option, but it looks like a hack in the code and "additionalOptions" looses its point.
Anyway, thank you very much for the advice :-).
