### ISSUE TITLE
tootlip position different from mouse cursor

### ISSUE THREAD

**Issue by shubhijain106** [highcharts/highcharts#5986]
#### Expected behaviour
I have almost 200 series on my charts most of which are vertically slanted. I have shared tooltip for series. The problem is that when I place a cursor on any 1 series, then the tooltip for other series appears
I know this happens because it finds a point for any other series and not the one that I am pointing to at that particular position of cursor. Is there any way around/hack to this problem.Is there any way my pointed series near point gets highlighted instead of any other series point.
In large scenario, the distance between the position of cursor and the point of the series highlighted is quite large.

example:
2 series: one intersects the other

                          /       /
                        /   ___/
                      /   /
                 _____/
               / /

**Comment by jon-a-nygaard** [comment]
Hi @shubhijain106 could you perhaps provide us with a replication of your issue? [JSFiddle]

**Comment by jon-a-nygaard** [comment]
Hi @shubhijain106 
If I understand your issue correctly then you might be looking one of the following two scenarios:
1. Just the [closestPoints gets hovered and displayed in tooltip](http://jsfiddle.net/jon_a_nygaard/89tnzjuq/2/)
2. All points are hovered, but [just the closest are displayed in the tooltip](http://jsfiddle.net/jon_a_nygaard/xgqexney/1/)

How you decide which points are closest must be adapted to your own needs.
Read more about both the [tooltip.formatter](http://api.highcharts.com/highcharts/tooltip.formatter) or [how to extend Highcharts](http://www.highcharts.com/docs/extending-highcharts/extending-highcharts) to know more about how the examples above works.

**Comment by shubhijain106** [comment]
its similar to the problem #1452
except that it happens without zoom too and in line chart

**Comment by jon-a-nygaard** [comment]
@shubhijain106 Can you provide a replication of your issue, using for example [JSFiddle](https://jsfiddle.net/)?

**Comment by jon-a-nygaard** [comment]
Closing this as we are unable to make a replication, and it is considered inactive. If anyone should have further information on the issue, please give us a comment.
