### ISSUE TITLE
The chart.update function does not handle colors appropriately

### ISSUE THREAD

**Issue by aazhari** [highcharts/highcharts#5988]
#### Expected behaviour
After creating a new chart with a specific color array specified:
```
  var chart = Highcharts.chart('container', {
    colors: ["red", "blue", "green", "purple", "gray"],
    series: [{
      name: 'Tokyo',
      data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
    }
    ....
}
```
![image](https://cloud.githubusercontent.com/assets/7737331/20368432/913b30e6-ac19-11e6-8374-9c2e13a41840.png)
After updating the color property using chart.update:
```
chart.update({
    colors: ["orange", "violet", "indigo"]
})

```
The chart should look how it does when initially drawing it with those colors:
![image](https://cloud.githubusercontent.com/assets/7737331/20368308/172e4964-ac19-11e6-8722-164e76269f38.png)

#### Actual behaviour
After calling:
chart.update({
    colors: ["orange", "violet", "indigo"]
})
If not as many colors are specified, they don't roll over resulting in hidden series:
![image](https://cloud.githubusercontent.com/assets/7737331/20368344/3c948164-ac19-11e6-8c06-f2727cd884d0.png)

#### Live demo with steps to reproduce
[Link to jsfiddle](https://jsfiddle.net/a3bge3fL/2/)

#### Affected browser(s)
All browsers

**Comment by jon-a-nygaard** [comment]
Thanks for reporting, we will try to fix this as soon as possible.

Internal Note:
Series color indexes probably needs a refresh. I also believe that it should be possible to [change chart options and do a redraw](https://jsfiddle.net/jon_a_nygaard/a3bge3fL/3/), but this does not work.

**Comment by TorsteinHonsi** [comment]
The bug is that `series.userOptions._colorIndex` is cached on the first run, and since the length of the color array is changed, the index now points to non-existing colors.

The workaround is to set equal length colors.

**Comment by sebastianbochan** [comment]
+1
