### ISSUE TITLE
More than 1000 data points causes Stock chart to not render

### ISSUE THREAD

**Issue by lehresman** [highcharts/highcharts#599]
See this for an example of it not rendering:  http://jsfiddle.net/nHJMk/

And see this for an example of it working properly: http://jsfiddle.net/SMLJx/1/

The only difference between those two is the 2nd uses 999 data points and the first uses 1000.

I'm currently running into this in my application for any graph that plots more than 1000 data points.

**Comment by sorenhoyer** [comment]
How much faster is it to use the array form over the object form with x and y properties?

**Comment by pawelfus** [comment]
Hi @sorenhoyer - I don't think we can provide any hard numbers, it depends on a machine, os and a browser. The best is to setup your chart, with config and data, with two data formats and compare it directly.

**Comment by TorsteinHonsi** [comment]
In my Chrome, testing with 100k points, the [object data](http://jsfiddle.net/nHJMk/53/) renders in ~320 ms, while the [array data](http://jsfiddle.net/nHJMk/55/) renders in ~200 ms. With smaller series the difference will be less significant. 

The `turboThreshold` feature was implemented at a time when IE 8 and less had 50% marketshare, and in those browsers, the difference was much greater.
