### ISSUE TITLE
Coloring of new series doesn't take current colors of the chart into account

### ISSUE THREAD

**Issue by newlukai** [highcharts/highcharts#5990]
#### Expected behaviour
After removing a series from the chart a newly added series should be colored in the same color the removed series used.

#### Actual behaviour
The new series is colored in the next color available in the options.colors array.

#### Live demo with steps to reproduce
[Replacing all series](http://jsfiddle.net/pvebpu8d/)
In the live demo use the "Another chart" button to dynamically change the series displayed. The two series are drawn using the primary and secondary color. Hitting the button again, removes the series and adds them again. This time, the series are drawn using the third and fourth color. Would be great if the coloring would start at zero again.

[chart.colorCount doesn't work](http://jsfiddle.net/pvebpu8d/)
An approach to start coloring with the primary color after removing all series would be to limit the color count in chart.colorCount. But as you can see (hit "New series" multiple times), this setting doesn't work as expected, the colors are chosen from the complete options.colors array.

#### Affected browser(s)
All, I think.

**Comment by pawelfus** [comment]
Hi @newlukai 

Thanks for reporting this. However, I don't think it's a bug:

- replacing all series:
It starts from first color because the original series has `colorByPoint` - then first series doesn't have color from `colors` array. So in the first update, colors counter is still set to 0.

- `chart.colorCount`
This option works in `styled mode` as described in the [API](http://api.highcharts.com/highstock/chart.colorCount).

You can always set colors array in options: http://jsfiddle.net/nw53pbwq/ or alternatively set color for each series separately.

**Comment by newlukai** [comment]
Hi @pawelfus ,

sorry for the late answer, I didn't have a chance to care about this issue.

In my opinion, it is still a bug. Going one step back and thinking about a simple set with two entities: one you would call the first one, the other is the second one. Once I remove those two entities, leaving the set empty, and put two other entities in this set, why should these replacing entities be a third one and a fourth one?

What do you think?

In my application I create charts dynamically. If Highcharts would reset the colors counter to zero once all series are removed, I wouldn't need to count the displayed series and adjust the colors array accordingly.

**Comment by pawelfus** [comment]
Thank you for the feedback!

I see your point and I agree, that would be convenient in a certain cases. Actually, there is a discussion about the same issue: #6168 and #6138. Will `chart.resetColorCounter()` (or simple `chart.colorCounter = 0;` method be helpful in your case too? In that way, anyone can decide if colors should start from the last one or from the first one.

**Comment by crh225** [comment]
@pawelfus chart.resetColorCounter() will defiantly be helpful. at my company, all charts must have the same color in a certain order.

if you add chart.resetColorCounter() can you also add chart.resetMarkerCounter()

**Comment by oysteinmoseng** [comment]
Ref #6138 colorCounter and symbolCounter is now automatically reset when there are no series in the chart.
