### ISSUE TITLE
Animation of new tick labels origin in the wrong place.

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#5992]
#### Actual behaviour
They come in from too high on the axis

#### Live demo with steps to reproduce
1. http://jsfiddle.net/highcharts/m4184as8/
2. Click the + button once.

This is a regression between v4.2.7 and v5.0.0, but I have not been able to trace it reliably to a specific commit.

**Comment by KacperMadej** [comment]
Still visible in v7.0.1

**Comment by pawelfus** [comment]
Works fine since v8.1.1: http://jsfiddle.net/BlackLabel/9w27rzun/
