### ISSUE TITLE
exported "activity chart" style solid gauge charts are rendered with slanted/strange linecaps

### ISSUE THREAD

**Issue by dbasner** [highcharts/highcharts#5994]
#### Expected behaviour
When you export an activity chart with square linecaps to an export server it renders it the way it is shown on the front end.

#### Actual behaviour
exported activity charts contain strange and often inaccurate linecaps.

#### Live demo with steps to reproduce
http://jsfiddle.net/ummubyk4/

click export to image/pdf and view it
![Activity chart exported incorrectly](https://cloud.githubusercontent.com/assets/6394494/20407988/925e1dbc-ace1-11e6-9418-f34e26a8ec13.png)

**Comment by oysteinmoseng** [comment]
Thank you for reporting.

It seems to work well in offline-exporting: http://jsfiddle.net/ummubyk4/1/.

**Comment by TorsteinHonsi** [comment]
It's most likely a rendering issue in PhantomJS. The generated SVG renders correctly in Chrome and Firefox.

#### Workaround
If you don't need/want the rounded line ends of the original demo, you can remove the `stroke-linecap` option and use `radius` and `innerRadius` instead: http://jsfiddle.net/highcharts/ummubyk4/2/
