### ISSUE TITLE
Panning with reversed x axis

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5997]
#### Actual behaviour
Panning with reversed axis causes that the chart is zoomed.

#### Live demo with steps to reproduce
http://jsfiddle.net/akehpzq4/1/

Compare how it works with a non-reversed axis:
http://jsfiddle.net/akehpzq4/2/

Partially connected with [#3278](https://github.com/highcharts/highcharts/issues/3278)

**Comment by Drumstix42** [comment]
Added comment to commit aee476c with additional fixes.
