### ISSUE TITLE
Cannot select dates freely (bug) ?

### ISSUE THREAD

**Issue by steven-fernandez** [highcharts/highcharts#5998]
I am having problems where I cannot freely select from / to dates from the calendar.

I can see the same issue in all of the demo's provided by Highcharts so it's either supposed to be that way or it's a bug in Highcharts.

In any case I'd love to know.

Here's an example:

http://jsfiddle.net/BWEm5/

If you try to select on the FROM ... the 1st of that month and on the TO selected the 2nd of that month is will not change to what I've selected.

Is this a bug or is their a reason for it?

Thanks

**Comment by zevero** [comment]
I'd say its a feature not a bug!
This is daily data, so just selecting the next day would result in a rather ugly straight line.

**Comment by TorsteinHonsi** [comment]
Yes, it's a feature, the date picker only works within the chart's actual data range. 

In the future, for general tech support, please see www.highcharts.com/support.
