### ISSUE TITLE
export png not working on Highcharts demo

### ISSUE THREAD

**Issue by tdubb** [highcharts/highcharts#6000]
#### Expected behaviour

png of chart is downloaded
#### Actual behaviour
timeout error

#### Live demo with steps to reproduce

http://www.highcharts.com/demo/line-labels
click the download png image option and it will timeout.

#### Affected browser(s)
chrome, safari

**Comment by liorbentov** [comment]
@TorsteinHonsi, is there any solution to this?
This is a big problem

**Comment by HoangHades** [comment]
It's also can't export jpeg file
[https://gyazo.com/9649a475a3bfbc9cb3dbf6683ea8ce07](url)

**Comment by TorsteinHonsi** [comment]
Hi, we're looking into this as we speak, it is of top priority.

**Comment by TorsteinHonsi** [comment]
Meanwhile I'll recommend that you look into our [client side export](http://www.highcharts.com/docs/export-module/client-side-export) feature.

**Comment by larsac07** [comment]
This issue is resolved, as the export server issue was fixed earlier this week
