### ISSUE TITLE
connectNulls does not work correctly for arearange chart type

### ISSUE THREAD

**Issue by ryaa** [highcharts/highcharts#6001]
#### Expected behaviour
connect not nulls values to show continuous min/max lines 
It used to work before however for the latest build it does not

#### Actual behaviour
The filling background is off

#### Live demo with steps to reproduce
set up arearange with connectNulls: true and provide dataset with nulls

http://jsfiddle.net/ryaa/c93bbqpt/6/

#### Affected browser(s)
chrome

**Comment by ryaa** [comment]
Note that the min/max lines are fine but the filling between them is off

**Comment by ryaa** [comment]
I also created another fiddle for highcharts version 4.2.0 and everything works there http://jsfiddle.net/ryaa/c93bbqpt/8/

**Comment by jon-a-nygaard** [comment]
Thanks for reporting, we will have a look at this a soon as possible.

**Comment by TorsteinHonsi** [comment]
Interestingly, it worked as intended in d71fb4b, where `isNull` was set to true on the `highAreaPoints`. But this commit broke other stuff, like the basic [arearange demo](http://jsfiddle.net/gh/get/jquery/3.1.1/highcharts/highcharts/tree/master/samples/highcharts/demo/arearange/).

**Comment by ryaa** [comment]
Any plans to fix the problem? Any estimate when this can happen? Thanks

**Comment by abrambailey** [comment]
Broken in 5 http://jsfiddle.net/xsf9tf4r/
