### ISSUE TITLE
Pie Chart Select State Border Width variation in different library versions

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6003]
#### Expected behaviour
Pie Chart select state border width across different versions of highchart library should work correctly.

#### Actual behaviour
In v4.2.1 of highchart library, there is no need to give initial borderWidth in series options for select state borderWidth to work; i.e. upon selecting pie slice, width of border is applied only after select. But in the latest highchart library, borderWidth in series options needs to be given for borderWidth of select state to work.

#### Live demo with steps to reproduce
v4.2.1 http://jsfiddle.net/kvv2gtj3/
Latest version http://jsfiddle.net/kvv2gtj3/2/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @sagargurtu 

Thank you for reporting the issue.

**Workaround:**
Use CSS to change selected state: http://jsfiddle.net/kvv2gtj3/3/

    .highcharts-point-select {
      stroke-width: 5
    }
