### ISSUE TITLE
Selecting pie slices in styled mode

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6005]
#### Behaviour
Selecting any of the pie slices in styled mode changes its initial color to the color of the first point.

#### Live demos
http://jsfiddle.net/d_paul/5hdctfhe/

**Comment by garybrain** [comment]
Hi, as a workaround I disabled the following two CSS entries.

.highcharts-pie-series .highcharts-point-select {
/* fill: inherit;
stroke: inherit; */
}
.highcharts-point-select {
/*fill: #cccccc;
stroke: #000000;*/
}

**Comment by TorsteinHonsi** [comment]
Ok, by [setting the selected pie](https://github.com/highcharts/highcharts/blob/v5.0.4/css/highcharts.scss#L237-L240) color to `inherit`, the intention was to override the [general point select rule](https://github.com/highcharts/highcharts/blob/v5.0.4/css/highcharts.scss#L217-L220), that set the color to gray.

However the fill didn't go back to `.highcharts-color-n`, but to the general series color. 

Any idea of how we can simply disqualify the fill set for `.highcharts-point-select`?

**Comment by KacperMadej** [comment]
@TorsteinHonsi How about:

- remove [CSS for selected pie](https://github.com/highcharts/highcharts/blob/v5.0.4/css/highcharts.scss#L237-L240)
- add `highcharts-color-by-point` for series with [colorByPoint](http://api.highcharts.com/highcharts/plotOptions.bar.colorByPoint)

(or `highcharts-series-pie` only for pies)
- change [general point select rule](https://github.com/highcharts/highcharts/blob/v5.0.4/css/highcharts.scss#L217-L220) selector to:
`.highcharts-series:not(.highcharts-color-by-point) .highcharts-point-select {` 

(or `highcharts-series-pie` only for pies)

Result: http://jsfiddle.net/df74rdgv/

**Comment by TorsteinHonsi** [comment]
Yes, that works well! Will you commit the fix?
