### ISSUE TITLE
stackLabels not working on Firefox

### ISSUE THREAD

**Issue by kevinfra** [highcharts/highcharts#6006]
#### Actual behaviour
I'm getting "NS_ERROR_FAILURE:" when enabling stackLabels for stacked columns charts.

#### Live demo with steps to reproduce
[example from highcharts API reference](http://jsfiddle.net/gh/get/jquery/2/highcharts/highcharts/tree/master/samples/highcharts/yaxis/stacklabels-align-center/)

#### Affected browser(s)
Firefox 45.0.2, 49.0.2

**Comment by TorsteinHonsi** [comment]
Duplicate of #6008.
