### ISSUE TITLE
Query: Drilldown for Fixed Placement Column Charts

### ISSUE THREAD

**Issue by chanduk040** [highcharts/highcharts#6011]
Dear Team,

Is there a feasibility to create drill downs for Fixed Placement Column Charts? If yes could you please share the sample how to create? The drilldown chart also should be same  Fixed Placement Column Chart. 

Regards,
Chandu

**Comment by oysteinmoseng** [comment]
Yes, this is possible by simply setting `grouping: false` and creating multiple series. Example: http://jsfiddle.net/9pxcqLjk/.

The example uses version 5.0.3 because of a drilldown bug in 5.0.4 (see #6017).

**Comment by HarpreetSandhu** [comment]
@chanduk040  You can take reference (multi-level drill for Fixed Placement Column Charts)  from this  link - http://jsfiddle.net/49q18Lp3/610/
