### ISSUE TITLE
Navigator handles cannot be moved

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6012]
#### Expected behaviour
Navigator should work like with enabled series.

#### Actual behaviour
Navigator "overwrites" extremes

#### Live demo with steps to reproduce
Example: http://jsfiddle.net/hhLxe9vw/2/

Steps to reproduce
  1.  Resize the navigator in the beginning to show less points.
  2.  Hide the first series by legend.
  3.  Update the chart.
  4.  Set the size of the navigator to show all the data.
  5.  Try to resize the navigator again, without appending the removed series from legend (The problem appears here).

#### Affected browser(s)
All

![slider2](https://cloud.githubusercontent.com/assets/2115686/20527595/4c3a3168-b0c9-11e6-9dd3-70e5348d4b83.gif)

**Comment by pawelfus** [comment]
Works fine on the dev-navigator branch: http://jsfiddle.net/hhLxe9vw/3/

**Comment by sergiomcunha** [comment]
When this dev-navigator will be available to use as production?

**Comment by sergiomcunha** [comment]
How's the correction of this issue?

**Comment by pawelfus** [comment]
Hi @sergiomcunha 

The release date hasn't been specified yet. We will try to release this in the next release.

**Comment by TorsteinHonsi** [comment]
@pawelfus I have now merged the dev-navigator branch  into master. But actually I don't think this issue has been fixed. Dragging the scrollbar works as long as it doesn't touch the min or max, but after that, the labels are frozen. This is the same for the old master, the dev-navigator and the new master.

**Comment by pawelfus** [comment]
You are right, navigator "works" as we don't see the returning navigator to the original position, so it only hides the real issue here: extremes are wrong.

**Comment by TorsteinHonsi** [comment]
Will you look into it @pawelfus ?

**Comment by pawelfus** [comment]
@TorsteinHonsi Done. And a reminder for tests: e81e5a6b12f1a611b6ebf5ef9cc16e3e03c11408
