### ISSUE TITLE
Missing Y-Axis options 

### ISSUE THREAD

**Issue by lazymeadow** [highcharts/highcharts#6013]
#### Expected behaviour
Highcharts cloud should have more options for the Y-Axis under advanced (like gridline color and tick options).
The legend option to change the symbol shape between square and circle should do that.

#### Actual behaviour
Highcharts cloud is missing a lot of options under Y-axis. The legend option to change symbol shape between circle and square is not functioning, but is showing only circles.

#### Affected browser(s)
Chrome and Firefox on OSX

**Comment by oysteinmoseng** [comment]
Thank you for reporting. Note that you can use the custom code area to set options that are not available through the GUI.

**Comment by TorsteinHonsi** [comment]
This belongs to the Highcharts Cloud project. @havardge FYI.
