### ISSUE TITLE
Column Chart Zoom Out not working

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6014]
#### Expected behaviour
Zoom in to the column chart until the whole chart disappears. Upon clicking reset zoom button, the column chart should appear correctly.

#### Actual behaviour
Upon clicking reset zoom button, the column chart does not show up. Issue since Highcharts v5.0.1

#### Live demo with steps to reproduce
http://jsfiddle.net/uu2b1ave/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thanks for reporting the issue!

Responsible commit: 7c2a168
