### ISSUE TITLE
Click event on entire series crosshair

### ISSUE THREAD

**Issue by maximelafarie** [highcharts/highcharts#6015]
#### Expected behaviour
I would like be able to click on an entire series crosshair to get the column category instead of click on a series point and get `this.category`.

#### Actual behaviour
<img width="457" alt="capture d ecran 2016-11-22 a 19 34 56" src="https://cloud.githubusercontent.com/assets/5319267/20557164/a9721cbe-b16a-11e6-9163-f997fd89b658.png">

On the above example, I can only click on the points in the highlighted column to get the category ("janvier 16"). So I would like to attach a click event to the crosshair to get the category (that is the same for the two points)

#### Affected browser(s)
All.

**Comment by pawelfus** [comment]
I thinks this is not a bug. Crosshair simply doesn't have events, but you can add them by extending Highcharts, snippet:

```javascript
(function(H) {
  H.wrap(H.Axis.prototype, 'drawCrosshair', function(proceed) {
    var axis = this;
    wasRendered = !!this.cross; // on init, cross is not defined

    proceed.apply(this, Array.prototype.slice.call(arguments, 1));

    // Add event just once:
    if (!wasRendered && this.cross) {
      this.cross.on('click', function(e) {
        var point = axis.chart.hoverPoint;
        console.log(
          'Point:',
          point,
          '\nCategory',
          point.category
        )
      });
    }
  });
})(Highcharts);
```

Live demo: http://jsfiddle.net/w1kg053z/

**Comment by MaadMax** [comment]
Thank you @pawelfus ! So now with this new snippet am I able to call it in a Highchart config object or do I have to call it each time I want to add a new action on click event (it depends on the charts I have) ?

**Comment by pawelfus** [comment]
This snippet is following extending Highcharts [guidelines](http://www.highcharts.com/docs/extending-highcharts/extending-highcharts). Once you add this snippet, all charts will get this functionality (it works almost the same way as works `exporting.js` or any other module/plugin). If you want to, you can add extra parameter, for example: 

```
xAxis: {
  clickOnCrosshair: true
  ...
}
```

And then check in the plugin above:

```javascript
    ...
    // Add event just once:
    if (!wasRendered && this.cross && this.options.clickOnCrosshair) {
    ...
```

And this way, only charts with `xAxis.clickOnCrosshair` flag set to true will get this functionality.

**Comment by MaadMax** [comment]
That's nice, thanks you ! But i would also like to know if it's possible to do something like this : 

```
xAxis: {
  clickOnCrosshair: function () {
    console.log(this.category);
    //some actions...
  }
  ...
}
```
directly inside the chart configuration object, like that (event on click on a chart series point):
```
series: {
  cursor: 'pointer',
  point: {
    events: {
      click: function () {
        console.log(this.category);
        //some actions...
      }
    }
  }
}
```

**Comment by pawelfus** [comment]
Ah, right, sorry for the misunderstanding! Of course it can be done too: http://jsfiddle.net/w1kg053z/1/ - note `this` refers to the Axis.

**Comment by MaadMax** [comment]
No problem, that's so awesome! I didn't expect that it was that customizable ! By the way, thank you again!

**Comment by sebastianbochan** [comment]
Now available in the custom-events.js plugin.

Example:
- http://jsfiddle.net/mo37r7qw/

**Comment by maximelafarie** [comment]
Recently wrote an article about awesome @pawelfus solution! https://maximelafarie.com/click-event-on-highcharts-series-crosshair

**Comment by jon-a-nygaard** [comment]
We consider the custom-event plugin from Black Label to be a very good solution for these use cases, and will therefore for the time beeing not add this enhancement to the Highcharts core.

**In Conclusion:**
For those interested in adding events for crosshairs, have a look at the [custom-event.js plugin from Black Label](https://www.highcharts.com/plugin-registry/single/15/Custom-Events)

**Comment by maximelafarie** [comment]
@pigeontoe This solution isn't good anymore **since Highcharts upgrade to v6**. E.g.: if you take the above fiddle (https://jsfiddle.net/maximelafarie/gmxpucud/) it doesn't work, but if you downgrade the `highcharts.js` to v5.x.x, it will work as expected (**[same fiddle with Highcharts v5.0.14](https://jsfiddle.net/maximelafarie/d0b09b1s/)**).

**Comment by pawelfus** [comment]
Updated my demo to work with v6: http://jsfiddle.net/w1kg053z/5/ (added `pointerEvents: 'auto'` to a crosshair).

**Comment by pigeontoe** [comment]
Thanks for the response. I should have posted an update yesterday. I came to the same conclusion. I noticed Highcharts adds an inline style of "pointer-events: none;". Works fine when changed to auto. Thanks!
