### ISSUE TITLE
New chartOptions are wrong applied in a chart with multiple axis when using responsive option.

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6019]
#### Behaviour
In case when chart has multiple axis and all requirements are met to apply a new responsive options for them, only the first one receive options destined for the last one.

#### Live demos with steps to reproduce
http://jsfiddle.net/d_paul/vwjo7Le1/

1. Click ‘Small’ button to decrease chart size and apply new set of options (options for the last additional axis are applied to the first (main) axis).

2. After that, click ‘Large’ button to increase chart size again and notice how instead to go back to the default options, axis adapts default options of the last additional axis.

**Comment by oysteinmoseng** [comment]
The issue with applying options to axes can be seen in pure `chart.update` as well: http://jsfiddle.net/vwjo7Le1/1/

Regarding restoring to default options, there is a TODO comment [here](https://github.com/highcharts/highcharts/blob/master/js/parts/Responsive.js#L70) that may or may not be relevant..

**Comment by TorsteinHonsi** [comment]
See http://api.highcharts.com/highcharts/Chart.update.

> A special case is configuration objects that take arrays, for example xAxis, yAxis or series. For these collections, an id option is used to map the new option set to an existing object. If an existing object of the same id is not found, the first item is updated. So for example, running chart.update with a series item without an id, will cause the existing chart's first series to be updated.

In short, unidentified options apply to the first item.

See it in action: http://jsfiddle.net/highcharts/vwjo7Le1/2/

**Comment by jnschrag** [comment]
Could we get this added to the documentation for the responsive options? It isn't intuitive to have to go look at the Chart.updates documentation to find out that you need to map the axis to an ID if you want to change multiples of the same type.

Thanks!

**Comment by TorsteinHonsi** [comment]
Thanks for pointing this out! I've added the same information to http://api.highcharts.com/highcharts/responsive.rules.chartOptions.

Another question is if this is intuitive. Actually I think not. The most intuitive behaviour is probably what you expected in the first place, that item _n_ in the new configuration matched item _n_ in the existing configuration. Obviously it leads to problems when dynamically adding and removing axes and series, but so does the current default of always setting item 0.

**Comment by jnschrag** [comment]
Excellent, thank you!

I would agree with you that this isn't particularly intuitive and that it would make more sense for the new configuration to match the existing configuration. I see the benefits to being able to map them to an ID, but wouldn't it be possible for both methods to work in tandem? If an ID is specified, it should update the appropriate axis/series/etc., but if one is not specified, it should assume the existing configuration is the correct one.
