### ISSUE TITLE
Navigartor loses width when the series are removed from legend

### ISSUE THREAD

**Issue by sergiomcunha** [highcharts/highcharts#6022]
#### Expected behaviour
When all the series are removed from the chart, the navigator chart shouldn't go out of container.

#### Actual behaviour
Actually when removing all the series from a chart that have shared series from chart to navigator and with legend active the chart gets out of the container.
![Image of bug](https://s21.postimg.org/64bdjwl5j/Screenshot_from_2016_11_23_14_51_14.png)
#### Live demo with steps to reproduce
http://jsfiddle.net/yczmchey/

#### Affected browser(s)
Chrome, Firefox and IE

**Comment by pawelfus** [comment]
Thank you for reporting!

It looks like this issue: #5381 - it may be related, or even the same.

**Comment by pawelfus** [comment]
**Workaround:**
Set [`rangeSelector.selected`](http://api.highcharts.com/highstock/rangeSelector.selected) to any other button than "All".  Demo: http://jsfiddle.net/yczmchey/6/

*Internal note:*
Issue comes from "All", where extremes are undefined when we have all series hidden on the chart. In fact, we can simply drag&drop the navigator and the issue goes away. Actually, we can not base on `rangeSelector` - as this can be disabled, so we should mark navigator state as `dirty` when `navigator.xAxis` changes it's size (width/height).

**Comment by TorsteinHonsi** [comment]
@pawelfus I cherry-picked this fix after merging dev-navigator. Now the fix does nothing to this actual problem, and the provided unit test fails. Will you have a look?

**Comment by pawelfus** [comment]
For me it works fine on the master branch: http://jsfiddle.net/yczmchey/10/
Regarding unit-test - fixed by commit above.

**Comment by TorsteinHonsi** [comment]
It works for me too. Probably cache problems earlier.
