### ISSUE TITLE
Pie Chart - Drilldown wrong color

### ISSUE THREAD

**Issue by SojeSkormdark** [highcharts/highcharts#6023]
#### Expected behaviour
Seems to have a problem with drilldown on pie chart. When you select a drilldown the color are note good and you need to hover with the mouse to have the good one.

#### Actual behaviour
The color should work and not be needed to hover the pie chart to have the good one

#### Live demo with steps to reproduce
Try out in this fiddle and click on Microsoft Internet Explorer you will see the problem
http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pie-drilldown/

#### Affected browser(s)
All browser

**Comment by oysteinmoseng** [comment]
Thank you for reporting. 

Possibly vaguely related to #6005.
