### ISSUE TITLE
Drilldown Pie Chart expected colors don't show up until hover event (in demo chart)

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6024]
#### Expected behaviour
After clicking part of a pie, another pie should show up with new colors.

#### Actual behaviour
After clicking part of a pie, another pie shows up in single color (same as clicked slice of original pie).

#### Live demo with steps to reproduce
// Current HC version
http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pie-drilldown/
// Github version
http://jsfiddle.net/sh2nb7rs/

1. Click part of a pie
2. Don't move your mouse
3. Start hovering mouse over parts of a pie

**Comment by stpoa** [comment]
Duplicate of: #6023

**Comment by oysteinmoseng** [comment]
Closing as duplicate, please follow discussion in other issue.
