### ISSUE TITLE
Can't display datetime label in xAxis

### ISSUE THREAD

**Issue by ittus** [highcharts/highcharts#6026]
#### Expected behaviour
Datetime label is displayed on xAxis

#### Actual behaviour
Datetime label is not displayed, instead of it's auto incremental number

#### Live demo with steps to reproduce
http://jsfiddle.net/LLExL/6773/

![Image](https://www.dropbox.com/s/w0u7ms266m6nldp/Screen%20Shot%202016-11-23%20at%206.35.15%20PM.png?raw=1)

#### Affected browser(s)
Chrome 54.0.2840.98 (64 bit)

**Comment by pawelfus** [comment]
Thanks for reporting!

I think we have some misconfigured options. From our [docs](http://www.highcharts.com/docs/chart-concepts/axes):

> A datetime axis prints labels of round date values in appropriate intervals. Internally, a datetime axis is a linear numeric axis based on milliseconds since midnight Jan 1, 1970, as specified by the JavaScript Date object. Depending on the scale the datetime label will either be represented as time or a date.

 Your data has strings as x-values, so you should to one of the following:

- change `xAxis.type` to `"category"`: http://jsfiddle.net/LLExL/6774/
- change x-values to timestamps: http://jsfiddle.net/LLExL/6775/ (it's better solution if you want to use `dateTimeLabelFormats`).

Of course don't forget to remove `xAxis.categories = []` - setting this an empty array tells Highcharts to use that exactly array, and if array is empty, you will see only auto-incremented labels.

**Comment by ittus** [comment]
The problem is that it works with highcharts 4.2.5, but for 4.2.7 and above it will be broken.

**Comment by ittus** [comment]
Out code works perfectly with highcharts 4.2.5 but will be broken on highcharts 4.2.7 and above.

**Comment by oysteinmoseng** [comment]
@ittus This is because setting `categories: []` used to imply `type: "category"` on axes. Now you have to remove the empty array and set `type: "category"` explicitly for the same behavior. Example: http://jsfiddle.net/LLExL/6776. But as Pawel mentions, it would be a better solution to use milliseconds for your x-values.
