### ISSUE TITLE
getLinearTickPositions always starts with 0 when min is less than tickInterval

### ISSUE THREAD

**Issue by hitlcy** [highcharts/highcharts#6027]
calling getLinearTickPositions(4, 2, 10)
#### Expected behaviour
[2, 6,10]

#### Actual behaviour
[0, 4, 8, 12]

#### Live demo with steps to reproduce
check the source code,  roundedMin = correctFloat(mathFloor(min / tickInterval) * tickInterval), will always returns 0 if min< tickInterval. 

getLinearTickPositions: function (tickInterval, min, max) {
            var pos,
                lastPos,
                roundedMin = correctFloat(mathFloor(min / tickInterval) * tickInterval),
                roundedMax = correctFloat(mathCeil(max / tickInterval) * tickInterval),
                tickPositions = [];

            // For single points, add a tick regardless of the relative position (#2662)
            if (min === max && isNumber(min)) {
                return [min];
            }

            // Populate the intermediate values
            pos = roundedMin;
            while (pos <= roundedMax) {

                // Place the tick on the rounded value
                tickPositions.push(pos);

                // Always add the raw tickInterval, not the corrected one.
                pos = correctFloat(pos + tickInterval);

                // If the interval is not big enough in the current min - max range to actually increase
                // the loop variable, we need to break out to prevent endless loop. Issue #619
                if (pos === lastPos) {
                    break;
                }

                // Record the last value
                lastPos = pos;
            }
            return tickPositions;
        },

**Comment by oysteinmoseng** [comment]
Thank you for reporting this, though I'm not sure if this is by design. It seems to always have behaved this way, and this is an undocumented internal function. Do you have a chart that displays wrong ticks?

@TorsteinHonsi Any input?

**Comment by hitlcy** [comment]
Please check the simple setup 
 yAxis:[{
   min:2,
   max:10,
   tickInterval:4
   }],
see even I setup the min = 2 the yAxis is still starting from 0.
 
https://jsfiddle.net/hitlcy/mora1xo1/.

**Comment by TorsteinHonsi** [comment]
As documented in http://api.highcharts.com/highcharts/yAxis.min : 

> If the startOnTick option is true, the min value might be rounded down.

I'll add to the docs that this is true by default.

See https://jsfiddle.net/highcharts/mora1xo1/1/
