### ISSUE TITLE
Drilldown Issue: Unable to drilldown onClick of count shown on ColumnBar.

### ISSUE THREAD

**Issue by rohitszone** [highcharts/highcharts#6028]
#### Expected behaviour
Drilldown should work.

#### Actual behaviour
Attached snapshot shows stacked column bar which can drill down onClick. I.e the mouse pointer/cursor changes to clickable pointer over the column bar however the same doesn't happen when hovered over the count hence on click of count the drilldown doesn't happen.

Can you please suggest something to fix it? 

#### Affected browser(s) 
IE/Chrome

![image](https://cloud.githubusercontent.com/assets/1780659/20585389/01dd86e2-b24f-11e6-899b-5724c56b5a44.png)

**Comment by pawelfus** [comment]
Hi @rohitszone 

Could you recreate issue in jsFiddle? Our demo works fine, please take a look: http://www.highcharts.com/demo/column-drilldown

**Comment by rohitszone** [comment]
You demo is a regular column bar with drilldown, this works fine.

The thing that I've developed in stacked column bar with drilldown for each stack, which has the count embedded inside stack as shown in the image. The click on count label doesn't work.

Anyhow let me get you the issue[May not be] in jsFiddle.

Cheers.

**Comment by pawelfus** [comment]
Thanks! I just modified the original demo with stacks: http://jsfiddle.net/hks4qv0p/ I am not sure about the "count label". I assume you mean just label on the column (like highlighted `143` in your demo).

**Comment by rohitszone** [comment]
Awesome, let me verify if I have put dataLabels.useHTML.

I think you have found the issue, let me confirm this after looking at the code tomorrow.

Many thanks, Mate!

**Comment by rohitszone** [comment]
Yep, that was the problem.

**Thanks for help!**
