### ISSUE TITLE
After drilldown, drillup and another drilldown original column visible in the background

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6029]
#### Expected behaviour
After clicking a column, going back, clicking another one, there should be only drilldown series visible.

// Works ok in 5.0.3
http://jsfiddle.net/x7zg9v1d/

#### Actual behaviour
After clicking a column, going back, clicking another one, there is a column (from original chart, which triggered first drilldown) in the background.
![screen shot 2016-11-24 at 10 13 02](https://cloud.githubusercontent.com/assets/19593179/20592574/9f85d4a6-b22e-11e6-8aa3-d9c96938dcdb.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/column-drilldown/

1. Click one column to trigger drilldown
2. Click back button to trigger drillup
3. Click another column.
4. Notice that column from chart is in the background.

**Comment by pawelfus** [comment]
Thanks for reporting!

We have a report for this already: #6017
