### ISSUE TITLE
Highcharts map hover state color in not removed on mouse out when color set as string

### ISSUE THREAD

**Issue by bkozera** [highcharts/highcharts#6030]
#### Expected behaviour
This is official example with hover color set as hex value (''#a4edba'):
http://jsfiddle.net/gh/get/jquery/2/highcharts/highcharts/tree/master/samples/maps/plotoptions/series-states-hover/

#### Actual behaviour
When we change hover color to a name like 'red' it will not be removed on mouse out:
http://jsfiddle.net/hepu37hc/

#### Affected browser(s)
Chrome, 54.0.2840.7 and Firefox 49.02 on OS X El Capitan (10.11.6)

**Comment by bkozera** [comment]
If this is desired behaviour then I suggest updating docs here:
http://api.highcharts.com/highmaps/plotOptions.series.states.hover.color

**Comment by oysteinmoseng** [comment]
Worked in 4.2.7: http://jsfiddle.net/hepu37hc/1, but note that you don't get the fade animation of the color with named colors, making it a bit jittery. This is documented here http://www.highcharts.com/docs/chart-design-and-style/colors.

Workaround: http://jsfiddle.net/hepu37hc/2/
