### ISSUE TITLE
Changing solidgauge color on Point.update() in Highcharts v5.0.4

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6032]
#### Behaviour
In solidgauge chart using the newest version of Highcharts (v5.0.4), updating point’s value with Point.update() function does not show correct color defined by yAxis.stops. With v5.0.3 everything works fine.

#### Live demos with steps to reproduce
http://jsfiddle.net/6bsjg97q/ - v5.0.3 (working)
http://jsfiddle.net/6bsjg97q/1/ - v5.0.4 (not working)

**Comment by pawelfus** [comment]
Responsible commit: a4135b5

**Comment by larsac07** [comment]
Related: #6017 (same commit where animation was refactored)

**Comment by TorsteinHonsi** [comment]
Closed by 13ec61636ff5a4e2
