### ISSUE TITLE
Series color zone does not work with axes with custom size

### ISSUE THREAD

**Issue by GabrielMarcilio** [highcharts/highcharts#6034]
In my application i want to display two y axes side by side (as displayed in the associated demo).

To do that i configure the axes offset, left and width.

This works fine until i set the curve color zones. When i set then, the curve segments are not draw (or are drawn in the wrong position)

This seems to be something related with the clipping area of the curve draw not taking into account the custom axis configuration that i set.

I can only reproduce the issue if set an arbitrary width for the axis (using the automatic axes arrangement where the y axes are drawn one over the other, then the color zones works fine),

#### Live demo with steps to reproduce
http://jsfiddle.net/100yqmrx/3/

I am using Highstock version 4.2.7, but this seems to be reproducible in the current version as well.

**Comment by larsac07** [comment]
Simplified fiddle: http://jsfiddle.net/larsac07/cbzuytpg/

**Comment by henrikskar** [comment]
It looks like it has to do with the axis width not being respected all the way through the code. With inversion, points are correctly calculated, but clips and tooltips are not.
