### ISSUE TITLE
Dynamic areaspline chart glitch

### ISSUE THREAD

**Issue by MaadMax** [highcharts/highcharts#6036]
#### Expected behaviour
The behavior of the Highchart example dynamic spline chart, but in "aeraspline".
http://jsfiddle.net/jq80r5k9/1/ (no glitch if 'spline')

#### Actual behaviour
To test, play with 'type' on line 11 and switch value between 'spline' and 'aeraspline'.
http://jsfiddle.net/jq80r5k9/ (strange glitch if 'aeraspline')

#### Affected browser(s)
Chrome, FF (not tested on other browsers).

**Comment by pawelfus** [comment]
It looks like a duplicate of #5892
