### ISSUE TITLE
Legend Name on click

### ISSUE THREAD

**Issue by arth1992** [highcharts/highcharts#6038]
Hello,

I want to know if there any options to get legend name on click of stacked column chart. 
For example on this chart :  http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/column-stacked/

On clicking one of these column how do i get legend name i.e ''John'.

**Comment by oysteinmoseng** [comment]
Assuming you are referring to the `point.click` event, you can use `this.series.name`: http://jsfiddle.net/14e2sz7v/

**Comment by arth1992** [comment]
thank you got it.
