### ISSUE TITLE
Display column chart automaticlly with relevant zoom 

### ISSUE THREAD

**Issue by royigoldi** [highcharts/highcharts#6039]
Hi,

I wan't to know how I can implement column chart to display automaticlly in the relevant zoom:

the actual chart:

![image](https://cloud.githubusercontent.com/assets/20413250/20646510/f1dd01e2-b482-11e6-96e1-25bed719fcfb.png)

but beacuse one catagory has a lot of values, the user doesn't see the small catagories, my expected behaivor is to diaply automaticlly in this mode (i did zoom on x axis):

![image](https://cloud.githubusercontent.com/assets/20413250/20646523/436cab20-b483-11e6-97c9-c573ad5d6846.png)

Thanks,
Royi

**Comment by pawelfus** [comment]
Hi @royigoldi 

This is our issue tracker, for support related questions please check [how we can help you](http://www.highcharts.com/support).

Yo answer your question: you can use [`yAxis.min`](http://api.highcharts.com/highcharts/yAxis.min) or [`Axis.setExtremes(min, max)`](http://api.highcharts.com/highcharts/Axis.setExtremes).
