### ISSUE TITLE
Boost module - Not calculating dataMin and dataMax when min and max are set

### ISSUE THREAD

**Issue by hkostia** [highcharts/highcharts#6041]
#### Expected behaviour
Possibility to toggle calculation of dataMax and dataMin when boost module enabled.

#### Actual behaviour
If min/max are set, dataMax/dataMin is not calculated.

#### Live demo with steps to reproduce
http://jsfiddle.net/ry4quL3r/

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
In order to cut performance times, the boost module prevents excessive looping over the data set. When min and max is set, it doesn't have to inspect the data in order to find the appropriate axis extremes, so it skips this altogether. That's why it's faster :)

**Comment by hkostia** [comment]
Yes, that's true. There can be use cases where you need to set the min and max (predefined min and max for some data so that the scale is always same not depending on the actual data) but want to still use dataMin and dataMax do something else (for example, zoom in to the data that's shown).

For the time being, using this:
``
Highcharts.Series.prototype.hasExtremes = function() {
  return false;
};
``

**Comment by TorsteinHonsi** [comment]
> Now patched using this

That works, but also affects performance. In the future we may consider writing a simpler version of `getExtremes` for use cases like this - one that is not used internally but only on direct calls.
