### ISSUE TITLE
Strange behavior when initializing Highcharts without series.

### ISSUE THREAD

**Issue by SamMousa** [highcharts/highcharts#6043]
#### Expected behaviour
If I initially have no series in my chart and then add 1 I expect it to get the type specified in the series, if any.

#### Actual behaviour
A bar series becomes a column series.

#### Live demo with steps to reproduce
http://jsfiddle.net/wv76uym6/1/

Wait 1 second, the dynamic series is added with a delay.

#### Affected browser(s)
Chrome,  Firefox

**Comment by oysteinmoseng** [comment]
Currently, `addSeries` does not automatically invert the chart for bar series. You would have to call      

    chart.update({
        chart: { 
            inverted: true 
        }
    });

before adding the series, or initialize the chart with `inverted: true` for this to work. Example: http://jsfiddle.net/wv76uym6/2/

**Comment by SamMousa** [comment]
Thanks for the workaround; yet I don't feel that this should be closed.

If the chart at any point in time is empty, adding a series of a specific type should just work.

Furthermore, if a bar series is actually just a column series on an inverted chart, why not remove the bar type altogether? 
Wouldn't it be more intuitive if there are less `types`, and instead the `inverted` property is used for changing any cartesian series?

**Comment by oysteinmoseng** [comment]
Reopening to promote further discussion.

**Comment by TorsteinHonsi** [comment]
> Furthermore, if a bar series is actually just a column series on an inverted chart, why not remove the bar type altogether? Wouldn't it be more intuitive if there are less types, and instead the inverted property is used for changing any cartesian series?

Absolutely. This was a decision I made very early before Highcharts version 1, but if we remove it now we will break stuff for users all over the place.

**Comment by SamMousa** [comment]
It could be deprecated (optionally with a message in the console. It is not
a lot of work to fix as part of moving to the next major release?

**Comment by TorsteinHonsi** [comment]
Yes it could, but I think it's not worth the inconvenience for our existing users. Bar charts are so common that this would be a major and unnecessary  hassle for a lot of people out there.

**Comment by SamMousa** [comment]
Well it's up to you in the end; I don't like the inconsistency and even though it is a shortcut that indeed helps lower the time to production initially, it has already hurt me more than it helped.

For a developer it doesn't really matter what way the chart is initialized (if that takes a few more lines of configuration it's fine), but getting weird behavior because the API is inconsistent is a lot more annoying.

Anyway, it's your project so if you prefer to keep it like this feel free to close the issue :)
