### ISSUE TITLE
addPoint animation in an areaspline chart

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#6044]
#### Expected behaviour
Working animation in Highcharts 5.0.3 for an areaspline chart (during addpoint)
http://jsfiddle.net/mchc59nb/3/

#### Actual behaviour
In 5.0.4 the animation looks as it is broken.
http://jsfiddle.net/mchc59nb/2/

**Comment by sebastianbochan** [comment]
Fixed in the master branch:
- http://jsfiddle.net/xcdzqdpe/
