### ISSUE TITLE
series.update() turns es6 classes to objects in userOptions

### ISSUE THREAD

**Issue by yogevyuval** [highcharts/highcharts#6046]
#### Expected behaviour
userOptions should keep their type when they are es6 classes.

#### Actual behaviour
I tried putting an object in a series userOptions like so:

`chart.addSeries({
  ...,
  mySpecialOption: myObject
})`

where myObject is an instance of class I created like following (es6 syntax):

`class SomeClass {
constructor() {
}
...
}
myObject = new SomeClass();`

So putting the option works fine, but when I call series.update() mySpecialOption becomes a different object of type 'Object'. Then my original instance is gone and i cannot use it as planned. :(

I think it is probably caused by H.merge or something in that area...

**Comment by TorsteinHonsi** [comment]
> I think it is probably caused by H.merge or something in that area...

Yes, you're probably right, the object is mutated and stored in the series object itself. A workaround would be to pass a copy of the configuration object to `addSeries`.

**Comment by yogevyuval** [comment]
I did not quite understand your workaround. Can you provide a code sample? 

I'm passing the instance of my es6 type to addSeries

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard

**Comment by yogevyuval** [comment]
Any update on this one?
@jon-a-nygaard @TorsteinHonsi

**Comment by jon-a-nygaard** [comment]
@yogevyuval Apologies for the late reply.
There is a possible workaround for you to [override `Highcharts.isObject`](http://jsfiddle.net/g6tx4n96/4/), which is used in the `merge` function, to have it return false when it is a class. 

**Internal Note:**
In stead of modifying `isObject`, it is probably better to check if the object is a class in the merge function around [L449 in Utilities.js](https://github.com/highcharts/highcharts/blob/master/js/parts/Utilities.js#L449-L451)

**Comment by yogevyuval** [comment]
@jon-a-nygaard Thanks for the reply.
While overriding isObject is possible this seems like a very patchy solution :) I prefer to stick with my current patch...

A fix to the H.merge function seems like a good idea, would love to see it :) es6 classes are becoming very popular and I think it's necessary that Highcharts will handle them correctly.
