### ISSUE TITLE
pointFormat HTML classes only work with double quotes. Styled Mode

### ISSUE THREAD

**Issue by KieranDotCo** [highcharts/highcharts#6048]
#### Expected behaviour
Adding a point format of : - 
`pointFormat:"<span class='highcharts-color-{point.colorIndex}'>●</span> <b>{point.x}</b>"` 
should show the dot in the color of the series.

#### Actual behaviour
Dot actually shows in a single color for all series.

#### Live demo with steps to reproduce

http://jsfiddle.net/Lze1tvha/

If you use double quotes on the class in the example below it works
`pointFormat:'<span class="highcharts-color-{point.colorIndex}">●</span> <b>{point.x}</b>'` 
http://jsfiddle.net/hz3wspe5/

#### Affected browser(s)
Chrome MacOs (Possibly others not checked)

**Comment by TorsteinHonsi** [comment]
This applies to all formats that are passed through our SVG pseudo-HTML parser. If you need double quotes in your config (for true JSON compliance), you can escape the double quotes in the pseudo-HTML:

```js
pointFormat:"<span class=\"highcharts-color-{point.colorIndex}\">●</span> <b>{point.x}</b>"
```

**Comment by KieranDotCo** [comment]
Ah okay super, thanks @TorsteinHonsi.
