### ISSUE TITLE
Pie chart 'Expected arc flag' error

### ISSUE THREAD

**Issue by SuperOleg39** [highcharts/highcharts#6051]
#### Expected behaviour
Hello!
When I many times clicked on different Pie chart pieces, I catched many errors.
But the chart continues to work steadily.

#### Actual behaviour
Error message:
`Error: <path> attribute d: Expected arc flag ('0' or '1'), "…647399097473 0 0.004450126317012…".`

#### Live demo with steps to reproduce
You can see it on highcharts demo page:
http://www.highcharts.com/demo/pie-basic

#### Affected browser(s)
Google Chrome 54.0.2840.99 m (64-bit)

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

I can see errors too, but interestingly, not the same as you. My errors are
`VM200 highcharts.js:3674Error: <path> attribute d: Unexpected end of attribute. Expected number, "M".`

They can be traced back to d9c7781

**Comment by TorsteinHonsi** [comment]
Can you verify that the issue is fixed at http://jsfiddle.net/highcharts/hp66m188/?

**Comment by SuperOleg39** [comment]
Yes, issue is fixed! :)

**Comment by karthiknwo** [comment]
@TorsteinHonsi Can you please mention what caused and what the fix is? I am seeing this when I try to display a dialog when someone clicks on a slice in the pie chart. Any help would be appreciated. Please let me know if you need sample code.

**Comment by SuperOleg39** [comment]
@karthiknwo Just update the library version :)
