### ISSUE TITLE
Bubble Chart allowPointSelect not working

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6054]
#### Expected behaviour
Bubble chart allowPointSelect should work correctly. Selection should be applied irrespective of whether data labels are enabled or disabled.

#### Actual behaviour
Bubble chart allowPointSelect is not working properly. It only works if data labels are enabled and the click is done on data labels.

#### Live demo with steps to reproduce
Without Data Labels http://jsfiddle.net/jz1dooub/
With Data Labels (click on data labels for selection to work) http://jsfiddle.net/jz1dooub/1/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @sagargurtu 

Thanks for reporting!

It's a regression after 9a9b4a3

**Workaround:**
Set `markerAttribs` to null in the prototype:

```javascript
Highcharts.seriesTypes.bubble.prototype.markerAttribs = null;
```

*Internal note:*
I will try to find a solution which will work properly in the CSS na JS modes.
