### ISSUE TITLE
Bubble Shadow weird behaviour

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6055]
#### Expected behaviour
Bubbles on bubble chart should render correctly.

#### Actual behaviour
Bubble shadow moves between points when clicking on two data labels back and forth.

#### Live demo with steps to reproduce
http://jsfiddle.net/jz1dooub/2/
1. Click on bubble 24.7 data label (not bubble).
2. Click on bubble 14.7 data label (not bubble).
3. Now click on these two data labels back and forth.
4. Check that bubble shadows are moving between points.

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thanks again!

I also realized this when checking your previous report, it's a regression after d83c4b2

**Comment by sagargurtu** [comment]
Hi,

This issue is also present in line, scatter and area charts. Basically all those charts with marker points.
