### ISSUE TITLE
Spider Web Chart area fill not working

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6057]
#### Expected behaviour
The area for spider web chart should be filled according to the options.

#### Actual behaviour
Even though the area fill for spider web chart has been enabled, it disappears after the chart is fully rendered.

#### Live demo with steps to reproduce
http://jsfiddle.net/k04mxmwb/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thank you very much! We really appreciate your feedback.

And here comes another regression: 0a92202
