### ISSUE TITLE
unexpected yAxis category

### ISSUE THREAD

**Issue by hotohoto** [highcharts/highcharts#6063]
#### Expected behaviour
There should not be a 22 at the top of yAxis

#### Actual behaviour
There is 22 at the top of yAxis.

#### Live demo with steps to reproduce
http://jsfiddle.net/hotohoto/jnatbb4t/

#### Affected browser(s)
I have tested it with chrome.

**Comment by sebastianbochan** [comment]
Duplicate of #4385
