### ISSUE TITLE
Flags `onSeries` property dependency on series sort order

### ISSUE THREAD

**Issue by havgry** [highcharts/highcharts#6066]
#### Expected behaviour
That the flags `onSeries` property works regardless of the order of the series - just like the `linkedTo` property does. Or at the very least the documentation should state the dependency on the series order.

#### Actual behaviour
The flag is not drawn on the series as expected.

#### Live demo with steps to reproduce
Working (flag is placed on the series): http://jsfiddle.net/keavhtnw/
Broken (flag is not placed on the series): http://jsfiddle.net/keavhtnw/1/

Fun fact: Toggling either of the series or resizing the chart fixes the issue.

#### Affected browser(s)
All (not browser specific).

**Comment by pawelfus** [comment]
Thanks for reporting the issue!

At this moment, if flag series can not find related series then it's rendered on xAxis. After redraw, base-series exists so it's positioned correctly.
