### ISSUE TITLE
Styled mode: bubble halo stays for ever per series

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6067]
#### Expected behaviour
Halo removed after state of a point changes.

#### Actual behaviour
Halo stays and hovering all points makes halos for all points.

#### Live demo with steps to reproduce
http://jsfiddle.net/7Lw1esye/
1. Hover over all points - halos are staying
2. Zoom to any 3 points
3. Halo is not updated after zoom

**Comment by pawelfus** [comment]
It's a general issue, not related to styled mode. Demo: http://jsfiddle.net/7Lw1esye/3/

**Comment by pawelfus** [comment]
*Internal note:*
Bubble series resizes the halo to the original bubble size, not to the size == 0. That causes the halo to remain after resize (actually, every halo stays there, but the ones size == 0 are not visible). 

I think we have two (at least) possible solutions to fix this:

- after the animation, really hide the halo, e.g.:

			halo.animate({
				d: point.haloPath(0)
			}, {
				complete: function ()  {
					halo.attr({
						d: ''
                                                // OR: visibility: 'hidden' and restore this above
					});
				}
			}); // Hide

- move halo logic to the separate method, so bubble series can overwrite this. That may not be as bad as it seems, perhaps it will be easier to fix some other issues, for example #5746, #4198 and #3533 (so we can call this method in other places, to update the halo).
