### ISSUE TITLE
DataClasses not in legend - styles mode

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6069]
#### Actual behaviour
Legend should be displayed like in non-styled mode.

#### Live demo with steps to reproduce
http://jsfiddle.net/1sg7tepw/

In the styles mode, colors are not applied in the legend.

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Data class colors shouldn't be set directly in styled mode - see http://jsfiddle.net/gh/get/jquery/3.1.1/highcharts/highcharts/tree/master/samples/highcharts/css/map-dataclasses/

**Comment by sebastianbochan** [comment]
Thanks!

**Comment by rbeasse** [comment]
This works great for the legend, however I noticed the class isn't getting applied to the on hover dot.

From the fiddle:
![hover](https://cloud.githubusercontent.com/assets/1575910/20904127/c9217c60-bb03-11e6-819a-29ef073ea3bd.png)

**Comment by oysteinmoseng** [comment]
Reopening for attention.

Isn't there also an issue of hovering over the legend items causing excessive brightening of all map areas? Or is this a feature?

**Comment by TorsteinHonsi** [comment]
> Isn't there also an issue of hovering over the legend items causing excessive brightening of all map areas?

Yes, that looks like a bug. It is supposed to dim all areas except the one you're inspecting, like in the [styled mode column chart](http://jsfiddle.net/gh/get/jquery/3.1.1/highcharts/highcharts/tree/master/samples/highcharts/css/axis/).
