### ISSUE TITLE
Panning the map up and down

### ISSUE THREAD

**Issue by vipera** [highcharts/highcharts#6070]
Hi, I'm trying out the Highmaps library and have run into a usability issue which could be a bug (I'm completely new to Highmaps). Here's the report:

#### Actual behaviour
Panning along the y-axis doesn't happen when clicking and dragging after zooming in, while the x-axis can be panned normally.
#### Live demo with steps to reproduce
Any of the official Highmaps demos that use the current master, e.g. [this fiddle](http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/maps/demo/all-maps/).

#### Affected browser(s)
Chromium 53, Firefox 50

**Comment by vipera** [comment]
After some more testing, I realized it only happens when zooming in using the mouse wheel - using the zoom buttons it works just fine.

**Comment by pawelfus** [comment]
Hi @vipera 

Thank you for reporting the issue! That info with zooming by mouse wheel is the key part here.

**Workaround:**
Use the snippet below, before creating any of charts:

    (function (H) {
      H.wrap(H.Chart.prototype, 'pan', function (proceed) {
        H.each(this.yAxis, function (axis) {
          axis.fixTo = null;
        });
        proceed.apply(this, Array.prototype.slice.call(arguments, 1));
      });
    })(Highcharts);

Working demo: http://jsfiddle.net/vserez4y/

*Internal note:*
Why `axis.fixTo` is not cleared in the wrap for `render` ?

**Comment by vipera** [comment]
Hi @pawelfus !

Thanks for the info, the fiddle and fix work wonderfully!

**Comment by ashnewport** [comment]
This is broken in version `8.0.0`. As the demo by @pawelfus uses the latest code therefore it does not work.

Workaround (use version [`7.2.1`](https://code.highcharts.com/maps/7.2.1/highmaps.js)) and fix noted in https://github.com/highcharts/highcharts/issues/12671
