### ISSUE TITLE
Highstock: axis update changes default settings

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6071]
#### Expected behaviour
Keep settings that are not being updated.

#### Actual behaviour
Changes not mentioned in an update options.

#### Live demo with steps to reproduce
http://jsfiddle.net/zqxtd4mb/1/

Press any button and position of yAxis labels will be changed, but update has nothing to do with labels.

**Comment by TorsteinHonsi** [comment]
Most likely it goes wrong in the [autoLabelAlign override](https://github.com/highcharts/highcharts/blob/v5.0.5/js/parts/StockChart.js#L176-L198). This code is supposed to make the labels of the _first series_ align within the plot area.

**Comment by KacperMadej** [comment]
@pawelfus  It seems like there should be `apply` instead of `call` on [this line](https://github.com/highcharts/highcharts/commit/a895f326f828f05ce43117742e2ac8e69921a6f6#diff-7145d81a7a733d70c302f4ce750d0bfeR213).
