### ISSUE TITLE
Problem with tooltip when polygon and scatter are present on the same chart (with boost module)

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6073]
#### Behaviour
When series with type coming from highcharts-more.js (e.g. polygon) is present on a chart along with scatter series where number of points exceeds boostThreshold value, tooltip does not show up. Disabling boostThreshold (or changing to the number lower than number of points) or getting rid of polygon series resolves the problem.

#### Live demos
https://jsfiddle.net/d_paul/1d4odb7s/ - turboThreshold = 1000, number of points = 1000 (tooltip does not work)
https://jsfiddle.net/d_paul/1d4odb7s/1/ - turboThreshold = 1000, number of points = 999 (tooltip does work)

**Comment by mattjvincent** [comment]
Just to add some more information, the tooltips do actually work with the number of points exceeding the threshold and if a series of type "line" is used.  For the tooltips to show, you have to hover over the line to activate the tooltip.  Than the tooltips will also show on the scatter points:

[https://jsfiddle.net/1d4odb7s/2/](https://jsfiddle.net/1d4odb7s/2/)

**Comment by TorsteinHonsi** [comment]
Thanks for reporting. We're currently completely rewriting the boost module to WebGL rendering, so we'll put this on hold.

**Comment by brian428** [comment]
@TorsteinHonsi is there any status update or ETA on when the WebGL version of the Boost module will be available?

**Comment by TorsteinHonsi** [comment]
Hi @brian428, the WebGL version of the Boost module is out as of Highcharts v5.0.9.

**Comment by brian428** [comment]
@TorsteinHonsi Great! Does that mean this demo is now using the WebGL boost (since it is loading the latest via code.highcharts.com)? http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/boost/scatter

**Comment by TorsteinHonsi** [comment]
Yes it does.
