### ISSUE TITLE
Why does borderWidth behave differently when its a string?

### ISSUE THREAD

**Issue by VictorioBerra** [highcharts/highcharts#6075]
#### Expected behaviour
Border should not be INSIDE the chart area.

#### Actual behaviour
Border is inside the chart area when chart.borderWidth is a string.

#### Live demo with steps to reproduce
http://jsfiddle.net/Lord_Zero/8jeusy2n/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
According to the API, it should be set as number: [`chart.borderWidth`](http://api.highcharts.com/highstock/chart.borderWidth).

And it works that way, because we don't parse this value:

```javascript
                // Presentational
                chartBorderWidth = optionsChart.borderWidth || 0;
                mgn = chartBorderWidth + (optionsChart.shadow ? 8 : 0);
```
And as we know, in Javascrtipt: `"10" + 0 = "100"` :)
