### ISSUE TITLE
How does Highmaps interactive with colorAxis?

### ISSUE THREAD

**Issue by Shu-Ji** [highcharts/highcharts#6078]
like echarts's datarange:

http://jsfiddle.net/bh20077/xcvvamxr/

Notice the left of the jsfiddle page, the datarange("colorAxis" in Highcharts), user can drag the high and low handle to view states.

**Comment by sebastianbochan** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
