### ISSUE TITLE
setSize and hidden container

### ISSUE THREAD

**Issue by slawekkolodziej** [highcharts/highcharts#608]
When a chart is rendered for the first time it doesn't matter if the container is hidden via "display: none" or not, but it does when you try to use setSize.

Take a look at this example: http://jsfiddle.net/hfrntt/t2HF7/14/

**Comment by cxytomo** [comment]
I doesn't work for when I use new Highcharts.Chart({option}) instead of $('#id').highcharts({}); After reflow(), the chart is till little bit wider then the container. And I want the chart to be responsive. Anyone help me?

**Comment by cxytomo** [comment]
@slawekkolodziej Hi, I come across this problem and tried every solution I can find. This morning I fixed it. I don't hide the container by 'display:none'. instead, I set 'position: absolute;'. I tried 'top:-9999em' but failed. So don't change the position,' top:0;left:0'. use'opacity and z-index'to hide and show the element you want. This is the solution I find and it perfectly works for me.
