### ISSUE TITLE
Bad rendering when series data is an empty object

### ISSUE THREAD

**Issue by lucasmauro** [highcharts/highcharts#6080]
#### Expected behaviour
When series.data contains an empty object as a value, this value is not rendered.

#### Actual behaviour
When series.data contains an empty object as a value, a 0 floats around the chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/k0botpL0/1/

**Comment by oysteinmoseng** [comment]
Thank you for reporting. Workaround: Use null points - [example](http://jsfiddle.net/k0botpL0/2/).

Issue since 4.2.7.

**Comment by TorsteinHonsi** [comment]
Fails since 7903240

**Comment by sebastianbochan** [comment]
@TorsteinHonsi the commit looks like promising, but unfortunately it breaks the treemap labels. #4812 (test 1466).

**Comment by TorsteinHonsi** [comment]
You're right. Reopening this. I think instead we need to go back to the fix for #3169 and move that logic to the drilldown module, since it's the only place where we expect a null column to have a shape. It also shaves off some bloat from the core.

**Comment by sebastianbochan** [comment]
_Internal note_
I think that one of possibly solutions is checking `point.plotY` and then set a null for y param in the point `init` function.

**Comment by sebastianbochan** [comment]
The issue seems to be solved in since HC v7.0.0.

Demo:
- http://jsfiddle.net/BlackLabel/7Lktqdva/

Please reopen if problem will be valid.
