### ISSUE TITLE
Maps breaks on redraw with animations=true using src files

### ISSUE THREAD

**Issue by YusselPP** [highcharts/highcharts#6082]
#### Expected behaviour
Be able to set option "chart.animation = true"

#### Actual behaviour
Setting "chart.animation = true" and "dataLabels.enabled = true" using src files i.e. "https://code.highcharts.com/highcharts.src.js" throws: Uncaught TypeError: Cannot create property 'complete' on boolean 'true'

#### Live demo with steps to reproduce
Try to zoom in and zoom out the map many times and you will see errors in the console.

http://jsfiddle.net/1aenwcsL/2/

**Comment by jon-a-nygaard** [comment]
Thanks for reporting!

Internal Note: Appeared in v5.0,0

**Comment by TorsteinHonsi** [comment]
Fixed in v5.0.6, by dada0ff5704b36ad3dda4e65eb15bd8227d49a05.

**Comment by dukarc** [comment]
Any options in V5 Vanilla for a workaround?  Patching Highcharts is not an option for us at the moment

**Comment by KacperMadej** [comment]
@dukarc The issue was fixed in v5.0.6. Which version are you using that requires a workaround? I should be able to provide you a wrapper workaround if you could provide a version number or a live demo in JSFiddle.

**Comment by dukarc** [comment]
@KacperMadej thanks for getting back to me.  Apologies for the delay on my part ... just caught this message.

We are on v5.0.2

**Comment by KacperMadej** [comment]
@dukarc Here's a demo with the fix applied for version 5.0.2 as a wrapper / override:
http://jsfiddle.net/2kwvykrz/

**Comment by dukarc** [comment]
Great ... thanks @KacperMadej!
