### ISSUE TITLE
Updating point.x in stacking column chart doesn't work

### ISSUE THREAD

**Issue by YusselPP** [highcharts/highcharts#6083]
#### Expected behaviour
Render one point above the other

#### Actual behaviour
Both points render in the same spot and a blank space appears below them

#### Live demo with steps to reproduce
http://jsfiddle.net/bhjfer9x/

#### Affected browser(s)
Chrome 54

**Comment by jon-a-nygaard** [comment]
Internal Note: [Simplified example](http://jsfiddle.net/jon_a_nygaard/bhjfer9x/2/)

**Comment by jon-a-nygaard** [comment]
Hi @YusselPP, when stacking is enabled data must be sorted in ascending X order, like in [this example](http://jsfiddle.net/jon_a_nygaard/bhjfer9x/3/). I have [updated the API](http://api.highcharts.com/highcharts/plotOptions.series.stacking) with the missing information.

**Comment by YusselPP** [comment]
Hi @jon-a-nygaard, my chart use dynamic updates with Point.update method. So, your solution is not applicable for me. What should I do to successfully update Point.x without issues?

**Comment by TorsteinHonsi** [comment]
In spite of the warning about unsorted data, this actually [worked in v4.1.8](http://jsfiddle.net/bhjfer9x/4/), but broke in v4.1.9. Offending commit: 8d8cbee.

**Comment by TorsteinHonsi** [comment]
Another observation: If the X values are ascending, it works: http://jsfiddle.net/bhjfer9x/6/. But if we swap number 1 and 2, it breaks: http://jsfiddle.net/bhjfer9x/7/

**Comment by TorsteinHonsi** [comment]
> What should I do to successfully update Point.x without issues?

Removing and re-adding a new point works around the ordering issue: http://jsfiddle.net/bhjfer9x/8/
