### ISSUE TITLE
Floating point/rounding issue

### ISSUE THREAD

**Issue by 925dk** [highcharts/highcharts#6085]
See:

http://jsfiddle.net/68f9b056/1/

It seems tick mark values occasionally are being incorrectly rounded/calculated, resulting in values such as 0.00000000000000022 shown (or similar small values).

I'm guessing this is a recent regression, as I've never seen it before.

**Comment by jon-a-nygaard** [comment]
Thanks for reporting!

Internal Note: regression since 5.0.3
