### ISSUE TITLE
 e.doDrilldown is not a function

### ISSUE THREAD

**Issue by laopunk** [highcharts/highcharts#6086]
#### Expected behaviour
being able to use highcharts-drilldown in multiple instances

#### Actual behaviour
exception raised `e.doDrilldown is not a function`  when the drilldown actually works fine.
This happens in my node environment, where each graph is in its own module and unaware of the other graphs present. As soon as I have two modules using highcharts-drilldown I get this error message.
Managed to reproduce it hackily on jsfiddle, by simply importing the library twice.
No idea why this causes a pb, but could there be a way for the lib to determine if another instance has already been loaded ?

#### Live demo with steps to reproduce
http://jsfiddle.net/m3bvp13h/

Open the console and look at messages as soon as you drill down through the columns.
This error seems to be only triggered when clicking on the bars, not on the group name on the axis. 

#### Affected browser(s)
Chrome on osx

**Comment by oysteinmoseng** [comment]
In general we don't support loading the library or modules multiple times. Perhaps adding a simple test to the libraries to do nothing if already included is something we should consider.

Using Javascript you could test with e.g. `if (Highcharts.Chart.prototype.addSeriesAsDrilldown)` to see if the drilldown module has been included, and load it otherwise.

**Comment by jon-a-nygaard** [comment]
@laopunk You can use a bundler (for instance Browserify), to avoid Highcharts being set on the `window` object. Then you should be able to have as many instances of Highcharts as you want. Each instance will also have to load  the modules that it needs.

**Comment by laopunk** [comment]
Hi @jon-a-nygaard 
This indeed the right approach, and actually the one I'm using :-)
Webpack is my bundler, and it does include the library only once in the final output, the error happens only when a second module makes use of that lib. In a nutshell, it is not loaded twice, but used twice, if that makes sense ...

But like I said, it is working as such, it just generates an unnecessary error. I am not blocked, just puzzled ... all the more as it is not generating the error when you click on the axis title ... 

Thanks for your help,
David

**Comment by brandontineo** [comment]
Hi @laopunk I am still facing this issue. Did changing the configurations in Webpack bundler make this error stop appearing for you?

**Comment by laopunk** [comment]
Hi @brandontineo 
The issue is still very much present, and upgrading to 5.0.10 didn't help either.

I looked at your SO post and this solution is working. I will update it with a bit more info to help the community.

@jon-a-nygaard it seems that importing some of the modules multiple times causes all sorts of issues: errors when redrawing, polar columns intermittently displaying, drilldown alerts, etc ...
Since each Highchart module seems to alter/enhance to the Chart prototype, I would advocate for an initial check within the Highchart module itself making sure such load has snot been carried out previously. 

See examples of the workaround:
http://stackoverflow.com/questions/42076332/uncaught-typeerror-e-dodrilldown-is-not-a-function-highcharts

**Comment by urvashimehra** [comment]
i am facing same issue and had no solution

**Comment by pawelfus** [comment]
Hi @urvashimehra 

That means you either use quite old version of Highcharts (solution: upgrade to v8) or this is a different issue. If this is some other bug, please report this following our bug-report template. In case of problems with setting up a demo, please contact our [support team](https://www.highcharts.com/blog/support/) first.
