### ISSUE TITLE
`minPointLength` shifts all following values in waterfall

### ISSUE THREAD

**Issue by hon2a** [highcharts/highcharts#6087]
#### Expected behaviour

When I use `minPointLength` in a waterfall chart, it should force a minimum (visual) size of all columns, but it shouldn't shift the starting points of following columns.

#### Actual behaviour

Using `minPointLength` in a waterfall actually shifts all of the following columns, putting them in (sometimes wildly) different places than where they should be and possibly distorting the shape of the whole series to be completely misrepresentative of the data it visualizes.

#### Live demo with steps to reproduce

* [regular demo](http://jsfiddle.net/gwkg19t6/) - note how the 90% column at the end is bigger than the 100% column at the beginning (it's also exhibiting some weird rendering bug making column bases shifted up, but that's not the concern of this ticket)
* [zero adjustments demo](http://jsfiddle.net/1qu32g9n/4/) - this prevents me from making waterfall zero adjustments visible using `minPointLength: 1`

_Use the input below the chart to quickly experiment with different `minPointLength` values._

#### Affected browser(s)

All of them, AFAICS. (I tested it in IE11, Chrome, and Firefox.)

---

_I was hoping [this ticket](https://github.com/highcharts/highcharts/issues/4338) will get the issue resolved, but it's now supposedly fixed and the issue remains._

**Comment by znevrly** [comment]
+1 for fixing this.

**Comment by pawelfus** [comment]
Thank you for reporting the issue!

- regular demo: 

That will be fixed of course. Previous ticket assumed values are noticeable smaller.

- zero-adjustments demo:
 
I am open for a suggestions here. Minimum point length is applied for all points when height is lower than a set value. Of course, it will increate the last point - instead I suggest to use `minPointLength ~ 0.0001`. For example: http://jsfiddle.net/1qu32g9n/2/ 

In my opinion setting to high `minPointLength` is simply wrong, for example: http://jsfiddle.net/1qu32g9n/3/ - I don't see any logic to compromise: chart's height, bars height and actual values on the chart. Note: my second demo is exactly the same issue as "zero-adjustments", just shows the real issue here.

**Comment by hon2a** [comment]
My original zero-adjustments demo was misleading, because the data labels were obscuring the main point of the `minPointLength` use - presence of the columns. I've updated the data labels with tooltips and updated the [link](http://jsfiddle.net/1qu32g9n/4/).

Using `minPointLength` lower than 1 does nothing for me, because the whole point of setting `minPointLength: 1` is to make the zero values visible in the chart. Making it much higher than `1` doesn't really make sense in this context, but as you said, it does show the issue, which is IMO that

**`minPointLength` is just a visualization property, it shouldn't affect data integrity.**

While `minPointLength` can make a waterfall column higher than its value warrants, it shouldn't affect how the position of the next column is computed. It should be applied only after all of the column positions and lengths are computed and prolong the column in the direction based on the sign of its value (move column top up by default but move column bottom down for negative adjustments instead).

**Comment by pawelfus** [comment]
Thanks for your feedback!

Then how about this use-case: http://jsfiddle.net/1qu32g9n/5/ - all values are positive, and moving column to the bottom doesn't make sense, right?

Isn't better to use `tooltip.shared` instead? In that case, tooltip will display regardless of the column shape, please take a look: http://jsfiddle.net/1qu32g9n/7/

**Comment by hon2a** [comment]
[This mock demo](http://jsfiddle.net/7q49me36/) shows how I'd expect the zero-adjustments waterfall to look. [This mock demo](http://jsfiddle.net/466dvbne/1/) shows how I'd expect your one-percent-adjustments to look. And [this](http://jsfiddle.net/t6uesxy4/) is how I'd expect the same case (one-percent) to work if `minPointLength` was increased.

**Comment by pawelfus** [comment]
Thank you for the explanation. And my apologies for a delay. 

There is one problem with a solution you propose. For example this demo: http://jsfiddle.net/1qu32g9n/8/ - the first point will rendered **below** zero which is certainly a a misleading representation.

I am worried, that one way or another, we will break data integrity anyway - that's what `minPointLength` actually does.

> minPointLength should only affect the columns individually (not incrementally)
We can change that, but it will break the idea in the waterfall chart: shouldn't every point start at a position when **previous** ends? Just to be on the same page: of course you are right, the current solution is not a perfect one as the last (sum) column may be very misleading in a certain cases.

My point with `shared` tooltip is that `minPointLength` is not the best idea (imho) to use in a waterfall series. Instead it's better to use tooltip to display values when those are equal to zero.

**Comment by hon2a** [comment]
> There is one problem with a solution you propose. For example this demo: http://jsfiddle.net/1qu32g9n/8/ - the first point will rendered below zero which is certainly a misleading representation.

That's not what I proposed though, I proposed for each column to start where computed from the data and then be prolonged in the direction it's "pointing". IMO that's exactly the impact to be expected from the `minPointLength` property. Of course it will make the visualization different from the data on principle, but by breaking integrity I meant the impact on position of the following points that makes the shape of the whole series inconsistent with the data.

> We can change that, but it will break the idea in the waterfall chart: shouldn't every point start at a position when previous ends?

First and foremost, the chart should correctly represent the data. What you describe is an invariant of the waterfall _data_. It doesn't mean that keeping this invariant in the _visualization_ should take precedence over keeping it consistent with the data.

> My point with shared tooltip is that minPointLength is not the best idea (imho) to use in a waterfall series. Instead it's better to use tooltip to display values when those are equal to zero.

I disagree. This issue points out a bug in waterfall rendering - `minPointLength` is used to transform the actual data, not just "length" of individual columns. Of course it's possible to just say it's not supported for waterfall, but then it should be clearly stated in the documentation. I don't see though, how the functionality I propose above is much different from how `minPointLength` is used in plain column series.

**Comment by znevrly** [comment]
Hi,
please HighChart team, can you make a statement to this issues?

Thank you very much.

**Comment by pawelfus** [comment]
@hon2a and @znevrly - my apologies for a delay. Of course, we will fix this. When fixed, `minPointLength` will not affect next points on an axis, only the current one.

**Comment by hon2a** [comment]
Great, thanks.

**Comment by pawelfus** [comment]
Demo with fixed applied: http://jsfiddle.net/1qu32g9n/10/ - let me know if you find any issues with that solution. Thank you!

**Comment by hon2a** [comment]
That looks awesome, can't wait for the release. Thank you!

**Comment by rudovjan** [comment]
I'm afraid this is back with 5.0.10

**Comment by pawelfus** [comment]
Could you create a demo? This one looks fine: http://jsfiddle.net/1qu32g9n/11/

**Comment by hon2a** [comment]
> I'm afraid this is back with 5.0.10

It's not. This time it's a bug in our own plugin.
