### ISSUE TITLE
0.995 rounded to 0.00 in tooltip when set to show two decimal places

### ISSUE THREAD

**Issue by paulmdavies** [highcharts/highcharts#6088]
#### Expected behaviour
Tooltip should display 1.00 for value of 0.995 when set to show two decimal places

#### Actual behaviour
Tooltip displays 0.00

#### Live demo with steps to reproduce
http://jsfiddle.net/m59yzt9a/

#### Affected browser(s)
Firefox, Chrome

**Comment by oysteinmoseng** [comment]
Thank you for reporting. It seems the issue is that we are rounding the decimal places separately, so the rounded decimals don't carry over to the integer part.

Internal note: It fails in `Utilies - Highcharts.numberFormat`.
