### ISSUE TITLE
Cannot update panes in gauge chart

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6089]
#### Behaviour
Function Chart.update() does not seem to update pane in gauge chart. Not sure if this is a bug, as in pre-Chart.update() function era it was not treated as such (#5593)

#### Live demo
http://jsfiddle.net/d_paul/60dvhrpg/

**Comment by oysteinmoseng** [comment]
I would definitely consider this a bug, it's not a logical limitation from the user's perspective.

**Comment by TorsteinHonsi** [comment]
I did some research and found that chart.update with pane is currently not implemented. I agree it is a bug.

This is [how far I got](https://gist.github.com/TorsteinHonsi/4d598d0ecab9aec836c890c4862eee77).

The problem now is with the background, which is implemented as a plot band on the pane's first axis. This is a problematic design, especially when it comes to adding, updating and removing, and even on exporting as we have seen before. It is probably not too hard to finish the gist to fix the issue, but we should also consider a different binding between panes and axes.

**Comment by newlukai** [comment]
Today I also stumbled upon this bug. How far is the progress here, can we expect a fix soon? Or would I need to create a new Chart object in the case I want to update a gauge chart?

**Comment by KacperMadej** [comment]
+1

**Comment by KacperMadej** [comment]
Fixed through https://github.com/highcharts/highcharts/commit/2f49339665f794eb4c29ec0a887f25b6d550dbc8
