### ISSUE TITLE
Map format legend values

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#6090]
Impossible to format legend values, because they overlap each other.

#### Expected behaviour
Legend labels do not overlap each other.

#### Actual behaviour
Legend labels overlap each other.

#### Live demo with steps to reproduce
http://jsfiddle.net/Pashe4ka/5ctxc9q9/

#### Affected browser(s)
Chrome latest version

**Comment by pawelfus** [comment]
Thanks for reporting!
I'm closing this as a duplicate of #4816

**Comment by TorsteinHonsi** [comment]
See your fiddle after fixing #4816 : http://jsfiddle.net/highcharts/5ctxc9q9/1/
