### ISSUE TITLE
Is there a way to extract the default values of various configuration options from the library?

### ISSUE THREAD

**Issue by VictorioBerra** [highcharts/highcharts#6091]
We need to generate some angular controls to configure a highcharts instance and need to set the controls to the default values. Is there a way to pull the defaults from the library?

**Comment by oysteinmoseng** [comment]
Calling `Highcharts.getOptions()` will return the default option structure object.

**Comment by TorsteinHonsi** [comment]
Also check out the dump from the API: http://api.highcharts.com/highcharts/option/dump.json

**Comment by VictorioBerra** [comment]
@TorsteinHonsi  thanks! Is there a reason some stuff is not inside `getOptions()` like `zoomType` or `panning`?

**Comment by TorsteinHonsi** [comment]
Yes, it's because its default value is resolved inline, and this applies to a lot of options. So I would recommend using the API dump instead, but it's heavy so you should preprocess it and for example compile a simple hash of options and their default values.
