### ISSUE TITLE
borderWidth on HighMaps states seems to be ignored

### ISSUE THREAD

**Issue by hjnilsson** [highcharts/highcharts#6093]
#### Expected behaviour
Specifiying `borderWidth` on a state will change the width of the borders.

#### Actual behaviour
Width is always the same.

#### Live demo with steps to reproduce
http://jsfiddle.net/29tgts3h/

Click / hover, `borderWidth` has different values for `select` and `hover` states, but nothing changes in the display.

**Comment by oysteinmoseng** [comment]
Fails since 5.0

**Comment by TorsteinHonsi** [comment]
Fixed in v5.0.6: http://jsfiddle.net/29tgts3h/
