### ISSUE TITLE
Hover tooltips and button icon run into each other

### ISSUE THREAD

**Issue by znevrly** [highcharts/highcharts#6096]
#### Expected behaviour
Tooltips should not be overlapped by buttons. This is general problem for example in Bubble/Scatter etc.

#### Actual behaviour
Tooltips are overlapped and therefore unreadable.

#### Affected browser(s)
Chrome, actually I think that all of them.
![zoom_bug](https://cloud.githubusercontent.com/assets/1698263/20925666/6a409d6a-bbb8-11e6-8d7e-8b6c05e656e4.png)

**Comment by oysteinmoseng** [comment]
Thank you for reporting this.

Live demo: http://jsfiddle.net/LLExL/6799/
Steps to reproduce:
- Zoom to last point on line
- Hover over last point
- "Reset zoom" button should overlap tooltip

**Comment by pratapgowda007** [comment]
Is there an update on this? I'm also facing same issue? any help would be really appreciable.

**Comment by oysteinmoseng** [comment]
@pratapgowda007 You can fix this by setting zIndex on the resetZoomButton: http://jsfiddle.net/LLExL/8250/

Should this be the default perhaps @TorsteinHonsi? Or will it break other things?

**Comment by TorsteinHonsi** [comment]
I don't understand why it was rendered with `zIndex` 20 by default, it should obviously go below the tooltip. It was probably set to 20 just to make sure it wasn't covered by axis and series stuff. I changed it to 6, the tooltip is 7.
