### ISSUE TITLE
Additional space character in first and last datetime label using custom format

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6097]
#### Expected behaviour
Display date in correct format for every tick, for example:
`Jan/7/2013`
Works in 4.2.3: http://jsfiddle.net/9ty6netc/

#### Actual behaviour
First and last tick labels have additional space, for example:
`Jan/ 7/2013`

#### Live demo with steps to reproduce
http://jsfiddle.net/9ty6netc/1/

**Comment by oysteinmoseng** [comment]
Actually this is by design, see issue #5060.
