### ISSUE TITLE
highcharts editor modal bug

### ISSUE THREAD

**Issue by crh225** [highcharts/highcharts#6099]
#### Expected behaviour
the dates are not showing up correctly when using the sample data for the modal on http://editor.highcharts.com/modal.html

![image](https://cloud.githubusercontent.com/assets/19475195/20934986/aaea306c-bba2-11e6-8650-56b240ef8e08.png)

#### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/19475195/20934953/93c202a2-bba2-11e6-9533-8c527366615a.png)

#### Live demo with steps to reproduce

http://editor.highcharts.com/modal.html
#### Affected browser(s)
all

**Comment by crh225** [comment]
if you see the x axis, you can see they dont show up correctly either:
![image](https://cloud.githubusercontent.com/assets/19475195/20935016/c59e6a54-bba2-11e6-887d-c4d7bc4d46ba.png)

**Comment by crh225** [comment]
same applies to http://editor.highcharts.com/full.html

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! This issue belongs in the https://github.com/highcharts/highcharts-editor repo, so I'm closing it here. @cvasseng
