### ISSUE TITLE
Highcharts editor breaks configuration is not working

### ISSUE THREAD

**Issue by berdeter** [highcharts/highcharts#6101]
#### Expected behaviour
You should be able to add breaks to an axis. In JSON you shoud have breaks:[{<break1}, {break2}, ...]. Breaks should appear on the graph

#### Actual behaviour
You can configure one break. JSON is breaks:{my break}. The break does not appear on the graph (as JSON is not correct, it shoud include a list of break, on a single break)
![capture](https://cloud.githubusercontent.com/assets/853740/20967234/a9f13ade-bc7e-11e6-9384-89954fcaf5c5.PNG)
[breaks.txt](https://github.com/highcharts/highcharts/files/636563/breaks.txt)

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! Please report editor issues in https://github.com/highcharts/highcharts-editor/issues. @cvasseng .
