### ISSUE TITLE
Reset Zoom not working when drilldown

### ISSUE THREAD

**Issue by nabster11** [highcharts/highcharts#6103]
#### Expected behaviour
Reset Zoom button should work on drilldown.

#### Actual behaviour
Reset Zoom button not working on drilldown.

#### Live demo with steps to reproduce

http://jsfiddle.net/y9cao4kj/

Steps to reproduce:- 
1) Zoom 'xy' enough to hide the 1st column bar.

2) Now drilldown on any column, 

- Press on Reset Zoom and then "Back to Brands", Still the zoomed view is shown and not the full view (1st Bug).
- The buttons "Reset Zoom" and "Back to Brands" are overlapped. (2nd Bug)

#### Affected browser(s)
All

**Comment by venbal** [comment]
Hi, What is the status of this issue?

**Comment by amit1911** [comment]
+1

**Comment by echarlus** [comment]
any idea of when this issue will be closed ? 
I'm experiencing the issue with the Vaadin Framework, I managed to reset the zoom level of the serie before the drilldown so when I go back on drill-up zoom is reset to 1:1 but I cannot find a way to automatically hide the ResetZoom button on drilldown which is not good....

**Comment by pawelfus** [comment]
**Workaround:**

Manually reset extremes and remove reset zoom button: https://jsfiddle.net/p4agkwx8/1/

Snippet:
```
chart.xAxis[0].setExtremes(null, null, false, false); // reset extremes, without redraw
if (chart.resetZoomButton) {
    chart.resetZoomButton = chart.resetZoomButton.destroy(); // destroy the button
}
```
