### ISSUE TITLE
xrange y axis label position calculated incorrectly.

### ISSUE THREAD

**Issue by mikecentiq** [highcharts/highcharts#6104]
https://jsfiddle.net/aq4ossty/1/

The positioning of the top positioned label "Line 3" is being calculated badly. It's actually giving it a `y="-9999"` positioning it off the top of the viewport.

I copied the minified xrange module src into the jsfiddle directly from github as I couldn't see a way of using a script tag to add it.

**Comment by pawelfus** [comment]
Hi @mikecentiq 

It's caused by [`yAxis.showLastLabel`](http://api.highcharts.com/highstock/yAxis.showLastLabel), which by default is set to false. See working demo: https://jsfiddle.net/aq4ossty/2/

**Comment by mikecentiq** [comment]
Oh. That seems like a very odd configuration item to exist. I'm sure it has a use case, but it doesn't seem like the correct default for an xrange series graph. Should the default be changed?

**Comment by pawelfus** [comment]
This is a default setting for yAxis (not for xrange series) and this is a default behaviour in Highstock. I don't think this default value should change: it's a common design for stock charts.

**Comment by TorsteinHonsi** [comment]
It's an odd configuration for a category axis though... The most intuitive default behaviour would be that `showLastLabel` was false for numeric Y axes but true for category Y axes.
