### ISSUE TITLE
Copious errors in browser console when using xrange

### ISSUE THREAD

**Issue by mikecentiq** [highcharts/highcharts#6107]
https://jsfiddle.net/p0eawzuw/4/

Move the brush in the navigator from left to right a few times and your browser console will fill full of errors like:

Error: <rect> attribute width: A negative value is not valid. ("-228.68789637628004")

Seems like there is a miscalculation of some sort inside xrange / highstock.

**Comment by oysteinmoseng** [comment]
Thank you for reporting, but the xrange series type is still under development.

@larsac07 FYI

**Comment by TorsteinHonsi** [comment]
Reopening it, as we need to handle it anyway.
