### ISSUE TITLE
v5.0.6 causes bug when swapping 2 series indexes

### ISSUE THREAD

**Issue by Munzey** [highcharts/highcharts#6112]
#### Expected behaviour
Be able to right click on two legend items of a stack column chart and swap there position/order by switching their indexes

#### Actual behaviour
always works when i click the left item first before the right. sometimes swaps their positions when clicking the right item first, but usually makes one item lose its color

#### Live demo with steps to reproduce
try right clicking 'test2' legend name first then 'test1' and the desired behaviour wont occur with 5.0.6
http://jsfiddle.net/LLExL/6817/   --> 5.0.6 
http://jsfiddle.net/LLExL/6818/   --> 5.0.5

*Note*: Youll need to hit 'run' again everytime you want to try swap the items

#### Affected browser(s)
chrome, firefox is all ive tested

**Comment by TorsteinHonsi** [comment]
I have troubles getting the right-click thing to work, but I simplified it here: http://jsfiddle.net/highcharts/Le32owLp/

Something has changed in v5.0.6.

**Comment by oysteinmoseng** [comment]
Offending commit: ed84e5d
