### ISSUE TITLE
Legend items stays hovered on mouseout.

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#6113]
#### Expected behaviour

If series are hidden, legend items are changing color on mouseover. When the mouse is no longer hovering legend items (mouseout event) they should change color to default again.

#### Actual behaviour

Right now sometimes legend item stays hovered on even if mouse is not longer over this element. It looks to be connected with setting specific width of legend items.

#### Live demo with steps to reproduce
http://jsfiddle.net/bpaq9zz3/4/

To reproduce this issue try to move mouse pointer fast inside legend.

#### Affected browser(s)
Tested on Chrome and Safari browsers.

**Comment by sebastianbochan** [comment]
_Internal note_
It looks like `buildText` in the `css()` function has an influence on delay. When we comment it, the text is displayed in the right width and hover state is applied properly.

```
if (textWidth) {
	elemWrapper.renderer.buildText(elemWrapper);
}
```

**Comment by TorsteinHonsi** [comment]
The `buildText` function is quite heavy and it's not necessary to call it in this case. We should probably add a caching system similar to (or the same as) the one at getBBox. The text only needs to be rebuilt when:
* The textWidth changes.
* The font size changes.
* The text string itself changes.

**Comment by Izothep** [comment]
As a quick workaround, you can use small wrapper I made: 
http://jsfiddle.net/bpaq9zz3/6/

Unfortunately, it is just a workaround, not a full solution.
