### ISSUE TITLE
Minor observations : highcharts-negative extry twice.

### ISSUE THREAD

**Issue by garybrain** [highcharts/highcharts#6114]
#### Expected behaviour

Single class entry for .highcharts-negative

#### Actual behaviour

double entry for .highcharts-negative

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/css/series-negative-color/

Also testing with the Master Branch,

If you inspect one of the points we can see the double entry.

`<path d="M 227 199.36 L 231 203.36 227 207.36 223 203.36 Z" class="highcharts-point highcharts-negative highcharts-color-1 highcharts-negative "></path>
`
Also noticed in the CSS File.

https://code.highcharts.com/css/highcharts.css

Duplicate CSS Entries, the 2nd "inherit" I disabled as it was not applying the stroke colour I was trying to configure.

.highcharts-column-series .highcharts-point {
  stroke: #ffffff;
  transition: fill-opacity 250ms;
}

and

.highcharts-column-series .highcharts-point {
  stroke: inherit;
  /* use point color */
}

**Comment by pawelfus** [comment]
Thanks for reporting!

*Internal note:*
Issue comes from `getClassName` in point. Most probably zone applies negative class and `point.negative` too.

**Comment by oysteinmoseng** [comment]
Yes, zones are used for negative color, and then have a className of `highcharts-negative`. See https://github.com/highcharts/highcharts/blob/master/js/parts/Series.js#L433

**Comment by oysteinmoseng** [comment]
Assigning the remaining CSS part of the issue to you @TorsteinHonsi
