### ISSUE TITLE
Returning an array from tooltip formatter with false value when split is enabled does not hide tooltip

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6115]
#### Expected behaviour
With enabled tooltip.split, after returning an array from tooltip formatter when one of the values is false, after hovering series one tooltip should not be visible.

example `[false, ' ', ' ', ' ']` // tooltip 0 should be hidden

From api:
> Callback function to format the text of the tooltip. Return false to disable tooltip for a specific point on series.

#### Actual behaviour
Tooltip 0 shows 'false' string

#### Live demo with steps to reproduce
https://jsfiddle.net/e7Lrh2Lc/

**Comment by oysteinmoseng** [comment]
Thank you for reporting this.

**Comment by kamilf92** [comment]
Hi,
Some progress in the work ?
Regards

**Comment by oysteinmoseng** [comment]
@kamilf92 I'll see if I can get a look at it this week.
