### ISSUE TITLE
Highcharts doe not react on touchOutside (touchLeave) event

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [highcharts/highcharts#6117]
I have chart with mouseOut event hook under plotOptions (from documentation) but it is not being fired when using with touch devices. 
For the same reason tooltip.refresh method not being called.

So my column stays selected on touche away.
This could be implemented by adding event like: 

```
Rx.Observable.fromEvent(document, 'touchend')
            .filter((event: TouchEvent) => !HTMLElementHelper.isChildOf(<HTMLElement>event.target, element));
```

where  

```
export class HTMLElementHelper {

    static isChildOf(element: HTMLElement | Node, parent: HTMLElement) {

        if (!parent || !element || (!element.parentElement && !element.parentNode)) {
            return false;
        }

        while (element.parentElement || element.parentNode) {
            if (element === parent) {
                return true;
            }
            element = element.parentElement || element.parentNode;
        }

        return false;
    }
}
```

Is there any chance of doing this in short time for two reasons:

I think it is critically important to support touch devices nowadays.
Don't want to hack in software to gain such common behaviour

**Comment by oysteinmoseng** [comment]
This works for me on Android 6.0.1 ([demo](http://jsfiddle.net/gh/get/jquery/2/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-events-mouseover-sticky/)). Which device are you using, and could you reproduce a demo that fails?

**Comment by vytautas-pranskunas-** [comment]
I am testing on iPad Air 5

**Comment by oysteinmoseng** [comment]
I could still not reproduce this on an iPad Air 2 with either Safari or Chrome. (And as far as I know, iPad Air 5 has not been released yet?)

**Comment by vytautas-pranskunas-** [comment]
Sry for it was iPad Air 1.

**Comment by oysteinmoseng** [comment]
I apologize, I think I misunderstood the issue. The mouseout event is not always fired properly if touching outside of the container. This can be reproduced on most devices.

**Comment by vytautas-pranskunas-** [comment]
I am glad that you have reproduced it. Where you think it can be fixed?
