### ISSUE TITLE
Highcharts 5 'Style by CSS' not exporting to PDF with colors

### ISSUE THREAD

**Issue by rbeasse** [highcharts/highcharts#6118]
#### Expected behaviour
Using offline-exporting to export to a PDF should include the correct chart colors

#### Actual behaviour
Exporting to a PDF is making the text and chart bars black

#### Live demo with steps to reproduce
http://jsfiddle.net/jcnwfjsx/

#### Affected browser(s)
Chrome 54

**Comment by TorsteinHonsi** [comment]
@henrikskar 

The online export server does it correctly, so it's a problem with the offline PDF download. I would start debugging on the color formats in the generated SVG. Maybe the PDF generator can't parse it.

**Comment by sebastianbochan** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Apparently this comes down to the fact that the export module sets fill and stroke on the series group elements, and the individual `rect` elements inherit them from there. The svg2pdf.js library doesn't handle this. I have reported it as https://github.com/yWorks/svg2pdf.js/issues/27. 

If the svg2pdf.js team is not able to fix it, and alternative is to handle the inheritance in Highcharts, but that would be a workaround and is not ideal.
