### ISSUE TITLE
[highcharts] some datalabels are missing

### ISSUE THREAD

**Issue by havefull** [highcharts/highcharts#6119]
Hi,

Currently I'm using highcharts for diagrams.
However I discover that some datalabels are missing for bar chart.

please have a look on my demo page
https://jsfiddle.net/have_full/ybjf4wzg/1/

as you can see, the first datalabels on hammer, is missing
and last datalabels for bow is missing

however if you change the value it will show.

do you have any idea how to fix it?

thanks

**Comment by pawelfus** [comment]
Hi @havefull 

For me it works fine (osx + chrome): 
![screen shot 2016-12-09 at 10 40 15](https://cloud.githubusercontent.com/assets/1453926/21044375/ed6f8ab2-bdfb-11e6-8e03-6b325f8f22d5.png)

Different browsers (on different systems) returns different bounding box of a label. Highcharts by default hides overlapping labels. Could you try:

- set [`series.dataLabels.allowOverlap`](http://api.highcharts.com/highcharts/plotOptions.series.dataLabels.allowOverlap) to true ? Or:
- set [`series.dataLabels.padding`](http://api.highcharts.com/highcharts/plotOptions.series.dataLabels.padding) to 0 ?

**Comment by havefull** [comment]
yes, it works.
yes, it seems that I need to add extra style on firefox.
currently I'm using version 50.0.2

Thanks for your help.
