### ISSUE TITLE
Missing a width attribute to align legend values on the right

### ISSUE THREAD

**Issue by berdeter** [highcharts/highcharts#6120]
#### Expected behaviour
In the legend, have entry names ligned on the left and values on the same line aligned on the right.

Let's start with this http://jsfiddle.net/hAnCr/790/

I'd love to have my legend aligned like the first line ("Domestic Equity") in this image
![capture](https://cloud.githubusercontent.com/assets/853740/21045189/a2198596-bdff-11e6-9d9d-263894c762c1.PNG)

#### Actual behaviour
Values are down on the next lines as you can see in other lines

To fix the problem you need to add the itemWidth values to the div with class highcharts-legend-item like in this image 
![capture2](https://cloud.githubusercontent.com/assets/853740/21045332/3906b334-be00-11e6-9205-ed297be30e4b.PNG)

Doing this is enough to let the formated value enough space to expand in a single line

#### Live demo with steps to reproduce
http://jsfiddle.net/hAnCr/790/

#### Affected browser(s)
All

**Comment by berdeter** [comment]
I could fix it with this configuration : 

labelFormat : <div style="display:inline-block;width:150px">{name}</div><div  style="display:inline-block;width:50px">{y} €</div>
width : 220

**Comment by TorsteinHonsi** [comment]
For the records, here's how it looks with that configuration: http://jsfiddle.net/highcharts/hAnCr/793/
