### ISSUE TITLE
TickPixelInterval depends on amount of data

### ISSUE THREAD

**Issue by patrickjuchli** [highcharts/highcharts#6121]
#### Expected behaviour

When using a line chart for datetime data that only contains 2 entries, ticks should still be drawn according to tickPixelInterval.

#### Actual behaviour

I only see one single tick. Seems to depend on the amount of data and not the available screen space only. I need this to work as documented.

#### Live demo with steps to reproduce

[Example](http://jsfiddle.net/mLztq56c/)

#### Affected browser(s)

Tested on Chrome 55

**Comment by oysteinmoseng** [comment]
Thank you for reporting, this seems like a bug.

**Comment by TorsteinHonsi** [comment]
There's another option, called [minTickInterval](http://api.highcharts.com/highcharts/xAxis.minTickInterval), that influences your axis. The prevents ticks from being drawn closer than the data points. To override that, [set the minTickInterval to 1](http://jsfiddle.net/highcharts/mLztq56c/2/). 

I've added this information to the [xAxis.tickPixelInterval](http://api.highcharts.com/highcharts/xAxis.tickPixelInterval) documentation.
