### ISSUE TITLE
Easilly configurable and more functional dual column legend

### ISSUE THREAD

**Issue by berdeter** [highcharts/highcharts#6122]
#### Expected behaviour
Inspired from #6120 it would be very nice to have an easy configuration of a two column legend including features such as : 

- column 1 aligned on the left, column to on the right
- possibility to configure the with of each column
- possibility to word wrap column 1 if its content exceeds allowed width
- possibility to configure labels to display on top of each columns
- possibility to configure labels to display at the bottom of each columns (for totals, etc)
- dotted lines between both columns to ease readability
- ...

#### Actual behaviour
Some points can be achieved with a labelFormatter that is quite complicated for such a simple and recurrent requirement but #6120 make them actually not usable.

#### Affected browser(s)
All

**Comment by berdeter** [comment]
Alternatively a low cost solution would be : 

- Add two fields legendHeader and legendFooter
- Let useHTML apply on such fields
- allow some expressions such as {sum(y)} or {avg(y)}

Then you can configure like this :

- width=220
- useHTML=true
- labelFormat=<div style="display:inline-block;width:150px">{name}</div><div  style="text-align:right;display:inline-block;width:50px">{y} %</div>
- labelHeader=<div style="display:inline-block;width:150px">Browser</div><div  style="text-align:right;display:inline-block;width:50px">Share</div>
- labelFooter=<div style="display:inline-block;width:150px">Total</div><div  style="text-align:right;display:inline-block;width:50px">{sum(y)} %</div>

This could also make it possible to use this solution that supports leading dots : 

https://codepen.io/caseymhunt/pen/xEhcp 

You can see that it implies that the legend is included inside an <ul></ul>. This would be possible with labelHeader and labelFooter

Bernard

**Comment by pawelfus** [comment]
I agree with you: even simple n-columns legend would be great. Or just a possibility to create a table-like structure in legend (it would be perfect to do that without `useHTML` flag).

**Comment by TorsteinHonsi** [comment]
Currently we have something like that on the tooltip, with `headerFormat` and `footerFormat` which allows a HTML table: http://jsfiddle.net/gh/get/jquery/3.1.1/highcharts/highcharts/tree/master/samples/highcharts/tooltip/footerformat/

**Comment by LaniMoo** [comment]
I too would like something like this. This would be particularly useful for charts with multiple axes or any data tied to groups. For example, I have a chart that uses 2 y-axes and would like to separate the different series into 2 columns in the legend with a title above each column.

 It would be great if there was a formatter made available for the legend that was as flexible as the tooltip formatter.
