### ISSUE TITLE
Grouped Categories as objects

### ISSUE THREAD

**Issue by royigoldi** [highcharts/highcharts#6124]
Hi,

I used the group categories plugin, i want to ask if there is a way to save the categories as object, for example:
{name:Jon, value:"some unique guid"}

that when i clicked on the specific data lables i will get the unique guid also and not only the name.

Thanks,
Royi

**Comment by pawelfus** [comment]
Hi @royigoldi 

Please, create a ticket in the plugin repo: https://github.com/blacklabel/grouped_categories
