### ISSUE TITLE
Getting addional data on x-axis data labels click

### ISSUE THREAD

**Issue by royigoldi** [highcharts/highcharts#6125]
Hi, 

I am using custom events plugin and groupd categories plugin:
i defined categories, for example as: 
{name: "test", value: "3", id:"id1"}
{name: "test2", value: "4", id:"id2"}

when i click on x-axis data labels i am getting only the "test" name in this.textStr.
ther ei no this.pos for getting the categories and no addinional data (for example: the value and the id that I defined)

can you help me to understand how i get my addional data (my names are not unique so i need to get the id also by click)

Thanks,
Royi

**Comment by oysteinmoseng** [comment]
Hi, would you be able to reproduce your issue in a jsFiddle as a live demo?

**Comment by royigoldi** [comment]
you can send me yours working example?

**Comment by pawelfus** [comment]
I would suggest to create issue (issues?) in the plugins' repos: https://github.com/blacklabel/grouped_categories or https://github.com/blacklabel/custom_events

**Comment by oysteinmoseng** [comment]
Closing for follow up in plugin repos instead.
