### ISSUE TITLE
Tooltip caret not drawn after updating `tooltip.options.shared` dynamically

### ISSUE THREAD

**Issue by magnushavgry** [highcharts/highcharts#6128]
#### Expected behaviour
The tooltip is drawn according to the current state of `shared` (in this case when the tooltip isn't shared) in the same way it is with e.g. `backgroundColor`.

#### Actual behaviour
The `shared` property is updated and working accordingly but the caret is no longer drawn.

#### Live demo with steps to reproduce
http://jsfiddle.net/dm2fLhan/

1. The tooltip is not shared and a caret is visible
2. Click the toggle button
3. The tooltip is now shared and no caret is displayed (as expected)
4. Click the toggle button again
5. The `shared` property is now back to its initial value (`false`) but the caret is gone

#### Affected browser(s)
All. Issue is not browser specific.

**Comment by pawelfus** [comment]
Thanks for reporting!

**Workaround:**
Set `chart.tooltip.len = null;` before updating the tooltip. Demo: http://jsfiddle.net/3va712y2/

*Internal note:*
In `tooltip.refresh()` method `tooltip.len` is always set for a shared tooltip, but never for a non-shared tooltip.
