### ISSUE TITLE
update() doesnt trigger my rules to be re-evaluated.

### ISSUE THREAD

**Issue by VictorioBerra** [highcharts/highcharts#6130]
Is calling setResponsive() with no arguments the only way to re-trigger my rules to run? I see that it calls update internally but i dont see it updating my chart. Also if you hit the "top" button twice my credits disappear and I think thats because .update() reset my settings.

#### Expected behaviour
update() re-runs my rules.

#### Actual behaviour
update() does not re-run my rules.

#### Live demo with steps to reproduce
http://jsfiddle.net/Lord_Zero/wkh4b6ko/

#### Affected browser(s)
Latest Chrome

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! More general, all chart redraws should evaluate responsive rules.
