### ISSUE TITLE
SVG/axis elements don't respond well to pinch zooming on mobile devices

### ISSUE THREAD

**Issue by pixelnix** [highcharts/highcharts#6131]
#### Expected behaviour
During a zoom action on a touch/mobile device, the elements of the chart are warped in real time to show the user an approximation of what the new visible area of the chart will be.  Data series markers shift around in the viewport as the user pinches/drags control points.  But other elements of the chart - the axes, SVG elements - do not respond until after the user releases the pinch action and the chart is re-rendered.

#### Actual behaviour
I suppose this may be more of a feature request, but now that Highcharts supports zoom on touch devices I think it's a bug in the usability of that feature that could hopefully be dealt with.  SVG elements and the chart axes should respond in real time during the zoom action, as the data series markers respond.

#### Live demo with steps to reproduce
http://jsfiddle.net/0wwjwe8u/

This fiddle is a fork of one linked from the API documentation, to which I added zoomability.  Try it on a mobile device to reproduce the behavior I'm trying (maybe badly) to describe.

#### Affected browser(s)
touch devices, all browsers

**Comment by pixelnix** [comment]
Can we just get the non-touch zoom behavior for touch screens?  It's a fine user experience to zoom with the little rectangle overlay that lets you see exactly what part of the chart you're selecting.  Is there a way to opt back to that behavior for touch devices?

**Comment by TorsteinHonsi** [comment]
The problem is with the mouse there is a difference between moving the mouse over the chart and moving the mouse with the button pressed. In touch events we don't have this. The typical way of zooming on touch devices is pinching with two fingers. 

> Is there a way to opt back to that behavior for touch devices?

Not an easy one I'm afraid.

**Comment by ourabio** [comment]
Hi, I am using Highstock on a mobile app and having a problem scrolling the zoomed area, chart renders after scroll ends ( touch release ).

Tested on Android Device, Xcode Simulators.
Test video:
Navigator disabled: https://streamable.com/5hzic
Navigator enabled: https://streamable.com/xgtht

**Comment by sebastianbochan** [comment]
Hi @ourabio 
The issue is related with our known case, reported here: #5270.

**Comment by ourabio** [comment]
Hi @sebastianbochan 
Ok, Thanks!
