### ISSUE TITLE
bar chart with max x-axis

### ISSUE THREAD

**Issue by royigoldi** [highcharts/highcharts#6133]
Hi,

I had bar column that i load my categories dynamically after i getting data from server:
it can 1 columns or 100 for eaxmple.

i want to diaplay no more then 8 columns, so i put the x-axis: max to 8 and it is ok when I load more then 8, I got horizontal scrollbar.
My problem is that when I got less then 8, empty categoris columns exist in the end...

### Expected behaviour
Only relevant columns will be displayed

#### Actual behaviour
all the columns until the max value displayed

#### Live demo with steps to reproduce
Simple example that discribe my problem:
http://jsfiddle.net/RoyiGoldenberg/4nft4u93/

**Comment by pawelfus** [comment]
Hi,
you can set conditionally `xAxis.max`, take a look: http://jsfiddle.net/4nft4u93/2/ or you can use [`xAxis.ceiling`](http://api.highcharts.com/highcharts/xAxis.ceiling), see another demo: http://jsfiddle.net/4nft4u93/3/
