### ISSUE TITLE
addPoint does not work in Highmaps

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#6134]
#### Actual behaviour
The demo for `addPoint` in Highmaps fails since 5.0.1. Greenland is part of export, however.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/2/highcharts/highcharts/tree/master/samples/maps/members/series-addpoint/

- Click button to add Greenland. Observe that extremes are changed, but the point is not visible.

**Comment by TorsteinHonsi** [comment]
Fails since 862f09f.

The check for `isDirtyData` should be enough, I'd expect this to be true after addPoint.
