### ISSUE TITLE
SSL for github.highcharts.com. Without HTTPS I cant load these via jsfiddle.

### ISSUE THREAD

**Issue by VictorioBerra** [highcharts/highcharts#6135]
#### Expected behaviour
https://github.highcharts.com/ should resolve just like code.highcharts.com.

#### Actual behaviour
https://github.highcharts.com/ refuses connection

#### Live demo with steps to reproduce
[Github.](https://github.highcharts.com/)
[Code.](https://code.highcharts.com/)

**Comment by oysteinmoseng** [comment]
Note: It should be possible to load these via jsFiddle as long as you load the fiddle over HTTP.

**Comment by TorsteinHonsi** [comment]
Also, please note that github.highcharts.com is just a service we set up for convenience. Under no circumstances should it be used in production.

**Comment by jon-a-nygaard** [comment]
Support for SSL on github.highcharts.com was added on February 16.
