### ISSUE TITLE
Updated point doesn't render the correct value after removing another point in same redraw

### ISSUE THREAD

**Issue by YusselPP** [highcharts/highcharts#6136]
#### Expected behaviour
Render correct values after applying dynamic removes and updates in the same redraw cycle.

#### Actual behaviour
When stacking is enabled, If you update a point that is located after a removed point the updated point doesn't render the correct value.

#### Live demo with steps to reproduce
https://jsfiddle.net/vcnevffj/

**Comment by sebastianbochan** [comment]
The workaround is update points firstly and then remove.

Example:
- https://jsfiddle.net/mexsdno1/
