### ISSUE TITLE
reset the default color to series

### ISSUE THREAD

**Issue by crh225** [highcharts/highcharts#6138]
#### Expected behaviour
when I clear all series, then add a new series, it should start over on the colors. 
It says I can do chart.counters.color = 0; but counters in not in the latest typings for highcharts.

#### Actual behaviour
similar issue to https://github.com/highcharts/highcharts/pull/203

#### Affected browser(s)
all

**Comment by oysteinmoseng** [comment]
There is a `chart.colorCounter`, see http://jsfiddle.net/1ok4oege/.

Not sure how we should handle this automatically, as we can't just decrement this every time we remove a series, in case the series is not the last one, or there are custom colors on the series.

**Comment by crh225** [comment]
That link does not use rulings from the definabtly types project for highcharts.

**Comment by crh225** [comment]
That link does not use typings*

**Comment by magnushavgry** [comment]
As far as I can see `counters` is no longer part of the `chart` object and probably hasn't been for a while.

Regarding typings you're welcome to create a pull request with the addition of `colorCounter` but that's another repository: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/highcharts

**Comment by crh225** [comment]
I realize it's a different repository but isn't highcharts responsible for their own typings?

**Comment by crh225** [comment]
Couldn't when it goes and gets the next chart series color, it does a check that says: if (series.length === 0) { chart.counter = 0;}

**Comment by oysteinmoseng** [comment]
We are not behind the DefinitelyTyped project for Highcharts, this is a 3rd party project.

Regarding `chart.colorCounter = 0`, this is something we could perhaps consider? @TorsteinHonsi comments?

**Comment by crh225** [comment]
@oysteinmoseng, @TorsteinHonsi, have you guys any update on this?

**Comment by oysteinmoseng** [comment]
@crh225 This will be part of the next maintenance release, v5.0.7

**Comment by crh225** [comment]
Thanks!

**Comment by crh225** [comment]
@oysteinmoseng , I tried to update to 5.0.7, but it cannot find it (yet?) on npm
![image](https://cloud.githubusercontent.com/assets/19475195/21782326/a373cde8-d678-11e6-8c02-129669f09ec3.png)

**Comment by oysteinmoseng** [comment]
@crh225 5.0.7 is not released yet, however you can find the latest code here on github. Example: `http://github.highcharts.com/highcharts.js`
