### ISSUE TITLE
Boost module - renderCanvas memory leak

### ISSUE THREAD

**Issue by hkostia** [highcharts/highcharts#6139]
#### Expected behaviour
Boost module renderCanvas shouldn't add multiple event listeners to series object with type 'destroy'.
https://github.com/highcharts/highcharts/blame/master/lib/modules/boost.src.js#L381

#### Actual behaviour
Boost module adds event listener for series in each call to renderCanvas which leaks memory and will eventually crash browser when updating the chart with data periodically.

**Comment by cvasseng** [comment]
Hi hkostia,

thanks for reporting.

There's an overhaul to the boost module incoming, and I'll be sure to address this once it lands.

**Comment by drkbkr** [comment]
Hello,

We're experiencing this issue and are having people work around it by just refreshing the page periodically but is there any estimate for when the mentioned overhaul would be released? Thanks.

**Comment by hkostia** [comment]
We used something like this to patch it:

```
    function override(object, methodName, callback) {
      object[methodName] = callback(object[methodName]);
    }

    function before(extraBehavior) {
      return function(original) {
        return function() {
          extraBehavior.apply(this, arguments);
          return original.apply(this, arguments);
        };
      };
    }

    function boostModuleRemoveEventFix() {
      override(window.Highcharts.Series.prototype, 'renderCanvas', before(function() {
        window.Highcharts.removeEvent(this, 'destroy');
      }));
    };
```

**Comment by drkbkr** [comment]
Thanks so much!

**Comment by Cheprer** [comment]
Hi, we've faced the similar issue but with different methods [onDocumentPointerUp](https://imgur.com/a/JRMJk) and [generatePoints](https://imgur.com/a/G1Bia).

You can see the problem on our [demo](https://unms-demo.ubnt.com/devices/) -> choose a device a go to statistics. With the real data it is even more severe.

Did someone address the problem? Here there is running v5.0.14 but I've tested it locally and it is still there with v6.0.3. And thanks @hkostia for a workaround we will try to apply it.

**Comment by TorsteinHonsi** [comment]
@Cheprer As far as I can see your statistics are not boosted, they seem to be in SVG mode...

**Comment by Cheprer** [comment]
@TorsteinHonsi You are right it supposed to be placed in the other issue. However I think the problem is not in the highcharts but in the react holding some object in state which still have these handlers.
