### ISSUE TITLE
Candlestick does not have hover state

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6140]
#### Actual behaviour
OHLC does not have hover state

#### Live demo with steps to reproduce
Example: 
- http://jsfiddle.net/5y7kbhdb/

Hover on any point, columns have hover state but candles not.

#### Affected browser(s)
All browsers

**Comment by oysteinmoseng** [comment]
Seems to fail since 5.0.0.

**Comment by ddotlic** [comment]
@TorsteinHonsi I was the one who reported the issue to support initially. This is not limited to candlestick, OHLC also does not show any hover state. Did you take care of that as well?

What is the fastest way for me to validate the fix? Our build system uses npm but I assume you're not pushing the dev version to the npm registry?

**Comment by TorsteinHonsi** [comment]
Sorry about that, the demo showed a candlestick so I assumed the title was wrong.

**Comment by ddotlic** [comment]
@TorsteinHonsi No worries. 

Once the fix is in, is there going to be a pre-built dev version I can integrate into our build process (see above, we use npm)?

**Comment by TorsteinHonsi** [comment]
You're right we're not pushing code in development to npm, so you'll find the latest build at http://github.highcharts.com/stock/highstock.js. Alternatively, you can just override the fixed part of the prototypes, like http://jsfiddle.net/highcharts/77awgha7/.

**Comment by ddotlic** [comment]
@TorsteinHonsi Thanks for that GitHub link, I saw it in a jsFiddle this morning for the first time. OK, I'll think of something for the dev build.

Do you issue patch releases with some (rough) regularity or based on some other criteria (like number of bugs fixed)? Trying to _roughly_ estimate when to expect the fix to become public.

**Comment by TorsteinHonsi** [comment]
The rough regularity is to release bugfix versions every one or two months.

**Comment by ddotlic** [comment]
@TorsteinHonsi Based on the additional commit above (`59bd067`), I assume you've fixed this.

Are you waiting on us to confirm the fix in order to close this bug?

**Comment by TorsteinHonsi** [comment]
Sorry for the delay. It should be closed, I wasn't aware it was reopened.
