### ISSUE TITLE
Error bars : allow custom whiskers

### ISSUE THREAD

**Issue by berdeter** [highcharts/highcharts#6141]
#### Expected behaviour
Have the possibility to configure the look of whiskers. e.g. arrows (up and down), big dots, etc.

#### Actual behaviour
only the horizontal line is possible

**Comment by pawelfus** [comment]
Actually it can be achieved by wrapping `drawPoints` method, for example: http://jsfiddle.net/u8tnd3eL/

Snippet: 

    (function(H) {
      H.wrap(H.seriesTypes.boxplot.prototype, 'drawPoints', function(p) {
        var renderer = this.chart.renderer;
        p.apply(this, Array.prototype.slice.call(arguments, 1));

        H.each(this.points, function(point) {
          if (point.whiskers) {
            point.whiskers.attr({
              d: getPath(point, renderer)
            });
          }
        });
      });

      // Generate path for each of the whiskers
      // It should be path for both, top and the bottom, whiskers:
      function getPath(point, r) {
        // x position in pixels
        var x = point.plotX, 
          // y-top whisker position in pixels
          high = Math.floor(point.highPlot),
          // y-bottom whisker position in pixels
          low = Math.floor(point.lowPlot),
          // just width and height for a whisker
          width = 10,
          height = 10,
          // we can use for example renderer.symbols[symbolName]
          // to generate paths:
          highTriangle = r.symbols['triangle-down'](x - width / 2, high - height, width, height),
          lowTriangle = r.symbols['triangle'](x - width / 2, low, width, height);

        return highTriangle.concat(lowTriangle);
      }

    })(Highcharts);

**Comment by berdeter** [comment]
Great. Thank you !
