### ISSUE TITLE
Threshold for value other than zero

### ISSUE THREAD

**Issue by Reg1234** [highcharts/highcharts#6143]
#### Expected behaviour
I need the graph to display a threshold value of e.g. 2.5

#### Actual behaviour
The graph is setting the threshold to 0

**Comment by pawelfus** [comment]
Hi @Reg1234 

This is our bug tracker. For questions, please email us or create a topic on our forum. 

Regarding threshold, it works like this: http://jsfiddle.net/mem05j3t/ - see [docs](http://api.highcharts.com/highstock/plotOptions.area.threshold).

**Comment by Reg1234** [comment]
Hi pawelfus ,

Sorry for posting in the wrong place, and thanks for the links to the docs.

R
