### ISSUE TITLE
Problem with tooltip when category name is empty

### ISSUE THREAD

**Issue by madreason** [highcharts/highcharts#6144]
Breaking tooltip layout on category name "" or " " or null or tab

#### Expected behaviour
Correct tooltip layout
![hc_1](https://cloud.githubusercontent.com/assets/1410761/21182741/ae5db63c-c215-11e6-9d39-2e9cdbfc3afb.png)

#### Actual behaviour
Uncorrect tooltip layout
![hc_2](https://cloud.githubusercontent.com/assets/1410761/21182748/bb548dd4-c215-11e6-9817-ce63b9a1edb3.png)

#### Live demo with steps to reproduce
[jsfiddle](http://jsfiddle.net/madreason/mt8q3L77/1/)

#### Affected browser(s)
Chrome 54

**Comment by sebastianbochan** [comment]
_Workaround_
Set the useHTML flag as true.

Example:
- http://jsfiddle.net/9o49fwgo/

**Comment by henrikskar** [comment]
Simplified demo: http://jsfiddle.net/henrikskar/4ckk9wzm/
Working on  a solution now. Thanks for reporting!

**Comment by madreason** [comment]
@sebastianbochan thanks for the fix
