### ISSUE TITLE
Export offline a pie chart to PDF makes crash the browser

### ISSUE THREAD

**Issue by fernandommota** [highcharts/highcharts#6145]
#### Expected behaviour
Export offline a pie chart to PDF.

#### Actual behaviour
Crash the browser.

#### Live demo with steps to reproduce
http://jsfiddle.net/9e553w2d

#### Affected browser(s)
chrome, safari

**Comment by TorsteinHonsi** [comment]
The problem seems to be arc definitions in the paths. Any arc will fail. This also affects the latest development code of line series with circle markers, that are drawn as arcs.

**Comment by TorsteinHonsi** [comment]
See https://github.com/yWorks/svg2pdf.js/issues/10 for details.

**Comment by TorsteinHonsi** [comment]
The fixed library seems to work only for Chrome. For Safari and Firefox the arcs are simply left out, which also now affects point markers.

**Comment by TorsteinHonsi** [comment]
Continuing in #6481
