### ISSUE TITLE
Get non-existent series now crashes with TypeError: item.options is null

### ISSUE THREAD

**Issue by weakunix** [highcharts/highcharts#6147]
Highcharts.StockChart.get("seriesid") has an obvious bug in 5.0.6, (line 14511 of highstock.src.js):

    function itemById(item) {
        return item.id === id || item.options.id === id;
    }
should read:

    return item.id === id || (item.options != null && item.options.id === id);

**Comment by pawelfus** [comment]
Hi @weakunix 

Any chance to reproduce the issue? For me it works fine: http://jsfiddle.net/43gctL1f/

Thanks!

**Comment by weakunix** [comment]
Ok, it's a tricky one and it only fails when a `setData` is called on an existing series **without redraw** AND the number of points have been changed: [http://jsfiddle.net/43gctL1f/9/]

**Comment by weakunix** [comment]
Just to add, when I originally said "obviously", I meant purely from a code review point of view in the sense that while it's relatively easy to make sure `itemById` is called with `item` never being null (since it's basically a lambda expression used locally in Get), it's less easy to enforce that `item.options` never being null. In general, the safest code would be:

return (item !=null && item.id === id) || (item.options != null && item.options.id === id);
