### ISSUE TITLE
HeatMap series setData() with high volume of data don't always refresh Y axis range

### ISSUE THREAD

**Issue by Dunge** [highcharts/highcharts#6152]
I create a heatmap chart container, and then on a javascript event use setData() to fill series values.

#### Expected behaviour
Y axis to limit itself to the data.

#### Actual behaviour
Even if my values are contained in the [7-20] range, the first click bring an Y axis range up to 120 and all cells are squished at the bottom. Clicking the button a second time refresh the range correctly.

#### Live demo with steps to reproduce
https://jsfiddle.net/m3mvww1z/

#### Affected browser(s)
All

#### Two observations
1. When only using half the values (no matter which one), it always works fine. Seems to break with large amount of values.
2. Setting the third parameter of setData() (updatePoints) to false will never refresh the axis range correctly. I guess the "second click" behavior happens because this time the data is of the same length and the "point update" feature instead of the "point replace" feature works.

**Comment by pawelfus** [comment]
Hi @Dunge - thank you for reporting the issue!

This is caused by [`series.turboThreshold`](http://api.highcharts.com/highcharts/plotOptions.series.turboThreshold) option - when disabled, it works fine: https://jsfiddle.net/m3mvww1z/3/

**Internal note:**
Heatmap `series.data` consist of three values `[x, y, value]`, so it has three parallel arrays. Unfortunately, because of `turboThreshold`, these arrays are not correct: `xData` is fine, `yData` haas a format `[y, value]` and `valueData` is an empty array. Because of wrong `yData` format, `yAxis` get extremes from both: `y`-values **and** `value`-values (for a colorAxis).

**Comment by Dunge** [comment]
Hello @pawelfus !

Thanks for the reply. As you mentioned, disabling the turboThreshold fixed my visual problem. I understand you want to leave the ticket open to fix the default behavior with heatmaps data format?

I would like to add a bit that isn't directly linked to my original problem, but still the same use case. In some extreme situation, my data can explode into a VERY large set (x axis: one per minute for a day (1440) and y axis: up to 50 rows, which give a total of 72000 cells).

Setting any set of data individually works, even with setData() and it looks fine and is taking an adequate amount of time to process. Problem arise when I first set a data set and then replace it with a second call to setData() with another set of values. The browser freeze until it say the javascript is not responding and get killed. My guess is that animations is killing the system, but even if I set the animations globally disabled in the series options, and in the setData() parameters, I still can't get it to work. Do you have any other idea of options I can play with that would improve the reaction speed?

**Comment by pawelfus** [comment]
Yes, I want to keep this ticket open, to fix the original issue.

Regarding performance, I suggest to try boost.js module or use as a base this demo: http://www.highcharts.com/demo/heatmap-canvas You have a lot of points, and adding them to the DOM may cause this "javascript is not responding" issue. Could you check this?

**Comment by Dunge** [comment]
Thank you so much! I stumbled upon this sample before, but haven't realized there was a function to render using HTML5 canvas hidden in there. It's much more faster, and even fix the small seams that sometimes appeared between cells. This should be the default renderer when supported!

Note that there a line in this sample relating to this ticket:
turboThreshold: Number.MAX_VALUE // #3404, remove after 4.0.5 release

Unfortunately, only one small hiccup with this solution still.. If I resize the chart containing the container and call reflow on it (from my #6137 issue), the cells and axis resize correctly, but the bottom portion of the chart don't redraw. I guess this is due to canvas width and height attribute not being refreshed. I will try to listen to the redraw event and see if I can update these values and come back with my results.

**Comment by pawelfus** [comment]
Thanks!

It's not a default rendered as it comes with limitations (see the header in the source file). Could you explain what do you mean by "the bottom portion of the chart" ? Do you mean legend?

**Comment by Dunge** [comment]
@pawelfus

Sorry, I don't want to confuse things:

1. My previous comment was using the code from the sample you linked and not the boost module. It's extremely fast to render, but cause refresh problems. I do not mean the legend, but every cells that are positioned in an area that is in a zone larger than the previous size. Screenshot: http://i.imgur.com/OQ0HK0R.jpg

2. Using the boost.js module and the heatmap type, it does not improve the performance at all. Everything is as slow as before. I modified the area chart sample to use heatmap instead. As you can see, pressing the button to push a new data set will freeze your browser: http://jsfiddle.net/j42fhdwk/ . On the other hand, size refresh works fine and other chart types are extremely fast (scatter plot look nice).

**Comment by pawelfus** [comment]
Thanks for the clarification!

1. That may be simple a bug, but it's just a demo... so see below:

2. Yes, that's one of the limitations in boost.js - in the source file ( https://code.highcharts.com/modules/boost.src.js ) you can find: 

>         * Development plan
>         * - Column range.
>         * - Heatmap. Modify the heatmap-canvas demo so that it uses this module.
>         * - Treemap.
>         ....

Heatmap is not supported at this moment by boost.js, but it certainly will.

**Comment by Dunge** [comment]
For anyone stumbling on this post in the future, I managed to fix the resize of the boost heatmap demo by simply adding this line:

`this.image = this.chart.renderer.image('', 0, 0, this.chart.chartWidth, this.chart.chartHeight).add(this.group);`

As the first line in the "if (ctx) {}" scope for the drawPoints wrapper function.

Since there's an "add" in there, I wonder if it keep accumulating something, but for now it seems to work fine.
