### ISSUE TITLE
TypeError: Highcharts.chart is not a function

### ISSUE THREAD

**Issue by jwerre** [highcharts/highcharts#6153]
After installing Highcharts@5.0.6 via npm and running in Node I get the above error:

#### Example

    var Highcharts = require('highcharts'),
        chart = Highcharts.chart(null, {
        series: [{
            data: [1, 3, 2, 4]
        }],
        // ...
    });
   
    // TypeError: Highcharts.chart is not a function

**Comment by jwerre** [comment]
I was able to get this going using [jsdom](https://github.com/tmpvar/jsdom). I wanted to confirm that Highcharts does need a `window` and `document`? If so why the example [here](https://github.com/highcharts/highcharts#usage-in-nodebrowserifywebpack)?

**Comment by TorsteinHonsi** [comment]
Yes it needs a window and document to run. See [this gist](https://gist.github.com/TorsteinHonsi/e8a1e6971608523eb8dd), where we render a chart in JSDom by passing a window shim to Highcharts:

```js
// Require Highcharts with the window shim
var Highcharts = require('highcharts')(win);
```

> If so why the example here?
@jon-a-nygaard Can you have a look at that? Is the chart constructor out of place?
That example is for bundling files in Webpack and Browserify. @jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
> Is the chart constructor out of place?

@TorsteinHonsi Not quite certain about what you mean by out of place, but the UMD pattern seem to work as expected.
> That example is for bundling files in Webpack and Browserify

@TorsteinHonsi Yes it is, so mentioning Node is probably a bit incorrect. The [approach which jQuery is using](https://www.npmjs.com/package/jquery) looks in my opinion like a good structure, and is relatively similar to how including Highcharts would look like.  If you also agree, then I'll be happy to make the appropriate changes to our readme?

**Comment by TorsteinHonsi** [comment]
> If you also agree, then I'll be happy to make the appropriate changes to our readme?

@jon-a-nygaard Yes, as long as it is clear to the users.
