### ISSUE TITLE
Intervals of xAxis have irregular length at the end Highstock 4.2.6 

### ISSUE THREAD

**Issue by tobiasexner** [highcharts/highcharts#6155]
#### Expected behaviour
Intervals on xaxis should be equal. In given snpashot 7-day-duration has different length, 11.Dec to 18.Dec is longer than all intervals before (e.g. 4.Dez to 11.Dez). In snapshot days are marked as light-grey xAxis-plotband.

#### Actual behaviour
Length of intervals on xaxis are not equal. 
In given snpashot 7-day-duration has different length, 11.Dec to 18.Dec is longer than all intervals before (e.g. 4.Dez to 11.Dez). In snapshot days are marked as light-grey xAxis-plotband. 

![xaxis-intervall-not-equal-in-december](https://cloud.githubusercontent.com/assets/24605590/21260342/b77d8a3c-c385-11e6-83d4-bdd2ea2a76db.PNG)
![xaxis-intervall-not-equal-in-december-zoomed](https://cloud.githubusercontent.com/assets/24605590/21260348/badb8a44-c385-11e6-91ff-a54013521ed2.PNG)

#### Live demo with steps to reproduce

Could you give an answer how these intervals are calculated?
It only appears in some special cases. Option DataGrouping is enabled.

#### Affected browser(s)
Firefox 46.0.1, 
Chome 55.0.2883.87

**Comment by pawelfus** [comment]
Hi @tobiasexner 

This is caused by [`xAxis.ordinal`](http://api.highcharts.com/highstock/xAxis.ordinal) option. Have you tried to disable it?

**Comment by tobiasexner** [comment]
Thank you very much! 
Now it works fine with disabled xAxis.ordinal.

Issue could be closed.
