### ISSUE TITLE
Poor performance with forced dataGrouping

### ISSUE THREAD

**Issue by magnushavgry** [highcharts/highcharts#6156]
It seems like a variation of issue #5388 has resurfaced with the release of Highstock v5.0.1.

#### Expected behaviour
No performance impact whatsoever when rendering small datasets.

#### Actual behaviour
In the linked broken JSFiddle it takes 5-10 seconds to render the chart and the browser becomes unresponsive. With larger datasets it's even worse and causes some clients to crash.

#### Live demo with steps to reproduce
Working (Highstock v5.0.0): http://jsfiddle.net/hfatxg26/2/
Broken (Highstock v5.0.1): http://jsfiddle.net/hfatxg26/3/

#### Affected browser(s)
All.

**Comment by TorsteinHonsi** [comment]
It happens since 2d27725, when the datetime tick positioning algorithm was updated. This algorithm is used by both datetime axis and data grouping.
