### ISSUE TITLE
Offline exporting module: on Edge has wrong background color

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6157]
#### Behaviour
Exported to JPEG or PNG chart is almost all black and size is wrong - right part is clipped out of the image by like 30%.

On master branch version of the module exporting is not working at all.

#### Live demo with steps to reproduce
Export to JPEG or PNG and view the exported image:
http://jsfiddle.net/vepx7mqs/1/

On master:
http://jsfiddle.net/vepx7mqs/

#### Affected browser(s)
Edge

**Comment by oysteinmoseng** [comment]
Fails since 4.2.6. Before that, Edge PNG fell back to export server. So somehow this has never worked, but seems strange that it hasn't been picked up before. Will investigate further.

**Comment by oysteinmoseng** [comment]
Related to #5410, which probably never got a proper conclusion for Edge with no embedded images.

**Comment by oysteinmoseng** [comment]
> Also found that Edge has a bug where it capitalizes several SVG attribute names (fill="red" becomes FILL="red"), which appears to mess up things across the board. I got downloading to work by using CanVG, but because of this bug the rendering is all wrong.

Looks like Edge and CanVG are not cooperating well, so browser detection and graceful fall back might be the only option. Before the fixes to #5410 Edge always failed and fell back anyway.
