### ISSUE TITLE
Problem with documentation at panKey

### ISSUE THREAD

**Issue by HACKHERS** [highcharts/highcharts#6160]
Hello, I noticed a problem with panKey, there isn't any information about keys. I have tried "space" but no luck. Is there any chance you could add information about keys in the documentation?

One more thing is there anyway I use left click for panning? If not you could leave this as a suggestion.

Thanks,

Source: http://api.highcharts.com/highcharts/chart.panKey

**Comment by pawelfus** [comment]
Actually, `panKey` can be one of:

- [`shift`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/shiftKey)
- [`alt`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/altKey)
- [`ctrl`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/ctrlKey)

> One more thing is there anyway I use left click for panning?

Yes, you can. You should disable zooming, and it will work without the panning key:  http://jsfiddle.net/nemszbtx/

**Comment by TorsteinHonsi** [comment]
I have added more information to the docs: http://api.highcharts.com/highcharts/chart.panKey
