### ISSUE TITLE
Columnrange width changing when series are hidden/shown even if axis extremes are fixed

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#6161]
#### Expected behaviour
Columnrange series type should have fixed width of columns when series are shown or hidden without recalculation of axis extremes. It looks to be working fine in 5.0.2 Highcharts version:

http://jsfiddle.net/g5gk1ug6/1/

#### Actual behaviour
Right now columns width is changing when series are shown/hidden.

#### Live demo with steps to reproduce
http://jsfiddle.net/g5gk1ug6/

To reproduce, hide black series.

**Comment by TorsteinHonsi** [comment]
Simplified to column: http://jsfiddle.net/highcharts/g5gk1ug6/4/
It happens since 0799761.

It is in direct conflict with #5961. What you expected can be achieved by setting chart.ignoreHiddenSeries: http://jsfiddle.net/highcharts/g5gk1ug6/6/

**Comment by pawelfus** [comment]
**Another solution:**
We can use [`series.pointRange`](http://api.highcharts.com/highcharts/plotOptions.columnrange.pointRange) - demo: http://jsfiddle.net/g5gk1ug6/3/
