### ISSUE TITLE
How to  implement high charts  into  angular 2 application  

### ISSUE THREAD

**Issue by RobertRajcool** [highcharts/highcharts#6163]
Could you please add read me file in angular2 application

**Comment by oysteinmoseng** [comment]
@RobertRajcool At this point we do not provide an official Angular 2 directive for Highcharts, could you be more specific as to which application you are referring to?

Here is a link to a 3rd party Angular 2 directive that is being used by some our users: https://www.npmjs.com/package/angular2-highcharts.
