### ISSUE TITLE
Series step parameter not working correctly with type: 'datetime'

### ISSUE THREAD

**Issue by eithed** [highcharts/highcharts#6164]
When defining options as:

xAxis: {
 type: 'datetime'
},
series: {
 step: 'center',
}

the displayed labels / steps are in wrong position.

#### Expected behaviour

Labels should display between steps

(also, if not defining type: spline, the step behaviour is weird - it seems to put steps between the labels, but actual tick is above the label)

#### Actual behaviour

Labels display above the step

#### Live demo with steps to reproduce

http://jsfiddle.net/knz9w6ac/

**Comment by pawelfus** [comment]
Hi @eithed 

There is no option for spline called `step` ([docs](http://api.highcharts.com/highcharts/plotOptions.spline)). Only `line` series supports [`series.step`](http://api.highcharts.com/highcharts/plotOptions.line.step).

Demo: http://jsfiddle.net/knz9w6ac/1/

**Comment by pawelfus** [comment]
Hi @eithed 

There is no option for a spline series called `step` ([docs](http://api.highcharts.com/highcharts/plotOptions.spline)). Only `line` series supports [`series.step`](http://api.highcharts.com/highcharts/plotOptions.line.step).

Demo: http://jsfiddle.net/knz9w6ac/1/

Regarding ticks position on xAxis, let me explain. Highcharts ticks positioner renders tick at 00:00 for each day, not 12:00. As you noticed `step` option is set on series level, not xAxis so that option doesn't change behaviour of ticks.

You can achieve that result using [`tickPositioner`](http://api.highcharts.com/highcharts/xAxis.tickPositioner), for example: http://jsfiddle.net/knz9w6ac/2/

**Comment by eithed** [comment]
Hi @pawelfus 

Fair point - I thought that there's no difference between spline and line, as spline is just Berzier set upon the given edges, but indeed looking at [http://api.highcharts.com/highcharts/series%3Cspline%3E](docs) for spline, indeed no `step` is defined.

With your second point, when using `type: 'line'` isn't it a bug then that `step` renders the tick at 00:00 when using `type: 'datetime'`, rather that at 12:00 (I'd also assume that `step: 'right'` should display at 24:00, but I've not checked that) as you've mentioned? I guess a note in the documentation would be enough, specifying that step doesn't work with `datetime` type (as I guess the label is displayed between two adjacent values - here, timestamps, which are very close together, so, changing the `step` doesn't amount to anything, but that's just guesswork).

Thank you for that option! It completely eluded me and will be using it :)

**Comment by pawelfus** [comment]
There is one significant difference between linear and datetime axes. For example ticks `[200, 400, 600, 800, 1000]` are perfectly fine for a linear axis (nice, rounded numbers), however the same extremes on datetime axis, will render as `[300, 600, 900]` (5s, 10s, 15s) or `[300, 600, 900, 1200]`  (5s, 10s, 15s, 20s) - depending on exact data of course. As you can see, these ticks won't start at the same place and this is exactly what happens in your case. In other words, datetime axis is more strict, when deciding ticks.

When datetime axis decides to use daily ticks, then ticks are rendered always at 00:00, not at 12:00 nor 06:00 etc. I don't think that `step` doesn't work `datetime` type. But maybe I'm missing something? 

PS: I really appreciate your feedback here!

**Comment by TorsteinHonsi** [comment]
To put it simply, the X axis doesn't look at the data points or step option at all when laying out the ticks, it just looks at the data min and max and places the ticks according the axis options.

**Comment by eithed** [comment]
Oh, then I misunderstood what step parameter does - it actually controls at what point of the given "spline" the step should happen (as, if it's defined as 'center' then value increase/decrease and appropriate line draw will happen between two ticks). I was under impression it controls the label placements in the x axis as well, but that has nothing to do with it!

Apologies for taking your time and I appreciate the explanations :) Thank you very much!
