### ISSUE TITLE
Highmaps: dynamically switching maps keeps previous map on page

### ISSUE THREAD

**Issue by briangroelinger** [highcharts/highcharts#6165]
#### Expected behaviour
switch map from CA to US and have the previous map not be on the page at all, but show the new map i want to show only. 

#### Actual behaviour
Any state/territory/region that has no data will still appear, even when completely wiping out the html and re-creating the highmap

#### Live demo with steps to reproduce

load data
click switch button which re-instantiates the highmap object and loads a new set of data
all territories/states/regions that had no data filled in on the previous map will still appear in the new map

http://jsfiddle.net/LLExL/6830/

#### Affected browser(s)
ALL

**Comment by oysteinmoseng** [comment]
This is because Highcharts will in some cases mutate the input data. The quick workaround is to pass in a copy of the data array: http://jsfiddle.net/LLExL/6832/.

See issue #4259.

Closing this as duplicate, please follow up further discussion there.
