### ISSUE TITLE
Highcharts events issue with plotbands in Date Range Line Series

### ISSUE THREAD

**Issue by sorb999** [highcharts/highcharts#6166]
Highcharts plotbands event is not working when trying to use it with **Date Range Line Series**

Here is my [fiddle](http://jsfiddle.net/sorb999/cup7h00L/2/)

Expected behavior : click should show alert box.

Actual behavior : event is not working at all.

Affected browsers : All Browsers.

**Comment by pawelfus** [comment]
Thank you for reporting this issue!

*Internal note:*
It applies only to Highstock, in Highcharts it works fine: http://jsfiddle.net/cup7h00L/3/ - most probably it's connected to wrapped `getPlotLinePath` method [here](https://github.com/highcharts/highcharts/blob/21856014c6e97e43840ec2ea4c3ecc4ee9be1333/js/parts/StockChart.js#L208).

**Comment by morganfree** [comment]
I think a plot band event is blocked by the following crosshair.
http://jsfiddle.net/cup7h00L/8/
With crosshair's pointer-events set to none the event seems to work. http://jsfiddle.net/cup7h00L/10/

**Comment by pawelfus** [comment]
@morganfree - that was my first assumption too, but: http://jsfiddle.net/cup7h00L/11/ Click "All" and click on the first plotBand.

**Comment by sorb999** [comment]
@morganfree - Thanks for showing interest in it. :+1: 
@pawelfus - How much time is it going to take to fix it?

**Comment by pawelfus** [comment]
I will take care of it next week.
