### ISSUE TITLE
Problem with incorrect country borders

### ISSUE THREAD

**Issue by AleksandarVelk** [highcharts/highcharts#6167]
Hello Highcharts Team,
I using highmaps. But about one country "Western Sahara" i think that the borders are incorrect, comparing with google maps I found the differentness which I present on next image:

This is the google maps:
http://prnt.sc/dl7wb2

and this is the highmaps:
http://prntscr.com/dlor66

And this situation is on all highmaps.

Thank you in Advance, I am waiting for your response.

Greetings.

**Comment by KacperMadej** [comment]
Thank you for reporting the issue. Situation of Western Sahara is [quite complex](https://en.wikipedia.org/wiki/Western_Sahara#Stalling_of_the_referendum_and_Settlement_Plan).

Currently there is no map with a different view on Western Sahara in Highmaps map collection, so you would need to [create a custom map](http://www.highcharts.com/docs/maps/custom-maps).

If you have a source that we could use for a map that you would like to see in the Map Collection, please let us know.

**Comment by oysteinmoseng** [comment]
Leaving this open to allow for discussion around the topic.

Google Maps, as you can see, shows Western Sahara as a disputed territory using a dashed line in most areas. Depending on where you use Google Maps from it might show this differently.

Our current map shows one of the common ways to visualize the situation, but there are others, and it might be worth looking into having those alternatives available as well.

**Comment by mekhatria** [comment]
It is a good practice to stick to the **UN maps** and **be neutral** for disputed areas:
http://www.un.org/Depts/Cartographic/map/profile/wsahara.pdf
http://www.un.org/Depts/Cartographic/map/profile/morocco.pdf

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#9
