### ISSUE TITLE
api documentation for colorCounter

### ISSUE THREAD

**Issue by crh225** [highcharts/highcharts#6168]
#### Expected behaviour
If it exists in the code, then it should be in the api
http://api.highcharts.com/highcharts/chart.colorCounter

#### Actual behaviour
It doesnt exist

#### Live demo with steps to reproduce

N/A
#### Affected browser(s)
all

**Comment by crh225** [comment]
Im trying to update the typings for highcharts.
https://github.com/highcharts/highcharts/issues/6138
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13391

In order to make a pull request for DefinitelyTyped, they need documentation of the propety, colorCounter. It does not exist on the api website.

**Comment by oysteinmoseng** [comment]
Related to #5990 and #6138.

At the moment, `chart.colorCounter` is an internal property that is not part of the official API. We should consider changing this, or introducing something like `chart.resetColorCounter()`.

**Comment by crh225** [comment]
@oysteinmoseng , if you guys graciously decide to add resetColorCounter() can you also add resetMarkerCounter() as well?

at our company, all charts must have the color in a certain order.

**Comment by crh225** [comment]
closed: see - https://github.com/highcharts/highcharts/issues/6138
