### ISSUE TITLE
xRange Chart timeline not shown when zoom

### ISSUE THREAD

**Issue by adrimarti** [highcharts/highcharts#6169]
#### Expected behaviour
View the data also when making zoom.

#### Actual behaviour
Everything works ok until I try to zoom the chart and one of the extremes of the data entry falls outside the viewport, since then the graphic representation is not shown.

#### Live demo with steps to reproduce
http://jsfiddle.net/gyun8q3a/1/

**Comment by larsac07** [comment]
_INFO: x-range study is being developed into a module, but is not released or documented yet_

Yes, it seems that when `point.x2` is more than the selected range max, the whole point is filtered out. I'm looking into it

**Comment by larsac07** [comment]
Thanks for reporting the issue, @adrimarti! Latest version of x-range (not production ready yet): http://github.highcharts.com/gantt/modules/xrange-series.src.js
