### ISSUE TITLE
Fill Area below line with reversed Y-axis

### ISSUE THREAD

**Issue by Imbatido** [highcharts/highcharts#6170]
Hello,

I've a question about Highcharts. I want to use Area or Areaspline. I'm using it to show sportresults of people, so I reversed the Y-axis to show the best results (1st position) on top. But when I reverse the order, the filled area also goes to the top (above the line). I just want to fill the area between the line and the X-axis. 

I found the same question on Stackoverflow, but the given answer doesn't work. Because the heighest result can differ it's impossible to set the right threshold. Any solution for this?

http://jsfiddle.net/peter/wnyjK/
http://stackoverflow.com/questions/15459433/highcharts-reversed-yaxis-but-keep-fill-area-below-spline

**Comment by pawelfus** [comment]
Hi @Imbatido - thank you for contacting us!

Do you mean something like this: http://jsfiddle.net/wnyjK/18/ ?

**Comment by Imbatido** [comment]
Exactly what I was looking for. Thanks for your help and quick reaction! 

Another quick question which I couldn't solve. Is it possible to always show 1 on Y-Axis? I've set 'min: 1' for the y-axis, but when it's a large range the 1 disappears and only shows 10-20-30-40. Is it possible to show 1-..-..-..?

**Comment by sebastianbochan** [comment]
You can use the tickPositioner / tickPositions, which allows you to customise ticks.

- http://jsfiddle.net/ub9vmyva/

This is bugtracker, so for general support questions, please contact with us by forum / email / stackoverflow. You can find more information about it here: http://www.highcharts.com/support

**Comment by pawelfus** [comment]
Updated previous demo: http://jsfiddle.net/wnyjK/20/ (added tickPositioner and disabled decimal labels on yAxis).
