### ISSUE TITLE
There is no colorAxis session on the api page

### ISSUE THREAD

**Issue by yohanleafheart** [highcharts/highcharts#6172]
Hey guys, Regarding my other issue, I searched for some info on the API, but there is no section for  colorAxis, and the links scattered on the pages goes nowhere

#### Expected behaviour
Going to http://api.highcharts.com/highcharts/colorAxis should open the API for the color axis.

#### Actual behaviour
There is nothing on that link

#### Live demo with steps to reproduce
Just click the link, or you can go to http://api.highcharts.com/highcharts/plotOptions.heatmap and click the link on colorAxis.

#### Affected browser(s)
All

**Comment by jon-a-nygaard** [comment]
Thanks for reporting. In case you are looking for it, you can find the [colorAxis section in the Highmaps API](http://api.highcharts.com/highmaps/colorAxis).

_Internal Note: Add colorAxis to the highcharts api, as we have done with Heatmap._

**Comment by yohanleafheart** [comment]
Thanks mate, I will check it there.

**Comment by pawelfus** [comment]
http://api.highcharts.com/highcharts/colorAxis is now available under Highcharts options.
