### ISSUE TITLE
HC5 - Inline styles

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6173]
#### Expected behaviour
No inline styles

#### Actual behaviour
Inline styles are still applied.

#### Live demo with steps to reproduce
We still have inline styles: 
- http://jsfiddle.net/yLu0zreg/ (check a title <text>)

#### Affected browser(s)
All browsers

<img width="1106" alt="zrzut ekranu 2016-12-23 o 11 02 08" src="https://cloud.githubusercontent.com/assets/2115686/21451851/b57f031e-c902-11e6-9102-f87b0c584706.png">

EDIT:
- errors when content-security-policy header is applied

**Comment by KacperMadej** [comment]
Another inline CSS can be found in [defaultOptions for tooltip](https://github.com/highcharts/highcharts/blob/870c3e46b40ce75945e07569b85dd4b2a670ce2b/js/parts/Options.js#L255). It is later producing `style="font-weight:bold"` in [SvgRenderer](https://github.com/highcharts/highcharts/blob/870c3e46b40ce75945e07569b85dd4b2a670ce2b/js/parts/SvgRenderer.js#L2096).

**Comment by KacperMadej** [comment]
Another problem: For [Content Security Policy](https://developers.google.com/web/fundamentals/security/csp/) `<style>.highcharts-tooltip-0{filter:url(#drop-shadow-0)}</style>` that is being added to `<defs>` when displaying a tooltip ([here in code](https://github.com/highcharts/highcharts/blob/cc73e3f0150eda5160a8e0025fc5173679981ad1/js/parts/Tooltip.js#L115-L120)) is considered violation of inline styles. 

Demo: http://jsfiddle.net/ksvbztm0/ (content of the problematic style tag in browser console)

**Comment by TorsteinHonsi** [comment]
Now that's a tough one. I don't know how we can apply the drop shadow without this inline style. It references another definition, and if we put the style rule in the external CSS, we mess up the reference. So in order to accomplish this I think we need to disable the shadows entirely or if possible avoid using filters. The same goes for the different faces of 3D columns.

A _workaround_ is to override the `Tooltip.applyFilter` function: http://jsfiddle.net/highcharts/ksvbztm0/1/

**Comment by sebastianbochan** [comment]
+1

**Comment by KacperMadej** [comment]
_Internal note:_
If we add an additional test for `tooltip.options.shadow` we wouldn’t need the `applyFilter` override.

```js
if (styledMode && options.shadow) {
      // Apply the drop-shadow filter
      this.applyFilter();
      this.label.addClass('highcharts-tooltip-' + this.chart.index);
  }
```

**Comment by TorsteinHonsi** [comment]
Actually this can be fixed directly. We just apply the `filter` as an attribute rather than a `style`. Fix coming up.
