### ISSUE TITLE
series.update causes drilldown broken

### ISSUE THREAD

**Issue by lsycxyj** [highcharts/highcharts#6174]
#### Expected behaviour
The map should drill down to deeper level.

#### Actual behaviour
The map did drill down but just the area that you clicked on was replaced by the one has drilled down, and the current level of map was still there.

#### Live demo with steps to reproduce
No live demo here since the data is too large and it isn't openly available. 

It happens when you drill down more than 2 levels and use "update" function to update tooltip or other options.

For example, now we have 3 levels of map, then you drill down to the 2nd level. Then call "update" function to change tooltip option, and click any area of the map to drill down to the 3rd level . And it will reproduce.

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @lsycxyj - thank you for reporting the issue.

However, without a live demo and with a very specific requirements (large dataset) it will be hard for us to recreate the issue and even harder to fix and test the solution. Could you contact us by email? Our support team will try to find out if this is really a bug and will help you to setup a live demo. Please, attach to the email this ticket number.

**Comment by oysteinmoseng** [comment]
Follow up by email.
