### ISSUE TITLE
Column drilldown with navigator does not work properly

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#6176]
#### Actual behaviour
A column chart with an enabled navigator and rotated x labels is not rendered properly after drill up.
The columns bottoms are trimmed.

#### Live demo with steps to reproduce
http://jsfiddle.net/uqq1h2be/
1. Click on cars
2. Click Back to Things

Turning off the animation in drilldown prevents from animating to the incorrect shape.
http://jsfiddle.net/uqq1h2be/1/

**Comment by oysteinmoseng** [comment]
Thank you for reporting. Minimal example: http://jsfiddle.net/uqq1h2be/2/.

Looks like the issue is related to the extra margin that's added by long, rotated labels.

**Comment by TorsteinHonsi** [comment]
The problem lies in the extra pane-related [clipping logic](https://github.com/highcharts/highcharts/blob/v5.0.6/js/parts/StockChart.js#L679) in Highstock. If we comment out this, the columns are not clipped.

**Comment by KacperMadej** [comment]
Solved while fixing #6363 through commit https://github.com/highcharts/highcharts/commit/fc2014697b8ef37542da645788512a381f201834 - working on master: http://jsfiddle.net/uqq1h2be/3/
