### ISSUE TITLE
Axis.update() creates duplicate shapes in 3D

### ISSUE THREAD

**Issue by paulo-raca** [highcharts/highcharts#6178]
#### Expected behaviour
The same shape should be reused, or the old one should be deleted

#### Actual behaviour
Every time Axis.update() is executed, the "background" or the graphic is duplicated

This used to work fine a while months ago -- I think the problem was introduced on Highcharts 5

#### Live demo with steps to reproduce
http://jsfiddle.net/wegwvcsk/

#### Affected browser(s)
All?
I've tested on Chrome and Firefox

**Comment by pawelfus** [comment]
Thanks for reporting!
