### ISSUE TITLE
each series area has independent color

### ISSUE THREAD

**Issue by TabSh** [highcharts/highcharts#6179]
#### Expected behavior
exactly independent linearGradient color or solid color set to each series area.

#### Actual behavior
the linearGradient color overlay on another one

#### Live demo with steps to reproduce

https://jsfiddle.net/TabGre/fyxqsq4L/1/

**Comment by sebastianbochan** [comment]
The series overlaps, because is default behaviour in area charts. You can use stacking option and draw series over themselves.

Example:
 - https://jsfiddle.net/gtd40hpp/

**Comment by oysteinmoseng** [comment]
Closing as not a bug, feel free to reopen if I misunderstood the question.
