### ISSUE TITLE
Can't get this when clicking on xAxis chart's object

### ISSUE THREAD

**Issue by royigoldi** [highcharts/highcharts#6182]
Hi,

http://jsfiddle.net/cc0wnqv6/1/

 In "this" I had a reference to a SVG element not parameters from xAxis chart's object.
How I can get the clicked ocject data?
(in the example, i want to add id property to the category, and get it when clicked on the category)

Thanks,
Royi

**Comment by sebastianbochan** [comment]
The issue is related with the custom-events extension not Highcharts. 

Related topic:
- https://github.com/blacklabel/custom_events/issues/78
