### ISSUE TITLE
Y axis label location is where the legend is 

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#6183]
The yaxis label "hides" under the plot area and is located right next to the legend 
Please view here: http://jsfiddle.net/onemenny/faq2wnjw/

**Comment by oysteinmoseng** [comment]
Thank you for reporting. Minimal example: http://jsfiddle.net/faq2wnjw/1/

**Comment by onemenny** [comment]
@oysteinmoseng is there any update regarding?

**Comment by oysteinmoseng** [comment]
It could be a float rounding issue. @TorsteinHonsi any thoughts?

**Comment by TorsteinHonsi** [comment]
Further simplified: http://jsfiddle.net/highcharts/faq2wnjw/2/

**Comment by TorsteinHonsi** [comment]
It comes from [this line](https://github.com/highcharts/highcharts/blob/v5.0.10/js/parts/Axis.js#L724), where we run correctFloat after adding ticks. Removing the `correctFloat` call will make the bug go away, but will break cases when correctFloat is needed.

**Comment by onemenny** [comment]
Is this going to be fixed @oysteinmoseng?

**Comment by oysteinmoseng** [comment]
What do you think @TorsteinHonsi, can we fix this without breaking other behavior?
