### ISSUE TITLE
SpiderWeb arearange and areasplinerange fill discontinuity

### ISSUE THREAD

**Issue by cromulus** [highcharts/highcharts#6184]
#### Expected behaviour
The area range spline should wrap around the spider web chart consistently, connecting the high and low value of each data point on in the range series.

#### Actual behaviour
the step between the last element in the series and the first element in the series on the spiderweb chart data set, the spline seems to somehow result in a negative value.

The behavior varies between different browsers, which leads me to believe this is not the expected output.

Note: the lines seem to function as expected, it is the area fill that seems to break.

This also breaks with 'arearange' as well.

#### Live demo with steps to reproduce
http://jsfiddle.net/cromulus/v0r9dtcm/

#### Affected browser(s)
Chrome: 55.0.2883.95 (64-bit)
Safari: 10.0.2 (12602.3.12.0.1)

**Comment by cromulus** [comment]
Note: the lines seem to function as expected, it is the area fill that seems to break.

I updated the jsfiddle appropriately to highlight the discontinuity of the area fill.

**Comment by cromulus** [comment]
It appears that the same issue is effecting polar arearange charts as well: 
http://jsfiddle.net/highcharts/30q95we5/
http://jsfiddle.net/highcharts/30q95we5/

**Comment by pawelfus** [comment]
Thank you for reporting!

It used to work in 4.2.1: http://jsfiddle.net/v0r9dtcm/7/

Related issue: 5528

**Comment by TorsteinHonsi** [comment]
It works as expected once we set `connectEnds` to true: http://jsfiddle.net/v0r9dtcm/8/
