### ISSUE TITLE
innerRadius not affecting gauge fill

### ISSUE THREAD

**Issue by activestylus** [highcharts/highcharts#6189]
#### Expected behaviour
When I change the `pane.background.innerRadius` to `90%` I expect the filling to also change

#### Actual behaviour
Instead only the outer wrap is scaled down, but the colored area remains out of bounds

#### Live demo with steps to reproduce
http://jsfiddle.net/dm435x8p/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @activestylus 
As you noticed this is a `background` property, so it affects only the background size. To control series size, you can use [`series/point.innerSize`](http://api.highcharts.com/highcharts/series%3Csolidgauge%3E.data.innerRadius), please take a look: http://jsfiddle.net/dm435x8p/2/

**Comment by activestylus** [comment]
Thanks for the pointer. It works
