### ISSUE TITLE
Gauge Chart needle disappears after rendering

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6192]
#### Expected behaviour
The Gauge Chart needle should be shown correctly after chart has rendered.

#### Actual behaviour
The Gauge Chart needle disappears after rendering.

#### Live demo with steps to reproduce
http://jsfiddle.net/s9g9o13y/

#### Affected browser(s)
Chrome

**Comment by oysteinmoseng** [comment]
Thank you for reporting. Minimal example: http://jsfiddle.net/s9g9o13y/1/

**Comment by TorsteinHonsi** [comment]
It is related to the pane clipping feature in Highstock. When used with the `highcharts.js` file it works fine: http://jsfiddle.net/s9g9o13y/2/
