### ISSUE TITLE
Hiding a series does not hide navigator series.

### ISSUE THREAD

**Issue by rninne** [highcharts/highcharts#6193]
#### Expected behaviour
When a series is hidden using the legend, or using setVisible() or hide() the corresponding series in the navigator (using showInNavigator) is not hidden

#### Actual behaviour
Linked navigator series remains. If you update the data points in the primary series, the navigator series will also update (kudos btw) but hiding the series does not hide the linked series in the navigator.

#### Live demo with steps to reproduce
http://jsfiddle.net/z0ag8rL8/

#### Affected browser(s)
all AFAIK

**Comment by oysteinmoseng** [comment]
Thanks for reporting, this is actually a feature we are planning to implement.

For now, here is a workaround using events: http://jsfiddle.net/qq0dc9ah.

**Comment by rninne** [comment]
Sweet,

This answers another question I had about how to get a reference to the navigator series from a series. Works a charm in my original example.

http://jsfiddle.net/z0ag8rL8/1/
