### ISSUE TITLE
References to dead clip paths after animation

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#6196]
As seen in http://jsfiddle.net/LLExL/6856/, the marker group holds a reference to a non-existing clip-path.

When removing the clip path after animation, we should also remove old references.

**Comment by TorsteinHonsi** [comment]
The practical implication is that it fails rendering in Batik.

**Comment by oysteinmoseng** [comment]
It seems the applied fix doesn't work for multiple series [example](http://jsfiddle.net/LLExL/7229/). The one added by me present in `hc5-fixes` works, but there probably was a reason we didn't use that one. @TorsteinHonsi

**Comment by KacperMadej** [comment]
@oysteinmoseng I am checking clip-paths and I am not able to find the problem in your last demo - is it resolved or I am checking something wrong?

**Comment by oysteinmoseng** [comment]
@KacperMadej The problem seems to be fixed in `5.0.10`. Closing again for now.
