### ISSUE TITLE
Weird behaviour

### ISSUE THREAD

**Issue by poolerMF** [highcharts/highcharts#6197]
Example 1:
http://jsfiddle.net/0yk0ssuc/2/
I can not make navigator smaller then half (try to catch it from left side)

Example 2:
http://jsfiddle.net/0yk0ssuc/1/
Try to make navigator bigger and then smaller - not working properly
Impossible to move navigator by dragging (or clicking on scrollbar)

Example 3:
http://jsfiddle.net/0yk0ssuc/3/
Click on Zoom 1d ... and try to move with navigation to left .. it stuck on time 10:19

**Comment by sebastianbochan** [comment]
1 / 2 )
You should set [minRange](http://api.highcharts.com/highcharts/xAxis.minRange) parameter on the xAxis.
Example:
- http://jsfiddle.net/rdz7zvkb/

3) There is no 1d active, could you update your demo?

This is our bugtracker, so for the further support, please contact with us by email / stackOverflow / forum (http://www.highcharts.com/support)

**Comment by oysteinmoseng** [comment]
Closing for now, feel free to reopen if this turns out to be a bug.
