### ISSUE TITLE
Cannot load highcharts when run inside electron

### ISSUE THREAD

**Issue by jmaicaaan** [highcharts/highcharts#6199]
I have created an angular app for my front, and I want to load it via url (localhost). Everything is working fine and good on other components but when it comes to Highcharts library for my charting, it doesn't work when I load it inside the electron using `browserWindow.loadURL()`. In my browser, google chrome, the chart is working but inside electron it is not. I've doubled check in my network panel if it's loaded and yes it is. Injected it also in my angular app correctly. 

* Electron version: v1.4.13
* Operating system: windows 10

### Expected behavior

It would load the chart normally like any browser would do.

### Actual behavior

The chart is not loading, it says `Possibly unhandled rejection: {}` when I use the Highcharts directive, `<highchart ....> </highchart>`

### How to reproduce

Here is my angular app without the web service up.
https://jmaicaaan.github.io/InventoryManagement-Beta/app/#!/

You could see that the chart is working on a browser. But when it is loaded in electron it is not. 
To reproduce it in electron, just copy & paste the above link to your electron.

My main.js file:
https://github.com/jmaicaaan/InventoryManagement-Beta/blob/master/app/main.js

**Comment by pawelfus** [comment]
Hi @jmaicaaan 

Do you have the same problem using standalone Highcharts library (without angular and highcharts-ng module)? Try to load any of our demos.

If this will work for you, then [this issue](https://github.com/angular-ui/ui-router/issues/2889) may be the reason here.

**Comment by jmaicaaan** [comment]
Feel free to close this issue. For some people who would encounter the same problem, here's the solution to fix it. 
https://github.com/electron/electron/issues/8333#issuecomment-270293652

Thanks @pawelfus
