### ISSUE TITLE
Treemap borders

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6200]
#### Expected behaviour
No borders around points

#### Actual behaviour
Borders are visible (stroke-width is 0, but I guess that is caused by wrong rect size and positions).

#### Live demo with steps to reproduce
Example:
- http://jsfiddle.net/8vyfyuzk/

#### Affected browser(s)
All

**Comment by jon-a-nygaard** [comment]
Yes, your guess is right. It was caused by the positioning logic for crisp-edges, which is not needed when there is no stroke.
[Simplified demo](http://jsfiddle.net/jon_a_nygaard/8vyfyuzk/1/)
