### ISSUE TITLE
Legend icon size increases on increasing the radius of marker

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6202]
#### Expected behaviour
Legend marker radius should not change on change of chart marker radius.

#### Actual behaviour
On increasing marker radius, legend marker radius also increases.

#### Live demo with steps to reproduce
http://jsfiddle.net/Rfaav/25/

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
At this moment this is default behaviour, but you can use a workround with linked two series. The first defines legend symbol and the second one, draw points.

Example:
- http://jsfiddle.net/sm7r1cor/

For general support, please use email / stackOverflow / forum. More information you can find here: http://www.highcharts.com/support

**Comment by TorsteinHonsi** [comment]
I agree with @sagargurtu it's a bug. It doesn't make sense to allow the legend markers to overflow the text lines.

We should go in to the [drawLineMarker](https://github.com/highcharts/highcharts/blob/v5.0.6/js/parts/Legend.js#L878) function and disallow the marker to be larger than `legend.symbolHeight`. Also check with the new Bubble markers.
