### ISSUE TITLE
yAxis extremes aren't correctly calculated

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#6203]
#### Expected behaviour
yAxis extremes should be calculated using only visible data.

#### Actual behaviour
yAxis extremes are calculated using not only visible data, but also near points that are not visible in plotArea.

#### Live demo with steps to reproduce
http://jsfiddle.net/vRDNZ/2/

To reproduce show only one scatter point in chart using navigator. 

It looks that this problem may be connected with this github topic: https://github.com/highcharts/highcharts/issues/3422

**Comment by KacperMadej** [comment]
Reopening due to the fix being reverted:  https://github.com/highcharts/highcharts/commit/b91477777e1aacd4685430b682b02708d643cd10

**Comment by KacperMadej** [comment]
Works fine - v7.0.2.
Closing as resolved.
(Scatter doesn't require sorting and sorting is not forced in Highstock anymore)
