### ISSUE TITLE
Stacked step area charts have unnecessary gaps

### ISSUE THREAD

**Issue by kpau** [highcharts/highcharts#6204]
#### Expected behaviour
Should connect lines/areas, as in the line chart (see in the example below).

#### Actual behaviour
The area chart have gaps, regardless that connectNulls is true.

#### Live demo with steps to reproduce
Create area chart with step, stacking and connectNulls enabled for series.

Example: http://jsfiddle.net/y8gLogvz/1/
In the first series there is missing data for 3:00 and 5:00, but the second series have data for every hour. If the second series have the same data, or it is removed completely, the first series will behave the same.
In the area chart the line starts from 2:00 but stops at 3:00, and there is gap between 3:00 and 4:00. The line chart does not have this issue, and the line starts from 2:00 and goes to 4:00.
The behavior for 4:00-6:00 is the same.

#### Affected browser(s)
Google Chrome 55.0.2883.87 m (64-bit).
IE 11.0.9600.18525
Firefox Developer Edition 52.0a2 (2017-01-04) (32-bit)
OS: Windows 8.1, 64-bit.

Is there a configuration that I am missing which can solve the problem?

Regards,
Kristiyan Nikolov

**Comment by TorsteinHonsi** [comment]
It is because `connectNulls` doesn't play well with stacking, it is not directly connected to `step`: http://jsfiddle.net/y8gLogvz/2/

We are currently missing an option to interpolate stacks in order to do connectNulls. The logic problem becomes more visible when the null points are not on the same x value.

**Comment by KacperMadej** [comment]
+1

**Comment by RaviDasari** [comment]
+1

**Comment by aashayjoshi** [comment]
Can someone update when we can expect the fix? This is open from more than a year.

**Comment by KacperMadej** [comment]
There's no ETA for the fix as of yet.
