### ISSUE TITLE
Tooltips of labels that include the "<" symbol aren't displayed correctly

### ISSUE THREAD

**Issue by jbgarr** [highcharts/highcharts#6205]
#### Expected behaviour
Tooltips of labels that include the "<" symbol should be displayed just like any other label as a string of text. I came across this bug when trying to display a tooltip for a chart group with a label of "< 10%".

#### Actual behaviour
Tooltips for chart groups that include the "<" symbol in their label are not displayed correctly. Only characters before the "<" symbol are shown, and if the label begins with "<" then the whole label is not shown at all, and the tooltip (that is displayed on hover) layout is broken. I assume this is caused by Highcharts treating the label as HTML.

#### Live demo with steps to reproduce
http://jsfiddle.net/jbgarr/6uy8L33n/
To see the bug, hover over the label for the first bar (< Jan) and you'll notice the tooltip is broken

#### Affected browser(s)
Tested in Chrome Version 55.0.2883.95

**Comment by sebastianbochan** [comment]
Thank you for the reporting.

You should set the [useHTML](http://api.highcharts.com/highcharts/tooltip.useHTML) flag as a true in the tooltip object.

Example:
- http://jsfiddle.net/guqn60g9/

**Comment by oysteinmoseng** [comment]
Although it can be worked around with useHTML I think this should be considered a bug

**Comment by oysteinmoseng** [comment]
@pawelfus Brought to my attention that this is actually a duplicate of #2379
