### ISSUE TITLE
Render tooltip by it's own content 

### ISSUE THREAD

**Issue by fourmisz** [highcharts/highcharts#6206]
Short text tooltip is always okay. But when i wrote long series names or category names, tooltip went to be out of the chart and couldn't see more. So I have tried many things, for example, fixed tooltip width and made `white-space` as normal.  It was okay to see long text content but didn't fit as it's content if there was short text content.

How can I implement flexable tooltip by it's content?

#### Expected behaviour
![image](https://cloud.githubusercontent.com/assets/2562653/21673745/b08e8b02-d36d-11e6-99aa-a5fe00a8f439.png)

#### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/2562653/21673341/d7b2233a-d36b-11e6-94be-4644b405e76e.png)

#### Live demo with steps to reproduce
**http://jsfiddle.net/phe8xrfa/**

#### Affected browser(s)
Chrome 55+

**Comment by jon-a-nygaard** [comment]
Hi @fourmisz 
If I understand you correctly then you are looking to limit the tooltip to a certain width and have it resized when the content is smaller. In such a case something like this example with a [maximum width of 200px](http://jsfiddle.net/jon_a_nygaard/phe8xrfa/3/) might help.

In case you are looking to keep the width fixed no matter the size of the content, then you could try something like this example with [static width of 200px](http://jsfiddle.net/jon_a_nygaard/5a0euqfr/3/)

**Comment by sebastianbochan** [comment]
You can also use a workround which uses custom tooltip.

- http://jsfiddle.net/7wVDV/147/

**Comment by fourmisz** [comment]
Thanks for all. 
I really appreciate it.
