### ISSUE TITLE
Responsive rules for plotOptions.series causes error

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#6208]
#### Expected behaviour
In responsive rules plotOptions.series changes chart's options correctly, like e.g. plotOptions.line http://jsfiddle.net/hsd19y0y/1/

#### Actual behaviour
The chart throws error `Uncaught TypeError: Cannot read property '0' of undefined`
Responsible part of code [here](https://github.com/highcharts/highcharts/blob/master/js/parts/Responsive.js#L83)
It assumes that the plotOptions.series should be a series array.

#### Live demo with steps to reproduce
http://jsfiddle.net/hsd19y0y/2/
1. Click 'Small' button
2. Open console

**Comment by KacperMadej** [comment]
Similar problem, caused by the same issue, happens if we change axis (y or x) number for series:
http://jsfiddle.net/hsd19y0y/4/
Steps as before.
Difference: [error 18](http://www.highcharts.com/errors/18) is being thrown, while the config is correct.
