### ISSUE TITLE
colorAxis: automatic range is based on first series only

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6209]
#### Expected behaviour
Automatically calculated range of a colorAxis should be based on all series using the colorAxis.

#### Actual behaviour
Range of the colorAxis based only on first series.

#### Live demo with steps to reproduce
http://jsfiddle.net/6ocbgy54/

**Comment by KacperMadej** [comment]
This problem applies also to colorAxis in Highcharts, but it's not that popular to create multiple heat map series.

http://jsfiddle.net/x80tg92q/

**Comment by TorsteinHonsi** [comment]
The fix broke the mapseries color in the `highcharts/studies/direction-arrows` demo.

**Comment by oysteinmoseng** [comment]
@TorsteinHonsi
