### ISSUE TITLE
areaspline polar curve path and area path

### ISSUE THREAD

**Issue by RaidersII** [highcharts/highcharts#6212]
#### Expected behaviour
A full plain circle.

#### Actual behaviour
A strange end curved path and a area overflowing

#### Live demo with steps to reproduce

https://jsfiddle.net/RaidersII/L41xnat0/

#### Affected browser(s)
Google Chrome 55
Firefox 50

**Comment by TorsteinHonsi** [comment]
It's a regression, failing since v4.2.2 when the area stacking and null point handling was refactored.

**Comment by TorsteinHonsi** [comment]
Interestingly, the artifacts are different for a polar spline without the area: http://jsfiddle.net/highcharts/L41xnat0/1/

**Comment by Izothep** [comment]
Resolved through a54f5b0

Working since 5.0.10
