### ISSUE TITLE
Can't update tooltip's valuePrefix and valueSuffix 

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#6218]
I want to update tooltip's valuePrefix or valueSuffix  by chart.update, but it no effect.

demo:  https://jsfiddle.net/m9uzuht9/

**Comment by sebastianbochan** [comment]
_Workaround_
Update each series:
- https://jsfiddle.net/of56mrsr/

**Comment by zhy1stgg** [comment]
Hi @sebastianbochan 

I just want to make sure it's a bug while chart.update can update toolip.share and other options but can't update valuePrefix or valueSuffix.

thanks

**Comment by oysteinmoseng** [comment]
Hi @zhy1stgg, thanks for reporting, it's indeed a bug. Sebastian's posted fiddle is just a workaround.
