### ISSUE TITLE
wrong y-axis format showed in specific range selector

### ISSUE THREAD

**Issue by a1300300** [highcharts/highcharts#6219]
#### Expected behaviour and Actual behaviour
Hello, our website is using highchart 5.0.6 library, and facing an issue at displaying y-axis value. IN the the page "https://www.macromicro.me/collections/51/us-treasury-bond", when clicking 6m or YTD in range selector, the first y-axis value at left side should be zero  or 0.0, but it is like 0.000000000000011.

#### Live demo with steps to reproduce
https://www.macromicro.me/collections/51/us-treasury-bond
In the page, click 6m or YTD in range selector, it would be seen at left side.

#### Affected browser(s)
Google Chrome 55.0.2883

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Minimized demo: http://jsfiddle.net/highcharts/L805usjh/
Fixed in the latest development branch: http://jsfiddle.net/highcharts/L805usjh/1/

This will be released with Highcharts 5.0.7 within a few weeks.
