### ISSUE TITLE
Rangeselector - inputs lost updated date on blur

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6220]
#### Actual behaviour
Changed value is lost

#### Live demo with steps to reproduce
http://jsfiddle.net/va2s7w4y/

Steps:
1. Change the date 2014-07-01 to 2014-08-01 and do to not tab or press enter
2. Click on the next text box using your mouse
3. The date change is lost.

**Comment by oysteinmoseng** [comment]
Seems to work in latest bugfixing code, though there is a (probably unrelated) problem with null areas: http://jsfiddle.net/va2s7w4y/1/.

**Comment by oysteinmoseng** [comment]
Regarding the null areas: #6001
