### ISSUE TITLE
Always 100% in total for stacked graphs

### ISSUE THREAD

**Issue by berdeter** [highcharts/highcharts#6221]
#### Expected behaviour
Sum of percentages on a stack is always 100%

#### Actual behaviour
See http://www.highcharts.com/demo/column-stacked-percent

Rounding roles are so that the sum of rounded values is not equal to the rounded value of the sum. Som in some cases when percentages are rounded the sum of rounded values is not 100% but 99% or 101%. In your example : 

Apples : 50+20+30=100 OK
Oranges 33+22+44 = 99% KO
Pears : 36+27+36 = 99% KO
Grapes : 64+18+18 = 100% OK
Bananas = 25+13+63 = 101% KO

So more KO's than OK's !

There should be a processing to adjust the percentage of one item (usually the the biggest item) up or down so that the total fits 100% all the time.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/column-stacked-percent/

#### Affected browser(s)
ALL

**Comment by KacperMadej** [comment]
This is not a bug - it is caused by `point.perventage` being rounded to full integers by `:.0f`. Here's the demo with the rounding removed: http://jsfiddle.net/fm8fsLL7/

**Comment by berdeter** [comment]
Well of course this is due to rounding. It is meaningless to propose removing the rounding as additional digits mean nothing if it exceeds the precision of the base data. If you consider your example even removing the rounding does not fix the problem. 

The sum of your Orange percentages is still not equal to 100%. It equals 99.999999999999% which is not 100%.

To be correct the displayed percentages must be adjusted in some way. By definition the sum of percentages must be exactly equal to 100%.

Is there at least a way to plug-in some logic that could fix the displayed percentages ? That means there should be a callback invoked in the construction of the graph where percentages can be computed by a customer provided algorithm that would turn 33+22+44=99% into 33+22+45=100%

**Comment by KacperMadej** [comment]
It might be rather hard to determinate which value should be changed to ensure a sum of 100%. This might suggest that data is different in a chart than in reality. Fo example this [demo](http://jsfiddle.net/fm8fsLL7/1/) - if we change any of the values in tooltip, then this will suggest that one of the values is bigger than the rest while all are equal.

**Comment by berdeter** [comment]
Of course That's why I was just suggesting that a custom callback logic would be used to adjust the values. Does such a callback mechanism exist ? Is there a way to plug-in such behavior ? Would it be possible to keep this ticket open as an enhancement just to provide the callback mechanism or a way to implement the percentage trick ?

**Comment by TorsteinHonsi** [comment]
Altough I see the problem, there's also a problem with the solution - if we round off 33.333333% and display it as 34% in order to make the 100% stack go up, that's also wrong...

Anyway, I suggest you add a custom point option to use in the tooltip: http://jsfiddle.net/highcharts/mmdmayde/. Next step now would be to implement a function to automatically calculate the false percentages.

**Comment by berdeter** [comment]
Thank you for the workaround. The function to automatically calculate the false percentage remains interesting for me but the workaround can fix the problem in the mean time.

**Comment by KacperMadej** [comment]
If you want to display the values using fractions (to get e.g. `33 1/3` instead of `33.333333...` or rounded `33`), then you could use a third party library for fraction calculations (e.g. [mathjs](http://mathjs.org/)) and a custom format. Demo: http://jsfiddle.net/cczu1m7o/

**Comment by berdeter** [comment]
Great. I've made a fix in the fiddle (misplaced %) : http://jsfiddle.net/cczu1m7o/2/
