### ISSUE TITLE
Series line clipping on axis limit

### ISSUE THREAD

**Issue by GabrielMarcilio** [highcharts/highcharts#6225]
The series lines are clipped when its values are on the axis limits, as it can be found [here](http://jsfiddle.net/zxmj0dfe/1/). Note that the line width is half of the expected in values 0 and 5.

Searching on stackoverflow i found the clip flag on series that causes the [expected behavior](http://jsfiddle.net/zxmj0dfe/2/)

However, this flag does not seems to work with [color zones](http://jsfiddle.net/zxmj0dfe/4/)

This flag is not part of the series public api, so let me know if there is a better way to reproduce the expected behavior with color zones without changing the axis limits.

**Comment by oysteinmoseng** [comment]
Thank you for reporting. Any reason why `clip` is not in the API @TorsteinHonsi?

**Comment by TorsteinHonsi** [comment]
> Any reason why clip is not in the API @TorsteinHonsi?

Yes, it was created internally for series that are allowed to live outside of the plot area, like pie series. As the OP correctly observes, it is not quality assured for other scenarios. For example, a line series with values outside the plot area will fail terribly: http://jsfiddle.net/highcharts/zxmj0dfe/8/.

Does the `clip` option solve your problem @GabrielMarcilio or do you need a more stable solution? Possible ideas would be to make the `offset` option also [move the clipping rectangle](http://jsfiddle.net/highcharts/zxmj0dfe/9/), or to introduce a new option to increase the clipping rectangle by for example 5 pixels.

The last approach would look [something like this](http://jsfiddle.net/highcharts/zxmj0dfe/10/).

**Comment by oysteinmoseng** [comment]
And if you don't want top clipping: http://jsfiddle.net/zxmj0dfe/11/

**Comment by GabrielMarcilio** [comment]
Thanks for the Quick answer

@TorsteinHonsi : The clip option would solve my problem but it does not seem to work with [color zones](http://jsfiddle.net/zxmj0dfe/4/).

@oysteinmoseng : The option to move the clip rectangle also do not work with [color zones](http://jsfiddle.net/zxmj0dfe/12/).

In both cases i still have a top clipping. I Guess that the clipping calculation for color zones is not taking the clipping rectangle (or the clip flag) into account.

**Comment by oysteinmoseng** [comment]
@GabrielMarcilio Here is a hacky workaround to allow zones: http://jsfiddle.net/zxmj0dfe/13/

**Comment by GabrielMarcilio** [comment]
@oysteinmoseng  Thanks for the quick answer. Unfortunatelly i was not abble to directly apply your suggestion. I am working with inverted chats (have not mentioned that before to reproduce the issue in a chart as simple as possible). With the suggestion that you sent i was able to remove the right clipping, but i am still facing a [left clipping](http://jsfiddle.net/zxmj0dfe/16/).

I also perceived that the results are not reliable (sometimes the fiddle has left and right clipping, sometimes it has just left).

It might be that i am not applying the correct offsets in the y / height (from what i understood in the code in inverted charts i still manipulate the height to control the horizontal size of the clipping).

Please let me know if am doing something wrong

Thanks in advance

**Comment by oysteinmoseng** [comment]
@GabrielMarcilio Well, that complicates things a bit as you now have to pad the clip rectangles for both the first and last zone. You could try something like this: http://jsfiddle.net/zxmj0dfe/17/.

**Comment by GabrielMarcilio** [comment]
@oysteinmoseng that worked out. I will keep this workaround until the fix is implemented.

Thanks for the help!

**Comment by duongquocvinh** [comment]
@oysteinmoseng: Hello, can I ask for your help ?
I have the same issue as GabrielMarcilio, and solve it by your solution http://jsfiddle.net/zxmj0dfe/13/
But I have another issue, if I click on the legend to hide the series and active it again, the redraw event of chart is called and the line of axis limit become half-width again
Can you support me this issue

Thanks in advance!

**Comment by duongquocvinh** [comment]
@sebastianbochan 
Yes, it's worked
Thanks for your help !
