### ISSUE TITLE
Disappearing halo

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6227]
#### Behaviour
In the situation where one point overlaps another and when the hover at them occurs, tooltip of the point with higher zIndex shows up, which is fine. The problem is when after that, if hover on a series of ‘covered’ point within close distance occurs, the halo disappears while tooltip remains in the same place.

#### Workaround
Setting tooltip.snap property with high value helps.

#### Live demos
https://jsfiddle.net/d_paul/31q2fcay/ - stickyTracking set to true (does not work)
https://jsfiddle.net/d_paul/31q2fcay/1/ - stickyTracking set to false (works)
https://jsfiddle.net/d_paul/31q2fcay/2/ - with snap property set (workaround)

**Comment by jon-a-nygaard** [comment]
Quite possibly related to #5914, work in progress found in dev-runPointActions branch. Aiming to release fix in upcoming maintenance version 5.0.7.

**Comment by jon-a-nygaard** [comment]
Considered fixed as of version 5.0.8. Please give a comment should this be incorrect.
