### ISSUE TITLE
A bug with spline stacked graph

### ISSUE THREAD

**Issue by naguibihab** [highcharts/highcharts#6230]
#### Expected behaviour
To draw a stacked spline area chart with +ve and -ve values

#### Actual behaviour
The lines overlap each other and are not going on the correct y-axis

#### Live demo with steps to reproduce
http://jsfiddle.net/73bbx5wf/

#### Affected browser(s)
I just tested on Chrome

**Comment by TorsteinHonsi** [comment]
In area-like charts, points will be stacked successively whether they are positive or negative, resulting in overlapping areas. You can change that by assigning two different stacks: http://jsfiddle.net/highcharts/73bbx5wf/3/

**Comment by naguibihab** [comment]
Thank you for the prompt reply :)
