### ISSUE TITLE
Development branch: mapline colors broken

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#6232]
Local test suite, `highcharts/studies/flight-routes`

Fails since d0dee80

**Comment by oysteinmoseng** [comment]
Not sure what actually fails here? Looks like point marker size changed slightly, but that's all I can see - probably due to the switch to SVG arcs for circles. Everything related to null points seem correct as far as I can see.

**Comment by TorsteinHonsi** [comment]
Below is a screenshot running the master in the test suite. It's in Chrome. As you can see the map line colors are gone.

![skjermbilde 2017-01-12 kl 09 39 24](https://cloud.githubusercontent.com/assets/227836/21882510/0f4bf53e-d8ab-11e6-8741-0dbb1f391638.png)

**Comment by oysteinmoseng** [comment]
Commit that fixes this in `hc5-fixes` a20312016fd1cadabb1a5e8a787282454e6ec5c6
