### ISSUE TITLE
Range Selector is not hidden on export

### ISSUE THREAD

**Issue by pjagajitprusty** [highcharts/highcharts#6233]
#### Expected behaviour
Range selector should not be visible if it's not enabled for exporting mode.

#### Actual behaviour
It's coming when I am exporting to PNG.

#### Live demo with steps to reproduce

http://jsfiddle.net/23ey3tn0/

#### Affected browser(s)
Mac OsX/ Chrome 55V

**Comment by pawelfus** [comment]
Hi @pjagajitprusty 

It works fine for me (osx + chrome 55), here is the exported chart:

![most-chart](https://cloud.githubusercontent.com/assets/1453926/21857070/7d1ddd48-d824-11e6-961b-dc87c0c71912.png)

**Comment by pjagajitprusty** [comment]
@pawelfus Range selector is coming in the exported image u sent.

**Comment by sebastianbochan** [comment]
I also was not able to replicate the issue. I exported to PNG and JPG, which format do you use? Do you have your own exporting server or use default option (export.highcharts.com) ?

**Comment by oysteinmoseng** [comment]
@pjagajitprusty I believe you are referring to the navigator. See http://www.highcharts.com/docs/chart-concepts/understanding-highstock. Try disabling `navigator` and `scrollbar` in the exporting options: http://jsfiddle.net/23ey3tn0/4/.

**Comment by pjagajitprusty** [comment]
@oysteinmoseng Thanks for the clarification! & Sorry for the misunderstanding
