### ISSUE TITLE
series<bar>.zones doesn't change border (borderColor & dashStyle)

### ISSUE THREAD

**Issue by psingler** [highcharts/highcharts#6234]
#### Expected behaviour
Expected series<bar>.zones to be able to change dashStyle, borderColor etc.

#### Actual behaviour
No change in dashStyle, borderColor etc. occurs.
Change in Color works fine

#### Live demo with steps to reproduce

http://jsfiddle.net/v0Lxy27d/

#### Affected browser(s)
Firefox 50.1.0
IE 11

**Comment by sebastianbochan** [comment]
Problem is also reproducible in the Chrome (55.0.2883.95)

**Comment by TorsteinHonsi** [comment]
This is not a workaround but rather a different approach - Did you consider creating a separate series for the Durchschnitt? http://jsfiddle.net/highcharts/v0Lxy27d/1/

**Comment by Kiyus7** [comment]
Problem with creating a different series (apart from the fact it's much less convenient) is that when you switch from column/bar to line/spline, the method to have the last bar/segment dotted is not the same (for a line/spline you need a series with two points, to create the dotted segment ; for a column/bar you just need one point). So if you have a graph that proposes to switch from one type to another, it becomes a nightmare to handle.

Also it's a shame the zone option doesn't work as intended, as it's very useful!

Any chance this gets fixed?

**Comment by pawelfus** [comment]
Hi @Kiyus7 

Thanks! Did you try zones in the styled mode? In styled mode, you are not limited to the JS API options, you can change anything via CSS, take a look: http://jsfiddle.net/axe7ubyk/
