### ISSUE TITLE
Tooltip getting broken 

### ISSUE THREAD

**Issue by nishanth-satmetrix** [highcharts/highcharts#6236]
#### Expected behaviour

Tooltip should be proper 
#### Live demo with steps to reproduce

![tooltipbroken](https://cloud.githubusercontent.com/assets/24522559/21888905/5b020c5c-d8ec-11e6-83d0-bedd463565b5.jpg)

#### Affected brows
All browsers

Thanks in Advance
Nishanth

**Comment by sebastianbochan** [comment]
Please try to set [useHTML](http://api.highcharts.com/highcharts/tooltip.useHTML) as a true. Is your tooltip's content a image?

**Comment by nishanth-satmetrix** [comment]
yes its true

**Comment by sebastianbochan** [comment]
The issue is duplicate of https://github.com/highcharts/highcharts/issues/6211
