### ISSUE TITLE
Wrong labels for multiple axes using labels.formatter in exporting.chartOptions after exporting [5.0.4+]

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6238]
#### Expected behaviour
After exporting chart, image should display 2 yAxes with labels set in exporting.chartOptions with formatter.

#### Actual behaviour
After exporting chart, image shows 2 yAxes with same labels.

#### Live demo with steps to reproduce
1. Click export button
2. Look at exported image

Works well in 5.0.3, broken since 5.0.4
https://jsfiddle.net/5h2fwycf/

5.0.3
https://jsfiddle.net/5h2fwycf/1

**Comment by oysteinmoseng** [comment]
Thank you for reporting this.

**Comment by TorsteinHonsi** [comment]
Fixed in v5.0.7: https://jsfiddle.net/highcharts/5h2fwycf/2/
