### ISSUE TITLE
Disabling the legend in HighMaps shows some dots at the upper left corner

### ISSUE THREAD

**Issue by flegallo** [highcharts/highcharts#6242]
#### Expected behaviour
It should disable the legend without any side effets

#### Actual behaviour
We can see 2 dots at the upper left corner of the charts. In the DOM tree, there is also some `<text>` elements:
```
<text x="0" style="color:#666666;cursor:default;font-size:11px;fill:#666666;">0</text>
<text x="0" style="color:#666666;cursor:default;font-size:11px;fill:#666666;">100</text>
<text x="0" style="color:#666666;cursor:default;font-size:11px;fill:#666666;">200</text>
<text x="0" style="color:#666666;cursor:default;font-size:11px;fill:#666666;">300</text>
```

#### Live demo with steps to reproduce
http://jsfiddle.net/heq8c5tr/

#### Affected browser(s)
Chrome

**Comment by oysteinmoseng** [comment]
Thank you for reporting. Minimal example: http://jsfiddle.net/90te1vxv/1/

**Comment by TorsteinHonsi** [comment]
Looks like orphaned color axis labels. The color axis needs to check if the legend is enabled at all. Remember to test `legend.update` also to toggle enabled/disabled.

**Comment by flegallo** [comment]
Any updates?

**Comment by oysteinmoseng** [comment]
@flegallo The issue is with color axis labels, as Torstein mentioned. A temporary workaround can be to disable these explicitly: http://jsfiddle.net/90te1vxv/3/.

We'll look further into the issue as soon as possible.

**Comment by flegallo** [comment]
Thanks for the workaround!
