### ISSUE TITLE
data labels are not up to speed with markers

### ISSUE THREAD

**Issue by imcullan** [highcharts/highcharts#6245]
#### Expected behaviour
The data labels are supposed to be in sync with the markers.

#### Actual behaviour
The data labels lag behind the markers.

#### Live demo with steps to reproduce
Since a live dataset is required, there is no reproducible example, but there are about 10000 data points to make this graph.
http://rpubs.com/cullan/nba-play

**Comment by oysteinmoseng** [comment]
Without seeing how your chart is configured it's hard to give any advice on this. Would you be able to make an example with a limited dataset? It looks like it could be an animation issue, so you could try disabling animation and see if that resolves the issue.

**Comment by imcullan** [comment]
Thanks oystein! It worked after disabling the animations on the chart level! I tried doing it on the scatter level and it didn't work because it only applied the animations on the initial load (I didn't realize that until now...)
