### ISSUE TITLE
HighChart display data Issue in stacked barchart

### ISSUE THREAD

**Issue by mssarul361** [highcharts/highcharts#6248]
I am using Highchart for my reporting purposes. I am facing the issue while displaying the details which exceeds certain limit.

As per the below screen shot I am trying to display the details like user Vs count.The issue I am facing that after certain number of user (say 15) the chart doesnot shows the user details and some of the user label is missing but the count is showing in the chart. Please refer the 'yellow' marked areas for the 
details.

Also the count in the stack for some user is missingand please refer the 'blue' marked area for the details.

What I suspect is that there could be an issue in highchart itself when the category list exceeds some number. I have tried in highchart demo section as well and facing the same issue.
![highchart](https://cloud.githubusercontent.com/assets/25143305/21970882/0dadfe50-dbe6-11e6-93a2-bef69326edbf.jpeg)

#### In JSFiddle below link to given demo

http://jsfiddle.net/makarul361/4qc92zmz/2/

**Comment by oysteinmoseng** [comment]
It sounds and looks like you are simply running into label collisions. Highcharts will automatically hide labels if there isn't room to display them. This usually makes sense, as overlapping labels tend to be unreadable anyway.

There is an option to allow overlapping data labels for a series, [dataLabels.allowOverlap](http://api.highcharts.com/highcharts/plotOptions.series.dataLabels.allowOverlap): http://jsfiddle.net/vwcja91b/. It looks like enabling zoom, or increasing the size of your chart might be more suitable for your use-case, though.

I'm closing this for now. Feel free to reopen if I misunderstood your problem.

**Comment by mssarul361** [comment]
@oysteinmoseng  When I increase the div width and height to now data will be  shown then export the highchart facing same  issue in chart i.e Highchart export menu to choose jpeg or png  to  missing data in chart.

![chart](https://cloud.githubusercontent.com/assets/25143305/22006254/8766cce0-dca4-11e6-8e3a-80f14bb76c44.jpeg)

**Comment by oysteinmoseng** [comment]
@mssarul361 
1) Highcharts is responsive and will adapt to the container size. It is possible, though, to set the size at runtime with [Chart.setSize](http://api.highcharts.com/highcharts/Chart.setSize), so you could dynamically try to increase the size. [This example](http://jsfiddle.net/gh/get/jquery/3.1.1/highcharts/highcharts/tree/master/samples/highcharts/studies/axis-staticscale) does something similar for height.

2) If you set `Chart.width` the exporting chart will respect this setting. You can also set the width explicitly for exporting only with [exporting.width](http://api.highcharts.com/highcharts/exporting.width)
