### ISSUE TITLE
Must the xAxis's value type of bubble be number?

### ISSUE THREAD

**Issue by codepandy** [highcharts/highcharts#6249]
Hi,

now I use the chart of bubble,I want to set the xAxis is a string,because when I set it is a number,the tickInterval is ugly,for example [1,2,40,1000]
whether can I  set the xAxis  by string.

**Comment by oysteinmoseng** [comment]
You can absolutely use strings for the x-value. Just use a category axis: http://jsfiddle.net/vtyyyhwm.

**Comment by codepandy** [comment]
@oysteinmoseng You are so cool,but how to set the bubble's color?
`http://jsfiddle.net/jason_pandy/upov9ha6/`
the high is ,the middle is green and the low is yellow.

**Comment by codepandy** [comment]
I have resolved the problem.the attribute isn't x,it is name,as:
{name:'high', y:4, z:5,color:'red'},

thank you very much!
