### ISSUE TITLE
Hotlink image redirects to google-spreadsheet-thumb.png

### ISSUE THREAD

**Issue by ivankin** [highcharts/highcharts#6250]
#### Expected behaviour
Click to  https://cloud.highcharts.com/images/adiboce/400.png and get chart preview.

#### Actual behaviour
Images https://cloud.highcharts.com/images/adiboce/400.png redirects to https://cloud.highcharts.com/resources/images/google-spreadsheet-thumb.png

#### Live demo with steps to reproduce
Just open https://cloud.highcharts.com/images/adiboce/400.png

#### Affected browser(s)

All browsers

**Comment by oysteinmoseng** [comment]
Thank you for reporting.

Internal note: Cyrillic font issues in export?

**Comment by TorsteinHonsi** [comment]
This issue belongs in the Cloud project, not Highcharts per se.

It probably relates somehow to the fact that we were unable to generate previews for charts based on Google Spreadsheet data, because they are async by nature. So someone jumped to the false conclusion that 404 == GS.

**Comment by TorsteinHonsi** [comment]
I'm closing it here so @havardge can take it further in the appropriate repo.
