### ISSUE TITLE
Navigator with explicit data not visible if showInNavigator is false

### ISSUE THREAD

**Issue by slozier** [highcharts/highcharts#6251]
#### Expected behaviour
I would expect the navigator to show the explicit data if explicit data is set even if `showInNavigator` is `false` for all series.

#### Actual behaviour
No data appears in the navigator.

#### Live demo with steps to reproduce
http://jsfiddle.net/v084kn7h/

**Comment by TorsteinHonsi** [comment]
I agree, we should handle expressive navigator.series settings with greater precedence. Also, do we allow setting navigator.series as an array?
