### ISSUE TITLE
ColorAxis. Highmaps and Heatmap not compatible

### ISSUE THREAD

**Issue by bloodmozg** [highcharts/highcharts#6253]
#### Expected behaviour
When I update ColorAxis of my highmaps, ColorAxis must update without errors

#### Actual behaviour
When I update ColorAxis of my highmaps, ColorAxis can't correctly cleansed and error falls

#### Live demo with steps to reproduce
[https://jsfiddle.net/grzxLjhz/1/](https://jsfiddle.net/grzxLjhz/1/)

1. Open sample
2. See, legend is correctly.
3. Click button "Update color axis"
4. Error. ColorAxis must update, but error falls
5. **If remove Heatmaps module, ColorAxis correctly updated**

**Comment by Dunge** [comment]
Not sure if it's related to your problem (which seems to crash in highchart.js accessing this.renderer), but I was just about to post a issue about updating color axis in an heatmap. Thanks to you, I saw that I just missed [0] and managed to get it working. If it can help you in any way: http://jsfiddle.net/4aqhB/802/

**Comment by TorsteinHonsi** [comment]
Note that the heatmap module is included in highmaps.js, so simply removing the module fixes the problem. 

So the real issue is that including heatmap/color axis twice causes problems.
