### ISSUE TITLE
Points className doesn't get updated when using Series.setData() with original number of points

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6254]
#### Expected behaviour
Update chart with new class for points with changed class.

#### Actual behaviour
Series.setData doesn't update className for points, when points length is equal to original poinst length.

#### Live demo with steps to reproduce
https://jsfiddle.net/2qoL7xv4/

1. Run demo
2. Notice, that class for first point doesn't update

Workaround:

    chart.series[0].setData(data, undefined, undefined, false)

**Comment by TorsteinHonsi** [comment]
Broken down to `Point.update`: http://jsfiddle.net/highcharts/2qoL7xv4/1/
