### ISSUE TITLE
Highcharts error #25 does not resolve on highcharts.com website

### ISSUE THREAD

**Issue by whawker** [highcharts/highcharts#6255]
#### Expected behaviour
When error [25](https://github.com/highcharts/highcharts/blob/319ce590ffa8396fd67b51bb6a6e0aa365d48627/errors/errors.xml#L142-L147) occurs (Moment not found when using new `global.timezone` option - [see here](https://github.com/highcharts/highcharts/blob/319ce590ffa8396fd67b51bb6a6e0aa365d48627/errors/errors.xml#L142-L147)) the displayed link https://www.highcharts.com/errors/25 displays a webpage when I can view information on this error

#### Actual behaviour
Highcharts.com website displays page stating "No such error code"

#### Live demo with steps to reproduce
http://jsfiddle.net/0xnhsd4f/

#### Affected browser(s)
N/A - Website issue

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, it's fixed now.
