### ISSUE TITLE
Exported image different from the original chart due to not applied styles for axis labels

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6260]
Only some styles showing as working when comparing the original chart with the exported image.

Ellipsis is not visible and first label is too long - different from the original chart.

Demo:
http://jsfiddle.net/oxpu2ezb/1/

Steps:

export and compare with the original chart - first labels is different
Looks like the `useHTML` for axis labels is not respected.

([previously posted on a wrong repo](https://github.com/highcharts/highcharts-export-server/issues/44))

Thanks to **larsac07**:

The SVG which is sent to the export server is already "erroneous" in that the labels are not HTML markup, but SVG:

```
...
<g class="highcharts-axis-labels highcharts-xaxis-labels ">
        <text x="91.051058197684" style="color:#666666;cursor:default;font-size:11px;white-space:nowrap;fill:#666666;" text-anchor="end" transform="translate(0,0) rotate(-45 91.051058197684 336)" y="336" opacity="1">
            <tspan style="max-width: 50px; display: inline-block; text-overflow: ellipsis; overflow: hidden; white-space: nowrap; fill: red;">Big data for yAxislablel</tspan>
            <title>Big data for yAxis lablel</title>
        </text>
        ...
```

**Comment by TorsteinHonsi** [comment]
> The SVG which is sent to the export server is already "erroneous" in that the labels are not HTML markup, but SVG

Yes, that's what the [exporting.allowHTML](http://api.highcharts.com/highcharts/exporting.allowHTML) option is for. 

When we set `allowHTML` the ellipsis works, but the text rotation doesn't. That's probably a limitation with PhantomJS.

**Comment by KacperMadej** [comment]
Connected to (or maybe event a duplicate of) #5393
