### ISSUE TITLE
Highstock Scrollbar Bug in Release 5.0.7

### ISSUE THREAD

**Issue by hanoncs** [highcharts/highcharts#6262]
Yesterdays Highstock JS update to 5.0.7, it broke our live site.

![highstock js v5 0 7 2017-01-17 bug](https://cloud.githubusercontent.com/assets/4771689/22087232/a8b9e678-dd91-11e6-844a-fda359f38376.JPG)

http://code.highcharts.com/stock/highstock.js are supposed to be stable releases. But this completely broke our scroll functionality. To fix I reverted to using a specific version: 4.2.

Tested in current Chrome, IE, Edge.

**Comment by TorsteinHonsi** [comment]
I'm sorry for the inconvenience! However, remember that issues will always occur with software updates, so in order to be 100% safe you need to use a specific version when loading from our CDN. For example http://code.highcharts.com/stock/5.0.6/highstock.js. 

Now to the actual problem - can you show us some live code so we can start debugging?

**Comment by pawelfus** [comment]
I think it's an issue where we define scrollbar, let's consider examples:

- 5.0.6:
  - chart.scrollbar: http://jsfiddle.net/f4hakLx7/ (horizontal scrollbar)
  - chart.xAxis.scrollbar: http://jsfiddle.net/f4hakLx7/1/ (vertical scrollbar)

- 5.0.7:
  - chart.scrollbar: http://jsfiddle.net/f4hakLx7/2/ (1) (vertical scrollbar, misplaced)
  - chart.xAxis.scrollbar: http://jsfiddle.net/f4hakLx7/3/ (vertical scrollbar)

(1) is broken, but how should we draw this? It should work the same way as chart.xAxis.scrollbar (vertical).  On the other hand, I don't want to break compatibility with 5.0.6 (horizontal).

**Comment by TorsteinHonsi** [comment]
> On the other hand, I don't want to break compatibility with 5.0.6 (horizontal).

I think we need to break it in this case - it doesn't make sense to have a horizontal scrollbar that scrolls the vertical axis. We never intended it to be drawn this way, it's a Highstock feature that happened to (partly) work in a vanilla chart.

**Comment by hanoncs** [comment]
Finally got a minute to work on this.

Here is a fiddle to see the issue I reported. [https://jsfiddle.net/hanoncs/ujn2ebh2/](url)

And yes, our upper management also felt horizontal scroll was weird to control the vertical axis.

**Comment by pawelfus** [comment]
Thanks @hanoncs 

As a solution for 5.0.7 version, please set `scrollbar` option on `xAxis` level:

```javascript
xAxis: {
  scrollbar: { 
    ...
  },
  ...
}
```
