### ISSUE TITLE
Responsive rules applies only once after render

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6265]
#### Expected behaviour
After resizing chart container to small, and resizing it back to large chart should display correctly, also after resizing it back to small it should look like after first resize.

#### Actual behaviour
After resizing chart container to small, and resizing it back to large chart doesn't reset it's options to set in options object, but instead replaces values in arrays like color or center with null values, also after resizing it back it looks different from after initial resize, because color and center are filled with nulls.

#### Live demo with steps to reproduce
http://jsfiddle.net/nwq0qt3x/

1. Click small
2. Click large
3. Click small

**Comment by TorsteinHonsi** [comment]
I found a problem with array contents being copied into an object, so now at least it works if you specify the base level colors too: http://jsfiddle.net/highcharts/nwq0qt3x/1/.

The remaining problem is to make it work when colors are not set on the base level: http://jsfiddle.net/highcharts/nwq0qt3x/2/

**Comment by robineng** [comment]
There seems to be a similar problem on the jsfiddle linked from your documentation too.

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/responsive/axis/
