### ISSUE TITLE
For Charts with Bars, the legend item symbols should be square

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6267]
#### Expected behaviour
The legend item symbols should be square for bar/column charts.

#### Actual behaviour
The legend item symbols for bar/column charts used to be square before Highcharts library v5. They now appear circular for these charts.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/column-basic/

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
This is a design change we did in v5.0. The legend symbols are supposed to display the color, not the shape of items. 

You can use the [legend.symbolRadius](http://api.highcharts.com/highcharts/legend.symbolRadius) option to get the old look back.

**Comment by MiroLiska** [comment]
Hello
In my opinion, this design change was not a lucky one. Moreover, the wishful statement 'The legend symbols are supposed to display the color, not the shape of items.' is not applied to all chart types. If you switch to line charts, the legend will contain small lines (optionally also with marker bullets), all nicely shaped, no circles here. The same can be observed by scatter charts - the legend contains the symbol used for the scatter marker, and not circles.

If 'all is circles' is to be new design now, then:
1. it must work everywhere, it should not just replace rectangles with circles
2. there must be one setting per legend - useSeriesShape, not that I have to change symbolRadius property that causes as a side effect to look rectangles like circles (or not). With useSeriesShape we can turn the new design off / on in one step.
3. The demo screenshots at https://www.highcharts.com/demo must be also with circles, at the moment they are misleading

Kind regards

Miro

**Comment by MiroLiska** [comment]
One more thing regarding the global 'useSeriesShape' option - if I decide to have everywhere the same shape (as was the new design idea) , maybe I do not want to have everywhere circles - maybe I want to see everywhere rectangles or diamonds.

**Comment by TorsteinHonsi** [comment]
Thanks for you opinions!

Keep in mind we only changed the _default_ look, you can get the old look back by simply setting legend.symbolRadius in your themes. That will make it look like it did in Highcharts 4.

> it must work everywhere, it should not just replace rectangles with circles

We currently use solid disks for series types like column, pie etc where the color is the main differentiator. For line series and scatter series, the symbol and line width/style also matter, so we add them. This didn't change with HC5. However, as you correctly point out, there are probably cases where we could add a better symbolic representation than just a solid disk.

> The demo screenshots at https://www.highcharts.com/demo must be also with circles, at the moment they are misleading

Thanks for notifying, we will update all the screenshots.

**Comment by MiroLiska** [comment]
In my opinion is the best solution to provide the one global shape setting, as note above. Your default setting would be a solid disk, but mine would be a rectangle - thus I would have the same behavior like MS Excel. Solid disks simply do not look good to me.

**Comment by Malczewski** [comment]
Seems [legend.symbolRadius](http://api.highcharts.com/highcharts/legend.symbolRadius) option doesn't have any effect on bar/column chart in 6.0.0. 
Ability to set up custom legend shapes is crucial for combination of charts, e.g. look at real use case http://jsfiddle.net/Yurim/52vLzy73/1/ - first 2 legend items show the connection between shape and metric (_metric 2_ should be square - as it corresponds to columns), whereas 3 others legend items describe bubble coloring.

**Comment by pawelfus** [comment]
`symbolRadius` works fine, please take a look: http://jsfiddle.net/52vLzy73/2/ - column's legend symbol is square.

**Comment by aFatFlyingCat** [comment]
in combinations chart , different shape of symbol in legend is necessary

**Comment by pawelfus** [comment]
Yes, it is, just like in my demo above: `symbolRadius` is an option to resolve the issue.
