### ISSUE TITLE
Hicharts 2 tooltip is not taking background image

### ISSUE THREAD

**Issue by prabhaakkineni** [highcharts/highcharts#627]
Hi,

I have used background image for hicharts 1 but it is not working when we migrated to hicharts 2
tooltip: {
                    formatter: function() {
                        var val = this.percentage;
                        return '<b>' + this.point.name + '</b>: ' + val.toFixed(0) +'%';
                    },
                    style: {
                        width: '190px',
                        height: '40px',
                        background: 'url(/orbitimages/umg/bg_tooltip_l.png) no-repeat',
                        marginTop: '65px',
                        marginLeft: '20px',
                        textAlign: 'center',
                        fontWeight: 'bold',
                        paddingTop: '10px'
                    }
Most of the styles used above are not working in new version. Please let me know if you find any work around for this.

**Comment by kenng** [comment]
How could we make the tooltip svg to accommodate to the size of image inside the tooltip? As currently the image appears outside of the tooltip box. ([image reference])(https://imgur.com/a/pKFpe)

`                   tooltip: {
                        useHTML: true,
                        formatter: function() {
                            return `<img src='${this.point.img}' style="max-height: 200px">
                            <div>
                                <span>${this.point.status} </span>
                            </div>`
