### ISSUE TITLE
plotBands and plotLines labels in a polar chart are not positioned correctly

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#6270]
#### Behaviour
In a polar charts labels for plot bands have incorrect positions.

#### Live demo with steps to reproduce
http://jsfiddle.net/yexj8of6/

**Comment by TorsteinHonsi** [comment]
_Internal note_:
Possibly they can be hooked up to the logic that modifies the position of the axis tick labels.

**Comment by pawelfus** [comment]
When fixing, test against #6829

**Comment by tanmayshah95** [comment]
Hi, @TorsteinHonsi 
Is this issue fixed in commit [30146e8](https://github.com/highcharts/highcharts/commit/30146e8a69b1a789f5a9e3f2299d35dbd162c257) done against #7117
