### ISSUE TITLE
Legend is going down

### ISSUE THREAD

**Issue by nishanth-satmetrix** [highcharts/highcharts#6273]
#### Expected behaviour

need show the legend
#### Actual behaviour
Legends are going down

#### Live demo with steps to reproduce
http://jsfiddle.net/tdmwLt22/10/

Thanks
Nishanth

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

For your specific question, the answer is that you had set `y: 50`, which offsets the whole legend by 50px down. Remove that and it's okay: http://jsfiddle.net/highcharts/tdmwLt22/24/

**Comment by nishanth-satmetrix** [comment]
How to make the legend dynamic based on the series. for example if I have 2 series . it will show 2 legends in the bottom right? if I have one wanted to show only one legend with width size should be small
Thanks
Nishanth

**Comment by TorsteinHonsi** [comment]
> Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
