### ISSUE TITLE
Error when hiding series of line polar chart using data module with CSV [5.0.3+]

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6279]
#### Expected behaviour
After clicking series in legend it should hide without problems

#### Actual behaviour
After clicking series in legend there is an error
`Uncaught TypeError: Cannot set property 'index' of undefined
    at object.generatePoints (https://code.highcharts.com/5.0.3/highcharts.src.js:16732:33)`

#### Live demo with steps to reproduce
5.0.7 | https://jsfiddle.net/j4mwoh1q/1/ (does not work)
5.0.2 | https://jsfiddle.net/j4mwoh1q/ (works ok)

1. Click legend item to hide series
2. Notice error in console
3. Notice that chart doesn't scale to fit rest of series

**Comment by theskyliner** [comment]
The same goes for resizing a responsive webpage with this type of diagram. The series then is totally out of view.

**Comment by pawelfus** [comment]
It's a regression from https://github.com/highcharts/highcharts/commit/873aaa1

However, previous versions (e.g. 5.0.2) didn't work so good too (show and hide first series by legend multiple times).
