### ISSUE TITLE
TickInterval & TickAmount. Wrong behavior

### ISSUE THREAD

**Issue by Ty4ka** [highcharts/highcharts#6281]
#### Expected behaviour
tickInterval: 200,
tickAmount: 6

200 * 6 = **1200**

#### Actual behaviour
200 * 6 = **2000** (?)

#### Live demo with steps to reproduce
http://jsfiddle.net/ty4ka/wbf4Lm2y/1/

1. Open sample
2. See, Y-axis values.

**Comment by pawelfus** [comment]
Thank you for reporting, and my apologies for a delay in response!

Not related to the bug, but there is one, very small, mistake in your calculations: we start with 0 tick (in your demo), so it should be: 0-200-400-600-800-1000. However, this would cause the first point out of the visible range so Highcharts increases scale. If you want scale 0-1200, then tickInterval shouldn't be 240? Something like this: http://jsfiddle.net/wbf4Lm2y/3/

**Comment by Ty4ka** [comment]
whether it is possible to disable Highcharts increases the scale?

**Comment by pawelfus** [comment]
Something like this: http://jsfiddle.net/wbf4Lm2y/4/ ? It's possible to create your own [`tickPositioner`](http://api.highcharts.com/highcharts/yAxis.tickPositioner) if you want to.
