### ISSUE TITLE
Highcharts want to attach a chart 2times to the same div 

### ISSUE THREAD

**Issue by JeromeVi** [highcharts/highcharts#6283]
#### Expected behaviour
The expected behaviour would be to have 2 chart displayed in this HTML page because I have 2 div with 2 different id:
```
<template name="dataGraph">
<div id="bShCgpK6BgRJrssxP" data-highcharts-chart="1"></div>
<div id="7wfwqYuxJKrjFmD7W"></div>
</template>

```
And I used the reactive var as in the example:
```
<template name="chart">
   <div id="{{chart_id}}"></div>
 </template>

```

And with JavaScript I make some basic code to create 1 chart per element in a collection:
```
getContainerToDisplayGraph = function() {
    containersRngPsd = InfosContainers.find({
        $or: [{
            stateContainer: "running"
        }, {
            stateContainer: "paused"
        }]
    }).fetch();
    console.log("Atm you have " + (containersRngPsd.length) + " containers running or paused");

    for (i = 0; i < containersRngPsd.length; i++) {
        //dynamically create a chart
        console.log("nameDiv: " + Template.currentData().chart_id);
        console.log("containersRngPsd[" + i + "]: " + containersRngPsd[i].nameContainer);
        var nameChart = Highcharts.chart(Template.currentData().chart_id, {
            title: {
                text: 'Memory usage of ' + containersRngPsd[i].nameContainer
            },
            xAxis: {
                type: 'datetime',
            },
            yAxis: {
                title: {
                    text: 'usage'
                },
                labels: {
                    formatter: function() {
                        var usage = this.value;
                        if ((usage >= 1000000) && (usage < 1000000000)) {
                            return (usage / 1000000).toFixed(2) + "MB";
                        } else if (usage >= 1000000000) {
                            return (usage / 1000000000).toFixed(2) + "GB";
                        } else {
                            return usage + "KB";
                        }
                    }
                },
            },
            tooltip: {
                formatter: function() {
                    return '<b>' + this.series.name + '</b><br/>' + Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x) + '<br/>';
                }
            },
            series: [{
                type: 'line',
                name: 'memory usage',
                data: []
            }]
        });
        updateThisChartWithThisCtn(containersRngPsd[i].idContainer, nameChart);
    }
}
```

So in the wanted behaviour HighChart should see that the first div is already taken by a chart and go to the 2nd one. (or it's how I think it works)

#### Actual behaviour
The thing is that the actual behaviour is that it try to attach the 2nd chart in the same div: 
<img width="304" alt="capture d ecran 2017-01-23 a 13 37 55" src="https://cloud.githubusercontent.com/assets/22610050/22204250/2fc3a004-e171-11e6-8217-bf796f726ad7.png">

#### Live demo with steps to reproduce
I can't really make a reproducible fiddle....

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Are you sure it's a Highcahrts issue? From your code, you use twice the same container: `Template.currentData().chart_id` returns the same item, so of course Highcharts will render chart in that given container.

**Comment by JeromeVi** [comment]
Despite I'm using a for loop ? I though with my code it would take the first container of the array then at the second loop the 2nd one and take the 2nd div too

**Comment by pawelfus** [comment]
You loop over `containersRngPsd` items: 

    for (i = 0; i < containersRngPsd.length; i++) { ... }

Then `Template.currentData().chart_id` shouldn't change. Do `containersRngPsd` items contain the ID? I see you have in code: `containersRngPsd[i].idContainer` - are these ID's the same as `Template.currentData().chart_id`? Maybe you can use it instead of `Template.currentData().chart_id`.

**Comment by JeromeVi** [comment]
No it's not the same id but I can add the divId in the containersRngPsd pretty easily because the div id is the _id in the collection of the container.

----collection InfoContainers----
| idContainer: comes from Docker
| _id: is added automatically by Mongo and is the same as the div id

**Comment by JeromeVi** [comment]
So it's ok you were right ! I used the _id and it worked !

**Comment by pawelfus** [comment]
Perfect, thanks for the info!
