### ISSUE TITLE
Responsive rule does not apply new chart type from bar to column and from column to bar

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6286]
#### Expected behaviour
After changing charts container size to small chart type should change from column to bar (for first demo)
After changing charts container size to small chart type should change from bar to column (for second demo)

#### Actual behaviour
After changing charts container size to small new chart type does not apply

#### Live demo with steps to reproduce
https://jsfiddle.net/xxd86qbq/1/
https://jsfiddle.net/xxd86qbq/2/

1. Click 300px button
2. Notice, that chart does not render with a new type

_Note: this may be caused by not changing inverted property_
https://jsfiddle.net/xxd86qbq/3/
https://jsfiddle.net/xxd86qbq/4/

**Comment by KacperMadej** [comment]
Unable to recreate using version 6.1.4.
Closing as resolved.
