### ISSUE TITLE
panning/dragging issue in highmap clicking on Russia from worldview

### ISSUE THREAD

**Issue by avg6003** [highcharts/highcharts#6287]
#### Expected behaviour
Clicking on Russia disables the vertical dragging/panning. 

#### Actual behaviour
I am trying to use highchart API with maps plugin. I have just noticed that clicking from worldmap view on Russia country will zoom to the country but it disables the vertical dragging/panning.

#### Live demo with steps to reproduce

http://jsfiddle.net/highcharts/aaLuxgg6/17/

**Comment by morganfree** [comment]
Works in Highmaps 4.2.7 http://jsfiddle.net/aaLuxgg6/13/, broken in 5 http://jsfiddle.net/aaLuxgg6/14/

**Comment by morganfree** [comment]
Appeared in Highmaps 5.0.6

5.0.5 http://jsfiddle.net/aaLuxgg6/15/
5.0.6 http://jsfiddle.net/aaLuxgg6/16/

**Comment by TorsteinHonsi** [comment]
We need a specific width to reliably reproduce: http://jsfiddle.net/highcharts/aaLuxgg6/17/

It's caused by a rewrite in `chart.pan`: https://github.com/highcharts/highcharts/commit/193f1b9

**Comment by avg6003** [comment]
Thank you so much for your support. It is fixed.

**Comment by TorsteinHonsi** [comment]
What? Is it fixed? I can still reproduce it...

**Comment by avg6003** [comment]
I was using the version Highmaps 5.0.6 which has this bug. Apology for my wrong wordings. I had just solved it by changing the version of highmaps. the bug has not fixed yet.
