### ISSUE TITLE
When boost module kicks in (>5000 points), data is missing in the point and series objects, making custom formatters difficult

### ISSUE THREAD

**Issue by stolsvik** [highcharts/highcharts#6288]
Just a quick heads up on a problem that took me some time to deduce.

I had added the boost module "just in case" since my data was "somewhat largish", thinking that it wouldn't hurt. This turned out to have a side effect that I had no idea of.

It seems like the booster kicks in at something like more than 5000 points?

When that happens, it evidently takes over large parts of the calculation algorithm, making the internal state that my tooltip formatter depended on unusable.

In particular, I could not find the index for the current point anymore.

This formatter stopped working, as I didn't find the "this.points[0].point.index" anymore:

```javascript
            formatter: function () {
                // :: Must manually find all the values of all the series
                // Get the chart object
                var chart = this.points[0].series.chart;

                // NOTICE: THIS DOES NOT WORK WITH HighChart "Boost" plugin!
                // Evidently, over 5000 points, boost kicks in. This is relevant for our oldest series!
                // There is then missing lots of data on the points[] structure.
                var idx_S0 = this.points[0].point.index;
                var x_S0 = this.points[0].point.x;

                var s = '<b>' + df_YMD(x_S0) + '</b>';

                // Write out the info
                $.each(chart.series, function (i, series) { //loop through series array
                    // ?: Is this a Highstocks "Navigator" series?
                    if (_.includes(series.name, 'avigator')) {
                        // -> Yes, so not include.
                        return;
                    }
                    var point = series.points[idx_S0];
                    // :: Verify that we have same X as x_S0
                    if (!point || (point.x !== x_S0)) {
                        console.log("x_S0 doesn't yield same Xs: From S0: "+x_S0+", from point:"+point.x+" - search for correct idx");
                        var newIdx;
                        for (var i = 0; i < series.points.length; i++){
                            if (series.points[i].x === x_S0) {
                                newIdx = i;
                                break;
                            }
                        }
                        // ?: Did we find an index?
                        if (!newIdx) {
                            // -> No, so just include a blurb
                            s += '<br/><i><span style="color:#a0a0a0">\u25CF '
                                + series.name + ': - no data - </span></i>';
                            return;
                        }
                        point = series.points[newIdx];
                    }

                    var yAxisTitle = '';
                    var userOptionsTitle = series.yAxis.userOptions.title;
                    if (userOptionsTitle) {
                        yAxisTitle = userOptionsTitle.text || '';
                    }
                    var formattedNumber = Highcharts.numberFormat(point.y, 2);
                    var color = point.color;
                    s += '<br/><span style="color:' + color + '">\u25CF</span> '
                        + series.name + ': <b>'
                        + formattedNumber + '</b> ' + yAxisTitle;
                });
                return s;
            }
```

Suggestion: Give a proper way to find the current index into each series.

Suggestion2: The reason for taking control of the tooltip is that I want to display the value of the disabled (not visible) series too. That turned out harder than expected. It would be great if all points was available in the formatter context, even if they were invisible, with a flag of visibility. Due to backwards compat, that "all series" would obviously have to be available under a different property.

Suggestion3: The Navigator series turned up in the series-array (Highcharts). That was unexpected. A flag that flagged it as a "system series" or something would have been nice.

**Comment by TorsteinHonsi** [comment]
> Give a proper way to find the current index into each series.

**Comment by TorsteinHonsi** [comment]
> Give a proper way to find the current index into each series.

I think that can be done, as we can pass over the `index` in the point shim we are passing to the tooltip.

> The reason for taking control of the tooltip is that I want to display the value of the disabled (not visible) series too.

It's available from `chart.series[i].options.data`, and you can read series visibility from `series.visible`. 

> The Navigator series turned up in the series-array (Highcharts). That was unexpected. A flag that flagged it as a "system series" or something would have been nice.

You can look for its class name `highcharts-navigator-series`.

**Comment by stolsvik** [comment]
> It's available from chart.series[i].options.data, and you can read series visibility from series.visible.

Check out the included formatter. (I didn't know the difference between points and data until I zoomed, when "find the index" logic suddenly kicked in all the time when using points). However, this is pretty cumbersome, jfr. formatter - any improvements are most welcome! The main problem as I understand is that you need the specific index for each series - since all series might not have the same amount of data, you need to find the actual index for the current tooltip position within each series (which might not then exist) - even though highcharts probably know this already?
