### ISSUE TITLE
Use a hash to store ids and objects to improve .get() function performance

### ISSUE THREAD

**Issue by rninne** [highcharts/highcharts#6290]
Feature request

#### Expected behaviour
.get() function will search this hash first and only then search all objects if none is found?

The hash should be built on chart creation and modified each time you add / remove a point/series/axis with an id property.

#### Actual behaviour
Using get will search all points, series, axis for an object with a given id. This is very slow even with a modest amount of points.

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Thanks for the suggestion!

The `get()` function currently only searches until it finds something, so if it finds something in the axes or series (which are typically very few), it should not be slow. If it needs to search through the points however, it's a different story. 

What's your use case? Are you searching for series or axes or points? Maybe we can just add a boolean to prevent it from looping the points array? That would be a much lighter implementation in terms of file size and robustness.

**Comment by rninne** [comment]
Points :(

I'm changing the colour of a point in a series depending if a target has been hit. The easiest way to remember the point was to use an id. I could quickly retrieve it again if the target is deleted or modified and set the styling changes back to default.

I was also extending a series based on certain conditions (adding / removing points) and using an id seemed more accurate than the series index. but that was also really slow.

I'm keeping my own hash of points at the moment for each series and using that as a work around for the time being. Which is OK but means I still have to know the index to create a reference to it out of the data array.

For this it would also be nice if addPoint() returned the new point object ;)

I'd actually be really happy to set up a session with you guys to show you how we are using highcharts so you can see for yourself our use cases.
