### ISSUE TITLE
Scatter plot legend icon sizes go too small if scatter markers are set small

### ISSUE THREAD

**Issue by DCIP** [highcharts/highcharts#6294]
#### Expected behaviour

The size of legend icons is independent of the size of the markers in a scatter plot.

#### Actual behaviour

If scatter plot markers are small then legend icons are also set to the same size.

#### Live demo with steps to reproduce

http://jsfiddle.net/sd555x60/

#### Affected browser(s)

Only tested in Chrome

**Comment by pawelfus** [comment]
Hi @DCIP 

My apologies for the delay. I think this is expected behaviour: marker on chart and in legend should be the same. 

We can extend Highcharts to achieve that, please take a look: http://jsfiddle.net/sd555x60/1/

Plugin:
```javascript
  (function(H) {
    H.wrap(H.seriesTypes.scatter.prototype, 'drawLegendSymbol', function(proceed) {
      proceed.apply(this, Array.prototype.slice.call(arguments, 1));

      if (this.legendSymbol && this.legendSymbol.isMarker) {
        this.legendSymbol.attr({
          width: 10,
          height: 10,
          x: 5,
          y: 5
        });
      }
    });
  })(Highcharts)
```
