### ISSUE TITLE
Waterfall display is wrong when stacking multiple series

### ISSUE THREAD

**Issue by bendenois** [highcharts/highcharts#6295]
When we want to display a stacked waterfall chart, we want each serie to be correctly displayed. But only one serie is correct, the other ones have weird behaviour. That makes the chart completly unreadable.

Here is the demo to show the behaviour.
http://jsfiddle.net/9brbwnc9/

**Comment by pawelfus** [comment]
Hi @bendenois 

Thank you for reporting. It's already reported: #2280
