### ISSUE TITLE
Bubble chart not clipping bubbles to within plot area

### ISSUE THREAD

**Issue by DCIP** [highcharts/highcharts#6296]
#### Expected behaviour

Bubbles that extend outside of the plot area should be clipped.

#### Actual behaviour

When axis range is forced and bubbles are on the edge of the plot area, they overflow the plot area rather than being clipped.  This is scatterplot behaviour rather than bubble chart behaviour.

#### Live demo with steps to reproduce

http://jsfiddle.net/4s6fyzn1/

#### Affected browser(s)

Tested in Chrome

**Comment by pawelfus** [comment]
Thank you for reporting! It's a regression from: f5c95d2

**Comment by hon2a** [comment]
[Demo of the expected result](http://jsfiddle.net/7gcg3p42/) (working on v4.2.7).

**Comment by pawelfus** [comment]
**Workaround:**

Demo: http://jsfiddle.net/3feyufp9/

Plugin code:
```javascript
  (function(H) {
    H.wrap(H.seriesTypes.bubble.prototype, 'render', function(proceed) {
      proceed.apply(this, Array.prototype.slice.call(arguments, 1));
      this.markerGroup.clip(this.chart.clipRect);
    });
    H.wrap(H.seriesTypes.bubble.prototype, 'setClip', function(proceed) {
      proceed.apply(this, Array.prototype.slice.call(arguments, 1));
      this.markerGroup.clip(this.chart.clipRect);
    });
  })(Highcharts);
```

**Comment by hon2a** [comment]
@pawelfus Thanks for the work-around, I'll give it a try.

**Comment by hon2a** [comment]
Works like a charm :)

**Comment by mobilutz** [comment]
@pawelfus Would love to see the real fix in one of the next releases.
