### ISSUE TITLE
Setting the width on a right aligned legend affects margin between plot area and legend

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#6301]
#### Expected behaviour
Setting explicit legend width does not influence the margin between plot area and legend.

#### Actual behaviour
Setting explicit legend width does NOT influence the margin between plot area and legend. It looks like the legend is transposed 10 pixels to the right. There is less margin between the legend and the chart border.

#### Live demo with steps to reproduce
Compare http://jsfiddle.net/kzoon/monxmqtt/1/ and http://jsfiddle.net/kzoon/monxmqtt/2/

#### Affected browser(s)
Chrome 55
IE 11

**Comment by kzoon** [comment]
I would like to release a new version of my software in three weeks time. Any chance this issue could be addressed by then?

**Comment by TorsteinHonsi** [comment]
Compare the correct behaviour when [aligned left](http://jsfiddle.net/highcharts/monxmqtt/3/) to the wrong behaviour when [aligned right](http://jsfiddle.net/highcharts/monxmqtt/4/). When aligned right, the legend is shifted to the right and margin is not respected.
