### ISSUE TITLE
Error in H.Chart.getMargins when xAxis.max is defined and rangeSelector.selected = 3 (YTD)

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6302]
#### Expected behaviour

Render chart.

#### Actual behaviour

Chart does not render. There is an error:

    VM2127 highstock.src.js:15100 Uncaught TypeError: Cannot read property 'display' of undefined
    at H.Chart.getMargins (VM2127 highstock.src.js:15100)
    ...

#### Live demo with steps to reproduce
http://jsfiddle.net/kdqgxe4e/

1. Look at error in console

**Comment by sebastianbochan** [comment]
The max value is in conflict with selected range (rangeselector's button).
