### ISSUE TITLE
HighChart responsive is full bugged

### ISSUE THREAD

**Issue by JeromeVi** [highcharts/highcharts#6304]
#### Expected behaviour
The expected behaviour following the doc is that HighChart is responsive by itself if we don't specify any width. So when I reduce the window it should reduce the graph.

1) default view:
<img width="1528" alt="capture d ecran 2017-01-26 a 11 12 36" src="https://cloud.githubusercontent.com/assets/22610050/22327619/6100aaba-e3b8-11e6-88e0-0b0330d12ee1.png">

#### Actual behaviour
When I reduce the window the chart is placed on the right of the `<div>` and he disappear.

2) reduced view or mobile view:
<img width="1197" alt="capture d ecran 2017-01-26 a 11 13 29" src="https://cloud.githubusercontent.com/assets/22610050/22327640/809ab03c-e3b8-11e6-9306-91ec806902eb.png">

#### Code to create the chart 
```
  var nameChart = Highcharts.chart(currentContainer.idChartCPU, {
            title: {
                text: 'CPU usage of ' + currentContainer.nameContainer,
                style: {
                   color: '#009933',
                   fontSize: '15px'
                },
            },

            xAxis: {
                type: 'datetime',
            },
            yAxis: {
                title: {
                    text: 'usage'
                },
                 labels: {
                     formatter: function() {
                         var usage = this.value;
                         return usage + "%";
                     }
                 },
            },
            tooltip: {
                formatter: function() {
                    return '<b>' + this.series.name + '</b><br/>' + Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x) + '<br/>';
                }
            },
            series: [{
                type: 'line',
                name: 'CPU usage',
                color: '#7FFF00',
                data: []
            }],
        });
        nameChart.setSize(null,250);
        updateChartCPU(currentContainer.idContainer, nameChart);
```

Method to add the points on the graph:
```
updateChartCPU= function(idContainer, nameChart) {
    DockerStats.find({
        idCtn: idContainer
    }).observe({
        added: function(metric) {
            if (nameChart && nameChart.series && nameChart.series.length > 0) {
                var series = nameChart.series[0],
                    shift = series.data.length >= Session.get('window_size'),
                    x = (metric.read + 3600) * 1000,
                    //DELTA = (NEW-OLD)/OLD
                    cpuDelta = (metric.cpu_stats.cpu_usage.total_usage - metric.precpu_stats.cpu_usage.total_usage),
                    systemDelta = (metric.cpu_stats.system_cpu_usage - metric.precpu_stats.system_cpu_usage),
                    y =cpuDelta / systemDelta * metric.cpu_stats.cpu_usage.percpu_usage.length * 100;
                nameChart.series[0].addPoint([x, y], true, shift);
            };
        }
    });
}
```
#### HTML + CSS of the charts

The HTML structure is like this:
<img width="1145" alt="capture d ecran 2017-01-26 a 11 22 03" src="https://cloud.githubusercontent.com/assets/22610050/22327869/b5bb6a94-e3b9-11e6-9223-4a91da97f44d.png">

The CSS:
```
.divChart .highcharts-container {
   top: 0px !important;
   left: 0px !important;
   position: relative;
}
```

#### Live demo with steps to reproduce
I'm not able to reproduce it.

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
Thanks for writing, but I'm afraid we're not able to help you without a live demo. Your code has references to DockerStats and other interfaces that we don't recognize.

Here's an attempt based on your code: http://jsfiddle.net/highcharts/wnmb4pbs/

**Comment by JeromeVi** [comment]
@TorsteinHonsi  Yes I understand but maybe you have an idea how to always align the chart on the left of the screen ? or on the left of his container ?

**Comment by TorsteinHonsi** [comment]
Sure, see http://jsfiddle.net/highcharts/wnmb4pbs/1/

**Comment by JeromeVi** [comment]
@TorsteinHonsi It's aligned on the left because the container is 50% width but with a container who has 100% width. Look the picture of my "issue" the first is what I want to do

**Comment by JeromeVi** [comment]
@TorsteinHonsi Oh I see it works in JsFiddle as always... I'll try things on my code, thank you for your help

**Comment by JeromeVi** [comment]
@TorsteinHonsi I have a question, is it a known effect that when you display 16 live charts on the same page the points on the chart are not always displayed ? (like if it couldn't add the points for all the charts)
