### ISSUE TITLE
Impossible to add "preserveAspectRatio" on the svg created by Highcharts

### ISSUE THREAD

**Issue by JeromeVi** [highcharts/highcharts#6306]
#### Expected behaviour
I mean it's not really and issue who fails a behaviour but I didn't found this attribute on the [Highcharts api ](http://api.highcharts.com/highcharts). `preserveAspectRatio` would allow me to keep my charts displayed as I need to and it's an attribute for svg. It worked if I added it via the developer consol so it's right that's an attribute for svg.

#### Actual behaviour
No possibility (or I haven't founded it) too add this attribute.

Despite I used the ` nameChart.attr({preserveAspectRatio: 'xMinYMin'})` i got `chart.attr is not a function` but [in the api doc](http://api.highcharts.com/highcharts/Element.attr) it says that I could use it no ? I have tried with `nameChart.getSVG();`  and it's not a function too.

If I display my `nameChart` it's a chart and I can access to his properties like this one `nameChart.chartWidth` and it returns me the right one.
<img width="441" alt="capture d ecran 2017-01-26 a 15 02 05" src="https://cloud.githubusercontent.com/assets/22610050/22333862/700b3fc8-e3d8-11e6-82e0-fee6cf604d6e.png">
 I have tried `chart.getSVG()` but it's "not a function" too. 

Here you can see how I create my chart and call this method:
displayGraphMemory = function(currentContainer) {
```

        nameChart = Highcharts.chart(currentContainer.idChartMem, {
          title: {
                text: 'Memory usage of ' + currentContainer.nameContainer,
                style: {
                   color: '#3F7EF2',
                   fontSize: '15px'
                },
            },
            xAxis: {
                type: 'datetime',
            },
            yAxis: {
                title: {
                    text: 'usage'
                },
                labels: {
                    formatter: function() {
                        var usage = this.value;
                        if ((usage >= 1048576) && (usage < 1073741824)) {
                            return (usage / 1048576).toFixed(2) + "MB";
                        } else if (usage >= 1073741824) {
                            return (usage / 1073741824).toFixed(2) + "GB";
                        } else {
                            return usage + "KB";
                        }
                    }
                },
            },
            tooltip: {
                formatter: function() {
                    return '<b>' + this.series.name + '</b><br/>' + Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x) + '<br/>';
                }
            },
            series: [{
                type: 'line',
                name: 'memory usage',
                data: []
            }],
        });
        nameChart.setSize(null,250);
        nameChart.attr({preserveAspectRatio: 'xMinYMin'})
        updateChartMemory(currentContainer.idContainer, nameChart);
}
```
_don't panic it create the chart without problems I just need help for the part where I set `preserveAspectRatio`_

#### Live demo with steps to reproduce
http://sendvid.com/gcb4pq9r here you can see what I'm trying to do

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

What you're trying to do is probably to set it to the renderer.boxWrapper: http://jsfiddle.net/highcharts/7fytnfsp/
