### ISSUE TITLE
Using offline-exporting I am unable to export a PNG/JPEG in styled mode for IE11

### ISSUE THREAD

**Issue by rbeasse** [highcharts/highcharts#6307]
#### Expected behaviour
I should be able to export to PNG/JPEG when using IE11, a styled chart and offline-exporting.

#### Actual behaviour
Export returns an image that is all black (possibly no styles are being applied?)

#### Live demo with steps to reproduce
http://jsfiddle.net/88b0jxee/
Export  chart as PNG or JPEG

_The following example is from one of your existing fiddles, I just applied offline-exporting._

#### Affected browser(s)
Internet Explorer 11

**Comment by TorsteinHonsi** [comment]
Verified that it does indeed work with Chrome, and that it does work with IE11 when offline exporting is not in use.

**Comment by rbeasse** [comment]
Hello,

Any updates on this issue?

**Comment by oysteinmoseng** [comment]
@rbeasse Working on it! Styled mode adds a lot of inline style properties to the SVG for export, and some of these are probably tripping up CanVG.

**Comment by sebastianbochan** [comment]
Problem seems to be still valid.

IE11.953.14393.0

**Comment by rbeasse** [comment]
I noticed this still appears to still be an issue on the latest release - what version will this patch be for?

The demo provided is still broken as well.

**Comment by oysteinmoseng** [comment]
@rbeasse It is fixed, but you need to use the styled version of the offline exporting module: http://jsfiddle.net/9rzkgcks/
