### ISSUE TITLE
Highcharts automatically remove the caps when we add attributes to the `<svg>`

### ISSUE THREAD

**Issue by JeromeVi** [highcharts/highcharts#6309]
#### Expected behaviour
With this code            `$('#'+currentContainer.idChartMem).children("div").children("svg").attr("preserveAspectRatio", "xMinYMin meet");`

The expected behaviour is to have : 
<img width="1200" alt="capture d ecran 2017-01-27 a 07 48 10" src="https://cloud.githubusercontent.com/assets/22610050/22362707/fb94ef4e-e464-11e6-8cdf-fb4342a53a66.png">

#### Actual behaviour
But nothing happens like this. It looks like Highcharts remove the caps and then the attribute has 0 effect because is not known:
<img width="1204" alt="capture d ecran 2017-01-27 a 07 50 02" src="https://cloud.githubusercontent.com/assets/22610050/22362745/3f8fc598-e465-11e6-98a3-9de94fc4a861.png">

#### Live demo with steps to reproduce
It's not my [JSFiddle](http://jsfiddle.net/ew5qprhe/1/) and it's not a Highcharts but he use the `.attr` and set the same attribute as me

#### Affected browser(s)
Chrome

This issues is linked with the #6306

**Comment by TorsteinHonsi** [comment]
The demo uses d3 so it doesn't say anything about Highcharts. The code you are quoting in "Expected behaviour" looks like jQuery, so it also doesn't tell us anything. 

What you're trying to do is probably to set it to the `renderer.boxWrapper`: http://jsfiddle.net/highcharts/7fytnfsp/

**Comment by JeromeVi** [comment]
@TorsteinHonsi THANK YOU !!! It's what I needed to do !
