### ISSUE TITLE
Dynamic drilldown on x-axis label after scroll shows button on chart

### ISSUE THREAD

**Issue by mapeebles** [highcharts/highcharts#6311]
#### Expected behaviour
I have a column chart using dynamic drilldown along with a scrollbar and ranges due to the size of the x-axis categories.  Once you scroll the x-axis, and then click a x-axis label, it should execute the drilldown event.

#### Actual behaviour
After scrolling the x-axis, if you click a x-axis label to drilldown, a button appears on the screen.  If you click the button you will receive this exception:
TypeError: Cannot read property 'length' of undefined

NOTE: this is not an issue if you click the column bar itself...only on the label does it happen.

#### Live demo with steps to reproduce
https://jsfiddle.net/mpeebles/w18a273h/

#### Affected browser(s)
Tested on:
Chrome 55.0.2883.95
Safari 10.0.2 (12602.3.12.0.1)

**Comment by pawelfus** [comment]
Hi @mapeebles 

Thank you for reporting this bug. That button you see is the button to go back from drilldowned level. It works fine if you load data for a drilldown point: https://jsfiddle.net/w18a273h/40/

**Comment by mapeebles** [comment]
The point of the async drilldown is to not have drilldown data added, but to fire the drilldown event.  In my case I will navigate away when "drilling down" so I do not want to add data.  This is a bug.   It seems to work fine when clicking the column.  The problem is clicking the label to trigger the drilldown event is not handled properly.

**Comment by pawelfus** [comment]
Hi @mapeebles 

Of course, this is a bug, that's why I added "bug" flag. If you don't add data on drilldown event, then  you can simply use [`series.point.events.click`](http://api.highcharts.com/highcharts/plotOptions.series.point.events.click) and [`xAxis.labels.events.click`](https://github.com/blacklabel/custom_events).

**Comment by mapeebles** [comment]
Thanks Pawel.   I will look into using those events.

**Comment by xzblq** [comment]
Thanks pawelfus. i'll use those.
