### ISSUE TITLE
Highcharts correct tickInterval

### ISSUE THREAD

**Issue by Gazfay** [highcharts/highcharts#6313]
I am seted tickInterval by two hours (3600 * 2000) and set min value  (03:00h). X-axis show me this points - [04:00, 06:00, 08:00 ... ], but i want to see tickInterval like this - [03:00, 05:00, 07:00...]. How i can do this? Thanks.

Live-demo:
http://jsfiddle.net/Gazfay/4ft9k65L/

**Comment by pawelfus** [comment]
Hi @Gazfay 

Using [`tickPositioner`](http://api.highcharts.com/highcharts/xAxis.tickPositioner) you can modify calculated ticks. For example: http://jsfiddle.net/474cvnw8/

Snippet:

```javascript

    tickPositioner: function () {
      var offset = 3600000,
          newTicks;

      // Translate ticks:
      newTicks = this.tickPositions.map(function (tick) {
        return tick += offset;
      });

      // Pass info about formats:
      newTicks.info = this.tickPositions.info;

      return newTicks;

    },
```

@TorsteinHonsi - how about adding similar option to `startOfWeek` for all units? Maybe improving [`Axis.units`](http://api.highcharts.com/highcharts/xAxis.units)?

**Comment by Gazfay** [comment]
Thank you very mush! It's work! =)
