### ISSUE TITLE
Treemap in styled mode

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6314]
#### Behaviour
Trying to use treemap module in styled mode results in ‘Uncaught TypeError: a.pointAttribs is not a function’ error.

#### Live demo
http://jsfiddle.net/bfgyo89g/

**Comment by emsilva** [comment]
@PaulDalek, any idea on the lead time to get it fixed? Any workaround I could be using for now?  Thanks!

**Comment by jon-a-nygaard** [comment]
Hi @emsilva , a possible workaround for this issue would be to set a function named pointAttribs on the treemap series, and have it return an empty object. Here's [an example for you](http://jsfiddle.net/jon_a_nygaard/bfgyo89g/1/).
