### ISSUE TITLE
Animation duration does not have effect on map zooming

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#6315]
#### Expected behaviour
`chart.animation.duration` option has impact on map zooming.
http://jsfiddle.net/toptb28q/

#### Actual behaviour
The option has no effect on zooming duration. It stopped working in Highmaps 5.0.4.

#### Live demo with steps to reproduce
http://jsfiddle.net/toptb28q/1/

**Comment by TorsteinHonsi** [comment]
Fails since https://github.com/highcharts/highcharts/commit/bacc663
