### ISSUE TITLE
Chart renders differently if adjusts navigator

### ISSUE THREAD

**Issue by Vivihung** [highcharts/highcharts#6317]
#### Expected behaviour
Chart should be rendered the same way if navigator select the same range.

#### Actual behaviour
Chart is rendered differently than init state, even if the navigator selects the same range.

#### Live demo with steps to reproduce
https://jsfiddle.net/Vivien/L0vLzu0t/

Repro steps:
1. Pay attention to how chart is rendered in the init state.
2. Adjust navigator, then move navigator bar to the left-most, and right-most position. (Basically try to make it covers all data range)
3. Found the chart is rendered differently than init state, even if the navigator selects the same range.

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Hi,

Isn't this the same issue as #6318 ? I can not zoom back to the maximum range, and `showInNavigator` also fixes that issue: https://jsfiddle.net/sfe0861m/

**Comment by Vivihung** [comment]
No, I think it's different issue. Applying showInNavigator doesn't resolve the issue.

This is the chart _before_ I use navigator:
![1](https://cloud.githubusercontent.com/assets/4814277/22477560/77b0a7ec-e79b-11e6-9e3f-e41a8fdc8054.png)

This is the chart _after_ I use navigator then move the left bar back to the left position:
![2](https://cloud.githubusercontent.com/assets/4814277/22477561/77b175f0-e79b-11e6-81bd-ae111ad25434.png)


You can see they are rendered differently.

**Comment by pawelfus** [comment]
You are right, thank you for the screenshots!
