### ISSUE TITLE
Chart cannot zoom out to entire data points range by Navigator

### ISSUE THREAD

**Issue by Vivihung** [highcharts/highcharts#6318]
#### Expected behaviour
After using navigator, user should be able to zoom out from 1/16-1/30

#### Actual behaviour
User can only zoom out to 1/25-1/30 if using navigator.

#### Live demo with steps to reproduce
https://jsfiddle.net/Vivien/wqufhdhw/

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Thank you for reporting!

When using multiple series with different ranges I suggest to set [`plotOptions.series.showInNavigator`](http://api.highcharts.com/highstock/plotOptions.series.showInLegend) to true. Demo: https://jsfiddle.net/q1us3154/

Of course, it should work the same way also when using only first series in the navigator.

**Comment by Vivihung** [comment]
Cool, plotOptions.series.showInNavigator did resolve the issue. Thanks!
