### ISSUE TITLE
Vertical x-axis scrollbar getting merged with bars in case of bar chart

### ISSUE THREAD

**Issue by PurvaK** [highcharts/highcharts#6320]
#### Expected behaviour
Vertical scrollbar should render correctly in bar chart.

#### Actual behaviour
Vertical scrollbar is colliding with bars in bar chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/PurvaEQ/42hudw68/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @PurvaK 

Thank you for reporting this bug. It's already fixed on our master branch and will be part of 5.0.8 release, please take a look: http://jsfiddle.net/42hudw68/1/
