### ISSUE TITLE
Need to hide the bubble in the series line when clicking on the legend

### ISSUE THREAD

**Issue by nishanth-satmetrix** [highcharts/highcharts#6326]
#### Expected behaviour
Need to hide the bubble in the series line when clicking on the legend , in the line chart
 please help me,

Im adding a bubble in the each  series point, need to hide the bubble also while clicking on the legend.

opts.plotOptions.series.events = {
                   legendItemClick: function() {
                	   opts.plotOptions.bubble.minSize = 0;
                	   opts.plotOptions.bubble.maxSize = 10;
                   }
           };

this is not working for me
#### Affected browser(s)

Thanks
Nishanth

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
