### ISSUE TITLE
highstock flag tooltip in the wrong y position, if y axis top > 0

### ISSUE THREAD

**Issue by mhwlng** [highcharts/highcharts#6327]
highstock flag tooltip in the wrong y position, if y axis top > 0

see 

http://jsfiddle.net/4woawotu/1/

![untitled](https://cloud.githubusercontent.com/assets/1388886/22508860/222cc390-e88c-11e6-95bf-dc2e33bf12a7.png)

**Comment by pawelfus** [comment]
Hi @mhwlng 

Thank you for reporting this bug. 

*Internal note:*
Issue may be resolved in a similar way to #3517

**Comment by mhwlng** [comment]
>  It works fine with tooltip.followPointer set to true: 

Yes, that works for me, thanks !
