### ISSUE TITLE
https://github.com/highcharts/highcharts/issues/6308

### ISSUE THREAD

**Issue by brandontineo** [highcharts/highcharts#6329]
Hi, I would like to see if there is an response for the issue above. It is a bug but I can't seem to figure out how to label it as such:

https://github.com/highcharts/highcharts/issues/6308

**Comment by TorsteinHonsi** [comment]
Thanks for writing! Only the admins can label it a bug. If we don't respond quickly, please add comments to the issue.

Duplicate of #6308.
