### ISSUE TITLE
minorTickInterval on axes causes strange behavior

### ISSUE THREAD

**Issue by troddick** [highcharts/highcharts#6330]
#### Expected behaviour
user can change x and y Axis type from ui. (linear/logarithmic). They can also change whether there are ticks or grid lines on the x and y Axis. In order to change the x and y axis grid/ticks, I need minorTickInterval:'auto', but having this causes the line to plot strangely when going to type:'logarithmic'

#### Actual behaviour
line either draws partly out of view (due to yAxis minorTickInterval: 'auto') or grid/ticks are not being added at end of line (due to xAxis minorTickInterval:'auto')

#### Live demo with steps to reproduce
http://jsfiddle.net/outuqthf/6/

#### Affected browser(s)
Only tested in Chrome

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, and sorry for the late reply!

Here's a minimal demo of the Y axis part: http://jsfiddle.net/highcharts/outuqthf/7/

**Comment by troddick** [comment]
Thanks for looking into this.
I'll wait for your next release to do another npm install to update my code with the fix.
