### ISSUE TITLE
series<scatter>.data.marker.lineWidth does not override plotOptions.series.marker.lineWidth

### ISSUE THREAD

**Issue by ychi** [highcharts/highcharts#6331]
#### Expected behaviour
lineWidth be overridden, like what happens to lineColor.

#### Live demo with steps to reproduce
http://jsfiddle.net/439712ng/

#### Affected browser(s)
All. SVG element uses width value from plotOptions.series.marker.lineWidth.

**Comment by pawelfus** [comment]
Hi @ychi 

This is already reported here: #3881
