### ISSUE TITLE
A split tooltip does not work correctly with flags

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#6332]
#### Actual behaviour
When the flag does not cover the point (x value), a tooltip for the flags does not show up - instead the tooltip for the next point is shown (with empty text).

#### Expected behaviour
I think a split tooltip should work in a similar way as a shared tooltip for flags
http://jsfiddle.net/qdg47eu0

#### Live demo with steps to reproduce
http://jsfiddle.net/qdg47eu0/1/
1. Move mouse over the flag

**Comment by oysteinmoseng** [comment]
Thank you for reporting. I think this should be considered a bug.

**Comment by simdevmon** [comment]
I think this is not resolved and should not be in stale state.
