### ISSUE TITLE
Legend covers range selector

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#6333]
If you set vertical aligment for legend items, right and top alignment for legend than legend covers range selector inputs.

#### Expected behaviour
Legend is located below the range selector.

#### Actual behaviour
Legend covers range selector.

#### Live demo with steps to reproduce
http://jsfiddle.net/Pashe4ka/m9y05a0u/
![legend](https://cloud.githubusercontent.com/assets/2900934/22558959/9f3f6bf4-e980-11e6-9c36-ba4c238a159a.PNG)

#### Affected browser(s)
Latest Chrome version

**Comment by pawelfus** [comment]
Thanks for reporting!

You can set `legend.y`, which by default is 0: http://jsfiddle.net/m9y05a0u/1/

**Comment by pliasetski** [comment]
Thanks for answer.
But chart could have title, subtitle and they could be multilin, therefore I should calculate hight of all content that is above legend.
Is this the correct behavior?

**Comment by pawelfus** [comment]
Of course you are right. With title/subtitle it becomes an issue, for example with a responsive chart.

**Comment by pawelfus** [comment]
*Internal note:*
It looks like a general issue with positioning legend. For example title vs legend also doesn't translate legend: http://jsfiddle.net/m9y05a0u/2/

**Comment by emilecaron** [comment]
Is there any temporary workaround that doesnt require setting legend Y coordinate manually ?

**Comment by pawelfus** [comment]
We can try to move legend on init and redraws, something like this: http://jsfiddle.net/x88dd51v/

What do you think? 

Snippet:
```
(function(H) {
  H.Chart.prototype.callbacks.push(function (chart) {
  	H.addEvent(chart, 'redraw', function (e) {
    	// On redraw:
    	reflowLegend(this);
    });
  	// Initial:
    reflowLegend(chart);
  });

  function reflowLegend(chart) {
    var legend = chart.legend;
    if (legend && legend.options.verticalAlign === 'top') {
      legend.group.attr({
        translateY: legend.chart.plotTop
      });
    }
  }
})(Highcharts);
```

**Comment by emilecaron** [comment]
What i wanted was to have the legend directly between the title and the chart, not on the side. So the chart needs to be vertically resized to fit the legend.
Thank you for your detailed answer though 👍

**Comment by pawelfus** [comment]
Thank you for the details. Resizing plotting area to fit both, a legend and a title, would be tricky, but if we can assume size for legend, then we can workaround this in a similar way: http://jsfiddle.net/BlackLabel/x88dd51v/1/ (see `title.y` and `chart.spacingTop`)
