### ISSUE TITLE
event.point.dataGroup.start doesn't point at start of raw data if highstock navigator doesn't start at first point ?

### ISSUE THREAD

**Issue by mhwlng** [highcharts/highcharts#6335]
I am trying to get the first raw x value when clicking on a (grouped) data point.

see :

http://jsfiddle.net/u6j09m25/3/

click on a datapoint  :

This only works correctly if the navigator starts all the way to the left, 

So, there is some kind of offset needed, to get the 'real' raw point ?

`firstx = event.point.series.options.data[event.point.dataGroup.start + ???? ][0];`

**Comment by mhwlng** [comment]
This works

 var timestamp = event.point.series.options.data[event.point.series.cropStart+event.point.dataGroup.start][0];

http://jsfiddle.net/s6vaujsx/

I don't know if needing to add 'event.point.series.cropStart' to 'event.point.dataGroup.start' is a bug or by design ?

**Comment by oysteinmoseng** [comment]
Thank you for reporting this. I'm not sure if this is a bug or expected behavior, @TorsteinHonsi?

**Comment by KacperMadej** [comment]
Related to https://github.com/highcharts/highcharts/issues/8889
Might be related to #9928

**Comment by KacperMadej** [comment]
Resolved by https://github.com/highcharts/highcharts/commit/2d0d702c6493aad166ced3d6bb3df07771fa5c54
