### ISSUE TITLE
Highstock doesn't render properly after replacing data.

### ISSUE THREAD

**Issue by micbuh** [highcharts/highcharts#6337]
#### Expected behaviour
after replacing series data, chart and navigator should show this, fully zoomed out. 

#### Actual behaviour
after replacing series data, the navigator doesn't always update. Instead the previous data is shown and the zoom slider is fully pulled to one side. (this can be seen starting from V4.2.4).
In case zoom was applied, when data is replaced, the behavior is even worse. (< V4.2.3 also affected)

![highchart](https://cloud.githubusercontent.com/assets/9218614/22633125/a6feb616-ec40-11e6-98a2-21be8495766d.png)
2009 vs. 2010

#### Live demo with steps to reproduce
http://jsfiddle.net/eu2skaqn/1/ 

- switch back and forward between the years. At some point the navigator is stuck at the year of the previous data set. (especially while switching from 2010 to 2009)
- alternatively, zoom in and switch years

#### Affected browser(s)
at least chromium, firefox (linux)

**Comment by pawelfus** [comment]
It's problem with using exactly the same same variable for navigator and series. When using a copy of original data, it works fine, please take a look: http://jsfiddle.net/eu2skaqn/3/

Duplicate of #4259

**Comment by micbuh** [comment]
thanks pawelfus, that's good to know. Fully zoomed out, it works as suspected.
But, when I am zoomed in and switch the year, the navigation slider is still pulled to the left or right (depending on previous year). That's supposed to happen, when data is replaced? If yes, what's the best attempt to automatically zoom out fully? 
Btw. I also see unnecessary calls of `afterSetExtremes()`, but that's already handled in another issue, I believe.

**Comment by pawelfus** [comment]
Yes, that's how it suppose to work. Once user zooms in (using navigator or selection) then these extremes are kept and have the higher priority for a chart than `setData()`. So if users zooms in 2011, and later clicks on your button to load another year, then you should call `chart.xAxis[0].setExtremes(min, max)` to tell Highstock extremes **should** change. 

Simple demo: http://jsfiddle.net/eu2skaqn/4/ - note that `chart.xAxis[0].setExtremes()` also calls `afterSetExtremes` event, so I used a simple flag to prevent extra calls.

**Comment by micbuh** [comment]
ok, nice, then this is actually not an issue. thanks a lot for clarification!
