### ISSUE TITLE
Highmaps reflow issue

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#6338]
Hello,
Map reflow doesn't work after I set border to map container dynamically.

#### Expected behaviour
Map should reflows to its parent container.

#### Actual behaviour
Map doesn't reflow.

#### Live demo with steps to reproduce
http://jsfiddle.net/Pashe4ka/zm4rfqve/
Please click on "Toggle border size" button in demo.

#### Affected browser(s)
Latest chrome version

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Simplified demo: http://jsfiddle.net/highcharts/zm4rfqve/1/

**Comment by TorsteinHonsi** [comment]
Apparently the Highcharts SVG itself, or its container, is blocking the container box so the `scrollWidth` is not reported correctly. A *workaround* is to remove the container before reflowing: http://jsfiddle.net/highcharts/zm4rfqve/3/
