### ISSUE TITLE
highcharts image not rendering on Edge browser(Above 20.0 version) after export using jsPDF

### ISSUE THREAD

**Issue by codeReadyy** [highcharts/highcharts#6340]
I am not sure whether it is a problem of highcharts or jsPDF but I have seen browser compatibility page on highcharts documentation, that is the reason just wanted to confirm whether it is an issue of highchart or not.
#### Expected behaviour
Should render image on pdf.

#### Actual behaviour
Image is getting black background color.
![distorted](https://cloud.githubusercontent.com/assets/17539531/22646401/3eb01fee-ec92-11e6-9bc6-4bd4499446e3.png)

#### Live demo with steps to reproduce
I am using the latest version of jsPDF and I am trying to download the highcharts with some html content. My code works fine for all browser except "Microsoft Edge above version 20.0" .
Here is the working [Plunker](https://plnkr.co/edit/LTZHOc?p=info). I have googled similar questions but none of them talk about edge browser.

#### Affected browser(s)
Above microsoft edge version 20.0

**Comment by oysteinmoseng** [comment]
Edge should fall back to the online export server (or throw an exception) for PDF export. I'll look into it.

**Comment by oysteinmoseng** [comment]
Falls back nicely for me, are you using jsPDF directly?

jsPDF is not able to handle the Highcharts SVG in Edge at the moment, which is why we have the fallback. This is an issue with jsPDF, though. 

Closing this for now. Feel free to reopen if I misunderstood somehow.
