### ISSUE TITLE
highstock/plotOptions.flags.stackDistance mouseover problem

### ISSUE THREAD

**Issue by mhwlng** [highcharts/highcharts#6341]
when using 'stacked flags' using highstock/plotOptions.flags.stackDistance

the flag moves up when moving the mouse over it.

see your own demo :

http://jsfiddle.net/gh/get/jquery/3.1.1/highcharts/highcharts/tree/master/samples/stock/plotoptions/flags-stackdistance/

and move mouse over 'stacked flag' 'C'

it moves up.

**Comment by pawelfus** [comment]
Hi @mhwlng 

This is expected behaviour as a result of fixing #1924. We move up hovered flag on mouseover if flag is stacked (and not the first flag in a stack).

**Comment by mhwlng** [comment]
ok, thanks for the explanation. 
I'll close this issue, then...
