### ISSUE TITLE
Hidden class is missing when useHTML in legend

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6342]
#### Expected behaviour
.highcharts-legend-item-hidden should be applied

#### Actual behaviour
Hidden class (highcharts-legend-item-hidden) is missing when useHTML in legend

#### Live demo with steps to reproduce
Demo:
- http://jsfiddle.net/s8m9t47s/

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
_Internal note_
It looks like in the `colorizeItem` function, addClass / attr() methods cannot be used for div element. We should use setAttribute on item.legendGroup.div element. 

@TorsteinHonsi do you have any better suggestion?

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/s8m9t47s/1/
(Note: styled mode doesn't currently work with github.highcharts.com).
