### ISSUE TITLE
No mention of jQuery dependency in data module in documentation using Google sheets

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6343]
#### Expected behaviour
There should be information in documentation regarding jQuery dependency in data module (or preferred solution would be removing this dependency)

#### Live demo with steps to reproduce
![screen shot 2017-02-06 at 14 56 27](https://cloud.githubusercontent.com/assets/19593179/22650769/e322c660-ec80-11e6-972a-552b4541d65e.png)

https://github.com/highcharts/highcharts/blob/master/js/modules/data.src.js#L278

**Comment by oysteinmoseng** [comment]
Thank you for reporting. I think we'll consider this a bug, as it is surely not intentional to depend on jQuery for this.

**Comment by TorsteinHonsi** [comment]
The data module no longer depends on jQuery.
