### ISSUE TITLE
Responsiveness rules must contain the exact number of series of a chart

### ISSUE THREAD

**Issue by AtishaGarinMchd** [highcharts/highcharts#6347]
#### Expected behaviour
Responsive chart options related to an unexisting series or axis should be ignored and should not make the chart crash.
It would be useful to be able to share the same responsive rules with multiple dials.
Ideally, it would be great to have the option to define a series configuration once, applicable for all series of the chart.

#### Actual behaviour
A chart having less series than responsive.rules.chartOptions.series will crash when responsiveness conditions are met

#### Live demo with steps to reproduce
1. Open https://jsfiddle.net/wuang1so/1/
2. Click on Chart1 button. 
=> Top chart series changes to color chartreuse ('#7fff00')
3. Click on Chart2 button
=> Bottom chart crashes.

#### Affected browser(s)
Verified on Chrome, probably all.

#### Associated commit
https://github.com/highcharts/highcharts/commit/ff5f92ce44f665a7946993f3ea1f33e90e196143

**Comment by TorsteinHonsi** [comment]
> Ideally, it would be great to have the option to define a series configuration once, applicable for all series of the chart.

Yes, that's what the `plotOptions` structure does. It works well with your case: https://jsfiddle.net/highcharts/wuang1so/2/

**Comment by AtishaGarinMchd** [comment]
Thanks, that really helps and let us cut down some lines of code.
Nevertheless xAxis and yAxis are not driven by plotOptions, causing the same need of conditionally adding responsiveness rules.

Example for yAxis below: 
https://jsfiddle.net/rdmj2q20/

**Comment by TorsteinHonsi** [comment]
Thanks! 

According to the docs:
> A special case is configuration objects that take arrays, for example xAxis, yAxis or series. For these collections, an id option is used to map the new option set to an existing object. If an existing object of the same id is not found, the item of the same indexupdated. So for example, setting chartOptions with two series items without an id, will cause the existing chart's two series to be updated with respective options.

I think the actual problem here is that two charts are sharing the same set of options. I will look into that.

**Comment by TorsteinHonsi** [comment]
Your demos, fixed: 
* http://jsfiddle.net/highcharts/rdmj2q20/6/
* http://jsfiddle.net/highcharts/wuang1so/4/
