### ISSUE TITLE
Highchart tooltip does not show up completely.

### ISSUE THREAD

**Issue by vcmSwathiRai** [highcharts/highcharts#6352]
Hi,
I am using highchart version 5.0.7 in styled mode. For one of my graph tooltip doesn't show up completely. After googling I got few solution one of them is:
```
.highcharts-container {
   overflow: visible !important;
   z-index: auto !important;
} 
```
I tried this but it did not solve my problem. I have recreated issue in jsFiddle: http://jsfiddle.net/35r5k67y/5/

**Comment by pawelfus** [comment]
Hi @vcmSwathiRai 

This is known bug, please take a look: #5784. Could you try JS solution from there? It looks fine with non-useHTML tooltip: http://jsfiddle.net/35r5k67y/6/

I am closing this issue as a duplicate.
