### ISSUE TITLE
highcharts-convert.js in server-mode return svg with black image

### ISSUE THREAD

**Issue by Daizz** [highcharts/highcharts#6354]
result svg file with black background for any charts (all fine with the same settings in (5.0.6))

if open img in browser and press "Ctrl+A" 
![image](https://cloud.githubusercontent.com/assets/449665/22734774/923a76fa-edff-11e6-9a6a-71c44030ccbe.png)

> phantomjs highcharts-convert.js -infile test.json -outfile out1.svg -constr Chart

file test.json

> "{\"infile\":\"{xAxis: {categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']},series: [{data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]}]};\",\"callback\":\"function(chart) {chart.renderer.arc(200, 150, 100, 50, -Math.PI, 0).attr({fill : '#FCFFC5',stroke : 'black','stroke-width' : 1}).add();}\",\"constr\":\"Chart\"}"

phantomjs 2.1.1
highcharts 5.0.7
highcharts-convert.js  ( JS v3.0.1 (2012-11-02) )

**Comment by TorsteinHonsi** [comment]
For command line conversion, we recommend that you use the new [Highcharts export server](http://www.highcharts.com/news/256-introducing-the-highcharts-node-js-export-server/) instead. It is a node server and CLI conversion tool.
