### ISSUE TITLE
Y axis title rotation bug

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#6355]
Hello,
If I set to left YAxis title rotation to 90, it doesn't fit on the screen.

#### Expected behaviour
Title should fit on the screen.

#### Actual behaviour
Title doesn't fit on the screen.

#### Live demo with steps to reproduce
http://jsfiddle.net/Pashe4ka/q1zyec4p/

#### Affected browser(s)
Chrome latest version

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

It does what it is supposed to do, but you need to set the `textAlign` in addition: http://jsfiddle.net/highcharts/q1zyec4p/1/
