### ISSUE TITLE
State-related conflict caused by Series.update and Series.setData

### ISSUE THREAD

**Issue by inad9300** [highcharts/highcharts#6357]
#### Expected behaviour
Series.update should work despite Series.setData being called before.

#### Actual behaviour
Once Series.setData has been called, Series.update produces odd effects on the chart – that is my guess anyway.

#### Live demo with steps to reproduce
http://jsfiddle.net/inad9300/scj4d23o/

There are different workflows that one can try. First, this two sequences (series of actions preceded by a page refresh) work:

1. Click 'Show/hide labels' repeatedly.

and

1. Click 'Show/hide empty categories' repeatedly.

The most significant problem arises when you try the following, after which none of the buttons will work anymore:

1. Click 'Show/hide empty categories'.
2. Click 'Show/hide labels'.

Trying out the opposite sequence has some minor consequences as well: the columns series will lots its animation.

#### Affected browser(s)
Chrome, Firefox... Seems not to be related with the browser.

**Comment by pawelfus** [comment]
Hi @inad9300 

Thank you for reporting this issue. However I am not sure if this is a bug in Highcharts, let me explain: [`series[index].data`](http://api.highcharts.com/highcharts/Series.data) is a reference to the Point class. I am not sure how `_.cloneDeep` deals with circular references in objects, but I think it's not the best idea to clone whole class Point. 

Instead, I suggest to use [`series[index].options.data`](http://api.highcharts.com/highcharts/Series.options), which stores original data passed to the series. It works without issues: http://jsfiddle.net/qn0vjo2h/

**Comment by inad9300** [comment]
Well, the solution turned out to be rather simple! I think I wouldn't have figure it out from the documentation though -- both descriptions seem a bit vague.

In any case, thanks a lot for your time and your responsiveness.
