### ISSUE TITLE
Working of the softMin/softMax along with the floor/ceiling

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6359]
#### Expected behaviour
The softMin/softMax should work with the floor/ceiling, where softMin/softMax should display as a min/max until is exceeded and floor/ceiling should represents the lowest/highest allowed value for axis extremes.

#### Actual behaviour
When the softMin/softMax and the floor/ceiling are combined together it seems like the softMin/softMax have no effect.

#### Workaround
Set the Axis extremes with softMin/softMax values on load.

#### Live demos
http://jsfiddle.net/d_paul/au6o07xs/ - softMax combined with ceiling (does not work)
http://jsfiddle.net/d_paul/7ht8m45e/ - using Axis.setExtremes() (works)

**Comment by FlorianBurgevin** [comment]
+1
