### ISSUE TITLE
Highchart chart doesn't render in dynamically created div in Highstock's release

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#636]
See example https://jsfiddle.net/WFnTr/6/

Creating a Highcharts chart object  in a dynamically created div.

When switched to use highstock-release  the chart isn't rendered, however when using Highcharts it does work.
1. Click and mark a selection in the first chart. This should create a new chart below it.

**Comment by miguel-orange** [comment]
Hello,
I'm using version 5.0.6 and highmaps has the same behavior.

**Comment by TorsteinHonsi** [comment]
This seems to work okay: http://jsfiddle.net/highcharts/WFnTr/94/

**Comment by pawelfus** [comment]
It's also broken: click on a chart -> we don't get a chart as we get with Highcharts: http://jsfiddle.net/WFnTr/95/

**Comment by pawelfus** [comment]
See my commit above. Note it's different than mutating data: this issue applies only to Highstock and Highmaps, where `options.series` are set to null to increase performance (to avoid copying a lot of data points).

**Comment by bre1470** [comment]
@TorsteinHonsi @pawelfus 
The original example is working for me: https://jsfiddle.net/qg01ormd/. Can someone confirm and close the issue?

**Comment by pawelfus** [comment]
Yes, it's fixed since v7.0.0
Thanks!
