### ISSUE TITLE
innerRadius and outerRadius of plotBand in polar chart are not documented

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6360]
#### Behaviour
Works, but is not documented.

#### Live demo
http://jsfiddle.net/hhh2jwdb/3/

**Comment by TorsteinHonsi** [comment]
Why did you close it? It seems like it is legit...

**Comment by KacperMadej** [comment]
The issue was not related to any client report and I checked related code and this feature works because one function is used for few things. For yAxis radius related options are required (loaded internally if needed) and it's documented for gauge, while for polar chart's xAxis it works by accident. It's a happy accident (a new feature is added), but still it's not by design - at least it looks like it from the code.

Should I reopen and add docs for the option? @TorsteinHonsi
