### ISSUE TITLE
accessibility module incompatible with Internet Explorer 8 and earlier

### ISSUE THREAD

**Issue by mistergone** [highcharts/highcharts#6361]
#### Expected behaviour
Highcharts is compatible with IE6 through IE8. 

#### Actual behaviour
Highcharts' accessibility module causes an Expected Identifier error in IE6 through IE8.

#### Live demo with steps to reproduce
http://jsfiddle.net/z77pa6vz/

(Note: jsfiddle has other issues when used in IE8 and earlier, but the Expected Identifier error should show up for `accessibility.js`)

<img width="836" alt="screen shot 2017-02-10 at 10 45 39 am" src="https://cloud.githubusercontent.com/assets/1490703/22834684/f679e8dc-ef83-11e6-8e78-07c66d56bc85.png">

#### Affected browser(s)
Internet Explorer 6, 7, and 8

#### Details
Internet Explorer versions 6 through 8 do not allow for the use of "reserved words" as (dot notation) object properties, though it will allow them formatted as an Array property.

In `accessibility.src.js`, there are two references to `typeToSeriesMap.default` which causes the error (`default` is a reserved word).

In my (somewhat limited) testing, changing the references to `typeToSeriesMap['default']` bypasses the error, so that should be an easy fix. Alternatively, the property name `default` could be changed to any non-reserved word.

**Comment by TorsteinHonsi** [comment]
_Internal note_:

We should make the module fail gracefully with old IE, and make a note on the documentation page that it is not supported.

**Comment by oysteinmoseng** [comment]
Hopefully fixed now. I don't see anything in the module that suggests it should fail on old IE apart from the things fixed, so I don't think we'll need to mark it as unsupported in the docs. Will test and verify.
