### ISSUE TITLE
Highstock charts ignore redraw flag when removing a series

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/highcharts#6363]
1. Create a chart with at least 1 series
2. Remove the series programmatically, with the redraw boolean set to false: `series.remove(false)`

Behavior:
Chart will ignore redraw boolean and still redraw.

This is due to Highstock also removing the associated series in the navigator without any arguments. You can see in the code snippet below that the removal of the navigator series will always redraw the chart.

```                        
                        // Handle series removal
                        addEvent(base, 'remove', function() {
                            if (this.navigatorSeries) {
                                erase(navigator.series, this.navigatorSeries);
                                this.navigatorSeries.remove();
                                delete this.navigatorSeries;
                            }
                        });
```

**Comment by pawelfus** [comment]
*Internal note:*
Fix causes `stock/members`:`series-remove` test to fail, but it's fine (as it compares pixel by pixel with current version).
