### ISSUE TITLE
Improvement: Highstock as a module for Highcharts

### ISSUE THREAD

**Issue by gevgeny** [highcharts/highcharts#6364]
Using current modules model can be difficult in some cases when user works with ES6 modules and bundlers. Take [angular2-highcharts](https://github.com/gevgeny/angular2-highcharts) which is one of numerous Highcharts wrappers. This wrapper provides angular components to display charts. User easily can specify what kind of chart component he wants to create: 
1. `<chart type="Chart" [options]="options"></chart>`
2. `<chart type="Map" [options]="options"></chart>`
3. `<chart type="StockChart" [options]="options"></chart>`

First example works fine because angular2-highcharts references to highcharts core module by default. Second example is more tricky since it requires user to specify additional module before:
```js
import Highcharts  from 'highcharts';
import Highmap  from 'highcharts/modules/map';

Highmap(Highcharts); 
```
It makes sense because it helps to reduce result bundle size when only necessary modules are loaded.
Third example is the most unpleasant because user cannot just load highstock functionality when he needs it. One of the options it to use highstock by default right in the wrapper but it increases result bundle size for people how no need highcharts and can confuse users who don't have highstock license. Another option requires users to manually specify highcharts as an alias of highstock in bundler config. 
Fragment from webpack config: 
```js
resolve: {
  alias: {
    highcharts$: "highcharts/highstock.src.js"
  },
}
```
this option is hacky and not available for many user who don't have direct access to Webpack or SystemsJs config.
So it would be great to have possibility to load Highstock just like other modules.

Thanks.

**Comment by TorsteinHonsi** [comment]
Actually this was implemented as of v5.0.7, though it is not clearly communicated in our installation tutorials. I'll go over the docs and add the appropriate information. [View live demo](http://jsfiddle.net/highcharts/jtr1ejju/).
