### ISSUE TITLE
series.init is not a function - stop[1].indexOf is not a function -  require.js

### ISSUE THREAD

**Issue by Legends** [highcharts/highcharts#6365]
#### Error
Uncaught TypeError: series.init is not a function

#### Expected behaviour
Show functional charts

#### Actual behaviour
Shows nothing.

#### Live demo with steps to reproduce

**Highcharts JS v5.0.7**

**[DEMO](https://jsfiddle.net/legends77/fqerhwun/8/)** 
Check the console to see the error!

It sometimes works and sometimes not. So I think there must be an issue regarding the  dependency load order ?!?

The load order I have specified is:
Load highchart.js before all other scripts/modules, the scripts/modules have only a dependency on highchart.js.

This is the [example ](http://www.highcharts.com/demo/gauge-solid/dark-unica) I use, and I load all dependencies using require.js.

I've AMDfied all scripts I have here and made all dependend on highcharts.

`require(["jquery", "highcharts", "highcharts-modules-data", "highcharts-more", "highcharts-3d", "highcharts-modules-exporting", "highcharts-modules-solid-gauge"], function ($, Highcharts) {...`

#### Affected browser(s)
Chrome 56.029... x64

![image](https://cloud.githubusercontent.com/assets/966368/22856821/d9e3f71e-f099-11e6-88d6-569bbf92c283.png)

**Comment by Legends** [comment]
I also get another error using the [heatmap example](http://www.highcharts.com/demo/heatmap/dark-unica).
**Error:**
![image](https://cloud.githubusercontent.com/assets/966368/22858316/ca54865e-f0b9-11e6-9274-9d6e8f446aa5.png)

heatmap.src.js is also AMDfied:

```
if (typeof define === 'function' && define.amd) {
		// AMD. Register as an anonymous module.
		define(["highcharts"], factory);
	} else if (typeof module === 'object' && module.exports) {
		module.exports = factory;
	} else {
		factory(Highcharts);
	
```}

**Comment by tdhooper** [comment]
I think this can be fixed by ensuring `highcharts-more` is loaded before `solid-gauge`:

````
require.config({
    paths: {    
        jquery: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min', 
        highcharts: 'https://rawgit.com/Legends/hosting/master/highcharts.src',
        'highcharts-modules-drilldown': 'https://rawgit.com/Legends/hosting/master/drilldown.src',
        'highcharts-modules-heatmap': 'https://rawgit.com/Legends/hosting/master/heatmap.src',
        "highcharts-3d": 'https://rawgit.com/Legends/hosting/master/highcharts-3d.src',
        "highcharts-more": 'https://rawgit.com/Legends/hosting/master/highcharts-more.src',
        'highcharts-modules-data': 'https://rawgit.com/Legends/hosting/master/data.src',
        'highcharts-modules-exporting': 'https://rawgit.com/Legends/hosting/master/exporting.src',
        'highcharts-modules-solid-gauge': 'https://rawgit.com/Legends/hosting/master/solid-gauge.src'   
    },
    shim: {
        'highcharts-modules-solid-gauge': {
            deps: ['highcharts-more']
        }
    },
    waitSeconds: 10, // wait 10s before raising script load timeout 
});

````

**Comment by Legends** [comment]
Yes, that does trick, thanks!

**Comment by jon-a-nygaard** [comment]
Thanks @tdhooper for solving the issue.

Some additional info: We made an attempt to add some guidance for these issues, but unfortunately it caused some unexpected issues. Can be read about in #6686

**Comment by Tearsillusion** [comment]
Thanks @tdhooper
