### ISSUE TITLE
I cannot register, the captcha is buggy

### ISSUE THREAD

**Issue by vporton** [highcharts/highcharts#6366]
#### Expected behaviour

After assemling the captcha and clicking Submit I should become a registered user.

#### Actual behaviour

After I correctly assemble the captcha image at http://forum.highcharts.com/ucp.php?mode=register and click Submit, I get the message "The solution of task you submitted was incorrect. Please read the instruction and try again."

It is despite the green checkmark indicating that I did a correct solution. I tried a few times with the same error message.

#### Affected browser(s)

Firefox 51.0.1 (32-bit) for LInux.

**Comment by gvaartjes** [comment]
@vporton Yes, I can verify it's probably the captcha. Thanks for letting us know. We're working on it.

**Comment by gvaartjes** [comment]
Hi @vporton, 
we replaced the old captcha with Google's ReCaptcha. Now it's working. Welcome to the Highcharts Forum.
