### ISSUE TITLE
series.point.events.mouseOver event tooltipPos is outside the chart when value is out of scale

### ISSUE THREAD

**Issue by AtishaGarinMchd** [highcharts/highcharts#6367]
#### Expected behaviour
Using a series point event to render a custom tooltip, I would like to obtain consistent tooltipPos values whether a series value is within displayable range or not.

As a workaround, I would like to obtain a chart's plotBottom and plotRight values to normalize the custom tooltip's position.

#### Actual behaviour
When a series values is not being displayed entirely because of scaling, point is outside browser's rendering area.  Highchart's tooltip is displayed on the bottom of the rectangle instead of top.

#### Live demo with steps to reproduce
https://jsfiddle.net/487eontk/5/

Workaround attempt:
https://jsfiddle.net/jsvfhh4w/1/

#### Affected browser(s)
Tested on Chrome.

**Comment by pawelfus** [comment]
Hi @AtishaGarinMchd 

I think this is not a bug, `tooltipPos` is the internal property, which is normalized later. You can get "plotBottom" as a sum of `plotTop + plotHeight` and the same for "plotRight": `plotLeft + plotWidth`. 

Demo for you: https://jsfiddle.net/jsvfhh4w/2/

**Comment by AtishaGarinMchd** [comment]
True. e.target.tooltipPos is internal... my bad.
I am closing the issue.
Thank you for your answer :) 👍
