### ISSUE TITLE
"Malta" dataLabel is cut off (not fully visible on plot area) on Europan Union map.

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6371]
#### Expected behaviour
See whole "Malta" dataLabel

#### Actual behaviour
"Malta" dataLabel is not fully visible

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/custom/european-union

**Comment by oysteinmoseng** [comment]
Thank you for reporting.

Workaround: Set `yAxis` `max` and `min` manually, http://jsfiddle.net/qfaw0azr/

**Comment by TorsteinHonsi** [comment]
Good idea. To avoid hard coding, you can set a `maxPadding` instead: http://jsfiddle.net/highcharts/qfaw0azr/1/
