### ISSUE TITLE
When migrating from 5.0.5 to 5.0.7, `Chart.get` now returns undefined instead of null when axis or series not found

### ISSUE THREAD

**Issue by jaapz** [highcharts/highcharts#6375]
In previous versions, Chart.get (used when getting a specific series or axis by ID), used to return `null` when the chart or series was not found. Now it returns undefined. This breaks a lot of my code.

This is a breaking API change and I would think something like this would at least be communicated in the changelog.

Or is this an unintended change?

**Comment by TorsteinHonsi** [comment]
It is an intended change after a rewrite of the `get` function. Actually the docs don't define what should happen if no item is found. I have added that information to the docs now.
