### ISSUE TITLE
When two timestamps are too close, markers are not displayed.

### ISSUE THREAD

**Issue by sseif** [highcharts/highcharts#6377]
#### Expected behaviour
Markers are displayed correctly in chart1 similar to chart2 (refer to fiddle).

#### Actual behaviour
Markers are not displayed in chart1 (refer to fiddle).

#### Live demo with steps to reproduce

http://jsfiddle.net/2b7Lrk9u/1/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @sseif 

This is intentional behaviour. For point with a high density, markers are not rendered. This is explained in our [docs](http://api.highcharts.com/highstock/plotOptions.series.marker.enabled).

Updated demo for you: http://jsfiddle.net/2b7Lrk9u/2/
