### ISSUE TITLE
Mixed conttent in https for combo-meteogram

### ISSUE THREAD

**Issue by MattXcz** [highcharts/highcharts#6380]
#### Expected behaviour
HTTPS needed.
#### Actual behaviour
Images loaded from http://www.highcharts.com/samples/graphics/meteogram-symbols-30px.png only loads as http.

#### Live demo with steps to reproduce
https://www.mattx.cz/predpoved_graph.php

#### file:

highcharts/samples/highcharts/demo/combo-meteogram/demo.js

**Comment by zhy1stgg** [comment]
+1

**Comment by TorsteinHonsi** [comment]
This is already fixed in our demo, so you need to make the same fix to your application: https://github.com/highcharts/highcharts/blob/v5.0.7/samples/highcharts/demo/combo-meteogram/demo.js#L278

**Comment by MattXcz** [comment]
Thanks you for your answer.
Google Chrome site is not secured, even if loaded as HTTPS.
I put the PNG file on my server : `https://cdn.mattx.cz/mattx/pocasi/meteogram-symbols-30px.png`
Also, transleted to czech : `https://cdn.mattx.cz/mattx/pocasi/yr_graf.js`

Everybody, feel free to use it.
