### ISSUE TITLE
Tooltip with followPointer and shred is getting stuck on edges of columns

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6381]
#### Expected behaviour
Tooltip should follow pointer all over the plot area.

#### Actual behaviour
Tooltip gets stuck on edges of columns.

#### Live demo with steps to reproduce
http://jsfiddle.net/2v0a72mb/

1. Hover over the column
2. Hover over the edge of the column and out into the plot area
3. Tooltip stays on the column edge.

Was working in 5.0.0.
Looks like the offending commit is this one: https://github.com/highcharts/highcharts/commit/73e3ba9

**Comment by pawelfus** [comment]
Works fine in 5.0.9+

Demo: http://jsfiddle.net/2v0a72mb/1/
