### ISSUE TITLE
bar chart displays 0 instead of null in categorical xAxis

### ISSUE THREAD

**Issue by fourmisz** [highcharts/highcharts#6382]
#### Expected behaviour
Do not display bar if there is null in categorical xAxis.

#### Actual behaviour
Highcharts shows null as '0'.

*data*
```javascript
"data": [
        {
          "name": null,
          "y": 85.71
        },
        {
          "name": "Thu Feb 16 23:53:19 KST 2017",
          "y": 86.48
        },
        {
          "name": "Thu Feb 16 23:53:24 KST 2017",
          "y": 78.22
        },
        {
          "name": "Thu Feb 16 23:53:30 KST 2017",
          "y": 86.6
        },
        {
          "name": "Thu Feb 16 23:53:35 KST 2017",
          "y": 78.4
        }
 ]
```

![image](https://cloud.githubusercontent.com/assets/2562653/23027027/72b510da-f4a6-11e6-9358-80ff3d30ec29.png)

#### Live demo with steps to reproduce

http://jsfiddle.net/ahrzyc8s/

#### Affected browser(s)
Chrome 55.0.2883.95 (64-bit)

**Comment by TorsteinHonsi** [comment]
If no category exists for the given item, Highcharts will insert the index instead.

To omit the label, add an empty string instead: http://jsfiddle.net/highcharts/ahrzyc8s/1/

To hide the complete bar, you need to set the Y value to `null`.
