### ISSUE TITLE
Range Selector selects all points after dynamic update of options

### ISSUE THREAD

**Issue by carag-matthew** [highcharts/highcharts#6383]
#### Assumptions
Highstocks chart is consistently receiving new data points and updating the series.
Highstocks chart range selector shows a subset of the entire range.

#### Expected behaviour
When making dynamic changes to the options of the highstocks chart, the range selector maintains the range even after new points are added to the series*.

* May or may not be relevant: our specific project involves updating multiple series; however, the jsfiddle only shows the case of one series.

![image](https://cloud.githubusercontent.com/assets/8943898/23029677/f7919c22-f430-11e6-9931-ac486801562f.png)

This is the initial state of the jsfiddle.

#### Actual behaviour
When making dynamic changes to the options of the highstocks chart, the range selector defaults the range to encompass all points after a new point is added.

![image](https://cloud.githubusercontent.com/assets/8943898/23029720/127624fe-f431-11e6-9770-709dc2f47ce0.png)

This happens when either the 'on' or 'off' buttons are selected and thus updating the highstocks chart options.

#### Live demo with steps to reproduce
http://jsfiddle.net/dyug7zsx/11/

#### Affected browser(s)
Google Chrome Version 56.0.2924.87 (64-bit)
Mozilla Firefox 51.0.1 (32-bit)

**Comment by pawelfus** [comment]
Thank you for reporting!
