### ISSUE TITLE
useHTML option on label of plotband causes text to be on top of tooltip

### ISSUE THREAD

**Issue by redfire** [highcharts/highcharts#6385]
#### Expected behaviour
Labels should be indicative information. They should always be cover by the tooltip when user is hover over data. 

#### Actual behaviour
When setting useHTML to true on the plotband label it becomes covered by tooltip. 

#### Live demo with steps to reproduce
http://jsfiddle.net/b9oqacxa/

Hover over data to get the tooltip and attempt to position it over the label. You'll see it will be on top of the tooltip. See also this screenshot: https://s1.postimg.org/jiax908f3/label.jpg

#### Affected browser(s)
Tested in chrome.

**Comment by zhy1stgg** [comment]
> The downsides are that: it will always be laid out on top of all other SVG content

from Highcharts docs: http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#html

solutions: http://stackoverflow.com/questions/13740200/highcharts-html-tooltip-datalabels-render-issue
