### ISSUE TITLE
Meteogram other location 

### ISSUE THREAD

**Issue by debriuman** [highcharts/highcharts#6386]
Only works location London

    http://www.highcharts.com/demo/combo-meteogram#https://www.yr.no/place/United_Kingdom/England/London/forecast_hour_by_hour.xml

shows the correct result

but

    http://www.highcharts.com/demo/combo-meteogram#https://www.yr.no/place/Austria/Lower_Austria/Jettsdorf/forecast_hour_by_hour.xml

does not work.

Another example:

Is working (The original download files from highcharts.com, ver.7.0.5, were used.):

    http://www.3www.at/assets/highcharts/examples/combo-meteogram/index.htm#https://www.yr.no/place/United_Kingdom/England/London/forecast_hour_by_hour.xml

Does not work:

    http://www.3www.at/assets/highcharts/examples/combo-meteogram/index.htm#https://www.yr.no/place/Austria/Lower_Austria/Jettsdorf/forecast_hour_by_hour.xml

Best Regards!

**Comment by TorsteinHonsi** [comment]
The weather forecast XML is served through our server at www.highcharts.com and is only intended for use with our own demos.

We recently discovered abuse of the service, so we added some limitations. Here's the location where you would change it to use your own server: https://github.com/highcharts/highcharts/blob/v5.0.7/samples/highcharts/demo/combo-meteogram/demo.js#L751

@SamHoulder For the sake of our own demo, can you open up so that we can load forecasts from different locations? But limit only on the referer instead.

**Comment by debriuman** [comment]
Thank you for your answer

**Comment by SamHoulder** [comment]
This should work now for our demos, limited by referer.

**Comment by debriuman** [comment]
I changed locations jsonp.php on my server and it works fine thanks

**Comment by rbishwajit** [comment]
I am using Highchart with pentaho and pentaho server is apache . how can i call this php file on my server

**Comment by sebastianbochan** [comment]
Github is our bugtracker, so please use forum / stackoverflow or email for the support cases. 
You can find more informations about the support [here](http://www.highcharts.com/support)

**Comment by ZXant** [comment]
Torstein

Researching for days, and can not make Highchart Meteogram to work to other location other than London. Understand must place 'jsonp.php' on own server, but can not locate jsonp.php file as well (as it seems removed from highcharts/data folder).

May please advice on how to make Meteogram to work to diff locations and/or provide 'jsonp.php'.

Thanks,
Xant
NY/US

**Comment by pawelfus** [comment]
Hi @ZXant 

Thanks for reporting the issue. The file you refer to is no longer needed. It seems that `cors.io` is not working anymore, trying e.g. `YaCDN` service we get correct results: https://jsfiddle.net/BlackLabel/cm0xaen9/

**Comment by ZXant** [comment]
Pawel

Thank you for solution and reply, as I spent soo much time trying to figure-out trying to adjust 'jsonp.php' or other versions (as the one using cors.io).

But you crack-it! 

Thanks much, as Im sure the WeeWX will also appreciated.

Xant
