### ISSUE TITLE
inconsistance of UTC time display when using dateFormat function:

### ISSUE THREAD

**Issue by kennywangjin** [highcharts/highcharts#6388]
#### Expected behaviour
i have local datetime and i disable utc via global settings of 'useUTC:false'.
I expect that datetime for the xAxis could show corrent local time.

#### Actual behaviour
IE (11), Edge (latest) and Firefox (latest) work just as expected.
While chrome (55) fails. It adds 8 hours to my local time (I am in China and 8 hours earlier than UTC). seems that useUTC:false setting doesn't work in chrome.

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
This works fine on my machine. I am on Central European Time and browsers display the same scale. Can you open http://jsfiddle.net/highcharts/of99L2ar/ and upload screenshots from different browsers? It might give us an idea.

**Comment by kennywangjin** [comment]
@TorsteinHonsi 
Please try this one: `http://jsfiddle.net/of99L2ar/3/` in Chrome.
When I use Date.parse("2017-02-21T15:05:25.32") in xAxis, IE/Edge and Firefox show correct local time (15:05), but chrome shows +8 time (23:05). 
While disable UTC, I expect that the time I pass in would be treated as local time.

**Comment by pawelfus** [comment]
For me it also works fine (latest chrome, osx), screenshot from your demo (I'm UTC+1 too):

![screen shot 2017-02-22 at 13 26 44](https://cloud.githubusercontent.com/assets/1453926/23211480/ae93f886-f902-11e6-88af-d6fd7d8d1fd8.png)

Actually Firefox returns different format:
![screen shot 2017-02-22 at 13 38 54](https://cloud.githubusercontent.com/assets/1453926/23211857/4b45408a-f904-11e6-98e1-7d8632a59b2c.png)

To be clear: China is +8hours, so all browsers should return 23:05 for you @kennywangjin when using `useUTC: false`. 

Using full date format for parsing: `Date.parse("2017-02-21T15:05:25.32+00:00")` - works fine.

Using timestamp (number) instead of parsing date-string also works fine: http://jsfiddle.net/of99L2ar/7/ - I suggest to use that solution as is not influenced by different browsers' engines.

**Comment by kennywangjin** [comment]
CHROME:
![chrome](https://cloud.githubusercontent.com/assets/3364218/23241345/8dd7c9b4-f9ad-11e6-9be9-fccf3ad99e0c.png)
EDGE:
![edge](https://cloud.githubusercontent.com/assets/3364218/23241344/8dd7cd1a-f9ad-11e6-9f60-263750ebbb77.png)
FIREFOX:
![firefox](https://cloud.githubusercontent.com/assets/3364218/23241346/8dd923e0-f9ad-11e6-8476-dd19267bb413.png)
IE:
![ie](https://cloud.githubusercontent.com/assets/3364218/23241347/8dd95c02-f9ad-11e6-9fec-adea0402bddd.png)

Please check images above. All these charts above are rendered with same code. I use the time via Date.parse([ISO date string]). please refer this link: [http://jsfiddle.net/of99L2ar/8/](http://jsfiddle.net/of99L2ar/8/)
Only in Chrome, local time is mis-handled, as the images above show.
My workstation:
Win10(pro) latest, Firefox (latest), Chrome (latest), Edge (latest), IE 11
time zone: china (+8)

**Comment by pawelfus** [comment]
Yes, I see the difference, but I am not sure if this is something we should take care of, as input options are just differently handled by browsers. What I want to say is that your ISO date string (I assume it's ISO-8601) is not compatible with browsers, format:

`2017-02-23T09:37:00`

Should be written in ISO-8601 (in UTC) as:

`2017-02-23T09:37:00Z` or `2017-02-23T09:37:00+00:00`.

With these formats chart will display properly, compare with browsers: 
- http://jsfiddle.net/01nywa5p/1/ (`2017-02-23T09:37:00Z`)
- http://jsfiddle.net/01nywa5p/2/ (`2017-02-23T09:37:00+00:00`)
- http://jsfiddle.net/01nywa5p/3/ (`2017-02-23T09:37:00`)

Please, let me know if I misunderstood something. My results from simple `new Date()` with a given formats in Firefox:

``` javascript
> new Date('2017-02-23T09:37:00')
< 'Date 2017-02-23T08:37:00.000Z'  -- see hours
> new Date('2017-02-23T09:37:00Z')
< 'Date 2017-02-23T09:37:00.000Z'
> new Date('2017-02-23T09:37:00+00:00')
< 'Date 2017-02-23T09:37:00.000Z'
```

**Comment by TorsteinHonsi** [comment]
Closing this, as Highcharts doesn't deal with `Date.parse`. Highcharts expects X values as integers.
