### ISSUE TITLE
First series don't have hovered state

### ISSUE THREAD

**Issue by WhiteTea** [highcharts/highcharts#6391]
#### Expected behaviour
Expect first series to have hovered state to highlight it's name in tooltip.

![hovered1](https://cloud.githubusercontent.com/assets/2177595/23165801/ee62f390-f84e-11e6-8982-7b587a97266e.png)

#### Actual behaviour
First series don't have hovered state.

![hovered2](https://cloud.githubusercontent.com/assets/2177595/23165804/f4cb5a9c-f84e-11e6-8570-b24071391270.png)

#### Live demo with steps to reproduce

I tried to highlight series name in shared tooltip.

http://jsfiddle.net/Nafania/r1ef696a/
1. Move cursor to hover first series point;
2. First series name is highlighted with bold font in tooltip just fine;
3. Move cursor to hover second series point;
3. Second series name is highlighted with bold font in tooltip;
4. Move cursor to hover first series point again;
5. First series name is not highlighted with bold font and first series don't have state 'hover' in tooltip.formatter.

#### Affected browser(s)
Yandex Browser (chromium based)
Chromium
Safari

**Comment by pawelfus** [comment]
Hi @WhiteTea 
Thank you for reporting! 

*Internal note:*
It works fine with `runPointActions` branch: http://jsfiddle.net/r1ef696a/2/ @jon-a-nygaard

**Comment by pawelfus** [comment]
Works fine in 5.0.10.
