### ISSUE TITLE
Exporting from iframe on IE11

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6392]
#### Expected behaviour
File should be downloaded and trigger a pop up with a question about whether you would like to open or save.

#### Actual behaviour
No indication that an exported chart is ready to download or open. After clicking in exporting menu nothing is showing.

#### Live demo with steps to reproduce
File to run:
```
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
</head>

<body>
  <iframe src="highcharts.html" width="700" height="800"></iframe> 
</body>
</html>
```

File `highcharts.html`:
```
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>  
</head>

<body>
    <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
    <script>
    Highcharts.chart('container', {
        series: [{
            data: [1,2,3]
        }]
    });</script>

</body>
</html>
```

#### Affected browser(s)
IE11 on Win10

**Comment by TorsteinHonsi** [comment]
I got this on BrowserStack. The download is presented in a dialog at the bottom:

![skjermbilde 2017-02-27 kl 14 08 51](https://cloud.githubusercontent.com/assets/227836/23362533/7710ea16-fcf6-11e6-9591-ac4b8207e6d1.png)
