### ISSUE TITLE
Data grouping not applied to hidden series

### ISSUE THREAD

**Issue by dualbootsoftware** [highcharts/highcharts#6393]
#### Expected behaviour
All series regardless of visibility should have data grouping applied (if data grouping is applicable)

#### Actual behaviour
Hidden series are not data grouped, leading to large memory usage on very large series 

Notice one series here is using ~13MB of heap and the others are much smaller. The one using ~13MB is hidden (see fiddle below). 

![screen shot 2017-02-21 at 9 42 46 am](https://cloud.githubusercontent.com/assets/15080439/23169654/99f54f4e-f81a-11e6-9eb3-7bee405895ba.png)

I believe this was caused in this commit by this fix for https://github.com/highcharts/highcharts/issues/5493 -  https://github.com/highcharts/highcharts/commit/4acf1e40d7c079bc23f0e54f06e4289789dd8845

#### Live demo with steps to reproduce

http://jsfiddle.net/joelhnatow/y516qj6a/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thank you for reporting this issue.

Fixed by a9b6ed4975925b07b5fc44756dbb10f76649f0e8 (wrong ticket number in the commit message)

**Comment by dualbootsoftware** [comment]
Thanks Pawel!

**Comment by pawelfus** [comment]
Fixed in v5.0.9
