### ISSUE TITLE
Column tooltips are elusive for lower density series

### ISSUE THREAD

**Issue by sanoodles** [highcharts/highcharts#6396]
#### Expected behaviour
On combined charts in which one column series has quite lower data point density than another series in the same chart, the tooltip should contain the column value as long as the user hovers the column.

That is, the column hover area should be thicker as the plotOptions.column.pointWidth increases.

#### Actual behaviour
The tooltip contains the column value only when the user hovers the (potentially very narrow) area that corresponds to the data point of the higher density series.

#### Live demo with steps to reproduce
https://jsfiddle.net/d9tkab16/9/

1. Hover the blue column on point 161
2. The tooltip will contain "Series 1" only when you hover the area that corresponds to 161 for "Series 2", instead of also containing it whenever you hover the area of the column.

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Thanks for writing. This is how a shared tooltip is supposed to work, it only looks at the X axis and what points lie at the same X value. You probably want to use a non-shared tooltip: https://jsfiddle.net/d9tkab16/16/.
