### ISSUE TITLE
Treemap's legend cannot restore its original color  when click again

### ISSUE THREAD

**Issue by jimczj** [highcharts/highcharts#6399]
#### Expected behaviour
When click the legend again, the legend can restore its original color.
![image](https://cloud.githubusercontent.com/assets/13499146/23222862/2e160c96-f964-11e6-9c26-9a4e456dc89a.png)

#### Actual behaviour
legend cannot restore its original color
![image](https://cloud.githubusercontent.com/assets/13499146/23222816/0ef5e188-f964-11e6-849a-22fa1ff2e9f9.png)

#### Live demo with steps to reproduce

http://jsfiddle.net/jimczj/egegw6mv/1/

#### Affected browser(s)

chrome 54.0.2840.98 (64-bit)

**Comment by jon-a-nygaard** [comment]
@jimczj Thanks for reporting, the issue should be fixed in the upcoming maintenance release 5.0.8.
