### ISSUE TITLE
Floating navigator labels appear in image export if you update the navigator's options

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/highcharts#6400]
[JsFiddle](https://jsfiddle.net/lanimelrok/sdypn1Lc/)

1. Create a Highstock chart.
2. Update navigator's options. You can do this in the [JsFiddle](https://jsfiddle.net/lanimelrok/sdypn1Lc/)
 by just clicking on the "Update navigator range" button.
3. Export chart as an image (any format)

Result:
Floating labels appear in the exported image. 
![2017-02-22_1518](https://cloud.githubusercontent.com/assets/24845394/23237447/4a2a0c68-f912-11e6-8495-2dd816309464.png)

This is due to 2 navigators being drawn in the exported chart. This is caused by an extra xAxis object getting added to the original chart's options when you call `update()` on the navigator. When a chart copy is created for the export process, on top of the default navigator that gets created, it also creates an additional navigator due to the extra xAxis in the original chart's options. 

My workaround for this is to delete the created xAxis object from the chart's options once the update is complete, before you export the chart. [Fixed JSFiddle](https://jsfiddle.net/lanimelrok/d4sju40r/)

Note: `setExtremes()` does not work for the navigator which is why I'm using `update()` to set the range. Either way, this bug will occur if you update ANY of the navigator's options.

**Comment by pawelfus** [comment]
Hi @LaniMoo 

Thank you for reporting this bug. And for the workaround too!

For updating navigator's xAxis I would use `chart.update()`, demo: https://jsfiddle.net/hyd9ookg/

**Comment by pawelfus** [comment]
Fixed since v6.0.2: https://jsfiddle.net/BlackLabel/sdypn1Lc/7/
