### ISSUE TITLE
point.states does not work in maps

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#6401]
#### Actual behaviour
Setting `point.states.hover.color` has no effect on a hovered point.

#### Live demo with steps to reproduce
http://jsfiddle.net/z2q5jvmn/2/

1. Hover over the point - color should be red according to the options

It stopped working in Highmaps 5, works correctly in Highmaps 4
http://jsfiddle.net/z2q5jvmn/3/

**Comment by pawelfus** [comment]
*Internal note:*
It looks like an issue with column states (map series uses column prototype for states), demo: http://jsfiddle.net/5Le0h0d9/
