### ISSUE TITLE
Treeamap option ignoreHiddenPoint default is undefined

### ISSUE THREAD

**Issue by jimczj** [highcharts/highcharts#6402]
#### Expected behaviour
When you do not set ignoreHiddenPoint value in options, Treeamap ignoreHiddenPoint default option is true.
Before click.
![image](https://cloud.githubusercontent.com/assets/13499146/23245688/7193fc3e-f9c9-11e6-813b-ad3f8fc34b85.png)
After click
![image](https://cloud.githubusercontent.com/assets/13499146/23245732/d279e946-f9c9-11e6-8f35-b7326ee11b7f.png)

#### Actual behaviour
When you do not set ignoreHiddenPoint value in options, Treeamap ignoreHiddenPoint default option is undefined.
![image](https://cloud.githubusercontent.com/assets/13499146/23245697/8301bbfa-f9c9-11e6-9314-4cdb6409de75.png)
#### Live demo with steps to reproduce

http://jsfiddle.net/jimczj/egegw6mv/1/

you can change the options to  
`series: [{
			type: "treemap",
			ignoreHiddenPoint: true,
			data: [{
				name: 'A',
				value: 1
			}, {
				name: 'B',
				value: 2
			}, {
				name: 'C',
				value: 3
			}, {
				name: 'Causes Exception',
				value: 4
			}]
		}],
`
it performs expected behaviour,but actually in [doc](http://api.highcharts.com/highcharts/plotOptions.pie.ignoreHiddenPoint),ignoreHiddenPoint defaults to true.
#### Affected browser(s)

chrome 54.0.2840.98 (64-bit)

**Comment by jon-a-nygaard** [comment]
@jimczj Thanks for reporting, in the upcoming maintenance release (5.0.8) ignoreHiddenPoint will default to true in Treemap.
