### ISSUE TITLE
plotBands labels are not aligned correctly in gauge chart

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#6406]
#### Expected behaviour
On gauge chart it should be possible to position plotBand labels in the middle of plotBands.

#### Actual behaviour
Labels are positioned incorrectly and it is hard to see which label is related to which plotBand.

#### Live demo with steps to reproduce
https://jsfiddle.net/2q39nkcn/4/

This issue may be connected with: https://github.com/highcharts/highcharts/issues/6270

**Comment by Izothep** [comment]
As a workaround it is possible to wrap PlotLineOrBand.prototype.renderLabel method: 
https://jsfiddle.net/2q39nkcn/6/

**Comment by onexdata** [comment]
Any plans on fixing this? This seems kinda serious... can't really label plot bands in a gauge while this bug remains...

**Comment by pevans360** [comment]
Same problem.  Tried using an Annotation as a workaround.  Can't get that to work on a Gauge either.

**Comment by sebastianbochan** [comment]
Hi @pevans360,
As a limited workaround you can use [renderer.text](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#text) and add custom text.

Simplified demo:
- https://jsfiddle.net/BlackLabel/p6txznm9/

**Comment by pevans360** [comment]
Thanks Sebastian.  As it turned out, I had a margin set that was interfering with the label display.  Maybe others will have the same issue.

**Comment by khlieng** [comment]
Fixed since 7.1.0 (https://github.com/highcharts/highcharts/commit/e058c0a16e5945fa0bc78ab1db7a8c7768b096f7, wrong issue number)
