### ISSUE TITLE
Y Axis is totally wrong for the Stacked Area Chart

### ISSUE THREAD

**Issue by AndreaFernandez256** [highcharts/highcharts#6407]
I'm new to highcharts, so I'm in no way an expert, but I find this to be a bug beacuse there is no way this Y axis seems to make sense given those series values, and I haven't find a workaround to fix this. Has anyone had the same problem and managed to fix this? This example I got from the very demo from highcharts.com

#### Expected behaviour
The Y axis values should match the series values

#### Actual behaviour
The Y axis values do not match at all the series values

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/area-stacked/

**Comment by pawelfus** [comment]
Hi @AndreaFernandez256 

Thanks for contacting us. Could you describe what exactly is wrong? For example points at x=2050, have values: 5268, 1766, 628, 1201, 46, so sum is 8909. And this is where the last point (Asia) is displayed on yAxis. 

Just to be on the same page, [here](http://www.highcharts.com/docs/advanced-chart-features/stacking-charts) you can find description how stacking works.

**Comment by AndreaFernandez256** [comment]
I'm sorry, @pawelfus I didn't know that would be expected behaviour. I thought the points should be desplayed in the y axis to the same value, not that they should be added up. Thank you for telling me that.
