### ISSUE TITLE
Hide non-visible series on export only

### ISSUE THREAD

**Issue by hjnilsson** [highcharts/highcharts#6411]
#### Expected behaviour
I wish to remove the non-visible from the legend upon export, because they are not very useful on print. I want to achieve this by setting `showInLegend = false;` before calling `exportChart`.

#### Actual behaviour
The `showInLegend` setting is ignored, and all lines are included in the export.

#### Live demo with steps to reproduce
http://jsfiddle.net/rpq4qkd9/6/

Randomly visible lines on the chart, on export, I wish the non-visible lines to be hidden from the legend, and I do this when clicking on the custom 'Save' button. But setting showInLegend = false; before the export has no effect on the saved PNG.

**Comment by pawelfus** [comment]
Hi @hjnilsson 

You can change this by setting `userOptions.showInLegend`, not `options.showInLegend`, demo: http://jsfiddle.net/rpq4qkd9/7/

**Comment by hjnilsson** [comment]
Ah, thank you. That resolved the issue.
