### ISSUE TITLE
Export chart to a string instead of downloading it

### ISSUE THREAD

**Issue by suuuunto** [highcharts/highcharts#6413]
#### Expected behaviour
I would like to pass the chart.exportChart() to a string like this

`let pngchart = chart.exportChart();`

instead of start a download. This way I can work with the file and add it to a pdf with some other data in it.

#### Actual behaviour
function exportChart() starts a download and is not able to return data to a string or object.

Many thanks,
suuuunto

**Comment by pawelfus** [comment]
Hi @suuuunto 

I think you want to use [`chart.getSVG()`](http://api.highcharts.com/highcharts/Chart.getSVG). 

If you have questions, please contact with us by email or create a topic on our forum. We use github issues as bug reports.

Thanks!
Paweł
