### ISSUE TITLE
tooltip issue when use point placement and point padding.

### ISSUE THREAD

**Issue by chiragsatapara** [highcharts/highcharts#6416]
I fetch the tooltip issue when i use two y axis , in one y axis i have 3 column chart and in second y axis i have 2 line chart.

I am using ..

tooltip: {
            shared: true
        }

here i attach you the two image of the issues.

For first point tooltip is display so far.

![h1](https://cloud.githubusercontent.com/assets/8191874/23351448/3796bee2-fce7-11e6-92e3-26ef5d831bd7.png)

I am using a shared tooltip , why it is take personal tooltip?

![h2](https://cloud.githubusercontent.com/assets/8191874/23351447/37947a24-fce7-11e6-9a35-e35f09e34e61.png)

Why shadow is move into the 'Feb-2017' .  ?

![h3](https://cloud.githubusercontent.com/assets/8191874/23351461/56af7f12-fce7-11e6-8ba3-6a74713da096.png)

Can you please help me to solve this issues ASAP.

**Comment by pawelfus** [comment]
Hi @chiragsatapara 

Could you recreate issue in jsFiddle? Thanks!

Paweł

**Comment by chiragsatapara** [comment]
Hi @pawelfus , 

You can see this issue on this jsfiddle link: [Click here](https://jsfiddle.net/f3h8c88t/2/)

**Comment by pawelfus** [comment]
Hi @chiragsatapara 

Thank you for the demo! Let me change the label.

*Internal note:*
Minified demo: https://jsfiddle.net/f3h8c88t/3/

**Comment by TorsteinHonsi** [comment]
The problem seems to be that the `tooltipPos`, which is only attended for pie charts, is taken into account for columns too: https://github.com/highcharts/highcharts/blob/v5.0.9/js/parts/Tooltip.js#L281.

When guarding this line, for example by checking `if (this.shared)`, we get another problem where the tooltips only show in the right when the pointer is directly above the columns. That may be related to a similar regression in v5.0.9 @jon-a-nygaard .

**Comment by chiragsatapara** [comment]
Hello @TorsteinHonsi , @pawelfus 

I don't get your answer ,  and the solution . Can you please help me out for the solution.

**Comment by pawelfus** [comment]
**Workaround:**

Modify `tooltipPos` for column series, code:

```javascript
(function(H) {
  H.wrap(H.seriesTypes.column.prototype, 'drawPoints', function(proceed) {
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));

    H.each(this.points, function(point) {
      point.tooltipPos = point.tooltipPos.slice(0, 2);
    });
  });
})(Highcharts);
```
Demo: https://jsfiddle.net/qejqruck/

**Comment by chiragsatapara** [comment]
Hello @pawelfus ,

It's work . thank you.

**Comment by pawelfus** [comment]
Thanks for the confirmation. Let's keep this ticket open.
