### ISSUE TITLE
Wrong encoding of Chinese characters in client side PDF export

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6417]
#### Expected behaviour
After exporting to PDF, chart in PDF should look similar to chart on the screen.

#### Actual behaviour
After exporting to PDF, chart in PDF has different characters (all Chinese characters displays wrong)

#### Live demo with steps to reproduce
http://jsfiddle.net/c6oqx5sg/

Original:
![screen shot 2017-02-27 at 17 14 56](https://cloud.githubusercontent.com/assets/19593179/23369212/e3a66308-fd10-11e6-8110-57572315060d.png)

In exported PDF:
![screen shot 2017-02-27 at 17 14 45](https://cloud.githubusercontent.com/assets/19593179/23369260/07adc4ee-fd11-11e6-8560-bdb84c5a9ac5.png)

#### Affected browser(s)
Chrome, Firefox (checked)

**Comment by binarudani** [comment]
I have same issue, HighChart using "jspdf" for "localexport", and jspdf not supporting Chinese character,
please provide alternate solution for Local exporting,I need very urgent solution for it..

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, I have passed this on to svg2pdf to see if they can help.

**Comment by sebastianbochan** [comment]
+1

Extra demo:
- http://jsfiddle.net/1fq1cpg3/

Workaround:
Set the useHTML flag for the title.

**Comment by oysteinmoseng** [comment]
PNG/JPEG works for me even without `useHTML`.

For PDF, [here is a workaround](http://jsfiddle.net/c6oqx5sg/2/) to use online export instead. This seems to be the only working option at this time.

**Comment by crapthings** [comment]
hello it looks both jsPDF and svg2pdf support custom font

https://github.com/MrRio/jsPDF#use-of-utf-8--ttf
https://github.com/yWorks/svg2pdf.js/tree/master#concerning-custom-fonts

but how to pass option to highcharts?

**Comment by pawelfus** [comment]
Thanks for the heads up! It seems we need to update dependancies in the module, current versions of jsPDF&svg2pdf work fine: http://jsfiddle.net/BlackLabel/7k0vmjef/ 

**How to fix in project:**
1. install [`yWorks/jsPDF`](https://github.com/yWorks/jsPDF) (not [`MrRio/jsPDF`](https://github.com/MrRio/jsPDF) !)
2. install [`yWorks/svg2pdf.js`](https://github.com/yWorks/svg2pdf.js)
3.  
- change [`exporting.lubURL`](https://api.highcharts.com/highcharts/exporting.libURL) to your server paths or:
 - alternatively load `jsPDF` and `svg2pdf.js` before loading `exporting-offline.js` module (see demo above for an example)
4. done, try exporting now

**Comment by vanlinh3006** [comment]
> Thanks for the heads up! It seems we need to update dependancies in the module, current versions of jsPDF&svg2pdf work fine: http://jsfiddle.net/BlackLabel/7k0vmjef/
> 
> **How to fix in project:**
> 
> 1. install [`yWorks/jsPDF`](https://github.com/yWorks/jsPDF) (not [`MrRio/jsPDF`](https://github.com/MrRio/jsPDF) !)
> 2. install [`yWorks/svg2pdf.js`](https://github.com/yWorks/svg2pdf.js)
> 
> * change [`exporting.lubURL`](https://api.highcharts.com/highcharts/exporting.libURL) to your server paths or:
> * alternatively load `jsPDF` and `svg2pdf.js` before loading `exporting-offline.js` module (see demo above for an example)
> 
> 1. done, try exporting now

it work with export png but not work with export pdf

**Comment by pawelfus** [comment]
Thanks for pointing this out. Which version of jsPDF and svg2pdf did you try in your project? jsPDF v2.0.2 and svg2pdf v1.3.4 seems to be broken now (which is strange). Did you try latest versions of these packages (v2.1 and v1.5)?

**Comment by WizardCM** [comment]
I can confirm jspdf-yworks 2.1.1 and svg2pdf.js 1.5.0 (the latest versions) **do not fix** the issue for offline PDFs. This is with Highcharts 8.0.0.

**Comment by Jollyfant** [comment]
Wow this is a headache! But I got unicode export working by modifying this code in the `downloadPDF` function in `offline-exporting.src.js`: 

    el.style['font-family'] = (
        el.style['font-family'] &&
        el.style['font-family'].split(' ').splice(-1)
    );

This part of the code doesn't sit well with the font `Lucida Sans Unicode`, because of the spaces in the font name maybe? Therefore, I am hardcoding and replacing the `font-family` with:

    el.style['font-family'] = "l_10646";

Where `l_10646` is the name of the `Lucida Sans Unicode` font that was made and loaded with the custom `jspdf-yworks` fontConverter tool (because default fonts do not supported Unicode). This can be done for `normal`, `bold`, and `italic` if needed:

    (function (jsPDFAPI) {
        var callAddFont = function () {
            var font = **truncated**
            this.addFileToVFS('l_10646-normal.ttf', font);
            this.addFont('l_10646-normal.ttf', 'l_10646', 'normal');
        };
        jsPDFAPI.events.push(['addFonts', callAddFont])
    })(jsPDF.API);

The base64 encoded font variable is truncated for clarity. See the jspdf-yworks repo for details. For the above function call to work you need to load `svg2pdf` and `jspdf` manually before loading Highcharts offline exporting like in the example of @pawelfus. I tried renaming the font `l_10646` to `Lucida Sans Unicode` but that doesn't sit well with `jsPDF`..

Perhaps a consideration is for Highcharts local exporting to include the `Lucida Sans Unicode` font by default (above snippet)? Otherwise everyone will have this problem since `jsPDF` does not support Unicode fonts out of the box.

**Comment by roychowdhuryrohit-dev** [comment]
@Jollyfant Any idea how to get Google's Varela Round font working with the offline export module. I've mentioned it in the header and the font seems to work fine in the graph. But during offline export, the engine isn't able to render the font properly.

**Comment by saurabh47** [comment]
@Jollyfant Please can you share the your working example on jsfiddle ?
it will very helpful.

**Comment by magistr4815** [comment]
@TorsteinHonsi  Do I understand correctly that there is no normal solution yet, how to fix local PDFs with Russian or Chinese characters?
This looks like a bug that charting designers need to fix!

**Comment by TorsteinHonsi** [comment]
@magistr4815 We want to get this working now. Apparently what we need to do is to upgrade to the newest versions of jsPDF and svg2pdf, then provide an API endpoint for implementers to use their own font code file.

Here's how I think we should proceed
* Upgrade the internal releases of jsPDF and svg2pdf
* Add a new option, `exporting.pdfFontURL`. When this is set, the external script-loading block for PDF is modified to also load the user-defined PDF font that is created from [jsPDF's online font converter tool](https://rawgit.com/MrRio/jsPDF/master/fontconverter/fontconverter.html). Note that we don't want to embed this font by default, as it would drastically increase the bundle size, and most users don't need it. 
* Create a sample font file that is added to `samples/data`. Create a sample to show implementers how to use the new option. In addition to loading the font file, users must supply the font family option.
```js
exporting: {
        chartOptions: { 
            chart: {
            	style: {
                	   fontFamily: 'ArialHB'
                }
            }
        },
        pdfFontURL: 'https://utils.highcharts.local/samples/data/ArialHB-normal.js'
    },
```
