### ISSUE TITLE
Crosshairs act weird with multiple axis

### ISSUE THREAD

**Issue by lorgan3** [highcharts/highcharts#6420]
#### Expected behaviour
Only one crosshair is visible at a time and it follows the cursor.

#### Actual behaviour
By first hovering over 1 series and then hovering over the second series you get 2 crosshairs and 1 doesn't move.

#### Live demo with steps to reproduce
http://jsfiddle.net/6enah4d8/

1) Move the cursor in the chart from the top so you start hovering over the blue line.
2) Move the cursor further down so you're hovering over the black line.
3) Now move the cursor horizontally to a different point on the x-axis, you will see 2 crosshairs and only one responds to mouse movement.

I also tried using this option which gave the same result: http://api.highcharts.com/highcharts/tooltip.crosshairs

#### Affected browser(s)
Doesn't seem to be browser related but tested on Chrome 57.0.2987.74 beta (64-bit)

**Comment by KacperMadej** [comment]
*Workaround:*

Use this wrapper:

```
(function(H) {
  H.wrap(H.Axis.prototype, 'drawCrosshair', function(proceed) {
    // proceed
    proceed.apply(this, [].slice.call(arguments, 1));

    var axis = this;
    if (axis.isXAxis) {
      H.each(axis.chart.xAxis, function(ax) {
        if (ax.isXAxis && ax !== axis) {
          ax.hideCrosshair(); // leave only one xAxis crosshair
        }
      });
    }
  });
}(Highcharts))
```
Demo: http://jsfiddle.net/6enah4d8/1/
