### ISSUE TITLE
Cannot read property 'normalize' of undefined when overwriting chart with multiple y axis with scrollbars

### ISSUE THREAD

**Issue by samidabeast** [highcharts/highcharts#6421]
I have a highchart with multiple y axis with scrollbars on them. When I update the chart, I start getting 'Cannot read property 'normalize' of undefined at HTMLDocument.a.mouseMoveHandler (highstock.js:434)

#### Live demo with steps to reproduce
This is a rough JS Fiddle that I pieced together from a demo to reproduce the error. In my actual code I am calling chart.destroy() but that does not help the issue.
[http://jsfiddle.net/8EmeV/47/](http://jsfiddle.net/8EmeV/47/)

#### Affected browser(s)
Chrome and IE

**Comment by pawelfus** [comment]
Thank you for the report. It's broken since 5.0.0, working demo: http://jsfiddle.net/8EmeV/49/
