### ISSUE TITLE
Highstock: dynamically added axes have wrong index property in relation to chart.options array

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6423]
#### Behaviour
When yAxes are added after chart is created: wrong axis is being updated on axis.update() and might cause a fail when trying to export.

#### Live demo with steps to reproduce
http://jsfiddle.net/6cgsf550/

1. Press the button
2. Two yAxes will be added and a series using second of them.
3. In chart.options index property of the axes are not the same as indexes of elements in the array.
4. This fails [here in axis.update() code](https://github.com/highcharts/highcharts/blob/040ac8a3fe099173b5b1062db746a81ee8fe21d3/js/parts/Dynamics.js#L649).
5. On update wrong axis is being updated and exporting fails to find id for the series axis - throws error.

**Comment by Newan** [comment]
+1

**Comment by pawelfus** [comment]
Another test case: http://jsfiddle.net/BlackLabel/19c93jv2/23/

Updating initialized axis is fine, but when we add axis by `addAxis()`, updating duplicates options in `userOptions`.
