### ISSUE TITLE
the conf storke-linecap is not work in chart.arc

### ISSUE THREAD

**Issue by kospot** [highcharts/highcharts#6428]
### Expected behaviour
draw a arc with round border

#### Actual behaviour
the border is not round

the arc method has not provid the conf for path open or not

#### Live demo with steps to reproduce
https://jsfiddle.net/miniwa/6qm72hL8/

**Comment by kospot** [comment]
stroke-linecap not work

**Comment by pawelfus** [comment]
Hi @kospot 

We don't have `options` param in the [`arc`](http://api.highcharts.com/highmaps/Renderer.arc) method: 

> arc (Number centerX, Number centerY, Number outerRadius, Number innerRadius, Number start, Number end)

Using `Renderer.symbol()` (internal API) we can achieve this:
```javascript
chart.symbol('arc', 200, 150, 85, 85, {
  open: true,
  innerR: 85,
  start: -Math.PI / 2,
  end: 0
}).attr({
  stroke: '#ff1f1f',
  'stroke-width': 30,
  'stroke-linecap': 'round'
}).add();
```
Demo: http://jsfiddle.net/6qm72hL8/1/
