### ISSUE TITLE
Marker symbol is ignored in point options of bubble series

### ISSUE THREAD

**Issue by hon2a** [highcharts/highcharts#6429]
#### Expected behaviour

Marker symbol can be set separately for each point of a bubble series, just like it's possible in scatter series.

#### Actual behaviour

Marker symbol in point options is ignored for bubble series and all points get the symbol from series options (or other options up the chain or the default).

#### Live demo with steps to reproduce

http://jsfiddle.net/hon2a/Letaa7a4/ (shows comparison with scatter series)

#### Affected browser(s)

All

**Comment by TorsteinHonsi** [comment]
This is already fixed in the master, and will be released with v5.0.8, hopefully this week.
