### ISSUE TITLE
Sharp corners in areasplinerange in polar

### ISSUE THREAD

**Issue by Mylogin-info** [highcharts/highcharts#6430]
#### Expected behaviour
Draw round corners

#### Actual behaviour
Some corners are round some not. The sharp corners look inverted or turned inside out.

#### Live demo with steps to reproduce
http://jsfiddle.net/v1wz50L7/1/

#### Affected browser(s)
All browsers

![image](https://cloud.githubusercontent.com/assets/16088627/23553321/931dda5c-0020-11e7-8f0b-754909142f05.png)

**Comment by TorsteinHonsi** [comment]
A simple area spline also has similar problems. This configuration should be expected to draw something as close as possible to a circle: http://jsfiddle.net/v1wz50L7/2/
