### ISSUE TITLE
crosshair click extending "H.wrap" handler returns wrong index on stacked bar chart

### ISSUE THREAD

**Issue by yashhy** [highcharts/highcharts#6431]
#### Expected behaviour

I'm trying to have a click handler on the crosshair and I followed this [issue's comment ](https://github.com/highcharts/highcharts/issues/6015#issuecomment-262741978)to override this functionality and I kinda achieved it in this [fiddle](http://jsfiddle.net/yashhy/8bedzxm5/2/).

The fiddle works fine and returns me the index in `clickOnCrosshair` callback.

#### Actual behaviour
However if I change the chart type to stacked bar, index returned is always the first crosshair clicked, unless focused out from the chart and clicked back again where it returns the expected index first time. Regardless of what type the chart is, index of the `clickOnCrosshair` should always be the same.

#### Steps to reproduce

1. Index works fine on override [fiddle](http://jsfiddle.net/yashhy/8bedzxm5/2/).
2. Wrong index returned on stacked bar chart [fiddle](http://jsfiddle.net/yashhy/8bedzxm5/). 
    - Click on a column observe the index in console, move to next column clicking will give the same index as before.
    - Click on a column observe the index in console, focus out from the chart and click back again the index is returned correctly.

#### Affected browser(s)

MacOS Sierra
Chrome : Version 56.0.2924.87 (64-bit)

Windows7
Chrome: Version 45.0.2454.99 m (64-bit)

**Comment by pawelfus** [comment]
Hi @yashhy 

Thank you for reporting this issue! It should be resolved once one of our dev branches will be merged into the master: http://jsfiddle.net/8bedzxm5/3/ We should be able to release this as part of 5.0.8.

FYI @jon-a-nygaard

**Comment by yashhy** [comment]
@pawelfus thanks for your comment, may I know when is the realese 5.0.8 planned?

**Comment by pawelfus** [comment]
v5.0.8 should be released within a week or two.

**Comment by yashhy** [comment]
@pawelfus I see the new release v5.0.9, but did it broke the crosshair (color) hovering on bar chart? Initially when this bug was opened, I was able to hover the bar chart without moving out of the chart container, but now it seems to be broken.

The crosshair color hover happens only if we are within the bar chart area and move to the next bar, if you try to move your mouse around the chart without hovering the bar chart area, the crosshair color doesn't change at all. Here the [fiddle](https://jsfiddle.net/yashhy/8bedzxm5/4/) with version v5.0.9

**Comment by TorsteinHonsi** [comment]
The last problem is probably the same as #6456.

**Comment by yashhy** [comment]
Based on this [comment](https://github.com/highcharts/highcharts/issues/6456#issuecomment-286757030) updating the [fiddle](https://jsfiddle.net/8bedzxm5/5/) for workaround.
