### ISSUE TITLE
setExtreme animation glitch with many categories

### ISSUE THREAD

**Issue by Rahza** [highcharts/highcharts#6432]
I have a chart with many categories and wanted to use the x axis min/max properties to only display only a couple of categories at a time and allow the user to scroll the chart with two buttons.

#### Expected behaviour
Smooth animation: http://jsfiddle.net/qvm0ba48/
Click left/right button to scroll

#### Actual behaviour
With many categories, the same chart will have a glitched animation when clicking the scroll buttons:
http://jsfiddle.net/zu5qejfd/

#### Affected browser(s)
Tested in Chrome 56

**Comment by pawelfus** [comment]
Hi @Rahza 

This is caused by [`series.cropThreshold`](http://api.highcharts.com/highstock/plotOptions.column.cropThreshold). You can increase that value (e.g. 100) to get all points rendered.

Demo: http://jsfiddle.net/zu5qejfd/1/

**Comment by Rahza** [comment]
Hi @pawelfus 

Increasing cropThreshold solved the problem for charts with a few series. However, it doesn't seem to work with many series - is this intended?

Demo: http://jsfiddle.net/eyyo4rry/

**Comment by pawelfus** [comment]
Yes, that can also be changed by [`animationLimit`](http://api.highcharts.com/highcharts/plotOptions.column.animationLimit).
