### ISSUE TITLE
Highcharts: solid gauge chart yAxis update

### ISSUE THREAD

**Issue by xorsnn** [highcharts/highcharts#6433]
#### Expected behaviour
When updating yAxis using 

`
chartSpeed.yAxis[0].setTitle({          
  text: "The new titile"         
});
`

I expect dom consistency, and expect that additional unsued nodes won't appear

#### Actual behaviour

every time yAxis is updated new dom node appears:
`<g class="highcharts-plot-bands-0"></g>`
![output](https://cloud.githubusercontent.com/assets/10442030/23610965/eefa95d8-0285-11e7-8e7b-793256057693.gif)

#### Live demo with steps to reproduce
http://jsfiddle.net/xors/afq7ge9v/8/

#### Affected browser(s)
google chrom  56.0.2924.87 (64-bit)

**Comment by pawelfus** [comment]
Hi @xorsnn 

Thank your for reporting this issue.

*Internal note:*
It can be caused by pane's background, when disabled it works fine: http://jsfiddle.net/afq7ge9v/9/

**Comment by pawelfus** [comment]
*Internal note:*
There are two commits to add test, but only the second one is correct. Reverting went wrong..
