### ISSUE TITLE
Point.update() causing error #15

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6434]
#### Behaviour
Updating a point in Highstock chart causing error 15 (http://www.highcharts.com/errors/15). The last version where function works fine, without the error, is 4.2.5. Probably related with: #4109.

#### Live demos
http://jsfiddle.net/d_paul/gasthney/ - v4.2.5 (works without errors)
http://jsfiddle.net/d_paul/vspxom91/ - v5.0.8 (throws an error)

**Comment by TorsteinHonsi** [comment]
It seems to be fixed.
v5.0.7 caused an error but v5.0.8 does not.

**Comment by hyalkaf** [comment]
Is doing 
```
chart.series.data[0].update(y = 100);
```
going to generate this error? I'm getting this error when I execute that line.

I'm uisng Highstock JS v6.0.1 (2017-10-05)

**Comment by pawelfus** [comment]
Hi @hyalkaf 

It depends, if you are using `dataGrouping`, then see #4109 issue. If it's not a grouped point, then could you recreate issue in jsFiddle?
