### ISSUE TITLE
Js Fiddle Extended Heatmap Broken

### ISSUE THREAD

**Issue by mckrti** [highcharts/highcharts#6435]
#### Expected behaviour
I expect to see a heatmap appear in the JS fiddle

#### Actual behaviour
No heat map appears

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/heatmap-canvas/

#### Affected browser(s)
Firefox, Chrome

I even copied to code locally, but no heat map shows.

**Comment by TorsteinHonsi** [comment]
Sorry for that, it will work again once we release v5.0.8 (any day now). Until then, please use the setup from the zip package.

**Comment by jon-a-nygaard** [comment]
Considered fixed as of 5.0.8.
