### ISSUE TITLE
sass !default for configurable variables

### ISSUE THREAD

**Issue by alifr** [highcharts/highcharts#6436]
#### Expected behaviour
The variables in the  [``highcharts/css/highcharts.scss``](https://github.com/highcharts/highcharts/blob/master/css/highcharts.scss) should have the ``!default`` flag. Then we could import the scss file into our project and override the theme styles without having to duplicate the entire file. 

#### Example
```
@import 'https://code.highcharts.com/5/css/highcharts.css';

$colors: #40bfa2 #984e9b #fb7830 #01acc8 #CDAED1 #82368C #AAAEB2 #565E65 #EF92A5 #DF264C #565E65 #A8E9F3 #FFBA9D #FF763B #95FEDB #27CAE1;

```

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestion!

We had a pull request for this, a couple of months back, but it broke our build system because the SASS variables are also inserted directly into the generated source code. So we'll have to fix that first.
