### ISSUE TITLE
Updating pane dynamically does not have any effect

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#6438]
#### Expected behaviour
Using `chart.update({ pane })`, the pane should be updated according the new options.

#### Actual behaviour
Updating pane does not have any impact on the chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/0xL048um/
1. Click on change start angle - the new angle is not applied

### Possible workaround
Remove the pane from `chart.panes` and update the axes
http://jsfiddle.net/0xL048um/2/

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! The pane options currently are passed on to Axis objects, and pane backgrounds are axis plot bands. This architecture hasn't proved very stable, and possibly we should create more standalone Pane objects.
