### ISSUE TITLE
Chart rendering on safari is showing weird lines.

### ISSUE THREAD

**Issue by sachin-dimble** [highcharts/highcharts#6439]
#### Expected behaviour
Chart should rendred cleanly/consistently across browsers chrome and safari.
Tried Highcharts version 4.2.6 and latest 5.0.7.

#### Actual behaviour
Chart on safari is showing weird small horizontal garbage lines (plot points) where as rendering in chrome is clean and neat.  

#### Live demo with steps to reproduce

https://jsfiddle.net/sachin4715/177xtowj/2/

#### Affected browser(s)

Safari.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting. I can't explain the horizontal lines, other than it may be some browser-specific rending issue. But it clearly comes from the fact that the points are very dense in this area. As a workaround I would suggest using a line series instead, which also better communicates the varying density of the data: https://jsfiddle.net/177xtowj/3/

**Comment by sachin-dimble** [comment]
Thanks @TorsteinHonsi , Ok, I will go with workaround.
