### ISSUE TITLE
Scroll issue in touch devices with 4.2.7

### ISSUE THREAD

**Issue by xavadu** [highcharts/highcharts#6442]
Hi, 
Before all, I think that 5.0.0 solve it be we don't have licence yet.. we have licence for v4. 

We tried with options like `panning: false;` and `tooltip.followTouchMove: true;` and trying to `disabled  touch events` for the graph but nothing working, the only workaround would be to put an overlay over the graph and this is not a good solution.

#### Expected behaviour
Touch on the graph and can scroll the page.

#### Actual behaviour
Touch in the graph, but the page it is not scrolled, instead the graph try to panning right or left, but without load any data, the effect is like a bounce when the touch is release 

It make the site unusable, specially the part under the graph.

#### Live demo with steps to reproduce
The cursor doesn't appear in the gif, but at begining it scroll the page if the touch is outside the graph, when the touch is inside the graph the page can't be scrolled and instead the graph have like a kind of bounce-panning to the right and left (then touch is release the graph back to be 'centered')

![img](http://i.imgur.com/YU0JV2W.gif)

also you can see it directly in [our pag](https://currency-converter.net)

Thanks.

##### Update
The bounce effect and the possibility to scroll work fine for Safari in iPhone if is `zoom: 'none';` is defined, but in Android with Chrome it throw error `Uncaught TypeError: Cannot read property 'chartX' of undefined(…)`

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, but if it is fixed in the latest release then I can only suggest you update to the latest version.

**Comment by xavadu** [comment]
Hello,
Yes it is what we finally do, but to be honest, a bit expensive to only fix a bug.

BTW, on v5 it is also not working totally fine. It is for the graph, but not for the navigator. 

Cheers.
