### ISSUE TITLE
inverted waterfall chart label position 

### ISSUE THREAD

**Issue by theDeliverer** [highcharts/highcharts#6447]
recently we've updated from 4.2.6 to the most recent version of high charts, and there has been some issues with the inverted waterfall chart. The axis seems to be in the reverse order when `yAxis.reverse` is set to `true`. This also seems to be causing an issue with the way the labels are being positioned.  

#### Expected behaviour
http://jsfiddle.net/jqLad586/5/

using a older version of of high charts (4.2.6), when `chart.inverted` = `true`, I can position the labels outside and to the right (where possible). This format is quite readable and is preferred by our users. 

#### Actual behaviour
http://jsfiddle.net/dpk4f27e/
this is the latest version, as you can see the labels are no longer aligned to the right, outside of the bars regardless of what value `dataLabels.align` is set to. in this example I have also had to set `yAxis.reverse` to `true` as the latest version seems to reverse the axis if `chart.inverted` = `true`.

also the chart axis ticks seem to be in the reverse order. My guess is that the positioning of the labels is related to the order in which the x-axis is being displayed. 

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Thank you for reporting about the problem.

This is duplicate for #5911 
http://jsfiddle.net/t2Lha3at/12/
`chart.inverted: true, xAxis.reversed: true, yAxis.reversed: false`
