### ISSUE TITLE
Tooltips on scatter cannot be shown when there is a line behind it (breaks on version 5.0.8)(works on 5.0.7)

### ISSUE THREAD

**Issue by tangyouze** [highcharts/highcharts#6449]
In highstock 5.0.7 when I create a figure with following series, I can see the tooltips on the scatter(black tooltips).
![image](https://cloud.githubusercontent.com/assets/815306/23779334/dcfcfb3a-057a-11e7-912f-b1a711b45af4.png) 
However this tooltip is missing when highstock upgrade to 5.0.8

```
        series: [{
            name: 'AAPL',
            data: data,
            zindex: 1,
            tooltip: {
                valueDecimals: 3
            }
        },
        {
            name: 'AAPL',
            type: 'scatter',
            zindex: 10,
            color: 'black',
            data: data,
            tooltip: {
                valueDecimals: 2
            }
        }
        
        ]
```
Jumping from highstock 5.0.7 to 5.0.8
The tooltips on scatter is missing(cannot be shown when mouse is around the node)

#### Expected behaviour
with version 5.0.7
http://jsfiddle.net/ao7zt82v/2/
![image](https://cloud.githubusercontent.com/assets/815306/23779334/dcfcfb3a-057a-11e7-912f-b1a711b45af4.png) 

#### Actual behaviour
with version 5.0.8
http://jsfiddle.net/92Lh0s5p/1/
![image](https://cloud.githubusercontent.com/assets/815306/23779307/aaea9ae4-057a-11e7-8f24-cf19857167ca.png)

#### Affected browser(s)

Chrome, Edge, and may be more

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

This is more general - when tooltip has `shared:true` then it is not possible to displayed tooltip for any `scatter` point.
Simple demo: http://jsfiddle.net/jjt0a5z5/

**Comment by KacperMadej** [comment]
This commit seems (tested on issue-by-commit) to be causing the issue: https://github.com/highcharts/highcharts/commit/fc77bfc

@jon-a-nygaard

**Comment by TorsteinHonsi** [comment]
Another case, scatter tooltip cannot be accessed: http://jsfiddle.net/highcharts/xgn6Lan4/5/
