### ISSUE TITLE
Series is drawed, but chart.series[n].data is an empty array (Higchstock)

### ISSUE THREAD

**Issue by NazarovTimur** [highcharts/highcharts#6450]
I implemented a function that extends series to end of chart (as example http://jsfiddle.net/jlbriggs/omtugbvo/3/), and it works very buggy... In some cases all works fine, but when a lot of data placed at chart (by deafult its zoomed out) or just in random cases (2 series with 10-20 points), I can't get any data from chart.series[n].data - it is an empty array.

I think, chart.series[n].data should be actual data array everytime.

**Comment by KacperMadej** [comment]
Hi @NazarovTimur ,

Thank you for reporting about the issue. However, please take a look at the comment for series data related arrays from highstock.src.js:

        /**
         * The base function which all other series types inherit from. The data in the series is stored
         * in various arrays.
         *
         * - First, series.options.data contains all the original config options for
         * each point whether added by options or methods like series.addPoint.
         * - Next, series.data contains those values converted to points, but in case the series data length
         * exceeds the cropThreshold, or if the data is grouped, series.data doesn't contain all the points. It
         * only contains the points that have been created on demand.
         * - Then there's series.points that contains all currently visible point objects. In case of cropping,
         * the cropped-away points are not part of this array. The series.points array starts at series.cropStart
         * compared to series.data and series.options.data. If however the series data is grouped, these can't
         * be correlated one to one.
         * - series.xData and series.processedXData contain clean x values, equivalent to series.data and series.points.
         * - series.yData and series.processedYData contain clean y values, equivalent to series.data and series.points.
         *
         * @constructor Series
         * @param {Object} chart - The chart instance.
         * @param {Object} options - The series options.
         */

The Series.data is also explained in API reference: http://api.highcharts.com/highstock/Series.data

> Read only. An array with the series' data point objects. In case the series data length exceeds the cropThreshold, or if the data is grouped, series.data doesn't contain all the points. It only contains the points that have been created on demand. In these cases, all original X and Y values can be read from series.xData and series.yData. Additionally, series.options.data contains all configuration objects for the points, whether they be numbers, arrays or objects.

If you still feel like there is a bug in here than please create a minimal, verifiable demo that will use Highstock and please provide required steps needed to recreate the problem. After that this issue will be possible to reopen.

Best Regards.

**Comment by NazarovTimur** [comment]
Thanks for your reply. It's my fault, I was too inattentive when read it. You save me :)

**Comment by Amiryy** [comment]
Hello,
I am getting this issue in Highcharts, not Highstock...
All of my series are drawn but when I try to access a specific point object to call `setState` on it I get empty `data` arrays under all series.
I couldn't find any Highcharts reference for this issue, only this one and a few more for Highstock, and my guess is that it is a different case.

Thanks.
