### ISSUE TITLE
Fix Y-Axis labels

### ISSUE THREAD

**Issue by jainabhishek14** [highcharts/highcharts#6455]
#### Expected behaviour
There are 5 categories on y-Axis according to which chart renders. I need fixed Y-axis.

#### Actual behaviour
But as the number of datapoints on x-Axis Increases. Few Categories on Y-Axis got skipped.

#### Affected browser(s)
Firefox

**Comment by pawelfus** [comment]
Hi @jainabhishek14 

Could you recreate issue in jsFiddle? Thanks!

**Comment by jainabhishek14** [comment]
Case 1: with low number of datapoints:
https://jsfiddle.net/wa6o6d5j/

Case 2: with large number of datapoints:
https://jsfiddle.net/sydu1xpr/

In Case 1 you can find 5 categories on y-Axis but in case 2 there is only 2 categories. I want to show categories of case 1 in case 2.

**Comment by pawelfus** [comment]
You can set [`tickInterval`](http://api.highcharts.com/highcharts/yAxis.tickInterval), demo for you: https://jsfiddle.net/sydu1xpr/1/ 

I see you use [`labels.step`](http://api.highcharts.com/highcharts/yAxis.labels.step) - but step allows only to decrease number of labels. It doesn't change number of ticks.

**Comment by jainabhishek14** [comment]
Oh.. Thanks @pawelfus. You saved my day!
