### ISSUE TITLE
Tooltip doesn't update after hovering above / below points (over plot area) [5.0.8+]

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6456]
#### Expected behaviour
After hovering over point on series and then hovering above or below different point, tooltip should update its position. (Works as expected in 5.0.7)

#### Actual behaviour
After hovering over point on series and then hovering above or below different point, tooltip doesn't update its position.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/intraday-candlestick/

1. Hover over one point
2. Move your mouse cursor above or below point on either right or left side
3. Notice tooltip doesn't redraw

**Comment by onmas59** [comment]
Hi Torsten,

It was me that filed this bug originally with stpoa.  I have a workaround (using 5.0.7) and wondered when you might expect to provide an official patch for 5.0.8 please?
Thanks.
Jason

**Comment by jon-a-nygaard** [comment]
Hi @onmas59
We will have this fixed by the next maintenance release, which is likely to be released in a few weeks.
In the meantime you could try out the workaround below.

**Workaround**
[Example of the workaround](http://jsfiddle.net/jon_a_nygaard/sd6b3c6n/)
Add the following snippet after loading Highcharts and before initializing the chart.
```javascript
Highcharts.wrap(Highcharts.Pointer.prototype, 'getHoverData', function (proceed, a, b, c, isDirectTouch, shared, f) {
    var directTouch = shared ? false : directTouch;
    return proceed.apply(this, [a, b, c, directTouch, shared, f]);
});

**Comment by onmas59** [comment]
Hi @jon-a-nygaard

Thanks for the update and workaround.

This fixes it for the axis used by the candle data series, but I have other axes (e.g. showing Volume, technical indicators etc.), which fail to show on the tooltip.  The workaround I'm using (going back to using 5.0.7) works fine for the moment.  I'll keep an eye out for the next release in a few weeks.

Thanks again.
Jason

**Comment by KacperMadej** [comment]
*Internal note:*

@oysteinmoseng @jon-a-nygaard 
This fix will break accessibility module.
Demo: http://jsfiddle.net/sd6b3c6n/1/
Steps:
1. click under the chart
2. press tab
3. press right arrow
4. error in the console - calling for a shared tooltip without an event

**Comment by jon-a-nygaard** [comment]
@KacperMadej See comment in #6633
