### ISSUE TITLE
Highstock Navigator slider does not work on the Google Chrome version ?

### ISSUE THREAD

**Issue by ziXet** [highcharts/highcharts#6457]
#### Expected behaviour
Navigator should slide for changing the time range.

#### Actual behaviour
It is not working on the latest(or possibly older) versions of Google Chrome. Basically, I cannot move the slider by dragging it to the left or right or expanding/shrinking the range. However, it works fine with touch screen(touch events) or Google chrome on Android. 

#### Live demo with steps to reproduce

All Highcharts demos that has navigator have this issue.

#### Affected browser(s)
Google Chrome Desktop (using mouse event) - tested on Linux and Windows

**Comment by TorsteinHonsi** [comment]
Do you see this in our official demos?

I went to http://www.highcharts.com/stock/demo/basic-line and it works fine for me. Tested with Chrome 56/Windows 10 and Chrome 56/Mac.

**Comment by ziXet** [comment]
My Chrome version was 54 and none of the examples that using navigator was working. However, I just tried Chrome 55 and 56 and it is working fine.

**Comment by ziXet** [comment]
I just updated my laptop chrome version to the latest version which is 57 and I still have the issue. My laptop screen is hidpi (retina). Would it cause this issue?

**Comment by pawelfus** [comment]
Tested http://www.highcharts.com/stock/demo/basic-line with Chrome 56 (Windows + Mac) and Chrome 57 (Windows + Mac) - both works fine for me.

**Comment by ziXet** [comment]
Did you try Retina as well?

**Comment by pawelfus** [comment]
Yes I did, sorry updated mu comment above.

**Comment by ziXet** [comment]
I just recorded a quick video. https://drive.google.com/file/d/0B9oKYsyaztjHTEN4eFRsMkFIMWs/view?usp=sharing
At the end of the demonstration, I tried to drag with the touch screen and it worked. There is no log in the console unfortunately.

**Comment by pawelfus** [comment]
Thank you for the video. 

Could you check if it used to work in 5.0.7? Demo: http://jsfiddle.net/70nk1jnf/show/

*Internal note:*
May be related to 0ef5846fac05d935f8bc13ac135631078045414a

**Comment by ziXet** [comment]
Yes. It worked! Is this the nightly version?

**Comment by pawelfus** [comment]
I am not sure what do you mean. I asked you to check 5.0.7 version (current version is 5.0.9), to confirm if it's a regression. Thanks!

**Comment by ziXet** [comment]
Sorry, my bad. I think 5.0.7 was the latest version.

**Comment by sgornick** [comment]
Just wanted to add that this issue occurs for me using Firefox 52.0 as well.   Using 5.0.7 there was no problem, so this a regression.

**Comment by jtbowden** [comment]
I also observed this on Chrome on a touch screen laptop.  It looks like the handles only get 'touchstart' handlers applied and not 'mousedown' handlers.

**Comment by barrymay** [comment]
+1 on this.  For me I'm seeing the same behavior it seems to be kind of specific:
- Using Chrome thru Citrix (or Windows 7?)
- Later Chrome 56/57 (haven't tried 55)

On MacOS and Windows 10, and IE on the same Chrome/Win7 environment, it's fine

**Comment by TorsteinHonsi** [comment]
Tested Chrome 54-57 on Windows 7 (via Browserstack), the navigator works as intended there.

**Comment by TorsteinHonsi** [comment]
See the commit above, I think the problem may be related to the fix for #6187, which is now reverted. It basically disabled mouse events on the navigator if the browser supported touch.

**Comment by barrymay** [comment]
Just tested 5.0.10, works fine now - thanks @TorsteinHonsi!! 

(quite surprised at the narrowness of that impact, but definitely fixed the issue between .9 and .10)
