### ISSUE TITLE
lines are not drawn while setting color by name when using boost module

### ISSUE THREAD

**Issue by drps** [highcharts/highcharts#6458]
#### Expected behaviour
draw all selected lines

#### Live demo with steps to reproduce
After each click on the redraw button we add one more serie but when series count become more than 9 (in test case) no more lines are drawn with color set by name

But still tooltips are working

https://jsfiddle.net/drps/m8aybekk/4/

**Comment by cvasseng** [comment]
Thanks for reporting.

I've added a fix which will get merged into master soon.

In the meantime you can work around it by using all-lowercase when referring to named colors.

**Comment by drps** [comment]
> In the meantime you can work around it by using all-lowercase when referring to named colors.

it works, thank you
