### ISSUE TITLE
Incorrect initial size of legend url-symbol

### ISSUE THREAD

**Issue by dilnara** [highcharts/highcharts#6462]
#### Expected behaviour
url-Icon in legend has the same size as at chart.

#### Actual behaviour
Icon has incorrect size at the first render, and since the 2nd render it becomes correct.

#### Live demo with steps to reproduce
http://jsfiddle.net/sy6nb7fk/1/

1. Press Run button. Sun icon in legend is small.
2. Click the Sun icon. It replaced with Cloud icon, which is small too.
3. Click the Cloud icon. Now the Sun icon is normal.
4. Click the Sun icon. Now the Cloud icon is normal.

#### Affected browser(s)
Checked in Chrome only.

**Comment by pawelfus** [comment]
It's caused by loading images without width and height. If image is not loaded (first time), then height of the image is not calculated and default size is set.

In case of using images as markers, I suggest to set `legend.symbolHeight`, demo: http://jsfiddle.net/sy6nb7fk/17/

**Comment by dilnara** [comment]
legend.symbolHeight sets height for all legend symbols, but I have one serie with a legend icon with height 2px, and for others series' icons default size 12px is ok. So I can't apply one height for all symbols. More than this, my picture has size 18x2, and if I set symbolHeight = 2, then image decreases proportionally, and I get something almost invisible, this is the case: http://jsfiddle.net/vretg7L0/

**Comment by dilnara** [comment]
Ideally, I want to have possibility to manage legend symbol (at least its size) for each data serie separately.

**Comment by pawelfus** [comment]
I think you are right, an option to set for each legend marker/symbol separate width and height would be great. At this moment `symbolWidth` and `symbolHeight` can be set only for all series at the same time. 

I created simple plugin to position properly marker icons, please take a look: http://jsfiddle.net/vL7h5pj1/ - it's not a perfect solution, distance between two legend items is not fixed.

**Comment by dilnara** [comment]
@pawelfus 
Thank you, it's much better than nothing.

By the way my current workaround is to find legend images in DOM tree after chart rendered (with querySelectorAll('g.highcharts-legend-item > image.highcharts-point')) and then call setAttribute('width', desiredWidth) on img.

Like this:
http://jsfiddle.net/vretg7L0/2/

**Comment by TorsteinHonsi** [comment]
Just for reference - it is correct behaviour that the marker symbol scales down in the legend. This is to prevent that large files, used for example in [bubble charts](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/highcharts/plotoptions/bubble-symbol/), take over the legend.
