### ISSUE TITLE
Code for SVGElement.attr missing trailing "$" in regex test when handling named symbols

### ISSUE THREAD

**Issue by matt-hoskins** [highcharts/highcharts#6463]
#### Expected behaviour
E.g. set rotation attribute on a named symbol SVGElement to a value and have that attribute change be processed.

#### Actual behaviour
Value is discarded because the attribute begins with the letter 'r' and the regex in question (line 485 in master SvgRender.js) is missing a trailing $:

```javascript
                                if (this.symbolName && /^(x|y|width|height|r|start|end|innerR|anchorX|anchorY)/.test(key)) {
					if (!hasSetSymbolSize) {
						this.symbolAttr(hash);
						hasSetSymbolSize = true;
					}
					skipAttr = true;
                                }
```
So the "r" part of the pattern would match a key of e.g. "rotation" and set skipAttr to true as there's no "$". symbolAttr will only process the attributes specifically named in the list in the regex so the attribute setting of rotation doesn't happen.

I would guess it's an accident that the trailing "$" isn't there rather than by design.

**Comment by TorsteinHonsi** [comment]
Thanks, that's a good catch! Yes I assume you're right about this.
