### ISSUE TITLE
Spider web with mulitple axis', doesn't inherit gridLineColor from theme

### ISSUE THREAD

**Issue by Quwink** [highcharts/highcharts#6464]
When yAxis or xAxis is an array, it doesn't inherit the setOptions xAxis.gridLineColor

#### Expected behaviour
xAxis and yAxis gridLineColor should inherit from theme xAxis.gridLineColor and yAxis.gridLineColor

#### Actual behaviour
gridLineColor are set back to default color

#### Live demo with steps to reproduce
Not working (both axis' is an array)
http://jsfiddle.net/y8rcsv9e/
Working (not an array)
http://jsfiddle.net/y8rcsv9e/1/

#### Affected browser(s)
Chrome

**Comment by Izothep** [comment]
+1

**Comment by pawelfus** [comment]
*Internal note:*
Related to #2439
