### ISSUE TITLE
tickPositioner conflicts with dateTime

### ISSUE THREAD

**Issue by mikecentiq** [highcharts/highcharts#6467]
When using xAxis.tickPositioner with xAxis.type = 'datetime', the labels on the xAxis are displayed as numbers rather than dates. See:

http://jsfiddle.net/oun5jmq7/

**Comment by pawelfus** [comment]
Hi @mikecentiq 

Thank you for reporting this issue. It works, when copying `info` property from original tick positions, demo: http://jsfiddle.net/oun5jmq7/2/

@TorsteinHonsi - should we add this to docs? Or is it a bug?

**Comment by mikecentiq** [comment]
Thanks for that. I know you didn't directly ask for my opinion, but I'm going to offer it anyway ;) "tickPositioner" to me sounds like an option that is only concerned with the positioning of ticks, and the usage of it should not affect the formatting. The "info" property sounds like an implementation detail that the user of the option should not need to be aware of. So I would say this is a bug.

**Comment by TorsteinHonsi** [comment]
I agree in principle, but the problem now is that the `.info` holds information about what unit name to use, for example, should we print the milliseconds, minutes, months or years. If you have yearly ticks it doesn't make sense to print seconds. This logic is handled when the tick positions are determined, so when you create your own tickPositioner it gets bypassed. It is possible to find a new unit name like we currently do with the tooltip, but it would add some complexity. So maybe we should just add this to the docs for tickPositioner...

**Comment by bansalswati2525** [comment]
getting error while setting .info
.info  doesnt exist on type any[]
