### ISSUE TITLE
autoRotation does not work with tickPositioner

### ISSUE THREAD

**Issue by mikecentiq** [highcharts/highcharts#6468]
If you use a tickPositioner to dynamically set the distance between ticks, you do not get the default autoRotation value of -45 deg. There is no rotation. You have to forcibly set it to *always* rotate or never. I feel like the autoRotation should be based on the minimal distance between two ticks returned by the tickPositioner function.

See: http://jsfiddle.net/oun5jmq7/1/

**Comment by TorsteinHonsi** [comment]
Thanks for writing! Currently the slot logic, as you say, doesn't account for uneven distances between the ticks. 

Here's a drop-in fix that seems to work, at least in this case. It looks at the translated pixel distance between the ticks: http://jsfiddle.net/oun5jmq7/4/

**Comment by mikecentiq** [comment]
Thanks for that. Seems to work. Guessing this will be included in a future version?

**Comment by VivianWeb** [comment]
Hi
My code is as below,but autoRotation doesn't work, may I know the reason?
chart: {
                type: 'column',
                animation: showAnimation
            },
            boost: {
                enabled: false
            },
            colors: ['#03A9F4', '#8BC34A', '#E91E63', '#9C27B0', '#673AB7', '#2BE0E8', '#3F51B5', '#CEDB04', '#009688', '#F8D800',
                '#FF9800', '#FF5722', '#777777', '#607D8B', '#054456', '#F44336', '#BF3126', '#795548', '#2A98C5', '#EC8B37',
                '#5BC9E8', '#7CB623', '#F5B632', '#f2f2f2', '#d9d9d9', '#bfbfbf', '#000000'
            ],
            tooltip: {},
            legend: {
                enabled: true,
            },
            plotOptions: {
                column: {
                    stacking: stackingType,
                    dataLabels: {
                        enabled: false
                    }
                }
            },

            xAxis: {
                categories: xCategories,
                labels: {
                    autoRotation: [-10, -20, -30, -40, -50, -60, -70, -80, -90]
                }
            },
            yAxis: {
                min: 0,
                title: {
                    text: yAxisText
                },
                stackLabels: {
                    enabled: true
                }
            },
            title: {
                text: ''
            },
            series,
            loading: false,
            func: (chart: any) => { //
                setTimeout(() => {
                    $('[data-toggle="tooltip"]').tooltip({ container: 'body' });
                }, 1000);
           
![image](https://user-images.githubusercontent.com/53067778/67456037-03a6c600-f662-11e9-88df-0da60a99bf95.png)
