### ISSUE TITLE
Interpolating multi-series values for a shared tooltip

### ISSUE THREAD

**Issue by mourner** [highcharts/highcharts#647]
Hi! Lets suppose I have several series on a chart with different point intervals (or data passed as [x,y] values), and enable shared tooltip for it, like this: http://jsfiddle.net/phhm9/

When you move the mouse over the chart, the tooltip flickers with values for different series. This may be OK with such a simple example, but when you have lots of points that are not consistently present at the same time for each x axis value, the tooltip becomes unusable.

Is there a way to make the tooltip show all series values in this case, e.g. by interpolating absent values between closest points, or by always choosing the closest value for each time series?

Thanks in advance!

**Comment by TorsteinHonsi** [comment]
Here's a little hack that creates a transparent series with interpolated data points and draws it on top of the data series, making the tooltip read from the interpolated series: http://jsfiddle.net/highcharts/F4e2Y/

**Comment by TorsteinHonsi** [comment]
Ref UserVoice: https://highcharts.uservoice.com/admin/forums/55896-highcharts-javascript-api/suggestions/5462529-tooltip-data-interpolation

**Comment by oysteinmoseng** [comment]
Here is a demo of using tooltip formatter to interpolate only when there are other points hovered: http://jsfiddle.net/oysteinmoseng/vcjqd4L9/

**Comment by Yovanys** [comment]
> Here is a demo of using tooltip formatter to interpolate only when there are other points hovered: http://jsfiddle.net/oysteinmoseng/vcjqd4L9/

It's been a long time and I just checking the solution from oysteinmoseng, it is very impressive, but it fails if you have more than one YAxis, how can you resolve it?
