### ISSUE TITLE
Highcharts5.0.9 bar getSVG not work with IE8

### ISSUE THREAD

**Issue by huoxuxu** [highcharts/highcharts#6470]
hello highcharts
when i use highcharts 5.0.9 with IE8，
chartType is bar
then i use getSVG method it‘s not work
error message is 缺少JScript 对象

**Comment by zhy1stgg** [comment]
+1 
I have the same issue, it's may affect from version 5.0.1

**Comment by KacperMadej** [comment]
Is this function working differently than in previous versions? I have tested the function and getSVG is working fine - it's just hard to display SVG in a browser that doesn't support it. Please provide a demo that should be used to recreate the problem.

**Comment by huoxuxu** [comment]
![123123123](https://cloud.githubusercontent.com/assets/7299484/24032540/84c06f7a-0b23-11e7-8ffc-51fb0220a599.png)

**Comment by KacperMadej** [comment]
Thank you for the image. There's a problem with exporting dataLabels. As a workaround you could avoid exporting charts with dataLabels through IE8 or use last working version - 5.0.2. I will be searching for the commit responsible for the problem.

**Comment by KacperMadej** [comment]
*Internal note:*

Responsible commit: https://github.com/highcharts/highcharts/commit/7ba29130fa445523c5bbf116ae746be654136843

IE8 throws an error: `JScript object expected` on [this line](https://github.com/highcharts/highcharts/blob/21004e7f138f09ebf94a96dbae7257fd1c6b0d56/js/parts/SvgRenderer.js#L336).
