### ISSUE TITLE
arearange  incorrect at Highcharts 5.0.9 with IE8

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#6471]
both arearange and arearange-line demo in your download examples 

#### Actual behaviour
![30](https://cloud.githubusercontent.com/assets/6829290/23930226/d9041af6-0965-11e7-9007-2d27f67a50b8.jpg)

![44](https://cloud.githubusercontent.com/assets/6829290/23930228/dbb5f224-0965-11e7-9328-6cfacd11088e.jpg)

#### Affected browser(s)

IE8

**Comment by zhy1stgg** [comment]
It's affect Highstock too.

**Comment by KacperMadej** [comment]
Thank you for reporting about the problem.

Last working version 4.2.6, so broken since 4.2.7 version of highcharts-more.
