### ISSUE TITLE
Data label text outlines in treemap chart are not properly cleaned up on reflow

### ISSUE THREAD

**Issue by hon2a** [highcharts/highcharts#6472]
I'm using charts in a context where they quite often need to `reflow()`. In treemap chart, the text outline of the data labels produces pretty weird visual artifacts. It seems to be a combination of 2 issues:

* new `tspan` nodes for the outline keep being added, but the old ones are not getting removed,
* something's wrong with how the nodes are positioned or ordered, sometimes causing more consecutive elements with just `dy` attribute (and not `y`) than there are lines of text to which the outline belongs, which then causes the superfluous outline nodes to become visible.

#### Expected behaviour

Text outline should only ever appear behind the data label it's outlining.

#### Actual behaviour

Lines of the "outline text" sometimes continue below the data label text.

#### Live demo with steps to reproduce

https://jsfiddle.net/hon2a/4ktu0m1m/

_Note: I forgot to remove part of the original code I based the demo off (`xAxis.categories` in chart config), but while it shouldn't be used and therefore shouldn't impact the issue in any way, when I tried removing it now, the issue disappeared. Since in my real-world scenario I don't have such stuff in the config, I'm leaving it in the fiddle for the sake of issue reproduction._

#### Affected browser(s)

Chrome, IE, ... (all of them would be my guess)

**Comment by hon2a** [comment]
When I tried to work around this for the time being by turning the text outline off, I got [this issue] instead.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting and providing the fix!

**Comment by TorsteinHonsi** [comment]
Closed by e25a78547451aee2752d62ddfffa7963f2c65851
