### ISSUE TITLE
Multiple lines of data labels in treemap chart are rendered in the same place

### ISSUE THREAD

**Issue by hon2a** [highcharts/highcharts#6473]
Trying to work around [another issue](https://github.com/highcharts/highcharts/issues/6472), I tried to use treemap chart data labels without text outline.

#### Expected behaviour

Data label for each point is either not rendered or each line of text is rendered on a separate line.

#### Actual behaviour

Multiple lines of the label get sometimes rendered in the same place, which makes the text unreadable.

#### Live demo with steps to reproduce

https://jsfiddle.net/hon2a/ey33otfs/

#### Affected browser(s)

Chrome, IE, ... (likely all of them)

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Reduced demo: http://jsfiddle.net/14ggmdca/

**Comment by TorsteinHonsi** [comment]
#### Workaround
Set `textOutline: null` instead of `"none"`.
