### ISSUE TITLE
Internal "custom CSS properties" are not stripped from `style`

### ISSUE THREAD

**Issue by hon2a** [highcharts/highcharts#6474]
#### Expected behaviour

Internal "custom CSS properties" defined in `SVGRenderer`, such as `textOutline`, are by default not applied as DOM element `style` properties, i.e. they are stripped from `style` before it's applied to an element.

#### Actual behaviour

Properties like `textOutline` are applied as `style` properties along with the rest. As long as they're invalid CSS (for the given CSS parser implementation) they're ignored, so it's not an issue as of itself, but apart from showing up in dev tools, they pose a forward-compatibility risk (of actually becoming valid).

#### Live demo with steps to reproduce

Any demo using `textOutline` suffices, e.g. [this one](https://jsfiddle.net/hon2a/4ktu0m1m/). Just inspect the `text` node of any data label.

#### Affected browser(s)

All

**Comment by TorsteinHonsi** [comment]
Accidentally closed, sorry.

**Comment by hon2a** [comment]
No problem. You do, however, have the wrong issue number on that commit.
