### ISSUE TITLE
stickyTracking set to false disables shared tooltip

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#6476]
#### Actual behaviour
When the series has stickyTracking set to false, it disables shared tooltip.

#### Live demo with steps to reproduce
http://jsfiddle.net/c1gqsqLm/

It worked in 5.0.7 http://jsfiddle.net/c1gqsqLm/2/
stopped in 5.0.8 http://jsfiddle.net/c1gqsqLm/4/

**Comment by jon-a-nygaard** [comment]
Thanks for reporting, this issue will be fixed in the upcoming maintenance release. From the next version on stickyTracking will not be affected by `tooltip.shared`, and behave in the same manner with or without a shared tooltip. Which means that the following always applies:

> When true, the mouseOut event on a series isn't triggered until the mouse moves over another series, or out of the plot area. When false, the mouseOut event on a series is triggered when the mouse leaves the area around the series' graph or markers.

**Comment by pawl-bb** [comment]
For anyone looking into hiding the tooltip when the mouse is between series, you can use `plotOptions.series.events.mouseOut`:
```
    plotOptions: {
        column: {
            events: {
                mouseOut: function() {
                    // hides the tooltip when not hovering over a series
                    // using this because stickyTracking:false doesn't work with shared:true
                    this.chart.tooltip.hide();
                }
            }
        }
    },
```
