### ISSUE TITLE
Crosshair snap not functioning on bubble chart

### ISSUE THREAD

**Issue by ibrennan** [highcharts/highcharts#6477]
#### Expected behaviour
Expect to be able to set the crosshair property `snap` to be true and for the lines to intersect the centre of the bubble.

#### Actual behaviour
When `snap` is true the crosshairs do not render on the chart

#### Live demo with steps to reproduce
With crosshair `snap: false` set: http://jsfiddle.net/kmqgp45m/
With crosshair `snap: true` set: http://jsfiddle.net/jnuhogog/

Note how the 2nd link doesn't render any crosshair on the chart

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
It's a regression since v5.0.8, worked in v5.0.7: http://jsfiddle.net/highcharts/jnuhogog/1/

**Comment by feyzo** [comment]
Thank you <3

**Comment by TorsteinHonsi** [comment]
Fails since https://github.com/highcharts/highcharts/commit/f6a5acb
