### ISSUE TITLE
Responsive rule doesn't apply on solid gauge pane options

### ISSUE THREAD

**Issue by frntz** [highcharts/highcharts#6479]
#### Expected behaviour
Pane options set in responsive rule must be used

#### Actual behaviour
Nothing change when setting pane options

#### Live demo with steps to reproduce
http://jsfiddle.net/frntz/Los01hL4/
Pane settings on the right solid gauge is not set

#### Affected browser(s)
Chrome / Safari

**Comment by pawelfus** [comment]
Thank you for reporting this issue.

Related tickets: #6089 and #6438

**Comment by TorsteinHonsi** [comment]
Prepared test: http://jsfiddle.net/highcharts/Los01hL4/1/
