### ISSUE TITLE
Highcharts SVG Export has overlapping chart legend icons

### ISSUE THREAD

**Issue by smithclay** [highcharts/highcharts#648]
It seems like the SVG export feature of Highcharts needs to be tweaked to allow for more padding between legend items.

Steps to reproduce (in Highstocks, latest version):
1. See http://jsfiddle.net/MQp56/
2. Export as SVG Image
3. Open SVG Image (in Safari 5.1.1 for Mac)

_Result_: The chart legend icons overlap/run into the legend item text.
_Expected_: The chart legend icons should have more padding.

Thanks for your help!

**Comment by kursion** [comment]
I have the same problem :( 
Using latest version of HighChart and exporting from HighChart server.
By the way: my legends are longer (around 50 chars)

**Comment by highslide-software** [comment]
The original post's fiddle works fine now: http://jsfiddle.net/highcharts/AtKV9/3/

Can you show an example of your failing chart?
