### ISSUE TITLE
Symbol Rotation

### ISSUE THREAD

**Issue by kiyongpark** [highcharts/highcharts#6480]
I have a question with Symbol rotation. 
I've seen your command and marker rotation is enable to revise highcharts.js
but I don't know detail thing how adjust .attr() function to series symbol in highcharts.

thanks

**Comment by pawelfus** [comment]
Hi @kiyongpark 

This is our bug tracker. If you have a question, then please create a topic on our forum or send us an email. More details [here](http://www.highcharts.com/support).
