### ISSUE TITLE
Offline Export of Pie Charts not working in Firefox

### ISSUE THREAD

**Issue by cmaguire1990** [highcharts/highcharts#6481]
#### Expected behaviour
When implementing the latest version of highcharts (5.0.9), I have created various Pie type charts. Upon choosing the export to PDF option, I expect the PDF to download and upon opening, the Pie chart should be displayed.

#### Actual behaviour
I can download the PDF document ok, however, upon opening the PDF, the Pie image is missing. Title and series data, however, is visible.

![piechart export](https://cloud.githubusercontent.com/assets/26483422/24044351/d2b4663e-0b12-11e7-91da-4f83d94f2712.png)

#### Live demo with steps to reproduce
I have realised that this issue can also be replicated on an official offline export demo on the highcharts site.
If we navigate to: 
http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/highcharts/exporting/offline-download-demo/

and if we proceed to change the chart type from "area" to "pie" and re-run the project, then we download and try to view the pdf...we can see that the title and series data loads fine, however, the actual pie chart does not display. I have only noticed this issue with downloading Pie charts into PDF on Firefox when using the latest (5.0.9) version of offline exporting.

#### Affected browser(s)
Firefox only

**Comment by cmaguire1990** [comment]
![piechart export](https://cloud.githubusercontent.com/assets/26483422/24044312/b1227cd6-0b12-11e7-8b55-0bb06902d6c2.png)

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

It's an issue with the svg2pdf.js library, hereby reported at https://github.com/yWorks/svg2pdf.js/issues/22.

**Comment by cmaguire1990** [comment]
Any update on this issue?

**Comment by TorsteinHonsi** [comment]
We are looking into it with the yWorks team, see https://github.com/yWorks/svg2pdf.js/issues/22.

**Comment by cmaguire1990** [comment]
Unfortunately, replacing the 2 files provided does not resolve the issue I am experiencing.
I updated both svg2pdf.js & svg2pdf.src.js within Highcharts-5.0.9\code\lib

**Comment by TorsteinHonsi** [comment]
It works nicely for me. Are you sure you're loading the correct files? Make sure the `libURL` setting is correct.

![skjermbilde 2017-03-31 kl 10 36 40](https://cloud.githubusercontent.com/assets/227836/24542990/0d8ec5ce-15fe-11e7-8c3e-276a891ceb41.png)

**Comment by cmaguire1990** [comment]
libURL:"https://code.highcharts.com/5.0.9/lib/

Maybe the files haven't been updated on the highcharts site?

**Comment by TorsteinHonsi** [comment]
Correct, v5.0.10 isn't published yet. It will probably be today, we're almost finished regression testing.

**Comment by cmaguire1990** [comment]
Thank you

**Comment by sebastianbochan** [comment]
Works since HC 5.0.10. 

Tested in FF 52.x.

Reopen if problem will come again.
