### ISSUE TITLE
on pie chart drilldown

### ISSUE THREAD

**Issue by mcatal** [highcharts/highcharts#6482]
#### Expected behaviour
![image](https://cloud.githubusercontent.com/assets/17703423/24046754/4fc0eeea-0b2c-11e7-9d51-a016187841a4.png)
![image](https://cloud.githubusercontent.com/assets/17703423/24046761/5ac48be4-0b2c-11e7-87a4-04e3777f0b40.png)

when i want to use <br/>, dataLabel using like the picture. how can i fix it ?

using ..

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/drilldown.js"></script>
online scripts...

**Comment by pawelfus** [comment]
Hi @mcatal 

For questions, please contact us directly by email, see [support info](http://www.highcharts.com/support). This is our bug tracker.

Kind Regards,
Paweł
