### ISSUE TITLE
Exporting in Safari

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#6484]
Exporting in Safari causes error in console:

> [Error] Failed to load resource: Frame load interrupted          (export.highcharts.com, line 0)

It doesn't break anything, but doesn't look healthy. It looks like a bug in Safari browser: https://bugs.webkit.org/show_bug.cgi?id=46491 - but I think it used to work fine with old exporting server.

#### Demo:
Any demo: http://www.highcharts.com/demo/

#### Affected browser(s)
Safari

**Comment by TorsteinHonsi** [comment]
@larsac07 Maybe it belongs in the export server repo.

**Comment by larsac07** [comment]
@TorsteinHonsi I think the closest related repo would be this one because it seems to be a problem with how Safari itself treats requests for downloading files

**Comment by TorsteinHonsi** [comment]
Maybe, but if it used to work fine with the old exporting server then it has to be something that changed with the way the data is sent over. We could start with checking if that is true, and if it is, check what headers the server sends.

**Comment by larsac07** [comment]
Looking into it

**Comment by larsac07** [comment]
Nope, same issue there. Not a problem with the server itself

**Comment by davidpelayo** [comment]
[Related to this discussion](https://github.com/eligrey/FileSaver.js/issues/215#issuecomment-302668297).

Now on latest Safari release, this gets fixed. See [more info here](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html).
