### ISSUE TITLE
Add point on pie chart at specific index/x value

### ISSUE THREAD

**Issue by croucha** [highcharts/highcharts#6485]
I have this pie chart demo below where I'm trying to add a point at a specific x and it always appends the point to the end.  I don't notice this issue with line charts.  Is there no way to indicate where I want to start adding the points to this pie chart?

http://jsfiddle.net/bxm4W/45/

**Comment by pawelfus** [comment]
Hi @croucha 

By design, pie doesn't have "x" value as there is no x-value. You can force that behaviour by setting `Highcharts.seriesTypes.pie.prototype.requireSorting = true;`.

Demo: http://jsfiddle.net/bxm4W/47/

**Comment by croucha** [comment]
Hi @pawelfus 

Thanks for showing me that!  That's very useful.
