### ISSUE TITLE
Removing colorAxis

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6488]
#### Behaviour
Trying to remove colorAxis results in ‘chart.options[key].splice is not a function’ error.

#### Live demo
http://jsfiddle.net/d_paul/agj45fas/

**Comment by TorsteinHonsi** [comment]
If we replace the failing code in `Axis.remove` with the following, we don't get the error message. But there's still a problem with the legend symbol remaining.
```js
if (H.isArray(chart.options[key])) {
			chart.options[key].splice(this.options.index, 1);
		} else {
			delete chart.options[key];
		}
		```

**Comment by sebastianbochan** [comment]
_Internal note_
The problem is that on colorAxis destroy, we do not check that we have relation wiht legend and not destroy legend. 

The fix looks like:


```
		if (key === 'colorAxis') {
			chart.legend.destroy();
			delete chart.options[key];
		} else {
			chart.options[key].splice(this.options.index, 1);
		}
```

but Im afraid that is not perfect. 

@TorsteinHonsi  what you mean?

**Comment by TorsteinHonsi** [comment]
Thanks @sebastianbochan. FYI, I modified your fix by removing the legend _item_ belonging to the color axis, not the whole legend.
