### ISSUE TITLE
Add SVG path along side of point?

### ISSUE THREAD

**Issue by croucha** [highcharts/highcharts#6489]
Hi @pawelfus,

Is it possible in the API to add an additional SVG path or something that runs parallel with the current point paths so that I can use stoke to give a border only on one side.  Please see screen below:

![svgborder-one-side](https://cloud.githubusercontent.com/assets/2465008/24122053/77b71fec-0d88-11e7-8b4e-999c3eea4559.png)

**Comment by pawelfus** [comment]
Hi @croucha 

This is our bug tracker, for questions please use our forum or send us an email :) [More details](http://www.highcharts.com/support).

Short answer, yes you can achieve that using our API: [Renderer.arc()](http://api.highcharts.com/highcharts/Renderer.arc).

**Comment by croucha** [comment]
awesome, thanks!
