### ISSUE TITLE
Split tooltip: scatter wrong tooltip

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6492]
#### Expected behaviour
Tooltip pointing to the scatter point.

#### Actual behaviour
Tooltip position is not refreshed - in 5.0.7: http://jsfiddle.net/xgn6Lan4/2/

In 5.0.9 (current) - tooltip is not displayed at all: http://jsfiddle.net/xgn6Lan4/3/
But this should be resolved through #6449 

After this is resolved fixing #6332 should be more efficient.

*Suggested fixing order:*
#6449 -> this issue -> #6332

**Comment by TorsteinHonsi** [comment]
The `split` tooltip feature is a variety of `shared` tooltip, and both scatter and flags series are prohibited from being part of the shared tooltip through the internal `noSharedTooltip` property. The fix will be to make sure this also applies to split tooltips in the same way as shared tooltips.
