### ISSUE TITLE
HighStock multi-panel y-zoom, cannot read property 'clientX' of null

### ISSUE THREAD

**Issue by GeoTob** [highcharts/highcharts#6494]
#### Expected behaviour
Using y-axis zoom on a highstock chart with multiple panels should 'just work'

#### Actual behaviour
While zoom technically works, the console is spammed with quite a lot of `TypeError`s like this: 

```
Uncaught TypeError: Cannot read property 'clientX' of null
    at https://code.highcharts.com/stock/highstock.js:201:237
    at Array.forEach (native)
    at a.each (https://code.highcharts.com/stock/highstock.js:26:471)
    at a.Pointer.getHoverData (https://code.highcharts.com/stock/highstock.js:201:90)
    at a.Pointer.runPointActions (https://code.highcharts.com/stock/highstock.js:202:321)
    at a.Pointer.onContainerMouseMove (https://code.highcharts.com/stock/highstock.js:211:163)
    at HTMLDivElement.d.onmousemove (https://code.highcharts.com/stock/highstock.js:213:68)
```

The error is thrown here, and can be fixed by adding `hoverpoint !== null &&` as a condition to the enclosing if: https://github.com/highcharts/highcharts/blob/8ffd09bce9b44441d35c9d6528d43a5f4c7c79aa/js/parts/Pointer.js#L240

It might also be useful to modify the following lines so that hoverPoints are hidden if the none can be found?

#### Live demo with steps to reproduce

1. http://jsfiddle.net/h1m871ke/
2. Open browser console
3. Zoom the y-axis

#### Affected browser(s)
At least Chromium v56.0.2924.87

**Comment by GeoTob** [comment]
Anyone able to reproduce this?

**Comment by GeoTob** [comment]
Interesting, seems to happen only on when tooltip sharing is enabled, ie when

```
tooltip: {
    shared: true
}
```

**Comment by yamaha252** [comment]
I have the same error when tooltip is shared

**Comment by TorsteinHonsi** [comment]
Strange, I can't see this error... I'm on Highcharts v5.0.10, Chrome v57 on macOS Sierra.

**Comment by GeoTob** [comment]
Thanks, I double-checked the fiddle and noticed it's using the latest stable. This error seems to have disappeared in v5.0.10, was there in v5.0.9.

Maybe @yamaha252 can confirm before we close this?

**Comment by yamaha252** [comment]
Thanks, guys! The issue was sloved in 5.0.10
