### ISSUE TITLE
Big right spacing causes part of legend to be clipped.

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6497]
#### Expected behaviour
Legend fits in chart.

#### Actual behaviour
Legend is clipped on left side.

#### Live demo with steps to reproduce
https://jsfiddle.net/4be6gddy/
(in Win/Chrome clipping is bigger and first items for each legend rows are not visible
![chart 2](https://cloud.githubusercontent.com/assets/8960408/24194674/38a0c8ce-0ef7-11e7-899f-ee878e95cc9d.jpeg)
)

**Comment by pawelfus** [comment]
@TorsteinHonsi - how should we resolve that issue? I see two possible solutions:

- [according to the docs](https://www.highcharts.com/docs/chart-design-and-style/design-and-style) we should apply spacings when calculating width of the legend [here](https://github.com/highcharts/highcharts/blob/27aff13f8a580c58a0a1b8aa18efc324bad41697/js/parts/Legend.js#L385). However, this will change how legend is rendered and some of the  tests will fail. For example:
![screen shot 2017-03-22 at 15 28 37](https://cloud.githubusercontent.com/assets/1453926/24202808/455feb5e-0f14-11e7-835e-8129f56d1e52.png)


- change aligning box [here](https://github.com/highcharts/highcharts/blob/27aff13f8a580c58a0a1b8aa18efc324bad41697/js/parts/Legend.js#L604-L607), so we align it to the correct bounding box

**Comment by TorsteinHonsi** [comment]
I think the first solution - it should be something like:
```js
if (horizontal && legend.itemX - initialItemX + itemWidth >
				(widthOption || (chart.spacingBox.width - 2 * padding - initialItemX - options.x))) {
```
But then I don't understand why it wraps in the test you picture above. The alignment to `spacingBox` looks correct to me.

**Comment by pawelfus** [comment]
I agree, the alignment to `spacingBox` is correct, so I would do the same fix as yours. Now just simple build and run test  `2104,2181` in the test suite you will see the legend in tow rows. I am worried that many users will come and report this as a bug. It can change drastically how chart is rendered, not always though (in our tests it is ~3 failing tests because of this change).

**Comment by TorsteinHonsi** [comment]
Yes I saw the same - but it shouldn't happen because it is well within the spacing box even with one row. I'll check some more.
