### ISSUE TITLE
problem in download page

### ISSUE THREAD

**Issue by lshgdut** [highcharts/highcharts#6498]
#### Expected behaviour
download button can been seen in download page

#### Actual behaviour

No buttons found in [download page](http://www.highcharts.com/download)
Because insecure script requests to http://www.highcharts.com/lib/jquery-1.11.0.min.js and http://code.highcharts.com/products.js?_=1490232505740 loading over http have been blocked by browser 's security policy

#### suggestions
change http to https 

#### Affected browser(s)

all

**Comment by sebastianbochan** [comment]
Thank you for reporting, we are fixing it.
