### ISSUE TITLE
Local exporting to PNG does not work with "allowHTML: true" [5.0.4+]

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6499]
#### Expected behaviour
Export chart to PNG using local exporting.

#### Actual behaviour
Chart doesn't get exported to PNG

#### Live demo with steps to reproduce
http://jsfiddle.net/a4nfo52h/ - 5.0.4 - does not work
http://jsfiddle.net/a4nfo52h/1/ - 5.0.3 - works as expected

1. Click export button
2. Notice that nothing happens

#### Affected browser(s)
Chrome
Firefox
Safari

**Comment by oysteinmoseng** [comment]
Note that we are supposed to fall back when there is actual HTML in the chart. But I added a fix so it doesn't fall back unless there really are `foreignObject`s in the SVG.

**Comment by aviramga** [comment]
Was this solved? Im still getting this on 6.1.0
@oysteinmoseng @stpoa

**Comment by aviramga** [comment]
Was this solved? Im still getting this on 6.1.0
@oysteinmoseng @stpoa

**Comment by sebastianbochan** [comment]
Hi @oysteinmoseng,
When I run a demo: http://jsfiddle.net/BlackLabel/9fhajmbe/ chart is exported to a file. Please let me know which browser (including full number of versions) you have.

Chrome: 67.0.3396.99

**Comment by mantydze** [comment]
Hi @sebastianbochan, 

I'm fighting same battle right now... 
My chart has yAxis with title like this "my units 10^30" 

I tried to add simple snippet into highcharts config and export stopped working:
```
yAxis:{
    	title:{
      	   useHTML: true,
      	   text: 'my units 10<sup>30</sup>'
      }
},
```
See working example: 
http://jsfiddle.net/u5e9cyn2/

**Comment by pawelfus** [comment]
@mantydze 

Please open js console, and you will find the reason: https://www.highcharts.com/errors/28/

> (...) The offline exporting module will fail for certain browsers, and certain features (e.g. exporting.allowHTML ) (...)
