### ISSUE TITLE
Point.update not working for changing color

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#65]
Demo: http://jsfiddle.net/cfKzS/226/
Report: http://highslide.com/forum/viewtopic.php?f=9&t=7122

**Comment by fredericlam** [comment]
Hi. 
I just reproduced the issue with chart.series[0].setData( new_data). Inside the new_data, i put the new values AND the new colors. 
Each path changes color only if I mouse over . 

Is this supposed to be fixed also for the setData() method ?

Thanks a lot.

**Comment by pawelfus** [comment]
See #4267 - it should be fixed on the bugfix branch: http://jsfiddle.net/ux74929j/6/

**Comment by fredericlam** [comment]
Hi and thanks for the reply.
Here is a case where it does not work : http://jsfiddle.net/fredericlam/nq24m739/
I based my code on the the bugfix js : http://github.highcharts.com/bugfix/highcharts.js.

Please can you have a look ?

**Comment by fredericlam** [comment]
@pawelfus i found a workaround with looping an all items and "forcing" the new color.
So chart.series[0].data[i].graphic.attr('fill', new_color).

Any new fix would be helpful.

Thank you.

**Comment by pawelfus** [comment]
Created separate ticket for `setData`: #4704
