### ISSUE TITLE
Download builder for HighCharts doesn't produce correct file

### ISSUE THREAD

**Issue by alphestdev** [highcharts/highcharts#6500]
Current download builder produces incorrect file:
http://www.highcharts.com/download

No matter how many checkboxes I check or uncheck, the downloaded file is always exactly the same.

I've noticed that the download link is not unique. 
https://www.highcharts.com/download/highcharts-custom.js

I don't know how the file is supposed to become custom, but I've tested after clearing cookies and cache, different browser. It doesn't help.

**Comment by sebastianbochan** [comment]
Thank you for the reporting.

@jon-a-nygaard any advices?

**Comment by alphestdev** [comment]
Today, with the new release, download builder for HighCharts 5.0.10 produced a file that triggers JavaScript syntax error: `missing } after function body`

[highcharts-5.0.10-custompack.js.txt](https://github.com/highcharts/highcharts/files/885834/highcharts-5.0.10-custompack.js.txt)

![screen shot 2017-03-31 at 15 47 18-fullpage](https://cloud.githubusercontent.com/assets/32202/24553121/5a7b3536-1629-11e7-93e4-6c34789035e1.png)

**Comment by TorsteinHonsi** [comment]
I did the same right now, with the same settings, but it works correctly. Could it be that you ran this right when we were deploying the new release?

**Comment by sebastianbochan** [comment]
When I was testing in Chrome / Firefox I was not able to reproduce it. Could you supply some browser details?

**Comment by alphestdev** [comment]
A day after my last message, the download builder a error-free file and even adopted the file when I changed the configuration (original issue). The original issue occurred in both latest Chrome & Firefox on Windows 7. I don't know what's changed, but it worked.

**Comment by sebastianbochan** [comment]
I closed the case, if problem will come again, please reopen.
