### ISSUE TITLE
Typo in Highcharts documentation

### ISSUE THREAD

**Issue by vget98** [highcharts/highcharts#6501]
#### Expected behaviour

On the highcharts website the description for the http://api.highcharts.com/highcharts/yAxis.softMax

The description is: 
A soft maximum for the axis. If the series data maximum is **greater** than this, the axis will stay at this maximum, but if the series data maximum is higher, the axis will flex to show all data.

#### Actual behaviour

It should be 
A soft maximum for the axis. If the series data maximum is **less** than this, the axis will stay at this maximum but if the series data maximum is higher, the axis will flex to show all data.

A minor issue just wanted to let you guys know.

**Comment by TorsteinHonsi** [comment]
Thanks!
