### ISSUE TITLE
Chart series are missing

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#6502]
Hello,
When I resize chart and make it wider, some series are missed and console error appears.

#### Live demo with steps to reproduce
http://jsfiddle.net/Pashe4ka/3dn7LeL0/1/

Video to reproduce: https://www.dropbox.com/s/j22tkvxtuop7yxn/missed_series.mp4?dl=0

#### Affected browser(s)

Latest chrome version

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! 

Simplified: http://jsfiddle.net/highcharts/3dn7LeL0/2/
