### ISSUE TITLE
No working way to escape delimeter character inside CSV using data module

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6503]
#### Expected behaviour
You should be able to escape delimeter character in CSV file.

#### Actual behaviour
There seem to be no way of doing this using CSV module

#### Live demo with steps to reproduce
https://jsfiddle.net/r8c62cwz/

Look at 2 different comma escaping example in CSV, both of them don't work

**Comment by morganfree** [comment]
Duplicate of #3850
