### ISSUE TITLE
Multiple series with x-axis breaks produces console errors and bad chart while scrolling

### ISSUE THREAD

**Issue by pldilley** [highcharts/highcharts#6504]
#### Actual behaviour
The chart in the below fiddle consists of three series and a separate navigator series. Two of the series are minutely data, while the most historic series is daily/weekly data. They are all meant to butt up against each other such that weekends and evening gaps for the stock market don't show.

When you drag on the chart itself to the right (move the data left) towards the daily data, and then once only daily data shows, drag back to the left (move the data right), you cannot get back to the minutely data. Instead console errors occur and the chart line goes flat.

#### Live demo with steps to reproduce
https://jsfiddle.net/pauld_ticko/tdvvgnrs/4/

#### Affected browser(s)
Seemingly all browsers

**Comment by pawelfus** [comment]
Hi @pldilley, thank you for reporting this bug!

*Internal note:*
It's caused by dividing by 0 [here](https://github.com/highcharts/highcharts/blob/6f842539af083e3351228a5dae364c6856f74d68/js/modules/broken-axis.src.js#L249-L250) -> that sets localA variable to Infinity.

**Comment by TorsteinHonsi** [comment]
Reliable reproduction: https://jsfiddle.net/highcharts/tdvvgnrs/8/

**Comment by TorsteinHonsi** [comment]
The commit above guards the division of zero, but we're still unable to pan back to the original data. Zooming with the navigator options works.

**Comment by pldilley** [comment]
Hey,
Just wondering what plans you guys have with this. Breaks appear in most stock charts (i.e. google finance), so I'm wondering am I approaching this in an unusual way in comparison to how most people would use breaks in HighStock? Is there a better way of doing these things?

I managed to reproduce the bug with just using a single series too (more simple to test with):
https://jsfiddle.net/pauld_ticko/k2nj1ofb/1/

**Comment by pldilley** [comment]
Hrm... well I have an ok work around for now. As soon as the user begins scrolling, I remove the breaks and show plotBands in place instead. Far from ideal, but it works for now. It would be awesome if you guys could fix the breaks though :)  Please let me know if you foresee any problems with this work around method.

**1. Edit highchart's source to add in some new events:**
`
           /**
             * Perform a drag operation in response to a mousemove event while the mouse is down
             */
            drag: function(e) {
                var chart = this.chart,
                ....
                ....
                if (this.hasDragged > 10) {
                    fireEvent(chart, 'drag', { chart: chart, e: e });  // <--- ADD THIS LINE HERE
`
`
           /**
             * On mouse up or touch end across the entire document, drop the selection.
             */
            drop: function(e) {
                ....
                ....
                fireEvent(chart, 'drop', { chart: chart, e: e });  // <--- ADD THIS LINE HERE
            }
`


2. When you create the x-axis break array, add in the properties for plotBands too (multi-purpose it). It could look like this:
`
{
   className: "fadeInPlotBand",
   color: "#FAFAFA",
   from: 1410552000000,    // From used in both breaks and plotBands
   label: {
      align: "center",
      rotation: 270,
      style: { color: "black", font-size: "11px" },
      text: "Closed",
      textAlign: "center",
      verticalAlign: "middle"
   },
   to: 1410811200000,   // To used in both breaks and plotBands
   zIndex: 5
}
`


3. Next, when you define the xAxis config, include the above multi-purpose break/plot band array for both breaks and plotbands:
`
{
   breaks: <that array>,
   plotBands: <that array>,
   otherConfigs: ...
}
`


4. Add in the custom event handler's to hide the breaks as the user drags, and show them when the user drops:
`
            chart: {
                events: {
                    drag: (args) => {
                        if (!args.chart.breaksBackup) {
                            args.chart.breaksBackup = args.chart.xAxis[0].userOptions.breaks;
                            args.chart.xAxis[0].update({ breaks: null });
                        }
                    },
                    drop: (args) => {
                        if (args.chart.breaksBackup) {
                            args.chart.xAxis[0].update({breaks: args.chart.breaksBackup});
                            args.chart.breaksBackup = null;
                        }
                    }
                }
            }
`


5. If you wish, you can use css transition effects with the "fadeInPlotBand" class defined above to fade in the plotBands. A fade in of 0.75 seconds works well with the timing of the chart animation as you show the breaks.

**Comment by pawelfus** [comment]
Hi @pldilley 

My apologies for the delay! Of course this needs to be fixed. Unfortunately I don't see any better and/or easier workaround. I guess this issue depends on data with a specific config. I just noticed that #6109 ticket refers to a very similar problem. Actually, on that ticket I am able to recreate your issue too.

Thank you for the workaround! It looks very good. In case you don't want to edit sources, you can use `Highcharts.wrap()` to [extend Highcharts](https://www.highcharts.com/docs/extending-highcharts/extending-highcharts) functionalities.

**Comment by pldilley** [comment]
As you suggested, I've created a wrap for this which needs 5.0.11 or greater for the fix [here](https://github.com/highcharts/highcharts/commit/cef7b9077eef76701112c5c4e7b50a3fe138c922).

```
Highcharts.wrap(Highcharts.Pointer.prototype, 'drag', function(proceed, e) {
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));

    if (!this.chart.breakBackups && this.hasDragged > 10) {
        let className = this.chart.container.className || '';
        let xAxises = this.chart.xAxis;

        this.chart.breakBackups = [];

        for (var i=0; i < xAxises.length; i++) {
            let xAxis = xAxises[i];
            this.chart.breakBackups.push(xAxis.userOptions && xAxis.userOptions.breaks);
            xAxis.update({ breaks: null }, false);
        }

        this.chart.container.className = className + ' isPanning';
        this.chart.redraw();
    }
});

Highcharts.wrap(Highcharts.Pointer.prototype, 'drop', function(proceed, e) {
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));

    if (this.chart.breakBackups) {
        let xAxises = this.chart.xAxis;
        let className = this.chart.container.className || '';

        for (var i=0; i < xAxises.length; i++) {
            let xAxis = xAxises[i];
            xAxis.update({ breaks: this.chart.breakBackups[i] }, false);
        }

        this.chart.breakBackups = null;
        this.chart.container.className = className.replace(/ isPanning/, '');
        this.chart.redraw();
    }
});
```

isPanning class gets added which can be used to fade in/out the break blocks if wanted using css.
