### ISSUE TITLE
Add Responsive part in Download Builder

### ISSUE THREAD

**Issue by jlescot** [highcharts/highcharts#6508]
We used to build our custom version of _Highcharts_ so that we would only load a single JS file. But with the latest version _5.0.x_, we wanted to give a try to the new **responsive** options, but it seems to be only available when using files from http://code.highcharts.com/

#### Expected behaviour
- It should be possible to select the **Responsive** part when building a custom version of _Highcharts_

#### Actual behaviour
- Currently, there is no way to include the **Responsive** part when using the _DOWNLOAD BUILDER (EXPERIMENTAL)_ tool (http://www.highcharts.com/download#builder-holder) to generate a custom version of _Highcharts_

**Comment by KacperMadej** [comment]
Thank you for reporting about the problem.

For a custom build you could use the Node.js solution documented here: http://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files

**Comment by jlescot** [comment]
Great, I didn't know about this solution yet! It shoud perfectly fit with our needs.
Should I close this issue or do you still want to add this possibility in your _DOWNLOAD BUILDER (EXPERIMENTAL)_ tool?

**Comment by KacperMadej** [comment]
@jlescot Let's keep this issue open.
