### ISSUE TITLE
Tooltip doesn't scroll

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#6515]
#### Expected behaviour
If the tooltip has too much content to be shown at once then a scrollbar or pagination arrows should be shown to be consistent with the legend.

#### Actual behaviour
Tooltips with a lot of content truncates the content and doesn't allow scrolling.

![image](https://cloud.githubusercontent.com/assets/14222462/24367774/e9bc76a6-12eb-11e7-958e-e97da21af562.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/ffmedy6L/

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
By default the tooltip is cropped, but you can use workaround with CSS styles.

Demo:
- http://jsfiddle.net/7wVDV/147/

**Comment by TorsteinHonsi** [comment]
Another thing to consider is to use a `split` tooltip. It doesn't supply scrolling, but at least it removes the overshooting values: http://jsfiddle.net/highcharts/ffmedy6L/1/

**Comment by Rashaine** [comment]
Thanks for the suggestion guys but neither is adequate. The tooltip overflowing outside the chart isn't desired and would still eventually run out of space causing the tooltip to be clipped without means of scrolling. The split option is also inadequate since it shows even less information. 

I think the best option is to allow the tooltip to be scrolled or paginated like the legend. If scrolling or pagination isn't a desired functionality for tooltips I'll have to work on a custom tooltip solution on my end.

**Comment by KacperMadej** [comment]
@Rashaine  You could use the Sebastian's solution and add few CSS styles to get a scrollable tooltip: http://jsfiddle.net/7wVDV/214/

**Comment by Rashaine** [comment]
Thanks KacperMadej that's more inline with what I was looking for. Is there a way to do something similar with just the svg tooltip? That is, without the useHTML flag. Our charts show multiple tooltips at a time and with the shape being in svg and the content being in html we encountered z-index issues when tooltips overlapped. Therefore we render our tooltips solely in svg and override the refresh method for custom layouts.

**Comment by TorsteinHonsi** [comment]
Rather than trying to do this in SVG, which is tricky, I think you are better off creating everything, including the shape, in HTML: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/highcharts/tooltip/fullhtml/

**Comment by Rashaine** [comment]
Ok, thanks Torstein, we have a lot of custom tooltips so this would require a bit of redesign on our end and might break our chart exports which contains sticky tooltips, but we'll look into it.

**Comment by sebastianbochan** [comment]
@TorsteinHonsi should we consider it still as a bug?

**Comment by TorsteinHonsi** [comment]
We can leave it open to keep track of the comments and workarounds.
