### ISSUE TITLE
First day shown on chart doesn't match 'from' date in date picker

### ISSUE THREAD

**Issue by Byteman2017** [highcharts/highcharts#6516]
#### Expected behaviour

•	1m range button must be highlighted 
•	the date range to be shown as From: 2017-02-24 , To: 2017-03-24
•	first day to be shown on chart should be: 2017-02-24

#### Actual behaviour

•	none of the range buttons appears highlighted                                           
•	the date range shows: FROM: 2017-02-24 / TO: 2017-03-24 (this is correct)                  
•	first day shown on chart is: 2017-02-27 (starting point shown on chart doesn’t match date ‘from’)

#### Live demo with steps to reproduce

- change selected: 1 to selected: 0
- run example

#### Affected browser(s)
Chrome, IE, FireFox

**Comment by Byteman2017** [comment]
to see expected behaviour  follow steps to reproduce bug then click on the 'from' date on the date picker and press ENTER key

**Comment by Byteman2017** [comment]
sorry! I missed the URL: 
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/column/

**Comment by pawelfus** [comment]
Hi @Byteman2017 

My apologies for the delay! Could you recreate issue with static dataset? Do you think it's the same issue as #6537 ? (Fixed version: https://github.highcharts.com/hc5-fixes/highstock.js )

**Comment by pawelfus** [comment]
Closing as I am not able to recreate the issue. If someone will be able to do it, with a static dataset, please let us know.
