### ISSUE TITLE
Legend elements are overlapped when series.name = ' ' and legend.layout = 'vertical'

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6519]
#### Expected behaviour
Elements in legend should display one below another

#### Actual behaviour
Elements in legend are overlapped

#### Live demo with steps to reproduce
https://jsfiddle.net/kwmfwsf6/

**Comment by Jmales** [comment]
@Izothep I'm the one with the problem. A solution is not mandatory for me at this point. If you find a workaround tell me please.

**Comment by Izothep** [comment]
Hi Jmales, 

Thank you for your message. Your issue is already fixed on Highcharts hc5-fixes branch. This is not the official release, but hc5-fixes is our developer branch and fixes from this branch gets to be implemented in future official Highcharts versions.

**Comment by Jmales** [comment]
Ty my man! However, how can I install that branch via npm or something else? I'm kind of a noob there

**Comment by Jmales** [comment]
Well, I just copied/pasted to `highcharts.src.js` for now, until an official fix comes up. Thank you for the fast help ;)
