### ISSUE TITLE
Callback argument for Highcharts.chart is undocumented

### ISSUE THREAD

**Issue by Fake51** [highcharts/highcharts#6523]
#### Expected behaviour
To be able to read from the documentation that the third argument for Highcharts.chart() is a callback that will be called with this bound to the chart object.

#### Actual behaviour
http://api.highcharts.com/highcharts/ does not show that other arguments than a string selector and a config object will be accepted. So it's hard to know if this is an official feature or just some undocumented debug feature.

#### Live demo with steps to reproduce
http://api.highcharts.com/highcharts/

#### Affected browser(s)
All/None

**Comment by TorsteinHonsi** [comment]
It is already there: 
http://api.highcharts.com/highcharts/Highcharts.chart and
http://api.highcharts.com/highcharts/Highcharts.Chart

![skjermbilde 2017-03-29 kl 11 25 07](https://cloud.githubusercontent.com/assets/227836/24447843/9664d434-1472-11e7-8a8e-d97c1f59552f.png)

**Comment by Fake51** [comment]
Yes, but it's missing from here
![highcharts api reference - google chrome_012](https://cloud.githubusercontent.com/assets/124474/24448039/2ed42a44-1473-11e7-9275-191103e01bc5.png)

It would be great to see the documentation consistent instead of getting mixed signals depending on where you look.

**Comment by TorsteinHonsi** [comment]
Yes I see the point. The tree structure on the left side is there in order to make it easy to get started with configuration options (hence the header), but I get your point, as we're also using the constructor here.

**Comment by Fake51** [comment]
It was literally the first thing I saw when I looked for documentation on the callback, so it confused me that it wasn't there. It was much harder to find the documentation on the .chart call.

Anyway, thanks for taking the time to respond and thanks for a great product.
