### ISSUE TITLE
Boost module doesn't seem to work with treemap

### ISSUE THREAD

**Issue by githistory** [highcharts/highcharts#6524]
#### Expected behaviour
Render treemap with image tag

#### Actual behaviour
Treemap doesn't render with image

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
You're aware of this - http://jsfiddle.net/highcharts/jjwu2u2x/ ?

**Comment by githistory** [comment]
thanks for the hint tors, is this to say that heatmap.js is required in order for boost.js to work?

**Comment by TorsteinHonsi** [comment]
You're welcome! Treemap requires heatmap.

**Comment by githistory** [comment]
seems it renders fine without image tag without heatmap.js

**Comment by githistory** [comment]
As a follow up to this question, I found another issue. The boost module does kick in and render treemap as an image, but the dataLabels still hinder the performance given a large data set. If you disable dataLabels, then tooltip is gone as well.

So the question is, is it possible to disable labels while we keep tooltip?

**Comment by TorsteinHonsi** [comment]
@cvasseng

**Comment by githistory** [comment]
Some observations as I experiment with treemap+boost module, performance has been satisfactory around 5000 data points. When it goes above 10k, it feels it takes around same time than if I render all points to dom. So in big O terms it feels like O(n^2). Any idea?

**Comment by githistory** [comment]
I've created a fiddle, http://jsfiddle.net/sdeobwtf/

You can experiment with number of data points. Try 10k, 20k and 30k, you should observe obvious difference in rendering time.

**Comment by githistory** [comment]
When rendering 12xxx nodes, this function in treemap.src.js
![image](https://cloud.githubusercontent.com/assets/3829878/24993403/bec38b90-2058-11e7-81f3-df3183cea00c.png)
gets called 148,596,100 times
![image](https://cloud.githubusercontent.com/assets/3829878/24993433/e170ac86-2058-11e7-9b04-30ba5b87c638.png)

**Comment by personalGitRep** [comment]
I have this problem too. with larger data like 18K in my case the chart takes forever to load even with boost enabled. why so?

**Comment by vlodko** [comment]
@TorsteinHonsi  @githistory  is it by design that drill down feature doesn't work in treemap charts when boost module is loaded?

**Comment by pawelfus** [comment]
*Internal note:* Reported as #13853
