### ISSUE TITLE
Disappearing points’ fill colors on resizing

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6525]
#### Behaviour
In case when each point has set individual color in candlestick chart, resizing causing points are losing their fill color.

#### Live demo with steps to reproduce
http://jsfiddle.net/vko5tk5c/

1. Resize to decrease (custom fill colors disappear) and increase (custom fill colors are visible)

**Comment by sebastianbochan** [comment]
It is related with datagrouping, which groups points only by y values, not custom params like color. The solution of it is disable datagrouping.
