### ISSUE TITLE
textDecoration: underline not working in IE11/Win7 when chart's div is after some tables

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6526]
#### Expected behaviour
dataLables underlined.

#### Actual behaviour
Not underlined.

#### Live demo with steps to reproduce
This is a strange issue to replicate.
The chart's div needs to have two tr with td inside a table. 
http://jsfiddle.net/zv44y93j/1/

or 2 tables like that: http://jsfiddle.net/zv44y93j/2/
(or 4, 7, 9, 12, 14, [17](http://jsfiddle.net/zv44y93j/3/), 19, etc.)

#### Affected browser(s)
IE11 on Win7

**Comment by sebastianbochan** [comment]
_Workaround_
Set useHTML param in the datalabels object.

Docs:
- http://api.highcharts.com/highcharts/plotOptions.series.dataLabels.useHTML
