### ISSUE TITLE
Color of negative column does not update on click

### ISSUE THREAD

**Issue by eric-2d** [highcharts/highcharts#6527]
#### Expected behaviour
When clicking on a column I'd like to change it's color to signify it's selected.

#### Actual behaviour
This work for postive values columns but not for negative ones.

#### Live demo with steps to reproduce
Try clicking on the lavender colored negative olumns
http://jsfiddle.net/7gfdpvy9/

**Comment by TorsteinHonsi** [comment]
It's fixed now.

However, @eric-2d , the recommended, built-in way of doing selection is to use `allowPointSelect` and setting select state options: http://jsfiddle.net/highcharts/7gfdpvy9/2/.
