### ISSUE TITLE
'columnrange' series not centered

### ISSUE THREAD

**Issue by inad9300** [highcharts/highcharts#6530]
#### Expected behaviour
The data points on the series should be centered vertically (assuming the axis are inverted) in their lane.

#### Actual behaviour
Series on the top of the chart display their points near the top of the lane, while series on the bottom seem to put their points closer to the bottom of their lane.

#### Live demo
http://jsfiddle.net/inad9300/5sL1s5Lw/3/

#### Affected browser(s)
All.

**Comment by sebastianbochan** [comment]
This is default behaviour of columns. In the case when series does not have a point, reserves space for it.

Simplified demo:
- http://jsfiddle.net/2Lyvq5rd/

The solution is set grouping as false:
- http://jsfiddle.net/x0r6baL3/

**Comment by inad9300** [comment]
Thanks a lot for taking the time and for the solution, and please excuse my ignorance.

This default value doesn't probably make much sense for my setup, but anyway it's very easy to fix.
