### ISSUE TITLE
yAxis > plotLines > className

### ISSUE THREAD

**Issue by 3lmanana** [highcharts/highcharts#6534]
#### Expected behaviour
It should add specified class to the element.

#### Actual behaviour
It doesn't.

#### Live demo with steps to reproduce
http://jsfiddle.net/3lmanana/m3t36vcj/

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
The issues is caused by loading incorrect (not styled) highcharts version.

Fixed demo:
- http://jsfiddle.net/rdk6ge79/

**Comment by 3lmanana** [comment]
I have included styles in my SASS project. Will definitely check this out. Thank you!
