### ISSUE TITLE
Highstock: wrong time range caused by data grouping

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6535]
#### Expected behaviour
After zoom min on xAxis should be the same as in "From" input and should be based on series data.

#### Actual behaviour
Min data from initially grouped data is in "From" input and influences min extreme for the xAxis.

#### Live demo with steps to reproduce
http://jsfiddle.net/h9kz8fvz/

Steps:
1 - pointStart: Date.UTC(2004, 3, 3), data is grouped - first point on 2004-03-29 and so if "From" input. OK
2 - zoom into the beginning of the data. First point is 2004-04-03, but "From" shows as 2004-03-29

**Comment by pawelfus** [comment]
*Internal note:*
The problem is we still have navigator with dataGrouping, which has defined minimum as beginning of the week (29 of March). With disabled ordinal it's easier to see it: http://jsfiddle.net/h9kz8fvz/1/
