### ISSUE TITLE
Incorrect dates ranges when using 1 month button on highchart (Maybe this happens due to quantity of days in February)

### ISSUE THREAD

**Issue by silverenio** [highcharts/highcharts#6537]
#### Expected behaviour
When we click on 1 month button we see the ranges on selectors at the top right corner (for example for today date 2017-03-30): 2016-03-02 - 2017-03-30

The range on graph should be: 2016-03-02 - 2017-03-30 (as on dates fields)

BUT these both cases are wrong:

The selectors should be 2016-02-28 - 2017-03-30
The range on graph should be 2016-02-28 - 2017-03-30

#### Actual behaviour
When we click on 3month button we see the ranges on selectors at the top right corner (for example for today date 2017-03-30): 2016-03-02 - 2017-03-30

The range on graph is: 2016-03-03 - 2017-03-30

#### Affected browser(s)
Chrome, FireFox

**Comment by pawelfus** [comment]
Hi @silverenio 

Thank you for reporting this issue. Could you setup static jsFiddle demo with this issue? We will take a look.

**Comment by silverenio** [comment]
You may see it just here: http://www.highcharts.com/stock/demo/basic-line
Look at the value at "begin date" field at the right part of graph and then look please begin date on the graph.

**Comment by pawelfus** [comment]
I wasn't able to reproduce the issue with current dates. Using static data I can see that too: http://jsfiddle.net/kjmj0922/1/ - most probably it's connected to 28days in February..

**Comment by silverenio** [comment]
Hi, I've reproduced issue on your link

​

2017-04-11 17:08 GMT+03:00 Paweł Fus <notifications@github.com>:

**Comment by pawelfus** [comment]
It really looks like a problem with setting month to Feb. Short test:

```javascript
var x = new Date('2017-03-30T01:00:00.000Z');
x.setMonth(1);
console.log('date: ', x);
console.log('month: ', x.getMonth());
```

Result? 
> date: Thu Mar 02 2017 03:00:00 GMT+0100 (CET)
> month: 2
