### ISSUE TITLE
Chart update didn't update chart.events functions

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#6538]
#### Expected behaviour
Using chart.update() method, I think that chart events methods should be updated.

#### Actual behaviour
WIth chart.update() chart events aren't updated

#### Live demo with steps to reproduce
http://jsfiddle.net/ahv1sLxu/1/

To reproduce click on the button and make drilldown. Drilldown event function is not working.

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
#### Workaround
Instead of modifying the options through `chart.update`, set the events directly using `Highcharts.addEvent`: http://jsfiddle.net/ahv1sLxu/4/

In my opinion this is also a cleaner solution that lets you add and remove event handlers in a more intuitive way.

**Comment by Bjarkias** [comment]
This is a bit inconvenient when using your react wrapper (highcharts-react) as it doesn't provide a reference to the chart object.

Updating the options object is the only method of control and updating the events has no effects.
Effectively you can't update the event handlers.

**Comment by KacperMadej** [comment]
Hi @Bjarkias 

As a workaround you could set up the event function to call a function that is placed outside of chart's configuration and update that. 
Demo: http://jsfiddle.net/BlackLabel/631f04k8/
Steps: 
1. open browser console
2. drill down
3. see console messages
4. click update button
5. drill up and back down
6. see new console message

**Comment by jamescrowley** [comment]
I don't think this issue should have been closed. The workaround is far from ideal, and I'm not clear on any reason why the 'update' path *couldn't* update the handlers right now?

**Comment by pawelfus** [comment]
Thanks @jamescrowley - let me reopen the issue. It seems that stale bot does not consider referencing the issue as an activity..
