### ISSUE TITLE
Offline Exporting with MS Edge finally possible

### ISSUE THREAD

**Issue by DRippstein** [highcharts/highcharts#6540]
Previously, offline exporting of JPEG or PNG files was impossible on Edge browser without a fallback export server, as seen here: https://github.com/highcharts/highcharts/issues/6157

One of your dependencies "canvg" found a workaround for this:
https://github.com/canvg/canvg/pull/441

If you pull in the [latest canvg.js](https://github.com/canvg/canvg/blob/master/canvg.js) and just drop it in your lib/canvg.src.js (plus disable your Edge-specific image fallbacks), Edge should instantly start exporting images offline again.

**Comment by TorsteinHonsi** [comment]
That's great news, thanks for letting us know.

**Comment by oysteinmoseng** [comment]
@DRippstein I unfortunately wasn't able to export using Edge despite upgrading to the latest canvg from master. Also from the [thread on their issue](https://github.com/canvg/canvg/pull/441) it seems Highcharts SVGs are still not working.

It's great to see that they are improving their Edge support, though.

**Comment by oysteinmoseng** [comment]
We found a workaround that allowed us to ditch CanVG for Edge entirely, which means this now works much better.
