### ISSUE TITLE
setData() leaves series.data empty -> How to update candlestick point?

### ISSUE THREAD

**Issue by CloudStrife28492** [highcharts/highcharts#6542]
Hey there folks,

i'm setting a huge dataset to the candlestick chart via "setData(myArray)" which leaves the series data-array empty. So far, that's a normal behaviour cause I can still get the values from xData and yData. 
But how can I update the last candlestick value if I cant use Point.update()?

**Comment by sebastianbochan** [comment]
The series.data object is empty, because points are grouped. You should disable dataGrouping and then update the last point.

This is our bugtracker. For the support questions, please use forum / stackoverflow / email. Further information you can find here: http://www.highcharts.com/support
