### ISSUE TITLE
Display actual task time

### ISSUE THREAD

**Issue by larsac07** [highcharts/highcharts#6545]
GanttSeries/XRange: Add an `actual`-property which works like `completed`/`partialFill`, but uses a different marker than a partial fill

**Comment by larsac07** [comment]
#6558 may be a good solution

**Comment by larsac07** [comment]
If implemented with #6558, this issue can be closed after closing #6558, by adding a demo and documentation

**Comment by oysteinmoseng** [comment]
Closing, as we want to implement #6558 which should take care of this. If it turns out we need this in addition, we can revisit the idea.
