### ISSUE TITLE
gapSize and stacking = 'normal' don't work together

### ISSUE THREAD

**Issue by mattLarson** [highcharts/highcharts#6546]
#### Expected behaviour

Having these options:
    plotOptions: {
        series: {
            gapSize: 1,
            stacking: 'normal'
        }
    }

I would expect the chart to stack and to see gaps.

#### Actual behaviour

The chart will stack properly, but you won't see any gaps

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/series-gapsize/#

**Comment by pawelfus** [comment]
It's a regression. It used to work in 4.2.1 version (before nosegments branch was merged), demo: https://jsfiddle.net/gy71dpso/

**Comment by pawelfus** [comment]
*Internal note:*
[This line](https://github.com/highcharts/highcharts/blob/6e13054637ddd6662c60ee611a530991bf3f77fb/js/parts/AreaSeries.js#L174) causes different rendering for percent-stacking, but I assume it's the expected result:

- hc5-fixes: http://jsfiddle.net/gy71dpso/5/
- v4.2.1: http://jsfiddle.net/gy71dpso/6/
