### ISSUE TITLE
Unable to render HighCharts inside Firefox Addon WebExtensions

### ISSUE THREAD

**Issue by bluechips23** [highcharts/highcharts#6547]
#### Expected behaviour
Clicking on the Firefox Web Extension icon opens a popup window which should dynamically show the charts rendered by Highcharts

#### Actual behaviour
Clicking on the Firefox Web Extension icon freezes Firefox and we ultimately get "Unresponsive script tabbrowser.xml at 5828". If I don't include Highcharts, popup window works fine.

#### Live demo with steps to reproduce

The code is here https://github.com/bluechips23/FirefoxTesting
I also attached the zip file here.
[Firefox-debugging.zip](https://github.com/highcharts/highcharts/files/888408/Firefox-debugging.zip)

#### Affected browser(s)
Firefox version 52 (I haven't tested it against other versions).

**Comment by KacperMadej** [comment]
Hi,
Please provide steps needed to recreate the problem.

**Comment by bluechips23** [comment]
Here are the steps:

1. Clone & checkout https://github.com/bluechips23/FirefoxTesting into a local repo - into a local folder.
2. Open firefox. Type "about:debugging" in the url.
3. Select "Enable add-on debugging"
4. Click on "Load Temporary Add-on" and select any file (e.g. manifest.json) from the extension's folder. This will import the extension into Firefox.
5. Click on "debug" button - this will open a new Firefox page and prompt you whether you want to connect to localhost:<port> - Click "yes"
6. Open a new tab in the first Firefox window and just go to any website - e.g. google.com. You'll see the "T" icon in the URL bar. After the page is loaded, click on the "T" icon. This should open a popup window displaying the charts but bug would cause your Firefox instance to freeze and after some time, you will get the error ""Unresponsive script tabbrowser.xml at 5828""
7. You can look at the additional stack trace and logs in the debugging Firefox window.

Let me know if you need more info.

**Comment by KacperMadej** [comment]
Thank you for providing the steps.

You are creating a chart with a wrong argument:
`Highcharts.chart(container, {`
It shouldn't be `container`, but id of the container instead - I made such changes and it works. I tested this and this works, so I will close this issue and in case of further problems we could reopen this issue.
