### ISSUE TITLE
Empty errorbar series messes up with axis

### ISSUE THREAD

**Issue by paulo-raca** [highcharts/highcharts#6548]
#### Expected behaviour

I just set `data=[]` to quickly see what my chart would look like without error bars.

#### Actual behaviour

While the chart continues to work, it's X axis was messes up: Only 2 ticks on plenty of padding on the sides

#### Live demo with steps to reproduce
http://jsfiddle.net/mcwf6Ldv/

#### Affected browser(s)

Probably affects all browsers -- Tested on Chrome 55 for Linux 64 bits.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Simplified, a column series has the same effect: http://jsfiddle.net/highcharts/mcwf6Ldv/1/

The underlying cause is that it reserves space for the width of two columns. A workaround is to set `pointRange` to 0: http://jsfiddle.net/highcharts/mcwf6Ldv/2/

**Comment by paulo-raca** [comment]
Thanks
