### ISSUE TITLE
Navigator support in GridAxis

### ISSUE THREAD

**Issue by larsac07** [highcharts/highcharts#6552]
**Wanted behavior**
Use GridAxis just like with a regular stock chart

**Actual behavior**
When editing the max-handle, the navigator filters out points even though they are within range. The min-handle has no effect.

**MWD**
~~http://jsfiddle.net/larsac07/LLExL/7293/~~
http://jsfiddle.net/LLExL/7302/

**Comment by pawelfus** [comment]
It does work, but two things:

- x-values should be timestamps
- you have only a few points, increase the number of points or set `xAxis.minRange`

Demo: http://jsfiddle.net/LLExL/7302/

**Comment by larsac07** [comment]
Thanks, @pawelfus!
- Updating MWD.
- Week numbers dealt with in 16d86523c99da84bf8ee4bd7cdbb96ece199ddf1
- Looks like the remaining issues deal with:
- - yAxis not properly updating positions when moving navigator
- - Weeks smooshed together when there is only one day left in the previous week
