### ISSUE TITLE
Legend symbol click is not hiding series when legend.useHTML is set to true

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#6553]
#### Expected behaviour
Clicking on legend symbol should work the same when legend useHTML is set and when legend is not using HTML.

#### Actual behaviour
Legend symbol click is not hiding series when legend.useHTML is set to true

#### Live demo with steps to reproduce
http://jsfiddle.net/5n948mqe/

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Unable to recreate using version 6.1.4.
Closing as resolved.

**Comment by RainerSchwarze** [comment]
Hi @KacperMadej,
for the styled build the symbol click does not seem to work: http://jsfiddle.net/pob2r7h4/ 
Would the click handler be needed on the item.legendSymbol too?

**Comment by KacperMadej** [comment]
Looks like there was a fix suggested, but it was not merge into master or there's no trace of it in current code, so let's reopen this issue.

**Comment by jacobworrel** [comment]
@KacperMadej any update on this?

**Comment by KacperMadej** [comment]
@jacobworrel  We will be working on this case soon.

**Comment by jacobworrel** [comment]
@KacperMadej Awesome thanks!
