### ISSUE TITLE
Animation of labels, ticks and grid lines with Axis.update()

### ISSUE THREAD

**Issue by larsac07** [highcharts/highcharts#6555]
Labels, ticks and grid lines should animate with `Axis.update()`. This requires refactoring of `axis.update()` to avoid deleting and reinitiating the axis.

**Comment by TorsteinHonsi** [comment]
Removed this issue from the Gantt project. Smooth animation of gantt grid axes are now achieved using `Axis.setBreaks`, so this issue is no longer critical.
