### ISSUE TITLE
TreeGrid: Multiple points with the same name

### ISSUE THREAD

**Issue by larsac07** [highcharts/highcharts#6558]
TreeGrid: Multiple points with the same name or y-value gives some bogus behavior

**Expected behavior**
In a TreeGrid, multiple points with the same `name` should be supported when supplying an `id`

**Actual behavior**
TreeGrid requires both `name` and `id`s to be unique, which overcomplicates things. Setting the same `name` on multiple points results in removed or mispositioned duplicates.

**MWE**
http://jsfiddle.net/larsac07/LLExL/7296/

**Comment by oysteinmoseng** [comment]
Keep in mind that this is now meant to implement #6545 functionality. Test that this works intuitively, and consider if we need to add an alias or something.

**Comment by jon-a-nygaard** [comment]
Another case to have in mind is; It should be allowed to have two points with the same name, but nested under two different parents.
Example: https://jsfiddle.net/t0r8qz9p/222/

**Comment by oysteinmoseng** [comment]
Note #7910 and the use case of adding a milestone on top of a bar.

**Comment by oysteinmoseng** [comment]
Fixed now, control this behavior with `yAxis.uniqueNames` https://jsfiddle.net/fsL6mfu4/14/
