### ISSUE TITLE
GridAxis: Use axis title as column header

### ISSUE THREAD

**Issue by larsac07** [highcharts/highcharts#6561]
**Wanted behavior**
In a GridAxis, the axis title could be positioned so that it can work as a column or row header

**Actual behavior**
The axis title is hidden by default in a GridAxis, and adding it adds unwanted space around the axis.

**MWE**
http://jsfiddle.net/larsac07/rte2vk2g/1/

**Comment by larsac07** [comment]
This is implemented in f94f8128b9, but alignment is not configurable

**Comment by jon-a-nygaard** [comment]
Works as described in the API at [yAxis.title](https://api.highcharts.com/highcharts/yAxis.title)
