### ISSUE TITLE
Crosshair is always based on Highest Value in candlestick

### ISSUE THREAD

**Issue by keoztiryaki** [highcharts/highcharts#6562]
#### Expected behaviour
Horizontal crosshair must be based on close value in candlestick chart.

#### Actual behaviour
Horizontal crosshair is always based on highest value.

#### Live demo with steps to reproduce
http://jsfiddle.net/j00gLrc9/

#### Affected browser(s)
Firefox, Chrome - MAC OS X

**Comment by Izothep** [comment]
Thank you for reporting this issue. 

I think that we should be able to make small change in drawCrosshair method for adding option of drawing crosshair for close value (OHLC and candlestick series).

To be more specific, we should be able to change:
`pos = this.isXAxis ? point.plotX : this.len - point.plotY; // #3834
`

to: 
`pos = this.isXAxis ? point.plotX : this.len - (point.plotClose || point.plotY); // #3834
`

Working example with this small change: http://jsfiddle.net/j00gLrc9/2/
