### ISSUE TITLE
Bubble Chart y-axis ticks appearing at different places between library versions.

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6563]
#### Expected behaviour
The bubbles should appear against tick label "1" placed in middle of y axis.

#### Actual behaviour
The tick label "1" merges with the origin "0" and bubbles seem to appear on x axis. Is this behaviour deliberately changed from v5.0.7?

#### Live demo with steps to reproduce
Latest version : http://jsfiddle.net/c3tyzn9j/
Version 5.0.7 : http://jsfiddle.net/c3tyzn9j/1/

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! It's a regression, fails since f8037a44a.
