### ISSUE TITLE
Stacked Bar Chart Weird Behaivour

### ISSUE THREAD

**Issue by Volem** [highcharts/highcharts#6565]
#### Expected behaviour
No empty spots on the stacked bar chart.

#### Actual behaviour
Rendering has an issue on stacked bar charts. 
Empty spots on the bar depending on the data at the series. See the fiddle link

#### Live demo with steps to reproduce

http://jsfiddle.net/f0y6gwds/

#### Affected browser(s)
Tested on Chrome Latest,  IE11+, Edge, Firefox, Opera, Safari

**Comment by TorsteinHonsi** [comment]
Thanks for writing! You've got sorting errors in the console. If we sort the data, it stacks correctly: http://jsfiddle.net/highcharts/f0y6gwds/1/.

**Comment by Volem** [comment]
Thanks for the response. Appreciated. 
We will try and let you know

**Comment by Volem** [comment]
Worked flawless. Thanks again.
