### ISSUE TITLE
Scroll y axis in highchart not in highstock

### ISSUE THREAD

**Issue by chiragsatapara** [highcharts/highcharts#6567]
Hello

It is not possible to display y axis scroll bar in highchart. Not in Highstock.

If i move to highchart to highstock it will affect to my other charts?

**Comment by KacperMadej** [comment]
Hi,

Please use [support channels](http://www.highcharts.com/support) for questions. We are trying to keep github for bugs.

It's possible to create Highcharts charts using Highstock - it's a matter of used constructor (chart - for Highcharts, or stockChart - Highstock). More info in docs: http://www.highcharts.com/docs/getting-started/your-first-chart
