### ISSUE TITLE
chart.exportChart() leaves undefined item in Highcharts.charts array

### ISSUE THREAD

**Issue by dankoliver** [highcharts/highcharts#6569]
#### Expected behaviour
Highcharts.charts array contains same items as before the image export

#### Actual behaviour
After each image export there is one undefined item appended to Highcharts.charts

#### Live demo with steps to reproduce
http://jsfiddle.net/p6j9hxLy/
Check the messages in the debug console

**Comment by dankoliver** [comment]
Thanks for the quick fix!
However, I've found it necessary to also modify the reflow() function - for some reason it's still being called with _this_ being undefined after a chart has been exported.
I haven't traced down the root cause, might well be that it's in my implementation, but I've fixed it like so:
```javascript
        initReflow: function () {
            var chart = this,
                reflow = function (e) {
                    if(chart.options) {
                        chart.reflow(e);
                    }
                };
            addEvent(win, 'resize', reflow);
            addEvent(chart, 'destroy', function () {
                removeEvent(win, 'resize', reflow);
            });
        },
```

**Comment by pawelfus** [comment]
@TorsteinHonsi - this commit breaks exporting 3D charts. In 3D, there is a reference to a chart by `renderer.chartIndex`, now an exported chart doesn't define this. It's an issue [here](https://github.com/highcharts/highcharts/blob/c35fc5c5f5f01cdef5cb250e29c249f9575bfb05/js/parts-3d/SVGRenderer.js#L253) and later error [here](https://github.com/highcharts/highcharts/blob/c35fc5c5f5f01cdef5cb250e29c249f9575bfb05/js/parts-3d/SVGRenderer.js#L267).
