### ISSUE TITLE
Propriety name not displayed

### ISSUE THREAD

**Issue by kadru** [highcharts/highcharts#6570]
Expected behaviour
The name property is expected to be displayed when begin with the '<' character

Actual behaviour
When type the character  '< ' on series array,inside of data array, the name propriety of a pie chart (I have only checked that type of chart) the name is not displayed

 Live demo 
jsfiddle template: http://jsfiddle.net/gx3m8f6y/1/

Affected browser(s)
Currently checked on chrome  56.0.2924.76, Ubuntu 64 bit
and firefox for Ubuntu 52.0.2 (64-bit)

**Comment by pawelfus** [comment]
Hi @kadru 

Thank you for reporting this issue. It works fine when using `&lt;`, demo: http://jsfiddle.net/gx3m8f6y/3/

Duplicate od #2379
