### ISSUE TITLE
gaugesolid chart did not show 

### ISSUE THREAD

**Issue by donizb** [highcharts/highcharts#6571]
gaugesolid chart did not show..

5.0.9 is ok, but when version 5.0.10, happens error

message is below..

ORIGINAL EXCEPTION: Cannot read property 'getPlotBandPath' of undefined

**Comment by jon-a-nygaard** [comment]
Hi @donizb 
Could you share an example of your use case? [JSFiddle](https://jsfiddle.net/) works great for this.
Our [demo of a solid gauge](http://jsfiddle.net/6cp1nxsp/) is running fine in v5.0.10, so we will need more information on how to locate the issue.

**Comment by donizb** [comment]
it's my fault.
I was using angular 2.
It was duplicate import problem.. 
but I don't know 5.0.9 is fine.
anyway, thank you.
