### ISSUE TITLE
Axis Labels are not rendered properly when scrollbar is enabled

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6573]
#### Expected behaviour
Bar Chart axis labels should be rendered properly when scrollbar is enabled.

#### Actual behaviour
The axis labels are not rendered at the correct position and are overlapping the scrollbar.

#### Live demo with steps to reproduce
http://jsfiddle.net/dxhpzb81/2/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @sagargurtu 

Thank you for reporting this issue. Workaround: use xAxis.scrollbar instead of scrollbar options, demo: http://jsfiddle.net/dxhpzb81/4/

**Comment by sagargurtu** [comment]
Hi @pawelfus 

In the fiddle, http://jsfiddle.net/dxhpzb81/5/ , the x-axis label is being cut off from the bottom, even after using your workaround.

**Comment by pawelfus** [comment]
Thanks! Looks like scrollbar doesn't consider title when positioning. As workaround, you can increase `scrollbar.margin`: http://jsfiddle.net/dxhpzb81/7/

Issue with title reported here: #6576 - thank you!

**Comment by pawelfus** [comment]
*Internal note:*
This commit should be merged after 4251db9b1209f1760a8a4c87177f757c86079812 (ticket: #6576).
