### ISSUE TITLE
Can't display an image using the exportChart JS resources

### ISSUE THREAD

**Issue by matixmatix** [highcharts/highcharts#6575]
#### Expected behaviour

I'd like to display a custom logo in exported PDF. 

#### Actual behaviour

So far I tried injecting an `<img>` element into the body via the `"JS"` parameter, but the custom image doesn't get rendered. 

#### Live demo with steps to reproduce
http://jsfiddle.net/Lhnss9su/

Click "Download chart", there is no custom image on downloaded PDF.

**Comment by pawelfus** [comment]
I think the problem here is time required to load image and exporting won't wait for that image to be loaded.

Instead I would use `chartOptions` with load callback. Images added by renderer are on the waiting list to load before exporting, demo: http://jsfiddle.net/Lhnss9su/1/

**Comment by matixmatix** [comment]
@pawelfus thank you for this!! Another quick question before I close the issue - is it possible to render the image by not knowing about the image size? For example, I'd like to render my image in the top left corner and resize it so the width is 100px. Is that possible with the renderer?

**Comment by pawelfus** [comment]
> (...) is it possible to render the image by not knowing about the image size
As far as I know, SVG's `<image>` tag requires width and height attributes.

> For example, I'd like to render my image in the top left corner and resize it so the width is 100px
You can set default width/height to zero, then resize image, demo: http://jsfiddle.net/Lhnss9su/4/

**Comment by matixmatix** [comment]
Thanks @pawelfus!
