### ISSUE TITLE
Boost: Incorrect area chart rendering with combined context

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#6579]
#### Expected behaviour
Area chart series should look identical if rendered in a separate context or in a shared context.

#### Actual behaviour
Area chart renders as multiple columns when sharing context.

#### Live demo with steps to reproduce
http://jsfiddle.net/cqfd4voj/
1) Note the current rendering with columns
2) Remove a series to get the correct rendering

#### Affected browser(s)
Chrome

**Comment by Rashaine** [comment]
Somewhat related. previously with boost canvas series.markerGroup pointed to the series image/element. I noted that is no longer the case with WebGL but I was able to use series.image for the same purpose. However, when all the series are rendered as 1 image I don't see a link in the series to that image. Is there a way to retrieve the image element from the series?

**Comment by cvasseng** [comment]
Currently area charts are, as you've found, rendered as bar charts where each bar is 1px wide. This works well for cases where the boosting is done on point-level, as it will look correct (except with a missing area line) when the point density is high. We'll look into adding support for actual paths.

For your last question, if you're boosting on chart-level (e.g. with one context/image for all series) the image is attached to the chart: `chart.image`. So if you're on the series level, you could do `series.chart.image` to get it in those cases (or something like `(series.image ? series : series.chart).image` to get it regardless of how you're boosting).
