### ISSUE TITLE
Boost: Some colors are barely visible when opacity is applied.

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#6580]
With boost
![image](https://cloud.githubusercontent.com/assets/14222462/24815671/f8bf34d4-1ba3-11e7-8357-ea5133867624.png)

Without boost
![image](https://cloud.githubusercontent.com/assets/14222462/24815685/08612a14-1ba4-11e7-8aec-7043c061364d.png)

#### Expected behaviour
Markers with opacity should look the same with and without boost.

#### Actual behaviour
With boost enabled some series are hardly visible when they have an opacity.

#### Live demo with steps to reproduce
http://jsfiddle.net/66at6bwf/

Disable line 30 to render without boost.

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
@cvasseng The fix causes the scatter-smaller test to fail with NaN in the generated SVG....

**Comment by cvasseng** [comment]
@TorsteinHonsi I'm not seeing this in neither `master` or `hc5-fixes` - are you getting a console error, or is it somewhere in the SVG?

**Comment by TorsteinHonsi** [comment]
@cvasseng It was in the side-by-side test, but I fixed it. Turned out that the base64 encode image by coincidence contained the letters `NaN`, so our vigilant test runner put the foot down.
