### ISSUE TITLE
dataLabels issue with zero on a logarithmic axis

### ISSUE THREAD

**Issue by laopunk** [highcharts/highcharts#6585]
#### Expected behaviour
The data label should be snapped to the x axis, and centered withing its column space.

#### Actual behaviour
The data label is floating half way through the y axis height, and is not centered

#### Live demo with steps to reproduce
http://jsfiddle.net/0L0afe16/
Just run it and look at February's Tokyo

#### Affected browser(s)
Chrome on OSX

**Comment by pawelfus** [comment]
Thank you for reporting, I will take a look.

**Comment by TorsteinHonsi** [comment]
@pawelfus It doesn't always make sense to draw it on the bottom of the Y axis... http://jsfiddle.net/highcharts/0L0afe16/3/

Maybe we should look for the threshold instead, or the part of the Y axis closest to the threshold || 0.

**Comment by pawelfus** [comment]
You are right, thanks! Threshold will be great (like here: http://jsfiddle.net/0L0afe16/5/ ), I will update the commit (using `translatedThreshold`).
