### ISSUE TITLE
Shared tooltip - wrong point click event for stacked columns

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6586]
#### Expected behaviour
Click fired for a point that is being hovered.

#### Actual behaviour
Click fired for a column that has top closer to the cursor.

#### Live demo with steps to reproduce
http://jsfiddle.net/rw7gt91r/
Steps:
1. click at the bottom part of blue column to see in console that a click event is fired for a black column.

**Comment by sebastianbochan** [comment]
Problem appears also without stacking:
- http://jsfiddle.net/3n4yaL3a/

**Comment by TorsteinHonsi** [comment]
Fails since 3b4afbbd, release v5.0.10.

**Comment by lesrpo** [comment]
Unfortunately is not working well. https://jsfiddle.net/s5JqN/1081/ sometimes when you go like crazy with the mouse it shows all the values
![high1](https://cloud.githubusercontent.com/assets/11498186/25605642/40ecc71c-2f1d-11e7-94cf-47019e4e716d.PNG)

Also the colorByPoint doesn't work, do I have to add it by every single data value?

Thank you

**Comment by TorsteinHonsi** [comment]
> Also the colorByPoint doesn't work, do I have to add it by every single data value?

For `colorByPoint` to work, you need more than one data point for each series. Your series all have one point each.

@jon-a-nygaard Will you have a look at the hoverPoints thing?

**Comment by jon-a-nygaard** [comment]
The second issue was a duplicate of #6687. Fixed in next maintenance.
