### ISSUE TITLE
Highcharts not displaying y-axis on right with opposite flag

### ISSUE THREAD

**Issue by LandonSchropp** [highcharts/highcharts#6587]
#### Expected behaviour

When setting the `opposite` flag to `true` in `yAxis`, I expect the yAxis to display to the right of the chart.

#### Actual behaviour

The yAxis is present in the DOM, but it's off the chart.

#### Live demo with steps to reproduce

http://jsfiddle.net/ah3qrtya/1/

#### Affected browser(s)

Tested in Chrome.

**Comment by LandonSchropp** [comment]
If you change the `opposite` flag to false, the titles show up again.

**Comment by sebastianbochan** [comment]
The reason of it is setting marginRight as 0. As a result title does not have enough space to be draw.

Fixed demo:
- http://jsfiddle.net/kw1jwyjv/

**Comment by LandonSchropp** [comment]
Is it possible to still have no space between the right edge of the chart and container without using `marginRight`?

**Comment by pawelfus** [comment]
I think you want to set `spacingRight`, not `marginRight`, please take a look: http://jsfiddle.net/ah3qrtya/2/

**Comment by LandonSchropp** [comment]
That did the trick. Thanks Pawel.
