### ISSUE TITLE
Pie chart not rendered with undefined values

### ISSUE THREAD

**Issue by ypconstante** [highcharts/highcharts#6589]
#### Expected behaviour
Chart rendered with all the available values

#### Actual behaviour
When one of the y values is undefined, the pie slices are not rendered

#### Live demo with steps to reproduce
http://jsfiddle.net/acduz89x/2/

#### Affected browser(s)
Opera 44

**Comment by sebastianbochan** [comment]
The number or null values are mandatory, not undefined.

**Comment by TorsteinHonsi** [comment]
While I agree with @sebastianbochan that it isn't strictly a bug (it conforms to the docs), I made a fix for it because we already have a good structure for checking point validity, which wasn't properly applied in pie series.
