### ISSUE TITLE
Upgrade to version 5 provides vastly different tones for rgba

### ISSUE THREAD

**Issue by tregoning** [highcharts/highcharts#6591]
#### Expected behaviour
Highcharts/stock 4:
http://jsfiddle.net/tregoning/00kmg5t5/

#### Actual behaviour
Highcharts/stock 5:
http://jsfiddle.net/tregoning/k4ydgq6x/

Open them both side by side and it will be obvious

**Comment by pawelfus** [comment]
Hi @tregoning 

Thank you for reporting this. In Highcharts 4, fill-opacity attribute was set on paths with rgba() colors which was wrong. Setting `fillOpacity: 1` in Highcharts 4 will produce the same result as in Highcharts 5: http://jsfiddle.net/00kmg5t5/1/

More about fillOpacity in our [docs](http://api.highcharts.com/highcharts/plotOptions.area.fillOpacity).
