### ISSUE TITLE
Upgrade to version 5 seems to set lineWidth to stacked series when 'state:hover'

### ISSUE THREAD

**Issue by tregoning** [highcharts/highcharts#6592]
#### Expected behaviour
Highcharts/stock 4
http://jsfiddle.net/tregoning/cp45kqbn/1/

#### Actual behaviour
Highcharts/stock 5
http://jsfiddle.net/tregoning/4arf6qep/1/

NOTE: Explicitly setting state={hover:{lineWidth:0}} does not fix the issue see: http://jsfiddle.net/tregoning/9x93jbb9/1/

**Comment by pawelfus** [comment]
It's added by [`lineWidthPlus`](http://api.highcharts.com/highcharts/plotOptions.area.states.hover.lineWidthPlus), when disabled (set to 0) it works as in Highcharts 4, demo: http://jsfiddle.net/4arf6qep/3/
