### ISSUE TITLE
Upgrade to version 5 no longer accepts lowercased rgba colors 

### ISSUE THREAD

**Issue by tregoning** [highcharts/highcharts#6593]
Setting color in rgba (lowercase) no longer works

#### Expected behaviour
Highstock/chart version 4
http://jsfiddle.net/tregoning/qauoca0x/

#### Actual behaviour
Highstock/chart version 5
http://jsfiddle.net/tregoning/ndyh2bLb/

**Comment by pawelfus** [comment]
Thanks!

It looks strange. Workaround, use `fillOpacity`: http://jsfiddle.net/ndyh2bLb/1/ I think that actually `RGBA()` is broken and should work like `rgba()`.

*Internal note:*
Looks like `Color.parsers[0]` doesn't accept `RGBA()`, only `rgba()`.

**Comment by TorsteinHonsi** [comment]
What happens in v5 is that the line color is correctly using the opacity from the rgba definition. We can see that if we make the line wider: http://jsfiddle.net/highcharts/ndyh2bLb/2/:

The area however, takes the rgb components from the `color`, and applies the default `fillOpacity` to it, which is 0.75. 

I've updated the docs with information about what settings that take precedence: http://api.highcharts.com/highcharts/plotOptions.area.fillOpacity

**Comment by TorsteinHonsi** [comment]
Regarding uppercase/lowercase, only lowercase is allowed. The v5 behaviour is caused by Highcharts.Color successfully parsing lowercase rgba.
