### ISSUE TITLE
Series out of clippath - boost module

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6594]
#### Actual behaviour
Points are out of clippath.

#### Live demo with steps to reproduce
Demo:
- http://jsfiddle.net/fqrwe6a9/

**Comment by cvasseng** [comment]
Internal note: Looks to be an issue with min/max on the y-axis. Setting it to a range which actually fits the points (e.g undefined or `min=0`/`max=1`) will cause the rendering to work as it should.

**Comment by TorsteinHonsi** [comment]
> Setting it to a range which actually fits the points (e.g undefined or min=0/max=1) will cause the rendering to work as it should.

But this also means that we don't need a clip path, since the whole graph is drawn within the plot area. 

The clip path in the demo is like the following: 
`xml
<clipPath id="highcharts-bjkilxn-2">
    <rect x="67" y="46" width="723" height="400" fill="none"></rect>
</clipPath>
`
The height is too great. 400 is is the height of the chart, not the plot area. It may be that we're clipping the group as a markerGroup instead of series.group, or that something goes wrong when animation is finished.

**Comment by TorsteinHonsi** [comment]
These two locations set the clip height:

* https://github.com/highcharts/highcharts/blob/v5.0.10/js/modules/boost.src.js#L1916
* https://github.com/highcharts/highcharts/blob/v5.0.10/js/modules/boost.src.js#L1949

It is obviously wrong in this case, but changing it to use `plotHeight` would probably break stock charts with multiple panes (navigator plus regular series). In non-boost we have resolved that by using [multiple clip areas](https://github.com/highcharts/highcharts/blob/v5.0.10/js/parts/StockChart.js#L690-L724), but in Boost that will only work when each series has its own canvas...

**Comment by cvasseng** [comment]
Yeah, you're right.

And yes; using `plotHeight` will break the navigator in stockcharts. 

It may work to do culling in the point transformation routine based on `plotHeight` when not rendering the navigator. That is, to clamp the transformed Y-value to `plotHeight` for regular series.

**Comment by hotohoto** [comment]
Is there any progress on this issue?

**Comment by KacperMadej** [comment]
+1
