### ISSUE TITLE
Legend displayed over tooltip

### ISSUE THREAD

**Issue by Ramyani** [highcharts/highcharts#6596]
When we are using floating legend with custom image then its' displayed over the tooltip.
http://jsfiddle.net/g2j344z4/

I have tried with the z-index by enabling useHTML for both legend and tooltip. But still the legend image is coming top of the tooltip.
http://jsfiddle.net/g2j344z4/2/

**Comment by pawelfus** [comment]
Hi @Ramyani 

Please, take a look [here](http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting): 

> Most places where text is handled in Highcharts, it is also followed by an option called useHTML. When this is true, the text is laid out as HTML on top of the chart. This allows for full HTML support and can be a good idea if you want to add images in your labels, tables in your tooltip etc. The downsides are that
> 
> - <b>it will always be laid out on top of all other SVG content</b>, and
> - that it is not rendered the same way in exported charts, unless you use the experimental exporting.allowHTML option.
