### ISSUE TITLE
why this.dataMax in labelFormatter function of legend  is undefined?

### ISSUE THREAD

**Issue by tailorsira** [highcharts/highcharts#6599]
#### Expected behaviour
this.dataMax is not undefined

#### Actual behaviour
the 'this' object is not null, but the this.dataMax is undefined, why?

#### Live demo with steps to reproduce

http://jsfiddle.net/LLExL/7406/

#### Affected browser(s)
chrome

**Comment by tailorsira** [comment]
![Uploading 微信图片_20170417174801.png…]()

**Comment by pawelfus** [comment]
Hi @tailorsira 

Legend is rendered before extremes of the series are calculated. That means `this.dataMax` is unavailable at this moment. If you need `dataMin` or `dataMax`, you need to calculate (you can use `this.options.data` array).

**Comment by tailorsira** [comment]
Thank you@pawelfus, Finally I use this.yData to get the data, then calculate it.

**Comment by pawelfus** [comment]
Thank for the info!
