### ISSUE TITLE
How to increase performance of chart loading without using boost.js

### ISSUE THREAD

**Issue by suryamdv** [highcharts/highcharts#6605]
#### Expected behaviour
Fast loading of chart without boost.js when more than 9 series data is available.

#### Actual behaviour
Able load chart without boost.js but it is taking more time especially in IE browser.

#### Live demo with steps to reproduce
We had created JSFiddle http://jsfiddle.net/19gf7rLx/9/  to reproduce but it is working  fine here. But we try to use same in our salesforce application we are getting issue.

#### Affected browser(s)
Almost in every browser it is taking some time to load but in IE it is taking more time to load chart.
We are looking for some suggestions where we can improve performance of charts without using boost.js
We had tried to use boost.js but we have issue with column and Bar charts. refer #6600  & #6602 .

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
