### ISSUE TITLE
Unable to tab to chart legend when heatmap module is loaded

### ISSUE THREAD

**Issue by vmaha** [highcharts/highcharts#6606]
We have a webpage that hosts multiple types of charts. 

Some of these charts require the heatmap module, so we've included the heatmap module script.

We also want the charts to be accessible and support keyboard navigation, so we included the accessibility module script.

#### Expected behaviour
A user should be able to use the 'Tab' key to move focus to the chart legend.

#### Actual behaviour
After adding the heatmap module script to the page, a user is unable to use the keyboard to navigate to the legend.

#### Live demo with steps to reproduce
http://jsfiddle.net/sxb3u3k8/1

Tab into the chart.

Keep pressing tab, and notice that you'll never get to the legend.

Remove the heatmap.src.js script from the html, re-run the jsfiddle, and note that the bug goes away.

#### Affected browser(s)
Chrome, IE, Firefox.

**Comment by sebastianbochan** [comment]
Related with: https://github.com/highcharts/highcharts/issues/6511
