### ISSUE TITLE
Click event not working 

### ISSUE THREAD

**Issue by bnerDY** [highcharts/highcharts#6607]
#### Expected behaviour
issue regression:
step 1: click on (3, 50) show the expected rectangle hover.
step 2: click on (2, 30). In this case, the rectangle hover is not working. you can not even catch the mouse event.

#### Actual behaviour
can not catch mouse event when selecting lower value on yaxis if you click on higher value first.

#### Live demo with steps to reproduce

https://jsfiddle.net/bnerDY/0e6anr7c/44/

#### Affected browser(s)
latest version of chrome.

**Comment by pawelfus** [comment]
This is caused by rendering the rect on top of the series. All events are captured by this new rectangle. You can remove events from this rect by setting `pointer-events: "none"`, demo: https://jsfiddle.net/0e6anr7c/45/

**Comment by bnerDY** [comment]
thanks a lot! :)
