### ISSUE TITLE
maxHeight does not hide all items

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6608]
#### Expected behaviour
Set pagination and correct amount of items.

#### Actual behaviour
When maxheight is set to less than 30 it shows the pagination links but still shows all legend items.

#### Live demo with steps to reproduce
Example:
- http://jsfiddle.net/7oumL71f/

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
The fixed version hides the legend completely, which isn't much better, but it may be more intuitive. The obvious workaround would be to make the maxHeight big enough to always show something.
