### ISSUE TITLE
PieChart label placed near wrong slice

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#661]
Run this example: http://jsfiddle.net/zKZPT/

The labels are not positioned with the slices for the smaller values. 
Each label takes up a whole horizontal line and the next label is placed below it even when there's enough room and the labels are short.

Forum thread: http://highslide.com/forum/viewtopic.php?f=9&t=14036

**Comment by TorsteinHonsi** [comment]
Still valid in v6.1.0.
