### ISSUE TITLE
Using the "Reset Zoom" button with Highstocks only zooms out to previous zoom

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/highcharts#6612]
#### Expected behaviour
Clicking on the "Reset Zoom" button when used with Highstocks should zoom the chart out all the way, just like with Highcharts.

#### Actual behaviour
After multiple zoom-ins, the "Reset Zoom" button will only zoom out to the previous zoom.

#### Live demo with steps to reproduce
0. Enable the "Reset Zoom" button to appear for Highstocks
1. Zoom into an area on the chart (not the navigator)
2. Without resetting zoom, zoom into an area on the chart again
3. Click the "Reset Zoom" button

[jsfiddle](http://jsfiddle.net/lanimelrok/9r6v4g7u/1/)

**Comment by pawelfus** [comment]
Hi @LaniMoo 

Thank you for reporting this issue. Actually, Reset Zoom button should only change yAxis extremes, as user has other options to interact with the xAxis (Navigator and Range Selector with "All" button). 

@TorsteinHonsi Do I miss something? So now Reset Zoom resets xAxis extremes to the previous ones?

**Comment by LaniMoo** [comment]
Thanks for your response, @pawelfus.

From what I observed, if you recreate the above steps with [regular Highcharts](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/resetzoombutton-position/), then Reset Zoom will actually zoom out all the way, as opposed to just the previous zoom.

Which is what leads me to think it's a bug with Highstock....

**Comment by TorsteinHonsi** [comment]
In Highstock we have the Range selector with the All button, and charts are often initialized in a zoomed state, for example to 1M or 3M. That's why the "Reset zoom" button resets to the previous state, not to "All".

**Comment by LaniMoo** [comment]
Is there any way I can get the "Reset zoom" button to reproduce the same behavior in Highstock as it does in Highcharts? I have the range selector disabled, which is why I'd like to use the "Reset zoom" button to zoom out all the way.

**Comment by TorsteinHonsi** [comment]
Here's a snippet that disables the previous zoom feature: 

```js
Highcharts.wrap(Highcharts.Axis.prototype, 'zoom', function (proceed, newMin, newMax) {
	var ret = proceed.call(this, newMin, newMax);
    
    delete this.previousZoom;
    
    return ret;
});
```
[View it on jsFiddle](http://jsfiddle.net/highcharts/9r6v4g7u/2/).

**Comment by LaniMoo** [comment]
This worked. Thank you so much!

**Comment by vlsg** [comment]
Lani, thanks so much for bringing up this issue - we were having the same problem and it was driving us nuts!  Torstein, thanks so much for the work-around, that worked for us too! :)

**Comment by TorsteinHonsi** [comment]
Ok, we should definately do something here. 

Do you feel it would be a good idea to let the _Reset zoom_ button zoom all the way out when the range selector is disabled, and keep the current behaviour when the range selector is enabled?

Alternatively, and for finer control, we could add an option like `zoomResetTo` that could take `all` and `previous` as settings? It is good if we can avoid adding another option to the API, but if you need the control we'll do it.

**Comment by LaniMoo** [comment]
> Do you feel it would be a good idea to let the Reset zoom button zoom all the way out when the range selector is disabled, and keep the current behaviour when the range selector is enabled?

I vote this one!

**Comment by vlsg** [comment]
Torstein, I am always in favor of being able to explicitly control a feature, so I like the zoomResetTo idea.  Could you default it to 'all'?  Thanks!

**Comment by TorsteinHonsi** [comment]
I found another thing when digging into the code - it currently goes to the previous zoom only if the navigator or the range selector is enabled, so actually we're half way there. 

But the missing feature in my opinion is that it does the previous zoom even when the chart is initialized with viewing "all", and I think that's where it goes wrong. So with the fix above, this is how it works:
* If the range selector is enabled, navigator enabled _and_ the chart is initialized with a specific range (typically by selecting one of the range selector buttons), the zoom button goes to previous. It would be counter intuitive if you start by looking at a month, zoom in, click the button then suddenly you are looking at all data.
* If the chart is initialized without a specific range (viewing all data), the reset zoom button will always revert to "all".
