### ISSUE TITLE
3D-highcharts axis rendering issue with Angular Material tabs

### ISSUE THREAD

**Issue by matt212** [highcharts/highcharts#6614]
#### Expected behaviour
 template: http://jsfiddle.net/bilbobaggins/17Lsdosf/4/

#### Actual behaviour

Hi,

when i using 3d highcharts with angular material tab , there is an axis rendering issue

Please refer to below jsfiddle for the same

#### Live demo with steps to reproduce

 template: http://jsfiddle.net/bilbobaggins/uv5cdyx9/3/

![highcharts-3d-issues](https://cloud.githubusercontent.com/assets/1698139/25219369/e45dc88e-25cb-11e7-851f-b59e90c8cf07.gif)

#### Affected browser(s)
chrome Version 58.0.3029.81 (64-bit)

**Comment by pawelfus** [comment]
Hi @matt212 

I don't think this is a bug. Highcharts generates chart in a given container. What happens next is angular **copying** the HTML and generates the page. In that moment, all events for the chart are lost and animation doesn't have a chance to run. The same happens with a 2D charts too, see: http://jsfiddle.net/uv5cdyx9/5/ (if we disable the animation, then it looks better, but still it's not interactive: http://jsfiddle.net/uv5cdyx9/6/ and http://jsfiddle.net/uv5cdyx9/4/ )

**Comment by matt212** [comment]
hi @pawelfus , 
thanks for response what would plan of action in order to apply 3d animation , any pointers , alternatives rendering approach ??.
other  issue is currently  not about 3d animation ,but  it is about  x and y axis being disoriented !
Please find attached screenshot for you reference 
![axis issue](https://cloud.githubusercontent.com/assets/1698139/25418206/90744860-2a67-11e7-82bf-a8b183ba030c.png)

**Comment by pawelfus** [comment]
Just don't create a chart outside angular app. For example you can use a controller and generate chart inside. Or use a directive highcharts-ng.

Example with controller: http://jsfiddle.net/uv5cdyx9/7/

**Comment by matt212** [comment]
Hi, 
Thanks for the reponse, 
I am creating chart inside angular app which is inside controller , but the x and y axis issues persist only  "3d chart " rest it is working as expected !

> working without 3d it was always working !

![2d](https://cloud.githubusercontent.com/assets/1698139/25471897/afb01134-2b46-11e7-9458-77dc7e2264c3.png)

> With 3d (highcharts-3d.js) the X and Y axis are getting distorted 

![distoration with 3d](https://cloud.githubusercontent.com/assets/1698139/25471907/bcb66f36-2b46-11e7-9351-44cf5f8da535.png)

Many thanks

**Comment by matt212** [comment]
Hi, 
Ok now i got hold of it, give me some time will re-evalute the components , in the meantime  this is updated version of your fiddle with 3d charts js integrated , working as expected 
http://jsfiddle.net/3ox2dgse/

**Comment by matt212** [comment]
Hi, 
I re-evaluated the components and applied child controller with app and now its is working as expected with perfect 3d rendering .
Please find attached screenshot for your reference 
![finalworking3d](https://cloud.githubusercontent.com/assets/1698139/25477357/dc2bda90-2b5a-11e7-8e9a-85566f8f5ea7.png)

Thanks for your time and assistance !

**Comment by pawelfus** [comment]
Ok, great to hear that! :)
