### ISSUE TITLE
Incorrect documentation for Highstock yAxis.breaks: no module actually required

### ISSUE THREAD

**Issue by ransoing** [highcharts/highcharts#6619]
In the Highstock documentation for `yAxis.breaks`, it says that the `broken-axis.js` module is required.

This is the case for Highcharts, but not for Highstock. In Highstock, there is no `broken-axis.js` module, and the `breaks` feature seems to work without loading any modules.

Documentation: http://api.highcharts.com/highstock/yAxis.breaks
JSFiddle example, not loading any "breaks" module: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/intraday-breaks/

**Comment by pawelfus** [comment]
Thank you for reporting this! Of course, you are right, Highstock has this plugin in the core.

**Comment by TorsteinHonsi** [comment]
Fixed.
