### ISSUE TITLE
Display different between Highcharts page and pure svg

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#6620]
#### pure svg code generate by Highcharts

![snipaste_20170421_112959](https://cloud.githubusercontent.com/assets/6829290/25261689/d7a527a8-2685-11e7-9eb5-bb27d58c04ff.png)

#### Highcharts page
![snipaste_20170421_113127](https://cloud.githubusercontent.com/assets/6829290/25261693/dda55646-2685-11e7-8d80-6593993272b6.png)

#### Live demo with steps to reproduce

http://jsfiddle.net/LLExL/7423/

pure SVG copy from above demo: http://jsfiddle.net/wamm2zdr/

**Comment by pawelfus** [comment]
Hi @zhy1stgg 

It's `refX` and `refY`, not `refx` and `refy`. See working demo: http://jsfiddle.net/LLExL/7425/

**Comment by zhy1stgg** [comment]
@pawelfus thank you very much
