### ISSUE TITLE
Stacked and Percentage area charts are not displaying correctly when data series is more than 9 when using boot.js

### ISSUE THREAD

**Issue by SrinivasGit049** [highcharts/highcharts#6621]
#### Expected behaviour
Stacked and Percentage area charts should display correctly when data series is more than 9 when using boot.js

#### Actual behaviour
Stacked and Percentage area charts are not displaying correctly when data series is more than 9 when using boot.js

#### Live demo with steps to reproduce
http://jsfiddle.net/z6t7xm4d/

#### Affected browser(s)
IE,Safari,Chrome,Firefox

**Comment by pawelfus** [comment]
Hi @SrinivasGit049 

Could you recreate issue in jsFiddle? For me it looks fine: http://jsfiddle.net/nq628xxn/ - thanks!

**Comment by onemenny** [comment]
@pawelfus Here is a reproduction (having the same issues)
http://jsfiddle.net/onemenny/hacd3Ljs/5/
When disabling the boost the stacking works as expected, with the boost, it just not working

**Comment by sebastianbochan** [comment]
Looks like `seriesThreshold` cause the issue.

Demo:
- http://jsfiddle.net/2zsof85n/

**Comment by SrinivasGit049** [comment]
@pawelfus  I had updated the jsfiddle where issue is reproducing
