### ISSUE TITLE
Demo error in your website

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#6622]
http://www.highcharts.com/demo/combo-meteogram#https://www.yr.no/place/United_Kingdom/England/London/forecast_hour_by_hour.xml

![snipaste_20170421_144700](https://cloud.githubusercontent.com/assets/6829290/25265789/3b2bd1c6-26a1-11e7-962f-b2028fb68d85.png)

**Comment by pawelfus** [comment]
Thank you for reporting this. It's already reported: #6550
