### ISSUE TITLE
Global timezone option broken

### ISSUE THREAD

**Issue by hylke94** [highcharts/highcharts#6623]
#### Expected behaviour
After setting another timezone, all datetimes are converted to the given timezone.

#### Actual behaviour
Even with moment.js included, an error is thrown and rendering stops (what not should happen according to the documentation). The demo page for this function gives the same error.

#### Live demo with steps to reproduce

http://api.highcharts.com/highstock/global.timezone
http://jsfiddle.net/gh/get/jquery/3.0.0/highslide-software/highcharts.com/tree/master/samples/highcharts/global/timezone/

#### Affected browser(s)
Chrome/all?

**Comment by pawelfus** [comment]
Thank you for reporting this issue. It looks like this URL is not loaded: http://momentjs.com/downloads/moment-timezone-with-data-2010-2020.min.js

Using this URL: http://momentjs.com/downloads/moment-timezone-with-data-2012-2022.min.js - we will get a chart. Demo: http://jsfiddle.net/hzrujv6L/

**Comment by hylke94** [comment]
Thanks. That fixed it indeed. Updated docs would be nice ;).
