### ISSUE TITLE
Series.update() is not updating options.series.data array

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#6626]
#### Expected behaviour
Using series.update() should update all series options (in chart.options.series).

#### Actual behaviour
Using series.update() doesn't update options.series.data array.

#### Live demo with steps to reproduce
http://jsfiddle.net/r69apkfj/5/

To reproduce update chart and look at series data in console (developer tools).

#### Affected browser(s)
All

**Comment by Resin01** [comment]
+1

**Comment by TorsteinHonsi** [comment]
_Internal note_:
While `chart.series[0].options.data` is updated, `chart.options.series[0].data` is not. A [merge](https://github.com/highcharts/highcharts/blob/v5.0.10/js/parts/Series.js#L402-L406) has caused to two objects to be different, while they should perhaps be the same object.

**Comment by ZenPylon** [comment]
I'm also having this issue.
