### ISSUE TITLE
Boost: Missing line rendering at 5000+ points

### ISSUE THREAD

**Issue by scottadmi** [highcharts/highcharts#6629]
#### Expected behaviour
A straight line (at y-value zero in jsfiddle demo) for provided timeseries data.

#### Actual behaviour
No line is rendered but the hover tooltips work demonstrating data is being loaded. Removing the boost module shows proper rendering

#### Live demo with steps to reproduce
https://jsfiddle.net/sp5p9guf/1/

#### Affected browser(s)
All

**Comment by cvasseng** [comment]
@TorsteinHonsi This works as expected in hc5-fixes. It's related to the Y-value being constantly zero as far as I can tell. I'm not sure where the difference is, it looks like the fix related to this has been merged into master..

**Comment by cvasseng** [comment]
Works in master and latest.
