### ISSUE TITLE
Boost module - boostThreshold is ignored, column charts are distorted 

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#6630]
As of 5.0.8 The boost module seems to have a different configuration settings (it is no longer just a number)
It took me some time to figure out what went wrong.
There are no breaking changes mentioned in the changelog, can someone please elaborate? 

It is still labeled experimental,  and I know you are working/already has webGL abstraction. When will the vail be taken off, When will it become a decent module?

**Comment by TorsteinHonsi** [comment]
> There are no breaking changes mentioned in the changelog, can someone please elaborate?

The boost module is still in the experimental phase, hence there is no official API to break.

**Comment by onemenny** [comment]
Ok, I understand what you mean. I'll add another limitation here (-;  https://github.com/highcharts/highcharts/issues/5223
