### ISSUE TITLE
Boost - errorbar and boxplot are not displayed

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6631]
#### Expected behaviour
http://jsfiddle.net/nsdevaraj/23wtvfcc/

#### Actual behaviour
Shapes are missing.

#### Live demo with steps to reproduce
Example:
- http://jsfiddle.net/nsdevaraj/0o0o57bw/

**Comment by TorsteinHonsi** [comment]
I'm not sure if we want a boosted boxplot/error bar plot... 

In general, many series types are not supported in Boost, for example pie and waterfalls, because they typically don't appear with tens of thousands of data points.

@cvasseng
