### ISSUE TITLE
Inverted Map reset zoom failure

### ISSUE THREAD

**Issue by npetralia** [highcharts/highcharts#6634]
Hello,

#### Expected behaviour
Zoom working on inverted map

#### Actual behaviour
After reset zoom the map is not displayed

#### Live demo with steps to reproduce
http://jsfiddle.net/4hg19x58/3/

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Please let us know what is a real use case of inverted map?

**Comment by npetralia** [comment]
I do not have real usage i agree, i found this bug during some tests. But if it is not relevant why we have this options ?
If this option is here it should works or the option should be removed.

**Comment by sebastianbochan** [comment]
_Internal note_
@oysteinmoseng the simplest solution is disable inverted option for a map. Does it make sense for you ?

**Comment by pawelfus** [comment]
*Internal note:*
It's not a problem when creating chart, but when updating chart, demo: http://jsfiddle.net/0jddrfpt/

**Comment by oysteinmoseng** [comment]
`inverted` is forced false for maps, but that's not enforced on `chart.update`. An inverted map does not really make sense.

**Comment by sebastianbochan** [comment]
@oysteinmoseng I know, but I think that it should be blocked in `chart.update` too.

**Comment by oysteinmoseng** [comment]
@sebastianbochan Yes ideally, although `inverted` is not in the docs for Highmaps, so we could also just ignore it. @TorsteinHonsi what do you think?

**Comment by TorsteinHonsi** [comment]
Either just ignore it, otherwise we would need to check for the forced options on update too. But it is a misconfiguration, so I say we just ignore it for now.

**Comment by sebastianbochan** [comment]
Should be close this case or leave as open with enhanmencent flag?

**Comment by TorsteinHonsi** [comment]
I'll just close it, if anyone disagrees they can add a comment.
