### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'yAxis' of undefined (related to tooltip with polygon series)

### ISSUE THREAD

**Issue by xyzisinus** [highcharts/highcharts#6635]
#### Expected behaviour

The issue is only seen from the developer console.  Behavior wise, the user will not observe any ill effects.

#### Actual behaviour

N/A

#### Live demo with steps to reproduce

https://jsfiddle.net/xyzisinus/st6tLdue/1/

Strictly follow the steps below to produce the error:

1. Go to the sample code above.
2. Open the developer console.
3. Let the mouse hover over any bar series at first.
4. Then move the mouse to the polygon series.  At that moment the error will appear.

This error shows up only once for each page reload.

Summary: The error will appear ONLY when the tooltip code is run for at least one bar series at first.  If the mouse is moved to the polygon series before touching any bar series, the error will not show.   Looking at the code, I suspect that a lingering tooltip object for a bar series gets into the mix.

#### Affected browser(s)

Chrome and Firefox (at least).  On Firefox, the error is
TypeError: a.series is undefined

The issue is observed on Highcharts v5.0.10 (2017-03-31).  In the uncompressed file, the stack is

(anonymous function)	@	highcharts.src.js:11923
H.each	@	highcharts.src.js:1605
H.Tooltip.getAnchor	@	highcharts.src.js:11922
H.Pointer.runPointActions	@	highcharts.src.js:12784
H.Pointer.onContainerMouseMove	@	highcharts.src.js:13165
container.onmousemove	@	highcharts.src.js:13255

**Comment by TorsteinHonsi** [comment]
It's a regression in v5.0.10. Fails since https://github.com/highcharts/highcharts/commit/0501f4c20.

**Comment by jon-a-nygaard** [comment]
Fixed since v5.0.12. Commit which fixes issue is 5c3ab4f
