### ISSUE TITLE
X-axis label disappears with timezoneOffset

### ISSUE THREAD

**Issue by Sydney-o9** [highcharts/highcharts#6636]
#### Expected behaviour

X-Axis datetime(s) should be labeled when timezone negative with multiple axis

#### Actual behaviour

X-Axis datetime(s) is not labeled when timezone negative with multiple axis.

#### Live demo with steps to reproduce

Demo which shows x-axis correctly labeled when `timezoneOffset = 0`
[WORKING DEMO](http://jsfiddle.net/ezczk0mp/3/)

Demo which shows x-axis NOT correctly labeled when `timezoneOffset = -3 *60`
[NON WORKING DEMO](http://jsfiddle.net/ezczk0mp/)

**Comment by pawelfus** [comment]
Hi @Sydney-o9 

Thank you for this report. Both demos are the same, but I assumed that the first one shouldn't have `timezoneOffset`. These are the results:

- without timezone:
![screen shot 2017-04-24 at 17 54 06](https://cloud.githubusercontent.com/assets/1453926/25346120/0b59d31c-2917-11e7-9787-033da74bd174.png)

- with timezone:
![screen shot 2017-04-24 at 17 54 00](https://cloud.githubusercontent.com/assets/1453926/25346136/18b055a4-2917-11e7-8784-307e65209ea9.png)

Tested with OSX + Chrome.

**Comment by Sydney-o9** [comment]
Hi @pawelfus,

Sorry, I have updated the jsfiddle, but still have the same issues, tested in:
- Chrome 57.0.2987.133
- Firefox 52.0.2
- Safari 10.1

- <kbd>Without</kbd Timezone

Demo which shows x-axis correctly labeled when `timezoneOffset = 0`
[WORKING DEMO](http://jsfiddle.net/ezczk0mp/3/)

<img width="527" alt="screen shot 2017-04-25 at 2 17 19 am" src="https://cloud.githubusercontent.com/assets/1480617/25347294/c438753c-295d-11e7-8c46-db8bf7806a3b.png">

- <kbd>With</kbd Timezone
Demo which shows x-axis NOT correctly labeled when `timezoneOffset = -3 *60`
[NON WORKING DEMO](http://jsfiddle.net/ezczk0mp/)

<img width="525" alt="screen shot 2017-04-25 at 2 17 26 am" src="https://cloud.githubusercontent.com/assets/1480617/25347295/c5e9f4d2-295d-11e7-9754-efabd8081db4.png">

**Comment by Sydney-o9** [comment]
@pawelfus, just a quick heads up, it seems to be due to the width of the chart... which is why we both get different results. You can see what I mean if you change the window width in your fiddle.

However, without `timezoneOffset`, that issue does not exist and the chart width does not matter.

<img width="1091" alt="screen shot 2017-04-25 at 2 33 23 am" src="https://cloud.githubusercontent.com/assets/1480617/25347887/ba0b3336-295f-11e7-8965-d71532173b88.png">

<img width="1098" alt="screen shot 2017-04-25 at 2 33 08 am" src="https://cloud.githubusercontent.com/assets/1480617/25347889/bd8d3694-295f-11e7-9ac4-859eadc417d2.png">

**Comment by pawelfus** [comment]
Thank you for the updates!

Demo with fixed width: http://jsfiddle.net/ezczk0mp/6/

**Comment by Sydney-o9** [comment]
Nice - thank you so much @pawelfus for looking into this.

**Comment by TorsteinHonsi** [comment]
It's a regression in v5.0.8, fails since 1e0903c2
