### ISSUE TITLE
Zoom on touch screen with inverted chart causes plot to go out of plot area while stretching the before-zoom view

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6638]
#### Expected behaviour
As in not inverted chart - a plot area acts as a clipping rectangle limiting chart's plot while it is being stretched during zooming.

#### Actual behaviour
Series plot goes out over whole SVG.

#### Live demo with steps to reproduce
http://jsfiddle.net/ezfsp4k3/3/

Steps:
1) on a touch screen: zoom in - pinch open
2) series plot goes out of the plot area

#### Affected browser(s)
Tested:
- Chrome 57/Android 6.0.0
- Safari on iPhone 7

**Comment by TorsteinHonsi** [comment]
[This code block](https://github.com/highcharts/highcharts/blob/v5.0.10/js/parts/TouchPointer.js#L99-L102) looks a bit strange - maybe we're missing coordinates for inverted cases.
