### ISSUE TITLE
Tooltip format with useHTML error in Highmaps while drilldown and drillup

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#6640]
#### Live demo with steps to reproduce

http://jsfiddle.net/00kuw6py/

steps to reproduce

1. before drilldown

![snipaste_20170426_105040](https://cloud.githubusercontent.com/assets/6829290/25416027/1de125e6-2a6e-11e7-82af-f9167b986c37.png)

2. drilldown by click map area

2. click drillup button and see content show in tooltip

![snipaste_20170426_105116](https://cloud.githubusercontent.com/assets/6829290/25416022/1a6a4898-2a6e-11e7-98cc-0ed67e8b844a.png)

**Comment by pawelfus** [comment]
Hi @zhy1stgg 

Thank you for reporting this! It's already fixed on the master branch: http://jsfiddle.net/00kuw6py/3/ and fix will be included in the next release.
