### ISSUE TITLE
Charts failing to load in 5.0.10 with JS TypeError: Cannot read property 'getPlotBandPath' of undefined

### ISSUE THREAD

**Issue by goodforenergy** [highcharts/highcharts#6641]
#### Expected behaviour

Charts load without JS error.

#### Actual behaviour

Charts fail to load with JS error ```highcharts.js:23873 Uncaught TypeError: Cannot read property 'getPlotBandPath' of undefined```

<img width="1440" alt="screen shot 2017-04-26 at 3 02 45 pm" src="https://cloud.githubusercontent.com/assets/1276346/25416964/12bf833e-2a95-11e7-94a3-fda8c7b7821b.png">

<img width="855" alt="screen shot 2017-04-26 at 3 03 16 pm" src="https://cloud.githubusercontent.com/assets/1276346/25416978/1ddfaa50-2a95-11e7-9efb-371856bfbeb3.png">

<img width="1440" alt="screen shot 2017-04-26 at 3 07 13 pm" src="https://cloud.githubusercontent.com/assets/1276346/25416992/29f00786-2a95-11e7-8848-0335c9b2f8d1.png">

#### Live demo with steps to reproduce

I'm afraid I've been unable to reproduce in a JSFiddle. Our app uses a lot of Highcharts charts, all of which work fine in 5.0.9. This same error seems to be stopping all of our Highcharts charts from loading.

Here's the configuration for one affected chart, if it's any help:

```
{
  "chart": {
    "zoomType": "x"
  },
  "legend": {
    "enabled": false
  },
  "xAxis": {
    "minTickInterval": 1,
    "labels": {},
    "title": {},
    "plotBands": []
  },
  "yAxis": {
    "min": 0,
    "title": {
      "text": "Title"
    },
    "plotLines": [{
        "color": "#1a567d", "width": 2, "value": 0, "dashStyle": "ShortDot", "zIndex": 10
      }]
  },
  "plotOptions": {
    "area": {
      "stacking": "normal"
    },
    "areaspline": {
      "stacking": "normal",
      "fillOpacity": 1
    },
    "column": {
      "stacking": "normal"
    }
  },
  "tooltip": {
    "shared": true
  },
  "series": [
    {
      "name": "Series one",
      "type": "spline",
      "data": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      "color": "#09a1de",
      "events": {}
    },
    {
      "name": "Series two",
      "band": "band",
      "type": "arearange",
      "data": [
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]
      ],
      "color": "#09a1de",
      "events": {}
    }
  ]
}
```

#### Affected browser(s)

All tested.

**Comment by sebastianbochan** [comment]
I recreated your chart as live demo (http://jsfiddle.net/bm33s2wm/) but unfortunately was not able to replicate your issue. Could you simplify your chart and update my code with yours to introduce the problem? It will allow us to debug and find a reason.

**Comment by goodforenergy** [comment]
Hi @sebastianbochan. I was able to reproduce the bug by adding some settings - see http://jsfiddle.net/bm33s2wm/1/. 

It seems adding a background property to the pane setting is enough to trigger the bug.

**Comment by sebastianbochan** [comment]
_Internal note_
Fails since https://github.com/highcharts/highcharts/commit/a392661ebb4c4b1f558923412cc643d7327386ec
