### ISSUE TITLE
Legend backgroundColor and width properties are not compatible

### ISSUE THREAD

**Issue by gatapia** [highcharts/highcharts#6642]
#### Expected behaviour
Setting the legend: width and backgroundColor properties should respect both values.

#### Actual behaviour
Only width is correctly applied

#### Live demo with steps to reproduce

Simple jsfiddle here:
http://jsfiddle.net/d8uqh5p3/

#### Affected browser(s)
Tested only in chrome, assume all browsers affected

**Comment by sebastianbochan** [comment]
According to [docs](http://api.highcharts.com/highcharts/legend.width), the width should be number not value in percents.
