### ISSUE TITLE
bug: highstock plotbands for one x-axis copied to all other x axes

### ISSUE THREAD

**Issue by mhwlng** [highcharts/highcharts#6644]
see example :

http://jsfiddle.net/s01ew96z/1/

each series has their own x-axis
plotbands are only defined for the first x-axis
but show on the others as well

**Comment by sebastianbochan** [comment]
_Internal note_
A few extra examples:
- http://jsfiddle.net/sLdse5o4/ offset does not move plotbands (HC and HS)
- http://jsfiddle.net/qoe2bp1r/ top fix the issue but only in HC not in HS (http://jsfiddle.net/mhh9sphv/)

**Comment by pawelfus** [comment]
Demos from #8630 : 

#### Expected behaviour
Plot lines should look like in Highcharts: http://jsfiddle.net/BlackLabel/dLkcm1bh/

#### Actual behaviour
Plot lines occupy the entire height of plot area: http://jsfiddle.net/BlackLabel/8dhL90st/
