### ISSUE TITLE
Bug with legend titles not wrapping on two lines after chart is clicked

### ISSUE THREAD

**Issue by elfia** [highcharts/highcharts#6646]
#### Expected behaviour
Long titles should wrap on two lines no matter if chart has been clicked

#### Actual behaviour
Longer titles overflow and hide other legend titles

#### Live demo with steps to reproduce
1. Run the fiddle, click the title of any metric to hide it. 
2. Click the Update series button, the text of first metric label stands over the text of second metric 

http://jsfiddle.net/elfi/LLExL/7433/

#### Affected browser(s)
Chrome, Version 57.0.2987.133 (64-bit)

**Comment by sebastianbochan** [comment]
Thank you for the reporting.

**Comment by TorsteinHonsi** [comment]
What makes this hard is that it doesn't always happen - I need to repeat the steps over and over, and sometimes it fails...

**Comment by pawelfus** [comment]
It looks like mouseover + mouseout cause the issue, demo: http://jsfiddle.net/LLExL/7449/

**Comment by sebastianbochan** [comment]
_Internal note_
The issue is caused by useHTML parameter, when is disabled, all works properly.
