### ISSUE TITLE
Boost keeps redraw even with series.setVisible sets redraw to false

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#6648]
boost version 5.0.9

Actually Im having two problems: 

1. Calling series setVisible with second argument set to false, do fires immediate redraw. see code here totally ignores the second argument (boost module line 2600)
`wrap(Series.prototype, 'setVisible', function(proceed, vis) {
            proceed.call(this, vis, false);
            if (this.visible === false && this.ogl && this.canvas && this.image) {
                this.ogl.clear();
                this.image.attr({
                    href: ''
                });
            } else {
                this.chart.redraw();
            }
        });
`

2. I have set the boost module thresholds so high and indeed isSeiresBoosting or isChartSeriesBoosting both return false, and even then the boost wrap for setVisible keeps firing

**Comment by jberrydev** [comment]
This exists in 5.0.14 as well.  Experiencing redraw with setVisible on series even with second false param.  Any temporary work around?

**Comment by jberrydev** [comment]
I just removed boost from my package and seems to have fixed the performance issues.  Odd. Thanks for the good work though guys.  I will check back for a fix.
