### ISSUE TITLE
Arearange series has no zoom animation when its length is greater than 8

### ISSUE THREAD

**Issue by samirelanduk** [highcharts/highcharts#6651]
#### Expected behaviour

I have a line series and an arearange series, with the arearange series overlapping the line series (it represents the error of the line series. The chart has xy zoom, and I would expect that zooming does so with an animation, which is what happens when there is only a line series.

#### Actual behaviour

There is no zoom animation. Bizarrely, there *is* an animation if the length of the arearange series is 8 or less, but *not* if it is greater than 8.

#### Live demo with steps to reproduce
http://codepen.io/samirelanduk/pen/eWgdZN

#### Affected browser(s)
Chrome, Safari, Firefox

**Comment by morganfree** [comment]
It looks like it is an undocumented default limit for the zoom animation. https://github.com/highcharts/highcharts/blob/master/js/parts/Interaction.js#L385

If the number of the points is higher than 99, set `chart.animation = true`
https://jsfiddle.net/sLw7qter/

**Comment by samirelanduk** [comment]
It looks like you are correct! Adding `animation: true` to the chart object has restored animation, with over 100 data points.

Thanks a lot for your help.
