### ISSUE TITLE
Display ticks on top of gauge chart

### ISSUE THREAD

**Issue by LandonSchropp** [highcharts/highcharts#6652]
#### Expected behaviour

I'm trying to create a gauge chart that looks like this:

![gauge chart](https://cloud.githubusercontent.com/assets/361591/25463056/5444e69c-2aa8-11e7-8aaa-26fdc9d4942e.png)

I would like the ticks to be displayed *on top* of the gauge's value like they are in the image.

#### Actual behaviour

I can't find a way to get the ticks to display on top of the chart. Am I missing a setting?

<img width="307" alt="screen shot 2017-04-26 at 5 50 04 pm" src="https://cloud.githubusercontent.com/assets/361591/25463130/dad9b444-2aa8-11e7-986a-2f9cb0bd009e.png">

#### Live demo with steps to reproduce

http://jsfiddle.net/yodfc83r/1/

**Comment by sebastianbochan** [comment]
It is our bug tracker, so for the further support cases please use forum / stackoverflow / email. More information are available here: https://www.highcharts.com/support

ps. Use offset parameter and adapt outerRadius: http://jsfiddle.net/97mc3z7k/.

**Comment by LandonSchropp** [comment]
Thanks for the response, but that didn't really answer my question. I've created a new question on [StackOverflow](http://stackoverflow.com/questions/43664417/displaying-ticks-on-top-of-gauge-chart).
