### ISSUE TITLE
Solid gauges with rounded corners show 0 values as circles

### ISSUE THREAD

**Issue by goodforenergy** [highcharts/highcharts#6653]
I'm afraid I'm not quite sure what the best behaviour is here. We moved our solid gauges to using rounded corners instead of flat (which look super nice!), and noticed spurious values start appearing.

On closer inspection, these were values of 0, which were invisible when using flat edges, but render as a circle when using rounded corners.

There is a further limitation of rounded corners that you can't show very small values.. below a point they all just render as that same sized circle - but I guess this is an understandable limitation of this type of chart.

For 0 values though, perhaps no circle should show?

[Here](http://jsfiddle.net/dqohbuo0/2/)'s a fiddle showing the issue.

Thanks for your time :)

**Comment by TorsteinHonsi** [comment]
Thanks for writing (and sorry for accidentally closing)! Here's an interactive demo so we can see what happens with various values: http://jsfiddle.net/highcharts/dqohbuo0/4/

I'm also not sure what to do with this - currently the rounded edges are applied at the end of the _real_ data range. As can be seen in the demo above, when the square gauge stops at a certain tick, the rounded one actually goes past it. So there are some different ways of resolving this:

1. Keep the current behaviour, but hide the graphic on 0.
2. Keep the rounded edge within the actual data range, and when the width of the point becomes less than the rounding radius, the radius becomes less. In effect, it will start to squeeze as the value becomes closer to 0, and 0 will be invisible.

What do you think? @jon-a-nygaard @pawelfus

**Comment by pawelfus** [comment]
Hiding a graphic sounds easier, but will tooltip show up? It has `directTouch` set to true.

**Comment by TorsteinHonsi** [comment]
It's way easier, though not stricly correct, as 0 will give nothing and 0.00000001 will show a circular dot. The tooltip will probably not show unless we hide the element by setting the opacity to something very low.

**Comment by christian1koch** [comment]
I ran into this issue as well
