### ISSUE TITLE
Maps from SVG is not working anymore

### ISSUE THREAD

**Issue by ricardborras** [highcharts/highcharts#6654]
#### Expected behaviour
Page https://www.highcharts.com/studies/map-from-svg.htm should allow to load SVGs and convert to JSON

#### Actual behaviour
On loading, page shows several javascript errors and does not work (no preset loading, no custom map conversion). Errors are:

map-from-svg.htm:1 Mixed Content: The page at 'https://www.highcharts.com/studies/map-from-svg.htm' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-1.10.1.js'. This request has been blocked; the content must be served over HTTPS.
map-from-svg.htm:1 Mixed Content: The page at 'https://www.highcharts.com/studies/map-from-svg.htm' was loaded over HTTPS, but requested an insecure script 'http://code.highcharts.com/maps/1.0.4/highmaps.js'. This request has been blocked; the content must be served over HTTPS.
map-from-svg.htm:1 Mixed Content: The page at 'https://www.highcharts.com/studies/map-from-svg.htm' was loaded over HTTPS, but requested an insecure script 'http://github.highcharts.com/82c192d73/modules/data.src.js'. This request has been blocked; the content must be served over HTTPS.
map-from-svg.htm:1 Mixed Content: The page at 'https://www.highcharts.com/studies/map-from-svg.htm' was loaded over HTTPS, but requested an insecure script 'http://github.highcharts.com/82c192d73/modules/map-parser.src.js'. This request has been blocked; the content must be served over HTTPS.
map-from-svg.js:70 Uncaught ReferenceError: $ is not defined(anonymous function) @ map-from-svg.js:70

#### Affected browser(s)
Chrome, Firefox

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! Fixed by be8284cb7ddaf48a85142d4c42e80b4a7236a8fc. We will update the web server accordingly.

**Comment by Denyllon** [comment]
@TorsteinHonsi The problem appeared again.
We can see that after opening the [Map from SVG](https://www.highcharts.com/studies/map-from-svg.htm) converter does not work at all, and there are errors 404 in the console.
I see that our GitHub's CDN have problems to find references to the 82c192d73 commit put in the links.
https://github.com/highcharts/highcharts/blob/cdadc3f63bc47a4ec58b6a28bacc17cc438e96f9/studies/map-from-svg.htm#L9-L11

**Comment by TorsteinHonsi** [comment]
Thanks. This tool is quite hard to maintain, as it resides in the main highcharts repo and is uploaded to the website. I think we should host it in a different way. Probably the best option would be to use a separate repo and serve it in github pages. I'll have a look at it.

**Comment by TorsteinHonsi** [comment]
It's now moved to https://highcharts.github.io/map-from-svg

**Comment by Basts** [comment]
@TorsteinHonsi

Is it now the official link now? Could be share in the documentation?

https://www.highcharts.com/docs/maps/create-custom-maps-for-highmaps - subpoint #13

**Comment by TorsteinHonsi** [comment]
Yes. I have created a redirect from that page, but it is not active until the next release. But it is better to update the actual docs too.
