### ISSUE TITLE
Flag series with the showInNavigator property set to true throws ‘segmentPositions is undefined’ error

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6655]
#### Behaviour
In situation where more than one flag series present on a chart has set the showInNavigator property to true, the ‘TypeError: segmentPositions is undefined’ error is thrown. It only happens in Firefox and IE browsers. In Chrome it works without any problems.

#### Live demo
http://jsfiddle.net/ca86wvtt/

#### Affected browsers
Firefox, IE

**Comment by morganfree** [comment]
+1

Flags can be forced to be displayed in the navigator if `navigatorOptions.type` is set to flags.
http://jsfiddle.net/co8e4d0j/

**Comment by pawelfus** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Simplified demo: http://jsfiddle.net/highcharts/ca86wvtt/6/

Data grouping is required.
