### ISSUE TITLE
Wrong color of first and last datalabel [5.0.10]

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6657]
#### Expected behaviour
Display all datalabels in dark colour.
![screen shot 2017-04-28 at 15 36 50](https://cloud.githubusercontent.com/assets/19593179/25531009/8e4f73b2-2c28-11e7-9b47-c242fc265e5b.png)

#### Actual behaviour
First and last datalabels are coulored with white
![screen shot 2017-04-28 at 15 37 40](https://cloud.githubusercontent.com/assets/19593179/25531052/bebbdfb8-2c28-11e7-98d5-c92fa236773b.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/c1rcxn0r/ [5.0.10] - Issue
https://jsfiddle.net/c1rcxn0r/1 [5.0.9] - Works OK

**Comment by pawelfus** [comment]
Thank you for the report!

It's a regression from 27aff13

**Comment by fabscav** [comment]
This is still an issue as of v6.1.1. Are there any plans to fix this?

**Comment by pawelfus** [comment]
Could you try to set `black` color instead of `contrast`? See: https://jsfiddle.net/BlackLabel/c1rcxn0r/4/
