### ISSUE TITLE
Changing colorIndex does not update all styles

### ISSUE THREAD

**Issue by kaptajnen** [highcharts/highcharts#6660]
#### Expected behaviour
When clicking the link in the fiddle I would expect the line in the series to change color, but only the points do.

#### Actual behaviour
Only the points change color

#### Live demo with steps to reproduce
https://jsfiddle.net/uxsuk20n/

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied (with area and a nice animation :) https://jsfiddle.net/highcharts/uxsuk20n/2/

**Comment by kaptajnen** [comment]
Great! Thanks for fixing this.
