### ISSUE TITLE
Inverted columnrange ignores max extreme on datetime y-axis

### ISSUE THREAD

**Issue by mapeebles** [highcharts/highcharts#6661]
#### Expected behaviour
I need to explicitly set the extremes in a datetime columnrange chart, so I set the yAxis.min and yAxis.max.  This should limit the range to: Sat, 11 Jul 2015 00:00:00 GMT -> // Wed, 09 Nov 2016 00:00:00 GMT

#### Actual behaviour
The chart appears to ignore the yAxis.max value as the yAxis shows a range out to Jan 2017.

#### Live demo with steps to reproduce
https://jsfiddle.net/mpeebles/o6w8ycqb/

#### Affected browser(s)
Chrome v57.0.2987.133

**Comment by sebastianbochan** [comment]
The reason is that calculated tickInterval is over your max and extend it. The solution is using tickPositioner and prepare custom logic.

Example:
- https://jsfiddle.net/owt17qvx/
