### ISSUE TITLE
Things I have found with uglify and/or babili in a React project

### ISSUE THREAD

**Issue by nicolechung** [highcharts/highcharts#6662]
#### Expected behaviour

High charts should show up

#### Actual behaviour

Either the chart disappears entirely or the chart shows a flat line

#### Live demo with steps to reproduce
If do the following in my webpack builds the charts show up again

When using uglify, if I change the settings to this, my charts show up again:

```
new webpack.optimize.UglifyJsPlugin({
   mangle: {
      except: ['highcharts', 'react-highcharts']
   }
})
```

When using babili (as a webpack plugin) my charts show up again:

```
new BabiliPlugin({
        builtIns: false,
      })
```

It's hard to show a jsbin or fiddle (how do you minify in those??)

#### Affected browser(s)

Chrome

This is not exactly an issue but I thought I should share this in case these settings work for anyone else.

My setup is:
- webpack 2
- React (using React-highcharts)
- Redux

**Comment by sebastianbochan** [comment]
I guess that you use the plugin: https://github.com/kirjs/react-highcharts. If yes, unfortunately we are not authors of it and I advise you to report this bug in their repo.
