### ISSUE TITLE
Export / Download feature currently down / Error 520

### ISSUE THREAD

**Issue by nielsmarston** [highcharts/highcharts#6663]
#### Expected behaviour
Charts will download/export when clicking download

#### Actual behaviour
export.highcharts.com timing out and Reverting to error page code 520

Error 520 Ray ID: 357f62ca9a276fea • 2017-05-01 02:43:25 UTC
Web server is returning an unknown error

#### Affected browser(s)
All - tried on own charts and confirmed via HighCharts demo page

**Comment by sebastianbochan** [comment]
We have had temporary problems with the exporting server, but now all works properly. Please confirm that is correct also in your charts.

**Comment by nielsmarston** [comment]
Hello Sebastian,

Export function of the charts does indeed work now; thanks for 
investigating and fixing.

Cheers,

- Niels

Niels Marston
OPA Systems Manager
Franchise Operator Management
Telephone 03 9027 5053
Mobile 0418 507 325
Email niels.marston@ptv.vic.gov.au
 
Part of Transport For Victoria

For more information visit ptv.vic.gov.au
Twitter | YouTube | Live travel updates

**Comment by pawellysy** [comment]
Hello @drichard1989, it does work for me. Could you share the demo, where the issue occurs so that we can search for the problem's origin? Thanks!
