### ISSUE TITLE
Heatmap + boost.js + no-data-to-display.js + some data = some data + no data to display

### ISSUE THREAD

**Issue by yoisel** [highcharts/highcharts#6664]
I am using heatmap with boost and the module no-data-to-display.js.
I am adding some partial data to my heatmap, my data shows up just fine, but the message "no data to display" is showing up as well.

#### Expected behaviour
When adding data to the heatmap, the message "no data to display" should be removed

#### Actual behaviour
The message "no data to display" is showing up together with the data

#### Live demo with steps to reproduce
https://jsfiddle.net/63u7qtmk/

#### Affected browser(s)
Tested on:
-Chrome 58 + Windows 10
-MS Edge

#### Fix proposal:
Inside no-data-to-display,js I changed the line:

```
each(['pie', 'gauge', 'waterfall', 'bubble', 'treemap'], function(type) { 
    if (seriesTypes[type]) { // ...
```

into

```
each(['pie', 'gauge', 'waterfall', 'bubble', 'treemap', 'heatmap'], function(type) {
    if (seriesTypes[type]) { // ...
```

This seems to fix the issue.

**Comment by TorsteinHonsi** [comment]
Sorry for the late reply, and thanks for pointing to the problem.
