### ISSUE TITLE
Relaoding a column-graph in IE11 causes an error "Die Eigenschaft "querySelectorAll" eines undefinierten oder Nullverweises kann nicht abgerufen werden."

### ISSUE THREAD

**Issue by dwittenb** [highcharts/highcharts#6666]
#### Expected behaviour
relaoding an column-graph must not create an error

#### Actual behaviour
Running in IE11 there is an error if the chart is reloaded. The reload is made with first destroy() and then create an nw chart.

The error occures at line 3644 of highcharts.src.js:

```
3643                      each(
3644                            wrapper.element.ownerSVGElement.querySelectorAll('[clip-path]'),
3645                            function (el) {
3646                                if (el.getAttribute('clip-path')
3647                                        .indexOf(wrapper.clipPath.element.id) > -1) {
3648                                    el.removeAttribute('clip-path');
3649                                }
3650                            }
3651                        );
3652                        wrapper.clipPath = wrapper.clipPath.destroy();
```
In debugger i found, that the `wrapper.element.ownerSVGElement` is null.

I patched the code, to test if `wrapper.element.ownerSVGElement` is null, but it is just a hack, that simply works:

```
                      if (wrapper.element.ownerSVGElement !== null) {  // patch
3643                      each(
3644                            wrapper.element.ownerSVGElement.querySelectorAll('[clip-path]'),
3645                            function (el) {
3646                                if (el.getAttribute('clip-path')
3647                                        .indexOf(wrapper.clipPath.element.id) > -1) {
3648                                    el.removeAttribute('clip-path');
3649                                }
3650                            }
3651                        );
3652                        wrapper.clipPath = wrapper.clipPath.destroy();
                     }      // patch
```

#### Affected browser(s)
IE 11

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Based on your description I set up [this live demo](http://jsfiddle.net/6s5ze6oe/), but I don't see any problem in IE11. I also tried with version 5.0.10, but there is no error either.

Please let us know if you have a live demonstration, or can alter the jsFiddle to display the bug.

**Comment by TorsteinHonsi** [comment]
Anyway, it is probably fixed with https://github.com/highcharts/highcharts/issues/6643. I'm closing this, please feel free to reopen it if you can still reproduce the issue.
