### ISSUE TITLE
Flags moving to axis when data out of time order

### ISSUE THREAD

**Issue by mykbaker** [highcharts/highcharts#6667]
#### Expected behaviour
When Flags are given a valid x value and onSeries, they always appear on the series.

#### Actual behaviour
If the points are out of time order, some flags end up on the axis

#### Live demo with steps to reproduce
http://jsfiddle.net/mykbaker/cg8pgp70/

#### Affected browser(s)
IE11 and Chrome tested

**Comment by pawelfus** [comment]
Hi @mykbaker 

Highstock requires data to be sorted ascending. In the JS console you can see errors:
> Highcharts error #15: www.highcharts.com/errors/15

Which leads to:
> Highcharts Error #15
>
> Highcharts expects data to be sorted
>
> This happens when you are trying to create a line series or a stock chart where the data is not sorted in ascending X order. For performance reasons, Highcharts does not sort the data, instead it is required that the implementer pre-sorts the data.
