### ISSUE TITLE
chart.style.fontSize option is not working for data labels , xaxis labels and legends text

### ISSUE THREAD

**Issue by Ramyani** [highcharts/highcharts#6668]
I have added chart.style.fontSize as '30px' but the changes are not getting reflected in the chart for data labels , x axis labels and legend texts
http://jsfiddle.net/r4nckaj3/8/

**Comment by TorsteinHonsi** [comment]
Thanks for writing! Those elements have their own font sizes defined elsewhere in the options structure, so they have to be defined specifically: http://jsfiddle.net/highcharts/r4nckaj3/9/

PS: for general tech support, please see www.highcharts.com/support.
