### ISSUE TITLE
Funnel chart doesn't hide point, sets height off/intersecting legend

### ISSUE THREAD

**Issue by schneckentempo** [highcharts/highcharts#6670]
#### Expected behaviour
When having a datapoint with `visible: false`, the chart shouldn't show the datapoint anymore

#### Actual behaviour
Point gets appended on the bottom and also intersecting the legend. Click events still possible

#### Live demo with steps to reproduce
http://jsfiddle.net/c3uy5z3g/

**Comment by sebastianbochan** [comment]
This is default functionality also for i.e pie chart so its not a bug.

@TorsteinHonsi could you comment it?

**Comment by schneckentempo** [comment]
it is possible to set the type in this fiddle to pie with the exact same series data and everything is working fine
