### ISSUE TITLE
Wrong series name for multiple series column click event

### ISSUE THREAD

**Issue by varaprashanthm** [highcharts/highcharts#6672]
#### Please check the jsfiddle, 
for the same column click everytime it'll show different series name

[http://jsfiddle.net/ah5szctp/](url)

**Comment by TorsteinHonsi** [comment]
Thanks for reporting. However, I am unable to reproduce it. Open http://jsfiddle.net/ah5szctp/ and click the tallest column several times. Every time it alerts "Sep-Tokyo". I'm using Chrome on Mac. 

Is there anything else we need to know to reproduce your problem?

**Comment by varaprashanthm** [comment]
Thanks for your reply,this issue got resolved with the new version  v5.0.11 (2017-05-04). Now its working fine for me as well.
