### ISSUE TITLE
Pie chart not exporting with labels [Styled by CSS]

### ISSUE THREAD

**Issue by rbeasse** [highcharts/highcharts#6680]
#### Expected behaviour
When exporting a pie chart I should also see the labels on the side.

#### Actual behaviour
Chart is exporting without the labels.

#### Live demo with steps to reproduce
Here is the example pie chart you provide
http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/css/colors/

#### Affected browser(s)
Chrome 58

We had no issues on 5.0.7 - this issue must have occurred after that.

**Comment by rbeasse** [comment]
This seems to be directly related to the opacity transition you added to .highcharts-data-labels

https://github.com/highcharts/highcharts/commit/223e1e025252422f7030666b3a9f93e01809b3bf

**Comment by oysteinmoseng** [comment]
Fixed in latest dev code: http://jsfiddle.net/5ru2wr2n/
