### ISSUE TITLE
Heatmap Legend Does Not Render in PDF

### ISSUE THREAD

**Issue by earllee** [highcharts/highcharts#6681]
#### Expected behaviour
After downloading a heatmap as a PDF, the legend should appear.

#### Actual behaviour
After downloading a heatmap as a PDF and opening it in Safari, Preview, Chrome, and Acrobat Reader the legend does NOT appear.

#### Live demo with steps to reproduce
1. Visit: https://www.highcharts.com/demo/heatmap
2. Click the hamburger icon (options menu).
3. Click "Download as PDF".
4. Open downloaded PDF with Safari or Mac OS X Preview.

#### Affected browser(s)
- Safari
- Mac OS X Preview
- Chrome
- Adobe Acrobat Reader

#### Screenshots
<img width="1920" alt="highcharts-heatmap-problem" src="https://cloud.githubusercontent.com/assets/2468620/25720718/e0854f82-30db-11e7-843d-697db1d76e2e.png">

**Comment by yoisel** [comment]
I just tried this with chrome (linux) and it worked fine for me. Maybe it's really specific to Mac OS X

**Comment by Aidurber** [comment]
Tested on Chrome (Windows), works fine for me.

**Comment by pawelfus** [comment]
That's .. interesting. You are right, it's issue specific to OSX previews (and Safari). Exported image:
[chart (21).pdf](https://github.com/highcharts/highcharts/files/983244/chart.21.pdf)

Opening the same file on different machines and browsers is fine. Acrobat reader works fine for me too. I was able to reproduce issue only with:

- opening PDF directly in Safarai (v 9.1.1)
- OSX preview

**Comment by yoisel** [comment]
@pawelfus  @earllee I looked at the internal structure of the PDF file, and I noticed that it uses a PDF structure called "shading pattern", I know for a fact that this PDF feature is not well supported by OSX Preview, I saw a post about it in stackoverflow but I cannot find it now. Anyway, this kind of PDF struct is a bit problematic and many PDF viewers will not implement it properly. I would recommend to Highchart developers to avoid it if possible.

**Comment by pawelfus** [comment]
Thank you @yoisel for your effort! As I pointer out earlier, it looks like an issue in PhantomJS. I'm curious, is there any `caniuse` for PDF's?

**Comment by yoisel** [comment]
@pawelfus Not that I am aware of : )
But aiming at generating PDF-A1b compliant files could be a good start. They are not supposed to contain transparency/shading-related features if I remember correctly.

**Comment by TorsteinHonsi** [comment]
As [Headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) is coming up, we may have to [abandon PhantomJS soon](https://groups.google.com/forum/#!msg/phantomjs/9aI5d-LDuNE/5Z3SMZrqAQAJ).

Loading the heatmap as SVG in Chrome and printing it to PDF correctly preserves the gradient. Which may indicate that once we move the export server to use Headless Chrome, the problem would be solved.
