### ISSUE TITLE
Highcharts Line Y Axis Range Rounding

### ISSUE THREAD

**Issue by chticer** [highcharts/highcharts#6682]
First of all, thank you to all the Highcharts contributors, maintainers, and supporters (and everyone else in the community) for this amazing library. It truly helps us in the organization make more informed decision and get more real-time data and visualizations out there.

I have been looking around for a while without any resolution on this issue I am having. I am creating a basic line chart such that I would like to round the y axis values to the nearest tenth value as well as always have 6 y axis labels appear that is distributed evenly between the minimum and maximum y axis values specified. This issue is not always reproducible though, depending on the min, max, and tickInterval y axis values.

I use a formula in my project but I have hard coded the exact same values, produced from console.log in the project and to make sure that the values were returning correctly as expected, in order to show this issue and is included in each JSFiddle provided.

Any insights would be greatly appreciated.

#### Expected behaviour
Y axis values that are displayed should always be divisible by 10 evenly and should always be no less than the maximum value in the data series and no more than the minimum value in the data series.

#### Actual behaviour
Certain y axis values subtract some percentage points to the minimum and maximum value specified.

[1] Reproducible Y Axis Values:
- min: 0.7, max: 1, tickInterval: 0.06, data[2][1]: 0.7291666666666666 (default JSFiddle)
- min: 0.6, max: 1, tickInterval: 0.08, data[2][1]: 0.6291666666666666
- min: 0.7, max: 1, tickInterval: 0.06, data[2][1]: null

Reproducible values causes y axis minimum and maximum values to display 4 percentage points lower than the specified y axis minimum and maximum values.

[1] Non-reproducible (correct, expected output) Y Axis Values:
- min: 0.5, max: 1, tickInterval: 0.1, data[2][1]: 0.5291666666666666
- min: 0.8, max: 1, tickInterval: 0.04, data[2][1]: null, data[3][1]: null
- min: 0.9, max: 1, tickInterval: 0.02, data[0][1]: null, data[1][1]: null, data[2][1]: null, data[3][1]: null

[2] Reproducible Y Axis Values:
- min: 0.3, max: 0.7, tickInterval: 0.08, data[2][1]: 0.375 (default JSFiddle)
- min: 0.4, max: 0.7, tickInterval: 0.06, data[2][1]: 0.475
- min: 0.4, max: 0.7, tickInterval: 0.06, data[2][1]: null

Reproducible values causes y axis minimum and maximum values to display 4 or 6 percentage points lower than the specified y axis minimum and maximum values.

[2] Non-reproducible (correct, expected output) Y Axis Values:
- min: 0.2, max: 0.7, tickInterval: 0.1, data[2][1]: 0.275

It seems that tickIntervals between 0.06 and 0.08, inclusive, replicates this issue whereas tickIntervals less than 0.06 or more than 0.08 does not replicate this issue.

#### Live demo with steps to reproduce

https://jsfiddle.net/4wgd5ry4/ (for use in reproducible/non-reproducible case [1] above)
https://jsfiddle.net/q8twLqd0/1/ (for use in reproducible/non-reproducible case [2] above)

#### Affected browser(s)
Google Chrome Version 57.0.2987.133 (64-bit)
Microsoft Edge 38.14393.1066.0 Microsoft EdgeHTML 14.14393

**Comment by TorsteinHonsi** [comment]
Thanks for writing! The problem actually is not a Highcharts bug, but related to how floats are calculated in JavaScript. Try to run `console.log(0.56 * 100);` in your browser and you'll see what I mean. 

You can fix your label formatter by rounding off the calculated number: http://jsfiddle.net/highcharts/q8twLqd0/2/

**Comment by chticer** [comment]
Thank you for responding. I understand that issue as I use a round function in my code to fix that issue and was already incorporated in my project before I posted this issue. That was not the issue I was referring to, which is why I intentionally left out the label formatter. The issue is the range calculation itself.

Taking that JSFiddle example, I have set the minimum to be 0.3, maximum to be 0.7, and tickInterval to be 0.08. This in theory should produce a range starting from 0.3 to 0.7 with 0.08 increments per tick in the axis, which means it should produce these values (after formatting): [30%, 38%, 46%, 54%, 62%, 70%]. However, it is producing the following values (after formatting with console.log(Math.round(this.value * 100) + "%") in the label formatter function): [24%, 32%, 40%, 48%, 56%, 64%].

It seems the tickInterval is working properly but it is completely ignoring the minimum and maximum values, even though I have no data that is outside the minimum and maximum range. I also tried using tickAmount = 6 instead of calculating the tickInterval and it produces the same result so the tickAmount and tickInterval does not seem to cause this issue at all. Even tried setting startOnTick = false as well but that had no effect.

**Comment by pawelfus** [comment]
@chticer - thank you for your feedback. I think maybe a short explanation what happens could help:

`min` and `max` options set extremes on an axis, but doesn't mean the first tick on the axis will start exactly in this place. That can be observed when setting `startOnTick` and `endOnTick` to false, please take a look: https://jsfiddle.net/4wgd5ry4/2/ In other words, with a given `tickInterval` and `min`/`max`, Highcharts algorithm decides to not use `min` as the first tick. 

Labels are calculated as **multiples** of tickInterval. For example: tickInterval=0.06, for <0.7, 1.0> range, we will have first tick at.. 0.66 (11x0.06). It would be nice to start calculating ticks from `min`, but it will work only for a certain cases, for example in your case (`min`, `max,` tickInterval` are set and perfectly utilizes available space), but all other cases could fail (where extremes are auto-calculated, especially when adding all other options, like `minPadding`, `floor` etc. ).

**Ok, so what now?**
You have two options to change this behaviour. It depends how flexible your solution needs to be:

1) You can define `tickPositions` per chart. For example: https://jsfiddle.net/4wgd5ry4/ - if you have some basic charts and you want exactly that look&feel, you can use this. You need to calculate/set manually that array.
2) You can use `tickPositioner`. This options can be defined as an external function, shared across all of the charts. It's more universal and let's you define where Highcharts should render ticks, for example, if I'm right, this is the result you expect: https://jsfiddle.net/4wgd5ry4/5/

@TorsteinHonsi please correct me if I'm wrong somewhere.

**Comment by chticer** [comment]
Thank you both for your help. The explanation was helpful and now I understand the functionality of Highcharts axis extremes. `tickPositioner` is definitely what I was looking for but had a hard time finding it due to my lack of knowledge in the API and did not really encounter the use of it that much while searching for a solution. I can acknowledge that this issue is not a bug, no further support will be needed regarding this, and a resolution has been reached.
