### ISSUE TITLE
Scrollbar not working in Bar Chart

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6683]
#### Expected behaviour
Scrollbar should work correctly in Bar Chart.

#### Actual behaviour
Scrollbar is not rendered correctly in Bar Chart and disappears when scrolled to bottom.

#### Live demo with steps to reproduce
http://jsfiddle.net/baefy0uv/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thanks for the report!

Workaround: define `scrollbar` on xAxis level: http://jsfiddle.net/baefy0uv/1/
