### ISSUE TITLE
[Highmaps] Shifted legend from the corner

### ISSUE THREAD

**Issue by piotrbarandeveloper** [highcharts/highcharts#6686]
#### Expected behaviour
The legend should appear at the corner.

#### Actual behaviour
The legend is shifted from the corner. This happens when my application includes the heatmap module. In the application I use both the map module and the heatmap module.

#### Live demo with steps to reproduce

http://jsfiddle.net/m9318og1/10/ (with heatmap module)
http://jsfiddle.net/m9318og1/9/ (without heatmap module)

#### Affected browser(s)
Chrome 58.0.3029.96 (64-bit)
Firefox 53.0
Edge 38.14393.1066.0

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

Heatmaps are included in Highmaps, so there is no need to include both.

**Comment by larrydahooster** [comment]
I am getting this error with the following modules I use: 

```
import Highcharts from 'highcharts';
import highchartsFunnel from 'highcharts/modules/funnel';
import highchartsMore from 'highcharts/highcharts-more';
import highchartsSolidGauge from 'highcharts/modules/solid-gauge';
import highmaps from 'highcharts/modules/map';


highchartsMore(Highcharts);
highchartsFunnel(Highcharts);
highchartsSolidGauge(Highcharts);
highmaps(Highcharts);
```

I am getting the error cause both `highcharts-more` and `map` add the series type 'bubble' and 'scatter'. How am I supposed to get rid of the error, when I need both modules, but they are using overlapping seriesTypes?

**Comment by TorsteinHonsi** [comment]
I'm sorry, you're right. We didn't anticipate this. Since the error message is not critical (just meant for guidance), I'll remove it.
