### ISSUE TITLE
Wrong Hover/Highlight(Selection) on Charts

### ISSUE THREAD

**Issue by dragoshzava** [highcharts/highcharts#6687]
#### Description
This happens when hovering over last serie, highcharts selects wrong points.

#### Expected behaviour
Highcharts should select an entire column with all points.

#### Actual behaviour
Highcharts selects points from different columns

#### Live demo with steps to reproduce
http://jsfiddle.net/Resems/m23omt3r/1/

Image attached, hovering last Column, lowest points, selects nearby Column, so the end result is awkward, selection is : 3 point from 7 jan, and other points from 8 jan.

![image](https://cloud.githubusercontent.com/assets/3819194/25739277/840c876a-3181-11e7-9c28-b213822679c4.png)

**Comment by PedroSolintel** [comment]
Same error happens here, with an additional bug: not only the hovering goes wrong, but the highlighting too. See http://jsfiddle.net/rrtwfv4m/

How to reproduce the highlighting bug:

1. Put the mouse over '**Jan**' category.
2. **May's** orange column will highlight.

How to reproduce the wrong hovering bug:

1. Slowly move your mouse back and forth over the base of the columns.
2. You'll notice strange behaviors on the following categories: **Feb**, **Apr**, **Jun**, **Jul**, **Sep** and **Oct**.

**Comment by pawelfus** [comment]
Thank you for reporting this issue. It's a regression, in 5.0.10 examples work fine:

- http://jsfiddle.net/m23omt3r/2/
- http://jsfiddle.net/c0fbL8vb/1/

Regression from 13cfbe1 commit.

**Comment by dragoshzava** [comment]
Hey, unfortunately with 5.0.10 i could still repro 
http://jsfiddle.net/m23omt3r/3/
![image](https://cloud.githubusercontent.com/assets/3819194/25804937/f64565d0-33fd-11e7-93b7-62c0a23b2f03.png)
in this attached picture, the hover is over **living room** column, but the info is displayed from **kitchen**.
you can repro by moving the mouse from under the living room column.

But with 5.0.9 works, attached fiddle.
http://jsfiddle.net/m23omt3r/4/

**Comment by PedroSolintel** [comment]
At first I thought that the bug persisted, because I regressed my `highcharts.js` to v5.0.10 and was still facing the same issues. It turned out that I was supposed to update every module as well (modules were a little bit outdated). Changed everything to version 5.0.10 and then everything started to work fine.

So for other people who might have the same problem: you should upgrade (or downgrade) every module as well, otherwise the bug will remain there.

Thanks for the help!

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard This needs priority.

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi Yes, currently working on it. Not yet found the cause of problem.

**Comment by jon-a-nygaard** [comment]
_Internal Note: [Simplified demo](http://jsfiddle.net/jon_a_nygaard/m23omt3r/6/)_

**Comment by jon-a-nygaard** [comment]
**Potential workaround**
Here's an example of a [potential workaround](http://jsfiddle.net/jon_a_nygaard/m23omt3r/7/). Unfortunately it is not very compact, so I will see if there an better alternative.

**Comment by MiroLiska** [comment]
Something is completely wrong now. I must hover with the mouse directly over the data point. Before, I could hover with the mouse anywhere over the data point, the tooltip would come. See http://jsfiddle.net/cjsnxj4x/3/ 
![wrongtooltip](https://cloud.githubusercontent.com/assets/23024867/26298299/10222b3a-3ed7-11e7-86c3-7bf9c0aadfd3.png)

versus http://jsfiddle.net/cjsnxj4x/2/ (version 4.2.3)

**Comment by MiroLiska** [comment]
Another bug found - with scatter charts using shared tooltips. See http://jsfiddle.net/773sz6Lv/1/ - move the mouse over the blue part of the point 1269 -  the shared tooltip from market value does not appear.
![ig1](https://cloud.githubusercontent.com/assets/23024867/26311037/27e202a0-3f03-11e7-96ae-c52d4aae29d8.png)

And now move the mouse up - the shared tooltip will eventually appear:
![ig2](https://cloud.githubusercontent.com/assets/23024867/26311068/3e9698b2-3f03-11e7-913d-77e18474c4b2.png)

**Comment by MiroLiska** [comment]
Just tested the issue above with freshly released 5.0.12 - it still persists :(
http://jsfiddle.net/773sz6Lv/2/

**Comment by sebastianbochan** [comment]
@jon-a-nygaard Could you verify it?

**Comment by jon-a-nygaard** [comment]
Not certain what excactly is causing that issue, currently looking into it.

**Comment by jon-a-nygaard** [comment]
The last issue is a similar but a different one from the original one in this topic. I will likely create a new issue to seperate these.
## Explanation
Caused by some series having the closest point to the mouse pointer on a different x value than the hovered point. Resulting in a [filter removing these points](https://github.com/highcharts/highcharts/blob/master/js/parts/Pointer.js#L224-L226), and too few points are passed to the tooltip.

## Potential Workaround
http://jsfiddle.net/jon_a_nygaard/773sz6Lv/3/

**Comment by MiroLiska** [comment]
Hi. The issue is not a show-stopper, take your time.
