### ISSUE TITLE
X Axis label not formatted when using timezoneOffset

### ISSUE THREAD

**Issue by dossorio** [highcharts/highcharts#6691]
When negative [timezoneOffset](http://api.highcharts.com/highcharts/global.timezoneOffset) is used, and one element is provided, the label in the x axis is not formatted

#### Expected behaviour
The label in the x axis should be formatted properly, `5 May` should be shown

#### Actual behaviour
The label is not formatted as expected and shows `1 493 942 400 000`

#### Live demo with steps to reproduce
http://jsfiddle.net/oo2jrv5b/5/
(Change timezoneOffset to 0 so you will see the date being formatted correctly)

#### Affected browser(s)
Chrome Version 57.0.2987.133 (64-bit) (Only checked in this one)

**Comment by pawelfus** [comment]
It is already fixed in 5.0.11 version, please take a look: http://jsfiddle.net/oo2jrv5b/6/
