### ISSUE TITLE
Boost module has bugs with graph dashstyle and marker symbols

### ISSUE THREAD

**Issue by mathiasconradt** [highcharts/highcharts#6692]
#### Expected behaviour

I enabled boost 

```
    boost: {
      useGPUTranslations: true,
      seriesThreshold: 0,
      boostThreshold: 0
    },
```

and configured the chart to have the following series plotOptions:

```
        dashStyle: 'dash',
        marker: {
          symbol: 'square'
        },
```

so I expected the markers to show as squares and the graph to be dashed.

#### Actual behaviour

The dashstyle of the graph is still solid and the markers show as circles. Only when hovering with the mouse over a point, the marker shows as square.

This is a problem with the boost module. If you remove the boost from the chart configuration, it works fine and the graph is dashed and the markers show as square at all times, not only when you hover over it.

#### Live demo with steps to reproduce
https://jsfiddle.net/fmfmxq9s/2/

#### Affected browser(s)

Test in Chrome latest version.

**Comment by sebastianbochan** [comment]
It looks like lineWidth parameter is ignored too.

**Comment by TorsteinHonsi** [comment]
There are several limitations to the rendering in the boost module compared to SVG rendering, for example markers will always be circles as noted in the head of the file. Once the module is officially launched, we'll compile a full list of limitations.

**Comment by TorsteinHonsi** [comment]
@cvasseng

**Comment by mathiasconradt** [comment]
@TorsteinHonsi Ok, thanks for the info. Understand. Not sure if you want to close this ticket and or not. Feel free to do so if it's not planned to support the mentioned issues as features in the boost module.

**Comment by pawelfus** [comment]
Marker symbols are supported since v6.2.0: https://jsfiddle.net/BlackLabel/2yo4b8p5/1/

Dash-style is still not supported, but has a separate ticket: #5264 

Closing the issue then.
