### ISSUE TITLE
3D frame hides the charts behind it

### ISSUE THREAD

**Issue by paulo-raca** [highcharts/highcharts#6694]
I'm having a weird z-order issue on the latest release o f Highcharts:
After the chart is redrawn, if the 3D frame is enabled, it is shown above the chart (if it is opaque, it effectively looks like the chart is empty).

As far as I can tell (Didn't test enough, though), it only affects 3D charts.

This is possibly a duplicate of #6693 -- That issue doesn't have enough details to be sure.

`git blame` points to b56caed / #5297.

#### Expected behaviour

Chart data is shown, the 3D frame is in the background

#### Actual behaviour

The 3D frame is above the chart contents. It effectively looks like the chart is empty

#### Live demo with steps to reproduce

My reproduction is the 3-D scatter plot demo, but with opaque walls: http://jsfiddle.net/zukduyfa/. 

Whenever you click "redraw", or rotate the chart using drag, the box is moved above the chart

#### Affected browser(s)

Tested on Chrome for Linux, v55.0.2883.87 (64-bit).
Probably affects all browsers.

**Comment by Izothep** [comment]
Thank you for reporting this issue. This problem was caused by changes in zIndex calculation algorithm for column series in 3D chart.

Looks to be solved by 653b4a0
Live demo: http://jsfiddle.net/zukduyfa/4/

**Comment by paulo-raca** [comment]
Thank you!
