### ISSUE TITLE
No pointer cursor on drill down line charts

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#6695]
#### Expected behaviour
The cursor should change into a 'hand' when you hover over a data point/series that can drill down. In line charts that doesn't happen (in column charts, pie charts, etc. it _does_)

#### Actual behaviour
The cursor doesn't change when hovering a drill down line

#### Live demo with steps to reproduce
http://jsfiddle.net/kzoon/nnyeho5j/3/

**Comment by pawelfus** [comment]
Thank you for the report.

**Comment by kzoon** [comment]
Bubble chart has comparable issue: See http://jsfiddle.net/6oq0pr6L/: it does drill down, but the cursor is not pointer.

(this fiddle uses 5.0.10 explicitly, because of a regression in the latest version, see https://forum.highcharts.com/post134961.html#p134961)

**Comment by kzoon** [comment]
Treemaps with drill down also have no pointer cursor. 
See http://jsfiddle.net/kzoon/ksb9k1yd/ (copied from pie drill down http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/pie-drilldown/)

Notice that this concerns regular drill down on tree map, not allowDrillToNode. http://jsfiddle.net/kzoon/ksb9k1yd/ drills down exactly how it should. Only the cursor is wrong.

**Comment by kzoon** [comment]
I plan to release a new version of my software in 2 weeks time. This version includes drill down. Any chance that this bug is fixed by then?
To recap: drill down works fine on line charts, bubble charts and treemaps, but the cursor doesn't indicate that the user can drill down (by showing a 'hand').

**Comment by pawelfus** [comment]
Version 5.0.12 was released about two weeks ago. We don't have ETA for the next release so it's unlikely to be released within two weeks.

**Comment by kzoon** [comment]
I am happy to integrate fixes from github into my release

**Comment by kzoon** [comment]
It looks like the fix solves the issue for bubble (http://jsfiddle.net/kzoon/6oq0pr6L/6/) and tree map (http://jsfiddle.net/kzoon/ksb9k1yd/2/),
but ****not for line charts**. The line between points does drill down, but doesn't have a 'hand' cursor:
http://jsfiddle.net/kzoon/nnyeho5j/8/
