### ISSUE TITLE
Tooltip doesn't show all values from different xAxes

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#6697]
#### Expected behaviour
The same as in 5.0.0: http://jsfiddle.net/K4Cj6/182/

#### Actual behaviour
Tooltip shows only the same xAxis related series: http://jsfiddle.net/K4Cj6/185/

It's a regression from f3bc93d ticket: #5832

**Comment by abdul-qadirdeveloper** [comment]
@pawelfus jsFiddle in expected and Actual Behaviour are same almost same (as they are referrencing same stock chart version 5.0.0), Actual Behaviour can be observed in later viersion 5.0.11, as shown in [http://jsfiddle.net/K4Cj6/184/](http://jsfiddle.net/K4Cj6/184/)

**Comment by abdul-qadirdeveloper** [comment]
@pawelfus, 2 months ago we have identified above said issue, [https://stackoverflow.com/questions/43821369/highstock-with-multiple-x-axes-tooltip-is-not-showing-values-of-all-series](url). but still no milestone have been assigned yet, as I said earlier above said bug is just not letting us to update our production, I would like you to plz fix said issue, and give us some estimated time when this issue will be fixed.

**Comment by KacperMadej** [comment]
@abdul-qadirdeveloper If this regression is the only problem that stops you from upgrading then maybe you would be interested in using a wrapper a workaround alongside newer Highstock version code. Please let me know and I will be able to prepare a workaround wrapper for you. Unfortunately we do not have an ETA for this issue.

**Comment by abdul-qadirdeveloper** [comment]
@KacperMadej If a wrapper could fix this issue, please prepare a workaround wrapper.

**Comment by KacperMadej** [comment]
@abdul-qadirdeveloper Here's a demo with the wrapper: http://jsfiddle.net/nqdLLz1w/ Please test the workaround and use it as long as it works for you. In case of any problems, please let me know and I will try to improve the solution.

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard Can you try to come up with a test that works with both cases?

**Comment by abdul-qadirdeveloper** [comment]
@KacperMadej you wrapper worked like a charm. thx.
Please do not close this bug, as issue still exist, and workaround temporarily fixed the issue.

**Comment by dustinjohnson13** [comment]
We're also waiting on this; encountered while upgrading from 4.2.3.

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard Maybe we can check for _both_ matching `clientX` and matching `x`. So if one of them matches, assume the same point group?
