### ISSUE TITLE
Bubble chart tooltip can't show 2 bubbles when mouse on one point

### ISSUE THREAD

**Issue by zhuwei** [highcharts/highcharts#6698]
Hi,
I want to show 2 bubbles when mouse on one point.
The attach file is an example.
Now I just can show 1 bubble. I wonder how to do it.
Thank you.
![qq 20170508173653](https://cloud.githubusercontent.com/assets/1817493/25799629/5368b824-3418-11e7-990b-254ffe7c2f26.png)

**Comment by pawelfus** [comment]
Hi @zhuwei 

This is our bug tracker, for questions please contact with us directly by email or create a topic on our forum, see [more details](https://www.highcharts.com/support).

Personally, I would use just one tooltip and in formatter generate content which looks like two separate tooltips.
