### ISSUE TITLE
Github Webhook don't work

### ISSUE THREAD

**Issue by rudovjan** [highcharts/highcharts#6699]
#### Expected behaviour

Hi guys, 

I updated my plugins today (did not touch it 3+ months) and webhook is redirecting my requests I tried to validate url and setup and everything seems to be same. 

Thank you for your advice.
Jan
Webhook update Higchart Plugin Site

#### Actual behaviour

Webhook returns 302 redirect

#### Live demo with steps to reproduce

https://ibb.co/n4mOo5

#### Affected browser(s)

Not related to browser

**Comment by jon-a-nygaard** [comment]
Hi @rudovjan 

Not too long ago we switched to https on our website, which is likely to be the reason for this problem.
Could you try edit the Payload Url to https://www.highcharts.com/plugin-registry/hook
And then press Redeliver on your latest request.

Please let me know if this should solve your issue.

**Comment by rudovjan** [comment]
Hi @jon-a-nygaard 

that worked very well .. just fyi https://www.highcharts.com/plugin-registry/howto over here is mentioned http version. Can you please refer me to newest guide or this one was not just updated?

Thank you very much for help,
Jan

**Comment by rudovjan** [comment]
oh, so link label is incorrect but actual href is ok :-) so probably just typo in link label

**Comment by jon-a-nygaard** [comment]
@rudovjan Yes, that is the latest. I have updated its content to use correct protocols in url's and some more information on common errors.

Thanks for reporting!
