### ISSUE TITLE
Axis labels are not positioned correctly when using large font sizes

### ISSUE THREAD

**Issue by andiger** [highcharts/highcharts#6700]
#### Expected behaviour
The x-axis labels should be positioned under the plot area.
The y-axis labels should be aligned with the y-values of the plot area.

#### Actual behaviour
The x-axis labels intersects the plot area.
The y-axis labels are not aligned with the values of the plot area. See for example the first data point in the provided fiddle-demo, it has the value 5 but visually it is closer to the '2.5' label.

#### Live demo with steps to reproduce
http://jsfiddle.net/adgadg/dnzvpkxb/9/

If I change the first y-value from 5 to 0 the labels seems to be positioned correctly.
If I remove both dates from the data array (leaving only one array with the two y-values) then the x-axis labels are positioned correctly. In all cases the x-axis labels 'area' seems to be calculated correctly (ie. the correct amount of space is reserved) but the labels are not placed inside it.

#### Affected browser(s)
Tested on Highcharts 5.0.10, Firefox 53

**Comment by pawelfus** [comment]
Thank you for reporting this issue!

**Workaround:*
Demo: http://jsfiddle.net/dnzvpkxb/12/

    (function(H) {
      H.wrap(H.Axis.prototype, 'labelMetrics', function(proceed) {
        var index = this.tickPositions && this.tickPositions[0] || 0;
        return this.chart.renderer.fontMetrics(
          this.options.labels.style && this.options.labels.style.fontSize,
          this.ticks[index] && this.ticks[index].label
        );
      })
    })(Highcharts);

*Internal note:*
We can not assume in `labelMetrics` that `this.ticks[0]` will always be defined.
