### ISSUE TITLE
Point events/tooltip are lost after chart.redraw in 3d chart

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#6703]
#### Expected behaviour
Point events/tooltip are preserved after the chart is redrawn.

#### Actual behaviour
Point events/tooltip do no fire after redraw

#### Live demo with steps to reproduce
http://jsfiddle.net/omp7cv4n/
1. Click on 'click' button
2. Click on point
3. The event is not fired

It worked in Highcharts 5.0.10 http://jsfiddle.net/omp7cv4n/1/

**Comment by TorsteinHonsi** [comment]
Regression since 6f842539a. 

In addition to click events, the whole tooltip interaction is gone.

**Comment by Izothep** [comment]
Thank you for reporting this issue! 

It looks that the problem is related to #6694 

When 3d frames are in front of the series it is not possible to trigger series/point events correctly.

**Comment by Izothep** [comment]
This issue looks to be solved by 653b4a0d1d110dc83fb05aeb6cf2ffa6d6897f5a 
Live demo: http://jsfiddle.net/omp7cv4n/6/
