### ISSUE TITLE
Series values not grouped for two series after drilldown (for multiple series with more than 48 values)

### ISSUE THREAD

**Issue by igimenez** [highcharts/highcharts#6704]
#### Expected behaviour
Chart grouping values for different series after drilldown in the right order

#### Actual behaviour
After drilldown some values are not grouped as they are supposed to

#### Live demo with steps to reproduce

http://jsfiddle.net/x9usgfe4/2/

1) Click on Product B (Label, not chart series)

-> The columns apear separated for same markets

2)  if I click and unclick one of the series label (Products 2015 Product B for example) the chart magically fixes itself.

**Comment by TorsteinHonsi** [comment]
_Internal note_:
The `xAxis.names` array gets extended during drilldown, so at some stage, both the old and the new categories are part of the `names`. That's why the offset of the second series is wrong.

**Comment by igimenez** [comment]
Thanks @TorsteinHonsi ! Will this be available in highstock.js as well in the next release?

**Comment by pawelfus** [comment]
Hi @igimenez 
It's on the master branch so it should be included in the next release.
