### ISSUE TITLE
Charts doesn't reflow/redraw when others item in the same container gets hidden

### ISSUE THREAD

**Issue by Abhijith-Nagaraja** [highcharts/highcharts#6707]
#### Expected behavior
At present, Charts gets **redrawn/reflowed** whenever a `window.resize` event gets triggered. The same thing should happen when other elements on the same level get hidden through `display: none` and make the chart container grow in size.

#### Actual behaviour
Chart should be redrawn / reflowed

#### Live demo with steps to reproduce
http://jsfiddle.net/0oc6s48a/2/

#### Affected browser(s)
All

#### Workaround (Typescript code)
When only one chart in the web page
```
setTimeout(function() {
  chart.reflow();
}, 1);
```

When multiple charts in the web page
```
setTimeout(function() {
     if (Highcharts.charts) {
        for (let chart of Highcharts.charts) {
           if (chart) {
             chart.reflow();
           }
        }
    }
}, 1);
```

**Comment by pawelfus** [comment]
Hi @Abhijith-Nagaraja 

Thank you for the report. Unfortunately, there's no event we can listen on and resize the chart, so you need to take care of it. That is one of the reasons why `chart.reflow()` is in the API.

**Comment by Abhijith-Nagaraja** [comment]
Hi @pawelfus

Actually if I am not wrong,  you can listen to the css attribute changes using mutation observer.

Here is the link.

https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

Let me know if it helps

**Comment by pawelfus** [comment]
MutationsObserver is supported IE11+, Highcharts lib has much longer compatibility list. We would need to add polyfill to the source code or create our own solution. Maybe as a plugin it makes sense but as part of the source code I'm a bit sceptic. @TorsteinHonsi what do you think?

**Comment by TorsteinHonsi** [comment]
If we find a good way to monitor changes to the container width I think we should use it, even if it's not fully supported. We need to leave it off by default to avoid confusing behaviour, then highlight in the docs that it has limitations.

I tried the MutationObserver, but it doesn't seem to respond to CSS changes: http://jsfiddle.net/highcharts/0oc6s48a/6/

Proposal if we get it working: 
Modify the [chart.reflow](http://api.highcharts.com/highcharts/chart.reflow) option to accept a third setting, `all`, that also sets up a listener for mutations in addition to window resize.

**Comment by QuentinLB** [comment]
It does respond to CSS change, you were just a bit quick on the mdn copy/past 😉 

By adding `subtree: true` to the observer options and removing `observer.disconnect();` at the end, it should be working. http://jsfiddle.net/e7akghfu/

I tried to make a naïve filter to determine if the chart should be redrawn or not by testing if the mutation target has common parent with the chart but it often come all the way to the body and is pretty costly.

**Comment by pawelfus** [comment]
Thanks @QuentinLB 

You are right, it looks promising: http://jsfiddle.net/e7akghfu/1/

The only problem now, as you realized, is to determine when `chart.reflow()` should be called. Maybe simple comparing chart's width and container's width will do? Demo: http://jsfiddle.net/75y07e8x/

**Comment by QuentinLB** [comment]
@pawelfus Look like a great solution for the reflow problem, I was focused on the mutation target and didn't think about checking the parent width. Although it may not cover the issue if there is multiple nesting levels between the chart and the mutation target's parent. 

I looked up this open issue because we have a similar problem in my team current project. If we decide to make a custom reflow plugin, like @TorsteinHonsi suggested, I'll make sure to keep you posted.

Regarding your earlier comment about HIghchart support, I understand the reasonning to offer the broadest support but instead of tailoring the library capabilities to the lowest common denominator maybe taking the graceful degradation philosophy would be more pertinent.

**Comment by Nosfistis** [comment]
`MutationObserver` does not seem to trigger in my Angular application. I believe that the solution would be [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver), a very young spec.
