### ISSUE TITLE
3D bar charts with a y value of 0 displaying incorrectly

### ISSUE THREAD

**Issue by plavski** [highcharts/highcharts#6708]
#### Expected behaviour
Bar chart should render correctly with a 0 value lying flat in its correct place.

#### Actual behaviour
Highcharts 3d is showing edges along the bottom of bar chart if a y value is set to 0.

#### Live demo with steps to reproduce
http://jsfiddle.net/9nbdb669/2/

#### Affected browser(s)
Chrome, Edge, Safari

**Comment by pawelfus** [comment]
Thank you for reporting this bug!

It's a regression after 67371c4 and 4025203a43afc772372640ca3f52690d8a0894f2

**Comment by plavski** [comment]
Any update on this issue? It's a pretty critical issue for us right now.

**Comment by Izothep** [comment]
@plavski Thank you for your message. 

It looks that your issue is solved by faab463

Live example:
http://jsfiddle.net/9nbdb669/12/

**Comment by plavski** [comment]
Great! Thanks very much.
