### ISSUE TITLE
[highstock] Chart.get(serie) when serie undefined and other series have visibility hidden

### ISSUE THREAD

**Issue by FlorianBurgevin** [highcharts/highcharts#6709]
Hello,

I'm trying to dinamically select/unselect series as a filter.

My series are also dynamic, so they may not exists every time. My filter don't take care of this and try to show/hide some series.

In my code, I use `chart.get('my_serie_id')` and then `setVisible() `on the serie returned if the serie exists.

An error occured when the serie not exists !

> Cannot read property 'id' of undefined

This came from when I try to **get a serie which not exists** AND when **some series are hidden.**

The error occured in the Highstock function itemById when get is trying to retreive points (no axis or series found) on an hidden serie because points of this serie are set to undefined

=> serie.points ==> [undefined, undefined, ...]

Do you have a solution for this problem?

**Comment by pawelfus** [comment]
Hi @FlorianBurgevin 

Thank you for reporting this bug. You are right it throws error, live demo: http://jsfiddle.net/sm5fw061/1/

Not the best workaround: disable dataGrouping: http://jsfiddle.net/sm5fw061/2/

*Internal note:*
It's only Highstock issue, and only when dataGrouping is enabled. All of grouped points are `undefined`.

**Comment by FlorianBurgevin** [comment]
OK thank you !

I must enable dataGrouping so I explored another solution by looping over all series instead of my filter series. So I never ask the get method for an undefined serie.

The loop is a bit longer but it's the best solution for the moment.

**Comment by TorsteinHonsi** [comment]
It's a regression in v5.0.8, commit 0d8f1bdc3.

**Comment by pawelfus** [comment]
*Internal note:*
It's also connected to f47d4ed4b391b0d44842f24dbf344203f9bf0f2a
