### ISSUE TITLE
Scatter tooltip doesn't consider xDateFormat

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#6711]
#### Expected behaviour
Scatter tooltip doesn't use [xDateFormat](http://api.highcharts.com/highcharts/plotOptions.scatter.tooltip.xDateFormat) as documented.

#### Actual behaviour
X value is shown in tooltip as a timestamp

#### Live demo with steps to reproduce
http://jsfiddle.net/alvarezg/noh73rbr/

It works as expected for line chart, might be related to fact that scatter tooltip doesn't have a header.

#### Workaround
One option is to use a line chart with 
```
            lineWidth: 0,
            states: {
                hover: {
                    lineWidthPlus: 0
                }
            }
```

**Comment by pawelfus** [comment]
It looks like a bug in docs. Scatter's `pointFormat` is different than all others. 

**Workaround:**
Use `series.tooltip.pointFormat`, for example: http://jsfiddle.net/noh73rbr/1/

    series: [{
      tooltip: {
        pointFormat: 'x: <b>{point.x:%Y-%m-%d}</b><br/>y: <b>{point.y}</b><br/>'
      },
      data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    }]

It looks like a duplicate of #3552

**Comment by alvarezguille** [comment]
I understand. Thanks for the pointFormat example!
Should I close this issue or wait for docs fix?

**Comment by pawelfus** [comment]
Let's keep this open.
