### ISSUE TITLE
The highstock API documentation does not list scrollbar as an available property for the xAxis

### ISSUE THREAD

**Issue by ryanewtaylor** [highcharts/highcharts#6712]
The [API documentation](http://api.highcharts.com/highstock/xAxis) does not list `scrollbar` as an option for the xAxis but it appears to be an option.  Some examples apply the scrollbar to the xAxis as [shown here](https://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/stock/yaxis/inverted-bar-scrollbar/). Further the [blog post introducing scrollable charts](https://www.highcharts.com/blog/news/224-scrollbars-for-any-axis/) mentions.

> ...scrollbars are not limited to stock charts or Y axis. Using the highstock.js file, it can be applied to regular Highcharts axes too,

This would appear to be an error in the documentation.

**Comment by pawelfus** [comment]
Thank you for the report! Of course, this should also be mentioned under `xAxis` options.
