### ISSUE TITLE
Is it possible to to prevent tooltip from moving when it's hovered over?

### ISSUE THREAD

**Issue by xdragus** [highcharts/highcharts#6713]
Seeing if there is an existing option I just have to enable.

- Using a stacked column chart.
- Tooltip has useHTML true and has <a> links inside it
- tooltip has custom positioner and formatter functions

#### Expected behaviour
When hovering over tooltip, prevent tooltip from shifting over to next set of data so user can view details of that data

#### Actual behaviour
When hovering over tooltip, when I try to move mouse over the <a> links inside the tooltip, it'll move over to the next bar chart, thus unable to view details of that data

![image](https://cloud.githubusercontent.com/assets/3050689/25909291/bffce51a-357a-11e7-99d9-7d5cd50e504f.png)

**Comment by pawelfus** [comment]
Related UserVoice ticket: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/1126429-allow-clickable-tooltips

**Comment by xdragus** [comment]
Thanks
