### ISSUE TITLE
Drilldown and tooltip are in conflict on mobile devices

### ISSUE THREAD

**Issue by starquake** [highcharts/highcharts#6715]
#### Expected behaviour
I can think of a few options: 
- When on mobile one of the two behaviours could be disabled
- When on mobile one of the two behaviours could be changed to trigger on 
- When on mobile show the tooltip and in the tooltip show the action to drill down

#### Actual behaviour
When you tap a bar you will get both the bar and the drilldown action. The issue is most apparent when click on the Opera bar. The tooltip will stay there but will not make any sense anymore.

#### Live demo with steps to reproduce

Gif of what happens here:
http://www.giphy.com/gifs/l0IypEdoMbHI5uSgE

Steps to reproduce:
Open this on a mobile device or in the chrome mobile emulator:
https://www.highcharts.com/demo/column-drilldown
Tap on a bar, you will see both the drill-down behaviour and the tooltip.

#### Affected browser(s)
Android Chrome (probably all versions)
iOS Safari (probably all versions)

**Comment by pawelfus** [comment]
Thank you for your suggestions @starquake 

I think there may be another option, or a variation of your last suggestion: the first tap on a point shows a tooltip and the second tap cause the drilldown.

At this moment we can hide tooltip in drilldown event: http://jsfiddle.net/5sgvyz3d/

    chart: {
        type: 'column',
        events: {
        	drilldown: function (e) {
          	    this.tooltip.hide();
            }
        }
    }

**Comment by starquake** [comment]
@pawelfus That would be an option indeed.

About hiding the tooltip: This way you won't see the tooltip on mobile.

**Comment by kzoon** [comment]
I plan to release a new version of my software in 2 weeks time. This version includes drill down on mobile devices. Any chance that this bug is fixed by then?

**Comment by pawelfus** [comment]
Hi @kzoon 

What do you think about proposed solutions? Implementing all of them is rather not possible.

**Comment by kzoon** [comment]
I think this would be the best solution:
On data points that  have drill down AND a tool tip, tap will result in drill down and long tap will result in displaying the tool tip.
