### ISSUE TITLE
Highstock "arearange" series not shows null values with active dataGrouping

### ISSUE THREAD

**Issue by smiith** [highcharts/highcharts#6716]
#### Expected behaviour

Arearange serie should show points with null values.

#### Actual behaviour
Null values dropped when dataGrouping is active.  

#### Live demo with steps to reproduce

1. Zoom should set to "All".
2. Compare with graph when dataGrouping "forced" set to "false".
     
http://jsfiddle.net/2p0rrx0m/

#### Affected browser(s)

Chrome

**Comment by pawelfus** [comment]
Thank you for this report. Current "range" approximation doesn't consider nulls. You can define your own approximation. Demo: http://jsfiddle.net/b20nznz0/

And code:

```
  series: [{
    type: 'arearange',
    name: 'Temperatures',
    data: data,
    dataGrouping: {
      forced: true,
      approximation: function(low, high) {
        low = low.length ? Highcharts.arrayMin(low) : (low.hasNulls ? null : undefined);
        high = high.length ? Highcharts.arrayMax(high) : (high.hasNulls ? null : undefined);

        if (Highcharts.isNumber(low) || Highcharts.isNumber(high)) {
          return [low, high];
        } else if (low === null && high === null) {
          return null;
        }
        // else, return is undefined
      }
    },
  }]
```

**Comment by smiith** [comment]
Pawelfus, Thank you for solution!

It would be great to have your fix as official "range" approximation function.
