### ISSUE TITLE
Navigator is always at the bottom

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6718]
#### Expected behaviour
Navigator should be placed under axis

#### Actual behaviour
Navigator is always at the bottom

#### Live demo with steps to reproduce
http://jsfiddle.net/h4urcjnr/

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
@sebastianbochan  marginBottom: `..bottom outer edge of the chart and the plot area...` - Navigator doesn't seem to be in the plot area. Shouldn't be used `spacingBottom` instead? Demo: http://jsfiddle.net/h4urcjnr/2/

**Comment by pawelfus** [comment]
It's the expected behaviour.
