### ISSUE TITLE
Highchart line serie gets larger and wide in pdf

### ISSUE THREAD

**Issue by Artlake** [highcharts/highcharts#6719]
#### Expected behaviour
I want my highchart to be same in pdf like it is in html. Especcialy the chart line.

#### Actual behaviour
I have highchart rendered in html and i have button that calls www.cloudformatter.com which exports my html to pdf. When i open this pdf line in the chart is larger and wide than same line i have in html display.

As you can see i also have shield ui chart there, his line is rendered well in pdf, using css2pdf. But i want to use higcharts, thats why i need this fixed.
#### Live demo with steps to reproduce
http://jsbin.com/ravemivega/edit?html,js,output

#### Affected browser(s)
Any browser

**Comment by pawelfus** [comment]
Thank you for the demo! :)

I think it's a bug in cloudformatter. Using simple SVG we have the same result: http://jsbin.com/cujifovegi/edit?html,js,output - it looks like they don't support correctly `stroke="rgba(r, g, b, 0.0001)"` formats. Have you tried to contact them?

I guessed right, it's connected to the tracker. Setting `enableMouseTracking` to false resolves the issue (more a workaround than a solution): http://jsbin.com/voyolemova/edit?html,js,output

Related [SO](http://stackoverflow.com/questions/43804214/highchart-line-renders-bigger-when-exported-to-pdf-using-css2pdf?noredirect=1#comment74657545_43804214) question.

**Comment by Artlake** [comment]
Pawel thank you sir! That realy worked, i would never thought that, that property will fix that, thanks again for your effort. I hope you will help as much more people in future with your knowledge!
