### ISSUE TITLE
zAxis grid lines incorrectly while using Highstock

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6720]
#### Behaviour
Grid lines of zAxis in 3d chart, render incorrectly while using Highstock. When using Highcharts, they render as expected.

#### Live demos
http://jsfiddle.net/0h1k776y/ - using Highstock
http://jsfiddle.net/2ntzzhg5/ - using Highcharts

**Comment by pawelfus** [comment]
It's a regression from 68dbd6e
