### ISSUE TITLE
area range fill broken in area range and line charts with null values

### ISSUE THREAD

**Issue by jcsturges** [highcharts/highcharts#6721]
#### Expected behaviour
I would expect the fill to stay consistent within the range upper and lower bounds but the fill falls below the line across null values. Using the area range and line chart in the demo charts as an example (https://www.highcharts.com/demo/arearange-line and http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/arearange-line/ on JSFiddle).

#### Actual behaviour
The upper and lower bounds of the range series work correctly, and stay smoothed across nulls as expected. However, the fill drops down oddly below the lower bounds like and fills to the x-axis over null values in a series. We want to show charts will intentionally null values along with an area range.

#### Live demo with steps to reproduce
Example showing movie gross revenue predictions leading up to the day of movie release with an upper and lower bound "confidence internal" range (broken fill). Since this is counting down until release date the x-axis values are set in reversed numerical order: https://jsfiddle.net/gxvs7ds4/16/

![chart](https://cloud.githubusercontent.com/assets/3021372/26008259/f9affa16-3711-11e7-8001-02332c46d1d1.png)

#### Affected browser(s)
All, doesn't seem to be browser specific.

**Comment by pawelfus** [comment]
You are right, it looks broken, simple demo: http://jsfiddle.net/jrhfcdk0/

**Comment by TorsteinHonsi** [comment]
Last working version was 4.2.1: http://jsfiddle.net/highcharts/jrhfcdk0/1/
