### ISSUE TITLE
Column range series shows data outside of selected range

### ISSUE THREAD

**Issue by reichert621** [highcharts/highcharts#6722]
#### Expected behaviour
If I set the range selector to a time period with no data, nothing should be shown on the graph. For example, this works fine with the 'arearange' type: http://jsfiddle.net/em812rrm/

#### Actual behaviour
If I set the range selector to a time period with no data, the chart still displays data from outside the range. 

For example, if data only exists for Jan 1, 2014 and Jan 1, 2015 and I select a time range of Apr 1, 2014 to Sept 1, 2014, the data point for Jan 1, 2015 is displayed

#### Live demo with steps to reproduce
Change the series type from 'columnrange' to 'arearange' to see the expected behavior:
http://jsfiddle.net/voecpf2k/

#### Affected browser(s)
Chrome 58.0.3029.110
Firefox 41.0.2
Safari 10.1

**Comment by pawelfus** [comment]
Hi @reichert621 
Thanks for the report!

**Workaround:**
Set [`series.pointRange`](http://api.highcharts.com/highcharts/plotOptions.columnrange.pointRange) to `1`, demo: http://jsfiddle.net/voecpf2k/1/

*Interla note:*
It's a regression after 0eab7a9
