### ISSUE TITLE
Errorbar xAxis starting tick outside of extremes

### ISSUE THREAD

**Issue by mapeebles** [highcharts/highcharts#6723]
#### Expected behaviour
I expect the xAxis ticks to match when the two charts have the same min and max.  The ticks are expected to match even when different chart types are used

#### Actual behaviour
A chart with an errorbar is causing the xAxis to have ticks passed the min and max settings

#### Live demo with steps to reproduce
https://jsfiddle.net/mpeebles/pvbcezx6/

Notice the bottom chart has space before March '15 and after Nov '16 where the line (only) chart does not, so they do not line up properly when stacked.

#### Affected browser(s)
Chrome Version 58.0.3029.110 (64-bit)

**Comment by pawelfus** [comment]
Hi @mapeebles 

This is the expected result. Errorbar series reserves extra space, just like a column series. To prevent this, you can set [`series.pointRange`](http://api.highcharts.com/highcharts/plotOptions.errorbar.pointRange) to zero: https://jsfiddle.net/pvbcezx6/2/

**Comment by mapeebles** [comment]
Thanks @pawelfus!  That works.
