### ISSUE TITLE
Column chart tooltips not grouping series correctly when too many categories

### ISSUE THREAD

**Issue by joekrie** [highcharts/highcharts#6726]
#### Expected behaviour
On an column chart, when hovering a bar within a category, the tooltip should show the values for the category you are hovering over.

#### Actual behaviour
When hovering over a bar within a category, the values do not always match the actual data, even though the bar itself is showing the correct data. Instead, the tooltip will show values from an adjacent category and highlight bars in the adjacent category.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/column-basic/

Chrome:
1. Hover over the Tokyo bar in June category. Tooltip shows correct values, and all bars in June category highlight.
2. Hover over New York bar in June category. Tooltip shows some values from July category and highlights some July bars.

IE:
1. Hover over the Tokyo bar in March category. Tooltip shows correct values, and all bars in March category highlight.
2. Hover over London bar in June category. Tooltip shows some values from February category and highlights some February bars.

#### Affected browser(s)
Chrome 58
IE 11

**Comment by pawelfus** [comment]
Hi @joekrie 

Thank you for the report! It's already fixed on our master branch: http://jsfiddle.net/qw8ppg4k/ - fix will be a part of the next release.
