### ISSUE TITLE
wrong show in hightStock when there is a long data and long date

### ISSUE THREAD

**Issue by fayfang** [highcharts/highcharts#6729]
as the screenshot below, my first data is '2010-01-08',but the show is '2010-01-04', all the data is mismatched.
when there is a shorter data or a shorter date, it will not appear.
the data.length = 383, the container's width is 550px
 
![5eec67aa-4460-450e-adb3-44c1ba1df423](https://cloud.githubusercontent.com/assets/15612884/26091239/9c7541f2-3a3c-11e7-84d7-fd42cd0ce87d.png)

![792c8fce-8fa0-467b-943d-6aa5ec976707](https://cloud.githubusercontent.com/assets/15612884/26086668/ab771a72-3a1e-11e7-95de-4979f1395069.png)

**Comment by pawelfus** [comment]
It looks like a `dataGrouping` feature. Highstock groups points when there isn't enough space for all of them. For example `dataGrouping` can group points into one week packages, where each point is rendered as Monday. You can change this default value to other day of the week: [`xAxis.startOfWeek`](http://api.highcharts.com/highstock/xAxis.startOfWeek).

You can also disable [`dataGrouping`](http://api.highcharts.com/highstock/plotOptions.series.dataGrouping.enabled) if you want to display only original points.
