### ISSUE TITLE
Inconsistent columns width issue in highcharts

### ISSUE THREAD

**Issue by Ramyani** [highcharts/highcharts#6732]
I've created a column chart width 2 series data with 61 entries in each series.
By default the columns width should be similar but it is getting inconsistent.

 http://jsfiddle.net/ynkq44oj/

**Comment by oysteinmoseng** [comment]
Hi, this is due to the crisping algorithm that rounds the column width to the nearest full pixel value. You can disable this with the [column.crisp](http://api.highcharts.com/highcharts/plotOptions.column.crisp) option.

**Comment by Ramyani** [comment]
Hi, I have tried with this option. After making `crisp: false` chart columns are looking hazy.
http://jsfiddle.net/ynkq44oj/1/

**Comment by oysteinmoseng** [comment]
@Ramyani Unfortunately that is unavoidable, your screen only has so many pixels. You can of course try to change `pointWidth` and see if it works better with your dataset. Example: http://jsfiddle.net/ynkq44oj/8/
