### ISSUE TITLE
Legend name formatting

### ISSUE THREAD

**Issue by nishanth-satmetrix** [highcharts/highcharts#6733]
#### Expected behaviour
Need to show part of legend name in bold. it should work when we resizing the chart. should not cut the legend name when we try increase the legend name. Note: passing data to the series as series.push(name:name,data:data, showLegend: false);

#### Actual behaviour
when im try to change bold the part of the legend name its not working.  the name got cut. images are shown below.  Note: How i format the legend name if i enabled the legend name inside the series.push()
![highchart](https://cloud.githubusercontent.com/assets/24522559/26101336/67b3bb3a-3a4e-11e7-93f9-0a19d0ccea40.jpg)

Thanks in Advance

Nishanth

**Comment by pawelfus** [comment]
Hi Nishanth,

Thank you for reporting this issue. It looks like [`legend.itemWidth`](http://api.highcharts.com/highstock/legend.itemWidth) is broken. [`legend.itemStyle.width`](http://api.highcharts.com/highstock/legend.itemStyle) works fine.

Demos:

- `legend.itemStyle.width`: http://jsfiddle.net/xbkukm32/1/
- `legend.width`: http://jsfiddle.net/xbkukm32/2/

**Comment by nishanth-satmetrix** [comment]
Hi Pawelfus,

    Thank you for the immediate response. I added that property still its showing Ui cut. if any problem that if I enabled the legend using showLegend property. ??

**Comment by pawelfus** [comment]
That property shouldn't matter, it only enables/disables series in a legend. 

If the above doesn't resolve your issue, then please recreate issue in jsfiddle (you can start with my demo). Thanks!

**Comment by nishanth-satmetrix** [comment]
Hi Pawelfus, Im not able to create the fiddle.  im trying that. but I can give you the code which I added

 name=name.replace("bold","<b>bold</b>")
 series.push({'name': name, 'data': col.data, showInLegend:true,cIndexes:col.cIndexes,width:100});
 opt.series=series;
 opt.legend={itemStye:{width:100}};

But its not affecting the legend

Thanks.

**Comment by pawelfus** [comment]
Unfortunately, without live demo we could only guess what is wrong. In that case it's better to contact with us directly, by email (simply attach this ticket number). 

For me, it looks like: `{itemStye:{width:100}};` is wrong, there should be `itemStyle`.

**Comment by nishanth-satmetrix** [comment]
http://jsfiddle.net/xbkukm32/4/ can you just check this one
 here im trying to replace , if the name contain overall need to replace with bold overall. its not picking
