### ISSUE TITLE
Disappearing series with point names

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6735]
#### Behaviour
Resizing div containing a waterfall chart, when xAxis type is set to category, causing disappearance of any other series.

#### Live demos with steps to reproduce
http://jsfiddle.net/nh0q5Lnn/

1. Resize result window.

**Comment by pawelfus** [comment]
It looks like a problem with mismatching categories for a column series and for a waterfall. On first render, categories are merged, but on redraw categories are mismatched. 

**Workaround (?)/Solution:**
Use the same points' names for column series: http://jsfiddle.net/nh0q5Lnn/1/

**Comment by TorsteinHonsi** [comment]
Waterfall has nothing to do with it, it is the axis category feature. Simplified: http://jsfiddle.net/highcharts/nh0q5Lnn/5/
