### ISSUE TITLE
dateFormat documentation missing

### ISSUE THREAD

**Issue by bananer** [highcharts/highcharts#6737]
#### Expected behaviour
I'm expecting to see a list of supported format characters on https://api.highcharts.com/class-reference/Highcharts#dateFormat

#### Actual behaviour
The list is mentioned in many places ("see below", "some of the formats above") but missing on that page. I can't find it anywhere else.

#### Affected browser(s)
Firefox 53

**Comment by pawelfus** [comment]
List of supported formats:


                        //-- Day
                        // Short weekday, like 'Mon'
                        'a'
                        // Long weekday, like 'Monday'
                        'A'
                        // Two digit day of the month, 01 to 31
                        'd'
                        // Day of the month, 1 through 31
                        'e'
                        // Day
                        'w': day,

                        // Week (not implemented)
                        //'W': weekNumber(),

                        //-- Month
                        // Short month, like 'Jan'
                        'b'
                        // Long month, like 'January'
                        'B'
                        // Two digit month number, 01 through 12
                        'm'

                        //-- Year
                        // Two digits year, like 09 for 2009
                        'y'
                        // Four digits year, like 2009
                        'Y'

                        //-- Time
                        // Two digits hours in 24h format, 00 through 23
                        'H'
                        // Hours in 24h format, 0 through 23
                        'k'
                        // Two digits hours in 12h format, 00 through 11
                        'I'
                        // Hours in 12h format, 1 through 12
                        'l'
                        // Two digits minutes, 00 through 59
                        'M'
                        // Upper case AM or PM
                        'p'
                        // Lower case AM or PM
                        'P'
                        // Two digits seconds, 00 through  59
                        'S'
                        // Milliseconds (naming from Ruby)
                        'L'

**Comment by KacperMadej** [comment]
**Internal note:**
The Paweł's list of supported formats could be added [here](https://github.com/highcharts/highcharts/blob/073df3634c6d6b1e9ce051b3585ab0fa1983e712/js/parts/Utilities.js#L873-L879) or if that would be too long for API reference, than the info could be added to the general documentation e.g. [here](https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting).

**Comment by dandv** [comment]
+1 for adding the list of formats in the documentation. Here on GitHub it's not really discoverable and I ended up filing a duplicate issue for this, #8808.

**Comment by trygveaa** [comment]
PR #12357 added this to https://api.highcharts.com/class-reference/Highcharts.Time#dateFormat, but it's still missing from https://api.highcharts.com/class-reference/Highcharts#.dateFormat

**Comment by pawelfus** [comment]
@bre1470
