### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pos' of undefined at H.Chart.preRender (VM1279 boost.src.js:2668)

### ISSUE THREAD

**Issue by mathiasconradt** [highcharts/highcharts#6739]
I found an issue with the boost module. Interestingly the **issue occurs by just including the boost.src.js without even enabling boost**!

This is my fiddle:
http://jsfiddle.net/j950np50/30/
where I have a highchart (using highcharts-ng as well).

This is what I do:
- initialize the chart, the chart has no data/series at the beginning
- after 1 second delay (setTimeout), I add 9 data series via script.
- after 2 seconds delay (setTimeout), I try to remove all series and axis again from the chart.

I would expect that all the series are being removed from the chart. But this is not the case. Instead I get an error in the console:

```
Uncaught TypeError: Cannot read property 'pos' of undefined
    at H.Chart.preRender (VM1279 boost.src.js:2668)
    at H.fireEvent (VM1278 highcharts.src.js:1888)
    at H.Chart.redraw (VM1278 highcharts.src.js:15485)
    at Axis.remove (VM1278 highcharts.src.js:20793)
    at VM1361:176
```

Interestingly, the error **does not occurs under two circumstances**:
- keep the number of series below 10 (i.e. change line 81 in my jsfiddle: `var numberOfSeries = 10; // change it to 9 and it works fine!`
- OR remove boost.src.js from the external resources in the jsfiddle, and then the error doesn't occurs even with more than 10 series (not though that boost is not enabled anywhere in the jsfiddle / chart config)

**Comment by pawelfus** [comment]
Hi @mathiasconradt 

Thanks for reporting this bug. Boost can be enabled in two cases: when you have a lot of point in one a series, or you have a lot of series. And default value for series is.. yup, 10 :) So, actually boost is enabled in your case.

You can control this threshold of series, using:

```
boost: {
  seriesThreshold: 100
}
```

Demo: http://jsfiddle.net/j950np50/33/

Simplified demo with error (without angular): http://jsfiddle.net/2gqo8Lrp/

**Comment by mathiasconradt** [comment]
Ok, I see. I thought that leaving out the `boost: {}` part from the config would disable it entirely. Good to know it's not the case.
