### ISSUE TITLE
Tick Labels disappear when chart is scrolled

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6741]
#### Expected behaviour
When the chart is rendered, the tick labels should be exactly aligned with the columns and should not move/disappear when the chart is scrolled.

#### Actual behaviour
When X axis is scrolled, tick labels for some columns disappear and reappear. It seems tick labels are being recalculated on chart scrolling. Is this default behaviour from Highcharts?

#### Live demo with steps to reproduce
http://jsfiddle.net/q7uca1mt/1/

For this fiddle, the result display window has to be increased in size as shown in the screenshots. For different screen resolutions, this may differ. If we carefully look at the screenshots, the column for 5 Aug has a tick on x-axis at one point of scroll, while at some other point, its tick disappears.

**Tick at 5 Aug**
![untitled](https://cloud.githubusercontent.com/assets/18263719/26149180/ed877bca-3b16-11e7-86cb-c64c9562f726.png)

**Between Ticks 4 Aug and 6 Aug**
![untitled2](https://cloud.githubusercontent.com/assets/18263719/26149185/f1c256ce-3b16-11e7-8f0f-8e61de631489.jpg)

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

First, when demoing you should set a fixed width on the chart in the fiddle, so we don't have to do a blind guess when trying to reproduce.

Second, what you see probably isn't a bug. The Highcharts axis is set up to place ticks in even intervals, and in your screenshots, that interval is two days. So it may vary if the ticks are placed on odd or even days. That depends on the start of the visible range.

**Comment by sagargurtu** [comment]
I guess you are right. In the first screenshot tick starts from 30th July, and in the second one it starts from 2nd August. Incrementing both by two days continuously, we get tick for 5th Aug in the first one, whereas in the second it skips it. Thanks!
