### ISSUE TITLE
Can't disable animation on point marker hover

### ISSUE THREAD

**Issue by goodforenergy** [highcharts/highcharts#6742]
Hey there! I'm upgrading from 5.0.0 to 5.0.11, and noticed a new animation on point marker hover on our spline charts that we don't want. We have chart.animation set to true globally, so I tried to disable the animation on the chart itself, by setting the plotOptions.spline.states.hover.animation value to false.

It seemed to have no effect. I'm not sure if this is a bug or if I'm not using the correct property. Advice much appreciated.

#### Expected behaviour

plotOptions.spline.states.hover.animation value should override the chart.animation value, to (for example) disable animation for one chart when chart.animation has been set to true globally.

#### Actual behaviour

plotOptions.spline.states.hover.animation value seems to have no effect.

#### Live demo with steps to reproduce
http://jsfiddle.net/m699zpxa/5/

#### Affected browser(s)
Chrome (all tested).

**Comment by pawelfus** [comment]
Thank you for reporting this bug! It works fine as long as we disable global animation: http://api.highcharts.com/highcharts/plotOptions.area.marker

*Internal note:*
It looks like we have wrong priority for animations here: https://github.com/highcharts/highcharts/blob/98c0943877b59e0b3fa1ff17aaa84382aaf61974/js/parts/Interaction.js#L658-L660 - I think it should be: `series.marker.states.stateName.animation` -> `series.states.stateName.animation` -> `chart.animation`. 

Extra:
Docs are missing references to `series.marker.states.stateName.animation` and to `series.marker.animation`.

**Comment by TorsteinHonsi** [comment]
> It looks like we have wrong priority for animations here:

**Comment by goodforenergy** [comment]
Hey again - is there any chance of addressing this before the next release? We're waiting on this to upgrade to 5.x.

**Comment by TorsteinHonsi** [comment]
It requires some restructuring... But why have you set animation to `true` globally? By leaving it undefined you get animation globally, but are able to override the hover state animation.

**Comment by goodforenergy** [comment]
I didn't realise that defaulted to true. Such a simple fix! Thanks :)
