### ISSUE TITLE
 Calling Chart.getSelectedPoints() generates error when series is not visible

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6744]
#### Behaviour
Calling Chart.getSelectedPoints(), while series is not visible results in 'Cannot read property 'selected' of undefined' error. When dataGrouping is disabled, everything works as expected. It is also related with chart’s width (series contains many points and width of chart is small). The latest working version, where error does not occur is 5.0.7. Could be related to #1798. I think below wrap:

    wrap(Chart.prototype, 'getSelectedPoints', function(proceed) {
        var points = proceed.call(this);
        each(this.series, function(serie) {
            // series.points - for grouped points (#6445)
	    if (serie.hasGroupedData) {
	        points = points.concat(grep(serie.points || [], function(point) {
		    return point.selected;
		}));
	    }
        });
	return points;
    });
is responsible for this behaviour. 
#### Workaround
Getting rid of getSelectedPoints() wrap or wrapping it but with changes in some lines:
     
    var points = proceed.call(this); -> var points = [];
and

    serie.points -> serie.data

fixes the problem.

#### Live demos with steps to reproduce
https://jsfiddle.net/f135k4xy/ - the newest version (5.0.11), does not work
https://jsfiddle.net/61zr3uc7/ - version 5.0.7, works
https://jsfiddle.net/v11b9msy/ - getSelectedPoints() wrapped, works

1. Turn of the visibility of the series.
2. Shrink chart to a small width size.
3. Click ‘Get selected points’ button.

**Comment by pawelfus** [comment]
It's already fixed on `hc5-fixes` branch: http://jsfiddle.net/f135k4xy/3/

Can be closed as soon as #6709 will be closed.
