### ISSUE TITLE
Chart will still trigger reflow after destoryed when window resize in internet explorer 8

### ISSUE THREAD

**Issue by Pennnn** [highcharts/highcharts#6746]
#### Expected behaviour
In IE8, it should not trigger the reflow event when the chart has been destroyed.

#### Actual behaviour
In IE8, after the chart has been destroyed, but the event attach to window hasn't been correctly removed;
so it still invoke the reflow when window is resizing.

#### Affected browser(s)
Internet explorer 8

**Comment by KacperMadej** [comment]
Hi Pennnn,

Thank you for reporting about the problem. However, I am unable to recreate the issue. Here's the code I used:
```
<html> 
  <head> 
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"> 
    </script>
    <script src="http://code.highcharts.com/highcharts.src.js"></script>
    <script src="http://code.highcharts.com/modules/exporting.src.js"></script>
  </head> 
  <body>
    <button id="button">Destroy the chart</button>
    <div id="container" style="height: 400px; margin: 0 auto;"></div>
    <script>
      Highcharts.chart('container', {
        series: [{
          data: [1,2,3]
        }]
      }, function (chart) {
        // the button handler
        $('#button').click(function() {
          chart.destroy();
          $(this).attr('disabled', true);
        });
      });
    </script>
  </body> 
</html>
```
Steps:
1. Press the button
1. Resize window

All is fine, no error.

@Pennnn Please provide a demo that will show the problem or a way to recreate, test and debug the issue.

**Comment by sebastianbochan** [comment]
@Pennnn please supply us a full number of IE8 version.

**Comment by Pennnn** [comment]
<html> 
      <head> 
        <meta http-equiv="X-UA-Compatible" content="IE=8" />
        <script src="jquery.min.js"> 
        </script>
        <script src="highcharts.src.js"></script>
       
        <script src="exporting.src.js"></script>
      </head> 
      <body>
        <button id="button">Destroy the chart</button>
        <button id="createBtn">create the chart</button>
        <div id="container1" style="height: 400px; margin: 0 auto;"></div>
        <div id="container2" style="height: 400px; margin: 0 auto;"></div>
        <div id="container3" style="height: 400px; margin: 0 auto;"></div>
        <script>
        $(function() {
          var charts = [];
          var createChart = function(id) {
            return new Highcharts.Chart({
                chart : {
                  defaultSeriesType : 'pie',
                  renderTo: id,
                },
                series: [{
                  data: [1,2,3]
                }]
              });
          };
          var createMutipleCharts = function() {
            $.each([1, 2, 3], function(index, item){
              charts.push(createChart('container' + item));
            });
          }

          $('#createBtn').click(createMutipleCharts);
          $('#button').click(function() {
              var c;
              while(c = charts.pop()) {
                c.destroy();
              }
          });
        
          createMutipleCharts();
        });
        </script>
      </body> 
    </html>

@KacperMadej thanks for your response. 
I found that this will only occurs when there are mutiple charts.
you can reproduce by step below.
Steps: 

1. Press the button 'Destroy the chart'
2. Press the button 'create the chart'
3. resize window
then it will throw error:   'options.chart' cannot be undefined  in line 16047 
But this is play well in chrome.

**Comment by Pennnn** [comment]
@sebastianbochan the version is 8.0.7601.17514

**Comment by Pennnn** [comment]
H.addEvent = function(el, type, fn) {
        
        var events = el.hcEvents = el.hcEvents || {};
        
        function wrappedFn(e) {
            e.target = e.srcElement || win; // #2820
            fn.call(el, e);
        }
        
        // Handle DOM events in modern browsers
        if (el.addEventListener) {
            el.addEventListener(type, fn, false);
            
            // Handle old IE implementation
        } else if (el.attachEvent) {
            
            if (!el.hcEventsIE) {
                el.hcEventsIE = {};
            }

            // Link wrapped fn with original fn, so we can get this in removeEvent
            el.hcEventsIE[fn.toString()] = wrappedFn;

            el.attachEvent('on' + type, wrappedFn);
        }
        
        if (!events[type]) {
            events[type] = [];
        }
        
        events[type].push(fn);
        
        // Return a function that can be called to remove this event.
        return function() {
            H.removeEvent(el, type, fn);
        };
    };

I think `el.hcEventsIE[fn.toString()] = wrappedFn;` cause this problem.
When you create mutiple charts, it will overide the previous one because `fn.toString()`is the same. 
So the 'resize' event cannot be correctly removed except the final one;

**Comment by KacperMadej** [comment]
@Pennnn Thank you very much for the debugging and help. I was also able to check that only one event is being removed, so in case of 3 charts - 2 events are not removed and are causing errors.

The problem seems to be as you have explained.

**Comment by fredure** [comment]
@KacperMadej 
Hello, this error is repeated if there are 4 diagrams on the page in IE11.
Will this query fix the error?? 
[073df36](https://github.com/highcharts/highcharts/commit/073df3634c6d6b1e9ce051b3585ab0fa1983e712)

**Comment by pawelfus** [comment]
It seems that IE11 was just updated (?) and broke something - just today, you are the third user reporting this issue, see #11553 - @KacperMadej is investigating the issue, will update #11553 ticket once he's ready. Please follow #11553
