### ISSUE TITLE
Possible to re-position the Highstock Navigator

### ISSUE THREAD

**Issue by ShMcK** [highcharts/highcharts#6750]
Is it possible to change the Highstock navigator's position so that is not next to the graph?

That is, the navigator is not simply above or below the graph, but a short distance away on the page.
This would require more than just x/y coordinates or absolute positioning.

**Comment by sebastianbochan** [comment]
You can create two charts, the first one is main chart and the second only navigator. As a result you can position navigator anywhere.

Example:
- http://jsfiddle.net/mL09syLj/

Please note github is our bug tracker, so for the further [support(http:///www.highcharts.com/support) questions, use email / stackoverflow / forum.
