### ISSUE TITLE
ActiveDataLabelStyle overrides styles set on a point

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#6752]
#### Expected behaviour
ActiveDataLabelStyle should not override styles that are specifically set on a point.

#### Actual behaviour
ActiveDataLabelStyle does override styles that are specifically set on a point.

#### Live demo with steps to reproduce
In http://jsfiddle.net/kzoon/am49zanx/2/ series with a low  score get red data labels
http://jsfiddle.net/kzoon/am49zanx/4/ enables drilldown, which overrides the red data label.

In http://jsfiddle.net/kzoon/am49zanx/4/ the data label of 'Fruits' should be bold and underlined because you can drill down, but it should be red, because I set the style of that particular data label to red. 

(See https://forum.highcharts.com/highcharts-usage/drill-down-overrides-color-set-on-point-t39079/)

**Comment by pawelfus** [comment]
Thank you for reporting this issue. I think you are right, styles should be merged with a higher priority for point options.
