### ISSUE TITLE
Gantt series points disappear on reversed xAxis

### ISSUE THREAD

**Issue by larsac07** [highcharts/highcharts#6755]
#### Expected behaviour
Gantt series points should be visible when reversing the xAxis

#### Actual behaviour
Gantt series points disappear when reversing the xAxis

#### Live demo with steps to reproduce
http://jsfiddle.net/LLExL/7543/

**Comment by KFoxder** [comment]
@larsac07 @oysteinmoseng do we have any update on this?

**Comment by jon-a-nygaard** [comment]
This issue seems to have been fixed somewhere before the current state of 66582e6 as seen by [this example](http://jsfiddle.net/ewqz1ht4/).

If the issue still exists please give us a comment and we will look into it.
