### ISSUE TITLE
Solid gauge highchart is not responsive 

### ISSUE THREAD

**Issue by RAFBOUK** [highcharts/highcharts#6756]
Hello,
I am currently working on an application and I use "solid gauge", I would like to have a gauge that fits all types of screen "iphone, ipad ... pc"

pane : {
		center : [ '50%', '85%' ],
		size : '170%',
		startAngle : -90,
		endAngle : 90, .....

How to adjust the size of the gauge according to the size of the window ? 
there is any responsive option for that ? 

thank's in advance

**Comment by RAFBOUK** [comment]
I find the solution, we can manipulate it with css :D

**Comment by pawelfus** [comment]
You can also use `responsive` rules, see [docs](http://api.highcharts.com/highcharts/responsive).
