### ISSUE TITLE
Month filter not working correctly with .NET wrapper

### ISSUE THREAD

**Issue by Neyjay** [highcharts/highcharts#6758]
#### Expected behaviour
When month filter is clicked, data values should only be shown for one month.

#### Actual behaviour
When month filter is clicked, all data values are shown.

#### Live demo with steps to reproduce
This happens in the example "1.7 million points with async loading"
http://dotnet.highcharts.com/Highstock/Demo/Gallery?demo=LazyLoading&theme=default

Just click the month filter and see that it shows an incorrect filter. When 2 months is filtered, it works. This only happens when the filter is set to 1 month.

This only happens in the .NET version!

#### Affected browser(s)
Chrome

Haven't tested others.

**Comment by pawelfus** [comment]
Thank you for reporting this issue! You are right `Count=1` looks broken.

**Comment by TorsteinHonsi** [comment]
Not a Highcharts bug but Highcharts .NET bug, so I'm closing it here. See https://github.com/highcharts/highcharts.net/issues/103#issuecomment-303359609
