### ISSUE TITLE
Boost - wrong color of area shape 

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6759]
#### Expected behaviour
The transparent color should be applied like in non-boost version.

#### Actual behaviour
The transparent color is not applied properly.

#### Live demo with steps to reproduce
Lets compare boost and non-boost examples.

- https://jsfiddle.net/t67w8q0k/
- https://jsfiddle.net/5zvu74nu/

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
@cvasseng See http://api.highcharts.com/highcharts/series%3Carea%3E.fillOpacity

**Comment by cvasseng** [comment]
This is definitely a bug - I'm already taking `fillOpacity` into consideration, so it's supposed to work. Will look into it.

**Comment by cvasseng** [comment]
When boosting line series, the `fillOpacity` is off by a factor of ten. Meaning, the alpha value that matches its svg counterpart is `fillOpacity / 10`. I added a temporary workaround for this until I get the chance to look more into it.
