### ISSUE TITLE
tooltip.enabled: false does not work when inside of responsive

### ISSUE THREAD

**Issue by RaquelRedondo** [highcharts/highcharts#6760]
#### Expected behaviour
Use tooltip: {enabled: false} to hide tooltip when resizing a chart below a threshold

#### Actual behaviour
It does not work.
As a workaround, I am setting 
         tooltip: {style: {display: "none"}}

#### Live demo with steps to reproduce

http://jsfiddle.net/rredondo/mdx82j8y/1/

#### Affected browser(s)
Chrome, Firefox

**Comment by pawelfus** [comment]
Thank you for reporting this issue. And for the workaround too!
