### ISSUE TITLE
Highchart excel export with multiple series skips data for scatter chart

### ISSUE THREAD

**Issue by SushantKadam008** [highcharts/highcharts#6761]
#### Expected behavior
When I export a highchart to excel with mutiple series and chart type as scatter it should show all series data. 

#### Actual behavior
In actual scenario, the x-axis data points are skipped. If we change the chart type to line then proper export takes place.

#### Issue sample

If we modify the JS fiddle at https://jsfiddle.net/pscjzhe4/1/?utm_source=website&utm_medium=embed&utm_campaign=pscjzhe4 

with the below data the issue can be reproduced
```
$('#example-1').highcharts({
   chart: {
      type: 'scatter'
   },
  title: {
    text: 'Monthly Average Temperature',
    x: -20 //center
  },
  subtitle: {
    text: 'Source: WorldClimate.com',
    x: -20
  },
  xAxis: {
    categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
    ]
  },
  yAxis: {
    title: {
      text: 'Temperature (°C)'
    },
    plotLines: [{
      value: 0,
      width: 1,
      color: '#808080'
    }]
  },
  tooltip: {
    valueSuffix: '°C'
  },
  legend: {
    layout: 'vertical',
    align: 'right',
    verticalAlign: 'middle',
    borderWidth: 0
  },
series: [{
    name: 'New York',
    data: [{x : -8.3 , y : 445.42},{x : -8.2 , y : 450.83},{x : -8.0 , y : 520.83},{x : -6.3 , y : 529.58},
    {x : -6.1 , y : 415.42}]
  },{
    name: 'Tokyo',
    data: [{x : -12.9 , y : 594.25},{x : -12.7 , y : 710.83},{x : -6.8 , y : 549.58}]
  }]
});
```

#### Affected browser(s)
All browser

**Comment by pawelfus** [comment]
It works fine for me, demo: https://jsfiddle.net/bsfmbwc8/

And this is the result:
[chart_download.xlsx](https://github.com/highcharts/highcharts/files/1022575/chart_download.xlsx)

Which looks like this:

<img width="352" alt="screen shot 2017-05-23 at 16 53 33" src="https://cloud.githubusercontent.com/assets/1453926/26360461/6f445438-3fd8-11e7-994d-7c6aedce675d.png">

Tested with: Chrome Version 58.0.3029.110 (64-bit) (OSX)

**Comment by SushantKadam008** [comment]
Hi,
This is not the correct data. It has skipped -8.3.
If you change the chart type to line instead of scatter and download again
it will show all the values.

**Comment by pawelfus** [comment]
You are right! I just noticed that values from first series are in wrong categories.

Minified demo: https://jsfiddle.net/cqjvD/1452/

**Comment by SushantKadam008** [comment]
HI @TorsteinHonsi ,
What was the fix ? Do I need to use latest version of export-csv ?

**Comment by TorsteinHonsi** [comment]
This is the fix: https://github.com/highcharts/highcharts/commit/12ce5022a80b32aebe7910fa345f2c047aa34436.

As indicated, the export-csv plugin is now deprecated. The Highcharts _module_ will be updated with the next maintenance release. Until then, you can apply the fix directly to the source code.

**Comment by SushantKadam008** [comment]
@TorsteinHonsi  : DO I need to use latest plugin of export-csv ? Where should I apply the fix ?

**Comment by pawelfus** [comment]
Please, try our pre-release version: http://github.highcharts.com/modules/export-data.src.js
