### ISSUE TITLE
Wrong category labels when switching from 'linear' do 'category' xAxis type

### ISSUE THREAD

**Issue by hellivan** [highcharts/highcharts#6762]
#### Expected behaviour
When I set the type of the xAxis to 'category' during runtime by calling the _setCategories_ method with an array of strings, the xAxis should display the labels passed to the _setCategories_ method.

#### Actual behaviour
After calling the _setCategories_ method with a labels array, the xAxis only shows categories labeled with sequential numbers (not necessarily starting by 1).

#### Live demo with steps to reproduce
To reproduce the issue, I had to initialize the chart with a usual linear series before setting the actual test-data with the categories. Hence, when only clicking the **Set categories1** or **Set categories2** button, the chart will behave as expected. However, when clicking on the **Set linear** button before, xAxis labels will break.

template: http://jsfiddle.net/hellivan/9nca5obd/ 

#### Affected browser(s)
ALL

**Comment by pawelfus** [comment]
Hi @hellivan 

My apologies for a delay! You are right, it is broken.

**Comment by TorsteinHonsi** [comment]
This issue is a quite subtle one - it comes from an internal optimization when setting new data. Series.update is directed to `setData`. The setData function, if the new data has the same length as the existing, just updates all points. And since the new points have no new X values, the X is not changed. 

#### Workaround 1:
Use setData with the `updatePoints` parameter set to false: http://jsfiddle.net/9nca5obd/4/

#### Workaround 2:
Explicitly set X values for new data: http://jsfiddle.net/9nca5obd/5/

**Comment by TorsteinHonsi** [comment]
Internally, I'm not sure how to handle it. If we change point.update, we break the possibility of changing only the Y value. We would need to do some trickery in setData I suppose, to check for new X values. But I have the feeling it could backfire.

**Comment by Joge97** [comment]
@TorsteinHonsi both workarounds do not work as expected:

Workaround 1:

- If you click to fast on `Set categories1` or `Set categories2` the bars are stacked

There are multiple ways to break workaround 2:

- `Set categories1` --> `Set categories2` --> `Set linear` -> `Set categories2`:
If you switch between the categories after clicking in this sequence, the categories and data are no longer updated
- `Set categories1` --> `Set categories2` --> `Set linear` --> `Set categories1`:
Now the X values are linear and not categories
- `Set linear` --> `Set categories1` --> `Set categories2`:
If you switch between the categories after clicking in this sequence, the X labels of the categories are no longer updated (always `test3` as label)
- `Set linear` --> `Set categories2` --> `Set categories1`:
If you switch between the categories after clicking in this sequence, the X labels of the categories are no longer updated (always `test` as label)

**Comment by pawelfus** [comment]
Hi @hellivan 

Second issue is conneced to a separate bug, that we use reference to the series.data options, so direct update of points updates array too. Using copy of the dataset: http://jsfiddle.net/BlackLabel/9nca5obd/7/ - resolves all of the issues.
