### ISSUE TITLE
Regression, color axis marker gone on treemaps

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#6763]
This is a regression in v5.0.11, specifically https://github.com/highcharts/highcharts/commit/3365e86bf.

#### Expected behaviour
The marker should be shown on the color axis when hovering.

#### Actual behaviour
No marker

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/highcharts/demo/treemap-coloraxis/

**Comment by jon-a-nygaard** [comment]
Treemap missing directTouch property. Workaround by setting `Highcharts.seriesTypes.treemap.prototype.directTouch = true`, as in following example: http://jsfiddle.net/jon_a_nygaard/6mw4f72j/
