### ISSUE TITLE
Flag series markers do not display text with the latest release(v5.0.12)

### ISSUE THREAD

**Issue by bb-jessePinkman** [highcharts/highcharts#6764]
Hey everyone, I'm currently using react-native-highcharts component to create interactive charts(Timeseries using highstocks), we were making use of flags/flag-series/flag-markers to display some information, as of today, they weren't displaying anything on click. The component react-native-highcharts uses online libraries, i.e from code.highcharts.com , and I noticed after changing the src to point to older release(4.2.2), the flags displayed the text fine.

I checked the change logs, might have missed something, please update if its a bug or something has been changed. Thanks.

#### Expected behaviour
Should display text when clicked upon.

#### Actual behaviour
Nothing is display when clicked upon.

**Comment by pawelfus** [comment]
Hi @bb-jessePinkman 

Our demo works fine, take a look: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/flags-general/ Could you update this demo to recreate issue? Otherwise it may be issue in react-native-highcharts component.

**Comment by pawelfus** [comment]
Sorry, the title was misleading. I assume you mean tooltip doesn't show up. 

Demo with this issue: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/flags-general/

**Comment by h3adache** [comment]
Hi @pawelfus. I noticed this as well but why is this marked as `Can't reproduce`? The fiddle you linked shows the exact issue. Flag series text don't show up.

**Comment by h3adache** [comment]
Dropping to 5.0.11 makes them appear again.

**Comment by pawelfus** [comment]
Hi, it's not marked as `Can't reproduce`. Flag was added and removed, my mistake, sorry.

**Comment by h3adache** [comment]
Apologies, my fault. Read it wrong.

**Comment by pldilley** [comment]
The mouse events are broken too in 5.0.12.

**Comment by pawelfus** [comment]
You are right. For now, please use v5.0.11.

**Comment by ff-sgupta** [comment]
When is the next  release for this fix?

**Comment by pawelfus** [comment]
Hi @ff-sgupta 

We don't have ETA for this issue, but I think it will be fixed in the next release.

**Comment by ff-skundalkar** [comment]
Can you please let us know when can we get this fix ? This is impacting us and have an feature in escalation currently. Can you provide a hot fix to us ?

**Comment by TorsteinHonsi** [comment]
The new release will be out within a few weeks. Until then, you can apply this to the source code: https://github.com/highcharts/highcharts/commit/46738ea80e9754b93417a38d565aebe1edb96844

**Comment by FlorianBurgevin** [comment]
Version 5.0.14 is here but this bugs seems to be still there :(

**Comment by KacperMadej** [comment]
@FlorianBurgevin Looks fine for me: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/flags-general/

Do you have another demo that could show the problem?

Please try to make sure that newer version of Highcharts is loaded.

**Comment by FlorianBurgevin** [comment]
My bad sorry !
The newer version was not loaded correctly
