### ISSUE TITLE
Renderer.label css color 'contrast' is not working

### ISSUE THREAD

**Issue by Ramyani** [highcharts/highcharts#6767]
I was trying to use `color: 'contrast' ` using Renderer.label css. But it seems it is not working.
http://jsfiddle.net/na2cf1yL/

**Comment by sebastianbochan** [comment]
By default in the CSS there is not "contrast" color.

Example:
- https://jsfiddle.net/bx9eocvw/

You can apply contrast as textOutline: http://jsfiddle.net/na2cf1yL/1/
