### ISSUE TITLE
Drilldown show datatables

### ISSUE THREAD

**Issue by drunkBottle6** [highcharts/highcharts#6768]
Hi all,
I have a question here about drilldown in highchart.
is it possible to show tables after click the chart?

[Chart Example](http://jsfiddle.net/gh/get/jquery/2/highcharts/highcharts/tree/master/samples/highcharts/drilldown/basic/)
when i click the animal category, its will show the data with table view not chart view.

sorry if my English bad
Thanks a lot.

**Comment by pawelfus** [comment]
Hi @drunkBottle6 

This is our bug tracker, for questions please use our other support channels, [details](https://www.highcharts.com/support).

**Comment by drunkBottle6** [comment]
Ok thanks a lot @pawelfus 
im will submit t there.
