### ISSUE TITLE
Empty row for every redundant taskName

### ISSUE THREAD

**Issue by milankmr** [highcharts/highcharts#6770]
#### Expected behaviour
Should not show the empty row for redundant taskName

#### Actual behaviour
Showing empty row for redundant taskName

#### Live demo with steps to reproduce
https://jsfiddle.net/s2zd539y/

#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Thank you for reporting the issue. We are aware of it, from [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/804783-gantt-chart):

> ​- Multiple tasks on a single y-value (X-range study: http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/studies/xrange-series/)

**Comment by Izothep** [comment]
+1

**Comment by oysteinmoseng** [comment]
Fixed now, control this behavior with `yAxis.uniqueNames` https://jsfiddle.net/s2zd539y/2/
