### ISSUE TITLE
'mouseup' Event is not set when the div container is in an iframe

### ISSUE THREAD

**Issue by RaquelRedondo** [highcharts/highcharts#6771]
#### Expected behaviour
Mouse events to work correctly when interacting with the navigator and the chart plotting area.

#### Actual behaviour
Because the 'mouseup' event is not being set properly, the mouse stays in a 'dragging' state when clicking on the chart plotting area and navigator.

I noticed that the mouseup event is set using this function: 
     addEvent(doc, 'mouseup', someHandler);

To get the behavior I want, I have changed this to :
     addEvent(container, 'mouseup', someHandler);

But I am unsure whether this change will cause other unwanted problems, or not. 

This problem happens because the mouse events are not being set to the iframe's document object to which the container belongs to.

#### Live demo with steps to reproduce
http://jsfiddle.net/rredondo/hxjjr3hv/
I could not get the fiddle working on Firefox, just the latest version of Chrome and IE.

#### Affected browser(s)
Chrome, Firefox

**Comment by pawelfus** [comment]
Thanks for reporting! It looks like the same issue when we want to zoom-in, see #2849.

**Comment by RaquelRedondo** [comment]
Hi, 
Yes, it is the same underlying problem. Do you think you are going to address this issue soon?

**Comment by RaquelRedondo** [comment]
Another possible related issue is #6446

**Comment by TorsteinHonsi** [comment]
_Internal note_:

Probably the events on _doc_ should be set on _container.ownerDocument_ instead, to ensure we are not dealing with two different documents. But I am not sure what side effects may occur.

**Comment by RaquelRedondo** [comment]
Hi, @TorsteinHonsi,
Your commit didn't resolve the issue for me. It seems that the issue is only fixed when the line inside the setDOMEvents function is changed from:
    addEvent(doc, 'mouseup', pointer.onDocumentMouseUp);
to:
    addEvent(container.ownerDocument, 'mouseup', pointer.onDocumentMouseUp);
