### ISSUE TITLE
Highcharts/highstock incorrectly calculates the displayed tick interval when using y-axis breaks

### ISSUE THREAD

**Issue by ransoing** [highcharts/highcharts#6772]
#### Expected behaviour
When using y-axis breaks, highcharts/highstock should place ticks at a reasonable interval, or at the interval specified by `tickInterval` if there is enough room.

#### Actual behaviour
It seems like highcharts calculates the displayed tick interval based on the range of the y-axis, but the problem is that it does this without taking breaks into account.

In the demo below, I've set `tickInterval` to `1`. Without any y-axis breaks, the displayed tick interval is `4`, because there's not enough room to display ticks at an interval of `1`. This is reasonable and expected. However, when you increase the size of the y-axis break, the displayed tick interval remains at `4`, even though there's plenty of room to display ticks at a smaller interval.

http://jsfiddle.net/jn90g57q/3/

The issue is present even when `tickInterval` isn't specified, and setting `minTickInterval` doesn't help any.

**Comment by ransoing** [comment]
The issue is also present in one of the official highcharts demos:
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/axisbreak/break-visualized/

`tickInterval` is set to `100`, but the displayed interval is `300` despite there being enough room for more ticks.

**Comment by pawelfus** [comment]
Thanks for reporting! You are right, it looks broken.

It's possible to use `tickPositioner`, but it won't hide overlapping ticks: http://jsfiddle.net/jn90g57q/4/
