### ISSUE TITLE
Cannot update xAxis range dynamically

### ISSUE THREAD

**Issue by ShMcK** [highcharts/highcharts#6773]
Calling update should change the xAxis range, but doesn't.

```js
Highcharts.stockChart('container', {
    xAxis: {
        range: 6 * 30 * 24 * 3600 * 1000 // six months
    },
    rangeSelector: {
        enabled: false
    },
    series: [{
        name: 'USD to EUR',
        data: usdeur
    }]
});


setTimeout(() => {
 $('#container').highcharts().xAxis[0].update({
   range: 12 * 30 * 24 * 3600 * 1000 // 1 year
 });
 alert('should be one year. Is still six months')
}, 3000);

```

See [Live Example](http://jsfiddle.net/480kgtch/)

**Comment by pawelfus** [comment]
Hi @ShMcK 

Thank you for reporting the issue. It looks like the extremes from navigator have higher priority than `range` option.

**Workaround:**
Use `Axis.setExtremes()` instead of `Axis.update({range: newRange})`. Demo: http://jsfiddle.net/mfroh6b4/
