### ISSUE TITLE
Y Axis labels misleading when values are huge

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6774]
#### Expected behaviour
When values are huge, the y axis labels should be correctly rendered. (At least the exponent part should be consistent throughout the ticks)

#### Actual behaviour
The y axis labels rendered in the following fiddle are misleading since the sequence is wrong (8 to 1) and there is a direct jump from 1 to 1.2e+23

#### Live demo with steps to reproduce
http://jsfiddle.net/an096w0k/

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Thank you for the reporting. 

**Workaround**
Use labels.formatter and return this.value.
- http://jsfiddle.net/4eL35xh3/
