### ISSUE TITLE
Wrong color of hovered flags and 3d columns caused by animation.

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6776]
#### Behaviour:
Flags are black because `fill` and `stroke` are `rgba(NaN,NaN,NaN,NaN)` 

#### Offending commit:
https://github.com/highcharts/highcharts/commit/222eae0

#### Live demo with steps to reproduce
http://jsfiddle.net/z33cj4rv/

Hover over flags to make them black.

**Comment by Izothep** [comment]
It looks that similar issue is visible in 3d columns chart: http://jsfiddle.net/z33cj4rv/3/

**Comment by nickdeamons** [comment]
I ran into the wrong color (black) displaying on the solidgauge chart. I was changing the yAxis maximum and the chart measurement would render with the fill, rgba(NaN,NaN,NaN,NaN).  I cannot post my code at the moment. I'll try a fiddle soon.

**Comment by KacperMadej** [comment]
@nickdeamons Mine and Izothep's issues are about github - pre-release - version of the code. If your problem is visible with the current (or any published) version of Highcharts then this will probably be a different issue, so a demo is very crucial.

**Comment by nickdeamons** [comment]
I figured out the issue, it was due to me trying to initially populate the chart with NaN
