### ISSUE TITLE
Highcharts - textOverflow ellipsis for axis titles not working in 5.0 as it did in 4.2.7

### ISSUE THREAD

**Issue by pavaleanuL** [highcharts/highcharts#6778]
#### Expected behaviour
When the title for the y axis is long, using overflow - hidden, textOverflow - ellipsis and setting a width would make the title look ok - as in http://jsfiddle.net/0qdyqh3h/1/ (which is using 4.2.7)

#### Actual behaviour
With version 5, setting these styles have no effect - http://jsfiddle.net/0qdyqh3h/
I have tried several stylings, even with css and could not fix this.

#### Live demo with steps to reproduce
http://jsfiddle.net/0qdyqh3h/

**Comment by pawelfus** [comment]
Thank you for reporting this issue.

*Internal note:*
It's broken since 5.0.10, responsible commit: 65eea38

**Comment by pavaleanuL** [comment]
Is there a workaround we can use, or we have to wait until it is fixed in a later release?

Thank you.

**Comment by pawelfus** [comment]
For now, I suggest to use 5.0.10 version if you need this design, I don't see any better workaround.

**Comment by sebastianbochan** [comment]
@pavaleanuL as a workaround, set `useHTML` flag as true in the `yAxis.title.`

Demo:
- http://jsfiddle.net/qdr8csut/
