### ISSUE TITLE
When min and max are given, ticks are not rendered properly

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6780]
#### Expected behaviour
When min and max for y axis are given, the ticks should be rendered accordingly.

#### Actual behaviour
In the fiddle below, for the secondary axis, the max tick is incorrect.

#### Live demo with steps to reproduce
http://jsfiddle.net/q3wwgnkc/1/

#### Affected browser(s)
Chrome

**Comment by oysteinmoseng** [comment]
Is this not expected behaviour? The blue line is series 1, which belongs to the first yAxis, which has `min: 0` and `max: 100`.

**Comment by sagargurtu** [comment]
Oh. Sorry for my stupidity. Closing the issue.
