### ISSUE TITLE
Data labels misaligned for x axis with height on inverted chart

### ISSUE THREAD

**Issue by robahs** [highcharts/highcharts#6781]
#### Expected behaviour
The data label should be placed near the point.

#### Actual behaviour
The data label is misaligned.

#### Live demo with steps to reproduce
http://jsfiddle.net/ofw5adeg/2/

#### Affected browser(s)
All browsers

**Comment by oysteinmoseng** [comment]
Thank you for reporting. Minimal example: http://jsfiddle.net/ofw5adeg/3/.
