### ISSUE TITLE
3d scatter demo is broken on touch devices

### ISSUE THREAD

**Issue by blackChef** [highcharts/highcharts#6784]
- There's no `touchdrag` event, this should be `touchmove` I believe.

         $(document).on({
            'mousemove.hc touchdrag.hc': function (e) {...

-  Touch events don't have `pageX` or `pageY`. I believe we are supposed to use `chartX` `chartY` instead. Otherwise `chart.pointer.normalize(eStart)` would be pointless.
    
        eStart = chart.pointer.normalize(eStart);

        var posX = eStart.pageX,
            posY = eStart.pageY,
            alpha = chart.options.chart.options3d.alpha,
            beta = chart.options.chart.options3d.beta,
            newAlpha,
            newBeta,
            sensitivity = 5; // lower is more sensitive

        $(document).on({
            'mousemove.hc touchdrag.hc': function (e) {
                // Run beta
                newBeta = beta + (posX - e.pageX) / sensitivity;
                chart.options.chart.options3d.beta = newBeta;

**Comment by pawelfus** [comment]
Thank you for reporting this issue! You are right it doesn't work with current config on touch devices, working example: http://jsfiddle.net/7k4a026x/
