### ISSUE TITLE
Funnel dalabels are cut

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6785]
#### Expected behaviour
Datalabels should be visible as in 5.0.11

#### Actual behaviour
Dalabels are cut

#### Live demo with steps to reproduce
Demos:
- 5.0.11 http://jsfiddle.net/vxwan5ba/
- 5.0.12 http://jsfiddle.net/jo7kLtey/

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
It is correct behaviour that the data labels are clipped when falling outside the plot area. It is a result of a bug fix on pie charts.

The problem with the funnel demo is that it uses chart.marginRight to make room for the labels, while it should use width and centering of the funnel instead. This has already been updated in the samples. See http://jsfiddle.net/highcharts/jo7kLtey/1/
