### ISSUE TITLE
Show animate when see charts block

### ISSUE THREAD

**Issue by Pantela777** [highcharts/highcharts#6786]
I use **highcharts** to my project, where page design has loading BG overlay, also when page is loading full, overlay is hiding, but I can't see **highcharts** line animate, because is already done before overlay is hide...

So, how I can to start animate it, when **highcharts** block is see, or maybe have another solutions?
I just use "**waypointScroll**" script, try to use with this.

P.S.  can't call **highcharts** from my loading BG functions.

**Comment by sebastianbochan** [comment]
Thank you for contating us. Unfortunately this is our bugtracker, so please use forum / stackoverflow / email for the further [support](http://www.highcharts.com/support).

ps. please supply us simplified demo on the jsfiddle.net which will allow us to investigate the issue.
