### ISSUE TITLE
Range selector on chart

### ISSUE THREAD

**Issue by lukemr** [highcharts/highcharts#6787]
Is it possible to do something like on an attached picture.
Those triangles will be used to select range on chart. 
I'm aware of range selector but it is rendered below the chart. my requirements is to do it on chart.

thanks in advance on any help
![chart](https://cloud.githubusercontent.com/assets/588298/26685966/9407b746-46b9-11e7-8573-ecadcf2f0d5b.PNG)

**Comment by pawelfus** [comment]
Hi @lukemr 

This is our bug tracker. For questions, please send us an email or write a post on our forum. See [details](https://www.highcharts.com/support).
