### ISSUE TITLE
Bubble chart only possible with highcharts-more.js

### ISSUE THREAD

**Issue by mslourens** [highcharts/highcharts#6789]
In the documentation it does not say you need highcharts-more.js to be able to use Bubble as chart type

#### Expected behaviour
It should say that highcharts-more.js is required in order to use bubble chart, like AreaSplineRange (where it says: 'Requires highcharts-more.js.') - http://api.highcharts.com/highcharts/plotOptions.arearange

#### Actual behaviour
The docs don't say you need the extra script.

#### Live demo with steps to reproduce
http://jsfiddle.net/mslourens/dongL6xe/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks! You are right, it should mention that `highcharts-more` is required.

**Comment by pawelfus** [comment]
Fixed in the new API docs.
