### ISSUE TITLE
Bubble series symbol doesn't reset to default when set to `null`

### ISSUE THREAD

**Issue by hon2a** [highcharts/highcharts#6792]
I'm rendering a bubble chart with an enhancement - points with zero size are rendered using a custom "cross" symbol. The default for the series in the chart is to use the "circle" symbol. It's set up through `plotOptions.bubble.marker.symbol`. The point data for zero-size points looks like this:

```
{ x: 12, y: 34, z: 0, marker: { symbol: 'cross' } }
```

and for regular points like this:

```
{ x: 12, y: 34, z: 56, marker: { symbol: null } }
```

#### Expected behaviour

When I call `.setData()` on the series with updated points' sizes and symbols, the symbols should update (to crosses for points that now have zero size, back to circles for points that don't have zero size anymore).

#### Actual behaviour

When the points markers' symbols get updated from `'cross'` to `null`, the symbol doesn't change.

#### Live demo with steps to reproduce

http://jsfiddle.net/hon2a/9x95qwqe/

_(It doesn't show the scenario described above, but it clearly shows how the symbol doesn't change, but resetting e.g. `color` to `null` works just fine.)_

#### Affected browser(s)

All.

**Comment by pawelfus** [comment]
Hi @hon2a 

Thank you for reporting. You are right, symbol should change too. At this moment, it's necessary to set strict symbol, `null` won't work: http://jsfiddle.net/341qq3pc/

**Comment by hon2a** [comment]
Sorry, misclicked :)
