### ISSUE TITLE
In Highstocks 5.0.12 flag series events are not working

### ISSUE THREAD

**Issue by KaranTankshali** [highcharts/highcharts#6793]
When adding a flag series, point.events.click should capture the click on flag, instead it captures the click on the chart, this is an issue introduced in 5.0.12

#### Live demo with steps to reproduce

a fiddle for issue, if you revert to 5.0.11 cdn then it works as expected
http://jsfiddle.net/a10k8sep/2/

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @KaranTankshali 

Thank you for reporting, it's the same issue as #6764 - all flag events are broken.
