### ISSUE TITLE
dataLabels.style = {cursor: 'pointer'} doesn't work when useHTML flag is set to true

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#6794]
Cursor should change to pointer while hovering labels:
https://jsfiddle.net/bobliberty/mesfy46g/

It doesn't work for activeDataLabelStyle within drilldown either:
http://jsfiddle.net/7uz4wvry/2/

**Comment by KacperMadej** [comment]
As a workaround it's possible to add another text property for SVGElement.prototype in textProps like:

`Highcharts.SVGElement.prototype.textProps.push('cursor');`

Demo: http://jsfiddle.net/7uz4wvry/3/

**Comment by sebastianbochan** [comment]
**Workaround:**
Use css styles for datalabels' span

Demo:
- http://jsfiddle.net/yqgujghk/

**Comment by bobliberty7777** [comment]
Unfortunately neither of those workarounds really work since it would apply the style to all data labels, not just the ones with drilldown data.

**Comment by sebastianbochan** [comment]
Could you update our demos with your code to introduce that it does not work properly?
