### ISSUE TITLE
hoverable tooltips for axis plotlines

### ISSUE THREAD

**Issue by efx** [highcharts/highcharts#6795]
#### Expected behaviour
I expect to configure Highcharts to allow me to configure a chart's plot line tooltip that behaves like tooltips for series data. 

#### Actual behaviour
Axes plot lines only allow configuring a label which is fixed to one part of the chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/tw6rmc1r/
In our application, I have created tooltips for plot lines by dynamically modifying the chart configuration when the plot line is hovered over. I think it would be useful to provide this option as a configuration setting, or highcharts plugin to enable this. Are there any plans to support this behaviour?

#### Affected browser(s)
N/A.

**Comment by pawelfus** [comment]
Hi @efx,

For feature requests please use our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api). In general, the most popular ideas are implemented as plugins/modules/core parts.

General idea without updating chart is to use internal classes and methods: http://jsfiddle.net/tw6rmc1r/2/

**Comment by efx** [comment]
thanks for the update and sample code @pawelfus. I will log something there and close this.

**Comment by efx** [comment]
Submitted idea here: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/19504105-hoverable-tooltips-for-axes-plot-lines
