### ISSUE TITLE
X axis label missing when using getTimezoneOffset, tickInterval, and DST transition occurs

### ISSUE THREAD

**Issue by AHelper** [highcharts/highcharts#6797]
#### Expected behaviour
All labels should be rendering for the x axis.

#### Actual behaviour
A label is missing when a transition occurs.

#### Live demo with steps to reproduce
http://jsfiddle.net/rpxvnmot/2/
Shows DST transition on 2017-11-05 for EST.  Axis correctly shows 1:00 rolling back to 1:00, but then 5:00's tick is absent.

Bug was introduced 5.0.0 -> 5.0.1, still exists in master.

#### Affected browser(s)
Chrome 58, FireFox 53.0.2, IE 11

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

It looks like only one time change is being handled. When having 3 time changes there are two missing labels - demo: http://jsfiddle.net/r2m15m6d/

Have you tried using moment.js to get proper time for a required time zone? API reference: http://api.highcharts.com/highstock/global.getTimezoneOffset

**Comment by AHelper** [comment]
Interesting. Also to note, the number of hours that are skipped in transition seem to equate to the number of labels missing (with hour tickInterval), and the first label(s) missing is an offset from the DST transition hour based on the timezone offset returned before transition.

And yes, there's a library behind the actual timezone handling, however the fiddle I made was very simplified with regards to timezone handling.

**Comment by KacperMadej** [comment]
First problem that we could resolve sooner here is to adjust the existing gap to the duplicated label. Currently the gap exists in a not intuitive place that is based on base time zone offest (time zone on first tick). Commit for this change should be above this comment.

Reason for the gap is to have tick/labels on same hours each day and to avoid doubled day label problem in #4951 reported in [this comment](https://github.com/highcharts/highcharts/issues/4951#issuecomment-253781009).

To have constant tick interval and resolve this issue we could add an option for it in API. However, viewing chart in that way will change hour ticks and might change midnight labels (that are automatically translated to day labels) to 23:00 or 1:00 depending on direction of time change. For now here's a workaround in form of a wrapper: http://jsfiddle.net/yqu9hve8/

New option is `dateRelevantIntervalSize`. It's an axis option and when set to false hour ticks will have constant time interval and not, as it is with the current default logic, on same clock hour over each day.

@TorsteinHonsi How about adding this option to API? Name might be changed to something more self-explanatory, however this is the best I could come up with.

**Comment by TorsteinHonsi** [comment]
> How about adding this option to API?

Not sure... Do we really want ticks on "uneven" hours like 01:00 and 23:00?

**Comment by KacperMadej** [comment]
@TorsteinHonsi I am not sure how popular or useful this feature could be, so this could be left as is (with the above commit). There's a workaround in my previous comment, so if anyone needs to use this like that could use that solution.

@AHelper Will this work for you? Could this issue be closed?

**Comment by AHelper** [comment]
@KacperMadej Works for me, thanks a bunch!
