### ISSUE TITLE
y-axis title not truncated well in latest version

### ISSUE THREAD

**Issue by ipip2005** [highcharts/highcharts#6799]
#### Expected behaviour
http://jsfiddle.net/fvfh05zw/6/

#### Actual behaviour
http://jsfiddle.net/fvfh05zw/7/

#### Live demo with steps to reproduce
Seems a **regression** of y-axis title that displaying well in 4.1.6 but not truncated in latest version?

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Set the useHTML flag as a true for the yAxis title.

Demo:
- http://jsfiddle.net/f0z3muxj/
