### ISSUE TITLE
minRange with one category displays not existing categories

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6800]
#### Expected behaviour
"x" zoomType should work properly, irrespective of number of data points plotted.

#### Actual behaviour
In the following fiddle, when the number of data points are less, "x" zoomType does not work properly (it zooms only a little bit), whereas, "y" zoomType does.

#### Live demo with steps to reproduce
http://jsfiddle.net/fn6svmwy/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
It doesn't zoom because `minRange` is not set, demo: http://jsfiddle.net/fn6svmwy/1/ and [docs](http://api.highcharts.com/highcharts/xAxis.minRange).

**Comment by sagargurtu** [comment]
Hi @pawelfus 

This is not working for the case when x axis has string categories. "-1" and "1" should not be visible on the extremities of x axis. Please refer http://jsfiddle.net/fn6svmwy/2/

Thanks

**Comment by sebastianbochan** [comment]
You can set min/max as 0 or use tickPositions and return array with 0 value.

Demos:
- http://jsfiddle.net/02tycw0m/
- http://jsfiddle.net/L68w9axg/

**Comment by sagargurtu** [comment]
Hi @sebastianbochan 

But in my case, number of x axis categories are dynamic. So, for categories greater than 1, above solution does not work.

Thanks

**Comment by pawelfus** [comment]
Reopening and changing issue title.

**Comment by sebastianbochan** [comment]
@sagargurtu it was simplified demo, which you can replace with more flexible solution, which extracts length of categories, dynamically.

Ref:
- http://jsfiddle.net/ymrzja7t/
