### ISSUE TITLE
Highcharts column chart: Update xaxis label with data object not responsive

### ISSUE THREAD

**Issue by ipip2005** [highcharts/highcharts#6801]
#### Expected behaviour
The text label in x-axis should be resized and truncated when I change it.

#### Actual behaviour
The text label expands and overlap with other text.

#### Live demo with steps to reproduce
http://jsfiddle.net/v2nu1g1n/
Click the button to see results

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @ipip2005 

Thank your for reporting this issue. Note it only happens with specific widths so in general it's a good practice to set fixed width when reporting bug. 

Example with fixed width: http://jsfiddle.net/v2nu1g1n/2/

It works fine for widths <= 400: http://jsfiddle.net/v2nu1g1n/3/

**Workaround:**
Force axis to recalculate labels, for example using `Axis.update()`, demo: http://jsfiddle.net/v2nu1g1n/4/

**Comment by ipip2005** [comment]
Thank you for Quick response, the workaround looks working and I'll try it in my code.
