### ISSUE TITLE
labels are getting overlaped in x-axis labels when the chart shrunk.

### ISSUE THREAD

**Issue by nishanth-satmetrix** [highcharts/highcharts#6802]
how to adjust the labels in x- axis label when chart shrunk..

Please help for this

Thanks in Advance
Nishanth

**Comment by sebastianbochan** [comment]
Hi Nishanth, 
Thank you for contacting us, but this is our bugtracker. For the [support](https://www.highcharts.com/support) questions, please use email / stackoverflow or forum.
