### ISSUE TITLE
Lines overflow chart area in offline PDF export

### ISSUE THREAD

**Issue by michaljanda** [highcharts/highcharts#6805]
#### Expected behaviour
When you restrict visible window by setExtremes function then exported PDF should reflect the visible window.

#### Actual behaviour
When you use offline export then line overflows from the chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/aps5e3e8/1/  use button at first and then use pdf export from chart menu.

**Comment by pawelfus** [comment]
Thank you for reporting this issue!

**Comment by sebastianbochan** [comment]
_Internal note_
@oysteinmoseng its related with issue from email

**Comment by oysteinmoseng** [comment]
Workaround: Use online export server for PDF export only http://jsfiddle.net/c6oqx5sg/2/
