### ISSUE TITLE
Error 27 is the same as error 26

### ISSUE THREAD

**Issue by bistory** [highcharts/highcharts#6806]
In latest release, highcharts.src.js, line 2022, calls error "Series type already defined"

Which sends the user to https://www.highcharts.com/errors/27.

Problem, this error is not the one expected... error 27 has the same message as error 26.

So the message defined for error 27 is not the good one.

I hope this will help you ;-)

**Comment by pawelfus** [comment]
Thanks for reporting!

Error 27 will be removed in the next release, please disregard this. See discussion in #6686
