### ISSUE TITLE
Pie chart does not render tooltips when "shared" is set to true in v5.0.12

### ISSUE THREAD

**Issue by JllyGrnGiant** [highcharts/highcharts#6808]
#### Expected behaviour
Setting "shared" to true does not affect whether pie chart tooltips appear
http://jsfiddle.net/33fgjq24/

#### Actual behaviour
Setting "shared" to true causes tooltip to not render
http://jsfiddle.net/c78y0ekp/

**Comment by JllyGrnGiant** [comment]
May also affect funnel charts.

**Comment by sebastianbochan** [comment]
Currently shared option does not support series types with non ordered data (pie, scatter, flags etc).

Docs:
- http://api.highcharts.com/highcharts/tooltip.shared
