### ISSUE TITLE
Highcharts column chart, need a way to make colors consistent between positive and negative

### ISSUE THREAD

**Issue by ipip2005** [highcharts/highcharts#6809]
The cool feature in Highcharts is that when default color is used, the
1. Data point color.
2. Tooltip border.
etc..
elements describing the same data point will have the same color.

When I try to apply customized color (for supporting theme) to column chart data point, I didn't find a way to align the color between positive and negative values. For example,
I want all positive column to have 'blue' color, their tooltip border should also be blue. 
I want all negative column and their tooltip border to be 'red' color.
I can using css to select positive data point or negative data point, but seems there is no way to select **tooltip describing positive value** or **tooltip describing negative value**

Maybe we can use the same pattern as **class="highcharts-color-x"**, for example, add class name "highcharts-positive" to the tooltip elements so we can use css to style them to be aligned with data point color?

**Comment by sebastianbochan** [comment]
@ipip2005 
Thank you for contacting us. This is our bugtracker, so for the [support](https://www.highcharts.com/support) please use email / stackoverflow or forum.

ps. How about http://jsfiddle.net/8be2a4ob/ ? It seems to solve your issue.
