### ISSUE TITLE
Chart does not reflow if created after json request

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#681]
Using this example: http://jsfiddle.net/Gh8VM/
1. Make sure that the height of the chart is big enough to force a scrollbar
2. Click run

Result: The chart does not reflow to fit inside the slightly smaller area now that the scrollbar is visible.
Forum thread: http://highslide.com/forum/viewtopic.php?f=12&t=14208

**Comment by TorsteinHonsi** [comment]
Still valid in Highstock v6.1.0: http://jsfiddle.net/highcharts/Gh8VM/3/
