### ISSUE TITLE
The same trigger value for setExtremes and Reset Zoom Button

### ISSUE THREAD

**Issue by SebaEnaMor** [highcharts/highcharts#6810]
#### Expected behaviour
Selecting new extremes should return `e.trigger` message `zoom` - like it is now.
Click on the Reset Zoom Button should return `e.trigger` message `resetZoom` or any other, but different than `zoom`.

#### Actual behaviour
Selecting new extremes and clicking on 'Reset Zoom Button' now returns the same e.trigger message named "zoom".

#### Live demo with steps to reproduce
http://jsfiddle.net/p9247tfv/
You need to run web browser console to see the message in console.log.

#### Affected browser(s)
Mozilla Firefox 53.0.3
Google Chrome 58.0.3029.110

**Comment by sebastianbochan** [comment]
Thank you for the reporting.

_Internal note_
We should check `this.displayBtn` flag in `zoom` method and then set proper trigger value.

Demo:
- http://jsfiddle.net/1jeuj89p/

**Comment by SebaEnaMor** [comment]
Hi @sebastianbochan 
Thanks for the workaround. It is works well for me.

**Comment by sebastianbochan** [comment]
Thank you for the feedback.

@TorsteinHonsi I can commit it, but a little bit afraid about 'back compatibility' and as a result some users' projects can be broken by new "trigger" value. What do your opinion ?

**Comment by TorsteinHonsi** [comment]
Strictly speaking it's not a bug, and probably we don't need to add another value for the `trigger` property. It may be enough to compare to `dataMin` and `dataMax` to determine that we're dealing with a reset: http://jsfiddle.net/highcharts/p9247tfv/1/

@SebaEnaMor Do you find this solution acceptable?

**Comment by SebaEnaMor** [comment]
The solution provided by you both guys (@TorsteinHonsi and @sebastianbochan) is acceptable for me.
Thanks for your time.
