### ISSUE TITLE
Accessibility: How can make the elements read aria-label when focused?

### ISSUE THREAD

**Issue by ipip2005** [highcharts/highcharts#6813]
I tried this demo http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/accessibility/accessible-line/
from https://www.highcharts.com/docs/chart-concepts/accessibility
But I tried IE + JAWS, Firefox + NVDA, Edge + Narrator, none of them will read the aria-label when I move focus to the data point.

**Comment by sebastianbochan** [comment]
Thank you for the reporting.

@oysteinmoseng

**Comment by ff-sgupta** [comment]
I have the following observations with different screen readers

1. ChromeVox: Using tab key the focus moves to the data points and aria-label is read (tooltip is visible as well)
2. JAWS + IE11: Using down arrow key (as it gets narrated when focus moves to the chart) it reads the aria-label for the datapoint. However the tooltip is not displayed

**Comment by ipip2005** [comment]
Thanks, it's great ChromeVOX can read something.
I've known that SVG accessibility is a urgent area for accessibility so I was pretty interested in how you're making the SVG chart accessible. Probably should wait for browsers/ATs to invest more on SVG. As I saw from Edge accessible tree, the aria-label on SVG elements haven't been exposed yet.

Thank you for reply
Close it now.

**Comment by oysteinmoseng** [comment]
@ipip2005 @ff-sgupta Thank you for testing. This is consistent with our findings. JAWS and NVDA are generally able to read the chart by down-arrowing or tabbing in most browsers. Clicking the points to read I think maybe works in Edge + Narrator, but I don't think it works elsewhere. To my knowledge there is little we can do right now to improve this, as it's all in the browser/AT.

**Comment by ipip2005** [comment]
@oysteinmoseng sounds fair, thanks for the details

**Comment by saroj08** [comment]
Narrator is not reading the tooltip ,so what necessary changes i have to make in accessibility.js file

**Comment by oysteinmoseng** [comment]
@saroj08 The Edge team are working on a fix that should help Narrator support. To my knowledge there is nothing we can do to improve Narrator support until then.

**Comment by saroj08** [comment]
thanks for the information @oysteinmoseng
