### ISSUE TITLE
Pie Chart sliced translation - The shadow overlaps the slice when the slice slides out on mouse hover

### ISSUE THREAD

**Issue by ff-sgupta** [highcharts/highcharts#6814]
#### Expected behaviour
Shadow should follow the slice translation

#### Actual behaviour
Shadow overlaps the slice

#### Live demo with steps to reproduce
http://jsfiddle.net/5H675/5/
Hover over the blue slice. Shadow overlaps the slice

**Comment by pawelfus** [comment]
Hi @ff-sgupta 

Thanks for reporting, however this is not a bug. Custom code is responsible for slices translation and this custom code should take care of animating halo too. 

Fixed demo: http://jsfiddle.net/5H675/99/

**Comment by ff-sgupta** [comment]
Thank you. Appreciate your fix to the demo. Helps a lot!
