### ISSUE TITLE
Flawed rendering in Chrome when embedding highcharts in svg with viewBox set

### ISSUE THREAD

**Issue by ctusch** [highcharts/highcharts#6815]
I'm trying to embed highcharts within an SVG using the foreignObject element. This works in Chrome as long as I'm not setting the viewBox attribute of the svg element.

#### Expected behaviour
Normal rendering like in Firefox.

#### Actual behaviour
Chrome seems to do two things as soon as I start using the viewBox attribute:
1. It moves the chart to the top left corner.
2. The rendering often looks incomplete and flickers on mouse-over.

This behavior doesn't occur if I embed some normal SVG within the foreignObject. So it has to be something highcharts is doing.

#### Live demo with steps to reproduce
http://jsfiddle.net/ry3mpjLq/

#### Affected browser(s)
This fiddle works in Firefox but doesn't work in Chrome (58.0.3029.110).

**Comment by pawelfus** [comment]
Hi @ctusch 

Thank you for reporting this issue! It is really strange one. 

Interesting fact: creating any element in Chart we get this error, however when using Renderer instance, it works fine, demos:

- chart: http://jsfiddle.net/4jacL1hs/
- renderer: http://jsfiddle.net/4jacL1hs/1/
