### ISSUE TITLE
Drilldown chart with scrollbar fails when the number of bars reaches 51

### ISSUE THREAD

**Issue by gianglv** [highcharts/highcharts#6816]
#### Expected behaviour
I tried to create a drilldown chart with scrollbar enabled, it works well if the number of bars less than or equal 50.
#### Actual behaviour
When the number of bars reaches 51, the chart fails to render correctly. If I scroll to the right, the bars will be missing.

#### Live demo with steps to reproduce
http://jsfiddle.net/gianglv/kvok0p8q/5/

#### Affected browser(s)
Chrome
Microsoft Edge
Opera

**Comment by sebastianbochan** [comment]
Thank you for reporting.

**Comment by pawelfus** [comment]
It's a duplicate of #5857

**Workaround:**
Set `cropThreshold`, demo: http://jsfiddle.net/kvok0p8q/6/
