### ISSUE TITLE
hide data labels if number doesn't fit in stacked bar is working for all export format except pdf in Client side export  

### ISSUE THREAD

**Issue by hellodpk** [highcharts/highcharts#6818]
#### Expected behaviour
It should work as it is working for other export format in client side export
#### Actual behaviour
when using client side export generated pdf is  showing data labels is bars  which is not expected

#### Live demo with steps to reproduce

This is post from stackoverflow [Highcharts exporting hide data labels if number doesn't fit in stacked bar
](https://stackoverflow.com/questions/44439030/highcharts-exporting-hide-data-labels-if-number-doesnt-fit-in-stacked-bar)

[fiddle](https://jsfiddle.net/deep3015/zem1u8ex/) when using Client side export generated pdf is not correct

**Comment by pawelfus** [comment]
Hi @hellodpk 

Thank you for reporting the issue. Instead of hiding labels, destroy them when exporting, demo: https://jsfiddle.net/kez30b00/

**Comment by hellodpk** [comment]
Thank a lot @pawelfus  this really helped me

**Comment by ellier7** [comment]
I noticed when you add yAxis styling, the datalabels are not destroyed. Please see demo: https://jsfiddle.net/er1187/6dm0rwn6/1/

**Comment by pawelfus** [comment]
It looks like yAxis styles cause chart to redraw, which recreates labels. In that case add `chart.events.redraw` event too. I am not sure if this is expected, but I would set those events only for exporting chart, demo: https://jsfiddle.net/ah79wk06/

**Comment by ellier7** [comment]
Great, thanks so much!
