### ISSUE TITLE
Why  my  Highcharts don't recognize the renderer?

### ISSUE THREAD

**Issue by alenan2016** [highcharts/highcharts#6821]
#### Expected behaviour
I would like to color Box Plot whiskers top and bottom in different colors (as I've found in the js fiddle below http://jsfiddle.net/coo8bcuq/), and also Box top and bottom in different colors.

#### Actual behaviour
My code don't recognize the renderer, although I've used the same version of Highcharts as in the http://jsfiddle.net/coo8bcuq/ is. My code is here: https://jsfiddle.net/hew8nq5u/

#### Live demo with steps to reproduce

http://jsfiddle.net/coo8bcuq/

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @alenan2016 

For support related questions please send us an email or post your issue on our forum.

To answer: for me it works fine: https://jsfiddle.net/hew8nq5u/4/ - I just added the code (`chart.events.load` method) from the first sample to your demo.

**Comment by alenan2016** [comment]
Thank you very much. I have one more question, please help as you can: how to color top of the box  and bottom of the box in different colors using renderer? Please update the  https://jsfiddle.net/hew8nq5u/4/ demo that you show before. Thank you in advance. Best regards, alenan2016

**Comment by pawelfus** [comment]
Hi @alenan2016 
Unfortunately this is not supported as #6796 says. It requires custom code to split a box into separate paths.

**Comment by alenan2016** [comment]
Thank you very much.
