### ISSUE TITLE
Support Navigator in Gantt

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#6822]
#### Expected behaviour
We would like to be able to navigate large datasets in Gantt with the navigator and/or scrollbars.

#### Actual behaviour
This currently breaks. Works with gridAxis alone, so should be doable.

#### Live demo with steps to reproduce
http://jsfiddle.net/1d3cs05s/

**Comment by oysteinmoseng** [comment]
Note #6552.

**Comment by jon-a-nygaard** [comment]
*Internal Note: Static scale affects this*
