### ISSUE TITLE
How to add labels to explain what each part of the Box Plot chart is

### ISSUE THREAD

**Issue by alenan2016** [highcharts/highcharts#6825]
#### Expected behaviour
I would like to have text labels to explain what each part of the Box Plot chart means. For example, on the right  of the  q3 (the top of the box), next to it, I want to have label "75th percentile", next to the median I need to have  the text "Median" etc. Please see the attached file.
[Box plot chart.pdf](https://github.com/highcharts/highcharts/files/1066767/Box.plot.chart.pdf)

#### Actual behaviour
I don't have the labels, I just have the legend below the chart, but it is not enough.

#### Live demo with steps to reproduce

https://jsfiddle.net/hew8nq5u/

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @alenan2016 

At this moment, dataLabels are not supported in boxplot series ([docs](http://api.highcharts.com/highcharts/plotOptions.boxplot)). You can create your idea on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api). 

You can try to use [Renderer](http://api.highcharts.com/highcharts/Renderer) to draw your own labels on a chart.

**Comment by alenan2016** [comment]
Thank you very much.
Best regards,
alenan2016
