### ISSUE TITLE
chart.redraw can't draw chart

### ISSUE THREAD

**Issue by f2egxz** [highcharts/highcharts#6826]
#### Expected behaviour
chart.series.setData(a, false); set data ,than 
chart.redraw() The updated data is drawn on the chart

#### Actual behaviour
The chart has not changed

#### Affected browser(s)
all

**Comment by f2egxz** [comment]
function draw(a,b) {
    chart.series[0].setData(a, false);
    chart.series[0].setData(b, false);
    chart.redraw();
 }

Use this function to draw the data of the chart. When the first call is made, the data can be plotted. After that, the data is called again. The diagram does not change. Why?

**Comment by pawelfus** [comment]
Hi @f2egxz 

Please, recreate issue in jsFiddle. It works in this simple demo: http://jsfiddle.net/zpfnub07/

**Comment by pawelfus** [comment]
Hi @f2egxz 

Please, recreate issue in jsFiddle. It works in this simple demo: http://jsfiddle.net/zpfnub07/1/

**Comment by f2egxz** [comment]
demo is success...

**Comment by pawelfus** [comment]
That would mean you don't change datasets. Try to use copies of the datasets.
