### ISSUE TITLE
Setting crisp to false has no effect in Internet Explorer

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#6828]
#### Expected behaviour
Setting crisp to false results in evenly spaced columns

#### Actual behaviour
Setting crisp to false has no effect

#### Live demo with steps to reproduce
http://jsfiddle.net/s5o23545/2/ renders with even space between columns in Chrome, but not in Internet Explorer 11 or Edge.

See https://s8.postimg.org/6pvw72wmd/No_Crisp_IE11.png

#### Affected browser(s)
Internet Explorer (11), Edge

**Comment by sebastianbochan** [comment]
Hi @kzoon 
Thank you for the reporting.

**Comment by TorsteinHonsi** [comment]
Strange. With the default shape-rendering it should give the same result. It seems that `shape-rendering: geometricPrecision` also doesn't work: http://jsfiddle.net/highcharts/s5o23545/3/

**Comment by KacperMadej** [comment]
Unfortunately, [the `shape-rendering` is not supported in IE or Edge.](https://msdn.microsoft.com/en-us/library/ff934768(v=vs.85).aspx)
