### ISSUE TITLE
[Highstocks] Very slow rendering on Firefox 9/10

### ISSUE THREAD

**Issue by zopyx** [highcharts/highcharts#683]
See 

http://monitoring.zopyx.com/@@hs

This chart has 3 series with 32k points each.

It is rendering pretty fast (3-4 seconds including loading of the data) on Chrome 16/17 (Linux + Mac) and Opera 11.6 (Linux + Mac).
It is taking up to 30 seconds to render with Firefox 9/10 (Mac + Linux) (also getting a popup about a slow running script).

Highstocks problem or Firefox problem?

At least the script timeout pop alerts indicate that control should be given back to the browser from time to time using setTimeout()

**Comment by KacperMadej** [comment]
If the problem is still present please create a demo in JSFiddle showing the issue.

**Comment by TorsteinHonsi** [comment]
In a two-and-a-half year old issue I think we can safely close it due to inactivity. Please reopened it if new information comes up.
