### ISSUE TITLE
Tooltip enabled state does not change when using Chart.update()

### ISSUE THREAD

**Issue by gkjohnson** [highcharts/highcharts#6832]
#### Expected behaviour
The behavior of the tooltip updates to accomodate the new chart options passed to `update()`

#### Actual behaviour
When updating the options of a chart with a tooltip to disable said tooltip using the following code:
```javascript
chart.update({ tooltip: { enabled: false } })
``` 
the tool tip does not hide

#### Live demo with steps to reproduce
Demo demonstrating the issue:
http://jsfiddle.net/9xq3fdj7/1/

The tooltip is enabled by default, but is set to disabled after two seconds using `update()`

#### Affected browser(s)
Chrome
Edge
Presumably all

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

This is ultimately the same issue as #6760 that is fixed in the master. See http://jsfiddle.net/highcharts/9xq3fdj7/2/. 

The fix will be part of the next maintenance release.
