### ISSUE TITLE
Boost displaying scatter plot with different styling

### ISSUE THREAD

**Issue by callumacrae** [highcharts/highcharts#6834]
#### Expected behaviour

This is the chart without boost:

![image](https://user-images.githubusercontent.com/472830/29818962-71584e5c-8cb6-11e7-8834-2e45b0c344ec.png)

#### Actual behaviour

This is it with boost:

![image](https://user-images.githubusercontent.com/472830/29818969-77c1fc8e-8cb6-11e7-8c24-79ffdd712f2c.png)

The fill colour is different, and the points have slightly square radiuses.

#### Live demo with steps to reproduce

http://jsfiddle.net/LLExL/7630/

Comment out the boost plugin to see what it should be like.

#### Affected browser(s)

All.

Also, where is the documentation for boost? I can only find a blog post from a couple years ago.

**Comment by sebastianbochan** [comment]
Thank you for reporting.

@cvasseng

**Comment by cvasseng** [comment]
This has been fixed in the `hc5-fixes` branch (https://github.highcharts.com/hc5-fixes/modules/boost.js).

One caveat: you need to specify the series color in the `series` object for now.

Example: http://jsfiddle.net/0tLr0bg7/1/

**Comment by callumacrae** [comment]
Sweet, that works great!

It seems to be working without me specifying the colour in the series, though. Has that changed since you sent that?

**Comment by cvasseng** [comment]
The rendering itself (i.e. no ugly edges on the points) work regardless, but I had to set the color on the series to make it look identical to the non-boost fiddle, as the boost module does not take the `plotOption` `fillColor` properties completely into account.

**Comment by TorsteinHonsi** [comment]
The `fillColor` is now also implemented for Boost.
