### ISSUE TITLE
Axis.SetExtremes on inverted columnrange chart causes some columns to dissapear

### ISSUE THREAD

**Issue by robahs** [highcharts/highcharts#6835]
#### Expected behaviour
All columns in the specified range should be shown.

#### Actual behaviour
Some columns in the specified range are not shown.

#### Live demo with steps to reproduce
http://jsfiddle.net/XKF6p/5/

#### Affected browser(s)
Chrome 59

Works in Firefox 54. Safari 10.1.1 and Microsoft Edge 40.15063.0.

**Comment by sebastianbochan** [comment]
Thank you for reporting.

_Internal note_
It looks like issue with rounding values, because min value 99.170521 works, but 99.170522 not. 
- problem appears inly in inverted
- pointRange does not solve the problem

**Comment by TorsteinHonsi** [comment]
Related to #1303. The cause is that Chrome (and others?) is unable to render the shape when it gets insanely big and outside the SVG viewbox.

**Comment by sebastianbochan** [comment]
Thank you for explanation.
