### ISSUE TITLE
Skip keyboard navigation for series that are not visibile 

### ISSUE THREAD

**Issue by primerano** [highcharts/highcharts#6838]
#### Expected behaviour

I thought this was a feature request but it might be a bug.

If I have 3 lines and one is hidden, i don't expect keyboard navigation to navigate the hidden series.

#### Actual behaviour

Keyboard navigation walks the visible and hidden series

#### Live demo with steps to reproduce

See https://forum.highcharts.com/post135758.html for background.

I made updates to H.Chart.prototype.highlightAdjacentPoint that mostly worked here
http://jsfiddle.net/primerano/44pum7oq/1/

But after looking at the code I think this line might be wrong.

`               if (
                    newPoint.isNull &&
                    this.options.accessibility.keyboardNavigation.skipNullPoints ||
                    newPoint.series.options.skipKeyboardNavigation // docs
                ) {
`

I think this code should actually skip if null and skip null is set OR skipKeyboardNavigation is set as below.

`               if (
                    (newPoint.isNull &&
                    this.options.accessibility.keyboardNavigation.skipNullPoints) ||
                    newPoint.series.options.skipKeyboardNavigation // docs
                ) {
`

I guess the question is.  Should HighCharts skip hidden series or should HighCharts skip series where skipKeyboardNavigation is true?   

Neither works at the moment but I would like to know if this is a feature that is planned or that is broken.  

Thanks!!!
Tony

#### Affected browser(s)

All.  Not browser specific.

**Comment by oysteinmoseng** [comment]
@primerano Thanks for reporting! The two code lines you mention are functionally identical due to operator precedence in JS, so the [`skipKeyboardNavigation`](http://api.highcharts.com/highcharts/series%3Cline%3E.skipKeyboardNavigation) option should work with the current code. Do you have an example where it doesn't work?

We should obviously also skip hidden series, so I'll quickly add in a check for that.

**Comment by primerano** [comment]
I guess the operator precedence works.  my bad.

I do notice that the 1st point in the hidden series is available to the keyboard navigation when using skipKeyboardNavigation.

See http://jsfiddle.net/primerano/x0d7325h/1/

click "Hide Series". shift tab to the chart, space to enter chart and then start tabbing.  1st point selected is in the hidden series.

Also, at the end it tabs through the hidden "Series 1" legend item.

I see you already made a commit to allow skipping of hidden series.  How can I test that code out?

Thanks
Tony

**Comment by oysteinmoseng** [comment]
@primerano There were definitely some bugs in the existing code, so it's great that you reported. With current code it works as it should, I believe: http://jsfiddle.net/x0d7325h/2/. You can load the latest accessibility module from `github.highcharts.com/hc5-fixes/modules/accessibility.js`.

Tabbing through hidden legend items is on purpose, as it allows keyboard-only users to hide/show series using the legend.

**Comment by primerano** [comment]
Is there a way to disable legend navigation?  In our case we have a line with all 50 states.  by default we show 1 and let folks hide or show the series via a select2 control as having 50 items in the legend is a bit much,

At the moment we stop the legend clicks via 

line: {
  events: {
    legendItemClick: function () {
    return false;
  }
}

but this doesn't affect keyboard navigation.

Maybe this is a better option?

    legend: {navigation: {enabled: false}}

This didn't seem to do anything for me.  maybe it is the wrong option?

I'll try out your fix for the series navigation next week and let you know if i find issues.

Thanks

**Comment by oysteinmoseng** [comment]
@primerano I added a new option `legend.keyboardNavigation.enabled` to allow this. Example: http://jsfiddle.net/oysteinmoseng/ugkgt4dj/

**Comment by primerano** [comment]
Thanks for the quick feedback and feature add.   I'm not sure if the changes are in the hc5-fixes anymore because your example is navigating the series now

http://jsfiddle.net/x0d7325h/2/

And I made one that uses the new legend.keyboardNavigation setting and it doesn't work either

http://jsfiddle.net/x0d7325h/7/

How often do you release patch releases?   Woudl 5.0.13 be out this month?

**Comment by oysteinmoseng** [comment]
@primerano The changes are still there, but there seems to be an issue with the `github.highcharts.com` service returning the wrong file somehow.

Regardless, the changes are also now in master so you can use `github.highcharts.com/modules/accessibility.js` which seems to work.

We do release patch versions roughly every month or so, and do expect `5.0.13` to be out in a few weeks max.

**Comment by primerano** [comment]
I just realized that you can still keyboard navigate to the hidden series with the up/down arrows.   Can we get a fix for that with this issue too?

**Comment by primerano** [comment]
Should we open a separate issue against the up.down arrow keys navigating into hidden series?

**Comment by sebastianbochan** [comment]
Hi @primerano 
It looks like keyboardNavigation parameter only enables / disables navigation, but does not "consider" hidden series. 

Thank you for the reporting and you do not create new case at this moment.

**Comment by primerano** [comment]
@sebastianbochan - will a fix for the arrow navigation be done under this issue #6838 or is there another issue i should follow?

**Comment by pawelfus** [comment]
Let's reopen this issue.

@oysteinmoseng

**Comment by primerano** [comment]
@pawelfus is there a chance we can get the up-down arrow into the hidden series fixed in the next release?

http://jsfiddle.net/primerano/x0d7325h/8/

**Comment by pawelfus** [comment]
I'm not sure, @oysteinmoseng what do you think?

**Comment by oysteinmoseng** [comment]
@primerano Should be doable, I'll add it as a milestone

**Comment by primerano** [comment]
@oysteinmoseng   was tab navigation of a line removed?  Before I could tab through the series.  now only up/down arrow are available to skip ahead and back in the series.

**Comment by oysteinmoseng** [comment]
@primerano Yes, tab navigation is now used to navigate between the major chart sections (points, exporting menu, legend, etc). To move between points/series, use arrow keys (up/down/left/right). Our testing so far indicates that this is fairly intuitive to users, and has the added benefit of making chart navigation through charts with lots of points much easier. A major issue with the previous navigation model was that users were unable to tab past charts with lots of points without going through all the points of the chart.
