### ISSUE TITLE
Line chart clips line thickness when the series aligns with the xAxis min value

### ISSUE THREAD

**Issue by pixelizedPeanut** [highcharts/highcharts#6839]
#### Expected behaviour
line thickness should be the same everywhere

#### Actual behaviour
line thickness is half

#### Live demo with steps to reproduce
http://jsfiddle.net/fkubgt5w/4/
See the 2 lines thicknesses fluctuating

#### Affected browser(s)
Chrome, Safari

**Comment by sebastianbochan** [comment]
Thank you for the reporting. 

Duplicate of: https://github.com/highcharts/highcharts/issues/6225 and https://github.com/highcharts/highcharts/issues/6604
