### ISSUE TITLE
Boost does not play nice with Polar Plots

### ISSUE THREAD

**Issue by gkjohnson** [highcharts/highcharts#6840]
#### Expected behaviour
When rendering a plot with polar coordinates, fall back to the basic renderer if boost cannot render polar charts

#### Actual behaviour
Charts are rendered on far left side of the pane when polar charts are enabled while using boost

#### Live demo with steps to reproduce

Here's a JS fiddle that starts with a basic polar chart then enables boost after 2 seconds
http://jsfiddle.net/xz4j89q1/3/

#### Affected browser(s)
all

**Comment by sebastianbochan** [comment]
Hi @gkjohnson 
Thank you for reporting.

@cvasseng

**Comment by deepak-iu** [comment]
Anything on this yet?
