### ISSUE TITLE
Cannot disable Pie dataLabels text-ellipsis functionality

### ISSUE THREAD

**Issue by Drumstix42** [highcharts/highcharts#6841]
If you create a pie chart within a small area, and specifically would like to have **dataLabels** overflow the chart margin/area, it does not seem currently possible. They are clipped and text-ellipsis is applied.

### Expected behaviour
Have a method/property to disable text ellipsis/clipping of text for **dataLabels**, even if it overflows the chart margin/area.

### Actual behaviour
dataLabel.sideOverflow logic prevents this, based on the plotWidth

### Example
http://jsfiddle.net/drumstix42/45k96hjf/1/

#### Suggested change
I'm sure the devs may have a better method, but my personal suggestion is to read from the **dataLabels.crop** option before applying the **sideOverflow** logic within _seriesTypes.pie.prototype.placeDataLabels_

Updated the variable section:
```
                    var dataLabel = point.dataLabel,
                        series = point.series,
                        options = series.options.dataLabels,
                        dataLabelCrop = pick(options.crop, true),
                        _pos;
```

Updated the check for sideOverflow functionality:
```
                            // Shorten data labels with ellipsis if they still overflow
                            // after the pie has reached minSize (#223).
                            if (dataLabelCrop && dataLabel.sideOverflow) {
```

Maybe there is a better way, like reading the style for textOverflow, but since these are dataLabels and not axis labels, I wasn't sure.

**Comment by sebastianbochan** [comment]
Hi @Drumstix42
Thank you for the reporting and suggestion.

You can set the useHTML param as a true and declare width of label.

Demo:
- http://jsfiddle.net/vLn5pa8v/

**Comment by Drumstix42** [comment]
@sebastianbochan

While this does remedy the text ellipsis part, it introduces other issues like the text getting clipped off the edge of the chart. Some may want text to be contained within the chart, but in this instance I was looking for a way to display the text whether it would overflow or not -- I still wanted it visible.

Perhaps my desired result is too specific a request, but I wanted to submit the issue/suggestion either way.

**Comment by sebastianbochan** [comment]
Thank you for the feedback. It is also related with the bug: https://github.com/highcharts/highcharts/issues/1581
