### ISSUE TITLE
Implement Bell curve and histogram series types

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#6843]
Bell curves and histogram share the same underlying algorithm. As far as I can see a bell curve is an area chart with smaller bins than the histogram.

https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/2879758-dynamic-histogram-charts

https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/2431670-probability-density-normal-distribution-bell

**Comment by morganfree** [comment]
I have split those two series into three files - if it is necessary they will be merged into one file (they are merged in masters in one module - histogram-bellcurve).

#### derivedSeriesMixin
 - it is currently in js/modules/ - probably should be moved to some 'parts' folder
 - methods which allow to access base series data
 - it fires a new event 'seriesLinked' after the series are linked

#### histogram
 - implements histogram series
 - inherits from column, mixes in derivedSeriesMixin

#### bellcurve
 - implements bellcurve series
 - inherits from areaspline, mixes in derivedSeriesMixin
 - it calculates mean and standard deviation from the base series data and plots the curve according to the normal distribution's density function

**Comment by TorsteinHonsi** [comment]
> it is currently in js/modules/ - probably should be moved to some 'parts' folder

You can create a separate `js/mixins/` folder for that. We also have a couple of other mixins that we should move there later.

Can the Pareto series type also utilize this _derivedSeriesMixin_? You can talk to @sebastianbochan about that.

**Comment by TorsteinHonsi** [comment]
@morganfree I did the same just now for FlagSeries / Windbarbs. Take a look at https://github.com/highcharts/highcharts/commit/63fa861ccef51c9dd7b1a4dfef1eeec01fa50b5c.
