### ISSUE TITLE
Implement Bullet graphs

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#6844]
https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/788709-add-bullet-graphs-to-the-selection-list

Already possible as a combination, but we need a simplified API

**Comment by KacperMadej** [comment]
## Bullet series type prototype v1 ##

**Possible options:**
The same as for column type series +
* _trackerWidth_ - pixels or percentage of column width
* _trackerColor_ - color
* _trackerHeight_ - pixels

**For styled mode:**
Added class `highcharts-bullet-target` for target markers.

**Demo / Testing:**
Classic mode: http://jsfiddle.net/rpao1305/1/
Themed for the "bullet" look: http://jsfiddle.net/uf7rvzok/

Styled mode: http://jsfiddle.net/rpao1305/2/

**Comment by TorsteinHonsi** [comment]
Nice work! Some comments:

- Can we use some other name than `tracker...` for the target? Since we're already using the word tracker for mouse tracking in Highcharts. Also, is there a specific reason for not calling it simply `targetWidth`, `targetColor` etc?
- Width and height settings for the target is a bit confusing when we're in an inverted chart, which I suppose will be quite common with bullet charts. I don't really have a good suggestion here - _size_ could be used for either, so it's not good... and we already use `pointWidth` even in an inverted chart. _Size_ and _length_ maybe? Suggestions?

**Comment by KacperMadej** [comment]
@TorsteinHonsi Thank you very much for the suggestions.

1. I think `tracker` was a typo - `target` will be used. Fixed ✅

2. The `target` in a bullet chart is like a line, so it has length and thickness. `length` sounds good and could be used with `width` (based on [this](http://thinkmath.edc.org/resource/measurement-length-width-height-depth) or [this](http://www.wikihow.com/Measure-the-Length-x-Width-x-Height-of-Shipping-Boxes)) - like _stroke-**width**_.

```
  Not inv.   Inverted
  ---------     ---
B |       |     | |
  ---------   A | |
      A         | |
                ---
                 B
```
Options:
 A and B (template)
a) width and height (current)
b) length and size
c) length and width

I'll wait for other options and/or decision before applying this change. ⏸

3. From Sebastian: enable `target` options from point level. Added ✅

4. Adding border options for the target - width and color. ✅
Should all target options be nested in series / point like marker options? or left like they are now?

## v2 demo ###
Classic mode: http://jsfiddle.net/nss4eath/1/
Styled mode: http://jsfiddle.net/6q7h43fj/

**Comment by TorsteinHonsi** [comment]
For the width/length stuff, my vote goes to c), length and width. It is also consistent with [whiskerLength](http://api.highcharts.com/highcharts/plotOptions.boxplot.whiskerLength) and whiskerWidth on box plots and error bars, which are visually related.

> Should all target options be nested in series / point like marker options? or left like they are now?

Do you mean like defining target in an options group? I'm not sure. I mean it's okay for now that we have five options starting with `target`, but it may be harder if we add more. Another consideration is that it would be easier to merge target options from the series with the point if you organize it in a group:

```js
target: {
   length: '100%',
   width: 2,
   borderColor: 'black',
   color: 'red',
   borderWidth: 2
}
```
