### ISSUE TITLE
Implement Hyperbolic Tree maps

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#6845]
https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/781629-hyperbolic-tree-maps-and-tree-maps

Probably the underlying data structure is the same as for tree maps, so the difference lies in the rendering.

**Comment by TorsteinHonsi** [comment]
Putting this on ice until after v6, awaiting a physics engine that also would come in handy for label positioning, packed bubble charts and force directed graphs.

**Comment by htveit** [comment]
We have decided to not implement Hyperbolic treemaps for now because a) demand is very low or non existent, b) Xerox has patented the algorithms in the US, and c) we have good alternatives like network graphs and regular treemaps
