### ISSUE TITLE
Implement Linear Gauge

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#6847]
See for the Uservoice FR here https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/4244550-linear-gauge

**Comment by KacperMadej** [comment]
@TorsteinHonsi Would it be better for this series to have [`bullet`](https://github.com/highcharts/highcharts/issues/6844) or `column` as a parent?

**Comment by TorsteinHonsi** [comment]
As far as I can see it is pretty close to your bullet series implementation, with the marker and all... So yes, bullet is probably the way to go. Frankly I don't see much difference between the two...

**Comment by sebastianbochan** [comment]
It seems that there is a small bug when you print a chart.

Demo:
- http://jsfiddle.net/BlackLabel/rayvsbke/

Click exporting and then Print chart. The line with arrow is duplicated.

**Comment by PaulDalek** [comment]
This demo references to the old version of the lineragauge, prepared for demonstration purposes. Here you can find the the newest version of lineragauge series (work in progress): http://jsfiddle.net/79ef16f8/.
