### ISSUE TITLE
Implement Parallel coordinates series type

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#6849]
Related to Sankey charts, but have separate Y axes instead of nodes. Some implementations exist on UserVoice, but perhaps we need to make special Y axis prototypes inspired by the nodes in Sankey.

related to issue #6850

**Comment by pawelfus** [comment]
## Demos:

- http://jsfiddle.net/wecf1z35/
- http://jsfiddle.net/tb3zd9hw/

## New options:

#### `chart.parallelCoordinates`
true/false - enables/disables parallel coordinates in a chart
#### `chart.parallelAxes`
object - The same options as in [Axis](http://api.highcharts.com/highcharts/yAxis) - it's a shorthand when we want to specify the same option for all of yAxes, for example `lineWidth` can be set here and all yAxes will get the same line width.

## Known issues:

- `addPoint()` does not add new Axis. new Axis should be added before `addPoint()` manually
- `point.remove()` does not remove any Axis. Axis should be removed manually
- when dealing with huge amount of data, it's recommended to disable initial animation
- can be partially supported by boost (without spline and forced `useGPUTranslations:false`)

**Comment by TorsteinHonsi** [comment]
It looks like the demo needs a `tooltip.pointFormatter` that distinguishes between the different parallel axes: http://jsfiddle.net/wecf1z35/1/. For example, training times and running paces are datetimes, but are displayed as integers.
