### ISSUE TITLE
Flags that are small don't have their label centered

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#685]
In this example: http://jsfiddle.net/6TLvx/ the flag 'P' is not positioned inside of the circle.

Expected: The label to be centered. Or a way to tweak the position with a padding/margin option

**Comment by sebastianbochan** [comment]
The flag is out of range and is generally missing.

**Comment by KacperMadej** [comment]
Updated demo to show the issue: http://jsfiddle.net/6TLvx/6/
