### ISSUE TITLE
Implement Pareto chart series type

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#6851]
It looks like a very simple preprocessing leading to a column and a line.

**Comment by sebastianbochan** [comment]
## Demo:

- http://jsfiddle.net/oubgag2z/

## Documentation:

```
{
	type: 'pareto',
	linkedTo: 'pareto', // required parameter
	yAxis: 1
}
```

## Known issues:

- `addPoint()` animation is not perfect, due to using setData inside the core. If setData will have right animation, problem will be solved.

**Comment by sebastianbochan** [comment]
@TorsteinHonsi 
I modeled my docs on Sankey, but I have two problems with docs:
- series is not linked to <series> object, only plotOptions
- new functions (getValues) are documented, but not visible in namesames

Do you have any ideas?

**Comment by TorsteinHonsi** [comment]
> series is not linked to object, only plotOptions

Actually there's a piece missing in the sankey.src.js file. You can see it in the streamgraph.src.js file, there's a section of doclets at the bottom.

> new functions (getValues) are documented, but not visible in namesames

Only the files listed in the gulpfile, `generateClassReference`, are parsed for the class ref. I've deliberately left out the series types for now, as it hasn't been quality assured.

**Comment by sebastianbochan** [comment]
Thank you, but when we would like to skip "data" object in series<type>, then whole series is missing.

**Comment by sebastianbochan** [comment]
The problem was with data parameter, I needed to add definition and then "exclude" it.

**Comment by TorsteinHonsi** [comment]
Note that we have a hack for `seriesType`, so you can put the doclet before the function call. But `H.seriesType` won't work.

**Comment by sebastianbochan** [comment]
Ok, meanwhile I was linting, but its fixed. Thanks!
