### ISSUE TITLE
Implement Stream Graph series type

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#6852]
A [study](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/highcharts/studies/streamgraph/) is created.

It may be as simple as to add another type of stacking, so the series type would just set { stacking: 'stream' } by default.

https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/4437096-streamgraph

**Comment by TorsteinHonsi** [comment]
Status: Production ready. Documentation done.
