### ISSUE TITLE
Implement Sunburst series type

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#6853]
Sunburst is a hierarchical chart type, its data definition should be the same as a tree map. Perhaps it can even be implemented as a  special case of tree map with its own layout algorithm.

https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/2274844-sunburst

**Comment by jon-a-nygaard** [comment]
# Documentation

Status: Pre-Alpha
Last update: 2017-08-18
Subscribe to the issue to receive notification about technical updates.
## Demo
Coming soon
## Options
Todo
## Advanced usage
Todo
## Nice to have
Todo
## Known issues
Todo

**Comment by yashjit** [comment]
How to implement it in angular 4. Please provide step by step approach. Help is required.

**Comment by pawelfus** [comment]
Hi @yashjit - please contact with our [support](https://www.highcharts.com/support).
