### ISSUE TITLE
Arabic Text Distorted on Area Chart's xAxis

### ISSUE THREAD

**Issue by MAlakel** [highcharts/highcharts#6855]
#### Actual behaviour
Arabic text on xAxis categories is distorted when it has numeric values and text is relatively long.

#### Live demo with steps to reproduce
https://jsfiddle.net/uzxd25ye/

#### Affected browser(s)
Internet Explorer, Version 11.0.9600.18698

**Comment by TorsteinHonsi** [comment]
It's a problem with SVGs buggy text rendering.

#### Workaround
Use HTML: https://jsfiddle.net/uzxd25ye/2/

**Comment by MAlakel** [comment]
Worked like a charm.

Thank you @TorsteinHonsi
