### ISSUE TITLE
Drilldown no longer working correctly with multiple series

### ISSUE THREAD

**Issue by mwgarwood** [highcharts/highcharts#6858]
#### Expected behaviour
Clicking on histogram bar should send drilldown event

#### Actual behaviour
Drilldown event only occurs at the top level chart when a second (cumulative) series is added to the chart.  Drilldown still occurs if using the links on the x-axis, but ceases to work when clicking on the chart itself.  Even the top level stops working properly after navigating back to it from a lower level.

#### Live demo with steps to reproduce

http://jsfiddle.net/mwgarwood/dv6pppox/
Click on chart to drilldown from Monthly to Daily level. Drilldown from the Daily chart will not jump to next layer even though the chart itself is "clickable".  Drilldown *does* work using the x-axis link labels.   Remove the call to chart.addSeries() to see proper behaviour.

This worked in previous versions of Highcharts (e.g. 4.2.2).

#### Affected browser(s)
Only tested on Chrome

**Comment by TorsteinHonsi** [comment]
Fails since v5.0.11.

Couldn't find the exact commit since github.highcharts.com is down at the moment.
