### ISSUE TITLE
Add axis label index access inside axis formatter

### ISSUE THREAD

**Issue by kennyjwilli** [highcharts/highcharts#6859]
In order to properly format my axis labels I need to access to the index of the data point. It looks like the only fields available from inside the axis formatter function are `axis`, `chart`, `dateTimeLabelFormat`, `isFirst`, `isLast`, and `value`. Would you guys be open to adding a new field called `index` or `pos`? At first glance, it looks like it would be as simple as adding the `pos` field to the `labelFormatter` call [here](https://github.com/highcharts/highcharts/blob/b2d16e5086b37dd883f147330ec5a84db59baeb5/js/parts/Tick.js#L69). I am happy to submit a PR if it would be merged.

**Comment by TorsteinHonsi** [comment]
Good point! Commit coming up.
