### ISSUE TITLE
yAxis.crosshair bug

### ISSUE THREAD

**Issue by helloroy** [highcharts/highcharts#6860]
The `yAxis `label and cross-hair position is wrong when add `crosshair` to `yAxis`

Wrong  cross-hair position:
![2017-06-17_220937](https://user-images.githubusercontent.com/2213000/27253611-92870ebe-53aa-11e7-878c-1c5c847d2266.jpg)

Wrong label value:
![2017-06-17_221249](https://user-images.githubusercontent.com/2213000/27253612-928733f8-53aa-11e7-91e5-a5f7e7209498.jpg)

Here is problem jsfiddle demo base on offical candlestick-and-volume demo
http://jsfiddle.net/yu7p8bzm

**Comment by sebastianbochan** [comment]
Hi @helloroy,
Thank you for the reporting.

_Internal note_
@jon-a-nygaard it looks like the issue in runPointActions method. In 5.0.10 worked well.
