### ISSUE TITLE
Navigator custom series doesn't work if first of chart series is a pie chart

### ISSUE THREAD

**Issue by Russellmd** [highcharts/highcharts#6861]
#### Expected behaviour
If navigator.series option is used then this shouldn't be affected by other chart's series settings 

#### Actual behaviour
If navigator.series option is used and first of chart's series is a pie chart then navigator doesn't work 

#### Live demo with steps to reproduce
https://jsfiddle.net/russellmd/7jbs40f3/ - try to move first of chart's series (pie chart) to another position to see that after move the navigator works as expected

**Comment by sebastianbochan** [comment]
Hi @Russellmd,
Thank you for the reporting. 

The solution is setting [showInNavigator](http://api.highcharts.com/highstock/plotOptions.series.showInNavigator) parameter as a true. 

Demo:
- https://jsfiddle.net/ekex4m40/

**Comment by Russellmd** [comment]
Hi @sebastianbochan ,
I know about this solution, but now in navigator are loaded 3 series (for each of chart series) with the same options:
https://jsfiddle.net/russellmd/r2ds094p/ - try to click on a column to see the results

**Comment by sebastianbochan** [comment]
Hi @Russellmd,
I apologize for my bad, the parameter should be applied for particular series, not global.

Example:
- https://jsfiddle.net/qgrpd78h/

As a result one series is visible in navigator, but obviously it is only workaround, because navigator series should be applied properly.

**Comment by Russellmd** [comment]
Hello @sebastianbochan,

Yes, your solution works, also mine (to move pie chart and exclude it to be first on series list), but these are just "tricks". My opinion is that if custom series are used in navigator then the chart series shouldn't appear in navigator until this is explicitly indicated
