### ISSUE TITLE
Excluding unused functionality 

### ISSUE THREAD

**Issue by torabian** [highcharts/highcharts#6862]
I was wondering if there is any way to include some portion of the code into project. In case we only need some type of charts or functionality, is there anyway to only include that functions, like what lodash did to it's repository?

**Comment by sebastianbochan** [comment]
Hi @torabian,
You can build your own package by a tool on the webpage.

Ref:
 -https://www.highcharts.com/download

For general [support](http://www.highcharts.com/support) questions, please use email / stackoverflow or forum.
