### ISSUE TITLE
Marker symbol changes on drilldown/backbutton events

### ISSUE THREAD

**Issue by schneckentempo** [highcharts/highcharts#6863]
#### Expected behaviour
I would expect that the markers stay the same as before

#### Actual behaviour
On drilling down i.e. a linechart the marker symbol changes. It again changes when pressing the back button. Actually it is cycling through all possible symbols ("circle", "square", "diamond", "triangle" and "triangle-down") and begins from a new when a cycle is completed

#### Live demo with steps to reproduce
http://jsfiddle.net/r06wLLhx/
This is the pie chart demo with just type set to `line`. Drill down, press back

**Comment by sebastianbochan** [comment]
Thank you for the reporting. The reason of it is that each time when you drill, new series is created (inluding new symbol marker).

Workaround:
Set [marker.symbol](http://api.highcharts.com/highcharts/plotOptions.series.marker.symbol) as circle in the series object.

Demo:
 - http://jsfiddle.net/17pa5av6/
