### ISSUE TITLE
X-axis labels are overalapping when the label  length is more. 

### ISSUE THREAD

**Issue by nishanth-satmetrix** [highcharts/highcharts#6866]
Hi,

 X-axis labels are overalapping when the label  length is more. 
Is there any way to break the grouped category label when it has lengthy one to adjust the chart.
for Ex: "Nishanth satmetrix " is my x-axis label
I need this like

Nishanth
satmetrix

without formatter if possible.

2.ellipsis is possible for the chart if it has more length?

Below JsFiddle have the issue I mentioned .

   https://jsfiddle.net/TFhd7/1406/
Thanks In advance
Nishanth
Satmetrix

**Comment by KacperMadej** [comment]
Hi,

For technical support please use forum, StackOverflow, e-mail. More info: https://www.highcharts.com/support

We are using this github for tracking bugs. Please report bug in a plugin on the plugin's github site: https://github.com/blacklabel/grouped_categories/issues

**Comment by nishanth-satmetrix** [comment]
Thanks KacperMadej for the reply,  I submitte it in grouped categories issues site. but they are not come back with the solution
