### ISSUE TITLE
Highcharts.Net wrapper improperly generates JSON for solid gauge stops

### ISSUE THREAD

**Issue by schutze** [highcharts/highcharts#6868]
#### Expected behaviour

Using Highcharts.NET wrapper (Highcharts.Web.Mvc.dll) Version 5.0.6360.17139 and this VB.NET code:
Dim cb As Highcharts = New Highcharts()
...
Dim stopList As List(Of [Stop]) = New List(Of [Stop])
stopList.Add(New [Stop] With {.Position = 0.33, .Color = "rgb(223, 83, 83, .5)"})
stopList.Add(New [Stop] With {.Position = 0.66, .Color = "rgb(221, 223, 13, .5)"})
stopList.Add(New [Stop] With {.Position = 1, .Color = "rgb(85, 191, 59, .5)"})
cb.YAxisList(0).Stops = stopList

temp = Highsoft.Highcharts(cb, "chart").ToHtmlString()     'For version 5.0.6323 or older
'Dim temp As String = Highsoft.GetHighchart(cb, "chart").ToHtmlString()  'For version 5.0.6324 or newer

BTW, the Highsoft.GetHighchart method DOES NOT EXIST in the 5.0.6360 wrapper even though the comment says that it should.

The JSON below should be generated:
stops: [ [0.1, 'rgb(223, 83, 83, .5)'],
       [0.5, 'rgb(221, 223, 13, .5)'],
       [0.9, 'rgb(85, 191, 59, .5)']],

As demonstrated here:
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/gauge-solid/

#### Actual behaviour

Instead, the JSON below is generated and the color stops are not applied:
"stops" [
  {  "position": 0.33,  "color": "rgb(223, 83, 83, .5)"
  }, { "position": 0.66, "color": "rgb(221, 223, 13, .5)"
  }, { "position": 1, "color": "rgb(85, 191, 59, .5)"
}],

#### Live demo with steps to reproduce

Refer to this jsfiddle:
https://jsfiddle.net/5bv1abz0/

The uncommented JSON does not work but the commented settings do work properly.

#### Affected browser(s)
Browser does not matter

**Comment by sebastianbochan** [comment]
Hi @schutze,
Thank you for the reporting, I have passed your to our .NET developer and I will get back to you when I will receive an answer.

**Comment by sebastianbochan** [comment]
The yAxis.Stops returns a list of objects instead of list of lists. We will fix this as soon as possible.

**Comment by schutze** [comment]
How are new wrapper releases announced? There should be a [change log](https://www.highcharts.com/documentation/changelog) for the .NET wrapper just like the other products.

Considering there is a [solid gauge example](http://dotnet.highcharts.com/Highcharts/Demo/Gallery?demo=GaugeSolid&theme=default) that demonstrates color stops, I'm surprised this issue was not caught before the .NET wrapper was released in December 2016.
