### ISSUE TITLE
Highcharts.Net wrapper generates improper JSON series option name for gauge and solid gauge

### ISSUE THREAD

**Issue by schutze** [highcharts/highcharts#6871]
#### Expected behaviour

Using Highcharts.NET wrapper (Highcharts.Web.Mvc.dll) Version 5.0.6360.17139 and this VB.NET code:

Dim guageSeriesData As New GaugeSeriesData With {.Y = 80, .Name = "Speed"}
Dim guageDataList As New List(Of GaugeSeriesData)
guageDataList.Add(guageSeriesData)

Dim gaugeSeries As New GaugeSeries
gaugeSeries.Data = guageDataList

Dim cb As Highcharts = New Highcharts()
...
cb.GaugeSeries = gaugeSeries

temp = Highsoft.Highcharts(cb, "chart").ToHtmlString() 'For version 5.0.6323 or older
'Dim temp As String = Highsoft.GetHighchart(cb, "chart").ToHtmlString() 'For version 5.0.6324 or newer

BTW, the Highsoft.GetHighchart method DOES NOT EXIST in the 5.0.6360 wrapper even though the comment says that it should.

Should generate the following JSON:
series: [{name: 'Speed',data: [80]}]

The same JSON should be generated if SolidgaugeSeries is used rather than GaugeSeries.

#### Actual behaviour

Depending on which series was used, one of the two JSONs below are generated which do not work:
gaugeSeries: [{name: 'Speed',data: [80]}]
solidgaugeSeries: [{name: 'Speed',data: [80]}]

The name for the series option should be "series" rather than "gaugeSeries" or "solidgaugeSeries".

#### Affected browser(s)
Browser does not matter.

**Comment by sebastianbochan** [comment]
Thank you for the reporting.

**Comment by schutze** [comment]
@sebastianbochan Any updates on this issue? If confirmed, it seems serious enough that it should be fixed sooner than later.

**Comment by sebastianbochan** [comment]
Im just waiting for reply from our .NET developer. I will let you know about details as soon as possible.

**Comment by schutze** [comment]
This issue should have a "Bug" label.

Considering there are examples that demonstrate both [angular gauge](http://dotnet.highcharts.com/Highcharts/Demo/Gallery?demo=GaugeSpeedometer&theme=default) and [solid gauges](http://dotnet.highcharts.com/Highcharts/Demo/Gallery?demo=GaugeSolid&theme=default), I'm surprised this issue was not caught before the .NET wrapper was released in December 2016.

**Comment by sebastianbochan** [comment]
The issue is already fixed for Highcharts in the newest 5.0.6397.2889 version. GaugeSeries, SolidgaugeSeries and other series are removed from Highcharts object. Please use a Series property such as in our demos here: http://dotnet.highcharts.com/Highcharts/Demo/Gallery?demo=GaugeSolid&theme=default

**Comment by schutze** [comment]
@sebastianbochan This has been corrected!
