### ISSUE TITLE
Can't dynamically position wrapped y-axis title to not overlap y-axis labels

### ISSUE THREAD

**Issue by SteelBurgher** [highcharts/highcharts#6873]
#### Expected behaviour

I have the need to wrap long y axis titles by styling the width property of the y axis title, as demonstrated in this fiddle: http://jsfiddle.net/wse1rhgc/4/

However, as you can see in the fiddle, this results in significant overlap of the title on top the y axis labels and even into the chart. 

I know that I can adjust the x property of the title to prevent overlap, as demonstrated in this fiddle: http://jsfiddle.net/wse1rhgc/3/

But I haven't been able to adjust in the load event the extent of this x offset, based on the  dynamic lengths of the y axis title and how many lines break as a result of wrapping the title. Ideally, would like to be able to offset the wrapped title to always fit it between edge of chart and the y axis label container, no matter if the y axis title is wrapped 3 lines deep, 2 lines deep, or not at all. 

#### Actual behaviour

As in this fiddle: http://jsfiddle.net/wse1rhgc/3/, I can adjust the x position of the y-axis title, but cannot do it dynamically according to how much the title gets wrapped

**Comment by KacperMadej** [comment]
Thank you for reporting about the problem.

*Internal note:*
Simplified issue and demo: http://jsfiddle.net/9pyx8385/1/
Muli line axis title is wrongly positioned and overlapping axis labels.

**Comment by sebastianbochan** [comment]
**Workaround**
Extract the width of the title (by getBBox method) and move element by translate.

Example:
- http://jsfiddle.net/ht88cupt/

**Comment by SteelBurgher** [comment]
Thanks @sebastianbochan, that's exactly what I need to dynamically position the wrapped title. I still think it's a good idea to mark this as a bug, or at least a feature improvement, to make the axis title translate by default when an explicit width causes the title to wrap.

**Comment by TorsteinHonsi** [comment]
OP demo with the fix applied: http://jsfiddle.net/highcharts/wse1rhgc/5/

The fix also removes the need to set the width in an event callback, from now on it will automatically wrap to the width of the axis length unless a specific width is set.
