### ISSUE TITLE
Implement Variable-Width chart

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#6874]
A Variable-Width chart where the width of the column would designate a third dimension, z. Possibly this would also affect the X axis, so that the columns can be packed tight.

See for example and Uservoice's FR here:
https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/2303560-multi-dimensional-column-charts

**Comment by TorsteinHonsi** [comment]
Need to figure out if the variwide chart is the same as marimekko. Currently we have two studies:

* _variwide_, which is simply a column series that is extended with a _z_ component that sets the width of the columns. This can be stacked, grouped, percent stacked etc just like a column series. Can be set up using a table of three columns.

* _marimekko_, which is a special case of a treemap. The data structure here is different. It is a hierarchy with two levels. The column widths reflect the sum of the values inside each group of points. Unlike variwide, this always stacks up to 100%.
