### ISSUE TITLE
stackLabels need an allowOverlap: false option

### ISSUE THREAD

**Issue by swrobel** [highcharts/highcharts#6876]
#### Expected behaviour
`allowOverlap: false` for stackLabels hides some labels so that none overlap, the same way the option works for dataLabels.

#### Actual behaviour
For dense charts, stackLabels overlap and become unreadable.

#### Live demo with steps to reproduce
On most screens sizes, the stackLabels will overlap on this chart, as shown below. I have set the `allowOverlap: false` option for stackLabels but it has no effect. Enabling it for dataLabels works as expected. I would expect these two types of labels to behave in the same way.
http://jsfiddle.net/uukL5u5n/
<img width="534" alt="screen shot 2017-06-19 at 2 17 49 pm" src="https://user-images.githubusercontent.com/157270/27306345-1bffe2b0-54fa-11e7-98fa-b15b896c34ee.png">

**Comment by sebastianbochan** [comment]
Thank you for reporting.

At this moment Highcharts doens't support an anty-collision algorithm. You can use a workaround for labels, like in the demo below:
  - http://jsfiddle.net/menXU/6/
  - http://jsfiddle.net/menXU/1/

**Comment by swrobel** [comment]
@sebastianbochan dataLabels support the `allowOverlap: false` option which at least hides some labels so none are overlapping. This request is simply to allow the same option & resulting behavior for stackLabels (but thank you for the suggestions).

**Comment by TorsteinHonsi** [comment]
Reliable demo (with specific width): http://jsfiddle.net/highcharts/uukL5u5n/1/
