### ISSUE TITLE
Implement Wordcloud series type

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#6877]
Read for examples and Uservoice's FR here: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/4180727-add-a-word-cloud-graph

@jon-a-nygaard has made some research here.

**Comment by jon-a-nygaard** [comment]
# Documentation
Status: Pre-Alpha
Last update: 2017-08-04
Subscribe to the issue to receive notification about technical updates.
## Demo
- [Wordcloud of Lorem Ipsum (95 words)](https://jsfiddle.net/jon_a_nygaard/x2nmxc99/2/)
## Options
### series\<wordcloud>.type: String
### series\<wordcloud>.placementStrategy: String
Which placement algorithm to use. The placement strategy decides rotation and initial position of a word. **Defaults to: "random"**.
### series\<wordcloud>.rotation.orientation: Number
The number of possible rotations between `rotation.from` and `rotation.to`. **Defaults to: 2**.
### series\<wordcloud>.rotation.from: Number
The smallest degree of rotation for a word. **Defaults to: 0**.
### series\<wordcloud>.rotation.to Number
The maximum degree of rotation for a word. **Defaults to: 90**.
### series\<wordcloud>.spiral: String
Which spiralling algorithm to use. The spiralling algorithm decides where to try and fit in a word if it collided with another word in its initial position. **Defaults to: "archimedean"**.
## Advanced usage
### Custom spiralling algorithm
 Spirals used for moving a word after the inital position experienced a collision with either another word or the borders of the playing field.
To implement a custom spiral, look at the function archimedeanSpiral for example:
```javascript
/**
 * archimedeanSpiral - Gives a set of cordinates for an Archimedian Spiral.
 *
 * @param {number} t How far along the spiral we have traversed.
 * @return {object} Resulting coordinates, x and y.
 */
var archimedeanSpiral = function archimedeanSpiral(t) {
	t *= 0.1;
	return {
		x: t * Math.cos(t),
		y: t * Math.sin(t)
	};
};
```
The spiralling algorithm is made accesible by attaching it to the `spirals` property:
```javascript
Highcharts.seriesTypes.wordcloud.prototype.spirals.archimedean = archimedeanSpiral;
```
Afterwards you can use the algorithm by specifying the option **series<wordcloud>.spiral**:
```javascript
Highcharts.chart(..., {
  series: [{
    type: 'wordcloud',
    spiral: 'archimedean'
  }]
});
```
### Custom placement strategies
Strategies used for deciding rotation and initial position of a word.
To implement a custom strategy, have a look at the function randomPlacement for example:
```javascript
var randomPlacement = function randomPlacement(point, options) {
  var field = options.field,
    r = options.rotation;
  return {
    x: getRandomPosition(field.width) - (field.width / 2),
    y: getRandomPosition(field.height) - (field.height / 2),
   rotation: getRotation(r.orientations, r.from, r.to)
  };
};
```
The placement algorithm is made accesible by attaching it to the `placementStrategy` property:
```javascript
Highcharts.seriesTypes.wordcloud.prototype.placementStrategy.random= randomPlacement;
```
Afterwards you can use the algorithm by specifying the option **series<wordcloud>.placementStrategy**:
```javascript
Highcharts.chart(..., {
  series: [{
    type: 'wordcloud',
    placementStrategy: 'random'
  }]
});
```
### Custom font sizing
The size of the font is calculated by the function `deriveFont`, which gives a result based on the relative weight of a word. The weight is on a scale 0-1, which indicates the words weight compared to the word with the largest weight.
When customizing the font sizes, you should be aware that higher font sizes can make the placement algorithm run slower, while a lower font size can make the placement of words more scattered.
```javascript
// Include this snippet after loading Highcharts and before Highcharts.chart is executed.
Highcharts.seriesTypes.wordcloud.prototype.deriveFontSize = function (relativeWeight) {
   var maxFontSize = 25;
  // Will return a fontSize between 0px and 25px.
  return Math.floor(maxFontSize * relativeWeight);
};
``` 
## Known issues
- When words are rotated in angles not divisible by 90, there is a lot of air between them.
  - The current collision algorithm does not take rotation into count, and only checks if the outer areas of two words collides. To fix this we can utilize the [Seperating Axis Theorem](https://gamedevelopment.tutsplus.com/tutorials/collision-detection-using-the-separating-axis-theorem--gamedev-169)
- The words has changed places when I export my chart.
  - The exporting does a new render of the data, which causes the words to be repositioned in different then coordinates then the original chart.
- There is a different font type in my exported chart.
  - The current default font used in our Wordcloud series is not installed on the export server.
- There is currently no animation available.
