### ISSUE TITLE
Image labels (useHtml) is broken in export

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#688]
Using this example: http://jsfiddle.net/SLgSF/
1. Axis labels use useHtml to display images instead of text but they require a character before the image otherwise the image is positioned wrong.
2. During export, the image is gone and only the invisible character is there.

Tried another way using the renderer directly: http://jsfiddle.net/SLgSF/1 but then its not possible to have links on the images

**Comment by digitalvapor** [comment]
Why isn't this supported? Would be so so so useful!
