### ISSUE TITLE
Highstock. Zoom in bar charts with data grouping

### ISSUE THREAD

**Issue by PatriRor** [highcharts/highcharts#6880]
- Highcharts 5.0.12
- zoomType: 'x'
- Init date of data: Jun 22, 2010

#### Expected behaviour
- Serie data with first month incomplete - select first month bar and only show days with data
- Data grouping by month/year - select month/year and show days of complete month/year 

#### Actual behaviour
- Serie data with first month incomplete - select first month bar and only show days without data
- Data grouping by month/year - select a month/year and show days of previous month/year and selected month/year
- Zoom applied (zoomType: 'x'): End labels without data (and data exist) https://github.com/highcharts/highcharts/issues/4785

#### Live demo with steps to reproduce

http://jsfiddle.net/nbmgtbzn/16/
- Select 2010 bar 
<img width="791" alt="zoom-2010" src="https://user-images.githubusercontent.com/5472707/27333113-11e78c30-55c5-11e7-998a-14a8f1f4b622.png">

After zoom (show days without data, does not display data for all year)
![captura de pantalla 2017-06-20 a las 14 15 31](https://user-images.githubusercontent.com/5472707/27333160-3d361f3c-55c5-11e7-8e1a-935c13adbce7.png)

- Select 2011 bar 
After zoom (show data of 2010 and 2011)
![captura de pantalla 2017-06-20 a las 14 29 12](https://user-images.githubusercontent.com/5472707/27333119-171f562e-55c5-11e7-9baa-d1bc9e4703a3.png)

#### Affected browser(s)
Safari 10.1.1
Chrome 58.0.3029.110 (64-bit)

#### Related Issues
https://github.com/highcharts/highcharts/issues/2461 Highcharts setExtremes for datetime axis is not right
https://github.com/highcharts/highcharts/issues/4785 Crop threshold affects zoomed data

**Comment by sebastianbochan** [comment]
Hi @PatriRor 
Thank you for the reporting.

It looks like a bug, related also with the case: https://github.com/highcharts/highcharts/issues/2437

**Comment by pawelfus** [comment]
This is general problem with representation of a year - point is placed exactly on 01.01.xxx 00:00:00.000. When we zoom in, we zoom into range where points don't exist (we have direct relation between selection area and values on a chart).

**Workaround:**
We can change how points are rendered: http://jsfiddle.net/BlackLabel/nbmgtbzn/20/ - this way we represent data as column from year A to year B and zooming makes sense now - you still can zoom in Jan-Feb 2010 which will be blank.

**Comment by KacperMadej** [comment]
The issue doesn't look like a bug - nothing is broken here and everything seems to be working as explained in documentation.

If you have more info and would like to see this issue reopened please leave a comment.
