### ISSUE TITLE
3d Column Display Bug? 

### ISSUE THREAD

**Issue by nealdav** [highcharts/highcharts#6882]
I’m experiencing an issue with a Stacked 3d Column Chart: 

#### Expected behaviour

Columns display in expected locations regardless of 'y' data values.

#### Actual behaviour

When I set the ‘y’ value of the last column to anything less than 4, the last column segment displays as a colored line on the (left) opposite side of the chart. 

#### Live demo with steps to reproduce
I’ve recreated this issue here ('y' value set below '4' on line 54): 
https://jsfiddle.net/ndavis/u3y230eq/

This is an example of the issue corrected when the data value is set above 4:
https://jsfiddle.net/ndavis/fxwL9qxr/

note: this also appears to affect 'bar' charts

#### Affected browser(s)

Chrome, FF, Safari

**Comment by Izothep** [comment]
Hi @nealdav!

Thank you for reporting your issue. 

I think that your problem is related to another GitHub issue: https://github.com/highcharts/highcharts/issues/6708

This problem should be already solved on our Github Master branch. Could you please test your example with GitHub version of highcharts-3d module?
https://jsfiddle.net/u3y230eq/28/

**Comment by nealdav** [comment]
Hello Grzegorz,

Yes, the GitHub version appears to fix the issue, which is great!

One quick note that you are probably aware of — when using: https://github.highcharts.com/highcharts.js <https://github.highcharts.com/highcharts.js> along with https://github.highcharts.com/highcharts-3d.js I see graphics anomalies when mousing over the columns like in the screenshot below. 

Using the currently supported version of highcharts fixes this:  https://jsfiddle.net/ndavis/9hmjpmvt/1/

**Comment by Izothep** [comment]
Hi @nealdav,

Thank you for information about the second issue with hovered points in 3d charts. 

It is a pre-release bug that is already reported on our GitHub. You can find more information about this issue in the link below: 
https://github.com/highcharts/highcharts/issues/6776

If you have any further questions related to our code please feel free to ask.

**Comment by KacperMadej** [comment]
#6776 has a suggested solution and will be resolved or continued on the issue site. There's nothing else that is not addressed by linking to another issues, so I am closing this case. Please reopen if needed.
