### ISSUE TITLE
Tooltip does not refresh without moving the mouse when drilling down (IE only)

### ISSUE THREAD

**Issue by checktheriddler** [highcharts/highcharts#6887]
#### Expected behaviour
When clicking on one of your areas on your treemap (tooltip for that area is active) the tooltip should update.

#### Actual behaviour
When you click on an area on the treemap and you do not move the mouse, the tooltip from the previous level is still showing up. (only IE, chrome and firefox works)

#### Live demo with steps to reproduce
You can test it with the treemap demo on the website:
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/treemap-large-dataset/

Just open it in the internet explorer, click e.g. on "Africa", but don't move the mouse cursor, you will see that the tooltip for "Africa" is still showing and i hope this can be fixed!

#### Affected browser(s)
only IE
firefox works fine, in chrome sometimes it shows a tooltip from another area (not that with the mouse above it)

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

I was able to recreate the issue on:
**Win10: Edge, IE11, Chrome
iOS: Chrome, Safari**

As a workaround you could clear tooltip after drilldown like in this demo:
- http://jsfiddle.net/v8uffme4/

***Internal note:*** This is a problem with heatmap drilldown and not the drilldown module. A similar problem appears when clicking the drill up button while a point is being hovered and tooltip is being displayed - tooltip stays for the lower data level and a hover halo for the point is visible in the previous position of the point.
![treemap_hover](https://user-images.githubusercontent.com/8960408/27388001-7a49738a-569a-11e7-94d3-06f90ed596bf.jpg)
