### ISSUE TITLE
Heatmap legend labels disappear when set via responsive rules

### ISSUE THREAD

**Issue by frntz** [highcharts/highcharts#6888]
#### Expected behavior
Heatmap labels are showed next to legend on a responsive heatmap

#### Actual behaviour
Heatmap legend labels disappear when setting symbolHeight in responsive rules

#### Live demo with steps to reproduce
http://jsfiddle.net/frntz/z5xnzs96/

#### Affected browser(s)
Chrome, Firefox, IE

**Comment by TorsteinHonsi** [comment]
Any call to `legend.update` will make all the ticks disappear: http://jsfiddle.net/highcharts/z5xnzs96/1/
