### ISSUE TITLE
stackDistance for flags is only applied per series

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#689]
Example: http://jsfiddle.net/By8t7/

The example contains two series where one of the x points is shared by both series. The flags for this point are rendered on top of each other even though stackDistance has a value greater than 0.

Expected: That the flags are stacked in the same way as if they were both in the same series.

**Comment by iweindesmedt** [comment]
+1
updated jsfiddle: http://jsfiddle.net/rkj7ou5h/1/
