### ISSUE TITLE
Markers are not shown on Line Chart peaks in FF

### ISSUE THREAD

**Issue by uladzimir-tsyperman** [highcharts/highcharts#6891]
#### Expected behaviour

Markers should be displayed

#### Actual behaviour

Markers are not shown on peaks of the Line Chart

![image](https://user-images.githubusercontent.com/23166100/27432534-e3da2838-5750-11e7-9c2c-147d4704f715.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/2hxqopo0/

#### Affected browser(s)
Only appears in Firefox on Windows (tested with version 54.0). Screen resolution 1920x1080.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

**Internal note:** Seems to be affecting only FF on Win. Chrome and FF on iOS, and IE, Edge, Chrome on Win10 are working fine.

**Comment by TorsteinHonsi** [comment]
Walks and talks like a roundoff issue.

#### Workaround
Set the maximum slightly higher, and set `endOnTick` to false: https://jsfiddle.net/2hxqopo0/1/

**Comment by KacperMadej** [comment]
Unable to recreate using version 6.1.4
Closing as resolved
