### ISSUE TITLE
Multiple panes not compatible with gridLineInterpolation='polygon'

### ISSUE THREAD

**Issue by remilandais** [highcharts/highcharts#6892]
#### Actual behaviour
When displaying two series on a polar chart, with two different y axes, each one being associated with a different pane, we cannot use gridLineInterpolation='polygon'
We get 'Cannot read property 'tickPositions' of undefined'

#### Live demo with steps to reproduce
http://jsfiddle.net/remilandais/d2azhhse/

**Comment by sebastianbochan** [comment]
Hi @remilandais,
Thank you for the reporting. Indeed it is a bug.

Demo:
- http://jsfiddle.net/0f70rszg/

**Comment by Izothep** [comment]
As a workaround it is possible to use multiple xAxis that are connected with all of the panes used in your chart: http://jsfiddle.net/0f70rszg/6/

It should also be possible to create small wrapper and set initial xAxis as chart.xAxis[0]: http://jsfiddle.net/0f70rszg/7/
