### ISSUE TITLE
Highstocks timestamp -> Date not working

### ISSUE THREAD

**Issue by mrv777** [highcharts/highcharts#6893]
#### Expected behaviour
Highstocks convert timestamps to date

#### Actual behaviour
Timestamps are staying and not be recognized as dates

#### Live demo with steps to reproduce
I'm using the exact data from here:
https://www.highcharts.com/stock/demo/candlestick
and here is a screenshot of what I get:
![screen shot 2017-06-22 at 8 40 47 am](https://user-images.githubusercontent.com/3099725/27439065-8f167a78-572c-11e7-8a2a-0e26673ce3d4.png)

I'm using this with angular 4, so I posted the issue in the wrapper github too: https://github.com/gevgeny/angular2-highcharts/issues/205
but wanted to post it here too in case it's related to this one as I'm not sure how to know which one is having the issue.

Thank you advance for any help

**Comment by KacperMadej** [comment]
Hi,
Please recreate the issue in a live demo, e.g. JSFiddle. Looks like you are setting ticks or axis labels in a way that datetime format info is lost or ignored.

**Comment by mrv777** [comment]
Switched to `ng2-highcharts` and is working fine now.  Sorry for the bother
