### ISSUE TITLE
softMax cannot take effect in some small value data

### ISSUE THREAD

**Issue by wangtao0101** [highcharts/highcharts#6894]
#### Expected behaviour
yAxis max is 100

#### Actual behaviour
yAxis max is 0 

#### Live demo with steps to reproduce
http://jsfiddle.net/8hfojL3z/1/

#### Affected browser(s)
chrome

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

With no positive values on axis softMax is behaving as if it were set to 0 instead of it's value (e.g. 100).

Minimal demo: http://jsfiddle.net/p3yhck9o/

**Comment by KacperMadej** [comment]
**Workaround:** set [`softThreshold`](http://api.highcharts.com/highcharts/series%3Cline%3E.softThreshold) to false for series.

**Demo:** http://jsfiddle.net/p3yhck9o/1/

**Comment by wangtao0101** [comment]
Thanks, softThreshold take effect.

**Comment by allanmc** [comment]
Also happens with all zeroes as data:
http://jsfiddle.net/allanmc/dwqmb96r/

**Comment by KacperMadej** [comment]
Thank you for pointing this our @allanmc 

Workaround could be the same: http://jsfiddle.net/BlackLabel/y604svut/
