### ISSUE TITLE
setExtremes method issue for heatmap plot with boost module

### ISSUE THREAD

**Issue by AndreiKoriagin** [highcharts/highcharts#6895]
There's problem with boost module when using setExtremes method.
#### Expected behaviour
rectangles with lower cathegory value are hidden.

#### Actual behaviour
rectangles with lower cathegory value are visible outside of plot area.

#### Live demo with steps to reproduce
http://jsfiddle.net/xs0z64ny/

#### Affected browser(s)
Chrome (Windows)

I reached expected behavior by changing line 2028 in boost.src.js (method `createAndAttachRenderer`):<br/>
```javascript
target.boostClipRect.attr({
    x: chart.plotLeft,
    y: chart.plotTop,
    width: chart.plotWidth,
    height: chart.plotHeight //height: chart.chartHeight <- instead of this
});
```

**Comment by sebastianbochan** [comment]
Thank you for the reporting.

It looks like the same issue as the: https://github.com/highcharts/highcharts/issues/6865

**Comment by yoderexploder** [comment]
I'm having this problem as well.  Is there a current work around?

**Comment by TorsteinHonsi** [comment]
@cvasseng As far as I can see there's a potential room for optimizing in the [createAndAttachRenderer](https://github.com/highcharts/highcharts/blob/5d27939/js/modules/boost.src.js#L2318-L2456) function. This function runs 1200 times in the `line-series-heavy-stock` sample, one for each series. On each iteration, it runs function like `boostClipRect.attr`, `boostResizeTarget` and `boostClear`. When it renders to a chart-level canvas, this is repeated 600 times with the same parameters, which seems redundant.

**Comment by cvasseng** [comment]
@TorsteinHonsi yes, there's some room for improvement there. It needs to be called for every series if not boosting on chart level, but the cliprect should only be set when the chart has reflowed, and when it's first initialized.
