### ISSUE TITLE
An error occur when `navigator.adaptToUpdatedData` is set to false on `addSeries` method

### ISSUE THREAD

**Issue by grrseguin** [highcharts/highcharts#6899]
#### Expected behaviour
I would like to update the series of a chart with the `navigator.adaptToUpdatedData` option set to `false`.

#### Actual behaviour
An error occurs : `Cannot read property 'hoverSeries' of undefined`

#### Live demo with steps to reproduce
http://jsfiddle.net/chgmzr4a/

#### Affected browser(s)
Google Chrome Version 59.0.3071.109 (Build officiel) (64 bits)

**Comment by sebastianbochan** [comment]
Hi @grrseguin 
Thank you for the reporting.

_Internal note_
It seems to be almost fixed: http://jsfiddle.net/n6u1bqs4/, but we have still errors in `text()` method.

**Comment by oysteinmoseng** [comment]
Seems to be fixed in `hc5-fixes`: http://jsfiddle.net/chgmzr4a/16/
