### ISSUE TITLE
Display problem with iphone on new version of ios 10.3.2

### ISSUE THREAD

**Issue by alexfroger** [highcharts/highcharts#6902]
I have found a problem with the new version of ios 10.3.2 on iphone. 
The problem appears only when i used custom font loader (google font, ...).
Indeed, the title and subtitle do not appear across the entire width of the line, while they have the space to display.
When i do not use specific web font it works well.

https://forum.highcharts.com/highcharts-usage/display-problem-with-iphone-on-new-version-of-ios-10-3-2-t39293/

#### Expected behaviour
Title and subtile should be displayed across the available width

#### Actual behaviour
On iphone with ios 10.3.2 title and subtitle who have specific font wrap and do not display across the width

#### Live demo with steps to reproduce
https://jsfiddle.net/alex_froger/kpqmwnaL/show/

Just launch the url on your iphone device with ios 10.3.2. And you will see that subtitle does not display as expected. 

#### Affected devices
I tested and the problem appears on iphone 5, 6, 7 on ios 10.3.2.
The phones was on ios 10.2 and all worked well. So I do not know from which version the problem actually appears 10.2.1, 10.3, 10.3.1 or 10.3.2.

**Comment by sebastianbochan** [comment]
Hi @alexfroger 
Thank you for the reporting.
It seems that useHTML flag solves the issue:
- https://jsfiddle.net/uyjqy66t/

Could you confirm too?

**Comment by alexfroger** [comment]
Indeed, it works well for this specific case. 
Weird?

**Comment by sebastianbochan** [comment]
It seems that master branch (release candidate) fix the issue: http://jsfiddle.net/btm4jmuL/ (iPhone 6s, iOs 10.3.2)

**Comment by alexfroger** [comment]
Thanks, it seems work on Iphone 5, ios 10.3.2.
So, where did the problem come from ? Or you noticed that in the master branch it was resolved?
Do you know a date when this master branch become a new stable version ? Because i need a stable version and especially minified.

Thanks you very much!

**Comment by sebastianbochan** [comment]
The new release should be in next few weeks, but we do not have ETA for it.

**Comment by alexfroger** [comment]
OK, thks for the information.

**Comment by alexfroger** [comment]
Hello,

I was found a display problem on ios with external font loaded inside the Higcharts.
highcharts-usage/display-problem-with-iphone-on-new-version-of-ios-10-3-2-t39293/

I reopen a new topic. Because the problem has not been resolved as mentioned in the news versions of Highcharts recently added (5.0.13 and 5.0.14). And i can't use the master branch (release candidate) like has been mentionned in the issue
6902, because it don't work anymore with it too.

I tested it on : iphone 5 + ios 10.3.2 and iphone 6 + ios 10.3.3

Wrong case with Highcharts 5.0.14 + External font loaded (here google font Gloria Hallelujah)
https://jsfiddle.net/alex_froger/qy932zmd/show
Good case with Highcharts 5.0.14 + no external font loaded
https://jsfiddle.net/alex_froger/vwm958kw/show

Wrong case with Highcharts latest branch master (07/31/2017) + External font loaded (here google font Gloria Hallelujah)
https://jsfiddle.net/alex_froger/1r2nvfnp/show
Good case with Highcharts latest branch master (07/31/2017) + no external font loaded
https://jsfiddle.net/alex_froger/0ppt2hga/show

It the same with Highcharts version 5.0.13 and the last branch master at the date 07-31-2017

It's possible to reopen the issue https://github.com/highcharts/highcharts/issues/6902 and find a real solution to this problem. Because, I know a lot of people who look at their graphs on iphone and this is annoying if the rendering is not good. 
In any case, I have hundreds of bad returns on my side on this problem

Thank you in advance for your work to correct this problem.

Best regards,
Alexandre FROGER

**Comment by KacperMadej** [comment]
@alexfroger The demo with master branch might have been cached on your browser or on server - please try with this demo: https://jsfiddle.net/qy932zmd/1/ It looks fine on iPhone 6S + iOS 10.3.3.

**Comment by alexfroger** [comment]
Thks for the quick reply. But it doesn't work for me.
Here is a screenshot on iphone 5 + iOS 10.3.2 : [url=https://www.noelshack.com/2017-31-1-1501509235-20561904-10156449453004951-1699591411-n.jpg][img]https://image.noelshack.com/minis/2017/31/1/1501509235-20561904-10156449453004951-1699591411-n.png[/img][/url]

**Comment by alexfroger** [comment]
Hello,

Do you have any information on how and when the problem will be fixed?

Thanks a lot,
Alexandre

**Comment by KacperMadej** [comment]
Hi @alexfroger 

Unfortunately we do not have ETA for the fix yet.

If you have any suggestion for the fix please let us know.

**Comment by alexfroger** [comment]
Thks for the reply. 
Unfortunately, i don't have time to find a solution.
Let me know, when your team fixed the problem, that i think is really important to solve for you.

Best Regards,
Alexandre

**Comment by TorsteinHonsi** [comment]
Simplified demo: https://jsfiddle.net/highcharts/kpqmwnaL/5/

**Comment by TorsteinHonsi** [comment]
@alexfroger I tried delaying the chart renderer until the Google Font is loaded, but that didn't help.

You say that this works with the master as it was on June 27, but I am not able to see that. Before I start looking for a hacky workaround, do you know an exact commit where it used to work correctly?

**Comment by alexfroger** [comment]
Hi, 
Unfortunatly, i don't know a exact commit where it used to work correctly.
Indeed, it worked in the main branch but this one points to the last version to date (08/04/2017).
As you can see in the above message from sebastianbochan :

> It seems that master branch (release candidate) fix the issue: http://jsfiddle.net/btm4jmuL/ (iPhone 6s, iOS 10.3.2)

It worked on June 27, 2017. Unless you can retrieve the master branch of that date exactly. I do not know any other way to test a code that worked.

**Comment by alexfroger** [comment]
My test with your link : https://jsfiddle.net/highcharts/kpqmwnaL/5/

**Wrong display with font :** 
https://jsfiddle.net/alex_froger/bqxjLks1/
https://image.noelshack.com/fichiers/2017/31/5/1501838390-20641582-10156462216769951-338874265-o.jpg

**Good display without font :** 
https://jsfiddle.net/alex_froger/bqxjLks1/3/
https://image.noelshack.com/fichiers/2017/31/5/1501838390-20629041-10156462216729951-2127089218-o.jpg

**Comment by TorsteinHonsi** [comment]
I reduced the sample further to only use the `label` function: http://jsfiddle.net/highcharts/kpqmwnaL/6/

There's also a difference with refreshing and just going to the page (in http://jsfiddle.net/draft, just highlight the URL bar and Enter). When refreshing, the line-wrapping is always wrong. When entering the page without refresh, it is often correct. This suggests the issue is with async loading of the fonts, so the boxes are computed before the font is properly loaded.

Also, this is probably what happened on June 27th.

**Comment by TorsteinHonsi** [comment]
#### Workaround
It looks like there's a very simple workaround you can use - as long as there is some text previously rendered in the page that has uses the same font, it will make sure the text is loaded before we start reading the bounding boxes. Check out this:

* With simple text: http://jsfiddle.net/highcharts/kpqmwnaL/8/
* With the chart: https://jsfiddle.net/highcharts/bqxjLks1/4/

**Comment by alexfroger** [comment]
Hi,

Really great answer. I confirm all that you have said. 
Thks for the workaround, i will see, if i can use it for the moment, waiting for a real bug fix.
If you have an idea when a real solution will be found, please keep me informed of the delay before it comes out.

Thanks you very much for your work.
Alexandre

**Comment by alexfroger** [comment]
Hi,

I'll be back with some tests informations on your workaround. (https://jsfiddle.net/highcharts/bqxjLks1/4/)
I mean, with this solution, on my website, the chart rendering doesn't look good when the page is first loaded on the Iphone. But, if you change the portrait or landscape display after, then the rendering is good. But every time I reload the page the rendering is bad.

Unfortunately, this solution seems to be working only on jsfiddle.

Would you have another solution or real fixed yet, so that I can finally get a good rendering on Iphone of my charts with specific fonts.

Thank you in advance.

Best Regards,
Alexandre

**Comment by sebastianbochan** [comment]
Hi Alexandre,
    Could you point me out, how can I replicate the issue? Is it possible to give us an access to your website? In the fiddle portrait and landscape works well on my iPhone too.

**Comment by alexfroger** [comment]
Hi, 

Here is a url I can provide you : http://teatis.com/test/test_like_jsfiddle.html
This is a copy-paste of the test above returned by jsffidle (https://jsfiddle.net/highcharts/bqxjLks1/4/).

With my url, there is a bad display after loading the page, whether i'm in portrait or landscape.
However, if I change the display of my Iphone then it works fine.

Unfortunatly i can give you access to my server website.

Thanks a lot.
Alexandre

**Comment by sebastianbochan** [comment]
Hi Alexandre,
    Thank you for valuable demo, indeed the problem appears also in my iPhone (6S).

I found a workaround with loading chart and then call update with new font. Im aware that is not perfect, but seems to working properly on my iPhone.

Ref:
- https://jsfiddle.net/BlackLabel/genq5r4f/

**Comment by alexfroger** [comment]
Hi,

Thanks you very much for the workaround. Unfortuynaltly, i don't know if i can use it. Indeed, I handle a lot of graphs in the same page and I must have the best performances. And this correction may hinder that.

I'm surprised that this is not an important bug to solve on your side, because this is visible to any Iphone user and I'm sure that a large majority of your users use an Iphone to look at your graphs. And I can't be the only one who wants to use different fonts in my graphs.

**I hope that a real bug fix will be proposed soon.** 
In the meantime, I'm going to have to settle for your solution, if you don't have better.

Best Regards,
Alexandre

**Comment by sebastianbochan** [comment]
_Internal note_
I tested WebFont library and problem seems still appear. Its strange because "active" is callback. 

```
            WebFont.load({
                google: { 
                    families: ['PT Sans']
                },
                active: function() {
                    Highcharts.chart('container', {
                        chart: {
                            style: {
                                    fontFamily: "'PT Sans', sans-serif"
                            }
                        },
                        title: {
                            align: 'left',
                            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
                        },
                        series: [{
                            data: [1, 3, 2, 4]
                        }]
                    })
                }
            }); 
```

Ref:
- https://github.com/typekit/webfontloader

**Comment by alexfroger** [comment]
Hello,

New ideas on a temporary solution to solve the problem while waiting for a real fix.

Thank you.
