### ISSUE TITLE
How to implement highcharts-3d for react application

### ISSUE THREAD

**Issue by parth19** [highcharts/highcharts#6903]
#### Expected behaviour
I am importing highcharts using below code in my react application.
var Highcharts = require('highcharts');

I am not able to get 3d charts using this import method. It renders 2D charts only.
I would like 3d highcharts to work same as it works while we import highcharts using script tag.

#### Actual behaviour
3d charts doesn't work by just importing the var Highcharts = require('highcharts');
Can you please help me get highcharts-3d imported using ES5 / ES6 syntax.

#### Affected browser(s)
All the browsers

**Comment by sebastianbochan** [comment]
Have you tried to use: `require('highcharts/modules/highcharts-3d');` ?

**Comment by pawelfus** [comment]
It's in our docs [here](https://github.com/highcharts/highcharts#usage-in-nodebrowserifywebpack) and [here](https://www.highcharts.com/docs/getting-started/install-from-npm).

**Comment by mosijava** [comment]
dear @sebastianbochan ,
there is not such module in `/modules` folder.
Is anything change in newer versions?

**Comment by mosijava** [comment]
Oh I found it.
the path has changed to `highcharts/highcharts-3d`.
