### ISSUE TITLE
Wrong position drill up button using align

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#6905]
#### Expected behaviour
Drill up button is rendered inside the plotBox  when using align: 'left' or vertical align: 'bottom'

#### Actual behaviour
Drill up button is rendered outside the plotBox when using align: 'left' or vertical align: 'bottom'

#### Live demo with steps to reproduce

drillUpButton: {
      relativeTo: 'plotBox',
      position: {
        align: 'left',
        verticalAlign: 'top'
        //verticalAlign: 'bottom'
      },
http://jsfiddle.net/kzoon/0t5jy4sx/

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Thank you for reporting about the problem.

**Comment by KacperMadej** [comment]
`verticalAlign` is placing the drill up button to match top line of the button with the `relativeTo` box. For `verticalAlign: 'top'` the button is inside of the alignment box and for `verticalAlign: 'bottom'` the button is under the alignment box. Default x and y values are not zeros, so this was not clearly visable in your demo. Please see here: http://jsfiddle.net/0t5jy4sx/2/

To fit the button inside you could set y to -buttonHeight like here (y: -34): http://jsfiddle.net/0t5jy4sx/3/

I am not convinced that this is a bug.

**Comment by kzoon** [comment]
I disagree for two reasons:

1. The default values for x and y are clearly chosen to automatically give the button a nice position inside the box when using the default alignment (top right). I don't see why this should only be done in the top right position.

2. Setting  correct values for x and y depending on the alignment is hard to do. Especially because the values depend on style in theme. For example: setting font size in your improved fiddle pushes the button again outside the plot box: http://jsfiddle.net/kzoon/0t5jy4sx/4/

It is really much more convenient if you calculate the correct default value of x and y
