### ISSUE TITLE
Flickering render of scatter chart on OSX Chrome

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#6909]
#### Actual behaviour
Some scatter charts seem to have a flickering issue on hover. This seems to be an issue even with much older versions of Highcharts (Reproduced on 4.2.5, although the issue manifests itself more in the initial animation, and less on hover).

#### Live demo with steps to reproduce
https://jsfiddle.net/hxenwugv/ - hover over points to see issue, the points not hovered disappear.

#### Affected browser(s)
Reproduced only on Chrome 58 for OSX. Seemed to work fine on other browser/OS combinations, including Chrome for Windows.

#### Workaround
Including Boost and setting `series.boostThreshold` to 1 works: https://jsfiddle.net/hxenwugv/1/

**Comment by TorsteinHonsi** [comment]
Now seen on my Mac/Chrome 59 combo...

**Comment by sebastianbochan** [comment]
The issue is not valid in the newest Chrome (v71) and Highcharts v7.0.1.
