### ISSUE TITLE
highstock distribution files overwrite existing directory

### ISSUE THREAD

**Issue by nikolas** [highcharts/highcharts#6911]
#### Expected behaviour
Highstock.zip unzips to a `highstock` directory

#### Actual behaviour
Many directories are created when unzipping: `api`, `code`, `examples`, `gfx`, etc.

#### Live demo with steps to reproduce
Download highstock from: https://www.highcharts.com/download

Run: `unzip Highstock-5.0.12.zip`

**Comment by sebastianbochan** [comment]
Thank you for the suggestion.

@jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
@nikolas Thanks for the suggestion, but as this will break the structure between new and previous releases, and you can achieve the same result by running `unzip Highstock-5.0.12.zip -d highstock`, we have decided to leave it as is.
