### ISSUE TITLE
Responsive Rule containing plotOptions, if condition met on load, kills data labels and opening animations

### ISSUE THREAD

**Issue by alifr** [highcharts/highcharts#6912]
#### Expected behaviour
If `responsive.rules.chartOptions.plotOptions` are set for a breakpoint, such as `minWidth: 500`, and a pie chart is loaded on a screen greater than 500px wide then the responsive rules should be applied

#### Actual behaviour
If the responsive rule is met on load and plotOptions are defined then the dataLabels do not show and loading animation does not occur.
1. Setting `plotOptions.pie.dataLabels.style.fontSize = '26px'` causes label to remain hidden after load (opacity is zero) and chart opening/loading animation is disabled
2. Having anything set for plotOptions, even just an an empty object, causes data labels to remain hidden after load (opacity is zero) and chart opening/loading animation is disabled
3. Setting plotOptions within a drilldown chart has the same initial result, but after interacting with the chart the dataLabel will appear. Drilldown charts may be responsive, but top level chart is not

#### Live demo with steps to reproduce
1. Empty object, minWidth: 500 and "result" frame is wider than 500 onLoad: http://jsfiddle.net/k0udd7yv/2/
2. plotOptions is set, minWidth: 500 and "result" frame is wider than 500 onLoad: http://jsfiddle.net/k0udd7yv/1/
3. drilldown showing how interaction renders dataLabels: http://jsfiddle.net/k0udd7yv/3/

#### Affected browser(s)
Tested in Firefox

#### Related
Possibly related to  #6265?

**Comment by KacperMadej** [comment]
Thank you for reporting about the problem.
