### ISSUE TITLE
Leftover text elements in map with data classes

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#6914]
#### Actual behaviour
Highmaps with color axis and data classes leaves some dots in the upper left corner of the container. Inspecting the DOM shows multiple `<text>` elements, possibly axis labels for the color axis.

#### Live demo with steps to reproduce
http://jsfiddle.net/fr934nx0/
Observe small dots in upper left corner of chart. 

#### Affected browser(s)
Tested on Chrome on OSX.

**Comment by oysteinmoseng** [comment]
Workaround - disable labels for colorAxis: http://jsfiddle.net/fr934nx0/1/

**Comment by sebastianbochan** [comment]
_Internal note_
It seems that y param set as 0 also does not solve the issue. Only what comes to my mind is use negative translation like (0,-9999)?
