### ISSUE TITLE
Highstock: touch panning disabled when navigator is disabled

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6915]
#### Expected behaviour
Panning as with the navigator.

#### Actual behaviour
Panning on touch (touch screen device) is not possible.

#### Live demo with steps to reproduce
http://jsfiddle.net/aj7gvunw/15/
Panning not possible on touch screen.

Possible with navigator and pinchType not set to 'none'.
http://jsfiddle.net/aj7gvunw/17/

#### Affected browser(s)
Tested on Chrome/Android 6.0

**Comment by sebastianbochan** [comment]
In the Chrome iOS (10.2.3) also does not work.

**Comment by jon-a-nygaard** [comment]
Is this really a bug? In the reproduction demo, the `pinchType` is set to `'none'`, which mean it is off.
When I set it to `'x'`, like in [this demo](http://jsfiddle.net/jon_a_nygaard/aj7gvunw/20/), then it works as I would expect.

Perhaps I am missing something?

**Comment by sebastianbochan** [comment]
When you set panning as 'x', and remove pinchType, then still you cannot pan.

Demo:
- http://jsfiddle.net/aj7gvunw/24/

iOS
