### ISSUE TITLE
Column chart display incommensurate values

### ISSUE THREAD

**Issue by 20cents** [highcharts/highcharts#6917]
#### Actual behaviour
Column chart display incommensurate values, line chart is ok, for the same data set.

#### Live demo with steps to reproduce
https://jsfiddle.net/20cents/qgezcb2c/
(The long waiting times is for data is normal)

#### Affected browser(s)
All

**Comment by IliassB** [comment]
The different display is caused by the default data grouping set for each type of series.
https://www.highcharts.com/docs/advanced-chart-features/data-grouping
> Line type series use an average approximation.
>Column type series compute the sum.

With the line series set to compute the sum, the results displayed are now the same.
https://jsfiddle.net/qgezcb2c/8/

**Comment by 20cents** [comment]
Merci !
