### ISSUE TITLE
Highcharts: Handling ng-click on tooltips

### ISSUE THREAD

**Issue by iAndy3** [highcharts/highcharts#6918]
#### Expected behaviour
When returning an angular element from pointFormatter function, it should display as it is.

#### Actual behaviour
I created a chart and a custom tooltip, whenever the user clicks on the tooltip, it should call the $scope function. It doesn't display the element I created, instead it shows [object Object].

#### Live demo with steps to reproduce

I created a fiddle for this [http://jsfiddle.net/4WHbv/683/](url)

**Comment by morganfree** [comment]
Hi @iAndy3,

Thank you for reporting the issue. However, this is not a Highcharts bug - a pointFormatter callback should return a string, not an object. For support related questions use [Highcharts forum](https://forum.highcharts.com/) or send an email to support@highcharts.com.

I have answered the question on stackoverflow - [link](https://stackoverflow.com/questions/44907719/highcharts-handling-ng-click-on-tooltips/44910773#44910773).
