### ISSUE TITLE
Hierarchical styling of labels in TreeGrid

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#6919]
It would be nice to have an options structure where the user can specify styling for the different levels of tasks.

One use case so far is a user asking to indent subtask labels to achieve a more traditional tree view.

**Comment by TorsteinHonsi** [comment]
I think we need more than indentation. In the hierarchy demo, it is hard to see what menu items belong to which level. Gantt tools typically have different _styling_ for levels, for example bold text for parent items and normal for child items. So what we need is

 * An options structure where the user can specify styling for the different levels of tasks. Possibly a `levels` structure similar to tree grids would be the best option here, then we can add support for more options than pure styling in the future, like `align`, `rotation`, `format` etc.
 * Class names with levels (like `highcharts-gridaxis-level-0`) to allow CSS access. We also need an additional class for parent items.
