### ISSUE TITLE
dashStyle doesn't work in boost mode

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#6922]
#### Expected behaviour
The same as in the SVG rendering.

#### Actual behaviour
`dashStyle` is not applied

#### Live demo with steps to reproduce
http://jsfiddle.net/ke8r8ywr/

**Comment by TorsteinHonsi** [comment]
@cvasseng Can it be done? Otherwise we'll leave it as a known limitation. I've added it to the limitations section in the comments.

**Comment by cvasseng** [comment]
I think we should leave this as a limitation, it's not possible to do without a lot of trickery unfortunately.

Also, duplicate of #5264.

**Comment by pawelfus** [comment]
Closing as duplicate of #5264.
