### ISSUE TITLE
series.zone fail to work with yAxis min and max properties set

### ISSUE THREAD

**Issue by ScottSpittle** [highcharts/highcharts#6923]
#### Expected behaviour
I expect values  below 0.01 to not render on the graph

#### Actual behaviour
plot points with the value 0 are rendered

#### Live demo with steps to reproduce
http://jsfiddle.net/mcr6edhg/1/

Comment out the yAxis config to see the difference.

I want the behaviour you get when the yAxis has no min and max properties set, but actually able to have them set.

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
The 0 value is still a number so is draw by default. If you would like to have "empty point", use null.

**Comment by sebastianbochan** [comment]
In the color you should use `color: 'rgba(255, 255, 255, 0)'` instead of `color: 'rgb(255, 255, 255, 0)'` which ignores alpha param.

**Comment by ScottSpittle** [comment]
The problem is, if the zone value is less than 0.5 it still draws the line.

0.5 Without a line being drawn for data values of 0: http://jsfiddle.net/gbdykawq/
0.01 With the line being drawn for data values of 0: http://jsfiddle.net/mcr6edhg/1/

**Comment by sebastianbochan** [comment]
Duplicate of https://github.com/highcharts/highcharts/issues/6923#issuecomment-313641738
