### ISSUE TITLE
Navigator not working as expected

### ISSUE THREAD

**Issue by olivierscheffler** [highcharts/highcharts#6924]
#### Expected behaviour
I should be able to scroll with the arrow on the navigator

#### Actual behaviour
The navigation stop working at a certain time

#### Live demo with steps to reproduce
template: http://jsfiddle.net/tfeky4ja/

#### Affected browser(s)
Chrome and expected firefox/safari and other

#### Step to reproduce
On the navigator, put the smaller zone as possible on the right.
Then tap on left arrow multiple time and normally it will stop working at a certain moment.

**Comment by sebastianbochan** [comment]
Thank you for the reporting.

**Workaround**
Setting minRange parameter on xAxis solves the problem. Could you confirm?
Demo:
- http://jsfiddle.net/c39qnts6/

**Comment by olivierscheffler** [comment]
Hi @sebastianbochan 
I try your fix but on my project and your workaround doesn't work.
The navigator still block when you put him on the small size as possible and put him on the extreme left.
Do you think it's a bug and so, is it hard to know how we can solve it ?

Thank you very much

**Comment by sebastianbochan** [comment]
Hi @olivierscheffler,
Unfortunately I was not able to replicate your issue in my jsfiddle. See a gif below.

![navigator](https://user-images.githubusercontent.com/2115686/27910303-d832eb28-6254-11e7-8608-59799e6aee7d.gif)

Could you supply me your browser details?

Chrome: 59.0.3071.115, MacOSX

**Comment by olivierscheffler** [comment]
Hi @sebastianbochan 

Ok thanks for the gif. Just one question how do you do that ?
Chromium Version 58.0.3029.0 (Build de développement) (64 bits) - I'mpretty sure it will not work on chrome too.
When you do in on the right, the left side of the navigator selector, push it to the extreme limit. You will see that it overlay to the right selector.
Can you see what I mean with the gif ?

Thank you
![overview](https://user-images.githubusercontent.com/9136245/27910871-ff19cb56-6224-11e7-94e7-639ad7e1bdce.gif)

**Comment by sebastianbochan** [comment]
Thank you for the feedback. 

It looks like that reason of the issue is data which is not ordinal. I updated your demo with minRange and ordinal parameter as false. http://jsfiddle.net/qzfhqrbq/ It seems working fine, could you confirm?

**Comment by olivierscheffler** [comment]
Hi @sebastianbochan 
Thank you for the response. It seems to working nicely thank you ! 
Just one question, on minRange, you put the value 1123200000. Can you explain how you obtain this number ?
I will test it on my real project.
Thank you !

**Comment by sebastianbochan** [comment]
It is minimum difference between two points from your data.

**Comment by olivierscheffler** [comment]
Can you explain how you obtain it ?
Because I have nearly 100 graph to display and I will need to make a dynamic calcul to have this number and I can't find how you calcul that..
Thank you !

**Comment by sebastianbochan** [comment]
More or less, your points are each month. So a extract to first points to verify it and set minRange, but you can setup minRange as 1 month (30 * 24 * 3600 * 1000) and will also work.

Demo:
- http://jsfiddle.net/vdz902j1/

**Comment by olivierscheffler** [comment]
Hi @sebastianbochan 

I have change the range of data and try it again with your settings : http://jsfiddle.net/qzfhqrbq/1/
You can see if you put the navigator as small as possible and on the extreme right and use the arrow, at some point, you are not able to scroll.
I have try to put 30 * 24 * 3600 * 1000 for minRange too and it doesn't work..
Are you able to reproduce the "bug" ?

Thank you !

**Comment by pawelfus** [comment]
I agree it's a bug. @sebastianbochan is right, it's connected to `ordinal` and `minRange` options. For some reason, n-th click on the button request to change range below calculated minRange. 

Interesting fact: removing `min` from options and disabling `ordinal` option results in a correct extremes change: http://jsfiddle.net/tfeky4ja/3/

I'm just curious why `min` is set to 10368000000 (Mar 1970) ?

**Comment by olivierscheffler** [comment]
@pawelfus ,
Thank you for your investigation.
For your question why min is set to Mar 1970, that's a good question. I think when we have developed the first version of the chart, we face problem and put Mar 1970 as min disable that problem so this option stay on the configuration.
Are you going to fix this bug ?

Thank you!

**Comment by pawelfus** [comment]
Of course, we will fix this, but I can not say any ETA for this issue.

**Comment by olivierscheffler** [comment]
Ok thank you ! Will have a look back in a few weeks so !
