### ISSUE TITLE
Api documentation 

### ISSUE THREAD

**Issue by pinkynrg** [highcharts/highcharts#6925]
Hello,

I just wrote on my database all the APIs found here: [http://api.highcharts.com/highstock/option/dump.json](url)

and I found out that a few of the returnType values are actually inaccurate.

Looking at the following list (ordered by usage): 

```
COUNT   RETURN_TYPE
1368	Number
889	Boolean
885	String
607	Function
432	Color
345	*THIS IS EITHER NULL OR EMPTY STRING*
212	Object
61	Boolean|Object
57	Array
55	CSSObject
31	Number|String
31	Array<String>
27	String|Number
27	plotOptions.series.states
25	String|Function
25	Array<Object>
11	Array<Color>
7	Array<Object|Array|Number>
6	Array<Object|Array>
5	Array<Number>
4	Mixed
2	CSS
2	Text
2	#CCC
1	Number|Boolean
1	String|Object
1	Array<String>;
```

I see for example that `scrollbar.trackBorderWidth` and `yAxis.scrollbar.trackBorderWidth` have as return_type `#CCC`. 
- Shouldn't it be `Color` if it describes a color? 
- I think is should be `Number` anyway since it is a width

Same thing for an api record that has as return_type `Array<String>;` 
- the semi-column at the end is probably unnecessary.

`CSS` should probably be `CSSObject`?

Same thing for `String` vs `Text`

Thanks

**Comment by pawelfus** [comment]
Hi @pinkynrg 

Thank you for reporting, you are right.

**Comment by pinkynrg** [comment]
I will keep listing details that may or may not be documentation bugs:

- "values" is supposed to be either NULL or an Array. In a few case it's just a simple string `true, false` instead of [true, false]: I'm referring to plotOptions-treemap--interactByLeaf, series<solidgauge>--rounded, series<treemap>--interactByLeaf

**Comment by pinkynrg** [comment]
I see that you follow `this-sort-of--pattern` to created IDs. There are for records that maybe, should not be there since the actual title (api) is empty string:

`plotOptions-gauge-- `
`plotOptions-solidgauge--`
`series<gauge>--`
`series<solidgauge>--`

**Comment by pinkynrg** [comment]
thanks!

**Comment by pinkynrg** [comment]
Actually I just checked the public api to the following links and the majority of the issues are still there. 
I also see that commit commit 9f7fc29 is only changing `Text` to `String` and `true, false` to `[true, false]`.
Is there are reason why the remaining points are not considered issues?

**Comment by TorsteinHonsi** [comment]
> I just checked the public api to the following links and the majority of the issues are still there.

Yes, it will take some time before this comes online, as we're in the middle of a refactoring of the API app.

> Is there are reason why the remaining points are not considered issues?

Yes, as far as I can see the other issues were already resolved in the new JSDoc-based docs.
