### ISSUE TITLE
boost module with navigator.adaptToUpdatedData and scrollbar.liveRedraw

### ISSUE THREAD

**Issue by jikadu** [highcharts/highcharts#6927]
Can i add the boost module and set navigtor.adaptToUpdateDate and scrollbar.liveRedraw all true and still get a good performance. I have see on the documentation that it has to be set to false but I need this in my project, Is the a way around it.
Chrome and Opera seem to have good performance but firefox and IE is a bit slow.
Any suggestion?

**Comment by sebastianbochan** [comment]
Hi @jikadu ,
    Currently the boost module does not support full Highstock and liveRedraw / adaptToUpdateDate options, but please replicate your example (on the jsfiddle.net) and we will test it for the further debugging.

**Comment by jikadu** [comment]
This the example on jsfiddle.net.
https://jsfiddle.net/3753vt85/54

**Comment by sebastianbochan** [comment]
Thank you for the feedback. 

@cvasseng any ideas?
