### ISSUE TITLE
Scrollbar is shown when there is no data for 'datetime' x-axis

### ISSUE THREAD

**Issue by aliosss** [highcharts/highcharts#6930]
#### Expected behaviour
In 'datetime' x-axis, no scrollbar is shown when there is no data.

#### Actual behaviour
Scrollbar is shown and scrollable within a wide interval in case there is an empty series in datetime chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/ucLpf6qr/1/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @aliosss 

Thank you for reporting this bug, I will take care of it.
