### ISSUE TITLE
Problem about the range of y-axis 

### ISSUE THREAD

**Issue by a1300300** [highcharts/highcharts#6931]
#### Actual behaviour
![1](https://user-images.githubusercontent.com/6691328/27941761-ed34c6bc-6304-11e7-9063-e851703a9b83.jpg)

![2](https://user-images.githubusercontent.com/6691328/27941765-f1991c76-6304-11e7-821f-ac6e0dab5e4e.jpg)

#### issue detail
Hello, we are using highcharts library to display our dataset on our website; however, the problem is that in some charts, the range of Y-Axis is too broad than what we expect, in some of them the range we don't need even occupy 1/2 space. 

I know there are two attributes, floor and ceiling , that can specify the range of y-axis; but it seems not to work on the chart that has more than one Y-Axis like the examples above. In addition, the results are the same when using version 5.0.7 and 5.0.12. Is there any solution we can use  to resolve this problem?

Thank you so much.

#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Hi @a1300300 

Thank you for reporting this issue, however without live demo we may not be able to help you. If you have problems with setting up a demo, please send us an email, our support team will help you. 

This is just a guess, but have your tried to change [`yAxis.minPadding`](http://api.highcharts.com/highcharts/yAxis.minPadding) and [`yAxis.maxPadding`](http://api.highcharts.com/highcharts/yAxis.maxPadding) ?

**Comment by a1300300** [comment]
Hello @pawelfus 

I haven't tried yAxis.minPadding and yAxis.maxPadding, I will try them in these days; if they still don't work, I will set up a live demo to show you. Thank you so much.

**Comment by a1300300** [comment]
It seems the yAxis.minPadding and yAxis.maxPadding can't work for my problem.

And I've built two similar examples in JSFiddle.
1.  The first one is the normal one
https://jsfiddle.net/a1300300/m1sx38do/
![screen shot 2017-07-10 at 4 19 48 pm](https://user-images.githubusercontent.com/6691328/28008846-adff56cc-658b-11e7-90a4-6f190c4b2328.png)

The data set of Sea-Level Pressure is [1000, 1016, 1015.9, 1015.5, 1012.3, 1009.5, 1009.6, 1010.2, 1013.1, 1016.9, 1018.2, 1016.7], and the data set of Temperature is [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]

2. The second one is the one which has the range of Y-axis problem I faced
https://jsfiddle.net/a1300300/f1goh7of/
![screen shot 2017-07-10 at 4 27 06 pm](https://user-images.githubusercontent.com/6691328/28009081-acb97846-658c-11e7-8e21-f1a208cd5be4.png)

I only change the first element in array of Sea-Level Pressure from 1000 to 990
The data set of Sea-Level Pressure is [990, 1016, 1015.9, 1015.5, 1012.3, 1009.5, 1009.6, 1010.2, 1013.1, 1016.9, 1018.2, 1016.7], and the data set of Temperature is [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6].

The image above shows that the max limitation of the range of yaxis increases from 1020 to 1040 even though I set the value 1000 to 990.

Is there any solution by that the yaxis can be set properly like the first example? If there is still question for my explanation of my problem, please reply to me. Thanks.

**Comment by pawelfus** [comment]
Hi @a1300300 

I didn't notice you have two yAxes, my apologies. This is caused by [`alignTicks`](http://api.highcharts.com/highstock/chart.alignTicks) option. With multiple axes, we align ticks because it's more readable than without aligning them, demo: https://jsfiddle.net/f1goh7of/1/

By changing the first value you actually change extremes for the first yAxis (new min =990), that cause changing `tickInterval`, which results in different extremes. What I want to say that I don't see why extremes from the first chart should be applied for the second one.

It looks like a duplicate of #5628 (changing height will results in extremes similar to the ones you expect to see: https://jsfiddle.net/m1sx38do/2/).
