### ISSUE TITLE
Scatter Chart damaged in 5.0

### ISSUE THREAD

**Issue by MiroLiska** [highcharts/highcharts#6933]
I have seen the our scatter charts are damaged after upgrade from 4.2.3 onto 5.0.12. See the version with 4.2.3 at http://jsfiddle.net/hh8ochm5/ :
![expected](https://user-images.githubusercontent.com/23024867/27951728-29e3d200-6306-11e7-9e35-7fccfd302a8e.png)

After upgrade to 5.0.12, the zero line is not anymore aligned with the x axis, thus creating ugly gap - http://jsfiddle.net/hh8ochm5/1/ :
![bug](https://user-images.githubusercontent.com/23024867/27951762-470ef8dc-6306-11e7-98bd-02e9db797e91.png)

This is clearly a bug in 5.0.12. If I set the height of the container to something smaller, e.g. 250px, the it works properly - http://jsfiddle.net/hh8ochm5/2/ :
![resized](https://user-images.githubusercontent.com/23024867/27951777-5658a4a0-6306-11e7-8e8f-b5ec30709b20.png)

**Comment by pawelfus** [comment]
Hi @MiroLiska 

Thank you for reporting this issue. We have this reported as #6897, which should be fixed, please take a look: http://jsfiddle.net/ndgmgacz/

**Comment by MiroLiska** [comment]
Hi. 
Thanks for pointing me to the right direction. I have reported this problem to the highcharts support on 26.06., but did not receive any response until now. GitHub probably works better than your support email.

**Comment by pawelfus** [comment]
Hi @MiroLiska 

I just checked and response was send 26.06 too. @KacperMadej even created #6897 ticket (the one I referred above) for you. Maybe you have our email in spam?

**Comment by pawelfus** [comment]
After some digging, I found out you also received 30.06 and 04.07 answers from us. Could you check the spam box and let us know if that's the case?

**Comment by MiroLiska** [comment]
Hello Pawel

Unfortunately, I really did not receive any e-mails from you at all. That’s why I kept sending emails (26.6., 30.6., 4.7.). I have nothing in my junk box either.

Who exactly has sent that e-mail to me? helpdesk@highsoft.com  ? I will check with our network admin and the e-mail provider. Maybe they have blocked the sender without notifying me.

Miro

**Comment by pawelfus** [comment]
Yes, we send emails from this email. I've just send you another email, using a different alias.
