### ISSUE TITLE
Subtitle cannot be updated if it had an empty string before

### ISSUE THREAD

**Issue by simdevmon** [highcharts/highcharts#6934]
#### Expected behaviour
If I init a chart with a subtitle having an empty string as text, I would expect that I am able to update the subtitle later with `chart.subtitle.update()`

#### Actual behaviour
Subtitle is not updated when calling the `update()` method.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/title-update/

Simply replace 

```
    subtitle: {
        text: 'Subtitle'
    },
```

with

```
    subtitle: {
        text: ''
    },
```

And click on update subtitle. This also happens when the subtitle is not defined, null, ect.

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @simdevmon 

Thank you for reporting this bug. It looks like `subtitle.update()` doesn't work but `chart.setTitle(null, options);` does work without issues, demo: http://jsfiddle.net/ke8bxfxw/

**Comment by KacperMadej** [comment]
Working fine in version 6.1.4
Closing as resolved
