### ISSUE TITLE
Offline PDF exporting doesn't respect column opacity 

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#6935]
This works correctly when using the Highcharts export server, but not for offline/client side exports.

Chart:
![image](https://user-images.githubusercontent.com/14222462/27960779-858d1690-62fa-11e7-962e-7ecd30cbbc1e.png)

Export:
![image](https://user-images.githubusercontent.com/14222462/27960813-a4371370-62fa-11e7-98f2-b7b7a743b8b4.png)

#### Expected behaviour
Offline exporting should correctly reflect the opacity of the columns.

#### Actual behaviour
column opacity isn't being respected

#### Live demo with steps to reproduce
https://jsfiddle.net/qz6r2xc2/

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @Rashaine,
Thank you for the reporting. 

_Internal note_
@oysteinmoseng problem appears only with PDF format.

**Comment by TorsteinHonsi** [comment]
It comes down to this issue in svg2pdf: https://github.com/yWorks/svg2pdf.js/issues/29

Will continue digging tomorrow.

**Comment by TorsteinHonsi** [comment]
Resetting the `activeGState` in `vendor/jspdf.src.js` will fix it. Awaiting upstream changes.

```js
    API.restoreGraphicsState = function () {
      out("Q");

      // restore previous font state
      var fontState = fontStateStack.pop();
      activeFontKey = fontState.key;
      activeFontSize = fontState.size;

      activeGState = null;

      return this;
    };
```
