### ISSUE TITLE
Highcharts.Net wrapper does not include dataLabels option in JSON if it is not enabled

### ISSUE THREAD

**Issue by schutze** [highcharts/highcharts#6937]
#### Expected behaviour

Using Highcharts.NET wrapper (Highcharts.Web.Mvc.dll) Version 5.0.6397.2889 with this VB.NET code:

Dim mGauge As Highcharts = New Highcharts()

mGauge.PlotOptionsGauge = New PlotOptionsGauge() With {.DataLabels = New PlotOptionsGaugeDataLabels() With {.Enabled = False}}

... additional code excluded for simplicity ...

Dim Highsoft As New HighsoftNamespace()
Highsoft.Highcharts(mGauge, "chart").ToHtmlString()

should generate JSON that includes a "dataLabels" option like below:

"dataLabels": { "enabled": false },

**Note:** There may be other instances where the wrapper does not emit JSON for options that are specifically disabled and they are enabled because that is the default behavior of the Highchart JS library.  A code review should be performed to uncover other settings that are excluded from the generated JavaScript when they are not enabled.

#### Actual behaviour

No "dataLabels" option is included in the generated JSON so the data label appears by default.

#### Live demo with steps to reproduce

The jsFiddle below demonstrates the issue:

[https://jsfiddle.net/Lybuxqxt/1/](https://jsfiddle.net/Lybuxqxt/1/)

The generated JSON should include the "dataLabels" option with "enabled": false but it does not so the data label appears on the gauge.  The data label will not appear if the commented option in the jsFiddle is uncommented.

#### Affected browser(s)
Browser does not matter

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem. The issue is forwarded to our .NET developer.
