### ISSUE TITLE
Category text gets cut when y axis has no title 

### ISSUE THREAD

**Issue by ypconstante** [highcharts/highcharts#6938]
#### Expected behaviour
The beginning of the text should be visible

#### Actual behaviour
When the first category text is too big, the begining of the text is draw outside the canvas area

#### Live demo with steps to reproduce
http://jsfiddle.net/s3dzqpzo/

**Comment by daannijkamp** [comment]
You can use the Margin Left property
http://api.highcharts.com/highcharts/chart.marginLeft

Demo: http://jsfiddle.net/s3dzqpzo/2/

**Comment by pawelfus** [comment]
Thank you for reporting the issue.

*Internal note:*
It looks like xAxis.labels didn't invoke recalculation for width, only for height.

**Comment by TorsteinHonsi** [comment]
We need to set a width to demonstrate precisely: http://jsfiddle.net/s3dzqpzo/3/

**Comment by TorsteinHonsi** [comment]
... and it appears to be fixed in the master: http://jsfiddle.net/s3dzqpzo/4/

Working since https://github.com/highcharts/highcharts/commit/5e431530b

Possible duplicate of #6778

**Comment by ypconstante** [comment]
Hi guys, I tried to see the fixed version, but it is not loading. The code in http://github.highcharts.com/highcharts.js is not running.

**Comment by sebastianbochan** [comment]
Hi @ypconstante 
You can try to test the developer version here: https://github.highcharts.com/hc5-fixes/highcharts.js and let us know if works properly.

Demo:
- http://jsfiddle.net/1s7bfLho/

@TorsteinHonsi it looks like master branch has an Unexpected identifier inside.

**Comment by TorsteinHonsi** [comment]
Master works fine now: http://jsfiddle.net/1s7bfLho/1/
