### ISSUE TITLE
Line chart

### ISSUE THREAD

**Issue by royigoldi** [highcharts/highcharts#6940]
Hi,
I want to know how i can get this implementations? which charts?

![image](https://user-images.githubusercontent.com/20413250/27995365-a8db30f0-64d5-11e7-9995-93236bdde103.png)

or 

![image](https://user-images.githubusercontent.com/20413250/27995388-24f12852-64d6-11e7-9e49-a48b3dcd93c9.png)

Thanks,
Royi

**Comment by daannijkamp** [comment]
You can use the rounded corners plugin.
https://github.com/highcharts/rounded-corners

**Comment by pawelfus** [comment]
For support related questions please send us an email. We use github tickets as bug reports.

**Comment by royigoldi** [comment]
Ok sorry and thanks

בתאריך 10 ביול' 2017 12:11 PM,‏ "Paweł Fus" <notifications@github.com> כתב:
