### ISSUE TITLE
Confusing behavior on click, if the nearest point belongs to another serie

### ISSUE THREAD

**Issue by gregoirechauvet** [highcharts/highcharts#6944]
Using theses options:
```
plotOptions: {
  series: {
    cursor: 'pointer',
    events: {
      click: function(event) {
        console.log(this.name);
      }
    }
  }
}
```

#### Expected behaviour
When my cursor changes to a pointer, I want to be able to have the serie that I clicked on in the callback.

#### Actual behaviour
When you click on a serie, if the nearset point belongs to another serie, this is the second serie which is clicked.

##### Solutions?
Maybe give the nearest point on that particular serie to the callback? Or add a option to have the serie even without a point?
If not possible, do not change the cursor to a pointer when hovering a serie if the nearest point is on another serie?

#### Live demo with steps to reproduce
http://jsfiddle.net/992e1nqh/2/
Click on **serie 2** on April. The console show that **serie 1** as been clicked. I understand that the nearest point is on **serie 1**, but the cursor is changing to a pointer when you hover **serie 2**, which is very confusing.

I found a related issue from 2015 which ask for click logic to be changed: https://github.com/highcharts/highcharts/issues/4353.

#### Affected browser(s)
Chrome 59
Firefox 54

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

Minimal demo: http://jsfiddle.net/992e1nqh/3/
Steps:
Click in the middle of the black line to see an event being fired for the different series.

**Comment by jon-a-nygaard** [comment]
Hi @Prince-Leto , as a workaround you could try setting [`stickyTracking: false`](http://api.highcharts.com/highcharts/plotOptions.series.stickyTracking). It will make the click behaviour more as expected, but the mouseout event will fire when the pointer leaves the series, which causes the tooltip to hide.
Here's an [Example](http://jsfiddle.net/992e1nqh/5/) for you. You may keep the tooltip visible longer by modifying [`tooltip.hideDelay`](http://api.highcharts.com/highcharts/plotOptions.area.tooltip.hideDelay).

**Comment by jon-a-nygaard** [comment]
@Prince-Leto You can also identify the clicked series by looking at `event.target`. Here is an [example](http://jsfiddle.net/992e1nqh/6/) which achieves the behaviour you are looking for.

We're not sure if modifying the click behaviour accordingly would make the case better, since that would create a mismatch between the tooltip, series.click and point.click.

**Comment by Prince-Leto** [comment]
Oh! Your solution with `event.target` is what I was looking for. Thanks a lot :)

I also tried to use `stickyTracking: false`, but in my app I am using a shared tooltip, and as you said, the tooltip disappear if my cursor is too far away from a serie. I my case I prefer the previous behavior.
