### ISSUE TITLE
DOC Problem

### ISSUE THREAD

**Issue by NieShuai** [highcharts/highcharts#6946]
#### Expected behaviour
There is a problem with the official chinese doc. The links are listed below.

#### Actual behaviour
'lower left corner' should be '左下角', but it has been translated to '左上角' in this doc.

#### Live demo with steps to reproduce
http://api.highcharts.com/highcharts/Renderer.text
https://api.hcharts.cn/highcharts#Renderer.text

**Comment by pawelfus** [comment]
Thank you for reporting!

**Comment by zhy1stgg** [comment]
Thanks for your reporting, We just fixed it, We will careful check for other possible mistake.
