### ISSUE TITLE
img onload not firing on some browsers

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#6950]
#### Expected behaviour

I need to determine when my `chart.renderer.image` is loaded (the image is fetched from a remote url so I can't rely on it loading quickly).  I set an `onload` handler for this purpose.  The `onload` handler should fire when the image is loaded.

#### Actual behaviour

On some browsers... probably the more recent ones... it works as expected.  On others, the handler is never apparently called.

#### Live demo with steps to reproduce

Just a basic image-loading example:

http://jsfiddle.net/d242moc0/

#### Affected browser(s)

I have discovered this in an Android context... seems to be fine on Android 7 but not on Android 4.4 and 4.3.  Probably relates to the version of WebView rather than Android per se.

I strongly suspect that this is due to caching... if the image is in the local cache then then `onload` event isn't firing, at least for some (older?) browsers.  Maybe the newer browsers handle things differently and ensure that the `onload` event fires regardless of whether the image is cached or not.

Some clues may be found in [this post](https://stackoverflow.com/questions/12354865/image-onload-event-and-browser-cache)... seems that "setting the `onload` property before the `src`" should help.

Maybe the caching thing is a red herring, but it seems like a possibility.

Are there any quick fixes or workarounds?

**Comment by sebastianbochan** [comment]
Hi @drmrbrewer 
Thank you for the reporting. 

It looks like the issue with missing externalResourcesRequired parameter in image. When I added it by attr() method, seems to working fine (Android 4.1.x). Could you confirm?

Demo:
- http://jsfiddle.net/zu4t2sq8/1/

Docs:
- https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/externalResourcesRequired

**Comment by drmrbrewer** [comment]
@sebastianbochan that does seem to have worked.  I haven't had a chance yet to watch the Android device logcat as the code is executing in the WebView (which is how I knew for certain that the `onload` handler wasn't being called) but I'm fairly sure that it's doing as it should now.

So, in your own tests on Android 4.1.x, with no `externalResourcesRequired` parameter you see the same issue I was seeing, i.e. `onload` not firing?  And with `externalResourcesRequired` set to `true` it works?  If so, I'm satisfied that it's the same issue and that your solution fixes it.

I love it when the solution is straightforward  :)

BTW are you testing this in an emulator?  BrowserStack?  It would be handy to know, and be able to roadtest this stuff quickly on various versions of Android.  I find the emulators in Android Studio to be a complete PITA to use... would be far nicer to test somewhere else, especially considering what I'm doing is basically just running stuff in a WebView.

**Comment by sebastianbochan** [comment]
Hi @drmrbrewer,
     I tested in native devices (HTC android 4.1) in native browser. In Chrome always worked properly.

Let me know about your tests and if problem will still appear, we will try to find other workaround.

**Comment by drmrbrewer** [comment]
@sebastianbochan no I think it's working well.  My remaining doubt is whether setting `externalResourcesRequired` to `true` forces the external resource to be fetched regardless of whether that resource is cacheable, but this seems not to be the case with some brief testing.  So I'm satisfied with this solution, at least until I find another problem with it :)

**Comment by sebastianbochan** [comment]
Thank you for the feedback.
