### ISSUE TITLE
highcharts documentation doesn't mention useHTML option for axis title text

### ISSUE THREAD

**Issue by choudhary001** [highcharts/highcharts#6951]
Hi,
I was trying to show Greek letter rho in X axis title text using &rho; but it wasn't getting rendered properly. After some googling I found that I can set useHTML option like below. However I didn't find this option in highcharts documentation of xAxis.title.text (See [http://api.highcharts.com/highcharts/xAxis.title.text](http://api.highcharts.com/highcharts/xAxis.title.text)).

Is this an officially supported option for axis title text or is there any other way to achieve this requirement.

```javascript
 "xAxis": {
        "title": {
            "text": "<span style='font-family:\"Times New Roman\"'>&rho; = -0.18</span>",
            "useHTML": true
        }
}
```
Thanks!

**Comment by sebastianbochan** [comment]
Thank you for the reporting.
