### ISSUE TITLE
Highstock  bigger data with liveRedraw set to True.

### ISSUE THREAD

**Issue by jikadu** [highcharts/highcharts#6952]
I'm trying to use highstock for my project. I have a large data so I'm using the boost module.
I want liveRedraw to kick in when i'm receiving a fewer data and false it when its a bigger data.
Can i achieve this in highstock?

**Comment by pawelfus** [comment]
Hi @jikadu 

For support related questions, please send us email or create a topic on our forum. We use github issues as bug reports. You can find more details [here](https://www.highcharts.com/support).

Thank you,
Paweł
