### ISSUE TITLE
Emoji version of unicode characters always used in certain browsers

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#6954]
#### Expected behaviour

I'm not really sure what the expected behaviour is.  All I know is that unicode characters can be displayed in both plain text style or emoji style, and I would expect somehow to be able to control this.

#### Actual behaviour

Unicode characters seem to display always in emoji style, at least in some browsers, and at least in highcharts.

#### Live demo with steps to reproduce

http://jsfiddle.net/cuek3qz4/

See my [stackoverflow post](https://stackoverflow.com/q/44903314/4070848) for an explanation of the issue.    Initially I thought that this wasn't specific to highcharts, but was more of an html issue generally. 
 
However, the second example in my SO post (in an Android browser) seems to suggest that the rendering of these unicode characters inside highcharts is treated differently to rendering outside highcharts... forcing use of the emoji version in highcharts when I really don't want that.

#### Affected browser(s)

Seems very inconsistent.  At least on Android 7.0 the unicode character is displayed in emoji style inside highcharts but plain-text style outside.  I want to display plain-text style always, or at least to be able to have control over this.  See the stackoverflow post linked above.  I can't seem to get [version selectors](http://mts.io/2015/04/21/unicode-symbol-render-text-emoji/) to have any effect, in any context.

**Comment by pawelfus** [comment]
Hi @drmrbrewer 

I just tested your demo (http://jsfiddle.net/cuek3qz4/) on Android 6 and 7 devices and both have very similar result as on Chrome (osx), compare:

- chrome osx: 
![screen shot 2017-07-13 at 12 21 30](https://user-images.githubusercontent.com/1453926/28162001-e719ab2e-67c5-11e7-94e6-058586d960f4.png)


- android 6&7:
![screen shot 2017-07-13 at 12 26 33](https://user-images.githubusercontent.com/1453926/28162193-8b30b446-67c6-11e7-9613-57dbf475c4ba.png)

I also tested HTML tags in title, result was the same, tested with: http://jsfiddle.net/cuek3qz4/1/

I think it depends on launcher and installed add ons/fonts. I remember similar issues with numbers and Skype ;)

**Comment by drmrbrewer** [comment]
@pawelfus as mentioned in my OS post, on Android 7 I'm getting the following:

![chrome android](https://user-images.githubusercontent.com/9009792/28162694-e816a780-67bf-11e7-9db4-5145b7cd50c4.jpg)

Can you explain why the emojis show within highcharts but not outside highcharts?  What is highcharts doing which means that emojis are used rather than plain text?  Since the characters are rendered in plain text outside of highcharts, surely there is some way in highcharts of producing the same result there?

**Comment by pawelfus** [comment]
@drmrbrewer 

In Highcharts, by default SVG tags are rendered, not HTML, like you did in your example - so that may be the reason. Could you try my second demo? 

I would love to debug and answer your question: "why", but I don't have this problem on any real device with Android 6 (Huawei 9) or 7 (HTC 10). Could you tell me your device details?

**Comment by drmrbrewer** [comment]
@pawelfus yes it's the same on my device even with `useHTML: true`

I had already updated my reply with device details, but here it is:

Samsung Galaxy S6
Model SM-G920F
Android 7.0
Nova Launcher

Thanks... this issue is small but surprisingly irritating!

**Comment by drmrbrewer** [comment]
@pawelfus see my [updated SO post](https://stackoverflow.com/q/44903314/4070848), with a bit more detail about where the fonts are coming from... seems that I've now got a way to force non-emoji characters to be used for the symbols, even on Samsung Android:

![screenshot_20170714-092959](https://user-images.githubusercontent.com/9009792/28204897-b4e01a96-6877-11e7-968b-ae7aa0403f05.jpg)

It seems to be a font issue... my guess is that many (possibly most) font families won't have characters for all of the many unicode symbols, and in that case the system font is maybe used?  And the system font on the Samsung maybe has these coloured emojis?  Maybe you have some further insight on this, and perhaps a better solution / workaround?

BTW this seems to work even with `useHTML` set to `false`... is that surprising?

**Comment by pawelfus** [comment]
Oh, that means default font used in Highcharts (Lucida Grande, [details](http://api.highcharts.com/highcharts/chart.style)) is not a "safe" font? 

If this is a problem with fonts, then I am not surprised. `useHTML` doesn't change styles/fonts, only SVG -> HTML.

Honestly it's the first time I see this issue. Of course, there are alternative solutions: use glyphicons, images etc. Then rendering will not depend on a user browser.

**Comment by drmrbrewer** [comment]
@pawelfus I've hit a snag with my "solution"... it works nicely for the sun symbol, but for the very next unicode character (moon symbol) it doesn't... so maybe that symbol is missing from the `serif` font family and it reverts again to system emoji.

[jsfiddle with moon](http://jsfiddle.net/a65qbyjr/1/)

![screenshot_20170714-100441](https://user-images.githubusercontent.com/9009792/28205955-1f948378-687c-11e7-9821-efda05328129.jpg)

So the solution is probably still very patchy.

I'm reluctant to use images because I want the symbol to be styled the same as the text, mainly the same colour... the font colour is user-definable.

**Comment by drmrbrewer** [comment]
I'm getting a sinking feeling that the only way forward is indeed to use images :(

What is the most straightforward way to integrate symbols into the flow of text, i.e. on the same line as text to the left and right e.g. in the chart's title, with the same size and colour?

Seems like svg shapes are available for these symbols, such as the [moon symbol](http://www.fileformat.info/info/unicode/char/263d/first_quarter_moon.svg) that is now causing me problems.  Can this be incorporated easily into the flow of text?

**Comment by drmrbrewer** [comment]
OK I have thrown in the towel, and given up on trying to get unicode characters to display in the way I want them.  It really shouldn't be this difficult?  (Nothing to do with highcharts.)  Instead, I've worked out how to use inline svg to render these symbols, and it's actually not that hard to get the sizing and colour to match the surrounding text.  And, as things often happen, it actually looks nicer than using the standard unicode characters.

**Comment by drmrbrewer** [comment]
Further update... [this answer](https://stackoverflow.com/a/45094126/4070848) on my SO post has provided an even neater means of overcoming this issue, by referring to a minimal custom font to ensure that symbols are always available for the codes that you want.  I'm now using that solution.  So this isn't a highcharts issue after all, but I've learned a lot in this process.

**Comment by pawelfus** [comment]
Thank you for sharing the details!
