### ISSUE TITLE
highcharts can't horizontal Linkage

### ISSUE THREAD

**Issue by GerogeKk** [highcharts/highcharts#6955]
our project need to  do this.
Two linkage chart, one is left, anohther is right,
But highcharts can't do this,
this is demo's Url 'https://www.hcharts.cn/demo/highcharts/synchronized-charts'
i think highcharts should support it.

**Comment by pawelfus** [comment]
Hi @GerogeKk 

It's possible, you can link any charts, the design doesn't matter, but of course it requires some coding. If you have any troubles, please contact with our support.
