### ISSUE TITLE
Accessibility: Default aria-label text i18n

### ISSUE THREAD

**Issue by sprungmarker** [highcharts/highcharts#6958]
#### Expected behaviour
For accessibility.js - default texts as aria-label as "Interactive chart. Desktop screen readers from 2009 to 2015. Use up and down arrows to navigate with most screen readers." can be translated in other languages (i18n)

#### Actual behaviour
For accessibility.js - default texts can not be translated in other languages (i18n) or configured in highcharts options

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/accessibility/accessible-line/

#### Affected browser(s)
screenreader reads default english text

**Comment by sebastianbochan** [comment]
Thank you for reporting!

@oysteinmoseng
