### ISSUE TITLE
Gantt Build Breaks Solidgauges

### ISSUE THREAD

**Issue by amber-workxpress** [highcharts/highcharts#6960]
So I have a setup where we're trying to include Gantt charts on the same page as other charts, including potentially solid gauges, meaning all of them must work from the same Highcharts repository. Unfortunately, it seems like this build will break solid gauges, due to something related to colors.

#### Expected behaviour

Should show solid gauges appropriately when including the Gantt build of core Highcharts.

#### Actual behaviour

No gauges actually show. Received console error is

> Uncaught TypeError: c.color.tweenTo is not a function
> at H.Axis.toColor (solid-gauge.js:11)
> at solid-gauge.js:12
> at Array.forEach (<anonymous>)
> at H.each (highcharts-gantt.src.js:1608)
> at object.drawPoints (solid-gauge.js:12)
> at object.render (highcharts-gantt.src.js:18460)
> at object.render (highcharts-more.js:34)
> at highcharts-gantt.src.js:15918
> at Array.forEach (<anonymous>)
> at H.each (highcharts-gantt.src.js:1608)

This behavior can _**not**_ be resolved, as far as I can tell, by not setting a color explicitly; I've yet to get a solid gauge to work at all with this build.

#### Live demo with steps to reproduce
http://jsfiddle.net/amber_workxpress/a0j3f8uu/1/ (uses https://github.highcharts.com/gantt/highcharts-gantt.src.js)
Can also be reproduced with http://jsfiddle.net/amber_workxpress/a0j3f8uu/2/ (which uses https://github.highcharts.com/gantt/highcharts.js)

#### Affected browser(s)
Google Chrome

**Comment by sebastianbochan** [comment]
Hi @amber-workxpress ,
Thank you for reporting.

**Workaround**
Add definition for tweenTo in color prototype.

Demo:
- http://jsfiddle.net/qorrk91b/

**Comment by amber-workxpress** [comment]
Ah, thank you for the workaround!

**Comment by TorsteinHonsi** [comment]
Looks like highcharts-gantt.src.js is built from a stage where the current master is not merged in. The `tweenTo` function is relatively new. This will be merged before final release.
