### ISSUE TITLE
Including Accessibility Module in Gantt Build breaks recreating chart in React

### ISSUE THREAD

**Issue by amber-workxpress** [highcharts/highcharts#6961]
I've encountered a very odd error involving an interaction between updating the props of a React component and the accessibility module.

Specifically, the issue appears to occur under the following scenario:
1. Include both https://github.highcharts.com/gantt/highcharts-gantt.src.js and https://code.highcharts.com/modules/accessibility.js
2. Include a method to destroy and re-create the chart whenever the options props are updated (triggered via componentWillReceiveProps)
3. Update the props to include new options.

#### Expected behaviour
It should destroy and recreate the chart without issue.

#### Actual behaviour

The chart refuses to destroy and recreate itself and just stays as it was. The received error is:

> Uncaught TypeError: Cannot read property 'hcEvents' of undefined
> at H.removeEvent (VM5218 highcharts-gantt.src.js:1695)
> at H.Chart.<anonymous> (VM5221 accessibility.js:39)
> at H.fireEvent (VM5218 highcharts-gantt.src.js:1821)
> at H.Chart.destroy (VM5218 highcharts-gantt.src.js:16090)

#### Live demo with steps to reproduce
http://jsfiddle.net/amber_workxpress/upe3bm3r/23/

1. Click the "2011-2013" button
2. Click the "2010--2016" button.

After both buttons have been pressed this issue will occur each time the button is pressed.

Two relevant notes:

1. This is definitely caused by including the Gantt chart code itself. I can include only https://github.highcharts.com/gantt/highcharts.js and have it function without issue, but adding in https://github.highcharts.com/gantt/modules/gantt.src.js or instead using https://github.highcharts.com/gantt/highcharts-gantt.src.js will cause the issue to occur. This issue does not include when using the Production build, but unfortunately, that doesn't have Gantt charts.
2. Using chart.update does resolve the issue, but does not satisfy our use case because the number and names of the series we are using may change between option updates, but using chart.update will leave in old series options after they should have been removed. (You can see an example of this behavior [here](http://jsfiddle.net/amber_workxpress/upe3bm3r/24/)) My research had shown that the best way to resolve this was to destroy and rebuild the chart if the series options changed; if there's another workaround that would let us update the series arbitrarily without encountering this issue, I'd definitely be open to using it.

#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Thank you for reporting!

**Minified demo:**
http://jsfiddle.net/gvpjr215/

*Internal note:*
It looks like in second `chart.destroy()`, [this line](https://github.com/highcharts/highcharts/blob/0fd2d3a1bcc4ca754cc81a6006d380178c367764/js/modules/accessibility.src.js#L1069) is called with `chart=undefined`. `chart.destroy()` method is different in Gantt and Highcharts which probably means there is more old methods in the core.

**Comment by oysteinmoseng** [comment]
Closing this as it seems to be working with the current code. Feel free to reopen if this is still an issue.
