### ISSUE TITLE
showLoading not working

### ISSUE THREAD

**Issue by amit1911** [highcharts/highcharts#6962]
#### Expected behaviour
after I call `chart.showLoading` it should show the loading screen.

#### Actual behaviour
Does not show any loading screen

#### Live demo with steps to reproduce
http://jsfiddle.net/amit1911/s0k2jo94/
1. Click on any bar to drill down.
No loading msg is seen.

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @amit1911 

It works, but wait() prevents DOM to get a chance to redraw. For example don't block the process, but use `setTimeout()` and you will see it's fine. Demo: http://jsfiddle.net/ddh3x5ek/

**Comment by amit1911** [comment]
i used `wait` to simulate some processing. In my actual project, I am doing some processing to generate the drilldown data which takes some time, so my code is something like
```
chart.showLoading('loading...')
// a lot of processing - takes a few seconds
chart.hideLoading();
```
But I don't see any loading in this case because as you mentioned that javascript is blocking the process. What can I do in this case? i cannot just use `setTimeout` as i don't know how much time the processing is going to take.

**Comment by pawelfus** [comment]
I think you can, very simple example:

```
chart.showLoading('loading...')
setTimeout( function () {
    // a lot of processing - takes a few seconds
    chart.hideLoading();
});
```
If you will have any problems, please get in touch with our support.
