### ISSUE TITLE
Drilldown with boost module fails if more than 5000 points

### ISSUE THREAD

**Issue by amit1911** [highcharts/highcharts#6964]
#### Expected behaviour
Chart should drilldown.

#### Actual behaviour
Does not drilldown. Error in console.

#### Live demo with steps to reproduce
http://jsfiddle.net/amit1911/rcmcre6L/

#### Affected browser(s)
All

**Comment by amit1911** [comment]
Seems to be caused by `each(series.points, function(point, i) {` in `updateNames` function`. If we change `series.points` to `series.points || []`, then it works fine.

**Comment by sebastianbochan** [comment]
The issue is caused by too many categories which you try to apply on xAxis.

**Workaround**
- in drilldown event, update the xAxis.type as linear: http://jsfiddle.net/3wdptuw5/

**Comment by amit1911** [comment]
Is there a limit on the x axis categories list? I cannot use linear because I have to display the category names.

**Comment by amit1911** [comment]
i just noticed that if i set the axis type to 'linear' and set 'categories', then the x axis values are taken from the 'categories' array. and the drilldown works fine as well but this seems wrong because the axis type is 'linear'. And i still don't understand why changing the `series.points` to `series.points || []` in `updateNames` fixes the issue.

**Comment by pawelfus** [comment]
**Workaround:**
Don't use `categeory` type, but predefined category names, where each drilldown series has own categories (using `Axis.setCategories`), simplified demo: http://jsfiddle.net/tjx2k102/

**Comment by amit1911** [comment]
Thanks @pawelfus...This is what i am doing right now but wasn't sure if this is okay because to me it seemed like using `type : category` with categories is the correct way. I didn't know we can use categories with linear type axes as well.
