### ISSUE TITLE
Bubble charts - Not reacting to hover when tooltip is shared

### ISSUE THREAD

**Issue by melloc01** [highcharts/highcharts#6965]
#### Expected behaviour
Bubble chart reacts to hover and shows shared tooltip.

#### Actual behaviour
Bubble chart do not render shared tooltip nor highlight any point on hover when tooltip is set to shared.

#### Live demo with steps to reproduce
http://jsfiddle.net/otf829cm/

Just hover the Chart.

#### Affected browser(s)
Browser agnostic, tested in several browsers.

**Comment by sebastianbochan** [comment]
The tooltip.shared works with all ordered series, but not for pie, scatter, bubble.

You can find more information about it in our docs.
- http://api.highcharts.com/highcharts/tooltip.shared

**Comment by melloc01** [comment]
Hi @sebastianbochan, thanks!

Works great, I see a little issue though:

`this.points` is undefined, even for equal `x` values as you can see here: http://jsfiddle.net/nqLbrph8/2/ (on the console log)

Even with equal `x` and `y`, no prop `points` is ever defined.

The current state already works for me, but just giving a heads up for a future issue.

**Comment by pawelfus** [comment]
Hi @melloc01 

bubble series is one of series that doesn't require sorted data and from [docs](http://api.highcharts.com/highcharts/tooltip.shared): 

> Tooltip texts for series types with ordered data (not pie, scatter, flags etc) will be shown in a single bubble. 

That means no `this.points`, only `this.point` is available for a bubble series.
