### ISSUE TITLE
Polar with Gauge chart in the same page - rendering issue

### ISSUE THREAD

**Issue by melsatar** [highcharts/highcharts#6966]
#### Expected behaviour
<img width="986" alt="screen shot 2017-07-15 at 12 24 17 am" src="https://user-images.githubusercontent.com/1831146/28233203-776b0882-68f5-11e7-837c-d13506262e9c.png">
this is the normal look for spider alone

#### Actual behaviour
![screen shot 2017-07-15 at 12 32 18 am](https://user-images.githubusercontent.com/1831146/28233215-87ffdb1e-68f5-11e7-86ad-6d5fef90bce2.png)

This how it looks when adding spider with gauge in the same page, the main issue with circle gray background

#### Affected browser(s)
This happens specially when you load gauge chart before the spider, while, in case I would like to have a like a popup window with the chart. I did not figure out how to solve the gray background.
Chrome, Safari, FireFox

**Comment by melsatar** [comment]
I found a solution to add this to polar chart pane
```javascript
pane: {
	background: [{
            	backgroundColor: 'white',
            	borderWidth: 0,
       	 }]    	
}
```

**Comment by pawelfus** [comment]
Hi @melsatar 

Thank you for reporting this issue. Could you recreate this in jsFiddle? For me it looks fine: http://jsfiddle.net/t538ng92/

**Comment by KacperMadej** [comment]
Please reopen if needed and the problem is recreated.
