### ISSUE TITLE
Chart height does not reflow if chart.width is set

### ISSUE THREAD

**Issue by cheoalvarez** [highcharts/highcharts#6968]
#### Expected behaviour

If the chart.width is set, the chart height should still reflow when the container is resized or chart.reflow is called

#### Actual behavior

If the chart.width is set, the chart height does not reflow.  

The behavior is as expected in the opposite scenario. If the chart height is set, the chart width _does_ reflow when the container is resized

#### Live demo with steps to reproduce

https://jsfiddle.net/leogdsl/ugu63ah0/12/

#### Affected browser(s)

Chrome, Safari, IE11

**Comment by pawelfus** [comment]
Hi @cheoalvarez 

Thank you for reporting this issue.

**Workaround:**
Instead of `chart.reflow()` use `chart.setSize(undefined, undefined, false);`, demo: https://jsfiddle.net/nmhk053u/
