### ISSUE TITLE
Data is null from boost-canvas.js if series data passed is null instead of [] when webgl is disabled

### ISSUE THREAD

**Issue by ff-sgupta** [highcharts/highcharts#6969]
#### Expected behaviour
Series data null should be handled gracefully

#### Actual behaviour
Disable webgl for the browser and try accessing chart. JS error is raised if data passes is null instead of []

#### Live demo with steps to reproduce
1. Disable webgl for the browser and access https://jsfiddle.net/63u7qtmk/5/
2. Tried on Firefox with webgl disabled from about:config option

#### Affected browser(s)
Should effect any browser when webgl is disabled. I had tried on Firefox

**Comment by sebastianbochan** [comment]
Hi @ff-sgupta 
Please let me know which browser do you use. When I run your demo, in both cases (null and []) the chart is draw without any issues and errors. (Chrome)

**Comment by ff-sgupta** [comment]
Apologies for the missing information. This is reproducible when webgl is disabled for the browser.

**Comment by sebastianbochan** [comment]
Hi @ff-sgupta 
Lets keep all here, I removed the label and set new one. 

**Errors:**
TypeError: data is null
chart is undefined

@cvasseng
