### ISSUE TITLE
Flags look transparent when used with CSS styling

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#6970]
#### Expected behavior
Same look - flags opaque over candlesticks - when switching to [styling via CSS](https://www.highcharts.com/docs/chart-design-and-style/style-by-css).

#### Actual behavior
Flags look transparent
![image](https://user-images.githubusercontent.com/33569/28265759-35421434-6aa6-11e7-9c98-908026e87e6a.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/mnp4pg8k/1/ and switch to http://jsfiddle.net/mnp4pg8k/ for the non-CSS version.

#### Affected browser(s)
Chrome, Firefox

**Comment by sebastianbochan** [comment]
Hi @dandv 
Thank you for the reporting. You can set the white fill for .highcharts-label-box and fix the issue.

Demo:
- http://jsfiddle.net/450fwj6L/
