### ISSUE TITLE
Step line not supported by boost module

### ISSUE THREAD

**Issue by Zeppelin15** [highcharts/highcharts#6976]
Hi, more of an enhancement than a bug.  Currently the boost module does not draw step lines, only normal lines. What is the chances of step-line support being added ? Would really like to use the boost-module in my current project, but due to the nature of the data I need to use a step line.

#### Expected behaviour
Step-line to be drawn

#### Actual behaviour
Normal line drawn

#### Live demo with steps to reproduce
https://jsfiddle.net/25day6or/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting!

@cvasseng
