### ISSUE TITLE
how to set part of legendItem in left and the rest in right?

### ISSUE THREAD

**Issue by tailorsira** [highcharts/highcharts#6977]
#### Expected behaviour
How to set text in the red box place left, and others in right? I set margin-right and float, but both of them are disabled.

#### Actual behaviour
![default](https://user-images.githubusercontent.com/17983274/28311616-cc22ebc0-6be2-11e7-978e-55b1ccf3aec2.png)

#### Live demo with steps to reproduce

![default](https://user-images.githubusercontent.com/17983274/28311787-487777c2-6be3-11e7-868d-270b11d700f9.png)

#### Affected browser(s)
chrome

**Comment by pawelfus** [comment]
Hi @tailorsira 

For questions, please contact with us by email or create a topic on our forum. See the [details](https://www.highcharts.com/support).
