### ISSUE TITLE
How to generate crs for hc-transform

### ISSUE THREAD

**Issue by jonny7** [highcharts/highcharts#6978]
Hi

I'm looking at some guidance on how to build a hc-transform to allow lat/longs on a custom map. I've created my own map using QGis and the guide on Highcharts. All went well. But I'm following this link now: https://www.highcharts.com/docs/maps/latlon

Looking at the sample code:

```
"hc-transform": {
	"default": {
		"crs": "+proj=lcc +lat_1=33 +lat_2=45 +lat_0=39 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"
	},
	"zone2": {
		"crs": "+proj=aea +lat_1=8 +lat_2=18 +lat_0=13 +lon_0=-157 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs",
		"hitZone": {
			"type": "Polygon",
			"coordinates": [[[1747,3900],[3651,2950],[3651,-999],[1747,-999],[1747,3900]]]
		},
		"xpan": 190,
		"ypan": 417,
		"scale": 0.000123090941806
	},
	"zone3": {
		"crs": "+proj=tmerc +lat_0=54 +lon_0=-142 +k=0.9999 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
		"hitZone": {
			"type": "Polygon",
			"coordinates": [[[-999,5188],[-707,5188],[1747,3900],[1747,-999],[-999,-999],[-999,5188]]]
		},
		"xpan": 5,
		"ypan": 357,
		"scale": 5.84397059179e-05,
		"rotation": 0.2618
	}
}
```

Am I right to assume that `zone2` should refer to a particular region of your map. IE, your map might be of New York. But your map is broken into boroughs, so `zone2` could be Brooklyn?

From the article I couldn't tell the best ways to generate the crs for each zone, assuming my statement above is correct?

**Comment by KacperMadej** [comment]
Hi,

This is more of a technical support case than a bug that could be reported here on github. In the future please use support channels: https://www.highcharts.com/support

In the official map collection you should be able to find a map of France with few different `crs` defined - for few islands placed under the continental part of France. GeoJSON for the map: http://code.highcharts.com/mapdata/countries/fr/fr-all.geo.json

To learn how to create such map you could look for a documentation or a tutorial for QGIS editor.

**Comment by jonny7** [comment]
Thanks @KacperMadej  :+1:
