### ISSUE TITLE
'linked' y-axis is not 'linked' when original tickAmount is less than 4

### ISSUE THREAD

**Issue by yazawa-log** [highcharts/highcharts#6979]
#### Expected behaviour
Same y-axis on the both sides

#### Actual behaviour
When tickAmount is 3, y-axis on the left shows 3 values
but linked y-axis on the opposite side shows 5 values.

#### Live demo with steps to reproduce
tickAmount = 4
http://jsfiddle.net/0exmcxqq/

tickAmount = 3
http://jsfiddle.net/0exmcxqq/1/

#### Affected browser(s)
chrome, firefox, and IE

**Comment by pawelfus** [comment]
Hi @yazawa-log,

Thank you for reporting this bug.

**Workaround:**
Use simple `tickPositioner` to make sure ticks are rendered in the same place: http://jsfiddle.net/0exmcxqq/2/

```javascript
    yAxis: [{
        min: 0,
        title: {
            text: 'Total fruit consumption'
        },
        tickAmount: 3
    },{
    	linkedTo:0,
        tickPositioner: function () {
        	return this.linkedParent.tickPositions.slice();
        },
        opposite: true
    }],
```

**Comment by yazawa-log** [comment]
Thank you for the workaround.
I'll try it.
