### ISSUE TITLE
Strange animations on zoom for arearange series type

### ISSUE THREAD

**Issue by simdevmon** [highcharts/highcharts#6984]
#### Expected behaviour
I would expect clean/smooth animations when I zoom in/out of an 'arearange' series type.

#### Actual behaviour
The animation often looks very strange:

![2017-07-20_15h29_00](https://user-images.githubusercontent.com/16277781/28419960-ea0db622-6d60-11e7-9284-4a054db52b16.png)

![2017-07-20_15h30_39](https://user-images.githubusercontent.com/16277781/28419961-eba1d16c-6d60-11e7-950c-d9110bb3a09e.png)

![2017-07-20_15h31_19](https://user-images.githubusercontent.com/16277781/28419962-ecad6b66-6d60-11e7-8b08-4f3a0354dde0.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/simdevmon/s2my775k/1/

It does not happen always, but often enough when zooming twice:

![2017-07-20_15h35_45](https://user-images.githubusercontent.com/16277781/28420085-48d54f1c-6d61-11e7-98f7-035908faea54.png)
![2017-07-20_15h35_57](https://user-images.githubusercontent.com/16277781/28420089-4a0807d0-6d61-11e7-8e6b-ef6d1ba1258a.png)

#### Affected browser(s)
Chrome 59

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting the problem. Please try to create a minimal demo for the issue.

Workaround: disable animation in series options - http://jsfiddle.net/s2my775k/2/

Related to #1841

**Comment by TorsteinHonsi** [comment]
Reliable reproduction - click the _zoom_ button: http://jsfiddle.net/highcharts/s2my775k/4/

**Comment by TorsteinHonsi** [comment]
The fix was to disable animation internally when we're crossing from one data grouping resolution to another.
Demo with the fix applied: http://jsfiddle.net/highcharts/s2my775k/6/
