### ISSUE TITLE
Highcharts documentation gives wrong information for datetime xAxis minRange 

### ISSUE THREAD

**Issue by saicharanp** [highcharts/highcharts#6986]
#### Expected behaviour
minRange has to be set to "36000000" to set maxZoom to one hour.

#### Actual behaviour
documentation says minRange is to be set to "3600000"  to set maxZoom to one hour.

#### Live demo with steps to reproduce

http://jsfiddle.net/zwLhrnwm/1/ 

URL: http://api.highcharts.com/highcharts/xAxis.minRange

**Comment by KacperMadej** [comment]
Hi,

Maybe I missed something, but this doesn't look like a bug in Highcharts.

1 hour in milliseconds is 36e5 (3 600 000) as in API reference.
1 second is 1 000 milliseconds, 1 minute is 60 seconds, 1 hour is 60 minutes.
1 000 * 60 * 60 = 60 000 * 60 = 3 600 000

Your demo is not showing 1 hour - this one with the API value shows: http://jsfiddle.net/zwLhrnwm/2/
