### ISSUE TITLE
TypeError: a.Highcharts.error is not a function

### ISSUE THREAD

**Issue by cotein** [highcharts/highcharts#6987]
Hello everybody:
first, i sorry by my horrible english.
I am working in a project with vue-highcharts but at moment to run display this error (**TypeError: a.Highcharts.error is not a function**) and them nothing!

Someone happened something this?
I hope you can help me.

Bye people and thanks.

**Comment by KacperMadej** [comment]
Hi,

Please use support channels for technical problems. We are trying to keep github for bugs.

https://www.highcharts.com/support
