### ISSUE TITLE
Using colorAxis.dataClasses in styled mode

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6988]
#### Expected behaviour
In styled mode, legend item symbol have the same color as point which fit in a specific value range, determined in colorAxis.dataClasses.

#### Actual behaviour
All legend item symbols are black.

#### Live demos
http://jsfiddle.net/unb06fus/ - classic mode
http://jsfiddle.net/snt2j4qw/ - styled mode

**Comment by KacperMadej** [comment]
**Workaround**: set [colorAxis.dataClassColor](http://api.highcharts.com/highmaps/colorAxis.dataClassColor) to `'category'` and redefine chart colors in CSS if needed. 

Demo: http://jsfiddle.net/7vck7Lkm/

**Comment by TorsteinHonsi** [comment]
In accordance with how color options generally work in styled mode, the expected behaviour is that `color` is ignored and colors should be defined in CSS. See for example how the basic series color option is ignored: http://jsfiddle.net/o4u6oxk4/.
