### ISSUE TITLE
How to center custom label (center text inside svg rect)

### ISSUE THREAD

**Issue by igimenez** [highcharts/highcharts#6990]
#### Expected behaviour
I want to center a text inside a Donut Chart. The chart is displayed on a widget inside a dashboard. Those widgets **can be resizable which means that the radio of the donut chart can change**.  I have seen a lot of fiddles out there that center text, labels, even the chart title inside a donut using fixed positioning. That does not work for me. **So this is not a duplicate.**

What i have done is create a label with a black filling with the same size of the chart. This label has the same width, height and position as the chart. The label is composed of a rect (with dark background just to make it visible) with a text inside (with white color).

When clicking on one of the pie segments the label becomes visible.

My problem is: How do I make the text to be horizontally and vertically centered relative to the rect (which in term would be in the center of the donut)? 

#### Actual behaviour

Text is not centered.

#### Live demo with steps to reproduce

http://jsfiddle.net/gimenez_83/8g9L5e3q/41/

Thanks, thanks, thanks in advance!

**Comment by KacperMadej** [comment]
Hi,

This is not a bug. For technical problems please use support support channels listed here: https://www.highcharts.com/support We are trying to keep github only for bug.

In short: you could adjust position based on the label size and update it's position in chart redraw event.
Demo: http://jsfiddle.net/a9w13b4a/

**Comment by igimenez** [comment]
@KacperMadej sorry!! And a million thanks!! You rock!
