### ISSUE TITLE
Bullet graph "Highcharts.setOptions" affects other charts showing wrong graph

### ISSUE THREAD

**Issue by Rinkuk1993** [highcharts/highcharts#6991]
#### Expected behaviour
say if there are two graphs. One bullet and other activity chart. Any chart say Activity chart if rendered after bullet chart shows completely wrong graph due to Highchart object which is being used by Activity graph.

#### Actual behaviour
Both graph shall be shown correct data.

#### Live demo with steps to reproduce
http://jsfiddle.net/awesomeRk/LdHYt/741/

#### Affected browser(s)
All

Please fix this issue ASAP.

**Comment by KacperMadej** [comment]
Hi,

This is because Highcharts.setOptions is global, so everything works as expected by design. If you do not want those options to be global set them per chart and do not use Highcharts.setOptions or override them in the activity gauge options.
