### ISSUE TITLE
pie dynamic update center and size cause error

### ISSUE THREAD

**Issue by Emily456** [highcharts/highcharts#6992]
![qq 20170721162326](https://user-images.githubusercontent.com/13901696/28455278-1c261caa-6e31-11e7-9a13-fc2608ba9f95.png)

**Comment by KacperMadej** [comment]
Hi,

Please provide a demo in JSFiddle. I am unable to recreate the problem. 
You could edit this working demo: http://jsfiddle.net/sfs66c81/

**Comment by Emily456** [comment]
Hi,

Please check the updated JSFiddle, open the chrome console to see the problem. 
https://jsfiddle.net/sfs66c81/1/

![highchart datalabel rotation](https://user-images.githubusercontent.com/13901696/29301009-170f371e-812e-11e7-8681-5271179e0278.png)

**Comment by TorsteinHonsi** [comment]
Okay, so it's not related to the updating, it still happens with static values: https://jsfiddle.net/highcharts/sfs66c81/2/
