### ISSUE TITLE
[5.0.x] Chart.description does not render in HTML

### ISSUE THREAD

**Issue by aedart** [highcharts/highcharts#6993]
#### Expected behaviour

Description is rendered in HTML (for screen readers) when accessibility module is loaded and the `chart.description` option is set.

#### Actual behaviour

Description is not rendered in HTML.

#### Live demo with steps to reproduce

Your own demo, from the documentation

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/accessibility/accessible-line/

#### Affected browser(s)

Firefox confirmed. Think that this a general bug that affects all browsers

**Comment by KacperMadej** [comment]
Hi,

The description is included by default as a long description of the chart.
I have tested Firefox and Chrome on Win10 - both are working correctly.
![a11y-fine](https://user-images.githubusercontent.com/8960408/28460004-5085fb26-6e10-11e7-8a58-fb938dd1c341.jpg)

Please provide more details and/or browser + OS information, so we could recreate the problem.

**Comment by aedart** [comment]
Hi again

Ty for the quick replay - and yes, this was a mistake on my part. Was apparently a bit too hasty when reviewing the generated source code. I'm sorry for the trouble.
