### ISSUE TITLE
esc key should exit chart when using modules/accessibility.js

### ISSUE THREAD

**Issue by primerano** [highcharts/highcharts#6996]
#### Expected behaviour

When tabbing through a chart or map a user needs a way to exit the HC object without going to the beginning or end of the series.

Ideally the esc key would allow users to go up a level so they can move past the chart/map

More notes here..  https://forum.highcharts.com/highcharts-usage/how-do-i-escape-a-map-or-chart-using-keyboard-navigation-t39386/

#### Actual behaviour

there appears to be no way to jump out of a series

#### Live demo with steps to reproduce

https://www.highcharts.com/samples/highcharts/accessibility/accessible-line/

tab in..  only escape is tabbing to end or beginning of series.

#### Affected browser(s)
all

**Comment by KacperMadej** [comment]
Hi,

Thank you for the suggestion.

*Internal note:* @oysteinmoseng

**Comment by primerano** [comment]
a better option might be to use tab to exit the chart and use arrow keys when in a visualization..  This is what google is doing on maps

https://support.google.com/maps/answer/6396990?co=GENIE.Platform%3DDesktop&hl=en
