### ISSUE TITLE
Exporting nested categories doesn't work

### ISSUE THREAD

**Issue by vgvassilev** [highcharts/highcharts#6997]
#### Live demo with steps to reproduce

https://jsfiddle.net/12rgcy11/9/

If one clicks on export to any kind of file the output seems garbled.

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi,

While loading Highcharts in Styled mode please load exporting in styled mode too. Additionally - you have already loaded Highcharts - in left panel and in HTML window, load them only one. The plugin is also loaded twice - load it once after Highcharts are loaded. 
A demo with the fix: https://jsfiddle.net/12rgcy11/13/

If you have you have technical problems and are unsure if a case is a bug, please contact technical support first. For more issues with a plugin please file a bug report in the plugin repository.
https://www.highcharts.com/support
