### ISSUE TITLE
Firefox browser incorrectly renders min/max if height is below certain no. of pixel (IE Edge does not have this bug)

### ISSUE THREAD

**Issue by josephedwardchang** [highcharts/highcharts#6998]
#### Expected behaviour
using yAxis: min/max: set to 0/1 (digital values) the highchart should render 0-1

#### Actual behaviour
highchart renders 0-1.75 

#### Live demo with steps to reproduce

http://jsfiddle.net/0xk22bww/

#### Affected browser(s)
only in firefox browser (IE Edge renders OK, no other browser has been tested)

background of the problem: I needed to cram several digital charts into 1 big chart so that I needed around max height of 55px for these digital charts. the live demo shows charts: height of 55px which renders wrong the yAxis 0-1.75 on firefox browser (Edge is ok, though). but when using chart: height of 65px, chart renders correctly the yAxis 0-1

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting the problem.

Font in Firefox (at least on Win10) is bigger than in Chrome (no problem there), so this might be why the ticks are placed differently. To have better control over the ticks you could use tickPositioner or tickPositions.
Demo: http://jsfiddle.net/0xk22bww/1/

**Comment by josephedwardchang** [comment]
thank you sir!
