### ISSUE TITLE
xAxsis min and max options don't work (xrange chart)

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#6999]
#### Live demo with steps to reproduce
http://jsfiddle.net/ejmf/L5yuL6z4/1/

**Comment by LaniMoo** [comment]
This is still an issue with x-range charts. Demo: http://jsfiddle.net/lanimelrok/5qbn1bst/1/

I've posted this issue on the forums as well: https://forum.highcharts.com/highcharts-usage/y-axis-and-x-axis-padding-on-xrange-chart-t39722/

**Comment by pawelfus** [comment]
Hi @LaniMoo 

The original demo posted by @kamilkulig works fine. Your demo doesn't have extremes set so it's not related to the issue. 

To answer your question from our forum: disable `pointPlacement` and set `pointRange: 1`, demo: http://jsfiddle.net/5qbn1bst/3/

**Comment by LaniMoo** [comment]
Ah, my mistake. Thanks so much, Pawel!
