### ISSUE TITLE
not is correct the format date

### ISSUE THREAD

**Issue by anjamago** [highcharts/highcharts#7002]
Hello, I have problems with the date is not being well parciada the date calendar if conicide with the taken but the time of the sample is very different this does not match and I do not know how to do so that this is what I am going

#### Live demo with steps to reproduce
 template: https://jsfiddle.net/anjamago/15ghxkkf/1/

**Comment by KacperMadej** [comment]
Hi,

This is not a bug. In the future please use any other [support channel](https://www.highcharts.com/support), because we are trying to keep github for bugs.

This date format is not parsed correctly by default, so you should parse it yourself. Demo: https://jsfiddle.net/jLyhjrjs/
