### ISSUE TITLE
null point data when clicking on point with drilldown

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#7005]
Looks like a regression of #3383

#### Expected behaviour
Point data is not null

#### Live demo with steps to reproduce
copied from #3383
>No drilldown: http://jsfiddle.net/2ho4wewo/
Drilldown: http://jsfiddle.net/97nma53g/

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem. I am unable to find a version in which the problem wasn't visible, so until that code version is found this is not a regression - if you have any more info, please share.

You could use drilldown event of a chart to get the point before it's destroyed. 
API reference: http://api.highcharts.com/highcharts/chart.events.drilldown
Demo: http://jsfiddle.net/97nma53g/2/

**Comment by alvarezguille** [comment]
Thanks for the quick answer!
I based my thought on the [comment on the original issue](https://github.com/highcharts/highcharts/issues/3383#issuecomment-53396418) stating that it was fixed before closing the issue
> Fixed in the master branch

Regression or not I think it's still not the expected behavior.

**Comment by TorsteinHonsi** [comment]
The point is already destroyed at the time the click event triggers, so we can't access its properties. This happens before the drilldown module's click handler is [added before](https://github.com/highcharts/highcharts/blob/v5.0.13/js/modules/drilldown.src.js#L906-L912) the handler that's added in the options.

If we decide to fix this, we need to change the order so the drilldown happens last, and preferably be able to cancel the drilldown from the click event.

#### Workaround
You can use the `chart.events.drilldown` event to access the point before it is destroyed: http://jsfiddle.net/97nma53g/3/
