### ISSUE TITLE
Chart with multiple xAxes and series displays wrong xAxes on drilldown

### ISSUE THREAD

**Issue by schneckentempo** [highcharts/highcharts#7008]
#### Expected behaviour
If there are multiple Series and multiple x axes which are assigned specifically via http://api.highcharts.com/highcharts/series%3Ccolumn%3E.xAxis, I would expect to have only one x axis on the drilldownseries

#### Actual behaviour
Currently on drilldown the drilldownseries + the second normal series get displayed. Also the axis from this series is applied

#### Live demo with steps to reproduce

http://jsfiddle.net/tgh79f4k/

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

Another demo: http://jsfiddle.net/2bphkhke/
