### ISSUE TITLE
rangeSelector labels misaligned

### ISSUE THREAD

**Issue by Lohkay** [highcharts/highcharts#7011]
#### Expected behaviour
rangeselector labels/buttons/inputs align correctly

#### Actual behaviour
![image](https://user-images.githubusercontent.com/14282367/28629984-03313d28-71f7-11e7-98ab-33f749286bf6.png)

Not sure why but the label/buttons/inputs don't align correctly on one of my charts. I've tried resizing, reflow, redraw, different configuration options, nothing seems to change this behavior. The rest of the chart behaves correctly.

#### Live demo with steps to reproduce
This is the only chart doing this and I can't reproduce it.

#### Affected browser(s)
chrome

**Comment by sebastianbochan** [comment]
Hi @Lohkay,
Thank you for reporting, but when I run our demos, the problem is unreproducible. Do you use any external CSS, js scripts or bootstrap ?

**Comment by Lohkay** [comment]
Without any changes on my side, the issue was resolved with the 5.0.13 update.

**Comment by sebastianbochan** [comment]
Thank you for the feedback.
