### ISSUE TITLE
Pie Chart off set when combined with Bar chart

### ISSUE THREAD

**Issue by garybrain** [highcharts/highcharts#7012]
Version : Highcharts 5.0.13

#### Expected behaviour
When using a combined pie chart and bar graph the pie chart is correctly located.

#### Actual behaviour
When using a 3d bar chart the pie chart labels are in the correct location but the pie chart is offset.

#### Live demo with steps to reproduce
Pie chart correct non 3d : http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/combo/

Pie offset using 3D. http://jsfiddle.net/4rj9Lw8p/

#### Affected browser(s)
Chrome, firefox, IE

**Comment by Izothep** [comment]
Hi Gary,

Thank you for posting information about your issue. It looks to be related with the topic below:
https://github.com/highcharts/highcharts/issues/6972

Some small changes in our code caused the issue of translating series in 3D chart. We will look into this problem as soon as possible.

**Comment by TorsteinHonsi** [comment]
Fails since v5.0.11. I think (but I'm not sure) that this is the offending commit: 6f842539a.
