### ISSUE TITLE
[HighChart.net] Formatter issue

### ISSUE THREAD

**Issue by DaDark** [highcharts/highcharts#7013]
#### Expected behaviour
When I set a formatter property with my own js function, it is well interpreted at js code execution. 

#### Actual behaviour
If I declare a var of type string with a value inside my js function, I've got a js error (method call not supported  by the object).

#### Steps to reproduce
Here is a sample of a formatter's content : 
`highStockContainer.XAxis[0].Labels.Formatter = "function() { return this.value + \" blablabla\"; }" `
highStockContainer is type of Highsoft.Web.Mvc.Stocks.Highstock

In the view, if I look at the MvcHtmlString when I call
`Html.Highsoft().Highstock(Model.HighStockModel.HighStockContainer, "div_stockChart");`
I see the following result
`"formatter":"function() { return this.value + \" blablabla\"; }"` 
and not 
`"formatter":function() { return this.value + \" blablabla\"; }` 
That's why there is an error at js execution.

#### Affected browser(s)
Tested on Chrome and IE11

**Comment by KacperMadej** [comment]
Hi,

Thank you for explaining the problem.

Function set by it's name and defined in JS as in [this demo](http://dotnet.highcharts.com/Highcharts/Demo/Gallery?demo=LineAjax&theme=default) is supported and works fine, but with the structure you have explained - I am no sure. This issue will be forwarded to our .NET developer.
