### ISSUE TITLE
Can the export-data module export point names for Scatter plots ?

### ISSUE THREAD

**Issue by conormaxwell** [highcharts/highcharts#7017]
Thankyou for the export-data module; it’s very useful.

Is it possible to add point names to the csv export data for Scatter plots ?  In my case the point names are countries, and the exported data is not useful without them.

Also the exported column headings for scatter plots (and maps) don’t seem to be quite right.

Expected behaviour:
CSV data from Scatter plot :
"Births Attended by Skilled Personnel (Percentage (%))"," Maternal Mortality Ratio (per 100,000 women)"
"Ethiopia",16,353
"South Sudan",19,789
"Sudan",23,856
"Chad",23,311
"Niger",29,553
"Somalia",33,732
etc
or the point name could be in the 3rd column if that is easier or more consistent.

Actual behaviour :
CSV data from Scatter plot :
"Births Attended by Skilled Personnel (Percentage (%))","Births Attended by Skilled Personnel v Maternal Mortality Ratio"
16,353
19,789
23,856
23,311
29,553
33,732
etc

Thankyou

**Comment by KacperMadej** [comment]
Hi,

**In general:**
For questions please use other [support channels](https://www.highcharts.com/support) as we are trying to keep github for bugs.

**For your problem:**
If you are using category type axis, then points with names will be exported. Demo: https://jsfiddle.net/wtbmL4fv/

If not than you could define [keys](http://api.highcharts.com/highcharts/series%3Cpie%3E.keys) and all keys should be exported. Demo: https://jsfiddle.net/wtbmL4fv/1/
