### ISSUE TITLE
Animation not working in responsive mode

### ISSUE THREAD

**Issue by ashish-developer-php** [highcharts/highcharts#7020]
Animation doesn't seem to work in responsive mode. If I set animation duration for series in plotOptions without using responsive properties then it works but if I set animation duration value for series in plotOptions with some responsive rule then animation doesn't work. Any idea guys?

**Comment by TorsteinHonsi** [comment]
Hi,

It does work here: http://jsfiddle.net/7joy6u5v/

You may be using an older version. The current version is 5.0.13. In 5.0.12 setting the animation didn't work correctly.

**Comment by TorsteinHonsi** [comment]
Closing this as already fixed, please reopen if necessary.
