### ISSUE TITLE
Bars and Columns not aligned correctly when categories are implied by point data

### ISSUE THREAD

**Issue by melloc01** [highcharts/highcharts#7022]
I'll be glad if anyone can spot my error if it's mine. Thanks in advance :smile: 

#### Expected behaviour
SVG data representation to be aligned with label.

#### Actual behaviour
Not aligned.

#### Live demo with steps to reproduce
http://jsfiddle.net/qabyfzdn/1/

#### Affected browser(s)
Browser agnostic.

**Comment by sebastianbochan** [comment]
The issue is related with fact, that Highcharts reserves space for all series, also when contains zero/null points.

The solution is disable grouping by the parameter.

Demo:
- http://jsfiddle.net/4t8uk2s9/
