### ISSUE TITLE
Unable to render a chart in a child of a detached node

### ISSUE THREAD

**Issue by natalan** [highcharts/highcharts#7024]
@TorsteinHonsi there is another regression since https://github.com/highcharts/highcharts/commit/5800b1b626149ca7518c7b09b336125a946b0b9a:

`chart.renderTo` node is getting removed from a parent container and never put back to the original location after "pre-rendering" and removal [here](https://github.com/highcharts/highcharts/blob/c92a4d6618f26358d75516c89c8f1489bf54a957/js/parts/Chart.js#L892) 

It was working as expected in 5.0.12 and broken in 5.0.13 and 5.0.14

#### Live demo with steps to reproduce
http://jsfiddle.net/45mt97xs/

**Comment by sebastianbochan** [comment]
Hi @natalan 
Thank you for the reporting.
