### ISSUE TITLE
treemap with colorAxis(heatmap) in styled mode - all nodes get the same color

### ISSUE THREAD

**Issue by hjalmers** [highcharts/highcharts#7025]
#### Expected behaviour
Each node should get it's own color following the rules defined in colorAxis, like in this [example](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/treemap-coloraxis).

#### Actual behaviour
All nodes have the same color (see live example below).

#### Live demo with steps to reproduce
http://jsfiddle.net/hjalmers/n54cwvo7/

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @hjalmers 
Thank you for the reporting.

**Comment by DiegoCardoso** [comment]
Hi!

Any plans to fix this on HC 5?

**Comment by pawelfus** [comment]
Hi @DiegoCardoso 

You can check the commit and apply fix in v5: 264455c984d2d2d914df75870d6444b063de3a26
