### ISSUE TITLE
The width style for vertical axis labels appears not to be respected

### ISSUE THREAD

**Issue by matt-hoskins** [highcharts/highcharts#7028]
#### Expected behaviour

When the label style on the vertical axis is set with both a width and whiteSpace set to "nowrap" I would expect the width to be respected and ellipsis to be shown.

#### Actual behaviour

The width style isn't respected when whiteSpace is set to "nowrap" - instead the labels behave as if no width were set (the label area grows). This also affects scatter charts with "inverted" set to true.

#### Live demo with steps to reproduce
I forked another fiddle with a simple bar chart and just adjusted the label style to demonstrate:

http://jsfiddle.net/8m10utq5/2/

If you remove the whiteSpace style then the labels wrap ok on the vertical axis to respect autosizing of the axis and plot areas - but not the specific size in the width style - if you make the whole chart wider they don't wrap to the size.

Alternatively if you change the chart type to scatter so the label axis is the horizontal one then you get ellipsis - although I still don't think the width is respected.

#### Affected browser(s)
Firefox, Chrome

Note: I've editing this comment as I realise, from a bit more testing, that I thought the sizing was being respected in some circumstances but actually that was just highcharts autosizing of the axis label area applying wrapping. 

I guess this may not be a bug if the width style has never been intended to work on axis labels!

**Comment by matt-hoskins** [comment]
On the off-chance I just tried specifically setting the textOverflow style on the labels to "ellipsis" and that made it work:
http://jsfiddle.net/8m10utq5/3/

I now realise, from the documentation, that the default style on the label doesn't have textOverflow set. However the documentation for style seems to imply that you only need to deliberately set textOverflow to 'none' to prevent ellipsis...

http://api.highcharts.com/highcharts/xAxis.labels.style

"CSS styles for the label. Use whiteSpace: 'nowrap' to prevent wrapping of category labels. Use textOverflow: 'none' to prevent ellipsis (dots)."

So I guess this is maybe a change in the defaulting behaviour for vertical axis labels and handling overflow - possibly just needs the documentation for the axis labels style to make it clear that textOverflow needs setting to "ellipsis" if you want it to use the combination of nowrap and a width.

**Comment by matt-hoskins** [comment]
Looking through Axis.js I guess it would be a case of maybe either factoring the label style width into the calculations for getSlotWidth (for vertical axis use the labels style width if set rather than the marginLeft as long as it's not greater than any set marginLeft) or maybe renderUnsquish. I don't know enough about the inner workings of highcharts really to be sure though :).

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

Like you have found already - ellipsis set for textOverflow will help slightly.

_Internal note:_ width on second run of axis labels is wrong, because it's based on slot width and set label is ignored. 

As a **workaround** you could set merginLeft to a required label width + 20 (for chart margin and axis labels padding).
Demo: http://jsfiddle.net/sferxawy/

**Comment by matt-hoskins** [comment]
Thanks Kacper - thanks for the suggestion of the workaround :). I'd figured out that workaround myself a little while after submitting this issue - and it does indeed do the job with my actual charts and datasets.

**Comment by TorsteinHonsi** [comment]
@KacperMadej Can you suggest a fix for this issue?
