### ISSUE TITLE
Export highcharts.scss file, please !

### ISSUE THREAD

**Issue by aedart** [highcharts/highcharts#7030]
Hi

While it is nice that your bundle does include the `highcharts.css`, it would be really nice to be able to use your `highcharts.scss`, instead of having to manually copy it from your git.

The reason why it is a very good idea for you to start exporting this, is so that developers are able to just include it directly into their "master" scss file, as a bundle from which their can overwrite just the few properties that they need to.

**Comment by KacperMadej** [comment]
Hi,

Thank you for posting your enhancement suggestion.

Just to make sure that all info is here:
* you are referring to NPM package,
* the files you have are the same as on the highcharts-dist repo https://github.com/highcharts/highcharts-dist,
* adding the [.scss](https://github.com/highcharts/highcharts/blob/master/css/highcharts.scss) in [here](https://github.com/highcharts/highcharts-dist/tree/master/css) is requested.

**Comment by aedart** [comment]
Hi KacperMadej

Yes, I am using `npm` for obtaining highcharts. Furthermore, I am creating my own custom bundle, where highcharts' "source" Javascript is just a small part of it.

Furthermore, I am also using `.scss` files, e.g. bootstrap, which I'm also building to a single file.
It would be great if you could include your scss file. It does not have to be to the `css` folder. Just where ever you find it to make the most sense.

**Comment by TorsteinHonsi** [comment]
Thanks, that makes sense. Should be published to the zip file and the shim repos.
