### ISSUE TITLE
Cannot setup Highcharts 5+ with a custom window

### ISSUE THREAD

**Issue by AamuLumi** [highcharts/highcharts#7031]
Hi ! 

I'm using Highcharts to make some server generated charts. Currently, I work with the Highcharts 4.2.6, but due to #5926, I need to work with at least the 5.0.3.

In version 4, Highcharts had the possibility to setup a custom _window_ (created for example with JSDom). In the last version, I cannot setup the custom _window_ because it is erased by the global object _window_. Here are the first lines of **highcharts.src.js** :

```js
'use strict';
(function(root, factory) {
    if (typeof module === 'object' && module.exports) {
        module.exports = root.document ?
            factory(root) :
            factory;
    } else {
        root.Highcharts = factory(root);
    }
}(typeof window !== 'undefined' ? window : this, function(win) {
    var Highcharts = (function() {
        /**
         * (c) 2010-2017 Torstein Honsi
         *
         * License: www.highcharts.com/license
         */
        /* global window */
        var win = window, // Custom window is erased
            doc = win.document;
```

I tested by removing the _var win = window_ line, and it worked.
The problem is I need this to be in the current npm package.

I know these lines come from the [Globals.js file](https://github.com/highcharts/highcharts/blob/master/js/parts/Globals.js) and the problematic line is used for front-end generation.

Is there a possibility to solve this for back-end development ?

Thanks a lot for all your job. :)

**Comment by KacperMadej** [comment]
@TorsteinHonsi  It's hard to see why `win` is provided as an argument and immediately a new variable of the same name is created basically erasing the argument value. Is there a reason or it's a bug?

**Comment by AamuLumi** [comment]
Thanks for the fix ! :)
