### ISSUE TITLE
Exporting complex PDF line charts with large amounts of data via exportChartLocal generates a PDF file correctly displayed in Google Chrome but wrongly in Acrobat Reader

### ISSUE THREAD

**Issue by mtubis** [highcharts/highcharts#7032]
#### Expected behaviour
Exported PDFs are displaed the same way in webbrowser like Google Chrome and PDF readers direct (Acrobat Reader version 17.009.20044.25828, Evince 3.10.3)

#### Actual behaviour
Exporting complex PDF line charts with large amounts of data via exportChartLocal generates a PDF file correctly displayed in Google Chrome but wrongly in Acrobat Reader (blank site with communicate that PDF is corrupted) oder other readers like Evince.

#### Live demo with steps to reproduce
https://github.com/mtubis/higcharts-issue
PDF with errors: https://github.com/mtubis/higcharts-issue/blob/master/Kesselleistung.pdf
Most important point in the code: https://github.com/mtubis/higcharts-issue/blob/master/em_report.js 
und code direct: 
export: function (report_item_id, export_type, export_name) {
            // Subtract 49 from chart height (44 for the navigator plus 5 margin):
            var chart = $('#' + report_item_id).highcharts();
            chart.exportChartLocal({
                filename: export_name,
                sourceHeight: chart.chartHeight - 49,
                sourceWidth: chart.chartWidth,
                type: export_type
            });
        },

#### Affected browser(s)
Acrobat Reader, Evince

**Comment by sebastianbochan** [comment]
Hi @mtubis,
Could you send us a chart configuration including data, which casues the problem? From your code I was not able to extract static data for the further debugging.

**Comment by mtubis** [comment]
Hi,
sorry I am answering so late but this highcharts module is only part of huge application with a lot of ajax request. 
It is quite difficult to prepare working static version of this but I have managed to export final config data from life app. 
You can find chart configuration here: https://github.com/mtubis/higcharts-issue/blob/master/chart_configuration/exported_chart_configuration.json
And PDF exported from this configuration here: https://github.com/mtubis/higcharts-issue/blob/master/chart_configuration/result_pdf_from_given_config.pdf

Please let me know if this is enough?

**Comment by TorsteinHonsi** [comment]
I took your configuration, tried to extract the relevant parts, and set up this fiddle: http://jsfiddle.net/highcharts/v55hq5qt/

Use the burger menu to export to PDF. In this case the result looks the same in Adobe Reader as in Chrome. Can you change anything to make sure the issue appears?

**Comment by mtubis** [comment]
Hi,
sorry I am answering so late again.

I have finally manage to prepare static example that generate the problem.

I hope this will help:
https://jsfiddle.net/mtubis/y9tgzz2v/11/

**Comment by prdatur** [comment]
Hello,

I took our ticket from mtubis and I saw she had provided all wanted infos.
Any chance you get in touch with it again?

best regards,
Christian

**Comment by pawelfus** [comment]
Thanks for the heads up! Yes, I was able to reproduce the problem: Chrome v63.0.3239.108 and AR v2018.009.20050

**Comment by pawelfus** [comment]
@prdatur 

After further investigation found the reason:

> "gridLineWidth": true,

This property should be set as Number: https://api.highcharts.com/highcharts/yAxis.gridLineWidth - it works in other readers because `true` can be casted to `1`, but it looks like Acrobat Reader needs exact types.
