### ISSUE TITLE
Bubble series: marker loosing stroke if only select state lineColor is set

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7034]
#### Behaviour
In bubble series type: marker loosing stroke options if only select state lineColor is set

#### Live demo with steps to reproduce
http://jsfiddle.net/jdrhowbt/
1. Select and deselect a point
2. Stroke is not visible and the marker has `stroke="rgba(NaN,NaN,NaN,NaN)"`

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
It's probably the use of 'red' in combination with animation that is the problem. Using hex colors it works: http://jsfiddle.net/highcharts/jdrhowbt/1/
