### ISSUE TITLE
Stacked Area with stacking: 'percentage' renders the chart differently than when calculating the percentage manually

### ISSUE THREAD

**Issue by kloppnr1** [highcharts/highcharts#7037]
#### Expected behaviour

I have a stacked area chart which series of numeric values. I use stacking: 'percentage' to have HighChart calculate the percentage distribution. This seems to be handled correctly: http://jsfiddle.net/n5Lzh3jo/

#### Actual behaviour

When i instead use the same numeric data and calculates the percentage manually and set that percentage in the series, then it visually gets rendered differently. Ex. negative values are only rendered as points but the area are not rendered: http://jsfiddle.net/ya1e5L88/4/

It could be related to this issue: https://github.com/highcharts/highcharts/issues/5671

**Comment by KacperMadej** [comment]
Hi @kloppnr1,

Both demos are identical - please correct at least one of the demos to show the problem.

**Comment by kloppnr1** [comment]
Sorry...

Please try:
http://jsfiddle.net/n5Lzh3jo/1/
http://jsfiddle.net/ya1e5L88/4/

**Comment by KacperMadej** [comment]
Please explain how do you expect negative values for percentage stacking to be displayed? For normal column stacking negative values are stacked under a chart, and for percentage stacking full stack has 100% and negative values are deducted from positive total. Demo: http://jsfiddle.net/n5Lzh3jo/2/ The same is done for area chart: http://jsfiddle.net/n5Lzh3jo/3/

The demo with normal stacking you have posted doesn't look good - is there a problem with it? If yes, please provide more info.

**Comment by kloppnr1** [comment]
I have resolved the issue. It was related to series not having datapoints for certain dates: resolved by adding datapoints with value as zero.
Secondly i changed the way i calculate the percentage when data has negative values. Then i get the same result as using stacking: 'percentage'
