### ISSUE TITLE
Adding a line series after chart creation is not animated

### ISSUE THREAD

**Issue by justcim** [highcharts/highcharts#7039]
#### Behaviour
When adding a line series after chart creation, it is not animated when using the highstock library, but works fine when using the highcharts library.

#### Live demo with steps to reproduce
I have tracked the issue down to starting with version 5.0.5 of highstock.

Demo with version 5.0.4 which works as expected: https://jsfiddle.net/k1Lvo5yL/
Demo with version 5.0.5 where addition of line series is not animated: https://jsfiddle.net/k1Lvo5yL/1/
Demo against current version where addition of line series is not animated: https://jsfiddle.net/k1Lvo5yL/2/

1. Click the button to add a line series, which will be animated in version 5.0.4, but is not animated in later versions.
2. Click the button to add a column series, which is animated correctly in all versions.

#### Affected browser(s)
Chrome, IE 11

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting the problem.

Offending commit https://github.com/highcharts/highcharts/commit/0a92202

However, this how animation works in Highstock for new series.
A hacky workaround that will work if you are not loading highcharts-more is to set chart.polar to true. 
Demo: https://jsfiddle.net/k1Lvo5yL/3/
