### ISSUE TITLE
Lack of spacing between navigator and plotArea using highcharts-custom.js

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7040]
#### Expected behaviour
Highstock should reserve space for navigator and scrollbar

#### Actual behaviour
Using highcharts-custom.js (from download builder https://www.highcharts.com/download) Highstock is not reserving space for navigator and scrollbar. Because of that xAxis labels overlap scrollbar

#### steps to reproduce

Download highcharts-custom with all possible parts and use it in demo below:
http://jsfiddle.net/yd31wn7u/4/

![screen shot 2017-08-04 at 15 18 29](https://user-images.githubusercontent.com/15050812/28970271-3719d09a-7928-11e7-8f28-d189d28ab83c.png)

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard Are you able to detect any differences between the custom build and the distributed files?

**Comment by jon-a-nygaard** [comment]
I am actually not able to get the custom download to work properly. It is giving me the following result:
```javascript
console.log('Sorry, nothing to download here. Please return to http://highcharts.com/download and make a new configuration.');
```
So I will likely have to investigate this issue first.
