### ISSUE TITLE
Highcharts numberFormat broken with a very small values

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#7042]
#### Expected behaviour
`Highcharts.numberFormat(100 * 5.372111214729405e-9, 2)` should return `0.00%`

#### Actual behaviour
`Highcharts.numberFormat(100 * 5.372111214729405e-9, 2)` returns `5.37e-7%`

#### Live demo with steps to reproduce
- 5.0.13+: http://jsfiddle.net/9s6398gt/
- 5.0.12: http://jsfiddle.net/9s6398gt/1/

*Note:*
It's a regression after ad892cb

**Comment by Izothep** [comment]
+1
