### ISSUE TITLE
[Question] dual charts on the same chart

### ISSUE THREAD

**Issue by MarcMagnin** [highcharts/highcharts#7043]
Thanks for Highcharts!
I would like to know if such thing is possible withing the same chart:
![image](https://user-images.githubusercontent.com/725667/29034222-de4aaa80-7b97-11e7-9232-45e6a05003de.png)
Basically: Top part containing some series and bottom part containing others but reversed.
Many thanks.

**Comment by sebastianbochan** [comment]
Hi @MarcMagnin,
The github is our bug tracker, so for general [support](http://www.highcharts.com/support) questions, please use email / stackoverflow or forum.

PS. yes it is possible by arearange series type. 

- https://www.highcharts.com/demo/arearange
