### ISSUE TITLE
Draws below yAxis.min with offset axis for HC 5.0.12+

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#7044]
#### Expected behaviour

Should not draw below the specified axis min.

#### Actual behaviour

It does.  But this only started happening from 5.0.12 on; for 5.0.11 it was as expected.

#### Live demo with steps to reproduce

http://jsfiddle.net/n04Lzhrf/

With 5.0.12, a line is drawn below the axis min of 0.  But note that it is only the line, and not the markers:

![bad](https://user-images.githubusercontent.com/9009792/29066113-30c16022-7c26-11e7-8b92-0c6517ef7bc2.JPG)

Change the highcharts version down a notch to 5.0.11 and nothing is drawn below the min:

![good](https://user-images.githubusercontent.com/9009792/29066152-4874af94-7c26-11e7-9c73-190b18ff6fa6.JPG)

I need the behaviour to be as per 5.0.11 because I have data below the min that I don't want to be displayed.  It's fine without an offset axis, because you can't see that data anyway, but with an offset axis the data becomes visible.  I'm not sure if this change was deliberate, but if it was then what is the workaround to achieve the same behaviour as before?  (*EDIT*: see my further comments below)

I should add that in my "real" code it does sometimes happen that the line is *not* drawn below the min, even in 5.0.12 and with an offset axis.  But I can't (yet) find a way to reproduce that in this simplified demo.  It is when I change the scaling of the features in my real case, but I'm not yet sure how that translates across into this simplified case.  If I work it out I'll update this because it may provide some further insight.

#### Affected browser(s)

Probably all.

**Comment by drmrbrewer** [comment]
Aaargh I see that this behaviour change was intentional:

![changelog](https://user-images.githubusercontent.com/9009792/29066964-cac09682-7c28-11e7-90bf-4b95dddffe0b.JPG)

See [issue 3160](https://github.com/highcharts/highcharts/issues/3160).

To me, this change is counter-intuitive and wrong.  I can see why this was done in order to fix the particular problem in issue 3160 (to avoid clipping of a line along the axis min) but it doesn't seem right to be drawing stuff that is out of bounds, and in particular below what is stated as being the axis min.

I'd consider a line running along the axis min to be *in bounds* and it should be drawn in full without clipping, but a line that goes out of bounds should *not* be drawn.

In my case I'm offsetting the xAxis in order to draw another adhoc feature in the gap that is opened up and I do *not* want the chart features spilling over into it.

**Comment by drmrbrewer** [comment]
@TorsteinHonsi to demonstrate how the solution of 3160 is not really very elegant, all I've done with your fiddle is change the lineWidth to 20:

http://jsfiddle.net/3ydauoo8/

So there is still clipping, because I didn't remember to update the axis offset.  To fix it, I would have to keep offsetting the axis further and further??  Like so:

http://jsfiddle.net/3ydauoo8/1/

And since the data is dynamic, and changes all the time, in the next update it looks like:

http://jsfiddle.net/3ydauoo8/2/

So there is an ugly gap for no reason.  The solution?  To have some complicated check to see where the data lies and to determine whether an axis offset is actually required, and if so then how much? 

This doesn't seem very elegant.  And it means that data that is genuinely out of the chart bounds (and which should not be plotted, like in my case) is plotted.

It doesn't seem to me that the axis offset should be used in this way to fix the problem of issue 3160.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting the problem.

Simplified demo showing the problem without using offset - yAxis height is set and plot is visible outside of axis while it shouldn't: http://jsfiddle.net/wbyf9ujs/

**Comment by drmrbrewer** [comment]
@KacperMadej so hopefully you will be able to go back to the previous behaviour, or at least allow this to be achieved in some way?

To continue with my previous discussion about why using `offset` to adjust the clip area of the chart (for 5.0.12+) is really not logical, let's consider clipping at the top end... which is just as valid a consideration as clipping at the bottom end:

http://jsfiddle.net/oc8L9vwz/

In the above, the line is clipped at the top just like it is clipped at the bottom (i.e. like issue 3160 but at both ends).  There is no logical difference between these two problems, and yet the "fix" implemented for issue 3160 (to enable the clipping area to be extended at the bottom end via `xAxis.offset`) is not available at the top end... there is no way of offsetting the upper gridline like there is for offsetting the x axis.

So it seems that issue 3160 should be solved in a different way (i.e. not via `xAxis.offset`), and that the clipping behaviour should otherwise revert back to what it was.

Maybe this exposes some wider questions, because from your example it seems like the vertical clipping range is (always has been?) defined at the bottom by the **non-offset** x axis at the bottom (and not yAxis.min)?

**Comment by KacperMadej** [comment]
As a workaround you could use Highstock - it supports multiple panes, that's why it works there. Also, [height](http://api.highcharts.com/highstock/yAxis.height) for axis is only a part of Highstock, so sorry for the confusion.
Demo: http://jsfiddle.net/n04Lzhrf/2/

I could prepare a workaround / wrapper for Highcharts that would bring back the previous chart behavior. Would you like me to prepare it?

**Comment by drmrbrewer** [comment]
I'd prefer to stick with highcharts.  It seems that with the previous behaviour it did not treat `yAxis.min` as the cut-off for drawing, but rather it is the outermost gridline.  For example, consider the following:

http://jsfiddle.net/nc32p98v/

In the above (using 5.0.11), `yAxis.min` is set to -1 and yet the line is drawn down to -30.  This is apparently because the lowest gridline is now at -100, so instead anything below -100 is now cut off:

http://jsfiddle.net/n1xgjgbm/

So, that is the behaviour which I need to retain from highcharts 5.0.11 and which was destroyed by the change to fix issue 3160... it still seems to me that the change implemented in 5.0.12 should be reversed, and issue 3160 fixed in a different way.... in a way that will work both at the top and at the bottom:

http://jsfiddle.net/wesc2ova/

I note that in the above jsfiddle, although the **line** is cut in half, the **marker is not**.  So to fix issue 3160 why can't you just alter the behaviour to draw the whole width of the line, just like you already draw the whole width of the marker?  i.e. completely independent of `xAxis.offset`?  Yes it would extend slightly outside the chart area, but the marker *already does* and if this matters then `xAxis.offset` can be used.

**Comment by TorsteinHonsi** [comment]
@drmrbrewer I totally follow your thoughts on the [20px line problem](http://jsfiddle.net/3ydauoo8/2/). Just keep in mind that this is offered as a workaround for a problem that (a few) users have encountered for years. And consider our three alternatives:

1. Clip the line along the plot area, like we did previously, and we still do by default. But some users were not happy with that.
2. Draw it along the edge of the cartesian plane, but do not clip it. Obviously not a good approach, as it would cover up the X axis labels.
3. Alter the behaviour to draw the whole width of the line, just like we already draw the whole width of the marker. Would work nicely for lines running along the 0 plane, but once it dips below, it would look strange.
4. What we did: Provide an option to offset the cartesian plane. And note it's an option, not a default.

Now I agree with you that number 3 may be a good alternative, though we need to check that it doesn't break anything else. For example, the markers are not clipped, they are just skipped when centered outside the plot area. So when altering the clipping area itself, it will affect areas, column chart etc. I was about to check this option, and I found that we already offered this as a workaround earlier. Check out this interesting user reaction:

<img width="644" alt="skjermbilde 2017-08-10 kl 10 01 56" src="https://user-images.githubusercontent.com/227836/29160610-39a1d03a-7db3-11e7-96ff-2705fd50aa5a.png">


Do you remember why you turned this proposal down? It is basically the same as you proposed above.

**Comment by drmrbrewer** [comment]
@TorsteinHonsi isn't your (2) the same as my (3)?

And when you say:

> Obviously not a good approach, as it would cover up the X axis labels

why is that?  At present, the marker is not clipped, so if the user chooses to have a massive marker, then my view is that they would expect the marker to stray over the edge of the chart.  To me this looks fine.  The marker is still *centred* within the chart, so it "looks right".  If a visible marker was centred outside the chart, that wouldn't look right.

Here is an example (in 5.0.11) where we have wide markers and a wide line:

http://jsfiddle.net/ujxo4hjm/

I think this looks fine, except that the full width of the line should just be shown, as per the marker.  The user must expect some overlap with the labels when using such fat features.  Of course that is extreme; a more realistic example is:

http://jsfiddle.net/nn5wp8v5/

So there is no overlap with the labels... that is only a theoretical possibility in an extreme situation (where the user must expect overlap).

And merely showing the full width of the line (like for the marker) would fix the problem both at the bottom end and the top end, where clipping of the line presently also occurs.

As for my reaction to the workaround on the other issue, doesn't that workaround suggest altering the clipping of the whole chart area?  To me the clipping should be control per feature, which it seems to be in 5.0.11... the marker is not clipped at the same height as the line, so clipping is controlled for each feature separately... you don't want other content to become visible just because you're expanding the chart clipping to account for a fat line... you just alter the clipping associated with the line?  Sorry if I'm misunderstanding what's possible.

**Comment by drmrbrewer** [comment]
@TorsteinHonsi what is the latest on this one?

**Comment by TorsteinHonsi** [comment]
I reverted the "fix" for #3160. Turned out to be a dead end.
