### ISSUE TITLE
Black fill color when defining hover color using rgb or rgba values

### ISSUE THREAD

**Issue by mhoyer** [highcharts/highcharts#7045]
Hi,

#### Actual behaviour

the issue appeared after update from 5.0.12 to 5.0.13 (as we actually trusted in semantic versioning). We are relying on this configuration option to set a different color with `plotOptions/column/states/hover` to show a semi transparent color on top of the actual gradient column fill color.

Since v5.0.13 we experience a black fill color with a style value set to `rgb(NaN, NaN, NaN)` in DOM explorer when hovering.

#### Expected behaviour

It should be possible to define a gradient color for the 2D bar charts **and** a semitransparent solid color for the hover state using `rgb()` or `rgba()` strings.

#### Live demo with steps to reproduce

I prepared a simplified demo here: https://jsfiddle.net/zt4xm146/ If you enable the `showBug` option in the 1st line you can simulate the issue by hovering the column bars. 

The problem is - as far as we figured out: when using `rgb()` or `rgba()` string values for this option it results in that black filling.

Furthermore, try to replace the `<script>` tag in the HTML section to use 5.0.12 version of highcharts:
```<script src="https://code.highcharts.com/5.0.12/highcharts.js"></script>```

Now the bug toggle variable `showBug` does not effect in terms of black filling on hover.

#### Affected browser(s)

Seen on Chrome, FF and IE.

### Side note

I think this issue might be related to this new _"Added color animation on state change for non-marker based series like columns and tree maps"_ feature I saw in the [changelog for v5.0.13](https://www.highcharts.com/documentation/changelog).

Plus, I wonder why such "features" show up in a patch version? ;-)

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

The issue is already resolved on master branch - next release candidate.

Demo: http://jsfiddle.net/kts34nhh/

**Comment by KacperMadej** [comment]
The issue seems to be resolved through commit: https://github.com/highcharts/highcharts/commit/a66aa7863099ae4929098c86283fbaf1311f3d5f, so this problem is related to the #7034

**Comment by AkibMankad** [comment]
Hi @KacperMadej , 

I am experiencing same issue mentioned by @mhoyer,  a black fill color with a style value set to rgb(NaN, NaN, NaN) in DOM explorer when hovering.

What could be solution for this? I am using Highcharts version 8.2.2.

**Comment by KacperMadej** [comment]
@AkibMankad I am unable to recreate the problem - could you edit the below demo (or link a new one) to show the issue?
https://jsfiddle.net/BlackLabel/s32fzy0q/
