### ISSUE TITLE
`minPointLength` doesn't work for zero value columns when all other columns have negative values

### ISSUE THREAD

**Issue by hon2a** [highcharts/highcharts#7046]
#### Expected behaviour

When I create a bar/column chart with a single series that has only zero and negative values and set `minPointLength` to a positive value, the zero value bars/columns should show up with the height set in `minPointLength`.

#### Actual behaviour

The zero value bars/columns don't show up.

If at least one of the values is positive, however, it works as expected.

#### Live demo with steps to reproduce

See the [demo](http://jsfiddle.net/hon2a/4j1zgegw/1/).

#### Affected browser(s)

All.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the bug.

_Internal note:_ This is caused by minPointLength showing only as a positive value - see here: http://jsfiddle.net/4j1zgegw/2/

**Comment by KacperMadej** [comment]
Regression due to https://github.com/highcharts/highcharts/commit/b91477777e1aacd4685430b682b02708d643cd10.
The logic for the fix of this issue was relaying on `series.dataMax` being calculated only for visible range.
Demo: http://jsfiddle.net/4j1zgegw/3/

**Comment by Sphinxxxx** [comment]
Not sure whether this is the same issue, but it shows the same behavior as the OP's demo: If the column chart has **only negative** values, nothing is rendered until you force a refresh, e.g. by resizing the window or hiding one of the series:

http://jsfiddle.net/dpnv7g2m/

**Comment by hon2a** [comment]
@Sphinxxxx: That's something different (and much more critical), so you should create a separate thread for it. This issue is concerned with the zero-value column rendering upwards (outside plot area) when used with non-zero `minPointLength` and when all other columns have negative values.

**Comment by Sphinxxxx** [comment]
@hon2a Thanks, new issue here: https://github.com/highcharts/highcharts/issues/7228

**Comment by hon2a** [comment]
@KacperMadej: @TorsteinHonsi: I'm closing this as it seems to be working in `6.0.1`.
