### ISSUE TITLE
dataGroupInfo.start doesn't always indicate the index of the first element passed to custom approximation function

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7051]
**Example:** https://jsfiddle.net/kkulig/zfou3kcu/

There're 2 series in this chart: the blue one is core 'sum' approximation, the black one is the same functionality achieved by using the custom function. As you can see - series are not the same. They should be.

console.log() examines only to the first data group and prints out three variables: 
1. `dataGroupingInfo`
2. `rawData` - array created by using information from `dataGroupInfo` (starts at the first element of the original data (index 0))
3. `data` - array passed as an argument to the function (starts at the second element of the original data (index 1))

**First** data group passed as an argument to the custom approximation function starts at index 1 from the original data (point at index 0 from the raw data is omitted by grouping algorithm - probably, because it's Sunday and it's not enough to form the first group). However `dataGroupInfo.star`t equals to 0 (which is misleading, because this point is not included in the data passed as an argument). `rawData` is created by using `dataGroupingInfo` - that's why it has inappropriate values. `dataGroupInfo.start` should equal to 1 for the first group.

Second group has proper value of  `dataGroupInfo.start`

Code based on the example from the API: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/series-datagrouping-approximation (http://api.highcharts.com/highstock/plotOptions.series.dataGrouping.approximation)

**Comment by pawelfus** [comment]
Note: Actually both series are wrong:
- build-in data grouping does not consider first point at all
- custom data grouping approximation includes in the first package point that is outside the range

Resulting chart should have four (!) data points (for dates: 15th, 22nd, 29th and 5th). First point (`1313964000000`) is actually `21 of Aug at 22:00 UTC`. That means we should create a separate grouped point for this date.
