### ISSUE TITLE
Odd Value in Gauge's Max key sets different value in output

### ISSUE THREAD

**Issue by kailashvele** [highcharts/highcharts#7052]
#### Expected behaviour
Max value should be what is provided.

#### Actual behaviour
Even after making endOnTick: false when an odd value is passed like 250 the output shows 320, if 5 output is 6, if 300 output is 400

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/gauge-solid/
This is the demo provided and can see value passed to RPM graph for max is 5 but output is 6

**Comment by kailashvele** [comment]
Thank You, Removing `tickAmount`  did solve the problem but the gauge shows `0`, `25`, `50`, `75` and `100%` mark which I do not want to show. Is there anyway to not have them I just want start value and end value.

Also I think it will be great if it can be mentioned in the `min` `max` value document.

**Comment by KacperMadej** [comment]
@kailashvele Yes, to have only start and end value you could use the code in the demo from my previous comment - set `tickPositions`.

**Comment by kailashvele** [comment]
@KacperMadej Oh Yes. Thank You.
