### ISSUE TITLE
Rotation for data labels of levels in TreeMap does not work

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#7053]
#### Expected behaviour
Rotation for data labels of levels in TreeMap chart should work correctly.

#### Actual behaviour
The rotation for data labels of levels in TreeMap chart does not work correctly. Some labels disappear while others are not positioned correctly.

#### Live demo with steps to reproduce
http://jsfiddle.net/2t6abgpc/

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

rotation + align (left or right) = the issue.
Demo: http://jsfiddle.net/2t6abgpc/2/
