### ISSUE TITLE
Export CSV should probably strip markup from category and series names etc

### ISSUE THREAD

**Issue by matt-hoskins** [highcharts/highcharts#7055]
#### Expected behaviour
When using the export data module I would expect the column headers and category names to have markup stripped (and "unescape" processing done for &lt; and &gt;) from the Download CSV.

#### Actual behaviour
Markup is not stripped - so e.g. bold markup or `&gt;` references are left as-is. Such markup is fine left in the "view data table" and "Download XLS" options as both are effectively HTML, so the markup gets rendered, but it probably makes sense to detect and strip markup (and unescape `&lt;` and `&gt;`) in category and series names etc so that in the csv they are just unstyled plain text versions of what you see as the labels on the chart (for consistency).

#### Live demo with steps to reproduce
http://jsfiddle.net/cqjvD/1524/

I used the example fiddle from the export module, but have added in some markup on a couple of category labels and the series label. I've also changed the preview to set the CSV as text on a pre tag (to better represent how it looks when loaded into excel/openoffice/etc

If you click on "Download CSV" and open the results in e.g. LibreOffice or Excel then you can see that the markup comes through as-is.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.

This looks like a good enhancement suggestion.

**Comment by TorsteinHonsi** [comment]
Just for the records - using markup in series names and categories should ideally be avoided in the first place. If special formatting is needed, it should be added in format strings, formatter callbacks or style settings.

**Comment by matt-hoskins** [comment]
Yeah - I'm not actually using markup in the names/categories at the moment in my application, it's the lack of unescaping of `&lt;` and `&gt;` that was more the issue for me. I'm escape processing user-provided labels before they're passed to the charting to prevent the users from putting anything tag-like in labels and that being processed as a tag. However having realised that `&lt;` would just come through as-is for the CSV download I figured I'd test markup as well (as markup is allowed of course, even if it's ideally avoided) and include that in the example.
