### ISSUE TITLE
Tooltips stay open when moving the mouse over multiple sparklines with left mouse button pressed

### ISSUE THREAD

**Issue by maximal** [highcharts/highcharts#7056]
When you press left mouse button and (whilst holding the button) move the pointer around multiple sparkline charts, you get all the charts with open tooltips.

#### Expected behaviour

Tooltips do not stay open.

#### Actual behaviour

Tooltips stay open.

#### Live demo with steps to reproduce

https://www.highcharts.com/demo/sparkline

See the video:
![Mouse button pressed over sparklines](https://user-images.githubusercontent.com/980679/29221126-47973928-7ec6-11e7-8241-01016ed78ff1.gif)

(Here, I moved the mouse without any button pressed, it worked just fine.
Then, I moved the mouse with left button pressed, all tooltips popped out.
Then, I moved the mouse without any button pressed one more time, all tooltips cleared again.)

#### Affected browsers

* Chromium, version 59.0.3071.109, Built on Ubuntu, running on Ubuntu 17.04, 64-bit;
* Google Chrome, version 60.0.3112.90 (Official Build), running on MacOS Sierra (v10.12.6), 64-bit.

**Comment by pawelfus** [comment]
Hi @maximal 

Thank you for reporting this bug.

*Internal note:*
It's a regression from #d39445b
