### ISSUE TITLE
Title text set to 0 (as number) won't render

### ISSUE THREAD

**Issue by ming-codes** [highcharts/highcharts#7059]
#### Expected behaviour

Expect number can be rendered just as text.

#### Actual behaviour

Number 0 is treated as falsy and title not rendered at all.

#### Live demo with steps to reproduce
http://jsfiddle.net/LLExL/7901/

**Comment by pawelfus** [comment]
Hi @ming-codes 

Thank you for the report. It's a problem with falsy values, the same issue with `false`: http://jsfiddle.net/LLExL/7902/

I'm not sure if it's a bug, `tooltip.text` should be `String`, not number: [docs](http://api.highcharts.com/highcharts/title.text). On the other hand, it's probably an easy fix.

**Comment by ming-codes** [comment]
We have a feature that uses the title to display stats. It can be zero sometimes. Since other numbers displays just fine, the behavior should be consistent.

I do have another request though. If text expects string, can we just call toString on it to convert to a string? This gives greater flexibility on the interface.

**Comment by KacperMadej** [comment]
This sound like a good enhancement suggestion. 

As a workaround you could cast the value to string before using it in chart options. Demo: http://jsfiddle.net/LLExL/7901/
