### ISSUE TITLE
Line is missing after zoom

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#7061]
#### Expected behaviour
Line should be visible

#### Actual behaviour
Line is missing, when zooming between points.

#### Live demo with steps to reproduce
Demo:
 - http://jsfiddle.net/f5dyor4L/ 5.0.9 -> works
 - http://jsfiddle.net/md3dL7ae/ 5.0.10+ -> does not work

![zooming](https://user-images.githubusercontent.com/2115686/29355677-3c9ae56a-8272-11e7-978a-d3828d013739.gif)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Regression after a6c5ecf

**Comment by TorsteinHonsi** [comment]
In my opinion, #6203 was a mistake. The extremes should take into account the first point outside the visible range just for this reason. I'll revert the fix and write a test for it.

**Comment by sebastianbochan** [comment]
I agree with that, it is a reason of fix.
