### ISSUE TITLE
Problem with the legend after using the setData method in bar chart

### ISSUE THREAD

**Issue by AnatolyPruchay** [highcharts/highcharts#7062]
Greetings! After using the setData method, the legend of the first column of the bar chart applies to all columns. 
And when you hide the other columns, then under them a column of the same color as the first

https://jsfiddle.net/Pierre_Cardi/7wqrrd8h/2/

Could you tell me how to solve this issue?

**Comment by pawelfus** [comment]
Hi @AnatolyPruchay 

This is not a bug, this is the expected result of `setData()` with multiple points ([docs](http://api.highcharts.com/highcharts/Series.setData)). As I asked before, in case of problems, please contact with our support.
