### ISSUE TITLE
Chart drawing leads to browser crashing (IE 11)

### ISSUE THREAD

**Issue by mamoo** [highcharts/highcharts#7063]
#### Expected behaviour
Chart should be displayed.

#### Actual behaviour
Browser crashes.
Chart initialization goes fine up until the painting phase, where the Browser crashes.
We've been able to consistently reproduce the error on different machines, and we've pin-pointed the chart that is causing issues (several charts are drawn in the page and by disabling only a specific one the page works).

#### Live demo with steps to reproduce
We have a package with all the files to reproduce the issue but no live demo, please let us know how we can provide it.

#### Affected browser(s)
Tested on Internet Explorer 11 v11.0.44 on Windows 8.1

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.

Please contact support - e.g. by e-mail - and send us the files needed to recreate the problem: https://www.highcharts.com/support

**Comment by mamoo** [comment]
Sent. 
Thank you very much in advance.
