### ISSUE TITLE
The file you are trying to open is in a different format than specified by the file extension

### ISSUE THREAD

**Issue by unknown-githubber** [highcharts/highcharts#7064]
#### Expected behaviour
When I export a chart in **XLS** format, the file should be opened without any error

#### Actual behaviour
When I open the **XLS** file, I get an error saying that the file has a different format than the extension specified by the file. This error DOESN'T happen when I export the file in **CSV** format.
[![1](https://user-images.githubusercontent.com/31068984/29364056-91824436-8292-11e7-8d4f-80dd0d74b840.PNG)](https://jsfiddle.net/pscjzhe4)
![2](https://user-images.githubusercontent.com/31068984/29363972-45c113b0-8292-11e7-836c-f2b2d40b015b.PNG)

#### Live demo with steps to reproduce
https://jsfiddle.net/pscjzhe4

#### Affected browser
Chrome

#### Affected Office version
Excel 2007

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting. You are using a community made / third party plugin that has it's own repository - you could report bugs or problem with the plugin there.

The plugin issues: https://github.com/A----/highcharts-export-clientside/issues
The plugin in the repository: https://www.highcharts.com/plugin-registry/single/37/highcharts-export-clientside

**Comment by unknown-githubber** [comment]
Thanks for your response.
I created an issue in their repository
https://github.com/A----/highcharts-export-clientside/issues/45

**Comment by simonberger** [comment]
This problem is part of the integrated csv/xls export module. It is really annoying these days and can only be fixed through using a more extended excel writer that produces a valid xls(x) file.
This bug should be opened again or decided to not be closed because of no priority.

**Comment by TorsteinHonsi** [comment]
The original post applies to a third party plugin, not our own export-data module. Can you demonstrate this issue with our own demos?

**Comment by simonberger** [comment]
@TorsteinHonsi 
Alright from the screenshots it looked to me to be the same and the code producing the problem has been shared between those projects anyway.
I opened a new bug #7977.

In a fork of the old export module of highcharts versions 4 and older I also fixed a CSV export bug. I hope I remember to create a issue / pull request here the next days.
