### ISSUE TITLE
Issue with mouseup event in multiple iframes

### ISSUE THREAD

**Issue by rrdnd** [highcharts/highcharts#7066]
#### Problem
It seems like the mouseup event is not being set for the owner document when H.chartCount is not 1, which causes the mouse to get stuck in a dragging state.
This happens when rendering multiple charts in different iframes (one chart per iframe), as each iframe has its own document.

In the code, look for this line:
```
if (H.chartCount === 1) {
    addEvent(
        ownerDoc,
        'mouseup',
        pointer.onDocumentMouseUp
    );
}
```
When creating the second chart, ```H.chartCount``` will be different from 1.

#### How to test
In the fiddle, click on the contents of both charts. In one of them (possibly the second chart), the mouse is going to remain in the dragging state.

#### Live demo with steps to reproduce
The fiddle doesn't work properly on Firefox, preferably use Chrome.
http://jsfiddle.net/rredondo/9t3trpta/

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
Probably we need to replace the whole `H.chartCount` idea with a chart count for each document, like `ownerDoc.hcChartCount`.
