### ISSUE TITLE
chart.update() doesn't enable the navigator under certain conditions

### ISSUE THREAD

**Issue by ransoing** [highcharts/highcharts#7067]
#### Expected behaviour

Calling `chart.update()` to toggle `navigator.enabled` should always work properly.

#### Actual behaviour

If a plot is initialized with both `scrollbar.enabled` and `navigator.enabled` set to `false`, then the navigator will not appear when `chart.update( {navigator: {enabled:true}} )` is called.

If the plot is initialized with either `scrollbar.enabled` or `navigator.enabled` set to `true`, then it will work properly.

#### Live demo with steps to reproduce
Press the "Toggle Navigators" button. Note how the second plot does not show a navigator.
http://jsfiddle.net/x40me94t/1/

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the bug.

_Internalnote:_ Navigator is added only on `beforeRender` event and cannot be added through `chart.update`.

**Comment by sebastianbochan** [comment]
_Internal note_
It seems that options are not "updated" in update function. However when we edit it, it is still wrong.

Demo:
- http://jsfiddle.net/rrLzatcv/

**Comment by KacperMadej** [comment]
**Workaround:** 
Set options for navigator manually, fire event that adds navigator/scrollbar, redraw the chart to see the changes. 
Demo: http://jsfiddle.net/x40me94t/2/

**Comment by cosycode** [comment]
_Internal note_
Requires unit test (scheduled for test/move_issues_tests_hs4.0.1)
