### ISSUE TITLE
Chart becomes unresponsive when you zoom below minutes

### ISSUE THREAD

**Issue by slawekkolodziej** [highcharts/highcharts#707]
1. Open this demo: http://jsfiddle.net/hfrntt/QPCDq
2. Zoom to 10 Nov, there are two points for this day
3. You should notice that when you zoom below minutes, chart becomes unresponsive for a while.

**Comment by oysteinmoseng** [comment]
Can't reproduce this in latest, so closing for now. http://jsfiddle.net/QPCDq/5/
