### ISSUE TITLE
Disabling sticky tracking breaks point hovering with Boost

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#7073]
#### Expected behaviour
Points should be hoverable with stickyTracking disabled

#### Actual behaviour
stickyTracking = false doesn't allow points to be hovered 

#### Live demo with steps to reproduce
With sticky tracking points can be hovered and there is no tooltip, with sticky tracking enabled point hovering is allowed.

https://jsfiddle.net/gncj66xd/

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.

**Comment by KacperMadej** [comment]
Closing as a duplicate in favor of a newer and better commented https://github.com/highcharts/highcharts/issues/9882
