### ISSUE TITLE
Vertical axis html label (long text) problem when ellipsis is turned off

### ISSUE THREAD

**Issue by amalyushko** [highcharts/highcharts#7074]
Hello guys,

I want to prevent ellipsis for HTML labels in vertical axis for a chart (for example, for _bar_  chart). I set settings as it described in docs (_Use textOverflow: 'none' to prevent ellipsis (dots)._). But, I suppose, it works a bit incorrect - http://jsfiddle.net/kw34jb9b/2/.

And it works ok when I set `useHTML: false` - http://jsfiddle.net/kw34jb9b/4/. This behavior would be good in my case.

But, unfortunately, I need HTML labels and I cannot set fixed width for my labels because texts can be different and I cannot decrease font size.
Is it possible to fix it? Or maybe some workaround?
And one more question: is it possible prevent overlapping when the ellipsis is turned off? May be automatically increase a width of labels area or increase the distance between series?

Thanks! 

P.S. I understand how it's hard to implement flexible solution for this problem because there are **a lot of cases**, so, guys, sorry in advance)

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.
