### ISSUE TITLE
Chart is not loaded correctly when adding series with zIndex option

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7075]
#### Expected behaviour
All series should be added to the chart correctly even when zIndex for navigator's base series is set.

#### Actual behaviour
When zIndex is set for navigator's base series, second series after base series is not loaded correctly to the chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/rnhcn1tc/4/

Bug looks to be introduced in 5.0.13 Highcharts version.

**Comment by TorsteinHonsi** [comment]
Fails since 15aad0d79.

**Comment by oysteinmoseng** [comment]
@Izothep This works now, correct? Or am I missing something?

**Comment by Izothep** [comment]
Hi Oystein! Yes, it looks that this bug is already solved since Highstock 6.0.0 release
