### ISSUE TITLE
Create Webjar that contains all modules

### ISSUE THREAD

**Issue by jcrosetto** [highcharts/highcharts#7079]
Could you please create a webjar (webjars.org) that contains everything in https://github.com/highcharts/highcharts-dist? (highcharts, highstocks, and highmaps)

Currently there are webjars for Highcharts and Highstocks but not Highmaps.

**Comment by sebastianbochan** [comment]
Thank you for suggestion.

@jon-a-nygaard

**Comment by alvarezguille** [comment]
Almost created a duplicate for this.

This could be fixed by including `license.txt` in `highcharts-dist` repo and having a valid license definition in `bower.json` as specified in https://github.com/bower/spec/blob/master/json.md#license

After that webjar generation in www.webjars.org should work

**Comment by Artur-** [comment]
As far as I understand, the PRs which copy the license URL from `package.json` to  `bower.json` should enable creating webjars using webjars.org:
* https://github.com/highcharts/highcharts-dist/pull/12
* https://github.com/highcharts/highstock-release/pull/7
* https://github.com/highcharts/highmaps-release/pull/4

**Comment by Artur-** [comment]
Actually the PRs do not resolve the issue. Seems like webjars.org only accept some given licenses listed at the end of https://bintray.com/docs/api/: 

"Available licenses:
AFL-2.1, AFL-3.0, AGPL-V3, Apache-1.0, Apache-1.1, Apache-2.0, APL-1.0, APSL-2.0, Artistic-License-2.0, Attribution, Bouncy-Castle, BSD, BSD 2-Clause, BSD 3-Clause, BSL-1.0, CA-TOSL-1.1, CC0-1.0, CDDL-1.0, Codehaus, CPAL-1.0, CPL-1.0, CPOL-1.02, CUAOFFICE-1.0, Day, Day-Addendum, ECL2, Eiffel-2.0, Entessa-1.0, EPL-1.0, EUDATAGRID, EUPL-1.1, Fair, Facebook-Platform, Frameworx-1.0, Go, GPL-2.0, GPL-2.0+CE, GPL-3.0, Historical, HSQLDB, IBMPL-1.0, ImageMagick, IPAFont-1.0, ISC, IU-Extreme-1.1.1, JA-SIG, JSON, JTidy, LGPL-2.1, LGPL-3.0, Libpng, LPPL-1.0, Lucent-1.02, MirOS, MIT, Motosoto-0.9.1, Mozilla-1.1, MPL-2.0, MS-PL, MS-RL, Multics, NASA-1.3, NAUMEN, Nethack, Nokia-1.0a, NOSL-3.0, NTP, NUnit-2.6.3, NUnit-Test-Adapter-2.6.3, OCLC-2.0, Openfont-1.1, Opengroup, OpenSSL, OSL-3.0, PHP-3.0, PostgreSQL, Public Domain, Public Domain - SUN, PythonPL, PythonSoftFoundation, QTPL-1.0, Real-1.0, RicohPL, RPL-1.5, Scala, SimPL-2.0, Sleepycat, SUNPublic-1.0, Sybase-1.0, TMate, Unlicense, UoI-NCSA, VIM License, VovidaPL-1.0, W3C, WTFPL, wxWindows, Xnet, ZLIB, ZPL-2.0"
