### ISSUE TITLE
Rotated labels + shadow throws JS exception

### ISSUE THREAD

**Issue by cristiscu** [highcharts/highcharts#7080]
#### Expected behaviour
chart rendered

#### Actual behaviour
chart not rendered (JavaScript exception).

You have to comment out either the shadow line, or the rotation line. With both there, you get a JavaScript exception and the chart is not rendered.

#### Live demo with steps to reproduce

Take your own fiddle from http://api.highcharts.com/highcharts/plotOptions.column.dataLabels.rotation and add a shadow (with background). My changed fiddle here: http://jsfiddle.net/cristiscu/89gesbqk/

#### Affected browser(s)
all

PS: reported first on the forum: https://forum.highcharts.com/topic39528/

**Comment by sebastianbochan** [comment]
Hi @cristiscu
Thank you for the reporting.

**Comment by TorsteinHonsi** [comment]
The commit above takes care of the error, but the background, border and shadow still doesn't apply to rotated labels.
