### ISSUE TITLE
Inconsistency between Highcharts and Highstock: xAxis line below / above the columns (zIndex dimension)

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7082]
#### Expected behaviour

These two fiddle's have exactly the same code except the first one is created using highcharts script and the second using highstock:
**Highcharts:** https://jsfiddle.net/gthk2fn4/1/
**Highstock:** https://jsfiddle.net/gthk2fn4/2/

These two charts should look the same.

#### Actual behaviour
In Highcharts the xAxis line lays above the columns (zIndex dimension). In Highstock it's below them.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the inconsistency.

**Workaround:**
use offset for xAxis:
- https://jsfiddle.net/gthk2fn4/4/
- https://jsfiddle.net/gthk2fn4/3/

**Comment by ppotaczek** [comment]
Duplicated: #8031
