### ISSUE TITLE
Highstock: column animation shown columns outside of set pane

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7083]
#### Expected behaviour
Clip columns like line series and animate within series' pane.

#### Actual behaviour
Columns are animating outside of set pane.

#### Live demo with steps to reproduce
http://jsfiddle.net/jspyvzop/

**Comment by KacperMadej** [comment]
This could be resolved like:
1. Wrapper in Highstock like in this demo: http://jsfiddle.net/d461t7fo/
However, it looks like this would require `import`ing `'./ColumnSeries.js'` into `StockChart.js` part, so force the dependency on `ColumnSeries.js` part for any Highsock custom builds.

2. Adding a similar, but shorter `if` in the Highcharts core under [this `ColumnSeries.js` line](https://github.com/highcharts/highcharts/blob/6da435aa8c87567da63048c62e45963f6ccbccdf/js/parts/ColumnSeries.js#L745).
```
				if (series.clipBox) {
					series.setClip();
				}
```

@TorsteinHonsi Which approach is better in this case? and in cases like that?

**Comment by KacperMadej** [comment]
No. 2 seems better.
@TorsteinHonsi Bump.

**Comment by TorsteinHonsi** [comment]
Seems okay, but there are some tests breaking...
