### ISSUE TITLE
High/non ASCII characters in csv file are not displayed correctly when exporting from IE

### ISSUE THREAD

**Issue by brannislav** [highcharts/highcharts#7084]
When exporting High\non ASCII characters (for example "哈哈ôéàÜ의 사용") to CSV using client side export from IE 11 the characters are not displayed correctly (in the case of the example above they appear as "å“ˆå“ˆÃ´Ã©Ã Ãœì˜ ì‚¬ìš©").

The issue is that when creating the blob from the csv content the BOM has to be prepended to the content.

https://github.com/highcharts/highcharts/blob/6da435aa8c87567da63048c62e45963f6ccbccdf/js/modules/export-data.src.js#L291

Possible fix would be:

`blobObject = new win.Blob(["\uFEFF" + content], {type: 'text/csv'})`

Setting the type is optional but a good practice.
This is already done for all other browsers here:

https://github.com/highcharts/highcharts/blob/6da435aa8c87567da63048c62e45963f6ccbccdf/js/modules/export-data.src.js#L319

but since IE uses other API it has to be done for IE separately.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting and proving the solution.

**Comment by brannislav** [comment]
I reproduce the issue using Microsoft Excell 2016 (adding screenshot).
![csv export opened with excell](https://user-images.githubusercontent.com/24313515/29569882-8050e1fc-875d-11e7-8d60-6648340e13d9.png)

Indeed using Notepad or Notepad++ works fine as they are not affected by the missing BOM.

However I still think that not having the BOM is an issue and will affect some applications (like MS Office). Also the exported files should be consistent regardless of the browser used and currently all other browser export csv with BOM.

Thanks,
Brani

**Comment by brannislav** [comment]
@TorsteinHonsi , I'm not sure why are you closing this issue as I have sent you steps to reproduce and justification why this is an issue.

**Comment by brannislav** [comment]
Thanks, for providing a fix @TorsteinHonsi !

**Comment by TorsteinHonsi** [comment]
Thanks for suggesting the actual fix 👍
