### ISSUE TITLE
highcharts-gantt.src.js isn't working

### ISSUE THREAD

**Issue by amramL** [highcharts/highcharts#7085]
https://github.highcharts.com/gantt/highcharts-gantt.src.js repository isn't working,
where can i download the highcharts-gantt.src.js file?

**Comment by sebastianbochan** [comment]
Hi @amramL,
Thank you for reporting.

@jon-a-nygaard

**Comment by TorsteinHonsi** [comment]
It may have to do with some reorganizing I did on the gantt branch yesterday. Will have a look, but I have to split right now.

**Comment by TorsteinHonsi** [comment]
Okay @jon-a-nygaard I couldn't find the problem...

**Comment by amramL** [comment]
Since yesterday i can't see any of my gantt charts, so i want to download the highcharts-gantt.src.js file to call it from my server instead of make this "<script src="https://github.highcharts.com/gantt/highcharts-gantt.src.js"></script>", but when i went to the repository i couldn't even find the "gantt" folder, and in my browser appears this:

![image](https://user-images.githubusercontent.com/31217214/29568282-79ffc96e-8715-11e7-9c00-f82761a25ef4.png)

**Comment by TorsteinHonsi** [comment]
Please keep in mind that _github.highcharts.com_ should never be used in production.

**Comment by TorsteinHonsi** [comment]
You can download the last working file from https://github.highcharts.com/e64e8de83a59e63514ff889f352bda6e01a6ec3b/highcharts-gantt.src.js

**Comment by amramL** [comment]
@TorsteinHonsi i know, i'm still developing xD 
thank you for the file!!

**Comment by pawelfus** [comment]
Works now.
