### ISSUE TITLE
tickmarkPlacement 'between' not working

### ISSUE THREAD

**Issue by ashok5a5** [highcharts/highcharts#7086]
I have been trying to get column chart for hourly data but I am unable to get tickmarkPlacement 'between'. Below is the xAxis values I am giving

xAxis: {
            		type:'datetime',
            		tickInterval:3600 * 1000,
			tickmarkPlacement: 'between'
            }

**Comment by pawelfus** [comment]
Hi @ashok5a5 

`tickmarkPlacement` works only for categorized axis, not for datetime/linear/logarithmic axis. From [docs](http://api.highcharts.com/highcharts/xAxis.tickmarkPlacement):

> For categorized axes only. If on the tick mark is placed in the center of the category, if between the tick mark is placed between categories. The default is between if the tickInterval is 1, else on. Defaults to null.
