### ISSUE TITLE
error when installing using npm 

### ISSUE THREAD

**Issue by donomron** [highcharts/highcharts#7087]
I'm trying to install highcharts using npm:
`npm i highcharts --save`
#### Expected behaviour
Should be installed with no errors

#### Actual behaviour
Can not install, console these errors:
`deprecated CSSselect@0.7.0: the module is now available as 'css-select'`
`deprecated CSSwhat@0.4.7: the module is now available as 'css-what'`

#### Environment
node version: 6.11.2
npm version: 5.3.0

#### Recommendation
I think I need to install a version of highcharts that uses `CSSselect` and `CSSwhat` but I don't know which specific version I should use

**Comment by pawelfus** [comment]
Hi @donomron

Are you sure it comes from Highcharts? Just tried, no errors:

```
github7087 $ sudo npm i highcharts --save
github7087@1.0.0 /Users/pawelfus/projects/projects/github7087
└── highcharts@5.0.14 

npm WARN github7087@1.0.0 No description
npm WARN github7087@1.0.0 No repository field.
```

Env:
npm: 4.2.0
node: v7.10.0

**Comment by donomron** [comment]
hmm, maybe it has to do something with npm version. let my downgrade my npm and try again

**Comment by pawelfus** [comment]
Thank you. Note: we don't use mentioned packages (`CSSselect` and `CSSwhat`). Not directly at least ([our package](https://github.com/highcharts/highcharts/blob/master/package.json)).

**Comment by donomron** [comment]
I installed npm v5.2.0 and it solved my problem, thanks. Though I still get the warning of `CSSselect ` and `CSSwhat`.

> Note: we don't use mentioned packages (CSSselect and CSSwhat)

Yeah, could be a dependency of other packages. I wonder why would anybody change the npm package name! :)
