### ISSUE TITLE
Boost module: series doesn't hide

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7088]
#### Expected behaviour
After clicking series legend item, corresponding series should be hidden.

#### Actual behavior

After the click series image remains on the plot area, but it's impossible to interact with it (e.g. via mouse hover). Chart behaves like if the clicked series was hidden (except visible plot).

Without boost module hiding mechanism works fine.

#### Live demo with steps to reproduce
http://jsfiddle.net/kkulig/korazrj2/

Click on the 'Series 1' legend item. 

#### Additional info
Each series contains 13000+ data points.

**Comment by kamilkulig** [comment]
Workaround: update series with an empty object on _hide_ event:

`    plotOptions: {
        series: {
            events: {
                hide: function () {
			this.update({});
                }
            }
        }
    },    `

http://jsfiddle.net/kkulig/zx9eq8o5/

**Comment by TorsteinHonsi** [comment]
Show/hide seems to be prepared for in the [setVisible wrap](https://github.com/highcharts/highcharts/blob/v5.0.14/js/modules/boost.src.js#L2662-L2670), but it doesn't work, `this.ogl` is false.
