### ISSUE TITLE
Offline PDF Exporting Shows Invisible Series

### ISSUE THREAD

**Issue by samirelanduk** [highcharts/highcharts#7090]
#### Expected behaviour
When exporting the chart to a file, the generated image should reflect that chart as it appears on screen at the time it was produced. Specifically, only visible series should be present in the image.

#### Actual behaviour
PNG and SVG output behave as expected, but PDF export shows all series, including those invisible at time of file generation.

#### Live demo with steps to reproduce
https://codepen.io/samirelanduk/pen/rzvqON

Download files for PNG and PDF in the above demo and you'll see what I mean.

#### Affected browser(s)
Chrome 60
(haven't tried others)

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

**Comment by TorsteinHonsi** [comment]
#### Workaround
Remove all hidden nodes before converting to PDF:
```js
Highcharts.wrap(Highcharts.Chart.prototype, 'getChartHTML', function (proceed) {
	proceed.call(this);
    this.container.querySelectorAll('*[visibility="hidden"]').forEach(function (node) {
    	node.remove();
    });
    return this.container.innerHTML;
});
```

[View it live on jsFiddle](http://jsfiddle.net/u5m3bfat/1/).

**Comment by TorsteinHonsi** [comment]
Related issue in svg2pdf: https://github.com/yWorks/svg2pdf.js/issues/28
