### ISSUE TITLE
US MAP after pinch zoom in mobile devices not able to drilldown state. ONly in mobile devices. 

### ISSUE THREAD

**Issue by jaiminmoslake7020** [highcharts/highcharts#7091]
#### Expected behaviour
After zooming with fingers US map should be able to drilldown and should show state on click of any state. 

#### Actual behaviour
But it does not respond. Either you have to click reset zoom button or you have to refresh the whole chart.  

#### Live demo with steps to reproduce

https://www.highcharts.com/maps/demo/map-drilldown

Use this. Pinch zoom on mobile and click on any state it will not go to that state. You have to refresh chart or click on reset zoom button.

#### Affected browser(s)
Mobile Devices, Tablets Android, iOS.

**Comment by pawelfus** [comment]
Hi @jaiminmoslake7020 

Thank you for reporting. You are right, after zooming in, touch event doesn't drilldown anymore.

**Comment by jaiminmoslake7020** [comment]
@pawelfus I had done some debugging , there are mouseenter , mousemove and touchstart events been removed. I don't know if any has to do with that. But i thought it may be helpfull to you so putting it here.
