### ISSUE TITLE
The chart disappears when the mouse is hovered [chrome]

### ISSUE THREAD

**Issue by MichalFab** [highcharts/highcharts#7094]
I have chart with lots of data (400 000 lines JSON file). Everything works fine, but here is a problem on chrome. Where mouse is hovered - chart is not visible. The problem only occurs on Chrome. On firefox/safari it works fine. 
My chart configuration is copied from official documentation:
`  $('#container').highcharts({
        chart: {
            type: 'area'
        },
        xAxis: {
            type: "datetime"
        },
        series: [{
            data: processed_json
        }]
    });`

Do you know how to solve it? 

Chrome version: Version 60.0.3112.101
OS: MAC

**Comment by TorsteinHonsi** [comment]
@pawelfus Maybe it's related to what we see on http://jsfiddle.net/wecf1z35/?

![skjermbilde 2017-08-24 kl 09 46 08](https://user-images.githubusercontent.com/227836/29655347-1789b888-88b1-11e7-9423-8ca40cd48418.png)

**Comment by Michalf94** [comment]
I think it is more related to this: https://github.com/highcharts/highcharts/issues/6909
The problem occurs in two macbooks (only on chrome)

**Comment by sebastianbochan** [comment]
I was also not able to replicate it.

MacOSX Sierra
Chrome 60.0.3112.101 

Which version of OSX do you use?

**Comment by Michalf94** [comment]
version:  10.11.6.

**Comment by pawelfus** [comment]
Thanks, just updated from 10.11.5 to 10.11.6 and demo: http://jsfiddle.net/wecf1z35/ looks broken in the latest chrome. Firefox and Safari are fine.

**Comment by pawelfus** [comment]
@Michalf94 

Could you recreate your issue in jsFiddle? It would really help.

**Comment by Michalf94** [comment]
It can be good example: https://jsfiddle.net/hxenwugv/
I have similar chart (with type: area and two axis). 
In the above example, when I hover the chart  - part of the chart is not visible. I have to refresh page to see it. 
In my situation there is the same problem, but all chart is not visible.

**Comment by TorsteinHonsi** [comment]
I can confirm that. Running Chrome 60.0.3112.90 on macOs 10.12.6.

![issue7094](https://user-images.githubusercontent.com/227836/29711203-05264362-8994-11e7-8366-48d337e89911.gif)

**Comment by moonchaser** [comment]
I see the same behavior with Chrome Version 60.0.3112.101 on 10.12.6

**Comment by wimg** [comment]
Experiencing the same on Chrome Version 63.0.3239.30 (Official Build) beta (64-bit) on Windows 8.1

**Comment by DestBest** [comment]
Experiencing the same on Chrome Version 62.0.3202.94 (Official Build) beta (64-bit) on Windows 10 Home

**Comment by TorsteinHonsi** [comment]
Running Chrome 62, 64-bit on MacOS, now I don't have the problem anymore.

**Comment by sebastianbochan** [comment]
Works fine:
- Chrome: 65.0.3325.181 MacOSX
- Chrome: 65.0.3325.162 Windows 10 Pro
