### ISSUE TITLE
3D scatter with enabled=false

### ISSUE THREAD

**Issue by bjarthur** [highcharts/highcharts#7095]
setting enabled to false for a 3D scatter plot with x,y,z values displays a 2D scatter plot between the x and y values.  it would be nice though if there were a way to specify that when enabled was false it was desired to scatter the x and z, or y and z, instead.  thanks.

**Comment by bjarthur** [comment]
relatedly, having an option to project the 3D points onto the 2D frames would be great.  like this:

![](http://www.originlab.com/doc/en/Tutorial/images/3D_Scatter_with_Colormap/3D_Scatter_with_Colormap.png)

**Comment by pawelfus** [comment]
Hi @bjarthur 

It is possible using array as a point with combination of [`series.key`](http://api.highcharts.com/highcharts/plotOptions.scatter.keys). Example for you: http://jsfiddle.net/yxxjj0vo/ If you have different format, you need to reset data with values changed, for example using `setData(data)`.

Regarding projections, you can use plugin [Projections](https://www.highcharts.com/plugin-registry/single/50/Projections).

**Comment by bjarthur** [comment]
you are my Hero!  thanks!!
