### ISSUE TITLE
Data Label not correctly positioned

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#7096]
#### Expected behaviour
There should be a consistency in positioning of data labels.

#### Actual behaviour
The last data label in the given fiddle is vertically bottom aligned while other labels are vertically top aligned. The max of y axis should be automatically adjusted so as to accomodate for the correct position of the last data label in the plot area.

#### Live demo with steps to reproduce
http://jsfiddle.net/yokefbg6/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @sagargurtu 

Extremes are **not** adjusted according to the label bounding box. By default [`crop`](http://api.highcharts.com/highcharts/plotOptions.series.dataLabels.crop) and [`overflow`](http://api.highcharts.com/highcharts/plotOptions.series.dataLabels.overflow) options cause labels translation to fit the plotting area. You can disable these options: http://jsfiddle.net/yokefbg6/1/

If you don't want to use `overflow` and `crop`, then increase [`Axis.maxPadding`](http://api.highcharts.com/highcharts/yAxis.maxPadding) and, if necessary, [`Axis.minPadding`](http://api.highcharts.com/highcharts/yAxis.minPadding).
