### ISSUE TITLE
Pie chart 3d - empty space between slices

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#7097]
#### Actual behaviour
![slicing](https://user-images.githubusercontent.com/2115686/29658979-1644f080-88bd-11e7-91db-7a6fdcde1bdd.gif)

#### Live demo with steps to reproduce
Demo:
- http://jsfiddle.net/to7kczpm/1/

Difficult to replicate.

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Steps:
Hover over animating slices while animation for hide / show runs. http://jsfiddle.net/h6ws554d/
This is visible in the gif - hover is triggered by legend item hover.

**Comment by vikingschris** [comment]
when there will be a solution for this? i have similar issue where my 3d pie chart slice overlaps another, or is under another 3d pie slice when i click legend to hide, then show.
tools:
angular@5
types/highcharts@5
highcharts@6

**Comment by sebastianbochan** [comment]
Hi @vikingschris,
Do you use native highcharts or highcharts-angular wrapper?

**Comment by vikingschris** [comment]
@sebastianbochan I'm using the angular-highcharts (specifically https://github.com/cebor/angular-highcharts) wrapper, and importing the highcharts-3d from highcharts itself. Are you suggesting if I'm using the wrapper, then this has to do with wrapper, and not the native highcharts?

**Comment by sebastianbochan** [comment]
Hi @vikingschris,
Unfortunately we are not authors of the mentioned wrapper, so I advise you to post the bug [here](https://github.com/cebor/angular-highcharts). 
If you will be able to reproduce the same issue in native highcharts, please post demo here.

**Comment by TorsteinHonsi** [comment]
@sebastianbochan It is most likely a Highcharts issue, it's just difficult to replicate. I doubt that the angular wrapper messes with our internal animation.

**Comment by TorsteinHonsi** [comment]
Distilled demo using the renderer only. As we can see, the 2d arc is able to run two animations in parallel (the color animation starts midway the shape animation). The 3d arc fails, as the first animation stops when the second sets in:

http://jsfiddle.net/highcharts/Lkx1ct9e/
