### ISSUE TITLE
Implement Honeycomb series type

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#7098]
Honeycomb or Hexmap visualizations are a type of Heatmaps, where the tiles are hexagonal.

We want to extend Heatmaps to cover this series type, and possibly other arbitrary heatmap types.

**Comment by rootten** [comment]
what happened to this idea?

**Comment by oysteinmoseng** [comment]
Hi @rootten, apologies for a the unclear GitHub history here. This happened: https://www.highcharts.com/demo/honeycomb-usa and Honeycomb (and other [tilemap styles](https://www.highcharts.com/docs/chart-and-series-types/tilemap-series)) are now supported in Highcharts Maps.

**Comment by rootten** [comment]
ok, thanks for explanation!
