### ISSUE TITLE
Local phantomjs/highcharts export server on tomcat,export to png timeout

### ISSUE THREAD

**Issue by ggforlife** [highcharts/highcharts#7099]
I have successfully installed phantomjs and highcharts on a Windows system per instructions Setting Up Export Server, I can preview pictures in type png,jpeg, pdf and svg+xml, can download pictures in PDF or svg+xml type, but when I try to download in type png or jpeg, the log in tomcat console print as:

[DEBUG] [pool-1-thread-1 10:24:21] (AbstractPool.java:poolCleaner:73) in cleanpool, the surplus or shortage is: 0 [DEBUG] [Timer-5146 10:24:22] (TimeOut.java:run:18) Timed out while downloading. [ERROR] [http-nio-8080-exec-1 10:24:22] (SVGConverter.java:requestServer:142) java.net.SocketTimeoutException: Read timed out [DEBUG] [http-nio-8080-exec-1 10:24:22] (ServerObjectFactory.java:validate:59) server didn't pass validation

the chrome browser returned "Timeout converting SVG, is your file this big, or maybe you have a syntax error in the javascript callback?"

I will be thankful for any help you can provide.

**Comment by ggforlife** [comment]
paantomjs version:2.0.0 
tomcat version:8.5 
jkd version:1.7.0_07

**Comment by TorsteinHonsi** [comment]
Thanks for writing, but the Java server is deprecated as you can see from https://www.highcharts.com/docs/export-module/setting-up-the-server. Have you tried the [node based server](https://github.com/highcharts/node-export-server)?

**Comment by ggforlife** [comment]
Thanks for your suggestion,I tried the node based server and succeed [https://github.com/highcharts/node-export-server#using-as-a-nodejs-module](url),but when I tried to start the server,it went wrong with exception:
yyfx_3:/mnt/824zhongyi/1021/tupian # highcharts-export-server -host "127.0.0.1" -port 7777 -styleMode 1 
 Please refer to the attachments for more details about the exception. 
![1](https://user-images.githubusercontent.com/31330334/30144855-6eec673c-93c0-11e7-90b0-5b84761112fe.png)
![console](https://user-images.githubusercontent.com/31330334/30144857-6f03415a-93c0-11e7-8265-3befaed8281c.png)
I am waiting for any suggestion you can provide ,thank you @TorsteinHonsi

**Comment by pawelfus** [comment]
Hi @ggforlife 

Could you tell us your Windows version and how did you install the package? 

If you could show installed packages that would be great:

>$ npm list -depth=0
highcharts-export-server@2.0.0 /path/to/node-export-server
├── async@2.1.4
├── body-parser@1.16.0
├── colors@1.1.2
├── cors@2.8.1
├── express@4.14.1
├── express-form-data@2.0.0
├── express-rate-limit@2.6.0
├── mkdirp@0.5.1
├── phantomjs-prebuilt@2.1.14
├── prompt@1.0.0
├── request@2.81.0
└── uuid@3.1.0

**Comment by TorsteinHonsi** [comment]
@cvasseng Any thoughts?

**Comment by cvasseng** [comment]
@ggforlife: Try running it without `-styleMode 1` (style mode is enabled/disabled using POST arguments).

Also try adding `--logLevel 4` to get some additional logging information:

`highcharts-export-server -enableServer 1 -port 7777 -logLevel 4`
