### ISSUE TITLE
Navigator and Scrollbar are boucing

### ISSUE THREAD

**Issue by zbMax74** [highcharts/highcharts#7100]
#### Expected behaviour
Navigator and Scrollbar have a fix position.

#### Actual behaviour
If the yAxis is set to "opposite: false", both navigator and scrollbar may bounce on the left side while navigating on the chart history, especially if the zoom is very close.

#### Live demo with steps to reproduce
http://jsfiddle.net/t5hmp9b1/1/
Select a close zoom (3 month for exemple). 
Navigate by panning or with the scrollbar.

#### Affected browser(s)
Chrome, Firefox, Internet Explorer, Opera, Safari

**Comment by pawelfus** [comment]
Hi @zbMax74 

Thank you for reporting this bug. It's a duplicated of #5381
