### ISSUE TITLE
Highstock X-Axis year label is not displayed at proper position

### ISSUE THREAD

**Issue by sanjaykanani** [highcharts/highcharts#7101]
refer below image :
![bug x-axis](https://user-images.githubusercontent.com/29813892/29710768-6839c53a-89af-11e7-866c-85144a2c8560.png)

As shown in image it's displaying tooltip of 2002 year  at label 2003  year.

#### Live demo with steps to reproduce
[http://jsfiddle.net/yj1p834f/1/](http://jsfiddle.net/yj1p834f/1/)

**Comment by KacperMadej** [comment]
Hi,

Is you would create the chart wide enough then you could see that ticks are on !st of Jan of each year while points are 1 day before. Crosshair and tick will overlap if both days are rounded to 1 pixel. This doesn't look like a bug. Demo: http://jsfiddle.net/yj1p834f/4/

**Comment by sanjaykanani** [comment]
![reply bug](https://user-images.githubusercontent.com/29813892/29712147-04f8c21c-89b6-11e7-8ef1-c966ab117c67.png)
In old version its displaying year same as tool-tip year.
is there any way to  modify x-axis label so both will be same  .

**Comment by KacperMadej** [comment]
Yes, you could set ticks to be on x values of series data. Demo: http://jsfiddle.net/74e7znwj/

For more technical questions please contact support through other support channels, because we are trying to keep github for bug tracking. https://www.highcharts.com/support
