### ISSUE TITLE
3d column chart with scrollbar shows spurious point label

### ISSUE THREAD

**Issue by marklofdahl** [highcharts/highcharts#7103]
#### Expected behaviour
Chart should only show data point labels for visible data points.

#### Actual behaviour
Chart has data points that are not visible, due to the xAxis max, and scrollbar.
For a data point off the chart to the right, the label is showing up on the far left of the chart.
135.6% is showing up on the far left, and should not show up at all when the scrollbar is to the far left.

#### Live demo with steps to reproduce
http://jsfiddle.net/marklofdahl/gj5Lqkar/

#### Affected browser(s)
tested in Firefox

**Comment by pawelfus** [comment]
Hi @marklofdahl 

Thank you for reporting this issue.

**Workaround:**
Manually filter out unnecessary datalabels using `dataLabels.formatter`, demo: http://jsfiddle.net/bgbpr5b6/

```

formatter: function () {
  var xAxis = this.series.xAxis;

  if (this.x >= xAxis.min && this.x <= xAxis.max) {
    return Highcharts.numberFormat(this.y, 2) +'%';
  } else {
    return '';
  }
}
```
