### ISSUE TITLE
Stacked data label misplaced with large minPointLength 

### ISSUE THREAD

**Issue by hugo-farinha** [highcharts/highcharts#7105]
#### Expected behaviour
Staked data label should be on top/bottom of series

#### Actual behaviour
Staked data label is over the series

#### Live demo with steps to reproduce
https://jsfiddle.net/9scre0u4/

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting. minPointLength and stacked chart is rather tricky - if not-the-last point in a stack is using minPointLength, then other points are not rendered on top of it but on top of the real y value - the same is with stack label. 

Demo: https://jsfiddle.net/9scre0u4/1/ See fist stack
