### ISSUE TITLE
Individual red line on the box plot chart

### ISSUE THREAD

**Issue by alenan2016** [highcharts/highcharts#7106]
#### Expected behaviour
I would like to show an individual red line over my box plot chart. The red line value should be 53 (please see my example below).

#### Actual behaviour
I can show only box plot chart. The red line is invisible.

#### Live demo with steps to reproduce
https://jsfiddle.net/g0y77gas/1/

#### Affected browser(s)
all browsers

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

PS: To insert a red line, use a [plotLine](http://api.highcharts.com/highcharts/yAxis.plotLines): https://jsfiddle.net/highcharts/g0y77gas/2/

**Comment by alenan2016** [comment]
Thank you very much! Best regards!
