### ISSUE TITLE
Series shifted when multiple yAxis with offset

### ISSUE THREAD

**Issue by zbMax74** [highcharts/highcharts#7107]
#### Expected behaviour
The chart is fully drawn and yAxis are displayed with the offest set in the options

#### Actual behaviour
The series is shifted to the left and truncated.
The tooltip still hover the hidden data on the right, but not he ones on the right that are displayed.

#### Live demo with steps to reproduce
http://jsfiddle.net/w26xs14q/

**Comment by pawelfus** [comment]
Thank you for reporting.

It's a regression after a93cef5  - used to work properly in 5.0.11: http://jsfiddle.net/w26xs14q/1/
