### ISSUE TITLE
Stack size exceeded error when using responsive rules.

### ISSUE THREAD

**Issue by RaquelRedondo** [highcharts/highcharts#7109]
#### Problem
When resizing a chart that has a responsive rule with the tooltip option, the chart throws the error:
    `Uncaught RangeError: Maximum call stack size exceeded`

#### Comments: 
I could only trigger the error by using the tooltip option. I am not sure if setting other options might also throw an error.

#### Live demo with steps to reproduce
https://jsfiddle.net/rredondo/x8792he0/

Decrease the width of the window containing the chart to make it smaller than maxWidth (set to 600px).
Make it large again. 
The error should appear in the console.

#### Affected browser(s)
Chrome, Firefox

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Normalized demo (click the button): https://jsfiddle.net/highcharts/x8792he0/6/

Note that it applies only in stock charts, not in vanilla Highcharts.

**Comment by TorsteinHonsi** [comment]
After some digging it comes down to this passage:

https://github.com/highcharts/highcharts/blob/v5.0.14/js/parts/Dynamics.js#L444-L450

When we run series.update on a seires that has a navigator series, something goes wrong. Isolated here: https://jsfiddle.net/highcharts/x8792he0/8/
1. Click the "Series.update" button.
2. Observe how one navigator series is added on each iteration.

So either we need to eliminate the navigator series from this update call, or we need to make sure it performs correctly even though we call .update on all series.

**Comment by TorsteinHonsi** [comment]
Interestingly, the same issue was just reported at #7110.

**Comment by RaquelRedondo** [comment]
Thanks!! I have already experienced problems with the navigator series and the Series.update function before. See #6734
