### ISSUE TITLE
Highstock: updating series type several times, increments chart series instances

### ISSUE THREAD

**Issue by rlaranjeira** [highcharts/highcharts#7110]
#### Expected behaviour
Updating series type should update series and potentially navigator series without re-creating every time new navigator series instance.

#### Actual behaviour
Every time user update series type, new navigator series is created.
Note: Defect dissapear if showInNavigator is false.

#### Live demo with steps to reproduce
http://jsfiddle.net/q5gt0us7/5/

#### Affected browser(s)
Chrome, Firefox and prehaps more ?

**Comment by rlaranjeira** [comment]
Thanks a lot!!

**Comment by rlaranjeira** [comment]
When the fix will be available ?

**Comment by KacperMadej** [comment]
@rlaranjeira The fix should be available in the next official release. Nex planned releases are version 5.0.15 (no ETA) and 6.0.0 (ETA September 30). You could also check the master github branch version of the code - next release candidate. Demo using github's code: http://jsfiddle.net/q5gt0us7/6/
