### ISSUE TITLE
IE doesn't apply defs pattern properly

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7111]
#### Expected behaviour
Hover pattern should be applied the same way as it is on the other browsers.

#### Actual behaviour
Some points are filled with pattern correctly, some partially, some disappear completely.

#### Live demo with steps to reproduce
Hover on every point. Then resize the chart to see that areas are filled with pattern differently, but still not correctly.

This issue occurs in current Highcharts release:
https://jsfiddle.net/cornelos/pwzbz917/

But in current development branch:  
https://jsfiddle.net/ankjyecp/
and hc-fixes:
https://jsfiddle.net/rptmcknf/
patterns are not applied at all.

#### Affected browser(s)
IE

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

**Affected browser(s)**
IE11/Win10, 
IE11/Win7

(Looks fine on: Win10: Chrome, Edge, Firefox, Opera)

**Comment by cornelos** [comment]
Hi,

I did some more investigating and seems to It seems to be an IE11 bug and not related to Highcharts.
Fortunately I found a workaround: https://jsfiddle.net/cornelos/nrapedce/

If I add an invisible <rect> that uses the mask, the problem is gone!
