### ISSUE TITLE
Pie chart shows data label for negative value

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#7112]
#### Expected behaviour
Pie charts should ignore negative values altogether

#### Actual behaviour
Data labels for negative values is rendered when datalabel.format is given (the pie slice itself is NOT rendered)

#### Live demo with steps to reproduce
http://jsfiddle.net/x8zbcbt6/2/
When you remove datalabel format, data label 'AAA' will disappear.

#### Affected browser(s)
All

**Comment by nsdevaraj** [comment]
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/map-bubble/

http://jsfiddle.net/nsdevaraj/pL4w2Lo4/
Data labels doesn't work on Bubble maps
https://github.com/highcharts/highcharts/blob/0017f6c6438795ee3105b283fa1a66d37c764ba0/js/parts/DataLabels.js#L201

**Comment by pawelfus** [comment]
Thank you for letting us know. It's a different issue, let me open new ticket for this: #7313
