### ISSUE TITLE
Updating a pie chart to all negative values doesn't clear the slices

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#7113]
#### Expected behaviour
When you update a pie chart series with all negative number, no pie slices should remain visible (just like when you open a new pie chart with all negative values.

#### Actual behaviour
The original pie slices remain visible

#### Live demo with steps to reproduce
http://jsfiddle.net/L5swc1bu/1/

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting the inconsistency. Negative values for a pie type series doesn't make much sens, but the inconsistency is visible.

**Workaround**: add a negative value to the starting data. Demo: http://jsfiddle.net/L5swc1bu/2/
