### ISSUE TITLE
data labels textOutline not working when useHTML is set

### ISSUE THREAD

**Issue by schneckentempo** [highcharts/highcharts#7114]
#### Expected behaviour
textOutline should work when property useHTML is true

#### Actual behaviour
textOutline is not working with useHTML is true. Readability of the data labels suffers a lot
setting useHTML to false is not an option because of #7092

#### Live demo with steps to reproduce
http://jsfiddle.net/vwutkLau/

**Comment by KacperMadej** [comment]
Hi,

The textOutline is a pseudo property that works for SVG, so if useHTML is used, then it's not applied. It looks like docs could be improved to provide more info and if you require adding the property to HTML, then you could use standard CSS property or suggest an enhancement idea on [userVoice](http://highcharts.uservoice.com/forums/55896-general).

Demo of a workaround: http://jsfiddle.net/vwutkLau/1/

**Comment by TorsteinHonsi** [comment]
The closest we get with HTML is to apply four different text shadows on all sides of the text: http://jsfiddle.net/highcharts/vwutkLau/2/

**Comment by schneckentempo** [comment]
thank you very much
no possibility to get the contrast working?

**Comment by TorsteinHonsi** [comment]
Actually there is - you can use the CSS classes generated by point color: http://jsfiddle.net/highcharts/vwutkLau/3/

**Comment by schneckentempo** [comment]
This looks quite promising, but the demo is not fully correct and any attempts to fix it myself failed

**Comment by TorsteinHonsi** [comment]
Sorry, it was a stupid mistake, I added a JS-style comment that doesn't work in CSS. This works: http://jsfiddle.net/highcharts/vwutkLau/4/

**Comment by schneckentempo** [comment]
I didn't recognice it myself looking at the format of JSFiddle, thanks.
But I still experience this with scatterplot and saw it on pie, funnel too.
Modified scatterplot demo: http://jsfiddle.net/tdc5k64w/
Things get weird here, tooltip is shown below the dataLabels

**Comment by TorsteinHonsi** [comment]
Yes, HTML content is always rendered on top of the SVG. To work around that you would need a full HTML tooltip.

**Comment by schneckentempo** [comment]
Text is still black with black shadow.

**Comment by TorsteinHonsi** [comment]
Yes, black text is the default, so if you have a dark background you need to set it to white: http://jsfiddle.net/highcharts/tdc5k64w/1/.

**Comment by schneckentempo** [comment]
http://jsfiddle.net/tdc5k64w/2/ same when background is white, color doesn't adopt

**Comment by TorsteinHonsi** [comment]
That's correct, it doesn't adapt automatically when you're using HTML. You need to specify the text-shadow in the CSS.
