### ISSUE TITLE
Error when check installation using yarn

### ISSUE THREAD

**Issue by magnus-staberg** [highcharts/highcharts#7115]
#### Expected behaviour
`yarn check` should pass.

#### Live demo with steps to reproduce
In terminal:
`yarn add highcharts`

`yarn check`
gives output
```
yarn check v0.27.5
warning package.json: No license field
warning No license field
error "highcharts" is wrong version: expected "5.0.14", got "v5.0.14"
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

Environment:
yarn 0.27.5
npm 5.3.0
node 8.4.0
macOS 10.12.6

https://github.com/highcharts/highcharts/blob/master/package.json (`"version": "5.0.14",`) has no "v" added to the version string 

https://github.com/highcharts/highcharts-dist/blob/master/package.json (`"version": "v5.0.14",`) has a "v" added to the version string.

Remove "v" from line ` "version": "v5.0.14",` in `package.json` from highcharts-dist.
The repo highcarts-dist has no issues list on github so I'm creating the issue on this repo instead. I hope the correct people notices this ( @TorsteinHonsi seems to do the releases) .

**Comment by TorsteinHonsi** [comment]
Thanks! It will be corrected by the next minor release.
