### ISSUE TITLE
Column Labels with minPointLength

### ISSUE THREAD

**Issue by TMane** [highcharts/highcharts#7118]
#### Expected behaviour
When minPointLength is set, the label position doesn't update his position accordingly of the value of minPointLength causing the column to overlap the label in some cases.

#### Actual behaviour
All Labels should be visible. (Check out the one for "banana" is hidden under the "0" column)

#### Live demo with steps to reproduce
http://jsfiddle.net/tkkuodsg/

**Comment by pawelfus** [comment]
Hi @TMane 

Thank you for reporting the issue. It's a duplicate of #7105.
