### ISSUE TITLE
Y axis scale issue

### ISSUE THREAD

**Issue by rinkudobariya** [highcharts/highcharts#7119]
I got issue in y axis scale for dynamic multiple series.
it automatically take extra scale value for it so may I know how can I set auto scale for it.

I have attach my chart, I want to remove 16 to 18 scale its unnecessary to display. so please let me know how can I remove it. 
![img_01092017_111156_0](https://user-images.githubusercontent.com/17171822/29956715-b9a79576-8e9d-11e7-81b1-a681e6ed1123.png)

and my code is here
```js
this.chart.addAxis({
              id: 1,
              //linkedTo: 0,
              visible: false,
              crosshair: {
                interpolate: true,
                label: {
                  enabled: true,
                  format: '{value:.4f}'
                }
              }
            });
          }

          this.chart.addSeries({
            name: new_series_obj['Tag_Name'],
            color: new_series_obj['color'],
            showInLegend: false,
            yAxis: new_series_obj['attribute_id'],
            data: this.apiDataToHighChartData(chartdata)
          });
         var points = []

          this.chart.series.forEach(function (entry) {
            entry.data.forEach(function (theData) {
              points.push(theData.y);
            });
          });
          this.chart.yAxis[0].update({
            max: Math.max.apply(Math, points)
          });
 ```

**Comment by TorsteinHonsi** [comment]
It's hard to say exactly what goes on since we can't see the chart live, but check out the [chart.alignTicks](http://api.highcharts.com/highcharts/chart.alignTicks) option.

**Comment by rinkudobariya** [comment]
I have added series dynamic in the chart. at that time scale is maintain automatically. and in my series there is no data point between 16 to 18. then this time interval is not have to display. this is the my issue. so I want to know how hightchart calculate y axis scale.

**Comment by TorsteinHonsi** [comment]
If you have more that one Y axis, the extra ticks may be a result of the axes trying to align. They do that by first determining how many ticks they should add, then finding the best fit with the data. This may result in spacing.

If you only have one axis, I'm not sure what is going on. Please set up a live demo on jsFiddle so we can see your actual data and debug.

**Comment by KacperMadej** [comment]
Unable to recreate
Please add a live demo and more info and the issue could be reopened
