### ISSUE TITLE
Column chart not aligned properly with x-axis

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#712]
I have created the following fiddle:
http://jsfiddle.net/2Rpks/

Here the green/blue columns are overlapping and they are not placed correctly 
while the line chart shown below works perfectly.

thanks.

**Comment by GaneshBChandgude** [comment]
We are facing same issue at customer end. 

We can't increase point range as they are interested in missing data points also.

Is there any plan to fix this issue in future release. 

Thanks

**Comment by TorsteinHonsi** [comment]
> We can't increase point range as they are interested in missing data points also.

What about adding null values for the missing data points?
