### ISSUE TITLE
Stacked Area Chart Rendering Strange Dotted Line

### ISSUE THREAD

**Issue by EvanSanderson** [highcharts/highcharts#7122]
#### Expected behaviour
We have a few graphs across our site that are rendering data served by php, and they are almost all rendering perfectly. Below, you can see we are using stacked area charts and all looks well. 

![screen shot 2017-09-01 at 4 35 44 pm](https://user-images.githubusercontent.com/19613745/29986933-a3f958fe-8f33-11e7-92d9-73e5a0968950.png)

#### Actual behaviour
However, for one chart on the site, we are getting a strange dotted line that cuts through the bottom of the chart. I've tried adjusting plotOptions and chart settings to no avail - I can't seem to get rid of this dotted line. I thought perhaps it might be the parameters I'm passing in, but there are about 50 other charts that use almost identical data that do not have this problem. 

![bluemountain graph](https://user-images.githubusercontent.com/19613745/29986910-81031d9e-8f33-11e7-93e8-0afe4cd7de87.PNG)

The Js Fiddle I provided below is utilizing the data from that misbehaving chart, and you can see there is indeed a dotted line cutting through the bottom left quadrant (very faint). 

#### Live demo with steps to reproduce

http://jsfiddle.net/9j7cjeo8/1/
#### Affected browser(s)

Chrome Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Hi @EvanSanderson 

Thank you for reporting the issue. It looks like generated path is not  properly rendered by Chrome, minified demo: http://jsfiddle.net/9j7cjeo8/4/ (FF is fine). Interesting fact: it affects the screen, not DOM, black dotted line is rendered outside the iframe: 
![screen shot 2017-09-04 at 11 41 37](https://user-images.githubusercontent.com/1453926/30021033-3b7195e6-9166-11e7-8ac0-3456081c032a.png)

**Comment by jacobworrel** [comment]
@EvanSanderson did you ever find a workaround for this? Seeing a similar problem in Chrome with some of our charts...

**Comment by pawelfus** [comment]
There is one workaround: [shape-rendering](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering) but it makes chart really bad... 

Snippet:
```
.highcharts-series {
  shape-rendering: optimizeSpeed;
}
```

Demo: http://jsfiddle.net/BlackLabel/9j7cjeo8/7/

**Comment by pawelfus** [comment]
Just tested with Chrome v65 - works fine.

**Comment by sebastianbochan** [comment]
Works fine:
- Chrome: 65.0.3325.181 MacOSX
- Chrome: 65.0.3325.162 Windows 10 Pro
