### ISSUE TITLE
Drilldown chart - can't drilldown by clicking bar after calling setExtremes in drillup event

### ISSUE THREAD

**Issue by marklofdahl** [highcharts/highcharts#7123]
#### Expected behaviour
After calling setExtremes in drillup event, getExtremes should not return null for dataMin, dataMax, and should be able to drilldown by clicking a bar. yAxis should have the height specified in setExtremes.

#### Actual behaviour
After calling setExtremes in drillup event, getExtremes returns null for dataMin, dataMax, and can't drilldown by clicking a bar. yAxis height is incorrect.

#### Live demo with steps to reproduce
https://jsfiddle.net/marklofdahl/zh23zwzv
1) click any bar to drill down
2) click back button to drill up
3) can't drilldown by clicking a bar

**Comment by marklofdahl** [comment]
Is there any workaround? I would like to be able to manually change the yAxis max on drilldown/drillup, but doing so makes it so I can't click on a bar anymore to drilldown.

**Comment by pawelfus** [comment]
Hi @marklofdahl 

This is caused by redrawing chart during the drillup/down action. In that moment series are not added yet. Workaround is to let drillup/down event redraw chart after all changes are done. Updated demo: https://jsfiddle.net/zh23zwzv/8/

**Comment by marklofdahl** [comment]
That fixes the problem with not being able to click the bar. However, the setExtremes call in the drillup event seems to have no effect: getExtremes returns 6 for max (rather than 8), and the y axis is still incorrect - it only shows up to 4 (rather than 8). Any additional thoughts or workarounds?

**Comment by marklofdahl** [comment]
Actually, there is an underlying problem I'm trying to deal with. I'm using a scrollbar from highstocks on the  x axis, and I don't want the y axis to change as I scroll the x axis. I do want the y axis to change on drillldown/drillup. If I can make the y axis not change on x axis scroll, then I won't have to call setExtremes anymore. Is there a way to do this?

**Comment by pawelfus** [comment]
In that case, I suggest to set [series.getExtremesFromAll](http://api.highcharts.com/highstock/plotOptions.series.getExtremesFromAll) to true. [Demo](https://jsfiddle.net/jmr9uofe/).

The problem with yAxis.setExtremes() is strange, it looks like extremes are applied for the previous level, no the one that will appear on.
