### ISSUE TITLE
numericSymbolMagnitude has weird behavior with auto set tickInterval.

### ISSUE THREAD

**Issue by MyeongkookKim** [highcharts/highcharts#7125]
#### Expected behaviour  
  
There is new lang option in Highcharts 5. `numericSymbolMagnitude: Number`.
First, let me explain about number unit in Korea.
Number unit is like below in Korea.
```
1
10
100
1,000
10,000 = 1만
100,000 = 10만
1,000,000 = 100만
10,000,000 = 1000만
100,000,000 = 1억
1,000,000,000 = 10억
10,000,000,000 = 100억
100,000,000,000 = 1000억
...
```

so there is no `10,000만`, `12,500만`, just `1억`, `1.25억`.
but when `tickInterval (auto set, not manually)` is `2,500`. `10,000만`, `12,500만` is shown.

#### Actual behaviour
already explained.

#### Live demo with steps to reproduce

[JS Fiddle Here](http://jsfiddle.net/4cntzqt3/)
This is example. auto set `tickInterval` is `2,500`. 
and `10,000만`,`12,500만`,`15,000만`,`17,500만`,`20,000만` is shown.
but expected appearance is `1억`, `1.25억`, `1.5억`, `1.75억`, `2억`.

#### Affected browser(s)
used browser in test is `Chrome 60` and UA string is `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36`.
but this issue is shown every other browser.

#### my own fix (dirty)
my dirty fix.
it applied labels formatter in axis option.
this snippet has error too when rounding up or down is occur.
```javascript
formatter: function () {
    if (this.value > 999999999999) {
        return Highcharts.numberFormat((Math.abs(this.value) / 1000000000000), 2) + '조';
    } else if (this.value > 99999999) {
        return Highcharts.numberFormat((Math.abs(this.value) / 100000000), 2) + '억';
    } else if (this.value > 9999) {
        return Highcharts.numberFormat((Math.abs(this.value) / 10000), 0) + '만';
    } else {
        return Highcharts.numberFormat(this.value, 0);
    }
}
```

Thanks. I'm happy with highcharts.

**Comment by TorsteinHonsi** [comment]
Thanks for the suggestions!

The responsible code is on these lines: https://github.com/highcharts/highcharts/blob/0d3e063/js/parts/Axis.js#L1239-L1254

In European languages it feels wrong (at least for me) to use decimals in these numbers, at least for low numbers. For example, `0.25k` is better written 250, and `0.25M` is better written 250k. But we should of course find a solution that suits different locales and styles. Perhaps we need to add another option for how deep below the full symbol we are allowed to go? For your example, this would work: 

```js
			var depth = 0.1;
			while (i-- && ret === undefined) {
				multi = Math.pow(numSymMagnitude, i + 1);
				if (
					// Only accept a numeric symbol when the distance is more 
					// than a full unit. So for example if the symbol is k, we
					// don't accept numbers like 0.5k.
					numericSymbolDetector >= multi * depth &&
					// Accept one decimal before the symbol. Accepts 0.5k but
					// not 0.25k. How does this work with the previous?
					(value * 10 / depth) % multi === 0 &&
					numericSymbols[i] !== null &&
					value !== 0
				) { // #5480
					ret = H.numberFormat(value / multi, -1) + numericSymbols[i];
				}
			}
```

**Comment by MyeongkookKim** [comment]
I think new option (depth) you suggested is good! thanks.
