### ISSUE TITLE
Exception in runPointActions method after Series.update()

### ISSUE THREAD

**Issue by AlexanderSokolov1** [highcharts/highcharts#7127]
#### Expected behaviour
The "update" method finished successful and no errors occurred.

#### Actual behaviour
Exception: _Uncaught TypeError: hoverPoint.firePointEvent is not a function_
occurred after calling the "update" method in series event handler.

#### Affected chart types
Heatmap

#### Live demo with steps to reproduce
[Live demo](http://jsfiddle.net/Alexander_Sokolov/z4pyzcdh/)
I am trying to show data labels on heatmap chart when the user hovers mouse on the chart series. It works fine, but exception occurred after calling the "update" method (only at the "mouseOver" event).

```
series: [{
    name: '...',
    data: ...,
    events: {
        mouseOver: function() {
            this.update({ dataLabels: { enabled: true }});
        },
        mouseOut: function() {
            this.update({ dataLabels: { enabled: false }});
       }
    }
}]
```

The exception occurred when the `runPointActions` method tried to call `firePointEvent` method of the `hoverPoint` object:
`hoverPoint.firePointEvent('mouseOver');`
But all fields and methods of the `hoverPoint` object are null because the `update` method destroys all series point objects.

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

#### Workaround
For your specific use case, I think calling `Series.update` on mouse over and mouse out is overkill that will affect performance on larger data sets. Instead, I would go for a pure CSS solution of hiding and showing the data labels: http://jsfiddle.net/highcharts/z4pyzcdh/1/

**Comment by AlexanderSokolov1** [comment]
Thank you for reply. It is helpful.
