### ISSUE TITLE
Highcahrts export to table with multiple column types

### ISSUE THREAD

**Issue by oyvindwh** [highcharts/highcharts#7128]
#### Expected behaviour
When having different chart types in the same chart (see attachment for example) one of the serie is of type scatter, the other ones are of type column the get table returns this in separate lines. Would be better if these where on the same line as expected.

If possible it would be nice to have the value of the first column in the tabel, not from the x-axis title but from a setting in exporting-settings in the script before defaulting to the Category/Datetime. The default is hard to translate to other languages. 

![2017-09-06_08-44-39](https://user-images.githubusercontent.com/106393/30101951-6938b278-92ee-11e7-870b-ed9729f0a628.jpg)

#### Live demo with steps to reproduce

See live example => https://www.nbim.no/no/fondet/markedsverdi/ (second chart)
(the live example uses the github version, but we are soon moving to the Highchart version which has the same behavior. The screenshot is with the Highchart version.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Simplified demo: http://jsfiddle.net/highcharts/f5wrh3uL/1/

Original demo moved to jsFiddle: http://jsfiddle.net/highcharts/ge4wovg3/

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/ge4wovg3/2/

**Comment by TorsteinHonsi** [comment]
#### Temporary workaround
The bug appears with scatter series. As a workaround, you can use a line series with `lineWidth` 0: http://jsfiddle.net/highcharts/ge4wovg3/3/

**Comment by oyvindwh** [comment]
I'll implement the workaround. Any possibilities for the first cell (DateTime/Category text) to get it localized from the exporting part of the script instead of the x-axis?

**Comment by pawelfus** [comment]
Hi @oyvindwh 

There are two options to change what is displayed in column headers:

1) Set `xAxis.title.text` but that will also be displayed on the chart.

2)  Use `exporting.csv.columnHeaderFormatter`, for example: 

```
            columnHeaderFormatter: function (item) {
              if (item instanceof Highcharts.Axis) {
                // axis
              	return 'My name';
              } else {
                // series
              	return item.name;
              }
            }
```

[Demo](http://jsfiddle.net/Lry2dedp/)
