### ISSUE TITLE
x-axis label format for datetime not working with series containing single data point

### ISSUE THREAD

**Issue by dougbergh** [highcharts/highcharts#7130]
When displaying a series with a single data point (using pointIntervalUnit), the x-axis label is incorrectly interpreted. Series with more than one data point are labeled correctly.

#### Expected behaviour

date label on x-axis should show the date corresponding to the pointStart regardless of how many data points are in the series.

#### Actual behaviour

date label is '08:00.00.000' when the series contains only one data point. If you add a second data point to the series in the jsfiddle, the labels appear correctly.

#### Live demo with steps to reproduce

http://jsfiddle.net/aenmd17d/

1. the x-axis label on the jsfiddle does not specify a day.
2. add a second data point to the series, e.g. [29.9, 30.9]. Now the x-axis labels are correctly formatted.

#### Affected browser(s)

Chrome (only one tested)

**Comment by pawelfus** [comment]
Hi @dougbergh 

Thank you reporting this issue. In general, when there is only one point it is hard to guess the best format for just one label. However, I agree with you: when `pointIntervalUnit` is set, we can use that info to use specific unit for that one label.

**Comment by dougbergh** [comment]
Thanks for the reply! So, I've never reported an issue before. What happens next?

**Comment by pawelfus** [comment]
If you have github notifications, then you will receive emails when this issue will receive comments and/or fixes.

**Comment by dougbergh** [comment]
...so it's in a queue to be fixed by someone at some point? Or I could fix it myself and submit a PR, right?
If I don't do that, do you have a sense of when someone might fix it?
I appreciate your attention, thanks a bunch!
Doug

**Comment by pawelfus** [comment]
My apologies for the delay. It is hard to predict when this will get fixed.

@TorsteinHonsi what do you think about the issue?

**Comment by dougbergh** [comment]
I have worked around it, so while it will be great, it's no longer urgent for me!

**Comment by TorsteinHonsi** [comment]
The `dateTimeLabelFormat` is computed in `Tick.addLabel` and handled in the `Axis.defaultLabelFormatter`. It ultimately comes from the `normalizeTimeTickInterval` function, that lands on 1 ms tick interval because there is no known range. 

Honestly I'm not sure how to handle it. We could have a mechanism that when there is only one single tick on the axis, it looks to properties like `pointRange`, `pointInterval` and `pointIntervalUnit` on the series. But what if that single point is on an odd time like 08:00 am like in this case? Should we still just show the date?

Also, I think there are some synergies to the tooltip and how to format the date header there.

**Comment by pawelfus** [comment]
I see, I was hoping for a simple fix, like this: http://jsfiddle.net/BlackLabel/aenmd17d/1/ but now I see complications.

At this moment, maybe a workaround is a way to go: http://jsfiddle.net/BlackLabel/aenmd17d/2/

**Comment by zelenkoff** [comment]
What about this issue? Will it fixed? I have the same problem.

**Comment by pawelfus** [comment]
Hi @zelenkoff could you try this workaround? It's rather simple solution.

> Apply `labels.format` conditionally: http://jsfiddle.net/BlackLabel/aenmd17d/21/

**Comment by zelenkoff** [comment]
Hi, @pawelfus! Thank you, it's works for me.
