### ISSUE TITLE
Feel confusing when using addPoint with mulit series.

### ISSUE THREAD

**Issue by zhenglingfei** [highcharts/highcharts#7131]
http://jsfiddle.net/mrumr25p/1/
When there is a mulit series data, use addPoint in each series makes chart animation seems confusing, is my code got wrong?
This problem seems more serious in highstock v4.2.1

**Comment by sebastianbochan** [comment]
Hi @zhenglingfei,
This is related with fact, that you run animation 3 times in the same moment (3 redraw). Set redraw flag as false and animate it one time.

Demo:
  -

**Comment by zhenglingfei** [comment]
Thank a lot @sebastianbochan
