### ISSUE TITLE
Grouping by year creates an extra column 

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#7132]
#### Expected behaviour

Grouping doesn't create unnecessary columns.

#### Actual behaviour

After data grouping ( yearly ), additional column is created on the right side of chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/kkulig/gpg9d4es/

Click on the "Annual" button.

#### Workaround:

Manualy set tick positions
Live working: http://jsfiddle.net/gmmq2r7y/

**Comment by pawelfus** [comment]
Closing as duplicate of #5692
