### ISSUE TITLE
Series not rendered properly on resize

### ISSUE THREAD

**Issue by rrdnd** [highcharts/highcharts#7133]
#### Problem
The series in the chart is not being rendered properly when resizing the chart.
This only happens when using responsive rules.
Note that I am using Highstock charts, with the repository code.

#### Live demo with steps to reproduce
1. Click the "Small" button.
2. Click the "Large" button.

https://jsfiddle.net/rredondo/vdmch5ed/

#### Affected browser(s)
Chrome, Firefox

**Comment by pawelfus** [comment]
Hi @RaquelRedondo 

Thank you for reporting this issue! It looks like an issue with clipping series. When calling `setSize()` twice it works fine: https://jsfiddle.net/vdmch5ed/2/
