### ISSUE TITLE
series.data is empty for all series when rangeSelector is not set

### ISSUE THREAD

**Issue by rrdnd** [highcharts/highcharts#7134]
#### Expected behaviour
I am trying to use `series.data` in the `chart.events.redraw` listener to get some values from the chart like this:
 `var data = chart.series[0].data`

#### Actual behaviour
`series.data` is an empty array if the rangeSelector property is not set in the chart options.
I am using Highstock.

#### Live demo with steps to reproduce
Click the resize button to trigger the resize event
https://jsfiddle.net/rredondo/f5607y9q/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @RaquelRedondo 

You can can get existing points on the chart from `series.points`, or if you need original points, from `series.options.data`

*Internal note:*
@TorsteinHonsi - I think we used to have info that `series.data` can be empty in the docs, but I don't see it anymore: http://api.highcharts.com/highstock/Series.data

**Comment by RaquelRedondo** [comment]
Hi @pawelfus  
I take it this is not a bug, I just reported it because series.data is in the official api.
I was using series.processedYData to get the point I needed.
Thanks again for everything!!
