### ISSUE TITLE
Random Missing bar labels

### ISSUE THREAD

**Issue by raptor235** [highcharts/highcharts#7135]
Any idea why we would be randomly missing bar labels as below? 

![Preview](http://www.flowpress.com/screenshots/Screenshot_2017-09-08_1.25.53.png)

Running latest version on chrome

**Comment by TorsteinHonsi** [comment]
Yes, it's the [allowOverlap](http://api.highcharts.com/highcharts/plotOptions.column.dataLabels.allowOverlap) option. By default, overlapping labels are removed.

For general tech support, please see www.highcharts.com/support.
