### ISSUE TITLE
Namespace events so that it's possible to properly garbage collect when destroying Highcharts

### ISSUE THREAD

**Issue by elisechant** [highcharts/highcharts#7136]
#### Expected behaviour

Ability to stop listening to document and window events.

#### Suggested solution

* namespace events with `highcharts`
* introduce an `instanceId`, additionally namespace highcharts events with the `instanceId` to allow multiple versions of HIghcharts available if desired
* provide a method of `Highcharts` to stop listening to events and/or destroy `window.Highcharts`

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestion! As you say, it's a big fix...

**Comment by elisechant** [comment]
Yeah, I understand that @TorsteinHonsi. Just flagging 👍
