### ISSUE TITLE
Display issue in 3d half dount chart

### ISSUE THREAD

**Issue by pjohansen1** [highcharts/highcharts#7137]
#### Expected behaviour
Colour lines for Kiwi in example to line up.

#### Actual behaviour
Looks bad, doesn't line up.

#### Live demo with steps to reproduce
http://jsfiddle.net/8k0yx19f/

#### Affected browser(s)
ALL

**Comment by pawelfus** [comment]
Hi @pjohansen1 

Thank you for reporting this bug!

**Comment by pjohansen1** [comment]
Thanks, will this be fixed?

**Comment by pjohansen1** [comment]
Guys?
We are a paying customer and getting queries about this from our clients. Is there a timeframe for a fix?

**Comment by pawelfus** [comment]
Hi @pjohansen1 

If you have the Premium Support service, then please contact with our [support](https://www.highcharts.com/support) - in the email's title add this case number+your license ID.

**Comment by Izothep** [comment]
Hi!

Thank you for information about this issue. 

Until we find a proper fix, it looks that as a workaround for your problem it should be possible to change order of zIndexes (similar to changes in https://github.com/highcharts/highcharts/commit/8694b8b commit). 

Live example: http://jsfiddle.net/8k0yx19f/5/

**Comment by pjohansen1** [comment]
That works great, thanks Grzegorz.


[cid:image002.png@01D19700.AF4ABCC0]
Paul Johansen Senior Solutions Architect
TELSTRA PHONEWORDS™ | CallN by Telstra
350A Douglas Parade, Newport, VIC 3015
P 1300 TWORDS | F 1800 TWORDS | W www.telstraphonewords.com.au<http://www.telstraphonewords.com.au> | W www.calln.com<http://www.calln.com>
