### ISSUE TITLE
Negative color is incorrectly applied - by navigator

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#7139]
#### Expected behaviour
Negative color should be applied below threshold level, in both cases (with navigator and without).

#### Live demo with steps to reproduce
Negative color is applied for points above threshold. The issue appears only when navigator / scrollbar are disabled.

Working demo:
- http://jsfiddle.net/e6jgdxsc/

Unworking:
- http://jsfiddle.net/9wwb3duu/

**Comment by sebastianbochan** [comment]
+1

**Comment by TorsteinHonsi** [comment]
It's not specific to Highstock, and it hasn't got to do with the navigator: http://jsfiddle.net/highcharts/9wwb3duu/1/

The way negative colors (and color zones) work is that for each zone, a separate graph is drawn and a clipping rectangle is applied to it. What happens is this case is that the threshold is so close to 0 that it is rounded to the same pixel, causing the 2px graph to be split in the middle. With a wider line it is easier to see: http://jsfiddle.net/highcharts/9wwb3duu/2/

The only way I can see to fix that behaviour would be to analyze the graph, identify the points where it crosses the threshold, and split it in individual segments. Which could probably be done, but the performance would be poor on data-heavy charts, and the computation would be complicated for splines and areas at least.

**Comment by molchanov1983** [comment]
Thanks
