### ISSUE TITLE
Data label is getting shown inside of the bar in sometimes

### ISSUE THREAD

**Issue by Ramyani** [highcharts/highcharts#7140]
Sometimes the data label is getting shown inside of the bar.
http://jsfiddle.net/n3me6r8k/

**Comment by TorsteinHonsi** [comment]
Yes I know, we designed it that way. See [dataLabels.overflow](http://api.highcharts.com/highcharts/plotOptions.bar.dataLabels.overflow).

If you don't want that to happen, set overflow and crop: http://jsfiddle.net/n3me6r8k/1/.
