### ISSUE TITLE
pie chart - offline exporting to pdf is wrong

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#7142]
#### Expected behaviour
Datalabels should be visible like in regular exporting

#### Actual behaviour
Datalabels are wrong positioned

#### Live demo with steps to reproduce
Demo:
- http://jsfiddle.net/p9czt7q1/

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
See http://jsfiddle.net/p9czt7q1/1/. The remaining problem now is that the data label of the green (third) slice is not hidden, so the second label becomes unreadable.

**Comment by TorsteinHonsi** [comment]
Now the remaining problem is fixed too thanks to https://github.com/yWorks/svg2pdf.js/commit/217c7aea5a33370abda9502fdc1acb21ffa8c9e9 .

Demo: http://jsfiddle.net/p9czt7q1/2/
