### ISSUE TITLE
Export CSV for Heatmap shows wrong header of y-axis

### ISSUE THREAD

**Issue by thaihuutam** [highcharts/highcharts#7144]
#### Expected behaviour
The header of CSV files (from Heatmap) are the same as the text of axis label.

#### Actual behaviour
It only works with x-axis, not with y-axis

#### Live demo with steps to reproduce
Demo:

- https://jsfiddle.net/thaihuutam/1xyo7067/

Steps to reproduce

- I used the demo of Heatmap from HighCharts, and include the exporting csv library
- I set the text of x-axis to "Employee" and y-axis to "Date"
- The name of the data series is "Sales per employee"
- I used the function "Export CSV"
- The header of the CSV files contain: Employee, "Sales per employee (y)", "Sales per employee (value)
- I expected that the headers contain: Employee, Date, "Sales per employee (value)

#### Affected browser(s): Firefox and Chrome

I have no idea if it is a bug, or I have to modify anything to change the header of y-axis

**Comment by TorsteinHonsi** [comment]
You can use the `exporting.csv.columnHeaderFormatter` for that. I've also improved it so that you can now return false in order to use the default header.

**Comment by TorsteinHonsi** [comment]
Live demo: https://jsfiddle.net/highcharts/1xyo7067/1/

**Comment by kamalgupta0808** [comment]
The heatmap exported by csv list first the xaxis , then y axis multiple times and then the values. Can it be not possible to export heatmap same as column stacked highchart

**Comment by pawelfus** [comment]
Hi @kamalgupta0808 

It looks impossible at this moment - stacked column is build from multiple series, heatmap is just one series. Maybe we could add custom callback, where user could write it's own generator for rows/columns/headers.
