### ISSUE TITLE
Feature request: Marker Extrapolation?

### ISSUE THREAD

**Issue by paulo-raca** [highcharts/highcharts#7145]
I often use Highcharts for plotting math curves, say "y=x²".

For pratical purposes, I calculate a small-ish number of data points that I use to create a spline serie. 
I can move the mouse over the series and see the different values of _x_ and _y_ on the tooltip.

And it works perfectly. e.g., http://jsfiddle.net/7gv9p8jo/

Given that this is a continous plot, I'd like to show tooltips on extrapolated data points.
e.g. I'd like to hover over x=0.5 and see y=0.25, despite the series only having the points for x=0 and x=1.

Is it currently possible? If not, Any suggestion on how I could implement it?

**Comment by TorsteinHonsi** [comment]
We did a [study for a function series](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/highcharts/studies/function-series/) type some time ago. Can you use this? 

With your function it looks like this: http://jsfiddle.net/0n6199d9/

**Comment by paulo-raca** [comment]
Very nice! I will probably use that :)

But this example does pretty much the same as I have described (only in a much better way).

Evaluating the value at every pixel is ok on this case, but would be too expensive on 2D and 3D function plots -- e.g., https://jsfiddle.net/gfo1kps9/ and http://jsfiddle.net/f21y4L4x/

**Comment by paulo-raca** [comment]
I was thinking of something along this:
```
series: [{
	[...],
	extrapolate: function(coord) {  // coord = {x:.., y:..., plotX:..., plotY:...}
		return {
			x: coord.x,
			y: coord.x * coord.x,
			marker: {...},
			[...]
		}; //Result is parsed exactly like a data point, including marker options and etc.
	}
}]
```

And `Series.searchPoint` would try using the `extrapolate` callback before using the kdTree.

**Comment by TorsteinHonsi** [comment]
I tried overriding searchPoint, but there are problems with having to fake the point item and series. 

Hooking up to mouse events and triggering the tooltip directly seems promising: http://jsfiddle.net/highcharts/7gv9p8jo/1/

**Comment by paulo-raca** [comment]
I've integrated your suggestions into my contour curve plugin, and it works perfectly :)
- http://jsfiddle.net/mk43z2cg/
- https://jsfiddle.net/7dt9d9oq/

Thank you!

Another question: 
Is there a way to do a "smart-rounding" of axis values?
E.g., If I map the mouse position to X = 0.93683, I should be able to round to 1, 0.9, 0.94, depending on the axis scale.

In other words, the "prettiest number" in the range [xAxis.toValue(e.chartX - 0.5), xAxis.toValue(e.chartX + 0.5)]. Does it make sense?

**Comment by TorsteinHonsi** [comment]
Not quite sure, but maybe you want to look at `xAxis.transA` to get an idea of the translation slope?

**Comment by paulo-raca** [comment]
Thanks for all your help :)

I've managed to use the `normalizeTickInterval` function for this:
```
//Smart-rounding of axis values, where the precision depends on the axis slope.
var axisRound = function (axis, value) {
    if (!axis) {
        return value;
    }
    var valueMin = axis.toValue(axis.toPixels(value) - 0.5);
    var valueMax = axis.toValue(axis.toPixels(value) + 0.5);
    var valueInterval = Math.abs(valueMax - valueMin);
    var roundedValueInterval = H.normalizeTickInterval(valueInterval, null, H.getMagnitude(valueInterval), true);
    var roundValue = H.correctFloat(roundedValueInterval * Math.round(value / roundedValueInterval));
    return roundValue;
};
```
