### ISSUE TITLE
Animation complete callback called many times

### ISSUE THREAD

**Issue by paulo-raca** [highcharts/highcharts#7146]
#### Expected behaviour

When using a `complete` callback on a animation, it should be called _once_, when everything is complete.

#### Actual behaviour

The callback is called a bazillion times.
I guess it's being called after the final animation step of _each_ element being animated.

#### Live demo with steps to reproduce
http://jsfiddle.net/0186u06j/

#### Affected browser(s)
Google Chrome 60

**Comment by TorsteinHonsi** [comment]
Yes that's what happens... The animation config gets passed on to all the elements that are animated. 

It also happens with other functions: http://jsfiddle.net/highcharts/0186u06j/1/

I'm not quite sure how to handle that, it would require some restructuring and rethinking of animation, and it will definately be prone to regressions.

A simple workaround would be to set a flag from the callback to ensure it only runs once.

**Comment by paulo-raca** [comment]
This came back to bite my ass :disappointed: 

I was doing as you said and only invoking the callback when the first element finishes it's animation.

That worked fine until this change: https://github.com/highcharts/highcharts/commit/b4b4221b19a3a50d9ed613b6f50b12f0afcc7d06#diff-4902869e857fed10664dc3f6cb635c92R182

That is, now the callback is invoked immediately for those elements that didn't change, and then again after a while, when the actual animation finishes.

How have you been handling that?

**Comment by paulo-raca** [comment]
I've found a temporary workaround, but it is probably a bug:
- When called immediately due to unmodified values, the callback's `this` is the animation options.
- When called at the end of the actual animation, `this` is the `SVGElement` affected by the animation
