### ISSUE TITLE
Issue in line series plot?

### ISSUE THREAD

**Issue by choudhary001** [highcharts/highcharts#7147]
Hi,
I am getting different line series plot for the same kind of data:

case 1:
```
    series: [{
        data: [
[15,0],[15,0.003875968992248062],[101,0.003875968992248062],[101,0.004521963824289405],[187,0.0006459948320413437],[187,0.004521963824289405],[273,0],[273,0.0006459948320413437],[359,0],[359,0.0012919896640826874],[445,0],[445,0.0012919896640826874],[531,0],[531,0],[617,0],[617,0],[703,0],[703,0],[789,0],[789,0.0012919896640826874],[875,0],[875,0.0012919896640826874]
        ],
        type: 'line'
    }]
```
![image](https://user-images.githubusercontent.com/1501895/30388781-61b30fae-98ce-11e7-8097-243d92d81940.png)

case 2:
```
    series: [{
        data: [[15.0, 0.0], [15.0, 0.003875968992248062], [101.0, 0.003875968992248062], [101.0, 0.0045219638242894053], [187.0, 0.0045219638242894053], [187.0, 0.0006459948320413437], [273.0, 0.0006459948320413437], [273.0, 0.0], [359.0, 0.0], [359.0, 0.0012919896640826874], [445.0, 0.0012919896640826874], [445.0, 0.0], [531.0, 0.0], [531.0, 0.0], [617.0, 0.0], [617.0, 0.0], [703.0, 0.0], [703.0, 0.0], [789.0, 0.0], [789.0, 0.0012919896640826874], [875.0, 0.0012919896640826874], [875.0, 0.0]
        ],
        type: 'line'
    }]
```
![image](https://user-images.githubusercontent.com/1501895/30388792-71e4c976-98ce-11e7-80f4-74963e4baa4d.png)

Can someone explain why I am getting different plots for similar kind of data where the only difference is x-axis values are floats instead of integer?

Thanks!

**Comment by TorsteinHonsi** [comment]
The X values are not the only difference in your data, you also have different Y values...

See for example the first part of the data, where the Y values are clearly different: http://jsfiddle.net/highcharts/74qwdh5a/

Please reopen if I'm missing something.
