### ISSUE TITLE
[Improvment] Indicator when plotBands is thin

### ISSUE THREAD

**Issue by SebaEnaMor** [highcharts/highcharts#7148]
#### Expected behaviour
Display some kind of indicator (like 4px dot on xAxis) instead of band when it is so thin that is not visible. When user will use zoom (by dragging mouse), the chart will dynamicaly replace this indicator into band when the width of band will reach some expected width (ie. 2px).

#### Actual behaviour
If the chart is very long in time, the bands is not showing on screen because period of band is shorten than one pixel width.

#### Live demo with steps to reproduce
http://jsfiddle.net/gL5w0pt9/
Zoom in date range between 2016-03-15 10:00:00 and 2016-03-15 10:10:00, then You'll see the red band.

#### Affected browser(s)
not applicable

#### Additional info(s)
this case is also posted on [Forum](https://forum.highcharts.com/highstock-usage/improvement-indicator-when-plotbands-is-thin-t39613/#p137146)

**Comment by pawelfus** [comment]
Hi @SebaEnaMor 

This is caused, by a very narrow plotband. In your case I suggest to set `borderWidth` and `borderColor` - border is always rendered, while `color` (fill) may not be visible due to small width of the plotband. 

Updated demo for you: http://jsfiddle.net/BlackLabel/L9j0mk2c/
