### ISSUE TITLE
Removing arearange series cause errors in console when tooltip is used 

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7150]
#### Expected behaviour
Removing series should not cause any errors in console

#### Actual behaviour
When arearange series is removed it causes errors in console and chart is not drawn correctly.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/0mr6xafs/6/

Hover over chart to see errors in console.

It looks that this issue is related to destroy "lowerStateMarkerGraphic" and to below commit:
https://github.com/highcharts/highcharts/commit/92f05a8e61b2c2deac690d7b09794699aea16b8d

**Comment by vfuse** [comment]
+1 Seems to be solved in version 6.
