### ISSUE TITLE
tooltip.pointFormat doesn't work in 3D Scatter

### ISSUE THREAD

**Issue by paulo-raca** [highcharts/highcharts#7152]
#### Expected behaviour
Setting tooltip.pointFormat should work as usual

#### Actual behaviour
On 3D scatter charts, pointFormat is always formatted as `x: {x}, y: {y}, z: {z}`

#### Live demo with steps to reproduce

http://jsfiddle.net/xjwhmmjn/

The 3D chart always shows the standard format.
If you disable 3D, the custom pointFormat is used.

#### Affected browser(s)

Chrome 60

**Comment by TorsteinHonsi** [comment]
The problem here is that 3d scatter should have been a separate series type, as it has its own data structure that separates it from a 2d scatter. I'll explore the possibilities.

**Comment by TorsteinHonsi** [comment]
I did what we should have done when we released the 3d features - created a new series type for scatter3d: https://github.com/highcharts/highcharts/commit/584907cdacf312510730f77930fdc732b1b9b1f6

This will be part of Highcharts 6.

See it live at http://jsfiddle.net/highcharts/xjwhmmjn/1/

**Comment by paulo-raca** [comment]
Thanks!
