### ISSUE TITLE
Lines between points doesn't render properly after the title is set to an empty string on drillup

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7155]
#### Expected behaviour
After drillup the chart should look exactly the same as before drilldown.

#### Actual behaviour
After drillup some bottom parts of the series that hasn't been clicked to drilldown are not visible (although all points are visible).

#### Live demo with steps to reproduce
https://jsfiddle.net/kkulig/uetrzLjq/

Click on any point. Drilldown happens and everything is fine. Then click back button to drillup. Some lines are not visible. 

If you clicked the **blue** series lines won't render properly in the **black** series. 
If you clicked the **black** series lines won't render properly in the **blue** series.

When the title set in drillup event **is not an empty string** this problem doesn't occur: https://jsfiddle.net/kkulig/797boaxk/

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
The issue appears only in the highstock.js file, not in highcharts.

Ref:
- https://jsfiddle.net/BlackLabel/au52ree7/
