### ISSUE TITLE
Highstock tooltip doesn't always work when using boost

### ISSUE THREAD

**Issue by cvasseng** [highcharts/highcharts#7159]
#### Expected behaviour

Highstock tooltips working when using boost.

#### Actual behaviour

Gives an exception when hovering. Problem is that it's assumed that `point` exists, while it doesn't when running in boost mode.

Introduced in [152e7e570](https://github.com/highcharts/highcharts/commit/152e7e570).

#### Live demo with steps to reproduce

http://jsfiddle.net/25day6or/2/

#### Affected browser(s)

All.

**Comment by jon-a-nygaard** [comment]
Internal Note: In the current solbrest branch it does not error any more, but it does also not show a tooltip at all.
This is likely due to the fact that kdTree does for some reason not get built. Updated example: http://jsfiddle.net/jon_a_nygaard/25day6or/3/
