### ISSUE TITLE
Highstock: series.addPoint() doesn't result in shifting extremes after resetting data

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#716]
See http://jsfiddle.net/highcharts/Rk6uQ/

Click Toggle. One would expect the extremes to keep changing, but they are frozen after clicking toggle.

**Comment by vickychijwani** [comment]
@TorsteinHonsi could you expose the setBaseSeries() method? I see [it's already there and apparently only requires a bit of modification](https://github.com/highcharts/highcharts/blob/6859245c42a1b2ab597e01957136d618f6b9860d/js/parts/Scroller.js#L932-L936). In fact if I just call it, it seems to work fine, so I'd really appreciate your thoughts on what scenarios could break by calling it currently.

**Comment by 212579878** [comment]
I am using highstock, with dynamic data , multiple axis (maximum 8). I need to add a datapoint to each series (all 8 axes) every second.I need to display data only for last 1 hour , so I enable shift after adding 3600 points to the chart (1 hour = 3600 seconds) , but it doesn't seems to be working for me.when i click on ALL (Range selector). It shows data for more than an hour. I am sure the shift is working (I have tested with less number of datapoints and when i export data so initial data timestamp differs between consecutive download which depicts datapoints are shifting) . But I am not sure why is it accumulating datapoints more than 3600.

**Comment by KacperMadej** [comment]
Hi @212579878

For technical support please use any other support channel - we are trying to keep the github only for bugs. https://www.highcharts.com/support

When you'll contact support please provide a live demo of the problem.

**Comment by oysteinmoseng** [comment]
This seems to be working in latest version of Highstock.
