### ISSUE TITLE
Area charts do not display single value between two null values

### ISSUE THREAD

**Issue by McNetic** [highcharts/highcharts#7161]
#### Expected behaviour
All actual values should be displayed in a chart, at least when explicitly configured so.

#### Actual behaviour
If a single value in an area chart is between two null values (or between a null value and beginning or end of chart), it is not displayed (unless hovered with the mouse). (when connectNulls is set to false, as is the default)

#### Live demo with steps to reproduce
http://jsfiddle.net/McNetic/b61pcy8h/
The first null value is obviously ok, but between the second and the third, the actual existing value is missing from the chart (unless hovered).

#### Affected browser(s)

Probably all

#### Reasoning
 I'm aware there were prior, relating reports like #2766, but I think the conclusion there is not thoroughly thought out:

1) First of all, I think when the user provides values to the chart, it is a fair assumption that he wants them all displayed.
2) Second, while using an area chart technically implies the user wants to display an area, this must not be generally what the user wants to achieve. In fact, we for example do want to display a line (measured values over the time of months or years, hourly or quarter hourly), but use the area chart to make the whole thing better readable/visible by having the space below the line filled.
3) You example charts often have a few categories, where the problems we got are not so obvious, and there may be workarounds. For our application, I do not have simple workarounds. I have thousands to hundreds of thousand of measured values. There are often null values between them, and I can not predict where they are. I provide editing functionality to the user to fill these null values, but the preview of these is not very readable if single points between null values are left out...
4) Lastly, the argument was that technically, below a point there is no area. If you want to stick to that argument, then drawing a point and line down below the point to fill the space below it does not actually draw an area anyways, so it would not really be an inconsistency ;-).

So, I think it would be very nice if this request would be reconsidered and perhaps be implemented as optional.

**Comment by TorsteinHonsi** [comment]
Thanks for writing! I agree with your reasoning. While it is true that a single point technically has no area below it, it is also true that it would be a good aid in situations like yours.

A simple trick would be to apply a stroke to the area fill: http://jsfiddle.net/highcharts/b61pcy8h/5/
Does this look okay to you? If so, we can consider adding logic that draws a 1px spike below the single point instead of the 0px spike that we already have (which is invisible because there is no stroke by default).

Another way to do it would be to add markers, but if you're drawing thousands of points that is not really an option.

**Comment by McNetic** [comment]
Thank you for your kind reply. Adding the stroke is a good workaround for the issue. I'd vote for adding the 1px spike eventually.

**Comment by McNetic** [comment]
Another argument the stroke is only a workaround: it is also added to the x axis where the series has null data points. Example:
Without stroke:
![grafik](https://user-images.githubusercontent.com/1324685/30695542-c66502ee-9ed8-11e7-8d0c-1ad0a6d5d7ca.png)
With stroke:
![grafik](https://user-images.githubusercontent.com/1324685/30695463-90adbc2c-9ed8-11e7-8059-c01779f8fc16.png)
