### ISSUE TITLE
Tiny columns, whereas in version 4.2.2 they are wide

### ISSUE THREAD

**Issue by gmathijssen** [highcharts/highcharts#7163]
#### Expected behaviour
Wide columns, like in version 4.2.2 (change /5/ bij /4.2.2/ for instance

I would like to have the wide bars, maybe with one or two settings.

#### Actual behaviour
Tiny columns

#### Live demo with steps to reproduce
http://jsfiddle.net/127b5fpv/

#### Affected browser(s)
n/a

**Comment by TorsteinHonsi** [comment]
Highcharts does what it should, makes each column fill 1 category. 

In your setup, you are trying to emulate a datetime axis by adding empty categories for all dates except the 1st of each month. It is recommended to use a datetime axis for this: http://jsfiddle.net/highcharts/127b5fpv/1/ .

Please let us know if you need help configuring the datetime axis.

**Comment by gmathijssen** [comment]
I would like to compare the monthly data for 2 years, so jan'16 and jan'17 next to each other
So there is not really a datetime axis, but a numeric one going from 1 to 366 days

**Comment by pawelfus** [comment]
Hi @gmathijssen 

But do you really need each day displayed, if you want to compare monthly data? For example: http://jsfiddle.net/BlackLabel/gdsbp8ry/1/
