### ISSUE TITLE
Borders get wider when zoomed in after mouseover

### ISSUE THREAD

**Issue by callumacrae** [highcharts/highcharts#7166]
#### Expected behaviour

The border should stay the same width as the map zooms in

#### Actual behaviour

![kapture 2017-09-19 at 16 28 18](https://user-images.githubusercontent.com/472830/30600521-95276780-9d57-11e7-9140-f45c10336c3f.gif)

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/all-maps/

1. Zoom in
2. Move mouse around

#### Affected browser(s)

Latest chrome on OS X

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! It's a regression in v5.0.13, specifically https://github.com/highcharts/highcharts/commit/222eae049.
