### ISSUE TITLE
Drillup Redraw

### ISSUE THREAD

**Issue by joshmcf** [highcharts/highcharts#7168]
#### Expected behaviour
After drillup being able to drilldown again.

#### Actual behaviour
After drillup is run drilldown on chart points will not work if drillup runs redraw. NB: this also occurs if redraw is invoked indirectly by functions such as axis.setTitle

#### Live demo with steps to reproduce
http://jsfiddle.net/z1ksnhmf/

1. Drilldown by cliking on a column.
2. Drillup by clicking on back.
3. Attempt to click on a column to drilldown again.

#### Affected browser(s)
All

### Workaround
wrap the redraw function in setTimeout eg:
`setTimeout(function(){chart.redraw();}, 0);`

**Comment by pawelfus** [comment]
Hi @joshmcf 

Thank you for reporting this issue. I would suggest to use [`drillupall`](http://api.highcharts.com/highcharts/chart.events.drillupall) event to change the title.

Regarding workaround: you don't have to call `chart.redraw()`. After drillup event `chart.redraw()` is called anyway.

Related to/duplicate of: #7123

**Comment by joshmcf** [comment]
Hi @pawelfus 
Thanks. I solved my issue by setting the redraw property of  chart.xAxis[0].setTitle to false.

**Comment by essineden** [comment]
Hi, 
I might be a bit late but I'm currently having this issue with dynamic data and multi column chart. 

The chart.redraw() doesn't seem to be working. Is the jsfiddle sample on this page updated with the chart.redraw() or the drillupall? How exactly can i use this on a multi column with xAxis[0].update()? 

TIA

**Comment by pawelfus** [comment]
Hi @essineden 

Could you recreate issue in jsfiddle? In general, workaround is to set `redraw` to false: `axis.update(options, false);`

**Comment by essineden** [comment]
Hi @pawelfus ,

Thanks! this actually fixed it..

chart: events: drillup: this.xAxis[0].update(_options_, false);

I didn't quite understand it at first.
