### ISSUE TITLE
Exported arearange charts aren't correctly rendered in Adobe Reader

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7169]
#### Expected behaviour
Exported arearange charts should be correctly rendered when exported to pdf.

#### Actual behaviour
In Adobe Reader additional thin lines are visible in arearange series.

![screen shot 2017-09-20 at 15 14 33](https://user-images.githubusercontent.com/15050812/30645578-732aea52-9e16-11e7-91a2-534e455b5647.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/znhzdvmw/

Export example to pdf and open it using Adobe Reader

Tested on 2017.012.20098 Adobe Reader version.

**Comment by TorsteinHonsi** [comment]
It's probably related to the areas being drawn section by section, and returning to the baseline for each section.

**Comment by TorsteinHonsi** [comment]
This was fixed in Highcharts v6.0.3.
