### ISSUE TITLE
Charts are rendered with artifacts in Firefox.

### ISSUE THREAD

**Issue by alexpashkov** [highcharts/highcharts#7171]
#### Expected behaviour

Charts are rendered without any artifacts.

#### Actual behaviour

Charts are rendered with artifacts (see attached screenshot);

#### Screenshot

![hcbug](https://user-images.githubusercontent.com/19917423/30648067-d5846d9a-9e25-11e7-8424-f467bcacb82c.jpg)

#### Affected browser(s)
Firefox 55.0.3

**Comment by pawelfus** [comment]
Hi @alexpashkov 

Thank you for reporting this. 

### Live Demo:
http://jsfiddle.net/x662o6u5/

**Comment by pawelfus** [comment]
Probably it was a bug in FF release, works fine in v59+

**Comment by sebastianbochan** [comment]
Works fine 
- FF 59.0.2 MacOSX
- FF 59.0.2 Windows 10 Pro
