### ISSUE TITLE
Tooltip of chart are behind of stacklabel with image

### ISSUE THREAD

**Issue by fedegara** [highcharts/highcharts#7172]
#### Expected behaviour
When i use stackLabels with useHTML:true and show a image, the tooltip should have more z-index than the stackLabels

#### Actual behaviour
stackLabels with useHTML:true and show a image in, the tooltip of the chart is behind of the image of stackLabel (image).

#### Live demo with steps to reproduce
http://jsfiddle.net/65uxy10q/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @fedegara 

This is not a bug. HTML is rendered on top of the SVG, so tooltip will be below the HTML images. You can read details in our [docs](https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting).

**Comment by sebastianbochan** [comment]
**Workaround**
The solution is disable Highcharts tooltip and use CSS version.

  Demo:
      - http://jsfiddle.net/BlackLabel/21q382hL/

**Comment by fedegara** [comment]
Thanks @pawelfus  and @sebastianbochan for the solution. this save my day
