### ISSUE TITLE
Add text to legend when mouseover on series cause Legend to cover up and chart adjust automatically up

### ISSUE THREAD

**Issue by santhosh1190** [highcharts/highcharts#7173]
Is there a way to break the legend downwards from current position instead chart reduce height automatically and legend to cover up chart.

Here's an example: https://jsfiddle.net/sandyAA/kg262wck/3/
Please mouse-over on series. We can see the text updating in legend.

A constraint we have is that the legend chart height should not reduce and legend should not breaking text on upwards. Legend should break the text downwards and increase the chart height automatically on downwards.

**Comment by pawelfus** [comment]
Hi @santhosh1190 

Please, contact with our [support](). We use github for bug reports.
