### ISSUE TITLE
Data Labels disappear when rotation is applied

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#7174]
#### Expected behaviour
The data labels should render correctly when "rotation" and "verticalAlign" is applied.

#### Actual behaviour
Data Labels disappear from the chart when "rotation" and "verticalAlign" is applied together with "inside" true.

#### Live demo with steps to reproduce
http://jsfiddle.net/4jffxqza/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @sagargurtu 

This is caused by `labels.crop` option which hides labels when those are rendered outside the plotting area.

In your case, you should disable this option ( http://jsfiddle.net/BlackLabel/4jffxqza/2/ ), or set `labels.y` ( http://jsfiddle.net/BlackLabel/4jffxqza/1/ ).

**Comment by sagargurtu** [comment]
Okay thanks.
