### ISSUE TITLE
Wrong text position in buttons - exporting  

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#7176]
#### Expected behaviour
Correct label position like in online exporting.

#### Actual behaviour
Labels are out of the box in offline-exporting.js

#### Live demo with steps to reproduce
Demo:
- http://jsfiddle.net/BlackLabel/e6w8uoy5/

#### Affected browser(s)
All

_Internal note_
It looks like a problem with svg2pdf part. @oysteinmoseng

**Comment by TorsteinHonsi** [comment]
This is already fixed in the master, see http://jsfiddle.net/highcharts/e6w8uoy5/1/.

PS: To test changes that has been done to the third party libraries since last release, use the `libURL` option: 

```js
        libURL: 'https://rawgit.com/highcharts/highcharts/master/vendor/'
```
