### ISSUE TITLE
heatmap - click event on iOS

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#7177]
#### Expected behaviour
Click event should triggered

#### Actual behaviour
Click event is not triggered.

#### Live demo with steps to reproduce
Demo:
- https://github.com/highcharts/highcharts/issues/6887

Click event on a point is missing.

#### Affected browser(s)
Chrome / Safari on iPhone / iPad.

_Internal note_
Related with https://github.com/highcharts/highcharts/issues/6887

**Comment by AhmedAlSammany** [comment]
+1 same here, working on Chrome iOS but not Safari iOS
