### ISSUE TITLE
Hidden series automatically becomes visible when chart pans

### ISSUE THREAD

**Issue by kozgal** [highcharts/highcharts#7178]
#### Expected behaviour
The user clicks the legend of a series, which hides it from the chart view.
The user pans the chart
The series that the user manually pressed legend to hide remains hidden

#### Actual behaviour
Any hidden series becomes visible when the chart gets panned or redrawn in any way.
Hidden series should stay hidden and keep state.

#### Affected browser(s)
Able to reproduce in latest version of Chrome and FF. IE not tested, but same behaviour expected

**Comment by pawelfus** [comment]
Hi @kozgal 

Could you recreate issue in jsFiddle? It looks fine: http://jsfiddle.net/BlackLabel/aLc71zyz/

**Comment by kozgal** [comment]
Hi Pawel,

Thanks for getting back so quickly! I can't seem to reproduce the issue in your fiddle either - Maybe it's an issue with the version we are using? we are on 5.0.14 now..

Here's a GIF of the behaviour on our financial markets platform
![sep-22-2017 10-11-28](https://user-images.githubusercontent.com/11654246/30735212-76d1df30-9f7e-11e7-93e0-bce0c9c76de4.gif)

I'll try to debug it a bit more, I have a feeling that it might be caused by the redraw trigger feeding our list of series to the chart without a state (hidden, shown) so it just redraws all the series visible

**Comment by kozgal** [comment]
Hi,

I've discovered the root cause of this issue. On the X-axis redraw, for some reason we refresh the entire list of series.

Sorry for the inconvenience - you can mark this as solved :)

**Comment by sebastianbochan** [comment]
Hi @kozgal 
Thank you for the feedback.

If problem will come again, please reopen the ticket.
