### ISSUE TITLE
Title not consistent when xAxis label shortened

### ISSUE THREAD

**Issue by zbycz** [highcharts/highcharts#7179]
#### Expected behaviour
Shortened xAxis label displays the same text in label and its title including html entities.

#### Actual behaviour
Html entities for title are not processed. 

Note, they are processed for the label by this method: https://github.com/highcharts/highcharts/blob/1ecd7de4c07868de62d81ded08c1472b59af21b1/js/parts/SvgRenderer.js#L2357-L2358

You should probably extend this section of titleSetter() method:
https://github.com/highcharts/highcharts/blob/1ecd7de4c07868de62d81ded08c1472b59af21b1/js/parts/SvgRenderer.js#L1768-L1769

#### Live demo with steps to reproduce
Hover over the first label on xAxis
http://jsfiddle.net/nhgh1Lz9/

#### Affected browser(s)
Chrome 61 on macos

#### Related issue
https://github.com/highcharts/highcharts/issues/3276

**Comment by sebastianbochan** [comment]
Workaround
Demo:
- http://jsfiddle.net/BlackLabel/0enx9rc1/

Based on solution from buildText method:

```
unescapeAngleBrackets = function(inputStr) {
                        return inputStr.replace(/&lt;/g, '<').replace(/&gt;/g, '>');
                    };
```

**Comment by pawelfus** [comment]
Hi @zbycz 

You are right, it should be consistent. 

**Workaround:**
Unescape entities:

    (function(H) {
      H.wrap(H.SVGElement.prototype, 'titleSetter', function(p, value) {
        var renderer = this.renderer;

        unescapeEntities = function(inputStr) {
          H.objectEach({
            '&': '&amp;',
            '<': '&lt;',
            '>': '&gt;',
            "'": '&#39;',
            '"': '&quot'
          }, function(value, key) {
            inputStr = inputStr.replace(
              new RegExp(value, 'g'),
              key
            );
          });
          return inputStr;
        };

        return p.call(this, unescapeEntities(value));
      });
    })(Highcharts)

Demo: http://jsfiddle.net/BlackLabel/nhgh1Lz9/2/

**Comment by zbycz** [comment]
Thanks for the help.

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/nhgh1Lz9/3/
