### ISSUE TITLE
Disabling tooltip causes mouse over point events flood

### ISSUE THREAD

**Issue by kievsash** [highcharts/highcharts#7180]
![highchartstooltipeventsflood](https://user-images.githubusercontent.com/15340874/30734477-ff87c3f8-9f83-11e7-9286-4dbe363e76b8.gif)
#### Expected behaviour
Mouseover event on series point is not generated numerously when you moving mouse on same point whether tooltip is enabled or disabled.

#### Actual behaviour
If I disable tooltip, mouseover and mouseleave events flood is starting. 

#### Live demo with steps to reproduce
Please, see http://jsfiddle.net/z2zwmsbt/

#### Affected browser(s)
Chrome, IE, etc.

**Comment by pawelfus** [comment]
Hi @kievsash 

Thank you for reporting this issue. It used to work in 5.0.12 (http://jsfiddle.net/BlackLabel/z2zwmsbt/1/)

Regression after 5c24114

**Comment by kievsash** [comment]
For now i just set tooltip style display: none to avoid this behaviour
