### ISSUE TITLE
Treemap: tooltip displayed for a parent instead for a child (IE only)

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7181]
#### Expected behaviour
Tooltip should be displayed for child leafs (in this case Rick, Anne, etc.) - like in all other browsers.

#### Actual behaviour
Sometimes tooltip shows the value for the parent leaf (in this case Bananas, Apples etc.):
![ie-treemap-hover-bug-1](https://user-images.githubusercontent.com/13188589/30738496-947cb0da-9f8a-11e7-8691-83b8fbbcc880.png)

It seems that the hover action is done for parent - not child.

#### Live demo with steps to reproduce

**Official demo:** 
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/treemap-with-levels/

Lanunch the fiddle. Don't hover anywhere on the chart. Position the mouse as shown here:

![ie-treemap-hover-bug-2](https://user-images.githubusercontent.com/13188589/30738528-a4183622-9f8a-11e7-8c9d-4e0b1bb3188a.png)

Then then place the mouse the same way as shown on the image from **Actual behaviour** section.
Tooltip always behaves correctly if you hover precisely on the data label.

#### Affected browser(s)
IE

**Comment by TorsteinHonsi** [comment]
I think this is fixed in the master. Please check out http://jsfiddle.net/5fa2be6x/.

**Comment by kamilkulig** [comment]
I confirm, it's fixed in the master branch.
