### ISSUE TITLE
highcharts not a constructor 

### ISSUE THREAD

**Issue by satishrao84** [highcharts/highcharts#7183]
Hello,
I am using webpack, with react and highcharts. I am getting an error with 

`Uncaught TypeError: _highcharts2.default[(this.props.type || "Chart")] is not a constructor`

I've gone though [https://github.com/highcharts/highcharts/issues/4994](url) and I've not been able to find a solution. I've tried every possible permutation and combination of import/require 'highcharts', 'highcharts/highstock,'highcharts.js' and now I am completely out of options. 

 ```
       var Chart = React.createClass({
            componentDidMount: function () {
                // Extend Highcharts with modules
                if (this.props.modules) {
                    this.props.modules.forEach(function (module) {
                        module(Highcharts);
                    });
                }
                // Set container which the chart should render to.
                this.chart = new Highcharts[this.props.type || "Chart"](
                    this.props.container, 
                    this.props.options
                );
            },
            //Destroy chart before unmount.
            componentWillUnmount: function () {
                this.chart.destroy();
            },
            //Create the div which the chart will be rendered to.
            render: function () {
                return React.createElement('div', { id: this.props.container });
            }
         }), element2;
```

Could you please help me out here?

**Comment by sebastianbochan** [comment]
Hi @satishrao84 
Thank you for the reporting.

@jon-a-nygaard any ideas?

**Comment by satishrao84** [comment]
Actually, The problem was the was I set the Chart Options, and the chart type. Once I fixed that, was able to move forward. This issue can be closed. Thanks!

**Comment by sebastianbochan** [comment]
Thank you for the feedback.
