### ISSUE TITLE
y-axis label is not aligned when used gantt as base

### ISSUE THREAD

**Issue by tiwarishrijan** [highcharts/highcharts#7184]
#### Expected behaviour
y-axis label should be aligned behind axis with proper margin calculation:
![image](https://user-images.githubusercontent.com/6523607/30774389-8430d1d2-a09f-11e7-9f88-f808b5b70d7c.png)

#### Actual behaviour
When using gantt as base Highcharts Object the yaxis label shifts to top 
![image](https://user-images.githubusercontent.com/6523607/30774385-6002d53a-a09f-11e7-8613-1fa0bb0537b3.png)

#### Live demo with steps to reproduce

https://jsfiddle.net/stiwari/6u5aeskz/

**Comment by jon-a-nygaard** [comment]
Closing this issue as it has been fixed in the current gantt branch.
- [Example reproducing the issue](https://jsfiddle.net/7gp0j6rd/)
- [Example of current gantt branch](https://jsfiddle.net/twy6pg07/1/)
