### ISSUE TITLE
Enable cross-origin resource sharing for the JS libraries

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#7187]
With [native ES6 module support having landed in Chrome and Safari a few months ago](https://github.com/highcharts/highcharts/issues/7186), it would be great to be able to use import HighCharts directly from [the CDN](https://code.highcharts.com/), without any bundler.

To do this, the linked issue needs to be solved first, after which the CDN server simply needs to add the following header to its responses:

    access-control-allow-origin:*

Learn more at https://enable-cors.org

To test:

**index.html**
```html
<script type="module" src="main.js"></script>
```
**main.js**
```js
console.log('I was imported');
// CORS error
import { HighCharts } from 'https://code.highcharts.com/js/highcharts.js';
// no CORS error
import { HighCharts } from 'https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.14/highcharts.js';
```

![image](https://user-images.githubusercontent.com/33569/30792923-0a258a98-a173-11e7-8bf4-2bbd1748c247.png)

**Comment by sebastianbochan** [comment]
Hi @dandv 
Thank you for the suggestion.

@TorsteinHonsi  what do you think about that?

**Comment by TorsteinHonsi** [comment]
I think that sounds like a great idea. @jon-a-nygaard .

**Comment by jon-a-nygaard** [comment]
This has now been taken care of by our sysadmin. I have briefly tested it and seems to work as it should.
