### ISSUE TITLE
Set Start and End Values Label (Intermediate Value)

### ISSUE THREAD

**Issue by mehmetalidumlu** [highcharts/highcharts#7190]
Hi,
I got this series data :[ 5.5, 7 ,7 ,8 ,6 ,8.5 ,6, 6 ]
Min Value: 5.5
Max Value: 8.5

When i run code block same as JSFiddle example then i line graph start from 5 to 10. 

#### [Image: Standart Graph](http://prntscr.com/gpu3gv)

But i dont wont it.
It must start from 5.5 to 8.5.

#### How can i start it from 5.5 to 8.5 by step 1. 
Example: 5.5 (min) - 6 - 7 - 8 - 8.5 (max) 
#### [JSFiddle Demo](http://jsfiddle.net/mehmetalidumlu/chye97w0/1/)

Thanks all...

**Comment by sebastianbochan** [comment]
For the general support questions please use forum / stackoverflow or email. You can find more information about support here: http://www.highcharts.com/support

ps. You can use tickPositions (http://jsfiddle.net/BlackLabel/d8crshLt/)  or tickPositioner http://jsfiddle.net/BlackLabel/Ld8fbaqg/

**Comment by mehmetalidumlu** [comment]
Hi @sebastianbochan ,
Thanks for your interest.
