### ISSUE TITLE
Problem with labels highcharts treeMap version 5.0.14

### ISSUE THREAD

**Issue by samur3** [highcharts/highcharts#7191]
#### Expected behavior

I used till now highcharts version 5.0.12 and after I did npm install the version changed into 5.0.14
After the update, I have a problem with the treemap, when I click on a parent with label X the label is staying after moving to the child Object.

**Comment by TorsteinHonsi** [comment]
Demo please? It doesn't happen here: http://jsfiddle.net/highcharts/6k1boy51/

**Comment by davidomelettes** [comment]
I'm witnessing this exact behaviour, with the official treemap demo and @TorsteinHonsi 's jsfiddle too. I get the correct behaviour in version 5.0.12, but 5.0.13 and all versions later seem to be affected.

If you click on 'Africa' in the example, I would expect to see the next level of labels displayed ('Sierra Leone', 'Lesotho', etc.) but instead I can only see the the 'Africa' label at this level in the affected versions.

v5.0.12:
![screenshot from 2018-02-07 11-04-37](https://user-images.githubusercontent.com/1515526/35913189-caa7d0b2-0bf6-11e8-9154-da1d38df6997.png)

v5.0.13-current:
![screenshot from 2018-02-07 11-05-01](https://user-images.githubusercontent.com/1515526/35913187-ca8f3944-0bf6-11e8-8618-bf7c23afc721.png)

**Comment by KacperMadej** [comment]
_Internal note:_ looks like the `levelIsConstant: false` doesn't work correctly.

**Comment by jon-a-nygaard** [comment]
Internal note: Regression since effdece
