### ISSUE TITLE
Tooltip wrongly displayed with direction: RTL

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7192]
#### Expected behaviour
Tooltip should be displayed correctly with direction set to RTL.

#### Actual behaviour
When direction set to RTL, text in tooltip is not displayed correctly. This issue is visible in the image below:
![screen shot 2017-09-26 at 17 01 10](https://user-images.githubusercontent.com/15050812/30867472-55201418-a2dc-11e7-8298-fe26b057b431.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/9f9dbo8m/9/

**Comment by SummerLi** [comment]
Is there any update for this bug? Our product is kind of blocked by this.

**Comment by pawelfus** [comment]
Hi @SummerLi 

It's already fixed in v6.0.3, thank you for the notification!
