### ISSUE TITLE
Shared or Split Tooltip NOT working with Boost Module

### ISSUE THREAD

**Issue by yoderexploder** [highcharts/highcharts#7193]
#### Expected behaviour
A shared or split tooltip should work with or without Boost module enabled

#### Actual behaviour
A shared or split tooltip does NOT work with Boost module enabled

#### Live demo with steps to reproduce
Not working, Boost Enabled: http://jsfiddle.net/7kk7L60k/
Working, Boost Disabled:  http://jsfiddle.net/7kk7L60k/1/

#### Affected browser(s)
Tested in Chrome and Safari

**Comment by TorsteinHonsi** [comment]
Fails since v5.0.13, specifically 152e7e570.

**Comment by jon-a-nygaard** [comment]
Internal Note: Goes bad due to the getHoverData is looking for hoverPoints on the series.points. series.points contains shimmed points without `x` values.
Possible solutions:
1. Go back to using searchKDTree. Its likely to cause regressions somehow.
2. Add the property `x` to the shimmed points.
