### ISSUE TITLE
Heatmap module has to be loaded before treemap module, but no errors get thrown if it's not the case

### ISSUE THREAD

**Issue by JoelSanchez** [highcharts/highcharts#7194]
#### Expected behaviour
Highcharts throws an error informing the user that the heatmap module has to be loaded before the treemap module.

#### Actual behaviour
No errors appear in the console and Highcharts behaves in unexpected ways.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/treemap-coloraxis
Change the require order of the mentioned modules (treemap and heatmap). You'll see that the treemap squares lose color. Impossible to debug.

#### Affected browser(s)
All?

**Comment by sebastianbochan** [comment]
Hi @JoelSanchez 
Thank you for the suggestion.

@jon-a-nygaard I think that we can update our article: https://www.highcharts.com/docs/chart-and-series-types/heatmap
