### ISSUE TITLE
Positive and Negative Non-Column type Series does not stack properly

### ISSUE THREAD

**Issue by simPod** [highcharts/highcharts#7195]
#### Expected behaviour

Chart should stack when both negative and positive series are present. I expect it to stack like this http://jsfiddle.net/sx2cku4e/ (but this example works only with positive or negative values

#### Actual behaviour

Chart does not stack and Y values are somehow shifted on Y axis

#### Live demo with steps to reproduce

http://jsfiddle.net/59je3p2q/

Am I doing something wrong?

**Comment by simPod** [comment]
It works properly when using column type chart http://jsfiddle.net/59je3p2q/1/ 🤔

**Comment by sebastianbochan** [comment]
Duplicate of https://github.com/highcharts/highcharts/issues/5671

**Comment by simPod** [comment]
Thanks, @TorsteinHonsi's fiddle http://jsfiddle.net/highcharts/0o61t9cr/4/ solves it

**Comment by simPod** [comment]
Ok not really, continuing in the thread
