### ISSUE TITLE
Highstock: Range selector cant set lower date than the first loaded serie when 2 or more series.

### ISSUE THREAD

**Issue by adamlindqvist** [highcharts/highcharts#7196]
Iam not sure this is a bug or expected behaviour: 

#### Expected behaviour
When changing date range in the range selector I want to be able to set date to the lowest date of any of the series. Even if one of the serie doesn't go that low. I want to see data from 2011. See fiddle.

#### Actual behaviour
It sets date range to the lowest common date of the different series = from 2012.

#### Live demo with steps to reproduce
http://jsfiddle.net/efvz8205/

1. Change date to 2012
2. Change date back to 2011.

Result: It wont be possible to set date range to 2011 again.

#### Affected browser(s)
Chrome, safari (only tested on)

**Comment by sebastianbochan** [comment]
Hi @adamlindqvist 
The navigator uses main series (the first) for setting extremes on xAxis. As a result when the second has "starting" points only, then it does not work properly. It is default functionality, but you can fix it by setting showInNavigator parameter as true.

Demo:
- http://jsfiddle.net/BlackLabel/shhskgkz/

**Comment by adamlindqvist** [comment]
Hi @sebastianbochan. 

Thanks for your answer.
You're right, this solved the issue for me. 

Thanks!
