### ISSUE TITLE
Apply new theme with React

### ISSUE THREAD

**Issue by zergote** [highcharts/highcharts#7197]
Hey, guys,
When you try to dynamically change the theme of the graph, fonts and line colors are not loaded correctly. For example, initially there is the white theme and its colors look good, when changing to the dark theme, it is also loaded correctly, but when trying to return to the white theme it no longer does

https://stackblitz.com/edit/react-dlqrz4

**Comment by sebastianbochan** [comment]
Hi @zergote 
It looks like a bug in highcharts-react, so I advise you to post it in the wrapper's repo.

Ref:
- https://www.npmjs.com/package/react-highcharts

Please reopen the ticket, if problem will come in native highcharts.
