### ISSUE TITLE
'color' option generically documented for other chart types

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#7198]
The documentation for several chart types (e.g. [scatter](http://api.highcharts.com/highcharts/plotOptions.scatter.color) or [gauge](http://api.highcharts.com/highcharts/plotOptions.gauge.color)) mentions different chart types:

> [...] In line type series it applies to the line and the point markers unless otherwise specified. In bar type series it applies to [...]

Other chart types, e.g. [heatmap](http://api.highcharts.com/highcharts/plotOptions.heatmap.color) do have specific documentation for `color`:

> In heat maps this color is rarely used

**Comment by pawelfus** [comment]
Thanks! This is caused by `colorAxis` which is available for heatmap (and not available for gauge, which has just general definition) - in general, heatmap inherits description from Highmaps which is a bit different than others.
