### ISSUE TITLE
'name' property of series<scatter>.data not used

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#7200]
http://api.highcharts.com/highstock/series%3Cscatter%3E.data documents a `name` property for scatter series types.

[This example](http://jsfiddle.net/mb8828ks/) shows that the name appears to not be displayed anywhere.

**Comment by pawelfus** [comment]
Hi @dandv 

Yes, the `name` property is available in the point config. It is not displayed in the tooltip as stated in tooltip config: http://api.highcharts.com/highstock/series%3Cscatter%3E.tooltip :

> Unlike other series, in a scatter plot the series.name by default shows in the headerFormat and poin.x and point.y in the pointFormat.

**Comment by dandv** [comment]
Thanks @pawelfus. BTW, you've just pasted a docs typo, "poin.x" :) (I've added more typos at #2519 today)

**Comment by pawelfus** [comment]
PR: #8094
