### ISSUE TITLE
Scatter plot points lose individual color in CSS styling mode

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#7201]
#### Expected behavior
The [documentation for `series<scatter>.data.color`](http://api.highcharts.com/highcharts/series%3Cscatter%3E.data.color) should mention how to set the color of individual points when using CSS styling.

#### Actual behavior
When using CSS styling, passing a `color` property to a `data` object (`{x, y, name, color}`) doesn't change the color of the point.

#### Live demo with steps to reproduce
In [the demo](http://jsfiddle.net/udv3oyak/), both scatter points remain black. Also, their names aren't displayed anywhere (issue #7200).

**Comment by pawelfus** [comment]
Thanks for reporting!

*Internal note:*
http://api.highcharts.com/highcharts/series%3Cscatter%3E.data.colorIndex explains it pretty well. Probably link to `colorIndex` should be enough.
