### ISSUE TITLE
redraw flag of Chart.update doesn't work when navigator is enabled

### ISSUE THREAD

**Issue by Freywar** [highcharts/highcharts#7202]
#### Expected behaviour
`chart.update({series: [{color: 'red'}], false)` doesn't render new data until `chart.redraw()` has been called.

#### Actual behaviour
Chart shows new values immediately. According to profiler redraw happens as much times as there are changed series.

#### Live demo with steps to reproduce
http://jsfiddle.net/6a4vzpto/2/

Hit update - chart with no navigator doesn't show new colors, chart with navigator does.

Start some profiler and hit update several times - updateNav takes significantly more time than updateNoNav. On my machine 70ms vs 10ms first time (it destroys series immediately for some reason), 70ms vs 1ms all other times. Some reflow operations can be seen in updateNav, but not updateNoNav.

Hit redraw - chart with no navigator now shows new colors.

#### Affected browser(s)
All

The problem is in navigator series update - normal serie update method calls navigator serie update but don't pass down redraw flag.

**Comment by pawelfus** [comment]
Hi again @Freywar 

This issue is also fixed on our master branch, please take a look: http://jsfiddle.net/6a4vzpto/3/

**Comment by Freywar** [comment]
Hi, @pawelfus 

Thanks for examples, next time I'll check latest version before posting issues. Are there any estimates of when it's going to reach NPM?

**Comment by sebastianbochan** [comment]
Hi @Freywar 
It should be within next weeks.
