### ISSUE TITLE
Attempt to update series.navigatorOptions of many series causes an error

### ISSUE THREAD

**Issue by Freywar** [highcharts/highcharts#7203]
#### Expected behaviour
Call to `chart.update(options)` renders chart with new options.

#### Actual behaviour
`Cannot read property '0' of undefined` is thrown, one of series is missing.

#### Live demo with steps to reproduce
http://jsfiddle.net/1h9ejc74/2/

Open dev console, hit update, see the error

#### Affected browser(s)

All

The problem seems to be in serie.update method, when first serie gets updated. It caches `chart.series[0].navigatorSeries`, recreates actual `chart.series[0]` and puts old cached `navigatorSeries` to newly created `chart.series[0]` instance. It does not update `chart.series[0].navigatorSeries.baseSeries` to point to new `chart.series[0]`, but preserves null pointer. navigatorSeries own update does not preserve baseSerie at all. At some point it causes navigator serie to be destroyed and `chart.series[0].navigatorSeries` to point to empty object.

**Comment by sebastianbochan** [comment]
Similiar issue: https://github.com/highcharts/highcharts/issues/7202

**Comment by pawelfus** [comment]
Hi @Freywar 

Thanks for reporting this issue. This is already fixed on our master branch and will be part of the next release: http://jsfiddle.net/1h9ejc74/3/
