### ISSUE TITLE
OHLC Ticks are Drawn Improperly When Line Width is > 1

### ISSUE THREAD

**Issue by mlvn23** [highcharts/highcharts#7204]
#### Expected behaviour
The lineWidth should be taken into account when drawing the ticks. 

#### Actual behaviour
![image](https://user-images.githubusercontent.com/5626477/30972132-91369772-a41e-11e7-954f-2513fbe005bb.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/7zadtvo1/

#### Affected browser(s)
Firefox, Chrome, etc.

**Comment by sebastianbochan** [comment]
Hi @mlvn23,
Could you elaborate your case in more details. Unfortunately it is a little bit unclear for me. Do you mean that lineWidth is not applied correctly ?

**Comment by mlvn23** [comment]
Hi @sebastianbochan,

As an example, look at the data for APPL on Sep 8, 2017:

![image](https://user-images.githubusercontent.com/5626477/30980273-56ae8ab2-a435-11e7-8f12-9f1af0ccc26f.png)

An OHLC visualizes the open, high, low, and the close. The left tick represents the opening price, the right tick represents the closing price, and the extremes of the vertical bar represents the highest and the lowest price of the bar. The open must be <= high and >= low. The close must be <= high and >= low.

On Sep 8, 2017, the low is 158.53 and the close is 158.63. So LOW < CLOSE, but the picture above does not depict this. Actually, if you zoom in or make lineWidth > 1, you'll see that the CLOSE is actually depicted as if it's lower than the LOW, which is not possible (and it forms this half-connected / dangling right tick as you increase the lineWidth):

![image](https://user-images.githubusercontent.com/5626477/30980576-654631dc-a436-11e7-811e-23c85870aede.png)

This is how it should have been rendered based from competing solutions:

![image](https://user-images.githubusercontent.com/5626477/30980455-fa597df2-a435-11e7-9d39-80a0973e56c0.png)

![image](https://user-images.githubusercontent.com/5626477/30980463-feda6c56-a435-11e7-8ab9-8d9f43d00838.png)

**Comment by sebastianbochan** [comment]
Hi @mlvn23,
Thank you for the valuable feedback. Now its clear.

**Comment by pawelfus** [comment]
**Workaround:**
Set in CSS:
```
.highcharts-series path {
  stroke-linecap: square
}
```
Demo: http://jsfiddle.net/7zadtvo1/2/

Note: That means ohlc tick is not 100% accurate. With current linecap, line end **exactly** where the value is, with squared line caps it looks better, but it's not that accurate..

**Comment by mlim-extra** [comment]
Bump
