### ISSUE TITLE
Slow heatmap series update after tooltip was shown

### ISSUE THREAD

**Issue by cbergmiller** [highcharts/highcharts#7205]
#### Expected behaviour
The series update should not take longer after the user has triggered point tooltips.

#### Actual behaviour
Updating a heatmap series with 3000 points takes three times longer after triggering tooltips on the series by hovering over it.

#### Live demo with steps to reproduce
http://jsfiddle.net/sv65x0ba/2/
- load the fiddle and press update - timing is shown in the console.
- run fiddle again and hover over the series before pressing the update button - update time should triple in chrome

#### Affected browser(s)
Tested in chrome 61.0.3163.100

**Comment by sebastianbochan** [comment]
Hi @cbergmiller 
Thank you for the reporting.

@jon-a-nygaard

**Comment by TorsteinHonsi** [comment]
This appears to be fixed in v6. I am able to reproduce it in v5, but now the update times are identical. Please reopen if you disagree.
