### ISSUE TITLE
Not all mouse events are fired

### ISSUE THREAD

**Issue by AlexanderSokolov1** [highcharts/highcharts#7206]
#### Expected behaviour
All the 'mouseleave/out' events are fired

#### Actual behaviour
Some of events are not fired

#### Live demo with steps to reproduce
http://jsfiddle.net/Alexander_Sokolov/js94u8aL/3/
Open this demo in IE (9, 10 or 11) in win7 and start hovering on columns with charts (as fast as you can :-) ). As a result, you may face a problem when several tooltips are not hiding at all.

#### Affected browser(s)
IE

#### Note
If you press on any chart and start moving the mouse to another one, the tooltips will not be hidden in all browsers.

**Comment by sebastianbochan** [comment]
Hi @AlexanderSokolov1 
Thank you for the reporting. The bug is really difficult and random to reproduce. I added a small addition, could you test it and let me know if worked?

http://jsfiddle.net/BlackLabel/pce9vdzf/

**Comment by AlexanderSokolov1** [comment]
Hi @sebastianbochan 

Thank you for your fast reply. Issue is still reproduced in your demo under IE:
![image](https://user-images.githubusercontent.com/13215221/31012786-ce78f398-a51b-11e7-9411-0d0250925f76.png)

Please note that it is always reproduced in any browsers if you click at any heatmap (do no release the mouse button) and move the mouse to another heatmap:
![image](https://user-images.githubusercontent.com/13215221/31013036-dccb9378-a51c-11e7-8c30-7f3f8f4060c6.png)

**Comment by AlexanderSokolov1** [comment]
Yes, if you press the mouse button and start move it, this issue will reproduced but I don't think what this is a major issue ("_Hey just release the button and it will looks good again._").

But in IE you can reproduce this issue just by moving your mouse over the column with charts. This is a bit more major problem I think because this is a common case when you move your mouse over a column when scrolling or searching something.
Also I discovered what all `.highcharts-cintainer` elements with unhidden tooltips have a `:hover` pseudo class at the same time.
