### ISSUE TITLE
Point click event is lost after chart reflow for 3D column chart

### ISSUE THREAD

**Issue by ecris87** [highcharts/highcharts#7207]
#### Expected behaviour
Point click event is preserved after chart reflow for 3D column chart.

#### Actual behaviour
Point click event does not fire after reflow.

#### Live demo with steps to reproduce
https://jsfiddle.net/ecris87/6b78usrL/

1. Click chart column
2. Click reflow button
3. Click column again

#### Note
Worked in 5.0.10. After upgrade to 5.0.14 it doesn't.

**Comment by Izothep** [comment]
Hi @ecris87!

Thank you for contacting us and for sending specific information about your issue! 

It looks that your problem is already solved on GitHub Highcharts version.

Live example: https://jsfiddle.net/BlackLabel/6b78usrL/3/

**Comment by ecris87** [comment]
That's great! Thanks @Izothep.
