### ISSUE TITLE
Need help to get a old project running

### ISSUE THREAD

**Issue by ChristianGrieger** [highcharts/highcharts#7208]
#### Live demo with steps to reproduce
https://just-dice.littlecms.de/

Hey all,
i found a old project on my saved files and tried to get it back working but it looks like the charts are totally broken.

Problem 1:
When open the page the line charts are displayed the right way. After selecting zoom range 'ALL' the chart ends in one point and its not possible to get back to the first view when loading the page.
This problem is present for tab profit,wagered,invested,staked.

Does anyone know how i can fix this :/?

Problem 2:
When selecting one of the column charts from my data tabs profit day, wagered day or staked day, all the data ends in one grouped point. Even the range change does not solve the problem for some reason. I already tried to disable data grouping that worked for zoom range all but when i try to zoom in all data is gone. There are daily points as you can see on source code from 2014 on in the column charts.

 Does anyone know how i can fix this :/?

Thank you very much for your help.

**Comment by sebastianbochan** [comment]
Hi @ChristianGrieger 
Thank you for contacting us. This is bugtracker for reporting issues only. I advise you to use stackoverflow / forum / email for the further [support](http://www.highcharts.com/support)

Ps. One of the reasons is not sorted data by x ascending. please try to fix this.

**Comment by ChristianGrieger** [comment]
okay thank you for the reply i try to find the option for sorted data by x ascending in the documentation.

**Comment by sebastianbochan** [comment]
In the Highcharts there is not build-in sorting function. You should do that in the preprocessing or in your back-end.
