### ISSUE TITLE
Legend is different position in macOSX and Windows

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#7209]
#### Expected behaviour
The same position and background.

#### Live demo with steps to reproduce
Demo:
- http://jsfiddle.net/BlackLabel/fdhubepy/

![mac_chrome3](https://user-images.githubusercontent.com/2115686/31011262-eb4185e8-a50d-11e7-8f23-644d8118594d.png)
![win10_chrome2-2](https://user-images.githubusercontent.com/2115686/31011263-eb601d28-a50d-11e7-919c-fcdbe628b815.png)

Morever it looks like transparent background is solid in Windows.

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
The exact pixel positioning of elements relate to what bounding boxes are reported for text elements. This differs greatly between browsers for the same font, and even more on different systems using different fonts.
