### ISSUE TITLE
iPad/iPhone page scrolling delay on a chart

### ISSUE THREAD

**Issue by nachoab** [highcharts/highcharts#721]
I've tried my site (full of charts) on an iPad and iPhone and there is a little problem: When you try to scroll the website,  if you put your finger on a chart, it has a big delay.  You have to put your finger in a place where there is no chart in order to see a smooth scrolling.
If you put your finger on a chart, wait for 2 seconds, and then try to scroll the page, the page will be scrolled okay.
Same with resizing the website.

It's not a SVG problem, with this one everything it's good: http://croczilla.com/bits_and_pieces/svg/samples/butterfly/butterfly.svg

**Comment by MartinMoizard** [comment]
It looks like this issue is still present on Highmaps.
