### ISSUE TITLE
Point.select() doesn't set highcharts-point-select class on the point

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7210]
#### Expected behaviour
_Point.select()_ should set _highcharts-point-select_ class on the point.

#### Actual behaviour
It doesn't.

#### Live demo with steps to reproduce
http://jsfiddle.net/kkulig/27x9hjkk/

Click the button. _console.log()_ proves that the point has the selected state. However Highcharts didn't add the class to the SVG element. Fill is not applied.
Everything works fine when the selected state is set via property: http://jsfiddle.net/kkulig/7vkznt2q/

#### Affected browser(s)
All

### UPDATE

_Point.update()_ doesn't seem to work either: http://jsfiddle.net/kkulig/0f3po26f/

**Comment by TorsteinHonsi** [comment]
It comes from these lines where the gauge series` `setState` function is overridden:

https://github.com/highcharts/highcharts/blob/v6.0.1/js/parts-more/GaugeSeries.js#L550-L552

#### Workaround
We can override the override, but the side effect is an unwanted hover effect and some repositioning: http://jsfiddle.net/27x9hjkk/4/

**Comment by bhuber2010** [comment]
Similar issue on boxplot, but the setState isn't being overridden so that doesn't seem to work.

https://jsfiddle.net/uuj77yh6/3/

**Comment by KacperMadej** [comment]
@bhuber2010 This is caused by boxplot points lacking selected state - https://github.com/highcharts/highcharts/issues/2340

**Addition for the last workaround:**
Removed side effect of moved point.
Demo: http://jsfiddle.net/BlackLabel/27x9hjkk/5/
