### ISSUE TITLE
Gaps in axis labels when crossing daylight savings boundary

### ISSUE THREAD

**Issue by sfishel18** [highcharts/highcharts#7211]
#### Expected behaviour

When drawing an axis with a 2 hour tick interval, that crosses a daylight savings boundary, I would expect the distance between ticks to be uniform across the whole axis.

#### Actual behaviour

The ticks are un-evenly distributed with a noticeable gap.  It seems that the tick placement logic is designed to preserve an even spacing between the numbers on the labels instead of the actual axis distance.  That logic makes sense for a larger tick interval like 12 hours, but for smaller tick intervals I think uniform spacing would be preferable.

#### Live demo with steps to reproduce

http://jsfiddle.net/sfishel18/ctrn78sv/

#### Affected browser(s)

Chrome

**Comment by pawelfus** [comment]
Hi @sfishel18 

Thank you for reporting the issue. It looks like a regression since v5.0.1, version 5.0.0 looks fine: http://jsfiddle.net/ctrn78sv/2/

**Comment by pawelfus** [comment]
**Workaround:**
Use [`tickPositioner`](https://api.highcharts.com/highcharts/xAxis.tickPositioner) to change how ticks are calculated:

```javascript
    tickPositioner: function(min, max) {
      var minV = this.tickPositions[0],
        ticks = [minV];

      while (minV < max) {
        ticks.push(minV += this.tickInterval);
      }

      ticks.info = this.tickPositions.info;

      return ticks;
    }
```
Demo: http://jsfiddle.net/BlackLabel/c2jqt97h/1/

Issue related to #7621 and #6797 - we have this limitation set here: https://github.com/highcharts/highcharts/blob/be069532aab81512c0385d36c68974ebb69dc83d/js/parts/Time.js#L694-L706

**Comment by TorsteinHonsi** [comment]
We have rewritten parts of the timezone/ticks handling now, but this behaviour is preserved. If ticks are configured to display every two hours, Highcharts will render them on 00:00, 02:00, 04:00 etc, even across DST transitions.
