### ISSUE TITLE
Docs: should /Point document the `name` and `color(Index)?` fields?

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#7212]
I landed at http://api.highcharts.com/highcharts/Point from http://api.highcharts.com/highcharts/tooltip.pointFormatter. pointFormatter supports `this.name`, so I expected the `name` property to be documented in the Point class.

Same for `color` and `colorIndex`.

**Comment by pawelfus** [comment]
Yes, is should be in our docs.

*Internal note:*
In the new API, Point class has `color` defined, but not `name` and `colorIndex`.
