### ISSUE TITLE
(Un)grouping fails when getExtremesFromAll enabled

### ISSUE THREAD

**Issue by noreentry** [highcharts/highcharts#7214]
#### Expected behaviour
Data grouping deactivates (or group size decreases) when zooming into smaller time range

#### Actual behaviour
Data grouping remains active even after zooming into smaller time range (if getExtremesFromAll == true)

#### Live demo with steps to reproduce
https://jsfiddle.net/h2y3cgvL/
1. notice that data is grouped into xx min intervals in both charts
2. zoom into 1h time range (in both charts)
3. data remains grouped in the second chart (data and all other settings except getExtremesFromAll are the same)

#### Affected browser(s)

**Comment by pawelfus** [comment]
Hi @noreentry 

Thank you for reporting your issue. I am not sure if this if bug - it is rather error in the docs, `getExtremesFromAll` works for both, xAxis and yAxis, that means dataGrouping will be turned on/off according to the entire dataset, not only given range (just like yAxis extremes). I think we had similar discussion earlier, to split this option into separate ones to get better control.

**Comment by noreentry** [comment]
maybe it's better to separate getExtremesFromAll into getExtremesFromAll**X** and getExtremesFromAll**Y** ?
