### ISSUE TITLE
resetZoomButton appears above tooltip

### ISSUE THREAD

**Issue by davidmatas** [highcharts/highcharts#7216]
#### Expected behaviour

Should be a way to paint tooltip above `resetZoomButton` 

#### Actual behaviour

![image](https://user-images.githubusercontent.com/271760/31089275-c3ae6922-a7a3-11e7-8e9c-88f81e504c2f.png)

resetZoomButton is painted after tooltip inside the `svg` element so there is no way to position tooltip above `resetZoomButton`.

I've tried `useHTML: true` for tooltip and use `.highcharts-tooltip > span` selector to give the tooltip background and z-index and it improves, but the button still appears above tooltips borders

![image](https://user-images.githubusercontent.com/271760/31089584-02da2964-a7a5-11e7-982f-47befc37a2b5.png)

#### Live demo with steps to reproduce
1. Zoom in a way that the chart line goes from down to top (April to September)
2. Show the tooltip near of the resetZoomButton

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/resetzoombutton-position/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @davidmatas 

It looks like our docs are missing `zIndex` option: it's available under `theme` options, please take a look: http://jsfiddle.net/nw8mmsz1/

**Comment by davidmatas** [comment]
@pawelfus Great! Thanks you!

I knew that `theme` options existence, but I thought it can only receive text properties as it says in the docs: `The theme also supports style, a collection of CSS properties for the text`
