### ISSUE TITLE
Enable cross-origin resource sharing for data sample JSON endpoints

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#7217]
Related to #7187 - would be great to be able to use the data samples (such as https://www.highcharts.com/samples/data/from-sql.php featured in the [lazy loading sample](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/lazy-loading/)) from local files via the modern [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) API call. Right now, trying to use that endpoint from `localhost` or a `file:///` origin results in a CORS error:

> Failed to load https://www.highcharts.com/samples/data/from-sql.php?callback=?: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

![image](https://user-images.githubusercontent.com/33569/31110584-e14ea0dc-a7bc-11e7-8346-20c5ec6029ca.png)

The code is just a saved local copy of the lazy loading sample, but trying to use [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) rather than `jQuery.getJSON`.

**Comment by pawelfus** [comment]
Thanks @dandv ! 
I'm not sure if we should use `fetch`, no IE support would result in not working official demo. We could check in code if `fetch` is supported, but that would complicate the example..

**Comment by dandv** [comment]
Oh, I meant `fetch` would be used in user code. The examples shouldn't be changed to use fetch, but if a user wanted to test quickly without jQuery, being able to `fetch` the JSON endpoints provided by HighCharts would be nice.

**Comment by dandv** [comment]
Is this issue also causing some samples to break? E.g. https://www.highcharts.com/stock/demo/markers-only in either JSFiddle or Codepen, fails to load the JSON.

**Comment by pawelfus** [comment]
It's probably cache problem, could you clear cache and try again? Thanks!

**Comment by pawelfus** [comment]
It's probably cache problem, could you clear cache and try again? Thanks!

**Comment by dandv** [comment]
This is incognito mode in Chromium 76.0.3809.100 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/33569/64756842-e379d800-d4f5-11e9-8765-4baa16abe45b.png)
