### ISSUE TITLE
Crosshair label not showing correctly on multiple series 

### ISSUE THREAD

**Issue by valency** [highcharts/highcharts#7219]
#### Expected behaviour
Crosshair label should show differently on different series.
On series 1:
![image](https://user-images.githubusercontent.com/829258/31122419-5a3b4818-a86e-11e7-97d2-c1815f1f4db4.png)
On series 2:
![image](https://user-images.githubusercontent.com/829258/31122502-bb530f32-a86e-11e7-8b81-427a76d70777.png)

#### Actual behaviour
But when moving the cursor from series 1 to series 2 and then back to series 1, it shows incorrectly:
![image](https://user-images.githubusercontent.com/829258/31122563-f1b55ad0-a86e-11e7-8732-1e88b635c82b.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/Ladgk4yp/4/

#### Affected browser(s)
Google Chrome 60.0

**Comment by pawelfus** [comment]
Hi @valency 

Thank you for reporting, it is clearly a bug.

**Comment by Karthikeyan1993** [comment]
any update on this bug ??

**Comment by pawelfus** [comment]
I will check this today.

**Comment by Karthikeyan1993** [comment]
@pawelfus you're life saver, i would be grateful if you could

**Comment by Karthikeyan1993** [comment]
@pawelfus is this fixed ??

**Comment by Karthikeyan1993** [comment]
@pawelfus can you please provide fiddle ,if you can

**Comment by pawelfus** [comment]
Hi @Karthikeyan1993 

I would love to, but jsFiddles are broken. It's fixed on a bugfix/* branch, not merged into the master branch.

**Comment by pawelfus** [comment]
Demo with fix applied on the master branch: http://jsfiddle.net/Ladgk4yp/6/
