### ISSUE TITLE
x-axis min and max are not respected for a datetime column series containing a single value

### ISSUE THREAD

**Issue by andiger** [highcharts/highcharts#7220]
#### Expected behaviour
The x axis should show 2016 to 2020 with a column only covering the 2016 tick.

#### Actual behaviour
The x axis seems to start at 2005 and end at 2029 (see console in demo). The column covers multiple years.

#### Live demo with steps to reproduce
http://jsfiddle.net/adgadg/6xfgc2rd/

Uncommenting the dummy data value in the total-series gives a much more reasonable start and end dates for the x-axis and the column only covers the 2016 tick.

**Comment by pawelfus** [comment]
Hi @andiger 

This is caused, as you noticed, by using just one column. With just one column, we don't know if you want to represent a year, a day, or maybe it's a value for an hour and we can only guess the best range and size for a point. 

In that cases, please use `series.pointRange` to inform Highcharts, what exactly that points represents, take a look: http://jsfiddle.net/6xfgc2rd/11/

**Comment by andiger** [comment]
Oh, I see. That solves my problem. Thank you.
