### ISSUE TITLE
Highcharts-dist double files 5.0.14

### ISSUE THREAD

**Issue by Fasani** [highcharts/highcharts#7221]
Hi, Why so many files. I have duplicates of everything with different line numbers. Why included the /js/modules when it is a dist build? I upgraded today and pulled in an extra 220k lines of code. 

https://github.com/highcharts/highcharts-dist/tree/master/modules
https://github.com/highcharts/highcharts-dist/tree/master/js/modules

**Comment by TorsteinHonsi** [comment]
The files in the `/js` folder are the ones without styling options.

See https://www.highcharts.com/docs/chart-design-and-style/style-by-css
