### ISSUE TITLE
Highstock (latest version 6) not working in Internet Explorer 11

### ISSUE THREAD

**Issue by WhiteBearSpirit** [highcharts/highcharts#7223]
#### Expected behaviour
I expected charts to be rendered as usual. For example, your first Highstock demo: https://www.highcharts.com/stock/demo/basic-line

#### Actual behaviour
Only part of some label and title is shown, the rest of container is empty. On every mouse move same error appears in console.
```
SCRIPT5007: Unable to get property 'call' of undefined or null reference
highstock.js (27,179)
```
![image](https://user-images.githubusercontent.com/18743472/31169557-af025498-a901-11e7-94f9-a5243667c82d.png)

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/basic-line

#### Affected browser(s)
Internet Explorer 11
![image](https://user-images.githubusercontent.com/18743472/31169457-52e0a8cc-a901-11e7-8c2c-75be9c9a672c.png)

upd: same results on IE mobile

**Comment by KacperMadej** [comment]
Thank you for reporting - it looks like H.findPolyfill is missing.

**Comment by KacperMadej** [comment]
**Workaround**: add module oldie - http://jsfiddle.net/BlackLabel/1k0c98uk/

Turns out that IE11 doesn't support `Array.prototype.find`

**Comment by Pakopub** [comment]
Well, thank you for this!

**Comment by boreynol** [comment]
Thanks for the workaround! Any ETA on a true fix?

**Comment by TorsteinHonsi** [comment]
We'll fix it today.

**Comment by Bill-VA** [comment]
Looks like it's up again.  Thanks

One thing I noticed yesterday is that if I followed the URL to https://code.highcharts.com/stock/highstock.js and saved the .js file locally and referenced it that way, the charts rendered normally.  Weird.
