### ISSUE TITLE
Legend item text not positioned properly when useHTML is enabled (Highcharts 6.0.0 only)

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7224]
#### Expected behaviour
Legend item text should be positioned in the bottom-middle part of the chart (next to the series marker).

#### Actual behaviour
It's positioned on the top-left part of the chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/kkulig/moax9L8u/

#### Affected browser(s)
All

**Comment by dstrickler** [comment]
I can confirm this bug as well, and that setting the legend "useHTML: false" gets around the bug.

**Comment by pawelfus** [comment]
Responsible commit: b0cb1ef

**Comment by PrzemekNiedziela** [comment]
Will this correction be included to next version of HighCharts? When will it be available?

**Comment by pawelfus** [comment]
Yes, this fix will be included in the next release. We don't have ETA for the next version, it should be released within a few weeks.

**Comment by TorsteinHonsi** [comment]
@PrzemekNiedziela, we are aiming at a release this week.

**Comment by binarybaba** [comment]
I'm on 6.0.7. Got the same issue. Is there anyone else or just me?

**Comment by pawelfus** [comment]
Issue should be fixed in v6.0.7, take a look: http://jsfiddle.net/BlackLabel/moax9L8u/1/ 

Could you recreate issue in jsFiddle? We will take a look, thanks!
