### ISSUE TITLE
Setting softMin/softMax does not allow to zoom chart correctly

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#7226]
#### Behaviour
Setting softMin and/or softMax properties does not allow to zoom chart correctly (or at all), even when minRange is set to small value.

#### Live demo
http://jsfiddle.net/pzLug7vp/

**Comment by KacperMadej** [comment]
On one side API reference says that extremes are kept due to setting the options on the other hand zooming would should work. One way would be to add more info to the API reference and another could be to allow zoom when soft[Min|Max] are set.

**Comment by WellyGus** [comment]
Plus one for allowing zoom please.
(We have people mangling my data trying to enforce softMin/Max like behaviour.)

**Comment by KacperMadej** [comment]
@TorsteinHonsi Could take a look and decide the label for the issue? Enhancement?

**Comment by TorsteinHonsi** [comment]
I agree it's a bug. It should behave like `min` and `max` in this case.

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/pzLug7vp/1/
