### ISSUE TITLE
Column or bar chart with only negative values doesn't render bars

### ISSUE THREAD

**Issue by Sphinxxxx** [highcharts/highcharts#7228]
In version 6, if a column (or bar) chart has **only negative** values, the bars aren't rendered until you force a refresh, e.g. by resizing the window or hiding one of the series.

#### Live demo with steps to reproduce
http://jsfiddle.net/dpnv7g2m/

#### Affected browser(s)
Chrome/Firefox/Edge

**Comment by pawelfus** [comment]
Hi @Sphinxxxx 

Thank you for reporting this bug! It's a regression since c4fef24 used to work fine in v5.
