### ISSUE TITLE
Title problem in example

### ISSUE THREAD

**Issue by subshark** [highcharts/highcharts#7229]
#### Expected behaviour
Nothing

#### Actual behaviour
Title removed when click on center of graph

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/sunburst

When click into graph center, all titles is removed.

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @subshark 
Thank you for the reporting.

**Comment by subshark** [comment]
You close topic, but problem did not go away. Try click in center of chart  https://www.highcharts.com/demo/sunburst , and the titles go away.

**Comment by jon-a-nygaard** [comment]
Hi @subshark 

The issue gets auto-closed when the fix is picked into our master branch. Which means that the fix will be included in our next release. Highcharts v6.0.2 will be released soon, and then the problem should be gone.

Best regards
