### ISSUE TITLE
How to add right space in stock chart

### ISSUE THREAD

**Issue by eakkasit** [highcharts/highcharts#7230]
#### Expected behaviour

I want to add right space same trading finance , I wan't to add null series but isn't work
#### Actual behaviour

![05-10-60 11-04-22](https://user-images.githubusercontent.com/7508045/31210555-39cf6a6e-a9bd-11e7-98c4-b5ebbddd36ce.jpg)

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/dynamic-update/

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

PS: Check out our new `overscroll` feature: http://api.highcharts.com/highstock/xAxis.overscroll
