### ISSUE TITLE
Metegram Not Working For All Location 

### ISSUE THREAD

**Issue by rbishwajit** [highcharts/highcharts#7231]
Metegram Highchart is only working for London location and not for any other issue. 

I am aware the jsonp.php should be placed in my own server to make it work.

But i am using highcharts with pentaho server which is tomcat apache. 

Please guide how to use metegrams on apache server for all locations

**Comment by sebastianbochan** [comment]
Github is our bugtracker, so please use forum / stackoverflow or email for the support cases. 
You can find more informations about the support [here](http://www.highcharts.com/support)
