### ISSUE TITLE
ScrollBar functionality  on HighCharts

### ISSUE THREAD

**Issue by JackMstry** [highcharts/highcharts#7232]
#### Expected behaviour
I have a situation where I have to create multiple instance of piechart within single container.

#### Actual behaviour
Multiple instance of pie is generated but some of the pie instance are hide inside the container

#### Live demo with steps to reproduce
http://jsfiddle.net/qnj39ume/193/

**Comment by sebastianbochan** [comment]
Hi @JackMstry,
In the case that you set pie chart out of container it is not displayed and you need to take care about the right center position.

The scrollbar functionality is available only in the Highstock.

**Comment by JackMstry** [comment]
Thanks :)
