### ISSUE TITLE
treemap.levelIsConstant option works in opposite to documentation

### ISSUE THREAD

**Issue by Malczewski** [highcharts/highcharts#7233]
#### Expected behaviour
From documentation http://api.highcharts.com/highcharts/plotOptions.treemap.levelIsConstant :
When treemap.levelIsConstant is true, level will be the same as the tree structure.
When treemap.levelIsConstant is false, first level visible when drilling is considered to be level one.

#### Actual behaviour
Vice versa

#### Live demo with steps to reproduce
Click on any node - style(e.g. align) of child nodes shouldn't change with levelIsConstant=true
6.0.0 - http://jsfiddle.net/Yurim/xa44pzpb/
4.2.7 - http://jsfiddle.net/Yurim/a97sw4nw/

#### Affected browser(s)
All

According to this commit, the behavior has got reversed:
https://github.com/highcharts/highcharts/commit/effdecee98f220653592ca5decc123f595a01e8c#diff-30af5c1a1413ede5f12b9670da851a61R450

**Comment by pawelfus** [comment]
Thank you for reporting!

**Comment by hon2a** [comment]
Please note that the issue was introduced in version `5.0.13`. I'd suggest removing the `6.0` mention from this issue's title.
