### ISSUE TITLE
Render problem in version 5.0.13 and 5.0.14 

### ISSUE THREAD

**Issue by GuilhermeErmel** [highcharts/highcharts#7234]
The problem started happen in version 5.0.13 and still happens in 5.0.14.

#### Live demo with steps to reproduce
https://codepen.io/ermel/pen/BwJRoR

**Comment by pawelfus** [comment]
Hi @GuilhermeErmel 

Thank you for reporting. It is already fixed in v6: https://codepen.io/anon/pen/MEQYbJ
