### ISSUE TITLE
Version 6 of HighCharts and html legends

### ISSUE THREAD

**Issue by Bill-VA** [highcharts/highcharts#7236]
With versions prior to version 6, using the useHTML:true option would display the legend in a nearly identical manner.

The legend labels are all bunched up in the upper-left corner

http://jsfiddle.net/td8qu1zo/

All browsers it seems.

**Comment by Bill-VA** [comment]
As a followup, here's a version of that fiddle using version 5.0.14 of highcharts.js
http://jsfiddle.net/td8qu1zo/1/

**Comment by pawelfus** [comment]
Hi @Bill-VA 

Thanks! It's a duplicate of #7224
