### ISSUE TITLE
Sunburst chart is not responsive

### ISSUE THREAD

**Issue by shicechi** [highcharts/highcharts#7237]
#### Expected behaviour
On window/container resize, sunburst chart should be resized and centered.

#### Actual behaviour
Sunburst chart shifts instead.

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/sunburst/
Can be produced by resizing the result section to a smaller size.

#### Affected browser(s)
Tested on Chrome Version 61.0.3163.100 (Official Build) (64-bit) on macOS

**Comment by pawelfus** [comment]
Thank you!
