### ISSUE TITLE
Updating dataLabel's connector color

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#7243]
Connector to the dataLabel should be updated when using `point.update({ color: newColor });`. At this moment, color doesn't change.

#### Live demo with steps to reproduce
http://jsfiddle.net/k7r0s5km/8/

#### Workaround
Destroy connector before updating point: 

    point.connector = point.connector.destroy();

Demo: http://jsfiddle.net/k7r0s5km/7/

**Comment by taalas** [comment]
Thanks for providing a workaround for this issue. Works perfectly in my case until this is fixed.
