### ISSUE TITLE
showCheckbox doesn't work

### ISSUE THREAD

**Issue by callumacrae** [highcharts/highcharts#7245]
#### Expected behaviour

showCheckbox does something

#### Actual behaviour

showCheckbox does nothing

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-showcheckbox-true/

1. Click on a checkbox
2. Nothing has happened

#### Affected browser(s)

Chrome 61.0.3163.100

**Comment by pawelfus** [comment]
Hi @callumacrae 

Thank you for contacting us. This is not a bug, `checkbox` **selects** a series. You can see that series with `selected` flag set to true has the checkbox selected too, [docs](http://api.highcharts.com/highcharts/plotOptions.series.showCheckbox):

> If true, a checkbox is displayed next to the legend item to allow selecting the series. The state of the checkbox is determined by the selected option.

**Comment by callumacrae** [comment]
Ah right, sorry! Misunderstood.

**Comment by pawelfus** [comment]
Not a problem! :)
