### ISSUE TITLE
Flag tooltips not working

### ISSUE THREAD

**Issue by dattusdwaltz** [highcharts/highcharts#7246]
#### Expected behaviour
Hovering over a flag should display a tooltip containing the value of the text key.

#### Actual behaviour
Hovering over a flag does not display anything.

#### Live demo with steps to reproduce
[Official Highstock Flags Demo](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/flags-shapes/)

Hover your mouse over a flag.

#### Affected browser(s)
Chromium 61
Firefox 57

**Comment by pawelfus** [comment]
Hi @dattusdwaltz 

Thank you for reporting! 

**Workaround:**
Use `shared` tooltip instead of `split` one: http://jsfiddle.net/7g1kb842/
