### ISSUE TITLE
Boost with arearange is distorted 

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#7247]
Arearange chart is distorted. 
https://jsfiddle.net/onemenny/06srgpxw/

when disabling the seriesThreshold SVG gives the correct draw, but with seriesThreshold=1 the chart is completely off. I cannot understand the reason. 

Also, for arearange I believe the fillOpacity is important, especially when combined with other series (line chart) in the same chart. I noticed that if fillOpacity is set the series cannot be seen at all 

The boost module draws the line with 1 pixel width, this could be problematic if you wish to emphasise parts of your line chart. Since boost is missing the option to use zones, you are left with the option to add (on top) another series to emphasis. While you can toggle the boost for a specific series, I find it cumbersome code wise, and I would like to see the lineWidth taken into account.

**Comment by cvasseng** [comment]
Thanks for reporting, we're looking into it.

`fillOpacity` should work for both `area` and `arearange` (https://jsfiddle.net/06srgpxw/1/), do you remember the value(s) you tried setting it to?

Also, could you please elaborate on why you find it cumbersome to use `series.boostThreshold` to get seamless transitions from boosted mode to regular mode?

Not much we can do about `lineWidth` at present time I'm afraid - setting the line width in WebGL is not properly supported by most browsers.

Thanks!

**Comment by onemenny** [comment]
Thanks,

fillOpacity: https://jsfiddle.net/onemenny/131wmL04/ once setting it on a series the series is not displayed at all, It may be related to the main "distorted" issue

The cumbersome is not a result of series.boostThreshold usage, its a result of emphasising a zone in the line chart. Since zones are not supported, and (apparently) lineWidth as well. So if I want to emphasis a zone on the chart I need to add another series overlaying with a different lineWidth for mimicking a zone. Doing that requires me to set the series.boostThreshold for a specific series and not just for the whole chart (for me it's kinda related to [this](https://github.com/highcharts/highcharts/issues/6842): 

So even if the lineWidth is not supported in all browsers I would expect it to work where it can IMO. Otherwise the chart will look totally different after zoom, or when ditching SVG all-together.

**Comment by cvasseng** [comment]
Yes - looks like the `fillOpacity` is related to the other issue you're having.

Thanks for clarifying, I understand what you mean now.  

We intentionally disabled line width for all browsers to avoid rendering differences between them (it only works properly in Firefox, and to some extent, Edge). We'll consider enabling it though.
