### ISSUE TITLE
Labels in polar chart are cut

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#7248]
#### Expected behaviour
The xAxis labels are aligned correctly.

#### Actual behaviour
The xAxis labels are cut.

The latest working version is 5.0.6.

#### Live demos
http://jsfiddle.net/853q77q7/ - labels are cut (the latest version)
http://jsfiddle.net/n9g7rej7/ - labels are correctly aligned (v5.0.6)

**Comment by pawelfus** [comment]
Hm.. for me in both versions labels are cut, but a bit different:

5.0.6: 
![screen shot 2017-10-10 at 11 18 57](https://user-images.githubusercontent.com/1453926/31378880-ee0c6944-adac-11e7-82d7-1c65fd272cd2.png)

Current:
![screen shot 2017-10-10 at 11 18 52](https://user-images.githubusercontent.com/1453926/31378890-f566b960-adac-11e7-9174-bca14fc17c65.png)

**Comment by gerbenvd** [comment]
For me the labels are also cut the wrong way in the latest version:

**Live demo**
http://jsfiddle.net/ne80rk3w/3/

**Comment by gerbenvd** [comment]
@PaulDalek Hi Paul, did you in the end manage to cope with this? I've decided to downgrade to 5.06 which doesn't seem the best solution, but at least it is working for now...
