### ISSUE TITLE
API Page missing

### ISSUE THREAD

**Issue by ajain17** [highcharts/highcharts#7251]
#### Expected behaviour
http://api.highcharts.com/highcharts/series%3Cline%3E.legendIndex
This should load

#### Actual behaviour
It gives 404. Is it deprecated? Can't find any references online.

#### Affected browser(s)
Chrome, Edge

**Comment by pawelfus** [comment]
Hi @ajain17 

URL is wrong, it should be: http://api.highcharts.com/highcharts/series.line.legendIndex

**Comment by jon-a-nygaard** [comment]
@cvasseng Is this a duplicate? If so could you reference the original issue and close this one.

**Comment by cvasseng** [comment]
@jon-a-nygaard: not a duplicate as far as I'm aware.

@ajain17: we're now redirecting the old format (`series<x>.y`) to the new style (`series.x.y`), so hopefully you will no longer get any 404's.
