### ISSUE TITLE
Long legend title is not wrapped, causing cropped overflow on both sides

### ISSUE THREAD

**Issue by hon2a** [highcharts/highcharts#7253]
#### Expected behaviour

Long legend title is either automatically line-wrapped (optimal) or at least overflows only to the right (sub-optimal). In any case, it shouldn't affect horizontal positioning and visibility of legend items.

#### Actual behaviour

Long legend title causes the whole legend to overflow to both sides, causing not only the title but also the overflowing legend items to be cropped (leading to partial or complete inacessibility).

#### Live demo with steps to reproduce

[See the demo.](http://jsfiddle.net/hon2a/s5tvjyL8/)

#### Affected browser(s)

All.

**Comment by pawelfus** [comment]
Hi @hon2a 

Thanks you for reporting, you are right it's broken.

**Workaround:**
Demo: http://jsfiddle.net/s5tvjyL8/3/ 

*Internal note:*
In the workarund, we apply width of the container. Interesting fact, we need to set text again, otherwise it won't update bounding box and `getBBox()` will return old values.

**Comment by hon2a** [comment]
Thanks for the work-around, but we'll likely wait for the fix to be released as this issue should only manifest for us in testing and not in production at this point (because of different lengths of the title text).

**Comment by ramod8** [comment]
any update on this?

**Comment by sebastianbochan** [comment]
Hi @ramod8,
At this moment the issue is still valid. You can use @pawelfus' workaround or set CSS styles and the [width](https://api.highcharts.com/highcharts/legend.width) of the legend by the option. 

**Demo**
- http://jsfiddle.net/BlackLabel/4th5fL9e/

**Comment by TorsteinHonsi** [comment]
Thanks for asking, we pushed a fix for this issue now. 

* Original demo with the fix applied: http://jsfiddle.net/highcharts/hva5tm76/
* Original demo with the fix and `textOverflow: 'ellipsis'`: http://jsfiddle.net/highcharts/hva5tm76/2/
