### ISSUE TITLE
Exporting - allowHTML - wrong positions of datalabels

### ISSUE THREAD

**Issue by PrzemekNiedziela** [highcharts/highcharts#7254]
#### Expected behaviour
After download get the same image as I see on HTML page.

#### Actual behaviour
DataLabels are on left top corner on downloaded image. If I set allowHTML to false then dataLabels are in correct positions, but HTML chars like '&#8680;' are not rendered.

#### Live demo with steps to reproduce
http://jsfiddle.net/c6cvbta7/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @wizard8912 

Thanks! This looks like a regression, in v5 this used to work: http://jsfiddle.net/c6cvbta7/1/

Related to: #7224
