### ISSUE TITLE
Highstock series.setVisible(false/true, false) triggers chart.events.redraw

### ISSUE THREAD

**Issue by rrdnd** [highcharts/highcharts#7256]
#### Expected behaviour
When the second parameter of ``series.setVisible`` is set to false, it should not trigger the redraw event.

#### Actual behaviour
``series.setVisible`` triggers the redraw event

#### Live demo with steps to reproduce
https://jsfiddle.net/rredondo/x8pzoqtv/
1. Open the console of the browser's debug tools
2. Click the "Toggle Series" button

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thanks!
