### ISSUE TITLE
New and old dump.json differences, missing fields

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#7258]
General issue to report issues/changes with JSON's and missing fields in the API.

**Comment by pawelfus** [comment]
1. Heatmap is missing `data.x` and `data.y` (only in Highcharts): http://api.highcharts.com/highcharts/series.heatmap.data

2. Navigator `handles.width` has wrong class (`umber`): 
http://api.highcharts.com/highstock/navigator.handles.width

3. Old dump used to generated `Array<Object|Number>` now we have `Array.<(Object|Number)>`

4. Missing `yAxis.title.text` in Highstock: http://api.highcharts.com/highstock/yAxis.title

5. Missing `plotOptions.solidgauge.dataLabels.useHTML` : http://api.highcharts.com/highcharts/plotOptions.solidgauge.dataLabels

6. Missing description+types for `pane.background.backgroundColor.stops`: http://api.highcharts.com/highcharts/pane.background.backgroundColor.stops

7. Missing `series.heatmap.borderWidth` for Highcharts: http://api.highcharts.com/highcharts/series.heatmap

8. Missing `yAxis.labels.style.fontFamily`: http://api.highcharts.com/highcharts/yAxis.labels.style

9. We can not distinct which demo belongs to which product, for example we have `products: [highcharts, highstock]` and demos are just a simple string: `demo: "<demo1> \n <demo2>`. We need a solution for this.

10. Duplicated the same demo for `` in the dump (http://api.highcharts.com/highcharts/series.area.data.dataLabels ) : 
```
{
    "description": "<p>Individual data label for each point. The options are the same as\nthe ones for <a href=\"#plotOptions.series.\ndataLabels\">plotOptions.series.dataLabels</a></p>\n",
    "parent": "series<area>-data",
    "title": "dataLabels",
    "demo": "<a href=\"https://jsfiddle.net/gh/library/pure/highcharts/highcharts/tree/master/samples/highcharts/point/datalabels/\">Show a label for the last value</a>\n<a href=\"https://jsfiddle.net/gh/library/pure/highcharts/highcharts/tree/master/samples/highcharts/point/datalabels/\">Show a label for the last value</a>",
    "isParent": false,
    "deprecated": false,
    "returnType": "Object",
    "seeAlso": "",
    "products": [
      "highcharts",
      "highstock"
    ],
    "name": "series<area>-data--dataLabels",
    "fullname": "series<area>.data.dataLabels"
  }
```

11. Descriptions for `xAxis` and `yAxis` are wrong: http://api.highcharts.com/highcharts/xAxis + http://api.highcharts.com/highcharts/yAxis (it looks like 3D replaced these descriptions).

**Comment by pawelfus** [comment]
- [ ] 12. Missing products in many places e.g. `plotOptions-ad-tooltip--footerFormat` (only bugfix)

**Comment by morganfree** [comment]
- [x] 13. Typo in http://api.highcharts.com/highcharts/annotations.labelOptions.style.fontWeigth.html

**Comment by pawelfus** [comment]
- [ ] 14. Mismatched types:
Example: 
http://api.highcharts.com/highcharts/plotOptions.pyramid.dataLabels.x - Boolean -> Number, full list:

series<sunburst>.dataLabels.x
plotOptions.pyramid.dataLabels.x
series<funnel>.dataLabels.x
plotOptions.sunburst.dataLabels.x
plotOptions.pie.dataLabels.x
series<pyramid>.dataLabels.x
series<pie>.dataLabels.x
series<variablepie>.dataLabels.x
plotOptions.variablepie.dataLabels.x
plotOptions.funnel.dataLabels.x

- [ ] 15. `data` under plotOptions:

- http://api.highcharts.com/highcharts/plotOptions.tilemap.data
- http://api.highcharts.com/highcharts/plotOptions.xrange.data

**Comment by pawelfus** [comment]
- [ ] 16. Double type for: http://api.highcharts.com/highcharts/drilldown.animation.duration.html - should be just Number

**Comment by pawelfus** [comment]
- [ ] 17. `animation` objects are defined as `Object|Boolean`,  but `states.hover.animation` is missing that definition

**Comment by pawelfus** [comment]
- [ ] 18. Wrong types in sunburst for `plotOptions.sunburst.levels.colorVariation.to`, `plotOptions.sunburst.levels.borderColor`, `plotOptions.sunburst.levels.color` and `plotOptions.sunburst.levels.borderWidth`

**Comment by pawelfus** [comment]
- [ ] 19. Missing `treemap.colorByPoint` and `treemap.colors`

**Comment by pawelfus** [comment]
Closing the issue, the remaining issues are manually corrected in the wrappers' generators.
