### ISSUE TITLE
series-label module: long rendering time with multiple series and points

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7259]
#### Actual behaviour
Browser / chart is frozen for few seconds while series labels positions are being calculated.

#### Expected behaviour
An enhancement suggestion: 
After N milliseconds the module could give up and render labels in an to-so-perfect position or could give up on points collision points detection to avoid the freeze. The N could be set from options.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5n9z65qf/

**Comment by TorsteinHonsi** [comment]
That's a good suggestion. We could also add async looping like we're doing in the canvas boost.

**Comment by sebastianbochan** [comment]
Related to: 
- https://github.com/highcharts/highcharts/issues/9815

The current version has high performance and problem is not visible.
