### ISSUE TITLE
Panning chart and date input

### ISSUE THREAD

**Issue by slawekkolodziej** [highcharts/highcharts#726]
I'm not really sure if it's an issue or something related with dataGrouping, anyway:
1. Open this demo: http://jsfiddle.net/hfrntt/SaYVY/
2. Put this date in "from" input: 09/23/2009 and hit return
3. Usually date input changes to other day (sometimes 21st, sometimes 22nd)
4. When you pan chart to the left and then back to the right, date input will show you 17th -18th or something similar

**Comment by KacperMadej** [comment]
The problem is not possible to recreate. I have tried with different dates on small chart (to force dataGrouping), but without success. If the problem is possible to recreate in a JSFiddle demo, please add a demo and the issue will be reopened.
