### ISSUE TITLE
Skip Irregular time intervals incase of Multiple serieses

### ISSUE THREAD

**Issue by anjareddy** [highcharts/highcharts#7262]
#### Expected behaviour
I have multiple series to show in chart, and need to skip the irregular timeintervels. But here if one series has data for a time interval and others are not, in this case the serieses which are not having data for that interval is getting splitted.

#### Actual behaviour
All serieses data should be connected.

**Comment by pawelfus** [comment]
Hi @anjareddy 

Your case doesn't sound like a bug, have you reached our [support](https://www.highcharts.com/support) team? I think you should set `connectNulls` to true, but it really depends on your chart config. Could you recreate issue in jsFiddle? Thanks!

**Comment by anjareddy** [comment]
https://jsfiddle.net/x9f1obge/

**Comment by anjareddy** [comment]
https://jsfiddle.net/x9f1obge/2/

**Comment by anjareddy** [comment]
Hi pwael,
Please use this js fiddle:
https://jsfiddle.net/x9f1obge/3/

**Comment by pawelfus** [comment]
Hi @anjareddy - unfortunately, your demo doesn't work.

**Comment by anjareddy** [comment]
Sorry Pawel, 
there was an issue, I have updated now.

https://jsfiddle.net/x9f1obge/8/

X-Axis values are not showing
Data is not getting plotted correctly
Zoom buttons on top are also not working properly.

**Comment by pawelfus** [comment]
Hi @anjareddy 

You have errors in the console: Highcharts error #15: www.highcharts.com/errors/15 

> Highcharts Error #15
>
> Highcharts expects data to be sorted
>
> This happens when you are trying to create a line series or a stock chart where the data is not sorted in ascending X order. For performance reasons, Highcharts does not sort the data, instead it is required that the implementer pre-sorts the data.

Please, sort your data, then it works fine: https://jsfiddle.net/nu8b1bpm/

**Comment by anjareddy** [comment]
Thanks Pawel, it is working now, showing the x-axis data but why the zoom buttons are not working?

**Comment by pawelfus** [comment]
Hi @anjareddy 

Please, contact with out support team, they will explain with details how exactly this works.
