### ISSUE TITLE
No-data-to-display label shows when word cloud chart has data plotted and visible.

### ISSUE THREAD

**Issue by peter-stoyanov** [highcharts/highcharts#7264]
#### Expected behaviour
When data is present and visible in the plot area of a Wordcloud type chart there should be no "No data to display" label rendered.

#### Actual behaviour
"No data to display" label is overlapping with the actual data.

#### Live demo with steps to reproduce
The issue is visible in the following js fiddle:

http://jsfiddle.net/peshoStoyanov/xq1sz6q7/4/

#### Affected browser(s)
Tested only on Google Chrome
Version 61.0.3163.100 (Official Build) (64-bit)

#### Debugging
I am new to highcharts but when I debugged the source code I think the issue is in these lines:

~~~~javascript
/**
* Define hasData functions for series. These return true if there are data
* points on this series within the plot area.
*/
H.Series.prototype.hasData = function() {
    return this.visible && this.dataMax !== undefined && this.dataMin !== undefined; // #3703
};
~~~~

For my wordcloud chart hasData() returns false, due to this.dataMax and this.dataMin  being undefined.

**Comment by pawelfus** [comment]
Hi @peter-stoyanov 

Thanks for reporting this bug! 

**Workaround:**
Overwrite `hasData` method:

```
Highcharts.seriesTypes.wordcloud.prototype.hasData = function () {
	return this.visible && this.points.length > 0;
};
```

Demo: http://jsfiddle.net/xq1sz6q7/6/
