### ISSUE TITLE
Data module: endRow is cutting off last row of data

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7265]
#### Expected behaviour
When endRow is set to e.g. 2, then 3th row of data should be used (because indexed from 0, as explained in API docs).

#### Actual behaviour
When endRow is set to 2 then 1st row is the last used data row.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/hr6j17eq/

**Comment by TorsteinHonsi** [comment]
It's a regression, it worked in v5: http://jsfiddle.net/hr6j17eq/1/

**Comment by cvasseng** [comment]
Sorry, I misread, looked like you referenced the other issue, so I fixed this too. Same solution though, so should merge fine.
