### ISSUE TITLE
boost + series-label = no series labels on boosted chart

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7266]
#### Behaviour
series-label module doesn't render series labels on boosted chart when using boost module

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/vz34npxj/1/

0. No series labels
1. Zoom in to see series labels
2. Zoom out and the labels are not adjusted nor removed

@cvasseng

**Comment by cvasseng** [comment]
Explicit support for `series-label` is non-existent in boost.

@TorsteinHonsi, should this be prioritized after The Cloud, or what do you think?

**Comment by nilsm0hr** [comment]
Is there any possibility that you enable series-labels on boosted series? It doesn't need to be as elegant as the current solution, but some labels close to a line would be quite nice.

**Comment by TorsteinHonsi** [comment]
We already process a subset of the points when be build the k-d-tree for the tooltip, so it should be possible to use these interpolated data points as base for the series labels.

**Comment by KacperMadej** [comment]
+1
