### ISSUE TITLE
linkedTo does not work properly when numeric ids are used for data series in line chart

### ISSUE THREAD

**Issue by DmitryPorotov** [highcharts/highcharts#7267]
#### Expected behaviour
https://fiddle.jshell.net/oxbm6mke/6/
Clicking on "Series 1" legend hides series 1 and series 2.

#### Actual behaviour
https://fiddle.jshell.net/oxbm6mke/7/
Clicking on "Series 1" legend does not hide both series. Hovering works OK though.

#### Affected browser(s)
Tested on Chromium Version 61.0.3163.100 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit) and Firefox 56.0 (64-bit)
Probably works the same on all browsers.

**Comment by pawelfus** [comment]
Hi @DmitryPorotov 

[`linkedTo`](http://api.highcharts.com/highcharts/plotOptions.series.linkedTo) option should be a string: 

> linkedTo: String
>
> The id of another series to link to. Additionally, the value can be ":previous" to link to the previous series. When two series are linked, only the first one appears in the legend. Toggling the visibility of this also toggles the linked series.
>
> Defaults to undefined.

It probably works for CSS version, because CSS doesn't see the difference between a number and a string in class names :)
