### ISSUE TITLE
X-range chart without color in highstock

### ISSUE THREAD

**Issue by t-ishimura** [highcharts/highcharts#7269]
In highstock version 6, X-range chart has some problems.

#### Expected behaviour
1. Each X-range bar draw by some colors.
2. The label in X-range bar with partialFill can read.
3. All tooltips on bar will show when mouse cursor over.

#### Actual behaviour
1. Each X-range bar draw with out color.
2. The label in X-range bar with partialFill can't read, e.g. Prototyping category in the live demo.
3. Some tooltips with same x data never shown, e.g. In first bar on Development category tooltip.

#### Live demo with steps to reproduce
http://jsfiddle.net/yt0jdp1y/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @t-ishimura 

The problem is you use `js` version of Highstock with `styled` version of nodules. Using `styled` Highstock results in a good chart: http://jsfiddle.net/yt0jdp1y/1/

**Comment by t-ishimura** [comment]
Thank you, @pawelfus 

Problem 1. and 2. is solved. However 3. is not solved.
When move the mouse cursor to the left bar on Development category, the tooltip is not shown.

**Comment by pawelfus** [comment]
You are right, my mistake, sorry! This is caused by `split` tooltip - it's intended to work with point with the same x-values, not x-ranges. When disabling, it's fine: http://jsfiddle.net/yt0jdp1y/1/

**Comment by t-ishimura** [comment]
I was convinced. Thank you!
