### ISSUE TITLE
Stack total tooltip doesn't show thousand separator

### ISSUE THREAD

**Issue by msaltieri** [highcharts/highcharts#7270]
I modified the [stacked column chart demo](http://jsfiddle.net/mk2kk8tc/) by increasing the numbers involved to show that the total of each column doesn't have the thousand separator inside the tooltip.

For comparison, just note that the `point.y` value is not affected by the same issue which probably is not browser dependent.

**Comment by pawelfus** [comment]
Hi @msaltieri 

Thanks for reporting! 

**Solution:**
Enable thousands separator in the template:
```
    tooltip: {
        headerFormat: '<b>{point.x}</b><br/>',
        pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal:,.0f}'
    },
```
Demo: http://jsfiddle.net/mk2kk8tc/1/

**Comment by msaltieri** [comment]
Thank you @pawelfus for your quick response!

I opened the issue just because I thought enabling the thousand separator should be a default behavior in `stackTotal`s. Anyway your solution works great and achieves the aim.
