### ISSUE TITLE
Highstock Shared tooltip is not working 

### ISSUE THREAD

**Issue by tiwarishrijan** [highcharts/highcharts#7271]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/6523607/31544557-fce37500-b038-11e7-972b-b067b0ba7965.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/6523607/31544569-10a8d6d4-b039-11e7-96c8-e192340e9f2f.png)

#### Affected browser(s)
All Browsers

**Comment by pawelfus** [comment]
Hi @tiwarishrijan 

Since Highstock v6, by default [`tooltip.split`](http://api.highcharts.com/highstock/tooltip.split) is set to `true`, you can disable this by setting to `false`.
