### ISSUE TITLE
Color axis marker on treemap blinking or disappearing completely

### ISSUE THREAD

**Issue by hon2a** [highcharts/highcharts#7274]
#### Expected behaviour

When I drill into a treemap chart and move the mouse over it, the color axis marker should be seamlessly jumping from one place to another. While the mouse is moving over the same point, it shouldn't blink or disappear.

#### Actual behaviour

This should've been fixed in #6763 (and it's certainly much better), but when I open up a multi-level treemap chart with bigger than demo-sized data, drill in and move the mouse over the points, the color axis marker ("crosshair") is blinking. When I move the mouse directly underneath the tooltip arrow, the color axis marker disappears completely.

### Notes

* I'd guess that the root cause is likely different from the one fixed in #6763.
* The blinking is best observable in Internet Explorer.
* The complete disappearance when mouse is directly under the tooltip arrow might have something to do with #7233.

#### Live demo with reproduction steps

* [Demo with bigger data to showcase blinking](http://jsfiddle.net/hon2a/pobag7v2/) - just move the mouse over the chart in IE
* [Small demo to showcase disappearance](http://jsfiddle.net/hon2a/ngsm8jjc/1/) - drill in and move mouse cursor _exactly_ over the point of the tooltip arrow

#### Affected browser(s)

All (but most affected is Internet Explorer, likely for performance reasons)

**Comment by PaulDalek** [comment]
Sorry but I am unable to reproduce the problem. Is marker blinking when you hover over data label of a specific point? I think that hovering over parent should not display color axis marker because it has no value. It should display only when you hover directly over the single point or its label. Hovering on points in both demos sent by you, results in displaying color axis marker correctly. Could you provide us with a gif presenting described behaviour? Tested on IE11 and Chrome 61.0.3163.100, Windows 8.1 x64.

**Comment by hon2a** [comment]
After re-testing this I found that I can only reproduce the second part of the issue (disappearance) and the blinking I was observing in the demo might have been caused by moving the mouse over the spot where the marker disappears (I'll try to create a video of that). The blinking when moving the mouse anywhere must be caused by something else in our real use case then.

**Comment by hon2a** [comment]
Here's a GIF of the cursor disappearing:

![highcharts-treemap-marker-disappearance](https://user-images.githubusercontent.com/2254160/31609562-03e2deca-b275-11e7-8536-b04b8def1200.gif)

Note that I'm drilled in as deep as possible. The "Others" label belongs to an ancestory, but the places where the marker disappears are where the labels for the points themselves should be.

**Comment by PaulDalek** [comment]
It seems indeed that the marker disappears when you hover over places where data labels should be but from what I checked it concerns v5.0.14. In the newest version (v6.0.1) this issue is fixed.

**Comment by hon2a** [comment]
Ah, I must've missed the release of the new version. I'll check it out tomorrow and close this if it works in the latest release.

**Comment by hon2a** [comment]
It looks like this is indeed fixed already in `6.0.1`, so I'm closing the issue.

Unfortunately, we still can't use the `6.0.1` and the fix because of #7233.
