### ISSUE TITLE
x-axis labels are hidden in scatter chart with x-axis breaks

### ISSUE THREAD

**Issue by suganya-suvadi** [highcharts/highcharts#7275]
x-axis labels do not show up on a scater chart with x-axis breaks
http://jsfiddle.net/foj1mwu6/

Using the same fiddle with the issue, there are 2 scenarios in which the x-axis labels show up fine - 
1. When chart type is line - http://jsfiddle.net/2a4yx6bz/
2. When there are no breaks in x-axis - http://jsfiddle.net/azyy9tq2/

(The **only** difference between the original fiddle and the 2 fiddles above are the changes described)

For a minute, I considered this could be a duplicate of #6870, but unlike that issue, the labels show up fine for the same data when the changes listed above are made.

* Version of Highcharts used - 5.0.12
* Issue exists in 6.0.1 as well - http://jsfiddle.net/jrteqwwn/

**Comment by pawelfus** [comment]
Hi @suganya-suvadi 

Thank you! Minified demo: http://jsfiddle.net/u7pksfjs/

**Workaround:**
Use line series which looks exactly like a scatter one: http://jsfiddle.net/u7pksfjs/1/

Code:
```
    marker: {
      enabled: true,
      radius: 4
    },
    states: {
      hover: {
        lineWidthPlus: 0
      }
    },
    lineWidth: 0
```

**Comment by TorsteinHonsi** [comment]
For whatever reason, it is the `noSharedTooltip` prototype property that makes the difference: http://jsfiddle.net/highcharts/u7pksfjs/2/

**Comment by suganya-suvadi** [comment]
@pawelfus, thanks for the workaround!

And I should have mentioned this earlier, but this occurs in polygon series as well.
