### ISSUE TITLE
Loading CSV data using papa parse and displaying chart with ReactHighcharts

### ISSUE THREAD

**Issue by nadim** [highcharts/highcharts#7277]
I'm trying to recreate this using ReactHighcharts:
http://jsfiddle.net/mhbf5b2g/

I pass in the exact same config object yet nothing renders. Is this supposed to work and if so, what am I doing wrong?

<ReactHighcharts config={config} /> (config object same as in fiddle above)

Latest Chrome on Mac OS X.

**Comment by pawelfus** [comment]
Hi @nadim, please contact with our support team ([details](https://www.highcharts.com/support)). We use github issues as bug reports.
