### ISSUE TITLE
Zoom animation not working for some charts

### ISSUE THREAD

**Issue by goodforenergy** [highcharts/highcharts#7278]
Hey there,

I recently noticed some of our charts weren't animating on zoom. It only seems to happen when a certain number of series and / or points are present. If you set

```
chart: {
    animation: true
}
```

zoom animation works as expected - but I took this out on advice from you to fix the bug seen in https://github.com/highcharts/highcharts/issues/6742. I figured as it defaults to true it shouldn't make a difference, but it does.

Side note - I was going to ask on the forums in case this is a config issue, but I tried to register back on the 10th and never got a follow up email to say my account was activated. I just tried again today.

#### Expected behaviour
Chart animates on zoom by default.

#### Actual behaviour
Chart zoom animation missing (with certain configuration).

#### Live demo with steps to reproduce
* Load the fiddle: http://jsfiddle.net/goodforenergy/e7r7dkfz/
* Zoom in on the chart

#### Affected browser(s)
Chrome (only browser tested).

**Comment by pawelfus** [comment]
Hi @goodforenergy 

Thank you for reporting issues! Regarding forum, could you contact with us by email? See [details](https://www.highcharts.com/support).

Regarding the issue, we have this defined here: 

https://github.com/highcharts/highcharts/blob/b39922516cdad8a880a7b8dbe13c23b4427deeb8/js/parts/Interaction.js#L382-L386

`chart.pointCount < 100` disables the animation. We can try to change that value manually in `load` and `redraw` events: http://jsfiddle.net/e7r7dkfz/1/

```
  chart: {
    //	animation: true,
    zoomType: 'x',
    events: {
      load: function() {
        this.pointCount = 1;
      },
      redraw: function() {
        this.pointCount = 1;
      }
    }
  },
```

**Comment by goodforenergy** [comment]
Thanks for the quick response @pawelfus! Appreciate all your work.
