### ISSUE TITLE
CSS transforms and navigator

### ISSUE THREAD

**Issue by slawekkolodziej** [highcharts/highcharts#728]
The latest dev version works fine with css transforms, but there are still problem with navigator in highstock, take a look at this demo: http://jsfiddle.net/hfrntt/wPpJg

**Comment by pawelfus** [comment]
Works fine with dev-navigator branch: http://jsfiddle.net/wPpJg/4/

**Comment by pawelfus** [comment]
dev-navigator branch merged.
