### ISSUE TITLE
Pie dataLabels with useHTML are not correctly positioned

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7280]
#### Expected behaviour
dataLabels should be aligned correctly with both useHTML set to false and true.

#### Actual behaviour
When dataLabels.useHTML is set to true dataLabels are not correctly aligned.

#### Live demo with steps to reproduce
http://jsfiddle.net/cqb186jr/3/

It looks to be implemented in Highcharts 6.0.0 version

**Comment by TorsteinHonsi** [comment]
Fails since b0cb1ef72
