### ISSUE TITLE
Streamgraph vs reversedStacks - chart cropped

### ISSUE THREAD

**Issue by MiroLiska** [highcharts/highcharts#7281]
#### Expected behaviour
The chart should not be cropped. Correct, not cropped chart is at http://jsfiddle.net/t60nffce/
![uncropped](https://user-images.githubusercontent.com/23024867/31616578-59669e82-b28d-11e7-8ac4-99ff16192e21.png)

#### Actual behaviour
When the reversedStacks is set to false, the chart gets cropped.

#### Live demo with steps to reproduce
See the cropped chart here: http://jsfiddle.net/t60nffce/1/
![cropped](https://user-images.githubusercontent.com/23024867/31616621-78c8f374-b28d-11e7-9574-4fb22a3a8454.png)

#### Affected browser(s)
Tested in IE11 on Windows7

**Comment by pawelfus** [comment]
Hi @MiroLiska 

Thank you for reporting this bug!

Minified demo: http://jsfiddle.net/t60nffce/3/ - it looks like it's connected to the data, with our demo I'm not able to reproduce the issue.

**Comment by sebastianbochan** [comment]
+1
