### ISSUE TITLE
Labels in area chart have not optimal position

### ISSUE THREAD

**Issue by MiroLiska** [highcharts/highcharts#7282]
#### Expected behaviour
The labels in area chart should be visible if possible. See correct placement here: http://jsfiddle.net/542asg0r/
![labelok](https://user-images.githubusercontent.com/23024867/31616874-30919be6-b28e-11e7-8223-caf2abb72b59.png)

#### Actual behaviour
The labels in area charts are sometimes not visible. It is sometimes enough to make the chart bigger(!) and the labels are half-gone.

#### Live demo with steps to reproduce
The same chart as above (at http://jsfiddle.net/542asg0r/), but made bigger:
![labelnotok](https://user-images.githubusercontent.com/23024867/31616924-500ff62a-b28e-11e7-934d-4c14c78dd8d0.png)

#### Affected browser(s)
Tested in IE11 on Windows7

**Comment by pawelfus** [comment]
Thank you for reporting. You are right, it could look better - label is not gone, just has white color and is rendered partially on the category where area doesn't exist.

**Comment by MiroLiska** [comment]
Seems to be fixed with the latest Highcharts version - cannot reproduce it anymore
