### ISSUE TITLE
Heatmap - Select event not triggered on iOS

### ISSUE THREAD

**Issue by epos** [highcharts/highcharts#7283]
#### Expected behaviour

`select` event should be triggered

#### Actual behaviour

`select` event is not triggered

#### Live demo with steps to reproduce

https://jsfiddle.net/4aqhB/1056/

Click on a cell: an alert should be displayed but it isn't on iOS.

#### Minimalist steps to reproduce live demo

1. take basic JSFiddle sample: https://www.highcharts.com/docs/chart-and-series-types/heatmap
2. add the following options:

        plotOptions: {
          series: {
            allowPointSelect: true,
            point: {
            	events: {
                  select: function() {
                    var point = this;
                    alert('Value: '+point.value);
                  }
                }
              }
            }
          }

#### Affected browser(s)

**Chrome or Safari on an iPhone (iOS 10 or 11)**: no select event.
Note: Chrome 61, Edge 40 and Safari 5.1.7 for Windows work fine: select event is triggered correctly.

**Comment by pawelfus** [comment]
Hi @epos 

Thank you for reporting this bug. I confirm it doesn't work on iOS 11 (Safari).

**Comment by epos** [comment]
Thank yoou @pawelfus
