### ISSUE TITLE
DataLabels formatter not working | Highcharts Sankey Diagram

### ISSUE THREAD

**Issue by junaidpkhader** [highcharts/highcharts#7284]
#### Expected Behaviour
Ability to format the dataLabel in the sankey diagram

#### Actual Behaviour
dataLabel is not getting formatted.

#### Live demo with steps to reproduce
http://jsfiddle.net/jy0761aw/2/

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @junaidpkhader 

Thanks! I'm not sure if `formatter` is supported in Sankey diagram, @TorsteinHonsi  ?

According to the [docs](http://api.highcharts.com/highcharts/series.sankey.dataLabels): 

> Options for the data labels appearing on top of the nodes and links. For sankey charts, data labels are visible for the nodes by default, but hidden for links. This is controlled by modifying the nodeFormat, and the format that applies to links and is an empty string by default.

And [nodeFormat](http://api.highcharts.com/highcharts/series.sankey.dataLabels.nodeFormat) docs:

> nodeFormat: String
> The format string specifying what to show for nodes in the sankey diagram.
>
> Defaults to {point.name}.

**Comment by junaidpkhader** [comment]
Thanks for the reply @pawelfus . Yes, I tried the `nodeFormat` as well. (The thing is I am unable to even write a ternary function in the `nodeFormat`).

Is there any way to call a function(similar to that in the `formatter`) in `nodeFormat`? (I was only able to give a string [eg.` {point.name}`]). We wanted to trim last part of the datalabel based on a condition. 

As you might have already seen in the jsfiddle, in the sankey diagram, **we are unable to show the change from the same stage.** (**In the fiddle, to override that we gave Contact to Contact1**) [And I need to trim the "1" from Contact1 so that we can show the diagram as I just told before.]
Thank you.

**Comment by pawelfus** [comment]
I agree, something like `nodeFormatter()` would be great here. Thank you for the details!

**Comment by junaidpkhader** [comment]
Yes @pawelfus . Hope something like that would come soon.

**Comment by chitraParihar** [comment]
Hi,
I am using this example
http://jsfiddle.net/Chitraprhr/vpsqv3Lb/2/

Unable to show label on node. Please help me on this.

**Comment by nodew** [comment]
Please help update the doc.
