### ISSUE TITLE
IE and Edge problem with search bar on http://api.highcharts.com/highcharts/

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7285]
#### Behaviour
On IE11 and Edge the serach bar on http://api.highcharts.com/highcharts/ doesn't open when typing anything into the input.

#### Live demo with steps to reproduce
http://api.highcharts.com/highcharts/

#### Affected browser(s)
IE11 / Win7, IE11 / Win10, Edge / Win10

**Comment by cvasseng** [comment]
Caused by #7290, so this is a duplicate.
