### ISSUE TITLE
filename for offline exporting in Edge is not working

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7286]
#### Behaviour
On Edge browser, the filename option is not working when trying to export offline.

#### Live demo with steps to reproduce
http://jsfiddle.net/5dkpz8hx/

#### Affected browser(s)
Edge

**Comment by sebastianbochan** [comment]
+1 @oysteinmoseng

**Comment by prietveld** [comment]
For me this was fixed with (I assume) an OS or Edge update. Currently Edge 40.15063.674.0 exports the chart as set in exporting.filename as expected.

**Comment by oysteinmoseng** [comment]
Probably because of https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6594876/.
