### ISSUE TITLE
HightCharts bug Month +1 ?? 

### ISSUE THREAD

**Issue by EnguerranMeens** [highcharts/highcharts#7289]
Hello.
 I have a problem, indeed all the dates I add found with a month more and I do not understand why, could you help me?

examplle : [Date.UTC(2017, 1, 18), 1] => February on highsharts 

http://jsfiddle.net/w7sasofr/1/

**Comment by KacperMadej** [comment]
Hi,

Nothing is wrong, all works as designed.

`Date.UTC(year, month[, day[, hour[, minute[, second[, millisecond]]]]])`

> **month**
> An integer between 0 and 11 representing the month.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC

**Comment by EnguerranMeens** [comment]
Thanks !
