### ISSUE TITLE
IE and Edge problem with forEach on http://api.highcharts.com/highcharts/

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7290]
#### Behaviour
Error in console when trying to hover on any item listed on the left side.

#### Live demo with steps to reproduce
http://api.highcharts.com/highcharts/

#### Affected browser(s)
IE11/Win10, Edge

**Comment by cvasseng** [comment]
Caused by #7285, so this is a duplicate.

**Comment by cvasseng** [comment]
This has been fixed in `api-docs`, and will be pushed live asap.

**Comment by sebastianbochan** [comment]
Problem fixed, when will come again. Please reopen the ticket.
