### ISSUE TITLE
First point in series has marker animation that can't be disabled

### ISSUE THREAD

**Issue by goodforenergy** [highcharts/highcharts#7293]
Hey guys, another little issue I found moving between 4.x and 6.x.

#### Expected behaviour
Disabling marker animation should disable all animation related to markers.

#### Actual behaviour
Animation is still visible on marker halo on the first point in the series.

#### Live demo with steps to reproduce
Demo: https://jsfiddle.net/goodforenergy/dqohbuo0/8/

Hover your mouse over the first point, and off to the left. If you resize the window, the issue goes away. Setting chart.animation to false doesn't help.

I made a [screencast](https://www.dropbox.com/s/yhh6c2et9p5ctnv/animation-bug.mov?dl=0) so it's clear about what I'm talking about.

It's not an issue in 4.x. Didn't try 5.x.

#### Affected browser(s)

Chrome (only tested).

**Comment by pawelfus** [comment]
Hi @goodforenergy 

Thank you for reporting and all the details, we really appreciate this :) Hover animations were introduced in v5.0.8, so v4.x was fine.

**Workaround:**
```
  chart: {
    events: {
      load: function() {
        this.renderer.globalAnimation = false;
      }
    }
  },
```
https://jsfiddle.net/dqohbuo0/10/

*Internal note:*
It looks like `globalAnimation` is `undefined` when initializing chart, but after resize, it's set to `false` (see workaround).
