### ISSUE TITLE
for remove hack <IE8

### ISSUE THREAD

**Issue by cnTomato** [highcharts/highcharts#7294]
I think it's time to remove highcharts's hack for <IE8
<img width="1135" alt="qq20171019-151458 2x" src="https://user-images.githubusercontent.com/12791216/31758500-4ea4553e-b4e0-11e7-85fe-8ebb34b6be95.png">

**Comment by TorsteinHonsi** [comment]
In Highcharts 6.0, IE8 specific code was moved out to a separate module, `modules/oldie.js`, that is _not_ loaded by default. 

Did you have other specific hacks in mind?

**Comment by cnTomato** [comment]
@TorsteinHonsi provide offical vue-component react-component ,one type one module,etc

**Comment by cnTomato** [comment]
@TorsteinHonsi 
Compared to other charts, this one is bigger, but I prefer highcharts's api more.

**Comment by pawelfus** [comment]
Thanks! Any issues/hacks with <IE8 as you mentioned earlier? Or should we close this ticket?

**Comment by cnTomato** [comment]
Pls close thx
