### ISSUE TITLE
Sunburst allowDrillToNode error clicking center

### ISSUE THREAD

**Issue by MarcNeis** [highcharts/highcharts#7297]
#### Expected behaviour
When clicking in the center of the basic sunburst graph nothing should happen.
Also the button on the top right displaying "The World"(only in example) should just take u back to the standard view.

#### Actual behaviour
All the labels of the sunburst graph disappear and clicking in the center again wont change that. To get the labels back u have to click into one of the pieces which is not the center and then back out.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/sunburst/

**Comment by pawelfus** [comment]
Hi @MarcNeis 

Thank you for reporting the issue, however it's already reported and fixed: #7229 - next (6.0.2) version will be released this week.
