### ISSUE TITLE
Google Chrome new version 62 created issues with Highstock 2.1.9

### ISSUE THREAD

**Issue by TideQc** [highcharts/highcharts#7298]
Hi There,

I have an application running in my local network that is using Highstock 2.1.9 and is running fine since years and now .. till i updated my Chrome to the new version 62 this morning, i start to have problems.

#### Expected behaviour
No javascript errors

#### Actual behaviour
Getting javascript errors in highstock 2.1.9 since Chrome updated to version 62:
highstock.js:959 Uncaught TypeError: Cannot use 'in' operator to search for '1' in arguments_marker
    at forEach (<anonymous>)

This make the chart unzoomable or resetable.

#### Affected browser(s)
Google Chrome version 62

I just don't know if it's a problem with the new Chrome version or should we put a fix?

**Comment by pawelfus** [comment]
Hi @TideQc 

Highistock 2.1.9 is no longer supported, please update to the new (v6) version. Unfortunately, minified version doesn't provide much info, try `src.js` version - that may help. If you can not update to v6, please contact with our [support](https://www.highcharts.com/support).

**Comment by mmorearty** [comment]
@TideQc, not sure if it was you that filed the following issue, but just FYI, it looks like a Chrome bug — I am hitting the exact same error in an entirely unrelated codebase (our Asana codebase): https://bugs.chromium.org/p/chromium/issues/detail?id=777836

**Comment by TideQc** [comment]
@mmorearty, Yes i definitely wrote this, unfortunately, i had to manually adjust my tool and re-write code to use the new 6.0.1 version of HighStock. Thank you for the heads up!
