### ISSUE TITLE
Point click event on touch screens in Highstock

### ISSUE THREAD

**Issue by slawekkolodziej** [highcharts/highcharts#730]
Highstock doesn't fire point click event, however it works fine in Highcharts. Here's a simple demo: http://jsfiddle.net/hfrntt/TTrU8/

**Comment by andy380743909** [comment]
are there some workaround for this issue?

**Comment by pawelfus** [comment]
Hi @andy380743909 

Issue is closed for 5+ years, if you have similar problem, please contact with our [support](https://www.highcharts.com/support) team.
