### ISSUE TITLE
HighCharts - Legend with useHTML does not work

### ISSUE THREAD

**Issue by tsmfirm** [highcharts/highcharts#7302]
#### Expected behaviour
Legend items line up in the legend

#### Actual behaviour
All the legend items go on top of each other.  If I remove useHTML:true, then the legend works perfectly.  This used to work fine in HighCharts 4.x.  In version 6.x, it is broken.

#### Live demo with steps to reproduce
      var HVDiskChart={
         colors: ['#ff0000', '#66CCFF', '#8d4654', '#7798BF', '#aaeeee', '#ff0066', '#eeaaee', '#55BF3B', '#DF5353', '#7798BF', '#aaeeee'],
         chart: {
          renderTo: 'IDDiskSpace',
          options3d: {
              enabled: true,
              alpha: 45,
              beta: 0
          },
          type: 'pie',
          backgroundColor: {
             linearGradient: [ 300,400,500,100],
             stops: [
                [0, '#ADFF4F'],
                [1, '#FFFF00']
             ]
          },
          borderColor: '#000000',
          borderRadius: 0,
          borderWidth: 1,
          marginTop: 30,
          marginLeft: 10,
          marginRight: 10,
          marginBottom: 60,
          plotBorderColor: '#000000',
          plotBorderWidth: 0,
          plotShadow: false,
          shadow: false
         },
         plotOptions: {
          series: {
             states: {
                hover: {
                   enabled: false
                }
             }
          },
          pie: {
             allowPointSelect: true,
             depth: 35,
             dataLabels: {
                enabled: false,
                format: '{point.name}'
             },
             showInLegend: true
          }
         },
         legend: {
          useHTML: true,
          align: 'left',
          verticalAlign: 'bottom',
          width: 200,
          itemWidth: 400,
          labelFormatter: function () {
             var mytmp, result;
             result = this.y; if ( result > 999999) { mytmp = Highcharts.numberFormat(result / 1000000, 2) + ' TB'; } else if ( result > 999) { mytmp = Highcharts.numberFormat(result / 1000,2) + ' GB'; } else { mytmp = Highcharts.numberFormat(result,2) + ' MB'; } return mytmp + ' ' + this.name;
          },
          y: -10
         },
         credits: {
          enabled: true,
          useHTML: true,
          text: 'Disk Space Usage Graph',
          style: {
            color: '#000000',
            fontWeight: 'bold'
          },
          position: {
             align: 'right',
             x: -15,
             verticalAlign: 'bottom',
             y: -10
          }
         },
         series: [{
            data: [ { name: 'Used Space', y: 8634.7877478 }, { name: 'Free Space', y: 64763.288252 } ]
         }],
         title: {
          text: '',
          align: 'center',
          floating: false,
          style: {
             color: '#000000'
          },
          useHTML: true,
          verticalAlign: 'top',
          y: 15
         },
         tooltip: {
            enabled: false,
         }
      };

#### Affected browser(s)
ALL

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, but this was fixed in v6.0.2: http://jsfiddle.net/highcharts/8kqrqkb4/
