### ISSUE TITLE
Chart sometime does nut run with ajax click!

### ISSUE THREAD

**Issue by nhathoangfarmtech** [highcharts/highcharts#7305]
#### Expected behaviour
I want render the chart after click button with ajax request data!

#### Actual behaviour
And it run OK!
But sometime it does not render and didn't show any error message!
Data get success fully!
I use
 $.getJSON('url', function (data) {});
to get json data!

**Comment by nhathoangfarmtech** [comment]
I solve my problem by set time out for this, maybe it run too fast and appear error!
`setTimeout(function(){},300);`

**Comment by TorsteinHonsi** [comment]
Thanks for using Highcharts!

I'm closing this issue, please reopen if you have further issues.
