### ISSUE TITLE
using RTL in Hebrew causes legend to run over text

### ISSUE THREAD

**Issue by Yoram-Zilberberg** [highcharts/highcharts#7306]
#### Expected behaviour
The text should apear to the right of the symbol, writen continued to the right

#### Actual behaviour
The text should apear to the right of the symbol.  writen continued to the left. causing the test to run over the marking.

Note: The info box also has the text outside the box itself (Seems like the same issue)

#### Live demo with steps to reproduce

See screen shot attached

#### Affected browser(s)
Chrome

**Comment by Yoram-Zilberberg** [comment]
![highchart_bug_16oct17](https://user-images.githubusercontent.com/33000161/31861639-a47aed64-b739-11e7-938e-5a981a368f9c.jpg)

**Comment by Yoram-Zilberberg** [comment]
Closed by mistake

**Comment by pawelfus** [comment]
Hi @Yoram-Zilberberg 

Thanks for reporting this issue, but could you recreate issue in jsFiddle? It looks fine: http://jsfiddle.net/buYCZ/409/

Make sure you have read [Internalization](https://www.highcharts.com/docs/advanced-chart-features/internationalization) docs.

**Comment by Yoram-Zilberberg** [comment]
Hi,

 We will check the doc - But the issue is that it is not working in Chrome. It is working in iExplorer.
So no need to check in jsFiddle. I think.

**Comment by pawelfus** [comment]
@Yoram-Zilberberg  - please, check my demo, it works fine with Chrome (tested v61.0.3163.100  and v 62.0.3202.62).  Maybe you found a bug with a very specific config, that's why I'm asking you for a jsFiddle demo.

**Comment by Yoram-Zilberberg** [comment]
Using the flag seems to have fixed most issues. Thanks
