### ISSUE TITLE
HighStock: setOptions doesn't work for tooltip:split

### ISSUE THREAD

**Issue by tomsommer** [highcharts/highcharts#7307]
http://jsfiddle.net/2g3aot8k/

**Comment by pawelfus** [comment]
Hi @tomsommer 

Thank you for reporting this issue. Just in case, it's `split` that can not be disabled, `shared` works fine: http://jsfiddle.net/2g3aot8k/2/

*Internal note:*
It looks very similar to #4988 - I guess we can use the same solution here with all default options for Highstock (legend, panning, crosshairs).
