### ISSUE TITLE
get navigator series by id

### ISSUE THREAD

**Issue by pinkynrg** [highcharts/highcharts#7308]
I know it is possible to do the following:

```js
let series = chart.get(seriesId);
series.setData(someData);
```
Is there a way to do the same with the navigator?

```js
let nav_series = chart.navigator.get(seriesId); // not working
nav_series.setData(someData);
```

**Comment by pawelfus** [comment]
Hi @pinkynrg 

For support questions, please contact with our [support](https://www.highcharts.com/support) team.

To answer your question: By default, all navigator series share the same ID ([docs](https://api.highcharts.com/highstock/navigator.series.id)), this will work (with first navigator series only): `chart.get('highcharts-navigator-series')`).
