### ISSUE TITLE
Boost: addSeries doesn't trigger clear after new extremes are set for axes

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7309]
#### Behaviour
Ghost series is visible - showing previous series plot, before new extremes for yAxis were calculated after addSeries

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/mv3z8d3L/
1. Press the 'add more series' button
2. Initial blue series is visible as well as the new and correct plot of the same series

**Comment by TorsteinHonsi** [comment]
This issue is fixes in the master. See the original fiddle with the fix applied: https://jsfiddle.net/mv3z8d3L/2/.
