### ISSUE TITLE
Cannot read property 'https://code.highcharts.com/mapdata/countries/us/us-all.js' of undefined

### ISSUE THREAD

**Issue by hc1skalyanasundaram** [highcharts/highcharts#7310]
I'm trying to implement highmaps using react and haven't found a good example. I'm trying like this and it keeps giving the above error. Any pointers would be much appreciated.

import React, { Component } from 'react'
import { findDOMNode } from 'react-dom';
import Highcharts from 'highcharts';
import HighMaps from 'highcharts/highmaps'
import drilldown from 'highcharts/modules/drilldown';

class CustomHighMap extends Component{

    componentDidMount() {
        // load modules
        drilldown(Highcharts);

        const options = {
            title: {
                text: 'Fruit Consumption'
            },
            xAxis: {
                categories: [
                    'Apples',
                    'Bananas',
                    'Oranges',
                    'Pineapples',
                    'Blueberries'
                ]
            },
            yAxis: {
                title: {
                    text: 'Fruit eaten'
                }
            },
            plotOptions: {
                map: {
                    states: {
                        hover: {
                            color: '#EEDD66'
                        }
                    }
                }
            },
            colorAxis: {
                min: 0,
                minColor: '#E6E7E8',
                maxColor: '#005645'
            },
            legend:  {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle'
            },

            series: [{
                data: Highcharts.geojson(Highcharts.maps['https://code.highcharts.com/mapdata/countries/us/us-all.js']),
                name: 'USA',
                dataLabels: {
                    enabled: true,
                    format: '{point.properties.postal-code}'
                }
            }]
        };

        this.chart = new Highcharts['Map'](
            findDOMNode(this),
            options
        );
    }

    componentWillUnmount () {
        this.chart.destroy();
    }

    render() {
        return (
            <div className="in-highchart"></div>
        )
    }
}

export default CustomHighMap;

**Comment by pawelfus** [comment]
Hi @hc1skalyanasundaram 

It's not a bug, please contact with our [support](https://www.highcharts.com/support).
