### ISSUE TITLE
MinPointLength not working if entire series values are 0

### ISSUE THREAD

**Issue by ngehlert** [highcharts/highcharts#7311]
#### Expected behaviour
When I have an entire series with 0 values, the plotOptions.series.minPointLength attribute should still apply and the entire series should be visible with the specified minPointLength

#### Actual behaviour
If the entire series has 0 values, the series is not visible at all. However if at least 1 value is > 0, the minPointLength does work for the entire series

Happens in the latest highcharts version: Highcharts JS v6.0.2 (2017-10-20)

#### Live demo with steps to reproduce
Entire series 0 values: http://jsfiddle.net/rpz0mv4f/
One value > 0: http://jsfiddle.net/rpz0mv4f/2/

#### Affected browser(s)
Chrome 61.0.3163.100
Firefox 56.0.0
Safari 11.0

**Comment by pawelfus** [comment]
Hi @ngehlert 

Thank you for reporting this bug. It used to work in v5: http://jsfiddle.net/rpz0mv4f/3/

*Internal note:*
It's a regression after 6b9e399 - @KacperMadej

**Comment by ngehlert** [comment]
downgrading is currently not an option, so I'll just wait for the fix :). thanks for your quick response @pawelfus 

do you know if there is any workaround besides setting a fake value in one entry?
