### ISSUE TITLE
Bubble Map not displays data labels

### ISSUE THREAD

**Issue by nsdevaraj** [highcharts/highcharts#7312]
#### Expected behaviour
Bubble Map should display data labels

#### Actual behaviour
Bubble Map not displays data labels

Root cause:
https://github.com/highcharts/highcharts/blob/0017f6c6438795ee3105b283fa1a66d37c764ba0/js/parts/DataLabels.js#L201

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/map-bubble/

http://jsfiddle.net/nsdevaraj/pL4w2Lo4/
Data labels doesn't work on Bubble maps

#### Affected browser(s)

All browsers

**Comment by pawelfus** [comment]
Thanks! Let's stick to this ticket: #7313
