### ISSUE TITLE
Mapbubble series doesn't have dataLabels 

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#7313]
Enabling them directly doesn't work.

#### Live demo with steps to reproduce
http://jsfiddle.net/wge3h3kb/

**Internal note:**
It's caused by `point.isNull` which is set for points that don't have `y` value. Mapbubble only requires `z` value (radius) and the rest is calculated from map itself.

Setting `pointValKey` doesn't really resolve the issue: http://jsfiddle.net/pL4w2Lo4/1/ - dataLabels are now enabled, but map is broken.

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/wge3h3kb/1/
