### ISSUE TITLE
Wordcloud and exporting: wrong font and labels are overlapping in the exported PNG/JPEG/PDF

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7314]
#### Behaviour
When exporting to format different that SVG, font is not preserverd on the exported chart - the default ` 'Impact, sans-serif'` is not used.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/wordcloud/

1. Export to PNG / JPEG / PDF and compare fonts + labels are overlapping.

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard We probably need to install the Impact font on the export server. Most likely it will also fix the problem with overlapping.

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi I believe you are right.
I had a look at the licensing and it requires an annual payment for server usage. That seems a bit cumbersome to me, so I suggest that I look into finding an open source font type in stead of Impact.

**Comment by TorsteinHonsi** [comment]
If we can use one of the standard fonts but with a greater `font-weight` that would be simpler.
