### ISSUE TITLE
Defined styles for marker selected state cannot be applied to bar/column charts

### ISSUE THREAD

**Issue by shicechi** [highcharts/highcharts#7315]
#### Expected behaviour
```javascript
plotOptions: {
          series: {
            allowPointSelect: true,
            marker: {
              states: {
                select: {
                  fillColor: 'red',
                  lineWidth: 0
                }
              }
            }
          },
```
Bars and columns styled with defined options above should draw with red filling when selected.

#### Actual behaviour
Default style is always used.

#### Live demo with steps to reproduce
http://jsfiddle.net/xaw7059x/

#### Affected browser(s)
Tested on Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Hi @shicechi 

Column series doesn't have markers, you can set options in `series.states.select`, demo: http://jsfiddle.net/xaw7059x/1/

Code:
```
  plotOptions: {
    series: {
      allowPointSelect: true,
      states: {
        select: {
          color: 'red',
          borderWidth: 4,
          borderColor: 'green'
        }
      }
    }
  },
```

**Comment by KacperMadej** [comment]
So it looks like an API documentation error, because marker is there while it shouldn't be: 
https://api.highcharts.com/highcharts/series.column.marker
