### ISSUE TITLE
Setting title: {useHTML: true, text: null} throws an error

### ISSUE THREAD

**Issue by sweetro** [highcharts/highcharts#7316]
#### Expected behaviour
Based on the documentation, should not show title when  `{title: {text: null}}` (assume this will be the case regardless of other parameters).

#### Actual behaviour
Errors on `{title: {text: null, useHTML: true}}` 

```
highcharts.js:51 Uncaught TypeError: Cannot read property 'toString' of null
    at a.SVGElement.getBBox (VM274 highcharts.js:51)
    at a.Chart.<anonymous> (VM274 highcharts.js:236)
    at Array.forEach (<anonymous>)
    at a.each (VM274 highcharts.js:28)
    at a.Chart.layOutTitles (VM274 highcharts.js:236)
    at a.Chart.setTitle (VM274 highcharts.js:236)
    at a.Chart.render (VM274 highcharts.js:251)
    at a.Chart.firstRender (VM274 highcharts.js:255)
    at a.Chart.init (VM274 highcharts.js:230)
    at a.Chart.getArgs (VM274 highcharts.js:229)
```

Doing a bit of digging it looks like this occurs because the `svgElement` that is set for `title` when `useHTML` is `true` has a `textStr` element that is set to `null` whereas when `useHTML` is `false` or `undefined` the `textStr` element is `undefined`. `getBBox` checks if `textStr` is `undefined`, but doesn't check `null` so errors on the `null.toString`. 

#### Live demo with steps to reproduce

http://jsfiddle.net/8kqrqkb4/1/

#### Affected browser(s)
Probably All (Tested Chrome and FF) Highcharts v 6.0.2

**Comment by pawelfus** [comment]
Hi @sweetro 

Thank you for reporting the issue!

**Comment by TorsteinHonsi** [comment]
@KacperMadej 

Thanks for fixing! However the test fails in Edge and IE11:
![skjermbilde 2017-11-01 kl 15 13 17](https://user-images.githubusercontent.com/227836/32278854-46117f14-bf17-11e7-84d2-1556e8017e49.png)

**Comment by KacperMadej** [comment]
Resolved through https://github.com/highcharts/highcharts/commit/7ed92fb8883573e9eec508c7407e4d9e444f6b51
