### ISSUE TITLE
Scatter chart is not working with Boost module

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7317]
#### Expected behaviour
Scatter chart should work correctly with boost module in every OS and browser

#### Actual behaviour
Scatter chart is working correctly on Windows, but is not working on macOS when marker radius is set to 0.1.

#### Live demo with steps to reproduce

Not working (radius: 0.1)
http://jsfiddle.net/BlackLabel/9kcw0f0q/1/

Working (radius: 1)
http://jsfiddle.net/BlackLabel/9kcw0f0q/

#### Affected browser(s)
All on macOS Sierra 10.12.6

**Comment by cvasseng** [comment]
Can't reproduce it on a El Captian box with AMD GPU. Are you by any chance on a nVidia card? I'm not sure if it's an issue with Sierra, or if it's a bug in a driver.

**Comment by sebastianbochan** [comment]
@cvasseng 
It reprocudable also in my macosx.
Details:
![zrzut ekranu 2018-01-10 o 12 26 12](https://user-images.githubusercontent.com/2115686/34770445-81d7280c-f601-11e7-8157-619ad42af291.png)

**Comment by TorsteinHonsi** [comment]
Not reproducible on my system.
![skjermbilde 2018-01-11 kl 09 45 24](https://user-images.githubusercontent.com/227836/34816108-2f436de0-f6b4-11e7-8f93-106f03f2a887.png)

**Comment by sebastianbochan** [comment]
@TorsteinHonsi  you are right, it is really difficult to see something, but is noticible in big zoom.

**Comment by Izothep** [comment]
The issue is still visible on iOS High Sierra as well, tested with 
10.13.6,
10.13.4,
10.12.4

**Comment by cvasseng** [comment]
I think, as @TorsteinHonsi also mentioned, that it's related to sub pixel rendering, if you set the size to 0.1 you're effectively saying that the size of one point is 1/10th the size of a pixel. This might explain why it's more obvious for some than others, as some monitors will do magical scaling that might make it work better than others. The density would need to be quite high for 0.1 radius points to be visible - especially when they're also blended.
