### ISSUE TITLE
large periods (rangeSelector) - incorrect values

### ISSUE THREAD

**Issue by Melvin-88** [highcharts/highcharts#7319]
I'm using your highcharts. But, when I use large periods (rangeSelector), I see incorrect values.

There is an example:
http://jsfiddle.net/J5y2D/28/

on date Oct. 10, 2011 (range - All) you can see value -7.77599999999 but if we change range to 1M we will see correct value -8.55. 

How can I fix this? I need the correct values for all periods.

Thank you!
Looking forward.

**Comment by pawelfus** [comment]
Hi @Melvin-88 

This is caused by [dataGrouping](https://api.highcharts.com/highstock/plotOptions.series.dataGrouping) - you can disable this option, demo: http://jsfiddle.net/J5y2D/29/
