### ISSUE TITLE
Chart doesn't return to previous configuration, after using options defined in responsive rules.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#7320]
#### Expected behaviour

When the condition is no longer true, chart should return to previous (or default) settings.

#### Actual behaviour

Settings from responsive rules remain set, even if condition is no longer true.

#### Live demo with steps to reproduce

[JSFiddle example](http://jsfiddle.net/daniel_s/qvbuzpzz/)
1. Click "Small" button
2. Click "Large" button

#### Affected browser(s)

All browsers

### Occurence

From v5.0.11 and above.

**Comment by TorsteinHonsi** [comment]
Fails since 69d8df517
