### ISSUE TITLE
Wrong symbols on some maps from Highmaps collection

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#7321]
#### Behaviour
There are at least two maps (Turkey, Poland) where some various characters in name property are replaced by with ? marks.

![turkey](https://user-images.githubusercontent.com/19933566/32001942-848049dc-b99b-11e7-93b0-40ae0da9ef20.png)
![poland](https://user-images.githubusercontent.com/19933566/32001952-8cc7fbf8-b99b-11e7-9bcf-43f966a40e99.png)

#### Live demos
https://jsfiddle.net/gh/get/library/pure/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/tr/tr-all - Turkey map
https://jsfiddle.net/gh/get/library/pure/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/pl/pl-all - Poland map

**Comment by TorsteinHonsi** [comment]
The encoding is not sent with the response headers as we would expect.

Also, I would expect it to work when I set the `chartset` attribute to `utf-8`, but it doesn't, so maybe the encoding itself is also wrong: https://jsfiddle.net/highcharts/f1cwsjhq/

![Uploading Skjermbilde 2017-11-01 kl. 15.33.47.png…]()

**Comment by oysteinmoseng** [comment]
I believe this is an issue with the source data. We can fix this manually.

**Comment by kamilkulig** [comment]
Fixed demos: 

- Poland: https://jsfiddle.net/BlackLabel/stzcwsgq/
- Turkey: https://jsfiddle.net/BlackLabel/4mfewn71/

Internal note: All properties for Świętokrzyskie (PL), Łódź (PL), Iğdır (TR) and Bartın (TR) regions changed from misspelled to correct.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#11
