### ISSUE TITLE
Data module parses table series name as a date if the name has number in it

### ISSUE THREAD

**Issue by imranzahid01** [highcharts/highcharts#7322]
#### Actual behaviour
If your x-series contains a number, then the data module tries to parse it as a date and gives the error 15, and your chart is messed up.

Looking at the example at http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/column-parsed/ if you change the label of `Apples` to `Apples 1` you will get an error

#### Expected behaviour
Data module should be able to parse the series name without any error.

#### Live demo with steps to reproduce
http://jsfiddle.net/w7qyysxr/

**Comment by pawelfus** [comment]
Hi @imranzahid01 

Thank you for reporting, you are right it shouldn't happen.

**Comment by imranzahid01** [comment]
For the time being, as my data doesn't contain dates I have made the following changes:
````
data: {
  table: 'datatable',
  parseDate: function(dates) {}
},
````
thanks to the help on stackoverflow (https://stackoverflow.com/a/46956968/694861)

**Comment by TorsteinHonsi** [comment]
It comes down to the browsers (at least Chrome) parsing `Apple 1` successfully as a date.

`Date.parse('Apples 1'); // => 978303600000 = Mon Jan 01 2001 00:00:00 GMT+0100 (CET)`
