### ISSUE TITLE
accessibility.js not honoring skipKeyboardNavigation

### ISSUE THREAD

**Issue by primerano** [highcharts/highcharts#7323]
#### Expected behaviour

If skipKeyboardNavigation is true I would not expect aria-labels to be set on chart points..     

this seems natural but may be considered a feature request.

#### Actual behaviour

screen reader reads all the points even when skipKeyboardNavigation is true.

#### Live demo with steps to reproduce

http://jsfiddle.net/primerano/dvqd16az/

'foos' and 'bars' have setKeyboardNavigation=true but you will see "ARIA for foos" in the page source

Looking at accessibility.src.js setA11yDescription I think i see the problem. See my comments.

in   H.Series.prototype.setA11yDescription = function() {
`
                   if (
                        this.points && (
                            this.points.length < a11yOptions.pointDescriptionThreshold ||
                            a11yOptions.pointDescriptionThreshold === false
                        )
    Comment: if statement should skip if this.options.skipKeyboardNavigation == true

                    ) {
                        each(this.points, function(point) {

    Comment: inside loop should skip if isSkipPoint(point)

                            if (point.graphic) {
                                point.graphic.element.setAttribute('role', 'img');
                                point.graphic.element.setAttribute('tabindex', '-1');
                                point.graphic.element.setAttribute('aria-label',
                                    point.series.options.pointDescriptionFormatter &&
                                    point.series.options.pointDescriptionFormatter(point) ||
                                    a11yOptions.pointDescriptionFormatter &&
                                    a11yOptions.pointDescriptionFormatter(point) ||
                                    point.buildPointInfoString());
                            }
                        });
                    }
`

Do you agree this is how setA11yDescription should work? 

#### Affected browser(s)
All

**Comment by oysteinmoseng** [comment]
`skipKeyboardNavigation` is designed to just skip the keyboard navigation, and as such works as intended, but I agree that we need an option to skip the screen reader functionality per series/point as well. I am out of office at the moment, but will look at this next week.

**Comment by oysteinmoseng** [comment]
A `series.accessibility.enabled` option is being introduced and will handle this.
