### ISSUE TITLE
Highmaps API docs contain undefined node

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#7324]
Hi, I found some node named `undefined` in Highmaps API.

![snipaste_20171027_155940](https://user-images.githubusercontent.com/6829290/32093591-70f7ded0-bb2f-11e7-8723-e5e1413f0fcf.png)
![snipaste_20171027_155906](https://user-images.githubusercontent.com/6829290/32093606-7dd4e9f4-bb2f-11e7-9806-b332328f15d8.png)

**Comment by pawelfus** [comment]
Thanks!

In Highcharts: 
- no undefined options

In Highstock:
- https://api.highcharts.com/highstock/rangeSelector.buttonTheme.undefined

In Highmaps:
- https://api.highcharts.com/highmaps/undefined
- https://api.highcharts.com/highmaps/mapNavigation.buttonOptions.theme.undefined
- https://api.highcharts.com/highmaps/mapNavigation.buttons.zoomIn.theme.undefined
- https://api.highcharts.com/highmaps/mapNavigation.buttons.zoomOut.theme.undefined

**Comment by TorsteinHonsi** [comment]
It's probably due to the single-quoted, dashed properties:

https://github.com/highcharts/highcharts/blob/v6.0.2/js/parts-map/Map.js#L147-L150

**Comment by pawelfus** [comment]
No more `undefined` props in the docs, closing the issue.
