### ISSUE TITLE
SetData with updatePoints parameter is not working correctly with stacked area series with null points

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7326]
#### Expected behaviour
Series should be correctly updated (using setData with updatePoints) with new data no matter if series contains null points.

#### Actual behaviour
In the case of using null points in stacked area chart, setting new data is not updating series correctly

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/y7wmL2x8/26/

Click update button.

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
**Workaround**: if a series is hidden, then the setData works fine - demo: http://jsfiddle.net/y7wmL2x8/27/
