### ISSUE TITLE
Bar chart with multiple series doesn't redraw correctly after zoom reset

### ISSUE THREAD

**Issue by udeleng** [highcharts/highcharts#7327]
#### Expected behaviour
Redraw the bars correctly, without any missing lines, when resetting zoom

#### Actual behaviour
After resetting zoom, the bars are not all draw, you have to resize the chart, to get a full correct redraw.

#### Live demo with steps to reproduce
1. Zoom in then zoom out.

http://jsfiddle.net/udeleng/wqrks5hc/1/

#### Affected browser(s)
Chrome 60, Firefox 56

**Comment by pawelfus** [comment]
Hi @udeleng 

Please, set `series.cropThreshold`, demo: http://jsfiddle.net/wqrks5hc/2/

Closing as duplicate of #6926
