### ISSUE TITLE
X-range: extra data labels remain on the screen

### ISSUE THREAD

**Issue by berlinger-dmaley** [highcharts/highcharts#7332]
#### Expected behaviour

Only the selected data label(s) remain on the screen.

#### Actual behaviour

**First**, **next** and selected data label(s) remain on the screen.

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/fLt3h1c7/). Steps to reproduce:

A. [Zoom-in](http://prntscr.com/h3u4nf) on the second label: you will see **first** and **third** as well

B. [Zoom-in](http://prntscr.com/h3u5bp) on the third label : you will see **first** and **fourth** as well

C. [Zoom-in](http://prntscr.com/h3u6bd) on the second and third labels : you will see **first** and **fourth** as well

#### Affected browser(s)

Google Chrome
Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Hi @berlinger-dmaley 

Thank you for reporting this bug, you are right these labels should be hidden when points are outside the visible range.
