### ISSUE TITLE
X-axis at 0 mislabeled with first category when data includes negative values

### ISSUE THREAD

**Issue by twheys** [highcharts/highcharts#7333]
#### Expected behaviour
X-axis is labeled with the category matching the X-value

#### Actual behaviour
0 On the x-axis is labeled with the first element in xAxis.categories, other categories are labeled correctly.

#### Live demo with steps to reproduce
https://jsfiddle.net/93fy7hbp/1/

#### Affected browser(s)
Tested in Chrome

**Comment by pawelfus** [comment]
Hi @twheys

Thank you for reporting your issue. I don't think it's a bug, you have set: `"categories": [-1, 0],` which means you have:

- first category (with x=0) with name "-1",
- second category (with x=1) with name "0"

Now, you have two points:
```
    "data": [
      [-1, 0.0],
      [0, 500.00]
    ],
```
First point (with x=-1, **not** a category name="-1") has value=0, and second point (with x=0 -> that means the first category) with value 500. That means first point is rendered before categories (those are indexed from 0), and the second point is rendered on the first category.

If values like `-1` are correct values for your category names then should be set as a string, not a number, for example: https://jsfiddle.net/93fy7hbp/3/

You don't have to use `xAxis.categories = []` options, if you set `xAxis.type = "category"`, take a look: https://jsfiddle.net/93fy7hbp/4/

Let me know if something is not clear.

**Comment by twheys** [comment]
This seems to be correct, only the numbers were misleading. I changed the category labels to be strings and got the expected behavior

https://jsfiddle.net/93fy7hbp/5/
