### ISSUE TITLE
Click event inside tooltip after zoom (only on mobile)

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#7334]
#### Expected behaviour
An alert appears always after clicking on the link inside tooltip.

#### Actual behaviour
When the chart is zoomed, clicking on the link does not cause any action.

#### Live demo with steps to reproduce
http://jsfiddle.net/quvaepad/15/

#### Affected browser(s)
All mobile browsers, tested on Iphone 5.

**Comment by KacperMadej** [comment]
Works fine on Android 6 / Chrome.

Here's a demo with click position highlighted for further testing: http://jsfiddle.net/BlackLabel/quvaepad/31/

**Comment by KacperMadej** [comment]
**Workaround**: add click event for chart - empty function will do just fine.
**Demo**: http://jsfiddle.net/BlackLabel/quvaepad/42/
**Tested on**: Android 6 and iPhone 5.

**Comment by felipeburin** [comment]
This workaround worked fine! 
Really appreciate.
