### ISSUE TITLE
Boost.js does not work with Heatmap on addSeries

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#7338]
#### Expected behaviour
Series appear on chart line by line on every 20ms. Added boost.js module increases performance.

#### Actual behaviour
After boost.js module is added, series are no longer drawn. Tooltip shows info for series.
An error appears in the console: WebGL warning: drawArrays: Bound vertex attribute buffers do not have sufficient size for given first and count.

#### Live demo with steps to reproduce
Original example:
https://jsfiddle.net/ppotaczek/cmpkgsbj/
Simplified example:
https://jsfiddle.net/2o75xmmL/16/

#### Affected browser(s)
All browsers compatible with boost.js

**Comment by TorsteinHonsi** [comment]
Slightly more debuggable demo: https://jsfiddle.net/highcharts/2o75xmmL/18/

It fails on adding a series.

**Comment by TorsteinHonsi** [comment]
@cvasseng Any idea?

**Comment by pawelfus** [comment]
This is caused by `boost.seriesThreshold`, which clears the previous series.

**Workaround:**
Please temporarily disable `boost.seriesThreshold` option, demos:
- https://jsfiddle.net/BlackLabel/kLj527fh/1/
- https://jsfiddle.net/BlackLabel/w9qdsuv5/
