### ISSUE TITLE
Bar chart incorrectly positioned on initial load

### ISSUE THREAD

**Issue by jestersoda** [highcharts/highcharts#7339]
#### Expected behaviour
The bar chart should be vertically centred on initial load.

#### Actual behaviour
The bar chart is positioned higher on initial load which also causes it to appear thinner. Upon redrawing the chart, the position is then corrected. This behaviour seems to have started from v5.0.13.

#### Live demo with steps to reproduce
Positioned higher on initial load, but centred upon clicking Redraw: https://jsfiddle.net/g19ar607/
Positioned correctly in v5.0.12: https://jsfiddle.net/dr9j6ws0/

#### Affected browser(s)
Google Chrome 61.0.3163.100

**Comment by pawelfus** [comment]
Hi @jestersoda 

Thank you for reporting this bug: it's a regression after da2557a

**Workaround:**
Set `xAxis.min=0` and `xAxis.max=1`: https://jsfiddle.net/dr9j6ws0/1/

@KacperMadej

**Comment by KacperMadej** [comment]
Looks like tick on axis for zero is doubled, while there's no need for it. I will try to resolve the problem through removing the source of the doubled tick.
