### ISSUE TITLE
xAxis.max example is wrong in documents

### ISSUE THREAD

**Issue by bbolek** [highcharts/highcharts#7342]
#### Expected behaviour
xAxis.max option must have been implemented in the example

#### Actual behaviour
yAxis.max option is implemented in example

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/xaxis/min-max/

#### Affected browser(s)
All

**Comment by bbolek** [comment]
Here is the link to the api docs [API](https://api.highcharts.com/highstock/xAxis.max)

**Comment by pawelfus** [comment]
Thank you for reporting, @bbolek.
