### ISSUE TITLE
Technical indicators are not included in highcharts-dist

### ISSUE THREAD

**Issue by dattusdwaltz** [highcharts/highcharts#7343]
#### Expected behaviour
Indicators should be a part of the distributed highcharts package.

#### Actual behaviour
Indicators and related modules are not included.

#### Live demo with steps to reproduce
Check contents of the [dist repo](https://github.com/highcharts/highcharts-dist).

#### Affected browser(s)
All.

**Comment by pawelfus** [comment]
Hi @dattusdwaltz 

Thank you for reporting!

@jon-a-nygaard - could you take a look?

**Comment by dattusdwaltz** [comment]
These still appear to be missing from the dist repo after 6.0.3.

**Comment by TorsteinHonsi** [comment]
Sorry for that, we didn't catch the v6.0.3 release. Will give priority to this now.
