### ISSUE TITLE
Using Zones in waterfall chart remove the line between bars

### ISSUE THREAD

**Issue by chabb** [highcharts/highcharts#7344]
#### Expected behaviour
Zones in waterfall remove the line between bars

#### Actual behaviour
We should see the lines between the columns

#### Live demo with steps to reproduce
http://jsfiddle.net/chab/d5pb47wt/12/

**Comment by pawelfus** [comment]
Hi @chabb, thank you for reporting the issue!

**Comment by pawelfus** [comment]
Fixed in #7862 (duplicated).
