### ISSUE TITLE
Xrange chart doesn't set proper min, max . 

### ISSUE THREAD

**Issue by urbannn** [highcharts/highcharts#7345]
The chart extremes should correspond to min and max properties.

jsFiddle: http://jsfiddle.net/q1b3yxL1/1/

After zomming:
![chart](https://user-images.githubusercontent.com/29573313/32318771-916ca0c8-bfb8-11e7-9a52-72a7ffe8555a.PNG)

**Comment by urbannn** [comment]
Hi  @pawelfus ,

Thanks , it is working now.

**Comment by TorsteinHonsi** [comment]
FYI, default pointRange was set to 0 in https://github.com/highcharts/highcharts/commit/cc78d2fa9af5b99fc215c42a57c87de01a71e6ed.
