### ISSUE TITLE
xAxis: With linked axes, "pointPlacement: 'between'" only works for series on the first x-axis

### ISSUE THREAD

**Issue by Sphinxxxx** [highcharts/highcharts#7348]
#### Expected behaviour
![chart](https://user-images.githubusercontent.com/7805101/32328829-79d49e84-bfdb-11e7-8dfa-273c6f3674e0.png)

#### Actual behaviour
![chart 1](https://user-images.githubusercontent.com/7805101/32328868-97197762-bfdb-11e7-836c-c98c1c955975.png)

#### Live demo with steps to reproduce

http://jsfiddle.net/y7tnLyr3/

Remove `linkedTo: 0` for the expected result.

#### Affected browser(s)
Chrome/Firefox/Edge

**Comment by KacperMadej** [comment]
Thank you for reporting about the problem.
