### ISSUE TITLE
Highstock defs is not inserting patterns in SVG defs

### ISSUE THREAD

**Issue by nerbos** [highcharts/highcharts#7352]
#### Expected behaviour
When adding a pattern to Highstock defs I was expecting to have it inserted in the SVG defs, as it happens in Highchart.

#### Actual behaviour
The pattern is not inserted in the SVG ellement.

#### Live demo with steps to reproduce
http://jsfiddle.net/7wLerta1/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @nerbos 

Please, use Highstock in styled mode, it works the same as Highcharts in the styled mode: http://jsfiddle.net/7wLerta1/1/ 

> <script src="https://code.highcharts.com/stock/js/highstock.js"></script>

**Comment by nerbos** [comment]
Hi @pawelfus 

Thank you for your help.

Best regards.
