### ISSUE TITLE
Orientation change issue in Highcharts after navigating to an inner component in Salesforce App in iPad iOS 11.1

### ISSUE THREAD

**Issue by aravindxz** [highcharts/highcharts#7353]
#### Expected behaviour:-
When navigated to an inner component from Highcharts by clicking in a column (in Highcharts) and changing the orientation change from the inner component and on coming back, the chart should be resized according to the current screen size.

#### Actual behaviour:-
When coming back after changing the orientation from inside, the chart is not getting the correct height and width.

#### Live demo with steps to reproduce
I am facing this issue when using Highcharts inside Salesforce app in iPad running iOS 11.1
You can test it out by installing a package whose link is provided in here:- https://salesforce.stackexchange.com/questions/197751/orientation-change-issue-in-highcharts-after-navigating-to-an-inner-component

#### Affected browser(s)
Inside Salesforce iOS app in iPad.

#### Screenshots in the chronological order:-

1. Highcharts loaded in landscape mode and user clicks on a series.
![image](https://user-images.githubusercontent.com/7611254/32375774-d45aba9e-c0c8-11e7-9d55-b4971c040ab5.png)

2. This is the inner component(which is navigated to when user clicks in any series).
![image](https://user-images.githubusercontent.com/7611254/32375970-6bffad82-c0c9-11e7-9d88-24f2b8f0ec1b.png)

3. Orientation changed from the inner component to portrait mode and then back button is clicked.
![image](https://user-images.githubusercontent.com/7611254/32376016-8b0dedf6-c0c9-11e7-8c2c-7d7ccfd2020c.png)

4. The highchart is not being rendered properly. (It's taking the previous orientation when it was loaded initially)
![image](https://user-images.githubusercontent.com/7611254/32376045-a5f7d73a-c0c9-11e7-880c-43ec8c44ab60.png)

**Comment by pawelfus** [comment]
Hi @aravindxz 

Let's continue discussion on [stackexchange](https://salesforce.stackexchange.com/questions/197751/orientation-change-issue-in-highcharts-after-navigating-to-an-inner-component?noredirect=1#comment298959_197751). For now it looks like salesforce issue.
