### ISSUE TITLE
Sankey / skip columns

### ISSUE THREAD

**Issue by RHCautomation** [highcharts/highcharts#7354]
Hi,

it's very often needed to skip columns in a sankey chart to get better visibility of the different links, respectively to better use the available space.

I've done a few workarounds to get close to that function - for that I've inserted a dummy-node with the same width and color of the previous node and removed the dataLabel. But it's still not a very elegant solution, even because there is a unnecessary dummy-rectangle visible. 
Here you can see my workaround - the final solution should be, that **1** moves to **2** an replaces it.

![grafik](https://user-images.githubusercontent.com/32926274/32392187-d913ad64-c0d4-11e7-93f4-3ea491521f1d.png)

It would be nice to declare the amount of columns to skip in the data-array like:

```
data: [
	{from:'A', to: 'B', weight: 5},
	{from:'C', to: 'D', weight: 3},
	{from:'E', to: 'F', weight: 4, skipColumns: 2}, //should skip two columns
	{from:'G', to: 'H', weight: 2}	
	{from:'H', to: 'I', weight: 3}
	{from:'I', to: 'F', weight: 3}
]
```

**Comment by pawelfus** [comment]
Hi @RHCautomation 

Could you show how this should look like? Basing on your description, something like should be fine: http://jsfiddle.net/f1cnwymm/ ?

**Comment by RHCautomation** [comment]
Hi,

thanks for response.

Your solution goes into the right direction. I've added few modifications to your code - otherwise it wouldn't be possible to add a new link to a skipped node. 

[http://jsfiddle.net/f1cnwymm/1/](url)

But with that solution, I have to add the skipColumns-parameter to all nodes which are linked behind the first skipped node - it would be much nicer and easier to handle, if the skipColumns-parameter has only to be declared for the first node. Any solutions for this?

Thanks!

**Comment by RHCautomation** [comment]
thanks!

the basic intention of this function was to better use the available space. but after a few tests I saw, that this solution isn't doing that - it seems, that the nodePadding-sum of the subsequent nodes are added to the previous skipped node.

I've set nodePadding of 40 in my application and this results in following space-wasting view:
![grafik](https://user-images.githubusercontent.com/32926274/32449468-ef6af5f6-c311-11e7-83c4-7b0d7d3d514d.png)

Quite same here:
[http://jsfiddle.net/j55m1ypy/2/](url)


Antoher problem is, that it's not possible to use a skipped node in a row between "normal" nodes, without vertical crossing of the lines, because the skipped nodes are always added in the last row (like here:)
[http://jsfiddle.net/j55m1ypy/3/](url)

The perfect solution would be the one from the screenshot of my first post...

**Comment by RHCautomation** [comment]
a quick hack to remove the duplicate nodes in the column of the skipped nodes, which caused the massive padding:
[http://jsfiddle.net/j55m1ypy/4/](http://jsfiddle.net/j55m1ypy/4/)
But now the vertical position of B and D is wrong...

**Comment by pawelfus** [comment]
It looks like simple workaround won't do the thing.. maybe we started in a wrong place.

FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Yeah we need to respect the order of the nodes within each column to avoid unnecessary overlapping, and also make sure the links curve around skipped columns. I'll have a closer look tomorrow.

**Comment by TorsteinHonsi** [comment]
Spent some hours on this now, here's what I've got so far:
- [x] Single node skipped - http://jsfiddle.net/highcharts/7zxvrye9/
- [x] Two nodes skipped, separate - http://jsfiddle.net/highcharts/j55m1ypy/5/
- [ ] Two nodes skipped, next to each other - http://jsfiddle.net/highcharts/j55m1ypy/6/

**Comment by RHCautomation** [comment]
Hi,

thanks for your work so far.

Is there a chance to also get a solution for the last application (two nodes skipped, next to each other)?

Some things I've also tried, which are not working:
- skip more than one node (for example: skipColumns: 2)
- skip a node after a skipped node

As a example for complex sankey diagrams: [https://bost.ocks.org/mike/sankey/](https://bost.ocks.org/mike/sankey/)

**Comment by RHCautomation** [comment]
Hi,

today I saw, that in the recent version are new options for sankey-diagrams available (node.index / node.offset).

The idea is good, but after firts tests I found out, that these options are still not practicable for complex diagrams.

I used the example from the API reference and added a additional node ("Test"). The new node is shown outside of the plot area, due to the used offset (with smaller offset it would overlap with the line above): 
[http://jsfiddle.net/mgdwspmf/](http://jsfiddle.net/mgdwspmf/)

It's nice that's now possible to directly define the node index, but the offset-parameter is not a good solution for me.
For me the best solution would be, if it would also be possible, to define some kind of a row-parameter and all the nodes would automatically be scaled and positioned in relation to the total height and the node-weights...

**Comment by TorsteinHonsi** [comment]
Yes I agree we don't still have the full flexibility that we want. The new `node.column` and `node.offset` options help, but it is still hard to automate it.
