### ISSUE TITLE
Offline-Exporting to PDF: Arabic words overlapping  English words

### ISSUE THREAD

**Issue by ecaffairs** [highcharts/highcharts#7358]
[chart (13).pdf](https://github.com/highcharts/highcharts/files/1445925/chart.13.pdf)
#### Expected behaviour
offline-exporting to PDF using function exportChartLocal should export chart without any words overlapping.

#### Actual behaviour
In Exported PDF, the Arabic characters overlap English characters

#### Live demo with steps to reproduce
http://jsfiddle.net/2sxohabs/3/

#### Affected browser(s)
Google Chrome, IE 11 and FireFox

**Comment by ecaffairs** [comment]
[chart (13).pdf](https://github.com/highcharts/highcharts/files/1445924/chart.13.pdf)

**Comment by pawelfus** [comment]
Hi @ecaffairs 

Thank you for reporting this issue. It looks fine when setting `exporting.allowHTML` and `dataLabels.useHTML` in the original chart object: http://jsfiddle.net/qtsy3fzf/

*Internal note:*
I guess it's bug with inheritance, for example setting `dataLabels.enabled=false` works fine.

**Comment by ecaffairs** [comment]
Hi Pawelfus

Thanks for your support.

You solution working with Chrome only. 

Could you please try IE 11?

Thanks

**Comment by pawelfus** [comment]
Hi @ecaffairs 

Thank you for your feedback. `exporting-offline` doesn't support exporting to PDF in IE11 (see [compatibility table](https://www.highcharts.com/docs/export-module/client-side-export)).

It looks like you found a bug in our default exporting server.

@cvasseng - this demo: http://jsfiddle.net/qtsy3fzf/1/ - exported to PDF in IE11 has labels mispositioned: [chart.pdf](https://github.com/highcharts/highcharts/files/1446433/chart.4.4.pdf)
