### ISSUE TITLE
Variwide: working only on categorized x axis

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7359]
#### Expected behaviour
Working with non categorized axes or info that it doesn't.

#### Actual behaviour
Only a comment in code: 

```
        /**
         * To do:
         * - When X axis is not categorized, the scale should reflect how the z values
         *   increase, like a horizontal stack. But then the actual X values aren't
         *   reflected the the axis.. Should we introduce a Z axis too?
         */
```

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/wvyd2yag/1/

I am unsure whether to tag this `Docs`, `Enhancement` or both.

**Comment by FilipeCosta06** [comment]
Hi,

I'm am still new to this and I'm unsure what the `Enhancement` means. Is this a "bug" that'll be fixed (not being able to use datetime with variwide is what I'm referring to) or that you inform us that is it a normal 
behavior (to this day, unless I did something wrong, [the points are invisible if using datetime with variwide](https://jsfiddle.net/DixiPoowa/93zmk02v/13/)) ?

**Comment by sebastianbochan** [comment]
Hi @FilipeCosta06,
The Enhancement flag means that the functionality is not included in the current version of Highcharts, but can be included in the future.

**Comment by sebastianbochan** [comment]
unstale

**Comment by pawellysy** [comment]
unstale

**Comment by TorsteinHonsi** [comment]
It does work with datetime axis: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series-variwide/datetime/
