### ISSUE TITLE
Point color in vector series

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#7360]
#### Expected behaviour
The arrow should change color to red.

#### Actual behaviour
Only the background under the arrow is changed. 
In API Reference, marker in vector series is unnecessarily described.

#### Live demo with steps to reproduce
http://jsfiddle.net/764tm7sa/3/

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Fixed since v6.0.5: http://jsfiddle.net/BlackLabel/764tm7sa/5/
