### ISSUE TITLE
Plotted vs Displayed data causes problems

### ISSUE THREAD

**Issue by vlsg** [highcharts/highcharts#7361]
#### Expected behaviour
Be able to set the display value's precision separate from the plotted value.

#### Actual behaviour
I can either set the plotted value through series:data:x/y and then have to change a LOT of format overrides to set the precision of what is displayed, or I can plot the displayed/truncated values and the data plots poorly.

#### Live demo with steps to reproduce
This example shows what happens when I have to PLOT the display value (i.e. applying the precision that should be displayed):

https://jsfiddle.net/vg10/s3o09cec/

IRL, I am looping through ~25k data points and applying precision to the x/y values in a single place in code, but then it displays stair-stepped like this.  Ideally, the x coordinate would be plotted with -0.038889172 and then I could tell it to display parseFloat(-0.038889172.toFixed(4) in ALL locations (tooltips, axes, labels, etc), at the same time that I am setting the x/y.  I have tried using datalabels in the data (fires but doesn't change display value), and using point name, but that only covers the X value.  I can't find any way to do this in a single location so I have dozens of charts that would require a lot of work to recreate formatting just so I can change the precision on what's displayed.

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @vlsg 

Thank you for letting us know about your issue. I think what you need is `tooltip.headerFormat`, `yAxis.labels.format` and/or `series.dataLabels.format` with exact formatting ([formatting options](https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting)). For example, for tooltip: https://jsfiddle.net/b4qqbtbm/ 

Regarding single location for changing this, I suggest to use themes, for example create a theme in a separate file:

- highcharts4precision.js :
```
Highcharts.setOptions({
  tooltip: {
    headerFormat: ...
  }
});
```

And now simply include this file in all locations where you have charts. Note that `setOptions()` will change options for all charts on a page, so you don't have to include this multiple times.

**Comment by TorsteinHonsi** [comment]
If you want to modify the _data_ itself, you may need to override the Point object: https://jsfiddle.net/highcharts/s3o09cec/9/ .

**Comment by vlsg** [comment]
Thank you both for your replies.  Pawel, using a theme sounds like a good idea, but would this solution really allow me to change the format for all types of charts?  For example, as I mentioned I have one place where we loop through our JSON code and set x/y data, but that code applies to line charts, column charts, polar charts and scatter plot charts.  When I look at the examples on highcharts websites, the default formatting is different depending on the chart type, so would I have to reproduce that formatting?  Also sometimes we already have special formatting to apply - for example we have already modified our polar charts to show the degree symbol (°) on the X value, so I don't know how I can set it up to have a theme that applies the precision, when you said that the theme would overwrite existing formatting we have applied.  We certainly wouldn't want to show the degree symbol for our other charts though.  And then, if we could get theming to do this for us, it sounds like I'd still have to write the logic in 3 places -  tooltip.headerFormat ,  yAxis.labels.format  and  series.dataLabels.format  - will that cover all of the places that the data displays?  Would it be possible for you to expand your fiddle to show all 3 formats done in one place for multiple chart types?

Lastly, in response to Torstein, no that is exactly what we do not want to do.  We do NOT want to modify the PLOTTED data, we only want to modify the precision of what is displayed, which is why I am requesting a separation of Plotted vs Displayed data.  Right now I am in a catch-22, if I use the full data values, our customers complain that they only want to see 4 significant digits and that the charts are hard to read because of it; if I use the truncated data, then the data does not plot properly and we end up with the stair-step example I showed, and that makes our charts even less useful.  For the time being we have reverted to no truncation, but again, seeing up to 17 digits on our X & Y values makes viewing the data less user-friendly.

Thanks again for your responses.
-VG

**Comment by pawelfus** [comment]
Hi @vlsg 

Thank you for the details! Let me answer your questions:

> (...) using a theme sounds like a good idea, but would this solution really allow me to change the format for all types of charts?

Yes, this solution allows to change all charts in one place.

> When I look at the examples on highcharts websites, the default formatting is different depending on the chart type, so would I have to reproduce that formatting?

It doesn't exactly depends on chart type, but in general on the chart config. For example `tooltip.shared` changes what params in `formatter()` we will have (point vs array of points).

> Also sometimes we already have special formatting to apply - for example we have already modified our polar charts to show the degree symbol (°) on the X value, so I don't know how I can set it up to have a theme that applies the precision (...)

Themes are useful when you want to use exactly the same options for charts. If you have different formats, then it's a bit more complicated but still possible. Instead using `format` options, use `formatter` which is a callback and allows to apply changes with extra options.

> tooltip.headerFormat , yAxis.labels.format and series.dataLabels.format - will that cover all of the places that the data displays?

Actually, `x/yAxis.labels.format` doesn't display data, so only `dataLabels` and `tooltip` are related. Of course `xAxis/yAxis` can also display rounded numbers, but I'm not sure if this the best way to display labels - labels will be duplicated (see demo below).

Example using theme + formatters: https://jsfiddle.net/6Lhjeryg/
As I mentioned above, I think `format` is too simple for your use case, `formatter` is better solution because grants better control for multiple, **different** charts. You can also observe duplicated labels on xAxes. You can control `minTickInterval` on axes, so it won't happen: https://jsfiddle.net/6Lhjeryg/1/

**Comment by vlsg** [comment]
Thank you so much Pawel, I'm going to study your example and see if I can apply it on my end.  I'll let you know how it goes in a few days.  Thanks again!

**Comment by vlsg** [comment]
Hello Pawel, I am having trouble implementing themeing for the tooltip formatter.  I don't typically display dataLabels, but in your example you use plotOptions to set the dataLabels formatter, and then you have access to this.series.chart.options.  When I use the tooltip formatter, "this" only has properties for x,y and a collection of points, so I am at a loss as to how to customize the tooltip display based on chart type here:

```
Highcharts.setOptions({
  tooltip: {
    formatter: function ()
    {
	//this has no series property
	}
  }
});
```

However, when I started putting together a fiddle to show you, that exact same formatter method ~does~ have a series property (and a whole lot more) inside the fiddle.  I updated to highcharts 6.03 (from 6.01) just in case this was a recent change, but I still can't seem to get access to the chart series info from inside my tooltip formatter.  Do you have any suggestions?

Thank you

**Comment by pawelfus** [comment]
Hi @vlsg 

This is important:

> It doesn't exactly depends on chart type, but in general on the chart config. For example `tooltip.shared` changes what params in `formatter()` we will have (point vs array of points).

I assume you have `shared`/`split` set to true (default for Highstock is `true`). Please, check [`formatter`](https://api.highcharts.com/highcharts/tooltip.formatter) docs for the details.

**Comment by vlsg** [comment]
Thank you Pawel, that is indeed an important detail.  I did have shared set to true, and based on the documentation:

> this.series (not shared) / this.points[i].series (shared)The series object. The series name is available through this.series.name.

I was able to use the second option to get to the series object.  I am making more progress now - thank you.  I hope to have the rest of my theme set up in-house this week and will let you know how it goes.

Thanks again,
-VG

**Comment by vlsg** [comment]
Hello again Pawel, I believe I have most of the theming working now and haven't run into too many problems.  I think this will be a sufficient solution for now.  However there seems to be one last problem I'm struggling with, and that is applying the date format for the X-axis values on a StockChart.  Before the chart is rendered, I have logic that tests the data for whether it is daily, weekly or yearly data and change the format accordingly in labels: { format: dateFormat }.  Since the theme overrides the label format, the values now show as the epoch time values such as "1510949511", which are plotted fine, but don't help with display.  I can figure out if it's a StockChart in the formatter via this.points[0].series.chart.options.isStock, but how do I format the epoch time based on Highcharts' date formatting parameters such as "{value:%e %a}"?

Thanks!
-VG

**Comment by pawelfus** [comment]
Hi @vlsg 

`format`'s don't support conditional formatting, you need to use `formatter` in this case: 

```
labels: {
  formatter: function () {
    var str;
    if (isStock) {
      str = ...
    } else {
      str = ...
    }
    return str;
  }
}
```

**Comment by vlsg** [comment]
Hi Pawel, Highcharts.dateFormat() was what I was looking for.  I have now completely revamped my charting code to use Highcharts.setOptions for the common formatting, and removed formatting from my plotted x/y data.  There is only one last problem I am experiencing, and that is a shared tooltip with a lot of series just doesn't display at all.  In some of the more complicated charts we generate, I have about 63 series, so naturally, we can't display them all, but I'd like to display as many as I can.  What is the character limit for the return value so that I can cleanly end the string and display it before hitting the character limit?

Thanks!

**Comment by pawelfus** [comment]
Hi @vlsg 

We don't have any characters limit in the tooltip formatter. If tooltip will be to big, it will be cut off, take a look: http://jsfiddle.net/3o3km8og/ And this moment you we can use one of the solutions:

- plugin to render full tooltip: 5784
- use `split` tooltip, where all labels that won't fit the container will be hidden automatically

**Comment by vlsg** [comment]
Hi Pawel, I'm sorry - I neglected to mention this particular chart that has the problem is using Highstock.  I hope I did this right - I took your fiddle and updated it to highstock with the text I'm trying to display:
http://jsfiddle.net/0yr7m909/1/

Thanks

**Comment by KacperMadej** [comment]
@vlsg In Highstock split is set to true by default, so setting split to false will enable the tooltip. Demo: http://jsfiddle.net/BlackLabel/0yr7m909/2/

**Comment by vlsg** [comment]
Kacper, since I am using setOptions to apply a theme to all Highcharts and Highstock charts at the same time, I set it there, but it doesn't seem to make it work in my local code.  Is this property supported via the setOptions theming? Thank you

**Comment by KacperMadej** [comment]
@vlsg 
Global options are overridden by constructor specific options because those options are merged with use options when using StockChart constructor.
Demo: http://jsfiddle.net/BlackLabel/0yr7m909/3/ (please see few top lines with comments)

**Workaround**: use default `chart` constructor and set all required stock options manually

**Comment by vlsg** [comment]
Kacper, unfortunately taking it out of the theme would defeat the purpose of formatting the data on one place.  I have dozens of chart instantiations to support and my original problem was specifically in regards to not being able to format the data in one place.  Pawel suggested theming and that has worked sufficiently.  If split is not a property that is supported by that, then it's not going to get used.  All I was looking for was how to cut off the formatted string so that it would display at least the first set of series instead of nothing at all.  So I have added if (i == 12) { break; } to my for loop and it now does just that.  I don't think it is necessary to apply a complex solution in this case.  I do recommend however that Highcharts and Highstock are updated to have the same defaults for each property - having a different default based on which is which is very confusing.

Thank you.

**Comment by pawelfus** [comment]
Hi @vlsg 

Thank you for your answers The problem with `split`.. it's a bug, reported here: #7307. Until we fix this bug, you may need to keep your limit in the formatter.

Regarding common options for Highcharts and Highstock, thank you for suggestion!

**Comment by vlsg** [comment]
Thank you @pawelfus , et al for your help in this matter!  I (and our customers!) greatly appreciate your help with getting this to meet our needs.
