### ISSUE TITLE
Data labels rotation overlap bug

### ISSUE THREAD

**Issue by yaroslavkorzh** [highcharts/highcharts#7362]
#### Expected behaviour
As in rotation set to 0 overlapping labels should be hidden
![screenshot 827](https://user-images.githubusercontent.com/4362415/32450579-427197ae-c31d-11e7-89ea-e1ba15d43334.jpg)

#### Actual behaviour
When you use rotation different from 0, data labels will overlap
![screenshot 826](https://user-images.githubusercontent.com/4362415/32450581-428ecb1c-c31d-11e7-8211-5a58c39dd1d5.jpg)

#### Live demo with steps to reproduce
1. Create any chart with big amount of points where points are close.
2. On created chart enable data labels with rotation = 0, check that overlapping labels aare hidden
3. Change rotation to 270 degrees
To check the steps you can use demo fiddle - changing rotation there shows issue.
http://jsfiddle.net/yako/6urguckf/4/
Seems like logic that calculates labels overlap misses when label is rotated.

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Thank you for reporting!

**Comment by skuske** [comment]
Any update on this (i.e. when this will be fixed?)

**Comment by skuske** [comment]
Any update, pleeeeeease!

**Comment by pawelfus** [comment]
Hi @skuske 

We don't have ETA for this issue. I added a workaround for this issue. **Note**: it may cause some performance issues with huge datasets.

**Workaround:**
Demo: http://jsfiddle.net/6urguckf/24/

Plugin:
```javascript
(function(H) {
  H.wrap(H.Chart.prototype, 'hideOverlappingLabels', function(p, labels) {
    var bbox;
    for (var i = 0; i < labels.length; i++) {
      bbox = labels[i].element.getBBox();
      labels[i].placed = true;
      labels[i].alignAttr = {
        x: bbox.x,
        y: bbox.y
      };
    }
    p.apply(this, Array.prototype.slice.call(arguments, 1));
  });
})(Highcharts);
```

*Internal note:*
It looks like rotated labels don't set `placed` and `alignAttr` params.

**Comment by skuske** [comment]
Thanks. How can I use that in the iOS Wrapper?

**Comment by pawelfus** [comment]
Unfortunately, this workaround can not be used in iOS wrapper. For iOS wrapper we need to use events, demo for you: http://jsfiddle.net/6urguckf/35/

**Comment by TorsteinHonsi** [comment]
@pawelfus Will you prepare a PR with the fix?
