### ISSUE TITLE
Sunburst label not showing up after drilldown

### ISSUE THREAD

**Issue by SpaceMalamute** [highcharts/highcharts#7363]
#### Expected behaviour
Shows the labels after drilldown

#### Actual behaviour
The labels are not displayed, works only when you resize the chart. 

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/sunburst/

#### Affected browser(s)
Google Chrome, Firefox, Edget, IE

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard Please note that I implemented the new `filter` option in the demo (remember to pull `bugfix`), but it doesn't affect this issue.

**Comment by jon-a-nygaard** [comment]
_Internal Note: Regression since https://github.com/highcharts/highcharts/commit/6b864f5027152ce0614eccf662fc3bb3735d3de3_

**Comment by TorsteinHonsi** [comment]
It boils down to a problem with running an animation from the `complete` callback of a previous one. This used to work in v6.0.1, before the offending commit: http://jsfiddle.net/wcshtb7w/
