### ISSUE TITLE
Tab navigation ignores zoom level when dataGrouping is disabled on Area charts

### ISSUE THREAD

**Issue by primerano** [highcharts/highcharts#7364]
#### Expected behaviour
When tabbing into an area chart on highstocks the 1st point selected should be at the beginning of the range.

#### Actual behaviour

The 1st point that tab navigation hits is the 1st item in the data series when dataGrouping is disabled.  The range selected is ignored.

This works fine when dataGrouping is enabled.   Also works fine on column charts.  Seems specific to area charts with dataGrouping disabled.

#### Live demo with steps to reproduce

https://jsfiddle.net/primerano/6396rd7z/

#### Affected browser(s)

All.

**Comment by pawelfus** [comment]
Hi @primerano 
Thank you for reporting. @oysteinmoseng could you take a look?

**Comment by oysteinmoseng** [comment]
Seems to be working with current code, feel free to reopen if there are still use cases where this is an issue.

**Comment by primerano** [comment]
@oysteinmoseng -- my fiddle still shows the behavior

https://jsfiddle.net/primerano/6396rd7z/

This is pointing to the current code right?

Click the "just here so i can get 1 tab away from chart" button.  hit tab 2x and you are on 1993 point instead of 2001.

**Comment by oysteinmoseng** [comment]
@primerano Ah, I misunderstood the issue. Reopening. I'll edit the issue title to clarify.

**Comment by khlieng** [comment]
Fixed since 9.0.0.
