### ISSUE TITLE
Technical indicators in chart will prevent data grouping of other series

### ISSUE THREAD

**Issue by shicechi** [highcharts/highcharts#7366]
#### Expected behaviour
All series should behave properly with their respective data group settings when technical indicators series are added.

#### Actual behaviour
Looks like the indicator series are not actually being grouped, which caused all other series to be zoomed out instead of grouped.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/sma-volume-by-price/

Select 'All' in range selector.

#### Affected browser(s)
Google Chrome Version 62.0.3202.75 (Official Build) (64-bit) on macOS

**Comment by pawelfus** [comment]
Hi @shicechi 

Thank you for using Highstock! It looks like `series.dataGrouping.groupPixelWidth` is the culprit here. Could you set the same value for all series and let me know if this resolves the issue? In the demo it works fine: http://jsfiddle.net/fjbfyq70/

**Comment by shicechi** [comment]
Thanks for the reply @pawelfus!

Yes, setting the same value for all series solves the problem in the demo. However in my use case, a new issue emerged.

I am using Bollinger band and custom grouping units, and the Bollinger band will become disconnected lines.

Demo: http://jsfiddle.net/j5zrjq30/

I am not sure if it is a bug or not. If so, please address it so I can change the title and the description of the issue.

Thanks!

**Comment by pawelfus** [comment]
This is certainly bug. Thank you for the details! I think it's caused by approximation function, I have written another one, and now it works fine, please take a look: http://jsfiddle.net/j5zrjq30/3/

Regarding approx issue, I have reported this a separate ticket: https://github.com/highcharts/highcharts/issues/7377

Thank you once again!
