### ISSUE TITLE
export to png not working in android webview

### ISSUE THREAD

**Issue by hallikaxinom** [highcharts/highcharts#7367]
1. In Android studio create project  
[project.zip](https://github.com/highcharts/highcharts/files/1449377/project.zip)
with simple webview activity, overrride
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        webView = (WebView) findViewById(R.id.webView);
        webView.getSettings().setJavaScriptEnabled(true);
        webView.loadUrl("https://www.highcharts.com/demo/line-basic");
        WebView.setWebContentsDebuggingEnabled(true);
        webView.getSettings().setSupportMultipleWindows(true);
        webView.getSettings().setSupportZoom(false);
        webView.getSettings().setDomStorageEnabled(true);
        webView.getSettings().setDatabaseEnabled(true);
    }
2. Make sure it will load https://www.highcharts.com/demo/line-basic
3. Add permissions to manifest 
```
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
4. install app
5. if os>=6.0 go to devices settings -> Application Manager -> WEBVIEWAPP -> permissions and accept the storage permissions
6. run app
7. open google chrome in your pc/mac, write chrome://inspect to address bar and then choose the webview that is in the app
8. at the top right corner of the chart, choose burger menu button -> Download PNG image

#### Expected behaviour
Image is downloaded and the export.highcharts.com request line in chrome inspector network tab is colored black and there is response data

#### Actual behaviour
Image is not downloaded and the export.highcharts.com request line is red in chome inspector network tab and there is no response data
![pilt](https://user-images.githubusercontent.com/33448719/32486435-4ab3be14-c3af-11e7-8fd6-5aa790097d4e.png)

#### Live demo 
[compiled_apk.zip](https://github.com/highcharts/highcharts/files/1449387/compiled_apk.zip)

#### Affected browser(s)
Android Webview

**Comment by pawelfus** [comment]
Hi @hallikaxinom 

Thank you for reporting this issue. You are right, something is wrong - request is immediately canceled:

![screen shot 2017-11-07 at 15 10 33](https://user-images.githubusercontent.com/1453926/32497795-02b4bc70-c3ce-11e7-965d-218aa105db8e.png)

May be helpful [this SO question](https://stackoverflow.com/questions/12009423/what-does-status-canceled-for-a-resource-mean-in-chrome-developer-tools/13459106) - we have `stopPropagation()`, so maybe it's not enough? 

*Internal note:*
1) When downloading new Android SDK, make sure to match tools, in file `build.gradle`:
```
android {
    compileSdkVersion 27
    buildToolsVersion "27.0.1"
    defaultConfig {
        applicationId "com.axinom.webview"
        minSdkVersion 17
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
```
2) Install `ConstraintLayout for Android` in Android SDK: Android Studio -> Preferences -> Appearance & Behaviour -> System Settings -> Android SDK -> SDK Tools tab -> Support Repository -> `ConstraintLayout for Android`

3) Additionally, make sure to rebuild the project, with `gradle-wrapper.properties` up-to-date:
```
#Wed Mar 22 16:13:58 BRT 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```

4) Now rebuild (`Build -> Clean` & `Build -> Build APK(s)`) project.

**Comment by hallikaxinom** [comment]
I think the stopPropagation() is some jS method. I'm native dev and the web dev is using highcharts through angular. Should i mention stopPropagation() to him?

**Comment by pawelfus** [comment]
Sorry, that part suppose to be under `Internal note:` :) In the `exporting.js` we may need to add `preventDefault()`. I'm not Android dev so I'm not sure if this is issue in the WebView or in our exporting module.

**Comment by hallikaxinom** [comment]
I tried setting different flags for webview i could think of. Couldn't make it work. I was going to also play around with access-control-origin and xframe headers, but that would have required a troublesome hack injecting special javascript etc just so i could get access to the post body so i could make my own custom query with custom headers added but using the same post data. Have been working on this for 2 days. Eventually found out the offline export demo - i could get the image from there into native code. Until theres a known fix for the online export we will probably use that as a workaround.

**Comment by hallikaxinom** [comment]
I tried to convert the blob to data url by loading javascript to webview:

loadJs("var xhr = new XMLHttpRequest;\n" +
"xhr.responseType = 'blob';\n" +
"\n" +
"xhr.onload = function() {\n" +
" var recoveredBlob = xhr.response;\n" +
"\n" +
" var reader = new FileReader;\n" +
"\n" +
" reader.onload = function() {\n" +
" var blobAsDataUrl = reader.result;\n" +
" window.location = blobAsDataUrl;\n" +
" };\n" +
"\n" +
" reader.readAsDataURL(recoveredBlob);\n" +
"};\n" +
"\n" +
"xhr.open('GET', '"+shareUrl+"');\n" +
"xhr.send();");
}

but when i run it, i get

Failed to load blob:https://fiddle.jshell.net/ab29b253-06e1-4e80-bf77-744447ae9898: Cross origin requests are only supported for protocol schemes: http, data, chrome, https.

Any ideas how i could get the svg data from blob url?

**Comment by pawelfus** [comment]
@oysteinmoseng - any ideas?

**Comment by oysteinmoseng** [comment]
I am not an android dev either, but maybe you could override the `Highcharts.svgToDataUrl` function of Highcharts to always return a data URI and not Blob. Example:

```javascript
Highcharts.svgToDataUrl = function (svg) {
    return 'data:image/svg+xml;charset=UTF-8,' + encodeURIComponent(svg);
};
```
