### ISSUE TITLE
Bubble chart with series containing points with null and negative x values is not rendered

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7369]
#### Expected behaviour
Chart should be correctly rendered when series contains null and negative points.

#### Actual behaviour
Chart is not drawn when some data points have null value and some data points have negative values.

#### Live demo with steps to reproduce
http://jsfiddle.net/mar7sems/2/

This issue may be related to
https://github.com/highcharts/highcharts/issues/4031

**Comment by TorsteinHonsi** [comment]
The bug is inherited from the scatter chart: http://jsfiddle.net/highcharts/mar7sems/3/
