### ISSUE TITLE
Sunburst - unable to use styled mode

### ISSUE THREAD

**Issue by SpaceMalamute** [highcharts/highcharts#7371]
#### Expected behaviour
To be able to have the sunburst with styled mode activated. 
Maybe i'm missing something. 

#### Actual behaviour
Not rendering, some errors in the console. 

#### Live demo with steps to reproduce
http://jsfiddle.net/2u833trw/2/

http://jsfiddle.net/2u833trw/3/

#### Affected browser(s)
IE, Chrome, Firefox, Edge

**Comment by pawelfus** [comment]
Thank you for reporting the issue. 

FYI @jon-a-nygaard
