### ISSUE TITLE
GridAxis label is overflowing

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/highcharts#7372]
#### Expected behaviour
Label should not move outside the grid cell.

<img width="825" alt="skjermbilde 2017-11-07 kl 14 22 28" src="https://user-images.githubusercontent.com/3284659/32495750-419b8ce0-c3c7-11e7-9b79-865de356d7f6.png">

**Comment by jon-a-nygaard** [comment]
*Internal Note: Consider using labels for grid labels. This would make support for ellispis available out of the box. It would also allow hover effects and styling.*

**Comment by oysteinmoseng** [comment]
Seems to be working fine now.

**Comment by oysteinmoseng** [comment]
Turns out it is still an issue. Labels will not overlap each other, but in some cases the label will still have a width that is greater than the cell.

**Comment by TorsteinHonsi** [comment]
Closed now.
