### ISSUE TITLE
Point.remove and Point.update don't work in the same redraw batch

### ISSUE THREAD

**Issue by Freywar** [highcharts/highcharts#7373]
#### Expected behaviour
Chart allows to remove some points and update others without redrawing after each call.

#### Actual behaviour
Certain combinations of remove and update cause an error.

#### Live demo with steps to reproduce
http://jsfiddle.net/u226dnxg/3/

Open dev tools, click "Remove", get an error. Other combinations (remove some "remove" or "update" call, remove some "redraw=false" flag etc) seem to work correctly.

#### Affected browser(s)
Any

**Comment by pawelfus** [comment]
Hi @Freywar 

Thank you for reporting the issue. 

*Internal note:*
It looks like an edge case when destroying points doesn't clear all props. Note that order of points does matter too: http://jsfiddle.net/u226dnxg/4/

**Comment by Freywar** [comment]
I researched it slightly deeper to find a workaround. The problem is in Point.index property. It updates only when render happens, but is used in Chart.get (or Point.update?) method to get the point from Serie.data array. So after I remove two first points, serie has only one point with index=2. Then update line causes Serie.data[2] to be updated (or recreated since it doesn't exist). Now I have a hole in Serie.data array and redraw method can't handle that.

If I remove some other points it might not create holes in array, but makes wrong point to be updated. And if I first update a point and then remove others, there won't be any problems with index.

In my application I have to remove points before updating others, but code below seems to help in my case:
` H.wrap(H.Point.prototype, 'remove', function (proceed, redraw) {
  const series = this.series;
  proceed.call(this, redraw);
  series.data.forEach((point, index) => point.index = index);
});`

**Comment by TorsteinHonsi** [comment]
Use used to run `series.points.indexOf(point)`, but because of #3260 we changed that so that it caches `point.index` in 6d3ad3f68b58b82a9fdfbab225e321fd10f63f6f.

I'm not sure how to handle this. If we update all `point.index`-es on every `Point.update`, we end up where we were with #3260. At the same time, @Freywar's case is obviously an issue.

**Comment by Freywar** [comment]
Can `Point.update` change the point's `index`? Wouldn't it help to update indices only when a point has been deleted?

**Comment by TorsteinHonsi** [comment]
But in order to get it right, we would need `Point.remove` to also change the index of all following points, which would take us back to #3260.
