### ISSUE TITLE
Setting extremes breaks the x-positioning of columns

### ISSUE THREAD

**Issue by nmykhailova** [highcharts/highcharts#7374]
#### Expected behaviour
Columns are positioned on the corresponding date ticks of the x axis.

#### Actual behaviour
Columns are out of sync with the x axis after setting extremes on it. Please, see jsfiddle for more details. 

#### Live demo with steps to reproduce
https://jsfiddle.net/fhyyc570/3/
If to comment out the line with setExtremes method or to remove the comment from the last line then everything works fine. 

#### Affected browser(s)
At least Mozilla Firefox and Google Chrome.

**Comment by pawelfus** [comment]
Hi @nmykhailova 

Thank you for reporting this issue! This is a bug, but when dealing with multiple operations at the same time it's recommended to set `redraw` params to false, and then call `chart.redraw()`. Take a look: https://jsfiddle.net/mx7ev7uo/

**Comment by nmykhailova** [comment]
Hi @pawelfus ,

Thank you for suggestions! 
pointRange is not an option for me, but the redraw param is helpful.
