### ISSUE TITLE
NVDA on IE reads too much useless information 

### ISSUE THREAD

**Issue by primerano** [highcharts/highcharts#7375]
#### Expected behaviour
Feel free to close this as an NVDA issue.  I just figured I would share what I see via nvda -> tools -> speech viewer.

If you go to the following chart on IE with NVDA

https://jsfiddle.net/primerano/4z2fLrxf/

the screen reader should read useful information

#### Actual behaviour

It reads a lot of junk before getting to useful information

https://jsfiddle.net/primerano/4z2fLrxf/

tab into the chart and you get 

Interactive chart. Chart. Use up and down arrows to navigate with most screen readers. region 
Chart
Created with Highstock 6.0.2
Chart
graphic
Chart
graphic
Chart
graphic

repeats about 40 times.    Do you need to add aria hidden at a higher level or should the screen reader be smart enough to ignore these?

#### Live demo with steps to reproduce
https://jsfiddle.net/primerano/4z2fLrxf/

#### Affected browser(s)

Internet Explorer.

**Comment by oysteinmoseng** [comment]
This will be much improved by the fix from #8637. NVDA/IE11 is still not an ideal combination, but seems to be working much better now. I will close this for now since we don't have a clear way to improve the markup on our end, and probably have to wait for NVDA to improve their IE11 support.

**Comment by primerano** [comment]
I'll take your word for it.  I'm stuck on 6.0.4 until #6957 is fixed. :-(
