### ISSUE TITLE
highcharts-dist has two copies of most files

### ISSUE THREAD

**Issue by pavarnos** [highcharts/highcharts#7376]
#### Expected behaviour
There should be one copy of each file 

#### Actual behaviour
There are two copies eg
https://github.com/highcharts/highcharts-dist/blob/master/modules/accessibility.js
and 
https://github.com/highcharts/highcharts-dist/blob/master/js/modules/accessibility.js

the /js/ folder appears to contain a copy of /modules/ and /themes/ and the *.js files from the root directory

**Comment by pawelfus** [comment]
Hi @pavarnos 

This is correct, since v5 we have two directories, one for JS styled Highcharts, and one for CSS styled mode, you can read more details in our [docs](https://www.highcharts.com/docs/chart-design-and-style/style-by-css).

**Comment by pavarnos** [comment]
Thanks. My apologies for not reading the docs properly. 
Is it possible to add a note to the Readme.md to explain this?

**Comment by TorsteinHonsi** [comment]
Thanks for the suggestion! See https://github.com/highcharts/highcharts-dist/#styled-mode-vs-classic.
