### ISSUE TITLE
Approximation "averages" doesn't return undefined

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#7377]
#### Issue
When approximating to days, line breaks in the Bollinger Bands indicator shouldn't show up.

This may not be necessary bug in the approximation method, but according to `sum` approx, we should return `undefined`:
```
                sum: function(arr) {
                    var len = arr.length,
                        ret;

                    // 1. it consists of nulls exclusively
                    if (!len && arr.hasNulls) {
                        ret = null;
                        // 2. it has a length and real values
                    } else if (len) {
                        ret = 0;
                        while (len--) {
                            ret += arr[len];
                        }
                    }
                    // 3. it has zero length, so just return undefined
                    // => doNothing()

                    return ret;
                },
```

I think docs should be updated too.

FYI @KacperMadej 

#### Live demo with steps to reproduce
http://jsfiddle.net/nLtpemxy/1/

#### Workaround
http://jsfiddle.net/nLtpemxy/

Set custom approximation:
```
        approximation: function(top, middle, bottom) {
          var ret = [];

          Highcharts.each(arguments, function(arr) {
            ret.push(Highcharts.approximations.average(arr));
          });

          return middle.length ? ret : undefined;
        }
```

**Comment by shicechi** [comment]
Thanks @pawelfus!

The workaround works well. However please notice that this problem also occurs on price envelope, and maybe other more.

Thanks again for the workaround.

**Comment by pawelfus** [comment]
Thank you for info! Resolving this issue will fix all indicators that use `averages` (like Bollinger bands, Price envelopes etc.).
