### ISSUE TITLE
Points are visible outside of plotArea range in vector series

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#7381]
#### Expected behaviour

Points shouldn't be rendered, when their x,y values aren't included in the actual ranges of axes.

#### Actual behaviour

Points are visible, even if their values don't belong to the axes ranges. 

#### Live demo with steps to reproduce

[http://jsfiddle.net/daniel_s/3sx6oh70/](http://jsfiddle.net/daniel_s/3sx6oh70/)

#### Affected browser(s)

All browsers

**Comment by TorsteinHonsi** [comment]
We need a fixed width to see it consistently: http://jsfiddle.net/highcharts/3sx6oh70/1/
