### ISSUE TITLE
Labels on solid-gauge charts are not correctly exported

### ISSUE THREAD

**Issue by brgbzh** [highcharts/highcharts#7382]
When you export a solid gauge chart (PNG/PDF/JPG), the label is hidden (behind the gauge).

http://jsfiddle.net/ethuxjjs/

![chart 8](https://user-images.githubusercontent.com/12527180/32562013-f40cc2e0-c4ad-11e7-8277-4a967fe8758e.png)

**Comment by pawelfus** [comment]
Hi @brgbzh 

This is caused by setting `useHTML`, but not enabling HTML in exporting won't correctly draw your chart. To enable HTML in exporting set:
```
    exporting: {
    	allowHTML: true
    },
```

Working demo: http://jsfiddle.net/ethuxjjs/1/
