### ISSUE TITLE
DataLabel is not visible after drillup in pie chart 

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7384]
#### Expected behaviour
All dataLabels should be visible in pie chart after drillup

#### Actual behaviour
When clicking on a point and then making drill-up, dataLabel of previously clicked point is not visible.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/LcwaL9sh/

Click on a point and then make a drill-up

**Comment by TorsteinHonsi** [comment]
It seems like a bug in Chrome, it fails to render the data label even though the only difference with the others is the opacity attribute.

**Comment by TorsteinHonsi** [comment]
Since it's a rendering issue in a specific browser, it isn't possible to test against the DOM, so I didn't add a regression test for it.
