### ISSUE TITLE
Bar drilldown not working in column charts

### ISSUE THREAD

**Issue by logineimer** [highcharts/highcharts#7386]
#### Expected behaviour
When creating a column chart with bar drilldowns the series type should affect it correctly. The drilldown should be displayed as a bar chart.

#### Actual behaviour
While the line drilldown (Chrome) works as expected, the bar drilldown (IE) doesn't as it shows up as a column chart.

#### Live demo with steps to reproduce
Demo: http://jsfiddle.net/ffc4jhb7/46/

Drilldown on IE: Wrong series type
Drilldown on Chrome: Correct series type

#### Affected browser(s)
Tested in Chrome

**Comment by pawelfus** [comment]
Hi @logineimer 

Thank you for reporting this issue. This is caused by fact that `bar` series is the same as `chart.inverted=true` + `column` series. Drilldown doesn't change `chart.inverted` flag, for example using `bar` series then drilling down: http://jsfiddle.net/ffc4jhb7/49/

**Comment by logineimer** [comment]
Hi @pawelfus 

Thank you very much for the quick response. You're darn right about this issue. Will there be a fix soon?

**Comment by logineimer** [comment]
Well, it might be complicated. However, the chart doesn't work as intended so this issue should be solved. :-)

**Comment by TorsteinHonsi** [comment]
Love your attitude :)

Ignoring the drilldown animations, we can switch from a column to a bar by running `chart.update` to set it inverted: http://jsfiddle.net/highcharts/ffc4jhb7/50/.

In order to resolve this issue I think we should resolve this on a lower level - not in drilldown, but in `chart.addSeries`, `series.update` etc. However there's a problem of logic nature. A column series can also exist in an inverted chart, so we don't know if we actually should shift...

**Comment by logineimer** [comment]
Hello @TorsteinHonsi !

Thank you very much for this quick solution. This is great and should work for now! It's funny because I had exactly the same idea about changing the `chart.inverted` flag in an event. My solution didn't work as intended when triggering the update on the chart drilldown event. Your solution includes the `drilldown` and `drillup` event which seems to work better. I will definitely test it as the animation isn't that important. Furthermore, I hope you will fix the basic problem in the future.

Best regards

**Comment by logineimer** [comment]
Huuups, I accidentally closed the issue. That's your privilege.

**Comment by laventnc** [comment]
worth noting that the proposed solution only works for drilling down one level... at the second level, the data is simply added to the chart. This is true even if you clear the xAxis names ... see the following fiddle: http://jsfiddle.net/q4d6otnv/1/

**Comment by KacperMadej** [comment]
@laventnc 
About the edit: If you could create a simple demo for the problem, then we could check if this is related or should require a separate issue.

**Comment by laventnc** [comment]
the link i posted contains the problem with drilling down to a second level. Just click Microsoft -> v11.0.
you should see that (a, b, c) get added to the series, instead of replacing the points

**Comment by sansmash** [comment]
> `update`

Any suggestion on how we can resolve for 'bar' to 'column' drilldown case? This solution isn't working.

**Comment by sansmash** [comment]
> Love your attitude :)
> 
> _Edited_
> Ignoring the drilldown animations, we can switch from a column to a bar by running `chart.update` to set it inverted: http://jsfiddle.net/highcharts/ffc4jhb7/51/.
> 
> In order to resolve this issue I think we should resolve this on a lower level - not in drilldown, but in `chart.addSeries`, `series.update` etc. However there's a problem of logic nature. A column series can also exist in an inverted chart, so we don't know if we actually should shift...
> 
> For now, this snippet should provide the feature you request, except that the animations don't really describe the drilling action:
> 
> ```js
> // Plugin that makes drilling to "bar" series invert the chart (#7386)
> (function (H) {
>     function handleInversion(e) {
>         var chart = this,
>             inverted = Boolean(e.seriesOptions && e.seriesOptions.type === 'bar');
>         if (inverted !== chart.inverted) {
>             setTimeout(function () {
>                 chart.update({
>                     chart: {
>                         inverted: inverted
>                     }
>                 });
>             }, 0);
>         }
>     }
>     H.addEvent(H.Chart.prototype, 'drilldown', handleInversion);
>     H.addEvent(H.Chart.prototype, 'drillup', handleInversion);
> }(Highcharts));
> ```

Any suggestion on how we can resolve for 'bar' to 'column' drilldown case? This solution isn't working.

**Comment by pawelfus** [comment]
Hmm. something like this should work: http://jsfiddle.net/BlackLabel/73dbct2m/6/

```js
(function(H) {
  function handleInversion(e) {
    var chart = this,
      inverted = Boolean(e.seriesOptions && e.seriesOptions.type === 'bar');

    if (inverted !== chart.inverted) {
      setTimeout(function() {
        chart.update({
          chart: {
            inverted: !chart.inverted
          }
        });
      }, 0);
    }
  }
  H.addEvent(H.Chart.prototype, 'drilldown', handleInversion);
  H.addEvent(H.Chart.prototype, 'drillup', handleInversion);

  H.wrap(H.Chart.prototype, 'propFromSeries', function(p) {

    p.apply(this, Array.prototype.slice.call(arguments, 1));

    if (this.options.chart.inverted !== undefined) {
      this.inverted = this.options.chart.inverted;
    }

  });
}(Highcharts));
```

**Comment by sansmash** [comment]
> Something like this should work: http://jsfiddle.net/BlackLabel/73dbct2m/6/
> 
> ```js
> (function(H) {
>   function handleInversion(e) {
>     var chart = this,
>       inverted = Boolean(e.seriesOptions && e.seriesOptions.type === 'bar');
> 
>     if (inverted !== chart.inverted) {
>       setTimeout(function() {
>         chart.update({
>           chart: {
>             inverted: !chart.inverted
>           }
>         });
>       }, 0);
>     }
>   }
>   H.addEvent(H.Chart.prototype, 'drilldown', handleInversion);
>   H.addEvent(H.Chart.prototype, 'drillup', handleInversion);
> 
>   H.wrap(H.Chart.prototype, 'propFromSeries', function(p) {
> 
>     p.apply(this, Array.prototype.slice.call(arguments, 1));
> 
>     if (this.options.chart.inverted !== undefined) {
>       this.inverted = this.options.chart.inverted;
>     }
> 
>   });
> }(Highcharts));
> ```


> Something like this should work: http://jsfiddle.net/BlackLabel/73dbct2m/6/
> 
> ```js
> (function(H) {
>   function handleInversion(e) {
>     var chart = this,
>       inverted = Boolean(e.seriesOptions && e.seriesOptions.type === 'bar');
> 
>     if (inverted !== chart.inverted) {
>       setTimeout(function() {
>         chart.update({
>           chart: {
>             inverted: !chart.inverted
>           }
>         });
>       }, 0);
>     }
>   }
>   H.addEvent(H.Chart.prototype, 'drilldown', handleInversion);
>   H.addEvent(H.Chart.prototype, 'drillup', handleInversion);
> 
>   H.wrap(H.Chart.prototype, 'propFromSeries', function(p) {
> 
>     p.apply(this, Array.prototype.slice.call(arguments, 1));
> 
>     if (this.options.chart.inverted !== undefined) {
>       this.inverted = this.options.chart.inverted;
>     }
> 
>   });
> }(Highcharts));
> ```

Second category ("Chrome") isn't working according to the drilldown series type!

**Comment by sansmash** [comment]
Ideally, when drilldown series is not provided, then points doesn't drilldown. If you make drilldown series empty in this case, it still drills down to the main series!! 

Other issue i'm facing here is that, not all data points are working based on drilldown series type. I could provide you the fiddle but for now, anything you can check with above case.? 

I'm a beginner and couldn't debug this myself. Sorry to comeback again and again.

**Comment by pawelfus** [comment]
Hi @sansmash 

I suggest to contact our support team: https://www.highcharts.com/blog/support/ - no need to scream :) Just to answer your questions:

> Ideally, when drilldown series is not provided, then points doesn't drilldown. If you make drilldown series empty in this case, it still drills down to the main series!!

Don't forget to remove `data[index].drilldown` option: http://jsfiddle.net/BlackLabel/73dbct2m/7/

> Other issue i'm facing here is that, not all data points are working based on drilldown series type. I could provide you the fiddle but for now, anything you can check with above case.?

Please, provide this demo our support team.

> I'm a beginner and couldn't debug this myself. Sorry to comeback again and again.

Don't worry, we all were beginners once :)
