### ISSUE TITLE
Reflow Cause Different Chart Tickers in yAxis

### ISSUE THREAD

**Issue by wxy325** [highcharts/highcharts#7387]
Hi, it seems that for some charts with some specific chart configuration in `chart.height` and `yAxis.tickPixelInterval`, the tickers of yAxis will change after calling `reflow`.

#### Steps to duplicated
1. Open JSFiddle provided below (https://jsfiddle.net/fde9wh15/1/) 
2. Notices that the tickers of yAxis are `['0', '10k', '20k', '30k']`
3. Click 'Reflow' button
4. Notices that the tickers of yAxis are `['0', '5k', '10k', '15k', '20k', '25k']` now

#### Expected behaviour
The tickers of the yAxis should be the same since there is not changed in the container `div`

#### Actual behaviour
The tickers of yAxis change from `['0', '10k', '20k', '30k']` to `['0', '5k', '10k', '15k', '20k', '25k']`

#### Live demo with steps to reproduce

https://jsfiddle.net/fde9wh15/1/

#### Affected browser(s)
Chrome Version 60.0.3112.113
Safari 10.1.2 (12603.3.8)
(Maybe not a bug for specific browser, but I only have Chrome and Safari in my laptop)

**Comment by pawelfus** [comment]
Hi @wxy325 

Thank you for reporting this issue. This is caused by approximate tickInterval, calculated from [`yAxis.tickPixelInterval`](https://api.highcharts.com/highcharts/yAxis.tickPixelInterval). In this case it means it can change after redraw/reflow, because we have more information about the length of the axis.

**Comment by wxy325** [comment]
Hi @pawelfus , thank you for you reply! Will it be fixed in a future version? Or do I have any other way (such as other configiration) to keep the original layout?

**Comment by pawelfus** [comment]
You can use `tickAmount` or use `tickInterval` - it's more strict. Take a look: https://jsfiddle.net/fde9wh15/4/ Still, there may be some edge cases when ticks are recalculated.
