### ISSUE TITLE
Sunburst chart - Show percentage share with respect to parent level or percentage share with respect to whole chart

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#7389]
#### Expected behaviour
Percentage share is used to depict the part-to-whole relationship in a chart.

Currently, the point.percentage property in Pie chart series data labels can be used to show the percentage share with respect to the whole chart : http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/pie-basic/
Expected behavior is to show percentage share in Sunburst chart. 
Refer the example on this link: https://www.grapecity.com/en/blogs/sunburst-chart-roadmap-what-would-you-like-to-see
Highcharts API reference doesn't show that it supports point.percentage for Sunburst charts. 
Is there any way to achieve this without doing the calculations in data labels formatter function?
Or if percentageWithRespectToWholeChart and percentageWithRespectToParentLevel properties can be provided in "point"?

#### Actual behaviour
Percentage share can be achieved in Sunburst chart by calculating the percentage and defining it in data labels formatter function.

#### Live demo with steps to reproduce
JS Fiddle: http://jsfiddle.net/cre0psov/1/

**Comment by pawelfus** [comment]
Hi @amruta30 

Thank you for more ideas for sunburst series! We really appreciate this! :)

At this moment, you need to use formatter to calculate these percentages. Could you tell us why `formatter` won't work for you? Of course, we are aware that `percentage` and `percentageWithRespectToParentLevel` would be useful in `dataLabels.format` so you don't need to calculate this.

**Comment by amruta30** [comment]
@pawelfus Yeah, i can use formatter to calculate the percentages for time being. Just wanted to add that the attributes such as percentage and percentageWithRespectToParentLevel would be great to have! Thanks.
