### ISSUE TITLE
To achieve exploded sections behaviour in Sunburst chart similar to pie chart

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#7390]
#### Expected behaviour

Is there any way in Highcharts to achieve the exploded sections behavior in Sunburst chart? Or if  "sliced" and "slicedOffset" properties be made available for Sunburst chart?
 
Following are the examples of Sunburst chart with exploded sections:
Link 1: http://helpcentral.componentone.com/nethelp/FlexChartWin/SunburstChart.html
Link 2: https://www.grapecity.com/en/blogs/getting-started-with-net-sunburst-chart-for-wpf-winforms-and-uwp

#### Actual behaviour

Currently, pie chart has a property "sliced" that shows exploded section in pie chart.
Refer: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/point/sliced/
However, Highcharts API reference does not show any property to support this behaviour in Sunburst chart. Slice or exploded sections feature is not available in Highcharts Sunburst chart.

#### Live demo with steps to reproduce
JS Fiddle: http://jsfiddle.net/ng3bgckt/
I tried setting the data point "sliced" property in the above example.The property sliced is set as true in the data point Asia, but it wasn't shown as exploded section.

**Comment by pawelfus** [comment]
Thanks for the idea!

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard FYI. In short, the request is for a `sliced` option for the sunburst points, and it should also offset the children.
