### ISSUE TITLE
New feature for Highcharts Gauge-Activity

### ISSUE THREAD

**Issue by lelogrott** [highcharts/highcharts#7392]
Would be interesting if was possible to make the tracks centered in the 0 starting angle.
This could also allow the tracks to have each one their own `startAngle` and `endAngle` variable.

Allowing something like this:
<img width="213" alt="screen shot 2017-11-10 at 5 14 11 pm" src="https://user-images.githubusercontent.com/9098681/32675030-915917a8-c63c-11e7-8750-f65bd86c6c3a.png">

The current  behavior make all the tracks to start from the same angle. Example with `startAngle: -90` and `endAngle: 270`:
<img width="415" alt="screen shot 2017-11-10 at 2 23 19 pm" src="https://user-images.githubusercontent.com/9098681/32675080-c41063f4-c63c-11e7-8388-c6fd27aa2d73.png">

**Comment by wesklei** [comment]
had the same problem!

**Comment by pawelfus** [comment]
Hi @lelogrott 

Thank you for sharing your idea!

**Workaround:**
Modify start angle:
```
(function(H) {
  H.wrap(H.seriesTypes.solidgauge.prototype, 'drawPoints', function(p) {
    var yAxis = this.yAxis,
      oldRad = yAxis.startAngleRad;

    yAxis.startAngleRad = (oldRad - yAxis.translate(this.points[0].y, null, null, null, true)) / 2;

    p.apply(this, Array.prototype.slice.call(arguments, 1));

    yAxis.startAngleRad = oldRad;
  });
})(Highcharts)
```

Working demo: http://jsfiddle.net/jzhfsrf7/ (don't miss changed `pane.startAngle` and `pane.endAndle`)

**Comment by lelogrott** [comment]
Thanks @pawelfus !
