### ISSUE TITLE
Infinity value breaks Heatmap

### ISSUE THREAD

**Issue by chabb** [highcharts/highcharts#7394]
There are some solutions to handle those Infinity value, but i think the default behaviour can be better. Right now, it breaks the legend, and all cells are black

#### Live demo with steps to reproduce
https://jsfiddle.net/chab/4aqhB/1091/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thank you for your suggestion.

**Comment by TorsteinHonsi** [comment]
Related to https://github.com/highcharts/highcharts/issues/3571#issuecomment-342964453. I'll add a check for `Infinity` and `-Infinity` in the `isNumber` function, it doesn't seem to affect performance.

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: https://jsfiddle.net/highcharts/4aqhB/1095/
