### ISSUE TITLE
Boost: connectNulls is not working

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7395]
#### Behaviour
When setting connectNulls to false the null gaps are connected.

#### Live demo with steps to reproduce
http://jsfiddle.net/vd1y2cjx/

compare with the no-boost demo: 
http://jsfiddle.net/vd1y2cjx/1/

**Comment by TorsteinHonsi** [comment]
As we mention in [the docs](https://www.highcharts.com/docs/advanced-chart-features/boost-module), not all features of the SVG rendering engine are available in Boost mode. 

I added the _Enhancement_ label to this issue, as we need to consider whether adding `connectNulls` support in Boost is feasible.

**Comment by NeuwenWolf** [comment]
I would like to add that this is not documented in the docs, nor is it documented in the "Notes for boost" in the module itself. 

This made it quite frustrating when it occurred for me as I assumed it was something I was doing wrong.

It might save someone else many hours of fiddling with the code if it were documented directly in the boost module with the other limitations. 


This behaviour may make highcharts entirely unusable for our use-case as we often deal with large, gappy datasets:
![image](https://user-images.githubusercontent.com/12142465/34690151-3df837f8-f475-11e7-9bda-f97c9f42826f.png)
Our customers would rightly not know how to interpret such a chart.

I attempted a work-around of setting all nulls to -1, and setting my yAxis ymin to 0, but in such a case, the negative values are plotted as 0 for some reason that I assume is just another expression of the connectNulls issue:
![image](https://user-images.githubusercontent.com/12142465/34690273-b5ccec24-f475-11e7-97bd-1f2c19a59eb6.png)

If there are any other workarounds for presenting such charts in boost, I'd love your feedback as this is the final major hurdle in our highcharts journey.

**Comment by TorsteinHonsi** [comment]
@cvasseng Can we implement [connectNulls](https://api.highcharts.com/highcharts/plotOptions.series.connectNulls) in the Boost module?

**Comment by cvasseng** [comment]
@TorsteinHonsi : I can take a look. It's not entirely trivial due to the way the vertex buffers are built. We'd basically need to split the buffer when encountering null values, and then batch render the splits for each series.

**Comment by TorsteinHonsi** [comment]
Closed by 4ff2d10aa1a5daeb371fb5da1015c8b201aedd7a

**Comment by NeuwenWolf** [comment]
Fantastic! you guys are the best.

**Comment by TorsteinHonsi** [comment]
@NeuwenWolf Just an off-topic comment on your "Daily totals" chart above - it looks like you're using a category axis to display dates. Your chart will probably perform (and look) better if you use a true `datetime` axis and let Highcharts determine the appropriate tick intervals.

**Comment by NeuwenWolf** [comment]
Thanks for the heads up, I've made the change.

Why is there a performance impact and what are the differences between the
category type and the datetime type?

I'm surprised you noticed. The difference seems quite subtle to me...

**Comment by TorsteinHonsi** [comment]
The difference is that a datetime axis is created to intelligently put labels on _round_ dates, like the first of each month for example. The category axis just blindly removes every n'th label. The potential performance implication is that it's trying to add as many category labels as possible, while the datetime axis doesn't have to because the user can interpolate time. Again, it is not a requirement, just best practice. See https://www.highcharts.com/docs/chart-concepts/axes#what-axis.
