### ISSUE TITLE
Legend items cut out with paging

### ISSUE THREAD

**Issue by boba-keyost** [highcharts/highcharts#7396]
#### Expected behaviour
Height of items in vertical legend should be calculated from height of text AND Symbol.

#### Actual behaviour
Top of the first item on every page in legend is cut out.
I guees, it happens because legend.lineHeight property calcualted from legend item's text bound box.
`legend.itemHeight = itemHeight = Math.round(
			item.legendItemHeight || bBox.height || legend.symbolHeight
);`

#### Live demo with steps to reproduce
https://jsfiddle.net/7pto3z2h/

**Comment by pawelfus** [comment]
Hi @boba-keyost 

Thank you for reporting the bug and the hint!

**Workaround:**
Use `legend.itemMarginTop` to prevent this issue: https://jsfiddle.net/yux4w0q6/ - still text is not vertically aligned to the legend symbol.

**Comment by TorsteinHonsi** [comment]
As far as I can see the paging is working correctly, though I agree that the overlapping is a bug: https://jsfiddle.net/highcharts/7pto3z2h/2/

**Comment by TorsteinHonsi** [comment]
I tried replacing the line in question with this:
```js
		legend.itemHeight = itemHeight = Math.round(
			item.legendItemHeight || Math.max(
				bBox.height || 0,
				legend.symbolHeight || 0
			)
		);
```
That prevents the overlapping. But the symbol is still aligned to the baseline of the text.

What do you think?

![skjermbilde 2017-11-15 kl 15 51 28](https://user-images.githubusercontent.com/227836/32842252-e2865436-ca1c-11e7-98ec-8cc976eee8ab.png)

**Comment by matt-hoskins** [comment]
Just to note that the samples linked from the documentation on legend navigation are affected by this at present.

Most of the settings on this page:
https://api.highcharts.com/highcharts/legend.navigation

Link to this:
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/legend/navigation/

And as you can see the the top of the circle symbol on the first legend entry is being clipped.
