### ISSUE TITLE
Updating chart type changes series order

### ISSUE THREAD

**Issue by zimmemit** [highcharts/highcharts#7397]
#### Actual behaviour
In highstock with multiple series, when the series type is updated, it changes the order that series are appearing in. In the example, the blue line starts furthest back after updating, it moves to the front. 

Am I doing something terribly wrong with updating the series type and/or is this the expected behavior? 

#### Live demo with steps to reproduce
https://jsfiddle.net/zimm56/nhcn8f5b/

#### Affected browser(s)
Non browser specific

**Comment by pawelfus** [comment]
Hi @zimmemit 

Thank you for reporting this issue.

**Workaround:**
Define `series.zIndex` when initializing series: https://jsfiddle.net/nhcn8f5b/4/

*Internal note:*
It used to work with 2.0.4 (2010), but issue-by-commit doesn't load that old versions.

**Comment by TorsteinHonsi** [comment]
Minimal demo: https://jsfiddle.net/highcharts/nhcn8f5b/5/

It also happens in basic Highcharts.

**Comment by TorsteinHonsi** [comment]
It happened because we destroy the groups when updating series type, and re-create them without a Z index, which means they were appended to the end. I can see no reason why to destroy the groups when we only have to update the Z index if the `zIndex` option change. So I refactored this.
