### ISSUE TITLE
Calling update with pointFormat for the tooltip not always change it

### ISSUE THREAD

**Issue by DiegoCardoso** [highcharts/highcharts#7398]
We are using Highcharts 5.0.14, but I found the same issue with Highcharts 6 as well.

#### Expected behaviour
Create a new chart with no tooltip options.
`Chart.update` method called with a `tooltip.pointFormat` option should update it.

#### Actual behaviour
`Chart.tooltip.options.pointFormat` is updated with the new configuration, but when tooltip is opened, user is presented with the default one.

#### Live demo with steps to reproduce
https://jsfiddle.net/alvarezg/rv12v1nj/

#### Affected browser(s)
Tested on latest versions of Chrome, Firefox and Safari.

PS.: If the chart is created with a custom `tooltip.pointFormat`, updating it works as expected.

**Comment by pawelfus** [comment]
Hi @DiegoCardoso 

Thank you for reporting this issue. In other words, setting default format in chart init, we get the desired tooltip formats: https://jsfiddle.net/393r3bn2/

**Workaround:**
https://jsfiddle.net/393r3bn2/

```
var chart = Highcharts.chart('container', {
  title: {
    text: 'Logarithmic axis demo'
  },

  xAxis: {
    tickInterval: 1
  },
  
  tooltip: {
    // Default tooltip
    pointFormat: '<span style="color:{point.color}">\u25CF</span> {series.name}: <b>{point.y}</b><br/>',
    headerFormat: '<span style="font-size: 10px">{point.key}</span><br/>'
  },
  
  series: [{
    data: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512],
    pointStart: 1
  }]
});
```

**Comment by DiegoCardoso** [comment]
If you only put an empty object, it will also work as expected.

**Demo:**
https://jsfiddle.net/xwkgs1yf/

```
var chart = Highcharts.chart('container', {
  title: {
    text: 'Logarithmic axis demo'
  },

  xAxis: {
    tickInterval: 1
  },
  
  tooltip: {
  },
  
  series: [{
    data: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512],
    pointStart: 1
  }]
});
```
