### ISSUE TITLE
Highstock crosshair stucks

### ISSUE THREAD

**Issue by likwifi** [highcharts/highcharts#7399]
#### Actual behavior
Highstock crosshair sometimes stuck on old point but tool tip is updating

#### Live demo with steps to reproduce
Highstock version  v2.0.4 (2014-09-02)
http://jsfiddle.net/znvkh14o/9/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @likwifi 

Please update Highstock, version v2.0.4 is no longer supported. Working demo with Highstock v6: http://jsfiddle.net/znvkh14o/10/

**Comment by likwifi** [comment]
@pawelfus I can't upgrade entire product's charting library for fixing minor issue. Can someone please share changes which fixes this issue.

**Comment by pawelfus** [comment]
It looks like 9fd4ca0 commit fixed the issue. Note: fix may or may not require more changes in the source code to work properly.
