### ISSUE TITLE
Data table is rendered incorrectly for charts with bullet and line series

### ISSUE THREAD

**Issue by AleksueiR** [highcharts/highcharts#7400]
#### Expected behaviour
Headers for `bullet` and `line` series rendered on a single line; `bullet` series subheaders underneath the corresponding header.
![](https://i.imgur.com/Nzs07Tk.png)

#### Actual behaviour
Headers for `bullet` series are rendered as the top line and the `line`  series header is rendered underneath one of the `bullet` header.

![](https://i.imgur.com/aAv5LfT.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/ouroborosDragon/aga1k7nd/7/

#### Affected browser(s)
Chrome, IE11, likely others.

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng I think it would be cleaner if we just do what we have to do in the export-data module instead of wrapping it from the accessibility module.

**Comment by oysteinmoseng** [comment]
Yes, it would for sure be a lot cleaner to build the accessibility functionality into export-data. We are just talking about simple markup after all.

**Comment by AleksueiR** [comment]
@pawelfus Thank you for the workaround with the formatter since I do need the accessibility module enabled.

Missing cells in the first row can be fixed by adding a null data point (`{ x: 6, y: null }`) to the "Bullet Series 4": https://jsfiddle.net/ouroborosDragon/twkvLhd0/2/

**Comment by AleksueiR** [comment]
@TorsteinHonsi I think this will be the best solution as I ran into another problem.

I need the table to be rendered in a different node, not immediately after the chart, so I specify a custom `viewData.onclick` implementation under `menuItemDefinitions`. 
```js
viewData: function() { customDiv.innerHTML = this.getTable(); }
```
This works well enough and the table is rendered where specified. However, none of the accessibility attributes are applied to this table anymore since the accessibility module [wraps the original `viewData` prototype function](https://github.com/highcharts/highcharts/blob/9ece0d40f7040ae87cf6aaf3661b9eb75646702e/js/modules/screen-reader.src.js#L817) to add these attributes. The original function is no longer called and no attributes are applied.

Any suggestions on how to deal with this?

**Comment by TorsteinHonsi** [comment]
You can create your own `chart.dataTableDiv` to hijack the logic in the `viewData` function: http://jsfiddle.net/quL1ajuc/

**Comment by AleksueiR** [comment]
@TorsteinHonsi thanks, that will do.

**Comment by AleksueiR** [comment]
Err, this doesn't work together with the accessibility module, since the function adding accessibility attributes is skipped if the `dataTableDiv` already defined: https://github.com/highcharts/highcharts/blob/9ece0d40f7040ae87cf6aaf3661b9eb75646702e/js/modules/screen-reader.src.js#L818

**Comment by oysteinmoseng** [comment]
@AleksueiR I think you would want to add these attributes manually here, the accessibility module will not really make intelligent guesses with your custom table regardless.

**Comment by AleksueiR** [comment]
@oysteinmoseng I'll probably do that, but I'm not using a custom table here - I'm just trying to render it in a custom location.

Works fine: http://jsfiddle.net/ouroborosDragon/quL1ajuc/3/
Stops working after adding the accessibility module: http://jsfiddle.net/ouroborosDragon/quL1ajuc/2/

**Comment by oysteinmoseng** [comment]
@AleksueiR Ouch, yes, that is obviously not intentional. I'll push a quick fix.

**Comment by AleksueiR** [comment]
@oysteinmoseng Thanks!

**Comment by oysteinmoseng** [comment]
@AleksueiR Try this: http://jsfiddle.net/quL1ajuc/4/

**Comment by AleksueiR** [comment]
Yeap, the table renders now, but no accessibility attributes are applied. 
Is this the intended behaviour - if I'm rendering the table outside of the default location, I should be responsible for its accessibility attributes?

**Comment by oysteinmoseng** [comment]
@AleksueiR Intended for now, but we will be rewriting this logic and moving the accessibility attributes to the `export-data` module eventually. Looking at the code, however, I am not sure why the accessibility logic is bypassed in this case. I think it may have been meant as a safeguard against adding the table multiple times, but that does not seem to be an issue regardless now.

**Comment by AleksueiR** [comment]
@oysteinmoseng Fair enough. I'll write my own accessibility logic for now. Thank you for the help!

I wonder if it makes sense to modify the [`viewData` prototype function](https://github.com/highcharts/highcharts/blob/06c986dc2bbeb0718c747dcd1c588aac4f8f5eee/js/modules/export-data.src.js#L525) so it accepts an optional node reference for the table to be rendered on top of. If not specified, it falls back to the default location.

**Comment by oysteinmoseng** [comment]
@AleksueiR You can of course do that, although that is kind of what `chart.dataTableDiv` does

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng Will you do the change we agreed on? Make the `export-data.js` table aria-compatible out of the box, so that we can remove the override in `accessibility.js`.
