### ISSUE TITLE
Scatter chart with wrong thousands and decimal separators

### ISSUE THREAD

**Issue by MiroLiska** [highcharts/highcharts#7401]
#### Expected behaviour
The scatter chart should accept the regional 'lang' setting for the thousands and decimal separators.

#### Actual behaviour
The axis have correct decimal separator, but the thousands separator is missing. The value for x tooltip is formatted with default settings, 'lang' will be ignored.

#### Live demo with steps to reproduce
Please see http://jsfiddle.net/8np6g814/

![chartbug](https://user-images.githubusercontent.com/23024867/32793069-3729ab9a-c965-11e7-96d5-57542793b066.png)

**Comment by KacperMadej** [comment]
Thank you for reporting the bug.

Minimal demo: http://jsfiddle.net/BlackLabel/8np6g814/1/

**Comment by MiroLiska** [comment]
I have adjusted your demo to show that the thousands separators on axes do not work for numbers >=1000 <10000 . See http://jsfiddle.net/8np6g814/2/

**Comment by KacperMadej** [comment]
@MiroLiska The part of the problem you shown is a duplicate of this issue: https://github.com/highcharts/highcharts/issues/3811

The tooltip case should be resolved through the commit linked above this comment.

**Comment by MiroLiska** [comment]
@KacperMadej  Thanks for a quick fix. It works, but when I read the comments from Torsterin for #3811, I have realized that there may be problem now if the X axis shows years. Would not you format the years now with thousands separator as well? At the moment I have solved my problem differently - I have simply used the tooltip.pointFormat and used the required formatting strings, e.g. {point.y:,2f} . That solves my issue good enough.

**Comment by KacperMadej** [comment]
@MiroLiska That would resolve the problem, but I am not sure it would look good - it's not something that a user usually expects. However, the issue has status `undecided`, so it looks like @TorsteinHonsi is not convinced either. Something more than few opinions might tip the scale - Y YYY is not a popular format for date, or at least I cannot find it anywhere.

**Comment by MiroLiska** [comment]
Hi. From my point of view, the fix is not needed, since I solved it with a formatting string as described above.
