### ISSUE TITLE
Highmaps should removeFocusBorder when redrawing a map.

### ISSUE THREAD

**Issue by primerano** [highcharts/highcharts#7402]
#### Expected behaviour
Highmaps should removeFocusBorder when redrawing a map.

#### Actual behaviour
Highmaps does not removeFocusBorder when redrawing a map.

#### Live demo with steps to reproduce
https://jsfiddle.net/primerano/m5cg0vmt/

tab into Maryland map and select Worcester or other. 
now switch to Alaska

The Worcester focus border is still set

#### Affected browser(s)
Assuming all

**Comment by pawelfus** [comment]
Hi @primerano 

Thanks! Tested with osx+chrome v62.0.3202.62 (Official Build) (64-bit) - the same issue.
