### ISSUE TITLE
zoomType 'x' not working on windbarb series with immense amounts of data

### ISSUE THREAD

**Issue by purejoy** [highcharts/highcharts#7403]
#### Expected behaviour
zoom by dragging the mouse

#### Actual behaviour
stuck while dragging, yielding ' Uncaught TypeError: Cannot read property 'slice' of undefined'.
Cannot reproduce the problem after reducing the amount of data.

#### Live demo with steps to reproduce

http://jsfiddle.net/tushita/6ntcvc6u/

#### Affected browser(s)
Chrome 63.0
Firefox 57

**Comment by pawelfus** [comment]
Hi @purejoy 

Thank you for reporting this bug. We can workaround this bug by setting `series.getExtremesFromAll` to true: http://jsfiddle.net/6ntcvc6u/1/ - however see internal note below.

*Internal note:*
It's also broken with our demo: http://jsfiddle.net/amgqqjfb/ - arrows are misplaced after zoom. The main issue here is with `cropData` (original error), but we don't hide points outside the given range.
