### ISSUE TITLE
csv export does not work on pie chart if the data: name is empty

### ISSUE THREAD

**Issue by ysu2** [highcharts/highcharts#7404]
#### Expected behaviour
csv to export 

#### Actual behaviour
no export happening
Js error: "missing xAxis" on line 304 in export-data.js (module, using src version) 
(version 6.0.3)

#### Live demo with steps to reproduce
http://jsfiddle.net/9eo3tz8n/1/

#### Affected browser(s)
probably all

**Comment by pawelfus** [comment]
Hi @ysu2 

Thank you for reporting this bug!

**Comment by TorsteinHonsi** [comment]
Original demo with the fix applied: http://jsfiddle.net/highcharts/9eo3tz8n/2/
