### ISSUE TITLE
format don't work with exponential numbers

### ISSUE THREAD

**Issue by xrado** [highcharts/highcharts#7405]
#### Expected behaviour
Highcharts.format('num {value:.8f}',{value:8.3000000e-7})
"num 0.00000083"

#### Actual behaviour
Highcharts.format('num {value:.8f}',{value:8.3000000e-7});
"num 8.30000000e-7"

#### Live demo with steps to reproduce
http://jsfiddle.net/xrado/jyLh6pqn/

see tooltip on the smallest bar

#### Affected browser(s)
probably all

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.

**Comment by xrado** [comment]
👍🏼

**Comment by xrado** [comment]
hi,

this still doesn't work with latest hc
I have on a serie 
tooltip: { valueDecimals: 8 ..

using highchairs 7.1.1 StockChart

**Comment by KacperMadej** [comment]
Hi @xrado 

`9.0-e7` is a correct number and it is meeting the decimals requirement as far as I can tell.

If you want to have a different format you could use tooltip [`formatter`](https://api.highcharts.com/highcharts/tooltip.formatter) and process numbers as you wish.
