### ISSUE TITLE
highcharts downloading data labels are missing

### ISSUE THREAD

**Issue by 6anji** [highcharts/highcharts#7407]
#### Expected behaviour
i need  when i am downloading the chart the result should be like this
![chart 1](https://user-images.githubusercontent.com/33681492/32875425-f3e5db10-cabd-11e7-8fd4-107914fbfb33.jpeg)

#### Actual behaviour

when iam downloading the stack bar chart in highchart the data labels are missing 
![prblm](https://user-images.githubusercontent.com/33681492/32874736-12d7c438-caba-11e7-874b-3f7adad40415.png)
![result](https://user-images.githubusercontent.com/33681492/32874737-1312d7bc-caba-11e7-90ae-26d39d709583.png)

**Comment by pawelfus** [comment]
Hi @6anji 

This is caused by the size of the container. If container is too small, overlapping dataLabels are hidden, you can disable this option (or make it less sensitive), see our [docs](https://api.highcharts.com/highcharts/plotOptions.bar.dataLabels.allowOverlap).

**Comment by 6anji** [comment]
thank you for ur rply but if  i am using that allowoverlap when iam giving the count in 180,160,198,6015 like this the data labels are mixing once see one more bug i raised and check once
