### ISSUE TITLE
Labels are not rendered when xAxis.labels.autoRotation = false 

### ISSUE THREAD

**Issue by stephan-hof** [highcharts/highcharts#7409]
#### Expected behaviour
Under the following situation

* ```xAxis.labels.autoRotation``` is set to ```false```
* x-Axis labels are set via the ```xAxis.categories``` option
* Number of labels inside the categories array are too many to display them all.

The chart should only display a portion of the labels.
However the ones which are shown, should be readable and not having a rotation.

#### Actual behaviour
No labels are shown.

#### Live demo with steps to reproduce
http://jsfiddle.net/Lbt3asp8/

The problem should be immediately visible.

I commented out the ```labels: {autoRotation: false}``` and then the x-Axis is rendered as expected.

#### Affected browser(s)
I tested with the following browsers and all of them have the issue.

* google chrome Version 62.0.3202.89
* firefox 52.4.0

**Comment by pawelfus** [comment]
Hi @stephan-hof 

Thank you for reporting this issue. 

We can see what exactly happens using a bit different categories: http://jsfiddle.net/Lbt3asp8/3/ - by default, `autoRotation` changes the tick interval for categorized xAxis, however without this option, we don't change `tickInterval` (defaults to 1, [docs](https://api.highcharts.com/highcharts/xAxis.tickInterval)). In this case we use ellipsis for labels (if we can) and hide all others that don't fit in the category slot. Note it's a space for category itself, not the label on the xAxis.

We can disable ellipsis/overflow: http://jsfiddle.net/Lbt3asp8/4/ - but labels will overlap. I think we should change `tickInterval` the same way as we do for `autoRotation`.

**Comment by stephan-hof** [comment]
Hi,

thanks for the quick response and your conclusion
> I think we should change tickInterval the same way as we do for autoRotation

makes much sense to me as well.

For now  use the following workarounds:
* setting tickInterval manually to a static value, but it assumes that the chart size does not change
* using pointStart and pointInterval, but this works not for all kind of data.

**Comment by TorsteinHonsi** [comment]
As far as I can see there is no inconsistency here - `autoRotation: false` behaves the same as `autoRotation: [0]`: http://jsfiddle.net/Lbt3asp8/5/. Once there is enough space for the labels, they will render.

Even with `autoRotation`, the tick layout algorithm doesn't look at the text length, it only looks at the line height. So when the ticks are horizontal, it doen't know how many ticks to skip. Demoed with a slider: http://jsfiddle.net/Lbt3asp8/6/
