### ISSUE TITLE
Bubble chart (relations between bubbles)

### ISSUE THREAD

**Issue by samokspv** [highcharts/highcharts#7410]
Hello! 
Please can you tell me, is it possible to create relations between bubbles (lines from one bubble to other(s))?
```
Example:
SE->FL->NL
FL->DE
SE->BE->DE
DE->NL
```
Demo:
http://jsfiddle.net/2pLog7fw/

**Comment by pawelfus** [comment]
Hi @samokspv 

If you have questions, please contact with our [support](https://www.highcharts.com/support). We use github for reporting bugs.

To answer your question: you can use scatter series to connect bubbles: http://jsfiddle.net/2pLog7fw/1/

**Comment by samokspv** [comment]
Thanks! This is what I need http://jsfiddle.net/2pLog7fw/1/.
