### ISSUE TITLE
Chart axis disappear, when navigator is exercised, after disabling of series

### ISSUE THREAD

**Issue by mynameiswhat1** [highcharts/highcharts#7411]
#### Expected behaviour
Chart axis should not disappear due to a navigator change

#### Actual behaviour
Chart axis disappear, when navigator is exercised, after disabling of series.

#### Live demo with steps to reproduce
http://jsfiddle.net/um1s8k7n/
- Move leftmost limit of navigator inwards;
- Move rightmost limit of navigator inwards;
- Disable series 1 by clicking on it's name in chart legend;
- Disable series 2 by clicking on it's name in chart legend;
- Move rightmost limit of navigator inwards;

**Result:** the axis disappear after navigator is moved. By looking at highstock code, it seems that the issue might be related with the redraw of the chart.

<a href="https://imgbb.com/"><img src="https://image.ibb.co/dLp5tR/noaxis.jpg" alt="noaxis" border="0"></a>

#### Affected browser(s)
62.0.3202.94 (Official Build) (64 bits)

**Comment by pawelfus** [comment]
Hi @mynameiswhat1 

Thank you, once again, for reporting an issue. It looks like connected navigator series is hidden with main series - that cause the issue (no visible series on the chart). Using a separate series for the navigator, we can workaround the issue: http://jsfiddle.net/um1s8k7n/1/

It used to work in 5.0.12: http://jsfiddle.net/um1s8k7n/2/ 

*Internal note:*
Regression after 15aad0d

**Comment by mynameiswhat1** [comment]
Hello @pawelfus,
Thank you for the quick response. Unfortunatelly, the workaround you have sugested will not work for us, since we need to be able to show all the chart's series in the navigator and be able to infer them from the series.
Will this be corrected in a future release?
Thank you very much.

**Comment by pawelfus** [comment]
Hi @mynameiswhat1 

Thank you for the details. I created simple drop-in fix for the current version:
```
  (function(H) {
    H.wrap(H.Series.prototype, 'setVisible', function(p, vis, redraw) {
      if (this.xAxis.options.className !== 'highcharts-navigator-xaxis') {
        p.call(this, vis, redraw);
      }
    });
  })(Highcharts);
```

It simply prevents series in navigator from being hidden: http://jsfiddle.net/um1s8k7n/4/

Of course, we need to fix this issue in the core.

**Comment by mynameiswhat1** [comment]
Hello @pawelfus ,
Please, let me know when the fix is available in the core.
Thank you very much.

**Comment by oysteinmoseng** [comment]
The hiding of the navigator series being linked with the base series is by design, and a new feature. The axis should not disappear when using the navigator with no visible series, though. Also, if you try to re-enable a series after the axis disappears, it fails.
