### ISSUE TITLE
csv export issue

### ISSUE THREAD

**Issue by Spider-Tech** [highcharts/highcharts#7417]
#### Expected behaviour
in csv export there has to be 3 rows with data

#### Actual behaviour
csv ignoring first data in the json array
in my csv export i am getting only 2 rows first rows is always ignored 

#### Live demo with steps to reproduce

http://jsfiddle.net/cqjvD/1583/

#### Affected browser(s)
ALL browsers

**Comment by pawelfus** [comment]
Hi @Spider-Tech 

You are using deprecated module: `export-csv`, this works correctly with current version of this module: `<script src="https://code.highcharts.com/modules/export-data.js"></script>`: http://jsfiddle.net/cqjvD/1585/
