### ISSUE TITLE
Numeric values in pointPlacement, xrange chart type

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#7419]
#### Expected behaviour
Property pointPlacement sets the element position relative to category.

#### Actual behaviour
Numeric values have no influence on the chart.

This property is described in API Reference as: series{type: "xrange"}.pointPlacement but not in plotOptions.xrange.

#### Live demo with steps to reproduce
http://jsfiddle.net/ppotaczek/upxfm3hj/

#### Affected browser(s)
All browsers

**Comment by TorsteinHonsi** [comment]
Since the X range series is designed for linear and datetime axes, and `pointPlacement` is designed for categorized axes, it doesn't make sense to combine them on the X axis. 

Or did you expect this to work with the categories on the Y axis?

**Comment by ppotaczek** [comment]
Yes, I expect this to work with the Y axis. Textual options seems to work.

Live demo: http://jsfiddle.net/ppotaczek/g2y0tx7a/

**Comment by LaniMoo** [comment]
Original finding here: https://forum.highcharts.com/topic39895/

**Comment by KacperMadej** [comment]
**Workaround**: use min, max, startOnTick and endOnTick - demo: http://jsfiddle.net/BlackLabel/g2y0tx7a/1/

**Comment by LaniMoo** [comment]
Hm, am I missing something? Your demo shows an example using a string value for point placement, but the original issue is that it doesn't work with numeric values.

**Comment by KacperMadej** [comment]
@LaniMoo 
Right, my workaround was for the last demo from @ppotaczek because it didn't look good.

All string options for `pointPlacement` are doing has to do with axis extremes and position of points in relation to axis is not changed.

**Comment by LaniMoo** [comment]
Any plans for this in the near future?

**Comment by KacperMadej** [comment]
@oysteinmoseng Is there any common ground between this issue and Gantt? Maybe a similar issue was resolved in Gantt?
