### ISSUE TITLE
[Highcharts Accessibility] Unify keyboard arrow key navigation -- navigate through chart data sequentially

### ISSUE THREAD

**Issue by SummerLi** [highcharts/highcharts#7421]
#### Actual behaviour
For keyboard navigation module, Highcharts version 5 supports tabbing through all chart series, but from version 6 it changes to use tabbing to navigate between main chart components, and use arrow keys to navigate between chart series. For some chart types, left/right arrow key is used to navigate inside one series, and up/down arrow key is used to navigate between series. For some chart types, e.g: scattered chart, up/down/left/right arrow key is used to navigate to the next closest data point.

#### Expected behaviour
Per discussion with @oysteinmoseng offline, using arrow keys to navigate between chart series is fine. But people who are blind will not have a clear clue on the chart layouts, so up/down/left/right direction is not very clear to them. We would like to unify the keyboard arrow key navigation, for example, despite of the chart type and directions, always using up/down arrow key to navigate through chart data sequentially. This is also in consistent with some screen reader's keyboard navigation module, such as JAWs.

#### Affected browser(s)
All browsers

**Comment by SummerLi** [comment]
FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
Internal note: As discussed in the meeting, we should consider introducing a chart option to serialize the keyboard navigation into a one-dimensional list. If we found a good way to make this controllable by the chart reader, this could also be an option.

**Comment by oysteinmoseng** [comment]
Added now a `keyboardNavigation.mode` option that can be set to `"serialize"`. That should take care of this issue. In cases where the reader needs to have control over the keyboard navigation behavior, some kind of toggle can be added that uses `chart.update()` to change this option.

Example: http://jsfiddle.net/oysteinmoseng/7u6muyb5/show/
