### ISSUE TITLE
[Highcharts Accessibility] For area chart, keyboard navigation (tab & arrow key) doesn't set focus on chart series at all.

### ISSUE THREAD

**Issue by SummerLi** [highcharts/highcharts#7423]
#### Expected behaviour
For area chart, keyboard navigation (tab & arrow key) should work.

#### Actual behaviour
For area chart, keyboard navigation (tab & arrow key) doesn't set focus on chart series at all.

#### Affected browser(s)
Edge, Chrome

**Comment by SummerLi** [comment]
FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
Seems to work in latest code, see: http://jsfiddle.net/oysteinmoseng/bp81738j/1/show/.

@SummerLi Can you verify that this works for you? The latest code can be found at http://github.highcharts.com/bugfix/modules/accessibility.js

**Comment by SummerLi** [comment]
[Accessibility_v6.0.2.zip](https://github.com/highcharts/highcharts/files/1488777/Accessibility_v6.0.2.zip)
@oysteinmoseng I can still repro this with the latest accessibility.js.

I've attached above demo zip file, the area chart script is: Highcharts_Demo/Highcharts_Demo/Accessibility_v6.0.2/area-basic/index.htm

**Comment by oysteinmoseng** [comment]
This was not an issue with area series specifically, but an issue with the default behavior for `skipNullPoints` (now enabled by default) and `pointDescriptionThreshold` (now disabled by default, and more predictable behavior for keyboard navigation when enabled).
