### ISSUE TITLE
The fillColor of marker cannot be inherited from corresponding data point

### ISSUE THREAD

**Issue by lzl124631x** [highcharts/highcharts#7425]
#### Expected behaviour
The marker can inherit the fillColor from the point.
![image](https://user-images.githubusercontent.com/5824517/32976989-b833c7f0-cbd8-11e7-8cbb-ecb52702dd45.png)
![image](https://user-images.githubusercontent.com/5824517/32976992-c7e61694-cbd8-11e7-8bf5-9731d3c8771d.png)

#### Actual behaviour
The marker doesn't inherit the fillColor from the point, but inherit from chart default.
![image](https://user-images.githubusercontent.com/5824517/32976981-8712dd32-cbd8-11e7-9448-7abb832fc77d.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/Richard_Liu/m9cdmu3e/

#### Affected browser(s)

Google Chrome | 62.0.3202.75 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 67b212ffb03c4401235f8961e2d15371b96cde27-refs/branch-heads/3202@{#750}
OS | Windows
JavaScript | V8 6.2.414.36

**Comment by lzl124631x** [comment]
I could achieve the expected result if I use the following one for the data point. But I think it `fillColor` should be automatically inherited .
```
        marker: {
          fillColor: 'red',
          states: {
            hover: {
              fillColor: 'red'
            }
          }
        }
```

**Comment by pawelfus** [comment]
Hi @lzl124631x 

Thank your for reporting this issue. You are using old version of Highcharts, with current one (v6) it works like you expect: http://jsfiddle.net/m9cdmu3e/6/

**Comment by lzl124631x** [comment]
Thanks @pawelfus
