### ISSUE TITLE
cannot change halo for individual point

### ISSUE THREAD

**Issue by lzl124631x** [highcharts/highcharts#7426]
#### Expected behaviour
I want the halo for the special red point be red. But it's blue as the halo for other points. I tried many ways but it still didn't work.

![image](https://user-images.githubusercontent.com/5824517/32977164-86e2c5b2-cbdc-11e7-9370-25f7bf6ed5dd.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/5824517/32977168-9b57bbba-cbdc-11e7-9246-7a1bda77d54c.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/Richard_Liu/9vdzbzuh/

#### Affected browser(s)
Google Chrome | 62.0.3202.75 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 67b212ffb03c4401235f8961e2d15371b96cde27-refs/branch-heads/3202@{#750}
OS | Windows
JavaScript | V8 6.2.414.36

**Comment by TorsteinHonsi** [comment]
You actually didn't set the `point.color` to red, you just set the marker fill color. Once you set the point.color, the point, halo, tooltip border and tooltip symbol will all get the correct color: http://jsfiddle.net/9vdzbzuh/8/
