### ISSUE TITLE
Chart legend overlaps with title and subtitle

### ISSUE THREAD

**Issue by GertVen** [highcharts/highcharts#7428]
#### Expected behaviour
Chart legend will show underneath title and subtitle, just above chart area itself

#### Actual behaviour
Chart legend overlaps with title and subtitle

#### Live demo with steps to reproduce
http://jsfiddle.net/b06p6rk5/

#### Affected browser(s)
Google Chrome
Mozilla Firefox
Microsoft Internet Explorer

Code generated via official Highcharts wrapper

#### Side question:
I have posted two errors regarding the Highcharts wrapper on the Highcharts forums:
-> https://forum.highcharts.com/highcharts-usage/net-wrapper-implementing-levels-in-sunburst-t39862/
-> https://forum.highcharts.com/highcharts-usage/net-wrapper-implementing-formatter-in-sunburst-t39861/

I would just like to know what their status are and if there is a possible ETA for the next update.

Thanks!

**Comment by pawelfus** [comment]
Hi @GertVen 

Thank you for reporting this issue. It is a general issue with legend and top-aligned items, see #6333.

Regarding side issues, we don't have ETA for the next release of the wrapper. Daniel will let you know in the forum topics when it will be fixed.
