### ISSUE TITLE
Indonesia has new province, Kalimantan Utara

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#7431]
New province in Kalimantan.
See https://en.wikipedia.org/wiki/North_Kalimantan
Our version: http://jsfiddle.net/gh/get/library/pure/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/id/id-all

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#12
