### ISSUE TITLE
Variwide stacked misbehaves with missing data

### ISSUE THREAD

**Issue by d2a-raudenaerde** [highcharts/highcharts#7434]
#### Expected behaviour
All stacked bars in column have same width so it looks good.

#### Actual behaviour
Different width for some bars. Ugly.

#### Live demo with steps to reproduce
http://jsfiddle.net/06jpczo9/5/

#### Affected browser(s)
All. Tested Firefox 57, Chrome 62.0.3202.94

**Comment by pawelfus** [comment]
Hi @d2a-raudenaerde 

Thank you for reporting this issue.

**Workaround:**
Instead of removing points, we can nullify them, for example: http://jsfiddle.net/06jpczo9/6/

**Comment by d2a-raudenaerde** [comment]
Hi @pawelfus 

Yes, I am aware of this. However, as my input is more complex this means I have to scan all data to extract all possible values of data[0] and add the missing values.
This is what I currently do, but it would be nice if HighCharts supports this in the variwide chart by default, so I don't have to worry about it.

Thank you for looking into this issue.
