### ISSUE TITLE
Extremes not computed correctly while having two x axes

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7436]
#### Expected behaviour
Plot area should look like on this fiddle (only one x axis): https://jsfiddle.net/kkulig/wcaov78w/

#### Actual behaviour
Extremes have some strange values when there're two x axes.

#### Live demo with steps to reproduce
https://jsfiddle.net/kkulig/rvnuhy87/

**Comment by pawelfus** [comment]
*Internal note:*
It's connected to `alignTicks`, when disabled looks the same way: https://jsfiddle.net/rvnuhy87/7/

**Comment by TorsteinHonsi** [comment]
When `alignTicks` is true, both axes first compute the best-fit for `tickAmount`, then renders. We could consider skipping this for flat data.
