### ISSUE TITLE
Chart.setSize() function doesn't work properly combined with 3d-highcharts.js plugin module.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#7437]
#### Expected behaviour

When passing _false_ parameter as last argument to setSize() function, then everything is working properly.

#### Actual behaviour

Points aren't resizing, and there are glitches created while hovering series and animation is in progress.

#### Live demo with steps to reproduce

[https://jsfiddle.net/daniel_s/bbuy876q/](https://jsfiddle.net/daniel_s/bbuy876q/)

This issue is probably related to [#3534](https://github.com/highcharts/highcharts/issues/3534)

**Comment by pawelfus** [comment]
*Internal note:*
Regression since v6, in v5 it used to work fine: https://jsfiddle.net/bbuy876q/4/

**Comment by TorsteinHonsi** [comment]
Fails since c4fef2479
