### ISSUE TITLE
is there easy way to get the y value of flag?

### ISSUE THREAD

**Issue by lzl124631x** [highcharts/highcharts#7440]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/5824517/33101542-83c8aad8-cecd-11e7-8409-269128e77707.png)

The flags' `onSeries` is designed to let you only specify the `x` value of flags. But it's had to retrieve the actual `y` value of flags.

#### Actual behaviour
![image](https://user-images.githubusercontent.com/5824517/33101556-8f0908f2-cecd-11e7-95e2-ee1f671e161d.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/Richard_Liu/Lz6bvh8w/

#### Affected browser(s)

Google Chrome | 62.0.3202.94 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 4fd852a98d66564c88736c017b0a0b0478e885ad-refs/branch-heads/3202@{#789}
OS | Windows
JavaScript | V8 6.2.414.42

**Comment by pawelfus** [comment]
Hi @lzl124631x 

Thank you for letting us know about your issue. You can translate `point.plotY` to a value using `yAxis.toValue()`. Demo for you: https://jsfiddle.net/g4hnpLf5/

If you have more questions, please contact with our [support](https://www.highcharts.com/support) - we are using github tickets as bug reports.

**Comment by lzl124631x** [comment]
@pawelfus  Thanks!

I think it's less obvious using `this.series.yAxis.toValue(this.point.plotY, true)` than just `this.point.y`. How about setting the `this.point.y` automatically if `onSeries` is set and `y` is not explicitly set?
