### ISSUE TITLE
Add "Xaisomboun Province" to Laos map in Highmaps

### ISSUE THREAD

**Issue by PhouvanhKCSV** [highcharts/highcharts#7442]
Hi,

I would like to add "Xaisomboun Province" refer to this [https://en.wikipedia.org/wiki/Provinces_of_Laos](https://en.wikipedia.org/wiki/Provinces_of_Laos), because "Xaisomboun Province" next to "Vientiane Province" is missing from the original map in Highcharts demo. Here: [https://www.highcharts.com/maps/demo/all-maps#countries/la/la-all](https://www.highcharts.com/maps/demo/all-maps#countries/la/la-all)

How can i update this in the original official JS file. Here: [https://code.highcharts.com/mapdata/countries/la/la-all.js](https://code.highcharts.com/mapdata/countries/la/la-all.js)

I try to use this tool [https://www.highcharts.com/studies/map-from-svg.htm](https://www.highcharts.com/studies/map-from-svg.htm) but it does not output data format like in the original javascript file above.

Source: [https://commons.wikimedia.org/wiki/File:Laos,_administrative_divisions_-_th_-_colored.svg](https://commons.wikimedia.org/wiki/File:Laos,_administrative_divisions_-_th_-_colored.svg)

Best Regards,
Phouvanh

**Comment by KacperMadej** [comment]
Hi,

This is more a support case than a bug - we are trying to keep github only for bugs, so I will be closing the issue.

If SVG is not working well with the map-from-svg tool, then you can create a custom map using instructions from general documentation:
- https://www.highcharts.com/docs/maps/custom-maps
- https://www.highcharts.com/docs/maps/custom-geojson-maps

In case of further questions or any other support problems please contact us through support channels listed here: https://www.highcharts.com/support

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng FYI

**Comment by oysteinmoseng** [comment]
We should probably consider this a bug and update our collection to reflect the new provinces for the next release. Reopening and tagging accordingly.

**Comment by kamilkulig** [comment]
**Fixed demo:** http://jsfiddle.net/BlackLabel/etxv0oqk/

Internal note: Map shape from different source applied. New map contains the missing region.

**Comment by kamilkulig** [comment]
**Fixed demo:** http://jsfiddle.net/BlackLabel/etxv0oqk/
**Internal note:** Map shape from different source applied. New map contains the missing region.

**License** disclaimer for shape utilized to generate the map: 
_These data were extracted from the GADM database (www.gadm.org), version 2.5, July 2015. They can be used for non-commercial purposes only.  It is not allowed to redistribute these data, or use them for commercial purposes, without prior consent._

**Comment by PhouvanhKCSV** [comment]
Thank you so much @kamilkulig for your help and helpful sample.

I wonder will it be update to [HIGHMAPS - MAP COLLECTION](https://code.highcharts.com/mapdata/)?

**Comment by sebastianbochan** [comment]
Hi @PhouvanhKCSV,
It should be avaiable in Q3 2018, but we still developing other maps.

**Comment by KacperMadej** [comment]
Let's keep this issue open until new version of the map collection is published.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#13
