### ISSUE TITLE
Highmaps: on iOS (iPhone, iPad) not able to drilldown.

### ISSUE THREAD

**Issue by aissaghouti** [highcharts/highcharts#7443]
#### Expected behaviour
On iOS web browser (Safari/Chrome) we should be able to drilldown a state on click. 
It's working well on Android web browsers.

#### Actual behaviour
But it does not respond to the drilldown event.

#### Live demo with steps to reproduce
Open the following demo on an iOS web browser: https://www.highcharts.com/maps/demo/map-drilldown

#### Affected browser(s)
iOS Safari, Chrome, ...

**Comment by pawelfus** [comment]
Hi @aissaghouti 

Thank you for reporting this issue. 

Tested with:
- iOS 11.1.2 + Safari -> doesn't work
- Android 6 + Chrome -> works fine

I think it's connected to #6715 - we should provide an option to show a tooltip, or to do a drilldown..

**Comment by TorsteinHonsi** [comment]
I don't see a drilldown even when disabling the tooltip... It seems like the `onContainerClick` function is not fired on the map, probably the event is stopped before it reaches that.

**Comment by hc1skalyanasundaram** [comment]
Did anyone find any workaround for this?

**Comment by pawelfus** [comment]
Hi @hc1skalyanasundaram 

Could you tell me your iOS version? Just tested with:

- iOS 11.2.5
- iOS 9.3.5

And OP demo (https://www.highcharts.com/maps/demo/map-drilldown) works fine.

**Comment by hc1skalyanasundaram** [comment]
I'm on 10.3.3. The demo works fine for me too, just my map drilldown is not working. Although I have similar options

**Comment by pawelfus** [comment]
@hc1skalyanasundaram - could you create jsFiddle demo with the issue? We will check this. Make sure you have the latest version of Highmaps (v6.0.7).

**Comment by aissaghouti** [comment]
**FIXED!**

We added `allowPointSelect:true` in `series` and `followTouchMove: true` in `series.tooltip`.
Thank you all.
