### ISSUE TITLE
Slow chart render speed...

### ISSUE THREAD

**Issue by ShevtsivAndriy** [highcharts/highcharts#7445]
Hello guys.
Can anybody explain me why this chart rendering so long time?
http://jsfiddle.net/ngnueab9/3/

And when I play before with random data they build very quickly.
http://jsfiddle.net/ngnueab9/

P.S. I use Angular4 for front-end on my project, and I use https://www.npmjs.com/package/angular2-highcharts to build charts.

**Comment by pawelfus** [comment]
Hi @ShevtsivAndriy 

Thank you for reporting your issue. Compare:

- working demo: `chart.addSeries({data: currentValue}, false);`
vs
- slow-demo: `chart.addSeries(element);`

In the slow-demo, you redraw chart after each series addition, when `redraw` is set to false it works fine: http://jsfiddle.net/ngnueab9/4/

In case of other issues, please contact with our [support](https://www.highcharts.com/support).
