### ISSUE TITLE
Unable to open highcarts demos on jsfiddle

### ISSUE THREAD

**Issue by likwifi** [highcharts/highcharts#7446]
#### Actual behaviour
Highcharts demos are not loading or taking too much time to load on Chrome
e.g.
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-visible/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @likwifi 

Just tested, works fine. Maybe jsFiddle had some problems? Tested with Chrome v62.0.3202.94
