### ISSUE TITLE
Some labels stay hidden after drill up in Pie Charts

### ISSUE THREAD

**Issue by ahmedkhan847** [highcharts/highcharts#7449]
I am having issue in chrome that when I drill back the label part of pie which I have clicked remain hidden and all other are visible. This is working fine in firefox, edge but not in chrome.  The same thing is happening with the live example of highcharts.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/pie-drilldown

#### Affected browser(s)
**Chrome**

**Comment by pawelfus** [comment]
Hi @ahmedkhan847 

Thank you for reporting this issue. We have already fixed this in our master branch and fix will be included in the next release. Demo with fix applied: http://jsfiddle.net/Lucwgv9a/
