### ISSUE TITLE
Any plan to created official Vue.js Highcharts wrapper

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#7450]
Hi, It's excited to hear  that you are created Highcharts official React, Angular wrapper, and do you have any plan to create Vue.js Wrapper ?

more information about Vue.js
* Official Website: [https://www.vuejs.com](https://www.vuejs.com)
* vue Highcharts wrapper : [https://github.com/weizhenye/vue-highcharts](https://github.com/weizhenye/vue-highcharts)

**Comment by pawelfus** [comment]
Hi @zhy1stgg 

Thanks for your suggestion! I think we should create Vue.js official wrapper, but we don't have any ETA for this. I suggest to create an idea on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api) - if the idea will gain votes, then certainly we will set a higher priority for this wrapper.

**Comment by KacperMadej** [comment]
Here's the official wrapper: https://github.com/highcharts/highcharts-vue
