### ISSUE TITLE
Highcharts issue related to panning and xAxis categories.

### ISSUE THREAD

**Issue by sebastienrocks** [highcharts/highcharts#7451]
(I don't know if this is specifically an issue or if I am missing some options that are needed.)

#### Expected behaviour
When you add categories to the xAxis, and activate panning, you can pan between the first and last categories.

#### Actual behaviour
For some reason when categories are activated, you can pan infinitely to the left or right of the chart.

#### Live demo with steps to reproduce
Panning with categories (the issue):  http://jsfiddle.net/2chLcxrs/1/
Panning without categories: http://jsfiddle.net/2chLcxrs/

#### Affected browser(s)
Tested only on Chrome.

**Comment by pawelfus** [comment]
Hi @sebastienrocks 

Thank you for reporting this issue. It's a regression since v5.0.8, in v5.0.7 it used to work fine: http://jsfiddle.net/2chLcxrs/2/

*Internal note:*
Regression after c56cdae

**Comment by sebastienrocks** [comment]
Hi @pawelfus,

Thanks for the info, I'll downgrade to 5.0.7 until this is fixed.

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/2chLcxrs/3/
