### ISSUE TITLE
crisp not working in HighStock<candlestick>

### ISSUE THREAD

**Issue by firetheworld** [highcharts/highcharts#7455]
#### Expected behaviourZ
Hi, I'm using highstock candlestick, and I have set crisp to false, but it seems not function,and some candlestick cover the near one，this screen shoot below,
And, you can see column chart belew the candlestick, I have set the crisp on column chart ,and it work!
so I don't know if there some sepecial param I have miss
![image](https://user-images.githubusercontent.com/7941843/33194070-27544b44-d108-11e7-88d6-2a23139b1991.png)
Here is my code:
series: [
        {
          type: 'candlestick',
          name: this.props.shortName,
          data: ohlc,
          id: 'candlestickID',
          pointPadding: 0,
          groupPadding: 0.1,
          crisp: false,
        },
      ],

#### Affected browser(s)
chrome

**Comment by pawelfus** [comment]
Hi @firetheworld 

Thank you for reporting this issue. It looks like a bug in the docs, ohlc/candlestick doesn't have `crisp` option. @TorsteinHonsi could you confirm?

**Comment by TorsteinHonsi** [comment]
Yes that's correct. It probably wouldn't be too hard to implement it though, as these series types inherit and extend the `translate` function from column series.
