### ISSUE TITLE
x-axis zoom ignores tickPositions option

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#7456]
#### Expected behaviour
Ticks on the x-axis are constrained by the ticksPositions option, also when zooming.

#### Actual behaviour
Zoom on the x-axis shows at least 1 tick that is not in the ticksPositions option.

#### Live demo with steps to reproduce
http://jsfiddle.net/kzoon/f6y2snqa/2/

Zoom somewhere between Jan 2011 and Jan 2012
July 2011 shows up as a tickmark, even though its index (7) is not  in the ticksPositions option.

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the issue. The behavior is by design: https://github.com/highcharts/highcharts/issues/3195

To avoid this, please use tickPositioner - demo: http://jsfiddle.net/BlackLabel/f6y2snqa/3/

**Comment by kzoon** [comment]
I will try to implement the tickPositioner. However, I can't quite see how this is intended behaviour on a category axis. Especially because the added tickmark is not always on a category, like in this example:
http://jsfiddle.net/kzoon/f6y2snqa/5/

**Comment by kzoon** [comment]
I created a new ticket #7463 for the trimTicks calculation errors

**Comment by KacperMadej** [comment]
@kzoon New ticket to make the problem more clear is always a good idea. Thank you for opening the new ticket.

**Comment by TorsteinHonsi** [comment]
FYI, this issue has been fixed. 

> The behavior is by design: #3195

We added one tick by design, but it doesn't make sense when using the `tickPositions` option. So the fix does what @kzoon expected.
