### ISSUE TITLE
Highstock: 1 month button in rangeSelector breaks button 'select' state

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7458]
#### Behaviour
The 1m button should have the same style after the click (`highcharts-button-pressed` - bold font, darker background) as the rest of the range selector's buttons.

#### Live demo
[Edit: The original fiddle doesn't show the problem since crossing over to December, so here's a reliable demo with static data and width:]
http://jsfiddle.net/highcharts/eLm9wmyd/1/

Steps:
1. click on 1m button
2. check button style -> not as the other buttons after selecting

**Comment by KacperMadej** [comment]
Buttons are indexed from 0, so `selected: 1` means that second button will be (and is) selected.

Or maybe this requires selected combination of browser + OS? If yes, then let me know what it is and I can reopen.

**Comment by ppotaczek** [comment]
The workaround is to manually set rangeSelector.buttons and change count and type property for 1 month.

Live demo: http://jsfiddle.net/ppotaczek/4vgvm966/
