### ISSUE TITLE
The line in a line chart does not animate on Microsoft Edge

### ISSUE THREAD

**Issue by FibHeap** [highcharts/highcharts#7460]
#### Expected behaviour
The line, not only the points should animate for
https://www.highcharts.com/demo/line-basic

#### Actual behaviour
Only the points are animated, but all the lines are only drawn at the very end.

#### Live demo with steps to reproduce
Just go to https://www.highcharts.com/demo/line-basic with the affected browser.

#### Affected browser(s)
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

Windows Version	10.0.16299 Build 16299

**Comment by KacperMadej** [comment]
Thank you for reporting.

I'm unable to recreate the problem using:
Microsoft Edge 40.15063.674.0
Microsoft EdgeHTML 15.15063
Windows 10 Pro / Version 1703 / OS Build 15063.726

I will check this again when any of my versions change.

**Comment by kamilkulig** [comment]
Works fine on:

Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299
Windows 10 Pro

**Comment by FibHeap** [comment]
It seems to be related to the Adblock plugin of Edge(https://www.microsoft.com/fr-ch/store/p/adblock/9nblggh4rfhk?rtc=1). Deactivating the plugin makes it work.

Sorry that I did not check with plugins disabled.  I guess ad blocking plugins can create a lot of bugs on pages so I guess it is not so important to fix and maybe even a problem within the plugin.
