### ISSUE TITLE
tooltip.formatter does not receive offset point.x when timezoneOffset is used

### ISSUE THREAD

**Issue by samturner** [highcharts/highcharts#7461]
#### Expected behaviour

If a `timezoneOffset` is set in `global`,  the value `this.x` in a `tooltip.formatter` should have the timezone offset applied. Or, there should be a way to access this offset so that dates can be formatted correctly in the tooltip.

#### Actual behaviour

`this.x` in a tooltip formatter has the original value of the point and no concise and reliable way to access the `timezoneOffset`.

Currently, a workaround is to do something like this in the `tooltip.formatter` function:

```
 let timezoneOffset = this.points[0].point.series.chart.options.global.timezoneOffset

```

And then use something like `moment` to adjust and format the timezone correctly:

```
moment.utc(this.x).utcOffset(-timezoneOffset).format('MMM DD, YYYY h:mm a')
```

#### Live demo with steps to reproduce

TODO: If needed

**Comment by KacperMadej** [comment]
Hi @samturner 

Thank you for reporting and suggesting the workaround.

Please add a live demo, so it will be easier for us to debug the problem and test possible solutions.

**Comment by TorsteinHonsi** [comment]
> If a timezoneOffset is set in global, the value `this.x` in a tooltip.formatter should have the timezone offset applied.

The `x` value applies to an absolute point in time, so we can't change that. What we change by default is only the formatting, so the date is printed according to the given timezone. Please provide a demo if this doesn't work as announced.

> Or, there should be a way to access this offset so that dates can be formatted correctly in the tooltip.

That we can do. We can use the global `Highcharts.getTZOffset` function for any timestamp, including `this.x`: http://jsfiddle.net/highcharts/tpox4y11/
