### ISSUE TITLE
Draw line charts by days/weeks/months from a timestamp

### ISSUE THREAD

**Issue by chengtie** [highcharts/highcharts#7462]
I want to analyze visit logs of my website. The website stores an array of `moment.js` time, each time there is a new visit on the website, it pushes a `moment.js` time to the array.

From that input, I want to draw line charts to show the `number of visits` `day by day`, `week by week` and `month by month`. In [this example](https://jsbin.com/qelosaceqa/3/edit?html,output) of showing number of visits day by day, I have to prepare the data (of x-axis and y-axis) by myself:

    var enumerateDaysBetweenDates = function(startDate, endDate) {
        var dates = {};
        var currDate = startDate.clone().startOf('day').add(-1,'days');
        var lastDate = endDate.clone().startOf('day');
        while(currDate.add(1, 'days').diff(lastDate) <= 0) {
            var x = currDate.clone(); 
            dates[x.format('YYYY-MM-DD')] = { "numberOfVisits": 0 };
        }
        return dates;
    };

    var startDate = moment({ year : 2017, month : 10, day : 1 });
    var endDate = moment({ year : 2017, month : 10, day : 30 });
    var res = enumerateDaysBetweenDates(startDate, endDate)
    for (var i = 0; i < logs.length; i++) {
        var date = moment.utc(logs[i]).format("YYYY-MM-DD");
        res[date].numberOfVisits++
    }

    // change format:
    var r = [];
    for (var d in res) {
        if (res.hasOwnProperty(d)) {
            var a = d.split("-");
            var b = Date.UTC(a[0], a[1] - 1, a[2]);
            r.push([b, res[d].numberOfVisits])
        }
    }

To draw a chart for weeks or months, I have to re-prepare the data. Does anyone know if there is a way, a parameter or a library that permits of automatically drawing the charts?

**Comment by KacperMadej** [comment]
Hi,

Please use any other support channel for tech support - we keep github for bugs.
https://www.highcharts.com/support

The problem seems to be about data, but that just the first look, so if I'm wrong please provide more info when contacting support.
