### ISSUE TITLE
Highstocks rangeSelector, `selected` not working on button with `offsetMin` (v6.0.3)

### ISSUE THREAD

**Issue by HarveyWilliams** [highcharts/highcharts#7467]
#### Expected behaviour
Using the `selected` config option in the `rangeSelector` should select a button by default.

#### Actual behaviour
No button iselected/s highlighted. Instead, It's like the default option for `1y` is being selected where as I need it to use my `offsetMin`.

#### Live demo with steps to reproduce
https://jsfiddle.net/h3g09d50/

I have created a custom button with this config:

```
{
    type: 'year',
    count: 1,
    text: '1y',
    // Commenting out this line causes 1y to get selected.
    offsetMin: -1 * 24 * 3600 * 1000
}
```
The `offsetMin` is there so 1 year and 1 day will be shown, so rather than:

```
2016-11-28 - 2017-11-28
```

This date range will be used:

```
2016-11-27 - 2017-11-28
```

However, the `selected` field doesn't work with this button.

Commenting out line 28 in the demo (the `offsetMin` field) causes the `selected` option to work again.

Thanks for the hard work!

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

**Comment by KacperMadej** [comment]
*Interna note:* time set by selected button in chart config doesn't include offsetMin

**Comment by gemadang** [comment]
Sorry why was this closed, was there a solution to this bug that was issued 2 years ago?

**Comment by pawelfus** [comment]
Hi @gemadang 

Yes, this is fixed. Above your message, a commit is referenced that closed this issue:

![Screen Shot 2019-06-17 at 09 52 53](https://user-images.githubusercontent.com/1453926/59587475-a021f000-90e5-11e9-969c-11159bf6e3a4.png)

Commit: 279530cf9d3c67a1d1f99e566cdd790dc5c151e1

**Comment by simonishak** [comment]
Hi @pawelfus 

I'm having an issue when you add one day instead of going back one day using offsetMin.

Here is a jsfiddle with the issue: https://jsfiddle.net/Lsro1t83/1/

As you can see we have this code for the 1 Year:

`offsetMin: 24 * 3600 * 1000`

And the 1y is not selected.

I know that the range is not exactly 1 year, but for my case I need the previous point to be included in the calculation.

**Comment by ectuser** [comment]
Hi @simonishak , 

Have you managed to fix this issue?
