### ISSUE TITLE
Tooltip hovered point stops syncing after too many back and forth hovering over the chart (shared tooltip)

### ISSUE THREAD

**Issue by manojmari** [highcharts/highcharts#7469]
#### Expected behaviour
Points with hover effect should always be in sync

#### Actual behaviour
Points with hover effect are not in sync

#### Live demo with steps to reproduce

Go to http://jsfiddle.net/mmanojma/p3p6b374/1/
move the mouse back and forth rapidly
Notice that tooltip has been set to shared
Once you are able to replicate it, try zooming in. The tooltip position too goes out of sync.
Although the data shown in the tooltip is always in sync.
Output: https://snag.gy/PhUogB.jpg

#### Affected browser(s)
Viewed on chrome (possible all the browsers)

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.

Might be that point state is not changed fast enough and animation done there creates lag and changes some state options of points preventing them from being hovered again correctly.
