### ISSUE TITLE
Part of the chart missing while moving the mouse around

### ISSUE THREAD

**Issue by Njuhobby** [highcharts/highcharts#7470]
#### Expected behavior
Nothing specifically should happen.

#### Actual behaviour
Part of the chart will be missing and then come back again.

#### Live demo with steps to reproduce
https://stackoverflow.com/questions/47465844/highcharts-part-missing-while-moving-mouse

#### Affected browser(s)

Edge 41.16299.15.0 and potentially other browsers 
I tested it in Firefox, too. Instead of part of the chart missing, the whole page becomes super laggy.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.

*Internal note:* Edge v.40 is not affected. Might be an issue with a single browser version. I suggest testing with Edge v.42 to confirm.

**Comment by PaulDalek** [comment]
+1

**Comment by KacperMadej** [comment]
Edge v44 seems to be working fine.
Closing.
