### ISSUE TITLE
Italy misspelled area, Crotone

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#7472]
Crotone is spelled "Crotene" in our [Italy map](http://jsfiddle.net/gh/get/library/pure/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/it/it-all).

Internal note: Fix manually in source data.

**Comment by kamilkulig** [comment]
Fixed demo: http://jsfiddle.net/BlackLabel/7odtr4y7/
Internal note: All properties for Crotone region changed from misspelled to correct.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#14
