### ISSUE TITLE
Pie Chart Drilldown loses top level label after navigating up stack

### ISSUE THREAD

**Issue by fergusg** [highcharts/highcharts#7476]
#### Expected behaviour

With a pie chart drilldown (as per "official" demo example, below), drilling down on any segment then backing up, the label for the selected segment disappears.

#### Actual behaviour

Label should be visible

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/pie-drilldown/

#### Affected browser(s)

Chrome 62.0.3202.94

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

**Comment by pawelfus** [comment]
It's already fixed on our master branch: http://jsfiddle.net/7f1hkwk5/ - fix will be part of the next release.
