### ISSUE TITLE
3d Line Chart rotates as series visibility are toggled

### ISSUE THREAD

**Issue by jpeterson** [highcharts/highcharts#7477]
#### Expected behaviour
When I toggle the visibility of a series in a 3d line chart (by clicking the legend item), the series should appear/disappear on the chart, but the chart's rotation angles should not change.

#### Actual behaviour
When I toggle the visibility of a series in a 3d line chart, the rotation angles of the chart change progressively with each toggle action, causing the chart to become misaligned. (2 screenshots included below)

#### Live demo with steps to reproduce
http://jsfiddle.net/9wd3yb2r/

#### Affected browser(s)
Confirmed in Chrome, Firefox, and Safari on MacOS

#### Initial View:
>![image](https://user-images.githubusercontent.com/3399064/33496633-2ebef4a8-d688-11e7-87c4-53dcefa857d8.png)

#### View after toggling "John" series a number of times:
>![image](https://user-images.githubusercontent.com/3399064/33496622-25a10c08-d688-11e7-8bce-7e990fd25db5.png)

**Comment by KacperMadej** [comment]
Hi @jpeterson ,

Line is not a supported series type for a 3d chart. You can use scatter3d with lineWdith set to a positive value. Demo: http://jsfiddle.net/9wd3yb2r/2/

**Comment by jpeterson** [comment]
Thank you @KacperMadej!

**Comment by TorsteinHonsi** [comment]
Line charts have basically been working with 3D charts since v6, so I fixed this issue. Here's the original demo with the fix applied: http://jsfiddle.net/highcharts/9wd3yb2r/3/ .
