### ISSUE TITLE
Plot area border does not resize when using a bar chart with a drilldown

### ISSUE THREAD

**Issue by matthewyarlett** [highcharts/highcharts#7478]
#### Expected behaviour
Border should resize with the plot area

#### Actual behaviour
Border doesn't resize

#### Live demo with steps to reproduce
http://jsfiddle.net/matthewyarlett/edtxkx2a/

#### Affected browser(s)
Confirmed not working in Chrome, Edge, Firefox

![image](https://user-images.githubusercontent.com/10984316/33519736-478600ba-d801-11e7-8ac1-a1c8ac797a0b.png)

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

**Comment by TorsteinHonsi** [comment]
Same problem with column: http://jsfiddle.net/highcharts/edtxkx2a/1/

**Comment by TorsteinHonsi** [comment]
Here's a drop-in fix you can use while waiting for the next maintenance release: http://jsfiddle.net/highcharts/edtxkx2a/3/
