### ISSUE TITLE
Loading hideDuration not working in Highcharts 5.0.14

### ISSUE THREAD

**Issue by whawker** [highcharts/highcharts#7479]
Note this for Highcharts 5.0.14. Seems to be fixed on Highcharts 6+.

I think this is due to an error in the `H.getStyle` function [here](https://github.com/highcharts/highcharts/blob/v5.0.14/js/parts/Utilities.js#L1931). It seems to return 0 when it should return 0.5?

#### Expected behaviour
The loading message fades away for [`hideDuration`](https://api.highcharts.com/highcharts/loading.hideDuration) milliseconds

#### Actual behaviour
The loading message disappears instantly.

#### Live demo with steps to reproduce
http://jsfiddle.net/x7zpms90/

#### Affected browser(s)
Chrome, Firefox, IE, (Probably all)

**Comment by KacperMadej** [comment]
The problem was resolved in version 6.0.0.
The responsible commit is given below if you would like to apply the fix manually to an older version of Highcharts:
https://github.com/highcharts/highcharts/commit/1ff5419d76e8d1a7c3ee7a2522d47b001b8327ef
