### ISSUE TITLE
"yData is undefined" in stacked chart with predefined x- and y-limits using boost

### ISSUE THREAD

**Issue by rstrietzel** [highcharts/highcharts#7481]
#### Expected behaviour
chart displays in the same way as without boost

#### Actual behaviour
No chart is displayed. Disabling stacking or removing one of the axis limits or disabling boost shows the chart.

Issue was discovered using Highcharts 5.0.7 (slightly different error message) but is also valid with the latest version.
#### Live demo with steps to reproduce
http://jsfiddle.net/re7c1qcs/5/

#### Affected browser(s)
Tested in Chrome, Firefox

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.
It looks like the issue is caused by the boost module - @cvasseng

**Comment by TorsteinHonsi** [comment]
Further simplified demo: http://jsfiddle.net/highcharts/re7c1qcs/6/
