### ISSUE TITLE
Data Label getting truncated for some cases

### ISSUE THREAD

**Issue by satyendra-singh-talentica** [highcharts/highcharts#7482]
#### Expected behavior
Y-Axis should adjust to accommodate Labels

#### Actual behaviour
Data Label getting truncated.

#### Live demo with steps to reproduce
http://jsfiddle.net/0cq5boa7/2/

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi,

This doesn't look like a bug. 
You have set crop to false, so the label is rendered partially outside of the plot area.
Set crop to true or remove the option (by default crop is enabled).
Demo: http://jsfiddle.net/BlackLabel/0cq5boa7/3/

Please provide more info if you think this is a bug and the case will be reopened.
If you require more technical support please use any other support channel - we are trying to keep the github only for bugs. https://www.highcharts.com/support

**Comment by satyendra-singh-talentica** [comment]
Hi,
The example you gave http://jsfiddle.net/BlackLabel/0cq5boa7/3/
with crop = true (or without crop, i.e. enabled by default)
The label on the largest bar doesn't show up.

The label should be shown for all bars and within the plot area.
Or the plot area should adjust to accommodate the labels.

**Comment by KacperMadej** [comment]
There's no room for the label and it's cropped. There's no implemented logic that would increase the axis extremes or change chart to fit dataLabels. 

You can place the dataLabels inside - http://jsfiddle.net/BlackLabel/0cq5boa7/4/ or create an enhancement suggestion on userVoice to add the feature you need - highcharts.uservoice.com/forums/55896-general
The most popular ideas are getting implemented.

**Comment by satyendra-singh-talentica** [comment]
Sure.
Thanks
