### ISSUE TITLE
Shared tooltip doesn't show correctly when pointer is on point in Polar chart

### ISSUE THREAD

**Issue by steveferry** [highcharts/highcharts#7483]
#### Expected behaviour
The tooltip should show data from the points where the pointer is

#### Actual behaviour
Show the previous tooltip
#### Live demo with steps to reproduce

[Polar-spider example](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/polar-spider/)
With the pointer, go from the points on 'Administration', to one of the points on 'Sales' without crossing it to the right side. The tooltip for 'Administration' is still visible but not the 'Sales' one.

[Btw work fine with a previous version of Highcharts (4.0.1)](http://jsfiddle.net/nwg2wft5/)

#### Affected browser(s)
Firefox, Chrome, Opera

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.
Looks like regression since 4.1.0 - since that version the points are not found until pointer hovers over the start/end gridline.

**Comment by TorsteinHonsi** [comment]
In 4.0.x there was some logic for wrapping the tooltip points, that was removed: 

https://github.com/highcharts/highcharts/blob/v4.0.4/js/parts-more/Polar.js#L52-L57

What probably happened is that we introduced k-d-trees for tooltip positioning, which works nicely for non-shared tooltips, but doesn't handle this case of shared tooltips.
