### ISSUE TITLE
Mozilla Addons Linter finds a "bad word"

### ISSUE THREAD

**Issue by ashclarke** [highcharts/highcharts#7485]
When Highcharts is included in a Firefox extension bundle, the extension is flagged by their validator as having content that violates their terms of use.

This is because of the abbreviation used to define the cumulative total for stacking:

https://github.com/highcharts/highcharts/blob/0885712ab265012505d2c1db6faab2dad2a1639f/js/parts/Stacking.js#L256

https://github.com/highcharts/highcharts/blob/0885712ab265012505d2c1db6faab2dad2a1639f/js/parts/Stacking.js#L274

Would it be possible to rename this to `cumulative` in future?

Reference:

https://github.com/mozilla/addons-linter/blob/master/src/badwords.json#L92

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.
This can be an enhancement suggestion.
