### ISSUE TITLE
Top-level column headers are missing in XLS exports

### ISSUE THREAD

**Issue by AleksueiR** [highcharts/highcharts#7486]
#### Expected behaviour
For XLS exports, I expect the table to have two-level headers since the accessibility module adds top-level columns:
HTML table:
![](https://i.imgur.com/lH54KiT.png)

XLS:
![](https://i.imgur.com/64ufnQS.png)

#### Actual behaviour
The top-level headers are missing in the actual output.
![](https://i.imgur.com/SwVrZdC.png)

#### Other
Same happens with CSV exports, but I don't think having two-level headers is a good idea for CSV files. They should probably keep the headers as they rendered without the accessibility module:
![](https://i.imgur.com/xbOSkef.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/ouroborosDragon/aga1k7nd/10/

#### Affected browser(s)
All.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.
This looks more like an enhancement suggestion than a bug, because both modules are not directly connected. The info is there, but given in a different format.

**Comment by AleksueiR** [comment]
Not all info is there, when the accessibility module is added, the series names are stripped from the export:

#### without accessibility module
http://jsfiddle.net/ouroborosDragon/aga1k7nd/10/
![](https://i.imgur.com/8B27XW4.png)

#### with accessibility module
http://jsfiddle.net/ouroborosDragon/aga1k7nd/11/
![](https://i.imgur.com/BDod6Mp.png)

**Comment by TorsteinHonsi** [comment]
We're currently working on this, expect a fix very soon.
