### ISSUE TITLE
Need bar chart tap event in iOS native code

### ISSUE THREAD

**Issue by anurag1991** [highcharts/highcharts#7487]
Hi ,

I am using HighCharts for displaying my data and i am not sure how i can get bar tap event in my native iOS code, is there any delegate or any function that we can render to get tap event and do we customize things like navigating to another controller.

Need Help here, appreciated any help.

**Comment by KacperMadej** [comment]
Hi,

Please check out the official iOS wrapper - https://www.highcharts.com/blog/products/mobile/

Please use any other support channel if the case is not a bug report - we try to keep the github for bugs.
https://www.highcharts.com/support
