### ISSUE TITLE
Pareto series axis value is beyond 100%

### ISSUE THREAD

**Issue by praveenn-vbi** [highcharts/highcharts#7488]
#### Expected behaviour
Pareto series axis value should be from 0% to 100%

#### Actual behaviour
Pareto series axis value is beyond 100%
![image](https://user-images.githubusercontent.com/20218070/33593536-d8ff2d2c-d9b5-11e7-84d2-d13949262ff4.png)

#### Live demo with steps to reproduce

[JS Fiddle Link](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/highcharts/demo/pareto/)

#### Affected browser(s)
All browsers

**Comment by KacperMadej** [comment]
Hi,

This is cause by `alignTicks` being set to true by default.
To keep the pareto's axis in 0-100% range set the `alignTicks` to `false` and if you want to ensure same tick alignment set the same amount of ticks for both yAxes. Demo: http://jsfiddle.net/BlackLabel/10t340nq/

This doesn't look like a bug - if you have more info confirming the case being a bug please provide it and the issue could be reopened.

**Comment by praveenn-vbi** [comment]
@KacperMadej  Thanks for your input...
