### ISSUE TITLE
compatibility of sankey and no-data-to-display modules

### ISSUE THREAD

**Issue by Shiro00000** [highcharts/highcharts#7489]
#### Expected behaviour
if a sankey diagram is displayed, there should not be shown "no data to display"

#### Actual behaviour
"no data to display" is always displayed, no matter if a sankey diagram is shown or not
if another series is added no-data-to-display works correct. it seems to just ignore the sankey-diagram

#### Live demo with steps to reproduce
http://jsfiddle.net/L8vs4dsf/

just hang in both modules and insert a sankey-diagram

#### Affected browser(s)
tested in google chrome
![sankeyshownodata](https://user-images.githubusercontent.com/32356888/33598451-1920513c-d9a3-11e7-96a3-75ea4b2802c7.PNG)

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the bug.

*Internal note:* snakey doesn't have dataMin nor dataMax set, so it's recognized by the no-data-to-display as an empty:
https://github.com/highcharts/highcharts/blob/94aac8904380170b881585a517319cfe0e7ad158/js/modules/no-data-to-display.src.js#L149-L151
