### ISSUE TITLE
Highcharts Error #25: Getting error that moment is not loaded

### ISSUE THREAD

**Issue by francinen** [highcharts/highcharts#7492]
#### Expected behaviour
I'm attempting to set the global `timezone` setting in a module where I am already importing `moment`:

```js
import moment from 'moment';
import Highcharts from 'highcharts';

Highcharts.setOptions({
    global: {
        timezone: 'America/Toronto'
    }
});
```

#### Actual behaviour
Even though I'm explicitly importing moment in the module, I'm still seeing [`Highcharts error #25`](https://www.highcharts.com/errors/25) in my console.

#### Live demo with steps to reproduce
N/A

#### Affected browser(s)
Currently testing on Chrome.

**Comment by zhy1stgg** [comment]
you should set moment to Window object by `window.moment = moment` 

source code: 
![snipaste_2017-12-06_15-14-08](https://user-images.githubusercontent.com/6829290/33649335-7acbde6a-da98-11e7-900b-4f661b47ecd5.png)

**Comment by KacperMadej** [comment]
Hi @francinen ,

If the problem is not resolved then please provide more info and a live demo - the issue will be reopened if needed.

**Comment by francinen** [comment]
It works 👍  Thanks for the prompt response, @zhy1stgg!
