### ISSUE TITLE
Stacked area chart with null value render incorrectly after redraw

### ISSUE THREAD

**Issue by beelit94** [highcharts/highcharts#7493]
#### Expected behaviour
showing gap for the null value after redraw with data contain null value

#### Actual behaviour
the area chart connected and didn't show any gap.
And the result is different than first create chart with the same data

#### Live demo with steps to reproduce
https://jsfiddle.net/q73odptz/

#### Affected browser(s)
chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @beelit94
It looks like the issue is caused by stacking param. Without it it behaves properly.

**Comment by beelit94** [comment]
@sebastianbochan indeed. Would you able to suggest any workaround for this other than destroy the chart?
