### ISSUE TITLE
addSeries() combined with boost.js throws console errors.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#7499]
#### Actual behaviour

While using addSeries() combined with boost.js module there are errors throwed in console, and one of added series isn't visible.

Might be related to [7309](https://github.com/highcharts/highcharts/issues/7309)

#### Live demo with steps to reproduce
[https://jsfiddle.net/daniel_s/vgoq9f4r/](https://jsfiddle.net/daniel_s/vgoq9f4r/)

#### Occurence

v6.0.0 and above

**Comment by KacperMadej** [comment]
@cvasseng

**Comment by TorsteinHonsi** [comment]
First of all, I don't know if it resolves the actual use case, but the demo doesn't adhere to best practice. In stead of removing the two series, setting new data to the option set and add new series, it is recommended to use `Series.setData`. This also resolves the issue with the console error: https://jsfiddle.net/highcharts/vgoq9f4r/1/.

**Comment by TorsteinHonsi** [comment]
#### Simplified demo
https://jsfiddle.net/highcharts/vgoq9f4r/2/

**Comment by TorsteinHonsi** [comment]
Debugging so far points to the `shouldForceChartSeriesBoosting` function. If first returns `false` as expected, but when adding the second series it returns `true`, which is not expected as we only have two series each with four points in the chart. Will discuss this with @cvasseng.
