### ISSUE TITLE
lineWidth, color options are not working in series

### ISSUE THREAD

**Issue by Deimos620** [highcharts/highcharts#7500]
I draw a line graph with highcharts / AngularJS. Here is JSfiddle link.

Highcharts.chart('container', {..})
https://jsfiddle.net/Texas101/pL0at45o/

As you can see, I set linewidth and color for every series, and it works correctly.

I've used the same code in my application, but the linewidth and color options are not working. 
Here is the image of the graph on my application. 

![local-graph](https://user-images.githubusercontent.com/20041972/33728551-2639ad96-db51-11e7-980f-66c133de102b.jpg)

As you can see, lineWidth and color options are not working, and automatically added _colorIndex option. It seems these colors are automatically allocated to these series. I want to fix this problem.

Is this something you'd faced before? Why options are not working and colors / lineWidths are automatically allocated? Is there any solution to fix this problem?

**Comment by pawelfus** [comment]
Hi @Deimos620 

Thank you for reporting the issue. Could you recreate issue in a standalone environment? Adding `_colorIndex` doesn't change anything, please take a look: https://jsfiddle.net/pL0at45o/1/ If it's not easy to recreate the issue then contact with our [support](https://www.highcharts.com/support).

**Comment by Deimos620** [comment]
Hello @pawelfus 

Thanks for checking my report.
Yes. I tried to reproduce it in independent environment for a few times, but it works correctly in standalone environment.
I "copied" and "pasted" code snippet it into my application, but it doesn't work every time.
Of course, I am using the recent version of highcharts(v 6.0.3, 2017.11.14).

So, here is a question, is there any options or settings that let highcharts set _colorIndex to arrange the color to series?

**Comment by pawelfus** [comment]
Hi @Deimos620 

Thank you for the details. `_colorIndex` is used internally, only for series that **don't** have set `series.color`: https://jsfiddle.net/pL0at45o/2/ and it's necessary for updating series, to keep the original color (in case `series.color` is not defined).

If you have problems with setting up a live demo, please, contact with [our support](https://www.highcharts.com/support).

Closing this ticket as we can not recreate the issue. When the demo will be available, please reopen the issue.

**Comment by Deimos620** [comment]
Dear @pawelfus 

I am contacting again because of I found the issue.
I've installed highcharts with bower, with this command
bower install highcharts
In the "highcharts" directory, I've found two highcharts.js files.
One is : bower_components/highcharts/highcharts.js
Another one is: bower_componetns/highcharts/js/highcharts.js
They have same version mark like below.
>  ( Highcharts JS v6.0.3 (2017-11-14)
> 
>  (c) 2009-2016 Torstein Honsi
> 
>  License: www.highcharts.com/license

And the issue, I mentioned above(can not control line width and color) is occured when I use "js/highcharts.js", instead of highcharts.js in root directory.
I've updated highcharts lib from "js/highcharts.js" to "highcharts.js", and it worked correctly.

Which one is true version of highcharts? "js/highcharts.js" or "highcharts.js"? What is different between two versions of library?

**Comment by pawelfus** [comment]
Hi @Deimos620 

Thank you for the details, that explains everything :) `js/highcharts.js` is a styled version of Highcharts - all styles (like colors) are set via CSS. You can read more in our [docs](https://www.highcharts.com/docs/chart-design-and-style/style-by-css). In short, this is expected behaviour for styled version, `series.color` is not applied as stated in our [API docs](https://api.highcharts.com/highcharts/plotOptions.series.color).

**Comment by Deimos620** [comment]
Hi @pawelfus 

Thanks for your reply. I understand everything and that works for me.
Thanks again and glad to close issue.
