### ISSUE TITLE
How to collapse a time gap?

### ISSUE THREAD

**Issue by ronczzzz** [highcharts/highcharts#7502]
I would like to be able to collapse a gap greater than ten minutes and show a icon that indicates there was a gap in the data and of course have the time labels correct at the top as pictured below.  Can I do this in highcharts?  Thanks in advance.

Current graph:
![image](https://user-images.githubusercontent.com/3877793/33735200-3b0da67a-db54-11e7-8f81-6dea294ff392.png)

desired graph:
![image](https://user-images.githubusercontent.com/3877793/33735223-4c6dde08-db54-11e7-9c01-8ec7a5519376.png)

**Comment by pawelfus** [comment]
Hi @ronczzzz 

Thanks for using Highcharts! It looks like you need [gaps](https://api.highcharts.com/highstock/plotOptions.series.gapSize) and/or [breaks](https://api.highcharts.com/highcharts/xAxis.breaks). In general, if you have any questions, please contact with our [support](https://www.highcharts.com/support) - we use github for bug reports :)
