### ISSUE TITLE
Encoded html characters are displayed as is

### ISSUE THREAD

**Issue by mnoskov** [highcharts/highcharts#7504]
Quotes `&laquo;`, `&raquo;` and others after encoding are displayed as raw text in titles and legend, and `&quot;` displayed as `";` (quote and semicolon).

#### Live demo with steps to reproduce
http://jsfiddle.net/mnoskov/9uo6huqr/2/

#### Affected browser(s)
Chrome, Firefox

**Comment by pawelfus** [comment]
Hi @mnoskov 

Thank your reporting the issue. You are right, text is rendered as is in SVG as we don't translate `&laquo;`. You can workaround the issue setting `title.useHTML = true`: http://jsfiddle.net/9uo6huqr/4/

**Comment by mnoskov** [comment]
Thanks!

**Comment by TorsteinHonsi** [comment]
There's also the new [escapes object](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#escapes) that you can extend:

http://jsfiddle.net/highcharts/9uo6huqr/5/
