### ISSUE TITLE
Linked multiple axis breaks drilling

### ISSUE THREAD

**Issue by GertVen** [highcharts/highcharts#7505]
#### Expected behaviour
Chart will drill, and when returning to root level the chart will look the same as with first execution

#### Actual behaviour
->Drilling on X Axis member drills correctly but returning to root level corrupts left axis and grid lines (grid lines of right axis are turned off in the given example)
->Drilling on chart member, such as the bar element inside the chart removes all chart elements

#### Live demo with steps to reproduce
http://jsfiddle.net/txy8eptx/1/

See "Actual behaviour" for steps

#### Additional information
This only seems to occur when the left axis is linked to the right one (Axis 0 inked to 1). Everything works correctly when the right axis is linked to the left one (Axis 1 to Axis 0)

#### Affected browser(s)
Google Chrome
Microsoft Edge
Did not test further

All code generated via official Highcharts Wrapper

**Comment by pawelfus** [comment]
Hi @GertVen 

Thank you for reporting this bug! You are right, changing order of axes (first "main" axis, then linked one) works fine: http://jsfiddle.net/txy8eptx/2/
