### ISSUE TITLE
Problem with Chart Fixed placement columns 

### ISSUE THREAD

**Issue by danilomcb** [highcharts/highcharts#7506]
I'm trying to create a chart of the Fixed placement columns type used in the example on the Highcharts website. In my case, I need the x-axis to be of the datetime type, but when a single reference date is added to the periods, the graph columns will overlap. 

#### Expected behaviour
The expected behavior would be for the columns to be separated as in this example using categories: http://jsfiddle.net/n1nkyhse

#### Actual behaviour
Currently, using datetime as the x-axis behavior is this: http://jsfiddle.net/z5f1owhg

**Comment by KacperMadej** [comment]
Hi,

Add pointRange and the chart looks the same - it's not calculated properly by default because all point have the same x value.
Demo: http://jsfiddle.net/BlackLabel/z5f1owhg/1/

**Comment by danilomcb** [comment]
Thank you @KacperMadej. Worked perfectly
