### ISSUE TITLE
Misplaced winbarb stems on highstock during scrolling

### ISSUE THREAD

**Issue by rychoo2** [highcharts/highcharts#7507]
Hi, I am using windbarb series on highstock chart type. There is a visual problem displaying stems around chart edges as you can see on attached picture and during scrolling on jsfiddle.

Anything that can be done about it?

#### Live demo with steps to reproduce
Keep scrolling the chart below. The edge stems will be appearing misplaced on top of the chart.
http://jsfiddle.net/9cuqneso/

![image](https://user-images.githubusercontent.com/4820692/33770572-6c80106e-dc2e-11e7-99e4-6aeb3c1f207f.png)

#### Affected browser(s)
Chrome 62

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting the issue.

windbarb is not officially supported for Highstock - it's not a part of Highstock API.
Here's a demo of the problem in Highcharts:
http://jsfiddle.net/BlackLabel/9cuqneso/1/
Steps: zoom into the chart - arrows misplaced

**Comment by TorsteinHonsi** [comment]
Simplified demo: http://jsfiddle.net/highcharts/9cuqneso/2/

**Comment by rychoo2** [comment]
Hello, 
According to changelog this issue is supposed to be fixed in 6.0.4 but it doesn't appear so.
Could you please revisit this?
See jsfiddle with 6.0.4:
http://jsfiddle.net/9cuqneso/4/
Steps: zoom into the chart - arrows misplaced

**Comment by pawelfus** [comment]
Hi @rychoo2 

Thank you for letting us know, it looks like simplified demo was a separate case when it fails. Let me reopen the issue. Simpleified demo with zoom: http://jsfiddle.net/9cuqneso/5/

**Comment by rychoo2** [comment]
Hello Team,
Thanks for follow up. We found out that setting pointRange: 0 in plotOptions.series fixes the problem.
http://jsfiddle.net/9cuqneso/6/
Maybe that should be the default for windbarb series.

**Comment by TorsteinHonsi** [comment]
Predictable reproduction: http://jsfiddle.net/9cuqneso/8/
