### ISSUE TITLE
chart.destroy() error if you call setData with redraw=false

### ISSUE THREAD

**Issue by jacobweber** [highcharts/highcharts#7509]
#### Expected behaviour
Call chart.series[n].setData(data, false), to set the data but skip the redraw.
Then call chart.destroy(). You shouldn't get an error.

#### Actual behaviour
When you call destroy(), you get an error here, when it tries to call groupedData[i].destroy():
```
        seriesProto.destroy = function() {
            var series = this,
                groupedData = series.groupedData || [],
                i = groupedData.length;

            while (i--) {
                if (groupedData[i]) {
                    groupedData[i].destroy();
                }
            }
            baseDestroy.apply(series);
        };
```

#### Live demo with steps to reproduce
http://jsfiddle.net/hu7kzkdp/

#### Affected browser(s)
Chrome 62.0.3202.94 / Mac

**Comment by pawelfus** [comment]
Hi @jacobweber 

Thank you for reporting this issue and all of the details! 

*Internal note:*
I guess it's a case where `point.destroy()` removed all of the properties of a point but not the point itself. So probably three possible solutions:

- `point.destroy()` will remove point too, but only for grouped points
- add checking for `groupedData[i].destroy` (it shouldn't affect performance, it's only on `series.destroy()` and only for grouped data)
- make sure `series.groupedData` is nullified (I think this may be the real culprit in this case)

**Comment by TorsteinHonsi** [comment]
#### Modified demo
We need a specific width for the error to occur reliably: http://jsfiddle.net/highcharts/hu7kzkdp/3/

**Comment by TorsteinHonsi** [comment]
Turns out we already had a `destroyGroupedData` function where the points were guarded, so I simply called that instead. See the demo with the fix applied: http://jsfiddle.net/highcharts/hu7kzkdp/4/
