### ISSUE TITLE
Question about align column in X-Axis and duplicate Period

### ISSUE THREAD

**Issue by anhdangx** [highcharts/highcharts#7510]
#### Expected behaviour
- Period is no longer duplicated
- Each Period column is aligned to the center (like this: https://www.highcharts.com/demo/column-stacked)

#### Actual behaviour
- Please see my below picture
![highchart](https://user-images.githubusercontent.com/33924801/33823921-4cad138c-de8f-11e7-9224-1a7bb23655db.png)
+ There are 2 Mar 2018
- Period column is not aligned like this: https://www.highcharts.com/demo/column-stacked

#### Affected browser(s)
Chrome, Firefox, Microsoft Edge, Internet Explorer, Safari

**Comment by pawelfus** [comment]
Hi @anhdangx 

Thank you for reporting this issue. Could you recreate the issue in jsFiddle? I assume you are not using categorized xAxis (`xAxis.categories = [ ... ]`)?

**Comment by anhdangx** [comment]
Hi @pawelfus 
Thank for your reply. Actually, I am not a coder. I am just BA. We have implemented a new function related to highchart. Then we are facing those 2 issues but dev explained that this is from the core of highchart. That why I came here to get the answer from highchart team.
This is the js file in my tool `{
 "maxY": 695000.0,
 "title": {
  "text": ""
 },
 "series": [{
  "displayValues": true,
  "name": "RES",
  "yAxis": 0,
  "dataType": "$",
  "data": [
   [1512086400000, 0.0],
   [1514764800000, 0.0],
   [1517443200000, 0.0],
   [1519862400000, 0.0],
   [1522540800000, 150000.0],
   [1525132800000, 200000.0],
   [1527811200000, 300000.0],
   [1530403200000, 350000.0],
   [1533081600000, 400000.0],
   [1535760000000, 420000.0],
   [1538352000000, 420000.0],
   [1541030400000, 430000.0],
   [1543622400000, 440000.0]
  ],
  "stack": 1,
  "color": "#7cb5ec",
  "type": "column",
  "id": "id_1_1065"
 }, {
  "displayValues": true,
  "name": "Finance",
  "yAxis": 0,
  "dataType": "$",
  "data": [
   [1512086400000, 0.0],
   [1514764800000, 0.0],
   [1517443200000, 0.0],
   [1519862400000, 0.0],
   [1522540800000, 0.0],
   [1525132800000, 0.0],
   [1527811200000, 0.0],
   [1530403200000, 0.0],
   [1533081600000, 0.0],
   [1535760000000, 0.0],
   [1538352000000, 0.0],
   [1541030400000, 0.0],
   [1543622400000, 0.0]
  ],
  "stack": 1,
  "color": "#434348",
  "type": "column",
  "id": "id_1_1061"
 }, {
  "displayValues": true,
  "name": "Technology",
  "yAxis": 0,
  "dataType": "$",
  "data": [
   [1512086400000, 0.0],
   [1514764800000, 0.0],
   [1517443200000, 0.0],
   [1519862400000, 0.0],
   [1522540800000, 0.0],
   [1525132800000, 0.0],
   [1527811200000, 0.0],
   [1530403200000, 0.0],
   [1533081600000, 0.0],
   [1535760000000, 0.0],
   [1538352000000, 0.0],
   [1541030400000, 0.0],
   [1543622400000, 0.0]
  ],
  "stack": 1,
  "color": "#90ed7d",
  "type": "column",
  "id": "id_1_1062"
 }, {
  "dashStyle": "ShortDash",
  "name": "Total Benefits",
  "yAxis": 0,
  "dataType": "$",
  "type": "spline",
  "data": [
   [1512086400000, 0.0],
   [1514764800000, 0.0],
   [1517443200000, 295000.0],
   [1519862400000, 295000.0],
   [1522540800000, 695000.0],
   [1525132800000, 695000.0],
   [1527811200000, 695000.0],
   [1530403200000, 695000.0],
   [1533081600000, 695000.0],
   [1535760000000, 695000.0],
   [1538352000000, 695000.0],
   [1541030400000, 695000.0],
   [1543622400000, 695000.0]
  ]
 }],
 "yAxis": [{
  "title": {
   "text": "$AUD of Benefits",
   "margin": 20
  },
  "max": null,
  "labels": {
   "format": ""
  },
  "stackLabels": {
   "formatter": null,
   "enabled": true,
   "offset": 20,
   "opposite": false
  },
  "min": null,
  "opposite": false,
  "type": "$"
 }],
 "chart": {
  "style": {
   "fontFamily": "Open Sans"
  },
  "type": "column",
  "marginRight": 150
 },
 "tooltip": {
  "shared": true,
  "formatter": null,
  "useHTML": true
 },
 "plotOptions": {
  "column": {
   "stacking": "normal",
   "dataLabels": {
    "enabled": false
   }
  }
 },
 "period_type": true,
 "xAxis": {
  "labels": {
   "style": {
    "fontSize": "12px"
   }
  },
  "title": {
   "text": "Monthly Timescale"
  }
 },
 "legend": {
  "y": 10,
  "itemStyle": {
   "fontWeight": "normal",
   "fontSize": "13px"
  }
 }
}`

**Comment by anhdangx** [comment]
We just have this issue when X-Axis is Timeline (Period)

**Comment by anhdangx** [comment]
We already can fix the duplicate Period issue. But:
- With categorized xAxis (xAxis.categories = [ ... ] we can use tickmarkPlacement: 'between'
- With timeline xAxis, how to align label like tickmarkPlacement: 'between'?
Please see my below 2 charts (they have different alignment way):
- Chart 1: Timeline X-Axis
- Chart 2: Categories X-Axis
![highchart1](https://user-images.githubusercontent.com/33924801/33874528-b3092efa-df51-11e7-9d59-195c4cfdc855.png)

**Comment by pawelfus** [comment]
Hi @anhdangx 

Just checked your demo, looks fine: http://jsfiddle.net/BlackLabel/su07pf8b/1/

![screen shot 2017-12-12 at 17 29 24](https://user-images.githubusercontent.com/1453926/33895991-0b849794-df62-11e7-90b3-04c0097b381d.png)

Regarding your questions, please contact with our [support](https://www.highcharts.com/support). We use github tickets as bug reports. Just a short answer here: you should be able to translate timestamps to categories and render them on a chart (like you have with Q1 20xx).

**Comment by VasilPetrovDigifico** [comment]
> We already can fix the duplicate Period issue. But:
> 
> * With categorized xAxis (xAxis.categories = [ ... ] we can use tickmarkPlacement: 'between'
> * With timeline xAxis, how to align label like tickmarkPlacement: 'between'?
>   Please see my below 2 charts (they have different alignment way):
> * Chart 1: Timeline X-Axis
> * Chart 2: Categories X-Axis
>   ![highchart1](https://user-images.githubusercontent.com/33924801/33874528-b3092efa-df51-11e7-9d59-195c4cfdc855.png)

How you are fix duplicate?

**Comment by KacperMadej** [comment]
The above question seems to be for @anhdangx 
(Adding username to trigger notification)

**Comment by VasilPetrovDigifico** [comment]
@KacperMadej 
I ask , how he did it
