### ISSUE TITLE
Bubble chart with series containing points with null in all x values  in any one series. 

### ISSUE THREAD

**Issue by vbiarulkumar** [highcharts/highcharts#7515]
**Expected behavior** 
The chart should be correctly rendered when data points have null in all x values in any one series.

**Actual behavior** 
The chart is not drawn when data points have null in all x values in any one series.

**Sample series data:** 
```js
[{**//Series 1**
        data: [       
            { x:100, y: 102.9, z: 14.7, name: 'DE', country: 'Germany' }     
        ]
    },{**//Series 2**
        data: [
            { **x: null**, y: 95, z: 13.8, name: 'BE', country: 'Belgium' }
        ]
    }]
```
**Live demo with steps to reproduce**
http://jsfiddle.net/ArulkumarSambasivam/mar7sems/5/

This issue may be related to
#7369,#4031

**Comment by pawelfus** [comment]
Hi @vbiarulkumar 

Thank you for reporting this bug.

Minified demo: http://jsfiddle.net/x9eotjrj/ (again, inherited from the scatter series: http://jsfiddle.net/x9eotjrj/1/ )

**Comment by TorsteinHonsi** [comment]
It goes beyond the scatter series too - inherited from the base Series: http://jsfiddle.net/highcharts/x9eotjrj/2/
