### ISSUE TITLE
Pie chart sliced rendering issue

### ISSUE THREAD

**Issue by krunalshah68** [highcharts/highcharts#7518]
#### Expected behavior
Slices should be aligned properly

#### Actual behaviour
Some of the slices are placed bit oddly!

Look at chrome, other and firefox. They look out of sync!
![highcharts demo jsfiddle](https://user-images.githubusercontent.com/3402958/33882723-155e5dfc-df5f-11e7-93c4-96ddedaae57f.png)

#### Live demo with steps to reproduce

JS Fiddle: [http://jsfiddle.net/jwr903na/](http://jsfiddle.net/jwr903na/)

**Comment by pawelfus** [comment]
Hi @krunalshah68 

Thank you for reporting this issue. I think this is rendered as expected - slices are moved out of the center (in the direction of the middle-slice), take a look: http://jsfiddle.net/BlackLabel/jwr903na/1/ - (click on each slice twice to slice in).

I guess you want result similar to this one: http://jsfiddle.net/BlackLabel/jwr903na/2/ - where all points are evenly sliced out. In that case, I suggest to use `borderWidth` with `borderColor`, demo: http://jsfiddle.net/BlackLabel/jwr903na/3/

**Comment by krunalshah68** [comment]
Hi @pawelfus 

Thank you so much for your quick response.
And yes you have got it right I want solution as [http://jsfiddle.net/BlackLabel/jwr903na/3/](http://jsfiddle.net/BlackLabel/jwr903na/3/) , but the thing is the UI I'm creating has borders different than background. 
In that case how can I achieve result same as in [http://jsfiddle.net/BlackLabel/jwr903na/3/](http://jsfiddle.net/BlackLabel/jwr903na/3/) ?

Thanks again

**Comment by pawelfus** [comment]
Hi @krunalshah68 

Could you show an example of your design? I guess you mean something like this: http://jsfiddle.net/BlackLabel/jwr903na/5/

Let me close the issue - we use github issues as bugs. If my demo doesn't resolve the issue, please contact our support ([details](https://www.highcharts.com/support)).

**Comment by krunalshah68** [comment]
Hi @pawelfus 

Thanks a lot for the solution. That solves my purpose. Cheers!
