### ISSUE TITLE
Drilldown chart not rendered in styled mode

### ISSUE THREAD

**Issue by oluwasayo** [highcharts/highcharts#7523]
#### Expected behaviour
Columns should display properly at every drilldown level
https://imgur.com/a/jWHqW

#### Actual behaviour
Top-level drilldown columns not rendered. Drilling down into the innermost level (by clicking on the axis labels) displays but not the top levels even when drilling back up.
https://imgur.com/a/HxfZo

#### Live demo with steps to reproduce
http://jsfiddle.net/oluwasayo/w158g3pm/

#### Affected browser(s)
Chrome
Firefox
Safari

**Comment by KacperMadej** [comment]
Hi @oluwasayo 

Thank you for reporting about the problem.
You are mixing styled mode with classic. Use one or the another, not both.

Classic mode (working fine): http://jsfiddle.net/BlackLabel/w158g3pm/1/
Styled mode (bug visible - error in console): http://jsfiddle.net/BlackLabel/w158g3pm/2/
