### ISSUE TITLE
Wrong hc-key for 2 regions in Switzerland map

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7527]
#### Expected behaviour
HC-key should have correct values for all of the regions in Switzerland map

#### Actual behaviour
In Switzerland map, a region "CH-3306" should have hc-key: "CH-BL",
for the region of Basel-Landschaft. Additionally, region "CH-7" should have an hc-key of "CH-NI"
(Nidwalden)

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/ch/ch-all

**Comment by oysteinmoseng** [comment]
As a workaround you can modify the properties of the map in Javascript directly: http://jsfiddle.net/oysteinmoseng/udj7p8m4/

Internal note: We need to fix this in the source data.

**Comment by PaulDalek** [comment]
Here is the demo with corrected hc-key values: http://jsfiddle.net/BlackLabel/fyj5z9dL/.

Internal Note:
I have changed values of postal and postal_new properties in mentioned regions (they where previously set to null). Code of Switzerland map generated with QGIS.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#15
