### ISSUE TITLE
Pie Chart label positioning incorrect on IE11 & Edge when using useHTML

### ISSUE THREAD

**Issue by georgewilde** [highcharts/highcharts#7529]
#### Expected behavior
The labels are positioned so they do not overlap the chart and appear as they do in Firefox and Chrome.

#### Actual behaviour
The labels overlap the chart and the connectors.

#### Live demo with steps to reproduce
Example: http://jsfiddle.net/3kv209d6

Open in IE11 or Edge and you will see the labels are positioned badly.
Open this is Firefox or Chrome and you will see the labels are positioned nicely.

#### Affected browser(s)
Internet Explorer 11 (Windows 10)
Edge (Windows 10)

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

**Comment by georgewilde** [comment]
Hi @KacperMadej,

I agree. I've just tested 5.0.14 and all looks good there.

**Comment by TorsteinHonsi** [comment]
Broken down to the SVGRenderer: http://jsfiddle.net/highcharts/rjqwevvv/
