### ISSUE TITLE
Simple  donut chart with legend

### ISSUE THREAD

**Issue by cotterjd** [highcharts/highcharts#7531]
This seems so simple, but I can't seem to find a chart type that will fulfill these simple needs. the closest I've come is a sunburst or donut chart with only one level or a variable pie, but I can't seem to put a legend with values on these. Any suggestions?

![screen shot 2017-12-13 at 9 25 14 am](https://user-images.githubusercontent.com/2576700/33946563-be2d5158-dfe7-11e7-928c-4cfbf0fdfc6b.png)

**Comment by cotterjd** [comment]
I think I have a workaround, but this seems like it should be among the simplest and easiest things to do with highcharts. http://jsfiddle.net/Ucotter/kvxeregg/4/

**Comment by pawelfus** [comment]
Hi @cotterjd 

Thank you for choosing Highcharts!

Default pie (donut) should be fine, please take a look: http://jsfiddle.net/BlackLabel/4jo945tv/

You need to enable points in legend by setting [`series.showInLegend`](https://api.highcharts.com/highcharts/plotOptions.pie.showInLegend) to true, then use [`legend.labelFormatter`](https://api.highcharts.com/highcharts/legend.labelFormatter) (or `legend.labelFormat`) to show in legend what you need. 

If you have any questions, don't hesitate to contact our [support](https://www.highcharts.com/support) :)

**Comment by cotterjd** [comment]
That's perfect. Thank you.
