### ISSUE TITLE
Chart with table

### ISSUE THREAD

**Issue by danilomcb** [highcharts/highcharts#7532]
There is something in highcharts that makes it possible to create a table below the chart with the values referring to each of the series in their categories

Illustrative graphic image:

![image](https://user-images.githubusercontent.com/4964961/33956383-1cd5ba76-e01d-11e7-888c-930dcef4d318.png)

**Comment by pawelfus** [comment]
Hi @danilomcb 

You can create table using our [Renderer](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer) - you can check an example (a bit different than what you need) in our [FAQ](https://www.highcharts.com/docs/getting-started/frequently-asked-questions#add-data-table).

We also have a module for [exporting data to an HTML table](http://jsfiddle.net/highcharts/VEs7z/3/) and you can vote for other table-modules on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api?query=table).

Let us know if you have any questions. In this case, please contact our [support](https://www.highcharts.com/support) - we use github issues as bug reports.

**Comment by TorsteinHonsi** [comment]
Hi,

Please note that there's a very simple solution to this, the [exporting.showTable](https://api.highcharts.com/highcharts/exporting.showTable) option. The FAQ item is about _exported_ charts. I will make this clearer in the FAQ item.

**Comment by o2v4nd** [comment]
Is there a way to destroy a data table? I'm using Highcharts within a calculator that has slider-driven controls. The graph updates fine, but when I add the exporting module and set the showTable option to 'true', changing a calculator input renders a new table. And when the value is changed via a slider, a new table is created for each step along the slider path.

**Comment by pawelfus** [comment]
Hi @o2v4nd 

Demo for you: http://jsfiddle.net/BlackLabel/x53vyftk/

In short:

- `chart.update({ exporting: { showTable: false }});` will stop re-rendering table
- we need to manually remove old table (jQuery for example: `$('.chart-outer .highcharts-data-table').remove();`).

@TorsteinHonsi - shouldn't `chart.update({ exporting: { showTable: false }});` remove old table too?

**Comment by o2v4nd** [comment]
Thank you pawelfus! That solves my issue.

**Comment by 805bluebell** [comment]
But I was not able to display a table for Pie chart. Used [exporting.showTable](https://api.highcharts.com/highcharts/exporting.showTable) option.

**Comment by KacperMadej** [comment]
@805bluebell 
We'll be happy to help you with your code.
Your comment looks like something that should go through our technical support channels - https://www.highcharts.com/blog/support/
Please don't forget to add a live demo, e.g. in JSFiddle, or provide a way to recreate, test and debug your problem for the technical support when you will be contacting them.
