### ISSUE TITLE
Annotations are anchored on plotArea when there are more than 50 series points.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#7534]
#### Expected behaviour

Annotations should be hidden while their x,y values are out of axes extremes range.

#### Actual behaviour

When zooming or panning a chart, the annotations which are currently out of extreme values are still visible on plotArea. 
We can observe it on **bar** and **column** chart types.

#### Live demo with steps to reproduce

[JSFiddle](https://jsfiddle.net/1qa51ues/)
1. Zoom or try to use panning (with SHIFT key) to see the incorrect behaviour of annotation.

**Comment by KacperMadej** [comment]
The point limit comes from cropThreshold: https://jsfiddle.net/BlackLabel/1qa51ues/1/

Workaround - increase the cropThreshold: https://jsfiddle.net/BlackLabel/1qa51ues/2/

**Comment by KacperMadej** [comment]
@morganfree

**Comment by TorsteinHonsi** [comment]
Use the [Chart.isInsidePlot](https://api.highcharts.com/class-reference/Highcharts.Chart#isInsidePlot) function to test.
