### ISSUE TITLE
Grid Axis: min and max values are calculated incorrectly.

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/highcharts#7536]
#### Expected behaviour
The axis.min should default to the smallest start value in the chart.
The axis.max should default to the largest end value in the chart.

#### Actual behaviour
Max is smaller then it should be, and min is larger then it should be, causing the Gantt chart to be cropped.

#### Live demo with steps to reproduce
You can see from the example that the Grid Axis spans only 3 days, while the data provided spans 7 days.
https://jsfiddle.net/t0r8qz9p/222/

**Comment by oysteinmoseng** [comment]
Seems to be working fine now.
