### ISSUE TITLE
Honolulu should be added as one region without additional islands

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7537]
#### Expected behaviour
On Hawaii map Honolulu should be added as one region without additional islands

#### Actual behaviour
Honolulu is added with small additional islands.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/us/us-hi-all

**Comment by kamilkulig** [comment]
**Fixed demo:** http://jsfiddle.net/BlackLabel/n0rzngyn/

All minor islands that were incorrectly assigned to the Hawaii county have been removed from the map.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#16
