### ISSUE TITLE
drilldown.js works badly whereas drilldown.src.js works fine in 6.0.3

### ISSUE THREAD

**Issue by eportalez** [highcharts/highcharts#7541]
#### Expected behaviour
drilldown.js should work the same as drilldown.src.js works in 6.0.3

#### Actual behaviour
drilldown.js dosen't work the same as drilldown.src.js works in 6.0.3
I observe it by using a code allowing drilldown for multiple series.

#### Live demo with steps to reproduce
JSON
{
--
  | "credits": {
  | "enabled": false
  | },
  | "chart": {
  | "type": "line",
  | "polar": true,
  | "events": {
  | "drilldown": "function(event) { myDrilldown(event, this); }"
  | }
  | },
  | "title": {
  | "text": "",
  | "x": -50
  | },
  | "plotOptions": {
  | "line": {
  | "dataLabels": {
  | "enabled": true,
  | "formatter": "function() { return this.y; }"
  | },
  | "enableMouseTracking": true,
  | "allowPointSelect": true
  | }
  | },
  | "tooltip": {
  | "formatter": "function () { return '<b>' + this.point.name + '</b> : ' + this.y; }"
  | },
  | "legend": {
  | "align": "right",
  | "verticalAlign": "top",
  | "y": 70,
  | "layout": "vertical"
  | },
  | "xAxis": {
  | "gridLineColor": "#C0C0C0",
  | "tickColor": "#C0C0C0",
  | "type": "category",
  | "lineWidth": 1,
  | "tickmarkPlacement": "on"
  | },
  | "yAxis": {
  | "gridLineColor": "#C0C0C0",
  | "lineColor": "#C0C0C0",
  | "lineWidth": 0,
  | "gridLineInterpolation": "polygon",
  | "tickInterval": 5.0,
  | "min": 0.0,
  | "max": 20.0
  | },
  | "series": [
  | {
  | "name": "2017",
  | "pointPlacement": "on",
  | "colorIndex": 0,
  | "data": [
  | { "y": 3.33, "drilldown": "d", "name": "d" }
  | ]
  | },
  | {
  | "name": "Minimum",
  | "pointPlacement": "on",
  | "colorIndex": 10,
  | "data": [
  | { "y": 1.00, "name": "d" }
  | ]
  | }
  | ],
  | "drilldown": {
  | "series": [
  | {
  | "name": "d",
  | "id": "d",
  | "series": [
  | {
  | "name": "2017",
  | "colorIndex": 0,
  | "pointPlacement": "on",
  | "data": [
  | {
  | "name": "a", "y": 5.00
  | },
  | {
  | "name": "b", "y": 3.00
  | },
  | {
  | "name": "c", "y": 2.00
  | }
  | ]
  | },
  | {
  | "name": "Minimum",
  | "colorIndex": 10,
  | "pointPlacement": "on",
  | "data": [
  | {
  | "name": "a", "y": 2.00
  | },
  | {
  | "name": "b"
  | },
  | {
  | "name": "c"
  | }
  | ]
  | }
  | ]
  | }
  | ]
  | }
  | }

JS
/* Drilldown Highcharts */
function myDrilldown(event, chart){
	function findSubSeries(series,id){for(index in series){if(series[index].name==id){return series[index].series}}}
	function addSerieToChart(chart,point,series){for(index in series){chart.addSingleSeriesAsDrilldown(point,series[index])}}
	var serieToDrilldown	= findSubSeries(chart.userOptions.drilldown.series, event.seriesOptions.id);
	addSerieToChart(chart, event.point, serieToDrilldown);
	chart.applyDrilldown();
}

Rq : 
I have too a javscript hack for formatter which uses a function.
You can put something more classic instead of the function for testing

#### Affected browser(s)
all

**Comment by KacperMadej** [comment]
Hi,

Please describe what it the difference and add a live demo - you can edit this JSFiddle: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/column-drilldown/
