### ISSUE TITLE
Last category label does not render when using x-range chart with Highstock

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/highcharts#7546]
#### Expected behaviour
All category labels should be displayed when using x-range chart with Highstock.

#### Actual behaviour
The last category label is not displayed when using x-range chart with Highstock. The reason why I'm using Highstock is because I want to be able to use the navigator with x-range.

#### Live demo with steps to reproduce
http://jsfiddle.net/lanimelrok/nexxvup7/

**Comment by oysteinmoseng** [comment]
Not specific to xrange. Absolute minimal example: http://jsfiddle.net/nexxvup7/2/

**Comment by oysteinmoseng** [comment]
This seems to be due to [yAxis.showLastLabel](https://api.highcharts.com/highstock/yAxis.showLastLabel) being `false` by default in Highstock. Setting this to `true` solves the issue: http://jsfiddle.net/nexxvup7/3/.

Should this perhaps be `true` by default for category axes @TorsteinHonsi?

**Comment by oysteinmoseng** [comment]
#6104 is already open on same issue.
