### ISSUE TITLE
DataGrouping zoom : Previous data stay and new data displayed over 

### ISSUE THREAD

**Issue by trebosc** [highcharts/highcharts#7547]
#### Expected behaviour
On a graph with custom datagrouping, displaying month data. When user click on level (day for example), the month data are deleted and Day data are displayed

#### Actual behaviour
The month data aren't deleted and Day data are displayed over the old one

#### Live demo with steps to reproduce
http://jsfiddle.net/tqyyqmzs/12/
Month data are displayed. 
Click on "Day" or "week" and you will see that month data sill be on the graph and the new data are paint over.

#### Affected browser(s)
All

**Comment by DmitryPorotov** [comment]
That looks like regression in 6.0.4. It works fine in 6.0.3.
http://jsfiddle.net/tqyyqmzs/13/

**Comment by VladislavAlushkin** [comment]
Yes, i have the same error after update to 6.0.4.

**Comment by eiamei** [comment]
Yes, i have the same error after update to 6.0.4.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.

Markers are staying on the chart.

**Workaround:**
- use 6.0.3
or
- disable markers: http://jsfiddle.net/BlackLabel/tqyyqmzs/14/

**Comment by trebosc** [comment]
Disabling markers don't work for column graph : http://jsfiddle.net/tqyyqmzs/15/

**Comment by pawelfus** [comment]
Regression after 985df82a0ceb4565ab203942e3c3d944dac597ae

*Internal note:*
Well, this change was almost the same as I suggested in the related topic: #7509 - only order of removing points is different (ascending vs descending).
Actually, it may be connected to #6985 (something is wrong with points' references).
