### ISSUE TITLE
yAxis extremes range is not stable when linked series is hidden and scrollbar is used

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7549]
#### Expected behaviour
The difference between yAxis.min and yAxis.max should be constant when using scrollbar, even when series is hidden.

#### Actual behaviour
When series is hidden yAxis extremes change when scrollbar is used.

#### Live demo with steps to reproduce
http://jsfiddle.net/wxwcqgd5/13/

Steps:

1. Scroll to the visible point (yAxis max)
2. Hide series
3. Scroll to the yAxis.min
4. Scroll again to the yAxis.max

The number of visible categories changed.

**Comment by muffrank** [comment]
Facing the same issue.
