### ISSUE TITLE
Support other time intervals than days in Gantt

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#7551]
We should ensure that not only day intervals are supported in Gantt.

Torstein set up a demo for this:
Demo: https://jsfiddle.net/highcharts/5vkxoecn/4/
For the internal records, there are two things failing here:
- The X axis should automatically pick hours as the best resolution (based on `tickPixelInterval`)
- The format should automatically comply (based on `xAxis.dateTimeLabelFormats`)

**Comment by TorsteinHonsi** [comment]
Making the grid tick intervals dynamic fixes obvious issues when dealing with small or large time spans, but reveals some problems. See http://jsfiddle.net/highcharts/7qdbsmk1/9/.

## To do

1. Small time intervals don't fit well into the grid concept. For example, it makes little sense with a grid cell for half an hour or six hours. In this scale, time is linear. Check out if it is reasonably feasible to make the grid axis switch to a regular datetime axis for small time intervals, or alternatively make sure whole hours and minutes are used.

2. Some labels, when truncated with an ellipsis, reveal little information. For example, Week 32, Week 33, Week 34 truncates to "Week..., Week..., Week...". Try out alternative `dateTimeLabelFormats` for trunkating, for example "W%W" could be a short form for week. So when an axis label exceeds its cell, the shorter forms should be applied. This goes to other way too. When there is plenty or room to spell out "Monday, september 10", we should not print simply "M".
3. In some cases, the tick interval of the two axes are the same. It is hard to tune this using the `tickPixelInterval` option alone. Check out if we can make axis 1 always use one time unit greater than axis 0.

**Comment by oysteinmoseng** [comment]
Closing this, as it has been implemented in Gantt now.
