### ISSUE TITLE
Candlestick Bars Are Sometimes Drawn Inaccurately

### ISSUE THREAD

**Issue by mlvn23** [highcharts/highcharts#7552]
This is related to #7204.

#### Expected behaviour

A candlestick visualizes the open, high, low, and the close. The top of the body is the open, the highest point of the top wick represents the high, the lowest point of the bottom wick represents the low, and the bottom of the bottom represents the close. The open must be <= high and >= low. The close must be <= high and >= low. If open = to the high, there will not be a top wick. If close = to the low, there will not be a bottom wick.

On Nov 21 bar, there's no bottom wick, but the data shows that the Low < the Close, so there should be one.

On Nov 22 bar, there's no top wick, but the data shows that the High is > the Open, so there should be one.

This is how is should have been plotted:

![image](https://user-images.githubusercontent.com/5626477/34140542-3887c68a-e430-11e7-92cb-9a2fe79f886b.png)

#### Actual behaviour

![image](https://user-images.githubusercontent.com/5626477/34140346-e31ec474-e42e-11e7-9fe3-6f1b80084581.png)

![image](https://user-images.githubusercontent.com/5626477/34140371-0d78c0f8-e42f-11e7-86aa-1435148ea899.png)

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/candlestick/

Click 1M

#### Affected browser(s)

Firefox, Chrome

**Comment by KacperMadej** [comment]
Hi,

This doesn't look like a bug.

For Nov 21st - open = low, so bottom of box and bottom line overlap.
For Nov 22nd - difference with thicker lines is below 1 pixel. Normal state shows correctly and if you increase height of the chart then it's more visible: http://jsfiddle.net/BlackLabel/0xtfyjtz/

Please provide more info if you would like to have the issue reopened.
