### ISSUE TITLE
Column Drilldown for some of 3rd layes is not working

### ISSUE THREAD

**Issue by sepullupes** [highcharts/highcharts#7553]
#### Expected behaviour

should be working on the 3rd layer of drilldown

#### Actual behaviour

When we click on REG MK then appear 2nd drilldown 
but after we click the 2nd layer (some of column is working) 
Column 
12/2016 - Working
1/2017 - Working
2/2017 - Not Working
3/2017 - Working
4/2017 - Not Working
5/2017 - Working
6/2017 - Working
7/2017 - Not Working
8/2017 - Not Working
9/2017 - Not Working
10/2017 - Not Working
11/2017 - Not Working
12/2017 - Not Working

#### Live demo with steps to reproduce
https://jsfiddle.net/zerotomero/ph1w0aaz/

#### Affected browser(s)
FIREFOX

**Comment by KacperMadej** [comment]
Hi,

This doesn't look like a bug.

Your data doesn't have drilldown series with ID of '2/2017' that is required for the drilldown to work. You also have duplicated IDs in drilldown.series array - those should be unique, so maybe that's the source of the problem you have.

We are trying to keep github for bugs, so if you are not sure if a case is a bug or would just require technical support, then contact us using other support channels: https://www.highcharts.com/support
