### ISSUE TITLE
mapbubble chart rendered not correct

### ISSUE THREAD

**Issue by herodhb** [highcharts/highcharts#7554]
#### Expected behaviour
the chart size is normal though the data is not match

#### Actual behaviour
map was very small

#### Live demo with steps to reproduce
http://jsfiddle.net/8fcsgmzj/

**Comment by herodhb** [comment]
there is no such problem when type is 'map'.

**Comment by KacperMadej** [comment]
Hi,

This doesn't look like a bug.

When using series data that is matching with the map data you will get correct chart. Demo: http://jsfiddle.net/BlackLabel/8fcsgmzj/1/

It's a wrong data issue for me, but if you have more info please share.

**Comment by herodhb** [comment]
@KacperMadej 
thanks you for your reply, but the same issue is not reproduced in "map" chart. Demo:
http://jsfiddle.net/96tj7ss7/
it's still a wrong data, but it performs well.

**Comment by KacperMadej** [comment]
@herodhb Yes, but then that series does nothing - you can remove it and it works the same: http://jsfiddle.net/BlackLabel/96tj7ss7/1/

Here's a minimal demo: http://jsfiddle.net/BlackLabel/rtatf4d0/

I'm not sure what is the expected chart what you are using points that are not correct, but the map shouldn't change it's size like that.

**Comment by herodhb** [comment]
@KacperMadej Thank you! you are very nice! it looks like 'map' chart filter the data but 'mapbubble' not.

**Comment by oysteinmoseng** [comment]
I don't think this is necessarily a bug, the bubble points that aren't joined simply don't get `x` and `y` coordinates, which means the data is invalid. You get the same behavior if you try to define a normal bubble series without `x` and `y` data. 

We don't want to filter out all points that are not joined, as these can be manually defined. For example you can manually set `x` and `y` on some points that are not joined to the map.

We could decide to filter out any points that have invalid data at the time of rendering, but this would cause a performance overhead, and we would also have to start doing this for other series types. The current policy on this in Highcharts is to not babysit the user, and assume valid data. This allows for a faster and leaner library, but we can of course debate if we need more error handling.

@TorsteinHonsi any thoughts?

**Comment by TorsteinHonsi** [comment]
> the bubble points that aren't joined simply don't get x and y coordinates, which means the data is invalid.

It looks like it passes the validity test in the `mapbubble` series, which simply tests that `this.z` is a number. So actually the points pass as valid, but are given an x value from 0 because no x given. In my opinion these orphaned mapbubble points should be filtered out, but the `isValid` function runs too soon.
