### ISSUE TITLE
Series area stack: huge "peak" values causes smaller values not rendered when zoomed in

### ISSUE THREAD

**Issue by lebnic** [highcharts/highcharts#7555]
#### Expected behaviour
When zooming on portions of the graph "away" from the huge peak values, normal smaller values should be rendered accurately. Here, a "peak value" of 999999 was used for each series area
![image](https://user-images.githubusercontent.com/6682795/34164810-923e4b5e-e4a8-11e7-9d27-604e741bf4ef.png)
![image](https://user-images.githubusercontent.com/6682795/34164821-9a317750-e4a8-11e7-997a-1ef7263c8f8b.png)
![image](https://user-images.githubusercontent.com/6682795/34164933-e670cc9c-e4a8-11e7-8d5a-63ed2fc6b014.png)

#### Actual behaviour
When "**huge peak values**" are used (here we used **491913125223966660**), small series area values are not all visible when zoomed in
![image](https://user-images.githubusercontent.com/6682795/34164635-1397651a-e4a8-11e7-9a06-6122c4dea510.png)
![image](https://user-images.githubusercontent.com/6682795/34164639-16320ff0-e4a8-11e7-88bb-27cb6ac91682.png)
![image](https://user-images.githubusercontent.com/6682795/34164911-d47874f4-e4a8-11e7-8356-b7ad9b3df5fd.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/lebnic/3h30s0v6/

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
Same as #3201, it happens because the path goes too far outside the viewport. It also happens in Firefox, but only for the area and not the graph itself.

**Comment by lebnic** [comment]
@TorsteinHonsi , is a fix expected for this issue ?

**Comment by pawelfus** [comment]
Hi @lebnic - you are right, it's fixed in a26ca3c commit. You can check the fix in action here: http://jsfiddle.net/BlackLabel/3h30s0v6/6/

**Comment by lebnic** [comment]
You guys are awesome! thanks !
