### ISSUE TITLE
Arearange: zoom out to boosted mode caused error in js

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#7557]
#### Error:
Version 6.0.4: 
```
highcharts.src.js:4274 Uncaught TypeError: Cannot read property 'setAttribute' of undefined
    at H.SVGElement._defaultSetter (highcharts.src.js:4274)
    at H.SVGElement.eachAttribute (highcharts.src.js:2980)
    at H.objectEach (highcharts.src.js:1808)
    at H.SVGElement.attr (highcharts.src.js:2952)
    at H.SVGElement.removeClass (highcharts.src.js:3094)
    at object.setState (highcharts.src.js:33738)
    at object.setState (highcharts-more.src.js:1496)
    at highcharts.src.js:17619
    at Array.forEach (<anonymous>)
    at H.each (highcharts.src.js:1790)
_defaultSetter @ highcharts.src.js:4274
eachAttribute @ highcharts.src.js:2980
H.objectEach @ highcharts.src.js:1808
attr @ highcharts.src.js:2952
removeClass @ highcharts.src.js:3094
setState @ highcharts.src.js:33738
setState @ highcharts-more.src.js:1496
(anonymous) @ highcharts.src.js:17619
H.each @ highcharts.src.js:1790
runPointActions @ highcharts.src.js:17617
onContainerMouseMove @ highcharts.src.js:18059
container.onmousemove @ highcharts.src.js:18169
```

#### Live demo with steps to reproduce
[Demo](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/boost/arearange/) (and [demo github vs current](http://jsfiddle.net/BlackLabel/pv5ermvq/1/))

It looks like problem with not cleared point from `chart.hoverPoints`. This is what actually happens:

- zoom in until we see markers
- reset zoom and **don't** move mouse 
- you can still observe markers from previously zoomed range (shouldn't that be cleaned in reset zoom?)
- original points (`series.points`) are correct, but in `chart.hoverPoints` we still have a point from the old range - but `point.graphic` was destroyed (nullified points). Interesting part: that marker is still visible..

**Comment by pawelfus** [comment]
Found the problem, it's caused by top-graphic which is not cleared out: 

https://github.com/highcharts/highcharts/blob/e61738018b26db200f1ce5b40f8e13d4d354ec51/js/modules/boost.src.js#L2837-L2844

Could we replace this with `destroyElements` method?

```javascript
	if (points) {
		for (i = 0; i < points.length; i = i + 1) {
			point = points[i];
			if (point && point.destroyElements) {
				point.destroyElements();
			}
		}
	}
```
So it will be safe to remove all associated elements to a point? I'm not sure about the performance.. it's called only for SVG-based points, so shouldn't affect Canvas solution, right? On the other hand, we have there more checks than simple `if (point && point.graphic) { ... }`: 

https://github.com/highcharts/highcharts/blob/e61738018b26db200f1ce5b40f8e13d4d354ec51/js/parts/Point.js#L305-L316

@cvasseng @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
> Could we replace this with destroyElements method?

Yes, let's do that! As for performance, this only happens when switching from non-boost to boost mode, so we're limited to the `boostThreshold`.

Will you do the fix?
