### ISSUE TITLE
Bug in waterfall chart updating

### ISSUE THREAD

**Issue by Munksgaard** [highcharts/highcharts#7559]
When updating a waterfall chart, if there are no data points between an intermediate sum and the total, the graph ends up looking strange.

Here's a waterfall chart that demonstrates the erroneous behavior. Notice that the chart looks fine before clicking the button, whereas afterwards the product revenue bar is painted black, the product revenue bar shows the wrong number, and the positive balance is 0:

http://jsfiddle.net/mxLfgco5/2/

Here is a waterfall chart that uses the same data set that the above waterfall chart gets updated to. Notice that it renders just like it should:

http://jsfiddle.net/g1hkLqy3/1/

#### Affected browser(s)

Firefox and chrome

**Comment by Munksgaard** [comment]
Probably related:

An "empty" waterfall (one that contains just an intermediate sum and a total sum) works as it should, but when we try to update a chart with such a dataset, we get the following error in the console: 

    Highcharts error #14: www.highcharts.com/errors/14

[Example without update](http://jsfiddle.net/g1hkLqy3/2/)
[Example with update](http://jsfiddle.net/mxLfgco5/4/)

**Comment by KacperMadej** [comment]
Hi,

This doesn't look like a bug - it's how setData works.

On `Series.setData`, if point count is the same, point will be updated, so you should change type of point (e.g. isSum to false or true) or use `setData` with `updatePoints` set to false.

Demo: http://jsfiddle.net/BlackLabel/mxLfgco5/5/
API reference: https://api.highcharts.com/class-reference/Highcharts.Series#setData

**Comment by Munksgaard** [comment]
Thank you @KacperMadej, that seems to work for my initial problems. However, it doesn't seem to handle the problem in [my second comment](https://github.com/highcharts/highcharts/issues/7559#issuecomment-353011663). But perhaps that warrants a separate issue? [Here](http://jsfiddle.net/mxLfgco5/6/) is a modified example that has the correct `updatePoints`, but still throws an error

**Comment by pawelfus** [comment]
Hi @Munksgaard - thank you for the heads up! You are right, we accidentally missed your second comment. This looks like a bug in ` categorized xAxis. If we use linear xAxis, it works fine: http://jsfiddle.net/bdcw2w8f/1/

Minified buggy demo with categorized xAxis: http://jsfiddle.net/bdcw2w8f/

**Workaround:**
Use `xAxis.categories = [ ... ]` instead of `xAxis.type = 'category'` with point names, demo http://jsfiddle.net/mxLfgco5/7/

**Comment by Munksgaard** [comment]
@pawelfus No worries, I'm just happy to help out.

**Comment by KacperMadej** [comment]
Another workaround - set x values for new points: http://jsfiddle.net/BlackLabel/bdcw2w8f/2/

**Comment by Munksgaard** [comment]
While there are workarounds available, I don't think the core issue has been resolved here. Both of the following examples from the above comments still fail: http://jsfiddle.net/bdcw2w8f/ http://jsfiddle.net/mxLfgco5/6/

**Comment by TorsteinHonsi** [comment]
It turned out to be a variety of #3245, error 14 on initial summary data points. Only this time it only happened on update. See http://jsfiddle.net/highcharts/zskg42xb/ for a demo with the fix applied.
