### ISSUE TITLE
Line series not visible when combined with a heatmap and activated boost.js

### ISSUE THREAD

**Issue by miher** [highcharts/highcharts#7560]
#### Expected behaviour
A line series should be visible when combined with a heatmap and activated boost.js

#### Actual behaviour
The line series is not visible. After deactivating boost.js all data is visible again.

#### Live demo with steps to reproduce
https://jsfiddle.net/1vz6tb0x/

In the fiddle example above deactivate boost in the corresponding line  (47) --> the line series is visible.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

**Comment by cvasseng** [comment]
Internal note: I think the issue is heatmap rendering, it looks like it breaks successive renderings. May be the same issue that's causing #7338.

**Comment by pawelfus** [comment]
It looks like a bit different, than #7338 - here the first series takes precedence over all other types: https://jsfiddle.net/BlackLabel/Lnt73ecd/ (happens only in when heatmap is available).
