### ISSUE TITLE
Tooltip shows wrong point with Boost

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#7561]
#### Expected behaviour
Tooltip should show point from series at the top, like in a situation without Boost:
https://jsfiddle.net/ngoeb02f/

#### Actual behaviour
Tooltip shows point from below. Property zIndex does not work.

#### Live demo with steps to reproduce
https://jsfiddle.net/ksxjec3m/

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
*Internal note:*
Issue similar to #9819 - `zIndex` seems to be missing from implementation. Probably simple sorting series by `zIndex` (then `index`) before rendering could help.
