### ISSUE TITLE
Hiding/showing axis via CSS does not reflow the chart correctly when using HTML:true 

### ISSUE THREAD

**Issue by chabb** [highcharts/highcharts#7565]
Hi,

#### Expected behaviour

When i hide back the axis title, the chart should reflow correctly

#### Actual behaviour
it does not happen

#### Live demo with steps to reproduce
http://jsfiddle.net/eDJfq/33/

1) click on the button -> the  axis title is shown, the chart moves
2) click on the button -> the axis title is hidden, the chart does not get back

If you have a fix for that, i would be super-grateful :) 

Thanks

**Comment by chabb** [comment]
i think the issue is there  (getOffset method) :  

`
                if (axisTitleOptions && axisTitleOptions.text && axisTitleOptions.enabled !== false) {
                    axis.addTitle(showAxis);

                    if (showAxis && axisTitleOptions.reserveSpace !== false) {
                        axis.titleOffset = titleOffset =
                            axis.axisTitle.getBBox()[horiz ? 'height' : 'width'];

                        console.log(axis.axisTitle.element);
                        console.log(axis.axisTitle.element.offsetHeight,
                            axis.axisTitle.element.offsetWidth,
                            axis.titleOffset);
                        titleOffsetOption = axisTitleOptions.offset;
                        titleMargin = defined(titleOffsetOption) ? 0 : pick(axisTitleOptions.margin, horiz ? 5 : 10);
                    }
                }`

i added the console.log statement, it seems that getBBox() is doing some caching, as the returned value are not the same ( titleOffset should be 0, but it's something like 20 ).. i'll take a closer look tomorrow

**Comment by TorsteinHonsi** [comment]
This really a fix, but the recommended way of showing/hiding the title is by using the `Axis.update` function. See http://jsfiddle.net/highcharts/eDJfq/34/.

```js
let count = 0;

$("#update-axis").click(function() {
    chart.yAxis[0].update({
        title: {
            text: (count % 2 ? 'some text' : '')
        }
    });
    count++;
});
```

**Comment by chabb** [comment]
Thanks @TorsteinHonsi .. i took that route; I understand that chart manipulations should not be done via CSS, but via the API, but this was due to some old legacy code
