### ISSUE TITLE
Boost. Serie opacity

### ISSUE THREAD

**Issue by Ty4ka** [highcharts/highcharts#7567]
#### Expected behaviour
Transparency is applied to the series.
https://jsfiddle.net/ty4ka/7mne67t4/

#### Actual behaviour
Since there is no SVG, then an error occurs. And opacity does not apply.
**https://jsfiddle.net/ty4ka/7wzqek5d/**

#### Live demo with steps to reproduce
Move the cursor over the series.
**https://jsfiddle.net/ty4ka/7wzqek5d/**

#### Affected browser(s)
All browsers.

**Comment by KacperMadej** [comment]
Hi,

The custom code you are using will not work with boost because all series are generated as one image.

**Comment by Ty4ka** [comment]
What are the options to add opacity to image and highlight the serie?

**Comment by KacperMadej** [comment]
@Ty4ka All series are in a single image, so it's not possible to highlight a single series. You could update series, but this would require generating all chart anew and will be time consuming - not something that will look good when hovering over a chart. 

In short - currently it's not possible, series would have to be generated in separate images. 

Would you like me to label this issue as an enhancement suggestion?

**Comment by TorsteinHonsi** [comment]
You can set the [seriesThreshold](https://api.highcharts.com/highcharts/boost.seriesThreshold) very high to force the chart to draw one image per series, then you should be able to set the opacity for each image.
