### ISSUE TITLE
Invalid Country Code mapping for SX Sint Maarten

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#7568]
#### Expected behaviour
SX should be linked to Sint Maarten.
Link to ISO standard: https://en.wikipedia.org/wiki/ISO_3166-2:SX

#### Actual behaviour
It is linked to Somaliland

#### Live demo with steps to reproduce
http://jsfiddle.net/2ywjvxxw/

#### Affected browser(s)
All browsers

**Comment by KacperMadej** [comment]
_Internal note:_ Sint Maarten is not in [the world map](https://code.highcharts.com/mapdata/custom/world.js). [Somaliland](https://en.wikipedia.org/wiki/Somaliland) has the same ISO 3166 code as [Somalia](https://en.wikipedia.org/wiki/ISO_3166-2:SO) - changing to `SO` would make the `hc-a2` not unique, but this is not required according to [the docs](https://www.highcharts.com/docs/maps/map-collection).

**Comment by npetralia** [comment]
hello,

Any chance to have an estimated date for bug fix ?

Thanks.

**Comment by oysteinmoseng** [comment]
@npetralia We are aiming for a Q1/Q2 release, but for now you can simply replace this code in the mapData programatically as a workaround. Example: http://jsfiddle.net/2ywjvxxw/1/

**Comment by npetralia** [comment]
@oysteinmoseng thanks for update.

Just one remark my issue is on 'iso-a2' and not on 'hc-a2'.

**Comment by npetralia** [comment]
@oysteinmoseng hello do you have any news on this bug fix ?

**Comment by KacperMadej** [comment]
> Just one remark my issue is on 'iso-a2' and not on 'hc-a2'.

Both are based on the same map property. `iso-a2` will be the same for Somaliland and Somalia - to see difference in possible future map version use `iso-a3`: `Somaliland: SOL, Somalia: SOM`.

Demo: http://jsfiddle.net/BlackLabel/2ywjvxxw/3/

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#17
