### ISSUE TITLE
Disappear graph on the scroll

### ISSUE THREAD

**Issue by avdohusic** [highcharts/highcharts#7569]
#### Expected behaviour
Should work with any set of data which is in the right format.

#### Actual behaviour
Any event on the scroll, "the main" graph disappear.

#### Live demo with steps to reproduce

https://jsfiddle.net/avdohusic/ez6fuhez/1/

#### Affected browser(s)
Any browser.

**Comment by KacperMadej** [comment]
Hi,

This doesn't look like a but.
Your data is not sorted in ascending order by x - the error is in browser console.
Fixed by sorting the data by x (reversing the data array) in ascending order: https://jsfiddle.net/BlackLabel/ez6fuhez/2/
