### ISSUE TITLE
Allow plotOptions to override tooltip formatter function

### ISSUE THREAD

**Issue by cloudshark** [highcharts/highcharts#757]
It would be incredibly useful to allow the `formatter` to be overridden by `plotOptions`.  For example we want change the tooltip of a "flags" series to all uppercase letters:

``` javascript
plotOptions: {
  flags: {
     tooltip: {
        formatter: function() {
            return this.text.toUpperCase();
        }
     }
  }
}
```

This currently cannot be accomplished with only the `pointFormat` option (which is also not working for flags - see #706)

Is there a workaround that would check the series type but still call the defaultFormatter except for specific types?

**Comment by oysteinmoseng** [comment]
This is implemented with current code, and works fine with shared tooltips as well, since we now have a `pointFormatter`: http://jsfiddle.net/2mowm7nc/
