### ISSUE TITLE
type: 'variablepie' creat  charts has a bug,please look this link,thx

### ISSUE THREAD

**Issue by Baymaxxx** [highcharts/highcharts#7570]
#### Expected behaviour
none

#### Actual behaviour
none

#### Live demo with steps to reproduce

https://code.hcharts.cn/temp/HOF6mj

#### Affected browser(s)
chrome

**Comment by KacperMadej** [comment]
Hi,

I'm unable to open the demo, please add another and more description to the bug report.

**Comment by pawelfus** [comment]
Closing due to description of the issue. Chart is rendered as:

![screen shot 2018-04-09 at 13 57 58](https://user-images.githubusercontent.com/1453926/38496514-21eefd6e-3bfe-11e8-8516-8150f02c6c5a.png)
