### ISSUE TITLE
Column Graph taking time to load the 10k points in IE and Chrome even using boost.js

### ISSUE THREAD

**Issue by vikvish1** [highcharts/highcharts#7571]
#### Expected behaviour
Graph must be loaded less than a 1 or 2 secs. 

#### Actual behaviour
Graph taking too much time to load the data around 3-5 secs in Chrome and 10-15secs in IE.
for more info please check the below discussion.
https://forum.highcharts.com/post138573.html#p138573

#### Live demo with steps to reproduce
http://jsfiddle.net/daniel_s/d6Lgnnhq/

#### Affected browser(s)
IE and Chrome

Regards
Vik

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.
In short: even with boost.js, 10k points loads 3 times slower in IE then in Chrome.

**Comment by TorsteinHonsi** [comment]
> In short: even with boost.js, 10k points loads 3 times slower in IE then in Chrome.

That's about what we can expect from IE.

Also, the stacking is what takes most of the time in this sample. If we draw the same data without stacking, it is about five times faster in Chrome.
