### ISSUE TITLE
Heat map sub title

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#7572]
Heat map subtitle overlaps chart area.

#### Live demo with steps to reproduce
http://jsfiddle.net/Pashe4ka/8rLnvsc3/

#### Affected browser(s)
Chrome latest version

**Comment by KacperMadej** [comment]
Hi,

You have set margin top, so it's not calculated automatically. Demo with the option removed: http://jsfiddle.net/BlackLabel/8rLnvsc3/1/

This is not a bug - used options are working correctly.

**Comment by pliasetski** [comment]
Thanks @KacperMadej 
But it works fine for chart, map.

**Comment by KacperMadej** [comment]
@pliasetski Without margin it works fine, because it's calculated automatically. Setting the option prevents the auto calculation and set's the margin as set in the chart option.

Case closed and resolved or there's anything more to it?

**Comment by pliasetski** [comment]
Yes, thank you!
