### ISSUE TITLE
HighCharts Rangebutton not vertically aligned

### ISSUE THREAD

**Issue by springjben** [highcharts/highcharts#7580]
On every version of high charts the text inside the range selector buttons are raised slightly.
Like so: https://i.gyazo.com/069a4b33cbd0e958f2a7b81527bf3858.png

I want to just put almost a padding-top inside the buttons, so the text moves down and becomes central. I like the buttons to remain the same size they are now. Adding padding just makes the button huge.

Any ideas?

**Comment by pawelfus** [comment]
Hi @springjben 

Thank you for reporting the issue. You are right, text is slightly translated to the top! It looks like the real problem is missing vertical alignment option and default value, which is.. `top`, not `middle`! Fixing #1285 issue would resolve this issue too.

**Comment by springjben** [comment]
@pawelfus I looked into that issue, however if I add padding of 10 the buttons increase massively. I like the size they are at now. Using padding and height/width corrupts the buttons.

What is the vertical alignment option you where referring to? Not the position of the actual buttons on the chart?

Thank you for replying.

**Comment by springjben** [comment]
I have tried:

`angeSelector: {
        buttonTheme: {
          verticalAlign: middle,
        },
        selected: 1,
        buttons: [{
          type: 'minute',
          count: 240,
          text: '1h',
        }, {
          type: 'day',
          count: 1,
          text: '1d'
        }, {
          type: 'week',
          count: 1,
          text: '7d'
        }, {
          type: 'all',
          text: 'All'
        }]
      },`

But it doesn't work. I am using this to input highcharts:

<script src="https://code.highcharts.com/stock/highstock.js"></script>
  <script src="https://code.highcharts.com/stock/modules/exporting.js"></script>

**Comment by springjben** [comment]
Doing:

`        buttonTheme: {
          verticalAlign: 'middle',
        },`

Still doesn't make the text inside the buttons in the middle.

**Comment by pawelfus** [comment]
@springjben as I said:
>  It looks like the real problem is **missing** vertical alignment option

It's alignment of the text within the button's background - sorry for the confusion! For example if you set `height: 28` (like  in #1285 issue) text will still be aligned to the top of the button, not middle-aligned. This should be configurable, like #1285 issue describes.

**Comment by TorsteinHonsi** [comment]
Just for the records, the text alignment is pretty consistent across browsers and systems, probably due to our bounding box workarounds in `getBBox`.

![skjermbilde 2018-01-02 kl 15 05 33](https://user-images.githubusercontent.com/227836/34486106-68ff2566-efce-11e7-8536-ba45c318b357.png)
