### ISSUE TITLE
Polar chart - Removing all series from legend causes a UI issue

### ISSUE THREAD

**Issue by alons1** [highcharts/highcharts#7584]
#### Expected behaviour
Numbers removed

#### Actual behaviour
Numbers remain

#### Live demo with steps to reproduce
http://jsfiddle.net/ttcz214e/

#### Notes
This happens because of the yAxis 'max' parameter.
If removed - the issue does not occur.

**Comment by pawelfus** [comment]
Hi @alons1 

Thank you for reporting this issue. This doesn't affect only polar chart, take a look: http://jsfiddle.net/ttcz214e/1/ - in general, if extremes are set, then axes are not hidden. This is caused how [`yAxis.showEmpty`](https://api.highcharts.com/highcharts/yAxis.showEmpty) option works. More details can be found in #705 issue.

**Comment by KacperMadej** [comment]
Closing because it's a duplicate.
