### ISSUE TITLE
xrange xAxis min/max wrongly calculated

### ISSUE THREAD

**Issue by orouz** [highcharts/highcharts#7587]
#### Expected behaviour

setting min and max range on the xAxis, along with `startOnTick` and `endOnTick`, should result with an xAxis that its ticks starts and ends at the specified min and max values. (and only show the relevant part of the series)
 
#### Actual behaviour

first and last tick are sometimes correct and sometimes aren't

#### Live demo with steps to reproduce

http://jsfiddle.net/orouz/jhn4etz4/
https://jsfiddle.net/orouz/3npemjkf/
--- 

i've seen #7345 but it also relates to zooming, which isn't relevant for me here. 
i have also looked at #6999, and it does seem `min/max` is labelled as buggy, but due to the corresponds there, it also seems like it was resolved with a workaround. 
so i'm not quite sure where this bug stands. i'm certainly affected by it :)

**Comment by pawelfus** [comment]
Hi @orouz 

Thank you for reporting this issue. It's not a bug, this is how `startOnTick` and `endOnTick` options work. `start/endOnTick` option doesn't make axis to start at min/max but stretches extremes to nearest tick. For example narrower chart: http://jsfiddle.net/jhn4etz4/5/ - extremes are: 1st of Dec - 15th of Dec. If we set directly `tickInterval` to one day, then it will show exactly what you expect: http://jsfiddle.net/jhn4etz4/6/ - you can notice that all "wrong" extremes has odd numbers (5, 1, 11), which stretches extremes to the nearest even number.

**Comment by orouz** [comment]
oh, i see now. sorry :)
thanks for your time !
