### ISSUE TITLE
yaxis.min breaks the chart if string

### ISSUE THREAD

**Issue by klodoma** [highcharts/highcharts#7593]
If the value if yAxis.min is a string then the chart is not being rendered or it's not visible.
https://api.highcharts.com/highcharts/yAxis.min

#### Expected behaviour
chart visible with min and max active

#### Actual behaviour
chart is not rendered

#### Live demo with steps to reproduce
http://jsfiddle.net/klodoma/07qv283u/
Steps:

- go to yAxis.min settings
- uncomment the string version

![screenshot_31](https://user-images.githubusercontent.com/944350/34434807-11429e5e-ec89-11e7-8e1b-20da311009d1.png)

#### Affected browser(s)
Tested in Google Chrome.

**Comment by pawelfus** [comment]
Hi @klodoma 

Thank you for reporting this issue. I'm not sure if we should fix this, in the [API](https://api.highcharts.com/highcharts/yAxis.min) we have strict type:
> min: Number

Setting `min` to false, NaN etc. also doesn't render a chart, take a look: http://jsfiddle.net/07qv283u/3/ 

Let me put the undecided flag for now. As a side note: we have plans for releasing typescript defs, so probably we could avoid that kind of issues.

*Internal note:*
@TorsteinHonsi what do you think?

We have checking for `min` (no `max`) here: https://github.com/highcharts/highcharts/blob/9dd35600e08a5732ae95db87715aa8ec24ae9949/js/parts/Axis.js#L2281-L2288 - that prevents from rendering anything when `min` is a string.

**Comment by klodoma** [comment]
Hi all, 

I agree that it's not a bug. I've noticed this because axis.max as string is working well and axis.min doesn't . So, at least that is a inconsistency for the behavior of min and max values(as I see it). 

I think it would be a great help to support string as "number", but that is up to you to decide.
