### ISSUE TITLE
How to take advantage of pointInterval / pointIntervalUnit in a non single data point serie?

### ISSUE THREAD

**Issue by ssoorriiin** [highcharts/highcharts#7595]
Not sure if this is an issue, but documentation does not mention anything about using these properties in non single data point serie(s).
This works fine in single data point serie(s), as @TorsteinHonsi demonstrates it [here](http://jsfiddle.net/highcharts/krourcnt/1/).

#### Expected behaviour
By setting `pointInterval : 1` and `pointIntervalUnit: "month"`, I expect `axis.tickInterval` to always be 1 month (in milliseconds) and axis labels display month and year according to default date time label format.

#### Actual behaviour
Displays year for given  data, and displays month and year if you zoom or if chart container is wide enough.

#### Live demo with steps to reproduce

https://jsfiddle.net/sorinar/8zcnd3yk/

#### Affected browser(s)
Chrome 63.0.3239.84 at least

**Comment by raulovidiu** [comment]
+1

**Comment by pawelfus** [comment]
Hi @ssoorriiin 

Thank you for reporting the issue. Correct me if I'm wrong, but by "non single data point series" you mean, that data points are just numbers, not array/object configs? In that case it's explained under [`SeriesType.data`](https://api.highcharts.com/highcharts/series.line.data).

Maybe we should add there a link to this URL? What do you think?

**Comment by ssoorriiin** [comment]
Hi @pawelfus ,

I was thinking about the second way of providing data, an array of arrays with 2 values.

Under [`SeriesType.data`](https://api.highcharts.com/highcharts/series.line.data) I already see a link demoing [`Arrays of datetime x and y`](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series/data-array-of-arrays-datetime/). So I would like to see the same thing using `pointInterval` / `pointIntervalUnit`  set to 1 day/month/year maybe. As a user, I want to be in control of what the intervals on X axis look like.

Thank you!

**Comment by pawelfus** [comment]
Thank you for the explanation. `pointInterval`/`pointIntervalUnit` are applied if `x` values are not provided: 

> An array of numerical values. In this case, the numerical values will be interpreted as y options. The x values will be automatically calculated, either starting at 0 and incremented by 1, or from pointStart and pointInterval given in the series options. If the axis has categories, these will be used. Example:
`data: [0, 5, 3, 5]`

Regarding:
> As a user, I want to be in control of what the intervals on X axis look like.

To control xAxis interval, you need to use xAxis options, not series options. You have options like [`tickInterval`](https://api.highcharts.com/highcharts/xAxis.tickInterval), [`tickPositioner`](https://api.highcharts.com/highcharts/xAxis.tickPositioner), [`tickPositions`](https://api.highcharts.com/highcharts/xAxis.tickPositions), [`units`](https://api.highcharts.com/highcharts/xAxis.units), [`tickAmount`](https://api.highcharts.com/highcharts/xAxis.tickAmount) and [`minTickInterval`](https://api.highcharts.com/highcharts/xAxis.minTickInterval). I think `xAxis.units` is what you are looking for.
