### ISSUE TITLE
how-to-create-custom-highcharts-files is outdated

### ISSUE THREAD

**Issue by Pyppe** [highcharts/highcharts#7598]
The documentation of https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files seems to be out-dated. The page mentions `./highcharts/assembler/build.js` which no longer exists.

What is the current way of creating custom builds?

**Comment by pawelfus** [comment]
Hi @Pyppe 

Thank you for reporting this issue! `assembler` part was moved into a separate repo: https://github.com/highcharts/highcharts-assembler

@jon-a-nygaard could you fix our docs?

**Comment by jon-a-nygaard** [comment]
Hi @Pyppe, thanks again for letting us know about this.

I have now updated the article [How to create custom Highcharts files](https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files). 
The documentation can also be found in the `highcharts-assembler` repository's [readme](https://github.com/highcharts/highcharts-assembler/blob/master/README.md).

Please let us know if there should be anything else.
