### ISSUE TITLE
Updating x axis with an empty set of options resets extremes

### ISSUE THREAD

**Issue by nmykhailova** [highcharts/highcharts#7599]
#### Expected behaviour
X axis extremes stay the same when update method is called with an empty set of options.

#### Actual behaviour
X axis extremes are reset when update method is called with an empty set of options.

#### Live demo with steps to reproduce
Please, check the following jsfiddle https://jsfiddle.net/3krngsyv/8/ . The line 19 sets the initial extremes, therefore the 3rd point for 2017-10-12 is not displayed. However, if you uncomment the line 34 with an empty update, the previously set extremes are  cleared and all 3 points are visible. Resetting the initial extremes does not help either (try to uncomment the line 35).

#### Affected browser(s)
At least Mozilla Firefox and Google Chrome.

**Comment by pawelfus** [comment]
Hi @nmykhailova 

Thank you for reporting your issue. Your jsFiddle is dead - could you check this? 
![screen shot 2018-01-02 at 12 01 32](https://user-images.githubusercontent.com/1453926/34481843-a609d9ac-efb4-11e7-8b19-d8b0f4cdc7bb.png)

It looks like jsFiddle has problems, could use another online tool to recreate issue? Thanks!

**Comment by nmykhailova** [comment]
Hi @pawelfus ,

jsFiddle tool is up again, it should be possible to see the reproduction scenario.

Best regards,
nmykhailova

**Comment by pawelfus** [comment]
@nmykhailova - thanks for the info! Just checked, it's caused by [`minRange`](https://api.highcharts.com/highcharts/xAxis.minRange) which doesn't allow zooming below 5 days in your case. Setting `minRange` to 1, resolves the issue: https://jsfiddle.net/3krngsyv/9/ - could you confirm?

**Comment by sebastianbochan** [comment]
Closed due to inactivity. Please reopen if any additional information will be available.
