### ISSUE TITLE
chart.update with a drilldown doesn't work

### ISSUE THREAD

**Issue by Munksgaard** [highcharts/highcharts#7600]
#### Expected behaviour

Using chart.update to update the data series and a corresponding change to the drilldown data should work.

#### Actual behaviour

It doesn't

#### Live demo with steps to reproduce

Here's an example: http://jsfiddle.net/f6fydL8p/1/

Note that the two data sets (before and after) are pretty much the same, but after clicking the update button which updates the `series` and `drilldown`, trying to drill down into one of the columns doesn't actually work.

#### Affected browser(s)

Firefox and chrome

**Comment by pawelfus** [comment]
Hi @Munksgaard 

Thank you for reporting this bug. It looks like `chart.options.drilldown` and `chart.userOptions.drilldown` are not updated which causes this. Possible workaround is to overwrite these options manually, instead of using `chart.update()` method, demo: http://jsfiddle.net/f6fydL8p/4/

**Comment by bdevika** [comment]
it is not working for me it throws **TypeError: Cannot read property 'turboThreshold' of undefined**

**Comment by sebastianbochan** [comment]
Hi @bdevika,
Thank you for reporting, but when I run the demos from the thread, all works properly. Could you update one of them with your code? It will allow us to debug.

**Comment by bdevika** [comment]
Hi @sebastianbochan  Here is the sample https://stackblitz.com/edit/react-4ippjp?file=DrillChart.js

step to reproduce:
1. click any category 
2. click Update Chart button

**Comment by pawelfus** [comment]
Hi @bdevika 

Thanks for the demo, but could you recreate issue **without** react-jsx-highchart? This is not our wrapper, and from it's github issues, it looks like `drilldown` is not supported, only available by some workaround (which may cause this issue). Thanks once again!

**Comment by bdevika** [comment]
Hi, Sorry for the delayed reply , Yes you are right @pawelfus  **react-jsx-highchart** wrapper not supporting drill down feature.
