### ISSUE TITLE
drillUp throws an error when a chart is not drilled into

### ISSUE THREAD

**Issue by Munksgaard** [highcharts/highcharts#7602]
#### Expected behaviour

Calling `chart.drillUp` should do nothing when the chart hasn't been drilled into. The documentation at https://api.highcharts.com/class-reference/Highcharts.Chart.html#.drillUp doesn't require that the chart has been drilled down in.

#### Actual behaviour

The following error is thrown (in Chrome):

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at a.Chart.q.drillUp (VM440 drilldown.js:15)
    at HTMLButtonElement.<anonymous> ((index):139)
    at HTMLButtonElement.dispatch (VM437 jquery-3.1.1.min.js:3)
    at HTMLButtonElement.q.handle (VM437 jquery-3.1.1.min.js:3)
```

#### Live demo with steps to reproduce

http://jsfiddle.net/f6fydL8p/3/

#### Affected browser(s)

Firefox and Chrome

**Comment by pawelfus** [comment]
Hi @Munksgaard 

Thank you for reporting this issue.

*Internal note:*
@jon-a-nygaard - should we fix this in the core or add an explanation to the docs?

**Comment by TorsteinHonsi** [comment]
It's a bug, we should fix this in the drilldown module. It should be easy to check if we're already on the top level.
