### ISSUE TITLE
(.Net wrapper) Formatter string does not convert to function

### ISSUE THREAD

**Issue by GertVen** [highcharts/highcharts#7606]
#### Expected behaviour
Pie chart renders correctly with percentages shown inside the segments

#### Actual behaviour
Pie chart does not render at all

#### Live demo with steps to reproduce
With error: http://jsfiddle.net/33ynsk69/
Fixed: http://jsfiddle.net/33ynsk69/1/

Look at "plotOptions" -> "pie" -> "data labels" for the differences

#### Affected browser(s)
All

#### Additional information
All code generated via the official .Net wrapper via the following code (VB.NET):

            Dim sFormatter As String = "function() { return Math.round(this.percentage*100)/100 + ' %'; }"
            fChart.PlotOptions.Pie.DataLabels.Enabled = True
            fChart.PlotOptions.Pie.DataLabels.Distance = -30
            fChart.PlotOptions.Pie.DataLabels.Formatter = sFormatter

It would seem the error is caused by the formatter string staying as a string when the Javascript is created instead of being converted to a function, which is what Highcharts is expecting

**Comment by GertVen** [comment]
Additional note: same happens with the pyramid and funnel charts. Will provide fiddles if needed but the code is very similar to that which I posted above

**Comment by pawelfus** [comment]
Hi @GertVen 

Thank you for letting us know about the issue. In wrapper, `Formatter` should be a name of a function, not a function body in a string. For example: http://dotnet.highcharts.com/Highcharts/Demo/Gallery?demo=AreaBasic&theme=default - it applies to all `Formatter`s, not only pie chart.

**Comment by GertVen** [comment]
Hi Pawel

Thank you for the answer, I was not aware the Javascript had to be called via a function. I've adapted my code and it works perfectly. Since the question is answered I will close the issue.
