### ISSUE TITLE
Make Highcharts free.

### ISSUE THREAD

**Issue by stas730** [highcharts/highcharts#7609]
Highcharts is non-free. There are some issues with chess website Lichess. It's better to free Highcharts than replace it.
Update: free means free as in freedom.
You can find more info on GNU website.

**Comment by AAChartModel** [comment]
Ridiculous!!!

**Comment by pawelfus** [comment]
Hi @stas730 

Thanks for your suggestion. Unfortunately, I don't think we should change pricing model for a Lichess website. I suggest to contact with our Sales team regarding licensing: https://shop.highsoft.com/contact
