### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by pdeva** [highcharts/highcharts#7611]
#### Expected behaviour
No exception to be thrown

#### Actual behaviour

```
highcharts.js:198 Uncaught TypeError: Cannot read property 'destroy' of null
    at a.Pointer.drop (highcharts.js:198)
    at HTMLDocument.onDocumentMouseUp (highcharts.js:199)
drop @ highcharts.js:198
onDocumentMouseUp @ highcharts.js:199

```

#### Live demo with steps to reproduce

I am creating the chart in React, with config like:

```
chart: {
  events : {
  selection: function (event) {
    //do something that destroys react component
  }
 }
}
```

Basically when the user selects a range in the chart, the react component destructs and loads a new component with the data for the selected time range.

However, it seems the highcharts chart when destroyed this way, results in a `null` pointer exception

#### Affected browser(s)

All browsers.

Highcharts 6.

**Comment by pawelfus** [comment]
Hi @pdeva 

Thank you for reporting this bug. 

**Standalone demo:**
http://jsfiddle.net/wn1LLLjx/1/
