### ISSUE TITLE
Is the document not updated

### ISSUE THREAD

**Issue by yoonasy** [highcharts/highcharts#7615]
Is the document not updated?

The language is not in effect according to the document

```
Highcharts.stockChart('chart', {
    tooltip: {
            dateTimeLabelFormats: {
                week: "星期从：%A, %b %e, %Y"
            }
    }
})
```
![image](https://user-images.githubusercontent.com/24489180/34604350-5b8e3090-f242-11e7-9d32-b09c0b647f58.png)
Is there something wrong with the way I use it?

**Comment by pawelfus** [comment]
Hi @yoonasy 

This looks like Highstock's `dataGrouping` was used. In that case, please use [`series.dataGrouping.dateTimeLabelFormats`](https://api.highcharts.com/highstock/plotOptions.series.dataGrouping.dateTimeLabelFormats).  Compare:

- `tooltip.dateTimeLabelFormat`: http://jsfiddle.net/qqov18nd/2/
- `series.dataGrouping.dateTimeLabelFormats`: http://jsfiddle.net/qqov18nd/1/

**Comment by yoonasy** [comment]
thank god
grateful

**Comment by yoonasy** [comment]
Thanks again
```
tooltip: {
            xDateFormat: "%Y-%m-%d %A"
        }
```
