### ISSUE TITLE
I can not get the first click event on iOS device!

### ISSUE THREAD

**Issue by AAChartModel** [highcharts/highcharts#7616]
#### Expected behaviour
Get the every click event on iOS device.

#### Actual behaviour
Can not get the first click event on iOS device.

#### Live demo with steps to reproduce

https://code.hcharts.cn/highcharts/Zh5m1w

#### Affected browser(s)
Safari on iPhone. UIWebView on iOS.

**Comment by pawelfus** [comment]
Hi @AAChartModel 

Thank you for reporting the issue. It looks like a duplicate of #6817 - could you try the workaround posted there?

**Comment by sebastianbochan** [comment]
Closed due to inactivity. Please reopen if new details will appear.
