### ISSUE TITLE
Master pawelfus  Please help me

### ISSUE THREAD

**Issue by yoonasy** [highcharts/highcharts#7618]
#### Expected behaviour
 @pawelfus 
Excuse me, I think every time I click li to change the data, the following selection can be at the end, is there a way
![image](https://user-images.githubusercontent.com/24489180/34618657-67ee3d7a-f27a-11e7-823f-33370f302293.png)

#### Live demo with steps to reproduce
codeLink: https://jsfiddle.net/k50dsb40/

**Comment by pawelfus** [comment]
Hi @yoonasy 

Thank you for your kind words! :) Please, keep in mind that we use github as bug reports, for questions, please contact with our support: https://www.highcharts.com/support

And to answer your question, I think you want to use [`xAxis.setExtremes(min, max)`](https://api.highcharts.com/class-reference/Highcharts.Axis.html#setExtremes).

**Comment by yoonasy** [comment]
Thank you very much~
