### ISSUE TITLE
Hierarchical sunburst tooltip

### ISSUE THREAD

**Issue by GertVen** [highcharts/highcharts#7622]
I'm using the Highcharts Sunburst demo (https://www.highcharts.com/demo/sunburst) as an example.

Is it possible for the tooltip to adapt in order to show the entire hierarchy for the node where the user hovers? For example:

-> If the user hovers over "Asia", the tooltip will show: "Asia: 4 503 248 822" as it's a level one element
-> If the user hovers over "China" the tooltip shows: "Asia - Eastern Asia - China: 1 409 517 397" as it's a level three element

Thanks!

**Comment by KacperMadej** [comment]
Hi @GertVen 

This is not a bug and we are trying to keep bugfix for bugs. In the future please use any other support channel for cases that are not a bug report. https://www.highcharts.com/support

The tooltip text can be changed like in the below linked demo:
http://jsfiddle.net/BlackLabel/z9ozkz5w/1/
