### ISSUE TITLE
Point Highlight in HighStock

### ISSUE THREAD

**Issue by whooguyy** [highcharts/highcharts#7624]
#### Expected behaviour
Selecting a point in highstock keeps the point highlighted. It stays highlighted either until the range is changed or the points are no longer grouped.

#### Actual behaviour
When using Highstock, if a point is selected it does not remain highlighted. I can retrieve and view the data of that point just fine, but after I click and accidently move my mouse I have no idea which point was selected.

#### Live demo with steps to reproduce
Highstock Example of point selection on, and points will temporarily be highlighted.
https://jsfiddle.net/rhavelka/w2k9Le5r/1/

Highcharts example where point selection is on and points stay highlighted.
https://jsfiddle.net/rhavelka/82uq8htx/

Also note that in the Highcharts example, using ctrl will select multiple points

**Comment by KacperMadej** [comment]
Hi @whooguyy 

The difference comes from disabled markers by default in Highstock.
Enable them and selection works: https://jsfiddle.net/BlackLabel/w2k9Le5r/2/

This doesn't look like a bug. Is there something more to add to this case? or could it be closed?

**Comment by whooguyy** [comment]
Thank you @KacperMadej, your fix solves my issue. This can be closed.
