### ISSUE TITLE
hidden series data disappearing after changing the series marker enabled state

### ISSUE THREAD

**Issue by nimishjain79** [highcharts/highcharts#7627]
#### Expected behaviour
by toggling the series marker enabled state, series data must not disappear

#### Actual behaviour
by toggling the series marker enabled state, series data is disappearing

#### Live demo with steps to reproduce
https://jsfiddle.net/1t7eu60t/

1. hide series 2 by clicking on legend item
2. uncheck 'Toggle Marker' checkbox
3. inspect chart.series[1].data[] in console, data has disappeared

#### Affected browser(s)
Chrome Version 63.0.3239.84 (Official Build) (32-bit)
Not tested on other browsers

**Comment by pawelfus** [comment]
Hi @nimishjain79 

Thank you for reporting this issue. If series is hidden, we don't generate points and if you call `series.update()` all points will be destroyed. If you want to, you can force "rendering" a series  (even if hidden) using `series.redraw()`, demo: https://jsfiddle.net/1t7eu60t/1/

*Internal note:*
We have this limitation set here:

https://github.com/highcharts/highcharts/blob/c2bfb0e210183749a48b0c48b6182b2b5143dceb/js/parts/Chart.js#L481-L483

**Comment by nimishjain79** [comment]
Hi Pawel,

Thanks for the clarification. Where can I find such information on
api.highcharts.com?

Actually after hiding the series and updating the marker for it, I was
trying to get the selected value of particular point for the hidden series
and I was getting the error of null object. I now understood why it was
happening.

If this is the expected behavior, then please mark the issue as not bug and
close it. Thank you.

Regards,
Nimish Jain

**Comment by pawelfus** [comment]
Hi @nimishjain79 

Let's keep this issue open, because our docs: https://api.highcharts.com/class-reference/Highcharts.Series#.data don't metion about this case. 

*Internal note:*
I think this should be fixed in the core, not in the docs, but it can (and will in Highstock) decrease performance for a big datasets and hidden series. Any thoughts @TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
> Any thoughts @TorsteinHonsi ?

I don't think we should change the current behaviour - this is an optimization we have done for speed and memory usage. I'll update the docs.

@nimishjain79 You can access `series.options.data` for the raw values.
