### ISSUE TITLE
Drilldown total and graph calculation are wrong on first stack

### ISSUE THREAD

**Issue by mjgruta** [highcharts/highcharts#7628]
#### Expected behaviour (except the style)
using version 4.2.2, calculation is OK see below.
http://jsfiddle.net/o598q1j0/

#### Actual behaviour
Using version 6.0.4 causes wrong total calculation and graph for the first stack but when I click the drilldown and go back, the calculation becomes OK.
http://jsfiddle.net/sy9y11qp/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @mjgruta 

Thank you for reporting this issue.

**Workaround:**
It works fine if we set name for the last point: http://jsfiddle.net/o598q1j0/1/ or if we set [`xAxis.uniquesNames`](https://api.highcharts.com/highcharts/xAxis.uniqueNames) to false: http://jsfiddle.net/o598q1j0/2/

*Internal note:*
It's probably a regression after f58282cc39b3c72ec0faf51e45ce208e3c804102

**Comment by mjgruta** [comment]
Thanks! I did not see that :)
it was supposed to be year 2014 but had issue on generating the years. I fixed it on my php and it is now working fine.
