### ISSUE TITLE
Points outside extremes are visible when boost.js is used

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7631]
#### Expected behaviour
Points that are outside yAxis extremes should not be visible. 

Example without boost.js:
http://jsfiddle.net/vd1y2cjx/4/

#### Actual behaviour
Points are visible even when they are outside the axis extremes. Also, the tooltip is not working for this points.

#### Live demo 
http://jsfiddle.net/vd1y2cjx/5/

**Comment by pawelfus** [comment]
Fixed since v7.1, demo: http://jsfiddle.net/BlackLabel/6yf0rnpv/1/
