### ISSUE TITLE
Style CSP error when using options.legend.useHTML=true (style-src 'self')

### ISSUE THREAD

**Issue by codemasterover9000** [highcharts/highcharts#7633]
We are using styled mode but when using a custom HTML based legend item. We still get CSP errors caused by the the highcharts library. 

This is caused at highcharts.src.js:6585 (version 6.0.4) in the SVGRenderer.html() method at the following code `wrapper.css({position: 'absolute'})`.

Using `wrapper.style.position = 'absolute'` instead of  would probably fix the problem.

**Comment by KacperMadej** [comment]
Hi @codemasterover9000 

Thank you for reporting about the problem.
Please post a JSFiddle demo of the problem, so we could double check that not only a problem is resolved but also your problem will be solved.

**Comment by codemasterover9000** [comment]
We use this configuration: http://jsfiddle.net/g9yj6aqh/
The legend with useHTML seems to cause the problem. setting useHTML to false causes the CSP error to disappear.

**Comment by sebastianbochan** [comment]
Hi @codemasterover9000 
When I run the demo: http://jsfiddle.net/3qe6v2y9/ (styled mode) I always have inline styles (with or withoout useHTML). Could you confirm that I have the right scenario?

**Comment by codemasterover9000** [comment]
I found a solution by modifying the follwing code in SvgRenderer.js [here](https://github.com/highcharts/highcharts/blob/10e70a55871f0d473f8250ea5c730b98c71b8cc9/js/parts/SvgRenderer.js#L821)  to the following:

```
                    if (isMS && !svg) {
                        css(this.element, styles);
                    } else {
                        hyphenate = function(a, b) {
                            return '-' + b.toLowerCase();
                        };
                        var resultStyles = {};
                        objectEach(styles, function(style, n) {
                            if (inArray(n, svgPseudoProps) === -1) {
                                resultStyles[n.replace(/([A-Z])/g, hyphenate)] = style;
                            }
                        });
                        css(elem, resultStyles);
                    }
```

**Comment by codemasterover9000** [comment]
When I remove useHTML for the legend I dont get CSP errors originating from highcharts when I run your fiddle. When I set useHTML to true I get multiple CSP errors originating from Legend.renderItem(). Using the code in my previous comment fixes this issue.

The real point of this issue imo is that the library should never set the style attribute directly (unsafe-line) in any case. But modify its properties directly (which in theory would also perform better). 

In our case this would have saved us a lot of time as we are implementing a CSP where unsafe-inline is not allowed. Now we need to switch al our code to styled mode. Which is a better way to style but not the thing we wanted to spend our resources on atm ;)

**Comment by KacperMadej** [comment]
@codemasterover9000 Styled mode shouldn't generate inline CSS - if it does, please post a simple demo for it. Classic mode doesn't have this restriction, so please make sure that you are using correct code version for your requirements.

**Comment by codemasterover9000** [comment]
Fiddle: http://jsfiddle.net/g9yj6aqh/1/ same code as the one I posted before but with the styled mode js/css files (Just saw I added the classic mode js in the previous fiddle). 

I also gave you a code pointer where you can clearly see the style attribute being set. This code should not even exist in the styled mode js files according to your comment. Maybe take some time to look at the comment/source next time. I am also spending my time to help you fix this...

**Comment by KacperMadej** [comment]
Thank you for your help, time and the live demo.

Currently there's no way around this because style is used to position elements. 

*Internal note:* inline CSS for styled mode extending issue https://github.com/highcharts/highcharts/issues/6173

**Comment by codemasterover9000** [comment]
Yes thats why I proposed a fix where style attributes are set in a secure way 5 days ago. This at least fixes this case (and probably others).

**Comment by pawelfus** [comment]
@TorsteinHonsi

**Comment by codemasterover9000** [comment]
Not sure if I should open a new issue but I found a similar issue in exporting.src.js [here ](https://github.com/highcharts/highcharts/blob/master/js/modules/exporting.src.js#L1674)

**Comment by TorsteinHonsi** [comment]
I think the real purpose of the snippet above is to handle styles separately for SVG elements and HTML elements. Will the following version resolve your case?

```js
			// serialize and set style attribute
			if (elem.namespaceURI === this.SVG_NS) {
				hyphenate = function (a, b) {
					return '-' + b.toLowerCase();
				};
				objectEach(styles, function (style, n) {
					if (inArray(n, svgPseudoProps) === -1) {
						serializedCss +=
						n.replace(/([A-Z])/g, hyphenate) + ':' +
						style + ';';
					}
				});
				if (serializedCss) {
					attr(elem, 'style', serializedCss); // #1881
				}
			} else {
				css(elem, styles);
			}
```

**Comment by codemasterover9000** [comment]
@TorsteinHonsi Yes the above code resolves the issue.
