### ISSUE TITLE
HighStock Flags Boost Module erroring out 'cannot read property length of undefined'

### ISSUE THREAD

**Issue by drichard1989** [highcharts/highcharts#7634]
#### Expected behaviour
Wanting to use highstock with the boost module on a line chart with multiple series and flags. 

#### Actual behaviour
When we try to incorporate the boost module, we keep getting an error that states 'cannot read property length of undefined.' 

Disabling the boost module allows us to render the chart, but the chart becomes slow with the navigator handles and large data sets. Removing flags allows us to render the chart, but we need those. 

The error seems to start occurring when the points number is greater than the boostThreshold. 

I guess our question is, can you use the boost module with flags on a line chart in highstock with a high number of series? We have included the fiddle below that is a broken fiddle for your use. 

#### Live demo with steps to reproduce

http://jsfiddle.net/gerdsen/bLvr7dz5/4/ 

#### Affected browser(s)
All. 
Version 6.0.1

**Comment by Izothep** [comment]
Thank you for reporting the issue! 

The same problem is visible when multiple lines are combined with pie chart: 
http://jsfiddle.net/ntjgu67n/3/

**Comment by TorsteinHonsi** [comment]
#### Minimal demo
http://jsfiddle.net/highcharts/ntjgu67n/4/

**Comment by zombiehugs** [comment]
@TorsteinHonsi we most definitely appreciate the quick turnaround!
