### ISSUE TITLE
Variwide labels overlap when column too small

### ISSUE THREAD

**Issue by d2a-raudenaerde** [highcharts/highcharts#7635]
#### Expected behaviour
I'd expect the labels that overlap to be left out or repositioned so that I can actually read them when the variwide columns get small.

#### Actual behaviour
The labels overlap.
As workaround I can set the rotation of the label to -90, but still when the columns are too small they will start overlapping.

#### Live demo with steps to reproduce
http://jsfiddle.net/mgqk836o/

![image](https://user-images.githubusercontent.com/5213150/34762419-017a201a-f5e8-11e7-83f8-fb37bf8ab6b9.png)

#### Affected browser(s)
All.

**Comment by KacperMadej** [comment]
Hi @d2a-raudenaerde 

Thank you for reporting.

Axis labels are calculated as if the categories were of equal width.
Demo: http://jsfiddle.net/BlackLabel/mgqk836o/2/
Steps: resize the chart and observe xAxis labels

**Comment by dosaki** [comment]
Hi,

Is there any prediction for when a fix will be available? Or a work-around?

**Comment by KacperMadej** [comment]
As an attempt for a workaround: here's a simple wrapper that changes how the widths are calculated - http://jsfiddle.net/BlackLabel/mgqk836o/3/

**Comment by dosaki** [comment]
@KacperMadej My `series.relZ` is undefined for some reason.
If I do `relZ = series.relZ || [],` however, it makes my x-axis labels go even more overlapped:
![image](https://user-images.githubusercontent.com/1957450/37168257-2dbd3c34-22fc-11e8-9ee0-79798b504d61.png)

My bars are all the same width though.

**Comment by KacperMadej** [comment]
@dosaki 
Please post a live demo in JSFiddle, because based on you screen shoots it looks like you are doing something strange in the chart options. The variwide series type was introduced in Highcharts version 6.

**Comment by dosaki** [comment]
@KacperMadej Please have a look here: http://jsfiddle.net/mgqk836o/19/
I'm getting this problem not with the variwide charts but with a regular column chart.

The way it breaks is when I turn `xAxis.labels.useHTML = true`.

**Comment by TorsteinHonsi** [comment]
Hi @dosaki, this is a known regression. It worked in [v6.0.4](http://jsfiddle.net/highcharts/mgqk836o/21/), was broken in [v6.0.5](http://jsfiddle.net/highcharts/mgqk836o/23/) and is [fixed in the master](http://jsfiddle.net/highcharts/mgqk836o/26/).

**Comment by dosaki** [comment]
@TorsteinHonsi I've applied your commit that fixes the issue manually and things started working!

Thanks :+1:
