### ISSUE TITLE
Line plot (styled mode) tooltip does not take plotOptions.line.negativeColor into account.

### ISSUE THREAD

**Issue by codemasterover9000** [highcharts/highcharts#7638]
Using highcharts 6.0.4. When showing the tooltip over a negative part of the line. The used class is highcharts-color-0 instead of highcharts-negative.

`<tspan class="highcharts-color-0" x="8" dy="15">●</tspan>`

This does work correctly in classic mode.

Example: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/css/series-negative-color/

**Comment by TorsteinHonsi** [comment]
Classic mode works because `point.color` is set to `series.negativeColor`. In order for this to work the same way we probably need to add a new option, `negativeColorIndex`.

**Comment by alobakov** [comment]
That's what I was going to propose - negativeColorIndex would be the most natural solution.
