### ISSUE TITLE
Zooming issue in scatter chart

### ISSUE THREAD

**Issue by BarunSriwastawa** [highcharts/highcharts#7639]
Selected points should be visible on charts.

in given example on jsfiddle 
1-I select area only cover two points on very right on chart point 1 (x:197.1, y:90.9) and point 2 (x:198.1, y:85.5). in first selection chart zoomed and both points are visible. 
2- Again i select area on chart covers both points only. now points are invisible. also y axis values shows 83.6 only.

please refer below link for replicate.
http://jsfiddle.net/b6pry9qw/5/

#### Affected browser(s)
chrome, firefox.

**Comment by BarunSriwastawa** [comment]
Refer below screenshots for above issues
![2](https://user-images.githubusercontent.com/25636102/34772929-dd50d290-f62f-11e7-96cd-e25e1c21afc6.png)
![3](https://user-images.githubusercontent.com/25636102/34772930-dd83c43e-f62f-11e7-9a3a-1aba4f9bf638.png)
![1](https://user-images.githubusercontent.com/25636102/34772931-ddb1a19c-f62f-11e7-926f-b1ffdc4e85cf.png)

**Comment by KacperMadej** [comment]
Thank you for reporting about the problem.

_Internal note:_ [the solution](https://github.com/highcharts/highcharts/issues/4185#issuecomment-143241869) with pointRange from #4185 doesn't help for the edge of axis case

**Comment by BarunSriwastawa** [comment]
Hi Team,

Is there any update on this issue. When it will be fixed?

**Comment by KacperMadej** [comment]
Hi,

We do not have ETA for the fix for now.

**Comment by TorsteinHonsi** [comment]
Looking into this now.

**Comment by TorsteinHonsi** [comment]
The original demo with the fix applied: http://jsfiddle.net/b6pry9qw/31/
