### ISSUE TITLE
Bullet graph does not work

### ISSUE THREAD

**Issue by Tauka** [highcharts/highcharts#7640]
#### Expected behaviour
Bullet graph rendering normally

#### Actual behaviour
Gives "Highchart Error 17", which is unrecognized chart type

#### Live demo with steps to reproduce
I have copied and pasted demo from Highcharts official website

https://jsfiddle.net/highcharts/llexl/

#### Affected browser(s)
Google Chrome 
Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @Tauka 
When I run the demo: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/bullet-graph/ bullet chart is displayed properly. 

Your demo is regular column chart only.

Could you point me out, that my demo works well for you too ?

**Comment by Tauka** [comment]
Thank you @sebastianbochan,

I'm sorry for false alarm, I was not aware of the fact that you also need to include bullet as a module.  And I also forgot to save my fiddle =) Your fiddle works fine for me. Well, I guess we can close on that

**Comment by sebastianbochan** [comment]
Thank for the feedback.
