### ISSUE TITLE
Flag tooltips do not react to hover when Boost Enabled

### ISSUE THREAD

**Issue by zombiehugs** [highcharts/highcharts#7646]
#### Expected behaviour
As a user I should be able to hover over flags on series and off series to see more information.

#### Actual behaviour
When enabling Boost Module flags now appear on series and off series but can no longer hover over the flags for additional information. The cursor scrubs right over them.

#### Live demo with steps to reproduce
Run Fiddle, attempt to hover over flag.
No Hover allowed.
Hide line series and attempt to hover over flag on axis.
Flag is now responding to hover.

Minimal Fiddle: http://jsfiddle.net/gerdsen/ntjgu67n/8/

#### Product version
HighStock Master JS (1/10/2018)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @zombiehugs 

Thank you for reporting.

**Comment by TorsteinHonsi** [comment]
Strange... At least, `boost.seriesThreshold` has something to do with it. When removed, the tooltip performs as expected: http://jsfiddle.net/highcharts/ntjgu67n/9/

**Comment by drichard1989** [comment]
We have noticed that as well. But, since we are dealing with alot of data points on each series, the chart performs much better with the boostModule turned on. Any idea on a timeline for a fix on this?

**Comment by zombiehugs** [comment]
@TorsteinHonsi thanks for inspecting. So I see your fiddle is working, we tried the same within our application with little to no success. What does appear to be linked to the problem is the number of points and or series present, when we render out a small time period of say 7 days the flags work. If we tried to render a larger dataset the flags appear but cannot be hovered. This was done utilizing simple configuration and no seriesThreshold.

I updated your Fiddle from above and augmented the number or series and points within the series to show one working and one not.

Fiddle (working, 5 line series, 1 flag series): http://jsfiddle.net/gerdsen/ntjgu67n/10/
Fiddle (NOT working, 6 line series, 1 flag series): http://jsfiddle.net/gerdsen/ntjgu67n/11/

Thanks for all of  your assistance.

**Comment by drichard1989** [comment]
@TorsteinHonsi we appreciate you looking into this issue. Is there an estimated time that this issue will be resolved?

**Comment by drichard1989** [comment]
@TorsteinHonsi Good morning. I wanted to follow up to see if there is an estimated time that this issue will be resolved. We have a customer that is depending on this fix for us to roll out the next patch, so we are just trying to gain some information on this timeline. We are an OEM License Holder as well. Thank you in advance.

**Comment by pawelfus** [comment]
**Workaround:**

Set on chart's load/redraw stickyTracking flag: http://jsfiddle.net/BlackLabel/ntjgu67n/14/

```
function resetTracking() {
  Highcharts.each(this.series, function(series) {
    if (Highcharts.noop === series.buildKDTree) {
      series.stickyTracking = false;
    }
  })
}

Highcharts.chart('container', {

  chart: {
    events: {
      load: resetTracking,
      redraw: resetTracking
    }
  },
  ...
});
```

**Comment by zombiehugs** [comment]
@pawelfus this seems to do the trick and we can run with this. Looking forward to seeing it in the next release! Thanks to you and the HighCharts team for the solid support.

**Comment by drichard1989** [comment]
@pawelfus Thank you very much! The support here has been awesome.
