### ISSUE TITLE
why indicator bollingerbands isn't show in area chart

### ISSUE THREAD

**Issue by eakkasit** [highcharts/highcharts#7648]
#### Expected behaviour
How to set data for area chart to showing bollinger bands? @pawelfus 
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/stock/indicators/bollinger-bands/

#### Actual behaviour
![11-01-61 11-15-51](https://user-images.githubusercontent.com/7508045/34808336-dc61a68e-f6c0-11e7-95bb-320b6ee9e1ca.png)

**Comment by sebastianbochan** [comment]
Hi @eakkasit 
The Bollinger bands algorithm is based on low / open values of a point, so you need to use OHLC instead of area which has only y value.

**Comment by pawelfus** [comment]
I agree, it's a bug that we expect always array for Bollinger bands.
