### ISSUE TITLE
Hovered points outside plotting area

### ISSUE THREAD

**Issue by MichaelMayrhofer** [highcharts/highcharts#7650]
#### Expected behaviour
Points which are outside the plotting area should not be visible/hovered.

#### Actual behaviour
See the attached screenshot:
![image](https://user-images.githubusercontent.com/33220176/34814885-97c480a2-f6af-11e7-894b-ac79e9ead6ef.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/efujfuat/1/
1. Move the mouse cursor to point {Series 1, x: 2, y: 3} 
-> point {Series 2, x: 2, y: 1} will be visible outside the plotting area.

Removing the chart setting `{ tooltip: {shared: true} }` fixes the problem. But I need this shared tooltip.

Similar issue: #3916

#### Product version
Highcharts: latest version

#### Affected browser(s)
Chrome v63

**Comment by pawelfus** [comment]
Hi @MichaelMayrhofer 

Thank you for reporting this bug. It's a regression since v5.0.13:

- v5.0.12: http://jsfiddle.net/efujfuat/2/
- v5.0.13(broken): http://jsfiddle.net/efujfuat/3/

*Internal note:*
Regression after commit: 152e7e57018daeeacf08056c5bf5733ad0bf50fd @jon-a-nygaard
