### ISSUE TITLE
Series custom className not applied on tooltip item (styled mode)

### ISSUE THREAD

**Issue by codemasterover9000** [highcharts/highcharts#7651]
jsfiddle: http://jsfiddle.net/kj8aL1q3/

In the jsfiddle the 'Other' series has a custom class 'customSeriesColor'. This class is not assigned in the tooltip item for that series. This does work correctly for the legend for example.

**Comment by pawelfus** [comment]
Hi @codemasterover9000 

Thank you for reporting this issue. Could explain what do you mean by tooltip item? The circle in the tooltip is not a marker, like in legend, it's only a color indicator.

**Comment by codemasterover9000** [comment]
Hi,

I want the 'Other' series to take on another color/style through the custom class 'customSeriesColor' as applied to the series through the className property. What I expect is that I can style the graph line/markers/legend and tooltip through this classname. This is not possible for the tooltip as the class 'customSeriesColor' is not applied to the tooltip section.

Basically what I want is the same as the other series in the jsfiddle that dont have a custom class assigned. Where the marker/tooltip/legend/graph-line have the same color/styling but now defined through the customSeriesColor class. This is not possible now since the tooltip section always only has highcharts-color-# class assigned.

**Comment by TorsteinHonsi** [comment]
Currently you need to include the option in the `tooltip.pointFormat`: http://jsfiddle.net/highcharts/kj8aL1q3/1/

**Comment by codemasterover9000** [comment]
Thanks, your solution works. Maybe make that the default tooltip format?
