### ISSUE TITLE
Incorrect font-family definitions in SVGRenderer.getStyle()

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#7653]
#### Actual behaviour

Fonts (Lucida Grande, Lucida Sans Unicode) added to style through _extend()_ function shouldn't be wrapped by quotation marks, because it causes a problems when using getSVGForExport() and sending that SVG element to export server by encoded URI. Those quotation marks are transformed to **&quot;** expressions and their ampersands makes new keys in Form Data.

#### Expected behaviour

Quotation marks are unnecessary in this case

    getStyle: function(style) {
        this.style = extend({

            fontFamily: 'Lucida Grande, Lucida Sans Unicode, ' +
                'Arial, Helvetica, sans-serif',
            fontSize: '12px'

        }, style);
        return this.style;
    },

#### Live demo with steps to reproduce
[http://jsfiddle.net/daniel_s/148pa906/](http://jsfiddle.net/daniel_s/148pa906/)
1. Click "Run Code" button to send the SVG to highcharts export server
2. Open console, go to Network tab, and search the POST request to _export.highcharts.com_ and click on to reveal it.
3. Scroll to Form Data and see what happen with _svg:_ value

**Comment by TorsteinHonsi** [comment]
Although it seems like the proposed solution is safe, I think the real issue is that the SVG is not properly escaped. 

It works if we run `escapeURIComponent` on the data only: 

```js
dataString = 'async=true&type=jpeg&width=400&svg=' + encodeURIComponent(svg);
```

[View on jsFiddle](http://jsfiddle.net/highcharts/148pa906/1/).
