### ISSUE TITLE
Boost.js using wrong fillColor for points

### ISSUE THREAD

**Issue by NeuwenWolf** [highcharts/highcharts#7655]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/12142465/34837808-33c5b0da-f6b9-11e7-9d28-4449570e20d2.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/12142465/34837784-1e1f0844-f6b9-11e7-8127-4cc8176e9923.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/pp30eh2y/
Needs marker and boost enabled.
Requires more than 1 series, incorrectly uses fill color from last series for all series
(In my use-case it takes more than 5 series, not sure what the difference is caused by)

#### Product version

Boost.js development build
#### Affected browser(s)
Tested in Chrome only

**Comment by zombiehugs** [comment]
@NeuwenWolf, I can second this. We have noticed the same within our application; when boost is activated the fill color of our markers were the color of the last series on the axis.

**Comment by pawelfus** [comment]
Thank you for reporting this issue!

**Comment by zombiehugs** [comment]
@pawelfus @NeuwenWolf  It should be noted (will probably fix itself when bug is discovered) that when hiding the particular culprit series, the last one, the marker fill color is now the "new" last series's color.

**Comment by cvasseng** [comment]
A fix for this has been pushed to the `bugfix/7655-boost-wrong-marker-color` branch.

Demo of the fix: http://jsfiddle.net/cbx9kz9r/

[Pull request](https://github.com/highcharts/highcharts/pull/7685) has been added, so it will likely be merged into master before the end of the week.

**Comment by cvasseng** [comment]
Fixed in 6.0.5.
