### ISSUE TITLE
xAxis.labels.useHtml suffers major performance hit with useHtml as true

### ISSUE THREAD

**Issue by jmeyerit** [highcharts/highcharts#7656]
#### Expected behaviour

Similar rendering performance using html rendering options versus svg.

#### Actual behaviour

Suffer a large performance hit when rendering with xAxis labels using html rendering.

Use Case: 

Client wants to view customer order data (includes tons hauled information and sale type) for the entire year. This is in bar chart form and can easily surpass 3000 rows. In addition, each row would have information on click/hover of the label in table format if necessary. Since svg doesn't have table rendering, we require useHtml for those labels without rewriting the logic for our hover data.

#### Live demo with steps to reproduce

The attached fiddle showcases the issue.

https://jsfiddle.net/cthchdfw/2/

After going to the fiddle, open your console and run the js file a few times. In my tests, rendering time took between 1.6-2.2 seconds. Now, change the htmlBool to true. Rendering times skyrocket to 9.4-10.0 seconds. This only gets worse as the dataset increases in size. If we change from the default 1000 to 3000 rows, we go from 9.1-10.3 seconds for normal svg render (which is, at least to our client, acceptable) vs 83-85 seconds for html render.

Using the Chrome profiler, I noticed a couple potential issues.

![image](https://user-images.githubusercontent.com/25272921/34850569-5c4f3f40-f6f4-11e7-85f4-07479290b171.png)

1. HtmlUpdateTransform appears to be called multiple times inside and outside the Layout function.
2. Recalculate Style is being called, taking 23% of the rendering time. I suspect that this may be the core of the issue. Using html rendering, the layout is constantly resizing (at least internally), and causing unnecessary updates.

#### Product version

highcharts >= 4.0.0 tested.

#### Affected browser(s)

Chrome only tested.

**Comment by pawelfus** [comment]
Hi @jmeyerit 

Thank you for reporting this performance issue. 

For my machine it's ~1s for SVG and ~4s for HTML. Which is still ~4x slower for HTML.

**Comment by TorsteinHonsi** [comment]
On my machine, in Chrome, it rendered in ~2500ms [before the fix](https://jsfiddle.net/highcharts/cthchdfw/4/).

After the fix, it renders in ~270 ms: https://jsfiddle.net/highcharts/cthchdfw/5/

The fix does mainly two things:
* Avoid applying changes unless necessary. For example, the SVGRenderer's model of deferring element update until all attributes of an `.attr()` call are set, is now also applied to HTML elements.
* Avoid refering to `elem.offsetWidth`. This caused recalculating style as noted in the OP, and chopped off the last 300ms.

**Comment by TorsteinHonsi** [comment]
Thanks, I have a few ideas of how to increase rendering speed significantly in SVG too. 

Before I dive in, are you sure the performance decreased when using SVG, compared to earlier? I can't see any difference in rendering speed before and after, and it doesn't make sense either, since the only change in non-HTML related code was to move some variables around.

@pawelfus did you experience this?

**Comment by jmeyerit** [comment]
I am sorry, I was incredibly ambiguous in my wording choice. What I meant to say was, since the performance improvement you made, html is now faster at rendering than svg. The svg rendering time is still the same and was not affected.

**Comment by TorsteinHonsi** [comment]
That makes sense, thanks!

**Comment by TorsteinHonsi** [comment]
The above commit reduces rendering times with SVG labels from ~700ms to ~350ms on my system. It checks for the length of each label before setting the `width` pseudo-CSS, thereby avoiding the heavier word-wrap logic.
