### ISSUE TITLE
Adding a method to get chart instance from container DOM element (plain js)

### ISSUE THREAD

**Issue by Tauka** [highcharts/highcharts#7660]
#### Expected behaviour
```
Highcharts.chartInstance(document.getElementById("container"))
``` 

or similar to return chart instance

#### Actual behaviour
It's only possible via jquery

`$("#container").highcharts();`

I've searched through api and [stackoverflow](https://stackoverflow.com/questions/13049977/how-can-i-get-access-to-a-highcharts-chart-through-a-dom-container), and it seems only ready-to-use solution requires `jquery`. It would be nice to have similar functionality for plain js, which also would be described in the docs (I also noticed people requesting no-jquery solution at stackoverflow). 

I'd like to open PR, if you consider this functionality viable.

**Comment by zhy1stgg** [comment]
below code may help you
`// create chart
var chart = Highcharts.chart('container', chartOptions);

// get chart object by dom's data-highcharts-chart attribute
var container = document.querySelector('#container'),
    chartIndex = container.getAttribute('data-highcharts-chart'), 
    chart = Highcharts.charts[chartIndex];
    
console.log(chart)`

**Comment by oysteinmoseng** [comment]
You can also use `var chart = Highcharts.find(Highcharts.charts, function (chart) { return chart.renderTo.id === 'containerName'; })`. Example: http://jsfiddle.net/Lo6ya4dk/

**Comment by Tauka** [comment]
Thank you @oysteinmoseng, @zhy1stgg 

I was aware of these methods, that's actually precisely what I did in my project. I just was guided by the fact you provide plugin for jquery, and also expected the same thing for plain js. Generally, I don't think it's a good design to have a jquery plugin, with no jquery dependency. It might have been a good idea a long ago, when jquery had dominance, but now it's seems trend is shifting towards **no-jquery** solutions (React for example). So it might confuse people and force them to install jquery into their project just for that (calling `$(".container").highcharts()` it's way easier than the code you wrote, and for beginner programmers that might seem a good solution). You should not encourage people to use `jquery`.

I would suggest you replace jquery plugin with plain js solution (gradually of course, so it won't break number of projects). But I understand if you don't want to overflow your api with function, which can be implemented with few more lines, but you might consider this, since it's a very common function.

**Comment by oysteinmoseng** [comment]
@Tauka Thank you for your feedback. We have phased out jQuery from our docs and demos, and are encouraging a pattern of `var chart = Highcharts.chart('container', options);` now, but you still make a valid point. @TorsteinHonsi Any thoughts?

**Comment by TorsteinHonsi** [comment]
Yes, we have left the jQuery plugin for the sake of backwards compatibility. It is very lightweight, doesn't do any harm, and removing it would create a lot of trouble for a lot of people.

The intention of the jQuery plugin was mainly to provide a shortcut for the _constructor_ rather than getting the chart instance from a DOM node. 

And to be honest, I think the current approach is quite clean:

```js
var chart = Highcharts.charts[node.getAttribute('data-highcharts-chart')];
```
