### ISSUE TITLE
Incorrect drawing of one label in Variablepie chart

### ISSUE THREAD

**Issue by vitaliy-bykovets** [highcharts/highcharts#7663]
#### Expected behaviour
The label for one pie is drawing incorrect. This happens when data for chart series are placed in the specific order. Please, check Fiddle example.

Maybe, the issue in a data representation.

#### Live demo with steps to reproduce
http://jsfiddle.net/lopilup/4xk4fytn/2/

#### Product version
Highcharts JS v6.0.4 (2017-12-15)
Variable Pie module for Highcharts

#### Affected browser(s)
Chrome, Firefox, IE11, Edge, Safari

**Comment by pawelfus** [comment]
Hi @vitaliy-bykovets 
Thanks for reporting the issue!
