### ISSUE TITLE
Legend is only hiding first and last series, others stay visible on X-axis (bar and column charts)

### ISSUE THREAD

**Issue by ananasij** [highcharts/highcharts#7664]
I'm creating a bar chart where each bar represents a separate series and should be possible to hide/show via legend.

#### Expected behaviour
Click on any legend item. Related series/bar is fully hidden.

#### Actual behaviour
Only first and last visible series are getting fully hidden. For the middle ones  X-axis label remains visible.
Same story for columns.

#### Live demo with steps to reproduce
https://jsfiddle.net/ananasij/2e942js4/
1. Click 'department 1' legend item. It's getting fully hidden. Click 'department 2' legend item. It's also hidden properly.
2. Make all series visible again.
3. Click 'department 2' legend item (make sure 'dep 1' and 'dep 3' are visible).  Bar is hidden from the plot area,  label 'department 2' remains visible at X-axis.

#### Product version
Highcharts, at least ^6.0.3, haven't checked older ones

**Comment by pawelfus** [comment]
Hi @ananasij 

Thank you for reporting the issue. It's a general problem with categorized axes, hidden points don't hide linked categories, except the first/last one, where we can simply change extremes on xAxis.

Not a simple solution, but we can decide what is displayed on a chart using [`series.events.legendItemClick`](https://api.highcharts.com/highcharts/plotOptions.series.events.legendItemClick) callback: https://jsfiddle.net/2e942js4/1/

**Comment by ananasij** [comment]
Hi @pawelfus 

Thanks for this workaround, it helped a lot!
