### ISSUE TITLE
googleSpreadsheetKey did not work for Spider Chart 

### ISSUE THREAD

**Issue by powerguo** [highcharts/highcharts#7668]
#### Expected behaviour
googleSpreadsheetKey gets the value from a public google spreadsheet using the spreadsheet key.

#### Actual behaviour
The data is not grabbed from google spreadsheet. 

#### Live demo with steps to reproduce

Using the Highcharts demo of the spider chart, I changed the data value from existing hardcoded value to a google spreadsheet: https://docs.google.com/spreadsheets/d/1QwJuLpRWeXTTZ3k0zaUeCncHY1sRu6FxBnmlgsPw9pE/edit#gid=0

I extracted the googleSpreadsheetKey as 1QwJuLpRWeXTTZ3k0zaUeCncHY1sRu6FxBnmlgsPw9pE. However, no data is extracted from the spreadsheet. 

http://jsfiddle.net/fbb65ou7/

**Comment by sebastianbochan** [comment]
Hi @powerguo 
Thank you for reporitng.
It looks like your spreadsheet does not have public access. 

Simplified demo:
- http://jsfiddle.net/fbb65ou7/

Error:
![zrzut ekranu 2018-01-16 o 11 46 54](https://user-images.githubusercontent.com/2115686/34984993-fc6b3012-fab2-11e7-965c-bb3023b5f47f.png)

Example of working demo:
- http://jsfiddle.net/cyaoqmgy/

For general support questions, please use email / stackoverflow / forum. You can find more information about support [here](http://www.highsoft.com/support)
