### ISSUE TITLE
Styled mode annotations not working

### ISSUE THREAD

**Issue by angelpcadena** [highcharts/highcharts#7669]
When trying to use Annotations.js in Styled mode, it gives the error: 
`Uncaught TypeError: d.attr(...).css(...).shadow is not a function
    at f.Annotation.initLabel`

Example: http://jsfiddle.net/og4o7p9L/

**Comment by pawelfus** [comment]
Hi @angelpcadena 

Thank you for reporting this issue.

**Comment by morganfree** [comment]
@TorsteinHonsi 

Styled mode also affects defining markers in annotations - [jsFiddle](http://jsfiddle.net/qa23d0en/). I have made a [PR](https://github.com/highcharts/highcharts/pull/7724) which should resolved the issue - defining markers will be more consistent with defining other defs in styled mode - [jsFiddle](http://jsfiddle.net/mL9wovyh/).
