### ISSUE TITLE
Export menu and tooltip crepped

### ISSUE THREAD

**Issue by JohnPortella** [highcharts/highcharts#7671]
Hi,
I found some tooltip problems that exceed the size of the chart.

(1) If the chart is small, the export menu is cropped.
(2) If the number of the series is big, the tooltip is cropped. If add this solution (http://jsfiddle.net/highcharts/7wVDV/202/) but not working for charts in modal.

`
(function(H) {
 //code in the example
}(Highcharts));
`

#### Live demo with steps to reproduce
(1)http://jsfiddle.net/3hbac04o/1/
(2)http://jsfiddle.net/7wVDV/252/

#### Product version
Highcharts v6.0.4

#### Affected browser(s)
IE11
Firefox 56

**Comment by sebastianbochan** [comment]
Hi @JohnPortella 
Thank you for the reporting.

In your tickets, there are two separated issues.
1) Tootlip -> which is duplicate of https://github.com/highcharts/highcharts/issues/6515
2) Exporting menu -> you can apply CSS styles which overwrites inline styles: 
```
#container-speed > .highcharts-container {
  overflow: visible!important;
}
```
Demo:
- http://jsfiddle.net/ffdj6ox5/

**Comment by JohnPortella** [comment]
It works. I hope that in a new version you can deal with the tooltip. Thanks
