### ISSUE TITLE
Range Selector Buttons With Data Grouping Corrupt Chart

### ISSUE THREAD

**Issue by holtc** [highcharts/highcharts#7673]
It appears that when changing the data grouping via the range selector buttons, the chart does not erase the old dataGroupings, so the chart becomes messy quickly.  The issue also appears when using the navigator.  You can see the issue  [here](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/rangeselector/datagrouping/).  Is there a way to fix this?

**Comment by pawelfus** [comment]
Hi @holtc 

Thank you for reporting this bug. It's fixed on our master branch: http://jsfiddle.net/dz21chbn/ - fix will be included in the next release (within a few weeks).

**Comment by holtc** [comment]
great thanks!
