### ISSUE TITLE
Discrete spikes in Highstock line series not showing correct value

### ISSUE THREAD

**Issue by dznicol** [highcharts/highcharts#7674]
I have a data series which is almost always 0 apart from a single spike to the value 1. Using a simple datetime line series in Highstock this spike is rendering at 0.5 not 1. If I zoom in using the range selector the value does show as 1, but only once zooming in using the navigator. If I specify a y-axis min/max the spike also renders at 0.5 and not 1. I would expect the line spike to always render the correct value of 1.

I have found that having a shorter data series the value does show properly at 1, for example remove the last row of 0's from the example below, but in all cases I would expect the spike to properly render at value 1.

https://jsfiddle.net/dznicol/y55b4mmb/6/

Found using Highstock v6.0.4 and v5.0.14

Tested on Chrome v63.

**Comment by pawelfus** [comment]
Hi @dznicol 

Thanks you for using Highstock. This is caused by [`series.dataGrouping`](https://api.highcharts.com/highstock/plotOptions.series.dataGrouping) - you can disable this option: https://jsfiddle.net/y55b4mmb/7/

**Comment by dznicol** [comment]
Thanks pawelfus!
David
