### ISSUE TITLE
Combination Chart Axis Labels are being cut off

### ISSUE THREAD

**Issue by abhishek-ip** [highcharts/highcharts#7679]
Hello Support, 

We are facing the issue with the Combination Chart Axis Labels as they are being cut off, Please have a look at the link mentioned below to observed the behavior 
http://jsfiddle.net/nthung2112/5h8es7yp/

#### Expected behavior
The data should be displaying well within the combination chart area.

#### Actual behaviour
Combination Chart Axis Labels are being cut off

**Comment by abhishek-ip** [comment]
Please let me know if this issues has been fixed **OR** if there is a workaround solution to handle this situation currently.

**Comment by sebastianbochan** [comment]
Hi @abhishek-ip,
    Thank you for reporting. At this moment Highcharts does not room space for rotated labels. The workaround is setting spacingTop manually.

   Example:
     - http://jsfiddle.net/ytjvdtqc/
