### ISSUE TITLE
Bug: Halo effect artifact after Pie chart resizing

### ISSUE THREAD

**Issue by fiantsev** [highcharts/highcharts#7681]
#### Expected behaviour
There are not any artifacts staying after resizing of Pie chart

#### Actual behaviour
There is artifact after resizing of Pie chart. This behavior occur only in version 6.0.4 and not prior.

#### Live demo with steps to reproduce
http://jsfiddle.net/ouzrwtxz/2/

1. open jsfiddle
2. hover the most right Pie piece (in order to invoke halo effect)
3. shrink render frame of jsfiddle to the right
4. the artifact will be there. (like in the screenshot below)

![image](https://user-images.githubusercontent.com/25036176/35036960-01e1a1e6-fb87-11e7-9543-b3f5ab4f0df1.png)

#### Product version
Highcharts 6.0.4

#### Affected browser(s)
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Hi @fiantsev 

Thank you for reporting this bug. 

**Workaround:**
Manually redraw halo after chart's redraw: http://jsfiddle.net/BlackLabel/ouzrwtxz/4/
```
  chart: {
    type: 'pie',
    events: {
      redraw: function() {
        Highcharts.each(this.series, function(s) {
          if (s.halo && s.points && s.points[0] && s.points[0].haloPath) {
            s.halo.attr({
              d: s.points[0].haloPath(0)
            });
          }
        });
      }
    }
  },
```

**Comment by TorsteinHonsi** [comment]
It appears prior to v6.0.4 too.
