### ISSUE TITLE
USEHTML Issue in Data-Label (IE-browser) works fine in chrome

### ISSUE THREAD

**Issue by vbinaveenr** [highcharts/highcharts#7689]
#### Live demo with steps to reproduce
Step1: hide series 1
Step2: hide series 2
Step3: hide series 3
<img width="799" alt="chrome" src="https://user-images.githubusercontent.com/9585622/35083730-8bebd860-fc46-11e7-8035-1a88413a2f1d.png">
<img width="787" alt="ie-issue" src="https://user-images.githubusercontent.com/9585622/35083788-dd33426c-fc46-11e7-86d0-20657f1cd498.png">

Step4 : Now you can see the data-label are not aligned properly in IE.

Note : works fine in Chrome.

#### Affected browser(s)
IE

**Comment by nsdevaraj** [comment]
http://jsfiddle.net/skcbhsje/

**Comment by KacperMadej** [comment]
Hi @nsdevaraj 

Thank you for reporting about the problem.

**Affected, tested browsers:**
IE11/Win10,
Edge

**Comment by TorsteinHonsi** [comment]
It has been fixed in the master, will be part of the next release within a few weeks.

Demo with the fix applied: http://jsfiddle.net/skcbhsje/1
