### ISSUE TITLE
yAxis array options ignored in Highstock when setOptions method is used

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7690]
#### Expected behaviour
When using setOptions(), all used parameters should change the default chart options.

#### Actual behaviour
When using setOptions() with multiple yAxis (as an array of axes), options for yAxis aren't used in created charts

#### Live demo with steps to reproduce
http://jsfiddle.net/1dwwhnvt/1/

The same will work with Highcharts chart:
http://jsfiddle.net/1dwwhnvt/2/

#### Product version
Highstock 6.0.4

#### Affected browser(s)
All

**Comment by olehumborstad** [comment]
+1
