### ISSUE TITLE
Highstock xrange chart showing data values of different range with the same width

### ISSUE THREAD

**Issue by semmel87** [highcharts/highcharts#7692]
#### Expected behaviour
When using xrange chart each rectangle on the time axis should have the correct width according to its actual time range.

#### Actual behaviour
Each rectangle has the same width regardless of its time range.

#### Live demo with steps to reproduce
http://jsfiddle.net/oq5a4q2v/3/

#### Product version
Highstock 6.0.4

**Comment by pawelfus** [comment]
Hi @semmel87 

Thanks you for using Highstock. This is caused by [`xAxis.ordinal`](https://api.highcharts.com/highstock/xAxis.ordinal) option, which by default is set to true. You can disable this feature: http://jsfiddle.net/BlackLabel/oq5a4q2v/4/

**Comment by semmel87** [comment]
Hi @pawelfus 
Thanks for helping me out.
