### ISSUE TITLE
dataLabel rotation breaks if y value exceeds yAxis

### ISSUE THREAD

**Issue by drakej** [highcharts/highcharts#7694]
#### Expected behaviour
See data label rotated -10 y pixels above the data point

#### Actual behaviour
Data label never shows up and instead is hidden

#### Live demo with steps to reproduce
http://jsfiddle.net/zu520eut/

I took the dataLabels' rotation example from the latest API document. Then I added a yAxis with a max of 250, and changed the last data point to be 250. This is required to reproduce the bug because otherwise the auto scale for the yAxis will set it to 300 which keeps the label visible.

If you remove the rotation then the data label for the point with 250 will show up. You can even set y to something like -40 with the max in place and it will show up. Therefore it appears that this unexpected behavior is a problem with just the rotation logic.

Oh and here's it working as expected on version 4.2.1:

http://jsfiddle.net/hmpgorhx/

It appears to be the last version that worked as 4.2.2 shows the problem as well as 6.0.4. I discovered this problem months ago and didn't upgrade as it breaks our application. Currently I'm on 4.1.9 still as a result.

#### Product version
6.0.4

#### Affected browser(s)
Chromium 63.0.3239.84
Firefox Quantum 57.0.4

Note: I'm pretty sure the browser isn't the problem in this case unless it doesn't support SVG all together.

**Comment by sebastianbochan** [comment]
Hi @drakej 
Datalabels are cropped by default, but you can disable it by parameter.

Demo:
- http://jsfiddle.net/qwy6p0cw/

Docs:
- https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.crop
