### ISSUE TITLE
Highstock 6 ignores tooltip.shared

### ISSUE THREAD

**Issue by tregoning** [highcharts/highcharts#7696]
#### Expected behaviour
https://api.highcharts.com/highstock/tooltip.shared should behave as Highcharts.

#### Actual behaviour
Highstock *always* behaves as if tooltip.shared was set to true.

#### Live demo with steps to reproduce
(Highstock) broken version: http://jsfiddle.net/tregoning/qgpLmj9y/
(Highcharts) OK version: http://jsfiddle.net/tregoning/10h23xks/

Note: that previous version of Highstock (5.0.14) does work as expected
(Highstock 5.0.14 works as expected) http://jsfiddle.net/tregoning/qts93djL/

#### Product version
Version with the bug: Highstock (6.0.4)

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @tregoning 
You should also disable the split option.

Demo:
- http://jsfiddle.net/gc7btyjp/

**Comment by pawelfus** [comment]
@tregoning 
 
> Highstock always behaves as if tooltip.shared was set to true.

Let me explain. In Highstock < v6, `tooltip.shared` by default was set to true, now in v6 `shared` option is disabled as in [docs](https://api.highcharts.com/highstock/tooltip.shared):

> Defaults to false.

As @sebastianbochan said, what you see now in Highstock, it's [`tooltip.split`](https://api.highcharts.com/highstock/tooltip.split) which by default is enabled: 

> In Highstock, tooltips are split by default since v6.0.0. Stock charts typically contain multi-dimension points and multiple panes, making split tooltips the preferred layout over the previous shared tooltip.
>
> Defaults to true.

Compare:

- disabled `split` & `shared`: http://jsfiddle.net/BlackLabel/qgpLmj9y/1/
- enabled `shared`: http://jsfiddle.net/BlackLabel/qgpLmj9y/2/
- enabled `split` (default): http://jsfiddle.net/BlackLabel/qgpLmj9y/3/

**Comment by tregoning** [comment]
Thanks for the prompt reply. This fixed my issue. 

Just heads up that it might want to consider to document the relationship/interdependency between "shared" and "split" in the documentation (where tooltip.split reads simply as an alternative).

Thanks for the great product, keep up the great work!

**Comment by pawelfus** [comment]
Thanks! You are right, it should be clear in our docs.
