### ISSUE TITLE
Offline chart export as PNG does not work with CSP img-src 'self'

### ISSUE THREAD

**Issue by codemasterover9000** [highcharts/highcharts#7697]
We have a strict CSP where blob: and data: sources are not allowed for images. The highcharts exporter seems to depend on rendering blob sourced images somewhere offscreen when exporting as PNG. As a result of our CSP this fails. 

SVG export works perfectly but that image format is not very user friendly.

We tried using the legacy offline exporting library [highcharts-export-clientside](https://github.com/A----/highcharts-export-clientside) combined with highcharts 6.0.4 with some success except on IE and Edge where the result is a blank image.

Is there a way to make the offline exporting for PNG work without using blob/data sourced images like highcharts-export-clientside used to do?

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.
This looks more like an enhancement suggestion than a bug report.

You could check the decision flow chart (at the bottom [here](https://www.highcharts.com/docs/export-module/client-side-export)) to see if your problem could be resolved by using some exporting options.

@oysteinmoseng ?

**Comment by oysteinmoseng** [comment]
@codemasterover9000 I am curious as to how you had success with the legacy library and not the current one, as the methods seem to be the same for offline PNGs (i.e. using canvas/canVG for the rendering, and downloading with HTML5 download attribute - where the `href` is a data/blob source).

To my knowledge there is no way to currently get the same behavior without data URIs or blobs. You would have to use an online exporting server that can serve the image as an actual PNG. We host such a service at http://export.highcharts.com, and also provide documentation and tools for hosting your own server (see https://www.highcharts.com/docs/export-module/setting-up-the-server). Is this an option?

**Comment by codemasterover9000** [comment]
Yes you are right there is no way to not use data or blob uri's. 

There seems to be an internal change in highcharts where the export output depends on an actual img element in the page dom containing a data or blob based uri as source. Maybe used as an intermediate image to be (re)rendered on the canvas that will be eventually used as a source for the file to download. I dont know.

The legacy library does not seem to do this but wont work on IE/Edge unfortunately.

Below is the error I get in the chrome console when I use the exportChartLocal method. No file is presented for download but also no further error messages.

`Refused to load the image 'blob:http://localhost:8081/8ecb9599-709a-471b-8182-ae3d58ea0e8f' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by oysteinmoseng** [comment]
@codemasterover9000 I see, this is probably because we use the `Image` API to draw the SVG on Canvas. We fall back to canVG for some browsers, while the legacy library seems to use canVG for everything.

The function chain here is `exportChartLocal`calls `getSVGForLocalExport` calls `downloadSVGLocal` calls `imageToDataURL` calls `downloadURL`. You could probably override `downloadSVGLocal` to always use CanVG and then call `downloadURL` directly from the CanVG output.

Example: http://jsfiddle.net/oysteinmoseng/z7h9embf/
Note that this example only works for PNG, and that there is no error handling. For other image types, you can probably just call the original Highcharts.downloadSVGLocal function.

**Comment by oysteinmoseng** [comment]
Actually, looking at the source, you might be able to get away with just doing this: http://jsfiddle.net/oysteinmoseng/g70xqeqz/

That would force CanVG use as well, but leaving the existing functionality for the other image types.

**Comment by codemasterover9000** [comment]
Thanks this does make PNG export work. Is it possible to make it a setting to only use canvg?

There is still one problem though. In Firefox the text size for legend and axis name labels is way too big.  Chrome/IE11/Edge work as expected.

**Comment by oysteinmoseng** [comment]
@codemasterover9000 I was unable to reproduce this issue with my jsfiddle example above. Which version of Firefox are you seeing this with? Let me also know if the issues are the same with the legacy library.

As for adding an option to force CanVG, we can certainly consider that if more users have this issue. For now, please use the workaround above.

**Comment by codemasterover9000** [comment]
Firefox version 58.0

BTW I'am using the styled version of highcharts but that does not seem to make a difference.

The cause seems to be that Firefox is still blocking inline styles on the svg. To reproduce use this CSP Header value using CSP Tester extension for example: `script-src 'unsafe-eval' 'unsafe-inline' code.highcharts.com 'self'; style-src code.highcharts.com 'self'; img-src code.highcharts.com 'self'`

**Comment by oysteinmoseng** [comment]
@codemasterover9000 Avoiding inline styles on the SVG could be tricky, but this seems to be a separate issue. Please contact our support for more specific help with this (see https://www.highcharts.com/support).

**Comment by codemasterover9000** [comment]
@oysteinmoseng I though your solution worked but now I see that it just does the export through the remote export server through the failedLoadCallback function. As I stated earlier we can't use the remote exporting feature.

Your previous solution of overriding downloadSVGLocal results in incorrect images. Width is found to be 2 on most charts. But event when manually set to a higher value results in partial images. The fiddle itself  does seem to work though.

**Comment by oysteinmoseng** [comment]
@codemasterover9000 My fault, try this: http://jsfiddle.net/oysteinmoseng/muLc94tz/

**Comment by codemasterover9000** [comment]
@oysteinmoseng For some reason your second solution results in incorrect or even images that cant be opened. I don't know why. The fiddle you provided above does work but when incorporated in our product fails.

I modified your [first](http://jsfiddle.net/oysteinmoseng/z7h9embf/) solution to work with our code. So will be using that for now. Thanks.

**Comment by oysteinmoseng** [comment]
Interesting.. At least you found a solution. Let me know if this becomes an issue again, and we can reopen.

**Comment by crazyUI** [comment]
+1 

I faced same issue with blob blocked due to CSP. But the second workaround solution given in jsfiddle seems to work.

**Comment by pawelfus** [comment]
Reopening.
FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
@crazyUI Would you be able to reproduce your issue in a jsFiddle?

**Comment by crazyUI** [comment]
Hi,

Since its browser issue I cant replicate in jsfiddle. However update is no blob blocked error in firefox.  Only latest version of chrome is throwing error. We are trying to change the CSP policy in server. Please let me know if there is any other solution or if blob could be avoided always with any setting.

Thank you!

**Comment by oysteinmoseng** [comment]
@crazyUI If you could recreate the chart that is failing in jsFiddle we can see if we can reproduce it on our end. You might also be able to replicate the CSP using iframes and [frame-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src).

**Comment by Dinkarv** [comment]
Hi

While performing PDF export, I see that it makes call for jspdf and svg2pdf js from highcharts url “code.highcharts.com”. Can I avoid this call and use the same libarires from my applications directory? I tried adding these two by npm but exporting still uses highcharts url.

**Comment by karolkolodziej** [comment]
@Dinkarv please use the [libUrl](https://api.highcharts.com/highcharts/exporting.libURL) property in order to change the svg2pdf path.
If this is now what you have been looking for, please [contact our support team.](https://www.highcharts.com/blog/support/)

**Comment by Dinkarv** [comment]
I am working on ember application so I found that copying jspdf.js & svg2pdf.js into distribution folder and load from index.html resulted in pdf offline export a success.

**Comment by Dinkarv** [comment]
> @codemasterover9000 My fault, try this: http://jsfiddle.net/oysteinmoseng/muLc94tz/

I also have the same issue where organisation restricts blob as img-src in CSP. Above, I can observe its still creating blob in network tag while exporting png/jpeg type but it works for SVG type.

Is there any possible solution now available where blob type can be avoided and directly download it?

**Comment by karolkolodziej** [comment]
HI @Dinkarv, 
Are you able to recreate that issue in the fiddle you linked from Oysteyn because I'm not?

**Comment by Dinkarv** [comment]
If you use same jsfiddle and download PNG image. you can observe in network tab that blob is being created.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/22851940/213722699-3a018245-7ef3-452a-abd2-f0602cd2114a.png">

**Comment by karolkolodziej** [comment]
Could you please tell me which version are you using?
If this is one of the latest, could you please try running it with the 9.2.2 version?

**Comment by Dinkarv** [comment]
We are using version 10.0.0 and i think that resolved the issue.
Also, we have enabled the blob for img-src.

**Comment by karolkolodziej** [comment]
Does it mean that the issue is now? Could you please confirm in which version it was resolved?

**Comment by Dinkarv** [comment]
Hi @karolkolodziej 
We are still on the same issue with the versions mentioned above.

**Comment by Dinkarv** [comment]
> @oysteinmoseng For some reason your second solution results in incorrect or even images that cant be opened. I don't know why. The fiddle you provided above does work but when incorporated in our product fails.
> 
> I modified your [first](http://jsfiddle.net/oysteinmoseng/z7h9embf/) solution to work with our code. So will be using that for now. Thanks.

Hi @codemasterover9000 
Can you share the soultion that solved your issue!
