### ISSUE TITLE
Docs: make it easier to find drag-panes.js

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#7704]
https://api.highcharts.com/highstock/yAxis.resize says

> This feature requires the `drag-panes.js` module.

I've spent more than 10 minutes hunting for how to use that module with [CSS styling](https://www.highcharts.com/docs/chart-design-and-style/style-by-css). There's no "drag-panes" at either http://code.highcharts.com/js or https://code.highcharts.com/.

I had to try some URL hacks to discover the right one, https://code.highcharts.com/maps/js/modules/drag-panes.js

Also, [this Uservoice idea](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/5025441-resize-pane-height-dynamically-by-mouse-drag) should be marked as implemented.

**Comment by pawelfus** [comment]
Hi @dandv 

Thanks! This plugin is available for Highstock only [https://api.highcharts.com/**highstock**/yAxis.resize](https://api.highcharts.com/highstock/yAxis.resize), so URL is like any other Highstock plugin: http://code.highcharts.com/stock/js/modules/drag-panes.src.js

**Comment by KacperMadej** [comment]
[The userVoice idea](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/5025441-resize-pane-height-dynamically-by-mouse-drag) is now marked as `completed`.

The remaining issue is an enhancement suggestion.
[ _ ] The links for modules in both modes (classic and styled) should be added to [the Docs site](https://www.highcharts.com/docs/chart-and-series-types/axis-resizer).
[ _ ] The links for modules in both modes (classic and styled) should be added to API reference in at least [yAxis.resize](https://api.highcharts.com/highstock/yAxis.resize).

**Comment by dandv** [comment]
BTW, the sample code at https://www.highcharts.com/docs/chart-and-series-types/axis-resizer has "smart" apostrophes instead of actual `'`.

**Comment by KacperMadej** [comment]
About Docs site - @jon-a-nygaard ?

**Comment by TorsteinHonsi** [comment]
I've added to the API reference.

**Comment by jon-a-nygaard** [comment]
I have added a **Requirements** section, and replaced the apostrophes with the appropriate single quotes in the [docs article](https://www.highcharts.com/docs/chart-and-series-types/axis-resizer).

Does this mean that we can close the issue? @KacperMadej

**Comment by KacperMadej** [comment]
All looks resolved 👍 

Thank you @TorsteinHonsi and @jon-a-nygaard
