### ISSUE TITLE
Series.update called from point events throws an error

### ISSUE THREAD

**Issue by Freywar** [highcharts/highcharts#7708]
#### Expected behaviour
No errors / Error with an explanation is thrown

#### Actual behaviour
`Cannot read property 'tooltipOptions' of null` is thrown

#### Live demo with steps to reproduce
http://jsfiddle.net/69qLLh6L/

Hover any point, see the error in dev console. Tooltips do work.

#### Product version
Highcharts JS v6.0.4

#### Affected browser(s)
Any

**Comment by Freywar** [comment]
Probably a related bug - the same call from series events in some cases shows some weird behavior: http://jsfiddle.net/oy1x3h3z/ when I move mouse fast horizontally starting from outside the chart, labels jump from series to series, tooltip does not appear.

**Comment by pawelfus** [comment]
Hi @Freywar 

Thank you for reporting this bug.

**Workaround:**
Hide/show labels using CSS, instead of `series.update()`: http://jsfiddle.net/BlackLabel/69qLLh6L/2/ - note: CSS solution is much faster than `series.update()`.
JS:
```javascript
  plotOptions: {
    series: {
      dataLabels: {
        enabled: true
      },
      point: {
        events: {
          mouseOver: function() {
            if (this.series.dataLabelsGroup) {
              this.series.dataLabelsGroup.css({
                display: 'block'
              });
            }
          },
          mouseOut: function() {
            if (this.series.dataLabelsGroup) {
              this.series.dataLabelsGroup.css({
                display: 'none'
              });
            }
          }
        }
      }
    }
  },
```
CSS:
```css
#container .highcharts-data-labels {
  display: none;
}

```

**Comment by TorsteinHonsi** [comment]
#### Workaround 2:
Pure CSS solution: http://jsfiddle.net/highcharts/69qLLh6L/3/
