### ISSUE TITLE
Plot Bands are not redered if Infinity passed as `to` parameter 

### ISSUE THREAD

**Issue by aklkv** [highcharts/highcharts#7709]
#### Expected behaviour
If infinity passed to `to` parameter, plot band should render from `from` point to the end of the graph.

#### Actual behaviour
Nothing is rendered.

#### Live demo with steps to reproduce
[http://jsfiddle.net/aklkv/nuLwxdo0/2/](http://jsfiddle.net/aklkv/nuLwxdo0/2/)
#### Product version
v6.0.4

**Comment by sebastianbochan** [comment]
Hi @aklkv 
Thank you for reporting.

**Workaround**
Set date i.e for 3000 year.

Demo:
- http://jsfiddle.net/a2z2zv09/

**Comment by pawelfus** [comment]
Or in general, we can use `Number.MAX_SAFE_INTEGER`. Demo: http://jsfiddle.net/BlackLabel/nuLwxdo0/3/

The same issue with `from` and `-Inifity`: http://jsfiddle.net/BlackLabel/nuLwxdo0/4/

*Internal note:*
Technically, `Infinite` is the number type..

**Comment by TorsteinHonsi** [comment]
It's a regression since v6.0.4, specifically 2032e5769.
