### ISSUE TITLE
Highcharts dataLabels remain on the frame after reset zoom

### ISSUE THREAD

**Issue by alirezameftahi71** [highcharts/highcharts#7710]
#### Scenario
Say we have a column chart with 50000 data on it. We use the boost module to speed it up. And we have the zoom and dataLabels enabled. At first load no dataLabels display because of the boost behavior.  But when I zoom in enough, I must see the dataLabels and I do. So far so good. 

#### Expected behaviour
When I press the resetzoom button, the chart should zoom out, and the dataLabels should disappear again.

#### Actual behaviour
The dataLabels remain on the chart in a messed up way.

#### Example
https://jsfiddle.net/alinux7/m1tp8ub2/

#### Product version
Highcharts 6.0.4

#### Affected browser(s)
Tested on:
Firefox, Chrome

**Comment by pawelfus** [comment]
Hi @alirezameftahi71 

Thank you for reporting this bug. It should be fixed on our master branch: http://jsfiddle.net/BlackLabel/m1tp8ub2/2/ - could you confirm?

**Comment by alirezameftahi71** [comment]
Yes, thank you this fixed the problem. 
When the stable version will be released?

**Comment by KacperMadej** [comment]
@alirezameftahi71  Within next few weeks.
