### ISSUE TITLE
Series is removed when using update() and remove() even when redraw: false parameter is used

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7712]
#### Expected behaviour
Series should not be removed until chart redraw (in Series.update() and Series.remove()) when redraw parameter is set to false.

#### Actual behaviour
When Series.update() and Series.remove() is used series is removed even when redraw is set to false.

#### Live demo with steps to reproduce
Using remove:
http://jsfiddle.net/0L97atxb/1/

Using update:
http://jsfiddle.net/0L97atxb/2/

#### Product version
Highcharts 6.0.4

**Comment by bmartinelle** [comment]
We are impacted by this defect as it results in a very visible white flash when series that are updated are immediately removed from the chart (we're iterating over a number of series to update a bunch of options and then performing some additional calculations before calling chart.redraw()) is there any workaround?

**Comment by KacperMadej** [comment]
This doesn't look like a bug.

The redraw option is about chart being rendered again - align all chart's elements that might require it, like changing legend, axes, other series, etc.

If you call chart.redraw right after all dynamic changes then there shouldn't be any white flashes, but if you calculations take too much time you could consider calling series.remove / series.update after the calculations or adding [loading screen](https://api.highcharts.com/class-reference/Highcharts.Chart#showLoading)

**Comment by bmartinelle** [comment]
Adding chart.redraw right after my forEach does help with the flicker. Thanks for that suggestion - better than passing that redraw flag as true for sure! 
If you don't consider this a bug maybe the API doc should reflect that the item will be immediately removed regardless of the redraw flag. That would have saved me a lot of time ;)
