### ISSUE TITLE
HighStock bug with reversed X-axis and dynamic update

### ISSUE THREAD

**Issue by tjheiska** [highcharts/highcharts#7713]
#### Expected behaviour
When navigator scrollbar is dragged left, it should be tied there and dynamically added points should appear in detailchart.

#### Actual behaviour
Dragged scrollbar is not tied to left and new values does not show up in detailed view.
Also, if bar is dragged right, it automatically flows to left extreme.

#### Live demo with steps to reproduce
https://jsfiddle.net/tjheiska/ovq3vvzp/2/

#### Product version
Highstock v. 6.0.4

#### Affected browser(s)
Tested with Google Chrome Version 63.0.3239.132 (64-bit)

**Comment by KacperMadej** [comment]
Hi @tjheiska 

Thank you for reporting about the problem.

**Comment by tjheiska** [comment]
Commit seems to fix the issue with new points. Dragging the scrollbar maximum right still throws it to left.

**Comment by KacperMadej** [comment]
@tjheiska 
I'm not sure that you have tested the code with the fix. Please check this demo: https://jsfiddle.net/BlackLabel/ovq3vvzp/5/

If there's still a problem, please let us know.

**Comment by tjheiska** [comment]
@KacperMadej Ok, the demo is working, so must be my mistake. Sorry about false alarm.
