### ISSUE TITLE
bug in using addPoint method to draw a polar chart 

### ISSUE THREAD

**Issue by sumile-ting** [highcharts/highcharts#7719]
var datas = [{x: 50.48, y: 0.0565685424949238}, 
              {x: 50.48, y: 0.4482186966202994}, 
              {x: 38.51, y: 0.7990619500389191}];
    var series =chart.series[0];
    for(var i=0;i < datas.length;i++){
         series.addPoint(datas[i])
    }
    chart.redraw();

#### Expected behaviour

![image](https://user-images.githubusercontent.com/29885006/35326413-901b051a-0131-11e8-9ca4-d98b581709af.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/29885006/35326461-b50139a8-0131-11e8-87f9-c8c016605f33.png)

but using method below can achive expected behaviour:
` var datas = [{x: 50.48, y: 0.0565685424949238}, 
                      {x: 50.48, y: 0.4482186966202994}, 
                      {x: 38.51, y: 0.7990619500389191}];
    chart.update({
         series: [{
                   data: datas  
        }]
     }, true)`

#### Live demo with steps to reproduce

error draw:   http://jsfiddle.net/sumile/fwvjvpu6/1/
expected: http://jsfiddle.net/sumile/yj2jn9qp/6/
#### Product version

higcharts v5.0.7
highcharts-more.js  v5.0.7
#### Affected browser(s)
Google Chrome 63.0.3239.132

**Comment by KacperMadej** [comment]
Hi @sumile-ting 

This does not look like a bug. Line type series with point with the same x values behavior is not defined, so it's not expected to work one way or another. For this kind of data use `scatter` type series.
Demo: http://jsfiddle.net/BlackLabel/fwvjvpu6/2/

`scatter` also allows using unsorted (by x in ascending order) data sets and points will be connected in the order of appearance in the data array of the series.

If you don't have any more questions I would like to close this issue as `not-a-bug` case.

**Comment by sumile-ting** [comment]
Thank you @KacperMadej for your reply.

It seems have no relation to line type series with point with the same x values, but seems to be that points is sorted  by x in ascending order for line type when invoke addpoint method.
Demo: http://jsfiddle.net/sumile/3mf1o7ca/1/

scatter can solve my problem, so thanks again.

**Comment by KacperMadej** [comment]
@sumile-ting 

The answer to "why not sort data sets in the first case" is given in [the error # 15 site](https://www.highcharts.com/errors/15) to which link is given in browser console in your [first case demo](http://jsfiddle.net/sumile/3mf1o7ca/).

> For performance reasons, Highcharts does not sort the data, instead it is required that the implementer pre-sorts the data.
