### ISSUE TITLE
Click with drag on context menu button within a 3D column chart triggers chart zoom

### ISSUE THREAD

**Issue by vadimpopa** [highcharts/highcharts#7728]
#### Expected behaviour
When clicking with drag on the context menu within the chart should do anything.

#### Actual behaviour
Clicking with a slight drag on the button triggers chart zoom and changes it.

#### Live demo with steps to reproduce
http://jsfiddle.net/vadimpopa/z078e60u/

![dd1](https://user-images.githubusercontent.com/3592131/35393177-e7bcdb66-01ec-11e8-8787-b2b2d3a31382.gif)

#### Product version

Tested on 5.0.12 and latest version.

#### Affected browser(s)
All.

Other notes:

<img width="856" alt="screen shot 2018-01-25 at 4 31 00 pm" src="https://user-images.githubusercontent.com/3592131/35393279-34513738-01ed-11e8-9889-8e887e795610.png">

**Comment by pawelfus** [comment]
Hi @vadimpopa 

Thank you for reporting this issue. You are right, it shouldn't happen on the non-plotting area.

**Comment by vadimpopa** [comment]
@pawelfus any idea on a temporary fix ? I could find it myself, but I'm buys right now with something else which has a higher priority. If you don't, I'll take a look on it later, I'm sure will find an workaround. Thanks.

**Comment by pawelfus** [comment]
**Possible workaround:**

Disable `is3d()` method: http://jsfiddle.net/BlackLabel/z078e60u/1/

```javascript
(function (H) {
  H.wrap(H.Chart.prototype, 'isInsidePlot', function (p) {
    var orig3d = this.is3d, ret;

    this.is3d = false;
    ret = p.applt(this, Array.prototype.slice.call(arguments, 1));
    this.is3d = orig3d;

    return ret;
  });
})(Highcharts);
```

**Comment by vadimpopa** [comment]
With your workaround zoom selection is not working anymore. Try on your fiddle to select a sub-chart, is not working.

**Comment by pawelfus** [comment]
My apologies, fixed demo: http://jsfiddle.net/BlackLabel/z078e60u/2/

```javascript
(function (H) {
	H.wrap(H.Chart.prototype, 'isInsidePlot', function (p) {
  	var orig3d = this.is3d, ret;
    
    this.is3d = function () { return false };
    ret = p.apply(this, Array.prototype.slice.call(arguments, 1));
    this.is3d = orig3d;
    
    return ret;
  });
})(Highcharts);
```
