### ISSUE TITLE
Boost: Issue with ConnectNulls when zooming

### ISSUE THREAD

**Issue by NeuwenWolf** [highcharts/highcharts#7730]
#### Expected behaviour
Null points should never be connected.

#### Actual behaviour
In specific circumstances (which I cannot fully pin down), points that are not within the zoomed range (i.e. not visible) are connected.

#### Live demo with steps to reproduce
http://jsfiddle.net/vd1y2cjx/7/
Zoom in on the two points in Series 2 to see Series 1 connect
![image](https://user-images.githubusercontent.com/12142465/35411954-e77480c4-01d7-11e8-96ae-ef482d663af9.png)
![image](https://user-images.githubusercontent.com/12142465/35411978-f6445d18-01d7-11e8-9cea-b571e13f7a4f.png)
![image](https://user-images.githubusercontent.com/12142465/35411994-0491719e-01d8-11e8-9506-e06652e77141.png)

#### Product version
Development version of boost.js
Latest stable of highcharts.js

#### Affected browser(s)
Only tested in Chrome

#### Further Comments
It seems you need at least 3 series to make it happen.
You don't need values on either side, here is the edge of a chart where there are no values to the left, but the chart is drawing horizontal null-value lines:
![image](https://user-images.githubusercontent.com/12142465/35412269-e4dfc9c6-01d8-11e8-9dc9-54f68bafa1e6.png)

**Comment by sebastianbochan** [comment]
Hi @NeuwenWolf 
Thank you for reporting

_Internal note_
Looks like similiar issue like https://github.com/highcharts/highcharts/issues/7716

@cvasseng any comments?

**Comment by cvasseng** [comment]
A fix has been pushed, and is pending merge.

Here's a preview: http://jsfiddle.net/baz8mfLh/

**Comment by cvasseng** [comment]
Fixed in 6.0.5.
