### ISSUE TITLE
update series type error while dataGrouping

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#7731]
I try to update column to line in Highstock

#### Expected behaviour

column series update to line 

#### Actual behaviour
add line series

#### Live demo with steps to reproduce
http://jsfiddle.net/b62tdy3w/2/

zoom the navigator to trigger dataGrouing, then click the button to update Column serises to line
![snipaste_2018-01-26_16-06-05](https://user-images.githubusercontent.com/6829290/35430338-cecacd0e-02b2-11e8-953e-482e46ad1ce5.png)

#### Product version
Highstock

**Comment by pawelfus** [comment]
Thanks! It's already fixed on our master branch, take a look: http://jsfiddle.net/BlackLabel/b62tdy3w/10/
