### ISSUE TITLE
drag panes resize navigator axis

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#7732]
#### Live demo with steps to reproduce

http://jsfiddle.net/b62tdy3w/8/

1. drag the axis resizer, yAxis in navigator will change size
2. click the button to Add a yAxis,  drag the axis resizer, yAxis in navigator will chang size too

#### Product version
Highstock

#### Note
set `axis.resize.controlledAxis` options can fix the issue demo: http://jsfiddle.net/b62tdy3w/9/.
drag panes should ignore the yAxis in navigator while resize.

**Comment by pawelfus** [comment]
Hi @zhy1stgg 

Thanks for reporting. You are right, yAxis from navigator should be excluded from the resizables axes.
