### ISSUE TITLE
关于两根条柱大小差距过大不显示的问题

### ISSUE THREAD

**Issue by zx472010602** [highcharts/highcharts#7737]
在柱状图分类X轴时：
当同时设置了Y轴min属性和max属性值时，正数时，Y值过小时一切正常（若max1000，min-1000），Y是1，也能正确显示一个短柱

但负数时，大于一定范围的轴却会直接消失（若max1000，min-1000），Y-100会显示，-10就会直接消失，（若max368600,min-368600），Y值大于-1986的柱子会直接消失（如-1985），-1986会显示一条短柱

总结：当同时设置了max属性和min属性相同时，若负数过大时（根据MAX，MIN的大小不同），柱子会消失。
若该BUG可以修复，请回复我下邮件多谢。若需要我提供option，可以回我email：472010602@qq.com

**Comment by zhy1stgg** [comment]
@zx472010602 Please describe your issue in English.

### Expected behaviour

http://jsfiddle.net/romhzcmh/

### Actual behaviour

 http://jsfiddle.net/romhzcmh/1/

**Comment by KacperMadej** [comment]
@zx472010602 
Wild guess: use [`minPointLength`](https://api.highcharts.com/highcharts/plotOptions.column.minPointLength) to make sure that a point is visible. Demo: http://jsfiddle.net/BlackLabel/romhzcmh/2/

**Comment by pawelfus** [comment]
Closing dues to inactivity.
