### ISSUE TITLE
Conditional drilldown breaks drilldown axis labels

### ISSUE THREAD

**Issue by p-himik** [highcharts/highcharts#7738]
#### Expected behaviour
Clicking on a drilldown axis label shouldn't do anything when all drilldown event handlers return false

#### Actual behaviour
After drilling down via a drilldown axis label, the state of the chart is broken - no drilldown was performed, an empty drill up button is present, clicking on which results in
```
drilldown.js:15 Uncaught TypeError: Cannot read property 'levelNumber' of undefined
    at a.Chart.q.drillUp (drilldown.js:15)
    at a.SVGElement.<anonymous> (drilldown.js:14)
    at SVGGElement.<anonymous> (highcharts.js:74)
```

#### Live demo with steps to reproduce
https://jsfiddle.net/1bzm2vdu/
Click on any drilldown axis label

#### Product version
6.0.4

#### Affected browser(s)
Checked only Google Chrome, but should be reproducible in any browser

**Comment by sebastianbochan** [comment]
Hi @p-himik 
Thank you for reporting.

**Workaround:**
Move the condition to the drilldownCategory method.

Demo:
- https://jsfiddle.net/xr00eckL/
