### ISSUE TITLE
Pie Chart slices are not updating properly (duplicated) when refresh on certain on time interval

### ISSUE THREAD

**Issue by sakthivelbirt** [highcharts/highcharts#7740]
#### Expected behaviour
The pie slices should reflect the new data

#### Actual behaviour
The pie slices are duplicated after refresh happens for couple of times (Consider the Singapore slice. It will be generated twice)

#### Live demo with steps to reproduce
http://jsfiddle.net/cuxounrr/3/

**Comment by KacperMadej** [comment]
Hi @sakthivelbirt 

Nothing is wrong here. The duplicate is from previous update, because you are shifting in 5 points in 6 points data array, so 1 will stay.

Use 5 points array at start and there's no problem: http://jsfiddle.net/BlackLabel/cuxounrr/5/
