### ISSUE TITLE
Is it possible to set the lineWidth for the specific zones?

### ISSUE THREAD

**Issue by m-maksyutin** [highcharts/highcharts#7741]
For example: http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/series/color-zones-simple

Сan we make the green part thicker?

**Comment by sebastianbochan** [comment]
Hi @m-maksyutin 
For general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email. 

Regarding to your case, you can try to use [zones](https://api.highcharts.com/highcharts/plotOptions.series.zones).

**Comment by m-maksyutin** [comment]
Hi @sebastianbochan 
Unfortunately, your example does not solve my problem, because I need to change line width (not line color).
Apparently, Highcharts can not change line width for specific zone. 
There is no option for it: https://api.highcharts.com/highcharts/plotOptions.series.zones
Is there any workaround?

**Comment by pawelfus** [comment]
In Highcharts CSS version, you can apply any styles you want for a zone, for example increase the line-width: http://jsfiddle.net/BlackLabel/rs8o6yzb/ Zones in JS version support only options in the API: https://api.highcharts.com/highcharts/plotOptions.series.zones

**Comment by m-maksyutin** [comment]
Hi @pawelfus 
Thank you, this is what I need
