### ISSUE TITLE
Alpha value of rgba shows incorrectly for bubble chart

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#7742]
#### Expected behaviour
Alpha value of rgba should show correct color for bubble chart

#### Actual behaviour
The alpha value is not respected when it's entered above 0.5, it displays as 0.5. However, when alpha value is entered below 0.5, e.g. 0.2, it displays correctly. It's almost like there's a cap alpha value for data points at 0.5.

#### Live demo with steps to reproduce
- https://jsfiddle.net/wz6wz8e7/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
**Workaround:**

Set `series.marker.fillOpacity` to 1, otherwise default value (0.5) will be applied. Demo: https://jsfiddle.net/BlackLabel/wz6wz8e7/4/

Note:
`marker.fillOpacity` doesn't exist in our docs: https://api.highcharts.com/highcharts/plotOptions.bubble.marker

**Comment by KacperMadej** [comment]
The docs are updated and the option is documented.
