### ISSUE TITLE
[Bug][Spyderweb] Click event always gets the same series when tooltip is shared

### ISSUE THREAD

**Issue by sergipr** [highcharts/highcharts#7743]
#### Expected behaviour
Clicking any series of the chart must generate an event with the information of the series clicked.

#### Actual behaviour
Spyderweb chart (polar: true, type: line) when tooltip is shared always gets the same series in the event no matter which one you clicked.
If the chart is not polar or the tooltip is not shared it works fine.

#### Live demo with steps to reproduce
http://jsfiddle.net/12L28jw0/

#### Product version
Latest

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @sergipr 

Thank you for reporting this bug. You are right, click event is always fired for the last series (or series with highest zIndex).
