### ISSUE TITLE
Highstock 6.0.4 update datagroup -> markers issue

### ISSUE THREAD

**Issue by lmchzromain** [highcharts/highcharts#7745]
#### Expected behaviour
When i update the chart, old markers should dissapear

#### Actual behaviour
When i update the chart, old markers still appear

#### Live demo with steps to reproduce
Ok with 6.0.3 : http://jsfiddle.net/65qjLa6q/2/
Broken with 6.0.4 : http://jsfiddle.net/65qjLa6q/1/

#### Product version
Highstock 6.0.4

#### Affected browser(s)
Chrome 63

**Comment by pawelfus** [comment]
Hi @lmchzromain 

Thank you for reporting this bug. It's fixed on our master branch: http://jsfiddle.net/BlackLabel/65qjLa6q/3/ and will be part of the v6.0.5 release.
