### ISSUE TITLE
Available data in highstock tooltip formatter is not correct

### ISSUE THREAD

**Issue by kennydp** [highcharts/highcharts#7747]
#### Expected behaviour
When delaring a non shared tooltip, the formatter should have the data detailed in the [API documentation](https://api.highcharts.com/highstock/tooltip.formatter). So e.g. `this.series`

#### Actual behaviour
We only get the properties available in a shared tooltip. So x, y and the points array.

#### Live demo with steps to reproduce
https://jsfiddle.net/ushc9v1q/

#### Product version
Highstock 6.0.4
I should note that I encountered this issue since updating from 5..14 earlier today

#### Affected browser(s)
Tested in Chrome and Firefox

**Comment by pawelfus** [comment]
Hi @kennydp 

Thank you for reporting the issue. This is caused by `tooltip.split` - in Highcharts v6, by default `split` is set to true which works similar to `tooltip.shared`. See: https://jsfiddle.net/BlackLabel/ushc9v1q/1/ - [docs](https://api.highcharts.com/highstock/tooltip.split)

**Comment by pawelfus** [comment]
Docs updated.
