### ISSUE TITLE
HighMaps Stroke color

### ISSUE THREAD

**Issue by ankha0109** [highcharts/highcharts#7762]
Hi,
I am using Highmaps. I need to add stroke color of the region like attached image and i am unable to do it.

How i can add stroke color in map ?
**Demo:**
http://jsfiddle.net/pe40p00y/59/

I'm using latest version.

![screenshot_696](https://user-images.githubusercontent.com/8737838/35604146-c3aba7be-067b-11e8-982c-3e16dc548d12.png)

**Comment by oysteinmoseng** [comment]
You can achieve this by adding a second series below the main series, with a larger border width. Example: http://jsfiddle.net/mp5owkp8/
