### ISSUE TITLE
Sankey Chart: Color of Links

### ISSUE THREAD

**Issue by shabala** [highcharts/highcharts#7763]
# Enhancement
#### Expected behaviour
Is there some way we can specify the color of the links in a Sankey Chart?

#### Actual behaviour
Right now, the chart considers color by node.

**Comment by pawelfus** [comment]
Hi @shabala 

At this moment, link color is inherited from point color. A small plugin can add this feature:

```javascript
(function(H) {
  H.wrap(H.seriesTypes.sankey.prototype, 'pointAttribs', function(p, point, state) {
    var orig = p.call(this, point, state);
    // Added to a point "linkColor" option:
    var color = point.options.linkColor;

    if (color) {
      orig.fill = color;
    }

    return orig;
  });
})(Highcharts);
```

Demo: http://jsfiddle.net/9cqpbnc3/

**Comment by TorsteinHonsi** [comment]
The points _are_ the links, so all you have to do is to add a `point.color` option: http://jsfiddle.net/highcharts/rdaxso6o/
