### ISSUE TITLE
US map

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#7764]
#### Expected behaviour
115 Congressional Districts

#### Actual behaviour
113 Congressional Districts

The map is not up-to-date (2017), but from 2015.

**Comment by KacperMadej** [comment]
_Internal note:_ I suggest keeping the current one as a historical map when resolving the problem.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#18
