### ISSUE TITLE
Wrong position of dataLabels with useHTML: true on IE11 and Edge

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7768]
#### Behaviour
Wrong position of dataLabels with useHTML: true on IE11 and Edge.
Sometimes on load, but 99% of times after manual zoom.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/uxxu69yw/
Steps:
1. zoom into middle section of the chart

#### Internal notes
1. The problem is not always recreated by calling the set extremes by setExtremes call, so zoom in manually.

2. The visible problem is in the main div holding dataLabels - it has both top & left set in CSS and translate with same or similar values. Usually those offsets are doubled - one of them should be removed or not be set.
<pre><code>
&lt;div class="highcharts-data-labels highcharts-series-2 highcharts-xrange-series " 
    style="
      <b>left: 67px; top: 53px;</b>
      visibility: visible; position: absolute; opacity: 1; 
      <b>transform: translate(60px, 53px);</b>
    ">
  [...]
&lt;/div>
</pre></code>

#### Affected browser(s)
IE11 / Win10, Edge

**Comment by TorsteinHonsi** [comment]
Not visible on my system, tested IE11 and Edge. I suspect it may be a regression, can you do a little bisecting and see and you can pinpoint it to a commit?

**Comment by KacperMadej** [comment]
Resolved since 6.0.5 (at least I'm no longer able to recreate the issue with the 6.0.5 and I can in IE11 with version 6.0.4). Since the problem is resolved then there's no need to find a commit - or should I find it anyway? If yes, please let me know.
