### ISSUE TITLE
SVG offline export in styled version in IE11 includes style "length: 317;" in svg element

### ISSUE THREAD

**Issue by RainerSchwarze** [highcharts/highcharts#7770]
#### Expected behaviour

The `length` property should not be included when inlining styles.

#### Actual behaviour

The `length` property gets included when inlining styles in offline export in IE11.

#### Live demo with steps to reproduce

https://jsfiddle.net/vus7pxbb/

- Open in IE11
- click on chart context menu, select SVG export
- download / save the SVG file
- (I open SVG files in Chrome -> right click, Inspect Element or View Source)

#### Product version

- Highcharts v5 and v6

#### Affected browser(s)

IE11 (tested with 11.0.9600.17843 on Win7 64bit)

#### Notes:

The exported svg element looks like this: (style "clipped")

```
<svg 
   xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" 
   class="highcharts-root" 
   style="...; css-float: none; length: 317;"
```

`length` gets iterated over when checking computed styles during inlining styles with the `for (... in ...)` loop.
`length` is not inlined when using Chrome.

**Comment by KacperMadej** [comment]
Hi @RainerSchwarze 

Thank you for reporting about the problem.

Is the problem causing any serious problems?
We could try creating a workaround if it does.

**Comment by RainerSchwarze** [comment]
Hi @KacperMadej , as far as I see it does not create problems on its own. I am looking into another problem where inlining styles leads to different output between IE11 and Chrome. Until I know more, I would assume that this (`length`) does not cause problems. I'll import the SVG file into a few programs, to see if there are issues with that. I'll update this issue, if something relevant shows up.

**Comment by TorsteinHonsi** [comment]
As you can see in the commit, we just needed to add the CSS property to the blacklist. This is also exposed, so you can experiment with different properties to blacklist:

`Highcharts.SVGRenderer.prototype.inlineBlacklist.push(/^length$/);`

https://jsfiddle.net/highcharts/vus7pxbb/1/

Thanks for reporting, and please keep us posted if you find other things that should be modified to get closer to full browser parity.

**Comment by RainerSchwarze** [comment]
Thanks for pointing out the blacklist. I saw it when looking through the code, but it slipped my mind later :-)
