### ISSUE TITLE
Area Series Marker Symbol is not applied to Legend item for Area Series

### ISSUE THREAD

**Issue by cnrudd** [highcharts/highcharts#7771]
#### Expected behaviour
Expect same marker symbol used in Area series to be used in chart legend for the Area series.

#### Actual behaviour
The marker symbol is not used.  For Area series, the legend symbol is always a solid colored circle.
For other types of series the symbol is the same in the marker and in the legend.

#### Live demo with steps to reproduce
http://jsfiddle.net/cnrudd/zkqLyzm6/

#### Product version
Highcharts 6.0.4 

#### Affected browser(s)
Observed in Chrome 63, but this is most likely not a browser specific issue

**Comment by pawelfus** [comment]
Hi @cnrudd 

Thank you for reporting the issue. Area/areaspline/column/bar series types have fill color in the legend, line/spline/scatter series types have marker+line in the legend.

We can replace the method responsible for rendering legend item: http://jsfiddle.net/BlackLabel/zkqLyzm6/2/ but I'm not sure if we should do this in the core - it will change already existing charts and will be reported as regression by other users. Maybe an option in the API to choose method?

Snippet:
```javascript
Highcharts.seriesTypes.area.prototype.drawLegendSymbol = Highcharts.seriesTypes.line.prototype.drawLegendSymbol;
```

**Comment by cnrudd** [comment]
Hi @pawelfus 
Thanks for taking a look and suggesting an immediate fix.

In our case I would favor applying a modified version of 
     Highcharts.seriesTypes.line.prototype.drawLegendSymbol
     to
    Highcharts.seriesTypes.area.prototype.drawLegendSymbol 
one which produces a larger (same size as current area circle symbols) legendSymbol that does not have a line through it.

For the long term core change question, I don't have the perspective of users that would report a permanent (no API option) change as a regression.  An API option is certainly possible, but I don't see the use case for it being a necessity.

**Comment by pawelfus** [comment]
@cnrudd thanks for the answer. In other words, you just want the symbol in the legend, nothing else? We don't have this type of symbol, but you can modify a bit code and hide temporary line: http://jsfiddle.net/BlackLabel/zkqLyzm6/4/

```javascript
Highcharts.seriesTypes.area.prototype.drawLegendSymbol = function(legend) {
  var lineWidth = this.options.lineWidth;
  // Reset line width
  this.options.lineWidth = 0;
  // Draw the symbol
  Highcharts.LegendSymbolMixin.drawLineMarker.apply(this, arguments);
  // Restore line width
  this.options.lineWidth = lineWidth;
}
```

**Comment by cnrudd** [comment]
Very cool, thanks for the tip!

**Comment by BKSelvakumaranK** [comment]
https://github.com/highcharts/highcharts/issues/17388
