### ISSUE TITLE
Incorrect rtl long text xAxis labels

### ISSUE THREAD

**Issue by EmmanuelBens** [highcharts/highcharts#7772]
Hi,

when using Highchart with labels in xAxis in rtl language (hebrew), text is incorrectly displayed.

Please see http://jsfiddle.net/qqcep7rn/2/

when text is long and have to be wrapped, you can see that title (tooltip) text (that is correct) is different than displayed text (that is incorrect).

Thanks

**Comment by KacperMadej** [comment]
Hi @firemen26 

Thank you for reporting about the problem.
Just to be on the same page - the line's order is inverted when text is wrapped? It should be right-to-left and top-to-bottom and it's bottom-to-top, right? If a simple yes is not the answer, please provide detailed info.

**Comment by firemen26** [comment]
Hi **@KacperMadej** 
Thanks you for you response.

Almost. If the string is smaller than 22 characters, this is right.
If the string is longer, this is more complicated. Some of the first characters are on the right place, and the following text need to be inverted like in the first case.
![highcharts rtl](https://user-images.githubusercontent.com/36004321/35667550-c2c2e450-0736-11e8-8809-e814663e2a64.png)

**Comment by mooioom** [comment]
I am having the same issue, this problem is probably affecting all RTL languages...

**Comment by pawelfus** [comment]
Hi @firemen26  and @mooioom 

Thank you for the details. I'm not sure if this is Highcharts bug, maybe browser? Let's consider this SVG (part of the Highcharts):

```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="700" height="400">
  <text x="50" y="50">
    <tspan>צריכה בפועל</tspan>
    <tspan dy="14" x="50">ממוצעת למר</tspan>
    <title>צריכה בפועל ממוצעת למר</title>
  </text>
</svg>
```

Demo: http://jsfiddle.net/BlackLabel/qqcep7rn/5/ - correct me if I'm wrong, but aren't `tspan`'s correct? It's `צריכה בפועל` and `ממוצעת למר`, but in a browser it's rendered as:

![screen shot 2018-02-01 at 13 43 35](https://user-images.githubusercontent.com/1453926/35679057-f3a59ed6-0755-11e8-93cc-be96e61da2c9.png)

**Comment by firemen26** [comment]
Hi **@pawelfus**

You're right. It seems to be bug in chrome. In IE, FF and mobile, it works fine.

Thanks you
