### ISSUE TITLE
SMA compare setting

### ISSUE THREAD

**Issue by 3Ue** [highcharts/highcharts#7773]
#### Expected behaviour
When setting compare to "percent" for a sma series, you get the moving average of the percent values of the linked series. The sma series does not start at 0% but rather is based on the current compareValue from the linked series.

#### Actual behaviour
The sma series starts at 0% and is based on the ealiest sma value in the visible plotarea.

#### Live demo with steps to reproduce
http://jsfiddle.net/meke162u/

With expected behaviour by wrapping Highcharts.seriesTypes.sma.prototype.processData:
http://jsfiddle.net/0k1Lhgfz/

#### Product version
Highstock 6.0.4

#### Affected browser(s)
Firefox (probably all)

**Comment by pawelfus** [comment]
Hi @3Ue 

Thanks for using Highstock! You are right, it should be possible to decide if we want to show change of SMA, or SMA of change.
