### ISSUE TITLE
Minified sunburst.js missing in Highcharts v6.0.5

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#7775]
#### Expected behaviour
sunburst.js should be available in Highcharts v6.0.5

#### Actual behaviour
Only sunburst.src.js is available

#### Steps performed
Checked on the link : http://code.highcharts.com/
Also checked the archived zip on the link: https://www.highcharts.com/download

#### Product version
Highcharts v6.0.5

**Comment by sebastianbochan** [comment]
Hi @amruta30 
    Thank you for the reporting.

@jon-a-nygaard

**Comment by TorsteinHonsi** [comment]
It's a regression, it was [available in v6.0.4](http://code.highcharts.com/6.0.4/modules/sunburst.js).

**Comment by RainerSchwarze** [comment]
(See also #7759)

**Comment by amruta30** [comment]
When will it be available? 
Since the latest version has fixes related to Sunburst chart like inner size, etc. I need to upgrade to v6.0.5 as soon as possible.

**Comment by jon-a-nygaard** [comment]
Hi @amruta30,

[modules/sunburst.js](http://code.highcharts.com/6.0.6/modules/sunburst.js) is available again now that the v6.0.6 has been released. We have also added precautions to avoid this from happening again.

Thanks again for reporting!
If you need anything further, please let us know.

**Comment by amruta30** [comment]
Hi @jon-a-nygaard ,

Thanks alot for support. I upgraded to v6.0.6!
