### ISSUE TITLE
plotOptions.line.linecap cannot define both stroke-linecap and stroke-linejoin

### ISSUE THREAD

**Issue by xdestiny** [highcharts/highcharts#7777]
#### Expected behaviour
Setting the linecap to "miter" should make linejoins sharp. 

#### Actual behaviour
The SVG options stroke-linecap and stroke-linejoin have different possible values. Highcharts allows "round", "butt", "square" which are only linecap options, Linejoin only has the "round" value in common and thus any other settings does not affect the linejoins. 

An independant linejoin setting would be required to allow the settings "miter" and "bevel" which are not valid settings for linecap behaviour. 

#### Live demo with steps to reproduce
none

#### Product version
all version since linecap was introduced

#### Affected browser(s)
all

**Comment by KacperMadej** [comment]
Hi @xdestiny 

This looks like an enhancement suggestion and for those we recommend using userVoice. highcharts.uservoice.com/forums/55896-general

**Comment by pawelfus** [comment]
Hi @xdestiny 

Thank you for the suggestion! 

**Workaround:**
Use CSS styles to change `stroke-linecap` and `stroke-linejoin`: http://jsfiddle.net/BlackLabel/rvwstdr8/

```css
.highcharts-series path {
  stroke-linecap: square;
  stroke-linejoin: miter;
}
```
