### ISSUE TITLE
Fill-opacity is not applied to the 1st series in spiderweb (polar) area chart

### ISSUE THREAD

**Issue by DmitryPorotov** [highcharts/highcharts#7779]
#### Expected behaviour
`fill-opacity` to be applied to all series

I'm not sure whether it's by design or not. I've tested versions down to version 4.2.7 and they all behave the same.

#### Actual behaviour
first series does not get `fill-opacity` attribute

#### Live demo with steps to reproduce
http://jsfiddle.net/nLhqLxwd/1/

#### Product version
Highcharts (spiderweb chart): tested on a lot of versions between 4.2.7 to 6.0.5 - same result

#### Affected browser(s)

All

**Comment by sebastianbochan** [comment]
Hi @DmitryPorotov 
Use the opacity instead.

Demo:
- http://jsfiddle.net/BlackLabel/e6tet0ju/

The second solution is setting rgba() as color
- http://jsfiddle.net/BlackLabel/qzL0gkfs/

**Comment by DmitryPorotov** [comment]
`opacity` and `color` don't affect the area fill color at all. But `fillColor: 'rgba(255, 0, 0, 0.2)'` works well.
http://jsfiddle.net/e6tet0ju/1/

**Comment by pawelfus** [comment]
Hi @DmitryPorotov 

Thank you for the info. You are right, `fillColor` doesn't work with `fillOpacity`, see [`fillOpacity`](https://api.highcharts.com/highcharts/plotOptions.area.fillOpacity) docs:

> Fill opacity for the area. When you set an explicit `fillColor`, the `fillOpacity` is not applied. Instead, you should define the opacity in the `fillColor` with an rgba color definition. The `fillOpacity` setting, also the default setting, overrides the alpha component of the `color` setting.
