### ISSUE TITLE
JS API site has extraneous horizontal scrollbar

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#7785]
The documentation site https://api.highcharts.com/highcharts/ has a horizontal scrollbar both in Chrome and Firefox.

The scrollbar is shorter on https://api.highcharts.com/class-reference, but it's still of no real use.

**Comment by sebastianbochan** [comment]
Hi @dandv 
Thank you for reporting.

_Internal note:_ 
- https://api.highcharts.com/highcharts/
The reason of the probelm is setting padding-left:15% and width as 100%. The width should be 85%.
