### ISSUE TITLE
Title alignment incorrect when useHTML is enabled in release 6.0.5 

### ISSUE THREAD

**Issue by wonderboyjon** [highcharts/highcharts#7787]
#### Expected behaviour
Title alignment with `useHTML: true` should be the same as it is when using `useHTML: false`, as it was in release 6.0.4.

#### Actual behaviour
Title is not aligned centrally when the graph is loaded, and calling `reflow()` doesn't seem to fix it either.

#### Live demo with steps to reproduce
Initialise a chart (doesn't seem to matter which type) , ensuring that the `title: { useHTML: true }` option is set. Having a long graph title helps to make the issue more obvious (though isn't required). When the graph is loaded, you'll see that the title is not aligned properly/centrally.

Working version (on 6.0.4):
[Fiddle](http://jsfiddle.net/07ew41zt/3/)

Broken version (on 6.0.5):
[Fiddle](http://jsfiddle.net/07ew41zt/4/)

#### Product version
Highcharts version 6.0.5

#### Affected browser(s)
Chrome (tested on v64.0.3282.140)
Firefox (tested on v58.0.1)
Edge
IE 11

**Comment by pawelfus** [comment]
Hi @wonderboyjon 

Thank you for reporting the issue.

*Internal note:*
It's a regression after 6bf7ff5c8 @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Simplified demo: http://jsfiddle.net/tovzk88u/13/

**Comment by srinidhikrishnan** [comment]
how to fix this issue..Also reflecting in 5.0.14
