### ISSUE TITLE
Given several plotBands along xAxis, what's the best way to know which one that user clicked.  ('click' event of plotBand doesn't give xAxis info)

### ISSUE THREAD

**Issue by bfang711** [highcharts/highcharts#7789]
Using the following piece of code, I want to add a plotBand at runtime and access its `e.xAxis[0].value`.  

`xAxis.addPlotBand({ 
              from:..., 
              to: ..., 
              events:{
                   click: function(e) {
                             console.log(e); 
                             console.log(e.hasOwnProperty('xAxis');}
}})`

However as you can see from the following picture, even if I see `xAxis` present in the `MouseEvent` object, `e.hasOwnProperty('xAxis')` returns `false`. Can someone let me know why?

Please check the error in this picture
![image](https://user-images.githubusercontent.com/13139744/35762857-0b4cd3de-086d-11e8-8a50-839cba9a67ad.png)

If I expand `xAxis` property from the console, the xAxis[0].value does give correct value. But how can I get the value from plotBand "click" event, not chart "click" event? (I want to click on the plotBand, not the whole chart.)  or any other possible work around, pls let me know. 

thank you very much

**Comment by bfang711** [comment]
I found the reason why Chrome console misleading. Here is an explanation. 
https://stackoverflow.com/questions/17546953/cant-access-object-property-even-though-it-exists-returns-undefined

So when I run `console.log(Object.keys(e))` for "click" callback of **plotBand**. I get  
![image](https://user-images.githubusercontent.com/13139744/35762917-8286a794-086e-11e8-9cfc-5878e32978f2.png) only.
However if I run  `console.log(Object.keys(e))` for "click" callback of **chart**. I get 
![image](https://user-images.githubusercontent.com/13139744/35762921-9d664af6-086e-11e8-8c45-233a4220bce0.png), including xAxis & yAxis.

Now my question is that is there any work around solution to get xAxis from plotBand's "click". or at least ID of that plotBand.  (I do have several plotBands along the X axis. and I would like to know which one user clicked. )

thank you.

**Comment by bfang711** [comment]
This is the case for plotLine as well. And this makes all events, `click, mousemove, mouseout` have no practical use at all by clicking plotLine/plotBand. 

Can someone help with this? thank you.

**Comment by pawelfus** [comment]
Hi @bfang711 

Thanks for contacting us. In general, we use github as bug reports, so if you have questions, please contact with our support: https://www.highcharts.com/support

Just to answer your question: in a plotLine event, `this` refers to plotLine, so you can get options like this: `this.options`, for `id` it's `this.options.id` of course. There's no such option like `e.xAxis[0].value` in the plotBand event. `chart.events.click` and `plotBand.events.click` are not the same events.
