### ISSUE TITLE
Bar chart, UI issues with boost enabled

### ISSUE THREAD

**Issue by alirezameftahi71** [highcharts/highcharts#7791]
#### Scenario
We experienced UI issues with highcharts of type 'bar' and boost enabled. 
The right side of the chart is flat and won't show up correctly until we zoom in multiple times.

#### Expected behaviour
To see the bars correctly and not flat

#### Actual behaviour
We get this:
![2](https://user-images.githubusercontent.com/31916958/35777646-dd8b6554-09c6-11e8-9ed1-33523fa18eb1.PNG)

#### Live demo with steps to reproduce
See the example and just zoom in a few times, you'll see the problem we're facing.
https://jsfiddle.net/alinux7/74aw7c96/4/

#### Product version

Highcharts v6.0.5

#### Affected browser(s)
Tested on Chrome

**Comment by KacperMadej** [comment]
Thank you for reporting.

More visible when extremes are set for yAxis: https://jsfiddle.net/BlackLabel/74aw7c96/5/

**Comment by TorsteinHonsi** [comment]
More reliable with fixed width: https://jsfiddle.net/74aw7c96/6/

The clipping rectangle is the problem, it must be adjusted for `chart.inverted`.

**Comment by cvasseng** [comment]
Fixed, and pending merging: https://github.com/highcharts/highcharts/pull/7922

Demo of fix: https://jsfiddle.net/xms6cofa/

**Comment by pawelfus** [comment]
Issue was fixed in version 6.1.0, demo: https://jsfiddle.net/BlackLabel/1ohaw60d/
