### ISSUE TITLE
Bar Chart UI issue - chart goes under legend when zooming with boost enabled

### ISSUE THREAD

**Issue by alirezameftahi71** [highcharts/highcharts#7792]
#### Scenario
When using bar chart with boost enabled, 
**If we set the `boostThreshold` OR `seriesThreshold` manually,**
after zooming in, the chart kinda goes under the legend and the X-Axis of the chart. See the pic.
#### Expected behaviour
We expect to be able to set the `boostThreshold` manually (For example 500) and still get the correct functionality. 

#### Actual behaviour
We see this: 
![1](https://user-images.githubusercontent.com/31916958/35777716-e642e518-09c7-11e8-90ea-4260e00b1309.PNG)

#### Live demo with steps to reproduce
https://jsfiddle.net/alinux7/yj9x4yan/9/
NOTE: I was just testing some values for boostThreshold, and I kinda think if you set any value less than 620, you'll face this problem. When I set boostThreshold anything greater than 620 I have NO problem.

#### Product version
Highcharts v6.0.5

#### Affected browser(s)
Tested on Chrome

**Comment by sebastianbochan** [comment]
Hi @alirezameftahi71 
Thank you for reporting.

@cvasseng

**Comment by TorsteinHonsi** [comment]
It's basically the same bug as #7791 - the clipping rectangle is not taking `chart.inverted` into account.

**Comment by alirezameftahi71** [comment]
Hi. So is there a fix for this?

**Comment by cvasseng** [comment]
Fixed, and pending merging: https://github.com/highcharts/highcharts/pull/7922

Demo of fix: https://jsfiddle.net/x4zu58yb/

**Comment by pawelfus** [comment]
Issue was fixed in v6.1.0: https://jsfiddle.net/BlackLabel/mtao53sy/
