### ISSUE TITLE
how to render a rect with shadow?

### ISSUE THREAD

**Issue by king-king** [highcharts/highcharts#7794]
i use chart.renderer.rect to generate a rect . i want it has shadow,i has tryfilter: 'url(#drop-shadow)',and i read this(https://www.highcharts.com/docs/chart-design-and-style/gradients-shadows-and-patterns),but i failed at last.i want to know how to make it

**Comment by sebastianbochan** [comment]
Hi @king-king 
Github is our bug tracker, so for general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.
