### ISSUE TITLE
All browsers crashes when highcharts tries to render 100+ serieses data points

### ISSUE THREAD

**Issue by Lir10** [highcharts/highcharts#7796]
This code below works perfectly for up to 100 serieses but crashes (browser freezes)  when it's above

Here is how i build the data:

```
var tmp_array = []
total = 100;
for (var i=0;i<total;i++) {
                    var room_name = received_msg[i]["Location"];
                    var tmp = {
                        name: room_name,
                        data: [[start_time, index_of_room_name], [end_time, index_of_room_name]],
                    };
                    tmp_array.push(tmp);
                }
vm.chartConfig.series = tmp_array;
```
I can't use this library if it can't build a graph out of simple 100+ serieses

**Comment by TorsteinHonsi** [comment]
100 data points is usually no problem, and with the Boost module you can render millions. Can you recreate your problem chart in jsFiddle?

**Comment by Lir10** [comment]
@TorsteinHonsi Will try - it's 100 serieses with 2 data points on each series

**Comment by sebastianbochan** [comment]
I created a simple demo of chart: 
- http://jsfiddle.net/BlackLabel/8L6ach3r/

Browser: Chrome 64.0.3282.140

Unfortunately I was not able to replicate the problem, could you supply us more details (browser version, OS) ?

**Comment by Lir10** [comment]
@sebastianbochan Thanks for the response. i have tried to repreduce the issue on fiddle but couldn't. 

I'm using this library with angularjs and ng-highcharts

is it possible that this causing the issue?

**Comment by sebastianbochan** [comment]
Hi @Lir10 
I am not still able to replicate.

Demo with highcharts-ng:
- https://jsfiddle.net/BlackLabel/vws1v48h/

Please update my demo with your simplified code for the further debugging.

**Comment by Lir10** [comment]
@sebastianbochan I have updated the file but can't see the graph

**Comment by Lir10** [comment]
@sebastianbochan Looks like it does work (needed to add bootstrap.js) : https://jsfiddle.net/vws1v48h/10/
I still don't understand what's the difference in my code.

I'm updating the graph when i receive the data from the server and if it's above 100 the browser freezes

**Comment by Lir10** [comment]
@TorsteinHonsi @sebastianbochan I have repreduce the problem with large data set. found out that this line : `$scope.chartConfig.series = series;` is causing the problem

any ideas?

That's the fiddle: https://jsfiddle.net/vws1v48h/10/

**Comment by sebastianbochan** [comment]
Hi @Lir10 
When I run the demo https://jsfiddle.net/vws1v48h/10/ all worked properly. Which browser do you use ?

**Comment by Lir10** [comment]
@sebastianbochan Try to run it with maxseries = 2000 tried it on chrome and firefox and browser got stuck

**Comment by pawelfus** [comment]
Hi @Lir10 

Just tested with 2000, it works fine (latest chrome+osx). Just a few notes:

- Your example throws errors in the console about unsorted data, please sort your data, for example: https://jsfiddle.net/BlackLabel/vws1v48h/12/ (just changed how x-values are generated)
- Are you sure you need to render 2000+ series? Your chart looks like x-range series type, compare performance:
  - https://jsfiddle.net/BlackLabel/vws1v48h/13/ (~300ms, 200 series with two points each)
  - https://jsfiddle.net/BlackLabel/vws1v48h/14/ (~100ms, 200 points, each based on two points)
  Increasing number to 1000:
  - https://jsfiddle.net/BlackLabel/vws1v48h/16/ (~1200ms, 1000 series, line series)
  - https://jsfiddle.net/BlackLabel/vws1v48h/15/ (~150ms, one series, 1000 points)

As you can see, increasing number of series is not the best idea, simply each series generates more elements in the DOM than a simple point. I think the browser freeze issue is connected to your hardware, if you add watchers from angular your app will start consuming even more RAM (especially in Chrome ;) ).

**Comment by Lir10** [comment]
Hi @pawelfus 
Thanks so much for the informative response.

Your last fiddle looks promising i will give it a shot

**Comment by Lir10** [comment]
@pawelfus @TorsteinHonsi @sebastianbochan Looks like @pawelfus  last fiddle solved the problem. Thanks alot!

**Comment by RonjaKnudtsen** [comment]
I dont know if this helps anyone, i struggled with too many series, and came across this bug thread. And for me disabling the boost module which i had imported and used on other charts was my fix.

**Comment by Maulik009** [comment]
It's an open issue. Don't close it. When I am using version 6 that time all browsers are crashes frequently and it's not fixed yet by highchart team for version 6. Better ti use version 7.

**Comment by KacperMadej** [comment]
@Maulik009 
It's a closed issue. Closed for over 1 year.
If version 7 works and 6 is broken, then the code was fixed in version 7 and solution is to upgrade Highcharts.

If you need version 6 to work in this case then please recreate the problem in a simple demo and contact [technical support](https://www.highcharts.com/blog/support/) - they might be able to provide you a solution other than to upgrade Highcharts.

**Comment by Maulik009** [comment]
Yes I know that if we use version 7 then it's working fine but I want to use only highchart version 6. Thanks for the updates @KacperMadej . Will contact technical support team.
