### ISSUE TITLE
Axis values for Sankey Chart

### ISSUE THREAD

**Issue by shabala** [highcharts/highcharts#7797]
#### Expected behaviour
Is there any way to add the values of 'from', 'to' and 'weight' in a Sankey chart as an axis?  Eg, Countries -> Countries: Distance would denote a sankey chart that maps the distance between countries - therefore Countries would be placed along the x-axis and Distance along the y-axis.

#### Actual behaviour
Currently, there is no such option available.

**Comment by KacperMadej** [comment]
Hi,

We are keeping github for bugs.

Please contact technical support for help.
I cannot imagine the chart based on your description - please add an image.
https://www.highcharts.com/support

Or you could suggest an idea on userVoice for an enhancement suggestion.
https://highcharts.uservoice.com/forums/55896-general
