### ISSUE TITLE
IE11 + compatibility mode (IE 7 and 5): hover error

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7800]
#### Behaviour
When running Highcharts chart in IE11 + compatibility mode (IE 7 and 5) a critical error is thrown on point hover. `_defaultGetter` get's `stoke` value that is an object and it doesn't support [the regex check done later](https://github.com/highcharts/highcharts/blob/0f24c64ed3558986a0cdef4138a6673d098668eb/js/parts/SvgRenderer.js#L1694).

#### Live demo with steps to reproduce
```html
<html> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
        <title>Highcharts Example</title> 
        <!-- 1. Add JavaScript in the head of the page --> 
        <script src="https://code.highcharts.com/highcharts.src.js"></script>
        <script src="https://code.highcharts.com/modules/oldie.src.js"></script>
        <script src="https://code.highcharts.com/modules/sankey.src.js"></script>
        <script src="https://code.highcharts.com/modules/exporting.src.js"></script>
    </head>

    <body>
        <div id="container" style="width: 600px; height: 400px;"></div>

        <script>
          Highcharts.chart('container', {
            series: [{
              data: [1,2,3]
            }]
          });
        </script>
    </body> 
</html> 
```

#### Affected browser(s)
IE11 + compatibility mode (7 & 5)

**Comment by zlateskud** [comment]
The issue is present on **Sankey Diagram**

I attach the code

![highcharts error](https://user-images.githubusercontent.com/7415552/36095225-f7313db0-0ff9-11e8-9d40-2986830c9b1b.jpg)


[sankey_test.zip](https://github.com/highcharts/highcharts/files/1716143/sankey_test.zip)

**Comment by pawelfus** [comment]
Hi @zlateskud - issue should be fixed on our master branch, could you test it? http://github.highcharts.com/highcharts.src.js

**Comment by zlateskud** [comment]
hi @pawelfus - we have same error with version from git

**Comment by KacperMadej** [comment]
@zlateskud 
The oldie.js module should be loaded from the github.

```
        <script src="https://github.highcharts.com/highcharts.src.js"></script>
        <script src="https://github.highcharts.com/modules/oldie.src.js"></script>
        <script src="https://github.highcharts.com/modules/sankey.src.js"></script>
        <script src="https://github.highcharts.com/modules/exporting.src.js"></script>
```

I have tested this and the error is not visible.

**Comment by zlateskud** [comment]
@KacperMadej 
Hi,
Hover is ok, thanks..
I tried to click, but the event does not work.
Thanks.

![err button](https://user-images.githubusercontent.com/7415552/36106045-e776ed1e-101e-11e8-8ad2-e6f500763d40.jpg)

**Comment by KacperMadej** [comment]
Ok, but this is a different error. New issue here: https://github.com/highcharts/highcharts/issues/7850
