### ISSUE TITLE
yAxis.stackLabels.style.visibility is not described in documentation

### ISSUE THREAD

**Issue by UristMcKerman** [highcharts/highcharts#7801]
Hello, I was developing percentage stacked column chart, and apparently when I set yAxis.max to 100, the stack labels disappear completely (which is an issue on its own), and there was no fix in sight, except manually setting it to visible in JS after chart being drawn. But then I tried that 'visibility' option (I literally had no clue it would work). And surprisingly it worked!

#### Expected behaviour
yAxis.stackLabels.style.visibility is described in documentation

#### Actual behaviour
yAxis.stackLabels.style.visibility is not described in documentation

#### Live demo with steps to reproduce
https://jsfiddle.net/43aa0tq8/
Stack labels are visible, but they will disappear if line 27 commented

#### Product version
Latest

#### Affected browser(s)
Chrome 63.0.3239.132 (Windows 7)

**Comment by sebastianbochan** [comment]
Hi @UristMcKerman 
Thank you for contacting us.
Labels (stackLabels and dataLabels) are cropped by default. You can disable it by the option.

Demo:
- https://jsfiddle.net/BlackLabel/v6bjs4pv/
