### ISSUE TITLE
Select states for Box and Whisker Chart

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#7803]
#### Expected behaviour
Please support select state options for box and whisker chart.

#### Actual behaviour
Currently, boxplot series do not have select state options.

#### Live demo with steps to reproduce
http://jsfiddle.net/sq4w7co2/

#### Product version
6.0.6

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @sagargurtu 

Thanks for your suggestion. You are right, `states` are not supported by `boxplot` series. Closing as duplicate of #2340
