### ISSUE TITLE
Map Navigation line graph. Is there an option to zoom out of boundaries?

### ISSUE THREAD

**Issue by mustafaibrahim989** [highcharts/highcharts#7809]
#### Expected behaviour

I should be able to zoom out after setData and redraw.

#### Actual behaviour

No more zoom out is allowed after setDate.
When I zoom in, I reset the data then when I try to zoom out I can't.
I think it's because the boundaries of the chart are set with the min/max of the new data ranges.

#### Product version
Highcharts, Highmaps 

#### Affected browser(s)
Any browser

**Comment by pawelfus** [comment]
Hi @mustafaibrahim989 

Thank you for reporting the issue. Could you recreate this in jsFiddle? I'm not sure if I understand correctly the part with zooming in and setting new data. Is that necessary? If map changes with new boundaries, then where should we zoom out? Did you consider drilldown solution, like in this demo: https://www.highcharts.com/maps/demo/map-drilldown ?

**Comment by KacperMadej** [comment]
Hi @mustafaibrahim989 

Please add a live demo for the issue.

**Comment by mustafaibrahim989** [comment]
Hi @pawelfus Please find this demo [https://jsfiddle.net/highcharts/9rwe76gx/](url). 

Everytime I zoom in I get the range from setExtremes and reload the point from backend. how I can zoom out?

**Comment by pawelfus** [comment]
Hi @mustafaibrahim989 

Thank you for the details! In that case I suggest to use Highstock, here you can find and article how to implement lazy-loading: https://www.highcharts.com/blog/news/48-loading-millions-of-points-in-highcharts/
