### ISSUE TITLE
Highcharts reflow not happend to x-axis

### ISSUE THREAD

**Issue by ipip2005** [highcharts/highcharts#7814]
#### Expected behaviour
x-axis is reflowed when calling chart.reflow()

#### Actual behaviour
x-axis is not reflowed properly when calling chart.reflow()

#### Live demo with steps to reproduce
http://jsfiddle.net/644syxw3/

1. Click 'Toggle' and 'Reflow' several times.

![image](https://user-images.githubusercontent.com/7711735/35902334-c99d1c3a-0c15-11e8-9d6e-96f421c706b9.png)

#### Product version
5.0.13

#### Affected browser(s)

Chrome

**Comment by KacperMadej** [comment]
Hi @ipip2005 

Thank you for reporting.

The problem is also visible in the current (6.0.6) and github code version.

**Comment by pawelfus** [comment]
**Workaround:**
Reflow title manually on redraw/load chart events: http://jsfiddle.net/BlackLabel/644syxw3/6/

```javascript
function resizeTitle(axis) {
  axis.axisTitle.css({
    width: axis.len
  });
}

var chart = Highcharts.chart('container', {
  chart: {
    events: {
      load: function() {
        resizeTitle(this.xAxis[0]);
      },
      redraw: function() {
        resizeTitle(this.xAxis[0]);
      }
    }
  },
  ...
});
```

*Internal note:*
In the demo above, when rendering title, `axis.pos` equals `380`, but after chart is fully rendered, this `axis.pos` is equal to `319`. Missing 61pixels are later added to `chart.plotLeft`, so I assume it's space needed by yAxis title and labels. Auto-wrapping xAxis title was added in 321e0257d commit.

**Comment by ipip2005** [comment]
Closed the issue by accident, reopened it now.

Thanks for the workaround!
