### ISSUE TITLE
Donut pie for highcharts.net missing inner circle

### ISSUE THREAD

**Issue by Datarmanatar** [highcharts/highcharts#7816]
#### Expected behaviour

Should be a inner circle in the same way it is for normal Highcharts

#### Actual behaviour

Missing the circle in the middle

#### Live demo with steps to reproduce

http://dotnet.highcharts.com/Highcharts/Demo/Gallery?demo=PieDonut&theme=default

#### Affected browser(s)
Chrome
Internet Explorer

**Comment by pawelfus** [comment]
Hi @Datarmanatar 

Thank you for reporting the issue. It's a mistake in this line: `chart.series[0].setData(versionsData);` - it should be `chart.series[1].setData(versionsData);`.

**Comment by pawelfus** [comment]
Fixed.
