### ISSUE TITLE
bug in drilldown

### ISSUE THREAD

**Issue by smj-hosseini** [highcharts/highcharts#7817]
There seems to be a problem in the drilldown module after destroying and re-initialising the chart. This occurs when a drilldown series in the new chart existed in the previous chart.
highcharts team said this bug was fixed but i test drilldown and still not working

**Comment by pawelfus** [comment]
Hi @smj-hosseini 

Could you follow our instruction when reporting the bug? It would be great to know:

- Highcharts version
- browser name(s) and version
- jsfiddle demo with the issue

I know it's a follow up from #3990 - but demo posted there works fine: http://jsfiddle.net/BlackLabel/dxdzdw5q/2/

**Comment by smj-hosseini** [comment]
hi pawelfus,

    Highcharts version: Highcharts JS v6.0.6 (2018-02-05)
    browser name(s) and version: firefox quantum 58.0.1(64bit) 
i used currently highcharts and drilldown version but this not work
go to this jsfiddle link and follow the below steps to see the bug:
 http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/column-drilldown/
first: click on "microsoft internet explorer" bar and go back,
second: click on "safari" bar, and now you see this bug
thanks & good luck

**Comment by pawelfus** [comment]
Hi @smj-hosseini 

Thank you for the details! Just tested with the same firefox version, osx, and this is how it works me:

![7y8mnrq0hv](https://user-images.githubusercontent.com/1453926/35924644-dfe9829a-0c23-11e8-8d44-7a3b46571ec0.gif)

**Comment by smj-hosseini** [comment]
thanks men!
my issue is after click on "safari" bar there is a extra and unusable data on "safari" chart. this extra data mark as '4' on x-axis that not in data series for "safari" chart.
how to prevent of showing this extra data?

**Comment by pawelfus** [comment]
Thank you for the explanation, I was paying attention to the bug you reported in #3990 - but it's actually something different. You are right there shouldn't be extra category "4" when drilling down second time.

It's a regression since v6.0.5, v6.0.4 works fine: http://jsfiddle.net/BlackLabel/4ehmx54k/

*Internal note:*
Regression after 652e11b5b commit.

**Comment by smj-hosseini** [comment]
Tank you very much pawelfus,
Yes, highcharts v6.0.4 works fine,
thanks again for your help and fast replying

**Comment by smj-hosseini** [comment]
hello again,
i faced again this problem, i have to ues both highcharts and highstock in my project. after googling and based on highcharts doc i realized that i should import only highstock to my project.
but when i import only highstock, the problem go back!!
i tested with a older highstock version but this trick not work.
jsfiddle link: http://jsfiddle.net/cjjm3xjL/

**Comment by pawelfus** [comment]
v6.0.4 looks fine: http://jsfiddle.net/BlackLabel/cjjm3xjL/3/

**Comment by smj-hosseini** [comment]
yes, it works
thanks
