### ISSUE TITLE
Null series causing connectNull and marker colour issues

### ISSUE THREAD

**Issue by NeuwenWolf** [highcharts/highcharts#7820]
#### Expected behaviour
http://jsfiddle.net/ernmhuxL/

#### Actual behaviour
http://jsfiddle.net/ernmhuxL/1/

#### Live demo with steps to reproduce
http://jsfiddle.net/ernmhuxL/2/
It seems that if a series is entirely null, it colors all subsequent series markers with its own colour.
It also connects the end of one series, to the start of the next (with its line color).
In this demo, series 1 and 2 are null.
Toggle series 2 to see the lines and markers take series 1s colour.

The null series must be first to cause the issue.
In this demo, the null series are series 3 & 4.  Toggle series 1 and 2 off to see the issue:
http://jsfiddle.net/ernmhuxL/4/

#### Product version
Regression since 6.0.6, 6.0.5 works mostly fine.
I say mostly fine because 6.0.5 draws a single marker for the null series at 0,0 like so:
![image](https://user-images.githubusercontent.com/12142465/35930971-a36d705c-0bf0-11e8-97ca-8cec583acf1d.png)

#### Affected browser(s)
tested in chrome

Edit:
I forgot to mention that this affects boosted series only.

**Comment by KacperMadej** [comment]
Hi @NeuwenWolf 

Thank you for reporting about the problem.
It's a boost issue @cvasseng
