### ISSUE TITLE
Follow up on #7288

### ISSUE THREAD

**Issue by willifordj** [highcharts/highcharts#7821]
In a previous support request (Scatter chart tooltip limit? #7288) you suggested a different way to format the tooltip so that it would be compatible with boost mode:

“The problem in your tooltip comes from this logic in the formatter:
this.series.options.extra[this.series.data.indexOf(this.point)]
In boost mode, this.point is a mock point object created just for the tooltip, so it is not part of the this.series.data array. Instead of having the extra array as a parallel array to the data, I would recommend you to index it by the x values so you can look up directly, something like this:
this.series.options.extra[this.point.x]”
We have be unsuccessful in getting this implemented.  Can you provide corrections to the syntax in jsfiddle http://jsfiddle.net/adkkqkwm/27/? The upper chart shows expected tooltip. The lower was an attempt to implement the suggested syntax but does not display “extra” content

**Comment by pawelfus** [comment]
Hi @willifordj 

Your `extra` arrays structure is wrong, it should be more like this: http://jsfiddle.net/BlackLabel/adkkqkwm/28/ (can be also an object, where indexes are keys). 

If you find any other issues with this implementation, please contact with our support. We use github tickets as bug reports, not as support tickets. Thank you.
