### ISSUE TITLE
Highcharts has random gradient bar appear legend

### ISSUE THREAD

**Issue by ashok-sc** [highcharts/highcharts#7822]
#### Expected behaviour
Only show items in legend related to actual lines in chart.

#### Actual behaviour
Gradient bar appears in legend that has no correlation to anything. This also only appears on our production servers. Does not appear when I'm testing locally. 

See gradient bar in bottom of image here:
![screen shot 2018-02-07 at 1 38 14 pm](https://user-images.githubusercontent.com/32855087/35942905-32923d1a-0c0c-11e8-8617-255c0ff4738f.png)

#### Live demo with steps to reproduce
N/A 

This is only happening when we push to our AWS instances. Testing locally I can't reproduce this issue.

#### Product version
"react-highcharts": "15.0.0",
"@types/highcharts": "5.0.15",
"highcharts": "6.0.4",
"highcharts-boost": "0.1.7",

#### Affected browser(s)
ALL OF THEM

**Comment by ashok-sc** [comment]
This is what I'm seeing when I inspect this element:

`<g class="highcharts-legend-item highcharts-undefined-series highcharts-color-undefined" transform="translate(8,3)"><rect x="0" y="4" width="200" height="12" fill="url(#highcharts-20gduvf-146)"></rect><g class="highcharts-grid highcharts-coloraxis-grid "></g><text x="21" style="color:#333333;font-size:12px;font-weight:bold;cursor:pointer;fill:#333333;" text-anchor="start" y="15"></text><g class="highcharts-axis highcharts-coloraxis "><path fill="none" class="highcharts-axis-line" d="M 0 16 L 200 16" visibility="hidden"></path></g><g class="highcharts-axis-labels highcharts-coloraxis-labels "></g></g>`

**Comment by pawelfus** [comment]
Hi @ashok-sc 

Could you show your config? It would be the best to recreate issue in jsFiddle. In general, this gradient-bar is [`colorAxis`](https://api.highcharts.com/highcharts/colorAxis). That suggests you have different config locally vs production, or different files are loaded. I would start with looking for `colorAxis` options in your configs.

**Comment by ashok-sc** [comment]
Hey @pawelfus thanks for the hint! This is indeed the problem, but it's really weird because locally none of my configs have `colorAxis`, but once deployed to our AWS instance I'm seeing `colorAxis` on the config. Have you seen anything like this? Super weird, but I'll continue investigating.

**Comment by ashok-sc** [comment]
Looks like this is an issue with our webpack and typescript compiler. Really not sure what's different in these environments, but either way this is not an issue with highcharts. Thanks for your help!
