### ISSUE TITLE
Highstock Technical Indicator, data grouping issues.

### ISSUE THREAD

**Issue by Nuadnoi** [highcharts/highcharts#7823]
#### Expected behaviour
I would like to group the data with ohlc chart including technical indicator ex. MACD or any indicators. It's not grouping as usual. But if I have only ohlc chart, It can be grouping the data.

#### Actual behaviour
Chart data are not grouping when there are one or more technical indicators.
Problems on grouping data with
- week
- month
- year

#### Live demo with steps to reproduce
http://jsfiddle.net/nuadnoi/0uvfw4za/ --- with week parameter data grouping and including MACD indicator.
http://jsfiddle.net/nuadnoi/0uvfw4za/1/ ---  with week parameter data grouping and excluding MACD indicator.

I'm not sure what i'm missing. Thank you

**Comment by pawelfus** [comment]
**Workaround:**

Set `dataGrouping.approximation` and `dataGrouping.groupPixelWidth` in the indicator config: http://jsfiddle.net/BlackLabel/0uvfw4za/5/

```javascript
series: [{
  type: 'ohlc',
  id: 'aapl',
  name: 'AAPL Stock Price',
  data: data
}, {
  yAxis: 1,
  type: 'macd',
  linkedTo: 'aapl',
  dataGrouping: {
    approximation: 'averages',
    groupPixelWidth: 10
  },
  params: {
    shortPeriod: 12,
    longPeriod: 26,
    signalPeriod: 9,
    period: 26
  }
}]
```

**Comment by Nuadnoi** [comment]
Hi @pawelfus , 

Thank you very much.
