### ISSUE TITLE
Polar chart render wrong when twice require highcharts-more

### ISSUE THREAD

**Issue by xcqwan** [highcharts/highcharts#7832]
#### Actual behaviour
Polar chart will render wrong when twice require highcharts-more

#### Live demo with steps to reproduce

twice require: http://jsfiddle.net/b1f1LxaL/1/
once require: http://jsfiddle.net/b1f1LxaL/2/

**Comment by sebastianbochan** [comment]
Hi @xcqwan 
    Thank you for contacting us. You should not load highcharts (core or modules) more than one time. It is described by the error [#16](https://www.highcharts.com/errors/16) returned in your console.

**Comment by xcqwan** [comment]
@sebastianbochan what's happened with one more time require highcharts-more.js?

**Comment by KacperMadej** [comment]
@xcqwan Related issue #7729.

If you would like to propose an enhancement idea for a checker that will do nothing on an attempt of loading an already loaded module please open an idea on userVoice of vote for the already registered one if it already exists. The most popular ideas are getting implemented.
highcharts.uservoice.com/forums/55896-general
