### ISSUE TITLE
Plot Band colors with alpha channel on Samsung Internet

### ISSUE THREAD

**Issue by adriangaro** [highcharts/highcharts#7838]
#### Expected behaviour
Plot lines and Plot bands should have the specified color code(has alpha channel).

#### Actual behaviour
All plot lines and bands are black on Samsung Internet

#### Live demo with steps to reproduce
https://jsfiddle.net/me0b1wyf/

#### Product version
Highstock 6.0.4

#### Affected browser(s)
Samsung Internet

**Comment by pawelfus** [comment]
Hi @adriangaro 

Thank you for reporting the issue. This is problem with a browser, not Highcharts, `#rrggbbaa` is not supported by Samsung Internet: https://caniuse.com/#feat=css-rrggbbaa

Standalone example (Highcharts not included): https://jsfiddle.net/BlackLabel/me0b1wyf/2/
