### ISSUE TITLE
Logarithmic setting overriden by datetime in highstock

### ISSUE THREAD

**Issue by manu-st** [highcharts/highcharts#7842]
#### Expected behaviour
Preserve the `type` field specified when creating the chart.

#### Actual behaviour
The `type` property is overridden to be `datetime`, see https://github.com/highcharts/highcharts/blob/master/js/parts/StockChart.js#L178

#### Live demo with steps to reproduce
None, but simply create a chart with a xAxis whose type is `logarithmic`.

#### Product version
Using 6.0.4

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @manu-st 

In Highstock, only `datetime` xAxis is available, you can't change type: https://api.highcharts.com/highstock/xAxis (no `type` option). 

If you want to use `logarithmic`  xAxis, then use `Highcharts.chart()` constructor.

**Comment by manu-st** [comment]
Is there a reason for not having this option? If I override the code myself to remove the setting, it seems to work just fine.

**Comment by TorsteinHonsi** [comment]
Highstock is all about datetime - the range selector, navigator, data grouping, everything is there for navigation long time series. So using a logarithmic X axis would break those elements, so you may as well use a vanilla Highcharts constructor.
