### ISSUE TITLE
Bizarre Grouping Behavior

### ISSUE THREAD

**Issue by holtc** [highcharts/highcharts#7843]
#### Expected behaviour
I should be able to set the color of the individual grouped data points when the chart is redrawn after grouping

#### Actual behaviour
Seems pretty random.  Sometimes the points have the correct colors, other times they do not, and yet others the color is correct once the point is hovered over.

EDIT:  Seems to have at least something to do with custom range selectors and forced data grouping, as this [fiddle](http://jsfiddle.net/holtc/m5zjnd27/) has a fix, but this [fiddle](http://jsfiddle.net/holtc/0v8f80dh/) uses custom range selectors, and the previous fix does not work.  

EDIT2: May also have something to do with the chart.render() function.  If you call this at the end of the redraw() function, then the correct volume colors will not show on hover.  [Fiddle](http://jsfiddle.net/holtc/jzmbv80c/) here.

#### Live demo with steps to reproduce
http://jsfiddle.net/x4gy675f/

#### Product version
Highstock 6.0.6

#### Affected browser(s)
At least Chrome

**Comment by KacperMadej** [comment]
Hi @holtc 

The coloring you are trying to perform is based on custom code. There's no such feature (for now at least) to set color options for the grouped points, so this could be a feature request and for those we are using [userVoice](https://highcharts.uservoice.com/forums/55896-general).

This is not a bug. For technical support please use any other support channel.
https://www.highcharts.com/support
