### ISSUE TITLE
Description for plotOptions.pie.dataLabels.distance is missing in API reference

### ISSUE THREAD

**Issue by Freywar** [highcharts/highcharts#7848]
[plotOptions.pie.dataLabels.distance](https://api.highcharts.com/highcharts/plotOptions.pie.dataLabels.distance) entry does not exist in API reference. The link is the first result from ["dataLabels.distance" search](https://www.google.fi/search?q=dataLabels.distance&oq=dataLabels.distance&aqs=chrome..69i57j69i60l2j0l2.302j0j9&sourceid=chrome&ie=UTF-8) by Google, there are [demos](https://www.highcharts.com/demo/pie-semi-circle) using the property with the latest HC version and I did not find anything about it in changelogs, so I guess it existed recently and is not removed or deprecated. 

It's not a bug of Highcharts themselves, so I'm not sure what would be the best place to report it, excuse me if this is not the one.

**Comment by TorsteinHonsi** [comment]
It's fixed as of today, thanks!
