### ISSUE TITLE
IE11 + compatibility mode (IE 7): onContainerMouseDown doesn't pass event and causes an error

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7850]
#### Behaviour
IE11 + compatibility mode (IE 7): 
onContainerMouseDown doesn't pass event and causes an error

#### Live demo with steps to reproduce
```
<html> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
        <title>Highcharts Example</title> 
        <!-- 1. Add JavaScript in the head of the page --> 
        <script src="https://github.highcharts.com/highcharts.src.js"></script>
        <script src="https://github.highcharts.com/modules/oldie.src.js"></script>
        <script src="https://github.highcharts.com/modules/exporting.src.js"></script>
    </head>

    <body>
        <div id="container" style="width: 600px; height: 400px;"></div>

        <script>
          Highcharts.chart('container', {
            series: [{
              data: [1,2,3]
            }]
          });
        </script>
    </body> 
</html> 
```

Steps:
1. click on the chart
2. error

#### Affected browser(s)
IE11 + compatibility mode (IE 7)

**Comment by KacperMadej** [comment]
Event is not passed and it's resolved for e.g. `H.addEvent` or `pointer.normalize`. Normalizing before accessing any event properties resolves the problem.

I'll fix the reported issue and I am adding this comment for reference for potential, further, related issues.

**Comment by KacperMadej** [comment]
@zlateskud
Fix suggested, please test with the code loaded as:
```
        <script src="http://github.highcharts.com/5a83eb3/highcharts.src.js"></script>
        <script src="http://github.highcharts.com/5a83eb3/modules/oldie.src.js"></script>
        <script src="http://github.highcharts.com/5a83eb3/modules/exporting.src.js"></script>
```

(Unless the PR will be accepted - then you could use the github code source as seen in the initial comment for this issue.)

**Comment by zlateskud** [comment]
@KacperMadej 

Error fixed but, the event(hover, click) don't work everytime.
I think this works only on bottom part of the diagram.

I attach a video.

[chart video.zip](https://github.com/highcharts/highcharts/files/1717255/chart.video.zip)

**Comment by zlateskud** [comment]
@KacperMadej @TorsteinHonsi 
Hi,
if i use the code below, the event does not start(IE11 compatibility mode 7 ), with IE native it works.

plotOptions : {
	series : {
		point : {
			events : {
				click : function (e) {
					alert('From: ' + this.from + ', to: ' + this.to + ', weight:' + this.weight);
				}
			}
		}
	}
}
