### ISSUE TITLE
stack chart bug on small screens

### ISSUE THREAD

**Issue by jakesmorrison** [highcharts/highcharts#7852]
Hello, I am creating a simple chart to display stock data. I am trying to combine a Spline and Stacked chart with Highstocks. I have it working well for larger screen sizes, but it seems to break when the screen size gets too small. The chart does not stack anymore and the key values are the date instead of the actual names. 

#### Expected behaviour
Here is the data in my series when everything is working okay. 
key:"AAPL", percentage:14.604810996563572, total:17.46, x:1518418800000, y:2.55

Here is a screenshot of the working version on a large screen. 
<img width="661" alt="highcharts_working" src="https://user-images.githubusercontent.com/14865171/36115867-9b2b8230-0ff1-11e8-82b9-122a86fbea07.PNG">

#### Actual behaviour
For some reason on smaller screens the "key" in the data gets set not to the name of the stack but to the xaxis date. Example below. This explains why there are no stacks anymore. 

key:1518418800000, percentage:100, total:17.46, x:1518418800000, y:2.55

<img width="453" alt="highcharts_broken" src="https://user-images.githubusercontent.com/14865171/36116289-f0190f8c-0ff2-11e8-9d49-accdac4260a8.PNG">

#### Live demo with steps to reproduce
I created a live demo to show the issue. 
[Live Demo](https://jsfiddle.net/jakesmorrison/0bhsLdjb/)

#### Product version
highstock 6.0.3

#### Affected browser(s)
Google Chrome on Windows. Google Chrome on OSX. Safari on OSX. Safari on IOS. Dolphin on IOS. 

Thank you for your help,

Jake

**Comment by jakesmorrison** [comment]
If you increase/decrease the size of the output window in jsFiddle you can toggle the bug.

**Comment by KacperMadej** [comment]
Hi @jakesmorrison 

Stacking shouldn't be done within the same series points. Each point should have different x values and if you are having duplicates of x values then those should be put into different series.

Disabling dataGrouping can help in your case if you don't want to reorganize your data.
Demo: https://jsfiddle.net/0bhsLdjb/1/

**Comment by jakesmorrison** [comment]
Thanks @KacperMadej. That seemed to work. 

It is still strange to me how toggling the screen size would toggle whether highstocks recognized the stacks. 

I will close the issue. Thanks again.
