### ISSUE TITLE
Highcharts boost problem with stacked bar chart

### ISSUE THREAD

**Issue by yoni12ab** [highcharts/highcharts#7853]
Hi,
I just tried to include the boost file in my project and it works mostly well,
I am facing an issue with stacked bar with a lot of points it shrinks the bars 
see this : http://jsfiddle.net/yoni12ab/unpbuh8f/4/
if you change boost enabled to false you will see the desired result.

another thing that I see in console is WebGl error :
.Offscreen-For-WebGL-000001BEE72C6AD0]RENDER WARNING: Render count or primcount is 0.

Thanks in advance
Yoni

**Comment by sebastianbochan** [comment]
Hi @yoni12ab 
Thank you for reporting.

@cvasseng

**Comment by TorsteinHonsi** [comment]
One of boost's current limitations is that columns/bars are always 1px wide when in Boost mode.

**Comment by pawelfus** [comment]
Added to docs:

- https://www.highcharts.com/docs/advanced-chart-features/boost-module
> The largest caveat is that rectangles for column and bar charts are always drawn as a single 1 pixel wide line. This will likely not be the desired outcome when zoomed in to the level where each column/bar is visible as an individual entity. Thus, column and bar charts are more suited to series-level boosting.
