### ISSUE TITLE
PieChart does not display label on the pie when container > 1000px

### ISSUE THREAD

**Issue by Bastorx** [highcharts/highcharts#7859]
#### Expected behaviour
PieChart should display labels on the pie

#### Actual behaviour
PieChart does not display labels on the pie

#### Product version
Tested on highcharts@5.0.11 and highcharts@6.0.6

#### Affected browser(s)
Google Chrome (I didn't test for others)

**Comment by Bastorx** [comment]
Impossible to reproduce in JS fiddle, I will try another way later...

**Comment by TorsteinHonsi** [comment]
Here's a 1100px pie with data labels: http://jsfiddle.net/hs2m60fs/. 

I'm closing this for now, please reopen it if you can reproduce the issue.
