### ISSUE TITLE
Numeric value of pointPlacement doesn't work in heatmap

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7860]
#### Expected behaviour
`pointPlacement` with number as value shoud work in heatmap series just like it does in column series: http://jsfiddle.net/BlackLabel/7uwqy45z/

#### Actual behaviour
`pointPlacement` with number as value (e.g. `0.5`) has no effect in heatmap.

#### Live demo
http://jsfiddle.net/BlackLabel/6s7Lzn90/
Comment out `pointPlacement: 0.5,` line and run the code again to see that there's no difference.

#### Product version
6.0.6

**Comment by TorsteinHonsi** [comment]
I'm removing `pointPlacement` from the heatmaps docs and flagging this as an Enhancement.
