### ISSUE TITLE
Performance get down when many chart coming up

### ISSUE THREAD

**Issue by zantdev** [highcharts/highcharts#7865]
I had problem with optimation and needed several suggestion. I created Stock Analysis Application which showing 50 real time chart. I used react JS and highchart for JS framework and charting lib. The issues i faced currently is the chart got slows when i'm hovering to get tooltip info of certain point. When i used 10 real time chart, it's still ok no issues coming up. But after 50, it's so stuttering. 1 chart has 10,800 points. I have used boost mode in highchart but still not resolve my issues.

This is attached image of my 50 charts
[Charts Screenshot](https://imgur.com/psKyBoB)

**Comment by pawelfus** [comment]
Hi @zantdev 

Thank you for reporting the issue. Could you recreate in jsFiddle? Simple example: http://jsfiddle.net/9sq7y82n/13/ - works fine. Note: `dataGrouping` is disabled to see `boost` in action.

**Comment by zantdev** [comment]
Hi @pawelfus 

I have edited from your code and this is what i have done. I put setInterval function for simulating realtime data per seconds from my showcases.  
http://jsfiddle.net/zantknight/9sq7y82n/64/

Thanks for reply me ...

**Comment by pawelfus** [comment]
Hi @zantdev 

Thank you for the demo. It's caused by animation, I suggest to disable animation when adding a point: browser is not able to handle ~50 animations running at the same time: http://jsfiddle.net/9sq7y82n/69/

More about performance can be found in our docs: https://www.highcharts.com/docs/getting-started/frequently-asked-questions#optimize-performance

**Comment by zantdev** [comment]
I'm sorry i forget to put nData into 3600, as it's estimated 1 hour already data. Please check this one again http://jsfiddle.net/zantknight/9sq7y82n/72/

**Comment by pawelfus** [comment]
Thank you for the details - I see things are getting complicated :) For me, the best result is to keep the `dataGrouping` on and disable the animation: http://jsfiddle.net/9sq7y82n/107/

Note: First hover on a chart may take a while, because we need to build the tooltip tree.

Boost still needs some polishing, when comes to Highstock (see: https://code.highcharts.com/modules/boost.src.js -> development plan) - Highcharts chart (without the navigator) works faster: http://jsfiddle.net/9sq7y82n/108/

**Comment by zantdev** [comment]
I'm so sorry @pawelfus, i changed into 21600 point already, it was so slow again... im sorry my showcases are quite huge point which i'm implementing 6 * 3600 point per chart for real time stock monitoring... Can u suggest me how to configure the chart?

This is my chart configuration

```json
{      
      chart: {
        backgroundColor: '#232323',
        height: 300,
        defaultSeriesType: 'spline',
        animation: false
      },
      boost: {
        useGPUTranslations: true,
        usePreAllocated: true
      },
      plotOptions: {
          series: {
              animation: false
          }
      },
      rangeSelector: {
        enabled: false,
      },
      title: {
        text: ''
      },
      credits: {
        enabled: false
      },
      yAxis: {
        labels: {
          format: '{value} %',
          style: {
            color: '#fff'
          }
        },
        style: {
          color: '#fff'
        },
        title: {
          text: ''
        },
        tickPositioner: function () {
          var maxDeviation = Math.ceil(Math.max(Math.abs(this.dataMax), Math.abs(this.dataMin)));          
          if (maxDeviation === 1) {
            maxDeviation = 2;
          }
          var halfMaxDeviation = Math.ceil(maxDeviation / 2);
          return [-maxDeviation, -halfMaxDeviation, 0, halfMaxDeviation, maxDeviation];
        },
      },
      xAxis: {
        events: {
          afterSetExtremes: function (e) {
            if (e.trigger == "navigator" && e.triggerOp == "navigator-drag") {
              let objMinMax = {
                changeMax: e.userMax,
                changeMin: e.userMin,								
              }
              that.props.onChangeMinMax(objMinMax, that.props.code);
            }
          },
        },        
        title: {
          text: ''
        },
        type: 'datetime',
        min: min,
        max: max,
        minRange: 3600,
        ordinal: false,  // this sets the fixed time formats         
        labels: {
          enabled: true,
          style: {
            color: '#fff'
          }
        },
      },
      series: [
        {
          name: 'Line 1',
          showInNavigator: true,
          data: data,  
          dataGrouping: {
            enabled: false
          },
          lineWidth: 0,
          type: 'area',
          fillColor: 'red',
          animation: false,
          style: { opacity: 0.5 },
          negativeFillColor: 'green',
          states: {
            hover: {
              enabled: false
            }
          },
          marker: {
            enabled: false,
          },
          boostThreshold: 20,
        }
      ],
      tooltip: {
        hideDelay: 0,
        shared: true,
        useHTML: true,
        followPointer: false,
        shadow: false,
        animation: false,
        formatter: function () {
          return (`<b>Delta (%): ${this.points[0].point.y} %</b><br>
                   <b>Delta Rp: ${this.points[0].point.delta}</b><br>
                   <b>Price: Rp. ${this.points[0].point.price}</b><br>
                   <b>VWAP: Rp. ${this.points[0].point.vwap}</b><br>
                   <b>Time: ${this.points[0].point.time}</b>`);
  
        },
      },
      navigator: {
        enabled: true,
        yAxis: {
          crosshair: false,
        },
        xAxis: {
          lineWidth: 1,
          crosshair: false,
          labels: {
            x: 3,
            y: -10
          }
        },
        series: {
          fillColor: '#232323',
          color: 'red',
          negativeFillColor: '#232323',
          negativeColor: 'green',
          dataGrouping: {
            enabled: false
          },
          threshold: 0,
        },
        height: 70,
      },
      scrollbar: {
        enabled: false
      },
      noData: 'Personalized no data message'
    }
```

**Comment by pawelfus** [comment]
@zantdev - Could you display last n-points on the chart, not all of them? Option in `addPoint(options, redraw, shift, animation)` -> `shift` should help to keep n-points on the chart. You say you have `21600` points, but actually that number is doubled by navigator. If we add a few hours we get 60k+ points per chart and 3 000 000 on all charts. I'm not sure if browsers can handle this: each chart needs to calculate extremes (or can you set fixed extremes?), rebuild tooltip-tree etc. And if we have 50 charts, then we have only 20ms to redraw the chart. In general, live dashboard-style charts have ~100-200 points updated every second.

Alternative solution is to update charts that are in the view port, not all of them. Maybe adding lazy-loading of data should help too: https://www.highcharts.com/blog/news/48-loading-millions-of-points-in-highcharts/ (note: navigator needs to be updated manually, as `adaptToUpdatedData` is disabled).

**Comment by zantdev** [comment]
@pawelfus thanks for advice i'll try your suggestion... :)
