### ISSUE TITLE
HighCharts-HighStock AddPoint Performance Issue In IE And Edge

### ISSUE THREAD

**Issue by rajeevsinghchib** [highcharts/highcharts#7869]
Hi,

Please find the attached sample zip file containing "test.html" file.
Please run test.html file with following browsers (ie, edge, chrome & firefox) and click on "Add Points" button.

Chrome and Firefox takes 2-3 seconds for plotting around 0.3 million(279496) data points, while IE and Edge takes around 2 minutes for plotting same number of data points.

I tried applying highchart boost module and haven't seen any difference in my sample.

Please suggest.

Regards,
Rajeev Singh Chib

#### Expected behaviour
Plot Points in 2 seconds

#### Actual behaviour
Plots Points in 2 minutes

#### Live demo with steps to reproduce
Sample Attached

#### Product version
Highstock JS v6.0.6

#### Affected browser(s)
[HighStockIE&EdgePerformanceIssue.zip](https://github.com/highcharts/highcharts/files/1727729/HighStockIE.EdgePerformanceIssue.zip)

IE & Edge

**Comment by pawelfus** [comment]
Hi @rajeevsinghchib 

Thank you for reporting the issue. If you want to add a lot of points at the same time, don't use `addPoint()`, but `setData()`:

```javascript
function addPoints()
{
	var nPointsAdded = 0;
	var dt = new Date();
	var time = dt.getHours() + ":" + dt.getMinutes() + ":" + dt.getSeconds();
	var datasets = [[], [], [], [], [], [], [], []];

	$.each(inputData, function( index, values ) {
		var timestamp = Number(moment.utc(index, 'YYYYMMDDHHmmss'));
		for(var i = 0; i < values.length; i++)
		{
			datasets[i].push([ timestamp, values[i] ]);
			nPointsAdded++;
		}
	});

	datasets.forEach(function (set, i) {
		chart.series[i].setData(set, false, false, false);
	});

	chart.redraw();
	dt = new Date();
	time = dt.getHours() + ":" + dt.getMinutes() + ":" + dt.getSeconds();
	console.log(time);
	console.log(nPointsAdded);
}
```

**Comment by sebastianbochan** [comment]
Closed due to inactivity. Please reopen if you have any further informations.
