### ISSUE TITLE
Columns not visible - wrong extremes computed by Highcharts

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7871]
#### Expected behaviour
All columns should be visible.

#### Actual behaviour
Columns of Series 1 and Series 3 are not visible. X axis extremes seem to have inappropriate values (computed by Highcharts).

#### Live demo
http://jsfiddle.net/BlackLabel/nt3kcp03/

#### Product version
6.0.6

**Comment by pawelfus** [comment]
**Workaround:**

Set `pointRange` manually: http://jsfiddle.net/nt3kcp03/8/

**Comment by pawelfus** [comment]
Closing as duplicate of #7346
