### ISSUE TITLE
Problem with extremes of exported files after using scrollbar.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#7873]
#### Expected behaviour

Using scrollbar shouldn't affect on extremes that are set on exporting configuration object.

#### Actual behaviour

Exporting isn't keeping in mind the extremes that are set on _chart.exporting_ object, just right after using scrollbar.

#### Live demo with steps to reproduce

[https://jsfiddle.net/BlackLabel/8ko88jb8/](https://jsfiddle.net/BlackLabel/8ko88jb8/)
1. Export chart (but don't use scrollbar). Exported file has all points included.
2. Move scrollbar a little to the bottom, again export the chart, and see what happened.

#### Product version

All versions

#### Affected browser(s)

All browsers

#### Workaround (v5.0.6 and above)

Everything is working well after wrapping the _exporting.xAxis_ object with an array, and also defining the _xAxis.type_ field again, just like that:
```js
xAxis: [{
    type: 'category'
    min: 0,
    max: 5,
    scrollbar: {
        enabled: false
    }
}] 
```
Workaround example: [https://jsfiddle.net/BlackLabel/vcjafzvb/](https://jsfiddle.net/BlackLabel/vcjafzvb/)

**Comment by coded9** [comment]
No, the workaround doesn't work, it repeats the same behavior as before.

**Comment by Denyllon** [comment]
I tested it, and the workaround is working correctly on v5.0.6 and above. Also, you should add the _xAxis.type_ field to exporting configuration object. I edited the issue description.

**Comment by Denyllon** [comment]
Are you sure, that you opened correct JSfiddle example? In the **Workaround** section there is another link to example where the workaround is applied.

**Comment by Vageshwar** [comment]
@Denyllon Workaround is not working, tried the fiddle link the export only gives visible parts of graph on export after scroll. 
Any other workarounds ?

**Comment by bm64** [comment]
Hello @Vageshwar 

Please slightly modify the workaround demo and set undefined for min and max in exporting config: https://jsfiddle.net/BlackLabel/btjmazL6/

**Comment by Vageshwar** [comment]
Thanks @bm64 it worked !

**Comment by bm64** [comment]
@Vageshwar could you try to recreate the issue in this demo https://codesandbox.io/s/highcharts-react-demo-forked-tesrpg?

**Comment by Vageshwar** [comment]
@bm64  I did some trial and error, minRange ( xAxis attribute ) worked as per my requirement
Thanks for the help

**Comment by Akshay20240305** [comment]
Hi @Denyllon,

We are encountering the same issue with download when there is scroll bar. 

Below are the details:
Even after specifying the type and minRange properties under exporting.chartOptions.xAxis, the configuration does not work as expected.

Below is a JSFiddle that reproduces the issue:
https://jsfiddle.net/ymah0bd3/

Request for Assistance:
Could you please provide guidance on how to resolve this issue?
