### ISSUE TITLE
Uncaught TypeError: a.Highcharts.error is not a function

### ISSUE THREAD

**Issue by Ashwin117** [highcharts/highcharts#7876]
I'm doing npm install highcharts and simply requiring...yet getting this problem at runtime.

I'm using React 16 w Webpack 3. What am i missing?

**Comment by pawelfus** [comment]
Hi @Ashwin117 

Could you provide more details? How do you require Highcharts? It looks like Highcharts are trying to throw an error - and tell us what is wrong, but someone removed `Highcharts.error()` method?

**Comment by sebastianbochan** [comment]
Closed due to inactivity. Please reopen if any steps for reproduce will be available.
