### ISSUE TITLE
legend causes layout thrashing, even worse when `useHTML` is set to true

### ISSUE THREAD

**Issue by liqiang372** [highcharts/highcharts#7881]
#### Expected behaviour
Good performance of legend.

#### Actual behaviour
it causes a lot of layout thrashing.

Without legend
![Without legend](https://user-images.githubusercontent.com/6468832/36335233-2e0b7a3a-1333-11e8-9b6d-1f92dec06a26.png)

With svg legend
![with svg legend](https://user-images.githubusercontent.com/6468832/36335248-580f4c8a-1333-11e8-9cb0-179f30360e4d.png)

With html legend
![HTML legend](https://user-images.githubusercontent.com/6468832/36335283-95927bea-1333-11e8-8a57-d80f0faf2231.png)

profile on production, 300 legend, each legend has around 40ms recalculate style. which is 12s in total
![image](https://user-images.githubusercontent.com/6468832/37131047-64b4bd14-223b-11e8-9492-5d1df9a31875.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/o04o27L0/19/

#### Product version
highcharts, 6.0.7

#### Affected browser(s)
Chrome

**Comment by oysteinmoseng** [comment]
Thank you for reporting, note that we have a [boost module](https://www.highcharts.com/docs/advanced-chart-features/boost-module) that might be helpful if you have high performance requirements.

**Comment by liqiang372** [comment]
@oysteinmoseng Thanks for replying, I think boost module has little help with the legend issue, I uploaded my production profile to give you an intuitive feeling how this legend can really slow everything down when the page is complex
