### ISSUE TITLE
Trouble finding documentation for certain properties

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#7882]
#### Expected behaviour

Searching for `startOnTick` at https://api.highcharts.com/class-reference/ should lead to documentation about `startOnTick` in at most 2-3 clicks.

#### Actual behaviour

Searching bring up this popup, but clicking either link doesn't lead to any documentation about `startOnTick`

![image](https://user-images.githubusercontent.com/33569/36338556-7cae2334-1367-11e8-86d9-d555f0cb4678.png)

Searching at https://www.highcharts.com/docs brings up one release note.

**Comment by oysteinmoseng** [comment]
Thanks for the suggestion, in other words, the class reference search should also include options.

**Comment by TorsteinHonsi** [comment]
> class reference search should also include options.

Or perhaps easier, a common search box that indexes both options and object members.
