### ISSUE TITLE
line chart render problem

### ISSUE THREAD

**Issue by maxlibin** [highcharts/highcharts#7883]
Hi, I have numbers of users report of getting line chart render problem with hardware acceleration on in their chrome settings. Check my screenshot below.

<img width="185" alt="screen shot 2018-02-19 at 6 29 23 pm" src="https://user-images.githubusercontent.com/1277038/36373397-fc474c28-15a2-11e8-9ef0-395019b434b8.png">
Does anyone know whats the problem caused? and this seems only in chrome.
currently using Highcharts JS v6.0.6 (2018-02-05) but problem start since v5.

**Comment by pawelfus** [comment]
Hi @maxlibin - please check #7528 issue. This CSS should resolve the Chrome issue:

```css
.highcharts-series path {
     stroke-linecap: initial; 
}
```
