### ISSUE TITLE
The order of series in Gantt chart

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#7884]
#### Expected behaviour
All series (parents along with their children) are visible no matter the order they are placed in series array.

#### Actual behaviour
The order of series does matter. The first demo below has three series. The first one contains three parent elements. The second, a child of the last parent. The last series has the child of the first series and the child of the second. This results in not showing the last parent along with its child at all. In the second demo, where the order is changed and the series that contains child of the last parent is placed at the end of series array, all parents are visible, as intended.

#### Live demos
http://jsfiddle.net/jvzLwk2c/ - lack of the last parent
http://jsfiddle.net/uwe6mm5h/ - all parents visible (changed the order)

**Comment by oysteinmoseng** [comment]
Seems to be working fine now.
