### ISSUE TITLE
SVG text not well rendered on PDF with FOP 2.1

### ISSUE THREAD

**Issue by discofunk80** [highcharts/highcharts#7888]
#### Expected behaviour
Text is displayed correctly.

#### Actual behaviour
I'm trying to display an SVG object exported with Highcharts v5.0.7 on a PDF using FOP 2.1 (fo external graphic) as a data:image/svg+xml;base64

All texts are surrounded by a sort of cells. I was trying to change font family or other attributes but cells are still there. Please check the attached image.

Any suggestion to remove this cells? The SVG object is perfectly rendered on an SVG online tester.

#### Product version
Highcharts v5.0.7 / FOP 2.1

#### Affected browser(s)
I tried with Chrome 64 and IE 11

![gitimagesvg](https://user-images.githubusercontent.com/23059769/36388826-6b418ebe-159d-11e8-85ad-2c9334ba5d70.PNG)

**Comment by pawelfus** [comment]
Hi @discofunk80 

Thank you for reporting the issue. Unfortunately it's first time I see this error, so I assume it's connected to FOP 2.1. Did you report the issue on the FOP bug list too? I would suggest to send them generated SVG.

It looks like they use Batik for rendering, so.. isn't this issue the same: https://stackoverflow.com/questions/34654510/border-boxed-characters-when-using-batik-fop-svg-to-pdf-conversion-under-jruby ?

**Comment by discofunk80** [comment]
Hi @pawelfus 
Thank you for your quick reply. Indeed, changing the level for log4j logger to INFO (instead of DEBUG) resolved this issue on the text.
