### ISSUE TITLE
cannot find module highcharts/highstock

### ISSUE THREAD

**Issue by hamzahamidi** [highcharts/highcharts#7889]
#### Actual behaviour
Ionic / angular
Error: cannot find module highcharts/highstock

#### Product version

I tried every version from **5.0.10**

Ionic Framework    : ionic-angular 3.9.0
System:
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : Linux 4.4

### Code
```
import * as Highcharts from 'highcharts/highstock';
// Alternatively, this is how to load Highstock. Highmaps is similar.
// import Highcharts from 'highcharts/highstock';

// Load the exporting module.
import * as Exporting from 'highcharts/modules/exporting';
// Initialize exporting module.
Exporting(Highcharts);
```

#### Affected browser(s)
Chrome mozilla ...

**Comment by KacperMadej** [comment]
Hi @hamzahamidi 

How have you installed the Highcharts?
The version 5.0.10 should have Highstock available at the path you have posted. (For fast check: https://unpkg.com/highcharts@5.0.10/highstock)

Please provide more info to help us recreate the problem.

**Comment by hamzahamidi** [comment]
I solved it.

**Comment by KacperMadej** [comment]
@hamzahamidi 
Could you share how did you solved the problem?

**Comment by hamzahamidi** [comment]
@KacperMadej Sure, Actually I thought Highcharts doesn't have types definition, so I installed typings & @types/highcharts which caused this error. I just deleted these dependencies & now it works just fine.

**Comment by raha1923** [comment]
@hamzahamidi
can tell me more about how you solved it, i have this problem too and i don't know how i can solve it at all

**Comment by raha1923** [comment]
ok, i solve it with installing `@types/highcharts`.

thanks every one

**Comment by raha1923** [comment]
ok, i solve it with installing `@types/highcharts`.

thanks every one

**Comment by hamzahamidi** [comment]
In my case I just deleted all the typings I had about highcharts.  Import is simple 
``` import * as Highcharts from 'highcharts/highstock'; ```
