### ISSUE TITLE
highcharts 3d -js version not supporting both of column drillDown and Pie DrilDown charts

### ISSUE THREAD

**Issue by ManeshM** [highcharts/highcharts#7890]
Can you please provide me with highcharts-3d of version  Highcharts JS v4.0.12 (2017-05-24)>? I couldn't find it in the website (and I want to use older version instead of newer versions).

**Comment by pawelfus** [comment]
Hi @ManeshM 

We don't have Highcharts v4.0.12, but I assume you mean v5.0.12 (according to the date): http://code.highcharts.com/5.0.12/highcharts-3d.src.js

Please, keep in mind that we use github issues as bug reports. If you have questions, please contact our support: https://www.highcharts.com/support

**Comment by ManeshM** [comment]
can you please provide a version of highcharts-3d where both pie drilldown and column drilldown charts work? When we tried using, pie drilldown didn't work in v6.0.7 (2018-02-16) and column drilldown didn't work in v5.0.12 (2017-05-24)

**Comment by pawelfus** [comment]
@ManeshM could you contact with our support? I just tested 5.0.12 and it looks fine: http://jsfiddle.net/BlackLabel/pouvdj5d/
