### ISSUE TITLE
Need a feature to set a minimum width for treemap block

### ISSUE THREAD

**Issue by kundansonu** [highcharts/highcharts#7891]
#### Expected behaviour

There should be an option to provide a minimum block size

#### Actual behaviour
For a large dataset with few of records having a smaller value the block plotted on treemap is too small to interact. 
![image](https://user-images.githubusercontent.com/5444055/36411249-a34251c0-163a-11e8-9c54-18e298515929.png)

#### Live demo with steps to reproduce
Please click on Europe and check for switzerland
I have changed the large tree map example and changed the value of Switzerland to 1
http://fiddle.jshell.net/s41m016L/

#### Product version

 Highcharts JS v6.0.7

#### Affected browser(s)
Google Chrome, Firefox

**Comment by pawelfus** [comment]
Hi @kundansonu 

Thank you for your suggestion.

@jon-a-nygaard FYI

**Comment by TorsteinHonsi** [comment]
This is thematically related to [the column minPointLength option](https://api.highcharts.com/highcharts/plotOptions.column.minPointLength). It also comes with the same logical problems - what happens if many of these oversized items are positioned next to each other?

**Comment by vadimpopa** [comment]
This problem is in older versions as well. Any idea how this could be fixed in current versions, a temporary fix ?

**Comment by vadimpopa** [comment]
Checked the forum and it seems there have been lots of requests for this feature since 2016 at least. And if I'm not wrong only fix/solution is to write a new algorithm based on the one we've chosen.

**Comment by ajankit85** [comment]
I am facing the same issue. Is there any resolution to this problem?

**Comment by sebastianbochan** [comment]
Hi @ajankit85,
How about workaround from here: http://jsfiddle.net/sgm86hyd/18/ ?
