### ISSUE TITLE
legend.verticalAlign = 'top' does not work

### ISSUE THREAD

**Issue by benzmarkus** [highcharts/highcharts#7894]
#### Expected behaviour
legend.verticalAlign = 'top' does not work

#### Actual behaviour
should work as written in docu

#### Live demo with steps to reproduce
1) Example with the verticalAlign and not working
template: https://jsfiddle.net/72yjn7yk/2/

2) Working without verticalAlign
template: https://jsfiddle.net/72yjn7yk/3/

#### Product version
Highcharts 6.0.7

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @benzmarkus 

Thank you for reporting about the problem.
