### ISSUE TITLE
Stream Chart Tooltip issue 

### ISSUE THREAD

**Issue by vbinaveenr** [highcharts/highcharts#7896]
#### Expected behaviour
When all the series except the second series is disabled in run time ( by deselecting the legend) , the tool tip should show for  properly for all the members when hovered over the data series like how it works for line chart

#### Actual behaviour
When all the series except the second series is disabled in run time ( by deselecting the legend), the tool tip is not shown properly for all the members when hovered over the data series 

#### Live demo with steps to reproduce
http://jsfiddle.net/q85hqk3g/4/

#### Affected browser(s)
All browser

**Comment by pawelfus** [comment]
Hi @vbinaveenr 

Thank you for reporting the issue!

**Comment by TorsteinHonsi** [comment]
There seems to be more general problems with a single series in stream graphs:

* One series chart http://jsfiddle.net/q85hqk3g/11/
  * The lower part of the graph is not shown and the axis is cut off
* Two series in the chart, the first series hidden (like in the OP) http://jsfiddle.net/q85hqk3g/12/
  * The upper part of the graph is not shown
  * The tooltip only works for zero points (others are outside plot area)

**Comment by TorsteinHonsi** [comment]
OP fiddle with the fix applied: http://jsfiddle.net/q85hqk3g/21/
