### ISSUE TITLE
Map of Sudan

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#7897]
#### Expected behaviour
Map of Sudan including a disputed territory.
![sudan2](https://user-images.githubusercontent.com/19933566/36483489-94b93eac-1716-11e8-9ee1-9949672314b5.png)

#### Actual behaviour
Highmaps map collection lacks map of Sudan with a disputed territory (Hala'ib Triangle).
![sudan1](https://user-images.githubusercontent.com/19933566/36483502-9bce0cae-1716-11e8-9012-0dc17c0358ae.png)

**Comment by kamilkulig** [comment]
**Fixed demo:** http://jsfiddle.net/BlackLabel/293kezvr/

_Internal note:_
Source shapes for Sudan and Egypt changed on admin0 level.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#19
