### ISSUE TITLE
Merge buildKDTree timeouts

### ISSUE THREAD

**Issue by ypconstante** [highcharts/highcharts#7900]
#### Actual behaviour
Highcharts creates a new timeout for each series in the buildKDTree method. In situations that there is a lot of series, this ends up consuming a significant amount of time. In a test I made, half a second was spend just creating the timeouts. 
I've tried to use the kdNow option, but the tooltips are put behind the columns. 
This big number of timeouts also end up slowing down the rendering for people using the angular zone.js, because after the execution of each of this timeouts, a digest cycle is executed.

#### Product version
Highcharts 6.0.7

#### Affected browser(s)
Chrome 64

**Comment by pawelfus** [comment]
Hi @ypconstante 

Thank you for reporting the issue. Could you show an example for:

> I've tried to use the kdNow option, but the tooltips are put behind the columns.

zIndex of the tooltip shouldn't change even if `kdNow` is set.

Regarding the issue itself, could you define a lot of series? In general chart becomes unreadable when dealing with more than 20 series. Again, a live demo would be great.

**Comment by ypconstante** [comment]
Tested the kdNow config again and the zIndex is correct, must have done something else wrong.
With this config, the zone.js problem doesn't happen anymore.

> could you define a lot of series?
I'm doing some testing with some ridiculous configs, in this case it's more than 100 series. But the same behavior happen when there is a lot of charts in the same page. 

There is some reason for this timeout? In my tests its usually less than  1ms per chart, so it does't seem to be a performance problem.

**Comment by ypconstante** [comment]
The zIndex problem was caused by some testings I was making in the `foreignObject` boost config https://github.com/highcharts/highcharts/issues/6842#issuecomment-332793391

**Comment by pawelfus** [comment]
Thank you for the details. This setTimeout is useful when a dataset has a lot of points, for example 100k. Older browsers need to catch a breath so it makes sense to build a tooltip tree after chart is visible. This is more common case than 100+ series on a chart.

@TorsteinHonsi FYI

**Comment by ypconstante** [comment]
Currently the tooltips are rendered right after the chart is rendered. If it was changed to be rendered only on hover, maybe the timeout wouldn't be needed.

**Comment by pawelfus** [comment]
That could be a problem for big datasets - from ux perspective, we would see a delay when hovering chart. For mobile it would be even worse - user would need to tap chart twice to see the tooltip..

**Comment by ypconstante** [comment]
I think the delay on hover could be an acceptable trade off for a faster page load. The hover delay could be reduced by rendering just the data necessary to show the current hover tooltip, instead of rendering the tooltip for all data.
I couldn't simulate this tap twice behavior that you mentioned. From what I understood of Highcharts behavior, this would happen after rotating the screen, forcing the chart to resize.

**Comment by pawelfus** [comment]
Thanks! Regarding this:
> The hover delay could be reduced by rendering just the data necessary to show the current hover tooltip, instead of rendering the tooltip for all data.

I'm not sure if we are talking about the same feature but it's implemented by cropping data (see [`series.cropThreshold`](https://api.highcharts.com/highcharts/plotOptions.series.cropThreshold) option) or, in Highstock, by dataGrouping (API: [`dataGrouping`](https://api.highcharts.com/highstock/plotOptions.series.dataGrouping)).

**Comment by TorsteinHonsi** [comment]
I tried this out, and as far as I can see, the current functionality is that we don't build the k-d-tree until the user hovers the chart - am I missing something?

Also, I did some performance test on the time spent in `startRecursive`:

| Series type | No of points | Time |
| ---------- | ------------ | -----:|
| line             | 100                 | 0.7 ms |
| line             | 1k                    | 7 ms   |
| line             | 10k                 | 32 ms | 
| scatter      | 100                 | 0.6 ms |
| scatter      | 1k                   | 8 ms    |
| scatter      | 10k                 | 72 ms |    

The takeaway is that at 100 points the rendering time is neglectable, but already at 1k points, the extra time for chart rendering should be avoided. A possible solution would be to build the k-d-tree in sync if the data length is below a certain threshold. It would resolve the issue of configs having a huge number of series with a small number of points in each. 

What do you think?

**Comment by pawelfus** [comment]
Oh, you are right. Just checked code once again and you are right - kdTree is build sync/async only after first hover/point searching. How do we sync later with `searchPoint()` method on mobiles?
