### ISSUE TITLE
Verify timeoutID before calling clearTimeout

### ISSUE THREAD

**Issue by ypconstante** [highcharts/highcharts#7901]
#### Actual behaviour
When destroying a chart, Highcharts calls clearTimeout a lot of times. For some reasons, browsers are kind of slow when calling clearTimeout with a null or undefined value, which is what happens a lot of times in this clearTimeout calls. In some tests I've made, the time for the execution of clearTimeout and removeChild were the same.

#### Live demo with steps to reproduce
clearTimeout performance demo: https://jsperf.com/null-check-cleartimeout-vs-cleartimeout-null/3

#### Product version
Highcharts 6.0.7

#### Affected browser(s)
Chrome 64

**Comment by pawelfus** [comment]
@ypconstante - it looks like your jsperf is broken, could you update the URL?

**Comment by ypconstante** [comment]
jsperf is returning error in every page right now.
