### ISSUE TITLE
Formatted labels for xAxis are incorrectly positioned when `useHTML` is enabled

### ISSUE THREAD

**Issue by daniel-araujo** [highcharts/highcharts#7902]
#### Expected behaviour
Display short labels for xAxis when labels are rotated.

#### Actual behaviour
Highcharts does not correctly place the short labels if `useHTML` is enabled.

![With useHTML](https://i.imgur.com/wH3NnUG.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/dp05x684/
1. Decrease width until autoRotation kicks in

#### Product version
Highcharts JS v6.0.7 (2018-02-16)

#### Affected browser(s)
Reproduced on Firefox and Chromium.

**Comment by pawelfus** [comment]
Hi @daniel-araujo 

Thank you for reporting this bug! It's a regression, in v6.0.4 is works fine: http://jsfiddle.net/BlackLabel/dp05x684/5/

*Internal note:*
Regression after 6bf7ff5c8

**Comment by pawelfus** [comment]
Closing this ticket, see #7920  for the explanation.

**Comment by totszwai** [comment]
Same thing for yAxis
