### ISSUE TITLE
Overlapped legend items on exported chart

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#7904]
#### Behaviour
Changing fontFamily property inside chart.style object results in overlapped legend items on exported image. Could be related with: #1428.

#### Live demo with steps to reproduce
http://jsfiddle.net/nhj1s0tx/

1. Export to PNG/JPEG/PDF.

**Comment by KacperMadej** [comment]
Looks like the font is not installed on the exporting server.
The letters look very different.

`verdana` works fine - http://jsfiddle.net/BlackLabel/nhj1s0tx/2/

**Comment by sebastianbochan** [comment]
The problem is not still valid.
