### ISSUE TITLE
Gauge chart throws error if no yAxis.labels config is provided on styled mode

### ISSUE THREAD

**Issue by DiegoCardoso** [highcharts/highcharts#7906]
#### Expected behaviour
Charts should work if no configuration for `yAxis.labels` is provided in styled mode. It works if not in styled mode.

#### Actual behaviour
Chart is not fully display and and error is raised on console:
```javascript
VM570 highcharts-more.js:22 Uncaught TypeError: Cannot read property 'fontSize' of undefined
```

#### Live demo with steps to reproduce
Run the code at:

http://jsfiddle.net/diegocardoso/mzpb44vn/7/

You can uncomment the `rotation` code to see it working as expected.

#### Product version
Tried first for Highcharts 5.0.14 but could also see the same behaviour for 6.0.7.

#### Affected browser(s)
Tested on Chrome

**Comment by pawelfus** [comment]
Hi @DiegoCardoso 

Thank you for reporting this bug!

**Comment by TorsteinHonsi** [comment]
Original demo with the fix applied: http://jsfiddle.net/mzpb44vn/13/
