### ISSUE TITLE
borderColor and borderWidth properties set on Suburst level didn't work.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#7908]
#### Expected behaviour

As it is written in documentation, those parameters set inside _level_ configuration should affect on that specific level, but they aren't.

Documentation reference:
[https://api.highcharts.com/highcharts/series.sunburst.levels.borderColor](https://api.highcharts.com/highcharts/series.sunburst.levels.borderColor)
[https://api.highcharts.com/highcharts/series.sunburst.levels.borderWidth](https://api.highcharts.com/highcharts/series.sunburst.levels.borderWidth)

#### Actual behaviour

The parameters mentioned above, don't change anything.

#### Live demo with steps to reproduce

[http://jsfiddle.net/BlackLabel/o340fz9a/](http://jsfiddle.net/BlackLabel/o340fz9a/)

#### Product version

All versions

**Comment by KacperMadej** [comment]
@jon-a-nygaard Treemap works fine http://jsfiddle.net/0wu2pvhn/
