### ISSUE TITLE
Script error in ie8 when the version is greater than 6.0.2

### ISSUE THREAD

**Issue by guxingke201** [highcharts/highcharts#7909]
#### Expected behaviour
no script error in the latest vesion

#### Actual behaviour
1、open https://www.hcharts.cn/samples/highcharts/line/line-basic in ie8 
2、click the chart
3、script error
#### Live demo with steps to reproduce

https://www.hcharts.cn/samples/highcharts/line/line-basic
#### Product version

Highcharts@6.0.3-6.0.6
#### Affected browser(s)
ie8

**Comment by KacperMadej** [comment]
Hi @guxingke201 

I'm unable to recreate the problem.
The demo works fine in IE8. The Highcharts version loaded in the demo is 6.0.7.

![ie8-no-error](https://user-images.githubusercontent.com/8960408/36593443-037457ee-189a-11e8-9b70-96a8a7002174.jpg)

The same is with the official Highcharts demo - works fine, no errors: 
https://www.highcharts.com/demo/line-basic

Remember about loading the oldie.js module when using legacy IE.

**Comment by guxingke201** [comment]
The error appear in Highcharts@6.0.3-6.0.6,fortunately it has disappear in 6.0.7
