### ISSUE TITLE
duplicate labels if i use milestone on any bar

### ISSUE THREAD

**Issue by rameshbimarian** [highcharts/highcharts#7910]
#### Expected behaviour
Should not have duplicate label name and milestone should be added on bar.

#### Actual behaviour
Milestone is getting added into bar.But showing as duplicate label name

#### Live demo with steps to reproduce

https://jsfiddle.net/fh9v8g47/1/
Here v1.5 showing duplicate in facebook

#### Product version

Alpha gantt

#### Affected browser(s)
Chrome latest

**Comment by oysteinmoseng** [comment]
Minimal example: https://jsfiddle.net/fsL6mfu4/3/. Note the duplicated yAxis labels for `V1.5`.

This looks like a bug, we would not expect milestones to add an axis label. At the same time, it might be related to #6558. We do not currently have good support for multiple points with the same yAxis value. The current workaround would be to add a unique name to the milestone, e.g. https://jsfiddle.net/fsL6mfu4/5/.

**Comment by oysteinmoseng** [comment]
Fixed now, control this behavior with `yAxis.uniqueNames` https://jsfiddle.net/fsL6mfu4/14/
