### ISSUE TITLE
When using yAxis.labels.format option, labels are no longer abbreviated with k, m, b, etc.

### ISSUE THREAD

**Issue by bradbesserman** [highcharts/highcharts#7915]
#### Expected behaviour
When using yAxis.labels.format option, labels are displayed with selected formatted and still abbreviated with k, m, b when over thousand, million, billion, etc.

#### Actual behaviour
When not using yAxis.labels.format option, labels are abbreviated with k, m, b when over thousand, million, billion, etc.  When using labels format option, the number is displayed full length, with no k, m, b abbreviation.

#### Live demo with steps to reproduce
http://jsfiddle.net/tc1qab8q/6/

#### Product version
Highcharts 6

#### Affected browser(s)
All

**Comment by oysteinmoseng** [comment]
This functionality is part of the default label formatter, which is overridden by specifying either your own `format` or `formatter`. Specifying either of these will give you 100% control of the label format, so all additional magic is disabled when you do this. You can work around it by specifying a formatter and calling the default formatter within it: http://jsfiddle.net/a1b90b38/.

I am not sure if we want to change this behavior. If we do, we need to make sure users can also disable the automatic formatting of numbers from `1000` to `1k` if they want to.

Opinions @TorsteinHonsi?

**Comment by robinsoncrus0e** [comment]
Thanks for the quick reply!

If you do not change the behavior, it would be great if you could update the documentation on the Highcharts website to include the workaround you showed in the jsfiddle.

**Comment by sebastianbochan** [comment]
_Internal note_
@oysteinmoseng @TorsteinHonsi  
Im thinking in loud, maybe we should consider add simple function i.e addSuffix() which can be called on value in formatter?

**Comment by TorsteinHonsi** [comment]
Another option could be to add a key for these abbreviation in the number format itself, in principle `{value:.2fx}` where `x` says that we want abbreviations. In that case we need to check whether there is a convention for this in Python or other languages. However, I'm inclined to support Øystein that for more complex formatting the `formatter` function should be used.
