### ISSUE TITLE
Adding color codes to tooltip for indicators

### ISSUE THREAD

**Issue by ourarash** [highcharts/highcharts#7918]
#### Expected behaviour
Color codes in tooltips for indicator series such as MACD and Ichimoku

#### Actual behaviour
Each indicator series only has one  color. There is no color separate codes for MACD signal and Histogram for example  in the tooltip.

#### Live demo with steps to reproduce
http://jsfiddle.net/1pbhtbwo/3/

#### Product version
6.0.7

#### Affected browser(s)
All browsers

On the tooltip, only MACD has the color code. It is hard for the user to know which line is Signal and which line is Value:

![image](https://user-images.githubusercontent.com/20846105/36645893-4b5bab76-1a24-11e8-8b45-1fed7bf86d38.png)

How can I add a color for Value, Signal and Histogram on the tooltip to make it easy to distinguish them? Ideally, this is what I need:

![image](https://user-images.githubusercontent.com/20846105/36645890-42c166f4-1a24-11e8-8a19-a7f658083aff.png)

**Comment by pawelfus** [comment]
Hi @ourarash 

Thank you for reporting the issue. This is default format, inherited from other multiple-values series types (e.g. OHLC). You can add your own `pointFormatter` and generate content, for example: http://jsfiddle.net/BlackLabel/1pbhtbwo/18/

Snippet:

```javascript
      tooltip: {
        pointFormatter: function() {
          var seriesOptions = this.series.options,
            str = '<b>MACD (26, 12, 9)</b><br>';

          function getLine(color, name, value) {
            return '<span style="color:' + color + '">\u25CF</span> ' + name + ': <b>' + value + '</b><br/>';
          }

          str += getLine(seriesOptions.color, 'Value', this.options.MACD.toFixed(2));

          str += getLine(seriesOptions.signalLine.styles.lineColor, 'Signal', this.options.signal.toFixed(2));

          str += getLine(seriesOptions.macdLine.styles.lineColor, 'Histogram', this.options.y.toFixed(2));

          return str;
        }
```

**Comment by ourarash** [comment]
Thanks! 

I appreciate if you could also provide the code for IKH and Stochastics.

**Comment by pawelfus** [comment]
Hi @ourarash 

The same way you can create other tooltip pointFormatters, example for [Stochastic](http://jsfiddle.net/1pbhtbwo/25/) and [IKH](http://jsfiddle.net/1pbhtbwo/35/).
