### ISSUE TITLE
Can I have a total fixed bar?

### ISSUE THREAD

**Issue by anhdangx** [highcharts/highcharts#7919]
#### Expected behaviour
I am finding a way to have a fixed bar. 
X-Axis: Period or groups of some value
Y-Axis: value for each Period
Then I want to have a fixed bar, which will calculate the total of all value within the graph (see my picture below)
<img width="342" alt="171127_-_interpretation_-_summary_of_cost_out_pmo_graphs_and_formulav0_1_hjp" src="https://user-images.githubusercontent.com/33924801/36652501-a2987df2-1ae1-11e8-867d-97d3f2ceb8b8.png">

#### Actual behaviour
I don't know how to implement this function. Is it possible?

**Comment by pawelfus** [comment]
Hi @anhdangx 

Please contact with out support: https://www.highcharts.com/support - we use github issues for bug reports.
