### ISSUE TITLE
xAxis wrong positioning

### ISSUE THREAD

**Issue by alirezameftahi71** [highcharts/highcharts#7920]
#### Expected behaviour
To load all the xAxis labels correctly.

#### Actual behaviour
On first load, xAxis position are wrong (Mostly on first xAxis)
![1](https://user-images.githubusercontent.com/31916958/36657241-09e17a14-1ae1-11e8-85e1-741d0f990295.PNG)

After disabling and enabling the "input" again, from legend
![2](https://user-images.githubusercontent.com/31916958/36657249-11a5933e-1ae1-11e8-8c8a-d49adac1f97b.PNG)

#### Live demo with steps to reproduce
http://jsfiddle.net/alinux7/vgff7jj3/2/

#### Product version
Highcharts 6.0.7 and 6.0.5
It was OK on 5.x.x
#### Affected browser(s)
Tested on Chrome and Firefox

**Comment by pawelfus** [comment]
Hi @alirezameftahi71 

Thank you for reporting this bug! It's a regression since v6.0.5, v6.0.4 works fine: http://jsfiddle.net/BlackLabel/vgff7jj3/6/

Duplicate of #7902 - however, in this issue we have more advanced demo, so I'm closing #7902, leaving this one open.

**Comment by TorsteinHonsi** [comment]
Just for the records @alirezameftahi71 , cramping datetime labels into a category axis is usually not recommended. Instead we recommend a true `datetime` axis that understands the intervals and puts ticks on the natural places: http://jsfiddle.net/vgff7jj3/15/ .

**Comment by alirezameftahi71** [comment]
@TorsteinHonsi Thank you for your suggestion. I knew datetime type exists in axis but since I would Like to have persian dates in my axis and highcharts does not support it, so I have to use string of date in my xAxis.  I would love to see other date types like shamsi and hijri in highcharts in near future.

**Comment by pawelfus** [comment]
It should be possible to add other calendars than gregorian via API options: https://api.highcharts.com/highcharts/time.Date

It looks like `jdate` doesn't exist anymore. Maybe we should put there an example? We have also a plugin highcharts-localization: https://www.highcharts.com/products/plugin-registry/single/21/Highcharts%20Localization

**Comment by TorsteinHonsi** [comment]
@alirezameftahi71 I would like to set up a demo of using internationalized dates, this is where I've got so far: http://jsfiddle.net/highcharts/f8wsuthn/. It uses a library called _PersianDate_ and I have wrapped it to emulate a native JavaScript `Date` class.

Does the time look okay?

Also, the weekdays, months etc. are still in English. If you are interested, we would greatly appreciate help on getting this right, with the correct time and translation.

**Comment by TorsteinHonsi** [comment]
On a side note we already have a demo for i18n digits: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/highcharts-numberformat/

**Comment by alirezameftahi71** [comment]
@TorsteinHonsi @pawelfus Yes it works perfectly. This saves me a lot of trouble when I have a chart with dates on xAxis. Thank you very much.
But I also have charts with just `string` values on the xAxis. The problem still exists for those situations. If this little bug would be fixed, I would really appreciate it.

**Comment by TorsteinHonsi** [comment]
Thanks, we won't forget the original labeling issue. 

I'm happy to hear the time functions work for you! If you are interested, we would greatly appreciate help on getting this right, with the correct translation. Then we could share that chart in the internationalization page, so other users can see it.

**Comment by TorsteinHonsi** [comment]
There's also a related issue when `useHTML` is false: http://jsfiddle.net/highcharts/vgff7jj3/48/ . It seems to be a regression since 08b85659e7ec4f4ff979fe338b39d2ed8776276c

**Comment by alirezameftahi71** [comment]
@TorsteinHonsi Yes I would love to participate in anyway I can in this project. How Can I help?

**Comment by TorsteinHonsi** [comment]
Great! Here's what we want input on, referring to http://jsfiddle.net/highcharts/f8wsuthn/.
- Add the correct names of `weekdays` as well as `months` names and `shortMonts` to the language settings.
- Verify that the dates are actually correct
- Verify that the dates display correctly in the X axis and the tooltip.

**Comment by alirezameftahi71** [comment]
Here is the translations.
http://jsfiddle.net/alinux7/f8wsuthn/28/
But I think the dates are wrong, because 11th of 'آبان' or 2th of November, in 2018 will be Friday not Wednesday.

**Comment by behnam7171** [comment]
Hi, I also faced xAxis issue. just wanted to know is there any update on this bug? and is there any estimated time related to resolve this issue

**Comment by TorsteinHonsi** [comment]
The issue has been fixed in the master, but not released. We will start testing and preparing a new release this week, expecting the release next week. You can use https://github.highcharts.com/highcharts.js to see if your issue is resolved.

**Comment by totszwai** [comment]
Same issue for yAxis label when useHTML. The positioning is completely off. Would love to have this fix release asap.

**Comment by totszwai** [comment]
@TorsteinHonsi 
Can't reproduce it for now, we did an upgrade to a newer version of highcharts along with some workaround with the formatter I think, seems to be ok now. Thanks!
