### ISSUE TITLE
Area is drawn like separated vertical lines, when boostThreshold option is used.

### ISSUE THREAD

**Issue by tarasbogach** [highcharts/highcharts#7925]
#### Actual behaviour
Area is drawn like separated vertical lines, when boostThreshold option is used.
Screen Shot http://ibb.co/iSucFx 

#### Live demo
https://jsfiddle.net/xb4yxjj8/2/

#### Product version
Highcharts 6.0.7

#### Affected browser(s)
MacOSX Google Chrome
Version 64.0.3282.167 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @tarasbogach 
Thank you for the reporting. At this moment this is default behaviour but you can use workaround which disables boost on the high zoom level.

Demo:
 - http://jsfiddle.net/BlackLabel/b4mtrrjh/

**Comment by TorsteinHonsi** [comment]
> At this moment this is default behaviour

Just to clear any confusion - the default `boostThreshold` is 5000, so this issue will not appear by default.

**Comment by cvasseng** [comment]
As @sebastianbochan said, this a current, intentional, limitation of the boost module.

The reasoning is that a `boostThreshold` should be set to a value where the SVG renderer naturally takes over when the point density is low enough for the individual lines to be visible.

**Comment by tarasbogach** [comment]
Thank you for answers.
