### ISSUE TITLE
Strange animation with using addPoint with similar duration and interval time 

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#7926]
#### Expected behaviour
The animation should run smoothly.

#### Actual behaviour
Waving is added to the animation.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/t797ewpw/

#### Product version
from version 5

#### Affected browser(s)
All

#### Similar issue
https://github.com/highcharts/highcharts/issues/5294

**Comment by pawelfus** [comment]
Simplified demo: http://jsfiddle.net/t797ewpw/7/

**Comment by TorsteinHonsi** [comment]
#### Workaround
Set a shorter animation duration: http://jsfiddle.net/t797ewpw/11/

**Comment by TorsteinHonsi** [comment]
Things really start disintegrating when the animation duration exceeds the update interval, or more specifically, when we run `Series.addPoint` in midst of an animation: http://jsfiddle.net/t797ewpw/13/
