### ISSUE TITLE
Overlapping data labels and legend labels in exporting chart in ppt or pdf

### ISSUE THREAD

**Issue by MangeshPimprikar** [highcharts/highcharts#7928]
#### Expected behaviour
Labels should not overlap on each other

#### Actual behaviour
data labels and legend labels overlap in exporting chart in ppt or pdf

**Comment by MangeshPimprikar** [comment]
Overlapping data labels and legend labels in exporting chart in ppt or pdf

**Comment by sebastianbochan** [comment]
Hi @MangeshPimprikar 
The default exporting module does not allow to export to ppt. Could you elaborate what kind of converting module, do you use?

**Comment by oysteinmoseng** [comment]
Closing as unable to reproduce with PDF, and PPT is not supported.
