### ISSUE TITLE
startPoint and showInLegend don't always work well together

### ISSUE THREAD

**Issue by pulp260** [highcharts/highcharts#7933]
- Set pointStart on a series once.
- Update series data and set showInLegend to true in one command, or set showInLegend to true first and then set the data.

#### Expected behaviour
The data is really displayed starting from pointStart on the x-axis

#### Actual behaviour
The pointStart set once is ignored and the default (i.e. zero) is applied. The data is actually displayed starting from 0 on the x-axis.

#### Live demo with steps to reproduce
https://jsfiddle.net/gaddini/Ljtvm4vp/13/

#### Product version
Highcharts JS v6.0.7 (2018-02-16)

#### Affected browser(s)
Any

**Comment by pawelfus** [comment]
Hi @pulp260 

Thank you for reporting this issue. It looks like `setData()` does not apply `pointStart` option properly. 

**Workaround:**
Set `pointStart` again in the config:

```javascript
chart.series[0].update({data: data, showInLegend: true, pointStart: chart.series[0].options.pointStart});
```

*Internal note:*
We have this line, which most probably should check if `pointStart` was not set in the config previously: 

https://github.com/highcharts/highcharts/blob/de2d28a9d73718eb9822aa74f69b429e4c4fc77d/js/parts/Dynamics.js#L878-L882

**Comment by pulp260** [comment]
Hi @pawelfus 

Thank you for your swift answer and the workaround you suggested.
I actually already found another workaround, namely setting the new data first (with setData()) *and then* updating `showInLegend` (with update()), like this:

```
chart.series[0].setData(data, false);
chart.series[0].update({showInLegend: true});
```

I would expect then to have to pass `pointStart: chart.series[0].options.pointStart` to the update() call in this case too, if the issue is, like you presume, that the internal code does not check whether `pointStart` was already set in the config. But strangely enough, the update() call with just `{showInLegend: true}` as an argument DOES result in a correct (shifted) display of the data, if it is called **AFTER** setData().

Anyway, that was just an additional note from my side, which might help you debug.
Thanks again.
Regards,
