### ISSUE TITLE
Not able to hide navigator on export..

### ISSUE THREAD

**Issue by sorb999** [highcharts/highcharts#7937]
#### Expected behaviour
Navigator should completely hide on export only

#### Actual behaviour

Only able to set it's height, not able to hide it on export, after setting height its navigator bar is still visible.

#### Live demo with steps to reproduce
https://jsfiddle.net/7xg6rLyL/9/

#### Product version
Highstock 
#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @sorb999 
In the chart.getSVG() use chartOptions with disabled navigator and scrollbar.

Demo:
- https://jsfiddle.net/BlackLabel/3pyd707c/

For the further [support](http://www.highcharts.com/support) questions, use forum / stackoverflow or email.
