### ISSUE TITLE
MACD signalLine lineColor not works when zones is added

### ISSUE THREAD

**Issue by freddysu** [highcharts/highcharts#7945]
#### Expected behaviour
signalLine in MACD should shows the lineColor that is assigned to.

#### Actual behaviour
When I set signalLine lineColor to 'grey', macdLine lineColor to 'blue' and set the zones color to give macd bar different color above and below value 0, the macdLine works correctly, while the signalLine lineColor follows the zones' settings not showing 'grey' lineColor,

#### Live demo with steps to reproduce
http://jsfiddle.net/eoooppaw/11/

#### Product version
6.0.7

#### Affected browser(s)
All browsers

Do I set it wrong or is it a bug? Thanks for help!

**Comment by pawelfus** [comment]
Hi @freddysu 

Thank you for using Highstock and reporting the issue. At this moment MACD line does not support zones. I'm labelling this as a bug - it should be supported like any other line.

*Internal note:*
Similar issue we will have with Stochastic and IKH indicators.
