### ISSUE TITLE
Strange animations on zoom for arearange series type [regression 6.0.7]

### ISSUE THREAD

**Issue by simdevmon** [highcharts/highcharts#7948]
I reported this issue, which was fixed: https://github.com/highcharts/highcharts/issues/6984

Now in HighStock 6.0.7 the animation does not work anymore: 
see jsfiddle here: https://github.com/highcharts/highcharts/issues/6984#issuecomment-340394973

**Comment by KacperMadej** [comment]
Hi @simdevmon 

If the strange animation you wanted to report is the lack of animation, then this is how the problem was resolved.

If you want to have animation in this case (that will work well) then you can open an userVoice idea as this will be an enhancement. https://highcharts.uservoice.com/forums/55896-general

**Comment by simdevmon** [comment]
Hi @KacperMadej 

yes, I reported the strange animation and it was resolved. But now I do not have any animation at all. Even though I enable it, it is still disabled (see last fiddle).

**Comment by TorsteinHonsi** [comment]
Hi @simdevmon, I'm sorry about this, there are cases where animation is complex so we don't support it. In this case, we are zooming from a state where the data is grouped, into original data. So there is not a one-to-one correlation between data points before and after the animation, which makes it more complex than our path animation logic currently supports.

**Comment by simdevmon** [comment]
@TorsteinHonsi Thank you for the explanation. As far as I remember it was working when you posted the fiddle exmaple in issue #6984

I have a snipet from @KacperMadej which I included and now the points are animated, but the lines are not, which looks strange: 
![2018-03-08_10h32_29](https://user-images.githubusercontent.com/16277781/37143686-2d80b0ce-22bc-11e8-9d67-1e5b8c14e7e3.png)

**Comment by TorsteinHonsi** [comment]
@simdevmon @KacperMadej Can we see the live demo?

**Comment by simdevmon** [comment]
@TorsteinHonsi I have a demo here: http://plnkr.co/edit/iAbNxHzKP0mL5gv6nody?p=preview

If you zoom in twice you should see the effect.

**Comment by pawelfus** [comment]
I can confirm that animation in plunker for lines and markers is not in sync.

**Comment by simdevmon** [comment]
The issue has not been resolved, so it should not be closed in my opinion.

**Comment by KacperMadej** [comment]
@simdevmon 
I'm unable to run the demo. Could you reupload it or update it so it will work again?

**Comment by pawelfus** [comment]
I'm afraid this is still the case: https://github.com/highcharts/highcharts/issues/7948#issuecomment-371075688
