### ISSUE TITLE
License links are broken

### ISSUE THREAD

**Issue by quackenbush** [highcharts/highcharts#7954]
#### Expected behaviour

Your license file has bad links:

https://github.com/highcharts/highcharts/blob/master/license.txt

These links are broken:

---

Read more on licensing alternatives here:
- Highcharts: http://shop.highsoft.com/highcharts.html
- Highstock: http://shop.highsoft.com/highstock.html
- Highmaps: http://shop.highsoft.com/highmaps.html

#### Live demo with steps to reproduce

https://github.com/highcharts/highcharts/blob/master/license.txt

#### Product version

Seen on Highcharts master, version d25167bd5906131377ded2fe889cc3f0c07c247f

#### Affected browser(s)

n/a

**Comment by sebastianbochan** [comment]
Hi @quackenbush 
Thank you for the reporting.

@jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
Thanks for reporting @quackenbush. The links has now been updated in the master branch: https://github.com/highcharts/highcharts/blob/master/license.txt
