### ISSUE TITLE
[help needed] how to draw dense data points into a clustered one in highmaps

### ISSUE THREAD

**Issue by DongShi** [highcharts/highcharts#7956]
#### Expected behaviour
Almost all the Geo-Based map library (mapbox, leaflet, esri, etc)  support data clustering feature.
As a reference, check it here: 
https://github.com/SINTEF-9012/PruneCluster

This feature makes senes in that 
1. it can showcase the birdview of the data at a higher level. 
2. In big data case, it exposes such a flexibility to show limited data points.

In our own case, we are suffering from 2, since we have pulling a big mount of data to display from user's DB.

It seems clustering is not supported yet, or do I miss anything from the documents?
Could you give some hints on how to support clustering?
Or at least, how to calculate the distance between two datapoints in highmaps?

#### Actual behaviour
It seems HM does not suppor clustering now.
https://www.highcharts.com/maps/demo/map-bubble

**Comment by pawelfus** [comment]
Hi @DongShi 

Thank you for using Highmaps. At this moment clustering is not supported. Could you vote on our UserVoice for it? Link: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/13753944-marker-clusters-in-highmaps

@oysteinmoseng

**Comment by alvintheodora** [comment]
Hi @pawelfus Is it supported now? If not, do you have any other solution to mimic the clustering?
Thanks in advance

**Comment by oysteinmoseng** [comment]
@alvintheodora @sebastianbochan It is possible to do clustering by manually computing the clusters beforehand and showing them as you zoom the chart. This can be done by listening to the `afterSetExtremes` event on the axis to detect zoom level. One way to do it would be to keep each cluster level in a separate series, and show/hide these on demand: http://jsfiddle.net/gqcbz23v/

**Comment by sebastianbochan** [comment]
@oysteinmoseng datalabels are visible, but should not be in the lowest level.

![zrzut ekranu 2018-08-20 o 14 29 22](https://user-images.githubusercontent.com/2115686/44340546-75471b00-a485-11e8-964a-e44e93890b37.png)

**Comment by oysteinmoseng** [comment]
@sebastianbochan This is an issue (or feature?) that is not related to this demo. See e.g. https://jsfiddle.net/13tjydeo/

**Comment by sebastianbochan** [comment]
@oysteinmoseng You are right, its separate issue.

**Comment by alvintheodora** [comment]
@sebastianbochan @oysteinmoseng Thank you for the workaround. Cheers.

**Comment by pawelfus** [comment]
Since Highcharts (and Highmaps) v8, marker clusters are available: https://www.highcharts.com/docs/advanced-chart-features/marker-clusters
