### ISSUE TITLE
how to set custom image button's height width 

### ISSUE THREAD

**Issue by MuraliKaliappan** [highcharts/highcharts#7957]
try to make custom height width for custom image button 

#### Live demo with steps to reproduce
http://jsfiddle.net/Murali_Kaliappan/2F4pJ/1029/

#### Product version
Highchart 6.0.7

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @MuraliKaliappan 

Thank you for reporting this issue. I'm not sure if it's a bug, according to our docs: https://api.highcharts.com/highcharts/exporting.buttons.contextButton.symbol - string should point to SVG collection of shapes. However, it's almost supported, just `symbolSize` is not properly handled for images. 

**Workaround:**
Use the image that has the same size as expected output or try to define cached values in the Highcharts: http://jsfiddle.net/BlackLabel/2F4pJ/1067/ (may not work with all sizes though..)

**Comment by MuraliKaliappan** [comment]
wanna to know the possibility of image resize that's all , thank you any way ,cheers

**Comment by pawelfus** [comment]
Added scaling for image symbols. Note: `symbolX` and `symbolY` still needs to be applied per image to center it.

**Comment by skuske** [comment]
@pawelfus 

I cannot find the symbolX and symbolY properties in the iOS wrapper... How do I center it there?

**Comment by pawelfus** [comment]
It works in JS version: http://jsfiddle.net/BlackLabel/egcmu4to/

However, it seems that it's missing in API: https://api.highcharts.com/highcharts/exporting.buttons.contextButton ( no `symbolX`, `symbolY` and `symbolSize`), so probably iOS wrapper can not use these options.. 

Reported as #11941

Thanks!

**Comment by sebastianbochan** [comment]
The issue will be fixed in the next iOS wrapper release 7.2.1.
