### ISSUE TITLE
Drillup "Cannot set property 'length' of undefined"

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#7958]
When I add click event to `plotOptions.series.point` and call `chart.drillUp()` I get error

> Drillup "Cannot set property 'length' of undefined".
```
plotOptions: {
        series: {
            point: {
                events: {
                    click: function () {

                    },
               }
          }
    }
}
```

Without `plotOptions.series.point.click` there is no error, but I need the click event

#### Expected behaviour
Without error

#### Actual behaviour
Has error 
![error](https://user-images.githubusercontent.com/6030335/36972361-da148912-207f-11e8-9e08-cc5faa11e86c.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/0t21eyha/

#### Product version
Highcharts version 6.0.7

#### Affected browser(s)
Chrome 64.0.3282.167

**Comment by pawelfus** [comment]
Reported also in custom-events plugin: https://github.com/blacklabel/custom_events/issues/114 - it looks like a bug in the plugin, not in Highcharts.

**Comment by balkarov** [comment]
@pawelfus hello. thank you. Yes, I closed issue before your message.
There is bug in the plugin.
