### ISSUE TITLE
IE versus Rest of the world bug when having '&' in a serie's name

### ISSUE THREAD

**Issue by lemoinem** [highcharts/highcharts#796]
Hello,

I happen to have a graph (line graph) of which one of the series has an '&' in its name.

I have two different buggy behaviors:

If I escape the & in &amp;amp; (HTML/XML style), it displays correctly on IE6-8, but display a literal &amp;amp; in the legend of any other browser.

If I don't escape it and simply put '&', it displays correctly on "any other browser" but it crashes the legend in IE6-8 everything or at least the first word after the & seems to be skipped and the legend border is messed up.

**Comment by TorsteinHonsi** [comment]
Closed due to inactivity.
