### ISSUE TITLE
Highmaps with custom GeoJson doesn't get Lat/Long right

### ISSUE THREAD

**Issue by Menighin** [highcharts/highcharts#7960]
#### Expected behaviour
The city to be plotted on the same points of the maps

#### Actual behaviour
When the custom geojson is loaded, the city is plotted in another place. Also the lat/long coordinates are messy.

So, I get that this maybe is because I am messing around with the `crs` parameter for the geo json, but I have searched a lot around and tried to edit the map on QGis and couldnt make it work. I followed the [documentation](https://www.highcharts.com/docs/maps/latlon) for getting the map to work with the `crs`, but even after reprojecting around with QGis it doesn't work. 

I have also created [this topic](https://gis.stackexchange.com/questions/273622/qgis-how-to-reproject-a-layer) (please read) on Stack Exchange and a guy raised a question that maybe highchart does something internal with the geojson and I would like to know if that is the case. Also, on the `hc-transform` for the oficial Highmaps geojson there are some properties besides `crs` that are not documented (`jsonres`, `xoffset`, etc.). Can you guys give some information about them and how can I find the right ones for my custom geojson? 

#### Live demo with steps to reproduce
http://jsfiddle.net/0vm8a4x3/
- Uncoment Line 8
- Custom Brazil map is loaded
- `Belo Horizonte` is plotted in the wrong place

#### Product version
Highcharts 6.0.6

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi,

If you are using a custom map, consider using the Proj4js library to convert between projections.
http://proj4js.org/

We are trying to keep github for bugs, so please contact support in the future.
https://www.highcharts.com/support

**Comment by Menighin** [comment]
Hi @KacperMadej thanks for the reply.

Please, give this a careful look. I do believe there's something **wrong** or at least **not clear** on how Highmaps deals with GeoJsons because of the parameters defined on `hc-transform` that are not documented. Also, on [this question](https://gis.stackexchange.com/questions/273622/how-to-reproject-a-layer?noredirect=1#comment436365_273622) there are people suggesting that the projection used does not make sense. Can you please point me on any direction?

You mentioned that I should consider using proj4js, but how? It supose to be the same thing as using QGis to Reproject Layer, no?

I tried using proj4js to simply reproject as you can see here: http://jsfiddle.net/aq69ancm/

But it is still plotting the map wrong (and with some missing pieces).

**Comment by KacperMadej** [comment]
I don't know the projection of your map. Are lat & long working correctly for your map in QGis?

@oysteinmoseng Maybe you have more info for the case?

**Comment by Menighin** [comment]
Hi @KacperMadej thanks again.

I finally solved it. Indeed QGis was giving me some wrong information about my map projection. It was not `WGS84` as it was showing. After asking a friend, he looked into it with another software and found out the right one. Then setting the right `crs` on the `hc-transform` solved it and Highmaps is plotting it correctly. 

Sorry for the inconvenient and thanks again!

**Comment by KacperMadej** [comment]
@Menighin 

Thank you for sharing your solution.
I'm happy to hear that the map is working for you.
Just for the possible future questions - what was the another software?

**Comment by Menighin** [comment]
Ah yes, it was ArcGIS!

**Comment by zhalice2011** [comment]
hello everyone

 I put coordinates of all counties into coordinates array of one object and change its type to 'MultiPolygon'." 

and I get The following map

![image](https://user-images.githubusercontent.com/24289349/53092109-d2b04780-354e-11e9-8acf-e7ea8ceb17f6.png)

But the demand for the product is The following PIC

![image](https://user-images.githubusercontent.com/24289349/53091834-0b9bec80-354e-11e9-8669-b96770d73fef.png)


Please help children!

Excuse me, how can I eliminate the border ?

My code :  https://github.com/zhalice2011/highcharts-custom-region

**Comment by KacperMadej** [comment]
Hi @Menighin 

This is a technical support question, so you should contact technical support using one of the available channels: https://www.highcharts.com/blog/support/

In general, documentation for custom maps is here: https://www.highcharts.com/docs/maps/custom-maps

**Comment by Menighin** [comment]
@KacperMadej I think you wanted to mark @zhalice2011

**Comment by KacperMadej** [comment]
Right, sorry :)
