### ISSUE TITLE
Bug: tick collapsing when two Y-axis

### ISSUE THREAD

**Issue by fiantsev** [highcharts/highcharts#7961]
#### Expected behaviour
Ticks & labels of the left Y-axis remain unchanged (see Image 1, 2 below)

#### Actual behaviour
Ticks become collapsed when appears second Y-axis

#### Live demo with steps to reproduce
http://jsfiddle.net/ztLau676/1/

Steps:
1 First I have a chart with just one axis and tickInterval = 1
2 Then im trying to add second Y-axis (for one serie)
3 Ticks&labels from the first axis are collapsed into top-left corner

**Image 1**
![image](https://user-images.githubusercontent.com/25036176/37031413-b0e5cb20-214f-11e8-9458-42903b9fd7b8.png)
**Image 2**
![image](https://user-images.githubusercontent.com/25036176/37031446-d50c4f38-214f-11e8-8886-e0dcb41ccf39.png)

#### Product version
Highcharts 6.0.7

#### Affected browser(s)
Chrome Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @fiantsev 
Thank you for the reporting.

The solution is setting the alignTicks parameter as false, which will separate aligning ticks between axes.
Demo:
- http://jsfiddle.net/BlackLabel/62obr9hq/

**Comment by fiantsev** [comment]
@sebastianbochan thank you, man 👍

**Comment by sebastianbochan** [comment]
@TorsteinHonsi should we consider initial demo as bug ?

**Comment by TorsteinHonsi** [comment]
Yes, I would say it is a bug. It is not clear how aligned axes would work in this case, as a `tickInterval` of 1 obviously isn't compatible with aligning to the other axis. Also, setting `tickInterval` to 1 when the axis range is 30k is not very meaningful.

But overlapping labels is a bug in any case.

Simplified demo: http://jsfiddle.net/highcharts/2ak8nsra/
