### ISSUE TITLE
Breaks not working on solid guages

### ISSUE THREAD

**Issue by arj-ary** [highcharts/highcharts#7962]
#### Expected behaviour
I am trying to get the below desired behaviour - 
![image](https://user-images.githubusercontent.com/10525258/37039248-9af95f62-211c-11e8-8e5c-d9ed84227899.png)

#### Actual behaviour
The breaks don't seem to work right, i have made sure i have included the broken axis module     <script src="https://code.highcharts.com/modules/broken-axis.js"> and used breaks like below
breaks: [{
              from: 100,
              to: 120,
              breakSize: 20,
              repeat: 10
          }],

#### The below fiddle demonstrates the issue Live demo with steps to reproduce
http://jsfiddle.net/arj_ary/1g0v9Lhg/42/

#### Product version

v6.0.7
#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @arj-ary 

Thank you for reporting this issue. I must say, it is interesting idea of using `gauge`-series! I see you use `plotBands` to show value on a chart. In that case, you can split plotBands into separate ones, take a look: http://jsfiddle.net/BlackLabel/8guq6bht/2/ (or, something similar automated a bit: http://jsfiddle.net/BlackLabel/8guq6bht/11/)

However, I suggest to use solid-gauge series instead, see: http://jsfiddle.net/BlackLabel/gsgeexx9/8/ - in this case, white spaces can be easily controlled in pixels   by `tickWidth` option, positions are set in `tickPositions`, everything with nice animation.

**Comment by arj-ary** [comment]
@pawelfus that worked great!. Thank you.
