### ISSUE TITLE
findNearestPointBy is broken in highstock

### ISSUE THREAD

**Issue by choudhary001** [highcharts/highcharts#7963]
#### Expected behaviour
Expected behavior is with findNearestPointBy set to 'xy', tooltip should appear for both points that have different y value for same x value.

#### Actual behaviour
findNearestPointBy behavior is broken.

#### Live demo with steps to reproduce
http://jsfiddle.net/xhdg8ooo/

#### Product version
Highstock - https://code.highcharts.com/stock/highstock.js

**Comment by pawelfus** [comment]
Hi @choudhary001 

Thank you for reporting this issue. This is not related to Highstock, Highcharts works the same way: http://jsfiddle.net/BlackLabel/xhdg8ooo/3/

If you have multiple points, then you shouldn't use `line` series, but `scatter` with enabled `lineWidth`, please take a look: http://jsfiddle.net/BlackLabel/xhdg8ooo/5/
