### ISSUE TITLE
Cannot set chart.reflow with chart.update()

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#7965]
#### Expected behaviour
To be able to toggle `chart.reflow`.

#### Actual behaviour
Cannot change it with `chart.update()`.

#### Live demo with steps to reproduce
1. Open http://jsfiddle.net/rc8h4age/1/
2. Click the "reflow: false" button.
3. Drag the splitter in the middle to resize the pane. The chart still resizes.

#### Product version
v6.0.7

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
_Internal note:_
Unit tests coming up in a separate commit.

**Comment by cosycode** [comment]
`chart.update({reflow:true})` is still failing, if chart gets initialized with `reflow: false`: http://jsfiddle.net/pxamkgff/

**Comment by TorsteinHonsi** [comment]
I don't think so... Your fiddle used v6.0.7, which is the current release. See http://jsfiddle.net/highcharts/pxamkgff/2/.

**Comment by cosycode** [comment]
Yes, you are correct. Sorry for the mistake.
