### ISSUE TITLE
View Data showing empty table cells for 0 values

### ISSUE THREAD

**Issue by kai2468** [highcharts/highcharts#7969]
#### Expected behaviour

Shows "0" in the table cell when selecting the View Data option in the export menu. 

#### Actual behaviour

Shows an empty cell instead

#### Live demo with steps to reproduce
http://jsfiddle.net/89ukaymv/
Click the View Data option in the export menu, the table cell for January will be empty.

https://github.com/highcharts/highcharts/blob/master/js/modules/export-data.src.js#L550

Issue seems to be in the modules/export-data.src.js file. getCellHTMLFromValue function, I think because its a 0 value. Its counting that as false so just assigning an empty string to the variable

**Comment by pawelfus** [comment]
Hi @kai2468 

Thank you for reporting this bug. Probably you are right, this checking should be improved.

*Internal note:*
It's a regression from af2908318 commit.

**Comment by SimoneMSR** [comment]
Could we just update the code of  `getCellHTMLFromValue` in `export-data.js` ?
the accused row seems to be the 539 in `export-data.src.js`
```var val = value || '',```
and can be replaced, say, with
```var val = value != null ? value : value || '' ```

**Comment by SimoneMSR** [comment]
Just realized that Highcharts version 6.1.1 solves this issue. Sorry!

**Comment by sebastianbochan** [comment]
Thank you for the feedback.
