### ISSUE TITLE
Mobile Pie chart with long labels

### ISSUE THREAD

**Issue by bronze** [highcharts/highcharts#7975]
#### Expected behaviour
On mobile, wrap long labels into a more readable format

#### Actual behaviour
Using `useHTML:true,` it overflows, without it i have ellipsis.
Ive been reading through older issues but i cant seem to find a solution.
This older isue (jun/2017) is pretty much close to what im experiencing: Cannot disable Pie dataLabels text-ellipsis functionality https://github.com/highcharts/highcharts/issues/6841#issuecomment-309437879)
But i cant find/reproduce a solution.
Any help greatly appreciated.

#### Live demo with steps to reproduce
https://jsfiddle.net/wxy0292h/

#### Product version
Highcharts JS v6.0.0 (2017-10-04)

#### Affected browser(s)
Chrome

Below are some screenshots of production
![screen shot 2018-03-08 at 08 49 34](https://user-images.githubusercontent.com/170220/37149705-c0a40d2e-22ad-11e8-9f15-952f97899571.png)
This was without expliciting `size` under plotOptions/pie
![screen shot 2018-03-08 at 08 49 51](https://user-images.githubusercontent.com/170220/37149706-c0c514ec-22ad-11e8-840b-eea2db3e5d9a.png)

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! With the fix, you can set `dataLabels.style.textOverflow` to `clip` to enable word-wrap: https://jsfiddle.net/highcharts/wxy0292h/15/

**Comment by n-kumari** [comment]
Using `dataLabels.style.textOverflow: clip` displays the label over pie chart on mobile. Below is the screenshot from iOS simulator. 

<img width="396" alt="screen shot 2018-07-18 at 10 22 11 am" src="https://user-images.githubusercontent.com/30132665/42888138-8f61daf4-8a75-11e8-927f-e7d12e439ffb.png">
