### ISSUE TITLE
Histogram documentation suggestion

### ISSUE THREAD

**Issue by camsteffen** [highcharts/highcharts#7979]
On the docs page for histogram series, there should be something saying that, if you need a histogram for pre-aggregated data, use column chart with such and such settings. There is a comment explaining this on the column chart page, but that's not where I looked first.

https://www.highcharts.com/docs/chart-and-series-types/histogram-series
https://www.highcharts.com/docs/chart-and-series-types/column-chart

**Comment by pawelfus** [comment]
Hi @camsteffen 

Thank you for letting us know! We will update the docs. Sorry for the inconvenience!
