### ISSUE TITLE
heatmap export csv 

### ISSUE THREAD

**Issue by kamalgupta0808** [highcharts/highcharts#7980]
I am currently using export-data.csv for exporting heatmap chart data to CSV. I would like to export in a certain format that is same as column stacked chart. Can you help?

**Comment by pawelfus** [comment]
Hi @kamalgupta0808 

As answered in #7144 : 

> It looks impossible at this moment - stacked column is build from multiple series, heatmap is just one series. Maybe we could add custom callback, where user could write it's own generator for rows/columns/headers.

I created simple plugin to modify how rows and columns are rendered: https://jsfiddle.net/BlackLabel/1xyo7067/9/

Snippet: 

```javascript
(function(H) {
  H.wrap(H.Chart.prototype, 'getDataRows', function(p, opt) {
    var rows = p.call(this, opt),
      longRows = [],
      categories = [],
      yCategories = [rows[0][0]];

    H.each(rows, function(row) {
      var index = categories.indexOf(row[0]);

      if (index < 0) {
        index = categories.push(row[0]) - 1;
      }

      if (!longRows[index]) {
        longRows[index] = [row[0]];
        longRows[index].x = index;
        longRows[index].xValues = [index];
      }

      longRows[index].push(row[2]);
    });

    longRows[0] = yCategories.concat(this.yAxis[0].categories);

    return longRows;
  });
})(Highcharts);
```

**Comment by kamalgupta0808** [comment]
Thanks for the reply @pawelfus 
Heat Map and Bubble Chart are working fine but the callback function is now affecting my column stack chart. Can you suggest the callback function for column stack also.

**Comment by pawelfus** [comment]
Hi @kamalgupta0808 

Modified demo: https://jsfiddle.net/BlackLabel/x0o6ddaa/2/ - now you can use conditionally custom callback by setting `exporting.dataExportModifier` in the chart.

**Comment by kamalgupta0808** [comment]
I have used conditionally custom callback in both heatmap and bubble chart but once it is used in heatmap (The csv made is correct) , then when i make bubble chart, csv exported in bubble chart has empty data. Same is true when i make bubble chart first time (csv made is correct), but then when i make heatmap, data in csv is empty.

**Comment by pawelfus** [comment]
Could you recreate issue in jsFiddle? I will take a look. Thanks!

**Comment by kamalgupta0808** [comment]
I have a javascript code that has several functions to create heatmap, column stack chart, line charts, pie charts, bubble chart, etc. They are are called from another js file. All export functions are working fine(CSV made correctly) but i was getting problem while exporting heatmap and bubble chart. I  used conditionally custom callback in both heatmap and bubble chart function. So when i export heatmap first, it works fine but then when i export bubble chart, csv made has data column empty. Vice-Verse is the case when i make bubble chart first, it is made fine and when i make heatmap, then csv data column is empty. 
//Bubble Chart function
function show_bubble(encoded_data,div_id,title,xAxis,yAxis,label_data,xAxisVal,yAxisVal,arrf_data,data_labels,graph_color,level,style_data) {
	var label_size = parseInt(style_data['label_size']);
	xaxis_font = parseInt(style_data['xaxis_font']);
	xaxis_font = xaxis_font + 'px';
	yaxis_font = parseInt(style_data['yaxis_font']);
	yaxis_font = yaxis_font + "px";
	//swal(xaxis_font);
	invert_graph = parseInt(style_data['invert_graph']);
	var label 	= JSON.parse(label_data);
	var arrf 	= JSON.parse(arrf_data);
	var yAx_arr	= JSON.parse(yAxis);
	title_chart=label_for_bar3D_graph(arrf_data);
	console.log(encoded_data);
	// swal(graph_color);
	// swal(encoded_data);
	// swal(xAxis);
	// swal(yAxis);
	$('#'+div_id).show();
	if(div_id == 'large-graph-box'){
		$("html, body").scrollTop($('#'+div_id).offset().top);
	}


(function(H) {
  H.wrap(H.Chart.prototype, 'getDataRows', function(p, opt) {
    var rows = p.call(this, opt);
    console.log(rows);
    if (this.options.exporting.dataExportModifier) {
    	rows = this.options.exporting.dataExportModifier(this, rows);
    }

    return rows;
  });
})(Highcharts);



function dataIntoColumn (chart, rows) {
     var longRows = [],
      categories = [],
      yCategories = [rows[0][0]].concat(chart.yAxis[0].categories);

    Highcharts.each(rows, function(row) {
      var index = categories.indexOf(row[0]);

      if (index < 0) {
        index = categories.push(row[0]) - 1;
      }

      if (!longRows[index]) {
        longRows[index] = [row[0]];
        longRows[index].x = index;
        longRows[index].xValues = [index];
      }

      longRows[index][yCategories.indexOf(row[1])] = row[2];
    });

    longRows[0] = yCategories;
     console.log(longRows);

    return longRows;
}


	$('#'+div_id).highcharts({
		colors: graph_color,
        chart: {
			panning: true,
            panKey: 'shift',
			backgroundColor:style_data['bgcolor'],
			inverted:invert_graph,
            type: 'bubble',
            zoomType: 'xy'
        },

        title: {
			 style: {
                color: style_data['titleColor'],
            },
            text: title
        },
		tooltip:{
			enabled:true,
			formatter:function(){
				return label[this.x][this.y];
			}
		},
		xAxis: {
			allowDecimals:false,
			labels: {
				autoRotation: [-10, -20, -30, -40, -50, -60, -70, -80, -90]
			},
			 title: {
                text: title_chart
            },
			gridLineWidth: 1,
			labels: {
                style: {
                    fontSize: xaxis_font,
                }
            },
            categories: JSON.parse(xAxis)
        },
		yAxis: {
			allowDecimals:false,
			min:0,
            categories: yAx_arr,
            title: {
                text: yAxisVal
            },
			labels: {
                style: {
                    fontSize: yaxis_font,
                }
            },
        },
		plotOptions: {
			series:{
				cursor: 'pointer',
				point: {
					events: {
						click: function() {
							show_patents_from_graph(div_id,arrf[this.x][this.y],'',0);
						}
					}
				},
				dataLabels: {
                    enabled: data_labels,
					style: {
						fontSize: label_size+'px',
                    }
                }
			},
			bubble:{
				minSize: 0
			}
		},
        series: [{
			name: xAxisVal,
			sizeBy: 'width',
            data: JSON.parse(encoded_data),
        }],
           exporting: {
      csv: {
        columnHeaderFormatter: function(item, key) {
        	console.log(encoded_data);
          if (key === 'y') {
            return item.yAxis.options.title.text;
          }
          return false;
        }
      },
      dataExportModifier: dataIntoColumn,
      showTable: true
    }
    });
}

// HeatMap function
function heat_map_3D(div_id,title,xAxisVal,yAxisTxt,yAxisVal,dataCount,arrf_data,data_labels,graph_color,level,style_data,xAxisTxt) {
 var label_size = parseInt(style_data['label_size']);
 xaxis_font   = parseInt(style_data['xaxis_font']);
 xaxis_font  = xaxis_font + 'px';
 yaxis_font   = parseInt(style_data['yaxis_font']);
 yaxis_font  = yaxis_font + 'px'; 
 invert_graph = parseInt(style_data['invert_graph']);
 var arrf = JSON.parse(arrf_data);
 $('#'+div_id).show();
 title_chart=label_for_bar3D_graph(arrf_data);
 console.log(xAxisTxt);
// var flag_grap2=1;
 // swal(arrf);
 /*
 if(arrf != undefined){
  arrf = JSON.parse(arrf);
 }
 if(div_id == 'large-graph-box'){
  $("html, body").scrollTop($('#'+div_id).offset().top);
 }
 */
(function(H) {
  H.wrap(H.Chart.prototype, 'getDataRows', function(p, opt) {
    var rows = p.call(this, opt);
         console.log(rows);

    if (this.options.exporting.dataExportModifier) {
    	rows = this.options.exporting.dataExportModifier(this, rows);
    }

    return rows;
  });
})(Highcharts);


function dataIntoColumn (chart, rows) {
     var longRows = [],
      categories = [],
      yCategories = [rows[0][0]].concat(chart.yAxis[0].categories);
      console.log(rows);
    Highcharts.each(rows, function(row) {
      var index = categories.indexOf(row[0]);

      if (index < 0) {
        index = categories.push(row[0]) - 1;
      }

      if (!longRows[index]) {
        longRows[index] = [row[0]];
        longRows[index].x = index;
        longRows[index].xValues = [index];
      }

      longRows[index][yCategories.indexOf(row[1])] = row[2];
    });

    longRows[0] = yCategories;
    console.log(longRows);
    return longRows;
}




  // callback_graph(Highcharts,flag_grap2);
 $('#'+div_id).highcharts({
        chart: {
   panning: true,
            panKey: 'shift',
   backgroundColor: style_data['bgcolor'],
   inverted:invert_graph,
            type: 'heatmap',
            // marginTop: 40,
            // marginBottom: 80,
            plotBorderWidth: 1
        },
        title: {
    style: {
                color: style_data['titleColor'],
            },
            text: title
        },

        xAxis: {
   allowDecimals:false,
   title: {
    text: title_chart
   },
   labels: {
    autoRotation: [-10, -20, -30, -40, -50, -60, -70, -80, -90]
   },
            categories: JSON.parse(xAxisVal),
   labels: {
                style: {
                    fontSize: xaxis_font,
                }
            },
   // ['Alexander', 'Marie', 'Maximilian', 'Sophia', 'Lukas', 'Maria', 'Leon', 'Anna', 'Tim', 'Laura']
        },

        yAxis: {
   allowDecimals:false,
   title: {
    text: yAxisTxt
   },
   labels: {
                style: {
                    fontSize: yaxis_font,
                }
            },
            categories: JSON.parse(yAxisVal)
   // ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        },

        colorAxis: {
            min: 0,
            minColor: '#FFFFFF',
            maxColor: graph_color[0]
        },

        legend: {
            align: 'center',
            layout: 'horinzontal',
            // margin: 0,
            verticalAlign: 'bottom',
            // y: 25,
            // symbolHeight: 320
    
        },
  plotOptions: {
            series:{
    cursor: 'pointer',
    point: {
     events: {
      click: function() {
       show_patents_from_graph(div_id,arrf[this.x][this.y],'',0);
      }
     }
    }
   }
        },

  tooltip: {
            formatter: function () {
                // return '<b>' + this.series.xAxis.categories[this.point.x] + '</b> '+txt1+' <br><b>' + this.point.value + '</b> '+txt2+' <br><b>' + this.series.yAxis.categories[this.point.y] + '</b>';
                // flag_grap2=1;
                return '<b>' + this.series.xAxis.categories[this.point.x] + '</b> , <b>'+ this.series.yAxis.categories[this.point.y] + " (" + this.point.value + ')</b>';
            }
        },

        series: [{
            name: 'Sales per employee',
            borderWidth: 1,
            data: JSON.parse(dataCount),
   // [[0, 0, 10], [0, 1, 19], [0, 2, 8], [0, 3, 24], [0, 4, 67], [1, 0, 92], [1, 1, 58], [1, 2, 78], [1, 3, 117], [1, 4, 48], [2, 0, 35], [2, 1, 15], [2, 2, 123], [2, 3, 64], [2, 4, 52], [3, 0, 72], [3, 1, 132], [3, 2, 114], [3, 3, 19], [3, 4, 16], [4, 0, 38], [4, 1, 5], [4, 2, 8], [4, 3, 117], [4, 4, 115], [5, 0, 88], [5, 1, 32], [5, 2, 12], [5, 3, 6], [5, 4, 120], [6, 0, 13], [6, 1, 44], [6, 2, 88], [6, 3, 98], [6, 4, 96], [7, 0, 31], [7, 1, 1], [7, 2, 82], [7, 3, 32], [7, 4, 30], [8, 0, 85], [8, 1, 97], [8, 2, 123], [8, 3, 64], [8, 4, 84], [9, 0, 47], [9, 1, 114], [9, 2, 31], [9, 3, 48], [9, 4, 91]],
            dataLabels: {
                enabled: data_labels,
    style:{
     fontSize : label_size+'px',
    },
                color: '#000000',
            }
        }],
    //                 exporting: {
    //   csv: {
    //     columnHeaderFormatter: function(item, key) {
    //   	// flag_grap2=1;
    //       if (key === 'y') {
    //         return item.yAxis.options.title.text;
    //       }
    //       return false;
    //     }
    //   },
    //   showTable: true
    // }
    exporting: {
      csv: {
        columnHeaderFormatter: function(item, key) {
          if (key === 'y') {
            return item.yAxis.options.title.text;
          }
          return false;
        }
      },
      dataExportModifier: dataIntoColumn,
      showTable: true
    }

    });
}

**Comment by pawelfus** [comment]
Thank you for the code-sample. This is most probably caused by applying this snippet twice:

```
(function(H) {
  H.wrap(H.Chart.prototype, 'getDataRows', function(p, opt) {
    var rows = p.call(this, opt);
    console.log(rows);
    if (this.options.exporting.dataExportModifier) {
    	rows = this.options.exporting.dataExportModifier(this, rows);
    }

    return rows;
  });
})(Highcharts);
```

Could you put this in a separate file, for example `highcharts-7980.js` and include this plugin after Highcharts? Like this:

```html
<script src="js/highcharts.js"></script>
<script src="js/highcharts-7980.js"></script>
```

It works fine when using my simple dataset: https://jsfiddle.net/BlackLabel/x0o6ddaa/8/

Of this won't help, could you contact our support? See details: https://www.highcharts.com/support

**Comment by kamalgupta0808** [comment]
Thank you @pawelfus 
Now my code works fine. CSV made is correct in all the cases. But I m getting empty cells, when there is no data available. Is there any way I can fill 0 instead of empty cell when i export csv?

**Comment by pawelfus** [comment]
Hi @kamalgupta0808 

This is expected behaviour. You can modify my code fo fill in missing parts, or add 0-values to your original dataset.

Alternatively, contact our support team: https://www.highcharts.com/support
