### ISSUE TITLE
Highcharts update scroll issue- scroll to initial position

### ISSUE THREAD

**Issue by shashivardhan** [highcharts/highcharts#7985]
I am having an issue with Highcharts highstock column chart. With xaxis min=0, max=5 [page size] which has 20 categories.
After the initial load when you scroll the xaxis to the end and then click on modify data. On this action I will invoke an api and update the series data. **'The chart displays as No data to display'** even if there is one category. I wanted to reset scroll to initial position, which I cannot do for categories. You will need to move scroll manually

Also Since there is only one category and I do not want other categories to display as numbers.
https://jsfiddle.net/shashi3337/zcf8kvgx/7/

I am updating the chart to modify xaxis min and max to set max as 0 [ 1 category] to remove numbers.
https://jsfiddle.net/shashi3337/zcf8kvgx/5/.

Now when you click on Add data which adds back the data. I am resetting min=0 and max=5. Now
I just see only 1 category per page scroll.

**Expected Behavior**
I expect the scroll bar to be automatically scrolled back after I click **modify data** button and when I click on add data button I expect to see 6 categories per page scroll on xaxis.

**Comment by pawelfus** [comment]
Hi @shashivardhan 

Thank you for reporting the issue. You need to use `xAxis.setExtremes()` to modify extremes on the chart. At this moment, extremes set by user (e.g. by scrollbar) have the highest priority and are not cleared when you remove all series. Example for you: https://jsfiddle.net/BlackLabel/pp2qpxks/

I'm not sure if we should change this: I can imagine opposite case, when user **wants** to display extremes outside the given dataset (e.g. more categories than data, no nulls or simply empty space on the right side). @TorsteinHonsi 

Note: When applying multiple changes on a chart, set `redraw` flag to false and redraw chart only once, in the last action (or use `chart.redraw()`).
