### ISSUE TITLE
Chart Overlapping issue

### ISSUE THREAD

**Issue by vishalsingh119** [highcharts/highcharts#7987]
For better understanding please refer screenshot - https://prnt.sc/ip95hp

If we have more data, data in the chart is overlapping. Normal data showing like this- https://prnt.sc/ip95x8
I already tried responsive and auto height but no effect.

**Comment by sebastianbochan** [comment]
Hi @vishalsingh119 
Please try to set the [pointRange]() parameter. If it will not solve your issue, please replicate your example as live demo on the jsfiddle.net and contact with us by forum / stackoveflow or email. 
You can find more information about our support [here](http://www.highcharts.com/support)

**Comment by vishalsingh119** [comment]
Hi,
The demo for overlapping is here - https://jsfiddle.net/efnw1cvo/8/

**Comment by pawelfus** [comment]
Hi @vishalsingh119 

You have too many points for a given height. At this moment, every bar has width=1, adding border (1px for both sides) we get 3px per bar, 200+ points, where plotting area is only about 250px.

I see two possible solutions here:

- increase chart's height: https://jsfiddle.net/BlackLabel/efnw1cvo/18/
- use Highstock with scrollbar: https://jsfiddle.net/BlackLabel/efnw1cvo/19/

**Comment by vishalsingh119** [comment]
Thanks a lot. use of Highstock with scrollbar fixed that issue.
