### ISSUE TITLE
Changing the color of Ichimoku Cloud

### ISSUE THREAD

**Issue by ourarash** [highcharts/highcharts#7988]
#### Expected behaviour
Color of the cloud changes  when Senkou Span A and B cross.

#### Actual behaviour
Color of the cloud is always the same

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/stock/indicators/ichimoku-kinko-hyo/

#### Affected browser(s)
All

Is there any way to change the cloud color when  Senkou Span A and B cross like in the attached picture?
![image](https://user-images.githubusercontent.com/20846105/37256307-f61f7014-2515-11e8-81b0-27cbcc059a93.png)

**Comment by TorsteinHonsi** [comment]
This feature has also been requested for the common arearange series, see https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/3240151-area-range-with-flipping-colors-after-lines-cros. Interestingly, the use case seems to be Ichimoku indicators.

**Comment by pawelfus** [comment]
*Internal note:*
I see two possible solutions to implement this:
- reuse `zones` - can be calculated at the same time as data. Sounds easy, but requires full support for zones in first place. I'm not sure about the performance with multiple long paths that are clipped, too
- use the same solution as @sebastianbochan some time ago: calculate separate shapes for red/green manually and put into two paths

**Comment by TorsteinHonsi** [comment]
The second one probably performs better.

**Comment by wchmiel** [comment]
I followed @pawelfus second suggestion and prepared a workaround for this issue. Check the demo: [http://jsfiddle.net/wchmiel/vahmo6kt/](http://jsfiddle.net/wchmiel/vahmo6kt/).

**Comment by jnoorman** [comment]
@wchmiel worked perfectly, thanks.
