### ISSUE TITLE
Strange fill flickering on data update when xAxis: { minPadding: 0 }

### ISSUE THREAD

**Issue by kushn1ruk** [highcharts/highcharts#7990]
#### Expected behaviour
To render properly

#### Actual behaviour
Sometimes strange SVG fill flickering appears

#### Live demo with steps to reproduce
I've tried to compose a live demo, but it renders fine 🤷‍♂️
http://jsfiddle.net/LLExL/10052/

#### Product version
Highcharts JS v6.0.7 (2018-02-16)

#### Affected browser(s)
Latest Chrome
<img width="1068" alt="screen shot 2018-03-12 at 10 39 38" src="https://user-images.githubusercontent.com/44265/37273588-f2dd60f0-25e2-11e8-9554-828bfe4a5fcc.png">

**Comment by sebastianbochan** [comment]
Hi @kushn1ruk 
Thank you for the reporting, It looks like known bug, reported here:
- https://github.com/highcharts/highcharts/issues/7662
