### ISSUE TITLE
Crash during chart creation in highstock

### ISSUE THREAD

**Issue by manu-st** [highcharts/highcharts#7995]
#### Expected behaviour
No crash.

#### Actual behaviour
Crash when trying to call `getExtremes` on an X-axis that doesn't exist yet.

#### Live demo with steps to reproduce
http://jsfiddle.net/xccgbzru/

#### Product version
Latest version of highstock.

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @manu-st 

Thank you for reporting the issue. It's connected to Highstock components: rangeSelector, Navigator and Scrollbar require an xAxis to be connected to. With disabled scrollbar (and others) it works fine: http://jsfiddle.net/BlackLabel/xccgbzru/5/

**Comment by TorsteinHonsi** [comment]
The problem also goes away when omitting the empty `xAxis: []` in the configuration.
