### ISSUE TITLE
Spiderweb Chart: Changing startAngle to particular angle, one data point on X-axis disappears

### ISSUE THREAD

**Issue by tanmayshah95** [highcharts/highcharts#7996]
#### Expected behaviour
On changing Start angle of polar X axis, all X-Axis data points should get plotted from given angle.
There should not be any data loss.

#### Actual behaviour
On changing startAngle to some particular angle, one data point on X-Axis disappears.
some angles on which issue is reproduced are: 15, 120, 135, 225, 285, 300.

#### Live demo with steps to reproduce
startAngle: 0   -->  http://jsfiddle.net/dhr5dxxa/
startAngle: 15 -->  http://jsfiddle.net/dhr5dxxa/3/

Verify that last data point is not plotted, when startAngle = 15.

**Comment by pawelfus** [comment]
Hi @tanmayshah95 

Thank you for reporting this bug.


Note:
It looks like last point is rendered at the same tick as the first one and `autoConnect` is wrong.
