### ISSUE TITLE
Data labels are not rendering if the series is set to visible: false

### ISSUE THREAD

**Issue by MounikaSiva** [highcharts/highcharts#7998]
Though the series is invisible I want the data labels to be printed.
But, the data labels are also invisible.
Please find the sample in the link: http://jsfiddle.net/fdvw8rqx/430/

**Comment by pawelfus** [comment]
Hi @MounikaSiva 

Thank you for reporting the issue. This is expected behaviour. When series is hidden, all linked to the series elements are hidden. If you want to show labels even if the series is hidden, please contact with our support: https://www.highcharts.com/support
