### ISSUE TITLE
Highmaps: mappoint points given as array doesn't work despite set keys

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7999]
#### Behaviour
Turbo mode is not working for `mappoint` and points given in an array form, with defined `series.keys`, aren't working.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/mtrcxyum/
London is not visible.

#### Internal notes
This code: https://github.com/highcharts/highcharts/blob/c1f2015ccd55d76b12316bcdacaf4e3ca30dc580/js/parts-map/MapPointSeries.js#L51-L60

Runs before `keys` are even checked, so the `merge(options, this.series.chart.fromLatLonToPoint(options))` doesn't run and x and y are not created for points.

#### Workaround
After running code with points set as objects you can extract x and y coords and use them in a array format data point. Demo: http://jsfiddle.net/BlackLabel/mtrcxyum/1/ (London is showing fine, other green points are added just to trigger the `turboThreshold`)

**Comment by TorsteinHonsi** [comment]
Thinking out loud @oysteinmoseng - maybe we should hook on to the `optionsToObject` function instead?
