### ISSUE TITLE
Display BUG？

### ISSUE THREAD

**Issue by neo-hu** [highcharts/highcharts#8005]
![1](https://user-images.githubusercontent.com/7464483/37392703-dbb4b784-27a9-11e8-9705-fb41bcfeb1ac.png)
What is this BUG

**Comment by sebastianbochan** [comment]
Hi @neo-hu 
Thank you for the reporting. It looks like a known bug reported here: https://github.com/highcharts/highcharts/issues/7662

If it is something different, please reopen the ticket and supply us a live demo.
