### ISSUE TITLE
series.visible (boolean) does not allow 1/0, only true/false 

### ISSUE THREAD

**Issue by HeebyGeeby** [highcharts/highcharts#8011]
#### Expected behaviour
In the following fiddle, series 1 and 2 should behave the same. 
visible: false, showCheckbox: true

Series 3 and 4 should behave the same.
visible: true, showCheckbox: false

#### Actual behaviour
'showCheckbox' will accept both true/false or 1/0 values.
'visible' will only accept true/false. 

#### Live demo with steps to reproduce
http://jsfiddle.net/HeebyGeeby/vsm3rhqh/2/

#### Product version
Both HighCharts and HighStock 6.0.7

#### Affected browser(s)
Chrome and IE

**Comment by pawelfus** [comment]
Hi @HeebyGeeby 

Thank you for reporting the issue. Both `series.showCheckbox` and `series.visible` should be Boolean type, not Number, as in our API:

- https://api.highcharts.com/highcharts/series.line.showCheckbox
> showCheckbox: Boolean
- https://api.highcharts.com/highcharts/series.line.visible
> visible: Boolean

**Comment by HeebyGeeby** [comment]
Thanks @pawelfus 

Yes, though it seems odd that some boolean parameters accept 1 and 0 and some are more strict. 

I create my chart data with Perl/json where typing is very loose, up to now I've used 1 or 0, although the Perl JSON module will allow /0 and /1 to represent booleans.

**Comment by pawelfus** [comment]
Well.. JavaScript is loose typed too, so for example `showCheckbox` can be easily controlled as `if (showCheckbox) { ... } `. We can replace this checks with `if (showCheckbox === true) { ... }` and support only String as docs states. That could cause errors in existing charts when upgrading to next version of Highcharts. We can also replace all of `visible === true`/`visible === false` entries to let `visible = 1/0` be accepted, but I think this should be handled by type-definitions we plan to add.
