### ISSUE TITLE
Highcharts - WordCloud and css scaling

### ISSUE THREAD

**Issue by sruchot** [highcharts/highcharts#8012]
Hello guys,
I'm trying to integrate some word cloud in my solution and at some point I needed to scale to fit the chart and found this issue. Maybe that's intended but I prefer to be sure and report it, to maybe get more information on this one.

#### Expected behaviour
After a css scaling the words placement and/or font sizes should update to fit the new highcharts container taking the scaling into account.

#### Actual behaviour
The word keep the same font sizes and placement as the initial load and will create collision and some of them will go outside of the highcharts box.

#### Live demo with steps to reproduce
I just did a simple fork on the live demo offered by Highcharts with the scaling

[Example](http://jsfiddle.net/Lelith/u5a9b854/)

#### Product version
Latest Highcharts version

#### Affected browser(s)
All my tests were done on Chrome

Thanks in advance for your answers

**Comment by pawelfus** [comment]
Hi @sruchot 

Thank you for reporting this issue. You are right, it looks strange.

@jon-a-nygaard - could you take a look?

**Comment by jon-a-nygaard** [comment]
It seems the scaling is somehow messing with the calculation of the word size and positioning.

A potential workaround would be to [apply the scaling after the chart has rendered](http://jsfiddle.net/u5a9b854/26/).

**Comment by sruchot** [comment]
Hello @jon-a-nygaard , sorry for the delay between your post and my answer.

So in my case, all the charts are within a container and this container will be the one scaled.
So far, all charts behave as wanted and everything will look fine.

The word cloud is actually the first chart that does this unwanted behavior.
Even in your example, if you somehow resize the chart/container everything will be "broken" again.

The "funny" thing though is if you render your chart, then after everyting is done apply a scale on the container, it will work as expected.

In my solution, we're not waiting for the full load to scale, but so far we didn't have any issue with that.

So my guess is that during the rendering of the chart some calculation are done and will not take into consideration any scaling properties.

**Comment by jon-a-nygaard** [comment]
> So my guess is that during the rendering of the chart some calculation are done and will not take into consideration any scaling properties.

Yes, the word cloud is calculating the positions based on the size of each word will have when they are drawn in the svg. The scaling modifies these sizes without the word cloud picking it up.

I updated the previous workaround to take resizing into account, it seems that it can do the trick for now: http://jsfiddle.net/u5a9b854/72/

**Comment by Dams591** [comment]
@jon-a-nygaard 
I'm facing a similar issue and unfortunately due to my application design I cannot remove (or add) the scale on the chart parent container once the chart is rendered.
Is there anyway to render the chart on a scaled container ?

**Comment by sebastianbochan** [comment]
@jon-a-nygaard is it any other workaround?

**Comment by jon-a-nygaard** [comment]
There is some work in progress in the branch `bugfix/8184-wordcloud-missing-large-words` which appears to solve the issue: [Live demo](http://jsfiddle.net/ekvjasmt/)

I am hoping to complete the work soon and submit a PR to include in an upcoming maintenance release.

In the meantime a possible workaround may be to get and use a build of wordcloud.src.js from this branch at https://github.highcharts.com/bugfix/8184-wordcloud-missing-large-words/modules/wordcloud.js

**Comment by Dams591** [comment]
@jon-a-nygaard this is amazing ! thank you so much.
