### ISSUE TITLE
Label for point without corresponding point in mapData is shown in topleft

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#8016]
#### Expected behaviour
Some warning is received but point is ignored.

#### Actual behaviour
Point is located of top left corner of map
![image](https://user-images.githubusercontent.com/9820084/37410298-f9043e6e-27a8-11e8-8dac-a264b92a32ce.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/alvarezg/y1enacvh/

#### Product version
Discovered in 4.2.6, can reproduce with latest from `code.highcharts.com/maps/highmaps.js`

**Comment by pawelfus** [comment]
Hi @alvarezguille 

Thank you for reporting the issue. 

**Workaround:**
Check in `dataLabels.formatter` if point exists on a map: 

```javascript
dataLabels: {
  enabled: true,
    formatter: function () {
      return isNaN(this.point.plotX) ? '' : this.point.code_hasc;
    }
}
```

Demo: http://jsfiddle.net/BlackLabel/y1enacvh/12/

*Internal note:*
Last working version was v1.1.4 - so it's hard to say if this is really a regression. v1.1.4 doesn't even show a map: http://jsfiddle.net/BlackLabel/y1enacvh/8/

**Comment by alvarezguille** [comment]
Related to the internal note, `chart.map` is supported since 5.0.0 so demo should change a bit.
I can reproduce the issue in 1.1.4 by changing to use `series.mapData` as show in https://jsfiddle.net/alvarezg/yorz0r7z/

**Comment by KacperMadej** [comment]
There's no `DE.NOPE` in maps `'code_hasc'`, so it seems like the data is wrong. However, the dataLabel shouldn't be added.

**Comment by oysteinmoseng** [comment]
I am not sure if we consider this a bug - what you are basically doing here is defining a point outside mapdata. This is allowed. You are not giving it a `path`, however, which means it is basically useless.

On the other hand, it is probably a common usecase to have a dataset that doesn't fully match the map, and we probably want to ignore these. Maybe a good course of action here is to ignore map area points with no `path`.

@TorsteinHonsi thoughts?

**Comment by alvarezguille** [comment]
My 5 cents for this: I know it's an unintended/accidental use case, but I would expect the point to be ignored.

**Comment by TorsteinHonsi** [comment]
Agreed, it makes no sense with a data label without a position.
