### ISSUE TITLE
Extra spacing/padding between bars

### ISSUE THREAD

**Issue by chabb** [highcharts/highcharts#8018]
#### Expected behaviour
I have set groupPadding and pointPadding  to zero, so i would expect no padding between the bars
#### Actual behaviour
The padding is changing between bars.

#### Live demo with steps to reproduce
http://jsfiddle.net/hoxo2xqb/4/

#### Product version
Highcharts 6.0.7

**Comment by chabb** [comment]
ohh.. i need a datetime axis for it.. i'm closing it

**Comment by pawelfus** [comment]
Hi @chabb 

Thank you for reporting the issue. This is supported by `ordinal` xAxis in Highchstock, demo: http://jsfiddle.net/BlackLabel/am8bguw3/

For quarters, you can consider using categorized xAxis.
