### ISSUE TITLE
highstock event call e.point.update throw exceptions

### ISSUE THREAD

**Issue by xcqwan** [highcharts/highcharts#8023]
#### Expected behaviour
click column call e.point.update() will throw exception when render by highstock

#### Actual behaviour
http://jsfiddle.net/yzkgoxcb/3/

**Comment by pawelfus** [comment]
Hi @xcqwan 

Thank you for reporting this issue. It looks fine when we update point with any options, even empty object: http://jsfiddle.net/BlackLabel/yzkgoxcb/10/ - do you want to update point without any options?

**Comment by xcqwan** [comment]
this will let navigator render error
http://jsfiddle.net/yzkgoxcb/14/

**Comment by pawelfus** [comment]
Thank you! You are right, something is wrong there. 

Simplified demo: http://jsfiddle.net/BlackLabel/yzkgoxcb/30/

*Internal notes:*
- using Highstock's constructor, it works fine: http://jsfiddle.net/BlackLabel/yzkgoxcb/27/ - probably something is misconfigured
- this used to work in v5: http://jsfiddle.net/BlackLabel/yzkgoxcb/32/

**Comment by pawelfus** [comment]
*Internal note:*
We have two issues here: 
- updating point (as simply y-value) without options cause error in Highstock
- updating point when using `Highcharts.chart` constructor with enabled navigator cause wrong extremes (`xAxis.overscroll` is not defined for this constructor -> max is calculated as NaN)

**Comment by pawelfus** [comment]
The commit above fixes both issues. 

**Workaround:**
Set `xAxis.overscroll = 0` in options, demo: http://jsfiddle.net/BlackLabel/yzkgoxcb/45/

*Internal note:*
If we find more bugs like this, where `overscroll` is not defined with `Highcharts.chart` constructor, we could consider setting this options in `Axis.js` file, instead of `Navigator.js`.

**Comment by xcqwan** [comment]
@pawelfus Thanks, is work for me, but overscroll don't defined on doc

**Comment by pawelfus** [comment]
Hi @xcqwan 

That's correct, `overscroll` is not defined in Highcharts docs, but you use Highstock where we have it's definition (similar to Navigator, Scrollbar etc.): https://api.highcharts.com/highstock/xAxis.overscroll It's set by default to 0 for `stockChart()`, but not defined for `chart()`.
