### ISSUE TITLE
Waterfall connector line is broken in case when there is a null value

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#8024]
#### Expected behaviour
Lines between waterfall columns should be connected in case there is a null value in between and when the connectNulls is set to true.

#### Actual behaviour
In case there is a null value and connectNulls is set to true, the gap between the lines is visible.

#### Live demo
http://jsfiddle.net/jLbn7zxy/

**Comment by sebastianbochan** [comment]
_Internal note_
Incorrect since 5.0.11 version.
5.0.10 works well - http://jsfiddle.net/BlackLabel/35kzdy3r/

**Comment by TorsteinHonsi** [comment]
It appears to come from 1f1a99fb0
