### ISSUE TITLE
Adding map module is heatmap was imported breaks color axis legend position (v4.2.6)

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#8027]
#### Expected behaviour
Legend is centered

![image](https://user-images.githubusercontent.com/9820084/37508462-d52a9eee-28fb-11e8-8783-7c791387e1df.png)

#### Actual behaviour
Legend is located to the right from the center

![image](https://user-images.githubusercontent.com/9820084/37508507-0539501c-28fc-11e8-98cb-9171a5a48826.png)

#### Live demo with steps to reproduce
Can be tested in the following demo http://jsfiddle.net/alvarezg/v8Lxz7xx/

#### Product version

Highcharts-Highmaps 4.2.6

I know heatmap is already included in `map.js`, but at the time to load charts it's not possible to determine if maps is going to be loaded in the future, so this odd behavior happens if charts is loaded before maps.

Is there some workaround for this specific legend position issue?

**Comment by sebastianbochan** [comment]
**Workaround**
- legend - set align as left

**Comment by pawelfus** [comment]
This issue was fixed in v6.0.2: http://jsfiddle.net/BlackLabel/v8Lxz7xx/13/
