### ISSUE TITLE
Chart columns overlap X axis

### ISSUE THREAD

**Issue by proteamer** [highcharts/highcharts#8031]
Hi, I've faced with issue when tried set custom [xAxis.lineWidth](https://api.highcharts.com/highstock/xAxis.lineWidth) in **Highstock** chart. 

#### Actual behaviour
When I set `xAxis.lineWidth` to 10 I see that chart columns overlap `X` axis. See image bellow: 

<img width="398" alt="screen shot 2018-03-16 at 17 50 08" src="https://user-images.githubusercontent.com/1376014/37527242-a05ae6aa-2942-11e8-9f04-3d95678b6be7.png">

#### Expected behaviour
I tried to set `xAxis.lineWidth` to 10  in **Highcharts** chart. It works as expected:

<img width="397" alt="screen shot 2018-03-16 at 17 55 27" src="https://user-images.githubusercontent.com/1376014/37527518-43311660-2943-11e8-9f8c-b1bc360ea639.png">

Also I figured out that in Highstock v5.0.4 the same example work as expected.

#### Live demo with steps to reproduce

Highstock v6.0.7 example: https://jsfiddle.net/unlimit/yjjqL44x/ (works with issue)
Highcharts v6.0.7 example: https://jsfiddle.net/unlimit/ycyy7k5m/ (works as expected)

#### Product version

Highstock v6.0.7

#### Affected browser(s)
Google Chrome v65, Safari v11.0.2, etc.

**Comment by pawelfus** [comment]
Hi @proteamer 

Thank  your for reporting this issue. 

*Internal note:*
Regression from 0a9220256 @KacperMadej

**Comment by ppotaczek** [comment]
The workaround is to set zIndex for xAxis:

`
  xAxis: {
    zIndex: 999
  }
`

Live demo: https://jsfiddle.net/BlackLabel/jjk39ass/
