### ISSUE TITLE
Zooming issue when boost is enabled

### ISSUE THREAD

**Issue by manu-st** [highcharts/highcharts#8033]
#### Expected behaviour
Zooming in and out of a graph should behave the same whether boost is enabled or not.

#### Actual behaviour
When boost is enabled, each time you zoom, you see all the series entirely. When boost is disabled, series are not shown entirely, the stop to the last datapoint included in the zoomed area.

See with boost:
![image](https://user-images.githubusercontent.com/13194660/37548662-abe94cd4-2936-11e8-83d6-f26ef23f1a31.png)

Without Boost:
![image](https://user-images.githubusercontent.com/13194660/37548768-72463842-2937-11e8-9f4e-0dc1352630d8.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/fhdLxa21/

#### Product version
6.0.7.

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks @manu-st !

Minified demo: http://jsfiddle.net/BlackLabel/oL7a9bkg/14/ simple zoom in results:

![screen shot 2018-03-19 at 12 14 26](https://user-images.githubusercontent.com/1453926/37592489-1856effe-2b6f-11e8-8243-f6a20f489c8f.png)
![screen shot 2018-03-19 at 12 13 25](https://user-images.githubusercontent.com/1453926/37592490-18747b6e-2b6f-11e8-9fba-cd76fdf2423a.png)

**Comment by cvasseng** [comment]
Setting `xAxis.min|max` should resolve this. See http://jsfiddle.net/oL7a9bkg/28/

**Comment by ablakok** [comment]
Thank you for fixing this issue.  But it still seems to be a problem in version 6.1.11.  Has it been merged into master?

**Comment by sebastianbochan** [comment]
As I see its not merged yet.

@TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
It's merged now, thanks for your patience!

**Comment by manu-st** [comment]
@TorsteinHonsi Do you know when the next version of highcharts will be available with this fix? Thanks!

**Comment by TorsteinHonsi** [comment]
Sorry for the late reply! We hope to publish it next week.
