### ISSUE TITLE
HighMaps United States not working

### ISSUE THREAD

**Issue by salugubelly** [highcharts/highcharts#8034]
#### Expected behaviour
Given HighMaps type:MapBubble Series.joinBy: 'name'  and 'United States' should plot bubble at 'United States' on the Map.

#### Actual behaviour
Given HighMaps type:MapBubble Series.joinBy: 'name' is **not plotting bubble for** **'United States'** on the Map whereas  'United States of America' is being plotted on the map.

#### Product version
"highcharts": "^6.0.3",
"highcharts-map": "^0.1.2",

**Comment by pawelfus** [comment]
Hi @salugubelly 

Thank you for reporting this issue. It looks like you use some old highcharts-map module: `"highcharts-map": "^0.1.2",`. It's version compatible with.. Highcharts v0.1.7 (???). 

You don't need that plugin, `highcharts` package contains Highmaps, see instructions: https://github.com/highcharts/highcharts#load-highcharts-as-a-commonjs-module

    var Highcharts = require('highcharts/highmaps');

If this doesn't resolve the issue, please recreate this problem in jsFiddle, thanks!

**Comment by sebastianbochan** [comment]
Closed due to inactivity. Please reopen if live demo will be available.
