### ISSUE TITLE
Add annotation via buttons

### ISSUE THREAD

**Issue by ourarash** [highcharts/highcharts#8035]
#### Expected behaviour
Buttons for adding annotation should exist on the chart

#### Actual behaviour
Buttons done't exits

#### Live demo with steps to reproduce

http://jsfiddle.net/7m3Mr/261/

#### Product version

Latest
#### Affected browser(s)

This document mentions that the Black label annotation plug in is now part of Highcharts

https://www.highcharts.com/products/plugin-registry/single/17/Annotations

I wasn't able to find anywhere in the documentation to add those  buttons  (Adding text, square, line, and circle) to the chart.

Are they available now?

![image](https://user-images.githubusercontent.com/20846105/37563401-091c7cb2-2a3d-11e8-80b9-cfc982215a51.png)

**Comment by pawelfus** [comment]
Hi @ourarash 

Highcharts' Annotations module is not the same as BlackLabel's plugin. Buttons are not implemented yet.

**Comment by ourarash** [comment]
Thanks! Is this feature on the roadmap?

**Comment by ourarash** [comment]
Also is it still possible to use Black label on the latest version?

**Comment by pawelfus** [comment]
You can try Black Label's plugin, it should work, but configs are not compatible. This feature is not on our roadmap as far as I know.

**Comment by pawelfus** [comment]
Closing the issue. Since v6 annotations are implemented as a separate module. Since v7 it's possible to add buttons for annotations (https://api.highcharts.com/highcharts/navigation.bindings)
