### ISSUE TITLE
Remove annotations without redrawing the chart

### ISSUE THREAD

**Issue by ourarash** [highcharts/highcharts#8036]
#### Expected behaviour
Remove the annotations on the chart without redrawing the chart

#### Actual behaviour
Remove only the annotations without redrawing the chart

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/annotations/fibonacci-retracements

#### Product version

Latest

#### Affected browser(s)
All

Currently I use the following to draw fibonacci annotations

```
 annotations: [
            fibonacciRetracements(Date.UTC(2016, 10, 14), 105, Date.UTC(2017, 8, 4), 170)
        ],

```

Then set it  null, and redraw the chart again to remove  it, which takes some time. How can I remove the annotations without completely redrawing the chart?

**Comment by pawelfus** [comment]
Hi @ourarash 

It seems that our docs is missing all annotation-related methods:

- `chart.addAnnotations(options, [redraw])`
- `chart.removeAnnotation(id)` (chart redraw doesn't happen)

Demo: http://jsfiddle.net/BlackLabel/bcgbjbrL/2/
