### ISSUE TITLE
dynamic changes to navigator.adaptToUpdatedData do not work

### ISSUE THREAD

**Issue by piotriwojcik** [highcharts/highcharts#8038]
#### Expected behaviour

It should be possible to change the `navigator.adaptToUpdatedData` property dynamically. That is, after creating a chart with
```
...
navigator: {
    adaptToUpdatedData: true
},
...
```
changing `adaptToUpdatedData` to `false` with either of these commands:
```
chart.navigator.update({adaptToUpdatedData: false});
chart.update({navigator: {adaptToUpdatedData: false}});
chart.navigator.adaptToUpdatedData = false;
chart.navigator.navigatorOptions.adaptToUpdatedData = false;
```
should prevent updating the navigator series when the chart data gets updated.

#### Actual behaviour
After creating a chart with `navigator.adaptToUpdatedData=true` and changing the property to `false` the navigator series still gets updated when `chart.series[0].setData(...)` is called.

#### Live demo with steps to reproduce

http://jsfiddle.net/8q4eocjL/183/

To reproduce: change the selected range in the navigator - the navigator series gets updated (it shouldn't).
The demo contains a workaround (commented at the end) which makes the chart behave as expected.

#### Product version

Highstock, 6.0.7

**Comment by pawelfus** [comment]
Hi @piotriwojcik 

Thank you for reporting this bug and for the workaround!

*Internal note:*
We add call `addBaseSeriesEvents` multiple times: 

- in general, after init:
https://github.com/highcharts/highcharts/blob/9002aba21ec85b18e9c096cfc5f950b00d942958/js/parts/Navigator.js#L1549-L1552

- in case we have baseSeries: https://github.com/highcharts/highcharts/blob/9002aba21ec85b18e9c096cfc5f950b00d942958/js/parts/Navigator.js#L1462
we add events once again:
https://github.com/highcharts/highcharts/blob/9002aba21ec85b18e9c096cfc5f950b00d942958/js/parts/Navigator.js#L1786
