### ISSUE TITLE
Highmaps - colorAxis behaves oddly with many dataClasses in styled mode

### ISSUE THREAD

**Issue by aaronrosenthal** [highcharts/highcharts#8043]
#### Expected behaviour
Map series should use CSS classes for as many items that exist in the colorAxis.dataClasses array.

#### Actual behaviour
Highmaps seems to not use CSS classes after index 9, and resets back to zero. This causes not all colors to be used and colors to be repeated in the legend.

#### Live demo with steps to reproduce

http://jsfiddle.net/umdauno7/

#### Product version

Highmaps 6.0.7

#### Affected browser(s)
Chrome 64.0.3282.186

**Comment by pawelfus** [comment]
Hi @aaronrosenthal 

Thank you for choosing Highmaps! You need to set [`chart.colorCount`](https://api.highcharts.com/highmaps/chart.colorCount) to tell Highmaps how many colors you are going to use: http://jsfiddle.net/BlackLabel/umdauno7/5/
