### ISSUE TITLE
Drilldown not working in React-Native

### ISSUE THREAD

**Issue by JMCNAM** [highcharts/highcharts#8048]
#### Expected behaviour

Clicking on column in chart should display line chart.

#### Actual behavior

Type Error: undefined is not an object(evaluation 'n.pie')
( Chart renders correctly without drilldown(Highcharts)  )

![image](https://user-images.githubusercontent.com/32990455/37656646-8ed54d34-2c40-11e8-83ed-fbd46cb85794.png)

#### Live demo with steps to reproduce
// Did not include jsfiddle as issue is with React-Native implementation.

import React, { Component } from 'react';
import { View } from 'react-native';
import ChartView from 'native-highcharts-wrapper';
import Highcharts from 'highcharts';
import drilldown from 'highcharts/modules/drilldown.js';

export default class DrillChart extends Component {
  state = {
    data: []
  };
  constructor(props){
    super(props);
  }
  render() {
    var Highcharts='Highcharts';

    var series = [];
    series.push({name: 'Solar', data: [{name: 'CNOR', y: 10, drilldown:'CNOR-Solar'}]});
    series.push({name: 'Wind', data:  [{name: 'CNOR', y: 10, drilldown:'CNOR-Wind'}]});
    series[0].data.push({name: 'NORD', y: 6, drilldown:'NORD-Solar'});
    series[1].data.push({name: 'NORD', y: 6, drilldown:'NORD-Wind'});
    var drilldownSeries = [{name: 'CNOR-Solar', id: 'CNOR-Solar' ,data: [['1', 4],['2', 2],['3', 1],['4', 2],['5', 1],['6', 4],['7', 2],['8', 1],['9', 2],['10', 1],['11', 4],['12', 2],['13', 1],['14', 2],['15', 1],['16', 4],['17', 2],['18', 1],['19', 2],['20', 5],['21', 3],['22', 9],['23', 6],['24', 5]]}];
    drilldownSeries.push({name: 'CNOR-Wind', id: 'CNOR-Wind' ,data: [['1', 4],['2', 2],['3', 1],['4', 2],['5', 1],['6', 4],['7', 2],['8', 1],['9', 2],['10', 1],['11', 4],['12', 2],['13', 1],['14', 2],['15', 1],['16', 4],['17', 2],['18', 1],['19', 2],['20', 5],['21', 3],['22', 9],['23', 6],['24', 5]]});

    drilldown(Highcharts);
    var conf={
        chart: {
            type: 'column',
            marginRight: 10,
        },
        title: {
            text: "Renewable Production (daily avg.)",
            style: {color: "#333333",
                    fontSize: "20px"}
        },
        xAxis: {
            type: 'category',
            crosshair: true,
            lineColor: "#092938",
        },
        tooltip: {
            shared: true
        },
        yAxis: {
            title: {
                text: 'Average Production'
            },
        },
        exporting: {
            enabled: false
        },
        plotOptions:{
          series:{
            stacking: 'Normal'
          }
        },
        series: series,
        drilldown: {
          series: drilldownSeries
        }
    };
    return(
      <View style={styles.container}>
        <ChartView style={{height:"100%"}} config={conf}/>
      </View>
    );
  }
}
const styles = {
  container: {
    flex:1
  },
}

#### Product version

"name": "highcharts",
"version": "6.0.7",

**Comment by pawelfus** [comment]
Hi @JMCNAM 

Thank you for reporting the issue. Problem may be related to including the drilldown module on every render: `drilldown(Highcharts);`.

Instead import this module only once:

```javascript
import React, { Component } from 'react';
import { View } from 'react-native';
import ChartView from 'native-highcharts-wrapper';
import Highcharts from 'highcharts';
import drilldown from 'highcharts/modules/drilldown.js';

drilldown(Highcharts);
```

Could you change this and let us know the results?

**Comment by JMCNAM** [comment]
Hi,

Thanks for the rapid response.

I assume that you meant put drilldown(Highcharts);. Outside the class, just below the imports.
I have tried this and am getting the same error.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by pawelfus** [comment]
Thanks @JMCNAM 

Could you use minified version of the files? 

```javascript
import Highcharts from 'highcharts/highcharts.src.js';
import drilldown from 'highcharts/modules/drilldown.src.js';
```

And let me know about the results? 

Additionally, did you contact authors of the native-highcharts-wrapper plugin? It looks like they don't include drilldown module, but include Highcharts again: https://github.com/jacobsteves/native-highcharts-wrapper/blob/master/index.js#L31-L34 which may cause errors.

**Comment by JMCNAM** [comment]
Same error as before.

I suspected that it was something to do with the fact that the ChartView component from native-highcharts-wrapper was just taking the config and drilldown wasn’t being called in my component.

Looking at the wrapper index.js, I expected the fix to be something like:

<head>
                        <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
                        ${this.props.stock ? '<script src="https://code.highcharts.com/stock/highstock.js"></script>'
                                      : '<script src="https://code.highcharts.com/highcharts.js"></script>'}

                        <script src="https://code.highcharts.com/modules/drilldown.js"></script>

                        <script src="https://code.highcharts.com/modules/exporting.js"></script>
                        <script>
                        $(function () {
                            Highcharts.chart('container', `,
            end:`           );
                        });
                        </script>
                    </head>

, including the drilldown import after the jQ, so that it would always be available.

Not sure where to call the drilldown(Highcharts) for my component. Drilldown is only imported when WebView renders.
Is it the case that the html will have to be altered in include the config parameters for the drilldown setup and pass them through state? Sent message to author.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by pawelfus** [comment]
Hi @JMCNAM 

Using this wrapper, I think you shouldn't use `import Highcharts` at all. It looks like this wrapper always imports only Highcharts/Highstock with exporting module.. Note: this wrapper includes our libraries from cdn, so app won't work offline. Let me know if get any news from the author.

**Comment by oysteinmoseng** [comment]
Closing this as does not seem to be a bug.
