### ISSUE TITLE
Word Cloud chart sometimes display none when has long-word

### ISSUE THREAD

**Issue by xcqwan** [highcharts/highcharts#8052]
#### Expected behaviour
try run many times should get it

#### Live demo with steps to reproduce

http://jsfiddle.net/uo6216q9/3/

**Comment by pawelfus** [comment]
Hi @xcqwan 

Thank you for reporting this issue!

*Internal note:*
We can also resize the chart and the issue will show up too.

**Comment by xcqwan** [comment]
okey

**Comment by jon-a-nygaard** [comment]
Closed by #8497
