### ISSUE TITLE
Highchart series label issue

### ISSUE THREAD

**Issue by VBIManonmaniM** [highcharts/highcharts#8054]
#### Expected behaviour
When I am trying to use the series-label plugin to display the series name it's working fine for inverted flag set to false.when the inverted flag is set series-name is displayed as mirror text;Kindly look into it.

#### Actual behaviour
Series-name should be displayed normal readable text even though we inverted the chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/8Lzu6tuj/8/

#### Product version
Highcharts

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @VBIManonmaniM 

Thank you for reporting the issue!
