### ISSUE TITLE
Tick of Polar Chart undefined in Styled Mode

### ISSUE THREAD

**Issue by dominikkaegi** [highcharts/highcharts#8058]
#### Expected behaviour
I'm using a polar chart in styled mode. I use the default styles highcharts.scss as a base (to later overwrite them). I expect that if I use the styled mode and use the default highcharts.scss I should get the following chart:

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/polar/

#### Actual behaviour
When I use the styled mode import and use the highcharts.scss default I get following error:

Uncaught TypeError: Cannot read property 'fontSize' of undefined
    at a.Tick.<anonymous> (highcharts-more.js:22)
    at a.Tick.a.(/4wh33sa7/4/anonymous function) [as getLabelPosition] (https://code.highcharts.com/js/highcharts.js:19:437)
    at a.Tick.renderLabel (highcharts.js:109)
    at a.Tick.render (highcharts.js:110)
    at I.renderTick (highcharts.js:153)
    at highcharts.js:154
    at Array.forEach (<anonymous>)
    at a.each (highcharts.js:27)
    at I.render (highcharts.js:154)
    at highcharts.js:248

#### Live demo with steps to reproduce
Change the import from ```https://code.highcharts.com/js/highcharts.js``` to ```https://code.highcharts.com/highcharts.js``` to get the working chart as in the expected behavior above. The JS fiddle is already set to import highcharts in styled mode in which the bug occurs.
http://jsfiddle.net/4wh33sa7/4/

#### Product version
Highcharts 6

#### Affected browser(s)
Firefox, Safari, Chrome

**Comment by pawelfus** [comment]
Hi @dominikkaegi 

Thank you for reporting this issue. This should be fixed on our master branch and be part of the next release: http://jsfiddle.net/BlackLabel/4wh33sa7/12/ - could you confirm?

**Comment by dominikkaegi** [comment]
@pawelfus that works. Thank you for the reply.

**Comment by KieranDotCo** [comment]
Thanks @pawelfus any ideas when a release of 6.0.8 will happen?

**Comment by pawelfus** [comment]
Hi @KieranDotCo next release (v6.1.0) should be ready in April.
