### ISSUE TITLE
Highcharts Marker Flickering When Redraw is deferred

### ISSUE THREAD

**Issue by allanmacmillan4** [highcharts/highcharts#8060]
#### Expected behaviour
When redraw is called (regardless of whether that is immediately or deferred until later), the series will be redrawn without any flickering markers

#### Actual behaviour
When redraw is called, the series is redrawn, but the markers flicker

#### Live demo with steps to reproduce
Flicker present - http://jsfiddle.net/vmw9xgbe/
No Flicker - http://jsfiddle.net/drgxbjnn/
#### Product version

Highcharts (also present in Highstoks) 6.0.7 (I think)
#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @allanmacmillan4 

The flickering is always there, just when you don't defer redraw, you won't see it. When setting new dataset (with different amount of points), all points are destroyed and new ones are created. How about using `addPoint()` instead of `setData()` ? Like this: http://jsfiddle.net/BlackLabel/vmw9xgbe/4/

**Comment by allanmacmillan4** [comment]
Why should the time you choose to redraw the chart influence the behavior of that chart when the interactions are the same. 

The jsfiddles i have attached are simple to show the problem, in reality, setData is sometimes the only option and should manage the redrawing without flickering. 

This must be a bug

**Comment by pawelfus** [comment]
@allanmacmillan4 As I said:
> The flickering is always there, just when you don't defer redraw, you won't see it. 

Anyway, it should be possible to fix this issue in the core in the upcoming 6.1 version: http://jsfiddle.net/BlackLabel/u3e66azL/ (note: `updatePoints` is set to true, and this setting is necessary).

Let me test the solution above.

**Comment by pawelfus** [comment]
Fixed version on PR branch: http://jsfiddle.net/BlackLabel/vmw9xgbe/79/
