### ISSUE TITLE
Color zones not supported with local export to PDF

### ISSUE THREAD

**Issue by ransoing** [highcharts/highcharts#8062]
#### Expected behaviour
Exporting locally should download the plot as it appears on the screen.

#### Actual behaviour
When exporting locally as a PDF, the downloaded file does not color the plot according to the defined color zones.
Server export works fine.

#### Live demo with steps to reproduce
http://jsfiddle.net/sgzf10hx/2/
Export to png, jpeg, svg, and pdf. Notice how the red part of the line does not show up for the PDF.

#### Product version
Highstock, latest

#### Affected browser(s)
Chrome, Firefox

**Comment by sebastianbochan** [comment]
Hi @ransoing 
Thank you for the reporting.

@oysteinmoseng

**Comment by TorsteinHonsi** [comment]
This goes back to the lack of support for `clipPath` elements in svg2pdf.js. See https://github.com/yWorks/svg2pdf.js/issues/45.

**Comment by pawelfus** [comment]
Fixed in c88342ca1717bc5a4d4d6ba40dab3fb126efbc6c
