### ISSUE TITLE
Sankey Diagram: Highlighting all flow for a particular node instead of single flow

### ISSUE THREAD

**Issue by Ganesh-babu-sakthivel** [highcharts/highcharts#8067]
Hello,

I would like to highlight the entire relationship a node has, but now we have the ability to highlight only the flow / line by hovering on it.

Is there a way we can click on a node and highlight it along with flow on both the sides of node and all other nodes which are not linked, get faded away. This way we can get a solid picture of how a single node has impact on all other applicable nodes.

Thanks!

**Comment by pawelfus** [comment]
Hi @Ganesh-babu-sakthivel 

Could you contact with our support? See details: https://www.highcharts.com/support We use github issues as bug reports.

PS: Simple example: use [`point.events.click`](https://api.highcharts.com/highcharts/series.sankey.point.events.click) and highlight selected links: http://jsfiddle.net/BlackLabel/y49oo3jL/
