### ISSUE TITLE
Custom numbers formatting for tooltipx, x and y axis per a chart

### ISSUE THREAD

**Issue by simon2k** [highcharts/highcharts#8070]
#### Expected behaviour
Ability to format tooltip numeric values per a chart.

Here I have seen that there is a way to override the way values are formatted in a global scope:
https://github.com/highcharts/highcharts/blob/334c804fb666cd04d64f5097a308e1b35bdad23e/samples/highcharts/members/highcharts-numberformat/demo.js#L25

I would expect to be able to define such a formatting in e.g. the `tooltip` option. Currently we are limited in the `pointFormat` option to format numbers, for instance: `{point.y:,.0f}`. I would expect that per a chart definition we would be able to provide a function that can format numbers that are displayed in tooltips, x, y axis.

#### Actual behaviour
Limited way to format tooltips numeric values per a chart.

**Comment by pawelfus** [comment]
Hi @simon2k 

Do you mean formatters? For example:
- https://api.highcharts.com/highcharts/tooltip.formatter
- https://api.highcharts.com/highcharts/xAxis.labels.formatter
- https://api.highcharts.com/highcharts/yAxis.labels.formatter
- https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.formatter 

In formatters you can return formatted string in any format you want to, per chart/series/axis.

**Comment by simon2k** [comment]
@pawelfus Thank you, I have seen this option. I thought that maybe there could be added support to specify the formatter function for values, without defining the whole template. Is there any plan for this in the near future?

**Comment by pawelfus** [comment]
Could you show an example what exactly you want to achieve? Live demo in jsFiddle would be great.

**Comment by simon2k** [comment]
Definitely, here's a sample: http://jsfiddle.net/z1n31ns3/3/

**Comment by pawelfus** [comment]
Thank you for the details! 

Just a side note: you can achieve this result by formatting values before rendering chart, for example: http://jsfiddle.net/BlackLabel/z1n31ns3/7/

**Comment by simon2k** [comment]
@pawelfus thank you a lot! I haven't seen that option anywhere :sweat_smile:
