### ISSUE TITLE
Add ability to programmatically modify zoom area

### ISSUE THREAD

**Issue by KieranCairney** [highcharts/highcharts#8071]
#### Expected behaviour

Add ability to programmatically modify zoom area such that in the event of a mouse drag across and off of a chart we can set the highlighted zoom range programatically.

#### Actual behaviour

The Highcharts API does not offer any programatic control over highlight area when dragging the mouse.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/arearange

![fast-highlight](https://user-images.githubusercontent.com/10413200/37788020-9ca250b4-2dbd-11e8-98f0-5321cec73574.gif)

#### Product version
Highcharts 6.0.7

**Comment by pawelfus** [comment]
Hi @KieranCairney 

Thank you for your suggestion. You can use our internal method `chart.pointer.onDocumentMouseUp(event)`.
Demo: http://jsfiddle.net/BlackLabel/qbfLLc94/2/

**Comment by KieranCairney** [comment]
Thanks for the response @pawelfus. Perhaps this was my own fault in the explanation, however my actual feature request was intended to be that we could change the highlight area to the edge of the chart that we exit on (left or right when zoom is on the x axis) by not triggering a mouse up and not triggering a zoom.

**Comment by pawelfus** [comment]
Hi @KieranCairney 

Thank you for the details! It's a bit tricky - what if user exit chart by top/bottom edges? I assume we should decide this according to the start of the drag event: http://jsfiddle.net/BlackLabel/qbfLLc94/16/

Snippet:
```javascript
    $("#container").on('mouseleave', function(e) {
      var selectionBox,
        selectionMarker = chart.pointer.selectionMarker; // blueish rectangle reference
      if (selectionMarker) {
        selectionBox = selectionMarker.getBBox(); // get current x/y/width/height
        if (e.offsetX < chart.pointer.mouseDownX) { // left or right
          selectionMarker.attr({
            x: chart.plotLeft,
            width: selectionBox.width + selectionBox.x - chart.plotLeft
          });
        } else {
          selectionMarker.attr({
            width: chart.plotWidth - selectionBox.x + chart.plotWidth
          });
        }
      }
    });
```

**Comment by KieranCairney** [comment]
Thanks for the detailed response @pawelfus. Basically for my case I don't want selection to change on 'bottom'/'top' exits so I just handle the case of left/right exit, which works. My only nitpick is that this mouseleave event responds to a cursor exit on the whole chart, not just the charting area. As a result there could be an edge case where you quickly drag your mouse off of the left edge onto the legend and a mouseleave would not be triggered, therefore not updating the charting area in case of a fast movement of the mouse. Is there a way to add a mouseleave listener to strictly the chart area?

**Comment by pawelfus** [comment]
@KieranCairney 
>  Is there a way to add a mouseleave listener to strictly the chart area?

There's no element we can bind event to (well there is, but has lowest zIndex..). However, we can simply check where `mousemove` event happened: 

```javascript
    $("#container")
      .on('mouseleave', function(e) {
        selectionToExtremes(e, chart)
      })
      .on('mousemove', function(e) {
        var chartEvent = chart.pointer.normalize(e);
        // If we are outside plotting area, check if user is zooming in, then apply changes:
        if (!chart
            .isInsidePlot(
              chartEvent.chartX - chart.plotLeft,
              chartEvent.chartY - chart.plotTop
            )
        ) {
          selectionToExtremes(e, chart)
        }
      });
```

http://jsfiddle.net/BlackLabel/qbfLLc94/25/
