### ISSUE TITLE
Updating export button menu items dynamically breaks export button

### ISSUE THREAD

**Issue by mitsuthar** [highcharts/highcharts#8072]
I am updating the menu items dynamically.
`const newObj = {
    exporting: {
        buttons: {
            contextButton: {
                menuItems: newchartSettings.exporting.buttons.contextButton.menuItems
            }
        }
    }
};
this.chart.update(newObj);`

But this results in export button breaking with this error
`Uncaught TypeError: button.setState is not a function
    at hide (exporting.src.js?bundleVirtualPath=~%2fauthenticatedbundles%2fwidgets:569)
    at HTMLDocument.<anonymous> (exporting.src.js?bundleVirtualPath=~%2fauthenticatedbundles%2fwidgets:587)`

#### Expected behaviour
New menu items are visible on the chart

#### Actual behaviour
Export button breaks

#### Product version
Highstock JS v5.0.7

#### Affected browser(s)
Chrome
Not sure about others

**Comment by pawelfus** [comment]
Hi @mitsuthar 

Thank you for reporting this issue. Please update your Highcharts to 5.0.10. Demo: http://jsfiddle.net/BlackLabel/1qs46aw3/7/
