### ISSUE TITLE
Adding new data points with series.step: center causes distortions in an animated graph

### ISSUE THREAD

**Issue by ernstvanrijn** [highcharts/highcharts#8073]
#### Expected behaviour
When using the step option "center" for a series, the graph should be rendered the same as when "left" or "right" is used when new data points are added to the graph.

#### Actual behaviour
When series.step: center is used, the graph distorts whenever new data points are added.

#### Live demo with steps to reproduce
http://jsfiddle.net/4pf9x56d/4/

#### Product version
Current

#### Affected browser(s)
Chrome, Firefox, Edge

**Comment by pawelfus** [comment]
Hi @ernstvanrijn 

Thank you for reporting this issue. 

*Internal note:*
The same happens in Highcharts: http://jsfiddle.net/BlackLabel/4pf9x56d/10/ - in general it's path animation issue.
