### ISSUE TITLE
xAxis drilldown labels are not properly styled with custom build

### ISSUE THREAD

**Issue by tomfortmuller** [highcharts/highcharts#8076]
A custom Highcharts build using node yields unexpected styles for drill down labels on the xAxis of a column chart.

#### Expected behavior
xAxis labels should be styled to look like links.

#### Actual behaviour
Most labels are unstyled, although drill down functionality works. Drill back up or hide/show the series and the labels will be styled correctly.

#### Live demo with steps to reproduce
https://jsfiddle.net/tomfortmuller/ccdqt6q6/6/

The custom build file can be found here: 
https://github.com/tomfortmuller/highcharts-custom-build/blob/master/custom.src.2018.3.23.MASTER.js

#### Product version
6.0.7

#### Affected browser(s)
Chrome, Firefox

**Comment by pawelfus** [comment]
Hi @tomfortmuller 

Thank you for reporting this issue. It is already fixed on our master branch by 44f748ced24ce745986cbd2c52c97b96f20cb6db commit.
