### ISSUE TITLE
Array.prototype.forEach called on null or undefined

### ISSUE THREAD

**Issue by bgity** [highcharts/highcharts#8077]
I am working on Highcharts highmaps rich information on click chart.First time load the information by json array and its working fine.But when I am filter data using filter and load chart again its give me same error at below lines.What is solution for this?

Highcharts.wrap(Highcharts.Point.prototype, 'select', function (proceed) {
proceed.apply(this, Array.prototype.slice.call(arguments, 1));
var points = mapChart.getSelectedPoints();

**Comment by pawelfus** [comment]
Hi @bgity 

Thank you for reporting this issue, but without live demo we won't be able to tell what happens. Could you create one? Thanks!

**Comment by bgity** [comment]
yes i will create

**Comment by pawelfus** [comment]
@bgity 

Please contact our support: https://www.highcharts.com/support - we use github issues as bugs in our library. Thanks!

**Comment by bgity** [comment]
Issue solve I declare countries array  outside function

**Comment by midhun-p** [comment]
I am also have the same issue.. How did you fixed this issue ?
