### ISSUE TITLE
How to programmatically disable tooltips?

### ISSUE THREAD

**Issue by ourarash** [highcharts/highcharts#8078]
#### Expected behaviour
A  function to disable/enable tooltips

#### Actual behaviour
tooltip.enabled  can only be set upon chart creation

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/enabled/

#### Product version

Latest
#### Affected browser(s)
All

Is there a function that I can call to programmatically enable/disable the tooltips on the chart? Currently, I have to update `tooltip.enabled`, destroy and redraw  the chart.

**Comment by sebastianbochan** [comment]
Hi @yash27
Thank you for contacting us. This is our bugtracker, so for the further questions please use forum / stackoverflow or email. You can find more informations about support here

ps. You can enable / disable tooltip by the chart.update() function.
Demo: 
- http://jsfiddle.net/BlackLabel/26kbo0gj/1/

**Comment by ourarash** [comment]
Thanks for the answer! Sorry for posting  in the wrong place.
