### ISSUE TITLE
in which basis,stock chart calculating sma? in opening value or closing one?

### ISSUE THREAD

**Issue by yash27** [highcharts/highcharts#8079]
I am using `SMA` series in my stock chart based on stock data i.e. ohlc values, so I want to know whether the chart is calculating `SMA` in opening value or closing value?

**Comment by sebastianbochan** [comment]
Hi @yash27 
Thank you for contacting us. This is our bugtracker, so for the further questions, please use forum / stackoverflow or email. You can find more informations about support [here](http://www.highcharts.com/support)

SMA is based on OPEN value calculation, but you can change it by the [index](https://api.highcharts.com/highstock/series.sma.params.index) parameter.
