### ISSUE TITLE
Pie3d with large amount data is not stable, on disabling legends is creating empty gap in chart sometime

### ISSUE THREAD

**Issue by praveenn-vbi** [highcharts/highcharts#8080]
#### Actual behaviour
![image](https://user-images.githubusercontent.com/20218070/37892296-0663410e-30f5-11e8-8e8f-3e6fc1c76e67.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/mcvv2kzm/

#### Product version
6.0.7

#### Affected browser(s)
All Browser

**Comment by KacperMadej** [comment]
Hi @praveenn-vbi 

Thank you for reporting about the problem.
Looks like a duplicate of https://github.com/highcharts/highcharts/issues/7097
