### ISSUE TITLE
Multiple title for legends

### ISSUE THREAD

**Issue by nashikin** [highcharts/highcharts#8085]
Hi.. May I know, it is possible to have multiple title in legend

**Comment by sebastianbochan** [comment]
Hi @nashikin 
Thank you for contacting us. The github is our bugtracker so please use forum / stackoverflow or email for the further questions. You can find more informations about support [here](http://www.highcharts.com/support).

ps You can use [renderer.text](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#text) to add custom text.
