### ISSUE TITLE
Regions are outdated in France map.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#8086]
**Fr-all.js** map has 28 regions, but since 2016 it should be reduced to 18 regions.

External source:
[https://en.wikipedia.org/wiki/Regions_of_France](https://en.wikipedia.org/wiki/Regions_of_France)

**Comment by PaulDalek** [comment]
Here are the maps of France with corrected regions:
- https://jsfiddle.net/wegdb7uk/ - mainland
- https://jsfiddle.net/oqp5acke/ - with overseas territories

Internal Note:
Some of the labels in mainland map where aligned incorrectly after generating with QGIS so it required to do some corrections (in some regions hc-middle-x, hc-middle-y properties are modified manually).

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#21
