### ISSUE TITLE
Bubble series with 'sizeByAbsoluteValue' and similar 'z' values shows empty chart

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#8092]
#### Expected behaviour
Chart should render independently from 'z' value.
https://jsfiddle.net/BlackLabel/ktp0f7nL/

#### Actual behaviour
If 'z' data values are different in two points and the difference of these values is not greater than approximately 0.1, the chart does not render.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/f6mb4ubt/

#### Product version
Highcharts v6.0.7

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
You should declare the zThreshold parameter. 

Demo:
- https://jsfiddle.net/BlackLabel/L9c0v6gu/

**Comment by criozen** [comment]
Looks like that the problem is in this piece of code in **getRadii** method:

    // When sizing by threshold, the absolute value of z determines the size
    // of the bubble.
    if (options.sizeByAbsoluteValue && value !== null) {
        value = Math.abs(value - zThreshold);
        zMax = Math.max(zMax - zThreshold, Math.abs(zMin - zThreshold));
        zMin = 0;       
    }

After update zMax and zMin values, should we not also update **zRange**?

**Comment by criozen** [comment]
> Workaround
Set the zThreshold parameter.
This won't work if difference in z values is 0.01
