### ISSUE TITLE
Reset zoom button does not show up when performing zooming after drilldown

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#8095]
#### Expected behaviour
Zooming on any drilldown level should result in displaying reset zoom button.
#### Actual behaviour
The reset zoom button does not display when performing zooming on any drilldown level.

#### Live demo with steps to reproduce
http://jsfiddle.net/502k9msp/

1. Perform a drilldown.
2. Zoom anywhere.

**Comment by pawelfus** [comment]
*Internal note:*
Related to #6103

**Comment by balkarov** [comment]
@pawelfus hello I have the same problem
https://jsfiddle.net/qwv6s9ur/

When you fixed it?

**Comment by pawelfus** [comment]
Hi @balkarov 

No ETA for this issue, but let me provide you a possible workaround: https://jsfiddle.net/BlackLabel/zscjd6op/ - could you test it and let us know the results? We should be able later to convert this workaround to a real solution.

Snippet:
```js
var H = Highcharts;

H.Chart.prototype.protoEvents.beforeShowResetZoom[0].order = 1;

H.addEvent(
  H.Chart,
  'beforeShowResetZoom',
  function(event) {
    if (this.drillUpButton) {
      this.temporaryDrillUpButton = this.drillUpButton;
      delete this.drillUpButton;
    }
  }, {
    order: 0
  }
);

H.addEvent(
  H.Chart,
  'afterShowResetZoom',
  function(event) {
    if (this.temporaryDrillUpButton && this.resetZoomButton) {
      var buttonOptions = this.options.drilldown.drillUpButton,
        bbox = this.resetZoomButton.getBBox();

      this.temporaryDrillUpButton.align({
          x: buttonOptions.position.x - bbox.width - 20,
          y: buttonOptions.position.y,
          align: 'right'
        },
        false,
        buttonOptions.relativeTo || 'plotBox'
      );


      this.drillUpButton = this.temporaryDrillUpButton;
      delete this.temporaryDrillUpButton;
    }
  }
);

H.addEvent(
  H.Chart,
  'selection',
  function(event) {
    if (event.resetSelection === true && this.drillUpButton) {
      var buttonOptions = this.options.drilldown.drillUpButton;

      this.drillUpButton.align({
          x: buttonOptions.position.x,
          y: buttonOptions.position.y,
          align: 'right'
        },
        false,
        buttonOptions.relativeTo || 'plotBox'
      );
    }
  }
);

H.addEvent(
  H.Chart,
  'drillupall',
  function() {
    if (this.resetZoomButton) {
      this.resetZoomButton = this.resetZoomButton.destroy();
    }
  }
);
```

**Comment by balkarov** [comment]
@pawelfus thank you!
It is work for me. But need add it to library, please.

**Comment by balkarov** [comment]
@pawelfus hello. I have bug after this hack
https://jsfiddle.net/5qw0x7u9/

![3](https://user-images.githubusercontent.com/6030335/57758488-78afc000-7700-11e9-964f-5b758f318722.gif)

**Comment by pawelfus** [comment]
Hi @balkarov - it's broken without my workaround: https://jsfiddle.net/BlackLabel/36vaxLpc/1/ - see #8324

**Comment by vitaliy-patsay** [comment]
Hi, are there any plans to fix this behavior on library level instead of using workaround?

**Comment by sebastianbochan** [comment]
Hi @vitaliy-patsay,
At this moment we do not have ETA for this ticket.

**Comment by balkarov** [comment]
Highcharts 9.0.1
![image](https://user-images.githubusercontent.com/6030335/112472511-46505e80-8d7e-11eb-9669-0f34e95b91d5.png)
