### ISSUE TITLE
Uncaught Error On Drilldown From Column Category Label

### ISSUE THREAD

**Issue by doubletriplezero** [highcharts/highcharts#8096]
#### Expected behaviour
Click Category Label below Column style chart to drill down into that category.

Chart drills down into that category without throwing error.

#### Actual behaviour

Drilldown does occur, but console shows two uncaught errors:

`Uncaught TypeError: Cannot read property 'applyDrilldown' of undefined
    at G.e.Axis.drilldownCategory (drilldown.js:formatted:333)
    at SVGTextElement.<anonymous> (drilldown.js:formatted:358)`

`Uncaught TypeError: Cannot read property 'hoverPoint' of null
    at a.Pointer.onContainerClick (highcharts.js:formatted:4563)
    at HTMLDivElement.c.onclick (highcharts.js:formatted:4586)`

#### Product version
Highcharts v 6.0.7

#### Affected browser(s)

Chrome 65, IE 11

**Comment by pawelfus** [comment]
Hi @doubletriplezero 

Thanks for reporting the issue. Please recreate bug in jsFiddle, we will take a look. Thanks!

**Comment by doubletriplezero** [comment]
I was unable to reproduce simply in jsfiddle. After further investigation I noticed that we are overriding the default drilldown event in our config. Essentially we are re-parsing the data, setting our drilldown values and then redrawing the chart. Simply wrapping a setTimeout around this redraw in our drilldown event prevents the uncaught error in the console.

**Comment by pawelfus** [comment]
Thanks for the info @doubletriplezero 

Should we close the ticket then?

**Comment by doubletriplezero** [comment]
Yes, thanks. One more thing I'll add to the thread is that the reason we were seeing more issues when clicking to drilldown on the category label (rather than the chart itself) is that the drilldown event gets fired multiple times (once for each series in the category). When handling the drilldown and chart redraw in our own function, it was helpful to use setTimeout on the redraw and to ignore the multiple events since we were handling setting up the data ourselves. Thanks.

**Comment by WangYiCong** [comment]
hi，How can I solve this problem?

**Comment by WangYiCong** [comment]
When I click on the legend, it will report this error.

highcharts@6.2.0.min.js:215 Uncaught TypeError: Cannot read property 'hoverPoint' of null
    at a.Pointer.onContainerClick (highcharts@6.2.0.min.js:215)
    at HTMLDivElement.b.onclic

**Comment by KacperMadej** [comment]
Please contact technical support with a live demo for the problem - https://www.highcharts.com/blog/support/

**Comment by ungarson** [comment]
Same problem ! 😩

**Comment by KacperMadej** [comment]
Then probably the same solution will help you:
Please contact technical support with a live demo for the problem - https://www.highcharts.com/blog/support/

**Comment by ungarson** [comment]
I've figured it out. The problem was that the chart was inside a container which has `v-if`, and the chart didn't like to be rerendered I guess 😄 I removed the `v-if` and it works fine now.
