### ISSUE TITLE
New York County is missing in the Highmaps county shape file

### ISSUE THREAD

**Issue by JCHS-Riordan** [highcharts/highcharts#8097]
#### Expected behaviour
New York County, containing Manhattan, should appear on the county shape file: Highcharts.maps["countries/us/us-all-all"].

#### Actual behaviour
New York County does not appear, though the rest of NYC's counties do appear.

#### Live demo with steps to reproduce
Highcharts demo: "Detailed map, US counties" https://www.highcharts.com/maps/demo/us-counties

Zoom in to New York, only see Richmond, Kings, Queens, and Bronx counties. Manhattan (New York) is missing.

#### Product version
Highmaps v6.0.7

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @JCHS-Riordan 

Thank you for reporting. The New York County is more visible in high resolution version of the map: http://jsfiddle.net/BlackLabel/thonmcw2/2/

The New York County is there - the shape is not correct.
![nyc_is_there](https://user-images.githubusercontent.com/8960408/38084987-3439e446-334f-11e8-8787-14ca7972978e.jpg)


_Internal note:_ Looks like the county's shape is wrong.

**Comment by JCHS-Riordan** [comment]
Thank you @KacperMadej! I have switched to using the highres version in my project. Will keep an eye out for any changes in the low res version.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#22
