### ISSUE TITLE
Bubble chart render bug on iMac 5K

### ISSUE THREAD

**Issue by RyanChill94** [highcharts/highcharts#8098]
Hi,there!
I found a rendering bug at high resolution,The bubbles flicker as they are rendered,The final effect is the same as the picture below,even the official Demo has the same problem,What's the solution, please.

ps:I am not a native English speaker. I hope you understand what I mean :) 

Actual behaviour
some bubble marker did not render as expected 

![image](https://user-images.githubusercontent.com/12482300/38066812-4464d60e-333c-11e8-8eed-b1ce60b0094c.png)

Live demo with steps to reproduce
official demo
https://www.highcharts.com/demo/bubble-3d
![image](https://user-images.githubusercontent.com/12482300/38067133-b6d638d0-333d-11e8-940b-4a0a23eec483.png)

Product version
Highcharts v6.0.5

Affected browser(s)
chrome 65.0.3325.181

**Comment by pawelfus** [comment]
Hi @RyanChill94 

Thank you for reporting this issue. It looks like a bug in Chrome, simple SVG is broken on some machines (osx + Chrome only, not all of them): http://jsfiddle.net/BlackLabel/o1t62xzL/

Screenshot: 
![screen shot 2018-03-29 at 16 37 12](https://user-images.githubusercontent.com/1453926/38094986-932e4dbe-336f-11e8-83ca-e8a4e8ba7c75.png)

Working screenshot:
![screen shot 2018-03-29 at 16 41 15](https://user-images.githubusercontent.com/1453926/38095171-0cb3e75c-3370-11e8-936e-bc80ad23939c.png)
