### ISSUE TITLE
Arearange chart: marker symbol shows wrong color when negativeColor is set

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts#8100]
#### Expected behaviour

Marker symbol located in the positive area should show up in the series's color, and not in the negative color

#### Actual behaviour

Marker symbol located in the positive area show up with the negative color if arearange has a negative minimum and a positive maximum

 #### Live demo with steps to reproduce

Am using the iOS wrapper - therefore I attach a screenshot:

![img_3558](https://user-images.githubusercontent.com/12996815/38107888-72c19850-3393-11e8-9628-1012b93b6b90.jpg)

#### Product version
Highcharts 6.0.7, Latest iOS wrapper

#### Affected browser(s)

iOS wrapper - not tested as JS on a browser

**Comment by pawelfus** [comment]
Hi @skuske 

Thank you for reporting the issue.

**Demo:**
http://jsfiddle.net/BlackLabel/hs1g71m3/1/

**Comment by skuske** [comment]
@pawelfus , @TorsteinHonsi 

Thanks for fixing that so quickly, but: we need that fixed in the iOS wrapper as we use arearange charts and negative colors quite a lot. How can I get that incorporated into the iOS wrapper?

Thanks! :o)

**Comment by pawelfus** [comment]
@skuske 

First we need to release Highcharts v6.1.0 (~next week), then, probably in ~two weeks, we should release iOS version.
