### ISSUE TITLE
xrange series does not update when selected

### ISSUE THREAD

**Issue by spacedarcy** [highcharts/highcharts#8104]
#### Expected behaviour
When clicking on an xrange series, the series should update visually.

#### Actual behaviour
When clicking on an xrange series, the series will only visibly update on zoom or reflow.

#### Live demo with steps to reproduce
http://jsfiddle.net/aqupng7k/

1. select a series in the chart, observe that the visual state does not change
2. zoom in on the series you clicked, you should see the state of the series has changed

#### Product version
Highcharts v6.0.7

#### Affected browser(s)
Google Chrome 65.0.3325.181, OSX High Sierra

**Comment by pawelfus** [comment]
Hi @spacedarcy 

Thanks for reporting this bug! 

**Workaround:**
Redraw point after selection: http://jsfiddle.net/BlackLabel/aqupng7k/4/

```javascript
    point: {
      events: {
        select: function() {
          this.selected = true;
          this.series.drawPoint(this, 'attr');
        },
        unselect: function() {
          this.selected = false;
          this.series.drawPoint(this, 'attr');
        }
      }
    },
```

**Comment by spacedarcy** [comment]
This workaround unblocks me. Thanks for the quick turnaround!
