### ISSUE TITLE
Problems with overriding lin2log and log2lin

### ISSUE THREAD

**Issue by PhilBraica** [highcharts/highcharts#8106]
This is one of those bugs that if you look at the code, you'll just see it after a bit of thought.

Throughout the highcharts.src.js code you see the lin2log and log2lin functions called 1 of 3 different ways, only one of which works in all cases as expected.

1. Correct:
value = axis.lin2log(otherValue);

Inside lin2log, the "this" value is set to the axis, and the local lin2log (or log2lin) function can access other scaling data about how the log is to be applied on that chart. In other words, inside my override:
    this !== undefined, so I can then do     
    return  this.userOptions.scale * Math.log(adjustedNum) / Math.LN10

2. Incorrect
value = lin2log(otherValue);

When called like this, my override can't know which of my charts / which axis is asking for the conversion because this is undefined.

3. Incorrect2
var lin2log = axis.lin2log
value = lin2log(otherValue);

In this case, var lin2log = axis.lin2log doesn't help at all, I double checked and stepped through the code, 
the call to lin2log wasn't binded, (perhaps lin2log = axis.lin2log.bind(axis)?) so when lin2log got called this === undefined.

Going through and substituting axis.log2lin in place of log2lin   and axis.lin2log in place of lin2log appears to fix things.

**Comment by pawelfus** [comment]
Hi @PhilBraica 

Thank you for reporting, you are right we should keep context within this method.

**Comment by smathirajan** [comment]
Hello,
Was this fix backported into 6.0 branch?

Thanks
