### ISSUE TITLE
panning is not working properly with parallel-coordinates.

### ISSUE THREAD

**Issue by VBIManonmaniM** [highcharts/highcharts#8107]
#### Expected behaviour
panning should work with parallel-coordinates.

#### Actual behaviour
But panning is not working properly with parallel-coordinates.

#### Live demo with steps to reproduce
http://jsfiddle.net/m825oea8/2/

#### Product version
Highcharts 

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @VBIManonmaniM 

Thank you for reporting the issue. At this moment, zooming and panning are not implemented (vertical zooming works partially).

**Comment by nsdevaraj** [comment]
Also lasso have problems in selection

**Comment by pawelfus** [comment]
Hi @nsdevaraj 
Could you show demo with lasso selection? Thanks!

**Comment by praveenn-vbi** [comment]
Hi @pawelfus 
This is the demo link for lasso selection
http://jsfiddle.net/nsdevaraj/9f5c2ejc/

You can see that only the points in the first plot line is getting selected. 
Thanks.
