### ISSUE TITLE
Generating RSI Study (Indicator) does not work on Line Charts

### ISSUE THREAD

**Issue by anth-3** [highcharts/highcharts#8109]
#### Expected behaviour
RSI Indicator line appears on Line chart

#### Actual behaviour
RSI Indicator line does not appear on Line chart

#### Live demo with steps to reproduce
https://jsfiddle.net/anth_3/ajx87cw7/

#### Product version
Latest Highstock

#### Affected browser(s)
All that I tested (Chrome, Firefox, Safari)

**Comment by sebastianbochan** [comment]
Hi @anth-3 
The RSI indicator requires the "close" value for calculation. When you use line chart (y value only), the parameters is missing.

For the further [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

**Comment by pawelfus** [comment]
*Internal note:*
At this moment, we require OHLC format for RSI, because we always use Close value. Actually nothing stops us from calculating RSI from a line series, where we can assume given values are Close ones. Probably we can improve RSI to support `params.index` option like we do for SMA/EMA technical indicators.

**Comment by subhabrata2017** [comment]
is there any way to point the line chart data to close. Now for me its pointing open value.

**Comment by pawelfus** [comment]
Hi @subhabrata2017 

Could you provide more details? RSI always use Close value to calculate the line.

**Comment by danieljhochman** [comment]
When is V7 scheduled for release?

**Comment by pawelfus** [comment]
It's implemented since v7, updated demo: https://jsfiddle.net/BlackLabel/r0hvwyto/2/ - not that you need to provide all OHLC data, not only close.

Docs: https://api.highcharts.com/highstock/series.line.useOhlcData
