### ISSUE TITLE
Heatmap 'connectNulls' not working

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts#8116]
#### Expected behaviour

In a heatmap, null areas should be connected if 'connectNulls' is set to 'true'

#### Actual behaviour

Null areas show up as white spaces, although 'connectNulls' set to 'true'

#### Live demo with steps to reproduce

http://jsfiddle.net/2xrnvtuy/

#### Product version
6.0.7

#### Affected browser(s)

All, iOS wrapper included (https://github.com/highcharts/highcharts-ios/issues/81)

**Comment by skuske** [comment]
@pawelfus 

Thanks. :o) That means that there's no way to get rid of those blank (null) areas in Heatmap?

**Comment by pawelfus** [comment]
@skuske `nullColor` works, just remember to use null points in first place, for example: http://jsfiddle.net/hou2brvp/ (x+y are defined, value is null). If you completely remove points, then point will not show up: http://jsfiddle.net/hou2brvp/2/

**Comment by skuske** [comment]
@pawelfus 

Thanks!

**Comment by TorsteinHonsi** [comment]
An alternative way to control the color of missing points is to apply a `plotBackgroundColor`: http://jsfiddle.net/highcharts/hou2brvp/4/
