### ISSUE TITLE
Custom buttons added to a chart are not keyboard-accessible

### ISSUE THREAD

**Issue by AleksueiR** [highcharts/highcharts#8123]
#### Expected behaviour
Buttons added to the chart using `chart.renderer.button` should be keyboard-accessible.

#### Actual behaviour
It's not possible to focus on a custom button by tabbing through the chart's interactive elements even when explicitly setting the `tabindex` attribute.

#### Live demo with steps to reproduce
http://jsfiddle.net/ouroborosDragon/4o7ey37u/1/

#### Product version
6.0.7

#### Affected browser(s)
Chrome, IE 11, likely others

**Comment by sebastianbochan** [comment]
Hi @AleksueiR 
Thank you for reporting.

@oysteinmoseng any comments?

**Comment by pawelfus** [comment]
*Internal note:*
Maybe we could make `KeyboardNavigationModule` + `navModuleFactory` available in the API? It looks really nice and easy to extend with custom elements. For example `annotations` module could be easily added too.

**Comment by oysteinmoseng** [comment]
From upcoming v7.1 there will be an option to add custom accessibility components that will be able handle this. More info will be in the API docs upon release.
