### ISSUE TITLE
Highcharts.Net wrapper does not support softMin or softMax

### ISSUE THREAD

**Issue by schutze** [highcharts/highcharts#8124]
#### Expected behaviour

The softMin and softMax properties should exist for the XAxis and YAxis classes.  These options were introduced a long time ago (version 5.0.1) so it's surprising they are missing. A code review should be performed to make sure there are no other missing properties.

#### Actual behaviour

The Min and Max properties exist for the XAxis and YAxis classes but softMin and softMax do not.

#### Product version

Highcharts.Net wrapper version 6.0.6502

#### Affected browser(s)
Browser does not matter.

**Comment by TorsteinHonsi** [comment]
@pawelfus

**Comment by pawelfus** [comment]
Hi @schutze 

SoftMin and SoftMax options exist in Highcharts.Net for XAxis, take a look: 

- [XAxis.softMin()](http://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_x_axis.html#a5cc3118c83876c48b8c7a5c562c2c23e)
- [XAxis.softMax()](http://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_x_axis.html#a84f21b8f7956edd31e59a93845b7c98f)

YAxis.SoftMin() and SoftMax() are missing, but those were fixed in 6.0.7 in our docs (not related to the .Net wrapper). Classes generated for v6.0.7 should be released in a few days. Fixed in https://github.com/highcharts/highcharts/commit/dc05c4930bd9ba86565da86c35c61aed7de4acc6 commit.

**Comment by TorsteinHonsi** [comment]
@pawelfus On a side note, the docs generator for .NET seems to be buggy:

> A soft minimum for the axis. If the series data minimum is greaterthan this, the axis will stay at this minimum, but if the seriesdata minimum is lower, the axis will flex to show all data.

The words "greaterthan" and "seriesdata" are concatenated, corresponding to newlines in the original doclet.

https://github.com/highcharts/highcharts/blob/8c1c146ab5bf0dd5bd798d997fc46b7fe75884e2/js/supplemental.docs.js#L57-L59

**Comment by pawelfus** [comment]
Thanks! 

From the JSON:

> "description": "A soft minimum for the axis. If the series data minimum is greater\nthan this, the axis will stay at this minimum, but if the series\ndata minimum is lower, the axis will flex to show all data."

Should we replace single `\n` with space and `\n\n` with new line?

**Comment by schutze** [comment]
@pawelfus you are correct.  In the 6.0.6502 wrapper version I am using, I see the `softMin` and `softMax` settings for XAxis so they are only missing for the YAxis.  I will have to try the latest once it is released.

**Comment by pawelfus** [comment]
Wrapper for Highstock v6.0.7 is released, Highcharts v6.0.7 should be ready tomorrow. Sorry for the delay!

**Comment by schutze** [comment]
@pawelfus It would be nice if there was a change log for Highcharts.NET so it is obvious when items are fixed and when releases are available.

Assuming Highcharts.NET for Highcharts v6.0.7 was released as you planned, I downloaded the latest Highcharts JS (Version 6.1.0) and Highcharts.NET for Highcharts.  The Highcharts.Web.Mvc.dll file version is 6.0.6680.8760, rather than the 6.0.7 version number you noted, so I'm guessing the release did not go as planned?  BTW, shouldn't the new version be 6.1.x to coincide with the JS version?

Also, the new file is about half the size of the 6.0.6502 release I am currently using (6.21 MB vs. 12.1 MB).

Lastly, my Visual Studio build failed with the new DLL. If I swap back the old file Visual Studio builds my project just fine.  So, the new file must be missing something.

**Comment by schutze** [comment]
@TorsteinHonsi @pawelfus I figured out why there were build errors when I upgraded to the latest Highcharts.Web.Mvc.dll file:

- `YAxisPlotLinesLabel.Style` was previously `Object `and is now `Hashtable`.  This should have been `Hashtable` from the start but this breaking change should have been documented somewhere. Again, wrappers should probably be treated like any other Highsoft product and appear on the [Changelog page](https://www.highcharts.com/documentation/changelog).
- `YAxisPlotBands.Thickness` and `SolidgaugeSeriesData.InnerRadius` were changed to `Double` when they were `String`. **These must be changed back** to `String` because `Double` does not support percent values as described in the API documentation ([Thickness](https://api.highcharts.com/highcharts/yAxis.plotBands.thickness), [InnerRadius](https://api.highcharts.com/highcharts/series.solidgauge.data.innerRadius)).

**Comment by pawelfus** [comment]
Hi @schutze 

I've just received info that v6.0.7 is still not released, some minor issues are blocking us. We will release v6.1.0 after releasing v6.0.7 - we need last version of v6.0 available. The size of a library is correct. Regarding versioning it's not in sync (.NET wrapper has daily releases, so "x" in v6.0.x is not related to Highcharts version).

You are right, we need to provide changelog with update-notes for .NET wrapper, my apologies for the issues you encountered!

**Comment by schutze** [comment]
@pawelfus I've been checking every day for the 6.1.0 release and saw it today.  It contains `YAxis.SoftMin` and `YAxis.SoftMax` so I will close this issue.

I created #8191 to request that wrappers be documented like the other products and #8229 to change `YAxisPlotBands.Thickness` and `SolidgaugeSeriesData.InnerRadius` back to `String` type.
