### ISSUE TITLE
When min and max are set, plot bands still appear even when all series are hidden

### ISSUE THREAD

**Issue by schutze** [highcharts/highcharts#8125]
#### Expected behaviour

Axis plot bands should be hidden whenever all the series for that axis are hidden.  Plot bands properly toggle when the series are toggled but not if the axis has BOTH a min AND max set.

#### Actual behaviour

When an axis has BOTH a min AND max set, the plot bands on the axis still appear even when all series on the axis are hidden.

#### Live demo with steps to reproduce
http://jsfiddle.net/pLk9v0cm/12/

Hide the "Effluent ph" series and the "Ideal pH Range" plot band still appears.  Now, comment either the min and/or max setting for YAxis id: 0 and the plot band will properly show and hide based on the series.

#### Product version
Highcharts 6.0

#### Affected browser(s)
Browser does not matter.

**Comment by TorsteinHonsi** [comment]
As far as I can see, this is correct behaviour. The plot bands are applied on the axis, so they don't have anything to do with the series per se.

The logic in use is in fact the other way around - when you don't apply `min` or `max` on the axis, and all the data series are hidden, the axis is not able to automatically determine the scale, so all ticks and plotbands are hidden. When you do apply `min` and `max`, the axis has enough information to render ticks and plotbands.

**Comment by schutze** [comment]
Sorry @TorsteinHonsi, but I respectfully don't agree that this should be the correct behavior.  If no min/max settings are applied and you hide all the series for an axis then the scale disappears along with the series.  The same behavior exists if only `softMin` and `softMax` settings are applied.  Use the fiddle above and comment different combinations of settings.  I think `softMin` and `softMax` are the correct behavior and `min` and `max` are in error.

**Comment by pawelfus** [comment]
This issue looks very similar to `showEmpty` and `min`/`max` configs (#705). Probably we could limit rendering plotLines/Bands too.
