### ISSUE TITLE
数据刷新，坐标轴不稳定

### ISSUE THREAD

**Issue by gelin0318** [highcharts/highcharts#8126]
#### Actual behaviour
events: {
    load: function () {
        // set up the updating of the chart each second
var series = this.series[0];
        var x, y;
        setInterval(function () {
            var x = new Date(ret[4][k] * 1000).getTime(), // current time
y = ret[0][k++],
            series.addPoint([x, y], false, true);
x = new Date(ret[4][k] * 1000).getTime(); // current time
y = ret[0][k++];
            series.addPoint([x, y], true, true);
        }, 600);
    }
如题，数据最少设置成0.6秒刷新一次，若再往短了设置，就会出现曲线跳动，不稳定，坐标轴的坐标也显示不清的情况，望解决

**Comment by pawelfus** [comment]
Hi @gelin0318 

Could you contact our support (in english)? Details: https://www.highcharts.com/support Thanks!

**Comment by gelin0318** [comment]
The data is set at least 0.6 seconds to refresh. If the refresh rate gets smaller ,the curve will be unstable, and the coordinates of the axes will also be unstable.

**Comment by pawelfus** [comment]
@gelin0318 
Thanks! Do you mean #7926 issue? It's caused if animation duration > refresh rate. See: https://github.com/highcharts/highcharts/issues/7926#issuecomment-370427468.

**Comment by gelin0318** [comment]
Yes，it's very similar. And the scale of the axes becomes fuzzy.

**Comment by gelin0318** [comment]
Thank you very much.This problem has been solved.
