### ISSUE TITLE
Y-axis has an abnormal coordinate show

### ISSUE THREAD

**Issue by gelin0318** [highcharts/highcharts#8129]
#### Actual behaviour
As shown in figure，the Y-axis has an abnormal coordinate show.

#### Affected browser(s)

![a](https://user-images.githubusercontent.com/38098947/38366391-22695436-3912-11e8-9b3c-dc9a61af3691.png)

**Comment by pawelfus** [comment]
Hi again @gelin0318 

Please, recreate issue in jsFiddle. Thanks!

**Comment by pawelfus** [comment]
Thanks for the options! It was enough to recreate the issue, data want not that important.

Minified demo: http://jsfiddle.net/cxk5cu57/3/
