### ISSUE TITLE
Minimum dragrange value instead of hard-coded 10px

### ISSUE THREAD

**Issue by niekvandael** [highcharts/highcharts#8130]
#### Live demo with steps to reproduce

Possibility to **define** the minimum-dragrange instead of the fixed value of 10px.
https://github.com/highcharts/highcharts/blob/88c0013b0d8a1447fe477af151e64002f59f0ecf/js/parts/Pointer.js#L653

**Comment by sebastianbochan** [comment]
Hi @niekvandael 
Thank you for the suggestion. We will add the option in the future.
