### ISSUE TITLE
Chart doesn't render properly using boost module in system has 4GB RAM

### ISSUE THREAD

**Issue by msjegan3** [highcharts/highcharts#8131]
Hi, 
I am using highchart js with boost module which loads 12 series data.
chart loading perfectly when I am using 16GB RAM installed System.but when i am using 4GB RAM installed system chart doesn't render properly.some parts are missing.

#### Expected behaviour
Chart render properly in both system.
![image](https://user-images.githubusercontent.com/38105188/38368451-f2621d2c-3902-11e8-9760-b5806c5a9cd7.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/38105188/38368371-c1aa777e-3902-11e8-8421-f0746a84ff6b.png)

#### Live demo with steps to reproduce

http://jsfiddle.net/o9qu6myv/33/

#### Product version
Highcharts JS v6.0.7 (2018-02-16)

#### Affected browser(s)
Chrome 65.0.3325.181

**Comment by sebastianbochan** [comment]
Hi @msjegan3 
Thank you for reporting.

@cvasseng

**Comment by msjegan3** [comment]
Hi @cvasseng,
Any update on this issue?

**Comment by KacperMadej** [comment]
+1

**Comment by cvasseng** [comment]
@msjegan3 is the two systems otherwise identical? Specifically, do they have the same GPU?
