### ISSUE TITLE
Loader does not appear between setextremes and Redraw

### ISSUE THREAD

**Issue by vishalbhalla07** [highcharts/highcharts#8137]
#### Expected behaviour
I have a showLoader() in the setExtremes function of high stock . I have disabled liveRedraw and hence  setExtremes method should be called on Mouseup event after the navigator has been set. The showloader simply overlays a div with a loader gif on the chart. As soon as I release the navigator, the loader should appear on the screen

#### Actual behaviour
This method is called but the loader does not appear on the screen because high stock immediately calls the redraw() after execution of the setextremes not allowing enough time for the loader to appear on the screen. On performance profiling it looks like the browser paint is called only after the redraw event is over hence the loader appears but only for a fraction of a second just before the chart is redrawn while it should have as soon as I let go of the mouse in the navigator.

#### Product version
Highstock 4.2.2

**Comment by vishalbhalla07** [comment]
To add to this, it is during large amounts of data for multiple series (say 50 or more ) that I usually observe this and not for a single series.

**Comment by vishalbhalla07** [comment]
Is there a way I could insert a delay between the setExtremes and the Redraw to insert allow the loader to draw on the screen ? Rather where could Insert a setTimeout to call the Redraw event after some delay (I Men’s the Redraw event called after the setExtremes) . Is there a way to disable the Redraw event after the setExtremes until I explicitly call Redraw ? Or to do so on abutting click

**Comment by pawelfus** [comment]
Hi @vishalbhalla07 

Could you provide live demo of the issue? I assume this is your case: http://jsfiddle.net/BlackLabel/4tf2pxab/4/ - `showLoading` in `setExtremes` and `hideLoading` in `redraw` event. You can see blinking `Loading...` screen.

Note: It works the way you described since v6, older versions won't show loading info.

**Comment by sebastianbochan** [comment]
Closed due to inactivity. Please reopen if any additional information will be available.
