### ISSUE TITLE
Can arearange support null lower/upperbound?

### ISSUE THREAD

**Issue by lzl124631x** [highcharts/highcharts#8139]
#### Expected behaviour
For arearange, if upperbound is null, just show the lower bound and highlight the upper area.

![1](https://user-images.githubusercontent.com/5824517/38395029-baf81052-38e5-11e8-8ea5-44a01a421e9c.png)

#### Actual behaviour
No arearange will show if either bound is missing.

#### Live demo with steps to reproduce

http://jsfiddle.net/Richard_Liu/o8wmzw0a/2/

**Comment by TorsteinHonsi** [comment]
You can achieve the same by using an area with a higher `threshold` value: http://jsfiddle.net/highcharts/o8wmzw0a/4/

It's not perfect however, as the threshold needs to be hard-coded to the Y axis max. In practice you would need to analyze the data for its max value before creating the chart.

**Comment by lzl124631x** [comment]
Yes. I came up that solution before. [SO link](https://stackoverflow.com/questions/49501992/how-to-create-a-highcharts-area-with-the-top-area-highlighted). But I'd like to prevent the computation because the chart is so dynamic; I need to compute the `threshold` every time.

I wish I could stick my `threshold` to the highcharts-computed y-axis min/max (I cannot know these values before the chart is rendered), or `-Infinity`/`Infinity`.

This could be a good feature to add.

**Comment by TorsteinHonsi** [comment]
Yes, `-Infinity/Infinity` was what I had in mind too! Commit coming up.

**Comment by lzl124631x** [comment]
Wow. This is fabulous. Thanks @TorsteinHonsi !

**Comment by lzl124631x** [comment]
@TorsteinHonsi 
* When will 6.1.0 be available?
* Will arearange automatically inherit this change?
* May you have a look at this [issue](https://github.com/highcharts/highcharts-utils/issues/10)? I wanted to contribute to highcharts but I cannot run the test.

**Comment by pawelfus** [comment]
Hi @lzl124631x 

- v6.1 was released 2018-04-13
- It's a different case, valid point in area range should have both values, lower and upper. If one of them is nullified, then point on a chart is not rendered. 
- map collection is private, I will leave this up to @TorsteinHonsi

**Comment by lzl124631x** [comment]
@pawelfus Thanks for your response.

> It's a different case, valid point in area range should have both values, lower and upper. If one of them is nullified, then point on a chart is not rendered.

I understand this point. But my original thought was extending the arearange. Imagine it supports thresholds being `Infinity/-Infinity`, I don't need to switch to area any more; and arearange could support rendering the following chart.

![image](https://user-images.githubusercontent.com/5824517/39142748-56b9abf6-46e0-11e8-8b47-4ada9355a149.png)

And that's why I investigated how to contribute to highcharts and create a pull request for this feature.

**Comment by pawelfus** [comment]
@lzl124631x 
Thank you for the image - now it's clear what you want to achieve. This is not exactly as your image, but good starting point: http://jsfiddle.net/BlackLabel/o8wmzw0a/19/ - point is not treated as null if one of high/low is defined.

**Comment by pawelfus** [comment]
Thanks! Updated jsFiddle demo. This `if()` always evaluates to false and should, I was playing around to get straight lines when point changes null->value but it's not working. We would need to artificial points like this:

```
*--*--* <-- extra point
      |
      |
      *
```
But we have:

```
*--*
    \
     \
      *
```
