### ISSUE TITLE
Series legend items don't display in the legend when colorAxis.showInLegend is false

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#8140]
#### Expected behaviour
Series legend items should normally appear in the legend when `colorAxis.showInLegend` is `false` .

#### Actual behaviour
Legend is empty.

#### Live demo
http://jsfiddle.net/BlackLabel/a1v5v4ps/

#### Product version
Highcharts 6.0.7

**Comment by kamilkulig** [comment]
_Internal note:_ 
I suppose that this issue occurs because the code responsible for hiding legend items:
**lines 990-993 in modules/heatmap.src.js** :
```            
                    // Don't add the color axis' series
                    each(colorAxis.series, function(series) {
                        series.options.showInLegend = false;
                    });
```
is not included in the scope of the `if` condition that precedes it: 

```
if (colorAxis.options.showInLegend) {
       // Data classes
      (...)
```

---

**Workaround:** http://jsfiddle.net/BlackLabel/a1v5v4ps/

**Comment by TorsteinHonsi** [comment]
I don't get it... Isn't it expected that the color axis is hidden from the legend when `colorAxis.showInLegend` is `false`?

**Comment by pawelfus** [comment]
That's correct, but when colorAxis is hidden in the legend, default legend should show up: http://jsfiddle.net/BlackLabel/a1v5v4ps/25/ (bugfix branch) vs http://jsfiddle.net/BlackLabel/a1v5v4ps/ (v6.1.0)
