### ISSUE TITLE
legend with verticalAlign of 'middle' and 'y' offset and navigation allocates too much height to legend

### ISSUE THREAD

**Issue by matt-hoskins** [highcharts/highcharts#8148]
#### Expected behaviour
If I use verticalAlign of "middle" and a "y" offset on the legend and the legend has too many items to display within the vertical space available to the legend then when the navigator is enabled I expect it to account for the "y" offset when calculating the height available for the legend.

#### Actual behaviour
It seems maybe the "y" offset isn't accounted for when allocating the height available for the legend when verticalAlign is "middle".

#### Live demo with steps to reproduce
I've taken the highcharts legend navigation sample and just changed the verticalAlign to "middle":
http://jsfiddle.net/f5v0w4pr/2/

If you alter the legend "y" value to be 0 then it's fine.

(Note that the top symbol on the legend is truncated, but I've noted that the highcharts samples are affected on https://github.com/highcharts/highcharts/issues/7396)

#### Product version
Latest highcharts release (6.0.7)

#### Affected browser(s)
Seen it under firefox and chrome

**Comment by pawelfus** [comment]
Hi @matt-hoskins 

Thank you for reporting the issue. I assume you are aware that `verticalAlign: "top"` works fine: http://jsfiddle.net/BlackLabel/f5v0w4pr/7/
