### ISSUE TITLE
highcharts.js regexp affected by jawr minification procedure

### ISSUE THREAD

**Issue by galanblancom** [highcharts/highcharts#8149]
#### Expected behaviour
**/(NaN| {2}|^$)/.test(value)** must be converted to: **(new RegExp("NaN| {2}|ˆ$")).test(value)**

#### Actual behaviour
After apply JAWR to a Spring MVC project I got this line: **/(NaN| {2}|^$)/.test(value)** converted to this: **/(NaN|{2}|^$)/.test(value)**, this produce an error on Google Chrome.

#### Product version
Highcharts JS v6.0.7

#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Hi @galanblancom 

Thank you for reporting.

@TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
It is a bug in JAWR, so I'm not sure how to handle it. We could fix it, but it's a bit painful to create workarounds for other libraries' bugs...

**Comment by ashishshukla1681** [comment]
Getting the same error while trying to apply JAWR for highcharts library and their module specific JS files in my project.

**Comment by pawelfus** [comment]
Hi @ashishshukla1681 

Did you contact with JAWR authors? This should be reported to them.
