### ISSUE TITLE
X-Range points placed incorrect

### ISSUE THREAD

**Issue by mnboos** [highcharts/highcharts#8152]
#### Expected behaviour
The date range on the chart should match the dates in the data.

#### Actual behaviour
The date range is totally incorrect on the  chart and doesn't correspoding with the data.

#### Live demo with steps to reproduce
That's the original link for the documentation to the x-range demo:
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/x-range/

#### Product version
 Highcharts JS v6.0.7 (2018-02-16)
 X-range series

#### Affected browser(s)
- Chrome (Version 64.0.3282.186)
- Edge (Version 41.16299.248.0)
- Firefox (Version 59)

**Comment by pawelfus** [comment]
Hi @mnboos 

Thank you for reporting the issue. Could you define `The date range is totally incorrect `? This is how this chart looks on my mac: 

![screen shot 2018-04-10 at 11 42 28](https://user-images.githubusercontent.com/1453926/38549442-4db4a442-3cb4-11e8-8564-8326aca83c64.png)

And dataset has first point in Novermber (`Date.UTC(2014, 10, 21)`), last in December (`Date.UTC(2014, 11, 23)`). Reminder: months in JS start at 0 (0=January, 11=December).

**Comment by mnboos** [comment]
Thank you @pawelfus for the fast reploy.

Apologies for the misunderstanding, I didn't realize the zero-index of the months.
