### ISSUE TITLE
Bug: Wrong Chart being destroyed 

### ISSUE THREAD

**Issue by raptor235** [highcharts/highcharts#8154]
I'm iterating over multiple divs on a page to display a chart in each div... I call highcharts on each div passing in custom attributes as options. 

The problem I'm running into is that the 2nd highcharts call destroys the first drawn chart... I've tracked it down to the getContainer functions line 974... https://github.com/highcharts/highcharts/blob/88c0013b0d8a1447fe477af151e64002f59f0ecf/js/parts/Chart.js#L974

Unfortunately the project is private so I can't make this available publicly... but I'll explain what's happening in detail.

I'm drawing charts as follows -> http://www.flowpress.com/screenshots/screenshot_2018-04-10_at_12.00.08PM.png 

When the second chart is being drawn the first chart gets destroyed by the  

charts[oldChartIndex].destroy();

You can see that the chart we're working with is second on the screen
http://www.flowpress.com/screenshots/screenshot_2018-04-10_at_12.01.03PM.png

but when I dump charts[oldChartIndex] that get's checked it shows chart #1 resulting in chart #1 being destroyed and then chart #2 gets drawn where it should... 

http://www.flowpress.com/screenshots/screenshot_2018-04-10_at_12.02.37PM.png

Resulting in this 

http://www.flowpress.com/screenshots/screenshot_2018-04-10_at_12.03.48PM.png

First chart is always dead.

I do a foreach loop in jQuery and then target each chart and pass in new options so I'm not sure why that first chart get's killed... 

Any thoughts?

**Comment by raptor235** [comment]
To me it seems like 

        oldChartIndex = pInt(attr(renderTo, indexAttrName));

isn't working correctly as renderTo is being ignored and not making a differentiation between the two different target containers.

**Comment by pawelfus** [comment]
Hi @raptor235 

Thanks for reporting the issue. My first thought: maybe you have multiple containers with the same ID?  Simple demo: http://jsfiddle.net/BlackLabel/u1pjLem0/3/ - works fine. Without live demo (dataset doesn't matter in your issue, right?) we won't be able to fix this.

PS: For debugging we suggest to use `highcharts.src.js` file instead of minified `highcharts.js`.

**Comment by raptor235** [comment]
Hi @pawelfus ,

No we don't use targets... we loop over a jquery selection of items and assign each by one by one... 

In the each loop we loop over as follows

				jQuery(item_target).highcharts(options_context);


http://www.flowpress.com/screenshots/screenshot_2018-04-19_at_9.28.44PM.png

and getting random draw fail..

http://www.flowpress.com/screenshots/screenshot_2018-04-19_at_9.30.00PM.png

As I said in the initial ticket whatever is the first container to draw then get's destroyed by the second chart that gets drawn on that page... without fail...

**Comment by raptor235** [comment]
In this example you can see chart 2 is being rendered

http://www.flowpress.com/screenshots/screenshot_2018-04-19_at_9.38.11PM.png

yet chart #1 is about to be destroyed by the breakbpoint... 

charts[oldCharrtIndex] points to chart #1 

http://www.flowpress.com/screenshots/screenshot_2018-04-19_at_9.39.21PM.png

....

so why is the first chart being destroyed while the 2nd chart gets drawn...

This only happens when the second chart gets drawn...

To me again it seems that 

       oldChartIndex = pInt(attr(renderTo, indexAttrName));

is ignoring the fact that there are multiple charts on the page if renderto was taken into account it shouldn't return chart #1 as the container for chart #2 is different from the first one...

**Comment by raptor235** [comment]
I've added a watch on renderto you can see the renderto container is below the chart that's about to be destroyed 

renderto highlighted
http://www.flowpress.com/screenshots/screenshot_2018-04-19_at_9.42.39PM.png

charts[oldChartIndex].destroy(); highlighted

http://www.flowpress.com/screenshots/screenshot_2018-04-19_at_9.43.21PM.png

**Comment by raptor235** [comment]
Well I found the issue.. I had a hardcoded data attribute that was causing this... if this happens to someone else see if you have 

data-highcharts-chart="0" 

in your source that's hard coded... 

pls close this issue.

**Comment by pawelfus** [comment]
Hi @raptor235 

Thanks for the info! We don't hard code `data-highcharts-chart="0"` - value for this attribute is taken from `chart.index`, where each new chart has incremented index.
