### ISSUE TITLE
Title of StockChart Overlaps Range Selector when No Data

### ISSUE THREAD

**Issue by ricazhang** [highcharts/highcharts#8155]
#### Expected behaviour
The title and range selector should not overlap. When there _is_ data, they do not overlap. But when there is no data, and we are using the noData display, they overlap.

#### Actual behaviour
The title and range selector overlap. 
![image](https://user-images.githubusercontent.com/7819877/38592017-92cfd756-3cee-11e8-9b0f-0c4b71129b63.png)

#### Live demo with steps to reproduce
Example of the overlap: http://jsfiddle.net/pzfLartg/2/
If you change line 60 to say `data = data` then that will fill the chart with data and the title will no longer overlap with the range selector.

#### Product version
Highstock JS v6.0.7

#### Affected browser(s)
Chrome, Firefox, etc.

**Comment by sebastianbochan** [comment]
Hi @ricazhang 
Thank you for the reporting.

**Comment by sebastianbochan** [comment]
Issue is not valid since HS v7.0.2.

Please reopen and attach the details, when problem will come again.
