### ISSUE TITLE
Glyphicon Fails To Load

### ISSUE THREAD

**Issue by kitturkoustubh** [highcharts/highcharts#8156]
> Link to see the what I found

https://api.highcharts.com/class-reference/namespaces.list

Search Class Reference Search button: 
**glyphicon glyphicon-search** 
fails to show icon there.

```
<div class="input-group-btn">
      <button id="search-submit"><i class="glyphicon glyphicon-search"></i></button>
</div>
```
It seems a minor thing, actually not an issue but an enhancement feature. 
Also, check spelling once for **glyphicon** class, seems its **glyphicons**.
I checked on chrome and firefox both.

**Comment by pawelfus** [comment]
Thanks @kitturkoustubh !
