### ISSUE TITLE
Unable to synchronize highchart using angular5 upon click event

### ISSUE THREAD

**Issue by manhar-developer** [highcharts/highcharts#8157]
#### Expected behaviour
Multiple highcharts should be syncronize upon click event. For eg. If there are two highcharts are one is clicked for drilled down, then the other highchart should also drilldown

#### Actual behaviour
event property does not support the global function

#### Live demo with steps to reproduce

https://stackblitz.com/edit/angular-r4hy3c?file=app/app.component.ts

In this url drill down is working fine individually. 

#### Product version

Highcharts : 6.0.7
Angular highcharts 5.2.10

**Comment by pawelfus** [comment]
Hi @manhar-developer 

Could you contact our support? We use github issues as bug reports, not support tickets. See details: https://www.highcharts.com/support Thanks!
