### ISSUE TITLE
Treemap: data label exceeds point's boundaries

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#8160]
#### Expected behaviour
Data label shouldn't exceed the boundaries of its point. The overflow should be handled somehow (e.g. by ellipsis crop).

#### Actual behavior
The label exceeds point's boundaries when the word (no white spaces inside) is wider than the point.

#### Live demo
http://jsfiddle.net/BlackLabel/4wf9cb95/

#### Product version
6.0.7

**Comment by oblivione81** [comment]
I'm experiencing the same issue in styled mode. Any news on this?

**Comment by oblivione81** [comment]
Update: I made some progress to enable ellipsis for data labels in styled mode.

http://jsfiddle.net/b0fo1wcr/
(Please resize the window to see the ellipsis work correctly.) 
I still don't know why the initial state of the data labels bounding box is incorrect, which is causing the ellipsis to initially not work. Is this possible to work that around by triggering a reflow of the chart somehow?

What I've found:

- WIth `useHTML: false`, the data labels are split into multiple tspans, 1 per row,  that do not overflow the bounding box. So I don't see a way of activating the ellipsis.

- With `useHTML: true`, the data labels are rendered through a single span, which overflows the bounding box. So, it's only a matter of activating these 3 properties for the style of that span:
`white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis`
Problem is, the span that highcharts creates by default has an inline `white-space: normal` property, which overrides the one you set in the css. To work this around, you can use a formatter to return your own span.

Now, I'm not sure if there's a better workaround for this issue, and this is still not working untill you resize the window, but at least this is some info.

**Comment by k-dauda** [comment]
The workaround I used was to make the width of the dataLabel smaller than it's bounding box.
http://jsfiddle.net/b0fo1wcr/4/
