### ISSUE TITLE
Boost zoom does not kick in the SVG renderer

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#8164]
V6.0.7 

Boosting a chart and then zooming in should kick the SVG renderer (with proper opacity/lineWidth) in. 
The above is not deterministic. 
See here: https://jsfiddle.net/onemenny/yyhrLjmd/3/
It's hard to pin the scenario down, but it seems that after 3 zooms, The svg works fine, but when reseting the zoom and doing it once more, the SVG does not kick in. 

![apr-12-2018 13-50-49](https://user-images.githubusercontent.com/1677449/38673303-9b6eee8a-3e59-11e8-8f45-58d18ce73948.gif)

**Comment by onemenny** [comment]
Thank you @pawelfus 
Can this be turned into a workaround? can I trigger setExtremes after the selection event?

**Comment by pawelfus** [comment]
Yes, it can, but if we want to show extremes button, then it's a bit tricky, possible workarounds:
- extremes should be changed a little: https://jsfiddle.net/BlackLabel/yyhrLjmd/8/ 
- we need to use `setTimeout`: https://jsfiddle.net/BlackLabel/yyhrLjmd/9/
- we can handle zoom-in action by callback (prevent default function by returning `false`) : https://jsfiddle.net/BlackLabel/yyhrLjmd/11/

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/cpawxs9b/
Snippet:
```js
(function(H) {
  H.addEvent(H.Chart, 'beforeRedraw', function() {
    this.boostForceChartBoost = undefined;
  });
})(Highcharts);
```

*Internal note:*
We have special event for boost called `predraw` (`addEvent(chart, 'predraw', preRender);`). Replacing `predraw` with `beforeRender` resolves the issue, but I don't know what consequences may this change have. Do you remember @cvasseng reason for `predraw` to be placed somewhere in the middle of `chart.render()`?
