### ISSUE TITLE
Not all points are visible in boost mode

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#8166]
#### Expected behaviour
All points should be visible when using boost module.

#### Actual behaviour
Some of the points are not visible when boost module is used. In some cases (the 1st example below), setting useGPUTranslations to true helps but in others (the 3rd example below) it works the other way around (setting useGPUTranslations to true making points disappear). Looks like the latest version when it worked (with useGPUTranslations disabled) was v5.0.14 (the 2nd example below). Additionally, sometimes error: ‘[.Offscreen-For-WebGL-0000009C276F23B0]RENDER WARNING: Render count or primcount is 0.’ occurs.

#### Live demos
http://jsfiddle.net/xstLb04f/ - v6.0.7, some points are not visible (useGPUTranslations disabled)
http://jsfiddle.net/77xohfxm/ - v5.0.14, all points are visible (useGPUTranslations disabled)
http://jsfiddle.net/dzmkLtce/ - v6.0.7, some points are not visible (useGPUTranslations enabled)

**Comment by Nijadas** [comment]
boost: {
				        useGPUTranslations: true,
				        usePreAllocated: true
				    },
  plotOptions: {
    series: {
    cropThreshold: Infinity,
    boostThreshold: 1000000,
		        	 turboThreshold: Number.MAX_VALUE
    }
  },
this may work

**Comment by Nijadas** [comment]
http://jsfiddle.net/6303e8g5/4/
please check if this works fine

**Comment by cvasseng** [comment]
Internal note: the case when points are not visible and `useGPUTranslations = true` is caused by the known floating precision issue with large numbers with small increments on the x-axis. The other issue may be a similar thing looking at the data, but more investigation is needed.

**Comment by pawelfus** [comment]
2019 update:
First two demos are fine, the remaining issue is with `useGPUTranslations = true` which is known and described issue in [docs](https://api.highcharts.com/highcharts/boost.useGPUTranslations).
