### ISSUE TITLE
Edge compatibility: querySelectorAll with attribute value search fails sometimes

### ISSUE THREAD

**Issue by cosycode** [highcharts/highcharts#8167]
This test preparation fails on Edge:
```javascript
querySelectorAll('g.highcharts-label[visibility=hidden]')
```
We have to find a workaround for querySelectorAll on Edge.

**Comment by cosycode** [comment]
Possible related Edge issues:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12380812/
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7163109/

**Comment by oysteinmoseng** [comment]
Problem is, this does not fail on Edge for me, neither in Edge 14 or 16: http://jsfiddle.net/xqktmuyt/

Are we sure this is an Edge issue?

**Comment by cosycode** [comment]
Further tests indicate, that this was just an issue in Edge 15. Edge 14 and 16 are fine and therefor the case will be closed without providing a bugfix for tests on Edge 15.
