### ISSUE TITLE
Variwide throws an error when the mouse moves over any column

### ISSUE THREAD

**Issue by joseph-newton** [highcharts/highcharts#8173]
#### Expected behaviour
Users should be able to move their mouse over any column in the chart without any errors.

#### Actual behaviour
Throws `TypeError: cannot read property 'attr' of undefined` from [variwide.js](https://github.com/highcharts/highcharts/blob/4cd3bbc87355102d740923156cb61d0af14dde76/js/modules/variwide.src.js#L157):
```
c(b.Axis, "afterDrawCrosshair", function(a) {
    this.variwide && this.cross.attr("stroke-width", a.point && a.point.shapeArgs.width)
});
```
#### Live demo with steps to reproduce
https://www.highcharts.com/demo/variwide
Open the browser dev-tools console, move the mouse over any of the columns.

#### Product version
Highcharts 6.1.0

#### Affected browser(s)
Presumably all of them (tested in latest Chrome, Firefox, Edge and IE)

**Comment by pawelfus** [comment]
Hi @joseph-newton 

Thank you for reporting this regression!
