### ISSUE TITLE
Curve display problem

### ISSUE THREAD

**Issue by gelin0318** [highcharts/highcharts#8176]
#### Expected behaviour
I want the result of red line

#### Actual behaviour
Actual the result is the yellow
![1](https://user-images.githubusercontent.com/38098947/38734870-a4836c2a-3f59-11e8-9458-ec850144d323.png)

#### Live demo with steps to reproduce

my code:
    var chart3 = {
                {#backgroundColor: '#020611',#}
                 backgroundColor:'rgba(0,0,0,0)',
                style: {
                    fontSize: '12px',
                    fontWeight: 'bold',
                },
                type: 'line',
                {#缩放的设置#}
                zoomType: "x",
                {#缩放键的设置#}

                resetZoomButton: {

                    position: {
                        x: 0,
                        y: 0
                    },
             theme: {
                        fill: '#084679',
                        opacity:'0.8',
                        style:{
                            color:'white'
                        },
                        stroke: 'silver',
                        r: 8, {# 圆角#}
                        states: {
                            hover: {
                                fill: '#084679',
                                opacity:'1',
                                style: {
                                    color: 'white'
                                }
                            }
                        }
                    }
                },
                {#shift平移#}
                panning: true,
                panKey: 'shift',

                animation: {
                    duration: 100
                },
                marginRight: 10,
                events: {
                    load: function () {
                        // set up the updating of the chart each second
                        var series = this.series[0];
                        var x, y;
                        setInterval(function () {
                            if(flag1){

                            }
                            else{
                            x = ret[8][r];
                            y = ret[9][r++];
                            series.addPoint([x, y], true, false);
                            }
                        }, 100);
                    }

                }
            };
             var title3 = {
                text: null,
            };
            var xAxis3 = {
                {#十字准线#}
                crosshair: true,
                lineWidth:1,
                lineColor:'white',
                {#tickInterval: 0.001,#}
                tickColor:'white',
                minorGridLineWidth: 0,
                minorTickInterval: 0.1,
                minorTickWidth: 3,
                title: {
                    text:null
                },
                tickPixelInterval: 100,
                {#坐标显示内容#}

            };
            var yAxis3 = {
                {#十字准线#}
                crosshair: true,
                title: {
                    text:null
                },

                tickPixelInterval: 100,
                tickPosition:'inside',
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }],
            };

            var tooltip3 = {
                {#在固定的位置显示标签#}
                formatter: function () {
                    return 'longitude: ' + this.x + '<br/>' + 'latitude: ' + this.y;
                }
            };
            var plotOptions3 = {
                line: {
                    dataGrouping: {
                        enabled: false,
                    },
                },
                series: {
                    marker: {
                        enabled: false,
                        symbol: 'circle',
                        radius: 1,
                    },
                    allowPointSelect: true,
                    connectNulls: true,
                    cursor: 'pointer',
                },

            };
            {#图例的显示#}
            var legend3 = {
                enabled: false
            };
            var exporting3 = {
                enabled: false
            };
            var series3 = [
                {
                    lineWidth:3,
                    color:'#FEFE43',
                    name: 'longi_lati_tude',
                    data: [[ret[8][r], ret[9][r++]]]
                    //{())
                },];

**Comment by sebastianbochan** [comment]
Hi @gelin0318 
Thank you for contacting us. This is our bugtracker for reporting bugs, not [support](http://www.highcharts.com/support) cases. For the further questions please use forum / stackoverflow or email.

ps. You should use the spline series and correct data. 
Example:
- https://www.highcharts.com/demo/spline-inverted
