### ISSUE TITLE
I want to get both series point in single on click event

### ISSUE THREAD

**Issue by kamalkishorebss** [highcharts/highcharts#8177]
Hello all,
I want to get both series value in single click event, how I can do that, please suggest

I am trying this way

  scrollablePlotArea: { minWidth: 100,scrollPositionX: 2},
            plotOptions: { series: { 
              cursor: 'pointer',
              point: { 
                  events: { 
                      click: function (e) {                     
                         alert('Category: ' + this.category);
                       },
                      mouseOver: function () {                      	
                      	if(document.getElementById('values1')){
                      	 var x = document.getElementById('values1');
                      	 x.innerHTML = this.x;	
                      	}                         
                      	if(document.getElementById('values2')){
                      	  var y = document.getElementById('values2');	
                      	  y.innerHTML = this.y;	
                      	}                         
                      }                      
                }
              },                     
            }

             
            },
            
            type: 'arearange',            
            tooltip: {
	            crosshairs: true,
              shared: true,
              formatter: function() {
	              var s = [];                 
	              this.points.forEach((point, index) => {
		      s.push('<span style="color:#D31B22;font-weight:bold;">'+ point.series.name +' : '+point.y +'<span>');
		      });
		     return s;	                
	            }	            
            },
            series: [
                  {
            	     name:"a",
                     data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
                  },{
                    name:"b",	
                    data: [144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4, 29.9, 71.5, 106.4, 129.2],
                  }
            ]
        }

**Comment by sebastianbochan** [comment]
Hi @kamalkishorebss 
Thank you for contacting us. This is our bugtracker so for the [support](http://www.highcharts.com/support) cases please use forum / stackoverflow or email.
