### ISSUE TITLE
"Large tree map" does not work 

### ISSUE THREAD

**Issue by steeeeven123456** [highcharts/highcharts#8180]
#### Expected behaviour
"Large tree map" should work 

#### Actual behaviour
"Large tree map" does not work (blank page)

#### Live demo with steps to reproduce
template: https://www.highcharts.com/demo/treemap-large-dataset

**Comment by TorsteinHonsi** [comment]
It works for me. What browser are you on? Can you try a refresh, maybe the old Highcharts version is cached?

**Comment by sebastianbochan** [comment]
For the reproduce, run the jsfiddle and the problem is with $ is missing.

![zrzut ekranu 2018-04-16 o 10 32 39](https://user-images.githubusercontent.com/2115686/38798330-98344d68-4161-11e8-900e-14cc25cb2dd5.png)

**Comment by Nijadas** [comment]
maybe because of absence of jquery file

**Comment by steeeeven123456** [comment]
Thanks, it works fine now.
