### ISSUE TITLE
Sunburst DrillUp

### ISSUE THREAD

**Issue by ryanhepple6489** [highcharts/highcharts#8181]
Sunburst chart does not "drill up" by clicking center circle anymore. My application is dependent on this. Stopped working since Highcharts 6.1.0 (2018-04-13). 
Example: https://www.highcharts.com/demo/sunburst

**Comment by pawelfus** [comment]
Thanks @ryanhepple6489 for reporting.

It's a regression after ea00fde4b - @jon-a-nygaard
