### ISSUE TITLE
World Map Does not show Data

### ISSUE THREAD

**Issue by deep2701** [highcharts/highcharts#8182]
#### Expected behaviour

World Map should display the country wise statistics

#### Actual behaviour

Its throwing an error 
Array.prototype.forEach called on null or undefined

#### Product version

Issue is with version
Highmaps JS v6.1.0 (2018-04-13)

Current implementation works fine with  version
Highmaps JS v6.0.7 (2018-02-16)

#### Affected browser(s)

All

**Comment by sebastianbochan** [comment]
Hi @deep2701 
When I run the demo: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/rich-info/ all seems to working fine. Please let me know which exactly demo you run.

**Comment by deep2701** [comment]
Hi @sebastianbochan 

Thanks for the response , i think the issue is due to different versions of highchart.js and modules/map.js

Check this fiddle : http://jsfiddle.net/9an73pgy/4/

If any of these 2 scripts are updated to latest, the map stops displaying. 

Do we always need to work with a single version of Highchart scripts ?

**Comment by pawelfus** [comment]
Hi @deep2701 

Yes, you should work with one version of scripts, for example all files from v6.1.0 or v6.0.7. Between patch versions (e.g. v6.0.6 and v6.0.7) it may work without issues but it's not guaranteed. Simply some parts may be refactored (or simply added more arguments to a function, function name changed etc. etc.) and will not work across different versions. Do we have anywhere in our docs written that you **can** use different versions of packages? We will remove/change that.

**Comment by deep2701** [comment]
@pawelfus : Thanks for the clarification. I could not find any document about the versions compatibility  hence raise the issue. It will be great if we can have the backward compatibility but a compatibility chart or advice somewhere will be also helpful.

**Comment by pawelfus** [comment]
@deep2701 

Highcharts releases are backward compatible. If you upgrade from v6.0.1 to v6.0.2 you don't have to change anything. Just upgrade/downgrade the whole library, not random parts of it.
