### ISSUE TITLE
Exporting CSV downloads all data instead of zoomed portion

### ISSUE THREAD

**Issue by colincueto** [highcharts/highcharts#8183]
#### Expected behaviour
Downloaded CSV only shows data within selected area e.g. data from 100-150km only.

#### Actual behaviour
Downloaded CSV contains all data e.g. data from 0-187km

#### Live demo with steps to reproduce
http://jsfiddle.net/jcocueto/9yrwffby/6/
Steps:
* Zoom from around 100km to 150km
* Click context button
* Click Download CSV
* Open CSV file and check contents

#### Product version
Highcharts latest version

#### Affected browser(s)
Firefox, Chrome

**Comment by sebastianbochan** [comment]
Hi @colincueto 
Thank you for the opinion. The functionality is related with the topic  https://github.com/highcharts/highcharts/issues/7913 so I lets keep all in the single thread.
