### ISSUE TITLE
Weight issue (?) in version 6.1.0

### ISSUE THREAD

**Issue by jwldnr** [highcharts/highcharts#8184]
We're seeing some unexpected behaviour with the wordcloud module since upgrading from Highcharts JS`v6.0.7` to `v6.1.0`:

#### Actual behaviour

1.  words with higher weight in series are not showing in the wordcloud:
https://codepen.io/jwldnr/pen/PRMGEr

2. words with same weight in series are showing errors:
https://codepen.io/jwldnr/pen/MVNjRv

![err](https://user-images.githubusercontent.com/11960421/38800015-60cf72bc-4166-11e8-997c-4676aa4b7a5f.png)

#### Expected behaviour

1. words with higher weight are showing and are larger than those with lower weight.

2. words with same weight are showing without errors and are equal in size.

#### Product version
Highcharts JS `v6.1.0` (2018-04-13)

**Comment by sebastianbochan** [comment]
Hi @jwldnr 
Thank you for the reporting.

@jon-a-nygaard any comments?

**Comment by jwldnr** [comment]
Hi @sebastianbochan no problem.

I've got another example here:

#### Actual behaviour

1. words with short names are not showing up in wordcloud:
https://codepen.io/jwldnr/pen/pLMNxK

_same pen with longer words:_
https://codepen.io/jwldnr/pen/PRMbVm

#### Expected behaviour

1. words show up regardless of name length

**Comment by jwldnr** [comment]
I believe theres something up with the font size calculation because the same series with different weight partly shows up:

https://codepen.io/jwldnr/pen/MVNbdZ

**Comment by pawelfus** [comment]
It's a regression from b76ae40f6c139795d1fd6cdba669a4a8998f925d - playing field used to be hardcoded, now it's calculated, probably a small mistake there.

**Comment by ppotaczek** [comment]
This problem seems to be related with chart width.

Example: https://jsfiddle.net/BlackLabel/5etnsony/

**Comment by KacperMadej** [comment]
+1

**Comment by jasonbenedict** [comment]
In this example I'm missing the eighth (last) value.

[https://jsfiddle.net/skj78u5a/ ](https://jsfiddle.net/skj78u5a/)

**Comment by PaulDalek** [comment]
+1

**Comment by pawelfus** [comment]
Bug is still present in v6.1.1: https://jsfiddle.net/BlackLabel/qcc57umw/25/
