### ISSUE TITLE
Bar chart x axis lables taking half width of chart when height is very high

### ISSUE THREAD

**Issue by smithj0016** [highcharts/highcharts#8185]
#### Expected behaviour
I have any number of categories in a bar chart. Normally it omits few of them when there are too many. But I want to show all. So I dynamically increase height of bar chart and it is working fine

#### Actual behaviour
But it is also increasing the width of x axis labels. Now they are coming in half of the chart width and looking horrible.

#### Live demo with steps to reproduce
http://design.tribondinfosystems.com/vertical.php
 

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @smithj0016 

Thanks for reporting your issue. You can set fixed margin on the left side: https://api.highcharts.com/highcharts/chart.marginLeft so labels will not take more space than defined value. 

If you have questions, please contact our support: https://www.highcharts.com/support - we are trying to keep github issues as bug reports, not support tickets, thanks!

**Comment by smithj0016** [comment]
Thanks for reply.
When I added margin into chart it is behaving weird. Labels overlapped each others.  Please see at below link nothing is drawn as graph.

http://design.tribondinfosystems.com/vertical_updated.php

If possible can you please provide an example with my data values on js fiddle.

**Comment by pawelfus** [comment]
> If you have questions, please contact our support: https://www.highcharts.com/support - we are trying to keep github issues as bug reports, not support tickets, thanks!
