### ISSUE TITLE
Incorrect stacked data render on mobile device

### ISSUE THREAD

**Issue by FonDorn** [highcharts/highcharts#8188]
Hi!  I use highcharts in WebView on React Native (iOS) and when I scrolling stacked chart then next column show incorrect data (less than in reality). After scroll this column rendered ok, but next column will have the same effects.

#### Live demo with steps to reproduce
![incorrectrender](https://user-images.githubusercontent.com/778724/38839624-404b11c6-41e4-11e8-8b6b-12bdb393ae87.gif)

#### Product version
version 6.1.0

#### Affected browser(s)
iOS application

**Comment by pawelfus** [comment]
Hi @FonDorn 

Thank you for reporting the issue. This looks wrong (stack label is correct), but can you recreate issue in jsFiddle? Unfortunately, we will not be able to fix this issue basing on a gif. 

Simple demo: http://jsfiddle.net/BlackLabel/sgL1pkuk/1/ - works fine, feel free to use my demo as base and update it.

**Comment by FonDorn** [comment]
Demo link - http://jsfiddle.net/sgL1pkuk/14/
You can see this issues when zoom-in. Thanks!

**Comment by FonDorn** [comment]
@pawelfus Thank! Works fine

**Comment by pawelfus** [comment]
Let's reopen this - we should fix this in the core.
