### ISSUE TITLE
Update chart.spacing doesn't reflow all elements

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#8190]
#### Expected behaviour
All elements (title, legend, plotting area) should reflow/resize when updating `chart.spacing` options.

#### Actual behaviour
On the first update, plotting area is resized, on the second update, title is updated, legend is updated only on window resize.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/LLx8fbw2/2/

**Comment by TorsteinHonsi** [comment]
Works well now with v7.2.1.
