### ISSUE TITLE
A way to plot multiple points in one category?

### ISSUE THREAD

**Issue by kmacayetano** [highcharts/highcharts#8194]
#### Sample data

Category = Value
A = 10, 20, 40
B = 20
C = 0, 10, 20, 30, 40, 20, 30, 60, 20, 10, 100

#### Expected behaviour
To plot multiple point within the tick of 1 category

#### Actual behaviour
The chart is plotting the same category multiple time based on how much value there is.

#### Question
Is it at all possible to plot inconsistent amount of value within the tick of their own unique categories?

**Comment by pawelfus** [comment]
Hi @kmacayetano 

Could you contact our support? See details: https://www.highcharts.com/support

We use github issues as bug reports, not questions. Thanks!
