### ISSUE TITLE
Incorrect county names & FIPS codes in the county shape file

### ISSUE THREAD

**Issue by JCHS-Riordan** [highcharts/highcharts#8195]
#### Expected behaviour
In the county shape file, would expect to see county names and FIPS codes that match current county names and FIPS codes as per the US Census Bureau.

#### Actual behaviour
Outdated county names and FIPS codes are still in use, resulting in a mismatch when using contemporary data with an updated list of FIPS codes and county names. The Census Bureau outlines major county changes [here](https://www.census.gov/geo/reference/county-changes.html).

The most visible examples are just two counties:
- Shannon County, SD (FIPS: 46-113)
--This became Oglala Lakota County, SD (FIPS: 46-102) on July 1, 2015
- Wade Hampton Census Area, AK (FIPS: 02-270)
--This became Kusilvak Census Area, AK (FIPS: 02-158) on July 1, 2015

I understand that there may be issues with deciding when to incorporate changes like these, but with these two counties in particular, this is a data issue due to the change in the FIPS codes that accompanied the name change. 

#### Live demo with steps to reproduce
The [project](https://codepen.io/JCHS-Riordan/full/YLKdEa/) I'm working on shows Shannon and Wade Hampton as blank counties as they have no data. Note: Shannon is near the southwest corner of South Dakota, and Wade Hampton is on the western edge of Alaska.

#### Product version
Highmaps v6.0.7

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @JCHS-Riordan 

Thank you for reporting about the problem.

The changes can be done manually in the map data files like in this demo:
http://jsfiddle.net/vwLudjdq/

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#23
