### ISSUE TITLE
Highstock navigator causes errors when adding series using chart.update() with oneToOne: true

### ISSUE THREAD

**Issue by gilmoreorless** [highcharts/highcharts#8196]
We have data coming in from an external API, with a variable number of series. Using base Highcharts, we can call `chart.update()` with the `oneToOne` option set to `true` to account for new series that come in from the API.

#### Expected behaviour

Calling the same method with the same option when using Highstock should produce the same result.

#### Actual behaviour

Highstock navigator throws errors in the console (`Cannot read property 'hoverSeries' of undefined`) and the chart fails to render.
Turning off the navigator makes the chart work as expected.

This also causes errors in the boost module when the navigator is enabled.

#### Live demo with steps to reproduce

http://jsfiddle.net/gilmoreorless/qzpzbhsm/3/ (adapted from the "Single line series" demo).

Click the "Add new series" button and watch the browser script console. Each click _should_ add a new series to the graph.
This is what happens instead:

1. 1st click doesn't change the chart at all.
2. 2nd click adds a series to the chart, which now shows 2 series instead of 3.
3. 3rd click (and all subsequent clicks) throws `Uncaught TypeError: Cannot read property 'hoverSeries' of undefined` and makes the original series disappear.

From my quick stepping through the code, it looks like the root cause is the navigator adding its own series to the main chart's `series` array. That array is then checked in the chart's `update()` method and the navigator series objects are merged with the incoming options.

#### Product version

Problem appears in at least Highstock 6.0.7 and 6.1.0, but I haven't tested other versions.

#### Affected browser(s)

All.

**Comment by pawelfus** [comment]
Hi @gilmoreorless

Thank you again for reporting another bug. You are right, the problem comes from series in navigator. 

**Workaround:**
Use `chart.addSeries()` and `series.remove()` (or `series.update()`) to maintain series on a chart.

**Comment by erkez** [comment]
Hi, I am facing the same issue, but with version 6.1.1.

I created a fiddle to demonstrate. Just click the update button to see `Cannot read property 'hoverSeries' of undefined`

https://jsfiddle.net/vmxgw4z2/4/

I noticed Highstocks mutates at least the `series` property by setting it to null. I wasn't expecting it to mutate the provided object, but even if we deep clone the config and try to apply the same update, the error still happens.

https://jsfiddle.net/vmxgw4z2/8/

It also doesn't render initially when Object.freeze is used.

**Comment by pawelfus** [comment]
Hi @erkez 

Thanks for creating examples! Let me reopen this issue.

*Internal note:*
Simplified demo: https://jsfiddle.net/BlackLabel/thrqwjc1/

**Comment by ppotaczek** [comment]
+1

**Comment by Denyllon** [comment]
+1

**Comment by Kyniu** [comment]
+1

**Comment by robinv** [comment]
+1

**Comment by yoninn** [comment]
+1

**Comment by levid** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Thanks for your patience! The issue comes not from using `oneToOne` per se, but from reusing the same options set, which Highcharts mutates internally. The *workaround* is to work on copies of the data: https://jsfiddle.net/highcharts/thrqwjc1/6/.

I'll investigate more on which mutations cause the issue, and whether it can be avoided.

**Comment by TorsteinHonsi** [comment]
#### Fix
The issue is now fixed in the master branch and will be official with the next release. See the demo with the fix applied: https://jsfiddle.net/highcharts/thrqwjc1/24/.

#### Workaround
Until then, a clean workaround is to add this snippet to your pages:

```js
Highcharts.setOptions({
	navigator: {
    	xAxis: {
        	isInternal: true
        },
    	yAxis: {
        	isInternal: true
        }
    }
});
```
View it live at https://jsfiddle.net/highcharts/thrqwjc1/23/
