### ISSUE TITLE
Boost module v6.1.0 has problems rendering zoomed scatter plots when useGPUTranslations is turned off

### ISSUE THREAD

**Issue by gilmoreorless** [highcharts/highcharts#8197]
#### Expected behaviour

Boost module v6.1.0 should render scatter plots in the same way as previous versions.

#### Actual behaviour

Zooming into a scatter plot rendered with the boost module enabled (but `useGPUTranslations` set to `false`) shows points that are meant to be hidden, pushed up against the right edge of the graph.

#### Live demo with steps to reproduce

https://jsfiddle.net/gilmoreorless/Lgyhugtf/11/ (adapted from the boost line chart demo).

1. Zoom in to an area of the chart.
2. Notice that any scatter points to the right of the zoomed area, which should be hidden, are now displaying as a blue line against the right edge of the chart.
3. Pan around the chart and notice that the blue line changes height depending on which points are hidden.

This only happens when `useGPUTranslations` is set to `false`.

![image](https://user-images.githubusercontent.com/159415/38910857-e58b46c6-430e-11e8-8724-e6893c9ff388.png)

#### Product version

Highcharts + boost module, v6.1.0. This doesn't happen with v6.0.7.

#### Affected browser(s)

All

**Comment by pawelfus** [comment]
Hi @gilmoreorless 

Thank you for reporting this bug!

*Internal note:*
It's a regression after 123aed700 @cvasseng

**Comment by cvasseng** [comment]
This has been fixed in the `bugfix/boost-scatter-culling` branch which is now [pending merge](https://github.com/highcharts/highcharts/pull/8962).

Demo of the fix: https://jsfiddle.net/Lgyhugtf/24/

The fix will be available in the next maintainance release.
