### ISSUE TITLE
Map collection: Norway, counties Sør-Trøndelag and Nord-Trøndelag were merged

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#8199]
#### Behaviour
The counties changed 1 January 2018, when Sør-Trøndelag and Nord-Trøndelag were merged into one, Trøndelag.

#### Live demo with steps to reproduce
See the counties around the middle of Norway:

Bad (current map collection with marked counties for merge): http://jsfiddle.net/5x3d46co/
Good: https://en.wikipedia.org/wiki/Counties_of_Norway#/media/File:Norway_counties.svg

#### Product version
Map collection 1.1.2

**Comment by PaulDalek** [comment]
Here is Norway map with merged both (Nord-Trøndelag and Sør-Trøndelag) regions into one (Trøndelag): http://jsfiddle.net/q824kye7/.

Internal note:
The map generated without any problems, although I am not sure about some of the properties. The most of them are taken from Sør-Trøndelag but some (e.g. code_hasc, postal, fips) are set intuitively as I could not find information about their values for a new region. Also, there is an encoding problem with some symbols (more specifically with a ø letter). It is turned to o. Changing to a different encoding when adding vector layer does not help.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#24
