### ISSUE TITLE
Highmaps with Google Spreadsheets doesn't work 

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#8202]
#### Actual behaviour

Demo from API documentation stuck on loading data from Google Spreadsheet.

#### Live demo with steps to reproduce
[http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/data-class-two-ranges/](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/data-class-two-ranges/)

#### Product version
above than v6.0.7

**Comment by pawelfus** [comment]
Related test: http://utils.highcharts.local/samples/#test/maps/demo/data-class-two-ranges

**Comment by stesi561** [comment]
Also impacted by this issue.

**Comment by kairusann** [comment]
Same here. I tried switching back to any version between 5.0.14 and 6.0.7. The map did show but colors and borderlines are all messed up. 
Test: https://jsfiddle.net/kz5gdqmp/

**Comment by TorsteinHonsi** [comment]
Duplicate of #8245, fixed in the master.

**Comment by DrSimEvans** [comment]
Hi there,
Just saw you had closed this report and checked to see if our Highmaps are now working. Unfortunately not, see example below:

https://s3-eu-west-1.amazonaws.com/cbhighcharts/Solar+PV+2016/solar_per_capita_addition_map.html

**Comment by sebastianbochan** [comment]
Hi @DrSimEvans 
Unfortunately I cannot run your demo (only logo is displayed).

The fix is available in the master branch here: 
- https://github.highcharts.com/maps/highmaps.js
- ttps://github.highcharts.com/maps/modules/data.js
and will be included in the next release.

**Comment by DrSimEvans** [comment]
Hi @sebastianbochan 
Thank you, using those sources instead I can get our maps to work.
Roughly how long until the next release?
Best,
Simon

**Comment by sebastianbochan** [comment]
We release new version each month or two, so the next version should be within few weeks.

**Comment by DrSimEvans** [comment]
Great, thank you @sebastianbochan

**Comment by stesi561** [comment]
Thanks heaps - shifting to the master resolved the issue - the fix appears to be working!
