### ISSUE TITLE
some css in _custom.scss not been processed by npm run build

### ISSUE THREAD

**Issue by Davidriquelme** [highcharts/highcharts#8207]
#### Expected behaviour
eliminate rounded corners and shadow. in dev and build deployment
![image](https://user-images.githubusercontent.com/12628676/38944943-918bedc6-430b-11e8-885b-5666ba7de938.png)

#### Actual behaviour
rounded corners are still present in build deployment but not in dev deployment. 
Rest of the css not related to highcharts in the same file custom.scss working just fine.

css: 
![image](https://user-images.githubusercontent.com/12628676/38945032-ba8903da-430b-11e8-857b-3e85f0c56023.png)

#### Product version
free version "vue2-highcharts": "^1.1.9"

#### Affected browser(s)
chrome, edge

**Comment by pawelfus** [comment]
Hi @Davidriquelme 

You should report this issue to authors of vue2-highcharts. We don't create class "vue-highcharts", neither styles for this class.
