### ISSUE TITLE
dataLabels.y offset doesn't work correctly with candlestick charts

### ISSUE THREAD

**Issue by ourarash** [highcharts/highcharts#8212]
#### Expected behaviour
datalabels to appear  on top of each candle

#### Actual behaviour
Seems like y offset functions randomly

#### Live demo with steps to reproduce
http://jsfiddle.net/802jmfnc/10/

#### Product version

Highstock, latest 

#### Affected browser(s)
All

I want to put datalabels on top of each candle (above data.high). It looks like the labels are normally at y=data.close value. Therefore, the offset for the top of the candle should be 

`-(data.high - data.close)`

However, in the above js fiddle this offset doesn't work for all candles. For example, the last one is far off.

As a side note, I tried to do this with annotations too (which worked very well), but the performance was too low and panning was very sluggish.

**Comment by pawelfus** [comment]
Hi @ourarash 

Thanks for reporting the issue. Value for `dataLabel.y` is in pixels, not value on a chart. We will make this clear in the docs. 

There is hidden option in candlestick, which can control where label should be rendered - `pointValKey`, demo: http://jsfiddle.net/802jmfnc/16/ (actually it determines which of o/h/l/c values should be represented as `point.y`, which is used to determine dataLabel position).
