### ISSUE TITLE
Grid lines of xAxis not covering whole grid in HighStock

### ISSUE THREAD

**Issue by slozier** [highcharts/highcharts#8220]
#### Expected behaviour
Grid lines of xAxis covering whole grid like it used to with Highstock 5.x.

#### Actual behaviour
Grid lines of xAxis only covering range of first yAxis.

#### Live demo with steps to reproduce
https://jsfiddle.net/e19vxjrs/

#### Product version
Highstock 6.x

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @slozier 

Thank you for reporting about the regression.

Last working version 5.0.10.
Regression caused by commit: https://github.com/highcharts/highcharts/commit/5dba091
