### ISSUE TITLE
Version 5.0.15 absence

### ISSUE THREAD

**Issue by nightty93** [highcharts/highcharts#8223]
#### Expected behaviour
Version 5.0.15 is contained in npm repository (https://registry.npmjs.org/highcharts/-/highcharts-5.0.15.tgz) and in list of releases (https://github.com/highcharts/highcharts/releases).

#### Actual behaviour
Version 5.0.15 is contained in npm repository and NOT contained in list of releases.

Why version 5.0.15 is missing in list of releases?
Thanks

**Comment by KacperMadej** [comment]
Hi @nightty93 

The version 5.0.15 is only published to NPM, and is not mentioned in the changelog.
It is a copy of 5.0.14 with a change of only one character in the package.json - https://github.com/highcharts/highcharts/commit/57cecb99d81daec59edd66034344c92e2add5f09

Related issue; https://github.com/highcharts/highcharts/issues/7115

**Comment by nightty93** [comment]
Ok, thanks for your answer
