### ISSUE TITLE
Using 'direction' css property in buttonTheme object of rangeSelector.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#8224]
#### Expected behaviour

After setting `direction: 'rtl'` inside of `rangeSelector.buttonTheme` object, button labels should be positioned in the other way.  The **x** value of the **text** element should be equal to the current **x** and its width. Here is the example:
[https://jsfiddle.net/nd591tuw/](https://jsfiddle.net/nd591tuw/)

#### Actual behaviour

If you set the `direction: 'rtl'` inside of `rangeSelector.buttonTheme` object, the `text-anchor` of all labels and their character positions are correct, but the text position is the same as before setting it.

#### Live demo with steps to reproduce
This is how it looks without calculation:
[https://jsfiddle.net/55jrak8d/](https://jsfiddle.net/55jrak8d/)

**Comment by KacperMadej** [comment]
Simpler workaround:

```
    buttonTheme: {
      direction: 'rtl',
      'text-anchor': 'end'
    },
```

https://jsfiddle.net/BlackLabel/nd591tuw/1/

What's the point of setting this property if without this text looks the same?
https://jsfiddle.net/BlackLabel/nd591tuw/2/

**Comment by Denyllon** [comment]
It isn't looks the same, because the text direction is incorrect when using Hebrew characters for example. Take a look on it:

_**Direction** property set to 'rtl':_
![screen shot 2018-04-23 at 16 41 50](https://user-images.githubusercontent.com/15111955/39133909-a09871e6-4715-11e8-8040-98420fc227d3.png)

_**Direction** and **text-anchor** commented_
![screen shot 2018-04-23 at 16 46 34](https://user-images.githubusercontent.com/15111955/39134268-8ae2f15e-4716-11e8-947b-2d1000b6db51.png)

Here is good reference article to better understand of this issue:
[https://www.w3.org/International/tutorials/svg-tiny-bidi/](https://www.w3.org/International/tutorials/svg-tiny-bidi/)
