### ISSUE TITLE
Highcharts not showing tooltip

### ISSUE THREAD

**Issue by Hraesvelg** [highcharts/highcharts#8225]
#### Expected behaviour

i use Highcharts in webextensions in content script and since the lastest version of firefox Highcharts return two error : 
1- the charts is not drawing, the console return : 

> TypeError: 'requestAnimationFrame' called on an object that does not implement interface Window.

I have found solution to fix but i have a second bug

2- the tooltip is not showing
console return : 

> Error: Permission denied to access property Symbol.toPrimitive

and i don't have solution for that do you know where come from the bug ?

#### Product version

Highcharts 6.0.7

#### Affected browser(s)

Firefox 59.0.2

**Comment by pawelfus** [comment]
Hi @Hraesvelg 

Is you webextension available somewhere, for example github? It would be great if we could use a demo for debugging.

In general `requestAnimationFrame` is required for animations, but we have fallback for browsers that don't support it. You can remove in webextension this method for Highcharts: `window.requestAnimationFrame = null` (before creating any chart).

Regarding `toPrimitive` error, we don't use this method in the core, so it's hard to say. Do you have more details about this bug?

**Comment by Hraesvelg** [comment]
hi, thanks for your fast response.

my webextension is : [Outiiil](https://github.com/Hraesvelg/Outiiil)
if you wan't to try and see the bug you need to adapt the code because the extension work in specific game website... 
(i suggest : create manifest, include highcharts with a basic JS content script... would you like to send a zip ? )

**Comment by sebastianbochan** [comment]
Hi @Hraesvelg,
I prepared a really simple extension for FF and does not cause the error. What is important, we need to disable animations.
I agree that the tootlip is missing. 
Tested: FF 59.0.2, macosx sierra (10.12.4).

Please test and let me know if errors still appears.


[_highcharts.zip](https://github.com/highcharts/highcharts/files/1941639/_highcharts.zip)

**Comment by pawelfus** [comment]
Just a guess: `Highcharts.dateFormat("%A %e %b", new Date(this.x));` -> second param in `dateFormat` should be number (timestamp), not a Date object. Simply try: `Highcharts.dateFormat("%A %e %b", this.x);`

**Comment by Hraesvelg** [comment]
ok it works ! thanks again ! 

solved for me !

**Comment by jon-a-nygaard** [comment]
Closing this issue as it appears to be solved. If this is not correct, please give a comment and we will consider reopening the issue.
