### ISSUE TITLE
Drill Down proper not work please help me

### ISSUE THREAD

**Issue by sairojalam** [highcharts/highcharts#8228]
<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="highChartStock.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/data.js"></script>
    <script src="https://code.highcharts.com/modules/drilldown.js"></script>
    <script src="https://code.highcharts.com/modules/pareto.js"></script>

</head>
<body>
    <form id="form1" runat="server">
        <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
    </form>

    <script type="text/javascript">
        Highcharts.chart('container', {
            chart: {
                renderTo: 'container',
                type: 'column'
            },
            title: {
                text: 'Restaurants Complaints'
            },
            xAxis: {
                // categories: ['Overpriced', 'Small portions', 'Wait time', 'Food is tasteless', 'No atmosphere', 'Not clean', 'Too noisy', 'Unfriendly staff']
                type: 'category',
            },
            yAxis: [{
                title: {
                    text: ''
                }
            }, {
                title: {
                    text: ''
                },
                minPadding: 0,
                maxPadding: 0,
                max: 100,
                min: 0,
                opposite: true,
                labels: {
                    format: "{value}%"
                }
            }],

            series: [{
                type: 'pareto',
                name: 'Pareto',
                yAxis: 1,
                zIndex: 10,
                baseSeries: 1
            }, {
                name: 'Complaints',
                type: 'column',
                zIndex: 2,
                data: [
                    {
                        "name": "Chrome",
                        "y": 62.74,
                    },
                    {
                        "name": "Firefox",
                        "y": 10.57,
                    },
                    {
                        "name": "Internet Explorer",
                        "y": 7.23,
                    },
                    {
                        "name": "Safari",
                        "y": 5.58,
                    },
                    {
                        "name": "Edge",
                        "y": 4.02,
                    },
                    {
                        "name": "Opera",
                        "y": 1.92,
                    },
                    {
                        "name": "Other",
                        "y": 7.62,
                        "drilldown": "Chrome"
                    }
                ]
            }, {
                name: 'Complaints',
                type: 'pie',
                zIndex: 2,
                data: [
                    {
                        "name": "Chrome",
                        "y": 62.74,
                    },
                    {
                        "name": "Firefox",
                        "y": 10.57,
                    },
                    {
                        "name": "Internet Explorer",
                        "y": 7.23,
                    },
                    {
                        "name": "Safari",
                        "y": 5.58,
                    },
                    {
                        "name": "Edge",
                        "y": 4.02,
                    },
                    {
                        "name": "Opera",
                        "y": 1.92,
                    },
                    {
                        "name": "Other",
                        "y": 7.62,
                        "drilldown": "Chrome1"
                    }
                ]
            }
            ],
            drilldown: {
                series: [
                    {
                        "name": "Chrome",
                        "id": "Chrome",
                        "data": [
                            [
                                "v65.0",
                                0.1
                            ],
                            [
                                "v64.0",
                                1.3
                            ],
                            [
                                "v63.0",
                                53.02
                            ],
                            [
                                "v62.0",
                                1.4
                            ],
                            [
                                "v61.0",
                                0.88
                            ],
                            [
                                "v60.0",
                                0.56
                            ],
                            [
                                "v59.0",
                                0.45
                            ],
                            [
                                "v58.0",
                                0.49
                            ],
                            [
                                "v57.0",
                                0.32
                            ],
                            [
                                "v56.0",
                                0.29
                            ],
                            [
                                "v55.0",
                                0.79
                            ],
                            [
                                "v54.0",
                                0.18
                            ],
                            [
                                "v51.0",
                                0.13
                            ],
                            [
                                "v49.0",
                                2.16
                            ],
                            [
                                "v48.0",
                                0.13
                            ],
                            [
                                "v47.0",
                                0.11
                            ],
                            [
                                "v43.0",
                                0.17
                            ],
                            [
                                "v29.0",
                                0.26
                            ]
                        ]
                    }, {
                        "name": "Chrome",
                        "id": "Chrome1",
                        type: 'pie',
                        "data": [
                            [
                                "v65.0",
                                0.1
                            ],
                            [
                                "v64.0",
                                1.3
                            ],
                            [
                                "v63.0",
                                53.02
                            ],
                            [
                                "v62.0",
                                1.4
                            ],
                            [
                                "v61.0",
                                0.88
                            ],
                            [
                                "v60.0",
                                0.56
                            ],
                            [
                                "v59.0",
                                0.45
                            ],
                            [
                                "v58.0",
                                0.49
                            ],
                            [
                                "v57.0",
                                0.32
                            ],
                            [
                                "v56.0",
                                0.29
                            ],
                            [
                                "v55.0",
                                0.79
                            ],
                            [
                                "v54.0",
                                0.18
                            ],
                            [
                                "v51.0",
                                0.13
                            ],
                            [
                                "v49.0",
                                2.16
                            ],
                            [
                                "v48.0",
                                0.13
                            ],
                            [
                                "v47.0",
                                0.11
                            ],
                            [
                                "v43.0",
                                0.17
                            ],
                            [
                                "v29.0",
                                0.26
                            ]
                        ]
                    }
                ]
            }
        });

    </script>
</body>
</html>

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
