### ISSUE TITLE
Highcharts.Net wrapper YAxisPlotBands.Thickness and SolidgaugeSeriesData.InnerRadius should be string type

### ISSUE THREAD

**Issue by schutze** [highcharts/highcharts#8229]
#### Expected behaviour

`YAxisPlotBands.Thickness` and `SolidgaugeSeriesData.InnerRadius` should both be `String` types.  This was the case in older releases but was erroneously changed at some point, maybe in the 6.0.7 release.

#### Actual behaviour

`YAxisPlotBands.Thickness` and `SolidgaugeSeriesData.InnerRadius` were changed to `Double `when they were `String`. These must be changed back to `String` because `Double` does not support percent values as described in the API documentation ([Thickness](https://api.highcharts.com/highcharts/yAxis.plotBands.thickness), [InnerRadius](https://api.highcharts.com/highcharts/series.solidgauge.data.innerRadius)).

#### Live demo with steps to reproduce

Not applicable

#### Product version
Highcharts.NET for Highcharts v6.0.7.x??
Highcharts.NET for Highcharts v6.1.0

#### Affected browser(s)

Not applicable

**Comment by pawelfus** [comment]
Hi @schutze 

Thanks for reporting this issue!

*Internal note:*
It looks like order in jsdoc doclet (which defines types) has changed (?). The first type in a list is taken as a default type. Right now we we are in the tests stage for multi-types for this wrapper.
