### ISSUE TITLE
xAxis' labels are messed up since v6.0.5 and worsed since v6.0.7

### ISSUE THREAD

**Issue by ptijul** [highcharts/highcharts#8234]
#### Expected behaviour
The x labels should wrapped (as it was until v6.0.4)

#### Actual behaviour
The x labels are cut off (since v6.0.5) and completly messed up and unreadable since v6.0.7. 
Still not working neither with latest version (6.1.0) nor master branch.

Note that the problem appears with the demo link (see below) only from v6.0.7 whereas in my application the text messed up from v.6.0.5 : I don't have ellipsis shown but text messed up. My application contains a drill down with 3 main series with 5 categories (1st level) resulting in 12 categories (2nd level) at max.

#### Live demo with steps to reproduce
Use the [demo](http://jsfiddle.net/Lxgqogn7/1/)  :
1. Click on the serie "Animals"
2. Reproduce step 1 by changing the Highchart version in JS section.

Please change the version below and play with :

- 6.0.4 (works perfectly !!)
- 6.0.5 (some labels are cut off (ellispsis) and some labels wrap....I would prefer to keep the wrap)
- 6.0.7 and later (overlapped labels)

```
<script src="https://code.highcharts.com/6.0.7/highcharts.js"></script>
<script src="https://code.highcharts.com/6.0.7/modules/drilldown.js"></script>
```

#### Product version
Highcharts : 6.0.5, 6.0.7

#### Affected browser(s)
All (tested under Chrome 66.0.3359.117 and FF 59.0.2)

**Comment by ptijul** [comment]
Hi @pawelfus 

Oups sorry I've pasted a wrong link. Here it is : http://jsfiddle.net/Lxgqogn7/1/
(I've updated the link in my original post). 

Here is what you should see with v6.0.7 and above : 
![image](https://user-images.githubusercontent.com/8395615/39245967-7fa537cc-4895-11e8-9e1e-fc7940688f35.png)

**Comment by pawelfus** [comment]
Thanks for the updated demo @ptijul - you are right, it looks broken. 

*Internal note:*
Bisect points to:
- 08b85659e - instead of wrapping we have elipssis 
- 5a2adf0be - instead of elipssis we have overlapped labels

**Comment by ptijul** [comment]
You're welcome, thanks for your quick reply and for your research to find the commits responsible of the regression.
I've upgraded to 6.0.4 for now.

**Comment by TorsteinHonsi** [comment]
We need a fixed with in order to reliably reproduce: http://jsfiddle.net/Lxgqogn7/3/
