### ISSUE TITLE
Line and Spline charts' drawn paths are clipped at the bottom

### ISSUE THREAD

**Issue by joedski** [highcharts/highcharts#8235]
#### Expected behaviour

Line and Spline charts' drawn paths do not get clipped.

#### Actual behaviour

Line and Spline charts' drawn paths are clipped at the bottom, removing half of the drawn width.

#### Live demo with steps to reproduce

https://jsfiddle.net/Lcrkb7ov/1/

#### Product version

Current version of Highcharts as of 2018-04-24 (version 6.1.0)

#### Affected browser(s)

- Chrome 65.0.3325.181
- Firefox 59.0.2
- Safari 11.1

I don't think I've seen this reported yet, but my apologies if this already has been.  It's a minor issue, but one I ran into while creating a small sparkline type chart.

**Comment by pawelfus** [comment]
Hi @joedski 

Thanks for reporting the issue. You can set `series.clip` to prevent this, demo: https://jsfiddle.net/BlackLabel/Lcrkb7ov/2/

It looks like `series.clip` is not available in our docs (only for a pie chart: https://api.highcharts.com/highcharts/series.pie.clip and other extended series). We will add this.
