### ISSUE TITLE
Regression: Data module's parsed callback is not called on loading Google Spreadsheets.

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#8245]
#### Live demo with steps to reproduce
http://jsfiddle.net/highcharts/ztkkd8Lv/

#### Product version
6.1.0

**Comment by DrSimEvans** [comment]
Hi Torstein, cross-posting in case you don't see my comment on the other thread

Just saw you had closed this report and checked to see if our Highmaps are now working. Unfortunately not, see example below:

https://s3-eu-west-1.amazonaws.com/cbhighcharts/Solar+PV+2016/solar_per_capita_addition_map.html

**Comment by sebastianbochan** [comment]
Hi @DrSimEvans 
Unfortunately I cannot run your demo (only logo is displayed).

The fix is available in the master branch here: 
- https://github.highcharts.com/maps/highmaps.js
- ttps://github.highcharts.com/maps/modules/data.js
and will be included in the next release.
