### ISSUE TITLE
Areaspline stacking - gaps between stacked series

### ISSUE THREAD

**Issue by d6teo** [highcharts/highcharts#8246]
Hi, we have problems in areaspline charts with stacking, multiple series, and each series containing both positive/negative values. About a year ago we upgraded from Highcharts v2 to v4 and since stacking functionality was different, we had to make some changes to make the functionality as it was previously, according to a proposal by @TorsteinHonsi (see [related issue)](https://github.com/highcharts/highcharts/issues/5671) The problem is that in some cases there are gaps between the stacked series (see fiddle and image) 
![image](https://user-images.githubusercontent.com/22095087/39359151-7592f69c-4a21-11e8-82a1-25aa57e0438f.png)
Any ideas/workarounds ?

#### Expected behaviour
There should be no gaps between stacked series

#### Actual behaviour
There are gaps between stacked series

#### Live demo with steps to reproduce

http://jsfiddle.net/06xre8ve/
#### Product version

Highcharts 4.2.6, Highstock 4.2.6
#### Affected browser(s)
Cross-browser Issue

**Comment by pawelfus** [comment]
Hi @d6teo 

My apologies for a late response! Is this a duplicate of #5671 ? I mean isn't the issue the same, but with different dataset?

**Comment by d6teo** [comment]
Hi, i don't think this is a duplicate of [#5671](https://github.com/highcharts/highcharts/issues/5671). I have used the prototype overrides indicated in the [demo fiddle](http://jsfiddle.net/06xre8ve/) to resolve that. The problem here is that there are 'gaps' between the stacked series (see posted image)
Thanks
