### ISSUE TITLE
Talkback is reading tagname (like <h4> as header label 4 ).

### ISSUE THREAD

**Issue by saroj08** [highcharts/highcharts#8247]
#### Expected behaviour
Talkback or Narrator should not read HTMLelements like <h4>,it should only read the contents of the elements.

#### Actual behaviour
I am not  finding any solution to fix highchart related bug where talkback is reading HTMLelement (like <h4> as header label 4 ).

#### Live demo with steps to reproduce

Link for the BUG: https://1drv.ms/v/s!At1ZjscrbmUicVyWHBoJeLYrLnU
@oysteinmoseng 
[RE Regarding Highchart Bug.txt](https://github.com/highcharts/highcharts/files/1955038/RE.Regarding.Highchart.Bug.txt)

#### Product version

Highchart version-V6.0.4
#### Affected browser(s)
IE(internet Explorer) Narrator and Android [TalkBack]

**Comment by oysteinmoseng** [comment]
Closing this and following up by email.
