### ISSUE TITLE
Problem with autorotated xAxis labels and columns position after point.update on added series

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#8248]
#### Expected behaviour
The columns should keep the right position, the labels should remain unchanged.

#### Actual behaviour
The columns rise and do not stand on the axis, the labels are rotated.

![screen shot 2018-04-27 at 14 30 10](https://user-images.githubusercontent.com/22988131/39362670-8f22a4c6-4a27-11e8-8895-96de4f98c6ee.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/h76emxde/

Click on 'Change color' button.

#### Product version
Highcharts v6.1.0

#### Affected browser(s)
All

**Comment by newlukai** [comment]
Would be great to have this in 5.x too.
