### ISSUE TITLE
Axis title is not removed after linked series is hidden

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#8249]
#### Expected behaviour
Both axis and axis title are removed when hiding the linked series by clicking in legend

#### Actual behaviour
Axis is removed but axis title remains in char

#### Live demo with steps to reproduce
Can be reproduced in https://jsfiddle.net/alvarezg/e9ucotby/
* Click on any series in the legend, the legend will be hidden, so will the axis, but the title stays

Would appreciate if a workaround is suggested for this scenario but in css styled mode

**Comment by alvarezguille** [comment]
This is probably not a bug, just noticed that setting `showEmpty: false` makes the expected behavior.
It's still a bit surprising that by default hiding the series leaves the title hanging there

**Comment by pawelfus** [comment]
Hi @alvarezguille 

Thanks for reporting the issue! You are right, `Axis.showEmpty` option is responsible for changing that. `showEmpty` was not available in the first releases of Highcharts, so probably when option was added it was decided to keep backward compatibility and not breaking already created charts.
