### ISSUE TITLE
Export server with plotBackgroundImage absolute public url not exporting

### ISSUE THREAD

**Issue by karlbarry** [highcharts/highcharts#8250]
#### Expected behaviour
plotBackgroundImage should export via self hosted export server using phantomjs java

#### Actual behaviour
No plotBackgrounImage was exported on the output chart

#### Live demo with steps to reproduce
Using the export server to test http://export.highcharts.com/ 

Copy the chart json config from example http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/plotbackgroundimage/

This uses a public absolute reference to an image hosted on highcharts.com

Also tried a base64 encoded string which also did not export via the export server

#### Product version
Latest version

#### Affected browser(s)
Test on Chrome Version 66.0.3359.117 (Official Build) (64-bit)

**Comment by karlbarry** [comment]
Just to note this worked June last year.

**Comment by karlbarry** [comment]
Just to note this worked June last year.

**Comment by pawelfus** [comment]
Hi @karlbarry 

Thank you for reporting this bug. 

Simplified demo: https://jsfiddle.net/BlackLabel/rzb0j1v9/5/
@cvasseng
