### ISSUE TITLE
Highcharts init doesn't support class based options

### ISSUE THREAD

**Issue by ciarancourtney** [highcharts/highcharts#8251]
#### Expected behaviour
 When building up options as typed ES6 classes (instead of the recommended object literals as per docs):

    export class Options {
        chart: Chart = new Chart();
        legend: Legend = new Legend();
        title: Title = new Title();
}

Since v5.0.11 anything you set will not get merged correctly with `defaultOptions` due to [this](https://github.com/highcharts/highcharts/blob/84328e1cddd1fc390fe71eb219ff7bf2c98ca4c7/js/parts/Utilities.js#L465) line

Is there any good reason why class is not allowed? Using typed classes makes building up the options dynamically a much nicer experience, it would be a shame to disallow this approach.

#### Actual behaviour

Options post-merge should contain all defaults not set by user.

#### Product version

Highcharts >5.0.10

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @ciarancourtney 

Thank you for reporting the issue. It's a result of #6046 fix.

FYI @jon-a-nygaard
