### ISSUE TITLE
Highchart more js require two time initialize for  inverse transformation to polar 

### ISSUE THREAD

**Issue by matt212** [highcharts/highcharts#8252]
Hi, 
#### Expected behaviour
from 3d highchart to polar inversion in chart.update feature  **not working as expected** in first initialization
i.e first click
#### Actual behaviour
from 3d highchart to polar inversion in chart.update feature  **working as expected** in  second initialization
i.e second click

#### Please find below gif for issue in question
![ice_video_20180427-215011](https://user-images.githubusercontent.com/1698139/39373496-69d834ae-4a65-11e8-9947-2933984c110f.gif)

#### Live demo with steps to reproduce
click button named polar to invert chart to polar chart
https://jsfiddle.net/bilbobaggins/u78pyd5q/3/
#### Product version

highchart
highchart-3d
highchart-more

 Highcharts JS v6.1.0 (2018-04-13)
#### Affected browser(s)
chrome Version 66.0.3359.117 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Hi @matt212 

Thank you for reporting this bug. 

**Workaround:**
Calculate missing option:

Demo: https://jsfiddle.net/BlackLabel/u78pyd5q/5/

Snippet: 
```javascript
(function(H) {
  H.addEvent(H.Series, 'afterRender', function() {
    var chart = this.chart;
    if (chart.polar && chart.pane && chart.pane[0]) {
      chart.pane[0].updateCenter(this.xAxis);
      chart.pane[0].updateCenter(this.yAxis);
    }
  });
})(Highcharts);
```

*Internal note:*
Polar's pane does not update center position of axes after update.

**Comment by pawelfus** [comment]
Let's keep this open until we fix this in the core.

**Comment by matt212** [comment]
@pawelfus  
acknowledged :+1:  !
