### ISSUE TITLE
Click event doesn't always trigger  on iphone

### ISSUE THREAD

**Issue by ourarash** [highcharts/highcharts#8253]
#### Expected behaviour
Click event on chart to always trigger as soon as you touch the chart

#### Actual behaviour
On iphone, when you touch the chart, sometimes (specially the first time after refreshing the page) the  click event doesn't get triggered

#### Live demo with steps to reproduce
http://jsfiddle.net/kj7vqzr7/

#### Product version

Highstock - latest

#### Affected browser(s)
Safari

Steps to reproduce: visit the jsfiddle link above on iphone, and touch somewhere on the chart where there is no line or datapoint. You can see the crosshairs moving there, but the touch event doesn't get triggered! Looks like this happens the first time when you refresh the page, but I have seen it happening randomly even after the first touch. It's odd that the crosshair actually gets the touch event, but the callback function doesn't get called.

 I'm using iPhone 6, version 11.3.

This is not the case on Android, and it works as expected for me.

This creates confusion for the user because they have touched the screen but the expected event didn't happen.

**Comment by pawelfus** [comment]
Hi @ourarash 

Thank you for reporting the issue. Is this a duplicate of #6817 ? I don't have access to iOS device at this moment, but setting `series.kdNow = true` should resolve the issue. Could you confirm?

**Comment by ourarash** [comment]
I can confirm that this is the same issue and the workaround worked for me. Thanks!
