### ISSUE TITLE
PASSING LIVE DATA TO SPLINE CHART FRO MQTT SERVER EVERY SECOND

### ISSUE THREAD

**Issue by gouthamtj** [highcharts/highcharts#8255]
#### Expected behaviour
Component should not re-render when data from mqtt server passed as props to Highchart component. Live data should get rendered like heartbeat chart but with multi lines.

#### Actual behaviour
Component is re-rendering, every time the new data is passed 

#### Live demo with steps to reproduce
Sample Data from mqtt : 
x value is TimeStamp and y the data point
[ {"data":[[1524903290174,50],[1524903295176,55],[1524903300182,0],[1524903305185,5]]}]

Code passed from index to highchart.
```
import Chart from 'components/HighCharts';

import { Connector } from 'mqtt-react';
import {subscribe} from 'mqtt-react';

const MessageContainer = subscribe({topic: 'system_monitor'})(Chart);
export class HomePage extends React.PureComponent {
render() {
   return (
      <article>
        <Helmet>
          <title>Home Page</title>
          <meta name="description" content="A React.js Boilerplate application homepage" />
        </Helmet>
        <div>
        <Connector mqttProps="ws://localhost:1884/">
         <MessageContainer/>
         </Connector>
        </div>
      </article>
    );
  }

}
```

#### Product version
<!--- Highcharts, Latest Version

#### Affected browser(s)
Google Chrome, Safari and others

**Comment by pawelfus** [comment]
Hi @gouthamtj 

This is our bug tracker, not a support channel. Please contact our support: https://www.highcharts.com/support

PS: You probably have problem with your Chart component (which renders whole chart, with container, from scratch, not just updating data and series).
