### ISSUE TITLE
Candlestick Details in separated block instead of tooltip

### ISSUE THREAD

**Issue by Insider77** [highcharts/highcharts#8257]
Hi, 
is it possible to show candlestick data (Open, High, Low, Close) in separated block, instead of showing it inside a tooltip, like in the screenshot below?

Thanks

![2018-04-30 1 36 48](https://user-images.githubusercontent.com/5548059/39411669-4d5cbfbc-4c17-11e8-90d2-72e2ca3e2678.png)

**Comment by pawelfus** [comment]
Hi @Insider77 

Do you mean [`tooltip.positioner`](https://api.highcharts.com/highstock/tooltip.positioner), to place tooltip in top left corner? It works for tooltip that has not `split` option.

**Comment by Insider77** [comment]
Oh, thank you so much! That's exactly what I need.
