### ISSUE TITLE
Images for polar xAxis labels are not correctly aligned on first rendering

### ISSUE THREAD

**Issue by jonathan-armond-mpf** [highcharts/highcharts#8258]
#### Expected behaviour
Images used as labels with `formatter` property should be offset from polar x axis.

<img width="421" alt="second_run" src="https://user-images.githubusercontent.com/33230963/39419901-e8c1c2f8-4c59-11e8-9a5b-ce11b5325bd8.png">

#### Actual behaviour

Images on left side overlap graph, only for **first** rendering. After refresh the correct image above is rendered.

<img width="394" alt="first_run" src="https://user-images.githubusercontent.com/33230963/39419878-c87bd574-4c59-11e8-9346-9fa1dcc959f6.png">
 
#### Live demo with steps to reproduce
[jsfiddle](https://jsfiddle.net/qsscbah2/)

1. Open jsfiddle example. Plot is incorrect.
2. Press Run to rerender. Plot is correct.

#### Product version
Highcharts JS v6.1.0 (2018-04-13)

#### Affected browser(s)
Chrome Mac 65.0.3325.181

**Comment by pawelfus** [comment]
Hi @jonathan-armond-mpf 

This is caused by missing `height` param in the `<img>` tag. When it's set, it works fine: https://jsfiddle.net/BlackLabel/qsscbah2/3/

**Comment by jonathan-armond-mpf** [comment]
I think you mean the missing `width`, but you are right it works now, thanks!
