### ISSUE TITLE
Stacks label misplaced on my bar charts

### ISSUE THREAD

**Issue by Glenfiddish** [highcharts/highcharts#8269]
#### Expected behaviour
Stacks label show in correct place

#### Actual behaviour
Stacks label misplaced

#### Live demo with steps to reproduce
http://jsfiddle.net/EdwinLai927/evfkzs0g/7/

#### Product version
V 6.1.0

#### Affected browser(s)
All

**Comment by cosycode** [comment]
Thank you for the report. See #8269 for more information regarding this issue.
