### ISSUE TITLE
HighStock loaded in an app with Content Security Policy(CSP) enabled and inside an iframe, CSV export fails

### ISSUE THREAD

**Issue by ff-sgupta** [highcharts/highcharts#8270]
#### Expected behaviour
CSV export should work

#### Actual behaviour
In Browser console, I get an error "Content Security Policy: The page’s settings blocked the loading of a resource at data:text/csv,%EF%BB%BF%22DateTime%22%2C... (“frame-src”)."

#### Live demo with steps to reproduce
1. Create a html file and paste following code.

```
<html>
<head>
<meta http-equiv="Content-Security-Policy" content="default-src https:; frame-src https: http:; object-src 'none';style-src 'self' https: http: ;script-src 'self' https: http: 'unsafe-eval' 'unsafe-inline';">
</head>

<body>
<iframe src="https://www.highcharts.com/stock/demo/spline" height="600px" width="1000px"></iframe>
</body>
</html>

```
2. Open the file in Firefox browser (any browser which supports CSP). Click on Download CSV and observe the error in console

#### Product version
Highstock 6.1.0

#### Affected browser(s)
Firefox 59.0.2 on Ubuntu. Should be reproducible on any browser with CSP enabled

![csp_error](https://user-images.githubusercontent.com/644292/39563698-deef69b6-4ece-11e8-8f1d-80441d203244.png)
[highcharts_csp.txt](https://github.com/highcharts/highcharts/files/1969886/highcharts_csp.txt)

**Comment by ff-cviradiya** [comment]
Here is the JSFiddle link where the same issue can be seen 

http://jsfiddle.net/6mSuK/14958/

**Comment by pawelfus** [comment]
Thank you for reporting the issue.

@oysteinmoseng it looks like we need to change this, see Mozilla statement: https://bugzilla.mozilla.org/show_bug.cgi?id=1365502

**Comment by ff-sgupta** [comment]
@pawelfus @oysteinmoseng Is this being considered to be fixed? 
Can we please get a timeline for a fix as this is impacting our highcharts integration.
Thank you

**Comment by oysteinmoseng** [comment]
Well, there isn't much we can really do here if the CSP is set very strictly. We can use Blob objects, but I believe those are also blocked by default. We can use an external export server and send the CSV data there, like we do for image exporting, but that is about it I think.

Is there no way you can allow data URI sources for the Highcharts iframes specifically ([example](http://jsfiddle.net/6up7psnj/))? That would obviously be the easiest fix.

**Comment by ff-sgupta** [comment]
Unfortunately there's no way we can update the CSP policy where we are integrating high-charts. How do we move to export export server?

**Comment by oysteinmoseng** [comment]
I see. Let's see what we can do.

@cvasseng Is there any way we can leverage our existing export server to relay CSV files? We also have XLS export and should probably think of that too while we are at it.

**Comment by TorsteinHonsi** [comment]
It would probably be equivalent to the SVG export, where we basically create the SVG on the client side and posts it to the export server which adds headers and returns it as a downloadable file.

**Comment by cvasseng** [comment]
I wonder if this would make more sense as a separate data export server? It doesn't really require phantom and such to work, and having it be a separate thing would not cause more bloat in the export server.

**Comment by TorsteinHonsi** [comment]
Not sure... It is dead simple, plus we already have one case by serving the SVG, which also does not require PhantomJS. I think it would be easier for all to have it in one server. Especially for implementers installing their own export server, so they don't have to set up and configure two instances.

**Comment by ff-sgupta** [comment]
Appreciate the response of this issue. Is there a timeline by when we can expect a fix for this? Accordingly we need to plan for this issue on our side.

Thank you

**Comment by oysteinmoseng** [comment]
@ff-skundalkar We are working on a solution, and should have something ready by the end of next week. Apologies for the delay, but there are several public holidays these days, and we are a bit short on staff.

**Comment by KacperMadej** [comment]
@cvasseng 
Do you have any official info that we could share here?

**Comment by oysteinmoseng** [comment]
@ff-skundalkar CSV support has been added to a separate branch of the export server for now. We might end up pulling it into the official server as well eventually.

For now, in order to use this feature, you will need to install your own installation of our export server. This is very straightforward, and the docs can be found in the repo readme: https://github.com/highcharts/node-export-server/tree/feature/data-export. Make sure you use the `feature/data-export` branch when you install, or CSV export will not be supported.

To use this export server, see http://jsfiddle.net/wgphp2jr/1/. The code in this jsFiddle demo overrides the default CSV export function, and sends a POST request to `/dataexp` on a custom server instead. Replace this URL `http://localhost:7801` with the URL to your server installation.

Should you run into any issues with this, please contact us through `support@highcharts.com`, and we can help you with any issues specific to your use case.

**Comment by arberosmani** [comment]
@oysteinmoseng 

> [...] Well, there isn't much we can really do here if the CSP is set very strictly. We can use Blob objects, but I believe those are also blocked by default. [...]

Blob url's are blocked as well. However there is a possible workaround to this issue, that can be applied by the parent client that integrates the iframe. I made created a demo application showing this workaround:

https://arberosmani.github.io/workaround-csp-frame-src-blocked-on-firefox/

You can find more details on the Github [source page](https://github.com/arberosmani/workaround-csp-frame-src-blocked-on-firefox).
