### ISSUE TITLE
Display red crosses instead of gaps for missing values

### ISSUE THREAD

**Issue by ali-master** [highcharts/highcharts#8272]
#### Expected behaviour
There is a chart with 3 series and I expect to draw the red crosses on x-Axis when the series data has missing values, like this image: [image](https://pasteboard.co/Hjrsaob.png)
#### Actual behaviour
My chart with red crosses instead of using gaps for showing missing values by this plugin [Highchart plugin](https://gist.github.com/ali-master/9138f02dfdf29d8d5875e7a3d2d88ad5)
image: [My chart](https://pasteboard.co/HjrtekB.png)
#### Live demo with steps to reproduce

I don't have a demo
#### Product version

Highchats(Line, Area, Histogram)
#### Affected browser(s)
Chrome v66

Please help me because and I don't understand how can I do it.

**Comment by pawelfus** [comment]
Hi @ali-master 

Could you contact our support? This is our bug tracker. Thanks!

Support info: https://www.highcharts.com/support

**Comment by ali-master** [comment]
Making an ask in your forum is very difficult and it has complex stages. Can you help me here?

**Comment by pawelfus** [comment]
You can contact us directly, by email. We use github issues as bug reports, not support questions.
