### ISSUE TITLE
Highcharts heatmap bubbles exported CSV contains empty column

### ISSUE THREAD

**Issue by blaise-io** [highcharts/highcharts#8275]
#### Expected behaviour

CSV only contains columns for series with data

#### Actual behaviour

CSV contains an empty column

#### Live demo with steps to reproduce

 - Go to https://jsfiddle.net/h2Lbd8ug/  (same as https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/map-bubble/, but with included export-data.js)
 - Click hamburger menu
 - Click Download CSV

#### Product version

Latest stable

#### Affected browser(s)

All

**Comment by pawelfus** [comment]
Hi @blaise-io 

Thank you for reporting the issue. It happens not only with CSV, but when displaying table too: https://jsfiddle.net/BlackLabel/h2Lbd8ug/1/

**Comment by blaise-io** [comment]
Issue is still present in latest.

**Comment by pawelfus** [comment]
Thanks! ~1 year later I'm no longer convinced if this is a bug per se. On the chart we have two series: countries and population. Countries has no data at all, so all cells for that series are empty. 

Now it's possible to control which series are rendered in table/CSV export using [`series.includeInDataExport`](https://api.highcharts.com/highmaps/series.map.includeInDataExport): https://jsfiddle.net/BlackLabel/mn0orkx3/1/
