### ISSUE TITLE
Incorrect halo z-index in styled Highcharts

### ISSUE THREAD

**Issue by proteamer** [highcharts/highcharts#8276]
Hi, I'm not sure that it is bug or not but I сould not setup _Highcharts_ in styled mode to get expected behaviour:

#### Expected behaviour
Marker `halo` appears behind the point marker:

<img width="392" alt="screen shot 2018-05-03 at 17 00 14" src="https://user-images.githubusercontent.com/1376014/39581283-dfac815c-4ef3-11e8-800c-8c4959367a09.png">

#### Actual behaviour

Marker `halo` overlaps the point marker:
<img width="381" alt="screen shot 2018-05-03 at 17 13 28" src="https://user-images.githubusercontent.com/1376014/39581929-5eb848a4-4ef5-11e8-95ee-6d9184df069b.png">

#### Live demo with steps to reproduce
The issue is only reproduced in styled mode: https://jsfiddle.net/unlimit/mekcvgxx/

#### Product version
Styled highcharts v6.1.0

#### Affected browser(s)
Google Chrome v66, Safari v11.1, etc.

**Comment by pawelfus** [comment]
Hi @proteamer 

Thank you for reporting this bug. I think you are right, it's wrong zIndex which is applied only in classic version, but should be available in both classic and and styled modes.

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/mekcvgxx/5/
Snippet: 
```javascript
  plotOptions: {
    series: {
      point: {
        events: {
          mouseOver: function() {
            if (this.series.halo) {
              this.series.halo.attr({
                // Apply zIndex manually
                zIndex: -1
              });
            }
          }
        }
      }
    }
  },
```

*Internal note:*
Related lines:

https://github.com/highcharts/highcharts/blob/4cb1efc5810ee99581821c3dff75c7f13b9a9cda/js/parts/Interaction.js#L828-L834
