### ISSUE TITLE
Missing top bar of rotated funnel chart if a series spans from the main part to the neck

### ISSUE THREAD

**Issue by DK-Unit4** [highcharts/highcharts#8277]
#### Expected behaviour
The top bar is visble

#### Actual behaviour
The top part is missing on the rotated funnel chart if a series spans from main part to the neck

#### Live demo with steps to reproduce
https://jsfiddle.net/Kumlander/Ljtsuhtp/

#### Product version
5.14, latest

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @DK-Unit4 

Thank you for reporting this bug.
