### ISSUE TITLE
3D column wrong display order with large chart width

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#8280]
#### Expected behaviour
The display order should look like in the case of smaller chart widths.

![screen shot 2018-05-04 at 12 03 40](https://user-images.githubusercontent.com/22988131/39623189-1a518a40-4f95-11e8-82a8-d58c06b51848.png)

#### Actual behaviour
In my case, if chart width is more than 1223 and the y value is 0, the display order is wrong.

![screen shot 2018-05-04 at 12 03 19](https://user-images.githubusercontent.com/22988131/39623165-0993fa1c-4f95-11e8-99f5-1aaea37b76f6.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8co8yjb9/

#### Product version
Highcharts, 6.1.0

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Another issue with 3d columns: https://jsfiddle.net/BlackLabel/8co8yjb9/10/
- top side not present for animation
- wrong z index order
