### ISSUE TITLE
Options of 6.1.0 are missing in the old format json dump

### ISSUE THREAD

**Issue by suganya-suvadi** [highcharts/highcharts#8281]
I could not find the new options released in 6.1.0 in the options dump (old format) at https://api.highcharts.com/highcharts/option/dump.json; the latest I could find was an option from 6.0.3.

I did find an older thread on this around the time version 6 (and the new tree format) were released - https://github.com/highcharts/highcharts/issues/7227#issuecomment-334172297

Could you please confirm if 6.0.4 is officially the version after which the old dump will not be updated? Or can we still expect this dump to keep up with the newer releases?

Thanks in advance!

**Comment by suganya-suvadi** [comment]
Hello, any update here?

**Comment by pawelfus** [comment]
Hi @suganya-suvadi 

Thank you for reporting missing fields in the old dump.json. @cvasseng, @jon-a-nygaard - maybe scripts didn't update this file on release?

**Comment by jon-a-nygaard** [comment]
Hi @suganya-suvadi,

Apologies for the very late reply.

The dump.json has been located at https://api.highcharts.com/highcharts/dump.json since v6.0.0.

I will update the layout of api.highcharts.com with a link to the old format, so that it can be easier found.
Will also make sure we add a redirect from https://api.highcharts.com/highcharts/option/dump.json to its new location.

**Comment by suganya-suvadi** [comment]
@jon-a-nygaard Thanks for the detailed reponse! 

I assume Highstock and Highmaps options are aslo present in highstock/dump.json and highmaps/dump.json. I'll pick the options from the url in the last update.

**Comment by jon-a-nygaard** [comment]
The api has now been updated with the previously mentioned changes.
I consider this issue solved and will close it, should this be incorrect please give us a comment and we will consider reopening it.

**Comment by suganya-suvadi** [comment]
@jon-a-nygaard Thanks; I have one last question though. The size of the file now (6.1.0) has decreased compared to the size of the options for 6.0.2.

Can you confirm if this is expected?

Other than that. this is good to close!
