### ISSUE TITLE
marker's position don't follow the series when highstock chart is scrolling

### ISSUE THREAD

**Issue by sylaince** [highcharts/highcharts#8284]
#### Expected behaviour
create a highstock chart with two serieses, when mouse over marker and tooltip will display, don't move the mouse and all the markers are following the movement of the series when chart is scrolling

#### Actual behaviour
one of the markers didn't follow the movement of its series
screenshot: [https://i.stack.imgur.com/L8FJZ.jpg](url)

#### Live demo with steps to reproduce
https://jsfiddle.net/sylaince/fz7cv853/3/
put your mouse over the top right or bottom right area of the chart would help reproducte the problem.

#### Product version
Highstock-6.1.0

#### Affected browser(s)
Chrome 66.0.3359.139

**Comment by pawelfus** [comment]
Hi @sylaince 

Thank you for reporting this bug. You are right, both markers should follow last hovered point, the same way it works for just one series: https://jsfiddle.net/BlackLabel/fz7cv853/6/

**Workaround:**
Update states by plugin: https://jsfiddle.net/BlackLabel/fz7cv853/11/

Plugin:
```javascript
(function(H) {
  H.wrap(H.Pointer.prototype, 'reset', function(proceed, allowMove, delay) {

    proceed.call(this, Array.prototype.slice.call(arguments, 1));

    if (this.chart.tooltip && allowMove && this.chart.hoverPoints) {
      H.each(this.chart.hoverPoints, function(hoverPoint) {
        hoverPoint.setState(hoverPoint.state, true);
      });
    }
  })
})(Highcharts)
```
*Internal note:*
Only `hoverPoint` gets it's state refreshed, not all `hoverPoints`.

**Comment by tuhao1020** [comment]
It's completely resolved, thanks for your awesome work!

**Comment by sylaince** [comment]
It's completely resolved, thanks for your awesome work!

**Comment by pawelfus** [comment]
Let's keep this open - I think this should be fixed in the core.

**Comment by sylaince** [comment]
That will be great!

**Comment by pawelfus** [comment]
*Internal note:*
Just an idea of a fix. Still test needed, no PR yet.
