### ISSUE TITLE
Drilldown - overlapping categories

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#8286]
#### Behaviour
Width calculation of categories in next level of drilldown relates on previous axis labels.

#### Live demo with steps to reproduce
https://jsfiddle.net/mav9L65n/1/

Drill down into first column and categories are overlapping. Text is not wrapped if previous label at the same place was not wrapped and was clickable for drill down.

#### Workaround
Update the axis with categories, so labels will be recalculated.
https://jsfiddle.net/mav9L65n/2/

**Comment by TorsteinHonsi** [comment]
Regression since v6.0.7, duplicate of #8234.
