### ISSUE TITLE
Drilldown x-axis labels are changing

### ISSUE THREAD

**Issue by n7229** [highcharts/highcharts#8287]
https://codepen.io/naren7229/pen/YLEXNq

**Comment by pawelfus** [comment]
Hi @n7229 

Thank you for reporting this issue. This is known bug with more than ~30 categories on a chart. Workaround is to increase [`plotOptions.series.cropThreshold`](https://api.highcharts.com/highcharts/plotOptions.series.cropThreshold), demo: https://codepen.io/anon/pen/VxrPXQ

Closing as duplicate of #5857
