### ISSUE TITLE
Legend: break line so the following legends start from the next line

### ISSUE THREAD

**Issue by ivanelrey** [highcharts/highcharts#8297]
I have 10 labels for legends and I would like to separate them in 2 lines. 

I have tried to add a **<br>** tag but it affects only the label text.

```
legend: {
        enabled: true,
       ...
        useHTML: true,
        labelFormatter: function () {
            if (this.index == 4) {
              return this.name + '<br/>';
             } else {
              return this.name;
             }
        }
    },
```

How can I break the line so the following legends start from the next line?

**Comment by sebastianbochan** [comment]
Hi @ivanelrey,
This is our bugtracker for reporting bugs. For the general [support](http://www.highcharts.com) cases, please use forum, stackoverflow or email.

ps. I prepared you a simple demo: https://jsfiddle.net/vLx4s4wr/ but Im not sure how it should look like. Could you update my fiddle with your code, attach a mockup of requested chart and contact with us by support channels?

**Comment by ivanelrey** [comment]
Thank you @sebastianbochan 

I have created a post.

https://stackoverflow.com/questions/50256450/legend-break-line-so-the-following-legends-start-from-the-next-line

**Comment by sebastianbochan** [comment]
Thank you, we will answer you as soon as possible.
