### ISSUE TITLE
data lost in csv file

### ISSUE THREAD

**Issue by sylaince** [highcharts/highcharts#8298]
#### Expected behaviour
data update interval is 1 second, all points data should be saved in file

#### Actual behaviour
interval of some data records are greater than 1 second
below data is extract from my data.csv, some data lost.

2018-05-09 00:48:35 | 5
2018-05-09 00:48:38 | 50
2018-05-09 00:48:40 | 23
2018-05-09 00:48:45 | 68
2018-05-09 00:48:48 | 41
2018-05-09 00:48:50 | 38
2018-05-09 00:48:56 | 38
2018-05-09 00:48:56 | 70
2018-05-09 00:49:00 | 52
2018-05-09 00:49:06 | 55
2018-05-09 00:49:16 | 89
2018-05-09 00:49:18 | 31
2018-05-09 00:49:27 | 66

[data.csv.zip](https://github.com/highcharts/highcharts/files/1984888/data.csv.zip)

#### Live demo with steps to reproduce
http://jsfiddle.net/sylaince/kpe5fc42/3/

run the live demo for more than 10 minutes（30 minutes recommended） and then download csv or xls file

#### Product version
Highstock-6.1.0

#### Affected browser(s)
Chrome 66.0.3359.139

**Comment by sylaince** [comment]
I run both your demo and my demo, disabled animation and enabled animation, the issue can't  be reproduced. but the wrong csv file is downloaded from my demo,  How did it happen?

**Comment by sebastianbochan** [comment]
Hi @sylaince,
Thank you for the feedback. Unfortunately Im not able to predict, cause all my tests were passed. If you will be able to reproduce the issue in stable environment, let me know and reopen the ticket.
