### ISSUE TITLE
Area chart with 'percent' stacking doesn't show tooltip if ceiling is set on an axis

### ISSUE THREAD

**Issue by BernardoFBBraga** [highcharts/highcharts#8300]
#### Expected behaviour
Area chart stacking and axis ceiling should be independent

#### Actual behaviour
Area chart stacking 'percent' and axis ceiling affect the tooltip functioning

#### Live demo with steps to reproduce

https://jsfiddle.net/gqg618eb/468/

1- use your mouse over the chart and notice there is no tooltip
2- remove the ceiling property in yAxis and notice the tooltip works
3- reintroduce the ceiling property and now remove the stacking property in the area plotoptions - the tooltip also works
4- alternatively, change the stacking property to normal - tooltip works now

#### Product version

6.1.0
#### Affected browser(s)
Chorme, Firefox

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

It doesn't have to do with stacking or ceiling per se - the functionality is that points that lie outside the plot area don't show the tooltip. You can see it simplified here: http://jsfiddle.net/uq9xhp4L/

**Comment by BernardoFBBraga** [comment]
On a sidenote, I considered writing my own tooltip using plotoptions.series.point.events.mouseOver but those don't trigger either

**Comment by BernardoFBBraga** [comment]
How come if I set floor to 70 or 100 the chart loses width, while if I set to 50 it doesn't
https://jsfiddle.net/gqg618eb/469/
