### ISSUE TITLE
The chart stops updating when user clicks on update button after scrolling the chart using scrollbar

### ISSUE THREAD

**Issue by surgicaI** [highcharts/highcharts#8301]
#### Expected behaviour
The chart should update when clicking on update button

#### Actual behaviour
The chart doesn't update when clicking on update button

#### Live demo with steps to reproduce
https://jsfiddle.net/a093hxpd/
Steps: 
1. Use the scrollbar to scroll the chart.
2. Click on the update button.
3. Nothing happens.
4. Now reload the page and click on update button without interacting with the chart first. Now the update button works.

#### Product version
Highstock 6.1.0

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
The axis doesn't move because after scrolling, you have chosen a user-defined min and max that takes precedence over the options.

What you probably want to do is to use `setExtremes`: https://jsfiddle.net/a093hxpd/1/
