### ISSUE TITLE
API Examples doens't work anymore 

### ISSUE THREAD

**Issue by Karlito88** [highcharts/highcharts#8302]
#### Expected behaviour
Load the Examples in JsFiddle.

#### Actual behaviour
Are blocked from the Browsers to secure my personal data.

#### Affected browser(s)
Chrome and Opera

Picture:
[Picture of the not working JsFiddle](https://imgur.com/a/axFAsIB)

**Comment by pawelfus** [comment]
Hi @Karlito88 

Thanks for reporting the issue. It was a problem with jsFiddle, but should have been fixed  since yesterday. Just tested with Opera v52.0.2871.99 and it works fine. The same with latest Chrome and Firefox.

**Comment by Karlito88** [comment]
You're right. It works again.
