### ISSUE TITLE
Chinese display trouble in exported pdf file

### ISSUE THREAD

**Issue by sylaince** [highcharts/highcharts#8304]
#### Expected behaviour
all characters should show correctly

#### Actual behaviour
Chinese characters can't show correctly

#### Live demo with steps to reproduce
http://jsfiddle.net/sylaince/54gdfw91/

the title of the chart is in Chinese, download pdf file and open it you will reproduce this problem.

#### Product version
HIGHCHARTS 6.1.0

#### Affected browser(s)
Chrome 66

**Comment by TorsteinHonsi** [comment]
This is a known limitation of jsPDF, see #6417 and the discussion there.
