### ISSUE TITLE
hourly automatic datetime axis ticks in Asia/Kolkata time zone

### ISSUE THREAD

**Issue by kaikuchn** [highcharts/highcharts#8308]
#### Expected behaviour

When specifying every hour as the time interval for ticks to fall on, on a datetime axis via `xAxis.units` while using `time.timezone` to localize timestamps, I'd expect those ticks to fall on the beginning of the hour for the corresponding time zone.

#### Actual behaviour

Ticks fall on the beginning of UTC hours.

#### Live demo with steps to reproduce
http://jsfiddle.net/5nx95y6d/2/

```js
Highcharts.chart('container', {
  time: {
    timezone: 'Asia/Kolkata'
  },
  xAxis: {
    type: 'datetime',
    units: [['hour', [1]]]
  },
  series: [{
    data: Array.from({ length: 12 }, (_, i) => i),
    pointStart: Date.UTC(2016, 9, 22, 0, 30),
    pointInterval: 36e5
  }]
});
```

#### Product version
Highcharts JS v6.1.0 (2018-04-13

#### Workaround
I can specify the `xAxis.tickPositions` manually, but then I also have to override the default formatting and handle label rotation by myself. See https://github.com/highcharts/highcharts/issues/1441

PS: It works fine for `day`, etc.

**Comment by TorsteinHonsi** [comment]
If we remove `Minutes` from the array here, we get the correct results. However, it causes failure in the `timeticks` test.

https://github.com/highcharts/highcharts/blob/88c0013b0d8a1447fe477af151e64002f59f0ecf/js/parts/Time.js#L257
