### ISSUE TITLE
Reflow sometimes doesn't update the axis label

### ISSUE THREAD

**Issue by BernardoFBBraga** [highcharts/highcharts#8309]
#### Expected behaviour
If the chart has a width where the label is rendered fully (without ellipsis), is shrinked (to a point where the label is rendered with ellipsis) reflowed, and expanded back to its original position and reflowed again, labels should be rendered in full

#### Actual behaviour
Shrinking the chart, reflowing, expanding the chart again and reflowing leaves the labels with ellipsis, as if there was not enough room for them to render.

#### Live demo with steps to reproduce

http://jsfiddle.net/xzjzzq3s/3/

- drag the slider to the minimum and then to the maximum

**debug extra: if you set the step to a lower value or remove it entirely, the bug only presents in the last label

#### Product version

6.1.0
#### Affected browser(s)
Chrome, Firefox
In Chrome all the labels in the chart present the problem
In Firefox only the last label presents the problem

**Comment by pawelfus** [comment]
Hi @BernardoFBBraga 

Thank you for reporting this issue. This should be fixed on our master branch, take a look: http://jsfiddle.net/BlackLabel/xzjzzq3s/4/ 0 could you confirm?

**Comment by BernardoFBBraga** [comment]
Seems good to me!
When will this be released?

**Comment by pawelfus** [comment]
@BernardoFBBraga - we don't have ETA for v6.1.1. We are trying to release patched versions every month or two, so I would expect v6.1.1 within a few weeks.

Since it's fixed, closing issue then.

**Comment by BernardoFBBraga** [comment]
Thanks!
