### ISSUE TITLE
Click events does not work in blackberry

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#831]
1. Run the example http://jsfiddle.net/mjbjb/506/show in a blackberry browser (or emulator)
2. Click the rectangle
   Result: Nothing happens
   Expected: Alert box 'hi'

This happens because the blackberry browser "supports" touch events but then fires a click event. Highcharts renderer translates click events to touchstart when it sees that a browser support touch. We need to change this as more and more browsers support both touch and mouse events.

**Comment by oysteinmoseng** [comment]
Blackberry is now Android powered and this issue should no longer be relevant.
