### ISSUE TITLE
Responsive rules do not return to original value when condition is false

### ISSUE THREAD

**Issue by einord** [highcharts/highcharts#8311]
#### Expected behaviour
When using responsive rules to change options on a chart they should return to normal when the condition callback returns false.

#### Actual behaviour
When using the responsive settings, options do not return to their original values.

#### Live demo with steps to reproduce
See my example here: https://jsfiddle.net/einord/4vnreujx/2/
The button in the example toggles the settings and redraws the chart, but they only change the first time.

#### Product version

Highcharts version 6.1.0.

#### Affected browser(s)
Safari, Chrome, Firefox, Edge, Internet Explorer
(All using the latest version)

**Comment by pawelfus** [comment]
Hi @einord 

Thank you for reporting this bug. You are right, default `visible` option for an axis is not restored. I am curious, why don't you simply use `chart.update()` but play around with responsive options? See example: https://jsfiddle.net/BlackLabel/4vnreujx/3/

**Comment by einord** [comment]
@pawelfus Yes, you are correct. It is easier to use chart.update as in your example.
I was just simply playing around with the responsive rules and stumbled upon this bug, so I tried to make the example to reproduce the bug as simple as possible.
