### ISSUE TITLE
highcharts sizing breaks flexbox

### ISSUE THREAD

**Issue by HiloCoder** [highcharts/highcharts#8312]
#### Expected behaviour
The chart should abide by flexbox rules.

#### Actual behaviour
The chart is initially larger than the rules specified by the flexbox css.   Resizing the window causes the chart to continue to resize incorrectly.

#### Live demo with steps to reproduce
http://jsfiddle.net/6ao7t900/4/

#### Product version
6.1.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @HiloCoder 

Thank you for reporting this issue.

Related to #6427

**Workaround:**
Set `#chart { overflow: hidden }` so containers can shrink and force chart's layout to redraw. Demo: http://jsfiddle.net/BlackLabel/6ao7t900/5/

**Comment by HiloCoder** [comment]
That doesn't work.  Add overflow: hidden to the chart element in my fiddle and you will see the chart is still sized incorrectly and continues to incorrectly resize horizontally when the window is resized vertically.
