### ISSUE TITLE
Mouse hover in heatmap creates large box what leaves trail

### ISSUE THREAD

**Issue by choudhary001** [highcharts/highcharts#8313]
#### Expected behaviour
Mouse hover should work properly

#### Actual behaviour
In this case, mouse hover in heatmap turns in to giant square that leaves a trail when mouse moved around.

#### Live demo with steps to reproduce
https://jsfiddle.net/L1g7uxmw/

#### Product version
highcharts v6.1.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @choudhary001 

Thank your for reporting the issue. This is expected behabiour, default [`heatmap.colsize`](https://api.highcharts.com/highcharts/series.heatmap.colsize) and [`heatmap.rowsize`](https://api.highcharts.com/highcharts/series.heatmap.rowsize) is set to `1`. In your case you should decrease this value according to closest distance between two points, for example: https://jsfiddle.net/BlackLabel/L1g7uxmw/4/

**Comment by choudhary001** [comment]
Hi,

Thanks for the tip. I also noticed that if i use 'data.csv' option to provide plot data this issue doesn't happen.

    data: {
        csv: document.getElementById('csv').innerHTML
    },

Could you please explain what happens in this case?

link: https://jsfiddle.net/6Ljo3L3a/

Thanks for the help.

**Comment by pawelfus** [comment]
Hi @choudhary001 

That's not related to `data` module, but to `boost` - in boost, everything is rendered on a canvas, in SVG elements are in DOM. When elements are in DOM, we can bring them to front. See demo without boost: https://jsfiddle.net/BlackLabel/6Ljo3L3a/1/

**Comment by choudhary001** [comment]
Thanks for the clarification and help, @pawelfus
