### ISSUE TITLE
Update color in pie legend

### ISSUE THREAD

**Issue by alexandrgorodilov** [highcharts/highcharts#8315]
Incorrect display of the legend after the update:
![image](https://user-images.githubusercontent.com/16904814/39866973-377fa288-546c-11e8-81b4-bb4d8b2961ca.png)

#### Expected behaviour
After clicking on the chart, the legend will be updated in the color of the selected chart

#### Actual behaviour
After clicking the legend is updated, but there is an additional item in the legend

#### Live demo with steps to reproduce
https://jsfiddle.net/alexandrgorodilov/ep75ge4u/4/

#### Product version
Highcharts version 6.1.0

#### Affected browser(s)
Chrome 66.0.3359.139

**Comment by pawelfus** [comment]
Hi @alexandrgorodilov 

Thanks for reporting this issue. The way you update options is wrong - you update objects directly, while [`series.update()`](https://api.highcharts.com/class-reference/Highcharts.Series#update) should be used. Demo for you: https://jsfiddle.net/BlackLabel/ep75ge4u/5/

**Comment by alexandrgorodilov** [comment]
Hi @pawelfus . Thanks for answer!
