### ISSUE TITLE
scrollablePlotArea: exporting and series visibility toggle

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#8316]
#### Behaviour
scrollablePlotArea is causing:

- [x] exporting menu is overlapped by the scrollableMask
- [ ] exported chart has total width and doesn't look like the viewed chart
- [x] on series hide / show via legend click the scroll jumps back to the set scrollPositionX when set to a value different than 0

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/rgg8syxq/

Steps:
1. Scroll
2. Toggle series by legend item click
3. Open exporting menu
4. Export chart
5. Compare exported chart with the original one

**Comment by boyanfi** [comment]
I can add that the tooltip appears underneath the Mask, and i found no way to avoid it. 

Can be reproduced on the same fiddle as above - when you scroll a bit and hover the line close to the mask - the tooltip appears below it.

**Comment by TorsteinHonsi** [comment]
All issues fixed now. 

The scrolling effect is disabled for exported charts. In practice this probably means that we want wider charts in export, which can be achieved by setting an [exporting.sourceWidth](https://api.highcharts.com/highcharts/exporting.sourceWidth).
