### ISSUE TITLE
Remove break between two series

### ISSUE THREAD

**Issue by boolkaco** [highcharts/highcharts#8317]
#### Expected behaviour
Two series must be glued to each other

#### Live demo with steps to reproduce
http://jsfiddle.net/5ypnffww/284/

#### Product version
6.0.4

#### Affected browser(s)
Coogle chrome

**Comment by pawelfus** [comment]
Hi @boolkaco 

Thank you for reporting this issue. You can achieve this by setting [`xAxis.breaks`](https://api.highcharts.com/highcharts/xAxis.breaks), see: http://jsfiddle.net/BlackLabel/5ypnffww/285/ (note: `broken-axis.js` module is required)

@sebastianbochan FYI

**Comment by boolkaco** [comment]
Thanks @pawelfus.
Can you help me with this http://jsfiddle.net/5ypnffww/287/ ?
How to center two series along the x axis?
So that each series occupies half the height of the graph.

**Comment by pawelfus** [comment]
Hi @boolkaco 

Something like this: http://jsfiddle.net/BlackLabel/5ypnffww/288/ ? It's ordinal axis, instead of breaks.

**Comment by boolkaco** [comment]
@pawelfus but how can you combine these two properties?

**Comment by pawelfus** [comment]
@boolkaco I'm not sure how this should work. For example one set has set in range 0-100, second one has 0-150. In other words, both sets require different amount of space, but you want them equal. Ordinal takes care of this, but you have empty space between sets. Maybe instead use two xAxes? Something like this: http://jsfiddle.net/5ypnffww/289/

**Comment by boolkaco** [comment]
@pawelfus Thanks!

**Comment by boolkaco** [comment]
@pawelfus Why the toolbar for the green line is displayed incorrectly?
