### ISSUE TITLE
Legend item position does not account for font size when useHTML option is enabled

### ISSUE THREAD

**Issue by jonathanfroy** [highcharts/highcharts#8319]
Using CSS version of Highcharts 6.0.7. Setting a larger-than-default font size on legend items (CSS class .highcharts-legend-item). When legend.useHTML option is enabled, the label in the legend item is misaligned vertically relative to the symbol.

http://jsfiddle.net/15s1kyu0/2/

All positioning seems to be using absolute coordinates directly on the legend item, making it difficult to override. Any suggestions how to work around this?

Seen on Chrome 66.

**Comment by sebastianbochan** [comment]
Hi @jonathanfroy,
You can set negative marginTop as workaround.
- http://jsfiddle.net/tsgguogq/

**Comment by pawelfus** [comment]
I would expect the same result, no matter if `useHTML` is set to true or not: http://jsfiddle.net/BlackLabel/15s1kyu0/3/

**Comment by jonathanfroy** [comment]
@sebastianbochan, negative margin-top works, indeed, but how come it affects only the label and not the symbol as well? The class name does seem to apply to the whole legend item.

**Comment by sebastianbochan** [comment]
@jonathanfroy 
The class is applied only for the label, not for symbol. At this moment this is default functionality.

If you would like to move symbol, you should call `translate()` method on the legend item.

Demo:
- http://jsfiddle.net/BlackLabel/ux31of5p/
- Move the whole legendItem group - http://jsfiddle.net/BlackLabel/k6cggcov/
