### ISSUE TITLE
[Question]What kind of point hover properties changed since highmaps version >= 5.0.6

### ISSUE THREAD

**Issue by ceyhunnabiyev** [highcharts/highcharts#8326]
#### Expected behaviour
I want to show  the correct result  with highmaps latest version

#### Actual behaviour
Point on another point disappears after mouse hover with highmaps version >= 5.0.6.
Correct result:
[http://jsfiddle.net/jeyhunn/qxvdatm4/](http://jsfiddle.net/jeyhunn/qxvdatm4/)

Wrong result:
[http://jsfiddle.net/jeyhunn/9eag99b6/1/](http://jsfiddle.net/jeyhunn/9eag99b6/1/)

#### Affected browser(s)
Google Chrome and Firefox

**Comment by ceyhunnabiyev** [comment]
Thank you so much. I understood...
However, For inkscape when I save the changes(fixes for path),  there is v and h instructions (vertical and horizontal lines) in d attribute. Highcharts from svg gives me  strange view. Seems like it doesn't support v and h instructions. How do I fix this?

**Comment by KacperMadej** [comment]
You could contact support using any other channel - https://www.highcharts.com/support
We are trying to keep github for bugs only.

It should be possible to convert you SVG, but to be sure please provide more details about the "Highcharts from svg" thing you mentioned when contacting support.
