### ISSUE TITLE
 Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by savi429** [highcharts/highcharts#8327]
#### Expected behaviour
I want simple chart in react component

#### Actual behaviour
I am facing this error 

#### Product version
highcharts version 6.1.0

#### Affected browser(s)

chrome

**Comment by sebastianbochan** [comment]
Hi @savi429,
The github is our bug tracker for reporting bugs. Please use [support](http://www.highcharts.com/support) channels for contacting us.

Meanwhile I advise you to familiar with our examples here: 
- https://www.highcharts.com/blog/frameworks/react/192-use-highcharts-to-create-charts-in-react/
