### ISSUE TITLE
Highcharts performance issues

### ISSUE THREAD

**Issue by Attrash-Islam** [highcharts/highcharts#8328]
Hi,
I was profilling a heavy page in Chrome with 4x CPU throttling. The page is rendering more than 15 Highcharts chart (every chart with multiple series and more than 300 point per series). The page is written with AngularJS 1.x

I done the the redraw as false and triggered it at the end of the operations. And Animation is turned off. I see that the most of the time is spent in redraw execution as shown in Chrome Devtools.

Is there any suggestion other than the mentioned above? Or is that expected for that amount of charts (with 4x CPU throttling)? Is writing the code with async/await can split the connected chunks of JS execution in the Chrome Devtools?

P.S. I tried the boost modules and the page became more slower.

Highcharts version: 4.2.3
AngularJS version: 1.5.8

Thanks

Best Regards,
Islam

**Comment by Attrash-Islam** [comment]
All the charts is rendered in a $watch on the same data array. That may means that the change for all the charts may update in one $digest if I understand AngularJS well enough

**Comment by sebastianbochan** [comment]
Hi @Attrash-Islam,
Thank you for contacting us. The github is our bugtracker for reporting bugs.

Could you contact with us by [email](support@highsoft.com), simplify your webpage's chart and replicate it as live demo? It will allow us to debug and find a reason of low performance.
