### ISSUE TITLE
Plot band overlap issue on the y-axis and unable to display plot band label and range on data point tooltip 

### ISSUE THREAD

**Issue by sureshbakshi** [highcharts/highcharts#8329]
#### Expected behavior
when points get close the label has to hide and display it as a legend and display of plot band range and label on tooltip when hovering on the data point. 

#### Actual behaviour

unable to display label and range of plot band on the tooltip.when points close it is overlapping with other.

#### Live demo with steps to reproduce

http://jsfiddle.net/suresh30/02fe1tp5/2/

**Comment by sebastianbochan** [comment]
Hi @sureshbakshi,
Thank you for reporting. The github is our bugtracker for reporting bugs. Your scenario is a custom solution and not build in Highcharts at this moment. I advise you to post your idea in our [uservoice](https://highcharts.uservoice.com/) service.

Workaround:
Add minPadding option in the xAxis.
Demo:
- http://jsfiddle.net/BlackLabel/w0nt9and/
