### ISSUE TITLE
Problem with 'min' property or 'setExtremes' method with enabled dataGrouping - Highstock

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#8335]
#### Expected behaviour
![screen shot 2018-05-14 at 17 30 42](https://user-images.githubusercontent.com/22988131/40007264-95ff5d20-579c-11e8-80f5-e9542eb28ca8.png)

Works fine with Highstock v6.0.7: http://jsfiddle.net/BlackLabel/6cqfz44n/

#### Actual behaviour
Using 'setExtremes' or setting 'min' do not affect the x axis.

![screen shot 2018-05-14 at 17 29 15](https://user-images.githubusercontent.com/22988131/40007306-b0e1b692-579c-11e8-90e3-152dbf215754.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/quxLews1/

#### Product version
Highstock 6.1.0

#### Affected browser(s)
All

**Comment by ppotaczek** [comment]
It looks like this problem is caused by: f1f4adc

**Comment by Head** [comment]
Having the same issue. Did you find a fix or workaround @ppotaczek?

**Comment by pawelfus** [comment]
Demo with fix applied: http://jsfiddle.net/BlackLabel/quxLews1/24/

Note: In the next versions, you need to set `xAxis.min` for both, main and the navigator xAxis: http://jsfiddle.net/BlackLabel/quxLews1/23/ to reflect extremes in the navigator.
