### ISSUE TITLE
Removing a series/axis at the same time when updating causes an error

### ISSUE THREAD

**Issue by chored** [highcharts/highcharts#8336]
#### Expected behaviour

Calling update with new config, where one yAxis and its series have been removed redraws the chart with the series/axis removed from the chart.

#### Actual behaviour

Error in console and chart is empty

#### Live demo with steps to reproduce
http://jsfiddle.net/bb1b1s9q/1/

Click Add button
Click Remove both button 
Error occurs

Click Add button
Click Remove separate button
Everything works

#### Product version
Highcharts

**Comment by chored** [comment]
Sorry, calling update two times was to demonstrate that removing a series first and then removing the axis in a second update worked fine - i.e. the bug is specifically when trying to do both in the same update.

**Comment by sebastianbochan** [comment]
Hi @chored,
Thank you for the feedback.
