### ISSUE TITLE
Numbers as series labels disappear in iOS UIWebView (React Native)

### ISSUE THREAD

**Issue by rgoldiez** [highcharts/highcharts#8339]
#### Expected behaviour
In React Native, rending a HighChart in a WebView (iOS UIWebView) a simple column chart with numeric series names (represented as a string, through) disappear shortly after animations finish.  This shouldn't happen.  No issues on Android WebView.

#### Actual behaviour
![may-14-2018 17-12-46](https://user-images.githubusercontent.com/10797610/40026211-188d0c0e-579a-11e8-9e4b-c5dee8278d97.gif)

#### Live demo with steps to reproduce
I created an expo 'snack' to see the issue.  You can run the iOS simulator in the browser (for free) by clicking "Tap to Play" on the right side (might have to wait your turn if the queue is long).

https://snack.expo.io/Skw3ufJiM

#### Product version
Appears to be an issue in 5.0.12 and 6.1.0 (latest)

#### Affected browser(s)
iOS UIWebView

**Comment by sebastianbochan** [comment]
Hi @rgoldiez,
Thank you for the reporting. It looks like Highcharts' SVG element is converted into object in webView wrongly, when formatter refers to the variable. 

**Workaround**
The solution is setting 'useHTML' as true.

Demo:
- https://snack.expo.io/SJQg6GdCf

**Comment by rgoldiez** [comment]
@sebastianbochan - Awesome!  Thanks for the fast response and workaround.

**Comment by morganfree** [comment]
It looks like your series name is detected as a phone number and converted to the URL - `<a>` tag -this is not desired behaviour for svg elements.

The automatic conversion can be configured with [dataDetectorTypes](https://facebook.github.io/react-native/docs/webview.html#datadetectortypes) prop of the WebView component. By default only phone numbers are detecting.

Set `dataDetectorTypes` to`'none'`:

    <WebView
      ...
      dataDetectorTypes='none'
    />
