### ISSUE TITLE
How to add descriptions in a graph at a time node on the X axis?

### ISSUE THREAD

**Issue by yanranxiaoxiaoshu** [highcharts/highcharts#8340]
#### How to add descriptions in a graph at a time node on the X axis?

For example:

![image](https://user-images.githubusercontent.com/21351375/40034370-350aa824-582f-11e8-83c6-da2bd45fdb6a.png)

**Comment by sebastianbochan** [comment]
Hi @yanranxiaoxiaoshu 
Thank you for contacting. The github is our bugtracker for reporting issues. For the further [support](http://www.highcharts.com/support) questions, please use forum / email or stackoverlow.

ps. You can add custom text and shapes by the [Renderer](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer).
