### ISSUE TITLE
Vertical lines appear in treemap chart on Chrome 67+

### ISSUE THREAD

**Issue by Malczewski** [highcharts/highcharts#8341]
White lines are shown over the treemap (and some other "area" charts with horizontal animation) on newer chrome versions (see screenshot), works fine in Chrome 66 or FF or IE.
Seems it's caused by rendering animation (each frame lefts its "fingerprint"), as with disabled animation the issue is not reproduced. 

#### Live demo with steps to reproduce
Screenshot - https://prnt.sc/ji3ak4
Reproduced on charts with filled area (treemap, area) and horizontal animation direction. 
https://www.highcharts.com/demo/treemap-coloraxis
https://www.highcharts.com/demo/area-basic
On some charts white lines are visible during animation, but then disappear (e.g. https://www.highcharts.com/demo/area-negative)
#### Product version
Highcharts 6.1.0

#### Affected browser(s)
Chrome 67+ (at this moment - beta, dev and canary builds)

**Comment by KacperMadej** [comment]
Hi @Malczewski 

If this is visible only in a browser that is in development than maybe it's a browser caused problem? Please check if this is possible to recreate with just SVG and if yes, then please report it to the browser support.

Right now, as you wrote, this works fine for stable browser versions, so let's wait for Chrome 67+ release.

**Comment by Malczewski** [comment]
Hi @KacperMadej, thank you for the reply.
I tried simple svg animation https://jsfiddle.net/L1mda5th/ and it worked fine. Though seems Highcharts uses a different animation approaches for different charts:
1) simple bar chart uses animation based on changing _scale_ and doesn't have the issue
2) area/line/treemap and similar charts use _clipPath_ based animation, and all of these have the issue.
P.S. 11 days left for Chrome 67

**Comment by KacperMadej** [comment]
It's Chrome v67 problem with SVG - Highcharts-free demo with the same problem: https://jsfiddle.net/L1mda5th/1/

I have reported this via Chrome's report problem feature.

**Comment by KacperMadej** [comment]
Unable to recreate the problem in Chrome v78, so it must have been fixed somewhere in between v67 and v78. This was a browser issue with SVG that is no longer possible to be recreated. Closing as resolved.
