### ISSUE TITLE
[BUG] Loading options documentation is incorrect regarding styled mode classes

### ISSUE THREAD

**Issue by marques-work** [highcharts/highcharts#8342]
For the lines below, the classes should read `highcharts-loading-inner` and `highcharts-loading`, respectively:

https://github.com/highcharts/highcharts/blob/88e8c4884cae0884fc8dc90a80b2c4d80f793ceb/js/parts/Options.js#L2338

https://github.com/highcharts/highcharts/blob/88e8c4884cae0884fc8dc90a80b2c4d80f793ceb/js/parts/Options.js#L2354

**Comment by KacperMadej** [comment]
Hi @marques-work 

Thank you for finding this one.

**Comment by marques-work** [comment]
@KacperMadej I submitted a small [PR to fix this](https://github.com/highcharts/highcharts/pull/8345)
