### ISSUE TITLE
tooltip.positioner returns inconsistent labelWidth

### ISSUE THREAD

**Issue by KieranCairney** [highcharts/highcharts#8343]
#### Expected behaviour

labelWidth is not effected by external values outside of the tooltip config.

#### Actual behaviour

I'm trying to debug an issue with the callback from tooltip.positioner, specifically around the value of labelWidth. Using the same tooltip config in my app and in a vanilla fiddle that I created (and same versions of highcharts), the issue does not exist in the fiddle.

This lead me to believe that the callback's labelWidth may be different as a result of using useHTML and some global css rule within my app affecting the callback for labelWidth.

In my app specifically, this occurs after a browser zoom in/out and the tooltip background will then flicker.

I'm curious as to what css could be overwriting something in highcharts to change labelWidth, if that is the issue.

#### Product version

Highcharts 6.1.0

#### Affected browser(s)

Chrome

**Comment by sebastianbochan** [comment]
Hi @KieranCairney,
Thank you for reporting. Could you isolate your problem and replicate as live demo? It will allow us to debug, because at this moment it is really difficult to predict a reason of the issue.

**Comment by KieranCairney** [comment]
Here is a fiddle with the same tooltip config I use within the app having this issue: https://jsfiddle.net/665h1jxn/4/

Again, note that the issue does not happen within the fiddle so I'm suspecting something externally is modifying the HTML within the app, as the issue only happens when useHTML is true. However, useHTML is required in this case for a specific UX spec.

And here is the flicker within the app:
![flicker](https://user-images.githubusercontent.com/10413200/40129864-3ef4dfce-58ea-11e8-9d2d-90b9bac357ca.gif)

**Comment by sebastianbochan** [comment]
Hi @KieranCairney 
Unfortunately without any live demo we are not able to replicate, debug, fix and test it.

**Comment by KieranCairney** [comment]
I understand, thanks @sebastianbochan I'm okay with closing this for now, I may re-open if I'm able to reproduce in a more restricted environment.
