### ISSUE TITLE
The position of the legend changed from migrating from 6.0.3 to 6.1.0

### ISSUE THREAD

**Issue by VBIManonmaniM** [highcharts/highcharts#8344]
The position of the legend changed from migrating from 6.0.3 to 6.1.0.Please refer the jsfiddle.

#### Live demo with steps to reproduce

v6.0.3 : https://jsfiddle.net/6s4tLmxh/
v6.1.0 : https://jsfiddle.net/6s4tLmxh/1/
#### Product version

Highcharts v6.1.0

#### Affected browser(s)
All Browsers

**Comment by sebastianbochan** [comment]
Hi @VBIManonmaniM,
The position was changed since 6.0.4 version due to overlapping bug.

https://github.com/highcharts/highcharts/issues/7428
