### ISSUE TITLE
Array indexOf Polyfill error in oldie module

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#8346]
Array indexOf Polyfill in your [modules/oldie.src.js](https://github.com/highcharts/highcharts/blob/88e8c4884cae0884fc8dc90a80b2c4d80f793ceb/js/modules/oldie.src.js#L107)

	if (!Array.prototype.indexOf) {
	    H.indexOfPolyfill = function(arr) {
	        var len,
	            i = 0;

	        if (arr) {
	            len = arr.length;

	            for (; i < len; i++) {
	                if (arr[i] === this) {
	                    return i;
	                }
	            }
	        }

	        return -1;
	    };
	}

fixed with: 

	if (!Array.prototype.indexOf) {
	    H.indexOfPolyfill = function(item) {
	        var len,
	            i = 0;

	        if (item) {
	            len = this.length;

	            for (; i < len; i++) {
	                if (this[i] === item) {
	                    return i;
	                }
	            }
	        }

	        return -1;
	    };
	}

**Comment by KacperMadej** [comment]
_Internal note:_

Additionally, `H.indexOfPolyfill `

https://github.com/highcharts/highcharts/blob/88e8c4884cae0884fc8dc90a80b2c4d80f793ceb/js/modules/oldie.src.js#L107-L124

doesn't support `fromIndex`.

https://github.com/highcharts/highcharts/blob/f47dfac813d05ee6eadd24403e4d48ad89ef28c2/js/parts/Utilities.js#L1469-L1474
