### ISSUE TITLE
Column Graph - Stacking and Grouping

### ISSUE THREAD

**Issue by lrapchan** [highcharts/highcharts#8348]
Is it possible to group the dates that are stacked? In my example is adding, wanted to overlap. Thanks.

https://jsfiddle.net/3yw8xxy8/1/

**Comment by sebastianbochan** [comment]
Hi @lrapchan 
Thank you for contacting us. The github is our bugtracker for reporting bugs, so please use our forum / stackoverflow or email for general [support](http://www.highcharts.com/support) questions.
