### ISSUE TITLE
Hardcoded chart.pointCount limit = 100

### ISSUE THREAD

**Issue by DamianoPantani** [highcharts/highcharts#8351]
Check chart's zoom function:

		            chart.redraw(
		                pick( // animation
		                    chart.options.chart.animation,
		                    event && event.animation,
		                    chart.pointCount < 100
		                )
		            );

if I zoom the chart (either in or out) it refuses to animate if it contains more than 100 points. I'd love to have it configurable without the need of wrapping zoom function.

#### Expected behaviour
animationLimit should be configurable (ideally in 'chart' config)

#### Actual behaviour
it's hardcoded to 100

#### NOTES
series' drawPoints function has default points limit = 250, which is inconsistent and way less restrictive than chart's zoom function which doesn't make sense

**Comment by KacperMadej** [comment]
Hi @DamianoPantani 

No need to wrap this - you could set [chart.animation](https://api.highcharts.com/highcharts/chart.animation) and the `pick` function will pick this one up first while trying to determinate if redraw should run with animation enabled.

If you call the `zoom` function yourself and don't want to set the `chart.animation` then you could use the `animation` property of first argument resolved to the `event` in the code you pasted.

Here's the code reference in this repository:

https://github.com/highcharts/highcharts/blob/514042760f1b57a5d48a50c73ae5ab352bc38498/js/parts/Interaction.js#L424-L430

However, I'm marking this as enhancement.
