### ISSUE TITLE
Highstocks charts no longer displays "Reset Zoom" button in v6.1.0

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/highcharts#8352]
#### Expected behaviour
"Reset Zoom" button appears when zooming into a chart via dragging the mouse on the main plot area.

#### Actual behaviour
"Reset Zoom" button no longer shows up when zooming into a chart via dragging the mouse on the main plot area.

#### Live demo with steps to reproduce
v6.0.7: https://jsfiddle.net/lanimelrok/pg90yvwm/ (Reset Zoom button appears!)
v6.1.0: https://jsfiddle.net/lanimelrok/5wsrps2p/ (Reset Zoom button is missing!)

#### Product version
Highstock 6.1.0

**Comment by sebastianbochan** [comment]
Hi @LaniMoo,
Thank you for reporting. The issue has been already fixed in the newest master branch:
Demo:
- https://jsfiddle.net/BlackLabel/3bnx2Lmw/

The fix will be added to the next official release, withing a few weeks.
