### ISSUE TITLE
 Placing information about the risk of use 'useHTML' in the documentation.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#8354]
It would be good to mention in documentation about the risk of using `useHTML` parameters, because if developer would download data from some unverified sources and assign it for example directly to string returned from `formatter` function, he is exposed to run some unauthorized code  in a browser. For example:

```js
dataLabels: {
        enabled: true,
        useHTML: true,
        formatter: function() {
              return "<h3 onmouseover='console.log(window)'>Some data label</h3>";
        }
}
```

#### Live demo with steps to reproduce
Example: https://jsfiddle.net/Lhg110no/ (hover on some dataLabel, then open the console, there is window object logged)

**Comment by sebastianbochan** [comment]
@TorsteinHonsi what do you think?

**Comment by bre1470** [comment]
My suggestion:
```js
        /** ...
         * Please note, that this can become a security risk to run unauthorized
         * code in the browser, if you load options from an untrusted source.
         * ...
```

**Comment by bre1470** [comment]
Integrated into the regular documentation: https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#html
