### ISSUE TITLE
plotLines ->labels -> useHTML doesn't work

### ISSUE THREAD

**Issue by chenmei1** [highcharts/highcharts#8356]
#### Actual behaviour
useHTML doesn't work and no debugger

#### Live demo with steps to reproduce
plotLines: [{
                color: '#E0E0E0',
                width: 1,
                value: xIndex,
                label:{
                    useHTML:true,
	            formatter: function () {
                          debugger;
			  return '<span>'+ this.value +'</span>'
		    },
                    y:96,
                }
            }]

#### Product version
 Highcharts version 6.0.7 

#### Affected browser(s)
chrome、FF

**Comment by TorsteinHonsi** [comment]
This issue has a `Status: Pending review` label, but I can't see a PR for it?

**Comment by kamilkulig** [comment]
My bad, it's already merged into master: https://github.com/highcharts/highcharts/pull/11398
