### ISSUE TITLE
The legend can't be enabled using 'setOptions()' on Highstock.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#8357]
#### Actual behaviour

Setting the legend enabled by `Highcharts.setOptions()` doesn't give any effect.

#### Live demo with steps to reproduce

http://jsfiddle.net/krm00Lre/

#### Product version
Highstock, All versions

**Comment by KacperMadej** [comment]
`StockChart` constructor is setting default options that are out of reach for `Highcharts.setOptions()` - `legend.enabled` is one of them.

You could resolve this as:
1. set options on chart level
or
2. copy all stock options from [stockChart constructor](https://github.com/highcharts/highcharts/blob/master/js/parts/StockChart.js#L126-L273) and set them using `setOptions()`, so you could later use `chart` constructor and have all stock options set by default.

_Internal note:_ +1 for stock default options or any_constructor default options @pawelfus

**Comment by sebastianbochan** [comment]
_Internal note_
Related with: https://github.com/highcharts/highcharts/issues/7307
