### ISSUE TITLE
Only one label shown on the Y axis when the values are the same

### ISSUE THREAD

**Issue by dominikfilkus** [highcharts/highcharts#8359]
Hi All,

There is a special case when the line charts only have the same values on the Y axis then we see only one label.

#### Live demo with steps to reproduce
Here is a modified highcharts example representing this case:
http://jsfiddle.net/b5v889nu/2/

According to the documentation we can manually modify the number of the labels by setting the `tickAmount` or set the `min` value for example 0. The problem is I do not want to hardcode values because the data in my case is always dynamic. I rather looking for a flag like option to choose if I would like to see multiple automatically calculated labels in this special case or not. 

Currently I handle this case by workarounds, checking each of the values from the Y axis, check if they are the same and play with `tickAmount`.

**Comment by sebastianbochan** [comment]
Hi @dominikfilkus,
You can use the [tickPositioner](https://api.highcharts.com/highstock/yAxis.tickPositioner) and add the logic of amount of ticks.

For the further [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

**Comment by pawelfus** [comment]
Alternative solution: set [`yAxis.minRange`](https://api.highcharts.com/highcharts/yAxis.minRange), demo: http://jsfiddle.net/b5v889nu/5/
