### ISSUE TITLE
How can I solve the problem of the blank space in this time period?

### ISSUE THREAD

**Issue by yyb1994** [highcharts/highcharts#8360]
#### Expected behaviour

My chart time is 9:30-11:30, 13:00-15:00,
Now there will be a blank at 11:30 -13:00. How can I solve this problem?

#### Live demo with steps to reproduce
https://jsfiddle.net/fct26nhs/2/

#### Product version
 Highstock 

#### Affected browser(s)

![_20171215132236](https://s9.postimg.cc/e5z3q0qy7/image.png)

**Comment by sebastianbochan** [comment]
Hi @yyb1994,
Please let me know how the chart should be draw, the gap should be not visible and all points "connected" ?

**Comment by camtin** [comment]
Maybe you can consider using "breaks" on the xAxis?

See this demo: https://www.highcharts.com/stock/demo/intraday-breaks

**Comment by yyb1994** [comment]
I feel very well that I have solved this problem with the help of my friends.
