### ISSUE TITLE
Is it possible to create a chart like attached image in Highcharts

### ISSUE THREAD

**Issue by anjareddy** [highcharts/highcharts#8361]
#### Live demo with steps to reproduce

![hourstracking](https://user-images.githubusercontent.com/3666148/40307368-c0440274-5d1f-11e8-8b19-7f8e403168f7.PNG)

**Comment by sebastianbochan** [comment]
Hi @anjareddy,
The github is our bugtracker, so for general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.
