### ISSUE TITLE
Plot line value in percent

### ISSUE THREAD

**Issue by yauhenihrabun** [highcharts/highcharts#8363]
Is it possible to define plotLines value in percent based on chart area dimension?

**Comment by sebastianbochan** [comment]
Hi @yauhenihrabun ,
The github is our bugtracker, so for general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

ps. You can extract height of plotarea and multiply by value in percent. 
Example:
 - http://jsfiddle.net/BlackLabel/nx3fah8k/
