### ISSUE TITLE
Missing check for link in boost

### ISSUE THREAD

**Issue by manu-st** [highcharts/highcharts#8364]
I'm trying to debug a webGL failure on old hardware but boost does not check all the time the return status of certain functions. For example, at this location:
https://github.com/highcharts/highcharts/blob/8ffd09bce9b44441d35c9d6528d43a5f4c7c79aa/js/modules/boost.src.js#L564

After linking the program, there is no check to see if it linked properly. The result is that instead of telling why it failed, it continues onto `useProgram` with just an error stating it is invalid.

Add the following line to fix this:
```
   gl.linkProgram(shaderProgram);

   if (!gl.getProgramParameter(shaderProgram, gl.LINK_STATUS)) {
      shaderProgram = false;
      // console.error ('error linking shader program');
      return false;  
   }
```

I do not have a reproducible sample on recent hardware only on a quite old computer (6+ years).

**Comment by KacperMadej** [comment]
Hi @manu-st 

Thank you for reporting.

Please let us know hardware and software (OS, browsers used, etc.) specification of the problematic machine. Do you have any more details about the error / webGL failure?

FYI @cvasseng

**Comment by manu-st** [comment]
Got the real info now:
Intel i7 870 
AMD Radeon HD 3450 with a very old driver from 2009

The machine is running Windows 7 and to render the graph we use Electron 2.0 which corresponds to Chrome 61.

**Comment by KacperMadej** [comment]
Please check if in your chart's configuration you are using any experimental options (as described in API reference), so maybe you could avoid this error. Additionally please provide used chart's configuration (and at least data format used for series) or a live demo - e.g. if you can recreate the problem with any of our default boost demos then it will be fine for further debugging and testing.

**Comment by manu-st** [comment]
Still cannot produce yet a demo showing the issue but I'm providing here some info on the failure. When the link fails, I query the error and get:

```
C:\fakepath(28,12): error X6077: texld/texldb/texldp/dsx/dsy instructions with r# as source cannot be used inside dynamic conditional 'if' blocks, dynamic conditional subroutine calls, or loop/rep with break*. 

Warning: D3D shader compilation failed with default flags. (ps_3_0)
 Retrying with avoid flow control
C:\fakepath(28,12): error X6077: texld/texldb/texldp/dsx/dsy instructions with r# as source cannot be used inside dynamic conditional 'if' blocks, dynamic conditional subroutine calls, or loop/rep with break*. 

Warning: D3D shader compilation failed with avoid flow control flags. (ps_3_0)
 Retrying with prefer flow control
C:\fakepath(28,12): error X6077: texld/texldb/texldp/dsx/dsy instructions with r# as source cannot be used inside dynamic conditional 'if' blocks, dynamic conditional subroutine calls, or loop/rep with break*. 

Warning: D3D shader compilation failed with prefer flow control flags. (ps_3_0)


Failed to create D3D shaders.
```

My configuration is as following:
- useragent: "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) ASTRA/8.0.0 Chrome/61.0.3163.100 Electron/2.0.2 Safari/537.36"
- shading language version: "WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)"
- Unmasked renderer webgl: "ANGLE (ATI Radeon HD 3450 (Microsoft Corporation WDDM 1.1)  Direct3D9Ex vs_3_0 ps_3_0)" 
- gl version: "WebGL 1.0 (OpenGL ES 2.0 Chromium)"
- extensions:
	0:"ANGLE_instanced_arrays"
	1:"EXT_blend_minmax"
	2:"EXT_frag_depth"
	3:"EXT_shader_texture_lod"
	4:"EXT_texture_filter_anisotropic"
	5:"WEBKIT_EXT_texture_filter_anisotropic"
	6:"OES_element_index_uint"
	7:"OES_standard_derivatives"
	8:"OES_texture_float"
	9:"OES_texture_float_linear"
	10:"OES_texture_half_float"
	11:"OES_texture_half_float_linear"
	12:"OES_vertex_array_object"
	13:"WEBGL_compressed_texture_s3tc"
	14:"WEBKIT_WEBGL_compressed_texture_s3tc"
	15:"WEBGL_debug_renderer_info"
	16:"WEBGL_debug_shaders"
	17:"WEBGL_lose_context"
	18:"WEBKIT_WEBGL_lose_context"


I'm also attaching the translated shader and fragment hlsl program:
- [shader.txt](https://github.com/highcharts/highcharts/files/2059817/shader.txt)
- [fragment.txt](https://github.com/highcharts/highcharts/files/2059816/fragment.txt)


I found this and wonder if this would explain what I'm observing:
https://steamcommunity.com/app/431960/discussions/1/135512931356560121/

**Comment by manu-st** [comment]
Update, it turns out that it is also happening on a more recent laptop with an Intel i5-6440hq and its native gpu HD Graphics 530.

Both computers are running Windows 7.

**Comment by KacperMadej** [comment]
We are unable to recreate the problem - maybe a demo will help, so please let us know when you will be able to provide one.

**Comment by nilsm0hr** [comment]
We are experiencing the same issue in Google Chome (v 64 and v 69) on Windows 7 32 bit with a fairly old Intel Pentium G630 with second Gen HD Grafics. 

The boost samples/demos and my own code fails in Chrome, but it works in internet explorer. 
I also tried the Override software renderig list setting in Chrome without success. 

Is that just a hardware issue? Or is there a different cause hidden somewhere else? 

![1](https://user-images.githubusercontent.com/25453204/47710184-11ca2e00-dc2a-11e8-960f-d4ed0987a39d.png)

**Comment by cvasseng** [comment]
@nilsm0hr could you try to use this version of the module https://github.highcharts.com/bugfix/boost-shaderfixes/modules/boost.js and see if you're still getting the error?

**Comment by nilsm0hr** [comment]
@cvasseng Hi, build this fiddle https://jsfiddle.net/x5onbakq/ and unfortunately still the same error. 
![pastedimage](https://user-images.githubusercontent.com/25453204/47712832-b2bbe780-dc30-11e8-97b7-69aced024555.png)

**Comment by cvasseng** [comment]
@nilsm0hr thanks for testing. I've tried something else now - does the fiddle still give you issues if you reload it?

I suspect this is a driver problem and/or an issue with the GLSL->HLSL transpiler. I am unable to reproduce it here, so it may require a bit of back and forth to get to the bottom of it.

**Comment by nilsm0hr** [comment]
@cvasseng As I said, we are running on old hardware, however the demo here (https://get.webgl.org/) works. Would the chrome://gpu help? Or any other suggestions to simplify the process?

I did a empty cache and hard reload on the fiddle but still the error message.

**Comment by cvasseng** [comment]
@nilsm0hr sure, the report from chrome://gpu could be helpful. You can send it to support@highcharts.com if you're not comfortable sharing it here. 

Thanks!

**Comment by nilsm0hr** [comment]
Just send the report to the provided mail.

**Comment by lvyv** [comment]
> @nilsm0hr could you try to use this version of the module

> @nilsm0hr could you try to use this version of the module https://github.highcharts.com/bugfix/boost-shaderfixes/modules/boost.js and see if you're still getting the error?

It works for me. Thanks!
