### ISSUE TITLE
MACD doesn't work with shortPeriod: 8 and longPeriod: 16

### ISSUE THREAD

**Issue by faisalferoz** [highcharts/highcharts#8365]
#### Expected behaviour
MACD should work with shortPeriod set to 8 and longPeriod set to 16

#### Actual behaviour
It ends up with an exception
```
[Error] TypeError: undefined is not an object (evaluating 'k[a+b.shortPeriod+1][0]')
	getValues (macd.js:17:174)
	c (indicators.js:10:474)
	init (indicators.js:11:476)
	init (macd.js:13:199)
	initSeries (highstock.js:241:373)
	(anonymous function) (highstock.js:266)
	forEach
	each (highstock.js:28:210)
	firstRender (highstock.js:266)
	(anonymous function) (highstock.js:241:246)
	fireEvent (highstock.js:30:502)
	init (highstock.js:240)
	getArgs (highstock.js:239:471)
	Chart (highstock.js:239:271)
	stockChart (highstock.js:530:358)
	(anonymous function) (_display:81)
	i (jquery-3.1.1.min.js:2:27989)
	fireWith (jquery-3.1.1.min.js:2:28751)
	A (jquery-3.1.1.min.js:4:14215)
	(anonymous function) (jquery-3.1.1.min.js:4:16493)
```

#### Live demo with steps to reproduce
http://jsfiddle.net/90dza0cd/

#### Product version
Highstock 6

#### Affected browser(s)
All

**Comment by faisalferoz** [comment]
I think the issue is here - https://github.com/highcharts/highstock-release/blob/master/indicators/macd.src.js#L408

Where the shortEMA's index is calculated by adding params.shortPeriod and 1 to the iterator index which will result in it being greater then the length of shortEMA array.

The fix should be to make it `i + params.shortPeriod -1` instead.

**Comment by sebastianbochan** [comment]
Hi @faisalferoz,
Thank you for the reporting, I will debug it as soon as possible.
