### ISSUE TITLE
Heatmaps don't work in styled mode

### ISSUE THREAD

**Issue by k-dauda** [highcharts/highcharts#8367]
When you include the styles and override the colors, heatmap points display only one color.
See: https://codepen.io/anon/pen/XqQjyK

**Comment by KacperMadej** [comment]
Hi @k-dauda 

If you want to use styled mode, then load Highcharts and it's modules using
`https://code.highcharts.com/js/ + ...`
as explained here: http://code.highcharts.com/ and here: https://www.highcharts.com/docs/chart-design-and-style/style-by-css
Working demo: https://codepen.io/Blacklabel/pen/YLMamG

For technical support please use any other [support channel](https://www.highcharts.com/support), we are trying to keep the github repository for bugs.
