### ISSUE TITLE
Chart is not displaying if I'm pointing it to my local json data file

### ISSUE THREAD

**Issue by RamDivrania** [highcharts/highcharts#8372]
I'm using same code which is provided in example 'advanced-stock-chart' by replacing data file/code as ::
url: '../../../../../OHCL/Graph/NSE_EQ20MICRONS.json',

my json file (NSE_EQ20MICRONS.json) is as below.

[
[1525631400000,47.00,50.50,46.10,46.65],
[1525717800000,46.50,47.25,45.50,45.75],
[1525804200000,45.65,46.75,45.65,45.90],
[1525890600000,46.70,46.70,45.00,46.00],
[1525977000000,46.10,47.20,45.05,45.35],
[1526236200000,44.25,45.40,44.15,44.35],
[1526322600000,44.65,46.45,44.00,44.75],
[1526409000000,45.00,45.00,43.90,44.30],
[1526495400000,44.20,45.45,42.25,43.30],
[1526581800000,43.45,44.25,42.45,42.55],
[1526841000000,43.55,43.55,41.25,41.45]
]

Please help, I'm new in this area.

Thanks,
Ram

**Comment by RamDivrania** [comment]
If I'm reverting code to as below It's displaying chart properly.
url: 'https://www.highcharts.com/samples/data/aapl-ohlc.json',

**Comment by RamDivrania** [comment]
**Another chart 'candlestick'** is also behaving same while I use my json file,

```
<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Highstock Example</title>
<style type="text/css">
</style>
	</head>
	<body>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="../../code/highstock.js"></script>
<script src="../../code/modules/exporting.js"></script>

<div id="container" style="height: 400px; min-width: 310px"></div>

<script type="text/javascript">
$.getJSON('../../../../../OHCL/Graph/NSE_EQ20MICRONS.json', function (data) {
    // create the chart
    Highcharts.stockChart('container', {
        rangeSelector: {
            selected: 1
        },
        title: {
            text: 'AAPL Stock Price'
        },
        series: [{
            type: 'candlestick',
            name: 'AAPL Stock Price',
            data: data,
            dataGrouping: {
                units: [
                    [
                        'week', // unit name
                        [1] // allowed multiples
                    ], [
                        'month',
                        [1, 2, 3, 4, 6]
                    ]
                ]
            }
        }]
    });
});
		</script>
	</body>
</html>
```

**Comment by KacperMadej** [comment]
Hi @RamDivrania 

Please create a live demo in JSFiddle or provide another way to debug your problem and test possible solutions.

**Comment by RamDivrania** [comment]
Hey @KacperMadej ,
Thank you for your response,
Could you please download my code from below link please?

https://redidirect-my.sharepoint.com/:u:/g/personal/rdivaraniya_stayinfront_com/EQkSWPuJqgxLtukQPjcvMnwBgXP_kLWolwZ7NM-LRnO00w?e=YoNDlQ

Many thanks,
Ram

**Comment by RamDivrania** [comment]
The problem is when I run below Chart
Demo\src\app\candlestick\examples\advanced-stock-chart\index.html   after pointing Demo\OHCL\Graph\NSE_EQ20MICRONS.json data file in index.html (line no : 3206 and 3264) it's not rendering graph,
Bu when I replace that data file with https://www.highcharts.com/samples/data/aapl-ohlc.json it's rendering graph.
I don't know my data file/format is incorrect or something cde change is required.

Thanks,
Ram

**Comment by KacperMadej** [comment]
We are trying to keep github for bugs only - for technical support check: https://www.highcharts.com/support

Demo works fine if it runs from server. Check console errors - make sure those are resolved if you have any and if those are related to Highcharts then you should contact support - https://www.highcharts.com/support

**Comment by RamDivrania** [comment]
Hi,

So It was assumed that it also works fine if it runs from local?
I'm not getting any error that's why I reported here.

Thanks,
Ram
