### ISSUE TITLE
Highstock navigator doesn't respect series.visible option from linked series

### ISSUE THREAD

**Issue by gilmoreorless** [highcharts/highcharts#8374]
#### Expected behaviour

Define a main chart series with `visible` set to `false`. The series should not appear in the main chart or in the navigator, but should produce a legend item. Clicking on the legend item should display the series.

#### Actual behaviour

The series is not visible in the main chart, but is still shown in the navigator. Clicking the legend item toggles the navigator series visibility correctly — it's just the initial data load that produces the inconsistent state.

#### Live demo with steps to reproduce

http://jsfiddle.net/gilmoreorless/xfav4dr5/1/

Note that the black "Hidden by default" series still shows in the navigator.

#### Product version

Tested Highstock 6.0.7 and 6.1.0

#### Affected browser(s)

All

**Comment by sebastianbochan** [comment]
Hi @gilmoreorless 
Please let me know what is the purpose of setting visible as false and showInNavigator as true at the same time? If you need to disable series in navigator, set the showInNavigator as false only.

**Comment by sebastianbochan** [comment]
Hi @gilmoreorless,
Thank you very much for the valuable feedback. I absolutely agree with you that this scenario make sense.

You should declate visiblity also in the `plotOptions.series.navigatorOptions` object.

Demo:
- http://jsfiddle.net/BlackLabel/Lp5hrmrf/

**Comment by gilmoreorless** [comment]
Thanks for the tip, @sebastianbochan — I didn't realise that secondary option was available.

However, setting `series.navigatorOptions.visible` works for the initial render, but causes other problems when showing/hiding the series. I've created a second example with step-by-step details to show some bugs: http://jsfiddle.net/gilmoreorless/5xr5gsk7/1/

I still think the original bug report stands: the navigator series isn't respecting the main series' `visible` option. The correct synchronised behaviour is shown when manually clicking the legend item, or using the `.show()` and `.hide()` API options on a series. But using either the `series.visible` or `series.navigatorOptions.visible` options produces inconsistent results in different scenarios.

**Comment by sebastianbochan** [comment]
Hi @gilmoreorless,
Thank you for demo, now it looks like a bug in my opinion.

**Comment by gilmoreorless** [comment]
Thanks @sebastianbochan. Should this issue be re-opened then?
