### ISSUE TITLE
Issue when resizing a hidden chart div that has padding

### ISSUE THREAD

**Issue by Munksgaard** [highcharts/highcharts#8377]
I have a graph in a div that is sometimes hidden. When resizing the window containing the div while it is hidden, the graph does not come back when the div is shown again. It seems like this only happens if the graph has padding.

Here's an example without padding:

https://jsfiddle.net/k435w62o/3/

If you click `hide`, resize the window a bit and then click `show`, the graph comes back.

Here is an example with padding:

https://jsfiddle.net/k435w62o/2/

Doing the same steps as above, you should see that the graph does not come back when you try to show it again. You can resize the window once more to make it appear. 

#### Product version

Highcharts JS v6.1.0 (2018-04-13) 

#### Affected browser(s)
Chrome and Firefox

**Comment by sebastianbochan** [comment]
Hi @Munksgaard,
Thank you for reporting.

**Workaround**
Call chart.reflow() when chart is show.

Demo:
- https://jsfiddle.net/BlackLabel/endwd8mL/
