### ISSUE TITLE
Calling chart.update with title option overrides responsive rule

### ISSUE THREAD

**Issue by andylhansen** [highcharts/highcharts#8378]
#### Expected behaviour
Chart title should still show value specified in responsive rule after calling chart.update.

#### Actual behaviour
Chart shows the title passed into chart.update()

#### Live demo with steps to reproduce
[https://jsfiddle.net/d27na7k6/2/](https://jsfiddle.net/d27na7k6/2/)
Click "Small"
Click "Large"
Click "Update"

#### Product version
6.1.0 and 5.0.15

#### Affected browser(s)
Chrome. Firefox

**Comment by sebastianbochan** [comment]
Hi @andylhansen,
The `chart.update()` set the highest priority for options and overwrites the all current statement. This is default functionality.

Extra demo:
- https://jsfiddle.net/BlackLabel/L3f3wkdm/

@TorsteinHonsi what do you think, should we consider it as a bug?

**Comment by andylhansen** [comment]
Even if I add the responsive rules into chart.update, it still has the same problem.

[https://jsfiddle.net/d27na7k6/3/](https://jsfiddle.net/d27na7k6/3/)

**Comment by emjaksa** [comment]
I have encountered the same issue as @andylhansen. Even if I set the responsive rules in the update.
