### ISSUE TITLE
Legends and Axis not coming

### ISSUE THREAD

**Issue by snehalseth** [highcharts/highcharts#8380]
i am using high-charts along with react to make charts along with web-pack to bundle up the react app.
while development on the local machine everything works fine but on deployment to the server with the production build the legends and the axis are not coming on the charts. tried different version but no luck.
Tried installing it as dependency and dev-dependency but still no effect.

**Comment by sebastianbochan** [comment]
Hi @snehalseth,
Please let us know how we can replicate the issue or what kind of errors you have.

**Comment by snehalseth** [comment]
there is no issues coming on the console
the graphs renders properly 
but the axis and legends are not coming

**Comment by snehalseth** [comment]
![highcharts](https://user-images.githubusercontent.com/30615846/40542737-0c631d94-603f-11e8-9fc8-01ec88c844f8.png)
this is the final render of it

**Comment by snehalseth** [comment]
got the solution 
there was some problem with the webpack uglify plugin that i was using which was causing this issue
resolved it
