### ISSUE TITLE
Legend symbol with two colors

### ISSUE THREAD

**Issue by danilomcb** [highcharts/highcharts#8383]
I have a chart that depending on the value, has two colors in the series (negative and positive). Is there any way to make highcharts create the symbol of the image above for the legend of the series?

Illustrative graphic image:

![image](https://user-images.githubusercontent.com/4964961/40566525-84796a9c-6047-11e8-8406-07a48e7f6948.png)

**Comment by sebastianbochan** [comment]
Hi @danilomcb,
THe github is our bugtracker, so for the general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

ps. You can render a custom symbol as workaround.
https://stackoverflow.com/questions/36302395/custom-highcharts-legend-symbol
