### ISSUE TITLE
Heatmap charts cannot update data properly

### ISSUE THREAD

**Issue by lotsawa** [highcharts/highcharts#8384]
#### Expected behaviour
On calling `setData` of the heatmap chart, the chart should be updated with new data, with all categories on the y-axis.

#### Actual behaviour
Heatmap chart updates with only one category showing on the y-axis.

#### Live demo with steps to reproduce

https://codepen.io/anon/pen/odKNBM?editors=1010
Click on either button to call `setData` on the chart object.

#### Product version

Highcharts 6.1.0
The issue was not present in version 6.0.7.

#### Affected browser(s)
Tested on Google Chrome Version 66.0.3359.181 (Official Build) (64-bit) for macOS

**Comment by snehalseth** [comment]
you need to use the updatePoints parameter of the setData function to re-render the chart properly

**Comment by sebastianbochan** [comment]
Hi @lotsawa 
Thank you for the reporting. We added a new feature to animate the series when updating data through `Series.setData`, `Series.update` or `Chart.update`. The new logic looks for matching X values and can be disabled through setData's updatePoints option.

Correct demo:
- https://codepen.io/anon/pen/WyejGJ?editors=1010
