### ISSUE TITLE
Scroller functinality missed in latest highstock.js

### ISSUE THREAD

**Issue by anjireddychalla** [highcharts/highcharts#8385]
Highcharts.Scroller.prototype.drawHandle  --- undefined

scroller.elementsToDestroy ---- undefined

second issue:

here .tooltip.label.attr --- undefined

 trendsvw.mainChart = new Highcharts.StockChart(trendsvw.mainChartOptions);

trendsvw.mainChart.tooltip.label.attr({ zIndex: 300 });

**Comment by pawelfus** [comment]
`Highcharts.Scroller` class was replaced with `Highcharts.Navigator`. 

`tooltip.label` is not defined when using `tooltip.split` (true by default). `tooltip.label` is defined only in shared/non-shared tooltips.
