### ISSUE TITLE
Highsoft.Highcharts ASP NET CORE 2.0 Compatibility

### ISSUE THREAD

**Issue by alextof** [highcharts/highcharts#8386]
#### Expected behaviour
Highsoft.HighCharts to be compatible with ASP NET CORE 2.0 

#### Actual behaviour
Highsoft.HighCharts not compatible with ASP NET CORE 2.0 

#### Live demo with steps to reproduce

No demo

#### Product version

Nuget --> Highsoft.Highcharts 6.1.0.33

#### Affected browser(s)
C# View Server Side Issue.

#### Pictures
![image](https://user-images.githubusercontent.com/39694295/40607069-ac5e904c-6267-11e8-8516-acc5d79c87e3.png)

![image](https://user-images.githubusercontent.com/39694295/40607090-c05086d2-6267-11e8-8438-1feca2a67eb6.png)

**Comment by sebastianbochan** [comment]
Hi @alextof,
Thank you for the report.
I have passed your case to our .NET developers and when I will let you know when get any feedback.

**Comment by alextof** [comment]
Thank you! It would be great to have Core 2.0 with Highcharts, nowadays slowly everything is being programmed with it, the adoption is currently in progress.

**Comment by NibblyPig** [comment]
We just just bought a license for this and it is referencing `HtmlString` in MVC, which exists in a different location in Core 2.  Googling the issue has led only to this. A year has passed, is it compatible with Core 2 now?

**Comment by pawelfus** [comment]
Hi @NibblyPig 

We are working on it. ETA: within two weeks

**Comment by pawelfus** [comment]
New version of the wrapper was just released, see details:
- http://dotnet.highcharts.com/Highcharts/Demo/Docs?section=UpgradeToStandard
- http://dotnet.highcharts.com/Highcharts/Demo/Docs?section=Core
