### ISSUE TITLE
Annotations are not exported if added dynamically 

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#8393]
#### Expected behaviour
Annotations should be exported when added dynamically just like they are exported when added in initial chart options.

#### Actual behaviour
Annotations are not visible on exported chart if added dynamically

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8d1xa85o/1/

#### Product version
Highcharts 6.1.0

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
The `addAnnotation` function must probably also add it the the chart annotation _options_ in order for it to be picked up by the export. The same applies to `removeAnnotation`. 

On a side note, there seems to be an `Annotation.update` function missing.

**Comment by sebastianbochan** [comment]
@morganfree 
Any comments?
