### ISSUE TITLE
API documentation for custom easing function in plotOptions.series.animation in not complete

### ISSUE THREAD

**Issue by pieniazek** [highcharts/highcharts#8395]
#### Expected behaviour
API documentation for [plotOptions.series.animation](https://api.highcharts.com/highcharts/plotOptions.series.animation) should also mention possibility to provide a function instead of only "A string reference to an easing function set on the Math object." as a custom easing function.

Code reference:
https://github.com/highcharts/highcharts/blob/f47dfac813d05ee6eadd24403e4d48ad89ef28c2/js/parts/Utilities.js#L1922-L1924

#### Actual behaviour
Only "A string reference to an easing function set on the Math object." is mentioned in the API documentation as option to customise easing function

#### Live demo with steps to reproduce
http://jsfiddle.net/yw9ujybk/ - example using function instead of string reference

#### Product version
Highcharts version: N/A

#### Affected browser(s)
N/A

**Comment by KacperMadej** [comment]
Hi @pieniazek 

Thank you for reporting about the problem.
