### ISSUE TITLE
Sunburst chart: Color variation(color spread) should be distinctly for positive data values seen on the chart ignoring the null data values

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#8396]
#### Expected behaviour
It is expected that color variation should be applied only to positive data values seen on the chart with distinct color spread, ignoring the null data values.

#### Actual behaviour
Consider the following JS Fiddle: http://jsfiddle.net/amrutaJgtp/d9b29qnw/7/
Here, all datapoints have positive values and color variation is seen distinctly amongst the nodes of leaf level.
Now, consider a JS Fiddle: http://jsfiddle.net/amrutaJgtp/d9b29qnw/8/
Here, the number of datapoints having null values > datapoints having positive values. Hence all nodes on the leaf level appear to have same color as compared to that in the above fiddle.

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard We need to filter out null points when we compute index and siblings here:

https://github.com/highcharts/highcharts/blob/88c0013b0d8a1447fe477af151e64002f59f0ecf/js/mixins/tree-series.js#L48-L52
