### ISSUE TITLE
Broken examples on documentation

### ISSUE THREAD

**Issue by Menighin** [highcharts/highcharts#8399]
Some `Highmaps` examples do not load on JS Fiddle, like the ones for [`colorAxis.dataClasses`](https://api.highcharts.com/highmaps/colorAxis.dataClasses). They keep loading and loading.
The network tab on Chrome shows everything was loaded right and no error is logged on the console.

**Comment by KacperMadej** [comment]
Hi @Menighin 

Thank you for reporting about the problem.
It's already resolved in the next release candidate, so it should be published with next release.
Demos:
- http://jsfiddle.net/BlackLabel/ae499gto/
- http://jsfiddle.net/BlackLabel/m38yr969/
