### ISSUE TITLE
 How to set the axis color of 3D column chart

### ISSUE THREAD

**Issue by Alexander-txj** [highcharts/highcharts#8401]
v 6.0.7

Invalid use of lineColor

**Comment by Alexander-txj** [comment]
I found that the 3D figure is not the axis, is the gridLine

**Comment by pawelfus** [comment]
Hi @Alexander-txj 

Thanks for contacting us, but if you have questions please use our forum, stackoverflow or simply contact us by email. We use github issues as bug reports. Thanks!
