### ISSUE TITLE
Boost.js not working properly for Bubble Chart

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#8402]
I am trying to render bubble chart using boostjs, but seem to be not working properly.
I have also set **series.boostThreshold** property.

http://jsfiddle.net/tejaspchordiya/e95tubr6/

**Comment by pawelfus** [comment]
Hi @tejaspchordiya 

Thank you for reporting this bug! It looks like bug comes from missing `z` params for a point, when setting those: http://jsfiddle.net/e95tubr6/1/ - works fine.

**Comment by amruta30** [comment]
Consider a case of plotting bubble chart without using boost.js
https://jsfiddle.net/amrutaJgtp/hmvfrwa9/
Above JS fiddle shows that, on removing z param from the datapoint, bubbles are not seen.

However, in Highcharts v6.0.6 - z param in bubble chart datapoint was optional.
Example: https://jsfiddle.net/amrutaJgtp/hmvfrwa9/1/

Backward compatibility should be supported.

**Comment by KacperMadej** [comment]
@amruta30 If you require bubble type series without z set you could use scatter with defined marker sizes. Your request is not the same as the issue you commented on, so if you want to suggest an enhancement or report a bug please open a new issue.

**Comment by amruta30** [comment]
@KacperMadej  I have opened a new issue : https://github.com/highcharts/highcharts/issues/8608
