### ISSUE TITLE
Highchart error render first and last value of columns

### ISSUE THREAD

**Issue by jmsalai99** [highcharts/highcharts#8403]
We can view the highchart error render first and last value of columns, if the chart type is line it works well but columns not render correctly.

An exemple:
https://jsfiddle.net/jmsalai/p8n9707t/

How to correct these chart ?

**Comment by pawelfus** [comment]
Hi @jmsalai99 

This is how chart with your config should look like. Each point is in a  separate series, so each series reserves space for more points. If you have one point per series, always, you can disable this by setting [`series.grouping`](https://api.highcharts.com/highcharts/series.column.grouping) to false and providing information about point range (~20minutes in your case), demo for you: https://jsfiddle.net/p8n9707t/1/

**Comment by jmsalai99** [comment]
Ok thank you very much !!

But when the chart is small the columns overlap each other.

Exemple:
https://jsfiddle.net/jmsalai/kozcsc36/


How can I correct it?

**Comment by pawelfus** [comment]
You can calculate this, for example: https://jsfiddle.net/BlackLabel/kozcsc36/2/

@TorsteinHonsi - maybe we should add this as an option like `pointRangeFromAllSeries` to cover this common use case?
