### ISSUE TITLE
Add series.symbolUnicode property for easy tooltip formatting

### ISSUE THREAD

**Issue by ciarancourtney** [highcharts/highcharts#8404]
PR https://github.com/highcharts/highcharts/pull/8405

#### Expected behaviour

As per [this ](https://stackoverflow.com/questions/25973920/how-to-display-highchart-series-line-marker-symbol-from-tooltip-formatter) popular SO question, it would be nice if the tooltip symbol matched the actual chart symbol, and if this was available as a Unicode character, this could be achieved using `pointFormat`

#### Actual behaviour

    pointFormat = '{series.symbol} {point.y}';

Using the above, you will get `circle 123` or `diamond 123` in the tooltip, not very useful

    pointFormat = '{series.symbolUnicode} {point.y}';

Using the above, you could get `● 123` or `♦123` in the tooltip, which you can color appropriately

#### Live demo with steps to reproduce
current `symbol` example http://jsfiddle.net/w6yvxpzh/

Proposed `symbolUnicode` example http://jsfiddle.net/pjqz79pv/ (will work when GA)

#### Product version
Highcharts v6.1.0

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
A lightweight solution would be to hook up to the `afterInit` event and add the symbols:

```js
Highcharts.addEvent(Highcharts.Series, 'afterInit', function () {
	this.symbolUnicode = {
    	circle: '●',
        diamond: '♦',
        square: '■',
        triangle: '▲',
        'triangle-down': '▼'
    }[this.symbol] || '●';
});
```

View live demo: http://jsfiddle.net/pjqz79pv/1/

**Comment by ciarancourtney** [comment]
That works, thanks @TorsteinHonsi
