### ISSUE TITLE
Treemap first renders incorrectly when yAxis is added via addAxis

### ISSUE THREAD

**Issue by anajavi** [highcharts/highcharts#8406]
#### Expected behaviour
The treemap should render correctly on first render. When yAxis is added in chart config this happens.

#### Actual behaviour
The first render doesn't set colors and legend. After resizing window, the colors and legend display correctly.

#### Live demo with steps to reproduce
https://jsfiddle.net/brdjj8y7/3/

First the colors are all black, and legend does not show numbers. After resizing window the chart renders with blue colors and legend with numbers

#### Product version
Highcharts 6.1.0

#### Affected browser(s)
Tested: Chrome latest, Safari latest

**Comment by KacperMadej** [comment]
Hi @anajavi 

Thank you for reporting about the problem.

As a workaround you could set min and max for the color axis - https://jsfiddle.net/BlackLabel/brdjj8y7/4/
