### ISSUE TITLE
Tooltip useHtml=true, split = true not working in Highstock 6.1.0

### ISSUE THREAD

**Issue by jphamilton** [highcharts/highcharts#8408]
This issue is related to https://github.com/highcharts/highcharts/issues/7238

#### Expected behaviour 
Version 5.0.13
![highstock5](https://user-images.githubusercontent.com/19796/40733281-d40e2e24-63fa-11e8-9c53-a71526840795.png)

#### Actual behaviour
Version 6.1.0
![split-true](https://user-images.githubusercontent.com/19796/40733630-bba05e88-63fb-11e8-9829-d0ee58b40b6e.png)

If I change split=false, I get this, but it's still not what I need:
![highstock6](https://user-images.githubusercontent.com/19796/40733300-df6b68ea-63fa-11e8-8c56-33be16bc7c4c.png)

I need all values that occur at the same time to display in the table.

#### Affected browser(s)
All

Is it no longer possible to achieve the expected behavior with v.6?

**Comment by TorsteinHonsi** [comment]
You probably want to set `shared` to `true`.

**Comment by jphamilton** [comment]
@TorsteinHonsi You are a saint! That works.

In case someone else needs this info, to get the expected behavior you need:
```
useHTML: true,
shared: true,
split: false
```

**Comment by lumberg72** [comment]
Although not specifically stated, as far as I can tell, useHtml=true with split=true is not supported. Is that correct?
In other words, when split=true, useHtml=true is ignored?
