### ISSUE TITLE
Remove Spacing between errorbar and column types

### ISSUE THREAD

**Issue by Andriy-Kulak** [highcharts/highcharts#8412]
How do I remove the small spacing that happens between end of some columns and beginning of some errorbars?

The reason I ask is because it only happens sometimes, and both the column data and errorbar start value are the same, yet they sometimes have these gaps that I cannot figure out how to get rid of. (as you can see in one screenshot both values are `1,129,526` yet they have a gap between them. 
![equalvalues](https://user-images.githubusercontent.com/12179976/40751101-c65523ea-6437-11e8-9446-5fe91eac54fb.png)
![screenshotofgaps](https://user-images.githubusercontent.com/12179976/40751102-c65e5686-6437-11e8-8948-9d92cb2afde0.png)

I can't seem to get the react version to get to work in jsfiddle unfortunately, but I assume this is a common issue. I haven't been able to find anything in the API that addresses this so maybe someone can provide some suggestions! Thanks!

#### Product version
Highcharts v6.1.0

**Comment by sebastianbochan** [comment]
Hi @Andriy-Kulak,
Thank you for the reporting.

Simplified demo: 
- https://jsfiddle.net/y1ms55at/
