### ISSUE TITLE
x-axis labels are not visible when type set to category and parseDate method doesn't trigger when type set to datetime

### ISSUE THREAD

**Issue by mike-code** [highcharts/highcharts#8414]
#### Expected behaviour

1. The x-axis labels should be shown whether I'm using array or object with `x`,`y` parameters.
2. The `parseDate` method should trigger when parsing datetime labels

#### Actual behaviour

1. The x-axis labels are shown only when array of values is passed otherwise they are not visible
2. The parseDate method never triggers which makes me unable to properly parse datetime string into epoch timestamp

#### Live demo with steps to reproduce

https://jsfiddle.net/8wjop0v7/

#### Product version
6.1.0

#### Affected browser(s)

All

**Comment by pawelfus** [comment]
Hi @mike-code 

Thanks for reporting the issue. The `data.parseDate` callback is part of `data.js` module, from the API: https://api.highcharts.com/highcharts/data

> The Data module provides a simplified interface for adding data to a chart from sources like CVS, HTML tables or grid views. See also the tutorial article on the Data module.
> 
> It requires the modules/data.js file to be loaded.
> 
> Please note that the default way of adding data in Highcharts, without the need of a module, is through the series.data option.

In short, `data.parseData` is called when data is loaded from CSV/ HTML table, not when applying `series.data` options in JS. If you want `datetime` axis, then use timestamps as x-values: https://jsfiddle.net/BlackLabel/8wjop0v7/1/

**Comment by mike-code** [comment]
Thanks
