### ISSUE TITLE
crosshair formatter doesn't have  x,y values

### ISSUE THREAD

**Issue by ourarash** [highcharts/highcharts#8416]
#### Expected behaviour
crosshair formatter to provide these:

> 

this.percentage | Stacked series and pies only. The point's percentage of the total.
-- | --
this.point | The point object. The point name, if defined, is available through this.point.name.
this.series: | The series object. The series name is available through this.series.name.
this.total | Stacked series only. The total value at this point's x value.
this.x: | The x value.
this.y: | The y value.

#### Actual behaviour
All values are undefined

#### Live demo with steps to reproduce
http://jsfiddle.net/d5acqyu3/1/

#### Product version

Highstock latest

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
The context of the crosshair formatter is the axis, so none of these properties are defined. The first argument is the Y value. If we were to pass over this labelConfig, I think it would need to be as the second argument.
