### ISSUE TITLE
Stacked column chart appears transparent when converted to 3D on update

### ISSUE THREAD

**Issue by oluwasayo** [highcharts/highcharts#8417]
When a stacked column chart is updated to 3D it becomes transparent, making the innards of the stacks visible.

#### Expected behaviour
![screen shot 2018-06-01 at 11 20 41 am](https://user-images.githubusercontent.com/900868/40830211-76f61a4a-658e-11e8-8b9a-e8febe5deaf8.png)

#### Actual behaviour
![screen shot 2018-06-01 at 11 20 15 am](https://user-images.githubusercontent.com/900868/40830220-7edcadf0-658e-11e8-80d9-302b032e11d3.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/ywaxzhtg/3/
- Run Fiddle
- Click "Update" (to observe the actual behavior)
- Uncomment the commented section and run (to observe the expected behavior)

#### Product version
Highcharts/Highstock: 5, 6

#### Affected browser(s)
[x] Chrome
[x] Firefox
[x] Safari

#### More examples 
Stacked column chart
<img width="539" alt="screen shot 2018-06-01 at 11 49 14 am" src="https://user-images.githubusercontent.com/900868/40831617-2407abb0-6592-11e8-87bc-b1e5d62392f9.png">

Hover on first column
<img width="510" alt="screen shot 2018-06-01 at 11 49 20 am" src="https://user-images.githubusercontent.com/900868/40831638-2fd5dd18-6592-11e8-815d-445da2d7f5d0.png">

**Comment by KacperMadej** [comment]
Hi @oluwasayo 

Thank you for reporting about the problem.

**Comment by Izothep** [comment]
Hi @oluwasayo 

Thank you for providing us with detailed information about your issue. It looks that the issue you have reported is related to creating series.group in 2D charts. When charts are updated to 3D these groups still exist which results in the bug in zIndex calculation for different series.

Simple workaround: http://jsfiddle.net/BlackLabel/ywaxzhtg/6/

**Comment by oluwasayo** [comment]
Hi @Izothep,

Thanks for the workaround! Applying it seems to have introduced an issue.

Scenario:
- Chart on page, updated to 3D (works fine with workaround)
- Discard chart and create a new one (non 3D) on the same page

Result:
<img width="563" alt="screen shot 2018-06-14 at 2 49 06 pm" src="https://user-images.githubusercontent.com/900868/41410608-a6810bcc-6fe2-11e8-9843-b59b17ed88e5.png">

**Comment by pawelfus** [comment]
@oluwasayo - just tested: http://jsfiddle.net/BlackLabel/ywaxzhtg/8/ - could you update my demo to show the issue?
