### ISSUE TITLE
view data:data start、end is different from chart start、end

### ISSUE THREAD

**Issue by dolphinfine** [highcharts/highcharts#8421]
#### Expected behaviour
chart start is the same with data start，so end is

#### Actual behaviour 
data start、end is different from chart start、end
#### Live demo with steps to reproduce
https://jshare.com.cn/highstock/hhhhio/45

#### Product version
Highstock JS v6.1.0 (2018-04-13)
export-csv Version:  1.4.8

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Hi @dolphinfine 

Could you contact our support? `export-csv Version: 1.4.8` plugin is a very old module, official release is v6.1.0 as an official module from: https://code.highcharts.com/modules/export-data.js

Closing as duplicate of #7913
