### ISSUE TITLE
Series mouseOver event does not work for div manipulation

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#8423]
Please refer the fiddle below. It consists of a treemap with click, mouseOver and mouseOut events attached to the series. The mouseOver event displays the point name in #info div. The mouseOut event hides this div.

#### Expected behaviour
The series mouseOver event should work correctly across all browsers. The point name should be displayed correctly.

#### Actual behaviour
The mouseOver event handler does not work properly in IE 11. Also, the click event does not work. Moreover, when this #info div is placed below the chart div, it works correctly (see fiddle below). Both fiddles work properly in Chrome.

#### Live demo with steps to reproduce
With #info div above chart container (Does not work): http://jsfiddle.net/xdg6y855/
With #info div below chart container (Works): http://jsfiddle.net/xdg6y855/1/

#### Affected browser(s)
Internet Explorer 11

**Comment by KacperMadej** [comment]
Hi @sagargurtu 

Thank you for reporting about the problem.

Workaround: use `setTimeout` - http://jsfiddle.net/xdg6y855/5/

Looks like events that are changing DOM elements (also tested without jQuery) are triggering mouseOut event for IE11.

**Comment by sagargurtu** [comment]
@KacperMadej Another workaround is to set stickyTracking to true
