### ISSUE TITLE
Second y Axis not set up in chart

### ISSUE THREAD

**Issue by YahiaZZ** [highcharts/highcharts#8425]
Hi, 
I add two series to my Chart in order to have two separate yAxis
but it add the two series to the same yAxis

```
$(document).ready(function() {
	    chart3 = new Highcharts.Chart({
	        chart: {
	            renderTo: 'container3',
	            type: 'spline',
	            alignTicks: false,
				zoomType: 'xy'
	        },
	        title: {
	            text: 'Combined'
	        },
	        
			tooltip: {
				headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
				pointFormat: '<tr><td style="color:{series.color};padding:0"> </td>' +
					'<td style="padding:0"><b>{point.y:,.2f}</b></td></tr>',
				footerFormat: '</table>',
				shared: true,
				useHTML: true
			},
               credits: {
            		enabled: false
            	},
	        xAxis: {
	            type: 'datetime',
	            tickPixelInterval: 150,
	            maxZoom: 20 * 1000
	        },
	        yAxis: [{
	        	title: {
	                text: 'Temperature (C)'
	            },
	            
	        },{
	        	opposite: true,
	        	title: {
	                text: 'Pressure (Pa)'
	            },
	            
	        }],
	        series: []
	    });        
	});
```
the result is like this
![image](https://user-images.githubusercontent.com/13751183/40916343-e734c4a2-67ee-11e8-9744-0cd90dea6293.png)

Thanks in advance

**Comment by sebastianbochan** [comment]
Hi @YahiaZZ,
In the each series object you need to declare the yAxis index.
Could you paste your series object to verify the structure.

**Comment by YahiaZZ** [comment]
Hi @sebastianbochan 
Thank you for your quick answer,
I add series like 
```
var newseries = {
		            id: y,
		            name: message.destinationName,
					color:"#ef5256",
					showInLegend: false,
		            data: []
		            };
var newseries2 = {
		            id: y,
		            name: message.destinationName,
					color:"#DDDF00",
					showInLegend: false,
		            data: []
		            };
chart3.addSeries(newseries); 
chart3.addSeries(newseries2);
thanks
```

**Comment by sebastianbochan** [comment]
Hi @YahiaZZ 
You should declare yAxis index, like below : 

var newseries = {
		            id: y,
		            name: message.destinationName,
					color:"#ef5256",
yAxis: 0,
					showInLegend: false,
		            data: []
		            };
var newseries2 = {
		            id: y,
yAxis: 1,
		            name: message.destinationName,
					color:"#DDDF00",
					showInLegend: false,
		            data: []
		            };

For the further [support](http://www.highcharts.com/support) questions, please use stackoverflow / forum or email.

**Comment by YahiaZZ** [comment]
Thank you @sebastianbochan

**Comment by YahiaZZ** [comment]
Hi @KacperMadej 
It was an instance of series and those are populated dynamically,
Sebastian's solution resolve the problem
Thanks

**Comment by KacperMadej** [comment]
@YahiaZZ  I haven't refreshed the site - it refreshed after posting (and this is why my first comment here is now removed). Sorry for the confusion.
