### ISSUE TITLE
Pie chart slice does not display properly when visibility changes

### ISSUE THREAD

**Issue by whawker** [highcharts/highcharts#8428]
#### Expected behaviour
Calling `setData` on Pie chart series, changing the `visible` property on one of the Pie slices. 
Previously hidden slice is then displayed.

#### Actual behaviour
Slice is loaded, and takes up space, but has no background colour.

#### Live demo with steps to reproduce
https://jsfiddle.net/hn8tgerq/
Then click on "Show Chrome Usage" button

#### Product version
Highcharts 6.1.0

#### Affected browser(s)
Chrome latest, Firefox latest, Safari latest (assume all)

**Comment by sebastianbochan** [comment]
Hi @whawker,
Thank you for reporting.

**Simplified demo:**
- https://jsfiddle.net/sd1z4nr9/
