### ISSUE TITLE
^6.0.5 Bar chart xAxis category labels wrap and overlap if too long

### ISSUE THREAD

**Issue by emiliano-ponce** [highcharts/highcharts#8429]
#### Expected behaviour
Bar chart xAxis labels should not overlap.

#### Actual behaviour
Bar chart xAxis labels overlap.

#### Live demo with steps to reproduce
http://jsfiddle.net/xzw439fn/10/

Change the version here: `<script src="https://code.highcharts.com/6.0.4/highcharts.js"></script>` from 6.0.4 to anything higher, and long category label(s) on the xAxis will wrap and overlap.

#### Product version
Highcharts v6.0.5 (anything above 6.0.4)

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @emiliano-ponce 

Thank you for reporting this bug, it's fixed on our master branch: http://jsfiddle.net/BlackLabel/xzw439fn/14/ by https://github.com/highcharts/highcharts/commit/4cb1efc58 commit.

**Comment by emiliano-ponce** [comment]
Hi @pawelfus 

I believe your shim repo needs to be updated then. I have installed the latest version using npm and the issue is present.

Checked the commit you referenced and that was completed on May 3rd. 

The last commit for https://github.com/highcharts/highcharts-dist was Apr 13th.

**Comment by pawelfus** [comment]
ETA is not specified yet, I would expect a release within two-three weeks.
