### ISSUE TITLE
Sunburst chart is not rendered if id of any datapoint is set as ''

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#8432]
#### Expected behaviour
Sunburst chart should be rendered successfully. All other highcharts charts are rendered even if any datapoint contains id : ''

#### Actual behaviour
Sunburst chart is not rendered if id of any datapoint is set as ''.

#### Live demo with steps to reproduce
https://jsfiddle.net/4td8ucy6/6/

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @amruta30,
Thank you for reporting.

**Workaround**
Set id as undefined.
Demo:
- https://jsfiddle.net/j4n3vac7/

**Internal note**
The empty string causes Maximum call on stack.
