### ISSUE TITLE
Getting error bar data from CSV

### ISSUE THREAD

**Issue by roatesTag** [highcharts/highcharts#8434]
We're trying to load chart data from CSV files and are struggling with data for error bars. 
We tried using a single column (with "low, high" data format) and separate columns for low and high (similar to how the export-data module outputs).
Does Highcharts' data module support parsing CSV data for error bars or do we need to use an alternative, like Papa Parse, to load the series data?

**Comment by sebastianbochan** [comment]
Hi @roatesTag,
The github is our bugtracker for reporting bugs. For general [support]() questions, please use stackoverflow / forum or email.
