### ISSUE TITLE
How do I control histogram width when data is small?

### ISSUE THREAD

**Issue by yyb1994** [highcharts/highcharts#8435]
#### Expected behaviour
When data is scarce, can I control the width of histogram?
Let the display be like second pictures

#### Live demo with steps to reproduce

http://jsfiddle.net/xa8ozfmL/7/

![](https://s22.postimg.cc/b0qtjmu9t/image.png)

![2](https://user-images.githubusercontent.com/17470456/41089803-4cbe9b94-6a75-11e8-8bad-5fbf206f8cb1.png)

**Comment by pawelfus** [comment]
Hi @yyb1994 

You can use one of the given options:

- fixed [`series.pointWidth`](https://api.highcharts.com/highstock/plotOptions.candlestick.pointWidth)
- fixed maximum point's width: [`series.maxPointWidth`](https://api.highcharts.com/highstock/plotOptions.candlestick.maxPointWidth)
- dynamic [`series.pointPadding`](https://api.highcharts.com/highstock/plotOptions.candlestick.pointPadding) and [`series.groupPadding`](https://api.highcharts.com/highstock/plotOptions.candlestick.groupPadding)
