### ISSUE TITLE
broken demo - how to add custom mouse events?

### ISSUE THREAD

**Issue by orouz** [highcharts/highcharts#8437]
#### Expected behaviour

when clicked, we should get the normalised mouse position of the click event

#### Actual behaviour

it throws when you click the chart 
`Cannot read property 'touches' of undefined`

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/members/chart-callback/

got there from your article about [extending highcharts - hooking to init](https://www.highcharts.com/docs/extending-highcharts/extending-highcharts)

**Comment by sebastianbochan** [comment]
Hi @orouz,
The problem is caused by missing event `e`. To do that, add  reference to `e` in `normalize()` function.

The code:
```
(function (H) {
    Highcharts.Chart.prototype.callbacks.push(function (chart) {
        H.addEvent(chart.container, 'click', function (e) {
            e = chart.pointer.normalize(e);
            $('#report').html('Clicked chart at ' + e.chartX + ', ' + e.chartY);
        });
        H.addEvent(chart.xAxis[0], 'afterSetExtremes', function (e) {
            $('#report').html('Set extremes to ' + e.min.toFixed(2) + ', ' + e.max.toFixed(2));
        });
    });
}(Highcharts));
```

Demo:
- http://jsfiddle.net/zywuLg2n/

For general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

**Comment by sebastianbochan** [comment]
Fixed by commit https://github.com/highcharts/highcharts/commit/1ad523ed6fbb5e4808a3839de6ec3610c1fef70e
