### ISSUE TITLE
桑基图转化条怎么显示百分比？

### ISSUE THREAD

**Issue by ShawshankLin** [highcharts/highcharts#8439]
桑基图转化条怎么显示百分比？

**Comment by ShawshankLin** [comment]
How does the sankey conversion bar show percentages?

**Comment by sebastianbochan** [comment]
Hi @ShawshankLin,
The github is our bugtracker, so for general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

**Comment by hurrine** [comment]
Can use "pointFormatter", for example:

        tooltip: {
          pointFormatter: function (this: any) {
            return `
              <div>
                <div>${this.fromNode.name} → ${this.toNode.name}: <b>${this.weight}</div><br/>
                <b>
                ${(this.weight / this.toNode.sum * 100).toFixed(2)} % of ${this.toNode.name} target
              </b>
              </div>
            `;
          }
        },
