### ISSUE TITLE
Flag load event 

### ISSUE THREAD

**Issue by ozgurbircan** [highcharts/highcharts#8441]
#### Expected behaviour
Hi, I want to flag the "load event" flag on the chart.

#### Actual behaviour

series: [{
            name: 'USD to EUR',
            data: data,
            id: 'dataseries',
                        events: {
                **load: function()** {
                for(var i=0;i<1;i++)
                {
                    this.chart.series[1].addPoint({
                        x: 1512691200000,
                        title: 'Down'
                    });}
                }

            }
            

        // the event marker flags
        }, {
            type: 'flags',
            data: [],
            onSeries: 'data',
            shape: 'squarepin'
        }]
#### Live demo with steps to reproduce
https://jsfiddle.net/ywjxbhLv/6/

**Comment by ozgurbircan** [comment]
I want the flag to be displayed when the graphic is loaded, not by clicking on the graph.

**Comment by pawelfus** [comment]
Hi @ozgurbircan 

There's no `series.events.load` event, see API: https://api.highcharts.com/highstock/plotOptions.series.events

Probably you want to use `chart.events.load`: https://api.highcharts.com/highstock/chart.events.load

Demo: https://jsfiddle.net/BlackLabel/ywjxbhLv/8/

**Comment by ozgurbircan** [comment]
omg  thx my friend :dagger:
