### ISSUE TITLE
Axis title renders an extra 'title' tag when text is wrapped in 2 or more lines

### ISSUE THREAD

**Issue by LittleHendrix** [highcharts/highcharts#8444]
#### Expected behaviour
Axis title is rendered in `<Text><tspan>` tags. 

#### Actual behaviour
When the title is wrapped in 2 or more lines, an extra `<title>` tag is added for some reason

Is there a way to always have the `<title>` tag? or permanently disable it?

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! The title tag is intended to appear when the text is clipped, but not when wrapped.
