### ISSUE TITLE
Rate of change tooltip is wrong

### ISSUE THREAD

**Issue by ourarash** [highcharts/highcharts#8445]
#### Expected behaviour
Tooltip to show the period  correctly based on the value of period:
`params: {
                period: 5
            }`

It should show:

`Rate of Change(50)`

#### Actual behaviour
Always shows 9:

`Rate of Change(9)`

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/stock/indicators/roc/

#### Product version

Latest

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @ourarash 

Thanks for reporting this bug.

**Workaround:**
Set `series.name = null` and name will be auto-generated: http://jsfiddle.net/BlackLabel/zqhfjLdo/
