### ISSUE TITLE
Dynamically  data json url 

### ISSUE THREAD

**Issue by ozgurbircan** [highcharts/highcharts#8446]
#### Expected behaviour

Hi, I want to show the data from json at 60 seconds.
#### Actual behaviour
    events: {
      load: function () {
    // set up the updating of the chart each second
        
        var series = this.series[0];
        setInterval(function () {
          $.getJSON("data.json", function(json) { getjson not working.
        let d = json.results;
        //var l=data[0].series[0].deger
        let l=d[0].series[0].values;
          var x = l[0], // current time
            y = l[1];
          series.addPoint([x, y], true, true);
        });}, 60000);
      }
    }
  },

#### Live demo with steps to reproduce

https://jsfiddle.net/6xbtg9f8/

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
