### ISSUE TITLE
Setting custom navigator.xAxis.id does not work

### ISSUE THREAD

**Issue by piotriwojcik** [highcharts/highcharts#8450]
#### Expected behaviour
 It should be possible to set `chart.navigator.xAxis.id` similarly to setting `chart.xAxis.id`:
```
...
    xAxis: {
    	id: "axis1"
    },
    navigator: {
    	xAxis: {
      	id: "axis2"
      }
    },
...
```
so that calling `chart.get("axis1")` and `chart.get("axis2")` worked as expected.

#### Actual behaviour
Custom id value is overwritten by the default string: "navigator-x-axis" and `chart.get("axis2")` returns `undefined`.

#### Live demo with steps to reproduce
http://jsfiddle.net/3vmn3wfh/80/

#### Product version
Highstock, master

**Comment by pawelfus** [comment]
Thanks for reporting!

*Internal note:*
It seems that we use this ID for linking series in navigator to xAxis and yAxis. Should this be described in [API](https://api.highcharts.com/highstock/navigator.xAxis.id). @oysteinmoseng any thoughts.
