### ISSUE TITLE
null matrix positioning bug

### ISSUE THREAD

**Issue by hoshmn** [highcharts/highcharts#8456]
Hi there,

Is there a need to set this null here? We wrote a plugin to enable images to be used as axis labels, but this was causing them to be positioned in the upper left of the chart, despite `position` also including the appropriate x and y coords (in fact, this would occur even with `matrix: undefined`). Is there a reason to set this at all (/a reason the SVG renderer--or whatever is positioning elements--should be checking whether `position` has the property `matrix` rather than checking that the value isn't nil?)?

We worked around this with another plugin to delete the property, but making `fix3dPosition` a prototype method (and therefore wrappable) would also be nice.

It's difficult to provide repro steps or a demo because this only affected the positioning of images--text labels were not mis-positioned due to the `matrix: null` setting.

Thanks,
Josh

https://github.com/highcharts/highcharts/blob/1477eac80e6fd3f108533f3a85d40139f5f63fd5/js/parts-3d/Axis.js#L426

**Comment by KacperMadej** [comment]
Hi @hoshmn 

Thank you for reporting about the issue.

We can run tests and check is a suggested solution / change will work and won't break anything. Just to be on the same page - `delete projected.matrix` instead of `projected.matrix = null` is what you are looking for?

**Comment by hoshmn** [comment]
Actually simpler than that, you could just remove the else case of setting `projected.matrix = null` entirely--`projected` does not have a `matrix` property at that point, so there's no need to delete it. Thanks!
