### ISSUE TITLE
how to add an annotation to the last point in candlestick plot?

### ISSUE THREAD

**Issue by lvze1992** [highcharts/highcharts#8457]
#### Expected behaviour
I just can't add an annotation to the last point. please give me some suggestion. I gave my code below.
<img width="227" alt="2018-06-12 3 26 06" src="https://user-images.githubusercontent.com/14118535/41275990-53dd5864-6e55-11e8-9706-68c8c337b528.png">

#### Actual behaviour
![2018-06-12 3 29 26](https://user-images.githubusercontent.com/14118535/41276051-80ee031c-6e55-11e8-9fe9-70656eea4b20.png)

#### Live demo with steps to reproduce

https://jshare.com.cn/temp/PtScGi/1

**Comment by sebastianbochan** [comment]
Hi @lvze1992,
Thank you for contacting us. The github is our bugtracker and for general [support](http://www.highcharts.com/support) qestions, please use forum / stackoverflow or email.
