### ISSUE TITLE
Y-axis stackLabels alignment issue

### ISSUE THREAD

**Issue by VBIManonmaniM** [highcharts/highcharts#8461]
#### Expected behaviour
When stacked bar chart used with stacklabel's it should align with the bar

#### Actual behaviour
When stacked bar chart used with stacklabel's but it doesn't align with chart.
It is happening only in 6.1.0.

#### Live demo with steps to reproduce

https://jsfiddle.net/u0gwc5dy/19/

#### Product version

Highcharts
#### Affected browser(s)
All Browsers

**Comment by sebastianbochan** [comment]
Hi @VBIManonmaniM,
Thank you for reporting.

_Internal note_
Regression since 6.0.7.
- https://jsfiddle.net/ntcvek9d/

Related issue and commit https://github.com/highcharts/highcharts/issues/7798
