### ISSUE TITLE
Documentation: Add missing members like legend and tooltip to chart

### ISSUE THREAD

**Issue by sophiebremer** [highcharts/highcharts#8464]
There are important members in the Chart class missing.

**Comment by jdelight** [comment]
Thanks for this - I was wondering if the access to the Tooltip prototype was a supported API as it's not listed on the namespace page. Does this mean it is?

**Comment by sophiebremer** [comment]
Hi! Thank you for getting in touch with us.

It is not official yet, because the online documentation for it is missing. In the beta of the TypeScript declarations for Highcharts v6 this will already be exposed. This might happen next week, depending on the alpha test phase for the declarations.

You can count on both properties (chart.legend, chart.tooltip) and the corresponding classes, including their update function (like chart.legend.update) and the chart and options properties (like chart.legend.chart). There will be additional functions and properties official, but this is under review.
