### ISSUE TITLE
Axis labels are cut off outside the chart area when 'labels.useHTML' is true.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#8467]
#### Expected behaviour

Axis labels shouldn't be cut. Instead of that, plot area should make room for labels.

#### Actual behaviour

Plot area height doesn't respect axis label size.

#### Live demo with steps to reproduce

Example: http://jsfiddle.net/L3y862ck/
Both charts differ in `xAxis.labels.useHTML` setting.

#### Product version

 Below v6.1.0 everything works properly.

**Comment by TorsteinHonsi** [comment]
Breaking commit: 2c8cea8e4
