### ISSUE TITLE
Hover color API for pie chart missing 

### ISSUE THREAD

**Issue by DamolAAkinleye** [highcharts/highcharts#8468]
I have a pie chart which I am using via angular v6. However, I have found it is not possible to change the hover colour of each of the slice as against the  other chart type. 

Please is there a missing api to do this. I have a stack blitz repo to reproduce this 

https://stackblitz.com/edit/angular-highcharts-zl3wjq?file=app%2Fapp.component.ts 

Also is there a way to animate out the slices on rollover rather than on click.

I am using the  chrome browser 54 and I have high charts 6.1.0

**Comment by TorsteinHonsi** [comment]
You can change the hover color for each slice individually (blue), or for all of them combined (red): http://jsfiddle.net/68p2rutn/

This is not clear from the docs though.

**Comment by DamolAAkinleye** [comment]
Thanks @TorsteinHonsi  for this works. Do you know of any way to accomplish my second question with high charts via its Api. It used to be a default options. To mouse over and have the slices animate out.

**Comment by TorsteinHonsi** [comment]
Hmm.. I don't think it has ever behaved like that, but you can achieve it by adding events. Disabling the halo is also a good idea so it doesn't conflict: http://jsfiddle.net/nhdgw12b/
