### ISSUE TITLE
scatterplot shows only a few points after 8K points

### ISSUE THREAD

**Issue by HyETBV** [highcharts/highcharts#8470]
#### Expected behaviour
points on every X point with random data on y point

#### Actual behaviour
columns of scatterpoints shown on a few X points

#### Live demo with steps to reproduce
http://jsfiddle.net/3pe2j8c1/9/

#### Product version
Highchart V6

#### Affected browser(s)
only tested in chrome

![image](https://user-images.githubusercontent.com/35219732/41354606-b4b0d90c-6f1f-11e8-887d-9f547f8a94bc.png)

![image](https://user-images.githubusercontent.com/35219732/41356834-000ac980-6f25-11e8-8582-212005442d15.png)

**Comment by sebastianbochan** [comment]
Hi @HyETBV,
Unfortunately I was not able to replicate your issue. Could you paste static data for reproduce the issue? It will allow us to debug it.

**Comment by HyETBV** [comment]
It is a timing issue, after +/- 30 minutes (just keep jfiddle in the background), it will change it's shape.
When you have a static dataset, the problem does not occurre. should i replace the chart with a fresh chart after 30 minutes?

**Comment by sebastianbochan** [comment]
Hi @HyETBV,
30min time frame its a little bit tricky and can be related with machine performance, browsers details and many other factors. We would like to have a stable demo, which allow us to prepare fix and verify it in tests.

**Comment by pawelfus** [comment]
I will check this tomorrow, but it looks like a bug in floating point precisions, when [`boost.useGPUTranslations`](https://api.highcharts.com/highcharts/boost.useGPUTranslations) is enabled. @HyETBV - could you disable this option and let us know about the result? This probably should be disabled (you have timestamps-based dataset). Thanks!

**Comment by HyETBV** [comment]
effect is not pressent in edge, so i will try to find a method for it in chrome.
