### ISSUE TITLE
Series label Text Outline properties should not be set but the color should be contrasted with the plot background color

### ISSUE THREAD

**Issue by akritianand93** [highcharts/highcharts#8472]
#### Expected behaviour
When series label is placed outside the pie chart and text outline property is set to none, its color should be inverted(without applying textOutline) according to the plotBackgroundColor provided by the chart.

#### Actual behaviour
The series label color is not inverted according to the chart background color.
However, if the series label position is inside the pie chart, series label color is inverted.

#### Live demo with steps to reproduce

When we do not pass any style for text outline and **series label is placed outside**, a **text outline** of the color in **contrast** is applied.(black or white)
https://jsfiddle.net/muzb9apk/18/ 

When **series label** is placed **inside** the pie chart and **text outline style is none**, series label color is **contrasted** to black and white depending upon the background color(**without text outline**).
https://jsfiddle.net/muzb9apk/24/

However, with **series label** placed **outside** the chart and **text outline** style set to **none**, **series label color** is not contrasted therefore **mixes** with the background color. 
https://jsfiddle.net/muzb9apk/26/

I want the **series label color to be in contrast** with the plotBackgroundColor(if it is placed outside the chart), **without** applying a **textOutline**(as it behaves when series label is placed inside the pie chart).

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @akritianand93 

Thank you for your suggestion. You can achieve that (if you want this process automated, and you prefer Highcharts logic for contrast values) by adding event and applying changes: 

```javascript
Highcharts.addEvent(Highcharts.seriesTypes.pie, 'afterDrawDataLabels', function() {
  var series = this,
    chart = this.chart,
    options;

  Highcharts.each(series.points, function(point) {
    // Get all dataLabels options:
    options = Highcharts.merge(
      series.options.dataLabels,
      point.options && point.options.dataLabels
    );

    // dataLabel exists, is outside the pie and contrast is requested
    if (
      point.dataLabel &&
      options.distance > 0 &&
      options.style.color === 'contrast'
    ) {
      point.dataLabel.css({
        color: chart.renderer.getContrast(
          // plotBackgroundColor -> backgroundColor -> white
          chart.options.chart.plotBackgroundColor ||
          chart.options.chart.backgroundColor ||
          '#FFFFFF'
        )
      });
    }
  });
});
```

Of course, there is another solution: when you set `plotBackgroundColor` in options, then you can set contrast color for dataLabels manually.

**Comment by TorsteinHonsi** [comment]
Playing around with a more flexible solution I've had in mind - to actually read the color from the background instead of guessing. This will work both inside and outside the pie, but there are of course still flaws, for example it wouldn't work with a gradient background (doesn't have a `fill`), or mixed backgrounds.

https://jsfiddle.net/muzb9apk/59/
