### ISSUE TITLE
may I ask how to build to files that can replace the highcharts-dist codebase?

### ISSUE THREAD

**Issue by lopugit** [highcharts/highcharts#8473]
#### Expected behaviour
gulp builds files to /code that can be put into the highcharts-dist repo to replace any highcharts-dist dependancies in other projects

#### Actual behaviour
builds files to /code with a file structure that is missing some folders and files that are in highcarts-dist such as

`adapters`
`lib`
'*.js.map' files

I was just wondering how you build this repo into the files which can replace all the files in the highcharts-dist repo?

Because the highcarts npm module uses the highcarts-dist repo as it's codebase, so building modified code to replace that dependancy needs to come from this repo, 

thanks a lot!

**Comment by sebastianbochan** [comment]
Hi @lopugit,
Thank you for contacting us.

@TorsteinHonsi any comments?

**Comment by jon-a-nygaard** [comment]
The easiest way to achieve this would be to run our complete distribution process.

This can be done by executing `gulp dist` then afterwards executing `node copy-release`.
It will create all the distributed files and copy them to `/highcharts/../highcharts-dist`. This folder will likely have to be created in advance.

**Comment by TorsteinHonsi** [comment]
@jon Should we describe this in the readme of the `highcharts-dist` repo?

**Comment by lopugit** [comment]
Thanks so so much guys I'll try it out :D <3 may be worth adding it to the docs, I couldn't find any previous issues for it, this issue should appear in google searches now though so that'll be helpful

**Comment by jon** [comment]
Please be careful with your @ replies -- they reference people by username,
not first name (unless they happen to coincide as in my case).
