### ISSUE TITLE
Regression: Updating stacking does not update all stacked series

### ISSUE THREAD

**Issue by oluwasayo** [highcharts/highcharts#8475]
#### Expected behaviour (Highcharts 5)
Before = 2
After = 50
<img width="726" alt="screen shot 2018-06-14 at 2 29 00 pm" src="https://user-images.githubusercontent.com/900868/41409562-562515b8-6fdf-11e8-843a-c307b7349d97.png">

#### Actual behaviour (Highcharts 6)
Before = 2
After = 2
<img width="730" alt="screen shot 2018-06-14 at 2 28 41 pm" src="https://user-images.githubusercontent.com/900868/41409575-5ca4e0ee-6fdf-11e8-9721-610b47e8f75b.png">

#### Live demo with steps to reproduce
http://jsfiddle.net/oluwasayo/ar369czu/1/
1. Run Fiddle
2. Open browser console
3. Click on Print Stacking to observe the behavior in Highcharts 6
4. Comment Highcharts 6 import and uncomment Highcharts 5
5. Rerun Fiddle and click on Print Stacking to observe the behavior in Highcharts 5

#### Product version
Highcharts/Highstock 6

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @oluwasayo 

Thanks again for reporting the issue! I'm not sure if this is really a bug. Behaviour between v5 and v6 obviously has changed so probably we should treat this as a regression. 

In your case, you have two series with different stackings on the same yAxis. It's wrong, both series should be updated: http://jsfiddle.net/BlackLabel/ar369czu/11/  Alternatively, you can use `chart.update()` in this case: http://jsfiddle.net/BlackLabel/ar369czu/13/  

*Internal note:*
Bisect leads to c2dfc7144

**Comment by KacperMadej** [comment]
Works fine when using Highcharts v 7.0.3
Closing as resolved
