### ISSUE TITLE
plotLine labels do not work in browsers that support Array.prototype.flat()

### ISSUE THREAD

**Issue by cers** [highcharts/highcharts#8477]
The issue comes from line https://github.com/highcharts/highcharts/blob/7e30b142a1e0809302d14b55668c8b6b0b4215d0/js/parts/PlotLineOrBand.js#L153

I'm not sure what that "if" is testing for, but that attribute will probably have to be renamed...

#### Expected behaviour
plotLine labels should show up.

#### Actual behaviour
plotLine labels do not show up.

#### Live demo with steps to reproduce

http://jsfiddle.net/cers/whzeL2um/

#### Product version

Highcharts 6.1.0 (I haven't checked the others)

#### Affected browser(s)
Firefox 62
Chrome 69

**Comment by sebastianbochan** [comment]
Hi @cers,
Thank you for the suggestion.

**Internal note**
The issue is more complex and i.e appears also in other references i.e:
- https://github.com/highcharts/highcharts/blob/master/js/parts/PlotLineOrBand.js#L307

**Comment by cfarm** [comment]
Can confirm this is also an issue in 5.0.11 in Chrome 69.

**Comment by sebastianbochan** [comment]
Hi @cfarm,
The issue has been already fixed, so I advise you to update your Highcharts library  to the newest version (v6.1.3).

**Comment by TorsteinHonsi** [comment]
#### Workaround
Here's a workaround for those who can't update Highcharts for some reason:

```js
	// Drop-in fix for Highcharts issue #8477 on older Highcharts versions. The
    // issue is fixed since Highcharts v6.1.1.
	Highcharts.wrap(Highcharts.Axis.prototype, 'getPlotLinePath', function (proceed) {
    	var path = proceed.apply(this, Array.prototype.slice.call(arguments, 1));
        path.flat = false;
        return path;
    });
```

View it [live on jsFiddle](http://jsfiddle.net/highcharts/r4kzcfdq/).

**Comment by eltonjude** [comment]
I required a null check for `path` in our application.

**Comment by TorsteinHonsi** [comment]
Thanks, I added an `if` to the snippet above.
