### ISSUE TITLE
Duplicated legend items in "Map with overlaid pie charts" demo.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#8478]
#### Actual behaviour

All elements in legend are duplicated, but only in DOM (Chart.legend object has appropriate amount of items). 

#### Live demo with steps to reproduce
Demo from our documentation:
https://www.highcharts.com/maps/demo/map-pies
While inspecting `highcharts-legend` group element, we can see:
<img width="394" alt="rsz_screen_shot_2018-06-14_at_154547" src="https://user-images.githubusercontent.com/15111955/41416049-539567fc-6fea-11e8-88b4-dddb11c0d2d0.png">

#### Product version
From v6.1.0 
It seems c8a25294f causes the problem:

**Comment by KacperMadej** [comment]
Minimal demo (without map, but with colorAxis): https://jsfiddle.net/BlackLabel/g734Lzof/
