### ISSUE TITLE
If the K-line graph is in a small amount of data, if it controls the display effect?

### ISSUE THREAD

**Issue by yyb1994** [highcharts/highcharts#8480]
I encountered a problem when K-line was in a small amount of data.
How do I control the spacing between charts and shorten the distance?

#### Live demo with steps to reproduce
https://jsfiddle.net/gn7oapmw/

![1](https://user-images.githubusercontent.com/17470456/41458503-5e618290-70b9-11e8-894a-023196821552.png)
![2](https://user-images.githubusercontent.com/17470456/41458565-872e188c-70b9-11e8-9bab-af55aba9173a.png)

**Comment by pawelfus** [comment]
Hi @yyb1994 

This is our bugtracker, if you have questions, please contact our support: https://www.highcharts.com/support

PS: Probably you want to remove `pointWidth` from your config.
