### ISSUE TITLE
Chart corrupted when update() with chart.type

### ISSUE THREAD

**Issue by vpckso** [highcharts/highcharts#8481]
#### Expected behaviour
1. change to bar chart
2. keep showing 3 x-axis

#### Actual behaviour
1. can't change type to bar
2. duplicated x-axis

#### Live demo with steps to reproduce
http://jsfiddle.net/3oybgrep/10/

#### Product version
Highcharts 6.1

#### Affected browser(s)
any

**Comment by TorsteinHonsi** [comment]
Thanks for reporting this bug!

#### Workaround
What separates a column from a bar chart is only that a bar is in an `inverted` chart, so in your case you can work around the issue by setting `chart.inverted`: http://jsfiddle.net/3oybgrep/12/

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/3oybgrep/17/

**Comment by vpckso** [comment]
Thx for the fix, but problem 2 didn't fix.
http://jsfiddle.net/3oybgrep/24/

**Comment by pawelfus** [comment]
This works fine also when providing `series` options, instead of using `data.js` module http://jsfiddle.net/BlackLabel/3oybgrep/40/
