### ISSUE TITLE
Tooltips appear on another trace's area when there is more than one axis

### ISSUE THREAD

**Issue by bbonczek** [highcharts/highcharts#8482]
#### Expected behaviour
If I want to show chart with 2 traces one above the other, and extremes for the higher one are cutting part of trace (so it 'overlaps' to one below) the tooltip should not appear.

#### Actual behaviour
The tooltip appears:
![obraz](https://user-images.githubusercontent.com/11254976/41465113-fb34f6fa-709c-11e8-8277-c5e532567443.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/092bsmod/

#### Product version
Highstock 6.1.0

#### Affected browser(s)
Chrome, firefox

**Comment by sebastianbochan** [comment]
Hi @bbonczek,
Thank you for reporting. 

**Workaround**
Disable `stickyTracking`.

Demo:
- https://jsfiddle.net/qgmt93px/
