### ISSUE TITLE
series name not coming when using drilldown 

### ISSUE THREAD

**Issue by snehalseth** [highcharts/highcharts#8484]
using react js
#### Expected behaviour

i should get the series name on both levels of the chart 

#### Actual behaviour
instead of the series name given in the config i am getting numbers as series name (0, 1 etc)

#### Live demo with steps to reproduce
this is the config i am using 

when i use this code in fiddle it gives me the correct output

```
Highcharts.chart("attendance-chart-container", {
      chart: {
        type: "column"
      },
      title: {
        text: ""
      },
      xAxis: {
        crosshair: true
      },
      credits: {
        enabled: false
      },
      yAxis: {
        min: 0,
        title: {
          text: "Count"
        }
      },
      series: [
        {
          name: "Browsers",
          colorByPoint: true,
          data: [
            {
              name: "Sikandarabad",

              y: 2,
              drilldown: "Sikandarabad"
            },
            {
              name: "Dadri",

              y: 3,
              drilldown: "Dadri"
            }
          ]
        }
      ],
      drilldown: {
        series: [
          {
            name: "Sikandarabad",
            id: "Sikandarabad",
            data: [
              {
                name: "P.S Sanwali",
                y: 1
              },
              {
                name: "P.S Mandawara-1",
                y: 1
              },
            ]
          },
          {
            name: "Dadri",
            id: "Dadri",
            data: [
              {
                name: "S.R Public School",
                y: 1
              },
              {
                name: "R.K Memorial Public School",
                y: 1
              },
              {
                name: "P.S Chitehra-1",
                y: 1
              },
              
            ]
          }
        ]
      }
    });
```

**Comment by pawelfus** [comment]
Hi @snehalseth 

Thank you for reporting the issue. Could you recreate this in jsFiddle with react? jsFiddle should support react.

**Comment by tarican** [comment]
I am struggling with the same problem for 3 days.. Couldn't find any solutions and it seems buggy.. At least it is good to know that I am not the only one :)

Here is the jsfiddle link which you can see the problem: [https://jsfiddle.net/dpr6h05L/4/](url) 

Please drilldown by clicking on **Chrome** bar. After that you will see, only first 3 bar has names and the other ones numbers. (even tooltips have the correct names) The weird part is, if you resize your browser (to be precise the chart width or height) the names start to can be seen.

Problem is (I guess), about data loading process and rendering names or bars in terms of count. I hope this explanation will be helpful, I will continue to seek for a work-around solution for our customers..

**Comment by snehalseth** [comment]
my problem was solved by making the correct series format. the structure of the array for series and drill-down was wrong and i didn't provide the type in the x-axis so the name was not rendering.

as far as your problem is concerned i think your drill-down series has too much data that's why you are seeing numbers instead of the names of the series. try reducing the drill-down series and try, i hope you will get the desired output or make the container of the chart wide enough to contain the whole graph.

**Comment by snehalseth** [comment]
@pawelfus i was able to solve the problem. it was with the config that i was giving and the data format was also wrong so i was not getting the desired output.

**Comment by tarican** [comment]
thx for your reply, but this is the data that i have to show that level, and also not satisfied because after you drilldown, just try to resize browser. Than it corrects the chart and draws the expected result.

which is: [https://cl.ly/323O1f143d2k](https://cl.ly/323O1f143d2k)

**Comment by tarican** [comment]
as far as you closed this issue, i guess i am gonna open another one :)

**Comment by tarican** [comment]
actually found a work-around which is not pretty but does the trick if anyone else needs it:

[https://jsfiddle.net/dpr6h05L/15/](https://jsfiddle.net/dpr6h05L/15/)

on drilldown event, setting chart size to null does the trick (weird:)

**Comment by snehalseth** [comment]
it a work around for what you wanna do but still you are not getting every name on the x-axis after drill-down. just take a look at it

**Comment by tarican** [comment]
yup i know i can not get every name but it won't show up a like a glitch instead at least.. otherwise, there are nonsense numbers & on window resize appear names & only few names.. probably with the some of latest updates of highcharts this bug appeared, it wasn't like this before..

**Comment by pawelfus** [comment]
@snehalseth I'm glad you resolved the issue! Thanks for the details :) 

Hi @tarican 

Your issue is a separate one, this one is connected to this bug: #5857 - workaround is to set `series.cropThreshold`, for example to 10000, demo: https://jsfiddle.net/BlackLabel/dpr6h05L/18/

**Comment by tarican** [comment]
@pawelfus thx mate!
