### ISSUE TITLE
Unable to get bar graph with negative stack & correct category lables after drilldown

### ISSUE THREAD

**Issue by adityakapre2009** [highcharts/highcharts#8486]
#### Expected behaviour

After drill down from pie, should get bar with negative stack and correct labels
(want something like this : https://www.highcharts.com/demo/bar-negative-stack)

#### Actual behaviour
After drill down from pie, getting column chart and no labels

#### Live demo with steps to reproduce
https://jsfiddle.net/aditya14641/hLtj3wqb/26/

**Comment by sebastianbochan** [comment]
Hi @adityakapre2009,
When I run your demo, I am not able to reproduce the issue. See the gif below.

![drilldown](https://user-images.githubusercontent.com/2115686/41521967-801df220-72d4-11e8-8951-a2ff2e683817.gif)


Could you point me out, which browser do you use (including full number of version) and how can I reproduce the issue ?

**Comment by adityakapre2009** [comment]
Hi,

Sorry for confusion, I guess I did nt make myself clear.
I can see the issue in your gif too. The problem is I want the drill down view to show up horizontal bars instead of vertical bars (so I guess Y axis should be horizontal).

By horizontal bars, I meant as below

![image](https://user-images.githubusercontent.com/2627618/41542193-61db183e-72e2-11e8-9901-e14b80490143.png)

    --|--
---- |----
    --|--

However, I see vertical bars as below
    |
 |  |  |
-------
 |  |  |
    |

Not sure if that explains

**Comment by sebastianbochan** [comment]
Hi @adityakapre2009,
This is our bugtracker, so for the general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

ps. If you need to change chart's rotation, call `chart.update()` with the inverted parameter.
