### ISSUE TITLE
When series starts with "NaN", chart is not drawn

### ISSUE THREAD

**Issue by opeeters** [highcharts/highcharts#8490]
#### Expected behaviour

in the following:
```
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'area'
        },
        xAxis: {
        	type: 'datetime'
        },

        series: [{
        	
            data: [
            	[Date.UTC(2014, 0, 1), 2],
            	[Date.UTC(2014, 0, 2), 12],
            	[Date.UTC(2014, 0, 3), "NaN"],
            	[Date.UTC(2014, 0, 4), 12],
              [Date.UTC(2014, 0, 5), 4],
            ]
        }]
    });
});
```

the chart is correctly drawn. 

However, if the "NaN" comes first, like so:
```
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'area'
        },
        xAxis: {
        	type: 'datetime'
        },

        series: [{
        	
            data: [
            	[Date.UTC(2014, 0, 3), "NaN"],
            	[Date.UTC(2014, 0, 1), 2],
            	[Date.UTC(2014, 0, 2), 5],
            	[Date.UTC(2014, 0, 4), 12],
              [Date.UTC(2014, 0, 5), 4],
            ]
        }]
    });
});
```
there is an error (see below).

Without the `"` the `NaN` works as expected, but when using data from an external REST-api for instance it is not very convenient to check for this case. To me this seems something which should rather be handle within highcharts.js.

#### Actual behaviour
```
Error: Highcharts error #14: www.highcharts.com/errors/14
highcharts.js:10:178
```
#### Live demo with steps to reproduce
jsfiddle.net/vw1tdg6a/1/

#### Product version

Highcharts JS v6.1.0 (2018-04-13)

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @opeeters,
Thank you for reporting. The issue is related with known bug here: https://github.com/highcharts/highcharts/issues/3571.
