### ISSUE TITLE
Incorrect assignment in data table for donut charts

### ISSUE THREAD

**Issue by emichalsky** [highcharts/highcharts#8494]
#### Expected behaviour
Values in the donut data table are correctly assigned to their categories.

#### Actual behaviour
You can see it in the Fiddle of the donut chart demo https://www.highcharts.com/demo/pie-donut.
Values in the second column ("Browsers") are all shifted to the top, such that the correct assignment gets lost. In order to avoid the misalignment, there should be spaces in the respective table cells of the second column. I tried to illustrate the correct behaviour in contrast to the actual one in a screenshot by colored arrows and boxes:
![highchartsincorrectdonutdatatable_large](https://user-images.githubusercontent.com/40357054/41545729-27675a34-731c-11e8-956f-f0c779984a4b.jpg)

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/pie-donut/
#### Product version

6.1.0
#### Affected browser(s)
all

**Comment by sebastianbochan** [comment]
Hi @emichalsky,
Thank you reporting. 

@oysteinmoseng any comments?

**Comment by TorsteinHonsi** [comment]
Simplified demo: https://jsfiddle.net/highcharts/edby3r0q/4/

The top-level categories are completely missing from the data export.

**Comment by emichalsky** [comment]
Thank you Torstein, this was very fast!
