### ISSUE TITLE
variwide chart type does not work when chart.inverted is true

### ISSUE THREAD

**Issue by lionel87** [highcharts/highcharts#8498]
#### Expected behaviour

Correct variwide bar chart.

#### Actual behaviour

Bar widhts are not correct, chart fallen apart.

#### Live demo with steps to reproduce
https://jsfiddle.net/qchg8923/

#### Product version
highcharts 6.1

#### Affected browser(s)

All.

**Comment by sebastianbochan** [comment]
Hi @lionel87,
Thank you for the reporting. 

**Internal note**
@TorsteinHonsi 
It looks like inverted chart is not supported at all and its not documented in our API.

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: https://jsfiddle.net/qchg8923/16/
