### ISSUE TITLE
Waterfall chart connectors can be hidden by other bars with multiple series

### ISSUE THREAD

**Issue by KevinShiCA** [highcharts/highcharts#8499]
#### Expected behaviour
Connectors between bars should be visible (rendered on top of the SVG).

#### Actual behaviour
In a waterfall chart with more than one series, connectors can be hidden by other bars.

#### Live demo with steps to reproduce
https://jsfiddle.net/qpakywz5/1/
Notice how the second series bars hide connectors from the first series.

#### Product version
6.1.0

#### Affected browser(s)
Chrome, Firefox, Edge

**Comment by sebastianbochan** [comment]
Hi @KevinShiCA,
In the jsfiddle, all connectors are visible. Could you take a screenshot and mark which one are missing?

Tested in Chrome: 67.0.3396.87

**Comment by pawelfus** [comment]
Explanation: this is caused by series groups: each series has a separate group, so connectors from one series are below the next series.

**Workaround:**
Workaround requires disabled animation: https://jsfiddle.net/BlackLabel/qpakywz5/8/

Snippet:
```javascript
(function(H) {
  // Change group temporarily:
  H.wrap(H.seriesTypes.waterfall.prototype, 'drawGraph', function(proceed) {
    var group = this.group;

    this.group = this.chart.seriesGroup;
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    this.group = group;
  });

  // Apply offset to the lines:
  H.wrap(H.seriesTypes.waterfall.prototype, 'getCrispPath', function(proceed) {
    var chart = this.chart,
      path = proceed.apply(this, Array.prototype.slice.call(arguments, 1)),
      length = path.length,
      i = 0;

    for (; i < length; i += 3) {
      path[i + 1] += chart.plotLeft;
      path[i + 2] += chart.plotTop;
    }

    return path;
  });
})(Highcharts);
```

**Comment by KevinShiCA** [comment]
@pawelfus's workaround works, closing.
