### ISSUE TITLE
addPoint with array on datetime charts results in empty x-coordinate

### ISSUE THREAD

**Issue by mhindery** [highcharts/highcharts#8500]
#### Expected behaviour
When passing an array A to `series.addPoin(A)` on a chart with a datetime x-axis, the x-coordinate is not set correctly. The first item in the array should be used as the x-coordinate, according to the documentation and the provided example [Both X and Y values given.](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/series-addpoint-x-and-y/)

#### Actual behaviour
The x-coordinate is set to 0 instead of the first item in the array (which it should do according to the [addPoint reference](https://api.highcharts.com/class-reference/Highcharts.Series#addPoint)). In the datetime universe, this leads to a point being added with timestamp 1 jan 1970. When trying out the code from the provided example under `Both X and Y values given.`, it doesn't work on these graphs.

When you call `series.addPoint(O)` with an object O having an x and y field, everything works as expected.

#### Live demo with steps to reproduce
https://codepen.io/anon/pen/WyMpjp?editors=1111

The demo will initialize a spline chart with a series of 4 points (x = timestamp `ts`, y = value) on a datetime x-axis. There are 2 buttons which each invoke a addPoint() operation. One uses an object `(x: ts, y: value)` which adds a new point correctly to the chart. The other one uses an array `[ts, value]` and you see the chart jump to 1970 where the point gets added.

#### Product version
Highcharts. Have observed it with latest version (demo uses [https://code.highcharts.com/highcharts.js](https://code.highcharts.com/highcharts.js), I use locally [https://cdnjs.cloudflare.com/ajax/libs/highcharts/6.0.7/highcharts.js](https://cdnjs.cloudflare.com/ajax/libs/highcharts/6.0.7/highcharts.js))

#### Affected browser(s)
It's not browser-specific, it happens on my MacOS Chrome / Firefox / Safari

**Comment by pawelfus** [comment]
Hi @mhindery 

Thanks for reporting the issue. The problem is that `moment(raw_latest_point.timestamp).toDate()` returns **Object** for x-values (see console: https://codepen.io/anon/pen/yEvRyx?editors=1111 ), while **Number** (timestamp) is expected. See [Axes](https://www.highcharts.com/docs/chart-concepts/axes) docs.

Why it works for object? Because we map array to object internally, and we don't know what to do with object for x-value.

**Comment by KacperMadej** [comment]
There's no official plans for the support of date-objects for x-values based on the https://www.highcharts.com/blog/roadmap/
