### ISSUE TITLE
setCategories causes error in drilldown event

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#8501]
#### Expected behaviour
`setCategories` with `redraw` argument set to `true` shouldn't cause an error.

#### Actual behaviour
I produces an error: 
`Uncaught TypeError: Cannot read property '0' of undefined`

Everything works fine if  `redraw` argument is `false`: https://jsfiddle.net/BlackLabel/zh7qfes1/

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/x86dz3gL/
Click any pie slice.

#### Product version
Highcharts 6.1.0

**Comment by sebastianbochan** [comment]
**Workaround:**
Set categories names in points.

Demo:
- https://jsfiddle.net/BlackLabel/aods9tg3/

**Comment by kamilkulig** [comment]
`addSingleSeriesAsDrilldown` and `applyDrilldown` are Highcharts' internal functions - they're not documented in the API and they're not adjusted to perform `setCategories` "between" them. 

Official function `addSeriesAsDrilldown` can be use instead - it doesn't produce an error:

```
            chart.addSeriesAsDrilldown(e.point, {type: 'column', data: [1, 2, 3]});
            chart.xAxis[0].setCategories(['20-30', '31-40', '41-50', '51-60']);
```
**Live demo:** https://jsfiddle.net/BlackLabel/54pguqwz/
