### ISSUE TITLE
Sunburst - datalabels draw incorrectly

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#8502]
#### Actual behaviour
- overlapping labels in the center of circle
- when we click i.e on equity, label from the first level is still visible
- when we click i.e on equity and get back to initial state, more labels are visible

#### Live demo with steps to reproduce
- https://jsfiddle.net/BlackLabel/8qLfuzor/

#### Product version
6.1

#### Affected browser(s)
All

@jon-a-nygaard

**Comment by TorsteinHonsi** [comment]
The commit above fixes the two first bullet points.

The last one is not related I think, it has to do with what levels are rendered, rather than what labels. See #8504.
