### ISSUE TITLE
如何设置环形图的线条向右对齐显示?

### ISSUE THREAD

**Issue by shanewds** [highcharts/highcharts#8505]
原图
![41c07428dfaa04e4c7b736d902a7e69a](https://user-images.githubusercontent.com/19984920/41698078-9e0fcbb0-754e-11e8-91dc-b8bb5221e386.jpg)
实现的效果图如下
![wechatimg146](https://user-images.githubusercontent.com/19984920/41698089-b58e5c3e-754e-11e8-9808-c06035ce3e53.jpeg)

**Comment by sebastianbochan** [comment]
Hi @shanewds,
Thank you for contacting us. The github is our bugtracker for reporting issues. Please use our [support](http://www.highcharts.com/support) channels for general questions.
