### ISSUE TITLE
setSize changes the style of axis labels

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#8510]
#### Expected behaviour
Labels should look the same after clicking _Step 1_ (change size of the chart) and _Step 2_ (restore the original size of the chart) buttons.

#### Actual behaviour
`textOverflow: 'ellipsis'` is not applied to y axis labels anymore.

#### Live demo with steps to reproduce
First click _Step 1_ and then _Step 2_. 
http://jsfiddle.net/BlackLabel/s1a6eg9y/

#### Product version
Highcharts 6.1.0

**Comment by kamilkulig** [comment]
**Workaround:**
Update `textOverflow` manually: http://jsfiddle.net/BlackLabel/axhcwrmd/

**Comment by Denyllon** [comment]
Already fixed on `master` branch.
Live example: http://jsfiddle.net/vx0wLszc/

**Comment by burch78** [comment]
This does not appear totally fixed. After step 2, ellipsis still isn't applied, and wrapping occurs in some titles.

Please consider this demo instead. It is important to exclude the legend to notice the full issue:

http://jsfiddle.net/burchw78/rwb7ms93/

**Comment by pawelfus** [comment]
Hi @burch78 

This is how it works for me:

![w93zirioqj](https://user-images.githubusercontent.com/1453926/41770012-4b1a11e0-7611-11e8-93c2-299dfb9bfd1f.gif)
