### ISSUE TITLE
Category axis to datetime axis drilling and zoom shows both axis on drill up

### ISSUE THREAD

**Issue by ChaoDjinn** [highcharts/highcharts#8511]
The chart has 2 xAxis, one is category, one is datetime. The first level of data is grouped by category, when drilling down it is datetime. Once drilled down, if you zoom in on the date data, then drill back up, the datetime aAxis remains, sitting on top of the category axis.

#### Live demo with steps to reproduce
https://jsfiddle.net/52hfwb07/11/

#### Product version
Highcharts, Highstocks: 6.1

**Comment by sebastianbochan** [comment]
Hi @ChaoDjinn,
Thank you for reporting.

**Comment by ChaoDjinn** [comment]
@sebastianbochan Excellent, thank you very much!
