### ISSUE TITLE
Range selector not working correctly on Apple devices

### ISSUE THREAD

**Issue by DimitarIvanov2898** [highcharts/highcharts#8512]
#### Expected behaviour
Dates in the range selector fields show wrong starting date when opened on apple device.

**Comment by sebastianbochan** [comment]
HI @DimitarIvanov2898,
I run the example: https://www.highcharts.com/stock/demo/basic-line and in both cases (Chrome and Apple) the result is the same. Could you supply me more details how can I reproduce the issue?

<img width="856" alt="zrzut ekranu 2018-06-22 o 09 53 41" src="https://user-images.githubusercontent.com/2115686/41764678-2cc058b2-7602-11e8-97e1-161adaee04d3.png">


![35842472_1968400439860652_6558505959679852544_n](https://user-images.githubusercontent.com/2115686/41764666-23146894-7602-11e8-9d38-6061487469af.jpg)

**Comment by DimitarIvanov2898** [comment]
Hello, i've created the graphs through the cloud. Once i open them with any non apple device everything works fine. But if i open it with iPhone for example, the dates just go mad.
I am attaching the same graph opened in chrome and safari - see the dates in safari are wrong.
![photo_2018-06-22_09-44-15](https://user-images.githubusercontent.com/22296488/41896106-659d5bbc-792c-11e8-848b-1e4f6e2a3bd1.jpg)
<img width="1440" alt="screen shot 2018-06-22 at 9 40 10" src="https://user-images.githubusercontent.com/22296488/41896107-65bc5d0a-792c-11e8-8d79-bf3c2fd0b896.png">

**Comment by DimitarIvanov2898** [comment]
Hello, test with this graph
http://alpharesearch.bg/monitoring/31/

**Comment by sebastianbochan** [comment]
Hi @DimitarIvanov2898,
Thank you for the live demo and now I see the issue. 

The problem is more complex and appears also in desktop Safari. Its related with date format and wrong parsing data in our data module. 

Chrome:
```new Date('2016-09-01 00:00:00')
Thu Sep 01 2016 00:00:00 GMT+0200
```

Safari:
```new Date('2016-09-01 00:00:00')
Invalid Date
```

**Comment by DimitarIvanov2898** [comment]
Hello, do you have any idea when the bug will be fixed?

**Comment by sebastianbochan** [comment]
@TorsteinHonsi @cvasseng any comments?

**Comment by pawelfus** [comment]
**Workaround:**

In CUSTOM CODE section add parser for this format: 

```
// Extending options:
Highcharts.merge(true, options, {
    data: {
        // Safari doesn't support YYYY-MM-DD format
        // Manually parse these dates:
     	parseDate: function (d) {
            var safe = d.split(' '),
                date = safe[0].split('-'),
                time = safe[1].split(':');
          
         	return Date.UTC(
                  date[0],
                  parseInt(date[1]) - 1,
                  date[2],
                  time[0],
                  time[1],
                  time[1]
                ); 
          }
    }
});
```

**Comment by TorsteinHonsi** [comment]
As Sebastian mentions above, the problem is quite complex because it comes down to how the browsers themselves parse dates. In Highcharts we have defined a handful of date formats where we support parsing directly. If a match is not found for these, the string is passed on to the browser's `Date.parse` function. The problem appears because browsers are not perfectly aligned as to what format they support.

So even though we could add a parser function for this specific format, it will be hard for us to cover all browser inconsistencies. 

It might even be better _not_ to fall back to `Date.parse`, but instead use a date parser library so that at least it is 100% browser consistent.
