### ISSUE TITLE
Update radar to pyramid bug

### ISSUE THREAD

**Issue by vpckso** [highcharts/highcharts#8513]
#### Live demo with steps to reproduce
http://jsfiddle.net/3oybgrep/50/

#### Product version
Highcharts 6.1

**Comment by sebastianbochan** [comment]
Hi @vpckso,
Thank you for reporting.

**Workaround:** 
Destroy chart and create with new options.

Demo:
- http://jsfiddle.net/BlackLabel/6he9tqL2/

**Comment by KacperMadej** [comment]
Looks like the problem is resolved in Highcharts version 8.0.0
