### ISSUE TITLE
Highcharts support for horizontal Waterfall chart

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#8516]
#### Expected behaviour
Highcharts should provide some attribute to change the orientation of waterfall chart as horizontal, inorder to plot horizontal waterfall.
Example:
![horizontal waterfall](https://user-images.githubusercontent.com/7830487/41777205-345d258c-7648-11e8-9b5a-fd4fb7f93f7d.png)

#### Actual behaviour
Currently, Highcharts have waterfall chart with vertical orientation only.
https://www.highcharts.com/demo/waterfall

**Comment by sebastianbochan** [comment]
Hi @amruta30,
As workaround you can use `columnrange` series.

Demo:
- https://www.highcharts.com/demo/columnrange

**Comment by TorsteinHonsi** [comment]
Highcharts waterfalls can already be rendered horizontal - all you have to do is to set `chart.inverted` to `true`: https://jsfiddle.net/6euzcL1r/

I'm closing this, please reopen if you're having issues with it.
