### ISSUE TITLE
splicing a series out of a multiple series array causes undefined errors and 'empty' space within larger array

### ISSUE THREAD

**Issue by snoh8** [highcharts/highcharts#8518]
#### Expected behaviour
When I splice a series out of a series array, the chart takes the series away and allows for the addition of other dynamically generated series. 

#### Actual behaviour
After I splice a series out of the series array, I get an 'empty' notification within the array and an undefined error when I try to add a new series and update the chart. 

#### Live demo with steps to reproduce

This is my code to delete a series from a series array (ie. seriesOptions):function deleteAction(id){
			
			for(var i = seriesOptions.length - 1; i> -1; i--){
				
				//seriesOptions2 = [];
							
				if(chart.series[i].userOptions.name == id.substr(6)){
					console.log(chart.series)
					chart.series[i].remove(true);
					seriesOptions.splice(i, 1);
					//chart.update();
					//chart.redraw(); 
					
					break;
							
				}
The function is attached to dynamically generated "delete" buttons, like so: 

![screen shot 2018-06-14 at 4 13 00 pm](https://user-images.githubusercontent.com/38966861/41793192-f0f4ed2e-7620-11e8-8306-5ae8f616b224.png)

When I click on them, that series does disappear; however, I cannot add additional series without the application breaking and getting undefined errors. I believe this is because when I console.log seriesOptions, there is an 'empty' space where the deleted series used to be. I'm guessing that the problem is that when the chart tries to update itself, it doesn't know what to do with this 'empty'  space: 
![screen shot 2018-06-22 at 1 35 35 pm](https://user-images.githubusercontent.com/38966861/41793275-2c029448-7621-11e8-8096-29052ef92e84.png)

Is there a way I can actively delete and add series to a series array and update the chart without refreshing the page or getting these errors? 

Thank you very much!

**Comment by snoh8** [comment]
Apologies, the first screen capture was not the right one. The dynamically generated button version of this application can be seen here: 
![screen shot 2018-06-22 at 1 32 02 pm](https://user-images.githubusercontent.com/38966861/41793402-865be002-7621-11e8-81da-9bd16371962f.png)

**Comment by TorsteinHonsi** [comment]
I think the your problem is that you're running `splice` on `chart.series`. When you run `series.remove()` it is already removed safely from the internal arrays. Running `splice` is not necessary.

**Comment by snoh8** [comment]
Hello, 
The issue is that if the user "deletes" a query and then tries to add another one without refreshing the page, the older, formerly deleted ones come back if I don't take it directly out of the original seriesOptions series array. However, when I try to splice it out of the seriesOptions array, I get the 'empty' notification in console.

**Comment by pawelfus** [comment]
@snoh8 0 please provide a live demo, instead of live data, you can use any data (like `[1, 2, 3]`) since data is not related to the issue. Right now, we can only guess what is wrong - I have never seen issue like this before.

**Comment by snoh8** [comment]
Hello, 
the basic set up of my visualization application is like so: https://jsfiddle.net/snoh8/mjo680a2/32/
I have tried to alter a pre-existing demo on your site to show you what I'm trying to do. The query can actively add series onto the chart and there should be a delete function that allows for the chosen chart series to destroy itself. Then, the user should be able to continue to add queries as they wish, and delete as well. For some reason, the input query doesn't seem to actually update the example code chart, but I hope that it is a little more helpful. I would like to record a video of the behavior of my actual chart, but currently, our VPN is down and this may take some a little more time. Apologies. 

Thank you so much for your patience!

**Comment by snoh8** [comment]
An update: I have recorded a screen video of my current situation with my actual application. It can be viewed here. I hope that this can clarify what is going on with my situation currently: https://youtu.be/x81lI5yX0Do

**Comment by pawelfus** [comment]
Thank for the demo and video, but that unfortunately this won't help me debug what's happening there.

Maybe it would be better for you to use `addSeries()` instead? Demo: https://jsfiddle.net/BlackLabel/mjo680a2/42/

Note:
Removing is done in `legendItemClick`, no need to loop over all series:
```javascript
    series: {
      label: {
        connectorAllowed: false
      },
      pointStart: 2010,
      events: {
        legendItemClick: function(e) {
          this.remove();
          return false;
        }
      },
    },
  },
```
Adding is done via `addSeries()`:
```javascript
document.getElementById('search').addEventListener('click', function() {

  var thisName = document.querySelector('input[name="query"]').value;
  var newSeries = {
    name: thisName,
    data: [24916, 24064, 29742, 29851, 32490, 30282, 38121, 40434]
  }

  chart.addSeries(newSeries);
});

```

**Comment by snoh8** [comment]
I see, thank you! I've changed my code to work with the add/remove series framework that you have. I'm not entirely sure still why my prior method didn't work, but it works now, so I'll take it. Thank you!
