### ISSUE TITLE
The menu of Export Module doesn't close when you click outside of the chart with an iPad

### ISSUE THREAD

**Issue by aaronplanell** [highcharts/highcharts#8520]
#### Brief explanation
It seems that I have the same problem with the [Export Module](https://www.highcharts.com/docs/export-module/export-module-overview) with an iPad. The menu doesn't close when you click outside of the chart.

#### Expected behaviour
1. I click the context button with a menu that appears in the top right corner of the chart when the Export Module is enabled. The menu opens. 
2. I click outside of the menu **and** outside of the chart. The menu remains opened. 

#### Actual behaviour
1. I click the context button with a menu that appears in the top right corner of the chart when the Export Module is enabled. The menu opens. 
2. I click outside of the menu **and** outside of the chart. The menu closes. 

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/basic-line

#### Product version
Highcharts: 6.0.4

#### Affected browser(s)
iOS 11.4, Safari

**Comment by pawelfus** [comment]
Hi @aaronplanell 

Thank you for reporting the issue.

jsFiddle: https://jsfiddle.net/BlackLabel/mg3rakq1/2/ (tap on the grey box - context menu won't hide)

**Comment by sebastianbochan** [comment]
Related topic: https://github.com/highcharts/highcharts/issues/5735

**Comment by aaronplanell** [comment]
Hello @sebastianbochan ! Thanks for your answer. The ticket #5735 is different: it doesn't close when you click near of the menu because the padding of 24px. Here is when you click outside of the chart in a different element of the DOM.

**Comment by aaronplanell** [comment]
Sorry, could you marked it as a bug at least?

**Comment by aaronplanell** [comment]
Hello,

Can I help in something?

Thanks.

**Comment by pawelfus** [comment]
Thanks! According to commit from 2013 ( 98701ca7d86d183f43dcf4807247ff055d2e564f ) - this should work. Browser should fire `mousedown` event after touch events (ref: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent#Event_order ). Probably `mousedown` in iOS is not fired. I can't find anything in the official apple [docs](https://developer.apple.com/search/?q=mousedown%20event).

**Comment by aaronplanell** [comment]
Hello @pawelfus ,

Maybe it is needed to launch first the touchstart event: 
> If the browser fires both touch and mouse events because of a single user input, the browser must fire a touchstart before any mouse events.

It's the only thing I think is relevant :thinking: .

What do you think?

**Comment by pawelfus** [comment]
I'm not convinced. The same scenario works in Android, so most probably it's a problem with iOS. I remember other issue, where I simply added `touchStart` event, copy of `mousedown`. After the release we received reports that something happens twice on mobile devices (including iOS mobiles!). We needed to revert the commit..

Possible workaround is to add `touchstart` event and simply call this twice in other mobile devices. In theory it should be fine, demo: https://jsfiddle.net/BlackLabel/cyv7j9x0/

Config:

```javascript
    chart: {
      events: {
        load: function() {
          var chart = this,
            className = 'highcharts-contextmenu';


          chart.exportEvents.push(
            Highcharts.addEvent(document, 'touchstart', function(e) {
              var menu = chart['cache-' + className];
              if (
                menu &&
                !chart.pointer.inClass(e.target, className) &&
                !chart.pointer.inClass(e.target, 'highcharts-contextbutton')
              ) {
                Highcharts.css(menu, {
                  display: 'none'
                });
                chart.openMenu = false;
                chart.exportSVGElements[0].setState(0);
              }
            })
          );
        }
      }
    },
```

**Comment by aaronplanell** [comment]
Hello @pawelfus ,

Good news! I have tried both examples:
- Without workaround: https://jsfiddle.net/BlackLabel/mg3rakq1/2/show
- With workaround: https://jsfiddle.net/BlackLabel/cyv7j9x0/2/show

With an iPad the workaround **works** :grinning: 

Do you think that it will be a new release of Highcharts with this workaround?

Thanks a lot for your job!

**Comment by pawelfus** [comment]
Thanks for the test! 

@TorsteinHonsi - what do you think? Should we simply bind `touchstart` event to `hide()` menu?

**Comment by TorsteinHonsi** [comment]
Yes I think we should add it.
