### ISSUE TITLE
[highstock] 1.7 million points with async loading

### ISSUE THREAD

**Issue by zionsky79** [highcharts/highcharts#8521]
#### Expected behaviour
when i max zoom and click scroll button continuously.
sometimes x axis is not match.
x axis = date

![stockchart bug](https://user-images.githubusercontent.com/17314011/41839820-29e648f0-789f-11e8-9dd4-bd317e03fe59.png)

#### Live demo with steps to reproduce

http://jsfiddle.net/Ldu403sp/

#### Product version

Highstock JS v6.1.0 (2018-04-13)

#### Affected browser(s)
chrome 67.0.3396.87 (64bit)

**Comment by pawelfus** [comment]
Hi @zionsky79 

Thank you for reporting the issue. You are right, sometimes it's wrong. It looks like simple redraw (e.g. browser resize) solves the issue, so my guess it's connected to the redraws. Could you try this demo: http://jsfiddle.net/BlackLabel/Ldu403sp/7/  and let us know about the results? Thanks!

**Comment by zionsky79** [comment]
thank you for reply, pawelfus!!
i added keyword "chart.redraw();" follow your comment.
but, the phenomenon has not improved.

**the X-axis value of the mouse position does not match.**

![stockchart bug 02](https://user-images.githubusercontent.com/17314011/41882794-cff37c6e-7925-11e8-8a9c-4af7752bfef9.png)

**Comment by pawelfus** [comment]
This should be:
```javascript
    chart.series[0].setData(data, false, false, false);
    chart.series[1].setData(data, false, false, false);
    chart.redraw();
    chart.hideLoading();
```

So it won't update points with multiple redraws.

**Comment by zionsky79** [comment]
thank you for reply, pawelfus!!
It seems to work well.

**Comment by pawelfus** [comment]
Closing the issue since multiple redraws are not recommended when updating multiple series.
