### ISSUE TITLE
alignTicks for logarithmic axis

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#8522]
#### Expected behaviour
Ticks should be aligned as `alignTicks` option describes.

#### Actual behaviour
Ticks are not aligned: 
![screen shot 2018-06-25 at 10 50 29](https://user-images.githubusercontent.com/1453926/41840278-9c45421e-7865-11e8-8e22-46e66e9def72.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/utxf0ck8/

#### Product version
N/A

#### Affected browser(s)
N/A

**Comment by TorsteinHonsi** [comment]
The problem is that ticks on a logarithmic axis are not always evenly spaced like in the OP screenshot: https://jsfiddle.net/highcharts/utxf0ck8/2/

So either we need to align the ticks only when the log ticks are even, or we need to change the docs to specify that it doesn't apply for log axes.
