### ISSUE TITLE
Boxplot: Varying number of observations per category causes issues

### ISSUE THREAD

**Issue by jln-ho** [highcharts/highcharts#8523]
#### Expected behaviour

Box plots should display correctly when the number of observations per category is not always the same.

#### Actual behaviour

When creating a boxplot with a dataset where the number of observations per category is not always the same, the X axis goes into some weird state (it seems as though the values of the observations somehow determine the limits of the x-axis instead of the number categories).

#### Live demo with steps to reproduce

Consider the following example from the highcharts demo page: [https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/box-plot/](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/box-plot/). Lines 44 to 48 define a dataset with 5 observations for 5 experiments. The boxplot displays correctly.

Now consider the following example, which was slightly modified on line 44: [https://jsfiddle.net/brks5avd/](https://jsfiddle.net/brks5avd/). The dataset for experiment no. 1 has an additional observation and the x-axis is totally thrown off for some reason.

#### Product version
Highcharts v6.1.0

#### Affected browser(s)

Tested on Firefox v60.0.2 (64-bit) and Chrome v66.0.3359.181 (64-bit)

**Comment by pawelfus** [comment]
Hi @jln-ho 

Thank you for reporting the issue. In the boxplot example, point is defined as an array of five elements: low value, first quartile, median, third quartile and high value. If you supply sixth value, then you have format as: [x-position, low, q1, median, q3, high] which will render first point on the x=760. That cause xAxis to stretch. See full description in our docs: https://www.highcharts.com/docs/chart-and-series-types/box-plot-series
