### ISSUE TITLE
writingMode in style failing

### ISSUE THREAD

**Issue by Dannybrown2710** [highcharts/highcharts#8527]
#### Expected behaviour
Trying to use writingMode to vertical-lr for Asian languages, expect the titles to show words vertically 
compared to rotated ones.
先秦先秦先秦先秦先秦先秦 to be shown like this instead of rotated

先
秦
先
秦
先
秦
先
秦
先
秦
先
秦

#### Actual behaviour
The word goes away from the chart area. Automatic position calculation is failing

#### Live demo with steps to reproduce
http://jsfiddle.net/dannybrown/q1hvdc6u/1/

#### Affected browser(s)
Chrome, didnt test anywhere else

**Comment by pawelfus** [comment]
Hi @Dannybrown2710 

Thank you for reporting this issue.

**Workaround:**
Reposition labels in `chart.events.load` and `chart.events.redraw` events: http://jsfiddle.net/BlackLabel/q1hvdc6u/18/

Snippet:
```javascript
function repositionTitles() {
  var chart = this,
    bbox;

  Highcharts.each(chart.yAxis, function(axis) {
    if (axis.axisTitle) {
      bbox = axis.axisTitle.getBBox(true);
      console.log(bbox);
      if (axis.opposite) {
        axis.axisTitle.element.style.left = axis.left + axis.width + bbox.width / 2 + axis.axisTitleMargin + 'px';
      } else {
        axis.axisTitle.element.style.left = axis.left - bbox.width - axis.axisTitleMargin + 'px';
      }
      axis.axisTitle.element.style.top = chart.plotTop - bbox.height / 2 + axis.len / 2 + 'px';


    }
  });
}
```

Usage:
```javascript
var chart = Highcharts.chart('container', {
  chart: {
    events: {
      load: repositionTitles,
      redraw: repositionTitles
    }
  },
  ...
});
```

*Internal note:*
Something seems to be broken in `css()` method, that's why workaround use `element.style` instead.

**Comment by Dannybrown2710** [comment]
Thanks for the response, would try this.

**Comment by Dannybrown2710** [comment]
But if I need to switch between languages?

**Comment by Dannybrown2710** [comment]
Great, thanks :) Found another workaround.
