### ISSUE TITLE
StackLabel is wrongly positioned when chart is inverted (e.g. bar-chart)

### ISSUE THREAD

**Issue by DirkDeWachter** [highcharts/highcharts#8528]
#### Expected behaviour
Bargraph: The stacklabels are positioned in the middle (top/bottom) of the bar.

#### Actual behaviour
Bargraph: The stacklabel positions depend on the length of the category.

#### Live demo with steps to reproduce
We started with the Stacked Bar [demo](http://docs.highcharts.com/demo/bar-stacked) and added stackLabels
```
    yAxis: {
        stackLabels: { enabled: true} }
```
To examplify the problem, we extended the categories:
```
    xAxis: {
        categories: ['Fruity Apples', 'Succulent Oranges', 'Large Pears', 'Multiple Grapes', 'Long Bananas']
    },
```
And finally we changed the size of the bars to better detect the edge of the bars
```
    plotOptions: {
        series: {
            stacking: 'normal',
            pointWidth: 50
        }
    },
```
**Live Example**

[jsfiddle](https://jsfiddle.net/9s8tgaf0/2/)
The problem lies in the calculation of StackBox.
In the fiddle we added a new version of StackBox in which we left the old code (line 4 of JS) 
`axisPos = axis.height + axis.pos - chart.plotTop, // OLD code (line 27246 of current code)`

and added new code (line 5 of JS). 
`axisPos = axis.height + (inverted? axis.top : axis.pos) - chart.plotTop, // NEW Code`
Leave out the new code to show the problem. (https://jsfiddle.net/9s8tgaf0/3/)
Add the new code to correct the problem. (https://jsfiddle.net/9s8tgaf0/2/)

#### Product version

[Latest](https://code.highcharts.com/js/highcharts.js) (6.1)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @DirkDeWachter 

Thank you for reporting this bug. We have already fixed this on our master branch: https://jsfiddle.net/BlackLabel/9s8tgaf0/6/ - fix will be included in the upcoming release (2-3 weeks).
