### ISSUE TITLE
Inconsistent behavior of setting series to undefined

### ISSUE THREAD

**Issue by piotriwojcik** [highcharts/highcharts#8529]
#### Expected behaviour
For all chart types, not setting the ```chart.series``` property (or setting it to ```undefined```) should either result in an error when rendering the chart or, alternatively, it should render an empty chart.

#### Actual behaviour
For 2D charts not setting ```chart.series``` results in rendering an empty chart and no errors thrown.
For 3D charts, the chart is not rendered and an error is thrown: ```Uncaught TypeError: Array.prototype.forEach called on null or undefined```

#### Live demo with steps to reproduce
2D chart: http://jsfiddle.net/4qaekp71/18/
3D chart: https://jsfiddle.net/V37Vv/499/

#### Product version
6.1.0

**Comment by pawelfus** [comment]
Hi @piotriwojcik 

Thank you for reporting this bug. You are right, 3D module is shouldn't throw errors in this case.

**Comment by KacperMadej** [comment]
Hi @k-sai-kiranmayee 

The suggested solution is to use API options only the way they are supported and passing `null` as a series in the series array is not.

If you have no control over how the options are defined then you at least should be able to sanitize/filter/process the options to remove this error throwing `null` before passing them into a chart constructor as the chart options.

For technical support see https://www.highcharts.com/blog/support/
