### ISSUE TITLE
Sunburst - some data labels are not visible

### ISSUE THREAD

**Issue by leandrocosta** [highcharts/highcharts#8531]
#### Expected behaviour

All labels in the following example should be visible

#### Actual behaviour

Some of them are not visible.

#### Live demo with steps to reproduce
http://bl.ocks.org/leandrocosta/raw/727747c1253044921e16288cb63da4fd/

#### Product version

v6.1.0

#### Affected browser(s)

Chrome v67.0.3396.87
Firefox v52.8.0

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

The problem is with the collision detection in the data label overlapping logic - it doesn't work correctly with rotated labels.

#### Workaround
Set `allowOverlap` to `true`: http://jsfiddle.net/highcharts/gcqfd43L/
