### ISSUE TITLE
sankey.states.hover.color is never used 

### ISSUE THREAD

**Issue by xuv** [highcharts/highcharts#8532]
#### Expected behaviour
Setting a hover color should display elements in that color when hovered.

#### Actual behaviour
The hover color is never taken into account

#### Live demo with steps to reproduce
http://jsfiddle.net/3xkpd5z2/

#### Product version
6.1.0

#### Affected browser(s)
Tested in Firefox and Chrome

**Comment by sebastianbochan** [comment]
Hi @xuv,
Thank you for the reporting. The color is ignored in the `pointAttibs` function, but I prepared you a wrap which fixes the issue.

```
  H.wrap(H.seriesTypes.sankey.prototype, 'pointAttribs', function(proceed, point, state) {

    var opacity = this.options.linkOpacity,
    		color = point.color;

    if (state) {
      opacity = this.options.states[state].linkOpacity || opacity;
      color = this.options.states[state].color || point.color;
    }
    
    return {
      fill: point.isNode ?
        color : H.color(color).setOpacity(opacity).get()
    };
  });
```

- http://jsfiddle.net/BlackLabel/9hdvtofL/

_Internal note_
@TorsteinHonsi does it make sense? If yes I will create a PR.

**Comment by xuv** [comment]
@sebastianbochan Thx for the quick response and for the fix.

**Comment by TorsteinHonsi** [comment]
@sebastianbochan Yes, makes sense! Thanks!

**Comment by mjkstudios** [comment]
I had been using the select state to change the opacity on selection. That's great that the color is now taken into consideration, but for anyone wanting the previous behavior, color must be explicitly set to a falsy value:

http://jsfiddle.net/j2Lyzt1k/

```
    states: {
      select: {
      	color: null, // defaults to #cccccc
        linkOpacity: 1
      }
    }
```
