### ISSUE TITLE
Zip archive (v6.0.0 and above) doesn't include offline API reference

### ISSUE THREAD

**Issue by peteriman** [highcharts/highcharts#8533]
Since v5.0.0 (Highcharts, Highmaps and Highstocks), the zip archive contained the offline API reference.

However, from v6.0.0 onwards (Highcharts, Highmaps and Highstocks), the zip archive no longer contains the offline API reference.

Would you be so kind to update the build routines to once again include the offline API reference?
(similar to #4991)

**Comment by pawelfus** [comment]
@jon-a-nygaard FYI

**Comment by peteriman** [comment]
Hi, the new v7.2.0 still does not include the offline API reference.
The build routine must have been changed during v6.0.0.

**Comment by jon-a-nygaard** [comment]
Hi @peteriman, apologies for the long wait.

We will bring up this topic on our next team meeting in the following week, and see if we can reach a conclusion on how to solve this issue.

As far as I know there are currently three possible solutions considered:
- Distribute the versioned API in the zip archive (how it used to be)
- Distribute the versioned API in its own zip archive
- Add versioned sections of the API to https://api.highcharts.com. E.g. `api.highcharts.com/highcharts/6.2.0`

## Workaround
As a workaround you can consider building your own local copy of the API. This should be possible by opening a terminal and executing the following commands:
**NB!:** Requires an installation of [Node.js](https://nodejs.org/en/)
```
# Fetch and install the Highcharts project
git clone https://github.com/highcharts/highcharts.git
cd highcharts
git checkout <version_tag> # e.g git checkout v6.2.0
npm i

# Check the version of gulp
npx gulp -v

# If gulp v4
npm i node@12 --no-save
# else if gulp v3
npm i node@10 --no-save

# Build the distribution files and then build the API
npx node node_modules/gulp/bin/gulp.js scripts
npx node node_modules/gulp/bin/gulp.js jsdoc

# In older history the "gulp jsdoc" task will start a server and serve the local API build at http://localhost:9005
# If this does not happen automatically, then you should be able to run the following to serve the API at the same port
npx node node_modules/gulp/bin/gulp.js jsdoc-server

# Now you should be able to view the API at http://localhost:9005
```

**Comment by jon-a-nygaard** [comment]
This was discussed in the team meeting and it was decided on the alternative "Distribute the versioned API in its own zip archive".

**Todo:**
- Modify the distribution scripts to accommodate the decision above.
- Modify existing ZIP archives to add missing API's where possible. 
- Assign an available developer to perform these tasks ASAP.

**Comment by jon-a-nygaard** [comment]
There's a new PR #12442 that will add functionality to include the API in our distributed zip archives. This will fix the issue for releases going forward, but there is still the issue of providing the API for existing releases.

**Comment by bre1470** [comment]
This issue can only be completed by @cvasseng , @SamHoulder , @TorsteinHonsi because of permission rules.
