### ISSUE TITLE
When chart is in zoom mode then if you hide the x-axis by clicking on legends, still x-axis labels are visible on the chart. 

### ISSUE THREAD

**Issue by digambargurav** [highcharts/highcharts#8537]
#### Expected behaviour
X-Axis Values should be hide when clicked on series, when chart is in zoom mode.

#### Actual behaviour
X-Axis Values are not hiding
![zoom-graph-issue](https://user-images.githubusercontent.com/40631385/41973010-4baabe2e-7a31-11e8-91db-5a4707f3eb4d.JPG)
 when clicked on series, when chart is in zoom mode.

#### Live demo with steps to reproduce
http://jsfiddle.net/gwamsh77/13/

**Comment by pawelfus** [comment]
Hi @digambargurav 

Thanks for reporting. This is expected behaviour - Axis is hidden only when extremes are not set. When a user zooms in, then extremes are set. You can change this behaviour as per #705 issue.

Demo for you: http://jsfiddle.net/BlackLabel/gwamsh77/54/

**Comment by digambargurav** [comment]
@pawelfus  Thanks for quick reply. 
only way is to add below line?
Highcharts.Axis.prototype.hasData = function () {
    return this.hasVisibleSeries;
};

**Comment by pawelfus** [comment]
That's correct @digambargurav - issue #705 is still open.
