### ISSUE TITLE
when chart  resize，lines in navigator out of their container

### ISSUE THREAD

**Issue by dolphinfine** [highcharts/highcharts#8540]
#### Expected behaviour
when chart resize，lines in navigator adapt to their container

#### Actual behaviour
line in navigator out of its container

#### Live demo with steps to reproduce
https://jshare.com.cn/temp/JpBcgg
1.click all the legends
2.click one of the legends again

#### Product version
 Highstock JS v6.1.0 (2018-04-13)

#### Affected browser(s)
chrome，Firefox...

**Comment by sebastianbochan** [comment]
Hi @dolphinfine,
Unfortunately I was not able to open your demo for the further debugging. Could you create a new demo in the jsfiddle / jsbin service?

**Comment by dolphinfine** [comment]
Hi @sebastianbochan  ,
I transfer the code to jsfiddle a moment ago,then I found the bug was disappear. Highstock v6.1.1 has solve it.thank you very much
