### ISSUE TITLE
Cross hair labels is not displayed on y logarithmic axis

### ISSUE THREAD

**Issue by nagin** [highcharts/highcharts#8542]
#### Expected behaviour
If in highstock and highchart if y axis is logarithmic then crosshair label should be displayed (Of course crosshair labels are enabled  )

#### Actual behaviour
If in highstock and highchart if y axis is logarithmic then crosshair label  is not  displayed (Of course crosshair labels are enabled  )

#### Live demo with steps to reproduce
You make take any chart with y axis on logarithmic scale. 
#### Product version

6.1.1

**Comment by sebastianbochan** [comment]
Hi @nagin,
I tested the simplfied demo: http://jsfiddle.net/BlackLabel/abkxver4/ and works properly. Could you update my example with your minified code to introduce the issue? It will allow me to debug it.

**Comment by pawelfus** [comment]
Thanks for reporting! 

Live demo: https://jsfiddle.net/BlackLabel/voa15ktw/4/

**Comment by sebastianbochan** [comment]
_Internal note_
The last working version is 6.0.4.

**Comment by nagin** [comment]
I think issue may be in addEvent(Axis, 'afterDrawCrosshair', function (event) {
......

 crossLabel.attr({
		        text: formatOption ?
		            format(formatOption, { value: value }, chart.time) :
		            options.formatter.call(this, value),
		        x: posx,
		        y: posy,
		        // Crosshair should be rendered within Axis range (#7219)
		        visibility: value < this.min || value > this.max ? 'hidden' : 'visible'
		    });
'''''
}

here this.min & this.max are not real coordinates and that's why  crosshair labels is always hidden
