### ISSUE TITLE
Flags getting out of plot area, when the chart has fixed width.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#8546]
#### Expected behaviour

Flags, which  `y` values are out of axis extremes, should be hidden, just like in case when the chart width is not fixed.

#### Actual behaviour

All flags are always visible, whatever they are between axis extremes they overlaps other chart elements (range selector, title).

#### Live demo with steps to reproduce

JSFiddle: https://jsfiddle.net/0dach714/

**Comment by pawelfus** [comment]
Actually, it's working "fine" in 5.0.13 because rangeSelector buttons are hidden, with fixed marginTop we have the same issue: https://jsfiddle.net/BlackLabel/10y2Ljaw/1/

**Comment by spidercode** [comment]
is there any workaround using css for this issue ?

**Comment by pawelfus** [comment]
Hi @spidercode 

Issue is that `clip` is not applied to the SVG element, so without JS I don't think we can work around this issue. In JS it's a single line of code in `load` event: http://jsfiddle.net/BlackLabel/0dach714/10/

```
    chart: {
      events: {
        load: function() {
          this.series[1].markerGroup.clip(this.clipRect); // series[1] -> index of flag series
        }
      }
    },
```

**Comment by spidercode** [comment]
Thanks @pawelfus . This works just fine. Now it is causing the same problem when I call getSVG() method to export chart to Image. Is there any workaround for the same ?

**Comment by pawelfus** [comment]
Could you show when it's broken? For me it looks fine: http://jsfiddle.net/BlackLabel/0dach714/15/ (our exporting module)

**Comment by spidercode** [comment]
@pawelfus : First of all, sorry for the late reply. 

Here is the demo. 

https://jsfiddle.net/spidercode/o3hdezg1/2/

Once chart is loaded, 

- First click on **Set Extremes** button
- After that click on **Plot Annotations**
- And then, from export menu, "Download PNG Image"

**Comment by pawelfus** [comment]
@spidercode don't forget to apply workaround to each series. My example shows solution for just one series. Demo for you, with multiple flag-series: https://jsfiddle.net/BlackLabel/m8bptx3a/

Snippet:

```javascript
  chart: {
    events: {
      load: function() {
      	var chart = this;
        Highcharts.each(this.series, function(series) {
          if (series.type === 'flags') {
            series.markerGroup.clip(chart.clipRect);
          }
        });
      }
    }
  },
```
