### ISSUE TITLE
Highcharts Assembler building a bugged version of Highcharts (Tooltip Formatter Issue)

### ISSUE THREAD

**Issue by seanvgarner** [highcharts/highcharts#8547]
#### Expected behaviour
When Hovering over a Stacked Column Chart, and the Tooltip property 'shared' is set to False, the tooltip formatter callback function (if provided) should fire. 

JS Fiddle using the CDN (Which works as expected, you will see the console.log message in the console when hovering over the graph):
https://jsfiddle.net/30vue5nt/10/

#### Actual behaviour
Here is where things get interesting. If using the CDN, this behavior works as expected. I have tested this with my own code base as well as a JS fiddle highcharts demo. HOWEVER, when using highcharts-assembler to build our own custom version of the highcharts library, only including what we need, the formatter function never fires.

Here is the same JS fiddle with the assembler build of Highcharts pasted in (Notice that the formatter function does not fire-- no console.log message):
https://jsfiddle.net/30vue5nt/10/

(Takes a while to load, sorry).

####  Steps to reproduce this build of Highcharts
1 Download the latest licensed version of Highcharts from `https://github.com/highcharts/highcharts/releases` into a new directory (we will call this $PARENT) and unzip.
2 Rename the versioned directory to `highcharts` (or create a symlink).
3 Create a `custom.src.js` file in `$PARENT/highcharts/js/masters`.
4 paste the following code into `custom.src.js`: 

```
'use strict';
import Highcharts from '../parts/Globals.js';
import '../parts/SvgRenderer.js';
import '../parts/Chart.js';
import '../parts/Series.js';
import '../parts/Interaction.js';
import '../parts/AreaSeries.js';
import '../parts/BarSeries.js';
import '../parts/ColumnSeries.js';
import '../parts/LogarithmicAxis.js';
import '../parts/Responsive.js';
import '../parts/Tick.js';
import '../parts/DateTimeAxis.js';
import '../parts/PlotLineOrBand.js';
import '../parts/Stacking.js';
import '../parts/DataGrouping.js';
import '../parts/Utilities.js';
import '../parts/Options.js';
import '../parts/Dynamics.js';
import '../modules/exporting.src.js';
import '../modules/offline-exporting.src.js';
export default Highcharts;
```
5 Make sure you have the assembler installed: `npm install --save-dev highcharts/highcharts-assembler`
6 Create a `custom.builder.js` in $PARENT directory and paste the following code into it:

```
'use strict';
const build = require('highcharts-assembler');
build({
    base: './highcharts/js/masters/',
    files: ['custom.src.js'],
    output: './dist/'
});
```
7 From $PARENT, run `node custom.builder.js`.
8 Inside the newly created dist directory you will see a file called `custom.src.js`.
9 Use this Highcharts build and create a stacked column chart and see the the tooltip formatter function does not fire.

#### Product version
Highcharts v6.1.0 (Though we found this same bug on 6.0.0) we used the latest version of the highcharts-assembler.

#### Affected browser(s)
Chrome, but probably others. I couldn't find the time to test this on other browsers, but I imagine this is not a browser specific issue.

**Comment by sebastianbochan** [comment]
Hi @seanvgarner,
Thank you for the reporting.

@jon-a-nygaard any comments?

**Comment by jon-a-nygaard** [comment]
I suspect there is a dependency missing in one our parts files. Currently looking into the issue, and will come back to you as soon as I know some more.

**Comment by jon-a-nygaard** [comment]
@seanvgarner This issue is caused by the `Interaction.js` beeing loaded before `ColumnSeries.js`.
Modifying the `custom.src.js` slightly as following will fix the issue:
```javascript
'use strict';
import Highcharts from '../parts/Globals.js';
import '../parts/SvgRenderer.js';
import '../parts/Chart.js';
import '../parts/Series.js';
import '../parts/AreaSeries.js';
import '../parts/BarSeries.js';
import '../parts/ColumnSeries.js';
import '../parts/Interaction.js';
import '../parts/LogarithmicAxis.js';
import '../parts/Responsive.js';
import '../parts/Tick.js';
import '../parts/DateTimeAxis.js';
import '../parts/PlotLineOrBand.js';
import '../parts/Stacking.js';
import '../parts/DataGrouping.js';
import '../parts/Utilities.js';
import '../parts/Options.js';
import '../parts/Dynamics.js';
import '../modules/exporting.src.js';
import '../modules/offline-exporting.src.js';
export default Highcharts;
```

I am not sure what to do with the issue. Since the `Interaction.js` is optional, adding it to `ColumnSeries.js`, `PieSeries.js`, and `ScatterSeries.js` as an dependency would be incorrect. I guess the best option would be to document the order of importing better.
What do you think @TorsteinHonsi?

**Comment by seanvgarner** [comment]
Thank you! That fixes my issue. Yes I think better documentation on the
order of importing would be helpful. I am not sure if you manage
documentation for highcharts-assembler, but I think there is an opportunity
there to provide documentation that would help avoid this issue.

Thanks again,

Sean

**Comment by gvaartjes** [comment]
@seanvgarner I will look into it and see where I can improve our documentation, or find a technical solution for it.
