### ISSUE TITLE
Series.map not drawing properly in Chrome under OSX

### ISSUE THREAD

**Issue by siphr** [highcharts/highcharts#8550]
Highcharts series.map is not rendering properly exclusively on chrome.
I have verified that the chart renders properly in firefox and safari.
I have tried with GPU acceleration enabled and disabled.
I have tried with GPU blacklist enabled or disabled.

#### Expected behaviour
Polygon rendering should be correct.
![screen shot 2018-06-29 at 09 42 53](https://user-images.githubusercontent.com/786993/42082805-e1d5544a-7b80-11e8-9b59-0c9f715eb91f.png)

#### Actual behaviour
Polygons are rendered incorrectly, shapes are erratic and inconsistent.

#### Live demo with steps to reproduce
![screen shot 2018-06-29 at 09 36 08](https://user-images.githubusercontent.com/786993/42082616-5f8faaf8-7b80-11e8-8737-7ec8e09676eb.png)
![screen shot 2018-06-29 at 09 36 40](https://user-images.githubusercontent.com/786993/42082631-69d050c6-7b80-11e8-926b-b591a22fa545.png)

#### Affected browser(s)
Chrome: Version 67.0.3396.99 (Official Build) (64-bit)
Mac OSX: High Sierra 10.13.5

#### Other tested browsers
Opera: 54.0.2952.41 (Not working)
Firefox: 61.0 (Working)
Safari: 11.1.1 (13605.2.8) (Working)

Both opera and chrome use the same engine (Blink) so could be that, but it would be good to find out exactly.

**Comment by pawelfus** [comment]
Hi @siphr 

This issue should be fixed in v6.1.1 (originally it's a bug in Chrome) - which version do you have?

**Comment by siphr** [comment]
Hi @pawelfus, as mention in the issue the version is 67.0.3396.99, I know there was something like this in the past, perhaps it has re-emerged?

**Comment by TorsteinHonsi** [comment]
Hi @siphr, probably you are not on the latest _Highcharts_ version. This looks like a duplicate of #8442, which was fixed in Highcharts v6.1.1.

**Comment by siphr** [comment]
@TorsteinHonsi Thanks for sharing the issue. I'll double check at my end and get back to you guys shortly.

**Comment by siphr** [comment]
@TorsteinHonsi :+1: That did it. Thanks a lot. The world makes sense again.
