### ISSUE TITLE
Histogram plot might not show some bins

### ISSUE THREAD

**Issue by gamer01** [highcharts/highcharts#8554]
#### Expected behaviour
histogram shows all data irrespective of the number of bins

#### Actual behaviour
if the data and the binnumber is badly choosen, the last bin will not be displayed (data: 39,50,60; bins:5)

#### Live demo with steps to reproduce
* 5 bins: https://jsfiddle.net/4fdqmu30/2/
* 10 bins, even much worse: https://jsfiddle.net/4fdqmu30/3/

#### Product version
Highcharts 6.1.1

#### Affected browser(s)
i think its independent of browser (tested Firefox and Chrome)

**Comment by gamer01** [comment]
after playing arround with the bin number a bit, i suppose it is a rounding issue. It seems as if the datapoints fall between the bins and are therefore not covered.

**Comment by sebastianbochan** [comment]
Hi @gamer01,
Thank you for reporting. 
This is duplicate of https://github.com/highcharts/highcharts/issues/8519
