### ISSUE TITLE
ErrorBar changes Axis unexpectedly

### ISSUE THREAD

**Issue by paulo-raca** [highcharts/highcharts#8558]
#### Expected behaviour
The presence of the ErrorBar should not affect the axis scale, and the width of error bar should not change unexpectedly for different datasets (It should probably have the same default as the marker size)

#### Actual behaviour

Axis ticks move around with minor changes to the data, and the errorBar width is unpredictible.

#### Workaround

I've found that adding
```
pointWidth:20,
pointRange:0,
```
to the errorBar series does what I want, but that really shouldn't be necessary.

#### Live demo with steps to reproduce

This demos show how changing a little the X position of one of my (non extreme) points moves my X axis around and modifies the width of the error bar.

https://jsfiddle.net/51uh84v9/

#### Product version
Highcharts JS v6.1.1 (2018-06-27)

#### Affected browser(s)
Probably browser-agnostic, tested with Google Chrome 66.0.3359.139 64 bits for Linux

**Comment by paulo-raca** [comment]
I also find https://github.com/highcharts/highcharts/issues/5334 extremely annoying, but it's already been tracked.

**Comment by sebastianbochan** [comment]
Hi @paulo-raca,
Thank you for the reporting.

**Comment by pawelfus** [comment]
I'm not sure if this is a bug. The errorbar series is more like a column, not scatter. In the errorbar series, we don't want overlapping whiskers. That means size of the whisker depends on a range on xAxis. In your case it's not a minor change, considering xData:

- first demo: 0 - 1.5 - 3 - 4.5 - 6 - 7.5 - 9 -> minimum range between points: 1.5unit
- second demo: 0 - 0.5 - 3 - 4.5 - 6 - 7.5 - 9 -> minimum range between points: 0.5unit

Second demo reserves space for 3x more units than first demo, so size of the whisker must be decreased. I'm not sure why you need to set `pointRange`, but in general `pointWidth` should be enough: https://jsfiddle.net/BlackLabel/51uh84v9/4/

**Comment by paulo-raca** [comment]
Thanks for looking into it.
What you said make sense.

Yet it look me a long while to figure out the problem. Indeed, I've omitted error bars in the past because of this issue. :disappointed: 

Would be great if we could at least get sample / documentation updates for this kind of chart.

**Comment by paulo-raca** [comment]
Also, `pointRange` is also necessary to remove extra space before x=0.

**Comment by pawelfus** [comment]
I see, that extra padding is added to prevent rendering whiskers outside the plotting area.

We have errorbars documented here: https://www.highcharts.com/docs/chart-and-series-types/error-bar-series which leads to general options for errorbar, which includes reference to [`pointPadding`](https://api.highcharts.com/highcharts/plotOptions.errorbar.pointPadding) and [`groupPadding`](https://api.highcharts.com/highcharts/plotOptions.errorbar.groupPadding) (and all other options). It works the same way for all other types.. Do you mean we should create more examples for errorbar series type?

**Comment by paulo-raca** [comment]
Also related: #6548

**Comment by paulo-raca** [comment]
:thinking:  Maybe we could we change the default behavior to stay the same when linked to a column series, and be fixed-fixed when linked to other types of series?

**Comment by paulo-raca** [comment]
An example like this would have helped me a lot: https://jsfiddle.net/96ps03vg/

**Comment by pawelfus** [comment]
Thanks for sharing! I agree with you, we should add this example to our docs.
