### ISSUE TITLE
Pie chart disappears after mouseover

### ISSUE THREAD

**Issue by Elise194** [highcharts/highcharts#8559]
Hi! 

I have pie chart and I generate data for it by using data attributes of other element. 
When I refresh values of this attributes with ajax and use chart.setData(...) it refresh my chart with new values, but after mouseover event parts of chart dissapears and I see only their labels. 

view:
`<div id="graph-rounded"></div>`

```
<div class="additional-graph-info"
     data-names='<?= $names?>'
     data-values='<?= $maxValues ?>'></div>
```

js:
```
  chart = Highcharts.chart('graph-rounded', {
        chart: {
            type: 'pie'
       },
 series: [{
            type: 'pie'
            data: browserData,
           }
      }],

```

and in ajax I do this:
```
 $.ajax({
            url: '/get-right-diagram',
           type: "POST",
             success: function (data) {
                   $('.js__right-diagram-widget').html(data); //here I refresh data attributes
              ... 
              //here I set new browserData
              ....

                  chart.series[0].setData(
                        browserData
                    );
                }
          });
```

**Comment by sebastianbochan** [comment]
Hi @Elise194,
Please let me know if it is possible to send us a live demo of your chart? It will allow us to debug it, because at this moment it is really difficult to replicate the issue.

**Comment by Elise194** [comment]
OMG error was in the color -_-

**Comment by sebastianbochan** [comment]
Hi @Elise194,
Thank you for the feedback.
