### ISSUE TITLE
Error occurs when legend covers plot area

### ISSUE THREAD

**Issue by AlisonNiu** [highcharts/highcharts#8562]
#### Expected behaviour
Should no error show in chrome console
#### Actual behaviour
Error: <rect> attribute width: Expected length, "NaN". this error show in chrome console.

#### Live demo with steps to reproduce
http://jsfiddle.net/pj0oLzqm/1/
[Edit: Need a fixed width to reliably reproduce:] http://jsfiddle.net/highcharts/pj0oLzqm/5/

When legend is long and xAxis length is 0.  first load or drage graph window will show the error message.
#### Product version

Highstock JS v6.1.1 (2018-06-27)
#### Affected browser(s)
chrome, firfox

**Comment by sebastianbochan** [comment]
Hi @AlisonNiu,
Thank you for the reporting.

**Internal note**
The issue appears only in the Highstock, in Highcharts works well: http://jsfiddle.net/BlackLabel/0njqz724/

**Comment by pawelfus** [comment]
*Internal note:*
It comes from `navigatorSize` which is.. 0px. When we try to calculate range we are dividing by 0. 

**Workaround:**
Chart is unusable anyway (legend covers 99% of the chart), so I suggest to set [`legend.itemWidth`](https://api.highcharts.com/highstock/legend.itemWidth): http://jsfiddle.net/BlackLabel/pj0oLzqm/11/
