### ISSUE TITLE
Consider providing public zoom methods

### ISSUE THREAD

**Issue by gilmoreorless** [highcharts/highcharts#8563]
I get a lot of value out of the select-to-zoom functionality. However there have been a few times when I've wanted to achieve the same effect programmatically.

For example, I'd like to highlight an interesting variance in some data. At the graph's default scale (which encompasses all the data), the variance is too small to see. Users can click-and-drag several times to focus in on the variance, but they might not know where to look. I'd like to be able to add a button which, when clicked, will zoom the chart to highlight the specific subset of data. This should behave the same way as users doing it themselves (e.g. the "Reset zoom" button appears).

So far I've not found any public API that allows me to do this. I've tried using `axis.setExtremes`, but this doesn't show the "Reset zoom" button. The `Chart` and `Axis` prototypes both have `zoom` methods that mostly do what I want, but they're marked private and undocumented. This means I can't rely on them staying the same between releases.

It would be great value if you could provide a public API method to zoom a chart in to a particular region, with all the same behaviours as select-to-zoom. Ideally there would also be an equivalent way to zoom out to default scale (i.e. the same behaviour as a user clicking "Reset zoom").

**Comment by sebastianbochan** [comment]
Hi @gilmoreorless,
Thank you for contacting us.
You can use `axis.setExtremes` in combination with `chart.showResetZoom();`

Demo:
- http://jsfiddle.net/BlackLabel/gqbz68yx/

ps For the general [support](http://www.highcharts.com/support) questions, please use our stackoverflow / forum or email.

**Comment by gilmoreorless** [comment]
Thanks for the quick reply. Apologies for posting this in the wrong place, I'll remember for next time.

Unfortunately your solution suffers from the same problem as my opening description: `chart.showResetZoom()` is an undocumented private method. There is no **documented public** method that allows control of this behaviour.

**Comment by sebastianbochan** [comment]
Hi @gilmoreorless,
The function will be documented in our official API in the nearest days.

**Comment by bre1470** [comment]
Wait.

**Comment by bre1470** [comment]
@TorsteinHonsi Can we make `Chart.showResetZoom` a official public function in `Interaction.ts`?

**Comment by bre1470** [comment]
Torstein's answer was:
```
OK :)
```
