### ISSUE TITLE
Depth of Market example

### ISSUE THREAD

**Issue by finethanks** [highcharts/highcharts#8564]
#### Example
Hello, how I can create chart like "depth of market" with Highcharts?

<img width="943" alt="screen shot 2018-07-03 at 11 37 03" src="https://user-images.githubusercontent.com/2275434/42208821-d6ec7918-7eb5-11e8-8469-df984bc8e740.png">

**Comment by sebastianbochan** [comment]
Hi @finethanks,
Thank you for contacting us. The github is our bugtracker, so please use forum / stackoverflow or email for the further [support](http://www.highcharts.com/support) questions.

Ps. example of depth chart: 
- https://jsfiddle.net/daniel_s/tc7dswjd/

**Comment by finethanks** [comment]
Oh, thank so much! Sorry for posting in issues.
