### ISSUE TITLE
plotOptions.series.dataLabels.filter documentation gives incorrect advice

### ISSUE THREAD

**Issue by benelliott** [highcharts/highcharts#8566]
The documentation for `plotOptions.series.dataLabels.filter` states the following:

>  For programmatic control, use the formatter instead, and return `false` to disable a single data label.

As can be seen [here](http://jsfiddle.net/h51mazky/4/), returning `false` from the formatter does not disable a data label; in fact if you resize the window the data labels actually show the string `"false"`. The correct approach to filter out data labels is actually to return `undefined`, as shown [here](http://jsfiddle.net/dy42a0pg/2/). Not only does this hide the `"false"` string, but it also refrains from creating the data label element at all.

The documentation should be amended to fix this.

**Comment by sebastianbochan** [comment]
Hi @benelliott,
Thank you for reporting. We will fix it as soon as possible.

**Comment by benelliott** [comment]
@sebastianbochan Thanks. Would be happy to submit a PR but don't know where the documentation lives?
