### ISSUE TITLE
mouseOut event not firing on mobile when zoomed

### ISSUE THREAD

**Issue by KevinShiCA** [highcharts/highcharts#8578]
#### Expected behaviour
Given a `plotOptions.series.point.events.mouseOut` callback, it should be called when the user mouses out of a data point.

#### Actual behaviour
It works on all desktop browsers, but does not work on mobile when zoomed. 

#### Live demo with steps to reproduce
Fiddle: https://jsfiddle.net/L7boz4pv/12/

Steps to reproduce:
1. Open the fiddle on a desktop browser
2. Mouse over some bars, notice that the bottom text changes to `MOUSE OVER` when the mouse enters the data point (triggering the tooltip), and changes to `MOUSE OUT` when the mouse leaves (dismissing the tooltip)
3. Open the fiddle on a mobile browser
4. Tap on one of the bars, notice that the bottom text changes to `MOUSE OVER` (triggering the tooltip)
5. Tap elsewhere, notice that the bottom text changes to `MOUSE OUT` (dismissing the tooltip)
6. Pinch to zoom in
7. Tap on one of the bars, notice that the bottom text changes to `MOUSE OVER` (triggering the tooltip)
8. Tap elsewhere, notice that the bottom text does not change and the tooltip is not dismissed

#### Product version
6.1.0

#### Affected browser(s)
Tested on: iOS Safari, Android Chrome

**Comment by pawelfus** [comment]
Hi @KevinShiCA 

Thank you for reporting this bug. Temporary workaround: https://jsfiddle.net/BlackLabel/L7boz4pv/77/ - could you test and let us know the results? Snippet:

```javascript
(function(H) {

  H.Pointer.prototype.touch = function(e, start) {
    var chart = this.chart,
      hasMoved,
      pinchDown,
      isInside;

    if (chart.index !== H.hoverChartIndex) {
      this.onContainerMouseLeave({
        relatedTarget: true
      });
    }
    H.hoverChartIndex = chart.index;

    if (e.touches.length === 1) {

      e = this.normalize(e);

      isInside = chart.isInsidePlot(
        e.chartX - chart.plotLeft,
        e.chartY - chart.plotTop
      );
      if (isInside && !chart.openMenu) {

        // Run mouse events and display tooltip etc
        if (start) {
          this.runPointActions(e);
        }

        // Android fires touchmove events after the touchstart even if
        // the finger hasn't moved, or moved only a pixel or two. In iOS
        // however, the touchmove doesn't fire unless the finger moves
        // more than ~4px. So we emulate this behaviour in Android by
        // checking how much it moved, and cancelling on small
        // distances. #3450.
        if (e.type === 'touchmove') {
          pinchDown = this.pinchDown;
          hasMoved = pinchDown[0] ? Math.sqrt( // #5266
            Math.pow(pinchDown[0].chartX - e.chartX, 2) +
            Math.pow(pinchDown[0].chartY - e.chartY, 2)
          ) >= 4 : false;
        }

        if (!start && H.pick(hasMoved, true)) {
          this.pinch(e);
        }

      } else if (start) {
        // Hide the tooltip on touching outside the plot area (#1203)
        this.reset();
      }

    } else if (e.touches.length === 2) {
      this.pinch(e);
    }
  };
})(Highcharts);
```

*Internal note:*
Everything leads to this lines: 

https://github.com/highcharts/highcharts/blob/ce695f114322050be11df61b05eae5df99ad63d4/js/parts/TouchPointer.js#L288-L304

I suggest to change:

```javascript
if (pick(hasMoved, true)) {
  this.pinch(e);
}
```

To
```javascript
if (!start && pick(hasMoved, true)) {
  this.pinch(e);
}
```

@TorsteinHonsi - what do you think? I'm not sure about Android vs iOS difference with touchstart&touchmove - should `pinch` always be called?

**Comment by KevinShiCA** [comment]
@pawelfus Your workaround works, but it is not worth adding so many lines for such a small bug. I will wait for an internal fix.
