### ISSUE TITLE
Apply border to full stacked bar

### ISSUE THREAD

**Issue by PrathikGBS** [highcharts/highcharts#8587]
I am unable to apply the border to the entire stacked bar, instead, it applied borders to the individual bar.
Is there any way I can do this?

http://jsfiddle.net/Lh98dcu6/1/

**Comment by sebastianbochan** [comment]
Hi @PrathikGBS,
This is our bugtracker, so for general [support](http://www.highcharts.com/support) questions, please use stackoverflow / forum or email.
