### ISSUE TITLE
Regarding Logarithmic scale in Highcharts

### ISSUE THREAD

**Issue by aarthivijiaarthi1** [highcharts/highcharts#8588]
Regarding logarithmic scale in highcharts: 

When we use logarithmic scale in highcharts, the axis values depends on the data. If we provide data with the least value in range of 100's, the minimum in yaxis starts with 100 and if the data almost falls in the same interval, the axis contains values other than powers of 10.  While, in excel, however the data is, the axis starts with 1 and goes in powers of 10. Please find attached image. How do we achieve this in highcharts without setting any properties like min, tickInterval explicitly. 

Excel Image: 
![image](https://user-images.githubusercontent.com/36232611/42438558-f6e94da0-837d-11e8-9562-ce6f2187e997.png)

Highcharts Image:
![image](https://user-images.githubusercontent.com/36232611/42439436-8a65045a-8380-11e8-805e-bd8af3d01d35.png)

Example JsFiddle:
https://jsfiddle.net/1jczwn7m/23/

**Comment by pawelfus** [comment]
Hi @aarthivijiaarthi1 

You posted on our bug tracker, for questions please use our forum, stackoverflow or contact us directly. 

PS: You probably want to use [`yAxis.softMin`](https://api.highcharts.com/highstock/yAxis.softMin), however I think `tickInterval` and `min` is a right way to to that.
