### ISSUE TITLE
Toggling highstock navigator enabled/disabled pushes chart upward

### ISSUE THREAD

**Issue by itsjohnward** [highcharts/highcharts#8595]
#### Expected behaviour

Toggling navigator enabled true/false works as expected in 6.1.0: chart height toggles between having a bottom margin 0 vs bottom margin equal to the height of the navigator. Returns to the same height each time.

#### Actual behaviour

In 6.1.1, the bottom margin is additive each time the navigator is re-enabled. So the chart gets squashed further and further up toward the top of the container.

#### Live demo with steps to reproduce

6.1.0: http://jsfiddle.net/itsjohnward/mdz90Lwu/
6.1.1: http://jsfiddle.net/itsjohnward/9mwtn1vp/

#### Product version

Highstock 6.1.1

#### Affected browser(s)

Observed in Chrome 69.0.3473.0

**Comment by pawelfus** [comment]
Hi @itsjohnward 

Thank you for reporting this regression! 

*Internal note:*
Bisect leads to ed0cc64df
