### ISSUE TITLE
candlestick custom property display undefined in tooltip at  a large date range

### ISSUE THREAD

**Issue by dolphinfine** [highcharts/highcharts#8596]
#### Expected behaviour
custom property display normal in tooltip at  a large date range
#### Actual behaviour
custom property display undefined in tooltip at  a large date range

#### Live demo with steps to reproduce

http://jsfiddle.net/9mwtn1vp/14/
1.when rangeSelector is '1m',custom property 'prevClose' display normal in tooltip.
2.click rangeSelector of '6m' or more,custom property 'prevClose' display undefined in tooltip 
#### Product version

highstock 6.11.1
#### Affected browser(s)
only test chrome,firefox

**Comment by sebastianbochan** [comment]
Hi @dolphinfine,
The issue is related with enabled dataGrouping. If you have huge amount of data, points are grouped (by x/y values) and custom parameters are ignored. Its related with fact that Highstock is not able to calculate value of custom parameter.
