### ISSUE TITLE
Line chart is not drawing the lines if opened in unfocused tab

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#8599]
#### Expected behaviour
Chart should renderer correctly when opened in unfocused tab.

#### Actual behaviour
Currently, when chart is opened in new, unfocused tab, sometimes lines in chart are not drawn correctly - only markers are shown. 

After hovering the series lines are visible.

![screen shot 2018-07-10 at 12 07 57](https://user-images.githubusercontent.com/15050812/42503834-ff5e4640-8439-11e8-9a38-ff72f42dd244.png)

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/line-basic

Click on "edit in jsFiddle" so it will open in unfocused, new tab.

The issue should be visible more or less one time per 10 clicks.

#### Product version
Highcharts 6.1.1.

#### Affected browser(s)
Chrome 65.0.3325.181
Chrome 67.0.3396.99

**Comment by Denyllon** [comment]
I'm able to reproduce it only on Chrome browser, but in a slightly different way.
When I click "Edit in JSFiddle" and tab is loading, then I change the tab to other already opened one. Finally, when the tab is loaded, then I'm switch to it and see the same effect, but only then.

**Comment by sebastianbochan** [comment]
The problem is fixed since 7.0.3. Please reopen the ticket if issue will come again.

Chrome:  72.0.3626.119
