### ISSUE TITLE
PDF export removes part of the Gantt chart when there is large data set

### ISSUE THREAD

**Issue by saranga-rathnayake** [highcharts/highcharts#8600]
#### Expected behaviour
PDF export should export entire chart
#### Actual behaviour
PDF export removes part of the Gantt chart when there is large data set

#### Live demo with steps to reproduce

https://jsfiddle.net/t0r8qz9p/2420/
![gantt-pdf-export-issue](https://user-images.githubusercontent.com/22959475/42505629-f3ccd062-845c-11e8-9e71-a993e3b8488d.jpg)

#### Product version

Highcharts JS vgantt (2018-07-09)

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thank you for reporting this issue!
