### ISSUE TITLE
Custom Highchart JS Issue

### ISSUE THREAD

**Issue by shwetakhati** [highcharts/highcharts#8601]
#### Actual behaviour
When I compile the code from highchart custom builder  I got compilation error.
Steps I followed to create the  custom build highchart file 
1.	I select the options in Download Builder(Experimental). (selected options are specified below)
2.	Click on build buttom to build the js file.
3.	Download the “highcharts-custom.js” file.
4.	Copy the code of “highcharts-custom.js” file into Closure Compiler Service UI.
5.	Got the below error.
![googlecompiler](https://user-images.githubusercontent.com/40982750/42509522-d28bb76c-8469-11e8-86a0-a69dbe252772.jpg)
Also try to compile with another compiler  https://repl.it/repls/SoftEntireDimensions showing  error.
![replcomplier](https://user-images.githubusercontent.com/40982750/42509602-0beb7df8-846a-11e8-8b0c-56760d5e82d0.jpg)

Can please help me in this issue I need custom build highchart js?

I have included all the available options from below functions in build :

1. FEATURES
2. Dynamics and Interaction
3. Chart and Series types
4. Stock
5. Modules
Not included options in build are :
1. Renderers
2. Maps

**Comment by KacperMadej** [comment]
Hi @shwetakhati 

You mentioned 

> selected options are specified in below mail

but the info is not attached. The problem is based or seems to be based on custom build, so please specify it.

**Comment by shwetakhati** [comment]
I have included all the available options from below functions in build
1.	FEATURES
2.	Dynamics and Interaction
3.	Chart and Series types
4.	Stock
5.	Modules
Not included options in build are :
1.	Renderers
2.	Maps

**Comment by shwetakhati** [comment]
Can please help me in this issue I need custom build highchart js?

I have included all the available options from below functions in build :

1. FEATURES
2. Dynamics and Interaction
3. Chart and Series types
4. Stock
5. Modules
Not included options in build are :
1. Renderers
2. Maps

**Comment by KacperMadej** [comment]
Custom code builds elements into wrong order and the error comes from `broken-axis` part loaded before `ColumnSeries`.

**Comment by shwetakhati** [comment]
How to build the highchart custom js file?
I also removed all the components from modules part then also error is coming while compiling.

**Comment by KacperMadej** [comment]
@shwetakhati Please try with possible options explained in general documentation: https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files

The builder on download site is not a finished product and is still in beta, but thank you for reporting about the problem with it - we'll be working on resolving the issue and this is why this issue is open and labeled `bug`.
