### ISSUE TITLE
Highstock: Dynamically added axes do not have same defaults

### ISSUE THREAD

**Issue by whawker** [highcharts/highcharts#8603]
#### Expected behaviour
Default axis options are applied to dynamically added axes (via `chart.addAxis()`)

#### Actual behaviour
Default options not applied, meaning default options like `ordinal` are not used

#### Live demo with steps to reproduce
https://jsfiddle.net/brojuf06/1/

In the demo above note how in the first chart, the xAxis is `ordinal: true` and has no gap. However in the second chart the default options are *not* applied, so a gap in the data is present.

Seems to be related to [this section](https://github.com/highcharts/highcharts/blob/master/js/parts/StockChart.js#L160-L214) of the code, where default are applied for `Highcharts.stockChart()` but no defaults are applied to `chart.addAxis`

#### Product version
Highstock 6.1.1

#### Affected browser(s)
All

**Comment by whawker** [comment]
Judging by the inactivity, I guess this is a won't fix?

**Comment by pawelfus** [comment]
Hi @whawker 

This ticket wasn't prioritized. At this moment please provide all of the options to `addAxis` you need to use. My apologies for the inconvenience!
