### ISSUE TITLE
Lack of properties description "height" and "width" in Highstock.series.flags API Reference

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#8604]
#### Behaviour
Two properties - **height** and **width** - that are not in the API (but should be). We can find them used in demo.

#### Live demo with steps to reproduce

We use **width: 16** here:
https://www.highcharts.com/stock/demo/flags-shapes

But no mention about it here:
https://api.highcharts.com/highstock/series.flags

#### Product version
Highstock 6.1.1

**Comment by sebastianbochan** [comment]
Hi @raf18seb,
Thank you for reporting, we will add it as soon as possible.
