### ISSUE TITLE
Offline export to PNG doesnt work when using useHTML: true in legend

### ISSUE THREAD

**Issue by aviramga** [highcharts/highcharts#8605]
#### Expected behaviour

Offline export to PNG should work with useHTML: true in the config legend

#### Actual behaviour

Tries to go to the remote server for processing

#### Live demo with steps to reproduce
http://jsfiddle.net/zL862x5h/14/

exporting png to image will not work unless you change the legend -> useHTML to false

#### Product version
latest

#### Affected browser(s)
 all

**Comment by aviramga** [comment]
@sebastianbochan I've updated the js fiddle, make sure the useHTML under legend is set to true to reproduce this issue

**Comment by sebastianbochan** [comment]
Hi @aviramga,
Thank you for updated demo, now is reproducible.
