### ISSUE TITLE
scrollablePlotArea - when used, tooltips appear beneath the labels overlay

### ISSUE THREAD

**Issue by boyanfi** [highcharts/highcharts#8607]
When the scrollablePlotArea is enabled and the chart is scrollable horizontally, when a tooltip needs to be shown it should always be on top.

Currently, when scrolled to the right, the tooltip can appear below the semi-transparent labels area (see screenshot)

![image](https://user-images.githubusercontent.com/27766481/42561969-d0dfa874-84fa-11e8-9d7d-9dd98b910e53.png)

highcharts for 6.1.0 and react-highcharts 16.0.2, on all browsers

**Comment by KacperMadej** [comment]
Hi @boyanfi 

Thank you for reporting about the problem.

Live demo: http://jsfiddle.net/BlackLabel/9nywdLre/

Steps: hover points under the mask or right side of the chart

**Comment by TorsteinHonsi** [comment]
_Internal note_
This should be fixed by
* Forcing `tooltip.outside` when in scrollable mode, and
* Setting the default z-index of the tooltip renderer to 3
