### ISSUE TITLE
Yaxis labels doesn't appear when adding axis using addAxis method with redraw parameter enabled to a chart without data.

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#8609]
#### Expected behaviour
addAxis method with redraw parameter enabled should render axis with labels even when chart is empty

#### Actual behaviour
axis labels doesn't appear when chart is empty

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/z26grxtw/

1. Click the first button with redraw disabled - labels are rendered correctly
2. Run jsfiddle again
2. Click the second button with redraw enabled - labels are not rendered

#### Product version
Highcharts

#### Affected browser(s)
all

**Comment by TorsteinHonsi** [comment]
This works as intended now (v8.0.0)
