### ISSUE TITLE
Rotation of labels is not supported in the annotations part of the API

### ISSUE THREAD

**Issue by lookermagic** [highcharts/highcharts#8611]
#### Expected behaviour
`annotations.labels` objects (and/or `annotations.labelOptions`) to have a `rotation` property that rotates the text of the label similar to `xAxis.labels.rotation`.

#### Actual behaviour
No apparent way to rotate annotations labels from within the API

#### Product version
Highcharts v6.1.1

**Comment by sebastianbochan** [comment]
Hi @lookermagic,
The option is not available yet, so I marked your suggestion as enhancement.

**Comment by lookermagic** [comment]
@sebastianbochan thanks kindly! We'll certainly be making use of it once it's made it in. Anything I can do to add urgency to this suggestion?

**Comment by sebastianbochan** [comment]
Hi @lookermagic,
We are developing new version of annotation and by callback it should be available. Please stay on track with out newsletter and this thread.

**Comment by lookermagic** [comment]
@sebastianbochan good to hear. We're using annotations pretty aggressively to fill gaps in the current default labels implementation, so the sooner the better.
