### ISSUE TITLE
Boost.js - Series data label are not working for Scatter series

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#8612]
Series data labels are working for Line series chart.
https://jsfiddle.net/tejaspchordiya/rwtdgq7s/2/

Series data labels are not working for Scatter series chart.
https://jsfiddle.net/tejaspchordiya/2vcn9syp/2/

**Comment by tejaspchordiya** [comment]
Try Zoom in the examples that I shared, you will be able to reproduce the issue.

**Comment by cvasseng** [comment]
Data labels are not supported in boost, and are unlikely to be in the near future as text rendering in general is not supported by the WebGL renderer.

The reason it appears to work when you zoom in is that you're zooming below the boost threshold so the SVG renderer "takes over" and the chart is no longer boosting.

**Comment by TorsteinHonsi** [comment]
I'm tempted to label this a _won't fix_. The whole idea of boost is to save rendering time by eliminating features (in addition to WebGL support), and data labels don't make sense for heavy data sets. Like in the OP examples, a 100k data labels would make no sense. This is what the boostThreshold is for.

**Comment by cvasseng** [comment]
Yes, I agree also.
