### ISSUE TITLE
Sunburst chart:How to add space between levels ?

### ISSUE THREAD

**Issue by wangnan1305** [highcharts/highcharts#8614]
#### Expected behaviour
Excuse me,I want to achieve this sunburst chart that has some space on the different levels.Examples are as follows:

![2018-07-12 8 19 22](https://user-images.githubusercontent.com/11911901/42633041-cba02b96-8611-11e8-954e-143e29cf3e55.png)

And i try to use highcharts v6.1.1 api, only  **borderWidth** and **borderColor**  are controled the space of each slice. Finally, i can,t  achieve the effect of the above picture.
#### Actual behaviour

<img width="648" alt="2018-07-12 8 24 16" src="https://user-images.githubusercontent.com/11911901/42633051-d51fceba-8611-11e8-8b29-ca558fa22e64.png">

#### Live demo with steps to reproduce

[demo](https://jshare.com.cn/temp/BMZcwi)
#### Product version

Highcharts v6.1.1
#### Affected browser(s)
chrome latest version

**Comment by KacperMadej** [comment]
Hi @wangnan1305 

There's no such feature implemented for sunburst series for now.

**As a workaround** 
- you could use multiple pie / donut series: https://jsfiddle.net/BlackLabel/v0qxL1ct/
- or add a fake level to the sunburst chart that will look like a break: https://jsfiddle.net/BlackLabel/tekh7mo3/
