### ISSUE TITLE
xAxis labels are overwritten by chart when rangeSelector is dynamically disabled

### ISSUE THREAD

**Issue by tinu232** [highcharts/highcharts#8617]
#### Expected behaviour

When rangeSelector is disabled, xAxis labels should stay outside the chart.

#### Actual behaviour

Chart is overwriting the xAxis labels.
_This happens when yAxis top is set._

Not so dramatically for chart display only (don't know any use case to dynamically enable/disable the rangeSelector), but for export, when rangeSelector is disabled in exporting options.

#### Live demo with steps to reproduce

https://jsfiddle.net/4ekcw3vg/
Press "Disable rangeSelector"

#### Product version

Current master branch

#### Affected browser(s)

Chrome Version 56.0.2924.87 (64-bit)

**Comment by KacperMadej** [comment]
Hi @tinu232 

Thank you for reporting about the issue. To have xAxis match yAxis you could set `top` for xAxis too. https://jsfiddle.net/BlackLabel/4ekcw3vg/1/
If you are setting `top` axis position then position will not be recalculated, but size will be, so you could set `height` too.

Not sure if this is a bug, more like a partial usage of API options. To set `top` for an axis do it for all connected x and y axes.

**Comment by tinu232** [comment]
Hi @KacperMadej 

Thanks for your comments!

We are using `yAxis.top` to separate e.g 2 diagrams with 2 different units.
See https://jsfiddle.net/4ekcw3vg/26/

Strange, in this combination there is no overwrite of the xAxis labels on disabling the rangeSelector, even when `xAxis.top` is not set...

**Comment by KacperMadej** [comment]
@tinu232 
In the last demo you are setting height for axes - remove it and it will work the same as in the first demo.
Use percentage values and it works fine: https://jsfiddle.net/BlackLabel/4ekcw3vg/27/
