### ISSUE TITLE
Array some polyfill error

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#8619]
Hi, I found pie chart run out error in IE8,  this is caused by `H.some` polyfill name 

in `Utilities.js` is `H.somePolyfill` 
https://github.com/highcharts/highcharts/blob/e9082f1ed28e2df2e3b04f1998a5a3227247b4ac/js/parts/Utilities.js#L1537-L1539

but in oldie.js is `H.some` (should be `H.somePolyfill`)
https://github.com/highcharts/highcharts/blob/e9082f1ed28e2df2e3b04f1998a5a3227247b4ac/js/modules/oldie.src.js#L142-L153

**Comment by pawelfus** [comment]
Nice catch @zhy1stgg ! Thank you for reporting.
