### ISSUE TITLE
Highcharts demo page incorrectly configures the donut chart.

### ISSUE THREAD

**Issue by NotionCommotion** [highcharts/highcharts#8623]
https://www.highcharts.com/demo/pie-donut uses the yAxis property, however, according to https://www.highcharts.com/docs/chart-concepts/axes, it shouldn't be used for pie charts.  If it shouldn't be used, please remove it from the demo example.  Thank you

```
yAxis: {
        title: {
            text: 'Total percent market share'
        }
    },
```

**Comment by sebastianbochan** [comment]
Hi @NotionCommotion,
Thank you for the suggestion. I will fix it as soon as possible.
