### ISSUE TITLE
setData() not working fine on StockChart

### ISSUE THREAD

**Issue by sanderzz91** [highcharts/highcharts#8624]
#### Expected behaviour
Hi, I think setData() should work just as fine as addPoints() on a StockChart, so you can add points in bulk every few seconds to a chart.

#### Actual behaviour
For StockCharts, setData() actually leads to incomplete series data arrays and incomplete charts.

#### Live demo with steps to reproduce
http://jsfiddle.net/hvrednas/mf4yu62c/127/
(Note: I notice that the template mentioned in the "new issue" template (jsfiddle.net/highcharts/llexl/) is gone.)

#### Product version
Highstock JS v6.1.1 (2018-06-27)
Highcharts JS v6.1.1 (2018-06-27) Boost module

#### Affected browser(s)
Reproducible in Firefox 61.0.1, Chrome Version 67.0.3396.99 (Official Build) (64-bit)
Could not test the jsfiddle in IE 11.

**Comment by pawelfus** [comment]
Hi @sanderzz91 

Thank you for reporting this bug. It looks like a regression, v5.0.12 works better: http://jsfiddle.net/BlackLabel/vq6mcd7r/

*Internal note:*
Bisect leads to d6f2ef4ab

**Comment by zane2007** [comment]
Also, after using setData(), addPoint() method doesn't properly redraw the chart. http://jsfiddle.net/twru23pf/18/
Please, confirm that issue and if it possible, write a workaround. Thanks.

**Comment by pawelfus** [comment]
@zane2007 - this works as expected. You add point without x-value, so x-value is automatically incremented (0, 1, 2...) that means you add points **at the beginning** of the dataset (`01.01.1970 00:00:00.001`, `01.01.1970 00:00:00.002`, etc.)

**Comment by zane2007** [comment]
@pawelfus Oh, how can I've missed that? Thanks a lot. You've saved my day!
