### ISSUE TITLE
hciconarray in library(highcharter) for R is not working

### ISSUE THREAD

**Issue by clintdk** [highcharts/highcharts#8625]
#### Expected behaviour
In hciconarray() I want to change the colors of the icons and I want to appoint the right icons to the right label. 

    #icons define
    iconen <- c("male", "female")
    iconslabel <- c("Mannen","Vrouwen")
    #create dataset (same order as icons)
    number_of_icons <- 100
    n_male <- round(dataset$percentagemannen*number_of_icons)
    n_female <- round((1-dataset$percentagemannen)*number_of_icons) 
    n <- c(n_male,n_female) #format as icons 
    
    #control if data is available
    no_data <- FALSE
    if(all(is.na(n) == TRUE)){ 
      no_data <-TRUE
    } else {
      no_data <- FALSE
    }
  `n <- ifelse (is.na(n)== TRUE,0,n) `
   
    #should connect the right labels with the right icons
    testyx <- ifelse(iconslabel == "Mannen", iconen[2], iconen[1])
   
 
   
    #browser()

    if (no_data == FALSE){
      #does not sort right
      hc <- hciconarray(iconslabel, n, icons = testyx, size = 5)
      hcTag <- tagList(hc) 
    } else {
      hc <- "No data available"
      hcTag <- tagList((hc)) 
    }
    hcTag
  })
 `

#### Actual behaviour
male icons are female and the other way around. But sometimes it is the other way around. On top of that the colors won't change.

**Comment by sebastianbochan** [comment]
Hi @clintdk,
Unfortunately we are not authors of the wrapper and I advise you to contact with developers of it.

http://jkunst.com/highcharter/
