### ISSUE TITLE
xAxis ticks overlap

### ISSUE THREAD

**Issue by plamens** [highcharts/highcharts#8626]
#### Expected behaviour
Tick labels are broken into several lines if there is not enough place to fit them on one.

#### Actual behaviour
Sometimes, tick labels are not broken into several lines properly and overlap with one another.

![overlapping_ticks](https://user-images.githubusercontent.com/1782459/42762944-56ea4906-891a-11e8-9ad6-2828415d791d.PNG)

#### Live demo with steps to reproduce
http://jsfiddle.net/jLvax2dz/27/
- Slowly resize the chart horizontally until the overlapping is visible.
- Zoom different parts of the chart.

#### Product version
Highcharts 6.0.4

#### Affected browser(s)
Firefox 61, Chrome 67, possibly others.

I tried tweaking the [xAxis.labels.padding](https://api.highcharts.com/highcharts/xAxis.labels.padding) property and setting values larger than the default (from 10 to 100)  and that seems to make the problem appear less frequently. However, it still does, especially when zooming in on a part of the chart. Also, I don't feel confident using this property since I don't know how it works - setting the value small or large (10 - 400) does not cause a noticeable difference.

**Comment by sebastianbochan** [comment]
Hi @plamens,
Thank you for reporting.

Workaround:
- use `rotation`: http://jsfiddle.net/BlackLabel/b8r4o0fd/
- set `useHTML` as true and add CSS styles: http://jsfiddle.net/BlackLabel/pw3jxc9u/

Similar to https://github.com/highcharts/highcharts/issues/8632

**Comment by plamens** [comment]
Rotated labels do not look nice and take up too much vertical space.
Also, the labels overlap on the useHtml example too:
![usehtml_overlapping](https://user-images.githubusercontent.com/1782459/43089101-833c6236-8eac-11e8-970b-8b120d3193dc.PNG)

**Comment by sebastianbochan** [comment]
Hi @plamens,
When you set useHTML, please add CSS styles too (like in my demo).

**Comment by plamens** [comment]
I took the screenshot of http://jsfiddle.net/BlackLabel/pw3jxc9u/ without modifying it.
Expand the chart and then shrink it slowly to observe the labels overlap.
You can also zoom in on parts of the chart to achieve the same.

**Comment by sebastianbochan** [comment]
Hi @plamens,
You are right, indeed its a bug.

**Internal note**
Simplified demo:
- http://jsfiddle.net/BlackLabel/8mrh9j2s/

**Comment by TorsteinHonsi** [comment]
I'm not sure why, but @sebastianbochan 's demo doesn't prove it for me. Here's one that causes overlapping labels on my system (Chrome on Mac): http://jsfiddle.net/pw3jxc9u/8/

It's already overlapping in the initial render, and when clicking the _Smaller_ button, the labels are rendered on one line and overlap even more.

**Comment by sebastianbochan** [comment]
![zrzut ekranu 2018-08-02 o 09 05 43](https://user-images.githubusercontent.com/2115686/43567883-6d3384b8-9633-11e8-95ba-0cae85239859.png)


Chrome: 68.0.3440.75
MacOSX: 10.12.4 (16E195)

**Comment by KacperMadej** [comment]
_Internal note:_ 
Tested on **Windows 10**.
 - On **Edge** both demos are showing the problem - single line of text every time, steps do not matter. 
- On **Chrome** and **Firefox** - only Torstein's demo showing the problem.
