### ISSUE TITLE
Not all of the legend items are exported

### ISSUE THREAD

**Issue by undefined77** [highcharts/highcharts#8627]
#### Expected behaviour
All of the legend items should be exported

#### Actual behaviour
Not all of the legend items are exported

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/legend/navigation-enabled-false/
or here
https://cloud.highcharts.com/edit/171518

#### Product version
Highcharts version 6.1.1

**Comment by sebastianbochan** [comment]
Hi @undefined77,
In your [demo](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/legend/navigation-enabled-false/) there are 30 points. In the exported file (png or pdf) I see also 30 elements, so could you elaborate which items are missing?

![chart](https://user-images.githubusercontent.com/2115686/42805098-2dfeff3c-89ab-11e8-84f0-eb168942a670.png)

**Comment by undefined77** [comment]
![chart 5](https://user-images.githubusercontent.com/15032318/42871488-2d0c351c-8a83-11e8-899e-19e2f1bd22c4.png)

**Comment by undefined77** [comment]
![2018-07-18_12-10-41](https://user-images.githubusercontent.com/15032318/42871732-c0ea179a-8a83-11e8-934a-c1c5843c3b73.gif)

**Comment by KacperMadej** [comment]
Possible to recreate using Windows 10 / Chrome 67.0.3396.99

**Comment by pawelfus** [comment]
**Internal note:**
Don't we simply need to increase `exporting.chartOptions.chart.height`? Demo works fine on osx, so probably windows font-sizes cause this.

**Comment by KacperMadej** [comment]
@undefined77 

Please share where in options are you disabling navigation for export or are you reporting that the demo from API reference is not showing what it supposed to show (in that case please share API reference where the demo is posted). When legend.navigation is disabled for exporting then it's disabled, so I'm not sure what's the problem here. Demo: http://jsfiddle.net/BlackLabel/8tnr4m5v/

**Comment by KacperMadej** [comment]
Fixed demo to work on Windows, fixed link in API reference to look and work better. PR pending.
