### ISSUE TITLE
Missing point in boosted scatter

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#8629]
There seems to be a bug that causes missing points in boosted scatter charts when points have the same y values but aren't added to the chart in a sorted list.

Note in the attached demo that the points render fine if the order of the points are reversed.

#### Expected behaviour
All points are drawn.
![image](https://user-images.githubusercontent.com/14222462/42777058-f805c9dc-8906-11e8-8cc0-d80571725e64.png)

#### Actual behaviour
First point is missing.
![image](https://user-images.githubusercontent.com/14222462/42777050-f1756fbe-8906-11e8-91cd-efde96288ee7.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/omta7sL4/29/

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @Rashaine,
Thank you for the reporting. You try to set the `useGPUTranslations` as true.

Docs:
- https://api.highcharts.com/highcharts/boost.useGPUTranslations

Demo:
- https://jsfiddle.net/BlackLabel/asr7z6n0/

@cvasseng

**Comment by cvasseng** [comment]
Unfortunately unsorted points are not supported in boost. While it may in some cases work when setting `useGPUTranslations` to `true`, this will not be a consistent fix. There's likely to be issues with e.g. culling (and thus performance), min/max clamping, and `connectNulls` if the points are not sorted.

The workaround here would be to either use `Array.sort` on your dataset prior to sending it to Highcharts, or sorting the set before bringing it into JavaScript.

**Comment by cvasseng** [comment]
My apologies - I misread the issue here. This is indeed a bug.

**Comment by cvasseng** [comment]
A fix for this has now been pushed to the `bugfix/boost-unsorted-scatter-points` branch. [Pull request](https://github.com/highcharts/highcharts/pull/8961) has also been created.

Demo of fix: https://jsfiddle.net/omta7sL4/33/

The fix will be available in the next minor version, and in master after the code review has been completed.
