### ISSUE TITLE
Boostjs - Scatter chart only supports circle marker symbol, while line chart supports all symbols

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#8633]
Scatter chart with boost. Here, marker points are plotted with symbol square:
https://jsfiddle.net/tejaspchordiya/mvan0gko/23/

Line chart with boost. Here, marker points are plotted with symbol square:
https://jsfiddle.net/tejaspchordiya/egm28tn5/1/

Now, try zoom in both the charts, one will observe Line chart correctly renders square symbol while scatter chart does not. Same is the case for other symbols as well.

It is observed Scatter chart supports only circle symbol for markers, while Line series supports all marker symbols.

**Comment by sebastianbochan** [comment]
Hi @tejaspchordiya,
Thank you for reporting.

@cvasseng

**Comment by cvasseng** [comment]
This is an [inherent limitation in the boost module at the moment](https://github.com/highcharts/highcharts/blob/master/js/modules/boost.src.js#L23) - scatter and bubble charts are always drawn as circles. So it's not so much a bug as it is an unsupported feature.  

The reason it "works" when zooming in on the line chart is that when you zoom in to a low point density, boost is by default disabled, and the SVG renderer takes over. So when you see square markers in the line chart, it's actually not boosting. 

Internal note: in the future it might be possible to support this by rendering the marker shape to the [circle texture](https://github.com/highcharts/highcharts/blob/master/js/modules/boost.src.js#L2351-L2362) - this would let us keep rendering the points as point sprites and thus it should not have a  performance penalty.

**Comment by manu-st** [comment]
Any timeline on getting this fixed? If this is just a texture issue, wouldn't it be possible to provide a texture? We have SVG markers so it should be possible to create a texture for them. Or provide a way for users to create their own texture code if there is an easy way to convert the SVG (or a subset of SVG) to a texture.

**Comment by cvasseng** [comment]
We're looking on the best approach to this. The complicating factor is that it's very much a case of "all or nothing" - if we're going to open the door on more types of shapes, we should open up for arbitrary ones as well. This requires some thought.

Partly internal note:

If the marker can be done on a canvas, it's fairly easy to patch in.

The texture is created here: https://github.com/highcharts/highcharts/blob/master/js/modules/boost.src.js#L2381-L2384

The basic fix would be to create one `Image` (by doing a canvas buffer copy) per. supported shape, put them in a map along with a `GLint` for the texture on the GPU. Then it's just a matter of indexing the map based on shape type when rendering the series.

However - we need to figure out if and how to support custom shapes.

**Comment by cvasseng** [comment]
Support for all the regular symbols (i.e. `diamond square circle triangle triangle-down`) has now been added to boost through baf771a ([pull request](https://github.com/highcharts/highcharts/pull/8866)):

https://jsfiddle.net/egm28tn5/

Custom symbols can conceivably be added by forking the module and using [this](https://github.com/highcharts/highcharts/blob/feature/boost-marker-pool/js/modules/boost.src.js#L2440-L2443) basic setup. We will do a review internally to see if/how we will define a more structured API for adding them.
