### ISSUE TITLE
Variwide chart - zoom not working properly.

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#8635]
#### Expected behaviour
After zoom a variwide chart points should be rendered properly (next to each other).

#### Actual behaviour
After zoom points are overlapping and they are often on wrong positions.

#### Live demo with steps to reproduce
https://jsfiddle.net/wchmiel/fwL7t3hn/

#### Product version
Highcharts

#### Affected browser(s)
all

**Comment by andrius-k** [comment]
+1

**Comment by mantydze** [comment]
+1

**Comment by raf18seb** [comment]
+1

**Comment by TorsteinHonsi** [comment]
This demo gives an idea of how things behave (use the sliders): https://jsfiddle.net/highcharts/xLwpe3r0/14/

It seems like the width of each item affects its placement when it shouldn't.

**Comment by monojp** [comment]
@TorsteinHonsi as this is still happening on the latest version and the bug is still open and multiple people experiences that - is there a plan to work on this / fix it?

Or has somebody an idea what the problem might be here so that somebody else can fix it?

**Comment by KarlBaumann** [comment]
+1
