### ISSUE TITLE
Narrator's scan mode while using Edge goes to many unseen elements

### ISSUE THREAD

**Issue by Hugodol** [highcharts/highcharts#8637]
#### Expected behaviour
Narrator's scan mode should only go through elements to relay information regarding the chart and its data.

#### Actual behaviour
While using Narrator's scan mode in Edge, the scan goes through many unseen elements that do not convey any information regarding the data of the chart making really confusing for people using screen readers (Narrator can be started with CTRL + WINDOWS + ENTER on any Windows machine, scan mode is activated by CAPS LOCK + SPACE while Narrator is active).

#### Live demo with steps to reproduce
https://jsfiddle.net/pcmqya3h/6/

#### Product version
Highcharts, Highstock 

#### Affected browser(s)
Edge (with Narrator)

**Comment by sebastianbochan** [comment]
Hi @Hugodol,
Thank you for the reporting.

@oysteinmoseng any comments?

**Comment by justinmwarner** [comment]
Hey @sebastianbochan  and @oysteinmoseng , any update on this one?

**Comment by oysteinmoseng** [comment]
@justinmwarner The major problem with the jsFiddle demo provided is that the accessibility module is loaded over HTTP and thus blocked from loading using HTTPS. But once this is fixed, there is still a definite issue that Narrator is picking up lots of SVG elements that it should ignore. It seems the only way to solve this is to flood the DOM with `aria-hidden`, but this is a very bloaty approach.

I will take a look at it.

**Comment by oysteinmoseng** [comment]
I took a closer look, and it seems Narrator now announces all elements of an SVG, as long as they are not explicitly hidden (using an `aria-hidden` attribute). This even includes group elements. Given that our charts also has a `title` element, this is announced for every element.

In summary this means we have to explicitly hide every SVG element we don't want to expose to Narrator. Given the dynamic nature of some of these elements, this will take some time to fix in a clean way, but we will look at this as soon as we have time.

**Comment by justinmwarner** [comment]
@oysteinmoseng, any update here?

**Comment by oysteinmoseng** [comment]
Here is a workaround for the issue: https://jsfiddle.net/m173rz0f/

We basically add `aria-hidden` to all elements that we can, and leave the ones with `aria-label` and their parents only.

**Comment by oysteinmoseng** [comment]
Note: Edited jsFiddle above for better workaround that will preserve `aria-hidden=false` attributes

**Comment by oysteinmoseng** [comment]
This will be handled internally by Highcharts from v7.1, and the above workaround should no longer be required from then on.
