### ISSUE TITLE
Legend with proximate option

### ISSUE THREAD

**Issue by VBIManonmaniM** [highcharts/highcharts#8638]
Expected behaviour
Legend with proximate option have to work with all kind of Series Data.

Actual behaviour
But it is not working properly with Series with all null data

Live demo with steps to reproduce
https://jsfiddle.net/v24xsjh8/4/

Product version
Highcharts

Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Thanks for reporting @VBIManonmaniM !

**Comment by VBIManonmaniM** [comment]
@pawelfus Thank you for your reply, When this fix will release.
