### ISSUE TITLE
Proximate does not work for horizontal charts

### ISSUE THREAD

**Issue by VBIManonmaniM** [highcharts/highcharts#8639]
#### Expected behaviour
Proximate does not work for horizontal charts

#### Actual behaviour
Proximate option should have to work for horizontal charts

#### Live demo with steps to reproduce

https://jsfiddle.net/v24xsjh8/7/
#### Product version

Highcharts

**Comment by pawelfus** [comment]
Hi @VBIManonmaniM 

`proximate` option does not work with inverted charts, [docs](https://api.highcharts.com/highcharts/legend.layout): 

>  The layout of the legend items. Can be one of horizontal or vertical or proximate. When proximate, the legend items will be placed as close as possible to the graphs they're representing, **except in inverted charts or when the legend position doesn't allow it**.
