### ISSUE TITLE
Chart update doesn't work with 3D when chart initialized with empty array of series

### ISSUE THREAD

**Issue by renatoly** [highcharts/highcharts#8641]
This could possibly be related to: https://github.com/highcharts/highcharts/issues/8628.  But errors are different and demo setup as well.

Hero is the Demo: https://jsfiddle.net/renatoly/43wzkva5/1/

After initializing a chart with an empty series array, and then when updating it chart.update(options,true,true) it works perfectly when the chart is non 3D.

But when using options to specify a 3D Chart we get the following error:

highcharts-3d.js:64 Uncaught TypeError: Cannot read property 'left' of undefined
    at G.<anonymous> (highcharts-3d.js:64)
    at G.a.(fiddle.jshell.net/_display/anonymous function) [as getSlotWidth] (https://code.highcharts.com/highcharts.js:20:80)
    at a.Tick.handleOverflow (highcharts.js:112)
    at a.Tick.renderLabel (highcharts.js:117)
    at a.Tick.render (highcharts.js:118)
    at G.renderTick (highcharts.js:163)
    at highcharts.js:164
    at Array.forEach (<anonymous>)
    at a.each (highcharts.js:28)
    at G.render (highcharts.js:164)

**Comment by KacperMadej** [comment]
Hi @renatoly 

Thank you for reporting about the problem.

_Internal note:_ This is a different issue than #8628

**Comment by renatoly** [comment]
Hi, I was wondering if there are any updates on this issue.

Thanks

**Comment by sebastianbochan** [comment]
The bug is still opened, as a result it has not been not fixed yet.

**Comment by TorsteinHonsi** [comment]
Hi @renatoly , sorry for the delay!

Here's your demo with the fix applied: https://jsfiddle.net/highcharts/43wzkva5/41/.

The fix will be part of the next maintenance release, within a few weeks.

**Comment by renatoly** [comment]
Thank you very much, I am looking forward for the next release.

**Comment by apuravchauhan** [comment]
@TorsteinHonsi 
Might be unrelated, but it seems when you update the chart data, animation is not happening.
Example, click 3d button and then 3d2 button, you could see the changes don't animate



https://jsfiddle.net/asL5o8r9/

**Comment by pawelfus** [comment]
It seems that line is animating correctly, while column is not animating at all. Let me open new issue for that: #11100 - it's a regression, animation used to be fine in v7.0.

**Comment by apuravchauhan** [comment]
@pawelfus Thanks for prompt acknowledgement
