### ISSUE TITLE
Histogram: value is not visible in class range or tooltip

### ISSUE THREAD

**Issue by daBacky** [highcharts/highcharts#8646]
#### Expected behaviour
We expect that the value 123 is visible in the class range with a correct tooltip .

#### Actual behaviour
The value 123 is not visible in the class range because the class range is calculated only until 122.802469.

#### Live demo with steps to reproduce
https://codepen.io/Mili2121/pen/EpgWBm

#### Product version
Highcharts JS v6.1.1 (2018-06-27)

#### Affected browser(s)
On all actual browsers

**Comment by sebastianbochan** [comment]
Hi @daBacky,
When I run the demo, I was not able to observe where this value is draw. Could you point me out, how can find it?

![zrzut ekranu 2018-07-19 o 10 36 40](https://user-images.githubusercontent.com/2115686/42931326-b4f52b48-8b3f-11e8-9c88-92565ba9c66b.png)

**Comment by sebastianbochan** [comment]
Hi @daBacky,
Thank you for reporting.

@Denyllon
