### ISSUE TITLE
Exception on setting Legend property "enabled : false"

### ISSUE THREAD

**Issue by SudhanshuDabral** [highcharts/highcharts#8648]
#### Expected behaviour
Should hide the legend box without any error.

#### Actual behaviour
I am using Value in legend plugins.
When i am setting Legend property "enabled :  false" it hides the legend box but on mouse over of chart it throws exceptions in highcharts js.

"Unhandled exception at line 27, column 373 in Highchart.js
JavaScript runtime error: Array.prototype.forEach: 'this' is null or undefined"

**Comment by sebastianbochan** [comment]
Hi @SudhanshuDabral,
The issue is related with the plugin: https://github.com/highcharts/value-in-legend and should be reported in the repo there.
