### ISSUE TITLE
Spline series disappears on mobile devices

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#8649]
#### Expected behaviour
The series shouldn't disappear after dragging the pointer across the plot area.

List of environments where the issue can be reproduced:

- The Samsung Galaxy S7 has the following versions:
  -  Chrome: 67.0.3396.87 (latest)
  -   Android 8.0.0
- The Samsung Galaxy S5:
  -  Chrome: 67.0.3396.87 (latest)
  -  Android 6.0.1
- Xiaomi Mi A1:
  - Android 8.0.0
  - Firefox Focus 6.0 (Build #21861909)
- Xiaomi Redmi 5A
  -  Chrome: 67.0.3396.87 (latest)
  -  Android 7.1.2

#### Actual behaviour
The series disappears after dragging the pointer across the plot area. It has to be the spline series and tooltip has to be enabled.

#### Live demo with steps to reproduce
Open the following link in one of the environments specified in _Expected behaviour_ section:
http://jsfiddle.net/BlackLabel/5hLpe0w2/show
Drag the pointer across the plot area.

#### Product version
6.1.1

**Comment by sebastianbochan** [comment]
The problem is fixed since 7.1.1.
