### ISSUE TITLE
incorrect tickInterval/minRange (high width chart)

### ISSUE THREAD

**Issue by Broutard** [highcharts/highcharts#865]
In a StockChart, when my chart width is over 1000px, tickIntervals are incorrect :

=> tickInterval: 24 \* 3600 \* 1000 (One day)

http://jsfiddle.net/DcuGu/1/

It seems also affect "minRange"

**Comment by oysteinmoseng** [comment]
Seems to behave as expected now: http://jsfiddle.net/DcuGu/3/. If not, feel free to comment and we can reopen.
