### ISSUE TITLE
Pie chart connectors drawn on Pie chart

### ISSUE THREAD

**Issue by iamanoopmk** [highcharts/highcharts#8651]
I am wrapping this code in a react library
#### Expected behaviour
The connectors must not be drawn on pie chart but on the side

#### Actual behaviour
<img width="606" alt="weird_pie" src="https://user-images.githubusercontent.com/1889875/42951546-0c246f06-8b94-11e8-90d8-820bf9536f7f.png">

As you can see, the connector crosses over even though there is space on the right side.

I am essentially wrapping the code into a React component as outlined in this blog https://www.highcharts.com/blog/frameworks/react/192-use-highcharts-to-create-charts-in-react/

Following is my code
`import React, {Component} from 'react'
import Highcharts from 'highcharts'
import HighchartsMore from 'highcharts-more'
HighchartsMore(Highcharts)

export default class AlarmPieChart extends Component{
    componentDidMount(){
        if(this.props.data&&this.props.data.length){
            this.loadPieChart(this.props.data,this.props.height,this.props.from,this.props.size,this.props.durationOrFrqType,this.props.dispatch,this.props.filterOnSliceClick)
        }

    }

    loadPieChart(data,height,from,size,durationOrFrqType,dispatch,filterOnSliceClick){

        var pieColors = (function () {
            var colors = []

            var base = "#ea5e35"

            var    i

            for (i = 255; i > 128; i -= 25) {
                // Start out with a darkened base color (negative brighten), and end
                // up with a much brighter color
                colors.push(base + i.toString(16));
            }
            return colors;
        }());

        Highcharts.chart(from, {
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie',
                height : height
            },
            credits: {
                enabled: false
            },

            title: {
                text: ''
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    size: size,
                    allowPointSelect: true,
                    allowOverlap: true,
                    cursor: 'pointer',
                    colors: pieColors,
                    dataLabels: {
                        enabled: true,
                        padding: 0,

                        formatter : function(){

                            var descriptionArray= this.key ? this.key.replace(/.{15}\S*\s+/g, "$&@").split(/\s+@/) : []
                            var text = ""
                            descriptionArray.map((data)=>{
                                text = text+"<span style={{'fontWeight':'normal'}}>"+data+"<br/></span>"
                            })
                            if((from=="alarms"&&durationOrFrqType!="frequency")||(from=="turbine"&&durationOrFrqType!="frequency")){
                                return   '<span style={{fontWeight":"normal"}}>' + this.key + '<br></span><span style={{"fontWeight":"normal"}}> ' + getFormatedTime(this.y,durationOrFrqType) + '</span>'
                            }else if(from=="windfarm"&&durationOrFrqType=="frequency"){
                                return   '<span style={{fontWeight":"normal"}}>' + text + '<br></span><span style={{"fontWeight":"normal"}}> ' + this.y + '</span>'
                            }else if(from=="maintenanceRepairByCost"){
                                    return   '<span style={{fontWeight":"normal"}}>' + text + '<br></span><span style={{"fontWeight":"normal"}}> </span>'
                            }else if(from=="alarms"&&durationOrFrqType=="frequency"){
                                return   '<span style={{fontWeight":"normal"}}>' + this.key + '<br></span><span style={{"fontWeight":"normal"}}> ' + this.y + '</span>'
                            }else{
                                return   '<span style={{fontWeight":"normal"}}>' + text + '<br></span><span style={{"fontWeight":"normal"}}> ' + getFormatedTime(this.y,durationOrFrqType) + '</span>'
                            }
                        },
                        filter: {
                            property: 'percentage',
                            operator: '>',
                            value: (from=="maintenanceRepairByCost"||from=="maintenanceRepairByTime")?3:4
                        }
                    }
                },
                line:{

                        fontWeight:"normal"

                }
            },
            series: [{
                name: 'Share',
                data: data,
                dataLabels: {

                    style: {
                        fontWeight: 'normal'
                    }
                },
                point: {
                events: {
                    select: function() {

                        //some thing
                    },
                    mouseOver: function (e) {

                    }
                }
            }

            }]
            });
    }

    render(){
        var id = this.props.from
        return (
            <div id={id}>

            </div>

        )
    }

}
`

#### Product version
version 6.0.7 [Updated on July 20, 2018]

#### Affected browser(s)
Chrome, Safari

**Comment by sebastianbochan** [comment]
Hi @iamanoopmk,
Thank you for contacting us.
I replicated your example as live demo [here](https://jsfiddle.net/BlackLabel/ypmtsuj4/), but unfortunately was not able to reproduce the issue. Could you update my code with your hardcoded data and values to introduce the issue?

**Comment by iamanoopmk** [comment]
@sebastianbochan 
Thank you for the response. I made a mistake in the reporting. The version I used was 6.0.7 and not the latest. When I upgraded to the latest, the issue seems to have gone. But just so that you can try it, here is the json formatted data that was causing this issue
`{
  "topTenDuration": {
    "1222": {
      "duration": 560.85,
      "frequency": 1,
      "description": "description 1"
    },
    "1054": {
      "duration": 436.20000000000033,
      "frequency": 8,
      "description": "description 2"
    },
    "1063": {
      "duration": 11.5,
      "frequency": 2,
      "description": "description 3"
    },
    "1141": {
      "duration": 2.25,
      "frequency": 1,
      "description": "description 4"
    },
    "2058": {
      "duration": 2.05,
      "frequency": 1,
      "description": "description 5"
    },
    "14": {
      "duration": 0.4833333333333337,
      "frequency": 2,
      "description": "description 5"
    },
    "1134": {
      "duration": -766.166666666667,
      "frequency": 1,
      "description": "description 7"
    },
    "1276": {
      "duration": -3020.25,
      "frequency": 1,
      "description": "description 8"
    },
    "1139": {
      "duration": -3834.81666666667,
      "frequency": 1,
      "description": "description 9"
    },
    "9": {
      "duration": -4821.23333333333,
      "frequency": 3,
      "description": "description 10"
    }
  },
  "topTenFreq": {
    "1280": {
      "duration": -42786.466666666725,
      "frequency": 1533,
      "description": "description 1"
    },
    "1054": {
      "duration": 436.20000000000033,
      "frequency": 8,
      "description": "description 2"
    },
    "1157": {
      "duration": -5955.6,
      "frequency": 7,
      "description": "description 3"
    },
    "2053": {
      "duration": -10469.31666666667,
      "frequency": 6,
      "description": "description 4"
    },
    "9": {
      "duration": -4821.23333333333,
      "frequency": 3,
      "description": "description 5"
    },
    "1213": {
      "duration": -13578.650000000001,
      "frequency": 3,
      "description": "description 6"
    },
    "1063": {
      "duration": 11.5,
      "frequency": 2,
      "description": "description 7"
    },
    "1076": {
      "duration": -13879.55,
      "frequency": 2,
      "description": "description 8"
    },
    "14": {
      "duration": 0.4833333333333337,
      "frequency": 2,
      "description": "description 9"
    },
    "1222": {
      "duration": 560.85,
      "frequency": 1,
      "description": "description 10"
    }
  }
}`

I will keep an eye out for any other data set that might cause this issue. Even in the older version, the issue did not appear all the time. It was only in a few cases.

**Comment by sebastianbochan** [comment]
Thank you for the feedback.
