### ISSUE TITLE
Feature Request: Sankey Node Vertical Alignment

### ISSUE THREAD

**Issue by imjeffp** [highcharts/highcharts#8653]
#### Desired behaviour
I'd like an alignment where child nodes are centered on their parent nodes. Hard to explain, but here's a picture:

![asset 2](https://user-images.githubusercontent.com/25798597/42963524-1a9845ce-8b5a-11e8-9f15-4185fb861d81.png)

#### Actual behaviour

The current alignment is for all nodes to be centered in the chart, like this:

![asset 3](https://user-images.githubusercontent.com/25798597/42963654-77c1a84e-8b5a-11e8-87dc-18f90eabc1f5.png)

You could also do a bottom or top alignment like this:

![asset 4](https://user-images.githubusercontent.com/25798597/42963927-3344775e-8b5b-11e8-9559-f9b202bae904.png)

Apologies if this exists and I'm merely not seeing it.

Thanks!

**Comment by sebastianbochan** [comment]
Hi @imjeffp,
I think that its more related with your data and weight of points. Let's consider the demo: https://jsfiddle.net/BlackLabel/qdro1unb/, it looks like close to your concept from the first image.

You can also try to control your chart by [curveFactor](https://api.highcharts.com/highcharts/series.sankey.curveFactor).

@TorsteinHonsi what do you think?

**Comment by pawelfus** [comment]
Hi @imjeffp 

Thank you for suggestion. I think you are right, we should add an option to change alignment, possible solutions:

- current (center in the column): https://jsfiddle.net/BlackLabel/pb5jhntw/3/
- top alignment: https://jsfiddle.net/BlackLabel/pb5jhntw/
- bottom alignment: https://jsfiddle.net/BlackLabel/pb5jhntw/9/

I don't see a simple plugin to change from "center in the column" to "center on the parent". That requires extra scaling of nodes. Demo: https://jsfiddle.net/BlackLabel/pb5jhntw/26/ - grey border shows plotting area. Without scaling "B", we will cause overlapping in "B", or "A" will be rendered outside the plotting area (overlapping longer titles, or even rendered outside the container).
