### ISSUE TITLE
Windrose Chart plotting empty values and overlapping the columns

### ISSUE THREAD

**Issue by iamanoopmk** [highcharts/highcharts#8657]
#### Expected behaviour
If the value is 0 then that column must not be plotted. Also, the columns must not overlap but must be stacked.

#### Actual behaviour
I am wrapping the code into a React component as outlined in this blog https://www.highcharts.com/blog/frameworks/react/192-use-highcharts-to-create-charts-in-react/

I have used the highcharts-more to draw the Polar Chart. Following are the results.

![polar](https://user-images.githubusercontent.com/1889875/42997966-325825f8-8c36-11e8-8162-97a2d61d308d.png)
![screenshot from 2018-07-20 15-48-26](https://user-images.githubusercontent.com/1889875/42997968-329fb508-8c36-11e8-828b-7648ded2f523.png)
![screenshot from 2018-07-20 15-48-02](https://user-images.githubusercontent.com/1889875/42997970-32cf56c8-8c36-11e8-82d3-fb14a2235a52.png)

As you can see in the images and the tooltips, even the data mapping is wrong. However when I try the same code on a JSfiddle it works perfectly. Here is the fiddle

https://jsfiddle.net/zv91nhwf/6/

Following is my code for React component

`import React, {Component} from 'react'
import Highcharts from 'highcharts'
import HighchartsMore from 'highcharts/js/highcharts-more'

HighchartsMore(Highcharts)

export default class Windrose extends Component{
    componentDidMount() {
        
        this.loadWindroseChart(this.props)
    }

    loadWindroseChart(data){
        const {windRoseData} = data
        let seriesData = [
          {
            "name": "0-5 m/s",
            "data": [
              [
                "N",
                4.261645193260654
              ],
              [
                "NNE",
                11.99207135777998
              ],
              [
                "NE",
                11.496531219028741
              ],
              [
                "ENE",
                6.144697720515362
              ],
              [
                "E",
                3.865213082259663
              ],
              [
                "ESE",
                3.7661050545094152
              ],
              [
                "SE",
                0.6937561942517344
              ],
              [
                "SSE",
                3.072348860257681
              ],
              [
                "S",
                5.450941526263628
              ],
              [
                "SSW",
                2.973240832507433
              ],
              [
                "SW",
                2.3785926660059467
              ],
              [
                "WSW",
                0.39643211100099107
              ],
              [
                "W",
                1.3875123885034688
              ],
              [
                "WNW",
                0.09910802775024777
              ],
              [
                "NW",
                0.09910802775024777
              ],
              [
                "NNW",
                0.09910802775024777
              ]
            ],
            "color": "rgb(93, 180, 135)",
            "type": "column"
          },
          {
            "name": "5-10 m/s",
            "data": [
              [
                "N",
                0.09910802775024777
              ],
              [
                "NNE",
                3.1714568880079286
              ],
              [
                "NE",
                9.217046580773042
              ],
              [
                "ENE",
                3.072348860257681
              ],
              [
                "E",
                0.09910802775024777
              ],
              [
                "ESE",
                0.39643211100099107
              ],
              [
                "SE",
                5.550049554013875
              ],
              [
                "SSE",
                9.712586719524282
              ],
              [
                "S",
                3.1714568880079286
              ],
              [
                "SSW",
                2.180376610505451
              ],
              [
                "SW",
                0.09910802775024777
              ],
              [
                "WSW",
                0
              ],
              [
                "W",
                0
              ],
              [
                "WNW",
                0
              ],
              [
                "NW",
                0
              ],
              [
                "NNW",
                0.19821605550049554
              ]
            ],
            "color": "rgb(234, 94, 53)",
            "type": "column"
          },
          {
            "name": "10-15 m/s",
            "data": [
              [
                "N",
                0
              ],
              [
                "NNE",
                0.29732408325074333
              ],
              [
                "NE",
                1.1892963330029733
              ],
              [
                "ENE",
                0
              ],
              [
                "E",
                0
              ],
              [
                "ESE",
                0
              ],
              [
                "SE",
                1.1892963330029733
              ],
              [
                "SSE",
                1.8830525272547076
              ],
              [
                "S",
                0.29732408325074333
              ],
              [
                "SSW",
                0
              ],
              [
                "SW",
                0
              ],
              [
                "WSW",
                0
              ],
              [
                "W",
                0
              ],
              [
                "WNW",
                0
              ],
              [
                "NW",
                0
              ],
              [
                "NNW",
                0
              ]
            ],
            "color": "rgb(78, 132, 175)",
            "type": "column"
          },
          {
            "name": "15-20 m/s",
            "data": [
              [
                "N",
                0
              ],
              [
                "NNE",
                0
              ],
              [
                "NE",
                0
              ],
              [
                "ENE",
                0
              ],
              [
                "E",
                0
              ],
              [
                "ESE",
                0
              ],
              [
                "SE",
                0
              ],
              [
                "SSE",
                0
              ],
              [
                "S",
                0
              ],
              [
                "SSW",
                0
              ],
              [
                "SW",
                0
              ],
              [
                "WSW",
                0
              ],
              [
                "W",
                0
              ],
              [
                "WNW",
                0
              ],
              [
                "NW",
                0
              ],
              [
                "NNW",
                0
              ]
            ],
            "color": "rgb(128, 133, 233)",
            "type": "column"
          },
          {
            "name": "20-25 m/s",
            "data": [
              [
                "N",
                0
              ],
              [
                "NNE",
                0
              ],
              [
                "NE",
                0
              ],
              [
                "ENE",
                0
              ],
              [
                "E",
                0
              ],
              [
                "ESE",
                0
              ],
              [
                "SE",
                0
              ],
              [
                "SSE",
                0
              ],
              [
                "S",
                0
              ],
              [
                "SSW",
                0
              ],
              [
                "SW",
                0
              ],
              [
                "WSW",
                0
              ],
              [
                "W",
                0
              ],
              [
                "WNW",
                0
              ],
              [
                "NW",
                0
              ],
              [
                "NNW",
                0
              ]
            ],
            "color": "rgb(141, 70, 84)",
            "type": "column"
          },
          {
            "name": ">25 m/s",
            "data": [
              [
                "N",
                0
              ],
              [
                "NNE",
                0
              ],
              [
                "NE",
                0
              ],
              [
                "ENE",
                0
              ],
              [
                "E",
                0
              ],
              [
                "ESE",
                0
              ],
              [
                "SE",
                0
              ],
              [
                "SSE",
                0
              ],
              [
                "S",
                0
              ],
              [
                "SSW",
                0
              ],
              [
                "SW",
                0
              ],
              [
                "WSW",
                0
              ],
              [
                "W",
                0
              ],
              [
                "WNW",
                0
              ],
              [
                "NW",
                0
              ],
              [
                "NNW",
                0
              ]
            ],
            "color": "rgb(78, 75, 100)",
            "type": "column"
          }
        ]

        var categories = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'];
        
        Highcharts.chart('windrose',  {
            series: seriesData,

            chart: {
                polar: true,
                type: 'column'
            },

            credits: {
                enabled: false
            },

            title: {
                text: ''
            },

            pane: {
                size: '85%'
            },

            legend: {
                align: 'right',
                verticalAlign: 'top',
                y: 100,
                layout: 'vertical'
            },

            xAxis: {
                tickmarkPlacement: 'on',
                categories: categories
            },

            yAxis: {
                min: 0,
                endOnTick: false,
                showLastLabel: true,
                title: {
                    text: 'Frequency (%)'
                },
                labels: {
                    formatter: function () {
                        return this.value + '%';
                    }
                },
                reversedStacks: false
            },

            tooltip: {
                formatter: function() {
                    return this.x + '<br/>' +' in series '+ this.series.name + " "+this.y.toFixed(2)+"%";
                }
            },

            plotOptions: {
                series: {
                    stacking: 'normal',
                    shadow: false,
                    groupPadding: 0,
                    pointPlacement: 'on'
                }
            }
        });
    }
    
    render(){
    
        return(
            <div style={{"paddingTop" : "10px"}} id="windrose">
                
            </div>
        )
    }
}

`

#### Product version
Verified to be running the latest version of Highcharts 6.1.1

#### Affected browser(s)
Chrome, Firefox, Safari

**Comment by sebastianbochan** [comment]
Hi @iamanoopmk,
Did you try to use our official wrapper for React? 
- https://www.highcharts.com/blog/tutorials/highcharts-react-wrapper/

**Comment by KacperMadej** [comment]
@iamanoopmk 

Please add a live demo of the problem or provide another way for us to recreate the problem, debug it and test possible solutions.

**Comment by iamanoopmk** [comment]
Sorry for the late reply. I was not able to replicate the issue on a jsfiddle so was not able to provide a live demo. I finally resolved this issue by reinstalling the package after cleaning the node_models folder of my project. I will close the issue as resolved.

**Comment by sebastianbochan** [comment]
Thank you for the feedback.
