### ISSUE TITLE
Treemap children nodes: no reaction while hovering its area

### ISSUE THREAD

**Issue by dmitrygorbenko** [highcharts/highcharts#8659]
Steps:
1. Open page https://www.highcharts.com/demo/treemap-large-dataset
2. Click on Africa
3. Hover any country

#### Expected behaviour
As you hover any country the tooltip appears and helps you to see country's details (like on one level above). Also you may click on country's area and drill down into it.

#### Actual behaviour
You need to hover exactly country's title to see its tooltip. You need to click on country's titleto drill down into it.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/treemap-large-dataset

#### Product version
Highcharts v6

#### Affected browser(s)
Chrome and Firefox

**Comment by sebastianbochan** [comment]
Hi @dmitrygorbenko,
Thank you for the reporting.

**Internal note**
Regression since v6.0.7

Bisect leads me to https://github.com/highcharts/highcharts/commit/3aa2eca

**Comment by dmitrygorbenko** [comment]
Hi Sebastian,

Yep, by changing

> graphic[verb](series.pointAttribs(

to

> graphic["term"](series.pointAttribs(

I'm getting issue kind of fixed.

I hope fix on your side would be quick and easy.

Thanks,
Dima

**Comment by TorsteinHonsi** [comment]
It's now fixed in the master. The workaround is simple, just add this line after highcharts.js is included: 

`delete Highcharts.Color.prototype.names.none;`

Demo: https://jsfiddle.net/uq8Lgoxw/2/
