### ISSUE TITLE
csv data - series names are random when seriesMapping object property has value more than 10.

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#8662]
#### Expected behaviour
appropriate series names when data loaded from csv file and seriesMapping property value is more than 10.

#### Actual behaviour
series names are get from csv file randomly (first row of csv file).

#### Live demo with steps to reproduce
https://jsfiddle.net/wchmiel/64bcp0Lq/

1. set var in seriesMapping more than 10 and run example
2. check particular series name - it should't be correct
3. set var in seriesMapping less than 10 and run example
4. check particular series name - it should be correct

#### Product version
Highcharts

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
**Internal note:**
Issue comes from these lines: https://github.com/highcharts/highcharts/blob/e9082f1ed28e2df2e3b04f1998a5a3227247b4ac/js/modules/data.src.js#L2070-L2079

Where `[5, 10].sort()` results as `[10, 5]` (string sorting conversion).
