### ISSUE TITLE
Highcharts editor not applying settings correctly on subsequent applications

### ISSUE THREAD

**Issue by andrei-gheorghiu** [highcharts/highcharts#8664]
#### Preamble
We implemented Highcharts Editor to allow chart customization. We allow re-loading the initial chart options using `loadProject()` method.
When a chart that sets `inverted:true` or `polar:true` is selected, if it gets loaded again and a different chart type, which doesn't feature the above settings is selected, they are not unset. They persist, making all charts `inverted`, respectively `polar`.

#### Expected behaviour
`inverted` and `polar` settings to be unset when a chart which requires them to be either `false` or `unset` is applied. This behavior might also apply to other options that are `unset` by default.

#### Actual behaviour
`inverted` and `polar` settings persist when charts without these settings are selected.

#### Live demo with steps to reproduce

None yet. Let me know if it's compulsory.

#### Product version

Highcharts Editor v0.2.1
Highcharts JS v6.1.1

#### Affected browser(s)
All.

**Comment by pawelfus** [comment]
Hi @andrei-gheorghiu 

Thank you for reporting the issue. I think this should be reported on the editor repo: https://github.com/highcharts/highcharts-editor 

Regarding the issue, it's always good to attach a demo, it simply help us to fix the issue sooner than later. For now, I'm not sure if this is a bug.

**Comment by andrei-gheorghiu** [comment]
Thank you, @pawelfus.

I will create a fiddle and post it on highed git.
