### ISSUE TITLE
Modulize Highchart? Tree shaking capability.

### ISSUE THREAD

**Issue by envil** [highcharts/highcharts#8667]
I'm using Highcharts and Highstocks with Angular in my application. The functionality is good, however it's impossible to optimize the bundle size of Highcharts:
Take look at this screenshot of my application bundle information:
<img width="961" alt="screen shot 2018-07-24 at 12 07 05 pm" src="https://user-images.githubusercontent.com/775364/43116583-12e92d9a-8f3b-11e8-8dc4-99d943a39a4c.png">
You can see that Highcharts ate up to nearly 500kb (dark blue outline), even bigger than a chunky framework like Angular (red outline). Even if one uses only one chart in Highcharts, they have to carry on all of the Highcharts code, which is unacceptably unoptimized.

The solution I know here is to modulize Highcharts so that one can only import what they need. Also with new Webpack Tree Shaking, the bundle size will be reduced vastly.
I know this cannot be fixed soon but are you guys thinking about it?

**Comment by sebastianbochan** [comment]
Hi @envil,
At the begining I advise you to load only `highstock.js` which included all Highcharts' features. You can also build your custom file by our tool here:
-  https://www.highcharts.com/download

**Comment by envil** [comment]
Thank you for your responses.
I'm looking at the custom build feature. It gives me a `highchart-custom.src.js`which is not convenient to use at all since it's not a node_modules, so I cannot import it to my Angular application in a regular way. And all the type definitions for the typescript are gone.

**Comment by envil** [comment]
Also what I mean is ES module, completely independent and can be imported to other ES modules. See how `lodash` and `date-fns` have defeated `underscore` and `momentjs`, one of the most important factor is the modularization capability like this.

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard FYI

**Comment by GeorgeKnap** [comment]
I am running into this as well.
I tried to go around with  `import * as Highstock from 'highcharts/highstock';` but it has no effect whatsoever.

**Comment by jon-a-nygaard** [comment]
Hi, a while back we started publishing our parts files as ES modules which means you can do `import Highcharts from 'highcharts/es-modules/masters/highcharts.src.js'`. This may help some on the issue.

We are also currently working on making these parts files more standalone, which should improve tree shaking capabilities. It is a bit difficult at the moment to give a good ETA for when this will be published, but I will keep you updated as soon as I know some more.

**Comment by ymanvieu** [comment]
hi,

i'm using only 'stockChart' type and ran into the same problem, but found a solution described here : 
https://github.com/highcharts/highcharts-angular#core
 
```
import * as Highcharts from 'highcharts';
import Stock from 'highcharts/modules/stock';
Stock(Highcharts);
```
instead of : 
`import * as Highstock from 'highcharts/highstock';` 

now in bundle, its look like this : 
![screen](https://user-images.githubusercontent.com/17235237/56886621-a7c30200-6a6f-11e9-8b7a-d9a5114e161e.jpg)

**Comment by fantapop** [comment]
I'm using highcharts-react which uses the import * syntax.  I'm not giving up yet but i've been unable to get tree shaking working for it so far.

https://github.com/highcharts/highcharts-react/blob/08cd61ca178276d716ae65fba76e1d07924b2838/src/HighchartsReact.d.ts#L6

**Comment by kMeillet** [comment]
My current workaround : Aalias Highcharts module into Highstock module.

This can be done with Webpack (check "resolve.alias" in Webpack documentation for more information) :

```js
    alias: {
      highcharts$: 'highcharts/highstock.js',
    }
```

You can do aliasing with Babel to (babel-plugin-module-resolver).

**Comment by pawelfus** [comment]
Note that Highstock can be loaded as a module to Highcharts, using `modules/stock.js` module. Like mentioned above:

```
import * as Highcharts from 'highcharts';
import Stock from 'highcharts/modules/stock';
Stock(Highcharts);
```

**Comment by mediafreakch** [comment]
@pawelfus Somehow that fails in my tests with: `TypeError: Highcharts.stockChart is not a function`

No type issues though and the application itself works too. I'm using jest. Any idea?

**Comment by Yohandah** [comment]
Any update on this ? Considering dropping Highcharts since it's really a HUGE library to import into my project :(

**Comment by bre1470** [comment]
Hi @Yohandah! We are about half way through, as you can see in https://github.com/highcharts/highcharts/issues/12738.

You can use most ES modules to tree shake. Though this is for the moment not officially supported (only masters), because we are moving and splitting files right now. So with the next release, paths in the example will be different.

```js
import Chart from 'https://code.highcharts.com/es-modules/parts/Chart.js'
import SVGRenderer from 'https://code.highcharts.com/es-modules/parts/SVGRenderer.js'
new Chart('container', { /* ...options... */ });
```
https://jsfiddle.net/xtof0m14/

**Comment by petterw03** [comment]
Do you have any new ETA for this?

**Comment by KacperMadej** [comment]
Hi @petterw03 

There is no ETA for a fix for this issue, but you could check the progress in https://github.com/highcharts/highcharts/issues/12738

Any comments @bre1470 ?

**Comment by bre1470** [comment]
Yes, here are some comments on this:
- We have made significant process, but the file splits might be not final yet, but it is safe to say that the ETA is this year.
- To be safe than sorry, stick to the modules in `es-modules/masters` for now as in the past.
- We evaluate the possibility of a list of files, that already fulfill the requirements for ES6 and tree shaking. In about a week I might have more information regarding the list (not the list itself yet).

**Comment by petterw03** [comment]
How is the list coming along @bre1470? :) Waiting very eagerly!

**Comment by bre1470** [comment]
Hi, @petterw03!

We have created an internal list, which show important core components not ready for tree shaking. This makes unfortunately all useful module pathes incompatible. We will publish the list as soon as we have dependency trees (= series types) working with tree shaking.

If someone has some specific series in mind, please let us know.

**Comment by bre1470** [comment]
Status update for tree shaking with master branch:

- [x] Core/Animation
- [ ] Core/Axis
- [ ] Core/Chart
- [x] Core/FormatUtilities
- [x] Core/Globals
- [ ] Core/Legend
- [x] Core/DefaultOptions
- [ ] Core/Pointer
- [x] Core/Renderer
- [ ] Core/Responsive
- [ ] Core/Series
- [x] Core/Time
- [ ] Core/Tooltip
- [x] Core/Utilities
- [ ] Extensions/Exporting:
- [ ] Extensions/OfflineExporting:
- [x] Series/Bar
- [x] Series/Column
- [ ] Series/Line
- [ ] Series/Pie

*Note: ETA for initial set above is July. Additional files/folders have to be made compatible as well.*

**Comment by bre1470** [comment]
As mentioned by @hakimio, an alternative to do full ES6 tree shaking on `highcharts/es-modules` is the creation of a custom master package. That can help in the meantime and is explained in our docs: https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files
