### ISSUE TITLE
StockChart is not showing a time gap with missing data

### ISSUE THREAD

**Issue by sanderzz91** [highcharts/highcharts#8670]
#### Expected behaviour
Whenever data was first available, then temporarily it wasn't available anymore, and later it was again available, I would expect that a chart displays the data for the first period, then a period with no data, then a period with again data.

#### Actual behaviour
A stock chart actually doesn't show periods with missing data. The first and third period of the above example are just "stitched together", the second period (missing data) isn't shown. This also messes up a proper division of time displayed on the x axis on the chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/hvrednas/dyncg4b3/40/

#### Product version
Highstock JS v6.1.1 (2018-06-27)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @sanderzz91 

This is expected behaviour when [`xAxis.ordinal`](https://api.highcharts.com/highstock/xAxis.ordinal) options is enabled (which is by default in Highstock).

**Comment by sanderzz91** [comment]
Ah, great! I didn't know that.
