### ISSUE TITLE
dataLabels.distance has no effect in sunburst

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#8672]
#### Expected behaviour
`dataLabels.distance` should work in sunburst.

#### Actual behaviour
It's documented (https://api.highcharts.com/highcharts/series.sunburst.dataLabels.distance) and it doesn't work.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/gxwzLk3u/

#### Product version
6.1.0

**Comment by KacperMadej** [comment]
Is this a documentation/API or code/bug issue? @jon-a-nygaard

**Comment by TorsteinHonsi** [comment]
It is not currently implemented, so I've removed it from the docs for now. Though I appreciate that it could be a useful feature.
