### ISSUE TITLE
chart.update seems to change series data when no series data is passed to it

### ISSUE THREAD

**Issue by rlm1023** [highcharts/highcharts#8676]
#### Expected behaviour
`chart.update` shouldn't change series data at all if I haven't passed a `series` object in.

#### Actual behaviour
`chart.update` mutates series objects when x coordinates are vague.

#### Live demo with steps to reproduce

https://jsfiddle.net/nfgrectj/11/

#### Product version

Highcharts 6.1.1

#### Affected browser(s)
Chrome at least, didn't check others.

**Comment by sebastianbochan** [comment]
Hi @rlm1023,
The problem appears, because you mixed two types of xAxis values. In the case of setting `type: category`, in both series you need to declare points in format: `{name: 'string', y: 123}`.

Demo:
- https://jsfiddle.net/BlackLabel/kgvzsn2q/

**Comment by rlm1023** [comment]
Agreed, and that's how I fixed it in the project I'm using it. Was just really strange behavior from update, so figured it was worth filing.
