### ISSUE TITLE
xAxis.showLastLabel not working

### ISSUE THREAD

**Issue by lisaied** [highcharts/highcharts#8677]
last xAxis label not showing up where xAxis.showLastLabel is true
see this sample http://jsfiddle.net/pLfko4zn/3/
notice 28 is not latest xAxis label.

**Comment by sebastianbochan** [comment]
Hi @lisaied,
The last tick is not calculated, so the last label is also missing. The solution is setting `endOnTick` as true.

Demo:
- http://jsfiddle.net/BlackLabel/zw9va6yp/

**Comment by lisaied** [comment]
Thanks Sebastian, but last two xAxis labels are 27.5 & 30. I can't see 28
see this snipe
![image](https://user-images.githubusercontent.com/7660078/43186325-00369a04-8ff7-11e8-88f1-633bee542b42.png)

**Comment by sebastianbochan** [comment]
Hi @lisaied,
By default ticks are calculated according to range, point's x and "size of container". If you would like to have a ticks in exactly points' x values, you need to use [tickPositioner](https://api.highcharts.com/highcharts/xAxis.tickPositioner) and return array of x point's values.

**Comment by lisaied** [comment]
any idea if highchart expose a function to calculate points'x before init the chart?
