### ISSUE TITLE
Annotations don't work with responsive rules

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#8680]
#### Expected behaviour
User should be able to manipulate annotations with responsive rules (same way as it's implemented for series).

#### Actual behaviour
There's no way to affect annotations by using responsive rules.

#### Live demo with steps to reproduce
Click "Small" button.
https://jsfiddle.net/BlackLabel/7n3ucksw/
Annotation should disappear but it doesn't.

#### Product version
6.1.0

**Comment by lameyer** [comment]
+1

**Comment by TorsteinHonsi** [comment]
@pawelfus Will you assign one of your team members for this?

**Comment by pawelfus** [comment]
Most probably I will take care of it.

**Comment by raf18seb** [comment]
Issue still occurs in 7.1.1: https://jsfiddle.net/BlackLabel/z7tnp9ar
