### ISSUE TITLE
Break legend items into two lines

### ISSUE THREAD

**Issue by arj-ary** [highcharts/highcharts#8681]
#### Expected behaviour
I have a chart with 10 series, so i want to break the series legends into 4 in first row and 6 in another. Is there a way to do this? Playing with legend.itemWidth and legend.width does no good. Please let me know if this is a known challenge? Or is there a workaround for this. I have pasted a screenshot below on what i am trying to achieve.

#### Live demo with steps to reproduce
![image](https://user-images.githubusercontent.com/10525258/43231735-34805cdc-9033-11e8-8a63-400d53174a59.png)

#### Affected browser(s)
Chrome version 67.0.0.0

**Comment by sebastianbochan** [comment]
Hi @arj-ary,
The github is our bugtracker, so for general [support](https://www.highcharts.com/support) questions please use forum / stackoverflow of forum.

**Comment by neevarp-cs** [comment]
> #### Expected behaviour
> I have a chart with 10 series, so i want to break the series legends into 4 in first row and 6 in another. Is there a way to do this? Playing with legend.itemWidth and legend.width does no good. Please let me know if this is a known challenge? Or is there a workaround for this. I have pasted a screenshot below on what i am trying to achieve.
> 
> #### Actual behaviour
> #### Live demo with steps to reproduce
> ![image](https://user-images.githubusercontent.com/10525258/43231735-34805cdc-9033-11e8-8a63-400d53174a59.png)
> 
> #### Product version
> #### Affected browser(s)
> Chrome version 67.0.0.0

I'm also facing same problem in that, have you resolved that?

**Comment by hubertkozik** [comment]
Hi @neevarp-cs! This functionality is not available in Highcharts by default. You can read about it e.g. here: https://www.highcharts.com/forum/viewtopic.php?t=34938 and here's a demo with a plugin: https://jsfiddle.net/BlackLabel/db20mqho/

You can also create your own, custom legend like in this demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/legend/scrollable-vertical/

In case of any further support questions feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
