### ISSUE TITLE
Using chart.update to update series data/nodes for SANKEY results in appended instead of replaced node/dataLabel elements

### ISSUE THREAD

**Issue by enderton** [highcharts/highcharts#8682]
#### Expected behaviour
If using chart.update to update the series data and nodes for a sankey, both the links and node displays (including labels) are properly updated (removed/replaced as appropriate)

#### Actual behaviour
The links are properly updated with new options, with one accurate set of link paths; however for the nodes, including the labels for them, instead of a single updated set, the old sets remains and a new set of nodes/label elements are appended.  After multiple updates there are many duplicated elements.
(In fiddle below, if inspect elements can see each time hit 'update' button, additional <rect> elements are added in relevant groups each time)

1st fiddle most closely represents use case trying to update for (changing color of a node programatically), 2nd fiddle is one where issues is more obvious visually, as opposed to needing to inspect elements - and that even if not included nodes specifically in update body, they are not accurately updated.

#### Live demo with steps to reproduce

https://jsfiddle.net/nfgrectj/43/
https://jsfiddle.net/nfgrectj/46/

#### Product version

Highcharts 6.1.1

#### Affected browser(s)
Presumably all, but confirmed issue in
Chrome 67.0.3396.99
Firefox 61.0.1 (64-bit)
Safari 11.1.2 (12605.3.8.1)

**Comment by sebastianbochan** [comment]
Hi @enderton,
Thank you for the reporitng.

**Internal note**
`chart.series[0].update()` does not work too.
Demo:
- https://jsfiddle.net/BlackLabel/b2k4Lq0r/
