### ISSUE TITLE
Tooltip 'split' and 'outside'

### ISSUE THREAD

**Issue by nhitchins** [highcharts/highcharts#8683]
#### Expected behaviour
After unsuccessfully trying to get 'split' tooltips to display 'outside', I noticed your dev comments in the source re: 'not supported in first iteration'.

It would be really great to see this functionality added! Any ETA?

#### Product version
Highstock 6.1.1

**Comment by sebastianbochan** [comment]
Hi @nhitchins,
Thank you for the reporting. 
Im closing this ticket, because its related with https://github.com/highcharts/highcharts/issues/8669
