### ISSUE TITLE
Negative SoftMin for yAxis ignored when using line graph with only positive values

### ISSUE THREAD

**Issue by tj-td-scharbau-benjamin** [highcharts/highcharts#8684]
#### Expected behaviour
When I set a SoftMin of < 0 on yAxis, I want my graphs origin to be set at the SoftMin or lower, even if the series contains only positive values

#### Actual behaviour
When I set a SoftMin of < 0 on yAxis, and the series contains only values >=0, my origin is set to zero.
This behaviour occurs when using a line graph, using a bar graph results in the expected behaviour

#### Live demo with steps to reproduce
I tries to access the fiddle, but I got 404.
To reproduce, simply create a line graph with negative SoftMin on yAxis and only positive values in series.
Switch to bar graph, or insert negative values in series to get the expected behaviour

HTML:
```
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>

<div id="container" style="max-width: 800px"></div>

<button id="point-update">Update max data point</button>
```

js:
```

var chart = Highcharts.chart('container', {

    title: {
        text: 'Y axis softMax is 100'
    },

    subtitle: {
        text: 'Click the button to change data max'
    },

    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },

    yAxis: {
        softMax: 100,
				softMin: -100,
        title: {
            text: 'Percentage'
        }
    },

    series: [{
        data: [0, 1, 0, 2, 3, 5, 8, 5, 15, 14, 25, 54]
    }]
});


var toggle = false;
$('#point-update').click(function () {
    chart.series[0].points[11].update((toggle = (!toggle)) ? 120 : 54);
});
```

#### Product version
Highcharts 5.0.7

#### Affected browser(s)
Reproduced with Vivaldi and Chrome

**Comment by tj-td-scharbau-benjamin** [comment]
Thanks for your response @pawelfus ,

I didnt realize that option, so in my case it really helps.
However, I still find it strange that you have different default behaviour on a line and column graph (if you change the graph type to column and delete the `series.softThreshold` option, the axis will be padded to negative. 

Is this expected behaviour?

**Comment by pawelfus** [comment]
This is expected behaviour @tj-td-scharbau-benjamin - see docs:

- [series.line.softThreshold](https://api.highcharts.com/highcharts/series.line.softThreshold) - defaults to true
- [series.column.softThreshold](https://api.highcharts.com/highcharts/series.column.softThreshold) - defaults to false

**Comment by tj-td-scharbau-benjamin** [comment]
@pawelfus 
Thanks, I was able to fix my issue thanks to you information.
