### ISSUE TITLE
Column series shift when adding new data dynamically

### ISSUE THREAD

**Issue by SkyFlame00** [highcharts/highcharts#8696]
#### Expected behaviour
When adding new data created columns should be placed on xAxis (of datetime type) on x coordinate which is specified in the input.

#### Actual behaviour
New data is placed but the entire series is shifted to the left for an unknown reason. If there's a need in resizing y axis, it will not be shitfted. Otherwise it **sometimes** will be shifted.

I mean, for example, if you add x = 1 and y = 5, there will be a shift. Try adding x = 1, y = 12 and there will be no shift (as chart is resized). The third case, if you add x = 7, y = 5, there'll be no shift too.

#### Live demo with steps to reproduce
https://jsfiddle.net/SkyFlame/se6gzfLa/11/

#### Product version
Latest Highcharts

#### Affected browser(s)
Opera 54.0.2952.60

**Comment by pawelfus** [comment]
Hi @SkyFlame00 

Could you attach screenshots for better explanation? I'm not sure what do you mean by shift? This is  how it looks before adding a point:

![screen shot 2018-07-27 at 11 06 33](https://user-images.githubusercontent.com/1453926/43312379-616fc542-918d-11e8-80df-384737fc2d15.png)

And after (x=1, y=5):
![screen shot 2018-07-27 at 11 06 41](https://user-images.githubusercontent.com/1453926/43312381-624a95be-918d-11e8-8ecf-f2950e1804bd.png)


Similar, after (x=1, y=12):
![screen shot 2018-07-27 at 11 07 00](https://user-images.githubusercontent.com/1453926/43312385-65408e5e-918d-11e8-8b73-9779b926565e.png)

And this works as expected.

**Comment by SkyFlame00** [comment]
![image](https://user-images.githubusercontent.com/7037108/43365075-9381f2c8-932f-11e8-8d12-474c5be1e2ec.png)

But I have this (a small shift to the left):
![image](https://user-images.githubusercontent.com/7037108/43365084-a7715238-932f-11e8-9809-47c705172c1e.png)

**Comment by pawelfus** [comment]
Thank you for the screenshot, now I see the difference. Fixed width for the chart is required to spot the bug: https://jsfiddle.net/BlackLabel/L0crtb75/

**Workaround:**
Disable `series.maxPointWidth` - this options breaks columns positions.

**Comment by SkyFlame00** [comment]
Thank you! :)
