### ISSUE TITLE
Xrange chart dataLabels formatter not working

### ISSUE THREAD

**Issue by khoaanh2212** [highcharts/highcharts#8698]
```javascript
plotOptions: {
    xrange: {
      dataLabels: {
        formatter: function () {
         console.log(this);
          return `${this.point.x2} %`;
        },
      },
    },
  },
```
the function formatter never is called.with another property of dataLabels works,except formatter

**Comment by sebastianbochan** [comment]
Hi @khoaanh2212,
You should also set `enabled: true` in the `datalabels` object.

Demo:
- http://jsfiddle.net/BlackLabel/zkru45a9/

If it will not work in your scenario, please update my code with yours for the further debugging.
