### ISSUE TITLE
No flag shapes in the Flag Shapes and Colors demo?

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#8699]
In Chrome 67.0.3396.99, https://www.highcharts.com/stock/demo/flags-shapes doesn't show any flags:

![image](https://user-images.githubusercontent.com/33569/43307060-0ae572ea-9132-11e8-9c8e-eec916c8385f.png)

**Comment by sebastianbochan** [comment]
Hi @dandv,
Flags are visible when you spread the range on xAxis (use navigator handles).

**Comment by dandv** [comment]
I see. May I suggest initializing the chart with such a range that the flags are visible? Otherwise, users may think the demo doesn't work.

**Comment by sebastianbochan** [comment]
Hi @dandv,
We will fix our demo as soon as possible to avoid confusing.
