### ISSUE TITLE
Highcharts Custom Events

### ISSUE THREAD

**Issue by chalecki** [highcharts/highcharts#8702]
Hello!

I want to extend the capabilities of Highchart. 
I’ve got a formatted code that displays the category (category name) on the x-axis. It looks like that

![bar-chart-custom-y-axis-label](https://user-images.githubusercontent.com/6918096/43330925-d6789d0a-91c4-11e8-9a24-b8f16028f815.png)

I’ve found a library which allows handling an event after clicking the label on the x-axis (category). 
The problem gets even more complicated when we have formatted category name like this:

```
<div class="bar-chart-xlabel">
    <i class="material-icons set-filter-icon">filter_list</i>
    <i class="material-icons set-filter-icon">filter_list</i>
    <span>${this.value}</span>
</div>
```

After clicking the label as ’value’ I’ll get an entire HTML code as ’String’. 
Each icon should call different function, additionally I need to give a parameter to each of the functions.

How to solve this problem?

#### Example demo
http://jsfiddle.net/vy8ujtnk/

#### Versions
Highcharts: 6.1.1
Highcharts customEvents: 2.1.6

**Comment by sebastianbochan** [comment]
Hi @chalecki,
The custom-events is external plugin, co please report bug [here](https://www.highcharts.com/products/plugin-registry/single/15/Custom-Events)
