### ISSUE TITLE
Getting Error: <text> attribute x: Expected length, "NaN",Error: <rect> attribut..... second time load highchart page using Electron-VUE

### ISSUE THREAD

**Issue by alanzbl** [highcharts/highcharts#8703]
highcharts": "^6.0.7
I have set up two windows in Electron-vue, second window as background window feeding data to main window where the highchart is. 
First time into highchart works perfectly. If I load another page and come back to the page. error out:
```
Error: <text> attribute x: Expected length, "NaN".
Error: <rect> attribute rx: Expected length, "undefined".
Error: <rect> attribute ry: Expected length, "undefined".
Error: <rect> attribute x: Expected length, "NaN".
Error: <rect> attribute y: Expected length, "NaN".
Error: <rect> attribute width: Expected length, "NaN".
Error: <rect> attribute height: Expected length, "NaN".
Error: <rect> attribute width: Expected length, "NaN".
Error: <rect> attribute height: Expected length, "NaN".
```
I printed out renderer: 
```javascript
{
  "style": {
    "fontFamily": "\"Lucida Grande\", \"Lucida Sans Unicode\", Arial, Helvetica, sans-serif",
    "fontSize": "12px"
  },
  "isSVG": true,
  "box": {},
  "boxWrapper": {
    "element": {
      "$ref": "$[\"box\"]"
    },
    "renderer": {
      "$ref": "$"
    },
    "styles": {
      "fontFamily": "\"Lucida Grande\", \"Lucida Sans Unicode\", Arial, Helvetica, sans-serif",
      "fontSize": "12px"
    }
  },
  "alignedObjects": [
    {
      "element": {},
      "renderer": {
        "$ref": "$"
      },
      "zIndex": 4,
      "added": true,
      "styles": {
        "color": "#333333",
        "fontSize": "18px",
        "fill": "#333333",
        "width": "NaNpx"
      },
      "textCache": ",false,false,,,18px,NaN",
      "textWidth": null,
      "alignOptions": {
        "y": 14,
        "style": {
          "$ref": "$[\"alignedObjects\"][0][\"styles\"]"
        },
        "text": null
      },
      "alignByTranslate": false,
      "alignTo": "spacingBox",
      "placed": true,
      "alignAttr": {
        "x": 0,
        "y": 14
      }
    },
    {
      "element": {},
      "renderer": {
        "$ref": "$"
      },
      "alignValue": "center",
      "zIndex": 4,
      "added": true,
      "styles": {
        "color": "#666666",
        "fill": "#666666",
        "width": "NaNpx"
      },
      "textCache": ",false,false,,,,NaN",
      "textWidth": null,
      "alignOptions": {
        "y": 14,
        "style": {
          "$ref": "$[\"alignedObjects\"][1][\"styles\"]"
        },
        "text": "",
        "align": "center",
        "widthAdjust": -44
      },
      "alignByTranslate": false,
      "alignTo": "spacingBox",
      "placed": true,
      "alignAttr": {
        "x": null,
        "y": 14
      }
    }
  ],
  "url": "",
  "defs": {
    "element": {},
    "renderer": {
      "$ref": "$"
    },
    "added": true
  },
  "gradients": {},
  "cache": {},
  "cacheKeys": [],
  "imgCount": 0,
  "width": 640,
  "height": 400,
  "chartIndex": 1,
  "spacingBox": {
    "width": null,
    "height": null
  },
  "plotBox": {
    "x": null,
    "y": null,
    "width": null,
    "height": null
  }
}
```
Code is fairly simple setup <highchart :options="graphOptions"></highcharts>

```javascript
graphOptions: {
        chart: {
          type: 'line',
          animation: false,
          shadow: false,
        },
        title: {
          text: null
        },
        plotOptions: {
          series: {
            animation: false,
            shadow: false,
            marker: {
              enabled: false,
            }
          },
        },
        exporting: {
          enabled: false
        },
        credits: {
          enabled: false
        },
        tooltip: {
          enabled: false
        },
        legend: {
          enabled: false
        },
        xAxis: {
          lineWidth: 5,
          lineColor: '#6D6E71',  // grey rgb(109, 110, 113),
          labels: {
            enabled: true,
            align: 'center',
            formatter: function() {
              return this.value; // samples to seconds
            },
            style:{
              fontSize: '1.25em'
            }
          },
          allowDecimals: false,
          title: {
            text: 'TIME (s)',  // TODO $t() Tanslation?
            style: {
              fontSize: '1.5em'
            }
          },
        },
        yAxis: {
          min: -1050,
          max:  1050,
          lineWidth: 5,
          lineColor: '#6D6E71',  // grey rgb(109, 110, 113),
          title: {
            text: 'ROTATIONAL VELOCITY (deg/s)', // TODO $t() Tanslation?
            style: {
              fontSize: '1.5em'
            }
          },
          labels: {
            enabled: true,
            style: {
              fontSize: '1.25em'
            }
          },
        },
        series: []
      }
```
I couldn't reproduce the issue elsewhere.. IDK why...

**Comment by alanzbl** [comment]
@pawelfus 
Both times have shown 640px in the console. 
Here are the html elements from devtool: 
<div data-v-5a625647="" data-v-6cc43b88="" id="container" data-highcharts-chart="1" dir="ltr">
   <div id="highcharts-sqmqnog-3" dir="ltr" class="highcharts-container " style="position: relative; overflow: hidden; width: 640px; height: 11200px; text-align: left; line-height: normal; z-index: 0; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
      <svg version="1.1" class="highcharts-root" style="font-family:&quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, Arial, Helvetica, sans-serif;font-size:12px;" xmlns="http://www.w3.org/2000/svg" width="640" height="11200" viewBox="0 0 640 11200">
         <desc>Created with Highcharts 6.1.1</desc>
         <defs>
            <clipPath id="highcharts-sqmqnog-4">
               <rect x="0" y="0" width="NaN" height="NaN" fill="none"></rect>
            </clipPath>
         </defs>
         <rect fill="none" class="highcharts-background" x="0" y="0" width="640" height="11200" rx="undefined" ry="undefined"></rect>
         <rect fill="none" class="highcharts-plot-background" x="NaN" y="NaN" width="NaN" height="NaN"></rect>
         <rect fill="none" class="highcharts-plot-border" data-z-index="1" x="0" y="0" width="0" height="0"></rect>
         <g class="highcharts-series-group" data-z-index="3"></g>
         <text x="0" text-anchor="undefined" class="highcharts-title" data-z-index="4" style="color:#333333;font-size:18px;fill:#333333;" y="14"></text>
         <text x="NaN" text-anchor="middle" class="highcharts-subtitle" data-z-index="4" style="color:#666666;fill:#666666;" y="14"></text>
      </svg>
   </div>
   <svg version="1.1" class="highcharts-root" style="font-family:&quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, Arial, Helvetica, sans-serif;font-size:12px;" width="752" height="400" viewBox="0 0 752 400">
      <desc>Created with Highcharts 6.1.1</desc>
      <defs></defs>
   </svg>
</div>

**Comment by alanzbl** [comment]
@pawelfus Thank you for helping me out.
My original project is fairly big and I couldn't reproduce the issues in a sandboxed version. 
I've narrowed down the issue:
          It happens only after bluetooth connection in background window (bluetooth-serial-port & Win-BT); data is transmitted (does not matter if the data is from bluetooth); the second time I revisit highchart page, error out. 

I can provide some relative source code that might matter. Or I can keep trying creating the sandboxed version which I am not certain it can reproduce the issue. I feel like bluetooth connection here somehow messed up with highchart. Suggestions?

**Comment by pawelfus** [comment]
Without live demo we won't be able to fix the issue (if this is Highcharts issue). You can share your chart initialization (with config options), maybe our eyes can catch something. 

It looks like something is wrong with dimensions of the chart. That suggest the container is malformed (wrong width, height, hidden?). You can try older versions of Highcharts (e.g. v5), maybe it's a regression on our side, that would certainly help. If none of the above helps, then you either need to recreate issue in the sandboxed env, so we can debug this, or you will need to debug this (use `src.js` files).

**Comment by alanzbl** [comment]
Hello @pawelfus, 
I was able to recreate the issue: https://github.com/alanzbl/Highchart_Bug_Recreation
I also found the solution that I shouldn't pass an object via eventEmitter; however, I still wanna know how this messes up with Highchart initialization. 
Thanks!

**Comment by pawelfus** [comment]
Thanks for the repo with bug! However it looks like not all packages are installed/added to the package.json. I'm not able to rune the example, here is error:

```
$ npm run dev

> highchart-test@0.0.0 dev /Users/pawelfus/githubissues/Highchart_Bug_Recreation
> node .electron-vue/dev-runner.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/pawelfus/githubissues/Highchart_Bug_Recreation/.electron-vue/dev-runner.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! highchart-test@0.0.0 dev: `node .electron-vue/dev-runner.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the highchart-test@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by alanzbl** [comment]
@pawelfus That's bizarre. It works well on mine. Do you mind trying to remove node_modules folder and run npm install again to reinstall everything (or 'npm install' before 'npm run dev') ? It sometimes behaves weirdly on different machine.

**Comment by pawelfus** [comment]
Nope, that's not it. Could you check if you added to the repo all files? For example `projectName/.electron-vue`?

**Comment by pawelfus** [comment]
Thanks, now I was able to install example properly. I see you use two wrappers of Highcharts at the same time (?):

```
    "vue-electron": "^1.0.6",
    "vue-highcharts": "0.0.10", ---
    "vue-router": "^2.5.3",
    "vue2-highcharts": "^1.2.4", ---
```

And none of them is our product. Error comes from `/node_modules/vue2-highcharts/dist/vue-highcharts.js` to I suggest to contact authors of vue2-highcharts.

**Comment by alanzbl** [comment]
@pawelfus My apologies for that I should've posted pure highcharts version. I've tried too many wrappers. If you could pull from my repo again, I have updated to only highcharts without any wrappers.

**Comment by pawelfus** [comment]
Thanks! 

It looks like I found the reason, unfortunately, I'm not sure how to fix this (or at least work around the issue). In general it's a problem with merging default options and observable variable from vue. Actually doesn't look like direct issue with observable but with.. HighchartsPoint class generation (or, probably, both). To remove these observable references, vue suggest to use `JSON.parse(JSON.stringify(this.options))` which works in most cases. Let's compare results in your case. First follow instructions you have in the github repo, then:

- in the first window (`load background` part), in the console try: `JSON.parse('{}').constructor.name`. Result: `"Object"`
- in the second window (after error), in the console try the same: `JSON.parse('{}').constructor.name`. Result: `"HighchartPoint"`

As you can see, any created object (even simple `var a = {}; a.constructor.name`) returns always constructor name as if this was generated by HighchartsPoint class. I think this is wrong, we can not distinguish internally if anything is a constructor class or a simple object. Every nested object we get from `this.options` suggest it's an instance of HighchartsPoint. Probably we could fix this in our code, but it looks like a bug in vue/electron (I don't know which one, sorry) and this shouldn't affect our code. I'm not a master in vue+electron so I may be wrong.

**Comment by alanzbl** [comment]
@pawelfus Thank you for help!!! I kinda get around by emitting everything stringified instead of objects. But I'll try to see if anything else that could help the case hopefully. Thanks again
