### ISSUE TITLE
Sunburst -  dataLabels.useHTML is not working properly in dataLabless.formatter function.

### ISSUE THREAD

**Issue by vbiarulkumar** [highcharts/highcharts#8704]
#### Expected behaviour
Styles are not applied to child element when applied style in root element.
EX: <span style='color:#ff0000'><span style='white-space:pre;'>205.00</span></span>

#### Actual behaviour
Should apply styles to the child element.

#### Live demo with steps to reproduce
Working in Pie: https://jsfiddle.net/3op8y1rx/4/
Not working in Sunburst: https://jsfiddle.net/qweghk4b/23/

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @vbiarulkumar,
Thank you for reporting.

**Internal note**
It looks like a problem in this merge: https://github.com/highcharts/highcharts/blob/master/js/modules/treemap.src.js#L1161 which does not extract options from series.

@jon-a-nygaard
