### ISSUE TITLE
CISCO "VPN" and Highcharts

### ISSUE THREAD

**Issue by rafael-trevisan** [highcharts/highcharts#8709]
Hi all,

IT department has implemented some CISCO "VPN" solution that broke all application pages that use Highcharts :(

Here's what is happening:

![highchart error](https://user-images.githubusercontent.com/17282530/43425063-51e248ae-9406-11e8-9f64-d33c005e2f85.png)

Unfortunately, I don't know much about this CISCO so-called solution they've implemented. I know that whenever I open my application page now the URL has been changed to point to some CISCO server and then Highcharts doesn't work anymore.

![csco](https://user-images.githubusercontent.com/17282530/43425243-d5ecd290-9406-11e8-8664-a8f412e2c470.png)

I'll try to find out more about the solution they've implemented, but in the meantime, has someone had this problem before?

It's worth to say: there're another JS libraries in the page and they're working well... only Highcharts has been broken with this thing 😕

**Comment by rafael-trevisan** [comment]
Thanks, @sebastianbochan.

I was using Highcharts JS v5.0.14 (2017-07-28). I upgraded to Highcharts JS v6.1.1 (2018-06-27) and now everything is working fine with this CISCO thing.

Highcharts is awesome! 👍

**Comment by sebastianbochan** [comment]
Hi @rafael-trevisan,
Thank you for the feedback.
