### ISSUE TITLE
Rotated xAxis labels are not wrapped in 2.2.1

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#871]
Example in 2.1.6: http://jsfiddle.net/Fusher/QhMkc/2/
Example in 2.2.1: http://jsfiddle.net/QhMkc/1/

**Comment by sebastianbochan** [comment]
Since HC 4.0.1, whole category name is printed (http://jsfiddle.net/p5n21ek4/). But we have use ellipsis: http://jsfiddle.net/7em4ngm4/

If it still incorrect, reopen a bug.
