### ISSUE TITLE
Show only unique cetegories on yAxis

### ISSUE THREAD

**Issue by msh666** [highcharts/highcharts#8710]
Hello, I do not know if highchart support thi or not, thats why I'm here.
I have a long yAxis on my Heatmap chart and category for each, look like:
["a", "a", "a", "b", "b", "b", "c", "c"] the problem is that I need to show the category only if it's faced first time like this: 
["a", "", "", "b", "", "", "c", ""]
this is not a problem to pass categories like in example, BUT I need always show new faced category and this not always happend cause of tickInterval and enough spaces for each, cause other still exist on axis.
The interval between new coming can be different.

Is there are any possibilities to solve this problem or it is not supported in any cases?

Thank you

**Comment by sebastianbochan** [comment]
Hi @msh666,
The github is our bug tracker, so for general [support](http://www.highcharts.com/support) questions, please use stackoverflow / forum or email.

Ps. You can try to use [uniqueNames](https://api.highcharts.com/highcharts/yAxis.uniqueNames) option. If it will not solve your problem, please recreate your chart as live demo and contact with by support channels.
