### ISSUE TITLE
Keys are not being respected with dataGrouping unless zoomed

### ISSUE THREAD

**Issue by josh-byster** [highcharts/highcharts#8711]
#### Expected behaviour
With the default settings (not explicitly setting `dataGrouping: false`), the chart should not have an issue render.

#### Actual behaviour
I ran into this problem during a personal project and thought that updating to the latest version of Highstocks would fix, but it looks like there's still issues with not respecting keys as initially demonstrated in #6590. I'm using the same JSFiddle as used in the other issue for consistency, and to demonstrate that the fix doesn't seem to keep us from needing a workaround. From my debugging, it looks like it's not entering the if statement on line 937 shown [here](https://github.com/highcharts/highcharts/commit/2a8bab7083513d61ed5b2d1ecaf63a2d6725b3e8#diff-935901c6fb72a4ef40f8fc0977cb59bdR928). 

#### Live demo with steps to reproduce

https://jsfiddle.net/15qhj9oy/6/
#### Product version

Highstock 6.1.1
#### Affected browser(s)
Chrome 67 on Mac OS X

**Comment by pawelfus** [comment]
Hi @josh-byster 

Thanks for contacting us. This is caused by workaround for versions <5.0.11 in your code: 

    Highcharts.seriesTypes.line.prototype.pointArrayMap = ["open", "high", "low", "y"];

Remove this and your chart will be fine: https://jsfiddle.net/15qhj9oy/10/

**Comment by josh-byster** [comment]
Hey there @pawelfus, thanks for the reply. I actually just used the link from #6590 to give code to reproduce, but the issue is still there _without_ the workaround in the latest version. Since the code where the bug occurred is not open source, I cannot share it here. However I will try to reproduce.
