### ISSUE TITLE
Box Plot chart not rendering Axis labels as per min and max values

### ISSUE THREAD

**Issue by webXtended** [highcharts/highcharts#8712]
#### Expected behaviour
The Y-Axis is not showing labels according to the min and max set on the data 

#### Actual behaviour
When the size of the chart is small then the min and max value in y-axis is not being used.

#### Live demo with steps to reproduce
change the value of the height in
`<div id="container" style="height: 200px; margin: auto; min-width: 310px; max-width: 600px"></div>`
 to 300, then the correct min values for y-axis labels are shown, but make it 200 then the values are incorrect
https://jsfiddle.net/ebok7fa0/2/

**Comment by sebastianbochan** [comment]
Hi @webXtended,
Thank you for the reporting.

**Workaround**
Use [tickPositioner](https://api.highcharts.com/highcharts/yAxis.tickPositioner) which allows you to define calculation of ticks.
- https://jsfiddle.net/BlackLabel/td1943pu/

**Comment by webXtended** [comment]
thanks for the workaround @sebastianbochan

**Comment by TorsteinHonsi** [comment]
The [yAxis.min](https://api.highcharts.com/highcharts/yAxis.min) API also explains what happens:

> If the startOnTick option is true (default), the min value might be rounded down.

In this case, setting `startOnTick` to false probably gives the desired result: https://jsfiddle.net/highcharts/ebok7fa0/12/.
