### ISSUE TITLE
Series.cropData throws error for wind barb series

### ISSUE THREAD

**Issue by luuuke** [highcharts/highcharts#8713]
#### Expected behaviour

Wind barb's data gets cropped and later displayed. 

#### Actual behaviour

cropData throws an error as yData is undefined for the wind barb series type. 
Catching the case of yData being undefined and returning an undefined value for yData makes everything work again.  

#### Live demo with steps to reproduce

http://jsfiddle.net/4saL58wu/2/

Notice how the xAxis' min is later than the series' pointStart. Also cropThreshold is set to 0 for the series to always crop its data. If setting the min to the same value as pointStart or cropThreshold to a higher value, the error does not occur, as cropData is not called.

#### Product version
Highcharts, Highstock v6.1.1

**Comment by luuuke** [comment]
For now I "fixed" it by wrapping cropData and passing a bogus yData to it:

```javascript
Highcharts.wrap(Highcharts.Series.prototype, 'cropData', function (proceed, xData, yData, min, max, cropShoulder) {
    if (typeof yData === 'undefined') {
        yData = {
            slice: _.noop
        };
        let croppedData = proceed.call(this, xData, yData, min, max, cropShoulder);
        croppedData.yData = undefined;
        return croppedData;
    } else {
        return proceed.call(this, xData, yData, min, max, cropShoulder);
    }
});
```

**Comment by pawelfus** [comment]
Hi @luuuke 

Thank you for reporting the issue. It looks like a bug in our docs, `cropThreshold` is not supported by windbarb series: 

https://github.com/highcharts/highcharts/blob/602a2533ed92fbd951c36cb153d4657939565aec/js/modules/windbarb.src.js#L22-L24

Of course, this should be fixed, we can exceed default 200 points and this will be broken again: http://jsfiddle.net/BlackLabel/4saL58wu/8/

*Internal note:*
It looks like all options from this exclude exist in the docs, we should remove this. The same applies to `vector` or `pareto` series, but `sankey` is fine.  The only difference I see:

- vector:
https://github.com/highcharts/highcharts/blob/602a2533ed92fbd951c36cb153d4657939565aec/js/modules/vector.src.js#L19

- sankey:
https://github.com/highcharts/highcharts/blob/602a2533ed92fbd951c36cb153d4657939565aec/js/modules/sankey.src.js#L25

**Comment by TorsteinHonsi** [comment]
@sophiebremer Will you have a look at why the syntax matters? Propably the easiest fix is just to make sure we use the one syntax that works.

**Comment by luuuke** [comment]
I'm not sure if I'm understanding you right. So the guess is, that setting cropThreshold explicitly in the series config is causing it and by adjusting the docs it will be fixed? 
In my observations the error also occurs when not supplying cropThreshold (see http://jsfiddle.net/4saL58wu/13/). As a default value is then used instead, just more data is required to cause this problem.

**Comment by pawelfus** [comment]
Hi @luuuke 

This will be fixed in the core too. Simply we have two issues here: wrong docs and bug in code. As I said above: 

> Of course, this should be fixed, we can exceed default 200 points and this will be broken again: http://jsfiddle.net/BlackLabel/4saL58wu/8/
