### ISSUE TITLE
Error in Highstock (with boost): Cannot read property 'markerGroup' of undefined

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#8715]
#### Expected behaviour
The code included in the demo shouldn't produce any errors - all operations are quite standard.

#### Actual behaviour
The following errors occurs:
```
Uncaught TypeError: Cannot read property 'markerGroup' of undefined
    at object.<anonymous> (boost.src.js:2749)
```
#### Live demo
http://jsfiddle.net/BlackLabel/r321y4h6/

#### Product version
6.1.1

**Comment by kamilkulig** [comment]
_Internal note:_ Everything seems to work fine if `showInNavigator` is commented out: http://jsfiddle.net/BlackLabel/c03humpr/

**Comment by pawelfus** [comment]
*Internal note:*
Even when removed boost module, still we see error in the console (another, but still broken):  http://jsfiddle.net/BlackLabel/ja3q0kLe/

**Comment by TorsteinHonsi** [comment]
The error comes when running `Series.remove` on a navigator series after its parent has already been destroyed. The *workaround* is to remove only the parent series: http://jsfiddle.net/highcharts/r321y4h6/11/
