### ISSUE TITLE
HighStock: Issue with zoom buttons where datagrouping and lazyloading is enabled

### ISSUE THREAD

**Issue by meduza777** [highcharts/highcharts#8718]
#### Expected behaviour
Zoom buttons in Highstock Chart example "1.7 million points with async loading" should be able to work with data grouping option enabled.

#### Actual behaviour
"loading data from server" appears repeatedly - data is loaded repeatedly because afterSetExtremes function is called multiple times each time with new ranges.

#### Live demo with steps to reproduce
1. https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/lazy-loading/
2. change dataGrouping enabled property from false to true
3. run the script
4. click zoom button "1d" - and you'll see undesired behaviour

#### Product version
Highstock JS v6.1.1 (2018-06-27)

**Comment by meduza777** [comment]
My findings:
Button Click calls SetExtremes =>
chart redraw => 
axis.setScale => 
axis.setTickInterval(); => 
seriesProto.processData //Extend the basic processData method, that crops the data to the current zoom range, with data grouping logic.

last function adjusts xAxis.min property which leads to new setExtremes call. something is wrong here...

**Comment by pawelfus** [comment]
Hi @meduza777 

Thanks for reporting the issue. `lazy-loading` solution "expects" data grouping to be done on the server side, thus `dataGrouping` should be disabled. `lazy-loading` is more like a different approach of data-grouping/processing. 

More in our article: https://www.highcharts.com/blog/news/48-loading-millions-of-points-in-highcharts/

**Comment by meduza777** [comment]
In my case data is already prepared by serverside from pre-calculated tables, however it is still big sometimes for highcharts, especialy if i plot dozen of series at once in browser. And I want a user to be able to get data, that server currently gives, when exporting chart data to csv - current implementation of highcharts & datagrouping function allows this. So i think datagroping is cool feature to fine tune server's data for plotting. The only thing that it has a strange behaviour, described above, - to call setExtremes from within setExtremes call..

**Comment by pawelfus** [comment]
I'm not sure how this can be solved. Imagine this situation: current grouping for dataset is week. User zoomed into the range that starts on Friday.  Grouped points, by default, are rendered at the beginning of the group, so first grouped point is rendered on Monday. We need to adjust `xAxis.min` in order to show this first grouped point. Setting extremes should again fire `afterSetExtremes` because extremes simply changed.

Possible workaround is to limit when data from server is fetched: https://jsfiddle.net/BlackLabel/xd1vzojh/

```javascript
function afterSetExtremes(e) {

  var chart = Highcharts.charts[0];

  if (e.trigger === 'zoom' || e.trigger === 'rangeSelectorButton' || e.trigger === 'navigator') {
    chart.showLoading('Loading data from server...');
    $.getJSON('https://www.highcharts.com/samples/data/from-sql.php?start=' + Math.round(e.min) +
      '&end=' + Math.round(e.max) + '&callback=?',
      function(data) {

        chart.series[0].setData(data);
        console.log(e, e.min, e.max);
        chart.hideLoading();
      });
  }
}
```
