### ISSUE TITLE
highcharts: className not set when marker disabled

### ISSUE THREAD

**Issue by anitakurz** [highcharts/highcharts#8729]
It is possible to set a className on a dataPoint in the series in most charts. Unfortunately this className is not applied when the marker is disabled (plotOptions -> series -> marker -> enabled: false).
Since Issue #8119 is fixed, the class is set at least on the halo but still not on the point itself.

To reproduce, just add a className to a dataPoint in [marker enabled demo](http://jsfiddle.net/atm29bgr/1/).

JavaScript:
```javascript
Highcharts.chart('container', {
    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },
    plotOptions: {
        series: {
            marker: {
                enabled: false
            }
        }
    },
    series: [{
        data: [{y:29.9, className:'test'}, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    }]
});
```
CSS:
```css
.test {
  cursor:pointer;
}
```

Expected result: the cursor is a pointer when hovering over the first dataPoint.
Current result: the cursor doesn't change for version < 6.1.0 while the cursor only changes on the halo of the point for version >= 6.1.0

**Comment by sebastianbochan** [comment]
Hi @anitakurz,
Thank you for reporting. 

**Workaround**
Add sibling to current class.

```
.test, .test + path {
  cursor: pointer;
}
```

Example:
- http://jsfiddle.net/BlackLabel/7xyrgz9s/

**Internal note**
Lets consider to apply the class on all elements from marker group

**Comment by anitakurz** [comment]
Hi @sebastianbochan 

Thanks a lot for the workaround.
It works fine for version >= 6.1 as the class is set on the halo.

Am I correct that there is no workaround for version < 6.1 (as there the class is not set at all, not even on the halo)? It's not a big problem for us, as we will upgrade to the latest version soon.

**Comment by sebastianbochan** [comment]
Hi @anitakurz,
You are right, in previous versions its not applied at all. So I recommend to update to the newest version.
