### ISSUE TITLE
Boosted area displays beyond pane when yAxis height is decreased and min is set to some positive value.

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#8731]
#### Expected behaviour
Area series starts from the the min value of yAxis (just like line series).

#### Actual behaviour
Area series goes beyond the min value and displays outside the pane.

#### Live demo
http://jsfiddle.net/BlackLabel/w8otdhnp/ - line series, works
http://jsfiddle.net/BlackLabel/c9ek6pdb/ - area series, does not work

**Comment by vishalpherwani** [comment]
Hi Paul, any updates on when can we get this fixed? the boosted area displays beyond the pane when we try to define some min value, it breaks our fundamental requirement to use the area chart with any other chart for data segregation and comparison purposes. Is there any ETA as to when can this be fixed? 
Thanks!

**Comment by TorsteinHonsi** [comment]
@cvasseng Any insight?

**Comment by cvasseng** [comment]
The answer is likely in [this block](https://github.com/highcharts/highcharts/blob/master/js/modules/boost.src.js#L1801-L1810). I think `minVal` needs to be set to `yAxis.min` in there if it's not a range series or a stacked series.

**Comment by vishalpherwani** [comment]
@cvasseng @TorsteinHonsi : any update on the fix?

**Comment by TorsteinHonsi** [comment]
Hi @vishalpherwani, we're working on a fix, expect it to be fixed pretty soon.

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/c9ek6pdb/14/

We're just preparing a release, and expect it ready for publishing tomorrow or early next week.

**Comment by vishalpherwani** [comment]
Thank you @TorsteinHonsi ! please update once it is published.

**Comment by KacperMadej** [comment]
@vishalpherwani version 6.1.2 was published.
Demo with version 6.1.2: http://jsfiddle.net/BlackLabel/8po7m3ct/

**Comment by vishalpherwani** [comment]
Thank you @KacperMadej
