### ISSUE TITLE
Let plotOptions.series.zones.value accept a function that takes a point object and returns a boolean

### ISSUE THREAD

**Issue by jamiechong** [highcharts/highcharts#8732]
It would be great if we could override the default behaviour of  `plotOptions.series.zones.value`. 

In my situation I would like to control the zone on values other than `point.x` or `point.y` (I have a custom value).

**Comment by pawelfus** [comment]
Hi @jamiechong 

Could you provide more details? Do you mean column series? I don't quite understand how this should work for a line/spline series. If this is column type, then you can preprocess data adding `color` option to each point: http://jsfiddle.net/BlackLabel/t3kmhL8q/2/

Current implementation of zones expects zones to be rectangles. That means we have only x/y values to use (so we can translate to x/y pixel coords).

**Comment by sebastianbochan** [comment]
Hi @jamiechong,
The zone requires the `value` param which declares end point of a zone. If you need to extract the information form point, use reference to index of point.

Demo:
- https://jsfiddle.net/BlackLabel/7gLfpyoh/

Let me know if its correct with your expecations?

**Comment by sebastianbochan** [comment]
Hi @jamiechong,
Thank you for the feedback. For general suggestion I recommend you to use our [userVoice](https://highcharts.uservoice.com/) and post your idea there.

**Comment by pawelfus** [comment]
@jamiechong 

I'm sorry, I still don't understand how this should work. As I said above, zones are rectangles so we need `x` or `y` reference. In your example with `zoneAttribute` you still use `zoneAxis: 'x'`. What if `zoneAttribute` has no correlation with `x`-values? For example this is dataset: `[ 0, 1, 10], [1, 1, 1], [2, 2, 11]] // [x, y, customParam]` and zones are defined as `{ zoneAxis: 'y', zoneParam: 2, zones: [{ value: 5, color: 'red'}, { value: 15, color: 'green' } ] }`. Where 'green' line should start and where 'red' should end? Not to mention that line is a horizontal line. 

Could you show an example of expected output for you dataset and zones settings? Thanks!

**Comment by OysteinAmundsen** [comment]
I have a use case for this: 

I'm using a dynamically updated areaspline graph, similar to https://www.highcharts.com/stock/demo/dynamic-update, and I want the zone to be the second last x value always, as to highlight where the value enters the graph. Now I cannot set a static `value` in the zone config, as this value will change over time. I could update the zone value each time I receive a new entry in my dataset, but there does not appear to be any method to update it.

**Comment by pawelfus** [comment]
Thanks for the details @OysteinAmundsen - when you update dataset (e.g. `addPoint()` or `setData()`), you can call `series.update({ zones: [ ... ] })` and update series with new zones. It won't have the best performance but should work.
