### ISSUE TITLE
Range Selector Unable to update to enabled:true

### ISSUE THREAD

**Issue by briankpw** [highcharts/highcharts#8733]
#### Expected behaviour
Range Selector should be to update from enabled:false to true. 

#### Actual behaviour
When there is range selector init enable:false, its wont update to true

#### Live demo with steps to reproduce

Highstock rangeSelector unable to enabled to true when we use chart.update. 
http://jsfiddle.net/a4gyupvt/

But if initialize the rangeSelector enabled to true and we chart.update enabled: false, its work
http://jsfiddle.net/edozmgnr/

#### Product version

 6.1.0

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @briankpw,
Thank you for reporting. The rangeSelector is initalized only in the `afterGetContainer` event, triggered on the chart init. In the update its missing, as a result, rangeSelector object does not exist.

Workaround: 
Set `options.rangeSelector.enabled` as true and fire event   `afterGetContainer`

Demo:
- https://jsfiddle.net/BlackLabel/aL9v6qw0/
