### ISSUE TITLE
setCategory() with false redraw options ruined tooltip

### ISSUE THREAD

**Issue by msh666** [highcharts/highcharts#8734]
setCategory() with false redraw options ruined tooltip

ex:
http://jsfiddle.net/msh666/hsp8werb/

When we pressed "Setcategories" Tooltip stop working

If it is okay situation, so then tooltip should not be shown at all.

**Comment by pawelfus** [comment]
Hi @msh666 

Thank you for reporting this issue. Can you tell us more about your use case? In general, `chart.redraw()` should be postponed when applying multiple changes on the chart, then called immediately. For example `x/yAxis.update()` works the same way: http://jsfiddle.net/BlackLabel/hsp8werb/1/ 

*Internal note:*
We can consider this as a regression (v4 works fine: http://jsfiddle.net/BlackLabel/hsp8werb/4/ ) - however, in v4 we replaced tooltip searching logic with kd-tree so probably that's the reason.

**Comment by msh666** [comment]
@pawelfus 
Yeah, v4 works as I imagine it.

But what is v4 is it new or beta verison of highcharts?

**Comment by pawelfus** [comment]
Current release is v6, v4 is an old version of Highcharts. That was only an internal note.
