### ISSUE TITLE
gapSize doesn't work in boost module

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#8735]
#### Expected behaviour
Gaps should be draw the same with and without boost module.

#### Actual behaviour
Gaps don't work in boost mode.

#### Live demo with steps to reproduce
Works fine (no boost): http://jsfiddle.net/BlackLabel/8bect5rh/
Doesn't work (with boost): http://jsfiddle.net/BlackLabel/78yb3596/

#### Product version
6.1.1

**Comment by TorsteinHonsi** [comment]
The logic for `gapSize` is performed when the path is generated, so it is skipped in boost mode: https://github.com/highcharts/highcharts/blob/v6.1.0/js/modules/broken-axis.src.js#L430.

Probaly it needs to either be re-implemented in WebGL (look for similar `connectNulls` logic), or added to the list of missing features in Boost.

@cvasseng

**Comment by KacperMadej** [comment]
+1
