### ISSUE TITLE
Negative xCategories when switching legend

### ISSUE THREAD

**Issue by Blapi** [highcharts/highcharts#8743]
Hi !

#### Expected behaviour
When using the legends on a highchart with 2 series, I'd expect that the serie with the less data is displayed with only the available data according to its xCategories.

#### Actual behaviour
Extra xCategories (both negative and positive integers) are displayed alongside the defined and matched xCategories.

#### Live demo with steps to reproduce
https://jsfiddle.net/93fy7hbp/18/
=> Click on "Click me" legend to disable it, you will see extra negative and positive values as xCategories

(By the way, if the "Click me" legend is already disabled on start, it's working properly)

#### Product version
highcharts@6.1.1

#### Affected browser(s)
Chrome (possibly more, only tried on Chrome)

**Comment by sebastianbochan** [comment]
Hi @Blapi,
Could you describe step by step how can I replicate the probelm and let me know which version of OS / Chrome do you have? Unfortunately I was not able to replicate the issue.

![legendclick](https://user-images.githubusercontent.com/2115686/43835818-9027d30e-9b13-11e8-91db-40dd7a822c95.gif)

Chrome: 68.0.3440.84
MacOSX: 10.12.4

**Comment by Blapi** [comment]
Check my jsfiddle please : 

https://jsfiddle.net/93fy7hbp/18/
=> Click on "Click me" legend to disable it, you will see extra negative and positive values as xCategories

**Comment by Blapi** [comment]
Check my jsfiddle please :

https://jsfiddle.net/93fy7hbp/18/
=> Click on "Click me" legend to disable it, you will see extra negative and positive values as xCategories

**Comment by sebastianbochan** [comment]
Thank you for the feedback and the right demo. The issue is caused by missing `type` parameter on xAxis, so columns are positioned in the center of chart (by default) and for -1 you do not have declared category name (categories are array, indexed from 0). 

The solution is setting `min` and `max` parameter.

Demo:
- https://jsfiddle.net/BlackLabel/k5ehbtz2/

or set the right type in `xAxis`

Demo:
- https://jsfiddle.net/BlackLabel/zyL5tpqx/

**Comment by Blapi** [comment]
`type: 'category'` works like a charm ! Thanks a lot for your very quick help @sebastianbochan !
