### ISSUE TITLE
Series flickering on hover in Microsoft Edge

### ISSUE THREAD

**Issue by cvleesen** [highcharts/highcharts#8744]
#### Expected behaviour
Chart is rendered without flickering in all browsers

#### Actual behaviour
The chart is flickering randomly in Microsoft Edge. 

#### Live demo with steps to reproduce
https://jsfiddle.net/cvleesen/m265bsuk/

Just move the mouse randomly over the first 2 bars in Microsoft Edge. After a while the flickering should start like this:
![flickering](https://user-images.githubusercontent.com/26432225/43830891-b2cfa230-9b02-11e8-9881-092fac46cc36.gif)

Apart from the jsfiddle above I can even reproduce this behaviour in the showcase (e.g. on https://www.highcharts.com/demo/bar-stacked):

![flickering-showcase](https://user-images.githubusercontent.com/26432225/43831152-72984414-9b03-11e8-8e2c-dc51b87a65eb.gif)

#### Product version
Highcharts JS v6.1.1 + JQuery 1.9.1 (but also with pure JS as in the showcase example)

#### Affected browser(s)
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

**Comment by TorsteinHonsi** [comment]
I can't reproduce this on BrowserStack - @jon-a-nygaard can you see it in native Edge?

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi Yes, I am. It seems that Edge is struggling to redraw the svg elements when there is "too much" interaction for it to handle.

I found that there is similar issues reported that Microsoft Edge 42.17134.1.0 Microsoft EdgeHTML 17.17134 has a bug with this. One of them can be found at https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3723601/#comment-19

**Comment by tawu05** [comment]
We are using HighCharts bar chart in our product. And I'm seeing the same flickering issue in Edge browser (Microsoft Edge 42.17134.1.0 Microsoft EdgeHTML 17.17134).

Do we have any workaround to this issue? Thanks!

**Comment by TorsteinHonsi** [comment]
@tawu05 We did some experimenting with dynamic elements in the chart. Apparently disabling the hover state of the columns does not help. We also tried disabling the tooltip and setting tooltip.animation to false, to no avail.

The only thing that actually did help was to set `enableMouseTracking` to false on the series, but then you throw away the baby with the bathwater, as no tooltip will display.

**Comment by tawu05** [comment]
@TorsteinHonsi, Thanks very much! 

Currently we disabled the tooltip animation and hover state of the series. The flickering issue is not totally fixed but it gets better. We cannot set enableMouseTracking to false since we need tooltip in the chart.

Is there any ETA when this issue can be fixed? Thanks!

**Comment by TorsteinHonsi** [comment]
> Is there any ETA when this issue can be fixed?

I'm afraid not - since we don't know the actual cause. All symptoms point to an underlying SVG rendering bug in Edge.

> Currently we disabled the tooltip animation and hover state of the series.

Great. And if I were you I would do that conditionally, so it is only disabled for Edge, maybe even this specific version, hoping it will be fixed in the next release.

**Comment by tawu05** [comment]
@TorsteinHonsi Thanks!

Currently we do it only for Edge. Check the version is a good idea! I will try to figure out which Edge browser version has that problem.

**Comment by yoisel** [comment]
We have *many* performance issues with svg and MS Edge v42 in a project I am working on. The workaround that is working for us is to remove any kind of text from the svg objects (we discovered this by mare change). So we have to use useHTML for almost every attribute in highcharts. If we forget even one, some of our test systems will take up to a minute to show a chart that chrome shows in less than a second. Even IE11 is performing better.

**Comment by TorsteinHonsi** [comment]
@yoisel Are you running the latest version? We did a [refactoring](https://github.com/highcharts/highcharts/issues/5009) since v6.1.4 that greatly improves the rendering speed of long, multiline text in SVG.

**Comment by yoisel** [comment]
@TorsteinHonsi Thanks a lot for the response, that looks promising. Our category names are indeed a bit large. I will see if upgrading solves the performance issue.

Unfortunately with Edge 42 we have more issues to worry about, like text dissapearing from the chart for example, possibly related to this: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18322813. It's a never ending battle...

Thanks again.

**Comment by HardcoreParkore** [comment]
@yoisel Did upgrading seem to fix your problem at all? We're having the same issue with Edge on Highcharts v6.1.2
