### ISSUE TITLE
Line charts rendering wrong on Chrome OS

### ISSUE THREAD

**Issue by vfuse** [highcharts/highcharts#8747]
#### Expected behaviour
Linecharts rendering correctly

#### Actual behaviour
Line charts renders wrong on Chrome Version 67.0.3396.99 (Official Build) (64-bit) on certain window sizes.

#### Live demo with steps to reproduce
http://jsfiddle.net/1y9Lhqbc/10/

incorrect: https://i.imgur.com/CQj848v.png
correct: https://i.imgur.com/nrsQsdP.png
incorrect: https://i.imgur.com/H1xOd6G.png
incorrect: https://i.imgur.com/JmK3mJy.png
incorrect: https://i.imgur.com/MVaupMn.png

Have to press "run" button on jsfiddle once the page loads!

#### Product version

Highcharts latest version

#### Affected browser(s)
Chrome Version 67.0.3396.99 (Official Build) (64-bit)
Mac OS

**Comment by sebastianbochan** [comment]
Hi @vfuse,
Please let me know on which width the problem exist? Could you prepare two jsfiddles, one with worng width and the second with correct? It will allow me to replicate the issue, because at this moment, I was not able.

**Comment by vfuse** [comment]
http://jsfiddle.net/ck6qb5hs/

Here's an example that renders correctly, remember once the page load and the chart is rendered you have to press "run" again for this to show the incorrect rendering.

**Comment by sebastianbochan** [comment]
Hi @vfuse,
I run this demo: 
- `width: 2000px;` http://jsfiddle.net/BlackLabel/xrec0v9u/
- `width: auto;` http://jsfiddle.net/BlackLabel/jc463bng/

In both cases the chart is the same. Could you run two examples and let me know your results, or fix the width if Im wrong.

**Comment by vfuse** [comment]
The width was still set to 600 in the javascript so it would be:

width 200px: http://jsfiddle.net/oh2176cp/
width auto: http://jsfiddle.net/gL15rpv3/

**Comment by pawelfus** [comment]
It works for me the same every time in jsFiddle. Can this be a bug similar to #7662 ? Current version of Chrome (Version 68.0.3440.106 (Official Build) (64-bit)) works fine, and Chrome said they have fixed this bug. Could you update Chrome and confirm @vfuse ?

**Comment by vfuse** [comment]
Odd that I can't seem to reproduce after restarting chrome... I still hear this from several of my endusers so will keep an eye on it.

It does look like #7662 but this is not on hover, it renders like that without having to hover.

**Comment by pawelfus** [comment]
Thanks for confirming! #7662 was reported initially on hover action, but we were able to recreate issue in a standalone SVG elements, without mouseover events.
