### ISSUE TITLE
Browserstack fails

### ISSUE THREAD

**Issue by GardEngen** [highcharts/highcharts#8748]
#### Expected behaviour
Firefox 61.0.0 (Mac OS X 10.13.0): Executed 855 of 866

#### Actual behaviour
'test' errored after 12 min
Firefox 61.0.0 (Mac OS X 10.13.0): Executed 0 of 866

#### Live demo with steps to reproduce
npm run testall

#### Product version
master

#### Affected browser(s)
Mac Firefox Browserstack

**Comment by TorsteinHonsi** [comment]
Closing this as we are aware of some tests failing in various Browserstack instances. Awaiting full custom integration.
