### ISSUE TITLE
docs could describe csv export

### ISSUE THREAD

**Issue by fgnievinski** [highcharts/highcharts#8749]
Documentation for the [export modules overview](https://www.highcharts.com/docs/export-module/export-module-overview) could mention the possibility of [exporting csv](https://api.highcharts.com/highcharts/exporting.csv).

**Comment by sebastianbochan** [comment]
Hi @fgnievinski,
Thank you for the suggestion. I have passed this case to our dosc's publishers.

**Comment by TorsteinHonsi** [comment]
Fixed, thanks!
