### ISSUE TITLE
Docs: link series.typedata

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#8752]
At https://api.highcharts.com/class-reference/Highcharts.Series.html#setData:

> Takes an array of data in the same format as described under `series.typedata` for the given series type.

Where can `series.typedata` be found?

**Comment by sebastianbochan** [comment]
Hi @dandv,
Thank you for the reporting. The `series.typedata` should be `series.data` for any type of series.

Ref: 
- https://api.highcharts.com/class-reference/Highcharts.Series#.data

**Comment by dandv** [comment]
Another doc link suggestion: https://api.highcharts.com/highcharts/xAxis.events.afterSetExtremes could have a "Try it" link pointing to a demo.

**Comment by dandv** [comment]
Thanks @sebastianbochan. I'd be happy to submit a PR linking `series.typedata` to https://api.highcharts.com/class-reference/Highcharts.Series#.data but I don't see an edit button on **class-reference** pages. Is there another way to submit PRs for them, as it is for the JS API Reference pages?

**Comment by pawelfus** [comment]
There's no reference URL to the github parts for classes. It would be useful, I agree. 

Definition can be found here: https://github.com/highcharts/highcharts/blob/c78aa15292dfc3b5e39de922143d2363e8911472/js/parts/Series.js#L3153-L3196

**Comment by TorsteinHonsi** [comment]
It's just a typo, there is no such thing as `series.typedata`. What we are referring to is `series.{type}.data`, like [series.line.data](https://api.highcharts.com/highcharts/series.line.data).
