### ISSUE TITLE
Heatmap legend DOM elements recreated and not cleaned up on window resize

### ISSUE THREAD

**Issue by andi1984** [highcharts/highcharts#8754]
#### Expected behaviour

When window is resized the legend entries are kept and not recreated. Or at least in case of recreation, the old ones will be removed from DOM.

#### Actual behaviour

The current legend entries stack up with old legend entries  until a chart.update() is called and enabling/disabling for example the series data-labels or for example first disable the legend and enable it afterwards again. Then the old DOM elements are removed.

This happens even when chart.reflow is enabled or when chart.reflow() or chart.redraw() are called by hand.

#### Live demo with steps to reproduce

Unfortunately this happened on a very complex product heatmap which I have no demo for (yet). But in case you would need one, I think we could give you a product account to see it in action. Sorry for that.

#### Product version

Highcharts: 6.1.1

#### Affected browser(s)

Any

**Comment by andi1984** [comment]
As an addition, I can see that all my legend DOM elements have the class name `highcharts-undefined-series`. Looking at the source code I see that the series type 'heatmap' should be taken instead of undefined, but for whatever reason it is not. But in our own code we clearly specify

```
series: [
{
type: 'heatmap'
}
]
```

Not sure though this is related.

**Comment by pawelfus** [comment]
Hi @andi1984 

If you are not able to recreate issue in standalone env, please contact our support. They will help you setting up a demo. If this couldn't be recreated in a standalone env, then I expect to be a bug not related to Highcharts code.

**Comment by TorsteinHonsi** [comment]
Note: When resizing the pane of our [basic heatmap demo](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/heatmap/), the legend items are not recreated.
