### ISSUE TITLE
Drilldown Level number

### ISSUE THREAD

**Issue by Nijadas** [highcharts/highcharts#8757]
how can get the level number in drilldown highcharts

**Comment by sebastianbochan** [comment]
Hi @Nijadas,
Thank you for contacting us. This is our bug tracker for reporting issues, so for general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or forum.

ps. Its not limited, you an create as much levels as you need.

**Comment by sebastianbochan** [comment]
For general support questions please use forum / stackoverflow or forum.
