### ISSUE TITLE
the first point`s data went wrong when zoom in all the data

### ISSUE THREAD

**Issue by dolphinfine** [highcharts/highcharts#8765]
#### Expected behaviour
the first point shows correct data

#### Actual behaviour
the first point shows wrong data

#### Live demo with steps to reproduce
https://jsfiddle.net/c8xhnk3v/53/
1.select one month,and move the navigator to left,
the first point`s tooltip shows:date 2016-7-20,open 83.27 high 84.7 low 83.23 close 84.42.

2.move the navigator to all data,
the first point`s tooltip shows:date 2016-7-18,open 83.27 high 85 low 83.23 close 84.49.

3.the correct data of the first point is: date 2016-7-20,open 83.27 high 84.7 low 83.23 close 84.42.

#### Product version
Highstock JS v6.1.1

#### Affected browser(s)
chrome ,firefox,ms edge

**Comment by sebastianbochan** [comment]
Hi @dolphinfine,
By default, Highstock groups points to create single point and increase perfromance. As a result in the second scenario you can observe point with grouped value.

The solution is disable the option.
Demo:
- https://jsfiddle.net/BlackLabel/eznp0hya/

Docs:
- https://api.highcharts.com/highstock/plotOptions.series.dataGrouping.enabled
