### ISSUE TITLE
Cannot create property 'tooltip' on boolean 'false'

### ISSUE THREAD

**Issue by miladyeganeh** [highcharts/highcharts#8766]
#### Expected behaviour
If create a undefined property for tooltip in plotOpiton, it must be ignored and continue to create legal property

#### Actual behaviour
when I define a illegal property for high stock, It is thrown an exception and doesn't create chart.

#### Live demo with steps to reproduce

In line 21102 of highstock.src.js version 6.1.1 if use checking before create tooltip, the bug will be solve.
#### Product version

Highstock.src.js all version 

#### Affected browser(s)
Chrome, FireFox new version

**Comment by sebastianbochan** [comment]
Hi @miladyeganeh,
Could you prepare a live demo on the jsfiddle.net?

**Comment by miladyeganeh** [comment]
Hi Sebastian
on jsfiddle.net works properly but in my source doesn't work correctly. I reviewed highstock.src.js and changed the original code. After my changing highstock created my chart.

this is original snip
**********************************************************************************
 for (type in options.plotOptions) {
                options.plotOptions[type].tooltip = (
                          userPlotOptions[type] &&
                          merge(userPlotOptions[type].tooltip) // override by copy
                          ) || undefined; // or clear
   }
**********************************************************************************
and I've changed to this.

 for (type in options.plotOptions) {
         if (options.plotOptions[type].tooltip !== undefined ){
                        options.plotOptions[type].tooltip = (
                                userPlotOptions[type] &&
                                merge(userPlotOptions[type].tooltip) // override by copy
                            ) || undefined; // or clear
         }
}

and this is my Json
*************************************************************************************************
area:{lineWidth: 2, allowPointSelect: false, showCheckbox: false, animation: {…}, events: {…}, …}
arearange:{marker: {…}}
areaspline:{lineWidth: 2, allowPointSelect: false, showCheckbox: false, animation: {…}, events: {…}, …}
areasplinerange:{marker: {…}}
bar:{lineWidth: 2, allowPointSelect: false, showCheckbox: false, animation: {…}, events: {…}, …}
candlestick:{lineWidth: 1, allowPointSelect: false, showCheckbox: false, animation: {…}, events: {…}, …}
column:{lineWidth: 2, allowPointSelect: false, showCheckbox: false, animation: {…}, events: {…}, …}
columnrange:{shadow: false, borderWidth: 0}
flags:{lineWidth: 1, allowPointSelect: false, showCheckbox: false, animation: {…}, events: {…}, …}
line:{lineWidth: 2, allowPointSelect: false, showCheckbox: false, animation: {…}, events: {…}, …}
ohlc:{lineWidth: 1, allowPointSelect: false, showCheckbox: false, animation: {…}, events: {…}, …}
opposite:false
pie:{lineWidth: 2, allowPointSelect: false, showCheckbox: false, animation: {…}, events: {…}, …}
**reversed:false
**rtl:false
scatter:{lineWidth: 0, allowPointSelect: false, showCheckbox: false, animation: {…}, events: {…}, …}
series:{stacking: "normal", rtl: false, useHTML: true, reversed: false, opposite: false}
spline:{lineWidth: 2, allowPointSelect: false, showCheckbox: false, animation: {…}, events: {…}, …}
**useHTML:true
****************************************************************************************************
I've mentioned illegal properties with asterisks that couldn't be recognized

**Comment by sebastianbochan** [comment]
Hi @miladyeganeh,
Thank you for the feedback. In general editing source of code is not safe, because after update your fix will miss. Instead of it you can use `wrap` and overwrite the function.

Docs:
- https://www.highcharts.com/docs/extending-highcharts/extending-highcharts

The best solution is prepare us, a live demo which will allow to debug the problem and prepare stable fix.

**Comment by miladyeganeh** [comment]
Hi @sebastianbochan 
Thank you for your reply, I'll do it.

**Comment by TorsteinHonsi** [comment]
Closing this as inactive. Please don't hesitate to reopen if you have a live demo with fail case.

**Comment by sebastianbochan** [comment]
Im reopening, because the issue is still valid and appears only with `highcharts.src.js` file, not with minified.

Simplified demo:
- https://codepen.io/anon/pen/oVMMzy

**Comment by pawelfus** [comment]
Simplified demo: https://jsfiddle.net/BlackLabel/8o47mnqw/4/

```javascript
let tooltip_error = new Highcharts.Chart('container', {
  plotOptions: {
    randomProperty: true, // <--- error
    series: {
      color: 'red'
    }
  }
});

```
