### ISSUE TITLE
Strange ticks behaviour when screen is stretched - Highstock (ordinal = true)

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#8767]
#### Expected behaviour
When screen is stretched (with xAxis.ordinal set to true) all that should happen is that the distance between the labels increases.

#### Actual behaviour
When screen is stretched ticks are replaced in a strange way.

#### Live demo with steps to reproduce
https://jsfiddle.net/wchmiel/q5x1wkap/

1. Set screen width to about 1000px. Ticks are 9, 10, 11, 12, 13, 16, 17.....
2. Stretch screen to about 1500px width and notice strange ticks behaviour. Now they changed and are 9, 10, 11, 12, 14, 16, 17....

#### Product version
Highstock

#### Affected browser(s)
all

**Comment by cdburke** [comment]
Sebastian

I reported the issue originally on the Highstock forum. In this case, the highstock behaviour is clearly a bug.

Please understand that I do not want to set ordinal false. This displays the weekends, for which there is no data. Instead, I only want to see the dates (i.e. the weekdays) for which there is data.

Please see the Highstock forum messages ("incorrect date label on resize") for background, thanks.

Chris

**Comment by sebastianbochan** [comment]
Hi @cdburke,
Thank you for the feedback. It looks like a problem with `pointRange` calculation. If you are declare it, seems to work fine in the both resolutions (1000px, 1500px).

Demo:
- https://jsfiddle.net/BlackLabel/rbnmdh0u/

Let me know if worked properly.

**Comment by cdburke** [comment]
Hi Sebastian

Setting pointRange gives a slight improvement, but the problem remains.

On my machine, the original code (without setting pointRange) manifests the problem when window.innerWidth >= 1478. If pointRange is set, then the problem shows up when window.innerWidth >= 1596.

I see it on your fiddle if you change the container width to 1600px.

Chris

**Comment by pawelfus** [comment]
Hi @cdburke - nice to meet you!

If you want to render xAxis labels only where points exist, then [`xAxis.tickPositioner`](https://api.highcharts.com/highstock/xAxis.tickPositioner) is a good idea: https://jsfiddle.net/BlackLabel/q5x1wkap/7/ Solution to calculate xAxis labels is more complex than the one in my demo. Build-in positioner does not ensure the same x-positions, because x-positions.. vary when chart's width (and height) change. I'm not convinced if this is a bug, but it's already reported and acknowledged as one: #5536

**Comment by cdburke** [comment]
Hi Pawel

Thanks. Using xAxis.tickPositioner does prevent that problem, but it is more work to set up and I don't want to get into the business of calculating label extents to determine which dates should be labelled.

I do think this is a bug. It occurs in a very simple case (just 13 stock prices), where Highstock should just work out of the box. 

I understand that it may be buried deep in the code and hard to fix, but for me as a user, it is a show-stopper. 

Chris
