### ISSUE TITLE
Ticks aren't rendered properly if the timezone is UTC+0530

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#8768]
#### Expected behaviour
Ticks should appear along the entire span of the x axis.

#### Actual behaviour
Some of the ticks are missing:
![image](https://user-images.githubusercontent.com/13188589/44019448-73a6a268-9efc-11e8-99e8-1a0aa55ecedb.png)

#### Live demo with steps to reproduce

Change OS/Browser timezone to UTC+0530 (Delhi, Kolkata, Mumbai) and launch this fiddle:
http://jsfiddle.net/BlackLabel/tvhknz04/

#### Product version
6.1.1

**Comment by KacperMadej** [comment]
_Internal note:_
Problem comes from all time zones that have offset with not full hours (like H + 0:30 or 0:45).
Simpler demo: http://jsfiddle.net/BlackLabel/tvhknz04/1/

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/tvhknz04/11/

This fix will be part of the next maintenance release scheduled next week.
