### ISSUE TITLE
Scrollable plot area with background color

### ISSUE THREAD

**Issue by leokury** [highcharts/highcharts#8773]
#### Expected behaviour
Scrollable plot area should fill all chart's background area

#### Actual behaviour
The extended area is getting background page color

#### Live demo with steps to reproduce
http://jsfiddle.net/sbog6ep5/

#### Product version
6.1.1

#### Affected browser(s)
Tested in Google Chrome

**Comment by sebastianbochan** [comment]
Hi @leokury,
The white background is applied in Highcharts, by default. You should set `chart.backgroundColor` param as transparent.

Demo:
- http://jsfiddle.net/BlackLabel/23ygme0h/

Docs:
- https://api.highcharts.com/highcharts/chart.backgroundColor

**Comment by leokury** [comment]
Hello @sebastianbochan , 

is it also possible to have the white background fill the entire chart area (including scrollable area)?

**Comment by pawelfus** [comment]
Simple CSS should resolve the issue: http://jsfiddle.net/BlackLabel/sbog6ep5/9/ (background color set on container). I think this is a bug, background's width should be updated when scrollable plotting area is increased.

**Comment by leokury** [comment]
I agree. I also got other solutions on this [StackOverflow](https://stackoverflow.com/questions/51828636/how-to-make-scrollable-plot-area-fill-all-charts-background-area-in-highcharts).

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/sbog6ep5/11/
