### ISSUE TITLE
setExtremes(a,a),chart display is not normal

### ISSUE THREAD

**Issue by dolphinfine** [highcharts/highcharts#8774]
#### Expected behaviour
when click "2018/06-2018/06",display the same as click "2018/06-2018/07" or "2018/06-2018/08",
when click "2018/07-2018/07" or "2018/08-2018/08",display "no-data"
#### Actual behaviour
when you click "2018/06-2018/06",the column show on the right edge of the chart,
and the tick label is 2018/05,but the matched point tooltip shows 2018-06.
when you click "2018/07-2018/07",display 2018-05`s data;
when you click "2018/08-2018/08",display the same as click "2018/06-2018/06"

#### Live demo with steps to reproduce
https://jsfiddle.net/c8xhnk3v/83/
1.click "2018/06-2018/06"
2. click "2018/07-2018/07"
3.click "2018/08-2018/08"

#### Product version
highstock 6.11.1

#### Affected browser(s)
all

**Comment by sebastianbochan** [comment]
Hi @dolphinfine,
Thank you for the reporting.

**Internal note**
It looks like the problem is with calculating extremes on edges. 

Simplified demo:
- https://jsfiddle.net/BlackLabel/f25pztx3/ -> Click 1m and change navigator extremes. Columns flickering on navigator's moving.
