### ISSUE TITLE
cell shadow in heatmap: borders of cells are disappearing after mouse over

### ISSUE THREAD

**Issue by dmitrygorbenko** [highcharts/highcharts#8776]
I created simplest heatmap chart with shadow enabled.
On the demo chart from the beginning you can clearly see the cell borders (made by their shadows), and once you move mouse over the cells the shadow disappears and you can't see anymore cell borders.

#### Expected behaviour
When I "mouse out" from the cell the shadow of the cell gets back.

#### Actual behaviour
When I "mouse out" from the cell the shadow of the cell disappears.

#### Live demo with steps to reproduce
https://jsfiddle.net/DimaGorbenko/0cz1Lpkb/2/

#### Product version
The latest version of Highcharts

#### Affected browser(s)
Chrome, Firefox

**Comment by sebastianbochan** [comment]
Hi @dmitrygorbenko,
Thank you for the reporting.

@jon-a-nygaard any comment?

**Comment by jon-a-nygaard** [comment]
@sebastianbochan According to the result from `ColumnSeries.pointAttribs` the `stroke: #7cb5ec` and `stroke-width: 0` which is seen after hover is the correct styling. This also matches what is set as default options passed to the heatmap series.

I am not sure why there is graphic elements with borders when the chart is first rendered. It seems that they are some kind of duplicates that should not be there, and that they are drawn above the correct graphic elements of the points.

A workaround is to explicitly set the `borderColor` and `borderWidth` options: https://jsfiddle.net/jon_a_nygaard/st72c4bj/

**Comment by sebastianbochan** [comment]
@jon-a-nygaard but workaround sets only borders, not keep rules for shadow. After hover, the shadow disappears still.

**Comment by jon-a-nygaard** [comment]
@sebastianbochan Sorry, I somehow missed the `shadow` option and assumed it was `stroke`. Will take another look.
