### ISSUE TITLE
Option series.states.hover.marker.enabled = false ignored in arearange chart

### ISSUE THREAD

**Issue by SimoneMSR** [highcharts/highcharts#8781]
#### Expected behaviour

In an arearange chart When using the series option
```
...
states =  { 
   hover: { 
      marker : {
         enabled: false
      }
   }
};
        
...

```
and hovering the series, no marker should be rendered. 

#### Actual behaviour
Markers are rendered when hovering.

#### Live demo with steps to reproduce
https://jsfiddle.net/simone_msr/tag4spod/
#### Product version
6.1.1

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @SimoneMSR,
Thank you for the reporting.

**Workaround**
Disable the hover state in general.

Demo:
- https://jsfiddle.net/BlackLabel/mvxeLrug/

**Comment by SimoneMSR** [comment]
Hello @sebastianbochan,
thank you for the reply. I already have used that workaround, but the thing is this: in the website that is inspiring there is an arearange which has the hovering enabled but the marker disabled on hover...

**Comment by pawelfus** [comment]
This should be configured by [`series.marker.states.hover`](https://api.highcharts.com/highstock/plotOptions.series.marker.states.hover), demo: https://jsfiddle.net/BlackLabel/tag4spod/7/

According to docs, [`series.states.hover.marker`](https://api.highcharts.com/highstock/series.arearange.states.hover.marker) was used in Highcharts v1..

**Comment by SimoneMSR** [comment]
Thank you @pawelfus! I have used the  series.marker.states.hover option but together with series.states.hover.enabled = false and what I have got was no hover state at all!!! Now everything works

**Comment by pawelfus** [comment]
Thanks for the info! Closing the issue then.
