### ISSUE TITLE
X-Axis labels with useHTML true sometimes compute bogus widths when auto-rotated

### ISSUE THREAD

**Issue by rlm1023** [highcharts/highcharts#8789]
#### Expected behaviour
X-axis labels should only take up as much width as they need. Regardless of the status of auto-rotation and useHTML.

#### Actual behaviour
X-axis labels take up way too much space.

#### Live demo with steps to reproduce
If you play with the window size here:
https://jsfiddle.net/xuca79fr/35/

You can get this to happen:
![screen shot 2018-08-15 at 09 19 23](https://user-images.githubusercontent.com/8899937/44159612-c5c90d80-a06c-11e8-8340-b77c96206a65.png)

#### Product version
Highcharts 6.1.1

#### Affected browser(s)
Reproduced in Chrome and Firefox.

**Comment by sebastianbochan** [comment]
Hi @rlm1023,
Thank you for reporting.
Its a regression since v6.0.5.

Bisect leads to https://github.com/highcharts/highcharts/commit/6bf7ff5
Related topic: https://github.com/highcharts/highcharts/issues/7656

**Comment by TorsteinHonsi** [comment]
Reliable repro with fixed widths: https://jsfiddle.net/highcharts/hqzfat7k/3/
