### ISSUE TITLE
small values & minPointLength - change 0 to null when exporting to csv, causes empty columns

### ISSUE THREAD

**Issue by vitoexe** [highcharts/highcharts#8793]
#### Expected behaviour
Add option that prevent small values being invisible, similar to minPointLength but only when value is greater than 0 

#### Actual behaviour
To display small values common method is combine minPointLength and replacing **zeros** to **null**.
But this is kind of hack, especial when you export data to csv, then you have empty columns instead of 0.

**Comment by pawelfus** [comment]
Hi @vitoexe 

Thanks for sharing your idea. Please vote for this feature on our UserVoice: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/3891296-add-minpointlength-for-close-to-zero-values-but-no
