### ISSUE TITLE
Console errors when zoomed in and using series.setData with redraw set to false

### ISSUE THREAD

**Issue by matdion** [highcharts/highcharts#8795]
#### Expected behaviour
Zooming in on a live updated chart should not trigger console errors on chart hover.
I need to throttle redraws on a chart to prevent it being redrawn on ever serie's setData.
Is this use case supposed to work or there another way to achieve throttling

#### Actual behaviour
When using a deferred chart.redraw instead of a direct redraw on serie.setData hovering the chart when zoomed in will trigger hundreds of console errors.

FF 61.0.2 Error:
`11:35:06.165 TypeError: h.series is null[Learn More] 18 highcharts.js:186:59
	findNearestKDPoint/< https://code.highcharts.com/6.0.0/highcharts.js:186:59
	forEach self-hosted:268:13
	a.each https://code.highcharts.com/6.0.0/highcharts.js:28:236
	findNearestKDPoint https://code.highcharts.com/6.0.0/highcharts.js:185:381
	getHoverData https://code.highcharts.com/6.0.0/highcharts.js:187:240
	runPointActions https://code.highcharts.com/6.0.0/highcharts.js:188:272
	onContainerMouseMove https://code.highcharts.com/6.0.0/highcharts.js:197:204
	setDOMEvents/c.onmousemove https://code.highcharts.com/6.0.0/highcharts.js:199:123
`

Chrome 68.0.3440.106 Error (IE11 has the same):
`highcharts.js:186 Uncaught TypeError: Cannot read property 'group' of null
    at highcharts.js:186
    at Array.forEach (<anonymous>)
    at a.each (highcharts.js:28)
    at a.Pointer.findNearestKDPoint (highcharts.js:185)
    at a.Pointer.getHoverData (highcharts.js:187)
    at a.Pointer.runPointActions (highcharts.js:188)
    at a.Pointer.onContainerMouseMove (highcharts.js:197)
    at HTMLDivElement.c.onmousemove (highcharts.js:199)
    (anonymous) @ highcharts.js:186
    a.each @ highcharts.js:28
    findNearestKDPoint @ highcharts.js:185
    getHoverData @ highcharts.js:187
    runPointActions @ highcharts.js:188
    onContainerMouseMove @ highcharts.js:197
    c.onmousemove @ highcharts.js:199`

#### Live demo with steps to reproduce
Deferred redraw causes console error https://jsfiddle.net/ma_di/Laxsvgbw 
1. To reproduce zoom in close and hover the series.

Direct redraw has no error but kills the cpu usage https://jsfiddle.net/ma_di/81mhcp07/

#### Product version
Highcharts 6.X.X
Highcharts 6.1.X will also cause #8355

#### Affected browser(s)
Chrome
Firefox
IE11

**Comment by sebastianbochan** [comment]
Hi @matdion,
Thank you for reporting. Its a bug.

v6.0.0
![zrzut ekranu 2018-08-17 o 10 06 00](https://user-images.githubusercontent.com/2115686/44255091-31de7980-a205-11e8-8435-23e2fa7c957d.png)


v6.1.1
![zrzut ekranu 2018-08-17 o 10 05 44](https://user-images.githubusercontent.com/2115686/44255111-3c007800-a205-11e8-886e-5d8ad35d5c05.png)

The problem also appears without boost module.
Demo:
- https://jsfiddle.net/BlackLabel/wj4et7c9/

![zrzut ekranu 2018-08-17 o 10 07 38](https://user-images.githubusercontent.com/2115686/44255163-66523580-a205-11e8-89b8-9db078a599d1.png)

The different time in `setInterval` does not have influence on error.

**Comment by KacperMadej** [comment]
There's been a revert that accidentally (so it seems) canceled this fix.
https://github.com/highcharts/highcharts/commit/92dbf4aefd9491b02e9358276e41f366da71e762

The problem is still visible in version 7.1.2, so I will reopen the issue.
It looks like all this was done and lost between versions 6.1.1 and 6.1.2, so we don't have a release with the fix.

As a workaround you could try using the same solution applied to current code, but please note that this solution was not fully tested yet. Demo: https://jsfiddle.net/BlackLabel/wj4et7c9/1/

**Comment by sacrarat** [comment]
Any update on getting this fix incorporated in a release?

**Comment by sebastianbochan** [comment]
Hi @sacrarat,
At this moment we do not have any ETA for fixing this bug.

**Comment by sacrarat** [comment]
Thanks for the quick response @sebastianbochan . For the time being I've used the suggested workaround and it seems to work.
