### ISSUE TITLE
Missing documentation for Point.options

### ISSUE THREAD

**Issue by KevinShiCA** [highcharts/highcharts#8796]
There is an option to attach custom data onto the series which would then be accessible through `Point.options`. There's a sample fiddle using this in the documentation (the "Go to URL" example, there is a `this.options.key` where the context is `Point`): https://api.highcharts.com/highcharts/plotOptions.series.point.events.click

I could not find any official documentation for this property, which would be nice to have.

**Comment by sebastianbochan** [comment]
Hi @KevinShiCA,
Thank you for the suggestion.

**Comment by TorsteinHonsi** [comment]
Closed by 6b6b83a7867509862769903678ee62437c591dbb
