### ISSUE TITLE
Conflict between scrollablePlotArea and responsive tag

### ISSUE THREAD

**Issue by leokury** [highcharts/highcharts#8797]
#### Expected behaviour

With scrollablePlotArea chart should have scroll and we should use responsive tag normally to adapt to mobile devices 

#### Actual behaviour

When we use scrollablePlotArea toghether with responsive tag we can't scroll the chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/w5uohq82/1/

#### Product version
Highchart 6.1.1

#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Hi @leokury 

Thank you for reporting the issue. It looks like initialized chart does not apply scrollable area. After redraw (e.g. window resize) it works fine. Could you confirm? Tested on Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by leokury** [comment]
Yes, after window resize the scroll bar is created but scrollPositionX still does not apply. 

Any workaround for this?

**Comment by TorsteinHonsi** [comment]
_Internal note_
Broken down, it's a problem with calling setSize on a chart with scrollablePlotArea: http://jsfiddle.net/highcharts/w5uohq82/14/. Running reflow makes it even worse.

**Comment by TorsteinHonsi** [comment]
#### Workaround
We can tap into the `endResize` event and make it right.

```js
Highcharts.addEvent(Highcharts.Chart, 'endResize', function () {
	if (this.scrollablePixels) {
    	this.container.style.width = (this.chartWidth + this.scrollablePixels) + 'px';
    }
});
```

Live demo: http://jsfiddle.net/highcharts/w5uohq82/19/
