### ISSUE TITLE
Funnel chart in styled mode is blank if one point label needs to be cropped

### ISSUE THREAD

**Issue by DiegoCardoso** [highcharts/highcharts#8801]
This is a regression introduced in 6.1.0.

I first saw it while using a Funnel chart, but I believe it can also happen to other types as the error is being thrown from `highcharts.js`/`highstock.js`.

#### Expected behaviour
If I have a Funnel chart with labels that are to wide to fit, I expect it to be cropped so it fits in the available area.

#### Actual behaviour
Chart is blank (only title is displayed) and an error `Uncaught TypeError: Cannot read property 'textOverflow' of undefined` is raised in console.

#### Live demo with steps to reproduce
https://jsfiddle.net/7fnbLd85/1/

You can switch to 6.0.7 version to see it working.

#### Product version
Highcharts/Highstock 6.1.0+

#### Affected browser(s)
Tested in Chrome and IE11

**Comment by sebastianbochan** [comment]
Hi @DiegoCardoso,
Thank you for reporting. The issue is already reported here: https://github.com/highcharts/highcharts/issues/8801.

**Comment by DiegoCardoso** [comment]
Hi, you have linked to this very same issue 😅

**Comment by DiegoCardoso** [comment]
Hello, @sebastianbochan 

Could you update your comment to point to the original issue, please? I would like to follow it.

**Comment by sebastianbochan** [comment]
Hi @DiegoCardoso,
Sorry for my bad, I added incorrect reference to the main issue, by accident.

**Comment by DiegoCardoso** [comment]
No probs. Thanks for the update!
