### ISSUE TITLE
Line charts (large datasets) are not rendering with boost enabled in latest Chrome

### ISSUE THREAD

**Issue by zombiehugs** [highcharts/highcharts#8803]
#### Expected behaviour
When rendering large datasets with Boost Module enabled the user should expect increased performance and efficiency.

#### Actual behaviour
When rendering large datasets with Boost Module enabled lines are no longer drawn, the points can still be hovered but are not visible until hover.

#### Live demo with steps to reproduce
https://jsfiddle.net/5bvLgs5w (HighCharts own demo)

The issue has been hard to reproduce locally, we've had complaints from customers (licensed OEM) that recently their lines have stopped rendering, with little luck reproducing we've found success utilizing BrowserStack, Windows 10 + Chrome 68. As far as we are told these users have no issues in other browsers, just latest Chrome release.

It should be noted when using HighStock shrinking the navigator to reduce the number of points displayed will eventually render the lines. 

#### Product version
Highcharts 6.0.5+ 

#### Affected browser(s)
Chrome 68.0.3440.106

Example Screenshot of resulting behavior:
![image](https://user-images.githubusercontent.com/5231398/44273471-386cf100-a205-11e8-876f-48bb76f61e97.png)

**Comment by pawelfus** [comment]
Hi @zombiehugs 

Thank you for reporting the issue. It looks like specific os/hardware + browser causes the issue. For me it works fine:

![screen shot 2018-08-20 at 10 59 46](https://user-images.githubusercontent.com/1453926/44330795-3c4c7d80-a468-11e8-8f26-6267a1f1da82.png)
Chrome:
![screen shot 2018-08-20 at 11 00 08](https://user-images.githubusercontent.com/1453926/44330796-3c4c7d80-a468-11e8-80b9-2ee705f0d358.png)

**Comment by martinste1n** [comment]
I can confirm the issue. 
Chrome Dev-Tools log prints

[.Offscreen-For-WebGL-000001E6666E16B0]RENDER WARNING: Render count or primcount is 0.

**Chrome Version**
Version 68.0.3440.106 (Official Build) (64-Bit)

**OS**
Windows 10

Tried Software & Hardware Rendering.

Firefox & Edge render just fine. Seems to be related to newest Chrome Version.

**Comment by KacperMadej** [comment]
Still can't reproduce. Works fine for me with the same setup:
**Win 10 + Chrome v. 68.0.3440.106 (64-Bit)**

When running console (dev. tools) with verbose (all levels) then there's no error - only console logs for line rendering (and some verbose violations about `requestAnimationFrame` - nothing exiting).

Does it make any sense to dig dipper into hardware configuration @cvasseng ? If yes, then what info will be useful?

**Comment by zombiehugs** [comment]
@martinste1n confirmed working in Edge and Firefox as stated, previous versions and future (69) do not appear to be affected at this time.

@KacperMadej I concur with your findings regarding errors and messaging, no exceptions appear to be thrown. 

Thanks for all the help.

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard Can you confirm this on Windows with Windows 10?

**Comment by cvasseng** [comment]
@zombiehugs what kind of GPU are you running, and which driver version for it are you on?

**Comment by zombiehugs** [comment]
@cvasseng I can find out, it does not occur on my development machine but rather on a customer's machine. Let me get that information and return.

**Comment by zombiehugs** [comment]
@cvasseng These are the drivers in use on customer's laptop that is experiencing the issue. It is a laptop will dual cards. I have screenshots of driver versions below.

![intel](https://user-images.githubusercontent.com/5231398/44601844-6de48200-a7a3-11e8-88d0-7401e809cfcf.png)
![nvidia](https://user-images.githubusercontent.com/5231398/44601845-6de48200-a7a3-11e8-8268-a201d6e7dc19.png)

**Comment by jon-a-nygaard** [comment]
I was unsuccessful to reproduce this issue.

**OS**
Name: Microsoft Windows 10 Pro
Version: 10.0.17134 Build 1734

**Chrome**
Version 68.0.3440.106 (Official Build) (64-bit)

**GPU**
Intel(R) UHD Graphics 620 (22.20.16.4840)
NVIDIA GeForce GTX 1060 (23.21.13.8808)

**Comment by JoostvDoorn** [comment]
Just an FYI that this is not isolated to Windows. I had this issue on Ubuntu, but it has magically gone away. My current chrome version is 68.0.3440.106.

**OS**
Ubuntu 16.04

**GPU**
Quadro M1200/PCIe/SSE2

**Comment by thomasp11** [comment]
I have a Windows 10 VM running under VMWare Fusion on macOS that is also having this issue on on Chrome. This was the page I went to to test this:

https://www.highcharts.com/demo/line-boost

This does work on Edge. [Here](https://github.com/highcharts/highcharts/files/2333245/chrome_gpu.txt) is the report from going to chrome://gpu. [This](https://github.com/highcharts/highcharts/files/2333246/www.highcharts.com-1535565496204.log) is the javascript console from chrome too. If I can collect anything else to help troubleshoot this please let me know!

**Comment by TorsteinHonsi** [comment]
Thanks for the debug info! @cvasseng is out of the office until the middle of next week, he will have a look when he's back.

**Comment by zombiehugs** [comment]
@TorsteinHonsi  @cvasseng @pawelfus Latest stable Chrome (69.0.3497.81) has been released. I have confirmed with customers that after updating their browser the issue with large scale data sets has been alleviated. Obviously issue will exist for those left on Chrome 68 for whatever reason.

Release:
https://chromereleases.googleblog.com/2018/09/stable-channel-update-for-desktop.html

**Comment by jonfreedman** [comment]
Your support team have suggested I may be experiencing this issue, using Chrome Version 66.0.3359.139 (Official Build) (64-bit) boost charts are visible fine when I am physically using my PC but when I connect over Citrix from home they are not rendered in Chrome (IE is fine).

**This is a major issue for us as it makes our applications unusable remotely**

For reference my desktop PC has 2x NVidia NVS 510 graphics cards outputting to 3x Dell  U2718Q monitors (3840 x 2160 resolution) running Windows 7 and I am connected from my home PC which has 1x GTX 1060 graphics card outputting to 2x Dell U2718Q monitors (3840 x 2160 resolution) running Windows 10 connected over Citrix Workspace.

**Comment by cvasseng** [comment]
It looks like 3d acceleration is disabled for Chrome in Citrix by default. You may need to contact your system administrator to sort this out. There's some additional information here: https://virtuallyvisual.wordpress.com/2015/09/21/why-isnt-my-gpu-being-used-with-citrix-xendesktop-or-xenapp/

**Comment by raphaeldovale** [comment]
We have this issue on some machines with win 7 and Chrome 71 (not all)
It works without issues in Firefox.
What other info can I provide to you?

**Comment by KacperMadej** [comment]
fyi: @cvasseng

**Comment by cvasseng** [comment]
@raphaeldovale are you getting any errors in the console? Does other WebGL content work properly?

**Comment by jonfreedman** [comment]
For others the relevant setting in Chrome I had to change to get the charts to render is under Settings -> Advanced -> Use hardware acceleration when available

Counter-intuitively this setting has to be turned off - it's not yet clear to me whether that has an adverse effect over remote desktop.
