### ISSUE TITLE
Broken text in v6 announcement post

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#8805]
https://www.highcharts.com/blog/news/announcing-highcharts-6/

![image](https://user-images.githubusercontent.com/33569/44306072-06aa7600-a33c-11e8-9a24-936cc3e8459e.png)

Another break: "allowing visually

impaired users"

Farther down below: "datavisualization"

**Comment by sebastianbochan** [comment]
Hi @dandv,
Thank you for reporting, we will fix it as soon as possible.

**Comment by mekhatria** [comment]
Fixed :)
