### ISSUE TITLE
Accessibility issue in the JS API Reference site

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#8806]
On the [API docs site](https://api.highcharts.com/highstock/plotOptions), once the `#body` is focused by clicking in the right-side panel, pressing up/down arrow doesn't scroll. It seems that the keyboard focus is split between the search box and the right hand side panel:

* PgDn/PgUp/Space scroll the right side panel (`#body`)
* arrows move in the drop-down below the search box at the top of the sidebar
* other keystrokes are by default ignored
* but after pressing up arrow, other keystrokes (e.g [a-z]) end up in the search box, and after the search-results dropdown triggers, PgUp/PgDn scroll the search results, then the entire sidebar instead after reaching the end of the search results

All in all the keyboard accessibility of the API reference site is a little confusing.

**Comment by sebastianbochan** [comment]
Hi @dandv,
Thank you for reporting.

@jon-a-nygaard @sophiebremer

**Comment by bre1470** [comment]
@oysteinmoseng Do you agree with me, that this has been solved and can be closed?

**Comment by oysteinmoseng** [comment]
@bre1470 Yes, this particular issue looks to be fixed. There are still issues with the keyboard navigation of the API site, but we can handle remaining issues separately.

**Comment by bre1470** [comment]
Okay. I will close the issue. We have to redo the documentation templates for TypeDoc anyway so we can focus on a full accessible navigation there later on.
