### ISSUE TITLE
Broken link in .dateFormat docs

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#8808]
https://api.highcharts.com/class-reference/Highcharts#dateFormat

> Formats a JavaScript date timestamp (milliseconds since Jan 1st 1970) into a human readable date string. The format is a subset of the formats for PHP's strftime">www.php.net/manual/en/function.strftime.php} function.

**Comment by dandv** [comment]
Also, can you please document the "subset of the formats"? `%R` doesn't work, for example.

**Comment by sebastianbochan** [comment]
Hi @dandv,
Thank you for reporting!

**Comment by pawelfus** [comment]
Duplicate of #6737
