### ISSUE TITLE
Broken JS API Reference edit link

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#8811]
At https://api.highcharts.com/highstock/xAxis.ordinal, the edit link points to https://github.com/highcharts/highcharts/blob/c8b1b0ea3/js/supplemental.docs.js#L1473-#L1485

That file [no longer appears to exist in master](https://github.com/highcharts/highcharts/pull/8810).

**Comment by TorsteinHonsi** [comment]
Thanks for reporting,

You're correct, the file has been removed in master, but the link points to the file that the docs were generated from. Maybe the pencil icon is misleading, but the tooltip text simply says "Defined in...".

**Comment by dandv** [comment]
Oh, I thought the pencil icon was to encourage readers to submit documentation PRs, the way [the MongoDB docs](https://docs.mongodb.com/manual/tutorial/getting-started/) do.

**Comment by TorsteinHonsi** [comment]
Yes, that's exactly what it is for. I'm not sure how to handle cases like this though. Although rare, it may happen that the source location of a doclet is changed. We could do a [GitHub code search](https://github.com/highcharts/highcharts/search?q=%40apioption+xAxis.ordinal&unscoped_q=%40apioption+xAxis.ordinal), but all things considered I think the current approach is more precise.
