### ISSUE TITLE
Regression in Highstock navigator when chart inverted. >= Highstock 6.0.5

### ISSUE THREAD

**Issue by vyakymenko** [highcharts/highcharts#8812]
#### Expected behaviour

Correctly working navigator when `inverted: true` configured.
```
...
chart: {
    inverted: true,
    ....
  },
...
```

#### Actual behaviour

Once you configure `inverted: true` and chart is rendered try to drag the selected navigator area to the top or bottom, you will see that at the top and bottom it `setExtremes` to some random data. This issue does not occur on **Highstock 6.0.4**

#### Live demo with steps to reproduce

Demo:
https://codepen.io/valedev/pen/dqbBjv

_Note: You can uncomment version 6.0.4 and this issue will be gone._

#### Product version

**>= Highstock 6.0.5** 

#### Affected browser(s)

All browsers.

**Comment by pawelfus** [comment]
Hi @vyakymenko 

Thank you for reporting this regression!

*Internal note:*
Regression after b75814dd7
