### ISSUE TITLE
Highchart export option not working CSRF token missing issue

### ISSUE THREAD

**Issue by karthiiivgn** [highcharts/highcharts#8815]
Hi ,
I'm developing high-chart. 
When using self server, how to add csrf token when posting the data.
#### Expected behaviour
when clicking the download option i need to post csrf token along with the posted data (for self server)
#### Actual behaviour
due to csrf token missing its shows bad request. But exporting option is working only on exporting server (https://exporting.highcharts.com)

**Comment by karthiiivgn** [comment]
I am using self server.

**Comment by pawelfus** [comment]
Thank you for confirmation @karthiiivgn 

I have reported the issue in exporting server repository: https://github.com/highcharts/node-export-server/issues/164 - this is main library repository.

**Comment by karthiiivgn** [comment]
Still i'm facing Highchart export issue.

**Comment by KacperMadej** [comment]
@karthiiivgn Please continue on the moved issue to avoid duplication: https://github.com/highcharts/node-export-server/issues/164
