### ISSUE TITLE
Candlestick docs: stacking is included in the docs but it's not working.

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#8817]
Check api for candlestick series: [https://api.highcharts.com/highstock/series.candlestick.stacking](https://api.highcharts.com/highstock/series.candlestick.stacking).

When you try to set stacking = "normal" the console shows error **num.toPrecision is not a function** see [https://jsfiddle.net/wchmiel/z4boxtn1/](https://jsfiddle.net/wchmiel/z4boxtn1/). The documentation for candlestick series should be updated.

**Comment by pawelfus** [comment]
*Internal note:*
The fix should update docs **and** prevent errors when `stacking` is set (e.g. changed type with default config etc.).
