### ISSUE TITLE
chart title disappears when useHTML:true and scrollablePlotArea

### ISSUE THREAD

**Issue by SaleemDiab** [highcharts/highcharts#8820]
#### Actual behaviour
when using scrollablePlotArea with chart title.useHTMl = true, title disappears although the element is in the DOM

#### Live demo with steps to reproduce
http://jsfiddle.net/hsa9zwL1/1/

#### Product version
Highcharts v6.1.1 

#### Affected browser(s)
Chrome only tested (v68.0)

**Comment by KacperMadej** [comment]
Hi @SaleemDiab 

Thank you for reporting about the problem.

Here's more detailed description:
With `useHTML: true` some elements are not shown:
- title, 
- subtitle,
- vertical axis title and labels (yAxis for not inverted and xAxis for inverted)

http://jsfiddle.net/BlackLabel/vrq625z4/

Additionally - after resize to init the scrollablePlotArea the problematic elements hide and never go back - even after resize to starting size with the scrollablePlotArea disabled.
