### ISSUE TITLE
Map of Estonia

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#8822]
#### Behaviour
Estonia had Administrative-Territorial Reform, so the map changed:
https://www.rahandusministeerium.ee/en/objectivesactivities/local-governments-and-administrative-territorial-reform/administrative

No source available on current map collection source.

If you have a source for the map that could be used (QGIS map file format and usable license are required), please let us know.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#25
