### ISSUE TITLE
Show checkboxes and usehtml within diagram legend does not work well if scrollablePlotArea is configured

### ISSUE THREAD

**Issue by toh82** [highcharts/highcharts#8824]
#### Expected behaviour
1. Highcharts series checkboxes should stick to the Legend lables on scrollable plot areas
2. HTML formatted legend should also be visible on scrollable plot areas

#### Actual behaviour
If you want to have swipable diagrams on mobile or a specific viewport you can activate chart.scrollablePlotArea https://api.highcharts.com/highcharts/chart.scrollablePlotArea

And if you want to use the checkbox feature plotOptions.series.showCheckbox within the same diagram, it will happen that your checkboxes are not visible or they'll scroll with the diagram on swiping the chart. This happens because they're placed in the highcharts-scrolling div. From my opinion, the checkboxes should be placed within the highcharts-fixed div.

Seems like an Issue in the highcharts lib, but I'm not sure.

In the following, we found another problem: If you want to use HTML for Legend formatting legend.useHTML while having chart.scrollablePlotArea configured. It will happen, that the Legend completely disappear, as soon as the chart turns swipable.

This happens, because the html legend is put into an svg (highcharts-root) wrapper within the highcharts-fixed div. As soon as you pull it out, the legend start to work again.

#### Live demo with steps to reproduce
both issues can be viewed here, make sure to narrow the diagram preview box until scrollbars are visible
http://jsfiddle.net/xfnq0s34/6/

#### Product version
highcharts v6.1.0

#### Affected browser(s)
all

**Comment by toh82** [comment]
Interesting Workaround, Thanks.
The Workaround I used is a bit shorter, I just moved the legend out of the svg with JS ;)

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/xfnq0s34/34/.

Generally, the `useHTML` cases were fixed in another commit earlier today.
