### ISSUE TITLE
Charts not responsive when its container DIV's width changes.

### ISSUE THREAD

**Issue by sharma848** [highcharts/highcharts#8828]
I am using a toggle view for the charts where I can view them in both small view and large view.

But when I switch view and width of the containers changes graphs are not adjusting themselves accordingly.

Please reply as soon as possible.

**Comment by sebastianbochan** [comment]
Hi @sharma848,
I created a simple demo here: https://jsfiddle.net/BlackLabel/vo64g75k/ , which uses responsive. 
For testing, please click on a `update` button and as a result the legend is disabled according to responsive rules. Could you confirm that it works in your environment too?

Could you simplify your demo and update my code with yours? It will allow me to debug your chart.

**Comment by sharma848** [comment]
@sebastianbochan  thanks for the time and help you did. I get it solved by using reflow() whenever the view changes and it solved my problem.

Hence closing this issue.
