### ISSUE TITLE
Data labels of non-visible points appear on the bottom of the plot area after zoom

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#8830]
#### Expected behaviour
Only the labels of the visible points should be shown within the plot area.

#### Actual behaviour
Data labels of the points which are beyond the extremes appear on the bottom of the plot area after the zoom action.

![image](https://user-images.githubusercontent.com/13188589/44514184-b7f43780-a6bf-11e8-8b9e-74493a9bb73e.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/37ypuzec/
Zoom to y axis' categories 1-8.

#### Product version
6.1.1

_INTERNAL NOTE:_
Maybe it's related to: https://github.com/highcharts/highcharts/issues/7815

**Comment by kamilkulig** [comment]
**Workaround:** https://jsfiddle.net/BlackLabel/z0u5pv4e/

**Comment by TorsteinHonsi** [comment]
Removed some noise from demo: https://jsfiddle.net/highcharts/37ypuzec/29/
