### ISSUE TITLE
Vector and wind barb series do not consider borderColor option

### ISSUE THREAD

**Issue by luuuke** [highcharts/highcharts#8831]
#### Expected behaviour

Vector and wind barb series show a border around their pictograms.

#### Actual behaviour

They don't.

#### Live demo with steps to reproduce
wind barb: https://jsfiddle.net/8wyqe2Lr/4/
vector: https://jsfiddle.net/8wh6qrc4/1/

#### Product version
6.0.5

**Comment by pawelfus** [comment]
Hi @luuuke 

Thanks for reporting the issue. It looks like a bug in docs: only `lineWidth` and `color` are supported and options like `borderRadius`, `borderColor` and `borderWidth` are accidentally inherited from parent series. @TorsteinHonsi could you confirm? 

Possible workaround: Duplicate series in the background: https://jsfiddle.net/BlackLabel/8wyqe2Lr/10/

**Comment by luuuke** [comment]
Thanks for the workaround!

Would it be possible to add those options natively? In our case we're overlaying the wind barbs on top of an area chart with the accompanying wind speeds; with a small white border around the barbs it looks much nicer. Something like this, using your workaround: https://jsfiddle.net/8wyqe2Lr/13/. I can imagine the option of having a border for the vector types to be quite useful in not just this specific scenario.

**Comment by pawelfus** [comment]
I agree, that would be nice feature. The problem is paths in SVG don't support border. To support this natively we would need to .. duplicate shape in the background. Just like creating a new series. Of course native solution would be faster than a duplicated series, but for a vector/windbarb series amount of points is relatively small (less than 50k points). 

**Workaround:**
Simple plugin to generate background shapes: https://jsfiddle.net/BlackLabel/rbw13zkh/

```javascript
(function(H) {
  H.wrap(H.seriesTypes.windbarb.prototype, 'drawPoints', function(proceed) {
    var series = this;

    // If borderWidth is set, create background shapes:
    if (series.options.borderWidth > 0) {
      // Temporary store some references:
      H.each(series.points, function(point) {
        point._graphic = point.graphic;
        point.graphic = point.backgroundGraphic;
        point._color = point.color;
        point.color = series.options.borderColor;
      });

      var width = series.options.lineWidth;

      series.options.lineWidth += series.options.borderWidth;
      proceed.apply(series, Array.prototype.slice.call(arguments, 1));

      // Restore references
      H.each(series.points, function(point) {
        point.backgroundGraphic = point.graphic;
        point.graphic = point._graphic;
        point.color = point._color;
        delete point._graphic;
        delete point._color;
      });

      series.options.lineWidth = width;
    }
    // Now render original shapes:
    proceed.apply(series, Array.prototype.slice.call(arguments, 1));

  });
})(Highcharts);
```

**Comment by luuuke** [comment]
I was hoping that SVG would support borders, too bad. 
Thanks for the workaround though, looks great! As we are using Highstock, the only issue is now, that the background shapes stay when navigating to some other point in time.

**Comment by pawelfus** [comment]
Could you update my demo to recreate the issue? Simple demo looks fine: https://jsfiddle.net/BlackLabel/yu4sx8fh/

**Comment by luuuke** [comment]
What I've forgot to note, we're using async loading and thus update data on switching times. This recreates the issue: https://jsfiddle.net/yu4sx8fh/7/.

**Comment by pawelfus** [comment]
Ah, thanks! Updated demo: https://jsfiddle.net/BlackLabel/cbyjw0z2/

And plugin:

    (function(H) {
      H.wrap(H.seriesTypes.windbarb.prototype.pointClass.prototype, 'destroyElements', function(proceed) {
        if (this.backgroundGraphic) {
          this.backgroundGraphic = this.backgroundGraphic.destroy();
        }

        proceed.apply(this, Array.prototype.slice.call(arguments, 1));
      });

      H.wrap(H.seriesTypes.windbarb.prototype, 'drawPoints', function(proceed) {
        var series = this;

        // If borderWidth is set, create background shapes:
        if (series.options.borderWidth > 0) {
          // Temporary store some references:
          H.each(series.points, function(point) {
            point._graphic = point.graphic;
            point.graphic = point.backgroundGraphic;
            point._color = point.color;
            point.color = series.options.borderColor;
          });

          var width = series.options.lineWidth;

          series.options.lineWidth += series.options.borderWidth;
          proceed.apply(series, Array.prototype.slice.call(arguments, 1));

          // Restore references
          H.each(series.points, function(point) {
            point.backgroundGraphic = point.graphic;
            point.graphic = point._graphic;
            point.color = point._color;
            delete point._graphic;
            delete point._color;
          });

          series.options.lineWidth = width;
        }
        // Now render original shapes:
        proceed.apply(series, Array.prototype.slice.call(arguments, 1));

      });
    })(Highcharts);

**Comment by luuuke** [comment]
Works great, thank you!
