### ISSUE TITLE
Support point.select in Gantt

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#8841]
We need to support `point.select`/ `series.allowPointSelect` in Gantt, even with the draggable-gantt module loaded.

We want to be able to group points to select, but this does not have to be core logic.

We need to be able to get the selected point in the chart programmatically.

**Comment by TorsteinHonsi** [comment]
The select state and `allowPointSelect` work, and the appropriate class name is given. However the visual attributes are not correctly set, as they are applied to `point.graphic` from `Point.setState`. For gantt series, `point.graphic` is a group element, and the path is nested inside. We need to redirect `.attr` from the group element to the appropriate child.

Interestingly, the select state visuals work with the xrange demo.
