### ISSUE TITLE
MACD crashes when not enough points in graph to generate plot

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#8847]
#### Behaviour
Look like current check doesn't include signal line plot check.
` signalLine = EMA.prototype.getValues(...` returns false and code later fails when trying to access `if (MACD[i][0] >= signalLine[0][0]) {`

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/5gsmy12w/

Steps:
0. it just fails on build
1. run with dev tools to debug the error

@pawelfus I saw your last edition around similar issue in MACD - could you take a look?

**Comment by pawelfus** [comment]
**Workaround:**
Demo: http://jsfiddle.net/BlackLabel/8mfz62y9/

Snippet:
```javascript
(function(H) {
  H.wrap(H.seriesTypes.macd.prototype, 'getValues', function(proceed, series, params) {
    if (series.xData.length < params.longPeriod + params.signalPeriod) {
      return false;
    } else {
      return proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    }
  });
})(Highcharts);
```
