### ISSUE TITLE
MACD unable to remove when no plot

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#8848]
#### Behaviour
No plot due to not enough data in base series. On the MACD remove - error.
`this.graphmacd = this.graphmacd.destroy();`

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/5gsmy12w/1/

Steps:
1. click destroy
2. error in browser console

_Internal note:_ Might be related to #8847

**Comment by pawelfus** [comment]
**Workaround:**
Overwrite `destroy()` for MACD, demo: http://jsfiddle.net/BlackLabel/u128rx05/

Snippet:

```javascript
(function(H) {
  H.seriesTypes.macd.prototype.destroy = function() {
    // this.graph is null due to removing two times the same SVG element
    this.graph = null;
    this.graphmacd = this.graphmacd && this.graphmacd.destroy();
    this.graphsignal = this.graphsignal && this.graphsignal.destroy();

    H.seriesTypes.sma.prototype.destroy.apply(this, arguments);
  };
})(Highcharts);
```
