### ISSUE TITLE
support assign a percentage to series.pie.dataLabels.distance property

### ISSUE THREAD

**Issue by DongShi** [highcharts/highcharts#8854]
#### Expected behavior
With a percentage, we can denote how far away the data labels should be placed in related to the radius length.

#### Actual behaviour

See document(https://api.highcharts.com/highcharts/series.pie.dataLabels.distance):
distance: NumberSince 2.1
The distance of the data label from the pie's edge. Negative numbers put the data label on top of the pie slices. Connectors are only shown for data labels outside the pie.

Defaults to 30

Currently it is not straight forward to put data labels in related to the radius length in pie chart, like say, put the labels at the center of the radius ? or put the labels outside the pie, the label is 1.5 times radius length away from the pie center...

Since the chart size can be changed (via resize, etc), we have to draw the pie first, get the chart radius, calculate the distance in number, and update this property afterwards. Why not make this supported internally with a percentage value?

So you can draw the pie with something like 
 plotOptions: {
        pie: {
            dataLabels: {
                distance: 50%
            }
        }
    },

With this, the labels will always be at the middle point of the radius, no matter how the pie chart is resized....

**Comment by pawelfus** [comment]
Hi @DongShi 

Thank you for your suggestion! Actually it's already reported on our UserVoice: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/3072785-pie-label-distance-as-percentage-of-pie-size - please vote for this feature
