### ISSUE TITLE
Boost module support mappoint? 

### ISSUE THREAD

**Issue by neewbee** [highcharts/highcharts#8855]
![image](https://user-images.githubusercontent.com/13777940/44774308-66f3b000-aba5-11e8-8aa7-cd2564a0b8f7.png)

there are approximately 50,0000 mappoints in this map, and the render process is very slow.

according to the doc

> Boost is a stripped-down renderer-in-a-module for Highcharts and Highstock. It bypasses some of the standard Highcharts features (such as animation), and focuses on pushing as many points as possible as quickly as possible.

It seems that there is no way to render mappoints using canvas, or am I missing something?

**Comment by pawelfus** [comment]
Hi @neewbee 

As you pointed out, Boost module is a module for Highcharts and Highstock, not Highmaps. It is already requested on our UserVoice: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/34799527-boost-module-for-mappoint - please vote for this feature.
