### ISSUE TITLE
Highcharts flickers when hover event occurs over the chart or a click event next to it

### ISSUE THREAD

**Issue by Memija** [highcharts/highcharts#8856]
#### Expected behaviour

When clicking on a element next to the Highchart or hovering over Highchart elements the graph should be drawn correctly. The Bug does not occurs on Chrome or IE browsers.

#### Actual behaviour

Highcharts graph is broken when either clicking on the element next to it or when a hover event is performed over random elements of the chart itself. Once the graph is broken then either window resizing, scrolling or adding element will make the graph fix itself.

#### Product version

Highcharts 6.1.0

#### Affected browser(s)

Firefox

**Comment by KacperMadej** [comment]
Hi @Memija 

Unable to recreate - please add a demo and describe precise steps required to recreate the problem.

**Comment by Memija** [comment]
I am unable to create JSFiddle that will have a bug present. The graph where the bug is present is part of the React application and the graph itself gets disturbed on any hover or click event. I am attaching the image of the bug. The issue is not present on Chrome or IE browser, only in Firefox, and any resizing of the window or just scrolling makes the graph correct it self.

![image](https://user-images.githubusercontent.com/8274921/44899346-c49d0f00-ad01-11e8-81b9-29e158ca4138.png)

**Comment by KacperMadej** [comment]
If we cannot the problem and there's no demo for us to work with, then I think I can only advise you to debug the problem yourself - use highcharts.src.js instead highcharts.js to work with readable code, and remove all code step by step until you will work with minimal demo and when you find the source then please let us know.

**Comment by Memija** [comment]
That could not work as the graph would fix itself as soon as any break point would be hit. The graph would only flicker while the hover or click event is being performed. All this being said I have managed to solve the issue by setting position of the graph parent div to sticky. After that change the bug is no longer present. Thank you for the help.

**Comment by KacperMadej** [comment]
Thank you for sharing your solution @Memija
