### ISSUE TITLE
Highcharts Waterfall low value for yAxis point

### ISSUE THREAD

**Issue by pgusic** [highcharts/highcharts#8857]
#### Expected behaviour

Waterfall chart should start at "low" value (series.data.low), the point should not start at bottom of the chart.

#### Actual behaviour

While testing Highcharts v6.0.7 I found that Waterfall chart yAxis point does not accept "low" value anymore. The same option in the Column chart works and the point does not start at the bottom but at the "low" value.

I tried it with an older version (4.2.3) and it works. https://codepen.io/pgusic/pen/MqjGeb

#### Product version
https://codepen.io/pgusic/pen/xaEjEY

**Comment by Denyllon** [comment]
If something _worked_ on specific version and wasn't documented at all (I checked the documentation of v4.2.3), then we can assume that was some type of undesirable behaviour. I see that `waterfall` series inherits from `column` series, on which the low parameter still works as you described, but it also doesn't occurs in documentation.

If you would like to get similar effect, please try to use series.threshold parameter, but in my opinion both of ways breaks the logic of the chart a bit.

```js
series: [{
    threshold: 100000,
    data: [{
        y: 120000,
    }, {
        y: 569000,
    }, {
        y: 231000
    }, {
        isIntermediateSum: true,
        color: Highcharts.getOptions().colors[1]
    }, {
        y: -342000
    }, {
        y: -233000
    }, {
        isSum: true,
}]
```
**Live example:** https://jsfiddle.net/nxwy48uj/

**API Reference:** https://api.highcharts.com/highcharts/series.waterfall.threshold
