### ISSUE TITLE
Halo on pie charts is not shown when defined through series

### ISSUE THREAD

**Issue by ejubkadric94** [highcharts/highcharts#8861]
I wanted to make halo different for each slice of pie chart, but that is currently not possible. It is only possible to define halo through plotOptions, but then the halo is the same for all pie slices.

#### Expected behaviour
Halo should behave as specified for each data point of series.

#### Actual behaviour
Chart keeps default halo, despite the fact that different halo is specified for each data point. (As it is described in documentation: https://api.highcharts.com/highcharts/series.pie.states.hover.halo )

#### Live demo with steps to reproduce
When defined through series (does not work): 
http://jsfiddle.net/6zbf90cj/5/

When defined through plotOptions (works):
http://jsfiddle.net/n7fu8zkb/2/

#### Product version
Latest highcharts version

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @ejubkadric94 

Thank your for reporting the issue. You are right, halo can be defined on **series** level, not **point** level. Defining in series object works fine: http://jsfiddle.net/BlackLabel/n7fu8zkb/5/

Please, create an idea on our [UserVoice](https://github.com/highcharts/highcharts) and vote for it. Thanks!

**Comment by pawelfus** [comment]
## Workaround:
Manually apply states for halo after point state's changed: 

### Demo: 
http://jsfiddle.net/BlackLabel/g0asqnhy/

### Snippet:
```javascript
Highcharts.addEvent(Highcharts.Point, 'afterSetState', function() {
  var state = this.state;

  if (
    this.series.halo &&
    this.states[state] &&
    this.states[state].halo &&
    this.states[state].halo.attributes
  ) {
    this.series.halo.animate(this.states[state].halo.attributes);
  }
});
```

**Comment by ejubkadric94** [comment]
Hello @pawelfus 
Thank you for replying. You are right, in documentation it is stated that it can only be set on **series** level. BUT, there are some other properties which are also supposed to work only on series level, but they also work on **point** level.
For example `series.pie.states.hover.borderColor` and `series.pie.states.hover.borderWidth` (Those are same in column charts, and on other chart types as well).
In documentation, they are described in the same way as Halo (`series.pie.states.hover.halo`), and yet they can be set on point level. Therefore, I was thinking that the Halo will behave in the same manner.

You can see the borderWidth example in the fiddle I attached in issue live demo.

Thanks for the workaround, I will give it a try.

**Comment by pawelfus** [comment]
Thank you for pointing this out! It looks like a bug in our docs, for example: https://api.highcharts.com/highcharts/series.pie.data should describe `states` with list of available options or at least reference `states` with limitations.
