### ISSUE TITLE
yAxis updated when scrollablePlotArea is active

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#8862]
#### Expected behaviour
Updating yAxis/xAxis should overlay scrollable box like on init.

#### Actual behaviour
Updating yAxis/xAxis doesn't overlay scrollable box like on init.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/jfco1L8z/

Steps:
- click on "update" button
- observer yAxis labels hidden below the overlay box

#### Product version
n/a

#### Affected browser(s)
n/a

**Comment by ajhaupt7** [comment]
Has there been any progress on this issue? I am having the same problem

**Comment by ajhaupt7** [comment]
thanks @KacperMadej!

**Comment by jlpstolwijk** [comment]
Same issue here. [CodePen](https://codepen.io/jlpstolwijk/pen/KJVwQz.). 

2 additional points perhaps worth noting:
1. When yAxis is not defined in options, the yaxis does not get hidden, but another issue occurs: chart is resized but series is not redrawn. [CodePen](https://codepen.io/jlpstolwijk/pen/RvrrNy)
2. When one of the series is hidden by clicking on legend, resizing works fine! See same codepen as previous point.

**Comment by FilipeCosta06** [comment]
_Sorry for the somewhat unnecessary comment_

Thanks @KacperMadej ! 

Why isn't this "officially" fixed already ? I'm calling the `workaround` in the redraw event and it completely solves my issue too (using GanttChart). Is this not a "clean" solution (performance-wise maybe) ? Anyway, thanks again.

**Comment by KacperMadej** [comment]
@FilipeCosta06 
Thank you for the comment.

Probably the problem was not so important - we didn't got much reports for it, and the workaround helps enough for now. Another problem was that I forgot to add @TorsteinHonsi in the internal note in my last comment 😃

**Comment by jareware** [comment]
FWIW, implementing the workaround isn't all that straightforward when using via `highcharts-react-official`, because the `chart` reference isn't exposed outside the wrapper. So an "official" fix would still be much appreciated!

Looks like I'll need to fork `highcharts-react-official` for the time being.

**Comment by ppotaczek** [comment]
Hi @jareware,

You can get the `chart` reference as described here: https://github.com/highcharts/highcharts-react#how-to-get-a-chart-instance

**Comment by jareware** [comment]
Thanks for the quick response and the link, didn't realize refs could be used for that, neat!

Still has the nagging issue of determining when the `options` changed, so you know when to call `workaround()`, but that's definitely doable.

I did however run into the same problem as https://github.com/highcharts/highcharts-angular/issues/137 with the workaround, so as a word of warning to anyone else wandering here and copy-pasting the workaround code, **it will throw when invoked on a chart that doesn't use `scrollablePlotArea`**.

A quick `if (!chart.options.chart.scrollablePlotArea) return;` at the top might be a good addition. Until the official fix lands, that is. :wink:

**Comment by Bakerburgh** [comment]
Interestingly, I have found that simply updating the chart with empty yAxis options can fix this issue:
http://jsfiddle.net/92wfscux/2/

`
function otherWorkaround() {
  chart.update({yAxis: []});
}`

**Comment by Hari-edit** [comment]
This [solution](https://jsfiddle.net/BlackLabel/jfco1L8z/2/) is not working for me in angular-highcharts.

After updating the chart Y axis is not fixed.
https://stackblitz.com/edit/highcharts-angular-basic-line-zrcjqv.

Anything I am doing wrong?

**Comment by jsyvino** [comment]
for what it is worth I am also having this issue with highcharts-react-official, would love a bugfix there too!
