### ISSUE TITLE
Not able to show series only in navigator

### ISSUE THREAD

**Issue by Abrissirba** [highcharts/highcharts#8863]
#### Expected behaviour
Being able to show multiple series in navigator and without showing them in the normal chart area.

#### Actual behaviour
This worked before https://github.com/highcharts/highcharts/pull/8453 by setting showInNavigator = true and visible = false. 

#### Live demo with steps to reproduce
https://jsfiddle.net/je5zro78/24/
switch between 6.1.0 and 6.1.1 and click on addnavigatorseries. In 6.1.0 the serie is visible in the navigator and not in 6.1.1

#### Product version
6.1.0

**Comment by pawelfus** [comment]
Hi @Abrissirba 

Thank you for reporting this issue. This is expected behaviour: `visible` option should be inherited from base series. If you want to show series only in navigator, please set `series.navigatorOptions.visible = true`, demo: https://jsfiddle.net/BlackLabel/je5zro78/27/
