### ISSUE TITLE
Unable to set connectorColor on point level

### ISSUE THREAD

**Issue by ejubkadric94** [highcharts/highcharts#8864]
I need to set the connectorColor to be different for different pie slices. Currently it seems that it is only possible to set it on series level, and if done so, all points will have the same color of connector line. 
Is there some workaround for this, to make it work on **point(slice)** level?
Thanks

#### Live demo with steps to reproduce
http://jsfiddle.net/9k0endv5/

#### Product version
6.1.1

**Comment by KacperMadej** [comment]
Hi @ejubkadric94 

Thank you for reporting about the enhancement idea - next time please use userVoice to suggest new ideas or features. The most popular ideas are getting implemented. https://highcharts.uservoice.com/forums/55896-general

#### As a workaround:
use the code in the demo below:
http://jsfiddle.net/BlackLabel/31shq4k8/

In short - changed connector stroke to:
```js
              connector.attr({
                'stroke-width': connectorWidth,
                'stroke': (
                	point.options.dataLabels && point.options.dataLabels.connectorColor ||
                  options.connectorColor ||
                  point.color ||
                  '#666666'
                )
              });
```

**Comment by KacperMadej** [comment]
Let's keep this open until it's implemented or reported on userVoice
