### ISSUE TITLE
Label automatic rotation fail if step is set

### ISSUE THREAD

**Issue by AmmyXu** [highcharts/highcharts#8868]
#### Expected behaviour
Labels rotate automatically when they overlap horizontally

#### Actual behaviour
If step is not set, the label can be automatically rotated. Otherwise, the rotation will fail.

#### Live demo with steps to reproduce
http://jsfiddle.net/ammyxu/568ec9rv/16/

**without Setp**
![image](https://user-images.githubusercontent.com/29430746/44896560-33429280-ad2b-11e8-9082-27cc18ec45e0.png)

**with Step**
![image](https://user-images.githubusercontent.com/29430746/44896545-258d0d00-ad2b-11e8-8829-b6f12f894e27.png)

#### Product version

The latest

#### Affected browser(s)
chrome

**Comment by pawelfus** [comment]
Hi @AmmyXu 

Isn't that a direct duplicate of #8632 ? Exactly the same issue: setting step causes overlapping (https://github.com/highcharts/highcharts/issues/8632#issuecomment-405503476).

**Comment by AmmyXu** [comment]
it is a new problem

**Comment by KacperMadej** [comment]
@AmmyXu Please describe the difference, so we could avoid closing this issue as a duplicate.

**Comment by AmmyXu** [comment]
Sorry, I may not have described it clearly, so that you can not understand.
The problem of #8632 is how to automatically rotate labels when they are long.
The problem of this issue is that when the step attribute is set, the solution given in #8632 fails and the labels are always placed horizontally rather than rotated automatically.

**Comment by KacperMadej** [comment]
Thank you for the clarification @AmmyXu
