### ISSUE TITLE
Unable to display dynamic data in IE8

### ISSUE THREAD

**Issue by chen365409389** [highcharts/highcharts#8874]
#### Expected behaviour
display dynamic data in IE8
#### Actual behaviour
unable to display dynamic data in IE8
#### Live demo with steps to reproduce
I get the archive from official website,in examples\dynamic-update , I import the oldie.js after highcharts.js,but still cann't display dynamic data in IE8.
I noticed that if i invoke addPoint method like "series.addPoint([x, y], true, true);",charts will not be updated,but if i set the third parameter (shift) to false,charts will be updated,but the first point will not be removed.
Thanks！
#### Product version

Highcharts-6.1.1
#### Affected browser(s)
IE6,IE8

**Comment by chen365409389** [comment]
yes,it works fine in Chrome and IE9, but got issue in old IE browsers(IE6,IE8).
I open the official demo url in IE9, it tips need add oldie.js , so I download the latest archive from https://code.highcharts.com/zips/Highcharts-6.1.2.zip , and got the same issue
Thanks

**Comment by pawelfus** [comment]
@KacperMadej - could you take a look?

**Comment by KacperMadej** [comment]
It's a bug in `H.indexOfPolyfill` in `oldie`. The function there is wrongly called or just not as it should be.

### As a workaround:

use this code after loading `oldie` and before creating any charts:
```js
Highcharts.indexOfPolyfill = function (member, fromIndex) {
    var arr = this,
        len,
        i = fromIndex || 0;

    if (arr) {
        len = arr.length;

        for (; i < len; i++) {
            if (arr[i] === member) {
                return i;
            }
        }
    }

    return -1;
};
```

_Internal note:_
Resolve this with #8346 too

**Comment by chen365409389** [comment]
It's all good,I use the code in my chart and it works fine,Thanks for your effort!
