### ISSUE TITLE
Missing Sankey diagram legend

### ISSUE THREAD

**Issue by nosto-mikpou** [highcharts/highcharts#8879]
#### Expected behaviour
Sankey diagram: adding ```legend: {enabled: true}``` legend to the default position of the chart. Note: This is the default value for legend

#### Actual behaviour
The legend is not visible or contains anything
![screen shot 2018-09-04 at 10 45 49](https://user-images.githubusercontent.com/12759991/45017233-c3385300-b02f-11e8-91e6-3a90bf3a9bb7.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/oepjasdh/

#### Product version
Highcharts 6.1.0

#### Affected browser(s)
Chrome

Is the legend supported in Sankey diagram?

**Comment by pawelfus** [comment]
Hi @nosto-mikpou 

Thanks for reporting the issue. In sankey diagram, you need to enable `series.showInLegend` option: https://jsfiddle.net/BlackLabel/oepjasdh/2/

Docs: https://api.highcharts.com/highcharts/series.sankey.showInLegend
