### ISSUE TITLE
Y Axis Title Break Lines Not Spacing Correctly

### ISSUE THREAD

**Issue by nsidawy** [highcharts/highcharts#888]
If a y-axis title is created with break lines space is added to the left side of the chart to accommodate the multi-line title but the top (or in this case the left) of the title is still appearing adjacent to the y-axis rather than hugging the right side of chart and using the extra space.

See: http://jsfiddle.net/QWe5n/

This seems like it would be a straightforward fix.

**Comment by oysteinmoseng** [comment]
Seems to be working as expected now
