### ISSUE TITLE
Gantt: Constant cell size in datetime GridAxis

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#8882]
#### Expected behaviour
Some users seem to expect a constant cell size from the GridAxis.

#### Actual behaviour
We now (by default) crop to data min.

#### Live demo with steps to reproduce
https://jsfiddle.net/2shmed8z/6/ - The first Monday has a squished box.

#### Product version
Highcharts Gantt Alpha

**Comment by TorsteinHonsi** [comment]
I half expected that `xAxis.startOnTick` would make a difference here, but it doesn't. First step in fixing this would be to find out why so.
