### ISSUE TITLE
Lineargauge tooltip issue

### ISSUE THREAD

**Issue by nithyavanig** [highcharts/highcharts#8883]
#### Expected behaviour
When datalabels are not enabled, tooltip should be shown.

#### Actual behaviour
When datalabels are set to false, tooltip does not work in linear gauge .

#### Live demo with steps to reproduce

https://jsfiddle.net/nithivani86/ny0btsv2/3/

#### Product version

Highcharts  v6.1.1
#### Affected browser(s)
chrome

**Comment by pawelfus** [comment]
Hi @nithyavanig 

Linear gauge series is not officially supported (see #6847). Please use bullet series instead, demo for you: https://jsfiddle.net/BlackLabel/ny0btsv2/8/
