### ISSUE TITLE
Tooltip remains after mouseleave on synchronized charts

### ISSUE THREAD

**Issue by tdornele** [highcharts/highcharts#8886]
#### Expected behaviour
Tooltip should only be shown when the graph is being hovered over, on mouseleave it should fade out, the same as a non-synchronized chart.

#### Actual behaviour
Tooltip is not initially drawn, but once it is drawn on hover, it remains there unless you refresh the page.

An alternative solution would be using tooltip.hide(), however this only hides the tooltip itself, it doesn't unselect the point.

#### Product version
Version 6.0.7

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/synchronized-charts/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @tdornele 

Thank you for reporting the issue. This is expected behaviour from lines:
```javascript
/**
 * Override the reset function, we don't need to hide the tooltips and
 * crosshairs.
 */
Highcharts.Pointer.prototype.reset = function () {
    return undefined;
};
```

Instead of preventing this, we can hide all tooltips:
```javascript

/**
 * Hide tooltip and crosshair on container mouseleave:
 */
$('#container').bind('mouseleave', function(e) {
  Highcharts.each(Highcharts.charts, function(chart) {
    if (chart) {
      chart.pointer.reset();
    }
  });
});
```

Demo: https://jsfiddle.net/BlackLabel/vrcp59ds/
