### ISSUE TITLE
No way to completely disable HTML parsing from chart labels

### ISSUE THREAD

**Issue by mgol** [highcharts/highcharts#8892]
#### Expected behaviour

There should be a way to completely disable HTML parsing from chart labels.

#### Actual behaviour

Even with `useHTML: false` basic HTML is still allowed. It's not possible to disable that.

#### Live demo with steps to reproduce

https://jsfiddle.net/g2xc3ow5/9/

#### Product version

Latest Highcharts

#### Affected browser(s)

All

#### Other remarks

Sometimes, as a way to test for XSS issues reflecting any user-provided HTML anywhere is forbidden by QA. Achieving that with Highcharts is currently cumbersome and relies on manual escaping or stripping problematic characters, which is easy to do incorrectly.

**Comment by TorsteinHonsi** [comment]
We can override the `buildText` function to insert raw unhandled strings into the `text` elements: https://jsfiddle.net/highcharts/g2xc3ow5/18/

**Comment by mgol** [comment]
Is this an official API? I don't want to rely on something theoretically not supported as it may change between releases and then I'll have the issue back.

Ideally, there would be an option to skip this handling completely.

**Comment by mgol** [comment]
Also, the fact that `Highcharts.SVGRenderer#buildText` is called after the element has already been constructed means there's still a potential attack vector here.

**Comment by TorsteinHonsi** [comment]
> Is this an official API?

No, but it's a snippet that will work with newer releases.

> Also, the fact that Highcharts.SVGRenderer#buildText is called after the element has already been constructed means there's still a potential attack vector here.

It runs after the `text` element has been generated, but before text content is applied to it. We must necessarily create the element before we add content to it.

**Comment by pawelfus** [comment]
Alternative solution:  translate tags to entity-based strings before passing it to Highcharts: https://jsfiddle.net/BlackLabel/g2xc3ow5/11/

**Comment by kssmith** [comment]
I'm also having this issue and an entity-based string does not work if it was converted using HTML5 encoding.
For example:
```php
$string = '<b>test</b>';
echo htmlentities($string, ENT_QUOTES | ENT_HTML5, 'UTF-8');
// &lt;b&gt;test&lt;&sol;b&gt;
```
When the legend is provided `&lt;b&gt;test&lt;&sol;b&gt;`
it renders as `<b>test<&sol;b>`
rather than the expected `<b>test</b>`

https://jsfiddle.net/06hc5wvx/

**Comment by pawelfus** [comment]
Hi @kssmith 

Please add additional entities to the [`Highcharts.Renderer.prototype.escapes`](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer.html#escapes) object. Demo: https://jsfiddle.net/BlackLabel/p0dcmkbf/

Snippet:
```javascript
Highcharts.Renderer.prototype.escapes['/'] = '&sol;';
```
