### ISSUE TITLE
almond.js fails on no module name with v6.1.2; v6.1.1 is OK

### ISSUE THREAD

**Issue by aaron-sua** [highcharts/highcharts#8896]
#### Expected behaviour
almond.js can find the module name

#### Actual behaviour
incorrect module build, no module name

#### Live demo with steps to reproduce
no live demo.  used in JIRA Universal Gadget to hit this error

#### Product version
Highcharts 6.1.2

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

@jon-a-nygaard , @oysteinmoseng I suspect it may have something to do with https://github.com/highcharts/highcharts-assembler/commit/0d223359731079077a5a6ad693b53655e8352fc2?

**Comment by oysteinmoseng** [comment]
Most likely same issue as #8890.

@aaron-sua I am not familiar with almond.js, but with `6.1.2` and the new AMD support, there is an initialization step required for Highcharts modules (exporting, data module etc). Is there any way to add this step? You might also need to reconfigure almond.js somehow to account for the fact that Highcharts files are now AMD modules.

**Comment by aaron-sua** [comment]
It is the same issue. This is a plug-in for jira and as such I can't opt to
initialize in this new manner.  I'll simply stick to 6.1.1

**Comment by oysteinmoseng** [comment]
If you are able to host the files yourself you can also modify them to remove the AMD loading. At the top of the files you will find 

```javascript 
	} else if (typeof define === 'function' && define.amd) {
		define(function () {
			return factory(root);
		});
```
for highcharts.js and other main files. For the module files you will find

```javascript
	} else if (typeof define === 'function' && define.amd) {
		define(function () {
			return factory;
		});
```

Simply removing this part will disable AMD support for the files, and loading will function as it did in `6.1.1`.

I am closing the issue for now, as there does not seem to be a clear way for us to do anything about this, but feel free to reopen if you have more information.
