### ISSUE TITLE
Column 3D series with visible=false on init cause rendering bugs

### ISSUE THREAD

**Issue by Vovan-VE** [highcharts/highcharts#8897]
#### Expected behaviour

Correct rendering when toggling series visible.

#### Actual behaviour

Incorrect rendering depending on initial visible states.

#### Live demo with steps to reproduce

1. http://jsfiddle.net/p2cxt8Lz/6/

    First `visible=true`, second `visible=false`. Click `Series 2` twice to show and hide it. Here comes rendering bugs.

2. http://jsfiddle.net/p2cxt8Lz/8/

   First `visible=false`, second `visible=true`. Just nothing rendered on init in addition to same bugs as above.

#### Product version

Highcharts 6.1.2

#### Affected browser(s)

Chrome, FireFox, Opera, something else may be.

**Comment by KacperMadej** [comment]
Hi @Vovan-VE 

Thank you for reporting about the problem.

### As a workaround:
toggle series visibility on init instead of using options, demo: 
http://jsfiddle.net/BlackLabel/75394o0d/
