### ISSUE TITLE
Solid gauge chart : Tooltip and series data label intersect

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#8900]
#### Expected behaviour
Tooltip should be rendered above series data label.

#### Actual behaviour
Tooltip and series data label intersect.

#### Live demo with steps to reproduce
https://jsfiddle.net/amrutaJgtp/tq34x29e/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @amruta30 

This is expected behaviour: dataLabel is rendered as HTML, tooltip as SVG. SVG is always rendered below HTML elements, from [docs](https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting):

> Most places where text is handled in Highcharts, it is also followed by an option called useHTML. When this is true, the text is laid out as HTML on top of the chart. This allows for full HTML support and can be a good idea if you want to add images in your labels, tables in your tooltip etc. The downsides are that
>
> - it will always be laid out on top of all other SVG content, and
> - that it is not rendered the same way in exported charts, unless you use the experimental exporting.allowHTML option.

**Comment by amruta30** [comment]
Thanks. I will try the solution.

**Comment by TorsteinHonsi** [comment]
A new and better workaround (since Highcharts v6.1.2) is to set `tooltip.outside` to true: https://jsfiddle.net/highcharts/tq34x29e/1/
