### ISSUE TITLE
Bubble chart wrong X axis maximum calculated when min is set

### ISSUE THREAD

**Issue by ivanmjartan** [highcharts/highcharts#8901]
Hi there we have problem in our Bubble chart. 

We have several series in bubble chart. 

3 of them have X value [40542, 40907,41270] (3 bubbles) others are empty. 

When we set min value of x axis to 40805 result graph is empty 

#### Expected behaviour

there will be one bubble with value  41270

#### Actual behaviour

Graph is empty 

#### Live demo with steps to reproduce
https://jsfiddle.net/9j07b3ym/

Try to remove "min": 40805 in x axis definition 

#### Product version
We are using 4.2.5

Test repro version current

**Comment by pawelfus** [comment]
Hi @ivanmjartan 

Thank you for reporting this bug. It looks like setting `max` resolves the issue too: https://jsfiddle.net/BlackLabel/9n0sjrae/ 

Simplified demo: https://jsfiddle.net/BlackLabel/9n0sjrae/4/

*Internal note:*
For some reason, `xAxis.max` is miscalculated: 

```javascript
< Highcharts.charts[0].xAxis[0].getExtremes();
> {
>   dataMax: 41013,
>   dataMin: 40542,
>   max: 40975.42787658802,
>   min: 40805,
>  userMax: undefined,
>   userMin: undefined
> }
```

Simple modification here:
https://github.com/highcharts/highcharts/blob/c6850f1c3c95ebc47b6ee8a7231b7c6bedaa510a/js/parts-more/BubbleSeries.js#L553

From `pxMin - pxMax` to `Math.abs(pxMin - pxMax)` looks better, but bubble is still cut off.
