### ISSUE TITLE
Pie 3D - tooltip not rendered when hovering edge of the slice

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#8906]
#### Expected behaviour
Hover on slice edge should show tooltip and fire all connected events (e.g. click).

#### Actual behaviour
Events are not fired, tooltip not rendered.

#### Live demo with steps to reproduce
Official demo: https://www.highcharts.com/demo/3d-pie-donut
Demo with events: https://jsfiddle.net/BlackLabel/s76nfoe2/ (click on the edge, hovering directly from the outside of the chart)

**Comment by pawelfus** [comment]
**Workaround:**
Add simple plugin:

```javascript
(function(H) {
  H.addEvent(H.seriesTypes.pie.prototype, 'afterDrawTracker', function() {
    if (this.chart.is3d()) {
      // Add reference to the point all sub-shapes
      H.each(this.points, function(point) {
        if (point.graphic) {
          if (point.graphic.side1) {
            point.graphic.side1.element.point = point;
          }
          if (point.graphic.side2) {
            point.graphic.side2.element.point = point;
          }
          if (point.graphic.inn) {
            point.graphic.inn.element.point = point;
          }
          if (point.graphic.out) {
            point.graphic.out.element.point = point;
          }
        }
      });
    }
  });
})(Highcharts);
```

Demo: https://jsfiddle.net/BlackLabel/s76nfoe2/8/

*Internal note:*
@KacperMadej - will pie-3d series get refactoring similar to other 3d series shapes? For example all sides (side1, side2, top, out, inn) will get structure config?

**Comment by KacperMadej** [comment]
@pawelfus Looks like it's possible - probably yes.
