### ISSUE TITLE
How to change height plotLines or plotBands

### ISSUE THREAD

**Issue by boolkaco** [highcharts/highcharts#8909]
#### Expected behavior
Can I please please change the length of the line?

#### Live demo with steps to reproduce
http://jsfiddle.net/st2urd39/1/

#### Affected browser(s)
Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @boolkaco,
Thank you for contacting us. This is our bugtracker, so for the general [support](http://www.highcharts.com/support) questions please use  forum / stackoverflow or email.

Ps. The plotBands / plotLines use full width / height, but you can use [Renderer](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer) (path / rect) and add custom shapes with declared size.
