### ISSUE TITLE
update on dataLabels not working more than once.

### ISSUE THREAD

**Issue by merakmarey** [highcharts/highcharts#8910]
#### Expected behaviour
enable/disable dataLabels

#### Actual behaviour
enable succeed, disable not working

#### Live demo with steps to reproduce

http://jsfiddle.net/otjs0uqf/15/

#### Product version

Latest from cdn
#### Affected browser(s)
Chrome

---------- HTML ----------------
<script src="https://code.highcharts.com/highcharts.js"></script>

<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<div id="container" style="height: 400px"></div>
<input id="switch" type="button" value="ON"/>

---------------- JS ------------------------

$(document).ready(function () {
chart = Highcharts.chart('container', {
    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },

    plotOptions: {
        series: {
            dataLabels: {
                align: 'left',
                enabled: false,
                rotation: 270,
                x: 2,
                y: -10
            }
        }
    },

    series: [{
        data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    }]
});

$('#switch').on('click',function(){
	if ($(this).val()=='ON') {
  	chart.series[0].update({ dataLabels: { enabled: 'true' } });
    $(this).val('OFF');
  } else {
    chart.series[0].update({ dataLabels: { enabled: 'false' } });
    $(this).val('ON');
  }
});
});

**Comment by sebastianbochan** [comment]
Hi @merakmarey,
Thank you for contacting us. The issue is caused by using strings (`'true'` / `'false'`) instead of boolean type (`true / false`).

Fixed demo:
- http://jsfiddle.net/BlackLabel/0r9b6nvj/
