### ISSUE TITLE
Setting softThreshold to false does not work for areaspline

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#8911]
#### Expected behaviour

Setting `softThreshold` for a series to `false` is meant to allow the axis to go negative based on the `minPadding` value, as described [here](https://api.highcharts.com/highcharts/plotOptions.series.softThreshold).

#### Actual behaviour

This happens for `line` and `spline` series types, but not for `areaspline`.  For `areaspline` the axis refuses to go negative, i.e. the `minPadding` value is ignored.

#### Live demo with steps to reproduce

`spline`: http://jsfiddle.net/x8ph7sqt/
`areaspline`: http://jsfiddle.net/62n18bmo/

I can anticipate that it will be suggested that this is "expected" for areaspline because the shading is down to the zero line and it doesn't make sense to show below that.  But IMHO the user should be allowed to show space below the shading if that is what they want, which is possible for example by setting explicit `min` and `max` values on the axis:

http://jsfiddle.net/e407t8yz/

That is a possible workaround, but for my use case padding is far more convenient because I want the positioning to be _relative_ to the data and not _absolute_... the data changes all the time.

#### Product version

6.1.2

#### Affected browser(s)

Chrome, probably all.

**Comment by pawelfus** [comment]
Hi @drmrbrewer 

Thank you for reporting the issue. You are right, this is expected behaviour for area-type series and can be configured through [`series.threshold`](https://api.highcharts.com/highcharts/series.areaspline.threshold) option: http://jsfiddle.net/BlackLabel/62n18bmo/3/ - however it does apply to the area shade too. 

Alternative solution is to use [`yAxis.tickPositioner`](https://api.highcharts.com/highcharts/yAxis.tickPositioner) with `startOnTick = true`: http://jsfiddle.net/BlackLabel/scxw79z1/

**Comment by drmrbrewer** [comment]
Hmm, OK thanks @pawelfus so this isn't a bug but expected?  Personally I think it is surprising that the padding behaviour is so different when simply changing between `spline` and `areaspline`.

Well I foresee yet another workaround in my highcharts code ;)

Another option I guess is to use combine your first suggestion with `zones` to wipe out the fill below the zero line, which seems less hacky than having to use a `tickPositioner` (and having to calculate the absolute padding to match what the user expects from a `minPadding` view of things):

http://jsfiddle.net/dsfn9jgr/

**Comment by pawelfus** [comment]
Thank you for sharing workarounds @drmrbrewer! `areaspline` works the same way, simply `series.threshold` option has different default (`null` for spline, `0` for areaspline). Setting `threshold = 0` for a spline series has exactly the same result: http://jsfiddle.net/BlackLabel/x8ph7sqt/3/ The only difference here is that `threshold` controls extremes in both series, but in `area-type` also controls where shaded area should start. So it's not like `areaspline` behaves differently.

**Comment by drmrbrewer** [comment]
OK so I'll keep my workaround in place, then.  Thanks.
