### ISSUE TITLE
Stacked labels of first and last column are getting out of chart or truncated

### ISSUE THREAD

**Issue by ivan-nejezchleb** [highcharts/highcharts#8912]
#### Expected behaviour
There should be same crop+overflow settings for stacked labels same as for data labels and stack labels should behave according it

#### Actual behaviour
Stack labels cant be positioned and are getting out of chart. Crop and overflow options don't work

#### Live demo with steps to reproduce
http://jsfiddle.net/gq4fahnk/2/

#### Product version
latest

**Comment by pawelfus** [comment]
Hi @ivan-nejezchleb 

Thank you for your suggestion! I think you are right, this would be useful to share crop&overflow feature between dataLabels and stackLabels.

**Comment by alexeykuznetsov** [comment]
When?

**Comment by sebastianbochan** [comment]
Hi @alexeykuznetsov,
Unfortunately, at this moment we do not have ETA for this case, yet. But Im preparing you a really simple snippet, which will overflow the first and the last label. Will post today or tomorrow morning.

**Comment by balkarov** [comment]
Hello. When you fixed the bug?

**Comment by balkarov** [comment]
@sebastianbochan hello!
I tried your workaround, but it did not help me.
https://jsfiddle.net/nt5oh2pw/

![image](https://user-images.githubusercontent.com/6030335/56951379-59c9ff00-6b40-11e9-84d7-5671fd10db0e.png)

**Comment by pawelfus** [comment]
The workaround above is designed to work with `column` series, for `bar` series it's a bit different: https://jsfiddle.net/BlackLabel/yocf798u/1/

**Comment by balkarov** [comment]
@pawelfus but why do you send some workaround? Why can't you add this fix to the library?
The bug from 2018 September.
We pay for the library and now our project has 7 workarounds for Highcharts already. It is not normally.

**Comment by balkarov** [comment]
@pawelfus when you fix this problem in library?

**Comment by pawelfus** [comment]
Hi @balkarov 

No ETA for this feature at this moment, but we will take a look this week.

**Comment by balkarov** [comment]
@pawelfus hello. What about ETA?

**Comment by Basts** [comment]
@balkarov I am going fix it this week.

**Comment by sebastianbochan** [comment]
Hi @balkarov,
Me and @Basts just prepared a solution which solve the issue. All our tests look like promising, but we would like to ensure that all will work also in your environment. 

**Demo:**
- http://jsfiddle.net/BlackLabel/q8ocrw10/5/

Any feedback from you will be really helpful.

**Comment by balkarov** [comment]
@sebastianbochan thank you! We will check

**Comment by balkarov** [comment]
@sebastianbochan after you hack label has big margin
https://jsfiddle.net/5ynre6su/

**before hack**
![before](https://user-images.githubusercontent.com/6030335/58855904-df921a80-86a9-11e9-82fb-9ebcdab46907.PNG)

 **after hack**
![after](https://user-images.githubusercontent.com/6030335/58855932-eae54600-86a9-11e9-8699-04548081cd74.PNG)

**Comment by balkarov** [comment]
Bug is not fixed yet in 7.1.3
https://jsfiddle.net/4qhL5fvg/
![image](https://user-images.githubusercontent.com/6030335/63509058-e62f7180-c4e3-11e9-8f36-2d2af49a6a92.png)

**Comment by Basts** [comment]
@balkarov,
Thank you for the information about it. It seems that my fix doesn't work well in some cases for an inverted chart. 
For your particular case as a workaround, I will suggest setting some small value for stackLabel.x property - [demo](https://jsfiddle.net/BlackLabel/husL902c/).

I suggest also to close this topic and open a new one with this particular issue, which I will try to fix immediately. Would you agree? @TorsteinHonsi

**Comment by balkarov** [comment]
@Basts the similar my issue already closed. But I do not know why. 
https://github.com/highcharts/highcharts/issues/9602

**Comment by pawelfus** [comment]
It seems that was my mistake, my apologies for that! It seems that the issues weren't actually the same. Let me reopen the second issue and close this one (OPs demo looks fine).
