### ISSUE TITLE
X Axis crosshair label not customizable

### ISSUE THREAD

**Issue by outils-tiers-metafactory** [highcharts/highcharts#8915]
#### Expected behaviour
Reading HighStocks documentation, it seems possible to customize the crosshair X axis label, specifying xAxis.crosshair.label.format (https://api.highcharts.com/highstock/xAxis.crosshair.label.format)

#### Actual behaviour
When setting xAxis.crosshair object, a custom label is shown but default crosshair X axis label is also shown and placed above.

#### Live demo with steps to reproduce
http://jsfiddle.net/Lq9v6ma4/ (customizing documentation example taken from http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/css/crosshair-label/)

`

    $.getJSON('https://www.highcharts.com/samples/data/aapl-c.json', function (data) {

        Highcharts.stockChart('container', {

            chart: {
                marginRight: 50
            },
            rangeSelector: {
                selected: 1
            },

            title: {
                text: 'AAPL Stock Price'
            },

            xAxis: {
                crosshair: {
                    label: {
                        enabled: true,
                        format: 'dddddd dddddddd ddd ddddddd'
                    }
                }
            },

            series: [{
                name: 'AAPL',
                data: data,
                tooltip: {
                    valueDecimals: 2
                }
            }]
        });
    });

`

#### Product version

Highstock 6.1.2

#### Affected browser(s)
Chrome, Firefox, Edge (and probably others...)

**Comment by pawelfus** [comment]
Hi @outils-tiers-metafactory 

Thank you for reporting the issue. The second label is not coming from crosshair, but from tooltip ([`tooltip.split`](https://api.highcharts.com/highstock/tooltip.split)). You can disable split option: http://jsfiddle.net/BlackLabel/Lq9v6ma4/1/

By default, crosshair does not have a label ([docs](https://api.highcharts.com/highstock/xAxis.crosshair.label.format): `Defaults to undefined.`).
