### ISSUE TITLE
Missing dependency in Highcharts modules

### ISSUE THREAD

**Issue by mbrodala** [highcharts/highcharts#8916]
#### Expected behaviour
The Highcarts `heatmap` module should declare its dependency on the `highcharts` module. Otherwise it cannot register itself properly using the Highcharts API in case RequireJS is used for loading the modules.

#### Actual behaviour
Rendering the graph fails with [Highcharts error #17](https://www.highcharts.com/errors/17).

#### Live demo with steps to reproduce
https://jsfiddle.net/whvypc7m/1/

#### Product version
Highcharts 6.1.2

#### Affected browser(s)
All

**Comment by mbrodala** [comment]
This is what the head of the module file currenty looks like:

```js
(function (factory) {
	if (typeof module === 'object' && module.exports) {
		module.exports = factory;
	} else if (typeof define === 'function' && define.amd) {
		define(function () {
			return factory;
		});
	} else {
		factory(Highcharts);
	}
}(function (Highcharts) {
```

This is how it should look like instead:

```js
(function (factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory(require('Highcharts'));
  } else if (typeof define === 'function' && define.amd) {
    define(['Highcharts'], factory);
  } else {
    factory(Highcharts);
  }
}(function (Highcharts) {
```

**Comment by mbrodala** [comment]
I just had a look and apparently **all** Highchart modules are affected, so none of these can currently be used with RequireJS.

**Comment by jon-a-nygaard** [comment]
Thanks for reporting. Our developer who implemented the AMD support is currently on vacation. He will have a look at the issue when he is back in the end of next week.

**Comment by oysteinmoseng** [comment]
This is the same issue as https://github.com/highcharts/highcharts/issues/8890. We made a decision to not specify the dependencies in the module files to give our users more control and avoid forcing people into a specific config, but we are seeing a lot of confusion around this. Clearly we need to at least document this in a more visible place. I will take this up with the team.

Closing this as duplicate for now, @mbrodala let me know if the info in #8890 is not enough to solve your issues.

**Comment by oysteinmoseng** [comment]
I am reopening #8890, let's discuss there

**Comment by ak-il** [comment]
I see the [heatmap's demo](https://www.highcharts.com/demo/heatmap) doesn't work, I also tried the code in my create-react-app project and in both cases i see the error log:
`
Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=heatmap
missingModuleFor: heatmap
`
I tried directly importing the heatmap module with the following line but it didn't work as well:
`
import 'highcharts/modules/heatmap';
`
How can I fix this?

**Comment by oysteinmoseng** [comment]
@ak-il Our heatmap module is being picked up by certain ad-blocking filters. This seems to now also be an issue in production, while it was previously limited to local development environments. We will see if we can find a way around this ASAP.

It seems like loading `heatmap.src.js` still works (this is the unminified version), so as a workaround you might want to try that for now.

**Comment by ak-il** [comment]
@oysteinmoseng thanks, disabling the ad blocker did made it work.

**Comment by ganeshchukka** [comment]
> @oysteinmoseng thanks, disabling the ad blocker did make it work.

its not working for me please can you help me

**Comment by oysteinmoseng** [comment]
@ganeshchukka Please contact our [support](https://www.highcharts.com/support/) and give them details about your case, and they can help you out.
