### ISSUE TITLE
Boost module - y zoom type is not working properly.

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#8918]
#### Expected behaviour
With boost module enabled, a chart should be rendered properly after zoom in.

#### Actual behaviour
With boost module enabled, a chart is defective after zoom in.

#### Live demo with steps to reproduce
[http://jsfiddle.net/wchmiel/ru452ec8/](http://jsfiddle.net/wchmiel/ru452ec8/)

#### Product version
Broken since v6.0.5 after commit [https://github.com/highcharts/highcharts/commit/0503060](https://github.com/highcharts/highcharts/commit/0503060)

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Fixed since v6.2.0: http://jsfiddle.net/BlackLabel/bwzg5h4f/2/
