### ISSUE TITLE
Old reflow method for printing doesn't work anymore (no more initReflow)

### ISSUE THREAD

**Issue by lumberg72** [highcharts/highcharts#8921]
#### Expected behaviour
The chart to resize to width of then print-page when printing.

#### Actual behaviour
Isn't resized to accommodate the print-page.

#### Product version
Highcharts 6.1.2

#### Affected browser(s)
Chrome

Previously I had been using the method shown here....
http://jsfiddle.net/highcharts/tp0qo0r9/2/
... and it was working beautifully.

But I just recently noticed that it doesn't 'reflow' anymore when printing. Then I noticed that it seems initReflow() was removed at verison 6.1
Is there a new way to accomplish this?

Thanks!

**Comment by pawelfus** [comment]
Hi @lumberg72 

Thanks for reporting the issue! The method now is called `setReflow` instead of `initReflow`: http://jsfiddle.net/BlackLabel/tp0qo0r9/44/

Alternative solution (not based on internal methods), use `Chart.load` event: http://jsfiddle.net/BlackLabel/tp0qo0r9/46/
