### ISSUE TITLE
heatmap-canvas: Problems render data on Chrome ver.68.0.3440

### ISSUE THREAD

**Issue by marrocmau** [highcharts/highcharts#8924]
#### Expected behaviour
Render data on large Heatmap canvas

#### Actual behaviour
I have a problems using Chrome.

Like you see in image using "old" chrome versione (not canary) your demo apps (large heatmaps) not render the data.

<img width="390" alt="issuechrome" src="https://user-images.githubusercontent.com/914987/45346653-0e131700-b5aa-11e8-9c5f-e7ddbff57e11.png">

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/heatmap-canvas

#### Affected browser(s)
Chrome ver. 68.0.3440

**Comment by pawelfus** [comment]
Hi @marrocmau 

Thank you for reporting this issue. It looks like the same issue described in #8803 - which seems to be a bug in Chrome v68. Could you try current (v69) Chrome release and let us know the result? Thanks!

**Comment by marrocmau** [comment]
On my MAC I have Chrome "69.0.3497.81 (Official Build) (64-bit)" and its works fine with Highcharts.

But our customers have different Windows Server 2008 and all use Chrome 68.0.3440.

I tried also to re-install chrome on Windows Server but the version that google gave me is always the same (68.0.3440).

How do i install the chrome ver.69?

**Comment by pawelfus** [comment]
Go to options (top right corner) -> "Help" -> "About Google Chrome" -> wait for Chrome to update, click restart Chrome button.

**Comment by marrocmau** [comment]
_"Go to options (top right corner) -> "Help" -> "About Google Chrome" -> wait for Chrome to update, click restart Chrome button."

I knew it but there is only the text "Nearly up to date! Relaunch Google Chrome to finish updating."

After restart nothing has changed. Chrome is always in the v68

**Comment by pawelfus** [comment]
I'm sorry I don't know what's the issue then, I suggest to contact Chrome support and report them the upgrade issue.

**Comment by Bertolossi** [comment]
There are still issues on Chrome 69. The PlotLine and PlotBand labels are not displayed.
It works on firefox 59.

**Comment by pawelfus** [comment]
Hi @Bertolossi 

Please provide an example. I think your issue is different from this one (this one is about **canvas** rendering, not SVG).

**Comment by KacperMadej** [comment]
Unable to recreate on Chrome 70+
Looks like a browser issue and it seems to be resolved, so a browser update is required.
Closing as resolved, but if you are still experiencing the problem then please leave a comment with more info and the issue could be reopened.
