### ISSUE TITLE
Wrong decimal separator in tooltip with multiple values for stagged charts

### ISSUE THREAD

**Issue by pa775** [highcharts/highcharts#8926]
#### Expected behaviour
For a stagged chart view the "point.stackTotal" should look like the normal value (comma for german numbers).

#### Actual behaviour
Currently the "point.stackTotal" shows a dot instead of of comma. See the old issue:
https://github.com/highcharts/highcharts/issues/8101

The behaviour should already be fixed (Issue 8101), but this doesn't work for stagged charts.

![image](https://user-images.githubusercontent.com/24253429/45351192-d5793a80-b5b5-11e8-8aa3-b027f6f8b2a4.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/8oxLnhfd/

#### Product version
Hightcharts library 6.1 are used.

#### Affected browser(s)
The effect is shown in every browser (IE, Chrome, Firefox)

**Comment by KacperMadej** [comment]
Hi @pa775 

Thank you for reporting about the problem.

**Workaround:**
Format is set by default only for `y`, so for `stackTotal` you could set it as `{point.stackTotal:.f}` to get a working chart: http://jsfiddle.net/BlackLabel/8oxLnhfd/2/
