### ISSUE TITLE
Bubble chart changes yAxis scale when setting min/max to xAxis

### ISSUE THREAD

**Issue by peterlacko** [highcharts/highcharts#8929]
#### Expected behaviour
Scale on yAxes should not be changed when I set min/max value on xAxis

#### Actual behaviour
When I set max value on xAxis (and thus hide point with maximal value on yAxes), yAxis is re-scaled to new values. This does not happen when I set max value on yAxis, i.e. xAxes doesn't change it's scale.

#### Live demo with steps to reproduce
https://jsfiddle.net/j6v41hL0/23/

#### Product version
Highcharts 6.1.2

#### Affected browser(s)
Firefox, Chrome, others possibly as well

PS: I'm not sure what is correct behavior, if second axis should re-scale or not, but I would expect it to be consistent on both axes.

**Comment by pawelfus** [comment]
Hi @peterlacko 

Have you tried [`series.getExtremesFromAll`](https://api.highcharts.com/highcharts/series.bubble.getExtremesFromAll) ? For example: https://jsfiddle.net/BlackLabel/j6v41hL0/28/

**Comment by peterlacko** [comment]
Hi @pawelfus ,
I wasn't aware of this option which seems to solve the problem, many thanks!

Peter
