### ISSUE TITLE
legend.floating docstring shows legend.layout docstring

### ISSUE THREAD

**Issue by chris-vecchio** [highcharts/highcharts#8932]
#### Expected behaviour
https://api.highcharts.com/highcharts/legend.floating,
https://api.highcharts.com/highstock/legend.floating,
and https://api.highcharts.com/highmaps/legend.floating
should show the docstring for legend.floating.

#### Actual behaviour
The docstring for legend.layout is shown instead. From what I can tell, the @apioption for legend.layout was changed to legend.floating in c2359b24d5d2396a21759ecdd6548deb7a4cc8d5.

Edit: Also just noticed that the Tooltip docstring has @apioption legend instead of tooltip.

**Comment by KacperMadej** [comment]
Hi @chris-vecchio 

Thank you for reporting about this problem.

**Comment by pawelfus** [comment]
Related PR: #8931

**Comment by chris-vecchio** [comment]
@KacperMadej and @pawelfus My pleasure. Thanks for making a great charting library!

**Comment by TorsteinHonsi** [comment]
Fixed, thanks for reporting!
