### ISSUE TITLE
Setting minPointLength on a reversed x-axis xrange-chart will squish all ranges to minPointLength

### ISSUE THREAD

**Issue by satub** [highcharts/highcharts#8933]
#### Expected behaviour
When setting minPointLength to 1, xranges with 0 length should show up as if a vertical line, while wider xranges should render normally.

#### Actual behaviour
When x-axis is reversed, all ranges are squished into lines with width of 1, regardless of their width.

#### Live demo with steps to reproduce
(Template address gives me 404)
Demonstration fiddle: 
https://jsfiddle.net/96m1jcuv/4/

Demo created by starting with official jsfiddle x-range demo  at https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/x-range/

Steps to reproduce:
  1. Change one of the  datapoints to have same start and stop time
  1. Set `minPointLength: 1` . 
      ===> 
![screen shot 2018-09-11 at 10 03 29 am](https://user-images.githubusercontent.com/20072999/45365405-75c96200-b5aa-11e8-824d-c9d238e86a6e.png)

  1. Set x-axis to `reversed: true`
   ====> 
![screen shot 2018-09-11 at 10 03 47 am](https://user-images.githubusercontent.com/20072999/45365416-7bbf4300-b5aa-11e8-843c-7d8b1bd5d499.png)

#### Product version
highcharts v. 6.1.1
highcharts-react-official v1.3.0

#### Affected browser(s)
Chrome, Safari

Edit: x-range works normally when reversed as long as the minPointLength is not set.

**Comment by pawelfus** [comment]
Hi @satub 

Thank you for reporting this bug!
