### ISSUE TITLE
Need help/inputs in upgrade from 4.1.6 to 6.1.2 

### ISSUE THREAD

**Issue by Ramkumar2411** [highcharts/highcharts#8939]
#### Expected behavior
To be able to seamlessly upgrade Highcharts from version 4.1.6 to 6.1.2
(As a drop-in replacement)

#### Actual behavior
I use require to handle module loading(AMD)

When using Highcharts version 4.1.6 I  was loading Highcharts and its dependency like below :
```
define([   
    'highcharts',   
    'highcharts_more',
    'highcharts_3d',
    'funnel',
    'heatmap',
    'treemap',
    'solid_gauge',
    'highchart_annotations',
    'highchart_drilldown',
    'highchart_noData'
], function(Highcharts, Highcharts_more, highcharts_3d, funnel, heatmap,treemap,solid_gauge,Highchart_annotations, Highcharts_drilldown,Highchart_noData) {
    //Code
});
```

Recently I upgraded Highcharts version to 6.1.2 and the charts stopped drawing as per earlier code.
After some debugging, following seems to have worked for me

```
define([   
    'highcharts',   
    'highcharts_more',
    'highcharts_3d',
    'funnel',
    'heatmap',
    'treemap',
    'solid_gauge',
    'highchart_annotations',
    'highchart_drilldown',
    'highchart_noData'	
], function(Highcharts, Highcharts_more, highcharts_3d, funnel, heatmap,treemap,solid_gauge,Highchart_annotations, Highcharts_drilldown,Highchart_noData) {

    // -------- had to add this block  -------- //
     Highcharts_more(Highcharts);
     highcharts_3d(Highcharts);
     funnel(Highcharts)
     heatmap(Highcharts);
     treemap(Highcharts);
     solid_gauge(Highcharts);   
    // --------------------------------------------- //
    //Code
});

```

Is this expected/rightway to work with new Highcharts version? Am I missing something here?

**Comment by pawelfus** [comment]
Hi @Ramkumar2411 

The import with initialisation is the correct way to import Highcharts and all other modules:  https://github.com/highcharts/highcharts#load-highcharts-as-an-amd-module

PS: I didn't know that previous even used to work, probably accidentally, before AMD support was added.
