### ISSUE TITLE
No animation on pie chart using update method and Vue Wrapper

### ISSUE THREAD

**Issue by bensladden** [highcharts/highcharts#8942]
#### Expected behaviour
It is expected that the charts will animate as shown in this example:
http://jsfiddle.net/0wp4ngy9/

#### Actual behaviour
No animation, the pie chart instantly changes to the most recent values. This also appears to be the case for bar and column charts

#### Live demo with steps to reproduce
https://codesandbox.io/s/y0x2561vk9

#### Product version
Highcharts 6.1.0
highcharts-vue 1.0.4
vue ^2.5.2

**Comment by Denyllon** [comment]
This issue was moved to highcharts/highcharts-vue#29

**Comment by TorsteinHonsi** [comment]
@bensladden Please see https://github.com/highcharts/highcharts/issues/8960, it may fix this issue.
