### ISSUE TITLE
How to call API inside highchart in React Js ?

### ISSUE THREAD

**Issue by itjayaprakash** [highcharts/highcharts#8943]
Hi,

We are using  "highcharts": "^6.1.1",  in React App   "react": "^16.4.1",
how to  call the api and parse the data.

data: []
categories: []

Static data is working fine. but we need to change the dynamic data from API

Thanks

**Comment by sebastianbochan** [comment]
Hi @itjayaprakash,
Thank you for contacting us. The github is our bugtracker, so for the general [support](http://www.highcharts.com/support) cases, please use forum / stackoverflow or email.
