### ISSUE TITLE
Boost does not respect 0 boostThreshold when allowForce logic kicks in

### ISSUE THREAD

**Issue by cvasseng** [highcharts/highcharts#8950]
#### Expected behaviour

Setting boost threshold to 0 should force disable boost for that series, even when the `allowForce` logic kicks in (>5 series). Note that the `allowForce` logic works apart from this.

#### Actual behaviour

Setting boost threshold to 0 does nothing to stop boosting when allowForce kicks in.

#### Live demo with steps to reproduce

Series threshold 0 when no allowForce logic is running (works): http://jsfiddle.net/yan68ku1/14/
Series threshold 0 when allowForce logic is running (not working): http://jsfiddle.net/yan68ku1/10/

#### Product version

All.

#### Affected browser(s)

All.

Also see https://github.com/highcharts/highcharts/issues/8919

**Comment by TorsteinHonsi** [comment]
Here's the rationale:

https://github.com/highcharts/highcharts/blob/03c71dbaf5ed412d6017ade9237e867d360fef38/js/modules/boost.src.js#L487-L488

**Comment by cvasseng** [comment]
I think we can still stay within that if this is fixed, as it will still gather the boostables into one canvas/context.

There might be an issue if there's a layout like this though:
series 1: boostable
series 2: non-boostable
series 3: boostable
series 4: boostable
series 5: boostable
series 6: non-boostable
series 7: boostable
series 9: non-boostable
series 10: boostable
series 11: non-boostable
series 12: boostable

..as that would result in 6 contexts. There's a fix we can do for that too, which is to destroy the renderer after rendering (I have a vague memory of having done that already).

**Comment by cvasseng** [comment]
A fix for this has been pushed to `bugfix/allow-disable-series-boost-when-allowforce`. [Pull request](https://github.com/highcharts/highcharts/pull/8953) submitted.

Demo of fix: http://jsfiddle.net/yan68ku1/26/

**Comment by rajeevsinghchib** [comment]
Many Thanks, JSFiddle attached seems to be working as expected.
May I know how can I get hold of this latest boost.js file? The one available on your portal seems to be of date 12th Sep, but this change is in 13th Sep. Do I need to use the boost.js file referenced in jsfiddle for now?
And how long will it take to get it from your portal?

Thanks Again.

**Comment by cvasseng** [comment]
The change will be available on the CDN in the next minor version.

Until then it's available on our Github CDN: https://github.highcharts.com/modules/boost.js

We'd recommend you download the file from there and self-host it if using in production until it becomes available in the next stable version rather than link directly to it.
