### ISSUE TITLE
Click on category without drilldown data

### ISSUE THREAD

**Issue by jocage** [highcharts/highcharts#8956]
#### Expected behaviour

I have chart with legend and drilldown, when I unclick one legend (2010) and click on category Democrats I can see empty Back button.

#### Actual behaviour
When I click on category without data nothing should happened. 

#### Live demo with steps to reproduce
www.jsfiddle.net/69wytk5x/2

**Comment by KacperMadej** [comment]
Hi @jocage 

Thank you for reporting about the problem.

Demo with steps described:
https://jsfiddle.net/BlackLabel/69wytk5x/3/
Steps:
1. click middle category
2. top right corner has the unwanted rectangle

**Comment by jocage** [comment]
Hi Kacper, 

I have quick workarounds for this bug:  jsfiddle.net/69wytk5x/5.

mb will be helpful.
