### ISSUE TITLE
HIOptions not found in HIChartView

### ISSUE THREAD

**Issue by ASumIT2016** [highcharts/highcharts#8966]
#### Actual behaviour
java.util.NoSuchElementException: HIOptions not found in HIChartView

#### Product version

6.1.1

**Comment by sebastianbochan** [comment]
HI @ASumIT2016,
Thank you for reporting. Im moving this ticket to the Android wrapper repo. As a result developers of the platform will contact and help you to solve the issue.

Ref: https://github.com/highcharts/highcharts-android/issues/21
