### ISSUE TITLE
Highcharts y-axis labels format comma-separated values not working

### ISSUE THREAD

**Issue by gurtagel** [highcharts/highcharts#8973]
#### Expected behaviour
I would expect that by putting the following into my y-axis properties I would get comma-separated y-axis values with zero decimal places, but I do not

labels: {
  format: '{value:,.0f}'
}

#### Actual behaviour
What is actually happening is the comma is ignored completely

#### Live demo with steps to reproduce

This is the demo on the official highcharts site where it is also not working (this is for a tooltip but the problem is the same, the comma-separation is not working even for the jsfiddle that highcharts uses as an example):

http://jsfiddle.net/highcharts/rmTWS/
#### Product version

4.x
#### Affected browser(s)
chrome + firefox

**Comment by TorsteinHonsi** [comment]
This is dependent on the language settings. See https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting.

> Note that even though a dot and a comma symbolizes the decimal point and the thousands separator respectively, how it is actually rendered depends on the language settings.

Your demo with the language setting applied: http://jsfiddle.net/highcharts/rmTWS/2632/
