### ISSUE TITLE
MACD throws error while executing "destroy" method

### ISSUE THREAD

**Issue by Tantacula** [highcharts/highcharts#8974]
Hi.

Seems like there's error which I can't reproduce in jsfiddle. Maybe it caused by vuejs third-party plugin integration (our developer used github.com/weizhenye/vue-highcharts) or vuejs render mechanism, not macd script itself, but macd.src.js throws an error right after page loading: "Cannot read property 'destroy' of undefined."

If code in macd.src.js (line 381):

`this.graphmacd = this.graphmacd.destroy();`
`this.graphsignal = this.graphsignal.destroy();`

will be replaced with

`if(this.graphmacd !== undefined) {
    this.graphmacd = this.graphmacd.destroy();
}`
`if(this.graphsignal !== undefined) {
    this.graphsignal = this.graphsignal.destroy();
}`

then error disappears.

Is it possible to fix this moment? If this is expected behaviour and caused by errors in my code (for example some elements should be present in dom before calling destroy methods), could you tell me what could be a reason for this error?

**Comment by sebastianbochan** [comment]
Hi @Tantacula,
The issue (https://github.com/highcharts/highcharts/issues/8848) is already fixed by this commit: https://github.com/highcharts/highcharts/commit/e65140fe1a8f411e52702203f9f4c6397d469d57 and will be the part of next release (v6.1.4).

**Comment by Tantacula** [comment]
@sebastianbochan thanx for the fast reply. Do you know when 6.1.4 will be released?

**Comment by sebastianbochan** [comment]
The next release should be announced within next few weeks.
