### ISSUE TITLE
Cropped legends items became long on hover when useHTML=true

### ISSUE THREAD

**Issue by anikolaev** [highcharts/highcharts#8994]
#### Expected behaviour
Cropped legends items have ellipsis at the end, nothing should change on mouse hover.

#### Actual behaviour
When useHTML=true cropped legends items became long and uncropped on mouse hover. They will overflow the chart if overflow is allowed in CSS for the chart.

It is probably related to this change: https://github.com/highcharts/highcharts/commit/70242674d318b10d6072b9f4c12ffcc655f30722#diff-b96c38f44caa13ec28979489f406c891R40

![image](https://user-images.githubusercontent.com/14847/45692478-89089e80-bb63-11e8-8597-9f4c0c4295bf.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/f0nLvwk8

#### Product version
Highcharts 6.1.3.

#### Affected browser(s)
Probably anyone, checked in Chrome.

**Comment by pawelfus** [comment]
Hi @anikolaev 

Thanks for reporting this bug! 

Last working version: v6.1.1 (demo: https://jsfiddle.net/BlackLabel/f0nLvwk8/4/)

*Internal note:*
It's a regression after 70242674d commit.
