### ISSUE TITLE
Heatmap addData 6.1.2 not updating correctly.

### ISSUE THREAD

**Issue by garybrain** [highcharts/highcharts#8995]
#### Expected behaviour
Ajax addData should update the Heatmap with new data.

#### Actual behaviour
graph update deformed on update.

#### Live demo with steps to reproduce

Working with 6.0.3 : http://jsfiddle.net/gvnLu3f8/4/   ( Alexander / Tuesday = 100 )
No working using 6.1.0 to current : http://jsfiddle.net/gvnLu3f8/3/

#### Product version
Highcharts v6.1.2 (2018-08-31)

#### Affected browser(s)
All.

**Comment by KacperMadej** [comment]
Hi @garybrain 

Thank you for reporting about the regression.

Last working version is 6.0.7.
Broken since version 6.1.0.
Offending commit https://github.com/highcharts/highcharts/commit/7a74166

As a workaround please use version 6.0.7

**Comment by KacperMadej** [comment]
**Simplified demo:** http://jsfiddle.net/BlackLabel/rbkv9d2a/

**Details of the problem:**
Points are wrongly expected to have unique `x` values. Some series types like heatmap, scatter, etc. might not have unique `x` values.

**Code causing the problem:**
https://github.com/highcharts/highcharts/blob/93d9d51f652a7dce148fb1c7260682be82c9ed59/js/parts/Series.js#L3095-L3097

### Workaround:
Use `series.setData` with [`updatePoints`](https://api.highcharts.com/class-reference/Highcharts.Series#setData) argument set to `false`.

**Simple demo with the workaround:** http://jsfiddle.net/BlackLabel/rbkv9d2a/1/
**Original demo with the workaround:** http://jsfiddle.net/BlackLabel/gvnLu3f8/6/

**Comment by TorsteinHonsi** [comment]
I think the entire code block `if (isNumber(x)) {` should only run if `requireSorting`. What do you think @KacperMadej?

`if (requireSorting && isNumber(x)) {`

**Comment by TorsteinHonsi** [comment]
Besides, we should be able to make soft updates (with animation) by using `point.id` instead of linking the points by `x`.

**Comment by KacperMadej** [comment]
@TorsteinHonsi 
I wanted to write suggested changes, but it started to look like a very long text. Instead, I prepared a commit and I'll create a PR in few minutes, so you could comment directly on code.

**Comment by garybrain** [comment]
Hi, the workaround got me past the problem so many thanks for the quick reply.

G.
