### ISSUE TITLE
Tooltip crosshair is coming over the tooltip for area-spline chart

### ISSUE THREAD

**Issue by cowell-cor** [highcharts/highcharts#8996]
#### Expected behaviour
1. Crosshair should come below the tooltip container
2. How to bring the marker of the second series which is overlapped to the front?

#### Actual behaviour
1. Crosshair is coming over the tooltip container
2. All series marker should be visible and they should not be overlapped

#### Live demo with steps to reproduce
Hover over the chart area to see the tooltip
http://jsfiddle.net/kawaljeetdhesi/bwn4s5mg/24/

![image](https://user-images.githubusercontent.com/30604451/45723029-4a7fdd80-bb7d-11e8-93be-377272f8a0e9.png)

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @cowell-cor 

This is our bug tracker, for support questions please use our forum or contact us directly: https://www.highcharts.com/support

PS:
- you have set `zIndex: 20` for your crosshair, change that value and it works fine: http://jsfiddle.net/BlackLabel/bwn4s5mg/29/
- without DOM manipulation, you can not change zIndex of markers, one series is one group
