### ISSUE TITLE
Highstock.js 5.0.6  labels of plotBands can not work on chrome69

### ISSUE THREAD

**Issue by jiang0571** [highcharts/highcharts#8997]
#### Expected behaviour
show labels of plotBands 

#### Actual behaviour
labels disappeared from the chart
the latest version of Highstock works well。

#### Live demo with steps to reproduce

https://jsfiddle.net/jiang0571/2mgLyz4t/1/

#### Product version

5.0.6

#### Affected browser(s)
Chrome 69

**Comment by jiang0571** [comment]
hi pawelfus 

Thank you for your help.

I will upgrade my highstock.js to the latest version.

**Comment by DiegoCardoso** [comment]
Hi @pawelfus 

We have a project on which we are not able to update it to latest Highcharts. Currently we are using Highstock 4.2.6 and noticed the same issue for latest browsers (Chrome/Firefox/Safari). 
Do you believe there's a workaround that we could add in order to fix this issue?

Thanks

**Comment by pawelfus** [comment]
Hi @DiegoCardoso 

In my previous message you can find related commit that fixes the issue - you can apply changes from that commit in your highcharts.src.js file.

**Comment by DiegoCardoso** [comment]
Hi, @pawelfus, thanks for the answer. 

We would like to avoid changing the source file directly, so do you believe that if we add that snippet by extending the `Axis` prototype would also work as expected?

My guess would be that having something like `Highcharts.extend(Highcharts.Axis.prototype, {getPlotBandPath: ...})` would do trick. Is that correct?

**Comment by pawelfus** [comment]
I would use use faster version:

```javascript
Highcharts.Axis.prototype.getPlotBandPath = function () { ... };
```

But both, solutions will break any plugin loaded before this workaround (for example 3D and radial charts). In short, to prevent this, make sure you load file in this order:
- highcharts.js 
- workaround-8997.js
- highcharts-more.js 
- exporting.js
- ...

I can not promise it will do the trick, v4 is two years old, so a lot has changed. I will keep my fingers crossed!

**Comment by DiegoCardoso** [comment]
Ok, I will give a try!

Thanks, @pawelfus
