### ISSUE TITLE
Mention colorIndex in series.{type}.data documentation

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#8998]
Related to #7201

I think the documentation for `series.{type}.data` should also be updated to mention `colorIndex`. For example,

* https://api.highcharts.com/highcharts/series.scatter.data
* https://api.highcharts.com/highcharts/series.column.data
etc.

**Comment by pawelfus** [comment]
Hi @dandv 

Could you tell us where exactly it's missing? `colorIndex` is documented, for example: 
- https://api.highcharts.com/highcharts/series.column.data.colorIndex
- https://api.highcharts.com/highcharts/series.scatter.data.colorIndex

**Comment by dandv** [comment]
Hi, at "3. An array of objects..." - color is mentioned, but not colorIndex

**Comment by pawelfus** [comment]
I don't know.. we have a lot of options listed below, for example `dataLabels`, `className`, `id`, `marker` etc., so listing them there won't really help.

**Comment by TorsteinHonsi** [comment]
Point 3. is just showing the principle of defining points as object literals, it's not supposed to list all available options.

**Comment by dandv** [comment]
@TorsteinHonsi: that makes sense. As a compromise, I would suggest hyperlinking "point configuration objects" at point 3 though (perhaps to https://api.highcharts.com/class-reference/Highcharts.Point). That would prevent new users from thinking the only options for these config objects are those listed in that paragraph, i.e. `x`, `y`, `name` and `color`.

**Comment by TorsteinHonsi** [comment]
Thanks, but a hyperlink wouldn't be necessary, the valid options are the ones listed below the header. I'll try to clarify this in the text.
