### ISSUE TITLE
Highstock: in styled mode, column charts lose color if too many bars are displayed

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#8999]
Use case: display a volume pane (like in [this demo](https://www.highcharts.com/stock/demo/candlestick-and-volume)), but add color for the volume (based on the price going up/down), as in many professional charting applications (see [TradingView](https://www.tradingview.com/chart/?symbol=NASDAQ:AAPL)).

I've been trying to do this in styled mode for [too long, IMO](https://github.com/highcharts/highcharts/issues/8941#issuecomment-421101229) due to an undocumented behavior: when Highstock considers the chart is too "narrow", `colorIndex` information is lost and all column bars take the same color. Given that I was using real data, all volume bars appeared black, and I couldn't figure out why, until it occurred to me to artificially limit the number of data points.

#### Live demo with steps to reproduce
http://jsfiddle.net/dandv/rt716yf0/4/

#### Expected behaviour
HighStock should try to leave color information alone for colored bars (e.g. the volume bars in the example). If this isn't possible past a number of bars due to CSS limitations, the behavior should be documented, in at least these places:
* https://www.highcharts.com/docs/chart-design-and-style/style-by-css
* https://api.highcharts.com/highcharts/plotOptions.series.colorIndex
* https://api.highcharts.com/highcharts/series.column.colorByPoint

#### Actual behaviour
The extra confusing bit is that this unexpected behavior only occurs with `colorByPoint: false` (or omitted), which suggests the entire series should have one color. But that's not the case, as can be seen in the beginning of the demo, when only 4 points are defined, or if 200 is changed to 50 in the fiddle. Setting `colorByPoint: true` *does* display the colors per bar, which suggests there's no CSS limitation (or the colors are displayed incorrectly, similarly to setting `crisp: false`. Either way, this should be documented.

#### Other notes
As I suggested in https://github.com/highcharts/highcharts/issues/8941#issuecomment-421101229, given that colored volume charts are a very common use case for stock charts, an official demo would be great.

**Comment by TorsteinHonsi** [comment]
Pawel and I discussed a solution where non-data and custom point options are copied over from the first point instance and over to the grouped point.

This should prevent the situation we've seen many times, implementers wondering why the point options are not respected, not available in the tooltip etc.

With the OP chart it will look like this: http://jsfiddle.net/rt716yf0/17/ . At least now colors are applied, and since only every other color is shown, it gives a hint that points are somehow grouped or skipped.
