### ISSUE TITLE
Styled mode: column charts leaving 1px gaps between bars

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#9001]
See #6132. The [same fiddle in styled mode](http://jsfiddle.net/dandv/srq8zya6/4/) leaves 1px gap after each column.

#### Expected behaviour
No gap between columns.

#### Actual behaviour
![image](https://user-images.githubusercontent.com/33569/45733943-6ee8b380-bb97-11e8-9103-54f8917557f7.png)

#### Product version
Highcharts latest

#### Affected browser(s)
Chrome 69, possibly others

**Comment by TorsteinHonsi** [comment]
Hi,

In styled mode, the stroke-width is set in CSS, so even if you set `borderWidth` to 0, the CSS is applied. You need to add a CSS rule to style the columns: http://jsfiddle.net/srq8zya6/6/.

According to https://api.highcharts.com/highcharts/plotOptions.column.borderWidth: 

> In styled mode, the stroke width can be set with the .highcharts-point rule.

**Comment by dandv** [comment]
Thanks for clarifying. Would it be useful to mentioned styled mode at https://www.highcharts.com/docs/chart-and-series-types/column-chart ?

**Comment by KacperMadej** [comment]
Thank you for the idea.
Seems like a good enhancement suggestion for the documentation IMHO.

**Comment by pawelfus** [comment]
It's already described in `borderWidth` API and it's simple enough to find styles when inspecting DOM. `borderWidth` is no different from other styles, so we would need to write all styles there, for every series, making documentation crowded.
