### ISSUE TITLE
Boost module can't select a point

### ISSUE THREAD

**Issue by Abbo44** [highcharts/highcharts#9004]
#### Expected behaviour
I want to select a point when boost is enabled. Example without boost : http://jsfiddle.net/nzbLs178/6/

#### Actual behaviour
Select method don't work with boost module.

#### Live demo with steps to reproduce
http://jsfiddle.net/xwkzjpb9/6/

Try to select a point, nothing append.

#### Product version
Highcharts 6.1.2

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @Abbo44,
Thank you for reporting. By default the click / select event is attached to particular SVG point element. But in the boost module, the whole series is one shape. It increases performance but limits some functionalities.

I advise you to checkout related topic here: https://github.com/highcharts/highcharts/issues/4569

**Comment by tkaur6494** [comment]
I tried using the solution given in 4569

plotOptions: {
        series: {
            point: {
                events: {
                    click: function () {
                        alert('a');
                    },
                    mouseOver: function() {
                        if(this.series.halo) {
                            this.series.halo.attr({
                               'class': 'highcharts-tracker' 
                            }).toFront();   
                        }
                    }
                }
            }
        }
    },

But it seems to work only with v8.0.4. I cannot get it to work with v8.0.0. Is any fix available for that version as well?

Help will be highly appreciated.

**Comment by sebastianbochan** [comment]
Hi @tkaur6494,
I really close that this fix is applied by the commit from the ticket: https://github.com/highcharts/highcharts/issues/12870

You can try to edit your files and replace correct lines.

Please keep in your mind that you should use the newest version which fixes current issues.
