### ISSUE TITLE
Setting min on y-axis to value > max data value does not hide points

### ISSUE THREAD

**Issue by peterlacko** [highcharts/highcharts#9016]
When I set min on yAxis to value higher than maximal data value on y-axis, and set max on xAxis, I still see some points that should cut-off by min on yAxis. It does not affect points that are cut-off by setting max on xAxis.

#### Expected behaviour
Points below min value should not be visible.

#### Actual behaviour
Points below min value are visible.

#### Live demo with steps to reproduce
https://jsfiddle.net/8L1pk2ht/13/

#### Product version
Highcharts JS v6.1.3

#### Affected browser(s)
Chrome, Firefox, others probably as well

Note:
This behavior could be fixed by setting getExtremesFromAll in plotOptions.series to true, but I think it should work out of the box.

**Comment by KacperMadej** [comment]
Hi @peterlacko 

Thank you for reporting about the problem.

**Simple demo:**
https://jsfiddle.net/BlackLabel/xesvabrq/

**Simplified description:**
`yAxis` with set `min` to a value that is larger than auto-calculated `max` value, and both `startOnTick` and `endOnTick` are set to `false` than `min` is larger than `max` and axis is wrong and reversed.

**Workaround:**
set `max` in `yAxis` options.
