### ISSUE TITLE
Highstock only: Overlapping data labels in columnrange chart are not hidden correctly

### ISSUE THREAD

**Issue by smaiLee** [highcharts/highcharts#9020]
#### Expected behaviour
If a columnrange chart with data labels in Highstock has to many columns to show all data labels, some labels get hidden. But the visible labels for max values should still be shown on top of bar and the ones for min values on bottom.

#### Actual behaviour
The label for min values are shown on top of bar, the labels for max values aren't shown at all.

#### Live demo with steps to reproduce
Comparison of Highstock and Highcharts behaviour: http://jsfiddle.net/2q8h51nv/13/

#### Product version
Highstock only, v6.1.3 (in Highcharts it works correctly).

#### Affected browser(s)
Tested with Chrome 68 and Firefox 61 under Windows.

**Comment by pawelfus** [comment]
**Workaround:**
Disable [`dataGrouping`](https://api.highcharts.com/highstock/series.columnrange.dataGrouping): http://jsfiddle.net/2q8h51nv/16/
