### ISSUE TITLE
Sankey minimum node height enhancement request

### ISSUE THREAD

**Issue by calsupik** [highcharts/highcharts#9036]
#### Expected behaviour
Add an option to set a minimun node height (similar to nodeLength) to prevent nodes from becoming too small.

#### Actual behaviour
Node height is determined by the larger of either the links to or the links from the node.

#### Live demo with steps to reproduce
In my below demo, the node 'No Next Step' has a very small weight, and no paths after it, therefore the node is extremely small (I understand it is by design). It would be beneficial in my specific use case to have a minimum height for that node so that the label fits fully inside of the node.

https://jsfiddle.net/tvwr8fd3/193/

#### Product version
Highcharts 6.1.0

#### Affected browser(s)
N/A

**Comment by calsupik** [comment]
Support added in PR #9038.

**Comment by mkpasala** [comment]
http://jsfiddle.net/Lmn6gjby/24/ I had a similar issue here. When the values are 0 then the labels are overlapped one on another.

**Comment by baahuabhi** [comment]
hi , i too am facing same issue with google react charts for sankey. can anyone suggest better library?
