### ISSUE TITLE
Highchart scatter - connecting first and last point with line

### ISSUE THREAD

**Issue by abrockman** [highcharts/highcharts#9037]
#### Expected behaviour
Graph should connect each data point in the data array sequentially with a line.

#### Actual behaviour
First and last data points have a line drawn between them.

I have checked the chronological order of the data in the json - they are in the correct order. When the chart is updated it seems like the first and last data points have been swapped and inserted into the middle of the array (scatter.series[0].data).

Sometimes, more often than not, when moving between different data a line is drawn from first to last but it is not always the case. I am unable to isolate the differences in the data when it occurs and when it does not. 

#### Live demo with steps to reproduce
https://jsfiddle.net/abrockman/uak8c04p/2/

#### Product version
v6.1.3

#### Affected browser(s)
Present on at least chrome and firefox.

**Comment by pawelfus** [comment]
Hi @abrockman 

Thank you for reporting this issue. It looks like a regression bug, version v6.0.7 used to work correctly: https://jsfiddle.net/uak8c04p/7/

**Workarounds:**
If `series.update()` is necessary, add extra config option to recreate the series, for example `dataLabels`: https://jsfiddle.net/L9hq74vx/ 
```javascript
  scatter.series[0].update({
    dataLabels: {
      enabled: false
    },
    data: parseTestData(data1)
  });
```
If you only want to update data, use `series.setData(dataset, redraw, animation, updatePoints)` with `updatePoints=false`: https://jsfiddle.net/xyu9q4pe/
```javascript
  scatter.series[0].setData(parseTestData(data1), true, true, false);
```

*Internal note:*
I don't have access to our bisecting tool right now, but I assume it's related to v6.1.0 part from our changelog:

> Added feature to animate the series when updating data through `Series.setData`,  `Series.update` or `Chart.update`. The new logic looks for matching X values and can be disabled through `setData`'s `updatePoints` option.

**Comment by KacperMadej** [comment]
_Internal note:_ Old points are updated and new ones are added. Series type doesn't require sorting (requireSorting is set to false), so new points are pushed into the data array. In series those points are not last and first. Here's demo showing the issue even more: http://jsfiddle.net/BlackLabel/qpdxb08j/

Adding control over `updatePoints` from arguments in `Series.update` (and `Chart.update` for consistency) would resolve the problem? @pawelfus

**Comment by abrockman** [comment]
@pawelfus 
Thanks for the prompt response. I have put the `series.setData(dataset, redraw, animation, updatePoints)` work around into our application and I am no longer running into the behaviour.
