### ISSUE TITLE
Arabic language titles doesn't show up 

### ISSUE THREAD

**Issue by svejdo1** [highcharts/highcharts#9042]
#### Expected behaviour
Arabic language titles will show up

#### Actual behaviour
Arabic language titles doesn't show up

#### Live demo with steps to reproduce
https://jsfiddle.net/svejdo1/5681sbf2/

#### Product version
Highcharts v6.1.3

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @svejdo1,
Thank you for contacting us. For general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.

ps. You should declare `useHTML` flag in the `dataLabels` option.

Demo:
- https://jsfiddle.net/xykowa8f/
