### ISSUE TITLE
Highstock has bad performance on safari when using the scroller.

### ISSUE THREAD

**Issue by Jonathan002** [highcharts/highcharts#9043]
#### Expected behaviour
Highstock candlestick chart can scroll smoothly without forced layout

#### Actual behaviour
When using the scrollbar on a highstock candlestick series it causes a forced reflow causing scroll to be laggy on safari.

![Safari screenshot](https://i.imgur.com/i9x1bsz.png)

This is especially noticeable with mobile safari where a larger project with more nodes and css stall due to forced layout.

#### Live demo with steps to reproduce

https://www.highcharts.com/stock/demo/candlestick

#### Product version

Highstock JS v6.1.2 (2018-08-31)

#### Affected browser(s)
Safari Mobile.

Is there any workaround api config to producing the candlestick chart without calling the functions in the highstock lib that cause a forced layout?

**Comment by TorsteinHonsi** [comment]
You can use the `scrollbar.liveRedraw` setting to turn this off: https://jsfiddle.net/highcharts/ju217pg9/1/.
