### ISSUE TITLE
Serie property 'visible' set to false interferes with boostThreshold behaviour

### ISSUE THREAD

**Issue by BartBM** [highcharts/highcharts#9046]
#### Expected behaviour
When setting the series 'visible' property to false, the boost threshold should work and boost should be disabled when the threshold is not exceded.

#### Actual behaviour
As shown in the JSFiddle reproducible scenario:
- boost is enabled, seriesThreshold is set larger than amount of series
- boostThreshold per serie is set to 250
- the last serie (serie4) has 'visible' set to false
--> now zoom/scroll until you can't go further
--> **no markers are shown ->boost is not disabled**
<img width="696" alt="screen shot 2018-09-24 at 14 46 11" src="https://user-images.githubusercontent.com/9977712/45952936-d6c05380-c008-11e8-843b-dffe73707dfe.png">

- now set the 'visible' parameter of serie4 to true
--> now zoom/scroll until you can't further
--> **markers are shown ->boost is disabled**
<img width="688" alt="screen shot 2018-09-24 at 14 46 35" src="https://user-images.githubusercontent.com/9977712/45952940-db850780-c008-11e8-9059-30ae8893337b.png">

#### Live demo with steps to reproduce
http://jsfiddle.net/BartBM/rsgvx4zL/

#### Product version
Latest Highcharts, boost and maps version, currently 6.1.3

#### Affected browser(s)
Chrome, Safari, Firefox

**Comment by KacperMadej** [comment]
Hi @BartBM 

Thank you for reporting about the problem.

@cvasseng 
Additionally: if the last series is visible then try zooming into small area that would have markers visible, but the markers will not be visible until next zoom.

**Comment by cvasseng** [comment]
This looks to be an issue with `allowForce` not respecting series visibility, and thus making the chart be "stuck" in boost mode.

A workaround until it's fixed is to set `boost.allowForce` to `false` (http://jsfiddle.net/rsgvx4zL/12).

**Comment by BartBM** [comment]
@cvasseng the workaround works for a limited number of hidden series. 
When you increase the number of hidden series it fails too (http://jsfiddle.net/BartBM/rsgvx4zL/)

**Comment by BartBM** [comment]
Seems to work fine now!

**Comment by BartBM** [comment]
@cvasseng, @TorsteinHonsi  There seems to be a regression.
Suppose you load 2 series. And then you execute the following scenario:
```
myChart.series[0].visible = false;
myChart.series[1].visible = false;
myChart.redraw() --> OK

myChart.series[1].visible = true;
myChart.redraw() --> OK

myChart.series[1].visible = false;
myChart.redraw() --> NOK, the  series[1] will stay visible and cause further malfunction in HighCharts
```
There is a workaround, by using the serie.setVisible(serieVisible, false); everything is shown/hidden correctly BUT.. it still causes highcharts to malfunction when for example you zoom in.

![screenshot_20181207_121827](https://user-images.githubusercontent.com/9977712/49644970-84dd7600-fa1a-11e8-9181-ca70b13029ab.png)

**Comment by TorsteinHonsi** [comment]
According to [the docs](https://api.highcharts.com/class-reference/Highcharts.Series#visible), `series.visible` is read only, so this is not expected to work:
http://jsfiddle.net/highcharts/gk0u7fmx/

What you call the _workaround_ is actually the correct way of doing it: http://jsfiddle.net/highcharts/gk0u7fmx/3/.

**Comment by BartBM** [comment]
Indeed @readonly, my bad. But that does not solve the second regression. Notice that I was using the Boost fix files mentioned by cvasseng : http://jsfiddle.net/4dt1ofyx/
```
<script src="https://github.highcharts.com/36e23a3/highcharts.js"></script>
<script src="https://github.highcharts.com/36e23a3/modules/boost.js"></script>
```
Could you try the scenario above with setVisible (explicitly calling it, not via the legend) and then zoom in?

**Comment by TorsteinHonsi** [comment]
Like this? http://jsfiddle.net/highcharts/gk0u7fmx/6/

Wait 2 seconds for the hide/show sequence to run, then zoom in .
