### ISSUE TITLE
Connecting lines to points outside of axis range are not showing for boost mode

### ISSUE THREAD

**Issue by rajeevsinghchib** [highcharts/highcharts#9049]
**Expected behaviour**
Non-boost mode is displaying connecting lines to the point outside of axis range, while boost mode is not displaying the connecting lines.

**Actual behaviour**
To have connecting lines in boost mode also.

**Live demo with steps to reproduce**
Red series is without boost and displaying connecting line to point with value 16, which is out of range for y-axis.
While Green series is with boost and not displaying connecting line to point with value 16, which is out of range for y-axis.
### http://jsfiddle.net/yan68ku1/50/

**Product version**
All.

**Affected browser(s)**
All.

**Screenshot Attached**
![1](https://user-images.githubusercontent.com/25582424/45952753-9f13d480-c025-11e8-802c-d8949b18a64a.PNG)

**Comment by KacperMadej** [comment]
Hi @rajeevsinghchib 

Thank you for reporting about the problem.

@cvasseng It seems to be a boost issue.

**Comment by rajeevsinghchib** [comment]
Hi Guys, Is there any progress on this bug?
Will it be foxed soon?

**Comment by cvasseng** [comment]
Hi rajeevsinghchib, we're still looking into this, and hope to have a fix shortly.

**Comment by rajeevsinghchib** [comment]
Hi Guys,

I have some urgent demo next week. 
Can I expect it to be fixed this week?

**Comment by cvasseng** [comment]
Hi,

this has been fixed now in 02b30a6f2 ([PR](https://github.com/highcharts/highcharts/pull/9093)).

Here's a demo of the fix: http://jsfiddle.net/yan68ku1/52/

The fix will be part of the next release.

Please re-open this issue if you're still seeing issues with the fix enabled.

Thanks again for reporting!
