### ISSUE TITLE
Disable boost fails if min/max was set in yAxis

### ISSUE THREAD

**Issue by Bella-Wang** [highcharts/highcharts#9052]
When min/max was set in yAxis, and tried to disable boost via getSVG (newOptions),  it reported error.  

#### Expected behaviour
When min/max was set in yAxis, and tried to disable boost via getSVG (), getSVG() function should return a string representing the rendered chart

#### Actual behavior
getSVG() return nothing, and would report error when it calls generatePoints () function saying "TypeError: Cannot read property 'length' of undefined" on processedXData.

#### Live demo with steps to reproduce
<http://jsfiddle.net/d5ty7uzk/>

1. Click "Click me" button, which trigger a function to disable boost via getSVG() function.
2. It would throw errors

#### Product version
Tested on Highcharts version 6.1.3

#### Affected browser(s)
latest version of Google Chrome and Firefox

**Comment by pawelfus** [comment]
Hi @Bella-Wang 

Thank you for reporting this bug. 

**Workaround:**
Set also `series.boostThreshold` to 0.
Demos: http://jsfiddle.net/BlackLabel/d5ty7uzk/19/ and simplified http://jsfiddle.net/BlackLabel/vLao0efn/2/

**Simplified demo:**
http://jsfiddle.net/BlackLabel/vLao0efn/

**Comment by TorsteinHonsi** [comment]
Simplified simplified demo http://jsfiddle.net/highcharts/vLao0efn/10/
