### ISSUE TITLE
Plotline label not added to DOM and hence not visible

### ISSUE THREAD

**Issue by eltonjude** [highcharts/highcharts#9053]
#### Expected behaviour
Plotline label should be visible on the chart
http://jsfiddle.net/sb7ou6L4/4/

#### Actual behaviour
Only plotline shows up. Label is not added to the DOM and hence not visible
http://jsfiddle.net/sb7ou6L4/3/

#### Live demo with steps to reproduce
http://jsfiddle.net/sb7ou6L4/3/

#### Product version
Highcharts 4.2.7

#### Affected browser(s)
Tested on latest versions of Chrome, Safari, Firefox

**Comment by sebastianiorga** [comment]
I think this is the issue referenced in: https://github.com/highcharts/highcharts/issues/8477#issuecomment-424353401

The linked comment is a quick fix if you can't update(like me).

**Comment by eltonjude** [comment]
The workaround suggested here fixes the issue. Closing this issue.
https://github.com/highcharts/highcharts/issues/8477#issuecomment-424353401
