### ISSUE TITLE
Mouse hover doesn't show tooltip/highlight for all lines

### ISSUE THREAD

**Issue by pratikrawlekar** [highcharts/highcharts#9054]
#### Expected behaviour
Tooltip/line highlight should be shown for all the lines on which we are hovering.

#### Actual behaviour
It shows tooltip/line highlight in red for some of the lines even if we are hovering on another line.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/parallel-coordinates

**Comment by pawelfus** [comment]
Hi @pratikrawlekar 

Thank you for reporting! You are right, it would be useful to show tooltip for points with exactly the same y-value. 

Regarding issue with wrong lines: at this moment algorithm looks for the closest point, not using the currently hovered line as a reference.

*Internal note:*
We have tooltip per x-value (category), but we don't have `findNearestPointBy="y"` which would be useful in this case. Then we could highlight all points (and series) with the same value and use shared/split tooltip.

**Comment by TorsteinHonsi** [comment]
I'd expect that `findNearestPointBy: 'xy'` would resolve this, but it doesn't seem to make a difference: https://jsfiddle.net/highcharts/s2o5rgjL/1/

**Comment by pawelfus** [comment]
It won't change anything, I think this is simplified case: https://jsfiddle.net/BlackLabel/5qrkbv8e/2/ - hover vertically on the right side of the graph (closer to points with x=1) and you will always green point highlighted.
