### ISSUE TITLE
Area & Line charts - Data module breaks export menu

### ISSUE THREAD

**Issue by graham73may** [highcharts/highcharts#9055]
#### Expected behaviour
To see the export burger menu. 

#### Actual behaviour
When using chart type Area or Line, the export menu is not shown. 

#### Live demo with steps to reproduce
Broken version:
https://codepen.io/graham73may/pen/EeBQgZ?editors=1000

To get the menu working, remove the file:
`"https://code.highcharts.com/modules/data.js"`

This makes the button show up: (the big red thing)
https://codepen.io/graham73may/pen/dqBmOr?editors=1000

#### Product version
Latest

#### Affected browser(s)
All (?)

**Comment by pawelfus** [comment]
Hi @graham73may 

This looks like code generated from Highcharts Cloud, imported in a custom way - could you confirm?

Setting for `marker` is wrong. To be precise:`marker: { symbol: "url(blank)" }` is wrong, removing/disabling this option solves the issue: http://jsfiddle.net/BlackLabel/mb5tz3q8/3/

**Comment by graham73may** [comment]
Hi @pawelfus 

Yes the code is from Highcharts Cloud. Export -> HTML tab. 

I'm currently working on setting up a theme and it likes to keep track of any option I've touched. That marker setting must have snuck in! 

Removing the marker setting does 100% fix the problem. Is it an issue that the marker setting seemingly kills the context menu for area and line charts? (Should I close this issue?)

Thank you for the advice, much appreciated!

**Comment by pawelfus** [comment]
Let's keep it open - personally I think it's a bug, we should gracefully disregard `marker.shape` option when image couldn't be found. Now it breaks, as you reported, other modules.
