### ISSUE TITLE
[Question]Remove spacing between columns in a group in grouped column charts

### ISSUE THREAD

**Issue by Madhu94** [highcharts/highcharts#9061]
#### Expected behaviour
If the data size is variable, for smaller data sizes I would like to reduce the size of the columns(plotOptions.column.maxPointWidth). I would also like to  remove the space between the columns in a group, _no matter what the number of points or size of chart may be_. 

Note - the chart is categorical

#### Actual behaviour
I am able to achieve what I want for a fixed size data by tweaking groupPadding, pointPadding, maxPointWidth and borderWidth

#### Live demo with steps to reproduce
http://jsfiddle.net/u639nz7e/7/
(Increasing number of points also removes this issue, but would like to know if there is any other way to do this)

#### Product version
Highstock - 6.x.x

**Comment by pawelfus** [comment]
Hi @Madhu94 

Could you contact our [support](https://www.highcharts.com/support)? This is our bug tracker. Cheers!

**Comment by Madhu94** [comment]
Apologies, I didn't know. Thanks @pawelfus,
