### ISSUE TITLE
图例项的水平间距

### ISSUE THREAD

**Issue by 15390940742** [highcharts/highcharts#9065]
#### Expected behaviour
想改变图例像默认排列方式，如下图所示
![_15380140307012](https://user-images.githubusercontent.com/36804510/46119455-8ed64200-c23d-11e8-99e2-16c78653c3b5.png)

**Comment by TorsteinHonsi** [comment]
Translated by Google to:

> The horizontal spacing of the legend items
> I want to change the default arrangement of the legend, as shown below.

Thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.
