### ISSUE TITLE
eror with drilldown stacked bar highchart

### ISSUE THREAD

**Issue by ridhoamdeni26** [highcharts/highcharts#9067]
i trying create highchart with drilldown and if user clicked he got stacked bar 

example : http://jsfiddle.net/jpbkqme5/3/ 

see there I have an error when the first click on the data does not appear immediately and if I click again on the bar then it will return the data so that the data will be a lot. can anyone help why on this chart an error occurred

**Comment by sebastianbochan** [comment]
Hi @ridhoamdeni26,
The github is our bugtracker, so for general [support]() questions, please use forum / stackoverflow or email.

ps. In the drilldown event you refer to `chart.userOptions.drilldown.series` which, in the first click, are undefined (you declare it in the end of function). As a result your loop is not triggered and `chart.applyDrilldown` cannot be called. The solution is define drilldowns at the beginning of event.

Fixed demo:
- http://jsfiddle.net/BlackLabel/85ngu3wp/
