### ISSUE TITLE
Stacked area chart with multiple series shows line chart in one of the series for some x axis values 

### ISSUE THREAD

**Issue by rubiks-cube** [highcharts/highcharts#9069]
#### Affected browser(s)
Chrome(v69.0.3497.100)

**Comment by pawelfus** [comment]
Hi @rubiks-cube 

Please, provide all details required to report the issue, including live demo. Thanks!

**Comment by rubiks-cube** [comment]
![stackedareachart](https://user-images.githubusercontent.com/34497214/46141759-83e9d480-c272-11e8-8eb0-7c3d51883440.PNG)
This is how chart looks.

**Comment by TorsteinHonsi** [comment]
Live demo please? You can use this as a starting point: http://jsfiddle.net/highcharts/63nx2k5s/

Do your changes, click Save or Update then post the new link.
