### ISSUE TITLE
Pivoting Rendering?

### ISSUE THREAD

**Issue by DongShi** [highcharts/highcharts#9073]
#### Expected behaviour

Hi There,
We are using HC heavily on multiple product lines, one of which is the mobile H5 page. 
As on mobile screen,  one common request is to draw certain charts on a landscape mode, not  portrait mode.

Examples would include column chart with many category items. 
Less category items would be shown If drawn in portrait mobile screen, compared to landscape case. 

So my question is :
Is there an API such that we can pivot the chart?

Landscape:
![image](https://user-images.githubusercontent.com/5009987/46144738-717e9380-c290-11e8-8df2-a39013006118.png)

Portrait:
![image](https://user-images.githubusercontent.com/5009987/46144778-88bd8100-c290-11e8-89cf-6bee9d9b287d.png)

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

PS: See https://api.highcharts.com/highcharts/chart.inverted and also plenty of demos of this in https://www.highcharts.com/demo
