### ISSUE TITLE
Dynamic chart is not updated properly when browser's tab is inactive

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#9074]
#### Expected behaviour
The distance between every 2 subsequent points should always be 1 second (refer to the demo from _Live demo with steps to reproduce_ section).

#### Actual behaviour
Sometimes these distances are bigger when the tab is inactive:
![image](https://user-images.githubusercontent.com/13188589/46151721-af1ef480-c26f-11e8-9631-ab3fe29ef168.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/npy7c2ut/
Launch the demo and switch to some other tab of a browser (in the same window). Return to the inactive tab after 2-3 minutes and wait for 3-4 seconds. You should see something similar to what's presented on the above screenshot. After few seconds the chart comes back to normal look and behavior (all distances equal to 1 second).

#### Product version
6.1.4

**Comment by TorsteinHonsi** [comment]
Probably Chrome is limiting resources spent in inactive tabs, resulting in some of the steps in `setInterval` being skipped.

**Comment by KacperMadej** [comment]
Inactive tab needs to wait more - especially if another, active tab is using a lot of resources - so real interval between added points is bigger. This is not a Highcharts bug, this is just how browser handles inactive tabs activity. Closing as not a bug.
