### ISSUE TITLE
Animates when increasing size, even with all animation options turned off

### ISSUE THREAD

**Issue by jacobweber** [highcharts/highcharts#9076]
#### Expected behaviour
With all animation options off, when chart size is increased, chart doesn't animate.

#### Actual behaviour
Chart animates when increasing size. It's not the smooth animation that you get if animate=true, but it's still noticeable. It just sort of gradually reveals itself from left to right.

#### Live demo with steps to reproduce
http://jsfiddle.net/br5hj0s4/
1. Load page. No initial animation (correct).
2. Click Update to decrease size. Doesn't animate (correct).
3. Click Update again to increase size. This time it animates (incorrect).

#### Product version

Latest (6.1.4)

#### Affected browser(s)
Chrome 69.0.3497.100 and Safari 12.0 for Mac.

**Comment by KacperMadej** [comment]
Hi @jacobweber 

Thank you for contacting us about the problem.

By default animation for setSize defaults to true, so if you are not setting it in chart.udpate then is will animate the dynamic change that you have set up (update). To resolve this be sure to set animation to false for the used [update](https://api.highcharts.com/class-reference/Highcharts.Chart#update) function. You can see in documentation that by default chart.update has the animation argument set to true, so to prevent animation be sure to set it to false.

**Comment by jacobweber** [comment]
You can see the same behavior if you pass false ([example](http://jsfiddle.net/br5hj0s4/2/)), since I set the default animation to false. It's different than the normal animation that you get when you set it to true; it's more like it's just taking a while to draw it from left to right. But you don't see this when it's initially rendered.

**Comment by jacobweber** [comment]
My apologies; I mis-counted the arguments.
