### ISSUE TITLE
【6.1.4HighStock LineChart】After update to 6.1.4,  some data not show up when the data records are very large

### ISSUE THREAD

**Issue by kidmysoul** [highcharts/highcharts#9077]
#### Expected behaviour
show data like the version before 6.1.4

#### Actual behaviour
some data is not showing up

#### Live demo with steps to reproduce

http://jsfiddle.net/scny40jr/62/

#### Product version

I use "https://code.highcharts.com/stock/highstock.js" 
so it's the newest version 6.1.4
#### Affected browser(s)
I use this library in mobile webview

I have some data for people's weights , there are two people for example the first one have 700+ weights records and the second people have 5 weights records. And they both have records for .....9/26, 9/27, 9/28 . but for the first people, the 9/26 data is not showing,(and also 9/22 , 9/18...looks like data is missing every 3 days)

this behavior only happened when rangeSelector is in week, month. 
and for the second people ,all worked well.

this is example image

- the first people's record:
<img width="343" alt="2018-09-28 10 52 13" src="https://user-images.githubusercontent.com/15664045/46184242-9fef8380-c30f-11e8-91f6-8fa5e9f71d68.png">

- the wrong chart(week)

<img width="398" alt="2018-09-28 11 17 53" src="https://user-images.githubusercontent.com/15664045/46184371-5489a500-c310-11e8-9f2a-5725a804cfc4.png">

- the wrong chart(one month)
<img width="384" alt="2018-09-28 11 18 03" src="https://user-images.githubusercontent.com/15664045/46184377-6408ee00-c310-11e8-9eac-6b93dda544aa.png">

- the wrong chart(3 month)
<img width="407" alt="2018-09-28 10 53 26" src="https://user-images.githubusercontent.com/15664045/46184430-9ca8c780-c310-11e8-875f-a35b24742a32.png">

- the right chart(year)
<img width="404" alt="2018-09-28 10 53 33" src="https://user-images.githubusercontent.com/15664045/46184557-1d67c380-c311-11e8-8e12-5fee44d96043.png">

- the second people's record:

<img width="312" alt="2018-09-28 10 52 29" src="https://user-images.githubusercontent.com/15664045/46184447-a9c5b680-c310-11e8-9dd7-f32eb3a96a0d.png">

- the right chart
<img width="401" alt="2018-09-28 10 52 43" src="https://user-images.githubusercontent.com/15664045/46184461-b5b17880-c310-11e8-9e37-bff31fde6189.png">

I haven't changed any code  and it happened suddenly.

**Comment by KacperMadej** [comment]
Hi @kidmysoul 

Thank you for reporting about the problem.
Please add a live demo of the issue - minimal demo with hard coded exemplary data will be best in this case.

**Comment by kidmysoul** [comment]
@KacperMadej 

this is the demo.

http://jsfiddle.net/scny40jr/62/

and the demo even does not show any line.

**Comment by KacperMadej** [comment]
Offending commit - https://github.com/highcharts/highcharts/commit/7c82a4f

Simple demo - http://jsfiddle.net/BlackLabel/ez7urmy3/
Steps -
drag navigator window slowly decreasing it until you see it jump to no-point or only few point on right side.

@TorsteinHonsi @pawelfus

**Comment by pawelfus** [comment]
**Workaround:**
Use v6.1.3 or set [`dataGrouping.forced`](https://api.highcharts.com/highstock/plotOptions.line.dataGrouping.forced) to true: http://jsfiddle.net/BlackLabel/scny40jr/84/

*Internal note:* 
It's a regression after 7c82a4ffd and it's broken only for points in object format, array format is unaffected.
