### ISSUE TITLE
Plotlines label is not rendering

### ISSUE THREAD

**Issue by sowmyakj** [highcharts/highcharts#9078]
Hi,
#### Actual behaviour
I am using Highstock v6.0.7 from years it was working fine,after updating my chrome to new version  plotlines label is not rendering.

#### Product version
Highstock JS v6.0.7

#### Affected browser(s)
Version 69.0.3497.100

**Comment by nteetor** [comment]
Any chance this is a duplicate of https://github.com/highcharts/highcharts/issues/8477? 

If, like me, you cannot upgrade to the latest version of Highcharts, try the code snippet found here, https://github.com/highcharts/highcharts/issues/8477#issuecomment-424353401.

**Comment by pawelfus** [comment]
Closing as duplicate of #8477.
