### ISSUE TITLE
Docs: lint rules for doclets needed

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#9081]

**Comment by TorsteinHonsi** [comment]
Rules should be added to https://github.com/highcharts/eslint-plugin-highcharts which is already used for some custom rules.

**Comment by bre1470** [comment]
@TorsteinHonsi Please review and merge this PR: https://github.com/highcharts/eslint-plugin-highcharts/pull/2

**Comment by bre1470** [comment]
Rules are added.
