### ISSUE TITLE
Highmaps : Is it possible to add padding between container and plot area

### ISSUE THREAD

**Issue by inwebitrust** [highcharts/highcharts#9083]
#### Expected behaviour
I want to add some padding around the plot area in a map so that the drop shadow I use is not cut

#### Actual behaviour
The margin/spacing parameters doesn't seem to change the space between chart limits and plot area

#### Live demo with steps to reproduce
Live example here : 
https://jsfiddle.net/vku5edpx/

You can see there is no space between the plot background and the map

#### Product version
Highmaps 6.1.4

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @inwebitrust 

Please use available support channels for technical questions - we are trying to keep GitHub issues for bug reports. https://www.highcharts.com/support

The options you used in demo work fine - https://jsfiddle.net/BlackLabel/vku5edpx/1/ Margin adds space between container and plot area.

**Comment by Chandranath356** [comment]
789
