### ISSUE TITLE
Export HTML truncates at first </svg> instead of last </svg>

### ISSUE THREAD

**Issue by species360** [highcharts/highcharts#9087]
#### Expected behaviour
![chart 56](https://user-images.githubusercontent.com/42000974/46227029-9f60e800-c323-11e8-9185-a0fed573afd7.png)

#### Actual behaviour
![chart 53](https://user-images.githubusercontent.com/42000974/46227065-adaf0400-c323-11e8-9ca6-65c979ea398b.png)

#### Live demo with steps to reproduce
Custom HTML based legend with `<svg>` tags.

#### Product version
Highcharts 6.1.1

#### Affected browser(s)
All

The issue is caused by this line 918 in /js/modules/exporting.src.js which was added because of issue #894.

The offending line is:
`.replace(/<\/svg>.*?$/, '</svg>')`

But should be:
`.replace(/<\/svg>(?!.*<\/svg>).*$/, '</svg>')`

The former is relying on the regex lazy operator to match against the last `</svg>` , but it is jumping the fence to try to get a good match.  The latter is using negative-look-ahead to ensure that it is the final </svg> in the string.  Which then provides the expected result.

Note: If you look at what is submitted out to exporting.highcharts.com from the browser with `<svg>` in the legend you can see it is sending truncated (and the first `</svg>`) and improperly formed HTML to the server.

**Comment by TorsteinHonsi** [comment]
Even with this change, it seems to send malformed SVG. By setting `useHTML` to true, we add a div and some spans after the main SVG, and with this change, it is clipped after the last `</svg>`.

**Comment by species360** [comment]
Agreed, but it looked like the original code was trying to remove any trailing HTML from the content after the final SVG so I was trying to keep with the spirit of the original change.

**Comment by mfinger** [comment]
Actually, I think the commit that closed this is not fixing the issue but just doing the bug in a different way.

The commit is looking for the index of the first </svg> then removing anything trailing it.  Which is going to result in the same.

`var split = svg.indexOf('</svg>') + 6`

The above is just finding the index of the first </svg> then setting the position after it.

that is why I sent in the regex, I did.  It finds the *last* </svg> and removes code after it.
`.replace(/<\/svg>(?!.*<\/svg>).*$/, '</svg>')`

Again, for us, we have multiple <svg> tags in there.  This commit will continue to remove all but the first <svg>

**Comment by TorsteinHonsi** [comment]
Did you try it? See https://jsfiddle.net/highcharts/10m87sgv/.

What happens is that we first split on the first `</svg>`. Then the HTML that is appended after the SVG is extracted and inserted in a `foreignObject`. Including the SVG graphics that were inside the HTML legend items.

**Comment by mfinger** [comment]
I apologize and am actually a little embarrassed that I had not yet.  Not how I normally work.

I will try to find time soon to test it in our code base and let you know.

Thanks!

**Comment by jasekiw** [comment]
@TorsteinHonsi This corrupts a chart output where nested svgs are added to it. Nesting svgs are [allowed in the spec](https://www.w3.org/TR/SVG2/struct.html#TermContainerElement). I thought it was fine to add an svg icon to the xrange series but highcharts cuts off the output at the first icon's `</svg>` losing the rest of the chart.

https://github.com/highcharts/highcharts/blob/69ad6ec944db680e97ed0e6e0e7539964b697251/ts/Extensions/Exporting/Exporting.ts#L1725

**Comment by hubertkozik** [comment]
Hi @jasekiw! I've just prepared a simple demo with SVG icons as data labels, when you set `exporting.allowHTML` to `true`, according to the documentation everything works as expected: https://jsfiddle.net/BlackLabel/4xf0bkcs/

Can you prepare a demo with the reproduced issue?

**Comment by jasekiw** [comment]
Hi @hubertkozik , I am specifically trying to add an icon to each point in an xrange series. I modified the example you gave and it only added it to the first one: https://jsfiddle.net/ycfgz3nx/3/ 

I was able to accomplish this via the renderer but like I mentioned, it chops it off at the ending </svg> of the first icon.  I'm guessing switching on allowHTML to true would fix that issue but It struck me as odd since nested svgs are part of the svg spec and not just html.

![image](https://github.com/highcharts/highcharts/assets/4037224/c4ab1bab-ac66-4a42-9588-ddd80e4b8433)

I specifically am picking a different icon per bar which represents an alert in my chart. The icon matches the color of the bar.

I essentially did this:

looped through the points of the xrange series  - checked if the icon is added, add it if not - calculate the position for it to be vertically centered and padded from the beginning of the bar - fill the color the same as the border color. I'm sure I did it the hard way.

```javascript
events: {
	render: function () {
	  const xRangeSeries = this.series.filter((s) => s.type === 'xrange')[0]?.data;
	  if (!xRangeSeries) return;
	  xRangeSeries.forEach((point) => {       
		if (!point.graphic?.element) {
		  return;
		}
		const alert = alertsById[point.options!.custom!['alertId'] as number];
		const lastChild = point.graphic!.element!.lastChild!;
		const pathElement = point.graphic!.element!.firstChild! as SVGPathElement;
		if (lastChild instanceof SVGPathElement) {
		  (point.graphic!.element as HTMLElement).insertAdjacentHTML(
			'beforeend',
			alert.AlertGroupName === 'Trip'
			  ? ExclamationTriangle
			  : alert.AlertGroupName === 'Warning'
				? ExclamationCircle
				: alert.AlertGroupName === 'Info'
				  ? Info
				  : alert.AlertGroupName === 'Error'
					? WifiOff
					: ExclamationTriangle
		  );
		}

		const iconElement = point.graphic!.element!.lastChild! as SVGElement;
		const x2 = this.xAxis[0]!.toPixels(point.x2!, true);
		const x = this.xAxis[0]!.toPixels(point.x, true);
		const width = Math.abs(x2 - x);
		const y = point.pos(false, undefined)![1];
		const height = pathElement.getClientRects()[0].height;
		const iconHeight = height * 0.8;
		const iconWidth = width > 20 ? 10 : width * 0.5;
		const iconSize = Math.min(iconHeight, iconWidth);
		const iconX = x + (width > 20 ? 5 : width * 0.2);
		const iconY = y - iconSize / 2;
		iconElement.setAttribute('width', String(iconSize));
		iconElement.setAttribute('height', String(iconSize));
		iconElement.setAttribute('x', String(iconX));
		iconElement.setAttribute('y', String(iconY));
		iconElement.setAttribute('fill', point.options.borderColor as string);
	  });
}
```
