### ISSUE TITLE
Exporting color problem with Rtl text

### ISSUE THREAD

**Issue by amirhosseinghorbani** [highcharts/highcharts#9089]
#### Expected
Highchart use exporting configuration and works well with font styles and colors for Ltr text(data labels). it doesn't have any problem with English.
Actually it was working until I updated my highcharts.js from **v4.1.5** to latest version  **v6.1.4**

#### Actual
My problem with Highcharts is when we need to get export of chats, Highcharts use White color to render Rtl text(data labels) as default and we cannot change the default color.
![chart](https://user-images.githubusercontent.com/14129919/46243844-f084e080-c3e4-11e8-8a26-37ad88db5f85.jpeg)

#### Live demo with steps to reproduce
[Live Demo](https://jsfiddle.net/amirhosseinghorbani/kbjxeo7z/2/)

### Product version
 **v6.1.4**

#### Affected browser(s)
**Chrome, Firefox, All**

**Comment by pawelfus** [comment]
Hi @amirhosseinghorbani 

Thank you for reporting this issue. 

**Workaround:**
Set [`dataLabels.style.textOutline`](https://api.highcharts.com/highstock/series.column.dataLabels.style) to `"none"`: https://jsfiddle.net/BlackLabel/kbjxeo7z/19/


It's a regression after 7ba29130f

**Comment by TorsteinHonsi** [comment]
Duplicate of #9048
