### ISSUE TITLE
showCheckbox doesn't work with layout proximate

### ISSUE THREAD

**Issue by Talglys** [highcharts/highcharts#9091]
#### Expected behaviour
Checkboxes appears next to legend elements

#### Actual behaviour
No checkboxes appear

#### Live demo with steps to reproduce
http://jsfiddle.net/9xf2d0bu/
Changing the layout to vertical brings back the checkboxes, but with layout set to proximate, the checkboxes never appear.

#### Product version
Highcharts 6.1.2

#### Affected browser(s)
Google chrome, firefox, probably others

**Comment by pawelfus** [comment]
Hi @Talglys 

Thank you for reporting this issue. 

**Workaround:**
Demo: http://jsfiddle.net/BlackLabel/xbm6hzds/
Snippet:
```javascript
(function(H) {
  H.wrap(H.Legend.prototype, 'positionCheckboxes', function(p) {
    p.apply(this, Array.prototype.slice.call(arguments, 1));

    H.each(this.allItems, function(item) {
      if (item.checkbox) {
        H.css(item.checkbox, {
          display: 'block'
        });
      }
    });
  });
})(Highcharts);
```
