### ISSUE TITLE
Changelog generator

### ISSUE THREAD

**Issue by marvin19** [highcharts/highcharts#9092]
#### Expected behaviour
Removed two of the columns: `<div class="col-md-1 hidden-sm"> </div>`(There should be only one column after this).
Html-classes has been updated to bootstrap 4:
Replace `<div id="accordion" class="panel-group">` with  `<div id="accordion" class="card-group">`
Replace `<div class="panel panel-default">` with `<div class="card">`
Replace `<div id="heading-6-1-4-bug-fixes" class="panel-heading">` with `<div id="heading-6-1-4-bug-fixes" class="card-header">` (The id is not supposed to be change since it is different for every item)
Replace `<h4 class="panel-title">` with `<h4 class="card-title" id="changelog">` (Also ad the id)
Replace `<div id="6-1-1-bug-fixes" class="panel-collapse collapse">` with `<div id="6-1-1-bug-fixes" class="collapse">` (again, the id not relevant in the change)
Replace `<div class="panel-body">` with `<div class="card-body">`

I put it in a diffchecker if it is easier to see the changes I made: https://www.diffchecker.com/mfxkXGP5

#### Actual behaviour
Old bootstrap

**Comment by KacperMadej** [comment]
Hi @marvin19 

Thank you for reporting about the issue.

**Comment by bre1470** [comment]
Does anybody know, if this issue is still valid? I do not see a diff.

**Comment by marvin19** [comment]
Not valid anymore!
