### ISSUE TITLE
Problem with reducing the number of series with individual axes in chart.update

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#9097]
#### Expected behaviour
Method `update` should allow to reduce the number of series with individual axes.

#### Actual behaviour
Error in the console: `Uncaught TypeError: Cannot read property 'hoverSeries' of undefined`

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/3bdojkf9/

Click on 'update' button.

#### Product version
Highcharts v6.1.4

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
_Internal note:_
Caused by removing a removed series. `itemsForRemoval` are being removed. Axis first and on yAxis remove it's series are removed. Later the removed series are in `itemsForRemoval` and code fails on second remove call (due to lack of chart reference in the object).
