### ISSUE TITLE
Wind Rose / Polar chart tooltip placement incorrect

### ISSUE THREAD

**Issue by jamie-pi** [highcharts/highcharts#9098]
#### Expected behaviour
The tooltip for each point will show when the mouse is within the consistent boundary for that point.

#### Actual behaviour
When hovering slightly to the left of the top (first) point on the chart, the tooltip shows for the point to the left. However, this doesn't happen with any other points. The hover area for the first point is too small, and the area for the last point is too big.

#### Live demo with steps to reproduce
template: jsfiddle.net/jamie_ip/pojk2eb7/

#### Product version
Highcharts 6.1.4

#### Affected browser(s)
Chrome, Firefox (only tested on these two)

**Comment by pawelfus** [comment]
Hi @jamie-pi 

Thank you for reporting the issue. It looks like it happens only when `poinPlacement` is set to `"on"`. For between it works fine: http://jsfiddle.net/BlackLabel/pojk2eb7/6/

Simplified demo: http://jsfiddle.net/BlackLabel/pojk2eb7/12/

Steps:
- hover first point
- hover yAxis label "2.5"

![cdmlwzscyg](https://user-images.githubusercontent.com/1453926/46341296-18b84d80-c638-11e8-8c15-e350a3b2de22.gif)
