### ISSUE TITLE
"Off-by-one" Behavior of chart.getSelectedPoints() in series.point.events.select event handler. 

### ISSUE THREAD

**Issue by krishnaku** [highcharts/highcharts#9099]
Hi, 

When I call chart.getSelectedPoints inside the series.point.events.select handler, the points
being returned are "off-by-one". After the first click it returns an empty list. The next shift-click (which should have returned two items, returns 1, the next shift-click returns 2 (instead of 3) etc..

I have attached a live demo link below 

thanks
Krishna

#### Expected behaviour
First click returns 1 point, next shift-click returns 2... etc

#### Actual behaviour
First click returns 0, next shift-click returns 1 etc..

#### Live demo with steps to reproduce
http://jsfiddle.net/yjsL3b76/

#### Product version
Latest.

**Comment by krishnaku** [comment]
I see.. thanks. I can work with this if this is expected behavior. 

Krishna

**Comment by krishnaku** [comment]
I must say this is very counter intuitive behavior in a "selection" handler. It seems like it might be better to allow selection cancellation in the click event, but I understand that this is the design. I will close the issue.

**Comment by adumesny** [comment]
totally agree with @krishnaku - very counter intuitive AND there is no way I could find to be called AFTER selection is done to have a correct getSelectedPoints() (short of a setTimeout hack on the click but that's assumes user driven). If you do select then you need to handle unselect as well....

You already have the click event (where you could prevent selection) and would expect select event to be after, but then you have unselect, so it seems you need a afterSelectionChange type of events to not break current behavior.

**Comment by TorsteinHonsi** [comment]
I agree this is counter-intuitive. Working on a fix where the point is staged before running the event, and part of the returned `getSelectedPoints`.

**Comment by krishnaku** [comment]
That’s good. I will happily unwind the hacks I had to put in to work around this :)

Krishna.

**Comment by adumesny** [comment]
@TorsteinHonsi while updating `getSelectedPoints` to have the point added (hopefully that won't break existing code), this doesn't prevent the need to have a single event for selection change is done BECAUSE otherwise the user has to also realize they need to do the same in `unselect` event. I think it's ok to leave existing behavior as long as it clearly documented that `select/unselect` can be used to prevent selection, and that `afterSelectionChanged` can be used to get the final state, which you haven't taken yet.
