### ISSUE TITLE
Feature Request: Don't show labels for all categories

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#910]
I have a case where I'm using data + categories.  The categories follow a pattern, but there are many of them, so when the graph is small, the labels overlap and are unreadable.

What would be preferable would be to not display all labels, but to intelligently display every n-th label to make it readable.

I understand that in many cases, categories should not be hidden, but in my case, they follow a pattern, so the missing labels can be inferred by the viewer.  An option true/false would be nice.

**Comment by abdulwahidgul24085** [comment]
So is this not an existing feature? :|

**Comment by TorsteinHonsi** [comment]
This thread is five years old. In current version, Highcharts doesn't overlap category labels. By default, it tries to rotate them to make room for all labels. If that doesn't work, intermediate labels are removed.
