### ISSUE TITLE
Docs: Automate deployment of wrapper documentation

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#9101]
The wrapper documentation should be deployed automatically like build/api.

**Comment by sophiebremer** [comment]
Todo:
- fetch documentation from corresponding repository branches
- put it in build/api
- upload
- sync backend accordingly

**Comment by bre1470** [comment]
It actually makes no sense, because the wrapper docs are not ready in time of release. The created solution with jsdoc-wrappers + jsdoc-upload is an effective solution.
