### ISSUE TITLE
Highstock - Stochastic indicator name shows wrong periods (always default)

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#9102]
#### Expected behaviour
The name should show actual periods.

#### Actual behaviour
The name shows always default periods.

#### Live demo with steps to reproduce
http://jsfiddle.net/wchmiel/to3jns9d/1/

#### Product version
Highstock

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
**Workaround:**

Set `series.name=null` to use built-in name generator: http://jsfiddle.net/BlackLabel/to3jns9d/3/
