### ISSUE TITLE
Proximate formatting problem when combination of height and series 

### ISSUE THREAD

**Issue by garybrain** [highcharts/highcharts#9104]
#### Expected behaviour
Proximate should position legend near series data

#### Actual behaviour
When number of series exceeds height of the graph the legend are stacked at top of graph

#### Live demo with steps to reproduce
http://jsfiddle.net/u2yp509c/1/

#### Product version
Highcharts JS v6.1.4 (2018-09-25)

#### Affected browser(s)
All Browsers

**Comment by pawelfus** [comment]
Hi @garybrain 

Thank you for reporting this bug. 

Simplified demo:
http://jsfiddle.net/BlackLabel/u2yp509c/4/
