### ISSUE TITLE
Series labels are positioning in different ways in Firefox and Chrome.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#9105]
#### Expected behaviour

Series labels should be anchored to the same point in both of the browsers.

#### Actual behaviour

The same series label configuration looks different, depending on the browser in which we generate the chart.

#### Live demo with steps to reproduce

Official example: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series-label/stock-chart

#### Product version

v6.1.0 and above.

Looks like the https://github.com/highcharts/highcharts/commit/27b331469 commit makes it work incorrectly.

**Comment by KacperMadej** [comment]
Simplified demo:
http://jsfiddle.net/BlackLabel/ey1c5qr8/1/

Win 10:
* Chrome: 
![chart 66](https://user-images.githubusercontent.com/8960408/46402225-7368ac80-c6ff-11e8-83ff-95ab782ecaf2.png)
* FF and Edge: 
![chart 1](https://user-images.githubusercontent.com/8960408/46402240-7b285100-c6ff-11e8-9248-1c6ccd8b6f4b.png)
