### ISSUE TITLE
Highstock - Tooltip showing outside plot area for Y-zoomed multi-series line plot

### ISSUE THREAD

**Issue by Martin-Nyaga** [highcharts/highcharts#9108]
#### Expected behaviour
When hovering on a line plot with multiple series, and the plot is zoomed on the Y axis such that one or more of the series is not within the current visible range of the Y axis, when I hover over any of the points on the visible series, I should not see the tooltip for the series that are off the visible area showing outside the chart. Even if the tooltip is shown, it should be shown in such a way that it does not show outside of the chart area.

#### Actual behaviour
The tooltip shows outside the chart area, obstructing the navigator, and potentially any other elements below the chart.

#### Live demo with steps to reproduce
It's a little hard to explain, but here's a link to a jsFiddle showing the behaviour: http://jsfiddle.net/martinnyaga/9vxtf5nq/7/

#### Product version
Highstock 6.1.4

#### Affected browser(s)
Tested on Chrome 69 on MacOS

**Comment by Martin-Nyaga** [comment]
Thanks @pawelfus! I believe the workaround works for our needs at the moment.

**Comment by pawelfus** [comment]
*Internal note:*
Related to #7711
