### ISSUE TITLE
Highmaps: Center legend items

### ISSUE THREAD

**Issue by alexandrgorodilov** [highcharts/highcharts#9118]
#### Expected behaviour

I want to center legend items in the legend box

#### Actual behaviour

If the legend title is too long, the legend items are left aligned

#### Live demo with steps to reproduce

https://jsfiddle.net/6fjdvwxh/

#### Product version

Highmaps 6.1.4

#### Affected browser(s)

All

**Comment by KacperMadej** [comment]
Hi @alexandrgorodilov 

The github is our bugtracker, so for general support questions, please use forum / stackoverflow or email.
https://www.highcharts.com/support

The demo is showing the problem when legend title is not going to work for a chart, so title should be resolved first - changed to fit into chart e.g. by [adding breaks into title string](https://jsfiddle.net/BlackLabel/6fjdvwxh/1/) or using [responsive rules](https://api.highcharts.com/highcharts/responsive.rules) to adjust chart options.
