### ISSUE TITLE
Data labels can flow off the top of a chart

### ISSUE THREAD

**Issue by rlm1023** [highcharts/highcharts#9120]
#### Expected behaviour
If I'm going for a certain aesthetic in a column chart (always show values above the column), data labels should show up at the top of my columns.

#### Actual behaviour
Sometimes the labels run off the end of the chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/oybxa370/1/

#### Product version
Highcharts 6.1.4

#### Affected browser(s)
Chrome at least

**Comment by pawelfus** [comment]
Hi @rlm1023 

Thank you for reporting this issue.  It looks like you don't have enough space above the column in the container: http://jsfiddle.net/BlackLabel/oybxa370/10/

You can workaround the issue by enabling `maxPadding`: http://jsfiddle.net/BlackLabel/oybxa370/11/

**Comment by rlm1023** [comment]
Yeah, you can fix it that way, but you can always have long numbers that float off: http://jsfiddle.net/oybxa370/12/

In our product we're playing games with the margins to try and keep labels rendering, but that's pretty less than ideal. Would be great if there were at least an option to make room for the labels within the chart.

**Comment by pawelfus** [comment]
Good point @rlm1023  - thanks! I'm not sure about making room for dataLabels, current options (overflow+crop) should position labels inside the plotting area. If you think this option is needed, please create an idea on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api).

*Internal note:*
Demo (crop=false + overflow=justify): http://jsfiddle.net/BlackLabel/dLutv7z4/ - we have three positions for labels:
- first one is nicely aligned
- second one is clipped, didn't fit to plotting area
- third one is not justified too

Default options don't render labels at all: http://jsfiddle.net/BlackLabel/yfepa7vs/

**Comment by alirezameftahi71** [comment]
If I understand correctly, `overflow: 'justify'` is used to push data-labels inside the the plot area.
This works perfectly util I apply a rotation. ex: `rotation: 90`
Then `overflow: 'justify'` seems to be completely ineffective.
demo http://jsfiddle.net/a17osyu3/

**Comment by sebastianbochan** [comment]
Thank you @alirezameftahi71 for the additional demo.

**Comment by alirezameftahi71** [comment]
> Thank you @alirezameftahi71 for the additional demo.

Your welcome but do you accept this as a bug and will you fix this? Or is there any workaround?

**Comment by sebastianbochan** [comment]
Hi @alirezameftahi71,
I prepared you a really simple snippet which detects the edge and moves label.

Demo:
- http://jsfiddle.net/BlackLabel/2wvkex1j/
