### ISSUE TITLE
Animation is applied on chart.update even though chart.animation is set to false

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#9122]
#### Expected behaviour
When we set `chart.animation: false` and `plotOptions.series.animation: false` there should be no animation when updating chart's width.

#### Actual behaviour
There is no animation when we decrease the chart's width but the animation is applied when we increase the chart's width.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/7jwemxzv/

#### Product version
6.1.4

**Comment by pawelfus** [comment]
**Workaround:**
Disable animation in `chart.update(options, redraw, oneToOne, animation=false)`: http://jsfiddle.net/BlackLabel/nmLk3wxt/

**Comment by mir3z** [comment]
Is there any way to disable this animation in Highcharts 5?

**Comment by pawelfus** [comment]
Hi @mir3z 
See my comment above. The same should work in Highcharts v5, demo: http://jsfiddle.net/BlackLabel/nmLk3wxt/1/

**Comment by mir3z** [comment]
@pawelfus According to docs `update` method in v5 accepts only two args: 
```
update (Object options, Boolean redraw)
```

**Comment by pawelfus** [comment]
Ah, right! I didn't click the second time.. 

Anyway, I suggest to use `chart.setSize()` when setting size, not updating the whole chart: http://jsfiddle.net/BlackLabel/nmLk3wxt/2/

**Comment by khlieng** [comment]
Fixed since 8.0.4.
