### ISSUE TITLE
Halo in pie chart change size without a smooth transition when moving from one segment to another, and when the cursor is removed smoothly (nicely) from the chart.

### ISSUE THREAD

**Issue by SPavelV** [highcharts/highcharts#9123]
#### Expected behaviour
How to make the halo transition from one part (point) inside the chart to another also be smooth.

#### Actual behaviour
Halo in pie chart change size without a smooth transition when moving from one segment to another.

#### Live demo with steps to reproduce
https://yadi.sk/i/yJf7NpRAmoXVPQ

#### Product version
Highstock JS v6.1.0 (2018-04-13)

**Comment by pawelfus** [comment]
Hi @SPavelV 

Thank you for letting us know about this. There's only one halo per series, so we can not animate halo when hovering between slices (that would require one halo per slice). In your case, I think increasing and decreasing radius of the slice would be better solution, take a look: http://jsfiddle.net/BlackLabel/c5umezpL/

Snippet:
```javascript
  plotOptions: {
    pie: {
      states: {
        hover: {
          halo: {
            size: 0
          }
        }
      },
      point: {
        events: {
          mouseOver: function(e) {
            this.graphic.animate({
              r: this.shapeArgs.r + 10
            });
          },
          mouseOut: function(e) {
            this.graphic.animate({
              r: this.shapeArgs.r
            });
          }
        }
      }
    }
  },
```
In general, if you have questions, please contact our support: https://www.highcharts.com/support - this is our bug tracker.

**Comment by SPavelV** [comment]
Thanks Pavel, now it works.
