### ISSUE TITLE
Multiple Histogram series with different bin widths do not work correctly

### ISSUE THREAD

**Issue by marco-boeck** [highcharts/highcharts#9128]
#### Expected behaviour
Having 2 series with a different value range and showing a histogram for both at the same time should produce histograms that have different column widths as their bin width is different. There should not be any space between all columns of a single histogram series.

#### Actual behaviour
The visual bin width is always identical for all histogram series in a single chart, even if binWidth is different between the series (does not matter if "binsNumber" is used to auto-calculate bin width or if "binWidth" is set manually to different values per histogram).
The tooltip correctly says e.g. 4.66-5.02, but there is space between the bars of histograms with a higher bin width than the first. Hiding the first histogram makes the second appear correctly visually.

#### Live demo with steps to reproduce
Setting binWidth explicitly: https://jsfiddle.net/kge0q6Lt/1/
Using binsNumber: https://jsfiddle.net/bfh21xv0/1/

#### Product version
HighCharts 6.1.4

#### Affected browser(s)
All browsers

**Comment by marco-boeck** [comment]
Thank you, this works.
This still means I cannot use the binsNumber parameter and that I have to manually calculate the binWidth for each series (as the user will supply the bin number), but at least it's a workaround. Thank you!

**Comment by pawelfus** [comment]
I agree, it's should be set internally, without additional user actions. Once `binWidth` or `binNumber` is set, then `pointRange` should inherit this value.
