### ISSUE TITLE
Charts in columns in webkit

### ISSUE THREAD

**Issue by okohll** [highcharts/highcharts#913]
In webkit - most recent Safari and Chrome at time of writing - Safari 5.1.5 (7534.55.3) - placing two charts in a wrapper with CSS3 columns causes a display glitch where charts on the right get covered by a big white square as soon as the mouse moves over a data point, when the tooltip would usually be displayed.

Test:
1) Load test code http://jsfiddle.net/okohll/2mBx5/ in webkit
2) Resize result pane so charts are seen alongside each other in two columns
3) Move the mouse over one of the bars in the bar chart

**Comment by oysteinmoseng** [comment]
Seems to work fine with current code in current Safari and Chrome (http://jsfiddle.net/cem3dL18/).

Closing for now, as it was probably a browser bug. Feel free to reopen if this still affects people.
