### ISSUE TITLE
Incorrect point being hovered on line charts when large distance in between points

### ISSUE THREAD

**Issue by jamie-pi** [highcharts/highcharts#9132]
#### Expected behaviour
Hovering on a line chart should select the marker that has the same, or closest, x-axis position.

#### Actual behaviour
Marker/point in the wrong position on the x-axis is selected.

#### Live demo with steps to reproduce
https://jsfiddle.net/jamie_ip/h5wymuo1/
When you hover towards the bottom of the y-axis on the '2013' column, the marker that is highlighted is in '2014', despite there being points in '2013'. This seems inconsistent, especially with the crosshair enabled.

#### Product version
Highcharts 6.1.4

#### Affected browser(s)
Chrome, Firefox (All?)

**Comment by KacperMadej** [comment]
Hi @jamie-pi 

Closest point is displayed and when close to the bottom of the '2013' column the points from other 'x' columns are closer than any point from '2013'. You could disable [`stickyTracking`](https://api.highcharts.com/highcharts/series.line.stickyTracking) to prevent tooltip from showing closest point - demo: https://jsfiddle.net/BlackLabel/h5wymuo1/7/

This doesn't look like a bug and for technical support please use [Highcharts technical support](https://www.highcharts.com/support) as we are trying to keep GitHub issues for bug reports.

**Comment by jamie-pi** [comment]
Thank you. I did play around with stickyTracking but it prevents our required functionality (crosshairs always showing and closest marker always being selected). From what you have said then I guess the implementation of the hover is intended functionality and our requirement is more unique.

I will use the technical support from now on if I have any technical questions or problems. Thank you.
