### ISSUE TITLE
Missing Areas with GeoJSON map

### ISSUE THREAD

**Issue by Citriik** [highcharts/highcharts#9134]
#### Expected behaviour
The map should be displayed correctly.

#### Actual behaviour
When we load this map (GeoJSON) with this particular set of data some area are missing.

#### Live demo with steps to reproduce
JSFiddle: https://jsfiddle.net/9tk3oL1w/4/ (remove the data to see the full map)

#### Product version
Highcharts 6.1.1

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @Citriik 

For technical suport please contact [Highcharts technical support](https://www.highcharts.com/support), we are trying to keep GitHub issues for bug reports.

When contacting support please add information:
- how should the map look,
- what is missing,
- how was the map made
