### ISSUE TITLE
Vue js variable set and get properties makes chart.series[0],setData 10 times slower 

### ISSUE THREAD

**Issue by WeakMill98** [highcharts/highcharts#9135]
#### Expected behaviour
245 ms

#### Actual behaviour
2200 ms

#### Live demo with steps to reproduce

https://bpuat.edt.gov.ab.ca/export-tool

same data without Vue Js 
https://jsfiddle.net/baoshenyi/ncbhg56L/53/

1.	Destroy
                      // destroy old points
                      console.time("oldData[i].destroy");
                      i = oldDataLength;
                      while (i--) {
                          if (oldData[i] && oldData[i].destroy) {
                              oldData[i].destroy();
                          }
                      }
                      console.timeEnd("oldData[i].destroy");
2.	Redraw
                  // redraw affected series
                  console.time("redraw affected series");
                  each(series, function (serie) {
                      if ((isDirtyBox || serie.isDirty) && serie.visible) {
                          serie.redraw();
                      }
                      // Set it here, otherwise we will have unlimited 'updatedData' calls
                      // for a hidden series after setData(). Fixes #6012
                      serie.isDirtyData = false;
                  });
                  console.timeEnd("redraw affected series");

oldData[i].destroy: 777.115234375ms
highmaps.js?cdv=960000155:25880 redraw affected series: 1068.777587890625ms

#### Affected browser(s)
tested it in chrome
Hi Kamil,
I think your third point is absolute right and I found it yesterday afternoon.
“We noticed that in your Vue application you use complex objects (with getters and setters) as the data passed to Highcharts:”
Vue component adds get and set to the variables. Highmap’s destroy and redraw took longer time to handle these properties. I will try to make less properties object as a temporary solution and prefer to raise a ticket for it.

Thanks,
Shenyi

**Comment by kamilkulig** [comment]
As your demo shows: the performance of pure Highcharts library is fine. The problem is the logic of your Vue application (getters and setters are slowing the whole process down).

**Comment by WeakMill98** [comment]
Why vue component got slower when destroy and redraw function is called?

**Comment by kamilkulig** [comment]
I don't see anything like:

```
oldData[i].destroy: 777.115234375ms
highmaps.js?cdv=960000155:25880 redraw affected series: 1068.777587890625ms
```
in my browsers console. Could you correct the demo so that it prints that information? Moreover, please specify where in your project tree `highcharts.src.js` file is located.

**Comment by kamilkulig** [comment]
If everything works fine in pure Highcharts then it's Vue's fault. Please try to recreate the issue in our official Vue wrapper: https://github.com/highcharts/highcharts-vue If the same problem will occur while using the wrapper, create a new ticket here: https://github.com/highcharts/highcharts-vue/issues
