### ISSUE TITLE
Hover event in fixed-positioned container with Prototype

### ISSUE THREAD

**Issue by carneiror** [highcharts/highcharts#914]
If a chart has a fixed positioned container and we use Prototype the hover events don't work correctly after scrolling down the page.

This bug is a lot similar to Issue #208

I changed one of the examples on that issue and the problem still occurs after scrolling.

Updated fiddle: http://jsfiddle.net/W3AVn/15/

**Comment by oysteinmoseng** [comment]
Seems to work fine now.
