### ISSUE TITLE
Heatmaps using Boost are displayed incorrectly when no colorAxis bounds are set

### ISSUE THREAD

**Issue by Jilocasin** [highcharts/highcharts#9141]
#### Expected behaviour
Heatmap without explicit colorAxis boundaries (min/max) should be drawn correctly at every dataset size.
The colorAxis boundaries should be calculated automatically at every dataset size.

#### Actual behaviour
Heatmap with datasets large enough to trigger the series boost threshold (defaults to 5000) are drawn incorrectly when no explicit colorAxis boundaries are set.

#### Live demo with steps to reproduce
This can be seen in the official heatmap + boost demo when simply deleting the colorAxis min and max values.
Original: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/highcharts/boost/heatmap/
Without colorAxis min and max: http://jsfiddle.net/xwmvo89c/

#### Product version
Currently most recent Highcharts CDN version (6.1.4)

#### Affected browser(s)
Firefox 62.0.2 (64-Bit)
Chrome 69.0.3497.100 (64-Bit)

**Comment by KacperMadej** [comment]
Hi @Jilocasin 

Thank you for reporting about the boost module problem.

**Workaround:**
set `min` and `max` for `colorAxis`

_Internal note:_
FYI @cvasseng

**Comment by LaniMoo** [comment]
Is there a workaround for this other than setting the min and max? And is there an ETA on a fix? Thanks so much.

**Comment by KacperMadej** [comment]
@LaniMoo 
Another workaround could be to set `softMin` and `softMax` - demo: http://jsfiddle.net/BlackLabel/qk8tLyd6/

There's no ETA so far. Right @cvasseng ?

**Comment by pawelfus** [comment]
**Workaround:**
Demo: http://jsfiddle.net/BlackLabel/g4r5shLe/1/
Snippet:
```js
Highcharts.Series.prototype.hasExtremes = function() {
  return false;
};
```

*Internal note:*
We check extremes only for xAxis and yAxis, but for heatmap we should also check `colorAxis`.
