### ISSUE TITLE
Wrong date value in tooltip on range change

### ISSUE THREAD

**Issue by DominicSachs** [highcharts/highcharts#9145]
It seems that sometimes the tooltip for the xAxis has a wrong value (Day - 1). Please see the attached gif. This is a fiddle from your live demo.

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/stock/rangeselector/floating/

![highcharts](https://user-images.githubusercontent.com/5363927/46658758-bde0a200-cbb3-11e8-8305-3de471bde231.gif)

**Comment by KacperMadej** [comment]
Hi @DominicSachs 

Dates in inputs `From` and `To` are not precise enough to show time, so it could by any time during displayed day. It could be 1:00 am and a point is on 1:00 pm, so it doesn't fit into the currently displayed plotting area. Another issue there are weekend gaps - if `To` shows `Sep 30, 2018` then last point is from September 28th and next one is at October 1st.

This doesn't look like a bug.
For technical support please contact [Highcharts technical support](https://www.highcharts.com/support). We are using GitHub issues as bug tracker.
