### ISSUE TITLE
Highstock chart with Boost module looking strange.

### ISSUE THREAD

**Issue by bbonczek** [highcharts/highcharts#9147]
#### Expected behaviour
Boost module should render chart, when using Highstock.

#### Actual behaviour
Chart is rendered only partially, or it is very thin (not sure). There is this warning in the console:

```[.WebGL-000001EEBB82C700]RENDER WARNING: Render count or primcount is 0.```

![image](https://user-images.githubusercontent.com/11254976/46678256-85a58780-cbe4-11e8-9dc0-74e24625d49e.png)

#### Product version
"highcharts": "6.1.3",

#### Affected browser(s)
Google Chrome v. 69

#### Additional info (since there is no plunker)

Since I am using angular, this is the way I've imported boost module:

```
import * as Highstock from 'highcharts/highstock';
import * as boost from 'highcharts/modules/boost'
boost(Highstock);
```

Chart configuration looks like this:

```
public getChartOptions(): Highstock.Options {
        return {
            chart: {
                renderTo: this.trendElementRef.nativeElement,
                spacingLeft: 10,
                marginRight: 35,
                zoomType: 'x',
                animation: false,
                ignoreHiddenSeries: true,
                resetZoomButton: {
                    theme: {
                        display: 'none',
                    },
                },
            },
            colors: this.overridenColors != null ? this.overridenColors : this.colors,
            credits: {
                enabled: false,
            },
            navigator: {
                enabled: false,
            },
            boost: {
                enabled: true,
                useGPUTranslations: true,
                seriesThreshold: 1,
                debug: {
                    timeSetup: true,
                }
            } as any,
            series: {
                boostTreshold: 1,
            },
            scrollbar: {
                enabled: false,
            },
            tooltip: {
                enabled: false,
            },
            legend: {
                enabled: false,
            },
            xAxis: {
                type: 'datetime',
                tickInterval: 60000,
                crosshair: false,
            },
            yAxis: {
                opposite: false,
                offset: 10,
                labels: {
                    enabled: true,
                    format: this.numberOfDecimalPlacesFormatting,
                },
                showFirstLabel: true,
                showLastLabel: true,
                endOnTick: false,
                startOnTick: false,
            },
            title: {
                text: '',
            },
            plotOptions: {
                line: {
                    animation: false,
                    marker: {
                        enabled: true,
                    },
                },
                series: {
                    stickyTracking: false,
                    dataGrouping: {
                        enabled: false,
                    },
                    showInNavigator: false,
                    turboThreshold: 0,
                },
            } as ExtendedPlotOptions,
            rangeSelector: {
                enabled: false,
            },
        };
    }
```

Below there is a gif illustrating this issue:
![ezgif-3-dcdde9737e3e](https://user-images.githubusercontent.com/11254976/46790362-1001fe80-cd3f-11e8-9418-d7a8c461465c.gif)

**Comment by pawelfus** [comment]
Hi @bbonczek 

Could you recreate issue in plunker/jsfiddle? I have just tried to use your options in a standalone chart (no angular involved): https://jsfiddle.net/BlackLabel/c7tpfe05/2/ - this looks fine.

Chart looks different (disabled navigator) - are you sue these are the options you use? Could you also test `v6.1.4` version?

**Comment by bbonczek** [comment]
Hi,

Yes, I am sure that I am using settings I've sent - the navigator that you can see is separate chart, with it's height set to 0, so only navigator is visible. It is not using boost module, so it's not important here - I can reproduce this issue even with navigator removed. I am having troubles reproducing it in fiddler, but still not giving up :)

**Comment by pawelfus** [comment]
Thanks for clarification! Unfortunately we won't be able to debug the issue using image only. 

I guess this is caused by [`boost.useGPTTranslations`](https://api.highcharts.com/highcharts/boost.useGPUTranslations) which should be disabled if you have datetime axis. Could you try disabling this?

Another thing that comes to my mind: a few days ago we fixed similar issue (missing lines, tooltip fine), but it was related to dataGrouping (you can download master branch: https://github.highcharts.com/stock/highstock.js) which seems to be disabled in your options.

**Comment by bbonczek** [comment]
Hi,

I know it's hard to debug - I was trying to provide all information, that I think might be necessary to find the core issue, since I am not able to reproduce in fiddler (our code base is pretty large ATM, and we added bunch of custom stuff into highcharts).

My case resembles this one:
https://jsfiddle.net/c7tpfe05/5

Live data, with very often updates, usually there are more than one series in the chart. You can see that in the case send by me, there are some rendering issues - they are a bit different than what I have thought.

**The good news is disabling useGPTTranslations helped**, and chart is rendering correctly now :)

Using your master branch did not help though, but since disabling GPU translations helped it's okay :)

**Comment by bbonczek** [comment]
Also - are u sure, that [boost.useGPTTranslations](https://api.highcharts.com/highcharts/boost.useGPUTranslations) should be disabled when using datetime axis? Seems like in your first fiddle it worked (https://jsfiddle.net/BlackLabel/c7tpfe05/2/).

**Comment by pawelfus** [comment]
Thanks for confirmation!

Just like written in docs:

> This option may cause rendering issues with certain datasets. Namely, if your dataset has large numbers with small increments (such as timestamps), it won't work correctly. This is due to floating point precision.

It depends on a dataset. That is probably the reason we couldn't recreate the issue in jsFiddle. In general, when working with `datetime`-axis, `boost.useGPTTranslations` should be disabled.
