### ISSUE TITLE
Is it possible to hide the zero point in 3D column charts?

### ISSUE THREAD

**Issue by huangjun604** [highcharts/highcharts#9149]
#### Expected behaviour

The option to hide the zero point in 3D column charts.

#### Actual behaviour

There is no option to hide the zero point, and the zero point will also be drawn with color in 3D model, which is not making sense in some case. Especially to differ from other small data.

#### Live demo with steps to reproduce

The offical example is here: https://www.highcharts.com/demo/3d-column-null-values

Related code is here:

https://github.com/highcharts/highcharts/blob/80fb71a2241a2dafe1dac5af587804ee7afc5ac3/js/parts-3d/Column.js#L109
https://github.com/highcharts/highcharts/blob/80fb71a2241a2dafe1dac5af587804ee7afc5ac3/js/parts-3d/Column.js#L188

#### Product version

Highcharts v6.0.3

**Comment by sebastianbochan** [comment]
Hi @huangjun604,
It is not a bug, its default functionality that zero points are draw and only null point are not visible. 
The solution is replace zero points with null values in the preprocessing.

```
var each = Highcharts.each,
    seriesInput = [{
        data: [2, 3, null, 4, 0, 5, 1, 4, 6, 3]
    }],
    series = [],
    index;
   
   
each(seriesInput, function (serie) {
    index = series.push({
    	data: []
    });
    
    each(serie.data, function (point) {
    	series[index - 1].data.push({
      	y: point === 0 ? null : point
      });
    });
});
```

Example:
- https://jsfiddle.net/BlackLabel/1uLjpn7h/

or use a workaround with setting really small `threshold` and transparent `negativeColor`
- https://jsfiddle.net/BlackLabel/g8Ls07qc/
