### ISSUE TITLE
Heatmaps are half plotted on browsers with webgl disabled

### ISSUE THREAD

**Issue by ff-sgupta** [highcharts/highcharts#9150]
#### Expected behaviour
The heatmap shuld be completely rendered

#### Actual behaviour
The heatmap is half plotted. If we remove the boost-canvas module then the chart is plotted correctly. However for large points, the performance is slow

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/heatmap-canvas/

#### Product version
Highcharts 6.1.4

#### Affected browser(s)
Any browser with webgl disabled. I had disable webgl on Firefox

Type about:config in address bar. Search for webgl.disabled and turn it off

**Comment by pawelfus** [comment]
Hi @ff-sgupta 

Thank you for reporting the issue. You are right, it looks broken:

![screen shot 2018-10-10 at 13 05 12](https://user-images.githubusercontent.com/1453926/46732211-2780af00-cc8d-11e8-8c6c-e56b187318f3.png)

**Comment by ff-cviradiya** [comment]
@pawelfus This was working fine when we were in the old highcharts version 5.0.12.

**Comment by ff-sgupta** [comment]
@pawelfus Thanks for the response. By when are we expecting this to be fixed?

**Comment by pawelfus** [comment]
**Workaround:**
Position canvas manually, demo: https://jsfiddle.net/BlackLabel/79tmxrn8/2/

Snippet:
```javascript
function reflowCanvas () {
	var chart = this;
	Highcharts.each(this.series, function (series) {
  	if (series.renderTarget) {
    	series.renderTarget.attr({
      	x: chart.plotLeft,
        y: chart.plotTop
      });
    }
  });
}

Highcharts.addEvent(Highcharts.Chart, 'redraw', reflowCanvas);
Highcharts.addEvent(Highcharts.Chart, 'load', reflowCanvas);
```

@ff-sgupta Hopefully it will get into the next release.

**Comment by ff-sgupta** [comment]
@pawelfus The workaround does not seem to work for inverted heatmaps

Inverted heatmap with webgl disabled
![inverted_heatmap_webgl_disabled](https://user-images.githubusercontent.com/644292/46995099-dc571800-d134-11e8-8029-63a14130cce3.png)

Inverted heatmap with webgl enabled
![inverted_heatmap_webgl_enabled](https://user-images.githubusercontent.com/644292/46995122-eed15180-d134-11e8-9d47-8928703ab652.png)

**Comment by pawelfus** [comment]
Hi @ff-sgupta 

Thank you for pointing this out! It looks like a separate issue, but let's keep it here.

*Internal note:*
@oysteinmoseng / @TorsteinHonsi FYI:
We have simple translation for canvas-boost here:
https://github.com/highcharts/highcharts/blob/6f5df755f0589df601ad3d3f09057a74f1fdbf88/js/modules/boost-canvas.src.js#L61-L66
However, WebGL boost adds logic for inverted heatmap:
https://github.com/highcharts/highcharts/blob/6f5df755f0589df601ad3d3f09057a74f1fdbf88/js/modules/boost.src.js#L1682-L1692

I tried something similar: 

```javascript
if (inverted) {
    ctx.fillRect(
        yAxis.len - shapeArgs.y,
        xAxis.len - shapeArgs.x + xAxis.top,
        shapeArgs.height,
        shapeArgs.width
    );
} else {
    ctx.fillRect(
        shapeArgs.x + xAxis.left,
        shapeArgs.y + yAxis.top,
        shapeArgs.width,
        shapeArgs.height
    );
}
```

Note swapped `x` with `y`, but it looks the translation is a bit off: 

- canvas-2d:
![screen shot 2018-10-16 at 14 10 05](https://user-images.githubusercontent.com/1453926/47015450-509db580-d14d-11e8-9bb9-96761b6a0280.png)

- svg and/or canvas-3d:
![screen shot 2018-10-16 at 14 10 13](https://user-images.githubusercontent.com/1453926/47015459-572c2d00-d14d-11e8-8086-5c1ad2478d08.png)

Short debugging leads to interesting thing: `shapeArgs.x` are in <0, plotWidth> px range (correct), but `shapeArgs.y` are in range <0, plotWidth - A>, where A is some random number, thus this extra offset at the beginning (`hcy` and `hcx` are just arrays of `shapeArgs.x` and `shapeArgs.y`): 

![screen shot 2018-10-16 at 14 18 11](https://user-images.githubusercontent.com/1453926/47015827-5b0c7f00-d14e-11e8-8b75-27bc6694c764.png)

**Comment by ff-sgupta** [comment]
Thank you for the fix

**Comment by pawelfus** [comment]
Issue with inverted chart has a separate issue: #9211
