### ISSUE TITLE
DotNet Highcharts: Series click event handlers are broken (6.1.1.65)

### ISSUE THREAD

**Issue by ThePaSch** [highcharts/highcharts#9159]
Using the latest version of DotNet.Highcharts (NuGet 6.1.1.65), adding a "Click" event handler to any series on any chart type results in broken JavaScript code, which causes the click event to not properly function. 

I am using the Html.Highsoft().GetHighchartsJS method in my view to render the chart to an identified container. The generated javascript code defines the click event handler in the chart's series options, but instead of inserting the parameters given in my factory as javascript code, it instead inserts them as a string:

**BasicBarChartFactory**

```
public class BasicBarChartFactory : IHighchartFactory<BasicBarChartData>
    {
        public Highcharts GetChart(BasicBarChartData data, ChartMetaData metaData)
        {
            Highcharts basicBarChart = new Highcharts
            {
                Title = new Title
                {
                    Text = metaData.Title
                },

                Credits = new Credits
                {
                    Enabled = false
                },

                Subtitle = new Subtitle
                {
                    Text = metaData.Subtitle
                },

                XAxis = new List<XAxis>
                {
                    new XAxis
                    {
                        Type = XAxisType.Category
                    }
                },

                YAxis = new List<YAxis>
                {
                    new YAxis
                    {
                        Min = 0,
                        Title = new YAxisTitle
                        {
                            Text = null
                        }
                    }
                },

                PlotOptions = new PlotOptions
                {
                    Column = new PlotOptionsColumn
                    {
                        PointPadding = 0.2,
                        BorderWidth = 0,
                        Label = new PlotOptionsColumnLabel
                        {
                            Enabled = false
                        }
                    }
                },

                Legend = new Legend
                {
                    Enabled = false
                },

                Series = new List<Series>
                {
                    new ColumnSeries
                    {
                        Name = "Count",
                        ColorByPoint = true,
                        Data = data.ColumnSeriesData,
                        Events = new ColumnSeriesEvents
                        {
                            Click = "function(e) { chartImplicitFilter(e.point.name, \"" + metaData.FilterColumn + "\") }"
                        }
                    }
                },

                Responsive = new Responsive
                {
                    Rules = new List<ResponsiveRules>
                    {
                        new ResponsiveRules
                        {
                            Condition = new ResponsiveRulesCondition
                            {
                                MaxWidth = metaData.MaxWidth ?? 8000
                            }
                        }
                    }
                }
            };

            return basicBarChart;
        }
    }
```

**Javascript code generated by Highsoft.Highcharts**

`
var ChartOptions = {"xAxis":[{"type":"category"}],"chart":{"renderTo":"DevicesByLastScannedColumnChart"},"yAxis":[{"title":{"text":null},"min":0}],"title":{"text":"No. of devices by last scan date"},"subtitle":{"text":null},"legend":{"enabled":false},"credits":{"enabled":false},"series":[{"name":"Count","events":{"click":"function(e) { chartImplicitFilter(e.point.name, \"LastScan\") }"},"type":"column","colorByPoint":true,"data":[{"name":"19.04.2018","y":1},{"name":"07.05.2018","y":1},{"name":"24.04.2018","y":1},{"name":"18.04.2018","y":1},{"name":"25.07.2018","y":1},{"name":"25.04.2018","y":1},{"name":"11.04.2018","y":1},{"name":"17.04.2018","y":1},{"name":"12.04.2018","y":1},{"name":"23.04.2018","y":1},{"name":"29.04.2018","y":1},{"name":"08.05.2018","y":1},{"name":"09.05.2018","y":2},{"name":"26.07.2018","y":3},{"name":"14.05.2018","y":3},{"name":"10.05.2018","y":3},{"name":"16.04.2018","y":3},{"name":"15.05.2018","y":4},{"name":"11.05.2018","y":5},{"name":"18.05.2018","y":13},{"name":"17.05.2018","y":46},{"name":"16.05.2018","y":85}]}],"responsive":{"rules":[{"condition":{"maxWidth":8000}}]},"plotOptions":{"column":{"pointPadding":0.2,"borderWidth":0,"label":{"enabled":false}}}};new Highcharts.chart("DevicesByLastScannedColumnChart",ChartOptions);
`

As you can see, the "events" key of the chart's "series" member has an object with a key of "click", and a **string** of the function I passed in the factory for a value. When clicking, Highcharts' event handler thus tries to call a string, which results in a TypeError:

```
Uncaught TypeError: c.call is not a function
    at highcharts.js:31
    at Array.forEach (<anonymous>)
    at Object.a.each (highcharts.js:28)
    at a.fireEvent (highcharts.js:31)
    at a.Pointer.onContainerClick (highcharts.js:204)
    at HTMLDivElement.c.onclick (highcharts.js:205)
```

#### Expected behaviour

The Highsoft.Highcharts .NET library inserts the value given in the `ColumnSeriesEvents.Click` into the generated javascript code as code (without quotation marks), allowing the function to be called by the JS library's event handler.

#### Actual behaviour

The Highsoft.Highcharts .NET library inserts the value given in the `ColumnSeriesEvents.Click` into the generated javascript code as a string (with quotation marks), causing a TypeError in the JS library's event handler since it's trying to call a string.

#### Product version

Highsoft.Highcharts 6.1.1.65

This is a time-critical issue. The fix can't be very complicated; if you'd like proof of license purchase, I can provide it.

**Comment by sebastianbochan** [comment]
Hi @ThePaSch,
I have passed your case to our .NET developer. He will answer you here, as soon as possible.

**Comment by brofixo** [comment]
@ThePaSch Assign to `ColumnSeriesEvents.Click` only function name and place function in JS in view file.

**Comment by ThePaSch** [comment]
Hi @brofixo,

thanks for your response.

For my use-case, this unfortunately won't work. This behavior, if I'm correct, does not support anonymous functions like most other event/callback properties - including, actually, the Chart Click event, which implements the exact behavior I was expecting the Series Click event to implement as well (inserts the given value into the javascript code without quotes, making the use of anonymous/non-named functions possible).

Would it not be possible to adjust this? Backwards-compatibility is still maintained one way or the other, since users who have only assigned the function name to `ColumnSeriesEvent.Click` will not have their functionality impaired, even with the same code, while users who wish to utilize anonymous functions will now have the ability to do so. It won't take away from anything.

**Comment by brofixo** [comment]
@ThePaSch It will be adjusted by Monday.

Also I have a question :) Why do you name it DotNet Highcharts if official
name is Highcharts.NET and package on NuGet has name Highsoft.Highcharts?

Daniel Drwięga

śr., 17.10.2018, 11:19 użytkownik ThePaSch <notifications@github.com>
napisał:

**Comment by ThePaSch** [comment]
Hi @brofixo,

thanks a lot for your quick responses and the good support!

It's mostly a matter of habit. Before Highcharts.NET was available, the only .NET wrapper for the Highcharts.js library was an unofficial one called DotNet Highcharts, which I made use of once in the past.

**Comment by KacperMadej** [comment]
Closing as resolved
