### ISSUE TITLE
Highstock "overscroll" setting causing xAxis formatting issue

### ISSUE THREAD

**Issue by gbenthomas** [highcharts/highcharts#9160]
#### Expected behaviour
xAxis labels should be formatted the same as when there is no overscroll set

#### Actual behaviour
xAxis labels show hours, minutes, and seconds (instead of just hours and minutes) and too many labels are rendered which causes them to be oriented diagonally and take up too much space on the chart. It's also very difficult to read.

The labels generally format themselves correctly after the user zooms or more data is added to the chart.

![image](https://user-images.githubusercontent.com/35936423/46817375-9b31c300-cd44-11e8-8a88-de5dc2733046.png)

#### Live demo with steps to reproduce

This jsfiddle captures the issue. It's meant to be a "snapshot" of the real time data. 

http://jsfiddle.net/2rst0c7h/

#### Product version
Highstock v6.1.4

#### Affected browser(s)
Reproduced in Chrome and Firefox. Did not test other browsers

**Comment by gbenthomas** [comment]
Hi @pawelfus 

Thanks for the workaround and quick response! Just another question because I couldn't find anything about this in the documentation. Do I need to remove this event manually or does chart.destroy() take care of the cleanup?

**Comment by pawelfus** [comment]
Event is bound to the prototype of the `Highcharts.Axis` class, so no need to remove it.
