### ISSUE TITLE
Can't deactivate boost module

### ISSUE THREAD

**Issue by bbonczek** [highcharts/highcharts#9164]
#### Expected behaviour

From [boost module docs](https://www.highcharts.com/docs/advanced-chart-features/boost-module):

> The intended way of using the module, is to set thresholds in such a way that the SVG-renderer “takes over” rendering when zooming in. This approach gives the expected interactivity when the points are less dense, coupled with high performance when the point density is high.

In fidlder below I've set boostTreshold to 15. When I zoom into the area, where there are less then 15 points visible, boost module should be deactivated, and markers should become visible.

Same thing should happen if I click "Disable boost module" button.

#### Actual behaviour
Seems like there is no way to disable boost module, once it is triggered.

#### Live demo with steps to reproduce
https://jsfiddle.net/c7tpfe05/6/

#### Product version
Highstock 6.1.4

#### Affected browser(s)
Chrome 69

**Comment by pawelfus** [comment]
Hi @bbonczek 

Sorry for a late reply! For me it looks wrong, could you confirm @cvasseng ?
