### ISSUE TITLE
Cannot remove all space from the chart

### ISSUE THREAD

**Issue by meltingice1337** [highcharts/highcharts#9165]
#### Expected behaviour
Hello there, I'm trying to get the chart to be full height (without legend, axes, title, only the bars) but i cant seem to get it right, there always is that space as show in the image below
![chrome_2018-10-12_13-24-12](https://user-images.githubusercontent.com/10818970/46864212-52503c00-ce22-11e8-9419-7beedd11b289.png)

#### Config used
```ts
export const HighchartsBarConfig: Higcharts.Options = {
  chart: {
    margin: 0,
    showAxes: false,
    spacing: [0, 0, 0, 0],

    height: null,
    type: 'bar',
    width: null,
  },
  credits: {
    enabled: false
  },
  exporting: {
    enabled: false
  },
  legend: {
    enabled: false,
    itemDistance: 0,
    reversed: true
  },
  plotOptions: {
    series: {
      dataLabels: {
        crop: false,
        enabled: true,
        overflow: 'allow',
        style: { textOverflow: 'ellipsis' },
        useHTML: true
      }
    }
  },
  series: [{
    data: [200],
    name: 'John',
  }, {
    data: [50],
    name: 'Jane',
  }, {
    data: [40],
    name: 'Joe'
  }],
  title: {
    margin: 0,
    text: null
  },
  tooltip: {
    enabled: false
  },
  xAxis: {
    lineWidth: 0,
    visible: false
  },
  yAxis: {
    lineWidth: 0,
    visible: false
  },
}
```
#### Product version
Highcharts.js 6.1.4

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @meltingice1337 

Thanks for contacting us. This is our bug tracker, as for questions please use our other [support channels](https://www.highcharts.com/support).

PS: You can control this by [`series.groupPadding`](https://api.highcharts.com/highcharts/series.column.groupPadding) and [`series.pointPadding`](https://api.highcharts.com/highcharts/series.column.pointPadding).
