### ISSUE TITLE
When chart is zoomed in in boost mode, points accumulate on right side of the chart

### ISSUE THREAD

**Issue by bbonczek** [highcharts/highcharts#9166]
#### Expected behaviour
When zoomin in in boost mode overflowed data points should disappear completely.

#### Actual behaviour
When zoomin in in boost mode, overflowed data points are accumulating on the right side of the screen.

#### Live demo with steps to reproduce
https://jsfiddle.net/c7tpfe05/13/

#### Product version
Highcharts 6.1.4

#### Affected browser(s)
Chrome, Firefox

![image](https://user-images.githubusercontent.com/11254976/46866193-b07c1f80-ce20-11e8-8441-4bc509469bdd.png)

**Comment by sebastianbochan** [comment]
Hi @bbonczek,
Thank you for reporting. It looks like a bug with adding new point in the boost module.

@cvasseng

**Comment by bbonczek** [comment]
Hi,

I've just tried it again with highcharts 6.2.0, and seems like this issue is still appearing - are there any plans on fixing this issue soon?

**Comment by KacperMadej** [comment]
Hi @bbonczek 

There's no ETA currently.

@cvasseng Any comments?

**Comment by jon-a-nygaard** [comment]
@cvasseng is currently out of office, he will take a look at this issue as soon as he is back, most likely at the end of this week.

**Comment by bbonczek** [comment]
Hi,

Did u have a chance to have a look at this issue? :)

**Comment by cvasseng** [comment]
Sorry for the delay.

A pull request has been added. It will be merged into master once it passes review, and will be part of the next release.

The fix can be previewed here: https://jsfiddle.net/14Lh9vy8/

Please feel free to re-open this issue or submit a new one if necessary.
