### ISSUE TITLE
DotNet.Highcharts Rotation in X(Y)AxisTitle doesn't set '0' value

### ISSUE THREAD

**Issue by aodarenko** [highcharts/highcharts#9171]
I try to create horizontal title on xAxis in **inverted** chart. But DotNet.Highcharts think that rotation=0 is default value for all cases (I know that I can set value to 360), and as result DotNet.Highcharts library are skiped this property in JSON object.

#### Expected behaviour
For inverted charts. Default values of axis title rotation must be swapped between xAxis and yAxis. 

#### Actual behaviour
Default values of axis title rotation do not changes when chart used "inverted: true"

**Comment by KacperMadej** [comment]
Resolved through Highcharts .NET internal issue
