### ISSUE TITLE
Dragdrop should indicate the value it is currently dragging to

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#9174]
When dragging it is useful to see which value we are dragging to. Currently the tooltip is updating, but it is not reliably showing while dragging - i.e. the tooltip sometimes disappears while dragging.

#### Live demo with steps to reproduce
http://jsfiddle.net/1pm7o3Lj/

**Comment by pawelfus** [comment]
It's probably connected to `directTouch` for columns (dragging down - fine, dragging up - missing tooltip). For example `tooltip.shared` resolves the issue: http://jsfiddle.net/BlackLabel/1pm7o3Lj/2/
