### ISSUE TITLE
[Highstock]addPoint in candlestick does not refresh the navigator preview

### ISSUE THREAD

**Issue by george77** [highcharts/highcharts#918]
addPoint in candlestick does not refresh the navigator preview, the labels in the navigator get updated, but the series preview remains the same, or in some other cases which i can not reproduce, new data are represented as white blanks

http://jsfiddle.net/JNqTf/10/

**Comment by pawelfus** [comment]
It's a problem with reusing `data` variable which modifies data. It's a reference (not a copy), use separate object/array instead: http://jsfiddle.net/BlackLabel/JNqTf/22/

Otherwise, navigator picks `data` again on adding a point, which has modified previously last point.
