### ISSUE TITLE
How do I create a draggable plotline in Highcharts?

### ISSUE THREAD

**Issue by VasiliyPolyakov** [highcharts/highcharts#9185]
#### Expected behaviour

I couldn't find info about this. See please screenshot. You will see a green line on the screenshot. This plotline must be oriented on xAxis and draggable with max and min value on the axis Х. Can you help me? maybe some suggestion or link to official docs. Thank you in advance.

screenshot and a short video with this issue You can find in this issue on StackOverflow

https://stackoverflow.com/questions/52834831/how-do-i-create-a-draggable-plot-line-in-highcharts

**Comment by pawelfus** [comment]
Hi @VasiliyPolyakov 

This is our bug tracker. For questions please use StackOverflow, our forum or contact us by email: https://www.highcharts.com/support

PS: To answer your question: you can use simple line series with draggable points plugin: https://github.com/highcharts/draggable-points/

In upcoming Highcharts 7 it will be available through annotations module too.

**Comment by VasiliyPolyakov** [comment]
Ok, I got it! Thank you
