### ISSUE TITLE
Area chart: small height, no data results in JS errors

### ISSUE THREAD

**Issue by pimskie** [highcharts/highcharts#9200]
#### Expected behaviour
Expected an empty chart without JS errors.

#### Actual behaviour
An empty chart with JS errors.

#### Live demo with steps to reproduce
It looks like the following combination results in JS errors: 
no data + chart type `area` + chart height < 95px + setting `negativeColor`   

 *Working*: 
* chart height: < 95px
* data: yes
* property `negativeColor`  set: yes
* No JS errors: https://jsfiddle.net/ts4jbocm/1/  

*working*: 
* chart height: > 95px
* data: no
* property `negativeColor`  set: yes
* No JS errors:  https://jsfiddle.net/29ufxaqh/1/

*breaking*: 
* chart height: < 95px
* data: no
* property `negativeColor`  set: yes
* JS errors: https://jsfiddle.net/hyxzvnbe/1/

*working*: 
* chart height: < 95px
* data: no
* property `negativeColor`  set: no
* No JS errors: https://jsfiddle.net/cz9a7yLp/

#### Product version
Highstock: https://code.highcharts.com/stock/highstock.js
v6.1.4 (2018-09-25)

#### Affected browser(s)
- Chrome, FF

**Comment by pawelfus** [comment]
Hi @pimskie 

Thanks for reporting this bug.

**Workaround:**
Don't use `negativeColor` on a small empty chart. Instead use `series.update({ .. });` to set this once data is available. Or create chart **without** series and later use `chart.addSeries({ ... });`.

*Internal note:*
Simplified demo: https://jsfiddle.net/BlackLabel/hyxzvnbe/5/

**Comment by pimskie** [comment]
Thanks for the quick reply @pawelfus 
The `series.update({ .. });` workaround when data comes is works.

**Comment by pawelfus** [comment]
Thanks for the info! Let's keep this open - this should be fixed in the core.
