### ISSUE TITLE
highstock present null integer values as their index 

### ISSUE THREAD

**Issue by ArielKr** [highcharts/highcharts#9204]
#### Expected behaviour

xAris with null value will be displaed as null.
#### Actual behaviour
It shows bar index, that looks like one of the values

#### Live demo with steps to reproduce

https://jsfiddle.net/v1gc0udp/2/

**Comment by pawelfus** [comment]
Hi @ArielKr 

Thanks for reporting the issue. This is expected behaviour - when no category name is provided, then index of the point is used. If you want to use `null`, then set it as string: `'null'`: https://jsfiddle.net/BlackLabel/v1gc0udp/3/
