### ISSUE TITLE
Sort items in JSON file

### ISSUE THREAD

**Issue by brofixo** [highcharts/highcharts#9207]
#### Expected behaviour
Items in JSON file are sorted - specially items in `children`.

#### Actual behaviour
Items in JSON file are not sorted. They seem to be randomly located in JSON.

**Comment by brofixo** [comment]
It is about https://api.highcharts.com/highcharts/tree.json. I use it to
create .NET wrapper and it is really helpful if items are sorted. I was
talking about it with @sophie and she asked me to create this task and
assign it to her, but I don't have privileges here to do that.

Daniel Drwięga

czw., 18.10.2018, 09:22 użytkownik Torstein Hønsi <notifications@github.com>
napisał:

**Comment by bre1470** [comment]
This has been fixed.
