### ISSUE TITLE
Boost - inverted heatmap has wrong dimensions when WebGL is disabled

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#9211]
#### Expected behaviour
Correct inverted chart when WebGL is disabled

#### Actual behaviour
Chart is misplaced

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/79tmxrn8/13/

#### Details:
We have simple translation for canvas-boost here:
https://github.com/highcharts/highcharts/blob/6f5df755f0589df601ad3d3f09057a74f1fdbf88/js/modules/boost-canvas.src.js#L61-L66
However, WebGL boost adds logic for inverted heatmap:
https://github.com/highcharts/highcharts/blob/6f5df755f0589df601ad3d3f09057a74f1fdbf88/js/modules/boost.src.js#L1682-L1692

I tried something similar: 

```javascript
if (inverted) {
    ctx.fillRect(
        yAxis.len - shapeArgs.y,
        xAxis.len - shapeArgs.x + xAxis.top,
        shapeArgs.height,
        shapeArgs.width
    );
} else {
    ctx.fillRect(
        shapeArgs.x + xAxis.left,
        shapeArgs.y + yAxis.top,
        shapeArgs.width,
        shapeArgs.height
    );
}
```

Note swapped `x` with `y`, but it looks the translation is a bit off: 

- canvas-2d:
![screen shot 2018-10-16 at 14 10 05](https://user-images.githubusercontent.com/1453926/47015450-509db580-d14d-11e8-9bb9-96761b6a0280.png)

- svg and/or canvas-3d:
![screen shot 2018-10-16 at 14 10 13](https://user-images.githubusercontent.com/1453926/47015459-572c2d00-d14d-11e8-8086-5c1ad2478d08.png)

Short debugging leads to interesting thing: `shapeArgs.x` are in <0, plotWidth> px range (correct), but `shapeArgs.y` are in range <0, plotWidth - A>, where A is some random number, thus this extra offset at the beginning (`hcy` and `hcx` are just arrays of `shapeArgs.x` and `shapeArgs.y`): 

![screen shot 2018-10-16 at 14 18 11](https://user-images.githubusercontent.com/1453926/47015827-5b0c7f00-d14e-11e8-8b75-27bc6694c764.png)

It's a part of #9150

**Comment by ff-sgupta** [comment]
By when can we expect a fix for this issue?

**Comment by ff-sgupta** [comment]
By when can we expect this issue to be fixed?

**Comment by ff-rboutotte** [comment]
Here are the code changes that I have that make this work for us with v5.0.x, not sure if other changes are needed for newer version, but hopefully this will allow this issue to get fixed sooner....

Replace lines 289 - 310 with these lines:
```
                    if (chart.inverted) {
                        if (target.canvas.width !== height) {
                            target.canvas.width = height;
                        }

                        if (target.canvas.height !== width) {
                            target.canvas.height = width;
                        }

                        target.image.attr({
                            x: 0,
                            y: 0,
                            width: height,
                            height: width,
                            style: 'pointer-events: none'
                        });

                        target.boostClipRect.attr({
                            x: 0,
                            y: 0,
                            width: chart.chartHeight,
                            height: chart.plotWidth
                        });

                    }
                    else {
                        if (target.canvas.width !== width) {
                            target.canvas.width = width;
                        }

                        if (target.canvas.height !== height) {
                            target.canvas.height = height;
                        }

                        target.image.attr({
                            x: 0,
                            y: 0,
                            width: width,
                            height: height,
                            style: 'pointer-events: none'
                        });

                        target.boostClipRect.attr({
                            x: 0,
                            y: 0,
                            width: chart.plotWidth,
                            height: chart.chartHeight
                        });
                    }
```

**Comment by pawelfus** [comment]
Thanks @ff-rboutotte for sharing! @ff-sgupta no ETA at this moment.

**Comment by ff-sgupta** [comment]
@pawelfus One possible solution

refering boost-canvas.src.js - https://github.com/highcharts/highcharts/blob/master/js/modules/boost-canvas.src.js

Replace line 63-68 
```
ctx.fillRect(
       shapeArgs.x + plotLeft,
       shapeArgs.y + plotTop,
       shapeArgs.width,
       shapeArgs.height
);

```
with
```
                             if(point.series.chart.inverted) {
                                    ctx.fillRect(
                                        point.series.chart.yAxis[0].len - shapeArgs.y + plotLeft,
                                        point.series.chart.xAxis[0].len - shapeArgs.x + plotTop,
                                        shapeArgs.height,
                                        shapeArgs.width
                                    );
                                }else {
                                    ctx.fillRect(
                                        shapeArgs.x + plotLeft,
                                        shapeArgs.y + plotTop,
                                        shapeArgs.width,
                                        shapeArgs.height
                                    );
                                }
```

**Comment by pawelfus** [comment]
Hi @ff-sgupta 

Thank you! I have tried this before, it's not a correct solution: 

![screen shot 2018-10-23 at 13 54 08](https://user-images.githubusercontent.com/1453926/47358817-30c93d00-d6cb-11e8-9f2f-d7969a798898.png)

Tested with: http://jsfiddle.net/79tmxrn8/18/ (lines 81-94).

**Comment by ff-rboutotte** [comment]
So further debugging the following code fixes the last issue from what I can tell:
<img width="762" alt="screen shot 2018-10-23 at 8 19 25 pm" src="https://user-images.githubusercontent.com/6979875/47369297-01cdbe00-d701-11e8-941e-d02707eb53f2.png">

```
if(point.series.chart.inverted) {
    ctx.fillRect(
        point.series.chart.yAxis[0].len - shapeArgs.y + plotLeft,
        point.series.chart.xAxis[0].len - shapeArgs.x + plotTop,
        -shapeArgs.height,
        -shapeArgs.width
    );
}else {
    ctx.fillRect(
        shapeArgs.x,
        shapeArgs.y,
        shapeArgs.width,
        shapeArgs.height
    );
}
```

**Comment by pawelfus** [comment]
Thanks @ff-rboutotte - your code looks good! Implemented and PR'ed.
