### ISSUE TITLE
Feature request - Can themed sass be included in the NPM package?

### ISSUE THREAD

**Issue by whawker** [highcharts/highcharts#9214]
It's very useful that Highcharts includes the Sass file `css/highcharts.scss` in the NPM package.

Would it be possible to also include the Sass files for the themes as well (i.e. Dark Unica) in the NPM module too?

**Comment by sebastianbochan** [comment]
Hi @whawker,
Thank you for contacting us. Its really good suggestion and I will notify our NPM publishers about it.

@jon-a-nygaard
