### ISSUE TITLE
Reversing labels array results in values not text being displayed on axis

### ISSUE THREAD

**Issue by LoranHayden** [highcharts/highcharts#9223]
#### Expected behaviour
I have an array of
```
dates = [ {value: 7, text: "10/19"},
{value: 6, text: "10/18"},
{value: 5, text: "10/17"},
{value: 4, text: "10/16"},
{value: 3, text: "10/15"},
{value: 2, text: "10/14"},
{value: 1, text: "10/13"}]
```
And I find that when I use it as: 
```
chart1.addAxis("x",
{
   labels: dates
});
```

the x-axis labels **do not show the text** but show the value instead
if I use the same array but call **reverse** on it then the text values appear properly

```
chart1.addAxis("x",
{
   labels: dates.reverse()
});
```

**Comment by sebastianbochan** [comment]
Hi @LoranHayden,
This is our tracker to reporting bugs. For general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

p.s You should use [categories](https://api.highcharts.com/highcharts/xAxis.categories) which allows you to declare axis labels as strings.
