### ISSUE TITLE
Highcharts 7 - remove abstractions for array functions like forEach etc.

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#9225]
Until now we have kept abstractions for array functions like `forEach`, `map`, `filter` etc to avoid using polyfills for legacy browsers, that can induce bugs in unrelated code.

From Highcharts 7 we will remove those abstractions (`Highcharts.each`, `Highcharts.map` etc.) and provide workarounds for those who still need to support IE8. Either we demonstrate how to use a third party polyfill library, or we make our own polyfills that are part of `modules/oldie.js`. In case we make our own, they should probably be disabled by default, and enabled one by one through an option. 

## To do
 - [x] Replace `H.each` with `[].forEach`.
 - [x] Replace `H.map` with`[].map`.
 - [x] Replace `H.grep` with `[].filter`.
 - [x] Replace `H.reduce`.
 - [x] Replace `H.some`.
 - [x] Replace `H.inArray` with `[].indexOf`.
 - [x] Replace `H.keys` with `Object.keys`.
 - [x] Set up option structure and polyfills in oldie.js. Add demo.
 - [x] Set up demo with third party polyfills.
 - [x] Simplify and generalize the abstractions in Utilities.js. They are probably in use by many implementations and plugins.

**Comment by TorsteinHonsi** [comment]
`H.each` to `forEach`: aa3c02972762b5274ad7c3fe5c8f2ba93ba8fb78

**Comment by yuisakov** [comment]
InArray is still used https://github.com/highcharts/highcharts/blob/2de58a663e1734084dd7f90d75ae0b6dd81de87a/js/modules/accessibility/components/AnnotationsA11y.js#L124

Using 8.1.1 see the following error in console:
![1](https://user-images.githubusercontent.com/17232794/84561389-c9795a00-ad00-11ea-8039-e74308ab73c2.png)

**Comment by pawelfus** [comment]
FYI @oysteinmoseng @TorsteinHonsi

**Comment by sebastianbochan** [comment]
Hi @yuisakov,
Thank you for the feedback.

FYI @oysteinmoseng
