### ISSUE TITLE
After updating series with indexes one is omitted

### ISSUE THREAD

**Issue by yunicz** [highcharts/highcharts#9226]
#### Expected behaviour
I have a chart and I would like to update it's series. Each serie has got ID and INDEX specified. After data is fetched from server and chart.update() is called series are updated because each has its unique ID.

#### Actual behaviour
After calling chart.update() one of the new series is ignored. Check attached fiddle. This happens if series in array are not sorted by index param.

#### Live demo with steps to reproduce
https://jsfiddle.net/wn2br6pf/

1, open fiddle
2, click button
3, chart contains only 3 series 

#### Product version
 Highcharts JS v6.2.0

#### Affected browser(s)
Chrome, Firefox

**Comment by sebastianbochan** [comment]
Hi @yunicz,
Thank you for reporting.

**Workaround:**
- Remove all series before update.

Demo:
- https://jsfiddle.net/BlackLabel/46t0udoa/

**Internal note:**
It looks like a problem with `oneToOne` param which does not map indexes properly. When we disable this param, update is the same.

**Comment by pawelfus** [comment]
*Internal note:*
Probably caused by these lines:
https://github.com/highcharts/highcharts/blob/76842291e846d41de8027ebc848117cc5986f5ca/js/parts/Dynamics.js#L510-L512

Probably should be `indexMap.push(pick(s.options.index, i))`.
