### ISSUE TITLE
Funnel : inside is not working and when it is inside it is still bold despite fontWeight: normal

### ISSUE THREAD

**Issue by DK-Unit4** [highcharts/highcharts#9234]
#### Expected behaviour
1. Data label is inside
2. Font is not bold

#### Actual behaviour
1. In version 6.1.14 the label is inside but bold
2. in sample below the data label is not inside (6.2)

#### Live demo with steps to reproduce
https://jsfiddle.net/Kumlander/hbrcpuwj/3/

note I use inside and use style for data label

#### Product version
highcharts 6.2 and 6.1.4

#### Affected browser(s)
Chrome at least

**Comment by pawelfus** [comment]
Hi @DK-Unit4 

Thank you fro reporting the issue. I'm not sure if it's not a bug in funnel documentation, as `inside` option is not implemented for funnel (neither for pie chart: http://jsfiddle.net/BlackLabel/h0kj9zcf/). These series (pie, funnel) have [`series.dataLabels.distance`](https://api.highcharts.com/highcharts/series.funnel.dataLabels.distance) option which replaces `inside` option: https://jsfiddle.net/BlackLabel/hbrcpuwj/6/

Are you sure it used to work in v6.1.4? Just tried and it looks the same: https://jsfiddle.net/BlackLabel/hbrcpuwj/10/

**Comment by DK-Unit4** [comment]
Thank you very much. you are correct it is not a bug: I was mis-leaded by our old code and documentation: you are right : inside have no effect on funnel, and the bold text is also comes from a different place. Sorry for bothering you
