### ISSUE TITLE
Issue with ScrollBar in HighStocks

### ISSUE THREAD

**Issue by VBIManonmaniM** [highcharts/highcharts#9235]
#### Expected behaviour
Highstocks trigger the redraw or render function after the scroll bar moved.

#### Actual behaviour
**But I don't want to trigger the redraw or render function after the scroll bar moved**. Because I setting axis maximum value inside the render function.

#### Live demo with steps to reproduce

http://jsfiddle.net/qfhc09z7/

#### Product version

Highstock 6.2.0
#### Affected browser(s)
All browsers

**Comment by VBIManonmaniM** [comment]
@nsdevaraj Please look tinto the issue.

**Comment by pawelfus** [comment]
Hi @VBIManonmaniM 

Thanks for reporting the issue. In `chart.scrollbar` you have an option `liveRedraw` which will call `render` and `redraw` only after mouseup: http://jsfiddle.net/BlackLabel/qfhc09z7/6/

It looks like the same option is broken for `Axis.scrollbar`: http://jsfiddle.net/BlackLabel/qfhc09z7/8/
