### ISSUE TITLE
In newly contributed India map with Telangana, the hc-a2 code for Andhra Pradesh and Arunachal Pradesh is same. This will result in a conflict when try to plot data from Json.

### ISSUE THREAD

**Issue by akhilj64** [highcharts/highcharts#9236]
**EXPECTED BEHAVIOUR**
Andhra Pradesh, hc-a2: AP,
Arunanchal Pradesh, hc-a2: AR

**ACTUAL BEHAVIOUR**

Andhra Pradesh, hc-a2: AP,
Arunanchal Pradesh, hc-a2: AP

**LIVE DEMO**
Please verify the hc-a2 code for Andhra Pradesh and Arunachal Pradesh in the following example.
http://jsfiddle.net/BlackLabel/jyhLxfb4/

**SOLUTION**
Changing the hc-a2 code of Arunachal Pradesh from "AP" to "AR" will fix the issue.

**PRODUCT VERSION**
All versions

**AFFECTED BROWSERS**
All browsers

**Comment by pawelfus** [comment]
@KacperMadej

**Comment by KacperMadej** [comment]
Hi @akhilj64 

Thank you for reporting about the problem.

https://www.highcharts.com/docs/maps/map-collection :
> hc-a2: Two letter abbreviation of area name. Usually same as postal code/ISO code, but not always. Not guaranteed to be unique within map.

According to documentation this is not a bug. Tagging as an enhancement suggestion.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#27
