### ISSUE TITLE
Idea: Rename series long clicking on its legend item

### ISSUE THREAD

**Issue by ivankokan** [highcharts/highcharts#9239]
#### Expected behaviour
The idea is about improving click handling so that user gets an opportunity to rename series if click is long enough.

#### Actual behaviour
Currently, a common click on a legend item is handled in a way it toggles the corresponding series visibility.

I will try to implement this on my own and submit a PR.

**Comment by pawelfus** [comment]
Hi @ivankokan 

Thanks for sharing your idea. We gather ideas on our uservoice: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api and we implement them in core once popularity increases. We use github for bug reports.

**Comment by ivankokan** [comment]
Hi @pawelfus 

Do I still have freedom to submit a PR when ready?

**Comment by ivankokan** [comment]
Idea submitted: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/35813527-enhance-legend-item-click-handling-so-that-corresp

**Comment by pawelfus** [comment]
Yes, of course! Feel free to submit PR. Thanks! :)
