### ISSUE TITLE
Exporting SVGs with Multiple Y Axes

### ISSUE THREAD

**Issue by tuckergordon** [highcharts/highcharts#9242]
#### Expected behaviour
When exporting a chart with two y axes using `getSVG(..)`, the user should be able to apply styles to both axes using something like:

```
chart.getSVG({
  ...,
  yAxis: [{ // Primary yAxis
    gridLineWidth: 1.25,
    title: {
      style: {
        fontSize: '22px'
      },

    },
    labels: {
      style: {
        fontSize: '18px'
      }
    }
  }, { // Secondary yAxis
    gridLineWidth: 1.25,
    title: {
      style: {
        fontSize: '22px'
      }
    },
    labels: {
      style: {
        fontSize: '18px'
      }
    },
    opposite: true
  }],
  ...
})
```

#### Actual behaviour

Doing the above breaks the `merge` function and results in all options being overwritten except for the new options. For example, the above will result in two y axes each titled "Values" but with the correct size. 

Attempting to use the style format of a single axis in this case results in only one of the y axes getting the correct options. For example:

```
chart.getSVG({
  ...,
  yAxis: { // Primary yAxis
    gridLineWidth: 1.25,
    title: {
      style: {
        fontSize: '40px'
      },

    },
    labels: {
      style: {
        fontSize: '18px'
      }
    }
  },
  ...
})
```
This will result in one axes with the correct fontSize but the other left unchanged.

#### Product version
Highcharts 6.1.0

#### Affected browser(s)
Tested in Chrome 70

**Comment by pawelfus** [comment]
Hi @tuckergordon 

Thanks for reporting the issue! You are right, the issue comes from `merge()` method in the core, which does not merge arrays, but instead replaces items in those arrays.

### Live demo:
http://jsfiddle.net/BlackLabel/924npmts/

And simplified to `merge()` case: http://jsfiddle.net/BlackLabel/vktae0hd/

*Internal note:*
Actually it's the same issue as #2439 - just different use case.

**Comment by OldBuddy** [comment]
Hi @pawelfus, any plans to fix this?

**Comment by OldBuddy** [comment]
@raf18seb can you try [this](https://jsfiddle.net/yqhwdp7g/)? Export chart and see only first y-axis is getting red grid lines.

**Comment by OldBuddy** [comment]
@raf18seb I don't think that workaround will be convenient for us, as we set up `exporting` under default options. I guess this new `load` event from workaround will "erase" original ones.

**Comment by raf18seb** [comment]
@OldBuddy 

> @raf18seb can you try this? Export chart and see only first y-axis is getting red grid lines.
I exported chart and everything works fine. Could you provide the exact steps to reproduce the issue and describe what is current vs expected behavior?

**Comment by raf18seb** [comment]
@OldBuddy you are changing gridLines only for the first yAxis. You need to change it for both, like in original chart's config:
```js
exporting: {
    chartOptions: {
      yAxis: [{
        gridLineColor: '#f00'
      }, {
        gridLineColor: '#f00'
      }]
    }
  }
```


Demo: https://jsfiddle.net/BlackLabel/jhotpn6L/

**Comment by OldBuddy** [comment]
@raf18seb agree with your method, but I think it's a little counterintuitive. Shouldn't it be the same way how `series` are processed (when we set up e.g. `plotOptions.series` - we don't need to specify options for each specific series)?

**Comment by raf18seb** [comment]
@OldBuddy sounds fair. You can create a separate feature request ticket for this, as this ticket is about a different bug that is solved/closed already.

**Comment by OldBuddy** [comment]
@raf18seb thanks! #16888 created.
