### ISSUE TITLE
Line and area series not rendering correctly.

### ISSUE THREAD

**Issue by offthetwig** [highcharts/highcharts#9244]
#### Expected behaviour
I cannot reproduce this problem in Fiddle (I included the example anyway), so I assume that the problem is related to something specific to my application.  The chart should be a simple line, but instead I am seeing the attached image.  I suspect that it is some sort of CSS conflict, but I have not been able to isolate the cause.  I get similar results for an area series but other series such as pie, bar, scatter, or column work as expected.  Any suggestions would be greatly appreciated

![screen shot 2018-10-24 at 12 53 37 pm](https://user-images.githubusercontent.com/2325677/47457431-ee1b6980-d78b-11e8-998f-f01a1f9e4830.png)

#### Actual behaviour
![screen shot 2018-10-24 at 12 35 07 pm](https://user-images.githubusercontent.com/2325677/47456445-63396f80-d789-11e8-83ee-b2c7f117c04a.png)

#### Live demo with steps to reproduce

template: https://jsfiddle.net/LLExL/13263/ 

#### Product version

Highcharts v6.20

#### Affected browser(s)
I have only tried Chrome, but the issue is not present in Fiddle using Chrome.

**Comment by pawelfus** [comment]
Hi @offthetwig 

Thank you for reporting the issue. Unfortunately, without live demo we can only guess what is wrong. This can be a CSS issue, like `fill` option set somewhere in your code: https://jsfiddle.net/BlackLabel/LLExL/13265/

**Comment by offthetwig** [comment]
Thank you so much for your very prompt reply.  Since I could not reproduce the problem outside of my application, the best I could hope for was what you provided.  You have provided me with a great start. 
 I will let you know what I find.

Thanks

**Comment by offthetwig** [comment]
Hi @pawelfus 

Found a workaround but not the specific cause.  For whatever reason the minified version is not working in the context of my application.  When I replace the minified version with the clear text version, the line based series are rendered correctly.

Thanks again for your help with this.

**Comment by pawelfus** [comment]
That's strange. Which files do you load (and how)?

**Comment by offthetwig** [comment]
I load highcharts by itself or before other highcharts modules as follows.  Either way the result is the same:

<link href="css/highcharts.css" rel="stylesheet">
...
<script src="js/highcharts/highcharts.js"></script>
<script src="js/highcharts/histogram-bellcurve.js"></script>
<script src="js/highcharts/exporting.js"></script>
<script src="js/highcharts/offline-exporting.js"></script>
<script src="js/highcharts/export-data.js"></script>
...

The problem is completely isolated to the minified highcharts.js scripts interaction with my application.  I haven't run into any issues with other modules yet.

**Comment by pawelfus** [comment]
Are you sure you load correct files? Do you load styled-mode or just JS version? In the second case, css file is redundant. Maybe you accidentally mixed modules (some for JS version, others for CSS mode). I would suggest to load library once again and replace files, if that fixes the issue then above is correct.

**Comment by offthetwig** [comment]
I will take another look.
Thanks again.

**Comment by offthetwig** [comment]
That was the issue.  I apologize for bothering you with this.  I had not found the documentation until you pointed out that there was a difference.  Thank you very much for your help.
