### ISSUE TITLE
Highcharts Bug - clicking on legend item in heatmap with use of colorAxis > dataClasses  & legendItemClick not fired event.

### ISSUE THREAD

**Issue by berdejitendra14** [highcharts/highcharts#9246]
#### Expected behaviour
http://jsfiddle.net/2mvfgh99/20/
Above jsfiddle has Highcharts heatmap example integrated heatmap graph with colorAxis property and it showing corresponding legends. 
By clicking of legend items, we don't want to fire an event which hides a range of heat blocks on the graph.

#### Actual behaviour
By clicking of legend items, it hides a range of heat blocks on the graph.

#### Live demo with steps to reproduce

http://jsfiddle.net/2mvfgh99/20/

#### Product version

Highcharts 5.0.16

**Comment by pawelfus** [comment]
Hi @berdejitendra14 

Thanks for reporting the issue. As described in #3444, there's no `colorAxis.dataClasses.event.legendItemClick`. Only `colorAxis.events.legendItemClick` bound to colorAxis without dataClasses: http://jsfiddle.net/BlackLabel/2mvfgh99/25/

I agree, these events should be supported in `dataClasses`. Simple plugin to add this functionality to the core: http://jsfiddle.net/BlackLabel/t1oxcn73/

```javascript
(function(H) {
  H.wrap(H.Legend.prototype, 'renderItem', function(proceed, item) {
    var ret,
      chart = this.chart,
      colorAxis = chart.colorAxis,
      legendItem = item.legendItem;

    ret = proceed.apply(this, Array.prototype.slice.call(arguments, 1));

    if (
      item.isDataClass &&
      // Created new item, add event:
      !legendItem &&
      item.legendItem &&
      item.events
    ) {

      H.objectEach(item.events, function(value, key) {
        H.addEvent(item, key, value);
      });
    }

    return ret;
  });
})(Highcharts)
```

*Internal note:*
It looks like event is bound to `colorAxis` instance (`colorAxis` has `hcEvents` storage), but fired for `colorAxis.dataClasses[index]`:

https://github.com/highcharts/highcharts/blob/bd59aa5b1145d1dc8e85f57f43df38a8e92bf3d3/js/parts-map/ColorAxis.js#L987-L1006

**Comment by berdejitendra14** [comment]
Hi @pawelfus,

Regret for not following up on the above-reported issue. 

You jsfiddle solution work perfectly fine with highcharts jquery library. However, I am using Angular Highchart 5.0.16 git code. Could you please help us how can I integrate above-suggested changes into Angular library. 

Thanks in advance.

**Comment by pawelfus** [comment]
Hi @berdejitendra14 

Don't worry, I'm glad it works! In angular, copy code to a separate file, then load file/module as any other Highcharts plugin (e.g. exporting).

**Comment by rahulxyz** [comment]
Hi @pawelfus,

I was facing a similar issue and tried your solution. It worked as expected. I'm able to restrict as well as intercept legend clicks in heat map. I'm sharing a [demo](https://stackblitz.com/edit/angular-wilgzo?file=src%2Fapp%2Fapp.component.ts) implementation in angular for future reference.
_PS: 3 out of 6 legends are unclickable._

I do have one issue. Legend toggle makes the bullet-color of legend turn grey unlike other graphs which only fades the text and not bullet-color of legend. Any suggestions how i can maintain that consistency in heatmap.

**Comment by pawelfus** [comment]
Hi @rahulxyz 

Great to hear it works for you too! Legend item (rectangle) is greyed out by default, just like legend text (it's consistent across series, see: https://www.highcharts.com/demo/line-basic). You can change this behaviour by setting [`legend.itemHiddenStyle.color = null`](https://api.highcharts.com/highcharts/legend.itemHiddenStyle), demo: https://stackblitz.com/edit/angular-5dejws?file=src/app/app.component.ts
