### ISSUE TITLE
dataLabels bug in HC 6.2.0?

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#9247]
I think this must relate to changes made to add the new feature "Added support for multiple data labels on each single point" in 6.2.0.

I'm getting the error:

    Uncaught TypeError: Cannot read property 'options' of undefined

The problem occurs in the following bit of HC code:

    each(dataLabels, function (label) {
        var options = label.options; // <---- label is undefined here
        // ...
    });

Problem occurs when we somehow get to that part of the code with `point.dataLabels` being an array including one defined element and another undefined element: `[H.SVGElement, undefined]`.

Problem seems to be confined to `areasplinerange` type (probably any `range` type), and can be reproduced in the following jsfiddle:

https://jsfiddle.net/jbhgkze2/

**Comment by pawelfus** [comment]
Hi @drmrbrewer 

Thanks for reporting the issue. You are right, it used to work in v6.1: https://jsfiddle.net/BlackLabel/jbhgkze2/5/

**Workaround:**
Instead of returning `null`, return empty string: https://jsfiddle.net/BlackLabel/2pq3fzhg/

**Comment by drmrbrewer** [comment]
I tried returning blank strings already, but the problem is that I am using boxes around the labels, so they appear around the blank labels.
