### ISSUE TITLE
Can't set xAxis min max if panning

### ISSUE THREAD

**Issue by Abrissirba** [highcharts/highcharts#9250]
#### Expected behaviour
In a chart where I have panned, I want to be able to set xAxis min and max manually in code later.

#### Actual behaviour
If I have panned, I can no longer update the graphs xAxis with xAxis.update({ min:..., max: ...})

#### Live demo with steps to reproduce
https://jsfiddle.net/bLu1645x/
If no panning has been made and you click on Update X-Axis, that chart will show another timespan.
If you pan, clicking the button will not update the shown timespan.

#### Product version
Highstock 6.2.0

#### Affected browser(s)
Tested in Chrome

**Comment by pawelfus** [comment]
Hi @Abrissirba 

Thanks for reporting the issue. I'm not sure if this is a bug, but certainly this should be explained in docs. `panning` internally uses `setExtremes()` which stores information about current extremes, set by user. These extremes have the highest priority when deciding extremes (data extremes < options extremes < user extremes), so later when you update `xAxis.options.min`, user extremes are still there. 

In general, when changing extremes, we recommend to use [`xAxis.setExtremes(min, max)`](https://api.highcharts.com/class-reference/Highcharts.Axis#setExtremes). It's faster than `xAxis.update()`.

*Internal note:*
We can inspect options in `Axis.update()` and if `min` and `max` are set, delegate to `setExtremes()`. Or at least remove `userMin`/`userMax` details. I'm not sure if this wouldn't affect Highstock's navigator - I remember some issues with `min`/`max` extremes there. Alternatively, we could add more details in [`Axis.update`](https://api.highcharts.com/class-reference/Highcharts.Axis#update).

**Comment by Abrissirba** [comment]
Thanks Pawel,

I agree that at least a note in the docs about this behavior would be nice. It was a bit confusing until I found out the why the update worked sometimes and sometimes not. setExtremes worked like a charm :) 

I do update some more properties of the xAxis at the same as I set the extremes so for my use case it would be nice to be able to set the extremes in update aswell.
