### ISSUE TITLE
change chart type to treemap after Drilldown cause Error

### ISSUE THREAD

**Issue by yunhyel** [highcharts/highcharts#9251]
change chart type to treemap after Drilldown cause Error...
Is it impossible for latest version?

http://jsfiddle.net/175t76qw/239/

**Comment by KacperMadej** [comment]
Hi @yunhyel 

Thank you for reporting about the problem.

On drilldown axes extremes are changed, because of how treemap series interacts with axes. The easiest solution here is to add different axes (xAxis and yAxis) for treemap series. Demo: http://jsfiddle.net/BlackLabel/2xzuyrcw/

**Comment by yunhyel** [comment]
OMG thank you for perfect answer
