### ISSUE TITLE
Add removeAnnotation by annotation object method

### ISSUE THREAD

**Issue by kutensky** [highcharts/highcharts#9252]
Currently you can remove annotation by calling **removeAnnotation(id)** method, where **id** is some value that was passed in options object during creation of **Annotation** object.
First of all, you don't want to set id for each annotation.
Second, you can't set id for **Annotation**'s object using **.Net Highsoft** library. There is no Id property in that library.

Good solution would be to add new method or change current **removeAnnotation** method to be able to pass **Annotation** object as a parameter.

**Comment by pawelfus** [comment]
Hi @kutensky 

Thank! We agree, that would be useful. In general, ideas should be created in our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api).

Actually this will be supported in v7: http://jsfiddle.net/BlackLabel/dywLou0r/

Thanks for reporting missing `id` for annotations in .Net extension!

**Comment by kutensky** [comment]
Great news about v7. Thanks for you response.
