### ISSUE TITLE
How to affect candlestick color-up/color-down classes

### ISSUE THREAD

**Issue by rriixx** [highcharts/highcharts#9265]
I'm trying to find out how to affect the candlestick classes `highcharts-point-down` and `highcharts-point-up`.
In my screenshot you can see that candles which four values (open, high, low, close) are equal, got the class `highcharts-point-down` applied which is red in my case.
<img width="949" alt="screenshot 2018-10-29 at 18 26 35" src="https://user-images.githubusercontent.com/7082458/47668241-31b90d80-dba8-11e8-8a05-48695e906524.png">

What i want is that those candles which four values are equal get the class `highcharts-point-up`. So they appear green not red.

Is there any way to achiev that?

**Comment by sebastianbochan** [comment]
Hi @rriixx,
Thank you for contacting us. This is our bug tracker so for general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or forum.
