### ISSUE TITLE
in detail graph, chart update (type to treemap) error when click

### ISSUE THREAD

**Issue by yunhyel** [highcharts/highcharts#9268]
I want to change the detail chart type to treemap (after click the point)
but error 17 "The requested series type does not exist" occurs
Is it impossible?

this is my code
https://jsfiddle.net/g572czrh/8/

**Comment by sebastianbochan** [comment]
Hi @yunhyel ,
Thank you for contacting us. This is our bug tracker so for general [support](http:/www.highcharts.com/support) questions please use forum / stackoverflow or forum.
