### ISSUE TITLE
Gantt: Problems with axis grid update

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#9269]
#### Expected behaviour
`chart.update()` should work properly.

#### Actual behaviour
Error with `oneToOne` flag:
`Uncaught TypeError: Cannot set property 'index' of undefined`

Error without `oneToOne` flag:
`Uncaught TypeError: Cannot read property 'uniqueNames' of undefined`

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8sxraqdp/

Click 'update' button.

#### Product version
Gantt v6.2.0

#### Affected browser(s)
All

**Comment by savnik** [comment]
This issue effectively prevents dynamic data loading. Is there a known fix or workaround?

**Comment by sebastianbochan** [comment]
The problem is still valid in the v7.0.3

FYI @jon-a-nygaard

**Comment by vlabs** [comment]
any progress here? this is blocking us using highgantt..

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
Hi, I am currently looking into the issue, and working on a fix for it.

It seems that [`Axis.update`](https://github.com/highcharts/highcharts/blob/414346cbe6ccc9045950689b681bc40f6bd948ed/js/parts/Dynamics.js#L537) is creating a new object at `chart.yAxis[0]` and thus the `touched` property is set on a different object, which is causing the yAxis to be destroyed later on.

Not sure yet why this happens, but I will come back with more information ASAP.

**Comment by jon-a-nygaard** [comment]
There seems to be some creation of new axes when adding the `grid.columns` options.

As a workaround this can be avoided by setting the title directly on the axis instead of using `grid.columns[].title`. Please see the following example https://jsfiddle.net/jon_a_nygaard/axw41053/

**Comment by danielbartsch** [comment]
correct me if I'm wrong, but that workaround isn't possible if your yAxis grid has more than one column, or is it?

**Comment by jon-a-nygaard** [comment]
Hi @danielbartsch,

The workaround is usable for multiple axis as well, the `axis.columns[]` options is in practical an alias for creating multiple axis with the same base options.

Using the workaround with multiple axes will look something like in the following example https://jsfiddle.net/jon_a_nygaard/axw41053/9/

Hope it helps.

**Comment by savnik** [comment]
Hi @jon-a-nygaard 
When I look at the example given above it is only rendering 1 row, and the data from 2 row is displayed on top. The button does not update the graph.
I'm viewing in Chrome.

**Comment by danielbartsch** [comment]
in the javascript code, `chart.update` updates the graph as if you  were clicking  the button.  The button shouldn't be here anymore.

Also here's a clearer solution, if you  have more lines: https://jsfiddle.net/qnzv2tLa/
