### ISSUE TITLE
labels's step option ignored showLastLabel

### ISSUE THREAD

**Issue by totszwai** [highcharts/highcharts#9275]
#### Expected behaviour
Axis label's step option should respect showLastLabel option

#### Actual behaviour
label's step option ignored showLastLabel option

#### Live demo with steps to reproduce
http://jsfiddle.net/totszwai/0tc2n3zd/

#### Product version
6.1.4

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @totszwai 

`step` option logic runs after `showLastLabel`, so if `step` will hide the label then state based on `showLastLabel` option will be overridden. It's possible to additionally hide last label using `showLastLabel` - [demo](http://jsfiddle.net/BlackLabel/0tc2n3zd/2/), but not other way around.

Here's a workaround (`step` logic runs first and after that `showLastLabel` or `showFirstLabel` could show or hide the relevant label anyway):
http://jsfiddle.net/BlackLabel/0tc2n3zd/3/

We could resolved this issue as adding more info in the relevant API docs (to describe how this works now) and later add an enhancement label (as an feature request to change the behavior).

**Comment by pawelfus** [comment]
The same we can achieve by simple `formatter`:
```javascript
  xAxis: {
    categories: [ ... ],
    labels: {
      formatter: function () {
      	return this.pos % 2 && !this.isLast ? '' : this.value;
      }
    }
  }
```
