### ISSUE TITLE
Series Sometimes disappears when x-axis height changes

### ISSUE THREAD

**Issue by f1ghtingfalcons** [highcharts/highcharts#9280]
#### Expected behaviour
Series at bottom of plot should always be rendered even after changing the x axis label formatters.

#### Actual behaviour
On occasion when you are zoomed in on a section of the plot and you change the height of the x-axis labels the series with values at 0 disappears. 

![image](https://user-images.githubusercontent.com/3945430/47813532-03a30d00-dd11-11e8-87bc-edfd6036f8f4.png)

You can see that there should be a line at the bottom at 0, but its not being rendered.

#### Live demo with steps to reproduce
https://jsfiddle.net/rz2naq5m/5/
 
I apologize, but this one is hard to reproduce. You need to zoom in so that the x-axis formatters switch between 1 line and 2 lines when you click the 'Change X Axis Version. Even then, it doesn't happen every time. You have to mess with the zoom a bunch until it happens. Here is the bug in action:

![highcharts_bug](https://user-images.githubusercontent.com/3945430/47813816-b1162080-dd11-11e8-9bb0-80dc8cb7b2f0.gif)

Once the bug happens, you can change the zoom or anything else and it will fix itself.

#### Product version
Highstock JS v6.2.0

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @f1ghtingfalcons 

Thank you for reporting about the problem.
This is hard to recreate - I'm unable to provide steps.

_Internal note:_
The issue is caused by wrong `clipPath` size - height is not updated.

**Comment by f1ghtingfalcons** [comment]
Yeah, sorry about the reproducibility. Even knowing that the bug exists I find it hard to reproduce myself, but I am always able to do it after enough experimentation with different zoom levels. It appears that you have found the culprit regardless. Thanks.
