### ISSUE TITLE
Half pie dataLabel is placed incorrectly after updating distance from positive to negative

### ISSUE THREAD

**Issue by henkli** [highcharts/highcharts#9284]
#### Expected behaviour
Updating the distance of the point in pie from positive to negative should move dataLabel inside the pie.

#### Actual behaviour
When updating distance of dataLabel for point in half-pie from positive (e.g. 20) to negative (e.g. -20), the dataLabel is (sometimes) placed outside the pie (not inside the pie, as one would expect with a negative distance).

#### Live demo with steps to reproduce
https://jsfiddle.net/p8reugq3/1/

#### Product version
Highcharts 6.2.0 (styled and unstyled)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Fixed in v7.1.0: https://jsfiddle.net/BlackLabel/x3smgfc0/
