### ISSUE TITLE
Not possible to reset zoom when toggling navigator

### ISSUE THREAD

**Issue by Abrissirba** [highcharts/highcharts#9285]
#### Expected behaviour
If the navigator is turned off I expect to be able to zoom and reset the zoom level.

#### Actual behaviour
I'm not able to reset zoom if I turn the navigator off

#### Live demo with steps to reproduce
http://jsfiddle.net/20pjhd9a/
1. Zoom the chart
2. Turn off the navigator by clicking on "Toggle navigator"
3. Zoom once again
4. No "Reset zoom" button available

#### Product version
6.2.0

**Comment by KacperMadej** [comment]
Hi @Abrissirba 

Thank you for reporting about the bug.

**Workaround**: set `chart.zoomType` to `'xy'`

_Internal note:_
`resetZoomButton` is blocked ([`chart.resetZoomButton = 'blocked';`](https://github.com/highcharts/highcharts/blob/942f67b85b6b81d297f242d012039344865b729b/js/parts/Navigator.js#L2348-L2349)), but never released from the block.
