### ISSUE TITLE
Problem when dynamically Loading data and setting the navigator

### ISSUE THREAD

**Issue by fazelmk** [highcharts/highcharts#9287]
#### Expected behaviour

afterSetExtremes called once

#### Actual behaviour

afterSetExtremes called infinite times until you manually change the zoom

#### Live demo with steps to reproduce
http://jsfiddle.net/1kbeuLrn/3/

#### Affected browser(s)
Chrome and Firefox have the problem ( didn't try others )

I need to set the navigator dynamically because I have multiple series and they are not loaded with the chart.

PS.: Notice that the problem only occur with splice in place ``` chart.get("s.id").setData(data.splice(1));```
otherwise it works. But as my data returned from the back-end is not guaranteed to have points to fill the ends of the zoomed area this problem is occurring

PS 2.: http://jsfiddle.net/paenLwx9/ have splice but not dinamically setted navigator series and works.
Same behavior when manually creating the navigator (http://jsfiddle.net/paenLwx9/1/)

**Comment by fazelmk** [comment]
Could you provide a JSFindler on how I could prevent the extremes to change?

**Comment by KacperMadej** [comment]
I was referring to your demo - http://jsfiddle.net/paenLwx9/
It works correctly or is the problem visible there?

**Comment by fazelmk** [comment]
Visible problem in this one: http://jsfiddle.net/paenLwx9/1/

**Comment by KacperMadej** [comment]
Empty chart is not initialized the same way as a chart with data, so it easier to create a new chart when data is loaded - after that use the code from the working demo.
http://jsfiddle.net/BlackLabel/paenLwx9/2/

**Comment by fazelmk** [comment]
So. The thing is. I have a list of points that have data associate with them. 

The user can add/remove them from the chart as pleased. So they can see the data for any point and compare any points they want.

For that reason I will need to dynamically add series to the chart. I can do the work around and recreate the chart if there is no series added to it. 

But in the case there is a series. How should I add the new series to chart?? 
```chart.addSeries```  will add the new series to the navigator?

**Comment by KacperMadej** [comment]
Here's a working demo with 2 series in navigator - few comments were added to better explain changes in demo: http://jsfiddle.net/BlackLabel/paenLwx9/4/

This seems to be more support case than bug report. In future please contact tech support - https://www.highcharts.com/support

If you want we could close this issue, continue the case through e-mails (support@highcharts.com) and when a bug will be found we'll report it as a new issue.

**Comment by fazelmk** [comment]
I got my chart working. If I have any further problems with it I will e-mail the support. 
Thanks for the help @KacperMadej.
