### ISSUE TITLE
chart.update() does not work with the same number of data with 'null' values

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#9290]
#### Expected behaviour
Chart update should work in the same way as in the case with a different number of data:
https://jsfiddle.net/BlackLabel/n27hyver/

#### Actual behaviour
Chart update does not cause any effects.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/q8g9jbar/

1. Click on '1st Data' button.
2. Click on '2nd Data' button.
3. Click on 'Again 1st Data (without Series1)' button.

#### Product version
Highcharts v6.2

#### Affected browser(s)
All

**Comment by ppotaczek** [comment]
The workaround is to update the chart with `null` values as `y` property: 

Live demo: https://jsfiddle.net/BlackLabel/cnw4vh65/

**Comment by TorsteinHonsi** [comment]
Should be straight forward, just replace the `pick` with a test for `undefined`?

**Comment by KacperMadej** [comment]
Closing as resolved.
