### ISSUE TITLE
XRange item labels sometimes display percentages with too many decimal places

### ISSUE THREAD

**Issue by objorkli** [highcharts/highcharts#9291]
#### How to reproduce.
Change the partialFill of a single dataset of an xrange chart to 0.28. 
#### Expected behaviour
The dataset label should show 28% 

#### Actual behaviour
The dataset label shows 28.0000000000004%

#### Live demo with steps to reproduce
template: https://jsfiddle.net/02rtqxp6/ 

#### Product version
Highcharts JS v6.2.0 (2018-10-17)

#### Affected browser(s)
Chrome, Firefox, Internet explorer, Edge

**Comment by KacperMadej** [comment]
Hi @objorkli 

Thank you for reporting about the problem.

**Workaround**: set custom [dataLabels.formatter](https://api.highcharts.com/highcharts/series.xrange.dataLabels.formatter). Demo: https://jsfiddle.net/BlackLabel/02rtqxp6/1/

_Internal note:_ `return H.correctFloat(amount * 100) + '%';` should be enough here.

**Comment by TorsteinHonsi** [comment]
> return H.correctFloat(amount * 100) + '%'; should be enough here.

Yes, agreed.
