### ISSUE TITLE
Denormalized points data on datetime type xAxis

### ISSUE THREAD

**Issue by ElectronicaGitHub** [highcharts/highcharts#9292]
I got a series with default X interval between points.

With xAxis.tickPixelInterval=10 for better problem understanding or without it, i got normalized xAxis intervals. 
![2018-11-05 15 20 41](https://user-images.githubusercontent.com/4830136/47997954-ab07b180-e10e-11e8-9f3c-1006617b6a01.png)

After customer zoom the chart i need to get more detailed data via server with smaller xAxis interval, combine old + new, and update my series, so it looks like this
`series.setData(data, true, false, false);`
![2018-11-05 15 21 31](https://user-images.githubusercontent.com/4830136/47997963-b22ebf80-e10e-11e8-83d2-09841f349f64.png)

Now, after removing zoom we got next picture with denormalized xAxis intervals between ticks(while tickPixelInterval=10). But i need to make this chart as it was before we insert part of more detailed data. 
![2018-11-05 15 21 39](https://user-images.githubusercontent.com/4830136/47997974-b6f37380-e10e-11e8-994e-23dcc65bbc50.png)

We tried some workaround with plotOptions.series.dataGrouping but that looks even stranger that with default dataGrouping.

Axis with type 'datetime' should be linear with fixed intervals. How to solve this problem and what i'm doing wrong? 

Thanks in advance.

**Comment by KacperMadej** [comment]
Hi @ElectronicaGitHub 

Thank you for reporting about the problem.

Axis might not be linear if it's ordinal - you could check that options in API reference: https://api.highcharts.com/highstock/xAxis.ordinal

Please add a live, minimal demo, so we could debug the problem and test possible solutions.
You could use simulated server connection through hard coded data samples.

**Comment by ElectronicaGitHub** [comment]
Thank you @KacperMadej 

That helps.
