### ISSUE TITLE
Zooming is not possible when some series is draggable

### ISSUE THREAD

**Issue by Timppe** [highcharts/highcharts#9298]
#### Expected behaviour
Zooming is possible even though draggableX/Y is true for some series in the graph

#### Actual behaviour
Zooming is not possible (the selection event is not even firing) when some series has draggableX/Y true

#### Live demo with steps to reproduce
Here you see a presumably zoomable chart, but the draggableY is set to true, so the selection event doesn't even fire: http://jsfiddle.net/sxk32aoL/

Here is the exact same thing, but the draggableY is set to false, so the zooming is possible (and naturally the selection even fires upon zooming and resetting zoom): http://jsfiddle.net/ko1jLtfp/1

#### Product version
Highcharts 6.2.0

#### Affected browser(s)
Tested only on chrome

**Comment by TorsteinHonsi** [comment]
Apparently the the draggable-points module prevents default so the mousedown or mousemove event never reaches the zoom logic. Probably should only happen if there is actually a point to drag.

**Comment by Timppe** [comment]
I bypassed this bug in my code by setting draggableX/Y true only when I have selected a dot to drag. (In our product, the point is programmatically selected by clicking before it can be dragged)
