### ISSUE TITLE
Highstock flags series data not visible at certain zoom ranges after 6.1.2

### ISSUE THREAD

**Issue by gbenthomas** [highcharts/highcharts#9299]
#### Expected behaviour
Flag series data should be visible if the point is visible on the chart.
Expected to see both flag data points as in version 6.1.1: http://jsfiddle.net/JppHN/51/

#### Actual behaviour

Flag series data is not visible when zoomed close to the point and there is no indication that there is data there. Noticed this behavior started with version 6.1.2.

#### Live demo with steps to reproduce
6.1.2+: http://jsfiddle.net/JppHN/52/

Notice that the C and E flags are not displayed at the same zoom range. The only change between the two jsfiddles is the version of Highstock.

#### Product version
Highstock 6.1.2+

#### Affected browser(s)
Chrome, Firefox

**Comment by KacperMadej** [comment]
Hi @gbenthomas 

Thank you for reporting about the problem.
Current workaround is rather plain - use version 6.1.1.

_Internal note:_
The offending commit is https://github.com/highcharts/highcharts/commit/281bc56
Probably allowing zeroes in here will be enough - https://github.com/highcharts/highcharts/blob/d8fdce3ee0609cc8f872c547f697278e15a9cc8e/js/parts/FlagsSeries.js#L448
