### ISSUE TITLE
Sankey chart crashes on update when addSeries was called with redraw=false

### ISSUE THREAD

**Issue by anajavi** [highcharts/highcharts#9300]
#### Expected behaviour
Other series types can do:
```javascript
var series = chart.addSeries(opts, false);
  
series.update({
  events: { }
}, false);
chart.redraw();
```

#### Actual behaviour
TypeError: Cannot read property 'concat' of undefined

Somehow this.points is undefined when addSeries was called with redraw set to false:
https://github.com/highcharts/highcharts/blob/ee6f7a4b5ce85eb3c6145d66c31d32a631f07666/js/modules/sankey.src.js#L616

#### Live demo with steps to reproduce
https://jsfiddle.net/cm352rLt/7/

#### Product version
Highcharts 6.2.0

#### Affected browser(s)
All.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, it's fixed now. 

#### Workaround
Add this snippet
```js
Highcharts.seriesTypes.sankey.prototype.destroy = function () {
    // Nodes must also be destroyed (#8682, #9300)
    this.data = [].concat(this.points, this.nodes);
    Highcharts.Series.prototype.destroy.call(this);
};
```
