### ISSUE TITLE
Tooltip headerFormat broken after updating to 6.2 from 6.1

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [highcharts/highcharts#9301]
#### Expected behaviour
In 6.1, I was using the tooltip as 
```
"tooltip": {
    "headerFormat": "<span style=\"font-size: 0.85em\">{point.x} - {point.x2}</span><br/>",
    "pointFormat": "<span style=\"color:{series.color}\">●</span> {series.name}: <b>{point.yCategory}</b><br/>"
}
```
Which was giving the output as 
![image](https://user-images.githubusercontent.com/13748882/48111993-5719db80-e27a-11e8-8087-3ce04a1f3f77.png)
http://jsfiddle.net/hq1kdpmo/52/
#### Actual behaviour
After upgrading to 6.2, my tooltip breaks and the output becomes
![image](https://user-images.githubusercontent.com/13748882/48112027-816b9900-e27a-11e8-9f43-35c1f8916541.png)

Since this is a minor version update, I didn't expect a breaking change to happen.

#### Live demo with steps to reproduce
http://jsfiddle.net/hq1kdpmo/6/

#### Product version
Highcharts 6.2.x

#### Affected browser(s)
All

Note: I have tried doing 
```
"tooltip": {
    "headerFormat": "<span style=\"font-size: 0.85em\">{point.point.x} - {point.point.x2}</span><br/>",
    "pointFormat": "<span style=\"color:{series.color}\">●</span> {series.name}: <b>{point.yCategory}</b><br/>"
}
```
Which gives me the output 
![image](https://user-images.githubusercontent.com/13748882/48112126-0ce52a00-e27b-11e8-8306-8014693bd77f.png)
and I am losing the Date formatting.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting this regression, it has now been fixed in the master.

Your demo with the fix applied: http://jsfiddle.net/highcharts/hq1kdpmo/64/

Until the next release, you can use this drop-in fix: 
```js
Highcharts.wrap(Highcharts.seriesTypes.xrange.prototype, 'translatePoint', function (proceed, point) {
    proceed.call(this, point);
    point.category = point.x;
});
```
View it [in action](http://jsfiddle.net/highcharts/hq1kdpmo/68/).
