### ISSUE TITLE
Demo link for series.flags.allowOverlapX in documents is missing jQuery as a requirement

### ISSUE THREAD

**Issue by dbowring** [highcharts/highcharts#9302]
#### Expected behaviour

clicking "Allow sideways overlap" on the docs page for [series.flags.allowOverlapX](https://api.highcharts.com/highstock/series.flags) shows a working demo

#### Actual behaviour

Chart fails to load with error `ReferenceError: $ is not defined`

#### Live demo with steps to reproduce

Go to https://api.highcharts.com/highstock/series.flags
Click on "Allow sideways overlap" under "allowOverlapX"
Alternatively, here is a [direct link](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/flags-allowoverlapx)

#### Product version

6.2.0

#### Affected browser(s)

Discovered in Firefox, however likely present in all.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, fix coming up!
