### ISSUE TITLE
Variwide chart produces uneven gaps between the bars with certain data

### ISSUE THREAD

**Issue by matsomo** [highcharts/highcharts#9304]
#### Expected behaviour
variwide chart with no gaps between the bars

#### Actual behaviour
variwide chart produces uneven gaps between the bars with certain data. The gaps also changes based on the chart width.

#### Live demo with steps to reproduce
https://jsfiddle.net/8fphxe4y/11/

#### Product version
highcharts: 6.2.0

#### Affected browser(s)
Tested on Chrome, Firefox and Edge. The amount of gaps vary from browser to browser

**Comment by TorsteinHonsi** [comment]
It has to do with rounding of the edge coordinates. A possible workaround could be to use a negative point padding: https://jsfiddle.net/highcharts/8fphxe4y/13/.

**Comment by matsomo** [comment]
Thanks for the suggestion. This solution will work when the columns are the same color because the overlap will be masked, but I use colored columns so the overlap is quite visible. I should have mentioned that beforehand, sorry about that.
https://jsfiddle.net/8fphxe4y/19/

**Comment by KacperMadej** [comment]
Pixel precision seems to be a limit here, so you could try [`crisp`](https://api.highcharts.com/highcharts/series.column.crisp)`: false` in series option.

How about using border with point color? Demo: https://jsfiddle.net/BlackLabel/8fphxe4y/20/

**Comment by matsomo** [comment]
borderWidth=1 seemed to fix my problem, tested on Chrome, Firefox and Edge.
