### ISSUE TITLE
Data dissapearing when zooming to small regions

### ISSUE THREAD

**Issue by RoberTnf** [highcharts/highcharts#9329]
#### Expected behaviour

Data still shows when zooming over smalls regions

#### Actual behaviour

Graph goes blank

#### Live demo with steps to reproduce
https://jsfiddle.net/c1fzvpm6/8/

- Click zoom1 button on the bottom, it will zoom to a small region without issues: y = [0.5, 0.8], x = [0, 0.002]
- Click zoom 2 button, it will zoom to a smaller region that still contains data:  y = [0.5, 0.8], x = [0, 0.0005] the graph will go blank

#### Product version
Highcharts master branch

#### Affected browser(s)
Firefox and chromium tested

**Comment by KacperMadej** [comment]
Hi @RoberTnf 

Thank you for reporting about this problem.

Please check browser console - there's error explained in link given there.
Data needs to be sorted for the used series type.
To create a working chart use scatter with positive `lineWidth`.
Demo: https://jsfiddle.net/BlackLabel/c1fzvpm6/9/

This is not a bug - we are using GitHub issues as bug tracker.
For technical support please contact Highcharts tech support - https://www.highcharts.com/support

**Comment by RoberTnf** [comment]
Thank you, I misunderstood the issue as my data was sorted along the Y axis, not on the X axis.

Sorry for misusing GitHub issues.
