### ISSUE TITLE
Highstock - hiding markers in navigator not working

### ISSUE THREAD

**Issue by Roman-Simik** [highcharts/highcharts#9330]
#### Expected behaviour
After setting marker `enabled: false` in navigator options, **it should hide the markers in navigator.**

#### Actual behaviour

After setting marker `enabled: false` in navigator options, **markers are still visible in the navigator.**

#### Live demo with steps to reproduce
https://jsfiddle.net/1um9gs47/3/ - look line 75 (just try set it to true or false, nothing changes)

#### Product version
Highstock (newest?)

#### Affected browser(s)
Propably all

**Comment by KacperMadej** [comment]
Hi @Roman-Simik 

Thank you for reporting about the problem.

You are setting `marker: { enabled: true }` for each point, so series option will be overridden by point setting.

This is not a bug. For technical support please use - https://www.highcharts.com/support
