### ISSUE TITLE
Highmaps: unable to disable legendItemClick

### ISSUE THREAD

**Issue by cscgrad** [highcharts/highcharts#9347]
#### Expected behaviour
For Highmaps with color axis data classes, I would like to disable legendItemClick

#### Actual behaviour
Adding the following in under colorAxis or plotOptions (series, map, mappoint) did not work:

                events: {
                	legendItemClick: function (e) { return false; }
                }

#### Live demo with steps to reproduce
https://jsfiddle.net/5rwgjoch/3/

#### Product version
Highmaps 6.1.3

#### Affected browser(s)
IE 11, Chrome

**Comment by KacperMadej** [comment]
Hi @cscgrad 

Thank you for reporting about the problem.
This issue is already reported - https://github.com/highcharts/highcharts/issues/9246

Closing as a duplicate, please continue in the original issue.
