### ISSUE TITLE
Highmaps: accessibility module tab order does not follow logical order

### ISSUE THREAD

**Issue by cscgrad** [highcharts/highcharts#9349]
#### Expected behaviour
For 508 compliance the map region tab order must be logical, based on some type of ordering that could be communicated to a screen reader.

#### Actual behaviour
For the US state map, the tab order could be based on the alphabetical ordering by name or numerical ordering by id (e.g. fips or zip). In the demo link below, it is unclear what order the tabbing follows.

#### Live demo with steps to reproduce
https://jsfiddle.net/82toL0x3/

#### Product version
Highmaps 6.1.3 + Accessibility module

#### Affected browser(s)
IE, Chrome

**Comment by oysteinmoseng** [comment]
This is a known issue, since the tab order follows the order of the points in the series, and the screen reader order follows the order of the SVG elements.

Alphabetical ordering seems like the most accessible and intuitive default ordering, and we should find a way to implement this.
