### ISSUE TITLE
Navigator negative color applied to wrong area.

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#9357]
#### Expected behaviour
The negative color area should be applied the same as the main series (the area between the xAxis 0 and the graph).

#### Actual behaviour
Negative color is applied incorrectly (the area below the graph).

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/3v1g5sxL/2/

#### Product version
Highstock

#### Affected browser(s)
all

**Comment by jegli** [comment]
+ 1

**Comment by jegli** [comment]
That does it for me. Thanks for the helpful and quick response!
