### ISSUE TITLE
3D Pyramid series

### ISSUE THREAD

**Issue by cvasseng** [highcharts/highcharts#9366]

**Comment by KacperMadej** [comment]
Pyramid series, but in 3D
Related to 3D Funnel (#9367)

**Comment by KacperMadej** [comment]
Code should be prepared for easy extend for Funnel features in mind, to avoid redundant code for any of the series. Base 3d features are extended from 3d column series to avoid code duplication - this might result in same bugs (not crucial) as in 3d column, but it's better to later fix all than only some IMHO.

**Comment by KacperMadej** [comment]
General documentation article draft: https://docs.google.com/document/d/1SSbttSrNB2vejN3uIQsVJT-2ewEUl82nhDOce3-dH6k/edit#heading=h.nc0dzws9revo

**Comment by KacperMadej** [comment]
Initial commit for the pyramid3d module: https://github.com/highcharts/highcharts/commit/703b8bdea5e6fa4caf25de2320fd89bc51a09c03
