### ISSUE TITLE
3D Funnel Series

### ISSUE THREAD

**Issue by cvasseng** [highcharts/highcharts#9367]

**Comment by KacperMadej** [comment]
Minor features still needs to be resolved - including neck in a point feature available in funnel, but not in pyramid and 3d rendering with correct z indexing. Base 3d features are extended from 3d column series to avoid code duplication - this might result in same bugs (not crucial) as in 3d column, but it's better to later fix all than only some IMHO.

**Comment by KacperMadej** [comment]
Initial commit pushed: https://github.com/highcharts/highcharts/commit/8ccc78d212c84e19a19ee38423158034c4f26253

Done:
- [ ] funnel3d module
- [ ] API docs
- [ ] demo

To do:
- [ ] article for general docs

**Comment by KacperMadej** [comment]
The general docs article draft: https://docs.google.com/document/d/1qnysmpCwLR68qaYR8cdh8vZt3PhEebcfHRJZaTqdido/edit#heading=h.nc0dzws9revo

**Comment by TorsteinHonsi** [comment]
Thanks, great work on the geometry! Two questions:

- Have you tried applying gradient colors to the 3D shapes? Without it, they don't really appear like 3D objects in space.
- The data label placement is a bit off in both the funnel and pyramid sample. We now have the `inside` option working on funnels, that could work good if the position is translated in 3D space. Otherwise, if not using `inside`,  the labels should have connectors pointing to the shapes.

**Comment by KacperMadej** [comment]
@TorsteinHonsi 
1. Gradients were postponed (discussed with Havard), but I can take care of them now.
2. I'll check the labels placement.

Those two issue are rather minor, so maybe to avoid any complications with later code merging I would prepare a PR? It the fixed `inside` dataLabels logic committed on the hc71/master branch?

**Comment by TorsteinHonsi** [comment]
> Gradients were postponed (discussed with Havard), but I can take care of them now.

Yes, please. At the very least we should have it in the demos.

> It the fixed inside dataLabels logic committed on the hc71/master branch?

It's currently on https://github.com/highcharts/highcharts/tree/feature/10036-datalabels-inside-funnel-2, awaiting some tests and checking from @wchmiel .

**Comment by KacperMadej** [comment]
@TorsteinHonsi 
Linear gradient is now working fine. Radial works too, but I'm not sure where would be a good center for it - based on a shape? based on point? based on chart? I'm already using pie's `setRadialReference`.

This doesn't look good:
![highcharts-funnel3d-char 1](https://user-images.githubusercontent.com/8960408/54020836-09ad6c80-418f-11e9-951c-dde4b4e63141.png)

**Comment by TorsteinHonsi** [comment]
I don't think radial gradients make much sense at all, so we may as well leave the center like that.
