### ISSUE TITLE
Top border is hidden on columns chart when value is yAxis max value

### ISSUE THREAD

**Issue by natalan** [highcharts/highcharts#9370]
#### Expected behaviour
Top border should be shown when a column is at max value allowed by yAxis

#### Actual behaviour
No top border
![image](https://user-images.githubusercontent.com/276187/48227718-0d5fec80-e371-11e8-9b83-6bb165763fb8.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/w3g5mfe0/

#### Product version
Highcharts 6.2.0

#### Affected browser(s)
Chrome 70 and maybe other.

**Comment by TorsteinHonsi** [comment]
Not sure whether this is a bug - it can be argued that the lower border should also be visible, since both the column and the axis start at 0. 

A way to avoid this would be to user a higher yAxis max or a `maxPadding`, combined with `endOnTick`: http://jsfiddle.net/highcharts/nyurv4tq/

**Comment by karolinakuzniewicz** [comment]
What about the bottom border? Even if the yAxis or xAxis is not visible the border is hidden. It is very hard to make progress bar chart without axes cause still one of the border (in my case left) is not visible. Here is the link: http://jsfiddle.net/zKgsF/133/. How to make every bar's border visible ?

**Comment by KacperMadej** [comment]
![chart 71](https://user-images.githubusercontent.com/8960408/48341321-0d136a00-e66d-11e8-8a7c-01705c6ad09f.png)

@karolinakuzniewicz  All borders are visible for me (Win 10 / Chrome)

**Comment by KacperMadej** [comment]
@karolinakuzniewicz Welp, it's from the demo from you previous comment. I just added exporting module, because it was faster for me to use it than a screen shot, but in case small differences are important - here's a screenshot:

![border-easdffffd344](https://user-images.githubusercontent.com/8960408/48363233-bece8d00-e6a5-11e8-9d85-f197436beb09.jpg)

**Comment by karolinakuzniewicz** [comment]
@KacperMadej there is assigned the min value for yAxis
``` 
yAxis: {
     max: 100.1,
     min: -.1
}
```
and yes, that's works and add left border but also move chart to the right. I'm looking for the solution that allowed to add full border to chart without moving and resizing it. I think that somehow the yAxis override chart's border even if the axis is hidden. @TorsteinHonsi wdyt ?

**Comment by pawelfus** [comment]
It all happens in crisping logic (hiding top and bottom borders, preventing from blurred edges etc.). We can simply override this, take a look: http://jsfiddle.net/BlackLabel/35xaw7to/

**Comment by karolinakuzniewicz** [comment]
thanks @pawelfus a lot for that hack! Unfortunately I can't use this in my project setup (vue+ts), typescript throws an error while calling this function and assigning it to static type `Highcharts`. I've used jquery setup in my jsfiddle only because it was easier and faster to explain that problem. Should we consider this border hidding as a bug in Highcharts ?

**Comment by KacperMadej** [comment]
@karolinakuzniewicz 
About the issue in Vue+TS: you could load the custom code give by Paweł in a similar way as it's done with modules - those files also have code that changes similar elements. If you would like us to help about this problem further then please contact [support](https://www.highcharts.com/support) or write directly on [highcharts-vue](https://github.com/highcharts/highcharts-vue)

**Comment by karolinakuzniewicz** [comment]
@KacperMadej I'm using Highcharts library instead of highcharts-vue due to lack of the types for highcharts-vue and other inconvenient differences so no need to change the repo. My question is: will be this issue treat as a potential bug ?

**Comment by KacperMadej** [comment]
It might be a bug, it's undecided for now.
Currently we are in a phase of investigating the issue and gathering feedback.
