### ISSUE TITLE
Tooltip background does not keep up with content with useHTML=true (IE/Edge)

### ISSUE THREAD

**Issue by anselmbradford** [highcharts/highcharts#9374]
#### Expected behaviour

Tooltip background keeps up with movement of tooltip content.

#### Actual behaviour

![geomap_tooltip](https://user-images.githubusercontent.com/704760/48272491-b6a7f080-e40c-11e8-91d0-66c954f059c8.gif)

#### Live demo with steps to reproduce
Haven't been able to reproduce in a jsfiddle, but hoping someone else has run into this issue in their setup.

EDIT: 
Fiddle http://jsfiddle.net/nc2g61r7/62/ 

![geomap_tooltip_ie11](https://user-images.githubusercontent.com/704760/48579327-27a64700-e8ea-11e8-99a0-f00e3d52676a.gif)

#### Product version
6.2.0

#### Affected browser(s)
IE/Edge.

**Comment by TorsteinHonsi** [comment]
I tried to replicate this in jsFiddle, but it seems to behave well in Edge: http://jsfiddle.net/highcharts/wd8chbpg/4/

If you can change anything in my fiddle to provoke the issue, please update.

**Comment by anselmbradford** [comment]
I've turned off all styles on highcharts-tooltip, and when the background doesn't follow and I remove and apply the stroke `.highcharts-color-4` it brings it back to its correct position:

![geomap_tooltip_stroke](https://user-images.githubusercontent.com/704760/48521600-2a019600-e843-11e8-8375-a7f0239544e8.gif)

Any hunch on what that could mean? I imagine that's forcing a redraw.

@TorsteinHonsi Still trying to reproduce in a jsfiddle… 

FWIW it's reproducible inside https://github.com/cfpb/cfpb-chart-builder/pull/152
Should be able to do it with:
```
git clone https://github.com/cfpb/cfpb-chart-builder
git checkout highchart6_layout
./setup.sh && gulp build && gulp watch
```
…and visit http://localhost:5000

**Comment by anselmbradford** [comment]
@TorsteinHonsi I have a fiddle for you! http://jsfiddle.net/nc2g61r7/62/ 
I can't believe it, it's related to https://github.com/highcharts/highcharts/issues/9266

The mere presence of this selector (doesn't need to contain any rules), causes the behavior shown in this issue. ???

```css
.highcharts-map-navigation[transform="translate(10,38)"] text {    
}
```

**Comment by KacperMadej** [comment]
@anselmbradford Thank you for the demo.
The problem is visible in IE11 (I'm not able to recreate this in Edge).
This reminds me of a somewhat similar issue: https://github.com/highcharts/highcharts/issues/5255
That issue was fixed as a side effect, so it's hard to apply a similar logic here.

Rather obvious workaround is to do not use the problematic CSS.
Or you could try with full/pure HTML tooltip - http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/tooltip/usehtml/

**Comment by anselmbradford** [comment]
@KacperMadej Glad you're able to see it! I was feeling crazy 😆. Yeah, I ended up using your solution in https://github.com/highcharts/highcharts/issues/9266#issuecomment-436033281, which by avoiding the attribute selector `[transform="translate(10,38)"]` worked around the problem.
