### ISSUE TITLE
Datalabels on Line Chart with series values close to each other confusing

### ISSUE THREAD

**Issue by GMUDuckman** [highcharts/highcharts#9376]
#### Expected behaviour
When values are close to each other on a multiseries line chart, if you have allowOverlap: false (or the default) it hides labels that would overlap with each other.

#### Actual behaviour
This functionality happens, but can lead to confusing results.  In some cases the label for the series with a higher value shows, in other cases the series with a slightly lower value shows. This can make it hard to determine which point's data label is actually showing.

#### Suggested solution
Add a display option for the data labels. Instead of just hiding labels that will overlap, move them so they both display.  In a 2 line scenario, you can set the higher value to display above the line, and the lower value display below. I started writing a function to account for this, but my math skills aren't what they need to be. Here is code that takes all of the series, and pushes each everything into one array. So if 

function movePoints(chartObj) {
    var arr = [];

    $.each(chartObj.series, function (i, series) {
        if (series.data.length > 0) {
            arr.push(series.data);
        }
    });
    if (arr.length > 0) {
        var allPoints = [];
        $.each(arr[0], function (index, point) {
            var obj = {};
            $.each(arr, function (ind, ser) {
                obj[ind] = ser[index];
            });
            allPoints.push(obj);
        });
        console.log(allPoints);
    }
}

arr[0] = {series[0].point[0],series[1].point[0],series[2].point[0]}
arr[1] = {series[0].point[1],series[1].point[1],series[2].point[1]}
arr[1] = {series[0].point[2],series[1].point[2],series[2].point[2]}
etc.

from there I would assume you can calculate if they overlap based on their Y position and font height. then move accordingly?

#### Live demo with steps to reproduce
https://jsfiddle.net/q8rtg7bd/

#### Product version
Highcharts

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestion! In practice it will be much more complex, as there may be any number of points, so moving up or down may lead to chain collisions. Our idea for resolving this is to apply forces to the labels, so each label is attracted by its point, but repelled by other labels. It was originally part of the roadmap for v7, but we may not make it.
