### ISSUE TITLE
Gantt Scrollable

### ISSUE THREAD

**Issue by MrMoronIV** [highcharts/highcharts#9378]
Is it really not possible to define a scrollable yAxis with a fixed height for gantt rows?

I can set the height of the chart, but it makes everything in the gantt chart really small, imagine having 100 rows, it would become impossible to work with....

I can also set overflow:auto; on the container div but then the label will disappear, since the labels are inside the svg I cannot make them sticky using CSS. Is the most obvious thing for a gantt chart impossible to do in highcharts or am I missing something?

**Comment by TorsteinHonsi** [comment]
You can make the gantt chart scrollable by adding the stock module and adding a scrollbar, but it doesn't seem to be very well optimized: http://jsfiddle.net/highcharts/sopg2qv8/6/.

A better solution I think would be if we implemented [scrollablePlotArea](https://api.highcharts.com/highcharts/chart.scrollablePlotArea) for the height as well.

**Comment by jon-a-nygaard** [comment]
**Note:** The PR #10205 fixes an issue with collapsed treegrid (axis breaks) in combination with the use of scrollbar that causes an error. It does however not include any further improvements to the usability of scrollbar with gantt.

**Comment by flakey-bit** [comment]
Seems like viewporting (for performance with many rows) would be good to do here. Is that planned?

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestion, could you elaborate a bit on what you mean by viewporting?

**Comment by flakey-bit** [comment]
Basically, only asking the DOM to render the rows _that are actually visible_ (plus say an additional 20% on either side).

As the user scrolls, the "window" of rendered rows will change (if it's done well, it is transparent). 

One technique is to use an empty DIV above and below the rendered rows, the top DIV will grow as the user scrolls down whilst the bottom DIV will shrink. 

The technique is used commonly with grid controls and what not.

It does usually mean a fixed row height though.

**Comment by TorsteinHonsi** [comment]
Ok, similar to what we do with points on an axis then, when there are more than a certain number of elements, we only render those that are visible in the given axis span. See [cropThreshold](https://api.highcharts.com/highcharts/series.column.cropThreshold). Actually this should come more or less for free if we make the scrollbar class work well with the gant chart.

**Comment by perfectstrong** [comment]
I'm having a problem with scrollable gantt chart as well.
![image](https://user-images.githubusercontent.com/23375518/57601111-ef5f8880-755b-11e9-9b36-ae250a42cf35.png)
1. My jobs lay on **whole day**, which require minWidth option (i already chose 2000, otherwise all ticks will collapse. Navigation does not work well in my case).
1. The yAxis scrollbar stays at the end of chart, which seems really ugly and unintuitive. It **should** stay above the chart so that user can use easily.
![image](https://user-images.githubusercontent.com/23375518/57601425-bf64b500-755c-11e9-9c03-4fc83de075d2.png)
I dont really want to mess with styledMode because it makes my gantt chart black entierly.

**Comment by sebastianbochan** [comment]
Hi @perfectstrong,
Could you update the demo: https://jsfiddle.net/BlackLabel/zymtxg7c/1/ with your simplified chart's configuration (including data) ? It will allow us to debug your case and find a solution.

**Comment by perfectstrong** [comment]
Hope this illustrates my point: https://jsfiddle.net/qynh6rjw/2/

**Comment by aaronbeall** [comment]
+1 one to have `scrollPlotArea` support Gantt. Seems that the stock module scrollbar thing performs pretty badly with more than 10-20 rows, and isn't a native scrollbar so it looks out of place and doesn't respond to mouse wheel events.

**Comment by TorsteinHonsi** [comment]
Work in progress: https://highcharts.github.io/highcharts-utils/samples/#gh/f67b942449/sample/highcharts/chart/scrollable-plotarea-vertical

Next is to get the bottom axis fixed.

**Comment by lebesnec** [comment]
Has this been fixed ?  I haven't been able to make a scrollable gantt with Highcharts 8 or 9 : https://jsfiddle.net/fvh650n3/22/

**Comment by KacperMadej** [comment]
The originally reported issue was resolved and the issue was closed. However, the feature still doesn't work well in every case so the issue is reopened. In short: no.

**Comment by KacperMadej** [comment]
Working correctly since v9.1.0
