### ISSUE TITLE
cannot print chart on Safari 11.1

### ISSUE THREAD

**Issue by sonnguyent1** [highcharts/highcharts#9393]
#### Expected behaviour
all charts can be printed on Safari 11.1

#### Actual behaviour
No preview page appeared

#### Live demo with steps to reproduce

Click "Print chart" on context menu.

#### Product version

Highcharts@6.1.2
#### Affected browser(s)
Safari 11.1
Mac OS X 10.13.5

**Comment by sonnguyent1** [comment]
I even  tried printing charts on page Highcharts Demo . But it doesn't work either.

**Comment by TorsteinHonsi** [comment]
Safari 12.0 seems to work well.

**Comment by sebastianbochan** [comment]
I run the the demo: https://jsfiddle.net/BlackLabel/p63yc8da/ in the Safari 10.1. Works well.

Let me know about your MacOSX version.

**Comment by sonnguyent1** [comment]
> I even tried printing charts on page Highcharts Demo . But it doesn't work either.

**Comment by sonnguyent1** [comment]
> I run the the demo: https://jsfiddle.net/BlackLabel/p63yc8da/ in the Safari 10.1. Works well.
> 
> Let me know about your MacOSX version.

I am using version 10.13

**Comment by sebastianbochan** [comment]
Hi @sonnguyent1,
Is it reproducible in any other browser? Unfortunately Im not able to replicate the issue.

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
