### ISSUE TITLE
Regression: Filled paths on line chart

### ISSUE THREAD

**Issue by frontier777** [highcharts/highcharts#9394]
<img width="598" alt="ecosresults-linechart-err" src="https://user-images.githubusercontent.com/3082939/46225399-1350bf80-c327-11e8-9fc9-df25692fe2a4.png">

Browsers:

Chrome Mac: Version 69.0.3497.100 (Official Build) (64-bit)
Firefox Mac: 62.0 
Client reported it on iOS Safari: Unsure which version

_Originally posted by @maljones in https://github.com/highcharts/highcharts/issues/8865#issuecomment-425518809_

**Comment by TorsteinHonsi** [comment]
I set up a replication of this chart at http://jsfiddle.net/highcharts/06jLyvhs/, but can't reproduce the filled areas.

I also set up the entire page context from https://www.ecosresults.org/states/alabama/ and replaced it with newest Highcharts, but couldn't replicate.

Are you able to set up _something_ that shows the issue?

If not, can you show some screenshot from the Chrome Developer Tools, highlighting the filled element so we can see where the fill comes from?

**Comment by TorsteinHonsi** [comment]
I found the cause - it comes from a mismatch between the JS version and the CSS version in styled mode. When you update highcharts.js, you also need to use the matching version of highcharts.css.

* Failing chart with mismatch: http://jsfiddle.net/highcharts/06jLyvhs/6/
* Updated chart using matching versions: http://jsfiddle.net/highcharts/06jLyvhs/8/

**Comment by frontier777** [comment]
Oh doh! That could definitely apply in my case, will confirm.

**Comment by frontier777** [comment]
Argh, yes in my case I was still using the old 6.1.0 css file. Sorry for this and thank you for your help!

**Comment by maljones** [comment]
Cheers for finding that! I'm working further on that project at the end of the month so I'll swap things around and see how it goes.
