### ISSUE TITLE
highcharts column stroke in styled mode

### ISSUE THREAD

**Issue by ouaigooo** [highcharts/highcharts#9395]
#### Expected behaviour
When using highcharts with a column chart in styled mode, I cannot change the color of the column border (borderColor property in normal mode). Setting

.highcharts-point {
    stroke: black;
}

has no effect ! (stroke-width works, but not stroke)

#### Actual behaviour
No effect on borderColor

#### Live demo with steps to reproduce
https://jsfiddle.net/ouaigooo/42xgm5r7/

#### Product version
Highcharts 6.2.0

#### Affected browser(s)
Firefox Chrome

**Comment by sebastianbochan** [comment]
Hi @ouaigooo,
Thank you for reporting. In our stylesheet there is `.highcharts-column-series rect.highcharts-point` class which overwrites  `.highcharts-point` class.

The solution is using the highest reference to class.

**Demo:**
- https://jsfiddle.net/BlackLabel/d41bsxLn/

**Internal note**
I think that we should mention about it in our docs or, better, update the stylesheet. @TorsteinHonsi what do you think?

**Comment by ouaigooo** [comment]
Great. Thanks for the quick answer!
