### ISSUE TITLE
Series label module - possibility to set animation from the API

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#9396]
It will be great to have a possibility to disable series-labels animation from the API. 

#### Live demo with steps to reproduce
[DEMO](https://jsfiddle.net/Bastss/1qs67g5r/)

#### Product version
Highcharts 6.2.0 - series-label.js module

**Comment by sebastianbochan** [comment]
Hi @Basts,
The labels are animated later because processing of them are heavy, so we need to wait until the animation is done.

**Internal note**
It looks like delay is required, but when we set `animation.duration` as 0, labels are also delayed.
		            ```
if (initial) {
		                delay = Math.max(
		                    delay,
		                    H.animObject(series.options.animation).duration
		                );
}
```

**Comment by raf18seb** [comment]
@sebastianbochan,
There is an opacity animation too. If you set opacity to 1, series labels don't animate at all and this is what we would like to easily disable through API:

`var attr = {
		                            opacity: chart.renderer.forExport ? 1 : 1,
		                            x: best.x,
		                            y: best.y
		                        },`

**Comment by jmalStorm** [comment]
+1
