### ISSUE TITLE
Highcharts not displaying all the data on large samples

### ISSUE THREAD

**Issue by tudor7gheorghiu** [highcharts/highcharts#9399]
#### Expected behaviour
I have a 10 year span on my xAxis and the value of an investment fund on the yAxis. I expect it to show the value for each day and the respective date when I hover over it.

#### Actual behaviour
It displays only the Monday value for each week. However, if I zoom in and the time span gets smaller than 3 years aprox all days are accessible. I suppose it is a default behaviour of the API when there are too many data samples, but I couldn't any way to overwrite it in your documentation.

#### Live demo with steps to reproduce
I don't have a jsfiddle to show, since I cannot reproduce the large data set. I attached the code snippet of my chart declaration:
`function createPerformanceChart(chartData) {

    var navigatorSeriesData = [];
    //we shoudl wait for the data to load first.
    if (chartData.length !== 0) { navigatorSeriesData = chartData.PerformanceData[2]}
    var perfchart = new Highcharts.StockChart({
        chart: { renderTo: 'PerformanceChart' },
        navigator: {
            series: {
                data: navigatorSeriesData[3],
            },
        },
        series: chartData.PerformanceData,
        credits: { enabled: false },
        rangeSelector: {
            buttons: [{ type: 'month', count: 1, text: '1m' },
            { type: 'month', count: 6, text: '6m' },
            { type: 'year', count: 1, text: '1y' },
            { type: 'year', count: 3, text: '3y' },
            { type: 'all', text: 'All' }],
            inputEnabled: true, selected: 5
        },
        legend: {
            align: 'center',
            enabled: true,
            layout: 'horizontal',
            maxHeight: 100
        },
        title: {
            text: chartData.PerformanceTitle
        },
        tooltip: {
            valueDecimals: 2
        },
        yAxis: {
            opposite: false
        },
        xAxis: {
            minRange: 3600 * 24000, // one day 
            
        },
        plotOptions: {
            series: {
                dataGrouping: {
                    dateTimeLabelFormats:
                    {
                        week: ['%A, %b %e, %Y', '%A, %b %e', '-%A, %b %e, %Y']
                    },
                },
            }
        }
     } , function (chart) {
            // apply the date pickers
            setTimeout(function () {
                $('input.highcharts-range-selector', $(chart.container).parent())
                    .datepicker();
            }, 0);
        });
    
    // Set the datepicker's date format
    $.datepicker.setDefaults({
        dateFormat: 'yy-mm-dd',
        onSelect: function () {
            this.onchange();
            this.onblur();
        }
    });

    if (navigatorSeriesData.length === 0 && perfchart != null) {
        perfchart.showLoading('Loading Data...');
    }
}`
#### Product version

Highcharts
#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @tudor7gheorghiu,
Thank you for contacting us. This is our bugtracker, so for general [support](http://www.highcharts.com/support) cases, please use stackoverflow / forum or email.

ps. Highstock uses [dataGrouping](https://api.highcharts.com/highstock/plotOptions.series.dataGrouping) for increasing performance. You dan disable it by the option.
