### ISSUE TITLE
Split tooltip: font size and wrongly aligned text

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#9400]
#### Behaviour
Labels in split tooltip are not aligned vertically if font size is changed.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/fhd6bjqL/1/

Hover over chart to see tooltip and that axis label is not centered vertically.
Change font sizes to see it better if it's not clear.

**Comment by jon-a-nygaard** [comment]
Thanks for reporting, we are currently looking into the issue, and will come back with an update as soon as we have more information.

*Internal Note: [Simplified demo](https://jsfiddle.net/jon_a_nygaard/ykp5r91z/)*

**Comment by TorsteinHonsi** [comment]
It happens because the font size given inside the string conflicts with the font size given by and applied to the outer `g` item. 

Broken down to the SVGRenderer: http://jsfiddle.net/highcharts/dea78gu1/.
