### ISSUE TITLE
Treemap: Error when deleting `point.dataLabel`

### ISSUE THREAD

**Issue by leonelgalan** [highcharts/highcharts#9404]
#### Expected behaviour
Treemap hides labels that don't fit in rectangle. This is accomplished by a `load` event:

```
function () {
  const points = this.series[0].points;
  points.forEach(function(point) {
    if (point.shapeArgs.width < point.dataLabel.width) {
      point.dataLabel.destroy();
    }
  });
}
```

This solution was proposed by _Kamil Kulig_ in [StackOverflow](https://stackoverflow.com/a/49750334/637094)

#### Actual behaviour
An error similar to the one described in #7021 is thrown: 

```
highcharts.js:54 Uncaught TypeError: Cannot read property 'isSVG' of undefined
    at a.SVGElement.destroy (highcharts.js:54)
    at e.destroyElements (highcharts.js:286)
    at e.destroy (highcharts.js:286)
    at e.destroy (highcharts.js:314)
    at a.Chart.destroy (highcharts.js:274)
    at a.Chart.getContainer (highcharts.js:259)
    at a.Chart.firstRender (highcharts.js:275)
    at a.Chart.<anonymous> (highcharts.js:250)
    at a.fireEvent (highcharts.js:31)
    at a.Chart.init (highcharts.js:249)
```

This only happens locally if a point's `dataLabel` is destroyed. Otherwise the chart renders just fine. Same code works fine in JSFiddle, see Live Demo.

#### Live demo (unable to reproduce)
https://jsfiddle.net/a79h4vnt/

The code works as intended on JSFiddle. The same configuration will error locally. Highcharts was installed through NPM. I'm hoping someone can help me build a reproducible example, so we can get this fixed.

#### Product version
Highcharts 6.2.0

#### Affected browser(s)
All

**Comment by leonelgalan** [comment]
I bypassed the issue by updating the point to disable _dataLabels_ and triggering a `redraw` after.

```js
function() {
  const { points } = this.series[0];
  points.forEach(function(point) {
    if (point.shapeArgs.width < point.dataLabel.width ||
        point.shapeArgs.height < point.dataLabel.height) {
      // point.dataLabel.destroy();
      point.update({
        dataLabels: {
          enabled: false,
        },
      });
    }
  });
  this.redraw();
}
```

I'm happy to help troubleshoot the reported issue, I tagged the version with it and can revert back as needed.

**Comment by KacperMadej** [comment]
Hi @leonelgalan 

Without a live demo we could only guess. Maybe you are loading something not from an official NPM packages? Please try with `.src.js` instead of `.js`, so the debugging message will be referring to unminified file lines - for Highcharts and it's modules. From the error's call stack it seems like your chart is destroyed right after it's created, so probably there something strange or unexpected is happening.

Please recreate the problem in a sandbox that supports your way of loading Highcharts, so we could debug the error and test possible solutions. You could try e.g. codesandbox, plunker, codepen, etc.

In case a live demo is not possible you could provide files to run locally with steps required to run it.

**Comment by leonelgalan** [comment]
Thanks for responding, is definitely pulling from the right package, here is the un-minimized stack trace:

```
highcharts.src.js:4802 Uncaught TypeError: Cannot read property 'isSVG' of undefined
    at H.SVGElement.destroy (highcharts.src.js:4802)
    at object.destroyElements (highcharts.src.js:28693)
    at object.destroy (highcharts.src.js:28661)
    at object.destroy (highcharts.src.js:33189)
    at H.Chart.destroy (highcharts.src.js:27812)
    at H.Chart.getContainer (highcharts.src.js:26821)
    at H.Chart.firstRender (highcharts.src.js:27865)
    at H.Chart.<anonymous> (highcharts.src.js:26047)
    at H.fireEvent (highcharts.src.js:2548)
    at H.Chart.init (highcharts.src.js:25920)
```

I am using `react-highcharts` and I just realized there is a 'highcharts-react' which is the official package, I'll try to try to setup a code pen with it and report back.

**Comment by leonelgalan** [comment]
@KacperMadej thanks for your help, I'm not sure I agree with the "not a bug, because it uses custom code" argument. It uses highchart's API after all and it produces an unhandled error. It appears that adding the following lines to my code works:

```js
delete point.dataLabel;

if (point.dataLabels) {
  delete point.dataLabels;
}
```

Shouldn't `destroy()` handle this? It's odd to have to do this manual cleanup afterwards.

Thanks again for your help, I'll ask in the appropriate channels more about deleting the data labels vs. updating the point, and the nuances of using _afterDrawDataLabels_ and not just _load_.

**Comment by KacperMadej** [comment]
[Destroy](https://api.highcharts.com/class-reference/Highcharts.SVGElement#destroy) is a part of API, but handling dataLabels removal is not.
Supported way to handle this is to update point with changed dataLabels options as you have done in you workaround.

One of the important differences between the events in question is that `afterDrawDataLabels` event is fired in a private `drawDataLabels` function, so it's not a part of public API and it's a series event while [`load`](https://api.highcharts.com/highcharts/chart.events.load) is a chart's event.

**Comment by pawelfus** [comment]
Let me clarify things here a bit:

```javascript
function () {
  const points = this.series[0].points;
  points.forEach(function(point) {
    if (point.shapeArgs.width < point.dataLabel.width) {
      point.dataLabel.destroy();
    }
  });
}
```
This is not what Kamil suggeested. `hide()`, not `destroy()` was suggested.

The way you use `destroy()` is wrong, it should also clear the dataLabel definition:
```javascript
point.dataLabel = point.dataLabel.destroy();
```

Answering your further question:
> Shouldn't destroy() handle this? It's odd to have to do this manual cleanup afterwards.

I think it shouldn't - `destroy()` destroys elements inside the object (all event, DOM references etc.) but does not modify parent's references. If that would be `point.destroyDataLabel(point.dataLabel)` then I would agree. Otherwise it's wrong to remove `point.dataLabel` in `dataLabel.destroy()` method.

**Comment by leonelgalan** [comment]
@pawelfus, the post was updated and it now reads `.hide()`, it didn't when I posted, but I'll definitely give that a try.

@KacperMadej thanks for for the detailed response.

**Comment by KacperMadej** [comment]
Let me explain the confusion that I have caused. I have asked Kamil to fix the demo, so it will not throw any errors and that he did. So, it was `destroy` at the time of my previous comment and it was changed to avoid any errors for others.
