### ISSUE TITLE
MapNavigation is not wrappable

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#9409]
In map.js module, MapNavigation object is not wrappable.

#### Product version
Highmaps 6.2.0
[module link](http://code.highcharts.com/maps/modules/map.src.js)

**Comment by KacperMadej** [comment]
_Internal note:_
The relevant part from parts-map: https://github.com/highcharts/highcharts/blob/master/js/parts-map/MapNavigation.js
`stopEvent` and `MapNavigation` are private, not accessible from outside.
