### ISSUE TITLE
Narrator + Edge unable to interact with chart legend

### ISSUE THREAD

**Issue by JllyGrnGiant** [highcharts/highcharts#9414]
#### Expected behaviour
Able to reach the chart legend using the keyboard,
Able to navigate through the legend using arrow keys,
Able to activate the focused legend item to hide/show series using space/enter,
Narrator announces what series label you're focused on and shown/hidden state.

#### Actual behaviour
Able to reach the legend items when scan mode is off, but Narrator doesn't announce anything while interacting with the legend items or navigating through them.
When scan mode is on, it isn't clear how to reach the legend items or use the keyboard to navigate through and interact with them.

#### Live demo with steps to reproduce
Highcharts 6.2.0 at the time this issue was created.
https://www.highcharts.com/samples/highcharts/accessibility/accessible-line/

1. Navigate to demo
2. Turn on Narrator
3. Press tab until chart is focused
4. Try arrow keys/tab/other keys while in scan on/off mode of Narrator to try to interact with the legend items

#### Product version
Highcharts 6.2.0

#### Affected browser(s)
Edge

**Comment by KacperMadej** [comment]
Hi @JllyGrnGiant 

Thank you for reporting about the problem.

@oysteinmoseng - accessibility module issue

**Comment by oysteinmoseng** [comment]
Interesting, for some reason it seems the legend items are not getting any ARIA attributes. I will look into this.

**Comment by oysteinmoseng** [comment]
See this example: https://jsfiddle.net/eqsrva6x/

I am able to get the legend items to be selectable with JAWS, but I can not seem to get Narrator to select the items, despite using `button` roles. Are you aware of any limitations with Narrator with regards to button roles on SVG elements?

**Comment by oysteinmoseng** [comment]
This will be fixed by upcoming v7.1.
