### ISSUE TITLE
Custom 2 finger panning in Highchart in Mobile along with pinch-zoom

### ISSUE THREAD

**Issue by rsoni0809** [highcharts/highcharts#9416]
I need help to capture 2 finger panning event in Highchart on mobile so that I can pass my custom min and max extreme to re-render Chart.

chart.event.selection I am able to get pinch and zoom but when I am swiping my chart with 2 finger, I am not able to capture this event. 
Do we have any custom function which can capture 2 finger panning in highchart in mobile without modifying pinch-zoom.
Any one got this usecase where able to capture pinch-zoom and 2 finger panning and making it customize

**Comment by KacperMadej** [comment]
Hi @rsoni0809 

We are using github as our bug tracker. For tech support please use - https://www.highcharts.com/support

P.S.
Highcharts are internally checking event type (`e.type`) and event's touches length (`e.touches.length`) to check which event is being processed.
