### ISSUE TITLE
Map for latest provinces and communes of Burundi

### ISSUE THREAD

**Issue by pzisynergy** [highcharts/highcharts#9419]
#### Expected behaviour
For our application we would like to create choropleth and bubble maps using HighMaps for country Burundi with its latest 18 provinces and communes. The latest geo-jasons are required from HighMaps

#### Actual behaviour
Old Burundi map is available which is of no use for our app.

**Comment by pzisynergy** [comment]
The old map by HighMaps
![highmaps_burundi](https://user-images.githubusercontent.com/45089248/48601113-ac4d9f80-e994-11e8-9c19-2cfd5a52245d.png)


The latest map of burundi with 18 provinces
![provinces_of_burundi_latest](https://user-images.githubusercontent.com/45089248/48601144-c5565080-e994-11e8-83e6-823490dd77bf.png)

**Comment by sebastianbochan** [comment]
Hi @pzisynergy,
Thank you for reporting. At this moment the updated map is not available yet, but you can customize it by QGIS tool. You can find the manual here: https://www.highcharts.com/docs/maps/custom-geojson-maps.

**Comment by pzisynergy** [comment]
Thanks for providing the link. But we want to create boundaries for burundi as well as all provinces of burundi. Is it possible with this tool to get exact boundaries?

**Comment by pzisynergy** [comment]
No. We have whatever wikipedia shows.
https://en.wikipedia.org/wiki/Provinces_of_Burundi

**Comment by pzisynergy** [comment]
Thank you.
 Please check if the following link helps
https://data.humdata.org/dataset/burundi-administrative-level-0-1-and-2-administrative-boundaries

**Comment by KacperMadej** [comment]
Here's a demo for admin1:
http://jsfiddle.net/BlackLabel/y8tgx5je/1/

Map file added in the HTML section of the demo.

I'm working on admin2.

**Comment by pzisynergy** [comment]
Thanks that was quite quick. Appreciate.
Hope we get support for commune level maps as well.
Hope the link i shared in previous comment helps.
Thanks again.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#28
