### ISSUE TITLE
[Wordcloud] Change color onHover

### ISSUE THREAD

**Issue by Naimikan** [highcharts/highcharts#9422]
Hi,

I'm trying to assign a new color when we hover a word in a wordcloud, but I don't know if it's possible or if I'm doing something wrong. Is there any way to do it?

**Live demo**: https://jsfiddle.net/Naimikan/se2da6rz/66/
**Highcharts version**: 6.1.1

Thanks!

**Comment by sebastianbochan** [comment]
Hi @Naimikan,
Thank you for reporting. It looks like a bug, but you can use events like below.

**Workaround**
Use [mouseOver](https://api.highcharts.com/highcharts/plotOptions.wordcloud.point.events.mouseOver) / [mouseOut](https://api.highcharts.com/highcharts/plotOptions.wordcloud.point.events.mouseOut) events and apply a color by `css()` method.

Demo:
- https://jsfiddle.net/BlackLabel/apenmu3j/

@jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
Yes, this seems to be a bug.
Right now it is only taking the color from `Point.color`, but it should likely use `Series.pointAttribs` to get the  color.

**Comment by sebastianbochan** [comment]
Unstale

**Comment by khlieng** [comment]
Fixed since 7.0.2.
