### ISSUE TITLE
Highmaps Map Navigation Zoom button styles are [object Object]

### ISSUE THREAD

**Issue by frankieali** [highcharts/highcharts#9424]
#### Expected behavior
When inspecting the style attribute for the "Zoom In" and "Zoom Out" buttons, one should see valid CSS styles

#### Actual behavior
On inspection of `highcharts-map-navigation` the style attribute is `style="[object Object]"`

#### Live demo with steps to reproduce
https://www.highcharts.com/maps/demo/all-maps

#### Product version
Highmaps JS v6.2.0 (2018-10-17)

#### Affected browser(s)
All

**Comment by frankieali** [comment]
I think the problem resides here https://github.com/highcharts/highcharts/blob/master/js/parts-map/MapNavigation.js#L103 where a merged object is assigned to `attr.style`. Instead, you should first merge the object then flatten it out to a string before assigning it to `attr.style`.
For Example:
```
let stylesObj = merge({},
  buttonOptions.theme.style,
  buttonOptions.style
);
let styles = "";

for(let key in stylesObj){
  styles += `${k}:${stylesObj[k]};`;
}
attr.style = styles;
```

**Comment by KacperMadej** [comment]
Hi @frankieali 

Thank you for reporting about the problem.

**Comment by pawelfus** [comment]
Unstale
