### ISSUE TITLE
No option for scroll

### ISSUE THREAD

**Issue by TeodorKolev** [highcharts/highcharts#9425]
I am using https://www.highcharts.com/demo/column-negative chart with 400 items of xAxis data.  ```
scrollbar: {
        enabled: true,
      },
did not help. Some of data are passed. It is something like every 6 items are passed.
```
#### Expected behaviour
Should be able to scroll. Should be able to see all items

#### Actual behaviour
Unable to scroll. Unable to use all items

#### Live demo with steps to reproduce
<!-- template: https://jsfiddle.net/highcharts/LLExL/ -->

#### Product version
<!--- Highcharts, Highstock or Highmaps plus version number -->

#### Affected browser(s)

**Comment by sebastianbochan** [comment]
Hi @TeodorKolev,
This is our bugtracker. For general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

ps. At this moment, the scrollbar is a part of Highstock only.
