### ISSUE TITLE
IgnoreHiddenSeries with stacked column

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#943]
When set to true works fine, but when false doesn't show proper columns (height is miss calculated).
 Example: http://jsfiddle.net/highcharts/T8KW7/ and related topic: http://highslide.com/forum/viewtopic.php?f=9&t=17280

**Comment by sebastianbochan** [comment]
Since 4.0.1, shape is correct (http://jsfiddle.net/k5wf3pwy/), but should be or not moved at the bottom?

**Comment by pawelfus** [comment]
Works fine in v5: http://jsfiddle.net/BlackLabel/T8KW7/2/
