### ISSUE TITLE
Unable to use chart.addSeries on Gantt chart

### ISSUE THREAD

**Issue by whawker** [highcharts/highcharts#9479]
#### Expected behaviour
Adding a gantt series via `chart.addSeries` should have the same behaviour as defining a series on initialisation, via `Highcharts.ganttChart({ series: [{/* ... */ }] })` 

Desired output: https://jsfiddle.net/rxcf0nyw/

#### Actual behaviour
When adding a series dynamically, all the series points are rendered on top of each other

Suspect this is related to [this code](https://github.com/highcharts/highcharts/blob/f10463e11d153df7effd726cde972822dac8b771/js/parts-gantt/TreeGrid.js#L527-L566) which is only called on initial render?

#### Live demo with steps to reproduce
https://jsfiddle.net/jyuqxf5b/

#### Product version
Highcharts Gantt - 6.2.0

#### Affected browser(s)
Chrome, likely all

**Comment by KacperMadej** [comment]
Hi @whawker 

Thank you for reporting about the problem.

Looks like a bug in Gantt @oysteinmoseng @jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
Yes, that seems to be a clear bug with the Treegrid axis.

## Potential workaround
In cases like this where there is no use of a hierarchy, the issue can be avoided by using a category axis and setting the y values manually: https://jsfiddle.net/jon_a_nygaard/ewzjt0fa/

**Comment by PaulDalek** [comment]
+1
