### ISSUE TITLE
Small chart with large timerange, few data points an datagroupint disables renders strange

### ISSUE THREAD

**Issue by Sinmson** [highcharts/highcharts#9480]
#### Expected behaviour
Anyhow the chart is able to render the data that is looks valuable and useable.

#### Actual behaviour
Columns get rendered in the air somehow.

#### Live demo with steps to reproduce
http://jsfiddle.net/vyoqm2fr/1/

#### Product version

We are using 6.0.5 but the fiddle uses the newest one.

#### Affected browser(s)
Every

#### Thoughts
The timerange is about 10 hours, but the data points are only in 1 hour. When the chart gets smaller the bars begin to "stack" and the lower ones get hidden.

I think important is the fact that dataGrouping is disabled. We disabled this because for some values it would not be accurate (creating an avg without the actual count).

**Comment by TorsteinHonsi** [comment]
What you're seeing is the white borders overlapping the neighbour column. If you remove the `borderWidth` setting for column charts, it looks okay: http://jsfiddle.net/highcharts/vyoqm2fr/4/.

By default, the border width is 1 when there is room for it, but it defaults to 0 in situations like yours, when the border would cover the next column: http://jsfiddle.net/highcharts/svroLybm/ . I can see that this is not clear from the API though, so I'll update the description.
