### ISSUE TITLE
Annotation doesn't disappear when pie slice is hidden by legend

### ISSUE THREAD

**Issue by kutensky** [highcharts/highcharts#9481]
Given Pie chart with few annotations added to some slices and legend shown.

#### Expected behaviour
Clicking on legend item hides pie slice and annotation attached to it disappear.

#### Actual behaviour
Clicking on legend item hides pie slice, but annotation is still shown.
It happens because pie slice doesn't really disappear, it just become minimum size, so Annotations module think that slice is still shown.

#### Live demo with steps to reproduce
https://jsfiddle.net/h027tfLq/

#### Product version
6.2

**Comment by TorsteinHonsi** [comment]
I would expect annotations attached to hidden points to be invisible. Assigning to @KacperMadej , please reassign as appropriate.

**Comment by kutensky** [comment]
As a workaround, I've edited redrawItem method in annotations.js.
I've added next code inside "if (item-itemType === 'label')" block:
`
var isPointsHidden = points.every(function(p) {
	return p.options.visible === false || p.series.options.visible === false;
});

isPointsHidden ? item.hide() : item.show();
`

**Comment by TorsteinHonsi** [comment]
See also #9217.
