### ISSUE TITLE
Check box is not working properly while drillup in highcart latest version

### ISSUE THREAD

**Issue by vishavgandotra** [highcharts/highcharts#9485]
#### Expected behaviour
While performing drilling in highchart, if a case arises when I first uncheck any of the checkbox among series and then do drilldown, then data of that particular series is not visible and if I again drill up back the data of that particular series will not be visible with its particular checkbox as unchecked.

#### Actual behaviour
But it is not behaving like this. When I reproduce the above mentioned steps and then perform drill up, data of that particular series whiech was earlier unchecked is not shown but its checkbox is checked.

I am attaching a file which has code with which you can reproduce this proble. I have used latest version of highchart.
[highchart with checkbox.txt](https://github.com/highcharts/highcharts/files/2602880/highchart.with.checkbox.txt)

**Comment by vishavgandotra** [comment]
Hi @KacperMadej 

Yes sure next time I will create a live demo. Thank you for creating a live demo for this and understanding it. I hope you will resolve this as soon as possible.

Thank you.

**Comment by TorsteinHonsi** [comment]
Yes, as you can see above it is closed with a fix. 

Here's the demo with the fix applied: https://jsfiddle.net/highcharts/eqy36r85/
Here's the fix itself: https://github.com/highcharts/highcharts/commit/371b094379df25f962d8a051ad03815d6f0d32b7

**Comment by TorsteinHonsi** [comment]
#### Workaround
While waiting for the next release, here's a drop-in fix for you: 
```js
Highcharts.wrap(Highcharts.Series.prototype, 'select', function (proceed, selected) {
	proceed.call(this, selected);
    
	this.options.selected = selected;
});
```
View it [live on jsFiddle](https://jsfiddle.net/highcharts/eqy36r85/5/).

**Comment by vishavgandotra** [comment]
Thank you so much for resolving this. :)
