### ISSUE TITLE
Indicators - points are rendered incorrectly after series.setData()

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#9493]
#### Expected behaviour
After series.setData() all points should be rendered within the plot area.

#### Actual behaviour
After series.setData() some points are rendered out of plot area.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/j1undfgL/

#### Product version
Highstock

#### Affected browser(s)
all

**Comment by sebastianbochan** [comment]
**Workaround:**
Call indicator `chart.series[1].update()` to recalculate values.

Demo:
- http://jsfiddle.net/BlackLabel/j1undfgL/25/
