### ISSUE TITLE
Highcharts Boost module renders markers although data is dense

### ISSUE THREAD

**Issue by devritter** [highcharts/highcharts#9498]
#### Expected behaviour
No markers when data is dense, 
markers when zoomed in a lot

#### Actual behaviour
Markers at the beginning, 
markers after a little zooming, 
no markers when zooming further, 
markers when zoomed in a lot

#### Live demo with steps to reproduce
https://jsfiddle.net/wsv0h6ae/

#### Product version
Highcharts v6.2.0 + Boost module

#### Affected browser(s)
Chrome 70
Firefox 63
Microsoft Edge 44

**Comment by TorsteinHonsi** [comment]
In non-boosted mode, the drawPoints method looks at the `closestPointRangePx` value, the closest distance between any two points, and determines whether we should draw a marker or not. This seems to be broken in the Boost. I assume `closestPointRangePx` isn't available in the Boost as we're doing translations in WebGL, so we then need to recreate similar logic.

https://github.com/highcharts/highcharts/blob/a578eb60e8baf4f4f36ed4470e122990b0b818dc/js/parts/Series.js#L4125-L4133
