### ISSUE TITLE
Boxplot zoom is broken when using categorical x axis

### ISSUE THREAD

**Issue by marco-boeck** [highcharts/highcharts#9500]
#### Expected behaviour
When I zoom into a boxplot with a categorical x axis and then zoom back out, it should look like it did before I did any zooming.

#### Actual behaviour
When I zoom into the plot and then reset the zoom, the originally zoomed values are now clumped together at the left side of the chart. The x axis ticks become broken at that point as well.

#### Live demo with steps to reproduce
https://jsfiddle.net/9bmut61g/

#### Product version
HighCharts 6.2

#### Affected browser(s)
All browsers

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

It's your lucky day, this is a long-standing issue that has been fixed earlier today. See #6926.

See https://jsfiddle.net/highcharts/ak36sjf2/ for your fiddle with the fix applied. 

#### Workaround
Until the fix is released, you can increase the `cropThreshold`: https://jsfiddle.net/highcharts/ak36sjf2/2/

**Comment by wjaspers** [comment]
This appears to have regressed in version 9+ (tested in 9.1.2, 9.2.2) when using a 
The cropThreshold workaround appears to behave as desired.

**Comment by raf18seb** [comment]
Hi @wjaspers, could you provide a demo and the exact steps to reproduce?

**Comment by wjaspers** [comment]
Failing demo:
https://jsfiddle.net/xe8ro5pz/

Any brushing/zooming applied will yield weird results. I didn't even need to externally update the chart.

**Comment by raf18seb** [comment]
Thanks for the demo! I was able to reproduce it. It is a different issue than described in this issue so I created a new one: https://github.com/highcharts/highcharts/issues/16322
