### ISSUE TITLE
MouseOut and MouseOver Events called continuously when mouse is hovered between the slices in pie chart

### ISSUE THREAD

**Issue by ff-sgupta** [highcharts/highcharts#9501]
#### Expected behaviour
Either MouseOut or MouseHover event should be called (only once)

#### Actual behaviour
Both MouseOut and MouseHover event called continuously

#### Live demo with steps to reproduce
http://jsfiddle.net/3v3xfh6e/56/

Open browser console. Now hover over in between any two slices(on the white space which separates two slices).

Observe that the slice continuously slices in and out even when the mouse is static and in the console log we can see the mouseout and mousehover event printed

#### Product version
Highcharts JS v6.2.0

#### Affected browser(s)
Any. I have tested using chrome

**Comment by ff-sgupta** [comment]
Thank you for the response. 
Apologies didn't realise this when was working on the sample. I have a fiddle with the events on point where the slice transitions but with same issue. Is it because of the animation I have?

http://jsfiddle.net/qk4rfbot/1/

**Comment by sebastianbochan** [comment]
Hi @ff-sgupta,
I apologize for my late reply. Could you point me out how it should work step by step?

**Comment by ff-sgupta** [comment]
@sebastianbochan Steps are as follows:

1. hover on the border joining the two slices (green and blue one)
2. Do not move mouse now

You should see the blue slice moving in and out even though the mouse is not moved ( which is not expected). Please let me know in case your not able to reproduce it. May be I can take a video and share
