### ISSUE TITLE
Negative databalel Issue

### ISSUE THREAD

**Issue by VBIManonmaniM** [highcharts/highcharts#9506]
#### Expected behaviour
We want to set the padding for data labels,When I am setting y value for my datalabel, negative datalabels doesn't take the reverse path.

#### Actual behaviour
I want to adjust the data label for negative values in the opposite direction 

#### Live demo with steps to reproduce
http://jsfiddle.net/38w0fx42/1/

#### Product version
Highcharts

#### Affected browser(s)
All browsers

**Comment by sebastianbochan** [comment]
Hi @VBIManonmaniM,
Thank you for reporting. I prepared a simple workaround which extracts y offset and align negative datalabel in the right position.

```
function reposition () {
   var chart = this,
   		series = chart.series,
      each = Highcharts.each,
      y,
      yOffset;
      
  each(series, function(serie) {
  	yOffset = serie.options.dataLabels && serie.options.dataLabels.y;

  	each(serie.data, function (point) {
      if (point.y < 0 && point.dataLabel) {
      	y = point.dataLabel.y
    		point.dataLabel.attr({
        	y: y - 2 * yOffset
        });
      }
    });
  });
}
```

Demo:
- http://jsfiddle.net/BlackLabel/sj0ch8dn/

**Internal note**
It looks like the issue in the `column.prototype.alignDataLabel` method.

**Comment by TorsteinHonsi** [comment]
This is how the `y` option works, it offsets the label in pixels.

Why not use the `padding` option? http://jsfiddle.net/highcharts/o6w1ankb/

**Comment by VBIManonmaniM** [comment]
Thank you for the response
