### ISSUE TITLE
Annotations not work in mobile, but work in PC

### ISSUE THREAD

**Issue by Luey168** [highcharts/highcharts#9514]
#### Expected behaviour
Annotations should display both in PC browser and mobile browser.

#### Actual behaviour
Annotations work correctly in PC Chrome, Safari, and Firefox. However, when in mobile Chrome or Safari, the annotations are not displayed. They are displayed only when you zoom to 'All', not displayed on any other time frame. 

#### Live demo with steps to reproduce

http://jsfiddle.net/BlackLabel/w3f9p6yt/

#### Product version

<script src="https://code.highcharts.com/stock/highstock.js"></script>

#### Affected browser(s)
Chrome, Safari, Firefox

**Comment by Luey168** [comment]
Hi KacperMadej,

Thank you so much for your reply. The problem occurred in iOS platform, not sure about Android. And the browsers I use are safari and chrome.

**Comment by sebastianbochan** [comment]
Hi @Luey168,
Thank you for reporting. You are right, its the bug and is reproducible on iOS (12.x).

**Comment by Luey168** [comment]
awesome!

**Comment by sebastianbochan** [comment]
The bug is fixed in the newest 7.1.1 version.

iOS 12.2
