### ISSUE TITLE
Series update for Variwide while zoomed changes series data for un-zommed chart

### ISSUE THREAD

**Issue by matsomo** [highcharts/highcharts#9525]
#### Expected behaviour
Original columns are displayed when clicking "Reset zoom"

#### Actual behaviour
Columns that are not part of the zoom selection are removed when clicking "Reset zoom"

#### Live demo with steps to reproduce

1. Zoom 
2. Select column while zoomed in
3. Click "Reset zoom"

https://stackblitz.com/edit/react-amqzi2

#### Product version
Highcharts: 6.2.0
highcharts-react-official: 2.0.0

#### Affected browser(s)
Chrome, Edge, FireFox, Opera

**Comment by matsomo** [comment]
Hi
Yeah, the second demo you provided shows my problem. Is there a way to stop the update form happening in the React wrapper?

**Comment by ppotaczek** [comment]
Hello @matsomo,

You call `setState` after point click event, which trigger `chart.update()`.

To prevent the update, use `allowChartUpdate` option:

      <HighchartsReact
        highcharts={Highcharts}
        allowChartUpdate={this.props.allowChartUpdate}  // false
        options={{ ... }}
      />

Live demo: https://stackblitz.com/edit/react-ssvnnx?file=HighchartsOfficialChart.jsx

**Comment by matsomo** [comment]
Hey @ppotaczek, thanks for the suggestion.

This takes care of the issue if the window is not resized. Pressing "Reset zoom" will still cause the same problem in the following scenarios: 
1. Zoom in
2. Select point
3. Resize window
4 "Reset zoom"
and
1. Select point
2. Zoom in
3. Resize window
4 "Reset zoom"

**Comment by ppotaczek** [comment]
@matsomo, thank you for the details. This is a bug related with `variwide` series type and `chart.redraw` on zoomed chart.

To workaround, you can set `cropThreshold` to a higher value than the number of points:

      series: [{
        cropThreshold: 9e9,
        ...
      }]

Live demo: https://stackblitz.com/edit/react-fnwb1s?file=HighchartsOfficialChart.jsx

**Comment by matsomo** [comment]
This seems to have done the trick. Thanks a lot for your help
