### ISSUE TITLE
Axes change the position of bubbles in Bubble Chart

### ISSUE THREAD

**Issue by karolinakuzniewicz** [highcharts/highcharts#9527]
#### Expected behaviour
Bubbles should not change their position while changing the xAxis and yAxis visibility. That's how this chart should look like but without axes.
https://jsfiddle.net/emsyavw3/6/

#### Actual behaviour
Bubbles (perhaps the plot area) position (x,y) should be the same if axes are visible or not. Actual behaviour makes really hard to create a venn chart. In this particulart example bubbles should stick to each other at the bottom border. This happen only if both axes are visible. Changing the visibility to false change also the position of bubbles some way.

#### Live demo with steps to reproduce
https://jsfiddle.net/srw1t9ze/

#### Product version
Highcharts 6.2.0

#### Affected browser(s)
Chrome latest version

**Comment by karolinakuzniewicz** [comment]
There is something wrong also with bubble radius. The biggest one in jsfiddle is should be 200x200 pixels with radius value 100 but the actual path element size is 200x200 pixels and the radius value is 98 to make space for a grid line which I think is incorrect. The bubble should be as big as its points values in series (x=0, y=0, z=100)

**Comment by TorsteinHonsi** [comment]
It is important to note that `z` is not a radius in terms of Y axis (nor X axis) values. The z value just dictates how big the bubbles are compared to each other and the `zMin`, `zMax`, `minSize` and `maxSize` options. 

If you want to map it to Y axis values, one solution could be to use `yAxis.height` to make the pixel height predictable: https://jsfiddle.net/highcharts/Lgvfxcna/

We recently had another user expecting the same behaviour as you did (bubble size being mapped to Y axis values), so this is an enhancement we need to consider.

**Comment by TorsteinHonsi** [comment]
Proposal: Take two additional possible settings for `sizeBy`: `yAxis` and `xAxis`.

**Comment by karolinakuzniewicz** [comment]
Thanks for your quick reply. Setting `yAxis.height` does the job. Now everything chart works fine. The last thing is that the `yAxis` object does not have `height` key and setting that throws an error but also solves the problem.
