### ISSUE TITLE
Pitchfork annotation getting stuck in dragging mode after right mouse click

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#9528]
#### Expected behaviour
Right mouse click in chart opens browsers context menu. Mouse click outside the context menu closes the context menu. 

#### Actual behaviour
Mouse click outside the browsers context menu is closing the menu. But the pitchfork is stuck in drag mode and can't be released from it.

#### Live demo with steps to reproduce
http://utils.highcharts.local/samples/#view/highcharts/studies/stocktools-custom-gui

#### Product version
Highstock 7

**Comment by TorsteinHonsi** [comment]
Probably the drag functionality should listen for mouse up on the document itself, not only the chart container. This is a common pattern.
