### ISSUE TITLE
Stroke can't be applied for labels in Stack column Charts

### ISSUE THREAD

**Issue by sbala69gmail** [highcharts/highcharts#9529]
Hai ,
 
We faced the problem when inserting stack column chart to the canvas, **stroke** for the labeled text as been removed. Kindly guide me if anyone know about this

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

PS: Here's how to set data label color: http://jsfiddle.net/highcharts/pLo9wbfm/

**Comment by sbala69gmail** [comment]
Thanks TorsteinHonsi. 

But in the above **PS** , the chart as append in **DIV**. I have a issue while draw the chart only on **CANVAS**. Kindly guide me if anyone know about this.

**Comment by TorsteinHonsi** [comment]
I think there is a misunderstanding here. Highcharts doesn't render on canvas. For further support, please use http://www.highcharts.com/support.

**Comment by sbala69gmail** [comment]
Hi TorsteinHonsi,

Highcharts can render on canvas,

![chatr](https://user-images.githubusercontent.com/2879062/49494606-313a2380-f886-11e8-86a5-3f3a04a88c10.png)

But we faced the problem when inserting stack column chart to the canvas, stroke for the labeled text as been removed.

**Comment by pawelfus** [comment]
Hi @sbala69gmail 

Please contact our support: www.highcharts.com/support and provide **live demo**. Thank you!
