### ISSUE TITLE
yAxis labels cut off when scrolling comes on chart 

### ISSUE THREAD

**Issue by psparmeet14** [highcharts/highcharts#9533]
#### Expected behaviour
YAxis and it's labels should remain intact on printing chart. Even if there was scrolling on highchart, the printed view must have yAxis and it's labels uncut

#### Actual behaviour
On clicking print on export context menu, in the print preview chart's yAxis and it's labels are getting cut off if scrolling comes. But if by default there is no scrolling, graph renders properly with YAxis and it's labels present. But as soon as we compress or expand the viewport scrolling comes and then on printing highchart, yAxis and it's labels cut off.

#### Live demo with steps to reproduce
http://jsfiddle.net/ykpcdu8b/

#### Product version
highcharts v6.1.4

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! It is now fixed in the working branch for v7, due for release in December.
