### ISSUE TITLE
findNearestPointBy disable for scatter

### ISSUE THREAD

**Issue by Groude** [highcharts/highcharts#9534]
Hello!
I have a scatter chart, and i want to disable this option: **findNearestPointBy**, is there any possible solutions to do it?

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

PS: I don't quite understand what you mean by disabling this. This option is used for finding the point that is closest to the mouse pointer. It searches either by `x` or by `xy`. If you want to disable the tooltip, you should set `tooltip.enabled` to false, or `series.enableMouseTracking` to false.
