### ISSUE TITLE
useHTML causes x-axis labels to not ellipses

### ISSUE THREAD

**Issue by rlm1023** [highcharts/highcharts#9537]
#### Expected behaviour
X-Axis labels should ellipses themselves when they overflow their space.

#### Actual behaviour
When `useHTML` is set, they no longer seem to ellipsis themselves

#### Live demo with steps to reproduce
http://jsfiddle.net/6dzfyeg8/

#### Product version
v6.2.0

#### Affected browser(s)
Chrome

**Comment by rlm1023** [comment]
@TorsteinHonsi Did you forget to save? That fiddle looks the same to me.

**Comment by rlm1023** [comment]
Looking at that fix the alignment is now off. If I make the strings longer, things get crazy:
http://jsfiddle.net/1x6h4qye/

**Comment by pawelfus** [comment]
Hi @rlm1023 

Thanks! 

@TorsteinHonsi simplified demo: http://jsfiddle.net/BlackLabel/uvofa7ky/

**Comment by TorsteinHonsi** [comment]
Fix of the fix: http://jsfiddle.net/BlackLabel/uvofa7ky/

**Comment by sebastianbochan** [comment]
@TorsteinHonsi 
As I see it has been already merged, but the case its not closed. Any comment ?

**Comment by TorsteinHonsi** [comment]
It's probably because the final fix was called "Addition to...". Closing now.
