### ISSUE TITLE
Scroll breaks when i collapse elements

### ISSUE THREAD

**Issue by ganiamine** [highcharts/highcharts#9547]
#### Expected behaviour
I build a Gantt chart using the highcharts API.
 I added a scrollbar on the yAxis, it should works when i collapse to show or hide sub elements.
#### Actual behaviour
When i collapse elements to hide sub-Lines of a category the length of yAxis is not updated.

#### Live demo with steps to reproduce
https://jsfiddle.net/lodou/6up1gezf/

#### Product version
6.2.0

#### Affected browser(s)
ALL

**Comment by KacperMadej** [comment]
Hi @ganiamine 

Thank you for reporting about the Highcharts Gantt problem.

**Comment by jon-a-nygaard** [comment]
The #10176 is a duplicate of this issue, but since there is a PR connected to the mentioned issue, then I will close this as a duplicate instead.

For further updates on the issue please see #10176.
