### ISSUE TITLE
draggable-points module: Drag column with reversed yAxis

### ISSUE THREAD

**Issue by jeansey** [highcharts/highcharts#9549]
#### Expected behaviour
When enabling dragging on serie with 'column' type and a reversed y axis i want to be able to drag the columns

#### Actual behaviour
Because the y axis is reversed i can't drag the serie with 'column' type. 
The drag handles seems to be hidden on top of the column.

#### Live demo with steps to reproduce
http://jsfiddle.net/h2839sfo/
Try to drag the 'column' type serie

#### Product version
Highcharts 6.2.0

#### Affected browser(s)
Firefox - 60.0.1
Chromium - 66.0.3359.181

**Comment by KacperMadej** [comment]
Hi @jeansey 

Thank you for reporting about the problem.

Here's a workaround for you - code fixing the problem added at the top of JS code - http://jsfiddle.net/BlackLabel/7t2srLzy/1/
