### ISSUE TITLE
Incorrect axis labels when cropped series data table updated

### ISSUE THREAD

**Issue by markhobson** [highcharts/highcharts#9561]
#### Expected behaviour

Given a chart driven by a data table that exceeds the series crop threshold, updating the underlying data should display the axis labels as per the initial render.

#### Actual behaviour

The axis labels for new points in the series alternate between names and positions.

#### Live demo with steps to reproduce

Demo of replacing all table data with new points: https://jsfiddle.net/markhobson/c1pwLjs7/
Click 'Update data' button. Crop threshold is set to 10, so replacing these 11 points triggers this problem. Note that the axis labels alternate between A-K, 11-21, and 0-10. Works as expected when crop threshold is increased to 11.

Demo of just adding a new point: https://jsfiddle.net/markhobson/yj7bt3u5/
Click 'Add point' 6 times. Crop threshold is also set to 10, so adding points works until this threshold is crossed. Note that the axis labels for new points start as numeric positions, and then correct themselves on subsequent renderings.

#### Product version

Highcharts JS v6.2.0 (2018-10-17)

#### Affected browser(s)

Firefox, Chrome.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

This issue has been resolved by fixing #5857. However, fixing #9197 results in no updates when the same options are set again using `chart.update`, so you need to use `chart.data.update` to refresh the data table:

* https://jsfiddle.net/highcharts/vw4rzbLt/
* https://jsfiddle.net/highcharts/e46qahfL/

**Comment by markhobson** [comment]
Thanks for the quick reply! Good to know that it'll be fixed in the next release.

Is there any way of preserving the animation when updating the entire data table? Running your second fiddle with `cropThreshold=100` has animation, but `cropThreshold=10` doesn't.

**Comment by TorsteinHonsi** [comment]
Nice catch, it took me a while to figure out why. But now it's fixed.

**Comment by markhobson** [comment]
Awesome, thanks @TorsteinHonsi!
