### ISSUE TITLE
Display of chart on drillup from drilldown on a chart with two series is incorrect

### ISSUE THREAD

**Issue by kengineer** [highcharts/highcharts#9562]
#### Expected behaviour
When a chart has multiple series and one of the series has a drilldown, when you drilldown and then drill back up, the chart would display like it does when it first loads

#### Actual behaviour
The second series is missing, but an extra data point is added to the end of the first series (sort of)

#### Live demo with steps to reproduce
https://jsfiddle.net/kengineer/qp60asf1/

1. Click Run in jsfiddle (while in my web application the chart initially loads correctly, in jsFiddle the problem manifests itself right away. If you click Run in the the jsfiddle, the chart loads correctly)
1. Drilldown on any point
1. Drillup to the first chart
1. notice now that there is an extra category on the x-axis with the value "7" and it appears the second series is condensed down into one point. 

#### Product version
I'm using Highcharts 6.2 but 4.2.5 is the last version it worked correctly. The following jsfiddle uses 4.2.5 and it works as expected https://jsfiddle.net/1s0Lv3b4/

#### Affected browser(s)
Chrome
IE Edge
Probably others

**Comment by TorsteinHonsi** [comment]
Simplified demo: https://jsfiddle.net/highcharts/wnv3gc9q/

**Comment by TorsteinHonsi** [comment]
#### Workaround
Set `xAxis.uniqueNames` to `false`:
https://jsfiddle.net/highcharts/wnv3gc9q/4/

**Comment by TorsteinHonsi** [comment]
Original demo with the fix applied: https://jsfiddle.net/highcharts/rc9ut18s/
