### ISSUE TITLE
Pattern fills with image disappear on hover 

### ISSUE THREAD

**Issue by ejubkadric94** [highcharts/highcharts#9563]
I have a colum chart with pattern fill background set on a point using `series.point.color.pattern.path.d`. And I also set the same pattern with different color on hover of the series, using `series.states.hover.color.pattern.path.d` and `series.states.hover.color.pattern.color`.

Then, I realized that I had some specific svg files which I would like to use as background pattern fill for the chart, and I went on to add it using `series.point.color.pattern.image`, and I created the same svg file with another stroke color, and saved it, so I can use it for hover background. I set it using `series.states.hover.color.pattern.image`.

My problem is that now, once I replaced the good old `path` way of creating pattern fills in highcharts, with the image pattern fills, once I hover on my point for the first time, for a moment, charts background is completely WHITE. And then after some time (like half a second), the svg that I specified for hover - is applied. It looks to me that highcharts somehow takes time to load the image, although I gave it the image in its binary form (please see the actual behavior fiddle).

After the initial hover over the point, pattern fill background and hover pattern fill background are switched with no problems, with no delay, and with no flashy white background. Is there a way to kill this flashing white?

#### Expected behaviour
https://jsfiddle.net/5kn9h8oy/14/
So in this fiddle, as soon as you hover over the point for the first time (and for every next time you hover over it), the red pattern background is replaced with blue one, as soon as you hover over it).

#### Actual behaviour
https://jsfiddle.net/5kn9h8oy/13/
In this fiddle, when you hover over the point for the first time, the red pattern is replaced with white non pattern background for a split of a second (maybe 400 milliseconds), and after that it is replaced with the blue pattern fill. 
Then if you move your pointer off the point, and then again hover over the point, there will be no flashy white background (looks like the image is loaded now, so no delay there).
I want to avoid this white background moment on first hover. 
(To see the issue again, RUN the fiddle again and hover over the point)

#### Product version
Highcharts 6.2.0, but I also reproduced it on the latest version (see the fiddles above)

#### Affected browser(s)
Latest Chrome - Version 70.0.3538.110 (Official Build) (64-bit)
Latest Firefox

**Comment by TorsteinHonsi** [comment]
Thanks for your patience @ejubkadric94 and sorry for the delay. The team is busy preparing v7 nowadays.

It seems like animation doesn't have anything to do with this. Apparently it is the processing of the new pattern that takes a fraction of a second, and causes the white blink. You can overcome that by adding the pattern to the renderer prior to hovering, so that it is already present for the first hover. There's a function `Chart.addPattern` that takes care of this. 

```js
Highcharts.addEvent(Highcharts.Chart, 'load', function () {
	this.renderer.addPattern({
    	id: 'hover-pattern',
        image: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyOCIgaGVpZ2h0PSI0OSIgdmlld0JveD0iMCAwIDI4IDQ5Ij48ZyBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxnIGlkPSJoZXhhZ29ucyIgZmlsbD0iYmx1ZSIgZmlsbC1ydWxlPSJub256ZXJvIj48cGF0aCBkPSJNMTMuOTkgOS4yNWwxMyA3LjV2MTVsLTEzIDcuNUwxIDMxLjc1di0xNWwxMi45OS03LjV6TTMgMTcuOXYxMi43bDEwLjk5IDYuMzQgMTEtNi4zNVYxNy45bC0xMS02LjM0TDMgMTcuOXpNMCAxNWwxMi45OC03LjVWMGgtMnY2LjM1TDAgMTIuNjl2Mi4zem0wIDE4LjVMMTIuOTggNDF2OGgtMnYtNi44NUwwIDM1Ljgxdi0yLjN6TTE1IDB2Ny41TDI3Ljk5IDE1SDI4di0yLjMxaC0uMDFMMTcgNi4zNVYwaC0yem0wIDQ5di04bDEyLjk5LTcuNUgyOHYyLjMxaC0uMDFMMTcgNDIuMTVWNDloLTJ6Ii8+PC9nPjwvZz48L3N2Zz4=",
        width: 30,
        height: 50
    })
});
```
[View it live on jsFiddle](https://jsfiddle.net/5kn9h8oy/15/).

**Comment by ejubkadric94** [comment]
Thanks a lot. `this.renderer.addPattern` solves my problem. Although the fiddle you provided does not load properly for some reason. 
Thanks :)

**Comment by pawelfus** [comment]
Fixed demo from the comment above: https://jsfiddle.net/BlackLabel/5ur1df2p/ (wrong URL for loading highcharts).

**Comment by ejubkadric94** [comment]
Thank you. This id done as far as I am concerned :)
