### ISSUE TITLE
y-axis max ignored in charts with multiple y-axes

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts#9574]
#### Expected behaviour
y-axis max should be applied even if there are multiple y-axes

#### Actual behaviour
y-axis max is not considered if there are multiple y-axes

#### Live demo with steps to reproduce
https://jsfiddle.net/1w2L03f9/

Tertiary yAxis max is set to 1019, but axis is drawn up to 1024

#### Product version
6.2

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
See https://api.highcharts.com/highcharts/yAxis.max for what other factors affect the `max`. If we set `alignTicks` to false and `endOnTick` to false, we get the expected max: https://jsfiddle.net/1w2L03f9/1/
