### ISSUE TITLE
Printing rotated text in VML will overlap its neighbour

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#960]
1. Start IE8
2. Open http://jsfiddle.net/B58P4/ containing 5 rotated labels. Only using the renderer here, not the entire library.
3. Print the document (for example to a file with pdf creator)

Result: Only the last label is fully readable, the others have been covered with a white bounding box, probably from the next label after it,

Expected: The same output as in the browser.

**Comment by cvasseng** [comment]
Hi! We're doing a bit of spring cleaning, and closing old issues. If you're still experiencing issues with this, please feel free to open a new issue! Thanks!
