### ISSUE TITLE
Highcharts does not update as expected

### ISSUE THREAD

**Issue by muperi** [highcharts/highcharts#9600]
Highcharts does not seem to update as expected. I originally have a pie chart and I try to update the options to load a line chart and the chart is blank when updated. I have a live demo below.

If you click the update button twice then it seems to load the chart, however the axis also seems to be flicker when you do that.

http://jsfiddle.net/f6fydL8p/95/

**Comment by pawelfus** [comment]
Hi @muperi 

Thank you for reporting the issue. This is problem with duplicated ID's, but even without duplicates it looks broken: http://jsfiddle.net/BlackLabel/r1eakhLb/ - where `plotOptions` are not used correctly.

**Workaround:**
Applying options for each series (with unique ID's) works fine: ttp://jsfiddle.net/BlackLabel/r1eakhLb/1/

Simplified demos:
- duplicated ID's: http://jsfiddle.net/BlackLabel/nxceq79u/ (I'm not sure if it's a bug, point and series share the same ID's.. it's like `<SPAN>` and `<DIV>` could have the same ID's)
- not applied `plotOptions.series.pointInterval` and `plotOptions.series.pointStart`: http://jsfiddle.net/BlackLabel/he5jfnow/

**Comment by muperi** [comment]
Thanks for the swift response. I will use the work around for now. Hopefully the bug gets resolved soon. Will update the thread if I run into other related issues.
