### ISSUE TITLE
Treemap - allowPointSelect is not working

### ISSUE THREAD

**Issue by rajeshdanabal** [highcharts/highcharts#9601]
#### Expected behaviour
Since I am setting **allowPointSelect** to **true** as shown in *https://api.highcharts.com/highcharts/series.treemap.allowPointSelect* ,
when I click on data point in tree map it should show as selected like changing its color and border color.

#### Actual behaviour

Selected data point in tree map is not showing as selected and it remains as it is.

#### Live demo with steps to reproduce

https://jsfiddle.net/jouyk3tx/

#### Product version

v6.2.0

#### Affected browser(s)
Google Chrome - Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Hi @rajeshdanabal 

Thanks for reporting the issue!

I'm not sure what to do here: color is always takes from `colorValue`. All other options works: https://jsfiddle.net/BlackLabel/trgn91yp/1/ (but require some improvement here I think).

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/dh7wmj4o/

Snippet:
```javascript
function setPointColor(point) {
  var color = point.userSelected ? 'rgba(200, 50, 50, 0.5)' : point.mainColor;

  if (point.graphic) {
    point.graphic.attr({
      fill: color
    });
  }

  point.color = color;
}

Highcharts.chart('container', {
  chart: {
    events: {
      redraw: function() {
        this.series.forEach(function(series) {
          series.points.forEach(function(point) {
            setPointColor(point);
          });
        });
      }
    }
  },
  series: [{
    type: 'treemap',
    allowPointSelect: true,
    point: {
      events: {
        select: function() {
          if (!this.mainColor) {
            this.mainColor = this.color;
          }

          this.userSelected = this.userSelected === undefined ? true : !this.userSelected;

          setPointColor(this);

          return false;
        }
      }
    },
    data: [ ... ]
});

```

**Comment by TorsteinHonsi** [comment]
I think it's a bug. Geo maps and heat maps are equivalent. Selected color should take precedence over color value.
