### ISSUE TITLE
Labels overlay with big values

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#9602]
Labels overlay with big values

![dasdasd](https://user-images.githubusercontent.com/6030335/49498874-8e7da700-f87d-11e8-94f4-d3e33f3c5c8a.PNG)

#### Expected behaviour
labels show fully

#### Actual behaviour
Labels overlay

#### Live demo with steps to reproduce
https://jsfiddle.net/4qhL5fvg/

#### Product version
Highcharts version 6.2.0

#### Affected browser(s)
Chrome 71.0.3578.80

**Comment by pawelfus** [comment]
Hi @balkarov 

Thank you for reporting the issue. It's already reported: #8912
