### ISSUE TITLE
Gantt: Draggable-points with breaks (weekends)

### ISSUE THREAD

**Issue by FilipeCosta06** [highcharts/highcharts#9613]
#### Expected behaviour
Using **Gantt Chart**, **xAxis breaks** (on week-ends, in order to have a "working days" only planning) and **draggable points module** : dragging a point (task) over/past a break shouldn't cause issues _(and, ideally, would somehow "split" and expand the point so that the length, for instance 5 work days, stays the same even though the point is, technically, 2 days longer, because the weekend is "skipped")_.

I intend to build an interactive planning on which dragging / resizing points would update the database from which the planning is built: Suppose the task lasts from a Monday to the next Friday (5 working days) and we dragged it to start on Wednesday, I would like to see the point end on the Tuesday of the next week (but that's not a bug, that's more of a feature I'm trying to add). 

As it is now, **the point (task) will visually "shrink" because 2 of the 5 days are "hidden" in the breaks**, and this is perfectly fine _(adding the 2 days to show the point's end on the next week is more of my personal final objective. I realise this isn't what the breaks / draggable are meant to do)_, but there is an **issue depending on where you drop the point**.

#### Actual behaviour
When the **mouse gets too close to the breaks, while dragging**, the point (task) will start **teleporting** / **blinking** nervously. And if you happen to "drop" (stop dragging) at this moment, the task can be lost forever. The point can either become "untargettable" (you can't interact with it anymore, and you cannot see the point label anymore) or straight up disappear !

Also, while I set 0 to the break size, we can still **see the Label of the breaks** but that could be because I only gave the day value when I created the breaks, maybe there is still a few hours / minutes allowed on the xAxis ?
![bug2](https://user-images.githubusercontent.com/25252573/49571258-12489980-f939-11e8-9eb0-fa33cdd3a961.PNG)

#### Live demo with steps to reproduce
https://jsfiddle.net/DixiPoowa/jd9gqn8p/40/
1- Un/Comment the breaks in the xAxis (line 11 to 16) to add/remove the breaks.
2- While breaks are active, drag (hold left click) any of the points (tasks) close to a break (from Saturday to Sunday)
3- When the task blinks / disappears / teleports, stop dragging and you'll "see" the task bugged (invisible or untargettable + no label)

#### Product version
Highcharts JS v6.2.0 (2018-10-17)

#### Affected browser(s)
I've only tested on Chrome "Version 70.0.3538.110 (Official Build) (64-bit)" and Firefox "63.0.3 (64 bits)" but I don't think this is a browser related issue.

File: the arrow shows where my cursor was when I was dragging (on the Friday, 1 day before the break). The two vertical bars next to it are the start and end of a task currently blinking because as I explained.
![bug](https://user-images.githubusercontent.com/25252573/49570764-ce08c980-f937-11e8-8ea3-4e0eff6ed8ec.png)

**Comment by pawelfus** [comment]
Hi @FilipeCosta06 

Thank you for reporting the issue and the detailed description of the issue! We really appreciate that.

**Simplified demo:**
It looks like `draggable` plugin does not matter here, simple `point.update()` causes missing point too: https://jsfiddle.net/BlackLabel/ye3b6kfp/2/

*Internal note:*
What's interesting, that point vanished from `series.points` array (but all others are fine: `xData`, `processedXData`, `data` etc). It looks like `broken-axis` module removes visuals of the point when point is in a break: https://github.com/highcharts/highcharts/blob/1c533d2e2c3ab022521d316f1bcfe2620d75965e/js/modules/broken-axis.src.js#L338-L354

But for multi-dimensional datasets (Gantt, xrange) we should check both `x` and `x2` and when both are inside the break then hide point.

**Comment by pawelfus** [comment]
Hi @FilipeCosta06 

That's correct, `liveRedraw` is one way to go. Alternatively we can use `dragStart`, `drag` and `drop` events to create our custom shadow: http://jsfiddle.net/BlackLabel/c6pdq2bs/

Actually, maybe you want to cancel `drop` event if point is dropped inside a break? 🤔

**Comment by FilipeCosta06** [comment]
Hello @pawelfus 

Yes absolutely. 

I'm fine with the default shadow but since I was planning on visually warning the user that this drop is forbidden (and preventing it, meaning the point won't move if dropped there), I'll be using the events you mentioned. I know this isn't bug related anymore and I shouldn't talk about it here but I think I'll be using these and `chart.xAxis[0].isInAnyBreak(e.newPoint.x)` (demo : http://jsfiddle.net/DixiPoowa/82zbwa15/11/) except, instead of just checking `x`, I'll have have to check `x2` too. I am kind of afraid I may run into performance issues since I'm also checking this in the `drag` event in order to color the shadow in red when needed but other than that, this seems like a great solution. 

Now, on a planning, I think I will expand the task because, if dragged over a break (weekend), I obviously need the task to "last" longer. I'll just have to be careful with infinite loops and probably use `%5` if I ever need to count the number of days in a task I guess.

Really thankful for your custom shadow demo by the way !
