### ISSUE TITLE
Data label   is not  visible for very small value like 0.1 ,0.2 in pie chart

### ISSUE THREAD

**Issue by shandy0** [highcharts/highcharts#9614]
#### Expected behaviour
Data label   should be  visible for very small value like 0.1 ,0.2 in pie chart
#### Actual behaviour
Data label   is not  visible for very small value like 0.1 ,0.2 in pie chart

**Comment by sebastianbochan** [comment]
Hi @shandy0,
I guess that its caused by `allowOverlap` option. Try to set it as true.

Docs:
- https://api.highcharts.com/highcharts/series.pie.dataLabels.allowOverlap

If problem will not be solved, please recreate your example as live demo on the jsfiddle.net. It will allow us to debug it.

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
