### ISSUE TITLE
Chart update in responsive mode causes some of the responsive options noneffective

### ISSUE THREAD

**Issue by mylazygirl** [highcharts/highcharts#9617]
#### Introduction
The example comes from official demo, just added a new button.
- "Small" button will make the chart smaller to entering responsive mode.
- "Small Update" button will make the chart smaller to entering responsive mode, and then call chart.update().
#### Expected behaviour
The margin of title is the same after I clicked "Small" and "Small Update" buttons.
#### Actual behaviour
The margin of title is different after I clicked "Small" and "Small Update" buttons.
- The margin of title is 10, which is defined for responsive, after I click "Small" button.
- The margin of title is 50, which is defined for common, after I click "Small Update" button.

#### Live demo with steps to reproduce
http://jsfiddle.net/7e3wacr1/2/

#### Product version
Highcharts 6.2.0

#### Affected browser(s)
Chrome 70

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

**Comment by KacperMadej** [comment]
@LoganDupont 
Thank you for another demo for the issue

**Comment by njifares** [comment]
Simular issue here. Any update or workaround for this?
