### ISSUE TITLE
Scrolling Issue with xAxis ceiling value

### ISSUE THREAD

**Issue by VBIManonmaniM** [highcharts/highcharts#9618]
#### Expected behaviour
I want the scrolling to be very smooth, But when I am setting ceiling value for xaxis it scrolling becomes very uneven

#### Actual behaviour
I want the scrolling to be very smooth, But when I am setting ceiling value for xaxis it scrolling becomes very uneven

#### Live demo with steps to reproduce
https://jsfiddle.net/3mLx1ze9/

#### Product version
Highstock 

#### Affected browser(s)

All browsers

**Comment by VBIManonmaniM** [comment]
If i set the max which may exceeds the length of xaxis the chart shows remaining numbers,Please refer https://jsfiddle.net/s01xmqnd/

**Comment by pawelfus** [comment]
Thanks for the explanation! At this moment I don't see any better workaround than setting `xAxis.max` conditionally: https://jsfiddle.net/BlackLabel/do0126ur/

**Comment by VBIManonmaniM** [comment]
Is there any other workaround or When it will be fixed

**Comment by pawelfus** [comment]
At this moment we are focused on v7, so I can not provide any ETA.

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: https://jsfiddle.net/highcharts/7mvnhLk5/

PS: It looks a lot better with `scrollbar.liveRedraw` enabled: https://jsfiddle.net/highcharts/7mvnhLk5/2/
