### ISSUE TITLE
BUG: Axis labels of dynamically added series does not display correctly.

### ISSUE THREAD

**Issue by merakmarey** [highcharts/highcharts#9619]
#### Expected behaviour
New series added dynamically should display same axis label since it have same parameters of initial series.

#### Actual behaviour
New axis label display differently. See demo

#### Live demo with steps to reproduce
https://jsfiddle.net/o432q6ge/

#### Product version
Highstock JS v6.2.0 (2018-10-17)

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @merakmarey 

This is expected behaviour. All axes have `offset` calculated dynamically to prevent overlapping (top/height does not matter). When you add new pane (yAxis) with different top/left/width/height you should also define `offset`: https://jsfiddle.net/BlackLabel/b9dsm024/

**Comment by merakmarey** [comment]
I see, thanks!
