### ISSUE TITLE
3d pie chart doesn't hide when using visibilty:hide

### ISSUE THREAD

**Issue by Asanchezvera** [highcharts/highcharts#9623]
#### Expected behaviour
When the contanier where the 3d pie chart is drawn has the css property visibility:hidden the chart isn't shown

#### Actual behaviour
The chart is still being shown, despite it shouldn't.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/ejqpcn68/

#### Product version
Highcharts 6.2

#### Affected browser(s)

Chrome 70
Firefox 63

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! Demo with the fix applied: http://jsfiddle.net/highcharts/2kwhq9n5/

Until the next release, here's a drop-in fix you can use:
```js
Highcharts.addEvent(Highcharts.Chart, 'render', function () {
	[].forEach.call(
    	this.container.querySelectorAll('*[visibility="visible"]'),
        function (elem) {
        	elem.setAttribute('visibility', 'inherit');
        }
    );
});
```
View it [live on jsFiddle](http://jsfiddle.net/highcharts/9hd748wc/).
