### ISSUE TITLE
Improve annotation doclets

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#9628]
- [x] Full namespace of type references needed.
- [x] There are several referenced types missing like `Controllable`.
- [x] ~Mixin and typedef group would not be necessary when using a base class.~
- [x] Classes should not use other classes as namespaces.
- [x] Make use of `@private` tag for internal functions like `init` and mixins (we should not have official mixins).
- [x] Some new interfaces / types should be replaced by existing ones, like `PositionObject`.
- [x] Some referenced classes are not available through the namespace, just by `require` statement. Two options: Replace with a simple `object` reference. Or add the class to a namespace.
- [x] ~Naming is inconsistent, especially `annotations options` vs. `AnnotationOptions`.~
- [x] Type definitions with properties should be interfaces instead.
- [x] Naming of members should be clearer.
   - [x] callbacks end with the suffix `...CallbackFunction`.
   - [x] functions end with the suffix `...Function`.
   - [x] interfaces end with the suffix `...Object`.
   - [x] types should end with the suffix `...Type`.
- [x] ~Sub-namespaces like `Highcharts.Annotations` should have a doclet with a short description. (`@namespace`)~

**Comment by TorsteinHonsi** [comment]
What's the status on this @bre1470 ?

**Comment by bre1470** [comment]
@TorsteinHonsi 
I suggest we leave it out for now. This can not be solved without inside knowledge. I count on the migration, because then we are forced to structure it correctly and at the same time get a clear understanding how types and namespaces are related to each other.

**Comment by bre1470** [comment]
The stroked todo points will be covered with following steps of the TypeScript transition.

**Comment by bre1470** [comment]
Covered by https://github.com/highcharts/highcharts/pull/12574
