### ISSUE TITLE
Zooming into a stacked barchart does not zoom precisely

### ISSUE THREAD

**Issue by MrLight** [highcharts/highcharts#9630]
#### Expected behaviour
Zooming into a stacked barchart, should zoom exactly into the selected region of the stacked bar. This is usefull if you use a gardient fill and especially if you use a pattern-fill image which shows extended informations.

#### Actual behaviour
Zooming into a stacked barchart does not zoom the bar itself precisly. When zooming into a area >50% of a stacked area it fits precisly. When zooming into the lower (lefthand area) the zooming is not precisely. 

#### Live demo with steps to reproduce
http://jsfiddle.net/L6ybtukm/
Please try to click and zoom. Use the gardient fill as "marker".

#### Product version
at least >6.0 

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @MrLight,
Thank you for reporting.

**Internal notes**
Simplified demo:
- http://jsfiddle.net/BlackLabel/c3e8xjL0/

Steps to reproduce:
- click on the button and you can observe that gradient should not be applied.
