### ISSUE TITLE
Gauge Plot bands issue

### ISSUE THREAD

**Issue by sureshjanarthan** [highcharts/highcharts#9635]
#### Expected behaviour
Gauge should show proper plot band irrespective of the min, max and actual value provided.

#### Actual behaviour
It looks like for few negative / edge cases Gauge is not shown properly as provided in the sample. 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/o13nckbh/  

#### Product version
  Highcharts 6 

#### Affected browser(s)
IE, Chrome

**Comment by pawelfus** [comment]
Hi @sureshjanarthan 

Thank you for reporting this bug! You are right, we should hide plotBands that are outside the current range.

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/hk5ft6x8/
Snippet:
```javascript
(function(H) {
  H.addEvent(H.Axis, 'init', function(e) {
    var getPlotBandPath = this.getPlotBandPath;
    if (!this.isXAxis && this.isCircular) {
      this.getPlotBandPath = function(from, to, options) {
        var arc = getPlotBandPath.apply(this, arguments);

        if (
          this.isCircular &&
          to < this.min ||
          from > this.max
        ) {
          // If outside the range, hide plotband:
          arc = [];
        }

        return arc;
      }
    }
  });
})(Highcharts)
```
