### ISSUE TITLE
Boost hiding series

### ISSUE THREAD

**Issue by callumacrae** [highcharts/highcharts#9636]
#### Expected behaviour

Both heatmap and line display.

#### Actual behaviour

Heatmap displays, but line is hidden.

#### Live demo with steps to reproduce
https://jsfiddle.net/chswz1b6/

That's what it's supposed to look like, uncomment boost and the red line will disappear.

Unfortunately, the chart I'm doing this with in my real app is a lot bigger than this, so we have to use boost.

#### Product version
Highcharts 6.2.0

#### Affected browser(s)

Chrome and safari, haven't tested on others

**Comment by cvasseng** [comment]
Fixed.

Demo of fix: https://jsfiddle.net/pgmda703/

[PR](https://github.com/highcharts/highcharts/pull/9644) submitted, and will be merged prior to the next release. 

As a work-around until the fix is live, you can set `boost.allowForce = false` ([demo](https://jsfiddle.net/2ndjb9qv/)).
