### ISSUE TITLE
Export responsive SVG

### ISSUE THREAD

**Issue by ashubham** [highcharts/highcharts#9638]
#### Expected behaviour

When I use the `exporting` features of Highcharts either Offline/Server. And, I select the SVG as the output, the image I get is fixed to the size I request it for. 

Is it possible to have a responsive SVG being exported instead ? Which would resize according to the container/viewport without needing HighchartJS.

I understand html text may not resize properly, but other `path` should work, right ?

I am trying to bulk generate SVGs using Highcharts export functionality and using them on blogs/static sites. But since the output SVG is not responsive, the approach does not work.

**Comment by pawelfus** [comment]
Hi @ashubham 

Thanks for contacting us. However, this is our bug tracker - for questions, please contact our support: https://www.highcharts.com/support

PS: I might be wrong, but in general SVG is an image, so the same CSS rules applies to it. Did you try for example this: https://css-tricks.com/scale-svg/ ?
