### ISSUE TITLE
[solved]Highcharts Sankey Diagram, data color

### ISSUE THREAD

**Issue by alkoval** [highcharts/highcharts#9640]
#### Expected behaviour
Data should be painted in the specified color.

#### Actual behaviour
Data painting uses [random colors](https://imgur.com/1DWr0X4).

#### Live demo with steps to reproduce
https://jsfiddle.net/efobL7c6/

#### Product version
Highcharts JS v6.2.0 (2018-10-17)

#### Affected browser(s)
Last Chrome

**Comment by alkoval** [comment]
Understood. It is necessary to use Nodes.
https://jsfiddle.net/p4f21w7e/

**Comment by pawelfus** [comment]
That's correct, use [nodes](https://api.highcharts.com/highcharts/series.sankey.nodes).
