### ISSUE TITLE
Sonification: Support data grouping

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#9642]
We want to add data grouping to our sonification module. When playing a lot of points in rapid succession we need control over which points are skipped/unintelligible. This could be done by reducing the points actually being played, and selecting/creating these points intelligently.

From the previous discussion on this point, it might be easiest to write this logic from scratch rather than depending on Highstock data grouping. The API options should be similarly structured, however.

**Comment by oysteinmoseng** [comment]
Still relevant.

**Comment by pawellysy** [comment]
unstale

**Comment by oysteinmoseng** [comment]
Re-stale, the current implementation where the sonification mirrors the visual experience should be good for now
