### ISSUE TITLE
Stock Tools Full Screen: Full screen miscalculates pane height after pane resize

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#9643]
#### Expected behaviour
That the panes' relative height be respected

#### Actual behaviour
The pane's absolute height takes precedence

#### Live demo with steps to reproduce
1. https://www.highcharts.com/stock/demo/stock-tools-gui
2. Resize the panes using the splitter in the middle
3. Click FullScreen. The panes don't resize to fill the full screen height.

#### Product version
Highstock v7.0.0

**Comment by pawelfus** [comment]
*Internal note:*
It looks similar to issue #8660 - resizing panes sets positions in pixels, not in percentages.
