### ISSUE TITLE
Spline/Area interpolation don't match

### ISSUE THREAD

**Issue by NickMurphy** [highcharts/highcharts#9646]
#### Expected behaviour
The spline line and area series should follow the same curve for the exact same data

#### Actual behaviour
The area data seems to be linear

#### Live demo with steps to reproduce
https://codepen.io/anon/pen/REPPvN

EDIT:
This is a working version - all I've done is change the chart type to areaspline rather than area
https://codepen.io/anon/pen/vvONJK

#### Product version
Hichcharts 7.0.0

#### Affected browser(s)
Chrome, edge, IE11

**Comment by pawelfus** [comment]
Hi @NickMurphy 

Thanks for contacting us. As you noticed there is `area` and `areaspline`: `area` use the same logic as `line` while `areaspline` uses `spline` for rendering the path.
