### ISSUE TITLE
Sonification: API docs demos have bad JSFiddle JS config

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#9652]
#### Behaviour
For demos from https://api.highcharts.com/class-reference/Highcharts.Chart#sonify
(in `Try it` section) you need to switch in JS box of JSFiddle demo from `No wrap - bottom of <head>` to `No wrap - bottom of <body>` (`LOAD TYPE` option)

This results in an error about not loaded Highcharts.

@oysteinmoseng

**Comment by oysteinmoseng** [comment]
Fixed in #9647
