### ISSUE TITLE
Error on IE7

### ISSUE THREAD

**Issue by uasy** [highcharts/highcharts#9654]
#### Expected behaviour
Charts work on IE7 near 1 month early.

#### Actual behaviour
Now not work

#### Live demo with steps to reproduce
Code from samples:
`<HTML>
  <HEAD>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-3d.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    
  <HEAD>
  <BODY>
    <div id="container" style="height: 400px"></div>
    <script>
      var myChart;
      $(function () {
        myChart = Highcharts.chart('container', {
          chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
          },
          title: {
            text: 'Browser market shares in January, 2018'
          },
          tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
          },
          plotOptions: {
            pie: {
              allowPointSelect: true,
              cursor: 'pointer',
              dataLabels: {
                enabled: true,
                format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                style: {color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'}
              }
            }
          },
          series: [{
            name: 'Brands',
            colorByPoint: true,
			dataLabels: true,
            data: [{name: 'Chrome', y: 61.41, sliced: true, selected: true}, 
                    {name: 'Internet Explorer', y: 11.84}, 
                    {name: 'Firefox', y: 10.85}, 
                    {name: 'Edge', y: 4.67}, 
                    {name: 'Safari', y: 4.18}, 
                    {name: 'Sogou Explorer', y: 1.64}, 
                    {name: 'Opera', y: 1.6}, 
                    {name: 'QQ', y: 1.2}, 
                    {name: 'Other', y: 2.61}] 
          }]
        });
      });
    </script>
  </BODY>
</HTML>
`

In browser on developer console (F12) set compatible 7 and agent string IE7.

In console see
Untitled-5.html
SCRIPT1028: Предполагается наличие идентификатора, строки или числа
highcharts.js (188,172)
SCRIPT5007: Не удалось получить свойство "deg2rad" ссылки, значение которой не определено или является NULL
highcharts-3d.js (8,220)

#### Affected browser(s)
IE 11 in IE 7 compatible

**Comment by TorsteinHonsi** [comment]
Thanks for reporting @uasy ! There are two problems here.

1. We released v7.0.0 yesterday, but failed to mention in the changelog that you need to load an extra file for old IE support. See https://www.highcharts.com/documentation/changelog => Upgrade notes, where it has been added now.
2. There's a bug in v7.0.0 (unrelated) that breaks old IE. 

My advice is that you downgrade to Highcharts v6.2.0 until we release v7.0.1.

**Comment by uasy** [comment]
Thank you for recomendations, but including 'modules/oldie-polyfills.js' not help for me.

I include library from you site, can i change url to use v6.2 version?

Changed script:
`<HTML>
  <HEAD>
	
	<script src="https://code.highcharts.com/highcharts.js"></script>
	  
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/json3/3.3.2/json3.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <HEAD>
  <BODY>
    <div id="container" style="height: 400px"></div>
    <script>
      var myChart;
      $(function () {
        myChart = Highcharts.chart('container', {
          chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
          },
          title: {
            text: 'Browser market shares in January, 2018'
          },
          tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
          },
          plotOptions: {
            pie: {
              allowPointSelect: true,
              cursor: 'pointer',
              dataLabels: {
                enabled: true,
                format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                style: {color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'}
              }
            }
          },
          series: [{
            name: 'Brands',
            colorByPoint: true,
			dataLabels: true,
            data: [{name: 'Chrome', y: 61.41, sliced: true, selected: true}, 
                    {name: 'Internet Explorer', y: 11.84}, 
                    {name: 'Firefox', y: 10.85}, 
                    {name: 'Edge', y: 4.67}, 
                    {name: 'Safari', y: 4.18}, 
                    {name: 'Sogou Explorer', y: 1.64}, 
                    {name: 'Opera', y: 1.6}, 
                    {name: 'QQ', y: 1.2}, 
                    {name: 'Other', y: 2.61}] 
          }]
        });
      });
    </script>
  </BODY>
</HTML>`

**Comment by TorsteinHonsi** [comment]
We have not yet released v7.0.1, but will probably do that tomorrow. Until then, you can load the old files from `https://code.highcharts.com/6/highcharts.js` etc. (include the version at root level).
