### ISSUE TITLE
node export server: reliance on phantomjs

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#9656]
I've posted over on [here](https://github.com/highcharts/node-export-server/issues/182) with a suggestion to support rendering based on something else other than phantomjs.  Not sure exactly where to post this, so I'm sorry if this is the wrong place.  It's a highcharts issue in the sense that the node-export-server library is relying on a project (phantomjs) that is no longer being maintained.

**Comment by pawelfus** [comment]
Hi @drmrbrewer 

Thanks for reporting! This should be reported in the node-export-server (as the exporting server use phantomJS, not the Highcharts library itself): https://github.com/highcharts/node-export-server/issues/

Actually it's already reported: https://github.com/highcharts/node-export-server/issues/57
