### ISSUE TITLE
Type definitions: Exporting.buttons is incorrect

### ISSUE THREAD

**Issue by cthrax** [highcharts/highcharts#9658]
#### Expected behaviour
The definition matches the documentation.

#### Actual behaviour
The definition adds a layer I believe to be incorrect.

#### Live demo with steps to reproduce

Current buttons definition:
```   
    buttons?: Dictionary<ExportingButtonsOptions>;
```
Where ExportingButtonsOptions is defined as:

```
export interface ExportingButtonsOptions {
    contextButton?: ExportingButtonsContextButtonOptions;
}
```

I believe the definition should be:
```
    buttons?: ExportingButtonsOptions;
```

```
export interface ExportingButtonsOptions {
    contextButton?: ExportingButtonsContextButtonOptions;
    [buttonName: string]: ExportingButtonsContextButtonOptions
}
```

Or the documentation is incorrect at https://api.highcharts.com/highcharts/exporting.buttons.contextButton 
#### Product version

Highcharts 7.0

**Comment by bre1470** [comment]
Hi @cthrax,
Thank you for the report. I believe you are correct with your suggestion. We will fix this in one of the following updates.
