### ISSUE TITLE
time range will be incorrect if default rangeSelector.selected is 1 year range

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#966]
Hi, 
if I set default rangeSelector.selected to 1year range, when I open the page, the time range will be May,16 2011 to May,15 2012.
but if I select 1 year range button again (click 1y again), the time range will become May,15 2011 to May,15 2012

while May,15 2011 to May,15 2012 is the correct time range.

see this fiddle:
http://jsfiddle.net/gh/get/jquery/edge/highslide-software/highcharts.com/tree/master/samples/stock/demo/basic-line/

the default rangeSelector.selected is 4 in the above fiddle.

**Comment by oysteinmoseng** [comment]
This seems to be working with current code.
