### ISSUE TITLE
Variwide with scrollbar

### ISSUE THREAD

**Issue by rajeshdanabal** [highcharts/highcharts#9660]
#### Expected behaviour
Add scrollbar to variwide chart, so that user can scroll when there is large amount of categories.

#### Actual behaviour
There is unwanted gaps and columns are over lapping with each other.

#### Live demo with steps to reproduce
http://jsfiddle.net/rajeshdanabal/vdcoz3y0/8/

#### Product version
Highstock - V7.0.0

#### Affected browser(s)

All. Tested with Google Chrome - Version 71.0.3578.80 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Hi @rajeshdanabal 

Thank you for reporting this bug! You are right it's broken. It's a general issue with `xAxis.min` and `xAxis.max` reported already as #8635 

FYI @TorsteinHonsi
