### ISSUE TITLE
Charts showing up with scroll bar in Story Maps 

### ISSUE THREAD

**Issue by srhickel** [highcharts/highcharts#9666]
#### Expected behaviour

Full chart to display in Story Maps container since HighCharts is set as responsive.

#### Actual behaviour

3/4 of the chart is displayed in Story Maps container and a scroll bar is needed to display the rest of the chart. Both the Story Map container and the High Charts are responsive so I am looking for a responsive code to get rid of the scroll bars. 

#### Live demo with steps to reproduce
Here is a link to the story map, Highcharts with scrollbars are towards the end of the Story Map.
https://arcg.is/15j0HG

#### Affected browser(s)
all browsers

**Comment by KacperMadej** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

P.S. Your demo site has a lot of errors in browser console (developer tools) making it harder to find the source of the problem. Please create a minimal example for support to check and test. Looks like you have not set height for chart - please see https://api.highcharts.com/highcharts/chart.height and you could also try using [chart.reflow](https://api.highcharts.com/class-reference/Highcharts.Chart#reflow) if size options are applied with delay.
