### ISSUE TITLE
Add API for dynamically switching between charts zoom and pan.

### ISSUE THREAD

**Issue by likwifi** [highcharts/highcharts#9667]
#### Actual behaviour
Add API for dynamically switching between charts zoom and pan.

**Comment by sebastianbochan** [comment]
Hi @likwifi,
Thank you for contacting us. This is our bug tracker for reporting bugs. For general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.

You can also post your ideas and suggestion in our [uservoice](https://highcharts.uservoice.com).

**Comment by likwifi** [comment]
@sebastianbochan Who said that enhancements or features request can't be here?
Your support recommends workarounds for doing this which are not working after upgrade to latest Highstock.
https://forum.highcharts.com/viewtopic.php?p=115385#p115385 
I would like to call single method for changing chart from zoom mode to pan when pressing button on toolbar, without any key.

**Comment by KacperMadej** [comment]
@likwifi 
> Who said that enhancements or features request can't be here?

It's instructed in already shared page: https://www.highcharts.com/blog/support/
"To request a feature, please post a suggestion on UserVoice, or vote for the ones that are already registered.". We care about your needs and if you want your enhancement to be implemented you should post it on the UserVoice. To be precise, enhancement or features can be here, but an issue might get closed (like this issue) as this is not designated place for such cases.

You are referring to a forum topic from 2015, it might be outdated. Try using [chart.update](https://api.highcharts.com/class-reference/Highcharts.Chart#update) - demo: http://jsfiddle.net/BlackLabel/p7xk0aLv/ This is not a bug, so it should be resolved by technical support as Sebastian already explained.
