### ISSUE TITLE
chart sankey does not support mapNavigation?

### ISSUE THREAD

**Issue by cheeses** [highcharts/highcharts#9668]
#### code
VUE: 
import Highcharts from 'highcharts/highstock'
import HighchartsMore from 'highcharts/highcharts-more'
import Sankey from 'highcharts/modules/sankey'
import loadMap from 'highcharts/modules/map'
import loadStock from 'highcharts/modules/stock'

loadStock(Highcharts)
loadMap(Highcharts)
HighchartsMore(Highcharts)
Sankey(Highcharts)

this.chart = new Highcharts.Chart('container', {
        chart: {
          zoomType: 'xy'
        },
        mapNavigation: {
          enabled: true,
          enableButtons: false
        },
       .....
})
mapNavigation No effect

**Comment by KacperMadej** [comment]
Hi @cheeses ,

Sankey is not connected to axes (like a pie chart), so it doesn't support mapNavigation - it has no effect.
Demo: https://jsfiddle.net/BlackLabel/up0behdm/

**Comment by cheeses** [comment]
> Hi @cheeses ,
> 
> Sankey is not connected to axes (like a pie chart), so it doesn't support mapNavigation - it has no effect.
> Demo: https://jsfiddle.net/BlackLabel/up0behdm/

thanks, is there any way to zoom according to the mouse roller?

**Comment by KacperMadej** [comment]
There's no zoom at all supported for sankey chart.

To request a feature, please post a suggestion on UserVoice, or vote for the ones that are already registered. https://highcharts.uservoice.com/forums/55896-general

**Comment by cheeses** [comment]
> There's no zoom at all supported for sankey chart.
> 
> To request a feature, please post a suggestion on UserVoice, or vote for the ones that are already registered. https://highcharts.uservoice.com/forums/55896-general

Hi @KacperMadej 
Thank you very much for your advice. Thank you.
