### ISSUE TITLE
Strange non-standard way of handling exceptions

### ISSUE THREAD

**Issue by markushausammann** [highcharts/highcharts#9670]
#### Expected behaviour

Uncatched exceptions stay uncatched and bubble up so our error tracking system can handle them.

#### Actual behaviour

Highcharts sends a link to its own domain to the console, e.g. https://www.highcharts.com/errors/15/
where an error message is shown.

This is non-standard and unwanted behavior. Bug trackers, etc. can't handle it. We want to be able to catch the exception and log it to sentry.

**Comment by TorsteinHonsi** [comment]
Thanks for your input! The rationale for using the links is to save bandwidth for our end users.

See https://api.highcharts.com/class-reference/Highcharts.html#.error for how to catch the error.

**Comment by markushausammann** [comment]
I'd still not advocate this, it's very unexpected, but with the the documentation link you provided, it was indeed easy to change.
