### ISSUE TITLE
Connect null values on Zoom out

### ISSUE THREAD

**Issue by Sogapp** [highcharts/highcharts#9673]
#### Expected behaviour
Should not connect null values

#### Actual behaviour
Issue occurs when you drag left the begin date in the volume panel 
At beginning the orange lines are not connected... after draging left, they are connected

#### Live demo with steps to reproduce
https://codepen.io/DFkd2/pen/KbzVOJ

![capture d ecran 2018-12-14 a 18 29 30](https://user-images.githubusercontent.com/11569914/50018083-6bb26780-ffce-11e8-817e-b90b84c49f44.png)

![capture d ecran 2018-12-14 a 18 29 50](https://user-images.githubusercontent.com/11569914/50018093-70771b80-ffce-11e8-9f3c-2f152bd36e02.png)

#### Product version
highstock last version

#### Affected browser(s)
Chrome and probably others

**Comment by KacperMadej** [comment]
Hi @Sogapp 

This is expected behavior for grouped data. Disable data grouping and point's won't be connected. Demo: https://codepen.io/Blacklabel/pen/oJxZRz

You've posted to our issue tracker and this is not a bug. For general tech support, please see www.highcharts.com/support.

**Comment by Sogapp** [comment]
OK thanks @KacperMadej
