### ISSUE TITLE
Highstock 'candlestick' changes location of data based on length

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [highcharts/highcharts#9674]
Hello,

I'm currently building a small app which utilizes series data from an exchange.

Now when my series has a length of more than ~30, I can no longer access the data trough:

chart.series[0].data[series.data.length-1].update({time:data[0][0], open: data[0][1], high: data[0][2], low: data[0][3], close: data[0][4]  });

When logging the series[0] Object, I find out that I can no longer update it, because the data object was empty but instead everything was moved into xData and yData.

Now those two properties have no method called .update

Question: How do I update the chart now?

This is my chart setup btw: 

````

$.getJSON('http://localhost:5000/series', function (data) {

    let chart = Highcharts.stockChart('container', {

        navigator: {
           enabled: false
       },
        rangeSelector: {
          enabled: false,
            buttons: [{
                type: 'minute',
                count: 1,
                text: '1m'
            }],
            inputEnabled: false
        },

        plotOptions: {
          line: {
          lineWidth:1
         }
        },

        series: [{
            type: 'candlestick',
            name: 'BINANCE:BTCUSDT',
            data: data,
            marker: {
                enabled: true,
                radius: 3
            },
            tooltip: {
                valueDecimals: 2
            }
        }],
        dataGrouping: [{
          enabled: false
        }]
    });
````

I found this answer: 

>  /**
     * The base function which all other series types inherit from. The data in the series is stored
     * in various arrays.
     *
     * - First, series.options.data contains all the original config options for
     * each point whether added by options or methods like series.addPoint.
     * - Next, series.data contains those values converted to points, but in case the series data length
     * exceeds the cropThreshold, or if the data is grouped, series.data doesn't contain all the points. It
     * only contains the points that have been created on demand.
     * - Then there's series.points that contains all currently visible point objects. In case of cropping,
     * the cropped-away points are not part of this array. The series.points array starts at series.cropStart
     * compared to series.data and series.options.data. If however the series data is grouped, these can't
     * be correlated one to one.
     * - series.xData and series.processedXData contain clean x values, equivalent to series.data and series.points.
     * - series.yData and series.processedYData contain clean y values, equivalent to series.data and series.points.
     *
     * @constructor Series
     * @param {Object} chart - The chart instance.
     * @param {Object} options - The series options.
     */

**Comment by KacperMadej** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

P.S.
You could disable dataGrouping or check if crop option is not blocking anything. It's hard to guess right without a live demo, so please add it when contacting support. If you want to update a point that is not grouped through dataGrouping then you could assign id to it and later use [`chart.get()`](https://api.highcharts.com/class-reference/Highcharts.Chart#get).
