### ISSUE TITLE
Bubble Chart - Chart plot area goes  blank when all z values all are negative.

### ISSUE THREAD

**Issue by vbiarulkumar** [highcharts/highcharts#9678]
#### Expected behaviour
Chart should work when all z values all are negative.

#### Actual behaviour
 Chart plot area goes  blank when all z values are negative.

#### Live demo with steps to reproduce
https://jsfiddle.net/h6wtsp9a/

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! It's a regression, it worked in v6.2.

**Comment by TorsteinHonsi** [comment]
It's fixed now, will be published with v7.0.1 tomorrow or the day after.

@ppotaczek I fixed the cause of the JS error, but I am still not sure how the bubble legend should handle negative values. Do you have any opinion on this? Is it deliberate that it doesn't display anything at all in the bubble legend?

**Comment by ppotaczek** [comment]
Currently to display negative values in bubble legend, it is necessary to set lower [zThreshold](https://api.highcharts.com/highcharts/legend.bubbleLegend.zThreshold), which is set to `0` by default: 

    legend: {
        ...,
        bubbleLegend: {
            zThreshold: -1000,
            ...
        }
    }

Live demo: https://jsfiddle.net/BlackLabel/bpcsgr3j/

The `zThreshold` option could be dynamic and adapt to the lowest `z` value. What do you think @TorsteinHonsi ?
