### ISSUE TITLE
Chart Sankey reports errors when there is too much data

### ISSUE THREAD

**Issue by cheeses** [highcharts/highcharts#9679]
When there is too much data, it can lead to the accumulation of graphics and error reporting. Is there a good solution? I want to make it scalable by scrolling the mouse, but I don't know how to do it. Looking forward to reply!
http://thyrsi.com/t6/635/1545028630x2728278865.png
http://thyrsi.com/t6/634/1545028310x2890171450.png

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Can you demonstrate this live? In my attempt it seems to work: https://jsfiddle.net/highcharts/a3rm16g8/3/

**Comment by cheeses** [comment]
> Thanks for reporting!
> 
> Can you demonstrate this live? In my attempt it seems to work: https://jsfiddle.net/highcharts/a3rm16g8/3/

Hi, @TorsteinHonsi 
Thanks, our data structure is different: https://jsfiddle.net/cheeses/a3rm16g8/5/

**Comment by KacperMadej** [comment]
Here's a smaller demo: https://jsfiddle.net/BlackLabel/zcbm2v83/
