### ISSUE TITLE
Highchart drawing problem on samsung s9

### ISSUE THREAD

**Issue by lnwanghao** [highcharts/highcharts#9681]
#### Actual behaviour
![image](https://user-images.githubusercontent.com/17587836/50083286-34da8c80-022e-11e9-9f71-89a37ff9e4db.png)

#### Product version

Highcharts version: v6.1.3
device: samsung s9

**Comment by sebastianbochan** [comment]
Hi @lnwanghao,
Thank you for reporting, could you recreate your example as live demo? It will allow us to test and debug it. 

Please add also information about browser and version of Android.

**Comment by lnwanghao** [comment]
> Hi @lnwanghao,
> Thank you for reporting, could you recreate your example as live demo? It will allow us to test and debug it.
> 
> Please add also information about browser and version of Android.

**Comment by lnwanghao** [comment]
Thank you for your reply@sebastianbochan,
My samsung s9 android version is 8.0.0.
I use highchart on react-native webview.(react-native version: 0.55.4)
The problem of being able to reproduce on a real machine, i can only provide my code. Sorry！
[https://jsfiddle.net/lnwanghao/euv0d7oc/14/](url)

**Comment by lnwanghao** [comment]
> Hi @lnwanghao,
> Thank you for reporting, could you recreate your example as live demo? It will allow us to test and debug it.
> 
> Please add also information about browser and version of Android.

Thank you for your reply@sebastianbochan,
My samsung s9 android version is 8.0.0.
I use highchart on react-native webview.(react-native version: 0.55.4)
The problem of being able to reproduce on a real machine, i can only provide my code. Sorry！
url: https://jsfiddle.net/lnwanghao/euv0d7oc/14/

**Comment by sebastianbochan** [comment]
Hi @lnwanghao,
Thank you for the feedback. When I run the demo, all seems to be correct (Samsung s7 edge, Android 8.0.0).

I think that the reason on the issue can be implicated by a few things:
- react-native
- external code - does the problem appear in simplified demo?

Have you tried to load a html file like below?

**Example:**
1. App.js
```
import React from 'react';
import { StyleSheet, WebView, View } from 'react-native';

const webapp = require('./index.html');

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <WebView source={webapp}/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'center',
  },
});
```
2. index.html
```
<html>
  <head>
  </head>
  <body>
    <h1>Highcharts webview demo</h1>
    <div id="container" style="width:100%; height:500px;"></div>
    <script type="text/javascript" src="highcharts.js"></script>
    <script>
      Highcharts.chart('container', {
        // highcharts options
      });
    </script>
  </body>
</html>
```

Please let me know if worked.

**Comment by lnwanghao** [comment]
> Hi @lnwanghao,
> Thank you for the feedback. When I run the demo, all seems to be correct (Samsung s7 edge, Android 8.0.0).
> 
> ![screenshot_20181218-131352_chrome](https://user-images.githubusercontent.com/2115686/50154897-e8915a00-02ca-11e9-8995-4b6456f09fbe.jpg)
> 
> I think that the reason on the issue can be implicated by a few things:
> 
> * react-native issue with gradients
> * external plugins
> * external code - does the problem appear in simplified demo?
> 
> Have you tried to load a html file like below?
> 
> **Example:**
> 
> 1. App.js
> 
> ```
> import React from 'react';
> import { StyleSheet, WebView, View } from 'react-native';
> 
> const webapp = require('./index.html');
> 
> export default class App extends React.Component {
>   render() {
>     return (
>       <View style={styles.container}>
>         <WebView source={webapp}/>
>       </View>
>     );
>   }
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     backgroundColor: '#fff',
>     justifyContent: 'center',
>   },
> });
> ```
> 1. index.html
> 
> ```
> <html>
>   <head>
>   </head>
>   <body>
>     <h1>Highcharts webview demo</h1>
>     <div id="container" style="width:100%; height:500px;"></div>
>     <script type="text/javascript" src="highcharts.js"></script>
>     <script>
>       Highcharts.chart('container', {
>         // highcharts options
>       });
>     </script>
>   </body>
> </html>
> ```
> Please let me know if it worked.

Hi @sebastianbochan , 
thank you for your reply.
I've tried the example you provided，
it 
works.
But I don't think there's a problem with simple data.
Now i will closed the issue.
I will reopened the issue, until i prepare my test data ready.

**Comment by sebastianbochan** [comment]
Hi @lnwanghao,
Thank you for the feedback.

**Comment by lnwanghao** [comment]
Hi @sebastianbochan ,
I have prepared my test data ready, you can try whether it works well on samsung s9.
https://jsfiddle.net/lnwanghao/euv0d7oc/28/
