### ISSUE TITLE
decimals do not work i my project but works on js fiddle

### ISSUE THREAD

**Issue by milossesiceng** [highcharts/highcharts#9683]
#### Expected behaviour
I expect once my chart renders to show decimals on yaxis

#### Actual behaviour
i get rounded numbers, instead of ( 0, 0.1, 0.3, 0.7, 2 ) I get ( 0, 1, 1 ,1 ,2 )

#### Live demo with steps to reproduce
http://jsfiddle.net/JeLrb/520/

#### Product version
https://code.highcharts.com/4.1.4/highcharts.js or https://code.highcharts.com/highcharts.js

#### Affected browser(s)
Chrome
![thumbnail_dasdasdasdasdasdas](https://user-images.githubusercontent.com/41570309/50084698-25405100-01f8-11e9-9f2d-432149938fe1.png)

Does anyone have an idea what might cause it to NOT work in my application and it works on jsfiddle ?

**Comment by bre1470** [comment]
I am not able to confirm this. It shows here floats on the y-axis. (Chrome 71.0.3578.98, macOS)

**Comment by bre1470** [comment]
I suggest to test with all browser plugins turned off. Maybe there is some extension modifying Highcharts functionality.

**Comment by milossesiceng** [comment]
This helped pawelfus, thank you.

**Comment by pawelfus** [comment]
@milossesiceng - Great! Should we close the issue then?

**Comment by milossesiceng** [comment]
Yes, please, the pain is finally over :)
