### ISSUE TITLE
One row Heatmap Chart aligned to bottom with title margin became zero height in case of printing 

### ISSUE THREAD

**Issue by evgenia-semenova** [highcharts/highcharts#9686]
**Case 1**
#### Expected behaviour
Heatmap Chart with one row should be printed correctly and stay drawn with the same row height on the page

#### Actual behaviour
Chart printed but with zero height of that row and redrawn with zero height after print dialog closed

#### Live demo with steps to reproduce
https://jsfiddle.net/Evgeniya_Semenova/d3je65hu/
The main case that some margin added to title for make plot bottom-aligned depends on amount of rows. Problem appeared when data has only one row

1. Open example.
2. Check that exact one row with values colored with blue colors has some height
![image](https://user-images.githubusercontent.com/44443056/50085367-e798f380-020a-11e9-9675-d9822cc05436.png)
3. Click 'Print chart' from menu on top right corner
4. Check row height on printed page it became zero
![image](https://user-images.githubusercontent.com/44443056/50085172-588bdb80-020a-11e9-91e8-4fc56927c7d9.png)

5. Close page and check the chart, the row became 0 height

#### Product version
6.1.1
#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @evgenia-semenova,
Thank you for reporting. It looks like general issue with heatmap, because when we set width as 300px, problem is visible without calling the print option.

**Demo:**
- https://jsfiddle.net/BlackLabel/3t8cpxog/

The problem seems to be caused by setting `margin: 290` for the title. Could you elaborate what is the reason of setting it?

**Comment by evgenia-semenova** [comment]
We have requirements to have fixed height and width of a single element and align the chart on the bottom left corner
In our case we potentialy have max 50 rows, and if there are less than we calculate margin. The chart is drawn correctly, but print is failed in case we have 1 to 5 rows.

**Comment by KacperMadej** [comment]
@evgenia-semenova 
This doesn't look like a bug. Rotated xAxis labels take more space than not rotated leaving not enough space to render bigger cells. You could prevent labels from rotating through [available labels options](https://api.highcharts.com/highcharts/xAxis.labels) - e.g. set rotation to 0 and labels that doesn't fit will be truncated with ellipses. Demo: https://jsfiddle.net/BlackLabel/uLm6k59s/1/ 
Try [`step: 1`](https://api.highcharts.com/highcharts/xAxis.labels.step), but labels might overlap each other.

**Comment by evgenia-semenova** [comment]
Why labels became rotated only on printing?

**Comment by sebastianbochan** [comment]
@evgenia-semenova 
Because the width of printed chart is smaller than in the browser.

**Comment by sebastianbochan** [comment]
Hi @evgenia-semenova,
I think that the best option is using the [responsive](https://api.highcharts.com/highcharts/responsive.rules) rules which allows you to define chart's options per resolution.

For further [support](http://www.highcharts.com) questions, please use forum / stackoverflow or email.
