### ISSUE TITLE
scrollablePlotArea doesn't work in v7.0.0

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#9690]
#### Behaviour
scrollablePlotArea is broken since version 7.0.0

@TorsteinHonsi 

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea

#### Product version
7.0.0

**Comment by ppotaczek** [comment]
It looks like there is a problem with `overflow: hidden;` style set on HTML container element: http://jsfiddle.net/BlackLabel/od28fkr5/

We can notice the same issue with different chart height: http://jsfiddle.net/BlackLabel/yk6fwomt/
