### ISSUE TITLE
Standard Intl Datetime for charts

### ISSUE THREAD

**Issue by mhf-ir** [highcharts/highcharts#9691]
#### Expected behaviour
I need the standard intl datetime to display as datetime charts on hichchart.
Backend servers send the unixtime to client. and client must show the charts based on locale and different calendar types.

Standard:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

Browser support:
http://kangax.github.io/compat-table/esintl/

See different of current date time in different countries:
```js
console.log(new Intl.DateTimeFormat('ar-SA').format(new Date()));
console.log(new Intl.DateTimeFormat('fa-IR').format(new Date()));
console.log(new Intl.DateTimeFormat('th-TH').format(new Date()));
```
#### Actual behaviour
I dont see any date time format base on Intl DateTimeFormat

More about differences:
https://mhf-ir.github.io/i18nplease/

**Comment by KacperMadej** [comment]
Hi @mhf-ir 

You could add custom date format through https://api.highcharts.com/class-reference/Highcharts.html#.dateFormats - there's a demo for adding a week number support, but any format based on given timestamp will look similar.

We are trying to keep GitHub issues for bug reports and this is not a bug. In case of technical problems please try contacting [support](https://www.highcharts.com/blog/support/). If you want to suggest an enhancement idea (e.g. build-in support for Intl DateTimeFormat as a part of core Highcharts or as an official moduel) - please use [UserVoice](https://highcharts.uservoice.com/forums/55896-general)

**Comment by mhf-ir** [comment]
As you can see in many great project like highchart Intl stuff, RTL is base problem. Web already use it in many years ago but developers doesn't consider for world class project.

I will continue Intl problem via support section. Thank you for awesome project.
