### ISSUE TITLE
Tooltip outside bug

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#9694]
When tooltip.outside is set to true and chart has more than one series with different types (checked at column & line and column & spline) occurs tooltip bug - tooltip displays without right and bottom border and without a pointer. What I noticed: 
- it happens in greater than 5 version (in 5 it works fine),
- the bug doesn't occur always, so it's needy to refresh the browser,

The bug is connected with the post from the [forum](https://forum.highcharts.com/viewtopic.php?f=9&t=41379)

#### Live demo with steps to reproduce
[jsFiddle](https://jsfiddle.net/Bastss/6jL2qbvd/)

#### Product version
Highcharts 6, 7

#### Affected browser(s)
Tested on chrome and firefox

**Comment by Bodokh** [comment]
Is there any temporary workaround until this is fixed?

**Comment by KacperMadej** [comment]
If you are happy with how version 5 works then you could just disable the option, because it was added in v6.1.1.
**Workaround**: https://jsfiddle.net/BlackLabel/2oxh308z/
