### ISSUE TITLE
7.0 doesn't work on initial render

### ISSUE THREAD

**Issue by getnashty** [highcharts/highcharts#9697]
My chart is not loading properly anymore after updating to 7.0. I can see it render properly for a split second, and then it looks completely messed up. If I tap around a few pages and revisit the chart, it looks correct on subsequent visits.

#### Expected behaviour
This is what the chart looks like when it works properly. This is also how the chart looks on any secondary render:
<img width="609" alt="screen shot 2018-12-17 at 1 16 02 pm" src="https://user-images.githubusercontent.com/113112/50106528-152b7000-01fe-11e9-9f23-661a0db35b65.png">

#### Actual behaviour
This is what the chart looks like on initial render after upgrading to 7.0 (from 6.2).
<img width="625" alt="screen shot 2018-12-17 at 1 15 44 pm" src="https://user-images.githubusercontent.com/113112/50106556-2aa09a00-01fe-11e9-9ec4-0cddcb8e665b.png">

------

I have since rolled back, not sure if this data is useful to anyone?

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! Can you reproduce it in a live demo that we can debug?

**Comment by getnashty** [comment]
@TorsteinHonsi I will update this thread when I have a chance to put a demo together

**Comment by getnashty** [comment]
@TorsteinHonsi I noticed 7.0.1 was released - I've made some changes to the chart in that time, and I'm not longer seeing the issue (not sure if it was my changes, or the upgrade) - but I'm closing this all the same! :) thank you!
