### ISSUE TITLE
yValue wrong for multiple xrange series on the same yAxis

### ISSUE THREAD

**Issue by ebaronov** [highcharts/highcharts#9698]
#### Expected behaviour

Intervals from two xrange charts on the same yAxis with the same yValue should be aligned vertically, i.e. if I have two points from different xrange charts: {x: 1, x2: 2, y: 5} and {x: 3, x2: 4, y:5} the two rendered intervals should be vertically centered around the y=5 line. 

#### Actual behaviour

Instead, the point from the first chart is rendered entirely below the y=5 line and the point from the second chart is rendered entirely above it.

#### Live demo with steps to reproduce

https://jsfiddle.net/hkq9zfbs/39/

#### Affected browser(s)

chrome, safari - latest versions

**Comment by KacperMadej** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

P.S.
Series are grouped by default. Turn the option off and they will be aligned. Demo: https://jsfiddle.net/BlackLabel/1ap6foL7/

**Comment by ebaronov** [comment]
This worked, thank you! I will use the correct channel next time
