### ISSUE TITLE
Packed bubble chart error with 1 bubble

### ISSUE THREAD

**Issue by nigmastar** [highcharts/highcharts#9700]
#### Expected behaviour
Simply showing 1 bubble

#### Actual behaviour
highcharts-more.src.js:6560 Uncaught TypeError: Cannot read property '3' of null
    at r.translate (highcharts-more.src.js:6560)
    at highcharts.src.js:28053
    at Array.forEach (<anonymous>)
    at a.Chart.renderSeries (highcharts.src.js:28052)
    at a.Chart.render (highcharts.src.js:28177)
    at a.Chart.firstRender (highcharts.src.js:28396)
    at a.Chart.<anonymous> (highcharts.src.js:26516)
    at a.fireEvent (highcharts.src.js:2610)
    at a.Chart.init (highcharts.src.js:26382)
    at a.Chart.getArgs (highcharts.src.js:26353)

#### Live demo with steps to reproduce
https://jsfiddle.net/x7mpzeya/

#### Product version
Highcharts 7.0

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @nigmastar,
The issue is caused by algorithm which expects to have at least 2 bubbles to calculate positions. The first bubble is in the chart's center, the second above. As a result, the solution allows to calculate position of next bubbles around the main bubble.

```
  // if length is 0, return empty array
  if (!sortedArr.length) {
    return [];
  }

  // if length is 1,return only one bubble
  bubblePos.push([
    [
      0, // starting in 0,0 coordinates
      0,
      sortedArr[0][2], // radius
      sortedArr[0][3], // series index
      sortedArr[0][4]
    ] // point index
  ]);

  if (sortedArr.length > 1) {
    bubblePos.push([
      [
        0,
        0 - sortedArr[1][2] - sortedArr[0][2],
        // move bubble above first one
        sortedArr[1][2],
        sortedArr[1][3],
        sortedArr[1][4]
      ]
    ]);
  }
```

**Demo:**
- http://jsfiddle.net/BlackLabel/cwtu9rg2/

**Internal note**
We should change conditions in the `placeBubbles` function.

@Izothep what do you think?

**Comment by Izothep** [comment]
Yes, I can fully agree, 

The issue was caused by the positioning function. Adding small conditional statement at the beginning (that will check the number of points) looks for me like the most accurate solution, that will not affect any later calculations.
