### ISSUE TITLE
Data-label is misplaced in bar charts when negative value is 0.

### ISSUE THREAD

**Issue by thapaniraj01** [highcharts/highcharts#9704]
#### Live demo with steps to reproduce
http://jsfiddle.net/thapaniraj01/v3o659bq/2/

**Comment by sebastianbochan** [comment]
Hi @thapaniraj01,
Thank you for reporting. The datalabels are positioned according to align option. In the demo, datalabels are positioned on the right side of axis, by default.

<img width="503" alt="zrzut ekranu 2018-12-18 o 16 10 46" src="https://user-images.githubusercontent.com/2115686/50163006-cfdf6f00-02df-11e9-9dbe-36dd360c5662.png">

Could you elaborate the positioning of zero-datalabels? Will be really helpful to prepare a mockup which will allow me to decide if it is a bug or only question.

**Comment by thapaniraj01** [comment]
Data labels are aligned differently both left and right for different data.

 _series: [{
       name: 'Male',
       data: [-1, 0, -1, 0, -2, -5, -4, -4, -4, -5, -3, 0, -3, 0, 0],
       dataLabels: {
         align: 'right'
       }
     }, {
       name: 'Female',
       data: [0, 0, 0, 0, 1, 0, 1, 0, 0, 4, 1, 3, 3, 0, 0],
       dataLabels: {
         align: 'left'
       }_

**Comment by thapaniraj01** [comment]
Yes, I was talking about 0 value for 55-59 category is aligned to the right, instead of center like other "zeros".

**Comment by KacperMadej** [comment]
@thapaniraj01 
Looks like you could disable grouping instead of using stacking (there's no real stacking in your chart - it creates only the issue you have reported). Demo: http://jsfiddle.net/BlackLabel/42c53q86/

The problem was caused by not negative values (so zero included) are stacked on right side.

**Comment by thapaniraj01** [comment]
Thanks, that worked for me.
