### ISSUE TITLE
Venn chart displayed incorrectly

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#9718]
#### Expected behaviour
With 2 sets:
- A: 20
- B: 30
- And section relation: 15
I would like to see chart displayed like in the picture:
![venn](https://user-images.githubusercontent.com/23310742/50162232-1a5fec00-02de-11e9-96b3-7db730a477b4.png)

#### Actual behaviour
Venn chart is displayed incorrectly: [jsFiddle](https://jsfiddle.net/BlackLabel/akcyLohm/)

Note that exported chart looks different.

#### Product version
Highcharts 7.0.0

#### Affected browser(s)
All

**Comment by BPavol** [comment]
I had same issue today and it is extremely annoying.
Result is wrong if intersection is in interval [B/2, A-1] -> [15, 19].

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! Due to the holidays it will take some time until we are able to look into a solution.
