### ISSUE TITLE
Reset Zoom not tabbable

### ISSUE THREAD

**Issue by GMUDuckman** [highcharts/highcharts#9719]
#### Expected behaviour
If using keyboard for accessibility to tab to things, would expect when zoomed in and the Reset zoom button is visible it would be the next tab item after the chart items and before the context menu.

#### Actual behaviour
Reset zoom button not tabbable at all.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/zoomtype-x/

**Comment by GMUDuckman** [comment]
@KacperMadej any ideas on workarounds? :-)

**Comment by oysteinmoseng** [comment]
No workarounds, but this should be easy to add. I will see if I can get something up and going before the holidays.

**Comment by oysteinmoseng** [comment]
This has now been added to a feature branch and will be merged into master eventually. Demo: http://jsfiddle.net/pwLo71e3/1/
