### ISSUE TITLE
Cannot create histogram with pre-aggregated chart using column chart

### ISSUE THREAD

**Issue by taichi-jp** [highcharts/highcharts#9721]
The doc (https://www.highcharts.com/docs/chart-and-series-types/histogram-series) says
> A histogram chart can also be created using a column chart if the data is already pre-aggregated.

but we cannot create the exactly same graph as histogram chart.

The difference between column chart and histogram chart is the positions of labels in x axis.

In histogram, number labels should be placed between the bars, like https://www.highcharts.com/docs/chart-and-series-types/histogram-series .

When I create it using column chart, the labels are put below the bars.
https://jsfiddle.net/taichi_jp/t4nqv5eg/4/

In addition, we cannot make intervals in the number labels like the histogram demo.

If there is a way to realize exactly the same as histogram chart using column chart, please notify me.

**Comment by KacperMadej** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

P.S.
Here's a more precise copy of histogram through column series type (with some comments in code for more info): https://jsfiddle.net/BlackLabel/2k7wLpmz/

**Comment by taichi-jp** [comment]
@KacperMadej 
Thank you!
It seems your approach needs using `histogram` after all.
The reason why I do not want to use `histogram` and use pre-aggregated data is that the `data` to be aggregated is *very* large . So I want to aggregate the data using BigQuery, and pass it to highcharts column chart. I think aggregating it on browsers using `histogram` is difficult.

**Comment by Denyllon** [comment]
Hello @taichi-jp ,

As @KacperMadej said before, we're using **Issues** tab for tracking bugs, and this kind of questions should be asked on one of our support channels. I see, that you asked this question on our forum where you've got very precise answer (as a reminder https://forum.highcharts.com/viewtopic.php?f=9&t=41377). If you will have any questions in the future, just contact our support team. I'm absolutely sure that you will get a satisfactory answer.

Kind regards!
