### ISSUE TITLE
Tooltip appears too far from plot area in x-range charts when using outside option

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/highcharts#9727]
#### Expected behaviour
For x-range charts, if you set the tooltip options to `outside: true`, the tooltip should be anchored to the visible part of the series.

#### Actual behaviour
The tooltip position for x-range charts defaults to (I believe) the center of the x-range for each point. If the center of the point range is outside of the x-axis min/max, the tooltip will appear too far from the chart.

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/lanimelrok/xenc6v9L/)
1. Make sure to expand width of panel that contains chart
2. Hover over the "Prototyping" series
3. Notice tooltip appears outside of chart area

#### Product version
Highstock 6.2.0

**Comment by KacperMadej** [comment]
Hi @LaniMoo 
Thank you for reporting about the problem.

_Internal note:_
Looks like tooltip's point anchor is not affected by set xAxis extremes.
