### ISSUE TITLE
Bubble Chart StyledMode incorrectly handles Negative z values

### ISSUE THREAD

**Issue by DannyLingard** [highcharts/highcharts#9728]
#### Expected behaviour
As with styledMode = false

#### Actual behaviour
.highchart-negative class added only to points based on y value instead of z. Have tested setting relevant displayNegative, negativeColor and zThreshold at both the series{} and bubble{} within plotOptions.

#### Live demo with steps to reproduce
http://jsfiddle.net/9b328kv0/1/

#### Product version
Highcharts v7.0.0

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! 

Demo with the fix applied: http://jsfiddle.net/highcharts/5nthykuo/
