### ISSUE TITLE
Y-Azis Plotted values didn't match with  scale Line Chart

### ISSUE THREAD

**Issue by ramasamykasiviswanathan** [highcharts/highcharts#9729]
#### Expected behaviour
The points should be plotted in the appropriate scale of Y-Axis

#### Actual behaviour
For the line graph on Scenario 2, the value -48 on Y axis and 0.25 on X axis is plotted on positive scale,

#### Live demo with steps to reproduce
https://jsfiddle.net/jzk8sLog/6/

#### Product version
Latest

**Comment by TorsteinHonsi** [comment]
Hi,

It's because you had stacking enabled. See https://jsfiddle.net/highcharts/h1dw5frp/.

**Comment by sebastianbochan** [comment]
Hi @ramasamykasiviswanathan,
Thank you for reporting. The reason of problem is enabled the `stacking` option which sums all series and draw points. When you disable it, all lines are draw properly.

Demo:
- https://jsfiddle.net/BlackLabel/tsuhk7cb/

Let me know if it is your requested chart.

**Comment by ramasamykasiviswanathan** [comment]
Thank you very much.
