### ISSUE TITLE
Bubble Chart Tooltip doesn't format xDateFormat on type = 'datetime'

### ISSUE THREAD

**Issue by DannyLingard** [highcharts/highcharts#9730]
#### Expected behaviour
As per documentation, works fine on other chart types.

#### Actual behaviour
Outputs 'datetime' as milliseconds, even though xAxis correctly handles and labels. Have never had trouble in the past using x,y charts.

#### Live demo with steps to reproduce
http://jsfiddle.net/sdyg3ne4/

#### Product version
v7.0.0

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

#### Workaround
Set the value format inside the `pointFormat`: http://jsfiddle.net/highcharts/hoejry25/

PS: This is not a regression, it also happens in older releases.

**Comment by KacperMadej** [comment]
Related to https://github.com/highcharts/highcharts/issues/3552
