### ISSUE TITLE
Version 7.0.1 mutate `config.series`

### ISSUE THREAD

**Issue by monopieces** [highcharts/highcharts#9731]
#### Expected behaviour
Should not mutate `config.series`

#### Actual behaviour
- Toggle checkbox, change chart to percentage, yAxis value change to percentage
- Toggle checkbox again, change chart back to normal,  yAxis value still remain percentage

#### Live demo with steps to reproduce
https://jsfiddle.net/pieces/o74n9pmh/40/

#### Product version
7.0.1

**Comment by sebastianbochan** [comment]
Duplicate of https://github.com/highcharts/highcharts/issues/9732
