### ISSUE TITLE
Selected option is not working with pie chart

### ISSUE THREAD

**Issue by VBIManonmaniM** [highcharts/highcharts#9733]
#### Expected behaviour
Selected option has to work with pie chart

#### Actual behaviour
But it is selecting the points

#### Live demo with steps to reproduce
http://jsfiddle.net/h7cwqy1t/

#### Product version
Highcharts
#### Affected browser(s)
All browsers

**Comment by KacperMadej** [comment]
Additionally: select state has no different style, so it's not noticeable. Here's a demo with color changed on select: http://jsfiddle.net/BlackLabel/2ckw8o3f/

Doesn't look like a bug.
