### ISSUE TITLE
Highcharts 7.0 Style Mode

### ISSUE THREAD

**Issue by DronkWynie** [highcharts/highcharts#9734]
#### Expected behaviour
Style Mode missing in highcharts 7.0 Typescript

#### Actual behaviour
I Upgraded from 6.2.0 to 7.0, The style-mode folder "js" folder seems to be missing. did the approach change for styled mode? How should one include it now?

#### Steps to reproduce
in highcharts 6.2.0 this works:
import * as Highcharts from "highcharts/js/highcharts";

in highcharts 7.0 this **does not work**:
import * as Highcharts from "highcharts/js/highcharts";

#### Product version
Highcharts 7.0

**Comment by DronkWynie** [comment]
Found it: https://api.highcharts.com/highcharts/chart.styledMode

**Comment by TorsteinHonsi** [comment]
For the records, this is mentioned in the Upgrade notes in the [changelog](https://www.highcharts.com/documentation/changelog#highcharts-v7.0.0).
