### ISSUE TITLE
Highcharts highstock using jsdom

### ISSUE THREAD

**Issue by sorb999** [highcharts/highcharts#9735]
I am trying to create highstock chart using jsdom. I got one [solution ](https://gist.github.com/graingert/10ab7c6b6f9af4c87a3482dcdacc8bed)but it is not working with highstock chart. Btw it is working fine with above example i.e. highcharts only. This is the svg image I am got.

You can find more details about the issue here: 

[https://stackoverflow.com/questions/53867608/highcharts-highstock-using-jsdom](https://stackoverflow.com/questions/53867608/highcharts-highstock-using-jsdom)

Here is my [code](https://github.com/sorb999/highcharts-jsdom)

Please let me know if you need any other information related to issue.

**Comment by sebastianbochan** [comment]
Hi @sorb999,
The github is our bugtracker, so for general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.
