### ISSUE TITLE
Highstock - calling chart update method breaks stock-tools.

### ISSUE THREAD

**Issue by flare256** [highcharts/highcharts#9740]
#### Expected behaviour
Chart.update call should not affect stock-tools functionality in the case of options which don't touch stock-tools settings.

#### Actual behaviour
Update call with empty options object as argument is breaking (broken onClick listener?) stock-tools. 

#### Live demo with steps to reproduce
http://jsfiddle.net/t8v2eh4y/
For eg. if you want to draw a line when you click on adequate icon, nothing happens when you hover and then click on the chart area.

#### Product version
Highstock 7.0.1

#### Affected browser(s)
Tested on Google Chrome 71.0.3578.98 (64-bit)

**Comment by KacperMadej** [comment]
Hi @flare256 

Thank you for reporting about the bug.
**Workaround** - manually reset events through `chart.navigationBindings.update()`.
Demo: http://jsfiddle.net/BlackLabel/7fqskgun/

_Internal note:_
`stockToolbar` is being recreated (destroy current + create new) on each chart update, but events are not. Looks like `navigationBindings.update` should be called at some point.

Extras:
- there's a typo `highcharts-highcharts-zoom-y` in `stock-tools` blocking zoom Y.
- is `Navigatorion` in `stock-tools` not a typo?

**Comment by pawelfus** [comment]
*Internal note:*
It's probably a result of splitting stockTools and bindings. Bindings used to be updated with stockTools, now update needs to be called directly.
