### ISSUE TITLE
Using point.name gives TypeError TypeScript

### ISSUE THREAD

**Issue by DronkWynie** [highcharts/highcharts#9741]
#### Expected behaviour
TypeScript: property "**name**" is valid on "**point**" class

#### Actual behaviour
Type error when accessing the property name on point

#### Live demo with steps to reproduce
Now:
```
tooltip: {
    formatter: function () {
        return (<any>this.point).name;
    },
},
```
Expected:
```
tooltip: {
    formatter: function () {
        return this.point.name;
    },
},
```
#### Product version
7.0.1

**Comment by sebastianbochan** [comment]
Hi @DronkWynie,
Thank you for reporting about the problem.

@bre1470
