### ISSUE TITLE
Setting 'lineWidth' on 'MACD' indicator affects on signal line after hovering series

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#9742]
#### Expected behaviour

The `lineWidth` parameter shouldn't affect on signal line after hovering series. Also consider excluding this options from MACD series documentation.

#### Actual behaviour

Currently, when `lineWidth` parameter is set to any number value, and we hover the series, then signal line width is set equal to this value.

#### Live demo with steps to reproduce
JSFiddle: http://jsfiddle.net/mzLuaenv/
1. Hover series
2. Move a mouse outside the chart.
3. See what happen with signal line width.

**Comment by pawelfus** [comment]
I don't know the context of the issue, but workaround for the OP's demo is to disable `states.hover` state: http://jsfiddle.net/BlackLabel/3Lzvbe7g/
