### ISSUE TITLE
Word Cloud does not show all data

### ISSUE THREAD

**Issue by ChrisLock90** [highcharts/highcharts#9743]
Hi,

I have a problem where our word cloud charts are not displaying correctly on every other refresh.

Worth noting that putting the same data into a pie chart gives the correct information. 
Also that If i manually refresh the widget it will not change to the correct/incorrect data, CTRL + F5 has varying results, it may change the data it may not.

Here is the JSON data
![image](https://user-images.githubusercontent.com/17903156/50336307-c7687d80-0505-11e9-80c3-d8cf45fc67b6.png)

#### Expected behaviour
Should show all of the data items in the word cloud

![image](https://user-images.githubusercontent.com/17903156/50336495-3940c700-0506-11e9-9f8b-fb6036f67b76.png)

#### Actual behaviour
In my example I have 6 items in the data for a word cloud and only 5 will show up when the widget is first created. Then the widget will refresh and redraw and it will have all 6 and show correctly. It will refresh again and only have 5 items and this continues.

![image](https://user-images.githubusercontent.com/17903156/50336453-27f7ba80-0506-11e9-8577-0c574a4832a2.png)

#### Product version
Highcharts Version 6.2 and 7.0

#### Affected browser(s)

I have tested in Chrome, Edge and Firefox.

**Comment by KacperMadej** [comment]
Works fine in v7.0.2
Demo: https://jsfiddle.net/BlackLabel/cqxuft2e/

Closing as resolved
