### ISSUE TITLE
Highstock - legend and title overlaps stock tools toolbar.

### ISSUE THREAD

**Issue by flare256** [highcharts/highcharts#9744]
#### Expected behaviour

When set and left aligned, title (and subtitle) and legend should take into account stock tools toolbar position.

#### Actual behaviour

Legend and title overlaps stocks tools toolbar.

#### Live demo with steps to reproduce
http://jsfiddle.net/936n7oxm/

#### Product version
Highstock 7.0.1

#### Affected browser(s)
71.0.3578.98 (Official) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @flare256,
Thank you for reporting about the problem.

**Comment by pawelfus** [comment]
*Internal note:*
I think we need to apply extra margin on these elements (legend, title, and probably xAxis title) or check why it's aligned to the border, not margins.

**Comment by KacperMadej** [comment]
**Workaround:**
add x offset for misaligned elements - http://jsfiddle.net/BlackLabel/dk5aq2n4/

**Comment by TorsteinHonsi** [comment]
_Internal note_:
It's because the stock toolbar modifies `chart.plotLeft`, but the title and legend uses `chart.spacing` and/or `chart.margin`. So modifying `chart.plotLeft` will not help in this case. Probably we need to go in at the right place and modify the spacing or the `spacingBox` instead.

https://github.com/highcharts/highcharts/blob/0a5d555a3e45d92eef18de945119cbb53a6e781d/js/modules/stock-tools-gui.js#L782-L791

**Comment by sebastianbochan** [comment]
**Internal note**
Modifing spacingLeft / spacing box its not perfect solution. There is still problem with updates on legend / rangeselector and random issues with titles. 

After deeper debugging, it looks like a really complex problem isolated from stockTools. 

Simplified demo: https://jsfiddle.net/BlackLabel/Lu3ysmvf/

**Comment by TorsteinHonsi** [comment]
It's also not specific to Highstock: https://jsfiddle.net/highcharts/3nrhso0e/

**Comment by pawelfus** [comment]
Since #9795 is fixed, spacing can be updated: https://jsfiddle.net/highcharts/3nrhso0e/ (v7.1.1+) but the OP's demo is still broken.

**Comment by raf18seb** [comment]
I don't see any warnings in the console anymore (newest Chrome 80). Tested on 3 machines (Mac and Windows 10). Can someone confirm whether the issue still occurs and provide the exact steps to reproduce it?

**Comment by raf18seb** [comment]
Status: I modified `spacingBox`, but the rangeSelector positioning needs to be refactored.
Also, I noticed that `marginRight` doesn't affect the rangeSelector, [see](https://jsfiddle.net/BlackLabel/g2rhztua/).
Instead of creating a new ticket, I'll kill it on the occasion.
