### ISSUE TITLE
Firefox 64.0 point hover highlight issue

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#9745]
On Firefox 63 everything worked fine. After updating to 64.0 you can see strange point highlighting behavior on point hover.

[Video](https://drive.google.com/file/d/1VyYT3Xvmwc3A4DGSdByWJlwt8F8qrS2F/view)
[jsFiddle](https://jsfiddle.net/BlackLabel/ueoyLt32/)
Similar issue also occours while adding points: [jsFiddle](https://jsfiddle.net/BlackLabel/qdawhb2g/)

#### Product version
Highcharts 7.0.1

#### Affected browser(s)
Firefox 64.0

**Comment by sebastianbochan** [comment]
![zrzut ekranu 2018-12-21 o 13 59 39](https://user-images.githubusercontent.com/2115686/50343820-b2511600-0528-11e9-8deb-8bade2fe9629.png)

**Comment by joldag** [comment]
Thanks for reporting to Mozilla, @TorsteinHonsi! Looks like it has been fixed with FF 65.0.
