### ISSUE TITLE
columnrange + datalabels + resize = position wrong

### ISSUE THREAD

**Issue by rudacs** [highcharts/highcharts#9747]
#### Expected behaviour
The position of the top label is updated (position) according to the graphic, same as the bottom label.

#### Actual behaviour
The position of the top label is not updated to follow the column position. The bottom label is updated.

#### Live demo with steps to reproduce
http://jsfiddle.net/Lzcsdywr/1/
Resize the preview portion to verify that the top label is in the wrong position.

#### Product version
Highcharts 7.0.1

**Comment by sebastianbochan** [comment]
Hi @rudacs,
Thank you for reporting about problem. Its a regression since v7.0.

**Internal note**
Bisect leads me to the commit: https://github.com/highcharts/highcharts/commit/60e9624

**Comment by TorsteinHonsi** [comment]
Thanks. Bisecting lead me to 192e576e2babd6f19b1de82d7da2719e6eaf125d.
