### ISSUE TITLE
Problem with 'mouseup' event in chart opened in a new window

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#9748]
#### Expected behaviour
The zoom should work.

#### Actual behaviour
Zoom-in on the chart is impossible, because the 'mouseup' event is not respected.

#### Live demo with steps to reproduce
1. Open jsfiddle: http://jsfiddle.net/BlackLabel/trv3ey4w/
2. Click twice on the 'Open new window' button
3. Zoom on the chart

#### Product version
Highcharts 7.0.1

#### Affected browser(s)
All

**Comment by ppotaczek** [comment]
Probably caused by Pointer `setDOMEvents` method. 

Workaround: http://jsfiddle.net/BlackLabel/bujf8s36/

**Comment by tw2as** [comment]
This is still an issue in the current version (10.3.3) Highcharts and Highstocks.
Thanks @ppotaczek for the workaround but instead of using workaround (which is a hack of the library) IMO it should be implemented within the library.

**Comment by insaneintenti0n** [comment]
As a potential heads-up to anyone else relying on the workaround, after updating to 10.x, I needed to remove the lines

```
this.unbindContainerMouseLeave = addEvent(
            container,
            'mouseleave',
            pointer.onContainerMouseLeave
        );
```

and

`this.unbindContainerMouseLeave();` in the destroy function

otherwise I got a tooltip error anytime the mouse left the graph container.

**Comment by Prodyjin** [comment]
Hi, i post this from highcharts community forum like Sebastian Wędzel told me, it seems the workaround is not working in the latest version of highcharts.
Hi all,
we found a bug using highcharts with highcharts-react-official in a react application
In this application we have a window.open with ReactPortal component which render the chart.
Everything works fine, beside zoom.
we this highcharts packages:
"highcharts": "^11.4.6",
"highcharts-react-official": "^3.2.1"

we share here a replicated example:
https://codesandbox.io/p/sandbox/react-portal-render-chart-in-the-pop-up-window-forked-fx4qjl?file=%2Fsrc%2Findex.js%3A5%2C1&ts=9tdh6892)

**Comment by hubertkozik** [comment]
Hi @Prodyjin! Here's the workaround for you for the latest version of Highcharts: https://jsfiddle.net/BlackLabel/5hceud6f/

I've added the issue to our backlog, we will investigate adding this fix natively.

**Comment by Prodyjin** [comment]
> Hi @Prodyjin! Here's the workaround for you for the latest version of Highcharts: https://jsfiddle.net/BlackLabel/5hceud6f/
> 
> I've added the issue to our backlog, we will investigate adding this fix natively.

Hi Hubert, works wonderfully!
Thank you! 👍
