### ISSUE TITLE
some of dataLabels not showing in stacked column Highchart

### ISSUE THREAD

**Issue by Umartahir93** [highcharts/highcharts#9751]
Expected behaviour
Data labels in the stacked bar should not hide. You can see in screenshot attached below Data Label for date dec11 dec18 dec21 is missing on stack bar. Please provide me a best way by which i can avoid this. I have also tried overlapping true and padding 0 but it wasn't worth a shot. 

Actual behaviour
DataLabels are missing on following date date dec11 dec18 dec21
![image](https://user-images.githubusercontent.com/31737085/50382363-4f45b780-06bf-11e9-9a5a-588166557c3d.png)

Live demo with steps to reproduce
http://jsfiddle.net/EnJ9v/89/

#### Affected browser(s)
chrome mozrilla

**Comment by sebastianbochan** [comment]
Hi @Umartahir93,
The github is our bugtracker for reporting bugs. For the general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

ps. By default datalabels which overlap or are out of the edge, are hidden. You can change it by [allowOverlap](https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.allowOverlap) and [crop](https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.crop) params.

**Comment by Umartahir93** [comment]
> Hi @Umartahir93,
> The github is our bugtracker. For the general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.
> 
> ps. By default datalabels which overlap or are out of the edge, are hidden. You can change it by [allowOverlap](https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.allowOverlap) and [crop](https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.crop) params.

I am sorry. I will refer to support next time.

Thank you @sebastianbochan
