### ISSUE TITLE
Scatter Chart : Panning is not working properly after zoom

### ISSUE THREAD

**Issue by vbiarulkumar** [highcharts/highcharts#9752]
#### Expected behaviour
Panning should work after zoom.

#### Actual behaviour
Panning  does not work after doing zoom.

#### Live demo with steps to reproduce
https://jsfiddle.net/5g80p2n6/

#### Product version
latest

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @vbiarulkumar,
Thank you for reporting. It looks like a bug.

**Internal note**
It looks like the problem with call `zoomOut` function, when panning.
