### ISSUE TITLE
Dynamic update artifacts on Firefox v64

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#9753]
#### Expected behaviour
The chart should not leave any artifacts on the screen during the update, like it works on Chrome and on previous Firefox versions.

#### Actual behaviour
During an update some old point traces are not removed until animation stops.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/dynamic-update
Open the chart in CodePen/jsFiddle

![screenshot 2018-12-24 at 09 20 24](https://user-images.githubusercontent.com/15050812/50394328-1825e380-075d-11e9-9dcd-518d5b49ba12.png)

#### Affected browser(s)
Firefox v64

**Comment by TorsteinHonsi** [comment]
Probably the same as #9745, awaiting response from Mozilla.

**Comment by and-cesbo** [comment]
In Firefox 65.0b7 works fine. Issue only in 64.0

**Comment by pawelfus** [comment]
@and-cesbo This is strange, which OS do you have? @KacperMadej was able to reproduce the issue in FF 65.0b7 on Windows 10. @KacperMadej could you test once again? Thanks!

**Comment by KacperMadej** [comment]
I can still recreate the problem in Firefox 65.0b7 / Windows 10
