### ISSUE TITLE
Incorrect color filling in type: areaspline 

### ISSUE THREAD

**Issue by vodolazskikh** [highcharts/highcharts#9754]
Incorrect color filling in small screen width.
Open the demo, set demo-screen width on 450-490px;
[https://jsfiddle.net/vodolazskikh/x7q3Luy1/4/](url)
Highcharts type: areaspline the latest version from www.highcharts.com

tested in google chrome

**Comment by sebastianbochan** [comment]
Hi @vodolazskikh,
When I set width as 450px in your demo I see the same colors like in higher resolutions.

450px
<img width="552" alt="zrzut ekranu 2018-12-27 o 09 17 11" src="https://user-images.githubusercontent.com/2115686/50472288-6c78cf80-09b8-11e9-852c-5c037b6a5f86.png">

900px
<img width="927" alt="zrzut ekranu 2018-12-27 o 09 18 58" src="https://user-images.githubusercontent.com/2115686/50472300-7b5f8200-09b8-11e9-8c45-8f5f8834662b.png">

Could you take a screenshot of your charts and leave me a information about OS? 

Chrome 71.0.3578.98

**Comment by vodolazskikh** [comment]
Windows 10 in Chrome 71.0.3578.98 too. 
![image](https://user-images.githubusercontent.com/36884611/50881408-09eded80-1414-11e9-9f02-678407e8e623.png)
![image](https://user-images.githubusercontent.com/36884611/50881425-140fec00-1414-11e9-946b-0a334c5b1c2a.png)

**Comment by KacperMadej** [comment]
The problem is visible on Chrome / Win10.
Here's a simpler demo with the same problem multiple times: https://jsfiddle.net/BlackLabel/pm2zkaLb/1/

On Chrome/Win10 the chart looks like this:
![chrome](https://user-images.githubusercontent.com/8960408/50894822-8f69a180-1404-11e9-9c2c-6cf51416bea3.jpg)

**Comment by sebastianbochan** [comment]
Thank you for the feedback. I was able also reproduce it when did some resizing actions. Finally I discovered that the `width:305px` breaks the chart.

**Simplified demo:**
- https://jsfiddle.net/BlackLabel/wqcpm52f/

MacOSX 10.12.4
Chrome: 71.0.3578.98

**Comment by vodolazskikh** [comment]
> I was able reproduce it, during some resizing actions. Finally I discovered that the `width:305px` breaks the chart.
> 
> **Simplified demo:**
> 
> * https://jsfiddle.net/BlackLabel/wqcpm52f/
> 
> MacOSX 10.12.4
> Chrome: 71.0.3578.98

How to resolve that?

**Comment by KacperMadej** [comment]
This looks like a general issue in Chrome as we couldn't recreate the problem in any other browser. I have recreate the problem in pure SVG (no Highcharts, no JavaScript) and reported to Chormium:
https://bugs.chromium.org/p/chromium/issues/detail?id=923850

Workaround for now seems to be to use other browser (or check other versions of Chrome), but let's wait for the Chromium issue to be resolved.
