### ISSUE TITLE
Selection problem in Column/Bar Chart

### ISSUE THREAD

**Issue by VBIManonmaniM** [highcharts/highcharts#9755]
Please look into the jsfiddle link.It has column chart.When I am selecting any point that selected point color is changed to grey But I want the selected point to be remain same color but all other points should be changed to grey apart from the selected point.

#### Live demo with steps to reproduce
https://jsfiddle.net/arb576oc/1/

#### Product version
Highcharts

#### Affected browser(s)
All browsers

**Comment by VBIManonmaniM** [comment]
@nsdevaraj Please look into the issue

**Comment by sebastianbochan** [comment]
Hi @VBIManonmaniM,
The github is our bug tracker. For general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.
