### ISSUE TITLE
Unable to wrap Series.prototype processData method

### ISSUE THREAD

**Issue by likwifi** [highcharts/highcharts#9756]
#### Actual behaviour
Getting baseProcessData is not defined error when trying to wrap processData method

**Comment by sebastianbochan** [comment]
Hi @likwifi,
The github is our bug tracker. For the general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.

ps. I prepared you a simple demo which allows you to wrap the method. 
**Demo:**
- https://jsfiddle.net/BlackLabel/kjrdxn4z/

**Docs:**
- https://www.highcharts.com/docs/extending-highcharts/extending-highcharts
