### ISSUE TITLE
Boost module and noDataToDisplay module together on scatter charts produce unexpected results

### ISSUE THREAD

**Issue by alirezameftahi71** [highcharts/highcharts#9758]
When we use boost module and noDataToDisplay module at the same time, when the scatter chart is at boost mode, it shows "No data to display" at the background. Even though there is data on the chart.

#### Actual behaviour
As you can see in the demo fiddle, the words "No Data To Display" appear in the background, while obviously there is A LOT of data on the chart.

#### Live demo with steps to reproduce
This is highcharts boost module demo fiddle for scatter chart and all I did was to include the 'no-data-to-display.js' module to it.
https://jsfiddle.net/41v07amx/

#### More info
When I set `yAxis.min` and `yAxis.max` to `null`, and the problem seems to be fixed.

#### Product version
Highcharts 7.0.1

#### Affected browser(s)
Tested and produced on Google Chrome

**Comment by sebastianbochan** [comment]
Hi @alirezameftahi71,
Thank you for reporting. It looks like a problem with setting `dataMin` and `dataMax` for series. Both values are empty and the `hasData` function returns false.

At this moment, as workaround you can wrap `hasData` method and change the main condition.

**Demo:**
https://jsfiddle.net/BlackLabel/xfLsgr6o/

@oysteinmoseng  what do you think about this fix?

**Comment by KacperMadej** [comment]
It's a bug, so let's keep it open until it's no longer labeled as a bug or until a fix is provided.

**Comment by sebastianbochan** [comment]
I agree with @KacperMadej, cause I introduced only workaround and possibly fix.

**Comment by TorsteinHonsi** [comment]
@sebastianbochan The fix looks good to me, will you create a PR?

**Comment by sebastianbochan** [comment]
Yes sure, will do!

**Comment by sebastianbochan** [comment]
@TorsteinHonsi Im curious, which test was not passed? I did not have any error.

**Comment by TorsteinHonsi** [comment]
I got 108 errors on `gulp test` among others in `unit-tests/utilities/utilities`.

**Comment by sebastianbochan** [comment]
Thank you for he information, its strange because I pulled all highcharts / highcharts-utils and rebuild. Will check and compare with other guys.

**Comment by TorsteinHonsi** [comment]
Sophie mentioned an issue in the gulpfile, that may be it.
