### ISSUE TITLE
The index.d.ts type definition is incomplete for IndividualSeriesOptions

### ISSUE THREAD

**Issue by malik97160** [highcharts/highcharts#9759]
#### Live demo with steps to reproduce

![image](https://user-images.githubusercontent.com/41372672/50475459-1f4f2a80-09c5-11e9-9fe9-3e4d320920d2.png)

#### Product version
Highcharts v7.0.1

#### Affected browser(s)
All brower

**Comment by pawelfus** [comment]
Hi @malik97160 

Thanks for reporting! 

FYI @bre1470

**Comment by bre1470** [comment]
Hi @malik97160,
Thank you for the report. You must to set the `type` property (even if it is just a `line` series) in the series object to get the additional options for a series.

**Comment by malik97160** [comment]
ok thank you @bre1470 .
