### ISSUE TITLE
Polar chart - Xaxis lable overlap with multiple categories

### ISSUE THREAD

**Issue by rajeshdanabal** [highcharts/highcharts#9761]
#### Expected behaviour
When we have multiple categories on xaxis, xaxis labels should not get overlapped and should get hidden if there is no room for it or it should get elevated with a connector pointing like as in pie chart data labels.

#### Actual behaviour
When we have multiple categories on xaxis, xaxis label is getting overlapped on polar chart when it is getting hidden on line or polar charts with out categories (You can see that in live demo).

#### Live demo with steps to reproduce
http://jsfiddle.net/rajeshdanabal/cseon2az/41/

#### Product version
Highcharts V7.0.1

#### Affected browser(s)
Tested on Google chrome - Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Hi @rajeshdanabal 

Thanks for reporting this issue. 

**Workaround:**
Manually hide overlapping labels: http://jsfiddle.net/BlackLabel/ca3hwr48/

Snippet:
```javascript

  function hideOverlappingCategories() {
    var ticks = this.xAxis[0].ticks,
      categories = this.xAxis[0].tickPositions.map(function(tick) {
        return ticks[tick].label;
      });

    this.hideOverlappingLabels(categories);
  }


  $('#container-polar_with_cat').highcharts({
    chart: {
      polar: true,
      events: {
        load: hideOverlappingCategories,
        redraw: hideOverlappingCategories
      }
    },
    ...
  });
```

**Comment by rajeshdanabal** [comment]
Thank you very much for the reply and workaround. I will try that.
