### ISSUE TITLE
cleanRecursively in series' update

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#9762]
#### Behaviour
`cleanRecursively` in `series.update` runs on `userOptions` stored in the series, but that object with options is just a reference to the series object in chart's options, so in case a user will change initial chart options object (namely the series we're discussing) then `cleanRecursively` will not compare with current series options. Only series' data is detected and `doSoftUpdate` is `true` - `setData` runs instead.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/kvyh1nu2/

#### Workaround
Call series.update with an empty object (like in the demo - 3rd update).
or
Add something that will prevent soft update - e.g. option defined as an array, like `zones`.
Demo: https://jsfiddle.net/BlackLabel/kvyh1nu2/1/

**Comment by TorsteinHonsi** [comment]
A possible fix is to run with `this.options`:

`newOptions = H.cleanRecursively(newOptions, this.userOptions);`

Do you see any problems with that?

**Comment by KacperMadej** [comment]
So like `newOptions = H.cleanRecursively(newOptions, this.options);`, right?
It will break cases like this:
1. user sets some general plotOptions for all series or used series type (plotOptions.<series_type>)
2. user updates an option for the series that is the same as the already used general option
3. the option is filtered out by `cleanRecursively`, because when checking against `series.options` it's already set
4. user changes general plotOptions expecting the option from series to take precedence, but it was never set, so plotOptions option will apply

Demo: http://jsfiddle.net/BlackLabel/7dm15ut6/1/ (tested locally and simulated on line 23 in the demo)

After longer code checking, the solution here might be to use a copy of options instead of the original object when setting `userOptions` for series in `setOptions.setOptions`, so like:
`this.userOptions = merge(itemOptions);`

Additionally, it took me some time to understand that `oldType` is not previous series type, but initial series type, so to avoid any confusion for anyone else I have prepared a commit in the related PR.
