### ISSUE TITLE
Rendering error with line graph

### ISSUE THREAD

**Issue by Benjamin-Lee** [highcharts/highcharts#9766]
#### Expected behaviour

Plot a large number (100) of linked series.

#### Actual behaviour

There appears to be a rendering artifact:

![image](https://user-images.githubusercontent.com/13618205/50547340-4d1ab600-0bf5-11e9-8793-5fb757756b6e.png)

All series start at the point (0, 0) and go until x=12000 so I know the region that is offset is not correct. The region is not interactive and does not have tooltips. Rerendering the chart with the series unlinked reveal the chart as expected:

![image](https://user-images.githubusercontent.com/13618205/50547357-979c3280-0bf5-11e9-8314-32c33da36cf9.png)

#### Live demo with steps to reproduce

[DNAvisualization.org](DNAvisualization.org) with [this file](https://github.com/Benjamin-Lee/DNAvisualization.org/blob/master/example_seqs/100_12000bp_random_seqs.fasta)

#### Product version

Highcharts v7.0.1

#### Affected browser(s)
Safari 12.0.2
Chrime Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by KacperMadej** [comment]
Hi @Benjamin-Lee 

Thank you reporting about the problem.

I have tried to test the issue using the steps you have provided, but the web site give me `Error: Too many sequences` when trying to use the file you have provided.

Are you using boost module?

**Comment by sebastianbochan** [comment]
Hi @Benjamin-Lee,
I was also not able to reproduce the issue and run your demo. Always I got the info like below: 
<img width="520" alt="zrzut ekranu 2018-12-31 o 11 48 33" src="https://user-images.githubusercontent.com/2115686/50558924-3443fa80-0cf2-11e9-9cd9-c5aac1731fe1.png">

Is it possible to simplify scenario to introduce the issue?

**Comment by sebastianbochan** [comment]
Close due to inactivity. 
Please reopen if you will be able to supply is live demo or more details.
