### ISSUE TITLE
Highstock - Issues with client side export and stock tools.

### ISSUE THREAD

**Issue by flare256** [highcharts/highcharts#9767]
#### Expected behaviour

Exported chart should contain elements as they are on chart using offline-exporting and stock tools modules.

#### Actual behaviour

When you create an additional element on chart using stock tools and then delete it, it is still present on exported svg, pdf or jpeg. 

In addition, it seems that initial state (position, shape and/or labels) of simpleShapes (label, circle, rectangle), crookedLines (labels on Elliot 3 and 5 line), measure (XY, X and Y), advanced (fibonacci, parallel channel) and verticalLabels (vertical counter, vertical label, vertical arrow) is being exported instead of ones that were updated by user.

#### Live demo with steps to reproduce
http://jsfiddle.net/5n6xeoud/

#### Product version
Highstock 7.0.1

#### Affected browser(s)
71.0.3578.98 (official version) (64-bit)

**Comment by KacperMadej** [comment]
Hi @flare256 

Thank you for reporting about the problem.

To make the issue more general - exporting (not only client side exporting, but standard exporting too) fails to export edited stock tools shapes with other than initial options.

Simple demo: http://jsfiddle.net/BlackLabel/5gy2bo7z/

After few tests it seems like changes done through pop-up inputs is not saved for exported image and for other shapes even changes done through drag are not saved.
