### ISSUE TITLE
Sets on venn diagram are visually overlapping while there is no overlap in data

### ISSUE THREAD

**Issue by gtanczyk** [highcharts/highcharts#9769]
#### Expected behaviour
Circles should not overlap

#### Actual behaviour
![image](https://user-images.githubusercontent.com/1281113/50558515-59833980-0cef-11e9-9b32-9815b42e1239.png)
(error was marked in red color using Gimp)

#### Live demo with steps to reproduce
https://jsfiddle.net/q8ucmd0a/

#### Product version
Highcharts 7.0.1

#### Affected browser(s)
Latest google chrome

**Comment by sebastianbochan** [comment]
Hi @gtanczyk,
Thank you for reporting about the problem. 

@jon-a-nygaard
