### ISSUE TITLE
data labels not working if passed an object and not an array

### ISSUE THREAD

**Issue by fridlinimrod** [highcharts/highcharts#9770]
#### Expected behaviour
when dynamically adding a new points with configuration such as
```
 {
   x : time stamp,
   y: value, 
   datalabels: {
       enabled: true
   }
}
```
I expect the chart to update constantly with new points.
#### Actual behaviour
one / two points are added, then the chart stop updating, (I can see "Uncaught TypeError: point.dataLabels.forEach is not a function" in the console, and when moving the navigator - it malfunctioning (not recognizing mouse up)

#### Live demo with steps to reproduce

the original Highcharts example:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/dynamic-update/

my tiny addition is in line 14:
https://jsfiddle.net/JimmyBoy/kq57zmLs/1/

#### Product version

highstock 7.0.0 (in the fiddle using latest from github)

#### Affected browser(s)
only tried on chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @fridlinimrod,
Thank you for reporting about the problem. It looks like a problem with the `destroyElements` method which try to run loop on array instead of array.
 
I prepared you a wrap which replace `forEach` with `objectEach`.

Demo:
- https://jsfiddle.net/BlackLabel/u7rom2cx/

**Comment by pawelfus** [comment]
This looks like an issue with `dataGrouping` (in navigator) and multiple `dataLabels` feature. 

Disabled `dataGrouping` resolves the issue: https://jsfiddle.net/BlackLabel/fup5k2e6/ 

The best solution, at this moment, is to disable `dataGrouping` for all series on the chart: https://jsfiddle.net/BlackLabel/fup5k2e6/2/

Snippet:
```javascript
    navigator: {
    	series: {
      	dataGrouping: {
        	enabled: false
        }
      }
    },
    
    plotOptions: {
    	series: {
      	dataGrouping: {
        	enabled: false
        }
      }
    },
```

*Internal note:*
It's probably related to copying option over to grouped points. In the debugger we can observe that problematic label is defined as object: `{0 : DataLabel, enabled: true}` instead of `[{DataLabel}]`, here:

```javascrtipt
		                point.dataGroup = series.groupMap[i];
		                if (point.dataGroup.options) {
		                    point.options = point.dataGroup.options;
		                    extend(point, point.dataGroup.options);
		                }
```

**Comment by fridlinimrod** [comment]
perfect :)
I knew the dataGrouping was causing me problems and I disabled it in the series, but did not know it exists on the navigator as well!

Thanks for the quick response and the solution!!
I opened another bug [https://github.com/highcharts/highcharts/issues/9771](url)
you can have a look, it might be the same issue.

will appreciate if you could have a look. :)
Thanks again.

**Comment by pawelfus** [comment]
Hi @fridlinimrod 

You guessed right! It's the same issue. Disabling `navigator.series.dataGrouping` resolves the issue.
