### ISSUE TITLE
Y-Axis is not updating correctly (Highstock bar chart)

### ISSUE THREAD

**Issue by csigmanek** [highcharts/highcharts#9772]
#### Expected behaviour
Y-Axis values are calculated based on the visible values.

#### Actual behaviour
There is a strong overlapping to the righthand side. With dataGrouping enabled: false.

#### Live demo with steps to reproduce

1) Try to resize the navigator
2) Now move the navigator to the right and left side and watch the y-Axis labels.
3) On the top chart axis labels disapear when no data is visible -> this is not what I want ( I want to see at least softMin softMax
4) On the bottom chart labels stay. However, when you move the navigator to the righthand side of the big bars, the scale is not updated properly. E.g. 2 and 10 are visible, but axis scales >100. Though 100 is clearly hidden.

I want the accuracy of the top chart with the labels staying like in the bottom chart.

https://jsfiddle.net/m1uaLtdn/1/

#### Product version
Latest Highcharts

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @csigmanek 

Thank you for reporting about the problems.

Looks like you are writing about multiple issues at the same time. It would be better to keep one issues for one bug and if you are not sure if a case is a bug please contact technical support before creating an issue on GitHub. https://www.highcharts.com/blog/support/

P.S.
 If you want to have constant yAxis extremes regardless of zoom then you could use [`getExtremesFromAll`](https://api.highcharts.com/highcharts/series.line.getExtremesFromAll) and set it to `true`.

Without that option used in case all points have null values axis will not display labels unless min and max are set for the axis. You could also try adding a dummy series to keep axis displayed. Few options are there, but this is a support case and not a bug report.

**Comment by csigmanek** [comment]
Hello Kacper,
the bug I am talking about is this (look at picture):
![image](https://user-images.githubusercontent.com/25263374/50589578-879b8180-0e87-11e9-91c7-48c254d2b39d.png)

Of course I could write a function that calculates and sets min and max every time the extremes change. However, there is a build in function that is supposed to do exactly that. It is just noch working properly.

**Comment by KacperMadej** [comment]
Regarding your image: Difference between charts is due to dataGrouping. If it is enabled then only points in currently visible range are rendered and yAxis extremes are influenced only by those points. If dataGrouping is disabled then points under [cropThreshold](https://api.highcharts.com/highcharts/series.line.cropThreshold) are rendered and single points (on both ends) outside of current range are used for yAxis extremes calculations - this cannot be done for grouped data because there's no points outside or the current range.

**Comment by csigmanek** [comment]
Now I do understand the issue. Thank you. So I gues I'll have to implement the min / max change myself.
