### ISSUE TITLE
Pie chart does not render correctly in pdf (offline export)

### ISSUE THREAD

**Issue by constantintaivan** [highcharts/highcharts#9779]
Consider exporting SVG directly to PDF using the same tools as Highcharts shows at [client-side-export](https://www.highcharts.com/docs/export-module/client-side-export). When using the [latest jsPDF build  (yWorks fork)](https://github.com/yWorks/jsPDF/releases/tag/v2.0.0),  and [svg2pdf ](https://github.com/yWorks/svg2pdf.js/releases/tag/v1.3.0)I get the results from below - pie chart gets broken.

A workaround is to downgrade the above reference as used in this issue: ([7142](https://github.com/highcharts/highcharts/issues/7142)). The problem with this is that any other features I use in application such as [AutoTable jsPDF plugin](https://github.com/simonbengtsson/jsPDF-AutoTable) does not work anymore.

At best, I may need yWorks fork to be updated with the latest jsPDF release or consider adding a plugin instead of using a fork. The same for svg2pdf, I would expect pie rendering working fine for the latest release. 

**Expected behavior**
Pie charts should be rendered correctly in the latest version of jsPDF(yWorks fork)/svg2pdf

**Actual behavior**
Pie chart is rendered with a background color. Please see the image below:
![image](https://user-images.githubusercontent.com/19735774/50612981-e981d880-0ed3-11e9-997a-af77db52f9d6.png)

**Affected browser(s)**
All

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! Reported to svg2pdf at https://github.com/yWorks/svg2pdf.js/issues/67

**Comment by marco-boeck** [comment]
Yep, also draws lines around charts and legends, displays vertical grid lines, etc. Affects us, too.
Workaround seems to work fine according to my preliminary tests.

**Comment by marco-boeck** [comment]
Unfortunately, the workaround does break some stuff, e.g. exporting horizontal bar charts as PDF produces a chart without any bars: https://jsfiddle.net/frunkhvo/

**Comment by TorsteinHonsi** [comment]
The `clipPath` elements were the problem. I updated the snippet above.

**Comment by constantintaivan** [comment]
Hello Torstein,
I used latest releases of jsPDF (2.0.1) and SVG2PDF(1.3.2) and SVG charts can be added successfully to pdf. The fix is now part of those releases.
Thank you very much!
