### ISSUE TITLE
removal of points outside current plot is not working

### ISSUE THREAD

**Issue by fridlinimrod** [highcharts/highcharts#9782]
#### Expected behaviour
when I move the navigator and not seeing the last point, I should still be able to remove the last point.
series.removePoint(series.data.length -1).

#### Actual behaviour
if the navigator is positioned at the end (last point is within view) - all works as expected.
if the navigator is positioned in a position that puts the last point out of visible view- the last point is not removed.

#### Live demo with steps to reproduce

https://jsfiddle.net/JimmyBoy/9buk0d3g/3/
steps:
1. don't do anything and see how everything works.
2. move the navigator to the left.
3. wait several seconds.
4. move the navigator back to the end.
5. see all the points.

for convenience, I moved the yAxis to the left..

#### Product version

Highstock 7.0.0 (in the fiddle using latest from github)

#### Affected browser(s)
only tried on chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by KacperMadej** [comment]
Hi @fridlinimrod 

`series.data` is not a good points source in this case. Full info is in the [API class reference docs](https://api.highcharts.com/class-reference/Highcharts.Series#data), but in short it's about this part:

> In case [...] doesn't contain all the points. To access raw values, series.options.data will always be up to date.

Using `series.options.data` and not random data to better show that it works fine demo: https://jsfiddle.net/BlackLabel/pzrmf75v/

**Comment by fridlinimrod** [comment]
perfect!!
Thanks for the quick response :)
