### ISSUE TITLE
yAxis zoom in Highstock

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#979]
Is possible to zoom in, but not to zoom out - ResetZoom button doesn't show up. Example from docs: http://jsfiddle.net/gh/get/jquery/1.7.1/highslide-software/highcharts.com/tree/master/samples/stock/chart/zoomtype-y/

Workaround is to create separate button for that: http://jsfiddle.net/Fusher/GyurF/

**Comment by kevin-coelho** [comment]
Still having this issue in highstock. Currently using:

zoomType: 'x'
navigator: disabled
rangeSelector: enabled

reset zoom button is disabled. What I would like:

1. user drags across the chart to zoom in on specific section
2. reset zoom button appears
3. clicking it should reset to whatever the previous extremes were

This is different than using rangeSelector (inconvenient typing to get specific) or clicking a button which are fixed to whatever intervals are defined (1m, 3m, 6m etc.)

Ideally, reset zoom would keep track of a stack of extremes and clicking it twice would pop back until chart reaches the "All" zoom. Then as a user I can quickly zoom in and out of different sections.

**Comment by pawelfus** [comment]
**Workaround:**

To show/hide button under any circumstances, we can modify options in a simple wrapper, demo: http://jsfiddle.net/BlackLabel/npGey/25/

Snippet:
```javascript
(function(H) {
  H.wrap(H.Axis.prototype, 'zoom', function(proceed, newMin, newMax) {
    var ret;

    // This will always cause the button to show up after zooming in:
    this.chart.options.rangeSelector.enabled = false;
    this.chart.options.navigator.enabled = false;

    ret = proceed.call(this, newMin, newMax);

    // Restore default options
    this.chart.options.rangeSelector.enabled = true;
    this.chart.options.navigator.enabled = false;

    return ret;
  });
})(Highcharts);
```

@kevin-coelho  - regarding history of zooming events, I agree that would be cool feature. Maybe instead of double click I would prefer two small buttons (e.g. `<<` and `<`) but it probably vary between implementations and designs.

**Comment by SirZdanius** [comment]
The button doesn't show up for me either with navigator enabled and zoomType: 'xy'.

As far as i can see in the fiddle posted by @TorsteinHonsi this is how the library behaves - if either rangeSelector or navigator is enabled, then the reset zoom button doesn't appear.
It doesn't match the described behavior of appearing but only resetting y-axes (which is precisely the behavior my use case needs) or resetting the y-axes and returning the x-axis to the previous state (which, while unintuitive to me, would also be okay).

Is there some proper way to zoom out on the y-axes on a StockChart with scrollbars and navigator enabled?

**Comment by sebastianbochan** [comment]
Hi @SirZdanius,
The problem with "reset zoom button" is fixed in the master branch.

Demo:
- https://jsfiddle.net/q0xvgbz8/

Please test and let me know if all worked properly or you have any suggestions.

**Comment by SirZdanius** [comment]
Hi @sebastianbochan ,
Thanks for the quick reply.

Judging by the demo, the issue is indeed fixed! Any idea when we can expect this version on npm?

**Comment by EloHailwidis** [comment]
Hi @SamHoulder,
Any news about the date of the next version ?
Thanks :)

**Comment by sebastianbochan** [comment]
Hi @EloHailwidis,
The release will be this week. 
I advice you to subscribe our newsletter [here](https://www.highcharts.com/download) and be notified about new version, by email.
