### ISSUE TITLE
Inconsistent scale of xAxis when dynamically adding data

### ISSUE THREAD

**Issue by awxxxxxx** [highcharts/highcharts#9791]
There is a common scene, adding data when user scrolling and left boundary was reached. And the scale of xAxis should be consistent, after appending data.

#### Expected behaviour
The scale of xAxis should be consistent, after appending data.
![expected](https://user-images.githubusercontent.com/7347183/50381563-4eb01f80-06c5-11e9-90b0-279c2406c9c2.gif)

#### Actual behaviour
The scale of xAxis was changed.
![actual](https://user-images.githubusercontent.com/7347183/50381657-51ac0f80-06c7-11e9-970b-c88ba8a53c50.gif)

#### Live demo with steps to reproduce
demo: https://awbear.github.io/hdemo/
Open above link on phone browser, drag the chart to the left and the chart scale up.

It is related to https://github.com/highcharts/highcharts/issues/2535

#### Product version
Highstock version: 7.0.1

**Comment by raf18seb** [comment]
Demo: [jsFiddle](https://jsfiddle.net/BlackLabel/jvqw7hke/show)

**Comment by sebastianbochan** [comment]
Hi @awbear,
In my option it is not the bug, because you should set `xAxis.ordinal` as false.

**Docs:**
- https://jsfiddle.net/BlackLabel/ptq83wmo/

**Comment by awbear** [comment]
Hi sebastianbochan,

Thanks for reply.

I tried `ordinal: false`, it works expectedly, but as the document says, `Having ordinal: false will show any gaps created by the gapSize setting proportionate to their duration(nights and weekends also shown in stock chart).`, which is unexpected.

How to hide nights and weekends when set `ordinal: false` ?

Thanks.

**Comment by sebastianbochan** [comment]
@awbear,
You are right, I missed the information that it does not work only on mobile devices. Im reopening the issue and mark it as a bug.

**Comment by supernova16** [comment]
👀I have the same problem, so glad to see that someone had submitted it. 
Hope this could be fixed soon. Thanks！
