### ISSUE TITLE
Title and legend position overlap chart' plot area and subtitle

### ISSUE THREAD

**Issue by karolinakuzniewicz** [highcharts/highcharts#9795]
#### Expected behaviour
If chart should be responsive, `verticalAlign: "bottom"` of the `title` and `legend` should not cause overlapping with plot area or subtitle without chart's margin or spacing set. The chart should auto calculate the proper placement of title, subtitle, plot and legend.

#### Actual behaviour
If set the `title.verticalAlign: "bottom"` or `legend.verticalAlign: "bottom"` the title/legend or both overlap with plot area or the subtitle. The same problem occurs if there is many data and many items in legend.

#### Live demo with steps to reproduce
https://jsfiddle.net/5oc43frx/3/

#### Product version
Highcharts 7.0.1

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @karolinakuzniewicz 

Thanks for reporting the issue. This works as explained in the documentation. I believe you know that (as per your comment in #175), but let me share API description here: 

[title.verticalAlign](https://api.highcharts.com/highcharts/title.verticalAlign)
> Since 2.1.0
The vertical alignment of the title. Can be one of "top", "middle" and "bottom". When a value is given, the title behaves as if `floating` were true.

`floating` does not reserve the space, instead is rendered on top of other elements.

I agree, it would be useful to wrap title when it has different position (not only default) - let me mark this issue as enhancement.

**Comment by karolinakuzniewicz** [comment]
Ok, so right now there is no possible solution to place correct the title, subtitle, legend and plot to not overlap with each other? I've set `floating: false` but nothing has changed. https://jsfiddle.net/5oc43frx/8/

**Comment by pawelfus** [comment]
Changing `floating` won't work, as in docs it behaves like floating - not changing `floating` to true. Collision for title/subtitle is available only when placed on top of the chart, not below: https://jsfiddle.net/BlackLabel/e4v0moz5/
