### ISSUE TITLE
Network Graph not applying Color for individual points

### ISSUE THREAD

**Issue by trentmwillis** [highcharts/highcharts#9805]
#### Expected behaviour

Unsure.

The [documentation for `series.networkgraph.data.color`](https://api.highcharts.com/highcharts/series.networkgraph.data.color) states that you can set a color for a single data point in a `networkgraph` series, but it's not clear if that color should apply to the `from` point or the `to` point or both.

#### Actual behaviour

Setting `color` on an individual data point does not affect the appearance of the series at all.

#### Live demo with steps to reproduce

1. Visit the demo at https://jsfiddle.net/sq7rgnt6/
2. Note the data points are specifying the colors `green` and `orange`
3. Notice those colors are not showing in the chart at all

You can also notice that some of the points have been colored by setting a `nodes` array in the series. Like so:

```javascript
{
  nodes: [
    {
      id: '1',
      color: 'red'
    },
    {
      id: '2',
      color: 'blue'
    }
  ]
}
```

This is not documented anywhere. I tried it because it's similar to what you can do for Sankey charts and I read some of the source code. If this is the actual way to color individual data points, the documentation should be updated.

#### Affected browser: Chrome

---

P.S., apologies for all the `networkgraph` issues. We're very excited to use this new feature and are happy to help shore up areas that need improving 😄

**Comment by raf18seb** [comment]
Hi, trentmwillis!

Thank you for your suggestions and engagement! Actually, we are working on this now.
You can follow this thread: [9798](https://github.com/highcharts/highcharts/issues/9798)

For the clarification: data array does not define markers (circles) but links (connectors). So series.networkgraph.data.color property should color a particular link which will be available soon. To use it now you can use this workaround: 
`(function(H) {
  H.wrap(H.seriesTypes.networkgraph.prototype.pointClass.prototype, 'getLinkAttribues', function(proceed) {
    var linkOptions = this.series.options.link,
      pointOptions = this.options;

    return {
      'stroke-width': H.pick(pointOptions.width, linkOptions.width),
      stroke: H.pick(pointOptions.color, linkOptions.color),
      dashstyle: H.pick(pointOptions.dashStyle, linkOptions.dashStyle)
    };

  });
}(Highcharts));`

jsFiddle: [https://jsfiddle.net/BlackLabel/y4a1d96n/](https://jsfiddle.net/BlackLabel/y4a1d96n/)

Referring to the markers (series.networkgraph.nodes.color) we will improve the documentation and add info about that.

**Comment by trentmwillis** [comment]
Ah, okay. That makes sense!

We're primarily concerned with coloring the markers (and not the links between them), so we'll stick with the `nodes` array. Thanks for clarifying.

**Comment by pawelfus** [comment]
Works fine since v7.0.2 (see original demo, or this one: https://jsfiddle.net/BlackLabel/utg2wevy/)

Closing as resolved.
