### ISSUE TITLE
Error: Cannot find module '../highcharts-declarations-generator'

### ISSUE THREAD

**Issue by gtanczyk** [highcharts/highcharts#9806]
I'm trying to build highcharts v7 locally using `gulp dist`, but it fails on `dts` task. I'm not able to find `highcharts-declerations-generator` package/repository anywhere. I guess it's private.

Would it be possible to make it public?

**Comment by gtanczyk** [comment]
Related to #9579

**Comment by KacperMadej** [comment]
Hi @gtanczyk 

You are correct - it's private.
For local build use `gulp` and files will be created in `code` directory.

Could `highcharts-declerations-generator` be public @bre1470 ? or any other workaround for `dts` task to work?

**Comment by bre1470** [comment]
The generator will be public after leaving beta state. In the meantime I recommend to simply ignore the error or, if you depending on the ant task, to comment out the task reference in the `gulpfile.js` at https://github.com/highcharts/highcharts/blob/79c6abc471e2e96e437da5e444bd1ebfafdfb0f1/gulpfile.js#L1489-L1490.

**Comment by bre1470** [comment]
We decided to make the declarations generator public to increase the flexibility during the migration to TypeScript.
