### ISSUE TITLE
Treemap chart drillup button click event

### ISSUE THREAD

**Issue by euiRulz** [highcharts/highcharts#9812]
I want to do a modification to a treemap chart after click on the drill up button (back button). I am using the allowDrillToNode: true property, but there should be a way to catch the back button's click event.

**Comment by pawelfus** [comment]
Hi @euiRulz 

Thanks for contacting us. Did you try [`chart.events.drillup`](https://api.highcharts.com/highcharts/chart.events.drillup) event (or [`chart.events.drillupall`](https://api.highcharts.com/highcharts/chart.events.drillupall) for multiple series) ?

**Comment by sebastianbochan** [comment]
Hi @euiRulz,
The Drillup is for drilldown module events and treemap is using its own drilling feature, so this event is not being dispatched. 

I prepared you a demo that will allow you to catch both events: `drillUp` and `drillDown`. As a result you can run custom code on drill event of the treemap.

_drillUp_
```
    (function(H) {
      H.wrap(H.seriesTypes.treemap.prototype, 'drillUp', function(proceed) {
        // add code here to run before the drillup
        console.log('before drill up');

        // proceed
        proceed.apply(this, [].slice.call(arguments, 1));

        // add code here to run after the drillup
        console.log('after drill up');
      });
    }(Highcharts))
```

_drillDown_
``` 
    Highcharts.addEvent(Highcharts.Series, 'click', function() {
      console.log('drill down');
    });
```

**Demo:**
- https://jsfiddle.net/BlackLabel/1Lm4s63p/

**Internal note**
@jon-a-nygaard  I think that we should consider to add support for drillUp / drillDown events or, at least, define fireEvent, which allows to declare own event.

**Comment by euiRulz** [comment]
Thanks for the workaround @sebastianbochan. 
+1 for the **Internal note**

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard I'm concerned that the naming scheme here will cause confusion with the drilldown module. 

In Highcharts, the [drilldown feature](https://api.highcharts.com/highcharts/drilldown) means drilling from one point to load a whole new series.

In treemaps and sunburst, the `drillToNode` feature is something different - it focuses on a specific node and visualizes its parents, but it doesn't have anything to do with the drilldown module. 

There has already been cases where useres are confused about this, and we must take care to not cause more confusion. It is also unfortunate that the drillup-button has the same name as the unrelated button in the drilldown module. Ideally I would like the treemap/sunburst feature to be called something else, like `focusNode` or `setRoot`. Consequently the option `allowDrillToNode` must be renamed, and internal function like `drillToNode`, `drillUp` etc should also be renamed.

Opinions @jon-a-nygaard, @KacperMadej, @sebastianbochan ?

**Comment by sebastianbochan** [comment]
When we use `focusNode` param it is still confusing, let me explain why.

From our perspective this is different functionality. I agree, but from the end-user perspective in both scenarios (click on column or treemap point) he receives the same action (show points from lower level). So in my opinion its intuitively to have the same name of event for the same action in all cases (sunburst, treemap, column, line, pie etc) .

**Comment by TorsteinHonsi** [comment]
Yes, but that's also part of the problem. If we now create a `drilldown` event for treemaps and sunburst, it will be not be the same as for other series. Also confusing for the user would be that configuration of the drilldown is not the same. The word is the same, but all the API options are different. That's confusing.

On top of all, you can also use the drilldown module with tree maps:
https://jsfiddle.net/highcharts/xbs2fuon/2/. And you can probably even combine this with the `drillToNode` feature...

**Comment by sebastianbochan** [comment]
Its trickier than I expected.

At this moment I absolutely agree that we need to recognize two options to avoid param-conflict (drilldown module and "workaround" for sunburst and treemap).

Some ideas (only for further disciss):
- downLevel / upLevel
- showChildren / upParent
- nodeChildren / nodeParent
- leafsDown / leafsUp
- downPoints / upPoints

**Comment by KacperMadej** [comment]
Just adding more suggestions:
* `digIn` / `digOut`
* `peekIn` / `peekOut`

**Comment by jon-a-nygaard** [comment]
I agree that the names `drillToNode` and `drillUp` is misconceiving and that we should rename them.

My belief is that something like `setRootNode` and `stepUpTree`/`traverseUpTree`/`setRootNodeToParent` would make sense, also across other tree structure series.

We could add events for when these two functions are called, when the button is called, and events for when the tree is traversed up or down.
I am though uncertain about the usefulness of the traverse up/down events as this could also be achieved in `setRootNode` by looking at level property on the old and new root.

**Comment by sebastianbochan** [comment]
In my opinion will be better to use:

- stepUpTree / stepDownTree
- traverseUpTree / traverseDownTree

In both cases it sounds more intuitively.

What do you think @TorsteinHonsi @KacperMadej @jon-a-nygaard  ?

**Comment by jon-a-nygaard** [comment]
Had a quick chat with @TorsteinHonsi about this and he suggested that we could consider a pattern similar to [`setExtremes`](https://api.highcharts.com/highcharts/xAxis.events.setExtremes) where the event contains information about the trigger.

Then for example we could have `setRootNode` and in this event we could check if it was triggered by the "drillUp?" button. This would avoid the need for a seperate event for the button.

When it comes to step up/down or traverse up/down what basically happens in both these cases is that there is a change of root node for the tree so this would also be covered by the same event.

What do you guys think about this? @KacperMadej @sebastianbochan

**Comment by TorsteinHonsi** [comment]
In addition, we would make the actual drill action the default action of the `setRootNode` event, which allows users to cancel the drill conditionally after the button (or a node) has been clicked.
