### ISSUE TITLE
Sankey chart does not render correctly with specific data, but ok after resize

### ISSUE THREAD

**Issue by Trivette1** [highcharts/highcharts#9818]
#### Expected behaviour
sankey chart get rendered correctly

#### Actual behaviour
sankey chart does something like "line breaks" 

![highcharts-sankey-diagra](https://user-images.githubusercontent.com/31986846/50771500-198dfa80-128b-11e9-9456-0704511c4c17.jpeg)

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/sankey-diagram/

-> replace series.data with following data:
 [480, 481, 1],
[481, 482, 1],
[472, 477, 1],
[481, 474, 1],
[1, 472, 1],
[472, 473, 1],
[474, 475, 1],
[475, 476, 1],
[477, 478, 1],
[478, 479, 1],
[479, 480, 1]

#### Product version

Highcharts v6.2.6

#### Affected browser(s)
Chrome, Firefox

**Comment by Trivette1** [comment]
Thanks for the fast reply.
The jsfiddle above has the same problem. If you load the page, there are two root nodes displayed. (480 and 1).
But in the data, the 1 is the only root node and the 480 node has to be connected to 479 node.
After resizing, the chart gets displayed correctly.

**Comment by pawelfus** [comment]
Thanks @Trivette1 for the details!

It looks like order of points does matter, compare:
- unordered data: https://jsfiddle.net/BlackLabel/4y1c92me/
```
data: [
  [480, 481, 1],
  [481, 482, 1],
  [1, 472, 1],
  [472, 477, 1],
  [481, 474, 1],
  [472, 473, 1],
  [474, 475, 1],
  [475, 476, 1],
  [477, 478, 1],
  [478, 479, 1],
  [479, 480, 1]
],
```
- tree-like ordered data: https://jsfiddle.net/BlackLabel/q8xtwdme/
```
data: [
  [1, 472, 1],
  [472, 473, 1],
  [472, 477, 1],
  [477, 478, 1],
  [478, 479, 1],
  [479, 480, 1],
  [480, 481, 1],
  [481, 482, 1],
  [481, 474, 1],
  [474, 475, 1],
  [475, 476, 1]
],
```

**Comment by Trivette1** [comment]
Hi,
I tested the sankey with the sorted data array and the solution looks good. But it is not working all the time.
With the following data the bug occurs again.
[1, 573, 1],
[573, 574, 1],
[573, 577, 1],
[574, 586, 1],
[575, 585, 1],
[575, 596, 1],
[577, 575, 1],
[578, 582, 1],
[582, 609, 1],
[582, 606, 1],
[584, 578, 1],
[596, 584, 1],
[606, 607, 1],
[607, 608, 1]

Any other ideas?

**Comment by KacperMadej** [comment]
@Trivette1 
Please check the chart that is rendered after resize. As a workaround `chart.setSize` could be simulated through chart's callback function when setSize is called just to redraw the chart. Demo: https://jsfiddle.net/BlackLabel/q8xtwdme/4/

**Comment by Trivette1** [comment]
Hi  KacperMadej ,
this workaround seems to fix the bug. I will test more and post the result.
Thanks for support

**Comment by TorsteinHonsi** [comment]
It's fixed now, tested with the two demo data sets provided. Unfortunateyl github.highcharts.com currently has a build issue so I can't demonstrate it, but once it is up this fiddle should work: http://jsfiddle.net/highcharts/g95nc6uf/3/

This is how the OP demo data looks with the fix applied:
![skjermbilde 2019-01-09 kl 16 10 05](https://user-images.githubusercontent.com/227836/50908016-192b6600-1429-11e9-8a81-245f46cf08f7.png)

**Comment by stuffisthings** [comment]
@TorsteinHonsi 
Hi Torstein,
The fix for this in 7.02 has had some weird effects on one our Sankey charts in production. The chart in question should look like this:

![sankey701](https://user-images.githubusercontent.com/6656179/51672428-ba8aee00-1fcb-11e9-83e4-38532b8bc882.PNG)

But currently renders like this:

![sankey702](https://user-images.githubusercontent.com/6656179/51672441-c37bbf80-1fcb-11e9-8769-ad96f2328cf7.PNG)

Reverting the Sankey module to 7.01 fixes the problem so I assume this issue is the culprit.

This chart updates with new data when a country is selected from a select control, with the series assembled dynamically from two objects. First a nodes array that looks like this:

`var nodeColors = [
  // Manufacturing colors
  {
    id: 'Manufacturing',
    color: defaultChartOptions.colors[2]
  },
  {
    id: 'Wood',
    color: defaultChartOptions.colors[2]
  },
  {
    id: 'Basic metals',
    color: defaultChartOptions.colors[2]
  },
  {
    id: 'Non-metallic minerals',
    color: defaultChartOptions.colors[2]
  },
  ...`
 
 And second a data object that looks like this:
 
 `var sankeyData = {
  'IEA': [
    ['Manufacturing', 'Basic metals', 7541],
    ['Manufacturing', 'Chemicals', 6089],
    ['Manufacturing', 'Paper', 3853],
    ['Manufacturing', 'Food', 2981],
    ['Manufacturing', 'Non-metallic minerals', 2687],
    ['Manufacturing', 'Other manufacturing', 6049],
    ['Transport', 'Passenger road', 28048],
    ['Transport', 'Freight road', 11866],
    ['Transport', 'Rail', 1016],
    ['Transport', 'Air and water', 4020],
    ['Residential', 'Space heating', 12652],
    ['Residential', 'Lighting and appliances', 5957],
    ['Residential', 'Water heating', 4272],
    ['Residential', 'Cooking', 1151],
    ['Residential', 'Space cooling', 931],
    ['Residential', 'Other residential', 439],
    ['Services', 'All services', 18172]
  ],
  ...`
  
  Which are updated on the chart like so:
  
  `sankeyChart.update({
    series: [{
      keys: [
        'from',
        'to',
        'weight',
        'color'
      ],
      data: sankeyData[country],
      nodes: nodeColors,
      name: country
    }]
  });`
  
  In both the node array and the data array, data is in the desired order.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! However I'm not able to reproduce it with the provided data. `sankeyData[country]` is missing so I don't know what data to update to. Can you edit this fiddle to reproduce the error? http://jsfiddle.net/highcharts/skwfqco1/

**Comment by stuffisthings** [comment]
Thanks @TorsteinHonsi -- perhaps I overcomplicated the issue, as your fiddle actually shows the problem already (I wasn't sure if the order of the items should be based on series.nodes or series.data; updating doesn't seem to be part of the problem either).

If you change the sankey module import to 7.0.1 you can see that the flows are grouped from top to bottom according to their order in the series.data array, compared to the "jumbled" grouping you see in the fiddle now.

**Comment by KacperMadej** [comment]
I'm unable to recreate the problem Chrome/Win10, Firefox64.0.2/Win10 using the last shared demo in this thread - data is sorted the same way as in 7.0.1 (the same order as in options).

Please let us know about the browser and OS you are using to see the problem, @stuffisthings

**Comment by TorsteinHonsi** [comment]
Same here. This is what it looks like in Chrome/Mac, also tested on Firefox/Mac, Safari, Edge and IE11:
![skjermbilde 2019-01-28 kl 14 46 35](https://user-images.githubusercontent.com/227836/51840144-96047e00-230b-11e9-83d4-f049d54dc8b2.png)

**Comment by stuffisthings** [comment]
![image](https://user-images.githubusercontent.com/6656179/51898600-8c355600-23b1-11e9-9612-9082e9aaaaf5.png)

This is what it looks like in Chrome 68.0.3440.106 on Windows 10 Enterprise. It seems that is several versions behind the latest stable release -- sorry, I didn't even think to check that as a potential issue.

It does sort correctly in IE and Firefox for me.

**Comment by KacperMadej** [comment]
I'm unable to downgrade to check this right now. I'll try to check this later today.

@stuffisthings  Do you need this to work on Chrome v68 or have you just forgotten to update Chrome?

**Comment by stuffisthings** [comment]
@KacperMadej No, given that Chrome 68 seems to be < 0.25% of market share right now I don't see any strong need to support it. Apparently our IT department has blocked the Chrome update service so thoroughly that it wasn't even warning me about being out of date (for what reason, I have no idea). Sorry for the confusion!

**Comment by TorsteinHonsi** [comment]
I was able to reproduce it on BrowserStack. It's a case when we need to use [stableSort](https://api.highcharts.com/class-reference/Highcharts#.stableSort).

The good news is that from Chrome v70 object sorting behaves as expected, so in time we may be able to remove the `stableSort` function.

Demo with the fix applied: http://jsfiddle.net/highcharts/skwfqco1/4/

**Comment by jainez** [comment]
Hi, I'm having the same problem when rendering a Sankey chart. Some lines are broken and after resizing, the graphic is displayed correctly.
Product version
Highcharts JS v8.0.0 (2019-12-10)

Browser
Chrome 79.0.3945.130

Using the same Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/sankey-diagram/

-> replace series.data with following data:
['C', 'A', 1039] ,
['GBLSA', 'A', 28755] ,
['GBLSA', 'COST', 29847] ,
['GBLSA', 'GBLSRL', 65084] ,
['GBLSA', 'PHIL', 7000] ,
['GBLSA', 'PHILF', 16415] ,
['GBLSRL', '(*) GBLSRL', 20876] ,
['GBLSRL', 'A', 39008] ,
['GBLSRL', 'GBLBE', 985] ,
['HEIN', 'A', 1402] ,
['OPTI', 'A', 15400] ,
['TEC', 'A', 60336] ,
['TUR', 'A', 32040]

When is loaded:
![Sankey Graph](https://user-images.githubusercontent.com/60517314/73557502-4aede100-441f-11ea-91f3-7a8864a7b19c.PNG)

After resizing:
![image](https://user-images.githubusercontent.com/60517314/73559601-580ccf00-4423-11ea-916c-8fdd1356e7dd.png)
