### ISSUE TITLE
Boost - wrong z-index series order

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#9819]
#### Expected behaviour
The scatter series should be on top, as in the case without boost module: https://jsfiddle.net/BlackLabel/wt70h6bk/

#### Live demo with steps to reproduce

https://jsfiddle.net/BlackLabel/8sha2quo/

#### Product version
Highcharts 7.0.1

#### Affected browser(s)
All

**Comment by chuasteve** [comment]
Yes, I met the same problem when i'm using boost.js and the scatter will be hidden under heatmap.

WITHOUT boost.js 
https://jsfiddle.net/chuasteve/ogwv9yxm/

WITH boost.js 
https://jsfiddle.net/chuasteve/0gas59xt/1/

**Comment by sebastianbochan** [comment]
Hi @chuasteve,
As a workaround you can set a negative `z-index` on non-boosted series.

```
chart.series[0].group.attr({
   zIndex: -1
});
```

**Demo:**
- https://jsfiddle.net/BlackLabel/xdbh9zjf/

FYI @cvasseng

**Comment by chuasteve** [comment]
Thanks, finally I can generate huge data with boost.js

![image](https://user-images.githubusercontent.com/46465253/50939561-55f26e00-14b8-11e9-8875-9b0d57f8aa11.png)

**Comment by Cat1007** [comment]
same problem

**Comment by cheezbuggah** [comment]
Currently running into the same issue for months already. The workaround is valid, yes, until the chart is zoomed while in boost mode, which switches the renderer back to the non-boosted renderer. This flips the Z index once more, invalidating the workaround. Would it be possible to fix this issue? 

**Product version:**
Highcharts: 11.1.0
