### ISSUE TITLE
indicators are not updated on dragDrop

### ISSUE THREAD

**Issue by calhamdower** [highcharts/highcharts#9822]
#### Expected behaviour
On dragDrop of value indicators should be updated...

#### Actual behaviour
indicators are not updated on dragDrop

#### Live demo with steps to reproduce
http://jsfiddle.net/hwao6nrd/

#### Product version
Highstock 7.0.1

#### Affected browser(s)
All

This is similar to #8572 which is now closed but seems not released in 7.0.1
That fix may fix this issue.

**Comment by pawelfus** [comment]
Hi @calhamdower 

Thank you for reporting the issue! 

*Internal note:*
It looks like `draggable-points` plugin does not fire `updateData` event. This way, indicator has no information that values should be  recalculated. Firing event manually works for a simple datasets: http://jsfiddle.net/BlackLabel/092Lxvzk/ but not for the OP's demo: http://jsfiddle.net/BlackLabel/95sgfo1n/ (or does it?)
