### ISSUE TITLE
Draggable points per point not reflected in functionality (drop function still executed)

### ISSUE THREAD

**Issue by calhamdower** [highcharts/highcharts#9823]
#### Expected behaviour
When an individual point (singular axis) drag is set to false the drop event is not fired as it is not draggable in any direction. 

correct function is seen when BOTH draggableX and draggableY are set false on a point

#### Actual behaviour
When an individual point  (singular axis) drag is set to false, the point is correctly not draggable; however 
the drop event is still fired. 

#### Live demo with steps to reproduce
http://jsfiddle.net/f189tuxm/

#### Product version
Highchart 7.0.1

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Hi @calhamdower 

Thanks, but your demo (http://jsfiddle.net/f189tuxm/) looks fine: first point in Series 3 (green line) is not draggable and drop event is not fired.

**Comment by calhamdower** [comment]
Whoops, thats because i set BOTH the draggableX and Y on the point.
Try the first point on the line series here. where the draggableX is disabled globally and the draggableY is disabled per point. The drop function is still executed even though the point is not draggable in any direction. 
http://jsfiddle.net/32fxkz4q/
