### ISSUE TITLE
staticScale not working with dynamic data

### ISSUE THREAD

**Issue by matsomo** [highcharts/highcharts#9824]
#### Expected behaviour
The chart adjusts its height based on the number of rows

#### Actual behaviour
The chart height is set based on the number of rows when it is first rendered and then keeps that height when the data source is changed, pushing the rows together within that height.

I tried calculating the chart height based on a fixed row height, but the y-axis label is pushed down when there's only one row.

(never mind that the chart keeps some of the old rows when switching to fewer rows, this is not a problem with the actual application)

#### Live demo with steps to reproduce
https://stackblitz.com/edit/react-ckcue6

#### Product version
highcharts: 7.0.1
highcharts-react-official: 2.0.0
react: 16.5.0

**Comment by sebastianbochan** [comment]
Hi @matsomo,
Thank you for reporting. Summarising the height of rows should be dynamic, keeping constant size of chart's container.

Please let me know if I understand you properly.

**Comment by matsomo** [comment]
I'm not really sure what would be the best solution, but since the number of rows may vary based on my data, a fixed chart height could become crammed. 
That's why I thought a fixed row height might be better and calculate the chart height based on the number of rows.

**Comment by sebastianbochan** [comment]
**Internal note**

@oysteinmoseng @jon-a-nygaard what do you think about?

**Comment by oysteinmoseng** [comment]
This is what the [staticScale](https://api.highcharts.com/gantt/yAxis.staticScale) option is for.

It does however seem like there is a bug where the chart height is not updated as the data changes. Example: http://jsfiddle.net/m1Lnxcd0.

I'm changing the title of the issue to reflect this.

**Comment by oysteinmoseng** [comment]
@TorsteinHonsi Any insights?
