### ISSUE TITLE
Highstock Range Selector will hide the chart when clicked

### ISSUE THREAD

**Issue by briankpw** [highcharts/highcharts#9830]
#### Expected behaviour
When I click All for second times, it will hide the failure red bar, when I click again, its shown the bar. 

#### Actual behaviour
Its wont been hide

#### Live demo with steps to reproduce

Template: https://stackblitz.com/edit/highchart-routing-oredjp
Demo Video:  https://drive.google.com/file/d/1SLd-Xd5fdIpktF6z1IX8LkS7wAAGUnHH/view

**Comment by KacperMadej** [comment]
Hi @briankpw 

Thank you for reporting about the problem.

It looks like you are using `angular2-highcharts` - this is not an official wrapper. Please create a minimal demo that is done in pure JS, or use official wrapper in Angular and post the problem on the highcharts-angular repository, or contact support to help you with the issue.
https://www.highcharts.com/blog/support/

For bug report on github we'll need a minimal demo, but for a technical support case the demo you have would be a good enough starting point.

**Comment by briankpw** [comment]
Hi @KacperMadej 

Thanks for your replying and helping us solving the problem. 

I am switching to highcharts-angular, the problem still exist
Demo: https://stackblitz.com/edit/highchart-angular

**Comment by KacperMadej** [comment]
Thank you for the demo. Here's the problem recreated without Angular - so this is a Highstock general bug.
https://jsfiddle.net/BlackLabel/qb50z2dv/

**Comment by briankpw** [comment]
Thanks Kacper, 
It's works now

**Comment by KacperMadej** [comment]
Great to hear that the temporary workaround is successful, but the bug is not resolved yet - files loading order shouldn't be forced. Reopening.
