### ISSUE TITLE
Bar chart data are not displayed when i set yAxis labels rotation to 180

### ISSUE THREAD

**Issue by ZdenekVidensky** [highcharts/highcharts#9835]
#### Expected behaviour
All axis labels should be rotated for 180 degrees and displayed correctly.

#### Actual behaviour
Only min and max axis labels are displayed (without formatting) and data in bar chart are not displayed

#### Live demo with steps to reproduce
https://jsfiddle.net/skjL1wxc/2

#### Product version
Highcharts 4.2.5 (but also happens on JsFiddle)

#### Affected browser
Google Chrome version 71.0.3578.98

**Comment by KacperMadej** [comment]
Hi @ZdenekVidensky 

Thank you for reporting about the problem.
Please explain the use case of such labels.

Here's a workaround - set `step` to `1` for the labels. Demo: https://jsfiddle.net/BlackLabel/2zj0mgt4/

**Comment by ZdenekVidensky** [comment]
Hi @KacperMadej
I don't know exact use case but our customer reported this as a bug of our implementation.
Thank you very much for answer.
