### ISSUE TITLE
Treemap chart drillup button disappear after update the chart 

### ISSUE THREAD

**Issue by euiRulz** [highcharts/highcharts#9838]
#### Expected behaviour
If a treemap chart has updated in the drilled down state, drill up button should remain the same.
#### Actual behaviour

I was trying to update a property in a treemap chart on a button click. If the chart is in drilled down status the drill up button will disappear from the chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/nvom2u13/

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @euiRulz 

Thank you for reporting about the problem.

**Workaround:** 
Preserve the button before update and reapply on the series after the update. Demo: https://jsfiddle.net/BlackLabel/tg7uzh8r/

_Internal note:_
Series update is not flexible enough to easily add new members to be preserved, so this could be resolved first. If we had not only `afterUpdate`, but also `beforeUpdate` then this could be resolved without changes in general Series. Third option is to provide `update` function for the series type, so this will be a wrapper without the usage of the `H.wrap`.
