### ISSUE TITLE
FlagSeries cannot place on different yAxis when used multiple Axis

### ISSUE THREAD

**Issue by Micha0827** [highcharts/highcharts#9839]
#### Expected behaviour
Flag Series can be placed on diifferent yAxis with yAxis param

#### Actual behaviour
Flag Series can be placed ONLY on LAST yAxis

#### Live demo with steps to reproduce
http://jsfiddle.net/hreoa1x6/

#### Product version
actual highstock Version from https://code.highcharts.com/stock/highstock.js

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @Micha0827 

Thank you for contacting us.

Flags are placed on xAxis as explained in docs here: https://api.highcharts.com/highstock/series.flags.onSeries
Use the `onSeries` to place not on xAxis or set a different xAxis - demo: http://jsfiddle.net/BlackLabel/5huqwkj4/

**Comment by Micha0827** [comment]
Hello,
your Answer not help. I know how i can place flag on other series. But i would place on first from multiple (5) YAxis, NOT XAxis. This Abswer i received from Helpdesk today:

Hi Michael,

I am not sure what exactly causing this but it is somehow related to yAxis height. If you link the flags series to the most bottom yAxis (Verk?e), the flag will appear. If you want to, you can report it as a bug here: https://github.com/highcharts/highcharts/issues.

API Reference:
https://api.highcharts.com/highstock/series.flags.yAxis

Example:
http://jsfiddle.net/hreoa1x6/

**Comment by KacperMadej** [comment]
Flags are placed on xAxis and clipped when assigned to yAxis that doesn't share it's pane with the used xAxis. Set `clip` to false to show the flags - http://jsfiddle.net/BlackLabel/w6hfz4ts/
or add y value to a flag point - http://jsfiddle.net/BlackLabel/w6hfz4ts/2/

**Comment by TorsteinHonsi** [comment]
Simplified demo: http://jsfiddle.net/highcharts/y2095Lrh/

**Comment by TorsteinHonsi** [comment]
Thanks for reporting @Micha0827, we agree this is a bug, and have provided a fix. It will be fixed with the next release.

* Simplified demo with the fix applied: http://jsfiddle.net/highcharts/y2095Lrh/8/
* OP demo with the fix applied, modified to place the flag on the first Y axis: http://jsfiddle.net/highcharts/y9b2Lg75/

**Comment by TorsteinHonsi** [comment]
Fixed by https://github.com/highcharts/highcharts/commit/a8def2332f149e2a2d01519c8322b70f9a13f21d
