### ISSUE TITLE
Treemap render issue on legend toggle

### ISSUE THREAD

**Issue by BaarishRain** [highcharts/highcharts#9842]
#### Expected behaviour
I created the below treemap with legends.
![image](https://user-images.githubusercontent.com/13344028/50892247-0d897080-1424-11e9-9fed-e087591c3e84.png)

Expected: On legend toggle, treemap should be rendered properly.

#### Actual behaviour

You will observe that treemap is not rendered correctly. Check below image. 
![image](https://user-images.githubusercontent.com/13344028/50892316-3578d400-1424-11e9-8976-975fd8fb09fb.png)

On mouse hover over the chart now, it's corrected.
![image](https://user-images.githubusercontent.com/13344028/50892606-f13a0380-1424-11e9-87b5-0244bf866e1d.png)

This happens only with firefox 64.0 and not on chrome 63.0.3239.108. 

#### Live demo with steps to reproduce
http://jsfiddle.net/patn5xhf/6/

#### Affected browser(s)
Firefox 64.0

**Comment by sebastianbochan** [comment]
Hi @BaarishRain,
The Firefox v64 has a bug with correct rendering SVG. Probably the same as #9745, we are waiting for response from Mozilla.

Official report to Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1517458
