### ISSUE TITLE
[iOS] Highstock - segment edition on touch devices

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#9847]
[iOS system - touch devices]
After drawing a line and making a double click on it, the edition window is activated, but there is no possibility to click on any of the buttons. 

#### Live demo with steps to reproduce

[Highcharts demo](https://www.highcharts.com/stock/demo/stock-tools-custom-gui)

#### Product version

Highstock 7.0.1

**Comment by KacperMadej** [comment]
btw: the demo on highcharts.com have unwanted left margin for lists elements shown on hover over the bigger GUI buttons. The problem is not in JSFiddle demo as the unwanted CSS is not loaded there.

**Comment by sebastianbochan** [comment]
@KacperMadej I see, but its related with some global CSS styles applied by the highcharts.com website. In the jsfiddle all is displayed properly.
