### ISSUE TITLE
lineHeight of xAxis labels is calculated incorrectly if xAxis.labels.style.fontSize is set in rem

### ISSUE THREAD

**Issue by jakub-noga-antsolutions** [highcharts/highcharts#9849]
#### Expected behaviour
LineHeights of xAxis labels should not depend on unit used for xAxis.labels.style.fontSize
#### Actual behaviour
LineHeight is different if xAxis.labels.style.fontSize is set in rem AND font-size for html element is different than 12px (i.e. 62.5%)

#### Live demo with steps to reproduce
http://jsfiddle.net/jakub_noga_antsolutions/ywbz3o8x/2/

#### Product version
Highstock 7.0.1

#### Affected browser(s)
All supported by Highcharts

**Comment by sebastianbochan** [comment]
Hi @jakub-noga-antsolutions,
Thank you for reporting. You should set the `labels.useHTML` flag as true.

**Demo:**
- http://jsfiddle.net/BlackLabel/dbhrfsc6/

**Internal note**
@TorsteinHonsi  Should we consider it as a bug?

**Comment by jakub-noga-antsolutions** [comment]
Hi @sebastianbochan  thanks for response.
Unfortunately setting `labels.useHTML` to true also changes default white-space to nowrap, at least in our case, but I am not able to reproduce this behaviour on jsFiddle.

I found out that `fontMetrics: function (fontSize, elem)` treats 'rem' same as 'em'. It checks elements' parent for fontSize and eventually falls back to 16px. Maybe you could change this to proper behaviour?

**Comment by TorsteinHonsi** [comment]
We already have better font size detection for styled mode, so we should probably use that for everything that is not `px`. @jakub-noga-antsolutions How does this work for you? http://jsfiddle.net/highcharts/vx6g74n9/

**Comment by jakub-noga-antsolutions** [comment]
@TorsteinHonsi Your solution works well for us.
