### ISSUE TITLE
Type definition bug for positioner() method

### ISSUE THREAD

**Issue by karolinakuzniewicz** [highcharts/highcharts#9852]
#### Expected behaviour
Type definition should be `positioner?(labelWidth: number, labelHeight: number, point: PlotPoint): { x: number; y: number; };` instead of `positioner?: () => void;` in `highcharts.d.ts` file.

#### Product version
Highcharts v7.0.1

**Comment by bre1470** [comment]
Thank you for the feedback! This is probably a simple fix.
