### ISSUE TITLE
H.syncTimeout: context doesn't work on async

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#9855]
#### Expected behaviour
Support for `context` in `setTimeout` as docs say.

#### Actual behaviour
Used only for synchronous function call, because `setTimeout` [doesn't support such argument](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#The_this_problem).

#### Live demo with steps to reproduce
https://github.com/highcharts/highcharts/blob/abc4bc01baf1f5c777b50943ed58f81acfc0b228/js/parts/Utilities.js#L1119-L1143

#### Product version
7.0.1

**Comment by TorsteinHonsi** [comment]
Should we fix it or remove it? Do we use it for anything?

**Comment by TorsteinHonsi** [comment]
Actually neither the docs or the issue are accurate. The third parameter is not passed as the context, neither in sync or async mode. Instead, it is passed as the argument to the handler function:

http://jsfiddle.net/highcharts/LLExL/13634/

**Comment by KacperMadej** [comment]
> Should we fix it or remove it? Do we use it for anything?

I found this while working with other part of code, but in core's code the `context` (now `parameter`) argument was never used anyway.

Current implementation is not fully in line with multiple parameters (e.g. `var timeoutID = scope.setTimeout(function[, delay, param1, param2, ...]);`), but Highcharts docs are now accurate and as far as I'm concerned this issue could be closed.
