### ISSUE TITLE
offline-exporting not working

### ISSUE THREAD

**Issue by bonesoul** [highcharts/highcharts#9862]
I'm using highstock with a relatively large data set and https://export.highcharts.com/ gives "413 Request Entity Too Large" error.

Decided to give offline-exporting module a try but it somehow doesn't work.

here is my setup;

```
let Highcharts = require('highcharts/highstock.js');

// modules
require('highcharts/modules/boost-canvas.js')(Highcharts); // add webgl module support.
require('highcharts/modules/boost.js')(Highcharts); // add boost module support.
require('highcharts/modules/exporting.js')(Highcharts); // allow exporting.
require('highcharts/modules/offline-exporting.js')(Highcharts); // allow offline exporting.

// themes
require('./themes/simple-transparent.js')(Highcharts);

window.Highcharts = Highcharts;

```

#### Product version
    "highcharts": "7.0.1",

**Comment by KacperMadej** [comment]
Hi @bonesoul 

Thank you for reporting about the problem. 

Please elaborate about "but it somehow doesn't work" - do you have console (developer tools) errors when files are loaded or chart is created? are you getting any errors when trying to export offline? what browser have you used to recreate the problem? could you create a live demo or a way to recreate the problem?

**Comment by bonesoul** [comment]
i'm getting '413 Request Entity Too Large' error from the https://export.highcharts.com/.

Although i've included offline-exporting module, it still uses the online exporting?

**Comment by sebastianbochan** [comment]
Hi @bonesoul,
Please let me know about OS and browser you have (including full number of version).

**Comment by bonesoul** [comment]
found the error, was not related to highcharts.

`Access to image at 'https://cdn.hypetra.in/assets/images/logo/logo.png' from origin 'https://localhost:4443' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Was trying to access a watermark image without a proper CORS policy.

thanks for your response.

**Comment by KacperMadej** [comment]
Just in case anyone else would happen to have a similar issue about error 28.
Please check browser support table in docs to be sure that a file format and a browser are supported.
https://www.highcharts.com/docs/export-module/client-side-export
