### ISSUE TITLE
Type Series is not assignable to type SeriesZigzagOptions

### ISSUE THREAD

**Issue by olivierscheffler** [highcharts/highcharts#9867]
#### Expected behaviour
With version 6.2.0 on an project Angular versoin 6.0.3 i  was able to define my charts this way :
`
    Highcharts.chart('container', {
      chart: {
        type: 'column'
      },
      title: {
        text: 'Nombre de demande par processus par année'
      },
      exporting: {
        enabled: false
      },
      xAxis: {
        categories: ["2016", "2017", "2018", "2019"]
      },
      yAxis: {
        min: 0,
        title: {
          text: 'Nombre de demande'
        },
        stackLabels: {
          enabled: true,
          style: {
            fontWeight: 'bold'
          }
        }
      },
      legend: {
        align: 'left',
        x: 45,
        verticalAlign: 'top',
        backgroundColor: 'white',
        borderColor: '#CCC',
        borderWidth: 1,
        shadow: false
      },
      tooltip: {
        headerFormat: '<b>{point.x}</b><br/>',
        pointFormat: '{series.name}: {point.y}<br/><b>Total: {point.stackTotal}</b>'
      },
      plotOptions: {
        column: {
          stacking: 'normal',
          dataLabels: {
            enabled: true,
            color: 'white'
          }
        }
      },
      series: [{
        name: 'MADC',
        data: [0, 10, 60, 150],
        color: '#52A233'
      }, {
        name: 'NA',
        data: [652, 906, 1696, 1500],
        color: '#218290'
      }, {
        name: 'Alice',
        data: [874, 1300, 1986, 2355],
        color: '#0A4170'
      }]
    });
`

#### Actual behaviour
With version 7.0.1 of Highcharts and version 7.1.0 of Angular i am able to define the Highcharts the same way.
I have an error saying that the definition of series is not correct : 
Type is not assignable to type SeriesZigzagOptions.

#### Product version
Highcharts version 7.0.1
Angular version 7.0.1

#### Affected browser(s)
All browsers

**Comment by KacperMadej** [comment]
Hi @olivierscheffler 

Thank you for reporting about the problem.

Please provide info about the line where the error is point you to.
There's no zig zag series reference in the shared code, so also please provide info about loaded Highcharts modules.
If would be for the best if you could create a live demo or provide a way to recreate the problem.

**Comment by olivierscheffler** [comment]
HI @KacperMadej , thanks for your answer..
In fact, after review my code, this is an error only in VsCode...
I can see this error on the section series :
`
[ts]
Type '{ name: string; data: number[]; color: string; }' is not assignable to type 'SeriesAbandsOptions | SeriesAdOptions | SeriesAoOptions | SeriesApoOptions | SeriesAreaOptions | SeriesArearangeOptions | SeriesAreasplineOptions | SeriesAreasplinerangeOptions | ... 82 more ... | SeriesZigzagOptions'.
  Property 'type' is missing in type '{ name: string; data: number[]; color: string; }' but required in type 'SeriesXrangeOptions'. [2322]
highcharts.d.ts(335083, 5): 'type' is declared here.
`
I have no error during compilation.. The way I find to remove this error on my editor is to add for each series type: 'column' and everything work fine..

I don't know why VsCode react like that...

**Comment by KacperMadej** [comment]
@olivierscheffler 

> ... Property 'type' is missing ...

Each series options object needs to have defined type, (e.g. `type: 'column'`) or set TS type (`... } as Highcharts.SeriesColumnOptions`).

@bre1470 Is this explained in any docs? and if not, maybe it could be added?

**Comment by olivierscheffler** [comment]
@KacperMadej  yeah it took me time to see that... Because it's not written on any documentation and in earlier version of Highcharts you didn't need to write this on the series..
Now it's working nice but documentation should be adjust I think !

You said ' or set TS type (... } as Highcharts.SeriesColumnOptions).' what do you mean exactly ?

Thank you !

**Comment by KacperMadej** [comment]
@olivierscheffler 
I was referring to this comment - https://github.com/highcharts/highcharts-declarations-beta/issues/8#issuecomment-436662606

**Comment by bre1470** [comment]
@KacperMadej 
It is mentioned in the declarations, but maybe not in the right spot. Additionally we should consider adding TypeScript information to the API documentation. What do you think?

**Comment by KacperMadej** [comment]
It would be nice to have this mentioned somewhere in general docs - https://www.highcharts.com/docs/advanced-chart-features/typescript

Adding the info to the API docs will be useful too IMHO

**Comment by sudhirkaushk** [comment]
Whoopsie

![highchart-erro](https://user-images.githubusercontent.com/8871502/66902697-b5207880-f01e-11e9-8f79-9be2a3db0c23.PNG)

**Comment by sebastianbochan** [comment]
@sudhirkaushk 
Thank you for reporting, will fix that.

Meantime the page is available here: https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-beta

**Comment by bre1470** [comment]
Please use: https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-beta

**Comment by XemaA** [comment]
defining my chart as the following code helped me to resolve this problem !
(Highcharts as any).chart('hourCalls', {
      chart: {
        type: "column"
      },
      series: [
        {
          name: "Calls",
          data: this.hourCalls,
          type: undefined
        }
      ]
});
