### ISSUE TITLE
X-range tooltip anchor moved to the right on reversed xaxis

### ISSUE THREAD

**Issue by grakkpl** [highcharts/highcharts#9869]
#### Expected behaviour
The tooltip is anchored to the selected range

#### Actual behaviour
The tooltip is in random place on the right of the selected range

#### Live demo with steps to reproduce
https://jsfiddle.net/hsvy6rb8/

#### Product version
Latest highcharts

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @grakkpl 

Thank you for reporting about the problem.

Workaround wrapper added in a demo:
https://jsfiddle.net/BlackLabel/2j5pvucy/

_Internal note:_
There's no error. Logic for reversed axis seems to be missing.

**Comment by grakkpl** [comment]
The WA worked like a charm. Thanks, Kacper - keeping the issue open until fix reaches release.
