### ISSUE TITLE
If sankey charts support zoom button and xy zoom?

### ISSUE THREAD

**Issue by hurrine** [highcharts/highcharts#9870]
#### Expected behaviour
Sometimes the series data relationship is complicated. If support zoom?

**Comment by sebastianbochan** [comment]
Hi @hurrine,
The github is our bugtracker, so for general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.

ps. The sankey series does not use the cartesian's axis (like x/y axis) and at this moment the zoom option is not available.
