### ISSUE TITLE
Display issues on Firefox with Highmaps state hovering

### ISSUE THREAD

**Issue by Mania-1024** [highcharts/highcharts#9875]
#### Expected behaviour
When I hover my mouse on a state, the state should be entirely filled with the hovering color.

#### Actual behaviour
In some cases, on Firefox, a hovered state will not completely be filled with the hovering color.
In some other cases, still on Firefox, a hovered state will not completely return to its original color and a fraction of it will keep the hovering color.
It seems only states near the border of a map are affected.

![image](https://user-images.githubusercontent.com/38459514/51170506-ea8d0f80-18ae-11e9-9e28-be0a10dcdc0f.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/geojson/
This is the basic demo from the official website. The states "SH" and "MV" are affected (horizontal divide) as well as "RP" and "NW" (vertical divide).

#### Product version
In my project, I use Highcharts 6.1.2

#### Affected browser(s)
Firefox (my version is 64.0.2 (64 bits))

**Comment by sebastianbochan** [comment]
Hi @HolgerCarlsen,
The Firefox v64 has a bug with correct rendering SVG. Probably the same as #9745, we are waiting for response from Mozilla.

Official report to Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1517458

**Comment by HolgerCarlsen** [comment]
Thanks for your response ! Let's hope Mozilla will correct this soon then =)
