### ISSUE TITLE
Shared tooltip points skipped on large datasets

### ISSUE THREAD

**Issue by Gunner17** [highcharts/highcharts#9876]
When I am rendering a 'spline' or even 'areaspline' chart with 4 series and 2500+ data points, I see that the chart tooltip(custom formatted) skips 1 or 2 data points when I carefully hover from left to right. For example, if I have data for March 31st in a point, the next point should show 1st April on hovering from the previous point, but instead, it skips the 1st April and goes directly to 2nd April. Is that a known bug? Or, am I missing something?

**Comment by sebastianbochan** [comment]
Hi @Gunner17,
Thank you for reporting. 

Could you update this demo:  https://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/boost/scatter with your data and chart's options? It will allow us to check your configuration and debug.

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
