### ISSUE TITLE
Type definitions: ExportingButtonsContextButtonOptions.menuItems is incorrect

### ISSUE THREAD

**Issue by oBusk** [highcharts/highcharts#9878]
#### Expected behaviour

```ts
/** string[] |  MenuItem[] */
const menuItems = Highcharts.getOptions().exporting.buttons.contextButton.menuItems;
```

Where `MenuItem` is 

```ts
interface MenuItem {
    /**
     * The click handler for the menu item
     */
    onclick(): void;
    /**
     * The text for the menu item 
     */
    text: string;
    /** 
     * If internationalization is required, the key to a language string 
     */
    textKey?: string;
}
```

#### Actual behaviour

```ts
/** string[] */
const menuItems = Highcharts.getOptions().exporting.buttons.contextButton.menuItems;
```

#### Live demo with steps to reproduce

So getting menuItems returns an array of strings which is incorrect as far as I can gather from:

https://github.com/highcharts/highcharts/blob/f4210c9229c4b5459dfb3bf770bcaa48cac6ab92/js/modules/exporting.src.js#L810-L833

EDIT: To clarify, I understand that the original values are all `string`s, but it is possible to modify the value of the array to add custom exports.

This was a break for us moving from `highcharts@5` with `@types/highcharts@5` which has the following typing:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/945fd1a38258b551241eba913701b313c28b7884/types/highcharts/index.d.ts#L2587-L2596

#### Product version

`highcharts@7.0.1`

#### Affected browser(s)

N/a

**Comment by sebastianbochan** [comment]
Hi @oBusk,
Thank you for reporting.

FYI @bre1470

**Comment by bre1470** [comment]
Favorited way since v5.0.13 is to set button definitions in `exporting.menuItemDefinitions` (Dictionary of MenuItems) and reference the keys in `exporting.buttons.contextButton.menuItems`.
