### ISSUE TITLE
Highcharts.StockChart tooltip issue with column charts

### ISSUE THREAD

**Issue by Madhu94** [highcharts/highcharts#9883]
#### Expected behaviour
Column chart's tooltip shows the time given in datapoints

#### Actual behaviour
The "time" part of UTC timestamp isn't shown in tooltip if chart's SVG area is small - I've set container width to 700px in the example, increasing the width above 750 should rectify behavior

#### Live demo with steps to reproduce
http://jsfiddle.net/8vwyjenp/5/

#### Product version
Highstock 6.0.3

#### Affected browser(s)
Tested in Firefox and Chrome

**Comment by KacperMadej** [comment]
Hi @Madhu94 

Thank you for contacting us, but this is not a bug.

If you are unsure if a case is a bug (this case is not) you could always contact support first to confirm - https://www.highcharts.com/blog/support/

You are using custom tooltip formatter that returns not formatted x value of a point (date in timestamp time format). See how format could be set in API reference: https://api.highcharts.com/class-reference/Highcharts#.dateFormat

**Comment by Madhu94** [comment]
@KacperMadej, the tooltip format was not my issue. The issue is that the tooltip shows points that are not in my data - you can see that in the tooltip, the last point's is x value is 1546992000000, but the x value of the last point in my data is 1547010000000

**Comment by KacperMadej** [comment]
@Madhu94 
Right, my bad - sorry about that.
The problem is caused by dataGrouipng - disable it and point will not be grouped. Demo: http://jsfiddle.net/BlackLabel/uskgv0Lb/

Still not a bug, so I'll keep the issue closed.
