### ISSUE TITLE
boost module: enterBoost runs multiple times and original options are lost

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#9884]
#### Expected behaviour
enterBoost runs once or again only after exitBoost run

#### Actual behaviour
enterBoost runs multiple times while exitBoost doesn't run causing original series options to be lost

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/64kuzbs2/
See in console that `alteredByBoost` series array is altered.

#### Product version
7.0.1

**Comment by sebastianbochan** [comment]
FYI @cvasseng
