### ISSUE TITLE
dynamic Chart update not working properly when changing x-axis's type=datetime in place of category.

### ISSUE THREAD

**Issue by gouravgupta92** [highcharts/highcharts#9889]
#### Expected behaviour
Chart should redraw itself with proper x-axis values.

#### Actual behaviour
dynamic Chart update not working properly when changing x-axis's type=datetime in place of category.

This behavior is present when i change the chart options dynamically.
independently chart renders as expected.

I am changing all option values of chart dynamically, which seems to work when x-axis has categories and even if i change categories, add or remove any data.

But when i change x-axis type to datetime and have data as array of object, chart gets distorted.
```
xAxis: {
        categories: ['Apples', 'Oranges', 'Pears', 'Grapes', 'Bananas']
    },
    series: [{
        name: 'John',
        data: [5, 3, 4, 7, 2]
    }, {
        name: 'Jane',
        data: [2, 2, 3, 2, 1]
    }, {
        name: 'Joe',
        data: [3, 4, 4, 2, 5]
    }]
```

to
 
```
xAxis: {
        type: 'datetime',
    },
    series: [{
        name: 'PASS',
        type: 'column',
        data: [{
            x: 1167609600000,
            y: 5
        }, {
            x: 1167696000000,
            y: 10
        }]
    }, {
        name: 'FAIL',
        type: 'column',
        data: [{
            x: 1167609600000,
            y: 10
        }, {
            x: 1167696000000,
            y: 5
        }]
    }]
```
I have created a fiddle for the same.

#### Live demo with steps to reproduce
https://jsfiddle.net/jrv2ah8q/

#### Product version
Highcharts version 7.0.1

**Comment by KacperMadej** [comment]
Hi @gouravgupta92 

Thank you for contacting us about the problem.

When updating chart's elements with new options, old options are not removed, so in this case categories array is still there and is causing chart to act strange. Set categories (axis option) to false on chart update and axis type will be changed. Demo: https://jsfiddle.net/BlackLabel/mqu4b1yv/

Setting categories for an axis will make if act as category type axis, so I'm not seeing a bug here.
Please provide more info in case the issue is not resolved.

**Comment by gouravgupta92** [comment]
Thanks for the response.

Making categories to false seems to work for first time.

But in if you try to change it twice it again gets distorted.

Steps to reproduce in fiddle https://jsfiddle.net/BlackLabel/mqu4b1yv/

Click on :
change date button -> change category button -> change date button -> change category button

**Comment by KacperMadej** [comment]
@gouravgupta92  You have added points with defined x positions that are way our of the few categories indexes, so the chart looks like that. You could update those points with new x values.

**Comment by gouravgupta92** [comment]
Hi @sebastianbochan 
Thanks for reply. But there is a very strange behavior in chart.
in your fiddle https://jsfiddle.net/BlackLabel/zfcdx8q4/ value for series in config1 is
```
series: [{
    name: 'John',
    data: [['aaa',5], ['bbb',3], ['ccc',4], ['ddd',7], ['eee', 2]]
  }, {
    name: 'Jane',
    data: [['aaa',5], ['bbb',3], ['ccc',4], ['ddd',7], ['eee', 2]]
  }, {
    name: 'Joe',
    data: [['aaa',5], ['bbb',3], ['ccc',4], ['ddd',7], ['eee', 2]]
  }]
```

but if you reduce number of x-axis categories to 2 like below
```
series: [{
    name: 'John',
    data: [['aaa',5], ['bbb',3]]
  }, {
    name: 'Jane',
    data: [['aaa',5], ['bbb',3]]
  }, {
    name: 'Joe',
    data: [['aaa',5], ['bbb',3]]
  }]
```
then the graph again gets distorted.

I tried removing x-axis values from series data and putting it in categories property of x-axis then some different issue is coming.

Steps to reproduce:

Change series data -> click on change date -> click on change catagory

Demo:
https://jsfiddle.net/ts9zpfx4/

**Comment by sebastianbochan** [comment]
Hi @gouravgupta92,
It looks like the @KacperMadej 's solution with declared x positions, solves the problem. 

**Demo:**
- https://jsfiddle.net/BlackLabel/4Lnuag5q/

**Comment by sebastianbochan** [comment]
@gouravgupta92 
In the case of using object, you can declare x value by param.

```
  series: [{
    name: 'John',
    data: [{x:0, y: 5, myData : 'mydata'},{x: 1,y: 3, myData : 'mydata'}]
  }, {
    name: 'Jane',
    data: [{x:0, y: 5, myData : 'mydata'},{x:1,y: 3, myData : 'mydata'}]
  }, {
    name: 'Joe',
    data: [{x:0,y: 5, myData : 'mydata'},{x: 1,y: 3, myData : 'mydata'}]
  }]
```

**Demo:**
- https://jsfiddle.net/BlackLabel/xtj0whyz/

**Comment by gouravgupta92** [comment]
@sebastianbochan Thanks, Actually i was using value of x as the name of category ('aaa', 'bbb') but looks like i need to use index for the value of x.

**Comment by gouravgupta92** [comment]
Hi @sebastianbochan 
As you described earlier i tried with making deep copy of config, but i have some event handler function also in options. So deep copy will not work for that.

**Comment by sebastianbochan** [comment]
How about the Kacper's solution? Is seems to work correctly: 
- https://jsfiddle.net/BlackLabel/fd38x41r/

**Comment by KacperMadej** [comment]
Closing as not a bug and due to inactivity.

**Comment by dfenerski** [comment]
I am having an issue with the same problem. Switching between axis types on the fly seems problematic. Also the demo is not OK? Try switching from `category` to `datetime` to `category` ? I am having similar 'tick' problems..

Any clues are appreciated

**Comment by bm64** [comment]
Hello @dfenerski.
I have slightly simplified the demo, but everything seems to work correctly: https://jsfiddle.net/BlackLabel/8n1da0bk/ 
Could you try to recreate the issue?

**Comment by dfenerski** [comment]
Hi @bm64 
The demo works fine as it is, but if you comment out the `allowMutatingData` or set it to true you can observe the bug.
Why is this property essential? It is not mentioned in the `axis` docs

**Comment by dfenerski** [comment]
Thanks for the info @bm64.
Sorry to keep bothering, but I am not sure I get the full picture. What is wrong with the following sample: https://jsfiddle.net/c9jvnfw2/29/ ?
My goal is to not provide hardcoded initial values e.g `allowMutatingData` but add anything on the fly trough the `update` methods when needed. What is the above demo missing in this regard? Could this also work in combination with Highstocks?
Thank you for any info you provide in advance

**Comment by bm64** [comment]
Regarding you demo, please update chart few times and see in console how `categoryData` gets mutated. To avoid something like that you need either to use our `allowMutatingData: false` option, or work on copies of your original data. You can create a copy for example using spread syntax for less complex objects: https://jsfiddle.net/BlackLabel/dk38vyLr/. Creating a copy of more complex nested objects is not that easy though and you need for example a library that is able to create deep copies. 

We use github as a feature request / bug tracker only, so with any futher questions please reach us on our other support channels and someone surely will answer all you questions: https://www.highcharts.com/blog/support/
