### ISSUE TITLE
Item chart / Parliament chart

### ISSUE THREAD

**Issue by htveit** [highcharts/highcharts#9891]
Finish off the work started at https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/studies/item-rows/

 - [x] Organize into a proper module.
 - [x] Test common series operations (checklist - add, update, remove etc.)
 - [x] Add samples. Parliament and rectangular item chart. Chart with symbols (persons). To do: Make it work with the person symbols.
 - [x] API docs.
 - [x] Write docs article.
 - [x] Implement `inactive` state after that feature is merged.

**Comment by TorsteinHonsi** [comment]
Docs article available at https://github.com/highcharts/highcharts/blob/hc71/master/docs/item-series.md
