### ISSUE TITLE
Enhancement suggestion: improve error #17 (missing series)

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#9892]
#### Expected behaviour
Error with more details.

1 . What is the name of the missing series - in console

2 . What file should be loaded to avoid the error - on the error site, as 
**full table with all series and all related required files** visible to a user **or** error site with additional request about the missing series type, so 
**only the relevant info decided through the GET request** will be shown e.g. `https://www.highcharts.com/errors/17/?type=scatter` and an error about possible typo in case no match.

#### Actual behaviour
Error message not precise enough to help resolve the problem.

**Comment by bre1470** [comment]
I believe that this should not be part of the error message. So I am working on improving the documentation. @KacperMadej - Please let me know, if you think this will solve the issue: https://github.com/highcharts/highcharts/pull/12241

**Comment by bre1470** [comment]
Yes, it would help in that situation. I will follow your suggestion, but do it in a separate PR as the require tags are enough changes for their own.

**Comment by sebastianbochan** [comment]
I agree with @kacper, lets increase level of user-friendly
