### ISSUE TITLE
Add full screen capabilities to all charts

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#9895]
We want to add the fullscreening capabilities (or a similar popout) to charts for accessibility and usability purposes.

Assuming we can use fullscreen (which is basically a one-liner), this can be added easily in the exporting menu, alongside the Print option. See stock tools for code details, as there is already a fullscreen option there.

**Comment by oysteinmoseng** [comment]
Closed in #9970

**Comment by TorsteinHonsi** [comment]
It doesn't work in frames, but we get no indication why. In this situation the link should be dimmed (with a ligher color or an opacity), with a `title` tag telling why.

**Comment by sebastianbochan** [comment]
The fullscreen works in the <iframe> when the `allowfullscreen` attribute is set as true.

https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen

**Comment by TorsteinHonsi** [comment]
@sebastianbochan Do you know of a way to find out this before the call, so that we can enable/disable the link at render time?

**Comment by sebastianbochan** [comment]
@TorsteinHonsi @oysteinmoseng 
Only what comes to my mind is refer to iframe and verify the attribute or set it.

```
var i, frames;
frames = document.getElementsByTagName("iframe");
for (i = 0; i < frames.length; ++i)
{
      // The iFrame
    if (!frames[i].hasAttribute("allowfullscreen")) {
        frames[i].setAttribute('allowFullScreen', '') // add or disable menu
    }
}
```
