### ISSUE TITLE
Exception in the plugin price-indicator.js

### ISSUE THREAD

**Issue by javaguru** [highcharts/highcharts#9915]
Exception in the plugin price-indicator.js, place the scrollBar between January and February, active the lastPrice and lastVisiblePrice with the menu button

#### Expected behaviour
No exception

#### Actual behaviour
Exception : Uncaught TypeError: Cannot set property 'y' of undefined
    at r.<anonymous> (price-indicator.src.js:128)

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui/

#### Product version
Last version 7.0.1 

#### Affected browser(s)
All

#### Solution: Tested if serie.lastPrice is undefined
```javascript
// Fix price indicator Save price..
    (function (H) {
        var addEvent = H.addEvent,
            merge = H.merge,
            isArray = H.isArray;

        addEvent(H.Series, 'afterRender', function () {
            var serie = this,
                seriesOptions = serie.options,
                lastVisiblePrice = seriesOptions.lastVisiblePrice,
                lastPrice = seriesOptions.lastPrice;

            if ((lastVisiblePrice || lastPrice) && seriesOptions.id !== 'highcharts-navigator-series') {

                var xAxis = serie.xAxis,
                    yAxis = serie.yAxis,
                    origOptions = yAxis.crosshair,
                    origGraphic = yAxis.cross,
                    origLabel = yAxis.crossLabel,
                    points = serie.points,
                    x = serie.xData[serie.xData.length - 1],
                    y = serie.yData[serie.yData.length - 1],
                    lastPoint,
                    yValue,
                    crop;

                if (lastPrice && lastPrice.enabled) {

                    yAxis.crosshair = yAxis.options.crosshair = seriesOptions.lastPrice;

                    yAxis.cross = serie.lastPrice;
                    yValue = isArray(y) ? y[3] : y;

                    yAxis.drawCrosshair(null, {
                        x: x,
                        y: yValue,
                        plotX: xAxis.toPixels(x, true),
                        plotY: yAxis.toPixels(yValue, true)
                    });

                    // Save price
                    serie.lastPrice = yAxis.cross;
                    if (serie.lastPrice !== undefined)
                        serie.lastPrice.y = yValue;
                }

                if (lastVisiblePrice && lastVisiblePrice.enabled) {

                    crop = points[points.length - 1].x === x ? 1 : 2;

                    yAxis.crosshair = yAxis.options.crosshair = merge({color: 'transparent'}, seriesOptions.lastVisiblePrice);

                    yAxis.cross = serie.lastVisiblePrice;
                    lastPoint = points[points.length - crop];
                    // Save price
                    yAxis.drawCrosshair(null, lastPoint);

                    serie.lastVisiblePrice = yAxis.cross;
                    if (serie.lastVisiblePrice  !== undefined)
                        serie.lastVisiblePrice.y = lastPoint.y;

                    if (serie.crossLabel) {
                        serie.crossLabel.destroy();
                    }

                    serie.crossLabel = yAxis.crossLabel;
                }

                // Restore crosshair:
                yAxis.crosshair = origOptions;
                yAxis.cross = origGraphic;
                yAxis.crossLabel = origLabel;
            }
        });
    }(Highcharts));
```

**Comment by KacperMadej** [comment]
Hi @javaguru 

Thank you for reporting about the error and for suggesting the solution / workaround.

**Comment by sebastianbochan** [comment]
Hi @javaguru,
I tested the demo like below and was not able to reproduce the issue (no errors).

![indicator](https://user-images.githubusercontent.com/2115686/51322714-7dbc7580-1a66-11e9-99f5-ad98275a12af.gif)


Could you update the demo, with your extremes which causes issue. 
- https://jsfiddle.net/BlackLabel/rz1Ld6b2/

Would be great to set static width of chart (in pixels).

Tested:
- Chrome 71.0.3578.98
- MacOSX: 10.12.4

**Comment by javaguru** [comment]
I have updated your demo with range 1484749800000 - 1490016600000 here:
https://jsfiddle.net/javaguru/sa1ecovL/1/

**Comment by sebastianbochan** [comment]
Hi @javaguru,
Thank you for the feedback.
The reason of the bug is that you set extremes on the range where points do not exist.

You set start of range as:1147651200000  but data is since: 1484663400000.

Anyway I agree that the `price-indicator.js` should verify the length of points. I will fix it as soon as possible.

**Comment by javaguru** [comment]
Hi!
In fact you cannot save last price if your range selected is under the last price based on yAxis  (in your example 152,29) 

With data:
https://jsfiddle.net/javaguru/sa1ecovL/5/

**Comment by sebastianbochan** [comment]
Hi @javaguru,
Could you elaborate this point? When I run the last demo, I see correct values:
![zrzut ekranu 2019-01-18 o 13 03 45](https://user-images.githubusercontent.com/2115686/51386112-a6ee0c00-1b21-11e9-8f94-44146930bb2a.png)
![zrzut ekranu 2019-01-18 o 13 03 50](https://user-images.githubusercontent.com/2115686/51386118-aa819300-1b21-11e9-9a48-d7bce051d677.png)

Do you mean that the last price should not be visible when points are missing like below?
![zrzut ekranu 2019-01-18 o 13 05 20](https://user-images.githubusercontent.com/2115686/51386148-c38a4400-1b21-11e9-89af-1703a756df76.png)

**Comment by javaguru** [comment]
Hi @sebastianbochan!

Please, replay my demo, set the range and try to display the last price for see the exception:
https://jsfiddle.net/javaguru/sa1ecovL/5/

Red line cannot be rendered, normal, because yAxis is under 152,29, so serie.lastPrice.y (from yAxis.cross) cannot be saved at this time. But label last Price can be rendered, based on last point.y from selected range (like I can see on your second screenshoot)

I hope that it is more clear now..

![image](https://user-images.githubusercontent.com/3924532/51386993-b3c02f00-1b24-11e9-8626-9c1e46eb56e1.png)

**Comment by javaguru** [comment]
@sebastianbochan  perfect! :)

Just a small request! ;)
Can you add a numberFormat for the lastPrice label, please ? I cannot find in the doc the way to format this label..

**Comment by sebastianbochan** [comment]
Hi @javaguru,
Thank you.

For the feature request, please create a separate ticket to avoid confusions.
