### ISSUE TITLE
Highcharts solid gauge cannot update the pane.startAngle with the same initial value

### ISSUE THREAD

**Issue by karolinakuzniewicz** [highcharts/highcharts#9917]
#### Expected behaviour
Solid gauge should update the `pane.startAngle` and `pane.endAngle` values and rerender. 

#### Actual behaviour
By default and with mocked values the solid gauge renders properly with values `pane.startAngle = -270` and `pane.endAngle =  90` but while changing the values by selecting options `0, 90, 180, 270` all others besides the 270 value works and chart rerenders properly. Even though the chart is able to render by default with `pane.startAngle = -270` and `pane.endAngle =  90`, it's unable to update its with the same options. 

#### Live demo with steps to reproduce
https://jsfiddle.net/ka76rxwn/2/

#### Product version
Highcharts v7.0.1
#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @karolinakuzniewicz 

Thank you for reporting about the problem.

Pane update doesn't change chart options, so setting initial pane options will not work on update as it will run through cleanRecursively and will be identified as already in use and reduced.

**Workaround**:
Call update directly on the pane.
Demo: https://jsfiddle.net/BlackLabel/z5dhpsj3/

**Comment by karolinakuzniewicz** [comment]
Not sure if I can use the workaround in my stack, because it isn't jquery to handle the chart update so I'am looking forward to fix this. It seems to be a very strange bug only in this type of chart and idk why there is a possibility to handle the current chart's instance by `chart.pane` and `chart.pane[0]` with the same method `update` but apparently implemented different for these two ones.

**Comment by KacperMadej** [comment]
`chart.pane` is an array of panes. Each pane has update method that should handle updating chart options, but it doesn't - that's the bug.

**Comment by karolinakuzniewicz** [comment]
I just don't know why this is implemented this way that `this.chart.pane` is an Array but `this.chart.userOptions.pane` is an Object defined exactly as in doc and that's why `this.chart.update(Object.assign({}, options: Highcharts.Options))` won't update the `this.chart.pane` what is the Array. It makes no sense if from the doc there is only one pane Object and I think that the clue of the issue - the inconsistent types.
![zrzut ekranu 2019-01-17 o 14 03 53](https://user-images.githubusercontent.com/13152501/51321299-ae021500-1a62-11e9-8207-5217955bc456.png)
![zrzut ekranu 2019-01-17 o 14 03 27](https://user-images.githubusercontent.com/13152501/51321300-ae021500-1a62-11e9-96c9-0c66640e328a.png)
