### ISSUE TITLE
Number as string

### ISSUE THREAD

**Issue by username1565** [highcharts/highcharts#9930]
#### Expected behaviour
String value on the chart.

#### Actual behaviour
https://www.highcharts.com/errors/14/
>String value sent to series.data, expected Number
>This happens if you pass in a string as a data point, for example in a setup like this:
>```javascript
>series: [{
>	data: ["3", "5", "1", "6"]
>}]
>```
#### Live demo with steps to reproduce
http://jsfiddle.net/has0ufpk/
line 39.
Replace
```javascript
v[i] = [x[i], y[i]];
```
to
```javascript
v[i] = [x[i], (y[i]).toFixed(8)];
```
#### Product version
https://code.highcharts.com/highcharts.src.js

#### Affected browser(s)
All browsers
______________________________________________________________
Hello.
I try to display bitcoin satoshies on the charts.
This have values, like `0.00000001`,
but on the chars I can see `1e-8`, if there is numbers in array.
I want to tell "0.00000001" as string, to convert this string to number,
make point at 0.00000001, and display the string "0.00000001", not the number "1e-8".
Is this possible? I just get the error with code 14.

You can see this trouble here: http://jsfiddle.net/has0ufpk/
PV = 0.00000010
Rate = 10%
Years = 50
and press "Plot"-button

I see here: https://code.highcharts.com/highcharts.src.js
at line 13034, the following string:
```javascript
pointFormat: '<span style="color:{point.color}">\u25CF</span> {series.name}: <b>{point.y}</b><br/>',
```
Maybe need to add something, like this
```javascript
console.log(
	(0.00000001)			/*1e-8, float number*/,
	(0.00000001).toFixed(8)		/*"0.00000001" string output, not number*/
);
```
_______________________
Best regards.

**Comment by username1565** [comment]
Good, thanks. But... Fix e.preventDefault() warning too.

**Comment by TorsteinHonsi** [comment]
Thanks! I don't see the warning myself, but I added a condition as it seems this returnValue is only needed in IE8.
