### ISSUE TITLE
Piechart chart click does not work

### ISSUE THREAD

**Issue by nithyavanig** [highcharts/highcharts#9931]
#### Expected behaviour
Piechart - chart click event does not work.
chart : {
click: function(e){}
}
When clicked outside the plotarea of piechart , this event should be triggered.
#### Actual behaviour
This chart click event is not triggered onclick outside plotarea. Click event inside plotOptions -> pie works fine , but that is for plotarea. 

#### Live demo with steps to reproduce
https://jsfiddle.net/nithivani86/fujwmnt0/2/

#### Affected browser(s)
All browsers

**Comment by sebastianbochan** [comment]
Hi @nithyavanig,
The problem is caused by the wrong configuration. The `click` event should be placed in the `chart` object.

```
  chart: {
    plotBackgroundColor: null,
    plotBorderWidth: null,
    plotShadow: false,
    type: 'pie',
    events: {
      click: function(e) {
        console.log("hello");
      }
    }
  },
```

**Fixed demo:**
- https://jsfiddle.net/BlackLabel/bxdLz2nq/
