### ISSUE TITLE
Highmaps datalabel in front of tooltip if useHTML is true

### ISSUE THREAD

**Issue by DK-Unit4** [highcharts/highcharts#9935]
#### Expected behaviour
The tooltip is over data labels

#### Actual behaviour
The tooltip is behind the data label

#### Live demo with steps to reproduce
https://jsfiddle.net/Kumlander/w3yLh8as/

point to any map area to show tooltip

#### Product version
latest

#### Affected browser(s)
I tested with Chrome
![hm](https://user-images.githubusercontent.com/38954233/51386436-0d2b5c80-1b2b-11e9-84c6-6608128b83fd.PNG)

**Comment by KacperMadej** [comment]
Hi @DK-Unit4 

Thank you for contacting us about the problem.

Labels are created as HTML elements placed over SVG chart, so to have tooltip over them you need to use full HTML tooltip - API reference: https://api.highcharts.com/highcharts/tooltip.useHTML

or set outside in tooltip to true - demo: https://jsfiddle.net/BlackLabel/wm78ys6z/
API reference: https://api.highcharts.com/highcharts/tooltip.outside

This doesn't look like a bug.
Is your problem resolved now and we could close the issue?

**Comment by TorsteinHonsi** [comment]
It's a known issue, see https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting
