### ISSUE TITLE
Adding ability to pass default options within Annotations bindings

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#9938]
#### Expected behaviour
Annotation default options should be configurable in some way, for example there should be `defaultOptions` API option in every annotation binding, which would give user ability to set custom parameters.

#### Actual behaviour
It's not possible to add annotation default options, using `navigation.bindings`. Currently, the only way to to achieve it, is by overriding existing `start()` function and change the object passed to the `addAnnotation` function.

**Comment by pawelfus** [comment]
*Internal note:*
It's a general improvement for bindings (not only in Highstock).

**Comment by pawelfus** [comment]
That will limit us to one config for all annotations. On the binding level we could provide default options for each annotation:

```
navigation: {
  bindings: {
    circleAnnotation: {
      className: ...
      start: ...
      steps: [ ... ],
      end: ...
      annotationOptions: { 
          // default options here
      }
    }
  }
}
```

How about both? General options and `navigation.bindings[bindingName].options`? In that case name probably should start with `bindings` prefix for general options, so it will be clear for users it's bindings only.

**Comment by Denyllon** [comment]
Sounds great, and would be consistent with current approach of setting options within `series` and globally for all series in `plotOptions.series`.
Regarding the naming of both options, I propose to call the global parameter by `annotationsOptions`, and `annotationOptions` for every specific one, or just `annotationOptions` in both cases. Prefixing the names with `bindings` would be unnecessary, because either way all configurations are assigned to `bindings:` key. What do you think?

**Comment by TorsteinHonsi** [comment]
Yes, agreed 👍

**Comment by Svancara** [comment]
Can I have a qustion re this?
Will this allow to "persist" a user defined annotations using Stock Tools?
I plan to use Stock Tools and I need to store and recreate a user defined stuff later.
Or - in other words - will I be able to define some Stock Tools stuff (say some lines) in options and a chart will be shown including that stuff then?
Thank you.

**Comment by pawelfus** [comment]
Hi @Svancara 

All annotations are always available in `chart.annotations`. You can get them, for example:

```javascript
var annotationOptions = [];

chart.annotations.forEach(function (annotation) {
  annotationOptions.push(annotation.userOptions);
});
```

Now simply send `annotationOptions` array to the backend and store them. Later when user revisit your page, you simply use that array of annotations when creating chart:

```javascript
Highcharts.chart('container', {
    ...
    annotations: annotationOptions,
    ...
});
```

**Comment by pawelfus** [comment]
@sebastianbochan - can we make this in v7.1?

**Comment by sebastianbochan** [comment]
I hope that will be ready for 7.1, start today.
