### ISSUE TITLE
Incorrect yAxis extremes adjustment after zooming xAxis with column series type

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#9944]
#### Expected behaviour
yAxis with linked column series should adjust its extremes basing only on visible data.

#### Actual behaviour
After zooming the xAxis into some range, yAxis extremes are also adjusted, but they aren't focus just on the currently visible min and max data values. yAxis Extremes are calculated including the first points values, which are outside of visible xAxis range.

#### Live demo with steps to reproduce
yAxis not adjusted:
![yaxisnotadjusted](https://user-images.githubusercontent.com/15111955/51399952-7b7e1800-1b47-11e9-8e72-b95cb98babcf.gif)

yAxis adjusted:
![yaxisadjusted](https://user-images.githubusercontent.com/15111955/51400119-e4659000-1b47-11e9-8d8f-50183fca4404.gif)

https://jsfiddle.net/BlackLabel/kqzn2wc0/ 
_Uncomment the IIFE function on the top of the script in order to see how it should behave._
#### Product version
Highcharts

_**Internal Note:**
It happens because of `shoulder` parameter set within the `series.getExtremes()` function, which is set as `1`, when the series require sorting. Is really `requiredSorting` needed to be enabled on column series?_

Probably refers to #7061

**Comment by KacperMadej** [comment]
Looks like `requiredSorting` is needed. With the suggested fix try to zoom between two points - nothing is drawn and yAxis lost it's scale.
Demo: https://jsfiddle.net/BlackLabel/kqzn2wc0/4/

A solution here might require checking if a column point that is just outside of xAxis min-max range is visible (so should be included) or not visible (so shouldn't be included). 

Right now looks like the code works like that when pointPadding and groupPadding are zeroed. 
Demo: https://jsfiddle.net/BlackLabel/kqzn2wc0/5/ 
Or can you get a zoom / xAxis range that will not show the first point and still calculate yAxis extremes based on it?

**Comment by Denyllon** [comment]
> Looks like requiredSorting is needed. With the suggested fix try to zoom between two points - nothing is drawn and yAxis lost its scale.
Demo: https://jsfiddle.net/BlackLabel/kqzn2wc0/4/

What about the situation if we would change the `series.type` to `scatter`. It also has the `requireSorting` disabled, and the result is the same (yAxis scale is lost). Maybe the `shoulder` value calculations shouldn't be based on `requireSorting` series property at all?

**Comment by KacperMadej** [comment]
A problem with column series is that axis padding is added (equal to series' pointRange on both ends), so it looks like set extremes (e.g. through min and max) are not fully respected and columns should be rendered, but chart is empty - https://jsfiddle.net/BlackLabel/kqzn2wc0/8/

This is a bug, but the suggested solution will break more than it will fix - there must be another way. Like you wrote - maybe a different (new?) property should be used because for column series we need to keep requireSorting and change requireSorting at the same time.

**Comment by TorsteinHonsi** [comment]
I think the `cropThreshold` is also a key here. When setting it to 1, we're cropping away points that fall outside the zoomed area, and they are not taken into consideration when computing extremes: https://jsfiddle.net/highcharts/xevgoLq8/2/
