### ISSUE TITLE
Cannot read property 'forEach' of undefined, points array is undefined, highcharts 6->7

### ISSUE THREAD

**Issue by kfir124** [highcharts/highcharts#9946]
#### Expected behaviour
First check if points is an array before trying to `.forEach` it

#### Actual behaviour
When trying to `.addSeries` to highcharts' chart I am getting an error `Cannot read property 'forEach' of undefined`.
It seems like the points array is undefined at this point.
This is the code that breaks in highcharts: (line 417 in the minimized version)
`(this.series || []).forEach(function(c) {
                var r = c.options.dataLabels;
                c.visible && (!1 !== r.enabled || c._hasPointLabels) && c.points.forEach(function(c) {
                    c.visible && (F(c.dataLabels) ? c.dataLabels : c.dataLabel ? [c.dataLabel] : []).forEach(function(g) {
                        var d = g.options;
                        g.labelrank = h(d.labelrank, c.labelrank, c.shapeArgs && c.shapeArgs.height);
                        d.allowOverlap || a.push(g)
                    })`

The failing line is ` c.visible && (!1 !== r.enabled || c._hasPointLabels) && c.points.forEach(function(c) {`

Changing `&& c.points.forEach` with `&& (c.points || []).forEach` fixes this issue and allows highcharts to function normally.

#### Live demo with steps to reproduce
I didn't have much success in reproducing it in a fiddle, not sure why, my code is working in highcharts 6.1.0. upgrading to highcharts 7.0.2 caused this bug to appear.
changing `points.forEach` with `(points || []).forEach` will fix it with no downsides (didn't see any at least)

#### Product version
Highcharts 7.0.2 (was working in 6.1.0)

#### Affected browser(s)
Probably all, checked in chrome 70

#### Question
Why is this happening? is there a workaround except modifying highcharts to not fail when points array is undefined? why is it undefined? I do have data in that series.
It seems like it doesn't even need to run at this point since adding ` || []` will make the graph to work and be totally fine

**Comment by KacperMadej** [comment]
Hi @kfir124 

Thank you for reporting about the problem, however I'm unable to recreate the issue - http://jsfiddle.net/BlackLabel/e20uLq48/ , http://jsfiddle.net/BlackLabel/e20uLq48/1/
Please provide a live demo for the problem.

For debugging you could use Highcharts related files with `.src.js` suffixes to work with un-minimized, readable for humans code.

**Comment by KacperMadej** [comment]
> However I've found that this is a timing issue, if you try to chart.addSeries() before the chart got a chance to fully initiate it will crash your website with that error.

Could you let me know when are you adding a series to cause the crash? Maybe there's some king of infinite loop going on. E.g. adding series on chart's render event will cause infinite loop - demo (the loop is prevented there): http://jsfiddle.net/BlackLabel/e20uLq48/6/

We could consider improvements as soon as the issue will be reproduced - right now we don't know what should be improved.

**Comment by bre1470** [comment]
There is definitely a bug. By definition the points property on a series should never be undefined. 

@kfir124
If you could send us the (call) stack of the thrown error, this would really help to have an idea what is going on in Highcharts. Thank you!

**Comment by kfir124** [comment]
@KacperMadej  So I am using angular4 + angular-highcharts npm package.
What happens is that I set some options for the table (as an object), and when that object is updated it automatically updates the chart as well, I listen to the `(load)` event of the chart before doing anything so it did got a chance to load at start, then I get the chart object itself from the context of the load event and before adding a series to it I first update some options for the chart (I create a new object with a different title for example and other different options and set the older object pointer to point to this new object) I still didn't explicitly called chart redraw so I didn't think something would have changed, then I add `chart.addSeries()` then I crash, in normal flow after that I call `chart.redraw()` but after the update I already crashed on `chart.addSeries`

@bre1470 yes I will attach

**Comment by kfir124** [comment]
@bre1470 Ok so I've found that it worked in **6.1.4** started to break in **6.2.0** (didn't see official release for 6.1.5 6.1.6 6.1.7 ...) the error has different wording but it is the same error:

> ERROR TypeError: Array.prototype.forEach called on null or undefined
>     at forEach (<anonymous>)
>     at H.each (highcharts.src.js:2285)
>     at highcharts.src.js:41232
>     at Array.forEach (<anonymous>)
>     at H.each (highcharts.src.js:2285)
>     at H.Chart.collectAndHide (highcharts.src.js:41225)
>     at highcharts.src.js:2538
>     at Array.forEach (<anonymous>)
>     at Object.H.each (highcharts.src.js:2285)
>     at H.fireEvent (highcharts.src.js:2507)

Expanded:
> 
>  // #3866
> 		            each(series.points, function (point) {
> 		                if (point.visible) {
> 		                    var dataLabels = (
> 		                        isArray(point.dataLabels) ?
> 		                        point.dataLabels :
> 		                        (point.dataLabel ? [point.dataLabel] : [])
> 		                    );

**Comment by kfir124** [comment]
@bre1470 no problem!, I noticed that the (load) event called twice, probably the package I use kills and re-renders the chart when I change the options which means that the bug only happens when you try to `chart.addSeries()` before the `(load)` event has happened, which makes this bug almost irrelevant for most cases but it is weird that it worked in 6.1.4.

**Comment by bre1470** [comment]
I am sorry, but I am neither able to reproduce this. What I noticed is though, that the wrapper in use is optimized for Angular v2 with Highcharts v5.0.15, so the chance is high, that there is proper event handling missing.

We at Highsoft changed during the development of v6 the internal way, how Highcharts gets informed about changes and made this a public API with v7. This might be a core problem for the outdated wrapper. I suggest you should give our official wrapper a try, to avoid a trap with outdated versions of Angular and Highcharts.

**Comment by kfir124** [comment]
Thanks I will

**Comment by KacperMadej** [comment]
The main difference between the official and 3rd party wrapper is that the first uses chart.update and the second one is rebuilding the chart. The second approach is less optimal (take more resources and more time). I tried to recreate the problem by creating a new chart on in the same place (so the old one will be destroyed), but I was not able to get the described error.

@kfir124 
If the problem is with the angular2-highcharts you should report this to it's creator on the wrapper GitHub repository. We could help with debugging if we'll have a live demo to work with.

**Comment by jonatanbaardsen** [comment]
Your demo for boosting a line chart with 600 series and 600000 values are not working with the error mentioned by @kfir124 . Link: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/boost/line-series-heavy/
I have the same problem.

**Comment by KacperMadej** [comment]
@jonatanbaardsen 
Please provide more info about the problem in the demo. It works fine for me. Tested on Windows 10 / Chrome.

**Comment by saravanan1982** [comment]
I have same problem when I am using dynamic gauge and line charts but it works well when I am using column, bar, line spline, area. please refer below attached details.

![screencapture-localhost-3000-devices-2019-03-26-19_33_18](https://user-images.githubusercontent.com/48954617/55003292-230f3f00-4ffe-11e9-9f76-18922df1e416.png)
![StaticShot_26-03-2019_19-32-57](https://user-images.githubusercontent.com/48954617/55003295-23a7d580-4ffe-11e9-992d-e9f356a8daaa.png)

**Comment by KacperMadej** [comment]
@saravanan1982 
Please create a live demo for the problem and since we have difficulties recreating the problem please also provide info about used browser and OS.

**Comment by sebastianbochan** [comment]
@saravanan1982 
Have you tried to add `oldie` module ?

Ref:
- https://code.highcharts.com/modules/oldie.js

**Comment by saravanan1982** [comment]
Thank you for support

I fixed that issue after I removing the highchart npm import in parent component but it introduced another issue.

I used activity gauge chart in dashboard page and solid gauge in trending page whenever I navigate to trending page and back to dashboard the activity gauge colors are collapsed like below
![download](https://user-images.githubusercontent.com/48954617/55074759-27e3f980-50b7-11e9-9191-7d813de454d8.png)

In the console log I got below error:
![Screenshot from 2019-03-27 17-41-03](https://user-images.githubusercontent.com/48954617/55074913-9032db00-50b7-11e9-9a3f-ebf7c231ee3a.png)

**OS & Browser:**
OS: Ubuntu 16.04
Browser: Chrome Version 71.0.3578.80

Let me know what is cause of this issue.

**Comment by sebastianbochan** [comment]
Hi @saravanan1982,
Please let us know about live demo and how we can reproduce the problem. 

At this moment there can me many reasons of the issue and without the demo we are not able to debug.

**Comment by saravanan1982** [comment]
As of now I don't have live demo setup. So, I attached react source code. just you extract and try with yarn install && yarn start to check it.

[gauge.zip](https://github.com/highcharts/highcharts/files/3013386/gauge.zip)

Thanks!

**Comment by KacperMadej** [comment]
You have loaded solid-gauge multiple times and the code in the module is being applied multiple times. You could add a check before initializing a module to be sure if it's needed or not.

Loading the same module multiple times with any errors was previously recognized as a bug, so this should also be a bug. This issue is long and your error looks a bit unrelated and like it deserves a new issue, so let's keep this issue closed. Your problem is already reported here: https://github.com/highcharts/highcharts/issues/10293

Before reopening that issue let's wait for release of version 7.1.0 (should happen today).

**Comment by prevostc** [comment]
With some fiddling around, I found that when I cross the 5000 points threshold, I get the error.

I found out that `Highcharts More` is not compatible with the boosting mecanism (https://www.highcharts.com/forum/viewtopic.php?t=36109)

This config solved my issue:

```
boost: {
    enabled: false
}
```

**Comment by KacperMadej** [comment]
Hi @prevostc 

You are referring to a forum topic from 2016, so it might not be up to date with the current state of the code.

Please add a live demo with the problem visible if you would like us to check the problem.

**Comment by prevostc** [comment]
Hi @KacperMadej I tried, but I could not :s
https://codesandbox.io/s/quizzical-cohen-ugv17

I don't know what differs from my local setup at this point :)

**Comment by papirosko** [comment]
> redra

got exactly the same issue.
just do not call `chart.redraw()`,
use: 


```
chart.addSeries({
            {...},
            true,
            false
        );
```

(param `redraw` is set to `true`). If you have multiple series, the set `redraw` to `true` only on last serie.

**Comment by GeekSMN** [comment]
We appear to be seeing the issue as well with 7.2.1 at a customer site and the result is charts failing to render 

![highcharts9946](https://user-images.githubusercontent.com/7537059/110974844-fceb2280-832c-11eb-8e3c-f8fa9729b419.png)

**Comment by KacperMadej** [comment]
@GeekSMN 
Please add a live demo of the problem.

In general, when a problem is not possible to reproduce in a newer version of Highcharts the solution will be to upgrade Highcharts, so you might as well already test a newer version of Highcharts.

**Comment by MasoumeAfshar** [comment]
use this, 
I got same error and fix it with this

` <HighchartsReact
    options = { chartOptions }
    highcharts = { Highcharts }
    allowChartUpdate = { false }
    immutable = { false }
  />`
[https://github.com/highcharts/highcharts-react#optimal-way-to-update](url)

>
