### ISSUE TITLE
Variwide is not listed in Typescript definitions

### ISSUE THREAD

**Issue by anathematic** [highcharts/highcharts#9948]
#### Expected behaviour

Use of Type Variwide charts in Typescript:

```typescript
    const options: Highcharts.Options = {
      chart: {
        type: 'variwide',
      },
   }
```

#### Actual behaviour

An exception from Typescript.

```
Type error: Type '{ type: "variwide"; }' is not assignable to type 'ChartOptions'.
  Types of property 'type' are incompatible.
    Type '"variwide"' is not assignable to type '"column" | "area" | "arearange" | "areaspline" | "areasplinerange" | "bar" | "boxplot" | "bubble" | "columnrange" | "errorbar" | "funnel" | "gauge" | "heatmap" | "line" | "pie" | ... 7 more ... | undefined'.  TS2322
```

#### Live demo with steps to reproduce
This bug has been isolated to [this dummy app](https://github.com/anathematic/HighchartsTypescriptVariwide), should be easy enough to replicate!

#### Product version

On Highcharts 7.0.2

#### Anything else?

✅Thanks team! I've made a PR on [Highcharts Declarations Beta](https://github.com/highcharts/highcharts-declarations-beta/pull/32) - it seems that doesn't apply to Highcharts 7.x.

**Comment by bre1470** [comment]
Thank you for your feedback! This is a duplicate of #9810 and will be changed to type `string` with Highcharts v7.1.

Nevertheless the option is not really supported in the way TypeScript works and therefor is nearly useless. Instead use `plotOptions.variwide.type` and `series.variwide.type`.

Workaround in customer code:
```
{
    chart: {
        type: 'variwide' as any;
        // Option has no effect in TypeScript typing, use `plotOptions.variwide.type`
        // and `series.variwide.type`.
    }
}
```

**Comment by anathematic** [comment]
I can confirm that fixed the issue - thankyou!

For some reason I was under the impression `chart.type` was required, knowing it isn't this feedback makes sense! Closing!
