### ISSUE TITLE
code.highcharts.com should mention the v7+ styled mode deprecation

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#9949]
The [Upgrade Note about styled mode](https://www.highcharts.com/blog/changelog/#highcharts-v7.0.0) should probably be mentioned at https://code.highcharts.com.

**Comment by TorsteinHonsi** [comment]
Absolutely. Plus we should mention that ES modules are also served from code.highcharts.com.

**Comment by jon-a-nygaard** [comment]
Thanks again for reporting. code.highcharts.com is now updated with information about `chart.styledMode` and our ECMAScript modules.

I consider this issue fixed and will close it. If you should have any further comments or suggestions please feel free let us know.
