### ISSUE TITLE
AxisEventCallbackFunction mismatch in TypeScript

### ISSUE THREAD

**Issue by mcenkar** [highcharts/highcharts#9958]
#### Expected behaviour
TypeScript compiles AxisEventCallbackFunction correctly.

#### Actual behaviour
Right now AxisEventCallbackFunction is defined as:

```export type AxisEventCallbackFunction = (this: Axis) => void;```

however it looks like it should take `AxisSetExtremesEventObject` as parameter, rather than `Axis`.

#### Live demo with steps to reproduce
https://jsfiddle.net/6pw50e2d/

```
    xAxis: {
      events: {
          afterSetExtremes: ((event: Highcharts.AxisSetExtremesEventObject) => {
          }) as any,
        }
    },
```

Remove `as any` from above, you will get compilation error.
#### Product version
Highcharts 7.0.2

**Comment by sebastianbochan** [comment]
Hi @mcenkar,
Thank you for reporting.

FYI @bre1470
