### ISSUE TITLE
Docs diff on SVGRenderer#label

### ISSUE THREAD

**Issue by jonfreedman** [highcharts/highcharts#9961]
The documentation states that [SVGRenderer#label](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#label) has two shape parameters but the source code & Typescript definition suggests otherwise:
 * https://github.com/highcharts/highcharts/blob/master/js/parts/SvgRenderer.js#L4732

**Comment by jonfreedman** [comment]
shape is listed in the docs twice, that function signature has 9 arguments...

**Comment by pawelfus** [comment]
@sebastianbochan I think this is the problem: 

https://github.com/highcharts/highcharts/blob/e1527579cfefba28725da162807e1849a76cd51c/js/parts/SvgRenderer.js#L4700-L4709

**Comment by sebastianbochan** [comment]
Fixed, thanks @pawelfus.
