### ISSUE TITLE
Boost - line series is invisible if the points are outside the visible part of the plot area

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#9962]
#### Expected behaviour
The chart should look like without the boost module:
http://jsfiddle.net/BlackLabel/ryLqx7ku/

#### Actual behaviour
The line series is invisible which causes inconvenience when zooming.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/L73x6f5e/

#### Product version
Highcharts v7.0.2

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
@cvasseng When non-boosted, Highcharts looks at the first items before and after the visible range in order to draw the line correctly.

**Comment by lehmannsystems** [comment]
Any updates on this bug?  Thanks!

**Comment by pawelfus** [comment]
Hi @lehmannsystems 

Please check this solution: http://jsfiddle.net/BlackLabel/L73x6f5e/12/

You can test the solution in your own environment:
```
<script src="http://code.highcharts.local/highcharts.js"></script>
<script src="http://code.highcharts.local/modules/boost.js"></script>
```

**Comment by lehmannsystems** [comment]
That works @pawelfus !  I use Highstock... will the change be made in there as well?
Thank you!

**Comment by pawelfus** [comment]
If PR will get merged, then yes, see demo for Highstock: http://jsfiddle.net/BlackLabel/L73x6f5e/15/

**Comment by lehmannsystems** [comment]
Awesome thank you!
