### ISSUE TITLE
Graph doesn't load when tab is not focusing

### ISSUE THREAD

**Issue by ragmar** [highcharts/highcharts#9963]
#### Expected behaviour
See the complete graph

#### Actual behaviour
Graph is failing to initialize, and the console is thorwing the error Uncaught TypeError: Cannot read property 'pos' of undefined

#### Live demo with steps to reproduce
http://jsfiddle.net/ragmar/64fgb5m3/

- Open this fiddle in a new browser tab.
- Change the browser tab to any other, except the fiddle just opened.
- Right click the fiddle browser tab, and click reload page.
- Wait for it to load without focusing the browser tab.
- Open the fiddle browser tab.
- Graph does not appear, error in console

All this also work if you refresh and change the browser tab while the page is loading

NOTE: No error happen if you have opening the browser tab and wait for it to load, you need to change the browser tab

#### Product version
Highcharts 7.0.2 and drilldown 7.0.2

#### Affected browser(s)
IE, Chrome, Firefox, Edge

**Comment by KacperMadej** [comment]
Hi @ragmar 

Thank you for reporting about the problem.
It's already resolved on master branch (next release candidate).
See more info in the main thread - https://github.com/highcharts/highcharts/issues/7872
Closing this issue as a duplicate.
