### ISSUE TITLE
Margin of empty title is taken into account

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#9964]
#### Expected behaviour
When legend is at the top ignore the title margin when there is no title

#### Actual behaviour
The title margin is taken into account when determining the top of the legend, even though there is no title.
Only when setting the title margin explicitly to 0, the title doesn't take up any space.

#### Live demo with steps to reproduce
https://jsfiddle.net/kzoon/pdLxt0vz/

Compare with the same fiddel on 5.0.14:
https://jsfiddle.net/kzoon/pdLxt0vz/1

#### Product version
Highcharts 6.0 and higher

**Comment by KacperMadej** [comment]
Hi @kzoon 

Thank you for reporting about the problem.

The issue is caused by legend position - without legend on top the chart doesn't have the extra margin.

**Comment by sebastianbochan** [comment]
**Internal note**
Bisects leads me to https://github.com/highcharts/highcharts/commit/3d35563
Related bug: https://github.com/highcharts/highcharts/issues/7428
