### ISSUE TITLE
Typescript: Axis Labels not typed as per specs

### ISSUE THREAD

**Issue by GeorgeBark** [highcharts/highcharts#9966]
#### Expected behaviour
In https://api.highcharts.com/highcharts/xAxis.labels.overflow it says that the property can be boolean or string:

```
overflow: boolean, string
How to handle overflowing labels on horizontal axis. If set to "allow", it will not be aligned at all. By default it "justify" labels inside the chart area. If there is room to move it, it will be aligned to the edge, else it will be removed.

Defaults to justify.
```

And, when set to false, it just overlaps the labels (this is the current behavior).

#### Actual behaviour

In the typesctipt definitions, it is forced to be either "allow" or "justify", throwing an error when set to false:

```
    /**
     * (Highcharts, Highstock, Highmaps, Gantt) How to handle overflowing labels
     * on horizontal axis. If set to `"allow"`, it will not be aligned at all.
     * By default it `"justify"` labels inside the chart area. If there is room
     * to move it, it will be aligned to the edge, else it will be removed.
     *
     * @see https://api.highcharts.com/highcharts/xAxis.labels.overflow
     * @see https://api.highcharts.com/highstock/xAxis.labels.overflow
     * @see https://api.highcharts.com/highmaps/xAxis.labels.overflow
     * @see https://api.highcharts.com/gantt/xAxis.labels.overflow
     */
    overflow?: ("allow"|"justify");
```

#### Product version
"highcharts": "^7.0.2",

**Comment by sebastianbochan** [comment]
Hi @GeorgeBark,
Thank you for reporting.

FYI @bre1470

**Comment by bre1470** [comment]
Boolean is for backwards compatibility only.

**Comment by bre1470** [comment]
Actually boolean should be removed from the documentation.

**Comment by GeorgeBark** [comment]
And if it is only for backward compatibility, how do I make the labels overlap without the boolean?

**Comment by bre1470** [comment]
You should set it to `allow`.
