### ISSUE TITLE
Can the color attribute in a function be replaced with an image?

### ISSUE THREAD

**Issue by chengheai** [highcharts/highcharts#9977]
#### Expected behaviour
	function (e) {
		var colors = Highcharts.getOptions().colors,
			i = 0,
			nodes = {};
		e.options.data.forEach(function (link) {
			if (link[0] === 'Proto Indo-European') {
				nodes['Proto Indo-European'] = {
					id: 'Proto Indo-European',
					marker: {
						radius: 40
					}
				};
				nodes[link[1]] = {
					id: link[1],
					marker: {
						radius: 10
					},
					color: colors[i++]
				};
			} else if (nodes[link[0]] && nodes[link[0]].color) {
				nodes[link[1]] = {
					id: link[1],
					color: nodes[link[0]].color
				};
			}
		});
		e.options.nodes = Object.keys(nodes).map(function (id) {
			return nodes[id];
		});
	}
Can the color attribute in a function be replaced with an image?
#### Actual behaviour

Can the color attribute in a function be replaced with an image?
#### Live demo with steps to reproduce

Can the color attribute in a function be replaced with an image?
#### Product version

Can the color attribute in a function be replaced with an image?
#### Affected browser(s)
Can the color attribute in a function be replaced with an image?

**Comment by sebastianbochan** [comment]
Hi @chengheai,
The github is our bug tracker. For general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.

**Comment by chengheai** [comment]
@pawelfus Something like this：
https://github.com/chengheai/review-demo-image/blob/master/demo.jpg?raw=true

**Comment by chengheai** [comment]
@pawelfus  thank you very much👅
