### ISSUE TITLE
Horizontal scrollbar on "rtl" html when using "accessibility" plugin

### ISSUE THREAD

**Issue by hojovi** [highcharts/highcharts#9978]
When I use accessibility plugin in 'rtl' language, like 'ar-sa", there's an obvious horizontal scrollbar.
I found it came from this definition (screen-reader.src.js):
`hiddenStyle = {
        position: 'absolute',
        left: '-9999px',
        top: 'auto',
        width: '1px',
        height: '1px',
        overflow: 'hidden'
    };`

Is there any way to fix this? Hacky way is also fine.

**Comment by oysteinmoseng** [comment]
It seems to be working for me: http://jsfiddle.net/401xzkg9/

Are you able to reproduce the issue in a jsfiddle?

**Comment by hojovi** [comment]
@oysteinmoseng I've updated this link: [http://jsfiddle.net/401xzkg9/](url)
When you put the "dir" attribute in "html" tag, this bug happens.

**Comment by oysteinmoseng** [comment]
Here is a workaround, just removing the `left` positioning: http://jsfiddle.net/fe2uyv9j/2/

**Comment by TorsteinHonsi** [comment]
If you can't use `display:block`, our often-used way of hiding divs is to set a negative `top`, like `top:-999em`.

**Comment by hojovi** [comment]
I used css to resolve this problem, hope we can update to new version later to avoid this hacky way:
`#chart :nth-child(-n+2) { left: -9999px;}`
`html[dir=rtl] #chart :nth-child(-n+2) { right: -9999px;}`

**Comment by oysteinmoseng** [comment]
The fix should be part of the next maintenance release
