### ISSUE TITLE
Click event not fire in highcharts tooltip

### ISSUE THREAD

**Issue by snd1890** [highcharts/highcharts#9986]
Tooltip work proper but when i add a(anchor) tag in tooltip not working proper

#### Live demo with steps to reproduce
http://jsfiddle.net/vxnq3578/3/ 
http://jsfiddle.net/quvaepad/3/

#### Product version
Highstock JS v7.0.2

**Comment by sebastianbochan** [comment]
Hi @snd1890,
Thank you for reporting. There a few reasons of the issue:

- by default all events are reset on container
- events are triggered from the one level not bubbled
- tooltip is created "on the fly", so your jQuery has reference to object which does not exist.
- mixing SVG / HTML elements does not allow you to use CSS `pointer-events` properly.

**Workaround:**
The solution can be using Highcharts in [style mode](https://api.highcharts.com/highcharts/chart.styledMode), apply `pointer-events: 'auto'` and run click event action inline.

```
return 'Please <a href="#" class="comment_triger" onClick="alert();">Comment</a> On <b>' + this.x +
          '</b> = <b>' + this.y + '</b>';
```

Demo:
- http://jsfiddle.net/BlackLabel/fbaydh4w/

**Comment by KacperMadej** [comment]
By default events for tooltip are prevented via CSS, so you could allow them through tooltip.style
Demo: http://jsfiddle.net/BlackLabel/4q9kga7e/1/

We have an option to allow this, so this doesn't look like a bug.
We should add docs about this.
