### ISSUE TITLE
Highstock annotations popup on small screen

### ISSUE THREAD

**Issue by frabanca** [highcharts/highcharts#9988]
Hi! 

I've been working with highstock last release (v. 7.0.2) and I noticed there is a small css bug on annotations popup on small screen. 

#### Some facts
If you start a new chart with all available indicators tools, you will end to have something like 40 tools. (Eg: SMA, Accumulation/Distribution, AO, Aroon, Aroon Oscillator, ATR, ...)

#### The Problem
The problem (Bug) is that if you have a chart height like 300px and you open the indicators popup, you cannot see all your tools because [official highcharts popup css](https://github.com/highcharts/highcharts/blob/master/css/annotations/popup.scss) prevent you from scrolling the popup. 

#### The solution
IMHO the solution is quite easy, just add the following css to your code:
```
.highcharts-popup {
  overflow-x: hidden;
  overflow-y: scroll;
}
```

Here is a codepen withe the bug and the corrections (just uncomment the commented css code):
[https://jsfiddle.net/nc8b21zv/4/](https://jsfiddle.net/nc8b21zv/4/)

**Comment by sebastianbochan** [comment]
Hi @frabanca,
Thank you for reporting. I will take care of this and fix as soon as possible.

**Comment by sebastianbochan** [comment]
Hi @frabanca,
Scrolls of the left and right columns are applied by default, but it was a bug in popup's height which stopped to display both of them.

The solution: 

```
.highcharts-popup {
    ...
    height: 90%;  
}
```

**Comment by frabanca** [comment]
All right, tested and worked. Thanks @sebastianbochan !
