### ISSUE TITLE
Navigator is broken while adding points when xAxis min and max are set.

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#9994]
#### Actual behaviour
Navigator is broken when we add points using addPoint() method when a chart is initialized with xAxis min and max set.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/1g3mtw02/

Add several points using `add points` button and keep an eye on the navigator.

#### Product version
Highstock

#### Affected browser(s)
all

**Comment by sebastianbochan** [comment]
**Workaround:**
Set the force flag in `navigator.series.dataGrouping`

Demo:
- https://jsfiddle.net/BlackLabel/5twgyfbr/

**Comment by TorsteinHonsi** [comment]
I'm sorry I'll have to revert this, as it causes a regression on range selectors being active even with no data in the series. Adding a test for that case in the upcoming commit.

@wchmiel Can you improve the fix to handle this case?

**Comment by wchmiel** [comment]
Sure, I'll improve it.

**Comment by wchmiel** [comment]
Ok, I checked it. In my opinion, my fix was correct because in `RangeSelector.updateButtonStates` when data is empty variables `dataMin` and `dataMax` should be `undefined` rather than equal axis extremes.

Imho the issue with buttons state is another bug and it is related with `hasNoData` variable, which is:

`hasNoData = !baseAxis.hasVisibleSeries`

So even when data is empty `hasNoData` is false because the series exists. For me it should be something like this:

```
if (baseAxis.hasVisibleSeries) {
  baseAxis.series.forEach(function(series) {
    if (hasNoData && series.yData.length) {
      hasNoData = false;
    }
  });
}
```

Now when there is a series with empty data `hasNoData = true`.

After this change, all buttons are disabled when data is empty and the behavior is exactly the same as when there is no series. So why buttons state should be [3, 3, 3, 0, 3, 2] when data is empty while [3, 3, 3, 3, 3, 3] when there is no series? In my opinion, the behavior should be the same. What do you think about it?
