### ISSUE TITLE
Export menu gets clipped if chart size is too small

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/highcharts#9998]
#### Expected behaviour
There should be an `outside` property for the export menu just like the recently added `outside` property for tooltips so that the export menu does not get clipped with small charts.

#### Actual behaviour
Export menu is clipped.

#### Live demo with steps to reproduce
Open export menus in demo: https://jsfiddle.net/lanimelrok/o2hbp46r/

#### Product version
Highcharts/Highstock 6.2.0

**Comment by KacperMadej** [comment]
Hi @LaniMoo 

Thank you for submitting the enhancement suggestion, but we are using UserVoice to better track the new ideas, so we could implement the most popular ideas faster.

https://highcharts.uservoice.com/forums/55896-general

Please use UserVoice, so this issue could be moved there - a new idea there, close the issue here.

**Comment by LaniMoo** [comment]
Is this an enhancement though? I actually thought it’s more like a bug... My suggestion was a recommendation of a fix for the bug. But let me know if I’ve been mistaken and I’ll move it to UserVoice. Thanks!

On Jan 26, 2019, at 2:06 PM, Kacper Madej <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @LaniMoo<https://github.com/LaniMoo>

Thank you for submitting the enhancement suggestion, but we are using UserVoice to better track the new ideas, so we could implement the most popular ideas faster.

https://highcharts.uservoice.com/forums/55896-general

Please use UserVoice, so this issue could be moved there - a new idea there, close the issue here.

**Comment by LaniMoo** [comment]
Awesome, no problem! Thank you!


On Jan 26, 2019, at 2:26 PM, Kacper Madej <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure, this could be seen as a bug. You have suggested a solution that would require implementing a precisely described feature, so I though that the main reason for the issue was to get the new feature implemented.

In this case, thank you for reporting about the bug and suggesting the solution :)
